### ISSUE TITLE
Silithus Herbalism Issues

### ISSUE THREAD

**Issue by WarlordXecc** [gamefreedomgit/Maelstrom#1012]
Same issue as Winterspring, I could not find any Black Lotus in this zone after picking it clean for 30 minutes. I suspect they are missing their Black Lotus spawns, I know Black Lotus are supposed to be rare but when you flying around at x20 speed and have entire zone for yourself I am pretty sure something is wrong. 
Considering Silithus and Winterspring basically has no changes at all to their layout between Wotlk and Cataclysm I think you could maybe just copy paste all the spawns from a 1.12/3.3.5 Core.

**Comment by WarlordXecc** [comment]
Still can't find any Black Lotus.

**Comment by UltraNix** [comment]
Fixed.
