### ISSUE TITLE
Stuck in combat because of training dummies

### ISSUE THREAD

**Issue by fytchx** [gamefreedomgit/Maelstrom#1025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you attack the training dummies in the human starting area, they keep you stuck in combat until you go far enough away from them

**How to reproduce:**

**How it should work:**
combat should drop after a few seconds of no attacking

**Database links:**

**Comment by Afgann** [comment]
fixed
