### ISSUE TITLE
Inside Building/city lag

### ISSUE THREAD

**Issue by Cryptmaw** [gamefreedomgit/Maelstrom#1026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While inside buildings/near structures, sever FPS drop and lag occurs.

**How to reproduce:**

**How it should work:**
No lag - same as it is in the outside world.

**Database links:**

**Comment by UltraNix** [comment]
@Cryptmaw Give us more info. What locations? Provide maybe some screenshots.

**Comment by Cryptmaw** [comment]
Hey there - I was questing with another guy in jasperlode mine - we both talked about whenever we entered a structure such as lions pride inn, stormwind, or the mine, we lagged incredibly hard, both in and out of party. I will say it has become better since the first 2 days.

**Comment by UltraNix** [comment]
No info - closing.
