### ISSUE TITLE
(Quest) Kyle's Gone Missing!

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1027]
[//]: # (REMEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Video of quest completion from relevant time: https://www.youtube.com/watch?v=Pvwzn3YyXxo&ab_channel=QtarGaming

**Description:** While on the quest, the player should be able to kill any Elder or Adult Plainstriders to loot Tender Strider Meat. This should be a 100% drop chance. I have killed at least 20(?) Plainstriders so far and have not gotten one.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=11129
Quest Item: https://cata-twinhead.twinstar.cz/?item=33009

**Comment by Afgann** [comment]
fixed
