### ISSUE TITLE
[QUEST] [an-ancient-enemy] npc dupes

### ISSUE THREAD

**Issue by Endofree1247** [gamefreedomgit/Maelstrom#1029]
**Description:**
NPC Zuni (id=38423) dupes after script death

**How to reproduce:**
Go to the quest an-ancient-enemy in Echo Islands, in final phase of the fight Zuni must die. But one of zuny fall on the floor and second continue fighting 
https://drive.google.com/file/d/1iHEKjxbhsirC134QqyarNqI63jQM3U_k/view?usp=share_link

**How it should work:**
Zuni must die, obliviously

**Database links:**
https://www.wowhead.com/quest=24814/an-ancient-enemy
https://www.wowhead.com/npc=38423

**Comment by Endofree1247** [comment]
Did this fight 3 times now, so may be it was a random bug, 2 more fights Zuni totally dies

**Comment by UltraNix** [comment]
It might be - cannot reproduce it.
