### ISSUE TITLE
(Quest) Call of Duty - Horde Vashj'ir starting quest

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1030]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 

Commander Thorak does not currently give the player the starting quest for the Vashj'ir storyline.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=25924
NPC: https://cata-twinhead.twinstar.cz/?npc=41621

**Comment by UltraNix** [comment]
Fixed
