### ISSUE TITLE
(Quest) As Hyjal Burns

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1031]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After jumping on Aronus and going through the Emerald Portal to Hyjal, the player is teleported to their hearthstone location. Instead, the dragon should still be carrying the player over the Sulfarian Spire for a small RP event. Trying to enter Mount Hyjal afterwards causes a disconnect and another teleport back to hearthstone location. 

Either the RP event should take place or the player should be teleported to Nordrassil (easier option I'd assume).

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=b8ZC0TzXVpU&ab_channel=TomSanGames
Quest: https://cata-twinhead.twinstar.cz/?quest=25316

**Comment by JadedNate** [comment]
Quest can now be completed as intended, however the pathing of Aronus isn't working properly and is very choppy (goes back and forth)

**Comment by UltraNix** [comment]
Fixed.
