### ISSUE TITLE
Lvl 50 armor specialization passive bug

### ISSUE THREAD

**Issue by PrinceArtyx** [gamefreedomgit/Maelstrom#1032]
When you reach lvl 50 you can learn each armor specialization, for example, Cloth, Leather, Mail and Plate and you get 5% Intellect, Agility or Strenght. It’s a passive that you can learn only by reaching lvl 50 on each class/spec. On Whitemane you auto learn this from lvl 1 which is a bug. 
![0EE2A196-AFC2-4CF1-8248-9B09757E3D4B](https://user-images.githubusercontent.com/120288202/206883121-172a531e-ba44-4b39-beb9-67e091275555.png)
![B81944CA-BBCD-47EA-98D0-763A5CB4A4D6](https://user-images.githubusercontent.com/120288202/206883122-e9c78e3d-443c-44d9-adee-0e4705b20655.png)
First picture is Apollo and second is Whitemane

**Comment by Afgann** [comment]
fixed
