### ISSUE TITLE
Special abilties not critting nearly enough 

### ISSUE THREAD

**Issue by Zadess** [gamefreedomgit/Maelstrom#1034]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Most of rogues special abilities don't crit, or rarely crit. Also, honor amoing thieves is not producing its combo point for rogues when crits are finally produced. I believe bleeds are also not critting

**How to reproduce:**
Go to a target dummy, spam special abilities you'll see some never crit, and of the few that do, its far far too rate in relation to crit chance.

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
