### ISSUE TITLE
Mount Hyal Quest [As Hyal Burns] Flight Path 

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1037]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Flight path of the drake Aronus (which you need to mount on to fly to hyal) is very bugged, you fly through the whole map, all time.

**How to reproduce:**

Accept Quest at Townboard to teleport to hyal as level 80
Accept Quest As Hyal Burns as follow up after passing the portal
Fly with Aronus..

**How it should work:**

**Database links:**

![image](https://user-images.githubusercontent.com/120294125/206888763-2b7bdb42-cf11-4525-b6a8-c7c342e27283.png)

**Comment by UltraNix** [comment]
#1031
