### ISSUE TITLE
Cannot auto attack yellow target

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1041]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am unable to attack Frostmane Troll Whelp (ID 706) with right click. Offensive spells work on that mob. 

**How to reproduce:**

1. Go to the Coldridge Valley
2. Look for Yellow Mobs (Frostmane Troll Whelps)
3. Go near them, so you fit to the melee range
4. Press right click on mob to start auto attack

**How it should work:**
You should be able to auto attack with you main hand weapon.

![WoWScrnShot_121122_112553](https://user-images.githubusercontent.com/102141825/206898631-51af0ddf-d8b8-4b17-89cc-3aaa4c5415fa.jpg)

**Comment by shinzo69** [comment]
can confirm.
i cant seem to attack those yellow mobs on the "second" troll starter island

https://i.imgur.com/cwuJ38H.jpeg

**Comment by Afgann** [comment]
fixed
