### ISSUE TITLE
Copper ore node out of reach

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1042]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Copper ore node is out of reach.
I was at The Grizzled Den where I spotted Copper ore node that is deep in floor. 
Coordinates: 49.44    44.36

**How to reproduce:**

1. Visit The Grizzled Den
2. Search for Copper ore nodes
3. Check if node is into your reach

**How it should work:**
All nodes and herbs should be in reach of player so they can be minded/herbed. 

![WoWScrnShot_121122_132253](https://user-images.githubusercontent.com/102141825/206903508-d033a7b5-3fce-49f6-8784-984037b95bef.jpg)
![WoWScrnShot_121122_132249](https://user-images.githubusercontent.com/102141825/206903512-838d4978-570b-43f8-ab73-3856e17c7a77.jpg)

**Comment by UltraNix** [comment]
Fixed.
