### ISSUE TITLE
[Druid] Flight Form bug 

### ISSUE THREAD

**Issue by mniert** [gamefreedomgit/Maelstrom#1044]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When landing a ground flight form fades but player can still fly (works with other feral forms as well) and it doesn't end as the player lands on the ground

Spells are usable on midair 

**How to reproduce:**

**How it should work:**
Flight form shouldn't fade away as the player lands on the ground and the player shouldn't be flying without flight form

**Database links:**

![ssss](https://user-images.githubusercontent.com/114408367/206906849-7b1c408b-1688-40e7-8135-6d03d90abaa8.PNG)
![assss](https://user-images.githubusercontent.com/114408367/206906927-e9c997c5-7885-498d-b5e6-1df335e81c9c.PNG)

**Comment by WhitemaneSylah** [comment]
New bug found with this,    If player collides with water then uses flightform they are stuck in a flying state without the form itself 

![image](https://user-images.githubusercontent.com/121137397/211551249-7d7ab37d-1367-4159-9712-47665de0b8f3.png)


Constantly triggering the anticheat

**Comment by UltraNix** [comment]
Fixed.
