### ISSUE TITLE
[Hunter] Silencing Shot

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1045]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Silencing Shot has travel time

**How to reproduce:** cast Silencing Shot

**How it should work:** Silencing Shot shouldn't have any travel time despite it being ranged, it should be instant regardless of your distance of your target

**Database links:** https://cata-twinhead.twinstar.cz/?spell=34490

**Comment by Afgann** [comment]
fixed
