### ISSUE TITLE
[Priest] Mind Blast, Mind Spike

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1047]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** These 2 abilities should light up on action bar when you have 3 Shadow Orbs

**How to reproduce:** Have 3 Shadow Orbs

**How it should work:** They should light up (the buttons) when you have 3 Shadow Orbs

**Database links:** https://cata-twinhead.twinstar.cz/?spell=73510 https://cata-twinhead.twinstar.cz/?spell=8092

**Comment by Afgann** [comment]
fixed
