### ISSUE TITLE
[LOW] Flying objects

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1050]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are two scrolls at 53.73   52.15   at Kharanos  that are in the air

**How to reproduce:**
Visit location and check if scrolls are in the air

**How it should work:**
Scrolls should be on the ground OR on the table.

![WoWScrnShot_121122_153808](https://user-images.githubusercontent.com/102141825/206910124-e8c02d08-67ec-4962-b2ef-8dbd7f3e4c9f.jpg)

**Comment by UltraNix** [comment]
Fixed.
