### ISSUE TITLE
[QUEST] The Ultrasafe Personnel Launcher

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1051]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After taking quest, you should use Ultrasafe Personnel Launcher (ID 41398). It should launch you in the air (which is working) but instead to land on **62.70, 53.60**, you will land on 56.76, 35.37

**How to reproduce:**

1. Accept quest
2. Go to and press it
3. Check where will you land

**How it should work:**
After taking Ultrasafe Personnel Launcher you should land on **62.70, 53.60**

**Comment by Afgann** [comment]
fixed
