### ISSUE TITLE
Second spec cannot be activated

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1052]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After purchase Dual spec from Sally Whitemane, I try to activate it. Instead, I was returned to my main spec, and I gain additional 3 points to spent in main spec tree. 

**How to reproduce:**
Visit Sally Whitemane and buy Dual Spec
Activate second spec 
Check if second spec is activated
Check if you receive additional points

**How it should work:**
You should be able to activate secondary spec. Also, you should not receive additional talent points

**Comment by UltraNix** [comment]
@MijatRanok Cannot reproduce it.
![obraz_2022-12-12_221109595](https://user-images.githubusercontent.com/80540499/207155333-eeb8eb93-cc99-4939-9341-4f5abaa7517e.png)

**Comment by MijatRanok** [comment]
Hello I have retested this but still have an issue when it comes to dual spec. So, I went to Sally and learn dual specialization. After clicking on activate, I was not able to select new secondary tree. I have video of it now. 
https://youtu.be/JIU8db1GE70

**Comment by UltraNix** [comment]
@MijatRanok Same happens for other classes?

**Comment by MijatRanok** [comment]
@UltraNix I have tested with fresh priest and didn't have issue. I have also made a new shaman and went to GM island, try to reproduce issue but I couldn't. So basically issue is with my character Atina. Ill try to delete cash and WTF folder to see if I can figure it out.

**Comment by MijatRanok** [comment]
@UltraNix  I made character Lily, I level it to level 10. Went to Sally and same happens as with Atina. When I activate secondary tree, I have lost major spec, and my talent point start acting crazy. I made video, let me know if you want 

https://user-images.githubusercontent.com/102141825/207310579-7f148ef2-3030-45c6-9a46-9354b1392bb5.mp4

**Comment by UltraNix** [comment]
Fixed.
