### ISSUE TITLE
Talents cannot be reseted

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1054]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I went to trainer and wanted to reset talents but nothing happen. Message that appear is that I don't have talents that needs to be reseted. 

**How to reproduce:**
Go to class trainer and go to the "I wish to unlearn my talents"
Check if your talents are reseted

**How it should work:**
You should be able to select new Summary, and than to dispose available talent points.

![WoWScrnShot_121122_163204](https://user-images.githubusercontent.com/102141825/206912849-46267a90-7ac3-4584-b53c-b7260540dda0.jpg)

**Comment by UltraNix** [comment]
@MijatRanok Cannot reproduce it.
![WoWScrnShot_121222_221533](https://user-images.githubusercontent.com/80540499/207156250-c0a00222-cf8f-47b7-965c-0e801369ce02.jpg)
![WoWScrnShot_121222_221536](https://user-images.githubusercontent.com/80540499/207156274-86ef429f-6f51-4175-a4f4-68500836b2e7.jpg)

**Comment by MijatRanok** [comment]
I have retested this, issue is fixed.
