### ISSUE TITLE
Scarlet Monastery quests in wrong dungeon

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1055]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Dark Side of the Light and Stripping Their Defenses are switched.

**How to reproduce:**
Just enter the dungeons

**How it should work:**
The Dark Side of the Light is offered in Library, while it should be Graveyard.
Stripping their Defenses is offered in Graveyard, while it should be Library

**Database links:**
/?quest=26959
/?quest=26950

**Comment by Afgann** [comment]
fixed
