### ISSUE TITLE
[Quest] Breaking The Line - NPC keeps spawning new when phased

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1057]
https://www.wowhead.com/quest=25035/breaking-the-line
(the NPC stays after completing this quest, so maybe the quest after this one also affects this)

**Description:**
If i go from Spitescale Cove --> Spitescale Cavern, the NPC Zuni keeps respawning and talking his phrase.

**How to reproduce:**
https://streamable.com/5l75qi

**How it should work:**
Probably the NPC Zuni (https://www.wowhead.com/npc=38423/zuni) shouldnt respawn all the time when he phases.

**Comment by UltraNix** [comment]
Fixed.
