### ISSUE TITLE
(Quest) In the Rear With the Gear - NPCs and drops bugged

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1058]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Twilight Proveditors and Twilight Slavedrivers are broken in that you can only attack one at a time, rendering the other unattackable. These two NPCs are required for the quests [End of the Supply Line] and [In the Rear With the Gear]. Currently, [End of the Supply Line] can be completed by simply killing the Twilight Proveditors, but to complete [In the Rear With the Gear] the player needs to kill both NPCs in order for the Twilight Slaves to drop their [Twilight Supplies]. I was able to kill a Twilight Proveditor and Slavedriver ONCE to get the Twilight Slaves to drop their supplies and looting the supplies only granted one [Twilight Supplies] each where they should drop 3 per pick up.

**Database links:**
Quest completion reference: https://www.youtube.com/watch?v=-w2esp_3e0E&ab_channel=TomSanGames
Quest: https://cata-twinhead.twinstar.cz/?quest=25234
Twilight Proveditor: https://cata-twinhead.twinstar.cz/?npc=39436
Twilight Slavedriver: https://cata-twinhead.twinstar.cz/?npc=39438
Twilight Slave: https://cata-twinhead.twinstar.cz/?npc=39431
Twilight Supplies (object): https://cata-twinhead.twinstar.cz/?object=202652
Twilight Supplies (item): https://cata-twinhead.twinstar.cz/?item=52568

**Comment by UltraNix** [comment]
Cannot reproduce it.
I can attack both at the same time.
Also, always 3 objects are dropped (one per slave).
