### ISSUE TITLE
Random Heroic Dungeon Que [Server Crash]

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1059]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**
We que RHC, once last dps spot confirmed, the server crashed asap.
Crashtime: 20:39 CET
**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I see no crash at that time.
