### ISSUE TITLE
Initial Quest "Vashj'ir" Bug [Quest]

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1061]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The initial quest from town board have no follow up quest.

**How to reproduce:**

Accept Quest from townboard:
https://www.wowhead.com/quest=27718/warchiefs-command-vashjir
Complete Quest at [Commander Thorak](https://www.wowhead.com/npc=41621/commander-thorak)
-> No follow up quest!!

**How it should work:**

Follow up quest to enter the new area 

**Database links:**

**Comment by UltraNix** [comment]
#1030
