### ISSUE TITLE
The Vortex Pinnacle [Dungeon, Normal Mode]

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1063]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

1) Receiving several debuffs which switch around like every second (Screenshot 1 & 2)
2) cant attack whirlwind, will kick you down several times until you try to pass (Screenshot 3)

**How to reproduce:**

**How it should work:**

**Database links:**

Screenshot 1
![image](https://user-images.githubusercontent.com/120294125/206927000-64968d93-0603-4abc-b77f-7964e72e7718.png)
Screenshot 2
![image](https://user-images.githubusercontent.com/120294125/206927033-c397211f-ba33-47c3-aaf4-a8f295d91d8c.png)
SC3
![image](https://user-images.githubusercontent.com/120294125/206927142-1a872fcc-a2c7-4878-9eec-d740be008408.png)

**Comment by bughuntard** [comment]
1. Please write more about it, this is a debuff/buff from the boss encounter, do you get it randomly in dungeon?

**Comment by Fromtill** [comment]
> 

We got it randomly running through the dungeon, right after the first dragon and before this 2 spheres on screenshot 3.
It didnt go away anymore and the 2 debuffs switched every second like wild.

**Comment by UltraNix** [comment]
Fixed.
