### ISSUE TITLE
[Hunter] Deterrence and Tranq Shot

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1064]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

1. Deterrence (one of these ID's, not sure which: https://cata-twinhead.twinstar.cz/?spells=7.3): silences can go through Deterrence. Only Chaos Bolt should be able to bypass it.
2. Tranquilizing Shot (19801) should be always usable even in enemy doesn't have any buffs. It shouldnt just take any effect but it should still be usable.

**How to reproduce:**
Use there abilities

**How it should work:**
Like in description

**Database links:**
in description there are IDs

**Comment by Afgann** [comment]
fixed
