### ISSUE TITLE
[Druid] Glyph of Hurricane

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1065]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** It doesnt work at all

**How to reproduce:** Cast Hurricane while having this glyph

**How it should work:** It should slow enemies affected by hurricane by 50%

**Database links:**
https://cata-twinhead.twinstar.cz/?item=40920 - glyph

**Comment by Afgann** [comment]
fixed
