### ISSUE TITLE
[Mage] Cone of Cold

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1067]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Cone of Cold hits targets who are even behind you https://prnt.sc/eDsuU-JGdOjw

**How to reproduce:** Cast Cone of Cold when close to the target and it's behind you

**How it should work:**
It should affect all enemies in 90 degrees cone (arc)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=120

**Comment by Afgann** [comment]
fixed
