### ISSUE TITLE
[Hunter] Snake Trap

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1069]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Snake Trap takes more than 1s to trigger and debuff given by snakes is fading after snakes die

**How to reproduce:** Cast Snake Trap and let enemy step on it

**How it should work:** it should trigger normally as other traps and the debuff from snakes shouldn't fade once snakes despawn

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=34600
https://cata-twinhead.twinstar.cz/?spell=82949
there are more snake trap IDs I dont know which one is correct used by hunter

**Comment by Afgann** [comment]
fixed
