### ISSUE TITLE
[World Event] Commoners

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1070]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** There are commoners linked to few world events spawned that offer world event quests despite the events are not active

**How to reproduce:** go to Orgrimmar/Stormwind and talk to Human Commoner or Orcish Commoner

**How it should work:** they should be active only when there's world event

**Database links:**

**Comment by bughuntard** [comment]
also it looks like NPCs from several events like Hallows End are active but event is off

**Comment by UltraNix** [comment]
Fixed.
