### ISSUE TITLE
Hunter Spell "Readiness" Useless, no function

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1071]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hunterspell "Readiness" should reset all cooldowns from hunter abilitys. 
Currently it does nothing, just show its visual on activating.

**How to reproduce:**

**How it should work:**
If i press any ability that have a cooldown timer, readiness should reset the cooldown from all abilitys with cooldown.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=23989

**Comment by Afgann** [comment]
fixed
