### ISSUE TITLE
[4.3] [Item] Will of Unbinding

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1072]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

DO NOT TOUCH BEFORE FIXING 4.3 STUFF

**Description:** Will of Unbinding doesn't proc from DoTs

**How to reproduce:** Wear this item and cast DoTs

**How it should work:** First tick of each DoT should proc this trinket

Firstly, the effect of this trinket procs from spell cast hits rather than damage. 

One stack instantly procs from each application or reapplication of a DoT such as Immolate, Unstable Affliction, Corruption or Bane of Agony/Doom. It doesn't proc from the damage of these DoTs.

Cast time damaging spells such as Shadow Bolt, Incinerate, Soul Fire, Searing Pain or Haunt proc one stack each time they hit a target.

It procs one stack upon beginning a channel of Drain Soul or Drain Life but doesn't continue stacking from the damage of these channels.

Every tick of Rain of Fire on every target hit procs one stack of the trinket (ie, if Rain of Fire is channelled over three targets, three stacks will be applied everytime those targets take a tick from Rain of Fire).

Seed of Corruption procs one stack when the seed first hits a target but doesn't gain any more stacks from DoT damage or detonation damage - even when the detonation is empowered from Soulburn.

Hellfire doesn't proc the trinket by cast or damage.

Shadowflame procs one stack per target hit by the instant damage but doesn't proc any further stacks by the DoT damage.

Death Coil, Fel Flame and Shadowburn proc one stack every time they hit a target.

Soul Swap and Soul Swap Exhale both proc one stack each when used.

Immolation Aura and Demonic Leap don't proc the trinket.

Curses do not proc the trinket.

If any of the spells mentioned above that cause a proc miss their target, they do not cause a proc.

**Database links:**
https://cata-twinhead.twinstar.cz/?search=will+of+unbinding

**Comment by MullichWhitemane** [comment]
As you said yourself, 4.3 stuff. Will revisit this report in the future.

**Comment by UltraNix** [comment]
Fixed.
