### ISSUE TITLE
[Whitemane Features] Auto Flight path learning

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1073]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Doesn't include any Silithus flight paths

**How to reproduce:**

**How it should work:** should include

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
