### ISSUE TITLE
[NPC] Kali Remik

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1074]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The NPC Kali Remik which gives the quest Incoming Gumdrop for the Halloween event should be in Orgrimmar as of 4.2, and not in Sen'jin Village anymore 

**How to reproduce:** Check spawnpoint

**How it should work:** It shoul dbe in Orgrimmar troll district, screenshot is in Database links in WoWhead 

**Database links:** 
https://www.wowhead.com/npc=11814/kali-remik

**Comment by Afgann** [comment]
fixed
