### ISSUE TITLE
[Player] Locations not always known

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1076]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** sometimes in guild roster it doesnt show players location when player is in Durotar for example, it's just blank. Tag if more research is needed

**How to reproduce:** Go to Durotar and check guild roster player location

**How it should work:** it should always show where you are

**Database links:**

**Comment by UltraNix** [comment]
@bughuntard Yep - more info needed. Maybe happens only in specific spots - give us some coords or screenshots.

**Comment by UltraNix** [comment]
No info - closing.
