### ISSUE TITLE
[Quest] Breaking the Chain

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1077]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The Northwatch Lugs will drop the boxes to attack you if you are in aggro range. 

**How to reproduce:** 

**How it should work:** They should only attack you if you attack/break their box or their co-carrier (the other Northwatch Lug helping to carry the box). See video for how it works in retail https://www.youtube.com/watch?v=GKCqhoWx1jU

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
