### ISSUE TITLE
[Hunter] Pet while mounting disappears + Bad Manner

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1078]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Pet disappears while mounting. It should stay in Cataclysm but be forced into passive stance and his pet ability bar should disappear. Also Bad Manner pet skill doesn't work at all.

**How to reproduce:**

**How it should work:** Pet should not disappear while mounted and Bad Manner should work like in description

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=90337 Bad Manner

**Comment by Afgann** [comment]
fixed
