### ISSUE TITLE
Deepholm [NPC] Zoltrik´s Pyremaw

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1080]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

NPC bug through map

**How to reproduce:**

**How it should work:**

NPC should be not there normally, maybe from quest or something

**Database links:**

https://www.wowhead.com/npc=44136/zoltriks-pyremaw
https://www.wowhead.com/spell=82553/summon-zoltrik-drake

![image](https://user-images.githubusercontent.com/120294125/206930523-4d04aafd-6a11-4837-9b72-bf5d76aad902.png)

**Comment by UltraNix** [comment]
Fixed.
