### ISSUE TITLE
(Quest) Survey the Lakeshore

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1082]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The summoned NPC, Goblin Surveyor Jr. Grade, does not activate the North Survey Marker. The other two Survey Equipments work fine.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=PGSIMXXO2VA&ab_channel=GameGuides
Quest: https://cata-twinhead.twinstar.cz/?quest=14202
Goblin Surveyor Jr. Grade: https://cata-twinhead.twinstar.cz/?npc=35485

**Comment by UltraNix** [comment]
Fixed.
