### ISSUE TITLE
(Quest) Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1083]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The vehicle NPC, Head Caravan Kodo, doesn't have correct pathing for the quest. The quest can still be completed somehow? :D

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=UoYLPbuEOLI&ab_channel=Gamer
Quest: https://cata-twinhead.twinstar.cz/?quest=13975
Head Caravan Kodo: https://cata-twinhead.twinstar.cz/?npc=34577

**Comment by UltraNix** [comment]
Fixed.
