### ISSUE TITLE
[Quest] It's Raid Night Every Night

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1084]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest "It's Raid Night Every Night" is working but took almost 4 minutes to be completed. Firstly, I thought it was not working and start writing a ticket, when I was back in the game Amberstill Mountaineer was killing mobs (which should be case). 

**How to reproduce:**
Visit Amberstill Ranch and pick up quest from Rudra Amberstill (ID 1265).
Go down, near entrance to the ranch (70.59 , 49.11) and wait for fight
Check how long does it take to start fight with Frostmanes

**How it should work:**
Fight should start immediately when Frostmanes are out.

**Comment by MijatRanok** [comment]
I am not sure about Quest ID, but I think this is its ID: 25932

**Comment by UltraNix** [comment]
Fixed.
