### ISSUE TITLE
Standing in fire won't hurt you

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1085]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am standing in camp fire but I am not taking damage. 

**How to reproduce:**
Stand in fire.
I was standing in camp fire at 27.92, 74.73

**How it should work:**
You should take small amount of damage. 

![WoWScrnShot_121222_072517](https://user-images.githubusercontent.com/102141825/206976243-98934ea6-f86d-4d75-9a10-ce59e9bdef3c.jpg)

**Comment by UltraNix** [comment]
Not all campfires do the fire damage - some are just visuals or cosmetics. This one is such example.
