### ISSUE TITLE
Chest doesn't respawn its content

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1086]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I was looting chest in location Frostmane Retreat (63.54, 56.08). First time when I looted it it was with some stuff, but (12 hours later) when I looted it it was empty.

**How to reproduce:**
Go to Frostmane Retreat at 63.54, 56.08.
Loot the chest which is near big drum
Check if you receive any content from chest

**How it should work:**
You should receive goods from chest

**Database links:**

https://user-images.githubusercontent.com/102141825/206995525-b30aca52-af1d-4fbb-822b-229f32238317.mp4

**Comment by MijatRanok** [comment]
Same happens with chest on location 36.21, 57.88

**Comment by UltraNix** [comment]
@MijatRanok I don't see any chest at 36.21, 57.88. It's the same chest?

**Comment by MijatRanok** [comment]
@UltraNix , no, they are totally separated chest on two different locations. I went to first chest on location 63.54, 56.08 but i wont open it should you want to take a look.

**Comment by UltraNix** [comment]
I mean - if it's the same name of the chest?

**Comment by MijatRanok** [comment]
@UltraNix  Yes, Silverbound Treasure Chest. Also, I need to apologize to you because I gave you false information. Second chest is 36.21, 57.88 but at Grizzlepaw Ridge, Loch Modan. So different zone. I can park char in front of it and give you credentials if you wish to log in and check.

**Comment by UltraNix** [comment]
Not needed. Fix is on the way.

**Comment by UltraNix** [comment]
Fixed.
