### ISSUE TITLE
Im Ret, cant use plate, in spellbook i already have platespec

### ISSUE THREAD

**Issue by Papegator** [gamefreedomgit/Maelstrom#1088]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed

**Comment by Papegator** [comment]
Still bugged, i done screen what happen when trie to use.
 [image: image.png]

2022-12-12, pr, 16:17 Afgann ***@***.***> rašė:

**Comment by Afgann** [comment]
It will be fixed after update.

**Comment by Papegator** [comment]
Aa, when update will be?

2022-12-12, pr, 17:56 Afgann ***@***.***> rašė:

**Comment by gaga-whitemane** [comment]
Please follow #changelog-cata channel on discord. Next update will happen in 2-3 hours.
