### ISSUE TITLE
Mobs pathing

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1089]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Loch Modan, 25.59, 44.69,  mobs with ID 45384 and ID 44161, have a unusual pathing. They are moving up the objects and once I saw ID45384 goin into air. Also I have notice those not only mobs that have unusual pathing. 

**How to reproduce:**
Visit location and check mobs behaving

**How it should work:**
Mobs shouldn't be able to go into air or over objects.

**Comment by MijatRanok** [comment]
Since file is too big I have put it on discord: https://discord.com/channels/1040715551531618365/1040715552227872809/1051856923219206164

**Comment by MijatRanok** [comment]
![image](https://user-images.githubusercontent.com/102141825/207245629-b3f14f42-396f-48c4-8294-00e3a757f860.png)
I also saw Golden Eagle (ID 44628) standing still in The Farstrider Lodge (78.43, 63.74)

**Comment by UltraNix** [comment]
Already fixed.
