### ISSUE TITLE
Double First aid trainings 

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1090]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At The Great Forge, 54.90, 58.59, at NPC Nissa Firestone (ID 5150) there are two buttons to train First aid.

**How to reproduce:**
Visit train and check how many options you have

**How it should work:**
One training option should be enough

![WoWScrnShot_121222_152609](https://user-images.githubusercontent.com/102141825/207070646-1bf8048a-feea-4bbb-b960-db288ce30bef.jpg)

**Comment by Afgann** [comment]
fixed
