### ISSUE TITLE
Whitefin cannot be attacked

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1091]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Whitefin mob (ID 45401) cannot be attacked. I receive message that target is out of range. 

**How to reproduce:**
Visit The Loch and search for Whitefin
Try to attack him

**How it should work:**
As every other mob, Whitefin should die.

**Video:**
https://www.youtube.com/watch?v=kl0AQ42Eg8k&ab_channel=Mr.Ridji

**Comment by UltraNix** [comment]
Should be fixed.
