### ISSUE TITLE
(Quest) Kyle's Gone Missing! - [Very Minor]

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1093]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The quest is completable and works correctly, however Kyle the Frenzied should be running and he is currently RP walking. Not too big of a deal if fixed or not, just wanted to make note.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=11129
Kyle the Frenzied: https://cata-twinhead.twinstar.cz/?npc=23616

**Comment by UltraNix** [comment]
Fixed.
