### ISSUE TITLE
[Dun Morogh - Chill Breeze Valley] Gnomeregan Recruit NPCs are dead

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1094]
**Description:**
Those NPC's [Gnomeregan Recruit](https://www.wowhead.com/npc=43092/gnomeregan-recruit) are dead but walking around. They do also have a tooltip with various information about them that shouldnt be there.

**How to reproduce:**
Just go to [here](https://i.imgur.com/F4qlnbr.png) and have a look

**How it should work:**
NPC [Gnomeregan Recruit](https://www.wowhead.com/npc=43092/gnomeregan-recruit) should be alive with the correct tooltip

**Database links:**
https://www.wowhead.com/npc=43092/gnomeregan-recruit
https://i.imgur.com/1s6meyG.jpeg
https://i.imgur.com/swqzSFO.png

**Comment by UltraNix** [comment]
Fixed.
