### ISSUE TITLE
[Quest] Down with Crushcog! ID: 26364

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1095]
**Description:**
There should be some mobs and more of an "rp-event" at the beginning of the quest. The quest works, but idk if its right the way it is right now. Theres also some "DND" units on the ground that cast a spell and then disappear. (can be seen in the video below)
[Friendly NPC](https://www.wowhead.com/npc=42852/mountaineer-stonegrind) who's involved to the quest also doesn't help.

**How to reproduce:**
Take the [Quest](https://www.wowhead.com/quest=26364/down-with-crushcog), talk to [High Tinker Mekkatorque](https://cata-twinhead.twinstar.cz/?npc=7937) (ID may be wrong) to let the "rp walk" begin.

**How it should work:**
When Mekkatorgue and the NPC to kill meet together, there should normally happen a event with some mobs coming around. The friendly NPC should help attacking.

**Database links:**
[How the Quest should be](https://www.youtube.com/watch?v=EXxbvLe5uRw)
[My POV (with the DND unit)](https://streamable.com/astk6t)

**Comment by UltraNix** [comment]
Fixed.

**Comment by Awespriest** [comment]
I'm having the same issue.
