### ISSUE TITLE
[Dun Morogh - Chill Breeze Valley] Gnomeregan Recruit have no pathing/patrol

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1096]
**Description:**
The [Gnomeregan Recruit](https://www.wowhead.com/npc=43092/gnomeregan-recruit) NPCs are just standing there doing nothing. They should probably walk a route or patrol somewhere. Sadly I cant find a video on YT to see what they should be doing.

**How to reproduce:**
Walk [here](https://i.imgur.com/T5FChGp.png) and have a [look](https://i.imgur.com/gsBdDSy.jpeg) at the NPCs

**How it should work:**
The [Gnomeregan Recruit](https://www.wowhead.com/npc=43092/gnomeregan-recruit) NPCs should walk/patrol/path.

**Database links:**
https://www.wowhead.com/npc=43092/gnomeregan-recruit (same as above linked)

**Comment by UltraNix** [comment]
Fixed.
