### ISSUE TITLE
Elwynn Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1097]
**Description:**
This report is based on normal levelling without using any command while doing all the quests in the zone. Adding a noted bugs when visiting Stormwind.

1: Stormwind Infantry: https://www.wowhead.com/npc=49869/stormwind-infantry#sounds
- Stormwind infantry at Northshire aggro the hostile mobs if player kites them the guards, but they stand and just keep turning to face the mob in battle postions and do not attack.
- I believe they should be proactively fighting the mobs
-2016 video: https://www.youtube.com/watch?v=jsw5tCd17tc&t=506s **timestamp 8:26** you can see some of the infantry fighting the wolves. Not sure if  I will be able to find some cata video from the zone.

2: Kira Songshine: https://www.wowhead.com/npc=3937/kira-songshine
- Multiple spawns, two travel together at normal pathing and speed as far as I could say. Another spawn has bugged pathing, runs most of the time, goes through textures or air.

3: Herbalism; Silverleaf: https://www.wowhead.com/object=1617/silverleaf
- Found two spawn points below the ground. Coordinates: 57.5/75.4 and 82.5/76.5

4: Report to Thomas: https://www.wowhead.com/quest=71/report-to-thomas
- This quest is available, or at least the exlamation mark for it, before the player does pre-requisite quests
- Seen it available when on Find the Lost Guards https://www.wowhead.com/quest=37/find-the-lost-guards
- Should be available only after Completing quests Find the Lost Guards and Discover Rolf's Fate https://www.wowhead.com/quest=45/discover-rolfs-fate
Note: There might be more problems in Elwynn quests' order.

5: Crier Goodman: https://cata-twinhead.twinstar.cz/?npc=2198
- bad pathing, seen between Cathedral Square and The Mage Quarter (iirc) "flying" through the air

6: [Stormwind Royal Guard](https://cata-twinhead.twinstar.cz/?npc=1756) at 73.7/46.0 is under the bridge in the wall.

7: Canal Crab: https://www.wowhead.com/npc=42339/canal-crab
- This NPC is lootable for Canal Crab: https://www.wowhead.com/item=57175/canal-crab even without having the quest Feeling Crabby https://www.wowhead.com/quest=26177/feeling-crabby
- The NPC does not disappear after looting and you can loot one NPC for infinite number of crabs, it shouldn't be the case.
UPDATE: they properly despawn after looting when you have have the quest.

8: Most if not all generic Humanoid mobs, that supposed to do so, do not "attempts to run away in fear!" when they hit low hp, which was customary on preceding expansions and it occurs normally in Westfall on PTR. Hard to provide completely list of mobs, if even possible, maybe for some separate report.

9: I haven't noticed any treasure chests at all and I actually tried to look for a few. Maybe I am blind, maybe they are not spawned or maybe they don't respawn when fully looted. Worth looking into.
UPDATE: Haven't come across a single chest in Westfall either.

**Comment by UltraNix** [comment]
Fixed.
