### ISSUE TITLE
[Quest] Breaking the Line - ID: 25035

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1098]
**Description:**
The Raptor is walking a bit too fast, teleporting and overall (if its possible), the camera fixpoint ways should be a bit more smoother.

**How to reproduce:**
Accept the quest from [Tortunga](https://www.wowhead.com/npc=38440/tortunga), talk to the NPC next to the raptors to get u a raptor.

**How it should work:**
The Raptor should walk in a more smooth way
https://www.youtube.com/watch?v=6oW0m7bBc1U

**Database links:**
https://www.wowhead.com/quest=25035/breaking-the-line´
POV: https://streamable.com/qk2a6h

**Comment by UltraNix** [comment]
Fixed.
