### ISSUE TITLE
The Platinum Discs [Uldaman Quest]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1100]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Platinum Discs can not be completed

**How to reproduce:**
Accept the quest, talk to Lore Keeper of Norgannon to complete the talking part of the quest, try to activate the Discs of Norgannon. The dialog box of the discs does not allow to complete.

**How it should work:**
https://www.youtube.com/watch?v=pHNxfOGPmwA

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
