### ISSUE TITLE
[Zul'Farrak] Mobs evading by going under the terrain

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1102]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

During the stairs event in ZF, Sandfury Zealots go under the terrain in the stairs causing the fight to be uncompletable. They remain in combat, attacking Weegli Blastfuse, without being in line of sight to be attacked.

**How to reproduce:**

Start the stairs event and watch

**How it should work:**

They should stay on top of the terrain so they can be attacked

**Database links:**

/?npc=8877

**Comment by UltraNix** [comment]
Should be fixed.
