### ISSUE TITLE
Zul Gurub [Dungeon Heroic] unkillable group of enemies & Dungeon cant be finished!

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1103]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

In Zul Gurub Heroic (dont know of normal too) is a group of npc´s which dmg output is that crazy that all group members die like instant, even with BiS gear and all cooldowns ready you are not able to keep them alive.

You cant finish the dungeon, because you are unable to reach the boss "High Priestess Kilnara" which is below the group of enemies.

**How to reproduce:**

go to zul gurub heroic and fight the group of enemies.

**How it should work:**

**Database links:**
![image](https://user-images.githubusercontent.com/120294125/207158117-065c52e8-25a9-4dec-a90e-fd0c53f3b715.png)

![image](https://user-images.githubusercontent.com/120294125/207158153-3ef65824-c750-432f-92f9-3576dffacadc.png)

**Comment by UltraNix** [comment]
Fixed.
