### ISSUE TITLE
Frostmage dmg bugged

### ISSUE THREAD

**Issue by Damon156** [gamefreedomgit/Maelstrom#1105]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mage Frostdmg too low.
Tested other realms and it feels like spellpower and mastery is bugged. 
Frostbolt and icelance do less dmg compared to other realms and retail

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Damon156 More data/info is needed. Saying "dmg is too low" says nothing to me.

**Comment by Damon156** [comment]
When i compare frostbolt dmg to retail and other private realms up to 10k dmg is missing when it crits. 
On maelstrom it crits 42k on other realms 51-53k same for icelance

**Comment by UltraNix** [comment]
@Damon156 I need some tests or specific numbers. In what build? What lvl/auras/buffs/gear/talents/etc? Against what/who?

**Comment by UltraNix** [comment]
No info - closing.
