### ISSUE TITLE
Paladin Spell [Exorcism] no CD

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1106]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

You can spam it without global cd / cd.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
