### ISSUE TITLE
(Quest) Mending Old Wounds

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The quest should only be acceptable if the player has reputation lower than Neutral with Ratchet.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=9267
Mupsi Shacklefridd: https://cata-twinhead.twinstar.cz/?npc=16418

**Comment by UltraNix** [comment]
Fixed.
