### ISSUE TITLE
Missing NPC - Tony Two-Tusk

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1108]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Tony Two-Tusk is meant to be sitting inside the shack on Fray Island.

**Database links:**
https://www.wowhead.com/quest=14052/take-it-up-with-tony
Tony Two-Tusk: https://cata-twinhead.twinstar.cz/?npc=34749      /     https://www.wowhead.com/npc=34749/tony-two-tusk

**Comment by Afgann** [comment]
fixed
