### ISSUE TITLE
(Quest) Raging River Ride

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Quest is completable, but the Riverboat's speed needs to be increased.

**Database links:**
Quest video: https://www.youtube.com/watch?v=vrm6LftOwvw&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=26769
Riverboat: https://cata-twinhead.twinstar.cz/?npc=44055   /   https://www.wowhead.com/npc=44057/riverboat

**Comment by UltraNix** [comment]
Fixed.
