### ISSUE TITLE
(Quest) Report to Thork

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1110]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Upon completing the quest [Serena Bloodfeather], the questgiver Darsok Swiftdagger does not give the follow up quest [Report to Thork].

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=29095
Darsok Swiftdagger: https://cata-twinhead.twinstar.cz/?npc=3449

**Comment by UltraNix** [comment]
Fixed.
