### ISSUE TITLE
(Quest) Iterating Upon Success

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The flight path of the Forsaken Bat is not scripted correctly; it is very choppy and phases through the terrain. The Blight Concoction ability does no damage to the murlocs as the vehicle flies over them. As the quest stands right now, if the player kills them manually, the quest is completable.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=oD4g_O6Rpa4&ab_channel=GitGudGuides
Quest: https://cata-twinhead.twinstar.cz/?quest=26998
Forsaken Bat (vehicle): https://cata-twinhead.twinstar.cz/?npc=44821
Blight Concoction (ability): https://cata-twinhead.twinstar.cz/?spell=83573

**Comment by UltraNix** [comment]
Fixed.
