### ISSUE TITLE
(NPC) Forest Ettin - Minor?

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1113]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Forest Ettins are all at 1 health, they should all have full health

**Database links:**
Forest Ettin: https://cata-twinhead.twinstar.cz/?npc=44367

**Comment by UltraNix** [comment]
Fixed.
