### ISSUE TITLE
(Quest) No Escape

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1114]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

During the brief cutscene, Magistrate Henry Maleb will spam his line "We choose vengeance!" without stopping, and does not show the end of the cutscene where the humans turn into Worgen. Along with this, after a while of watching Maleb shout his line, when Agatha carries you out of Fenris Keep, she flies toward Forsaken High Command and then a second Agatha interrupts and restarts the interaction, carrying you back to Fenris Keep and basically dragging the player through that scenario I think 3-4 times (I think this was a total of like 10 minutes lol). Ideally, she is supposed to drop the player off in the middle of Forsaken High Command, in front of Lady Sylvanas Windrunner. After waiting through that, the quest was completable.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=5qiihri_3pY&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=27099
Magistrate Henry Maleb (unsure which it is): 
https://cata-twinhead.twinstar.cz/?npc=44996
https://cata-twinhead.twinstar.cz/?npc=2276
Agatha (again, unsure): 
https://cata-twinhead.twinstar.cz/?npc=44608
https://cata-twinhead.twinstar.cz/?npc=44951
https://cata-twinhead.twinstar.cz/?npc=45054

**Comment by UltraNix** [comment]
Fixed.
