### ISSUE TITLE
(Quest) Lordaeron - Minor?

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1115]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

During the cutscene, there are many instances of Sylvanas interrupting her own voicelines. It's nothing too major but very annoying :'D

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=Vbpt7XwAFF0&ab_channel=Tsazao
Lady Sylvanas Windrunner: https://cata-twinhead.twinstar.cz/?npc=44365

**Comment by UltraNix** [comment]
Fixed.
