### ISSUE TITLE
[Mage] Ignite

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1116]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Ignite spell doesn't work at all

**How to reproduce:** cast fireball/pyroblast and crit

**How it should work:** it should proc after fireball/pyroblast

**Database links:**
https://cata-twinhead.twinstar.cz/?spells=7.8 ignite

**Comment by Afgann** [comment]
fixed
