### ISSUE TITLE
[NPC] Zuni

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1117]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** In Durotar, Spitescale Cavern, During the quests "Territorial Fetish" Zuni NPC disappears and appears evently, even when he is close to the player. It happens especialy on the stairs, next to the entrance to the cave and also inside the cave.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Possible pathfinding/waypoint issue

**Comment by UltraNix** [comment]
Already fixed.
