### ISSUE TITLE
[Warrior] Heroic Leap

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1118]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** heroic leap should be available to use only when your target ground is in line of sight. if you cant for example Charge to a person standing in place A, you shouldnt be able to heroic leap into that place

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
