### ISSUE TITLE
Character stuck after summoning mount

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#1119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After casting mount (I have tried with few ones), my character stays with hands in the air. Rest is working okay, and it it comes back when I dismount. 

**How to reproduce:**
Mount up

**How it should work:**
Character's arms shouldn't be in the air.

![WoWScrnShot_121322_075650](https://user-images.githubusercontent.com/102141825/207247761-934dc8c0-0767-4f86-ab0d-5287367072be.jpg)

**Comment by UltraNix** [comment]
@MijatRanok Tried like 100 times - no reproduce.

**Comment by MijatRanok** [comment]
I also have retested this and could not reproduce. Might be incompatibility with some of the addons that I am using.
