### ISSUE TITLE
[Quest] Call of Duty (Horde)

### ISSUE THREAD

**Issue by mniert** [gamefreedomgit/Maelstrom#1120]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After the quest "Warchief's Command: Vashj'ir!" the next quest "Call of Duty" is not available from Commander Thorak

**How to reproduce:**

**How it should work:**

**Database links:**
Commander Thorak: https://cata-twinhead.twinstar.cz/?npc=41621
Call of Duty: https://cata-twinhead.twinstar.cz/?quest=25924

**Comment by UltraNix** [comment]
#1030
