### ISSUE TITLE
[Quest] A vision of the Past missing texts

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1122]
**Description:**
The roleplay after drinking the Incense Burner is missing all the emotes, yell and chat bubbles. You can hear VanCleef talking but there is no text either in chat box or in bubbles. There is no text whatsoever from the other npcs there.
I am also not sure if Vanessa spawned at all, but probably yes, because I was watching the Alliance party leaving.

**How to reproduce:**
Take the quest and do it.

**How it should work:**
Here is a link to a wowhead video: https://www.youtube.com/watch?v=4zeTrG4RVY8
- 2:35 the important part starts

**Database links:**
[Alliance Warrior](https://cata-twinhead.twinstar.cz/?npc=42699)
[Edwin VanCleef](https://cata-twinhead.twinstar.cz/?npc=42697)
[Defias Blackguard](https://cata-twinhead.twinstar.cz/?npc=42698)
Vanessa VanCleef: https://cata-twinhead.twinstar.cz/?npc=42371 or https://cata-twinhead.twinstar.cz/?npc=42372

**Comment by UltraNix** [comment]
Fixed.
