### ISSUE TITLE
[Object] [Dungeon] Deadmines – Defias Cannon

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1123]
**Description:**
If you jump into the [Defias Cannon](https://www.wowhead.com/npc=48266) in Deadmines there are three issues.
1: The [Cannonball](https://www.wowhead.com/spell=95491/cannonball) does no damage.
2: The Cannonball explosion visual is set on the cannon itself.
3: When you leave the cannon you will get Combat Bug.

Tried this on the 1st cannon in the dungeon, haven't tried others due to being unable to do so based on my ptr playstyle atm.

**How to reproduce:**
Jump into the cannon.

**How it should work:**
Should do damage to enemies, shouldn't leave you in combat.

**Comment by UltraNix** [comment]
Fixed.
