### ISSUE TITLE
Combat Bug - NPCs with pets?

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1124]
**Description:**
So, exact description of what happened:
I have attacked [Murloc Hunter](https://www.wowhead.com/npc=458/murloc-hunter) and killed his [Crawler](https://www.wowhead.com/npc=6250/crawler). Before I managed to kill the Hunter he ran away in fear, pulling 5 other mobs, at least 3 of them were other hunters with their pets.
I have decided to run away, just kileld one more Crawler pet on my way away. No matter how far I ran the Combat stayed on. I have decided to get back to the beach to find the still-aggroed mob but there was none. All the mobs lost their aggro but I was still in combat.

I suspect the NPC pets might be an issue here that somehow keeps you in combat. Otherwise I had no issues with combat bug so far (except the Deadmines cannon) and it was the 1st NPC with pets I have come across.

**Comment by UltraNix** [comment]
@Greywolf59 Just tested mutliple times and cannot reproduce it. Happened only once?

**Comment by Greywolf59** [comment]
Haven't tried again. I will try to reproduce within next 24 and let you know.

**Comment by Greywolf59** [comment]
@UltraNix Recreated as follows: Attacked Murlock Hunter and his pet, killed the pet Crawler. The Murlock ran away in fear into another Hunter and Crawler pet. **I ran away without killing anything**. Crawler followed me all the way to the Raging Chasm and would probably follow me still. There I turned around and killed the Crawler and I have stayed in combat. When I returned to the coast (still in combat), no Murloc Hunter was aggroed on me and they all had a full HP and a fresh Crawler pet. So it means my memory in OP wasn't exact.

**Comment by UltraNix** [comment]
@Greywolf59 Still can't reproduce it. Are you able to make a video of this?

**Comment by UltraNix** [comment]
Just tried on my local at the same spot, same level and still works okay.

**Comment by UltraNix** [comment]
Stil can't reproduce it.

**Comment by Greywolf59** [comment]
Well, what can I say. I am using the client provided by Whitemane, no commands used ever except .tele, no addons except Carbonite (Quest). Done this pull three times.

**Comment by UltraNix** [comment]
Okay - I know what is the problem.

**Comment by UltraNix** [comment]
Fixed.
