### ISSUE TITLE
(Quest) Nowhere to Run

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1125]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Overall the quest works as intended, but the NPC Packleader Ivar Bloodfang is interactable when he shouldn't be and can kill the player if they get too close. The quest is completable currently.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=3a--gbWzQpY&ab_channel=GitGudGuides
Quest: https://cata-twinhead.twinstar.cz/?quest=27195
Packleader Ivar Bloodfang: 
https://cata-twinhead.twinstar.cz/?npc=44990
https://cata-twinhead.twinstar.cz/?npc=44884

**Comment by UltraNix** [comment]
Fixed.
