### ISSUE TITLE
Herbalism Tracking

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1126]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Some objects in the world that are required for quests show up while tracking herbs even while not on the required quest.

**Database/Example links:**
Wolfsbane: https://cata-twinhead.twinstar.cz/?object=205367
Mulgore Pine Cone: https://cata-twinhead.twinstar.cz/?object=208875

**Comment by UltraNix** [comment]
Fixed.
