### ISSUE TITLE
(Quest) The Great Escape

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1127]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After picking up the player, Arthura's pathing is janky and goes through terrain and goes back and forth from the Greymane Wall to the pickup spot until she eventually drops the player off at the correct spot. Quest is currently completable.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=HaV6Ud8nv6w&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=27438
Arthura: 
https://cata-twinhead.twinstar.cz/?npc=45056
https://cata-twinhead.twinstar.cz/?npc=45106

**Comment by UltraNix** [comment]
Should be fixed.
