### ISSUE TITLE
[Quest] [NPC] Hilary's Necklace and Hilary

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1128]
1: [Hilary's Necklace](https://cata-twinhead.twinstar.cz/?quest=3741) – if you open convo with [Shawn](https://cata-twinhead.twinstar.cz/?npc=8965) and [Hilary](https://cata-twinhead.twinstar.cz/?npc=8962), it is full of thanks for returning the necklace even before even taking the quest.
 Based on [Hilary's Wowwiki](https://wowpedia.fandom.com/wiki/Nida), Hilary's gossip should say "I think my necklace fell in the lake. My daddy got it for me, and he's gonna be mad now." before completing the quest
And based on [Shawn's Wowwiki](https://wowpedia.fandom.com/wiki/Shawn_(child)) he should be saying "Hello there <mister/ma'am>... do you have a little time that you could help us out? Please?" before you complete the quest

2: On Wowwiki patch notes on Nida's entry , it is stated that since Cataclysm 4.0.3a this NPC is renamed to [Nida](https://www.wowhead.com/npc=8962) and the quest itself to [Nida's Necklace](https://www.wowhead.com/quest=26508/nidas-necklace). This is also acknowledge by Twinstar: https://cata-twinhead.twinstar.cz/?npc=8962.

3: I think the [cat](https://www.wowhead.com/npc=8963/effsee#comments) didn't meow after completing the quest.
- Not sure anymore if Hilary's answering replica to the meow was uttered: "I know how to speak kitty, and Effsee said thank you.."

What should Happen:
1: The gossip texts should be arranged properly based on if the quest is completed or not
2: Both the NPC and the Quest should be renamed.
3: Cat should meow after you finish the quest and Hilary = Nida should say the replica.

**Comment by UltraNix** [comment]
Fixed.
