### ISSUE TITLE
Redridge Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1129]
1: [Huge Boulder](https://cata-twinhead.twinstar.cz/?npc=43196) is spawned twice

2: [Foreman Oslow](https://cata-twinhead.twinstar.cz/?npc=341) under the boulder should be saying "Please... kill... me..." based on video https://www.youtube.com/watch?v=MVXqblwkWo4; TIME 13:25. Instead now he says something about looking for his tools.

3: Both versions of Foreman Oslow are visible at the same time, one is under the boulder and [the other Oslow](https://cata-twinhead.twinstar.cz/?npc=43194) is standing a few steps from him. The standing Oslow should be visible only after completing the appropriate quest, [Saving Foreman Oslow](https://www.wowhead.com/quest=26520/saving-foreman-oslow).

4: I think the event of Saving Foreman Oslow should be looked into also. I already finished the quest so I can't rewatch it atm, but it seemed to me the etinn grabbed both the boulder and Oslow.

5: Many of the quests ending directly at [Magistrate Solomon](https://cata-twinhead.twinstar.cz/?npc=344) don't go away after clicking complete and player has to close them manually and interact with the Magistrate again to grab the next quest.

6: [Bruiseweed](https://www.wowhead.com/object=1622/bruiseweed) under texture at: 33.3/23.4; 17.6/40.6; 71.0/64.7

7: [Messner](https://cata-twinhead.twinstar.cz/?npc=43270) runs out of the cage to fight nearby orc.

8: [Blackrock Worg Captain](https://www.wowhead.com/npc=43341/blackrock-worg-captain) stands on a spot instead of being on patrol
- video at 50:28: https://www.youtube.com/watch?v=MVXqblwkWo4

9: [Messner companion](https://cata-twinhead.twinstar.cz/?npc=43300) is way more agressive (long aggro range against orcs) than on the video above (53:40) and he keeps using [Molten Armor](https://cata-twinhead.twinstar.cz/?spell=79849) after every combat or after a few seconds.

10: [Jorgensen](https://www.wowhead.com/npc=43305/jorgensen#abilities) companion keeps spamming [Seal of Righteousness](https://www.wowhead.com/spell=79962/seal-of-righteousness). Other abilities might be worth looking into. Most likely the same aggro problem as Messner and the rest of companions.
There are also typos in his Quotes scripts, problem being in these two at least:
- Jorgensen says: Can't believe we're putting the old team back together. All thanks to you, **name**.
- Jorgensen says: You ever seen Keeshan kill an orc? It's a sight to behold, **lady**.
- Jorgensen says: You ever seen Keeshan kill an orc? It's a sight to behold, **man**.

11: [It's Never Over](https://www.wowhead.com/quest=26616/its-never-over) and the [Keeshan's Boat](https://www.wowhead.com/npc=43443/keeshans-riverboat)
- Using still the same video, you can see at 1:07:30 the Company is in the boat. The boat on the server is empty and a bit below water.
- The [summoned boat](https://www.wowhead.com/npc=43450/keeshans-riverboat) travels a bit under the water surface and afaik Messner is not using the flames to speed up the boat (on video and on wowhead screenshot).

12: [Prisoners of War](https://www.wowhead.com/quest=26646/prisoners-of-war#comments)
- It is stated that Jorgensen will be coming with you, but he stays in the camp, nothing.

13: [To Win a War, You Gotta Become War](https://www.wowhead.com/quest=26651/to-win-a-war-you-gotta-become-war)
- This quest should be recieved automatically after Prisoners of War through the comm/reciever in Bravo Company Field Kit but I did not get it and had to return to the quest giver at the lake, Might have been due to me not using the kit though.

14: [Ward of Ilgalar](https://cata-twinhead.twinstar.cz/?object=204582) is spawned twice

15: In the Tower of Ilgalar there should be [Grand Magus Doane](https://cata-twinhead.twinstar.cz/?npc=397), instead there is [Morganth](https://wowpedia.fandom.com/wiki/Morganth#Patch_changes) who has been removed by patch 4.0.3a and instead of him Grand Magus Doane was added. The kill still acounts for [the quest](https://cata-twinhead.twinstar.cz/?quest=26694) completion.

16: [AHHHHHHHHHHHH! AHHHHHHHHH!!!](https://www.wowhead.com/quest=26708/ahhhhhhhhhhhh-ahhhhhhhhh)
This whole quest is **not scripted at all**. You get auto complete and you can finish the quest at quest giver either at Shalewind Canyon or at Keeshan's Post.

17: [Showdown at Stone Watch](https://www.wowhead.com/quest=26713/showdown-at-stonewatch)
When you accept the quest and leave the camp, [Krakauer](https://cata-twinhead.twinstar.cz/?npc=43608), [Messner](https://cata-twinhead.twinstar.cz/?npc=43610), [John J. Keeshan](https://cata-twinhead.twinstar.cz/?npc=43611), [Jorgensen](https://cata-twinhead.twinstar.cz/?npc=43609) and [Danforth](https://cata-twinhead.twinstar.cz/?npc=43607) **NPCs should despawn and their Guardian/Companion versions should go with you.**
- When you accept the quest, the Companion versions spawn, still green, not blue.
- Only John J. Keeshan follows you, the rest is standing stacked on spot.
- The NPCs start with Commanding Shout and when it dissipates they go almost to 0% HP which is probably because that said [Commanding Shout](https://cata-twinhead.twinstar.cz/?spell=80983) adds 2 500 HP which is not reflect on the Companions who are still below 1.2k HP. I am not sure if this version of Danforth should even use this shout. Twisntar lists Commandign Shout at this version of NPC but WoWhead lists Battle Shout instead. I think Commanding Shout should be used by the higher level version of Danforth elsewhere.
- The proper NPCs don't disappear right away, only after some time.

Companion Counterparts list:
Krakauer: https://cata-twinhead.twinstar.cz/?npc=43829; https://www.wowhead.com/npc=43829/krakauer
Messner: https://cata-twinhead.twinstar.cz/?npc=43826; https://www.wowhead.com/npc=43826/messner
John J. Keeshan: https://cata-twinhead.twinstar.cz/?npc=43812; https://www.wowhead.com/npc=43812/john-j-keeshan
Jorgensen: https://cata-twinhead.twinstar.cz/?npc=43827; https://www.wowhead.com/npc=43827/jorgensen
Danforth: https://cata-twinhead.twinstar.cz/?npc=43828; https://www.wowhead.com/npc=43828/danforth

**EDIT: If I walk inside Stone Watch Keep and back there is some phasing, Keeshan disappears and the rest of Companions will relocate to me and then SOMETIMES they start following me and fighting alongside me, including resetted Keeshan.**
EDIT 2: They get unbugged if I pull a mob from inside the keep near the entrance where they are spawned and then outside of the keep before they manage to kill him in which case they despawn.
VIDEO: 1:41:55 at: https://www.youtube.com/watch?v=MVXqblwkWo4

18: [Tharil'Zun](https://cata-twinhead.twinstar.cz/?npc=486) follows the player way too far, if the player runs away.

19: [Showdown at Stonewatch](https://www.wowhead.com/quest=26713/showdown-at-stonewatch) should be handed in via the communicator, not by going back to the camp to the NPC, based on Completion text itself. And [Darkblaze, Brood of the Worldbreaker](https://www.wowhead.com/quest=26714/darkblaze-brood-of-the-worldbreaker) should aso be offered and accepted via the communicator.

20: [Darkblaze, Brood of the Worldbreaker](https://www.wowhead.com/quest=26714/darkblaze-brood-of-the-worldbreaker) is nto scripted properly. There is some [Horn of Summoning](https://www.wowhead.com/npc=43863/horn-of-summoning) you can click to summon [Darkblaze](https://cata-twinhead.twinstar.cz/?npc=43496). Comment on wowhead does not suggest it should be there at all and the video I am using as reference throughout this report does not include any horn, the dragon flies in right away (1:44:30).
- Also the fact the Companions are either missing or come running late result in some script breaking stuff, like Keeshan dying prematurely.
- Also Darkblaze's human form should be named "Grand Magus Doane", instead it is called "Morganth" (see point 15 in my report)

**Comment by UltraNix** [comment]
Fixed.
