### ISSUE TITLE
[Zone] The Lost Isles - full empty

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1131]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

the Zone is full empty, no single npc there.

**How to reproduce:**

**How it should work:**
https://wowpedia.fandom.com/wiki/Lost_Isles#:~:text=The%20Lost%20Isles%20is%20a,fleeing%20the%20devastation%20of%20Kezan.

**Database links:**

**Comment by Loken-coolguy** [comment]
Phasing issue possibly?

**Comment by UltraNix** [comment]
![obraz_2022-12-14_113221962](https://user-images.githubusercontent.com/80540499/207571897-65a35444-5031-497e-b655-1e198e0acca9.png)
![WoWScrnShot_121422_113525](https://user-images.githubusercontent.com/80540499/207572565-790df0db-635c-41b5-9ee4-35b3758fe84e.jpg)
![WoWScrnShot_121422_113507](https://user-images.githubusercontent.com/80540499/207572595-68e39698-c661-404c-bd2a-0f6963421107.jpg)
![WoWScrnShot_121422_113456](https://user-images.githubusercontent.com/80540499/207572620-a44a5100-b738-473e-b701-5df9b2ab1782.jpg)
Everything works okay - just do the chain quest.
