### ISSUE TITLE
[Zone] Nespirah VASHJ´IR Fully empty

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1132]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
No single NPC in the whole area.

![image](https://user-images.githubusercontent.com/120294125/207429368-577e0b47-9bf6-402f-8315-bc44d75e6c2a.png)
![image](https://user-images.githubusercontent.com/120294125/207429424-50a7a7a4-cf62-489a-90b5-bf75ed076908.png)

**How to reproduce:**

**How it should work:**
Get an idear which npcs are here:
https://www.youtube.com/watch?v=UqzZ5Xntnhw
https://www.youtube.com/watch?v=C5lFEeQdLrE

**Database links:**

**Comment by Loken-coolguy** [comment]
Phasing issue possibly?

**Comment by Fromtill** [comment]
> Phasing issue possibly?

Hello Loken, i cant say it. How can i see if iam inside phasing?
I just accepted the quest, to kill a special elite npc. according to youtube there should be npc´s around in the whole area.

But: i didnt enter this area the normal way (pre quest vashjir and travel by ship) because its currently not possible.

**Comment by Loken-coolguy** [comment]
> > Phasing issue possibly?
> 
> Hello Loken, i cant say it. How can i see if iam inside phasing? I just accepted the quest, to kill a special elite npc. according to youtube there should be npc´s around in the whole area.
> 
> But: i didnt enter this area the normal way (pre quest vashjir and travel by ship) because its currently not possible.

Sorry that was a comment directed to the devs hah

**Comment by UltraNix** [comment]
This area is disabled for now.
