### ISSUE TITLE
[Quest] Overseer Idra´kess (VASHJ´IR)

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1133]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
According to ##1132 there is no npc for the quest.
![image](https://user-images.githubusercontent.com/120294125/207429848-2ef9c2d5-9d0d-4be8-8d2b-d55768d7712a.png)

**How to reproduce:**

**How it should work:**
From Youtube:
![image](https://user-images.githubusercontent.com/120294125/207429804-48dac660-3996-48ad-b390-10e5b4b47996.png)

**Database links:**

**Comment by Loken-coolguy** [comment]
Possible phasing issue? NPCs missing

**Comment by UltraNix** [comment]
#1132
