### ISSUE TITLE
[VASHJ´IR] Bubbles dont refresh breath

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1134]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://user-images.githubusercontent.com/120294125/207430825-b191adfd-8368-440a-ae22-a0ece063f9af.png)

**How to reproduce:**

**How it should work:**
refresh breath while in range of bubbles on the ground

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
