### ISSUE TITLE
[NPC loot] Dormus the Camel Horder

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1135]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Dormus should have a 100% drop rate of the mount
he didnt drop it 
**How to reproduce:**

find camel figurine
kill dormus

**How it should work:**
100% drop mount

**Database links:**
https://www.wowhead.com/de/npc=50245/dormus-der-kameltreiber

**Comment by Fromtill** [comment]
> He should drop the mount only after you've killed him after clicking on the right camel figurine. if you kill him normally, you dont get loot.

Yep. He is not there "normally", because once you clicked the figurine, you gonna port inside another phasing area, only there, in this special phasing, the boss exists.

I found the figurine and got the port, from uldum :)

**Comment by bughuntard** [comment]
Okay, seems legit. Thank you. Report is valid.

**Comment by UltraNix** [comment]
Fixed.
