### ISSUE TITLE
[Spell] Deterrence (hunter)

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1136]
**Description:**

**Deterrence ID 19263**

should be 30% reduced damage taken + deflect on everything  (spells, ranged, and melee) 
**EXCEPT** the destro warlock spell **Chaos Bolt  (and NPC equivalents)**

chaos bolt IDs
79939
50796
51287
69576
71108
77069
89873

HOW IT IS WORKING RIGHT NOW
---------------------------------
Interrupts are going through deterrence and hitting the hunter

HOW IT SHOULD WORK
---------------------------------
Interrupts should NOT go through deterrence and affect the hunter while deterrence is up

**Comment by UltraNix** [comment]
@GMHiki Give us example of such interrupt effect.

**Comment by GMHiki** [comment]
examples i was given from Jimmy17 (hunter)

skull bash 80965 80964

kick 1766

rebuke 96231

silencing shot 34490

spell lock  19647

**Comment by UltraNix** [comment]
All of these spells have `SPELL_ATTR7_CANT_MISS`, so they can't miss.

**Comment by UltraNix** [comment]
`spell lock 19647` always hit.
`skull bash 80965 80964
kick 1766
rebuke 96231`
These spells are mellee spells and cannot miss.

**Comment by UltraNix** [comment]
Fixed.
