### ISSUE TITLE
[Core] Mitigation while casting

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1137]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** While casting, you shouldn't be able to dodge/parry/block, unless a skill says you can. 

**How to reproduce:** Use any channeling/casting ability while fighting mob and you can parry/dodge

**How it should work:** You shouldn't be able to mitigate attack while casting uless skill says yopu can

**Database links:**

Example 1: Blooddrinker https://www.wowhead.com/spell=206931/blooddrinker "You can move, parry, dodge... while channeling this ability" - and has this flag set: Allow Defense While Channeling

Example 2: Chi Burst https://www.wowhead.com/spell=123986/chi-burst "Brewmaster: Casting Chi Burst does not prevent avoiding attacks" - and has this flag set: Allow Defense While Casting

I also found this old wowhead comment under this thread from 2009: https://www.wowhead.com/forums/topic/can-i-block-while-casting-86262 "You cannot (block while casting). The same goes for Dodge and Parry. The opponent can still miss, though."

**Comment by UltraNix** [comment]
Fixed.
