### ISSUE TITLE
[Paladin] Bubble under charm effects

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1139]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** You should be able to use Divine Shield while under Charm effect

**How to reproduce:** Make succubus Seduce you, try casting bubble

**How it should work:** you should be able to bubble under all charm effects includign Seduction

**Database links:**
https://www.wowhead.com/classic/spell=6358/seduction

**Comment by UltraNix** [comment]
Seduction is not a charm.

**Comment by UltraNix** [comment]
Fixed.
