### ISSUE TITLE
[NPC] Xariona Worldboss wrong flight pass

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1140]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Xariona should circle on the upper stone ring of deepholm.
currently it just fly straight in the wrong direction and once far away, it ports back to the stone ring.
![image](https://user-images.githubusercontent.com/120294125/207440663-3e922c0f-ffbf-4872-ad33-57b49d7f68b0.png)
![image](https://user-images.githubusercontent.com/120294125/207440691-a33e9bb8-9137-426b-a3ff-342145947db2.png)

**How to reproduce:**

**How it should work:**

![image](https://user-images.githubusercontent.com/120294125/207440326-2673da86-6447-48f5-a189-30709a99af3d.png)

**Database links:**

**Comment by UltraNix** [comment]
Should be fixed.
