### ISSUE TITLE
[Hunter] [Pet] Roar of Recovery 

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1141]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** You can stack them by summoning different monkey pet

**How to reproduce:** Cast Roar of Recovery on your monkey pet, dismiss pet, summon another monkey, cast another Roar of Recovery. They will stack.

**How it should work:** They shouldn't stack. Short duration should be overwritten by longer duration

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=53517

**Comment by UltraNix** [comment]
Fixed.
