### ISSUE TITLE
[Core] Purging spells

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1142]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** shaman's Purge , shaman's cleanse spirit , mage's remove curse , druid's Remove Corruption , paladin's cleanse. ALL types of dispell / purge in the game should be usable even if there aren't anything to purge or dispell on the target. there shouldnt be a message saying ''there is nothing to dispell / purge '' NOTE: This is similiar to Tranqulizing Shot which was fixxed by @Afgann recently.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
