### ISSUE TITLE
[Mage] Mirror Image behavior

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1143]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Mirror Images should attack only after you attack first and they should ignore players that are in CC that can be broken via damage

**How to reproduce:** be mage, cast mirror image

**How it should work:** when i use mirror image they should be idle (not attacking anyone) unless i attack someone (after that,t hey should be in 'aggressive' mode). Also mirror image should never attack a target which is in a breakable CC such as polymorph , blind etc

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55342

**Comment by Loken-coolguy** [comment]
Confirmed, Mirror Images should only begin attacking on first targeted attack by the player. (I believe they begin attacking on the beginning of cast as well, correct?)

I am not sure about the targeting breakable CC, do you have any source or anything we can view regarding that?

**Comment by UltraNix** [comment]
Fixed.
