### ISSUE TITLE
[Pet] Autocast buffs don't work

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1144]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** no autocast buffs work on pets, the autocast is "active" but its not being autocast

**How to reproduce:** 

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Can you give an example?

**Comment by bughuntard** [comment]
Dash for example from hunter's pet

**Comment by UltraNix** [comment]
@bughuntard For me it works okay, but only in combat. (I think pet should not spam these spells out of combat).

**Comment by UltraNix** [comment]
Fixed.
