### ISSUE TITLE
[Mage] Ring of Frost

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Ring of Frost currently doesn't work if mage is CC'd. It should always work, unless mage is cycloned

**How to reproduce:** Cast Ring of Frost, get stunned

**How it should work:** Ring of Frost should always be active regardless of mage's state (as long as he's alive), with exception of Cyclone: if mage is under Cyclone, ring of frost shouldn't freeze passing players for time being

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=82676

**Comment by Loken-coolguy** [comment]
Confirmed - Ring of Frost should not be able to be interrupted

**Comment by UltraNix** [comment]
Fixed.
