### ISSUE TITLE
[Hunter][Spell] Bad Manner

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1147]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When I fake cast Bad Manner (cast then cancel), the spell is bugged and can't be used. There was another Bad Manner report fixed by @Afgann it should be connected.

**How to reproduce:** fake cast Bad Manner

**How it should work:** Bad Manner should work

**Database links:** https://cata-twinhead.twinstar.cz/?spell=90337

**Comment by UltraNix** [comment]
@bughuntard How you cancelled pet's cast?

**Comment by UltraNix** [comment]
Fixed.
