### ISSUE TITLE
[Talent] Talent Points Disappearing

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Sometimes after relogging, some talent points are missing, so some of your key abilities may also be missing. You can fix it by resetting talents.

**How to reproduce:** hard to reproduce, sometimes happens after relog (for example on DK)

**How it should work:** talents should never disappear

**Database links:**

**Comment by Loken-coolguy** [comment]
Can you give an example of a talent that goes missing? Does it seem to be random talents or the same every time? How many times has this happened

**Comment by UltraNix** [comment]
@bughuntard Have you tried buying dual spec?

**Comment by UltraNix** [comment]
No info - closing.
