### ISSUE TITLE
[Quests] Westfall

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1149]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Some bugged quests from Westfall:

Murder Was The Case That They Gave Me - Currently, you can't interrogate the Homeless Stormwind Citizens, and they also have some pathing issues - some, at the end of their patrols, randomly decide to lay down and sleep (similar to the ones at Sentinel Hill). Same issue exists at Sentinel Hill but in reverse (so that those that should normally be sleeping or sitting down randomly patrol around). Interrogating the homeless can result in the same results, while it should give you a different result each time, meaning there can only be a max of 4 successful interrogations instead of having to fish until you get them all (in my attempts, it took 17 interrogations to finish). https://www.youtube.com/watch?v=iwyW69BDYw8

Livin' the Life - The RP dialogue is full of typos. https://www.youtube.com/watch?v=08UYDyoTkDg at 1:37.

Lou's Parting Thoughts - The RP section has some typos. You get quest credit after killing one Thug, while you should only do so when you killed all four. After that, there is a phasing issue, where Lou is both alive and dead in the presence of a level 1 Horatio Lane. https://www.youtube.com/watch?v=z3zypYHoV_U

Heart of the Watcher - The quest item from the Harvest Reapers never dropped. Killed 150 to confirm. The follow up quest is inaccessible because of this.

Feeding the Hungry and the Hopeless - Pathing issues mentioned in the first report. Also, some NPCs have typo errors in their dialogue prompts, and some missing lines of dialogue as well. Right click talking to the homeless should be impossible too. https://www.youtube.com/watch?v=JBY9clrwB_E

Secrets of the Tower - A random "Tower Cannon Target" NPC - the trigger for the RP sections - is visible to the players, although this might be caused due to GM flags on PTR accounts. The Invis Potion does not grant the hazy world effect. https://www.youtube.com/watch?v=fhu7y9WCEl8

A Vision of the Past - All dialogue is missing. Some of the NPC pathing is screwed towards the end. During the fight, the priest AFKs, and the mage spams Arcane Intellect after every Arcane Missile. Tbh, this is just your average Classic WoW group. https://www.youtube.com/watch?v=SaKEUK4Nuoo at 2:47.

Evidence Collection - The starter quest item has an incredibly low chance to drop. Got it on my 9th Defias kill. Should be on the first.

Rise of the Brotherhood - The entire RP section has both missing dialogue and typos. Scout Galiaan sometimes repeats his normal, non quest-scripted dialogue lines, destroying immersion. The Blackguards in the end spam their fire torches on themselves instead of on the Tower and the surrounding area. https://www.youtube.com/watch?v=Vsn4Wjjg61w Note: the attached video is also bugged in the sense that the Chat displays the phased RP event from others - the one you should be paying attention to is the one that is playing out.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
I'm going to break this up into individual reports
