### ISSUE TITLE
[Quest] Murder Was The Case That They Gave Me

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1150]
Currently, you can't interrogate the Homeless Stormwind Citizens, and they also have some pathing issues - some, at the end of their patrols, randomly decide to lay down and sleep (similar to the ones at Sentinel Hill). Same issue exists at Sentinel Hill but in reverse (so that those that should normally be sleeping or sitting down randomly patrol around). Interrogating the homeless can result in the same results, while it should give you a different result each time, meaning there can only be a max of 4 successful interrogations instead of having to fish until you get them all (in my attempts, it took 17 interrogations to finish). https://www.youtube.com/watch?v=iwyW69BDYw8

**Comment by UltraNix** [comment]
Fixed.
