### ISSUE TITLE
[Quest] Lou's Parting Thoughts

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1152]
The RP section has some typos. You get quest credit after killing one Thug, while you should only do so when you killed all four. After that, there is a phasing issue, where Lou is both alive and dead in the presence of a level 1 Horatio Lane. https://www.youtube.com/watch?v=z3zypYHoV_U

**Comment by UltraNix** [comment]
Fixed.
