### ISSUE TITLE
[Quest] Heart of the Watcher 

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1153]
The quest item from the Harvest Reapers never dropped. Killed 150 to confirm. The follow up quest is inaccessible because of this.

**Comment by Greywolf59** [comment]
Yet as I stated on discord I got it during doing the quest to kill the Watchers. This might need retesting on some fresh toon maybe.

**Comment by UltraNix** [comment]
Drop chance is 9%. Works okay.
