### ISSUE TITLE
[Quest] A Vision of the Past

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1156]
All dialogue is missing. Some of the NPC pathing is screwed towards the end. During the fight, the priest AFKs, and the mage spams Arcane Intellect after every Arcane Missile. Tbh, this is just your average Classic WoW group. https://www.youtube.com/watch?v=SaKEUK4Nuoo at 2:47.

**Comment by Greywolf59** [comment]
Similar post, mention: https://github.com/gamefreedomgit/Maelstrom/issues/1122

**Comment by UltraNix** [comment]
#1122
