### ISSUE TITLE
[Throne of the Tides] Lady Naz'jar & Mindbender Ghursha

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1158]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Lady Nazjar doesn't become immune at her 2nd Phase, and Mindbender Ghursha isn't working correctly at all.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=USPsmol4rK0 Lady Naz'Jar Normal
https://www.youtube.com/watch?v=AMIV_4f4IpA Lady Naz'jar HC
https://www.youtube.com/watch?v=x59xIOWgOEk Mindbender Ghursha normal
https://www.youtube.com/watch?v=NM7g3d9zqNo Mindbender Ghursha Heroic

**Database links:**
https://www.wowhead.com/npc=40586/lady-nazjar
https://www.wowhead.com/npc=40788/mindbender-ghursha

**Comment by Afgann** [comment]
fixed
