### ISSUE TITLE
[Quest] Rise of the Brotherhood

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1159]
The entire RP section has both missing dialogue and typos. Scout Galiaan sometimes repeats his normal, non quest-scripted dialogue lines, destroying immersion. The Blackguards in the end spam their fire torches on themselves instead of on the Tower and the surrounding area. https://www.youtube.com/watch?v=Vsn4Wjjg61w Note: the attached video is also bugged in the sense that the Chat displays the phased RP event from others - the one you should be paying attention to is the one that is playing out.

**Comment by Greywolf59** [comment]
I can confirm that part about Scout Galiaan and the torches. My memory is shit so I can't attest to the RP as a whole but truth is it felt like there could be more.

**Comment by UltraNix** [comment]
Fixed.
