### ISSUE TITLE
[Throne of the Tides] Transport elevator

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1160]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Elevator is bugged - it can kill you when you're jumping and even if your corpse is close to healer, it says Out Of Range when he tries to resurrect

**How to reproduce:**

**How it should work:** It should work like all other elevators

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
