### ISSUE TITLE
[Quest] On Her Majesty's Secret Service

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1161]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Commander Lorna Crowley does her first interaction with the player's escorts but no more of the RP interaction happens. There should be about a minute worth of dialogue between the NPCs before Lorna initiates combat.

**Database links:**
Quest completion video: https://www .youtube.com/watch?v=B7FaY9tnyuI&ab_channel=Finom
Quest: https://cata-twinhead.twinstar.cz/?quest=27594
Commander Lorna Crowley: https://cata-twinhead.twinstar.cz/?npc=45997

**Comment by UltraNix** [comment]
![obraz_2022-12-22_220245893](https://user-images.githubusercontent.com/80540499/209225439-31436c1e-9f0f-4091-a54c-a9127303ec8f.png)
Works okay.

**Comment by MrTide** [comment]
Update: watched a player do it and it didnt work reopening the issue

**Comment by KevlinTallfellow** [comment]
The interactions between Lorna and Godfrey still fail to happen as of Jan 15 2024.

**Comment by GM-Nightmaree** [comment]
Quest is working fine 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/157993777/1af50690-678e-4f73-a999-961bcf1eb144)
as in 24/4/2024

**Comment by PanJanuszek** [comment]
not a issue anymore
