### ISSUE TITLE
[Hunter] Camouflage breaking

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1162]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Camouflage should break after your trap deals damage/explodes; not when you lay that trap. Camouflage doesn't currently break when your trap deals damage. 

**How to reproduce:** Use Trap Laucher skill, then launch Immolation Trap. 

**How it should work:** Launching trap shouldn't break camouflage. Traps exploding/dealing damage should break camouflage such as explosive trap or snake trap

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
