### ISSUE TITLE
[Combat Pets] Mounting

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1163]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** when i mount my pet is friendly to the enemy which is wrong. pet should always be hostile doesn't matter if im mounted or not, but when you're on a mount, your pets can't be attacked.

**How to reproduce:**

**How it should work:** When you are mounted on ground mount, your pet should be still with you, but Pet Bar should be greyed out, but it should be attackable (red). If you are on flying mount your pet should disappear.

**Database links:**

**Comment by Loken-coolguy** [comment]
Do you know if this is happening with every combat pet, or which combat pet did you experience this with?

**Comment by UltraNix** [comment]
@bughuntard As I can see this somethign clientside. Do you have any video with pet being attackable while its master mounting? Maybe Blizz wanted to protect pets while mounting?
