### ISSUE TITLE
[Warrior] Spell Reflect + Grounding Totem 

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1164]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Spell Reflect is consumed after warrior is hit by certain magical abilitiies that can't be reflected. It's the same for Grounding Totem.

**How to reproduce:** Have Grounding Totem / warrior with spell reflect up. Cast Frostfire Orb/Flame Orb/Searing Totem. Then Grounding Totem/Spell Reflect will be consumed, but it shouldnt

**How it should work:** it should be consumed after reflecting spell

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
