### ISSUE TITLE
[Mage] Flame Orb

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1165]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** It spawns underground 

**How to reproduce:**

**How it should work:**

**Database links:** I think its correct id https://cata-twinhead.twinstar.cz/?spell=82731

**Comment by Afgann** [comment]
fixed
