### ISSUE TITLE
[Quest] Rolling with my Homies

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1166]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Hotrod kicks you out as soon as you "mount" it 

**How to reproduce:** Get quest, enter hotrod

**How it should work:**
it shouldnt kick you out

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=14071

**Comment by UltraNix** [comment]
Should be fixed. @bughuntard Could you test it again?
