### ISSUE TITLE
[Pets] Assist stance

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1167]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Assist stance doesnt make your pet respond when you are attacked by NPCs

**How to reproduce:** have pet with Assist stance (any pet)

**How it should work:**  Assist stance should also make your pet attack enemy that attacks you (player)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
