### ISSUE TITLE
[Shaman] Spirit Link Totem

### ISSUE THREAD

**Issue by bughuntard** [gamefreedomgit/Maelstrom#1168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Spirit Link Totem shouldn't work when your partner is cycloned. t's working fine with smoke bomb , should be the same with cyclone. To elaborate - Shaman still takes damage during the spirit link but the partner receives nothing, both parties shouldn't take damage if this is the case

**How to reproduce:** cast spirit link totem, get cycloned, let your party member be attacked.

**How it should work:** cycloned partner shouldnt receive any damage from spirit link totem

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
This one needs to be revisited.

 https://www.mmo-champion.com/threads/978719-Resto-shaman-arena-tips?highlight=Cyclone+spirit+link+totem

> Spirit Link Totem does affect your and your partners health while you're cycloned.

No hotfixes, or patch notes mentioning any change to this and this was posted late 2011.
 
Also fixed to work through cyclone on Twinstar. https://cata-twinhead.twinstar.cz/?fixreport=show&id=10983

**Comment by bonfax4** [comment]
@UltraNix

**Comment by UltraNix** [comment]
It's nearly 1-year report - no sense to reopen. Make a new one.
