### ISSUE TITLE
[Quest] Elemental Bonds: Doubt (uldum)

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1170]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Once you fly up with the vortex, you should trigger a event to help thrall.
currently you can kill as much elementals you want, you cant trigger it or finish the quest.

![image](https://user-images.githubusercontent.com/120294125/207456153-dcdb3bd6-0f74-4807-b044-9b5cd42eb0fd.png)

**How to reproduce:**

accept the quest, fly up with vortex and try to complete the quest

**How it should work:**
https://www.youtube.com/watch?v=iAU5Qaf7pAI

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
