### ISSUE TITLE
[NPC] Mysterious Camel Figurine 

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1171]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
there are two different npc id:
50410
50409
![image](https://user-images.githubusercontent.com/120294125/207457811-be788cbd-2eaa-4a01-988d-cd98084693b9.png)

There are several spawn locations in whole uldum.
There should be only 1 camel figurine out of two npc ids out there in the whole area in the same time.

currently, if u fly around in uldum, you can find a lot of camel figurines in the whole area at the same time.

currently working:

different spawn locations
different npc ids

currently not working:

respawn time
1 respawn per all locations (only 1 npc out there)
respawn time, check below description

**How to reproduce:**

**How it should work:**

There are two Mysterious Camel Figurines, each with a separate NPC ID:

50409 will briefly incapacitate the player using [ Sandstorm](https://www.wowhead.com/spell=93473/sandstorm) and then teleport them to a phased instance of the Steam Pools in southern Feralas where [Dormus the Camel-Hoarder](https://www.wowhead.com/npc=50245/dormus-the-camel-hoarder) is located.

50410 will turn to into a pile of dust from which a player can loot [ Crumbled Statue Remnants](https://www.wowhead.com/item=67444/crumbled-statue-remnants) as a consolation prize. Consider this much like Vyrsagosa spawning instead of the [Time-Lost Proto-Drake](https://www.wowhead.com/npc=32491/time-lost-proto-drake) or the Blood Seeker spawning instead of [Aeonaxx](https://www.wowhead.com/npc=50062/aeonaxx).

Both share an identical model (with varying colours upon spawning that do not whatsoever reflect a difference in their NPC IDs) and a 50409 Figurine will never turn to dust and neither will a 50410 Figurine ever teleport the player.

Only one Mysterious Camel Figurine of either ID will be available at any given point of time and it is estimated the ratio of spawns is one 50409 per every sixteen 50410.

Estimated respawn times currently span 5-22 hours (extremely similar to the Time-Lost Proto Drake and Aeonaxx).

**Database links:**
https://wowpedia.fandom.com/wiki/Mysterious_Camel_Figurine

**Comment by UltraNix** [comment]
Fixed.
