### ISSUE TITLE
Cannot leave the combat 

### ISSUE THREAD

**Issue by mniert** [gamefreedomgit/Maelstrom#1172]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When running away from the combat even the mob also ran away, the game don't make the player leave the combat. I am standing still for a 5 mins or so and still my char is counted to be in a combat. I tried this with a rogue and even casting Vanish don't solve it.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Can you tell us which mob this is happening with?

**Comment by mniert** [comment]
> Can you tell us which mob this is happening with?

it doesn't happen with a specific mob type and happens randomly

**Comment by UltraNix** [comment]
@mniert Yep - It happens maybe with mobs' pets?

**Comment by mniert** [comment]
I am sure that is not. I've tested it today once again with a target dummy and it ended up with waiting about 5 mins solid waiting and an alt + F4. But what I am not sure about is the frequency of occurrence.

**Comment by UltraNix** [comment]
Problem should be resolved soon.

**Comment by UltraNix** [comment]
Fixed.
