### ISSUE TITLE
[Quest] Easy Money - Starting Quest Uldum

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1173]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Once you pick up the quest from town board (horde) you gonna go to south tanaris to accept "Easy Money".

The cinematic works fine, very good!

But after the cinematic finished, you wake up inside a prison:
![image](https://user-images.githubusercontent.com/120294125/207461308-53b4e9aa-2d19-42c1-8f83-5382b40d58cd.png)

And the quest, is still not finished:
![image](https://user-images.githubusercontent.com/120294125/207461550-16dc31ac-a9fe-4919-9a4c-9454fe76fc90.png)

**How to reproduce:**
Accept quest easy money
mount to the camel (triggers cinematic)
wait until ends, and you wake up in the prison.

**How it should work:**
Once you wake up in the prison, the quest should be finished
The NPC to complete quest, is inside prison too.
https://www.youtube.com/watch?v=iSgkJJmqMX4
![image](https://user-images.githubusercontent.com/120294125/207461855-d5c88322-45b8-428b-a30c-1dbce3edfd2f.png)

**Database links:**

**Comment by Afgann** [comment]
fixed
