### ISSUE TITLE
[Quest] The Ballad of Maximillian 24707

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1174]
Quest ID **24707**

How it works
-------------------------
When you mount on Maximillian's horse to fight the "dragon queen" it is supposed to act as a taxi and take you around ungoro until you find the dragon queen. The waypoints or pathing are screwed up and it flies and runs through the ground instead of pathing on the ground like normal.

(you are able to complete the quest, the mount/taxi pathing is just messy)

How it should work
-------------------------
Should mount up and path on ground plane, not glitch through floor and fly

**Comment by UltraNix** [comment]
It's okay - you must control it.
