### ISSUE TITLE
[Quest] By the Skin of His Teeth

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1176]
quest not working after 2 minute it's not completed...

**Comment by MrTide** [comment]
I tried to do this quest, event started, mobs spawned but couldnt finish it .. no credit nothing..

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/209314025-4170e6c7-1bf1-4d65-b4b9-6af758392f1d.png)
Works okay to me.

**Comment by UltraNix** [comment]
@MrTide The waves  of mobs stopped spawning after 2 mins?

**Comment by gaga-whitemane** [comment]
I cannot reproduce this issue either.

**Comment by MrTide** [comment]
@UltraNix yes they did i believe they stopped spawning right on time but i didnt get credit thats all
