### ISSUE TITLE
[Core] Equipping Weapon Resets GCD

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1177]
fytchx
OP
 — 12/10/2022 1:54 PM
when you equip a weapon, it resets your global cooldown

**Comment by UltraNix** [comment]
@Loken-coolguy I can't reproduce it. In combat, you are allowed to change weapon once per 1.5 sec.

**Comment by MrTide** [comment]
I can't reproduce it neither gonna close it
