### ISSUE TITLE
[Quest] Death Comes From On High

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1178]
Unintendet
OP
 — 12/10/2022 6:14 PM
while flying the eye, and pressing the scan thingy it instant completes it, also the monsters do not attack you. they should ...Edit, after leaving the Eye you move with 100000 Movespeed - Quest = Death Comes From On High

**Comment by MrTide** [comment]
1. What player means that he doesnt need to wait until cast is finished, which is incorrect and he is right
![image](https://user-images.githubusercontent.com/36106057/209171455-8faacbf9-b48e-4293-bfa0-c6b79482901e.png)
 
2. and getting extra move speed part is also correct
 
getting attacked part works i couldnt find an issue there

**Comment by MrTide** [comment]
Similar issue

**Comment by UltraNix** [comment]
Fixed.
