### ISSUE TITLE
[Quest] The Gift That Keeps On Giving

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1179]
Unintendet
OP
 — 12/10/2022 6:43 PM
Quest = The Gift That Keeps On Giving only turns one Miner into an Ghoul, it should turn everyone in that Radius into one. The Miners in General aren't moving theyr Carts, they just walk around it.

**Comment by MrTide** [comment]
It does work on those miners but not all at the same time there should be a delay between them which is correct behavior
and yes player is correct miners that are supposed to move the carts are not doing it and also the throwing object missing gas animation

**Comment by UltraNix** [comment]
`the throwing object missing gas animation`
Won't fix.

**Comment by UltraNix** [comment]
Fixed.
