### ISSUE TITLE
[Quest] Victory At Death's Breach!

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1180]
Unintendet
OP
 — 12/10/2022 6:54 PM
Quest = Victory At Death's Breach! ... Maybe I was to stupid for it but the Teleport didn't port me Up, or the Fly-guy to Fly Up is missing.

**Comment by MrTide** [comment]
looks like they are falling through the ground i managed to screenshot it for you guys
![image](https://user-images.githubusercontent.com/36106057/209176390-ff355575-e7ac-4ffb-8d8a-72c93820ccf7.png)

**Comment by UltraNix** [comment]
Already fixed.
