### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1183]
Unintendet
OP
 — 12/10/2022 7:25 PM
Quest = Bloody Breakout - all the Priest guy was doing is casting renew, not 1 other auto-hit or spell was used by him, shouldn't be the case, I also can't loot its head which makes the quest incomplete able - The Priest can Turn Undead the Quest giver making him run around in circles, shouldn't be the case

**Comment by MrTide** [comment]
this quest is not scripted at all he just goes out ignores everything and you can't even complete it
![image](https://user-images.githubusercontent.com/36106057/209179504-70e5d504-69de-41b2-976b-fc5cb3fc6501.png)
![image](https://user-images.githubusercontent.com/36106057/209179521-7ba2d635-026e-4658-91ba-bcc1ec62ae60.png)

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/1284 similar issue

**Comment by UltraNix** [comment]
Fixed.
