### ISSUE TITLE
[Priest][Spell] Mindblast & Mindspike

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1184]
Chris99
OP
 — 12/10/2022 10:29 PM
Mindblast and Mindspike do not light up when reaching 3 Shadoworbs

**Comment by UltraNix** [comment]
![WoWScrnShot_121422_200727](https://user-images.githubusercontent.com/80540499/207691874-ddf9b5e1-9ad5-4336-8bd6-967a740fbdf2.jpg)
Works okay.

**Comment by MrTide** [comment]
![image](https://user-images.githubusercontent.com/36106057/209180624-b2950500-1ec4-4327-a8cb-7eab63e0671f.png)
its possible that is client related its not working for me neither
