### ISSUE TITLE
[DK Starting Zone] Runeforges 

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1186]
Unintendet
OP
 — 12/10/2022 9:43 PM
After the Starter Area, the Runeforges are missing, you can still enchant your weapon doe, even tough the forges are missing

GaGa — 12/11/2022 5:58 AM
What? You can runeforge you weapon without being near the Runeforge?

Jeko — 12/11/2022 6:27 AM
I think he means the Runeforges are not appearing but u can still Runeforge when you are at the spot where it should be, so i think he is talking about a visual bug of the forge itself

Unintendet
OP
 — 12/11/2022 6:33 AM
Exactly.

**Comment by MrTide** [comment]
Player is correct they are missing 
but waypoint is still there so players can still use it as it explained on the message
![image](https://user-images.githubusercontent.com/36106057/209186475-361b368e-7106-4e49-9cbf-efe172c374a5.png)

![image](https://user-images.githubusercontent.com/36106057/209186475-361b368e-7106-4e49-9cbf-efe172c374a5.png)

**Comment by UltraNix** [comment]
Fixed.
