### ISSUE TITLE
[Druid] Skull Bash vs Immunities

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1189]
Jimmy17
OP
 — 12/11/2022 7:27 AM
When you skull bash on ice block or paladin's bubble it wont charge you to the target. it should charge you to the target even if the target is immune

SylahUmehara — 12/11/2022 7:27 AM
Both cat and bear skull bash suffer from this

**Comment by Afgann** [comment]
fixed
