### ISSUE TITLE
[NPC][Quest] Goblin Escape Pod & Geargrinder Gizmo

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1194]
Muro
OP
 — Today at 1:41 PM
After doing the intro quest as a goblin, when waking up on Shipwreck Shore after talking to Dic Zapnozzle, The NPC (Geargrinder Gizmo) beside him didnt give additional quest that called "Goblin Escape Pod"

**Comment by UltraNix** [comment]
https://www.wowhead.com/quest=14239/dont-go-into-the-light#comments:id=5458413
