### ISSUE TITLE
[Quest] End of the Supply Line

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1195]
Buuba
OP
 — Yesterday at 3:52 AM
Twilight Proveditor and Twilight Slavedriver keep walking, dont get aggroed and reset their HP

Zyncrow — Yesterday at 9:51 AM
Wasn't for me the case, maybe it's just you.
Edit: worked for me fine but Buuba still got ignored by them.

**Comment by UltraNix** [comment]
Tested - works okay.
