### ISSUE TITLE
(Quest) King of the Foulweald

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1196]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The Foulweald Furbolgs and Chief Margut should appear in waves, currently they appear all at once.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=vit7hvQxPCc&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=6621

**Comment by UltraNix** [comment]
Fixed.
