### ISSUE TITLE
[Hunter] Trap Activation Delay

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1198]
Jimmy17
OP
 — 12/11/2022 8:28 AM
Traps should take exactly 1 sec to trigger after landing on the floor. Sometimes it's delayed not sure i think its when there are pets arround the target or multiple enemies

**Comment by Afgann** [comment]
fixed

**Comment by bigticketx** [comment]
It's bugged again,sometimes procs after 1sec,sometimes after 2-3secs.
It should always be 1second
