### ISSUE TITLE
[Quest] Breaking the Line

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1200]
Bols
OP
 — Yesterday at 3:23 AM
When the raptor is mounted, he stuck for a while during the jump and starts to swim on the land.

**Comment by UltraNix** [comment]
Already fixed.

**Comment by WhitemaneSylah** [comment]
Raptor does not spawn anymore 

https://www.wowhead.com/quest=25035/breaking-the-line#comments
Non bugged: https://www.youtube.com/watch?v=hhWvuERXG6s
Bugged: https://www.youtube.com/watch?v=jU5edALmhVk

**Comment by UltraNix** [comment]
Fixed.
