### ISSUE TITLE
[Warrior] Heroic Leap

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1202]
Jimmy17
OP
 — Yesterday at 2:31 AM
Both pathing and height distance is wrong.

height , a warrior shouldn't be able to heroic leap in blades edge arena's Bridge from down.

pathing , warrior should jump more vertically instead of straight line

SylahUmehara — Yesterday at 2:50 AM
Also to add that Warriors can almost jump onto the boxes in dalaran ruins

**Comment by Afgann** [comment]
fixed

**Comment by UltraNix** [comment]
@WhitemaneSylah Why reopened?

**Comment by WhitemaneSylah** [comment]
no longer needed
