### ISSUE TITLE
[Fear] Target Pathing

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1205]
Jimmy17
OP
 — Yesterday at 2:35 AM
Feared target shouldn't walk where there is no Ground colision (shouldn't be able to walk in the air). 

Jimmy17
OP
 — Yesterday at 2:40 AM
also Pet pathing is wrong , for example in blades edge arena if im standing with my pet on top of the stone and i pet move to down (ground). my pet will just ignore the the whole path and running through the air

**Comment by UltraNix** [comment]
Pet always shortcut its way to master (to prevent stucking). It won't work different.
