### ISSUE TITLE
[Core] Spammable CC

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1216]
spammable CC such as polymorph or cyclone or entangling roots

Jimmy17
OP
 — 12/11/2022 11:34 PM
All these spells should have an error message saying  ''a more power spell is already active''  if you  use  it on a target that is already struck  by any of those CC and the active CC's duration is greater than the one that is being casted. 
for example i cast roots which is 8 sec duration > if i try to cast root when my 1st roo at 6 sec it shouldn't work and it sohuld say ''a more power spell is already active''
but if the 1st root is  at 3 secs then my root should be casted cz the 2nd casted root is 4 sec ( of of the DR) which is  higher than 3 secs.

**Comment by Afgann** [comment]
fixed
