### ISSUE TITLE
[Quest] A Scarlet Letter 

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1219]
neobludragon
OP
 — 12/11/2022 6:16 PM
NPC not disapearing and not appearing next to llian

https://cdn.discordapp.com/attachments/1051683900306493470/1051683900407173200/image.png

**Comment by MrTide** [comment]
can confirm npc goes through the floor and have pathing issues as well
also i believe causes server to crash needs attention

**Comment by MrTide** [comment]
crashing issue solved but still quest is not working properly
like player said, pathing got issues and also Voss is not killing gebler

**Comment by UltraNix** [comment]
Fixed.
