### ISSUE TITLE
[Spell] Mana Tide Totem & Mana Spring Totem

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1220]
SylahUmehara
OP
 — 12/11/2022 4:00 PM
neither totem generates additional mana.  Mana Spring is supposed to generate 326 per 5 seconds and Mana Tide is supposed to pulse and generate mana equal to 200% of the casters spirit,  both not working

**Comment by shinzo69** [comment]
can confirm, atleast for Mana Spring Totem on lvl 42.

**Comment by MrTide** [comment]
both working i couldn't reproduce this issue, your states changes and all. i didnt find anything wrong with this

**Comment by shinzo69** [comment]
https://streamable.com/3tkd60 not exactly sure but in my eyes there arent any 25 mana jumps in my vid so i assume its not working

**Comment by UltraNix** [comment]
ALso tested - I see no bug.
