### ISSUE TITLE
[Dungeon] Scarlet Monastery Cathedral Doors

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1226]
Titan
OP
 — 12/11/2022 9:30 AM
Scarlet Monastery Cathedral the doors into the  actual  cathedral were  open initially when starting the dungeon, after completing the dungeon/pulling the boss they closed behind  me and did not reopen so i was locked in the dungeon
https://cdn.discordapp.com/attachments/1051551666832408697/1051551667180540005/cathdoors.png

**Comment by Afgann** [comment]
fixed
