### ISSUE TITLE
Undercity Elevator

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1227]
UC West Elevator Broken
Titan
OP
 — 12/11/2022 9:16 AM
Door at the bottom  of the elevator is not closing when it  goes  up.

**Comment by MrTide** [comment]
player is right there is one that is not closing
west side
![image](https://user-images.githubusercontent.com/36106057/209188973-c49b287c-c2e3-441a-b08e-58f3d5f56122.png)
![image](https://user-images.githubusercontent.com/36106057/209188992-609d4733-3747-4f94-b870-94a8398865f9.png)

**Comment by UltraNix** [comment]
Fixed.
