### ISSUE TITLE
[Quest] Inciting the Elements

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1228]
Mitosis
OP
 — 12/11/2022 10:18 AM
The berries have very limited spawn locations that dont reflect retail spots or amount, and mobs have basic stealth and are detectable without feeding a berry to a faerie dragon, which should be the only way to unstealth them. Doing this mechanic results in mob being out of stealth for 1 second then despawning if not tagged. The mobs also have limited spawns that do not reflect the way it used to be

(https://www.wowhead.com/item=53009/juniper-berries)

**Comment by MrTide** [comment]
there are enough of them just spread in different locations 
i believe some correction is required but its up to developers.
https://www.youtube.com/watch?v=SJ3GL1bLJ4k

**Comment by UltraNix** [comment]
Fixed.
