### ISSUE TITLE
Mobs run away into terrain

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1229]
Mitosis
OP
 — 12/11/2022 10:15 AM
You can therefor charge, shadowcloak, etc out of bounds by simply using your rotation and the mob decides to run away through terrain

**Comment by UltraNix** [comment]
Useless report. Need more info where did it happen (screenshots, locations, etc)

**Comment by UltraNix** [comment]
Spot? Location? Mob name?

**Comment by UltraNix** [comment]
No info - closing.
