### ISSUE TITLE
[Quest] Personal Summons

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1232]
Quest 28790 [Personal Summons] the start of the chain for vash'ir doesnt pop up

Mitosis
OP
 — 12/11/2022 10:05 AM
Similar quests once you go into an area doesnt work either. its supposed to automaticly trigger when you visit a certain area(depending on the quest), you will get a popup top right corner under minimap asking you if you want to accept the quest

**Comment by UltraNix** [comment]
#1130.
