### ISSUE TITLE
[Hunter] Traps Disappearing

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1235]
Traps sometimes dissapear randomly

Jimmy17
OP
 — 12/11/2022 5:56 AM
no idea what's causing it

saral — 12/11/2022 6:35 AM
They May Just expire

Jimmy17
OP
 — 12/11/2022 6:43 AM
nop
1 min for expiration.

Jimmy17
OP
 — 12/11/2022 10:00 AM
1 of the cause is when a stealther step on a trap

**Comment by UltraNix** [comment]
Fixed.
