### ISSUE TITLE
[ITEM/BUFF/QUEST] Smoulderthorn Troll Disguise

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1240]
You cannot remove this Buff from yourself, impeding questlines in the future.

ITEMID for disguise
https://cata-twinhead.twinstar.cz/?item=63357

SPELLIDs
https://cata-twinhead.twinstar.cz/?spell=89259
https://cata-twinhead.twinstar.cz/?spell=89260

HOW IT WORKS
------------------------
You put on the disguise and it gives you a buff that disguises you from certain mobs for quests.
It is not removable and it doesnt auto remove it when quest completes.

HOW IT SHOULD WORK
------------------------
You should be able to remove the buff at your leisure.

**Comment by UltraNix** [comment]
Fixed.
