### ISSUE TITLE
(Quest) Shadumbra's Head - Missing

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1241]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After killing Shadumbra, the item Shadumbra's Head should be a 100% drop chance.

**Database links:**
Shadumbra: https://cata-twinhead.twinstar.cz/?npc=12677
Shadumbra's Head (item): https://cata-twinhead.twinstar.cz/?item=16304
Shadumbra's Head (quest): https://cata-twinhead.twinstar.cz/?quest=24

**Comment by Afgann** [comment]
fixed
