### ISSUE TITLE
(Quest) We're Here to Do One Thing, Maybe Two...

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1242]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The Krom'gar Wagon's pathing is not correct and goes through terrain. The quest is still completable, just janky :D

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=drF9VJMtIGg&ab_channel=GamesTV
Quest: https://cata-twinhead.twinstar.cz/?quest=25945
Krom'gar Wagon: https://cata-twinhead.twinstar.cz/?npc=41744

**Comment by UltraNix** [comment]
Already fixed.
