### ISSUE TITLE
(Quest) A Blight Upon the Land

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1243]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

During the encounter, only Warden Stillwater should attack the player and his allies while the surrounding 8 Sludge Guards use their ability [Blight Spray] the player. Currently Warden Stillwater and all 8 surrounding will melee attack the player.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=WfY54ffU-B4&ab_channel=GitGudGuides
Quest: https://cata-twinhead.twinstar.cz/?quest=28237
Warden Stillwater: https://cata-twinhead.twinstar.cz/?npc=48080
Sludge Guard: https://cata-twinhead.twinstar.cz/?npc=47786
Blight Spray (spell): https://cata-twinhead.twinstar.cz/?spell=88945

**Comment by UltraNix** [comment]
Fixed.
