### ISSUE TITLE
(Quest) Kasha Will Fly Again

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1244]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The quest objects, Mudsnout Blossom, either respawn too slow or there are not enough in the area. The quest is currently completable, but the player must wait for them to respawn.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=BbJ_9pF1GzY&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=28354
Mudsnout Blossom (object): https://cata-twinhead.twinstar.cz/?object=1723

**Comment by UltraNix** [comment]
Fixed.
