### ISSUE TITLE
(Quest) Heroes of the Horde!

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1245]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After looting the Alliance Battle Plans, Kasha should appear and pick up the player and Kingslayer Orkus, taking them to Tarren Mill. As of right now, Kasha does not appear after the player loots the plans, the quest cannot be completed.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=3JqbRm4zmQM&ab_channel=GitGudGuides
Quest: https://cata-twinhead.twinstar.cz/?quest=28400

**Comment by UltraNix** [comment]
Tested - works okay.

**Comment by mserkanoz** [comment]
It is still bugged. I tried 5 times yesterday and Kasha never appeared.

**Comment by maxstain** [comment]
Still bugged, please fix.
