### ISSUE TITLE
Extra NPCs in Stonetalon Mountains

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1247]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

There are several Deviate Guardians and Deviate Ravagers in Stonetalon Mountains around (63, 68) in Boulderslide Ravine. These NPCs are meant to only be in Wailing Caverns.
Stone Guard Kurjack and Bovaal Whitehorn are also underground somewhere around (67, 86) for some reason, according to my mini map. These NPCs are meant to only be inside Ragefire Chasm.

**Comment by Afgann** [comment]
fixed
