### ISSUE TITLE
[Quest] Our Mortal Enemies 

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1248]
[QUEST ID 26648](https://cata-twinhead.twinstar.cz/?quest=26648)

WHAT IS HAPPENING
-------------------------
You must kill 15 [Ninjas](https://cata-twinhead.twinstar.cz/?npc=43553) on Jaguero Island after summoning npc with item (he has a buff that is on him that is supposed to allow you to see the Ninjas)
Use [item](https://cata-twinhead.twinstar.cz/?item=59226) to summon ["Dead-Eye" Drederick Mcgumm](https://cata-twinhead.twinstar.cz/?npc=43557)  This all works fine.

But the [Ninja](https://cata-twinhead.twinstar.cz/?npc=43553) do not show up when he is summoned, although they are spawned there on some other phasing (checked with GM mode and i can see them)

WHAT SHOULD HAPPEN
-------------------------
After you summon npc with item, the Ninjas should show up and you should be able to kill them.

**Comment by gaga-whitemane** [comment]
Tested and working. Appears the spell for this quest has been fixed around other issues.
