### ISSUE TITLE
(NPC) Pridewing Wyvern

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1249]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

There are not enough Pridewing Wyvern in the area near Mirkfallon Lake, Stonetalon Mountains, there are currently only 5.

**Database links:**
Pridewing Wyvern: https://cata-twinhead.twinstar.cz/?npc=4012

**Comment by UltraNix** [comment]
Fixed.
