### ISSUE TITLE
(Quest) Final Delivery

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1250]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Due to phasing, the NPC General Grebo is missing from Cliffwalker Post until the player completes [Betrayal at the Grove]

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=VcGcn7eSozo&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=26077
General Grebo: https://cata-twinhead.twinstar.cz/?npc=42050

**Comment by UltraNix** [comment]
Fixed.
