### ISSUE TITLE
(Quest) Nighttime in the Jungle [H]

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1254]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The Zul'mamwe Braziers cannot be interacted with, the quest cannot be completed.

**Database links:**
Quest completion video: https://www.youtube.com/watch?v=bRNtEOuGFBE&ab_channel=WorldOfWarcraftGuidesAndGameplay
Quest: https://cata-twinhead.twinstar.cz/?quest=26304
Zul'mamwe Brazier: https://cata-twinhead.twinstar.cz/?object=204247

**Comment by Greywolf59** [comment]
My problem was different: See point 11 here https://github.com/gamefreedomgit/Maelstrom/issues/1278

**Comment by UltraNix** [comment]
Fixed.
