### ISSUE TITLE
[Quest] Call of Duty (H)

### ISSUE THREAD

**Issue by mniert** [gamefreedomgit/Maelstrom#1255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest Call of Duty fails as the player takes it 

**How to reproduce:**

**How it should work:**

**Database links:**
Quest: https://www.wowhead.com/quest=25924/call-of-duty

**Comment by Loken-coolguy** [comment]
Duplicate https://github.com/gamefreedomgit/Maelstrom/issues/1130
