### ISSUE TITLE
Duskwood Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1256]
Basis for check, comparisons and further research that led to the report. All info was verified it was indeed valid for Cataclysm itself:
https://www.youtube.com/watch?v=H3iMnHrQpKY

1: [Mound of Dirt](https://www.wowhead.com/object=19030/mound-of-dirt#comments) does not spawn [Velinde Starsong](https://www.wowhead.com/npc=3946/velinde-starsong) when clicked.
She should appear when you click the mound and say: "I have failed...failed in my duty...failed my people...The worgen run rampart, and the Scythe of my goddess is lost."
"The evil I have unleashed...In whose hand does the power my goddess granted to me now lie...by whose hand is it directed?"
TIMESTAMP: 49:08

2: [Briarthorn](https://cata-twinhead.twinstar.cz/?object=1621) in tree at 76.3/30.2

3: [Watcher Eva](https://www.wowhead.com/npc=45740/watcher-eva) did not want to fight me when he stood near [Blind Mary](https://cata-twinhead.twinstar.cz/?npc=302)'s House.
When attacked he did not fight back but I stayed in combat. His HP was resetting back to full after attacking him.
This problme was resolved after he moved away from the house and I also went for Alt + F4 to get rid of the combat bug. Killable after that. Might be one odd event that was resolved by the relog but hard to say atm.
Wowhead comment says he should be neutral NPC but iirc he is Hostile NPC, however he does not attack you even if you approach him.

4: [Mistmantle's Revenge](https://www.wowhead.com/quest=26674/mistmantles-revenge)
The event when you use the [Mistmantle Family Ring](https://www.wowhead.com/item=59363/mistmantle-family-ring) could use some work on it.
The NPCs spawn rather out of nowhere. The dialog between the brothers is fine, although a bit overlapping.
When [Tobias Mistmantle](https://www.wowhead.com/npc=43797/tobias-mistmantle) enters worgen form he should start fighting with his brother which does not happen. Neither of them is fighting, player has to attack [Stalvan Mistmantle](https://www.wowhead.com/npc=315/stalvan-mistmantle) and kill him on his own.
TIMESTAMP 1:00:05

5: [The Embalmer's Revenge](https://www.wowhead.com/quest=26727/the-embalmers-revenge)
When you start the quest, the town is set on fire and [Stitches](https://www.wowhead.com/npc=43862/stitches) is wreacking havoc around.
I don't think there was enough fires burning around on our server.
I haven't noticed [Abercrombie](https://www.wowhead.com/npc=43915/abercrombie) sitting on the Stitches' shoulder.
Immediately after killing Stitches, he despawns, respawns and starts attacking the village again until you hand in the quest.
TIMESTAMP: 1:27:05

6: [Sven Yorgen](https://www.wowhead.com/npc=43861/sven-yorgen) is visible in the camp before completing. He should spawn only after completing quest [Cry for the Moon](https://www.wowhead.com/quest=26760/cry-for-the-moon).
TIMESTAMP 1:33:18 (no NPC); 1:43:58 (NPC visible after quest)

7: [Cry for the Moon](https://www.wowhead.com/quest=26760/cry-for-the-moon)
When you accept the quest, [Oliver Harris](https://www.wowhead.com/npc=43730/oliver-harris) should disappear and his roleplay [event version](https://www.wowhead.com/npc=43858/oliver-harris) should appear.
His roleplay version appears but his normal version still remains. Sven Yorgen also still remains.
Iirc the whole interaction between the [Lurking Worgen](https://www.wowhead.com/npc=43950/lurking-worgen) and [Jitters](https://www.wowhead.com/npc=43859/jitters) does not look as nice as in the video.
There is also a typo in yelled speech of the Lurking Worgen "Every speAk of suffering..." instead of speCk. There might be more.
TIMESTAMP: 1:42:52

8: [Bone Chewers](https://cata-twinhead.twinstar.cz/?npc=210) and [Plague Spreaders](https://cata-twinhead.twinstar.cz/?npc=604) stay red on target after they die, instead of gray.

9: [Buried Corpses](https://www.wowhead.com/npc=43851/buried-corpse#abilities) are invisible and for a few secs untargettable when they attack you. After a while you can target them and attack them. When they die, they are visible.
Probably some bug tied to [Tunnel](https://www.wowhead.com/spell=84863/tunnel) ability.

**Comment by UltraNix** [comment]
Fixed.
