### ISSUE TITLE
[Hunter] Pet away and unusable

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1259]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i just fly away, with my pet on the ground.
my pet gone away after some time.

once i needed it again, i could call it, but it did not appear.
its gone forever, my lovely pet..

now, 30 minutes later, i could call it again (i die in the meanwhile).
Looks like the pets are bugged, until u die.

**How to reproduce:**
fly away with pet
pet bugged
die to recover from bug

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
