### ISSUE TITLE
[Dungeon] Stonecore boss Slabhide

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1260]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the boss fly in the air during fight
he just stand there, in the air. he have no flying animation

**How to reproduce:**

fight against the boss
**How it should work:**

**Database links:**
he just stand in the air, like on the ground
![image](https://user-images.githubusercontent.com/120294125/207722656-e135883f-adff-4260-8d5a-d7ad13950dd1.png)

**Comment by Afgann** [comment]
fixed
