### ISSUE TITLE
[Hunter] Feign Death

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1261]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the ability resets aggro but let the charakter stand up asap after hitting the button.
this happens while in combat only.
if u hit the ability without combat, that dont happen.

that bug dont let u reset during fight

**How to reproduce:**
hit the ability in combat

**How it should work:**
the charakter should be on the ground, until u standup (move) by yourself

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
