### ISSUE TITLE
[Dungeon][Boss] Stonecore - Ozruk

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1265]
Stonecore [Ozruk] Scripting errors HC

SylahUmehara
OP
 — Today at 2:03 PM
Heroic difficulty doesn't do Rupture.
Shatter only does 120k Damage not the intended 200k. Paralyze does not do the 50k damage when it expires naturally

**Comment by Afgann** [comment]
fixed
