### ISSUE TITLE
[Hunter][Item][Spell] Camouflage & Cataclysmic Gladiator's Badge of Conquest

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1273]
hunter spell [camouflage]

Jimmy17
OP
 — Today at 7:18 AM
When i use  [Cataclysmic Gladiator's Badge of Conquest] while in camouflage , my camouflage break.

i should be able to use  [Cataclysmic Gladiator's Badge of Conquest] without breaking my camouflage.

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
Correction in notes -  This should be ALL ON USE TRINKETS.  not just badges of conquest.

On Use trinkets will break camouflage.  Should behave as fixed above

**Comment by UltraNixx** [comment]
The bug has been already fixed. No need for opening this.
