### ISSUE TITLE
[Paladin][Talent] Pursuit of Justice

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1274]
[Pursuit of Justice] ret paladin talent

Jimmy17
OP
 — Today at 7:13 AM
[Pursuit of Justice] , is giving holy power even if the immobilize CC effect didn't happen , for example if mage nova a ret when he has freedom up. or if mage deep freeze into bubble. it will still give him the holy power which is wrong.
Also when an enemy ret use Holy wrath i will gain holy power which is also incorrect , cz Holy wrath only stuns undead  / demon. so there is no reason i should get holy power

**Comment by Afgann** [comment]
fixed
