### ISSUE TITLE
[Priest][Talent] Vampiric Embrace

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1275]
Vampiric Embrace (Shadow Priest)

Chris99
OP
 — Today at 5:45 AM
Vampiric Embrace is not healing at all, not the priest itself nor any party members) 6% of any single target dmg should heal the priest and 3% all groupmembers.

**Comment by UltraNix** [comment]
Mind Blast:
![obraz_2022-12-15_101423493](https://user-images.githubusercontent.com/80540499/207819882-8c5e85e2-d374-4120-bf16-cfae6d86f6ea.png)

Mind Spike:
![obraz_2022-12-15_101445248](https://user-images.githubusercontent.com/80540499/207819958-5d0fdb44-cd08-4c93-a096-e0fb09b8a363.png)

Mind Flay:
![obraz_2022-12-15_101512180](https://user-images.githubusercontent.com/80540499/207820065-88316864-d8cc-4d41-be85-ffb62ebbaa90.png)

Everything works okay.
