### ISSUE TITLE
[Quest] One With the Ground

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1277]
One With the Ground (Deepholm)

Arckangel3
OP
 — Today at 12:10 AM
When you take the ritual from the NPC he sends you on a path in the ground. You are still targetable by monsters and the path goes right under a monster. The monster hits you and knocks you out of the ritual.

**Comment by UltraNix** [comment]
Fixed.

**Comment by tarkfang** [comment]
It still needs to fix the movement speed while underground, it goes as 100% but it should be more like 400-500% as it was in retail.
