### ISSUE TITLE
Northern Stranglethorn Levelling Report (Alliance)

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1278]
1: [Population Con-Troll](https://cata-twinhead.twinstar.cz/?quest=26751)
- This Quest is available right from the 1st time you enter the Camp. It should be available only after you finish [A Nose for This Sort of Things](https://cata-twinhead.twinstar.cz/?quest=26746).

2: [Kurzen Supplies](https://www.wowhead.com/object=264/kurzen-supplies) can be looted for [Venom Fern Extract](https://www.wowhead.com/item=2634/venom-fern-extract). [Wowpedia](https://wowpedia.fandom.com/wiki/Venom_Fern_Extract) says the Fern was removed by patch 4.0.3a, so the container should either be empty or not lootable at all.

3: [Crystal Spine Basilisk](https://cata-twinhead.twinstar.cz/?npc=689) circa at 60.7/17.3 is under texture. I also seen some other basilisk nearby fly a bit through the air.

4: At Kurzen Compound, the mobs in the house at 56.5/20.3 can aggro, attack and walk through the walls of the house.

5: This old post: https://github.com/gamefreedomgit/Maelstrom/issues/145
https://www.youtube.com/watch?v=C-qv335PmxI 59:42 onwards (although looks like fan server)
I remember it from the short time spent on Apollo II too
The issues is not fixed, only that one quest that was listed in the OP. Quests needing same fixing:
- [Tiger Stalking](https://www.wowhead.com/quest=186/tiger-stalking); receive missing, hand in missing
- [Tiger Prowess](https://www.wowhead.com/quest=187/tiger-prowess); receive missing; hand in is good
- [Tiger Mastery](https://www.wowhead.com/quest=188/tiger-mastery); all good

- [Panther Hunting](https://www.wowhead.com/quest=190/panther-hunting); hand in missing
- [Panther Stalking](https://www.wowhead.com/quest=191/panther-stalking); receive missing, hand in good
- [Panther Prowess](https://www.wowhead.com/quest=192/panther-prowess); receive missing, hand in good
- [Panther Mastery](https://www.wowhead.com/quest=193/panther-mastery); all good

- [Raptor Hunting](https://www.wowhead.com/quest=194/raptor-hunting); hand in missing
- [Raptor Stalking](https://www.wowhead.com/quest=195/raptor-stalking); receive missing, hand in is good
- [Raptor Prowess](https://www.wowhead.com/quest=196/raptor-prowess); receive missing, hand in good
- [Raptor Mastery](https://www.wowhead.com/quest=197/raptor-mastery); all good

6: [Favored Skull](https://www.wowhead.com/quest=26745/favored-skull)
At the moment you can pick this quest up right after you finish [I Think She's Hungry](https://www.wowhead.com/quest=26739/i-think-shes-hungry)
You should recieve this quest only while doing [Deep Roots](https://www.wowhead.com/quest=26744/deep-roots#comments) and only in Bal'lal Ruins.
This results in that you can skip Deep Roots completely atm.

7: [Tsul'kalu](https://cata-twinhead.twinstar.cz/?npc=51661), [Pogeyan](https://cata-twinhead.twinstar.cz/?npc=51663) and [Mahamba](https://cata-twinhead.twinstar.cz/?npc=51662) rare mobs have no loot.

8: Rare mob [Gluggl](https://cata-twinhead.twinstar.cz/?npc=14487) is spawned twice, one of them dropped 3 green items at once.

9: [Green Hills of Stranglethorn - Page 25](https://www.wowhead.com/item=2749/green-hills-of-stranglethorn-page-25) dropped for my from one murloc near Gluggl. [Wowpedia](https://wowpedia.fandom.com/wiki/Green_Hills_of_Stranglethorn_-_Page_25) lists it as removed with patch 4.0.3a.

10: [Bloodlord Mandokir](https://www.wowhead.com/quest=26748/bloodlord-mandokir)
- After completing the quest the [Lashtail Hatchling](https://www.wowhead.com/npc=42736/lashtail-hatchling) is still following me until logout or .tele out of Stranglethorn. Based on the quest, it should disappear right after completing the quest in case you have it summoned.
- [Osborn Obnoticus](https://www.wowhead.com/npc=43884/osborn-obnoticus) should act scared and say: "Do something." which I haven't noticed happening.

11: [Nighttime in the Jungle](https://www.wowhead.com/quest=26780/nighttime-in-the-jungle)
https://www.youtube.com/watch?v=m5ogyIhnI54 Timestamp 1:10
[The braziers](https://www.wowhead.com/object=204247/zulmamwe-brazier) do not disappear after you extinguish them. Instead they stay and after a few seconds you can click the same brazier for another extinguish count.

12: [Crewman Crosswire](https://www.wowhead.com/npc=24929/crewman-crosswire), [Navigator Sparksizzle](https://www.wowhead.com/npc=24927/navigator-sparksizzle) and [Crewman Gazzlegear](https://www.wowhead.com/npc=24930/crewman-gazzlegear) in Northern Stranglethorn are spawned twice in NorthernStranglethorn and they stay standing in the air when the zeppelin leaves.
As to if there is 3rd, correctly working spawn of these guys I cannot say since I am not horde and thus couldn't take a look into the zeppelin.

13. [Priestess Thaalia](https://www.wowhead.com/npc=44017/priestess-thaalia) is missing text for [Mind Control](https://www.wowhead.com/quest=26774/mind-control) completion.
TIMESTAMP 2:13 https://www.youtube.com/watch?v=0tTfC7LiXDk

14: [Be Raptor](https://www.wowhead.com/quest=26775/be-raptor)
This quest is not scripted at all, auto-complete on taking it.

**Comment by UltraNix** [comment]
Fixed.
