### ISSUE TITLE
Gargoyles in Death's Breach

### ISSUE THREAD

**Issue by renton7eureka7** [gamefreedomgit/Maelstrom#1282]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The two gargoyles in DK starting zone, Death's Breach, doesn't appear to take you back up to Acherus. Doesn't appear with relogg.

**How to reproduce:**

**How it should work:**
The two gargoyles should exist.

**Database links:**

**Comment by UltraNix** [comment]
@renton7eureka7 What gargoyles?

**Comment by UltraNix** [comment]
Fixed.
