### ISSUE TITLE
Faulty Mining Deposit Spawns

### ISSUE THREAD

**Issue by WarlordXecc** [gamefreedomgit/Maelstrom#1286]
Outside BRD there are a bunch of faulty Mithril Deposits.
There is 8x Mithril Deposits outside BRD. But only two are in a mineable location. 1 is inside the BRD Portal and the other 5 are bugged inside terrain and can't be taken.
I don't think these should exist.

https://cdn.discordapp.com/attachments/1053065941061206166/1053076065309958144/2022-12-15_22-52-31.mp4

**Comment by UltraNix** [comment]
Fixed.
