### ISSUE TITLE
[World Boss] Julak Doom - not implemented [Zone Twilight Highland]

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Worldboss is not implemented yet.
Never seen since ptr start, every other worldboss is just there.

**How to reproduce:**

**How it should work:**
the boss should path through twilight highlands 

**Database links:**
https://www.wowhead.com/de/npc=50089/julak-doom

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
Fixed.
