### ISSUE TITLE
[NPC] [Pathing] Blazewing Rare Spawn Mount Hyal

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1288]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Npc dont move around
Its just sitting there on the mountain.
![image](https://user-images.githubusercontent.com/120294125/208091045-143d48f2-ce78-4391-841a-e6bbba3ca1b2.png)

**How to reproduce:**

**How it should work:**
The NPC need to path around the area / the way
https://www.youtube.com/watch?v=zz9Bi_qmqV0
**Database links:**

https://www.wowhead.com/de/npc=50057/flammenschwinge

**Comment by UltraNix** [comment]
Fixed.
