### ISSUE TITLE
[World Boss] [NPC] [Pathing] Garr - Mount Hyal

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1289]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Garr just sit there, dont move around.

![image](https://user-images.githubusercontent.com/120294125/208091602-670f6f5d-0a3f-40c3-80fc-f1ddac1abfdb.png)

**How to reproduce:**

**How it should work:**
he should path around the edge where he sit now.
https://www.youtube.com/watch?v=J6LubsmMlR0
https://www.youtube.com/watch?v=-aXQn7JKLnA
**Database links:**

**Comment by UltraNix** [comment]
Fixed.
