### ISSUE TITLE
[World Boss] [NPC] [Damage] Garr - Mount Hyal

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1290]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The boss just overkill you with the first spell:
![image](https://user-images.githubusercontent.com/120294125/208092649-4b856f1e-4665-4a47-b538-bab95482a3c0.png)

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/de/spell=93508/massiver-ausbruch
see the details of his spell on wowhead
pls check the spell damage scaling?
**Database links:**

**Comment by Afgann** [comment]
Damage seems to be correct.
sources:
https://www.wowhead.com/npc=50056/garr#comments:id=1360870
https://cata-twinhead.twinstar.cz/?spell=93508
