### ISSUE TITLE
[Quest] High Priestess Jeklik quest chain - Missing Comm

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1292]
Timestamp 3:14 at https://www.youtube.com/watch?v=cE8hbHWkU-g&t=17s
After handing in [High Priestess Jeklik](https://www.wowhead.com/quest=26812/high-priestess-jeklik) via comm, you should be offered the next quest, [Plunging Into Zul'Gurub](https://www.wowhead.com/quest=26813/plunging-into-zulgurub), also via comm. When you use the portal, which is not usable without the quest, you complete the quest and you should hand it via comm again, which is also not the case on the server atm. After that, you should get quest [High Priest Venoxis](https://www.wowhead.com/quest=26814/high-priest-venoxis), again via comm.

Here is also a video of the fights: https://www.youtube.com/watch?v=Z5snxP4qs7Q
Can't find Alli version but I suppose the baloon in that case takes you to the Alli camp instead of Horde camp :).

**Comment by Greywolf59** [comment]
Update: After logging out and logging in due to the update on PTR right now, the hand in of [Plunging Into Zul'Gurub](https://www.wowhead.com/quest=26813/plunging-into-zulgurub) was available via comm, same as taking [High Priest Venoxis](https://www.wowhead.com/quest=26814/high-priest-venoxis) quest.

**Comment by UltraNix** [comment]
Fixed.
