### ISSUE TITLE
[NPC] Garley Lightrider - hostile and aggresive against Alliance

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1293]
[Garley Lightrider](https://www.wowhead.com/npc=43849/garley-lightrider) just stomped me in the ground when I entered the room she was in. I haven't attacked here before or anything. I highly doubt it should be so.
Patch 4.1.0 comment on her Wowhead page says "Checked today (4.2) She is no longer attack-able by Alliance."

**Comment by UltraNix** [comment]
Fixed.
