### ISSUE TITLE
[NPC] Bloodsail Sea Dog - need more spawns on the beach

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1294]
[Bloodsail Sea Dog](https://www.wowhead.com/npc=1565/bloodsail-sea-dog) have a bit more spawns on the beach. There are some on the isles near the beach but of what I seen from the videos, there should be 8 or 9 of them on the beach itself. At the moment there is only 5 of them there. They are needed for [Details of the Attack](https://www.wowhead.com/quest=26612/details-of-the-attack). I will try to find the video again cause I lost it meanwhile, if I remember to.

**Comment by UltraNix** [comment]
Fixed.
