### ISSUE TITLE
[Minor] [NPC] Attack on Booty Bay

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1295]
There is a few small issues with this event. I have noticed mainly four.

1. [Brashtide Crewman](https://www.wowhead.com/npc=43717/brashtide-crewman). When they harbor in and go attack [Seahorn](https://www.wowhead.com/npc=2487/fleet-master-seahorn), they keep flaoting in the air on parachutes and not attacking, stacking themselves in front of Seahorn.
Video: https://files.fm/u/pfg7x9dtn

2: On the video above you can also notice there is a lot of boats coming in, some of them partly stacked on one another. Also the Brashtide Crewman spawn at Seahorn seems like a small army. I am pretty sure there should be less boats (and less NPCs spawning as a result too).

3: Most of the [Bloodsail Corsairs](https://www.wowhead.com/npc=43726/bloodsail-corsair) keep falling down through texture to the lowest deck or to the sea upon being attacked.

4: Same goes for [Fleet Master Firallon](https://www.wowhead.com/npc=2546/fleet-master-firallon). He ends up in the water when you attack him.

**Comment by UltraNix** [comment]
Fixed.
