### ISSUE TITLE
[NPC] Cant open Vendor Menu

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1296]
**Description:**
Atleast in the Azuremyst Isle and Bloodmist Isle i cant open the Vendor Menu of some Vendors. For Example https://wotlk-twinhead.twinstar.cz/?npc=21145. After clicking [this](https://i.imgur.com/jEWCOtU.png), the menu closes and i cant sell/buy items.

**How to reproduce:**
Talk to some vendors in those areas.

**Comment by shinzo69** [comment]
Here another NPC:
https://www.wowhead.com/npc=17421/clopper-wizbang
https://i.imgur.com/ORKoMEE.png

**Comment by Afgann** [comment]
fixed
