### ISSUE TITLE
[Minor] Ironforge Minor Bugs

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1297]
1: [Chicken Clucking for a Mint](https://www.wowhead.com/quest=8353/chicken-clucking-for-a-mint) is available at the moment.
- [Inkeeper Firebrew](https://www.wowhead.com/quest=8353/chicken-clucking-for-a-mint) should offer this quest only during Hallow's End and only if the player is on the quest [Hallow's End Treats for Jesper](https://cata-twinhead.twinstar.cz/?quest=8311)

2: [Sack of Oatmeal](https://www.wowhead.com/object=208870/sack-of-oatmeal) is looatable, although empty, at all times
- It should be lootable only when the player is on the quest [Keepin' the Haggis Flowin'](https://www.wowhead.com/quest=29353/keepin-the-haggis-flowin).

3: [Brew Vendor](https://cata-twinhead.twinstar.cz/?npc=27820) should sell you the special drinks (like currently [Lord of Frost's Private Label](https://cata-twinhead.twinstar.cz/?item=37909) ) only if you have completed the Brewfest quest [Brew of the Month Club](https://www.wowhead.com/quest=12420/brew-of-the-month-club). Otherwise the NPC should inform you that the services provided are only for the members of the Club. Currenctly you don't need to be a member to buy the special drinks.

4: Greatfather Winter is Here!
This quest has two versions:
Not taken in Ironforge = https://cata-twinhead.twinstar.cz/?quest=7023
Taken in Ironforge = https://cata-twinhead.twinstar.cz/?quest=7022
If you take one of the quests, you should not be able to take the other. If you compelte one of the quests, you should not be able to take the other. At least that is common beahviour of such quest. If nothing else it is really strange to hand in the quest from Stormwind and immediately be able to take the same one in Ironforge.
Currently if you finish one of them, you can take the other afterwards.

5. Braziers in Old Ironforge
When you hover your mouse over the braziers in Old Ironforge the tooltip says "Doodad_DwarvenBrazierXYZ (xyz = number). I have no idea what is their proper name that players should see but it is definitely not this.

6: [Advisor Belgrum](https://www.wowhead.com/npc=2918/advisor-belgrum)
[Wowpedia](https://wowpedia.fandom.com/wiki/Advisor_Belgrum) states:
- Time to time he should say: "This was my fault, my lord. I should've done more research on those tablets...". He doesn't.
- When talked to, he says "Greetings, [PName]. He should say: "King Magni's fate is my responsibility and my shame. I should've counseled patience instead of encouraging him! His rush to complete the ritual without understanding it cost him his life and availed us nothing."

7: [Alexander Calder](https://www.wowhead.com/npc=5173/alexander-calder) is neutral and attackable by Alliance.

8: [Squrky](https://www.wowhead.com/npc=53544/squrky)
- This guy is, most likely wrongly, named Squirky on ptr.
- He is neutral and attackable, he should be friendly to both factions.

**Comment by UltraNix** [comment]
Fixed.
