### ISSUE TITLE
[NPC] Rares dont use mana?

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1300]
**Description:**
Not 100% sure if this is a bug, but all rare mobs dont loose mana when casting spells.
Vid: https://streamable.com/pjw9m3

**How to reproduce:**
Attack any rare mob, for example some of those:
https://wowrarespawns.blogspot.com/2012/06/ashenvale-rare-spawns.html
https://wowrarespawns.blogspot.com/2013/08/northern-stranglethorn-rare-spawns.html

**How it should work:**
I think rares should loose mana when casting? Couldnt find any video evidence from retail.

**Comment by Afgann** [comment]
I've checked some rares, and spells that they cast don't have any mana costs, seems to be the same in the video (https://www.youtube.com/watch?v=omlUF2NfpKI).
