### ISSUE TITLE
[Character/Chat] Cant link all Items

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1301]
**Description:**
Im not able to link Back, Wrist, Finger. (maybe even more? dont have all item slots filled to check it out)
Vid: https://streamable.com/vyp2rx **(care music)**

**How to reproduce:**
Try to link Items you are wearing.

**How it should work:**
Items should be link-able in the chat

**Comment by UltraNix** [comment]
Soon should be fixed.

**Comment by UltraNix** [comment]
Fixed.
