### ISSUE TITLE
[Talent] [Shaman] Fulmination

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1302]
**Description:**
The Talent [Fulmination](http://cata.cavernoftime.com/spell=88766) shows a [visual proc](https://i.imgur.com/bR0Notl.png) even tho i dont have it talented. 
The Proc starts showing at 9 Stacks of [Lightning Shield](http://cata.cavernoftime.com/spell=8788). Im level 32 (cant even have that talent skilled yet).

**How to reproduce:**
Get some Stacks of Lightning Shield. 
Requires Pre-Talent [Rolling Thunder](http://cata.cavernoftime.com/spell=88765) (to get more than 3 Stacks)

**How it should work:**
Talent should only work if its skilled.

**Comment by Afgann** [comment]
fixed
