### ISSUE TITLE
[Rare Mob] Pogeyan hits too hard

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1303]
**Description:**
The Rare Mob [Pogeyan](https://www.wowhead.com/de/npc=51663/pogeyan) hits for ~350-450 each attack. 
Normally it should be something around 50?

**How to reproduce:**
Attack [Pogeyan](https://www.wowhead.com/de/npc=51663/pogeyan) in Stranglethorn Valley.

**How it should work:**
Mob should hit for less.

**Database links:**
Retail Video: https://www.youtube.com/watch?v=W_J0IJULeMg
My POV: https://streamable.com/thi73g

**Comment by Afgann** [comment]
fixed
