### ISSUE TITLE
[NPC] Twilight Keeper Havunth is not patrolling

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1304]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Keeper Havunth is stationary on the map where the quest tracker says he is.

**How to reproduce:**
Just go see him

**How it should work:**
He should be walking circles counter-clockwise around Twilight Base Camp 

**Database links:**
npc=11804/twilight-keeper-havunth

**Comment by UltraNix** [comment]
Fixed.
