### ISSUE TITLE
[Raid] Ahn'Qiraj - Gate to C'thun doesn't open after defeating Twin Emperors

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1306]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After killing Vek'lor and Vek'nilash, the gate doesn't open, so you can't advance

**How to reproduce:**
kill twin emps and try to go to C'thun

**How it should work:**
Gate is closed until killing them

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
