### ISSUE TITLE
frostmage Orb bugged

### ISSUE THREAD

**Issue by Damon156** [gamefreedomgit/Maelstrom#1307]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi frostfire orb disappaer and do nothing.

**How to reproduce:**
Just use orb

**How it should work:**
Attack and Not Stuck at one Place 

**Database links:**

**Comment by UltraNix** [comment]
@Damon156 Just tested and works okay. Please, give us more info or record a video.

**Comment by UltraNix** [comment]
No info - closing.
