### ISSUE TITLE
[Quest] The Endless Flow - ID: 27161

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1309]
**Description:**
Progress towards "Stickbone Berserker slain 0/5" doesn't count. Neither with the [Quest Item](https://www.wowhead.com/item=60849/langs-hand-grenades) or by just killing them.

**How to reproduce:**
Kill them normally or try it out with the Item.

**How it should work:**
Progress should count for completion of the quest.
https://www.youtube.com/watch?v=7TDUROn43t0

**Database links:**
Quest: https://www.wowhead.com/quest=27161/the-endless-flow
Quest Item: https://www.wowhead.com/item=60849/langs-hand-grenades
NPC to kill: https://www.wowhead.com/npc=44329/stickbone-berserker

**Comment by shinzo69** [comment]
.quest complete 27161 also doesn't work.
It shows "Quest Objective complete" but its not. I cant do the follow up quests in Western Plaguelands.

**Comment by shinzo69** [comment]
maybe a false issue since i was in a raid group.
can someone test it?

**Comment by UltraNix** [comment]
Works okay.
