### ISSUE TITLE
[NPC] Andorhal Defender + Flightmaster

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1311]
**Description:**
The [NPC's](https://www.wowhead.com/npc=44448/andorhal-defender) in and around the Town of Andorhal dont help in any activity. They just stand around or some do patrol but they dont attack nearby mobs or help when you are in combat.

Flightmaster [Ginny Goodwin](https://www.wowhead.com/npc=46006/ginny-goodwin) is stuck in an attack animation + completely [out of position](https://i.imgur.com/oBD3Azl.jpeg).

**How to reproduce:**
Walk around in Andorhal and look at those friendly NPCs.

**How it should work:**
[Andorhal Defender](https://www.wowhead.com/npc=44448/andorhal-defender) should attack nearby mobs and help.
Flightmaster [Ginny Goodwin](https://www.wowhead.com/npc=46006/ginny-goodwin) should be at her Flightmaster Camp (not mapped there?)

**Database links:**
NPC: https://www.wowhead.com/npc=44448/andorhal-defender
Flightmaster: https://www.wowhead.com/npc=46006/ginny-goodwin

**Comment by UltraNix** [comment]
Fixed.
