### ISSUE TITLE
[Quest] Scholomancer - ID: 27162

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1313]
**Description:**
NPC [Thassarian](https://cata-twinhead.twinstar.cz/?npc=44453) doesnt give the [Quest Scholomancer](https://cata-twinhead.twinstar.cz/?quest=27162) and therefore not all the follow ups.
Pre-Requirement is https://cata-twinhead.twinstar.cz/?quest=27160.

**How to reproduce:**
Complete this [Pre-Quest](https://cata-twinhead.twinstar.cz/?quest=27160) and then try to get the follow up Quests from Thassarian.

**How it should work:**
Thassarian should give follow up Quests.

**Database links:**
Pre-Quest: https://cata-twinhead.twinstar.cz/?quest=27160
Quest: https://cata-twinhead.twinstar.cz/?quest=27162
NPC: https://cata-twinhead.twinstar.cz/?npc=44453

**Comment by Afgann** [comment]
fixed
