### ISSUE TITLE
[NPC] [Minor] Rockjaw Goon missing /say

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1324]
Dun Morogh
[Rockjaw Goon](https://www.wowhead.com/npc=37073/rockjaw-goon) is missing say emotes ([wowpedia](https://wowpedia.fandom.com/wiki/Rockjaw_Goon))

Why you break our home?!
Trogg cave all gone! You pay for this!!
You break our cave, I break your skull!

**Comment by Afgann** [comment]
fixed
