### ISSUE TITLE
[NPC] [Minor] Hands Springsprocket's gossip

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1325]
[Hands Springsprocket](https://www.wowhead.com/npc=6782/hands-springsprocket)'s gossip currently states: "Need TXT YTDB"

Should be: How do you do, [class]? ([wowpedia](https://wowpedia.fandom.com/wiki/Hands_Springsprocket?so=search))

**Comment by Afgann** [comment]
fixed
