### ISSUE TITLE
[NPC] [Minor] Gorick Guzzledraught - speech

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1327]
When you find [Gorick Guzzledraught](https://www.wowhead.com/npc=33456/gorick-guzzledraught) (objective of a quest) [he says](https://wowpedia.fandom.com/wiki/Gorick_Guzzledraught): "Managed to find me, eh? No matter, you won't live to tell anyone of it!"
This speech has a typo in it and is missing spaces.

**Comment by Afgann** [comment]
fixed
