### ISSUE TITLE
[Quest] [Minor] Axis of Awful

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1328]
[Axis of Awful](https://www.wowhead.com/quest=26868/axis-of-awful)
Video: https://www.youtube.com/watch?v=GLXH-cGXl_0
Timestamp: 1:28 and 1:51

The event played after throwing [Potent Murloc Pheromones](https://www.wowhead.com/item=60503/potent-murloc-pheromones) on [Mosshide Representative](https://www.wowhead.com/npc=44262/mosshide-representative) is not played out properly. All says, emotes and yells are okay but:
1: The three additional [Bluegill Representatives](https://www.wowhead.com/npc=44263/bluegill-representative) won't spawn.
2: [Tunnel Rat Lackey](https://www.wowhead.com/npc=44264/tunnel-rat-lackey) won't run away.
3: Bluegills won't actually attack and kill the Mosshide Representative.

**Comment by UltraNix** [comment]
Fixed.
