### ISSUE TITLE
[NPC] Kurtok the Slayer missing Quotes

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1329]
0 out of 5 no Quotes
Suggestion:
Kurtok the Slayer says: Alliance weakling, your lands will burn!
Kurtok the Slayer says: The Blackrock Clan will end you…

Link: https://www.wowhead.com/npc=42938/kurtok-the-slayer

**Comment by Afgann** [comment]
fixed
