### ISSUE TITLE
[NPC] Stormwind Royal Guard in Northsire Alley patrol

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1330]
Weird patrol path
Random stops

Suggestion: 
Investigate the random stops
They should patrol in the center of the road
![Stormwind Royal Guard wierd patrol](https://user-images.githubusercontent.com/120984471/208439047-f2082260-4fec-457e-ab40-c5fafaa3c5b7.jpg)

**Comment by UltraNix** [comment]
I haven't noticied such problems.
