### ISSUE TITLE
[NPC] Stormwind Royal Guard in Goldshire patrol

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1331]
Same as in Northsire Alley

Floating Guards 
Not correct patrol path
![WoWScrnShot_121922_144419](https://user-images.githubusercontent.com/120984471/208439723-c27318b2-c044-4449-a264-79b84b662a32.jpg)
![WoWScrnShot_121922_144352](https://user-images.githubusercontent.com/120984471/208439758-d498e0cb-1da0-4543-aa56-ab1d0b4c70f8.jpg)

**Comment by UltraNix** [comment]
I haven't noticed such problems.
