### ISSUE TITLE
[NPC] [Minor] Optimo - HP reset, not fighting

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1332]
If you attack [Optimo](https://www.wowhead.com/npc=45399/optimo) when he stnds at the end of the cave (probably his spawn point) he does not fight back, keeps you in combat and resets HP to full after every other attack. The issue persist when he starts walking around, unless you alt+F4, relog and atack him later on. As a higher level I have managed to kill him during his way around the cave but for appropriate level it would be impossible.

**Comment by UltraNix** [comment]
Works okay.
