### ISSUE TITLE
[Quest] [NPC] [Minor] The Winds of Loch Modan - Skystrider speed

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1333]
[The Winds of Loch Modan](https://www.wowhead.com/quest=27116/the-winds-of-loch-modan)
Video: https://www.youtube.com/watch?v=NKSLjtrwSRk
1: [Skystrider](https://www.wowhead.com/npc=44572/skystrider) slows down when he gets past the broken dam and keeps flying slow (-10 to 5% movement speed) for the rest of the way.
2: The player sits on the Skystrider alone, he should be seated behind the quest giver [Ando Blastenheimer](https://www.wowhead.com/npc=44870/ando-blastenheimer). (not sure if it is right ID, havent found any other though)

**Comment by UltraNix** [comment]
Fixed.
