### ISSUE TITLE
[Spell] Earthquake

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1334]
**Description:**
Spell Earthquake gets [automaticly learned](https://i.imgur.com/HZkGVON.png) at Level 50.
It should be the [End Talent](https://i.imgur.com/vIQIKze.png) in the Elemental Talent Tree.

**How to reproduce:**
Reach Level 50 and look in the Chat.
I cant find it in the Spellbook but i can cast it via /cast Earthquake or with a macro.

**How it should work:**
Spell should be learned upon talenting and not automaticly at Level 50.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=77478 I think its this one?

**Comment by Afgann** [comment]
fixed
