### ISSUE TITLE
[PET] Hearthstone bug

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1335]
When Hearthstoning ,the pet is following me but not teleporting. Causing me to combat and aggro the mobs
![Hearthstone pet bug (1)](https://user-images.githubusercontent.com/120984471/208504647-29acd630-574b-4ad8-8181-3ebeeb633c76.jpg)
![Hearthstone pet bug (2)](https://user-images.githubusercontent.com/120984471/208504665-3d5e473b-0e06-438a-84f7-c38cc3818633.jpg)

**Comment by UltraNix** [comment]
Already fixed.
