### ISSUE TITLE
[NPC] Innkeeper Farley missing Quote

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1336]
No Quotes when entering the Inn
Suggestion:
Innkeeper Farley says: So much to do, so much to do! Where does the time go?
Innkeeper Farley says: Welcome to the Lion's Pride Inn. Make yourself at home!

See the link:
https://www.wowhead.com/npc=295/innkeeper-farley

**Comment by Afgann** [comment]
fixed
