### ISSUE TITLE
[MOB] Riverpaw Outrunner combat range

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1337]
The mob can reach me when I cast the ranged spell. Around 35yd is his range
Suggestion:
Investigate the mob range but I share the image
![Riverpawn outrunner range bug (2)](https://user-images.githubusercontent.com/120984471/208505031-b7300818-30ab-4cc7-bd92-855067887bfc.jpg)

**Comment by UltraNix** [comment]
I don't see your level, but at 10 lvl char it's ~12y. Looks okay.
