### ISSUE TITLE
Heart of the Unliving interaction with Holy Nova

### ISSUE THREAD

**Issue by Rememorize** [gamefreedomgit/Maelstrom#1338]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Priest spell Holy Nova doesn't proc the trinket Heart of the Unliving (normal or heroic versions).

**How to reproduce:**
Equip Heart of the Unliving and cast Holy Nova.

**How it should work:**
It should proc the stacking Spirit buff. To see it work as intended, cast Holy Nova with Darkmoon Card: Tsunami equipped.

**Database links:**

**Comment by Afgann** [comment]
https://www.wowhead.com/item=77199/heart-of-unliving?bonus=9057#comments:id=1592050
