### ISSUE TITLE
[MOB] Rogue Wizard lack of Quotes

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1339]
Rogue Wizard has Quote but Wiki says it has 4 of them. Not a major issue!

See the link:
https://www.wowhead.com/npc=474/rogue-wizard
![Rogue wizard lack of quotes](https://user-images.githubusercontent.com/120984471/208509055-c8f5f759-e640-4378-94b2-29196fe42db1.png)

**Comment by Afgann** [comment]
fixed
