### ISSUE TITLE
[Passive Spell] Armor Skills

### ISSUE THREAD

**Issue by shinzo69** [gamefreedomgit/Maelstrom#1340]
**Description:**
Can't wear Mail Items when boosting a Shaman to level 85 (i talked to Sally Whitemane "Teach Me - Armor Spec!")
https://i.imgur.com/t6oQs96.jpeg

**How to reproduce:**
Boost a Shaman to 85, talk to Sally, try to wear Mail Items.

**Comment by UltraNix** [comment]
Fixed.
