### ISSUE TITLE
Quest "An Ancient Reborn" bugged

### ISSUE THREAD

**Issue by BishopHimself** [gamefreedomgit/Maelstrom#1341]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/quest=25807/an-ancient-reborn
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?quest=25807
![wow quest bug](https://user-images.githubusercontent.com/121093926/208638390-20c6dc90-c9a5-4738-911d-1d18e36b079f.png)

**Description:**
Quest named #1199 is bugged. When you use the quest item called "Herald's Incense" in front of Aviana's egg, nothing happens except for egg disappearing. The npc Aviana doesnt spawn in and you can not talk to her in order to turn the quest in and continue the chain.

**How to reproduce:**
Take quest #1199 from the npc Choluna, located in Shrine of Aviana, Hyjal. Then use the quest item on an egg in room just above. 

**How it should work:**
The npc Aviana should spawn from the egg and you turn the quest in.

**Database links:**
https://www.wowhead.com/quest=25807/an-ancient-reborn

**Comment by UltraNix** [comment]
Already fixed.
