### ISSUE TITLE
[PTR][Dungeon] The vortex pinnacle 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1342]
**Description:** this instance can be found in Uldum there are some bugs here which is listed below

**How to reproduce:**
lurking tempest feign death has issues, it should keep doing it not just once
![image](https://user-images.githubusercontent.com/36106057/208729918-f7cb9917-8ee6-42e6-8da6-84148a9aa899.png)
altairus upwind downwind are pretty much active whole dungeon that should not happen
young storm dragon got movement issues it just flys off and its hard to hit him specially if you are melee
howling gale dont work orbs are not working properly sometimes after you hit them they work but not constantly it requires improvements.
![image](https://user-images.githubusercontent.com/36106057/208730684-9d025b8b-da82-4521-bc68-a5c82347c01d.png)

altairus debuff should disappear after killing it and he is not scripted at all its impossible to kill it

split streams are not scripted properly don't move you through the air properly and sometimes cause you to die specially second time that you use it

grounding field invis mob hitting me also not scripted properly they should have a electric links around the area
![image](https://user-images.githubusercontent.com/36106057/208731016-5c900a11-5669-4524-b6a9-bc0b60b0963b.png)
correct behavior 
![image](https://user-images.githubusercontent.com/36106057/208731225-45209ff5-c48b-40ef-a7d1-a8139217624c.png)

skyfall stars are not scripted properly and ground glowing light also following the player and hitting him

asaad is not scripted properly lightnings don't have correct movements also boss doesnt have correct animations and such

**Comment by Afgann** [comment]
fixed
