### ISSUE TITLE
[Minor] Westfall's minor issues 

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1344]
It is easier to share the document via drive.

https://docs.google.com/document/d/1pn-H__1XPmT9XgcJ7TBfp3T4egIDLm9mqgKt6aEouvs/edit?usp=sharing

I hope it won't be a problem, if yes then I can write one by one the issues here.

**Comment by UltraNix** [comment]
Fixed.
