### ISSUE TITLE
[Scripting error] Lost City of the Tol'Vir NPC "Neferset Torturer" cooldown on abilites incorrect.

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1345]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Torturer is seen to spam its Serum of Torment and branded Tongue with no cooldown.  This results in a CC that cannot be escaped from. 

**How to reproduce:**
Pulling the mob triggers this

**How it should work:**
The mob in question should only use its fear ability twice on a 20-30 second cooldown depending on difficulty.  These tests were done on normal mode 

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=44977 
https://cata-twinhead.twinstar.cz/?npc=44977#abilities

**Comment by WhitemaneSylah** [comment]
@MrTide

**Comment by MrTide** [comment]
Confirmed 
part of this report
https://github.com/gamefreedomgit/Maelstrom/issues/1346

**Comment by Afgann** [comment]
fixed
