### ISSUE TITLE
[PTR][Dungeon] Grim Batol issues list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1348]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Boss list
1) General Umbriss - Functioning

2) Forgemaster Throngus - Cave In's range is larger than 5 yards meaning players over 5 yards away still get the stacking debuff
Personal Phalanx does not reduce damage done by 99%, should only take 100% damage from flank and rear and 1% damage from front when shield is up.  Debuff is given but reduction to damage is not -  Sword Heroic Only ability "Burning Flames" is active on normal mode,  Mace untested - EDIT 27.12 - Throngus seems to be unable to switch through weapons normally,  Message on screen also doesn't up with what Throngus is doing.   

3) Drahga Shadowburner  -  Invoked Flaming spirit casts fixate but does nothing 
![image](https://user-images.githubusercontent.com/121137397/208791715-e2b93cce-17c8-421a-811d-62be5cdc4b9f.png)
Valiona spawns correctly at 30% but Drahga remains on the field and untargetable,  Dragha should be untargetable and should not attack when Valiona has joined the fight - EDIT 27.12 - Valiona RP scene triggers approx 20 seconds after valiona joins the fight.   Also to note Valiona does not move from the centre position.  Spell "Valiona's Flame" should function like Godfreys Pistol Barrage - where Valiona picks a direction and casts on it,  Instead She is following the main tank.  Main casted ability Burning Shadowbolt cannot be spell reflected yet is classed as a spell
4) Erudax - Works fine 

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=39625 - General Umbriss
https://cata-twinhead.twinstar.cz/?npc=40177 - Forgemaster Throngus
https://cata-twinhead.twinstar.cz/?npc=40319 - Dragha Shadowburner

**Comment by MrTide** [comment]
Confirmed the reports up there
requires attention

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
2/3 Dungeon's quest works ( Closing a Dark Chapter and Kill the Courier

Unable to complete the third one Soften them Up, that requires killing 30 Trogg Dwellers with Battered Red Drake , but for some reason, Trogg dwellers are not killable with Battered Red Drakes abillity ( They regenerate hp ) but even if more than one player hit them at once and kill them, it doesn't count for the quest


Trogg Dwellers on the room of Forgemaster Throngus should be moving to the door so players can pull them alone, they're stacked with another pack of adds actually and it will be hard to pull that actually.

Forgemaster Throngus: Disorienting Roar doesn't drop stacks on Healers on most healing abilities ( it should drop 1 stack for each ability you use / cast.

Drahga Shadowburner on the second phase with Valionna, Seeping Twilight stays less than 20s sometimes and Invoked Flame Spirit should be slowed by that zone.

Erudax, the Duke of Below Works perfectly.

**Comment by WhitemaneSylah** [comment]
moved to another report
