### ISSUE TITLE
[Quest][NPC] Good Help is Hard to Find - Defiant Troll

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1352]
Defiant Trolls are red for some reason currently: https://imgur.com/gxRN7gv

They shouldn't be red: https://imgur.com/x3XLRo3

**Comment by Loken-coolguy** [comment]
Also when you zap them, they currently yell. They should be doing their text dialogue in /say

**Comment by gaga-whitemane** [comment]
They should be red, at least on old models / client. 4.3.4. - Yell issue fixed.
![image](https://user-images.githubusercontent.com/4954400/209972140-a0979461-7e7a-4fb9-be62-e4796d1f1a5a.png)
