### ISSUE TITLE
[NPC][Pathing?] Forsaken Survivor (and others possibly)

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1356]
NPC ID - 36460

What is happening
-------------------------
NPC are supposed to be swimming in water on coastline of Allen farmstead, near Gilneas, When aggro, they run to the surface of water and stand there, and do not swim down to attack you but stay aggro and walk on water.

https://i.imgur.com/VX63GWT.png
https://i.imgur.com/Ai6c7AH.png

What should happen
-------------------------
They should swim properly and attack you underwater, and not run on water

**Comment by UltraNix** [comment]
Fixed.
