### ISSUE TITLE
[Quest][NPC] Rolling with my Homies - Missing Aura

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1360]
In the quest, Rolling with my Homies, Izzy should have a white light aura around them, like this: https://imgur.com/Duip2Rx

Currently, they have none: https://imgur.com/j8CdwCg

**Comment by Loken-coolguy** [comment]
Ace is also missing the same aura

**Comment by UltraNix** [comment]
Fixed.
