### ISSUE TITLE
[Quest] Exodus (another gate that takes long time to open)

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1361]
Quest ID - 24438

How it works
--------------------
After boarding stagecoach taxi, you are brought to another gate with a similar issue as my last ticket (it takes forever to open and you are sitting there infront of it for 2+ minutes. It eventually opens but it should not take this time.

How it works
--------------------
As stagecoach pulls up to the gate, it should open promptly, and complete the taxi ride.
https://i.imgur.com/1VNqGmq.png

**Comment by UltraNix** [comment]
Works okay.
