### ISSUE TITLE
[Quest][NPC][Animation] Rolling with my Homies - Izzy Animation

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1362]
When picking up Izzy for the quest Rolling with my Homies, Izzy should start an animation of her jumping into the car, like this: https://youtu.be/yz7vHxD_D_0?list=PLMUq0Stdh9Eb_TxHnv4Hmuc7GpAM37YAK&t=42 (timestamped for the direct moment she jumps in the car)

**Comment by Loken-coolguy** [comment]
Gobber is also missing this same animation

**Comment by UltraNix** [comment]
Fixed.
