### ISSUE TITLE
[Quest][NPC][Animation] Rolling with my Homies

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1364]
Once you have picked up all 3 NPCs for the quest Rolling with my Homies, they should randomly do an animation where they put their hands up in the air while driving: https://youtu.be/yz7vHxD_D_0?list=PLMUq0Stdh9Eb_TxHnv4Hmuc7GpAM37YAK&t=134

**Comment by UltraNix** [comment]
Fixed.
