### ISSUE TITLE
Black Lotus Issues

### ISSUE THREAD

**Issue by WarlordXecc** [gamefreedomgit/Maelstrom#1367]
Black Lotus both spawns way too often, and doesn't spawn in the correct zones.

According to wiki :

"Black Lotus can be found in Winterspring, Eastern Plaguelands, Burning Steppes, Silithus, and outside the instance portals in Dire Maul. It is rare in all of these places and never appears anywhere else."

"Each of the spawn zones has a small set of spawn points for Black Lotus. Only one Black Lotus will spawn at a time in the zone. Check sites which focus on gathering WoW data to see maps of the spawn locations. It is estimated that the respawn rate is 1 hour, possibly spawning on the hour."

Currently it only spawns inside Burning Steppes. And there is definitely not only 1x Spawn on a 1 Hour Respawn Timer.  I flew a lap around Burning Steppes and I found 7x Black Lotus currently up at the same time in Burning Steppes.

**Comment by UltraNix** [comment]
Fixed.
