### ISSUE TITLE
[NPC][Animation] Kezan Citizens - Kajaro Field

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1371]
At Kajaro Field, all of the NPCs are walking around randomly on the field. They should all be on the bleachers using a jumping animation (see this Youtube timestamp for reference: https://youtu.be/m8Z4x-_IiQs?list=PLMUq0Stdh9Eb_TxHnv4Hmuc7GpAM37YAK&t=114)

**Comment by UltraNix** [comment]
Fixed.
