### ISSUE TITLE
[Quest][NPC][Phasing] The Hunt for Sylvanas

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#1372]
Quest ID - 24902
NPC ID - 38507 (tobias minstmantle)

What is happening
-------------------
upon taking quest, Tobias Mistmantle is supposed to lead you outside, and Jump over the canal towards the gilnaes cathedral district while he leads you to search for sylvanas,  He get stuck before the jump and takes about 4 minutes of standing still and waiting to finally jump across the canal. After this happens, some phasing issue makes him disappear and there are no mobs or NPCs in the cathedral district when there should be.
https://i.imgur.com/tNnH2hh.png
https://i.imgur.com/PhfkEd1.png

There is much more to this quest but i cannot get past this part.

Whats supposed to happen
-------------------

(what quest is supposed to look like)
https://www.youtube.com/watch?v=b_M34sT5n8s

https://i.imgur.com/pJM7Yxs.png

**Comment by UltraNix** [comment]
Fixed.

**Comment by PPsunshine88** [comment]
I've got similar issue, im supposed to follow Tobias but I can't even find him. There are not mobs or NPC by the cathedral either. Can't move forward...
