### ISSUE TITLE
[PTR][Dungeon] End of Time

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1373]
**Description:** This dungeon can be found at cravens of time

**How to reproduce:** 

1. Image of Nozdormu lines overlap each other here they should happen one by one also correct ones are not playing.
 
2. on jaina fight packs of trash are not patrolling the area like this video (atleast most of them): https://youtu.be/bqBS_Dmuwok?t=580 , they just have a little movements at start then they stop moving.
 
3. echo of baine molten fists effects players only during the fight it should effect before the fight as well and its not effecting the boss at all
undying flames on the ground if players pass through them it keeps you on combat they are supposed to despawn after applying the debuff
 
4. on bronze dragon shirine area tornadoes are missing you can see them in this video
https://youtu.be/bqBS_Dmuwok?t=866
patrol units in this area are not working as intended they should keep patrolling and do not stop they take long stops right now.
also boss scripting is missing its not flying down to start the fight, i did manage to trigger it manually there was some issues related to tail sweep it was hitting the area of 360 dgree around him while it should be 120 behind him and sometimes it didnt face the tank even tho he had full agrro 
 
5. on Echo of sylvanas fight risen ghouls don't have correct hp value it should be 929k according to this video from 11 years ago https://www.youtube.com/watch?v=Aupe4u2zhRw
 
6. on echo of tyrande fight final RP scene is not playing and mobs around moon lights are not agrroing properly i am assuming increasing their aggro range by 5yards should solve the issue, the problem since they didnt aggro they attack you afterwards when you decide to move towards tyrande and with 90% damage reduction they are difficult to kill
Full fight in this video:https://www.youtube.com/watch?v=jl1H86GNYuA
![image](https://user-images.githubusercontent.com/36106057/208892711-369ecfcd-4714-4f7c-a68d-debb0d4cedc8.png)

**Comment by WhitemaneSylah** [comment]
Additional issue,  Baine sometimes spawns in the floor 
![image](https://user-images.githubusercontent.com/121137397/210838906-f256257f-7ea6-4792-8b1d-ee82bd96c162.png)

**Comment by UltraNix** [comment]
#4465
