### ISSUE TITLE
[PTR][Dungeon] Throne of the Tides

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1374]
**How to reproduce:** 
1. commander ulthok is not using his squeeze ability
2.  after killing lady naz'jar whole dungeon mobs respawned that should not happen
also after killing lady naz'jar she respawned (the scripted event of her) along side the ads of course , after moving through her trigger point mobs/npcs spawned again
![image](https://user-images.githubusercontent.com/36106057/208901924-f823428a-17a4-4dc7-bfeb-61b50d55dd9b.png)
![image](https://user-images.githubusercontent.com/36106057/208902125-885077d4-6f4d-42c7-9e48-673377d55dbd.png)
after moving through her trigger point mobs/npcs spawned again
![image](https://user-images.githubusercontent.com/36106057/208902348-088e50d5-f93d-440e-b847-906d24936a2d.png)
3.  mindbender ghur'sha after mind controlling a player on heroic mode if players fails to stop him it should kill the player but here it wont do that 
4.  during ozumat fight mobs stack inside eachother and dont spread out like the image below
![image](https://user-images.githubusercontent.com/36106057/208905762-29735091-8525-4fe0-8441-93125ae12d37.png)
also after finishing up the ads and players gaining the buffs ground should turn black there are some missing animations like the image below 
we are taking the damage but there are no animations
https://cdn.discordapp.com/attachments/1054548660584718369/1055101371550023721/image.png

**Comment by UltraNix** [comment]
Fixed.
