### ISSUE TITLE
[Mage] Pyromaniac talent

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Pyromaniac talent does not work at all:**

**For example use Flamestrike on 3 targets or any fire dots by the mage, you won't benefit from the talent which it provides haste **

**it should provide haste for the mage **

**https://cata-twinhead.twinstar.cz/?spell=34295)**

**Comment by WhitemaneSylah** [comment]
Confirmed

**Comment by Afgann** [comment]
fixed
