### ISSUE TITLE
[Mage] Ignite

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1380]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Ignite's dot is not stacking:**

**you have to hit 2 crits in a row before Ignite runs out, you will see, it does not stack**

**the stacking behavior has 2 parts :- 
the examples below show that how does Ignite rank 3 stacks, (each crit makes the target suffers 40% of the crit damage)

1- before Ignite first tick :- 

 : let's say ,first crit hits 1000, it provides total damage of ignite 400 (200 per tick), 
when the second crit hits 1100 it provides 440 (220 per tick)
so it must refresh ignite and the new total damage of ignite will be 840 (420 per tick )*

to summarize it, 2 hits before the first tick, add their total ignite damage together (then divide them by 2.... for per tick)

2- After the first tick:
 the first crit hits for 1000, it provides 400 (200 per tick)....... ignite's first tick will damage for 200
the second crit comes after the first tick, let's say the crit is 1100, which it provides 440 (220 per tick) so ignite will be refreshed and the total damage of ignite will be 640 (320 per tick)

Sorry for the grammatical mistakes if found 

perhaps this picture could simplify it more 
![Ignite](https://user-images.githubusercontent.com/121187280/208971543-e74352b9-c686-4f82-a8bf-9bf7977c92e1.png)

more explanation could be found here 
**(https://wowwiki-archive.fandom.com/wiki/Ignite_(old)):**
https://cata-twinhead.twinstar.cz/?spell=12846

**Comment by WhitemaneSylah** [comment]
Confirmed

**Comment by Afgann** [comment]
fixed
