### ISSUE TITLE
Rogue can stealth in combat

### ISSUE THREAD

**Issue by Damon156** [gamefreedomgit/Maelstrom#1381]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rogue can restealth und combat without Vanish.

**How to reproduce:**
Its random 

**How it should work:**
Only Not in combat or with vanish

**Database links:**

**Comment by UltraNix** [comment]
@Damon156 Need info please. Some screenshots or specific situations.

**Comment by UltraNix** [comment]
No info - closing.
