### ISSUE TITLE
[Quest] The Grand Magus Doane when killed not completing the quest

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1385]
The mob Morganth (ID:397) when killed is not completing the quest

Suggestion: Investigate the problem, because I can’t test the quest chain further

See links:
https://www.youtube.com/watch?v=KJfHFjlfegg&t=90s
https://youtu.be/h7BeaEziH-Y
https://wowpedia.fandom.com/wiki/The_Grand_Magus_Doane

**Comment by UltraNix** [comment]
Tested - works okay.
