### ISSUE TITLE
[Moved from discord] Wound Poison Proc

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1389]
Zades
OP
 — 12/15/2022 8:26 AM
Hello, when a rogue garrotes (or cheap shots for that matter). It seems to be a 100% chance wound poison will proc. I'm not sure for cheap shot, but I know for garrote at least wound poison should NOT proc. Ever. This is because you don't actually damage the target when you garrote, you just leave a bleed (which doesn't immediately tick) and a silence. 

If you garrote with instant poison on, and then immediately turn your character (to avoid autoattacks) you'll notice the sap is still on. Yet for wound poison this is not the case, it always procs wound poison instead. 

I know this shouldn't be the case seeing as a decently known technique vs frost mages in pvp is to sap ---> garrote, turn, then cheap shot so they can't blink or move when you open them. 

I.E Wound poison is procing when you use garrote, should not be the case. Thanks!
Zades
OP
 — 12/15/2022 8:28 AM
Also wanted to say, checked the tool tip of cheapshot, it also doesn't deal damage, so it shouldn't proc wound poison, only ambush should be procing poisons

**Comment by UltraNix** [comment]
Wound Poison is 50% chance, Instant - 20%.
Additional, Garrote starts melee attack, so not always Garrote proc Wound Poison.
And it's not about doing damage - it's about striking with melee (attack or spell).
It's not a bug.
