### ISSUE TITLE
[Moved from discord] During Killing Spree no auto attacks

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1390]
Zades
OP
 — 12/15/2022 8:48 AM
Supposed to have auto attacks during killing spree, but unfortunately none happen during the assaults of the spree.

**Comment by UltraNix** [comment]
![obraz_2022-12-27_162249440](https://user-images.githubusercontent.com/80540499/209687080-ed57d5b6-5151-4ccc-968f-a160ade9c5d9.png)
Works okay.
