### ISSUE TITLE
[Moved from discord] Ruins of lordaeron arena

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1391]
Jimmy17
OP
 — 12/12/2022 2:27 PM
those 3 tombs shouldn't have  collisions.
https://cdn.discordapp.com/attachments/1051815049074839612/1051815049288757328/image.png

**Comment by UltraNix** [comment]
@MrTide Screenshot not available.

**Comment by MrTide** [comment]
I will get a new image from the player as soon as possible for you

**Comment by MullichWhitemane** [comment]
Jimmy17 is no longer available, I am assuming he meant the three small pillars on the side of the middle grave. For all intents and purposes, these should have LoS, that is why they are put there.
