### ISSUE TITLE
[Moved from discord] Evasion

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1393]
Sometimes Spells even miss when behind the target.

Evasion should only work for spells that ur are facing.

https://prnt.sc/8VUZrKg2KoIS

As you can see on the screenshot, my Evasion is up, the enemy rogue is using shadowstep to jump behind me, then Blind, and the Blind is missing. Edit: The Enemy Rogue was hit capped.

**Comment by UltraNix** [comment]
Blind is considered as a ranged spell.
No bug here.
