### ISSUE TITLE
[Moved from discord] Rogues staying invisible in duels after opening

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1395]
liljon
OP
 — 12/21/2022 6:53 AM
https://www.youtube.com/watch?v=bikMTFxeg0Q The video speaks for itself. Also, similarly in duels, you can see Hunters and their pet through Camouflage.
Chris99 — Yesterday at 5:54 AM
i  was the rog and i can confirm i was laughing my ass off

**Comment by UltraNix** [comment]
I can't reproduce it.
@MrTide More info needed here.

**Comment by MrTide** [comment]
i think problem is with phasing as you can see in this image i dont phase out like the other player upon offering the duel you should phase out (both players) but if you don't move you dont phase at all
![image](https://user-images.githubusercontent.com/36106057/210118918-b4a33d33-e13c-4398-974d-5325edb2d6eb.png)
even happens after the duel
![image](https://user-images.githubusercontent.com/36106057/210118922-5b14e2c6-cd59-44f2-b297-eadbfab45adf.png)

**Comment by UltraNix** [comment]
@MrTide But you are not phased out when you offers duel to someone. Also, as I can see it happens only with rogue class?
Can you record a video of this as I can't reproduce it on my local

**Comment by UltraNix** [comment]
Fixed.
