### ISSUE TITLE
[Moved from discord] Rupture only lasting 5 secs with full combo points

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1397]
! JadedPrick
OP
 — 12/20/2022 10:22 AM
I'm playing assassination spec on dummies using 5 combo ruptures for energy regen but the ruptures are only lasting 5 secs, It's the same for all rogue specs rupture only lasting 5 secs. Rupture is important in assassination spec for poison/bleed + energy regen.

**Comment by UltraNix** [comment]
Fixed.
