### ISSUE TITLE
[Moved from discord] Lycanthoth the Corruptor Phasing issues

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1405]
LukaBxJx
OP
 — 12/17/2022 11:06 PM
After finishing this quest i cant see next quest hub.
On pictures you can see that when i am far away i can see quest hub, but when i come close then i cant see a single NPC.
I am not able to check more stuff in this area since i am stack on this quest.
https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor
https://cdn.discordapp.com/attachments/1053757592943476847/1053757593169965056/image.png

**Comment by UltraNix** [comment]
Fixed.
