### ISSUE TITLE
[Moved from discord] Shadow apparition. Shadow priest

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1406]
Nisou
OP
 — 12/18/2022 8:12 PM
Shadow apparition isn't doing ... much damage.   [Talent: https://cata-twinhead.twinstar.cz/?spell=78204]

It says it should do 8k damage scaling..ish
Mine is doing 400 Damage going to 800 crits.

Proof : 
https://cdn.discordapp.com/attachments/1054076309308968961/1054076309988442152/WoWScrnShot_121822_174028.jpg
https://cdn.discordapp.com/attachments/1054076309308968961/1054076310449831987/WoWScrnShot_121822_174128.jpg
 
Chris99 — 12/18/2022 8:42 PM
i cant agree 100%, on my shadow priest the apparitions do 4.5k ish dmg but yea will test later in more detail

**Comment by UltraNix** [comment]
Fixed.
