### ISSUE TITLE
[Moved from discord] Untargetable Vile familiars in Valley of Trials, Durotar

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1407]
Shivy001
OP
 — 12/18/2022 8:22 PM
Class warlock, level 7, but i noticed the problem earlier. Can cast spells or target it with pet, but right click targeting is just not working.
https://cdn.discordapp.com/attachments/1054078788331388999/1054078788750823525/image.png

**Comment by UltraNix** [comment]
Fixed.
