### ISSUE TITLE
[Moved from discord] The Sundried Driftwood at the Misty Reed Strand in Dustwallow Marsh is always lootable

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1408]
Saeva
OP
 — 12/18/2022 6:48 PM
I don't have any quest and its still lootable
https://cdn.discordapp.com/attachments/1054055006527029309/1054055006778691654/WoWScrnShot_121822_161504.jpg

**Comment by UltraNix** [comment]
Fixed.
