### ISSUE TITLE
[Moved from discord]  Shadow Priest Talent (Pain and Suffering)

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1409]
Chris99
OP
 — 12/18/2022 9:37 AM
Here a Screenshot of the Talent: https://prnt.sc/Kt5cyFQh-td9

I've noticed puting only 1 Point into this talent makes u take less dmg from shadowword death than 2 Points. 1 Point is like 1.6k ish dmg on urself, and 2 Points (which should lower it by an additional 20%) is like 2k ish dmg on urself, so it actually INcreases the dmg u take from ur own shadowword death instead of DEcreasing it.

Screenshot with 1 Point put in the Talent: https://prnt.sc/_DKB7_vy4nLd
Screenshot with 2 Points put in the Talent: https://prnt.sc/abnSxaz1fipc

**Comment by UltraNix** [comment]
Fixed.
