### ISSUE TITLE
[Moved from discord] Fury Warrior's Issues

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1410]
Waroxx
OP
 — 12/17/2022 4:37 AM
So there is 4 confirmed issues on Fury actually :

2. Death wish % damage increase showing 82% ( when i use prepul gear ofc ) and stays at 82% after i swap gear but the difference on the char info is the same as if i use it without prepull gear. so death wish should scale with mastery on use only and shouldn't be dynamic, i guess it will be the same problem with demono lock, so mastery prepul was possible on retail.

3. Bloodthrist znd Heroic Strike do almost the same damage with a full t11 371 ilvl ( without prepulling mastery ) as a 409 ilvl t13 gear the damage of these abilities should be recalculated.

 
LukaBxJx — 12/17/2022 10:06 PM
Problem number 4 should be related to spell que since you are probably spamming slam to much/late. I played Arms this days and i didnt have any problems with slam(cant talk about fury).
 
Waroxx
OP
 — 12/17/2022 10:11 PM
It's the same on arms like the spell remains with the yellow borders and get casted again, even if you click at mid cast
Cuz sometimes on arms you have to spam when stance dancing, maybe you don't use stance dancing macros that's why u didn't get it
 
LukaBxJx — 12/17/2022 10:13 PM
I am using stance dance, dont have any problems with any spells.
 
LukaBxJx — 12/17/2022 10:23 PM
I am playing on 39ms so i dont have any problems with warrior stance dancing.
 
Waroxx
OP
 — 12/18/2022 12:45 AM
I'm playing at 60-80ms don't have any lags too, it's not lags i played on 120ms+ servers, i never got this.
 
Waroxx
OP
 — 12/18/2022 12:58 AM
Why it happens only with slam ? cuz all spells are fine, latency affects all spells
LukaBxJx — 12/18/2022 1:27 AM
No idea. I dont have any problems while playing Arms.
Do you have any video?
 
Waroxx
OP
 — 12/18/2022 8:03 AM
i tried to make a video but nothing happens, so it was caused by latency, we skip the issue number 4 😛

**Comment by WhitemaneSylah** [comment]
Point 1 and 4 can be removed, issue 2 and 3 still outstanding

**Comment by UltraNix** [comment]
`Death wish % damage increase showing 82% ( when i use prepul gear ofc ) and stays at 82% after i swap gear but the difference on the char info is the same as if i use it without prepull gear. so death wish should scale with mastery on use only and shouldn't be dynamic, i guess it will be the same problem with demono lock, so mastery prepul was possible on retail.`
Honestly,  see no bug here. If it's still 82%, then calculations are correct. If you remove your gear, it's normal that your damage will be lower, as `Death wish` and other similar auras are % from your current damage (it's pct, not flat)

**Comment by UltraNix** [comment]
With t11:
![WoWScrnShot_010523_123725](https://user-images.githubusercontent.com/80540499/210773789-dd28bc24-29b7-41b2-93ec-3b7c5ece2fd0.jpg)

With t13:
![WoWScrnShot_010523_123920](https://user-images.githubusercontent.com/80540499/210773820-a82e2463-594b-4c33-b8e3-814dcb33089c.jpg)
Works okay.

**Comment by DjaouedBen** [comment]
Please check with bloodthrist, and also check Mastery effect on Enrage.
Another thing, Death wish % of damage increase ( mastery ) should be calculated on use only, and can't vary after that, cuz i tried prepulling with a mastery gear, the % stays the same when i use it and change gear but the damage remain the same so its variable, shouldn't be like that.

**Comment by UltraNix** [comment]
`Please check with bloodthrist, and also check Mastery effect on Enrage.` I don't need to as I see that dmg is increased on one of the basic ability.

**Comment by UltraNix** [comment]
Fixed.
