### ISSUE TITLE
[Moved from discord] Visual issues on mounting 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1411]
LukaBxJx
OP
 — 12/17/2022 11:40 PM
When i mount up, my character have weird animation bug. On both photos you can see how it looks. When i switch stance while being on mount or when i mount up.
https://cdn.discordapp.com/attachments/1053766209167949894/1053766209302188112/image.png
https://cdn.discordapp.com/attachments/1053766209167949894/1053766209721602158/image.png

**Comment by UltraNix** [comment]
Links are dead.

**Comment by MrTide** [comment]
I will get a new image from the player as soon as possible for you

**Comment by UltraNix** [comment]
No info - closing.
