### ISSUE TITLE
[Moved from discord] In the Rear With the Gear

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1413]
LukaBxJx
OP
 — 12/17/2022 10:21 PM
Cant kill quest npcs. Npcs keep reseting their HP after each attack,
also keep walking while i am attacking them and they dont agro me at all.
Both Twilight Proveditor & Twilight Slavedriver.
https://www.wowhead.com/quest=25234/in-the-rear-with-the-gear
https://cdn.discordapp.com/attachments/1053746373956218930/1053746374119788574/image.png

**Comment by Torpis** [comment]
I can confirm this bug. Mobs are Twilight Slavedriver

https://www.wowhead.com/npc=39438/twilight-slavedriver

Twilight Proveditor's seem okay. Location is 39.36, 24.44 in Mount Hyjal

**Comment by UltraNix** [comment]
Already fixed.
