### ISSUE TITLE
[NPC] [Script] Quest scripted NPCs despawning upon death

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1414]
The NPCs that are spawned via quest script often disappear (despawn) upon their death without dying animation and leave no body behind. I am really not sure if it happens all the time or sometimes but i have noticed this happening before, but forgot where.
Now I have seen it happen with [Daggerspine Marauders](https://www.wowhead.com/npc=2775/daggerspine-marauder), and  with additional spawns of [Hammerfall Grunts](https://www.wowhead.com/npc=2619/hammerfall-grunt) during quest Kinelory Strikes.
I will add more in case I find other such mobs and this issue is still open.

**Comment by UltraNix** [comment]
@Greywolf59 It's not a generic issue, but with these particular mobs and how ther are summoned. Just report every single one in new reports.

**Comment by UltraNix** [comment]
Fixed.
