### ISSUE TITLE
[Quest] Kinelory Strikes - available too early

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1415]
Quest [Kinelory Strikes](https://cata-twinhead.twinstar.cz/?quest=26116) (https://www.wowhead.com/quest=26116/kinelory-strikes)
should be available only after you hand in the quest [Quae Trusts You](https://cata-twinhead.twinstar.cz/?quest=26114).
This quest is available right away, without any prerequisites.

Also as a side note, [Kinelory](https://www.wowhead.com/npc=2713/kinelory) stayed in human form the whole fight and never used her [Bear Form](https://www.wowhead.com/spell=4948/kinelorys-bear-form). Might be due to mobs dying pretty fast though.

**Comment by Afgann** [comment]
fixed
