### ISSUE TITLE
[Quest] Northfold Manor - missing ties to Into Arathi

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1416]
Quest [Northfold Manor](https://www.wowhead.com/quest=26093/northfold-manor) should be a follow-up available after you hand in the quest [Into Arathi](https://www.wowhead.com/quest=26139/into-arathi).

This quest is not offered at all.

Note: After Northfold Manor, there should be one more quest, [Stromgarde Badges](https://www.wowhead.com/quest=26095/stromgarde-badges), so basically two quests are missing completely atm.

**Comment by Greywolf59** [comment]
UPDATE: [Northfold Manor](https://www.wowhead.com/quest=26093/northfold-manor) is obtainable after completing [Hero's Call: Arathi Highlands!](https://www.wowhead.com/quest=28573/heros-call-arathi-highlands).
It should also be obtainable after completing [Into Arathi](https://www.wowhead.com/quest=26139/into-arathi).

**Comment by UltraNix** [comment]
Fixed.
