### ISSUE TITLE
[Dungeon] Zul gurub Heroic

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1417]
1. Spirit of redemption interaction on bloodlord mandokir is not working as intended friendly npcs can't ress you when you are on that form it should work eitherway and you should be able to get the revive after loosing SOR effect
Friendly/event npc around the blood lord mandokir are falling under ground that should not happen
![image](https://user-images.githubusercontent.com/36106057/209339919-ccd5a8e0-ecd2-43a8-9c93-7019469c2bde.png)
2. Ritual tiki mask got issues they have wrong models and some can't be hit by the players
![image](https://user-images.githubusercontent.com/36106057/209340390-751d2ad0-4817-4849-a7c5-4889dcf8dcaf.png)
3. there are some pathing errors as well, i believe this happens all over the world but just for the reference these are the mobs before high priestess kilnara
npcs around this area also attack you through the walls and floors 
![image](https://user-images.githubusercontent.com/36106057/209342640-fe8c69bb-941e-4d75-a33b-9220b24734da.png)
4. zanzil is not scripted properly cauldrons are missing, pack of npcs that he summons are not working, basically its impossible to do the boss
it should work like this
https://youtu.be/SFkE8J5QYAs?t=1433
5. on jindo fight we are unable to destroy the hikkari chains even tho we destroyed the barried the correct way
![image](https://user-images.githubusercontent.com/36106057/209345318-4eeaba1a-321d-46f5-aa47-96dab19c3379.png)

**Comment by Sketish** [comment]
Updated version on  https://github.com/gamefreedomgit/Maelstrom/issues/3341
