### ISSUE TITLE
[Quest] [Minor] Redridge Mountain's minor issues

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1418]
Redridge Mountain's all quest is being tested. Here are the issues that i found.
It was a good quest chain, I enjoyed it very much!

https://docs.google.com/document/d/1JXdUci8RQF8bRHNW5M-re_3zTmnUJmtK5bIAQ2DVwFo/edit?usp=sharing

**Comment by UltraNix** [comment]
Fixed.
