### ISSUE TITLE
[Quest] Basic Botany - not working, phasing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1421]
[Basic Botany](https://www.wowhead.com/quest=28733/basic-botany) does not work. When you take the quest it phases you and you can see the plague wagons and the pool of light at the tile in front of you and the "treasure map tile" . However the camera does not change and there are no balls of light falling down to click. Your cast bar does not change either.
Another problem is that even if you abandon the quest and ride away you stay being phased and you can't see any npcs, veins, herbs etc until you log out and back in (teleporting to completely another location might help with that too, haven't tried).

Videos how it should look: https://www.youtube.com/watch?v=eFFdFVJ354Q; https://www.youtube.com/watch?v=RIquMuv42iE

It is possible the other quests following this one might be bugged too.

**Comment by UltraNix** [comment]
Fixed.
