### ISSUE TITLE
[Dungeon] Shadowfang Keep N minor bugs

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1425]
1. One [Frantic Geist](https://www.wowhead.com/npc=47131/frantic-geist) on the roof/scaffold keeps sapmming /say  belonging to [Inspector Tarem](https://www.wowhead.com/npc=23567/inspector-tarem)

2. [Baron Silverlaine](https://www.wowhead.com/npc=3887/baron-silverlaine) [summons](https://www.wowhead.com/spell=93857/summon-worgen-spirit) Worgen Spirits. Second of his summoned orbs (pre-worgen form) has dummy (infernal) visible. I think it was either [Rethilgore](https://www.wowhead.com/npc=50834/rethilgore) or [Razorclaw](https://www.wowhead.com/npc=50869/razorclaw-the-butcher).

**Comment by Afgann** [comment]
fixed
