### ISSUE TITLE
[Moved from discord] warrior charge + Crowd Control

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1427]
Jimmy17
OP
 — 12/16/2022 1:27 AM
When warrior charge  into freezing trap , warrior charge's path should stop at the freezing trap. he shouldnt be gliding to the target while trapped. and same goes for All Crowd control.

it's bugged also with roots , when i root a warrior mid charge it stops him but when the root expire he will still  glide to the target which is wrong. 

Any type of CC made after the warrior charged , should intercept his charge. Also [Entrapment] talent of survival hunter which would cause ice trap to root for 4 sec , is rooting warrior for 2 secs when he's charging through it.

**Comment by UltraNix** [comment]
Fixed.
