### ISSUE TITLE
[Moved from discord] Shadow dance duration

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1428]
PrinceArt
OP
 — 12/16/2022 1:05 AM
Bug: Shadow dance is now currently 8 sec without glyph, and 10 sec with shadow dance glyph, the bug is shadow dance duration is acting as if its glyphed.

How it should work: Shadow Dance without glyph should be 6 sec duration and with glyph which is additional 2 sec, should be max 8 sec.

**Comment by gaga-whitemane** [comment]
This issue has been fixed along with other issue packs for spell duration issues overall. I did test this case of this spell and it works now like it is supposed to work.
