### ISSUE TITLE
[Moved from discord] Distract in camouflage

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1430]
PrinceArt
OP
 — 12/16/2022 12:16 AM
The bug: When hunter is in camouflage and you use distract on them, either while theyre moving or not (outside of combat) they're not turning in any way.

How it should work: Their character should turn the other way around or turn to the side, depending on the angle you throw the distract even in camouflage.

**Comment by UltraNix** [comment]
Fixed.
