### ISSUE TITLE
[Moved from discord] Feral charge

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1433]
Jimmy17
OP
 — 12/15/2022 4:10 PM
Fixed Feral Charge (Cat) not setting proper orientation after jumping.

the orientation is fixed now.

but 2 new issues with it which were working before.

1. ravage doesn't light up anymore after using feral charge.
2. when i feral charge it's in sloooow motion , it should be way faster than that , just as how it was working before

**Comment by UltraNix** [comment]
`ravage doesn't light up anymore after using feral charge.`
![WoWScrnShot_122622_115531](https://user-images.githubusercontent.com/80540499/209541058-30887cbe-88f8-484c-9f2f-48b2d33bf13d.jpg)

**Comment by UltraNix** [comment]
Fixed.
