### ISSUE TITLE
[Moved from discord] feral spell "Survival Instincts"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1434]
Jimmy17
OP
 — 12/15/2022 4:05 PM
it's worse now.
1. it doesn't work at all the damage reduction
2. when i go in night elf form i shouldn't lose the buff , the buff should remain but the Effect shouldn't work when in night elf form. but i can always go back to cat / bear form and the buff will work again.

**Comment by UltraNix** [comment]
Fixed.
