### ISSUE TITLE
[Moved from discord] hunter spell "Camouflage"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1435]
Jimmy17
OP
 — 12/15/2022 3:59 PM
Camouflage shouldn't break when i'm casting any  of those spells [Steady shot]  [Aimed shot] [Dismiss pet] or when i call a pet but the pet that i call should ofc be out of camouflage effect. Also when i cast my mount it should break camouflage once i'm mounted up instead of breaking it instantly

**Comment by UltraNix** [comment]
`Also when i cast my mount it should break camouflage once i'm mounted up instead of breaking it instantly`
Summoning a mount is also an action - I need more proofs about this one.

**Comment by UltraNix** [comment]
Fixed.
