### ISSUE TITLE
[Moved from discord] "Glyph of Concussive Shot" vs disc priest's 4 set pvp bonus

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1436]
Jimmy17
OP
 — 12/11/2022 10:53 PM
disc priest 4  set pvp bonus shouldnt work if hunter has   [Glyph of Concussive Shot].
 [Glyph of Concussive Shot] should limit the priest movement speed to 50%
 
 GaGa — 12/12/2022 12:28 AM
please give me link to this disci set bonus or any item from this set
Jimmy17
OP
 — 12/12/2022 12:49 AM
thats an item from the set
[Cataclysmic Gladiator's Mooncloth Robe]
 
voda — 12/12/2022 1:11 AM
https://www.wowhead.com/item=73691
https://www.wowhead.com/item-set=-439
https://www.wowhead.com/spell=33333/holy-spark

**Comment by UltraNix** [comment]
Fixed.
