### ISSUE TITLE
(Quest) Warchiefs revenge 

### ISSUE THREAD

**Issue by firemonster245** [gamefreedomgit/Maelstrom#1439]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cant do warchiefs revenge because i get disconnected and i bounce around
Playing as a goblin mage
https://youtu.be/lXsHECtyFa8

**How to reproduce:**
Start the quest

**How it should work:**
https://youtu.be/YqV9oBPja68

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
