### ISSUE TITLE
[Quest] The Battle for Andorhal - multiple versions available

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1440]
I have managed to gather 3 versions of this quest at the same time, plus [Hero's Call: Western Plaguelands](https://www.wowhead.com/quest=28576/heros-call-western-plaguelands).

Got one in Booty Bay: https://www.wowhead.com/quest=28749/the-battle-for-andorhal
One in Chillwind Camp: https://www.wowhead.com/quest=27158/the-battle-for-andorhal
And one in Hinterlands: https://www.wowhead.com/quest=28505/the-battle-for-andorhal

It would make sense that only one of these quests should be available at the time. If you take one, you should not be able to take the others, not even after you hand it in. At least it would be so even from a pure logic of not having three basically same quests stacked in quest log at the same time (plus Hero's Call version).

This comment is from patch 9.0.3 but I do believe it should apply to any patch really: https://www.wowhead.com/quest=27158/the-battle-for-andorhal#comments:id=5266409

I also believe there is more quests like this with the same problem. I definitely came upon one before, I think I have mentioned it in one of my older reports (hopefully, can't recall at all).

**Comment by MrTide** [comment]
this event was pretty messed up we did some improvements 
as you can see here https://github.com/SallyWhitemane/Maelstrom/issues/384
i guess it needs more

**Comment by Greywolf59** [comment]
Yup this post is just about the starting quest that leads to wester plaguelands itself. I have also noticed that when I handed in the quests, only the Hero's Call opened up a follow up (I have handed it in as the last). Which I am not sure if it should be so.
Some Alli NPCs further away from the Alli camp are not fighting the Scourge at all either. I will make my way through Plaguelands quests during today and tomorrow so I will see how it looks further on.

**Comment by Greywolf59** [comment]
See point 1. and then from point 13. onwards here: https://github.com/gamefreedomgit/Maelstrom/issues/1445

**Comment by MrTide** [comment]
guess nothing much is done :D i assume when an issue is closed its fixed looks like its not

**Comment by UltraNix** [comment]
Fixed.
