### ISSUE TITLE
[Dungeon] throne of the tides Feedback

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1443]
jellyfish elevator disappeared on players after server restart idk if this happens everytime but its something worth looking into
![image](https://user-images.githubusercontent.com/36106057/209450301-8fa6b2de-1a4f-47c8-9592-de7bcc8aa58b.png)
 
mobs spawning under water on neptulon event and area around us still missing animations.. ground didnt turn black
![image](https://user-images.githubusercontent.com/36106057/209450419-645023b7-bfd9-442b-adad-ba4948cf0a00.png)

**Comment by WhitemaneSylah** [comment]
HEROIC SPECIFIC

BEFORE BOSSES:
When entering main atrium on ground floor, can immediately hug wall to the left and bypass the tentacle,  this should be an invisible wall
 
1st boss : Scripting was fine - no action

Before 2nd boss:  Cutscene RP does not function fully,  boss spawns immediately during the cutscene.  This should be delayed until cutscene ends where boss jumps from the roof to the floor.    Have found that boss can attack before cutscene ends causing deaths

After 2nd boss : Jellyfish lift disappears,  Teleporter is also missing to allow players to go to the bottom.

Enroute to Erunak :  Faceless watchers can fall under the floor after using gravity lift.  Groundslam is also following players but should be in an AOE around the watcher.  Cast order should be Gravity Lift > Groundslam .  Have found evidence that the gravity lift is used but groundslam does not follow.

Erunak's Fight :   Mindbender does not use player abilties when enslaved.

Last boss Ozumat:  Vicious mindlashers should spawn 5 seconds into encounter,  One spawns in then two more after a set period.  Unyielding behemoths spawn in 15 seconds after - one at a time.  On our PTR the behemoths are spawning in instantly after 45 seconds (2 at a time) . 
Stage 2 : Blight beasts move at 100% speed, they should be 60% . Ozumat should spit pools "Blight of Ozumat" on the floor , 10 yard radius lasting 30 seconds inflicting 800 shadow damage every second, This does not happen
Stage 3: Working correctly
Retail video showing fights 
https://www.youtube.com/watch?v=WhUyJPMGBIM
https://www.youtube.com/watch?v=SmQ0YTFu61k

**Comment by WhitemaneSylah** [comment]
![image](https://user-images.githubusercontent.com/121137397/212498700-3fddd330-d97f-4c7b-82aa-2d7a447ab018.png)
Teleporter NPC that is missing as requested by Gaga

**Comment by UltraNix** [comment]
Fixed.

**Comment by WhitemaneSylah** [comment]
Above issue not fixed.

**Comment by WhitemaneSylah** [comment]
pending investigation, HC working

**Comment by Commander-Rug090** [comment]
Update: 

**lady Naz'Jar:**
geysers dont do any damage
she is damagable, during second phase, she should be shielded and immune until the ads die. 


Commander ulthok:
Dark Fissure: doesnt do any periodic damage, initial damage does happen (30k)


Erunak 
mind controlling a healer can break thier targetting for friendlies hwen the boss dies. relogging fixes this issue.

enemies before last Ozumat, dont debuff the players when they attack, and there are too many. should be half as much. 

Ozumat:
Blight beasts should have like 3 times the armour or health, should be harder to kill, the exact amount is hard to explain, but the tank should not be able to solo kill them. 
Blight of Ozumat is not working at all.

**Comment by UltraNixx** [comment]
`lady Naz'Jar:
she is damagable, during second phase, she should be shielded and immune until the ads die.`
She is not immuned to all damage, but deflect all spells and ranged attacks.

**Comment by UltraNixx** [comment]
`Commander ulthok:
Dark Fissure: doesnt do any periodic damage, initial damage does happen (30k)`
![asfd](https://user-images.githubusercontent.com/126691570/222779861-665ea4ff-9ef1-4a8c-8e5a-694350c949dc.png)

**Comment by UltraNixx** [comment]
`Erunak
mind controlling a healer can break thier targetting for friendlies hwen the boss dies.`
What do you mean by `break thier targetting`?

**Comment by Commander-Rug090** [comment]
quick question on your two "blight of Ozumat" and "dark fissure" damage screenshots, is that after changing something or testing as is? because we were definatly not seeing that damage. 

i have a recording of it too. https://youtu.be/xG1brEarIjY?t=1641

**Comment by UltraNix** [comment]
> > `Erunak mind controlling a healer can break thier targetting for friendlies hwen the boss dies.` What do you mean by `break thier targetting`?
> 
> when trying to target a friendly after this mind control they cannot heal, or they appear as a hostile completely. (game treats them as hostile. (sorry wasnt more descriptive at the time)

Can you make a video of this?
