### ISSUE TITLE
Western Plaguelands Alliance Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1445]
1. [Ginny Goodwin](https://www.wowhead.com/npc=46006/ginny-goodwin)
- Ginny Goodwin sometimes runs around and melees invisible enemies. She does not get hurt by anything.
- This happens prior doing Andorhal questline.

2. [Andorhal Defenders](https://www.wowhead.com/npc=44448/andorhal-defender)
- Some of these guys further away from Alli camp are not fighting the Scourge, nor they are attacked by the Scourge.
- This is prior Andorhal questline.

3. [Scholomancer](https://www.wowhead.com/quest=27162/scholomancer)
- [Darkmaster Gandling](https://www.wowhead.com/npc=44323/darkmaster-gandling) does not use [Shadow Prison](https://www.wowhead.com/spell=86780/shadow-prison) properly.
- Video how it should look: https://www.youtube.com/watch?v=bLrqenjExxI 0:55

4. [Ambushed!](https://www.wowhead.com/quest=27171/ambushed)
- When you take the quest [Thurman Grant](https://www.wowhead.com/npc=45165/thurman-grant) should disappear from Chillwind Camp, so when you come there to hand in the quest, you don't see him, because he moved elsewhere.
- At the moment you can still see Thurman Grant in Chillwind Camp, even after handing in the quest.

5. [Combat Training](https://www.wowhead.com/quest=27174/combat-training)
- Provincial Minutemen are stacked on one another; IDs: npc=45232, npc=45234, npc=45231, npc=45233

6. [Zen'Kiki](https://www.wowhead.com/npc=44269/zenkiki)
This guys spawns and follows you when you take the quest [Zen'Kiki the Druid](https://www.wowhead.com/quest=26953/zenkiki-the-druid).
- He runs a bit too fast I would say.
- When he tried to shapeshift into cat form, he just fell down through the textures. I still got kill credits though.
- On follow up quest he did not fall throguh the textures even in cat form. However he shapeshifts back from the forms a bit too early before he finishes the whole intended script for his shapeshift.

7. [This Means WAR](https://www.wowhead.com/quest=27001/this-means-war-wild-arachnid-roundup)
- It is simply impossible to lure the spiders in by using the horse, they run in fear in all directions, not just away from you.
- If you kill the [spiders](https://www.wowhead.com/npc=44284/northridge-spider) on your own you get the credit for the quest. I think only the kill by the guards should count.

8. [Morris Vant](https://www.wowhead.com/npc=45148/morris-vant) and [Outfitter Mendelev](https://www.wowhead.com/npc=45149/outfitter-mendelev)
- These NPCs have wrong icon on trade option and they will not commence in trade with the player.

9. [The Good People of Hearthglen](https://www.wowhead.com/quest=27153/the-good-people-of-hearthglen)
- Speaking to [Morris Vant](https://www.wowhead.com/npc=45148/morris-vant) does not open chat tab with his answer, player just gets the credit.

10. [Hearthglen Recruits](https://www.wowhead.com/npc=44437/hearthglen-recruit)
- All of the recruits in Hearthglen who stand on their own and do not walk in patrols are standing in combat-ready pose. They should stand normally.

11. [Cult-Sworn Pugilists](https://www.wowhead.com/npc=44444/cult-sworn-pugilist)
- All of the Pugilists act like they are fighting some enemy. Only one or two that train on dummies should do so.

12. [Cult-Sworn Warlock](https://www.wowhead.com/npc=44443/cult-sworn-warlock)
- All of the warlocks are acting like they are tinkering with something, even when they walk about. Should not be so.

Here follows **BATTLE FOR ANDORHAL (ALLIANCE)**

**PHASE ONE**
(started by handing in [The Battle Resumes!](https://www.wowhead.com/quest=27197/the-battle-resumes))

13. [Andorhal Defender](https://www.wowhead.com/npc=44448/andorhal-defender)
- Defenders sometimes keep attacking already dead enemies (only if they killed them without player's support)
- There seems to be a bit too many of the Defenders at certain spots (Square for example)

14. [Deathguard War Captain](https://www.wowhead.com/npc=44449/deathguard-war-captain)
- Some Captains killed by Defenders keep building rage and refreshing [Rallying Cry](https://www.wowhead.com/spell=85527/rallying-cry) even as dead and Defenders keep hitting them.

15. [Andorhal Deathguard](https://www.wowhead.com/npc=44447/andorhal-deathguard)
- They do 0 damage to the Defenders but they take damage from them just fine.
- Dead Andorhal Deathguards are sometimes still being attacked by Defenders.
- Dead Deathguards can aggro you and start following you and hitting you. Player can't hurt them except with AoE. Me being low level warrior I could not test if the AoE can kill them for good.
- This also results in permanent aggro.
-  This happened at 45.6/71.3, near the tower.

17. [Ginny Goodwin](https://www.wowhead.com/npc=46006/ginny-goodwin)
- Still fighting invisible enemies.

**PHASE TWO**
(Activated by taking [The Depravity of the Forsaken](https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken).)

18. [The Depravity of the Forsaken](https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken)
- After taking the quest phase changes and the quest is auto-complete.
- The automated event is missing.
- Video: https://www.youtube.com/watch?v=tauTHtQSu-g

19. [Ginny Goodwin](https://www.wowhead.com/npc=46006/ginny-goodwin)
- We can finally see she is fighting [Forsaken Troopers](https://www.wowhead.com/npc=45242/forsaken-trooper).

20. [Provintial Minutemen](https://www.wowhead.com/npc=44944/provincial-minuteman)
- They are level 1 instead of 40.
- Video: https://www.youtube.com/watch?v=tauTHtQSu-g 0:42

21. There are two [Andorhal Deathguards](https://www.wowhead.com/npc=44447/andorhal-deathguard) still near Thassarian. Should not be there.

22. [Forsaken Troopers](https://www.wowhead.com/npc=45242/forsaken-trooper) and [Provintial Minutemen](https://www.wowhead.com/npc=44944/provincial-minuteman)
- Forsaken Troopers are way to far into Alliance Territory (thus Ginny Goodwin bug)
- Andorhal is full of Troopers and Minutemen walking around, not fighting each other. But on the video you can notice the town is pretty much empty.
- Videos: 0:32 at https://www.youtube.com/watch?v=tauTHtQSu-g; 0:37 at https://www.youtube.com/watch?v=OdrO_20nQXQ

23. There is invisible dead [Lurid](https://www.wowhead.com/npc=44471/lurid) on a road out of town, not far from proper Lurid. Only his axe is visible. Not sure if the ID is right.

24. [Brother Against Brother](https://www.wowhead.com/quest=27202/brother-against-brother) and [Val'kyr Incursion](https://www.wowhead.com/quest=27201/valkyr-incursion)
- These quests should provide you with group of Militia as a pet once you enter further in the town. This does not happen.
- Video: https://www.youtube.com/watch?v=4IdFs0UHb1s

25. [Frightened Provincial Minutemen](https://www.wowhead.com/npc=45101/frightened-provincial-minuteman)
- These guys actively fight Troopers instead of runnign around in fear, although they keep "Feared posture") the whole time.

26. [Lesser Val'kyr](https://www.wowhead.com/npc=45239/lesser-valkyr)
- Based on all the videos linked earlier I can say that there is too few val'kyrs at the closer end of town and that they are a bit higher than needs be. Still reachable by ranged weapons though.

27. [Aradne](https://www.wowhead.com/quest=27204/aradne)
- This quest also does not provide you with the Milia pet, though it should.

28. [Alas, Andorhal](https://www.wowhead.com/quest=27206/alas-andorhal)
- As soon as you take the quest, phase shifts back to the basic one (beofre starting the quest chain)
- On the video below it is visible the phase stays as is at leat until you hand in the quest.
- Video: https://www.youtube.com/watch?v=o2yABrN7bgY
- After handing in the quest, phase stay on the basic one. It should phase out Alliance flight point for the Alliance.

**Comment by Torpis** [comment]
Bug # 15 [Andorhal Deathguard](https://www.wowhead.com/npc=44447/andorhal-deathguard)

As a Paladin, I can confirm they cannot be killed for good - they just keep attacking you until you leash them.

**Comment by UltraNix** [comment]
`[The Depravity of the Forsaken](https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken)` won't be fixed.

**Comment by UltraNix** [comment]
Fixed.
