### ISSUE TITLE
[Moved from discord] Windwalk Weapon Enchant

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1447]
liljon
OP
 — Yesterday at 12:38 AM
While the effects of the proc work fine, it's proc rate is absolutely messed up. On average, it procs after 2 minutes of continuous, 100% uptime (tested as a prot paladin spamming a basic rotation, always being on GCD).

I've done a bit of digging into WoWHead, and this is what I found (take everything from here with a grain of salt, as this is player tested and not given information by Blizzard, and the following copy pastes are all pre 4.3) https://www.wowhead.com/spell=74244/windwalk#comments

Patch 4.0.3. "After two hours of testing in various heroics, I've come to the following conclusions:

1) There is no internal cooldown. Back to back procs are possible, and hardly even uncommon.

2) If the enchant has a static PPM, it is at least 2 ppm. Currently, I'm sitting at 2.2 ppm though I have further testing to do. Theorized upper bound of 3 PPM based on 3 back to back procs."

Patch 4.0.3. "This buff has no internal cooldown, it is able to refresh itself, although unlikely due to the low proc rate, estimated at 4-5% using dummies, devastate, recount and spare time.

As far as I can tell this enchant still procs on failed, eg. missed, dodged, parried, melee attacks. But more testing needs to be done to accurately support this claim."

Patch 4.1.0. "The tests with a rotation were 6 minutes long. The averages are as follows;

For ONE Windwalk, rotation, 6 minutes;
33.49% Uptime on the Windwalk buff.
Average of 16 procs per test (2.66 Procs Per Minute)

For TWO Windwalks, one main hand one off hand, rotation, 6 minutes;
43.38% Uptime on the Windwalk buff (more on that later)
Average of 28 procs per test (4.66 Procs Per Minute)"

Make of this information what you will - one thing is for sure, right now, the proc rate is so low you are probably better off with Mongoose from TBC. 
liljon
OP
 — Yesterday at 5:31 PM
Or, just do the normal person thing and enchant Landslide or something. BIGDAMJUDGE

**Comment by Afgann** [comment]
fixed
