### ISSUE TITLE
[Pet] Pet don't like flight

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1448]
When the player take a flight and starts the route, the pet is following his player on the ground.
Suggestion: In flight mode despawn the pet and after the player arrives to the location it should spawn automatically.
![Flight pet bug](https://user-images.githubusercontent.com/120984471/209565848-49f3178e-475c-4570-bfd1-58487eecff30.jpg)

**Comment by Afgann** [comment]
fixed
