### ISSUE TITLE
[Moved from discord] Feral druid stats

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1450]
Jimmy17 — 12/16/2022 11:38 AM
i have 6085 agility and i only have  8.3k attack power. i should have some where arround 16.7k Attack power

also im full cata gear and i have 60 000 armor lol  which is wrong should be arround 27k
and when i have 3/3  [Thick Hide] talent on , i have 229 000 armor so i think  [Thick Hide] calculation is wrong. even with that specc'ed i should have something arround 53k armor. Also mastery isn't working for feral , i have 63% mastery (should increase bleed dmg by 198%) and my bleeds are ticking for 7-8k. 
 
UltraNix — 12/19/2022 6:03 PM
@Jimmy17 Could you re-test it?
 
Jimmy17
OP
 — 12/19/2022 6:07 PM
@Ultranix  Attack power is fixed now , but i still have 60k armor without [Thick hide] talent and with [thick hide] i get 220k armor which is wrong
also mastery isn't working
 
UltraNix — 12/19/2022 6:08 PM
Okay
 
Peter Weißbier — 12/24/2022 1:00 AM
train mastery at your trainer i believe 
 
Jimmy17 — 12/24/2022 1:37 AM
I had it on. Still doesnt work
Peter Weißbier — 12/24/2022 1:41 AM
at the real trainer i think that fixed it
cus the custom trainer doesnt train it
 
Jimmy17 — 12/24/2022 1:53 AM
ye still doesn't work

**Comment by UltraNix** [comment]
0 mastery - avg bleed for 272
![WoWScrnShot_122722_100213](https://user-images.githubusercontent.com/80540499/209641850-14f5780a-02f9-45ae-b00f-4adbed43fc30.jpg)

8 mastery (+25%) - avg bleed for 340
![WoWScrnShot_122722_100408](https://user-images.githubusercontent.com/80540499/209641920-52092c5a-0519-4b4e-89d8-da4c672a4a02.jpg)

Everything works okay here.

**Comment by UltraNix** [comment]
Fixed.
