### ISSUE TITLE
[Moved from discord]  4 t13 didn’t work on a warlock

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1451]
qplolkaqp — 12/12/2022 11:38 PM
Hello, I’ll testing warlock in demon spec, and I noticed that 4 t13 doesn’t working(burning soul don’t give 10% spell damage after using)

**Comment by UltraNix** [comment]
![obraz_2022-12-27_173557934](https://user-images.githubusercontent.com/80540499/209695154-7a812234-f179-471c-ba93-0bb87928bba5.png)
Works okay.
