### ISSUE TITLE
[Moved from discord] Talent Reset

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1452]
Buuba — 12/13/2022 3:37 PM
Sometimes after you log in some talent points get reset and you are missing the key ability you get from choosing that spec
 
𝐸𝒱𝐼𝐿 𝒜𝑅𝒯𝐻𝒜𝒮 — 12/13/2022 8:13 PM
Same thing

**Comment by UltraNix** [comment]
I belive it should be already fixed.

**Comment by MrTide** [comment]
Sadly it still happens
i believe its because of the disconnects and crashes similar issue with items cooldowns and such

**Comment by UltraNix** [comment]
Still have no clue how to reproduce it.

**Comment by MrTide** [comment]
I can reproduce it but its doesnt happen every time, i sat on it for a week, it sometimes happens and sometime doesnt, for example i just did my talents then relogged and after logging back in they all reset and i had to take them again.. idk maybe something related to character saving

**Comment by MrTide** [comment]
fixed already
