### ISSUE TITLE
[Moved from discord] Stood in the fire achievement

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1453]
𝐸𝒱𝐼𝐿 𝒜𝑅𝒯𝐻𝒜𝒮 — 12/13/2022 5:53 PM
Had died from falling and earned this achieve
https://cdn.discordapp.com/attachments/1052229381113782272/1052229381268975696/WoWScrnShot_121322_172151.jpg
![image](https://user-images.githubusercontent.com/36106057/209572588-523b0728-4034-4f53-98d3-1e128a3e0333.png)

**Comment by UltraNix** [comment]
Already fixed.
