### ISSUE TITLE
[Moved from discord] Portrait and Icons issue

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1454]
Cropinky — 12/13/2022 9:12 PM
sometimes i log in and my icons look like this idk why it happens, i use your client
https://cdn.discordapp.com/attachments/1052279262901719110/1052279263052701753/image.png

![image](https://user-images.githubusercontent.com/36106057/209572666-9b7b8f70-6858-4775-b238-241d3ed4f1bc.png)
-
 
skid ツ
 — 12/17/2022 6:10 PM
When you enter the spell book as a paladin, the icon is bugged and isn't the correct icon. It does the same thing with retribution aura.
https://cdn.discordapp.com/attachments/1053683146710855751/1053683147058987118/image.png
![image](https://user-images.githubusercontent.com/36106057/209572626-c5bc1360-34eb-44fd-843e-9b86385f6e40.png)

**Comment by UltraNix** [comment]
This is nothing with the server, but with client or addons.
