### ISSUE TITLE
[Quest] "Through the Troll Hole" not working

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1455]
When entering the portal in Ruins of Aboraz it should automatically complete the quest itself and auto accept the next quest in the quest chain
Suggestion: Investige the problem
See links:
https://wowpedia.fandom.com/wiki/Through_the_Troll_Hole
www.youtube.com/watch?v=83RWurfNLHQ&t

**Comment by UltraNix** [comment]
Tested - works okay.
