### ISSUE TITLE
[Dungeon] Scarlet Monastery - Entrances bug after Graveyard

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1457]
This is what happens when you enter the dungeon portal on the right, to the library if I am not wrong. Alliance toon
https://i.gyazo.com/2902c3d7b226089a03768d487bb223c9.png

I can't use .tele or anything. Had to alt+F4 out of the game. After logging back in I popped out at my heartstone location.

**Comment by Greywolf59** [comment]
UPDATE: Same thing happens when entering Armory.

**Comment by MrTide** [comment]
looks like its resolved no reports ingame closing it
