### ISSUE TITLE
[Quests] [NPCs] Stranglethorn Vale Issues 

### ISSUE THREAD

**Issue by MinusTwenty** [gamefreedomgit/Maelstrom#1458]
It was very fun to do this quest chain and storyline it was well scripted but here are the issues I find:

https://docs.google.com/document/d/1ol4YPe6P89PrmKdY4LI23v3EJ0CZTKSHgoWeIUE-Y7k/edit?usp=sharing

**Comment by UltraNix** [comment]
Fixed.
