### ISSUE TITLE
[Minor] Tirisfal Glades - Quest Objects visible, lootable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1460]
[Gloom Weed](https://cata-twinhead.twinstar.cz/?object=175566), [Tirisfal Pumpkin](https://cata-twinhead.twinstar.cz/?object=375) and [Corpse Worm Mound](https://cata-twinhead.twinstar.cz/?object=208828) are visible on herbalism map and are lootable (Weed and Pumpkin are empty, Worm Mound contains Corpse Worm) even by Alliance players without corresponding quests.

**Comment by MrTide** [comment]
Can confirm, what players means that they should not be interactable for the players without having the quest related to them
Note: they contain the items required for the quest while you have it.

**Comment by UltraNix** [comment]
Fixed.
