### ISSUE TITLE
[Class Priest] Prayer of Mending

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1462]
**Description:**
Priest ability mostly used on holy/disc class

**How to reproduce:**
Prayer of mending jump speed is instant
on first cast you can see the travel speed but after that its gone and each jump becomes instant even initial cast is instantly on the player although the animation is there

**How it should work:**
it should not be instant and consider travel time

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Prayer_of_Mending#:~:text=Prayer%20of%20Mending%20(abbrv.,a%20buff%20on%20the%20target.

**Comment by UltraNix** [comment]
Fixed.
