### ISSUE TITLE
[Class : Warrior][Skill: Heroic leap][Skill: Charge]  Travel time affected by movement speed

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1463]
Heroic leaps travel time is too slow.  this is also showing on Charge 

https://youtu.be/FC5BlQ1HfFk

Comparison between both servers

https://youtube.com/clip/UgkxiKBI_K_bE8CJ20GlBtWS06x_KP9UVugb -  Showing correct travel time

Edit -  Tide and I have found that heroic leap is affected by movement speed affects IE body and soul from holy priest. This also affects charge

**Comment by MrTide** [comment]
Confirmed requires attention

**Comment by UltraNix** [comment]
Fixed.
