### ISSUE TITLE
[Quest] Buried Blades - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1464]
Reporting this quest seperately from the rest of my EPL report since it can't be completed.

Quest: [Buried Blades](https://www.wowhead.com/quest=27467/buried-blades)
Issue: [Light-Touched Blades](https://www.wowhead.com/item=61302/light-touched-blades) can't be used on [Slain Scourged Troopers](https://www.wowhead.com/npc=45695/slain-scourge-trooper). They don't have the cog icon on them and clicking the Blades item elicits "Invalid Target" response.
Video: 2:05 https://www.youtube.com/watch?v=6daLtxu-DOs
Proof: https://i.gyazo.com/5649c63fc58b6822a3f3b46b9c64ae1d.mp4

**Comment by Afgann** [comment]
fixed
