### ISSUE TITLE
[Quest] Gidwin's Fate Revealed - bad scripted event, undoable, possible crash cause

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1466]
Making separate report for this EPL quest since it has serious issue.

Quest: [Gidwin's Fate Revealed](https://www.wowhead.com/quest=27526/gidwins-fate-revealed)
Issue: When the player enters ziggurat, camera switches to autopilot and moves to ziggurat. There should be an event palyed out. Instead you see just two empty tables and player walks in. After that nothing happens. Twice I tried to do this, both times server crashed after like 10 seconds.

Video of proper event: https://www.youtube.com/watch?v=q8B9Bf7ew-Q

**Comment by MrTide** [comment]
This event used to work ok i have tested this 2 month ago but looks like something broke requires attention
i just got stuck in the event, it played out a little bit then 
i didnt crash the server but i had to relaunch the game

**Comment by UltraNix** [comment]
Fixed.
