### ISSUE TITLE
[Minor] Incorrect speech text on Wetlands Ghost Mobs

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1467]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cursed Sailor, Cursed Marine and Captain Halyndor say $R and $C instead of Race and Character Name.

**How to reproduce:**
Pull the mobs, they generally do a line of text on each pull. One example is:

Cursed Marine says: A living $R... soon to be a dead like me. 

**How it should work:**

They should say 

Cursed Marine says: A living **Dwarf**... soon to be a dead like me. 

**Database links:**

https://www.wowhead.com/classic/npc=1157/cursed-sailor

**Comment by MrTide** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/36106057/210079070-d9b476d3-9489-4604-9278-8f4d799b39aa.png)
![image](https://user-images.githubusercontent.com/36106057/210079148-54130524-445f-4f23-ae37-ff1121ed0d0c.png)

**Comment by Afgann** [comment]
fixed
