### ISSUE TITLE
Mobs sometimes won't attack if you pull from range

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1468]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I've seen this occur in a couple of places, one example is the Twilight Convert mobs in Wetlands. If you pull with Avenger's Shield the mobs will just stand there.

I've also seen this occur with the elementals just south of the Whelgar's Retreat flightpath in Wetlands, so this could be a bug with all mobs who prefer to attack from ranged.

**How to reproduce:**
Head to Wetlands, Dun Modr, pull a Twilight Convert using for example Avenger's Shield. The mob will stand there and do nothing and let you hit them.

**How it should work:**
The mob should run to melee range and attack.

**Database links:**
https://www.wowhead.com/npc=94425/twilight-convert

**Comment by Torpis** [comment]
Paleolithic Elemental is the other mob which I found that does the same thing:

https://cata-twinhead.twinstar.cz/?npc=41389

**Comment by MrTide** [comment]
![image](https://user-images.githubusercontent.com/36106057/210078540-e5d2b5c6-f4d4-4d4e-9716-0fc0056d2a5a.png)
they do attack but they take a long delay before doing so this is a known issue with spell casters/rangers and such sadly reported a lot in our other bugtracker 
can confirm this issue, afgaan said its scripting issue.

**Comment by Afgann** [comment]
fixed (creatures that were posted here and some more, i'll try to slowly fix all of them)
