### ISSUE TITLE
[Talent] Level 31 Talent not Awarded

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1470]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The level 31 talent was not avaliable to spend.

**How to reproduce:**
Level to 31 on a Paladin (could be class specific)

You can see on the below that 11 talent points have been used, only 1 is avaliable. My character is level 33 in the screenshot so there should be 2 points avaliable. I noticed that when leveling 31 a talent was not awarded but just assumed I may have spent it - leveling to 33 then caused the bug reported in https://github.com/gamefreedomgit/Maelstrom/issues/1469 so it could be that these two are related.

![Talent Tree](https://user-images.githubusercontent.com/6482585/209840816-9f153b22-df0e-43f3-b7ba-2b429e67cf76.PNG)

**The following resolved the issue:

Visting trainer, paying 10g to Learn Dual Spec, switching specs, then switching back, then spend the talent point**

**How it should work:**
Talent point should be avaliable to spend at level 31

**Database links:**

**Comment by MrTide** [comment]
works fine for me i had the talents did you try a cache delete ? are you using our client ?

**Comment by Torpis** [comment]
Yep using the client, downloaded via the launcher. Didn't think it would be reproducable, possibly a one off issue?

**Comment by Orcmage** [comment]
This happened to me today for the first time at level 37.
-Paladin
-client from launcher
-no issues at earlier levels.
-General chat tab shows level up and the "New Talent Point Available!" message. Yet no talent point is awarded
