### ISSUE TITLE
[Object] [Loot] Sturdy Treasure Chest - empty

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1471]
Similar issue presumably fixed: https://github.com/gamefreedomgit/Maelstrom/issues/1086

So, I have found 3 [Sturdy Treasure Chests](https://www.wowhead.com/object=207484/sturdy-treasure-chest) in Eastern Plaguelands. Each of them was empty. According to wowhead comments every kind of chest should always countain at least gold and blue rarity piece of gear with appropriate ilvl to the zone you find it in. I believe this might be issue with all kinds of chest, not just the sturdy ones.

**Comment by Greywolf59** [comment]
Found one [Silken Treasure Chest](https://www.wowhead.com/object=207513/silken-treasure-chest) in Blasted Lands. Also empty.

**Comment by UltraNix** [comment]
Fixed.
