### ISSUE TITLE
[Quest] [Achievment] Ancient Protectors - undoable, blocking loremaster

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1472]
Quest: [Ancient Protectors](https://www.wowhead.com/quest=27793/ancient-protectors)

Issue: There is no talk option with either [Sentinel](https://www.wowhead.com/npc=46769/the-sentinel) nor [Warden](https://www.wowhead.com/npc=46768/the-warden). This leads to the quest being undoable which in turn leads to Badlands Loremaster Achievment being undoable.

How it should be: After you finish the prequests (The Warden's Game and the Sentinel's Game) and receive the quest you see talk option wih both golems. That activates them, makes them hostile and by killing them you get the quest credit.

Video of how it should look: https://www.youtube.com/watch?v=JnekzGct4Rw

**Comment by MrTide** [comment]
have you done all the requirements ? there are like 20 quests leading up to this quest
you can reach me through discord i can check the requirements on you

**Comment by MrTide** [comment]
Can confirm tested these quests a few month ago but now they are not working
![image](https://user-images.githubusercontent.com/36106057/210082277-f857d294-ce0c-483e-92db-445c5630fe8e.png)

**Comment by Greywolf59** [comment]
Fix confirmed.
