### ISSUE TITLE
Badlands Alliance Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1473]
1. When Dustbelcher ogres should say "Raar! Me smash _human/orc..._" they say "Raar! Me smash $R" Seen it at [Butcher](https://www.wowhead.com/npc=46928/dustbelcher-butcher) and [Mauler](https://www.wowhead.com/npc=2717/dustbelcher-mauler)

2. [Survival of the Fattest](https://www.wowhead.com/quest=27825/survival-of-the-fattest)
- There are only 4 [Dustbelcher Chests](https://www.wowhead.com/object=206499/dustbelcher-chest) spawned. |For the quest (silk), you need 10.
- Wowhead also says that the chest contains 2-4 [Dustbelcher Silk](https://www.wowhead.com/item=62547/dustbelcher-silk) whereas on PTR each chest contains only 1 silk. With 4 chest = 4 silks it means player needs to wait for chest respawn two times to finish the quest.

3. [Moltanus](https://www.wowhead.com/npc=52021/moltanus)
- This guy should be patrolling the Scar but he is standing on one spot.

4. [Barnabus](https://www.wowhead.com/npc=2753/barnabus)
- This silver elite sometimes walks through textures, needs better pathing.

5. [Billy Goat](https://www.wowhead.com/npc=46393/billy-goat)
- These guys often go throught the texture when you nudge them down by [Blaster](https://www.wowhead.com/item=62397/billy-goat-blaster) for quest (or for fun).

6. https://github.com/gamefreedomgit/Maelstrom/issues/1472

7. [The Day that Deathwing Came](https://www.wowhead.com/quest=27713/the-day-that-deathwing-came)
- When you punch [Deathwing](https://www.wowhead.com/npc=46471/deathwing) he does not fall down to the ground
- The original dragon form that comes in the cutscene at the start is still visible, it should disappear. That goes for the [next quest](https://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story) too.
- Video: https://www.youtube.com/watch?v=z4KBN9FVjVg

To be continue when issue 1472 mentioned in number six is fixed.

**Comment by UltraNix** [comment]
Fixed.
