### ISSUE TITLE
[Moved from Discord][Class: Paladin] Summon Warhorse not included in the auto-learn

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1475]
liljon
OP
 — 12/12/2022 17:57
Title. When you hit level 20, you don't automatically learn Warhorse, but you do learn Apprentice Riding. I'm gonna go on a stretch, and without any evidence, but the same issue probably exists for Charger, Dreadsteed and Felsteed.
GaGa — 13/12/2022 05:28
what's the race
liljon
OP
 — 13/12/2022 11:02
human

**Comment by Torpis** [comment]
I can confirm this. Needed to visit trainer to learn.

**Comment by Afgann** [comment]
fixed
