### ISSUE TITLE
[Moved from Discord][Quest: Recruitment][Zone:Tirisfal Glades] (Undead starting quest 4) -  Corpses scripting error

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1476]
might not be that big of an issue but just seems strange to just see the corpses only stand there rather then go on his back.

https://cata-twinhead.twinstar.cz/?quest=26800

![image](https://user-images.githubusercontent.com/121137397/210023579-3eaf2988-2c3b-4ac8-9402-dab95b4aabd6.png)

**Comment by UltraNix** [comment]
Fixed.
