### ISSUE TITLE
[Moved from Discord] Taunt Delay

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1478]
Buuba
OP
 — 16/12/2022 15:50
If you taunt something, it has a delay of one second. Like the ad has a delayed target change.
UltraNix — 19/12/2022 14:37
I observed no delay. Can you give us some example of such delayed mob/add?
Laddad — 19/12/2022 16:50
I experience some delays too, e.g. when using Paladin AOE taunt (righteous defense) directly on mobs on Bastion of Twilight trash

**Comment by UltraNix** [comment]
Fixed.
