### ISSUE TITLE
[Moved from Discord][Zone: Deep Run Tram] - Player spawns facing wrong way

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1480]
Greywolf/Gesh
OP
 — 26/12/2022 19:01
If you use Deeprun Tram portal you pop out on the other side facing the wall, turned left or right, not sure now. This happens at Ironforge portal on both sides. Haven't checked Stormwind side.

**Comment by WhitemaneSylah** [comment]
Confirmed -  Player orientation is incorrect on Ironforge and Stormwind portals to and from the tram

Ironforge side example (existing deeprun tram)
![image](https://user-images.githubusercontent.com/121137397/210084315-119795ca-5474-4cb0-b865-9ce1062f4ba4.png)
Entering deeprun Tram
![image](https://user-images.githubusercontent.com/121137397/210084372-c85ab9dc-3111-44aa-92b2-3ecb0f660ac7.png)

Exisiting Deeprun tram Stormwind
![image](https://user-images.githubusercontent.com/121137397/210084504-cf72b9ed-2635-4d1b-b8b0-9fa25f56ca53.png)

Entering
![image](https://user-images.githubusercontent.com/121137397/210084536-18e192ae-26fa-478c-ab52-ca2401e9b8bb.png)

**Comment by UltraNix** [comment]
Fixed.
