### ISSUE TITLE
[Moved from Discord][Pet ability: Bad Manner] Not function correctly within [Smoke Bomb]

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1481]
Jimmy17
OP
 — 27/12/2022 12:01
if a rogue sitting inside smoke bomb and i use [Bad manner], my pet should run inside smoke bomb and bad manner the rouge. Smoke bomb acts as  a pillar. so even if target is out of LoS pet should still chase

**Comment by WhitemaneSylah** [comment]
Second report added 
When I use bad manner and the pet's sprint, it comes back to me, I have to press the key again a 2nd time for it to go stun the target.

https://youtu.be/zgulGvy8mHk 

Proper function - Sprint shouldn't stop pet attack functions

**Comment by UltraNix** [comment]
Fixed.
