### ISSUE TITLE
[Moved from Discord] Hunters mark being overwritten by Marked for Death 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1482]
https://www.youtube.com/watch?v=nGiivnU5Ghc

Correct function -  

If target has Hunters mark = Yes. THEN do nothing
If target has hunters mark = No. THEN apply marked for death 

https://cata-twinhead.twinstar.cz/?spell=31615

https://cata-twinhead.twinstar.cz/?spell=88691

**Comment by Afgann** [comment]
fixed
