### ISSUE TITLE
Alliance/Dwarf - Booty Bay flight path not known

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1483]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Booty Bay flight path not known

**How to reproduce:**
Create a new Dwarf, try to fly to Booty Bay - the flight path isn't known.

**How it should work:**
All flight-paths should be known.

**Database links:**

**Comment by WhitemaneSylah** [comment]
Confirmed,  This is alliance only

![image](https://user-images.githubusercontent.com/121137397/210073061-4d3e42d0-d248-4c56-be5b-cb7a93c52c4c.png)

![image](https://user-images.githubusercontent.com/121137397/210073172-118f0b8e-33cf-46a9-b883-138e5f8debba.png)

**Comment by shinzo69** [comment]
Yup can confirm, i had this on gnome/draenai too.

**Comment by Afgann** [comment]
fixed
