### ISSUE TITLE
[Moved from Discord] Hunter Pet "more powerful spell active" - CC's cannot be overlapped on pets

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1484]
"A mower powerful spell is already active'' works good on players now.
But still doesn't work on pets. it should be the same for pets.
Sylah — Today at 01:03
Hey Jimmy!  Can you give a bit more info please?  I'll move this to BT once more info is provided,  What kind of spells are we speaking of?  Different buffs etc?
Jimmy17
OP
 — Today at 03:57
Spammable CC such as poly , entangling roots etc..

**Comment by Afgann** [comment]
fixed
