### ISSUE TITLE
Alliance - Andorhal Flight Path not Known

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Andhorhal Flight Path not known to Dwarf Paladin

**How to reproduce:**
Create Dwarf, try to fly there.

**How it should work:**
Should be able to

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=46006

**Comment by Torpis** [comment]
In fact, I'm not sure this is even right. Upon arrival in Andorhal I was able to see the flightmaster - however after doing some of the quests she disappeared. I didn't note down what quests I had done I but had just finished https://cata-twinhead.twinstar.cz/?quest=27164

**Comment by WhitemaneSylah** [comment]
Confirmed bug for alliance,  Flightpath is not added to auto learn,  Also NPC is in combat with invisble mobs (can be seen with GM mode on)
![image](https://user-images.githubusercontent.com/121137397/210085774-4570d473-7c11-4436-a6d5-d78731eb9710.png)

![image](https://user-images.githubusercontent.com/121137397/210085953-1d139b26-8838-42a6-bfcd-5914e7e69bfa.png)

**Comment by Torpis** [comment]
There is quite a lot of invisible and dead combat going on around there but it’s been reported by Grey as part of his WPL write up

**Comment by Afgann** [comment]
fixed
