### ISSUE TITLE
Paladin - Summon Charger not Taught 

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1486]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon reaching level 40, summon charger isn't automatically taught to the player.

**How to reproduce:**
Ding level 40 on a Paladin.

**How it should work:**
All spells should be automatically learned, this one isn't

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=23214

**Comment by WhitemaneSylah** [comment]
Tied into #1475

**Comment by UltraNix** [comment]
Already fixed.
