### ISSUE TITLE
Paladin - Plate Proficiency Not Learned

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1487]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon reaching level 40, plate mail isn't automatically learned.

**How to reproduce:**
Ding 40 on a Paladin

**How it should work:**
Should be automatically learned - currently have to visit trainer to learn.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=750

**Comment by WhitemaneSylah** [comment]
Confirmed to affect warrior too

**Comment by UltraNix** [comment]
Already fixed.

**Comment by UltraNix** [comment]
Already fixed.
