### ISSUE TITLE
[Minor] Zen'kiki still following after completing all quests

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Zen'kiki is following me still when I have no relevant quests in my log.

**How to reproduce:**
Hand in all the WPL Zen'kiki quests (last one Zen'Kiki and the Cultists) I then headed into EPL and briefly crossed into WPL, this caused Zen'kiki to come flying accross the map and now is following me and continues to help me kill stuff.

**How it should work:**
Zen'kiki should no longer appear if the quests are not in your quest log.

Logging out and back in resolves this so this is very minor, just means someone might get a bit of extra help with EPL quests.

**Database links:**

![Zen'Kiki Following](https://user-images.githubusercontent.com/6482585/210091275-771b46ac-a6ab-4241-a014-e442b4d242f5.PNG)

Likely linked to this spell not dropping off:

https://cata-twinhead.twinstar.cz/?spell=83456#used-by-npc

This is the last quest in the chain:

https://cata-twinhead.twinstar.cz/?quest=26955

**Comment by UltraNix** [comment]
Already fixed.
