### ISSUE TITLE
[Quest] Burning Vengeance - both versions avaialble if condions met

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1493]
Quest version 1: https://www.wowhead.com/quest=28416/burning-vengeance
Quest version 2: https://www.wowhead.com/quest=28174/burning-vengeance

So, the issue is that always the only one of those two version should be available to player.
If the player done Redrdige Mountain storyline, the version 1 should be available. If he haven't, then only version 2 should be available.

Issue: I have done the Redridge storyline. When I came to [the quest giver](https://www.wowhead.com/npc=47811/john-j-keeshan) I had breadcrumb quest [Hero's Call: Burning Steppes](https://www.wowhead.com/quest=28666/heros-call-burning-steppes) active. Before I have handed Hero's Call I had already version 1 available. When I handed in Hero's Call, I had also version two available. I was able to grab both of the quests and finish them and hand them in at the same time. I have grabbed version 2 and then version 1.

**Comment by UltraNix** [comment]
Fixed.
