### ISSUE TITLE
[NPC]Gorzeeki Wildeyes - trade option for non-warlocks

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1494]
This guy, [Gorzeeki Wildeyes](https://www.wowhead.com/npc=14437/gorzeeki-wildeyes) offers trade option with warlock quest items even to non-warlock classes.
I highly doubt that should be the case. Not sure if it should be avaialble even to warlock post-cata if they havent done the quests already (based on wowhead comments from later patches)

**Comment by Afgann** [comment]
fixed
