### ISSUE TITLE
[Quest] Chiselgrip, the Heart of the Steppes - missing kill credits and prequest demand

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1495]
Problem 1: Kill Credits
Video how it should be: https://www.youtube.com/watch?v=-m9ThhyxCBI
When doing [this quest](https://www.wowhead.com/quest=28184/chiselgrip-the-heart-of-the-steppes) it should count all the enemies, trolls, ogres, orcs (click on the arrow on wowhead at "Blackrock troop slain" for full list).

Problem is that orc npcs do not count toward quest kill credit. NPCs not being counted toward the quest completion:
[Blackrock Slayer](https://www.wowhead.com/npc=7027/blackrock-slayer)
[Blackrock Sorcerer](https://www.wowhead.com/npc=7026/blackrock-sorcerer)
untested (out of the loical quest path):
[Blackrock Soldier](https://www.wowhead.com/npc=7025/blackrock-soldier)
[Blackrock Sergeant](https://www.wowhead.com/npc=48201/blackrock-sergeant)

Problem 2: Missing mandatory Prerequisite
This quest is available when you finish [Return to Keeshan](https://www.wowhead.com/quest=28183/return-to-keeshan).
It is missing condition of [Done Nothing Wrong](https://www.wowhead.com/quest=28172/done-nothing-wrong) also being completed. Player should need both quest done to move forward and get Chiselgrip quest available.

Problem 3: [Done Nothing Wrong](https://www.wowhead.com/quest=28172/done-nothing-wrong) is not available unless the player grabs and finish the quest [Mounton Flamestar](https://www.wowhead.com/quest=28514/mouton-flamestar). Wowhead comment from 4.0.3 says that Mounton Flamestar is OPTIONAL breadcrumb quest so Done Nothing Wrong should be available no matter if player done Mounton Flamestar or not.

**Comment by UltraNix** [comment]
Fixed.
