### ISSUE TITLE
[Object] Flamefly and Blackrock Boots - interactable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1496]
[Flamefly](https://www.wowhead.com/npc=48671/flamefly) is interactable and lootable for [Flamefly](https://www.wowhead.com/item=64409/flamefly) even without having the quest, both before [the quest](https://www.wowhead.com/quest=28415/seven-yup) and after the quest.

[Blackrock Boots](https://www.wowhead.com/object=206977/blackrock-boots) are also interactable without having [the quest](https://www.wowhead.com/quest=28245/grunt-work) connected to them.

**Comment by UltraNix** [comment]
Fixed.
