### ISSUE TITLE
[NPC] Blackrock Sergeants - missing wolves

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1497]
[Blackrock Sergeants](https://www.wowhead.com/npc=48201/blackrock-sergeant) should be mounted on wolves. They are walking normally on foot at the moment. No idea what the ID of their wolf mount should be.
Also they keep walking around if you use [Cudgel](https://www.wowhead.com/item=63390/blackrock-cudgel-of-discipline) on them when doing [Abuse of Power](https://www.wowhead.com/quest=28279/abuse-of-power). They should stop walking and make /point gesture.
Video how it should be: https://www.youtube.com/watch?v=BqPPsYEhQas

**Comment by UltraNix** [comment]
Fixed.
