### ISSUE TITLE
[Quest] [NPC] Golem training - missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1498]
[Golem Training](https://www.wowhead.com/quest=28227/golem-training)
[The golems](https://www.wowhead.com/npc=48037/chiseled-golem) are not using their abilities [Heave](https://www.wowhead.com/spell=91314/heave) (I think) and [Flame Blast](https://www.wowhead.com/spell=91313/flame-blast) (definitely).
Points of reference: https://www.youtube.com/watch?v=Zz2tsPyDFOs; https://www.wowhead.com/quest=28227/golem-training#comments:id=1188919
They also despawn kinda really really fast after you get quest credit.

**Comment by Afgann** [comment]
fixed
