### ISSUE TITLE
[Quest] Locked and Loaded - wrongly acquired

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1499]
[Locked and Loaded](https://www.wowhead.com/quest=28327/locked-and-loaded) should be offered by the comm.
I got mine offered by [Xi'lun](https://www.wowhead.com/npc=48312/high-warlock-xilun). I done [his quest](https://www.wowhead.com/quest=28319/a-delivery-for-xilun) as last of the three prerequisites.

**Comment by UltraNix** [comment]
Already fixed.
