### ISSUE TITLE
[Quest] Assault on Dreadmaul Rock - dismount from drake

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1500]
Quest: [Assault on Dreadmaul Rock](https://www.wowhead.com/quest=28320/assault-on-dreadmaul-rock)
Horde version video of dismount, timestamp 5:20: https://www.youtube.com/watch?v=jOFQoVgNqHY

As you see in the video when the player finishes the kills he flies into the faction camp to hand it in. Player dismounts, gets parachute and goes hands it in.

What happened to me as Alliance player was: I flew to the Alli camp, dismounted → got telepored back to where you spawn on the drake → slowfalled down. I noticed that I was not in the quest phase, there were ordinary mobs. I could not interact with anything "Invalid Target", couldn't mount up "Can't do that while moving". I legged it back to the camp, mobs weren't attaking me on my way. Chat option with NPCs in Alli camp did not open soI could not hand in the quest.
So I logged out and logged back in → I appeared at the initial spot where you spawn at the drake once again, this time falling to my death, this time in proper quest phase. Ressurected and mounted up normally this time and went to hand in the quest successfully.

**Comment by UltraNix** [comment]
Fixed.
