### ISSUE TITLE
[Achievement] Explore Southern Barrens can't be completed

### ISSUE THREAD

**Issue by Pocokk** [gamefreedomgit/Maelstrom#1502]
**Description:**
Razorfen Kraul exploration point is not triggered, even if you stand in the correct spot 

**How to reproduce:**
Go to Southern Barrens 40.9, 94.5 and you will see it doesn't work.

**How it should work:**
Once you reach that area, it should pop.

**Database links:**

https://www.wowhead.com/achievement=4996/explore-southern-barrens

**Comment by UltraNix** [comment]
Fixed.
