### ISSUE TITLE
[Quest] A Blight Upon The Lands NPC hits too hard for cloth users

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1504]
Reported by Roxorloops 

Quest https://cata-twinhead.twinstar.cz/?quest=28237 - Scripting error ,  NPC Warden Stilltide damage numbers need looked at,  Hitting over 300 on cloth users,  should ideally only hit 100 https://cata-twinhead.twinstar.cz/?npc=48103

Roxorloops also stated that Apoth Lyndon did not cast shields during this quest whereas he should https://cata-twinhead.twinstar.cz/?npc=47900

Tested by GM Sylah on character Naesjnaesj

**Comment by Afgann** [comment]
fixed
