### ISSUE TITLE
[Death Knight ZONE][Quest][Bloody Breakout]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1505]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Related issue:
https://github.com/gamefreedomgit/Maelstrom/issues/835 (marked as fixed)

**Description:**
This quest is not working.
Upon accepting the quest, Koltira does a little roleplay walk to the outside of the Scarlet Hold, as if the quest is completed. However the attack and Valroth do not appear before he makes his walk.
The quest also doesn't give complete status, which is normal since the fight never happens.

**How to reproduce:**
Accept the quest and observe

**How it should work:**
u should defend koltira until High Inquisitor Valroth appear , After killing him u should pickup his head
https://www.youtube.com/watch?v=87s-K_3-tpM

**Database links:**
https://www.wowhead.com/npc=28912/koltira-deathweaver
https://www.wowhead.com/quest=12727/bloody-breakout
https://www.wowhead.com/item=39510/valroths-head
https://www.wowhead.com/npc=29001/high-inquisitor-valroth

**Comment by WhitemaneSylah** [comment]
Confirmed

**Comment by MrTide** [comment]
Same issue duplicate
https://github.com/gamefreedomgit/Maelstrom/issues/1183
