### ISSUE TITLE
[Death Knight ZONE][Quest][A Special Surprise]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1506]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

RP heavy quest where you eventually kill Kug Ironjaw

**How to reproduce:**
Accep the quest, go to Kug and watch the rp
He will die without being touched rendering the quest incomplete.
It seems like he dies on a timer

As witnessed by Sylah

**How it should work:**
https://www.youtube.com/watch?v=9lzb-Gz5bD4

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=12739

**Comment by WhitemaneSylah** [comment]
Quest cannot be completed if NPC dies on timer,  I had to complete this for Orcmage

**Comment by Orcmage** [comment]
ADDENDUM:

Upon turning in this quest, the follow up "A Sort of Homecoming" does not get offered.
?quest=12751
