### ISSUE TITLE
[Death Knight ZONE][Quest][A sort of Home coming]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1507]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon turning in this quest A special Surpise, the follow up "A Sort of Homecoming" does not get offered.

**How to reproduce:**
Complete A Special Surprise and turn it in.

**How it should work:**
Next quest is offered upon completion. (Follow up)

**Database links:**
?quest=12739
?quest=12751

**Comment by WhitemaneSylah** [comment]
Quest had to be added by GM command

**Comment by UltraNix** [comment]
Fixed.
