### ISSUE TITLE
[Death Knight][Ability][Death Gate] auto learn

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1512]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You auto learn Death Gate while leveling, instead of after completing The Light of Dawn

**How to reproduce:**
Just level up to 60

**How it should work:**
You learn it as a questreward from The Light of Dawn

**Database links:**
/?quest=12801
/?spell=50977

**Comment by WhitemaneSylah** [comment]
Potential to cause scripting errors

**Comment by Afgann** [comment]
fixed
