### ISSUE TITLE
[Death Knight ZONE][Quest][The Light of Dawn]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1513]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
*The Might of Mograine buff only applies when the mobs start combat instead of when the event begins.
*Highlord Darion Mograine has small pathing problems throughout this event.
*After combat, he is looking the wrong way while kneeling (see screenhot below)
*During his dialog with The Lich King, he very quickly runs away and towards him a few times, as if he is rubberbanding
*When the quest is complete and ready to turn in, Darion double spawn for about 3 seconds before the first iteration despawns.
*If you don't turn in the quest, Darion despawns after a little while
*After turnin in the quest, the combatlog shows you get +3 talent points, however they do not appear in the Talent tree, so you never actually get them. 

https://imgur.com/a/UsgoBmq

**How to reproduce:**

Accept the quest and let the event unfold.

**How it should work:**

https://www.youtube.com/watch?v=jHEcFOQRrC4

**Database links:**
/?quest=12801
/?spell=53642

**Comment by WhitemaneSylah** [comment]
Darion respawns at the start so quest can be handed in -  But should still function as shown above

**Comment by UltraNix** [comment]
Fixed.
