### ISSUE TITLE
[Moved from Discord] Ability to fly in Silvermoon

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1515]
Fels
OP
 — Today at 16:42
The following mounts I've tested so far allow flight in Silvermoon:

Corrupted Hippogryph
Feldrake
Flameward Hippogryph
Spectral Windrider
Swift Purple Wind Rider (I assume it also affects other Windriders)
Tyrael's Charger

Most of these are TCG but in the case of the Hippogryphs and Windriders, it seems to affect the entire mount "species". 

- GM Sylah - Flying is not implemented in Silvermoon on cataclysm realms

**Comment by UltraNix** [comment]
Fixed.
