### ISSUE TITLE
[Moved from Discord] old raid scripting

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1516]
(T)Remediation
OP
 — Today at 18:53
Sylah took me to Molten Core before as I was curious on scripting etc, all the trash is fine but the bosses are set to Cataclysm levels - appearing as ?? mobs to 85 characters. 

Whilst this is not a urgent bug, I would hope this would be fixed in order to allow players on release onwards to farm vanity items from raids for collections and memories.

Thank you - Precision.

**Comment by Afgann** [comment]
https://youtu.be/SbCi4vMcW3Y?t=117
![image](https://user-images.githubusercontent.com/19671319/210194102-997f95ab-b8db-4576-9499-eca2cb7bad56.png)
https://youtu.be/1F3DNajxIC0?t=113
![image](https://user-images.githubusercontent.com/19671319/210194119-9ded4646-03da-4254-ad56-520330e16e0b.png)
