### ISSUE TITLE
[Dustwallow Marsh][Quest/Pathing][Questioning Reethe] Ogron airwalks during this event

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After starting the quest [Questioning Reethe], Ogron starts his dialog and walks towards Reethe. When he gets to the first river, he jumps 10-15 feet into the air and airjumps for a while until he cleared the river and carries on his pathing correctly from there.

**How to reproduce:**
Start the quest event

**How it should work:**
He should just walk through the water

**Database links:**
/?npc=4983#
/?quest=27261

**Comment by UltraNix** [comment]
Fixed.
