### ISSUE TITLE
[NPC][Text] S.A.F.E. Operative

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1521]
NPCs at the beginning of the Gnome Zone (SAFE Operatives) should occasionally say these following lines:
![image](https://user-images.githubusercontent.com/67768754/210158540-7b1f606d-4be6-431c-a11e-da12271bae64.png)

(Don't make this spammy, have them only do it every once in a while)

**Comment by UltraNix** [comment]
Fixed.
