### ISSUE TITLE
[NPC] Rescued Survivor

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1524]
Rescued Survivors in the Loading Room should exit the portal and likely go over to where the rest of the Rescued Survivors are, see video for reference: https://youtu.be/NiB0iAd6LVw?t=507

Currently there are a ton of NPCs all stacked on top of each other doing nothing:
![image](https://user-images.githubusercontent.com/67768754/210158672-a79016cf-0766-43aa-930a-5b4cf0655b3d.png)
This will likely cause infinite NPC spawn and bring down server load over time

**Comment by UltraNix** [comment]
Fixed.
