### ISSUE TITLE
[NPC] Torben Zapblast - Bad Location

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1525]
![image](https://user-images.githubusercontent.com/67768754/210158722-e0ef32e5-009b-459d-bb2b-4604ee2c613a.png)
Currently inside gameobject

Should be slightly in front of it: 
![image](https://user-images.githubusercontent.com/67768754/210158727-bff23aaf-3b55-4df3-90b3-6a8557a68113.png)

**Comment by UltraNix** [comment]
Fixed.
