### ISSUE TITLE
[NPC] Remove NPC - S.A.F.E. Operative

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1526]
After teleporting for the quest "To the Surface", there is an NPC on the teleport pad: 
![image](https://user-images.githubusercontent.com/67768754/210158748-a017eccb-d25b-4721-a594-f7d40d5a9171.png)

This NPC does not exist in video references: 
![image](https://user-images.githubusercontent.com/67768754/210158751-6d3863d9-f85e-4a8d-8c0d-244241ada74b.png)

Please remove

**Comment by UltraNix** [comment]
Fixed.
