### ISSUE TITLE
[NPC][Animation] Gnomeregan Trainee

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1527]
See Video Reference: https://youtu.be/NiB0iAd6LVw?t=613
There should be a few Gnomeregan Trainee NPCs fighting Training Dummies, the NPC attacks and the Training Dummy does a little spin. Currently there is only one Gnomeregan Trainee, and he is not doing anything: 
![image](https://user-images.githubusercontent.com/67768754/210158781-348c3a1c-e8de-427d-a228-b3e66e2ffa2e.png)

**Comment by UltraNix** [comment]
Fixed.
