### ISSUE TITLE
[NPC] NPCs Missing? New Tinkertown

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1528]
![image](https://user-images.githubusercontent.com/67768754/210158795-d3f21e55-33b8-47ac-80ab-b8dba0c7a662.png)

It appears Elly Sharpedge and Carson Crazybread are missing from this location:
![image](https://user-images.githubusercontent.com/67768754/210158803-36cffdc9-f2ef-4c48-9c83-a9e97b0dea3e.png)

**Comment by UltraNix** [comment]
Fixed.
