### ISSUE TITLE
[Quest][Text] The Fight Continues - Minor Typos

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1530]
![image](https://user-images.githubusercontent.com/67768754/210158913-1ea7c540-a630-400b-82ac-d69458b20ad2.png)
Image of High Tinker Mekkatorque says "Handfull" it should be Handful"

High Tinker Mekkatorque says "harras" it should be "harass" 
![image](https://user-images.githubusercontent.com/67768754/210158930-0133ddef-c497-4278-8b97-aa043d2c2792.png)

**Comment by UltraNix** [comment]
Fixed.
