### ISSUE TITLE
[Quest] A Job for the Multi-Bot

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1531]
After finishing Scrounging for Spare Parts, Engineer Grindspark begins a small animated scene, video reference: https://youtu.be/oBn0B0PcaQw?t=224

The gameobject of the broken machine is also missing. He should walk over to the part, do the animation while doing the dialogue, and after he says "At last, it's finished." then the Companion GS-9x Multi-Bot should spawn for the player.

Currently, you accept the quest, Engineer Grindspark says nothing, your companion spawns, and it creates an additional gameobject that is not interactable
![image](https://user-images.githubusercontent.com/67768754/210158998-65406b72-2db8-4cad-919d-3ba78af55055.png)

**Comment by UltraNix** [comment]
Fixed.
