### ISSUE TITLE
[NPC] Wounded Infantry

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1532]
The Wounded Infantry should have some aura surrounding them like a bubble: 
![image](https://user-images.githubusercontent.com/67768754/210159018-5aa9eeff-0e4e-4188-9a0a-1ae70f17d258.png)
The Physician's Assistant's should also have an animation going.
(video reference: https://youtu.be/oBn0B0PcaQw?t=262)

Currently, no aura, Physician's Assistant's do nothing 
![image](https://user-images.githubusercontent.com/67768754/210159028-94878bf9-9aab-4dc2-8280-596b622a062c.png)

**Comment by UltraNix** [comment]
Fixed.
