### ISSUE TITLE
[NPC] Gnome Recruit

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1533]
Gnomeregan Recruit's should be shooting with their little guns at the Living Contamination NPCs, video reference here: https://youtu.be/oBn0B0PcaQw?t=308
![image](https://user-images.githubusercontent.com/67768754/210159070-e61ab4a6-d882-42da-9503-6425cfae5a70.png)

Currently, they attack with swords
![image](https://user-images.githubusercontent.com/67768754/210159072-63e701c1-078c-4c5c-9bec-4309b34d61da.png)

**Comment by UltraNix** [comment]
Fixed.
