### ISSUE TITLE
[NPC] Gnomeregan Recruit - Weird positioning

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1534]
![image](https://user-images.githubusercontent.com/67768754/210159153-3da37c6c-f241-49b2-a0cc-c32dc40b4cd4.png)

Not sure what this guy is up to, but he probably shouldn't be inside that gameobject

**Comment by Loken-coolguy** [comment]
Update, found a video reference of him pushing that cart along: https://youtu.be/phrCteGLtHQ?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=107

**Comment by Loken-coolguy** [comment]
There are actually a lot of these with broken animations and waypoints, recommend looking through them all: 
![image](https://user-images.githubusercontent.com/67768754/210160243-06a2ec69-4d3b-445c-a76b-cc8a09828d00.png)

**Comment by UltraNix** [comment]
Fixed.
