### ISSUE TITLE
[NPC] Living Contamination - Bad Waypoint

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1535]
![image](https://user-images.githubusercontent.com/67768754/210159209-0734d045-a6d3-4e1b-8731-ffaf1cbd2b85.png)
Shouldn't be hanging out up in a tree, also not patrolling, likely broken waypoint

**Comment by UltraNix** [comment]
All of these mobs wanders, as it should.
