### ISSUE TITLE
Bad Tooltip? 

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1536]
Unsure if this is repeatable, when completing "A Job for the Multi-Bot" quest, I received the tooltip that I am engaging in Player vs. Player combat: 
![image](https://user-images.githubusercontent.com/67768754/210159241-acb6293e-1b4d-4783-8c99-3159216acf4a.png)

**Comment by UltraNix** [comment]
Cannot reproduce it.
