### ISSUE TITLE
[Quest][Animation][Text] What's Left Behind - Missing Scene

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1537]
Video Reference: https://youtu.be/NpigGE251pY?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=169
(You can see in the video his party member completed the quest, activating the scene) 
After completing What's Left Behind, there should be a scene of a gnome recovering from radiation, he walks away after one gnome says not to, then explodes and goes flying away, pretty funny scene. Currently nothing happens

**Comment by UltraNix** [comment]
Fixed.
