### ISSUE TITLE
[NPC] Missing NPCs - Rockjaws

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1538]
As seen in this video reference: 
![image](https://user-images.githubusercontent.com/67768754/210159384-bc75418d-0dad-44f7-ad80-375f681a1c7e.png)
there should be Rockjaw NPCs in the small village of Frostmane Hold: https://youtu.be/NpigGE251pY?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=428

Currently it is completely empty 
![image](https://user-images.githubusercontent.com/67768754/210159395-b888f005-a7db-4264-9a1b-8a8c52121552.png)

**Comment by Loken-coolguy** [comment]
The cave is also completely empty of Rockjaws and should be filled with them, as seen here: https://youtu.be/NpigGE251pY?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=505

**Comment by UltraNix** [comment]
Fixed.
