### ISSUE TITLE
[Quest][NPC] Missing in Action - Captured Demolitionists

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1539]
When you free a Captured Demolitionist from their cage, they should run out and then despawn. Currently, they despawn inside the cage. 

Video reference: https://youtu.be/NpigGE251pY?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=442

**Comment by UltraNix** [comment]
Fixed.
