### ISSUE TITLE
[NPC] Gnomeregan Infantry & Rocket Defense Turret

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1543]
Gnomeregan Infantry should be mounted to the Rocket Defense Turret's, like so:
![image](https://user-images.githubusercontent.com/67768754/210159786-ea05ca55-f2cf-42a6-a410-4d956cff69b6.png)

Currently they are sitting inside the vehicle and not on it:
![image](https://user-images.githubusercontent.com/67768754/210159792-5377872e-453a-4efd-a304-55731aa9d507.png)

**Comment by UltraNix** [comment]
Fixed.
