### ISSUE TITLE
[NPC][Gameobject] Crushcog Battle Suit

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1544]
Replace these GameObjects: 
![image](https://user-images.githubusercontent.com/67768754/210159862-78ece30b-d169-4941-825c-2dc0349f907e.png)

With GameObjects that are dead like this one: 
![image](https://user-images.githubusercontent.com/67768754/210159868-64293899-4cc3-4b9d-86cb-878d6be091ac.png)

**Comment by UltraNix** [comment]
Fixed.
