### ISSUE TITLE
[GameObject] Brewnall Village - Missing Fire

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1545]
There should be a fire here: 
![image](https://user-images.githubusercontent.com/67768754/210159913-4422c78f-94ae-4e74-856b-0f13eed28fa1.png)

Currently there isn't one: 
![image](https://user-images.githubusercontent.com/67768754/210159916-e10528db-9d1e-4055-adb6-6c6413b2c4fd.png)

**Comment by UltraNix** [comment]
Fixed.
