### ISSUE TITLE
[Quest][NPC] Paint it Black - Crushcog Sentry Bot

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1546]
When you use Paintinator on the Crushcog Sentry Bots, please give it 5 seconds after the animation ends for it to despawn. 

Also the Text for the NPCs is incorrect:
![image](https://user-images.githubusercontent.com/67768754/210159965-31fb53d5-00e7-4c1d-bdfd-34da51c3cdd6.png)

It should be "Optical sensor malfunction detected! Shutting down...."

**Comment by UltraNix** [comment]
Fixed.
