### ISSUE TITLE
[NPC][GameObject] Iceflow Lake - Missing GameObjects, NPCs

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1547]
![image](https://user-images.githubusercontent.com/67768754/210160046-939dd3b8-dd7a-42cb-b832-bcd9f51177ed.png)
Please add 2 Gnomeregan Infantry to the left with their battle standards.
Please add 2 Dun Morogh Mountaineers to the right with their battle standards. Please put Mountaineer Stonegrind on a Ram mount.

Quest Down with Crushcog!
https://youtu.be/NCL47JYVScA?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=271
This event is completely broken currently. All enemies despawn except these two: 
![image](https://user-images.githubusercontent.com/67768754/210160098-abc10b26-3912-4c1e-b0f9-00d788d4ffca.png)

Mekkatorque Ray does not work at all, leaving you to have to kill a 132k HP enemy at level 7-8.

**Comment by UltraNix** [comment]
Fixed.
