### ISSUE TITLE
[Quest] On to Kharanos

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1548]
![image](https://user-images.githubusercontent.com/67768754/210160166-494b9ebc-e965-4d0a-8f7a-03b89e156e63.png)

Accepting On to Kharanos should begin a quick Quest Event, like so: 
![image](https://user-images.githubusercontent.com/67768754/210160172-4ba042ca-5c2f-460c-8eec-db18b4aa74ba.png)
https://youtu.be/NCL47JYVScA?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=422

Currently, it does nothing

**Comment by UltraNix** [comment]
Fixed.
