### ISSUE TITLE
[NPC] Gibblewilt

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1549]
Appears broken: 
![image](https://user-images.githubusercontent.com/67768754/210160221-529d0fb2-a10a-4b9b-9a60-d11a0bcdfcb6.png)

He did a text message and walked around a bit after being attacked, but never attacked back. Wowhead says he should be casting Fireball.

**Comment by UltraNix** [comment]
Fixed.
