### ISSUE TITLE
[Moved from Discord][Quest][Worgen Starting area] "By the skin of his teeth" bugged

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1550]
Ædrian
OP
 — Today at 13:36
https://www.wowhead.com/quest=14154/by-the-skin-of-his-teeth

The spawn rate of huargens is too high, the damage too... even crowley dies in the fight
Image
Wowhead
[By the Skin of His Teeth](https://www.wowhead.com/quest=14154/by-the-skin-of-his-teeth)
Hold back the worgen atop the Gilneas City Prison for 2 minutes. A level 1 Gilneas City Quest. +250 reputation with Gilneas. Added in World of Warcraft: Cataclysm.
By the Skin of His Teeth
Ædrian
OP
 — Today at 13:38
And the heal he should give to us doesn't work properly
Torpis — Today at 14:39
I’ve had this quest do this to me once. I then tried it again and stood right next to Crowley and it worked okay. Otherwise I can confirm this fight does seem to be bugged

**Comment by Torpis** [comment]
I actually raised a ticket for this but thought it worked okay on retry:

https://github.com/gamefreedomgit/Maelstrom/issues/1444

gives some more info on how the quest should work on that ticket.

**Comment by WhitemaneSylah** [comment]
[It's still broken (https://www.youtube.com/watch?v=89gjJDGd6dI) Too many creatures spawn

**Comment by Afgann** [comment]
fixed
