### ISSUE TITLE
[Moved from Discord] "From the Shadows" hidden units not hidden

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1552]
Mistake
OP
 — Today at 20:45
Bloodfang Lurkers are supposed to be hidden unless you get close to them, in the current version they are all unstealthed.
https://www.youtube.com/watch?v=eFa9YVOMF04
Image
[YouTube](https://www.youtube.com/)
[Roly _](https://www.youtube.com/channel/UC94vzsQADG0vC14FclTZ7Og)
[Wow Quest : From the Shadows](https://www.youtube.com/watch?v=eFa9YVOMF04)
Image

**Comment by Afgann** [comment]
fixed
