### ISSUE TITLE
[Moved from Discord] Sacrifices Quest mobs not de-aggro'ing

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1553]
https://cata-twinhead.twinstar.cz/?quest=14212

Mistake
OP
 — Today at 20:56
After you reach the destination, the Worgens are supposed to de-aggro, but doesn't.

https://www.youtube.com/watch?v=lBDgI0Wd7L8

**Comment by UltraNix** [comment]
Fixed.
