### ISSUE TITLE
[Moved from Discord] [Quest] "You Can't Take 'Em Alone" barrels not highlighted 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1554]
Barrels for the Abominations are supposed to glitter and glow, making it easier for them to be spotted.
![image](https://user-images.githubusercontent.com/121137397/210184800-ba311d73-d0a5-4396-b51d-b2fe4e533a59.png)
https://cata-twinhead.twinstar.cz/?quest=14348

**Comment by UltraNix** [comment]
Fixed.
