### ISSUE TITLE
[Moved from Discord] Two By Sea - killing NPC respawns instantly and cannot enter catapult

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1555]
Mistake
OP
 — Today at 21:24
You're supposed to kill a Forsaken Machinist and enter his catapult and shoot  yourself onto one of the two ships. However, when killing the Machinist, you're unable to enter the Catapult, and the Forsaken instantly respawns.

https://cata-twinhead.twinstar.cz/?quest=14382

**Comment by UltraNix** [comment]
Tested - works okay.
