### ISSUE TITLE
[NPC] Northshire Valley - Stormwind Infantry vs Blackrock Battle Worg

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1556]
![image](https://user-images.githubusercontent.com/67768754/210184977-d94a4add-f2e7-4496-aea2-dd17bffc5191.png)

These are fighting all over the place, spamming their animations and sounds (very very many sounds), not actually attacking each other. Maybe make these NPCs actually fight each other and die? Or at least lower the frequency of animations + sounds, it is extremely spammy

**Comment by UltraNix** [comment]
Fixed.
