### ISSUE TITLE
[NPC][Pathing] Stormwind Royal Guard

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1557]
The Stormwind Royal Guards that patrol Elwynn Forest need their pathing fixed, they should probably be following the pathway

They are also carrying a Sword and Battle Standard in the same hand

They also probably shouldn't attack the Cutpurses by the path, they continuously dismount and all rush to them, then go back to their pathing, looks clunky

**Comment by UltraNix** [comment]
Fixed.
