### ISSUE TITLE
[Moved from Discord] Gasping for Breath NPC bug - NPC does not despawn when "saved"

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1558]
Mistake
OP
 — Today at 21:52
https://cata-twinhead.twinstar.cz/?quest=14395

Drowning Watchmen do not disappear after being saved, and becomes unclickable.
![image](https://user-images.githubusercontent.com/121137397/210185823-60ab9998-16b4-416f-9dc2-e9ccf6b24892.png)

**Comment by UltraNix** [comment]
Fixed.
