### ISSUE TITLE
Quest: Slowing the inevitable

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#1559]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In this quest you have a bat that can kill literally anything even yourself. (Yes that means you can literally kill people questing around there)

**How to reproduce:**
Mount the bat with the quest Slowing the inevitable

**How it should work:**
https://www.youtube.com/watch?v=hwKPQWK5-Lw&ab_channel=WCQuests

**Database links:**
https://www.wowhead.com/quest=24920/slowing-the-inevitable

**Comment by WhitemaneSylah** [comment]
Confirmed you can kill players with this too

**Comment by Afgann** [comment]
fixed
