### ISSUE TITLE
[Moved from Discord] They Have Allies, But So do We 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1561]
Mistake
OP
 — Yesterday at 23:33
https://cata-twinhead.twinstar.cz/?quest=24681
Quest works decently. It does however, knock back the War Machines, which is not meant to happen.
https://www.youtube.com/watch?v=UxYRU0lw-RM

**Comment by UltraNix** [comment]
Fixed.
