### ISSUE TITLE
[Moved from Discord] Endgame

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1562]
https://discord.com/channels/1040715551531618365/1059254156415742113 - Full thread
Mistake
OP
 — Yesterday at 23:37
https://cata-twinhead.twinstar.cz/?quest=26706 Should give us ropes so we can drop down onto the Gunship, but we're forced to jump.
Image

There's supposed to be a big green orc you have to fight, and then theres Wind riders you'll have to click on and ride back to safety. None of this happens, and now you're stuck in the air with a wyvern, you CAN move, but you cannot move the Camera
Image

**Comment by UltraNix** [comment]
Fixed.
