### ISSUE TITLE
[Druid][Talent: Fungal Growth] does not provide slow 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1564]
Spell Wild Mushroom does not provide slow although animation is present

https://cata-twinhead.twinstar.cz/?spell=88747

![image](https://user-images.githubusercontent.com/121137397/210240863-ae28d79f-ed74-4729-a6fe-af5f77b4255a.png)
![image](https://user-images.githubusercontent.com/121137397/210240909-2204a46e-227e-4c26-be9b-bf0cb4d2db07.png)

**Comment by Afgann** [comment]
fixed
