### ISSUE TITLE
[Hunter][Beast Mastery][Spell- Spirit Mend] Does not heal when pet is dismissed

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1565]
https://cata-twinhead.twinstar.cz/?spell=90361

Buff is present but if pet is dismissed the healing stops

![image](https://user-images.githubusercontent.com/121137397/210242103-f1e55b64-8dfd-4e1e-93e9-06f1d6c39512.png)

**Comment by Afgann** [comment]
fixed
