### ISSUE TITLE
[Arena] Dalaran Arena shadow eye spawn location incorrect

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1570]
![image](https://user-images.githubusercontent.com/121137397/210284453-7cd838d2-a079-4729-b4c1-ba34e86b8494.png)

Should be in the corners not on the arena itself.

Screenshot from Crusader3455 showing the spawn location on wrath classic

![image](https://user-images.githubusercontent.com/121137397/210284488-1647f7c2-78bd-428d-a2c4-55a2ee03e205.png)

**Comment by Afgann** [comment]
fixed
