### ISSUE TITLE
[Arena] The Ring of  Valour bug list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1571]
players spawn in wrong orientation, black line should be correct orientation

![image](https://user-images.githubusercontent.com/121137397/210284837-8fec7cb3-26a7-4285-a64d-5e8a3ee2aebb.png)

Warrior can leap up into out of bounds, tied into issue #1569 
![image](https://user-images.githubusercontent.com/121137397/210284791-b98b8050-0caf-4b05-ae20-0922a990c799.png)
![image](https://user-images.githubusercontent.com/121137397/210284794-913c3c45-6a47-4fc6-8053-2863ab21b03c.png)

Pillars do not exist ,  you can fall through the part where they should spawn,  they also never show up.  Players who fall down are unable to get out without GM intervention

The chain animation works but the collision is missing

![image](https://user-images.githubusercontent.com/121137397/210284704-6cb6d299-3c62-4441-9d2e-5bab88e7623a.png)
![image](https://user-images.githubusercontent.com/121137397/210284923-18410d9c-feb4-49e1-9adf-cf3d96b76ce6.png)

**Comment by WhitemaneSylah** [comment]
Pillars still missing from RoV

**Comment by UltraNix** [comment]
Fixed.

**Comment by MullichWhitemane** [comment]
Most issues have been fixed, but the pillars in the east and west still have some funky behaviour.
https://www.youtube.com/watch?v=nVjGPCAnslo
Collision and LoS is always active until the split millisecond the pillars begins to rise.

**Comment by UltraNix** [comment]
Fixed.
