### ISSUE TITLE
[Minor][Object] Greatfather Winter's Chair still visible

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1572]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Christmas Event has finished but Greatfather Winter's Chair is still visible in Ironforge.

**How to reproduce:**
Visit Ironforge, 33,65 - you'll see the chair is still present. Deleting Cache did not resolve this.

**How it should work:**
The chair should not be visible as the Feast of Winter Veil ended yesterday.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
