### ISSUE TITLE
Badlands - Sleeping Dustbelcher Trainee doesn't attack

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1573]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When attacking a sleeping Dustbelcher Traineer in Badlands from Range, they don't get up and attack. They stay sleeping allowing you to freely cast.

**How to reproduce:**
Attack a sleeping Dustbelcher mob from range.

**How it should work:**
They should get up and start attacking. Could be because they attack from ranged so could be linked to previous bugs reported.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=46695

**Comment by Afgann** [comment]
fixed
