### ISSUE TITLE
Arathi - Twin Tin Ore Node

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1574]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Just north of Refuge Pointe in Arathi (42.52,42.62) there is a twin Tin Ore Node, where there are two nodes directly next to each other

**How to reproduce:**
.tele RefugePointe
Run North with "Find Minerals" enabled, you'll see two nodes right next to eachother

**How it should work:**
I don't believe nodes should be this close together.

**Database links:**

![Nodes](https://user-images.githubusercontent.com/6482585/210326946-c8be99b4-e109-4029-8680-8c9d027b0bb1.PNG)

**Comment by WhitemaneSylah** [comment]
This should be sorted when the player numbers goes up Torpis :)
