### ISSUE TITLE
[Moved from Discord][Class: Death Knight] Ghoul huddle not functioning

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1575]
Icetomeetyou
OP
 — Today at 09:44
How it should work: Go into a defensive crouch, reducing all damage taken  by 50% but preventing other actions

How it actually work: the pet uses this ability, but still continues to follow the character and interrupts it, so the pet continues to perform any other action that also interrupts the ability

Note: Dark Transformation version of the spell work correct

**Comment by MullichWhitemane** [comment]
Still doesn't work after the fix recent fix - https://discord.com/channels/1040715551531618365/1045188444617461870/1066044720847007875 

Video of the spell not functioning: https://www.youtube.com/watch?v=jI-hNx8iyXo

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/214001748-107571cd-dd45-4c2b-9355-8344fa6f66ae.png)

**Comment by UltraNix** [comment]
Also, why your ghoul has MANA power?
Spell itself works okay.

**Comment by MullichWhitemane** [comment]
Re-tested again, seems fixed now.
