### ISSUE TITLE
Winterfall Runner - Pathing Underground

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1578]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a Winterfall Runner who is totally underground in Winterspring. You should be able to see it if you track humanoids in Winterspring between 

It paths between 40.35, 52.08 and 44.60, 49.13 (possibly goes further than this but I stopped following)

**How to reproduce:**
Go to Winterspring 40, 52 and track Humanoids on a Hunter (I'd imagine this will be the easiest way to find the mob). I've seen it a couple of times just when running down the path so I know its a reccuring issue.

**How it should work:**
Mob should be above ground (or potentially not even there at all)

**Database links:**
https://wotlk-twinhead.twinstar.cz/?npc=10916
![Underground Mob](https://user-images.githubusercontent.com/6482585/210339058-a3d8e429-6934-412d-8fbc-ea078d6dc4c7.PNG)

**Comment by Torpis** [comment]
Could be linked to https://github.com/gamefreedomgit/Maelstrom/issues/1015

**Comment by UltraNix** [comment]
Fixed.
