### ISSUE TITLE
Winterspring - Twin Thorium Node Spawn

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1579]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At 31.50, 53.50 there is a twin node spawn of Thorium

**How to reproduce:**
Go to location on screenshot, there are 2 nodes directly next to eachother.

**How it should work:**
I don't believe nodes should be this close together.

**Database links:**

![Map Loc](https://user-images.githubusercontent.com/6482585/210339536-b0ae07cb-2970-4a07-9f3a-934ea7c8fda0.PNG)
![Twin Nodes](https://user-images.githubusercontent.com/6482585/210339541-bda54fe7-24db-48fc-b06c-c28dbc6d0d61.PNG)

**Comment by WhitemaneSylah** [comment]
Tied to #1574
