### ISSUE TITLE
[Minor] Holiday Snow still avaliable after Winter Veil has ended

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1580]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Winterspring I found some Holiday Snow even though Winter Veil ended yesterday.

**How to reproduce:**
The one I found I looted, but if I spot another I'll update it here.

**How it should work:**
Holiday Snow should only be avaliable during the winter veil event.

**Database links:**
https://www.wowhead.com/object=178609/holiday-snow#comments

**Comment by Torpis** [comment]
One is avaliable at 62.71, 53.71 in Winterspring

**Comment by UltraNix** [comment]
Fixed.
