### ISSUE TITLE
Ice Thistle Matriach / Yetis freezing player too often

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Both the Ice Thistle Matriach and Yetis are freezing the player too often.

**How to reproduce:**
Attack them when around level 52, notice how they freeze quite often. You'd expect this to be lower. Some old wowhead comments say this should be a chance on hit rather than them casting - but the proc rate/cast rate seems too high.

**How it should work:**
Be less frequent or add an icd.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=15878
https://cata-twinhead.twinstar.cz/?npc=7459
https://cata-twinhead.twinstar.cz/?npc=7458

**Comment by Afgann** [comment]
fixed
