### ISSUE TITLE
[Quest] Echo Three not working as expected

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1582]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When turning in Echo Three you get teleported into the cave, there should be an icicle that you have to hit to get free. What actually happens on the server is there is no icicle and you just hit the "Leave Vechicle" button.

**How to reproduce:**
Hand in Echo Three

**How it should work:**
https://www.youtube.com/watch?v=mb4sxiHDgyk

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28630

**Comment by UltraNix** [comment]
Fixed.
