### ISSUE TITLE
[Minor] Monstorous Crawler - Underground

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1583]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Swamp of Sorrows there are two Monstorous Crawler which are spawned undergound.

**How to reproduce:**
Go to 77.59, 10.61 in Swamp of Sorrows (East of Bogpaddle). There are some mobs spawning underground, at least 2 that I have found (I killed one of them) both are Monstorous Crawler 

If you track beasts you can probably find quite a few. I've just found another one north of the reported one.

**How it should work:**
They should be above ground pathing in the water/on the shore.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=1088
![Underground Spawn](https://user-images.githubusercontent.com/6482585/210359598-a624fa0f-4f85-41a8-880e-c2f1f818ee8e.PNG)

**Comment by Afgann** [comment]
fixed
