### ISSUE TITLE
Trade Baron Silversnap not Offering Quests

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After taking Hero's Call: Swamp of Sorrows, I expected Trade Baron Silversnap to offer "Maliciously Delicious" which would then lead to follow ups. He does not offer the quest for some reason.

**How to reproduce:**
.tele Bogpaddle
Trade Baron Silvernap doesn't have any quests.

**How it should work:**
I believe he should offer Maliciously Delicious (27587) - I can't see any requirements.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=45786#starts
https://cata-twinhead.twinstar.cz/?quest=27587

**Comment by Torpis** [comment]
https://www.wowhead.com/quest=28569/the-bogpaddle-bullet#comments may be the pre-requisite but this also isn't offered by the quest giver.

**Comment by Torpis** [comment]
This also means that you can't do any of the quests from https://cata-twinhead.twinstar.cz/?npc=46676 as the previous quests lead onto this.

**Comment by Torpis** [comment]
Also blocks out Crazy Larry Quests: 

https://www.wowhead.com/quest=27597/crazy-larry

**Comment by Greywolf59** [comment]
It worked fine for me. Started by handing in [The Bogpaddle Bullet](https://www.wowhead.com/quest=28569/the-bogpaddle-bullet). This quest is offered in Burning Steppes.
If [Hero's Call: Swamp of Sorrows!](https://www.wowhead.com/quest=28675/heros-call-swamp-of-sorrows) does not open [Maliciously Delicious](https://www.wowhead.com/quest=27587/maliciously-delicious) then it is a bug as:
1. Both Bullet and Call quests should open Maliciously Delicious
2. If you have either Bullet or the Call, you should not be able to grab the other

**Comment by Torpis** [comment]
Thanks Grey. then the bug is that hero’s call doesn’t then open up the chain!

**Comment by Afgann** [comment]
fixed
