### ISSUE TITLE
[NPC] [Item] [Minor] Frankie Goodtimes - sells STV Page 8

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1586]
[Frankie Goodtimes](https://www.wowhead.com/npc=47338/frankie-goodtimes) sells [Green Hills of Stranglethorn - Page 8](https://www.wowhead.com/item=2732/green-hills-of-stranglethorn-page-8), which should not be the case.

**Comment by Afgann** [comment]
fixed
