### ISSUE TITLE
[NPC] Bogpaddle Carousers

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1587]
[Marshtide Carousers](https://www.wowhead.com/npc=46187/marshtide-carouser) and [Stonard Carousers](https://www.wowhead.com/npc=46189/stonard-carouser).

Based on [wowpedia ](https://wowpedia.fandom.com/wiki/Marshtide_Carouser) they should be "commonly found sleeping in the inn, chatting with [Bogpaddle Workers](https://wowpedia.fandom.com/wiki/Bogpaddle_Worker), and watching [Bogpaddle Entertainers](https://wowpedia.fandom.com/wiki/Bogpaddle_Entertainer) at the bar alongside [Stonard Carousers](https://wowpedia.fandom.com/wiki/Stonard_Carouser)."

Problems:
1. I dont see any Carousers chatting with [Bogpaddle Workers](https://www.wowhead.com/npc=45791/bogpaddle-worker).
2. Those of them watching Bogpaddle Entertainers are not actually watching. In fact they are sleeping like they would be in an inn.
3. One of the Stonard Carousers is laying under the engine behind the entertainers.

**Comment by UltraNix** [comment]
Fixed.
