### ISSUE TITLE
[Object] Sundried Driftwood - lootable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1588]
[Sundried Driftwood Object](https://www.wowhead.com/object=24798/sundried-driftwood) is lootable for [Sundried Driftwood item](https://www.wowhead.com/item=6146/sundried-driftwood).

There is no quest linked to the driftwood anymore. According to [Wowpedia](https://wowpedia.fandom.com/wiki/Sundried_Driftwood), this item was removed with 4.0.3a so the object should not be interactable at all.

**Comment by Torpis** [comment]
I can confirm this is lootable.

**Comment by Greywolf59** [comment]
Should be fixed now acc to discord
