### ISSUE TITLE
[Quest] Step Two: The Bloodletter - missing Completion gossip

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1589]
[Step Two: The Bloodletter](https://www.wowhead.com/quest=27768/step-two-the-bloodletter) is missing gossip (text in chat window with Q giver) on Completion. It should say: A deserved fate. You will not find the pacifism of the red dragonflight among my kin, [name]; we will not suffer the intrusions of mortals. ([Wowpedia](https://wowpedia.fandom.com/wiki/Step_Two:_The_Bloodletter))

**Comment by UltraNix** [comment]
Fixed.
