### ISSUE TITLE
Subdued Seahorse doesn't increase move speed

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mount should be 270% speed in Vashj'ir and 108% speed in other areas.

**How to reproduce:**
.itemadd 67151
Use item
.tele Biel
/cast Subdued Seahorse
Notice how move-speed isn't increased

**How it should work:**
Should move 270% speed.

**Database links:**
https://www.wowhead.com/spell=98718/subdued-seahorse#comments

**Comment by UltraNix** [comment]
Fixed.
