### ISSUE TITLE
[Quest] Step Three: Prophet - dies, no escape

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1591]
Quest: [Step Three: Prophet](https://www.wowhead.com/quest=27773/step-three-prophet)
Video how it should be: https://www.youtube.com/watch?v=-XjweQPRrjo
Problem: [Jammal'an the Prophet](https://www.wowhead.com/npc=46656/jammalan-the-prophet) simply dies, doesn't escape. His emotes and ability usage should also be checked.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Priestelar** [comment]
@UltraNix i attempted this quest again today and the problem has reoccurred, GM Tide had to complete the quest for me
