### ISSUE TITLE
[Quest] Blessing of the Green Dragonflight - no teleport

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1592]
Quest: [Blessing of the Green Dragonflight ](https://www.wowhead.com/quest=27914/blessing-of-the-green-dragonflight)
Video how it should be: https://www.youtube.com/watch?v=-XjweQPRrjo; TIMESTAMP 0:45
Issue: When you accept the quest, you should be teleported back to the quest giver. This does not happen and player gotta leg it back.

**Comment by Afgann** [comment]
fixed
