### ISSUE TITLE
[NPC]Marshtide Knight - pathing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1593]
[Marshtide Knights](https://www.wowhead.com/npc=46414/marshtide-knight) in Marshtide Watch should be standing around the Infantry as seen in this video: https://www.youtube.com/watch?v=jP2VQhCSJ8s
Currenctly they are walking around through the Footmen.

**Comment by UltraNix** [comment]
Fixed.
