### ISSUE TITLE
[Script] Marshtide Watch vs Stonard - phasing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1594]
This is hard to explain but basically every phase of the battle between Marshtide and Stonard are thrown into one.
The battle should progress as the player does the quests:

1. Before and Druing these quests:
[Orcs and Humans](https://www.wowhead.com/quest=27821/orcs-and-humans)
[Lumbering Oafs](https://www.wowhead.com/quest=27822/lumbering-oafs)
Videos:
OaH https://www.youtube.com/watch?v=2VH-WVAs-LY
LO https://www.youtube.com/watch?v=cl9TPdpho_E
Observation: There are no [Stonard Warlocks](https://www.wowhead.com/npc=46770/stonard-warlock), [Marshtide Mages](https://www.wowhead.com/npc=46775/marshtide-mage) and [Stonard Ogres](https://www.wowhead.com/npc=46765/stonard-ogre) visible on either videos. On PTR you can see all those NPCs, plus it seems there is a bit unhealthy number of Alliance NPCs too (probably also phasing issue)

2. During next wave of quests:
[Tides of Darkness](https://www.wowhead.com/quest=27795/tides-of-darkness)
[Reinforcements Denied](https://www.wowhead.com/quest=27843/reinforcements-denied)
[Marking the Fallen](https://www.wowhead.com/quest=27845/marking-the-fallen)
Videos:
ToD https://www.youtube.com/watch?v=5BqG_Af8BC4
RD https://www.youtube.com/watch?v=6lfHko3AoVw
Observation: Now only the Ogres, mages and warlock and dead bodies are visible. You can even see how the phase changes when the player enters the zone.
On PTR, the knights on mounts and the [Stonard Wardrummers](https://www.wowhead.com/npc=46749/stonard-wardrummer) on [kodos](https://www.wowhead.com/npc=46748/stonard-kodo-beast) remain. [Stonard Warriors](https://www.wowhead.com/npc=46166/stonard-warrior) still fight against [Marshtide Footman](https://www.wowhead.com/npc=46164/marshtide-footman) and [Marshtide Knights](https://www.wowhead.com/npc=46414/marshtide-knight).

3. During the Final Phase:
[Assault on Stonard](https://www.wowhead.com/quest=27849/assault-on-stonard)
[Cutting Supply](https://www.wowhead.com/quest=27851/cutting-supply)
Videos:
AoS https://www.youtube.com/watch?v=-r3f6EUbiDU
CS https://www.youtube.com/watch?v=DMNeGaHf-zA
Observation: In the videos, there are only [Marshtide Invaders](https://www.wowhead.com/npc=46869/marshtide-invader) and [Stonard Defenders](https://www.wowhead.com/npc=46870/stonard-defender) fighting each other.
On PTR there are also normal unphased Stonard NPCs visible. Also all the NPCs mentioned before are still fighting on the battlefield which should now be empty.

**Comment by UltraNix** [comment]
Fixed.
