### ISSUE TITLE
[Quest] The Harborage - available early

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1595]
Quest: [The Harborage](https://www.wowhead.com/quest=27918/the-harborage)
Issue: This quest is available to players right away. It should be available only after completion of [Draenethyst Crystals](https://www.wowhead.com/quest=27840/draenethyst-crystals) and probably also [The Lost Ones](https://www.wowhead.com/quest=27860/the-lost-ones).
Requirements on Twinstar: https://cata-twinhead.twinstar.cz/?quest=27918
Video showing after completion of Draenethyst Crystals still only The Lost Ones is available: https://www.youtube.com/watch?v=FLw_g5OL45E (note: right at the start, check chat)
This suggests that both quests should be required as completed for player to be able to recieve The Harborage quest.

**Comment by Afgann** [comment]
fixed
