### ISSUE TITLE
[NPC] [Quests] Anchorite Avuun - quests offered too early

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1596]
Video 1:41: https://www.youtube.com/watch?v=GMSWzrWZuf4
[Anchorite Avuun](https://www.wowhead.com/npc=17127/anchorite-avuun) should offer at the start only [Prayerblossom](https://www.wowhead.com/quest=27875/prayerblossom), [Secrets of the Mire](https://www.wowhead.com/quest=27876/secrets-of-the-mire) and [Onward to Blasted Lands](https://www.wowhead.com/quest=27919/onward-to-the-blasted-lands).
Right from the start also offers [Breath of Mist](https://www.wowhead.com/quest=27904/breath-of-mist) and [The Purespring](https://www.wowhead.com/quest=27902/the-purespring), which should both be available only after completing Prayerblossom and Secrets of the Mire.
He even offers the very last quest right away, [Remember the Light](https://www.wowhead.com/quest=24913/remember-the-light) which should be available only after completing Breath of Mist and The Purespring.

**Comment by Torpis** [comment]
Interestingly I didn’t have this issue, I had to do all quests in order finishing with Remember the Light.

**Comment by UltraNix** [comment]
Fixed.
