### ISSUE TITLE
Night Elf - Mage - Starting Zone (Aldrassil) - Cant finish zone

### ISSUE THREAD

**Issue by ActionleagueWoW** [gamefreedomgit/Maelstrom#1597]
**Description:**
Night elf - Mage - Starting Zone Aldrassil - Quest: Priestess of the Moon - accepted after "Arcane Missiles" (Training dummy quest for skill - Mage)

First tested without addons. Noticed I got no quest so I downloaded a guide to make sure I was progressing properly. 

Quest does not activate and let the player continue the zone. Instead we receive a duplicate "Complete Quest" window in it's place that is non active.

**How to reproduce:**
Reproduced 3 times

Level a Night Elf mage. After first few quests, accept "Arcane Missiles" we need to talk to "Rhyanda <Mage Trainer>". and after you talk to skill trainer and test arcane missiles on the dummy. Return to quest giver and turn in quest to activate bug.

**How it should work:**
We should get the next quest available called "Priestess of the Moon" and continue the starting zone questline around the back of Aldrassil

**Database links:**
https://youtu.be/Vldp2pBYoNM (Video of bug)
https://www.wow-pro.com/solithas-alliance-leveling-guide-part-one-teldrassil-1-5/ Lvling guide

**Comment by UltraNix** [comment]
Fixed.
