### ISSUE TITLE
[Quest] Remember the Light - event could be better

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1600]
Quest: [Remember the Light](https://www.wowhead.com/quest=24913/remember-the-light)
Video: https://www.youtube.com/watch?v=ZxevDOEKqvU
Issue: Quest is completable and event looks nice at the start, except Avuun not kneeling, but after Magtoor says "Yes..." it does not play out properly and parts of events are missing, both visual and /emotes. Quest gets completed at the end though.

**Comment by UltraNix** [comment]
Fixed.
