### ISSUE TITLE
[Quest][Cata] Twilight Skies 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1601]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:** there is a twilight swarmer inside zeppelin keeping players in combat 
![image](https://user-images.githubusercontent.com/36106057/210422291-24a26bb5-f7a9-4945-b07e-b0c35d302985.png)
![image](https://user-images.githubusercontent.com/36106057/210422176-2622d09a-42ca-49f3-b2e9-94e30048bd18.png)
and end of the quest emergency debarkation device taking the player to a random unknown location its not working properly 
![image](https://user-images.githubusercontent.com/36106057/210423309-d8c167d5-8548-4999-b2cf-90cbff1bfa7a.png)

**How it should work:**
Like the video below 
https://www.youtube.com/watch?v=EqM-F6tYHfQ

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26388

**Comment by MrTide** [comment]
Some issues can be found here as well:
https://github.com/gamefreedomgit/Maelstrom/issues/2094

**Comment by Aughra23** [comment]
Adding to MrTides Post:
![image](https://user-images.githubusercontent.com/125700006/219871345-5adcd7ee-0f9d-4edc-a298-4079afedefa1.png)
Device locked me in place then I got dumped in Azshara. Quest completed though.

**Comment by MrTide** [comment]
update: still has issues looks like players can't grab parachute from time to time and requires multiple tries 
![image](https://user-images.githubusercontent.com/36106057/226194784-1afd9990-e7e9-4599-86d0-b3d727faa010.png)

**Comment by UltraNix** [comment]
@MrTide Let me know if there are still problems with parachutes.

**Comment by MrTide** [comment]
Update:
 i had a player ticket complaining that he couldnt click on the parachutes at end of the event

**Comment by PanJanuszek** [comment]
No longer in reproduction
