### ISSUE TITLE
[Quest][Cata]Traitor's Bait

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1604]
**How to reproduce:**
after talking to the npc suspicious peon, Sauranok the mystic appears and kills the peon then he disappears, event is not working 

**How it should work:**
He should fight the player
Like this video: https://www.youtube.com/watch?v=UmjeFx0ssto

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26830

**Comment by Afgann** [comment]
fixed
