### ISSUE TITLE
[Quest][Cata] Mo' Better Shredder

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1605]
**How to reproduce:**
Skirmishers that spawn around you to fight they just stand around and don't attack at all
since they dont fight players its possible for players to spawn a lot of them in the area and cause issues in long run (assuming multiple players try to do the same quest)
![image](https://user-images.githubusercontent.com/36106057/210431349-d8b44ef3-60ab-40c3-a1a4-98980deef6e1.png)
![image](https://user-images.githubusercontent.com/36106057/210431484-b8fe7699-b880-4a17-8fb7-eae49aa07524.png)

**How it should work:**
Like this video they should attack: https://www.youtube.com/watch?v=Z9KodxKsQGY

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27622

**Comment by Afgann** [comment]
fixed
