### ISSUE TITLE
[Quest][Cata] [Minor] Blast Him!

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1606]
**How to reproduce:**
In order to do quest Blast Him! you need to do [Shells on the Sea Shore](https://cata-twinhead.twinstar.cz/?quest=27586) first but here there is no requirement 
![image](https://user-images.githubusercontent.com/36106057/210432859-f1ecf610-6433-4093-9231-2487a8cb7628.png)

**How it should work:**
Blast Him! should be available after doing [Shells on the Sea Shore](https://cata-twinhead.twinstar.cz/?quest=27586)

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27606

**Comment by PanJanuszek** [comment]
Quest chain fixed
