### ISSUE TITLE
Night Elf - Warrior - Starting Zone (Aldrassil) - Cant finish zone

### ISSUE THREAD

**Issue by ActionleagueWoW** [gamefreedomgit/Maelstrom#1607]
Description:
Night elf - Warrior - Starting Zone (Aldrassil) - Quest: Priestess of the Moon - accepted after "Learning New Techniques" (Training dummy quest for skill - Warrior)

Quest does not activate and let the player continue the zone. Instead we receive a duplicate "Complete Quest" window in it's place that is non active.

How to reproduce:

Level a Night Elf Warrior. After first few quests, turn in "Simple Sigle" to "Alyissia <Warrior Trainer>" then accept quest "Learning New Techniques". After you use the target dummies, turn in the quest. 

How it should work:
We should get the next quest available called "Priestess of the Moon" and continue the starting zone questline around the back of Aldrassil

Links:
https://youtu.be/DZHbRTApx30

**Comment by UltraNix** [comment]
Fixed.
