### ISSUE TITLE
[Quest][Cata] How to Maim Your Dragon

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1608]
**How to reproduce:** after accepting the quest some secondary version of you gets mounted on the dragon and after 5-10 sec you also mount up and at the end of the event camera angle is weird and when event is done some copy of you is still around that should not happen, this would cause issues if a lot of ppl decide to do it.
![image](https://user-images.githubusercontent.com/36106057/210435866-98562b8b-0f1c-4a04-9553-d129b61e19b2.png)
![image](https://user-images.githubusercontent.com/36106057/210435999-7410d017-3df6-482e-8520-ecae445d5ee0.png)

**How it should work:** this is how its supposed to work
https://www.youtube.com/watch?v=GE8J0G3ca7g

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28043

**Comment by MrTide** [comment]
resolved

**Comment by PanJanuszek** [comment]
Gonna be good soon :)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/23cea474-c046-416c-812d-298cb412e7ab)
