### ISSUE TITLE
[Quest][Cata]  Parting Packages  +  Of Utmost Importance + Krazz Works!

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1612]
**How to reproduce:**
there is a phasing issue with these quests after completing  parting packages both npcs which is called patch and ticker phase out which makes it impossible for the players to complete patch quests he should stay until you turn your quests and accept his following quests
(also for some unknown reason if you turn your gm mode on ticker offers another parting packages quest)
![image](https://user-images.githubusercontent.com/36106057/210447927-e9b93f5c-8164-4f8f-8e3e-b9aca7fb405e.png)
![image](https://user-images.githubusercontent.com/36106057/210448904-e7492534-7b60-445e-8c0f-b00a3dbe5423.png)

**How it should work:**
patch should not phase out until you turn in the quests and accept his following quest which is called  Krazz Works!

**Comment by UltraNix** [comment]
Fixed.
