### ISSUE TITLE
[Quest][Cata]  Devoured

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1617]
**How to reproduce:**
Quest  [Devoured] is not scripted properly blood of iso'rath basically do no damage and you can't die without them spawning and killing you, right now they spawn but they don't attack you and they just stand around until some npc goes and kill them
note: looks like rest of the event works but i had to reduce my hp to 1 in order to get killed, most of them dont even hit anything.

**How it should work:**
Like this video: https://www.youtube.com/watch?v=Zb_LrMH30fk

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27377

**Comment by MrTide** [comment]
Did you removed it from quest autocom list after fix ? it might be still in there

**Comment by UltraNix** [comment]
No - I did not.
