### ISSUE TITLE
[Suggestion/Bug from Discord] Pet cooldown reset on duels

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1619]
Chris99
OP
 — 21/12/2022 02:55
Make Pet CDS reset as well on duels, pls.
liljon — 21/12/2022 03:15
As well as forbeareance
Foster — Today at 23:08
@Sylah can you make a bug report for this also :dogeheart:
Approved, I consider this more of a bug than anything
Sylah — Today at 23:09
Creating as we speak boss :SylahuLove:

**Comment by Afgann** [comment]
fixed
