### ISSUE TITLE
[Quest][Cata]  The Terrors of Iso'rath

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1620]
**How to reproduce:**
 The Terrors of Iso'rath is impossible to do
 earthmender duarn after getting freed falls and goes under ground 
 also while moving around in this area to finish the quest you keep phasing out and in and that should not happen.
![image](https://user-images.githubusercontent.com/36106057/210456320-81d640e0-ba96-4169-ade8-4aa0f8950c1b.png)
its not scripted properly
**How it should work:**
npcs should not fall under ground and events should work as intended like this video : https://www.youtube.com/watch?v=0uErXSxnSs8

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27379

**Comment by UltraNix** [comment]
Fixed.
