### ISSUE TITLE
[Quest][Cata]  Nightmare

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1621]
**How to reproduce:**
Players can't attack Iso'rath and after a few moments he just phases out
![image](https://user-images.githubusercontent.com/36106057/210457326-3013816f-475b-4f83-92a8-2a72965221aa.png)
![image](https://user-images.githubusercontent.com/36106057/210457346-e059471c-aebb-4fc3-b1ad-6d39633163fa.png)

**How it should work:**
he should not phase out and players should be able to kill it
https://youtu.be/4uHRkuX4naU?t=260
**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27380
related issue: https://github.com/gamefreedomgit/Maelstrom/issues/1620

**Comment by Greywolf59** [comment]
Is this fixed yet? Discord Maelstrom News say "Twilight Highlands still has number of outgoing reports… **Everything should be completable**, but we still need to put more effort into polishing out this zone."

**Comment by UltraNixx** [comment]
Fixed.
