### ISSUE TITLE
[Quest][Cata] The Crucible of Carnage: The Bloodeye Bruiser!

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1622]
**How to reproduce:**  gurgthock does does too many fears thats not how its supposed to work.
and after finishing the quest if you seek wodin the troll-servant you can turn in the quest on him multiple times that should not happen at all!

**How it should work:**
whole fight here
https://www.youtube.com/watch?v=UhTyiqp2fk0

**Comment by Afgann** [comment]
fixed

**Comment by MrTide** [comment]
Reopening the issue
