### ISSUE TITLE
[Quest][Cata] The Crucible of Carnage: The Wayward Wildhammer!

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1623]
**How to reproduce:** Sully kneecapper is not working properly
![image](https://user-images.githubusercontent.com/36106057/210459807-7ff1faab-3214-4a69-bb59-c08f711e443f.png)
after he grabs you and pushes you to the wall he just bugs out and stands in one places and throws hammers 

**How it should work:**
Like this video: https://www.youtube.com/watch?v=XUywsEPsCrU

**Comment by Afgann** [comment]
fixed
