### ISSUE TITLE
[Quest][Cata] The Crucible of Carnage: The Twilight Terror!

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1624]
**How to reproduce:** npc Emberscar the devourer does so much damage with its fireball 
that makes it impossible to kill him
![image](https://user-images.githubusercontent.com/36106057/210461468-67740bbc-ff9f-4263-a392-db93103d783e.png)

**How it should work:** he is not supposed to do that much damage with fireball
https://www.youtube.com/watch?v=Ak2GcOGr8EQ

**Comment by Afgann** [comment]
fixed
