### ISSUE TITLE
[Quest][Cata] Warm Welcome

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1625]
**How to reproduce:** Npc simply is not offering the quest although i have done the requirements, i tried to add the quest manually i dont think its working at all and thats why its disabled, probably its because this area is not scripted properly
i just saw some dragons here and there and nothing worked they are not even flying
![image](https://user-images.githubusercontent.com/36106057/210463163-48e70aa6-d2cc-4e5e-bc8f-4761d40c7b81.png)
![image](https://user-images.githubusercontent.com/36106057/210462183-a74de80f-ffb0-4059-8a63-5bb0789e77c7.png)
requirements 
![image](https://user-images.githubusercontent.com/36106057/210462217-2ea20d70-937c-4a59-86a4-80b80ce9fae4.png)
![image](https://user-images.githubusercontent.com/36106057/210462233-8292f856-6650-410b-b28f-9a76cdc76b59.png)

**How it should work:**
you should be able to get the quest i would assume its the same for alliance side
i couldn't find any other requirements 
this is how its done: https://www.youtube.com/watch?v=1FfDnwxqE5E
**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27486

**Comment by UltraNix** [comment]
Fixed.
