### ISSUE TITLE
[Minior][NPC] Sethria Bugged

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1627]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sethria (NPC 41255) doesn't work as intended. She starts the fight as a dragon rather than a human, and then becomes a human - should be the other way around. Also, you are able to kill the Twilight Fissures she spawns if you use an AOE skill (I used Hammer of Righteous) 

Twilight Fissures: https://cata-twinhead.twinstar.cz/?spell=78160

**How to reproduce:**
Pull Sethria, ideally with the quest - she was in dragon form at first for me. I was unable to use the quest item (which states she should be in dragon form). When she changes to Human form you are able to use the item - she changes around 75% HP.

When in "Dragon" form (ie. what should be human) - she casts Twilight Fissures, these are killable by players when they shouldn't be.

**How it should work:**
https://www.youtube.com/watch?v=z-hRYRjBNjM

Human becomes dragon in the above video.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=25776
https://www.wowhead.com/quest=25776/sethrias-demise
https://www.wowhead.com/npc=41255/sethria
![Spawns as Dragon](https://user-images.githubusercontent.com/6482585/210514630-0c11c6c1-dd13-437b-a36d-46d765a5d44c.PNG)

**Comment by Afgann** [comment]
fixed
