### ISSUE TITLE
[Quest] [Important] Hero's Call: Blasted Lands! - does not open next quests

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1630]
Quest: [Hero's Call: Blasted Lands!](https://www.wowhead.com/quest=28673/heros-call-blasted-lands)

Issue: After handing in this quest, you should be offered quest [Minor Distractions](https://www.wowhead.com/quest=25710/minor-distractions). This does not happen.
Note: I have delivered [Onward to the Blasted Lands](https://www.wowhead.com/quest=27919/onward-to-the-blasted-lands) first.

I will finish my Blasted Lands report when this is resolved.

**Comment by Afgann** [comment]
fixed
