### ISSUE TITLE
[Quest] Watcher Mahar Ba - available too early

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1632]
Quest: [Watcher Mahar Ba](https://www.wowhead.com/quest=25714/watcher-mahar-ba)

Issue: Both possible quest givers (Quartermaster and Enohar) offer this quest right away on player's 1st visit to Nethergarde.

Based on twinstar, wowpedia and wowhead comments, this quest should be available only after player completes all the quests both [Enohar](https://www.wowhead.com/npc=9540/enohar-thunderbrew) and [Quartermaster](https://www.wowhead.com/npc=5393/quartermaster-lungertz) has to offer.
In practice it should mean the quest is should be available after player completes both [Eliminate the Okri'lon](https://www.wowhead.com/quest=25711/eliminate-the-okrillon), [Curtail the Darktail](https://www.wowhead.com/quest=25709/curtail-the-darktail) and [Our Fallen Friends](https://www.wowhead.com/quest=25708/our-fallen-friends).

**Comment by Afgann** [comment]
fixed
