### ISSUE TITLE
[Minor][NPC] First Mate Moody should be Kneeling

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1635]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
First Mate Moody should be kneeling in pain from the injuries he sustatained during the attack on the ship.

**How to reproduce:**
Look at First Mate Moody, his own entrails are next to him! He should not be stood up like nothing happened.
![FMM](https://user-images.githubusercontent.com/6482585/210598210-41935e8a-2543-4401-bc41-f27697c587a2.PNG)

**How it should work:**
He should be kneeling/lying in pain

**Database links:**
https://wowpedia.fandom.com/wiki/First_Mate_Moody
https://www.wowhead.com/npc=43082/first-mate-moody

**Comment by UltraNix** [comment]
Fixed.
