### ISSUE TITLE
[Minor] "Generic Trigger Vehicle LAB" is visible on 2nd floor of Alliance Ship in Deepholm

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1636]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
"Generic Trigger Vehicle LAB" is visible on 2nd floor of Alliance Ship in Deepholm

**How to reproduce:**
Go to the second floor of the ship and look on the beam in the middle.
![Impy Boy](https://user-images.githubusercontent.com/6482585/210599030-a3391c71-726f-43a2-a1a1-7d7d55e2721e.PNG)

**How it should work:**
I imagine this little imp should be invisible.

**Database links:**
https://www.wowhead.com/npc=42809/generic-trigger-vehicle-lab

**Comment by Afgann** [comment]
fixed
