### ISSUE TITLE
[Quest] [Important] Nethergarde Reigns and Remove Their Arms - too early

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1637]
[Wowpedia](https://wowpedia.fandom.com/wiki/Nethergarde_Reigns?so=search#Progression); [twinstar](https://cata-twinhead.twinstar.cz/?quest=25710)

Issue: [Nethergarde Reigns](https://cata-twinhead.twinstar.cz/?quest=25712) and [Remove Their Arms](https://cata-twinhead.twinstar.cz/?quest=25713) should be available only after player accepts [Minor Distractions](https://cata-twinhead.twinstar.cz/?quest=25710) (which is currently unavailable).

**Comment by Greywolf59** [comment]
Update: After I have completed and ahnded in [Our Fallen Friends](https://www.wowhead.com/quest=25708/our-fallen-friends) I came back to check on the quest givers. Now they do not offer their quests at all. No Reigns, Arms, Distractions, not even [Watcher Mahar Ba](https://www.wowhead.com/quest=25714/watcher-mahar-ba) mentioned in other issue.

**Comment by Afgann** [comment]
fixed
