### ISSUE TITLE
[Quest] Some Spraining to Do doesn't complete

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1638]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Some Spraining to Do doesn't complete

**How to reproduce:**
Accept the quest and jump on Stormbeak - the quest does not complete once the RP has ended. The RP should also be a lot longer than it currently is as shown in the video below.

**How it should work:**
The quest should complete after the RP has finished.
https://www.youtube.com/watch?v=--8Fwa-EvSg

**Database links:**
https://www.wowhead.com/quest=26254/some-spraining-to-do

**Comment by Greywolf59** [comment]
Confirmed. Seems the gryphon returns too soon.

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
@Torpis  Are you sure you have not completed that before (e.g. by command or something)?
