### ISSUE TITLE
[Moved from Discord][Hunter][Spec=Survival] Issues found  with Pathing and Serpent Spread

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1647]
liljon
OP
 — Today at 23:17
Pathing gives sligthly more haste per rank than intended - each rank grants 1.043% haste instead of 1.0%.

Serpent Spread has a delay between Multi Shot damaging and Serpent Sting being applied. Normally, the Sting should be applied the moment Aimed Shot successfully connects.

**Comment by Afgann** [comment]
fixed
