### ISSUE TITLE
[Moved from Discord][PvP] Certain movement spells on thin terrain and elevation + minor issues 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1648]
liljon
OP
 — Today at 23:26
As context, imagine the rope between the bridge and the pillar on Blade's Edge Arena.

Charge, Intervene, Intercept, Hunter Pet Charge and Feral Bear Charge can throw you on the terrain below if you charge with the correct offset (generally, you can recreate this if you are not precisely lined up with the rope. Walk off to the sides a little bit and charge). This list would also contain Bear and Cat interrupts, but currently, they use Cat's Feral Charge as part of their physics, which utterly break those spells, they should behave just like Charge.

Shadowstepping to thin surfaces has the ability to throw you below ground if the person you are Shadowstepping on faces the right way. Normally, Shadowstep places you behind your target, but if the terrain does not allow that, then it places you with a smaller offset depending on the terrain (so it can be a 0.01 yard offset all the way into the origin point of the player that is being Shadowstepped on).

I forgot to test Blink, but I will edit this post once I have.

Similarly on Blade's Edge, if you attempt to use Charge and similar spells from the bridge to the pillar, it does not let you until the player drops down to the rope. This issue does not exist for any other type of gapcloser. Also, with Charge type spells, if you are in the deadzone, you can jump off the pillar, and at the apex of your jump, you can charge back onto the pillar. Normally, this shouldn't be possible, as if you are jumping, and if the terrain below you does not grant proper pathing for charge (which is the ground beneath the pillar in this case), you shouldn't be able to charge, and since there isn't any scenario where you can scale a pillar with a charge, you should only be able to charge people that are actually on the ground floor.

**Comment by WhitemaneSylah** [comment]
Update from liljon: Blink suffers from the same elevation issue as Charge. Again, taking Blade's Edge Arena as context, jumping off the pillar, as long as your character has a higher elevation than the pillar (at and around the apex of your jump) you can Blink back to the pillar, whereas you should be placed on the ground below if you Blink.
It's also impossible to Blink on the rope, or on the pillar from the bridge/rope.

**Comment by UltraNix** [comment]
@WhitemaneSylah Need some video or screenshots with coords or where I can test it properly.

**Comment by MullichWhitemane** [comment]
@WhitemaneSylah When available, we can re-test all the listed issues.

**Comment by MullichWhitemane** [comment]
Warrior charge on thin terrain from certain angles: https://www.youtube.com/watch?v=D6CV_J6_Rrc (this affects Intervene and Intercept as well)
Warrior charge when jumping off of high elevation: https://www.youtube.com/watch?v=PojGHco-vxE
Druid Skull Bashes using Cat Feral Charge physics and further issues with the Charge-like Feral Bear Charge spell: https://www.youtube.com/watch?v=OOxbH0oL4Q4
Shadowstepping people on thin terrain when they face their backs in the right direction: https://www.youtube.com/watch?v=9cVjlQQy8_0
Funky behaviour with Blink: https://www.youtube.com/watch?v=2-hBpGYPEII (although I couldn't recreate being able to blink back on top of the pillar, might be fixed?)

**Comment by MullichWhitemane** [comment]
With the new fix, Charge mechanics behave much better, but everything else is still wonky (Blink got worse). We also found a new issue with Death Grip on the ropes.
https://www.youtube.com/watch?v=GL4TeZ0Ecg8 Death Grip, if done at the very ends of the rope (so either near the pillar or near the bridge, not in the middle of the rope) places the gripped target beneath the Death Knight.
https://www.youtube.com/watch?v=fUnHmevWx-I Blink got much worse, the video sort of speaks for itself.

**Comment by UltraNix** [comment]
`With the new fix, Charge mechanics behave much better, but everything else is still wonky (meaning Shadowstep, Skull Bashes sharing Feral Charge Cat Leap physics and Blink).` Show me that "wonky"  behaviour.

**Comment by MullichWhitemane** [comment]
> Show me that "wonky" behaviour.

I've meant that other than Charge mechanics, everything else still has their listed issues - but I will relink everything in this reply just to be clear.

Druid Skull Bashes using Cat Feral Charge physics (instead of normal Charge physics): https://www.youtube.com/watch?v=OOxbH0oL4Q4 (Ignore Feral Charge Bear in this clip)

Shadowstepping people on thin terrain when they face their backs in the right direction: https://www.youtube.com/watch?v=9cVjlQQy8_0

Death Grip, if done at the very ends of the rope (so either near the pillar or near the bridge, not in the middle of the rope) places the gripped target beneath the Death Knight. https://www.youtube.com/watch?v=GL4TeZ0Ecg8 

Blinking lets you move through empty space, and even Blink across the pillar and land downstairs. https://www.youtube.com/watch?v=fUnHmevWx-I

**Comment by MullichWhitemane** [comment]
From the last post, everything seems to be fixed except Druid Skull Bashes.

As a reminder, they use Feral Charge (Cat) leap physics, instead of normal Charge physics.

**Comment by UltraNix** [comment]
I just tested and honestly I see no bugs with Skull Bash. Can you point it?

**Comment by MullichWhitemane** [comment]
https://www.youtube.com/watch?v=3WQwvJhzuFQ 0:33 The druid uses Skull Bash, is treated like a normal charge spell. Later on at 1:35, the video showcases a Retail Bug where you can Skull Bash from unintended places, which was later fixed with this hotfix: (2011-06-29): Feral druids can now use Skull Bash in the Firelands raid. It only seems fair. https://wowpedia.fandom.com/wiki/Skull_Bash

 https://www.youtube.com/watch?v=OOxbH0oL4Q4 In this clip of mine at the start, Skull Bash is used to leap across terrain, which is the physics of Cat Feral Charge only.

**Comment by UltraNix** [comment]
Alright.

**Comment by MullichWhitemane** [comment]
The physics are working correctly now, however, currently, even if there is no proper charge path, the spell will still go through, allowing you to interrupt in situations where you shouldn't be able to. https://www.youtube.com/watch?v=NSw1U7fkb1Q

I've tested with Root and Pacify CCs, and in those cases, Skull Bash is correcly unuseable.

**Comment by MullichWhitemane** [comment]
While Skull Bash doesn't interrupt anymore when a charge path is invalid, there is still an issue. If an invalid charge path is given, and if you use Skull Bash, the ability does absolutely nothing but goes on cooldown and consumes your resource. Both Cat and Bear form are affected.
https://www.youtube.com/watch?v=NUl7hyO4H5w

**Comment by UltraNix** [comment]
This is sick

**Comment by UltraNix** [comment]
Fixed.
