### ISSUE TITLE
Feedback on #1348 [Grim Batol]

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1650]
Forgemaster Throngus - Personal Phalanx debuff is not applied at the correct position,  this should be in a 30 degree angle front of his shield

Dragha still not working as intended when mounted,  He does not continue to cast his fireballs nor summon invocations of flame 
Valionna section - Devouring flames did not hit Tide for 3 seconds while inside the flames 

Erudax -  Faceless Corruptors ,  both spawn but only 1 runs in - the other is stuck at the door.  Shield of Nightmares only affects casters but should affect both melee and casters if faceless corruptor is struck within a 4 second window 

Also achievement "Don't Need to Break Eggs to Make an Omelet" is given even if the eggs are broken

**Comment by WhitemaneSylah** [comment]
[#1348](https://github.com/gamefreedomgit/Maelstrom/issues/1348)

**Comment by WhitemaneSylah** [comment]
Further testing :

Net NPCS have too much HP,  should ideally only have 500
![image](https://user-images.githubusercontent.com/121137397/212318921-12e8bc7f-3dbe-4a1b-892a-1c6a24c4376c.png)

Troggs are now friendly, should be hostile

Twilight Enforcers bladestorm is doing less damage than intended - should do 10k per tick,  on plates its doing 3.2k , cloths 5k

![image](https://user-images.githubusercontent.com/121137397/212320463-9f2af3f4-7c34-4e98-abd2-8ea1848d5a6c.png)
 water bug is back again.,.. this was supposed to be fixed.
 
 General Umbriss can fall through the floor when dragged into this area 
 
![image](https://user-images.githubusercontent.com/121137397/212321047-d47a312b-330d-47d6-a440-db7a97922b82.png)

Forgemaster Throngus;
Shield - Personal Phalanx doesn't give debuff when infront of it 
Flameing shield has the cone but has a 15yard range, should be 100 yard range 
Disorientating roar - Does not get removed from certain abilities, this should be scripted to allow every ability to remove a stack

![image](https://user-images.githubusercontent.com/121137397/212324337-962cbab5-064b-4c40-a8e4-9aace09444fc.png)
if you jump off into the lava you get this error

![image](https://user-images.githubusercontent.com/121137397/212325917-1ca91625-bf14-4c3e-aac0-3187cb51d0b8.png)


Dragha should run to the edge when he hits 30% but he stops to cast Burning Shadowbolt over and over.

Cone direction of Devouring flames is wrong,  should be 150 degrees infront not 360

![image](https://user-images.githubusercontent.com/121137397/212326181-b544183c-d68e-495f-851b-93e0757216dc.png)

![image](https://user-images.githubusercontent.com/121137397/212326619-d4f42e34-2296-4038-a09e-b5f7f2f06da5.png)
Dragons should be here to skip to bosses that have been killed after Umbriss dies, they are missing

![image](https://user-images.githubusercontent.com/121137397/212326862-2a6dfd57-6050-4933-90ac-90e98eeaa512.png)
Dragha doesn't respawn after a wipe

**Comment by WhitemaneSylah** [comment]
Updated test 18.01

Adds;  One add is missing ,  Twilight Wrymcaller, he should patroll this area
![image](https://user-images.githubusercontent.com/121137397/213300472-7dd716a0-8826-41cb-9314-878d569852bb.png)

https://cata-twinhead.twinstar.cz/?npc=48754 - HC version
https://cata-twinhead.twinstar.cz/?npc=39873 - normal version

Erudax NEW BUG FOUND-  Shadow Gale does not show initial safe zone animation ,  This was working in prior tests
![image](https://user-images.githubusercontent.com/121137397/213301003-195b68d8-38db-4082-8242-254bceef6f0e.png)

**Comment by WhitemaneSylah** [comment]
2/3 Dungeon's quest works ( Closing a Dark Chapter and Kill the Courier

Unable to complete the third one Soften them Up, that requires killing 30 Trogg Dwellers with Battered Red Drake , but for some reason, Trogg dwellers are not killable with Battered Red Drakes abillity ( They regenerate hp ) but even if more than one player hit them at once and kill them, it doesn't count for the quest

Trogg Dwellers on the room of Forgemaster Throngus should be moving to the door so players can pull them alone, they're stacked with another pack of adds actually and it will be hard to pull that actually.

Forgemaster Throngus: Disorienting Roar doesn't drop stacks on Healers on most healing abilities ( it should drop 1 stack for each ability you use / cast.

Drahga Shadowburner on the second phase with Valionna, Seeping Twilight stays less than 20s sometimes and Invoked Flame Spirit should be slowed by that zone.

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
Troggs are regenerating health when not hit,  This is part of a quest line and should not regen health

**Comment by WhitemaneSylah** [comment]
#2199 mentioned

**Comment by Aughra23** [comment]
This is not a dupe! This is not in your thread! In a CLOSED issue it was stated that the dragons killed them and were not supposed to and were not found. Mine were found and they attack you while dead.
![WoWScrnShot_022223_162239](https://user-images.githubusercontent.com/125700006/220803197-40c499ee-20a1-4f1d-aaee-0a37c707bf86.jpg)

**Comment by Commander-Rug090** [comment]
Update: 
Players are able to pull random drakes from below the ramparts when getting too close. 

*Twilight wyrmcaller's* take damage from Drakes when players shoot them, they should be immune to damage from drakes. 
additionally when engaged by the players this enemy should spawn a drake to fly down from above (out of thin air), it does not.

*Crimson Seer's* on patrol pack with "Ascended Wyrmcaller" are set as friendly targets, (Wyrmcaller is hostile), they should be hostile. players have reported multiple ads in dungeon are set friendly, but different every run. 

*Twilight Beguiler* in room with **Throngus** when pulled at range, do not move or engage the players but do put the players into combat. 

**Throngus:** damage is  not increased (200%) when he has his mace equipped. 

**Erudax:** 
*"Faceless Corruptor"*: 
 currently, enter the room and moves to the correct position, then begins casting "Twilight Corruption". after they successfully cast this **3** Twilight hatchlings spawn, they then begin channelling again, this continues until no more eggs are left. 

what should happen: 
enter the room and move to the left and right positions and begin to channel "Twilight Corruption" (so far same as current). after finishing the cast **2** Twilight Hatchlings spawn and fly **up** into the air and begin casting periodic "twilight Blasts". 

next the "Twilight Corruption" will cast **"umbral Mending"** on the boss (Erudax), which is interruptible, then pick a random player and begin casting **"siphon Essence"** on a random player, draining 15000 damage per second for 4 seconds (60k damage) and heal itself for 3x the amount 45k per tick or (180k) total. 

Tank PoV: https://youtu.be/IbwimBVAAxM

**Comment by whothatdog** [comment]
can I use this issue? @UltraNix 

there little problems with the NPC (Trash mobs) in the dungeon.
for example Crimsonborne Seer are using their abilities none-stop. the DXE is yelling.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/5325a815-dc35-4986-a9aa-c2f4df6b67fc)

the last boss is too easy because Shadow Gale mechanic is wrong.
I can explain if it matters.
