### ISSUE TITLE
Troggzor the Earthinator - HP and Combat Issues

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Troggzor the Earthinator spawns and fights friendly NPCs (he dies to them if left long enough), and his health is too high.

**How to reproduce:**
Go to 22.60, 56.90 in Deepholm. notice that either Troggzor isn't there (died to NPC), or that he is in combat with them. Also notice his max health is way higher than 107.4k.

**How it should work:**
He should have 107.4k Health as per this video:
https://youtu.be/9E_yUTnYBOo?t=49

**Database links:**
https://www.wowhead.com/npc=43456/troggzor-the-earthinator#comments

**Comment by Afgann** [comment]
fixed
