### ISSUE TITLE
[Quest] Escape from the Lost City

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1652]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After accepting "Escape from the Lost City" in Uldum and freeing the team - I then skipped the cinematic. This caused all the NPCs to be named "Mantaur" and are mountable.

Each time the quest is abandoned and taken again another set of mobs spawn too - could be problematic if lots of players do the quest.

The script also seems off as if you watch the cinematic, they should change into different animals. Also, **skipping the cinematic stops you being teleported to Ramkahen.** - this is the biggest issue as you can't progress

**How to reproduce:**
Accept "Escape from the Lost City" and skip the cinematic.

**How it should work:**
The NPCs shouldn't be mountable.
![Mountable](https://user-images.githubusercontent.com/6482585/210735367-e1ff6696-5d16-4850-a17f-c0d97d9ec3c8.png)

You should be teleported to Ramkahen after skipping the cinematic (or the cinematic shouldn't be skippable).

You should see the event play out properly.

https://www.youtube.com/watch?v=262ag6Mm4Mc

**Database links:**
https://www.wowhead.com/quest=28112/escape-from-the-lost-city

**Comment by UltraNix** [comment]
Fixed.
