### ISSUE TITLE
[Minor] Orsis Survivor Floating

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1654]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At least 3 Orsis Survivors are not Underground and are instead floating above ground.

**How to reproduce:**
.tele Orsis
Fly North
You'll see some Orsis Survivors that are not partially underground like they should be.

**How it should work:**
All Orsis Survivors should be partially underground.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=45715

**Comment by UltraNix** [comment]
Fixed.
