### ISSUE TITLE
[Minor] Pigmys in Orsis

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Orsis, there are a few pigmys - they shouldn't be there. (They are 3 mobs stacked on top of eachother, I've just done the link to one of them)

**How to reproduce:**
.tele Orsis
Fly towards the Pyramid, they are outside the Pyramid next to Prophet Hadassi.

If you can't see them - try going and doing "Theiving Little Pluckers" first and see if that's what makes them appear as I had just done that quest.

**How it should work:**
They shouldn't be there.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28250
https://cata-twinhead.twinstar.cz/?npc=48040

**Comment by UltraNix** [comment]
Fixed.
