### ISSUE TITLE
The Pit of Scales Quest - Not working correctly

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Gorebite doesn't attack when doing the pit of scales quest.

**How to reproduce:**
Accept The Pit of Scales, go to the quest area, Gorebite is summoned but doesn't attack if you let him run into the pit.

Khamen and Thartep also seem bugged and don't attack.

Then if you're stood in the water you take random damage from "Tiny Teeth" - this hurts.

Then when you kill the crocs and Caimas the Pit Master comes down, he also doesn't attack and you can't see the eggs you're supposed to kite him over.

The whole quest script seems a bit broken.

**How it should work:**
https://www.youtube.com/watch?v=ni3dx2aUWlw

**Database links:**
https://www.wowhead.com/quest=27738/the-pit-of-scales

**Comment by MrTide** [comment]
seems like its fixed no complains about it
