### ISSUE TITLE
[Item] [Minor] Ironforge dailies -"0" flavour text at items; fishing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1657]
1. There are several items with "0" as a flavour text (goldish color description)
There should be no flavour text whatsoever. The items are:
[Blind Minnow](https://www.wowhead.com/item=69933/blind-minnow)
[Young Ironjaw](https://www.wowhead.com/item=69932/young-ironjaw)
[Dun Morogh Chicken](https://www.wowhead.com/item=69982/dun-morogh-chicken)
[Sack of Oatmeal](https://www.wowhead.com/item=69985/sack-of-oatmeal)
[Rat Trap](https://www.wowhead.com/item=69980/rat-trap)
[Gnomish Bait-o-Matic](https://www.wowhead.com/item=69978/gnomish-bait-o-matic)

2. Player can fish out Blind Minnow and Young Ironjaw even when not on respective quests. I don't think that should be the case.

**Comment by EdyGlockenspiel** [comment]
Additionally, it seems either the drop rate for these are SUPER low or you can only have one in your bags at a time, either way both would be a bug. The drop rate is supposed to be 30% and the drop rate on Young Ironjaw is supposed to be 7%. I have 2 Young Ironjaw in my bags right now and only one Blind Minnow. Also you can use the Blind Minnow without being in range of Squrky, thus consuming the fish and giving you no credit. 


![image](https://user-images.githubusercontent.com/126888684/234200888-18582460-f2f0-41df-b86b-7f645d1d81f4.png)

**Comment by UltraNix** [comment]
Fixed.
