### ISSUE TITLE
[NPC] Dori'thur - pathing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1658]
[Dori'thur](https://www.wowhead.com/npc=54116/dorithur) is at the ground, on one spot. This lovely owl should be flying around the dome.
Proof:
[comment](https://www.wowhead.com/npc=54116/dorithur#comments:id=1456369)
[Twinstar issue](https://cata-twinhead.twinstar.cz/?issue=7414)
 → the issue says: "NPC should be flying in the air in the temple and in case of engaging Tyrande in battle, it should help her against the Horde (the movement of the NPC based on wowhead map). NPC also does not use its ability [Harsh Moonlight](https://www.wowhead.com/spell=101632/harsh-moonlight)."

**Comment by UltraNix** [comment]
Fixed.
