### ISSUE TITLE
Class mastery not being auto learned

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1660]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can someone check Prot Paladin Mastery is working as intended. I've noticed that the tooltip shows + and - of the mastery and then my block is showing 5% so has not increased by the mastery amount.

**How to reproduce:**
Equip Mastery Gear on a Paladin, notice the mastery values do not change.

![Notice how this shows Zero mastery even though I have 967 rating equiped](https://user-images.githubusercontent.com/6482585/210770853-89483b35-8db0-4090-ae58-eebb457c55be.png)
![Block is showing Zero too](https://user-images.githubusercontent.com/6482585/210771033-8b5cf387-fc5a-409c-b110-048bf3ab2999.png)

**How it should work:**
Mastery should work and should increase Block.

**Database links:**

**Comment by Torpis** [comment]
Disabled Addons and confirmed this issue is still present.

**Comment by Torpis** [comment]
Relogging resolved this (I also visited the class trainer just prior to raising the bug, so this may have required a class trainer visist, and a relog to resolve).

**Comment by WhitemaneSylah** [comment]
Changed to class mastery as this affects every single class

**Comment by Torpis** [comment]
Might also be worth noting that I learned “Plate Specialisation” whilst at the class trainer and I’m positive I’ve learned that before

**Comment by Afgann** [comment]
fixed
