### ISSUE TITLE
Salhet the Tactician - Falling through Floor when entering/exiting vehicle

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1662]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When entering and exiting the vehicle you can fall through the floor and die.

Location: 59.96, 62.34 in Uldum.

**How to reproduce:**
 Accept the quest and talk to Salhet to begin.
Leave the Vehicle and then talk to him again to enter (do this quickly)
I've done this 3 times and fallen through the floor each time - but just try it a few more times in different places if this doesn't make you fall through.

**How it should work:**
You shouldn't fall through the floor.

**Database links:**
https://www.wowhead.com/quest=28277/salhet-the-tactician#comments

**Comment by UltraNix** [comment]
Fixed.
