### ISSUE TITLE
[Moved from Discord] Bladefist Bay quest phasing

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1663]
Hotandspicy
OP
 — Today at 12:58
on the pier right oustide of ogrimmar called bladefist bay is a goblin ship that normally should only be visible for goblins and only when they have the assosiated quest for it . and while iam on the start quest for Vashj'ir (call of duty) i wont get phasing for the incoming ship event - so to speak it is not possible to get to Vashj'ir on any planned way as horde

**Comment by WhitemaneSylah** [comment]
![image](https://user-images.githubusercontent.com/121137397/210788202-93fbffe7-1009-417d-a36c-c72ef4be02e3.png)
![image](https://user-images.githubusercontent.com/121137397/210788216-6c2f5a7e-8d45-4c14-a008-174d3865634a.png)

**Comment by UltraNix** [comment]
#1130
