### ISSUE TITLE
[Moved from Discord] Hyjal Start quest (Horde)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1664]
Hotandspicy
OP
 — Today at 13:13
after i turned in the quest "Warchief's Command: Mount Hyjal!" ID:27721 there is no follow up quest - but there should be 
called : "As Hyjal Burns" ID:25316 
![image](https://user-images.githubusercontent.com/121137397/210788668-d934da26-c41d-451a-b4aa-6a171c56de22.png)

**Comment by Afgann** [comment]
fixed
