### ISSUE TITLE
Caravan Harness - Characters get Stuck

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1665]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can enter Caravan Harness, but then you can't get out. 

**How to reproduce:**
Go to 29.73, 22.38 in Uldum and enter the Caravan Harness - notice you can't get out.

**How it should work:**
Should either not be able to enter the harness, or you should be able to exit the vehicle.

**Database links:**
https://www.wowhead.com/npc=50470/caravan-harness
https://www.wowhead.com/npc=50476/caravan-harness

**Comment by UltraNix** [comment]
Fixed.
