### ISSUE TITLE
[Minor] Mysterious Camel Figurine is Targetable

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1666]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mysterious Camel Figurine should not be targetable.

**How to reproduce:**
Find the Camel - Target It.
![Camel](https://user-images.githubusercontent.com/6482585/210791561-7ba44f53-d322-464d-8d80-9db15eee6039.png)

**How it should work:**
It shouldn't be targetable as per the first/second comment on Wowhead. (Changed in 4.1)

**Database links:**
https://www.wowhead.com/npc=50410/mysterious-camel-figurine#comments
https://www.wowhead.com/npc=50409/mysterious-camel-figurine#comments

**Comment by UltraNix** [comment]
Fixed.
