### ISSUE TITLE
[Quest] Nelf Starting zone (Aldrassil) "Priestess of the Moon" broken for all classes.

### ISSUE THREAD

**Issue by ActionleagueWoW** [gamefreedomgit/Maelstrom#1668]
**Description:**
[Quest] "Priestess of the Moon" is obtained from the respective class trainer after the first few starting quests and is required to continue the Night Elf starting zone Aldrassil. 

This is broken for all 6 starting zone classes. Druid, Priest, Rogue, Hunter, Warrior and Mage. 

NOTE: I originally starting making tickets for all the classes but reduced it to this one as they're all the same named quest, just received from the trainer respective to the class you're playing.

**How to reproduce:**
Lvl any Night Elf class apart from Death Knight to start in Aldrassil, the Nelf introductory zone. Do the first few quests and you will get a quest to speak to your class trainer. Do the class trainer quest and then turn it in to activate the bug, resulting in a broken quest window that is a copy of the quest you just finished. 

**How it should work:**
The broken quest window (that is a copy of the quest you just turned in) should be "Preistess of the Moon", which leads you around to the back of Aldrassil to continue the introductory zone story. Video of all 6 classes unable to continue included.

**Database links:**
Druid - https://youtu.be/O9PgSIbcA1Y
Priest - https://youtu.be/tGyJf3jiwYA
Rogue - https://youtu.be/1ob1vn-If5U
Hunter - https://youtu.be/98VdB5FM83w
War - https://youtu.be/DZHbRTApx30
Mage - https://youtu.be/Vldp2pBYoNM

**Comment by UltraNix** [comment]
Already fixed.
