### ISSUE TITLE
[Quest] Salhet's Gambit - Cannot Complete

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When doing Salhet's Gambit, when the mobs spawn, the Ramkahen Ranger Captain just stands still once you've killed them and does not progress. The quest cannot be completed.

**How to reproduce:**
Accept the quest then talk to the Ramkahen Ranger Captain, he will get to a point - mobs will spawn, kill them, then he just stands there.
![Stuck Ranger](https://user-images.githubusercontent.com/6482585/210810030-2790cf5e-7433-40e8-ba55-c246cdc60b53.PNG)

**How it should work:**
Should progress up the hill then complete.

**Database links:**
https://www.wowhead.com/quest=28486/salhets-gambit

**Comment by UltraNix** [comment]
Fixed.
