### ISSUE TITLE
[Quest] Flamebreaker does not remove the item given after completion 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1675]
Hotandspicy
OP
![image](https://user-images.githubusercontent.com/121137397/210825628-77112db2-eeb4-4b7a-9592-86f297f437fa.png)

 — Today at 14:07
Quest ID: 25323 (Flamebreaker)
Quest Item ID: 53107
Does not get removed from inventory but should be removed automatically
Sylah — Today at 14:07
Screenshot confirming please
:SylahuLove:
Hotandspicy
OP
 — Today at 14:17
Image
i can only give you a screenshot of me having the item but u icant show you that i dont have the quest anymore
if you know what i mena
mean*
Sylah — Today at 14:22
That's perfect I'll move it to BT shortly Hotandspicy Thanks!
Hotandspicy
OP
 — Today at 14:22
happy to help
Torpis — Today at 16:00
I can confirm this too - still in my bags

**Comment by Afgann** [comment]
fixed
