### ISSUE TITLE
(Quest) The Emerging Threat - Desolace

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pretty minor, but the pathing for the quest is a bit choppy and Korrah's Mount is running on air when it should be flying. Quest is still completable.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=14256
Korrah's Mount: https://cata-twinhead.twinstar.cz/?npc=35779
Quest Completion Video: https://www.youtube.com/watch?v=ivqQ2q9O7rM&ab_channel=GitGudGuides

**Comment by MrTide** [comment]
works fine
