### ISSUE TITLE
[Moved from Discord][Warlock Talent] Critical issue with Demonic Circle, and small issues with Dark Intent and Emberstorm

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1677]
liljon
OP
 — Today at 18:39
1/2 Emberstorm only reduces Soul Fire casttime by 0.12 and not 0.13. 2/2 Emberstorm works correctly.

Demonic Circle: Teleport places you out of combat when used. Not sure if it was fixed yet, but this issue existed for other teleport like spells, such as Shadowstep and Blink.

Dark Intent grants 3.05% haste instead of 3%.

**Comment by UltraNix** [comment]
`1/2 Emberstorm only reduces Soul Fire casttime by 0.12 and not 0.13` Clientside visual. 0.01 sec difference...

`Demonic Circle: Teleport places you out of combat when used. Not sure if it was fixed yet, but this issue existed for other teleport like spells, such as Shadowstep and Blink.` And what is the bug?

**Comment by UltraNix** [comment]
`Dark Intent grants 3.05% haste instead of 3%.`
![image](https://user-images.githubusercontent.com/80540499/214578374-72595758-617d-42d5-b1de-01f9f7c9f36d.png)

**Comment by UltraNix** [comment]
No info - closing.
