### ISSUE TITLE
[Quest] Time is Short - missing prerequisite

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1679]
Quest: [Time is Short](https://cata-twinhead.twinstar.cz/?quest=26163)
Issue: Quest giver offered me this quest after I handed in [The Amulet of Sevine](https://cata-twinhead.twinstar.cz/?quest=26168). Before Sevine I have handed in also [The Amulet of Allistarj](https://cata-twinhead.twinstar.cz/?quest=26167). But I have not handed in [The Amulet of Grol](https://cata-twinhead.twinstar.cz/?quest=26169) yet.

This quest should be offred only after you finish all three amulet quests.

**Comment by UltraNix** [comment]
Fixed.
