### ISSUE TITLE
[Quest]Surwich - missing prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1681]
Quest: [Surwich](https://www.wowhead.com/quest=26175/surwich)

Issue: Offered without prerequisites
Should require: [Protecting our Rear](https://www.wowhead.com/quest=26173/protecting-our-rear) → [Watching Our Back](https://www.wowhead.com/quest=26174/watching-our-back)

Proof: https://cata-twinhead.twinstar.cz/?quest=26175 (Requires tab); https://www.wowhead.com/quest=26175/surwich#comments:id=1359240;
https://wowpedia.fandom.com/wiki/Surwich_(quest)

**Comment by UltraNix** [comment]
Fixed.
