### ISSUE TITLE
[Quest] [Important] The Altar of Storms - Loramus not in cave

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1685]
After getting credit for [The Altar of Storms](https://www.wowhead.com/quest=26162/the-altar-of-storms) (defending the body) the player is supposed to hand in the quest to now-revived [Loramus Thalipedes](https://www.wowhead.com/npc=7783/loramus-thalipedes) who should now appear at the cave, next to [Kasim Sharim](https://www.wowhead.com/npc=42298/kasim-sharim).

Issue: After completing the quest I went back to the cave. Loramus is not there. Question Mark is visible on minimap but /tar Loramus does not work. Resetting the game did not work either. This means the player can't hand in the quest and recieve the next ones to finish the quest chain.

**Comment by UltraNix** [comment]
Fixed.
