### ISSUE TITLE
[Quest] Hero's Call's not Opening Follow-Ups - Critical for New Players [ALLIANCE MEGATHREAD]

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1687]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Many instances of Hero's Calls do not open their respective follow ups.

**I'd flag this as Critical as it will put off new players from continuing.**

**How to reproduce:**
28562 and 28562 --- needs to open up 26209 (https://cata-twinhead.twinstar.cz/?quest=28562)
28565 --- needs to open up 25395 (https://cata-twinhead.twinstar.cz/?quest=28565)
28552 --- needs to open up 27210 (https://cata-twinhead.twinstar.cz/?quest=28552)
28576, 27158, 28505 and 28749  --- needs to open up 27159 (https://cata-twinhead.twinstar.cz/?quest=28576)
28582 --- needs to open up 27963 ((https://cata-twinhead.twinstar.cz/?quest=28582)
28673 ---  needs to open up 25710 (https://cata-twinhead.twinstar.cz/?quest=28673)
27726 ---  needs to open up 25316 (https://cata-twinhead.twinstar.cz/?quest=27726)
27724 ---  needs to open up 14482 (https://cata-twinhead.twinstar.cz/?quest=27724)
28503 ---  needs to open up 25486 (https://cata-twinhead.twinstar.cz/?quest=28503)

All the other Alliance Hero's Calls seem to be working as expected as I've tested them all!

**How it should work:**
All the above ID's should open up the following IDs.

**Comment by WhitemaneSylah** [comment]
#1688 
#1689
#1690 
#1691 

Compiled for easy viewing

**Comment by Torpis** [comment]
Merged them all together into the initial comment.

**Comment by Afgann** [comment]
fixed
