### ISSUE TITLE
[Quest] Hero's Call: Dustwallow Marsh! not Opening Follow-Ups - Critical for New Players

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1689]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hero's Call: Dustwallow Marsh! should open up 

**I'd flag this as Critical as it will put off new players from continuing.**

**How to reproduce:**
Take Hero's Call: Dustwallow Marsh(Quest 28565) then hand in. No follow up is given.

**How it should work:**
Quest 27210 should then be offered but isn't.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28552
https://cata-twinhead.twinstar.cz/?quest=27210

**Comment by WhitemaneSylah** [comment]
Compiled on report #1687
