### ISSUE TITLE
[Quest] Hero's Call: Searing Gorge! not Opening Follow-Ups

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1691]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hero's Call: Searing Gorge! should open up A New Master... But Who?

**I'd flag this as Critical as it will put off new players from continuing.**

**How to reproduce:**
Take Hero's Call: Searing Gorge! (Quest 28582) then hand in. No follow up is given.

**How it should work:**
Quest 27963 should then be offered but isn't.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28582
https://cata-twinhead.twinstar.cz/?quest=27963

**Comment by WhitemaneSylah** [comment]
Compiled on report #1687

**Comment by Greywolf59** [comment]
Can confirm with my older post https://github.com/gamefreedomgit/Maelstrom/issues/1474
