### ISSUE TITLE
[Minor] Scroll of Recall - Not Randomly Teleporting

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When using the Scroll of Recall above level 40, it should randomly teleport you. It currently seems to just keep you in your current location.

**How to reproduce:**
Use a Scroll of Recall at level 85, if it fails, you'll just stay where you are (or I did anyway)

**How it should work:**
Should be teleported to a random location.

**Database links:**
https://www.wowhead.com/wotlk/item=37118/scroll-of-recall

**Comment by UltraNix** [comment]
Fixed.
