### ISSUE TITLE
[NPC] Lor'danel Sentinels

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1694]
Video from 6:10: https://www.youtube.com/watch?v=sFTopf7rb4g
[Lor'danel Sentinel](https://www.wowhead.com/npc=142317/lordanel-sentinel)
All the sentinels in Lor'danel are dead, they shouldn't be.
At least two of the mounted ones are standing on spot in the air and they are burning with always refreshing [Flame Arrow](https://www.wowhead.com/spell=64439/flame-arrow). I guess they are shooting themselves (lol).
Also the one on the video that comes when player hands in [Breaking Waves of Change](https://www.wowhead.com/quest=26385/breaking-waves-of-change) did not come iirc.

**Comment by Greywolf59** [comment]
Update: In the next phase, that is I believe activated by taking [The Boon of the Seas](https://www.wowhead.com/quest=13520/the-boon-of-the-seas) and leaving the area, the Sentinels are alive and well.
Note to the Phase: On PTR leaving the zone of Lor'danel is not enough. When I returned the quest giver of this quest was on two spots at once.  After restarting the game the phase changed properly.

**Comment by UltraNix** [comment]
Fixed.
