### ISSUE TITLE
[Quest] The Last Wave of Survivors - missing sentinels

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1696]
Quest: [The Last Wave of Survivors](https://www.wowhead.com/quest=13518/the-last-wave-of-survivors)
Info: On interaction with each NPC of the objective, a sentinel should appear and save him/take him to the village.
Video: https://www.youtube.com/watch?v=sFTopf7rb4g  9:45 - 12:15
Issue: two of the sentinels won't spawn, the one at [Gershala](https://www.wowhead.com/npc=32911/gershala-nightwhisper-rescued) and the one at [Volcor](https://www.wowhead.com/npc=33094/volcor-rescued) iirc.
I am sorry, I have no idea what their respective IDs are.

**Comment by UltraNix** [comment]
Fixed.
