### ISSUE TITLE
[Quest] Burnin' at Both Ends - Can't Hand In

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1698]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can't hand in Burnin' at Both Ends - the NPC isn't located in the turn in spot.

**How to reproduce:**
Complete the quest and then go to the hand-in location, NPC isn't there. (Looks to potentially be a Phasing issue)
![image](https://user-images.githubusercontent.com/6482585/211069557-d7b23d85-9f0d-4b00-90f8-a04fe89c6e3d.png)

**How it should work:**
Fargo Flintlocke should be there to turn in.

**Database links:**
https://www.wowhead.com/quest=28597/burnin-at-both-ends

**Comment by MrTide** [comment]
He is correct, NPC is in different phase

**Comment by MrTide** [comment]
resolved
