### ISSUE TITLE
[Quest] In Defense of Darkshore - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1703]
In [Defense of Darkshore](https://www.wowhead.com/quest=13885/in-defense-of-darkshore) is undoable.
Player is supposed to speak with [Orseus](https://www.wowhead.com/npc=34392/orseus) and borrow a hippogryph from him.
The chat option to borrow one is there but nothing happens when player clicks it. This quest is not doable without the hippogryph
Video of working quest: https://www.youtube.com/watch?v=dlLUYWcsu8c

**Comment by UltraNix** [comment]
Fixed.
