### ISSUE TITLE
[Dungeon] Shadowfang Keep NORMAL issues

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1707]
Haunted Stable Hand at the start should be hostile

The mobs in the kitchen that don't have a proper patrol set wander around aimlessly instead of focusing on their tasks

Baron Ashbury - Pain and Suffering damage does not increase over time, Stay of Execution is not interruptible / silenceable

The levers on Ashbury cells are placed wrong

Love is in the Air event objects are spawned 

Haunting Spirits from Haunted Servitor-s have no effect

The allied NPCs instantly teleport in instead of having a proper intro sequence after killing Silverlaine

Same allied NPC teleport issue as Springvale

Bloodfang Berserkers are spawned in at Lord Walden while he's alive

The dead Bloodfang Bersekers should be actually dead and not just fully healed but inactive npcs

Godfrey uses Pistol Barrage in normal (heroic only spell), Cursed Bullets isn't interruptible

 
Refer to #1425  and  #1375

**Comment by Afgann** [comment]
fixed
