### ISSUE TITLE
[Quest][Cata] Colossal Guardians

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1711]
**How to reproduce:**
 [Stone of the Sun] [Stone of the Moon] are lootable without the quest
 and can't turn in the quest after getting the items
 i had to try .quest complete command to be able to turn it in, its possible that looting the quest items before hand causes this issue

**How it should work:**
quest items should be lootable with the quest
and be able to turn in the quest afterwards

**Comment by Torpis** [comment]
Yeah I looted them after taking the quests and had no issue - I think the mobs weren’t even visible before I took the quest but can’t fully remember.
