### ISSUE TITLE
[Quest][Cata]  Salhet the Tactician

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1712]
**How to reproduce:**
Quest simply is not working.. fear stops the attack, you can't move your lions simply "move" doesn't work and your lions can't kill anything since npcs are healing and if you try to get out of the event you fell underground and die
![image](https://user-images.githubusercontent.com/36106057/211170360-c7fd60d3-f338-4ad1-ba0b-07dae2ad2684.png)

**How it should work:** like this video:  
https://www.youtube.com/watch?v=IvZCGsNgHRA

**Comment by Torpis** [comment]
#1661 is linked to this

**Comment by UltraNix** [comment]
Fixed.
