### ISSUE TITLE
[Quest][Cata]  Make Yourself Useful

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1717]
**How to reproduce:** once npcs that were sleeping go hostile they dont wake up just stand on the ground "sleeping" and keep hitting you and once you make a little bit of distance they don't  follow you to fight you
also it should be easier to motivate them, they rarely listen and get back to work
also if players decide to not kill them they dont reset so it will cause issues for players to do that quest later on
![image](https://user-images.githubusercontent.com/36106057/211172885-7a858e16-89c8-4f71-865f-442c34af1a35.png)

**How it should work:**
like the video below
https://www.youtube.com/watch?v=xAz4zoKvGlo

**Comment by s71n63r** [comment]
All Slacking Laborers are hostile. Quest cannot be completed.

[Whitemane 2_28_2023 16_23_24](https://user-images.githubusercontent.com/125290607/221995199-c5feb9a2-d8dc-48c6-a1c6-e3c597c484f6.png)

**Comment by MrTide** [comment]
new problem
disguise is not doing anything sadly, creatures are still hostile after using it

**Comment by alexspew** [comment]
Fixed, was wrong factionid on the creatures. -- alex
