### ISSUE TITLE
[Quest][Cata] Battlezone

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1718]
**How to reproduce:** by the look of it quest is not fully scripted, watchers are not fighting anyone 
![image](https://user-images.githubusercontent.com/36106057/211173150-2ed424c2-2f1e-4bd2-9943-41b450cd8fae.png)

after riding the siege tank for a while it dismounts you and causes you to phase out from the area so even if you manage to kill them all (even after getting the tank again) when you try to go back to the schnottz like quest wants you to, the house that he is in on wont explode (because you are not in correct phase i believe)
![image](https://user-images.githubusercontent.com/36106057/211173463-67ffdc6f-07cd-4d48-a249-730c3f0529c4.png)

also slacking laborer, schnott'z landing laborer (i am not sure if these are the same npcs that are fighting the watchers) creatures should phase out once you accept this quest, the npcs that you used on previous quests because they might cause issues since you can displace them using your cannon

**How it should work:** like the video below
https://www.youtube.com/watch?v=FcsSUY8h2gQ
https://www.youtube.com/watch?v=ENxqxxDzy8w

**Comment by Greywolf59** [comment]
Can confirm this issue is still present.

**Comment by UltraNix** [comment]
Fixed.
