### ISSUE TITLE
[NPC] [Pathing] Huntress Ravenoak

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1723]
1. [Huntress Ravenoak](https://www.wowhead.com/npc=14379/huntress-ravenoak)
- She is standing next the cooking dailies hut, she should be patrolling around Darnassus (wowhead map)

Also I think [Darnassus Sentinels](https://www.wowhead.com/npc=4262/darnassus-sentinel) on hippogryphs should probably fly around and not hover on one spot all the time but I can't provide any proof for that at the moment.

**Comment by UltraNix** [comment]
Fixed.
