### ISSUE TITLE
Den grunts deal no damage

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#1727]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The guards from Valley of Trials ''Den Grunt'' deal no damage

**How to reproduce:**
Just get any character alliance and make them attack you

**How it should work:**
They should deal more damage

**Database links:**
https://www.wowhead.com/npc=5952/den-grunt

**Comment by WhitemaneSylah** [comment]
Confirmed
