### ISSUE TITLE
[Quest][Cata] Salhet's Gambit

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1732]
**How to reproduce:**
encounters spawns/ambushes are incorrect and Quest is not working after first fight they didn't move at all
Ramkahen ranger captain didnt fight neither
couldnt finish the quest 
![image](https://user-images.githubusercontent.com/36106057/211214217-6d752db1-b670-4367-8c72-0fa262eb50d8.png)

**How it should work:** like this video : https://www.youtube.com/watch?v=IWgr52KZwpI

**Database links:**

**Comment by Torpis** [comment]
Linked to #1671
