### ISSUE TITLE
[Dungeon] Ragefire Chasam - Issue list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1734]
Alliance quest givers do not spawn

Molten Elemental's fire shield sometimes does not hit if the target is nearby,  possibly taking elevation into consideration https://cata-twinhead.twinstar.cz/?spell=3054

Taragaman The Hungerer - Displayed as a humanoid - should be demon 
![image](https://user-images.githubusercontent.com/121137397/211219096-68707e23-fd55-4c53-aa5e-65a72b5cbf46.png)
https://cata-twinhead.twinstar.cz/?npc=11520

Bazzalan -  Also showing as humanoid , should be demon https://cata-twinhead.twinstar.cz/?npc=11519

**Comment by Afgann** [comment]
first issue is invalid:
https://www.youtube.com/watch?v=O9aYXF11DhY
there is no npcs in alliance version in the video, player earns gilneas reputation added in 4.0.3, so i'm 99.9% sure that video is from cataclysm

the rest of the issues are fixed
