### ISSUE TITLE
[Dungeon] Blackfathom Depths issue list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1736]
https://cata-twinhead.twinstar.cz/?npc=6243#drop - Gelihast has no loot table

https://cata-twinhead.twinstar.cz/?npc=12902 Lorgus Jett has no loot table

Twilight Lord Kelris - constantly has nature casting animation when engaged in combat - low prio 
![image](https://user-images.githubusercontent.com/121137397/211221418-914de441-fdd3-4128-b38e-5eed5f5140b6.png)

**Comment by Afgann** [comment]
fixed
