### ISSUE TITLE
[Quest][Cata]  Hacking the Wibson

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1737]
**How to reproduce:** you need to retrieve the quest item called  [Maintenance Axe] to complete the quest i believe it should be a requirement also you dont have any animation while destroying the wibson mainframe device

**How it should work:** like this video : https://www.youtube.com/watch?v=Rk7F1w_kZzo

**Comment by DorizarN** [comment]
Tested today, it's indeed broken!

**Comment by UltraNix** [comment]
Fixed.
