### ISSUE TITLE
[Quest][Cata] Gnomebliteration

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1738]
**How to reproduce:** if you accept the quest while mounted, quest bugs out you can't do the quest anymore until you relog or leave the area and come back again
![image](https://user-images.githubusercontent.com/36106057/211223832-5e1bf9af-71f8-4d25-b41b-aafbcbedf8d5.png)
![image](https://user-images.githubusercontent.com/36106057/211223866-713cb18c-bf3a-47dd-8871-09793f6a475f.png)

**How it should work:** you should be able to start the quest shapeshift or mounted it should not make any difference .
https://www.youtube.com/watch?v=56nF4mXFquc

**Comment by UltraNix** [comment]
Fixed.
