### ISSUE TITLE
(Quest - H) Nine's Plan - Azshara

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1741]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After accepting the quest, the player should be able to go to the building where the Secret Rocket Plans are and click a Door Buzzer to open the door and spawn the Mutant Goblin inside. There currently is no buzzer to click on, the quest cannot be completed.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=14408
Quest Completion Video: https://www.youtube.com/watch?v=fggpEl_Ad6I&ab_channel=GitGudGuides
Door Buzzer (Object): https://cata-twinhead.twinstar.cz/?npc=36472
Mutant Goblin: https://cata-twinhead.twinstar.cz/?npc=36156

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/220411319-caab3846-cc8a-44d7-95ad-10ac7014380e.png)
Works okay.
