### ISSUE TITLE
Quest "The name never spoken" missing flame pillars - questID 25412

### ISSUE THREAD

**Issue by BishopHimself** [gamefreedomgit/Maelstrom#1742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)https://www.wowhead.com/quest=25412/the-name-never-spoken
[//]: # (cata-twinhead.twinstar.cz)https://cata-twinhead.twinstar.cz/?quest=25412

**Description:**
The quest in Hyjal called "The name never spoken" can not be completed because the flame pillars are missing on the map. They are required for this quest and this chain because we need to read them to complete quest. 

**How to reproduce:**
Go to "The Inferno" in the far left part of Hyjal and the flame pillars that should be there are missing.

**How it should work:**
https://www.youtube.com/watch?v=JYrKoZhaIXE
This video shows firestones which are required for completing this quest.

**Database links:**

**Comment by MrTide** [comment]
Player is correct they are missing

**Comment by JadedNate** [comment]
Can confirm all three pillars are still missing.

**Comment by GMHiki** [comment]
this is correct, they are in the wrong phase, or upon taking this quest, the player is not forwarded to the right phase.

**Comment by Afgann** [comment]
fixed

**Comment by Greywolf59** [comment]
@Afgann 
Ehm, a "small" problem with the fix. Blackhorn (qeustgiver) and all the NPCs in Grove of Aessina and around are now not visible. Quest itself is doable (not able to hand in though).

**Comment by Afgann** [comment]
fixed
