### ISSUE TITLE
Plate specialization learned at level 2

### ISSUE THREAD

**Issue by RHawtin** [gamefreedomgit/Maelstrom#1746]
**Description:**
Got plate specialization on wargen warrior at level 2

**How to reproduce:** Make new char and hit few mobs til you get level 2 xD

**How it should work:**
Well for some reason i thought you get plate specialization at level 40, now i checked  
https://cata-twinhead.twinstar.cz/?spell=86525 and it says at level 50. I'm sure you know better. It's definitely not at level 2 though 

**Database links:** https://cata-twinhead.twinstar.cz/?spell=86525

**Comment by Afgann** [comment]
fixed
