### ISSUE TITLE
[Dungeon] Zul'Farrak - Cant do Last Boss

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1747]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Weegli Blastfuse doesn't blow up door to last boss after completing event

**How to reproduce:**
Enter ZF and free them from their cages, the event is well scripted - except Weegli doesn't open the door. I started by talking to Sergeant Bly and then spoke to Weegli just before Bly turned hostile.

![image](https://user-images.githubusercontent.com/6482585/211324881-d6f10ce7-270b-47ea-a0d4-1a6643d86d1a.png)

**How it should work:**
Weegli should blow up the door.

**Database links:**
https://www.wowhead.com/classic/npc=7607/weegli-blastfuse

**Comment by Torpis** [comment]
Speaking to the Golbin first stops this bug from occuring.

**Comment by MrTide** [comment]
seems to be working now
