### ISSUE TITLE
[Quest] Urgent Delivery! - unavailable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1748]
Quest: [Urgent Delivery](https://www.wowhead.com/quest=9409/urgent-delivery)
Issue: Should be available to all classes, worgens sometimes had issues. As human I was offered this quest but when I clicked accept, I did not get the quest and it disappeared.
Video of dwarf doing it (later patch): https://www.youtube.com/watch?v=9BQcqegJhYk
There is also a video of human doing it.

**Comment by Greywolf59** [comment]
Update: This same issue described in orginal post also occurs for draeneis, making the levelling in the zone pretty much undoable (thanks god for xp rate 3x), since it is the third quest in the zone questline.
I suggest elevating this issue from High to Critical Priority.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Greywolf59** [comment]
It works for Draeneis now, yes, however it should be available to all Alliance classes. Just a minor thing though.
https://www.wowhead.com/quest=9409/urgent-delivery#comments:id=254541
https://wowpedia.fandom.com/wiki/Urgent_Delivery!#Progression

**Comment by UltraNix** [comment]
Alliance classes or races?

**Comment by Greywolf59** [comment]
Oh, right, races, sorry.
