### ISSUE TITLE
(Quest - H) Trial of Frost - Azshara

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1753]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Once taking the portal to the Trial of Frost, the player should be able to collect 20 Essence of Ice to complete the quest while trying to avoid the environmental damage surrounding the platform. Currently, there are no runes, no rotating Frostburns and no Essences of Ice. The quest cannot be attempted/completed.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=24478
Quest Completion Video: https://www.youtube.com/watch?v=ljNzols-yVQ&t=3s&ab_channel=GitGudGuides
Essence of Ice (object): https://cata-twinhead.twinstar.cz/?object=195651

**Comment by UltraNix** [comment]
Fixed.
