### ISSUE TITLE
[Server CRASH][Quest][Cata]  On Second Thought, Take One Prisoner

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1755]
**How to reproduce:** one version of NPC Mor'norokk the hateful id:42801 is not on the ship and he causes the server to crash once you try to do the quest also his damage seems really low i believe he is a caster and should cast shadowbolt which he is not  https://cata-twinhead.twinstar.cz/?npc=42801
Note: he is also on the ship the one that is not causes server to crash
![image](https://user-images.githubusercontent.com/36106057/211430674-22df292b-4a77-41ab-97d6-69d0cee2c11d.png)
![image](https://user-images.githubusercontent.com/36106057/211429430-dad142e5-60d5-4397-95ce-25bfceba5f24.png)

**How it should work:** he should be on the ship like this video:  https://www.youtube.com/watch?v=zFSiMuPBMek

**Comment by Afgann** [comment]
fixed
