### ISSUE TITLE
Quest Phasing in Western Plaguelands

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1757]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Alliance Laborers needed for the quest are not spawned. Unsure if this is a phasing issue.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=26933
Quest Completion Video: https://www.youtube.com/watch?v=QWTcAfA5rnI&ab_channel=WorldOfWarcraftGuidesAndGameplay
Alliance Laborer: https://cata-twinhead.twinstar.cz/?npc=45047
(unsure which) https://cata-twinhead.twinstar.cz/?npc=44433

**Comment by JadedNate** [comment]
I believe it was a phasing issue, or maybe related to most quests not needing pre-requisites to be completed. I turned in Strange New Faces and accepted When Death is Not Enough and the mobs have appeared :'D

**Comment by JadedNate** [comment]
After completing every quest I could in WPL, there were only 36 quests I was able to complete out of 54. There were a few phasing issues, the one listed above, there are a few missing/phased mobs in Andorhal (I'll try to list what I can here)

Quests I wasn't able to accept:
The Reckoning - https://cata-twinhead.twinstar.cz/?quest=27144
Andorhal, Once and For All - https://cata-twinhead.twinstar.cz/?quest=27090
Into the Woods - https://cata-twinhead.twinstar.cz/?quest=27683
A New Era for the Plaguelands - https://cata-twinhead.twinstar.cz/?quest=26999
Northridge Lumber Mill - https://cata-twinhead.twinstar.cz/?quest=26935
Learning the Ropes - https://cata-twinhead.twinstar.cz/?quest=27000
This Means WAR (Wild Arachnid Roundup) - https://cata-twinhead.twinstar.cz/?quest=27001
An Audience with the Highlord - https://cata-twinhead.twinstar.cz/?quest=27002

*Andorhal Defenders don't give kill credit for the quest Supporting the Troops. (Wrong ones phased?)
Quest: https://cata-twinhead.twinstar.cz/?quest=27085
Andorhal Defenders: https://cata-twinhead.twinstar.cz/?npc=44448

*Andorhal Force-Commanders are phased and cannot be killed for completion of Ashes to Ashes.
Quest: https://cata-twinhead.twinstar.cz/?quest=27086
NPCs: https://cata-twinhead.twinstar.cz/?npc=44450

**Comment by JadedNate** [comment]
Y'know what, I missed a quest at the Bulwark and I think I might be mentally challenged, so Imma just close this :'D

**Comment by PanJanuszek** [comment]
Fixed 29.12.2023
