### ISSUE TITLE
[NPC] [Cata] Energized Geode

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1758]
**How to reproduce:** Energized Geode keep you in combat forever once you get hit by its lightning even tho you didnt attack it
![image](https://user-images.githubusercontent.com/36106057/211432960-4ee35555-7240-4f5a-a3ee-c788f9f5a28b.png)

**How it should work:** it should not keep you in combat even tho if you leave its area

**Comment by UltraNix** [comment]
Fixed.
