### ISSUE TITLE
[Quest][Cata] Quicksilver Submersion

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1761]
**How to reproduce:** Player doesn't need to do the quest you can just turn it in
even if you try to do the quest its not possible, i believe its not scripted at all
![image](https://user-images.githubusercontent.com/36106057/211435155-d38f45b6-bcd8-4b5c-bb23-ea75bee98f2d.png)

**How it should work:** you should do the quest 
https://www.youtube.com/watch?v=qapm9-umGQg

**Comment by Greywolf59** [comment]
Yup, confirmed, quest is missing its objective. Dunno if scripted or not, however [Trogg Crate](https://www.wowhead.com/object=205197/trogg-crate) that is essential to triggering the quest event is missing. Also this quest (as many others in the questline) should be handed in via comm, which is not the case and player has to return to the NPC in the Temple.

**Comment by UltraNix** [comment]
Fixed.
