### ISSUE TITLE
[Quest][Cata][NPC] Troggzor the Earthinator

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1763]
**How to reproduce:**
there is a earthen champion miss placed and keep killing the quest npc  troggzor the earthinator 
![image](https://user-images.githubusercontent.com/36106057/211440607-92fa1c17-569c-4f37-b842-91502d56366a.png)

**How it should work:** there shouldn't be any earthen champion up there
https://www.youtube.com/watch?v=85mjzhkJ3CE

**Comment by Afgann** [comment]
fixed
