### ISSUE TITLE
[Quest] [NPC] [Cata] Close Support

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1764]
**How to reproduce:** catapult that you build wont stop and fight and npcs that follow him do nothing, also you can summon infinite catapults which will cause issues 
![image](https://user-images.githubusercontent.com/36106057/211440953-8923451e-745a-4072-b841-052e1e25debe.png)
![image](https://user-images.githubusercontent.com/36106057/211441142-b7e33de3-7308-4126-9ae7-8855492724f8.png)

**How it should work:** like this video https://www.youtube.com/watch?v=LGvjgixT1nU
you should not be able to summon more catapults as long as you got one

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
