### ISSUE TITLE
[Quest][Cata][NPC] Keep Them off the Front

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1765]
**How to reproduce:** some catapults are missing, there are not any incoming waves to kill and so on.. event is not scripted properly. i believe its because ads don't get one shootted by your catapults and also friendly ads dont have the damage to kill them so at some point they stop spawning until you kill more.
here is my suggestion: let the friendly npcs kill them and reduce the respawn timers to 30sec instead of 3min so waves keep coming in.
![image](https://user-images.githubusercontent.com/36106057/211443325-4367c57e-3493-4c0b-bb26-652894aa3eba.png)

![image](https://user-images.githubusercontent.com/36106057/211441857-6217c4a3-86a5-429c-a8f3-12e971119171.png)

**How it should work:** like this video: 
https://www.youtube.com/watch?v=5TScdV-6q7E

**Comment by MrTide** [comment]
update: its even worse now ![image](https://user-images.githubusercontent.com/36106057/229355325-2f944e6e-330f-4337-a81f-c2d1b97a4e2e.png)

**Comment by UltraNix** [comment]
Fixed.
