### ISSUE TITLE
(Quest - H) Ace in the Hole (WPL)

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1766]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After "Hunting Thassarian" for the quest, the player should see the corpse of Lurid on the floor outside the tower on the Western part of Andorhal. Lurid is currently either missing or phased out or something; The quest cannot be completed.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=27089
Quest Completion Video: https://www.youtube.com/watch?v=BmGs9IqZAiU&ab_channel=GitGudGuides
Lurid: https://cata-twinhead.twinstar.cz/?npc=45129#

**Comment by UltraNix** [comment]
Fixed.

**Comment by Kownaco** [comment]
Description:

Doesn't work again, "Hunt Thassarian" doesn't get marked when you get to Lurid. I tried many things: relog, retake quest, relog before attempting getting to NPC to get flag, flying to NPC straight, getting there on foot, killing all mobs on the way so the "Enthralled Val'kyr" doesn't get jammed on mobs, moving around the target NPC all around the place. Nothing works.

How to reproduce:

Get to Lurid, don't get "Hunt Thassarian" flag.

How it should work:

"Hunt Thassarian" should get marked when you get to Lurid. Above links of videos show when it should happen.
