### ISSUE TITLE
[Quest][Alliance] - Call of Duty - Urgent, blocking Vashj'ir progress

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1768]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Call of Duty cannot be handed in & double ships at Dock

**How to reproduce:**
**Bug 1 - Urgent** 
Call of Duty can now be completed, but cannot be handed in. There is a bug with the quest where the end NPC ([Erunak Stonespeaker](https://www.wowhead.com/npc=36915/erunak-stonespeaker)) doesn't transport you to the hand in spot - but even moving there manually the quest giver is not there to hand the quest in to.

https://youtu.be/FEcLfCeP4Sk?t=511 - this is what should happen

Could be a phasing issue due to the fact Erunak doesn't teleport you to "The Briny Cutter" (the upside down boat underwater). This can be confirmed by doing .tele Legionsfate (or .tele Seafarerstomb) then swimming straight up. You will be grabbed by the tenticles again showing you are still in that phase.

I attempted to do this quest twice, and got the same issue both times.

**Bug 2 - Minor**
The Boat to Northrend still turns up when phased into the quest - this shouldn't happen.

![image](https://user-images.githubusercontent.com/6482585/211490187-9b628c9d-1aad-43d3-9b4e-5576f1f2dd83.png)

**How it should work:**
Quest NPC should be there for hand in.

**Database links:**
https://www.wowhead.com/quest=14482/call-of-duty

**Comment by WhitemaneSylah** [comment]
#1797
