### ISSUE TITLE
[Quest] By the Light of the Stars

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1769]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
By the Light of the Stars randomly takes you out of the phase. You then need to equip and unequip the helm provided to get back into the phase.

**How to reproduce:**
Accept Quest
Start to do quest, I found myself taken out of and into the phase even though I didn't have helm equiped.
Equiping and unequiping took me back into the correct phase.

**How it should work:**
The helm shouldn't need to be equiped https://www.wowhead.com/item=61509/sapphire-spectacles#comments - you just need it in your bags.

**Database links:**
https://www.wowhead.com/quest=27549/by-the-light-of-the-stars
https://www.wowhead.com/item=61509/sapphire-spectacles

**Comment by Clintmega** [comment]
In my phase the Tormented Grave Robbers for [Be Prepared](https://www.wowhead.com/quest=27517) were already spawned, 5-6 on top of each other and invincible.

**Comment by MrTide** [comment]
works fine no complains about this quest

**Comment by mserkanoz** [comment]
It shifts me out of the phase but keeps me stuck in combat, therefore I cannot equip/unequip the spectacles. When I ALT+F4 (because logging out is not possible while in combat) and login again, I find myself already dead. Level 85 Human Mage.
