### ISSUE TITLE
[Paladin][Ret] Guardian Of Ancient Kings / Judgements of the Bold / Long Arm of the Law issue

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1775]
Two more bugs with Ret Paladin:
- Guardian of Ancient Kings has an assist function, but not an attack function - essentially, he just stands around looking pretty.
- Judgements of the Bold and Long Arm of the Law do not proc on Absorb effects.

**Comment by MullichWhitemane** [comment]
To better visualize Guardian Angel behaviour: https://www.youtube.com/watch?v=5x1pMJKc6uc

**Comment by MullichWhitemane** [comment]
Judgments work fine now, but Angel still has some issues.

On the target dummy, Angel can't upkeep combat, and without the player's intervention, they will drop combat. https://www.youtube.com/watch?v=X-dPevHh75w

Not sure what triggers this, but in PvP combat, the Angel sometimes decides to take a breather for the remainder of his existence. https://www.youtube.com/watch?v=3R5uCuSrF2s

**Comment by UltraNix** [comment]
You mean the Guardian should keep always in combat with dummy?

**Comment by MullichWhitemane** [comment]
> You mean the Guardian should keep player always in combat with dummy?

Yes. Any pet action should place its owner into combat.

**Comment by MullichWhitemane** [comment]
Guardian Angel now correctly keeps you in combat, and is behaving much better in PvP, but still not perfect in PvP. https://www.youtube.com/watch?v=Swjh9SJSxsg

He struggles at sticking to his targets.
