### ISSUE TITLE
[Quest] [Important] Arcane Legacy - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1779]
Quest: [Arcane Legacy](https://www.wowhead.com/quest=25766/arcane-legacy)
Issue: Throwing [Highborne Prison](https://www.wowhead.com/item=55972/highborne-prison) near ghosts does not spawn anything, it just kills them.
Ghosts to use item at: [Highborne Sorcerer](https://www.wowhead.com/npc=34932/highborne-sorcerer), [Charlatan](https://www.wowhead.com/npc=34931/highborne-charlatan), [Citizen](https://www.wowhead.com/npc=34938/highborne-citizen)
It should kill the ghosts and summon spirits on random. Either guardian [Bound Highborne Spirit](https://www.wowhead.com/npc=41232/bound-highborne-spirit) for quest credit or hostile [Enraged Highborne Spirit](https://www.wowhead.com/npc=41231/enraged-highborne-spirit).
Seems like part of the main Stonetalon storyline that can't be continued without this or at least it would lead to skipping lot of other quests.
Video: https://www.youtube.com/watch?v=GLrF5PrSHS4

Note: Sorceres are notin the channeling pose as on video, the Prison does not have opening animation.
Note 2: The Pison can be used to kill any neutral or hostile creature in Stonetalon. **It can also kill the player that used it if he walks too near to it.**

Putting Stonetalon Mountains Report on hold until this gets fixed.

**Comment by UltraNix** [comment]
Fixed.
