### ISSUE TITLE
[Event][Quest] [NPC] [Cata] On Even Ground and Crumbling Defenses

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1782]
**How to reproduce:** On Even Ground and event in area is not scripted properly at all
i don't see any fighting going and your grapple line dont work on servant of therazane
when it comes to "Crumbling Defenses" mylra dimblaze and winterbluff you just go and click on them to get the credit its not how its supposed to work, i believe its like that because event is not scripted at all
![image](https://user-images.githubusercontent.com/36106057/211670553-e942e54a-20fd-4dab-aafd-b36d11e60a81.png)

**How it should work:** there should be some fights going on between friendly units and npcs around them and also you should be able to use your grapple and servant of therazane should throw rocks around (they basically do no damage to you on melee neither)
more details about the event can be seen in these videos below:
this is how On Even Ground should work
https://www.youtube.com/watch?v=zCV0ed2CEBc
and this is how Crumbling Defenses should work
https://www.youtube.com/watch?v=LWlK5R0rSlE

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
1. On Even Ground Using the quest item doesn't give you credit and servant is almost doing no damage to the players still and they are not throwing rocks
![image](https://user-images.githubusercontent.com/36106057/221385519-4ff96ad4-c44b-4585-8c7c-d5d3c0ddf36f.png)
2. Crumbling Defenses doesnt give you credit neither and markers are also missing

**Comment by UltraNix** [comment]
`they are not throwing rocks` Won't fix.

**Comment by MrTide** [comment]
Update:
On Even Ground doesnt show on middle of the screen that you got credit for the quest which might lead to confusion and servants are also not throwing rocks like the video but other than that looks fine
Crumbling Defenses seems fine
Up to you if you wanna close or not
thank you.

**Comment by UltraNixx** [comment]
The Rock spell is hard to find.

**Comment by UltraNix** [comment]
`On Even Ground doesnt show on middle of the screen that you got credit for the quest which might lead to confusion` Requires delete cache.
