### ISSUE TITLE
Death and decay not generating threath and not aggroing mobs when used on then

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1785]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Death and decay spell is not aggroing mobs ans bosses when used on them.
![00A424A2-73CC-40D1-B2D5-C1042F0ACE65](https://user-images.githubusercontent.com/35288643/211679170-0b42ce91-8e11-40fe-b1c0-83087cc75496.jpeg)

**How to reproduce:**
Get inside grin batol heroic and use dnd on any pack or boss

**How it should work:**
The mobs or boss that are beeing hit by dnd should aggro on the dk that casted it

**Database links:**

**Comment by Afgann** [comment]
fixed
