### ISSUE TITLE
[NPC] Petrified Stone bat

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1787]
**How to reproduce:** there are so many of them stacked inside eachother which it should not be like that 
they are related to quest  Petrified Delicacies
![image](https://user-images.githubusercontent.com/36106057/211679571-8fb73d73-6281-4505-af26-4769c014ac03.png)
![image](https://user-images.githubusercontent.com/36106057/211679839-c210c446-5b81-4a38-96d1-1a405c304704.png)

**How it should work:** they should spread out around the area

**Comment by UltraNix** [comment]
Fixed.
