### ISSUE TITLE
[Quest][Cata] [NPC]  [Don't. Stop. Moving.]

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1788]
**How to reproduce:** you can spawn as much as opalescent Guardians you want it should not happen! also they are all stacked inside eachother that should not happen
![image](https://user-images.githubusercontent.com/36106057/211680427-dff0156b-b672-485f-b486-020c8f97c890.png)

**How it should work:** you should be able to spawn one wave of them and they should not stack inside eachother
Overall idea shown in this video: https://www.youtube.com/watch?v=rAvEt1SWouA

**Comment by WhitemaneSylah** [comment]
@MrTide  Might be worth reopening this,  player found a similar issue abandoning the quest 

https://discord.com/channels/1040715551531618365/1080334567690481695

https://i.imgur.com/6GswGpx.jpg
