### ISSUE TITLE
[Server Crash][Quest]  Resonating Blow

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1790]
**How to reproduce:** once you try to use the crystal and click on the hammer server crashes i couldn't do the event at all please take a look and make sure event is working

**How it should work:** it should work and not crash the server
whole event: https://www.youtube.com/watch?v=h1HgqyGEmMo
https://www.youtube.com/watch?v=hnFAr_6qOso

**Comment by UltraNix** [comment]
@MrTide Just tested and got no crash during the event.
The quest works itself. 
Could you re-test it?

**Comment by MrTide** [comment]
Probably its because of new maps that gaga did, solved a lot of creatures falling through the floor as well,
i didn't see event reset for next try tho if you wanna take a look waited a long while in there (i didnt turn the quest in)
So basically if one person does it no one else can 
![image](https://user-images.githubusercontent.com/36106057/212854104-a9213cd9-55a0-40e6-a100-1a
![image](https://user-images.githubusercontent.com/36106057/212854321-fda9092c-9150-487a-a250-7206ce213e52.png)
4d6af043f2.png)

**Comment by UltraNix** [comment]
Tested and got no problems with doing the quest one after one. Event works everytime I use [Stonework Mallet](https://www.wowhead.com/item=60266/stonework-mallet)

**Comment by MrTide** [comment]
reopening the issue
![image](https://user-images.githubusercontent.com/36106057/223347805-53952943-6444-4828-9e8d-31c1efed2019.png)
looks like what i said still happening
