### ISSUE TITLE
[Priest] Mindcontrol causing errors

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1792]
If a player has auto attack enabled and is then mindcontrolled, brought over to the priest and allowed to auto attack it causes a latency spike of about 3000, meaning abilties cannot be cased during the channel (they should be castable but interrupt the channel itself).

How to replicate -  Mindcontrol another player with auto attack enabled on their side,  walk towards the priest, allow the auto attack to hit,  try using a spell during the channel from priest end

**Comment by UltraNix** [comment]
Fixed.
