### ISSUE TITLE
[NPC] [Cata][Quest] Wrath of the Fungalmancer

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1793]
**How to reproduce:** after trying to kill fungalmancer clop at some point he just became unkillable and evaded and if you stick around for a while he stop evading but heals to full everytime so its not possible to finish the quest
![image](https://user-images.githubusercontent.com/36106057/211684361-99406a65-c67c-45d4-8169-09209fbf783a.png)

**How it should work:** he should not stop and evade
i didnt see friendly npc fight neither
full run: https://www.youtube.com/watch?v=2DntiVg4xL0

**Comment by Greywolf59** [comment]
I can confirm. On his first stop, I tried to make one of the boomshrooms explode near him and damage him so his HP would stop replenishing. It worked and then he entered the fight properly. On the second stop he just went to evade, after a while he healed up, I made another mushroom explode near him and he once again entered the fight properly. When he run to his third and final stop he was so down on HP that my bleeds and hits finished him of just as he reached his last stop.
Also there are no mobs, the [Fungal Horrors](https://www.wowhead.com/npc=43502/fungal-horror) in the gauntlet, if you've noticed. [Summon Fungal Horror](https://www.wowhead.com/spell=81307/summon-fungal-horror).
So, the quest is completable, just a little bit tricky to do.
