### ISSUE TITLE
[NPC] [Cata][Quest]  The Stone March and Therazane´s Mercy and The Twilight Flight

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1794]
**How to reproduce:** Area event is not scripted at all
![image](https://user-images.githubusercontent.com/36106057/211686468-13facd2a-97a1-409e-bc9a-51c0ebc6fd50.png)
high priestess lorthuna just stands there and looks at you
![image](https://user-images.githubusercontent.com/36106057/211686663-aea1f0dd-91d6-4815-80b5-a64181be486d.png)
The Twilight Flight is not scripted at all, i just killed the npc
![image](https://user-images.githubusercontent.com/36106057/211687083-1b0a673d-998e-4d11-b8ed-2d8d7133a310.png)

**How it should work:**
both quests are not working properly
event should work
The Stone March and Therazane´s Mercy: https://www.youtube.com/watch?v=UGA7GrqqD9M
The Twilight Flight : https://www.youtube.com/watch?v=vrsmxzQCNh8

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
The Twilight Flight quest is not working properly
you move faster than Zoltrik drake.
and when your flight ends your drakes doesn't drop you at the right locations like its shown in the video to finish the fight
basically if you dont jump on its drake and decide to finish the event while being on your own drake it and if you dont manage to finish it until end of the ride while being on his drake or your own he just falls through the floor and you can't kill it again.
![image](https://user-images.githubusercontent.com/36106057/221258787-8647bd7e-5e90-4ae6-b434-7bf92d9c5a96.png)
and event in the area is not scripted still, like its shown in this video, there is no battle going on 
 https://www.youtube.com/watch?v=UGA7GrqqD9M

**Comment by MrTide** [comment]
no more complains so far if i find anything i will reopen this
