### ISSUE TITLE
[NPC] [Cata][Quest] Undying Twilight

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1795]
**How to reproduce:** npc for quest  Undying Twilight they just fell through ground once i tried to fight them, event related to it was not scripted at all, no friendly npcs nothing..
![image](https://user-images.githubusercontent.com/36106057/211687571-4d0d9f3d-acc1-410a-a1bb-7efb60913b91.png)
![image](https://user-images.githubusercontent.com/36106057/211687652-3ade06da-f83d-46a8-95ed-b3136d27ff8d.png)

**How it should work:** they should not fell through the ground and event should work properly like this video
https://youtu.be/DMABtRpgkMA?t=74

**Comment by UltraNix** [comment]
Falling under the ground fixed long time ago.

**Comment by UltraNix** [comment]
Wrongly generated mmaps. Should be okay with the next update.

**Comment by UltraNix** [comment]
Still no mmaps - just wait.

**Comment by Greywolf59** [comment]
Ow, and I have just done it. Could have waited and check how the event looks normally above ground :/ :D. Pity.

**Comment by UltraNixx** [comment]
@Greywolf59 Problems with mmaps is gone?

**Comment by Greywolf59** [comment]
Oh I have already finished the quest chain, I just found NPC I could charge under texture and finished both quest under temple texture.
