### ISSUE TITLE
[NPC] [Cata][Quest] The Binding

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1796]
**How to reproduce:** event is not scripted at all its not possible to do this event at all
fell through ground as well, there is nothing going on or happening
![image](https://user-images.githubusercontent.com/36106057/211688144-395da64f-8930-429a-bf93-63149f2d2a21.png)

**How it should work:** it should work like this : https://www.youtube.com/watch?v=8AdGCOPdcpo

**Comment by UltraNix** [comment]
High Priestess Lorthuna should be killable, but yeah - the whole event is missing.

**Comment by UltraNix** [comment]
No mmaps - wait for it.
