### ISSUE TITLE
[Quest] Call of Duty (alliance) Not working

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1797]
https://cata-twinhead.twinstar.cz/?quest=14482  quest does not function at all

RP scenes do not play out,  Phasing does not change when quest is accepted to get rid of the northrend boat.  

Boat does spawn and will take player to vashj'ir but as phasing doesn't change the quest will remain incomplete

![image](https://user-images.githubusercontent.com/121137397/211691889-b31a8920-44d3-4731-878c-ff4e2c5670ef.png)

After arriving in Kelp'thar forrest the player should be unable to move (which is the case) and is then saved by Erunak, the screen should fade to black and the player teleported to The Briny Cutter.  Player will be able to move after 3 minutes however as phasing didn't change the quest NPCs will never spawn

![image](https://user-images.githubusercontent.com/121137397/211691968-fcf638b7-3ca7-4501-9900-6cf13dea8c26.png)

Please review this video to see the sequence of events as they should be , including transitions and phase changes

https://www.youtube.com/watch?v=FEcLfCeP4Sk

**Comment by WhitemaneSylah** [comment]
This was tested with GM off for the whole duration to ensure no phasing issue

**Comment by WhitemaneSylah** [comment]
![image](https://user-images.githubusercontent.com/121137397/211692184-6ed7ca52-cec2-4c2c-9755-32e2a91c0f9b.png)


When GM is turned on the NPCs are visable but when turned off they disappear again

**Comment by MrTide** [comment]
horde version is not working neither no event nothing
