### ISSUE TITLE
[Client Crash] If you go to camp narache the game crashes

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#1798]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Camp narache makes your game crash
**How to reproduce:**
Bring characters to camp narache

**How it should work:**
It should not crash and i should be able to move

**Database links:**
https://www.wowhead.com/zone=6452/camp-narache

**Comment by WhitemaneSylah** [comment]
Confirmed, tested this myself

**Comment by MrTide** [comment]
![image](https://user-images.githubusercontent.com/36106057/211977203-1126656a-9c54-49b2-b3c3-7437d7d11bec.png)

**Comment by UltraNix** [comment]
Fixed.
