### ISSUE TITLE
Sultan Oogah drops less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1799]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The amount of money dropped by Sultan Oogah mob, on screen it's 23 copper, in reality, it should be around 25 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211747151-0b59bca9-290a-4dee-92a9-4e0f67ffa853.png)

**How to reproduce:**
Go to Uldum (68.23, 31.54) find  Sultan Oogah and kill him

**How it should work:**
It should drop around 25 silver

**Database links:**
https://www.wowhead.com/npc=45205/sultan-oogah#drops;0-19+16+1

**Comment by MrTide** [comment]
requires more info wow head is not enough since its for latest expansion and https://cata-twinhead.twinstar.cz/?npc=45205 is not showing the gold drop

**Comment by MrTide** [comment]
Confirmed thank you

**Comment by UltraNix** [comment]
Fixed.
