### ISSUE TITLE
Sand pygmy dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1800]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sand pygmy is dropping only 23-25 copper per kill it should drop around 24 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211749563-5aecb9a5-8508-4ae7-8a88-c54561460e02.png)

**How to reproduce:**
Go to Uldum (68, 31) find one of the mobs and kill it

**How it should work:**
It should drop around 24 silver according to the database but not 24 cooper

**Database links:**
https://www.wowhead.com/npc=45190/sand-pygmy#drops

**Comment by MrTide** [comment]
What database ? wowhead  its not for cataclysm content

**Comment by sadgh05t** [comment]
> What database ? wowhead its not for cataclysm content

![image](https://user-images.githubusercontent.com/35288643/211907858-b9faacdc-97b9-4da9-b3d6-6d8494a68012.png)
why even add it to the pre post? if it's not for cata?

**Comment by sadgh05t** [comment]
> > > What database ? wowhead its not for cataclysm content
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/35288643/211907858-b9faacdc-97b9-4da9-b3d6-6d8494a68012.png) why even add it to the pre post? if it's not for cata?
> 
> Wowhead comments can still be valid and it provides quest/item/NPC ids for the devs.
> 
> You can use web archive to go to old versions of wowhead to get info if the GMs request it (like this)

Yes I am using it

**Comment by sadgh05t** [comment]
> What database ? wowhead its not for cataclysm content

https://web.archive.org/web/20101215060506/http://www.wowhead.com/npc=45190/sand-pygmy 
25s 26 c

**Comment by MrTide** [comment]
Confirmed thank you

**Comment by UltraNix** [comment]
Fixed.
