### ISSUE TITLE
Wastewander Outrider dropping less than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1801]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Wastewander Outrider is dropping 23-25 cooper when killed but should drop around 25 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211750357-1b47360e-06b5-4f35-8f01-c793f30d8e84.png)

**How to reproduce:**
Go to Uldum 51 21 kill the Wastewander Outrider and check the coins drop

**How it should work:**
It should drop around 25 silver according to the database, not 24 cooper

**Database links:**
https://www.wowhead.com/npc=45905/wastewander-outrider#drops

**Comment by MrTide** [comment]
according to catatwin head player is correct
wowhead is not accurate usually because it uses latest expansion 
https://cata-twinhead.twinstar.cz/?npc=45905

**Comment by UltraNix** [comment]
Fixed.
