### ISSUE TITLE
Schnottz Excavator is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1802]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Schnottz Excavator is dropping 23-27 cooper per kill but should drop around 26 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211751594-de4387a2-75a7-47ca-8658-ceeef44b5f15.png)

**How to reproduce:**
Go to Uldum 40, 24 kill Schnottz Excavator and loot it

**How it should work:**
It should drop 26 silver

**Database links:**
https://www.wowhead.com/npc=48204/schnottz-excavator#drops

**Comment by MrTide** [comment]
wowhead is for latest expansion
require more info regarding the drop

**Comment by MrTide** [comment]
Confirmed thank you

**Comment by UltraNix** [comment]
Fixed.
