### ISSUE TITLE
Schnottz's Landing Laborer dropping less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1804]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Schnottz's Landing Laborer is dropping 16-27 cooper per kill but should drop 25 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211756125-a63c9b96-2b3d-4023-bcbd-c36e1209fe7b.png)

**How to reproduce:**
Got to Uldum 26 , 64.8 kill Schnottz's Landing Laborer and loot it

**How it should work:**
It should drop 25 silver

**Database links:**
https://www.wowhead.com/npc=47690/schnottzs-landing-laborer#drops

**Comment by MrTide** [comment]
require more info wowhead is for latest expansion

**Comment by sadgh05t** [comment]
> require more info wowhead is for latest expansion

https://web.archive.org/web/20101215034325/http://www.wowhead.com/npc=47690/schnottzs-landing-laborer 
25 s 51 c

**Comment by MrTide** [comment]
Thank you for your hard work
confirmed

**Comment by UltraNix** [comment]
Fixed.
