### ISSUE TITLE
Schnottz Sea Trooper dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1805]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Schnottz Sea Trooper is dropping 22-26 cooper per kill and should drop around 26 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211758189-88b01427-1309-4aa6-b22e-9d643be14818.png)

**How to reproduce:**
Go to Uldum 26.2 68.4 and kill one Schnottz Sea Trooper

**How it should work:**
It should drop around 26 silver 

**Database links:**

https://www.wowhead.com/npc=47982/schnottz-sea-trooper#drops

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47982

**Comment by UltraNix** [comment]
Fixed.
