### ISSUE TITLE
Eternal Protector is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1806]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Eternal Protector is dropping 19-25 cooper per kill it should drop around 26 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211760059-7089d437-4ef9-430d-985f-9f9fe659a155.png)

**How to reproduce:**
Go to Uldum 34.4 62.0 kill one Eternal Protector check the drop

**How it should work:**
It should drop 26 silver

**Database links:**

https://www.wowhead.com/npc=47227/eternal-protector#drops

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47227

**Comment by UltraNix** [comment]
Fixed.
