### ISSUE TITLE
Furious Specter drops less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1807]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Furious Specter is dropping 20-27 copper per kill but should drop around 25 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211760666-77b26fff-5c9e-424d-9fe4-8daabb06558f.png)

**How to reproduce:**
Go to   Uldum 31.4 67.6  and kill Furious Specter

**How it should work:**
It should drop 25 silver

**Database links:**
https://www.wowhead.com/npc=47220/furious-specter

**Comment by MrTide** [comment]
wowhead is for latest expansion
requires more info

**Comment by MrTide** [comment]
Confirmed thank you

**Comment by UltraNix** [comment]
Fixed.
