### ISSUE TITLE
Neferset Savage is dropping  less money than it  should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1808]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Savage is dropping around 17-25 cooper per kill and should drop 27 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211764582-c75207b4-0c0b-45b0-a527-a84d8573ef4f.png)

**How to reproduce:**
Go to Uldum 51.0 72.8 and kill Neferset Savage and loot it

**How it should work:**
It should drop 27 silver

**Database links:**

https://www.wowhead.com/npc=47729/neferset-savage#drops

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47729

**Comment by UltraNix** [comment]
Fixed.
