### ISSUE TITLE
Neferset Armorer is dropping  less money than is should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1809]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Armorer is dropping around 19-26 cooper per kill it should drop 28 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211765578-6c1610df-cbb3-4561-838c-c0c2c12cd73a.png)

**How to reproduce:**
Go to Uldum 51.0 72.8  kill Neferset Armorer and loot it

**How it should work:**
It should drop 28 silver

**Database links:**
https://www.wowhead.com/npc=47722/neferset-armorer

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47722

**Comment by UltraNix** [comment]
Fixed.
