### ISSUE TITLE
Tol'vir Merchant is dropping 1000 times less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1810]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Tol'vir Merchant is dropping around 17-25 cooper per kill and it should drop 1 gold 20 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211766191-adb75af6-8aa8-4c44-bb35-adc9fa73c12c.png)

**How to reproduce:**
Go to Uldum 51.6 71.0 kill Tol'vir Merchant and loot it

**How it should work:**
It should drop 1 gold 20 silver

**Database links:**
https://www.wowhead.com/npc=47725/tolvir-merchant

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47725

**Comment by UltraNix** [comment]
Fixed.
