### ISSUE TITLE
Neferset Blade Twister is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1811]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Blade Twister is dropping around 17-27 cooper per kill but should drop 27 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211767696-78c493f9-b22a-45a6-9eac-273c3c7333ae.png)

**How to reproduce:**
Go to Uldum 51.0 72.8 kill Neferset Blade Twister and loot it

**How it should work:**
It should drop 27 silver

**Database links:**

https://www.wowhead.com/npc=47727/neferset-blade-twister

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47727

**Comment by UltraNix** [comment]
Fixed.
