### ISSUE TITLE
Neferset Venom Keeper is dropping  less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1812]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Venom Keeper is dropping around 17-25 cooper per kill it should drop 26 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211768990-b4af0912-05eb-4bfe-b9fc-0ec90d4c5574.png)

**How to reproduce:**
Go to Uldum 50.6 80.8 kil Neferset Venom Keeper and loot it

**How it should work:**
It should drop 26 silver

**Database links:**
https://www.wowhead.com/npc=47741/neferset-venom-keeper

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47741

**Comment by UltraNix** [comment]
Fixed.
