### ISSUE TITLE
Neferset Snake Charmer drops  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1813]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Snake Charmer is dropping 17-27 cooper per kill it should drop 27 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211771945-f6df2e47-0ce1-42d9-99c6-c2a4253632c7.png)

**How to reproduce:**
Go to Uldum 50.6 80.6 kill Neferset Snake Charmer and loot it

**How it should work:**
It should drop 27 silver

**Database links:**
https://www.wowhead.com/npc=47738/neferset-snake-charmer

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47738

**Comment by UltraNix** [comment]
Fixed.
