### ISSUE TITLE
Neferset Ritualist is dropping  less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1814]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Ritualist is dropping 17-27 cooper per kill it should drop 27 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211772530-b4e02cea-1ccc-4cbf-adda-8c7a62313a9e.png)

**How to reproduce:**
Go to Uldum 50.0 82.4  kill Neferset Ritualist and loot it

**How it should work:**
It should drop 27 silver

**Database links:**
https://www.wowhead.com/npc=47762/neferset-ritualist

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47762

**Comment by UltraNix** [comment]
Fixed.
