### ISSUE TITLE
Dark Pharaoh Tekahn is dropping 800 times less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1816]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dark Pharaoh Tekahn is dropping 20-27 cooper per kill it should drop 81 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211773836-c0751913-6522-49d0-81f0-8887487804ca.png)

**How to reproduce:**
Go to Uldum 51.8 82.2 kill Dark Pharaoh Tekahn and loot it 

**How it should work:**
It should drop 81 silver

**Database links:**
https://www.wowhead.com/npc=47753/dark-pharaoh-tekahn

**Comment by MrTide** [comment]
requires more info https://cata-twinhead.twinstar.cz/?npc=47753 not showing the amount of gold and wowhead is for latest expansion, can't be considered as evidence really

**Comment by MrTide** [comment]
Confirmed
