### ISSUE TITLE
Scorpion-Lord Namkhare is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1817]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Scorpion-Lord Namkhare is dropping 27-29 cooper per kill it should drop 28 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211774483-dcb0b609-2147-4ebb-95e4-a20ed8311773.png)

**How to reproduce:**
Go to Uldum 50.6 86.8 kill Scorpion-Lord Namkhare and loot it

**How it should work:**
It should drop 28 silver

**Database links:**
https://www.wowhead.com/npc=47742/scorpion-lord-namkhare

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=47742

**Comment by UltraNix** [comment]
Fixed.
