### ISSUE TITLE
High Priest Sekhemet is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1818]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
High Priest Sekhemet is dropping around 20-27 cooper per kill he should drop 28 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211775075-4bc19aa8-1137-41d3-9515-f3046f5839b8.png)

**How to reproduce:**
Go to Uldum 47.6 77.2 kill High Priest Sekhemet and loot it

**How it should work:**
It should drop 28 silver

**Database links:**
https://www.wowhead.com/npc=47730/high-priest-sekhemet

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=47730 can confirm

**Comment by UltraNix** [comment]
Fixed.
