### ISSUE TITLE
Cyrus the Black is dropping 20000 times less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1819]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cyrus the Black is dropping 19-20 cooper per kill it should drop 20 gold 11 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211775865-e37550ca-75d8-4b4f-92b1-78ea48b30740.png)

**How to reproduce:**
Go to Uldum 58.4 61.6 \ 66.6 68.0 \ 70.8 74.2 \ 58.0 82.6 find and kill Cyrus the Black loot it

**How it should work:**
It should drop 20 gold 11 silver 

**Database links:**
https://www.wowhead.com/npc=50064/cyrus-the-black

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=50064

**Comment by UltraNix** [comment]
Fixed.
