### ISSUE TITLE
Neferset Guard is dropping  less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1820]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Guard is dropping 19-26 cooper per kill it should drop 26 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211776451-ee096615-4fb8-4d91-83b7-5ead16ed5d83.png)

**How to reproduce:**
Go to Uldum 58.6 61.0 kill Neferset Guard and loot

**How it should work:**
It should drop 26 silver

**Database links:**
https://www.wowhead.com/npc=46340/neferset-guard

**Comment by MrTide** [comment]
requires more info https://cata-twinhead.twinstar.cz/?npc=46340 is not showing the gold drop and wowhead is for latest expansion can not be considered as evidence

**Comment by MrTide** [comment]
Confirmed thank you

**Comment by UltraNix** [comment]
Fixed.
