### ISSUE TITLE
Colossus of the sun should be in the ground

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1821]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Colossus of the sun should be in the ground and in order to activate it you need to come close and click , here he is just standing
![image](https://user-images.githubusercontent.com/35288643/211782598-70dc51d7-578e-4702-a17b-dc3462d298a6.png)

**How to reproduce:**
Go to Uldum 39.6 41.0 and check Colossus of the sun 

**How it should work:**
He should be in the ground like on the picture

**Database links:**
https://www.wowhead.com/npc=46041/colossus-of-the-sun

**Comment by sadgh05t** [comment]
@MrTide  killed them and did wait for the respawn they are still standing and should be in the ground https://www.youtube.com/watch?v=whRmhjUcq7o&ab_channel=GameGuides

**Comment by UltraNix** [comment]
Fixed.
