### ISSUE TITLE
Neferset Scryer is dropping  less money than it should 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1823]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Scryer is dropping 19-26 cooper per kill it should drop 27 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211784548-3ddd828f-24d0-4a9f-b693-eaef592c7797.png)

**How to reproduce:**
Go to Uldum 75.2 47.8 kill Neferset Scryer and loot it

**How it should work:**
It should drop 27 silver

**Database links:**
https://www.wowhead.com/npc=48625/neferset-scryer

**Comment by MrTide** [comment]
can confirm https://cata-twinhead.twinstar.cz/?npc=48625
@sadgh05t next time please report all of these in one report

**Comment by UltraNix** [comment]
Fixed.
