### ISSUE TITLE
Neferset Looter is dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1824]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Looter is dropping 17-26 cooper per kill it should drop 27 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211784864-8629e914-b31e-47a5-83f2-45db4a6d21be.png)

**How to reproduce:**
Go to Uldum 75.2 50.0 kill Neferset Looter and loot it

**How it should work:**
It should drop 27 silver

**Database links:**
https://www.wowhead.com/npc=48627/neferset-looter

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=48627 can confirm

**Comment by UltraNix** [comment]
Fixed.
