### ISSUE TITLE
Neferset Raider dropping  less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1825]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neferset Raider drops 18-26 cooper per kill it should drop 26 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211785197-c6708977-196c-4958-898a-f3d30cd69a13.png)

**How to reproduce:**
Go to Uldum 74.6 45.6 kill Neferset Raider and loot it

**How it should work:**
It should drop 26 silver 

**Database links:**
https://www.wowhead.com/npc=48626/neferset-raider

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=48626 can confirm

**Comment by UltraNix** [comment]
Fixed.
