### ISSUE TITLE
Twilight Crusher is dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1826]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Crusher is dropping 19-22 copper per kill but should drop 26 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211811493-0a328438-68a5-4a7b-afd9-81059fab7288.png)

**How to reproduce:**
Go to Deepholm 41.4 69.6 kill Twilight Crusher and loot it

**How it should work:**
It should drop 26 silver 

**Database links:**
https://www.wowhead.com/npc=44849/twilight-crusher

**Comment by MrTide** [comment]
requires more info its wowhead link
https://cata-twinhead.twinstar.cz/?npc=44849 is showing 0

**Comment by sadgh05t** [comment]
Nothing on web archive and other databases closing in that case
