### ISSUE TITLE
Twilight Cryptomancer is dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1827]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Cryptomancer is dropping 17-27 cooper per kill and should drop 25 silver according to the database 
![image](https://user-images.githubusercontent.com/35288643/211812504-7cc33574-19d9-4d01-b169-8877912217ee.png)

**How to reproduce:**
Go to Deepholm 40.6 67.6 kill Twilight Cryptomancer and loot it

**How it should work:**
It should drop 25 silver

**Database links:**

https://www.wowhead.com/npc=44855/twilight-cryptomancer

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=44855 shows 0
wowhead is for latest expansion
requires more info

**Comment by sadgh05t** [comment]
Nothing on web archive closing
