### ISSUE TITLE
Twilight Armsman is dropping less amount of money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1828]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Armsman is dropping 17-30 copper per kill but should drop 25 silver according to the database

![image](https://user-images.githubusercontent.com/35288643/211813998-10e03f93-8e69-4da7-a166-2b1bb55c6184.png)

**How to reproduce:**
Go to Deepholm 41.2 69.6 kill Twilight Armsman and loot it

**How it should work:**
It should drop 25 silver

**Database links:**

https://www.wowhead.com/npc=44847/twilight-armsman

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=44847 shows 0
wow head is for latest expansion
requires more info

**Comment by sadgh05t** [comment]
Nothing on web archive closing
