### ISSUE TITLE
Deathforge Guardian dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1829]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Deathforge Guardian is dropping 2-3 silver per kill it should drop 14 silver according to the database

![image](https://user-images.githubusercontent.com/35288643/211820625-9ea30c37-994c-4fde-8e4d-ca5c4f759ab8.png)

**How to reproduce:**
Go to Shadowmoon valley 42.0 36.6 kill Deathforge Guardian and loot it

**How it should work:**
It should drop 14 silver

**Database links:**
https://www.wowhead.com/npc=20878/deathforge-guardian

**Comment by MrTide** [comment]
12 75
https://cata-twinhead.twinstar.cz/?npc=20878 can confirm
