### ISSUE TITLE
Demon Hunter Supplicant  dropping less money than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Demon Hunter Supplicant is dropping 2-3 silver per kill and should drop 15 silver according to the database

![image](https://user-images.githubusercontent.com/35288643/211821685-486f040d-1c54-422d-88f6-ff3944a0bf23.png)

**How to reproduce:**
Go to Shadowmoon valley 70.6 51.6 kill Demon Hunter Supplicant and loot it

**How it should work:**
It should drop 15 silver

**Database links:**
https://www.wowhead.com/npc=21179/demon-hunter-supplicant

**Comment by MrTide** [comment]
12 75
https://cata-twinhead.twinstar.cz/?npc=21179 can confirm
