### ISSUE TITLE
[TBC Content] Doomwalker is dropping more gold than he should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1831]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Doomwalker is dropping 500-520 gold per kill but he should drop 50 gold according to the database
![image](https://user-images.githubusercontent.com/35288643/211823011-3645d988-c25e-4cd5-afee-064f0d75897a.png)

**How to reproduce:**
Go to Shadowmoon valley kill Doomwalker check loot

**How it should work:**
It should drop 50 gold

**Database links:**
https://www.wowhead.com/npc=17711/doomwalker

**Comment by UltraNix** [comment]
Fixed.
