### ISSUE TITLE
Southern Barrens Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1832]
1. [Repel Boarders!](https://www.wowhead.com/quest=24934/repel-boarders)
- [Northwatch Gryphons](https://www.wowhead.com/npc=38707/northwatch-gryphon) + /npc=38709 are buggy.
- Player can fly the one from tower to ship on his own but always in the same altitude.
- Player can control the one from the ship to tower on his own, but the gryphon can't fly so you just gotta swim/run back on it.
- It seems the flights should be automatic: https://www.youtube.com/watch?v=unZLjIvSis8

2. [Langridge Shot](https://www.wowhead.com/quest=24941/langridge-shot)
- https://www.youtube.com/watch?v=WnilN-leB-g
- The NPCs should react to the player's looting the object for quest items. They don't.
- The cannon shot does after completion does not happen.

3. [Silencing Rageroar](https://www.wowhead.com/quest=24956/silencing-rageroar)
- 2:15 https://www.youtube.com/watch?v=s64Oam_Qc08
- When player gets close to the [Karga Rageroar](https://www.wowhead.com/npc=38663/karga-rageroar) an event should trigger. It doesn't.
- [Hexmaster Bastoon](https://www.wowhead.com/npc=38826/hexmaster-bastoon) is not attackable and does not react, jsut stands there.
- After killing Rageroar I have noticed I have combat bug, but it could have been there a little earlier.

4. [Elder Zhevra](https://www.wowhead.com/npc=37088/elder-zhevra)
- Zhevras between Northwatch Hold and Teegan's Expedition are all dead and do not despawn.
- There are no zhevras at all near and around Forward Command whereas on videos I was watching there should be some

5. [Enervated Adder](https://www.wowhead.com/npc=37738/enervated-adder)
- lootable for [Enervated Adder](https://www.wowhead.com/item=49875/enervated-adder) even without a [quest](https://www.wowhead.com/quest=24570/adder-subtraction)

6. [Budding Flower](https://www.wowhead.com/object=201738/budding-flower)
- This blue variety of the flower does nothing when interacted with.

7. [Naralex](https://www.wowhead.com/npc=37570/naralex)
- has wrong gossip meant for after-completion of [The Nightmare Scar](https://www.wowhead.com/quest=24601/the-nightmare-scar). Before it, it should be most likely: "As Druids, we are tasked with protecting the balance of nature. My life's work has gone against this. In my folly, I have sewn chaos, and this deviant crop must be reaped before it spreads further."
-  His chat option "What happened here?" does not open further dialogue.
- https://wowpedia.fandom.com/wiki/Naralex?so=search#Quotes

8. [Recipe: Savory Deviate Delight](https://cata-twinhead.twinstar.cz/?item=6661)
- has most likely boosted drop chance since I got two already and haven't been further than 1/3 in the zone progress

9. [Diplomacy By Another Means](https://www.wowhead.com/quest=25044/diplomacy-by-another-means)
- It feels and looks like this one should not be handed via comm.
- 1:50 https://www.youtube.com/watch?v=5f-ZL8qcbqo

10. Forward Command NPCs
- All of the NPCs in Forward Camp and around are standing completely still all the time, some of them in a strange posture. It just feels off.
- mainly [Northwatch Rifleman](https://www.wowhead.com/npc=39005/northwatch-rifleman), [Northwatch Recon](https://www.wowhead.com/npc=37585/northwatch-recon), [Karl](https://www.wowhead.com/npc=39024/karl). Could also be [Siege Tank Engineers](https://www.wowhead.com/npc=39006/siege-tank-engineer) and some of the [Northwatch Guards](https://www.wowhead.com/npc=51853/northwatch-guard)

11. [Clap 'em in Irons](https://www.wowhead.com/quest=25057/clap-em-in-irons)
- When player uses [Manacles](https://www.wowhead.com/item=52271/northwatch-manacles) on [Taurajo Looter](https://www.wowhead.com/npc=37743/taurajo-looter), the Looters won't get friendly and won't stop fighting. However the player gets credit and can either kill them or wait a few secs for them to despawn.
- Their emotes are messed up. On aggro they /say the things they should say when idle. When they are idle they /say nothing. Their "Arrest" emotes are missing completely too https://wowpedia.fandom.com/wiki/Taurajo_Looter?so=search#Quotes
- All Taurajo Looters are standing on one spot, not moving. They should walk around, rumage around or something.
- https://www.youtube.com/watch?v=vLPyj0pwlAE

12. [Dusthoof Giraffe](https://www.wowhead.com/npc=37082/dusthoof-giraffe)
- There are no alive Giraffes, at least not in northern parts of Southern Barrens. Only dead ones here and then. The dead ones are not even targettable.

13. [Sapper Specialists](https://www.wowhead.com/npc=37925/sapper-specialist)
- These guys are nto scripted. They just stand around on one spot a bit southwest from Fort Triumph.
- They should be running in small groups towards Fort Triumph and suicide themselves at the walls or Alliance guards.

14. [Reinforcements From Theramore](https://www.wowhead.com/quest=26687/reinforcements-from-theramore)
- Available too soon, the 1st time I came to the quest giver already.
- This quest should require whole quest chain done that ends with [The Deed is Done](https://www.wowhead.com/quest=25185/the-deed-is-done)
- https://wowpedia.fandom.com/wiki/Reinforcements_From_Theramore#Progression;  https://www.wowhead.com/quest=26687/reinforcements-from-theramore#comments:id=1715515

15. [Hands Off Me Dig!](https://www.wowhead.com/quest=25106/hands-off-me-dig)
- There are only 4 [Excavation Raiders](https://www.wowhead.com/npc=39153/excavation-raider)
- There should be slightly more raiders, 6 - 8 in total and their respawn should be faster according to the video
- https://www.youtube.com/watch?v=TPJOShZI1iw

16. [Larhasha](https://www.wowhead.com/npc=37836/larhasha)
- This NPC is missing

17. [Zang'do](https://www.wowhead.com/npc=37817/zangdo)
- This NPC is missing
- It seems that [Mahka](https://www.wowhead.com/npc=37812/mahka) sits on his spot instead of hers.

18. [Echoes of Agamaggan](https://www.wowhead.com/quest=24653/echoes-of-agamaggan)
- Missing post-completion event
- 2:35 https://www.youtube.com/watch?v=_5yp02Ltx0k

19. [Mankrik](https://www.wowhead.com/npc=37847/mankrik)
- Should be hostile to Alliance, is friendly and Alli can talk to him.

**Comment by PanJanuszek** [comment]
fixed 07.05.2024, after restart
