### ISSUE TITLE
Twilight Proveditor dropping less amount of gold than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1833]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Proveditor drops 17-27 cooper per kill but should drop 23 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211853858-9a42772c-0ca9-4dd6-9897-b8ff7cf34376.png)

**How to reproduce:**
Go to mount hyjal 39.6 23.4 kill Twilight Proveditor and loot it

**How it should work:**
It should drop 23 silver

**Database links:**
https://www.wowhead.com/npc=39436/twilight-proveditor

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=39436 not showing amount of gold
wowhead is not good enough since its for latest expansion

**Comment by sadgh05t** [comment]
> https://cata-twinhead.twinstar.cz/?npc=39436 not showing amount of gold wowhead is not good enough since its for latest expansion

yea just checked on other databases they are not showing the gold as well, thought the wowhead is reliable source

**Comment by sadgh05t** [comment]
nothing on web archive closing
