### ISSUE TITLE
Okrog dropping less gold than it should

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1834]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Okrog dropping 17-27 cooper per kill but he should drop 24 silver according to the database
![image](https://user-images.githubusercontent.com/35288643/211856176-26a0829c-477a-415d-b3fd-2f8812f8ceb9.png)

**How to reproduce:**
Go to mount hyjal 79.0 56.0 kill Okrog and loot it

**How it should work:**
It should drop 24 silver

**Database links:**
https://www.wowhead.com/npc=40922/okrog

**Comment by MrTide** [comment]
https://cata-twinhead.twinstar.cz/?npc=40922 is not showing the amount
wowhead is not good enough since its for latest expansion

**Comment by sadgh05t** [comment]
Nothing on web archive about this one closing in that case
