### ISSUE TITLE
Draenei Passive missing

### ISSUE THREAD

**Issue by Darkosz** [gamefreedomgit/Maelstrom#1837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Draenei Hunters, Paladins,DKs do not have their passive racial Heroic Presence upon creation. 

**How to reproduce:**
Create a Draenei character with the above mentioned classes and check their abilities. Heroic Presence is missing.

**How it should work:**
 The racial passive should be there.

**Database links:**
https://www.wowhead.com/spell=6562/heroic-presence

**Comment by MrTide** [comment]
its active on player 
![image](https://user-images.githubusercontent.com/36106057/211902700-9c96a2e2-0d00-4518-b0a7-6c8015ebcddd.png)
but its no longer an aura 
![image](https://user-images.githubusercontent.com/36106057/211902633-4fdd88cd-85ee-4389-a37a-cf3bf426275d.png)

**Comment by Afgann** [comment]
fixed
