### ISSUE TITLE
Orc Passive missing

### ISSUE THREAD

**Issue by Darkosz** [gamefreedomgit/Maelstrom#1838]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Orc Hunters do not get their racial passive Command upon creation.

**How to reproduce:**
Create an Orc hunter and check his abilities.

**How it should work:**
He should have the racial passive Command.

**Database links:**
https://www.wowhead.com/spell=21563/command

**Comment by MrTide** [comment]
Can confirm player is right
it should be auto learned on orc warlock/hunter/dk
https://wowwiki-archive.fandom.com/wiki/Command#:~:text=Command%20is%20a%20passive%20racial,warlock)%20by%20a%20small%20amount.

**Comment by Afgann** [comment]
fixed
