### ISSUE TITLE
[Quest] Working the Bugs Out - bugged

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1840]
Had to take the opportunity lol. Anyway…
Quest: [Working the Bugs Out](https://www.wowhead.com/quest=25082/working-the-bugs-out)
Issue: When trying to use [Bucket of Burning Pitch](https://www.wowhead.com/item=50128/bucket-of-burning-pitch), player gets error message "Requires Silithid Mound" even when standing on proper spot. Quest UNDOABLE
0:15 https://www.youtube.com/watch?v=nWsY3mniuXE

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/220755145-79a099b1-eea7-4b29-9742-64a47a000e66.png)
Works okay.
