### ISSUE TITLE
[Quest] Marley's Final Flight - missing hand-in NPC

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1841]
Quest: [Marley's Final Flight](https://www.wowhead.com/quest=25120/marleys-final-flight)

Issue: All works well except two things:
1. Bael'dun Phase 2 Effects Buny and Bael'dun Phase 2 Effects Bunny (Medium) are visible to players.
2. [Marley Twinbraid](https://www.wowhead.com/npc=39188/marley-twinbraid) is not visible for players, thus players can't hand in the quest and continue the quest chain. Moving out of the zone and restarting the game did not solve either of these issues.

**Comment by UltraNix** [comment]
Fixed.
