### ISSUE TITLE
[Quest] [Dungeon] RFK Agamaggan's Charge

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1846]
After handing in the quest [Agamaggan](https://cata-twinhead.twinstar.cz/?quest=26906), player does not receive the next quest, [Agamaggan's Charge](https://www.wowhead.com/quest=26905/agamaggans-charge).

**Comment by ootxc** [comment]
Spirit of Agamaggan still does not offer this quest after finishing the previous one.
