### ISSUE TITLE
[Quest] [Important] Eric, Olaf and Baelog - 3 undoable quests and loremaster

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1852]
**Quests:**

1. [Eric, the Utility Dwarf](https://www.wowhead.com/quest=27828/eric-the-utility-dwarf)
- [Eric "The Swift"](https://www.wowhead.com/npc=46855/eric-the-swift) does not use [Eric's Charge](https://www.wowhead.com/spell=87278/erics-charge) when the spell is clicked. Quest undoable.

2. [Olaf, the Big Fella'](https://www.wowhead.com/quest=27835/olaf-the-big-fella)
- [Olaf](https://www.wowhead.com/npc=46857/olaf) does not use [Olaf's Shield Wall](https://www.wowhead.com/spell=87275/olafs-shield-wall) when the spell is clicked. Same goes for [Olaf's Mighty Shout](https://www.wowhead.com/spell=87274/olafs-mighty-shout). Quest undoable.

3. [Baelog, the Glass Cannon](https://www.wowhead.com/quest=27834/baelog-the-glass-cannon)
- [Baelog](https://www.wowhead.com/npc=46856/baelog) does not use [Baelog's Valhalla Shot](https://www.wowhead.com/spell=87276/baelogs-valhalla-shot) when the spell is clicked. Quest undoable.

4. I broke it completely for myself since when I tried to use the spells again and again I had an idea and tried to right-click the Mighty Shout (or some other spell not responding). Since then the petbar through which I could command the dwarves disappeared and the macroes listed in wowhead comments does not work either. Dismissing the pet + abandoning quests + porting to Stormwind and restarting the game there and then retaking the quests did not fix this issue. It is worthwhile to note that I do not use any addons that would change my HUD except for Carbonite Quest for better maps and quest tracking, so the issue is within vanilla HUD. As always, done on warrior so no chance of my own pet (hunter, DK) interfering with it either.

NOTE: At this moment, Badlands is the only zone where Loremaster of Eastern Kingdoms is undoable for Alliance and it all hinges on this three-in-one quest.

**Comment by UltraNix** [comment]
![Uploading image.png…]()
Works okay.

**Comment by UltraNix** [comment]
![WoWScrnShot_022223_215129](https://user-images.githubusercontent.com/80540499/220756289-71de4f18-abbf-4dbc-9858-94e73fee7790.jpg)
Works okay.
