### ISSUE TITLE
[Moved from discord] Orc shamans have hunters racials twice 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1854]
Myth
OP
 — Yesterday at 7:56 PM
Not yet, will do. Btw Orc hunters are missing their pet racials and orc shamans have it twice
 
----------------
 
Can confirm 
i believe its orc dk,warlock,hunter specific passive
https://wowwiki-archive.fandom.com/wiki/Command#:~:text=Command%20is%20a%20passive%20racial,warlock)%20by%20a%20small%20amount.
![image](https://user-images.githubusercontent.com/36106057/211962839-fe6dbd8a-852f-4983-881d-c1521dd3b728.png)

**Comment by MrTide** [comment]
Link to https://github.com/gamefreedomgit/Maelstrom/issues/1838

**Comment by UltraNix** [comment]
Already fixed.
