### ISSUE TITLE
[Moved from discord] The usual suspects

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1855]
Ædrian
OP
 — Today at 4:49 AM
Anduin disappears after a short time of following you, and he's not at his starting point either.

https://cata-twinhead.twinstar.cz/?quest=26997

https://www.youtube.com/watch?v=t5gFzC2IucE

**Comment by MrTide** [comment]
can confirm 
i believe this issue is happening once you lost him like teleporting out or after he gets stuck 
also after talking to the workers they just fell under ground
this issue happens with a lot of creatures throughout the world maybe you can find a global solution for this. and you can't get him anymore.
![image](https://user-images.githubusercontent.com/36106057/211966116-296b2f00-5868-4011-b345-0b033215634e.png)

**Comment by Greywolf59** [comment]
Whole Anduin escort worked fine for me. Never disappeared.

**Comment by UltraNix** [comment]
For me it works okay as well.
