### ISSUE TITLE
Feral Spirits spellbook + casting issues? - Enhancement Shaman

### ISSUE THREAD

**Issue by y9ssk** [gamefreedomgit/Maelstrom#1856]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
![WoWScrnShot_011123_225344](https://user-images.githubusercontent.com/33011900/211980078-1984c1fd-d768-46eb-b74a-2e903137b831.jpg)
Image of Spellbook + Macros, Feral Spirit spells missing entirely from book which seems to translate into not being readable? by usual macros I've used across other cata servers...

**Description:**
Possibly related to Tremor totem/Pets issue mentioned earlier, but I'm not able to cast my Feral Spirit abilities through commands/macros, the only way to use them is to physically click them on the pet action bar.

**How to reproduce:**
Duel/test in game, Screenshot rough example...

**How it should work:**
Correctly! :D

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51533#see-also-ability

**Comment by y9ssk** [comment]
-Addition to Feral Spirits
                 - Bash not settings not being saved when turnings off "Autocast"

**Comment by UltraNix** [comment]
@y9ssk Show me any macros you use for Feral Spirits.

**Comment by UltraNix** [comment]
No info - closing.
