### ISSUE TITLE
Tremor totem + Mind control, not breaking CC correctly. (Ext. of Earlier Issue)

### ISSUE THREAD

**Issue by y9ssk** [gamefreedomgit/Maelstrom#1857]
![WoWScrnShot_011123_231212](https://user-images.githubusercontent.com/33011900/211982911-f11027cf-88ac-4a1a-95e6-f82b1181d08e.jpg)
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mind control is a charm, Tremor is not breaking Mind Control when placed.

**How to reproduce:**
In Game Duels/test

**How it should work:**
As Read in Spell Description.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=8143#see-also-ability

**Comment by UltraNix** [comment]
Fixed.
