### ISSUE TITLE
[Quest] Maliciously Delicious unavailable - Blocks out whole zone

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1858]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Maliciously Delicious (27587) is not avaliable to players without specific pre quests being done. It should have no pre-requisites  

**How to reproduce:**
Create new Char
.skip
Ask to be made level 80/85
.tele Bogpaddle
Notice no quests are offered.

**How it should work:**
Quest 27587 should be offered regardless of any pre quests 

It should at least be acceptable after turning in [Quest 28675](http://www.wowhead.com/quest=28675)

Proof:
https://wowpedia.fandom.com/wiki/Maliciously_Delicious?so=search#Progression

2nd Proof (Notice how it shows no pre-quest requirements):
https://cata-twinhead.twinstar.cz/?quest=27587

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27587

**Comment by Greywolf59** [comment]
Wowpedia says that these breadcrumb quests are optional, so this quest should be available even without HC:SoS! or Bogpaddle prequests most likely.

**Comment by Greywolf59** [comment]
https://wowpedia.fandom.com/wiki/Maliciously_Delicious?so=search#Progression

**Comment by UltraNix** [comment]
Fixed.
