### ISSUE TITLE
Draenei Passive

### ISSUE THREAD

**Issue by Darkosz** [gamefreedomgit/Maelstrom#1862]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Draenei passive Heroic Presence is still not applied upon creation for hunters.

**How to reproduce:**
Create a Dranei Hunter and check their abilities/stats.

**How it should work:**
The racial passive should be applied.

**Database links:**
![kép](https://user-images.githubusercontent.com/26027404/212109049-fc1ec80d-a66d-4054-abe7-0656b7d9aaeb.png)

**Comment by MullichWhitemane** [comment]
![WoWScrnShot_012223_104204](https://user-images.githubusercontent.com/121984461/213909352-5779b504-01c5-4a98-b33c-4913efc0ea83.jpg)

Working now.
