### ISSUE TITLE
Stance Dance on Warrior canceling Transformation

### ISSUE THREAD

**Issue by DjaouedBen** [gamefreedomgit/Maelstrom#1863]
**Description:** Well as mentionned on the title, i tried with many transformation items / consumables, when i change stance it's cancelling transformation but i still have buff/debuff, the worse is when i tried it with Vial ( Sandstone Drake ) when you change stance it looks like i'm using cheats :p

**How to reproduce:** Get any transformation > Change stance when transformed.

**Comment by MullichWhitemane** [comment]
Also affects Rogue's stealth, and likely other similar effects (such as Druid Shapeshifting or Mage Invisibility). Will update later with a full list.

**Comment by UltraNix** [comment]
Fixed.
