### ISSUE TITLE
[Spell][Dwarf Racial] Find Treasure Not Working for some Chests

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1864]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When on a Dwarf, find treasure doesn't seem to be working

**How to reproduce:**
Create a Dwarf
.teleport Feathermoon
Fly to 30.32, 45.98
There is a "Runestone Treasure Chest", it doesn't show on the minimap

![image](https://user-images.githubusercontent.com/6482585/212115970-466a7233-c0da-4fb1-b76b-2e6327ef942c.png)

It's working fine for a Silverbound Treasure Chest found in Loch Modan (Inside the Cave at 36.17, 58.06) but then **doesn't work** for a Silverbound Treasure Chest found in Arathi Highlands (.tele Circleofeast then turn 90deg clockwise, there is a chest there against the stone at 62.65,30.34)

**How it should work:**
It should show on the minimap

**Database links:**
Example Chest: https://cata-twinhead.twinstar.cz/?object=207533

**Comment by UltraNix** [comment]
Fixed.
