### ISSUE TITLE
[Object] Empty Treasure Chests

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1865]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This seems to be a reccuring issue, but many treasure chests are empty. You can keep respawning them and sometimes you'll get an item, other times they'll be totally empty.

**How to reproduce:**
Create a Dwarf
.teleport Feathermoon
Fly to 30.32, 45.98
There is a "Runestone Treasure Chest", open it - it will contain "Empty Slot"

(Do .respawn if no chest is present or if it does contain an item, do .respawn again and it might not the next time)

![image](https://user-images.githubusercontent.com/6482585/212116328-9a76412f-f2de-4410-a621-38f15c39a6b4.png)

I have found many other treasure chests with the same issue.

Loch Modan empty chest:

![image](https://user-images.githubusercontent.com/6482585/212124937-a26a5fa5-a258-43f6-a33f-7d8440769e67.png)

A chest found in Arathi Highlands wasn't empty (.tele Circleofeast then turn 90deg clockwise, there is a chest there against the stone at 62.65,30.34) so I'm not sure what decides which chests are affected and which aren't. Whenever I've found a working chest I've looted an item so far it's been either a Blue or a Gem, I've not recieved any whites or greens - so it could be the generic loot table isn't being picked up properly by the chests?

**How it should work:**
Chests should contain items!

**Database links:**
https://cata-twinhead.twinstar.cz/?object=207533
https://cata-twinhead.twinstar.cz/?object=207472 (https://www.wowhead.com/object=207472/silverbound-treasure-chest)

**Comment by Greywolf59** [comment]
1471 was repaired. At least all the chest I came across since then had one blue item in them. I haven't come across any Runestone one though.

**Comment by Greywolf59** [comment]
Just now I found Silverbound Treasure Chest that was empty, in Dustwallow. All the others before had some blue item since the fix.
That could mean two tgings:
A: Not all IDs were repaired (I have seen every chest level has several IDs on wowhead at least)
B: The fix does not apply to looted chest that got respawned.

**Comment by Afgann** [comment]
fixed
