### ISSUE TITLE
[Client Crash] [Dungeon] Siamat

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1867]
**How to reproduce:**while fighting siamat everyone's client crashed
![image](https://user-images.githubusercontent.com/36106057/212166838-e5d34a36-b331-4552-a92a-6d56d049a8e8.png)
it was during his storm which kicks players around.
(we did a second try and it didnt cause crash)
**How it should work:** it should not crash players clients

**Comment by UltraNix** [comment]
Should be fixed.
