### ISSUE TITLE
Stonecore heroic issue with mobs

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1868]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stonecore bruiser is not using his Body Slam ability
Stonecore sentry is not running to the pack to pull more when aggroed

**How to reproduce:**
Go to stonecore heroic and check those two mobs

**How it should work:**
Stonecore bruiser should use Body Slam
Stonecore sentry should run to the packs to alert them
**Database links:**
https://www.wowhead.com/npc=42692/stonecore-bruiser#abilities;mode:normal Stonecore bruiser
https://www.wowhead.com/npc=42695/stonecore-sentry stonecore sentry

**Comment by MrTide** [comment]
Stonecore bruiser should use body slam
https://wowpedia.fandom.com/wiki/Stonecore_Bruiser
and player is also right about the sentry
![image](https://user-images.githubusercontent.com/36106057/212183760-396fcb01-170f-46fd-9727-ad209d900d0b.png)

**Comment by Afgann** [comment]
fixed

**Comment by whothatdog** [comment]
@UltraNix I can use this issue?

Stonecore Berserker are using 'Spinning Slash' too often, like every 10-15 seconds
each pack we face 3-5 Spinning Slash, I believe the timer should be longer.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/45a71467-5d35-4f4a-811d-91e58571461e)
