### ISSUE TITLE
[Dungeon][Moved from Discord] deadmines

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1869]
**How to reproduce:**
if you kill oaf on top helix can't get down anymore
![image](https://user-images.githubusercontent.com/36106057/212186487-82485c8e-c536-400a-9f42-b7cc9dced20f.png)
combat bug issue
![image](https://user-images.githubusercontent.com/36106057/212188600-0fa7531a-e021-48d6-a946-146d0fa5d289.png)
and i believe helm should not drop after winterveil
 
Mora — Today at 1:17 AM
-Cannon "DBGUID 161019" causing combat bugs
-Last boss gave xmas Helmet
-After killing Oaf, Helix didnt come down

**Comment by UltraNix** [comment]
Fixed.
