### ISSUE TITLE
[Moved From Discord][Dungeon] Scarlet Armory Herod

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1870]
Hotandspicy — Today at 1:19 AM
the boss herod can just walk through the air
![image](https://user-images.githubusercontent.com/36106057/212190027-552d9244-f1d5-4b25-8ead-933b4fab4076.png)

Hotandspicy — Today at 1:19 AM
i pulled him from above - and he just straight walked to me through the air
![image](https://user-images.githubusercontent.com/36106057/212190069-f6159d3a-d2b8-4fb5-9390-17d8d2d0ec79.png)

**Comment by PanJanuszek** [comment]
Cant reproduce anymore

![Uploading image.png…]()
