### ISSUE TITLE
[Dungeon] Deadmines - quest givers

### ISSUE THREAD

**Issue by tydeFriz** [gamefreedomgit/Maelstrom#1871]
Entering deadmines with a crossfaction party will only spawn quest givers for one of the two. Seems to be bound to party leader's

To reproduce:
- Have a party with at least 1 alliance member and 1 horde member who have never been there before
- Enter deadmines
- Go where the quest givers are

**Comment by MrTide** [comment]
This probably happens on a lot of dungeon and raids 
need to look through all of them

**Comment by UltraNixx** [comment]
Fixed.
