### ISSUE TITLE
[Spell] Mind Control has many weird behaviours

### ISSUE THREAD

**Issue by tydeFriz** [gamefreedomgit/Maelstrom#1872]
- You often cannot stop the Mind Control you are using by pressing the red X
- Mind controlled mobs don't reset position when MC expires. With some dedication, you can bring them where they really shouldn't be
- Mind controlled casters can walk after starting a cast and successfully complete it while still walking

There are also many weirdly behaving MC subject spells I am still testing, for example Razorfen Down Necromancer's Shackle Undead does is not limited to 1 target (it should be) so you can shackle like 30 mobs

**Comment by UltraNix** [comment]
Fixed.
