### ISSUE TITLE
Just Broke Stormwind Royal Guards patrol and they cleared almost all mobs behind goldshire till murlock lil islands [PATROL BUG]

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#1873]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
So I Just Broke Stormwind Royal Guards patroling Stormwind > Goldshire Area and they cleared almost all mobs behind goldshire till murlock islands teleporting midair xd

**How to reproduce:**
I`ve used gryphon master from Goldshire to Stormwind and it broke. I was flying without Gryphon to Stormwind but it did not release me in SW city and went back to Goldshire throu all the textures then back to stormwind when it let me off. So i wanted to replicate this bug and I`ve reloaded game and just used multiple times those Gryphon masters and after few attemps i saw guards patrolling SW>Goldshire area bug out.
Well they started to fly midair towards all the mobs and going towards Goldshire teleporting throu buildings and then killing all the mobs there till after murlock islands and later on as I was observing them they cleared almost whole forest from Goldshire till Tower of Azora.
Seems like guards route is bugged and their agro too big.
Please look first comment for some more screenshots 
**How it should work:**
Guards should patrol from SW city > Goldshire > Eastvale Logging Camp area killing mobs that are close to road.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=42218
https://cata-twinhead.twinstar.cz/?npc=42983
https://cata-twinhead.twinstar.cz/?npc=352
![WoWScrnShot_011323_023845](https://user-images.githubusercontent.com/122581454/212224363-d5ae605d-afa2-43cf-aa6e-1859186dc9f0.jpg)
![WoWScrnShot_011323_025320](https://user-images.githubusercontent.com/122581454/212224456-e21c8f6b-58d7-45e0-998b-aef6ada0f7a5.jpg)
![xdd](https://user-images.githubusercontent.com/122581454/212224545-3ad537ec-02aa-485a-8332-33b4e582a7bd.jpg)
![WoWScrnShot_011323_025756](https://user-images.githubusercontent.com/122581454/212224598-9557fcfc-d988-400e-94c9-9bf6f650ad40.jpg)

**Comment by Nenze** [comment]
Okay waited till they spawn again and they seem to bug out at this location by first going throu this Fence.
![WoWScrnShot_011323_034322](https://user-images.githubusercontent.com/122581454/212225815-9ed53001-d552-4662-8916-19f2e667e719.jpg)
and then starting to fly
![WoWScrnShot_011323_034306](https://user-images.githubusercontent.com/122581454/212225842-ee3d32dc-c04c-4d96-ae20-1f4b3f37fe54.jpg)
and now they got stuck at this mountain 
![WoWScrnShot_011323_034452](https://user-images.githubusercontent.com/122581454/212226044-ef30eb7d-89e8-40da-87ff-dfd273c4f297.jpg)
![WoWScrnShot_011323_034500](https://user-images.githubusercontent.com/122581454/212226053-0c87fa32-fc2d-4970-9ac5-f905bc0bf5a9.jpg)
Not sure if its helful but good luck :V

**Comment by UltraNix** [comment]
Fixed.
