### ISSUE TITLE
[Quest] The Enemy of Our Enemy - Hydronis below texture, undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1876]
Quest: [The Enemy of Our Enemy](https://www.wowhead.com/quest=14292/the-enemy-of-our-enemy)

Player needs to hand in this quest to [Lord Hydronis](https://www.wowhead.com/npc=35902/lord-hydronis).
As player approaches the island, the phase changes and you can catch a glimpse of Lord Hydronis spawning in new position and falling down through texture right away. This makes the NPC unreachable and quest undoable.

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
He works fine now but his spells does so little damage but still doable, i will keep it closed unless you wanna do some changes. thanks
