### ISSUE TITLE
[Death Knight] Dark Simulacrum issues

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1878]
DK's cannot use DS abilites due to the below error

![image](https://user-images.githubusercontent.com/121137397/212329520-fca74d0e-c115-4563-8498-9f1d4ba387b7.png)

Have found a polish report of GMs fixing this on apollo https://cata-twinhead.twinstar.cz/?issue=794

**Comment by UltraNix** [comment]
The spell used by this NPC (76578 Chain Lightning) can be casted inly on players.
No bug here.

**Comment by UltraNix** [comment]
Fixed.
