### ISSUE TITLE
All the issues with Auto-Learn

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#1879]
Affecting all classes - Mastery is not included in the autolearn. In the spellbook, it appears as if it is learned, but it's not, and if you mouse over the mastery stat, it seems as if you can benefit from it but you will always be stuck at 0% - you have to speak to your class trainer and relog for it to function (including Warrior, Gaga).

Affecting all leather, mail and plate classes - Every class learns their Armour Specialization, but a duplicate exists at the trainer that can be learned. This duplicate does not stack with the one that is taught, so this is a low priority issue.

Paladin - missing Plate Mail and mounts (Human, Dwarf, Blood Elf: Warhorse, Charger, Draenei: Exarch's Elekk and Great Exarch's Elekk, Tauren: Sunwalker Kodo and Great Sunwalker Kodo).

Warrior - missing Plate mail. 

Death Knight - missing all post-starter Runeforges (so all Runeforges at lvl57 and above). 

Hunter - missing Mail, Track Hidden and Dual Wield.

Shaman - missing Mail. 

Druid - missing Track Humanoid. 

Mage - missing all Teleport and Portal spells.

Warlock - missing Dreadsteed and Felsteed.

**Comment by MullichWhitemane** [comment]
After running a re-test:

- Mastery is taught by the autolearn for all classes, but you still need to relog for it to activate. In the mastery stat tooltip, it shows up as X thing increased by 0%. Once you relog, it corrects itself to it's intended value - f.e., 12% Illuminated Healing for Hpala.
- Paladin - mounts (Draenei: Exarch's Elekk and Great Exarch's Elekk, Tauren: Great Sunwalker Kodo).
- Death Knight - missing all post-starter Runeforges: Rune of Spellbreaking, Rune of Spellshattering, Rune of Lichbane, Rune of Swordbreaking, Rune of Swordshattering, Rune of the Fallen Crusader, Rune of the Nerubian Carapace, Rune of the Stoneskin Gargoryle
- Mage - missing all Teleport and Portal spells.
Shared Portals and Teleport: Dalaran, Shattrath
Alliance Portals and Teleports: Darnassus, Ironforge, Stormwind, Exodar, Theramore, Tol Barad alliance
Horde Portals and Teleports: Orgrimmar, Thunder Bluff, Undercity, Silvermoon, Stonard, Tol Barad horde

**Comment by MullichWhitemane** [comment]
Paladin racial mounts and Mage portals are in.

Death Knight runeforges and Mage teleports are missing.

**Comment by UltraNix** [comment]
For portals - min level is 42, as DBC states.

**Comment by UltraNix** [comment]
Fixed.
