### ISSUE TITLE
[Dungeon] Vortex pinnacle feedback 2nd full test with players

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1880]
**How to reproduce:** 
1. you should not be able to grip howling gale and lurking tempest, mob chain agrro on first mobs are not working properly pulling one mob should pull others as well 
2. altairus winds should change based on players locations, it just randomly changes even if you dont move
![image](https://user-images.githubusercontent.com/36106057/212422398-fac05399-dd85-402b-8a08-6816030c845b.png)
3. combat bugs regarding to stalker and field they should not cause combat bugs 
also looks like lurking tempest stays on combat with pets as well if they get agrro
![image](https://user-images.githubusercontent.com/36106057/212423230-3822e11f-63e9-4cad-999f-d7de0f8d74fb.png)
4. after killing second boss second teleporting wind didn't spawn
![image](https://user-images.githubusercontent.com/36106057/212423560-ee7e6464-6efc-4add-a9c6-ae91dbed6d60.png)
5. last slip streaming after second boss has no visuals 
![image](https://user-images.githubusercontent.com/36106057/212423722-d3d53aa0-c0c8-4266-b169-101ae7d310e3.png)
![image](https://user-images.githubusercontent.com/36106057/212423746-e178f185-6cab-4fdc-9d5d-d75af00193a2.png)
6. ground fields are kinda messed up
![image](https://user-images.githubusercontent.com/36106057/212424002-7dec9efd-03c3-4f26-9830-f1fbb693b2e8.png)
7. you can't silence skyfall star nor stun them you should be able to silence and stun them (i couldnt find any evidence for that its just players claim beside the fear you can see here https://youtu.be/Js9Gb56jZmc?t=1077)
8. skyfall star on last boss you can grip it which you should not be able to and also heals for some reason. it also hits all the players at the same time.. correct behavior in this video
https://www.youtube.com/watch?v=frTmymb9K4s

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
Skyfall stars (npc 45933) are casting Arcane barrage (spell 92756) too fast,  they are casting every 0.5 seconds,  This should only be casted every 2 seconds

**Comment by Afgann** [comment]
fixed
