### ISSUE TITLE
Drahga Shadowburner Issues

### ISSUE THREAD

**Issue by Darkosz** [gamefreedomgit/Maelstrom#1882]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Drahga Shadowburner at the moment casts abilities and slowly walks towards his dragon mount for the second phase and in the last phase he casts Invocation of Flames an absurd amount of times.

**How to reproduce:**
Get Drahga to 30% hp to trigger his mount phase where he will slowly stutter towards the mount while casting, then get the mount to 20% to trigger the last phase where he will cast Invocation of Flames as many times as he can over and over again.

**How it should work:**
At 30% he should stop fighting and run towards the mount, in the last phase he should cast Invocation of Flames more than usual.

**Database links:**
https://cdn.discordapp.com/attachments/1061781961124876359/1063576805564502036/image.png

**Comment by Afgann** [comment]
fixed
