### ISSUE TITLE
[Moved from Discord]  Abilities that should only be usable on 1 target at a time can be used on multiple targets at once

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1884]
![image](https://user-images.githubusercontent.com/121137397/212471518-cd2ee6a9-455d-4854-aba0-584638d860b9.png)
![image](https://user-images.githubusercontent.com/121137397/212471519-3594f3f9-a719-47d8-ba33-267fe39e5afb.png)

correction function
https://cata-twinhead.twinstar.cz/?spell=73154

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_003920](https://user-images.githubusercontent.com/122824463/212781688-160764d0-f5b5-49ca-b109-0475194a8df9.jpg)
same for hunters mark

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_005534](https://user-images.githubusercontent.com/122824463/212781927-a89be5b6-8925-4176-8b10-9eb488797bd5.jpg)
same for entangling roots

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_005936](https://user-images.githubusercontent.com/122824463/212782269-fb9668df-5323-4bb0-af9c-6608cff2b255.jpg)
same for sheep

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_010656](https://user-images.githubusercontent.com/122824463/212782904-871b6ed5-a7cf-4359-8140-b74f58a5895a.jpg)
same for bane of doom

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_010728](https://user-images.githubusercontent.com/122824463/212782918-e5aaf273-7413-4518-a47f-e25dfde2f73d.jpg)
same for fear

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_010749](https://user-images.githubusercontent.com/122824463/212782931-3dc824e4-3955-4617-8b9d-20b64e33e962.jpg)
same for curse of elements

**Comment by Hotandspicy322** [comment]
![WoWScrnShot_011723_011146](https://user-images.githubusercontent.com/122824463/212783147-e78af802-421f-4121-bbc9-255916a6737b.jpg)
same for shackle undead

**Comment by Hotandspicy322** [comment]
i have the feeling that not every of these abillities is bugged for itself , but more of a general system error that makes it possible to have it up more often as it should 
just my 2cents

**Comment by tydeFriz** [comment]
> ![WoWScrnShot_011723_010749](https://user-images.githubusercontent.com/122824463/212782931-3dc824e4-3955-4617-8b9d-20b64e33e962.jpg) same for curse of elements

Curses can be on multiple targets, the limit is only 1 curse per target

**Comment by tydeFriz** [comment]
> ![WoWScrnShot_011723_010656](https://user-images.githubusercontent.com/122824463/212782904-871b6ed5-a7cf-4359-8140-b74f58a5895a.jpg) same for bane of doom

Same for Bane of Havoc

**Comment by APTX4869s** [comment]
Add Earth Shield and Beacon of Light to the report :D
