### ISSUE TITLE
All the issues with 10v10 and 15v15 Battlegrounds that I found

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#1889]
Prefacing this by saying that Warsong Gulch and Eye of the Storm have no issues. Once the issues are fixed, I will try to involve the greater PvP community to run as many BGs as they can for a more thorough sweep.

General issues (CRITICAL):
- ~~Conquest is being rewarded for a victory even when it isn't listed as a reward (in the case of specific queueing BGs f.e.)~~
- ~~15 min Deserter debuff is not applied if someone leaves a BG early~~ (disabled for PTR)
- At the moment, cross faction queueing is impossible
- BGs that have a time limit (WSG, Twin Peaks, SotA) do not show up at the top of the screen for Horde players
![alliance](https://user-images.githubusercontent.com/121984461/212494924-458d3d06-b7b7-42e0-b7d1-5ad88e1d5cfd.PNG)
Above is for alliance, below is for horde
![horde](https://user-images.githubusercontent.com/121984461/212494941-037e6769-e38d-4177-8215-c6a02119e80a.PNG)

SotA (CRITICAL):
- Attackers are spawned outside the map on a boat that does not move, making it impossible for attackers to compete
![WoWScrnShot_011423_180413](https://user-images.githubusercontent.com/121984461/212494979-fa7047dd-cd74-41f7-8b9b-dc09f00ac55c.jpg)
- There is no Announcement for when the gates are under attack (Announcement plays when the Gate Damaged animation plays).

Twin Peaks (CRITICAL):
- Players face a random direction when spawning in
- Horde sewer portcullis does not open on game start, has to be opened manually by players
- Neither Horde or Alliance flag can be picked up, making it impossible to win the battleground

Gilneas: (HIGH)
- Flags are clickable even when you control them (although this doesn't do anything, it still shouldn't appear as clickable)
- No Power Up boxes (Berserking, Healing and Sprint) spawn

Arathi: (MEDIUM)
- Base Assault Announcements appear as a system warning instead of blue / red coloured text in chat depending on the faction
- Flags are clickable even when you control them (although this doesn't do anything, it still shouldn't appear as clickable)
- Cleo and Lady at Blacksmith don't run around together
- Resilient Victory achievement triggers any time you win

**Comment by UltraNix** [comment]
Conquest is being rewarded for a victory even when it isn't listed as a reward (in the case of specific queueing BGs f.e.)
https://wowpedia.fandom.com/wiki/Conquest_Points?oldid=2869634
`In addition, every non-rated BG that you win will also give you 50 conquest. There is no limit to how many BGs you can run this way, up to the normal conquest cap.`

**Comment by UltraNix** [comment]
`15 min Deserter debuff is not applied if someone leaves a BG early`
I can't reproduce it (tested with /afk and simply leaving the bg)

**Comment by UltraNix** [comment]
@Torpis As I said: On PTR, Deserter is disabled in order to test BGs.

**Comment by MullichWhitemane** [comment]
Tested the fixes, all of them work apart from one (which, to be fair, I didn't provide much info on).
**In Gilneas, in the following locations (where my character is exactly standing), a randomized Power-up box should spawn.**
![WoWScrnShot_013023_054306](https://user-images.githubusercontent.com/121984461/215390097-2d46638c-68a2-4956-b052-672c72e6cbb7.jpg)
![WoWScrnShot_013023_054323](https://user-images.githubusercontent.com/121984461/215390101-2e99877c-fcd1-4c10-ab10-5820cb6d5820.jpg)
![WoWScrnShot_013023_054351](https://user-images.githubusercontent.com/121984461/215390106-de6bd8aa-30e2-4776-9540-0d33c8fdd7ae.jpg)
**Similarly, in the following locations (where my character is exactly standing), a Sprint Power-up box should spawn.**
![WoWScrnShot_013023_054339](https://user-images.githubusercontent.com/121984461/215390224-d825d7c2-9a1e-4398-afb4-6f94b598b721.jpg)
![WoWScrnShot_013023_054357](https://user-images.githubusercontent.com/121984461/215390231-dfafee96-30a5-42eb-a9a6-ce483801c4fd.jpg)

**Comment by MullichWhitemane** [comment]
All the fixes are working, but Gilneas still has issues with the Power-up Boxes (to be fair, I didn't provide much info on it).

**In the following locations (where my character is standing) randomized power-up boxes should spawn.**

![WoWScrnShot_013023_055501](https://user-images.githubusercontent.com/121984461/215393955-c88f52d8-0347-4eb6-a19f-fbc9fc5f73ac.jpg)
![WoWScrnShot_013023_055606](https://user-images.githubusercontent.com/121984461/215393956-2fe00c14-938e-4dcf-9195-726e4fbaaa9e.jpg)
![WoWScrnShot_013023_055621](https://user-images.githubusercontent.com/121984461/215393960-ac9c6761-5af4-4685-a077-5222d8cd1585.jpg)

**In the following locations (where my character is standing) sprint power-up boxes should spawn.**

![WoWScrnShot_013023_055631](https://user-images.githubusercontent.com/121984461/215394035-df635339-c026-4bb9-8f19-e6534c83cb03.jpg)
![WoWScrnShot_013023_055541](https://user-images.githubusercontent.com/121984461/215394027-11ff0ad7-9dad-4e4a-98d4-ffd1c086a9e6.jpg)

**Comment by UltraNix** [comment]
Fixed.
