### ISSUE TITLE
Scatter Shot does not turn off your attacks

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#1890]
[Original report by Usepot#1811 on Discord https://discord.com/channels/1040715551531618365/1063957854995873833]

Scatter Shot does not turn off your attack when used, making it so that when you use Scatter Shot, and if your ranged shot timer is ready, you will immediately break the CC effect.
Currently, the only way around this is the following macro:
/stopattack
/cast Scatter Shot
/stopattack
As a sidenote, Scatter Shot makes the Dummies on the GM Island move around (this issue does not exist for any other Target Dummy).

**Comment by UltraNix** [comment]
Tested with melee and ranged attacks - both works okay.
