### ISSUE TITLE
[Quest] [Cata] Durable Seeds quest locks the quest line

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1898]
**How to reproduce:** there are no seed around to pick i am assuming its phasing issues since you can see them with GM on
if you dont do this quest rest of the quests wont open up so we need to fix this

**How it should work:**
you should be able to see and pick the seeds 
more details in the video
https://www.youtube.com/watch?v=5NpiFH6kPB4

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/221623025-f37d15fc-bac8-48f5-9cd7-0a5e4dd805d8.png)
Works okay.

**Comment by MrTide** [comment]
Update:
Seems to be working now
closing the issue
thank you
