### ISSUE TITLE
[Quest] [Cata] Prepping the Soil -  questID 25502

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1899]
**How to reproduce:**
Objects are missing you can't do the quest
if you dont do this quest rest of the quests wont open up so we need to fix this
also mobs around like core hound and lava surger have no basic movements might wanna take look as well

**How it should work:**
like this video : https://www.youtube.com/watch?v=FV1wsBfnQnI

**Comment by GMHiki** [comment]
Flameward - objectID 202930
Either on the incorrect phase, or quest does not shift player to correct phase.

**Comment by MrTide** [comment]
npcs that spawn are stuck inside eachother and flame guard got no hp and they are not hitting it neither
other than that it worked
![image](https://user-images.githubusercontent.com/36106057/221969713-48f24ac7-2c10-48f2-a3e4-267e3208c031.png)

**Comment by sassou5018** [comment]
Update: issue is still not fixed but the quest auto completes after standing next to the ward for a bit now

**Comment by Sawyer19** [comment]
Still not working. At least it was clickable yesterday, today not.

**Comment by Greywolf59** [comment]
Now on autocomplete totally, no need to go anywhere at all.

**Comment by UltraNix** [comment]
Fixed (autocomplete flag is set on purpose).
