### ISSUE TITLE
[Quest] [Cata]  Sethria's Demise

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1901]
**How to reproduce:** using thisalee's signal rocket should bring friendly units for help which it does but they don't fight they just follow the enemy npcs
![image](https://user-images.githubusercontent.com/36106057/212604153-f2fc53e1-50e7-4231-aeee-264a88e18940.png)
also another minor issue if you wanna take a look quest giver floating 
![image](https://user-images.githubusercontent.com/36106057/212604526-361d4039-3ec7-44fd-b2d3-bfb54d803add.png)

**How it should work:** like the video below they should fight
https://www.youtube.com/watch?v=48hUIGlLW-4

**Comment by Greywolf59** [comment]
Can confirm the bug is still present and makes the quest kinda undoable at fresh lvl 80 that starts at Hyjal quest chain and goes to Aviana branch first. Tested live as lvl 80 arms warr.
