### ISSUE TITLE
[Quest] [Cata] Return to Aviana quest hard locked the rest of the quest line

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1902]
**How to reproduce:** as you can see in the image after finishing farden talonshrike quests and getting archivement  [Beware of the 'Unbeatable?' Pterodactyl] he phases out and you can't get the quest related to him afterwards so you get hard locked for rest of the quest line 
![image](https://user-images.githubusercontent.com/36106057/212605948-ad092d01-47f7-4cd5-955c-d30a94e71913.png)
i can only see him with .gm on
![image](https://user-images.githubusercontent.com/36106057/212605925-6ca08d8b-b101-451f-8624-791c9b6e9412.png)

**How it should work:** npc should not phase out and offer the last quest to you also he got a daily for you to do later 

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=25560

**Comment by Greywolf59** [comment]
I see the fix for this was uploaded to PTR today. Connected to this new issue? https://github.com/gamefreedomgit/Maelstrom/issues/2260

**Comment by MrTide** [comment]
you can see both phases at the same time now while being on [The Hatchery Must Burn](https://wowpedia.fandom.com/wiki/The_Hatchery_Must_Burn) quest after doing the quest and accepting the quest everything goes back to normal other than that there are no issues 
![image](https://user-images.githubusercontent.com/36106057/221967485-736b2921-5a83-440d-8d3f-c0f2310d0e06.png)

**Comment by UltraNix** [comment]
Fixed.
