### ISSUE TITLE
[Quest][NPC][Cata] Signed in Blood

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1904]
**How to reproduce:**
You should be able to grab only one twilight recruit and you should not be able to do that without the quest, it causes issues for the players that wanna do the quest later as well since one person with or without the quest can grab them all
note: you can even talk to the npc that is following you to grab him again it should not work like that

**How it should work:**
you should only be able to grab one npc and if you decide to grab more than one other one should run away and you should have the quest in order to do that
more details in the video: https://www.youtube.com/watch?v=2XP-xYo63fU

**Comment by MrTide** [comment]
Update:
Same issue persists, you should be able to only grab one of them
![image](https://user-images.githubusercontent.com/36106057/221965749-5cddc7ac-4b5b-43d7-8b1a-2b13fec6b491.png)

**Comment by UltraNix** [comment]
Fixed.
