### ISSUE TITLE
[Quest][Cata] The Firelord "Hard lock"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1908]
**How to reproduce:** portal to next part of the event is not working at all i couldnt test it out, rest of the quest line is locked
![image](https://user-images.githubusercontent.com/36106057/212622152-ad191186-bc1d-4276-8b22-1c3e86007fe1.png)

**How it should work:** quest teleporter/ event should work
https://www.youtube.com/watch?v=s5yDQcIB_lU
https://www.youtube.com/watch?v=Vsiekddcw7s

**Comment by UltraNix** [comment]
Is it the last quest in the chain?

**Comment by Greywolf59** [comment]
Looks like. Last of the big chain. Should only open https://www.wowhead.com/quest=27398/the-battle-is-won-the-war-goes-on as the last one.

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
credit is not working

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/223704691-a157476e-ce5f-4444-b4b1-a9139b20dd55.png)
The player was near Cenarius?

**Comment by Greywolf59** [comment]
Currently on autocomplete. Should be mentioned.
