### ISSUE TITLE
[On hold for now][Quest][Event][Content 4.2.0]Through a Glass, Darkly

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1910]
**How to reproduce:**
first time you enter the dungeon dragon name was unknown i had to go out reset and go in again in order to talk to her
wraiths activate but wont hit you
![image](https://user-images.githubusercontent.com/36106057/212633519-a610e759-84ff-4fc3-9a9b-1c9a8c536fda.png)
event worked partly although she was keep going through the wall couple times after reaching wraith she completely stopped and i couldnt finish it anymore
![image](https://user-images.githubusercontent.com/36106057/212634169-910fd062-44c6-45f1-9d86-333a1e0cef9d.png)

**How it should work:**
this is how event should be working : part 1https://www.youtube.com/watch?v=0qudG2YzqIk
part2 : https://www.youtube.com/watch?v=m5LRwBs9Ra8

**Comment by UltraNix** [comment]
#3827
