### ISSUE TITLE
[Event][Cata] Vermillion Redoubt

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1911]
**How to reproduce:** event in this area is not fully working, there are no running npcs, not enough waves of twilight abductors( some dont move which also effects a quest called "Far from the Nest") , the limited fights that are going on finish in a few seconds (or dont fight at all) since friendly npcs kill them quickly, there is no sense of war
![image](https://user-images.githubusercontent.com/36106057/212643072-91c5e5cb-e433-4ca0-8e21-5cc967b7f48b.png)

**How it should work:** full event can be seen while doing the quest  Encroaching Twilight : https://www.youtube.com/watch?v=V9NSW84ACtw
https://www.youtube.com/watch?v=2UzMVRSfO0U

**Comment by MrTide** [comment]
similar case https://github.com/gamefreedomgit/Maelstrom/issues/2989

**Comment by PanJanuszek** [comment]
Npc's are running with egg on the should to twilight portal, then leave egg on it. It will despawn in 5min. You can steal egg from shoulder or after killing Twilight Abductor.
