### ISSUE TITLE
[Quest] [Cata][NPC] Draconic Mending and Life from Death and Vermillion sentinels

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1912]
**How to reproduce:** Draconic Mending is not working properly nothing is happening
event is not scripted 
![image](https://user-images.githubusercontent.com/36106057/212646878-96b06a60-36c6-42f7-a803-c7d5862939e8.png)
![image](https://user-images.githubusercontent.com/36106057/212647239-a4731e43-7a33-4e8e-8363-a32452b24cfb.png)

twilight wyrmkillers are on the ground dead for quest Life from Death
![image](https://user-images.githubusercontent.com/36106057/212651896-90b2501e-9b69-4a82-8f87-364953df787d.png)

location :
![image](https://user-images.githubusercontent.com/36106057/212647123-a3c1fe47-da2f-4717-907b-e9d925a7595d.png)
![image](https://user-images.githubusercontent.com/36106057/212647172-a7b3f0af-ec5a-451f-be85-9c6fdfdeb81e.png)
![image](https://user-images.githubusercontent.com/36106057/212647203-c9e956d4-9ed6-4bb5-bc6a-83395b215f78.png)

**How it should work:**
for quest: Draconic Mending
every a few mins npc acridostrasz and celastrasza land on the ground after fighting with twilight wrymkillers on the sky and wave of Vermillion menders run to the dragon and start healing it i believe and you need to defend those and once you defended the dragons they start flying again and repeats for next players 
Like this video: https://www.youtube.com/watch?v=tEDPn7N3dHw
it can be seen in this video as well (flying and landing process): https://www.youtube.com/watch?v=jYPDOIKmAOo
for quest:  [Life from Death] you should be able to use item [Ruby Seeds] on dragonkin corpses that you killed to finish the quest like this video: https://www.youtube.com/watch?v=QxXkNh3UXK0
And regarding to [Vermillion sentinels](https://cata-twinhead.twinstar.cz/?npc=45503#objective-of) i dont think they should be on the ground right now they are lvl 1 and got 210hp which is incorrect, they should be flying ( you can see them in the sky in this video https://www.youtube.com/watch?v=1fAe4jwSq_o)
![image](https://user-images.githubusercontent.com/36106057/212651457-1af17458-5b76-45d2-84cb-ed261ea4d21a.png)

**Database links:** https://cata-twinhead.twinstar.cz/?quest=27505

**Comment by PanJanuszek** [comment]
Rewritten, menders are coming to dragon and try to heal them. Vermillion drake will attack sometimes the mender. 2 min respawn per finish q
