### ISSUE TITLE
[Moved from Discord][Shadow priest T13] Regalia of Dying Light 4 set not working correctly 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1913]
https://youtu.be/EM5HHDgz7jk

T13 4 set bonus does not proc when shadowy apparition hits however it does work with shadowfiend.  

Low prio as T13 fix

**Comment by MullichWhitemane** [comment]
Still doesn't work - just don't fix until we're actually at T13 content. For any future bug reporters - if I see any more post 4.0.6 content on this Github, I will immediately snipe it
