### ISSUE TITLE
[Quest] [Cata][NPC] "Patchwork Command AKA Mathias`s Command" ,  Easy Pickings, dragonmaw pass event and missing npcs

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1914]
**How to reproduce:** 
Npcs completely missing not even phased out, i couldnt turn in the quests nor could accept the next quests (this is a multi phase area both for horde and alliance)
location
![image](https://user-images.githubusercontent.com/36106057/212655108-ee8a5f21-ce1f-4a31-b479-7561ed53a505.png)
![image](https://user-images.githubusercontent.com/36106057/212655049-e9443c97-149c-48a4-a15a-32a4a31faa98.png)
there is also missing event here there are no fights 
![image](https://user-images.githubusercontent.com/36106057/212662523-8fd9c0a6-60a0-43db-81ac-842eead48c54.png)
since npcs in the area are missing you won't be able to finish quests like Easy Pickings quest both alliance and horde side.

**How it should work:** 
Horde: 
[Patchwork Command](https://cata-twinhead.twinstar.cz/?quest=27576) npcs should be there like this video:  https://www.youtube.com/watch?v=1fAe4jwSq_o
quest: https://cata-twinhead.twinstar.cz/?quest=27576
[Patch](https://cata-twinhead.twinstar.cz/?npc=47492) starts 3 quests and ends 3 quests
other npcs in this area are: 
Full list which pretty much all of them are missing https://wowwiki-archive.fandom.com/wiki/Dragonmaw_Pass
[Patch ](https://cata-twinhead.twinstar.cz/?npc=47492)
[Grit](https://cata-twinhead.twinstar.cz/?npc=47495) , 
[newt](https://cata-twinhead.twinstar.cz/?npc=47496) , 
[Ticker](https://cata-twinhead.twinstar.cz/?npc=47497) , 
[axebite soldier](https://cata-twinhead.twinstar.cz/?npc=47494) , 
[volt](https://cata-twinhead.twinstar.cz/?npc=47498) , 
[warlord krogg](https://cata-twinhead.twinstar.cz/?npc=47493) (multiphased)
[twilight spearwarder](https://cata-twinhead.twinstar.cz/?search=twilight+spearwarder) some on foot some riding both listed , 
[bilgewater marksman](https://cata-twinhead.twinstar.cz/?npc=47489) , 
[twilight caravan chest](https://cata-twinhead.twinstar.cz/?search=twilight+caravan+chest) and its [location](https://www.youtube.com/watch?v=GtJNu4aXHH8) (chest is already ingame) ,
 [Twilight's Hammer Horse](https://cata-twinhead.twinstar.cz/?npc=47457)
event fight can be seen here : https://www.youtube.com/watch?v=GLu9wB7MbNU

alliance side: 
Master Mathias Shaw : https://cata-twinhead.twinstar.cz/?npc=47592
also starts 3 and ends 3 quests
events/npc can be seen:
Mathias`s Command: https://www.youtube.com/watch?v=QY5gIIeY8cI 
more detail: https://www.youtube.com/watch?v=_GbnvM7GSk8

[highbank marine](https://cata-twinhead.twinstar.cz/?npc=47597)
[Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=47592)
[SI:7 Marksman](https://cata-twinhead.twinstar.cz/?search=si%3A7+marksman)

quest: Easy Pickings horde: https://www.youtube.com/watch?v=J4nHrCvFeyg
Alliance: https://www.youtube.com/watch?v=GUVtxiHTdFI

**Comment by DorizarN** [comment]
NPC still does not spawn.

**Comment by PanJanuszek** [comment]
Spawned, phased + vermillion doubt also
