### ISSUE TITLE
[Quest][NPC][Cata] Precious Goods

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1915]
**How to reproduce:** 
event is not scripted in area, npcs are missing so its impossible for players to do this quest
location of the creatures and their behaviors/fights are shown and explain here https://github.com/gamefreedomgit/Maelstrom/issues/1914
![image](https://user-images.githubusercontent.com/36106057/212667730-0e2d3254-31a8-4a30-bafe-5079de7eb7f3.png)

**How it should work:**
Full event here:
[Horde](https://www.youtube.com/watch?v=GLu9wB7MbNU)
[Alliance](https://www.youtube.com/watch?v=_GbnvM7GSk8)

**Comment by PanJanuszek** [comment]
Both factions have imitation of battle between twilight and horde/alliance. Fixed
