### ISSUE TITLE
Feralas Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1916]
1. [Hero's Call: Feralas!](https://www.wowhead.com/quest=28511/heros-call-feralas)
- Not sure if it opens further quests. Needs to be retested.
- I think [Signs of Change](https://www.wowhead.com/quest=25447/signs-of-change) were available only after I handed in [The Wilds of Feralas](https://www.wowhead.com/quest=14410/the-wilds-of-feralas).

2. [Sturdy Treasure Chest](https://www.wowhead.com/object=207487/sturdy-treasure-chest)
- at 40.3/8.6 it was empty.

3. [More Than Illness](https://www.wowhead.com/quest=25394/more-than-illness)
- post-complete event /says are too fast
- [Ysondre](https://www.wowhead.com/npc=39407/ysondre) (?) should be higher.
- 6:45 https://www.youtube.com/watch?v=HbnyQjv5g8I

4. [Quantas Jonespyre](https://www.wowhead.com/npc=44397/quantas-jonespyre)
- Does not offer trade.

5. [Shandris Feathermoon](https://www.wowhead.com/npc=3936/shandris-feathermoon)
- Her gossip states "Need TXT YTDB"

6. [General Shandris Feathermoon](https://www.wowhead.com/quest=26402/general-shandris-feathermoon)
- post-completion event is sped up a lot.
- 3:05 https://www.youtube.com/watch?v=Pvw_86Jt5gc

7. [Vivianna](https://www.wowhead.com/npc=7947/vivianna)
- Spawned twice.

8. [The Battle of Sardor](https://www.wowhead.com/quest=25304/the-battle-of-sardor)
- Player's position on [Karonas](https://www.wowhead.com/npc=40232/karonas) is likely wrong. Camera seems a bit off, there is breath timer going on and at one point.
- There is no breathing bar on video and camera looks better too: 0:45 https://www.youtube.com/watch?v=CUAgdaRIGec

9. [Runestone Treasure Chest](https://www.wowhead.com/object=207533/runestone-treasure-chest)
- The one at 30.3/46.2 was empty.

10. [Sensiria](https://www.wowhead.com/npc=40131/sensiria)
- should become visible only after handing in [The Lost Apprentice](https://www.wowhead.com/quest=25350/the-lost-apprentice) and say: "Help… please. If you can hear me, help…"
- https://www.wowhead.com/npc=40131/sensiria#comments:id=1322449
- 2:45 https://www.youtube.com/watch?v=3Tpp3fFVxmY
- 1:20 https://www.youtube.com/watch?v=fQ9PUFN3OMM

11. [Gordok Hyena](https://www.wowhead.com/npc=12418/gordok-hyena)
- All of them are sitting on spot and sleeping. Most of them should be normally walking around.

12. [Seyala Nightwisp](https://www.wowhead.com/npc=40367/seyala-nightwisp)
- No flight path connected to this one when player wants to fly from here.

13. [Falfindel Waywarder](https://www.wowhead.com/npc=40369/falfindel-waywarder)
- Missing his /says
- https://wowpedia.fandom.com/wiki/Falfindel_Waywarder?so=search

14. [Large Leather Backpacks](https://www.wowhead.com/object=164953/large-leather-backpacks)
- Should not be ingame. Removed with Cata.
- https://wowpedia.fandom.com/wiki/Large_Leather_Backpacks?so=search

15. [Griniblix the Spectator](https://www.wowhead.com/npc=14395/griniblix-the-spectator)
- His gossip states: "Need TXT YTDB".
- Probably should be: "Listen, if you're looking for a fight, [Skarr](https://wowpedia.fandom.com/wiki/Skarr_the_Broken) was headed towards the [Lariss Pavilion](https://wowpedia.fandom.com/wiki/Lariss_Pavilion), and [The Razza](https://wowpedia.fandom.com/wiki/The_Razza) was soaring in the direction of the [New Thalanaar](https://wowpedia.fandom.com/wiki/New_Thalanaar). Just be sure to let me in on the betting before the bloodbath begins!"
- https://wowpedia.fandom.com/wiki/Griniblix_the_Spectator?so=search
- https://www.wowhead.com/npc=14395/griniblix-the-spectator#comments:id=1205449:reply=239667

**Comment by UltraNix** [comment]
Fixed.
