### ISSUE TITLE
[Quest][NPC][Cata] The Gates of Grim Batol and If the Key Fits + Missing creatures

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1917]
**How to reproduce:** npcs ( both friendly and hostile) in this whole area are missing.
this area is multi phase both alliance and horde got their own phasing
![image](https://user-images.githubusercontent.com/36106057/212677427-ecba6d36-70bb-41f3-a116-b524b23b1a4e.png)
location:
![image](https://user-images.githubusercontent.com/36106057/212677386-8a3a6422-3617-4fec-83be-795a5891034e.png)
object phasing is also incorrect more details in the videos below
right now both gates are in the same phase i believe
![image](https://user-images.githubusercontent.com/36106057/212678083-96d24fba-bd38-4dae-bb19-82c6226c7770.png)

**How it should work:**
[If the Key Fits](https://www.youtube.com/watch?v=k6PV-9M4VN8&t=63s) 
Npcs in this area (horde+hostile npcs): please dont forget about their basic movements
full list: https://wowwiki-archive.fandom.com/wiki/Dragonmaw_Pass
examples: (whole area is empty)
[axebite soldier](https://cata-twinhead.twinstar.cz/?npc=47505)
[warlord krogg](https://cata-twinhead.twinstar.cz/?npc=47493)
[twilight sentinel](https://cata-twinhead.twinstar.cz/?npc=47406)
[twilight guardsman](https://cata-twinhead.twinstar.cz/?npc=47394)
[Twilight Cryomagus](https://cata-twinhead.twinstar.cz/?npc=47409) 
[Bound Groundshaker](https://cata-twinhead.twinstar.cz/?npc=47410)
[twilight stalker](https://cata-twinhead.twinstar.cz/?npc=47401)
[twilight earthbinder](https://cata-twinhead.twinstar.cz/?npc=47407)
full run for If the Key Fits: https://www.youtube.com/watch?v=iqjec4nueZw
full run for The gates of grim batol: https://www.youtube.com/watch?v=iqjec4nueZw

Alliance: missing npc : [SI:7 marksman](https://cata-twinhead.twinstar.cz/?search=si%3A7+marksman)
highbank marine : https://cata-twinhead.twinstar.cz/?npc=47597 and https://cata-twinhead.twinstar.cz/?npc=47685
full run for If the Key Fits only: https://www.youtube.com/watch?v=q599mBDa4Mg

**Comment by PanJanuszek** [comment]
Spawned area, fixed gates
