### ISSUE TITLE
[Quest][NPC][Cata] Pressing Forward

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1918]
**How to reproduce:** since previous quests mentioned [here](https://github.com/gamefreedomgit/Maelstrom/issues/1917) are not working, players can't access or complete this quest neither, both horde and alliance.
also same npcs explained on [this case](https://github.com/gamefreedomgit/Maelstrom/issues/1917)  are missing along the way
(npc [celen](https://cata-twinhead.twinstar.cz/?npc=47605) is not missing)
![image](https://user-images.githubusercontent.com/36106057/212680324-86d0347d-50b9-4008-8083-0c930f86e46f.png)

**How it should work:** like this videos: 
horde: https://www.youtube.com/watch?v=Ul4IujPnF0Q
alliance: https://www.youtube.com/watch?v=5-XS4valOo0

**Database links:**
horde: https://cata-twinhead.twinstar.cz/?quest=28093
alliance: https://cata-twinhead.twinstar.cz/?quest=28109

**Comment by PanJanuszek** [comment]
Both faction have his own 5-men team to push forward, with event nearby the gate. Fixed
