### ISSUE TITLE
[Quest][NPC][Cata] Paving the Way

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1919]
**How to reproduce:**
Due missing npcs and previous quests, this quest is not doable by the players
more info here: https://github.com/gamefreedomgit/Maelstrom/issues/1917
both horde and alliance

**How it should work:**
Like this video: 
horde: https://www.youtube.com/watch?v=XyKwXDwj4uc
alliance: https://www.youtube.com/watch?v=AYKWvx-2_ww

**Comment by PanJanuszek** [comment]
Whole area is phased, spawned and fixed.
