### ISSUE TITLE
[Quest][NPC][Cata] Enter the Dragon Queen

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1920]
**How to reproduce:** after finishing quest https://github.com/gamefreedomgit/Maelstrom/issues/1918 this quest becomes available which is not at this moment.
![image](https://user-images.githubusercontent.com/36106057/212684626-31c53c40-266c-4808-8514-cc12337c2aaf.png)
also i dont think these two are supposed to be here or visible for players posted the gps coordinates in the image
![image](https://user-images.githubusercontent.com/36106057/212685845-be9b9d22-2251-4cc0-892a-496fd1fd23ee.png)
I tried to add the quest manually and do the quest but sadly event here is not scripted at all neither horde or alliance can do it

**How it should work:**
after finishing Pressing Forward quest it should become available
[wowhead](https://www.wowhead.com/quest=28712/enter-the-dragon-queen#comments:id=1384306) comment from back in the day 
![image](https://user-images.githubusercontent.com/36106057/212685063-425c9ebe-6cae-43f2-a89f-acca8ae92884.png)
![image](https://user-images.githubusercontent.com/36106057/212685225-58977e59-3c48-485a-b453-61578423bc25.png)
[Enter the Dragon Queen](https://wowpedia.fandom.com/wiki/Enter_the_Dragon_Queen)

life binder waypoints/trigger should be corrected i believe they are related to this quest https://github.com/gamefreedomgit/Maelstrom/issues/1921

whole quest: https://www.youtube.com/watch?v=m0UPjZWUt3U

**Comment by PanJanuszek** [comment]
Removed these spawns, camera quest fixed
