### ISSUE TITLE
[Quest][NPC][Cata] Battle of Life and Death

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1921]
**How to reproduce:**
Since quest https://github.com/gamefreedomgit/Maelstrom/issues/1920 was not doable and npc was missing i was unable to get the quest after that, although even tho celen was not missing in that area there was a few missing npcs like [vermillion vanguard](https://cata-twinhead.twinstar.cz/?npc=49910)
right now nothing about to this event/quest works, both horde and alliance

**How it should work:** this is how quest is supposed to work
https://www.youtube.com/watch?v=w9ZUC4SMUCs

**Comment by PanJanuszek** [comment]
Quest is finished. Will be pushed on master soon.
