### ISSUE TITLE
[Quest][NPC][Cata] and the Sky Streaked Red

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1922]
**How to reproduce:** quest after [Battle of Life and Death](https://github.com/gamefreedomgit/Maelstrom/issues/1921) is offered to the players by celen but sadly since its not working its impossible to finish it (both horde and alliance)
even if you try to complete it manually with command there is no npc to talk to
![image](https://user-images.githubusercontent.com/36106057/212690171-18fbd950-1d3f-49ad-b197-6d17e81ea3b5.png)

**How it should work:** this is how its supposed to work : https://www.youtube.com/watch?v=O8crhIc-S48
missing npcs at the end of the quest line: 
[vermillion slayer](https://cata-twinhead.twinstar.cz/?npc=47798)
[Lirastrasza](https://cata-twinhead.twinstar.cz/?npc=47902)
[baleflame](https://cata-twinhead.twinstar.cz/?npc=47905)
[Velastrasza](https://cata-twinhead.twinstar.cz/?npc=47904)
[vermillion ashmaw](https://cata-twinhead.twinstar.cz/?npc=47799)
GPS: 
![image](https://user-images.githubusercontent.com/36106057/212691808-84a4aaf8-26e8-4d67-b917-44938516d2ed.png)

**Comment by PanJanuszek** [comment]
Whole area need to be spawned. IN_PROGRESS

**Comment by PanJanuszek** [comment]
Fixed
