### ISSUE TITLE
[Quest][NPC][Cata] Following the Young Home

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1924]
**How to reproduce:** you are supposed to use quest item called  [Mother's Flame] on bunch of eggs to free some [obsidian whelps ](https://cata-twinhead.twinstar.cz/?npc=48394) but sadly objects/triggers/stalkers are missing ( i couldnt find the eggs name sadly)
![image](https://user-images.githubusercontent.com/36106057/212699936-1629d879-2c33-4d11-ab90-689417be8646.png)
vermillion skyscreamer corpses are missing 
![image](https://user-images.githubusercontent.com/36106057/212701260-d688f708-70d0-4a72-93ab-af8bcb3dbe0c.png)
couldnt finish the quest because [baleflame ](https://cata-twinhead.twinstar.cz/?npc=47905) and mini event before meeting him was missing 
note: npc that offers the quest was also missing more details here: https://github.com/gamefreedomgit/Maelstrom/issues/1923
also [Obsidian Whelp](https://cata-twinhead.twinstar.cz/?npc=48394) inside of the cave are missing

**How it should work:** after destroying the eggs you are supposed to follow obsidian whelps to a cave nearby like [ this video](https://www.youtube.com/watch?v=AoUKjlFymXM)
[vermillion skyscreamer](https://cata-twinhead.twinstar.cz/?npc=47780) corpses should be there 
this is how quest supposed to work : https://www.youtube.com/watch?v=AoUKjlFymXM

**Comment by Sketish** [comment]
Fixed
