### ISSUE TITLE
[Quest][NPC][Cata] Last of Her Kind

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1927]
**How to reproduce:** after quest [Following the Young Home](https://github.com/gamefreedomgit/Maelstrom/issues/1924) you are supposed to accept [Last of Her Kind](https://cata-twinhead.twinstar.cz/?quest=28247) but quest giver is missing (i was able to add him temporarily to finish the previous quest which i also used command to finish) and after getting the quest nothing works.. no event.. no fight nothing .. also quest just auto complete itself.

**How it should work:** this is how its supposed to work: https://www.youtube.com/watch?v=fRG7In8eSwE

**Comment by PanJanuszek** [comment]
Fixed, battle with Obsidia is scripted
