### ISSUE TITLE
[Quest][NPC][Cata] Four Heads are Better than None

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1928]
**How to reproduce:**
Beeble'phod got too much HP to kill he is supposed to have 154k HP according to [this DB](https://cata-twinhead.twinstar.cz/?npc=46018) also he didnt cast anything 
[Npc Za'brox ](https://cata-twinhead.twinstar.cz/?npc=46017) is not casting anything 
also this quest should not be available before Signal the Attack
both horde and alliance
![image](https://user-images.githubusercontent.com/36106057/212712821-a2378c80-4ed1-4470-bb2c-0a4436336ba1.png)
![image](https://user-images.githubusercontent.com/36106057/212712511-87ff25e3-7e44-4cb9-b260-14b6a68707b8.png)
also you can get multiple of them i dont think thats how its supposed to work
![image](https://user-images.githubusercontent.com/36106057/212716023-8adc3fda-4e0d-4eec-952e-671d2c08989b.png)
i got one from lady cozwynn and another one got offered to me automatically after doing Signal the Attack

**How it should work:** Beeble'phod  should have less hp and also cast spells
Npc Za'brox should cast spells
like this video: https://www.youtube.com/watch?v=xiFBh7_TRPU

[Signal the Attack](https://cata-twinhead.twinstar.cz/?quest=27498)

**Comment by PanJanuszek** [comment]
Not in repro anymore
