### ISSUE TITLE
[Quest][NPC][Cata] Kor'kron Drop and SI:7 Drop

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1930]
**How to reproduce:** You can't get wind rider nor Wildhammer Hellions from the npcs quest is not scripted properly
![image](https://user-images.githubusercontent.com/36106057/212714624-a127935d-08a6-49f4-a60f-79e40b69ec6b.png)

**How it should work:** like this video: 
horde: https://www.youtube.com/watch?v=IZWikEye9NM
alliance: https://cata-twinhead.twinstar.cz/?quest=27490

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3085

**Comment by PanJanuszek** [comment]
Alliance and horde should have raiders available after gossip click. Drop point trigger is also spawned with proper model
