### ISSUE TITLE
[Quest][NPC][Cata] Up to the Citadel

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1931]
**How to reproduce:** neither horde or alliance side of the quest is scripted you simply can't do this quest.
**How it should work:**
also after accepting quest  Up to the Citadel for both alliance and horde side fight should reach inside of this area/castle as you can see the friendly and hostile creatures fighting inside now instead of outside and around the castle, basically you enter a new phase
alliance side: https://www.youtube.com/watch?v=SKprtGWG-vw
horde side: https://www.youtube.com/watch?v=-WY3UdlJ5ug

**Comment by PanJanuszek** [comment]
Both commanders are in phase, visible after Signal Attack quest
