### ISSUE TITLE
[Quest][NPC][Cata]  Signal the Attack, Ogres & Ettins and missing npcs 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1932]
**How to reproduce:**
quest item for signal the attack is not working at all
and this quest should be offered after doing move the mountain i got it twice once from npc before doing this quest and once after doing this quest which offered automatically 
![image](https://user-images.githubusercontent.com/36106057/212871885-686a8b90-8c27-48af-8b6a-5482af0f157e.png)
Ogres & Ettins not doable due missing npcs
Full list of creatures here : https://wowwiki-archive.fandom.com/wiki/Twilight_Gate
[Bloodeye mage](https://cata-twinhead.twinstar.cz/?npc=45795)[Bloodeye Brute](https://cata-twinhead.twinstar.cz/?npc=45787) are missing from the area 
[Twilight ettin](https://cata-twinhead.twinstar.cz/?npc=45838) is completely missing from the area 
![image](https://user-images.githubusercontent.com/36106057/212710943-474b4fd5-ddb4-4713-84db-83b917880eb4.png)
Horde side:
friendly [Crushblow Warrior](https://cata-twinhead.twinstar.cz/?npc=45798) are missing from the area 
they can be seen here in this video: https://www.youtube.com/watch?v=GZ_WBRxdNOc
alliance side : 
[Victor's Point Gryphon](https://cata-twinhead.twinstar.cz/?search=Victor%27s+Point+Gryphon) are missing
[Victor's Point Wildhammer](https://cata-twinhead.twinstar.cz/?search=Victor%27s+Point+Wildhammer) are missing
they can be seen in this video fighting: https://www.youtube.com/watch?v=YZNQhP6CPvE
[Skullcrusher the Mountain](https://cata-twinhead.twinstar.cz/?npc=45644)  is missing you can see him in [this video](https://www.youtube.com/watch?v=bxl_flSvvI8)
 
**How it should work:** Signal the Attack should work like this video: https://www.youtube.com/watch?v=X0q9mG27X5M
Ogres & Ettins should work like these videos: https://www.youtube.com/watch?v=YZNQhP6CPvE
 https://www.youtube.com/watch?v=GZ_WBRxdNOc
missing npcs should be restored

**Comment by PanJanuszek** [comment]
Not in repro anymore
