### ISSUE TITLE
[Quest][NPC][Cata] Move the Mountain

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1933]
**How to reproduce:** quest is not scripted and npc related to him is missing
more info about missing npc can be found here: https://github.com/gamefreedomgit/Maelstrom/issues/1932
also object that you are supposed to use to trigger the event is also missing

**How it should work:**
we need to script the event and add the npc and missing object.
Move the Mountain quest should be available before signal the attack quest and open up signal the attack quest afterwards, i was able to do signal the attack quest first.
![image](https://user-images.githubusercontent.com/36106057/212725166-8be4fa77-40b8-48e1-928a-3aaf6d526fe3.png)
![image](https://user-images.githubusercontent.com/36106057/212725209-37fb8020-c53f-45e2-a589-51d4d17220d7.png)
![image](https://user-images.githubusercontent.com/36106057/212725410-3f377d0e-aae9-440b-bd9e-ddb93218a2b0.png)

Like this video : https://www.youtube.com/watch?v=bxl_flSvvI8

**Comment by PanJanuszek** [comment]
Not in repro anymore
