### ISSUE TITLE
Hunter pet below level 10 is perma passive

### ISSUE THREAD

**Issue by Kolbeinnthor** [gamefreedomgit/Maelstrom#1936]
When below level 10 your hunter pet doesn't do anything, it should be automatically on defensive but it seems to be perma passive.
Make it automatically defensive not passive to fix :-)

**Comment by MullichWhitemane** [comment]
Couldn't recreate this issue, please try to recreate exactly what happened in your playthrough and attach relevant evidence.

**Comment by UltraNix** [comment]
It's not passive, but assist. Also tested - works okay.
