### ISSUE TITLE
[Quest][Cata][Npc] Just You and Garona and Just You and Mathias

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1940]
**How to reproduce:** 
horde: [Garona Halforcen](https://cata-twinhead.twinstar.cz/?npc=45675) is at wrong location for this quest
alliance: [Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=45796) doesn't exist at all
they also have quest of their own which they are not offering 
more details here: https://wowpedia.fandom.com/wiki/Just_You_and_Garona
they should start offering these quest lines right after 
![image](https://user-images.githubusercontent.com/36106057/212872387-7c3f7c5b-cf5f-482c-9965-a0da15720368.png)

**How it should work:**
Garona Halforcen location: https://www.youtube.com/watch?v=LERDaqcp9Xc
Master Mathias Shaw location: https://www.youtube.com/watch?v=suUVtfLmDuo

quests: [horde](https://cata-twinhead.twinstar.cz/?quest=27638) [alliance](https://cata-twinhead.twinstar.cz/?quest=27636)

**Comment by PanJanuszek** [comment]
Not in repro anymore
