### ISSUE TITLE
[Quest][Cata][Npc] Dark Assassins + Missing creatures

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1941]
**How to reproduce:** npcs are missing nor this quest offered by the npcs you can't finish the quest.

Missing npcs in this area ( please also pay attention to their HP pools some have incorrect values right now in DB)
**[Dark assassins](https://cata-twinhead.twinstar.cz/?npc=46202) are missing from the server** which are quest objective reported in this report
[enslaved tempest](https://cata-twinhead.twinstar.cz/?npc=46328) also missing
[Twilight Vindicator](https://cata-twinhead.twinstar.cz/?npc=46203) also missing
[Corrupted Elementalist](https://cata-twinhead.twinstar.cz/?npc=46204) also missing
[Citadel Veteran](https://cata-twinhead.twinstar.cz/?npc=46205) as well
[Enslaved Inferno](https://cata-twinhead.twinstar.cz/?npc=46327) missing 
[Twilight Skyterror ](https://cata-twinhead.twinstar.cz/?search=Twilight+Skyterror) missing ( which they are supposed to be dead in this video you can see a player doing it for a quest https://www.youtube.com/watch?v=FV3dKjdbvWI
)
[Dame Alys Finnsson](https://cata-twinhead.twinstar.cz/?npc=46341) missing 
[Mia the Rose](https://cata-twinhead.twinstar.cz/?npc=46343) missing 
[Master Klem](https://cata-twinhead.twinstar.cz/?npc=46342) missing 
[Blindeye the Guardian](https://cata-twinhead.twinstar.cz/?npc=46399) missing 
[Earthcaller Yevaa](https://cata-twinhead.twinstar.cz/?npc=46242) missing 
[Countess Verrall](https://cata-twinhead.twinstar.cz/?npc=46413) missing
[Initiate Goldmine](https://cata-twinhead.twinstar.cz/?npc=46243) missing
[Lord Cannon](https://cata-twinhead.twinstar.cz/?npc=46785) missing
[Garona Halforcen](https://cata-twinhead.twinstar.cz/?npc=45675) at wrong spot
[Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=45796) missing
 
NPCS and objects that are missing from inside of the cave Elementium depths:
[Magmatooth](https://cata-twinhead.twinstar.cz/?npc=46611) missing
[Twilight miner](https://cata-twinhead.twinstar.cz/?search=Twilight+Miner) only two in there should be a lot more
[Depths Overseer](https://cata-twinhead.twinstar.cz/?npc=46579) missing
[Elementium Spinner](https://wowwiki-archive.fandom.com/wiki/Elementium_Spinner) missing
[Elementium Shard](https://cata-twinhead.twinstar.cz/?object=206295) only one in there should be more
 
 
these objects and npcs have their own scripts which is explained here: https://github.com/gamefreedomgit/Maelstrom/issues/1955
- [Edemantus](https://cata-twinhead.twinstar.cz/?search=Edemantus) missing
- [Aetharon](https://cata-twinhead.twinstar.cz/?search=Aetharon) missing 
- [Apexar ](https://cata-twinhead.twinstar.cz/?search=Apexar) missing
- [Air Portal Controller](https://cata-twinhead.twinstar.cz/?object=206019) object missing
- [Water Portal Controller](https://cata-twinhead.twinstar.cz/?object=206017) object missing
- [Earth Portal Controller](https://cata-twinhead.twinstar.cz/?object=206018) object missing

more details about missing npcs here: https://wowwiki-archive.fandom.com/wiki/Twilight_Citadel and https://wowwiki-archive.fandom.com/wiki/Elementium_Depths

**How it should work:**
missing npcs should be ingame and should have movements mostly basic
this is how quest is supposed to work both alliance and horde:
https://www.youtube.com/watch?v=mP9zC_9o-o8

**Comment by MrTide** [comment]
**1. NPC is in the game but in wrong phase:** couldnt find npcs while having this quest
[Twilight Skyterror ](https://cata-twinhead.twinstar.cz/?search=Twilight+Skyterror)missing ( which they are supposed to be dead in this video you can see a player doing it for a quest https://www.youtube.com/watch?v=FV3dKjdbvWI
) 
2. [Mia the Rose](https://cata-twinhead.twinstar.cz/?npc=46343) got wrong HP value and missing abilities
![image](https://user-images.githubusercontent.com/36106057/219890368-9751fa33-ef11-4b6d-a3d1-b9daddd04a4d.png)
3. [Blindeye the Guardian](https://cata-twinhead.twinstar.cz/?npc=46399) missing
4. [Garona Halforcen](https://cata-twinhead.twinstar.cz/?npc=45675) + [Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=45796) are ingame now but at wrong phase, after  [Garona Needs You]  i believe after doing [ Just You and Mathias](https://cata-twinhead.twinstar.cz/?quest=27637) , [Just You and Garona](https://cata-twinhead.twinstar.cz/?quest=27638) they become available

5. [Edemantus](https://cata-twinhead.twinstar.cz/?search=Edemantus) got wrong HP values
[Edemantus](https://cata-twinhead.twinstar.cz/?search=Edemantus) [Aetharon](https://cata-twinhead.twinstar.cz/?search=Aetharon) [Apexar ](https://cata-twinhead.twinstar.cz/?search=Apexar) are not scripted properly and also their agrro range is way too high to do the quest more details in the video and the link
[Portal Overload](https://www.youtube.com/watch?v=2qWkqI0zDA0) https://github.com/gamefreedomgit/Maelstrom/issues/1955
[Air Portal Controller](https://cata-twinhead.twinstar.cz/?object=206019) is not working
[Water Portal Controller](https://cata-twinhead.twinstar.cz/?object=206017)  is not working
[Earth Portal Controller](https://cata-twinhead.twinstar.cz/?object=206018)  is not working
6. for the quest Dark Assassins i couldnt take the quest from the npc they are not offering it.
7. [Lirastrasza](https://cata-twinhead.twinstar.cz/?npc=46418) is missing objective of Dragon, Unchained https://github.com/gamefreedomgit/Maelstrom/issues/1947

**Comment by Afgann** [comment]
@MrTide you can wait before issue is closed, so we won't test multiple times

**Comment by MrTide** [comment]
> @MrTide you can wait before issue is closed, so we won't test multiple times

Oh i am sorry gaga said i should do that since you guys dont close them anymore i will wait on it from now on

**Comment by Afgann** [comment]
We can make an exception for Twilight Highlands, because it still needs a lot of work. I'll add something like [100% done] if any quest is fully finished.

**Comment by MrTide** [comment]
> We can make an exception for Twilight Highlands, because it still needs a lot of work. I'll add something like [100% done] if any quest is fully finished.
you can close them and tag me i will check again to make sure

**Comment by PanJanuszek** [comment]
1. Terrors and Lirastrasza are scripted now. Added chained Lirastrasza before, flying version.
2.  Mia the Rose has proper rogue class and spells
3. Blindeye's are spawned
4. Both are visible for proper faction after quest Up To Citadel
5. HP's are correct
6. Fixed
7. Added
