### ISSUE TITLE
Envenom only lasting 1second not matter the combo points

### ISSUE THREAD

**Issue by Hotandspicy322** [gamefreedomgit/Maelstrom#1942]
**Description:**
Envenom only lasts 1second

**How to reproduce:**
use envenom with any number of combo point

**How it should work:**
it should last 1second +1second per combo point

**Database links:**
(http://wowhead.com/)](https://www.wowhead.com/spell=32645/envenom)
(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?spell=32645)
this screenshot was taken with 5combopoints used on envenom
![WoWScrnShot_010623_135441](https://user-images.githubusercontent.com/122824463/212896022-8d172086-595f-40d7-93d3-2153d467c58b.jpg)

**Comment by UltraNix** [comment]
Fixed.
