### ISSUE TITLE
[Quest][Cata][Npc] Bring the Hammer Down

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1943]
**How to reproduce:** Bring the Hammer Down quest simply is not working 
twilight citadel cultists that you are supposed to kill are missing more details here: https://github.com/gamefreedomgit/Maelstrom/issues/1941
both horde and alliance side
quest givers [Garona Halforcen](https://cata-twinhead.twinstar.cz/?npc=45675) and [Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=45796)  they are not offering the quest

**How it should work:**
Quests: https://cata-twinhead.twinstar.cz/?search=Bring+the+Hammer+Down
this is how its supposed to work: https://www.youtube.com/watch?v=16fQM6m587w

**Comment by PanJanuszek** [comment]
Not in repro anymore
