### ISSUE TITLE
[Quest][Cata][Npc] Help from the Earthcaller

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1944]
**How to reproduce:** Earthcaller Yevaa is missing you can't do the quest line you couldnt get this quest from quest givers [Garona Halforcen](https://cata-twinhead.twinstar.cz/?npc=45675) and [Master Mathias Shaw](https://cata-twinhead.twinstar.cz/?npc=45796) neither they are not offering the quest
more details about missing creatures : https://github.com/gamefreedomgit/Maelstrom/issues/1941
**How it should work:**
like this video: https://www.youtube.com/watch?v=0zYQeIfI3uI

**Comment by PanJanuszek** [comment]
Fixed, soon
