### ISSUE TITLE
[Quest][Cata][Npc] Distract Them for Me

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1945]
**How to reproduce:**
both horde and alliance side of the quest npcs are not offering the quest (alliance side dont even exist), objectives are also missing more details here: https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:**
like this video you can also see friendly npcs helping you out: https://www.youtube.com/watch?v=30P8Rndgh9A

**Database links:** more details about the quests and their chain quests (both alliance and horde side)
https://cata-twinhead.twinstar.cz/?search=Distract+Them+for+Me

**Comment by PanJanuszek** [comment]
Fixed all chainline for horde & alliance
