### ISSUE TITLE
[Quest][Cata][Npc] The Elementium Axe

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1946]
**How to reproduce:** NPC blinkeye the guardian is missing nor quest giver offers the [quest](https://cata-twinhead.twinstar.cz/?search=The+Elementium+Axe#quests) https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:** like this video: https://www.youtube.com/watch?v=XNM6hQrHSKU

**Database links:** more details about the quests and their chain
both horde and alliance
https://cata-twinhead.twinstar.cz/?search=The+Elementium+Axe#quests

**Comment by PanJanuszek** [comment]
Not reproductable
