### ISSUE TITLE
[Quest][Cata][Npc] Dragon, Unchained

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1947]
**How to reproduce:** quest givers dont offer the quests and objectives are also missing more details here: https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:** like this video : https://www.youtube.com/watch?v=4gs0gHkqJVY

**Database links:** quests and their chains
https://cata-twinhead.twinstar.cz/?search=Dragon%2C+Unchained

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3084

**Comment by PanJanuszek** [comment]
Added npc, invis flag & text

**Comment by PanJanuszek** [comment]
Fixed
