### ISSUE TITLE
[Quest][Cata][Npc] Coup de Grace

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1948]
**How to reproduce:** Quest was offered by horde side npc (alliance side npc doesnt exist) after doing the pre quests (which i added one by one ) but sadly i couldnt finish it since npcs that i am supposed to use are missing details here: https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:** like this video
https://www.youtube.com/watch?v=FV3dKjdbvWI

**Database links:** horde and alliance quest and its chain order.
https://cata-twinhead.twinstar.cz/?search=Coup+de+Grace

**Comment by PanJanuszek** [comment]
Fixed. Both factions has it, also Lirastrasza is flying.

**Comment by PanJanuszek** [comment]
Fixed
