### ISSUE TITLE
DK starting zone texture issues

### ISSUE THREAD

**Issue by Darkosz** [gamefreedomgit/Maelstrom#1950]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
First issue shown on the first screenshot, The Lich King is inside the ramp texture. Second issue, Runeforges are missing once you finish the last DK starting quest. You are still able to Runeforge next to them but they are not there texture and physicality wise.

**How to reproduce:**
For both issues, create a DK and get to the point where the zones goes through the phases.

**How it should work:**
The Lich King shouldn't be inside the texture and the runeforges should be visible.

**Database links:**
![kép](https://user-images.githubusercontent.com/26027404/212977925-a3c17d4d-a173-4fb3-92f3-2f9041bee5eb.png)
![kép](https://user-images.githubusercontent.com/26027404/212977964-a1485d44-14ff-4284-8f61-50486114ab67.png)
![kép](https://user-images.githubusercontent.com/26027404/212978039-17611630-2e07-4505-b7e5-92b8e196d4bf.png)

**Comment by MullichWhitemane** [comment]
Lich King's position has been fixed with an older report, but the Runeforges still don't visibly appear (even though they are useable).

**Comment by MrTide** [comment]
Gobj IDs to add: 191746

**Comment by UltraNix** [comment]
Fixed.
