### ISSUE TITLE
[Quest][Cata][Npc]  Spirit of the Loch + Portal Overload +  Water of Life

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1955]
**How to reproduce:**
NPC [Earthcaller Yevaa](https://cata-twinhead.twinstar.cz/?npc=46242) and [Countess Verrall](https://cata-twinhead.twinstar.cz/?npc=46413) are missing more details here https://github.com/gamefreedomgit/Maelstrom/issues/1941
so you can't take or turn these 3 quests i added these two npc temporarily looks like they have the quests and you can turn them in afterwards but they are not in-game at this moment. 

- Spirit of the Loch simply there is nothing to take the quest from or turn it in.
- "Portal Overload" quest is not scripted properly i will post a video below there should be objects and two versions of the npcs there with proper scripting related to them
- regarding [Water of Life](https://cata-twinhead.twinstar.cz/?search=Water+of+Life#quests) npc objective [Corpse of Forgemaster Finlay](https://cata-twinhead.twinstar.cz/?npc=46819) is ingame but its not scripted properly nor you can do anything with it.

**How it should work:**
this is how these quests are supposed to work: (covers both alliance and horde)
[Spirit of the Loch](https://www.youtube.com/watch?v=VWDjqkrKiLU)
[Portal Overload](https://www.youtube.com/watch?v=2qWkqI0zDA0)
[Water of Life](https://www.youtube.com/watch?v=3gSvNIbAqV0)

**Comment by PanJanuszek** [comment]
Not in repro anymore
