### ISSUE TITLE
[Quest][Cata][Npc] Unbinding

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1956]
**How to reproduce:**
Npcs for the quest are simply missing both quest giver [Initiate Goldmine](https://cata-twinhead.twinstar.cz/?npc=46243) and objectives for you
more details about missing npcs: https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:**
Like this video: https://www.youtube.com/watch?v=c8Is2Z8JXeo

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27662

**Comment by MrTide** [comment]
Enslaved tempest after getting freed should be friendly
Freed tempest
![image](https://user-images.githubusercontent.com/36106057/219885456-e7df8013-35d7-4e1b-867b-db6e4ae6d967.png)
initiate goldmine missing dialog
![image](https://user-images.githubusercontent.com/36106057/219885359-a1bad5ca-bef7-4200-bab1-e20a914262e4.png)
Other than that it works fine.

**Comment by Afgann** [comment]
fixed
