### ISSUE TITLE
[Quest][Cata][Npc] Garona Needs You + Mathias Needs You

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1957]
**How to reproduce:** 
These quests and chain related to them should become available after doing [A Fiery Reunion](https://cata-twinhead.twinstar.cz/?quest=27745)
npc that offers the quest and also npc that completes it for horde side is at wrong spot and for alliance is missing more details here about missing creatures : https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:** 
these two quests related to alliance and horde should become available after [A Fiery Reunion](https://cata-twinhead.twinstar.cz/?quest=27745) not from start.
like this video for garona and mathias: https://www.youtube.com/watch?v=YksQqxdr2Xk
for Back to the Elementium Depths :https://www.youtube.com/watch?v=oc6GfVLauNU

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27782
https://cata-twinhead.twinstar.cz/?quest=27783
https://cata-twinhead.twinstar.cz/?search=Back+to+the+Elementium+Depths

**Comment by UltraNix** [comment]
Both NPCs are there - just need to complete "Up to the Citadel" respectively.

**Comment by PanJanuszek** [comment]
@UltraNix  is correct. Fixed chain line for alliance and horde for both Garona&Mathias. Fix soon

**Comment by PanJanuszek** [comment]
Fixed, both are mutliphased per faction.

**Comment by WhitemaneChronus** [comment]
Seems to be an issue
player has the quest Dragon, Unchained rewarded but cannot see the npc Mathias 
(all previous quests are completed)

**Comment by PanJanuszek** [comment]
This is not a condition, [Up To Citadel] in complete or rewarded state is the way to see him
