### ISSUE TITLE
[Quest][Cata][Npc] Mr. Goldmine's Wild Ride + A Little on the Side +  While We're Here + Rune Ruination + A Fiery Reunion

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1958]
**How to reproduce:** 

1. event  for quest Mr. Goldmine's Wild Ride simply is not working at all... quest giver is missing and also all of the npcs inside of the cave are missing (both horde and alliance are unable to do it) more details about missing npcs: https://github.com/gamefreedomgit/Maelstrom/issues/1941
2. since event is missing and npc at the end of the ride is not there neither(objects missing as well) so you can't accept and complete this quest  "A Little on the Side"
3. quest While We're Here is not doable since npcs that spawns after doing Mr. Goldmine's Wild Ride is not there and also npc objective that you are supposed to kill are also missing
4. quest Rune Ruination is simply not doable runes themselves are there but its not possible to interact  
5. after doing all the quests above A Fiery Reunion should be available for the players to do but sadly npcs are missing and its impossible to do the quest
**How it should work:** 
Mr. Goldmine's Wild Ride  : https://www.youtube.com/watch?v=lPnwwhxjSBE
A Little on the Side : https://www.youtube.com/watch?v=U6PYyPhFiuw
While We're Here : https://www.youtube.com/watch?v=EwVaeo3oXAs
Rune Ruination : https://www.youtube.com/watch?v=wPyc_XPNphY
A Fiery Reunion : https://www.youtube.com/watch?v=stBdNSr9EAs
**Database links:**
Mr. Goldmine's Wild Ride : https://cata-twinhead.twinstar.cz/?search=Mr.+Goldmine%27s+Wild+Ride#quests
A Little on the Side : https://cata-twinhead.twinstar.cz/?quest=27742
While We're Here : https://cata-twinhead.twinstar.cz/?quest=27743
Rune Ruination : https://cata-twinhead.twinstar.cz/?quest=27744
A Fiery Reunion : https://cata-twinhead.twinstar.cz/?quest=27745

**Comment by Afgann** [comment]
fixed
