### ISSUE TITLE
[Quest][Cata][Npc] The Hammer of Twilight +  Skullcrusher the Mountain

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1960]
**How to reproduce:** 
1. Quest simply is not doable, quest objective is missing and npc that offers the quest for horde side is at wrong location and for alliance side its missing
2. Quest Skullcrusher the Mountain simply is not scripted and not working at all, there is no event nothing is happening

 
 More details about missing npcs: https://github.com/gamefreedomgit/Maelstrom/issues/1941

**How it should work:** more details in these videos.
 [The Hammer of Twilight](https://www.youtube.com/watch?v=DKN07lJ_D6Y)
[Skullcrusher the Mountain](https://www.youtube.com/watch?v=jVlzM6s6n3Y)

**Database links:**
[The Hammer of Twilight](https://cata-twinhead.twinstar.cz/?search=The+Hammer+of+Twilight#quests)
[Skullcrusher the Mountain](https://cata-twinhead.twinstar.cz/?search=Skullcrusher+the+Mountain#quests)

**Comment by MrTide** [comment]
some creatures added but event is not fully scripted atm

**Comment by PanJanuszek** [comment]
Fix soon for both factions

**Comment by PanJanuszek** [comment]
Quest is multiphase per faction. Camera and battle fixed.
