### ISSUE TITLE
Uldum beasts dropping gold and they should not

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1963]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
One issue for the shole zone.

Riverbed Crocolisk dropping 25 c and should drop 0
![image](https://user-images.githubusercontent.com/35288643/213180669-e75339dc-3ae2-4dfd-b657-8b0bd87c336a.png)

Mangy Hyena dropping 23 c and should drop 0
![image](https://user-images.githubusercontent.com/35288643/213181111-0a64121e-cc22-4dca-b7fa-4717a9c781ee.png)

Venomscale Spitter dropping 24 silver should drop 0
![image](https://user-images.githubusercontent.com/35288643/213181608-82d1af63-7200-462a-bd34-9da65d81a045.png)

Skarf dropping 24 c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213182247-19a3bc65-bb6a-4530-b272-b09639cfdfea.png)

Venomblood Scorpid dropping 22c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213183226-9ca36eac-3657-48dd-af08-6bfd8e58f0bc.png)

Sand serpent dropping 20 c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213184629-6af9b5d5-3770-425b-95bb-87772363db4f.png)

Wild camel dropping 19c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213184974-8ab42f83-dbaf-4139-9409-386cfa929e92.png)

Stillwater Slitherer dropping 14c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213186768-b59d687e-a799-424b-b2b0-8b350ca9a1fa.png)

Camel dropping 35 silver should drop 0
![image](https://user-images.githubusercontent.com/35288643/213187289-e48cd81b-6129-4732-947b-8290aabc7a91.png)

Tiger is dropping 16c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213187736-548f41db-ce2c-4b84-8231-0032527a509b.png)

Diseased Vulture dropping 16c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213188013-94cf47d8-3e3a-4519-bd52-c1ae95700531.png)

Shaggy Desert Coyote dropping 20 c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213188256-782c2e0b-3dbf-4aeb-93f9-69eb11294e02.png)

Armadillo dropping 22c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213188553-8e92f0fb-bbe9-4397-b2f4-7fe369371d07.png)

**How to reproduce:**
Go to Uldum 57 , 44 and kill Riverbed Crocolisk

Go to Uldum 63 , 30 and kill  Mangy Hyena

Go to Uldum 63, 18 and kill Venomscale Spitter

Go to Uldum 68,2 31,6 and kill Skarf

Go to Uldum 52,1 19 and kill Venomblood Scorpid

Go to Uldum 35,3 27 and kill Sand serpent

Go to Uldum 30,5 27,7 and kill Wild camel

Go to Uldum 52.7 36.6 and kill Stillwater Slitherer

Go to Uldum 52 53 and kill Camel

Go to Uldum 50 76 and kill Tiger

Go to Uldum 43.8 66.8 and kill Diseased Vulture

Go to Uldum 43.3 66.6 and kill Shaggy Desert Coyote

Go to Uldum 43 66 and kill Armadillo

**How it should work:**
All beasts listed should drop 0c

**Database links:**

https://cata-twinhead.twinstar.cz/?npc=45321 Riverbed Crocolisk

https://cata-twinhead.twinstar.cz/?npc=45202 Mangy Hyena

https://cata-twinhead.twinstar.cz/?npc=51673  Venomscale Spitter

https://cata-twinhead.twinstar.cz/?npc=45204 Skarf

https://cata-twinhead.twinstar.cz/?npc=45859 Venomblood Scorpid

https://cata-twinhead.twinstar.cz/?npc=47283 Sand serpent

https://cata-twinhead.twinstar.cz/?npc=51193 Wild camel

https://cata-twinhead.twinstar.cz/?npc=46868 Stillwater Slitherer

https://cata-twinhead.twinstar.cz/?npc=47720 Camel 

https://cata-twinhead.twinstar.cz/?npc=47726 Tiger 

https://cata-twinhead.twinstar.cz/?npc=47202 Diseased Vulture

https://cata-twinhead.twinstar.cz/?npc=47190 Shaggy Desert Coyote

https://cata-twinhead.twinstar.cz/?npc=48239 Armadillo

**Comment by Afgann** [comment]
fixed
