### ISSUE TITLE
[Rogue] Many Critical rogue issues across all 3 specs

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#1964]
Killing Spree drops combat on every teleport iteration - it's the reason why https://github.com/gamefreedomgit/Maelstrom/issues/1390 existed. KS doesn't turn off your auto attacks, dropping combat does. https://www.youtube.com/watch?v=t6uKCnf9BHU In this clip, you can see me drop combat on every teleport, although I do also auto attack at the beginning, as I have made the following macro:
/startattack
/cast Killing Spree
There were no follow up auto attacks after the initial one despite having a quick enough attack speed to fit them in.

Shiv does not apply any poisons when used. https://discord.com/channels/1040715551531618365/1063970174979538944

Combat Readiness does not drop after 10 seconds of nothing.

Expose Armor does not work at all. When you have Glyph of Expose Armor active, Expose Armor will always last 12 seconds (modifiable by Revealing Strike) regardless of the combo points consumed.

If Kidney Shot is blocked, the stun will still go through, but the combo points will not be spent. Normally, blocked CC effects should be completely negated.

**Comment by MullichWhitemane** [comment]
When talenting Ruthlessness, sometimes Envenom will generate extra, unintended Combo Points. https://www.youtube.com/watch?v=gCfM9arllHg
I am not sure what exactly causes it to trigger - I've narrowed it down to Ruthlessness, meaning it can't be Seal Fate or any other talent or effect.

**Comment by UltraNix** [comment]
`Killing Spree drops combat on every teleport iteration - it's the reason why https://github.com/gamefreedomgit/Maelstrom/issues/1390 existed. KS doesn't turn off your auto attacks, dropping combat does.` Cannot reproduce it. No combat dropping during KS.

**Comment by UltraNix** [comment]
`If Kidney Shot is blocked, the stun will still go through, but the combo points will not be spent. Normally, blocked CC effects should be completely negated.` Kidney Shot can obbey block.

**Comment by UltraNix** [comment]
`Venomous Wounds procs (either the energy regen or the damage proc, or both) put both the Rogue and the target in combat.`
Each time your Rupture or Garrote deals damage to an enemy that you have poisoned, you have a 30/60% chance to **deal X additional Nature damage**  And that damage causes to enter combat, as many other similar effects.

**Comment by MullichWhitemane** [comment]
> Cannot reproduce it. No combat dropping during KS.
https://www.youtube.com/watch?v=aN6Gnoh8XHQ Still happens on any PvE or PvP target. Shadowstep, Blink, and Demonic Circle: Teleport still suffer from this as well. You might not be able to repro this due to a difference in the locally built client.

> Kidney Shot can obbey block.
https://www.youtube.com/watch?v=4uATLHojH5Q Something is causing Kidney Shot to both go through and not consume combo points. I am confident that it is due to blocks - however, the combat log only shows that my target was afflicted by kidney shot, and nothing else.

> Each time your Rupture or Garrote deals damage to an enemy that you have poisoned, you have a 30/60% chance to deal X additional Nature damage And that damage causes to enter combat, as many other similar effects.

Aye, took a second look at this, sorry for the wrong info. Will edit this issue out.

**Comment by UltraNix** [comment]
`https://www.youtube.com/watch?v=4uATLHojH5Q Something is causing Kidney Shot to both go through and not consume combo points. I am confident that it is due to blocks - however, the combat log only shows that my target was afflicted by kidney shot, and nothing else.`
What about talents, like Ruthlessness  or Seal Fate?

**Comment by MullichWhitemane** [comment]
> What about talents, like Ruthlessness or Seal Fate?

Neither were talented. I've tried this interaction without any talents or specialization selected, and it still happened. I can quickly brew up a video if you require.

**Comment by UltraNix** [comment]
Yes - with combat log on top.

**Comment by MullichWhitemane** [comment]
> Yes - with combat log on top.

https://www.youtube.com/watch?v=4y0IKnsHVfs Ask and you shall receive.

**Comment by UltraNix** [comment]
Alright - KS is gonna be fixed.
About Killing Spree - I can't do more if I can't reproduce it on my local.

**Comment by MullichWhitemane** [comment]
> About Killing Spree - I can't do more if I can't reproduce it on my local.

I've noticed something odd - have you tried to repro this on a PvE monster? It seems the combat drop no longer occurs against monsters, but it still happens on a Training Dummy and in PvP. I'm working on getting footage now, I'll edit it in as soon as they're available

**Comment by MullichWhitemane** [comment]
-Combat Readiness fixed
-Shiv fixed
-Instant posion fixed
-Wound poison fixed
-Ruthlessness and Seal Fate fixed
-Blocked Kidney Shot fixed
-Expose Armor fixed

The combat drops still exist - I will create a separate report for these with new evidence and close this issue.
