### ISSUE TITLE
Mount hyjal beasts should not drop gold

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1969]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hyjal stag dropping 25 silver should drop 0
![image](https://user-images.githubusercontent.com/35288643/213265050-b81e684a-fcc9-4a32-b620-02a14f1cec29.png)

Nemesis dropping 20c should drop 0 ( also he should not drop his quest item without you having a quest but he does)
![image](https://user-images.githubusercontent.com/35288643/213266995-0774cac2-87d3-4db8-80e1-e1e1da8fb930.png)

Smolderos the Carbonizer dropping 18 c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213273423-78947d62-d0e3-49aa-b1d2-e49f3a166e90.png)

**How to reproduce:**
Go to mount hyjal 37.2 23.3 and kill Hyjal stag

Go to mount hyjal 36.8 52.2 and kill Nemesis

Go to mount hyjal 81.7 65.4  and kill Smolderos the Carbonizer
**How it should work:**
all listed beasts should drop 0 gold

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=39588 Hyjal stag

https://cata-twinhead.twinstar.cz/?npc=40340 Nemesis

https://cata-twinhead.twinstar.cz/?npc=39348 Smolderos the Carbonizer

**Comment by Greywolf59** [comment]
This is pretty general issue in all zones on Azeroth. About 90% of all beasts drop money.

**Comment by sadgh05t** [comment]
Also would add this here not to create a separate issue 

Deep spider got 590k hp and should have 53681 according to the database
![image](https://user-images.githubusercontent.com/35288643/213651965-cc9243c9-0b9f-4af5-8a62-7ae1b0b27a68.png)

Go to deepholm 67.7 20.5 and check hp of deep spider

https://cata-twinhead.twinstar.cz/?npc=47071 , https://cata-twinhead.twinstar.cz/?npc=49815 , https://cata-twinhead.twinstar.cz/?npc=49816 deep spider

**Comment by Afgann** [comment]
fixed
