### ISSUE TITLE
[Quest] [Important] Hero's Call: Winterspring!

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1970]
Quest: [Hero's Call: Winterspring!](https://www.wowhead.com/quest=28544/heros-call-winterspring)

Issue: This quest does not open followups ([Threat of the Winterfall](https://www.wowhead.com/quest=28460/threat-of-the-winterfall)). CRITICAL issue!

NOTE: the parallel breadcrumb/starting quest from Felwood is also unavailable due to Felwood wuest chsin being stucked/bugged. So opening the Winterspring quests is absolutely impossible at the moment.

**Comment by UltraNix** [comment]
Fixed.
