### ISSUE TITLE
[TBC] Hellfire Peninsula Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1973]
I will not tackle small bugs whatsover in this report. This report will be focused on bugs seriously affecting gameplay and the bugs will divided into categories based on how serious they are.

Loremaster: Doable (so-so)

SERIOUS ISSUES

1. [The Exorcism of Colonel Jules](https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules)
- Undoable quest.
- Talking with [Anchorite Barada](https://www.wowhead.com/npc=22431/anchorite-barada), choosing chat option "I am ready, Anchorite. Let us begin the exorcism." does not trigger the event, making this quest undoable
- https://wowpedia.fandom.com/wiki/The_Exorcism_of_Colonel_Jules?so=search

2. [Overlord](https://www.wowhead.com/quest=10400/overlord)
- Not offered.
- This quest should be offered after handing in [The Dark Missive](https://www.wowhead.com/quest=10395/the-dark-missive).

3. [Makuru's Vengeance](https://www.wowhead.com/quest=9424/makurus-vengeance)
- Not offered.
- Should be offered after handing in [Return to Obadei](https://www.wowhead.com/quest=9423/return-to-obadei).

4. [Demonic Contamination](https://www.wowhead.com/quest=9372/demonic-contamination)
- Not offered.
- Should be offered after handing in [Helping the Cenarion Post](https://www.wowhead.com/quest=10443/helping-the-cenarion-post) (Horde: quest=10442)

BOTHERSOME ISSUES

5. [Hero's Call: Outland!](https://www.wowhead.com/quest=28708/heros-call-outland)
- HC: Outland! does not open [Arrival in Outland](https://www.wowhead.com/quest=10288/arrival-in-outland)
- This can be easily bypassed by taking [Burning Crusade: Through the Dark Portal](https://www.wowhead.com/quest=10119/burning-crusade-through-the-dark-portal) on the other side of the Portal.

6. [Journey to Honor Hold](https://www.wowhead.com/quest=10140/journey-to-honor-hold)
- Speaking with [Marshal Isildor](https://www.wowhead.com/npc=19308/marshal-isildor), asking him to send you to Honor Hold does nothing.
- Can be easily bypassed by the fact that the players have all flight paths open.

7. [Fel Spirits](https://www.wowhead.com/quest=10909/fel-spirits)
- [Fel Spirit](https://www.wowhead.com/npc=22454/fel-spirit) does not always spawn.
- [Shattered Hand Berserker](https://www.wowhead.com/npc=16878/shattered-hand-berserker) could use slightly faster respawn.
- Doable in two full clears of the area.

8. [Outland Sucks!](https://www.wowhead.com/quest=10236/outland-sucks)
- There is only 5 [Shredder Parts](https://www.wowhead.com/object=183934/shredder-parts) and the respawn is long.
- Six are needed for the quest. There should be a few more objects added.

9. [Atonement](https://www.wowhead.com/quest=9543/atonement)
- Offered too early.
- Should be offered only after completing [Makuru's Vengeance](https://www.wowhead.com/quest=9424/makurus-vengeance), which is currently not available (point 3).

10. [Rampaging Ravagers](https://www.wowhead.com/quest=9385/rampaging-ravagers)
- I wanted to write there is not enough [Quillfang Ravager](https://www.wowhead.com/quest=9385/rampaging-ravagers), only 6 of them, so they could use 4 more spawns. However on wowhead comments and wowpedia I read that since Wotlk [Quillfang Skitterers](https://www.wowhead.com/npc=19189/quillfang-skitterer) also count for the quest objective.
- It should be checked if Skitterers do indeed count towards the quest objective as they should (already handed in mine).

MINOR BUGS

11. [Fel Reavers](https://www.wowhead.com/npc=18733/fel-reaver)
- Fel Reavers are missing their sounds and trembling earth/screen effect when they get close to the player.

12. [Natural Remedies](https://www.wowhead.com/quest=10351/natural-remedies)
- [Goliathon](https://www.wowhead.com/npc=19305/goliathon) spawns and quest is completable.
- However whole event is missing. No roots, no Pathaleon.
- https://www.youtube.com/watch?v=iGrljCsdOy4

**Comment by DorizarN** [comment]
Can confirm that "The exorcism of colonel jules (10935)" is not doable.

**Comment by PanJanuszek** [comment]
Fixed after respawn
