### ISSUE TITLE
[TBC] [Quest] [NPC] City of Light - Khadgar's Servant

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1975]
Quest: [City of Light](https://www.wowhead.com/quest=10211/city-of-light)
This is introductionary quest into Shattrath after which player can choose his affiliation to be either with Aldor or Scryers and can start doing the quests for them gather rep and rep items. Pretty much one of the key quests in whole Outland.

Issue: Player is supposed to follow [Khadgar's Servant](https://www.wowhead.com/npc=19685/khadgars-servant) who takes player on HORRIBLY LONG tour around the city.
Problem is that Khadgar's Guardian acts as normal guardian npc and follows the player instead vice versa. Quest is undoable.

https://www.youtube.com/watch?v=xDDIk-3HXJk
https://www.wowhead.com/npc=19685/khadgars-servant#comments:id=159686

**Comment by KevlinTallfellow** [comment]
This quest is still bugged as of December 8 2023, only in a different way now.  After the fix to make the servant actually go do the tour of the city, we walked right out of the door of the building where the servant was promptly murdered by a horde Isle of Conquest Envoy.

**Comment by KevlinTallfellow** [comment]
Addendum:

After the recent change to Khadgar's servant, it spawns as hostile to horde, which is why it was immediately attacked by the envoy as it leaves the building.  It was even hostile to my blood elf paladin.  The servant should be a neutral NPC, so it is not attacked by anyone as it meanders through the city.

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
