### ISSUE TITLE
Beasts of Twilight Highlands dropping gold

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1978]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Barkmutt dropping 19c should drop 0
![image](https://user-images.githubusercontent.com/35288643/213655327-342bb290-3f64-41df-b5fc-c10c5150fba2.png)

Highland Worg dropping 15silver should drop 0
![image](https://user-images.githubusercontent.com/35288643/213657676-310ef31d-6f2d-4733-98e7-5fc8e52e4c71.png)

Not a gold issue but their corpse should float and you should be able skin them ( cuz it is a decent farm spot for deepsea scale)
![image](https://user-images.githubusercontent.com/35288643/213658877-b076c81f-da74-4239-bcf4-38afc7861d2f.png)

**How to reproduce:**
Go to Twilight Highlands 38.2 29.6 and kill  Barkmutt

Go to twilight highlands 65 27 and kill Highland Worg
 
Go to twilight highlands 79 12  and kill Frenzied Thresher

**How it should work:**
All listed beasts should drop 0 gold
Frenzied Thresher corpse should be floating and not falling down to the bottom of the sea
**Database links:**
https://cata-twinhead.twinstar.cz/?npc=47769 Barkmutt

https://cata-twinhead.twinstar.cz/?npc=46153 Highland Worg

https://cata-twinhead.twinstar.cz/?npc=49582 Frenzied Thresher

**Comment by Afgann** [comment]
fixed
