### ISSUE TITLE
[TBC] [Achievment] [Quest] Terokkar Forest Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1979]
I will not tackle small bugs whatsover in this report. This report will be focused on bugs seriously affecting gameplay and the bugs will divided into categories based on how serious they are.

Loremaster: Undoable. Stuck at 46/63. (48 if player does two Terokkar versions of breadcrumb quests available if he haven't took them elsewhere) **Thus whole Loremaster meta and title are not possible to get.**

As I see my TBC reports are "Not Planned" I will restrict myself to reporting only completely undoable quests (although I have notes on doable but problematic ones too).

1. [Secrets of the Arakkoa](https://www.wowhead.com/quest=10863/secrets-of-the-arakkoa)
- Handing in this quest does not open further quests in the chain, starting with [The Eyes of Skettis](https://www.wowhead.com/quest=10847/the-eyes-of-skettis).

2. [Speak With Rilak the Redeemed](https://www.wowhead.com/quest=10908/speak-with-rilak-the-redeemed)
- This is second possible quest that can open [The Eyes of Skettis](https://www.wowhead.com/quest=10847/the-eyes-of-skettis)
- This quest is not offered by the quest giver. It is possibly caused by me having handed in [Secrets of the Arakkoa](https://www.wowhead.com/quest=10863/secrets-of-the-arakkoa) already.

I do believe fixing points 1 and 2 could help immersely with the Loremaster being doable.

3. [The Final Code](https://www.wowhead.com/quest=10446/the-final-code)
- Not offered by the quest giver. Should be offered after handing in [Attack on Firewing Point](https://www.wowhead.com/quest=9996/attack-on-firewing-point).

4. [Digging Through Bones](https://www.wowhead.com/quest=10922/digging-through-bones)
- Escort quest is buggy. The NPCs reach their destinastion, do some walking around, two /says and then return to the camp where they despawn and quest is not completed.
- [Bone Sifter](https://www.wowhead.com/npc=22466/bone-sifter) that should attack them during their dig is already spawned and attack them right away. If he is already dead when NPCs come to the spot it does not change anything. I am pretty sure spawn of this mob is one of the key parts of functionality of this quest.
- https://www.youtube.com/watch?v=1HzdAMDeoJw

5. [What Book? I Don't See Any Book.](https://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book)
- When player talks to ["Dirty" Larry](https://www.wowhead.com/npc=19720/dirty-larry) using chat option "Ezekiel said that you might have a certain book...", after a pause Larry says a few wrong /says and he and his comapnion attack the player.
- Problem is that the NPCs turn red and attack the player, however the player can't attack them, making this quest undoable.
- https://wowpedia.fandom.com/wiki/What_Book%3F_I_Don%27t_See_Any_Book.
- https://www.youtube.com/watch?v=bqq5ouEsltE

**Comment by DorizarN** [comment]
Tried "[Digging Through Bones](https://www.wowhead.com/quest=10922/digging-through-bones)" today and yes, NPCs walk, talk then despawn.

**Comment by DorizarN** [comment]
Can confirm that Lieutenant Meridian does not give the quest "The Final Code" after completing "Attack on Firewing Point".

Attack on Firewing Point: https://cata-twinhead.twinstar.cz/?quest=9996
The Final Code: https://cata-twinhead.twinstar.cz/?quest=10446
Lieutenant Meridian: https://cata-twinhead.twinstar.cz/?npc=21006

**Comment by DorizarN** [comment]
GM gave me the quest. I then killed the mob that drops the final code, used it on the Mana Bomb but the quest did not complete.
