### ISSUE TITLE
[Warrior] [Spell] Retaliation does not work

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1984]
[Retaliation](https://cata-twinhead.twinstar.cz/?spell=20230) does not work. Stacks do not get consumed and nothing is visible in Combat Log.

**Comment by MullichWhitemane** [comment]
![retaliation](https://user-images.githubusercontent.com/121984461/213908256-2724b6f7-8c8c-41bb-a85b-90d71ad46dfa.PNG)

Tested it in a duel, it works. Can you please try to recreate the situation in which it didn't proc?

**Comment by Greywolf59** [comment]
I have retested it again and it works. Dunno why it did not proc before. It was in Nagrand PvE arena. Maybe I just had luck on miss/parries/dodges back then.
