### ISSUE TITLE
[TBC] [Achievment] [Quest] Nagrand Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1987]
I will not tackle small bugs whatsover in this report. This report will be focused on bugs seriously affecting gameplay and the bugs will divided into categories based on how serious they are.

Loremaster: Undoable. Stuck at 71/75. **Thus whole Loremaster meta and title are not possible to get.**
All the quests you can get in Nagrand do work, however there are two quest lines that start elsewhere and go through Nagrand and add to Nagrand Loremaster and neither of those quest chains work.

As I see my TBC reports are "Not Planned" I will restrict myself to reporting only completely undoable quests (although I have notes on doable but problematic ones too).

1. [Nitrin the Learned](https://www.wowhead.com/npc=19844/nitrin-the-learned)
- Quests leading to this Quest Giver and offered by this quest giver are stuck on [What Book? I Don't See Any Book.](https://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book) not working.
- Point 5 here: https://github.com/gamefreedomgit/Maelstrom/issues/1979

2. [Altruis the Sufferer](https://www.wowhead.com/npc=18417/altruis-the-sufferer)
- Half (or a third) of his quests are obtainable without leaving Nagrand. However the rest is obtainable only after you get quest [Altruis](https://www.wowhead.com/quest=10689/altruis) which is part of unavailable quests on Shadowmoon Valley Aldor/Scryers Quest hubs.
- Point 5 here: https://github.com/gamefreedomgit/Maelstrom/issues/1986

**Comment by MullichWhitemane** [comment]
I just want to say, we greatly appreciate all your work that you put into TBC, but as this (and Wrath) isn't what we are focusing on, I will close every post like this as not planned. However, looking ahead for the far future, these are great reports, and you deserve commendation.

**Comment by Greywolf59** [comment]
Thank you, all good. As long as it will eventually get repaired I am fine with that. I am an achievment hunter and Loremaster is my main achiev I am after to be honest. That is why I make these reports. If it would not be planned at all, that would be goodbye for me and this server, not gonna lie.

**Comment by PanJanuszek** [comment]
@Greywolf59 are you still playing?

**Comment by PanJanuszek** [comment]
works as 09.03.2024
