### ISSUE TITLE
(Quest) Circle the Wagons... er, Boats - Thousand Needles

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1990]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After sinking all 15 boats, the player should be able to hit the leave vehicle button and be launched over to the center of the barge. Currently, the leave vehicle button just drops the player into the water. Minor bug, the quest is completable.

**Database links:**
Quest:
https://cata-twinhead.twinstar.cz/?quest=25543 (Horde)
https://cata-twinhead.twinstar.cz/?quest=25542 (Alliance)
Quest Completion Video:
https://www.youtube.com/watch?v=jK1wxQopP18&ab_channel=WorldOfWarcraftGuidesAndGameplay

**Comment by MrTide** [comment]
I couldn't reproduce this bug but looks like it happens for a lot of players
also after finishing the quest and hitting leave boat should despawn

**Comment by UltraNix** [comment]
Fixed.

**Comment by mserkanoz** [comment]
When I take the quest, I didn't get on the vehicle, instead I got parachute buff and automaticvally jumped into the water. I am playing Alliance side, Human Mage.

**Comment by Rampageris** [comment]
hi 
I have today this one problem
