### ISSUE TITLE
(Heroic) Dungeon - Lost City of the Tol'Vir

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1992]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
-During the fight with Lockmaw, the Frenzied Crocolisks appear too often, they should only a few at a time.
-Theurgist and Torturers before the 3rd boss should be patrolling, instead they are standing in place.
-During the fight with High Prophet Barim, the Harbinger of Darkness casts Soul Sever on a random target and the targets soul should emerge and try to reach the Harbinger of Darkness. Currently, instead of the soul emerging, the server crashes.

The last boss cannot be reached/killed, dungeon cannot be completed.

**Database links:**
Lockmaw:
https://cata-twinhead.twinstar.cz/?npc=43614
https://cata-twinhead.twinstar.cz/?npc=49043
Frenzied Crocolisk:
https://cata-twinhead.twinstar.cz/?npc=43658
https://cata-twinhead.twinstar.cz/?npc=49311
Neferset Theurgist:
https://cata-twinhead.twinstar.cz/?npc=44980
https://cata-twinhead.twinstar.cz/?npc=49326
Neferset Torturer:
https://cata-twinhead.twinstar.cz/?npc=44977
https://cata-twinhead.twinstar.cz/?npc=49325
Harbinger of Darkness:
https://cata-twinhead.twinstar.cz/?npc=43927
https://cata-twinhead.twinstar.cz/?npc=48953
Soul Sever:
https://cata-twinhead.twinstar.cz/?search=soul+sever

**Comment by WhitemaneSylah** [comment]
Duplicate
