### ISSUE TITLE
[Mage] Pyroblast (dot)

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1993]
**Description: pyroblast's damage over time can hit critically, which it doesn't now**

**Cast Pyroblast on a target, you can see its damage over time does not hit crits at all**

**Pyroblast's damage over time can hit crit based on the mage crit chance.**

![dots](https://user-images.githubusercontent.com/121187280/214042150-53fef0a9-2078-4269-a40a-a9026cd3b915.png)

![Pyroblast](https://user-images.githubusercontent.com/121187280/214044823-457343c4-d6f6-4ea0-a468-a116fbd1b391.jpg)

https://wowpedia.fandom.com/wiki/Damage_over_Time#:~:text=Damage%20over%20Time%2C%20generally%20abbreviated,also%20deal%20damage%20over%20time.

Keep in mind that there are 2 version of Pyroblast, 
One is Pryoblast (dot)
and the other is Pyroblast! (dot)
both of them can hit critically
 
![Pryo and Pyro!](https://user-images.githubusercontent.com/121187280/214047699-c80f23bc-48e9-4f0b-a077-b87446b557d6.jpg)

**Comment by MullichWhitemane** [comment]
Closing and merging this with https://github.com/gamefreedomgit/Maelstrom/issues/2021 report any further non critting DoTs there
