### ISSUE TITLE
[Mage] Flamestrike (dot)

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1994]
Description: Flamestrike's damage over time can hit critically, which it doesn't now

Cast Flamestrike on a target, you can see its damage over time does not hit crits at all

Flamestrike's damage over time can hit crit based on the mage crit chance.

![dots](https://user-images.githubusercontent.com/121187280/214042332-c4d55a27-044a-45c3-9f58-ab02ebce2a99.png)

![Flamestrike](https://user-images.githubusercontent.com/121187280/214045361-64ec27f8-d4e0-4e66-ace3-575607e5e77e.jpg)

https://wowpedia.fandom.com/wiki/Damage_over_Time#:~:text=Damage%20over%20Time%2C%20generally%20abbreviated,also%20deal%20damage%20over%20time.

this issue is similar to https://github.com/gamefreedomgit/Maelstrom/issues/1993

**Comment by MullichWhitemane** [comment]
Closing and merging this with https://github.com/gamefreedomgit/Maelstrom/issues/2021 report any further non critting DoTs there
