### ISSUE TITLE
[Racial Shift] All known issues

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1995]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When Racial Shifting, Dwarves are keeping explorer - this should also get shifted away (and shifted to by other races).

**How to reproduce:**
Create a Dwarf
.skip
Speak to Racial Switcher, switch to Goblin.
Notice how you've kept Explorer.

Create a Troll
.skip
Speak to Racial Switcher, switch to Dwarf.
Notice how you've not gained Explorer.

**How it should work:**
Should lose explorer, and other races switching to Dwarf should get it.

**Database links:**
https://www.wowhead.com/spell=92682/explorer

**Comment by MullichWhitemane** [comment]
Warriors get taught the version of Arcane Torrent that restores Mana. Sidenote: Blood Elf Warriors start out with two Arcane Torrents: one that restores Mana, and one that restores Rage. Blood Elf Warriors keep the Rage generating Arcane Torrent upon Racial Shifting.

Changing to Worgen does not teach Darkflight. Running Wild is correctly retained however.

Night Elf and Tauren Druids can't swap to Worgen or Troll racials. Worgen Druids can't pick Troll racials. Troll Druids can't learn Worgen racials.

**Comment by WhitemaneSylah** [comment]
Darkflight (68992) is not removed from racial shift (worgen to other race)
