### ISSUE TITLE
[TBC] [Achievment] [Quest] Netherstorm Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1996]
I will not tackle small bugs whatsover in this report. This report will be focused on bugs seriously affecting gameplay and the bugs will divided into categories based on how serious they are.

Loremaster: Undoable. Stuck at 105/120, presumably doable 110 with higher Consortium rep and Karazhan quest chain. Thus whole Loremaster meta and title are not possible to get.

As I see my TBC reports are "Not Planned" I will restrict myself to reporting only completely undoable quests (although I have notes on doable but problematic ones too).

1. [Report to Spymaster Thalodien](https://www.wowhead.com/quest=11039/report-to-spymaster-thalodien)
- This quest does not open the following quests (destroying manaforges) due to [City of Light](https://www.wowhead.com/quest=10211/city-of-light) being undoable.
- Report to Spymaster Thalodien itself should not be obtainable without doing City of Light.
- https://github.com/gamefreedomgit/Maelstrom/issues/1975

2. [Parts for the Rocket-Chief](https://www.wowhead.com/quest=11040/parts-for-the-rocket-chief)
- Handing in this quest does not open [You're Hired!](https://www.wowhead.com/quest=10186/youre-hired)

3. [Warn Area 52!](https://www.wowhead.com/quest=10237/warn-area-52)
- This quest should be offered after handing in [Declawing Doomclaw](https://www.wowhead.com/quest=10235/declawing-doomclaw). It is not.

4. [Hitting the Motherlode](https://www.wowhead.com/quest=10293/hitting-the-motherlode)
- Should be offered after handing in [In Search of Farahlite](https://www.wowhead.com/quest=10290/in-search-of-farahlite). It is not.

5. [Ethereum Prisoner I.D. Catalogue](https://www.wowhead.com/quest=10972/ethereum-prisoner-i-d-catalogue)
- This repeatable quest should be offered once the player completes [Ethereum Secrets](https://www.wowhead.com/quest=10971/ethereum-secrets). It is not.

**Comment by PanJanuszek** [comment]
fixed 11.03.2024
