### ISSUE TITLE
Spell Batching issues when casting multiple spells in the same GCD

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2001]
Original Discord report: https://discord.com/channels/1040715551531618365/1063932864862888046

When you Polymorph someone and immediately follow it up with another spell that hits instantly, Polymorph should not break (for example, Polymorph into Frost Nova). Source: https://youtu.be/u7W75EXoev4?t=685

Another example: On Shaman, using Unleash Elements with Flametounge Weapon, casting Lava Burst and a Flame Shock, both spells should benefit from the 30% fire damage buff, but only Lava Burst does.

**Comment by UltraNix** [comment]
I'm not sure we want that spell batching system...

**Comment by MullichWhitemane** [comment]
As far as I understand, since we can't run on 0ms, you will always have some degree of spell batching, even if barely detectable. The point is, if spells fall into the same batch, they should interact in the ways listed in the above evidence - even if the window of opportunity is something like 0.0000001 seconds.

**Comment by UltraNix** [comment]
No - diff does not affect spells in terms of delaying them serverside. Big diff does not mean you can cast multiple spells in the same time. (I'm telling how it works know).

**Comment by MullichWhitemane** [comment]
> No - diff does not affect spells in terms of delaying them serverside. Big diff does not mean you can cast multiple spells in the same time. (I'm telling how it works know).

I see. Personally, I always thought spell batching was kind of silly anyways, so I'm not against not including it. Feel free to close if you'd like.

**Comment by UltraNix** [comment]
Spell batching was something up to WoD? And spells (not only spells) were sent in ticks every 400ms. We send them immediately, so we don;t have any spell batching.

**Comment by UltraNix** [comment]
I'm closing this as not going implemented mechanic.

**Comment by SimonBpvp** [comment]
Could you try to fix this for pvp?
