### ISSUE TITLE
Resistance and Spell Penetration

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2002]
(Original find by Fulgurance on Discord)

Resistance calculations are off. In the attached video, you can see me on a Warlock spamming Corruption with 0 spell pen against a 195 shadow resistance target (24.92% chance to partially or fully resist). However, spells are only resisted once every 10th cast or so, instead of once every 4th cast. This issue is global, I've only used Corruption to easily demonstrate.
https://www.youtube.com/watch?v=JjBDRWup5uE
Spellpen is a crucial stat for a lot of classes and being able to bypass not having to get Spellpen means several classes will be able to do much more damage - especially in PvP - than intended.

**Comment by UltraNix** [comment]
`195 shadow resistance target (24.92% chance to partially or fully resist).` Where did you get these calculations from?

**Comment by MullichWhitemane** [comment]
> Where did you get these calculations from?

As far as I understand, if you mouse over your resistance tooltip that shows how much your X elemental damage taken is reduced by an average of Y percentage, that means that you have that much chance to partially or fully resist (depending on if the spell is binary or not).

Here is some extra links for research purposes: 
https://wowwiki-archive.fandom.com/wiki/Resistance
https://www.mmo-champion.com/threads/843413-Spell-Penetration-Cataclysm-PvP 
"Incorrect, you will get resisted if you're not capped against it on all spells like cyclone, sheep, counterspell, fear, etc.
If you'd reduce damage done by a spell school, like Wrath or Insect Swarm etc by ~25% through resistance, you'd have a ~25% chance to fully resist a non-damage dealing spell of the same school aswell, like Cyclone."

**Comment by UltraNix** [comment]
Yeah, yeah - I misunderstood the title here :P
