### ISSUE TITLE
[WotLK] [Achievment] [Quest] Borean Tundra Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2004]
I will restrict myself to reporting only completely undoable quests (although I have notes on doable but problematic ones too).

Loremaster: Undoable. Stuck at 106/130.

1. [Nick of Time](https://www.wowhead.com/quest=11575/nick-of-time)
- Does not open follow up: [Prison Break](https://www.wowhead.com/quest=11587/prison-break) and thus many other quests further down the line.

2. [Monitoring the Rift: Cleftcliff Anomaly](https://www.wowhead.com/quest=11576/monitoring-the-rift-cleftcliff-anomaly)
- When trying to use [Arcanometer](https://www.wowhead.com/item=34669/arcanometer) on the right spot, player gets error message "Requires Westrift Seismic Anomaly". Undoable.

3. [King Mrgl-Mrgl](https://www.wowhead.com/quest=11704/king-mrgl-mrgl)
- Does not open follow up: [Learning to Communicate](https://www.wowhead.com/quest=11571/learning-to-communicate).

4. [Last Rites](https://www.wowhead.com/quest=12019/last-rites)
- [Thassarian](https://www.wowhead.com/npc=26170/thassarian) is missing chat option to start the event. All NPCs except Valanar are already there.
- [Leryssa](https://www.wowhead.com/npc=25251/leryssa) and [General Arlos](https://www.wowhead.com/npc=25250/general-arlos) are already there. Shouldn't be so.
- https://www.youtube.com/watch?v=BNfd1KWiLW0
- https://www.youtube.com/watch?v=D78bUE8vVD0

5. [Aces High!](https://www.wowhead.com/quest=13413/aces-high)
- [Wyrmrest Skytalon](https://www.wowhead.com/npc=30161/wyrmrest-skytalon)'s ability [Engulf in Flames](https://www.wowhead.com/spell=56092/engulf-in-flames) is not usable, making this quest really really hard, although somehow doable
- Also to use [Revivify](https://www.wowhead.com/spell=57090/revivify) on yourself, player has to de-target the enemy and it does not add combo points, which makes also the "safe way" of doing this quest complicated.
- https://www.youtube.com/watch?v=zNviZrJ9er8

**Comment by PanJanuszek** [comment]
fixed 24.04.2024
