### ISSUE TITLE
Combat drops immediately after killing a PvP target

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2005]
In any PvP combat, if no action is taken for 6 seconds, you should drop out of combat - however, normally, your combat flag is reset to its full 6 second duration if you land a killing blow. Currently, you drop combat as soon as you land a killing blow. https://www.youtube.com/watch?v=nQXedAm5pwA

**Comment by MrTide** [comment]
I am confused are you saying player should not leave combat right away like in this video and stay in combat for 6 more second?

**Comment by MullichWhitemane** [comment]
> I am confused are you saying player should not leave combat right away like in this video and stay in combat for 6 more second?

Aye, worded it poorly, edited the original message. You should still be in combat for 6 seconds after you land a killing blow.
