### ISSUE TITLE
Fire Mage talent: Cauterize - endless loop

### ISSUE THREAD

**Issue by drlinux-lm** [gamefreedomgit/Maelstrom#2006]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

https://webmshare.com/dP5Lb
As you can see, the cauterize triggers itself over and over again. It has an innate cooldown of 1 minute
It had 1min cd throughout the whole cataclysm expac. 
https://wowpedia.fandom.com/wiki/Patch_4.0.1_(class_changes)#Fire

**How to reproduce:**
Go out, take damage until hp reaches the deathmark 0HP, spell triggers automatically then endlessly repeats like
`while(true)
`
**How it should work:**
It should proc only once per minute.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=86949

**Comment by MullichWhitemane** [comment]
Closing, refer to https://github.com/gamefreedomgit/Maelstrom/issues/2016 for any further ICD issues.
