### ISSUE TITLE
[TBC] [Quest] Blade's Edge Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2010]
I will restrict myself to reporting only completely undoable quests plus one really hard one due to a bug.

Loremaster: Doable.

1. [Test Flight: Ruuan Weald](https://www.wowhead.com/quest=10712/test-flight-ruuan-weald)
- Player does not get credit for "Launch to Ruuan Weald"

2. [Death's Door](https://www.wowhead.com/quest=10910/deaths-door) (and onwards)
- Player can't interract with summoned [Evergrove Druid](https://www.wowhead.com/npc=22423/evergrove-druid) and thus can't hand in this quest and take the following.

3. [Into the Soulgrinder](Into the Soulgrinder)
- Doable but it took lvl 80 warr in full Wotlk BiS gear to survive the ARMY of ogre spirits. This is the reason this last TBC report was a bit delayed.
- [Sundered Spirits](https://www.wowhead.com/npc=22912/sundered-spirit) spawn in waves of four, each new wave either within 2s from the first or when player kills one of the four ogres in preceeding wave. Player has to withstand about 15 such waves. Sadly I did not think about recording it and now I have completed it.
- https://www.youtube.com/watch?v=U6F2vpW9Qog

**Comment by PanJanuszek** [comment]
You will get credit if you use quest item, while flying, ascending in air. Not a defect.

Point #2 #3 fixed
