### ISSUE TITLE
(Druid Talents) Leader of the Pack

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2013]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The talent is supposed to have an internal cooldown of 6 seconds after every proc, but it currently procs as much as possible.

**Database links:**
https://cata-twinhead.twinstar.cz/?search=leader+of+the+pack#spells

https://user-images.githubusercontent.com/57082188/214444086-49faba3e-bac6-4a41-9e2d-efdf934e3de2.mp4

**Comment by MullichWhitemane** [comment]
Marking this as Critical as in PvP this has massive implications.

**Comment by MullichWhitemane** [comment]
Closing, refer to https://github.com/gamefreedomgit/Maelstrom/issues/2016 for any further ICD issues.
