### ISSUE TITLE
[quest] The Wakening - Trisfal one of the starting undead quests

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2014]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in the quest you need to talk to 3 npc. When you talk to first one other phases out.  It's one of the first starting quests. 

**How to reproduce:**
i can see 2/3 from here 
![image](https://user-images.githubusercontent.com/99285606/214448556-c3466dd4-c349-490e-b59a-d735d9cb80d0.png)
once i talk to first one second disappears
![image](https://user-images.githubusercontent.com/99285606/214448607-efa2a68a-d8e4-49b0-9e32-30eabe22f485.png)
![image](https://user-images.githubusercontent.com/99285606/214448637-828d5160-6cfa-4570-b85e-bffa7f567ed1.png)

Relog fixes it. 
**How it should work:**

**Database links:**
https://www.wowhead.com/quest=24960/the-wakening

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
same as https://github.com/gamefreedomgit/Maelstrom/issues/2087
closing 2087
