### ISSUE TITLE
Paladin: Censure ( DoT ) doesn't crit

### ISSUE THREAD

**Issue by APTX4869s** [gamefreedomgit/Maelstrom#2017]
https://cata-twinhead.twinstar.cz/?spell=31803#issues
Spell ID 31803
![censure no crit](https://user-images.githubusercontent.com/57665529/214528756-419f3706-17f9-4138-8882-49b47b2fbf9d.png)

 https://wowpedia.fandom.com/wiki/Damage_over_Time
"As of patch 4.0.1, all DoTs can crit"

**Description:**
Censure, after 139 tick and having 30.76% crit chance, doesn't crit

**How to reproduce:**
Use Seal of Truth then hit a dummy

**How it should work:**
Censure should be able to crit

**Comment by MullichWhitemane** [comment]
Closing and merging this with https://github.com/gamefreedomgit/Maelstrom/issues/2021 report any further non critting DoTs there
