### ISSUE TITLE
Holy Paladin: Beacon of Light

### ISSUE THREAD

**Issue by APTX4869s** [gamefreedomgit/Maelstrom#2018]
https://cata-twinhead.twinstar.cz/?spell=53563

![Beacon of Light](https://user-images.githubusercontent.com/57665529/214530483-1cbcb53f-313a-41a6-a4c4-aa8b8adcfed9.png)

**Description:**
You can put Beacon of Light on all friendly targets in your party which you can heal the whole party by spamming holy light

**How to reproduce:**
Invite people to your party and then use Beacon of Light on all of them

**How it should work:**
Beacon of Light should be only on one target as it mentioned in the spell's description

**Comment by MullichWhitemane** [comment]
Actually this is related to https://github.com/gamefreedomgit/Maelstrom/issues/1884, closing this as a duplicate
