### ISSUE TITLE
Non-critting DoTs MEGATHREAD

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2021]
https://wowpedia.fandom.com/wiki/Damage_over_Time
"As of Patch 4.0.1, all DoTs can crit"
Any other previous report will be closed and merged with this. If a DoT effect isn't present here, that means that it either crits, or I haven't discovered if it doesn't. Probably the earlier. That means that this issue isn't global, but it affects a lot of classes.

Mage - Flamestrike, Pyroblast, Combustion (https://github.com/gamefreedomgit/Maelstrom/issues/1993 https://github.com/gamefreedomgit/Maelstrom/issues/1985 https://github.com/gamefreedomgit/Maelstrom/issues/1994)
Priest - Holy Fire
Warlock - Bane of Doom, Seed of Corruption, Shadowflame
Rogue - Hemorrage bleed, Garrote, Deadly Poison
Druid Feral - Rake, Rip, Lacerate, Thrash (https://github.com/gamefreedomgit/Maelstrom/issues/1999)
Druid Boomkin - Insect Swarm, Moonfire, Sunfire
Hunter - Serpent Sting, Black Arrow
Shaman - Searing Flames
Paladin - Exorcism Glyph, Flames of the Faithful, Censure (https://github.com/gamefreedomgit/Maelstrom/issues/2017)

**Comment by MullichWhitemane** [comment]
@UltraNix Edited in Rogue, accidentally forgot to include in the original post

**Comment by UltraNix** [comment]
Okay, not all DOTs should crit (despite what patches state).
Deep Wounds, Ignite, Unholy Blight, Piercing Shots have special attribute (from dbc files) that blocks crits. If you are able to show me more evidences about these spells, I will remove this extra condition.

**Comment by MullichWhitemane** [comment]
You're correct, I looked into this, those 4 shouldn't crit. I will edit the original post and remove them.
