### ISSUE TITLE
Druids automatically learn Sunfire at level 4

### ISSUE THREAD

**Issue by Lightraine2** [gamefreedomgit/Maelstrom#2023]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon reaching level four, druids automatically learn the spell Sunfire 
https://www.wowhead.com/spell=93402/sunfire

Whilst the spell isn't added to the spell book, it can be cast by typing /cast Sunfire or creating a macro.

***

**How to reproduce:**
Reach level four, target hostile npc, type "/cast Sunfire"

**How it should work:**
Sunfire should be learned via talent point in the Balance tree (20 point talent) 

**Database links:**
https://www.wowdb.com/spells/93402-sunfire
![WoWScrnShot_012523_130224](https://user-images.githubusercontent.com/24280476/214571319-93f5f631-6c22-410f-87cd-af0722b276c5.jpg)

**Comment by WhitemaneSylah** [comment]
![image](https://user-images.githubusercontent.com/121137397/214573114-b7b4153a-45bd-42d1-96ed-133924fa14b1.png)
Confirmed

**Comment by MullichWhitemane** [comment]
Just dropping this here https://github.com/gamefreedomgit/Maelstrom/issues/1879 for better clarity.

I will be checking every single level up today for the auto-learn, so I will edit this message when I'm done.
