### ISSUE TITLE
[WotLK] [Achievment] [Quest] Zul'Drak Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2026]
I will restrict myself to reporting only completely undoable quests with a small bonus here and then.

Loremaster: Undoable. Stuck at 92/100.

1. [Dressing Down](https://www.wowhead.com/quest=12648/dressing-down)
- Handing in this quest does not open [Infiltrating Voltarus](https://www.wowhead.com/quest=12661/infiltrating-voltarus), a second part of of Drakuru's quest chain.
- https://wowpedia.fandom.com/wiki/Dressing_Down?so=search
- https://cata-twinhead.twinstar.cz/?quest=12648

2. [The Key of Warlord Zol'Maz](https://www.wowhead.com/quest=12712/the-key-of-warlord-zolmaz)
- After  performing [Tiki Dervish Ceremony](https://www.wowhead.com/item=39314/tiki-dervish-ceremony) [Warlord Zol'Maz](https://www.wowhead.com/npc=28902/warlord-zolmaz) will open the gate and aggro the player. However Warlord does not attack the player and palyer can't attack or hurt the Warlord (not even by AoE). Warlord will follow the player until that player does Alt F4, upon which the warlord will remain standing on the spot the player left him when closing the game.
- [Enchanted Tiki Dervish](https://www.wowhead.com/npc=28927/enchanted-tiki-dervish) will spawn but only the flaming sword is visible and the dervish won't attack Zol'Maz either.

**Comment by PanJanuszek** [comment]
fixed 09.02.2024
