### ISSUE TITLE
[Battlegrounds] Cross Faction BG Queues

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2027]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When two alliance characters queued for a Battleground, it did not pop. The screenshot below shows that we were both classed as alliance.
![image](https://user-images.githubusercontent.com/6482585/214849374-0d4f541b-da47-4a96-9433-8aa22d882c0b.png)

I then created a Horde character and queued, it then popped and put 1 Alliance player vs 1 Horde player.

**How to reproduce:**
Queue Random Battleground on 2 Alliance Characters, notice the queue doesn't pop and the info in the chat box shows that there are 2 alliance queued.
Queue Random Battleground on 1 Alliance, 1 Horde Character, notice the queue does pop.

**How it should work:**
As Whitemane is cross-faction, BGs should take players from both pools classing some Alliance players as Horde and starting the BG.

**Database links:**

**Comment by UltraNix** [comment]
#1889
