### ISSUE TITLE
[Talent] Nature's Bounty

### ISSUE THREAD

**Issue by Esmeralda-CM** [gamefreedomgit/Maelstrom#2029]
Regardless of the points spent in this talent, the situation is the same. This is part of 3 or more Rejuvenation on targets that should reduce Nourish's cast time by x%. As you can see in the video, this is not the case. I also checked on players, but at the time of screen recording there were not enough people around me.

Depending on the talent points spent for example 3/3 with 3 Rejuvenation targets active, Nourish should be cast 30% faster

https://wowpedia.fandom.com/wiki/Nature%27s_Bounty_(druid_talent)
![image](https://user-images.githubusercontent.com/123559920/214865410-d9506030-93a8-4b02-bcda-21f81575fbe2.png)
[User submitted video on discord](https://ptb.discord.com/channels/1040715551531618365/1068177854153621664/1068177854153621664)
Original post by Themolka#0627 on discord.

**Comment by UltraNix** [comment]
As I can see the talent works only on raid/party members and their minions. The question is: should it work outside the group?
