### ISSUE TITLE
[Core] AOE Loot Issues 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2030]
**How to reproduce:**
There are a few problems regarding to aoe loots
1. if you kill and loot the mobs next to boss corpse you dont need to roll for items you can just loot the items from boss as well
![image](https://user-images.githubusercontent.com/36106057/214886606-355495e1-84c5-43f5-9f91-606b0066cd52.png)
![image](https://user-images.githubusercontent.com/36106057/214886664-9701f5ad-3f23-4a1e-b171-3ce6d9faab63.png)

2. it doesn't follow restrictions followed by different types of loot like group loot, whom ever loots first gets everything even boss items.
I was able to loot everything and other player got nothing even tho it was on group loot
![image](https://user-images.githubusercontent.com/36106057/214887129-6d92930e-bc7c-4282-ac74-96ebc7ec6f02.png)

**How it should work:**
My suggestion is that we make this feature self/solo only and disable it for parties, i am suggesting this because there is not really detailed personal loot like panda expansion. unless you have an idea to fix this so it wont get messy.
also please consider some ppl might abuse this and leave party and loot the boss gear that way we need to consider that as well just in case.

**Comment by Greywolf59** [comment]
There is another issue. If player is collecting quest items, lets say 10 heads and kills 5 mobs and only then loots one of them he gets only 1 quest item, even if the quest item is 100% drop chance. Worth to note this happened to me on Northrend but I don't doubt this affect other quests in Cataclysm areas as well. So player gotta kill one, loot one, then kill another, loot another etc.

**Comment by sadgh05t** [comment]
> There is another issue. If player is collecting quest items, lets say 10 heads and kills 5 mobs and only then loots one of them he gets only 1 quest item, even if the quest item is 100% drop chance. Worth to note this happened to me on Northrend but I don't doubt this affect other quests in Cataclysm areas as well. So player gotta kill one, loot one, then kill another, loot another etc.

happened to me in the tauren starting zone also when you kill like 2 quests mobs with drop and 1 non quest mob and loot non quest mob with aoe loot you did not get any quest items

**Comment by MadeinNoxus** [comment]
AOE looting only works for 16 items in total

**Comment by MadeinNoxus** [comment]
AOE looting makes you not able to use skinning on all the NPCs that you kill

**Comment by UltraNixx** [comment]
`AOE looting only works for 16 items in total, one of the ways to test that is kill a big group of NPCs and then try to loot all of them with the AOE looting`
Increased to 18, but this is the client limitation.
