### ISSUE TITLE
[The Vortex Pinnacle] Howling Gale causing WoW Error / Crash to all party members

### ISSUE THREAD

**Issue by DjaouedBen** [gamefreedomgit/Maelstrom#2032]
**### Howling Gale** adds on bridge before the 2nd boss. if any form of leap style attack (warrior: heroic leap, Feral Charge (CAT) and Warlock's Demonic Leap) and an immediate application of damage to render the gale inert is done then all other members of the dungeon will have their game crash, the person initiating the gale is not effected by the crash. other forms of charge do not have the same effect, extensive testing was undertaken with the above abilities and warrior/feral (bear) charge. 
**NOTE:** it works if you leap behind the Howling Gale and not in front, since feral charge takes you behind your target, it counts with Heroic / Demonic Leap from Warrior and Warlock

**Comment by UltraNix** [comment]
Fixed.
