### ISSUE TITLE
Ability is not ready yet bug on Instances

### ISSUE THREAD

**Issue by DjaouedBen** [gamefreedomgit/Maelstrom#2035]
I tried reproduce these two messages on "Heroic Leap", which works the first time you go into the instance, but as soon as you get out and get in again you won't be able to use it, and you get no path available, sometimes if it was on CD it doesn't show the cd, shows like it's available but when you click on it it says Ability is not ready yet... 
**Then** something worse happened, i tried getting in and out a lot of times to see if it can be fixed, i changed stance just before getting in ( so i still had the animation we get for the stance ) then when i got in i couldn't change my stance, and i couldn't use many abilities, you get the same message "Ability is not ready yet"
[SCREEN RECORD REPLICATING THE BUG](https://www.youtube.com/watch?v=5eysO3HEaTg)

**Comment by UltraNix** [comment]
@DjaouedBen Show us some screenshots.

**Comment by DjaouedBen** [comment]
I’ll make some screenshots / screen record tonight

Envoyé de mon iPhone

Le 27 janv. 2023 à 11:37, Torpis ***@***.***> a écrit :

﻿

This is to do with using .tele - .tele will sometimes cause abilities to break. Try again after relogging and then not using .tele anywhere.

**Comment by DjaouedBen** [comment]
[](https://www.youtube.com/watch?v=5eysO3HEaTg)

**Comment by WhitemaneSylah** [comment]
Honorless Target aura has been seen to cause this issue,  ID 2479/46705

**Comment by DjaouedBen** [comment]
> Honorless Target aura has been seen to cause this issue, ID 2479/46705

All teleports ( not .tele, but portals and instances ) that takes you from a map to a different one ( like Kalimdor to Eastern Kingdoms, All raids / dungs entrances etc... that gives Honorless Target that's why i mentionned that.
I could replicate that by simply using portals of different maps, the bug happens when you use a Cooldown on a map, and port to another map,  all cooldowns get reseted ( Visually ) and you won't be able to use that ability again, relogging solve the issue, ( except Heroic leap No Path Available, couldn't fix that in instances by relog ).
**THIS PHASING BUG IS NOT A WARRIOR SPECIFIC BUG**, it can be replicated on **ANY CLASS**.

**Comment by Esmeralda-CM** [comment]
> Honorless Target aura has been seen to cause this issue, ID 2479/46705

.una all does not remove this bug, 
.die/.rev does not either.

So Honorless target aura probably isn't the issue here

**Comment by Commander-Rug090** [comment]
upon .tele to Tol'Vir unable to use certain abilities in Bear form, including but not limited to: Enrage, Thrash, Maul and Swipe. Video attached shows full bug , can be replicated by using ".skip" followed by ".tele tolvir", video shows this in detail. 

https://youtu.be/MAbzdZHVlso

**Comment by DjaouedBen** [comment]
> upon .tele to Tol'Vir unable to use certain abilities in Bear form, including but not limited to: Enrage, Thrash, Maul and Swipe. Video attached shows full bug , can be replicated by using ".skip" followed by ".tele tolvir", video shows this in detail.
> 
> https://youtu.be/MAbzdZHVlso

It has no relation with .tele and .skip, cuz Uldum and GM Island are both in Kalimdor, it happens when you enter in Instances, or if you go from Kalimdor to Eastern Kingdoms...)

**Comment by gaga-whitemane** [comment]
The issue has been resolved, tested, and confirmed by players.
