### ISSUE TITLE
Alterac Valley Issues

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2038]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
- Troggs/Guards do not patrol in either mine
- Towers take 5 minutes to be destroyed - should be 4 minutes as of patch 2.3 [Source](https://wowwiki-archive.fandom.com/wiki/Alterac_Valley_buildings)
- Graveyards take 5 minutes to be taken - should be 4 minutes as of patch 2.4 [Source](https://wowwiki-archive.fandom.com/wiki/Alterac_Valley_buildings)
- Tower Warmasters can be pulled individually and pulled outside the room and killed without the main bosses coming out. This could lead to tower skipping.

**Comment by MullichWhitemane** [comment]
Whats fixed:
-Tower Warmasters are fixed and they properly chainpull
-Every structure and graveyard other than Snowfall now caps in four minutes
Whats not fixed:
-Troggs and Kobolds in the mines still don't patrol - I am honestly unsure if we can look for a proper source for this. Maybe Morgraine had this fixed and is backportable in some way?
-Snowfall Graveyard still takes 5 minutes to cap. https://wowwiki-archive.fandom.com/wiki/Alterac_Valley_buildings Snowfall Graveyard - Neutral Graveyard. Before it is fully controlled, it takes 4 minutes to become controlled. (Was 5 minutes before patch 2.4)

**Comment by UltraNix** [comment]
`Troggs and Kobolds in the mines still don't patrol` - We have no source/sniffs for that.

**Comment by MullichWhitemane** [comment]
GY fixed, closing. If there are new issues with AV, I will reopen.
