### ISSUE TITLE
[Druid] Shapeshift transformation doesn't happen when you have other transformations

### ISSUE THREAD

**Issue by DjaouedBen** [gamefreedomgit/Maelstrom#2039]
Shapeshift on Druids doesn't transform you ( you keep the item / consumable transformation )
[PIRATE HUMAN CAT](https://imgur.com/yY58S2w)

**Comment by MullichWhitemane** [comment]
This is intended behaviour to let players enjoy transformation effects when they otherwise have a displayid altering effect (f.e. Shadowform, Druid Forms, Stealth, etc.). This issue was recently fixed as well with https://github.com/gamefreedomgit/Maelstrom/issues/1863.
