### ISSUE TITLE
[NPC] [Quest]  The Enemy of Our Enemy

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2041]
**How to reproduce:**  while doing The Enemy of Our Enemy npc Lord Hydronis falls under the map
![image](https://user-images.githubusercontent.com/36106057/215204058-89230a6d-1a46-4794-a925-2b78d5974750.png)

**How it should work:** he should not fall under the map

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=14292

**Comment by Afgann** [comment]
fixed
