### ISSUE TITLE
Transformation mounts issues.

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#2042]
- [Burgy Blackheart's Handsome Hat](https://www.wowhead.com/item=65665/burgy-blackhearts-handsome-hat), Dismounts you if you are using [Sandstone Drake](https://www.wowhead.com/spell=93326/sandstone-drake) ... and with the two other transformation mounts that are [Obsidian Nightwing](https://www.wowhead.com/spell=121820/obsidian-nightwing) and [Tarecgosa's Visage](https://www.wowhead.com/spell=101641/tarecgosas-visage) from your point of view it makes you look like flying without mount ( With the transformation ), and for other players they see the transformation of the item Riding the mount ( With Tarecgosas, when you get unequip the Transformation Item, You get the same model as the mount on riding the mount)... shouldn't be like that, you should only get the transparency and the extra size that it adds on your model, and you should see the transformation only when dismounted or on the rest of the mounts that doesn't transform you.
- **UPDATE** Now i could make ppl see me flying as a gnome as i see it on my POV.
- **[SCREENSHOTS](https://imgur.com/a/1l0lzb2)**

**Comment by DjaouedBen** [comment]
Depends on if you guys wanna make it blizzlike or not, Transformation mount bug has been fixed but it's still not blizzlike.
The transformation should give the same transparency and extra size even on Transformations too ( works on transformation mounts, consumable and non-consumable transformations )
[SCREENSHOTS](https://imgur.com/a/oVbH2kH)

**Comment by UltraNix** [comment]
Sorry, but I don't understand. What extra size? What transparency? None of these items applies such effects.

**Comment by DjaouedBen** [comment]
[Burgy Blackheart's Handsome Hat](https://www.wowhead.com/item=65665/burgy-blackhearts-handsome-hat) does, it gives extra size and transparency...

**Comment by DjaouedBen** [comment]
Here's the proof : [Wowhead comments](https://www.wowhead.com/item=65665/burgy-blackhearts-handsome-hat#comments:id=1252099)
