### ISSUE TITLE
(Heroic) Dungeon - Vortex Pinnacle

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2046]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Group Composition: Bear Druid, Holy Paladin, Hunter, Rogue, DK

While fighting Young Storm Dragon, they should only cast Healing Well ONCE upon being pulled, they currently always cast Healing Well after their Chilling Blast attack. Healing Well, when cast, also shows as if it can be interrupted when it shouldn't be.

The pathing for Temple Adept, Servant of Asaad, Executor of the Caliph, and Minister of Air don't seem to be working; After going up the first spiral after the second boss, they are not patrolling correctly, and at some points during combat they will path through the floor.

Boss fights seemed to work correctly, very few bugs here.

**Database links:**
Young Storm Dragon:
(Heroic) https://cata-twinhead.twinstar.cz/?npc=45920
(Normal) https://cata-twinhead.twinstar.cz/?npc=45919
Healing Well:
https://cata-twinhead.twinstar.cz/?spell=88201
Temple Adept: 
(Normal) https://cata-twinhead.twinstar.cz/?npc=45935
(Heroic) https://cata-twinhead.twinstar.cz/?npc=45936
Servant of Asaad:
(Normal) https://cata-twinhead.twinstar.cz/?npc=45926
(Heroic) https://cata-twinhead.twinstar.cz/?npc=45927
Executor of the Caliph:
(Normal) https://cata-twinhead.twinstar.cz/?npc=45928
(Heroic) https://cata-twinhead.twinstar.cz/?npc=45929
Minister of Air:
(Normal) https://cata-twinhead.twinstar.cz/?npc=45930
(Heroic) https://cata-twinhead.twinstar.cz/?npc=45931

Watched this to double check:
https://www.youtube.com/watch?v=02L1UQzZjj4&ab_channel=TotalBiscuit

**Comment by Afgann** [comment]
fixed

**Comment by Commander-Rug090** [comment]
Wild Vortex, cast's "cyclone" on pull/charge to tank, might be caused by the range of aggro? not sure on this one. 

Altairus: 
no longer debuffs the player when standing downwind, only upwind buff is available. 

Asaad: 
Unstable Grounding Field no longer works, he stands there trying to draw the first points of the triangle on the floor, then stands still and does nothing while the party kill him.

**Comment by UltraNixx** [comment]
`Altairus:
no longer debuffs the player when standing downwind, only upwind buff is available.`
![WoWScrnShot_030323_190350](https://user-images.githubusercontent.com/126691570/222794761-4c1b72d9-1d13-4d8b-b666-bf975989cd5e.jpg)

**Comment by Afgann** [comment]
fixed
