### ISSUE TITLE
Glyph of Divine Protection

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2048]
The tooltip for the active buff if you have the Glyph of Divine Protection active is wrong.
![dp](https://user-images.githubusercontent.com/121984461/215320277-036136dc-1241-49c7-b6b8-8b2656f243fd.PNG)
It should say "Magical damage taken reduced by 40%.

**Comment by UltraNix** [comment]
![WoWScrnShot_020223_125909](https://user-images.githubusercontent.com/80540499/216318956-4e2ee3a3-337f-4362-a607-09e6d20d8028.jpg)
Works okay.

**Comment by MullichWhitemane** [comment]
There is a difference between the active spell's tooltip and the tooltip in the spellbook - the one I highlighted is the active buff. @UltraNix

**Comment by UltraNix** [comment]
Blame Blizzard for not updating buff tooltips. Nothign I can do with it.
