### ISSUE TITLE
[Profession] Northern Cloth Scavenging

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2051]
Training [Northern Cloth Scavenging](https://cata-twinhead.twinstar.cz/?spell=59390) through any of the questgivers that offers to train you this (as a quest hand in requiring 5g in Howling Fjord, Borean Tundra, Dalaran) does not teach player this skill. Northern Cloth Scavenging should also affect Embersilk.

https://wowpedia.fandom.com/wiki/Cloth_Scavenging?so=search

**Comment by UltraNix** [comment]
Teaching works okay.
![obraz_2023-02-02_130259311](https://user-images.githubusercontent.com/80540499/216319530-eb520325-7f84-40ce-9a63-1066b6406e02.png)
