### ISSUE TITLE
[TBC] [Dungeon] Mechanar - elevator disappearing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2052]
In Mechanar there is an elevator player needs to use to get to the 2nd boss and further on in Mechanar. This elevator is moving properly, however it phases out every time the player enters the short corridor to the elevator. The dungeon cannot be finished.
Observed on Normal difficulty, not tested on Heroic.

**Comment by Greywolf59** [comment]
Same issue in Heroic version.

**Comment by PanJanuszek** [comment]
cannot reproduce as on 11.03.2024
