### ISSUE TITLE
[TBC] [Quest] The Black Morass - not offered

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2053]
[The Black Morass](https://cata-twinhead.twinstar.cz/?quest=10296) is not offered by [Andormu](https://cata-twinhead.twinstar.cz/?npc=20130).
https://wowpedia.fandom.com/wiki/The_Black_Morass_(quest)
https://www.wowhead.com/quest=10296/the-black-morass

Return to Andormu: https://wowpedia.fandom.com/wiki/Return_to_Andormu
- This quest is offered after turning in [Escape from Durnholde](https://cata-twinhead.twinstar.cz/?quest=29599). This quest should have been removed ith 4.3.0. Might have something to do with The Black Morass not being offered.

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
