### ISSUE TITLE
[TBC] [Quest] Isle of Quel'Danas + MgT Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2056]
1. [Magister's Terrace](https://www.wowhead.com/quest=29682/magisters-terrace)
- [Exarch Larethor](https://www.wowhead.com/npc=55007/exarch-larethor) is not registering that player has this quest at all and there is no question mark nor chat option to hand in this quest.

2. [Severed Communications](https://www.wowhead.com/quest=29684/severed-communications)
- Handing in this quest does not open the followup [The Scryer's Scryer](https://www.wowhead.com/quest=11490/the-scryers-scryer)
- Exarch Lorethor offers this quest all the time. It is repeatable. Should not be so.

3. [Disrupt the Greengill Coast](https://www.wowhead.com/quest=11541/disrupt-the-greengill-coast)
- This daily quest is missing, not offered.

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
