### ISSUE TITLE
[Dungeon] [NPC] [Quest] RFD -  missing questgiver and boss

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2058]
[Koristrasza](https://cata-twinhead.twinstar.cz/?npc=44837) in Razorfen Downs is missing. If player has [Looming Threat](https://cata-twinhead.twinstar.cz/?quest=27063), the question mark is visible on minimap but the NPC is not there.

The boss [Glutton](https://cata-twinhead.twinstar.cz/?npc=8567) is also missing.

**Comment by Afgann** [comment]
fixed
