### ISSUE TITLE
[Dungeon] Upper Blackrock Spire Arena and The Beast

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2063]
The arena is buggy. After player jumps in and defeats waves of enemies, [Warchief Rend Blackhand](https://www.wowhead.com/npc=10429/warchief-rend-blackhand) comes down to deal with the player. He comes out into arena on his mount [Gyth](https://www.wowhead.com/npc=10339/gyth). When player kills Gyth, Blackhand should fight on his own, be killed and arena should open.
However, the Blackhand that drops from the mount is, although hostile, unattackable and he aggroes the player but does not attack him either. This results into combat bug for the rest of the dungeon and to not being able to finish the dungeon at all since the doors out of arena will not open. If player decides to wait around and hope that something happens, after a long time the new waves of adds will start spawning and Blackhand will /yell parts of his speech that he has on the balcony. However new Blackhand won't spawn and the arena remains bugged.

Now, there is a way to prevent the bug. You can see attackable version of Blackhand walking behind the bars, in the spawn area, to the spot where he mounts Gyth. If player attacks him from range, he will run to the player and player can kill him. The arena event "ends" and doors will open.
However Blackhand has no loot and the unattackable version of Blackhand on Gyth will still spawn too and after player kills Gyth, the unattackable version of Blackhand will follow the player around as described above. Also as soon as the player kills the killable version of Blackhand the waves of mobs will start spawning again, following the player around the dungeon.

Also the next optional boss, [The Beast](https://cata-twinhead.twinstar.cz/?npc=10430) has no loot.

**Comment by UltraNix** [comment]
`Also the next optional boss, [The Beast](https://cata-twinhead.twinstar.cz/?npc=10430) has no loot.`
Do not kill with .gm on

**Comment by UltraNix** [comment]
Fixed.
