### ISSUE TITLE
"Ranged Melee" spells breaking Hunter Camouflage

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2067]
[Bug and footage provided by Usepot#1811 from Discord]

Normally, even though you can see Hunters through Camouflage if they are moving, the only way to break their soft-stealth would be using melee attacks, however it seems as if Judgment is capable of breaking the effect. https://youtu.be/1TGHM9FB8Rk

**Comment by UltraNix** [comment]
Hmm, but Camouflage is not targetable only for ranged attacks?

**Comment by UltraNix** [comment]
General, Judgement is a melee spell and should work as a melee spell.

**Comment by MullichWhitemane** [comment]
I couldn't find any info on this and I scoured changelogs, wowhead, wowwiki, youtube, everything, but it feels very wrong to let Judgment go through Camouflage. The entire point is supposed to be that you can avoid ranged attacks with it. Also, Heroic Throw goes through, apparently, not just Judgment.

I'll keep the Status: Need Info label active on this, as I'm convinced you should only be able to be hit in melee range with direct attacks, but I can't seem to find evidence.

**Comment by UltraNix** [comment]
`Also, Heroic Throw and Shattering Throw goes through apparently`
These are also melee, not ranged.

**Comment by MullichWhitemane** [comment]
https://www.youtube.com/watch?v=RCw09vX1jZM Timestamp at 4:00

This is the best information I could find @UltraNix - Swifty was one of the better Warriors at the time, and he never once mentioned that Heroic / Shattering throw can be used to break Camouflage so that the Warrior can get a charge in. In fact, he phrased it like this:
"...What it means is that Hunters can get the opener on Warriors any time they want."
Make of this what you will - I would argue the complete lack of information of if Warrior Throws / Judgment can go through Camouflage is evidence that it actually can't.

**Comment by UltraNix** [comment]
Fixed.
