### ISSUE TITLE
Prayer of Mending bounces infintiely on multiple targets

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2069]
Original report: https://discord.com/channels/1040715551531618365/1070070297748832286
~~Screenshot attached of the combatlog. First Prayer is done without the glyph, the second is with the glyph - the second heal should have been roughly 4800.~~
![prayer](https://user-images.githubusercontent.com/121984461/215870514-b762c678-d898-4587-9b6b-ba01ea11784c.PNG)

Edit: Check https://github.com/gamefreedomgit/Maelstrom/issues/2069#issuecomment-1414196396 for new info.

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/216377023-dc70f3aa-e900-49c2-b574-909562fb8154.png)
1 and 3. is with glyph.
2. is without glyph.
4805/3017 ~ 1.60

**Comment by MullichWhitemane** [comment]
Interesting. This isn't the first time where the locally built client differs from the server (the other one being the blink-type spell combatdrops). Would you want me to create a megathread for these @UltraNix ?

**Comment by MullichWhitemane** [comment]
https://www.youtube.com/watch?v=C6Je9dvgU6s

New evidence: Prayer of Mending (with and without the glyph) will reset itself to 5 stacks after the first two bounces. This also makes it so that Glyph of Prayer of Mending procs infinitely, as technically, it is always the "first" Prayer that gets consumed.

**Comment by UltraNix** [comment]
Fixed.
