### ISSUE TITLE
[Racial][Store][Changerace]

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2071]
**How to reproduce:** reporting it here per gaga request :
.character changerace is supposed to allow the players to change their racials but i believe its not implemented yet
Right now it asks you to go and learn your new racials from the trainer, trainer is not teaching them atm but it should not happen eitherway it will cause issues if players purchase race change from the store, its probably because its not implemented yet.
![image](https://user-images.githubusercontent.com/36106057/215902332-73f3aaee-2a25-4180-ae2d-2e8cde08923a.png)
![image](https://user-images.githubusercontent.com/36106057/215903703-9af8d140-c6d3-4f9f-8731-bedc33c991b3.png)
![image](https://user-images.githubusercontent.com/36106057/215903890-f9516cc9-27df-4a3e-ac1e-f82046b3d599.png)
![image](https://user-images.githubusercontent.com/36106057/215901966-85e2e859-b559-4d63-904d-c8cc21e79743.png)
![image](https://user-images.githubusercontent.com/36106057/215902018-231d373f-33d8-4787-b959-1c9bb4e6c4b0.png)

to reproduce this:
1. create a human hunter
2. change your racial to worgen (for example)
3. use the command and change your racial to night elf

**How it should work:** it should allow you to change your racials (racial npc becomes visible again) and it should not offer your new race racials for you to learn even if you can't learn them from the trainer

**Comment by MullichWhitemane** [comment]
The racial shift NPC shows up after .character changerace now, and you can learn a new race's racials without issues, but the visual glitch of your old race's racials "See your trainer" remains.

**Comment by UltraNix** [comment]
Nothing I can do about it - client reads your race and propose your race racials in spellbook.
