### ISSUE TITLE
[Quest] [Hyjal] The Voice of Goldrinn - not offered

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2072]
[The Voice of Goldrinn](https://www.wowhead.com/quest=25268/the-voice-of-goldrinn) si the quest that should be offered to player after the [End of the Supply Line](https://www.wowhead.com/quest=25233/end-of-the-supply-line) is handed in.
The quest wasn't offered after I have handed in optional [Harrying the Hunters](https://www.wowhead.com/quest=25255/harrying-the-hunters), [In the Rear With the Gear](https://www.wowhead.com/quest=25234/in-the-rear-with-the-gear) and then required quest [End of the Supply Line](https://www.wowhead.com/quest=25233/end-of-the-supply-line).

**Comment by GMHiki** [comment]
not fixed. phasing issues still exist. with the townsfolk in shrine of goldrnn, and the spirit wolf that is supposed to offer quest.

**Comment by GMHiki** [comment]
cannot get quest

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/218822627-10d45683-5e20-41e2-8cf6-96e34674a112.png)
I don't know what are you doing wrong. Maybe already completed that quest?

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/218828397-4c26769a-c8db-45e0-9a2a-f74ae6e53922.png)
There you go.

**Comment by Greywolf59** [comment]
I see the NPCs but still can't get the quest The Voice of Goldrinn from Jadi. No idea why, except maybe due to handing in some of these quests, that should be available only later on https://github.com/gamefreedomgit/Maelstrom/issues/2075#event-8517251179 .

**Comment by UltraNix** [comment]
Try to remove all of these quests (command `.quest remove` if available on PTR)

**Comment by UltraNix** [comment]
Yes. `quest remove` removes from your completed/rewarded container - just like you'd never taken them.

**Comment by Greywolf59** [comment]
Can't remove on PTR, only add and complete.

**Comment by UltraNix** [comment]
Then try it on new character.

**Comment by Greywolf59** [comment]
Fresh toon, same issue. Started from Hero's Call, done quest as they came (skipped Shrine of Aviana quest hub this time), handed in Harrying the Hunters → End of the Suppy Line → In the Rear With the Gear. Now The Voice of Goldrinn should be available. It is not.

**Comment by UltraNix** [comment]
Just tested on fresh character. Also done the same quest chain and got `The Voice of Goldrinn` with no problems.

**Comment by Greywolf59** [comment]
GM on/off issue?

**Comment by UltraNix** [comment]
Gm off, without .quest add/quest complete commands.

**Comment by Greywolf59** [comment]
Then dunno, I will try to update launcher too )if it works finally) and try again. Btw got 20 quests completed from Loremaster by the time I got to The Voice of Goldrinn. Done all side quests in starting area, just in case if there should be any side quest at starting area that blocks it

**Comment by Greywolf59** [comment]
Exact path I took: Hero's Call: Mount Hyjal! → As Hyjal Burns → took Protect the World Tree → Took and handed in Incinting the Elements + The Earth Rises → took and handed in Flames From Above → handed in Protect the World Tree → War on the Twilight's Hammer + The Flameseer's Staff → Flamebreaker → The Return of Baron Geddon → Emerald Allies → The Captured Scout → Twilight Captivity → Return to Alysra → A Prisoner of Interest → Through the Dream → Return to Nordrassil → Took Return of the Ancients + Wings Over Mount Hyjal → Handed in Return of the Ancients (keeping Wings Over Mount Hyjal in quest log) → Harrying the Hunters → End of the Suppy Line → In the Rear With the Gear.
https://wowpedia.fandom.com/wiki/Hero%27s_Call:_Mount_Hyjal!?so=search#Progression
https://wowpedia.fandom.com/wiki/The_Return_of_the_Ancients#Progression

**Comment by UltraNix** [comment]
Fix not yet live on PTR.

**Comment by UltraNix** [comment]
@Torpis @Greywolf59 Test it again (with fresh toons).

**Comment by Greywolf59** [comment]
Works both on old and fresh toon.

**Comment by UltraNix** [comment]
Fixed.
