### ISSUE TITLE
[Quest] [Hyjal] Jordan Olafson's quests - no prerequsites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2075]
[Jordan Olafson](https://www.wowhead.com/npc=40834/jordan-olafson) and [Yargra Blackscar](https://www.wowhead.com/npc=40837/yargra-blackscar) offer their quests without any prerequisites. Starting with trio: [Rage of the Wolf Ancient](https://www.wowhead.com/quest=25576/rage-of-the-wolf-ancient), [Forged of Shadow and Flame](Forged of Shadow and Flame), [Crushing the Cores](https://www.wowhead.com/quest=25577/crushing-the-cores) and ending with [Return from the Firelands](https://www.wowhead.com/quest=25611/return-from-the-firelands).
Return from the Firelands is the problematic one since it _cannot be delivered_ due to Shrine of Goldrinn still being in enemy-occupied phase (as the quests to free it are bugged/not offered atm). 
I am pretty sure the quests at Olafson should be available only after handing in [Into the Maw!](https://www.wowhead.com/quest=25618/into-the-maw) /quest=25623

https://www.wowhead.com/quest=25618/into-the-maw#comments:id=1215278
https://wowpedia.fandom.com/wiki/Into_the_Maw!_(Alliance)?so=search#Progression

UPDATE: When I returned to the Shrine of Goldrinn once more, I was able to hand in the quest to Ian Duran who showed up in the cage in still-hostile phase. No followups, nothing after handing it in.

**Comment by UltraNix** [comment]
Fixed.
