### ISSUE TITLE
[Moved from discord] [Goblin starting area] The great bank heist

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2079]
Mytaxi
OP
 — 01/30/2023 5:36 AM
Quest in Kezan,doesnt interact with the bank vault by clicking on it.
![image](https://user-images.githubusercontent.com/36106057/216193374-cb04d125-b8b9-41c9-8970-7869797af40b.png)

**Comment by MrTide** [comment]
Confirmed player is correct
looks like a phasing issue.

**Comment by Loken-coolguy** [comment]
Gobject ID #195449 
Not interactable
