### ISSUE TITLE
[Moved from discord] [NPC] Orgrimmar Thief 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2080]
Fels
OP
 — 01/04/2023 9:55 PM
Currently Orgrimmar Thieves are just standing in the middle of the city, when I'm pretty sure they should be stealthed.

**Comment by MrTide** [comment]
Player is correct they should be in stealth
https://www.youtube.com/watch?v=ZmZhU18YWQc
![image](https://user-images.githubusercontent.com/36106057/216197603-cb59c3fb-4bcc-4cde-a1bb-795fa27047c7.png)

**Comment by Afgann** [comment]
fixed
