### ISSUE TITLE
[Moved From Discord] Missplaced NPC at Orgrimmar - The Cleft of Shadow

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2084]
Hotandspicy
OP
 — 01/12/2023 4:30 AM
do i need to explain this even? 
anyway
there is a goblin race mount without driver in the cleft of shadow AND a Orgrimmar Grunt running through the air that should not even be in this cave
![image](https://user-images.githubusercontent.com/36106057/216344221-ec157a87-21ae-4b97-96d0-4e6cbe087130.png)

**Comment by MrTide** [comment]
Confirmed
looks like its falling from the above
![image](https://user-images.githubusercontent.com/36106057/216344625-91ef855c-03b0-4890-a92c-bb02fc8f5006.png)

**Comment by Afgann** [comment]
fixed
