### ISSUE TITLE
[Engineering] Jeeves (mostly) Spawns Underground

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2086]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Jeeves spawns underground in some locations and doesn't pop up, I've replicated this throughout GM Island and in Stormwind. In Stormwind it does sometimes work so you might need to try a few locations.

**How to reproduce:**
Use Engineering Scroll
.itemadd 49040
Use item, notice it doesn't spawn

**How it should work:**
Should spawn and fly into the air

**Database links:**
https://cata-twinhead.twinstar.cz/?item=49040

**Comment by MrTide** [comment]
Player is correct
it falls through the ground by the look of it

**Comment by UltraNix** [comment]
Fixed.
