### ISSUE TITLE
Blink type spells dropping combat in (phased) duels

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2088]
Shadowstep combat drop: https://www.youtube.com/watch?v=wv--TFPEYiU
Killing Spree combat drop: https://www.youtube.com/watch?v=nm1r1VFqzGo
Demonic Circle: Summon combat drop: https://www.youtube.com/watch?v=nx-M65FU534
Blink combat drop: https://www.youtube.com/watch?v=CBcqc_b-iNQ

These only seem to occur in duels, which, as part of a new feature of Maelstrom makes it a completely new bug. In non phased PvP (such as natural WPvP, Battlegrounds or Arenas) there are no issues.

**Comment by UltraNix** [comment]
Fixed.
