### ISSUE TITLE
[Quest] Siege Tank Rescue (Twilight Highlands) - Cannot Complete

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2093]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are no "Siege Tank Commanders" on top of the siege tanks in order to do this quest.

**How to reproduce:**
.quest add 27468
Go to the quest area, notice how nothing is interactable.

**How it should work:**
The commanders should be on top of the siege engines

https://m.youtube.com/watch?v=yXtpMIYUYBQ

although the video is from a later expansion it shows where the npcs should be 

**Database links:**
https://www.wowhead.com/quest=27468/siege-tank-rescue

**Comment by Greywolf59** [comment]
Actually, I have found at least one commander hidden inside the tank. Just stand in the tank and zoom in.

**Comment by Alandiel** [comment]
Fixed.
