### ISSUE TITLE
Twilight Skies

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#2094]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest works but really scuffed and server crashes break it

**How to reproduce:**
Just do the quest Twilight Skies

**How it should work:**
https://www.youtube.com/watch?v=V11zl5XLAhs&ab_channel=GitGudGuides

**Database links:**
https://www.wowhead.com/quest=26388/twilight-skies

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/1601
