### ISSUE TITLE
[Moved from Discord] [DMF] Dual Spawn of "Barum"

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2096]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Two of the same NPC's in one place
![image](https://user-images.githubusercontent.com/6482585/216753928-95fff4ec-5a38-41e9-82cc-b41db26bf091.png)

**Comment by PanJanuszek** [comment]
fixed 10.05.2024
