### ISSUE TITLE
Smoke Bomb debuff not updating quick enough

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2098]
Original report: https://discord.com/channels/1040715551531618365/1071409941522436227
Smoke Bomb does not update it's debuff quickly / frequently enough, leading to cases where (especially if you have a lot of movement speed) you can "extend the reach" of the Smoke. https://www.youtube.com/watch?v=0OeP9mP5HGc

**Comment by Afgann** [comment]
fixed
