### ISSUE TITLE
Cross-faction party BG queueing

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2099]
Now that CF-BGs are enabled, soloqueing works completely fine, however, if you have a cross faction party and try to Join as Group, the leader of the party will get the following error:
![cfbg](https://user-images.githubusercontent.com/121984461/216782875-68e2b58e-3354-4b45-9ba5-c04f1862f954.PNG)

**Comment by UltraNix** [comment]
Tested and works okay to me.

**Comment by UltraNix** [comment]
Fixed.
