### ISSUE TITLE
[Warlock] Doomguard does not attack targets who Bane of Agony

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2102]
https://cata-twinhead.twinstar.cz/?spell=18540  -  Summon Doomguard entity does not attack targets that are afflicted with "Bane of Agony" however it will attack if a target has Bane of Doom.

How it should work:  When ability is pressed,  Doomguard should aggro to a target who has bane of Agony OR bane of doom.

How to replicate :  use "Summon Doomguard" onto a target, cast Bane of Agony and observe Doomguard to do nothing.  HOWEVER this can be forced to attack by using Bane of Doom.  refer to below tooltip
![image](https://user-images.githubusercontent.com/121137397/216842554-ac5b9f83-0510-471d-9473-bfc644ee694c.png)

**Comment by UltraNix** [comment]
Fixed.
