### ISSUE TITLE
Impact and Divine Purpose proccing even when you don't damage anyone

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2103]
Edit: As there is no concrete evidence on this, I will assume that the lack of evidence speaks of this being a bug, otherwise every guide would suggest spamming your spells pre-pull to get your procs.

Currently, if you spam untargeted damaging abilities as a Mage and Ret, who have both Impact and Divine Purpose talented, despite not doing any damage to anyone, they can still get their procs.
Divine Purpose proccing from a Divine Storm that deals no damage (also applies to Holy Wrath): https://www.youtube.com/watch?v=I2sO4IF388Y
Impact proccing from an Arcane Explosion that deals no damage (also applies to Flamestrike, Blast Wave, Blizzard, Cone of Cold, Frost Nova and Dragon's Breath): https://www.youtube.com/watch?v=dILv0xwG2EQ

I am not aware of any other bugs like this with other classes (for example, after 100 casts of Whirlwind and another 100 of Thunder Clap, Sudden Death does not proc this way). However, I found this interesting bit of evidence from an early MoP hotfix for Divine Purpose: (2012-09-12): Divine Purpose should only have one chance to activate once per finisher (which must land on at least one target).
https://wowpedia.fandom.com/wiki/Divine_Purpose
Hotfix generally means a bugfix. Yes, it is from MoP, but I couldn't find any Retail Cata info on this. Personally, I don't think those spells should be able to proc if you don't deal any damage. From a game health perspective, it'd lead to some toxic and degenerate playstyles of farming your procs before you get to your targets (and from a PvE lens, timing pulls around those procs - imagine having a full Inquisition before you pull any boss with your T11 4set, then swapping back to your main set post-T11).

**Comment by UltraNix** [comment]
Fixed.
