### ISSUE TITLE
Hero's Call Tanaris not Opening Tanaris

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1. [Hero's Call: Tanaris!](https://www.wowhead.com/quest=28507/heros-call-tanaris)

    Hand-in does not open [Seaside Salvage](https://www.wowhead.com/quest=25048/seaside-salvage). Seaside Salvage and thus whole Tanaris quest chain is unavailable unless player opens it by [Tanaris is Calling](https://www.wowhead.com/quest=27446/tanaris-is-calling).

**How to reproduce:**

**How it should work:**
Quest 28507 should open up 25048

**Database links:**

**Comment by UltraNixx** [comment]
Fixed.
