### ISSUE TITLE
Mining Monkey in The Deadmines are tamable but bugged.

### ISSUE THREAD

**Issue by FireboyWhitemane** [gamefreedomgit/Maelstrom#2110]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
The mining monkeys in The Deadmines instance can be tamed but they are bugged as a pet. After taming them, they become invisible to other players, meaning they can’t be attacked or targeted. Their size is smaller than the monkeys you can tame in Stranglethorn Vale too. You can talent the pet and use their abilities but you can’t command them to ”attack” I have tried with a petattack macro, manually clicking the petattack on the pet bar, tried petfollow and sending pet, petmove, petpassive etc. I have tried relogging, resummoning, killing it and reviving. Nothing works, the pet simply won’t attack the enemy wheter it’s an npc or a player. It moves to them, stops halfway and does nothing, in all zones. I don’t know what causes it, it could be that all tamable pets in a instance are this way after taming them, or maybe it’s mining monkey specific issue because you tame it while it’s chained, because if you unchain it, it becomes a friendly npc.

https://www.wowhead.com/npc=48278/mining-monkey#comments

**How to reproduce:** 
Make a hunter, go to Deadmines instance in Westfall and tame one of the mining Monkey.

**How it should work:**
Tamed mining monkey in deadmines should work the same as any other tamed hunter pets with all commands functioning.

**Database links:**

**Comment by GMHiki** [comment]
specifically in Normal deadmines
https://cata-twinhead.twinstar.cz/?npc=48278 - mining monkey


https://cata-twinhead.twinstar.cz/?object=207079 - Ball and chain object  <- when used makes monkey friendly and untameable


![Whitemane_KCGpaiEm3T](https://user-images.githubusercontent.com/93480183/217015269-594cc320-83e4-4872-ad40-4a8deb4e4f5b.png)
![Whitemane_WQ1hLYK8wh](https://user-images.githubusercontent.com/93480183/217015289-833ed6ff-f8d3-447c-a2d2-c30243a4a54c.png)
![Whitemane_hn3n4vHJ0a](https://user-images.githubusercontent.com/93480183/217015302-74dc58eb-6392-4ee9-bd36-7cbf06df2881.png)
![Whitemane_majA3m0eiG](https://user-images.githu
![Whitemane_5HiL4aJjNr](https://user-images.githubusercontent.com/93480183/217015347-1b84b6a3-7c86-4a22-87a4-139c2ab76f01.png)
busercontent.com/93480183/217015329-d878f6ac-b004-455d-abb3-6121dce61a1f.png)

**Comment by UltraNix** [comment]
Fixed.
