### ISSUE TITLE
[Moved from Discord] Mobs are not entering combat state properly

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2121]
Potentially global issue,  Mobs tested in Duskwood, Elywnn Forrest & Westfall.  Although player is engaged in combat the mobs do not show as engaged with at target.  They will continue their walking path and will heal constantly although not given an "Evade" error

![image](https://user-images.githubusercontent.com/121137397/217550586-4ffba340-9080-484b-81f3-83ea06a2f7db.png)
![image](https://user-images.githubusercontent.com/121137397/217550598-ef393a55-9673-45e8-b7a3-15205166b810.png)
![image](https://user-images.githubusercontent.com/121137397/217550614-535e659b-2549-4485-a75c-be174a16b458.png)
![image](https://user-images.githubusercontent.com/121137397/217550626-a26f585d-b67e-4bb6-82cc-39c21c4b0fe2.png)

Tested on GM toon with GM off and invis off
![image](https://user-images.githubusercontent.com/121137397/217550773-c59a2df3-d73c-4aa9-a0d1-f4f83b431046.png)

**Comment by WhitemaneSylah** [comment]
Tests done in horde zones,  GM off invis off

![image](https://user-images.githubusercontent.com/121137397/217552237-b0fb5671-f32b-40a7-a839-b607a4758867.png)

![image](https://user-images.githubusercontent.com/121137397/217552328-ccdb5b0e-9314-42a6-b512-6b3195c9a1a5.png)

![image](https://user-images.githubusercontent.com/121137397/217552479-a36ec452-3bcf-436b-9fc6-152d204a5aca.png)

![image](https://user-images.githubusercontent.com/121137397/217552709-0febf7d1-384c-42c0-9001-75e73f513b72.png)

**Comment by MrTide** [comment]
looks like there are more creatures with the same issue, probably something broke recently 
![image](https://user-images.githubusercontent.com/36106057/217555588-c1c6e9e7-0557-412f-9d52-60d3715a93f6.png)
![image](https://user-images.githubusercontent.com/36106057/217555996-5e77c238-1568-4d19-b2cf-45cc3e036030.png)
![image](https://user-images.githubusercontent.com/36106057/217556529-17eb370f-639c-4ee7-8e25-2c3fe8b76126.png)

**Comment by UltraNix** [comment]
Sorry guys, but I can't reproduce it on my local. Everything works okay. Something's changed in PTR config?

**Comment by WhitemaneSylah** [comment]
No clue,  It was fine yesterday.  needs fixed pronto
