### ISSUE TITLE
[Quest] To Fort Livingston and Bwemba's Spirit

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2122]
Starting quests of The Rise of Zandalari quest chain.

1. [To Fort Livingston](https://www.wowhead.com/quest=29102/to-fort-livingston) is offered, but the [Bwemba's Spirit](https://www.wowhead.com/quest=29100/bwembas-spirit) is not.
Note: I did [The Troll Incursion](https://www.wowhead.com/quest=29156/the-troll-incursion) first.
- https://wowpedia.fandom.com/wiki/Bwemba%27s_Spirit
- https://wowpedia.fandom.com/wiki/To_Fort_Livingston

2. If player goes to Fort Livingston with [To Fort Livingston](https://www.wowhead.com/quest=29102/to-fort-livingston) quest active, the camp is not phased properly.
- https://www.youtube.com/watch?v=tjbTt3FwDEQ

**Comment by PanJanuszek** [comment]
Fixed after update
