### ISSUE TITLE
[Dungeon] [WotLK] Utgarde Pinnacle - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2123]
Tested on Normal difficulty.

1. [Svala Sorrowgrave](https://www.wowhead.com/npc=26668/svala-sorrowgrave)
- Event that should start when player enter the room (when walking down the stairs) to transform [Svala](https://www.wowhead.com/npc=29281/svala) to the boss proper and triggering the boss fight does not occur.
-  Objective of [Working at the Source](https://www.wowhead.com/quest=29864/working-at-the-source)
- shitty quality: https://www.youtube.com/watch?v=n3SAL8O9Uac
- https://www.youtube.com/watch?v=JDeS5ANdBPI

2. [Skadi the Ruthless](https://www.wowhead.com/npc=26693/skadi-the-ruthless)
- [Ymirjar Harpooners](https://www.wowhead.com/npc=26692/ymirjar-harpooner) do spawn [Harpoon](https://www.wowhead.com/object=192539/harpoon) object on their death however upon interacting with them, the player does not recieve [Harpoon](https://www.wowhead.com/item=37372/harpoon) in their inventory, thus Skadi can't be pushed to Phase 2 and killed (need to shoot those harpoons on him three times). Gate to the last boss stays locked.

**Comment by EdyGlockenspiel** [comment]
Can confirm, both Svala Sorrowgrave and Skadi are unable to be killed.

**Comment by UltraNix** [comment]
Fixed.
