### ISSUE TITLE
Perfume and Cologne neutralizer

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#2126]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You can apply both effects at the same time
![image](https://user-images.githubusercontent.com/35288643/217618327-16031598-65fb-4039-9a14-7de0d8be1d7b.png)
![image](https://user-images.githubusercontent.com/35288643/217618364-daaade07-6c6b-45e5-a948-f281ba29c664.png)

**How to reproduce:**
Get the https://cata-twinhead.twinstar.cz/?item=49631 from quest npc inside the shadowfang keep open it and use both of the neutralizers

**How it should work:**
You should be able to apply only one effect

**Database links:**
https://www.wowhead.com/item=49351/perfume-neutralizer#comments
https://www.wowhead.com/item=49352/cologne-neutralizer#comments
https://cata-twinhead.twinstar.cz/?item=49352#contained-in-item
https://cata-twinhead.twinstar.cz/?item=49351

**Comment by UltraNix** [comment]
Fixed.
