### ISSUE TITLE
[Dungeon] [WotLK] Halls of Stone - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2127]
Tested on Normal difficulty.

[Tribunal of the Ages](https://www.wowhead.com/npc=28234/tribunal-of-the-ages)
- This event is not fully scripted. Only Brann speaks and only mobs spawn. There is no speech of the Tribunal and no added mechanics of the Tribunal (missiles, debuff orb, laser).
- This event ends too early (Brann just decides to run away) and thus the encounter can't be completed.
- Without completion of this encounter the doors to the last boss won't open.
- Both this boss and the last are needed for the achievment.
- https://wowpedia.fandom.com/wiki/Tribunal_of_Ages
- https://www.youtube.com/watch?v=YPNJSYEAu2U

**Comment by PanJanuszek** [comment]
fixed 04.04.2024 -> check changelog when update is ON
