### ISSUE TITLE
[Dungeon] [WotLK] Culling of Stratholme

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2129]
Tested on Normal difficulty.

I haven't managed to complete the dungeon, however there are already some notes.

1. Prince [Arthas](https://cata-twinhead.twinstar.cz/?npc=26499) is way too agressive and is skipping forward in the scenario.

2.  [Salramm the Fleshcarver](https://cata-twinhead.twinstar.cz/?npc=26530)
- With 91K max HP and at least 60k HP left, I got IK from his [Explode Ghoul](https://cata-twinhead.twinstar.cz/?spell=52480) (written in Combat Log simply as "Salramm the Fleshcrafter's Explode Ghoul instantly kills Greywolf"). This definitely should not be so.

3. When reentering the dungeon as dead to try again, I got texture bug. Camera and whole frozen under textures, some trees and hills visible around and slightly above me. Had to AltF4 out.

**Comment by PanJanuszek** [comment]
fixed 04.04.2024
