### ISSUE TITLE
[Quest][Server Crash] Once More Into the Fire

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2131]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest 27648 crashes the server or disconnects the client when being done.

**How to reproduce:**

PLEASE DO NOT FIX THIS UNTIL ITS BEEN USED TO SEE IF IT CAN REPLICATE #2055 

    .quest add 27648
    .go queststarter 27648
    Speak to Cayden to begin the event
    At some point in the escort you will be disconnected or the server with crash

PLEASE DO NOT FIX THIS UNTIL ITS BEEN USED TO SEE IF IT CAN REPLICATE #2055 

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=27648/once-more-into-the-fire

**Comment by UltraNix** [comment]
Fixed.
