### ISSUE TITLE
Twilight Highlands Alliance Bug Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2133]
Lesser and Medium bugs of Twilight Highlands. I can also confirm reports on "Devoured" and "Nigthmare" quests.
Loremaster: 85/120

1. [Fargo Flintlocke](https://www.wowhead.com/npc=49020/fargo-flintlocke)
- He shoots white-blue cubes, aka his shots are missing the proper model. (fixed)

2. [Evan Silvia](https://cata-twinhead.twinstar.cz/?npc=49704)
- Has a wrong title "Cooking Trainer". Should be "Cook". (fixed)

3. [Iain Firebeard](https://www.wowhead.com/npc=46805/iain-firebeard)
- He is dead, although properly interactable. Should be alive and well (and standing). (fixed)

4. [Dropping the Hammer](https://www.wowhead.com/quest=27817/dropping-the-hammer)
- If player dies during killing [Servias Windterror](https://www.wowhead.com/npc=46839/servias-windterror) on mount and goes there on a fresh mount, Servias won't have renewed HP and if he is killed too fast (as a result of this) the scenario where player lands on his platform and finishes him off won't play out and player will be stuck on the gryphon and will have to alt+f4 out of the game.
- I have no idea if this issue persists when the player manages to do the quest in one go.
- the guy on the video killed him a bit too fast too but you can see that the scenario was about to play out and the gryphon landed: https://www.youtube.com/watch?v=xuxpxAGg7es

5. [Eye Spy](https://www.wowhead.com/quest=28244/eye-spy)
- slight camera problems by the end of the cutscene
- https://www.youtube.com/watch?v=s1QJHamaVOc

6. [Narkrall, The Drake-Tamer](https://www.wowhead.com/quest=28282/narkrall-the-drake-tamer)
- [Narkrall](https://www.wowhead.com/npc=48257/narkrall-rakeclaw) has parachute and falling animation during the whole fight.

7. [The Eyes Have It](https://www.wowhead.com/quest=28243/the-eyes-have-it)
- Available for handing in for the second time (even when already handed in and not in quest log) when player flies over the area during [Rescue at Glopgut's Hollow](https://www.wowhead.com/quest=28377/rescue-at-glopguts-hollow). So possibly after phase changes.

8. [Highland Worg](https://www.wowhead.com/npc=46153/highland-worg)
- Most likely missing spawns. The area shown on wowhead map and by carbonite and other quest trackers (their meat for one quest) is basically empty. The area is northeastern part of the Twilight Highlands, around 68.6/27.1.

9. [Something Brewed](https://www.wowhead.com/quest=28409/something-brewed)
- [Kirthaven Courier](https://www.wowhead.com/npc=48759/kirthaven-courier) with their [Wildhammer Wheelbarrows](https://www.wowhead.com/npc=48909/wildhammer-wheelbarrow) stop after the 1st attack in fear position and stay there. Quest is still completable. They will be shown in that fear position also during the wedding cutscene.

10. [The Maw of Iso'rath](https://www.wowhead.com/quest=27376/the-maw-of-isorath)
- The flight is not properly scripted. The player's gryphon won't get grabbed by the tentacle. Parachute that shouldn't be there.
- https://www.youtube.com/watch?v=Fv6K89DF6cc

11. [The Worldbreaker](https://cata-twinhead.twinstar.cz/?quest=27378)
- Only Thrall visible, Deathwing, other shamans and all other animations are missing.
- after the quest is handed in, the player stays at the Maelstrom, just in normal phase (like when entering Deepholm). Player should get teleported back to the Maw of Madness.
- https://www.youtube.com/watch?v=ckt6hogBBpk

**Comment by Sketish** [comment]
Fixed
