### ISSUE TITLE
[Quest] [Twilight Highlands] Small Comforts

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2134]
[Small Comforts](https://www.wowhead.com/quest=27805/small-comforts)

1. The objects are not spawned/visible.
[Meara's Dried Roses](https://www.wowhead.com/object=206408/mearas-dried-roses), [Parlan's Ivory Hammer](https://www.wowhead.com/object=206411/parlans-ivory-hammer), [Aprika's Lost Doll](https://www.wowhead.com/object=206410/aprikas-lost-doll).
https://www.youtube.com/watch?v=Ol0UXMAuz8E

2. [Wowpedia](https://wowpedia.fandom.com/wiki/Small_Comforts?so=search) states it is offered earlier than I have seen this quest, basically when player starts questing in the location, when the village is on fire. I have noticed it only after I have handed in [Personal Request](https://www.wowhead.com/quest=27816/personal-request). However on the video above you can see that player doing it is also doing it a bit later, when the fires are already out and the village is clean and calm, so the phase should not matter.

**Comment by MrTide** [comment]
new update
looks like objects are just phased out 
players can't see it
player quest list while he was trying to do it
![image](https://user-images.githubusercontent.com/36106057/223062998-517065be-d1ff-4c7a-8618-799e3c07f12a.png)

**Comment by EdyGlockenspiel** [comment]
Currently right now the quest is showing like I already have it in my log, and completed. (the yellow ? is above the quest NPC) this is preventing me from actually accepting the quest.

**Comment by MrTide** [comment]
duplicate
