### ISSUE TITLE
[Love is in the Air] Lovely Charm Collector's Kit

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2136]
[Lovely Charm Collector's Kit](https://www.wowhead.com/item=49661/lovely-charm-collectors-kit)
Having this item in the inventory does not provide player with [Lovely Charms](https://www.wowhead.com/item=49655/lovely-charm) on worthy kills.
[This comment](https://www.wowhead.com/item=49661/lovely-charm-collectors-kit#comments:id=1621558) mentions a slight issue when player also has [Darkmoon Adventurer's Guide](https://www.wowhead.com/item=71634/darkmoon-adventurers-guide), which I do, however when player reaches 250 trophies (max) from the Guide, the lovely charms should be dropping. The comment also mentions hotfix that made both drop at the same time possible.

**Comment by PanJanuszek** [comment]
fixed by Ultranix long time ago
