### ISSUE TITLE
Feral Druid ability Tiger's Fury 2 hour cooldown

### ISSUE THREAD

**Issue by Lightraine2** [gamefreedomgit/Maelstrom#2141]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The feral druid ability Tiger's Fury currently has a cool down of 2 hours at level 80 (unconfirmed if cool down is different at other levels)

**How to reproduce:**
Create a druid - skip to gmisland and use level 80 boost. Apply talent points in feral tree - use Tiger's Fury ability - observe cool down applied

**How it should work:**
As per the tooltip, Tiger's Fury should have a base cool down of 30 Seconds

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=5217

![WoWScrnShot_021023_174717](https://user-images.githubusercontent.com/24280476/218160989-7ce5cb34-46a3-4807-8ef1-6808c0a940c5.jpg)

**Comment by MrTide** [comment]
similar issue
https://github.com/gamefreedomgit/Maelstrom/issues/2055
