### ISSUE TITLE
Druid ability Survival Instincts 2 hour cool down

### ISSUE THREAD

**Issue by Lightraine2** [gamefreedomgit/Maelstrom#2142]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Survival Instincts has a 2 hour cool down applied on use

**How to reproduce:**
Create druid character - .skip to GM island - use level boost to level 80 - use Survival Instincts 

**How it should work:**
As per the tool tip, Survival Instincts should have a 3 minute cool down.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=50322
![WoWScrnShot_021023_175120](https://user-images.githubusercontent.com/24280476/218186089-15d960f6-ded1-4ecc-8837-8ea495f4f8b5.jpg)

**Comment by MrTide** [comment]
similar issue
https://github.com/gamefreedomgit/Maelstrom/issues/2055
