### ISSUE TITLE
[Moved from Discord]  Pets are not stacking Focus fire

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2144]
Pet IDs below are shown not to stack focus fire when attacking,  talents have been checked 

![image](https://user-images.githubusercontent.com/121137397/218320804-dd434dfd-b63f-49fc-bdac-03d0e079f763.png)
![image](https://user-images.githubusercontent.com/121137397/218320811-de2004ee-5294-4faa-9718-c4c0f3ada484.png)

![image](https://user-images.githubusercontent.com/121137397/218320905-9cba07b9-aac1-4f23-bf31-4932764a43ac.png)
![image](https://user-images.githubusercontent.com/121137397/218320975-30e6e379-4531-4554-bc92-89329ca305ba.png)

![image](https://user-images.githubusercontent.com/121137397/218321034-b4d96ef2-44fc-48ad-a42f-5af8fa16f756.png)
![image](https://user-images.githubusercontent.com/121137397/218321039-d6e7c4f8-68fc-4a0f-baab-72dbc18f1953.png)

**Comment by Afgann** [comment]
fixed
