### ISSUE TITLE
[Moved from Discord] Patriarch's Blessing cutscene bug

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2145]
Cutscene for quest 24679 does not play correctly,  quest still completable however

https://wowpedia.fandom.com/wiki/Patriarch%27s_Blessing

Player submitted video https://youtu.be/Ex6xEzy-i2I?t=15 

Cutscene from WoW retail cata (minus random druid attacking ghosts)
https://www.youtube.com/watch?v=PE4zLFM4Mxc

**Comment by WhitemaneSylah** [comment]
Quest cannot be completed now as NPC does not phase in correctly.

**Comment by UltraNix** [comment]
Fixed.
