### ISSUE TITLE
UI Error? First Quest Completion Bug

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#2150]
I received this prompt - not sure why. I have completed about 11 quests so far 
![WoWScrnShot_021223_155222](https://user-images.githubusercontent.com/67768754/218344759-962bac9d-ae03-457b-90d5-acc0c7188651.jpg)

**Comment by Greywolf59** [comment]
Hmm I thought it is an issue with Carbonite but last few days I have same issue with quest giver tracking and their available quests on map. It shows all the quests as available, even those I have done very long time ago so I have to click them away as done one by one manually.

**Comment by UltraNix** [comment]
No further info - closing.
