### ISSUE TITLE
[Moved from Discord] Hitbox and facing enemys

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2153]
Melhar OP — 02/10/2023 11:24 PM
Seems hitbox and facing enemy mechanics little bugged I can auttoatack to targets behind me and also use spells on them
![image](https://user-images.githubusercontent.com/36106057/218349076-198a423d-446c-43e3-8799-3764f66b64ce.png)
![image](https://user-images.githubusercontent.com/36106057/218349087-bcfbb373-fa71-4e56-87ed-e5cad39289f7.png)
![image](https://user-images.githubusercontent.com/36106057/218349099-9e24f2cd-5f03-4c7e-b374-fadd05ad1dff.png)

**Comment by MrTide** [comment]
Can confirm player is correct, it should say you are facing the wrong way but when you are in hit box range of the creature it wont say that

**Comment by UltraNix** [comment]
Fixed.
