### ISSUE TITLE
Debuffs should be removed when exiting duel 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2154]
All debuffs should be removed when exiting duel either by a win, loss or forfiet.  Currently on the PTR all debuffs remain and can end up killing players,  example being cauterize overkilling players after dueling

**Comment by UltraNix** [comment]
All debuffs casted/applied by your opponent are removed properly.
Cauterize is an aura that is applied by player himself.
