### ISSUE TITLE
Ticket issue / Game master commands.

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2156]
**How to reproduce:**
So when we send an offline response to the players through addon the ticket window updates for the player up top near the mini map as you know like this image
![image](https://user-images.githubusercontent.com/36106057/218525771-b1acb596-ee82-4522-8cdd-16b4e7ceda63.png)
but when player is offline there is no window and it just goes to the mailbox and it doesn't even send the full message
![image](https://user-images.githubusercontent.com/36106057/218525927-1642dcc2-cef5-4c74-90ac-a1a6b2640b72.png)

**How it should work:**
we need to make it to just works with the window like that picture, even if you are offline
there are a lot of downsides to it
like player has to go to a mailbox to get his answer
fonts are not clear
and not full message goes through
**If you have access to the voltarus core you can use that core ticketing system to improve it.**
**After investigation with hiki this is what we found:**
offline responses should not go to mail, it should still be open in top right corner next to mini map
.ticket response append/appendln should not auto close a ticket if player is offline(right now it closes it when player is offline) until close/complete command is used
So all you need to do from our perspective is to compare two core ticket responses using .ticket response append/appendln (voltarus and maelstorm) and see what the difference is and implement it
Thank you in advance
we also used sunwell core which is still online so what we found is accurate

**Comment by UltraNix** [comment]
Fixed.
