### ISSUE TITLE
[INTERFACE] Click to move doesn't work

### ISSUE THREAD

**Issue by s71n63r** [gamefreedomgit/Maelstrom#2157]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
With "Click to move" enabled, clicking in the game space does make character move. Can only move by holding WASD keys or holding both mouse buttons. This behavior is the same as with "Click to move" disabled.

**How to reproduce:**
Game Menu --> Interface --> Mouse -- Enable "Click to move"
![Untitled](https://user-images.githubusercontent.com/125290607/218779479-8e33646f-7db0-4ed4-ac15-a78e97b6e652.png)

**How it should work:**
Should be able to click mouse button and character will travel toward the clicked point.

**Database links:**

**Comment by UltraNix** [comment]
Works - just use right-click.

**Comment by s71n63r** [comment]
> Works - just use right-click.

Not working. Is there a client update?

**Comment by UltraNix** [comment]
I don't what. Just tested and eberything works okay.
