### ISSUE TITLE
[Quest] Breaking the Bonds - qID 25514

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#2158]
Another issue of objects or player not being on the correct phase. during quest.

Objects - Rod of Subjugation

objectIDs:

202954
and
202955

These pillars should be visible to the player to "activate" and free tortolla
they are invisible to the player, on a different phase

**Comment by MrTide** [comment]
update: Seems to be working now
closing the issue
thanks
