### ISSUE TITLE
[Dungeon] Grim Batol Heroic issues list

### ISSUE THREAD

**Issue by DjaouedBen** [gamefreedomgit/Maelstrom#2159]
2/3 Dungeon's quest works ( **Closing a Dark Chapter** and **Kill the Courier**

Unable to complete the third one **Soften them Up**, that requires killing **30 Trogg Dwellers** with **Battered Red Drake** , but for some reason, Trogg dwellers are not killable with **Battered Red Drakes** abillity ( They regenerate hp ) but even if more than one player hit them at once and kill them, it doesn't count for the quest

- **General Umbriss:** Works perfectly.

Trogg Dwellers on the room of **Forgemaster Throngus** should be moving to the door so players can pull them alone, they're stacked with another pack of adds actually and it will be hard to pull that actually.

- **Forgemaster Throngus:** **Disorienting Roar** doesn't drop stacks on Healers on most healing abilities ( it should drop 1 stack for each ability you use / cast.

- **Drahga Shadowburner** on the second phase with Valionna, **Seeping Twilight** stays less than 20s sometimes and **Invoked Flame Spirit** should be slowed by that zone.
 
- **Erudax, the Duke of Below** Works perfectly.

**Comment by WhitemaneSylah** [comment]
Duplicate
