### ISSUE TITLE
Hunter's Kill Command resets the pet's swing timer

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2160]
https://www.youtube.com/watch?v=bBbI-4A26kc

As shown in the video, this can lead to awkward situations where your pet can't get his stun off (and just in general misses out on a bit of damage unless Kill Command is perfectly timed). In general, instant attacks shouldn't reset the swing timer.
https://wowpedia.fandom.com/wiki/Auto-attack "Auto-attacks function separately to the use of specific abilities, and do not interrupt or affect their use."

**Comment by Afgann** [comment]
fixed
