### ISSUE TITLE
[Moved from discord] Blackrock Depths Ring of Law event scripting not complete

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2161]
Ring of Law in Blackrock Depths only spawns first wave then stops causing players to become stuck inside the ring of law.  Requires GM intervention. 

https://www.youtube.com/watch?v=AUq-Tb7rZTY

This is the end vanilla dungeon and a key part of players dungeon leveling from 51-60.

**Comment by Greywolf59** [comment]
Already part of this report https://github.com/gamefreedomgit/Maelstrom/issues/2061
Also worth to note that since Cata players don't have to go through the Ring of Law at all if they are going only for the quests and to finish the dungeon.

**Comment by UltraNixx** [comment]
Fixed.
