### ISSUE TITLE
Player bug - Timewarp not showing as aura for certain player

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2163]
Player 2731(guid) is not seeing buff 80353 (Time Warp) and debuff 80354 (Timeporal Displacement) when casting TIme warp - yet is gaining the stat increase when using aura list.  Issue seems to be fixable by unaura'ing all of this players debuffs but issue returns after relog

**Comment by WhitemaneSylah** [comment]
Have noticed that player has aura 41054 but unable to trace from where

**Comment by WhitemaneSylah** [comment]
![image](https://user-images.githubusercontent.com/121137397/219414595-4e5aaee0-6d9b-41a1-87bf-189650d68863.png)

shown on auralist

**Comment by MrTide** [comment]
its caused by mirror image, it messes with players auras and also might cause server crashes when we .list aura them for further checks, might be a good idea to solve this
this aura stays on the player even after they fade away.

**Comment by Afgann** [comment]
fixed
