### ISSUE TITLE
Open box skill issue

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#2164]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After you learn engineering with the scroll you get base skill and a secondary skill open box, which after 3 seconds of cast gives you 1-3 Ruined metal parts which you can sell to vendor for 2 silver 37 coopers, and you can cast it as many times as you like to get infinite gold.
![image](https://user-images.githubusercontent.com/35288643/219411119-2605b61c-ab9f-46ce-9b5b-b2794e33aea3.png)
![image](https://user-images.githubusercontent.com/35288643/219411204-89066542-ae43-4061-af93-28177b205619.png)
![image](https://user-images.githubusercontent.com/35288643/219411243-bac4985e-16a0-4540-93e4-61f7935369ef.png)

**How to reproduce:**
Learn engineering with a scroll and cast an open box skill

**How it should work:**
It should required an item to be able to use the skill https://cata-twinhead.twinstar.cz/?item=6712

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=105518
https://cata-twinhead.twinstar.cz/?item=6712

**Comment by Afgann** [comment]
fixed
