### ISSUE TITLE
[Quest] [Winterspring] Falling to Corruption - not offered

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2165]
[Falling to Corruption](https://www.wowhead.com/quest=28464/falling-to-corruption)
- One of the starting quests in Winterspring, following closely after Hero's Call: Winterspring! (7/58 loremaster atm)
- Should be offered after handing in [Threat of the Winterfall](https://www.wowhead.com/quest=28460/threat-of-the-winterfall)
- https://wowpedia.fandom.com/wiki/Falling_to_Corruption_(quest)#Progression
- https://www.wowhead.com/quest=28460/threat-of-the-winterfall#comments:id=2535503

**Comment by UltraNix** [comment]
Fixed.
