### ISSUE TITLE
[Quest] [Stonetalon] Last Ditch Effort - not scripted

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2167]
[Last Ditch Effort](https://www.wowhead.com/quest=25891/last-ditch-effort)
- After accepting the quest nothing happens and quest remains incompletable.
- Upon accepting, player should get automounted and event should play out.
- https://www.youtube.com/watch?v=YbuIuFLJuBk
- https://www.youtube.com/watch?v=cDRzJp5xLHg

**Comment by EdyGlockenspiel** [comment]
This quest logs out the rest of the quests in the zone, this includes the Gilneas rep quests, which is generally why anyone would go through all the effort to get to this point questing in the zone to begin with as alliance..
