### ISSUE TITLE
Potion of treasure finding 

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2168]
Description:
While you have potion buff you should be able to drop addidtion chests from mobs that contains mats or gold, Currently chests aren't droping at all.

How to reproduce:
Use potion of Treasure farming and kill mobs on any cata zones.

How it should work:
Chests that are dropping from mobs should contain some cataclysm mats.
 
Database links:
https://www.wowhead.com/item=67539/tiny-treasure-chest#contains

**Comment by Afgann** [comment]
fixed
