### ISSUE TITLE
[Moved from Discord]  [Pet] Pet hold position does not work

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2171]
Warlock, Hunter and Mage pets when placed on "Stay" will continue to follow their master.  This should work the same as the "move to" pet command without the placement ring 

![image](https://user-images.githubusercontent.com/121137397/219762188-c74c60f1-8cd5-41af-95d0-bb0ef59dabcb.png)

**Comment by UltraNix** [comment]
Fixed.
