### ISSUE TITLE
[Moved from discord] - Soul Link causing Fel Armor to heal player when damage taken

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2174]
Spell 19028 (aura 25228) is causing damage TAKEN to heal the warlock with Fel Armor (aura 28176) 

Soul link should not cause any healing interactions.

![image](https://user-images.githubusercontent.com/121137397/219796147-ae6e5393-9ef2-422b-9f58-382b64a71a61.png)

**Comment by Afgann** [comment]
fixed
