### ISSUE TITLE
Shiv not applying poisons 100% of the time

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2176]
Original report: https://discord.com/channels/1040715551531618365/1076253083060944998
https://www.youtube.com/watch?v=OgOn1hv7Y30
The issue was also validated by me outside GM island. This affects all types of poisons (Instant, Deadly, Wound, Crippling, Mind-numbing).

**Comment by Afgann** [comment]
fixed
