### ISSUE TITLE
[CRITICAL][TALENTS] -  Talents that effect spells based on % chance no longer function.  FIX NEEDED IMMEDIATELY 

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#2177]
**Description:**
1. Talent FI from second resto tier is completely useless because it doesn't give you buff for stronger and cheaper healing after you hit with a shock spell.
2. Talent Frozen Power still grants additional 10% dmg against targets with Frostband slow but now it doesn't root target hit by Frost Shock from any distance.
If those 2 don't get repaired till second part of the tournament tomorrow - Shamans might as well throw the towel. So I really insist on priority being high.
3. (This was broken before the restart too) Focused Insight doesn't proc if your shock spell misses. It's a problem both in PvE due to no hit cap and in PvP, since you can't receive it from hitting into immunities like block, detter, cloak etc. 

**How to reproduce:**
1. Spec Focused Insight talent in any shaman spec, use a shock spell, receive nothing.
2. Spec Frozen Power, stand more than 15 yards from your target, use frost shock, it won't root the target.
3. Once point 1 is fixed, try hitting raid target dummy with a shock spell while having Focused Insight talent. Once you miss, you can see you don't get a proc.

**How it should work:**
1. FI should work at all, obviously.
2. FP should make Frost Shock root any target further than 15 yd from you for 5 seconds, as the talent describes.
3. FI should give you proc regardless of hitting the target or not. The talent says "after casting", not "after hitting".

For points 1 and 2 their descriptions alone serve as unquestionable proof.
[https://imgur.com/iTGvMth](url)
[https://imgur.com/6aeIA3I](url)
Point 3 I noticed doesn't occur only on this server.
Written proof from retail guide
https://www.tauri-veins.tk/restoration-shaman-wow-pve-healing-spec-builds-talents-glyphs
Video proof from cataclysm arena:
https://youtu.be/rbPUIC4_mwY?t=100
At 1:39 you can see shaman using his shock spell that didn't apply anything neither to target or focus, yet the FI buff still appeared.

**Comment by MullichWhitemane** [comment]
Marked this as critical as this will affect the ongoing tourney.

**Comment by WhitemaneSylah** [comment]
Author: Afgann
Message: Core/Spell: Add custom proc flag for any spell action done. 
^  This change has broken talents that are based on spells

Examples of this across multiple classes
Hot Streak -  Critical Mass - Master of Elements (Mage) -  Divine Aegis - Surge of Light (Priest)

**Comment by WhitemaneSylah** [comment]
Some talents are working fine -  E.g. eradication for affliction warlocks is working fine evne though is on a % chance

**Comment by MrTide** [comment]
Should be fine now, please update us if it happened again
change reverted for now.

**Comment by Afgann** [comment]
fixed
