### ISSUE TITLE
Priest lightwell click range

### ISSUE THREAD

**Issue by Artemhx** [gamefreedomgit/Maelstrom#2178]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://github.com/gamefreedomgit/Maelstrom/issues/329 the bug report is wrong 
Lightwell has 20 yard click range on cata, always had
also lightwell renew healing is abit low, maybe need fix healing formula
**How to reproduce:**
cast the light well ability as a priest with the holy specialization and click it
You can click it only stay near to lightwell in 1-2 yard
**How it should work:**
Players able to click lightwell from 20 yards

**Database links:**
Sadly wowhead link are not available
https://youtu.be/N1YI9aPz6fU?t=276
https://www.youtube.com/watch?v=9hcnWs8-ybA&t=254s&ab_channel=Shinypally

**Comment by WhitemaneSylah** [comment]
Should be 10 yards not 20 according to sourcecs from retail and no mention in changelogs from patch 4.0.3 - 4.3.4 about it being 20 yards
