### ISSUE TITLE
Shaman's Focused Insight not proccing on misses

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2179]
Original report by ussj10 under https://github.com/gamefreedomgit/Maelstrom/issues/2177 (relevant information copy pasted and validated):

**Description:**
Focused Insight doesn't proc if your shock spell misses. It's a problem both in PvE due to no hit cap and in PvP, since you can't receive it from hitting into immunities like block, detter, cloak etc.

**How to reproduce:**
Try hitting any target with a shock spell while having Focused Insight talent and inadequate hit chance. Once you miss, you can see you don't get a proc.

**How it should work:**
FI should give you proc regardless of hitting the target or not. The talent says "after casting", not "after hitting".
Written proof from retail guide
https://www.tauri-veins.tk/restoration-shaman-wow-pve-healing-spec-builds-talents-glyphs
Video proof from cataclysm arena:
https://youtu.be/rbPUIC4_mwY?t=100
At 1:39 you can see shaman using his shock spell that didn't apply anything neither to target or focus, yet the FI buff still appeared.

**Comment by UltraNix** [comment]
Fixed.
