### ISSUE TITLE
[Unholy Death Knight/PvP/passive] Death's Advance is missing 2 mechanics

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#2184]
**Description:**
1. Death's Advance is supposed to make DK unslowable below 75% speed if his both unholy runes are empty, no additional conditions. Meanwhile here it seems to be tied specifically to melee skills for no reason. It means that if the DK uses a non-melee spell to consume his only remaining unholy rune - the buff doesn't activate. It's a massive fault especially against rangeds, since normally you should just be able to use Death and Decay+AMZ to get the buff and limit enemy's kiting. DnD to keep the buff while somebody kites you around a pillar would also be a very common play if it worked correctly.
It gets even more nonsensical when you test it with Blood Tap. If you use your second U rune with spell like DnD, not get the proc, then use Blood Tap and use that transformed B rune on a skill that normally consumes U rune - the DA buff will activate; further confirming it's heavily tied to melee skill in particular. Which it should not.
2. This is stickier part of this report because I'm not sure how Whitemane treats things that at least seem to be Blizzard's mistakes. But if the server tries to be faithful - here's the other problem: lack of delay. While the DA buff is supposed to activate instantly, it should also have 2-3 seconds delay before it falls off from the DK. It means that after one of DK's U runes comes back from cooldown, the buff should still stay on him for 2-3 sec. I'm saying 2-3 because from my perspective it isn't perfectly consistent, I'll leave the exact number for you to decide.

**How to reproduce:**
1. Spec into unholy spec, take Death's Advance, use first unholy rune on anything, then second on non-melee skill (Death and Decay, Dark Transformation, Anti-Magic Zone, Army of the Dead) and receive no buff. If you did it the other way around though, like first DnD, second Necrotic Strike - the talent would work.
2. Use for example 2 Scourge Strikes to receive the DA buff, wait for one of your U runes to regenerate, the buff deactivates instantly even though it shouldn't.

**How it should work:**
1. DA should activate whenever both U runes are on cooldown, no additional conditions attached.
2. DA should not stop working instantly with the moment your U rune comes back, but instead stay for at least 2 seconds.

I understand that it's both big change and especially the second mechanic might be tempting to refute due to possibility of lags and such of the example at hand. Which is why I decided to risk overdoing it with overwhelming proof from multiple sources, rather than not providing enough. The delay part is easy to find all over the place, I only chose examples that showcase just how extensive it can be, not any outliers.

**Video #1:**
[https://www.youtube.com/watch?v=OCSg6DADT7g](url)
Examples of the delay at 1:22  1:45 and 4:40

**Video #2:**
[https://www.youtube.com/watch?v=E3Pm-NZiKhM](url)
1:46 Example of DnD spell activating DA talent. I suggest watching this moment in slow motion, since DK switches his target to hunter's pet right after, leaving the impression that it's ambiguous whether it's DnD or melee attack right after that caused it. But if you watch on slower speeds, you can see that the buff appeared even before he changed target and too soon after that DnD to fit in another gCD (even for unholy presence standards).
3:35 Here the DK used AMZ and few seconds later DnD, which also activated the DA passive. It happens less than a second before the hunter making that video cuts away to another scenery. Also had no hostile target nearby to use melee attack. You can see it without the cut at 9:13

Side note:
5:36 Mostly unrelated to the topic but just want to point out how the range of AMZ is actually enormous, legit 2x bigger than the bubble suggests. More or less works here but not to the same extent. At 9:19 you can also see that AMZ also is supposed to have a delay of 2 seconds between the spell disappearing and buff disappearing. Those are the only examples of it I could find so I chose to include it only as a small digression to keep in mind, maybe somebody else can make something out of it in the future.

**Video #3:**
[https://www.youtube.com/watch?v=yiii5ultT_Q](url)
0:17 example of the delay, DK was charge stunned and couldn't use up his rune, yet the buff doesn't go away.
1:05  2:59  3:14  4:04  6:05 (big one)  6:40  7:16  8:53  9:19  all clear delay examples
8:15 delay - the DK gained the buff and refreshed all runes with ERW but the buff still didn't have the time to fall off for even a picosecond before he used up both his runes again.

**Video #4:**
[https://www.youtube.com/watch?v=zNQiw69IveY](url)
0:42 big delay
0:53 Dark Transformation used up the only available unholy rune - DA didn't fall off for 4 seconds (so too long to be caused even by the delay, mentioning it to make sure it's not questioned as a proof for first point of the report)
1:12 delay easily 2,5 sec.
2:09 Dark Transformation used - DA didn't fall off (video very sped up here so delay of falling off is this time irrelevant)
2:41 delay
3:11 Dark Transformation used - DA didn't fall off
3:21 delay
3:27 legit 3 seconds delay
3:36 melee skill followed up by AMZ triggered Death's Advance
4:32 easily 3 seconds delay
4:41 Dark Transformation used to keep U runes empty, the DA buff didn't disappear

Pardon the textwall.

**Comment by MullichWhitemane** [comment]
Confirmed, although issue 2 doesn't need any fixing - no point in having an unneccesary delay.

**Comment by UltraNix** [comment]
Fixed.
