### ISSUE TITLE
[Server crash and high diff cause][Vashjir] Broken event causes server to crash.

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2187]
**How to reproduce:**
 There is an scripted event in vashjir that causes server to have high update time diff and crash eventually
 i couldnt investigate further since you freeze pretty much instantly moving around in this area, something is wrong there, i managed to get a gps before it happens.
![image](https://user-images.githubusercontent.com/36106057/220381982-27a2fdf7-647a-4e15-af09-03d1036b8bc6.png)

**How it should work:**
it should not freeze the client and crash the server

**Comment by Afgann** [comment]
fixed
