### ISSUE TITLE
[Wrath][Dungeon] Azjol-Nerub (lag report)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2188]
Engaging these 2 npcs (Anub'ar Warrior & Anub'ar Webspinner) caused the server diff to spike to 700
![image](https://user-images.githubusercontent.com/121137397/220399219-9a24bfdf-6499-4135-a05e-89bc9a86b84c.png)
![image](https://user-images.githubusercontent.com/121137397/220399267-f56c9f25-565f-4881-af82-5a22b833f8bd.png)
![image](https://user-images.githubusercontent.com/121137397/220399353-4bddcef1-53fc-4813-b1c8-cff7305daaef.png)

Krik'Thir the gate watcher - Does not spawn spiders when below 50%

Hadronox event causes server diff of 1000 when killing anub'ar crusher
![image](https://user-images.githubusercontent.com/121137397/220401768-d6486dfe-c11d-4209-9be2-72ccc8bc16c6.png)

Anub'arak burrow on boss fight causes diff of 700

![image](https://user-images.githubusercontent.com/121137397/220402970-1bd5d05f-2b1b-44fb-ab05-d4fdd27f073e.png)

**Comment by Afgann** [comment]
not related
