### ISSUE TITLE
Ahn'Kahet: The old Kingdom (lag report)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2189]
Ahn'Kahar Web Winder causes server diff of 1000
![image](https://user-images.githubusercontent.com/121137397/220405991-8e6a1dd3-b83c-43b1-a9e3-443fd515c003.png)
![image](https://user-images.githubusercontent.com/121137397/220405770-0ef57587-946f-49e4-bb46-a4a70c73ad8a.png)

Bound water elemental causes server diff of 857
![image](https://user-images.githubusercontent.com/121137397/220408623-3a251f5e-998b-4a7c-9b1c-ca0911458453.png)

![image](https://user-images.githubusercontent.com/121137397/220408549-57098f53-a2c0-478f-b99f-6830d47dd79f.png)

**Comment by Afgann** [comment]
not related
