### ISSUE TITLE
[Wrath][Dungeon]The Nexus (lag report)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2190]
NPC Azure Warder Spell Mana Shield causes server diff of nearly 800
![image](https://user-images.githubusercontent.com/121137397/220416317-7ce04273-9c56-4262-8849-7fe66d4fc03d.png)

![image](https://user-images.githubusercontent.com/121137397/220416216-98646e65-e180-41b4-a084-2dbc7754ef8f.png)

NPC Alliance Cleric shadow word: death causes diff of nearly 1k

![image](https://user-images.githubusercontent.com/121137397/220417314-d88789b2-b702-42a7-a15b-6d437c61324a.png)
![image](https://user-images.githubusercontent.com/121137397/220417374-bdb8a742-117e-4669-8d7f-3b7b55334b29.png)

Ormorok The Tree-sapper

![image](https://user-images.githubusercontent.com/121137397/220420640-2cdbb4e1-911c-482b-9909-b8e30c6bf201.png)

**Comment by Afgann** [comment]
not related
