### ISSUE TITLE
Unholy DK Gargoyle doing nothing once combat drops

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2191]
Title. Even if Gargoyle drops combat, due to the debuff, the pet should absolutely try to establish combat again by trying to cast once possible. 

https://www.youtube.com/watch?v=FpK9qYxJK5Y (Here, I Rebuke the Gargoyle, and while he does begin casting again, if I can avoid the 2 second cast, he will never be able to initiate combat again, thus becoming useless)
https://www.youtube.com/watch?v=PQSCYmH97IM at 22:20 (Here, the rogue Kick actually turns the Gargoyle useless for the whole duration, seems as if Kick itself is causing the pet to drop combat, validated outside GM island)

**Comment by UltraNix** [comment]
Fixed.
