### ISSUE TITLE
Spinal Healing Injector - Cooldown not working

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2195]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Spinal Healing Injector from Engineering does not show a cooldown and only resets cooldown upon relogging

**How to reproduce:**
Learn Engineering
Use the Tinker "Spinal Healing Injector" on your gloves
Use the gloves
Notice how a cooldown doesn't show and trying to use again gives an error.

**How it should work:**
Should show a cooldown and be usable again on expiry

**Database links:**
https://www.wowhead.com/spell=82200/spinal-healing-injector

**Comment by UltraNix** [comment]
Fixed.
