### ISSUE TITLE
[Moved from discord] Redridge quest line

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2198]
Enerhy
OP
 — 02/08/2023 5:40 PM
You can easily dupe your guardians from quest line : " https://www.wowhead.com/quest=26562/and-last-but-not-least-danforth " . It can be doable by dying on this quest when you have those npc near you. They will not despawn but come to you, however, if you get too far away from them by slowing them down on focusing enemy npc, new group of those npcs will spawn. that way you can easily dupe them and basically IK every mob you target. free exp. Only way they despawn is by turning in quest. They will be always same lvl as you.

**Comment by MrTide** [comment]
Player is correct
you can get a lot of them by dying as well
![image](https://user-images.githubusercontent.com/36106057/220737558-2b0337b6-b8f0-4703-bbe6-60f6aa6c85c7.png)

**Comment by UltraNix** [comment]
Fixed.
