### ISSUE TITLE
Warlock Conflagrate failing to account for extra ticks from Haste

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2201]
Original report: https://discord.com/channels/1040715551531618365/1077908127799848960

Conflagrate on Whitemane doesn't account for all the Immolation ticks in your Immolation - f.e. having enough haste to get 6 ticks, Conflagrate will still do damage as if only 5 ticks were available.

Example: Immolation tick does 2862 damage and you are sitting at 16% haste so that you get 1 extra tick of Immolate
Multiply by 6, 17172 Immolation DoT damage, multiply by 0.6 to get your Conflag damage, you get an expected result of 10303
Yet Conflag does 8586 damage

If we do the same above calculations, but replace 6 by 5:
2862 * 5 = 14130 Immolation DoT damage
14130 * 0.6 = 8586 Conflagrate damage

It seems as if Immolation is actually scaling 100% blizzlike with Haste, its Conflag that isn't.
Doing the same test but with 7 ticks at 30% haste, you end up with a Conflag damaging for 10303, even though the expected damage should be 12020.
![conflagrate](https://user-images.githubusercontent.com/121984461/220818219-f1ff5cb3-3a67-4ea6-b9cd-846e9706d721.PNG)
Note that Conflagrate shouldn't account for any Immolate crits - it's only the normal tick that Conflagrate uses to calculate.
Marking this as a High priority issue as Conflagrate is Destro's hardest hitting spell.

**Comment by UltraNix** [comment]
Fixed.
