### ISSUE TITLE
Enhancement Feral Spirit visual bugs

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2203]
Original report: https://discord.com/channels/1040715551531618365/1078035967820169317

The wolves seem to benefit from effects such as Unleashed Rage and Strength of Earth totem, as the buffs show up in their buffbar, but they correctly don't benefit from it.
Relevant copy paste:
Retail source: https://youtu.be/QHLPaND6vjI?t=349
Whitemane behaviour: 
![feral wolves](https://user-images.githubusercontent.com/121984461/220820263-a2617e3a-2d2d-4f25-b384-de7fa514aefe.png)
6vjI?t=349

**Comment by UltraNix** [comment]
Fixed.
