### ISSUE TITLE
Warlock Imp utility spells not being put on the Spell Queue while casting Firebolt

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2204]
Original report: https://discord.com/channels/1040715551531618365/1075654067084337203

Title. Video: https://www.youtube.com/watch?v=LxOeB5QTFa0
Normally, the Imp should place the casted utility spells in his spell queue, meaning that as soon as his current Firebolt finished casting, he will cast Flee / Singe Magic.

**Comment by MrTide** [comment]
Now it still says another action in progress but i believe that is how it should be.
and after finishing the cast imp casts the next spell in queue right away
So its fixed
Thank you closing this.
