### ISSUE TITLE
Hard casted Aimed Shot consume ''Fire!'' with no effect.

### ISSUE THREAD

**Issue by SexyPancake** [gamefreedomgit/Maelstrom#2206]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
''Fire!'' spellID: 82926 being consumed without granting the proper effect on hard casted Aimed Shot.

**How to reproduce:**
MM spec.
Cast Aimed Shot before acquiring ''Fire!'' 
by queuing Aimed Shot will at ''Ready, Set, Aim'' 4 stacks spellID: 82925
granted by Master Marksman 3/3 spellID: 34487.

Upon landing on target the hard casted Aimed Shot will consume ''Fire!'' wasting your proc and not refunding the focus cost.

**How it should work:**
The hard casted Aimed Shot should not consume the ''Fire!'' buff.
No reference to this behavior on blizzard forums or the wayback machine to EJ theorycrafting  MM hunter forum.

**Database links:**
# https://cata-twinhead.twinstar.cz/?spell=82925

# https://cata-twinhead.twinstar.cz/?spell=82926

# http://web.archive.org/web/20111228154621/http://elitistjerks.com/f74/t112408-cataclysm_4_3_marksmanship_guide_up_section_6_5_updated_4_3_a/#4_4_Enchants

Ctrl+G research was done with the words ''Aimed Shot'', ''Master Marksman'' and ''Fire!''.

**As my first github submission in years any feedback for accuracy is welcomed**

**Comment by MullichWhitemane** [comment]
I can't recreate this issue. Can you describe how you recreated it a bit better? What zone were you in, PvE / PvP target, Target Dummy or not, etc.

**Comment by SexyPancake** [comment]
Any update on the matter? Tested as today and the bug is still there. Adding the screenshot that I linked via PM in Discord :
![Fire!](https://user-images.githubusercontent.com/88563815/222544467-d7824cc6-d581-421f-b3bf-f8139a770077.png)
