### ISSUE TITLE
Spirit Wolf Damage

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2208]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Damage formula/scaling of spirit wolfs are wrong, they are doing double damage here on Whitemane compared to retail cataclsym.
If you watch this clip https://www.youtube.com/watch?v=rZo2J2OQsxg the shaman has 9416 attack power, later on at 1:20 of the video, he pops blood fury which gives him additional 1170 attack power, that means that he has 10586 attack power at the time of using spirit wolfs, he then pops spirit wolfs and they do 760 and 807 damage which you can see clearly at 1:30 of the video. Pets generally have orange numbers instead of yellow so they're easy to distinguish. Okay that's retail cataclsym. As for Whitemane, if you check this screenshot, https://imgur.com/a/PcNKPc6 I have equipped the same gear as the mage in the retail video which can be seen at 0:10 of the video, if you want to make sure of what gems and enchants hes using you can slow down the video to 0:25. I specced into arcane just like the mage in the video, I also picked up the talent Prismatic Cloak 3/3 points in arcane which would then give me 6% damage reduction incase the mage had it too. Now please check this screenshot, https://imgur.com/a/KVNXOvx Regis (from Whitemane PTR) has 10573 attack power which is only 13 attack power difference of that retail shaman, and as you can see his wolfs are doing 1810, 1815+ damage (with Glyph of Feral Spirit) on the screenshot. Here is a video proof https://www.veed.io/view/83995de6-253c-4115-a128-e7386a81d703?sharingWidget=true&panel=share in this clip you can see that the wolfs are doing way higher damage than the retail video I linked with the same gear, stats, spec and attack power replica. If you are wondering what patch the retail video I linked was on, it's from patch 4.0.6 and our Whitemane patch is 4.3.4, but there are no changes made to shamans Spirit Wolfs between 4.0.6 to 4.3.4 which means that the damage scaling of them remained the same throughout entire cata.

**How to reproduce:**
Make a shaman, spec into enhancement, get Glyph of Feral Spirit, get 10573 or 10586 attack power without any totems, no buffs other than Unleashed Rage. Make a mage, spec into arcane with Prismatic Cloak 3/3 in arcane talent tree, buy full honor pvp gear with gloves being an exception (it should be season 9 vicious gloves) Use 1x 40 resilience gem on any socket in your gear to match the resilience aswell as seen in the video above, duel the mage and use spirit wolfs.

**How it should work:**
Spirit Wolves receive 30% of the shaman's attack power, then another additional 30% attack power if you glyph into Glyph of Feral Spirit which makes it 60% of the shamans attack power in total. But as you can see in these screenshots and video, they are being scaled way above that. How? Nerf them with certain % according to the numbers provided with proof videos above.
It's clear that the shaman on retail video is using Glyph of Feral Spirit (Spirit wolves gains additional 30% of your attack power) even if it doesn't show it in the video. If you check this video which is another retail pov https://youtu.be/IRYBZ9kV4Ko?t=233 at 3:53 minute. He has way more attack power and bigger modifiers buff, he is also in season 11 gear which has a lot more agility than season 9 gear but yet his wolfs are doing below 1k damage only. Another great clip https://www.youtube.com/watch?v=qfjD7c9B8Tc none of these shamans wolves hit more than 1k unless it's a crit or full raid buff.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Feral_Spirit

**Comment by MullichWhitemane** [comment]
I will preface this by saying that it has been confirmed by Foster that the Wolves do actually get the correct amount of attack power on summon - 30% normally, 60% glyphed, this has been confirmed by a database check.
![proof](https://user-images.githubusercontent.com/121984461/220887662-c91fd0fc-48a1-4513-a6b1-2e71ef4e11dc.PNG)
I will also mention that the original video is from 4.0.6. While there were no balance changes going forward, there was one important change in 4.1: https://wowwiki-archive.fandom.com/wiki/Patch_4.1.0
_"Resilience scaling has been modified for linear returns, as opposed to increasing returns. Under the new formula, going from 30 resilience to 40 resilience gives players the same increase to survivability as going from 0 to 10. Resilience now scales in the same way armor and magic resistances do. A player with 32.5% damage reduction from resilience in 4.0.6 should see their damage reduction unchanged in 4.1. Those with less than 32.5% will gain slightly. Those with more will lose some damage reduction, increasingly so as their resilience climbs."_

I've set myself up accordingly to the first video: 10.5k attack power against a fully PvP geared Arcane Mage who was using Mage Armor - the Mage itself had 23.68% armor and 38.16% resilience. Remembering the Resilience change, my Mage had less active mitigation going on by roughly 3% (if I did the math correctly, formula taken was from https://wowwiki-archive.fandom.com/wiki/Resilience).
![enha pov](https://user-images.githubusercontent.com/121984461/220888339-217481b6-9f61-4345-8914-d443b4d91330.PNG)
![mage pov](https://user-images.githubusercontent.com/121984461/220888363-fe10e4db-d624-4367-b3ba-bdd420107b44.PNG)

The Resilience change doesn't explain the damage discrepency still however. But what does is the following - I have removed enough attack power from my Shaman to line up with the original 9416 unbuffed attack power. After testing:

![after removing ap](https://user-images.githubusercontent.com/121984461/220888733-4259006a-1802-463b-822d-f71662d9f29e.PNG)

And in this case, the Resilience change does actually explain the damage discrepency. After looking through the other footage, it seems as if on Retail, the Wolves only scale with the Shaman's RAW stats - modifiers and such aren't taken into account. I couldn't find an official source for this, but this is what seems to be the case - the Wolves simply seem to ignore the vast sums of Attack Power inherited by buffs and such on Retail. At the same time, it makes no sense for the Wolves to not take the buffs into account - pet summon snapshotting is a thing, but we also have to remember that Retail had spell batching, so the on use effects might not be going through on summon.

I will mark this as Status: Info Needed for now.

**Comment by MullichWhitemane** [comment]
@Torpis did some digging and found the 4.3 enhance sim and source code. Need a DB check on the following numbers:
const f32 SPIRIT_WOLVES_MANA = 0.12f;
const int SPIRIT_WOLVES_COOLDOWN = 12000;
const int SPIRIT_WOLVES_DURATION = 3000;
const int SPIRIT_WOLVES_ATTACK_POWER_BASE = 932;
const f32 SPIRIT_WOLVES_DPS_BASE = 490.06f;
const int SPIRIT_WOLVES_ATTACK_SPEED_BASE = 150;
const f32 SPIRIT_WOLVES_ATTACK_POWER_SCALING = 0.3295f;
const f32 SPIRIT_WOLVES_HIT_SCALING = 1.0f;
const f32 SPIRIT_WOLVES_CRIT_SCALING = 0.0f;
const f32 SPIRIT_WOLVES_EXPERTISE_SCALING = 1.0f;

**Comment by MrTide** [comment]
Well done on testing everyone, although further testing shows that damage calculations that you guys have done are correct but there are some minor differences in resil + racials and not using the glyph which yields the different results, but using the same numeric values and what you missed in calculations shows that damage is still way higher than it should, in some cases almost double. we don't know what the exact calculations are in our database, all we can see is that no talent or glyph beside shaman unleashed rage, Glyph of feral spirit has effects on those wolves, basically what ever that should effect those wolves are effecting them, even checked the auras to make sure if they are visual or have any negative effect towards our tests.
the class balance changes throughout the different patches can not be the reason for such big difference in damage.
Hopefully we will be able to gather more data on this moving forward.

**Comment by MrTide** [comment]
> 

Basically yes, we don't know if they are using the glyph or not, if they are using it that means then our core feral spirits are doing almost double the damage in same cases and should be nerfed, but if they are not using it the difference is basically about 10% worst case scenario.

**Comment by UltraNix** [comment]
Fixed.
