### ISSUE TITLE
Warlock's Aura of Foreboding does not root for long enough on PvP targets

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2209]
Original report: https://discord.com/channels/1040715551531618365/1076456936876298240

https://www.youtube.com/watch?v=-LDYuyyUniI
When talented 2/2, Hand of Gul'Dan still roots PvP targets for two seconds. It should root for three seconds.
The root works perfectly against any PvE target.

Edit: The root effect also DRs itself fully when applied, making it so that if try to use Hand of Gul'Dan to root again just shortly after it came off cooldown, it won't work.

**Comment by UltraNix** [comment]
`Edit: The root effect also DRs itself fully when applied, making it so that if try to use Hand of Gul'Dan to root again just shortly after it came off cooldown, it won't work.`
Please provide source that it should not apply DR.

**Comment by melezdev** [comment]
@UltraNix can be seen here: https://www.youtube.com/watch?v=fHeKCbgsMZ4&t=712s
One warlock roots, then the second warlock roots. The root is still 3 seconds in the second case.
