### ISSUE TITLE
Pet movement when trying to face attacking enemy pets up close

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2211]
https://www.youtube.com/watch?v=WJ44kmA_t0A
When you are trying to face enemy pets that are meleeing you, they will always move 180 degrees directly behind you. Normally, they should only update their position if their target moves on the XYZ, not when turning their character around. This makes fighting pets as casters insanely difficult especially in PvP.

**Comment by Afgann** [comment]
fixed
