### ISSUE TITLE
Priest Atonement issues

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2212]
Original report: https://discord.com/channels/1040715551531618365/1076985196664078396
https://www.youtube.com/watch?v=L7X7LEFaufw
Priest's Atonement has a much greater range than the advertised 15 yards around the enemy target. Atonement also fails to heal when your Smite or Holy Fire critically damages, and Atonement also doesn't heal 1:1 the damage dealt, but instead a bit more.

**Comment by UltraNix** [comment]
`Atonement also doesn't heal 1:1 the damage dealt, but instead a bit more`
https://wowpedia.fandom.com/wiki/Atonement?oldid=2856772
```
The returning heal from Atonement is also affected by buffs/debuffs that affect healing
```
Not a bug.

**Comment by UltraNix** [comment]
Fixed.
