### ISSUE TITLE
Unholy DK Ghoul not casting Claw at the correct energy values

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2214]
Original report: https://discord.com/channels/1040715551531618365/1077970070891921428
(I've hit the daily upload cap on youtube, ouch - will attach relevant video once the daily cap resets)

Claw costs 40 energy, and as such, if the Ghoul has a minimum of 40 energy, it should be able to cast if ordered - currently however, it seems as if Claw can only be casted (either manually or by enabling auto-cast for the Ghoul) when the Ghoul is above 70 energy, letting a lot of burst damage go to waste.

**Comment by Afgann** [comment]
fixed
