### ISSUE TITLE
[Quest] End of the Supply Line

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#2215]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
For what i have seen the view distance/game generation distance generates a issue in this quest, in the case there was a lot of people trying to complete this quest it could cause issues and waste a lot of their time.

**How to reproduce:**
Move far from the distance where the initial NPC respawns

**How it should work:**
There should be all the time NPC generation
https://www.youtube.com/watch?v=3DWBiHIyPaU&ab_channel=GitGudGuides

**Database links:**
https://www.wowhead.com/quest=25233/end-of-the-supply-line

**Comment by MadeinNoxus** [comment]
The issue is that are supposed to be respawning all the time and not just if you are on the NPC respawn spot

**Comment by MrTide** [comment]
these guys spawn here and have pathing issues, i think they need to spawn near bridge not in this location
![image](https://user-images.githubusercontent.com/36106057/221318507-fe43570e-5d19-4ac1-bc01-af1b1d167043.png)
![image](https://user-images.githubusercontent.com/36106057/221317787-79d24536-4de4-4de9-ae4b-c859cecbf2fd.png)
and movement issues, stuck on falling animation sometimes
![image](https://user-images.githubusercontent.com/36106057/221318619-18fc6670-96d8-4e70-ba15-40688af50c44.png)

other than that looks like they are spawning now even if you are not in their spawn location i sat here for a few mins and they came in
![image](https://user-images.githubusercontent.com/36106057/221319031-ceb8e05f-aefd-4fd7-b1b8-2a661bc37c69.png)

if you think that is not important you can close it Ultranix

**Comment by UltraNix** [comment]
The spawn position is moved due to grid system issues.
Movement will be fixed soon.

**Comment by MadeinNoxus** [comment]
Not important until there is multiple people stuck with the same quest and they start sending tickets or complaining about the quest.

**Comment by MrTide** [comment]
also looks like there are some phasing issues, as you can see me moving back and forth also shows the phasing issue
![image](https://user-images.githubusercontent.com/36106057/221430145-8ed87b7d-1a27-4ff0-a1d0-6b8ded773d69.png)
player couldnt see them 
![image](https://user-images.githubusercontent.com/36106057/221430145-8ed87b7d-1a27-4ff0-a1d0-6b8ded773d69.png)
Player quest list
![image](https://user-images.githubusercontent.com/36106057/221430202-0d438ddd-9467-40c5-8255-082f87b55820.png)

**Comment by s71n63r** [comment]
I made a video clip but I don't have editing superpowers so it's to large to post here. I posted it here.

http://64.33.111.8/pub/Whitemane-2023-02-26-13-15-57.mp4

**Comment by Greywolf59** [comment]
Yup, I have already mentioned in the old report that the part of the path they walk through belongs to the zone "Shrine of Goldrinn" and if player enters this zone, he phases out/can't see them.

**Comment by MrTide** [comment]
Update: they now spawn at the right location but players having phasing issues with them
also sometimes they just dont work
![image](https://user-images.githubusercontent.com/36106057/222946839-9a32ef07-b669-48db-8b4e-63ef2a6ee0e0.png)

**Comment by GMHiki** [comment]
creature ID 39431 (twilight slave) needs to despawn after certain time or else.. this
