### ISSUE TITLE
[Moved from Discord] Reinforcements.... -  Not obtainable after completing prerequisite 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2217]
Sattva
OP
 — 21/02/2023 07:01
Quest Link: https://cata-twinhead.twinstar.cz/?quest=26066
Prequest: https://cata-twinhead.twinstar.cz/?quest=26060

Quest is not acceptable at all. Should be unlocked after pre-quest "Da Voodoo: Stormer Heart" (quest linked above).

**Comment by MrTide** [comment]
Thank you Ultranix
Recent fix applied by you fixed the issue
Quest is now available for players. closing the issue.
