### ISSUE TITLE
[Moved from Discord] [Quest] Ring of Destruction - Phasing change causes formshift.

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2218]
Sattva   (REPORT LINK FOR ACCESS TO VIDEOS) https://discord.com/channels/1040715551531618365/1077477469222871060

OP
 — 21/02/2023 06:30
Quest Link: https://cata-twinhead.twinstar.cz/?quest=13798
Sometimes, very randomly you lose Imp form and your phasing changes, makes quest hard to complete!

Tested many times on different chars and classes.

As i said it's very random, you might lose it right away or you may not lose it at all. 

Hard to reproduce, usually happens when you run in the cave. 
Could be related to my Aquatic Form bug report, because it behaves the same - pure random, no reason.

Link to Aquatic form Bug report:
https://discord.com/channels/1040715551531618365/1076098895635021875

https://cdn.discordapp.com/attachments/1077477469222871060/1077477470388879401/Rain_of_Destruction_Druid.mp4
https://cdn.discordapp.com/attachments/1077477469222871060/1077477471634604052/Rain_of_Destruction_Mage.mp4

**Comment by MrTide** [comment]
you dont lose your aura anymore by the look of it but at the end of the quest you get two of them i am assuming one of them should phase out
![image](https://user-images.githubusercontent.com/36106057/221323761-6a377bc7-b057-4523-864f-2bb502df27f4.png)
i have done a similar report before
https://github.com/SallyWhitemane/Maelstrom/issues/515
but if you think that is ok, you can close it Ultranix beside that disguise worked fine.

**Comment by UltraNix** [comment]
Open a new report.

**Comment by Sattva-108** [comment]
I just lost my imp form again 3 times in a row (after fixes applied to PTR) 
It always happens on the first hill next to the quest giver, easy to reproduce.

**Comment by MrTide** [comment]
> 



> I just lost my imp form again 3 times in a row (after fixes applied to PTR) It always happens on the first hill next to the quest giver, easy to reproduce.

it doesnt happen to me, does it happen to you everytime ? can you please provide a video ?

**Comment by Sattva-108** [comment]
@MrTide 
The spot is next to the quest giver, the hill in the cave.
Watch video #4 https://discord.com/channels/1040715551531618365/1077477469222871060
I can reproduce it every 30 seconds no problem.

It's not a pixel of issue. I think it has nothing to do with this quest bug.
It might be server-side issue with forms. I had some quests same bug as this one and i also lose Aquatic  Form randomly, i have been reporting it. 

If you dont believe its common issue, then try to do https://www.wowhead.com/quest=24695/ever-watching-from-above#
I always was losing Bloodpetal form once i come close to the ridge.

Hope you can do something before launch thank you!
