### ISSUE TITLE
[Moved from discord] Mor'shan Defense - Cannot be picked up - no pre-req's 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2220]
Sattva
OP
 — 18/02/2023 05:05
Can't pickup quest.
It requires quest: https://www.wowhead.com/quest=28876/to-the-morshan-rampart

This quest not supposed to have any pre-quest according to:
Cata DB: https://cata-twinhead.twinstar.cz/?quest=13612
And WoWHead comments: https://www.wowhead.com/quest=13612/morshan-defense

As said in WoWHead comments and Zygor guides, those 2 quests are "breadcrumbs" meaning they are not pre-quest and will disappear once you have taken "Mor'Shan Defense" quest.

**Comment by PanJanuszek** [comment]
Q28876 - This quest is removed in 4.0.3.
Rest - fixed
