### ISSUE TITLE
[Core][Dungeon] Need before greed not aligned to class weapon/item usage

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2221]
Dungeon loot can be greeded / needed by any class despite classes not being able to use it.  Image below of how this should work for each class 

![image](https://user-images.githubusercontent.com/121137397/221069008-803d6f43-7647-4fb0-8ff6-40329bbae3d6.png)

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
@Afgann  please do not close this issue until our tester team have verified it.  This test was done with GM accounts and may have messed up the results.  I will update you when this has been done

**Comment by Commander-Rug090** [comment]
![Untitled](https://user-images.githubusercontent.com/123824412/221425867-c51eca27-6959-43ed-a347-349732d5a04b.png)

**Comment by MrTide** [comment]
@Afgann Thank you for the changes, so far it works Ok.
there are a few issues which need to get fixed
1. Players should not be able to change loot spec it should be greyed out on need before greed and uncommon. that should be default loot for Dungeon finder system
2. Shield is missing from the list above
![image](https://user-images.githubusercontent.com/36106057/221436795-35e470bd-e853-44fa-8716-7d674c759bf0.png)
If something else comes up over time we will update you
Thank you

**Comment by Commander-Rug090** [comment]
update: 
after a chat with Tide and a few saner heads, we came to the conclusion that the loot rules may not be broken, but the RDF loot rules not overriding the party system loot rules, this was tested and seemed accurate although a more comprehensive test could not be carried out at the time.

**Comment by UltraNixx** [comment]
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

```Note: Premade groups of five which use the Dungeon Finder to queue will function more or less like a normal group. The group leader will retain the ability to remove other group members and set the group’s looting rules. The difference is that these groups, unlike normal groups, will be able to earn daily random dungeon rewards and access the dungeon teleportation system. Certain features and benefits, however, like the Vote Kick system and "Luck of the Draw" buff (detailed below), will not be available for these group types.```
As long you won't source it has not been changed on Cata, I will close it.

**Comment by MrTide** [comment]
> 



> https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/
> 
> `Note: Premade groups of five which use the Dungeon Finder to queue will function more or less like a normal group. The group leader will retain the ability to remove other group members and set the group’s looting rules. The difference is that these groups, unlike normal groups, will be able to earn daily random dungeon rewards and access the dungeon teleportation system. Certain features and benefits, however, like the Vote Kick system and "Luck of the Draw" buff (detailed below), will not be available for these group types.` As long you won't source it has not been changed on Cata, I will close it.

Thanks ultranix if that is how its supposed to be then i will close it
otherwise it works fine

**Comment by MrTide** [comment]
Minor issue, reopening the thread
Hunters should be able to roll for leather until lvl 40
https://cdn.discordapp.com/attachments/1081353996490522654/1081354015083860050/send_to_gm.png

**Comment by MullichWhitemane** [comment]
Allegedly, the following issues exist:
- Shaman's can't roll need on leather within the 1-39 level ranges https://discord.com/channels/1040715551531618365/1081373646045577316
- Paladin's cant roll need on mail within the 1-39 level ranges https://discord.com/channels/1040715551531618365/1081375597101596683

**Comment by UltraNixx** [comment]
Should be okay now.
