### ISSUE TITLE
[Moved from Discord][Death Knight Starting Zone Quest] Massacre At Light's Hope (Cart not functioning)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2224]
![image](https://user-images.githubusercontent.com/121137397/221215635-6ed9dd95-96f5-47dd-bfe0-a9dcbe10dbf3.png)

Clicking on the cart will spawn you where the cart should be but outside it, the object then reverts to being clickable.

![image](https://user-images.githubusercontent.com/121137397/221215683-ff2fd652-9d32-4274-bb1b-0907f4b8d004.png)

**Comment by UltraNix** [comment]
Fixed.
