### ISSUE TITLE
[Moved from Discord] Furious Howl (Hunter pet buff) not being given to the pet itself

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2225]
![image](https://user-images.githubusercontent.com/121137397/221217295-4034f7d0-0d42-4c54-9597-62e1e6452bcd.png)

This buff is not being applied to the pet when used 
![image](https://user-images.githubusercontent.com/121137397/221217365-e8f9061f-dc60-4e60-8ac8-61499ee7d44a.png)
https://media.discordapp.net/attachments/1077971713008083065/1078664123165974569/image.png?width=713&height=616

How it should behave:  When the pet uses Furious Howl it should also buff itself and any pets in the party with the same buff

**Comment by bonfax4** [comment]
@UltraNix
