### ISSUE TITLE
[Balance Druid/PvP/Item] 4set gives energy but doesn't activate druid's eclipse

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#2228]
**Description:**
The 4set PvP bonus for Balance Druid spec gives you eclipse energy whenever you receive damage from critical strike, with the effect having 6 sec. CD. However on PTR it will grant the energy but won't activate the Eclipse (whether Solar or Lunar) on it's own when that energy reaches 100. You have to cast something to activate it yourself.
It can get even worse though, since sometimes when that happens you're unable to move the bar yourself, with the only option being relog or death to reset it back to 0. This part is particularly gamebreaking for druids, since this set bonus is their main source of energy in PvP scenarios other than BGs; so you can't really afford playing without it, while at the same time it can do more harm than good.

**How to reproduce:**
Equip 4 PvP parts on your Boomkin, get some energy and then ask another player or find a mob to critically strike you until your energy reaches 100.
Second part of the report (energy becoming immovable by your spells) happens randomly and I don't know any way of reproducing it. However fixing the former theoretically should make it impossible for the latter to happen again.

**How it should work:**
The set bonus giving you energy should make you enter Eclipse once you reach 100 energy, not require any further spells, let alone block itself.
Example at 8:59. Thyraz entered Eclipse while being in process of casting a Cyclone on enemy rogue. The only other sources of Eclipse energy are Wrath, Starfire, Starsurge and Moonfire's **direct** damage benefitting from Lunar Shower talent. None of them could be used while casting another spell, hence the Eclipse must've occurred because of rogue critically hitting him.
[https://youtu.be/bKTyHBKs0-0?t=536](url)

**Comment by MullichWhitemane** [comment]
Couldn't recreate the 2nd part of the issue, do you think you can reproduce it somehow and record it @ussj10?

**Comment by ussj10** [comment]
@MullichWhitemane 
I attempted different ways of testing it today. In animal form, in cc (stun and silence) and animal form, whether all energy came from the set bonus or only the last part, with both eclipses (tho one thing I remember for sure is that it was Solar when it happened to me). None of those produced "blocked energy bar". So I think it's just random. Happened only once and on GM island so hopefully this part won't be a problem again.

**Comment by UltraNix** [comment]
Fixed.
