### ISSUE TITLE
[Moved from Discord] Master's call is going on cooldown and not providing buff outside of LoS

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2229]
**Description:**
https://youtu.be/UQr6FmdOVVo
spell 53271 goes on cooldown without providing the buff if pet is out of LoS.
**How to reproduce:**
Use Master's Call when pet is outside of LoS (For example, via smoke bomb) 

**How it should work:**
Spell should not go on cooldown IF cannot provide buff due to LoS 

EDIT:  Master's call also is going on cooldown when used on a target that is  out of range - but pet will not travel to the target  to provide the buff either

How it should work -  The spell should not go on cooldown if the pet is outside of its casted range (40 yards from pet to target)

**Comment by sassouiabd** [comment]
I will that the spell should not be triggered in the first place.
The hunter is inside the smoke bomb and the pet is outside the smoke bomb.

**Comment by UltraNix** [comment]
Fixed.
