### ISSUE TITLE
[Moved from discord] Certain spells do not work after player goes into LoS

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2230]
Potential bug inhereted from Atlantiss Dragonwrath core - need check from Devs.  

Currently when going being LoS - Certain spells do not trigger their effects ,  the classes and spells affected are below
DK
Unholy Blight

HUNTER
Concussive Barrage
Flare
Serpent Spread

Confirmation from GM Fireboy who played on atlantiss this was a bug - 
![image](https://user-images.githubusercontent.com/121137397/221290504-185e458b-bfbb-4f81-9db7-62547d9960a1.png)

Dev check required - please check if their are any LoS flags to the spells labled above and test again spells such as warlocks Felflame etc

**Comment by Afgann** [comment]
fixed
