### ISSUE TITLE
Death Knight Pet Leap Bug 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2232]
PrinceArt
OP
 — Today at 23:03
The bug: When you use pet leap while your pet is in any root (tested on other root classes e.g. hunter snake trap) your pet leap will go on cooldown. If you use your pet leap while your ghoul is under Dark Transformation and in a nova, the leap will work, interrupt the player and immobilize them as written in the tooltip.
Proof: https://streamable.com/0qt50o

How to reproduce: Make a Death Knight, Spec unholy for ghoul control. have your pet rooted from any class that can root and use leap while the pet is being rooted in his normal form, then in the dark transformation form.

How it should work: Using pet leap while the pet is in its normal form and in a nova should not make the spell go on cooldown. It should just give an error message instead, something similar as other classes like warriors charge, rogues shadow step and feral charge etc, "cannot perform this spell right now" you get the point.

How it should work under dark transformation: It shouldn't work at all and just give an error message like written above until the pet is free from the root.

Couldn't find any video or comment proof from retail but I've got this as proof: https://streamable.com/6zk054

**Comment by UltraNix** [comment]
Fixed.
