### ISSUE TITLE
Non-damaging interrupts Should not miss

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2233]
**How to reproduce:** 

simply use these abilities on players

Pummel ID 6552:
![image](https://user-images.githubusercontent.com/36106057/221331246-4b36de76-a351-4be6-9a3b-f70e58799d7d.png)
![image](https://user-images.githubusercontent.com/36106057/221331265-295b769f-1141-4404-8260-37c7dcec62f9.png)
Kick ID 1766:
![image](https://user-images.githubusercontent.com/36106057/221331286-17471646-0b6c-4855-9563-ade77710934f.png)
![image](https://user-images.githubusercontent.com/36106057/221331319-65b16e21-238b-41e5-b1b5-68a3b8cee693.png)
Rebuke ID 96231:
![image](https://user-images.githubusercontent.com/36106057/221331768-3ec5a0c5-c2c0-43d7-af3b-93006722f210.png)

**How it should work:**
according to this evidence kicks and similar abilities to it should not miss, dodged or parried 
https://wowpedia.fandom.com/wiki/Interrupt
![image](https://user-images.githubusercontent.com/36106057/221331188-8cd50f27-44ba-4cf1-ba16-19764aab3b3f.png)
Beside these three listed above rest seemed fine

**Comment by UltraNix** [comment]
Fixed.
