### ISSUE TITLE
[Moved from Discord] [Warrior] Shield Wall - Retaliation - Recklessness,. should not be stackable

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2234]
https://youtu.be/SreZ-dLSr2Y

^ Retail video 

When using Recklessness  -  Shield wall AND Retaliation should go on a 12 second cooldown to ensure they cannot be stacked
When using Shield Wall - Recklessness and Retaliation should go on a 12 second cooldown to ensure no stacking
When using Retaliation - Shield Wall and Recklessness should go on a 12 second cooldown to ensure no stacking

How it functions on our server - They can all be stacked
![image](https://user-images.githubusercontent.com/121137397/221356866-825e6850-ae05-42ca-90f6-0177b9569bd0.png)

**Comment by UltraNix** [comment]
https://youtu.be/SreZ-dLSr2Y?t=21
I see Recklessness on cd used Deadly Calm?), but Retaliation is still up.

**Comment by MullichWhitemane** [comment]
This is not a bug.
https://vanilla-wow-archive.fandom.com/wiki/Recklessness
"As of Patch 3.0.2 (Wotlk), it NO longer shares cooldown timer with [Shield Wall](https://vanilla-wow-archive.fandom.com/wiki/Shield_Wall) or [Retaliation](https://vanilla-wow-archive.fandom.com/wiki/Retaliation)."
