### ISSUE TITLE
[Dungeon] Blackrock Caverns boss Rom'ogg - Chains of Woe untargetable

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2237]
Chains of Woe cannot be targeted by players,  video attached in discord report (link below)

https://cdn.discordapp.com/attachments/1078779385307471964/1079044462472331304/Desktop_2023.02.25_-_15.14.51.08.DVR.mp4

https://discord.com/channels/1040715551531618365/1078779385307471964/1079044464481407047

Boss is incompletable when this bug is present

**Comment by UltraNixx** [comment]
Fixed.
