### ISSUE TITLE
[Moved from Discord] Stoneclaw totems stun diminishing returns bug

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2238]
PrinceArt
OP
 — Today at 03:42
The bug: Stun that you receive hitting the Stoneclaw totem is not sharing same diminishing returns with other stuns.
Proof: https://streamable.com/at15bo, https://streamable.com/nalwm7

How to reproduce: Duel a shaman, ask him to use Stoneclaw totem, hit it and you'll be stunned, hit it again and you'll be DR stunned, then get another stun class user to stun you.

How it should work: Stoneclaw totems stun should be on the same diminishing returns as all other stuns e.g. Cheapshot, Kidneyshot, Throwdown, Bad manner, Wolf stun, Hammer of justice etc. In other words, if you have been stunned from Stoneclaw totem 3 times, you are immune to any stuns until the diminishing returns are back.

Retail proof: https://youtu.be/OWLI0lIusVo?t=627 I've linked with the timestamp, here the rogue in the video intentionally hits the stoneclaw totem so he would get stunned by it which puts him in a stun DR to avoid enemy rogue stun later on.

**Comment by Afgann** [comment]
fixed
