### ISSUE TITLE
[Quest] [Hyjal] Good News… and Bad News - not offered

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2239]
Quest [Good News... and Bad News](https://www.wowhead.com/quest=29066/good-news-and-bad-news) should be autoaccepted after handing in [Black Heart of Flame](https://www.wowhead.com/quest=25428/black-heart-of-flame). Instead, the next quest in the chain after Good News… and Bad News is available.
Also handing in the Black Heart of Flame does not trigger the completion event, instead Tyrus becomes "blue" npc. And instead of lamps that channel the chains to Tyrus, there are bunnies that disappear after completion.
https://www.wowhead.com/quest=29066/good-news-and-bad-news#comments:id=1427141
1:20 https://www.youtube.com/watch?v=bK1HjCDM_Cc

**Comment by UltraNix** [comment]
Fixed.
