### ISSUE TITLE
[Quest] The Final Ritual

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2242]
[The Final Ritual](https://www.wowhead.com/quest=26170/the-final-ritual)

1. [Loramus](https://www.wowhead.com/npc=7783/loramus-thalipedes) disappears on accepting this quest.
2. [Kasim Sharim](https://www.wowhead.com/npc=42298/kasim-sharim) has no chat option to trigger completion of this quest.
3. Quest is set as complete right from the start.

https://www.youtube.com/watch?v=vvqW52bH1eo
https://www.youtube.com/watch?v=vEk4UWIglD4

**Comment by UltraNix** [comment]
Fixed.
