### ISSUE TITLE
Moved from Discord [stonecore first boss]

### ISSUE THREAD

**Issue by Xstep-Whitemane** [gamefreedomgit/Maelstrom#2243]
**Description:**
 The first boss in [The Stonecore] Corborus falls through map when using burrow

https://ibb.co/gy9BYpB

"This is the correct XYZ coords for the boss"

https://ibb.co/ZRsP6Jx
"This is when he uses burrow, he falls to Z axis 00000

**Comment by Afgann** [comment]
fixed
