### ISSUE TITLE
[Spell] Bad Manner

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#2244]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can't use bad manner on a scatter or even a freezing trap

**How to reproduce:**
use scatter shot and spam Bad manner, u will see u cant use if scatter is active
https://youtu.be/2RNG4WKaJns

**How it should work:**
https://youtu.be/J9kNEWD6egg?t=201

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=90337

**Comment by MullichWhitemane** [comment]
Confirmed, doesn't work on Scatter Shot (disorient), Wyvern Sting (sleep) and Freezing Trap (freeze). It works with Intimidation (stun).

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/724feb7f-7634-4a40-a4c4-202f9ee88b53)
Works okay.
