### ISSUE TITLE
[Moved from Discord] Hunter trap activation delay

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2248]
Kenni
OP
 — Today at 14:09
Hunter's traps has random timers for when they proc, sometimes its 1seconds, sometimes its 2.5 seconds

It should always be 1 second

Use scatter shot and then trap launcher on the target with freezing trap and you can see. 🙂

-  Patch notes from 3.0.2 shows trap activation time was reduced to 1 second,  yet on our server it flucuates between 1.6 and 2.8 seconds 

https://us.forums.blizzard.com/en/wow/t/bug-hunter-trap-arm-times/1409454
https://wowwiki-archive.fandom.com/wiki/Freezing_Trap

**Comment by Afgann** [comment]
fixed
