### ISSUE TITLE
Misplaced NPC Amakkar  ID 47021, Gnarlpipe corruption totem ID 49598, Highland Elk ID 46970, NPC Provisioner eda 46271

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2249]
**How to reproduce:**
For some reason Amakkar ID 47021 can be found in Elwynn forest also he is blue like he summoned but you can also find him with list C command which means he is a perm spawn
![image](https://user-images.githubusercontent.com/36106057/221427292-a50a9786-1b05-4a45-94b3-7379f8b9b345.png)

Gnarlpipe corruption totem should not be able to follow players around. its a totem it should not have movements.
![image](https://user-images.githubusercontent.com/36106057/221427432-563ca8ea-4321-480b-a5ea-b7951058c3fd.png)

[Highland Elk](https://cata-twinhead.twinstar.cz/?npc=46970#abilities) knockdown looks like doesnt have cooldown 

NPC Provisioner eda vendor is not working nor its inkeep to make that place your new home
![image](https://user-images.githubusercontent.com/36106057/222950287-5558c46e-cd01-4032-b83b-5d9b71e0384e.png)

**How it should work:**
He should not be there.
https://wowpedia.fandom.com/wiki/Amakkar
and totem should not follow players

**Comment by Afgann** [comment]
fixed
