### ISSUE TITLE
[Spell] Death and Decay not ticking correct amount of times + AMS bug

### ISSUE THREAD

**Issue by testdk123** [gamefreedomgit/Maelstrom#2251]
**Description:**
Death and Decay isn't ticking for the correct amount of times and if you cast it while under the effect of AMS it renders the spell useless as everyone will appear "immune" to it.

**How to reproduce:**
1. Cast AMS.
2. Cast Death and Decay on any amount of targets.

**How it should work:**

### Ticks bug:
Regarding the amount of ticks, it should tick for 11 times instead of 10. This happens because the spell duration is 10 seconds, and it should tick immediately upon cast (0 seconds) and then once per second for the next 10 seconds, meaning it'll tick for one last time at the 10th second.
**Proof:** 
https://youtu.be/wwG2OvuhLfY?t=1241
You can see at ~20:43 he'll cast AMS on the chains, and if you count it carefully you'll notice it ticks for the intended 11 times.
Alternatively, you can check warcraftlogs both from classic WotLK and from 5.4 MoP, you'll see the spell has always worked this way (still does to this day even).

### AMS bug
https://wowpedia.fandom.com/wiki/Patch_4.3.0
Happened on retail for a while as well, was eventually fixed in 4.3.

**Database links:**
https://www.wowhead.com/spell=43265/death-and-decay#comments
You can even see the comments referring the amount of ticks there.

**Comment by MullichWhitemane** [comment]
Both bugs confirmed.
DnD only having 10 damage iterations (11th missing at the 0 second tick):
![DND](https://user-images.githubusercontent.com/121984461/221433423-b804b8da-c691-4359-833b-f9f9653108c2.PNG)

Anti-Magic Shell turning Death and Decay useless: https://www.youtube.com/watch?v=57W_4wSHc8o

**Comment by Afgann** [comment]
fixed

**Comment by MullichWhitemane** [comment]
@testdk123 Fixed with this https://discord.com/channels/1040715551531618365/1045188444617461870/1085603409635332146 now.
![dnd fixed](https://user-images.githubusercontent.com/121984461/225502381-f9e2a011-1d65-4783-b627-148c220a2fd0.PNG)
