### ISSUE TITLE
[Spell] Raise Dead: Death Knight's Ghoul not benefitting from Orc pet racial + base damage values 

### ISSUE THREAD

**Issue by testdk123** [gamefreedomgit/Maelstrom#2254]
**EDIT:** Adding to the original issue, I've found out that the ghoul is not currently benefitting from the 5% increased pet damage from Orc's racial. From my testing it seems to be a DK specific issue, although I can't be sure if it's related to the racial swap ability (my current DK is not an Orc).

**Description:**
The ghoul summoned by Raise Dead seems to be doing noticeably less damage than it should. A brief glance at the pet panel suggests that the base min-max damage values aren't correct, although I'm not sure about the base STR values or even the player:pet Strength conversion formula.

**How to reproduce:**
1. Summon the pet.
2. Notice how the baseline swing damage only has a variance of 43 damage (before multipliers such as Armor DR or Shadow Infusion stacks). 

**How it should work:**
Yeah this is kinda iffy. Proving that the values are off is easy just by looking at any retail video and noticing the min-max pet swing variance. 
Arriving at the actual values though is a different story. 

I've looked around and the conclusions I've come to are the following:
1. Ghoul should have base 476 Strength and -20AP, meaning 932AP before player inheritance. 
2. The actual Strength inheritance formula should actually be close to 1.01 x Player Strength without Glyph of Raise dead. With glyph it should be ~1.4354. As to why this is, I just don't know, perhaps some double dipping on a multiplier. 
3. Weapon damage is apparently calculated with (Ghoul AP)/16.66 x 2, added to a minimum base damage of 622.43, and a maximum of 933.64.

This information came mostly from reading simcraft discussions which in turn led me to a twinstar bug report.
https://code.google.com/archive/p/simulationcraft/issues/767
https://cata-twinhead.twinstar.cz/?issue=779#comments:id=139077
Unfortunately the google sheets link seems to have expired since. 

The x1.01 and x1.43 multipliers are also mentioned in the EJ thread for unholy: http://web.archive.org/web/20120508010219/http://elitistjerks.com/f72/t125292-unholy_dps_my_friend_misery_4_3_0_a/#Stat_Weights

> While our Ghoul is described as inheriting 100%/140%(glyphed) strength from the player, data collection has shown a distinct variation. In observation, an unglyphed Ghoul appears to have closer to ~101% strength and a glyphed Ghoul has closer to ~143%. Linear regressions performed with samples of player data place the Ghoul's base AP at ~931.

### Video example
Going to use the Preach video once more:
In this video we can clearly see his Strength value as 8513 with Flask, Well Fed and Horn of Winter. 
https://youtu.be/Tf1LiwVwfTE?t=1001
At around 16:40 his ghoul is attacking the target dummy without any Shadow Infusion stacks, same buffs as the beginning of the video except no Well Fed. 
8513-90x1.25 = 8400 as the new Strength value (this was 4.2 so Unholy might is only a 20% Strength buff, the other 5% is from plate spec).
Assuming the values previously presented this'd result in 8513x1.4354x2+932 = **25047** Ghoul AP.
This'd result in a minimum swing value of 25047/16.66x2+622.43 = **3629** and a Maximum of **3940**.
Taking into account the Orc racial and the damage reduction from the heroic raiding dummy you'd have
3629x1.05x0.685 = **2610** minimum dummy damage
3940x1.05x0.685 = **2834** maximum dummy damage
This more or less aligns with the values present in the video. From 16:10 to 16:42 the Ghoul lands more than 20 attacks, with 2611 as the minimum value and 2831 as the maximum. I doubt the values I arrived to are COMPLETELY right, especially considering my approximations aren't too exact and I don't recall what's the actual armor DR value, just know it's around 31.4%ish. 

We can also check the values with Dark Transformation and Unholy Strength active, later in the video.
https://youtu.be/Tf1LiwVwfTE?t=1092
8400/1.25x1.4 = 9408 new Strength value with Unholy Strength.
9408*1.4354*2+932 = 27940 new Pet AP value.
Minimum swing: 27940/16.66x2+622.43 = 3977
Maximum swing: 27940 /16.66x2+933.64 = 4288
Taking into account Orc racial, Dark Transformation and armor reduction:
Minimum dummy damage: 3977x1.6x1.05x0.685 = 4577
Maximum dummy damage: 4288x1.6x1.05x0.685 = 4935
During the video we actually see a 4977 swing even after the heart of rage proc, suggesting we lost damage somewhere in there, but again I'll blame the approximations. Overall the values seem pretty close to the calculated either way.

Might try doing the same with another video some other time, but I hope this is enough to prove that something is off.

**Comment by MullichWhitemane** [comment]
The only way to prove the following:

1. Ghoul should have base 476 Strength and -20AP, meaning 932AP before player inheritance.
2. The actual Strength inheritance formula should actually be close to 1.01 x Player Strength without Glyph of Raise dead. With glyph it should be ~1.4354. As to why this is, I just don't know, perhaps some double dipping on a multiplier.
3. Weapon damage is apparently calculated with (Ghoul AP)/16.66 x 2, added to a minimum base damage of 622.43, and a maximum of 933.64.

Is to run a database check. The sources are legitimate, but in my testing, Ghoul's damage didn't have big enough variance for me to come to the conclusion that it is possibly bugged - a quality check is always appreciated however.

**Comment by testdk123** [comment]
> Ghoul's damage didn't have big enough variance for me to come to the conclusion that it is possibly bugged

Wait maybe I'm misinterpreting what you said, but that's exactly the issue in the server. Variance right now is WAY too low, as I said it's 43 damage not taking into account the possible multipliers (Shadow Infusion/Dark Transformation and Armor most importantly), while you can clearly see in any retail video that variance should be in the hundreds even against high-armored bosses without any Shadow Infusion stacks.

https://youtu.be/bQKxSBrudCA?t=122
Another example from a video that was posted on discord; you can see from 2:02 to 4:38 (before he presses Horn of Winter) the pet is attacking a level 60 dummy without any SI stacks. Lowest non-crit hit was 3026, highest was 3277, that's a 251 damage difference. If I were to attempt the same test in this server I'd have a ~38 damage difference at most lol.

**Comment by pro100klass** [comment]
I personally did this topic on another project https://forum.wowcircle.com/showthread.php?t=952891
+ in my topic there are screenshots from the official server with the characteristics of the pet

**Comment by pro100klass** [comment]
![WoWScrnShot_011512_225120](https://user-images.githubusercontent.com/127721279/224625247-6619dca7-e6dd-42eb-b970-f92bb4c553b5.jpg)
![WoWScrnShot_011512_225129](https://user-images.githubusercontent.com/127721279/224625251-f9d43155-7b7f-45c0-8371-8d0744ca5860.jpg)

**Comment by pro100klass** [comment]
these screenshots are taken from here

**Comment by pro100klass** [comment]
https://forum.wowcircle.com/showthread.php?t=952891

**Comment by pro100klass** [comment]
https://forum.wowcircle.com/showthread.php?t=6739

**Comment by testdk123** [comment]
@pro100klass Great job my friend, this pretty much confirms the formulas presented in the earlier post.
@MullichWhitemane Please take a look whenever possible.

Stat inheritance: 
- Player has 6837 Strength
- Ghoul has **20560** AP
- 6837 * 1.4354 = 9813.83
- 9813.83 * 2 + 932 (Base Ghoul AP) = **20559.66**

Swing calculations + variance:
- Ghoul has 20560 AP
- Min. swing damage of 3089
- Max. swing damage of 3401
- 20560/16.66 * 2 = 2468.19
- 2468.19 - 3089 = **-620.81**
- 2468.19 - 3401 = **-932.81**

Currently on the server the swing damage seems to be calculated by AP/14 * 2 + 63~106 (min-max).
![ghoul](https://i.imgur.com/4L7kt2d.jpg)
Funnily enough, this'd actually be a positive bug for AP values above 30382.6, meaning player strength above 10258... which is not too realistic with T11 gear outside of trinket procs. The lower the AP value in question, the higher impact this bug has, meaning we're at the stage where it affects players the most.

As for the stat inheritance... it actually seems to be working fine. Apparently it's already using the 1.4354 multiplier actually, or at least something close to it. Sometimes the values seem off somehow, think there's some weird calculations going on with the impact of external strength buffs being inherited onto the pet. Might be an universal issue with pets.

Additionally, I'm not sure if the Orc pet command racial is actually working for Unholy DKs. Unfortunately the option to skip DK starting zone was removed from the server/PTR, but not only do the visual values in the pet panel not reflect the 5% damage increase, as they don't seem to translate into real combat numbers upon testing it for a bit with a dummy (tested this by calculating the armor DR with a normalised wdps 2hander in the PTR).

**Comment by pro100klass** [comment]
[testdk123](https://github.com/testdk123) make a new report about https://www.wowhead.com/wotlk/ru/spell=53365/%D0%BD%D0%B5%D1%87%D0%B5%D1%81%D1%82%D0%B8%D0%B2%D0%B0%D1%8F-%D1%81%D0%B8%D0%BB%D0%B0#sounds healing does not have a critical effect
https://forum.wowcircle.com/showthread.php?t=1103440

**Comment by pro100klass** [comment]
> [testdk123](https://github.com/testdk123) make a new report about https://www.wowhead.com/wotlk/ru/spell=53365/%D0%BD%D0%B5%D1%87%D0%B5%D1%81%D1%82%D0%B8%D0%B2%D0%B0%D1%8F-%D1%81%D0%B8%D0%BB%D0%B0#sounds healing does not have a critical effect https://forum.wowcircle.com/showthread.php?t=1103440&styleid=-1

**Comment by UltraNix** [comment]
Will be okay with the next update.

**Comment by testdk123** [comment]
@UltraNix It's better, but there's something funky going on still. Maybe the Orc racial is only being partly applied to some portion of the damage? 

Here's pet damage without any buffs:
![pet1](https://user-images.githubusercontent.com/126105309/228844405-4016d56b-a314-493f-8bfc-8fffedee7d42.jpg)

- 16280 AP
- Should be 16280/16.66 * 2 =  **1954.38** damage from the AP coeff
- 1954.38 + 622.43 = 2576.81 Min swing / 1954.38 + 933.64 = 2888 Max swing
- Including Orc pet racial that'd get us 2576.81 * 1.05 = **2705.65 Min** / 2888 * 1.05 = **3032.42 Max**

Instead we're getting 2601 Min and 2916 Max, values that don't match either the result with or without Orc pet racial.

And here's with Horn of Winter:
![pet2](https://user-images.githubusercontent.com/126105309/228844508-a7cfa01d-eb91-467c-800a-02e7c957ebc1.jpg)

- 18136 AP
- Should be 18136/16.66 *2 = **2177.19** damage from the AP coeff
- 2177.19 + 622.43 = 2799.62 Min swing / 2177.19 + 933.64 = 3110.83 Max Swing
- Including Orc pet racial 2799.62 * 1.05 = **2939.60 Min** / 3110.83 * 1.05 = **3266.37 Max**

Instead we're getting 2846 Min and 3161 Max, which again don't match either value.

**Comment by testdk123** [comment]
Could it be... that the base damage is getting the 5% orc racial multiplier, but the AP coeff damage is only getting 0.5% instead of 5%?

**Comment by UltraNix** [comment]
You pet's attack speed is 1.48, not 2.
`16280/16.66 * 1.48 = 1 446 damage from the AP coeff`

**Comment by UltraNix** [comment]
Of course it does matter.
` ``float base_value  = GetModifierValue(unitMod, BASE_VALUE) + GetTotalAttackPowerValue(attType)/ apMultiplier * att_speed + bonusDamage;```
`att_speed` is attack speed

**Comment by UltraNix** [comment]
You know that Attack Power increases damage PER SECOND? It makes no less damage (overall), but faster.

**Comment by testdk123** [comment]
I'm confused, what exactly are we discussing here? We're not talking about DPS calculations, we're talking about Swing damage calculations. DPS will indeed be calculated via (Swing damage / attack speed), but that's a completely different matter. 

None of the calculations posted in this thread make sense if you assume a dynamic attack speed value.

**Comment by testdk123** [comment]
The 16.6 modifier is fine, current pet damage is -fine- apart from the Orc Racial not being applied correctly. Or is that somehow related to the 16.6 modifier?

**Comment by UltraNix** [comment]
Now it's not.
See what client shows:
![image](https://user-images.githubusercontent.com/80540499/228881477-c6e14d31-41d2-466e-8af5-a8f0c86c5643.png)
2100 / 14 = 150.7. 14 was okay.

From that above SS:
20560 / 14 = 1 468 --> bonus damage from AP per second
1468 * 1.7 = 2 495 --> bonus damage per swing
2495 + 622 (base min damage) = 3117
2495 + 933 (base max damage) = 3428

**Comment by testdk123** [comment]
No, I have no idea how you're reached this conclusion. 
We can just compare it to how player melee hits behave; your swing damage is calculated by (wpn damage + AP/14 * {weapon speed}). 

![test](https://user-images.githubusercontent.com/126105309/228889536-d776c354-23d8-41dd-b701-4fcad0f68fa8.jpg)

Just look at this, with Zinrokh equipped I have (1894 + 13205/14 * 3.8) = 5479 Min damage and (2842 + 13205/14 * 3.8) = 6427 Max damage. These calculations only make sense if you assume the base weapon speed value of Zinrokh at 3.8, before any haste modifications.

Same thing is applied for the pet, just at a weird AP coefficient (nobody actually knows why, it's apparently very specific to DK's pet). The base weapon speed (melee) is 2, so the calculation will use that for the AP coefficient calculation. 

Refer to the calculations made using Preach's video, and again the actual retail screenshot. None of the maths make sense unless you assume these values.

**Comment by UltraNix** [comment]
@testdk123 Your ghoul is 85 lvl?

**Comment by UltraNix** [comment]
Orc Command works okay, but I will make some adjustment to basic damage.

**Comment by testdk123** [comment]
As of the last update; base damage looks fine but the orc racial is STILL not being applied.
Thus, we've lost damage with the update.

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/231388556-409e7d36-6a0b-46d2-bc97-ebe3a561aa21.png)
2130 / 16.6 = 128.313
128.313 * 2 = 256.62
Min dmg = 622.43 + 256.62 = 879.065 * 1.05 (Command) ~ 923
Max dmg = 933.64 + 256.62 = 1190.266 * 1.05 (Command) ~ 1250
Everything works okay here.

**Comment by testdk123** [comment]
@UltraNix 
![pet](https://user-images.githubusercontent.com/126105309/231466364-dd334ffe-70a0-4b90-aec6-08d66f8db75e.jpg)

Not working for me on the live server at least. Could it be related to racial swap? My character is not an orc.

**Comment by UltraNix** [comment]
@testdk123 Might be the case - I will test it.

**Comment by UltraNix** [comment]
Fixed.
