### ISSUE TITLE
[Hyjal] [Zone] [Phasing] Shrine of Aviana and Rim of the World - empty

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2260]
The zones Shrine of Aviana and Rim of the World are empty.
No active quests at the moment.
All quests completed up to (excluding) [Return to Aviana](https://www.wowhead.com/quest=25832/return-to-aviana) at Aviana branch and [The Bears Up There](https://www.wowhead.com/quest=25462/the-bears-up-there) at Goldrinn and onwards branch.
The zones are empty no matter if I pick up Return to Aviana or not.

UPDATE:
Same issue with somewhat fresho toon who goes to the zones for the 1st time, with quest [Wings Over Mount Hyjal](https://www.wowhead.com/quest=25985/wings-over-mount-hyjal) active. The zones are empty and remain empty if I abandon the quest. On this toon The Shrine of Goldrinn was completed an currently is on [The Fires of Mount Hyjal](https://www.wowhead.com/quest=25630/the-fires-of-mount-hyjal).

**Comment by Greywolf59** [comment]
UPDATE: After completing [Aessina's Miracle](https://www.wowhead.com/quest=25372/aessinas-miracle), these zones are fine again

**Comment by Afgann** [comment]
fixed
