### ISSUE TITLE
Mass Ressurection

### ISSUE THREAD

**Issue by Mietla122** [gamefreedomgit/Maelstrom#2263]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
guild perk mass ressurection is not working at all 

**How to reproduce:**

**How it should work:**

**Database links:**
https://wowpedia.fandom.com/wiki/Mass_Resurrection_(guild_perk)

**Comment by MullichWhitemane** [comment]
Marking this as low prio as Mass Ress won't be a thing for a while.

**Comment by UltraNix** [comment]
Fixed.
