### ISSUE TITLE
[Hunter][Spell][Talent] Lock and Load & Explosive Shot Visual GCD

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#2264]
Bug: When Survival Hunter uses Explosive Shot while having the Lock and Load talent activated (Your next two Explosive Shots trigger no cooldown/have no focus) the visual effect does not update
What needs to happen: The Explosive Shot icon should update properly when Lock and Load has been procced.

https://user-images.githubusercontent.com/67768754/222075824-154efd21-3d99-4c02-8121-9553f3c3f4e6.mp4

**Comment by UltraNixx** [comment]
@Loken-coolguy Could you make another test, but with "Everything" tab of combat log on top (and with more entries)?

**Comment by UltraNix** [comment]
No further info - closing.
