### ISSUE TITLE
Sap on mage invisibility

### ISSUE THREAD

**Issue by Wees369** [gamefreedomgit/Maelstrom#2266]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When a rogue sap a mage, and the mage has used invisibility, there is a 3 second delay before he makes him invisible, and during those 3 seconds, even if the rogue sap, the mage will be able to make invisible (the buff does not remove).

**How to reproduce:**
Used the sap during the 3 second delay before invisibility

**How it should work:**
https://youtu.be/pI46TI-Ryng?t=322

**Database links:**
https://www.wowhead.com/spell=66/invisibility

**Comment by Afgann** [comment]
fixed
