### ISSUE TITLE
List of Cross-faction RDF Dungeon Quests/NPCs (Level 15-60 only)

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2272]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The following dungeons contain faction-specific when in level 15-60 dungeons and may cause problems for cross-faction dungeon groups:
Ragefire Chasm
Deadmines
Shadowfang Keep
Blackfathom Deeps
Stockades
Scarlet Monastery (Graveyard, Library, Armory, Cathedral)
Uldaman
Blackrock Depths

**Possible fix ideas?** _probably scuffed because I have no idea how any of it works_
-Make everyone see only one faction's quest givers, but make all of them neutral and have all quests available.
-Have no NPCs of any faction and auto accept the dungeon's available quests.
-Have both factions' quest givers visible and make them all neutral

**Ragefire Chasm:**
*No Alliance NPCs*
*Horde*
Orgrimmar Defender (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44223
Bovaal Whitehorn (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44216
[Elemental Tampering] (quest) - https://cata-twinhead.twinstar.cz/?quest=26862
Stone Guard Kurjack (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44217
[Repel the Invasion] (quest) - https://cata-twinhead.twinstar.cz/?quest=26856
[Taragaman the Hungerer] (quest **MISSING**) - https://cata-twinhead.twinstar.cz/?quest=26858

**Deadmines:**
*Alliance NPCs*
Stormwind Defender (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=50595
Crime Scene Alarm-o-Bot (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46613
Stormwind Investigator (NPCs) - https://cata-twinhead.twinstar.cz/?npc=46614
Quartermaster Lewis (vendor) - https://cata-twinhead.twinstar.cz/?npc=491
Lieutenant Horatio Laine (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46612
[The Foreman] (quest) - https://cata-twinhead.twinstar.cz/?quest=27756
*Horde NPCs*
Shattered Hand Assassin (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46890
Slinky Sharpshiv (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46906
[Traitors!!!] (quest) - https://cata-twinhead.twinstar.cz/?quest=27844
Kagtha (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46889
[Only the Beginning] (quest) - https://cata-twinhead.twinstar.cz/?quest=27842
[Good Intentions... Poor Execution] (quest) - https://cata-twinhead.twinstar.cz/?quest=27848
[The Defias Kingpin] (quest **Not given after completing Good Intentions... Poor Execution** - https://cata-twinhead.twinstar.cz/?quest=27850
Miss Mayhem (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46902
[Not Quite There] (quest) - https://cata-twinhead.twinstar.cz/?quest=27847

**Shadowfang Keep:**
*Alliance NPCs*
Bloodfang Berserker (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=47027
Packleader Ivar Bloodfang (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=47006
[Sniffing Them Out] (quest) - https://cata-twinhead.twinstar.cz/?quest=27917
[Armored to the Teeth] (quest) - https://cata-twinhead.twinstar.cz/?quest=27920
[Fighting Tooth and Claw] (quest) - https://cata-twinhead.twinstar.cz/?quest=27921
[Fury of the Pack] (quest) - https://cata-twinhead.twinstar.cz/?quest=27968
*Horde NPCs*
Veteran Forsaken Trooper (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=47030
Forsaken Blightspreader (guard NPCs) - 
https://cata-twinhead.twinstar.cz/?npc=45374
https://cata-twinhead.twinstar.cz/?npc=45602
Deathstalker Commander Belmont (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=47293
[This Land is Our Land] (quest) - https://cata-twinhead.twinstar.cz/?quest=27974
[Plague... Plague Everywhere!] (quest) - https://cata-twinhead.twinstar.cz/?quest=27988
[Orders Are For the Living] (quest) - https://cata-twinhead.twinstar.cz/?quest=27996
[Sweet, Merciless Revenge] (quest) - https://cata-twinhead.twinstar.cz/?quest=27998

**Stockades:**
*Alliance NPCs*
Stockade Rifleman (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46406
Injured Stockade Rifleman (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46408
Stockade Guard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46405
Injured Stockade Guard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=46407
Rifle Commander Coe (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46417
[The Gold Ol' Switcheroo] (quest) - https://cata-twinhead.twinstar.cz/?quest=27733
Mortimer Molock (NPC) - https://cata-twinhead.twinstar.cz/?npc=46482
Warden Thelwater (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46409
[The Gnoll King] (quest) - https://cata-twinhead.twinstar.cz/?quest=27739
Nurse Lillian (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46410
[By Fire Be Saved!] (quest) - https://cata-twinhead.twinstar.cz/?quest=27737
*No Horde NPCs*

**Blackfathom Deeps:**
*Alliance NPCs*
Sentinel-trainee Issara (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=33261
[Knowledge in the Deeps] (quest) - https://cata-twinhead.twinstar.cz/?quest=26885
Sentinel Aluwyn (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=33260
[Twilight Falls] (quest) - https://cata-twinhead.twinstar.cz/?quest=26883
Relwyn Shadestar (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=33258
[Researching the Corruption] (quest) - https://cata-twinhead.twinstar.cz/?quest=26884
Ashelan Northwood (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=33256
[In Search of Thaelrid] - https://cata-twinhead.twinstar.cz/?quest=26881
Scout Thaelrid (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=4787
[Blackfathom Villainy] (quest) - https://cata-twinhead.twinstar.cz/?quest=26882
*Horde NPCs*
Zeya (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44375
[Deep in the Deeps] (quest) - https://cata-twinhead.twinstar.cz/?quest=26892
Je'neu Sancrea (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=12736
[Nightmare of the Deeps] (quest) - https://cata-twinhead.twinstar.cz/?quest=26888
Flaming Eradicator (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44387
[The Enemy of My Enemy] (quest) - https://cata-twinhead.twinstar.cz/?quest=26899

**Scarlet Monastery:**
*Alliance NPCs*
     -Graveyard
Scarlet Renegade (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44736
Joseph the Awakened (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44728
[The Dark Side of the Light] (quest) - https://cata-twinhead.twinstar.cz/?quest=26972
     -Library
Scarlet Renegade (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44739
Joseph the Awakened (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44738
[The Only True Path] (quest) - https://cata-twinhead.twinstar.cz/?quest=26973
     -Armory
Scarlet Renegade (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44742
Joseph the Crazed (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44741
[The False Champion] (quest) - https://cata-twinhead.twinstar.cz/?quest=26974
     -Cathedral
Scarlet Renegade (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44751
Joseph the Insane (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44746
[Battle for the Scarlet Monastery] (quest) - https://cata-twinhead.twinstar.cz/?quest=26976
*Horde NPCs*
     -Graveyard
Forsaken Royal Dreadguard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44655
Dark Ranger Velonara (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44637
[The Dark Side of the Light] (quest) - https://cata-twinhead.twinstar.cz/?quest=26950
     -Library
Forsaken Royal Dreadguard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44661
Dark Ranger Velonara (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44660
[Stripping Their Defenses] (quest) - https://cata-twinhead.twinstar.cz/?quest=26959
     -Armory
Forsaken Royal Dreadguard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44691
Forsaken Flesh Ripper (guard NPC) - https://cata-twinhead.twinstar.cz/?npc=44693
Dark Ranger Velonara (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44690
[Stripping Their Offense] - https://cata-twinhead.twinstar.cz/?quest=26962
     -Cathedral
Forsaken Royal Dreadguard (guard NPCs) - https://cata-twinhead.twinstar.cz/?npc=44707
Forsaken Flesh Ripper (guard NPC) - https://cata-twinhead.twinstar.cz/?npc=44708
Dark Ranger Velonara (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44706
[Battle for the Scarlet Monastery] (quest) - https://cata-twinhead.twinstar.cz/?quest=26967
Dominic (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44805
[Right Under Their Noses] (quest) - https://cata-twinhead.twinstar.cz/?quest=26996

Uldaman:
*Alliance NPCs*
Explorer's League Digger (NPCs) - https://cata-twinhead.twinstar.cz/?npc=46232
Kand Sandseeker (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46247
[It's What's Inside That Counts] (quest) - https://cata-twinhead.twinstar.cz/?quest=27673
Lead Prospector Durdin (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46234
[The Chamber of Khaz'mul] (quest) - https://cata-twinhead.twinstar.cz/?quest=27672
Olga Runesworn (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46233
[Behind Closed Doors] (quest) - https://cata-twinhead.twinstar.cz/?quest=27676
*Horde NPCs*
Reliquary Digger (NPCs) - https://cata-twinhead.twinstar.cz/?npc=46231
Lidia Sunglow (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46235
[Behind Closed Doors] (quest) - https://cata-twinhead.twinstar.cz/?quest=27681
High Examiner Tae'thelan Bloodwatcher (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46236
[The Chamber of Khaz'mul] (quest) - https://cata-twinhead.twinstar.cz/?quest=27679
Aoren Sunglow (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=46241
[We Require More Minerals] (quest) - https://cata-twinhead.twinstar.cz/?quest=27682

Blackrock Depths:
*Alliance NPCs*
Jalinda Sprig (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45892
[Into the Prison] (quest) - https://cata-twinhead.twinstar.cz/?quest=27565
Morgan (NPC) - https://cata-twinhead.twinstar.cz/?npc=45903
Oralius (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45891
[Infiltrating Shadowforge City] (quest) - https://cata-twinhead.twinstar.cz/?quest=27568
Kevin Dawson (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45898
[Twilight?! No!] (quest) - https://cata-twinhead.twinstar.cz/?quest=27567
Prospector Seymour (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45894
[Dark Iron Tacticians] (quest) - https://cata-twinhead.twinstar.cz/?quest=27569
Mayara Brightwing (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45888
[The Grim Guzzler] (quest) - https://cata-twinhead.twinstar.cz/?quest=27571
Mountaineer Orfus (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45899
[The Dark Iron Pact] (quest) - https://cata-twinhead.twinstar.cz/?quest=27573
Marshal Maxwell (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45890
[Morgan's Fruition] (quest) - https://cata-twinhead.twinstar.cz/?quest=27578
*Horde NPCs*
High Executioner Nuzrak (NPC) - https://cata-twinhead.twinstar.cz/?npc=45823
Tha'trak Proudtusk (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45821
Galamav the Marksman (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45839
[Infiltrating Shadowforge City] (quest) - https://cata-twinhead.twinstar.cz/?quest=27582
Lexlort (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45818
[Twilight?! No!] (quest) - https://cata-twinhead.twinstar.cz/?quest=27581
Razal'blade (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45820
[The 109th Division] (quest) - https://cata-twinhead.twinstar.cz/?quest=27585
Heirophant Theodora Mulvania (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45817
[The Grim Guzzler] (quest) - https://cata-twinhead.twinstar.cz/?quest=27589
Thunderheart (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45824
[The Dark Iron Pact] (quest) - https://cata-twinhead.twinstar.cz/?quest=27591
Warlord Goretooth (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=45840
[Rebirth of the K.E.F.] (quest) - https://cata-twinhead.twinstar.cz/?quest=27593

**Comment by UltraNixx** [comment]
Done.

**Comment by StarterEdition** [comment]
This is not a solution since some players dont have their quests available, I recommend make available only the quests in the side of the leader of the group, in the way every group can do the quest depending in who is the leader of that run.
