### ISSUE TITLE
(Quest) The G-Team - Alliance Dungeon Quest

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The first quest in the series requires either [Home Sweet Gnome] or [Exploring Gnomeregan] before entering the dungeon. The prerequisites should be skippable and Alliance players should be able to accept [The G-Team] as soon as they enter the dungeon without the need for either prerequisite.

**Database links:**
Home Sweet Gnome (quest) - https://cata-twinhead.twinstar.cz/?quest=26943
Exploring Gnomeregan (quest) - https://cata-twinhead.twinstar.cz/?quest=26944
The G-Team (quest) - https://cata-twinhead.twinstar.cz/?quest=26939

**Comment by alexspew** [comment]
Fixed, you should now be able to get G-Team quest while inside Gnomeregan.
