### ISSUE TITLE
(NPC) Koristrasza

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2274]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Koristrasza should be to the right as soon as players enter Razorfen Downs., but she is currently missing. She should be able to give the players three dungeon quests; [Cure the Scourge], [Partners in Crime], and [The Coldbringer], as well as turn in a faction specific quest [Looming Threat].

**Database links:**
Koristrasza (quest NPC) - https://cata-twinhead.twinstar.cz/?npc=44837#ends
[Looming Threat] (Horde Quest) - https://cata-twinhead.twinstar.cz/?quest=27062
[Looming Threat] (Alliance Quest) - https://cata-twinhead.twinstar.cz/?quest=27063
[Cure the Scourge] (quest) - https://cata-twinhead.twinstar.cz/?quest=27029
[Partners in Crime] (quest) - https://cata-twinhead.twinstar.cz/?quest=27024
[The Coldbringer] (quest) - https://cata-twinhead.twinstar.cz/?quest=27009

**Comment by Greywolf59** [comment]
Already reported :) https://github.com/gamefreedomgit/Maelstrom/issues/2058
