### ISSUE TITLE
You cant leave arena

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2276]
leave arena doesnt work

**Comment by SimonBpvp** [comment]
when youre in combat

**Comment by SimonBpvp** [comment]
and sometimes if you queue to fast your team mate cant enter arena

**Comment by MullichWhitemane** [comment]
I couldn't recreate any of this, could you please try to record a video of your PoV?

**Comment by SimonBpvp** [comment]
There u go mate
https://www.youtube.com/watch?v=Ww8mQPlPwwI&feature=youtu.be

**Comment by SimonBpvp** [comment]
bump

**Comment by UltraNix** [comment]
Tested - cannot reproduce it.
