### ISSUE TITLE
Impacted Fire Blasts not stunning when using it on Focus Targets

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2277]
Original report edited and redundant comments deleted by @MullichWhitemane 

Currently, if you try to use an Impact procced Fire Blast on a Focus Target, the stun effect will never occur on the Focus Target, but instead, will occur on whoever you are normally targeting (or will not occur at all if you have no target).
https://www.youtube.com/watch?v=BVM31JNuSK0

**Comment by MullichWhitemane** [comment]
What does this mean?

**Comment by SimonBpvp** [comment]
get a target, use your fireblast when u have impact proc. It stuns the target.
Now get a focus, hit the focus with fireblast when u have impact proc. It doesn't stun them.

**Comment by UltraNix** [comment]
Fixed.
