### ISSUE TITLE
wargame bug

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2279]
you cant wargame sometimes, it just says Wargame request failed

**Comment by MullichWhitemane** [comment]
Please explain how we can reproduce this.

**Comment by SimonBpvp** [comment]
join a group with 2 people. do '/wg 3v3' another guy with 2 people in his group

**Comment by UltraNix** [comment]
You can't queue 3v3 with only 2 party members.

**Comment by UltraNix** [comment]
Incorrect command. Just use UI.
It's clientside error.
