### ISSUE TITLE
[QUEST] no quest available after Don't go into The light!

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2282]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
after you escape kezan. there should be https://www.wowhead.com/quest=14001/goblin-escape-pods

**How to reproduce:**
![image](https://user-images.githubusercontent.com/99285606/222335210-7ac71248-23f8-42a7-89fd-20e930fc8f30.png)

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=14239/dont-go-into-the-light
https://www.wowhead.com/quest=14001/goblin-escape-pods

**Comment by DeadRatsYT** [comment]
After leaving to shore and comeback quest appeared.

**Comment by UltraNix** [comment]
Fixed.
