### ISSUE TITLE
[Quest] (minor) To the Cliffs

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2284]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When taking this quests npc should spawn a panter that rides you towards next quest. 
Can walk yea, but what about poor missing cat... 
![image](https://user-images.githubusercontent.com/99285606/222347004-2cdd754b-0537-4e55-b495-294bb3a7a600.png)

**How to reproduce:**

**How it should work:**
![image](https://user-images.githubusercontent.com/99285606/222347033-e0477e5a-52ab-4a09-adc0-2c05712d9901.png)

**Database links:**
https://www.youtube.com/watch?v=0AK5JDfKsh8

**Comment by alexspew** [comment]
Fixed
