### ISSUE TITLE
[NPC] Missing Teraptor Matriarch

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2285]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Should walk around the edge of the cliff. Im alone here after reset. Not needed for any quest. But it's missing.

![image](https://user-images.githubusercontent.com/99285606/222347683-93571dd4-6a15-4ed5-a02b-d727f9886a19.png)

**How to reproduce:**

**How it should work:**
![image](https://user-images.githubusercontent.com/99285606/222347714-19757a9b-7c44-4e3f-8ff2-cd0f7d1add25.png)

**Database links:**
https://www.wowhead.com/npc=36735/teraptor-matriarch#comments

**Comment by UltraNix** [comment]
Fixed.
