### ISSUE TITLE
[Quest] Surrender or Else!

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Nagas are hostile during the quest, but should be in "unfriendly" state
![image](https://user-images.githubusercontent.com/99285606/222353311-b7d7df49-1c7f-4b3a-b962-62e0bf295c21.png)

**How to reproduce:**

**How it should work:**
![image](https://user-images.githubusercontent.com/99285606/222354250-968bdb80-8669-40b1-8a31-97711c9b5ebf.png)

**Database links:**

https://www.wowhead.com/quest=24868/surrender-or-else

**Comment by UltraNix** [comment]
Fixed.
