### ISSUE TITLE
[QUEST] Children of a turtle God

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2289]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The mobs not killable from range. they stay on spot and evades on very short distance from them. Have to stay on them in order to kill them
![image](https://user-images.githubusercontent.com/99285606/222359704-025a6e91-4c21-494b-9055-b95154ad6d9e.png)

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=24954/children-of-a-turtle-god

**Comment by Afgann** [comment]
fixed
