### ISSUE TITLE
[QUEST] Volcanoth!

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2290]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mob is too far in cave. Stays on spot and disappears after short (random) time after attacking with quest item.
Killable in melee. But whole event missing.

![image](https://user-images.githubusercontent.com/99285606/222360580-fcfaa58f-cb07-4552-a322-0ca2239bce3c.png)
![image](https://user-images.githubusercontent.com/99285606/222361019-b1bb6078-b47f-4b3f-b58d-fc6b17ac1b34.png)

**How to reproduce:**

**How it should work:**
![image](https://user-images.githubusercontent.com/99285606/222361381-5158c6a9-84eb-418d-bcf0-46852a6bd782.png)
https://www.youtube.com/watch?v=bcQdnEzcFHg

**Database links:**
https://www.wowhead.com/quest=24958/volcanoth

**Comment by Afgann** [comment]
fixed
