### ISSUE TITLE
[Quest] Irrestible Pool Pony

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2292]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This npc provides already finished previous quest again for some reason. in multiple occasions.

![image](https://user-images.githubusercontent.com/99285606/222369034-8f23b793-365b-43b8-b3dd-2c9f06e04432.png)

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=24864/irresistible-pool-pony

**Comment by UltraNixx** [comment]
I can't reproduce this one. Did you take this quest again?

**Comment by DeadRatsYT** [comment]
I would say could be constant ptr server restarting related. didn't notice it on production server during leveling thought you fixed it.
