### ISSUE TITLE
Cross Faction Friendly Fire

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2294]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
AOE does opposite faction damage and pets might attack them too.

**How to reproduce:**
As a Priest, I can do holy nova should heal friendly targets and deal damage to hostile targets. If I am a human (Alliance faction) and use it to next someone from the Horde faction it does him 500 damage and heals him for 1500 as well. 

When I have a pet as a Shadow fiend he will start to attack him in the assisting state because I hurt him, I saw another class does the same with their spells.

It works the same even if we are in one party.

**How it should work:**
if it should be cross faction server, damaging spells shouldn't deal them damage and pets can't attack them as well.

**Comment by MullichWhitemane** [comment]
![taken care of](https://user-images.githubusercontent.com/121984461/222427081-dd2eb75a-fce0-4f5d-8c9c-a6e5b59386b8.PNG)

Just for those who aren't aware.

**Comment by Nightw4re** [comment]
I can confirm it works as expected now. Good job
