### ISSUE TITLE
[Item/Spell] Stormchops bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#2295]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://youtu.be/B-AueCGFqP4

The effects from the stormchops item seems to work properly itself, but it only zaps critters and never zaps hostile or neutral attackable mobs.

**How to reproduce:**
1. Eat stormchops to get the buff
2a. Stand next to any critter and will zap them all
2b. Stand next to any red/yellow mob and will never zap

**How it should work:**
It's primary function is to attack enemies as it's said in the tooltip. It should zap any red/yellow mob not only critters.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=33866
https://cata-twinhead.twinstar.cz/?spell=43730

**Comment by Afgann** [comment]
fixed
