### ISSUE TITLE
Rogue DoTs / HoTs clipping

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2296]
Original report: https://discord.com/channels/1040715551531618365/1080271720486809641 (validated outside GM island)

https://wowpedia.fandom.com/wiki/Damage_over_Time
"Also as of patch 4.0.1, DoTs no longer can be 'clipped'. Previously, if a DoT was refreshed before it had expired, the tick timer was reset, causing a delay of up to double the normal time between ticks between the last tick that occurred and the first tick of the refreshed DoT. Now, the tick timer is constant. If a DoT is refreshed before it expires, the duration of the DoT will be extended by up to the full normal duration of the DoT, and ticks will continue to occur at the prior interval."

Related Github bug report: https://github.com/gamefreedomgit/Maelstrom/issues/2202

Currently, the following Rogue DoT / HoT effects are being clipped when re-applied:
- Deadly Poison
- Garrote
- Glyph of Hemorrage
- Recuperate
- Serrated Blades

Rupture works fine.

**Comment by MullichWhitemane** [comment]
Serrated Blades is clipping still. https://www.youtube.com/watch?v=ftaMgaVvEnA

Everything else works as intended.

**Comment by bonfax4** [comment]
Can this be revisited ? where did you source any of this ? A single video showed me that Glyph of Hemorhage does clip. I think this is teh bug fix that messed up dot clipping for most classes. https://youtu.be/RLwx2ybF9nU?t=8 look at rupture refresh 25 sec. If clip wasn't a thing it would be 24 secs. Keep watching the vid and see how rupture refreshes also add the duration. rupture has a 16 sec default timer and refreshes sometimes put it on 17 seconds. Same with recuperate you see it being clipped and having 31 seconds (default is 30 secs). Clip happens in every spell even Bane of doom, this is just how dots worked in cata.
