### ISSUE TITLE
Missing base melee Attack Power 

### ISSUE THREAD

**Issue by testdk123** [gamefreedomgit/Maelstrom#2298]
**Description:**
Currently characters from any class only present an Attack Power value based on their STR/AGI amounts.

**How it should work:**
Every character should have a base Attack Power amount independent of their Agi/Str values that scales with levels.
For a list for the intended value for each class: https://worldofwarcraft.fandom.com/et/wiki/Attack_power

Proof it should work this way:
Warrior: https://youtu.be/99U7N1On8D4?t=135
Paladin: https://youtu.be/15M3RfKSCZA?t=190
Rogue: https://youtu.be/eDPWnv-Zy-s?t=42
As you can see in each case the total amount of Attack Power doesn't make sense only taking into account STR/AGI multipliers + 190 AP leg enchant. There's always a missing amount that can be calculated by the formulas present in the first link posted.

**Comment by MullichWhitemane** [comment]
![example](https://user-images.githubusercontent.com/121984461/222576280-d79d0c0b-c6b6-4fa3-8820-b4d4845d3d0a.PNG)
An example: 198 strength as a Warrior, that should give me a base attack power value of 396, yet I have 376. If we check the formula from the linked site, we can see that "character level * 3" (which should be 255 in my case) is missing from our calculations, as our STR values and the subtraction of 20 is being calculated for perfectly. So, the expected value should be:
(198*2) + (85*3) - 20 = 631

Nice catch.
