### ISSUE TITLE
Dragon's Breath vs flame strike

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2299]
firemages' DB can break from flame strike on the ground, it should only break from hits

**Comment by SimonBpvp** [comment]
How to reproduce: put a flame strike on someone then db them.

**Comment by MullichWhitemane** [comment]
Can't repro this, Flamestrike patches correctly don't break Dragon's Breath. Can you explain a bit better the exact scenario this happened in?

**Comment by SimonBpvp** [comment]
yeah youre right actually its working ok
