### ISSUE TITLE
Rogue Bandit's Guile buffs not refreshing appropriately 

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2301]
Original report: https://discord.com/channels/1040715551531618365/1080899920430633081
https://wowpedia.fandom.com/wiki/Bandit%27s_Guile

Shallow Insight and Moderate Insight buffs are not being appropriately refreshed when Sinister Strike / Revealing Strike is used.

Quoting from the above linked wikipage as to how it should work:
"Deep Insight will always end after 15 seconds, but the durations of Shallow and Moderate Insight are refreshed to 15 seconds with every new Strike made. Once a buff expires, the cycle will start over with no Insight. The timer is at work even with no Insight; after 15 seconds without a Strike, any accumulated strikes toward Shallow Insight will be lost."
Note that for Cataclysm, Revealing Strike is also included next to Sinister Strike.

**Comment by melezdev** [comment]
Bump. Also, probably related:
It does not always take 4 sinister / revealing strikes to achieve the next state of insight. Sometimes I need 5 of them, but I can't pinpoint the exact circumstances. Seems to just happen randomly

**Comment by UltraNix** [comment]
Fixed.
