### ISSUE TITLE
Huge shadowfang keep bug sumoned mob too high level oneshoting whole party

### ISSUE THREAD

**Issue by keelash123** [gamefreedomgit/Maelstrom#2302]
Shadowfangkeep 5man dungeon normal mode one of the mobs using curse that spawning another mob caled haunted spirit -4958 , mob is too high level, suggested dungeon level is around 20 but this mob is around 30+ so it canot be hited by any spel or attack cause it always miss, and dealing absurd amount of damage basicly oneshoting everyone every autoattack, just one mob causing wipe every time and often have like 3 or 5 of them.

That mob should be around lvl 20 and shouldnt deal that much of autoattack damage and should despawn after taking any damage.
(dont know if the despawn think after taking damage is working because mob is too high level to hit for us so we canot hit it)

link to summoned mob:
https://www.wowhead.com/npc=4958/haunting-spirit#comments

link to spell that summon that mob:
https://www.wowhead.com/spell=7057/haunting-spirits?dd=1&ddsize=5#used-by-npc

This need to be fixed before launch because if this stay everyone that get SFK while spaming rdf is done (many pple wil spam rdf on launch), yes this bug is that bad its basicly dezerter.

**Comment by MrTide** [comment]
Haunted servitor summons these they get summoned between lvl 30-85 the way i saw it and there are too many of them
![image](https://user-images.githubusercontent.com/36106057/222669028-6b7e9e11-4b6a-4016-be37-85224e5cb3ed.png)
