### ISSUE TITLE
[QUEST] Nozzlepot's Outpost Quests (map marks missing)

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2304]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quests doesn't show up on map  testes this two but probably there is more

![image](https://user-images.githubusercontent.com/99285606/222607473-c8ba1d22-4228-45dc-8366-731b5852e2b4.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by MrTide** [comment]
Which quests ? please provide more info

**Comment by DeadRatsYT** [comment]
As seen on screenshots quests are. 
Smophlange (https://www.wowhead.com/quest=29021/samophlange) and  (competition schmompetition) https://www.wowhead.com/quest=29086/competition-schmompetition
![image](https://user-images.githubusercontent.com/99285606/222763745-b6a7e56e-605a-4b37-9a84-8c07b33af2cc.png)

**Comment by PanJanuszek** [comment]
fixed 04.03.2024 with Northern Barrens refactor
