### ISSUE TITLE
[Animation] Drinking Animation

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2305]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Character standups after every sip. Maybe goblin related
![image](https://user-images.githubusercontent.com/99285606/222609641-57dd72c5-8104-4dcd-be94-aba4bbaa495c.png)
![image](https://user-images.githubusercontent.com/99285606/222609670-ce027da9-c74d-4eab-8ead-e8ac84093590.png)

**How to reproduce:**
Happens time to time not every time. Not sure how to reproduce it everytime

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
