### ISSUE TITLE
[QUEST] Management Material

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2306]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mobs that should pop up and attack orcs do nothing.

![image](https://user-images.githubusercontent.com/99285606/222613745-f427a407-4112-438c-8598-870b64326eee.png)

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=13640/management-material

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/afe5ff03-ecfd-41b4-866d-8a4f1ffc3e3a)

It works as for 24.04.2024
