### ISSUE TITLE
[Quest][Mount Hyjal] An Offering for Aviana not working, rest chain is locked.

### ISSUE THREAD

**Issue by Sattva-108** [gamefreedomgit/Maelstrom#2307]
[An Offering for Aviana](https://www.wowhead.com/quest=25663/an-offering-for-aviana)

**Description:**
Item quest is not usable at the Shrine of the Aviana.

**How to reproduce:**
Pick up quest and try to use quest item at the shrine. (6 rocks circle)
I have video guide attached.

**How it should work:**
You should be able to use quest item at the Shrine. 

**Database links:**

[Quest link Wowhead](https://www.wowhead.com/quest=25663/an-offering-for-aviana)
[Quest Item ](https://cata-twinhead.twinstar.cz/?item=55208)

https://user-images.githubusercontent.com/74269253/222618093-df8b3b24-737a-4915-8923-0343f446361e.mp4

**Comment by Afgann** [comment]
fixed

**Comment by MrTide** [comment]
by the looks of it
it works fine
