### ISSUE TITLE
[Quest][Objects][Mount Hyjal] Scrambling for Eggs, not working, rest chain 20+ quests locked.

### ISSUE THREAD

**Issue by Sattva-108** [gamefreedomgit/Maelstrom#2308]
## Scrambling for Eggs
**Description:**
Objects (eggs) are missing, can't complete quest.

**How to reproduce:**
Try to take quest Scrambling for Eggs and find eggs near harpies or elsewhere.

**How it should work:**
There should be eggs in a couple spots.

**Database links:**
[Quest link](https://www.wowhead.com/quest=25656/scrambling-for-eggs)
[Egg object link](https://cata-twinhead.twinstar.cz/?object=203143#.), it should contain [Quest Item](https://cata-twinhead.twinstar.cz/?item=55189)

**Comment by Afgann** [comment]
fixed
