### ISSUE TITLE
[QUEST] Take him to the earthcaller 

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2309]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Npc falls under the textures. Need to stay on top of npc in order to complete the quest.
![image](https://user-images.githubusercontent.com/99285606/222637024-620a4154-a75a-4a84-a9bf-4c473bb4e6c1.png)
![image](https://user-images.githubusercontent.com/99285606/222637069-f0771c12-5649-456d-aaa8-36cb2d347e47.png)

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=26413/take-him-to-the-earthcaller

**Comment by MrTide** [comment]
Duplicated
https://github.com/gamefreedomgit/Maelstrom/issues/1759
