### ISSUE TITLE
[Quest][Uldum][Phasing] Send Word to Phaoris breaks phasing -> all rest chains in not available in Uldum.

### ISSUE THREAD

**Issue by Sattva-108** [gamefreedomgit/Maelstrom#2310]
## Send Word to Phaoris

**Description:**
Quest breaks phasing once turned-in. You are no longer able to do any quest in the Uldum zone at all. Can't see any NPCs.
Tested on 3 characters, level 83, and 2 level 1s. 

**How to reproduce:**
Do .quest add 27628 command go to Ramkahen, turn in the quest and there the phasing breaks.

**How it should work:**
You should be phased where you can see NPCs and continue questing.

**Database links:**
[WoWHead Link](https://www.wowhead.com/quest=27628/send-word-to-phaoris)

https://user-images.githubusercontent.com/74269253/222657512-ed4c1673-d8cb-413e-80d6-f73b0a128ca4.mp4

**Comment by Sattva-108** [comment]
## **UPDATE:** 
***relog*** changes phase to "default" one in which u were before you did turn-in.
However it doesnt change a fact that all quests are locked, you should be able to get 3 quests right after this turn in:

**[The High Commander's Vote](https://www.wowhead.com/quest=27631/the-high-commanders-vote)
[The Vizier's Vote](https://www.wowhead.com/quest=27629/the-viziers-vote)
[The High Priest's Vote](https://www.wowhead.com/quest=27630/the-high-priests-vote)**

Which are long chains, and without them whole zone become useless. Couldn't ding 83-84 on x2 rates, missing 30% of XP.

**Comment by Sattva-108** [comment]
## UPDATE 2 
could be problem with cinematic, it gets skipped automatically therefore you don't phase correctly.
I can also, that if u port to orgrimmar after this or elsewhere without **relog** then you cant see any NPCs.

**Comment by Sattva-108** [comment]
same issue with https://github.com/gamefreedomgit/Maelstrom/issues/2311

**Comment by Afgann** [comment]
fixed
