### ISSUE TITLE
[Quest][Uldum] The High Council's Decision, phasing break/cinematic skipped.

### ISSUE THREAD

**Issue by Sattva-108** [gamefreedomgit/Maelstrom#2311]
## The High Council's Decision

**Description:**
Quest breaks phasing once turned-in. https://github.com/gamefreedomgit/Maelstrom/issues/2310

**How to reproduce:**
Do .quest add 28533 command go to Ramkahen, turn in the quest and there the phasing breaks.

**How it should work:**
You should be phased where you can see NPCs and continue questing.

**Database links:**
[WoWHead Link](https://www.wowhead.com/quest=28533/the-high-councils-decision#)

## Seems to be cinematic auto-skipped issue.

https://user-images.githubusercontent.com/74269253/222689934-33be5822-d9f4-408d-92c3-ac7479938180.mp4

**Comment by Afgann** [comment]
fixed
