### ISSUE TITLE
[Moved from Discord] Seduction enabling pet attack when pet is on passive stance

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2313]
**Description:**
When seduction pet ability is casted,  pets auto attack is enabled.  

**How to reproduce:**
Place pet on passive,  use seduction,  auto attack will enable without request 

**How it should work:**
Using pet skills should not activate the pets auto attack 

https://cdn.discordapp.com/attachments/1081237880397107221/1081237882980815038/Seduction_enable_Autoattack_Trim.mp4 
^ player submitted

https://cdn.discordapp.com/attachments/1081237880397107221/1081238319784009779/Cobrak_Seduction.mp4
^ retail

**Comment by UltraNixx** [comment]
Fixed.
