### ISSUE TITLE
Stranded in the Marsh: Worgen zone quest bug

### ISSUE THREAD

**Issue by Lynxi13** [gamefreedomgit/Maelstrom#2315]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest is to rescue survivors, usually you kill crocs. This does not count towards the quest.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Tested - everything works okay.
