### ISSUE TITLE
I cant link some items to chat

### ISSUE THREAD

**Issue by xyqzera** [gamefreedomgit/Maelstrom#2318]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I cant link some items to chat, like weapons etc. 

**How to reproduce:**
trying to link items im wearing and from bags

**How it should work:**
Items should be link-able in the chat

**Comment by UltraNix** [comment]
Fixed.
