### ISSUE TITLE
Getting Dungeondeserter after finishing the dungeon.

### ISSUE THREAD

**Issue by JovH2211** [gamefreedomgit/Maelstrom#2321]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While being in a pre-made group the issue occurs that we can't que after finishing a dungeon. We get the error. Teleportation issue. To fix this we leave the dungeon and want to regroup again. However, the first 2 who leave the group get the dungeon deserter.

**How to reproduce:**
Pre-made group. Not all people in the instance and queing for dungeon.

**How it should work:**
Beeing able to que with a group wherever they are.

**Database links:**

**Comment by WhitemaneSylah** [comment]
Should have been fixed, no further reports of this
