### ISSUE TITLE
Volcanoth!

### ISSUE THREAD

**Issue by Clintmega** [gamefreedomgit/Maelstrom#2322]
Volcanoth quest id: 24958

Goblin racial questline

After killing Volcanoth the plane to move you out of the Volcano spawns but does not remove you from the area, when trying to leave the cave I ended up falling through the world until a dev moved me.

I'm unsure if the Volcanoth! quest is marked complete but I've been unable to find the quest start for Old Friends and am stuck at this point.

**Comment by MrTide** [comment]
Further testing shows quest Volcanoth is marked as completed on the players but they can't turn it in  and quest old friends after that now after recent update is working decently

**Comment by spykoo** [comment]
I can kill Volcanoth but the plane does not appear afterwards but the question mark shows on the map where it should be at - how do i get this completed????

**Comment by Afgann** [comment]
fixed
