### ISSUE TITLE
A Prayer and a Wing, A Bird in Hand and Fact-Finding Mission

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2323]
**How to reproduce:**
Player was trying to do a quest called A Prayer and a Wing and  A Bird in Hand but he was unable to do it because he (or the objects) was in different phase : 33554432
![image](https://user-images.githubusercontent.com/36106057/222901241-07f450e6-c93e-46ae-b8c9-506c081d98d6.png)

obj was in phase 1 for quest A Prayer and a Wing
![image](https://user-images.githubusercontent.com/36106057/222883592-c4db0a75-bf10-4a61-9c95-f8593b2a28f5.png)
players can't see A Bird in Hand harpy signal fire
![image](https://user-images.githubusercontent.com/36106057/222886716-2b9c7bf7-3697-4bc9-ba74-ba32bb33333f.png)

player also was unable to get the next quest Fact-Finding Mission nor complete it after A Prayer and a Wing quest because npc/objective was phased out

**How it should work:**
player or the object should be in correct phase while doing this quest so he can finish it
i believe you need to move those objects and the npc to phase 33554432

**Comment by UltraNixx** [comment]
Fixed.
