### ISSUE TITLE
[ZONE] Twillight Highlands

### ISSUE THREAD

**Issue by whateveracc** [gamefreedomgit/Maelstrom#2325]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
u can't mine any ore there

**How to reproduce:**
https://streamable.com/bs8rry

**How it should work:**
~~~

**Database links:**
~~~

**Comment by UltraNixx** [comment]
Fixed.
