### ISSUE TITLE
[Quest] The Tortusk Takedown

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#2326]
Quest "The Tortusk Takedown"

Mob in front of it is mass spawning wolves, making the quest... more or less impossible to get around due to the mass amount of mobs.

![image-25](https://user-images.githubusercontent.com/67768754/222931863-e129d07b-190c-4a0f-8b55-c8f6e3552363.png)

or they might actually belong to Rortusk himself

**Comment by Afgann** [comment]
fixed
