### ISSUE TITLE
[Dungeon] Scarlet Monastery - Graveyard - Stuck on Death 

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#2327]
If you wipe in SM GY you arent able to zone back in and receive the message in game "Unable to zone in while an encounter is in progress."

Even if someone leaves and you try to reque the new people aren't able to zone in either thus resulting in everyone leaving and acquiring the 30 minute dungeon deserter debuff.

if you die you're unable to re-enter/use rdf teleport to enter

**Comment by UltraNixx** [comment]
@Loken-coolguy Do you remember what boss?

**Comment by UltraNix** [comment]
Fixed.
