### ISSUE TITLE
BG bugs

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2329]
https://gyazo.com/92346cbafad1a84f294e84dbb2cc669e
1. game end messages but the game doesnt end

https://gyazo.com/01635c3e18c3b3fb07fdb8546ac91de2
2. cant capture insignia from corpse (the cast finishes but it doesnt work)

3. https://gyazo.com/3f1cc7bde46907d5a8bcd51d3c26cab1
someone caps the alli flag before the horde flag is returned?

**Comment by UltraNixx** [comment]
1. Looks like something clientside and not sent by the server.

**Comment by UltraNix** [comment]
No 2. fixed.
No 1. won't fix.
