### ISSUE TITLE
Not getting experience for gathering herbs. 

### ISSUE THREAD

**Issue by ankorafeonix** [gamefreedomgit/Maelstrom#2332]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I was getting experience for gathering when the server launched, but at some point this stopped working and I dont get xp any more. I'm level 80 in Hyjal and gathering provides no experience. 

**How to reproduce:**

Try gathering from a node. 

**How it should work:**

You should get experience. 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
