### ISSUE TITLE
Reporting a player via the chat disconnects the player who is making the report

### ISSUE THREAD

**Issue by PendulumWM** [gamefreedomgit/Maelstrom#2333]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Reporting a player via in-game chat by right clicking <player name> > report player for > spamming (my picked option) disconnects me instantly from the game (Tried it 2 times)

*I wanted to report a player for selling gold via a shady website and spamming me in game*
**How to reproduce:**
right clicking them > report player for > spamming 

**How it should work:**
not to get disconnected 

**Database links:**

**Comment by sadgh05t** [comment]
Happened to me as well

**Comment by Wees3** [comment]
Hahahahaha

**Comment by UltraNix** [comment]
Please, test it again.

**Comment by PendulumWM** [comment]
Doesn't disconnect, now if it reaches you people that's a whole other story.

**Comment by Afgann** [comment]
fixed

**Comment by Nightw4re** [comment]
This issue is back on the production server.
