### ISSUE TITLE
Warlock's Succubus Seduction PvP duration is set to PvE duration

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2334]
Original report: https://discord.com/channels/1040715551531618365/1081879145841176596
Currently, Seduction has a duration of 30 seconds in PvP - it should be 8.
![seduc](https://user-images.githubusercontent.com/121984461/222968310-f08b33f9-7a69-4089-9d5e-de91f57f243c.png)

**Comment by UltraNixx** [comment]
Fixed.
