### ISSUE TITLE
Normal doungeons dont give exp from tabaard

### ISSUE THREAD

**Issue by Asherada** [gamefreedomgit/Maelstrom#2336]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Me and my friend didnt get reputation from normal doungeons from rep tabard

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Which Tabard? Which Dungeon?

**Comment by WhitemaneSylah** [comment]
All of them @Loken-coolguy 
status confirm

**Comment by EdyGlockenspiel** [comment]
Can personally confirm. I am soloing Forge of Souls with Kirin Tor Tabard equipped and getting no Kirin Tor rep.

**Comment by UltraNix** [comment]
Normal dungeon do not give rep (even with tabards).

**Comment by EdyGlockenspiel** [comment]
They definitely are supposed to, don't know where you read that *none* of them don't. Only the higher level ones do, but they do. This is how it worked in wrath and how it still works on retail.

**Comment by EdyGlockenspiel** [comment]
For example, halls of lightning should give tabard rep, but halls of stone will not. Utgard keep does not, but Utgard pinncal does.

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Championing
There are some exceptions and you can test whether it does work or not.

**Comment by EdyGlockenspiel** [comment]
I already did, when I was farming for my 22 slot bag from forge of souls on normal, I got no tabard rep. I only got tabard rep from H. Any 5 man instance lvl 77+ from wrath should give rep from tabards on normal mode. Halls of lightning is lvl 77+, where as halls of stone is 75+, hence why the one gives rep and not the other.
