### ISSUE TITLE
[dungeon] Grim Batol

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2337]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if you kill this mobs "Twillight Wyrmcaller" (2 in total in the dungeon) during dragon fly event he will be acting as alive: patrolling and attacking group. Also he is immortal in the state. So it will wipe your group 

And if you wipe Dragon ride skip is not there. 

![image](https://user-images.githubusercontent.com/99285606/222976830-5274df3a-02ec-4014-8331-f3afaa63a234.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNixx** [comment]
Should be fixed.

**Comment by UltraNix** [comment]
Fixed.
