### ISSUE TITLE
Uldum "Premature Explosionation" Quest Bugged

### ISSUE THREAD

**Issue by guddsy** [gamefreedomgit/Maelstrom#2338]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The quest for "Premature Explosionation" in Uldum didn't work for me.  After clicking the Powder Keg the cutscene would attempt to play but would just clone my character and after a few mins I get phased back with the NPC but the quest is not completed.

**How to reproduce:**

As soon as you click the Powder Keg you will create a clone image of yourself and after a few mins you phase back in with the quest not completed

**How it should work:**

When clicking the Powder Keg it should play the cutscene and then complete the quest once its finished

**Database links:**

**Comment by MrTide** [comment]
player is correct
cut scene is not playing anymore for some reason neither
https://www.youtube.com/watch?v=7Puz4DEGSOQ

**Comment by UltraNix** [comment]
Fixed.
