### ISSUE TITLE
Disarming a hunter trap makes a rogue leave stealth

### ISSUE THREAD

**Issue by sassouiabd** [gamefreedomgit/Maelstrom#2340]
**Description:**
Disarming a hunter trap makes a rogue leave stealth. This happened in Warsong Gulch, i am not sur if its reproductible also outside WSG.
Already reported on discord too: https://discord.com/channels/1040715551531618365/1082010036982788127

**How to reproduce:**
https://www.twitch.tv/videos/1756615928

**How it should work:**
Disarming a hunter trap should not make a rogue leave stealth

**Comment by Afgann** [comment]
fixed
