### ISSUE TITLE
quest Counterattack! not working

### ISSUE THREAD

**Issue by flareondash** [gamefreedomgit/Maelstrom#2342]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Hello, I would like to report the quest Counterattack! in Northwest Northern Barrens. The mobs required don't sim to be spawning so you cannot complete the quest.

**How to reproduce:** Im not sure how you can reproduce it just go to the exact location and see for your self.

**How it should work:** The mobs should be spawning in place so you can actually complete the quest, as shown in the link tutorial.

**Database links:** https://www.wowhead.com/quest=4021/counterattack
![image_2023-03-06_000559945](https://user-images.githubusercontent.com/126990264/222988576-26389082-d27c-4bdf-a2bb-c6e08a645e49.png)

**Comment by Loken-coolguy** [comment]
Confirmed, all NPCs are missing for this quest

**Comment by PanJanuszek** [comment]
Fixed with barrens refactor 04.03.2024
