### ISSUE TITLE
Cant connect to Server Without VPN

### ISSUE THREAD

**Issue by pish555** [gamefreedomgit/Maelstrom#2344]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** im from iran and i cant connect to server Without VPN i had this problem on some servers before but they fix it after my ticket please if you can fix this issue so our players can play this server too Thanks 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
We have plenty of Iranian players able to connect without VPN. This is an issue with your connection.

**Comment by Deexxyy** [comment]
Me and my friends have the same issue we cant connect without vpn we live in iran :(
