### ISSUE TITLE
BG's pet attack on respawn

### ISSUE THREAD

**Issue by UnholyPhage** [gamefreedomgit/Maelstrom#2345]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you RS (Respawn) in BG's your pet goes into passive mode all the time even though you selected ATK mode before dying

**How to reproduce:**

**How it should work:**
Should automatically be on atk mode when respawned

**Database links:**

**Comment by UltraNix** [comment]
ATK mode?

**Comment by UltraNix** [comment]
No further info - closing.
