### ISSUE TITLE
Stuck on a gryphon while dead

### ISSUE THREAD

**Issue by etainebless** [gamefreedomgit/Maelstrom#2355]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, I died in one of the Blackrock Mountain dungeons and spawned dead on a gryphon. I cant move or take rez sickness.
![WoWScrnShot_030623_161157](https://user-images.githubusercontent.com/126571268/223042510-87b4b59b-7ae3-4a21-a07a-be30412dc483.jpg)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneSylah** [comment]
should be fixed
