### ISSUE TITLE
Rahj Halls of Origination Heroic

### ISSUE THREAD

**Issue by gewmi** [gamefreedomgit/Maelstrom#2357]
Description:
Heroic Rahj uses way too many abilities and it is impossible to heal, his energy regenerates instantly so he can use his skills whenever he wants.

How to reproduce:
Just try to fight him on heroic Halls of Origination.

How it should work:
His abilities actually reduce his energy and he doesn't gain it back right away so he can't spam his abilities, instead he gains it back after his channel where he takes 100% extra damage.

Database links:
https://www.wowhead.com/npc=39378/rajh

**Comment by MrTide** [comment]
He is not losing his energy and regenerating all the time that might be the cause

**Comment by UltraNix** [comment]
Fixed.
