### ISSUE TITLE
[Archeology] You Occured Error! Digsite removed and generated new one!

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2360]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Discovered those 2 spots where is unable to gid, telescope even not appeared.
![image](https://user-images.githubusercontent.com/101097828/223115686-e26b1c1b-a7bb-414f-af48-6eea725598f0.png)

**How to reproduce:**
I have Archeology on 200 skill.
![image](https://user-images.githubusercontent.com/101097828/223116066-c73bee32-11a2-45ad-a971-6f5906fcd61f.png)
![image](https://user-images.githubusercontent.com/101097828/223116122-ed3db0f1-65ce-449e-8559-99785e71316e.png)

**Comment by Nightw4re** [comment]
![image](https://user-images.githubusercontent.com/101097828/223119832-4e9262e1-5b05-4cb2-a9f0-815a6e117874.png)

It starts doing here as well even I was digging there a while ago.

**Comment by UltraNix** [comment]
Fixed.
