### ISSUE TITLE
[Warlock] Seduction from warlock pet CC for 90 sec

### ISSUE THREAD

**Issue by sassouiabd** [gamefreedomgit/Maelstrom#2362]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Seduction from the warlock pet cc a player for 30 sec and this without DR

**How to reproduce:**
https://www.twitch.tv/videos/1757318144

**How it should work:**
Seduction should not be 30 sec on a player.

**Database links:**

**Comment by sassouiabd** [comment]
@[mortenmiddelhede](https://github.com/mortenmiddelhede) for more informations if needed

**Comment by mortenmiddelhede** [comment]
I am the warlock in the video helping showcase; the 30sec Seduction only happens sometimes and im not sure whats triggering it.

**Comment by WhitemaneSylah** [comment]
should have been fixed
