### ISSUE TITLE
Mount speed bug after joining game

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2363]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you exit game while being on a mount and then join again your mount movement speed is reduced by like 30% till you summon horse again.
Tested on 60% speed bonus and faster human horses and dwarf rams so its not mount specific.

**How to reproduce:**
Exit game while on mount and join again.

**How it should work:**
Mount should move all the time with +60% movment speed.

**Database links:**
https://tbc-twinhead.twinstar.cz/?spell=34768
https://www.wowhead.com/wotlk/spell=472/pinto
https://www.wowhead.com/wotlk/item=5655/chestnut-mare-bridle
https://www.wowhead.com/item=5656/brown-horse-bridle
________________________________________________
Link to video for confirmation
https://www.youtube.com/watch?v=oKmkmF-UFvc

**Comment by ChanJustWon** [comment]
Can confirm, happening to me aswell

**Comment by UltraNix** [comment]
Fixed.
