### ISSUE TITLE
mob locked on

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2364]
these little fuckers follow you everywhere lol, no aggro reset, no range

https://gyazo.com/306632bef30d198f023f1e2c32b43469

they dont attack they just follow you and cant be killed.

**Comment by SimonBpvp** [comment]
https://gyazo.com/83257638a7b5eb922574b7746fc3b2f2

2 more

**Comment by UltraNix** [comment]
I will leave #5763 as more info there.
