### ISSUE TITLE
"Vidow Venom" Hunter spell

### ISSUE THREAD

**Issue by DopeTripz** [gamefreedomgit/Maelstrom#2365]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:About Widow Venom **

**How to reproduce: The spell says it taken 30 sec 25% healing reduction but is only takes 9 seconds**

**How it should work:Increase the effect to 30 secs like the spell says**

**Database links:**

**Comment by MullichWhitemane** [comment]
Widow Venom has a PvE duration of 30 seconds and a PvP duration of 10 seconds. This is correct behaviour.
