### ISSUE TITLE
[Dungeon] Scarlet Monastery Libary, mobs and boss under the map

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2366]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the halls of libary dunegon mobs and boss Arcanist Doan when aggroed fall under the map.
Warrior can charge through floor.
Mobs who fell under the map later on when we went to finish quest appeared or respawned on the way back (look video)

**How to reproduce:**
Aggro the mobs in the way to the 2nd boss and they fall down, they are still killable 

**How it should work:**
Mobs and boss should not fall under the map.

**Database links:**
https://www.wowhead.com/classic/npc=6487/arcanist-doan

Videos for confirmation:
https://www.youtube.com/watch?v=ZuWnvLuXMKc
https://www.youtube.com/watch?v=86DOHU2pl00
https://www.youtube.com/watch?v=lIx_Wq3vQQM

**Comment by WhitemaneSylah** [comment]
Should be fixed already
