### ISSUE TITLE
[Cosmetic] Noggenfoggler doesn't allow to mount up

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#2368]
**Description:**
Noggenfoggler form tells you that you are in a shapeshift form, which doesn't allow you to mount up. Except that it's not a shapeshift form.

**How to reproduce:**
Drink NF elixir and try to mount up. You won't be able to.

**How it should work:**
You should be able to mount up.
https://www.youtube.com/watch?v=I5Zlfoz31c8

**Comment by Afgann** [comment]
fixed
