### ISSUE TITLE
Pickpocket loot table

### ISSUE THREAD

**Issue by Jokieh** [gamefreedomgit/Maelstrom#2369]
Junkboxes doesn't exist in Cata mobs' loot tables.

https://cata-twinhead.twinstar.cz/?item=63349

I was pickpocketing everything basically while grinding the RDF and junkboxes did drop with a very good chance pre-60.

I did run a lot of Cata normal dungeons (10+) pickpocketing every humanoid mob, also pickpocketed every mob while questing and no Flame-Scarred Junkbox dropped.

**Comment by sassouiabd** [comment]
Same issue as https://github.com/gamefreedomgit/Maelstrom/issues/2372
