### ISSUE TITLE
Raz is frozen at the end of Blackrock Cavern 

### ISSUE THREAD

**Issue by Mintzyfrmtwitch** [gamefreedomgit/Maelstrom#2370]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Raz leaps into the last boss, all the Wardens etc run into Raz and he just freezes, doesn't attack or even move.

**How to reproduce:**
Getting within range of the last boss in Blackrock Cavern

**How it should work:**
If I'm correct Raz should clear all but the boss, and the bosses adds.

**Database links:**
Reference clip of it happening
https://clips.twitch.tv/SpineyExquisiteCarrotSSSsss-7S7Hf9eFOvMiSmpE

**Comment by Afgann** [comment]
fixed
