### ISSUE TITLE
eating cancelled by dots

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2374]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
eating mana cakes gets interrupted by having a dot tick on you

**How to reproduce:**
put a dot then leave combat and eat

**How it should work:**
you should be able to eat/drink with dots on you. Only direct dmg should stop you

**Database links:**

**Comment by Afgann** [comment]
fixed
