### ISSUE TITLE
[Quest] Demon Duty not working

### ISSUE THREAD

**Issue by flareondash** [gamefreedomgit/Maelstrom#2379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** the quest Demon Duty from NPC 'Locke Okarr' in Splintertree Post, Ashenvale that requires you to close Demon portals at Satyrnaar and Xavian (Northeastern Ashenvale) doesnt sim to be working because the portals/crystals that you are supposed to close are not interactable.

**How to reproduce:** try the quest your self.

**How it should work:** you should be able to interact with the portals/crystals like in its quest page tutorial on wowhead.

**Database links:** https://www.wowhead.com/quest=13806/demon-duty

![image_2023-03-07_194322686](https://user-images.githubusercontent.com/126990264/223504983-c51ea738-7bb3-4310-b51c-2720c8a04612.png)

**Comment by UltraNix** [comment]
Fixed.
