### ISSUE TITLE
RDF dungeon level range either too broad, not filtering for level, or not working at all.

### ISSUE THREAD

**Issue by Clintmega** [gamefreedomgit/Maelstrom#2383]
I am a lv54 goblin and have been getting RDF queues into low level dungeons today, for example Scholomance, Scarlet Monastery Cath (where the door bugged out) and even Ragefire Chasm.

How it should work: RDF selects from the pool of available dungeons that your level is appropriate for.

**Comment by UltraNix** [comment]
Fixed.
