### ISSUE TITLE
paladin's gcd bug (retribution)buttons do not press from 1 time

### ISSUE THREAD

**Issue by dromn7** [gamefreedomgit/Maelstrom#2386]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Global cooldown
**Description:**
the buttons are not pressed the first time, you have to shout

**How to reproduce:**
[https://youtu.be/5o3irPnJr5g](https://vk.com/away.php?to=https%3A%2F%2Fyoutu.be%2F5o3irPnJr5g&cc_key=)(this is how it works now)

**How it should work:**

[https://youtu.be/FU83BLfkJIg](https://vk.com/away.php?to=https%3A%2F%2Fyoutu.be%2FFU83BLfkJIg&cc_key=)(this is how it shold work)
**Database links:**

**Comment by WhitemaneSylah** [comment]
Latency issue
