### ISSUE TITLE
Goblin Racial Quest ''Rocket Boot Boost'' 

### ISSUE THREAD

**Issue by stadadasta** [gamefreedomgit/Maelstrom#2388]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Goblin Racial Quest ''Rocket Boot Boost'' is bugged. I used the quest item at the correct location, but died on landing and the quest end point NPC remains with a greyed out question mark over his head.

Visual Aid = https://imageshack.com/i/pmUQNY4Gp

**How to reproduce:**

Take the quest, use the item (Rockin Powder Infused Rocket Boots) and you will see the same unfortunate result

**How it should work:**

You should land without dying and have the NPC with a yellow question mark above their heads

**Database links:**

https://wowpedia.fandom.com/wiki/Rocket_Boot_Boost

**Comment by Afgann** [comment]
fixed
