### ISSUE TITLE
Blackrock Caverns first boss bugged

### ISSUE THREAD

**Issue by mugiwara1226** [gamefreedomgit/Maelstrom#2391]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The first boss of Blackrock Caverns has an critical bug on his main mechanic which is https://www.wowhead.com/spell=75441/chains-of-woe?dd=6, it should pull all the players together so that they can broke the chain and get free and run away from him to avoid his aoe https://www.wowhead.com/spell=75543/the-skullcracker?dd=6, otherwise is a wipe on normal, on hero I dont think it will be possible to do it due to the high amount of dmg.

**How to reproduce:** Go into the Blackrock Caverns and lower his HP to 66% or 33% and he will use https://www.wowhead.com/spell=75441/chains-of-woe?dd=6, you will notice how he is not pulling anyone and all players stay where they were with movement down to 99% or 100%.

**How it should work:** It should bring all the players together showed on this video https://youtu.be/vZBzbb-ClOA?t=209

**Database links:** https://www.wowhead.com/spell=75441/chains-of-woe

**Comment by Afgann** [comment]
fixed
