### ISSUE TITLE
Beneath the surface

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2392]
**How to reproduce:**
looks like you can't click on the npc to trigger the event
![image](https://user-images.githubusercontent.com/36106057/223632565-c9302915-608f-4dce-889f-d3ef555df199.png)

**How it should work:** you should be able to click and finish the event
https://youtu.be/ySJIHRhY22E?t=98

**Comment by UltraNix** [comment]
Fixed.
