### ISSUE TITLE
Hunters: General Major Issues

### ISSUE THREAD

**Issue by markkits** [gamefreedomgit/Maelstrom#2394]
All the issues below are from my level **85 hunter, doing pvp in random bgs**. I don't know about pve.

**Description:**
1- **Hunter pets will randomly stop attacking a target. Pet will follow the target at a 10-15 yard distance, but do not attack.** Repeating a pet attack order does not do anything when this happens. Only way to get it to attack again is to pull the pet back completely with petfollow, and then send it to attack back. Which takes far too long and usually gets you killed.

2- **Master's Call does not work most of the time.** I've tried several combinations of macros and could not get it to work consistently. The pet will sometimes freedom itself, but not the hunter/target. It usually gets you killed every time you rely on this ability in pvp.

3- **All hunter traps take an extra 2 seconds to trigger.** This makes landing traps extremely difficult, as even when you pre trap, your enemy can casually approach and walk right through without triggering the traps. Usually gets you killed.

4- **Dismiss pet has an extra globals worth of delay that is not supposed to be there.** There is an extra delay when dismissing your current pet to quickly summon the next pet and use pet ability. Quickly cycling through pets for their abilities was an important tool in Cataclysm hunter's kit. But feels very clunky here with the added delay that is not supposed to be there.

**Comment by Wees369** [comment]
Pets don't lose focus too, for example in hunt vs hunt, if one of the hunt uses fd and the enemy pet was on him, it will stay on him.
For the master's call, it's when the pet is out of range that it doesn't work, for example if you want freedom an allies away from you, you will get closer by spamming freedom, and the latter will not apply but will put you the cd.

This often happens to me when I disengage.

**Comment by WhitemaneSylah** [comment]
Can we get some video proof of this please

**Comment by UltraNix** [comment]
No futher info - closing.
