### ISSUE TITLE
One item each missing from Valor and Honor Vendors

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2397]
itemid 68812 missing from the valor vendor (359 agi ring) https://www.wowhead.com/item=68812/hornet-sting-band
itemid 64850 missing from the bloodthirsty pvp vendor (353 agi offhand dagger) https://www.wowhead.com/item=64850/bloodthirsty-gladiators-shiv

**Comment by Afgann** [comment]
fixed
