### ISSUE TITLE
Quest bug - level 16 Loch Modan

### ISSUE THREAD

**Issue by einzel** [gamefreedomgit/Maelstrom#2402]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest "Keep your hands off the merchandise" https://cata-twinhead.twinstar.cz/?quest=13650 does not allow for interaction with the quest objects. They don't sparkle either.

**How to reproduce:**
Have the quest and walk into the dig site. On two PCs we had no interact ability with any of the artifacts. 

**How it should work:**
Should be able to inspect the artifacts for quest completion

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=13650

**Comment by UltraNix** [comment]
You don't need to click anything - just run into it.
