### ISSUE TITLE
Tarvus the Vile 

### ISSUE THREAD

**Issue by Esmeralda-CM** [gamefreedomgit/Maelstrom#2403]
This NPC is not currently spawned in game. 

https://www.wowhead.com/npc=50086/tarvus-the-vile#drops

even if he were dead he'd show up in this spawn list 

![image](https://user-images.githubusercontent.com/123559920/224042314-236ca28f-5af7-4206-8a70-3687824d1b8f.png)

**Comment by UltraNix** [comment]
Fixed.
