### ISSUE TITLE
Npc Spawned to many times

### ISSUE THREAD

**Issue by DinuGabriel** [gamefreedomgit/Maelstrom#2408]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Npc named "terrath the steady", coordinates 33.0 ,24.0, in deepholm around the pale roost spawned way to many times in the same place and may produce lag.

**How to reproduce:**
Im not sure how to reproduce it but i have all the quests in deepholm done in case this information helps.

**How it should work:**

**Database links:**
https://www.wowhead.com/npc=42466/terrath-the-steady

**Comment by UltraNix** [comment]
Fixed.
