### ISSUE TITLE
[priest] MC bug in bgs

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2410]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if you MC someone in a bg you can never attack them again but they can still play. ( has to be same faction as you)

**How to reproduce:**
MC someone from the same faction as you in BG

**How it should work:**
nobody knows how mc should work but not like this surely haha

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
