### ISSUE TITLE
Acherus The ebon blade bugs and enhancements 

### ISSUE THREAD

**Issue by Deexxyy** [gamefreedomgit/Maelstrom#2411]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The runeforges in Acherus the ebon blade on the second floor aren't visual you can rune forge your weapon but cant see them.
2 way death gates and portals are neccesery 
**How to reproduce:**
every time I get there I cant go back and or get into orgimmar or stormwind transportations are pretty much hard for death knights
 I'v seen two portals of Stormwind and Orgimmar in the second floors terrace in later versions of wow it can help a lot if you add them.  every time we use Deathgate we cant use it again to get back where we teleported. please make the death gate  a 2 way portal
Sorry for my English
**How it should work:**

**Database links:**
Runeforges
![image](https://user-images.githubusercontent.com/127470122/224234065-8026f6d4-5418-4237-9cb0-756332349013.png)
and for the portals 
![image](https://user-images.githubusercontent.com/127470122/224234274-06c4cd0d-93ef-42bf-b586-40feb97bd922.png)

**Comment by WhitemaneSylah** [comment]
Visual error regarding the runeforges,  standing in the correct area will still allow you to runeforge. 
Most likely will not add the portals in

**Comment by austre** [comment]
Portal to Stormwind not working when we click on it.

![image](https://user-images.githubusercontent.com/4764413/229662085-796060bb-1b81-42f4-911e-2559eef526bf.png)

**Comment by austre** [comment]
At the same way, flight not working too.

![image](https://user-images.githubusercontent.com/4764413/229662287-fe01eaad-b0cb-4354-9740-4fb9042883ca.png)

**Comment by UltraNix** [comment]
Fixed.
