### ISSUE TITLE
Unable to accept/enter battleground queue

### ISSUE THREAD

**Issue by Serxah19** [gamefreedomgit/Maelstrom#2414]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am constantly running into an issue where my Battleground queue will pop, and no matter how many times I try to select enter battle nothing happens. It will not even let me press leave queue 

**How to reproduce:**
I do not know what causes it to occur but it happened for an hour last night and then it stopped and now it is occurring again 

**How it should work:**
when I press enter battle I should enter the battle

**Database links:**

**Comment by Serxah19** [comment]
when I click enter battle the first time the notification disappears and moves up to the small button along the side of the map and from this button I  am pressing enter battle over and over again but nothing happens,

**Comment by Serxah19** [comment]
I have tried logging in and out, reloading, hearthing etc and nothing seems to correct this

**Comment by Afgann** [comment]
fixed
