### ISSUE TITLE
Arch digsite's npw spawning 

### ISSUE THREAD

**Issue by Svixu** [gamefreedomgit/Maelstrom#2416]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i reached 450 arch and only recieved this issue after reaching 450 but i finished all the digsites in eastern kingdoms, kalimdor and northrend. went to outland to finish the digsites got one digsite left that i can survey once till i find fragments then get "digsite error generating new dig site" no new on  pops up i relog can survey till i find fragments again then it dissappears no new one spawns and when i log back on the game that exact digsite is back and its the same process

**How to reproduce:**

**How it should work:**
i should be getting new digsites as one finish

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
