### ISSUE TITLE
[Rogue] energy regeneration vs PVE attack slows

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2419]
This one is hypothetical, feel free to close if it should work like that.

**Description:**
Attack slows in PVE cause rogue to regenerate proportionally less energy

**How to reproduce:**
Get your attack speed slowed by a monster. Example of such monster is https://www.wowhead.com/npc=51673/venomscale-spitter

**How it should work:**
Energy regeneration should not be affected by attack speed (??)

**Database links:**
none

**Comment by Vezax69** [comment]
Haste modifiers also affects energy regeneration, pretty common and widely known thing on Cataclysm, as beneficial effects increase your energy regeneration any negative haste modifier will do the opposite.

**Comment by melezdev** [comment]
yes, haste - but not attack speed?

**Comment by Vezax69** [comment]
Haste, as a stat, translates to attack speed (you can see it on the % conversion per points of haste). There is no difference between the two when it comes to this specific topic.

**Comment by melezdev** [comment]
No, there's tremendous difference.

Attack speed buffs like slice and dice and lightning reflexes do not alter energy regeneration. In this context, there's no sense in attack speed debuffs altering it either

**Comment by MullichWhitemane** [comment]
Tested this with Warrior's Thunder Clap on a Rogue which increases time between attacks by 20% (a weaponswing modifier, not haste), this issue did not occur.

**Comment by melezdev** [comment]
I said PVE in the title, @MullichWhitemane

**Comment by MullichWhitemane** [comment]
@melezdev The type of mechanic is the exact same though - if you believe there is a monster that uses any type of haste modifier debuff and you think it isn't working correctly, we'd appreciate a case-by-case report.

From the WoWHead link, it is clear that the NPC you linked as an example has a Haste modifier and not Swing Speed modifier:
<html>
<body>


Effect #3 | Apply Aura: Mod Melee, Ranged & Spell Haste by %Value: -30%PVP Multiplier: 1
-- | --



</body>
</html>

Therefore the modifier should affect energy regen.
