### ISSUE TITLE
LV85 Character Base Critical Chance Bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#2420]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is something wrong with base crit. Currently on the server my warrior has 0.49% crit with all items unequipped and unbuffed. My hunter friend has -1% crit. Since he is in the negative I had him test if its a visual bug and it is NOT, just autoattacking for 15-30minutes resulted in him not critting once. Relogging also doesn't solve this issue, I can only assume it is something to do with stat scaling to 85, but i'm no expert.
I do not have info about other classes except hunter happening, but i assume this might be present in others as well.
**How to reproduce:**
1. Have character (pref hunt) level 85
2. Unequip all gear and remove all buffs
3. Check crit chance and cry
4. Use attacks not influenced by talent crit increase (white attacks perhaps) on dummy over long period to test

**How it should work:**
Character crit chance should not be negative even when naked, instead should be equal to amount given by agility scaling ( as can be seen on warrior getting .5% from agi.
https://wowwiki-archive.fandom.com/wiki/Critical_strike

**Database links:**

![image](https://user-images.githubusercontent.com/79200711/224393798-72d27795-3036-4ff5-a2e4-5e1d0ebe9464.png)
![WoWScrnShot_031023_014919](https://user-images.githubusercontent.com/79200711/224393903-55697810-e5af-4112-800d-495d7c4b7ad5.jpg)
![WoWScrnShot_031023_014951](https://user-images.githubusercontent.com/79200711/224393982-c6e8dbff-87ab-411c-a6bf-b61520da36ad.jpg)

**Comment by MullichWhitemane** [comment]
Good find.

**Comment by Afgann** [comment]
fixed
