### ISSUE TITLE
Rogue extra CP generators (Ruthlesness & Seal Fate) currently not working.

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2421]
As described on the title, Ruthlesness doesnt ever give you 1 CP after a finisher and Seal fate doesn't ever give you an extra CP when you crit with one of your abilities. Issue has been on going for a day now.

**Comment by MullichWhitemane** [comment]
@Afgann I'm closing this and merging with another post that better details this issue. https://github.com/gamefreedomgit/Maelstrom/issues/2424

**Comment by Afgann** [comment]
fixed
