### ISSUE TITLE
[Warlock][Talent] Mana feed

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2422]
**Description:**
Mana feed demonology talent does not work as it is described in the tooltip.
Demon auto attack criticals (orange) do not currently proc this talent.
Demon special attack criticals (yellow) proc it, but the numbers are way off. I do not get 4% of my total mana (69533 * 0.04 =2781), but 11125 mana instead (4 times the amount)

**How to reproduce:**
Make a demon auto attack anything

**How it should work:**
From the description, only basic attacks (orange) criticals should generate mana. It makes sense considering that I often get multiple mana procs from a single felguard cleave.
The amount of mana gained should be 4 times lower.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=85175

**Comment by melezdev** [comment]
Okay cool, looks like this is not a bug then (if we take changelogs about 4X mana amount into account)

**Comment by UltraNix** [comment]
For felguard and Felhunter - yes
