### ISSUE TITLE
[Dungeon] The mechanar

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2423]
**Description:**
The mechanar instance cannot be proceeded. The lift is not present when you get close. It can be seen from 15 yards away, but then it disappears

**How to reproduce:**
Try to use the lift in the mechanar after the first boss

**How it should work:**
The lift can be used to proceed the instance

**Database links:**

![obraz](https://user-images.githubusercontent.com/61705382/224437619-144e5289-57b5-46d7-9048-47e29d975f9f.png)

**Comment by melezdev** [comment]
purpose: transmog runs

**Comment by PanJanuszek** [comment]
14.11.2023 no repro, elevator is unlocked after boss and 2x big adds. Visibility is ok
