### ISSUE TITLE
Feral Druid talent "Primal Fury" is not working

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#2424]
With the investment of 2 talent points the Feral Druid talent "Primal Fury" should give all abilities capable of generating a combo point a 100% chance to generate two combo points on critical hits.

Currently this is not working, critical hits only generate 1 combo point.

**Comment by VirtualReign** [comment]
A supposed fix to the issues ferals and rogues have been having was deployed as "Core/Spell: Fix spells that award combo points from finishing moves.".

I can't attest to the effectiveness of this regarding the rogue talent Ruthlessness (which has a chance of adding a combo point after a finishing move), but it did not actually fix the issue with Primal Fury for ferals and rogues are reporting that Seal Fate is still broken as well (both are talents that should guarantee an additional combo point on a critical strike with abilities that are combo point generators).

**Comment by MullichWhitemane** [comment]
Ruthlessness works as intended, but has a small visual error when proccing it when using a combo point spender with less than 5 combo point. 
![ruthlessness visual](https://user-images.githubusercontent.com/121984461/224484055-9bf7b604-5cbf-4617-b67d-401d7ff49a31.PNG)

Seal Fate at the moment correctly generates Combo Points on Crits, but on Mutilate, it is counting for both main hand and off hand crits, which means that if both crit, you generate 4 combo points with Mutilate, which, as far as I'm aware, shouldn't be a thing - even if both crit, it should only give three.

Primal Fury's Cat Form component does not work at all.

**Comment by VirtualReign** [comment]
Fixed, ty! Closing bug report.
