### ISSUE TITLE
Mob facing

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#2425]
Mob facing is currently all over the place.

Abilities like Shred and Backstab that require the user to be behind the enemy are practically unusable in high mobility fights due to this issue, which makes specs with those abilities severely dysfunctional.

If this is a hard to fix issue consider removing the facing requirement of those skills, at least in PvE.

**Comment by Jokieh** [comment]
#2400 
Same issue as mine.

**Comment by UltraNix** [comment]
Maybe more info? What fights specifically? What mobs/bosses?

**Comment by UltraNix** [comment]
@VirtualReign @Jokieh ?

**Comment by VirtualReign** [comment]
Hiya, sorry, hadn't been checking back here much.

The greatest offenders are mobs with scripted abilities during which they alter their facing, when they go back to normal they don't reset their facing properly.

As for examples, I had stopped running dungeons on my feral so I can't really provide an exhaustive list. Currently the biggest offender is Atramedes, where you sometimes need to stand in front of him with the tank to get your Shreds in.

**Comment by UltraNix** [comment]
Fixed.
