### ISSUE TITLE
[Rogue][Spell] Redirect + Bandit's guile

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2426]
**Description:**
Redirect does not correctly transfer Bandit's guile stacks to the other target. The damage is not increased against the new target and the stacks have to be acquired again.

**How to reproduce:**
Sinister strike 4 times, redirect to the other monster. Damage on the new target is not increased by bandit's guile.

**How it should work:**
After redirect, bandit's guile keeps functioning on the new target as it normally would.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=73981
https://cata-twinhead.twinstar.cz/?spell=84654

**Comment by MullichWhitemane** [comment]
Confirmed - tested by attempting to transfer all three Insight levels - casting SS 4 times will always reset it back to Shallow on the new target.

**Comment by melezdev** [comment]
works fine now
