### ISSUE TITLE
Copper Tube

### ISSUE THREAD

**Issue by Bradeyxz** [gamefreedomgit/Maelstrom#2427]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
No Engineering trainer teaches you copper tube.

**How to reproduce:**
Go to any engineering trainer

**How it should work:**
The engineering trainers should have the possibility to train copper tube

**Database links:**
https://www.wowhead.com/wotlk/spell=3924/copper-tube#changelog

**Comment by GMHiki** [comment]
![firefox_RAKx5YlWMB](https://user-images.githubusercontent.com/93480183/224570287-5c0efece-7d48-4f48-a0bb-a74295de9ea7.png)

**Comment by GMHiki** [comment]
![firefox_EGszUfr5eM](https://user-images.githubusercontent.com/93480183/224570456-d31eb4bc-672e-47c7-a546-14e03da9e907.png)
