### ISSUE TITLE
Jewelcrafting levelling

### ISSUE THREAD

**Issue by wantpizza** [gamefreedomgit/Maelstrom#2428]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Levelled Jewelcrafting to 300 and it didn't level to 450
**How to reproduce:**

**How it should work:**
SHould go from 300 to 450?

**Database links:**

**Comment by melezdev** [comment]
You most likely have a racial which improves jewelcrafting skill. Try getting 300 skill plus racial value
