### ISSUE TITLE
[Rogue][Glyph] Glyph of sinister strike

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2430]
**Description:**
Sinister strike stopped generating extra combo points. It used to work, but now I get no proc at all.

**How to reproduce:**
Sinister strike a camel 20 times

**How it should work:**
Every now and then two combo points should be generated

**Database links:**
https://cata-twinhead.twinstar.cz/?item=42972

**Comment by MullichWhitemane** [comment]
Confirmed - a sample pool size of 100 Sinister Strike casts yielded no extra combo points. At a 20% proc rate, the expected value should be roughly 20.

**Comment by melezdev** [comment]
Fixed in today's update
