### ISSUE TITLE
Guild Challenges

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#2431]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, Guild challenges do not extend the daily cap or go past it if capped as they should, making them pretty much useless.
We were at cap and guildies were doing dungeons. I checked the xp mark before they completed them and after; It was the same, did not increase even after waiting a few hours for lag.

**How to reproduce:**
1. Cap daily xp and check xp number
2. Do 1 heroic with guild for challenge
3. See xp not increasing the cap

**How it should work:**
Challenge xp should be independent of daily cap.
![WoWScrnShot_031123_141758](https://user-images.githubusercontent.com/79200711/224484496-c7ed5054-6a79-427b-bb60-a83c05f4ff13.jpg)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
