### ISSUE TITLE
Zapthrottle Mote Extractor

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Zapthrottle Mote extractor works to extract motes, but it does not show clouds on the minimap like it's supposed to.

**How to reproduce:**
Move close to a windy cloud in either Outland or Northrend with a Zapthrottle Mote Extractor in your inventory.

**How it should work:**
The windy clouds should appear on your minimap with a yellow dot, as a sort of tracking.

**Database links:**
https://www.wowhead.com/tbc/npc=24222/windy-cloud
https://www.wowhead.com/tbc/item=23821/zapthrottle-mote-extractor
https://imgur.com/a/7NAa6VK

**Comment by UltraNix** [comment]
Tested - works okay.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/669582dd-e2cc-424f-80a8-07b29ede8d18)
