### ISSUE TITLE
[Quest] Atonement

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2433]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing the two Hellfire quests, [In Search of Sedai](https://www.wowhead.com/quest=9390)
[Return to Obadei](https://www.wowhead.com/quest=9423), I should be able to pick up [Makuru's Vengeance](https://www.wowhead.com/quest=9424) from the NPC Makuru. However, after I handed in Return to Obadei, Makuru never offered the next quest in line. This quest is needed to obtain Atonement (https://www.wowhead.com/quest=9543/atonement), which is needed to eventually finish The Seer's Relic (https://www.wowhead.com/quest=9545/the-seers-relic) from which I was trying to get the Leggings of Telhamat (https://www.wowhead.com/item=25507/leggings-of-telhamat). The legging are a crucial part of my favourite transmog set, and it would suck to have quested all the way through Nagrand to never be able to complete the set.

**How to reproduce:**
Follow the questline as described above.

**How it should work:**
Makuru should offer "Makuru's Vengeance" (https://www.wowhead.com/quest=9424/makurus-vengeance), giving access to the rest of the quests.

**Database links:**

https://imgur.com/a/OGLvPab

**Comment by PanJanuszek** [comment]
works - 08.03.2024
