### ISSUE TITLE
[Quest] A Heap of Ethereals

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2434]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Trying another way of getting the legs that go with Telhamat Armor transmog set, but after starting on A Heap of Ethereals and having looted just one Zaxxis Insignia, the remaining insignias that dropped, just said "Already looted". Thus blocking me from proceeding with the quest line and making it impossible to finish my transmog set. I get that TBC isn't on your prio list, but I mean, could at least ONE of these quest lines work, since transmog is an actual part of the game in Cata.

**How to reproduce:**
Begin "A Heap of Ethereals" in Netherstorm and attempt to loot the ethereals just orth of Area 52.

**How it should work:**
The items should be lootable.

**Database links:**
https://www.wowhead.com/tbc/quest=10262/a-heap-of-ethereals
https://www.wowhead.com/tbc/item=29209/zaxxis-insignia
https://www.wowhead.com/tbc/item=30257/shattrath-leggings

**Comment by PanJanuszek** [comment]
fixed 07.03.2024
