### ISSUE TITLE
[NPC] Stonevault Wanderer

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2435]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
bugged loot of mob.

**How to reproduce:**
Zone: Badlands
NPC Name: Stonevault Wanderer
NPC ID: 46713
kill the mob it sometimes contains nothing but mostly it drops 3x Firebloom (so it has about 95% chance on drop this)

**How it should work:**
The NPC should be without loot.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=46713

**Comment by Afgann** [comment]
fixed
