### ISSUE TITLE
Eating/Drinking in PvP

### ISSUE THREAD

**Issue by hatethehitman** [gamefreedomgit/Maelstrom#2436]
I was inside of an Eye of The Storm BG yesterday when I noticed that having a dot on you and trying to regen by eating/drinking doesn't work the way it should as dot ticks stop you from regenerating and you have to spam your food in order to get to full HP with a dot on which is a waste and it should not work that way. Dots should not interfere with eating or drinking and should definitely not stop it.
Sadly I could not find any evidence to prove this but it is very common sense and it works that way on every single expansion/server. The community can back it up if needed.

**Comment by Afgann** [comment]
fixed
