### ISSUE TITLE
[Death Knight][Talent] Magic Suppression

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#2437]
**Description:**
Magic Suppression should be absorbing 100% of the incoming magic damage and convert it into a bulk amount of runic power. However, the number of runic power being generated is significantly lower than regular numbers. (E.g. Generating +2 runic power per spell).

**How to reproduce:**
Put 3/3 into the Magic Suppression talent and go into a duel with a magic caster class and use Anti-Magic Shell to absorb the damage.

**How it should work:**
The amount of runic power generated should be significantly higher than the current numbers which are too low.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=49611

**Comment by UltraNix** [comment]
Found the bug.

**Comment by clam119** [comment]
Apologies I've not been active on GitHub recently. I'm glad that you managed to find the bug, if you don't mind me asking - what exactly caused the numbers to be lower?

**Comment by UltraNix** [comment]
x10 missing multiplier

**Comment by clam119** [comment]
Didn't mean to close it 😂 I'm glad you managed to find it!

**Comment by UltraNix** [comment]
Fixed.
