### ISSUE TITLE
Blackrock Caverns Last boss bug

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2439]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you somehow manage to wipe at last boss and go at him again hes without adds called Shadow of Obsidius helping him.
Checked on normal difficulty.

**How to reproduce:**
Wipe 

**How it should work:**
Boss should spawn with adds which makes him use hes core mechanics.

**Database links:**
Video for confirmation: https://www.youtube.com/watch?v=nIpO6ncnTEs

https://www.wowhead.com/npc=40817/shadow-of-obsidius
https://www.wowhead.com/npc=39705/ascendant-lord-obsidius

**Comment by WhitemaneSylah** [comment]
note adds sometimes respawn - cause unknown

**Comment by UltraNix** [comment]
Fixed.
