### ISSUE TITLE
Preparing the mind: speaking truth to the Power. Killer spheres

### ISSUE THREAD

**Issue by LoadingCom** [gamefreedomgit/Maelstrom#2440]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

I do not know English well, so I used Google Translator, sorry for the inaccuracies in the text

**Description:**
Description: Tried to pass the quest "Preparing the mind: speaking truth to the Power"  After creating the first sphere could not answer the questions (the menu did not appear). Several times died and created 3 spheres
Looked at this quest on YouTube and realized that it does not work (probably because of the plugin 'br4')
Сreated a ticket GM, he completed me this quest, but the spheres still kill me and ask questions ( re-logging does not help)
I can't do anything because the spheres are killing me

UPD: This morning (probably after the server restart) the spheres disappeared

**How to reproduce:**
cancel the quest, die and spawn new spheres

**How it should work:**
I think the spheres should not remain after the quest has been completed

**Database links:**
screenshots: https://imgur.com/a/zfabAwv
https://www.wowhead.com/quest=25299/mental-training-speaking-the-truth-to-power

**Comment by UltraNix** [comment]
Fixed.
