### ISSUE TITLE
[Warlock][Spell] Hand of gul'dan

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2441]
**Description:**
Hand of gul'dan does not cause its aura (10% critical strike chance for demons) when metamorphosis is active. It works fine outside of metamorphosis.

A side effect of this is talent Aura of foreboding not rooting and stunning its targets.

Since metamorphosis is the cruical time for a demonology warlock, having your most basic source of damage / control not working in it really cripples the class.

**How to reproduce:**
Use metamorphosis + hand of gul'dan. Also try with extra talents (2/2  aura of foreboding)

**How it should work:**
Metamorphosis should not have any effect on this spell

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=71521
https://cata-twinhead.twinstar.cz/?spell=89604

**Comment by melezdev** [comment]
Looks like there's no aura at all - even the base aura that should increase demon's crit chance by 10%. Talent not working is probably just a side effect

**Comment by melezdev** [comment]
Bump, this is heavily impacting demonology warlock performance, @MullichWhitemane

**Comment by WhitemaneSylah** [comment]
Can you provide video evidence of this so we can assign a priority

**Comment by melezdev** [comment]
I won't, I don't have the setup to record videos and this is easily reproducible in under 5 minutes

**Comment by melezdev** [comment]
A video is really an overkill, this can be explained in two screenshots

![obraz](https://user-images.githubusercontent.com/61705382/227467314-45b1dc0a-76a5-462e-a558-60f43ebbe918.png)

![obraz](https://user-images.githubusercontent.com/61705382/227467349-d2b96e0e-d0e2-43d1-ab74-02b649f6cb1b.png)

**Comment by melezdev** [comment]
Mind explaining how is this low priority while this is high priority? https://github.com/gamefreedomgit/Maelstrom/issues/2466

Mage spell effect applies late - high
Warlock spell effect applies late - low

?

**Comment by WhitemaneSylah** [comment]
@melezdev  now that you've provided picture evidence I can put this to critical.  Thank you so much!

**Comment by UltraNix** [comment]
Fixed.
