### ISSUE TITLE
Absence world treasure chests

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2442]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in the world there are most missing chests, I made a dwarf to find treasures easily, but I found only one in Feralas that has 3 minutes respawn and 0% chance drop on [Book of Glyph Mastery]. I opened the chest many times maybe 50 times at least 

**IMPORTANT: Even though it looks like a minor issue it has a deeper impact on the whole game since there are so many missing glyphs since wotlk content is not visiting or in many cases not working properly, so there is a huge absence of glyphs.**

I was looking for it on live but had a look on PTR with same result as well.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=45912#contained-in-object
https://www.wowhead.com/object=207484/sturdy-treasure-chest

**Comment by UltraNix** [comment]
Fixed.
