### ISSUE TITLE
[NPC] Aeonaxx is not spawning

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2443]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am hunting aeonaxx several days and didn't find even his corpse, beside of NPCScan addon that is do a sound when rare mob is near to me.

I tried to find him on PTR as well with .respawn command but nothing happened I think he is disabled.

**Database links:**
https://www.wowhead.com/npc=50062/aeonaxx#comments
https://cata-twinhead.twinstar.cz/?npc=50062

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2662
Yes - he spawns.
