### ISSUE TITLE
[Mage] Re summoning mage pet does not reset freeze 

### ISSUE THREAD

**Issue by sassouiabd** [gamefreedomgit/Maelstrom#2444]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Re summoning the mage pet does not reset the coldown of freeze spell. 

**How to reproduce:**
https://www.twitch.tv/videos/1764000873
- Summon water elemental spell
- Use it's spell freeze
- Coldsnap
- Summon water elemental spell
- Freeze spell is on coldown

**How it should work:**
Re summoning the mage pet should reset the coldown of freeze spell. 
Check from 03:15 in the video below how it was on cataclysm, the freeze pet spell was on coldown he summons it back and the coldown is reseted (03:24)

https://www.warcraftmovies.com/fr/movieview.php?id=193691

**Comment by UltraNix** [comment]
Fixed.
