### ISSUE TITLE
Low level hunters are bugged 

### ISSUE THREAD

**Issue by huntersbugged** [gamefreedomgit/Maelstrom#2445]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
all low level hunters are bugged their pets are unkillabe and they 2 shot everyone, its much worse than it was on retail, every BG the hutner just sends his pets on people across the map and they cant be killed and one shot everyone

**How to reproduce:**

just take a look at all of the lower level BGs 
**How it should work:**
the pet shouldnt be one shotting people and they should be able to b killed, but they are literally immortal

**Database links:**

**Comment by WhitemaneSylah** [comment]
Pets stats scale with the player -  did you notice if the hunter had heirlooms at all?

**Comment by UltraNix** [comment]
#3592
