### ISSUE TITLE
The mist inst listening mobs not attackable

### ISSUE THREAD

**Issue by Kroetenmann** [gamefreedomgit/Maelstrom#2447]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
for the Quest. the mist isnt listening
https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening
the mobs are not attackable and you cant hit "at war" with the oracles.

**How to reproduce:**
Probably through starting the questchain in sholazar

**How it should work:**
mobs should be attackable

**Database links:**
https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening
https://www.wowhead.com/wotlk/npc=28109/mistwhisper-warrior

I know this isnt really priority, but still wanted to post.

**Comment by UltraNix** [comment]
#2031
