### ISSUE TITLE
[Talent][Paladin] Sanctuary 

### ISSUE THREAD

**Issue by Teddys-Rage** [gamefreedomgit/Maelstrom#2451]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the protection paladin talent tree
Am not able to learn the 2nd point in the talent 'Sanctuary'

**How to reproduce:**
Try selecting the 2nd point in sanctuary and press 'Learn'
The point resets back saying 1 talent point available and therefore not able to take the futher talents too

**How it should work:**
It should learn the talent and let me go ahead in the tree

**Database links:**

**Comment by WhitemaneSylah** [comment]
This should have been fixed now

**Comment by MestenoX** [comment]
Hi, I have the same problem. I can't add Sanctuary 2/3.
