### ISSUE TITLE
Teleporting whole bg to arena.

### ISSUE THREAD

**Issue by Tredaxik** [gamefreedomgit/Maelstrom#2452]
**Description:** If u challange some party to arena and u enter bg before they accept u can get leader in bg group, that means if they accept the arena after u enter the bg it teleports everyone into arena with u.

**How it should work:** It shouldnt teleport everyone into bg xD

![image](https://user-images.githubusercontent.com/127792306/224823874-bb39d77f-9647-4c60-a35c-fbff85bdecd6.png)

**Comment by WhitemaneSylah** [comment]
Interesting one,

can you provide replication instructions step by step,  what did you do / other people do exactly to cause this

**Comment by UltraNix** [comment]
No further info - closing.
