### ISSUE TITLE
Paladin Healing reduced while inside Battlegrounds

### ISSUE THREAD

**Issue by branrad** [gamefreedomgit/Maelstrom#2454]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Paladin healing appears to be roughly 10% lower than the tooltip says as soon as you enter a battleground. It applies to all spells such as Holy Light, Flash of Light, Divine light, and Word of Glory.

**How to reproduce:**
Use your healing abilities before you enter a battleground and compare them with the results of your healing abilities inside the battleground.

**How it should work:**
 
The healing outside battlegrounds should equal the same values once you are inside one. The images posted show my characters healing before and after entering a battleground to show the healing reduction. There is no change in my character's gears or buffs before or after.

**Database links:**

![Before BG](https://user-images.githubusercontent.com/93097763/224833047-2d4e4925-c750-4630-ba9a-d20b2e6b654a.PNG)
![Inside BG](https://user-images.githubusercontent.com/93097763/224834972-bec495d7-e829-416f-a0cc-28af9275a8b1.PNG)

**Comment by branrad** [comment]
I would also like to note that with my current gear and buffs, the tooltip for Holy Light says it should heal me for 5718, which is roughly the same amount it will averagely heal while outside of the battleground. The tooltip did not change while I was inside the battleground but still amounted to less healing than expected.

**Comment by Afgann** [comment]
fixed
