### ISSUE TITLE
hunter pets bugging out in combat

### ISSUE THREAD

**Issue by lolchomba** [gamefreedomgit/Maelstrom#2455]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** very often in combat pve/pvp my pet will be stuck standing still. i notice this particularly when my pet is attacking something and i whistle it to attack a different target-- it just wont move even when there is no form of CC on it. the solution i found is to whistle follow which unstucks the pet, afterwards im able to whistle it to attack a target. this is something that happens quite frequently but not always so im not sure what triggers it.

**How to reproduce:**not entirely sure, as i mentioned above, i notice it more often when i whistle my pet to switch targets. /petfollow unstucks the pet

**How it should work:** pet should not randomly get stuck in absence of any form of CC

**Database links:**

**Comment by WhitemaneSylah** [comment]
Might be an MMAP / VMAP issue.  I've seen examples of thi shappening when theirs a line of sight issue,  please provide more detail of what you were doing when this happened

**Comment by UltraNix** [comment]
#3749
