### ISSUE TITLE
Hunter - Running Flag w/ Camouflage 

### ISSUE THREAD

**Issue by SeraphTV** [gamefreedomgit/Maelstrom#2456]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While the Camouflage buff is active you are able to pick up the flag in WSG without breaking the buff. Based on what I can deduce you ARE targetable but you can't be hit by ranged attacks, only melee.

**How to reproduce:**
Enable/Have Buff Camouflage, Interact W/ PvP Flag. Camouflage Buff remains, People can target Me, But Can't Attack me with ranged(See Video Link)

**How it should work:**
Enable/Have Buff Camouflage, Interact With PvP Flag, Camouflage Buff is removed.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51753
Video Link of Recreating Bug : https://youtu.be/89sYEfFO0Ro

**Comment by MullichWhitemane** [comment]
The hunter will drop the flag once full stealth activates (aka when they stop moving). Every other type of stealth works correctly in relation to flags.

**Comment by Afgann** [comment]
fixed

**Comment by UltraNix** [comment]
Fixed.
