### ISSUE TITLE
Spinal Healing Injector

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2459]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Spinal Healing Injector enchant from Engineering occasionally does not reset cd outside of combat.
![WoWScrnShot_031323_163053](https://user-images.githubusercontent.com/57082188/224856326-74607344-0a47-460b-a326-734ddd32faca.jpg)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=82200
https://cata-twinhead.twinstar.cz/?spell=82184

**Comment by UltraNix** [comment]
Fixed.
