### ISSUE TITLE
Lycanthoth Vandal bugged movement, mobs flying after players.

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2460]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Lycanthoth Vandal in Mount Hyjal fly after you

**Database links:**
https://www.wowhead.com/npc=39445/lycanthoth-vandal
![WoWScrnShot_031423_015657](https://user-images.githubusercontent.com/122581454/224865331-ced311fa-43f0-4f1d-97af-e18fb2fddb9c.jpg)
![WoWScrnShot_031423_015701](https://user-images.githubusercontent.com/122581454/224865342-c8072b3f-307d-4591-ac90-1358a25489cd.jpg)

**Comment by Greywolf59** [comment]
Can confirm. Does nt happen all the time, but it does, like whne they climb the cage or stump first.

**Comment by UltraNix** [comment]
I cannot reproduce it.

**Comment by PanJanuszek** [comment]
Me either
