### ISSUE TITLE
Skinning on Cataclysm (450-525) has roughly 5% chance to skill up when it's orange.

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2462]
Once you reach Cataclysm, each time you use skinning on a viable target it has roughly 5% chance to skill up when it's orange.

According to multiple sources, depending on the proffesion, orange correlates to 100% or 90%+ chances of skill up. 

Worth to note yellow/green are also wrong and yellow has a way lower chance than the mentioned 5%.

Sources:

https://www.mmo-champion.com/threads/1133587-Orange-Colored-Task-Doesn-t-Mean-100-Chance-of-Skill-Up

https://www.wowhead.com/forums/topic/skill-level-percentages-141915

https://wowwiki-archive.fandom.com/wiki/Skinning

**Comment by UltraNix** [comment]
Fixed.
