### ISSUE TITLE
City tabards not giving rep

### ISSUE THREAD

**Issue by Naxxiel** [gamefreedomgit/Maelstrom#2464]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The city tabards doesnt give rep while you are doing dungens either by normal or using the RDF tool 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneSylah** [comment]
Tabard says only gives rep if dungeon is 85 (heroic)
