### ISSUE TITLE
[Quest] The Mist Isn't Listening - not working

### ISSUE THREAD

**Issue by Lucika77** [gamefreedomgit/Maelstrom#2465]
**Description:**
It's a kill quest, where you need to kill 12 Mistwhisper Gorloc. You can't kill them, even if you have Hated with The Oracles. Also you can't click At War option.

**How it should work:**
Normally you should be able to kill these mobs in order to continue the quest chain. Otherwise you can't choose between the reps and you can't get the egg for Green Proto-Drake mount from The Oracles (because you need to complete the whole quest chain).

**Database links:**
https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening
https://cata-twinhead.twinstar.cz/?quest=12538

**Comment by UltraNix** [comment]
#2031
