### ISSUE TITLE
Mage's Frostfire Bolt slow applies late.

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2466]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mage's Frostfire Bolt applies its slow ~1 second after damage hits.

**How to reproduce:**
Cast Frostfire Bolt on anything.

**How it should work:**
As damage lands slow should be applied, just as with Frostbolt.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=44614

**Comment by Afgann** [comment]
fixed
