### ISSUE TITLE
Heroic Leap No path available bug

### ISSUE THREAD

**Issue by adrnpvc17** [gamefreedomgit/Maelstrom#2468]
Heroic Leap on warriors can't be used sometimes, it always says no path available

**Comment by UltraNix** [comment]
@adrnpvc17 Please - more info here.

**Comment by xmrshoot** [comment]
confirm

**Comment by UltraNix** [comment]
Something more than "confirm"?

**Comment by UltraNix** [comment]
No further info - closing.
