### ISSUE TITLE
Who's top of the food chain now? Not working (goblin racial chain)

### ISSUE THREAD

**Issue by zenya13** [gamefreedomgit/Maelstrom#2472]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**Quest giver:**    Hobart Grapplehammer
**Quest:**    Who's top of the food chain now? (goblin racial chain)
**Zone:**    Pocket City, Lost Islands

**How to reproduce:**

Hobart doesn't give the quest .

**How it should work:**

Hobart should give the quest, then you have to kill sharks to obtain quest items, and give them to Greely.

**Database links:**

[https://www.wowhead.com/quest=24816/whos-top-of-the-food-chain-now](url)

**Comment by zenya13** [comment]
Sylah solved my problem adding the quest to my questlog. Thanks a lot Sylah. 
There are people who have the same bug as i did, hope this found a solution so they can continue their journey.

**Comment by hanahaki27** [comment]
Goblins simply become unplayable due to the inability to accept this quest.

**Comment by alexspew** [comment]
Should be resolved by now, if you still can't get the quest on leveling a goblin. Please assign me asap on the issue thanks!
