### ISSUE TITLE
Dragon's Breath disorient moves target dummies.

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2473]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dragon's Breath disorient moves target dummies.

**How to reproduce:**
Use Dragon's Breath on a target dummy.

**How it should work:**
They shouldn't move KEKW

**Database links:**

**Comment by Afgann** [comment]
fixed
