### ISSUE TITLE
Molten Armor Glyph not applying extra 2% Crit Chance

### ISSUE THREAD

**Issue by Trevorjl123** [gamefreedomgit/Maelstrom#2475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I was doing some math and it seemed like I was missing 2% crit which lined up a little perfectly with the added 2% crit bonus from the glyph and was wondering if either I'm doing my math all wrong or there is indeed a bug.

**How to reproduce:**

**How it should work:**
From what I understand every character get a base 5% Critical Strike Chance, Now having 3851 Intellect that would increase my Critical Strike Chance by 6.84% making the new total 11.84%. Now we add the Critical Strike Rating of 1309 which increases it by 7.30% making the new total 19.14%. Now we apply Molten Armor which with the glyph provides and additional 5% making the overall total of 24.14% but I am currently sitting at 22.14% with my Molten Armor on and the glyph applied. If i'm totally wrong just tell me I'm an idiot. Thanks!

**Database links:**

![Crit stuff](https://user-images.githubusercontent.com/73255261/225083704-4d6c3078-9a2a-44e6-9351-c0fde1d2807d.PNG)

**Comment by UltraNix** [comment]
Without glyph:
![WoWScrnShot_090123_152437](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9c8a057f-ab9b-4f6a-8f98-7221fbdd7ebe)

With glyph:
![WoWScrnShot_090123_152451](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/338b8aa1-12d6-4d2d-8447-db036512d648)

No bug here.
