### ISSUE TITLE
Halls of Origination - Anraphet encounter mini bosses counting as one continuous encounter 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2476]
When players engage the mini bosses for the anraphet encounter it will count as one contiunous encounter.  if the group wipes they will constnatly receive the "encounter is already in progress" error

Mobs in question are

Earth Warden
Air Warden
Water Warden 
Flame Warden.

If a group wipes on any of these they should reset and allow players to enter in normally.

**Comment by UltraNix** [comment]
Fixed.
