### ISSUE TITLE
[Hyjal] [Quest] Black Heart of Flame - sometimes undoable, blocking zone progression

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2477]
[Black Heart of Flame](https://www.wowhead.com/quest=25428/black-heart-of-flame) is undoable.
When player tries to use [Charred Branch](https://www.wowhead.com/item=53464/charred-branch) it says the player is in the wrong zone. A lead to this might be the fact that when I logged out and logged back in in Inferno zone, I was in Regrowth (post-event) zone instead and had to leave the area and return.
Additional Info: All the other quests in Inferno zone and around were doable and were handed in prior trying this quest. The fact thatt player has no other quest to anchor him 100% properly in Inferno phase might also play the role in this quest being undoable.
Be it as is, currently there is about dozen of stuck players in the zone and since it is the only zone for lvl 80-81 due to Vashj'ir not working, I would say this is a big issue atm.

**Comment by Greywolf59** [comment]
UPDATE: Got info from another palyer that the quest worked 2 hours ago (one hour before I wrote the report), so either it is recent issue or some conditions have to be met to be able to do it properly.

**Comment by Drevil-Dion** [comment]
Can confirm this is not working after killing him you are not able to loot Black Heart of Thol'embaar from his corpse 

[Screen Grab from Whitemane showing bags with item name in search to show not in bags  and loot window from npc](https://i.imgur.com/le71ZzH.jpeg)
[Footage of the quest from cata time may 2015](https://www.youtube.com/watch?v=bK1HjCDM_Cc)

**Comment by UltraNix** [comment]
@Drevil-Dion But you are already completed the quest - look at your quest log...

**Comment by Greywolf59** [comment]
I don't have any toon on which I can retest it soon. Plus I do not even have time to play at all lately, apologies.

**Comment by PanJanuszek** [comment]
Cannot reproduce
