### ISSUE TITLE
Heroic Leap

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#2478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Heroic Leap animation is incorrect.

**How to reproduce:**
-

**How it should work:**
It should perform the animation a bit faster and also actually make you leap further up into the air. Currently you just leap in a straight line forwards like 2yd in the air.

**Database links:**

Example clip: https://youtu.be/6zyrTlaDs-E?t=223

**Comment by UltraNix** [comment]
Fixed.
