### ISSUE TITLE
Area 52 Replica Vendors

### ISSUE THREAD

**Issue by WarriorAndy** [gamefreedomgit/Maelstrom#2480]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Vendors in area 52 sell me Horde replicas instead of Alliance ones, should be swapped

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

![WoWScrnShot_031423_210004](https://user-images.githubusercontent.com/127890794/225111018-23a0fbfe-85ab-4329-b242-c6198389587b.jpg)

**Comment by PanJanuszek** [comment]
cannot reproduce
