### ISSUE TITLE
Mobs not loading for the 5th time in a row

### ISSUE THREAD

**Issue by Paimon226** [gamefreedomgit/Maelstrom#2481]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

*classic bug, mobs not loading for the 5th time in a row in a dungeon, scarlet graveyard**

**go to a dungoen**

**mobs loading **

**Database links:**

![2023-03-14 (3)](https://user-images.githubusercontent.com/69484756/225114653-ec3429b0-d7d7-4c01-abb5-3ab46e707888.png)

**Comment by WhitemaneSylah** [comment]
This is an ID issue,  as you're not in a group you are most likely in an instance where the mobs are already dead
