### ISSUE TITLE
Warlock: Missing spells with hit cap

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#2483]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Getting misses even when hit capped. Makes the class feel wonky and do less damage than whats supposed to. I first noticed this when my immolate was dropping on single target as demo, while using hand of gul'dan on CD. Its not specific to hand of gul'dan tho, all spells(and maybe pets) are affected by this.

**How to reproduce:**
Do a heroic dungeon with the hit cap for dungeons. Watch out for misses

**How it should work:**
The spell hit cap for heroics(level 87 bosses) is supposed to be 8%. Im missing with 11.34%. This may also affect raid bosses after the lv 88 hit cap, but im not geared enough to test it on the boss training dummy.

**Database links:**

Im linking some screenshots of a spell breakdown from lord godfrey, the last boss i did today. here you can the the spells cast and spells hit. 

[https://ibb.co/k9k7YLg](url)

[https://ibb.co/4dzx9Mx](url)

[https://ibb.co/k2MTV8G](url)

**Comment by UltraNix** [comment]
You just showed links with no misses.

**Comment by UltraNix** [comment]
No further info - closing.
