### ISSUE TITLE
[Hyjal] [Quest] Children of Tortolla - autocomplete

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2484]
Player does not even have to take the quest [Children of Tortolla](https://www.wowhead.com/quest=25519/children-of-tortolla), it is automatically there and ready to hand in after player hands in [Tortolla Speaks](https://www.wowhead.com/quest=25510/tortolla-speaks). I don't understand why this is so since this quest worked absolutely fine on PTR.

**Comment by WhitemaneSylah** [comment]
We put this on auto complete because the fixes done on PTR were not ported correctly.
