### ISSUE TITLE
[General] [PvP???] Pets seem to get Stuck? Espacially noticed in Arena

### ISSUE THREAD

**Issue by Heroclassx** [gamefreedomgit/Maelstrom#2485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Pet gets randomly stuck and stops moving. Might happen after getting rooted since I was just recently facing a hunter and he AOE rooted everyone with Entrapment talent. It wont follow any commands like pet attack or pet follow for a period of time. Really crucial bug for pet classes.

**How to reproduce:** Main issue is I dont know how to reproduce it, I am recording currently some wargames and will post a clip off it happening as soon as I have one. It happens usually in every arena once or twice. 

**How it should work:** Your pet should not randomly get stuck at some random spot in the arena. 

**Database links:**

**Comment by MullichWhitemane** [comment]
Any news on this @Heroclassx?

**Comment by melezdev** [comment]
@MullichWhitemane my felguard got stuck in dalaran arena, in the center where the water torrent occurs. Of course there was no water yet, but he refused to move from there by attacking. I had to use petfollow to get him unstuck. As always, it's arena, stuff happen fast so there's a chance he was rooted by some effect.

**Comment by UltraNix** [comment]
#3749
