### ISSUE TITLE
[Racial] Perception

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2486]
Can someone more knowledgeable check Human Racial [Perception](https://cata-twinhead.twinstar.cz/?search=Perception)? Cause I have played Human on WotLK and I indeed seen the stealthed rogues and cats more easily and on this server I can't seen them stealthed at all.

Note: Original human, not racial switch.

**Comment by WhitemaneSylah** [comment]
Works fine,  range of detection is slightly increased by 3 yards
