### ISSUE TITLE
Mage Frostfire Bolt slow is slow to apply.

### ISSUE THREAD

**Issue by glaschu234** [gamefreedomgit/Maelstrom#2488]
](https://www.wowhead.com/wotlk/spell=51779/frostfire-bolt)

https://cata-twinhead.twinstar.cz/?spell=44614

Frostfire bolt has a delay until it applys the 70% slow, around 1.5 second. It should instantly apply the slow.

**Comment by WhitemaneSylah** [comment]
@Afgann  dup of #2466
