### ISSUE TITLE
Frost Mage Frostfire Orb is breaking CC. e.g. Sap

### ISSUE THREAD

**Issue by glaschu234** [gamefreedomgit/Maelstrom#2489]
(https://cata-twinhead.twinstar.cz/?spell=84714)

Frostfire Orb is breaking sap.

If an enemy is sapped, in a battle ground or arena, frostfire orb will break the sap.

It should interact the same as it does with polymorph, and not break the CC.

**Comment by Afgann** [comment]
fixed
