### ISSUE TITLE
Mirror Images is generally very buggy.

### ISSUE THREAD

**Issue by glaschu234** [gamefreedomgit/Maelstrom#2490]
Mage Mirror images is bugging alot, for example it will not stop attacking even if you tell it to and it will break polymorphs, saps, and rogues blind.
 
It should not attack players or mobs that are being CC

](https://cata-twinhead.twinstar.cz/?spell=55342)

**Comment by WhitemaneSylah** [comment]
need proof of this via video please

**Comment by UltraNix** [comment]
No further info - closing.
