### ISSUE TITLE
Shadow Dance is delayed.

### ISSUE THREAD

**Issue by glaschu234** [gamefreedomgit/Maelstrom#2491]
When shadow dance is used there is around a 1 sec delay before the action bar changes to dance bar.

The action bar should instantly change to shadow dance bar, it is very important for pvp.

(https://cata-twinhead.twinstar.cz/?spell=51713)

**Comment by WhitemaneSylah** [comment]
This was not rectified until later expansions.  Players overcome this with addons or macros.
