### ISSUE TITLE
Hunter skills and pet bugged

### ISSUE THREAD

**Issue by Wladczyni** [gamefreedomgit/Maelstrom#2496]
I noticed two bugs of my hunter when I reached level 85 and started encountering bosses. It happens everyday and on all bosses.
Hunter when using skills (for example Arcane Shot, Cobra Shot, Explosive Shot etc) during an encounter at least couple times CAN'T use/cast any of her skills, even if pressing them, she will only auto-attack. In order to be able to cast/use them again she needs to stop targetting the boss and then target it again. It happens at least couple times during the encounter and it should not be happening at all. It disrupts the gameplay drastically, as we know that all the seconds count for the stable DPS. 
I don't know what link to provide as this is a bug of a different nature. Hunter shouldn't be forced to stop targetting the boss and target it again to be able to use her skills normally. 

Second bug is about the hunter's pet. It often falls into textures, it often doesn't get dismissed or it doesn't listen to commands when it's called, it just stands in one place without moving.
 What it should be doing is being dismissed when spell is casted and it also should move and listen to commands when it's being called.

https://imgur.com/a/1f0VbjJ 
Here shown that pet isn't doing anything while being in combat.

I hope this issue witll be fixed ASAP, as this is unacceptable while encountering bosses especially during raids.

**Comment by MullichWhitemane** [comment]
@Wladczyni The next time you play, please record your gameplay because I'm unable to recreate this.

**Comment by Wladczyni** [comment]
Hi, I was finally able to get it recorded and posted on YouTube:

https://youtu.be/FkfdYgwDiPA

I showed the bug using target dummy. It shows how she can use her skills for a while during the encounter, then she can't use her skills again, stop target, target again, use skills and then again the same thing. Everything is on the video. I hope it gets fixed ASAP.

**Comment by Wladczyni** [comment]
Please review my reposne on GitHub regarding the bug.

czw., 16 mar 2023, 01:09 użytkownik MullichWhitemane <
***@***.***> napisał:
