### ISSUE TITLE
Cameo of Terrible Memories - nowhere seen in Valor Vendor

### ISSUE THREAD

**Issue by kyuhh** [gamefreedomgit/Maelstrom#2498]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Bis necklace missing from valor vendor in ogrimmar
http://cata-shoot.tauri.hu/?item=77091#sold-by

**How to reproduce:**

add it

**How it should work:**

add it

**Database links:**

http://cata-shoot.tauri.hu/?item=77091#sold-by

**Comment by WhitemaneSylah** [comment]
Added in patch 4.3.0.15005

It's not missing, we're not on that patch cycle yet.
