### ISSUE TITLE
[Raid][Boss] Blackwing's Lair - Nefarian

### ISSUE THREAD

**Issue by Massie323** [gamefreedomgit/Maelstrom#2505]
**Description:**
After speaking to Nefarius on his throne, he will aggro on the player and chase after him in his humanoid form without attacking them. The Encounter itself fails to start, as the exit gates remains open, and no adds spawning (nor will Nefarian ever descend as Dragon).
Additonally, only the player that started the encounter is put in combat.

**How to reproduce:**
Simply attempt to initiate Nefarian's encounter as normal and it will fail to start.

**How it should work:**
The exit gate should close, adds should begin to spawn and Nefarian in his humanoid form should cast Shadow Bolt Volley

**Database links:**
Humanoid Lord Victor Nefarius: https://cata-twinhead.twinstar.cz/?npc=10162
Dragonform Nefarian: https://cata-twinhead.twinstar.cz/?npc=11583

Chased by Humanoid Nef:
![Wow-64_I5MgmNkVwf](https://user-images.githubusercontent.com/57675820/225392314-8ca30ea3-487a-42ff-adf0-6806034d7e29.jpg)

![Wow-64_64If8jAVjs](https://user-images.githubusercontent.com/57675820/225392630-1497cb75-8b8b-43bc-b807-7637625f3420.jpg)

Exit open:
![Wow-64_C7MHIqpIpv](https://user-images.githubusercontent.com/57675820/225392497-6a599903-dacc-417b-8dcd-95b59858bc4d.png)

**Comment by UltraNix** [comment]
Fixed.
