### ISSUE TITLE
Scatter shot is breaking itself.

### ISSUE THREAD

**Issue by glaschu234** [gamefreedomgit/Maelstrom#2506]
Scatter shot is breaking on its own damage. 

When I scatter a player in pvp, the scatter will break its self or it will break from auto attack damage, this happens more often than not.

It should just CC them for 4 seconds and not break from its own damage and my auto attacks should stop when I scatter my target especially if I am using /stopattack in my macro. e.g. 

/stopattack
/stopcasting
/cast shatter shot

https://www.wowhead.com/spell=213691/scatter-shot

**Comment by WhitemaneSylah** [comment]
You need to add /stopattack 3 times for this to work.
