### ISSUE TITLE
[Quest][Item] Hellscream's Missive

### ISSUE THREAD

**Issue by Nhae15** [gamefreedomgit/Maelstrom#2507]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Killing "Jor'kil the Soulripper" drops "Hellscream's Missive", but when we click on it, we can't begin the quest. The thing is there are really important items for level 14  Twin Bracket.

**How to reproduce:**
Just make the "Hellscream's Missive" work so we can start the quest and get our item.

**How it should work:**
You should be able to start the quest, return it back and get the item
For my char i'd like "Silver Embroidered Cloak" if you can give it to me "Nhae"

**Database links:**
[https://cata-twinhead.twinstar.cz/?item=52675](url)

[https://cata-twinhead.twinstar.cz/?item=46318](url)

[https://cata-twinhead.twinstar.cz/?npc=32862](url)

**Comment by Pabloexodar** [comment]
@Afgann Please revert this back. This is not supposed to work until you have completed a certain quest chain. This is not blizzlike, . In retail cata, it would always drop but not be able to activate until a certain quest was completed.

**Comment by Pabloexodar** [comment]
@Nhae15 Bruh? Really? asking for something to be fixed that isn't broken
