### ISSUE TITLE
[Quest][NPC] Taragaman the Hungerer - Stone Guard Kurjack

### ISSUE THREAD

**Issue by Nhae15** [gamefreedomgit/Maelstrom#2508]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
"Taragaman the Hungerer" is a quest that you can start at level 13 in Ragefire Chasm. But, when you enter in the dungeon the quest isn't available. This is a very important quest for level 14 twink gear.

**How to reproduce:**
Just enable the quest from "Stone Guard Kurjack"

**How it should work:**
Start with "Stone Guard Kurjack"
0/1 Take Taragaman the Hungerer's heart.
End with "Stone Guard Kurjack"

**Database links:**
[https://cata-twinhead.twinstar.cz/?quest=26858](url)

Items:
[https://cata-twinhead.twinstar.cz/?item=66040](url)
[https://cata-twinhead.twinstar.cz/?item=66045](url)
[https://cata-twinhead.twinstar.cz/?item=66031](url)
[https://cata-twinhead.twinstar.cz/?item=66022](url)
[https://cata-twinhead.twinstar.cz/?item=49541](url)

**Comment by UltraNix** [comment]
#2271
