### ISSUE TITLE
[Quest] Counterattack!

### ISSUE THREAD

**Issue by Nhae15** [gamefreedomgit/Maelstrom#2509]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
"Counterattack!" is a quest that come after few other quests before. You must finish "Hezrul Bloodmark" then you should be able to do it.
It requires a level 11 char.

**How to reproduce:**
Enable the quest for level 14.

**How it should work:**
Require "Hezrul Bloodmark" quest ended
Start at "Regthar Deathgate"
Kill Kolkar centaur until Krom'zar appears, then slay him and take a Piece of Krom'zar's Banner.
End at "Regthar Deathgate"

**Database links:**
[https://cata-twinhead.twinstar.cz/?quest=4021](url)

**Comment by alexspew** [comment]
Hello! This has been fixed, should be live during the week! Thanks
