### ISSUE TITLE
[Quest][NPC] Who's Top of the Food Chain Now? - Hobart Grapplehammer

### ISSUE THREAD

**Issue by ComfyChrist** [gamefreedomgit/Maelstrom#2510]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This bug occurred on a level 7 Goblin Rogue. 

After completing the quest "The Biggest Egg Ever" on The Lost Isles. 
As soon as turn in for above quest was completed, no quest was accepted. 
The quest NPC who starts the bugged quest is 'Hobart Grapplehammer'.
Instead of offering you the quest to start, the NPC instead acts as the turn in for the quest, including having the text dialog 
of Assistant Greely.

Said quest is not in the quest log or quest journal.

**How to reproduce:**
Continue questing along the main quest chain for The Lost Isles until "The Biggest Egg Ever." is completed.

**How it should work:**
Quest should be available to accept from 'Hobart Grapplehammer' after completing "The Biggest Egg Ever." 
and turned in at Assistant Greely after collecting 5 shark parts from the sharks to the West.

**Database links:**
https://www.wowhead.com/quest=24744/the-biggest-egg-ever
https://www.wowhead.com/quest=24816/whos-top-of-the-food-chain-now

**Comment by alexspew** [comment]
Should be fixed as of few days ago, please reopen or make new ticket if it's still broken. Thanks!
