### ISSUE TITLE
[Item] Glyph of Death's Embrace

### ISSUE THREAD

**Issue by Mordekaiserx** [gamefreedomgit/Maelstrom#2511]
when i read deathcoil it say refund 20 runic power when used to heal . but when i heal myself with lichborn dosent refund anything .
![bugcoil](https://user-images.githubusercontent.com/127995027/225439166-5064f5aa-591e-48d9-aeeb-1b6b8a346009.png)

**Comment by Loken-coolguy** [comment]
https://www.wowhead.com/wotlk/item=43539/glyph-of-deaths-embrace

**Comment by UltraNix** [comment]
`Your Death Coil refunds $s1 Runic Power when used to heal an ALLIED minion.`
![image](https://user-images.githubusercontent.com/80540499/231719082-2b5ebfc1-2ef2-46d6-bb42-1c2621da9860.png)
