### ISSUE TITLE
[Mage][Talent] Impact

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#2512]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Talents "Impact" fire mage speciality, now work - have 10% chance to proc, regardless of the number of targets that were attacked.

**How to reproduce:**
Use aoe spell (no DoT) in 5-10 enemies

**How it should work:**
This talent "Impact" has a chance to be calculated for each target separately. Living bomb can cause this proc, when she end (Explode).
U can see it in video:
https://youtu.be/u7W75EXoev4?t=100
https://youtu.be/p667ZATEkPY?t=680
https://youtu.be/p667ZATEkPY?t=651
https://youtu.be/u7W75EXoev4?t=263
https://youtu.be/u7W75EXoev4?t=649

**Database links:**
https://wowpedia.fandom.com/wiki/Impact_(mage_talent)
https://wowpedia.fandom.com/wiki/Living_Bomb?so=search#History

**Comment by UltraNix** [comment]
Fixed.
