### ISSUE TITLE
[Profession][Item] Big Daddy

### ISSUE THREAD

**Issue by Genni123** [gamefreedomgit/Maelstrom#2513]
Description:

Certain bombs from engineering like "Big Daddy", are making casting spells impossible. For example, after I throw a bomb, then I can't cast "Fireball" and "Flamestrike" for some reason. It says "Spell is not ready yet". and its not working untill reload. 

How to reproduce:

Make sure that using items in combat won't bugg the game. 

How it should work:

Not like this.

Database links:
https://www.wowhead.com/item=63396/big-daddy

**Comment by Genni123** [comment]
Okay, one more thing. It seems that after throwing a Big Daddy, my Fireball and Flamestrike shares cooldown (:D) with Big Daddy. So after 1 minute, you can cast these spells without reloading.

**Comment by Afgann** [comment]
fixed
