### ISSUE TITLE
[Core][NPC] Corpses Moving

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2516]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://www.youtube.com/watch?v=J6S0gHxiqPE
Video is self explanatory

**Comment by Nightw4re** [comment]
it actually does a Defias Miner in Deadmines HC after 3rd boss as well, he use some bubble we kill him and he is still following and attacking us and we can't kill him again.

**Comment by UltraNix** [comment]
Already fixed.
