### ISSUE TITLE
Auction House is so slow

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2517]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I felt it yesterday and today morning any page is loading like 10+ sec I want to put Greater Cosmic Essence (wotlk item) into AH via auctionaator and it loads just one page but I was waiting maybe 20sec today.

**Comment by Nightw4re** [comment]
today it is like 1 minute to 1 page

**Comment by phchocean** [comment]
every morning open slow. someone so stupid put so many one peice things inside

**Comment by Loken-coolguy** [comment]
Should be good now
