### ISSUE TITLE
[Core][NPC] Aggro Delay

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when I taunt a mob from another player it took like up to 3seconds till mob goes on me(DK blood).

**How it should work:**
Aggro change should be immediately.

**Comment by UltraNix** [comment]
Already fixed.
