### ISSUE TITLE
[Death Knight][Spell] Rune of the Fallen Crusader

### ISSUE THREAD

**Issue by testdk123** [gamefreedomgit/Maelstrom#2519]
> > [@testdk123](https://github.com/testdk123) make a new report about https://www.wowhead.com/wotlk/ru/spell=53365/%D0%BD%D0%B5%D1%87%D0%B5%D1%81%D1%82%D0%B8%D0%B2%D0%B0%D1%8F-%D1%81%D0%B8%D0%BB%D0%B0#sounds healing does not have a critical effect https://forum.wowcircle.com/showthread.php?t=1103440&styleid=-1
https://github.com/gamefreedomgit/Maelstrom/issues/2254#issuecomment-1467599740

**Description:**
The healing portion of the Rune of the Fallen Crusader's spell proc should be able to crit, healing you for baseline 6% of your total hp instead of the normal 3%.

Proof it should be able to crit:
Classic WotLK log
https://classic.warcraftlogs.com/reports/KXvjAxN2r6hbVgMt#fight=11&type=healing&source=9&ability=53365&view=events
Retail 5.4.8 log
https://www.warcraftlogs.com/reports/JDkgQv3nbjZm4dWR#fight=22&type=healing&source=122&ability=53365&view=events

Unfortunately Cataclysm is the only expansion without any logs available for the moment. Couldn't find a decent Cata video that showcased it, but I'm sure they're around.

**Comment by pro100klass** [comment]
https://youtu.be/VdWeNNnbHWg?t=244 proof

**Comment by UltraNix** [comment]
Fixed.
