### ISSUE TITLE
[Item] Carved Ogre Idol & Shapeshift

### ISSUE THREAD

**Issue by gtfojulio** [gamefreedomgit/Maelstrom#2523]
Description: Carved Ogre Idol doesn't cloak(overwrite) shapeshift forms.

How to reproduce: When you use these items, they currently overwrite bear/cat form.

Items in question are:

- Savory Deviate Delight 
- Noggenfogger Elixir (Skeleton part)
- Iron Boot Flask

In the Case of using the Carved Ogre Idol it doesn't overwrite the bear/cat form.

How it should work : Carved Ogre Idol should be able to cloak(overwrite) shapeshift forms same way as Savory Deviate Delight, Iron Boot Flask and noggenfogger elixir that they do actually cloak(overwrite) shapeshift forms.

**Comment by BalanCV** [comment]
I think you have it the other way around. It's those 3 items that are bugged. Druid forms should override any other cosmetic. Doesn't make sense that you look like an ogre and clawing stuff, especially if you think how it gives you unfair advantage in PVP.

**Comment by UltraNix** [comment]
Intended.
