### ISSUE TITLE
[Death Knight][Spell] Gargoyle & /petfollow

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#2524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

1. http://wowroad.info/?spell=49206
2.Doesn't want to follow orders /petfollow
3. Must obey and follow the death knight (stop hitting the target)
[https://www.youtube.com/watch?v=bQKx...F152BF&index=2](https://www.youtube.com/watch?v=bQKxSBrudCA&list=PL0A530B197FF152BF&index=2) 8:07 8:21
4.10/10

**Comment by Hatepoem** [comment]
Note that ghoul must be alive for it to work.

**Comment by pro100klass** [comment]
fix pls

**Comment by pro100klass** [comment]
https://www.wowhead.com/zone=3702/blades-edge-arena
WHEN SUMMONING A GARGOYLE ON THE FIRST FLOOR, IT APPEARS ON THE SECOND FLOOR....
FIX PLS THIS FUCHING BUG

**Comment by UltraNix** [comment]
Fixed.

**Comment by pro100klass** [comment]
dont work
