### ISSUE TITLE
[Quests] Worgen starting area 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2526]
**How to reproduce:**
1. quest: after [finishing Push Them Out](https://cata-twinhead.twinstar.cz/?quest=24676) player was unable to pick up [Battle for Gilneas City](https://cata-twinhead.twinstar.cz/?quest=24904) because he abandoned battle for gilneas once so he was stuck and couldnt see anyone (different phase) also couldnt turn it in after completion 
2. quest: [Patriarch's Blessing](https://cata-twinhead.twinstar.cz/?quest=24679) players can't see the krennan aranas to turn in the quest (different phase)
3. quest: [Vengeance or Survival](https://cata-twinhead.twinstar.cz/?quest=24903) players can't see the npc to turn in the quest and take the next quest (different phase)
4. quest: [Slowing the Inevitable](https://cata-twinhead.twinstar.cz/?quest=24920) can't see the bat(different phase)
5. Quest: [Something`s Amiss](https://cata-twinhead.twinstar.cz/?quest=14091) players are unable to turn in the quest because npc is not visible and take the next quest(different phase)  (phase 2)
6. Quest: after finishing [Evacuate the Merchant Square](https://cata-twinhead.twinstar.cz/?quest=14098) players are unable to get the quest called [Royal Orders](https://cata-twinhead.twinstar.cz/?quest=14099)
7. Quest: after finishing quest [Last stand](https://cata-twinhead.twinstar.cz/?quest=14222) event is not triggered and working properly so players can't turn in the next quest called [Last Chance at Humanity](https://cata-twinhead.twinstar.cz/?quest=14375)
8. there is a serious issue with this area event marked with gps
![image](https://user-images.githubusercontent.com/36106057/225750336-8a37c61b-0f88-4dcc-98c3-9170a9e514f0.png)
![image](https://user-images.githubusercontent.com/36106057/225750363-a9643c1c-09c3-4e66-bc39-7836bdde81b6.png)

**How it should work:** npcs should be in their right phases and players should be able to finish those quests

**Comment by Zeehra** [comment]
Also, after finishing "The Rebel Lord's Arsenal" (https://cata-twinhead.twinstar.cz/11831?quest=14159), Lorna Crowley does not appear on the stairs (Or in fact, anywhere in Gilneas) to give the next quest, "From the Shadows" (https://www.wowhead.com/quest=14204/from-the-shadows).

**Comment by Zeehra** [comment]
And also, the Bloodfang Lurkers for "From the Shadows" don't spawn at all, nor is my bloodhound able to detect them. Guess I'll save worgen leveling for another day :')

**Comment by Zeehra** [comment]
Oh, I DID however see the bat while I was trying to locate Lorna Crowley after doing The Rebel Lord's Arsenal. So I guess it's in that phase.

**Comment by MrTide** [comment]
> 



> Oh, I DID however see the bat while I was trying to locate Lorna Crowley after doing The Rebel Lord's Arsenal. So I guess it's in that phase.

because i changed its phase temporarily it has issues for sure

**Comment by MrTide** [comment]
Two by sea 
players can't kill the undead to mount the catapults
