### ISSUE TITLE
pvp dagger with spell power

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#2527]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
pvp vendor with items for conquest points (from arena), does not have a dagger with spell power and intelligence

**How to reproduce:**
open trade

**How it should work:**
must be dagger with intelligence

**Database links:**

**Comment by Loken-coolguy** [comment]
Should be good now
