### ISSUE TITLE
[Core] /cancelqueuedspell Triggering  GCD

### ISSUE THREAD

**Issue by dejdus7** [gamefreedomgit/Maelstrom#2532]
/cancelqueuedspell is intermittently triggering a gcd while it should not.
To produce this I was casting Nourish>Regrowth>Nourish. There will be a point in-between the casts when a gcd is triggered but no casts are being started.

https://streamja.com/q1wl1

This is the macro i was using.

/cast [target=mouseover] Nourish
/cancelqueuedspell

**Comment by dejdus7** [comment]
https://streamja.com/PpzZG
This is not happening on Twinstar's Apollo realm.

**Comment by dejdus7** [comment]
This does have a drastic impact on gameplay especially for healers as preferable targets to cast on change during cast's duration.

**Comment by UltraNix** [comment]
Already fixed.

**Comment by dejdus7** [comment]
This is not fixed. The issue is still active. How can this be closed as fixed when it's not tested?
