### ISSUE TITLE
[Twilight Highlands] Low FPS above Thundermar

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2533]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My normal fps are about 100+ wherever I go but in that area fps gets super low. 
Its propably something wrong with those fire particles there.

Video for confirmartion:
https://www.youtube.com/watch?v=IO11ZVTsXHw

Diffrent part of the world fps
![WoWScrnShot_031723_062614](https://user-images.githubusercontent.com/122581454/225821685-90a5b399-7957-41ce-b12b-9afdf6f595e9.jpg)

**Comment by MrTide** [comment]
can't reproduce it
