### ISSUE TITLE
[Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by APTX4869s** [gamefreedomgit/Maelstrom#2534]
https://www.wowhead.com/quest=24594/the-purification-of-queldelar

**Description:**
after using [Tainted Quel'Delar] inside the sunwell, nothing happens

**How to reproduce:**
Do the " Battered hilt " quest chain till you reach The Purification of Quel'Delar

**How it should work:**
https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by Loken-coolguy** [comment]
Duplicate #2582

**Comment by ktm310** [comment]
Today, April 6, 2023, the error has not yet been corrected

**Comment by ktm310** [comment]
Today, April 6, 2023, the error has not yet been corrected
