### ISSUE TITLE
[Quest][NPC] Kor'kron Drop - Jon Jellyneck

### ISSUE THREAD

**Issue by noobaros** [gamefreedomgit/Maelstrom#2536]
Hey guys so here are the two quests that are currently bugged.
1.  [Kor'kron Drop] ( you cannot talk to Jon-Jon Jellyneck to give you a dialoge to pick a flight and get the squad
2.  [Patchwork Command] Patch ( The Turn-in NPC ) is nowhere to be found
3.  [Penetrating Their Defenses] You talk to Brann inside Halls of Origination to open the door, but you cannot proceed in talking him so he keeps moving to be able to complete this Quest, the dialoge is there but you cannot click on it

**Comment by Loken-coolguy** [comment]
Ignore #2 and #3 on this.

Quest: https://www.wowhead.com/quest=27491/korkron-drop
NPC: https://www.wowhead.com/npc=45947/jon-jon-jellyneck

**Comment by noobaros** [comment]
what do you mean? number 2 isnt there i just went and patch is nowhere to be found, unless he is in some other place than he is supposed to be
And Jon-Jon the first Quest is still not giving me the flight team

**Comment by MrTide** [comment]
duplicate
