### ISSUE TITLE
Nightmare quest makes freezes everytime the boss hp is like 30% or 40%

### ISSUE THREAD

**Issue by heikki2001** [gamefreedomgit/Maelstrom#2537]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Duplicate #2538
