### ISSUE TITLE
[Quest][NPC] Nightmare - Brain of Iso'rath

### ISSUE THREAD

**Issue by heikki2001** [gamefreedomgit/Maelstrom#2538]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi, this nightmare quest in the maw of madness, Twilight highlands, when i the boss hp reaches 30% or 40% the game freezes and it did this 3 times.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=27380/nightmare
NPC: https://www.wowhead.com/npc=47960/brain-of-isorath

**Comment by MrTide** [comment]
seems to be working fine
i recommend using full client of ours or if you still had issues make a ticket ingame
