### ISSUE TITLE
[Core][Spell] Moving While Stunned

### ISSUE THREAD

**Issue by Shatago** [gamefreedomgit/Maelstrom#2540]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.twitch.tv/videos/1767770536 - 00:50:10
When a target gets stunned, they rotate 180 degrees or are having their backs faced to away from you

**How to reproduce:**

stand behind a target, stun them

**How it should work:**
the target should stay in the exact position stunned, not move

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
