### ISSUE TITLE
[Pet][Vendor] Guild Page - Missing Vendor

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#2543]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Guild Page pet is supposed to be a portable guild vendor, showing the currently accessible items based on your guild level, reputation, and achievements. The pet currently cannot be interacted with to buy/sell any items.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=65362
https://cata-twinhead.twinstar.cz/?item=65361
https://cata-twinhead.twinstar.cz/?npc=49588#sells

**Comment by UltraNix** [comment]
Fixed.
