### ISSUE TITLE
Deadly poison at 5 stacks procs thrown weapon's poison, not other hand

### ISSUE THREAD

**Issue by Castcs** [gamefreedomgit/Maelstrom#2544]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
basically as title says, when deadly poison hits 5 stacks, it should start to also proc the main hand poison, but it's hitting with thrown weapon poison

**How to reproduce:**
put deadly poison on offhand. you can then put instant on main hand and wounding on thrown for example, and when deadly hits 5 stacks, it applies wounding poison.

**How it should work:**
"Once stacked to 5 times, each application of Deadly Poison also causes the poison on the Rogue's other weapon to apply."

**Database links:**
https://cata-twinhead.twinstar.cz/?item=2892#:~:text=Use%3A%20Coats%20a%20weapon%20with,times%20on%20a%20single%20target.

![image](https://user-images.githubusercontent.com/68359649/226079409-672ceb17-e810-42d8-9deb-489bde6cb1ae.png)

**Comment by Loken-coolguy** [comment]
User closed this for some reason, had another player report this is still an ongoing issue. Re-opening.
