### ISSUE TITLE
[Profession][Quest] Broken Serpent Figurine

### ISSUE THREAD

**Issue by andipro101** [gamefreedomgit/Maelstrom#2545]
**Description:**
Can't Turn in Broken Serpent Figurine when you go to click continue noting happens even if you have the mats required.

**How to reproduce:**
Get a Broken Serpent Figurine + mats and try to turn it in with 475+ jc 

**How it should work:**
you should be able to turn it in

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28775
https://www.wowhead.com/quest=28775/broken-serpent-figurine
![image](https://user-images.githubusercontent.com/41148760/226099823-368d17cd-65a9-4baf-9768-5ab0c9fc806a.png)
![image](https://user-images.githubusercontent.com/41148760/226099842-839b6a06-3e86-420f-b51f-ab41ee544153.png)

**Comment by UltraNix** [comment]
Fixed.
