### ISSUE TITLE
[Quest] The Mist Isn't Listening - Mistwhisper Warrior

### ISSUE THREAD

**Issue by Edgi1337** [gamefreedomgit/Maelstrom#2546]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest: The Mist Isn't Listening is bugged, mobs are unkillable and u cant finish quest chain

**How to reproduce:**
.

**How it should work:**
Mobs should be killable

**Database links:**

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening
NPC: https://www.wowhead.com/wotlk/npc=28109/mistwhisper-warrior

**Comment by alexspew** [comment]
Should be fixed soon. Thanks
