### ISSUE TITLE
[Battleground][Pet] Pet Damage Log Missing

### ISSUE THREAD

**Issue by unimaxxx** [gamefreedomgit/Maelstrom#2548]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pet dmg isnt included at bg dps meter = "fake" report couse of low dmg done=afk / even healing from spirit beasts are not included at dmg (like from loque/skoll special abilitie etc). Ive got like 3 times kicked becouse i had almost 0 dmg done when i was sending only pet to fight... at SS look at dmg done by other classes and then at other pet classes

**How to reproduce:**
reports

**How it should work:**
Pet's from BM hunter or Demo lock arent dps dealers? why u disabled dmg from them at bg?

**Database links:**

![skarga1](https://user-images.githubusercontent.com/128233441/226109691-fe5c21a1-7587-4cab-b037-3ccd2b2b0a89.png)

**Comment by UltraNix** [comment]
Fixed.
