### ISSUE TITLE
[Event][NPC][Loot] Kalu'ak Fishing Derby

### ISSUE THREAD

**Issue by Jokieh** [gamefreedomgit/Maelstrom#2549]
Description:

At Saturday 2 pm, Elder Clearwater should appear in Dalaran, near the fishing trainer and do a Northrend-wide announcement, that the event is started.
[Elder Clearwater](https://cata-twinhead.twinstar.cz/?npc=38294)

He's not there.

Also I'm not sure if it's tied, but I've tried to fish for around 30 minutes, only in fishing schools in Northrend and got 0 Pygmy Suckerfish.

It has a 65% drop rate from schools.
[Pygmy Suckerfish](https://cata-twinhead.twinstar.cz/?item=40199#fished-from-object)

I think the event fish is missing from the loot table also.
[Blacktip Shark](https://cata-twinhead.twinstar.cz/?item=50289#fished-from-object)

**Comment by MrTide** [comment]
can confirm event is not starting and elder is not appearing

**Comment by rhez** [comment]
The NPC does spawn, but still getting 0 Pygmy Suckerfish from schools. I do get some Pygmy Suckerfish from open water though.

**Comment by UltraNix** [comment]
Fixed.
