### ISSUE TITLE
[Dungeon][Boss] Lost City of the Tol'vir - Siamat

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2551]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

1. Siamat boss fight platform makes pets fell under the map
![image](https://user-images.githubusercontent.com/122581454/226112982-040c1027-2eb2-4a73-874e-35cfa25ffb24.png)

2.If you somehow manage to aggro mobs while using Wind thingy that gets you to boss platform mobs will be under you possibly making any ranged mobs attack you with boss.
![WoWScrnShot_031823_152210](https://user-images.githubusercontent.com/122581454/226113015-56840859-fd7a-4036-9449-a9f7761ecdc8.jpg)

3. Warriors cant use Heroic leap on platform
https://www.youtube.com/watch?v=vUhdtq4gEbk

4. Reporting gold sellers for spam makes your game crash
https://www.youtube.com/watch?v=_zxlwNNuLys

**Comment by Exorcista** [comment]
adding reference video showing a pet behavior in this platform: https://www.youtube.com/watch?v=AmNowZ73_gA

**Comment by whothatdog** [comment]
This kind of issue still exist.
the pet is fall through texture.

**Comment by UltraNix** [comment]
Already fixed.
