### ISSUE TITLE
[Quest][NPC] So Big, So Round... - Kor the Immovable

### ISSUE THREAD

**Issue by flennee** [gamefreedomgit/Maelstrom#2552]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I just got helpfrom a GM to fins where i ended my questline in Deepholm, so he gave me "Clingy". 
After i did that one i got "So Big, So Round..." from Pebble, where i am suppose to speak to Kor the Immovable. 
But I  Can't talk to him. I start attacking him if i right click him. My reputation with Therazane is Neutral. 
And Kor has a question mark above him indicating that the quest is done.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=26441/so-big-so-round
NPC: https://www.wowhead.com/npc=42469/kor-the-immovable

**Comment by bl2x14** [comment]
you should've go to reputations, and tick "at war" and then unmark it.

**Comment by varjla** [comment]
Confirmed today.

**Comment by varjla** [comment]
I must add to this bug, the NPC [Kor the Immovable](https://www.wowhead.com/npc=42469/kor-the-immovable) has a very strange hit box/box collider/mesh circle: you can only talk him if you are in his feet (inside them). Normally a very big NPC must have a very big area to interact with him, accordingly to his size.

**Comment by MrTide** [comment]
seems to be working fine

**Comment by gytckb** [comment]
> you should've go to reputations, and tick "at war" and then unmark it.

thanks,help me a lot

**Comment by gytckb** [comment]
上面说了，打开声望界面，找到对应声望，里面有个交战状态选项，前面的勾选点掉就行了，谢谢上面歪果仁
