### ISSUE TITLE
[Spell] On a Pale Horse, Da Voodoo Shuffle, Enigmatic Shadowspirit Diamond

### ISSUE THREAD

**Issue by bernymvp** [gamefreedomgit/Maelstrom#2553]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This gem, talent and race ability works fine with  slow effects, but its not working at root effects like Improved Harmstring, improved Cone of Cold. Its affects on 8 seconds duration roots like Frost Nova or Entagling Roots BUT its seems like the only On a Ple Horse work on the spells like this, so its not stackable(frost nova duration in pvp lasts 8 seconds, with ON a Pale Horse, Da Voodoo Shuffle, Engmatic Shadowspirit Diamond, it tooks 6 seconds, wich means is the only On a Pale Horse can affect on the 8 seconds roots or its just not stackable for 8 seconds roots.) So what we have: slow effects reduction works fine, short roots reduction like Improved Cone of Cold doesnt work, and 8 seconds root reduction works, but works wrong.
**How to reproduce:**
Use any slow effect like harmstring, crippline poison etc., on the player with On a Pale Horse, Da Voodoo Shuffle, Enigmatic Shadowspirit Diamond, same for the short/long duration roots.

**How it should work:**
All this effects should be stackable (30%/15%/10%) wich means, improved Cone of Cold should lasts only  1.35 seconds, Improved harmstring should lasts only 2.25 seconds, end effects like Frost Nova should lastsonly a  3.60 seconds. I did the same thing on wotlk classic, and on any other Cata server, so its should be blizzlike.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51986
https://cata-twinhead.twinstar.cz/?spell=58943
https://cata-twinhead.twinstar.cz/?item=52300

Please, fix it ASAP!

**Comment by UltraNix** [comment]
https://www.mmo-champion.com/threads/883254-DK-On-a-pale-horse
That spell does not affect roots (the same result is by reading DBC files)

**Comment by UltraNix** [comment]
No further info - closing.
