### ISSUE TITLE
[Quest]][NPC] Siege Tank Rescue - Fargo Flintlocke

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2558]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am not able to accept the quest https://www.wowhead.com/quest=27468/siege-tank-rescue from Fargo Flintlocke. Before I interact with him, he has a yellow exclamation mark, but when I interact with him, he acts as though I already have the quest, and as though he is waiting for me to complete the objective. However, the quest is not in my log.

**How to reproduce:**
Finish https://www.wowhead.com/quest=27433/shredderectomy - then attempt to carry on the quest line by taking Flintlocke's next quest.

**How it should work:**
The quest should appear as one I could accept, and not one I had already accepted, when in fact I haven't.

**Database links:**
https://imgur.com/a/AokVgiC

**Comment by MrTide** [comment]
fixed
