### ISSUE TITLE
[Quest][NPC] Do Me a Favor? - Razzeric

### ISSUE THREAD

**Issue by dreamk33per** [gamefreedomgit/Maelstrom#2559]
This quest can't be turned in because the NPC Razzeric is not there and you can't progress with the questline in the zone. I have done every prerequisite quests before this one. (horde side)

https://www.wowhead.com/quest=25505/do-me-a-favor

**Comment by Loken-coolguy** [comment]
NPC: https://www.wowhead.com/npc=40487/razzeric

**Comment by alexspew** [comment]
Unable to reproduce, if you still have issues with this quest, please let me know on discord thanks! (alex)

**Comment by Docpally** [comment]
Still an issue. NPC is missing and unable to hand in quest.

**Comment by dreamk33per** [comment]
It is obviously a phasing issue, but idk why since I've done all of the prerequisite quests. I dont get phased, NPC is missing and cant turn in the quest, hence can't continue the quest progress in the zone. I guess RIP Loremaster...

**Comment by alexspew** [comment]
Some info : NPC is spawned via some script server-side, unable to find static spawn (the one on the box)
