### ISSUE TITLE
[Arena] 123 Issue

### ISSUE THREAD

**Issue by Soundmanone** [gamefreedomgit/Maelstrom#2561]
**How to reproduce:**
Queue up arena it has a chance of happening
Sometimes arena 2 (so like the second bar on gladius) is registered as arena 3 even tho theres only 2 players in the arena so this could fuck up alot of players that have arena 123 macros for their spells

**How it should work:**
Arena 2 should be arena 2

**Database links:**

**Comment by UltraNix** [comment]
Still happens with solo arena teams?

**Comment by UltraNix** [comment]
No further info - closing.
