### ISSUE TITLE
[Core] RDF Not Re-Queueing Properly

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#2563]
There seems to be a new issue with the queue system.

Today I ran a couple of heroic dungeons where the tank in both cases left the group after not getting an item off the first boss.

In both cases when we re-queued and a new party was formed, we wouldn't get the confirmation message and would get removed from queue because we didn't accept the "invite". We tried to re-queue a few times but the result was always the same.

Edit: This wasn't just someone trolling, even when just me and a guildie were left in the party and reentered queue, the same thing happened.

**Comment by UltraNix** [comment]
#3637
