### ISSUE TITLE
Connection issues to server

### ISSUE THREAD

**Issue by Bustersword87** [gamefreedomgit/Maelstrom#2564]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to connect to server - I got a DC and then was unable to connect for 15 minutes, i finally got back in and it DC me again 5 minutes after, now i cannot connect to the server. IGN Timewarps. It is not my internet FYI :D

**How to reproduce:**

**How it should work:**
i should be able to connect :D

**Database links:**

**Comment by Loken-coolguy** [comment]
Please message in our #support channel in Discord, this is specifically for in-game bug reports.
