### ISSUE TITLE
[Warlock][Spell] Soulburn & Seed of Corruption/Drain Life

### ISSUE THREAD

**Issue by marekkys** [gamefreedomgit/Maelstrom#2566]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After using for example Soulburn: Drain life, the Soulburn effect stays on Seed of Corruption

**How to reproduce:**

**How it should work:**
After using Soulburn: Drain life the effect of it should disappear and you shouldn't be able to use it on Seed of corruption after 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
