### ISSUE TITLE
[Warlock][Spell] Soul Harvest - Incorrect Trigger

### ISSUE THREAD

**Issue by marekkys** [gamefreedomgit/Maelstrom#2567]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Soulharvest is proccing trinkets and enchants 

**How to reproduce:**

**How it should work:**
Soulharvest shouldn't proc trinkets and enchants 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by zsolti15a** [comment]
Hi! It still procs, Power Torrent (Attached the picture), Gale of Shadows - Trinket (from this I cannot give you pic, cuz I changed it yesterday). I'm sure there must be others that triggers too. 
![harvest](https://github.com/gamefreedomgit/Maelstrom/assets/61913518/595b8ce7-d7b8-4279-ac5f-b3a9443a89b0)

**Comment by UltraNix** [comment]
Fixed.
