### ISSUE TITLE
[Quest] Unknown Name?

### ISSUE THREAD

**Issue by Baycawn** [gamefreedomgit/Maelstrom#2570]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The questline for the Frenzyheart Tribe in Sholazar Basin seems to be bugged. I only got the first quest and no follow ups after that. I wanted to do this questline as it unlocks the Oracle tribe for reputation.

**How to reproduce:**

**How it should work:**
The quests should be one after the other very straightforward.

**Database links:**

**Comment by Loken-coolguy** [comment]
Needs more information, what quest? At least a name

**Comment by Baycawn** [comment]
Hi it is the entire questline. I am not sure what the quest name is as I
can't get it. But it's the quests with the Frenzyheart Tribe that
eventually unlocks the Oracles. Hope that helps.

**Comment by PanJanuszek** [comment]
All Oracle & Frenzyheart quest were refactored 15.01.2024
