### ISSUE TITLE
[Mage][Spell] Dragon's Breath - Disorient Effect

### ISSUE THREAD

**Issue by Shatago** [gamefreedomgit/Maelstrom#2571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When targets get db'd during movement, they seem to glitch in the direction they were moving and then port back towards/at the endof cc

**How to reproduce:**

DB a moving target

**How it should work:**

Db should make the target might slightly from where they were initially cc'd

**Database links:**

**Comment by Loken-coolguy** [comment]
Spell: https://www.wowhead.com/spell=31661/dragons-breath

**Comment by UltraNix** [comment]
Cannot reproduce it.
