### ISSUE TITLE
[Death Knight][Talent] Blade Barrier 

### ISSUE THREAD

**Issue by Gorgonic** [gamefreedomgit/Maelstrom#2572]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Cannot select more than 1/3 of Blade Barrier while blood spec selected as primary. If I select more than 1/3 and hit confirm, it resets all selections.

Try to select more than 1/3 Blade Barrier while blood spec in DK starting zone

Be able to select 2/3 or 3/3 without any problem

**Database links:**

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/231719585-130feef9-0d9b-4cef-b74f-c912af4f3228.png)
