### ISSUE TITLE
[Quest][Event] The Light of Dawn

### ISSUE THREAD

**Issue by Gorgonic** [gamefreedomgit/Maelstrom#2573]
Final quest The Light of Dawn is not starting properly - Spoke with Darien Mograine, Scourge mobs spawned at Light's Hope Chapel, no Argent Dawn mobs, no combat happening. 

Speak with Darien Mograine at Light's Hope Chapel to start The Light of Dawn.

Scourge should spawn in and charge Argent Dawn mobs at Light's Hope Chapel

**Database links:**

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/wotlk/quest=12801/the-light-of-dawn

**Comment by EdyGlockenspiel** [comment]
It started for me, and finished, though it is bugged beyond what I would think possible. First off, the named mobs are all level 88, they are supposed to each have their own level, between 73 and 80 I think. Next, there is just, a massive army of Rampaging Abominations and Flesh Behemoths just standing right at light's hope, even before the battle. Next, all of the Argent Dawn NPCs spawn in instantly once Darion reaches the Chapel. They are all supposed to already be there lined up before you even start the event. There is supposed to be a 5min wait between talking to Darion to start it and it actually starting, with a timer at the top of the screen. Lastly, there is supposed to be a counter, that shows Forces of the light and forces of the Lich King and each number goes down when the respective team loses an NPC in battle. All of this is just cosmetic as it still finished for me, but this is a really fun quest and it makes me sad to see it in such a state. :(

**Comment by UltraNix** [comment]
Fixed.
