### ISSUE TITLE
[Profession] Archaeology - Broken Dig

### ISSUE THREAD

**Issue by Hepticlol** [gamefreedomgit/Maelstrom#2574]
Hello
I am currently doing Archaeology and the digsite I am at has seemingly one broken dig.

From my understanding the digsite is called "Broken Commons Digsite" and is in Feralas.
I am getting a red marker, I move a centimeter and its red the other way, usually signilizing its up or down. There is no up or down to be accessed, atleast not up. Down however I can not for the life of me find the entrance if its there.

The map:
![image](https://user-images.githubusercontent.com/115653997/226392745-fc01c8ea-9f46-40dd-a008-860eec0c4bf8.png)

**Comment by UltraNix** [comment]
#4067
