### ISSUE TITLE
[Quest][NPC] Seige Tank Rescue - Fargo Flintlocke

### ISSUE THREAD

**Issue by jvy125** [gamefreedomgit/Maelstrom#2576]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can see the ! over Fargo Flinklocke's head, but he does not allow me to accept the quest Siege Tank Rescue, as it shows its grayed out. Same bug with quest " Small Comforts" but this time without the lag, just shows up gray.

**How to reproduce:**
I think I accepted it during server lag so now its not letting me accept.

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=27468/siege-tank-rescue
NPC: https://www.wowhead.com/npc=45168/fargo-flintlocke

**Comment by MrTide** [comment]
fixed
