### ISSUE TITLE
[Vendor] Krixel Pinchwhistle - Missing Set

### ISSUE THREAD

**Issue by Laxnacken** [gamefreedomgit/Maelstrom#2578]
**Description:**
the npc "Krixel Pinchwhistle" dosent sell the Replica field marshal set, I can only buy the Horde one as Alliance player.

**How to reproduce:**
i cant interact with the npc "Krixel Pinchwhistle".

**How it should work:**
I should be able to interact "Krixel Pinchwhistle".

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=23396

**Comment by Afgann** [comment]
fixed
