### ISSUE TITLE
[Raid][Boss] Black Temple - Shade of Akama

### ISSUE THREAD

**Issue by Massie323** [gamefreedomgit/Maelstrom#2579]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Inside Black Temple, you are supposed to talk to a stealthed Akama inside "The Refectory" in order to begin the encounter with the "Shade of Akama". Akama appears to be entirely missing however, or entirely invisible/stealthed in a way that is impossible for player characters to detect (i.e. Vanish level of improved stealth)

**How to reproduce:**
Enter the room of "Shade of Akama" and notice that Akama himself is nowhere to be found.

**How it should work:**
You are supposed to talk to Akama which would start the encounter.

**Database links:**
Akama: https://www.wowhead.com/tbc/npc=22990/akama

"Shade of Akama" (Hostile Boss): https://www.wowhead.com/tbc/npc=22841/shade-of-akama

![Wow-64_xI9HENXfV3](https://user-images.githubusercontent.com/57675820/226493911-72454990-ed26-4327-ac9c-521a6efb6496.jpg)

**Comment by Alandiel** [comment]
Akama for this fight is in wrong position. He's standing close to Illidan.

**Comment by PanJanuszek** [comment]
Should be in right place, however to see akama you have to clear previous bosses.
