### ISSUE TITLE
[Quest][NPC] Patchwork Command - Patch

### ISSUE THREAD

**Issue by 11thadthomas** [gamefreedomgit/Maelstrom#2581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://www.youtube.com/watch?v=1WT8Nd0YB4A

**Description:**
The quest Patchwork Command in Twillight higlands, there should be a npc where I am in the screenshot attached. However, the NPC is not there even after relogging and so forth. I have attached a video to how it should be.

**How to reproduce:**
Accepting the quest Patchwork Command and coming to where the quest says to go.

**How it should work:**
The npc's should be there to start the next questline.

**Database links:**
![image](https://user-images.githubusercontent.com/82884954/226498921-39dac43b-0a9c-4303-8d04-5a62f6f37ac6.png)

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=27576/patchwork-command
NPC: https://www.wowhead.com/npc=47492/patch

**Comment by MrTide** [comment]
duplicate
