### ISSUE TITLE
[Quest][NPC] The Purification of Quel'delar - Warden of the Sunwell

### ISSUE THREAD

**Issue by blurzyz** [gamefreedomgit/Maelstrom#2582]
(https://www.youtube.com/watch?v=FILdWp5AaaQ)

**Description:**
Step 12/13 of Quel'Delar questline that required you to enter instanced Sunwell to use quest item Tainted Quel'Delar in the Sunwell cannot be completed due to quest NPCs Warden of the Sunwell not teleporting you to that instance when interacted with.

**How to reproduce:**
Step 12/13 The Purification of Quel'Delar, simply talk to NPCs, prompt appears: "I will escort you into the sunwell when you're ready" option "I'm ready to enter the Sunwell" triggers nothing and dialogue closes.

**How it should work:**
With item in bags, and interaction selected, NPC should port you and take you to instanced Sunwell event

**Database links:**
![image](https://user-images.githubusercontent.com/128443098/226507184-be490c61-1832-47be-a03a-978c384524df.png)

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=24594/the-purification-of-queldelar

NPC: https://wotlk-twinhead.twinstar.cz/?npc=37523

**Comment by MrTide** [comment]
can confirm credit has issues (my original thought was that you dont get credit because you have to talk to warden while being in raid group otherwise he wont port you in) as far as i know you should not need to be in raid group to tp in for this quest.

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
