### ISSUE TITLE
[Warlock][Spell][NPC] Bane of Doom - Ebon Imp

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2583]
**Description:**
When bane of doom spawns a demon, that demon does not immediately attack the target but rather goes back to the warlock. If the warlock then starts attacking the target, the demon will aggro on it. So it seems that this demon attacks what warlock attacks, instead of the doomed target, which seems wrong. Surely it should start attacking the target immediately after spawning - since it only lasts a couple seconds its missing out on a lot of damage by running back and forth.

**How to reproduce:**
Bane of doom a target, wait for the demon to spawn. See what the demon does.

**How it should work:**
Demon should surely attack the baned target immediately. Can be seen here: https://www.youtube.com/watch?v=fHeKCbgsMZ4&t=76s

**Database links:**
https://www.wowhead.com/npc=50675/ebon-imp
https://www.wowhead.com/spell=43439/bane-of-doom

**Comment by melezdev** [comment]
It actually looks like snakes from snake trap have the same problem.

**Comment by UltraNix** [comment]
Fixed.
