### ISSUE TITLE
all my settings go to default when i exit game

### ISSUE THREAD

**Issue by thordian** [gamefreedomgit/Maelstrom#2584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I  open the program. the intro plays every time, then it ask me to agree to the policy again, when I log on all my setting are back to default.

**How to reproduce:**
Exit the game. and restart it

**How it should work:**
when I open the program it should just ask me to sign in and remember my settings

**Database links:**

**Comment by Loken-coolguy** [comment]
This is not a bug, you need to run your game as an administrator, or move the folder so it is not affected by user permission settings.
