### ISSUE TITLE
Pet no damage

### ISSUE THREAD

**Issue by elkheloufi** [gamefreedomgit/Maelstrom#2585]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When pet is attacking mobs, alot of numbers is getting shown but the mobs health is not moving at all.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Loken-coolguy** [comment]
There is not even close to enough information here, which pet? Which mobs? Unable to recreate, Pet attacks Mobs fine.
