### ISSUE TITLE
[Quest][Item] Without a Captain or Crew - Game Objects Missing

### ISSUE THREAD

**Issue by Paimon226** [gamefreedomgit/Maelstrom#2587]
[//]: https://www.wowhead.com/quest=26427/without-a-captain-or-crew

**Description: the quest, without captain or crew doesn't work. in the quest you need to bring the NPC 2 items a bottle of whiskey and a rope while a rope can be found the bottle of whiskey cannot and i checked other videos and websites where the bottle of whiskey can be found but sadly it's not on the ship so it doesn't work, needs to be fixed the quest is in deepholm**

**How to reproduce:**

**How it should work: you need to be able to find the bottle of whiskey to complete the quest, sadly u cannot**

**Database links:**

**Comment by WhitemaneSylah** [comment]
@alexspew  QA team says spawn time might be too high but items are there

**Comment by AvoelDev** [comment]
Can confirm the rope just spawns/respawns fine, however the bottle is missing for hours.

**Comment by MrTide** [comment]
fixed
