### ISSUE TITLE
 [Rogue][Spell] Killing Spree vs CC

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2588]
**Description:**
Killing spree does not interact correctly vs some CC abilities. I am immune to frost nova and chilled effects, but not to polymorph effect. This is not constrained to polymorph - I'm pretty sure blind works on killing spree performing rogues as well.

If frost nova was cast before starting killing spree, it is not dispelled.

**How to reproduce:**
Mage nova, cast polymorph, start killing spree at the end of polymorph cast. Observe the debuffs.

**How it should work:**
Killing spree should make you immune to all CC for 2.5 sec, while also removing all roots from you.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51690

**Comment by WhitemaneSylah** [comment]
Killing spree does not remove CCs or makes you immune to them.  This was changed in WoD.

**Comment by melezdev** [comment]
@WhitemaneSylah incorrect, what is your evidence? This changelog?

> [Patch 6.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_6.2.0) (23-Jun-2015): Killing Spree now only grants immunity to root and snare effects and the effect is now cancelled if the Rogue is affected by other crowd-control effects.

"Now **only** grants immunity to root and snare effects", suggesting it granted more before.

Also:

> [Patch 3.0.3](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.3) (04-Nov-2008): Instead of making the rogue untargetable, now causes all players to lose targeting on the rogue and the rogue to be unstoppable during its duration.

Unstoppable is pretty much what bladestorm does in wow. If it isn't enough for you, you can go read comments from patch 3.x.x on wowhead as I did, and you will see people explaining that rogue can't be targetted or CCed. Here's a link to one: https://www.wowhead.com/spell=51690/killing-spree#comments:id=924178

Please reopen or post more convincing evidence.

**Comment by bonfax4** [comment]
@UltraNix @Sketish   This issue needs a reopen.  But tested it and the polymorph goes through but it break close to instant during the cast even tho killing spree should make me immune.  Found retail video showing polymorph and frost nova being immune during killing spree. Not sure about losing target or becoming untargetteable unless polymorph still goes through if you lose target but you can also see the dk attempting to cast chains of ice in the video below (Possible he's using a target arena macro and they could still work ).

https://youtu.be/X-e89xckWT8?t=133 Slow the video down to 0.5 secs and look at his floating text. Mage starts castings poly and rogue presses killing spree into a poly immune followed by a frost nova immune and a chains of ice immune ( animation goes through without the slow  ).

**Comment by bonfax4** [comment]
Tested with fear, attacks still go through but i keep the fear until it finishes and it resumes lol

**Comment by UltraNix** [comment]
Fixed.
