### ISSUE TITLE
[Quest][NPC] Earthmender Torlok - The Hand of Gul'dan & Enraged Spirits of Fire and Earth

### ISSUE THREAD

**Issue by Harraiga** [gamefreedomgit/Maelstrom#2589]
Description:
In the Valley of the Ghost Moon, there is a quest chain that begins with the quest "The Hand of Gul'dan", gives the quest "Earthmender Splinthoof". I took the quest, then flew to the necessary NPC (Earthmender Torlok), handed it over, and that's it! The chain doesn't continue, he just doesn't have a new quest. 

How to reproduce:
Pass the first quest "The Hand of Gul'dan" in the storyline and Earthmender Torlok and it will not give the next one.

How it should work:
Just hand over the Earthmender Torlok task. Then get the next task "Enraged Spirits of Fire and Earth", from him.

Database links:
https://www.wowhead.com/quest=10681/the-hand-of-guldan

**Comment by Loken-coolguy** [comment]
Hand https://www.wowhead.com/quest=10681/the-hand-of-guldan into https://www.wowhead.com/npc=21024/earthmender-torlok and he does not give the next quest in the chain, https://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth

**Comment by alexspew** [comment]
Fixed

**Comment by Lilithra1** [comment]
This is still bugged, Earthmender Torlok does not give the next quest in the chain.
