### ISSUE TITLE
[NPC] Large NPCs Hitbox Incorrect

### ISSUE THREAD

**Issue by nichlasmm** [gamefreedomgit/Maelstrom#2590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Big mobs have wrong hitbox

**How to reproduce:**

**How it should work:**
The mobs have a circle under their feet. That's the hitbox radius, and on most(If not all) big mobs u have to move very close.

**Database links:**

**Comment by Loken-coolguy** [comment]
Can you give some examples?

**Comment by UltraNix** [comment]
No further info - closing.
