### ISSUE TITLE
[Raid][Boss] Tempest Keep - Kael'thas

### ISSUE THREAD

**Issue by CXPE1** [gamefreedomgit/Maelstrom#2591]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Last boss fight engages for full 10 seconds, when the first add comes and dies rest of the fight freezes and leaves you combat bugged. Other bosses and trash mobs work perfect exept last boss, the dialogue stops after the first add is killed and doesnt countinuo and after hearstoning or using mage port you cant go back inside bcs there is still encounter ongoing.

**How to reproduce:**

**How it should work:**
It should work that after you kill one add the other attack you until you kill every add, then their weapons attack you untill you kill them, then after you kill every wepon u engage all adds at once and after beating them you engage kael thas.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
