### ISSUE TITLE
[Quest][Item] Abuse of Power - Cudgel of Discipline

### ISSUE THREAD

**Issue by Nanab8** [gamefreedomgit/Maelstrom#2592]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**So the quests wants you to disguise as part of that orc group in Burning Steppes and kill 5 Blackrock Sergeants using the Blackrock Cudgel of Discipline but when I kill them it doesnt count towards the amount of kills needed to finish the quest, once you hit them they try to look trough your disguise so you have to kill them fast but even when doing that it still doesn't work not even when you take off your disguise and kill them when they are an "enemy" npc
SIDENOTE: after you kill them with the quest item they then respawn with just 1 hp, tried killing the ones that were full hp and still didnt count but I feel like that bug is still related to this quest.

**How to reproduce:**It's part of the questchain from Colonel Troteman, you get a disguise and eventually get a "Blackrock Cudgel of Discipline" and go to Blackrock Stronghold to kill the Blackrock Sergeants. When you get close to them, hit them with the quest item and see that it doesnt count the kills in any way.

**How it should work:**You should just hit them with the Blackrock Cudgel of Discipline(quest item) and kill 5 of Blackrock Sergeants wihtout taking off your disguise.

**Database links:**https://www.wowhead.com/quest=28279/abuse-of-power#comments

**Comment by alexspew** [comment]
Fixed.
