### ISSUE TITLE
[Quest][NPC] By the Light of the Stars - Harrison Jones

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2593]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quests is called "By the Light of the Stars" and after i found all quest items "Suspended Starlight" and gave them to Harrison Jones he did nothing and i dont have any quests for him anymore but according to this video
https://www.youtube.com/watch?v=y5RR58gNfdc&t=1s he should throw a staff at obelisk and be able to give me next mission

**Database links:**
https://www.wowhead.com/quest=27549/by-the-light-of-the-stars

**Comment by Nenze** [comment]
I think i have a talent for bugs xD
Not sure what you guys did with this quest, I`ve finished this quest thanks to GM few days ago and now I was in stormwind like 30min ago log out and just log back again to find myself in quest area in ULDUM XD 0.0 having this quest AGAIN XD 0.0 
time travel is real xD

![WoWScrnShot_032723_223818](https://user-images.githubusercontent.com/122581454/228061340-7e9bd080-54d3-4078-9460-f042df6244ed.jpg)
![WoWScrnShot_032723_223825](https://user-images.githubusercontent.com/122581454/228061402-64d0ff0c-1dfb-4b04-953b-9dd9b142a751.jpg)
![WoWScrnShot_032723_223837](https://user-images.githubusercontent.com/122581454/228061439-9157e411-7934-4c62-a3fd-8dbcff04e54b.jpg)

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/229100636-6082d989-2faa-49e0-bb00-8029b6001df4.png)
Just completed the quest and I'm able to get the next quest.

**Comment by UltraNix** [comment]
No further info - closing.
