### ISSUE TITLE
[Pet][Spell] Avoidance & PVP

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2594]
**Description:**
Pet avoidance works against player pets and minions. The most problematic part of this is felguard, which has a lot of AOE abilities. Currently, his damage against pets with avoidance is very weak.

**How to reproduce:**
Use felstorm against a pet with avoidance

**How it should work:**
Obviously avoidance is meant for pve. It makes no sense for it to work in pvp

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=32233

**Comment by UltraNix** [comment]
Fixed.
