### ISSUE TITLE
[Death Knight][Spell] Scourge Strike (Shadow)

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2595]
The shadow part of Scourge Strike seems to be doing way more damage than intended. Not going into some deep math, in a character with 35% increased shadow damage from mastery and taking in count 3 diseases ( FF, BP, EP) with glyph of scourge strike, the damage should be dealing roughly 102% of the physical portion, while here it is doing between 122 to 124% according to my numbers. 

SS attached from the encounter itself on Whitemane:
![image](https://user-images.githubusercontent.com/127544286/226750155-7de6688e-9857-4bab-9bd4-e13caa7811de.png)

Links from original retail sources with MSBT that can differentiate between physical and shadow portion, showing shadow portion doing roughly the same amount of damage as physical SS. 
https://www.youtube.com/watch?v=OVrrOdMjPeg&ab_channel=Afends

https://www.youtube.com/watch?v=u8zcxHaFGHI&ab_channel=ErupTV

https://www.youtube.com/watch?v=VdWeNNnbHWg&ab_channel=RefinedDreadmaul

**Comment by Klosterbro** [comment]
It is true, i was actually doing the math and the video Vezax69 provide was from DS gear and might also BiS on top of it doing less than it was in Whitemane/Maelstorm currently. While here on Whitemane/Maelstorm with a pre-bis even lower then a pre-bis. Unholy dk is just doing insane damage. Here for example the image shown from details, that scourge strike (shadow) was doing a 1 mill dmg in a BH 18 on a 4 min 15 sec fight. 
![image](https://user-images.githubusercontent.com/127820418/226756722-7b7bf5b7-7127-423f-b324-4deae5b0e33f.png)

**Comment by rade200** [comment]
You also have to take in account 25% dampening and how much mastery he has in this videos in my opinion.

**Comment by Vezax69** [comment]
''You also have to take in account 25% dampening and how much mastery he has in this videos in my opinion.''
Damage dampening is not a factor, if SS physical does more/less damage that also affects the shadow damage. Gotta count it as a radious, what is wrong here is the radious.
As for mastery, that's a point already taken into account, my dk was a 335 ilvl char w/o any reforged gear and had +35% shadow damage from mastery. That is way below any DK that was doing DS heroic back then, at the very endgame of the expansion.

**Comment by UltraNix** [comment]
3 diseases, means 3 x 18 = 54%
54 x 1.35 (mastery) = 72.9
72.9 x 1.3 (glyph of scorge strike) = 94.77
94.77 x 1.08 (Ebon Plague) = 102
Is that correct @Vezax69 ?

**Comment by UltraNix** [comment]
@testdk123 Yep - it takes 30% instead of 8% bonus.

**Comment by Vezax69** [comment]
> 3 diseases, means 3 x 18 = 54% 54 x 1.35 (mastery) = 72.9 72.9 x 1.3 (glyph of scorge strike) = 94.77 94.77 x 1.08 (Ebon Plague) = 102% of physical Is that correct @Vezax69 ?
It is correct taking in count the multipliers add up multiplicatively and not aditively.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Vezax69** [comment]
Did TOT4W and I've been checking SS damage, went from overtuned to undertuned with this fix. 
Current state atm (38% mastery DK): 
![image](https://user-images.githubusercontent.com/127544286/227682221-d4833358-0866-47a2-8e0b-25822a731a9c.png)

Opening new issue. Went from being 24% above SS physical to being 25% below SS physical.

**Comment by UltraNix** [comment]
2 DOTs with 29% mastery:
![WoWScrnShot_032723_143849](https://user-images.githubusercontent.com/80540499/227943189-ef70b249-1f9e-40e5-a336-cd9ac669dd3a.jpg)

3 DOTs with 29% mastery:
![WoWScrnShot_032723_143909](https://user-images.githubusercontent.com/80540499/227943219-6ae842ca-8bde-4b23-98e5-60d0ebd618b2.jpg)
For me - everything's here.

**Comment by UltraNix** [comment]
And don't compare with you overall damage done on raid, as there too many factors affecting these, eg. diseases count on your target.

**Comment by Vezax69** [comment]
''And don't compare with you overall damage done on raid, as there too many factors affecting these, eg. diseases count on your target.''
It's one of the things it passed through my mind, not really on the diseases since it should only count DK diseases which are basically 3 and should be up at all times for when you wanna SS, but regarding partial resists and stuff.
Went for a couple quick dummy runs and the difference was there, real and tangible, in the same way as on TO4W. Even checking on combat log too for partial resists. 
Needless to say, just one day after I wrote that second report SS was working just fine as we have agreed on the formula above.
