### ISSUE TITLE
[Druid][Talent] Nurturing Instinct Scaling

### ISSUE THREAD

**Issue by EspeonPam** [gamefreedomgit/Maelstrom#2596]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
![WoWScrnShot_032223_003222](https://user-images.githubusercontent.com/128550467/226769745-6b26ce12-841f-4b79-9b26-6b227da3cf0a.jpg)

**Description:**
After putting 2 talents points in Nurturing Instinct I don't heal myselft as it should work.

**How to reproduce:**
Put 2 talent points on Nurturing Instinct and try to heal yourself with any spell.

**How it should work:**
It should scale your healing spells with 100% of your agility + 20% healing done to you while in Cat form

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=33873

**Comment by UltraNix** [comment]
Tested - works okay.
