### ISSUE TITLE
[Quest][Vehicle] Pirate Accuracy Increasing - Vehicle Spell Doesn't Work

### ISSUE THREAD

**Issue by choppsz** [gamefreedomgit/Maelstrom#2597]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pirate Accuracy Increasing in Thousand Needles, the boat quest where you have to put out fires, the boat is stuck and you can still get in it but the ability to put out the fires doesn't put out the fires.
![WoWScrnShot_032223_010201](https://user-images.githubusercontent.com/128557981/226775165-1435cc22-d425-466c-9a20-03668839e042.jpg)

**How it should work:**
The boat should be sailing itself around Fizzle and Pozzik's Speedbarge while the player uses the ability to put out the fires.

**Database links:**
https://www.wowhead.com/quest=25533/pirate-accuracy-increasing

**Comment by alexspew** [comment]
Fixed, thanks!
