### ISSUE TITLE
[Dungeon][Boss][Spell] Deadmines - Foe Reaper 5000 - Heroic Leap Breaks Harvest

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2598]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Foe Reaper 5000 can bug while he uses Harvest ability.
If you are a warrior or propably any class with something similar to Warriors Heroic Leap and you will use it while running away before he casts "Harvest" you can bug him as you can see in video.
(But im not 100% sure if it will bug out if you simply use Heroic leap cuz as you can see in video ive casted my heroic leap at the wall so maybe he was going towards the wall cuz he didint reach the end path of his ability or something
tho ability parciles showed before wall so idk)

https://www.youtube.com/watch?v=9Z_6F099G34

**Database links:**
https://www.wowhead.com/npc=43778/foe-reaper-5000

**Comment by WhitemaneSylah** [comment]
@UltraNix  QA team says this one should be fixed,  can close when ready

**Comment by UltraNix** [comment]
Fixed.
