### ISSUE TITLE
[Dungeon][Core] Throne of the Tides - Revive to Elwynn Forest

### ISSUE THREAD

**Issue by sPyRRu** [gamefreedomgit/Maelstrom#2601]
So i was doing a random dungeon earlier, it happened to be Throne of the Tides.
After we wiped on 1st boss i realized that i couldn't walk past the dungeon portal..however my char got alive when trying to
I got killed by a horde and when i released i got sent to Elwynn Forest graveyard..

**Comment by Loken-coolguy** [comment]
Custom solution may be required for this, user was sent to Elwynn because Vashj'ir is closed.

**Comment by UltraNix** [comment]
Fixed.
