### ISSUE TITLE
[Quest][NPC] The Pit of Scales - Crocodiles

### ISSUE THREAD

**Issue by sPyRRu** [gamefreedomgit/Maelstrom#2602]

**Comment by Loken-coolguy** [comment]
The little crocs in the pit are invisible and untargetable.. really frustrating

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=27738/the-pit-of-scales

Blizzlike bug (https://www.wowhead.com/quest=27738/the-pit-of-scales#comments:id=1586791) but let's fix this anyways.
