### ISSUE TITLE
[Quest][NPC] Burnin' at Both Ends - Fargo Flintlocke

### ISSUE THREAD

**Issue by Thuleyt** [gamefreedomgit/Maelstrom#2604]
Quest: 'Burnin' at Both ends' not working, NPC Fargo Flintlocke isnt spawned so can't turn in.

**Comment by Loken-coolguy** [comment]
Quest: https://www.wowhead.com/quest=28597/burnin-at-both-ends
NPC: https://www.wowhead.com/npc=49020/fargo-flintlocke

**Comment by UltraNix** [comment]
Fixed.
