### ISSUE TITLE
[Arena] Pet Summon Cooldown

### ISSUE THREAD

**Issue by UwUTide** [gamefreedomgit/Maelstrom#2605]
Pet summon cooldown in arena preparation room doesn't reset, for e.g. dk ghoul has 2 minutes cooldown, gates open in approximately 40 seconds. So, if a player were to use death pact at the start it leaves them without a ghoul for +/- a minute or so which is a pretty important part of the unholy specialization. Please fix.

**Comment by UltraNix** [comment]
But cooldowns are reset once you enter arena, not when gates are opened.
@UwUTide Do you have any source saying that the pet should not be sacrificied while under Arena Preparation?
