### ISSUE TITLE
[Dungeon][Loot] Heroic Last Boss Drops 1 Item Instead of 2

### ISSUE THREAD

**Issue by Hemass** [gamefreedomgit/Maelstrom#2607]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Last bosses in heroic dungeons through RDF feature drop only 1 item, instead of the usual 2.

**How to reproduce:**
Last bosses in any heroic dungeon drop only 1 item

**How it should work:**
Pretty much every xpac or server(incl. Whitemane) I've played has dropped 2 so far, seems to be a different case here.

**Database links:**

**Comment by Loken-coolguy** [comment]
All HCs? @Hemass

**Comment by Hemass** [comment]
Yes @Loken-coolguy

**Comment by Sketish** [comment]
Every boss except last should drop only 1 item instead of 2. Currently every boss in deadmines is dropping 2 items which is incorrect.

**Comment by xmrshoot** [comment]
@Waroxx-QA it was fixed a few months ago   u can close it
