### ISSUE TITLE
[Dungeon] Disconnect when leaving RDF

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2608]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It is **not** 100% but mostly each time you leave RDF(heroic) by the "Leave Party" option it will disconnect the player, it happens to several players.

**How to reproduce:**
I figured out another way how to reproduce it simply by using "Deepholme potion" which instantly teleports a player into another area I used it a few times from Dalaran or Stormwind and it disconnects me every time the loading screen should disappear.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=58487

**Comment by UltraNix** [comment]
Cannot reproduce it.
