### ISSUE TITLE
[Item][Vendor] Sergeant Thunderhorn - Vicious Gladiator's Gavel

### ISSUE THREAD

**Issue by Hatepoem** [gamefreedomgit/Maelstrom#2609]
Sergeant Thunderhorn <Conquest Quartermaster> in Orgrimmar, the conquest points vendor, is missing all one-handed weapons, including Vicious Gladiator's Gavel. Two-handed weapons and shields are present.

https://cata-twinhead.twinstar.cz/?npc=54658
https://cata-twinhead.twinstar.cz/?item=61338

**Comment by Destaind** [comment]
yea plz fix this

**Comment by Hatepoem** [comment]
Fixed.

**Comment by Hatepoem** [comment]
Fixed.
