### ISSUE TITLE
[Item] Hornet-Sting Band Missing

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2611]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The item Hornet-Sting Band should be available to me as a druid from the Valor points vendor, but it is not there. All I can buy are either spell power or strength rings.

**How to reproduce:**
I have no idea, other people seem to have the ring available to them.

**How it should work:**
I should be able to buy the Honet-Sting Ring with 1250 valor points from Faldren Tillsdale in Stormwind.

**Database links:**
https://imgur.com/a/XZeyvHB - showing all 7 tabs of items available to me - the ring isn't there.

https://cata-twinhead.twinstar.cz/?item=68812

https://cata-twinhead.twinstar.cz/index.php?npc=44245

**Comment by UltraNix** [comment]
Fixed.
