### ISSUE TITLE
[Dungeon] Mechanar Elevator

### ISSUE THREAD

**Issue by switchykins** [gamefreedomgit/Maelstrom#2612]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

mechanar elevator doesent work as intended., it dissapears as you approach it.
**How to reproduce:**
do the instance regularly

**How it should work:**
as an elevator should,

**Database links:**

**Comment by MrTide** [comment]
can confirm it is missing

**Comment by Afgann** [comment]
fixed
