### ISSUE TITLE
[Death Knight][Pet] Pet Expertise Scaling

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2614]
Pet expertise should scale with the masters hit rating (gear + talents). If the master is hit capped, then therefore pet is hit capped. If the master is not hit capped then the expertise/hit from the pet is rounded down (most clear example would be having 7.99% melee hit rating on your character sheet and your pet having 7% hit, being the other 0.99% rounded down).

Pets are just getting dodged here and there and I don't know if they scale at all from master hit or the scaling is messed up.

![image](https://user-images.githubusercontent.com/127544286/227028790-5cb9f4c0-bf9c-4eeb-a439-1d2842ab67de.png)

How it worked before MoP (has been like this since early wrath):
https://www.engadget.com/2012-03-08-scattered-shots-hunter-expertise-in-mists-of-pandaria.html

https://www.wowhead.com/forums/topic/pet-expertise-116142

There were more detailed guides which would detail this topic better but all those websites are gone, this is still pretty common knowledge.

**Comment by testdk123** [comment]
Yeah pet should be expertise capped if the player has 8% hit rating. One of the reasons why expertise was pretty much worthless for unholy in Cataclysm. 
It's hard to find references to it, but I can guarantee you that you won't find a single PvE video where a DPS DK's pet will have a dodged attack. 
https://www.mmo-champion.com/threads/954108-Unholy-Expertise?p=12643178&viewfull=1#post12643178

I'm also wondering why the priority tag on this issue >https://github.com/gamefreedomgit/Maelstrom/issues/2254 was removed yesterday.

**Comment by UltraNix** [comment]
Tested - DK pets get 100% of owner's hit/spellhit.

**Comment by Vezax69** [comment]
@UltraNix  Should re-open this since it's not entirely fixed as shown on the next SS:

![image](https://user-images.githubusercontent.com/127544286/232343189-08b2f033-3d82-4ddb-93ed-1879e606d294.png)
You can see here:
1- Owner hit capped.
2- Pet dodge as it is happening.
3- Addon showing multiple dodge in the same test.
My guess is that the hit requirement might be slightly higher for the pet to not miss which is yet another bug.

**Comment by UltraNix** [comment]
Fixed.
