### ISSUE TITLE
[Achievement]Guild Achievement (Working As A Team) is Bugged and does not complete

### ISSUE THREAD

**Issue by kirogthar** [gamefreedomgit/Maelstrom#2618]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: The achievement requires all professions to be maxed to 525 with members at honored or above rank, it is met, but does not provide the achievement or the reward.

**How to reproduce: Create any guild, have members with achievement, some are checked off and are gray.

**How it should work: It should put a checkmark to all and grant achievement.

**Database links: https://www.wowhead.com/achievement=4860/working-as-a-team

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/227548987-c85e43e2-5ba0-4bd6-a8f0-13fd96911d8f.png)
Achievement works itself. Need more info. The criterias that are greyed out are maybe done by players before they did join your guild? Or does not have Honored rank?

**Comment by kirogthar** [comment]
![image](https://user-images.githubusercontent.com/48422993/227562041-bafde74d-0ec0-4afa-a604-5d3fecb32b87.png)
![image](https://user-images.githubusercontent.com/48422993/227562096-5384c38e-9620-4b7d-aea9-d8c08c2c6181.png)
![image](https://user-images.githubusercontent.com/48422993/227562170-a29e96ec-4099-40b9-8372-296bb84cb107.png)

**Comment by UltraNix** [comment]
I see - secondary professions. Fix on the way.

**Comment by UltraNix** [comment]
Fixed.
