### ISSUE TITLE
Cataclysm herbs have increased drops

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Maelstrom#2619]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can loot up to 9 pieces of Cinderbloom, Twilight Jasmine, etc. from one object, it looks like the guild perk (23 guild level) is active neither we don't reach it yet or cataclysm herbs have increased the drop amount.

this is the reason that sometimes classic herbs cost up to 20g/each and cataclysm herbs cost up to 3g/each.

The drop rate increase wasn't announced so it is a bug.

**How it should work:**
Each herb object should drop up to 5 herbs and there should be a chance to gather more with a guild perk on guild level 23.

https://cata-twinhead.twinstar.cz/?spell=83966

**Comment by MrTide** [comment]
related issues,
https://github.com/gamefreedomgit/Maelstrom/issues/2115
https://github.com/gamefreedomgit/Maelstrom/issues/2114
have the same issue with mining 
https://github.com/gamefreedomgit/Maelstrom/issues/2111

**Comment by WhitemaneSylah** [comment]
as Tide mentioned above - duplicate
