### ISSUE TITLE
SM mobs armory/cath friendly

### ISSUE THREAD

**Issue by Sugardad69** [gamefreedomgit/Maelstrom#2620]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz) cba

**Description:**
Mobs in SM Cath and SM armory friendly when they are supposed to be attackable mobs

**How to reproduce:**
Enter the dungeons and observe

**How it should work:**
Alot of generic mobs that are marked as friendly should be hostile, im missing out on that sweet juicy xp :(

**Database links:**
No. Its an obvious bug to anyone that sees it. Excuse my laziness

**Comment by UltraNix** [comment]
#2978
