### ISSUE TITLE
Worgen starting zone packed with mobs

### ISSUE THREAD

**Issue by Sugardad69** [gamefreedomgit/Maelstrom#2621]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Early on in the worgen starting zone i noticed a sea of endlessly spawning worgens, maybe hundreds? Its clearly more than intended and may have an impact on the servers

**How to reproduce:**
Roll a worgen and playtest, its at the part where u rescue som dipshit hanging in a tree

**How it should work:**
Moderate amount of worgens

**Database links:**
Database of my two beautiful eyes
Excuse my laziness

But honestly boys the worgen starting quests in its entirety needs to be overlooked, please playtest

**Comment by MrTide** [comment]
> Last test I did of Worgen zone everything was fine a week ago. Please post a screenshot of this .

https://github.com/gamefreedomgit/Maelstrom/issues/2526

**Comment by Sugardad69** [comment]
> > Last test I did of Worgen zone everything was fine a week ago. Please post a screenshot of this .
> 
> #2526

The screenshot is exactly what I witnessed aswell, Ill take a new aswell shortly if needed. Also had massive issues with the quest where you shoot yourself out of catapults to kill ship captains.
