### ISSUE TITLE
Anraphet and Glubtok hitbox is too small

### ISSUE THREAD

**Issue by zalger** [gamefreedomgit/Maelstrom#2624]
**Description:** 
Anraphet same as Glubtok has too small hitbox. It's kinda unreal to kill these bosses on rhc with full melee party. When it comes to Anraphet (Halls of Origination) when he casts alfa beams its just one circle in melee and u are unable to hit him, also its quite hard to move him since just after alpha beams he casts omega stance, then u have time to move him like 1-2 steps and he casts alpha beams again. Was trying to do it with melees, then we ran out of kicks and still with full melee party we were doing it for like 10min or so, no idea but it was hella long journey but troggs respawned when we were running downstairs cause upper room was full of violet circles and onshotted our healer. 
There's also no animation for Alpha Beams target switch, it just looks like he casts it on one player for full channel.
Some video i found:
https://www.youtube.com/watch?v=_xbgMenXlh8

Similar to Anraphet Glubtok (Deadmines) on phase 2 casts fire wall which hitbox is bigger than boss itself. You are unable to hit him as melee without being hit by fire wall which does alot of dmg so it's our of order to kill him without rangeds. Looks like it's either fire walls hitbox is too big or Glubtoks hitbox is too small, might be both.
Some video i found:
https://www.youtube.com/watch?v=Q9jKEicSZ2Q

**How to reproduce:**
Justo go for Halls of Origination heroic for Anraphet and Deadmines heroic for Glubtok. For Glubtok you have to first down him to 50% hp

**How it should work:** You should be able to hit them bosses as melee without getting smashed whenever u try to come melee range.

**Database links:**
https://warcraftdb.com/live/cataclysm/halls-of-origination/anraphet#dungeon-heroic
https://warcraftdb.com/live/cataclysm/deadmines/glubtok#dungeon-heroic

**Comment by WhitemaneSylah** [comment]
The hit box part is interesting,  can you share a video of this too from live so we can crosscheck please?

**Comment by zalger** [comment]
> The hit box part is interesting, can you share a video of this too from live so we can crosscheck please?

Working on it, I'll try to get some recordings this weekend

**Comment by zalger** [comment]
> The hit box part is interesting, can you share a video of this too from live so we can crosscheck please?

https://www.youtube.com/watch?v=1dzy18BecYk here is glubtok video, i was trying to hit him and nearly died, can't see a way to kill him with full melee party, comparing to retail video it looks quite different

**Comment by zalger** [comment]
https://www.youtube.com/watch?v=Puh9YYRaEzc and here is anraphet recording

**Comment by UltraNix** [comment]
Fixed.
