### ISSUE TITLE
[Area] Ice Thistle Hills - Yetis freeze too often

### ISSUE THREAD

**Issue by aabeba** [gamefreedomgit/Maelstrom#2625]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ice Thistle yetis freeze sporadically, but something they freeze seemingly too often.. I sometimes get chain frozen 4 times (in about 5 seconds).

**How to reproduce:**
Go to this cave in Winterspring and fight the yetis there.

**How it should work:**
Not sure this is a bug or if it works this way in live too. I don't remember ever being chain CC'd by mobs like this anywhere in WoW.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28632#reported-fixes

**Comment by Afgann** [comment]
fixed
