### ISSUE TITLE
Critical Mass / Improved Shadowbolt

### ISSUE THREAD

**Issue by Lakrosaswe** [gamefreedomgit/Maelstrom#2626]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Noticed quite a drop in proc frequency from the Shadowbolt overwriting Critical Mass. After extensive experimenting its a regular pattern as if Mages do not get the crit bonus from Improved shadowbolt and vice versa for Warlocks not getting the crit bonus from Critical Mass.

**How to reproduce:**
Extensive testing is the only way I can wager.

**How it should work:**
Both should get the spellcrit bonus from the others.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
