### ISSUE TITLE
Copper ore bugged in textures

### ISSUE THREAD

**Issue by zalger** [gamefreedomgit/Maelstrom#2627]
**Description:** Hello, just a while ago I started my quest to become proffesional miner cause i feel more like a dwarf than a goblin. Unfotunately alot of copper ore nodes are bugged in textures and I can't mine them! :c 

Cords for broken nodes in Durotar:

51.5, 15.6  
57.0, 31.2  
57.4, 70.1 (2 nodes there)
51.4, 54.8 (2 nodes there)
38.2, 26.6 (2 nodes there)
38.6, 23.9 x1

**Comment by UltraNix** [comment]
#3302
