### ISSUE TITLE
Frost DK- issues

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2635]
Description:
Frost DK is getting around 18-20% haste buff from unknown source
https://imgur.com/a/tabxXov
As you can see DK should have 15% haste from presence+25% from icy talons talent + additiontal 12% due to haste raiting.
Dk Should have in that case 52% haste not 70% as on snap.

Here are the results of Simcraft for patch 4.3.4 with ilvl of 350 and tests did on dummy on 23.03
https://imgur.com/a/EwtOKKd

Player is doing around 30% more than should. Biggest differences are on Obliterate main hand. It need more investigation because it may be related to boss armor values.

**Comment by Sketish** [comment]
While dual wiedling, proc Rime is stacking to 2 times when it shouldn't at all.

**Comment by UltraNix** [comment]
> Description: Frost DK is getting around 18-20% haste buff from unknown source https://imgur.com/a/tabxXov As you can see DK should have 15% haste from presence+25% from icy talons talent + additiontal 12% due to haste raiting. Dk Should have in that case 52% haste not 70% as on snap.
> 
> Here are the results of Simcraft for patch 4.3.4 with ilvl of 350 and tests did on dummy on 23.03 https://imgur.com/a/EwtOKKd
> 
> Player is doing around 30% more than should. Biggest differences are on Obliterate main hand. It need more investigation because it may be related to boss armor values.

![image](https://user-images.githubusercontent.com/80540499/227576745-e24f49a3-e63d-45e9-8528-3dbb2f027cd9.png)
Got the same talents and presence - haste is correct. Maybe something extra from your equipment?

**Comment by UltraNix** [comment]
20% from Icy Talons, 15% from Improved Icy Talons (that 10% bonus for DK here might be the bug), 10% from Unholy Presence
1.2 * 1.10 * 1.05 * 1.10 = 1.5246
