### ISSUE TITLE
Burning at Both Ends quest

### ISSUE THREAD

**Issue by Shanpou** [gamefreedomgit/Maelstrom#2636]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If u complete the quest Burnin at both ends Fargo Flintlocke dont spawns on his location on the High Banks. i looked around or on his first spawn he isnt there either

**How to reproduce:**
-

**How it should work:**
-

**Database links:**

https://www.wowhead.com/quest=28597/burnin-at-both-ends

**Comment by WhitemaneSylah** [comment]
#2604
