### ISSUE TITLE
Bugged Digsite

### ISSUE THREAD

**Issue by Exepowa** [gamefreedomgit/Maelstrom#2641]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Searing Gorge - Pyrox Flats Digsite

The place worked for me for the first time, the second time I went in I was unable to dig out a single piece, I don't know if I'm the only one with the issue tho

**Comment by UltraNix** [comment]
`I was unable to dig out a single piece` What do you mean? Show us some screenshots.

**Comment by Exorcista** [comment]
> `I was unable to dig out a single piece` What do you mean? Show us some screenshots.

#3166 , its red no matter where you put your survey tool

**Comment by UltraNix** [comment]
Fixed.
