### ISSUE TITLE
minerals in outland do not appear

### ISSUE THREAD

**Issue by Mercouwu** [gamefreedomgit/Maelstrom#2648]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** the Fel iron in outland does not appear anywhere

**How to reproduce:** just go check

**How it should work:**-

**Database links:** https://www.wowhead.com/tbc/es/item=23424/mena-de-hierro-vil

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ef53b399-5b02-4659-b080-71269ec86cf1)
