### ISSUE TITLE
Shortcuts losss

### ISSUE THREAD

**Issue by KingMav13** [gamefreedomgit/Maelstrom#2650]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

I lose all my shortcuts each time I log off

/ reload or log off

Should be saved

**Comment by DjaouedBen** [comment]
Check your game directory, make sure that Interface folder isn't in *Read Only*
