### ISSUE TITLE
[Death Knight] [Spell] Scourge Strike V2. 

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2651]
Reference to issue #2595 

Scourge Strike damage dropped from being 24% above SS physical to being 25% - 30% below. 

38% mastery DK:

(0,18 *3) * 1,3* 1,38 * 1,08: 1,046 (or 104,6% of SS physical damage). 
![image](https://user-images.githubusercontent.com/127544286/227682607-9bb3c172-495d-4ba8-9cce-01d0b41a7955.png)
![image](https://user-images.githubusercontent.com/127544286/227682632-71fc9e72-8573-473a-a343-cc60635a20d2.png)

**Comment by Vezax69** [comment]
Also, Army damage is still broken and it's doing way more damage, as referenced into issue #2520.
It also doesn't snapshot haste as far as I've tested.

**Comment by WhitemaneSylah** [comment]
Duplicate.  reopened your original report #2595   ,  Please don't create duplicate reports.
