### ISSUE TITLE
[Quest][WotLK] The Mist Isn't Listening - gorlocs not attackable.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2654]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While attempting to do the wolvar/gorloc questline in Sholazar Basin to get the green proto drake mount, I got stuck on trying to finish the part at Mistwhisper Refuge. The gorlocs, which I have to kill 12 of, are not attackable even though i get an attack icon on my cursor. I checked to make sure "at war" was checked, but it didn't make a difference. I am now stuck and unable to proceed with questline.

**How to reproduce:**
Attempt to attack the gorlocs at Mistwhisper Refuge.

**How it should work:**
They should be killable in order to complete the quest.

**Database links:**
https://imgur.com/a/M3JJQHf
https://cata-twinhead.twinstar.cz/?quest=12538
https://cata-twinhead.twinstar.cz/?npc=28110
https://cata-twinhead.twinstar.cz/?npc=28109

**Comment by UltraNix** [comment]
#2031
