### ISSUE TITLE
The Vortex Pinnacle Infight Bug

### ISSUE THREAD

**Issue by Durokian1337** [gamefreedomgit/Maelstrom#2655]
When you enter the dungeon you have no infight bug. At the latest after the 1st boss or even before, you have a permanent infight bug. This makes the dungeon unplayable.

**Comment by WhitemaneSylah** [comment]
Can you provide video evidence of this,  I've not seen this in any run I've been part of

**Comment by Durokian1337** [comment]
Sorry I don't have a video of it, but my colleague (Druidlul) who is a healer, has a permanent infight bug in the dungeon which is probably due to the elementals attacking us when we turn around. Either patch out the elementals, or patch in an NPC after each boss / vortex with which you can fix the infight bug.  
Greetings from Germany, I hope my english is good enough

**Comment by Durokian1337** [comment]
i hope the devs fixed it soon as possible

**Comment by UltraNix** [comment]
Should be fixed.
