### ISSUE TITLE
Al'Akir combat res bugged

### ISSUE THREAD

**Issue by Bandigoated** [gamefreedomgit/Maelstrom#2657]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
10 man normal Al'akir fight. Phase 2 fight got messy, main tank died while being in a tornado (I'm not 100% sure he died to the tornado dmg or when falling out from the tornado but the main thing is:). Me as a druid couldn't combat res him. It sad "out of range" (i was standing on top of him).

**How to reproduce:**
Let someone die in a tornado or try to time a death, so the character is "exiting out of the tornado"

**How it should work:**
You know. :)

**Database links:**
-

**Comment by Bandigoated** [comment]
This isn't a hight priority. To4 normal is really easy, fixing this right before the heroic mode drops is enough. :)

**Comment by UltraNix** [comment]
Should be okay now.
