### ISSUE TITLE
ARENA. combat 

### ISSUE THREAD

**Issue by mayday2013** [gamefreedomgit/Maelstrom#2659]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

https://canary.discord.com/channels/1040715551531618365/1040715552227872809/1089307343130472470

**How to reproduce:**

**How it should work:**

6 sec timer

**Database links:**
https://wowpedia.fandom.com/wiki/Combat

**Comment by UltraNix** [comment]
Fixed.
