### ISSUE TITLE
[Death Knight] [Spell] Risen Ally

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2660]
Risen Ally is not casting claw at all on frost/blood specs. All it does is just melee'ing with 100 energy pool.

Using /cast claw command just puts the risen ghoul on passive for some reason.

![image](https://user-images.githubusercontent.com/127544286/227748400-ec5c1a6f-32da-4236-9767-bb6df477d8eb.png)

Footage that shows claw on retail:

https://www.youtube.com/watch?v=UyOAsONwhaM&ab_channel=mbXtreme

**Comment by WhitemaneSylah** [comment]
Combat log isn't enough,  need proof that the pet has no orange damage too as your addon might be condensing it.  Please record your screen showing the pet actions.

**Comment by Vezax69** [comment]
Can’t log into the game now but it should not take much time for any staff member to test (quite literally 1 minute, as much). Details does segregate properly between melee and claw damage and as I said before the energy bar remains at 100 at all times (aka no claw usage). 
Worth to say> army still not fixed, even tho the evidence is quite clear.
I’m gonna be checking the formulas of many spells tomorrow hopefully finding everything working as intended. 
If by tomorrow you guys cant really test this subject I’ll record some test to see for yourselves.

**Comment by Vezax69** [comment]
Also, would like to ask about Army damage report and pet expertise cap report both tagged as “need info” even tho the knowledge is (or should be) widespread about those topics.

**Comment by Vezax69** [comment]
![image](https://user-images.githubusercontent.com/127544286/229258115-6f6536c3-3e5a-49f6-b53d-bf61f17bf9a3.png)
This shit is getting on my nerves

**Comment by Vezax69** [comment]
https://user-images.githubusercontent.com/127544286/229258223-68b76710-032b-42e8-bc3d-341c1c319d95.mp4

Very scuffed video length because of the file restriction. But you can clearly appreciate all I said above. Since I only got weekends to report, there's a couple more coming for tomorrow =)

**Comment by Vezax69** [comment]
> Combat log isn't enough, need proof that the pet has no orange damage too as your addon might be condensing it. Please record your screen showing the pet actions.

Any news on this?

**Comment by EdyGlockenspiel** [comment]
Can confirm, it's only auto hitting right now. It's supposed to actually use both gnaw and claw abilites as frost or blood. It's using neither.

**Comment by UltraNix** [comment]
Fixed.
