### ISSUE TITLE
Blue version of Vengeful Gladiator's Felweave Cowl missing in npc

### ISSUE THREAD

**Issue by lucario201** [gamefreedomgit/Maelstrom#2661]
**Description:**
I cant find blue version of Vengeful Gladiator's Felweave Cowl in npc (Kezzik the Striker in Netherstorm) it should be available to buy from him. All of his items from this set are red except head (below screen).

**How to reproduce:**
When i click on him there is no blue version of Vengeful head, all his items of Vengeful Gladiator's set are RED but head is missing.

**How it should work:**
Blue head of Vengeful Gladiator Felweave Cowl set should be available to buy  for honor points, will be nice if u can add it.

**Database links:**
https://cdn.discordapp.com/attachments/703295338391273623/1089350231449161728/image.png

**Comment by UltraNix** [comment]
#2409
