### ISSUE TITLE
[85] Patchwork Command, phasing issue?

### ISSUE THREAD

**Issue by squexence** [gamefreedomgit/Maelstrom#2663]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Phasing issue, Dragonmaw pass is empty, no npc at aall

**How to reproduce:**

**How it should work:**
Speak to the NPC named Patch to open the next chain of quests.

**Database links:**

https://www.wowhead.com/quest=27576/patchwork-command

**Comment by WhitemaneSylah** [comment]
Same issue as #2623 , compiling into one
