### ISSUE TITLE
Patriarch's blessing quest does not complete

### ISSUE THREAD

**Issue by itsasupa** [gamefreedomgit/Maelstrom#2667]
quest giver does not show up after completing the quest cant turn in quest
![WoWScrnShot_032623_064539](https://user-images.githubusercontent.com/128981371/227780085-b9dbbc66-b09f-4f02-966a-eb61dca2c83f.jpg)
![WoWScrnShot_032623_064605](https://user-images.githubusercontent.com/128981371/227780105-f587e16a-f2e7-48b3-91f3-b2f164c29650.jpg)

**Comment by WhitemaneSylah** [comment]
#2145
