### ISSUE TITLE
Achievement It's Frost Damage (Deadmines)

### ISSUE THREAD

**Issue by Klohunt** [gamefreedomgit/Maelstrom#2671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in the boss fight if you dont kill the vapors they should not despawn and now they do when the boss comes back out

**How to reproduce:**
start Admiral ripsnarl fight dont kill vapors and they dissapear when he returns

**How it should work:**
when he comes back the vapors shoulds not despawn

**Database links:**
https://www.wowhead.com/achievement=5369/its-frost-damage#videos:id=192452

second video is a bit better vieuw:
https://www.youtube.com/watch?v=d19Ha4XL27E&ab_channel=FuzionGaming

**Comment by UltraNix** [comment]
Fixed.
