### ISSUE TITLE
Bugged Quest - Siege Tank Rescue from Fargo Flintlocke - Twilight Highlands

### ISSUE THREAD

**Issue by ComfyChrist** [gamefreedomgit/Maelstrom#2673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing the quests before, including Shredderectomy, the follow up quest 'Siege Tank Rescue' appears to be offered
but when talking to the NPC (Fargo Flintlocke) he acts as if you've already accepted the quest and offers the turn-in dialog instead.
Also did not see any Siege Engine Commanders to the west, where the quest would normally be done.

**How to reproduce:**
Progress through main Twilight Highlands quest chain, until 'Our Boys on the Shore'. 
'Landgrab', 'Shredderectomy', and 'Scouting the Shore' are completable as normal.

**How it should work:**
After reaching the quest hub for 'Our Boys on the Shore'. you should be able to complete 'Landgrab', 'Scouting the Shore', 
'Shredderectomy', and 'Siege Tank Rescue'.
Would talk to Siege Tank Commander, who would be on top of/near a broken Siege Tank  west of the quest hub. 
Then defend the Engineers while they attemp to repair the Tank.

**Database links:**
https://www.wowhead.com/quest=27468/siege-tank-rescue
https://www.wowhead.com/npc=45168/fargo-flintlocke
https://www.wowhead.com/quest=27433/shredderectomy

**Comment by DjaouedBen** [comment]
Duplicate - #2558
