### ISSUE TITLE
[Quest][Item] Make Haste to Stormwind! - Dalaran Heroes Call Board quest

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You can spam quest finish button multiple times which gives you item "Hero`s Hearthstone" which should teleport you to Stormwind but it does not work.

Video: 
https://www.youtube.com/watch?v=4E1F-Yg9u-k

**Database links:**
https://www.wowhead.com/quest=29071/make-haste-to-stormwind
https://www.wowhead.com/item=68808/heros-hearthstone

**Comment by UltraNix** [comment]
Should be okay now.
