### ISSUE TITLE
[Core] Random teleports to Tol Barad bug

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2677]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometimes you get randomly teleported to Tol Barad xD and for some reason you appear only in Horde spawn xD

Video for confirmation:
https://www.youtube.com/watch?v=NEiMeewqIfY
https://www.youtube.com/watch?v=R5zYJHQp-hU

**Comment by UltraNix** [comment]
@Nenze Have you queued up for Tol Barad in any way or have been in Tol Barad Pensinsula that day?

**Comment by Nenze** [comment]
Never played Tol Barad, i`ve got teleported now like 3/4 times and sometimes random people also get TP there and they confused as i was.

**Comment by Nenze** [comment]
Yes it was

**Comment by UltraNix** [comment]
Fixed.

**Comment by Nenze** [comment]
@UltraNix GJ btw was it because someone joined BG after or something?

**Comment by UltraNix** [comment]
Crossfaction instances.
