### ISSUE TITLE
[10] Cloth and leather armor (Elwynn Forest)

### ISSUE THREAD

**Issue by Torises** [gamefreedomgit/Maelstrom#2679]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a quest missing in the [Guard Thomas](https://www.wowhead.com/npc=261/guard-thomas) quest chain unable to complete just because he gives no quest.

**How to reproduce:**

**How it should work:**
After finishing [Report to Thomas](https://www.wowhead.com/quest=71/report-to-thomas), same NPC must gives you the missing quest.

**Database links:**
Quest: https://www.wowhead.com/quest=59/cloth-and-leather-armor
Quest giver: https://www.wowhead.com/npc=261/guard-thomas

![1](https://user-images.githubusercontent.com/3170815/227923016-1c94d9ad-1b0d-4b64-8c2a-e12659c35170.png)

**Comment by UltraNix** [comment]
Fixed.
