### ISSUE TITLE
[NPC] Earthmender Norsala in Deepholm under the map

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2680]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Earthmender Norsala in Deepholm is fightning with respawning Irestone rumbler and while the fight is going on she falls under the map.

Video:
https://www.youtube.com/watch?v=okorDHRy3Qk

**Database links:**
https://www.wowhead.com/npc=42731/earthmender-norsala
https://www.wowhead.com/npc=42780/irestone-rumbler

**Comment by PanJanuszek** [comment]
Fixed after update
