### ISSUE TITLE
Orgrimmar Valor Vendor Missing Agility Ring Item Hornet-Sting Band

### ISSUE THREAD

**Issue by kirogthar** [gamefreedomgit/Maelstrom#2682]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
![image](https://user-images.githubusercontent.com/48422993/228029336-e9bde2c5-558a-476c-916e-8e6539b223bb.png)

**Description: The Orgrimmar vendor for Valor items is missing the agility ring Hornet-Sting Band, while having all other rings.

**How to reproduce:** Check the valor vendor inventory.

**How it should work:** It should have all of them. 

**Database links:** https://cata-twinhead.twinstar.cz/?item=68812

**Comment by WhitemaneSylah** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2611
