### ISSUE TITLE
hunter pet dmg

### ISSUE THREAD

**Issue by Pleasenerfhunters** [gamefreedomgit/Maelstrom#2685]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Please reduce mm/survival hunter's pet dmg. It's way too high.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneSylah** [comment]
Pet damage scales with the hunters stats. 

This is not a page to request adjustments,  but to provide evidence of bugs.
