### ISSUE TITLE
pet stance bug

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#2686]
whenever my monkey is on ''assisst'' stance it wont let me overlapp [bad manner] which is monkey spell. with any other CC. but whenever my monkey is on passive stance it does work im able to bad manner over scatter shot or freezing trap.

i should be able to overlap bad manner with any CC no matter pet's stance

**Comment by WhitemaneSylah** [comment]
Need video evidence of this one,  I haven't been able to reproduce it

**Comment by UltraNix** [comment]
No further info - closing.
