### ISSUE TITLE
hunter's ]Snake trap]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#2688]
Snakes from snake trap should NEVER  hit a CC target and that's including silenced target, atm my snakes always attack and dot a silenced target which is wrong. you can test it by using silence shot with snake trap

**Comment by WhitemaneSylah** [comment]
Snakes from snaketrap are treated as guardians.  

All guardians will stop attacking targets that has a CC that breaks on damage.

Silencing shot is not a CC that breaks with damage.

Bug invalid.
