### ISSUE TITLE
[Vortex Pinnacle] Slipstream zooming in camera

### ISSUE THREAD

**Issue by zalger** [gamefreedomgit/Maelstrom#2690]
**Description:** Every time you use slipstream on Vortex Pinnacle or Lost City of the Tol'vir camera zooms in, on longest path (4 slipstreams or so) camera zooms in to first person mode. Maybe not a critical bug, but its kinda annoying especially when your zoom out button is page up or smtg like that.

**How to reproduce:** Use slipstream on Vortex Pinnacle with camera zoomed out

**How it should work:** Using slipstream shouldn't zoom in your camera.

**Database links:** 
https://cata-twinhead.twinstar.cz/?zone=5035
https://warcraftdb.com/live/cataclysm/lost-city-of-the-tolvir#dungeon-normal

**Comment by UltraNix** [comment]
Works okay to me.
