### ISSUE TITLE
Aessina's Miracle NPC missing

### ISSUE THREAD

**Issue by switchykins** [gamefreedomgit/Maelstrom#2692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
can't find the Quest npc anywhere "Hamuul Runetotem"

**How to reproduce:**

start quest i believe
**How it should work:**
NPC should be standing at fixed location in "Grove of Aessina"

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
