### ISSUE TITLE
Can't Complete Forward Movement quest

### ISSUE THREAD

**Issue by babicszsolt** [gamefreedomgit/Maelstrom#2693]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/quest=14237/forward-movement)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=14237)

**Description:**
Cant complete Forward Movement Quest couse I cant click on and talk with the NPC

**How it should work:**
It should wait for my without mounting

![asd](https://user-images.githubusercontent.com/92633193/228063728-111ed83b-19db-4c7b-bc14-3c0ade42eb79.png)

**Comment by WhitemaneSylah** [comment]
Have you tried relogging ?

**Comment by babicszsolt** [comment]
Yes I tried reloging, disabling addons, totaly exit game and login again and nothing happend. I saw other players couldnt do it too. About 30 min the npc got dismount and I finally could take the quest.
