### ISSUE TITLE
[Throne of the Tides] Shielded cast on Lady Naz'jar

### ISSUE THREAD

**Issue by zalger** [gamefreedomgit/Maelstrom#2694]
**Description:** You cannot interrupt casts of Shock Blast on Lady Naz'jar (Throne of the Tides) after wiping her, cause they're shielded. This persists to transition phase (when adds spawn and she channels Watersprout), when adds are killed you can interrupt again.

https://www.youtube.com/watch?v=JF9yAALMmkM here's video i've taken, i started recording after we wiped, unfortunately server dced and our party was disbanded so you can't see it's interruptable again, but it is.

**Comment by UltraNix** [comment]
Fixed.
