### ISSUE TITLE
hunter polearm malfunction

### ISSUE THREAD

**Issue by carinhassb** [gamefreedomgit/Maelstrom#2695]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My hunter character can't need a polearm on roll and I can't use this item type to switch apperances either. It's as if I never learnt the weapon skill.  

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by DjaouedBen** [comment]
"Can't need a polearm" part is 100% confirmed.
But the second part about appearances is blurry, do you mean transmog ? cuz i've tried it and it's working correctly.

**Comment by UltraNix** [comment]
Fixed.
