### ISSUE TITLE
expertise not working properly?

### ISSUE THREAD

**Issue by Pleasenerfhunters** [gamefreedomgit/Maelstrom#2696]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
it seems like expertise just doesnt work properly. I have 21/21 expertise, which is soft cap, and still attacks are being parried way too often. 

**How to reproduce:**
I guess make a rogue, get 21/21 experise and spam gouge/kidney facing a warrior.

**How it should work:**
should obviously parry less.

**Database links:**
no clue how I could provide anything here and above.

**Comment by DjaouedBen** [comment]
"Note that DPS expertise scores are assuming that the player is attacking the target from behind, and thus only take dodged attacks into account. For targets that can parry attacks (i.e. from with tanks, standing in front of the target), the expertise ratings required to make both parries and dodges impossible would be much higher (see Tanking Expertise Caps, below)."
The expertise cap for not getting any parry / dodge facing your target is 53
[Fandom - Expertise (Cataclysm archive)](https://wowwiki-archive.fandom.com/wiki/Expertise?oldid=2503821#Expertise_rating)
