### ISSUE TITLE
just stuck im stuck the fuck...

### ISSUE THREAD

**Issue by pluso11** [gamefreedomgit/Maelstrom#2697]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by pluso11** [comment]
just need GM help to continued play..

**Comment by DjaouedBen** [comment]
Use in-game tickets for this case. 
Github is for DEVS, not GMs.
