### ISSUE TITLE
Unable to complete quest [The Devourer of Darkshore]

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#2698]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to complete quest [The Devourer of Darkshore](https://www.wowhead.com/quest=13891/the-devourer-of-darkshore). I have the quest item but cannot complete the quest, performed the correct actions, and got stuck in combat with an unattackable enemy that does not attack me but is stuck aggro on me.

**How to reproduce:**
Talk to [Kathrena Winterwisp](https://www.wowhead.com/npc=34301/kathrena-winterwisp). The quest is available but not completeable (grey question mark)

**How it should work:**
After completing the quest [In Defense of Darkshore](https://www.wowhead.com/quest=13885/in-defense-of-darkshore) you should be able to talk to her to get the next quest, [The Devourer of Darkshore](https://www.wowhead.com/quest=13891/the-devourer-of-darkshore)

**Database links:**
[The Devourer of Darkshore](https://www.wowhead.com/quest=13891/the-devourer-of-darkshore)
[In Defense of Darkshore](https://www.wowhead.com/quest=13885/in-defense-of-darkshore)
[Kathrena Winterwisp](https://www.wowhead.com/npc=34301/kathrena-winterwisp)

**Comment by alexspew** [comment]
Hi, this is completed. Should be live this week, in the meanwhile, you can make a gm ticket to get the quest completed. Thanks!

Duplicate : https://github.com/gamefreedomgit/Maelstrom/issues/2240
