### ISSUE TITLE
[Scarlet Monastery Library] Mobs fall through ground

### ISSUE THREAD

**Issue by apostolovskisimon** [gamefreedomgit/Maelstrom#2699]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mobs fall through the ground, ranged dps can still dps them but no loot. Its not doable

**How to reproduce:**
Enter Library, go pull mobs

**How it should work:**
Mobs shouldn't fall through ground

**Database links:**

**Comment by Waroxx-QA** [comment]
Can't reproduce it, i pulled the whole dungeon, no mob fell undermap
Can you give us more details ?

**Comment by jpaardekooper** [comment]
They are already spawned under the map.

**Comment by Waroxx-QA** [comment]
> They are already spawned under the map.
Can you make a screenshot or smthng  ? i coudn't find em

**Comment by UltraNix** [comment]
No further info - closing.
