### ISSUE TITLE
Last boss in halls of origination Rajh Construct of Sun drops only one item should drop two.

### ISSUE THREAD

**Issue by tvelander1** [gamefreedomgit/Maelstrom#2703]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Boss drops only one item but should drop + chaos orb

**How to reproduce:**
Kill boss drops one item + 1 chaos orb

**How it should work:**
Kill boss should drop 2 items + 1 chaos orb

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=48815
Proof
https://youtu.be/RoH0RgI83OE?t=89

**Comment by tvelander1** [comment]
https://cata-twinhead.twinstar.cz/?npc=39378

**Comment by Afgann** [comment]
fixed
