### ISSUE TITLE
Oracles daily quest  [Will of the Titans]

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2704]
**Description:**
Slain 50 Frenzyheart Attackers. Mobs cannot be killed, they illuminate red, however, the character cannot make a rare attack towards them

**How it should work:**
Mobs should be aggressive towards the player who chose Oracles factions which would allow them to be killed 

**Database links:**
https://www.wowhead.com/wotlk/quest=12705/will-of-the-titans
https://cata-twinhead.twinstar.cz/?quest=12705

**Comment by PanJanuszek** [comment]
should be fixed long time ago 02.04.2024
