### ISSUE TITLE
Anzu and Selin Fireheart failed to spawn today in HC mode

### ISSUE THREAD

**Issue by Mdomain** [gamefreedomgit/Maelstrom#2705]
Description:
So today there were a few bugs present. The second boss of sethekk halls, Anzu, didn't spawn in the instance. The same thing happened with the 1st boss of magister's terrace, Selin Fireheart. Fireheart is extra problematic because unless he is dead, the barrier at the entrance further in the dungeon will not dissapear and you can't progress further in the dungeon.

On the topic of buggy bosses, the Skadi fight in Utgarde pinnacle is bugged as well. There are too many NPC's spawning at once and they will aggro on you even if you use vanish. Without killing SKadi, you can't fight the final boss. Maybe just make Skadi attackable from the get go.

Database links:
https://www.wowhead.com/zone=4131/magisters-terrace
https://www.wowhead.com/npc=24723/selin-fireheart

https://www.wowhead.com/zone=3791/sethekk-halls
https://www.wowhead.com/npc=23035/anzu

https://www.wowhead.com/zone=1196/utgarde-pinnacle
https://www.wowhead.com/npc=26693/skadi-the-ruthless

**Comment by Waroxx-QA** [comment]
Sethekk halls / Magister's Terrace part is invalid. the two bosses spawn correctly.
Skadi part is confirmed.
