### ISSUE TITLE
Argent Tournament

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2706]
**Description:**
The Argent Tournament lance cannot be lifted from the handles. This makes it impossible to perform quests related to riding a mount, as it requires a lance. The handle interaction itself is, but it does not give an item.

**How it should work:**
The lance rack should give the player a lance that allows the mount to be ridden.

**Database links:**
https://www.wowhead.com/wotlk/item=46106/argent-lance

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
