### ISSUE TITLE
Sha'tari Skyguard Reputation "Skull Piles"

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2707]
**Description:**
Using 10 Time-Lost Scrolls, you summon a selected mob at the "altar." Currently, the altar can be used once every 40-50 minutes and only after that time can it be used again. 

**How it should work:**
Altars should be able to be used continuously without any cooldown limit their use only scrolls that are required to summon a mob.

**Database links:**
https://www.wowhead.com/tbc/object=185928/ancient-skull-pile

**Comment by Waroxx-QA** [comment]
Can't be used continuously, but respawn time should be 10-11 mintues according to retail archives.

**Comment by Kokaconk** [comment]
Hello, I've been waiting for more than 1 hour for it to activate, I have 146 scrolls and it doesn't work.
![Captura de pantalla 2024-01-13 210059](https://github.com/gamefreedomgit/Maelstrom/assets/131563086/80fe395e-3a57-4f65-9e5c-07f81443bd00)

**Comment by PanJanuszek** [comment]
fixed 11.03.2024
