### ISSUE TITLE
[26] Favored Skull (Stranglethorn Valley)

### ISSUE THREAD

**Issue by Torises** [gamefreedomgit/Maelstrom#2708]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Lashtail Hatchling](https://www.wowhead.com/npc=42736/lashtail-hatchling) doesn't pick up the skull who gives you the following quest: [Favored Skull](https://www.wowhead.com/quest=26745/favored-skull#comments)

**How to reproduce:**

**How it should work:**
[Lashtail Hatchling](https://www.wowhead.com/npc=42736/lashtail-hatchling) should pick up the quest from a nearby troll skull pile while (or not) doing [Deep Roots](https://www.wowhead.com/quest=26744/deep-roots)

**Database links:**
Quest: https://www.wowhead.com/quest=26745/favored-skull#comments

In-game capture to show where's the issue can be found:
![cSX5SzK](https://user-images.githubusercontent.com/3170815/228330666-aee7a99d-7849-49c3-9b37-cc0d40204464.png)

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/228791928-50ff093f-c5c5-43ef-9cd2-a5ffb28e4608.png)
You just need move a liitle bit around this place to trigger the areatrigger and the event.

**Comment by Torises** [comment]
I really did everything you talking about and the quest seems to be bugged for me. If i need to record screen, ill do it but i've literally walking around skulls and nothing happened.

I gotta say i finished Deep Roots but that's not even a problem because i can confirm from retail you can start this quest even finished Deep Roots.

So, gotta say it's still bugged. Anyway, thanks a lot for ur time. Appreciate it.

**Comment by UltraNix** [comment]
Okay - `Deep Rooys` is the key here.

**Comment by UltraNix** [comment]
Fixed.
