### ISSUE TITLE
Shadowfang Keep: Initial packs

### ISSUE THREAD

**Issue by gorxen** [gamefreedomgit/Maelstrom#2709]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in the Shadowfang Keep dungeon, the initial pack of mobs is like 8 of them and they all hit like a truck, leading to instant wipes, this keeps happening on 90% of my SFK runs, please consider doing something about it

**How it should work:**

There shouldn't be that many and they should not hit that hard.

**Comment by Waroxx-QA** [comment]
I never died on them, tanking em with a prot warrior with Dps gear ^^
