### ISSUE TITLE
Utgarde Pinnancle Skadi Boss

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2710]
**Description:**
Boss Skadi, after being attacked, soars up on a dragon, then using harpoons that fall out of mobs that spawn while fighting him, he is knocked off the dragon and begins the stage of fighting on the ground. Currently the harpoons fall out of the mobs, however, they cannot be picked up, which makes it impossible to start the second phase of the boss fight.

**How it should work:**
Harpoons that fall out of mobs on the ground should be able to be lifted which will allow you to defeat the dragon and start the second phase of the fight with Skadi

**Database links:**
https://www.wowhead.com/wotlk/npc=26693/skadi-the-ruthless

**Comment by PanJanuszek** [comment]
fixed 05.05.2024
