### ISSUE TITLE
 [The Black Knight of Westfall?] Argent Tournament Quest

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2711]
**Description:**
For this Quest you need to collect a book from a building in Westfall. It appears, but after collecting it, it is not added to the inventory.

**How it should work:**
The book, once collected, should go into the inventory of the player who collected it.

**Database links:**

https://www.wowhead.com/wotlk/quest=13633/the-black-knight-of-westfall
https://wotlk-twinhead.twinstar.cz/?quest=13633

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/d13795f1-9797-4f28-b045-230fd6018b81)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/71c4ee52-6fd2-493f-9508-37fb667eede9)

works as for 02.04.2024
