### ISSUE TITLE
Magister's Terrace HC

### ISSUE THREAD

**Issue by Pioterenko** [gamefreedomgit/Maelstrom#2714]
**Description:**
Bosses after an ID reset should revive, this does not happen.

**How it should work:**
Bosses after an ID reset should be reborn, which would allow you to perform fully instances.

**Database links:**
https://www.wowhead.com/tbc/zone=4131/magisters-terrace

**Comment by Waroxx-QA** [comment]
ID reset works for normal mode only, heroic mode can't be reset.
