### ISSUE TITLE
Problem with Frost DK

### ISSUE THREAD

**Issue by KezualDiaz** [gamefreedomgit/Maelstrom#2716]
There is very bad bug about frost DK SPELL that call: RIME no longer cause free costs of howling blast and icy touch
its happened day ago
Probally spell call: CHILL OF THE GRAVE dosnt generate runic power and porbally all spells dosnt generate runic power. 

In addition, it is not taking into account the double hit of the ability, when you have 2 one-handed weapons, it can cause the activation to be double in spell

**Comment by UltraNix** [comment]
#2713
