### ISSUE TITLE
DK FROST TALENT CHILL OF THE GRAVE 

### ISSUE THREAD

**Issue by miczis** [gamefreedomgit/Maelstrom#2717]
Dk talent "Chill of the Grave don't generate runic power at all, please repair this cuz this talent is essential to play this spec. Without this spec is unplayable.

**Comment by miczis** [comment]
If i have 0/2 points in talent Chill of the Grave obliterate on dk frost generate 20 runic power if i have 2/2 obliterate generate 21 runic power.  Howling Blast with this talent or not always generate 10 runic power.

**Comment by UltraNix** [comment]
#2713
