### ISSUE TITLE
[Shaman]Feral Spirit (wolves) - Missing spells in spell book -> Leads to two issues.

### ISSUE THREAD

**Issue by deviuz** [gamefreedomgit/Maelstrom#2718]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

My apologies if I wasn't supposed to report multiple issues under one report. Although this report pertains to Enhancement shamans, I assume any class with pets who are missing their pet spells in their spell book have the same issues. I have tested the macros on a DK and they're working with no problems. I have not tested this on a warlock yet, as I'd have to level up quite a bit in order to have a pet (as far as I know).

**Description:**
### Issue 2: In addition to not being able to toggle auto-cast for the spells, players also cannot use macros to use said spells either.

**How to reproduce:**

**Issue 1**
1. Cast Feral Spirit
2. Use a macro with /petautocastoff to toggle OFF the ability from automatically being cast, such as Bash, Feral Spirit Leap, etc.
OR
 Use a macro with /petautocaston to toggle ON the ability to automatically cast, such as Bash, Feral Spirit Leap, etc.
3. Doing so does not allow the player to toggle on or off these abilities.

**Issue 2**
1. Cast Feral Spirit
2. Use a macro with /cast Bash (or any other Feral Spirit 'spell')
3. The macro will not use the ability written in said macro; the player must key bind a button to a 'Pet Action Button (#)' under Key Bindings in order to use their pet abilities OR they have to use a macro such as /click PetActionButton# (# corresponding to the appropriate pet spell on the Pet Action Bar.

**How it should work:**

**Issue 1**

1. Cast Feral Spirit
2. Use a macro with /petautocastoff to toggle OFF the ability from automatically being cast, such as Bash, Feral Spirit Leap, etc.
 OR
 Use a macro with /petautocaston to toggle ON the ability to automatically cast, such as Bash, Feral Spirit Leap, etc.
3. The macro should allow the player to toggle between the ability being auto-cast when the Feral Spirits are summoned.

**Issue 2**

1. Cast Feral Spirit
2. Use a macro with /cast Bash (or any other Feral Spirit 'spell')
3. The macro should allow the player to use the Feral Spirit spell without having to resort to using other macros/means to use the spells.

**Database links:**

I couldn't find any videos with Shamans using the /petautocaston or /petautocastoff macros, but for the sake of proof here is a video from 2012, a DK using said macros for their ghoul: https://youtu.be/gqnrMZCgWNI?t=335

Also here are the appropriate links to wowpedia regarding these two commands:

https://wowpedia.fandom.com/wiki/MACRO_petautocaston
https://wowpedia.fandom.com/wiki/MACRO_petautocastoff

**Comment by UltraNix** [comment]
DK Ghoul is a pet, Shaman's Spirit Wolves are not (are summonable guardians with pet bar)

**Comment by UltraNix** [comment]
@deviuz What about macros with `/petautocastoff` and `/petautocaston`?

**Comment by UltraNix** [comment]
Fixed.
