### ISSUE TITLE
Twilight Highlands Quest NPC Missing

### ISSUE THREAD

**Issue by Xan12094** [gamefreedomgit/Maelstrom#2719]
**Description:**
NPC Fargo Flintlocke is not where he needs to be and therefore cannot continue questline in Twilight Highlands

**How it should work:**
He's supposed to stand on the box next to the cannon

**Database links:**
https://www.wowhead.com/npc=49020/fargo-flintlocke

**Comment by Waroxx-QA** [comment]
Duplicate - #2604
