### ISSUE TITLE
Deep Rock Island Refreshes Rare and cannot be attacked

### ISSUE THREAD

**Issue by skywangerye1989** [gamefreedomgit/Maelstrom#2721]
Character name, touqing, location: Deep Rock Island, server time: 10.36, refresh rare, unable to attack after riding, Oi Nax, drop rare mount, I waited for five days, finally refreshed, but unable to attack it, I hope to give me one

https://www.wowhead.com/item=63042/reins-of-the-phosphorescent-stone-drake

![微信截图_20230329162031](https://user-images.githubusercontent.com/129270277/228479050-1838371c-db5a-4432-bc6b-b52e46cc67c3.png)
![微信截图_20230329161036](https://user-images.githubusercontent.com/129270277/228479187-2987359d-03cf-42ae-915b-4d68cf5a7002.png)
![微信截图_20230329173640](https://user-images.githubusercontent.com/129270277/228492948-6537461f-d608-4934-8e04-c9495bede423.png)

**Comment by UltraNix** [comment]
@skywangerye1989 What do you mean by "cannot be attacked"? It's not targetable/selectable? Or maybe you can't reach it with your spells/melee attacks? Or maybe it's friendly?
Just tested and I can attack/cast spells without problems.

**Comment by Waroxx-QA** [comment]
> @skywangerye1989 What do you mean by "cannot be attacked"? It's not targetable/selectable? Or maybe you can't reach it with your spells/melee attacks? Or maybe it's friendly? Just tested and I can attack/cast spells without problems.

Aeonnax is Friendly sometimes for some players.

**Comment by Waroxx-QA** [comment]
Alright, yes he was targeting the vehicle and not the main boss ^^
