### ISSUE TITLE
Stranglethorn Fever + Mokk the savage

### ISSUE THREAD

**Issue by Torises** [gamefreedomgit/Maelstrom#2722]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[The Heart of Mokk](https://www.wowhead.com/es/quest=26598/the-heart-of-mokk), daily quest needed to summon [Mokk the savage](https://www.wowhead.com/npc=1514/mokk-the-savage) doesn't work properly.

**How to reproduce:**
Nps stands there static.

**How it should work:**
By giving him a [Gorilla Fang](https://www.wowhead.com/item=2799/gorilla-fang), it should starts an event with 3 gorilla pugs waves meant to be defeated in orther to get the last wave where Mokk appear. It doesn't work like this, i mean the event it doesn't even start.

**Database links:**
Broken quest: https://www.wowhead.com/quest=26598/the-heart-of-mokk
Quest giver: https://www.wowhead.com/npc=1449/witch-doctor-unbagwa

**Comment by PanJanuszek** [comment]
fixed 16.01.2024
