### ISSUE TITLE
Throne of Tides Old Faithful achievement bug

### ISSUE THREAD

**Issue by Jcbn0** [gamefreedomgit/Maelstrom#2723]
Achievement link: https://www.wowhead.com/achievement=5285/old-faithful

There is a bug with the achievement Old Faithful from Lady Naz'Jar. When the boss cast Geyser, this ability doesn't deal any damage to the adds or kills them, even with less than 20% of their health.

it should work like this:
https://www.youtube.com/watch?v=lJGNQtjg1-4

**Comment by Waroxx-QA** [comment]
The achievement works, i've tried it multiple times and it works.
