### ISSUE TITLE
Arena conquest cap

### ISSUE THREAD

**Issue by Slavyxd** [gamefreedomgit/Maelstrom#2724]
![image](https://user-images.githubusercontent.com/129298681/228558086-7b350f95-f8e9-469e-b7d8-3dbdef14fa72.png)
not a correct calculation for the second week in a row
with my rating, I should have a much higher limit on getting points
, this amount is commensurate with 1800 rating

**Comment by UltraNix** [comment]
According to [this site](https://web.archive.org/web/20121103021124/http://www.arenajunkies.com/tools/conquest-points-calculator) it should be 2911?

**Comment by UltraNix** [comment]
There are some calculators, but show different values.

**Comment by UltraNix** [comment]
http://www.arenajunkies.com/topic/179536-updated-for-season-10-conquest-point-cap-vs-personal-rating-chart/page__view__findpost__p__2914647
I think it scales good.

**Comment by Waroxx-QA** [comment]
[this one is for 3v3](https://web.archive.org/web/20110924073314im_/http://img838.imageshack.us/img838/6733/chartt.jpg)

**Comment by UltraNix** [comment]
Fixed.
