### ISSUE TITLE
[QUEST] (The Cape of Stranglethorn) The Final Voyage of the Brashtide

### ISSUE THREAD

**Issue by Torises** [gamefreedomgit/Maelstrom#2726]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This [quest](https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide) is a part of a Booty Bay chain and basically is bug due to a problem when talking to [Kebok](https://www.wowhead.com/npc=737/kebok) to get a ride.

**How to reproduce:**
Talking to [Kebok](https://www.wowhead.com/npc=737/kebok) you make a little jump it feels you gonna be mounted in a Bold Wind Rider but you inmediately fall to the ground. If you click again to be mounted, it's a loop.

**How it should work:**
By talking to [Kebok](https://www.wowhead.com/npc=737/kebok) you should get mounted to do the [quest](https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide).

**Database links:**
Broken quest: https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide
Quest giver: https://www.wowhead.com/npc=2496/baron-revilgaz

![1](https://user-images.githubusercontent.com/3170815/228605894-15cdc05a-bbce-4da4-b8cc-71c9b1c10473.png)
![2](https://user-images.githubusercontent.com/3170815/228605898-0cf2463c-8900-4258-8981-43782de2273b.png)

**Comment by UltraNix** [comment]
Fixed.
