### ISSUE TITLE
[ITEM] Electrostatic Condenser

### ISSUE THREAD

**Issue by Jokieh** [gamefreedomgit/Maelstrom#2729]
[Electrostatic Condenser](https://www.wowhead.com/item=67494/electrostatic-condenser) should give us extra Volatile Airs while we have the item in our inventory with 440+ engineering and another gathering profession.

I may have had really bad RNG but it didn't give me any from farming a full inventory of herbs: [screenshot](https://i.imgur.com/gkJhHUm.png) Edit: [another full inventory of herbs, 0 air
](https://i.imgur.com/g3jtZjF.png)
How it should work:

I'm not really sure.
From reading wowhead/mmo-champion/reddit comments, it should proc 3% - 10% of the time while gathering a node with mining/herba and it should a 100% provide an extra 1-3 airs from [Bloated Stomach](https://www.wowhead.com/item=67495/strange-bloated-stomach)s while skinning.

Edit:
After looking into it a bit more, the node proc chance should probably be in-line with the bloated stomach proc from skinning (which works currently, as far as I remember) and it should give 1-2 Airs according to a [comment](https://i.imgur.com/NDbiqnW.png) from the [strange bloated stomach](https://www.wowhead.com/item=67495/strange-bloated-stomach#comments) wowhead page.

**Comment by UltraNix** [comment]
Fixed.
