### ISSUE TITLE
Ascendtant Council - Arion/Terrastra AoE abilities (wrong timings)

### ISSUE THREAD

**Issue by vhasija** [gamefreedomgit/Maelstrom#2730]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During Arion and Terrastra phase, their raidwide AoE abilities are not happening on correct timers.
While we were pulling, Thundershock (from Arion) happened 1-2 seconds after Quake (from Terrastra).
It was also happening on wrong timings during the rest of the phase.

Didn't take screenshots yday during the kill, but our multiple guild runs reported the same problem, it should be checked out asap

**How to reproduce:**
Just get to P2 of Ascendant Council.

**How it should work:**
Quake and Thundershock shouldn't be happening at the same time.
They should be roughly 30 seconds apart, so people have time to change their debuff to grounded/swirling winds depending on the next AoE happening.

**Database links:**
_Video of blizzlike kill, timestamped at P2 (Arion/Terrastra phase), you can clearly see the DBM timers and how their raidwide abilites should be ~30 secs apart_
https://youtu.be/60NH5w_DZ50?t=144

**Comment by Sketish** [comment]
Already fixed
