### ISSUE TITLE
 Spinal Healing Injector

### ISSUE THREAD

**Issue by bernymvp** [gamefreedomgit/Maelstrom#2732]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Should reset like a regular potion, wich means, its suppose to start reset cooldown right after the combat. But here its start reset only after relog or after teleport to other location, so you need loading screen, i suppose

**How to reproduce:**
Just use it on your gloves and look at it being outside of combat, its not reset, then relog or teleport to other location and reset will start

**How it should work:**
Cooldown timer should start when you outside of combat

**Database links:**
https://www.wowhead.com/spell=82200/spinal-healing-injector#recipes

**Comment by UltraNix** [comment]
Fixed.
