### ISSUE TITLE
Paladin talent points

### ISSUE THREAD

**Issue by Speedo910** [gamefreedomgit/Maelstrom#2733]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

I'm missing a talent point from after dinging lvl 37. I hit lvl 37 and tried to asign my talent point but the game wouldnt let me. After relogging the point was missing and did not return after multiple tries of relogging.

**Comment by Waroxx-QA** [comment]
> I'm missing a talent point from after dinging lvl 37. I hit lvl 37 and tried to asign my talent point but the game wouldnt let me. After relogging the point was missing and did not return after multiple tries of relogging.

Just reset your talents, at lvl 37 you should have 15 talent points, if you have less even if you reset your talent, make an ingame ticket, github isn't for player's specific issues.
