### ISSUE TITLE
DK ghoul pet taking full aoe DMG

### ISSUE THREAD

**Issue by amanita199** [gamefreedomgit/Maelstrom#2735]
**Description:** 
As of the update earlier today. DK ghoul takes full damage from AoE dmg, example: deadmines 1st boss, when he does the spinning flames the ghoul just insta dies.

**How to reproduce:**
Have any sort of aoe damage the pet (ghoul)

**How it should work:**
Have the same reduction as hunters pets

**Comment by UltraNix** [comment]
Pet:
![image](https://user-images.githubusercontent.com/80540499/229059631-3b5e7d6b-6611-4fb3-95c7-d4a88d5de51c.png)
![image](https://user-images.githubusercontent.com/80540499/229061172-5790c7d5-2923-40fe-a571-1a8a38dd2e39.png)
Pet takes damage from Fire/Frost Blossom, which is not considered as AOE damage.

Non-pet:
![image](https://user-images.githubusercontent.com/80540499/229061477-bd7c4d83-6016-4df9-ae5f-6713539f8d2a.png)

**Comment by UltraNix** [comment]
Okay - I think I see what's the problem.

**Comment by Highhorizan** [comment]
Yea it dies to everything, my Spell is always on CD and there are times I have no pet while in Heroics and my damage just drops, due to having no pet for 2 mins...... :(

**Comment by Vezax69** [comment]
Yeah it wasn't like this before, right now it just died to any sort of AoE on DM.

**Comment by UltraNix** [comment]
Fixed.
