### ISSUE TITLE
[Dungeon][Boss] The Vortex Pinnacle 2nd boss

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2736]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You can bug 2nd boss Altairus by tanking him before platform essentially removing his core abilites.

Video:
https://www.youtube.com/watch?v=CqVDD47hDbA

**Database links:**
https://www.wowhead.com/npc=43873/altairus
https://www.wowhead.com/zone=5035/the-vortex-pinnacle

**Comment by UltraNix** [comment]
Fixed.
