### ISSUE TITLE
Cho'Gall - Fury Debuff not clearing with Hand of Protection

### ISSUE THREAD

**Issue by AzureScyclone** [gamefreedomgit/Maelstrom#2738]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cho'Gall's Fury Debuffs (Cho and Gall Blasts) are not clearing with Hand of Protection as they normally should. Other mechanics (such as antimagic shield, etc) do seem to block the reapplication of the Gall Blast (As it should) when active during Cho'gall's cast.

**How to reproduce:**
After being inflicted with Cho and Gall Blasts (the debuffs created by Cho'galls Fury of Cho'gall), try to have a paladin use Hand of Protection on the target.

**How it should work:**
Like wise most mechanics, Hand of Protection should remove all negative effects off the player with exception to Forebearance (the cooldown debuff placed on the use of any paladin immunity or major cooldowns/wings)

**Database links:**
N/A

**Comment by UltraNix** [comment]
Hand of Prorection remvoes only physical debuffs. Cho and Gall Blasts are from shadow school.

**Comment by AzureScyclone** [comment]
If both are from the shadow school - then AMS should prevent both from applying and it currently does not.

**Comment by UltraNix** [comment]
@AzureScyclone Yeah - my mistake. Only Gall's Blast is shadow and Anti-Magic Shell should work on it.

**Comment by UltraNix** [comment]
@AzureScyclone My mistake - only Gall's Blast is shadow and Anti-Magic Shell should work with it.
