### ISSUE TITLE
[Quest] To Win a War, You Gotta Become War - Can't Plant Seaforium

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#2739]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Wrong Bravo Company Field Kit provided, cannot plant seaforium charges to get credit.

**How to reproduce:**
Talk to [John J. Keeshan](https://www.wowhead.com/npc=43458/john-j-keeshan) for the quest [To Win a War, You Gotta Become War](https://www.wowhead.com/quest=26651/to-win-a-war-you-gotta-become-war), he will provide the incorrect Bravo Company Field Kit, making you unable to plant seaforium charges.

**How it should work:**
The correct Bravo Company Field Kit must have a 4th ability "Plant Seaforium Charge" in order to progress.

**Database links:**
https://www.wowhead.com/quest=26651/to-win-a-war-you-gotta-become-war

**Comment by UltraNix** [comment]
Just relog or /reload.
Clientside bug.
