### ISSUE TITLE
Fury warrior enrage effect bug

### ISSUE THREAD

**Issue by qnislavnachev** [gamefreedomgit/Maelstrom#2742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fury warrior enrage effect is increased by its mastery. When you open your fury talent, check the 'Enrage' its says for me:
"Your mele hits has 9% chance to Enrage you, giving you a 17% physical damage bonus for 9 sec."

But when I hit something and gain that the Enrage effect, when I check my buffs and point to the Enrage buff, its says to me:
"Physical damage increased by 10%" 

Maybe it is visual bug, I dont know, but if it is, it should be fixed as well I believe

Note: Mastery rating is 520

**How to reproduce:**
Gain some mastery on fury warrior (in my case is 520), gain the Enrage buff and check the bonus damage it gives to you.

**How it should work:**
You should gain the exact same percentage as in the talent, in my case when I gain the Enrage buff, it should give me 17% physical bonus damage

**Database links:**

**Comment by Waroxx-QA** [comment]
[https://wowpedia.fandom.com/wiki/Mastery:_Unshackled_Fury?oldid=2714828](https://wowpedia.fandom.com/wiki/Mastery:_Unshackled_Fury?oldid=2714828)

**Comment by qnislavnachev** [comment]
@Waroxx-QA I have been over this documentation already. Can you elaborate more to me why this is not a bug, please ?

**Comment by Waroxx-QA** [comment]
> @Waroxx-QA I have been over this documentation already. Can you elaborate more to me why this is not a bug, please ?

Everything is clear, mastery doesn't increase the % of damage increase of Enrage, it gives you more proc chance. BUT it will affect Death Wish ( you'll notice that the % of death wish buff will change if you have more/less mastery ) and it gives you more damage / heal on the two abilities that requires being enraged ( Raging Blow - Enraged regeneration ).
