### ISSUE TITLE
 [Elementium Dragonling] not working

### ISSUE THREAD

**Issue by jpaardekooper** [gamefreedomgit/Maelstrom#2743]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://www.wowhead.com/spell=84418/elementium-dragonling

**Description:**
 [Elementium Dragonling] spawns a lvl 1 dragon with 126 health...

**How to reproduce:**
Right click on trinket and whats the damage

**How it should work:**
spawns a lvl 85 dragon with correct amount of health
Does ~700 damage every 3 seconds.
Sometimes deals ~4500 nature damage to all nearby enemies. Looks like forked lightning.

**Database links:**

**Comment by Waroxx-QA** [comment]
Duplicate - #2737
