### ISSUE TITLE
[Priest] Dispersion cannot be used when affected by Maloriak's Flash freeze.

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2745]
Confirmed on PTR and Prod.

Priests specced into shadow cannot use Dispersion when under the effect of Flash Freeze 

Flash Freeze is considered a stun and should mean Shadow Priests can use Dispersion. 

![image](https://user-images.githubusercontent.com/121137397/229104916-d06a7952-1425-49e4-93ac-b41a4598fd22.png)
![image](https://user-images.githubusercontent.com/121137397/229104997-97aa27f0-53ab-44e7-8a03-f3113917af06.png)

**Comment by UltraNix** [comment]
Fixed.
