### ISSUE TITLE
Execute dmg in PvP

### ISSUE THREAD

**Issue by kewwwww** [gamefreedomgit/Maelstrom#2747]
Hello, so Medalx posted a screenshot of His Details, got Hit by execute for 54k dmg on resilience and Plate . I never got Hit by this much also never struggled that much to Take a Warrior down as firemage they Connect and 50% is Missing good luck fixxing that until maybe the right scalings kick in but i do believe whitemane going to be a pve Land before that happened. I wait for the Investigation but surely your PvP Community wont watch this for months. Just to Bring you Close i have played cata alot and Warrior was basicly Always and free kill for Frost and firemage.

 You Killing your own Project if you dont fix it. Saying everything is alright wont Change the fact that a warr with bloodthirsty Gear isnt supposed to do 54k executes. 

![Screenshot_2023-03-31-14-09-24-56_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/96470127/229118466-2bd2306e-b3d2-4a88-b344-d3beaa064142.jpg)

This state also holds Back Putting my Money into whitemane.

**Comment by WhitemaneSylah** [comment]
Execute is not ignoring resi or armor.  This is functioning correctly.
