### ISSUE TITLE
Old Faithful Throne of the tides Achievement Bug

### ISSUE THREAD

**Issue by MehdiGhannem** [gamefreedomgit/Maelstrom#2749]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Basically the achievement is that Lady Naz'Jar should kill one of her minions with her Geyser spell. We have tried multiple times to set the add on the blue zone before it pops and keep it there but it takes no damage! To make sure it is not a specific add we have tried with both melee and caster adds and it never worked

**How to reproduce:**

**How it should work:** The boss should be able to damage the adds with her spells once it phases after waterspout !

**Database links:**

**Comment by UltraNix** [comment]
#2448
