### ISSUE TITLE
[NPC][Quest][Deepholm] Beneath the Surface

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2752]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Beneath the Surface quest don`t work, not sure if I accepted this quest before or you just cant take this quest and it appears as if you are on it with "?" sign but you dont have it in quest log (checked with quest addon and without)

"https://github.com/gamefreedomgit/Maelstrom/issues/2748" on this closed topic i thought that I was on this quest but NPC Ruby Gemstone Cluster is just bugged but it just seems that quest is bugged and you appear as if you are doing it but its not even in guest log.

![WoWScrnShot_033123_162943](https://user-images.githubusercontent.com/122581454/229152730-ad15d399-6419-4c6a-9b91-ea2fc53d857a.jpg)
![WoWScrnShot_033123_163003](https://user-images.githubusercontent.com/122581454/229152896-bed4d5b5-64c5-4018-9296-0aa404c2a04c.jpg)
![WoWScrnShot_033123_163125](https://user-images.githubusercontent.com/122581454/229152911-b433be47-5e7c-4b27-85e9-796e2e89875a.jpg)
![WoWScrnShot_033123_163132](https://user-images.githubusercontent.com/122581454/229155353-bc7b6796-7205-4b47-827f-88b1acc4a387.jpg)

https://www.wowhead.com/quest=28488/beneath-the-surface

**Comment by UltraNix** [comment]
Fixed.
