### ISSUE TITLE
Cant link dropped loot in To4.

### ISSUE THREAD

**Issue by Bandigoated** [gamefreedomgit/Maelstrom#2753]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can't link dropped loot if its in master looter mode. Even when I "reward" it to myself after that, I am not able to link it to raid chat.
Very low priority. :)

**How to reproduce:**
-

**How it should work:**
-

**Database links:**
-

**Comment by UltraNix** [comment]
Should be fixed.
