### ISSUE TITLE
[Quest] He Who Would Be Forgiven

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2754]
**How to reproduce:**
Avrus Illwhisper is not visible for the players to turn in the quest
player and npc both are on phase 1 but still not visible 

**How it should work:**
he should not be phased out 

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13921

**Comment by alexspew** [comment]
npc_avrus_illwhisper

**Comment by PanJanuszek** [comment]
Added possibility to retake quest from [Pelturas Whitemoon](https://www.wowhead.com/npc=3894/pelturas-whitemoon) in Astranaar

He has invis aura which should be visible to player until he finish quest 13922 ( which is quest after this one )

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/58b082a7-3b4b-431c-978c-712c5b501e4c)

Did all chain and he switched to ELF form

**Comment by GM-Nightmaree** [comment]
Quest works fine
![image](https://github.com/gamefreedomgit/Maelstrom/assets/157993777/4471aa90-fc91-4e09-8e2f-f13c0fb2af9a)
it auto completes.
