### ISSUE TITLE
Half of the shadowmoon valley quests do not exist.

### ISSUE THREAD

**Issue by wolfingt219** [gamefreedomgit/Maelstrom#2756]
[[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

](https://www.wowhead.com/storyline/shadowmoon-valley-493)
 I was able to do everything up to dissension amongst the ranks after that no quests exist.

**Comment by PanJanuszek** [comment]
fixed with previous reports
