### ISSUE TITLE
Boss Nightbane is not work in Karazhan 

### ISSUE THREAD

**Issue by Harraiga** [gamefreedomgit/Maelstrom#2757]
Description:
The Nightbane boss does not work in the Karazhan dungeon. After completing a chain of quests on it, the last task "Nightbane" is given. You need to get to Master's Terrace and summon the boss by clicking on the urn. But it doesn't work and nothing happens after clicking.

How to reproduce:
Try to click on the Blackened Urn to summon the Nightbane(Nothing happens)

How it should work:
Into the Master's Terrace in Karazhan and touch the Blackened Urn to summon Nightbane(The boss appears)

Database links:
https://www.wowhead.com/quest=9644/nightbane

**Comment by PanJanuszek** [comment]
@Afgann fixed it long time ago
