### ISSUE TITLE
[Quest][Twilight Highlands] Once More Into the Fire

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#2758]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest "Once more into the fire" in Twilight Highlands isn't working. Cayden Dunwald gives the quest and offers dialogue, but then doesn't move an inch, making it impossible to complete the quest, as it requires a completed escort.

**How to reproduce:**
Click the 4 dialogues he has to offer, and then watch as he never moves through Dunwald Market Row.

**How it should work:**
After completing the dialogue, he should move forward though the village.

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=27648

**Comment by Waroxx-QA** [comment]
The quest is working, the npc moves correctly, maybe relogging / abandonning then taking the quest again will fix it ^^
