### ISSUE TITLE
Searing totem vs molten armor interraction

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2759]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Searing totem dmg onto a mage with molten armor damages the shaman and also breaks cc.
Video: https://streamable.com/xswiy3
**How to reproduce:**

**How it should work:**
Not a 100% sure if this is intended but I doubt it is.

**Database links:**

**Comment by UltraNix** [comment]
Totem is not a valid attack for most of spells and thus it procs on totem's owner. Do you have any proofs it's a bug?

**Comment by UltraNix** [comment]
No further info - closing.
