### ISSUE TITLE
Living bomb explosion goes through LOS.

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2760]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The living bomb explosions goes through LOS.
Video: https://streamable.com/o0flvc

Bad example video but the tree is LOS and it also keeps happening in obvious spots such as pillars in arenas.

**How to reproduce:**

**How it should work:**
Shouldnt go through LOS.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
