### ISSUE TITLE
Grounding totem doesnt ground deep freeze

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2761]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Grounding totem doesnt ground deep freeze
Video: https://streamable.com/zoyuby

**How to reproduce:**

**How it should work:**
Should ground the deep freeze (harmful spell)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
