### ISSUE TITLE
Druid Tier Normal Shoulder item valor vendor bug

### ISSUE THREAD

**Issue by Tuavea** [gamefreedomgit/Maelstrom#2762]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am a horde balance druid player. In my "Valor Vendor", to buy NORMAL balance druid shoulder set piece, I am required both Shoulder token and Balance Hands setpiece. This is not heroic shoulder set piece. This is buggy only for balance set item. Resto and feral shoulder set pieces don't have this problem.
![Screenshot_1](https://user-images.githubusercontent.com/31519007/229217613-fa3045cf-307b-4b09-a975-a478f71ef80b.png)
![Screenshot_2](https://user-images.githubusercontent.com/31519007/229217709-e59ecb9e-73e7-48a9-95bb-c3634c5acb53.png)

**How to reproduce:**
Just check the horde valor vendor as a druid

**How it should work:**
A NORMAL shoulder set piece should only require a shoulder set token. It works true for feral and resto set pieces but isn't for balance set piece.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=60284

**Comment by UltraNix** [comment]
Fixed.
