### ISSUE TITLE
Can't see archeology nodes

### ISSUE THREAD

**Issue by Tripaa** [gamefreedomgit/Maelstrom#2765]
I can't see the archeology nodes on the world map, but on the mínimap i can see the red archeology zone if it is close to me.

**Comment by Sketish** [comment]
Can you provide any snap or clip of that issue ?

**Comment by Tripaa** [comment]
![Minimapdigsite](https://user-images.githubusercontent.com/129558131/229309230-bf05bfc4-e3f0-4e18-ab9a-6cb1044f38eb.jpg)
![Mapnotdigsite](https://user-images.githubusercontent.com/129558131/229309233-2a41008e-d6f4-46ac-af2f-ce9a6b04f740.jpg)

As you can see, if im very close of the archeology digsites it appears on the minimap and in the map, but only when im close, and i cant see the digsites on the map.
