### ISSUE TITLE
Death knight- runes

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2767]
Death runes don't ever go back to their normal type if they are not spent. 
Spoiler: they should.

source:
https://www.youtube.com/watch?v=Tf1LiwVwfTE&ab_channel=PreachGaming

**Comment by Sketish** [comment]
Can you provide any snap or clip ?

**Comment by Vezax69** [comment]
I can't post clips here because due to the duration of them (and the archive weight), it's not hard to test. 2 festering strikes on unholy and wait 2 minutes you'll see the death runes not ever reverting back to their original type.

**Comment by Sketish** [comment]
Reaping passive is not working correctly. Death rune after spending should be converted back to oroginal one. Currently rune is staying as Death Rune even after spending it with abilities.

**Comment by testdk123** [comment]
> Reaping passive is not working correctly. Death rune after spending should be converted back to oroginal one. Currently rune is staying as Death Rune even after spending it with abilities.

That's... not true. Unless you're talking about Frost DK's Blood runes which are supposed to permanent be Death Runes via the Blood of the North passive.

**Comment by Sketish** [comment]
in frost  spec blood runes should stay pernament as death runes  but reaping is unholy passive

**Comment by testdk123** [comment]
> in frost spec blood runes should stay pernament as death runes but reaping is unholy passive

Yes, and they are going back to their original runes once expended, contrary to what you've said.
What's not working as intended is that they'll not expire back to their original state if you don't expend them, unless you change zones, die, relog. They should revert back after 30 seconds or 1 minute out of combat (I'm not completely sure about the exact timing).

**Comment by Vezax69** [comment]
> > in frost spec blood runes should stay pernament as death runes but reaping is unholy passive
> 
> Yes, and they are going back to their original runes once expended, contrary to what you've said. What's not working as intended is that they'll not expire back to their original state if you don't expend them, unless you change zones, die, relog. They should revert back after 30 seconds or 1 minute out of combat (I'm not completely sure about the exact timing).

Well you're right, however my bug report is accurate because it's pointed to something else>
If runes are not spent, they never go back to their original type. Regardless of being advantageous or not, is a bug.

Also runes are on a very weird state I must say, checking from the next picture, you can see my FDK (since unholy pet currently has no avoidance aura and dies to basically any random shit AoE spell) with a Blood rune (¿?) and a death rune; instead of 2 death runes.

I've also had this recurring thing happening in which whenever I log in (for some reason I'm still trying to figure out) in blood/frost spec; the permanent ghoul from unholy spec remains on those as a permanent pet.

It feels like a cycle of broken things that got fixed but then at some point they break again. 

SS just to see:
![image](https://user-images.githubusercontent.com/127544286/229662339-24d63181-c340-487f-ab03-0f9a17ef6869.png)

**Comment by UltraNix** [comment]
Fixed.
