### ISSUE TITLE
Death Knight- Pet out of LoS doesn't get Shadow infusion stacks.

### ISSUE THREAD

**Issue by Vezax69** [gamefreedomgit/Maelstrom#2768]
Currently, when your pet is out of your line of sight (and maybe also, too far away from you) it's not getting any shadow infusion stacks.
Noticed it when it happened to me on Al'akir; found a video of an unholy dk on the same boss not having any issue with this thing.

https://www.youtube.com/watch?v=-s9lh3DhEhg&ab_channel=mbXtreme

**Comment by UltraNix** [comment]
Fixed.
