### ISSUE TITLE
Deepholm Quest: Silvermarsh Rendezvous 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2769]
**Description:**

The quest " Silvermarsh Rendezvous ID: 27007 " should be automatic upon completion and not to go to the NPC at the earth core.

**How to reproduce:**

Take the quest and see for yourself.

**How it should work:**

It should be auto completed.

**Database links:**

https://www.youtube.com/watch?v=3Bp29gXk4kQ

**Comment by PanJanuszek** [comment]
Fixed after update
