### ISSUE TITLE
Tol Barad Peninsula - Cursed Stallion NPC

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2771]
**Description:**

Cursed stallion the horse in Tol Barad Peninsula currently has 30391K hp.

**How it should work:**

It should have 2854 hp according to https://www.wowhead.com/npc=46645/cursed-stallion

**Database links:**

https://www.wowhead.com/npc=46645/cursed-stallion

SS proof:

![Cursed Stallion](https://user-images.githubusercontent.com/67479994/229276175-bf0c75cb-af81-480a-bccf-a334466041a6.PNG)

**Comment by UltraNix** [comment]
#1877
