### ISSUE TITLE
Twilight Highlands Quest - Siege Tank Rescue is bugged

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2772]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

You can't get the quest, also it shows a yellow question mark above the npc.

**Database links:**

https://wowpedia.fandom.com/wiki/Siege_Tank_Rescue

SS proof:

![Siege Tank Rescue](https://user-images.githubusercontent.com/67479994/229276098-5a73beb4-90d8-42e7-987c-c1d950438e6b.PNG)

**Comment by UltraNix** [comment]
Fixed.
