### ISSUE TITLE
Twilight Highlands - Crucible of Carnage - Goblin NPC doesn't give last quest for the weapon

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2773]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

At the Crucible of Carnage the Goblin NPC doesn't give the last quest for the weapon reward.

Quest name is: " The Crucible of Carnage: The Twilight Terror! " 

**Database` links:**

https://www.wowhead.com/quest=27868/the-crucible-of-carnage-the-twilight-terror

**Comment by Mordurin** [comment]
Same here today for 2 ppl

**Comment by UltraNix** [comment]
Fixed.
