### ISSUE TITLE
Twilight Highlands Quest - A Steady Supply

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2774]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After you complete " Anything but water " quest the dwarf NPC Eoin Dunwald ( https://cata-twinhead.twinstar.cz/?npc=46583 )

should start a new quest called " A Steady Supply " in order to continue the chain and storyline.

**Database links:**

Quest giver link: https://cata-twinhead.twinstar.cz/?npc=46583

Quest link: https://cata-twinhead.twinstar.cz/?quest=27649

**Comment by UltraNix** [comment]
Fixed.
