### ISSUE TITLE
Twilight Highlands Quest - Once More Into The Fire is bugged! 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2775]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The quest " Once More Into The Fire " is bugged, when you talk with the NPC after 3-4 seconds he becomes unclickable and after that he disappears.

Please fix this as you can't continue the chain quest and the storyline.

**How it should work:**

After you talk to him, he should walk down the market row and you should protect him from the attackers.

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=27648

**Comment by MrTide** [comment]
Can confirm after multiple tries by a lot of ppl it bugs out

**Comment by MrTide** [comment]
after multiple tries by multiple ppl quest npc bugs out and stops working not even a reset (kill and respawn) by game masters fixes it

**Comment by PanJanuszek** [comment]
Found root cause.
