### ISSUE TITLE
Judgement and Hammer of Wrath CRITICAL bug!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2777]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Judgment and Hammer of Wrath are Paladin's ranged spells that hits from afar, being a ranged attack it is not supposed to trigger effects like Frost Armor and Nature's Grasp.

Right now both spells are triggered when the Paladin Judges and Hammers the target, that is wrong since both of them are only supposed to trigger when the caster is hit by a MELEE attack.

**How it should work:**

Proof: https://www.youtube.com/watch?v=b2QADmYk594

As you can see from the gear he is wearing and from his and his mates health pool he is playing in Cataclysm last season (Cataclysmic). If you skip at 3:11 you can clearly see that when he judges the Mage, that clearly has Frost Armor as you can see from his buffs, he doesn't get slowed.

**Database links:**

**Comment by Waroxx-QA** [comment]
The video is private.

**Comment by Renehadox** [comment]
Yea I just saw, how did that happen? Oo

Nevertheless it should work like I have reported.

**Comment by Renehadox** [comment]
Author: UltraNix
Message: Scripts/Spells: Frost Armor and Nature's Grasp should not proc off from Judgement and Hammer of Wrath.

gamefreedomgit/Maelstrom#2777 

Bug is still not fixed...

**Comment by UltraNix** [comment]
Judgement vs Frost Armor:
![image](https://user-images.githubusercontent.com/80540499/230354384-77672fd8-93a5-4322-bbdd-72d00c968d9b.png)

It's fixed.
