### ISSUE TITLE
The Eye (Raid)

### ISSUE THREAD

**Issue by Hepticlol** [gamefreedomgit/Maelstrom#2779]
The Kael'thas Sunstrider fight is consistently bugged.
The fight starts off normally, Thaladred the Darkener activates and attacks us.
We kill him off and then all dialogue stops. The first time we tried we got to kill the 2nd mini-boss but after we reset because it bugged, we have not gotten further than 1st mini-boss.

Thaladred's fixating ability is also broken in chat as shown on the picture:
![image](https://user-images.githubusercontent.com/115653997/229294717-44002cb8-a2ed-4583-b2fd-8d65402abe61.png)

Sucks a bit it is impossible right now to farm for transmog and mounts, but I hope you manage to find a fix,

Hope this helps and thanks in advance.

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
