### ISSUE TITLE
Isiset, Construct of magic boss bug

### ISSUE THREAD

**Issue by Zmordabear** [gamefreedomgit/Maelstrom#2780]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Isiset, Construct of Magic boss goes invisible on around %30 hp on normal mode of halls of origination.

**How to reproduce:**
For us we were just doing a normal run of the dungeon and it suddenly gone invisible at %30hp and after we wipe we ticket'ed a gm asking for help, and after we ressed we engage the boss again and it bugged again. The gm took care off the boss and we just left the dungeon afterwards

**How it should work:**
the boss should split into clones if i remember? and then u kill clones and the boss dies afterwards.

**Database links:**

**Comment by Waroxx-QA** [comment]
This happens when you kill all the clown on the previous phase.
Confirmed but but it's a special case.

**Comment by UltraNix** [comment]
Fixed.
