### ISSUE TITLE
Deepholm Quest Keep Them off the Front is bugged

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2785]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

 [Keep Them off the Front] quest is bugged, when you shoot the NPC's it says evade and the Fungal Terrors attack you, not the catapult but the player, i also killed myself 2 times.

Pictures:

![Capture1](https://user-images.githubusercontent.com/67479994/229311491-f327fb82-38b1-470f-9fc4-23ef31f28b38.PNG)

![Capture](https://user-images.githubusercontent.com/67479994/229311492-3b3481ea-8c15-42cd-9bb4-7322955b7493.PNG)

**How it should work:**

https://www.youtube.com/watch?v=lDU_JDVNQqY

It should work like this.

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=26755

**Comment by Waroxx-QA** [comment]
The quest is still doable, but it has to be fixed cuz it's not supposed to work this way.

**Comment by MrTide** [comment]
duplicate
