### ISSUE TITLE
Blackrock Caverns - Beauty heroic fight

### ISSUE THREAD

**Issue by Alandiel** [gamefreedomgit/Maelstrom#2786]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Currently there are 3 puppies not chained with Beauty. Lucky should be missing in heroic mode. Buster and Spot should be part of fight with Beauty on heroic difficulty.
Runty the puppy behind her shouldn't be chained with her, but killing him should trigger Berserk("Increases the caster's attack and movement speeds by 150% and all damage it deals by 500%. Also grants immunity to Taunt effects. Cast if Runty is killed.") for Beauty, and it should persist even after boss is reset, basically making boss unkillable. Currently killing Runty doesn't trigger Berserk. 

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Beauty?so=search
https://www.wowhead.com/npc=39700/beauty/heroic-encounter-journal

**Comment by UltraNix** [comment]
Fixed.
