### ISSUE TITLE
Darkmoon Card: Volcano proc issue

### ISSUE THREAD

**Issue by Endrjuboomkin** [gamefreedomgit/Maelstrom#2791]
https://www.youtube.com/watch?v=CgBCpM_xxV8 

As you can see on video there are no procs in Darkmoon Card: Volcano
Every 45 sec time Darkmoon Card: Volcano should give you bonus buff - 1600 intellect for 12 seconds.

https://www.wowhead.com/item=62047/darkmoon-card-volcano#comments

![image](https://user-images.githubusercontent.com/129656933/229346941-c414f11d-b151-406d-a025-873476a05483.png)

**Comment by bloodlust-whitemane** [comment]
also experiencing issues with this. attached approx 750 individual instances of spell damage with only 1 proc during this time over approx 10 minutes of testing. 
![image (4)](https://user-images.githubusercontent.com/129664318/229351071-f0c81e00-a18a-4973-83f1-102feb41ff23.png)

**Comment by alexspew** [comment]
According to spell dbc ::
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Proc flag 0x00050000, chance = 30, charges - 0

**Comment by UltraNix** [comment]
Fixed.
