### ISSUE TITLE
Quest can't be completed: Details of the Attack 

### ISSUE THREAD

**Issue by Aletrya** [gamefreedomgit/Maelstrom#2793]
**Description:**
Quest "Details of the Attack" in The Cape of Stranglethorn.
The Item "Bloodsail Charts" isn't on the table at Wild Shore, next to the NPC "Cowardly Crosby" as it is supposed to be.
Quest can't be completed like this.

https://www.youtube.com/watch?v=e09fzQzDsIQ&t
https://www.youtube.com/watch?v=RY8iV0lwAqs&t

**Comment by alexspew** [comment]
unable to reproduce, gameobject most likely looted before you arrived. It has a 3 minute respawn timer.
![image](https://user-images.githubusercontent.com/13508764/229354536-93a4cb0f-55a2-49a4-8ec0-e2d504ae08eb.png)
