### ISSUE TITLE
QUEST "Subdue the Subduer" bugged

### ISSUE THREAD

**Issue by Mahmoudajabi** [gamefreedomgit/Maelstrom#2794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest "Subdue the Subduer" doesn't work properly. The NPC simply dies from channel damage.

**How to reproduce:**

**How it should work:**
Instead what should happen is that at low health (maybe 1% health), Reth'hedron should trigger an event where he doesn't die and goes to the portal, says something, then disappears and the quest is validated. 

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/c7993bff-9559-46cf-b11d-96aeb99b0640)

On ~10% NPC become non attackable through attacks & questitem and run to portal to give player credit. 09.03.2024
