### ISSUE TITLE
Quest "An Old, Crazed Friend" can't be turned in.

### ISSUE THREAD

**Issue by Aletrya** [gamefreedomgit/Maelstrom#2795]
Quest "An Old, Crazed Friend"
Not able to turn-in the Quest. When I talk to "Joseph the Crazed" to turn it in inside of the Scarlet Monastery, I don't get the option to turn it in. Also like 50-70% of all mobs inside of the "Scarlet Monastery Armory" Part are friendly, maybe that's part of the problem with this Quest.

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/16b7460d-49a2-4eca-b306-fd21f5784f78)
