### ISSUE TITLE
Can't equip vicious gear

### ISSUE THREAD

**Issue by SirKwony** [gamefreedomgit/Maelstrom#2797]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hello, i just created a Vicious ruby signet (the one with str from jewelcrafting)and it says i need to be lvl 86 to equip the item while max lvl is 85
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bloodlust-whitemane** [comment]
This is because these items were not made to be crafted yet (they are 377 item level), it's not a bug, devs changed this intentionally.
