### ISSUE TITLE
The Crucible of Carnage: The Twilight Terror!

### ISSUE THREAD

**Issue by Addelynqt** [gamefreedomgit/Maelstrom#2801]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The last quest of The Crucible of Carnage in Twilight Highlands doesn't work and you can't aquire it.

**How to reproduce:**

**How it should work:**
You get it by clearing the previous four quests in the sequel.

**Database links:**
https://www.wowhead.com/quest=27868/the-crucible-of-carnage-the-twilight-terror

**Comment by Waroxx-QA** [comment]
Duplicate - #2773
