### ISSUE TITLE
T11 12/12N Clear - Bugs we have encountered

### ISSUE THREAD

**Issue by dejdus7** [gamefreedomgit/Maelstrom#2802]
https://www.twitch.tv/videos/1782722683

https://www.warcraftlogs.com/reports/n6bj3dfVWDAytzQh

Attaching a VOD of our 12/12 NM run today. I will be writing time-stamps for bugs we have encountered. I did not go through the effort of how exactly everything should be working nor how much damage it should deal. I do not have the time available for that, but I will explain what differs from Twinstar's Apollo.

4:20 - Rohash is casting Wind Blast multiple times. It should be 1 single cast in the combat log (makes DXE timer act weird here)

5:47 - Rohash doesn't do anything after ultimate. My stacks also dropped. This should not happen. The point of the fight is to play around the stacks, here i am not getting any debuff stacks on me allowing me to stay on the platform.

9:33 - Heroic Leap does not work on Al'akir

10:00 - Frost patches do not deal damage

10:51 - Acid rain stacks misteriously drop. Bloodlust affects it perhaps?

17:12 - Golem Sentry's frequency of pool spawns is slightly too high.

19:57 - Dispelling the debuff on players caused by attacking Poison Soaked Shell should remove all stacks, not 1 by 1.

20:31 / 20:57 - Arcanotron should be casting on the person with highest threat on him. Both of the healers were getting casted on here.

22:17 - Overhead smash is way too wide

24:32 - AOE damage should not be hitting the ranged here.

26:02 - Lava Spew's damage is way too low

27:33 - Our 2nd person assigned to jumping was not able to jump on the head. Unclear on this one.

27:57 - Main tank is not getting dropped on the correct location.

32:43 - Maloriak is missing a boss frame

33:23 - Abberations are able to be hard cc-ed. Roots-Cyclone should not work on them.

43:10 - Gongs are not respawning after a wipe

Chimareon - Hunter's Mark activates the boss from sleeping.

48:00 - Talking to the robot should not immediately start the encounter.

54:11 - Onyxia's energy regeneration is wrong. She is supposed to do first cast of Lightning discharge at 20s of encounter start (first cast is at 0:36 here)

54:11 - Onyxia has no boss frame. She should have one.

54:51 - Animated warriors's health frames should despawn after their energy is gone.

57:00 - The pillars should not affect Line of Sight (can't cast on Feral when he is behind pillars. You should be able to).

57:00 - Nefarian will start levitating above the ground at a certain point.

1:11:34 - Halfus should have a cast bar when doing the roar. Timing of consecutive roars is also wrong. You should be able to fit a global in between each Roar.

1:18:30 - Engulfing Magic should not be able to target melees.

1:19:20 - You are able to stun/root evolved drakonaar.

1:24:36 - You are able to receive both buffs (the ones that damage a particular boss derived from the specific debuffs) at the same time. You should only be able to have one active.

1:25:00 - Lightning Rod did no damage

Cho'Gall - https://www.twitch.tv/videos/1782784084

Using Cat Forms' Feral Charge will make you fall through the floor.

He should not be able to cast Mind Control on Tanks (casted on our feral)

The first add (the one that casts Corrupting Clashes) did not spawn adds from it's poll upon it's death.

Alliance characters were not able to cast on each other (Mind Control isn't working properly).

**Comment by dejdus7** [comment]
Mind Controlled players on Cho'Gall should be visible as enemy targets on Raid Frames. They are not here.

**Comment by Waroxx-QA** [comment]
I can confirm everything you listed here.
Heroic leap is another case, i could use it on alakir. Not being able to use it and getting "no path available" message is caused by porting out / in of the instances, and this can happen on all instances. so it's a class specific / core issue.
