### ISSUE TITLE
Fishing Major Bug

### ISSUE THREAD

**Issue by dantethehunter** [gamefreedomgit/Maelstrom#2803]
The leveling Fishing process is waaaaay to slow, making it hell even through skill 300. Obviously bugged, must be fixed in order to make cooking accesible and vital aspect of the game.

**Comment by Waroxx-QA** [comment]
Where's the bug ? at least take time to explain what's wrong.
We usually close these kinds of reports as Invalid, so make it clearer for us or it will be closed.

**Comment by dantethehunter** [comment]
The wrong is to have to make 50 attempts in order to get a level up. I also tried the specific zones depends on the skill level to maybe see any difference.

**Comment by UltraNix** [comment]
Fixed.
