### ISSUE TITLE
Nefarian - 10 Man Phase 2 - Cooldowns on Spells set to 25-Man Speed

### ISSUE THREAD

**Issue by AzureScyclone** [gamefreedomgit/Maelstrom#2804]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description**
Hello, the cooldowns on the adds (after interrupting them) for the 10-man version of Nefarian are currently set at the 25 Man frequency; which has certainly made interruption situations very interesting to say the least; but it effectively requires 2 reliable interrupts on each platform within a 10 man raid - kind of a hard bar to hit.

**How to reproduce:**
Just getting Nefarian to Phase 2 in a 10 man, interrupting adds and watching how quickly they can cast again.

**How it should work:**
The adds should be set to a 10-12 second cycle for their casting, which requires a dedicated interrupter per platform, but not two, in order to get through the phase.

**Database links:**
https://www.mmo-champion.com/threads/866326-Nef-10m-Questions
https://youtu.be/txPpAU2_aKY?t=199 (Time right at Phase 2 of 10 Man Nef)

**Comment by UltraNix** [comment]
Just tested - on 10 man normal there is 15 sec timer, on 10 man heroic - 12.5 sec.
