### ISSUE TITLE
Jewel-crafting rings and necks over level

### ISSUE THREAD

**Issue by cunbex** [gamefreedomgit/Maelstrom#2807]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Jewel crafting max level gear, when you reach level 525 with jewel crafting you have access to craft 
 [Vicious Amberjewel Pendant], [Vicious Ruby Choker], [Vicious Sapphire Necklace],  [Vicious Amberjewel Band], [Vicious Ruby Signet], [Vicious Sapphire Ring].
 
 but they are lvl 86, you can't wear them and you can't sell them.

**How to reproduce:**
fix it so it be wearable by level 85.

**How it should work:**
it should be used by level 85.

**Database links:**
![pic1 (1)](https://user-images.githubusercontent.com/98683647/229547525-cec92c20-c16b-45be-b6bf-0005e4bbabad.png)

**Comment by Waroxx-QA** [comment]
This is intentional.
377 ilvl items will be available on 4.3 ( Dragon soul and s11 pvp )
