### ISSUE TITLE
Didt skip profession 300-450

### ISSUE THREAD

**Issue by stasko-sergey** [gamefreedomgit/Maelstrom#2810]
When i was 39lvl i up my profession to 300, and now i take 80lvl but didnt take skip from 300 to 450. Nickname piypiy.

**Comment by Waroxx-QA** [comment]
Please use in-game ticket for this case.
![image](https://user-images.githubusercontent.com/120338315/229587441-b5fe13a3-365e-4372-89b6-2900f73fa9bc.png)
