### ISSUE TITLE
Minor quest bug

### ISSUE THREAD

**Issue by SirKwony** [gamefreedomgit/Maelstrom#2811]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello,I found a minor  bug, i think at least,in Dalaran there's a quest that rewards the player with one time use Heartstone,the quest it s already completed so u just have to click complete,the prob i was with this specific quest is that u can repeat this quest multiple times to get as many one time hs  as you want ,and also the hearstones dosent work

**How to reproduce:**

**How it should work:**

**Database links:**
![1](https://user-images.githubusercontent.com/129689718/229578567-da4922df-2b0a-464a-a404-d510b70512cf.jpg)

**Comment by Waroxx-QA** [comment]
Duplicate - #2676
