### ISSUE TITLE
Twilight Highlands Beer Run Daily Quest is bugged!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2815]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When you speak with the NPC he doesn't offer option to start the quest.

SS proof:
![beerrun](https://user-images.githubusercontent.com/67479994/229601188-caa951ff-b0e2-4650-a48b-d42b235cd7e0.PNG)

**How to reproduce:**

**How it should work:**

https://www.youtube.com/watch?v=X1LbovdNRLI

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=28864# - quest link

**Comment by PanJanuszek** [comment]
Fix soon

**Comment by PanJanuszek** [comment]
Fixed
