### ISSUE TITLE
[Raid][Boss]Blackwing Descent Atramedes gongs dissapear after wipe

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2817]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Our guild was doing Atramedes and we wiped using all gongs next few tries we had no gongs to use so we could not avoid boss mechanics and we wiped each time, server restart that happened at 23:00 today fixed issue.
Unfortunately I dont have video of this happening and after restart we killed boss so cant check it anymore.

**Database links:**
https://www.wowhead.com/npc=41442/atramedes

**Comment by MrTide** [comment]
changing difficulty before reaching this boss breaks the event so after killing the dwarfs boss wont spawn and event wont play out

**Comment by Afgann** [comment]
fixed
