### ISSUE TITLE
Ret Paladin's Aura with Communion talent

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2818]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Any Ret Paladin's aura with Communion talent loses its effect upon dying and you should re-use aura again to gain its effect, this is really annoying bug, mostly for battlegrounds and world pvp.

**How to reproduce:**

Make a ret paladin, talent communion, use aura, enter a bg, die and upon revival you should see that the 3% damage increase effect is lost.

**How it should work:**

Ret Paladin auras should be upon death and the effect of 3% dmg increase shouldn't be lost upon dying.

**Database links:**

**Comment by Renehadox** [comment]
Update:

It also loses its effect in a RDF without dying, like its random, at random times...

I am wondering whats the cause of it?

You have to double check it...

**Comment by Renehadox** [comment]
Status: Need Info?

Need info for what? :D

It's a really specific bug so there isn't video proof at the moment, since its really an unusual bug....

Here is a proof from in game:

25% from two hand weapon spec, 2% at all times from communion talent and +3% from active aura.

![WoWScrnShot_040423_000733](https://user-images.githubusercontent.com/67479994/229914263-86cd74a3-c6d4-4774-8be8-ace11e0512ce.jpg)
![WoWScrnShot_040423_165507](https://user-images.githubusercontent.com/67479994/229914280-cd32f121-9e4b-4ea9-84c9-81272e484ce6.jpg)
![WoWScrnShot_040323_234349](https://user-images.githubusercontent.com/67479994/229914286-6daa8cb5-6c90-4542-b725-cd923c1d8ad7.jpg)
![WoWScrnShot_040323_232415](https://user-images.githubusercontent.com/67479994/229914291-f110f6c3-3838-4b91-9e3f-1ced96b13a98.jpg)

As you can see I just spawned from a graveyard in BG and i have the aura active, but not the bonus damage.

Therefore mark this as confirmed and apply a fix asap!

Thank you very much indeed.

**Comment by Renehadox** [comment]
Bumping this... can you please put this as a high priority and fix it?

**Comment by UltraNix** [comment]
Before death:
![obraz_2023-05-29_174752319](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/126671b3-b8fc-4fdc-afbb-2ae4ef0dad7f)
On death:
![WoWScrnShot_052923_174845](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a4fc505e-ab55-4e6c-9341-304b0132865d)
After revival:
![WoWScrnShot_052923_174908](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/c5a5b33e-cfea-4e16-95c7-6ad3263fac01)

Works okay.

**Comment by Renehadox** [comment]
On your screenshot you are alone in your BG, also do not close thread when the bugs are not actually fixed.
I think something is bugging it out and in but i dont know what is it.
I just played a BG and look:

![WoWScrnShot_053023_170826](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/1d437229-71cc-4e56-b1e4-36c64a75c9e2)
![WoWScrnShot_053023_171234](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/d2db4ee5-d7ff-4061-a2b1-34e6d4d71fca)
![WoWScrnShot_053023_171636](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/bc1aa9ae-74ee-4d3d-934a-29a0643bb10e)

Aura is on and i still miss the 3% bonus dmg increase.
Whats going on here? :D

**Comment by Renehadox** [comment]
Any updates?

**Comment by Renehadox** [comment]
Bumping this, any updates??

**Comment by Renehadox** [comment]
Bumping this ???

**Comment by Renehadox** [comment]
@UltraNix @Afgann 
Any updates of this bug?
Come on guys, its been 3 months since i reported it, it should be marked as critical not a medium.
3% damage increase is a big deal!

**Comment by UltraNix** [comment]
#4249
