### ISSUE TITLE
Raid members are seen as enemies after Cho'Gall's Conversion

### ISSUE THREAD

**Issue by armagananteplioglu** [gamefreedomgit/Maelstrom#2822]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After being targeted by Cho'Gall's Conversion spell, raid members who haven't been targeted by the same spell are seen as enemies and will be seen as enemies until they are targeted by Conversion as well. This results in healers not being able to heal until those who haven't affected by Conversion and damage dealers deal cleave damage to raid. 

**How to reproduce:**
Just get affected by Cho'Gall's Conversion.

**How it should work:**
Raid members should seen as enemies during the Worshipping channeling, after being interrupted or losing Conversion all raid members should be seen as friendly, all healing should be able to resume and raid members should not be seen as attackable targets.

**Database links:**

https://www.wowhead.com/npc=43324/chogall

**Comment by Sketish** [comment]
Author: Afgann

 - Update Conversion handling, fix players appearing as hostile after aura removal, fix players appearing friendly when controlled in some cases. 
 
 Will confirm at evening if fix is solving this issue

**Comment by Afgann** [comment]
fixed
