### ISSUE TITLE
PVP- CC spam 

### ISSUE THREAD

**Issue by richysoscary** [gamefreedomgit/Maelstrom#2824]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If i remember correctly, back when i played AT Cata, if you sapped a person ( 8 sec ) if you spammed sap the red text on top said you cant use a less powerful spell on the enemy, the next time you could sap is at 4 sec timer, since the next sap is 50% DR = 4 sec, so its the "same" powerful"
Currently on the server you can spam 3x sap, and make it full DR

Note: This applies to every other cc.: poly, stuns, fears ,etc

Note 2.: This works like this on retail WOTLK, Warmane WOTLK, MoP servers, Shadowlands retail, Dragonflight retail, I dont think that it was different in only 1 expansion.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by richysoscary** [comment]
@Waroxx-QA  I can log on Warmane wotlk ,classic wotlk, 2x mop server, and Dragonflight retail to show it

**Comment by UltraNix** [comment]
Fixed.
