### ISSUE TITLE
Twilight Highlands : Quest : <Rune Ruination> BUGGED

### ISSUE THREAD

**Issue by ioriyan** [gamefreedomgit/Maelstrom#2825]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After complete quest, NPC doesn't pop up to return the quest

**How to reproduce:**
![螢幕擷取畫面 (55)](https://user-images.githubusercontent.com/129858022/229784460-42710190-1dd0-4560-ac68-22af50efd278.png)

**How it should work:**
https://www.youtube.com/watch?v=3sz0zwNFm_I

**Database links:**

https://www.wowhead.com/quest=27744/rune-ruination

**Comment by UltraNix** [comment]
Fixed.
