### ISSUE TITLE
PVP - BG - IoC - Vehicles

### ISSUE THREAD

**Issue by richysoscary** [gamefreedomgit/Maelstrom#2826]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometimes backstab, hemo says " immune " if im hitting the vehicles on IoC ( havent tried on other BG vehicles ) , so it takes like solid 10 min for a rogue to kill a demo in IoC, not happens everytime(?).

Idk what other spells have the same problem.

Note: 1 out of 1000 backstab says " immune " to players too.( or i was super tired )

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I've made over 500 attacks with Hemo (with and without glyph) and 500 attacks with backstab on demolisgers - no single immune. We'll need some more info here.

**Comment by UltraNix** [comment]
No further info - closing.
