### ISSUE TITLE
Warlock Affliction talent "Jinx"

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#2827]
**Description:**
The talent in the affliction tree should add the effect of the spell "Curse of the Elements" to nearby targets but it doesn't. 

**How to reproduce:**
Add the talent, cast "Curse of the Elements" on a target with nearby enemies, the effect appears only on the selected target and not to all the enemies. The damege done to the affected target is increased but the same damage done to another nearby target is not increased.

**How it should work:**
The talent should apply the effect of the spell "Curse of the Elements" to all the nearby target and increase all the damage done to the targets

**Database links:**
"Jinx" talent: https://www.cavernoftime.com/spell=85479
"Curse of the Elements" spell: https://www.cavernoftime.com/spell=1490

**Comment by UltraNix** [comment]
![image](https://user-imag@maldrek3103 thubusercontent.com/80540499/230484286-b5364ac6-57b0-4e80-9c6b-00fd7529e8d8.png)
@maldrek3103 Works okay to me. Could you re-test it?

**Comment by maldrek3103** [comment]
Yes is working, i re-tested it, don't know why it wasn't working last time. Anyway there is no icon that marks the affected targets
