### ISSUE TITLE
Unholy DK Talent: Contagion

### ISSUE THREAD

**Issue by Baermel** [gamefreedomgit/Maelstrom#2830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Tried it several times now. If u spread your plaque it doesn't deal increased damage. Please fix <3

**How to reproduce:**

**How it should work:**

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=91319

**Comment by Sketish** [comment]
Contagion is spreading with you current AP, if you snapshoted dots on mob and after all procs went off you used pestilence the dmg should be 'normal' - before any attack power modifiers.

If you can provide any video it will speed up solving this issue
