### ISSUE TITLE
last boss halls

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#2831]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**rajh on halls of origination drops only 1 item instead of 2

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
