### ISSUE TITLE
PVP - Rogue Evasion

### ISSUE THREAD

**Issue by richysoscary** [gamefreedomgit/Maelstrom#2832]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Maybe i could be unlucky, but i think evasion not working as intended. I got 3x straight scattered in evasion, then i asked a hunter in durotar to scatter me while i have evasion up. 5 out of 5 times i got scattered in evasion. I mean there is a pretty low chance for that.

Fun fact: Demonology warlock felguard stun is physical stun too. It cant be dodged with evasion either. I think it should be

I havent tested with other spells yet. 
Probably bugged.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Tested and worked okay to me. Sometimes 4-5 misses at row, sometimes 4-5 hits at row. But overall looks okay.
Made a test with 300 Scatter Shots:
First withhout evasion with 0 hit rating on hunter:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/518fef3f-24d8-43ac-a374-58727ac5c9f2)

Now with evasion and still 0 hit rating on hunter:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/4bbb8b04-f062-4f54-b93b-1943040b99d2)

Miss is increased by ~23%.
