### ISSUE TITLE
[Priest][Spell] Penance: Levitate Breaks Channeling

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#2833]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Channeling Penance on self or a friendly/enemy target will sometimes* break after the first volley if the Priest is also benefiting from [Levitate](https://cata-twinhead.twinstar.cz/?spell=1706).  

*Issue appears to happen more often when the target is both further away from the Priest, and moving. Issue happens less often when the target is closer to the Priest and standing still.

**How to reproduce:**
Have Levitate buff, then cast Penance. Watch for a break in the channeling of Penance after the first of three ticks. 

**How it should work:**
Penance channeling should never suddenly break because the player is benefiting from Levitate. There is an identical report on Twinstar with [video](https://clips.twitch.tv/GenerousRacyPotatoTwitchRPG) and additional notes, [here](https://cata-twinhead.twinstar.cz/?issue=8582). 

**Database links:**
[Penance] https://cata-twinhead.twinstar.cz/?spell=47540
[Levitate] https://cata-twinhead.twinstar.cz/?spell=1706
[Video] https://clips.twitch.tv/GenerousRacyPotatoTwitchRPG
[Report] https://cata-twinhead.twinstar.cz/?issue=8582

**Comment by UltraNix** [comment]
Fixed.

**Comment by MaelstromAbbey** [comment]
@UltraNix Thank you! Re-tested about 30 casts and cannot reproduce the original issue
