### ISSUE TITLE
[Priest][Spell] Fade: Not Reducing Threat

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#2834]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fade is not temporarily reducing all threat from the Priest. 

**How to reproduce:**
While in a party of at least two, generate enough threat that an enemy will aggro to the Priest. Then, cast Fade. Note that once casting Fade, all threat should reduce and cause the enemy to aggro to the next party member. 

**How it should work:**
Casting Fade should temporarily reduce all threat for 10 seconds. 

**Database links:**
[Fade] https://cata-twinhead.twinstar.cz/?spell=586

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/230588471-c75d324c-1282-4e29-9112-f28b75950989.png)
Just tested and worked okay for me.
@MaelstromAbbey Need more info/tests here.

**Comment by MaelstromAbbey** [comment]
@UltraNix Thanks for testing. This has not been my experience while in an RDF setting, though. I will try and gather additional evidence.

**Comment by UltraNix** [comment]
Thx.

**Comment by UltraNix** [comment]
No further info - closing.
