### ISSUE TITLE
[Rogue PvP] Cheap Shot getting dodged // Hit n Expertise cap not working as intended

### ISSUE THREAD

**Issue by jcminguy42** [gamefreedomgit/Maelstrom#2836]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Getting my cheap shot dodged from stealth from a sapped feral druid night elf
Vanish shadowstep cheap shot dodged from same feral

**How to reproduce:**
Basically 1/4 of arena games while being hit/exp cap facing opponents without any extra parry/dodge chance, Disarm gets parried, kidney gets dodged, etc etc etc.

**How it should work:**
Cheap shot cannot be dodged.
Hit/exp cap should mean you can't be dodged against opponent without any xtra parry/dodge chance.

**Database links:**
[PROOF (CLIP)] : https://clips.twitch.tv/GiftedShortPorpoiseEleGiggle-301T71otDOqZINIk
https://www.wowhead.com/spell=1833/cheap-shot      
[Cannot be dodged, parried or blocked](https://www.wowhead.com/spells?filter=60;1;0)

**Comment by richysoscary** [comment]
@jcminguy42  Most classes have extra parry,dodge, from their main stat ( agi or str)

**Comment by richysoscary** [comment]
But yes, cheapshot is bugged

**Comment by UltraNix** [comment]
Combat logs staying that cheapshot is dodged would be helpful.

**Comment by richysoscary** [comment]
https://clips.twitch.tv/FrigidKawaiiFrogHeyGirl-x2OVNoQjeDdX-9vA

yes im hitcapped before you ask.
![Screenshot_6](https://user-images.githubusercontent.com/129841569/230519849-99c62ad1-12b4-41b6-bb32-59fb6dca13ee.png)

**Comment by UltraNix** [comment]
The thing is that neither me nor testers are able to get this bug reproduced. I tried like 200 cheap shots on retri and prot paladins infront and behind - 0 dodges/parries/blocks. In normal/commond situations that always work. We would need still more info about your opponents (talents, level) and yours as well. Are you able to replicate it in regular duel?

**Comment by jcminguy42** [comment]
I mentionned it was a feral druid NE, try a few on that one maybe.

**Comment by UltraNix** [comment]
@jcminguy42 Tested again against feral NE - still no dodges (only misses)

**Comment by jcminguy42** [comment]
Well, I don't know what to tell you then, have you watched my clip? It's on
video, 2 dodges in a row. Same happened again yesterday, dodged a kidney
from behind against a NE Feral.

**Comment by UltraNix** [comment]
I would request for a video with the bug on our server.

**Comment by UltraNix** [comment]
@Renehadox I need another one from duel.

**Comment by jcminguy42** [comment]
I did link the clip in my post just above?

**Comment by Misxfits** [comment]
Sorry but still bugged, Today I get dodged few cheapshot, blind and disarm with 20/20 EXP. to much coincidence :D 
and a lot of them form behind, any attack done from behind cant be dodged or parried.

**Comment by UltraNix** [comment]
@Misxfits Maybe against night elves?
About cheap shot and blind - can you show me some screehsnots from combat log? (this spell should not be dodged/parried)
