### ISSUE TITLE
Fishing spell not working properly

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#2842]
**Description:**
When you are fishing after catching a fish, if you cast the spell too fast the fishing bobber bugs. The major problem is that if you cast again and start fishing it count the previous bugged bobber as your main.

**How to reproduce:**
Drag the fishing spell into action bar, start fishing, catch a fish and cast the spell fast again.

**Comment by UltraNix** [comment]
Fixed.
