### ISSUE TITLE
Textures issues

### ISSUE THREAD

**Issue by enriquegh995** [gamefreedomgit/Maelstrom#2843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
NPCs and pets are getting cliped through any uneven ground causing pets to get dismissed and NPCs attacking from below the surface in instances like Bastion of Twilight where entire pulls of adds clip through stairs and Cho gal clips through his throne, Lost City of Tol'vir where in last boss' platform pets get clipped below being useless, Shadowfang Keep where pets get clip through the stairs and get dismissed

**How to reproduce:**
Charge to cho gal when he is coming down the throne and he clips, sometimes the adds that he spawns also get cliped, the adds at the entrance of his room if you fight them in the stairs they clip, basically charging into any NPC in an uneven ground is a risk to get cliped too. If you take any pet with you ina fight in an uneven ground it is going to get cliped and dismissed.

**How it should work:**
Textures should keep NPCs and pets above the textures at all times

**Database links:**

**Comment by UltraNix** [comment]
#2884
#2852
#2851
