### ISSUE TITLE
Turn Evil Pets does not work, pets still cast spells while feared

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2845]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I just played AB and I was 1v1 vs affli lock, i turn evil his pet and right after i casted a heal and the pet silenced me while under turn evil. :D

**How to reproduce:**

**How it should work:**

Warlock or DK pets cannot use spells or attack under CC.

**Database links:**

**Comment by UltraNix** [comment]
![WoWScrnShot_041223_155324](https://user-images.githubusercontent.com/80540499/231479616-c4c06a6b-6bab-4355-a86b-41fd2a786eeb.jpg)
Remember, that any damage will brake the effect. Maybe that was the case here?

**Comment by Renehadox** [comment]
> ![WoWScrnShot_041223_155324](https://user-images.githubusercontent.com/80540499/231479616-c4c06a6b-6bab-4355-a86b-41fd2a786eeb.jpg) Remember, that any damage will brake the effect. Maybe that was the case here?

Well, i was in 1v1 vs that affli warlock in AB in the stables area as i remember, i feared his pet and then i casted a heal, but the pet interrupted me.

**Comment by UltraNix** [comment]
No further info - closing.

**Comment by Renehadox** [comment]
The fear damage should break until you take 30% of the damage, correct me if am wrong, sorry for the late reply i was not at home for a while.
