### ISSUE TITLE
[Quest - Terokkar Forest] Ishaal's Almanac - item doesn't drop

### ISSUE THREAD

**Issue by Lucika77** [gamefreedomgit/Maelstrom#2846]
**Description:**
When doing quest "Secrets of the Talonpriests", a mob called Talonpriest Ishaal should drop an item called Ishaal's Almanac, which starts next series of quest. The item for some reason does not drop, tried killing the mob multiple times.

**How it should work:**
Talonpriest Ishaal should drop an item called Ishaal's Almanac, in order to continue in the next series of quests.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11005 - the kill quest
https://cata-twinhead.twinstar.cz/?npc=23066 - the mob
https://cata-twinhead.twinstar.cz/?item=32523 - the item

**Comment by DorizarN** [comment]
Got the item on my first kill.

**Comment by PanJanuszek** [comment]
fixed 09.03.2024
