### ISSUE TITLE
[Enchant][Spell] Enchant weapon: mending + soul link

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2847]
**Description:**
Mending on weapon heals the warlock when the warlock is hit if soul link is active. This seems to happen both from direct attacks as well as dots.

**How to reproduce:**
Get hit by anything while under the effects of soul link

**How it should work:**
I'm pretty sure it shouldn't work like that. Soul link is really not damaging an enemy

**Database links:**

https://cata-twinhead.twinstar.cz/?item=52747
https://cata-twinhead.twinstar.cz/?spell=19028

![obraz](https://user-images.githubusercontent.com/61705382/230127225-534e8266-ec82-4a95-ad84-5c8ce9e3e764.png)

**Comment by melezdev** [comment]
Same with lightweave: https://cata-twinhead.twinstar.cz/?spell=75172

**Comment by UltraNix** [comment]
Fixed.
