### ISSUE TITLE
Teleport - Functional Test Bug - Teleport From The Ebon Hold to Stormwind does not work

### ISSUE THREAD

**Issue by ReiDyxSrb** [gamefreedomgit/Maelstrom#2848]
Teleport - Functional Test Bug - Teleport From The Ebon Hold to Stormwind does not work

Priority: Medium

Severity: Low

Server: Maelstorm

Time: 19:20 04/05/2023

Character Name: Reidyx

Class: Death Knight

Level: 84

Reproduce rate: 100%

Teleport From The Ebon Hold to Stormwind does not work

Steps to reproduce: 

	1. Rich The Ebon Hold
	2. Find the Stormwind City teleport
	3. Position the character next to Stormwind City teleport
	4. Select Stormwind City teleport with right click

Actual Result: 

Character is not teleported to Stormwind City

Expected Result: 

Character is teleported to Stormwind City

**Comment by UltraNix** [comment]
Fixed.
