### ISSUE TITLE
Archaeology. Incorrect direction of the pointer

### ISSUE THREAD

**Issue by Furytyan** [gamefreedomgit/Maelstrom#2850]
Eastern Plaguelands - The Infectis Scar (a place to dig) cant work , the pointers do not work correctly and indicate outside the red zone.
As far as I know I'm the only one with this problem but GM from the game sent me here.

**Comment by Waroxx-QA** [comment]
Hello,
Can you record it ?

**Comment by Furytyan** [comment]
Its work today =/
