### ISSUE TITLE
chogall critical bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#2851]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**boss and players are falling under the map at cho gall

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Fixed 6.04.2023
