### ISSUE TITLE
[Raid][Boss] Chogall platform bugged, boss falls down the platform

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2852]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Normal difficulty, Chogall platform is bugged players and boss fall down under map worked correctly week ago but with today update with Heroic raids its broken
We had few tries I fell down by using charge others simply fell down, one guy was in siniestra boss room xd
Video:
https://www.youtube.com/watch?v=flGS8PNImlA
https://www.youtube.com/watch?v=TnRk8K2raP8

**Comment by Sketish** [comment]
Fixed 6.04.2023

**Comment by Nenze** [comment]
@Sketish still not fixed

**Comment by Nenze** [comment]
we killed boss, only star in the middle is bugged
