### ISSUE TITLE
Hunter scatter/flare bug

### ISSUE THREAD

**Issue by elunee12** [gamefreedomgit/Maelstrom#2855]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Huntter scatter bugs some times when u scatter someone it breaks alone it says u dmg the guy for 800 dmg and it breaks the scatter like that and the flare when u launch it in any arena sometimes when it touch the floor it dispear instantly

**How to reproduce:**

**How it should work:**

when u scatter someone it should not break if u dont have any trinket that makes it break and the flare when u launch it should never dispear when it touch the floor in arenas thank you
**Database links:**

**Comment by UltraNix** [comment]
@elunee12 Do you have combat log with that Scatter Shot thing? What damage broke the Scatter?

**Comment by UltraNix** [comment]
No further info - closing.
