### ISSUE TITLE
Mage buff Arcane Brilliance doesn't give increased spellpower.

### ISSUE THREAD

**Issue by Bodify** [gamefreedomgit/Maelstrom#2857]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mage buff Arcane Brilliance doesn't give increased spellpower.

**How to reproduce:**
Log a mage and buff up, no spellpower increase.

**How it should work:**
Should increase spellpower by 6% as tooltip states.

**Database links:**

**Comment by Waroxx-QA** [comment]
Just checked it, Arcane Brillance gives spellpower, but when you remove the buff, you keep that 6% spell power, even if you try buffing again or removing it, it will be the same, relogging fixes this.

**Comment by UltraNix** [comment]
Fixed.
