### ISSUE TITLE
(BIG) Keeping buffs when Partner is Dead

### ISSUE THREAD

**Issue by Shatago** [gamefreedomgit/Maelstrom#2858]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

players are keeping aura buffs like true shot aura after their partner has died

**How to reproduce:**
Get a Hunter in an arena with you
Kill the hunter
You keep their trueshot aura

**How it should work:**
Players should lose aura’d buffs once the player with the buff has died 

**Database links:**

https://www.twitch.tv/videos/1784829258 - 38:40

**Comment by UltraNix** [comment]
That aura is passive and it's active even if hunter is dead.

**Comment by Shatago** [comment]
incorrect - if the hunter is dead his buffs should NOT be acitve

https://youtu.be/H8ZIH_-CBfU - see mintute 21:10 where the hunter is alive and the rog has the buff

then 21:40 where the hunter dies and the rogue loses the buff
