### ISSUE TITLE
Ret Paladin Inquisition doesn't increase holy damage at all!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2860]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Inquisition doesn't increase holy damage at all, this is a gamebreaking bug and it must be fixed as soon as possible, it ruins Ret both in pve and pvp.

**How to reproduce:**

SS proof: 

![sealdmg](https://user-images.githubusercontent.com/67479994/230396722-dffa23cb-0378-44aa-9f97-471c43372134.PNG)

![sealdmgwithinqu](https://user-images.githubusercontent.com/67479994/230396747-3d83e331-fd1a-4cdd-b577-e1a4a01cb1bb.PNG)

As you can see seal dmg is the same....

**How it should work:**

It should increase all holy damage done by 30%.

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=84963

**Comment by Sketish** [comment]
![image](https://user-images.githubusercontent.com/122209088/230460039-b5d31618-664f-409d-93b8-4d38927a7210.png)
![image](https://user-images.githubusercontent.com/122209088/230460242-5b21bd74-85ea-4445-a732-1fdd294a2be2.png)

If you refresh dot with auto attack it's increasing dmg by 30% so Inquisition is working correctly
