### ISSUE TITLE
This mission makes the game crash

### ISSUE THREAD

**Issue by Afromercamar** [gamefreedomgit/Maelstrom#2864]
https://www.wowhead.com/es/quest=27714/el-d%C3%ADa-que-vino-alamuerte-la-historia-real

This mission is from the gnome in the Badlands.

**Comment by Waroxx-QA** [comment]
didn't make me crash, but i couldn't do the quest

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/230656087-8f52a138-55e7-4f8f-a0b7-277c7ce32c94.png)
Just tested - no crashes and completed without problems.
