### ISSUE TITLE
Bugged quests worgen starting zone

### ISSUE THREAD

**Issue by RaguelWoW** [gamefreedomgit/Maelstrom#2866]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bugged quest i found: **(1)Unleash the beast** Most forsaken combatants are stuck at one place and always reset hp only ones working are    ones that are fighting other npcs 
                                     **(2)Two by sea** same with catapult operators  they cant be killed i found only one that could be.
                                     **(3)Losing your tail** Ranger spawns at weird position and won't attack you, but can be aggrod and killed
                                     **(4)Betrayal at Tempest's reach** attacking Npcs that need to be killed for quest completition won't respond to you and will reset hp until they come to starting position of their patrol route.
                                     **(5)They have allies, so do we** orcs sometimes don't take dmg from projectiles and get cnockbacked instead and catapults are imune to catapults shots from farther distance.
                                     **(6)Engame** mobs on first stage of boarding to zeppelin have weird hitbox its farther then their model and after destroying  zeppelin i was shapeshifted and wyvern that should take me to quest giver could be used like ground mount and i was able to move forward and bacward only. Don't know if same bug occures with no shapeshifting.

**How to reproduce:**
**(1)Unleash the beast** and **(2)Two by sea** simply attack mobs that dont have defender gilneans near them on shore near two boats.
**(3)Losing your tail** step on trap and spawn ranger.
**(4)Betrayal at Tempest's reach** attacking npcs that need to be killed when they are not standing on their starting(spawn) position.
**(5)They have allies, so do we** simply shoot at orcs and you can observe that some of them are imune to dmg they just knockback and try to hit catapults from farther distance.
**(6)Engame**  board zeppelin and you should have problem to hit first mobs from melee range and complete scenario shapeshifted and wyvern won't work don't if its by shapeshifting so try it without it too.

**How it should work:**
**(1)Unleash the beast** and **(2)Two by sea** mobs should be killable.
**(3)Losing your tail** mob should spawn near you and attack you.
**(4)Betrayal at Tempest's reach** mobs should respond to your attacks always.
**(5)They have allies, so do we**  mobs should be damaged with every hit
**(6)Engame** mobs should have normal hitboxes and wyvern should carry you to questgiver.

**Database links:**
(1)https://www.wowhead.com/quest=14369/unleash-the-beast
(2)https://www.wowhead.com/quest=14382/two-by-sea
(3)https://www.wowhead.com/quest=24616/losing-your-tail
(4)https://www.wowhead.com/quest=24592/betrayal-at-tempests-reach
(5)https://www.wowhead.com/quest=24681/they-have-allies-but-so-do-we
(6)https://www.wowhead.com/quest=26706/endgame

**Comment by Rezapaper** [comment]
Im stucked on two by sea quest cant do anything … opened a ticked no answer yet . There no solution!!

**Comment by RaguelWoW** [comment]
> Im stucked on two by sea quest cant do anything … opened a ticked no answer yet . There no solution!!

If its still bugged find catapult on most left side from map point there should be one npc that can be killed and you can catapult to the ship

**Comment by Voltarious** [comment]
I had the same problem (1)Unleash the beast and (2)Two by sea, but once I relogged, things worked again. The mobs stopped regenning health, and didn't stay in place when attacked
