### ISSUE TITLE
bwd bug

### ISSUE THREAD

**Issue by simon900525** [gamefreedomgit/Maelstrom#2867]
![image](https://user-images.githubusercontent.com/130083077/230441338-ed74b1ac-696c-4d00-b55e-aa0250f34931.png)
![image](https://user-images.githubusercontent.com/130083077/230441424-15be2d5a-7acb-4b8d-8cb2-b8b434c7ba22.png)
![image](https://user-images.githubusercontent.com/130083077/230441452-7eb3150a-85b1-4912-9701-816dad2c012b.png)

this boss has some bug.
rogue's blade flurry can't cover the melee attack
.
but in fact,its would be cover the melee attack

**Comment by simon900525** [comment]
rogue's blade flurry can't cover the melee attack,and this boss,whatever we focus boss or adds, we cast blade flurry,we can't cover the melee attack.

**Comment by Alandiel** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3004.
