### ISSUE TITLE
PVP - Blind miss on hitcap

### ISSUE THREAD

**Issue by richysoscary** [gamefreedomgit/Maelstrom#2869]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blind missed on hitcap.

**How to reproduce:**

**How it should work:**

**Database links:**

![Screenshot_5](https://user-images.githubusercontent.com/129841569/230461568-ec7bcd2e-c30e-47df-8f8f-3747f847d38c.png)

**Comment by UltraNix** [comment]
@richysoscary What's the name of the addon?

**Comment by Shatago** [comment]
Could be on a night elf player who has a 2% chance of spells missing?

**Comment by Shatago** [comment]
> 
Details

**Comment by Shatago** [comment]
Or even a blind into evasion could get missed

**Comment by richysoscary** [comment]
Evasion blind interaction wasnt a thing in cata??

**Comment by UltraNix** [comment]
Your hit chance is one factor. The other one is your target's auras.
Night Elves have a passive called `Quickness` that reduces the chance to be hit by 2%.

**Comment by UltraNix** [comment]
No further info - closing.
