### ISSUE TITLE
Maloriak HC - Abberations

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2870]
Abberations buff Growth Catalyst should only work on abberations,boss and Prime Subjects( adds from second phase). Currently this buff also works on Vile Swill when it shouldn't

![image](https://user-images.githubusercontent.com/122209088/230462039-ff88ea45-2a88-4beb-9ea0-10f08ff224e1.png)

**Comment by UltraNix** [comment]
Fixed.
