### ISSUE TITLE
[Hunter][Core] Cannot tame a 5th pet, says "you have too many pets already"

### ISSUE THREAD

**Issue by Exorcista** [gamefreedomgit/Maelstrom#2871]
**Description:** When trying to tame a new pet, having 4 on my Call Pet Spell (https://www.wowhead.com/wotlk/spell=67777/call-pet) displays a message saying i have too many (like i had 5 already).

I tried everything suggested by GMs via ingame ticket including:

Reseting my talents fully, chaging spec, abandon all my pets, stabling all my current pets, nothing helped

**How to reproduce:** As far as i can tell it started when 2nd boss on Deadmines put a bomb on my chest and my current pet at that time (A wolf) dissapeared completely from my Call Pet Spell

**How it should work:** Should let me tame a 5th pet, this is key for raiding/pvp please

**Database links:** https://www.wowhead.com/wotlk/spell=67777/call-pet

**Aditional info:** contact me ingame as: Exor

**Comment by Exorcista** [comment]
> @Exorcista I suspect you have learned `Call Pet 5`?

you tell me...

![petbug1](https://user-images.githubusercontent.com/6818405/232661062-def0b578-9508-4fe4-9667-e2051b7ac5dc.jpg)

i'm still unable to tame a 5th pet to this day...

**Comment by UltraNix** [comment]
@Exorcista Ping me on Discord.

**Comment by Exorcista** [comment]
> @Exorcista Ping me on Discord.

just did bro

**Comment by UltraNix** [comment]
@Exorcista I was off - do it once again.

**Comment by UltraNix** [comment]
Resolved.
