### ISSUE TITLE
Valor agility ring not in-game

### ISSUE THREAD

**Issue by Taelanor** [gamefreedomgit/Maelstrom#2872]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Title, the valor vendor is not selling the agility ring " Hornet-Sting Band "

**How to reproduce:**Talk to the valor vendor and look at the non existent ring

**How it should work:**the vendor should sell the agility ring " Hornet-Sting Band "

**Database links:** https://cata-twinhead.twinstar.cz/?item=68812

**Comment by Waroxx-QA** [comment]
Duplicate - #2776
