### ISSUE TITLE
cho gall

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#2873]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**  vho gall still bugged ,we fall under the map , and if mage blinks he falls , so it s not fixed completely

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Was that on 25 man ?
