### ISSUE TITLE
bug classe  arcane mage 

### ISSUE THREAD

**Issue by firedragoon10** [gamefreedomgit/Maelstrom#2874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**spell power stat arcane mage 

**How to reproduce:** arcane  mage must be wth hight spell power spec than fire and frost mage but he si not he have the same spell power  stat  like fire and frost .......... sorry icant found any site web for this  bug but i play mage from 2008 and i know well this   classe  

**How it should work:** so should  arcane mage should be wth hight  spell power  spec than fire and frost  and i hope can check  about that 

**Database links:**

**Comment by Waroxx-QA** [comment]
Doesn't work like that, read your talents please, high spell power is when you use your cooldowns, such as "Arcane Power" and "Improved Mana Gem" for example.

**Comment by firedragoon10** [comment]
ye i know all this  but  on others server when you change arcane sp  your spell power  stat be big than fire and frost   only if this  just  bug  on others servers  but all know that arcane is  hight  on single target  damage  vs aoe damage  anyway  thx
