### ISSUE TITLE
[Core] Tab Targeting

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#2875]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Recently started playing Warlock and it seems Tab Targeting is broken.
Which each use of tab it should target diffrent NPC till the first one targeted
A > B > C > D > A  - Like this but it works randomly which makes it very hard for warlocks and other dot based classes

**Comment by UltraNix** [comment]
Tab targeting has nothing to do with server - client decides what to target.
I just tested and without any camera shaking/moving - works okay.
