### ISSUE TITLE
[Priest][Spell] Prayer of Mending: Non-Group Behaviour

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#2876]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The charge or "hop" behavior of Prayer of Mending, while not in a Party or Raid, appears to have an issue. Prayer of Mending is not always* healing the Priest on the next damaging attack. Instead, the Prayer of Mending heal will proc only after the second attack. This behavior is detrimental to the Priest in two ways:

1) The Priest is healed only after a second damaging attack, and 

2) Priests leveraging [Glyph of Prayer of Mending] will not benefit from the increased 60% healing that occurs only on the first charge of Prayer of Mending.

*The issue is sporadic and does not appear to be happening in group settings.

**How to reproduce:**
While dueling, tested 10 casts of Prayer of Mending and damaging attacks -- results below indicate that the initial Prayer of Mending charge failed to heal the Priest seven out of 10 times.  

``` 
(Amount Healed)

5376 (Failed 1st Proc)
7266 (Successful 1st Proc + Glyph Increase)
5376 (Failed)
5376 (Failed)
5376 (Failed)
7266 (Successful)
7266 (Successful)
5376 (Failed)
5376 (Failed)
5376 (Failed)
```

**How it should work:**
Prayer of Mending charges, while not in a group setting, should always proc off of the first damaging attack.

**Database links:**
[PoM] https://cata-twinhead.twinstar.cz/?spell=33076
[Glyph] https://cata-twinhead.twinstar.cz/?item=42417

**Comment by UltraNix** [comment]
Hmm, but PoM stays: `Prayer of Mending jumps to a party or raid member `. It should work between players not in group/raid?

**Comment by MaelstromAbbey** [comment]
@UltraNix Non-group behavior of PoM should proc on the 1st damaging attack to the Priest, then dissipate completely -- no hopping like in a party or raid. It's essentially a one time heal (after damage) with a 10 second cool down. 

https://imgur.com/a/f95nDWe

**Comment by UltraNix** [comment]
Yeah, yeah - just realized that after some tests.
