### ISSUE TITLE
Lieutenant General Andorov not spawning in AQ20

### ISSUE THREAD

**Issue by Campyy** [gamefreedomgit/Maelstrom#2877]
Copied this from another server because this one seems to be having the same issue, ive tried on two different characters with no luck. 

Links:
Lieutenant General Andorov NPC ID: 15471
https://www.wowhead.com/npc=15471/lieutenant-general-andorov

https://wow.gamepedia.com/Lieutenant_General_Andorov

What is Happening:
In the Ruins of Ahn'Qiraj (AQ20), LtGen Andorov is not spawning after killing Kurinnaxx.

What Should happen:
After killing Kurinnaxx (NPC ID 15348), the first boss of AQ20, Lieutenant General Andorov and four Kaldorei Elite NPCs (ID 15473) should spawn right next to Kurinnaxx and run to the stairs between the Kurinnaxx boss room and General Rajaxx boss room. You can then talk to LtGen Andorov to start an event where he helps you kill General Rajaxx. After defeating the Rajaxx, Andorov turns into a vendor where you can buy blacksmithing plans and some consumables.

Although Wowhead and Wowpedia say Andorov spawns after killing Kurinnaxx, several Youtube videos I found show him and the four bodyguards standing near the boss before it is killed:

https://youtu.be/MMqJfX149hw?t=1275

https://youtu.be/bBX3V6XX-VA?t=511

**Comment by Campyy** [comment]
I understand this isn't the biggest priority as it is old content and you can still complete the raid but this NPC does offer buyable items that cannot be obtained any other way. Specifically I want the shield plan he sells to finish my transmog..

**Comment by PanJanuszek** [comment]
fixed 20.05.2024
