### ISSUE TITLE
Food Crate

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2879]
So while questing in Azuremyst Isle I have found 2 Food Crates that I could click on, but nothing happened after doing so. Even after relogging did this happen still. I am going to assume all Food Crates in the zone may be affected for some reason.

**How to reproduce:** Go to Azuremyst Isle (my last one found at the time of typing this up was at 27.29 66.2) and click on the food crate.

**How it should work:** They should be openable and contain food items.

**Database links:**
https://cata-twinhead.twinstar.cz/?object=3719

**Comment by Afgann** [comment]
fixed
