### ISSUE TITLE
Nolkai's Words quest dose not reward Nolkai's Box.

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2882]
**Description:** Upon turning in the quest Nolkai's Words, the quest reward is supposed to be Nolkai's Box which contains 3 items. Currently it dose not. 

**How to reproduce:** Complete the quest chain that leads up to Nolkai's Words that starts from the quest Explorers' League, Is That Something for Gnomes?

**How it should work:** The quest should have the reward of Nolkai's Box and in the box should be the 3 listed items in the link below

**Database links:**
https://www.wowhead.com/quest=9561/nolkais-words
https://cata-twinhead.twinstar.cz/?item=23846
https://cata-twinhead.twinstar.cz/?quest=10063

**Comment by Afgann** [comment]
fixed
