### ISSUE TITLE
Game crashes for everyone in Shadowfang Keep

### ISSUE THREAD

**Issue by msh2038** [gamefreedomgit/Maelstrom#2883]
**Description:**
SFK crashes game for everyone

**How to reproduce:**
After 3rd boss, have everyone teleport out, and teleport back in. Taking the NPC teleport to chapel skips all the trash and takes you to 4th boss instantly, however after the 4th person takes the teleport, everyone in the party has their client crash. Not sure if this is a heroic only thing as I havent done it on normal on this server.

**How it should work:**
Shouldnt crash.

**Comment by msh2038** [comment]
This happens with pets for some reason, just did it and it didnt crash when I dismissed.

**Comment by UltraNix** [comment]
@msh2038 Still happens?

**Comment by UltraNix** [comment]
No further info - closing.
