### ISSUE TITLE
Cho'gall - Massive Floor Bug

### ISSUE THREAD

**Issue by AzureScyclone** [gamefreedomgit/Maelstrom#2884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cho'gall and his adds decide to go swimming through the floor during the fight, having drinks with Sinestra, and overall making the fight feel like cleaning up a taco-bell enema. We had tried several locations in the room, and while we managed to keep Cho'gall standing on solid ground for a moment, the adds immediately after spawning would take a nose dive straight through the floor (way outside the bounds of the center area)

**How to reproduce:**
Just even attempting the cho'gall fight

**How it should work:**
Last I checked, swimming through solid ground is not permitted by the Twilight Council.

**Database links:**

**Comment by Waroxx-QA** [comment]
Fixed - It will be applied on the next restart.
