### ISSUE TITLE
deepholm alliance gunship

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#2886]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** no npc at alliance gunship in deepholm , cant do quests

**How to reproduce:**

**How it should work:**

**Database links:**
![image](https://user-images.githubusercontent.com/129559513/230569815-81506a2b-e1aa-4825-94f1-1d7ccacca847.png)

**Comment by xmrshoot** [comment]
never mind , npc has apered now

**Comment by Sketish** [comment]
Issue solved by author
