### ISSUE TITLE
Valiona and Theralion - Twilight portal

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2887]
During whole fight in Twilight realm, 2 Collapsing Twilight portals should spawn that last 1 minute and the dissapate. After each dissapate another portal should spawn making players able to leave twilight realm whenever they want. Currently portal duration is timed and after they dissapear players have to wait for Deep Dreath or Dazzling Destruction to make portal spawns inside realm.

Source:
https://www.youtube.com/watch?v=HGMo-7nxukQ|
https://www.youtube.com/watch?v=UzQIY7Qhnec

**Comment by UltraNix** [comment]
Fixed.
