### ISSUE TITLE
Tini Smalls in Area 52.

### ISSUE THREAD

**Issue by Paniqq** [gamefreedomgit/Maelstrom#2888]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Cant open the shop from Tini Smalls in Area 52, she is supposed to sell cloth/leather level 60 pvp Replica's Sets, but you cant interact with her, i checked other shop Plate/Mail and i works normal.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
