### ISSUE TITLE
Baron Ashbury - Shadowfang keep

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2889]
Asphyxiate should bring players to 1hp, currently dmg is resisted by shadow resistance making boss much easier.
![image](https://user-images.githubusercontent.com/122209088/230619389-ccbfaf4f-4b1a-4d34-87a5-22cf661dda1a.png)

Also sometimes if  you push boss under 25% he doesnt cast Calamity
![image](https://user-images.githubusercontent.com/122209088/230619370-e7b9f099-9415-4187-a5de-87229a254fdc.png)

**Comment by UltraNix** [comment]
Fixed.
