### ISSUE TITLE
The Thrill of Discovery

### ISSUE THREAD

**Issue by Kassapin** [gamefreedomgit/Maelstrom#2892]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest is given by Harrison Jones in Uldum after few chain quests.

**How it should work:**
When player takes the quest it requires player to discover middle section where the machine is, north and south artifact.

**Database links:**
https://www.youtube.com/watch?v=62XwccAsXuo

This is example from Youtube video showing how its suppose to be done.

**Comment by B-Jimmy-B** [comment]
Quest is not working. I visit the 3 places needed for the quest but never receive the ‘examined’

**Comment by PanJanuszek** [comment]
Works as expected. Please open it in case of spanish & russian client . It's client sensitive
