### ISSUE TITLE
TBC raids - The eye

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#2894]
Hello, I'd like to post a full bug report on The eye Boss by boss

1.Al'ar
Fully scripted

2.Void Reaver
Only uses the AOE silence which makes any dps/tank unable to cast.

3.High Astromancer Solarian
Fully scripted

4.Kael'thas Sunstrider
Encounter is bugged, once first "add" dies nothing happens.

Only Death knights aren't able to dot the bosses.

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
