### ISSUE TITLE
Baron Aquanis not spawning

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#2898]
**Description:**
In the dungeon "Blackfathom Deeps" Baron Aquanis is not spawning

**How to reproduce:**
Pick up the quest "Among the ruins" inside the dungeon, go to "Moonshrine Ruins" zone and pick up the Fathom Core

**How it should work:**
When you pick up the "Fathom Core", it should spawn "Baron Aquanis".

**Database links:**
[https://www.wowhead.com/classic/quest=6922/baron-aquanis#comments](url)

**Comment by PanJanuszek** [comment]
fixed 15.02.2024
