### ISSUE TITLE
Guild reputation from killing raid bosses 

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2899]
If you have guild raid group  each killed boss should reward with 60 guild reputation. Currently there is no guild reputation given after killing raid bosses.

Source:
https://youtu.be/uqvmBnxUabE?t=294
https://youtu.be/h6fGunTR068?t=509

**Comment by Sketish** [comment]
After killing 13 bosses on reset day, I had 0 progress in guild rep.

**Comment by UltraNix** [comment]
Hmm.
For 10 man, you need at least 8 people from the same guild and map, for 25 man - 20. I believe these conditions were met?

**Comment by UltraNix** [comment]
Fixed.
