### ISSUE TITLE
Quest Sniffing Them Out not offered by Packleader Ivar Bloodfang in SFK

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#2901]
Just like the deadmines quests, the SFK ones also seem to be MIA for alliance.. And these ones are more important as it's much harder to get Gilneas rep than Stormwind.

**How to reproduce:** Enter Shadowfang Keep as an alliance and speak with Packleader Ivar Bloodfang

**How it should work:** The NPC Packleader Ivar Bloodfang should offer the quest Sniffing Them Out to alliance level 16+

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27917
https://cata-twinhead.twinstar.cz/?npc=47006

**Comment by EdyGlockenspiel** [comment]
Incorrect label, this quest and it's follow ups where added in cata. 
https://www.wowhead.com/quest=27917/sniffing-them-out "Added in patch 4.0.3.13277" This is cata content, not pre cata content.

**Comment by PanJanuszek** [comment]
Works as expected
