### ISSUE TITLE
Somethings wrong about ARENA 2v2 RATING LOSS

### ISSUE THREAD

**Issue by dadawdawdwada** [gamefreedomgit/Maelstrom#2902]
**Description:**
Arena Calculations for RATING LOSS seems to be broken.
I'm queuing 2v2 and I loose the game. I get -35 my Teammate -0. How?

- Me                   - 1768 Rating ( Picture2 )
- My TeamMate - 1905 Rating ( Picture3 )
- Our MMR 1884 - ( Picture1 )

( See this link for Pictures https://imgur.com/a/lrPTSE0 )

**How it should work:**

Shouldn't I be the one who gets -0 and not my Teammate? I pretty sure that's how it should be.

**Comment by melezdev** [comment]
I think it's visual, when someone leaves the arena their rating change is displayed as -0
