### ISSUE TITLE
Sentinel Basic Care Package can contain nothing

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2903]
The box Sentinel Basic Care Package from the quest of the same name can contain nothing, which is weird because this one should always contain the exact same item and a 20 stack of said item.

**How to reproduce:** Complete the quest Sentinel Basic Care Package and open the box.

**How it should work:** 100% chance to obtain a 20 stack of Warsong Gulch Field Ration

**Database links:**
https://cata-twinhead.twinstar.cz/?item=19150
https://cata-twinhead.twinstar.cz/?item=19062

**Comment by Afgann** [comment]
fixed
