### ISSUE TITLE
Rocky Upheaval at Crimson Expanse, Deepholm

### ISSUE THREAD

**Issue by heikki2001** [gamefreedomgit/Maelstrom#2908]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Greetings, i was trying to do speak to Gorsik the Tumultuous upon the Crimson Expanse, Deepholm and then i found the golden question mark on him and couldn't speak to him, fix this bug please!!

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any snap of this issue ?

**Comment by UltraNix** [comment]
No further info - closing.
