### ISSUE TITLE
Quest Burn, Baby, Burn! is bugged

### ISSUE THREAD

**Issue by cybroook** [gamefreedomgit/Maelstrom#2911]
The quest Burn, Baby, Burn! does not work probably. Not all of the boxes in the area acually gets counted. So you are forced to wait for all to respawn in order to get 8/8.

the animation etc is fine and all just the fact it dont count towards the quest. 

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=25622/burn-baby-burn

**Comment by EdyGlockenspiel** [comment]
It seems that if the box has the buff for being burned you wont get credit. But using the item near the box but facing away seemed to work, maybe.
