### ISSUE TITLE
Darkmoon Card: Volcano proc issue

### ISSUE THREAD

**Issue by MokryJD** [gamefreedomgit/Maelstrom#2915]
Dunno what else i can say its just not procing for some reason

https://www.youtube.com/watch?v=t-ag2gro5LI

**Comment by MokryJD** [comment]
Did some testing rn with 3minute rotation and it just don't procs 
![image](https://user-images.githubusercontent.com/128102932/230729109-13bec770-f0a9-4e78-bf28-29360fbf67fb.png)

**Comment by Waroxx-QA** [comment]
The trinket procs normally on cd used on a Mage, i think it's a class specific issue.

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/231240416-197bbb25-ec1f-41ef-b31b-ae22fa2628d2.png)
Got no problem with proccing. Must be something else.

**Comment by staR1336** [comment]
Right, so i spent two hours testing volcano and results are as confusing as ever

First on Mage, Procced pretty much as it should, maybe after 3-4 spells - kept going, an estimated ICD of 20s, procs again, all is good

Second on Warlock, procced way later, around 15 spells in - kept dpsing for 10 minutes, volcano procced less than mage, but still procced enough to be blizzlike (bad rng)

Thirdly, on Priest - and here it begins - it would not proc at all. in truth, it only procced ONCE after 5 minutes - then never again for another 10 minutes.

starting to believe it was depending on the class, i was going to make a balance druid but i thought of re-testing my mage

Fourth test - SAME MAGE AS FIRST - It would not proc at all. 10 minutes of scorching, fireballing, absolute no procs.

i thought of re-equipping, re buying the volcano even (albeit not very doable on live) , swapping the item slot with the second trinket. NOTHING

Fifth test- i made another mage. - same results. ZERO

Sixth test - i logged warlock again, and to my surprise i got same behaviour as before. volcano took a bit, but it procced after 10-15 spells. after its 20s or so of internal cooldown, it procced again along the line.

Seventh test - i decided to relog the priest and try again, but same happened - no procs at all

Eight and final test - i relogged my main mage that worked perfectly first time yet again, and spent a good 20 final minutes dpsing. it did not proc once.

Note: around my 5th test i asked a friend to log ptr with me and do the same test. She did not get a single proc the whole time either

I jokingly declared that volcano simply went out of business after 11pm, and went to sleep.

Terribly Sorry this doesn't help you in any way, devs.

**Comment by kirogthar** [comment]
It still does not proc for some people. Worked for my boomie and ele shaman, but on my warlock it does not proc. 
https://youtu.be/dfqMz8OcwwI
Here is proof video.

**Comment by raller1006** [comment]
It procs for mages in PvP also by non damaging abilities such as; Polymorph, Counterspell & Spellsteal --> really crucial in arenas, because right now i'm breaking saps with Spellsteal and i'm breaking my own polymorph with this trinket. Kinda sucks because this trinket is hard bis for frost mages in pvp

U need to test this in a duel scenario (player vs player). Doesn't work on npc's.

**Comment by UltraNix** [comment]
@raller1006 @kirogthar @staR1336 please, retest it.

**Comment by UltraNix** [comment]
I assume it's fixed.
