### ISSUE TITLE
Hunter and Shaman Roots dont DR in PvP! Needs asap fix!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2916]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hunter and Ele shaman roots don't DR in pvp, which means that you can rooted forever in an arena game for an example, like it happened to me today in solo que...

Please fix this asap, thank you.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any clip of that ?

**Comment by Renehadox** [comment]
> Can you provide any clip of that ?

How?

I don't have any video recording program...

**Comment by UltraNix** [comment]
@Renehadox What roots?

**Comment by UltraNix** [comment]
You wrote about `Hunter and Ele shaman roots` - I'm asking about these roots.

**Comment by Renehadox** [comment]
> You wrote about `Hunter and Ele shaman roots` - I'm asking about these roots.

Hunter traps and and ele shaman earthbind totem roots...

**Comment by UltraNix** [comment]
Earthbind Totem:
1. cast
![WoWScrnShot_041223_114254](https://user-images.githubusercontent.com/80540499/231420241-0ff041af-d3ac-450d-94b0-68a9d4ea31a4.jpg)
2. cast
![WoWScrnShot_041223_114301](https://user-images.githubusercontent.com/80540499/231420288-3571e96b-2b2a-45fb-af5e-6e6ffd1b851b.jpg)
3. cast
![WoWScrnShot_041223_114305](https://user-images.githubusercontent.com/80540499/231420336-0da67edc-e598-4fb2-b5c0-1286e1250661.jpg)

Hunter Freezing trap:
1. cast
![WoWScrnShot_041223_114631](https://user-images.githubusercontent.com/80540499/231421137-6220a120-fea8-4884-8c77-338fb65efda5.jpg)
2. cast
![WoWScrnShot_041223_114642](https://user-images.githubusercontent.com/80540499/231421176-decba7e5-d7e9-4a2f-9237-3c4856ab022c.jpg)
3.cast
![WoWScrnShot_041223_114649](https://user-images.githubusercontent.com/80540499/231421224-c1e70e18-8e00-41ef-91d3-98487f485ccb.jpg)

I don;t see any bug here. Please, retest it and if it's still bugged for you, just post some screenshots, showing us it's broken.

**Comment by Renehadox** [comment]
Not hunter freezing trap, hunter ice trap and snake trap when talented with " entrapment " 

They don't DR with ele shaman earthbind totem.

**Comment by UltraNix** [comment]
So next time be more precise :)

**Comment by Renehadox** [comment]
> So next time be more precise :)

Yeah, I am sorry, I found this  bug in arena, so you need like 3-4 players to test it, one player vs ele shaman / hunter with the talent entrapment.

**Comment by Renehadox** [comment]
I am sorry i see this on Discord as a fix, can you try to test if ele shaman, hunter and druid roots share dr with each other?

Author: UltraNix
Message: Core/Spells: Shaman's Earthgrab should share DR with Hunter's Entrapment.

gamefreedomgit/Maelstrom#2916 

Can you trest if they share DR with druid entangling roots please?

**Comment by UltraNix** [comment]
Fixed.
