### ISSUE TITLE
The quest "Last Ditch Effort" bugged

### ISSUE THREAD

**Issue by cybroook** [gamefreedomgit/Maelstrom#2918]
The quest Last Ditch Effort is not working. When you accept the quest nothing happens.

When accepting the quest, you should immediately get on a flying mount that should fly you down and watch the horde bomb the area.
 

**Database links:**
https://www.wowhead.com/quest=25891/last-ditch-effort

**Comment by EdyGlockenspiel** [comment]
This quest logs out the rest of the quests in the zone, this includes the Gilneas rep quests, which is generally why anyone would go through all the effort to get to this point questing in the zone to begin with as alliance..

**Comment by UltraNix** [comment]
#2167
