### ISSUE TITLE
All of the bloodthirsty gladiator (Blue PVP Gear + Epic Weapon) Will only allow you to reforge Strength to Spirit

### ISSUE THREAD

**Issue by RyanWFRD** [gamefreedomgit/Maelstrom#2919]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
All of the bloodthirsty gladiator (Blue PVP Gear + Epic Weapon) Will only allow you to reforge Strength to Spirit
![image](https://user-images.githubusercontent.com/89116788/230732892-30a74da7-4ab9-4aa0-a1a7-f43c80dfab8f.png)

**How to reproduce:**
Attempt to reforge any blue piece of bloodthirsty gladiator pvp gear (I am a warrior) As well as the epic bloodthirsty gladiator sword. Unknown if the conquest gear has the same issue.

**How it should work:**
Reforging should allow you to reforge secondary stats to other secondary stats, definitely not strength to spirit. Esp in a warriors case.

**Database links:**
https://wowpedia.fandom.com/wiki/Reforging

**Comment by richysoscary** [comment]
Bro just reload xd

**Comment by Stega23** [comment]
This is cata client bug(afaik), you have to relog to fix it and reforge normally

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/231241510-29c7cff0-b6a5-4d9a-8526-baf06c8a540c.png)
I believe something with your client.
