### ISSUE TITLE
the quest Thal'darah's Vengeance is bugged

### ISSUE THREAD

**Issue by cybroook** [gamefreedomgit/Maelstrom#2920]
The quest Thal'darah's Vengeance is bugged. You cant enter the glaive throwers. You are forced to go down and kill them yourself. Now the Krom'gar Demolishers health resets instantly so you need to one shot them in order to kill them.

**Database links:**
https://www.wowhead.com/quest=25925/thaldarahs-vengeance

**Comment by EdyGlockenspiel** [comment]
Can confirm, Darnassian Glaive Thrower is unable to be entered.. https://cata-twinhead.twinstar.cz/?npc=35150#abilities

**Comment by EdyGlockenspiel** [comment]
And that the Demos are unkillable..

**Comment by PanJanuszek** [comment]
fixed 22.04.2024
