### ISSUE TITLE
The quest Purity From Corruption is missing

### ISSUE THREAD

**Issue by cybroook** [gamefreedomgit/Maelstrom#2922]
The quest Purity From Corruption is not appearing by the NPC.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=28119/purity-from-corruption

**Comment by Tutam507** [comment]
Once the quest Forces of Jaedenar is completed the interface doesn't give the next quest Purity From Corruption and the NPC Andalar Shadevale doesn't offer it either, this totally halts the Felwood quest progression.

**Comment by PanJanuszek** [comment]
fixed 10.01.2024
