### ISSUE TITLE
Tier 11 Hc Requirements - Shoulders and Head pieces

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#2923]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The 372 heroic Shoulders and Head tier set pieces for each class require the normal version of the gear piece + the heroic token, following the scheme found for Chest, Legs and Hands. this is actually not how it is supposed to work since 4.0.6 patch as it would require people to run the normal versions of the raid and then the heroic version in two separate weeks, not to mention the confusion with the names.

**How to reproduce:** Visiting the valor quartermasters, we can see they require the normal piece + hc token as one would initially think it is right.

**How it should work:** The Shoulders and Head gear pieces (and only them) should only require the token for their purchases. (normal token for 359 piece, hc token for 372 piece) / the remaining pieces continue to work as intended 

**Database links:**

https://worldofwarcraft.blizzard.com/en-us/news/2166872/patch-406-official-notes
![chrome_IOX1Rtc2SN](https://user-images.githubusercontent.com/130247490/230739072-5febcd01-35a3-4dbf-9f0b-22fa3e9f18d0.png)
![WoW_6fWjlxEdJQ](https://user-images.githubusercontent.com/130247490/230739152-96863791-6053-46b5-a151-ddf4e8ffab64.png)
![WoW_4iQ0qujOnJ](https://user-images.githubusercontent.com/130247490/230739184-27d5d759-e7cd-4903-93d5-e494550880eb.png)

**Comment by UltraNix** [comment]
Fixed.
