### ISSUE TITLE
"Primal Madness" feral talent does not affect energy pool as it should

### ISSUE THREAD

**Issue by Largemac** [gamefreedomgit/Maelstrom#2925]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Primal madness is supposed to increase energy pool by 20 during Berserk and Tiger's Fury durations. Currently only affects Tiger's Fury.

Cast Berserk as feral with Primal Madness talent

Increase energy by 20

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
