### ISSUE TITLE
Warlord Halthar is Back Quest! Too many dwarfs around the NPC

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#2926]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

There are too many dwarfs around Warlord Halthar and i dont know how do they spawn so many of them...

The only way to do the quest is to write a ticket and a GM to kill the dwarfs... otherwise you don't get the credit when you kill Halthar.

Edit: 

The area itself is bugged, it needs fixing...

**How to reproduce:**

**How it should work:**

**Database links:**

https://wowpedia.fandom.com/wiki/Warlord_Halthar

https://wowpedia.fandom.com/wiki/Warlord_Halthar_is_Back

**Comment by UltraNix** [comment]
Fixed.
