### ISSUE TITLE
[Quest] Twilight of the Dawn Runner - No Credit When Saving Ithania

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#2929]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to complete [Twilight of the Dawn Runner](https://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner)

**How to reproduce:**
Speak to Ithania to "rescue" her. Credit will not be given.

**How it should work:**
Credit should be given after you rescue Ithania

**Database links:**
https://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner

**Comment by Afgann** [comment]
fixed
