### ISSUE TITLE
To New Thalanaar Hippogryph takes you to Ruins of Feathermoon

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2932]
**Description:**
When you do the dialog option for the quest at the flight master, Seyala Nightwisp, it no clips you to Ruins of Feathermoon instead of New Thalanaar like it should. This is on the complete other side of the zone.

**How to reproduce:**
Accept the quest To New Thalanaar and use the dialog option for Seyala Nightwisp.

**How it should work:**
The Hippogryph ride should take you To New Thalanaar as the quest name suggests. Especially since it is the objective of the quest to do so.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=25481
https://cata-twinhead.twinstar.cz/?npc=40367

**Comment by Afgann** [comment]
fixed
