### ISSUE TITLE
26755 - Keep them of the front

### ISSUE THREAD

**Issue by Operaksecond** [gamefreedomgit/Maelstrom#2933]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After i enter Earthen Catapult and do damage to Fungal Terror, Stone Togg Reinforcement it creates threat. But insted of attactick Catapult or dont reacts on damage. They attacks player and almost instakilling them.  So it  makes quest longer then it should be and anoying.

**How to reproduce:**
Remove threat generation by damage. 

**How it should work:**
https://www.youtube.com/watch?v=AvN-Eymb7z8&embeds_euri=https%3A%2F%2Fwww.wowhead.com%2F&embeds_origin=https%3A%2F%2Fwww.wowhead.com&source_ve_path=MjM4NTE&feature=emb_title&ab_channel=GameGuidesChannel

**Database links:**
https://www.wowhead.com/quest=26755/keep-them-off-the-front

**Comment by UltraNix** [comment]
Fixed.
