### ISSUE TITLE
Deadmines bombs triggering 3 times each

### ISSUE THREAD

**Issue by msh2038** [gamefreedomgit/Maelstrom#2935]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Deadmines bombs triggering 3 times to 1 shot
**How it should work:**
![image](https://user-images.githubusercontent.com/104918750/230764454-223176e8-c130-4db2-9914-38b33f7f110b.png)
**Database links:**
![image](https://user-images.githubusercontent.com/104918750/230764441-8d05db37-5788-44fd-9729-71dbef36ae40.png)

**Comment by msh2038** [comment]
![image](https://user-images.githubusercontent.com/104918750/230764513-cf925eca-19f6-4dba-bb42-ebab32296b0f.png)

**Comment by msh2038** [comment]
![image](https://user-images.githubusercontent.com/104918750/232252856-74749ffa-8154-464f-96a9-cedfd7b34064.png)
chest bomb too it seems

**Comment by staR1336** [comment]
closing as reported issues in #3245
