### ISSUE TITLE
Worn Junkbox can have nothing inside it

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2936]
**Description:**
This problem seems to be common on private servers, openable items and even some times chests in world can have a chance to obtain nothing. This is obviously not intended and as I suspected it is affecting multiple boxes.

**How to reproduce:**
Unlock Worn Junkbox and open them. Eventually one will have nothing in it after just a few.

**How it should work:**
When you open any container type item it should pick from a pool of items to give you, so that you get something 100% of the time.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=16883#contains (As you can see it can drop quite a few things, and it might be using the literal % drop on them instead of pick one with higher % items being picked that much more often ect.)

**Comment by EdyGlockenspiel** [comment]
Just going to add the ones I find to this post instead of making a whole new one every time. Sturdy Junkbox also suffers this fate.
https://cata-twinhead.twinstar.cz/?item=16884#contains

**Comment by EdyGlockenspiel** [comment]
Heavy Junk as well, though I am pretty sure these are supposed to also have some silver inside them every time as it's guaranteed 'item' and then a rare chance at the list from the link below here.
https://cata-twinhead.twinstar.cz/?item=16885#contains

**Comment by EdyGlockenspiel** [comment]
Scum Covered Bag, just like the Heavy Junkbox as well, I think it is always supposed to contain some silver and sometimes an item from the list.
https://cata-twinhead.twinstar.cz/?item=20767#contains

**Comment by EdyGlockenspiel** [comment]
https://cata-twinhead.twinstar.cz/?item=21113#contains Watertight Trunk as well.

**Comment by Afgann** [comment]
fixed
