### ISSUE TITLE
Deadines Heroic is bugged to hell and back

### ISSUE THREAD

**Issue by bl2x14** [gamefreedomgit/Maelstrom#2938]
Deadmines HC:

Helix Gearbreaker encounter: mobs running through closed door during encounter from next room, players blowing up to invisible bombs then dying to fall damage. (Might not be Deadmines related only: party randomly gets converted to raid group, throwing 2 people out mid-fight, then can't re-queue or new players can't teleport to dungeon using the dungeon finder 'eye'.)

**Comment by staR1336** [comment]
Closing as reported Helix issues in #3245
