### ISSUE TITLE
Is this bug!

### ISSUE THREAD

**Issue by Wikilixx** [gamefreedomgit/Maelstrom#2940]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My frost dk with 8 cap hit still miss with norml attack is this norml or not plz 🙏

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any snaps or clip of that issue ? Because if  you are dual wielding you won't always hit with offhand with 8%hit
