### ISSUE TITLE
Judgements of the pure

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#2941]
**Description:**
Using judgment on a target which absorbs its damage(example: judgement on priest shield) does not give you judgements of the pure talent proc, which impacts holy spec a lot, because it increases your mana regen in combat & haste, it is also major impact on other specs.

**How to reproduce:**
Judgement on a shield/absorb

**How it should work:**
It should give you judgements of the pure absorbed by shield or not.
https://youtu.be/z_MTaN8AkAs?t=29
00:29 he judgments on top of the shield and gains the buffs

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
