### ISSUE TITLE
Achievement Glutton for Shadowy Punishment is bugged

### ISSUE THREAD

**Issue by cybroook** [gamefreedomgit/Maelstrom#2942]
The Achievement Glutton for Shadowy Punishment is not working. I dont get any credit when doing it. When you acually get the 20 stacks then you still dont get the acheivement

**Database links:**
https://www.wowhead.com/achievement=5547/glutton-for-shadowy-punishment#comments

**Comment by emirie1** [comment]
Just encountered this same issue with both this achievement and the achievement for "Fiery Punishment" as well. However I was able to get the achievement for "Icy Punishment" just fine. I turned on tracking for both achievements and the counters on each never increased while tracking. The only difference between Fiery/Shadowy and Icy is that the counter for Icy was a buff and the counters for Fiery/Shadowy are debuffs. Perhaps the difference is what is not allowing it to be tracked and counted.

**Comment by UltraNix** [comment]
Fixed.
