### ISSUE TITLE
Solo Queue: When someone doesn't enter arena it count as a loss instead of draw

### ISSUE THREAD

**Issue by aymenqtx** [gamefreedomgit/Maelstrom#2944]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Title

**How to reproduce:**
Enter any solo q arena, even if the match haven't started if u are 2 people in your team and your opponents 3, the arena match is finished instantly and count as a loss instead of draw 

**How it should work:**
make it as a draw 

**Database links:**
n/a

**Comment by UltraNix** [comment]
Fixed.
