### ISSUE TITLE
82327 - Holy Radiance Range

### ISSUE THREAD

**Issue by Operaksecond** [gamefreedomgit/Maelstrom#2946]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Spell Holy Radiance have more than 10 yard range for healing. I think its like 11-12.
https://www.youtube.com/watch?v=tzSDcGAQLNE
**How to reproduce:**
Reduce range

**How it should work:**
 In skill description is it heals 10 yards + 2.8sec *amount* after it. But it heals like 11-12 yards,

**Database links:**
http://cata-shoot.tauri.hu/?spell=82327

**Comment by UltraNix** [comment]
10y + combat reach. The center of the spell is the destination center, so it must include its combat reach.
