### ISSUE TITLE
[Warlock] Health of demons

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2947]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My friend has 87k health as a destro warlock, he has:
- 93k hp succubuss
- 101k hp felhunter
- 95k hp imp

I have 115k health as a demonology warlock, I have: 
- 157k hp felguard
- 115k hp succubuss
- 123k hp felhunter
- 117k hp imp

these values are way too high, as seen in some videos from retail:
- https://www.youtube.com/watch?v=eBEc9TbmXz8 - warlock 134k hp, imp 92k hp
- https://www.youtube.com/watch?v=uRl55meQxIs - warlock 109k hp, felguard 82k hp

To be determined if only warlock demons need fixing, or if hunter pets have too much health as well

**How to reproduce:**
self explanatory

**How it should work:**
HP of demons should be much lower. Currently they are hardly killable at all.

**Database links:**

**Comment by Drevil-Dion** [comment]
It affects all pets not to mention the damage they do from melee hits is also bugged

**Comment by Pornoodemon** [comment]
> It affects all pets not to mention the damage they do from melee hits is also bugged


You do not take into account that mastery in the demonology branch increases the damage of petomcenes by an average of 50% and more%

https://www.youtube.com/watch?v=rivxK2hLHZY

7:05
For one Felstorm of Felguard, removes 60% of the rogue's HP.
And that's just pure damage without burst and trinkets.

**Comment by UltraNix** [comment]
Fixed.
