### ISSUE TITLE
Dueling resets proffesion cooldowns

### ISSUE THREAD

**Issue by Palaedra** [gamefreedomgit/Maelstrom#2948]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you duel a player it resets the cd of truegold, inscription research. stb..

**How to reproduce:**
Use cd, request duel and accept

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
