### ISSUE TITLE
Death Knights are supposed to start with 20 silver

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2951]
**Description:**
Since 3.0, all DKs started with 20 silver in their bags when created, currently you don't.

**How to reproduce:**
Create a fresh DK.

**How it should work:**
You should have a starting amount of 20 silver in your bags when you first make a dk.

**Database links:**
https://wowpedia.fandom.com/wiki/Starting_a_death_knight

**Comment by UltraNix** [comment]
Fixed.
