### ISSUE TITLE
Two By Sea

### ISSUE THREAD

**Issue by tobythevanq** [gamefreedomgit/Maelstrom#2960]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

the gilneas quest two by sea is bugged the engineers for the cannons arent spawning and you cant interact with canons to get on the boats cant progress pass this quest

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
reopening this Ultranix, it got better but players are still need to relog its like they invisible to the npcs

**Comment by UltraNix** [comment]
Invisible - like when?

**Comment by MrTide** [comment]
they are trying to hit the forsaken machinist and they keep healing so they can't kill them to use forsaken catapult, even we as gms with gm on can't see them until they relog
so as result forsaken machinist keep healing, it also causes issues on a few quests after that

**Comment by UltraNix** [comment]
Just tested on live server and got no problems with invisibility/neverending evading. Need more info how to reproduce it.

**Comment by UltraNix** [comment]
No further info - closing.
