### ISSUE TITLE
Cambio de forma a huesos

### ISSUE THREAD

**Issue by Yodoxq** [gamefreedomgit/Maelstrom#2961]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Me he transformado en huesos y carne, no puedo volver a mi forma original por lo que no puedo usar monturas de ningun tipo
![image](https://user-images.githubusercontent.com/38476626/231027217-6ae37bc5-5254-40eb-8fc8-1863c3af57f4.png)

**How to reproduce:**
Estaba en una mazmorra cuando uno esqueleto exploto contra mi y me transforme en esto

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment]
Can you translate this to English?

**Comment by Yodoxq** [comment]
I have transformed into bones and meat, I cannot return to my original form so I cannot use mounts of any kind

My character's name is Senestans and I'm a human witch

**Comment by Alandiel** [comment]
What transformed you into bones?

**Comment by UltraNix** [comment]
No further info - closing.
