### ISSUE TITLE
[Warlock][Spell] Health funnel

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2963]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Health funnel is not always healing the third time. I have a glyph for health funnel, so 3 ticks should be guaranteed unless I cancel early. Seems like 50/50 for the last tick currently. When it doesn't heal, it also doesn't damage me.

**How to reproduce:**
Health funnel a demon

**How it should work:**
Heal all 3 ticks if no damage is taken

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=755

**Comment by UltraNix** [comment]
Tested with 50% haste - still tick 3 times.
If you are being hit, then it's normal to lose ticks.
