### ISSUE TITLE
[Profession] Tailoring - northern cloth scavenging vs AOE loot

### ISSUE THREAD

**Issue by melezdev** [gamefreedomgit/Maelstrom#2964]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Extra cloth from Northern cloth scavenging are not correctly looted by AOE loot. I often have to pick them up from extra mobs individually, but worse yet sometimes cloth can't be looted at all - "Already looted".
It seems like it's looted by AOE loot, but makes it very hard to loot a group of mobs.

**How to reproduce:**
Kill ~10 humanoids in a pack as a tailor, try looting them.

**How it should work:**
I guess extra cloth should be looted the same way as normal items

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=59390

**Comment by UltraNix** [comment]
Fixed.
