### ISSUE TITLE
Flying mounts in no fly zones seem to not work properly as ground mounts

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2965]
**Description:**
In cata, when you are in a zone with no flying, you can still use your flying mount as a ground mount. This allows you to basically fully replace your ground mounts on the keybind you use for them. Currently, this is not working. After I entered Azuremyst Isle via the boat, I noticed I was able to fly and nearly shit my pants. After I exited the sub zone of the veiled sea and got to land I instantly fell from the sky. However, my ground speed was capped at 120% instead of the 240% it should have been. I tried dismounting and remounting, even relogging and it was still 120% while my horse was going at the full 240%. This is obviously not intended, either the mount needs to be fully restricted/unusable in no fly zones, or it's run speed should match a standard ground mount's speed.

**How to reproduce:**
Go to Azuremyst Isle and mount a flying mount.

**How it should work:**
In cata, flying mounts should work as standard ground mounts in no fly zones.

**Database links:**
I have no links for this and don't feel like scouring google for a wowhead post talking about the patch from over a decade ago, stating that you can use flying mounts as ground mounts. If you ask anyone that played from cata and beyond they will tell you this is how it worked, though.

**Comment by EdyGlockenspiel** [comment]
So after doing OS 10 yesterday, the players in my group that had epic flying mounts seemed to have normal ground mount speed when running around on their gryphon/wyvren. But players like me who only have the blue flying mount had to switch to stuff like horses to run around. This tells me this bug *only* affects a select few mounts, namely the non epic vendor flying mounts such as Golden Gryphon for alliance (the one I use)

**Comment by varjla** [comment]
For add some information: In silvermoon, flying mounts give you a 8% speed increase: from 100% to 108%. All the [Wind Riders](https://www.wowhead.com/wotlk/spell=32244/blue-wind-rider) normal or faster are afected.

![WoWScrnShot_061423_190958](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/69531698-95e6-493c-b829-4fc80a2d0bd3)

**Comment by UltraNix** [comment]
Fixed.
