### ISSUE TITLE
bug mechanics to summon npc in terokkar forest

### ISSUE THREAD

**Issue by imperobator** [gamefreedomgit/Maelstrom#2966]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after complete the chain quest mission of tokens of the descendant  you cannot summon npc in the skull pile even having the time-lost scroll enough
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment]
Did you complete https://www.wowhead.com/quest=11021/ishaals-almanac this questline?

**Comment by Alandiel** [comment]
Works fine, just need to finish required quests.
