### ISSUE TITLE
Archeology in Un'goro Crater

### ISSUE THREAD

**Issue by zychshoo** [gamefreedomgit/Maelstrom#2967]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The issue is about un'goro crater archeology survey. Survey works only in the archeology area, yet this time while standing at the very odge of area survey tells me to look further away from "circle" shown on map and even tho i am at the very edge of area survey shows me that its stil lfar aways since red dot is on the archeology thingy. SS of my issue: https://gyazo.com/f98535fb24d28c866d9a10ed907091db
I was trying to survey all around the place but it still tells me to go outside of archeology circle. 

**How to reproduce:**
Can't tell since i was doing archeology there for days now and it  never got bugged like that. First survey went smoothly as usual 2nd one was bugged outside of archeology area.

**How it should work:**
Well i guess it should be in archeology area (sorry for being sarcastic ;p)

**Database links:**

**Comment by zychshoo** [comment]
Seem like some new stuff is happening right now in ungoro, pretty much surveys show red distance pointing at each other from range of ~10y : https://gyazo.com/1d3a46dc84170979ed54b3d713bf7543 and to be more specific its this area https://gyazo.com/5942936c5407c8b3a2df0ddf13a07e60

**Comment by UltraNix** [comment]
#3690
