### ISSUE TITLE
[Quest] Twilight Highlands - Cementing Our Victory (QID = 26788)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2970]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=26788/cementing-our-victory)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=26788)

**Description: Turn-in NPC not available**

**How to reproduce: **
Pick-up the quest, gather 10 pieces of Verrall River Muck from the River, then go back to the NPC. The NPC won't be there if you went back to orgrimmar to speak to Garrosh Hellscream through the portal and completed the quest that turns the encampment into a Horde city  (The Warchief Will be Pleased). 
Result: The Question Mark will still be on the map but the NPC won't be spawned, targetable or interactable.
![image](https://user-images.githubusercontent.com/29439770/231223258-828ba50d-0d3a-4945-9e66-15e58ffe382c.png)

**How it should work: **
NPC should either still be available after quest completion or you shouldn't be able to go back to Garrosh Hellscream before completing this quest.

**Database links:**
In WowHead the quest is marked as a prerequisite for "The Warchief Will be Pleased" (see above).

**Comment by UltraNix** [comment]
Fixed.

**Comment by meggynka** [comment]
It is not fixed... I dont see the NPC ...
