### ISSUE TITLE
[Quest] Twilight Highlands - Narkrall, the Drake Tamer (QID = 27690)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2971]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[[[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27690/narkrall-the-drake-tamer)]
[[//]: #[(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27690)]

**Description: Turn in NPC missing**

**How to reproduce:**
Just follow the quest normally. Narkrall Rakeclaw won't be standing besides his red dragon. The Question Mark still appears on the map but the NPC is not spawned, visible, targetable or interactable in anyway
![image](https://user-images.githubusercontent.com/29439770/231223830-f68bee69-467f-4b91-8fd3-deae8ebcab14.png)

**How it should work: You should be able to click on the NPC**

**Database links:**
See above.

**Comment by UltraNix** [comment]
![Uploading image.png…]()
Works okay to me.
