### ISSUE TITLE
[Quest] Twilight Highlands - Something Stolen (QID = 28410)

### ISSUE THREAD

**Issue by Nhae15** [gamefreedomgit/Maelstrom#2972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Everyone's going to want to dress their best for this, and finery is in short supply in the Highlands.

I understand that those goblin wretches off the coast use the finest silk for repairing their zeppelin air envelopes. A waste!

Find a zeppelin flying back and forth between Dragonmaw Port and the Krazzworks, and liberate some silk from the cargo hold in the lower decks.

**How to reproduce:**

**How it should work:**
There is not the silk in the cargo hold

**Database links:**
[https://cata-twinhead.twinstar.cz/?quest=28410](url)

**Comment by rey384** [comment]
There are two cargos and u can loot the silk without any problem. Did it actually.
![image](https://user-images.githubusercontent.com/39013777/231779946-e08a6356-ffb1-4441-8ad4-18c429958970.png)

**Comment by Sketish** [comment]
Fixed
