### ISSUE TITLE
[Quest] Uldum -  The Thrill of Discovery (QID = 27511)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2973]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27511/the-thrill-of-discovery)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27511)

**Description: Interactables not working**

**How to reproduce:**
Simply take the quest and you will notice that:

1- The Hieroglyphs are not working, they should sparkle and when you walk close to them you should get completion
2- The Machine doesn't show up as completed regardless of how close you are to it

**How it should work:**

By walking in proximity of the Hieroglyphs and the Ancient Machine you should get completion for examination.

**Database links:**

**Comment by BurntTongue** [comment]
Tried randomly today: it worked.

If you confirm that the behaviour has been fixed and this is not random, i'll close the issue right away.

Thanks!

**Comment by MrTide** [comment]
works fine seems like

**Comment by mserkanoz** [comment]
Additional info: An Alliance player was there, he completed it, but as a Horde player I can't complete because the sparkling quest-credit-givers won't show up to me.
