### ISSUE TITLE
[Dungeon] Uldum - Walk In - Lost City of the Tol'Vir

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2974]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: Walk-In portal does not allow to port out of dungeon**

**How to reproduce: Walk in by foot into the dungeon, then try to use the same portal to get out. It won't let you**

**How it should work: It should teleport you out**

**Database links:**

**Comment by MrTide** [comment]
looks like once you go inside you can't go out

**Comment by UltraNix** [comment]
No further info - closing.
