### ISSUE TITLE
[Quest] Uldum - The Pit of Scales (QID = 27738)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2975]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27738/the-pit-of-scales)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27738)

**Description: NPCs do not move at all, you take 4333 DpS while in water regardless of crocodiles spawning/visible**

**How to reproduce: Simply take the quest and go to the designated place. You will notice two things happening:

1- All NPCs (The three crocodile mini-bosses and the Taskmaster) stand completely still and won't do anything, not even attack back. This means that you won't generate rage as a warrior, they will stand in the middle and due to the second part of the bug, you will take 4333 damage each second while standing in the water.

You also aren't able to break the eggs in the second phase, this makes killing the Taskmaster a slog since it has 650k HP.
The eggs are breakable though, if you step on them you will spawn invisible crocodiles that will deal 4333 damage each second to you**

**How it should work: Enemies should move and attack, they should be able to break eggs.**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
