### ISSUE TITLE
Scarlet Monastery friendly mobs

### ISSUE THREAD

**Issue by Zalazame** [gamefreedomgit/Maelstrom#2978]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Scarlet Myrmidon, Defender and Soldier in the cathedral/armory (scarlet monastery) are friendly with all players

**How to reproduce:**
If the programming is the same as on WOTLK, the problem could come from the SQL table "creature template" -> faction 
the actual value for faction is maybe 35 (friendly with all) and the good value must be 14 (ennemy with all)

**How it should work:**
These entities must be aggressive towards the players (Myrmidon and defender are the only mob who loot the scarlet belt from the scarlet set. This set can not be completed actually due to this bug)

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=4295
https://cata-twinhead.twinstar.cz/?npc=4298
https://cata-twinhead.twinstar.cz/?npc=4286

**Comment by PanJanuszek** [comment]
Cannot reproduce

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/bbb05599-e1e8-4fda-834b-7c858e3b7b67)
