### ISSUE TITLE
DK Rime proc dont generate runic power

### ISSUE THREAD

**Issue by Endofree1247** [gamefreedomgit/Maelstrom#2979]
**Description:**
https://cata-twinhead.twinstar.cz/?spell=49184 Howling blast with Rime proc https://cata-twinhead.twinstar.cz/?spell=59057 dont generate rune power, so with 2-2.5 k haste you have huge pauses in rotation (3-4 secs till runes will recover)

**How to reproduce:**
Spam obliterate till rime procs and see that using howling blast with proc will not generate runic power

**How it should work:**
Rime procced howling blast should generate runic power as usual blast

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=49184
https://cata-twinhead.twinstar.cz/?spell=59057

**Comment by Endofree1247** [comment]
if you think if its works fine when it doesn't generate anything so sending you video from official 4.3.4 guide and timeline there can show you that its generate 10rp on using https://youtu.be/FlySOYaKvDs?t=116

**Comment by Sketish** [comment]
https://www.youtube.com/watch?v=FlySOYaKvDs&t=136s&ab_channel=mbXtreme
https://www.youtube.com/watch?v=Xlquf2zoTpk&t=35s&ab_channel=Jevagen
So why on those 2 he didnt get any RP when using howling with rime ?

**Comment by HelljudgeWhitemane** [comment]
Sketich u are wrong, at 0,25 speed right before he zoomed in you can clearly see at 0:16 https://www.youtube.com/watch?v=Xlquf2zoTpk&t=35s&ab_channel=Jevagen
he gained Runic Power from 52% to 60% without wasting any runes, after using howling blast with rime
Here comment from Rime spell on wowhead "It's worth noting a Howling Blast cast using this buff will provide no runic power, except 5 if you have the Chill of the Grave Talent" that means with 2/2 Chill of the Grave u must gain 10 runic power with Howling Blast that used after Rime

**Comment by Sandmanxqx** [comment]
this bug is so frustrating played in ton's of cata server and it worked all fine here is still bugged, hope they fix it !!

**Comment by Mietla122** [comment]
enforfe watch cloesly 2:05 with 0.x25 u can cleary see that howling didn't generate runic power

**Comment by UltraNix** [comment]
Fixed.
