### ISSUE TITLE
[Priest][Spell] Mind Flay/Mind Sear targetting issues.

### ISSUE THREAD

**Issue by dan-personal** [gamefreedomgit/Maelstrom#2980]
**Description:**
If you are already channelling mind flay on target1, and switch to target2 and cast mind flay, it will recast mind flay on target1. There are all sorts of visual issues going on with MF/MS too, like the beam firing at target2 but damaging target1, and the mind sear aoe affect is visible around target1 etc. 

**How to reproduce:**
1. Cast mind flay on target1
2. Cast mind flay on target2 mid-channel
3. Observe that the mind flay is cast on target1

**How it should work:**
Mind flay should be cast on target2

Some footage from original 4.0.6:
https://youtu.be/hk4xV7yeJhY?t=82

You can see at about 1:23 he recasts mind flay on Theralion then immediately switches target to Valiona. Shortly after you see him recast mind flay and it correctly targets Valiona.

**Comment by dan-personal** [comment]
It seems the issue is only visual, my mistake. The target is selected correctly but the animation targets the wrong target.

**Comment by DeadRatsYT** [comment]
visual but it rotates you to target. so would be nice if it get fixed.

**Comment by UltraNix** [comment]
Fixed.
