### ISSUE TITLE
[Priest][Spell] Glyph of Shadow Word: Death not behaving correctly when switching targets.

### ISSUE THREAD

**Issue by dan-personal** [gamefreedomgit/Maelstrom#2981]
**Description:**
SW:D doesn't go on cooldown as it should after 2 casts, when each cast is on a different target.

**How to reproduce:**
1. Be in combat with 2 mobs that are below 25% health, and will not die from a single SW:D cast
2. Cast SW:D on mob1
3. Cast SW:D on mob2
4. Observe that SW:D is still usable and not on cooldown
5. Cast SW:D on mob1 (or mob2) again and SW:D will go on cooldown.

Note: You can do this with as many mobs as you like. I have managed to replicate this with 4 sequential SW:D casts on 4 mobs.

**How it should work:**
SW:D should go on cooldown after 2 consecutive casts. 

Note: I can't find any source material that shows how this glyph should work, but the glyph text to me would indicate that it can only reset the cooldown on SW:D once every 6 seconds, not once per mob every 6 seconds. However, that is tenuous but valid interpretation of the glyphs text so if devs are happy with this behaviour then I am too.

**Comment by UltraNix** [comment]
Fixed.
