### ISSUE TITLE
Succubus doesnt enter combat while on follow/passive

### ISSUE THREAD

**Issue by Lyeex** [gamefreedomgit/Maelstrom#2982]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Succubus pet does not enter combat when being attacked while set to follow/passive. This might affect all pets.

**How to reproduce:**
Summon Succubus.
Set pet to follow and passive.
Let other player attack it.
Spam "Lesser Invisibility".

The issue is not the spell itself. When sending the Succubus to attack a target, it enters combat and you cannot cast Lesser Invisibility.

**How it should work:**
Succubus should enter combat when being attacked and be unable to spam Lesser Invisibility.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=7870

**Comment by UltraNix** [comment]
Fixed.
