### ISSUE TITLE
[NPC] Twilight Highlands - Thundermar War Gryphon dealing 1 damage

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2983]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: NPC does 1 damage**

**How to reproduce: Aggro a Thundermar War Gryphon , it will attack for 1 damage each attack**

![image](https://user-images.githubusercontent.com/29439770/231516821-f8ade054-d4ec-43a5-a4bc-11406c237245.png)

**How it should work: they should do normal damage (1k on a tank plate character)**

**Database links:**

**Comment by Afgann** [comment]
fixed
