### ISSUE TITLE
[Achievement] Kill it with fire!

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#2984]
**Description:**
The achievement want you to kill 3 Burning souls during the encounter with High Prophet Barim

**How to reproduce:**
Reach second boss phase by reaching 50% health, souls should spawn from players, kite the souls into the flames on the ground, kill the souls.

**How it should work:**
one killed three souls you should gain the achievement

**Database links:**
https://www.youtube.com/watch?v=oIsYURRfHy4
https://www.wowhead.com/achievement=5290/kill-it-with-fire#

**Comment by UltraNix** [comment]
Tested - works okay.
![obraz_2023-11-06_214637867](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/c5758a17-4ee2-433c-b4fe-6f23c8b4c569)
