### ISSUE TITLE
[Achievement] Headed South

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#2985]
**Description:**
During the encounter with Siamat in Lost city of tol'vir you have to take 3 debuff stack once the minions die and the kill the boss

**How to reproduce:**
kill Servants of siamat mobs and stay near them to take debuff, once died the mobs gives you a debuff that should (but it doesn't) stack, max stacks are 3 because the total adds spawned should be 3

**How it should work:**
The debuff should stack and once you kill the boss if should give you the achievement

**Database links:**
https://www.youtube.com/watch?v=d-Ymd3WvEIY
https://www.wowhead.com/achievement=5292/headed-south#

**Comment by UltraNix** [comment]
Just tested - works okay.
![obraz_2023-11-06_214925590](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/0ab4f3be-2469-4448-8c63-053b4069fd72)
