### ISSUE TITLE
[Quest] [NPC] Twilight Highlands - Patchwork Command (QID = 27576) - Patch not showing up

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2986]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27576/patchwork-command)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27576)

**Description: The target NPC "Patch" for the quest is not visible**

**How to reproduce:"**
Simply take the quest from the "Vermillion Redoubt" and go to the designated spot. There should be a dozen NPCs between goblins and orcs. One of them should be "Patch" that you have to talk to in order to complete the quest. The NPC is not visible while the question mark is accurately there.

**How it should work:**
The NPCS should be there, visible and interactable.
![image](https://user-images.githubusercontent.com/29439770/231551406-975be44d-22b4-48ef-8e7b-ad65eddb459d.png)

See this youtube video for reference: https://www.youtube.com/watch?v=1WT8Nd0YB4A

**Database links:**

**Comment by MrTide** [comment]
duplicate
