### ISSUE TITLE
[QUEST] [NPC]  [He's Holding Out on Us]

### ISSUE THREAD

**Issue by int24rain** [gamefreedomgit/Maelstrom#2987]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

** [He's Holding Out on Us]:**

**How to reproduce:**

**Bringing Anduin to Samuel's Wardrobe in SI:7 stairs must start conversation from Anduin and complete the quest by examining the Samuel's papers.:**

**Database links:**

**Comment by MrTide** [comment]
this sometimes works and sometimes doesnt very inconsistent

**Comment by UltraNix** [comment]
Just tested (multiple times) and worked okay.

**Comment by UltraNix** [comment]
Just tested (multipled times) and worked okay.

**Comment by UltraNix** [comment]
Fixed.
