### ISSUE TITLE
[QUEST] [NPC]  [Unholy Cow]

### ISSUE THREAD

**Issue by int24rain** [gamefreedomgit/Maelstrom#2988]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Must bring Anduin to the crime scene but nothing happens when we get to the fog/smoke place:**

**Read above:**

**Should be able to complete the quest by walking to the smoke (following the trail of meat)**

**[Database links:](https://www.wowhead.com/quest=27060/unholy-cow)**

**Comment by MrTide** [comment]
i can confirm, some players can do it but most can't also they take massive damage while passing through the meat looking objects which also makes it impossible to do

**Comment by UltraNix** [comment]
#3195
