### ISSUE TITLE
[Quest] Twilight Highlands - Far from the Nest (QID = 27508) - Eggs not spawning/not interactable

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#2989]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27508/far-from-the-nest)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27508)

**Description: Vermillion Eggs are not spawning or not interactable**

**How to reproduce: Simply take the quest and follow the instructions. As seen in wowhead, you should kill Abductors to make them drop the eggs. The egg drops only work when close to the nearby cave (the one needed for the "Breach the Defenses" quest) and most of them are not interactable. Luckily, you can click the same egg more than once (probably another bug) with a several second cooldown (spam-clicking doesn't work). This helps mitigate the issue: once you get a working egg to drop, you can use the same egg all the times that you need, provided enough time.**

**How it should work: Eggs should be dropped regularly and be interactable. Re-using the same egg should not be possible.**

**Database links:**

**Comment by Sketish** [comment]
Fixed
