### ISSUE TITLE
Death Strike is not healing at all

### ISSUE THREAD

**Issue by madihaz** [gamefreedomgit/Maelstrom#2990]
**Description:**
Sometimes during combat Death Strike stops healing at all when tanking as Blood DK with standard talent spec (Improved Death Strike). Blood Shield is still applied.
It happened for example on Magmaw HC. Helix Gearbreaker (Deadmines HC) and on every single pull on Atramedes HC.

![image](https://user-images.githubusercontent.com/36551230/231558471-6f46e6b6-cc87-4b31-aa77-cb2eaf4f0f86.png)

Combat log from Atramedes HC without any healing from Death Strike.
[WoWCombatLog.zip](https://github.com/gamefreedomgit/Maelstrom/files/11216338/WoWCombatLog.zip)

**How to reproduce:**
Pull Atramedes 10 HC. Death Strike is not healing from start of fight at all.

**How it should work:**
Death Strike should always heal. There should be combat log entries like below:
4/12 23:24:55.776  SPELL_HEAL,0x0000000000004D94,"Ihaz",0x511,0x0,0x0000000000004D94,"Ihaz",0x511,0x0,45470,"Death Strike",0x1,10113,0,0,nil

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=49998

**Comment by UltraNix** [comment]
Fixed.
