### ISSUE TITLE
Deep Freeze and Ring of Frost interaction

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#2991]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ring of frost and deep freeze should share DR even though they are different category, it was made to balance frost mage CC.
*I repeeat, its only this 2 spells which should do this, you dont need to touch the full categories.

**How to reproduce:**
Use deep freeze, use ring, both will be full duration.

**How it should work:**
https://youtu.be/djtKYp5NFKY?t=204
3:23 he uses ring of frost and deep on warrior, Deep freeze makes ring of frost give half duration.

**Database links:**

**Comment by Renehadox** [comment]
Confirmed.

**Comment by Stega23** [comment]
As far as i am aware, Cone of Cold is in random root category with hamstring etc...
Frost nova is controlled root, so no

**Comment by lalolalolz** [comment]
> On a side note, shouldn't cone of cold with the root talent and frost nova share dr with each other?
> 
> Since they are both root effects.

The cone of cold only shares dr with the talent of the frost magician who creates a nova when his bubble breaks.

**Comment by lalolalolz** [comment]
> **Description:** Ring of frost and deep freeze should share DR even though they are different category, it was made to balance frost mage CC. *I repeeat, its only this 2 spells which should do this, you dont need to touch the full categories.
> 
> **How to reproduce:** Use deep freeze, use ring, both will be full duration.
> 
> **How it should work:** https://youtu.be/djtKYp5NFKY?t=204 3:23 he uses ring of frost and deep on warrior, Deep freeze makes ring of frost give half duration.
> 
> **Database links:**

They should fix that the ring of frost does not break due to damage. I've seen warriors hit bladestorm or dot ticks and not break... 

It's frustrating to spend 8 seconds without being able to do anything, yes or yes, and if it's fire on top of that and it gives you ring+breath+silence... If you don't have a trinket, prepare your funeral

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2e66b051-5b8e-40fe-92dd-1d57a9f184cc)
Hit by Ring of Frost, then hit by Deep Freeze - DF is removed after 2.5 sec.
