### ISSUE TITLE
Typhoon (Balance) delay

### ISSUE THREAD

**Issue by rolandofgilead7** [gamefreedomgit/Maelstrom#2997]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Typhoon does not work as intended, delayed, sometimes misses entirely.

When using Typhoon, there is a significant delay and sometimes it does not work at all.

Typhoon should work instantly, so spells can be cancelled in PvP or enemies knocked off cliffs etc.

**Comment by UltraNix** [comment]
Cannot reproduce it.
Also, Typhoon is not an instant spell.

**Comment by rolandofgilead7** [comment]
You're a fucking moron. Typhoon does NOT work correctly. Why are you doing
this job if you are not willing to fix issues, and just getting issues off
your plate as quickly as possible. Absolute fucking dumb shit honestly,
fuck off.

**Comment by rolandofgilead7** [comment]
Also, saying typhoon is not an instant spell. Way to show you're
incompetence.

**Comment by UltraNix** [comment]
By saying instant I meant that spell is delayed. The farther you are from your target, the more spell is delayed.
Also, good day to you.
