### ISSUE TITLE
2 set PvP bonus stacking

### ISSUE THREAD

**Issue by rolandofgilead7** [gamefreedomgit/Maelstrom#2998]
PvP Set bonuses do not stack,

If I equip 2 pieces of balance gear, I get the +400 resilience. However, if I additionally use 2 different pieces of Resto gear, I do not get the +400 resilience for that set. Infact, it even reduces my resilience temporarily and removes both set bonuses.

It should work that both can be stacked, so I can use 2 piece of gear for 2 different specs, and get a bonus +800 resilience. This applies for priests, druids, etc.

**Comment by mipanka** [comment]
it shouldn't be like this, blizzard removed it after the first patches, you can find these changes in the patch notes

**Comment by rolandofgilead7** [comment]
> it shouldn't be like this, blizzard removed it after the first patches, you can find these changes in the patch notes

Change notes for which patch? We are on 4.0.6, and there's no changes that I can find relating to the set bonus.

**Comment by mipanka** [comment]
we patch on items 4.0.6 on abilities 4.3.4, or no? 
on patch 4.0.6, many abilities work completely differently, and some do not at all

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Patch_4.2.0
`
The 2-piece resilence bonus from Cataclysm PvP sets no longer stacks. If a player wears 2 pieces each from 2 different Cataclysm sets, the player will only receive the 400 resilience rating bonus once. This change does not apply to PvP sets from prior expansions.
`
It should be applied to s10 items.
