### ISSUE TITLE
Magma Totem in Stonetalon Mountains

### ISSUE THREAD

**Issue by meggynka** [gamefreedomgit/Maelstrom#3002]
**Description:**
?? lvl magma totem instantly and repeatedly killing me. 
Coordinates of the totem are 81.2, 82.1

**How it should work:**
Totem should have proper hp for area its located in

![Screenshot 2023-04-13 163141](https://user-images.githubusercontent.com/35611571/231793157-60f08a4d-7984-4b87-90e5-6d6275a0474d.png)
![Screenshot 2023-04-13 163135](https://user-images.githubusercontent.com/35611571/231793200-43350e46-309f-4dd4-a506-83c5725dd55b.png)

**Comment by Afgann** [comment]
fixed
