### ISSUE TITLE
[Raid] - Blackwing Descent

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3004]
Drakonid Drudge cleave should hit everyone in front of him, currently visual is not matching mob direction so it hits everyone but tank
Drakonid Slayer and  Drakeadon Mongrel should be patrolling between drakes. Currently they are stopping at drake before atramedes boss entrace.
Patroling trash packs in BWD are getting stuck after wiping on them. If you fall/jump down into the lava they will get stuck under the platform of Onyxia and bug the encounter.

Magmaw
Tank death should result in tank corpse spawning at these XYZ coords (also if Magmaw is killed while tank is being held by Mangle)
Throwing the dps that does chains into the lava sometimes.
![image](https://user-images.githubusercontent.com/122209088/231808218-d9e98ca5-265c-46d5-9b89-9dedf4ac9169.png)

Boss hitbox has issue because rogue ability Blade Flurry is not hitting both boss and add when add is near the boss. Also Exposed head of Magmaw haave hitbox isssue, melees arent able to do auto attack always on head + sometimes they cant even use ability.

Rogue ability Killing Spree is teleporting player to lava instead of keeping him on the platform.

Omnotron Defense System
Arcanotron
Boss is not using Power Converion at 50 energy.

https://www.wowhead.com/spell=79735/converted-power?dd=6 - If you try to multiple spellsteal this buff - it would stack -haste to your character infinitely. The effect is permanent until you relog your character. Even death doesnt save you.
Its a massive mage dps boost mechanic, which now just stops you from playing the game.

Toxitron
Poison bombs are all fixating one target during whole fights. Each bomb should pick random player except Toxitron target.
Poison bombs should be stunable

Chimaeron
Hunter's Mark is waking up boss, removing Sleeping buff.
Talking to the robot should not immediately start the encounter. Robot should wake boss after 7-8secs.

https://www.wowhead.com/spell=82848/massacre procs fire mage talent Cauterize, which it shouldnt, of course. Makes you respec always when you face this boss as a mage or you'll die every minute for no reason.

Atramedes

The enrage timer is tighter in Heroic Mode because Nefarian will destroy an additional Ancient Dwarven Shield every time you use one during the Ground Phase. This will basically leave you with 4 Ground Phases and 3 Air Phases to down the boss.
Currently he is destroying 2 shields in air phase, where should be 1.
https://youtu.be/q9FhBTT2gJU?t=106

Air Phase
First Roaring Flame Breath has too high speed at start(impossible to outrun). After reseting it with shield it has correct
Warrior's aren't able to leap on whole platform, priest leap is also not working during that fight.

Obnoxious fiend - player who has add on him should be able to hit him and interrupt. Currently you cant do any dmg when add is on player.
https://youtu.be/MhHtG6ZqDsA?t=328
Feral druid interrupt skullbash is not interrupting add cast

Maloriak
Abberation shouldnt be hard ccable, only slow should work on them
One of our players was streaming. Just found the footage.
https://kick.com/video/39a1a59f-4597-4f55-a21d-c870969d904b

At ~ 5:37:00, you can see the Maloriak fight, cast going through and adds not spawning. Also the push into last phase a minute later, release aberrations that did nothing.
If you push the boss to 25% the moment he's supposed to switch phase, he won't cast "Release All" so no adds will spawn, even if you don't release any aberrations during the boss.

Vile Swill
They are casting Dark Sludge too frequently  comapred to retail videos also Dark Sludge is damaging players before there is visual on ground
Guardians avoidance is not working for Dark Sludge, making fire elementals, infernals die nearly instantly
Nefarian

Animated Bone warriors
Pre nerf 6 adds should spawn, currently 5 are spawning.

The Chromatic Prototype on top of the pillars are not interuptable by skullbash (bear).
During the fight it was not possible to interrupt their spell as druid in bearform regardless of standing on the pillar (center/edge/jumping arround) or in the lava.
There was no warning/error message.

Shadowblaze Spark
Fire visual sometimes is not matching range making players take dmg when their character is not inside fire.

**Comment by triceratopsrider** [comment]
Also Onnotron defence system should be random. Random starting boss and random order of bosses being activated. Now it has strict cycle of Electron into toxitron into arcanotron into magmatron and repeat.
https://m.youtube.com/watch?v=Hss3cD8jHPs&pp=ygUXT21ub3Ryb24gRGVmZW5zZSBTeXN0ZW0%3D

**Comment by Sketish** [comment]
> Also Onnotron defence system should be random. Random starting boss and random order of bosses being activated. Now it has strict cycle of Electron into toxitron into arcanotron into magmatron and repeat. https://m.youtube.com/watch?v=Hss3cD8jHPs&pp=ygUXT21ub3Ryb24gRGVmZW5zZSBTeXN0ZW0%3D

Its not  true. 1 combination is for whole ID. Then it's changing on next ID.

**Comment by Godmatik** [comment]
After every wipe/reset - Omnitron should start with a new one. Maybe the order is the same each ID but the starting one should always change.

**Comment by Waroxx-QA** [comment]
**Maloriak** (CRITICAL)
The boss is going undermap ( it happened with us on 3 pulls ) - resetting doesn't fix it...
We cad to call a gm to fix the ID by resetting it and killing the previous bosses.

**Comment by UltraNix** [comment]
Fixed.
