### ISSUE TITLE
[Spring Fling] event achievement

### ISSUE THREAD

**Issue by Emjiri** [gamefreedomgit/Maelstrom#3005]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://www.wowhead.com/achievement=2497/spring-fling

**Description:**
The achivement requires to find Spring rabbit in 4 starting zone inns. The night elf and draenai zone works fine, but in goldshire and Kharanos dont have any rabbits in it. 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Mepox1** [comment]
The same problem with Horde. Razor Hill and Brill work just fine, but the Falconwing Square and Bloodhoof village don't work.

**Comment by UltraNix** [comment]
Tested all locations - all work okay. Just need to search up :)
![obraz_2023-11-06_220014945](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/6a64c315-4cd6-4ec2-aab8-80677aa09d08)
