### ISSUE TITLE
[Raid] - Bastion of Twilight 

### ISSUE THREAD

**Issue by Alandiel** [gamefreedomgit/Maelstrom#3007]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Trash patrols before Halfus are not linked, currently you can pull 3 out of 5 which shouldn't be possible.
Halfus drakes had no chained animation/Visual bug low prio
Halfus should have a cast bar when doing Furious Roar. Timing of consecutive roars is also wrong. You should be able to fit a global in between each roar.
Divine Shield doesn't protect you from Blackout, instead you take full dmg from Blackout.(https://www.icy-veins.com/wow/valiona-and-theralion-strategy-guide-normal-heroic)
Valiona rotates while casting Devouring Flames.
Valiona and Theralion should look transparent to players within Twilight Realm.(https://static.icy-veins.com/images/wow/valiona-theralion-twilight-realm-small.jpg)
Theralion's Dazzling Destruction and Valiona's Deep Breath should kill players within Twilight Realm.
You are able to stun/root Evolved Drakonaar.
You are able to receive both Burning Blood and Heart of Ice at the same time. You should only be able to have one active.

https://www.wowhead.com/spell=83710/furious-roar
https://www.wowhead.com/spell=82665/heart-of-ice?dd=3
https://www.wowhead.com/spell=82660/burning-blood?dd=3
https://www.wowhead.com/npc=49813/evolved-drakonaar
https://www.wowhead.com/spell=86788/blackout?dd=5&ddsize=10
https://www.wowhead.com/spell=86840/devouring-flames
https://www.twitch.tv/videos/1782722683

**Comment by Revly** [comment]
Valiona rotates while casting Devouring Flames.
[https://youtu.be/gWoYrWFrRrg](url)

**Comment by Waroxx-QA** [comment]
Valionna still rotating while doing Devouring Flames, the second time she lands.
