### ISSUE TITLE
BWD patrol trash pack getting stuck after wipe

### ISSUE THREAD

**Issue by Battledamn** [gamefreedomgit/Maelstrom#3009]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Patroling trash packs in BWD are getting stuck after wiping on them. If you fall/jump down into the lava they will get stuck under the platform of Onyxia and bug the encounter (Onyxia also gets stuck under platform)

**How to reproduce:**
Start killing the patrols (2 dogs 1 keeper type) and jump into nefarian's pit then die in lava. The adds will stay there and bug the encounter.

**How it should work:**
Trash pack should reset after each wipe to their original position.

**Database links:**
N/A as this is not documented on wowhead/other sites

**Comment by Sketish** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3004
