### ISSUE TITLE
DK bug howling explosion

### ISSUE THREAD

**Issue by heezymena** [gamefreedomgit/Maelstrom#3010]
https://www.wowhead.com/es/spell=237680/explosi%C3%B3n-aullante

**Description:**

This power has a bug, for each enemy you attack with it, it must generate, for example, 10 runic power, if you attack 2 enemies, it must give you 20 and if you attack 3, it must give you 30, but it doesn't work like that, this makes the DKS are at a disadvantage in all aspects, it would be very helpful if they fixed it

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by EdyGlockenspiel** [comment]
It has never worked like that, and if it works like that in DF I wouldn't know. It should generate the same runic power no mater how many enemies you hit with it in one cast.

**Comment by Sketish** [comment]
Please provide any proofs it should work like thise, otherwise will close issue

**Comment by EdyGlockenspiel** [comment]
As someone who mained 2 hand frost for 7 years of my life on retail servers, (end of wrath till 7.0 when it was removed from the game and the whole spec redesigned) I can personally state the fact that it never generated more RP based on number of targets hit, during that time frame. Unless I am forgetting some tier set bonus that is. In terms of base spec and talents however it never worked that way. I could personally explain the ins and outs of the spec in great detail and how it worked for each xpack between 3.3.5 and 6.2.4, what each ability did/didn't do ect. Howling blast generating more RP on AoE would not come up in that, once.

**Comment by Sketish** [comment]
Invalid report
