### ISSUE TITLE
353 Fist Wep Offhand agil.

### ISSUE THREAD

**Issue by BuddySpank** [gamefreedomgit/Maelstrom#3011]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
item # 64775 "Bloodthirsty Gladiator's Left Ripper" is not available for shamans to be purchasable from the honor vendors. the "Left Render" the offhand str wep is available to be purchased just not the agil one. On the conquest vendor you can purchase the Left Ripper and Render but on the honor vendor you can not.

**How to reproduce:**
try to purchase the "Bloodthirsty Gladiator's Left Ripper" and see that it is unavailable 

**How it should work:**
you should be able to see it from the vendor

**Database links:**
https://cata-twinhead.twinstar.cz/Raptor%20Egg?item=64775

![WoWScrnShot_041323_181533](https://user-images.githubusercontent.com/130712408/231902788-6b090fcc-aa24-4744-9e4a-7bed66c8434e.jpg)
![WoWScrnShot_041323_181531](https://user-images.githubusercontent.com/130712408/231902792-e0d55e73-6751-47d4-bf24-542e50f92868.jpg)
![WoWScrnShot_041323_181537](https://user-images.githubusercontent.com/130712408/231902795-d73e63a4-be79-4142-b98c-0fefebe17865.jpg)

**Comment by UltraNix** [comment]
Fixed.
