### ISSUE TITLE
Aoe looting only works the first time you loot

### ISSUE THREAD

**Issue by dan-personal** [gamefreedomgit/Maelstrom#3013]
**Description:**
Wasn't sure how to word the title for this one, but if you fail to loot everything on your first attempt to aoe loot, subsequent attempts to loot that same mob or any other mob involved in the aoe looting will only loot that individual mob.

Issue only confirmed with auto loot enabled and looting cancelled automatically via full inventory. Will update steps when I have a chance to test properly.

**How to reproduce:**
1. Enable auto loot. (Unsure if relevant)
2. Have only one inventory slot open. (Unsure if relevant)
3. Kill a decent sized pack of mobs.
4. Loot them.
5. Assuming at least 2 items dropped, observe that your looting session has been cancelled.
6. Now observe that looting any of the still lootable mobs will not result in an aoe loot, but an individual loot of that mob.

**How it should work:**
I would expect aoe looting to work every time you looted the mobs, not just the first time.

**Comment by UltraNix** [comment]
I see no bug here.
![WoWScrnShot_050423_214531](https://user-images.githubusercontent.com/80540499/236313391-dbacd5be-89e8-4fa2-99a6-a0d570d9d9b4.jpg)
You see here 3 mobs with loot inside and I have no free bag slots.

![WoWScrnShot_050423_214538](https://user-images.githubusercontent.com/80540499/236313486-105e963b-b475-45a9-a93d-b6c49975da4e.jpg)
Took some loot and some still inside body. AoE loot correctly worked, so only that bosy is lootable.

![WoWScrnShot_050423_214547](https://user-images.githubusercontent.com/80540499/236313631-41aeb732-ecff-4ef9-bf54-f8f9e9c6040d.jpg)
Another attempt to loot that body and still all items are inside.
