### ISSUE TITLE
AoE looting seems to not function correctly when looting very high counts of mobs.

### ISSUE THREAD

**Issue by dan-personal** [gamefreedomgit/Maelstrom#3014]
**Description:**
When looting a large amount of mobs at once (30+), aoe looting seems to fail to loot all of them.

**How to reproduce:**
1. Make sure you have sufficient bag space to accommodate all loot, ideally empty bags.
2. Kill a large quantity of mobs (I used Zul'Farrak).
3. Loot them.
4. Observe that (potentially) some mobs have been left unlooted.

**How it should work:**
For all mobs to be looted as part of the aoe loot.

Note: It's possible I am missing steps here, it's hard to know exactly what triggers this issue but it was very apparent while I was farming Zul'Farrak, chaining large pulls. This bug occurred in basically every single pull.

**Comment by UltraNix** [comment]
Already fixed.
