### ISSUE TITLE
Prospecting Macro is 80% efficient

### ISSUE THREAD

**Issue by msh2038** [gamefreedomgit/Maelstrom#3015]
**Description:**

If you use the simple macro of
/cast Prospecting 
/use <ORENAME>
if you spam prospect macro and clear a bag slot, it should auto prospect the next one, without getting the error message of item is gone

Assuming it might be the same for mill herbs for insciption
**How to reproduce:**
use macro when you have 2 stacks of ores and spam macro

**How it should work:**
No error message, smooth prospecting

**Comment by UltraNix** [comment]
Fixed.
