### ISSUE TITLE
second boss blackrock

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3016]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** sometimes players cant see the boss and cant dmg/tank it

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any snaps of that issue ?
