### ISSUE TITLE
Glubtok encounter issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3018]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Glubtok is mispositioned ( not in the middle of the fire spin ), so th firewall ends up pushing you into a side you can't dps him. There's 2 firewalls spinning which is wrong , which ends up killing people that don't notice very often. The 2nd firewall is spinning in the back left side.

**How to reproduce:**
Start the encounter

**How it should work:**

- Glubtok properly centered in the middle of the fire spins so melees can properly dps without taking dmg and within reach of the boss.
- Only 1 firewall spinning.

**Database links:**

**Comment by staR1336** [comment]
Closing as i am linking all issues in one report, #3342
