### ISSUE TITLE
New issue with dot clipping

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3020]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dot clipping/refresh is not adding the timer until your next tick into the next cast. May have been caused by a recent update, don't remeber this being the case few days ago. Druid Hots are working as intended. but not bleeds. Currently clipping rip or dot is just restarting the tick timer with no extra dots.

**How to reproduce:**
Tested with feral bleeds only. Hots are working as intended surpsisingly.

**How it should work:**
Dots should clip and not reset tick timer by adding the remaining time until next tick into your next cast

Don't think proof is needed but just in case.
https://www.mmo-champion.com/threads/775527-The-Cat-Guide-4-3
> Like rip, rake has gotten a big buff in 4.0 due to mastery, and agility giving 2 ap. Previously responsible for over 20% of your damage, in 4.2 will go down to 15%. If you reapply Rake when there's 3 or less seconds remaining on the current Rake (1 tick), the new Rake will have 3 seconds added to it.

**Database links:**

**Comment by bonfax4** [comment]
Happening with Rip/moonfire/insectswarm as well. Likely not just a druid problem but don't have another char to test.

**Comment by UltraNix** [comment]
All of these dots from above are missing special attribute - that's why the clipping mechanic does not work for them. It's not a generic problem, but with specific spells.

**Comment by bonfax4** [comment]
> All of these dots from above are missing special attribute - that's why the clipping mechanic does not work for them. It's not a generic problem, but with specific spells.

Just a matter of going over every class spell then i guess. Iirc all periodic effects ( not only dots/hots ) follow these clipping rules in cata right ? or are there any exceptions ?

**Comment by UltraNix** [comment]
As you can see, blizzard made some exceptions.

**Comment by UltraNix** [comment]
Fixed.
