### ISSUE TITLE
Big fps drop on RHC

### ISSUE THREAD

**Issue by SirKwony** [gamefreedomgit/Maelstrom#3024]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hello, i jump into a rhc today and something really wierd happend everyone in the party had a big fps drops ,our  healer had constant 3 fps at some point had to relog multiple times to finish the dung, me from usual 150-200 fps i gone to 30-20  ill leave some photos to prove it.Have to mention before this happend i tried to create a event on calendar and heared that is bugged but i dont see the conection between clendar didnt working and making 5 ppl haveing 10 fps.Anyway ty for you patience and fast responding hopefull this wont happen again
**How to reproduce:**

**How it should work:**

**Database links:**

https://imgur.com/a/HGzxwWR

**Comment by Waroxx-QA** [comment]
#3033
