### ISSUE TITLE
bug council

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** if u get grounded or winds at council u are throw out of texture

**How to reproduce:**
![image](https://user-images.githubusercontent.com/129559513/232098914-b321efba-0b18-4703-af33-4fe63db155c5.png)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#2288 3030
