### ISSUE TITLE
[Quest][Mount Hyjal] Inciting the Elements

### ISSUE THREAD

**Issue by apostolovskisimon** [gamefreedomgit/Maelstrom#3026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Following the Faerie Dragon while stealthed and when you start attacking the inciter when he is discovered while stealthed will cause the inciter (https://www.wowhead.com/npc=39926/twilight-inciter) to not attack you and to heal to full hp in a few seconds making him unkillable.

**How to reproduce:**
Let the dragon find the inciter while you are stealthed and then start attacking the inciter.

**How it should work:**
You should be able to normally kill him after being discovered no matter if you start attacking while stealthed or not.

**Database links:**
https://www.wowhead.com/quest=25370/inciting-the-elements
https://www.wowhead.com/npc=39926/twilight-inciter

**Comment by EdyGlockenspiel** [comment]
Additionally, if you are on GCD or mounted when you use the berry on the Faerie Dragon nothing will happen and you will use one of your Berries.

**Comment by EdyGlockenspiel** [comment]
Half the time I use the berries now nothing happens and they are consumed, even when dismounted and not on GCD. This quset is almost unable to be completed.
