### ISSUE TITLE
Fishing has a chance to have failed casts despite that mechanic being removed in wrath?

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3028]
**Description:**
Since wrath, when you fish in an area above your skill level, you will instead catch grey items like silckly looking fish, tangled fishing lime, tattered cloth ect. Currently though this is *not* the case. It seems when fishing in higher level areas with low level fishing your cast will fail like it did pre wrath.

**How to reproduce:**
Fish in a high level zone with low fishing skill

**How it should work:**
When fishing in an area above your skill level, you will instead catch grey items like silckly looking fish, tangled fishing lime, tattered cloth ect. These catches also can grant fishing skill.

**Database links:**
https://www.wowhead.com/skill=356/fishing#comments

**Comment by EdyGlockenspiel** [comment]
Another bug I just found with fishing is that turning your character mid fishing cast interrupts the cast. It shouldn't. Turning should not count as moving, like if I am turning while mounting it shouldn't interrupt the mount cast.

**Comment by bonfax4** [comment]
Something is wrong with fishing altogether. Skillups are taking longer than they should and apparently on patch 4.3 the amount of catches per skill up from 1-525  got halved. Check link below, it shows the average amount of catches needed per skill range.

https://web.archive.org/web/20120120152319/http://www.elsanglin.com/role_of_skill.html

> [Patch 3.1](https://web.archive.org/web/20120120152319/http://www.elsanglin.com/3_1_changes.html) changed the role of skill: Now you do not require a certain skill just to cast. With skill 1 you can cast anywhere. Junk items replace fish that "got away". Fish that "got away" did not improve your skill, but junk items do improve skill. So you can also now skill-up anywhere. For detailed analysis, read [The Role of Skill (Revised)](https://web.archive.org/web/20120120152319/http://www.elsanglin.com/the_role_of_skill.html). Patch 3.3 removed junk catches from pools. You will always catch fish from [pools](https://web.archive.org/web/20120120152319/http://www.elsanglin.com/equipment_and_pools.html), even at skill 1.

**Comment by EdyGlockenspiel** [comment]
I just tried fishing in outland with low skill and my fish "got away" still even have the "Core/Professions: Fixed fishing." in changelog, so it's still broke.

**Comment by EdyGlockenspiel** [comment]
Seems to be fixed (hopefully.) I just did the outland fishing daily on both of my toons and had 0 failed casts/fish that got away. Going to close this unless I sniff out an area where it still happens.
