### ISSUE TITLE
BOT 3.Boss ascendant council

### ISSUE THREAD

**Issue by Newernik** [gamefreedomgit/Maelstrom#3030]
Hi, with group at BoT raid we get bugged at 3. boss, everybody who get ground buff were get out up  to the air and falling down to die ... we cant continue this boss as normal kill please repair the bugged ground buff  thx

**Database links:**

**Comment by Newernik** [comment]
The spell Gravity Well dont get us Grounded thats the point sry i must find out spells names :D

**Comment by MrTide** [comment]
Bastion of twilight ascendant council, grounded effect is done by gravity well by the look of it

**Comment by MrTide** [comment]
similar report https://github.com/gamefreedomgit/Maelstrom/issues/3025

**Comment by GMHiki** [comment]
Big issue many groups are having, more than handful of tickets on this issue today

**Comment by Afgann** [comment]
fixed
