### ISSUE TITLE
Heroic Valiona and Theralion Cheat at Yugioh

### ISSUE THREAD

**Issue by AzureScyclone** [gamefreedomgit/Maelstrom#3031]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Whenever tanking Valiona (or Theralion) and building up the shift stacks, once it teleports you over to the shadow realm - the dragons are still chasing after your ass. This effectively almost guarantees the tank is going to be chomped without using cooldowns and rushing to the nearest portal to hopefully get back to the regular world and healed up. I noticed that even after Valiona would leave (phase transition), Theralion would land and still chase the tank in the shadow realm.

**How to reproduce:**
Tanking either dragon and being sent to the shadow realm

**How it should work:**
I am not sure if the dragons should even be present/targetable from the shadow realm, but even if they were - I thought that being sent to the shadow realm wipes all threat that the tank had on them.

**Database links:**

**Comment by franzkuplunga** [comment]
They shouldn't be targetable from the shadow realm. Only translucent to see them.

**Comment by AzureScyclone** [comment]
Yup, they are most certainly targetable, and absolutely loved targeting me :P

**Comment by Waroxx-QA** [comment]
@Alandiel please add it to your report
#3007

**Comment by Alandiel** [comment]
"You can continue tanking the currently grounded dragon while you are in the Twilight Realm."(https://www.icy-veins.com/wow/valiona-and-theralion-tank-strategy) 
The only thing that seems to be bugged is visual for bosses.
