### ISSUE TITLE
The Vortex Pinnacle FPS drop after first boss

### ISSUE THREAD

**Issue by franzkuplunga** [gamefreedomgit/Maelstrom#3033]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After today's update (14.4.2023), after you kill first boss, everyone gets a big FPS drop. Mine went from 100 constant FPS to 15 and then dropped to 7 fps at 2nd boss. Whole party had the same problem and it persisted up until the end. When we left the dungeon, FPS went back to normal. Relogging inside the dungeon temporarily fixed it, but dropped after going forward in the dungeon again.

**How to reproduce:**
Go through the dungeon after 1st boss is killed.

**How it should work:**
No FPS drops whatsoever.

**Database links:**

**Comment by emirie1** [comment]
A simple /reloadui will work to temporarily reset your FPS, but it will continue to decline as you progress further into the dungeon requiring multiple reloads by everyone in order to be able to finish.

**Comment by UltraNix** [comment]
Already fixed.
