### ISSUE TITLE
Game auto kicks player from a dungeon group after disconnect.

### ISSUE THREAD

**Issue by wrektor** [gamefreedomgit/Maelstrom#3034]
Description:

Today (4/14/2023) I experienced a bug where if I get disconnected while in a dungeon group, the game will automatically remove me from the group but I will still be visible to the dungeon group as Offline.

How to reproduce:

Get disconnected during a dungeon group.

How it should work:

I should be able to come back to the dungeon after getting disconnected.

**Comment by UltraNix** [comment]
Fixed.
