### ISSUE TITLE
crossfaction atackable in diremaul

### ISSUE THREAD

**Issue by xdreddx9** [gamefreedomgit/Maelstrom#3035]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in diremaul NPC casting mindcontrol, after that is crossfaction attackable, theres room for abusing it for honor

**How to reproduce:**
crossfaction party, 4h 1a, get party mindcontrolled, break mindcontrol, attack.

**How it should work:**

party members should change faction from friendly to hostile

**Database links:**
https://ibb.co/cgtwn85
- didnt found excact npc, because no db for cata

**Comment by UltraNix** [comment]
Fixed.
