### ISSUE TITLE
Unable to Right Click The Bobb

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#3037]
**Description:**
Over the last few days I have been trying to fish but there's been a major bug that's been getting in the way - and that is: that occasionally the fishing bob becomes untargettable, and thus I'm unable to right click it and reel the fish in. Although I move to cancel it and re-cast my rod, it'd interrupt the new fishing cast and give me the message "You missed your fish!". Despite having previously cancelled the previous fishing cast.

**How to reproduce:**
Go to any fishable zone and keep on fishing until you're unable to right click and target the fishing bob. After which, move your character again and re-cast another fish.

**How it should work:**
When you cancel your fishing cast, it should automatically remove the status on your character that says that you're still fishing - and the fishing bob should not be untargettable.

Side Notes: If you cancel a regular fishing cast that allows you to still right click the fishing bob, then it works completely as intended. However, as outlined in this issue, if the fishing bob becomes untargettable then it becomes an issue.

**Comment by UltraNix** [comment]
I tried a trillion times and still cannot reproduce it.
@clam119 Could you record a video of this?

**Comment by UltraNix** [comment]
Fixed.
