### ISSUE TITLE
Water Elemental Doesn't respawn with you on death in a BG

### ISSUE THREAD

**Issue by Adanoob** [gamefreedomgit/Maelstrom#3042]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Water Elemental is a permanent pet in Cata, when you die in a BG it respawns with you

**How to reproduce:**
Die in a BG as a frost mage, the ele won't spawn with you.

**How it should work:**
It is supposed to be alive with you when you respawn in a BG, like a hunter's pet.

**Database links:**

**Comment by Adanoob** [comment]
Actually, it seems to be all pets across all classes.

**Comment by sillsi** [comment]
Agree, pets should not despawn after death, next ressurection they should be alive with player.

**Comment by UltraNix** [comment]
Already fixed.
