### ISSUE TITLE
soloq

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3045]
The problem in soloq, when selecting players, adds a hunter and a mage to one team, this is utter absurdity, each such game is a loss, please remove this, it only spoils all the fun
mage hunter never playable comp

**Comment by mipanka** [comment]
low priority? Im on mage cant play soloq, -200 rate with hunter

**Comment by Sketish** [comment]
It's rather suggestion than bug that's why low prio.
