### ISSUE TITLE
[Quest] Keeping the Enemy at Bay

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#3046]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Flaming Oil](https://cata-twinhead.twinstar.cz/?item=34489) (Provided) does not provide quest credit when used on the quest objective.

**How to reproduce:**
On the Isle of Quel'Danas, take the daily quest 'Keeping the Enemy at Bay'. Speak to Ayren Cloudbreaker to initiate a flight to the objective. Then, during flight, use [Flaming Oil](https://cata-twinhead.twinstar.cz/?item=34489) as described. 

**How it should work:**
[Flaming Oil](https://cata-twinhead.twinstar.cz/?item=34489) (Provided) should provide quest credit when used on the boat sails.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11543

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
