### ISSUE TITLE
DK's Resilient Grip glyph issue

### ISSUE THREAD

**Issue by globalgame** [gamefreedomgit/Maelstrom#3047]
Death Grip ability with Resilient Grip glyph not always reset cd of Death Grip ability if player immune !

Previous topic closed https://github.com/gamefreedomgit/Maelstrom/issues/1954

**Comment by globalgame** [comment]
Updated info, Resilient Grip glyph not working if use +5 range another glyph for Death Grip at the same time

**Comment by UltraNix** [comment]
Just tested and works okay. @globalgame Are you able to replicate this one on regular duel every time?

**Comment by UltraNix** [comment]
No further info - closing.
