### ISSUE TITLE
Quest Mystery Solved gives rep for wrong Cenarion faction

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3049]
**Description:**
Mystery Solved currently gives rep with Cenarion Expedition, when it should give rep with Cenarion Circle.

**How to reproduce:**
Turn in the quest Mystery Solved

**How it should work:**
The quest should give rep with Cenarion Circle, not Cenarion Expedition.

**Database links:**
https://www.wowhead.com/quest=14282/mystery-solved
https://cata-twinhead.twinstar.cz/?quest=14282

**Comment by Afgann** [comment]
fixed
