### ISSUE TITLE
[Quest] Sludge Investigation - Northern Barrens

### ISSUE THREAD

**Issue by maldrek3103** [gamefreedomgit/Maelstrom#3059]
**Description:**
This quest is missing

**Database links:**
https://www.wowhead.com/quest=29087/sludge-investigation

**Comment by Afgann** [comment]
fixed

**Comment by Baleinebleu** [comment]
Hello Afgann, i saw you fixed this quest few days ago.  The quest exist now but the "Muddy track" that needs to be interact for this quest are not visible. Can you do something ? Do you want me to open a ticket somewhere ? Thks. Eddy.
