### ISSUE TITLE
soloq teams

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3060]
when matchmaking in soloq, the highest rated players are always added to the same team, and their opponents will be at least part of the team with a lower rated player
now all teams take hight rate same way
idk how fix it, only make report

**Comment by UltraNix** [comment]
@mipanka Still happens?

**Comment by mipanka** [comment]
it's been better lately. I'll take a look, thanks for taking the time

**Comment by mipanka** [comment]
I'll try to explain how it works now, I checked it yesterday
hight rate heal+2dps q and if they don't have an opponent with their rating, the system will look for one with a lower
as a result, a high rating team obviously plays against a weaker one
