### ISSUE TITLE
[Spell] Mage Flame Orb - shoots stealthed people in range

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3061]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** At the moment Flame Orb is able to shoot any target nearby, including stealthed units
Noticed the orb would shoot me while i was stealthed on my rogue alt. thought it was a fluke, turns out it is not.

**How to reproduce:** have a stealthed enemy nearby the mage's orb

**How it should work:** Definitely should not shoot stealthed opponents

**Database links:** https://cata-twinhead.twinstar.cz/?spell=82731

proof https://youtu.be/t2ov3QvqIaU

**Comment by mipanka** [comment]
why do you think this is a bug?

**Comment by staR1336** [comment]
> why do you think this is a bug?

This a joke?

**Comment by mipanka** [comment]
what proof do you have that this is a bug? I think if you reported, you should provide proof

**Comment by Only911** [comment]
It is not bug.
