### ISSUE TITLE
Professions can have Failed Attempts despite that feature being removed in wrath

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3064]
**Description:**
I just had a 'Failed Attempt' on my Archology gather, that profession was added *after* the Failed Attempt feature was removed from the game. This tells me *all* gathering professions, not just fishing have this which is obviously not intended. I even had my lockpick fail a few times as well on my rogue.

**How to reproduce:**
Attempt to gather something from a profession or pick a lock as a rogue with low skill.

**How it should work:**
Failed Attempts should not be present in the game at all for any skill/profession in cata, regardless of what profession or skill it is.

**Database links:**
I don't have a link because I don't feel like looking for the wowhead news post from over a decade ago stating this exact thing.

**Comment by EdyGlockenspiel** [comment]
You can check on *wrath* servers to see that failed attempts at professions were removed, Blizzard PTR or private servers. Archaeology digs never had that to begin with because that feature was already gone by the time it was added. It's the same problem with my other bug report for https://github.com/gamefreedomgit/Maelstrom/issues/3028 but that one is *just* about fishing.

**Comment by EdyGlockenspiel** [comment]
https://youtu.be/cXy173l2X6k?t=424

**Comment by UltraNix** [comment]
Fixed.
