### ISSUE TITLE
Prison Break quest not available or it's follow-ups. 

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3067]
**Description:**
With this quest and it's chain being missing, it locks out a whole bunch of Kirin Tor rep quests.

**How to reproduce:**
Turn in the quest Nick of Time/Too Close For Comfort

**How it should work:**
After turning in Nick of Time/Too Close For Comfort you should then be offered the quest Prison Break.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11587

**Comment by EdyGlockenspiel** [comment]
I assume it is because the other faction's breadcrumb quest is a requirement for some reason.

**Comment by PanJanuszek** [comment]
cannot reproduce
