### ISSUE TITLE
Flying mounts don't interact properly with water.

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3069]
**Description:**
When flying on a flying mount, it is impossible to go under the water unless you dismount first, this is not how it should work. When you fly into the water, you should keep going and it switch you to your swimming speed once you get below the surface. 

**How to reproduce:**
Fly into water on a flying mount

**How it should work:**
When you fly into water, you should go *into* the water, not stop like it's a solid wall.

**Database links:**
I don't have a link for this as it is just supposed to be a default feature to flying post TBC

**Comment by triceratopsrider** [comment]
Any proofs?

**Comment by Sketish** [comment]
Please provide any proof

**Comment by EdyGlockenspiel** [comment]
I mean I could get on the wrath classic PTR (which is free to play and DL) and upload a video as proof, would that be acceptable even though it is still wrath?

**Comment by Sketish** [comment]
I would prefer any video from retail cataclysm since then are using legion client for tbc/wrath classic

**Comment by EdyGlockenspiel** [comment]
Yeah I don't have that and can't go and create one, what if I got on a wrath private server like assmane or something and recorded that?

**Comment by EdyGlockenspiel** [comment]
So I checked both Dalaran WoW and Trashmane's wrath servers and both work the same way it does here. I am going to try and check Tauri's mop server and twinstar's cata server next.

**Comment by EdyGlockenspiel** [comment]
So I checked Tauri and it works the same way, water=wall when flying. Maybe it was changed much later than I remember.
