### ISSUE TITLE
Monitoring the Rift: Cleftcliff Anomaly unable to be completed

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3071]
**Description:**
Currently, Monitoring the Rift: Cleftcliff Anomaly is unable to be completed. This also locks you out of it's 2 follow up quests and a bunch of Kirin Tor rep.

**How to reproduce:**
Accept the quest Monitoring the Rift: Cleftcliff Anomaly, go to the area marked on the map and try to use the quest item.

**How it should work:**
Anywhere near the big purple seam at The Westrift should work to let you use the quest item

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11576#.

**Comment by EdyGlockenspiel** [comment]
So the GM Crywolf set the quest as completed for me, the follow up quest Monitoring the Rift: Sundered Chasm also suffers the same fate. The quest item refuses to work at all at it's intended area, making it impossible to complete and progress to the last quest on the chain.

**Comment by EdyGlockenspiel** [comment]
The last one in the chain, Monitoring the Rift: Winterfin Cavern also does not work either sadly. Quest item refuses to acknowledge you are in the correct area.

**Comment by EdyGlockenspiel** [comment]
Also for the follow up Monitoring the Rift: Sundered Chasm, the NPC is supposed to give the player a water breathing buff. 

https://cata-twinhead.twinstar.cz/?npc=25291#abilities

**Comment by PanJanuszek** [comment]
fixed 25.10.2023
