### ISSUE TITLE
[Quest] Diplomacy First

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#3074]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Looks like the phasing for that quest is broken.

**How to reproduce:**
Try to complete the quest Diplomacy first

**How it should work:**
https://www.youtube.com/watch?v=OPdGWG3tF0U&ab_channel=WorldOfWarcraftGuidesAndGameplay

**Database links:**
https://www.wowhead.com/quest=26247/diplomacy-first

**Comment by Sketish** [comment]
Can you provide any clip or snaps ?
