### ISSUE TITLE
The Oracles Reputation (Reins of the Green Proto-Drake)

### ISSUE THREAD

**Issue by Mepox1** [gamefreedomgit/Maelstrom#3076]
The quest can't be completed, because the "Mistwhisper Gorloc" NPCs can't be attacked. They appear hostile, but it's not possible to go through with an attack (I also tried using traps and my pet as hunter, but no damage). So it's not possible to acquire the Green Proto-Drake with the reputation. It already seems like, whatever achievements or mounts I decide to grind, a bug stops me almost instantly :/

SS: https://prnt.sc/If26fSBMNxxv

**Comment by Mepox1** [comment]
https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening

**Comment by PanJanuszek** [comment]
fixed 25.03.2024
