### ISSUE TITLE
Heartblossom 

### ISSUE THREAD

**Issue by ysiu15** [gamefreedomgit/Maelstrom#3078]
**Description:**
Heartblossom only spawns around the Temple of Earth. It should spawn all over the map.

**How to reproduce:**
Fly and try gather. 
![WoWScrnShot_041623_121551](https://user-images.githubusercontent.com/11962388/232294966-41c86899-ec8a-4362-82d1-9e338406a25a.jpg)

**How it should work:**
It should spawn all over the map.

**Database links:**
https://www.wowhead.com/object=202750/heartblossom#map

**Comment by UltraNix** [comment]
Fixed.
