### ISSUE TITLE
ghroul ability

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3080]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
raise dead ghroul have ability

**How to reproduce:**
to call ghroul from spell dk with ability raise dead

**How it should work:**
ghroul should not have ability (stun,charge) if dk does not use unholy spec

**Database links:**
https://wowpedia.fandom.com/wiki/Raise_Dead_(death_knight_ability)

**Comment by mipanka** [comment]
here ghoul have stun and charge, its bug

**Comment by EdyGlockenspiel** [comment]
It's not a bug. It was a bug when they *didn't* use the abilities.

**Comment by UltraNix** [comment]
Fixed.
