### ISSUE TITLE
Nefarian´s End

### ISSUE THREAD

**Issue by Newernik** [gamefreedomgit/Maelstrom#3081]
Hi, we found out new sexy Bug or problem :) last boss Nefarianś End at the end of 1. phase after killing Onyx all group members get error and disconnect from server we asking GMs in game to help so they check in game what we found so i post it in here to tell you about this one please fix it as soon as possible.

[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by MrTide** [comment]
Can confirm it requires attention as soon as possible
https://cdn.discordapp.com/attachments/1094415460113596546/1097193783759736882/image.png
https://imgbox.com/YZXScUI8

**Comment by UltraNix** [comment]
Fixed.
