### ISSUE TITLE
[Quest] [NPC] - Twilight Highlands - Dragon, Unchained (QID = 27701)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#3084]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27700/dragon-unchained)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27701)

**Description: Lirastrasza not spawning**

**How to reproduce:**
Simply take the quest, get the elementium axe then go to where Lirastrasza is being held captive and chained. She won't be there.
![image](https://user-images.githubusercontent.com/29439770/232340409-a3aa104a-77d8-457b-961c-95eb025c0f80.png)

You might wanna check the Alliance version too (QID = 27700)

**How it should work:**
Like this Yt video: https://www.youtube.com/watch?v=4gs0gHkqJVY

**Database links:**

**Comment by MrTide** [comment]
duplicate

**Comment by PanJanuszek** [comment]
Added npc with text & invis flag
