### ISSUE TITLE
[Quest] [NPC] - Twilight Highlands - Kor'Kron Drop (QID=27491)

### ISSUE THREAD

**Issue by BurntTongue** [gamefreedomgit/Maelstrom#3085]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27491/korkron-drop)
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?quest=27491)

**Description:**

**How to reproduce:**
Simply take the quest from the nearby quest giver. You are supposed to talk to Jon-Jon Jellyneck and receive a dialogue option to get a wind rider squad then fly off the drop point. You simply don't get the option.
![image](https://user-images.githubusercontent.com/29439770/232340796-6127a24b-408c-4529-bb70-5b6d9b0da444.png)

**How it should work:**
https://www.youtube.com/watch?v=_8sJwgYAN00

**Database links:**

**Comment by MrTide** [comment]
duplicate
