### ISSUE TITLE
coudnt need on BOE

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3086]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** cloth chest dropped and only mage coud need , the rest of party could only greed, but is BOE

**How to reproduce:**
![image](https://user-images.githubusercontent.com/129559513/232344408-e39f26de-d56d-42fa-8d7d-580ab69e91ac.png)

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
That's normal, It's not a bug.
But it should be soulbound when he need it so he can't sell it (On RDF only)
