### ISSUE TITLE
Death Grip does not work correctly on ranged NPCs

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3087]
**Description:**
When you use Death Grip on a ranged NPC, whether it be a caster or something like the mob uses "throw" ability ect, it does not work and only pulls them a short distance instead of pulling them to be directly in front of you like all other mobs. 

**How to reproduce:**
Grip a mob with ranged attacks.

**How it should work:**
When you use Death Grip it should pull the target to you regardless of if the target can cast or not.

**Database links:**
https://www.wowhead.com/wotlk/spell=49576/death-grip#comments

**Comment by globalgame** [comment]
Sometimes in pvp on mages Death Grip does not work too somehow and with Resilient Grip glyph does not reset cd if target immune...

**Comment by EdyGlockenspiel** [comment]
Also when gripping a mob that is mid cast, it does not interrupt the cast like it should. Or maybe it is a bug with doing it in melee but either way that would still be a bug. Why this is not labeled as an important bug report I have no idea since this affects DKs in pve greatly.

**Comment by UltraNix** [comment]
Fixed.
