### ISSUE TITLE
Divine Storm and Holy Wrath with Divine Purpose 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3088]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Divine Storm and Holy Wrath currently only proc this talent on hit.

DS and HW should proc this on cast, not on hit.

SpellWorks and Simcraft also do not show a requirement to hit anything.

**How to reproduce:**

1. Spam DS/HW, try to get a proc.
2. You will not get any procs without hitting at least one target

**How it should work:**

**Database links:**

https://web.archive.org/web/20120226130425/http://www.wowhead.com/spell=86172#comments

"It means per cast, not per hit"

**Comment by Sketish** [comment]
This comment is from patch 3.3.5

Please provide any proof from cataclysm.

**Comment by Renehadox** [comment]
> This comment is from patch 3.3.5
> 
> Please provide any proof from cataclysm.

Mister Developer, Divine Purpose did not exist in Wrath. :D

[Wafflepower](https://web.archive.org/web/20120226130425mp_/http://www.wowhead.com/user=Wafflepower) [on 2011/01/31](https://web.archive.org/web/20120226130425/http://www.wowhead.com/spell=86172#comments:id=1138359:reply=220552) (Patch 4.0.3)

**Comment by Sketish** [comment]
Ok so, pressing spell is rolling the chance for proc not amount of targets it hit.

**Comment by Renehadox** [comment]
> Ok so, pressing spell is rolling the chance for proc not amount of targets it hit.

Yes, also the replied comment is from 4.0.3 patch.

It should proc upon spell cast not spell hit.

**Comment by UltraNix** [comment]
@Renehadox @Sketish What about https://github.com/gamefreedomgit/Maelstrom/issues/2103?

**Comment by UltraNix** [comment]
This is not a bug. You just took the sentence out of context.
```
Using Divine Storm on 1 target will proc this the same amount as using it on 10.
```
The comment you linked is about number of procs. So it does not matter if you hit 1 target or 10 targets- you have always 1 proc. But you need to hit somebody.
https://github.com/gamefreedomgit/Maelstrom/issues/2103
