### ISSUE TITLE
Daily quest Smoke 'Em Out does not work if you are in combat with the mobs

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3089]
**Description:**
A general tactic for this quest is to gather up all the mobs via face pulling on your flying mount then use the quest item to get credit for a whole building's worth. Currently this only resets them and does not grant any credit for the quest unless they are not in combat when you use the item, making it take way longer to do.

**How to reproduce:**
Get into combat with the Venture Co. Stragglers and use the quest item on them.

**How it should work:**
When you use the quest item on the mobs you should instantly be granted credit for the quest per mob you hit, then they should become unattackable and run away then despawn. Regardless of being in combat with them or not.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12323

**Comment by PanJanuszek** [comment]
fixed 16.05.2024
