### ISSUE TITLE
Tracking Currencies in your backpack resets after a loading screen or logout. 

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3093]
**Description:**
When you relog, or hit a loading screen, the currencies you set to track in your backpack reset and are no longer tracked afterwards. 

**How to reproduce:**
Track any currency in your backpack then relog.

**How it should work:**
Currency tracked via backpack should be saved between loading screens/relogs.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
