### ISSUE TITLE
Hunter pet revive but and crab skill bug

### ISSUE THREAD

**Issue by Nightwiings** [gamefreedomgit/Maelstrom#3097]
**Description:**
Cuando mi mascota muere antes que yo en las bgs y luego muero yo, al revivir mi mascota no revive conmigo, debo revivirla manualmente! deberia ser que cuando yo revivo, mi mascota tambien deberia revivir! dejare un ejemplo de como es en otro servidor.

![Pet revive](https://user-images.githubusercontent.com/131043094/232596451-17d635fe-bd09-417c-a3d8-5781d6b374c8.png)

tambien el talento del cangrejo " intervenir" deberia darme una cantidad alta de absorcion de daño, pero aqui en whitemane tiene un error ese talento, dejare igualmente un ejemplo de como deberia ser y como es aqui en whitemane.

![pet crab](https://user-images.githubusercontent.com/131043094/232596272-a9d827ff-3b84-4176-b9a6-0c1700a8d4c0.png)

When my pet dies before me in the bgs and then I die, when I revive,my pet it doesn't revive me, I have to manually revive it! It should be that when I revive, my pet should also revive! I will leave an example of how it is on another server.

![Pet revive](https://user-images.githubusercontent.com/131043094/232596451-17d635fe-bd09-417c-a3d8-5781d6b374c8.png)

also the talent of the crab "intervene" should give me a high amount of damage absorption, but here in whitemane that talent has an error, I will also leave an example of how it should be and how it is here in whitemane.

![pet crab](https://user-images.githubusercontent.com/131043094/232596272-a9d827ff-3b84-4176-b9a6-0c1700a8d4c0.png)

**Database links:**
https://wowpedia.fandom.com/wiki/Intervene_(pet)

**Comment by Waroxx-QA** [comment]
Pet part isn't a bug, "another server" isn't a valid reference.

**Comment by Nightwiings** [comment]
i put a other server for show how must work... if u play 4.3.4 in the oficial wow u must know how crab skill work! and in all server in BGS when the hunter die! and revive the pet revive too... AND see the wowpedia link.. how the skill works.

**Comment by Nightwiings** [comment]
See in minute 1:30
https://www.youtube.com/watch?v=SMSj3jzoBRE&t=90s

**Comment by UltraNix** [comment]
Both fixed.
