### ISSUE TITLE
Raise Dead ghoul has no totem timer for frost/blood

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3098]
**Description:**
Currently when a non unholy DK summons their Raise Dead ghoul, it has no totem timer, this makes tracking it's duration very difficult and makes it impossible to dismiss early.

**How to reproduce:**
Summon your Raise Dead Ghoul as a non unholy DK.

**How it should work:**
Just like Shaman totems, the Raise Dead ghoul should have a totem timer that displays it's remaining duration to the player under their portrait, and can be right clicked to 'dismiss' the ghoul early.

**Database links:**
https://www.wowhead.com/wotlk/spell=46584/raise-dead#comments

**Comment by EdyGlockenspiel** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/126888684/e9fbef9f-cae0-4034-bab1-40d5f7aa4432)
For those wondering, this is the thing I am talking about here, the thing I am mousing over in the screen shot.

**Comment by UltraNix** [comment]
@EdyGlockenspiel It was a thing on cata retail? I see you posted a screenshot from Wotlk?

**Comment by UltraNix** [comment]
Fixed.
