### ISSUE TITLE
North Sea Kraken can not be killed

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3100]
**Description:**
Because North Sea Kraken can not be killed, that means the daily quest you get from killing it with the quest item is unable to be obtain as well.

**How to reproduce:**
Get the daily quest Get Kraken! and use the quest item on North Sea Kraken

**How it should work:**
The North Sea Kraken's HP should stay damaged when it is hit by the quest item, allowing players to kill it and get the daily quest tooth.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=34925
https://cata-twinhead.twinstar.cz/?quest=14108
https://cata-twinhead.twinstar.cz/?item=46955#starts

**Comment by PanJanuszek** [comment]
fixed 25.04.2024
