### ISSUE TITLE
Among the Champions unable to be completed

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3102]
**Description:**
There seems to be a LOT bugged with the whole of the Argent Tournament. For one, the horses' charge ability seems to do no damage to the target, the enemy mounted target seemed to randomly regen HP for seemingly no reason, and when they got down to one HP, nothing happened. They just kept fighting me exactly the same way. 

**How to reproduce:**
Start the quest Among the Champions and get on a horse, then talk to one of the Racial Champions.

**How it should work:**
When the Racial Campion gets reduced to one HP, you should be awarded with Mark of the Champion and given a debuff that prevents you from fighting that race again for a few min. The NPCs also should not randomly regen chunks of their HP.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13793
https://cata-twinhead.twinstar.cz/?item=45500#created-by

**Comment by EdyGlockenspiel** [comment]
Alright after attempting again using the Stormwind horse I found out charge *heals* them for the amount of damage it should be dealing instead. Also Shield-Breaker throws 2 lances at once.

**Comment by EdyGlockenspiel** [comment]
The Stormwind Champions are unattackable after challenging them to a fight, they will just follow you around and do nothing.

**Comment by EdyGlockenspiel** [comment]
Same with the Darnassus Champions.

**Comment by EdyGlockenspiel** [comment]
The Exodar Champions reset if you move 2 yards away from them.

**Comment by EdyGlockenspiel** [comment]
Orgrimmar and Undercity Champions also suffer the same fate as the Stormwind and Darnassus Champions.

**Comment by EdyGlockenspiel** [comment]
The Sen'Jin, Thunder Bluff and Silvermoon Champions all also reset if you move an inch away from them after combat starts.
