### ISSUE TITLE
darkmoon volcano rarely procs

### ISSUE THREAD

**Issue by Fystorm** [gamefreedomgit/Maelstrom#3106]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment]
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2915
