### ISSUE TITLE
[DRUID][SPELL] - Thorns - Partially Working

### ISSUE THREAD

**Issue by dadawdawdwada** [gamefreedomgit/Maelstrom#3110]
[//]: # (cata-twinhead.twinstar.cz)
https://cata-twinhead.twinstar.cz/?spell=467

**Description:**
Thorns not working when used on TARGET.
Thorns only working when used on myself. The caster of Thorns.

Picture1 - Thorns on my Teammate, enemy is attacking him and nothing is happening
https://imgur.com/a/iW7SJah

Picture2 - Thorns on my Teammate, enemy is attacking him and nothing is happening
https://imgur.com/a/EyIRA8P

Picture3 - Thorns on myself, enemy attacking me they taking damage.
https://imgur.com/a/rxARvZN

**How to reproduce:**

Use Thorns on Anyone and they do nothing. They only work when casted on myself.

**How it should work:**
Cast thorn on any target when they take damage they should deal damage back.
( Thorns sprout from the friendly target causing X Nature damage to attackers when hit. )

**Comment by UltraNix** [comment]
Against mob:
![image](https://user-images.githubusercontent.com/80540499/232894076-928a0a78-c711-4af8-a6ed-9189195b21a8.png)

Against other player:
![image](https://user-images.githubusercontent.com/80540499/232894535-3dca8d5d-4d8b-4912-bd36-e9b732d8961b.png)

Everything works okay here.

**Comment by dadawdawdwada** [comment]
No

You need 3 people. 2 Friendly 1 enemy.

you (1) cast thorns on friendly target (2) and let the enemy (3) attack. Thorns do not work.

Its clearly here.
I think you miss understood my report
https://imgur.com/a/iW7SJah
https://imgur.com/a/EyIRA8P



What you did is used thorns on YOURSELF. This way yes thorns work but use them on somebody else.

**Comment by UltraNix** [comment]
@dadawdawdwada You can see clearly, that Druidds casted Thorns on Dasd and then Dasd is attacked by another player. 2 friendly, 1 enemy.
@Waroxx-QA Have you confirmed that bug by yourself?

**Comment by Waroxx-QA** [comment]
@UltraNix Ofc i've confirmed it, and it's not working

**Comment by Waroxx-QA** [comment]
White flag, my bad i've tried it without activating pvp/gm on druid, just fixed everything and it's working properly.
Sorry for the inconvenience @UltraNix 🙇‍♂️
