### ISSUE TITLE
Make Don Carlos Fabolous hat transmogifiable  

### ISSUE THREAD

**Issue by Dalvae** [gamefreedomgit/Maelstrom#3111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Don Carlos Fabolous hat should be  transmogifiable into cloth heads.

**How to reproduce:**
Try to aply the don carlos fabolous hat into the transmog tab, and you get an error msg.
![imagen](https://user-images.githubusercontent.com/101679648/232845601-619cf7ea-83f9-4c76-b030-ae0b15c7a34f.png)

**How it should work:**
It should change the aparence of your hat into Don Carlos Fabolous hat.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=38506

**Comment by UltraNix** [comment]
It's not a bug- client restrictions.
