### ISSUE TITLE
Chogall HC, Darkened Creations

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#3116]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Darkened Creations do not have nameplates in heroic phase.

**How to reproduce:**
Get to heroic phase, pull boss closeish to wall, observe no nameplates

**How it should work:**
https://youtu.be/M90ZyCg-Pys?t=306
They should have nameplates

**Database links:**

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/234396083-994824a3-833a-409a-ba87-8b9f162c60e2.png)
Everything works okay.

**Comment by Stega23** [comment]
https://www.twitch.tv/stegaraid/v/1801638872?sr=a&t=3742s
You can see how it doesnt work.
