### ISSUE TITLE
Tree of Life + Lifebloom refreshes out of tree form bug

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3117]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1. Currently you can maintain as much lifebloom stacks rolling as possible after tree of life form ends, if you don't let them fall off.
2. Empowered touch is working on every single different target of Lifebloom after Tree ends.

**How to reproduce:**
Spam Lifebloom on different targets while tree of life is active and then recast or renew via empowered touch talent.

**How it should work:**

1. Don't exactly know how it works but I noticed tree of life lifebloom has a different ID (https://cata-twinhead.twinstar.cz/?spell=94447 ) so there might be a clue there but surely the current iteration is not blizzlike or it would be noted by every cataclysm resto guide. My guess is this empowered version of lifebloom is only refreshable with ET spell casts while the tree of life buff is up. A "normal" lifebloom cast (after tree finishes) would still refresh this version of the buff and make it into a normal one so the hotfix they did that I mentioned below would work and make it refreshable again, and still keep the other blooms unrefreshable and subsequent attempts of refreshing another via direct cast would remove the previous one since there can't be more than one "normal" bloom up ? Either this or a normal lifebloom cast done after the 1st could simply remove all other blooms ?  I'm trying to look for old videos to see how this interaction would pan out.

3. Was hotfixed during 4.0.6 to not allow this to happen. Only the most recent lifebloom cast/refresh after tree ends should be able to be refreshed by regrowth/nourish/healingtouch with Empowered Touch.

https://wowwiki-archive.fandom.com/wiki/Patch_4.0.6

> Empowered Touch now also affects Regrowth. In addition, after Tree of Life is no longer active, this talent will only refresh the most recently cast or refreshed Lifebloom, and will not refresh other copies of Lifebloom.

To note that on these discussions they only speak about maintaining the blooms via empowered touch and not normal casts before the hotfix. Refreshing via normal casts def caused something different to happen.
https://www.mmo-champion.com/threads/835036-Tree-form-Lifebloom-Nourish-more-than-one-Lifebloom-after-tree-wears-off

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=33763
https://cata-twinhead.twinstar.cz/?spell=33880

**Comment by bonfax4** [comment]
https://youtu.be/9X0BFI05Ntg?t=92 

Normal regrowth casted right after tree ends did not refresh the Tree form lifebloom as expected @ 1:34

**Comment by UltraNix** [comment]
Fixed.
