### ISSUE TITLE
SHALE SPIDER BUG 

### ISSUE THREAD

**Issue by Noak1234** [gamefreedomgit/Maelstrom#3118]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
![Screenshot_11](https://user-images.githubusercontent.com/129035688/232949196-32e1dc07-4e10-4365-916e-1b38d3ee9b15.png)
![Screenshot_12](https://user-images.githubusercontent.com/129035688/232949200-ab718a61-9553-42bb-9b00-cecfe486c8bd.png)
![Screenshot_13](https://user-images.githubusercontent.com/129035688/232949204-dedc36eb-7d7e-4141-a68a-c3ff8e8488f5.png)

[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
According to the spell of the pet, it should create a buff that absorbs 50% of the pet's life, but instead it only absorbs 50 life

As a second bug of this same pet, when you use anticritical this time it doesn't hit again until you return it and it attacks again, it shouldn't be like that, this pet is not working correctly

**Comment by UltraNix** [comment]
Fixed.
