### ISSUE TITLE
[WOTLK][Quest+NPC] Orfus of Kamagua + his chain of quests

### ISSUE THREAD

**Issue by Exorcista** [gamefreedomgit/Maelstrom#3121]
**Description:** The quest https://www.wowhead.com/wotlk/quest=11504/the-dead-rise cannot be obtained or started by Horde players via the npc: https://www.wowhead.com/wotlk/npc=23804/orfus-of-kamagua, did all chain leading up to it, didn't got "The Dead Rise!" from any NPC at any of the quest Hubs known in Howling Fjord or even at him directly

**How it should work:** Just make him give the quest, is a huge chain to unlock one of the few dailies for Kalu'ak Rep

**Database links:**

- Orfus of Kamagua: https://www.wowhead.com/wotlk/npc=23804/orfus-of-kamagua
- The Dead Rise! quest: https://www.wowhead.com/wotlk/quest=11504/the-dead-rise

**Comment by Aurorre** [comment]
Still not working 7 months later ( 3-11-2023 )

**Comment by PanJanuszek** [comment]
cannot reproduce anymore

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/f5ebfed9-3e78-4b5a-83dc-58f0155ad713)
