### ISSUE TITLE
Cunning pets' wolverine bite not working..even after hitting critical

### ISSUE THREAD

**Issue by utp9210** [gamefreedomgit/Maelstrom#3122]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[[//]: # (http://wowhead.com/)](https://www.wowhead.com/wotlk/spell=53508/wolverine-bite)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Cunning pets (birds etc) cant use their wolverine bite even after hitting a critical...i let my pet hit a dummy for hours it doesnt use it..i cant even use it manually....

**How to reproduce:**

**How it should work:**it shuld use it on its own after hitting a critical strike..

**Database links:**

**Comment by VirtualReign** [comment]
Can confirm. After spending the talent point in the ability it just remains greyed out. It's cannot be used neither manually or via auto-cast.

**Comment by UltraNix** [comment]
Fixed.

**Comment by vishanska** [comment]
hi now it is usable but inflicts almost negative damage even lvl 85, Currently my hunt is 377 ilvl the bite of my pet inflicts 800 max crit. thx
