### ISSUE TITLE
[Class: Priest][Spell] Cure Disease spell with Body and Soul talent does not remove poison

### ISSUE THREAD

**Issue by Hatepoem** [gamefreedomgit/Maelstrom#3123]
Given character has invested points in "Body and Soul" talent, when "Cure Disease" spell is cast on player by themselves, then one poison effect must be removed.

The talent grants two features. First, it modifies Power Word: Shield spell. This first feature works.

The second feature is ability to remove poison with Cure Disease spell, which baseline priest cannot do. But this does not happen. It is possible for the poison to resist the cleansing, but not this much.

Right now I cannot remove poison with my character despite having invested into the talent. It may have worked sometimes, but not most of the time.

I tried resetting the talents, it did not help.

[Body and Soul](https://cata-twinhead.twinstar.cz/?spell=64129)

**Comment by UltraNix** [comment]
Fixed.
