### ISSUE TITLE
[QA Run] Throne of the Four Winds - Heroic / Normal issues list

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#3124]
### **- The Conclave of Wind -**

> **- Bosses energy not dropping to 0% after full Energy phase**
> Also hitbox on the 3 bosses is smaller than it should be, as a melee you should be able to hit rohash for example even if the tornades are inside him without getting bumped.

> **- Rohash:** Wind Blast is broken, visual is missing, and if you dodge the ability by going to the right side, and you go back to left side where he started Wind Blast ( even if the boss has turned but still channeling ) you get hit and knocked by the ability, hits are insane, looks like there is a lot of wind blasts at the same time, and DXE can confirm it [SCREENSHOT](https://imgur.com/osirMbb)...
> 
> **- Anshal:** Adds are falling undermap sometimes.
> 

### **- Al'Akir -**

> **Phase 2:** Acid Rain stacks are dropping if you go to the edge of the plateform. it shouldn't drop.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Waroxx-QA** [comment]
- Anshal adds still going undermap.
- Rohash's Wind Blast isn't working properly.

**Comment by UltraNix** [comment]
Fixed.
