### ISSUE TITLE
Romulo and Julliette in Karazhan fight bugged on me

### ISSUE THREAD

**Issue by docter100000** [gamefreedomgit/Maelstrom#3125]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I killed Romulo for the second time he just laid down and started spinning around following me freezing the encounter

**How to reproduce:**
Kill Romulo

**How it should work:**
He should die and end the encounter

**Database links:**

**Comment by PanJanuszek** [comment]
@Afgann fixed it long time ago
