### ISSUE TITLE
bug en la mision de inicio para uldum

### ISSUE THREAD

**Issue by c1o2o3** [gamefreedomgit/Maelstrom#3126]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

en la misison de inicio para uldum que es yendo a tanaris, el npc de la mision no te lleva hasta uldum como normalmente lo hace, por lo tanto no puedes seguir con la cadena de misiones de ese lugar
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by c1o2o3** [comment]
tambien hay otro bug, cuando un huargen se desconecta montado en la montura racial y luego vuelve a conectarse el personaje parece que estuviera montado en algo invisible y se ve demasiado raro

**Comment by Waroxx-QA** [comment]
Please make your next reports in ENGLISH or it will be closed as invalid.
