### ISSUE TITLE
[Quest] Arelion's Mistress - Unable to talk to NPC

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#3128]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to finish [Arelion's Mistress](https://www.wowhead.com/beta/quest=9472/arelions-mistress). Cannot talk to NPC Viera Sunwhisper even with required item [Cenarion Spirits](https://www.wowhead.com/beta/item=29112/cenarion-spirits) in inventory, thus unable to use quest item [Carinda's Scroll of Retribution](https://www.wowhead.com/beta/item=23693/carindas-scroll-of-retribution) on her without taking her to discreet location.

**How to reproduce:**
Talk to Viera Sunwhisper, with or without [Cenarion Spirits](https://www.wowhead.com/beta/item=29112/cenarion-spirits) you do not have any option to take her to discreet location.

**How it should work:**
Once you have [Cenarion Spirits](https://www.wowhead.com/beta/item=29112/cenarion-spirits) in inventory, you should be able to talk to her and take her to a discreet location to use [Carinda's Scroll of Retribution](https://www.wowhead.com/beta/item=23693/carindas-scroll-of-retribution) on her.

**Database links:**
https://www.wowhead.com/beta/quest=9472/arelions-mistress

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
