### ISSUE TITLE
unable to exchange a item if its enchanted 

### ISSUE THREAD

**Issue by wowaholicx** [gamefreedomgit/Maelstrom#3133]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Unable to exchange a weapon that has been enchanted back to the honor Shop.

**How to reproduce:**
n/a

**How it should work:**
it should strip the item of the enchant as take the item back for the currency u bought it for if the item hasnt been out for 24 hours since the purchase

**Database links:**

![image](https://user-images.githubusercontent.com/131395459/233448867-13755055-b542-42ce-8a26-2ec7d0ef76d3.png)

**Comment by UltraNix** [comment]
Enchanted items cannot be refund to vendor.
