### ISSUE TITLE
Classic Alliance Mail & Plate vendor not working in Area 52

### ISSUE THREAD

**Issue by RosinaScarlett** [gamefreedomgit/Maelstrom#3134]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Classic Alliance Mail & Plate vendor not working in Area 52. the Classic Horde Mail &  Plate vendor works

**How to reproduce:**
N/A

**How it should work:**
Should sell the gear for rank 11-14 Alliance Mail & Plate armor for Transmog

**Database links:**
https://www.wowhead.com/npc=23396/krixel-pinchwhistle

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a3979a5c-8d6a-45f4-8789-180cf67b9282)
Tested - works okay.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/cde09331-a4df-45fa-b3f1-8138dda19099)
Works okay.
