### ISSUE TITLE
Hand of Salvation bug in arenas PVP

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#3135]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There's alot of paladins in arenas that are using a Hand of Salvation bug at the moment, where they use Hand of Salvation versus stealth teams and if they are against a mage who is using the ability invisibility the invisibility stops immediatly. 

**How to reproduce:**
In arenas. Have a paladin use Hand of Salvation on his arenapartner - while the enemy mage goes into invisiblity. Now the invisibility spell on the mage breaks.

**How it should work:**
The paladin ability Hand of Salvation is described in the following way:

"Places a Hand on the party or raid member, removing all threat from the target for 10sec. 
Places a Hand on the party or raid member, reducing their total threat by 2% every 1 sec for 10sec.
Players may only have one Hand on them per Paladin at any one time."

Shouldn't effect enemies. 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=1038
https://cata-twinhead.twinstar.cz/?spell=66

**Comment by UltraNix** [comment]
Fixed.
