### ISSUE TITLE
Darkmoon Card: Volcano. Breaking your own polymorph.

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#3136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The trinket "Darkmoon Card: Volcano" is currently able to proc from the ability polymorph. 
This means that a mage is able to break his own polymorph with this trinket. 

**How to reproduce:**
Have a mage wearing Darkmoon Card: Volcano trinket. Now duel another person and spam Polymorph untill the trinket procs --> will automatically break your own polymorph, which is not intended.

**How it should work:**
"When dealing damage with spells, you have a chance to deal 899 to 1500 additional Fire damage to the target and gain 1600 Intellect for 12sec."

The mage ability polymorph does not deal damage and should therefore not be able to proc this trinket.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=62047
https://cata-twinhead.twinstar.cz/?spell=61721

**Comment by UltraNix** [comment]
Already fixed.
