### ISSUE TITLE
Hunter monkey-pet bug with smokebomb. 

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#3137]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hunters are currently capable of using the pet ability "Bad Manner" on people standing in smoke bombs even though the pet is not standing in the smoke bomb.

**How to reproduce:**
In a duel. Let a hunter and rogue go up against each other. Let the rogue drop a smokebomb on top of himself. Have the pet stand outside the smokebomb and cast "Bad Manner" ability. The monkey pet doesn't care about the smokebomb, and the rogue will get stunned. 

**How it should work:**
"Creates a cloud of thick smoke in an 8 yard radius around the Rogue for 5sec. Enemies are unable to target into or out of the smoke cloud."

The hunter pet should therefore not be able to use abilities on people standing inside the smokebomb. 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=90337
https://cata-twinhead.twinstar.cz/?spell=76577

**Comment by UltraNix** [comment]
@raller1006 What about #1481?

**Comment by raller1006** [comment]
The pet is casting "Bad Manner" outside the smokebomb and the rogue will get blinded even if he's standing in the smokebomb. The pet doesn't run into the smokebomb (1481). I've tested this in duels multiple times, and it's the same outcome every time.

**Comment by UltraNix** [comment]
I mean - in #1481 reporter says the pet should cast Bad Manner even if rogue is inside Smoke Bomb. So #1481 so invalid?

**Comment by raller1006** [comment]
Agreed the pet should run into the smokebomb and then cast "Bad Manner". However right now this is not the case. Right now the pet doesn't care about the smokebomb and just cast "Bad Manner" through smokebomb.

**Comment by UltraNix** [comment]
`Agreed the pet should run into the smokebomb and then cast "Bad Manner"`
`Right now the pet doesn't care about the smokebomb and just cast "Bad Manner" through smokebomb`
?? I don't understand. First you say that pet should cast Bad Manner through Smoke Bomb, but then you say that this is the case. Or maybe I'm confused

**Comment by raller1006** [comment]
What do you mean? Bad Manner has 20y radius obviously, but that doesn't mean the hunterpet is suppose to cast spells to people standing in smokebomb?

**Comment by raller1006** [comment]
Has to be a misunderstanding - don't recall saying the pet should cast Bad Manner through Smoke Bomb. I'm saying that's the bug :) That's the part that's not intended

**Comment by UltraNix** [comment]
Yeah - I don't understand the report at all :)

**Comment by raller1006** [comment]
Can I show you in Elwynn forrest? It's really easy for me to showcase the problem there hehe.

**Comment by raller1006** [comment]
It's like every other class can't cast spells to people standing in Smoke Bombs... 
Frostbolt has 35 yd range also, but that doesn't mean I can cast it to a rogue standing in Smoke Bomb hehe :D It says your vision of the target is obscured. 

And that's what should happen to the Monkey Pet also :)

**Comment by UltraNix** [comment]
Fixed.
