### ISSUE TITLE
[Twilight Highlands] Any Portal in a Storm quest item drop chance

### ISSUE THREAD

**Issue by apostolovskisimon** [gamefreedomgit/Maelstrom#3138]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The drop chance of the quest item seems to be too low. Wowhead shows it at 17% but it feels like its less here.
I've killed atleast 10 of them and only 1 dropped.
Would be a nice QoL change atleast to increase the drop chance.

**How to reproduce:**
Grab quest https://www.wowhead.com/quest=27537/any-portal-in-a-storm#see-also and kill the elementals to get 5 quest items.

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=27537/any-portal-in-a-storm#see-also
https://www.wowhead.com/item=60333/whirlpool-core#comments

**Comment by Sketish** [comment]
It's rather suggestion than bug. Dropchance is correct.

**Comment by MrTide** [comment]
Player is correct reopening this issue
https://cata-twinhead.twinstar.cz/?item=60333
https://cata.cavernoftime.com/item=60333#dropped-by
drop rate should be 40-90% 
Right now its way lower than it should and players struggling over it for no reason

**Comment by Afgann** [comment]
fixed
