### ISSUE TITLE
[PvE] [Warrior] Bladestorm on Chogall rooting the warrior

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3139]
**Description:**
If you're using Bladestorm on Chogall and happen to be target of the mind control during it, you will get rooted in that spot for the rest of the fight. Reloading, bladestorming again, Hand of Freedom, Hand of Protection, grip, nothing will help you. Even after your death, you will be rooted in place as a spirit. Only relog can take you out of it.
Interestingly, it happened twice to me and the first time my bladestorm continued (and killed a teammate while at it) while the other time it got cancelled.

**How to reproduce:**
Use Bladestorm when Conversion is coming. If you are the target, you will get stuck.

**How it should work:**
Obviously nothing should indefinitely root you. In addition, Bladestorm is described to be unstoppable by anything that isn't a disarm or warrior's death, so Conversion shouldn't do anything at all to bladestorming warriors.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
