### ISSUE TITLE
Throne of 4 winds heroic/normal DK army and pet issues

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#3143]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you are in blood spec and using army or raise dead they are not attacking conclave bosses and Alakir as well ( got only proof of conclave bosses  if needed can record Alakir fight later next week).
https://youtu.be/zZaXs_w_TtE recorded video
**How to reproduce:**
Go to throne of 4 winds as bdk summon army and ghoul and attack any boss they will do nothing instead of attacking.

**How it should work:**
Army and ghoul should attack same target as you attacking

**Database links:**

**Comment by Endofree1247** [comment]
I can conform its a big problem

**Comment by UltraNix** [comment]
Fixed.

**Comment by sadgh05t** [comment]
@UltraNix  thanks for the fix https://youtu.be/WwebwcssXGc

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/235769835-a5410192-9020-422a-996a-0cc7f50aa145.png)
You're welcome.

**Comment by sadgh05t** [comment]
nice it never attacks for me in hc

**Comment by UltraNix** [comment]
@sadgh05t Try again and let me know if it's fixed.

**Comment by sadgh05t** [comment]
Will try this week
