### ISSUE TITLE
Darkmoon Card: Volcano. Spellsteal & Counterspell procs the trinket also. 

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#3144]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The trinket "Darkmoon Card: Volcano" is currently able to proc from the ability spellsteal & counterspell. Meaning you can break cc with spellsteal n counterspell because of the trinket proc. 

**How to reproduce:**
In a duel. Let a mage go up against someone with buffs, and spam spellsteal on the target untill Darkmoon Card: Volcano procs. Or duel someone and use counterspell on a target --> the trinket will proc n deal damage. 

**How it should work:**
When dealing damage with spells, you have a chance to deal 899 to 1500 additional Fire damage to the target and gain 1600 Intellect for 12sec.

Spellsteal & Counterspell does not deal damage, and you shouldn't be able to proc the trinket. 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=30449¨
https://cata-twinhead.twinstar.cz/?item=62047

**Comment by SexyPancake** [comment]
Also proc on Spell ID : 61721.
https://cata-twinhead.twinstar.cz/?spell=61721

**Comment by raller1006** [comment]
Yes - it does in pvp atleast.

**Comment by UltraNix** [comment]
Fixed.
