### ISSUE TITLE
Water elemental attack order

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#3145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Water elemental doesn't attack if you send him the command to attack.

**How to reproduce:**
Try to send the pet to attack any enemy.

**How it should work:**
It should move and attack the target after you tell him to attack it

**Database links:**
https://www.wowhead.com/spell=31687/summon-water-elemental

**Comment by lalolalolz** [comment]
The truth is that the pet works as it wants and I have everything macerated with my mage with /petattack and it attacks whoever it wants or it gets stuck in place and doesn't move or attack because it doesn't reach the range

**Comment by UltraNix** [comment]
Fixed.
