### ISSUE TITLE
elemental shaman issue

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#3146]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i've noticed this problem after adding points into feedback talent , the one that branches out of elemental mastery ,every time i use lightning bolt or chain lightning , it should take down 3 seconds from the cd of elemental mastery while it's on cd , but now it doesn't show the cd at all , once i use it , it greys out then goes back to being "out of cd" display but when i click it , it says "skill on cooldown"

**How to reproduce:**
just be 80+  ele shaman , put points in the talent "elemental mastery + feedback" , just use it and cast any lightning skill , it'll remain out of cd even tho it is on cd

**How it should work:**
it's suppose to remain on cd after used , then every time you cast lightning bolt or chain lightning , it takes 3 seconds off of it as it should display .

**Database links:**
not sure what to add here.

**Comment by UltraNix** [comment]
The talent works okay itself.
Elemental Mastery should stay on infinity cooldown while the buff is active and thus the talent won't reduce Elemental Mastery cooldown.
```
reduce the **remaining** cooldown 
```

**Comment by UltraNix** [comment]
@Macilious I cannot reproduce it. When used Elemental Mastery. it's greyed out (it's okay), then use Lightning Bolt and then cd on Elemental Mastery is 3 min.

**Comment by Macilious** [comment]
@UltraNix i will try again now to see how it works , i will reply later today as i'm not on pc atm , or if you want me to reply on discord later i don't mind either , i'll test again since it's been a while

**Comment by UltraNix** [comment]
Write here the results.

**Comment by bregegg** [comment]
This is true (https://youtu.be/GQZyQTG1wJY)

It has happened ever since and has always been such a big dps loss having to spam it everytime you think its up and available. Although for me, since EM (Elemental Mastery) is off-gcd, it happens when I input the ability in between my chain lightning/lightning bolt spam. Please fix its so bad :(

**Comment by bregegg** [comment]
Oh and yeah, if you try to use it when its on cd even though it shows its available, your character tries to cast it anyway as shown in the video.

**Comment by Macilious** [comment]
@UltraNix  yes , just as @bregegg  mentioned just now , it all happens , and it seem to happen frequently in groups and dungeons rather than solo , sorry for the late reply i was extremely busy

**Comment by UltraNix** [comment]
Fixed.
