### ISSUE TITLE
Soloqueue deserter

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#3148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Leaving the soloq game after both of your teammates have left gives you deserter.

**How to reproduce:**
Play soloq and leave last in your team after your teammates have died/left.

**How it should work:**
You shouldnt get deserter if you are the only person in your team.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
