### ISSUE TITLE
A Slippery Snack not working anymore while dismounted

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3149]
**Description:**
This quest was working before, but now it's suddenly not. After clicking on several of them, only the very first one actually worked and gave me the Baby Octopus.

**How to reproduce:**
Accept the quest and click on the NPCs for the quest.

**How it should work:**
You should get the item every time

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29325
https://cata-twinhead.twinstar.cz/?item=69915

**Comment by EdyGlockenspiel** [comment]
So after some testing, it seems you *only* get them now while you are mounted. If you are dismounted you wont get any.

**Comment by PanJanuszek** [comment]
fixed 25.04.2024
