### ISSUE TITLE
Energy Infusion does not stack

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3151]
**Description:**
The buff given by Brightscale Wyrm upon death, Energy Infusion currently does not stack like it should.

**How to reproduce:**
AoE down all the Brightscale Wyrm

**How it should work:**
It should stay up to 25 times

**Database links:**
https://www.wowhead.com/spell=44406/energy-infusion#comments
https://www.wowhead.com/npc=24761/brightscale-wyrm

**Comment by Afgann** [comment]
fixed
