### ISSUE TITLE
Quest Naxxramas and the Fall of Wintergarde missing

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3154]
**Description:**
This quest locks out the whole rest of the chain, which is pretty massive. 

**How to reproduce:**
Turn in the quest High Commander Halford Wyrmbane

**How it should work:**
After turning in the quest High Commander Halford Wyrmbane you should be given Naxxramas and the Fall of Wintergarde and then Flight of the Wintergarde Defender.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12237
https://cata-twinhead.twinstar.cz/?quest=12174

**Comment by PanJanuszek** [comment]
fixed 25.03.2024
