### ISSUE TITLE
MANY sub quests are missing from Zul'Drak's Pa'Troll quest

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3155]
**Description:**
Because this quest is bugged out, this locks you out of a LOT of Argent Crusade rep quests from the zone as well as the ability to actually finish this quest.

**How to reproduce:**
Accept the quest Pa'Troll and go to each of the NPCs listed for the quest.

**How it should work:**
Once you have picked up the Pa'Troll quest, you should have access to quests for each of the NPCs of the quest, and their follow ups.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12596
https://cata-twinhead.twinstar.cz/?quest=12599
https://cata-twinhead.twinstar.cz/?quest=12606
https://cata-twinhead.twinstar.cz/?quest=12552
https://cata-twinhead.twinstar.cz/?quest=12554
https://cata-twinhead.twinstar.cz/?quest=12597

**Comment by PanJanuszek** [comment]
fixed 27.03.2024
