### ISSUE TITLE
The Argent Vanguard has many bugs (no pun intended)

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3156]
**Description:**
First off, Crusader of Virtue, the elite guards around the area are supposed to fight the spiders around the area and be hostile to them if any come close. Currently, they do not. Next, the Webbed Crusaders all along the area have a 0% chance to spawn an actual Freed Crusader. The chance for it to have nothing is supposed to be 0 unless you are *not* on the quest to free them. The chance to spawn a spider is supposed to be low, not 95~% which is what it seemed like doing the quest. The quest to free them is possible, but when you get credit it seems it is just..random. As I said no crusader spawns. They are supposed to spawn 80% of the time and buff the player that freed them and cast Holy Light on them.

**How to reproduce:**
Accept the quest to free webbed crusaders and kill the webbed crusader cocoons. Simply look at the Crusader of Virtue NPCs and watch them just standing there doing literally nothing.

**How it should work:**
The Crusader of Virtue guards should attack the spiders and be hostile to them and the ratio of spawning spiders in Webbed Crusaders should be much lower, also on successful spawn of a crusader, an actual freeed crusader should spawn, buff the player with might or kings and cast Holy Light on the player afterwards.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=31033
https://www.wowhead.com/npc=30274/freed-crusader#abilities

**Comment by PanJanuszek** [comment]
fixed 11.04.2024
