### ISSUE TITLE
Quest It's All Fun and Games nearly impossible to complete

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3158]
**Description:**
The quest It's All Fun and Games gives you a quest item and has you kill a mob super high in the air, the only reliable way to kill it is by flying up to it and using the quest item 10 times to kill it as it is too high to even hit with ranged attacks. However, currently it is only doing 5% of the bosses's max HP in damage every use and sometimes even does no damage it looks like, meanwhile the boss hits you for 5% of *your* max HP every time. This means you are guaranteed to die before the boss does.

**How to reproduce:**
Accept the quest and use quest item on boss.

**How it should work:**
The quest item should deal *exactly* 10% of the bosses's HP every use, no more no less. The boss should hit you for exactly 5% of your max HP, no more no less with it's ability having the same CD as quest item, thus it will die when you are going to reach 50% hp.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12887
https://cata-twinhead.twinstar.cz/?spell=29142

**Comment by PanJanuszek** [comment]
fixed 25.03.2024
