### ISSUE TITLE
[Hunter]/[Death Knight]/[Warlock] dampening bug (Due to server hardcore status) - pets

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3160]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pets/guards/other summoned units doesnt recieve -20% debuff for damage in 10 men heroics. Probably same applies to 25 men, but in 10 men its much more impactful, cause pets deals most of unholy dps, significant amount of warlock and hunter dps.
Thanks to this bug Unholy is the most damaging spec in the game right now.

**How to reproduce:**

**How it should work:**
Well to balance classes at it should be - they should have reduction as well, now pet classes are gaining huge advantage in heroic modes.

**Database links:**

**Comment by triceratopsrider** [comment]
![WoWScrnShot_042223_121146](https://user-images.githubusercontent.com/39683434/233797460-798db776-9b5f-4328-8df2-29bfebbc5655.jpg)
![WoWScrnShot_042223_120947](https://user-images.githubusercontent.com/39683434/233797482-a8f37152-414c-4b20-bf7a-913ed4b93f56.jpg)
I dont know what confirmation do you need. It just works that way.

**Comment by UltraNix** [comment]
Fixed.
