### ISSUE TITLE
[Raid] Unable to finish Tempest Keep

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#3161]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to finish Tempest Keep. Kael'thas Sunstrider not moving.

**How to reproduce:**
Pull the final boss, Kael'thas Sunstrider. You will battle his advisors, he will be the last one remaining and not move or talk and cannot be attacked.

**How it should work:**
Kael'thas Sunstrider must be attackable when all his advisors are dead.

**Database links:**
https://www.wowhead.com/beta/npc=19622/kaelthas-sunstrider

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
