### ISSUE TITLE
Scryers faction (synthesis of power) the quest to get currency for quarter master isn’t there.

### ISSUE THREAD

**Issue by Varrim** [gamefreedomgit/Maelstrom#3162]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest isn’t available for faction currencies 🥲
**How to reproduce:**
Vendor the sells runes for tones reputation locked??

**How it should work:**
At friendly you should be able to see quest to turn in arcane tomes for arcane runes.
**Database links:**
https://cata-twinhead.twinstar.cz/?quest=10416

**Comment by Afgann** [comment]
fixed
