### ISSUE TITLE
Blackrock Caverns permanant combat bug

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3163]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At the start of Blackrock Caverns fireballs randomly fly out of the lava pools and land on the traversible ground. Being hit by one of these fireballs will permanently put you in combat until you either die or leave the instance

**How to reproduce:**
Stand under where a fireball will be landing at the start of Blackrock Caverns.

**How it should work:**
Being hit should either not put you in combat, or put you in a state of combat that falls off after a few seconds.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
