### ISSUE TITLE
Quest: Keep Them off the Front

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#3164]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When trying to bombard the troggs and fungal terrors while doing https://cata-twinhead.twinstar.cz/?quest=26755 , the mobs evade the damage from the Earthen Catapults, making it impossible to complete the quest.

**How to reproduce:**
Mount an Earthen Catapult and try to shoot troggs and fungal terrors.

**How it should work:**
They should take damage and eventually die.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26755
https://cata-twinhead.twinstar.cz/?npc=43952
https://cata-twinhead.twinstar.cz/?npc=43954
https://cata-twinhead.twinstar.cz/?npc=43960

https://imgur.com/a/j1GxQPV

**Comment by Waroxx-QA** [comment]
Duplicate - #2785
