### ISSUE TITLE
Quest: Do me a favor?, Zone: Thousand Needles

### ISSUE THREAD

**Issue by Seradily** [gamefreedomgit/Maelstrom#3167]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

The NPC that finishes the quest is not in the location where I'm supposed to turn it in. I double checked in a youtube cideo where he's supposed to be so I relatively sure I was in the right spot. Furthermore I've finished all previous quests in the questline up to this point.

It can be reproduced by start the warboard quest that sends you to Thousand Needles. It initially sends you to southern Dustwallow marsh and from there to Thousand Needles

The quest giver should be there. This is one of those short "Go meet that guy" quests with no real objectives other than going to him and turning it in.

https://www.wowhead.com/quest=25505/do-me-a-favor#comments
https://www.youtube.com/watch?v=Q9FJ1eZLGSM

**Comment by UltraNix** [comment]
#2559
