### ISSUE TITLE
A Unified Front unable to be turned in

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3168]
**Description:**
Because you can't turn in this quest, you also can't pick up the follow up quests either.

**How to reproduce:**
Kill Varos Cloudstrider

**How it should work:**
After you kill Varos Cloudstrider, Image of Belgaristrasz should spawn at his corpse.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13126
https://cata-twinhead.twinstar.cz/?npc=28012
https://cata-twinhead.twinstar.cz/?npc=31559

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
