### ISSUE TITLE
Stealing Their Thunder last boss of Utgarde Keep does not drop his head for quest or give rep for tabard

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3169]
**Description:**
I killed the last boss in Utgarde Keep and the quest item did not drop, I also got to rep for killing him from my tabard.

**How to reproduce:**
Accept the quest and kill the last boss.

**How it should work:**
The boss should always drop his head when killed.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=31674
https://cata-twinhead.twinstar.cz/?item=33330

**Comment by PanJanuszek** [comment]
fixed 27.03.2024
