### ISSUE TITLE
Junk in My Trunk most Shiny Bauble have nothing in them

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3170]
**Description:**
I got upto Skadi, the undoable boss and only managed to pick up 3 of these things, despite them being all over the place. When I tried to pick one up, there would be nothing inside the loot window and then the item would disappear. 

**How to reproduce:**
Accept the quest and attempt to pick up any of the Shiny Bauble items on the ground.

**How it should work:**
All Shiny Bauble items on the ground should have the quest item in side them.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13131
https://cata-twinhead.twinstar.cz/?item=43239

**Comment by PanJanuszek** [comment]
fixed 30.04.2024, server restart required
