### ISSUE TITLE
"Counterattack!" quest doesn't work properly

### ISSUE THREAD

**Issue by syphonaire** [gamefreedomgit/Maelstrom#3173]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest doesn't spawn the mobs

**How to reproduce:**
Accept quest in Northern barrens

**How it should work:**
Warlord Krom'zar should appear

**Database links:**
https://www.wowhead.com/quest=4021/counterattack

**Comment by varjla** [comment]
Duplicated from https://github.com/gamefreedomgit/Maelstrom/issues/2342

**Comment by PanJanuszek** [comment]
Fixed with barrens refactor 04.03.2024
