### ISSUE TITLE
[Quest] Unable to complete [72] [We Strike!]

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#3176]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to complete [We Strike!](https://www.wowhead.com/beta/quest=11592/we-strike).

**How to reproduce:**
Talk to Longrunner Proudhoof to begin the attack. He will charge forward initially, but after defeating some mobs in the way, he will not move anymore.

**How it should work:**
He should continue moving until reaching the banner. Then the quest will complete.

**Database links:**
https://www.wowhead.com/beta/quest=11592/we-strike

**Comment by PanJanuszek** [comment]
should be fixed as on 18.03.2024
