### ISSUE TITLE
Items listed on the auction house not showing when doing a search for that item

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#3177]
I encountered this when trying to sell a few stacks of Inferno Ink.

They show up when I look under my own auctions, but they're not listed when doing a search.

I'd re-posted them a few times and sometimes they would show up, other times they wouldn't and would remain hidden.

I hadn't noticed this issue with other items (mainly listing glyphs.)

**Comment by UltraNix** [comment]
Cannot reproduce it.
