### ISSUE TITLE
[Blackwing Descent] Nefarian bug list

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3179]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) Dominion. Mind control problem is not Nefarian specific bug, it also happens in throne of the tides Mindbender Ghu'rsha boss, but of course, its has a very drastic impact on heroic difficulties.
A - If Alliance player is being mced by the boss, he loses ability to interract with every other player of opposite faction, until horde players are also being targeted by mindcontrol. Sometimes it happens randomly to a single players with the same faction. 2 horde players in our raids were unfriendly (red healthbar) to each other.
B - Dominion can target tanks, ones that tanking Animated Bone Warriors and the one with the Nefarian himself, which should not happen and can lead to instant wipes.
![image](https://user-images.githubusercontent.com/39683434/233923154-ea5b4ae8-94c7-4c7d-9dc3-39a580bb2a81.png)
![image](https://user-images.githubusercontent.com/39683434/233923234-33bb6ff9-4e6f-454c-903f-57a6e7989278.png)
![image](https://user-images.githubusercontent.com/39683434/233923297-16a74f7e-0c52-4095-84b6-744ca2bcbcf9.png)
![image](https://user-images.githubusercontent.com/39683434/233923356-ca9770e3-3bde-4d7c-8c70-f480f47f92ad.png)

2) Shadowflame Breath. It is part of the previous bug, but can happen on its own. If boss agro is lost, due to Dominion being cast to tank or threat issues, a few seconds before boss breath, he will breath in direction of the raid, killing everyone.

3) Lava. 
A - Lava should raise at much faster pace. Right now it takes about 10 seconds to raise up, while on official server it takes at least half as much.
B - Lava ticks should happen when players already drowning in it. Right now floor is still solid and you already gaining stacks.
C - Lava on Whitemane sometimes begin to tick for 2 stacks per second instead of 1. This more than doubles damage from it. Probably happens after wipe.

4) Shadowblaze Spark. Fire speed is random, and sometimes its way too fast compared to retail, making tank run from bone warriors on incredible speed and covering all the platform in fire and its still reaching tank sometimes.

5) Pets bugs out and die on lava phase. Pets or other summoned units cannot stand on the columns and cannot find path to it when lava spawns, often being drown by geometry. On retail hunters, warlock and deathknights are killing adds with their pets on the platforms. 

**How to reproduce:**

**How it should work:**
https://youtu.be/3MQyH78aqT4?t=316
https://www.youtube.com/watch?v=U1z8IzaK3Yc

**Database links:**
https://www.wowhead.com/spell=79318/dominion?dd=6
https://www.wowhead.com/spell=77826/shadowflame-breath
https://www.wowhead.com/spell=81031/shadowblaze-spark?dd=6

**Comment by UltraNix** [comment]
Fixed.
