### ISSUE TITLE
[Throne of the Four Winds] Rohash hitbox

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3181]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Rohash atack range is way less than it should be, can be an rng issue on hc difficulty if tornados are under the boss.

**How to reproduce:**
Be a melee player on rohash platform

**How it should work:**

https://youtu.be/U4Uff4PS0H4?t=94
Look at the distance this rogue can attack Rohash in and compare it to the current attack distance.

**Database links:**

**Comment by triceratopsrider** [comment]
It is not boss attack range, it is hitbox.

**Comment by Waroxx-QA** [comment]
added to #3124
