### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by xXbakalaXx** [gamefreedomgit/Maelstrom#3185]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Alliance quest Last ditch effort is bugged. When the quest is accepted you should just hop onto the flying mount of an npc and continue the quest. But it’s not working. Please fix.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#2167
