### ISSUE TITLE
Quest bug no. 64829

### ISSUE THREAD

**Issue by xXbakalaXx** [gamefreedomgit/Maelstrom#3187]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Alliance quest King of the foulweald. You need to place a flag atop of a totem mound and defend it from the enemy. It’s bugged and the enemy won’t appear. Please fix.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#1743
