### ISSUE TITLE
Loremaster - missing quests - not working ones.

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#3188]
**Description:** Quest  https://cata-twinhead.twinstar.cz/?quest=26745
Missing quest from above at 39/50 raptor doesn't give the quest from above.

Zone : https://cata-twinhead.twinstar.cz/?quests=0.51
Quest : https://cata-twinhead.twinstar.cz/?quest=28056
Issue : Cannot click on altar to start the quest and kill Obsidion. -- **works**

Zone : https://cata-twinhead.twinstar.cz/?achievement=4900
Quest 1 : https://cata-twinhead.twinstar.cz/?quest=27834
Issue : Missing npc bar to control spells in order to do the quest.
Quest 2 : https://cata-twinhead.twinstar.cz/?issue=5627
Issue : Missing npc  bar to controll spells in order to do the quest.
Quest 3 : https://cata-twinhead.twinstar.cz/?quest=27828
Issue : Missing npc bar to controll spells in order to do the quest.

Zone : https://cata-twinhead.twinstar.cz/?achievement=4897
Missing quest : https://cata-twinhead.twinstar.cz/?quest=26525

Zone : https://cata-twinhead.twinstar.cz/?achievement=1678
Area : https://cata-twinhead.twinstar.cz/?achievement=4931
Issue : after completing quest - https://cata-twinhead.twinstar.cz/?quest=28121 You do not get continuation of quest line with next quest - https://cata-twinhead.twinstar.cz/?quest=28119

Zone : https://cata-twinhead.twinstar.cz/?achievement=4980
Issue with quest - https://cata-twinhead.twinstar.cz/?quest=25642  Npc's don;t drop the quest item https://cata-twinhead.twinstar.cz/?item=55174

Quest no.2 - https://cata-twinhead.twinstar.cz/?quest=25649  Npc's is getting killed by other npc's it isnt supposed to be killed.
Quest no,3 - https://cata-twinhead.twinstar.cz/?quest=25891 
Issue : when talk with npc you are stuck on dialogue to continue.

Zone : https://cata-twinhead.twinstar.cz/?achievement=1191
Quest not working : https://cata-twinhead.twinstar.cz/?quest=10922
Issue : Npc's walk to the dig site but finish before quest is completed.
Quest missing : https://cata-twinhead.twinstar.cz/?quest=10908
quest missing : https://cata-twinhead.twinstar.cz/?quest=10847

Quest not working : https://cata-twinhead.twinstar.cz/?quest=10231
Issue : Npc's attack you but you can't attack them.

Quest : https://cata-twinhead.twinstar.cz/?quest=10446 
Issue : when use the bomb it doesnt work or count as completed.

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=10840

quest - missing - https://cata-twinhead.twinstar.cz/?quest=10881

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=10873

Zone : https://cata-twinhead.twinstar.cz/?achievement=1195

Quest - Not working - https://cata-twinhead.twinstar.cz/?quest=10612
Issue - Fel reaver doesn't deal damage to infernals.

Quest - Not working - https://cata-twinhead.twinstar.cz/?quest=10645
Issue : Npc teron is supposed to fight doesnt spawn.

Quest : https://cata-twinhead.twinstar.cz/?quest=10588
Issue : entire quest line needs to be reworked.

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=10588

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=10458

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=10622

Zone : https://cata-twinhead.twinstar.cz/?achievement=1193
Quest - https://cata-twinhead.twinstar.cz/?quest=10910
Issue : Npc cannot be interracted to finish quest or get new one.

Quest : https://cata-twinhead.twinstar.cz/?quest=10911
Issue - not working cannot use canons.

Quest : https://cata-twinhead.twinstar.cz/?quest=11058
Issue not working cannot interract with orbs.

Zone - https://cata-twinhead.twinstar.cz/?achievement=1194

Quest - Not working - Missing : https://cata-twinhead.twinstar.cz/?quest=10971

Quest : https://cata-twinhead.twinstar.cz/?quest=10855
Issue : Cannot use condensed gas on the fel reaver- unusable.

Quest : https://cata-twinhead.twinstar.cz/?quest=10269
Issue : not working

Quest : https://cata-twinhead.twinstar.cz/?quest=10857
 Issue - Not working - Can't use engineers to destroy the teleporters.

Quest : https://cata-twinhead.twinstar.cz/?quest=10237
Issue : Missing.

Quest : https://cata-twinhead.twinstar.cz/?quest=10293
Issue : Missing.

Zone : https://cata-twinhead.twinstar.cz/?achievement=33
Quest not working : https://cata-twinhead.twinstar.cz/?quest=11576
Issue : Item cannot be used at appointed location, entire quest line is broken.

Quest : https://cata-twinhead.twinstar.cz/?quest=11587
Issue : Missing

Zone : https://cata-twinhead.twinstar.cz/?achievement=35
Quest : https://cata-twinhead.twinstar.cz/?issue=5947
issue : not working, entire quest line regarding mystery of the infinite doesnt work.

Zone : https://cata-twinhead.twinstar.cz/?achievement=37
Quest - missing - https://cata-twinhead.twinstar.cz/?quest=11989

quest - missing - https://cata-twinhead.twinstar.cz/?quest=11984

Quest - Missing - https://cata-twinhead.twinstar.cz/?quest=12310

quest - missing - https://cata-twinhead.twinstar.cz/?quest=12328

Quest - missing - https://cata-twinhead.twinstar.cz/?quest=11982

Zone : https://cata-twinhead.twinstar.cz/?achievement=34

quest - https://cata-twinhead.twinstar.cz/?quest=11485
Issue : not working

Quest : https://cata-twinhead.twinstar.cz/?quest=11251
Issue : Npc missing to turn in the quest.

Quest : https://cata-twinhead.twinstar.cz/?quest=11390
Issue : cannot place the quest item into drop zone.

Quest missing : https://cata-twinhead.twinstar.cz/?quest=11313

Zone : https://cata-twinhead.twinstar.cz/?achievement=36

Questline missing : https://cata-twinhead.twinstar.cz/?achievement=1596 Zul drak quests entire quest line doesnt work.

Quests dont work  aka entire quest line- https://cata-twinhead.twinstar.cz/?quest=12501

Zone - https://cata-twinhead.twinstar.cz/?achievement=39

Quest doesnt work : https://cata-twinhead.twinstar.cz/?quest=12538
Issue : Oracles npc's which are required for quest cannot be attacked.

Quest : https://cata-twinhead.twinstar.cz/?quest=12576
issue : npc's cannot be attacked.

Zone : https://cata-twinhead.twinstar.cz/?achievement=38
quest : https://cata-twinhead.twinstar.cz/?quest=13010 
Issue : after mounting giant  he doesnt lead u to the location of the quest and dialogue between npc's.

Quest : https://wotlk-twinhead.twinstar.cz/?quest=13057
issue : cannot turn in the quest - auto complete

Quest : https://cata-twinhead.twinstar.cz/?quest=12855
Issue : not working, wolf doesnt lead u to the location of the npc to kill which drops the item https://cata-twinhead.twinstar.cz/?item=40971

Zone : https://cata-twinhead.twinstar.cz/?achievement=40

Quest : https://cata-twinhead.twinstar.cz/?quest=13395
Issue : Doesn't work , after killing npcs, when use spell to rise undead, they rise but it doesnt count for the quest.

Quest : https://cata-twinhead.twinstar.cz/?quest=12898
Issue : after completing this quest you do not get continuation to the quest line quests missing.

Quest : https://cata-twinhead.twinstar.cz/?quest=13059
issue : after droping sword npc comes to you but he cannot be attacked-not working.

Quest : https://cata-twinhead.twinstar.cz/?quest=13043
issue : npc for the quest does no damage.

Quest : https://cata-twinhead.twinstar.cz/?quest=13169
Issue : Plaguehounds cannot be fed when using spell.

Quest : https://cata-twinhead.twinstar.cz/?quest=28062
Issue : ghouls cannot be assasinated does little damage, but it is supposed to instantly kill after debuff.

Quest : https://cata-twinhead.twinstar.cz/?quest=13143
Issue : Lithe stalker get's charmed but doesnt follow.

Quest : https://cata-twinhead.twinstar.cz/?quest=13147
Issue : Lithe stalker spell to throw a rock on npc works but npc's doesnt get aggravated or mad to count as fight started for quest.

Quest : https://cata-twinhead.twinstar.cz/?quest=13146
Issue : not working, bombs get dragged and kills npc but doesnt count for quest, and also they are supposed to be friendly with lithe stalker.

**Comment by MrTide** [comment]
Can confirm i pretty much helped the player go through all of these
Player ingame name: Character
thank you kindly for your report

**Comment by Alandiel** [comment]
https://cata-twinhead.twinstar.cz/?quest=28056, https://cata-twinhead.twinstar.cz/?quest=27834, https://cata-twinhead.twinstar.cz/?issue=5627, https://cata-twinhead.twinstar.cz/?quest=27828. These quests can be completed.

**Comment by MrTide** [comment]
> https://cata-twinhead.twinstar.cz/?quest=28056, https://cata-twinhead.twinstar.cz/?quest=27834, https://cata-twinhead.twinstar.cz/?issue=5627, https://cata-twinhead.twinstar.cz/?quest=27828. These quests can be completed.

Some of these quests work first a few times but rest of the players can't do it

**Comment by PanJanuszek** [comment]
Ok I will post my comments here:
QUEST 26745: You need to bring raptor here (picture) to get this q available.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/ad8a97d5-bdb0-4c9a-925f-881e80f869a4)
