### ISSUE TITLE
magmaw hc bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3189]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** sometimes when we wipe on magmaw hc adds dont dissapear

**How to reproduce:**  
![image](https://user-images.githubusercontent.com/129559513/234080822-279a9072-6d88-4cb8-a3ef-acc30e803f71.png)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
