### ISSUE TITLE
macroes not saving deleting after logging out

### ISSUE THREAD

**Issue by DoctorPiton** [gamefreedomgit/Maelstrom#3190]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by allshampain** [comment]
if you delete and redownload and it fixed it for me

**Comment by UltraNix** [comment]
Fixed.
