### ISSUE TITLE
maloriak suddenly dissapear

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3192]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** he suddenly dissapears during red phase

**How to reproduce:**  
![image](https://user-images.githubusercontent.com/129559513/234102555-64e688af-8fa7-4212-b871-0ac582e84cc3.png)

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
I've already reported this, boss is going undermap due to that semicircle texture on the ground, you can avoid it by keeping the boss inside it / close to the cauldron.
It will get fixed asap ! 😄
