### ISSUE TITLE
25 man loot is wrong AGAIN

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#3193]
Description:

25 Man loot is wrong again, its supposed to drop 6 loot pieces, NOT 5. It was working fine, you changed it to 5(wrong report), you fixed it, and now is wrong again.

10 man loot is working fine. 2 items +token

How to reproduce:

Clear 25 man boss nm or hc

How it should work:

Dropping 6 items on nontoken bosses,
Dropping 6 items + 3 tokens on tokenbosses.

Database links:

Video proofs, courtesy of owners and u/jlldarocha in his report on issue https://github.com/gamefreedomgit/Maelstrom/issues/2664

https://www.youtube.com/watch?v=rzid0DGMLU4&t=238s Baradin Hold, Argaloth 25

https://www.youtube.com/watch?v=S8A8tamdI2s&t=470s BWD , Chimaeron 25 (hc)

https://www.youtube.com/watch?v=NJCfe6YJ6Rc&t=572s , TOT4W, Al'Akir 25 (hc) [token boss]

**Comment by Rorhn** [comment]
I will not stand for this. 
Justice for Jildarocha!

**Comment by staR1336** [comment]
https://cdn.discordapp.com/attachments/1100335726123565136/1100337686428000257/2023-04-25_09-19-20.mp4

Found a first video proof, still searching for rest

Let me know if you need more or ur alrdy on it!

**Comment by staR1336** [comment]
Addendum: 

ToT4W  seems odd too: https://www.twitch.tv/videos/1801387095?t=04h47m48s Vod proof

Last boss dropped 2 items, 4 tokens and 3 essences of forlorn

Not only its weird as is, but the 3 essences of forlorn were in a stack and upon looting they would split in the bags of the master looter and lose the ability to be traded, they had to make a ticket.

**Comment by UltraNix** [comment]
Fixed.
