### ISSUE TITLE
Not recieving valor points after compeleting Rhc

### ISSUE THREAD

**Issue by allshampain** [gamefreedomgit/Maelstrom#3194]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
played 4 Rhc To cap for the week never recieved points stuck at 980 for the week

**How to reproduce:**
i can just play another one and not get them

**How it should work:**
i should get my points

**Database links:**
Talked to mod Crywolf about the issue said to report it on here

**Comment by UltraNix** [comment]
#4463
