### ISSUE TITLE
[Quest] Unholy Cow

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#3195]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you try to complete you just cant and die

**How to reproduce:**
Try to complete the quest

**How it should work:**
https://www.youtube.com/watch?v=pSaLJt6aiik&ab_channel=GitGudGuides

**Database links:**
https://www.wowhead.com/quest=27060/unholy-cow

**Comment by MadeinNoxus** [comment]
Same as #2988

**Comment by Sketish** [comment]
Mobs are not despawning after players run away from them/drop combat.

**Comment by EdyGlockenspiel** [comment]
"Stay on your flying mount, and stay just high enough above ground so that they can't attack you. They'll deaggro and all three will shortly despawn and give you quest credit." 2nd top comment on wowhead for the quest.

**Comment by UltraNix** [comment]
Fixed.
