### ISSUE TITLE
Low level npc threat level

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#3198]
**Description:** Area of visibility by low level npc's is on the same level like you are in a raid or dungeon, i think that is even bigger because they notice you from large area without even passing next to them, that is also considered as npc lvl 20 attacks lvl 85 from large distance, and it shouldn't be possible.

**Comment by UltraNix** [comment]
@Wick3dmind Please - give us exact examples of such mobs/NPCs.

**Comment by UltraNix** [comment]
No further info - closing.
