### ISSUE TITLE
Quest "To New Thalanaar"

### ISSUE THREAD

**Issue by Toeclipper** [gamefreedomgit/Maelstrom#3199]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**  Flight takes you to Ruins of Feathermoon instead of New Thalanaar.

**How to reproduce:** Take the Quest

**How it should work:** Should take you from Shadebough to New Thalanaar

**Database links:**

**Comment by Sketish** [comment]
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2932
