### ISSUE TITLE
WoW mision "¿Hace un Lucio?"

### ISSUE THREAD

**Issue by Terran629** [gamefreedomgit/Maelstrom#3201]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)  https://www.wowhead.com/es/quest=29320/hace-un-lucio#
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
el [gusano de cadáver](https://www.wowhead.com/es/item=69907/gusano-de-cad%C3%A1ver)  no se pueder recoger y entoces no se puede completar la mision

**How to reproduce:**

**How it should work:**

**Database links:**
[gusano de cadáver](https://www.wowhead.com/es/item=69907/gusano-de-cad%C3%A1ver)
https://www.wowhead.com/es/quest=29320/hace-un-lucio#

**Comment by Waroxx-QA** [comment]
Please make your future reports in English, devs don't have time to translate.
