### ISSUE TITLE
Disarm or knock stun mobs perma debuff

### ISSUE THREAD

**Issue by BarukTTV** [gamefreedomgit/Maelstrom#3203]
**Description:**
When you fight mobs that knock you or disarm has no dr and it perma leaves you with that disarm debuff or on the floor stunned

**How to reproduce:**
Fight any disarm or knock stun mob, disarm mob its lashtail raptors in stranglethorn valley or Highland Elk in Twilight Highlands

**How it should work:**
Not perma leaving you with the debuff, disarmed or stunned. Its like the mob can spam that ability

**Database links:**

**Comment by EdyGlockenspiel** [comment]
Can confirm. If you have 2 Highland Elk on you at once it is literally impossible to get out of their stun until you fucking die.

**Comment by Afgann** [comment]
fixed
