### ISSUE TITLE
[Bastion of Twilight] Sinestra's orbs

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3204]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Shadow orbs can randomly agrro to a player that is nearby (Was a healer in our case) and kill him instead of target it was spawned upon.
https://www.twitch.tv/videos/1803322715?t=1h15m19s

**How to reproduce:**
Dont know exactly. Is probably has something to do with the threat generated by others members of the group while orbs are spawning.

**How it should work:**
Orbs should follow their targets only, of course.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
