### ISSUE TITLE
Elizabeth Nesworth does not act as a vendor or sell any items

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3206]
**How to reproduce:**
Interact with the NPC as an alliance player.

**How it should work:**
She should act as a vendor with stuff to sell like any other Fishing vendor.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=48552
https://www.wowhead.com/npc=48552/elizabeth-nesworth#sells

**Comment by Afgann** [comment]
fixed
