### ISSUE TITLE
NPC Savanne is missing

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3207]
**How to reproduce:**
Go to 45.2 41.4 Feralas as an alliance player

**How it should work:**
The NPC should be standing next to Brannock, the Fishing Training and act as a Fishing Supplies vendor.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=7945#map
https://www.wowhead.com/npc=7945/savanne#sells
https://www.wowhead.com/npc=7946/brannock

**Comment by Afgann** [comment]
fixed
