### ISSUE TITLE
Rogue stealthed on mount

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3211]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://i.imgur.com/fNdiTEx.png
It is possible to use the battleground system to get stealthed on a mount.

**How to reproduce:**
Enter a battleground while mounted, use vanish right as the battleground ends and leave before the vanish buff falls off.

**How it should work:**
Vanish should be removed when the battleground ends

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
