### ISSUE TITLE
Sinestra orb targetting

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3212]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sinestra's orbs are targetting the tanks (Including the tank currently tanking Sinestra herself!), this should not happen.

**How to reproduce:**
Be a tank on Sinestra

**How it should work:**
Orbs should never target the tanks while they are in their respective tank stance and spec.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
