### ISSUE TITLE
[Death Knight] Ebon Gargoyle

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3213]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Gargoyle, probably as other colddown guardian pets that snapshot stats, currently fully recieve bloodlust/heroism buff effects.

**How to reproduce:**
Summon gargoyle and then use heroism.

**How it should work:**
Gargoyle shouldnt receive buff itself, cause dk that summoned pet under heroism effect already transfer haste stats to it. Probably same applies to other summoned units, would appreciate more proofs in the comments.

https://youtu.be/OVrrOdMjPeg?t=47

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
