### ISSUE TITLE
Intercept does not work in the fury specialisation

### ISSUE THREAD

**Issue by Furytyan** [gamefreedomgit/Maelstrom#3214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Intercept does not work in the fury specialisation
https://youtu.be/j3-hQxl35l0
**How to reproduce:**

**How it should work:**
Like a charge =)

**Database links:**

**Comment by xmrshoot** [comment]
same with bear charge

**Comment by Furytyan** [comment]
same with [Intervene](https://www.wowhead.com/spell=147833/intervene)
xd

**Comment by Alandiel** [comment]
Fixed.
