### ISSUE TITLE
INTERVENE BUGGED! [HOPE THIS WILL GET FIXED ASAP] 

### ISSUE THREAD

**Issue by Iemrohit** [gamefreedomgit/Maelstrom#3215]
**Description:**
Hello Game Master!

Hello Warrior, can you please fix the warrior spell called "intervene"? It's just not working as it should. Literally, I played some arenas and observed that it was not working as it should, and I tested it on as well. This just needs to be fixed asap because it's a main spell for warriors in arenas; without it, they just can't play until it has been fixed.

**How it should work:**  So look how it works i can't clip the video footage for some reason but i will try to explain "Run at high speed towards a party or raid member, intercepting the next ?s58377[2 melee or ranged attacks][melee or ranged attack] made against them as well as reducing their total threat by 10%". 

**Here it won't work:** Now here in this server you don't "run towards your party member and  he gets the buff though you just don't run towards them.

**Database links:** https://cata-twinhead.twinstar.cz/?spell=3411

Thanking you!

**Comment by Alandiel** [comment]
Duplicate.
