### ISSUE TITLE
Enhacement shaman Feral spirit bugs (perma auto cast, Don't heal themselves on auto)

### ISSUE THREAD

**Issue by Bruthay** [gamefreedomgit/Maelstrom#3217]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Enhance shaman ability "Feral Spirit" 
1. auto casted abilities are always set to auto-cast even if turned off during the summon, on next resummon auto cast will be active again.  
2. The wolves are supposed to life steal/heal themselves on auto, they currently do not. 
 

**How to reproduce:**
summon wolves, turn off auto cast on bash and spirit wolf leap, summon again, bash and spirit wolf leap will be back on auto cast. 
send wolves to attack any target, no life steal/healing

**How it should work:**
1. should be able to right click on auto-casted abilities in the pet menu when they're summoned to have it turned off and saved for future summons.
2. Wolves should lifesteal/heal on hit. 

**Database links:**
https://www.youtube.com/watch?v=IRYBZ9kV4Ko
(4:36 in the video wolf auto attacked for 822 and it healed for 1204, 862 auto heals wolf for 1285 and shaman 1478 -spark of life difference.) Wolves summoned in video, bash was not on auto cast.

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/236432365-0cc84482-3038-49b4-8fd1-5d4c7f49c70c.png)
Spirit Hunt works okay.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Bruthay** [comment]
Any chance to reopen this? both of the issues I'm reporting on weren't addressed. The wolves are supposed to heal the caster AND themselves, they currently do not heal themselves
