### ISSUE TITLE
[Items/NPC] Profession NPCs are not selling Bloodied gear

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#3218]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Profession NPCs are supposed to sell Bloodied gear recipes 4.0.3 content

**How to reproduce:**
Check the profession vendors

**How it should work:**
NPCs should sell Bloodied gear recipes

**Database links:**
https://cata-twinhead.twinstar.cz/?item=56546
https://cata-twinhead.twinstar.cz/?item=56534
https://cata-twinhead.twinstar.cz/?item=56526
https://cata-twinhead.twinstar.cz/?item=56559
https://cata-twinhead.twinstar.cz/?item=56535
https://cata-twinhead.twinstar.cz/?item=56547
https://cata-twinhead.twinstar.cz/?item=56558
https://cata-twinhead.twinstar.cz/?item=56527
https://cata-twinhead.twinstar.cz/?item=56542
https://cata-twinhead.twinstar.cz/?item=56530
https://cata-twinhead.twinstar.cz/?item=56522
https://cata-twinhead.twinstar.cz/?item=56554
https://cata-twinhead.twinstar.cz/?item=56523
https://cata-twinhead.twinstar.cz/?item=56543
https://cata-twinhead.twinstar.cz/?item=56555
https://cata-twinhead.twinstar.cz/?item=56531
https://cata-twinhead.twinstar.cz/?item=56545
https://cata-twinhead.twinstar.cz/?item=56544
https://cata-twinhead.twinstar.cz/?item=55073
https://cata-twinhead.twinstar.cz/?item=55074
https://cata-twinhead.twinstar.cz/?item=55071
https://cata-twinhead.twinstar.cz/?item=55078
https://cata-twinhead.twinstar.cz/?item=55072
https://cata-twinhead.twinstar.cz/?item=55077
https://cata-twinhead.twinstar.cz/?item=55076
https://cata-twinhead.twinstar.cz/?item=55075
https://cata-twinhead.twinstar.cz/?item=56533
https://cata-twinhead.twinstar.cz/?item=56532
https://cata-twinhead.twinstar.cz/?item=56524
https://cata-twinhead.twinstar.cz/?item=56556
https://cata-twinhead.twinstar.cz/?item=56525
https://cata-twinhead.twinstar.cz/?item=56557
https://cata-twinhead.twinstar.cz/?item=56521
https://cata-twinhead.twinstar.cz/?item=56529
https://cata-twinhead.twinstar.cz/?item=56520
https://cata-twinhead.twinstar.cz/?item=56541
https://cata-twinhead.twinstar.cz/?item=56528
https://cata-twinhead.twinstar.cz/?item=56553
https://cata-twinhead.twinstar.cz/?item=56552
https://cata-twinhead.twinstar.cz/?item=56540

**Comment by Alandiel** [comment]
Just buy Vicious recipes, after crafting them you will get Bloodied.
