### ISSUE TITLE
NPC BARÓN TAJADA CORONA DE HIELO

### ISSUE THREAD

**Issue by Dragonleon49** [gamefreedomgit/Maelstrom#3220]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the npc baron does not give the quest chain to make reputation with the knights of the ebony sword in icecrown, to obtain the tabard and its faction sales items,

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/es/quest=12891/tengo-una-idea-pero-primero

**Comment by PanJanuszek** [comment]
works as should 21.03.2024
