### ISSUE TITLE
Mage fire talent - "Improved Hot streak"

### ISSUE THREAD

**Issue by komugribov** [gamefreedomgit/Maelstrom#3221]
****Description**: I noticed the problem with talent that i wrote below. It should work in one way - you spell 2 citical hits alternately and then you can use pyroblast instantly. But it doesnt work, it works with random 1 critical hit only like just a hot streak talent. 

**How it should work:**  It should work in one way - you spell 2 citical hits alternately and then you can use pyroblast instantly in 15 sec.

**Database links:** [//]: # (https://cata.cavernoftime.com/spell=44448)

**Comment by Dechuka** [comment]
Not actually a bug, base Hot Streak has a chance to proc from one critical strike.
Same report was made before, and here it is
https://github.com/gamefreedomgit/Maelstrom/issues/2629

**Comment by triceratopsrider** [comment]
How did you tested improved hot streak without learning basic hot streak?

**Comment by komugribov** [comment]
> Not actually a bug, base Hot Streak has a chance to proc from one critical strike. Same report was made before, and here it is #2629

Hm. Am i right if these two talents work at the same time? Procs will happen in 1 random crit and 2 alternately crits?

**Comment by staR1336** [comment]
No bug. The improved hot streak helps you to get a proc in a more "stable" way, hitting two consecutive crits, but you still have the chance rng to get a hot streak proc normally!
