### ISSUE TITLE
[Quest] Hero's Call: Redridge Mountains! - No Item Rewarded

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#3222]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Completing [Hero's Call: Redridge Mountains!](https://www.wowhead.com/quest=28563/heros-call-redridge-mountains) should reward you an item, but currently it doesn't.

**How to reproduce:**
Take the quest from the Hero's Call Board, then complete the quest. You will get money, exp, and rep but no item.

**How it should work:**
Upon completing the quest, you are supposed to be able to choose one of 5 items as an additional reward.

**Database links:**
https://www.wowhead.com/quest=28563/heros-call-redridge-mountains

**Comment by Afgann** [comment]
fixed
