### ISSUE TITLE
door bug bot

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3223]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** door at valiona bugged ,w e must always relog so we can enter

**How to reproduce:** 
![image](https://user-images.githubusercontent.com/129559513/234902190-4eb0141e-ea7a-4f53-abc2-38200d1ae8d0.png)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
