### ISSUE TITLE
Bug report: Warrior Charge Ability being jumped

### ISSUE THREAD

**Issue by RealCrispyCalamari** [gamefreedomgit/Maelstrom#3224]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Charging on a moving jumping target will stun them but will not freeze them in place. This leads to the so-called charge jumping, where the non-warrior player gains distance on the warrior due to their jump inertia since the charge ability won't cause the warrior to follow them to where they would land, but rather to where they were where when the charge was cast, which is mid-air.
**How to reproduce:**

**How it should work:**

The charge ability should stun and freeze the target in place, even if they are jumping.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
