### ISSUE TITLE
Bug report: CC while charging with warrior

### ISSUE THREAD

**Issue by RealCrispyCalamari** [gamefreedomgit/Maelstrom#3225]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When the warrior casts charge on a target and a third party casts e.g. fear on the warrior, the charge movement is cancelled and the warrior starts running in fear. This results in a waste of a charge since the warrior cannot reach the target. The stun part of the charge works fine.

**How to reproduce:**

**How it should work:**

The warrior should reach the target and then the effect of the cc (fear) should take place. For example: 

I charge a mage. As I cast charge, a warlock near me fears me. I stun and reach the mage. The moment I reach the mage I get feared for the remaining duration of the fear, timing starts from the point of cast.

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
