### ISSUE TITLE
Flying issue - Character is mounted and fly to random location every time after login

### ISSUE THREAD

**Issue by ReiDyxSrb** [gamefreedomgit/Maelstrom#3226]
Flying issue - Character is mounted and fly to random location every time after login

Priority: High

Time: 7:30
Character name: Reidyxsrb
Raid: Old Hillsbrad

Steps to reproduce: 
1. Enter the Old hillsbrad
2. Reach the Brazen
3. Leave the raid
4. Wait 20 before get kicked out
5. Talk to Brazen

Actual Result:
Character get kicked out with mount and fly to random location
Note: Can be reproduced every time after game restart

Expected result:
After the time is up, character is teleported out to the cemetery

**Comment by UltraNix** [comment]
Tested and works okay.
