### ISSUE TITLE
anshal bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3227]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** ravenous creeps are going under map on hc

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
added to #3124
