### ISSUE TITLE
[QUEST] (The Cape of Stranglethorn) Bloodsail's End

### ISSUE THREAD

**Issue by Tiebob99** [gamefreedomgit/Maelstrom#3228]
**Description:**
Talking to the NPC Kebok next to the horde flight master after accepting the quest and asking for a wind rider does not work. Instead of mounting a wind rider my character just jumped to the spot you usually mount up for the quest. This makes the quest incompletable without a flying mount.

**How to reproduce:**
Start the quest and talk to Kebok to ask for a wind rider.

**How it should work:**
You should be able to talk to Kebok to obtain a flying mount so you can fly to the ship that Fleet Master Firallon is on.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26703

**Comment by bogdanian** [comment]
Can confirm this is an issue

**Comment by mserkanoz** [comment]
I can confirm it, still bugged. I tried with Alliance toon.

**Comment by PanJanuszek** [comment]
cannot reproduce anymore
