### ISSUE TITLE
Wanted: Knucklerot and Luzran

### ISSUE THREAD

**Issue by FoxxoSasha** [gamefreedomgit/Maelstrom#3229]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
unable to see Knucklerot roaming around on the map. 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/15ab8841-5182-4e4a-bba8-ab15e053ee40)
