### ISSUE TITLE
Shaman (Enhancement)- Feral Spirit not benefitting from Healing Steam Totem

### ISSUE THREAD

**Issue by Bruthay** [gamefreedomgit/Maelstrom#3230]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Feral Spirit Wolves not healing or getting the glyphed resistances from Healing Stream Totem

**How to reproduce:**
Summon wolves have them take any damage, set down a healing stream totem, their health will not go up. 
Summon wolves, have a Nature, Fire, or Frost caster with 0 Spell penetration cast the respective spells onto the wolves with and without Healing stream totem down (glyphed). 

**How it should work:**
Healing stream totem should be healing the wolves, it currently does not. 
195 resistance from glyphed healing stream totem should be reducing damage the wolves take from the respective magic schools, it currently does not. 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
