### ISSUE TITLE
[CORE] Proc trinkets have wrong ICD

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#3231]
**Description:**
Proc trinket's cooldown starts counting from the beginning of the proc. for example my heart of rage has an ICD of 90s, but it's procs before the end of that ICD.

**How to reproduce:**
Get [Heart Of Rage](https://cata-twinhead.twinstar.cz/?item=65072), Get it to proc, after the end of the first proc start counting 90s, the trinket will proc 99.9% between 70-89s

**How it should work:**
It should start counting from the end of the proc. **Proc time ∩ ICD**

**Database links:**
[https://cata-twinhead.twinstar.cz/?item=65072](https://cata-twinhead.twinstar.cz/?item=65072)

**Comment by jlldarocha** [comment]
This is not how trinket ICDs work. Using heart of rage as an example, here is one of wowhead comments on it:
![image](https://user-images.githubusercontent.com/127895081/235041610-aaf8b2c6-5064-474e-8023-ac871855e14a.png)

ICD starts as soon as it procs, the same that behaviour on use trinket have.

**Comment by jlldarocha** [comment]
From wowpedia:

![image](https://user-images.githubusercontent.com/127895081/235046969-e6108d47-9431-4b42-869b-4aeef581e642.png)

**Comment by UltraNix** [comment]
Internal Proc Cooldowns (as the name says itself) count from proc to proc.
