### ISSUE TITLE
[Throne of the Tides] Lady Naz'jar Encounter Adds Spawn

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3234]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The three adds that Lady Naz'jar spawns just instantly spawn on their position.

**How to reproduce:**
Engage Lady Naz'jar in Throne of the Tides.

**How it should work:**
The Adds should jump onto their position instead of instantly spawning and then wait there for about a second before engaging in the fight (makes it easier to pick them up as a Tank). See Reference Video for this.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=WhUyJPMGBIM (8:22 - 8:26)

**Comment by staR1336** [comment]
Confirming and including this in more complete description of encounter. closing this for clutter
