### ISSUE TITLE
[Shadowfang Keep] Baron Silverlaine - Worgen Spirits after Boss dies

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3237]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Worgen Spirits that Baron Silverlaine spawns throughout the fight don't disappear if he dies.

**How to reproduce:**
Engage Baron Silverlaine in Shadowfang keep, wait until he spawns Worgen Spirits and kill him.

**How it should work:**
The Worgen Spirits should disappear after the Boss dies.

**Database links:**

**Comment by Afgann** [comment]
fixed
