### ISSUE TITLE
[Shadowfang Keep] Baron Ashbury - Asphyxiate Health calculation, Wracking Pain and Last Phase

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3238]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Baron Ashbury's Asphyxiate (https://cata-twinhead.twinstar.cz/?spell=93423) Health Values Calculation is off. It leaves players at low health but not at exactly 1 Health (could also be 1% instead of 1 Health, not quite sure).

Wracking Pain (https://cata-twinhead.twinstar.cz/?spell=93720) isn't stacking up during the encounter.

Also Baron Ashbury doesn't enter his last Phase where he enters his Dark Archangel Form (https://cata-twinhead.twinstar.cz/?spell=93757).

He also doesn't walk around the room downstairs.

**How to reproduce:**
Engage Baron Ashbury in Shadowfang Keep and wait for him to cast Asphyxiate.

**How it should work:**
Asphyxiate should deal (afaik) a percentage value of the current Health a Player has and leave the Player at exactly 1 Health at the end of the cast.

Wracking Pain should stack up periodically throughout the fight.

Baron Ashbury should enter his last Phase at 25% Health, starting with casting his Dark Archangel Form.

He should also patrol around his area before being engaged instead of standing still at a set position.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=fIJ3cYQctdw

**Comment by Afgann** [comment]
fixed
