### ISSUE TITLE
[The Stonecore] High Priestess Azil - Devout Follower

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3239]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
High Priestess Azil doesn't spawn Devout Followers as much or as regularly as she should (It feels like they only spawn during the Energy Shield). Also they just spawn near the Staircase of her Platform.

**How to reproduce:**
Engage High Priestess Azil in the Stonecore.

**How it should work:**
Devout Followers should spawn regularly throughout the whole fight coming from far back around the corners of the Room and from the Exit. See the Reference Video for this.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=y7GFLI_PCUM

**Comment by UltraNix** [comment]
#3388
