### ISSUE TITLE
[Blackrock Caverns] Karsh Steelbender - Heat Wave Range and Lava Spout

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3240]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Karsh Steelbender's Heat Wave (https://cata-twinhead.twinstar.cz/?spell=63677) Range is off. It only hits targets very close to him, so mostly melees.

Also when losing his Superheated Quicksilver Armor (https://cata-twinhead.twinstar.cz/?spell=75846) stacks and gaining Quicksilver Armor (https://cata-twinhead.twinstar.cz/?spell=75842) again, the Lava Spout (https://cata-twinhead.twinstar.cz/?spell=76007) doesn't activate/spawn at the outer ring of his Platform.

**How to reproduce:**
Engage Karsh Steelbender in Blackrock Caverns.

**How it should work:**
Heat Wave's Range should be higher and should hit the whole Group.

Lava Spout should spawn at the outer ring after losing Superheated Quicksilver Armor stacks.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=aqeEvnE7mD4

**Comment by Alandiel** [comment]
Adds spawn, but there is no dmg to players standing on grate when boss loses Superheated Quicksilver Armor.

**Comment by Afgann** [comment]
fixed
