### ISSUE TITLE
[Lost City of the Tol'vir] Lockmaw and Augh - Scent of Blood, Frenzy and Whirlwind Speed

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3242]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Frenzied Crocolisk aren't focusing the target that is currently debuffed by Scent of Blood (https://cata-twinhead.twinstar.cz/?spell=81690), but rather a fixed target.
Also I am not quite sure, but I think Players don't even get the Debuff.

Augh doesn't enter Frenzy (https://cata-twinhead.twinstar.cz/?spell=91415) when engaged.

Augh isn't slowed during Whirlwind (https://cata-twinhead.twinstar.cz/?spell=84785) making it almost impossible to kite him.

**How to reproduce:**
Engage Lockmaw & Augh in Lost City of the Tol'vir.

**How it should work:**
Frenzied Crocolisk should always focus the target that is currently debuffed by Scent of Blood.
Players should randomly get debuffed by Scent of Blood.

Augh should enter Frenzy when engaged (because Lockmaw just died).

Augh should be slowed down during Whirlwind, so it's possible to kite him.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=BjLuzdSPHyg

**Comment by Afgann** [comment]
fixed
