### ISSUE TITLE
[Lost City of the Tol'vir] High Prophet Barim - Blaze of the Heavens, Repentance and Merged Souls

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3243]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blaze of the Heavens moves too quick.
If Blaze of the Heavens dies, it doesn't turn into an Egg, but disappears.

Repentance doesn't pull Players and make them kneel in front of him for 6 seconds. It also doesn't knock them back afterwards.

If the Merged Souls reach the Harbinger of Darkness, they don't heal it or increase damage with Merged Souls (https://cata-twinhead.twinstar.cz/?spell=82263).

**How to reproduce:**
Engage High Prophet Barim in Lost City of the Tol'vir.

**How it should work:**
Blaze of the Heavens should move much slower.
If Blaze of the Heavens dies, it should turn into an Egg, that starts with low health and slowly heals up. After 20 seconds of the Egg not dying and Boss not phasing, a new Blaze of the Heavens should hatch from the Egg, repeating the process.

Repentance should pull Players and make them kneel in front of High Prophet Barim for 6 seconds. It should also knock them back afterwards.

If the Merged Souls reach the Harbinger of Darkness, they should heal it and increase damage with Merged Souls (https://cata-twinhead.twinstar.cz/?spell=82263).

**Database links:**
Reference Video: https://www.youtube.com/watch?v=0GgWaUhU6-g

**Comment by Alandiel** [comment]
Harbinger of Darkness and Merged Souls works fine. Blaze of the Heavens speed is fine.
Blaze of the Heavens should spawn few seconds after the cast from small pool of fire, currently there is no pool of fire and add always appears close to boss.

**Comment by varjla** [comment]
I must add an error here:

After a wipe, Barim got stuck: we entered in combat after pull hihm with Feeric Fire, but he never moved. He casted all his skills, but no motion at all.

![WoWScrnShot_060423_175016](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/6a09c52e-7ebf-417a-af99-2224200df2f1)
