### ISSUE TITLE
[Deadmines] Glubtok - Fire Wall, Fire Blossom and Frost Blossom

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3244]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fire Wall moves too quickly.

Fire Blossom (https://cata-twinhead.twinstar.cz/?spell=91286) and Frost Blossom (https://cata-twinhead.twinstar.cz/?spell=91287) spawn way too often and too much in quantity. Also they spawn really close to eachother instead of being scattered around the room.

**How to reproduce:**
Engage Glubtok in the Deadmines.

**How it should work:**
Fire Wall should move slower.

Fire Blossom and Frost Blossom should spawn less often and less in quantity. Also the positions should split up more around the room.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=Q9jKEicSZ2Q

**Comment by staR1336** [comment]
Closing as i am linking all issues in one report, #3342
