### ISSUE TITLE
[Deadmines] Foe Reaper 5000 - Overdrive

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When Foe Reaper 5000 channels Overdrive (https://cata-twinhead.twinstar.cz/?spell=88481) he will still stick to the Tank.

**How to reproduce:**
Engage Foe Reaper 5000 in the Deadmines.

**How it should work:**
While channeling Overdrive, Foe Reaper 5000 should walk around randomly periodically instead of sticking to the Tank.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=GK0Cv7AMLio

**Comment by Afgann** [comment]
fixed
