### ISSUE TITLE
[Deadmines] Admiral Ripsnarl - Thirst for Blood, Go For the Throat, Vapor Abilities

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3247]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Admiral Ripsnarl doesn't stack Thirst for Blood (https://cata-twinhead.twinstar.cz/?spell=88737).
He also doesn't cast Go For the Throat (https://cata-twinhead.twinstar.cz/?spell=88836).

Vapors (Swirling Vapor & Condensing Vapor) don't use any abilites or transform.
Condensation (https://cata-twinhead.twinstar.cz/?spell=92013)
Swirling Vapor (https://cata-twinhead.twinstar.cz/?spell=92007)
Condensing Vapor (https://cata-twinhead.twinstar.cz/?spell=92008)
Coalesce (https://cata-twinhead.twinstar.cz/?spell=92042)

**How to reproduce:**
Engage Admiral Ripsnarl in the Deadmines.

**How it should work:**
Admiral Ripsnarl should stack Thirst for Blood.
He should also cast Go For the Throat.

Vapors (Swirling Vapor & Condensing Vapor) should make use of their abilites.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=Yqf6Jk26uR8

**Comment by Alandiel** [comment]
I've just checked this boss and everything works fine.
