### ISSUE TITLE
[Deadmines] Vanessa VanCleef Event - Missing NPC's, Reset if Encounter Wipe

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3248]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the Event for Vanessa VanCleef (before you can attack her), the last Part is missing the NPC's you actually need to save and their scripts.

Also if you finish the whole Event, engage Vanessa and wipe, you need to redo the whole Event.

**How to reproduce:**
Engage Vanessa VanCleefs pre-fight Event.

**How it should work:**
The NPC's you are saving should be there and react to you saving them.

Finishing the Event should make you able to engage Vanessa whenever you want to, without needing to do the Event again if you wipe on her.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=tkNxQ176Bhs (0:00 - 3:06)

**Comment by Alandiel** [comment]
NPCs are there, but they do not take any dmg from Worgen attacking them.

**Comment by staR1336** [comment]
closing as i merged all the issues in #3354
