### ISSUE TITLE
[Deadmines] Vanessa VanCleef - Adds can be outranged, Fiery Blaze leaves nothing behind

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3249]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The adds that Vanessa spawns can be outranged and don't automatically aggro.

Also after casting Fiery Blaze (https://cata-twinhead.twinstar.cz/?spell=93484), no fire patches are staying

**How to reproduce:**

**How it should work:**
Players shouldn't be able to outrange the adds and they should automatically aggro.

After casting Fiery Blaze (https://cata-twinhead.twinstar.cz/?spell=93484), some of the fire patches should stay on the boat and not disappear until the encounter is finished/wiped.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=tkNxQ176Bhs (3:06)

**Comment by triceratopsrider** [comment]
Players also shouldnt be able to leave the boat on ship ladder during bossfight with Vanessa, only by using the ropes on the right time. Right now whole party can just stay outside the ship and dps Vanessa from there.

**Comment by Whatisthisclass** [comment]
No they fixed that. You can't leave the boat and kill her there anymore.

What you CAN do though is, let one player(the tank) take the rope and the rest leaves the boat to avoid flames, which is also not working as intended.

Also Rope Swing Timers seem off, it feels like you need to press it with almost perfect timing, otherwise you may fall down because the ropes can just disappear.

**Comment by Alandiel** [comment]
Flames should cover whole ship. Adds stop spawning after first flames.

**Comment by staR1336** [comment]
closing as i merged all the issues in #3354
