### ISSUE TITLE
Stonecore and Vortex quests

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#3250]
Stonecore and Vortex quests should be accessed by level 81 according to wowhead/twinstar database but on this server they are 82.
Links: 
https://cata-twinhead.twinstar.cz/?quest=28760
https://cata-twinhead.twinstar.cz/?quest=28779
https://cata-twinhead.twinstar.cz/?quest=28814
(Requires level: 81)

**Comment by Afgann** [comment]
fixed
