### ISSUE TITLE
[Death Knight][Spell] Unholy - Ghoul disappears after teleporting

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3251]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you teleport (by using a portal for example) your pet ghoul disappears and you have to summon it again. If the ability is on cooldown you will have to wait up to 2 minutes to resummon your ghoul manually.

**How to reproduce:**
Create a Death Knight, choose Unholy Specialisation, summon your Ghoul Pet and take any Portal (Portal to Hyjal for example).

**How it should work:**
The Pet should automatically be resummoned after teleporting.

**Database links:**
Raise Dead: http://cata-shoot.tauri.hu/?spell=46584
Master of Ghouls: http://cata-shoot.tauri.hu/?spell=52143

**Comment by UltraNix** [comment]
Tested - works okay.
