### ISSUE TITLE
[Death Knight][Spell] Ghoul Pet - Avoidance

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3252]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ghoul Pet is missing Avoidance (http://cata-shoot.tauri.hu/?spell=62137), which leads to it taking great damage from NPC AoE abilities.

**How to reproduce:**
Create a Death Knight, choose Unholy Spec, summon ghoul pet, check spellbook.

**How it should work:**
Ghouls should know the Avoidance Spell.

**Database links:**
Avoidance: http://cata-shoot.tauri.hu/?spell=62137

**Comment by UltraNix** [comment]
Fixed.
