### ISSUE TITLE
Command dosen't work 

### ISSUE THREAD

**Issue by SirKwony** [gamefreedomgit/Maelstrom#3253]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello there good day to you,i have a problem with the following comands /dump GetCVar("SpellQueueWindow") and/console SpellQueueWindow  "X",I've always used those commands and it seems they dosen't work here,

**How to reproduce:**

**How it should work:**
By using /dump GetCVar("SpellQueueWindow")  it should show you the spell que value,when i use it on game says empty result and no the specific values (ussaly is set at 400 by default witch is to high for me personally),and by using /console SpellQueueWindow  "X" you should be able to change the value of spell que as any ammount u prefer but i cant check if the value changed beacuse /dump GetCVar("SpellQueueWindow")  dosnet work and also i cant see any diffrence in the gameplay test (witch i tryed on another server to see if the diffrence is visible and it is accualy very visible ,u can tell the diffrence between 400 spell que and 40-70)ty for your patience

**Database links:**
I think this link might be usefull to understand what this command does http://thedefiantguild.com/forums/discussion/15431.html

**Comment by triceratopsrider** [comment]
I dont know what weird proof with a guild site you showed, but spellque is not an option for cataclysm from 2012. Its Legion feature, which transferred to wotlk classic. When you'll play blizzard (TM) pirate server, you'll get your spell que.

**Comment by SirKwony** [comment]
Hello there ,good day to you yeah your right those commands were in fact added in 7.2 legion but there is an similar option(basically does the same thing but is called diffrent)called custom lag tolerance ,i didnt know that in cata has a diffrent name my bad sorry for wasting ur time .Btw i dont know if everyone can see the setting i read on this site https://wowpedia.fandom.com/wiki/Patch_4.0.3, that u have to add some text to a wow file for the setting to worked.It does for meso ty for educating me i gues Take care
