### ISSUE TITLE
now door at cho gall is locked

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
![image](https://user-images.githubusercontent.com/129559513/235263778-a61003e2-04a7-410f-808a-58dd21983ac3.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Fixed.
