### ISSUE TITLE
Need Before Greed - BoEs Not Becoming Soulbound From BoT Trash

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#3256]
**Description:**

The following implementation by UltraNix of #2615 does not work completely on the Bastion of Twilight (BoT) trash mobs. In the following screenshots, Diggy had won the need roll but the item was not soulbound. 

**How to reproduce:**

Have people inside the BoT raid all need on a BoE epic drop.

**How it should work:**
With the following implementation of soulbinding items that have been needed, the items should become soulbound.

**Image links:**
https://ibb.co/RYCXnmx
https://ibb.co/0Z1KR4V

**Comment by UltraNix** [comment]
@clam119 Need Before Greed system?

**Comment by clam119** [comment]
@UltraNix Yes, the previous implementation whereby if you need on a BoE item then it'll soulbind to the winner. Although I don't have the screenshots, the person who won the BoE shoulders said that it didn't say the item was soulbound at all. Would it be possible to see reproduce this & see if the BoEs from BoT are correctly soulbound & tradeable to people outside of the raid?

**Comment by UltraNix** [comment]
![WoWScrnShot_050123_101032](https://user-images.githubusercontent.com/80540499/235427226-339f04ac-cc60-454b-8c75-c9dbdf442755.jpg)
![WoWScrnShot_050123_101041](https://user-images.githubusercontent.com/80540499/235427230-ca815ddb-79e4-4216-8bd5-115346adc1e4.jpg)
Everything works okay.
