### ISSUE TITLE
BoT Chogall - Tentacle Nameplates Not Visible

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#3257]
**Description:**
The Cho'Gall tentacle adds that spawn on Cho'Gall are not visible when you select "Show Enemy Nameplates." However, they are visible if you enable the option for "Show All Name Plates." I've tested this with the standard UI and with Tidyplates. 

I believe that this is a pretty crucial issue because it decreases the lack of visibility for the DPS that need to clear these adds.

**How to reproduce:**
Enter the final phase of the fight with Cho'Gall and enable "Show Enemy Name Plates" and then "Show All Name Plates".

**How it should work:**
The tentacle adds' name plates should be visible.

**Image links:**
https://ibb.co/c1ynsQs

**Comment by UltraNix** [comment]
Fixed.
