### ISSUE TITLE
omnotron mage spellsteal bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3258]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** if you spellsteal Arcanotron Converted Power stacks with mage will double your cast time

**How to reproduce:**  just spellsteal stacks and cast fire ball

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
