### ISSUE TITLE
Hit on back

### ISSUE THREAD

**Issue by alucardcsn** [gamefreedomgit/Maelstrom#3259]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are monsters that you can't hit the coast even if he has his back to you

**How to reproduce:**
Skills that you have to hit from behind don't work

**How it should work:**
Skills that you have to hit from behind don't work

**Database links:**
[https://uploaddeimagens.com.br/images/004/448/237/original/image_%281%29.png?1682737867](url)

**Comment by Sketish** [comment]
Can you provide any snaps what mobs have that issue ?

**Comment by UltraNix** [comment]
#3261
