### ISSUE TITLE
Arathi Basin wrong achievement proc

### ISSUE THREAD

**Issue by cybertr0nix** [gamefreedomgit/Maelstrom#3260]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Joined Arathi Basin BG and we won 1600 vs 0. One of the Achievements i've got is wrong for this situation - https://www.wowhead.com/wotlk/achievement=161/resilient-victory

Should have only got victory achievement + 1600 vs 0 achievement, but actually got 3 of them.

**How to reproduce:**

Win AB BG 1600 vs 0

**How it should work:**

https://www.wowhead.com/wotlk/achievement=161/resilient-victory  should not proc

**Database links:**

https://www.wowhead.com/wotlk/achievement=154/arathi-basin-victory - correct

https://www.wowhead.com/wotlk/achievement=165/arathi-basin-perfection - correct

https://www.wowhead.com/wotlk/achievement=161/resilient-victory - wrong

**Comment by UltraNix** [comment]
Fixed.
