### ISSUE TITLE
[Druid] Shred does not work on Pounced targets.

### ISSUE THREAD

**Issue by wowstunt** [gamefreedomgit/Maelstrom#3261]
**Description:**
Shred does not work on a target stunned with Pounce.

**How to reproduce:**
Use Pounce on an enemy. Use Shred.

**How it should work:**
You should be able to use shred on stunned targets, as long as you stand behind them.

I have tested shred with different conditions: [Video](https://youtu.be/lo5x7JZDilc)

Shred works fine when used in stealth.
Shred works fine when used after Bash.
Shred works fine when used after War Stomp.
Shred does not work after using Pounce.

**Database links:**
[Shred](https://cata-twinhead.twinstar.cz/?spell=5221)
[Pounce](https://cata-twinhead.twinstar.cz/?spell=9005)
[Bash](https://cata-twinhead.twinstar.cz/?spell=5211)
[War Stomp](https://cata-twinhead.twinstar.cz/?spell=20549)

**Comment by wowstunt** [comment]
Update: Works fine with Maim as well.

**Comment by UltraNix** [comment]
Fixed.
