### ISSUE TITLE
BUG PICARO GNOMO

### ISSUE THREAD

**Issue by ztinku** [gamefreedomgit/Maelstrom#3262]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Hola.
saludos cordiales

Tengo un problema al jugar mi gnoma picara sutileza.
uso macro:

/lanzar Paso de las Sombras
/lanzar Premeditación
/lanzar Golpe bajo

funciona, pero siempre quedo lejos del alcance del objetivo y no lanza Golpe bajo.
es decir si se activa pero no permite lanzar Golpe bajo porque sale el mensaje fuera del alcance.
ayuda porfavor ya quiero probar mis habilidades.
![Sin título](https://user-images.githubusercontent.com/132145996/235305768-1741cf57-886a-4872-9331-42baae6f174d.png)
![2](https://user-images.githubusercontent.com/132145996/235305804-bff2e713-10e4-4a25-b30f-09fd9f76081c.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
By Google Translate:
```
Hello.
kind regards

I'm having a problem playing my gnome rogue subtlety.
macro usage:

/cast Shadowstep
/cast Premeditation
/cast Cheap Shot

It works, but I always stay out of target range and doesn't cast Cheap Shot.
that is, if it activates but does not allow Cheap Shot to be cast because the message goes out of range.
help please I want to test my skills.
```
