### ISSUE TITLE
Dancing Rune Weapon not using Pestilence and not always attacking main target

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3263]
There seem to be a number of bugs related to this ability currently. I have seen it attacking adds after I summoned it instead of attacking the target I have used it on, using it does not agro my target and the DRW will not even attack unless I do so first. It also is not spreading it's dots with Pestilence when I cast it, either like it should be.

**How to reproduce:**
Use DRW, outbreak and then Pestilence in AoE. The other targets will only get *your* debuffs, not the rune weapon's.

**How it should work:**
DRW should mimic all of your abilities, both buffs and debuffs and attack the target it is used on almost instantly instead of sitting and waiting for you to attack.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=49028#comments
https://cata-twinhead.twinstar.cz/?spell=50842

**Comment by UltraNix** [comment]
DRW (according to tooltip) should mimic only attacks, not all abilities.

**Comment by EdyGlockenspiel** [comment]
Incorrect. The only spell it is *not* supposed to use is Death and Decay. You can see this in the comments for it on wowhead. I personally just tested it on the wrath classic PTR (free to DL and use by anyone) I set a target dummy as skull and set it as focus, applied my dots, while rune weapon was up. Then used pest and both target were now afflicted with both dots. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/126888684/ccca9bb2-7ead-4076-bccc-2611018fb940)
As you can see in this SS, both skull and X are affected by both dots while rune weapon is up.

**Comment by EdyGlockenspiel** [comment]
The list of abilities the rune weapon can *not* do is shorter than the list in can. It can not use Strangulate/mind freeze, Death and Decay, Raise Dead, you can't death pact it. It wont blood tap, Darn Command (taunt), horn of winter, Icebound fortitude, path of frost, AMS, Death grip or death gate. It will do *everything* else. If I am missing something let me know. This was from my testing on the wrath classic PTR on a template instant 70 character.

**Comment by EdyGlockenspiel** [comment]
https://www.wowhead.com/spell=49028/dancing-rune-weapon#comments for reference, here is the wowhead version for ye olde comments on the ability.

**Comment by UltraNix** [comment]
Fixed.
