### ISSUE TITLE
[Achievement] Twin Peaks Mountaineer

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#3264]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Meeting the achievement criteria does not grant the achievement. 

**How to reproduce:**
Achievement within the battleground Twin Peaks. With the enemy flag in hand, perform a /roar emote while under the effect of Berserking and speed power. Tested as an Alliance player but playing for the Horde side. 

**How it should work:**
Performing /roar emote while under the effect of Berserking and speed power, while holding the enemy flag, should grant the achievement. 

**Database links:**
https://cata-twinhead.twinstar.cz/?achievement=5230

**Comment by UltraNix** [comment]
Fixed.
