### ISSUE TITLE
Hunters Camouflage Bug

### ISSUE THREAD

**Issue by Firsthunterz** [gamefreedomgit/Maelstrom#3265]
Camouflage is supposed to reduce the range enemies can detect you but currently this part of it does not work. The range at which mobs detect you stays the same with or without having Camouflage.

**Comment by UltraNix** [comment]
Without Camouflage:
![WoWScrnShot_052923_183935](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/38e390c8-588b-44ba-a3d5-6087972415f6)
It's something 20y for 60 lvl players against 70 lvl mob.

With Camouflage:
![WoWScrnShot_052923_184111](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b18f0bd7-ad52-4358-a13e-b41b2756aba3)
Only 7yards.

**Comment by Firsthunterz** [comment]
Camo is a level 85 ability. I think testing it at lvl 60 against lvl 70 mobs doesnt validate anything. Why not test it at lvl 85 against lvl 85 mobs?
