### ISSUE TITLE
Satchel of Spoils has no gold or Justice Points in it.

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3266]
**How to reproduce:**
Open a Satchel of Spoils from OS 10

**How it should work:**
It should have about 40~ gold and 80 Justice Points inside it 100% of the time 

**Database links:**
https://www.wowhead.com/item=43347/satchel-of-spoils#comments

**Comment by Afgann** [comment]
fixed
