### ISSUE TITLE
BoT HC Trash packs

### ISSUE THREAD

**Issue by Jcbn0** [gamefreedomgit/Maelstrom#3267]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

If you pull any of the patrol mobs in the first room of the raid BoT, they agro almost the whole room which should not happen

**Comment by xmrshoot** [comment]
same problem on nm difficulty

**Comment by UltraNix** [comment]
Fixed.
