### ISSUE TITLE
BoT: Ascendant Council - Lightning Blast

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#3268]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During Ascendant Council Phase 2 with Arion and Terrestria, Arion's Lightning Blast ability is chaining to the entire raid instead of only targeting the tank as it is supposed to. All guides for this fight including the dungeon guide say that Lightning Blast should only target Arion's primary target aka the tank.

**How to reproduce:**
Reach Phase 2 on the Ascendant Council fight and engage with the bosses. Wait for Arion to Disperse and then cast Lightning Blast.

**How it should work:**
Arion's Lightning Blast should only be affecting the tank who is Arion's primary target.

**Database links:**
https://www.tentonhammer.com/guides/cataclysm-raid-guide-ascendant-council

**Comment by UltraNix** [comment]
Fixed.
