### ISSUE TITLE
Small Spice Bag does not have a 100% chance for cooking awards

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3271]
**Description:**
Looking at comments on wowhead from 4.0 will show you that the cooking awards were upped in patch 4.0 to be a 100% drop from the spice bag, as opposed to the 50% at 1 or 2 during wrath. Currently, it seems the wrath drop rate may be the one being used here instead or even the twinhead incorrect drop chance, witch shows a 33% chance for a single award.

**How to reproduce:**
Open the Small Spice Bag

**How it should work:**
The bag should have a 100% chance to contain one award and some Spices, with a rare chance at cooking recipes. 

**Database links:**
https://www.wowhead.com/item=44113/small-spice-bag#comments "After doing about 20 daily cooking quests since 4.0.3a, I believe the bags now contain one award guaranteed. However, they don't ever seem to have more than that. It used to be that each bag had a chance (50%?) to get 1-2 extra awards. Now it is 100% chance to get one award."

**Comment by Afgann** [comment]
fixed
