### ISSUE TITLE
bwd gate locked

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3272]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** we killed omno and magmaw and gate is locked wtf ,we must relog to unlock it

**How to reproduce:** 
![image](https://user-images.githubusercontent.com/129559513/235370347-d2eb3365-5b5e-471d-a5e6-f797f74000f3.png)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
