### ISSUE TITLE
Sinestra whelp aggro after respawn

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After they die, the whelps on Sinestra are supposed to respawn with the same aggro they had when they died, however they seem to be respawning with no aggro at all.

**How to reproduce:**
Tank and kill the whelps on Sinestra with some DPS players doing AoE.

**How it should work:**
The whelps should continue attacking whoever they were attacking when they died.

**Database links:**
A kill video from retail illustrating the whelps staying on the tank: https://youtu.be/g97QQ9M8BcQ?t=110

**Comment by UltraNix** [comment]
Fixed.
