### ISSUE TITLE
[Quest][Npc] Grok doesn't have quest to start Ogri'la Chain

### ISSUE THREAD

**Issue by Exorcista** [gamefreedomgit/Maelstrom#3275]
**Description:** NPC: https://wowclassicdb.com/tbc/npc/22940 , doesn´t have quest: https://wowclassicdb.com/tbc/quest/10984 needed to unlock Ogri'la rep chain

**How it should work:** He should have it

**Comment by Alandiel** [comment]
Actually V'eru(https://wowclassicdb.com/tbc/npc/22497) should have 1st quest(https://wowclassicdb.com/tbc/quest/10984).

**Comment by Exorcista** [comment]
> Actually V'eru(https://wowclassicdb.com/tbc/npc/22497) should have 1st quest(https://wowclassicdb.com/tbc/quest/10984).

can confirm, so sorry
