### ISSUE TITLE
Issues with Horde Children's Week quests

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#3276]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) There is no NPC in Orgrimmar that sells the "Tigule and Foror's Strawberry Ice Cream" required to complete the quest "You Scream, I Scream..." The listed NPC in Thousand Needles has no merchant inventory and thus does not sell the required item either. The only other Horde side NPC that would possibly sell this item is the Innkeeper in Garadar in Nagrand, and this requires one to complete enough quests in Nagrand to become neutral with the Mag'har.

2) The NPC Blax Bottlerocket does not sell the unique quest item "Foam Sword Rack" for the Children's Week quest "A Warden of the Horde". He is supposed to sell said item as long as you have this quest active.

**How to reproduce:**
1) Examine the area shown with the in game quest helper tool and look for the NPC visually and using /tar commands.

2) Find Blax Bottlerocket in The Drag in Orgrimmar and open his inventory with the quest active.

**How it should work:**
1) The NPC should either be standing in Orgrimmar where it says he should be or possibly in a different location depending on the current "patches" applied.

2) The NPC should be selling the quest item as long as you have the associated quest active.

**Database links:**
1) https://cata-twinhead.twinstar.cz/?item=7228
    https://www.wowhead.com/npc=14480/alowicious-czervik
    https://cata-twinhead.twinstar.cz/?npc=14480

2) https://www.wowhead.com/item=69057/foam-sword-rack#sold-by
    https://cata-twinhead.twinstar.cz/?item=69057

**Comment by UltraNix** [comment]
Fixed.
