### ISSUE TITLE
Throne of the Four Winds HC

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3277]
Description:
-Lightning Clouds become invisible after first wipe in P3 of HC version of the fight (visual missing, damage still hits players so it's harder to know when to move) 
-Squall Line (tornados) still exists in P3 and if you go too low, you get sucked into them and spin around the boss like in P1 (they should dissapear forever after P2)
-Lightning Cloud stays under the platform if you wipe in P3 and it's visual is there even when you reenter the raid, you can see the cloud in P1/P2 of the fight always after the first wipe on that ID (doesn't do dmg, just a visual bug)

**Comment by UltraNix** [comment]
Fixed.
