### ISSUE TITLE
Children's Week

### ISSUE THREAD

**Issue by Mukthal** [gamefreedomgit/Maelstrom#3278]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Some achievements / quests are bugged. For example [School of Hard Knocks]
- Capture the flag in Eye of the Storm
- Assault a tower in Alterac Valley
- Assault a flag in Arathi Basin
- Return a fallen flag in Warsong Gulch

You can summon the orphan during the prepare phase but it's gone during bg and you can not resummon it.

You can not buy the dragon kite and foam sword rack in Ogrimmar or Stormwind either.

Not sure about the other quests yet, I will update this topic once I tried.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Mukthal One bug - one report please.

**Comment by UltraNix** [comment]
@Mukthal Just tested that achievement:
![image](https://user-images.githubusercontent.com/80540499/235490223-0e55a456-6190-4dbf-82fe-45c318b3d62e.png)

It works okay to me. Were you maybe crossfactioned?

About orphan - I got no problems with losing/resummoning orphan during the bg.  It despawns when you die or too far away from you. You can always despawn and summon a new one with the whistle.

**Comment by MaelstromAbbey** [comment]
@UltraNix  Tested as non-crossfaction with Human Orphan Whistle. Functional with exception to Alterac Valley which may be unobtainable at this time?

![](https://i.imgur.com/MO3jDnK.png)

**Comment by Mukthal** [comment]
Okay nice, thank you

**Comment by UltraNix** [comment]
Fixed with bringing back AV
