### ISSUE TITLE
[Twin Peaks] [Achievement] Double Jeopardy awarded incorrectly.

### ISSUE THREAD

**Issue by wowstunt** [gamefreedomgit/Maelstrom#3280]
**Description:**
The Twin Peaks Achievement "Double Jeopardy" is awarded incorrectly.

**How to reproduce:**
Win Twin Peaks 0-3.

**How it should work:**
The achievement should only be awarded for winning 2-3 after being behind 2-0.

**Database links:**
[Double Jeopardy](https://cata-twinhead.twinstar.cz/?achievement=5231)

**Comment by wowstunt** [comment]
![image](https://user-images.githubusercontent.com/132130079/235504587-4d86ac85-37c8-4d05-a669-d9b7437cee96.png)

You should not be able to get those achievements at the same time. One calls for a 0-3, the other calls for 2-3.

[Double Jeopardy](https://cata-twinhead.twinstar.cz/?achievement=5231)
[Twin Peaks Perfection](https://cata-twinhead.twinstar.cz/?achievement=5215)

**Comment by UltraNix** [comment]
Fixed.
