### ISSUE TITLE
Children's Week (Wolvar quests)

### ISSUE THREAD

**Issue by GMHiki** [gamefreedomgit/Maelstrom#3281]
### REPORTED BY PLAYER

Dalaran orphan quests (wolwar) couldn't be completed regardless of being revered with Frenzyheart tribe. None of the first 3 quest.

![Whitemane_mt2phOttDl](https://user-images.githubusercontent.com/93480183/235482332-02a0fe47-0fb6-4212-8a95-e0e9410a0a58.png)
![Whitemane_j8jTF0saPU](https://user-images.githubusercontent.com/93480183/235482337-93bc6829-3ae2-4404-8004-fe0e220fec72.png)
![Whitemane_T7gTcg5Qp2](https://user-images.githubusercontent.com/93480183/235482345-13ecbb25-9401-443b-aed5-93f6959199d5.png)

added these to myself and tried turning in, orphan doesnt register complete when we are in area to "visit"

**Comment by EdyGlockenspiel** [comment]
Same for the Oracle Orphan as well. I went to every location with both and neither got credit for any. I also could not do the quest in dal to talk to Aria for either of them.

**Comment by UltraNix** [comment]
Fixed.
