### ISSUE TITLE
Pendant of the Scarab Storm

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3282]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pendant of the Scarab Storm can be used in arena

**How to reproduce:**

use in arena
**How it should work:**

should not be able to use

**Database links:**
https://www.wowhead.com/item=64881/pendant-of-the-scarab-storm

**Comment by UltraNix** [comment]
Fixed.
