### ISSUE TITLE
The feign death ability for hunter is bugged 

### ISSUE THREAD

**Issue by trickHunt** [gamefreedomgit/Maelstrom#3283]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The ability barely works, Like it doesnt trigger when you click on it and when it does the animation doesnt play out. this happens 9 out 10 times. Mind you this used to work just fine the previous months.

**Comment by UltraNix** [comment]
@trickHunt Maybe some more info on here. Give us some screenshots.
Feign Death cannot be used against bosses and also can resist.

**Comment by trickHunt** [comment]
> @trickHunt Maybe some more info on here. Give us some screenshots. Feign Death cannot be used against bosses and also can resist.

It mainly happens in pvp. bgs and such

**Comment by UltraNix** [comment]
Still says nothing to me. Combat log and screenshots with that bug would be helpful.

**Comment by trickHunt** [comment]
> Still says nothing to me. Combat log and screenshots with that bug would be helpful.

Check discord ill send a video there

**Comment by UltraNix** [comment]
Fixed.
