### ISSUE TITLE
[Children's Week] School of Hard Knocks

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#3284]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are two issues with this achievement.

1) With your Orphan summoned within a battleground, meeting the achievement criteria does not count. For example, within Warsong Gulch and with the Orphan summoned, I personally returned a fallen flag but did not receive achievement credit. 

2) One of the 4 criteria for this achievement involves assaulting a tower within Alterac Valley. To my knowledge Alterac Valley in not within the random battleground lineup. This prevents the player from earning this achievement, and thus prevents completion of the [For The Children](https://cata-twinhead.twinstar.cz/?achievement=1793) World Event with title reward.

**How to reproduce:**
See description. 

**How it should work:**
With any Orphan summoned via the various [Orphan Whistle's](https://cata-twinhead.twinstar.cz/?item=18598), meeting the achievement criteria should grant credit. 

**Database links:**
https://cata-twinhead.twinstar.cz/?achievement=1786
https://cata-twinhead.twinstar.cz/?item=18598
https://cata-twinhead.twinstar.cz/?achievement=1793

**Comment by UltraNix** [comment]
#3278
