### ISSUE TITLE
gathering nodes inside the rocks and underground

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#3285]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
basically just like the title explains , herbs and ore nodes sometimes are inside the ground or under a rock or a tree , cannot be mined or gathered , and i've taken a sample , it shows on the minimap and i see a tiny glow coming out of the rock in the picture , but cannot be clicked no matter what i did

**How to reproduce:**
go to Desolace , coordinates : 66:49  , you'll see the sample i've spotted , there is another one in Durotar , i can get a screenshot if you want 

**How it should work:**
it shouldn't be underground , it's suppose to be ON the ground , visible and clickable

**Database links:**
https://imgur.com/mVLU3UO

https://imgur.com/IrmInSZ

**Comment by Exorcista** [comment]
just provide the coords (use carbonite or mapcoords addons) and gms fix it manually

**Comment by Macilious** [comment]
@Exorcista  read the post again
