### ISSUE TITLE
Crate of Tasty Meat can contain nothing, or just a single grey item

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3287]
**Description:**
I opened 16 of these are only a few had multiple meats inside, and the last 2 had *no* meat in side. The very last one had a single grey item in it and the one before that was empty.

**How to reproduce:**
Open Crate of Tasty Meat

**How it should work:**
As of 4.0.6, (this server is supposed to be based on the last patch of cata) you are supposed to always contain 2 things of meat like some Giant Turtle Tongue and some Crocolisk Tail for example, and not just a single one of each, but several. As well as several grey vendor trash items.

**Database links:**
https://www.wowhead.com/item=65513/crate-of-tasty-meat#comments "Does anyone else notice that these give more items than before patch 4.0.6? I'm asking this because I got 3 Snake Eyes and 2 Blood Shrimps when I opened a crate today." and there is a comment stating they opened 100 of them and what they got from those total.

**Comment by Afgann** [comment]
fixed
