### ISSUE TITLE
Enlarged Onyxia Hide Backpack and Head of Onyxia does not drop off boss

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3288]
**Description:**
My group downed 10 man Ony just now and no bag dropped. 

**How to reproduce:**
Kill Ony 10 or 25

**How it should work:**
The bag should be a 100% drop on either 10 or 25 man

**Database links:**
https://cata-twinhead.twinstar.cz/?item=49295

**Comment by EdyGlockenspiel** [comment]
Now that I am thinking about it, the head did not drop either, for either faction. We had both horde and alli in the group and neither faction head dropped.

**Comment by Afgann** [comment]
fixed
