### ISSUE TITLE
Magtheridon does not drop his head

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3289]
**Description:**
I just soloed Magtheridon and did not get the quest starter head off of him like I am supposed to.

**How to reproduce:**
Kill Magtheridon and loot him.

**How it should work:**
The boss should drop his head 100% of the time for both factions, but only horde can see the horde version and only alliance can see the alliance version.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=32385#dropped-by
https://cata-twinhead.twinstar.cz/?npc=17257

**Comment by Afgann** [comment]
fixed
