### ISSUE TITLE
Black Sack of Gems has no gems inside it

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3290]
**Description:**
I just opened a Black Sack of Gems, and like most openable items on this server, to nobody's surprise, it was empty.

**How to reproduce:**
Open Black Sack of Gems

**How it should work:**
It should always contain a handful of gems, with a rare chance to contain epic gems instead of rare gems.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=34846#contains

**Comment by UltraNix** [comment]
Fixed.
