### ISSUE TITLE
Time to Visit the Caverns does not give quest credit

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3291]
**How to reproduce:**
Fly up to Zaladormu with your Orphan out.

**How it should work:**
When you get to Zaladormu, you should get quest credit for taking the Orphan to the Caverns of Time.

**Database links:**
https://www.wowhead.com/quest=10962/time-to-visit-the-caverns#comments "to discover caverns of time you need to walk infront of the big dragon "Zaladormu" who's lying in the middle of the room after you've landed (If you've used the dragon to fly down in the cave)"

**Comment by MaelstromAbbey** [comment]
I had no issues with this quest while using Human Orphan Whistle

**Comment by MaelstromAbbey** [comment]
I had no issues with this quest on the Alliance side using Human Orphan Whistle

**Comment by UltraNix** [comment]
Works okay. You must have [Toy Dragon](https://www.wowhead.com/item=31951/toy-dragon) before you visit the dragon.
