### ISSUE TITLE
Playmates! for Wolvar Orphan quest does not work still

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3292]
**How to reproduce:**
Take Wolvar Orphan to where it says on the map and fly around the area

**How it should work:**
A Snowfall Glade Playmate should be present at the coords specified on wowhead so that an interaction can happen and quest can complete. Currently that NPC is not there.

**Database links:**
https://www.wowhead.com/quest=13951/playmates#comments
https://www.wowhead.com/npc=34490/snowfall-glade-playmate

**Comment by sadgh05t** [comment]
Can confirm it's still not working

**Comment by emirie1** [comment]
I was able to complete this quest just a little while ago myself. The playmate was at the end of one of the northern pathways out of the area.

**Comment by UltraNix** [comment]
Fixed.
