### ISSUE TITLE
Darkmoon card Hurricane

### ISSUE THREAD

**Issue by Knezwow** [gamefreedomgit/Maelstrom#3295]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Given trinket doesnt work properly from the begining of server , few of us did testing it procs 1 time in 2million damage or not proc at all this is an urge to fix because its bis trinket thats completly unusable.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any combat logs/video that is showing for example 3 min of dummy testing?

Data I found on websites.

During 10 minutes on dummy:

41 procs, (37 hits 5500-8200 dmg, 4 crits 7500-10700 dmg)
Total proc damage 289.4k / 600 sec = 482 DPS
![image](https://user-images.githubusercontent.com/122209088/235628438-bbfa8874-5980-461f-8016-5ccd6afad75f.png)
![image](https://user-images.githubusercontent.com/122209088/235628683-418a8d54-a8ac-4a27-9c6b-3f7ebce46126.png)
![image](https://user-images.githubusercontent.com/122209088/235629099-d9fb540f-6f43-4dc0-830b-df2418993134.png)

[Patch 4.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_4.2.0) (2011-06-28): Darkmoon Card: Hurricane damage done when triggered has been increased by 40%, however, it can no longer deal critical strikes and no longer receives any modifiers to its damage from the equipping player.

**Comment by Knezwow** [comment]
Here we go  i did 5 min round of shooting and this is the result [https://prnt.sc/JFsP4q11S0Er](url)

**Comment by UltraNix** [comment]
Hmm, as I can see that in database the PPM rate is set to 1. It means e.g. for weapon or ranged with 2.3sec, it's 3.8% chance of proc.

**Comment by Sketish** [comment]
Yes, proc has no icd so for example you can have  2 procs in a row

**Comment by UltraNix** [comment]
Yep, but bassicaly it's 1 proc per 1 minute, as it's stated above in the wowhead comment.

**Comment by Knezwow** [comment]
All darkmoon cards should be bis trinket untill raid hc ones and thats the problem here every trinket is usefull but hurricane at the moment.

**Comment by Sketish** [comment]
Thats not true, hurricane + earthquake weren't best options. 
http://web.archive.org/web/20120106083555/http://elitistjerks.com/f79/t110302-enhsim_cataclysm/
http://web.archive.org/web/20111125080502/http://elitistjerks.com/f79/t113391-enhancement_bis_gear_set_up_discussion_4_2_onward

After nerf on 4.2 it wasnt considered good since any modifier wasnt working on that proc.
