### ISSUE TITLE
Vortex Pinnacle trash

### ISSUE THREAD

**Issue by tchernobay** [gamefreedomgit/Maelstrom#3297]
The Trash in Vortex Pinnacle is completly wrong. Because of that the tank has a debuff the whole time that reduces his tempo for 75% 
Its literally hardmode compared to how it normally should work. 

https://www.youtube.com/watch?v=TJECDDNc-Ts Here a link for the proper set up

**Comment by Alandiel** [comment]
Can you specify which trash mobs exactly?

**Comment by tchernobay** [comment]
For example the 3rd till the 6th group are completly wrong. Instead of 3 Gust soldiers and 1 Vortex there should be 3 vortex and 1 Gust Soldier.

**Comment by Sketish** [comment]
https://youtu.be/W4YJggZsbKM?t=27 as you can see it not always true there are packs with 3 gust soldiers and 1 vortex

**Comment by UltraNix** [comment]
Fixed.
