### ISSUE TITLE
vortex pinnacle bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3299]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** after we kill first boss tornado dpnt appear and i coudnt go to second 

**How to reproduce:** 
![image](https://user-images.githubusercontent.com/129559513/235648471-85c2711a-482a-4049-ba83-1971b1b8735b.png)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
