### ISSUE TITLE
Leaving Combat takes too much time (especially in arenas)!

### ISSUE THREAD

**Issue by VincentADK** [gamefreedomgit/Maelstrom#3301]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am writing this for Alp#2070 (if you need more Information, it's his discord handle)
Quote:" Combat on this server is bugged. 
You stay in combat for too long in arenas sometimes. 
Even when you meld you get in combat 1 sec later sometimes.
I feel like there is also the typical private server issues with HoT effects keeping combat too long."

This seems to be a general issue.
Like sometimes a blind doesn't drop combat and so on!

**How to reproduce:**
Try to test an arena match and then have a hot effect on you and try to meld or things like vanish.
This should pretty much show you how long it will take to leave combat.
You can also try this on normal mobs with blind as an example!

**How it should work:**
You should drop combat immediately after melding or using other means to escape active combat.

**Database links:**
Don't have a link - sorry!

**Comment by UltraNix** [comment]
#3375
