### ISSUE TITLE
[NPC] Scarshield warlocks

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#3311]
**How to reproduce:**
Scarshield warlocks are summoning infinite amount of burning felguards
![image](https://user-images.githubusercontent.com/36106057/235811526-299c70ef-6333-4c1c-8bb6-cf83c28f6714.png)
reported before also on previous bug tracker
https://github.com/SallyWhitemane/Maelstrom/issues/574
**How it should work:**
It should not summon infinite amount of them

**Comment by itsemmastone** [comment]
Fixed in: Core/Scripts: Fix some scripts spawning too many summons.
