### ISSUE TITLE
Damage does not stop channeling if shielded

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3313]
When you cap an objective in battlegrounds, and I suspect that by transitivity, any channeling anywhere that requires x seconds to complete, if you happen to be shielded (power word shield, mage barriers, engi belt shield and so on) you do not get interrupted due to the damage being absorbed and not actually being dealt.

How it should work: no matter if absorbed or not, channeling should interrupt upon receiving an act of attack

How to reproduce: cap a base in Arathi Basin and get attacked while shielded, the cap will not stop, often resulting in tricky, usually impossible base caps .

I suspect that it is the same for Eye of the storm Flag channel.

Alternatively, can go to tol vir dungeon and try to channel the lever on first boss mechanic, if shielded you prob wont be stopped from channeling the lever for the mechanic.

**Comment by UltraNix** [comment]
Fixed.
