### ISSUE TITLE
[TotfW] The Conclave of Wind 

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3314]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) Ravenous Creepers sometimes stops attacking, running or doing anything really, when they are switching targets due to taunts or threat overwhelming. Creepers can just stay in the healing aoe and wipe the raid or not gather around the tank.
They should also move a bit quicker and have only 187k hp.
2) Soothing Breeze timers are not matching with the DBM, also boss always use it on himself, while he should use it on creepers too.
3) Rohash Wind Blast still has a much larger aoe than he should. (https://youtu.be/GWRCA06kmOk?t=174 Notice how here retri is managing to dodge the knockback).

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=YBEtPSNn4D0
https://www.youtube.com/watch?v=GWRCA06kmOk

**Database links:**

https://wowpedia.fandom.com/wiki/Ravenous_Creeper
https://www.wowhead.com/npc=45812/ravenous-creeper
https://www.wowhead.com/spell=86206/soothing-breeze#comments

**Comment by UltraNix** [comment]
Fixed.
