### ISSUE TITLE
Vampiric Touch - dispell issue

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3315]
When you try to dispell Vampiric Touch from player it  should fear they player that casted dispell not the player who had debuff.
https://clips.twitch.tv/SlipperyPluckyPterodactylCurseLit-OnxFbIB-mp5y1PmX
Mullich comment
![image](https://user-images.githubusercontent.com/122209088/235876416-d1bab4eb-4b70-49da-8179-aafd6fb48a9a.png)

**Comment by UltraNix** [comment]
Fixed.
