### ISSUE TITLE
Extending Dugenons lockouts not working

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3316]
I was trying to extend the ID of deadmines HC but as soon as I press the button it appears extended for one second and after goes back to normal. Although in the chat you can see I was spamming it and it was saying it was extended. Not working as intended
![image](https://user-images.githubusercontent.com/122209088/235877159-9217392c-631b-49da-8812-fe608aeeae70.png)
 How it should work
 Existing or recently expired IDs can be extended via the Social tab under Raid by clicking on Raid Info. The ID of any instance to which a player is saved can be extended. Doing so will extend the lockout period by the same amount of time as the original lockout (i.e. extending an [Ulduar](https://wowpedia.fandom.com/wiki/Ulduar_(instance)) raid ID will add 7 days, a Heroic: [Halls of Lightning](https://wowpedia.fandom.com/wiki/Halls_of_Lightning) dungeon ID will add 24 hours, and a [Zul'Gurub](https://wowpedia.fandom.com/wiki/Zul%27Gurub) raid ID will add 3 days to the lockout time). An ID can be extended more than once. An extension can be reversed on an individual basis provided the player does not do anything in the instance during the extended lockout period that would save that player to the instance.
 
 Source:
 https://wowpedia.fandom.com/wiki/Instance_Lock_Extension

**Comment by Afgann** [comment]
fixed
