### ISSUE TITLE
[NPC] [BWD] Chimaeron boss frame absent

### ISSUE THREAD

**Issue by johnatgh** [gamefreedomgit/Maelstrom#3317]
Description:

When engaging Chimaeron, it's boss frame isn't present under minimap (default position) therefore boss mods addons fail to initiate.
Not sure if this is the reason, maybe an event isn't triggering to let dbm addons know the fight has begun.

How to reproduce:

Engage the boss.

How it should work:

When fight starts boss frame should be shown under minimap.

**Comment by UltraNix** [comment]
Fixed.
