### ISSUE TITLE
Res sickness doesnt show

### ISSUE THREAD

**Issue by bmeas** [gamefreedomgit/Maelstrom#3319]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This guy has res sickness but doesnt show debuff.

**How to reproduce:**
Not sure.

**How it should work:**
Should show debuff

**Database links:**
![image](https://user-images.githubusercontent.com/131665314/235919686-8dfeb499-169f-46bd-b049-0d724789e0ab.png)

**Comment by UltraNix** [comment]
Fixed.
