### ISSUE TITLE
valiona breath didnt do damage

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3321]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
![image](https://user-images.githubusercontent.com/129559513/235962366-18f37fd0-5ab4-4628-91c4-3ac79e418200.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
i stood in breath and receive dmg only from 1 tick ( 20k)

**Comment by UltraNix** [comment]
Fixed.
