### ISSUE TITLE
The Lone Hunter pet will retain "death" animation after taming (will not attack or follow).

### ISSUE THREAD

**Issue by Wob223** [gamefreedomgit/Maelstrom#3323]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Lone Hunter mob in Easter Plaguelands (https://www.wowhead.com/npc=45450/the-lone-hunter) will continue to display its "death" animation after being tamed, despite having a normal run animation when engaging with it. Appears with full health and will start following the player upon casting the "follow pet" function; will also not attack by itself even on aggressive stance, but will engage if the player will cast the "attack pet" function, however no damage will be dealt and will just follow said mob.  Probably related to the issue: #701 .

**How to reproduce:**
Approach the mob and throw a Freezing Trap (https://www.wowhead.com/spell=187650/freezing-trap) between you and it, and start taming. The mob will "wake" up and run towards the player (all normal animations there); once trapped complete the taming process. Now the pet will be in his original "dormant" position and will not follow on its own, except when using "follow pet" function.

**How it should work:**
The Lone Hunter should not appear in its original "dormant" state when the taming process has been successful, mimicking the intended script: "needs to do a wake up animation" in order to start attacking/using its abilities.

**Database links:**

-Picture bellow, Thank you!
https://www.wowhead.com/npc=45450/the-lone-hunter
https://www.wow-petopia.com/npc.php?id=45450
![Lone Hunter](https://user-images.githubusercontent.com/132481140/235976290-4f642d67-9d8e-492d-857c-62db91aaf586.JPG)

**Comment by UltraNix** [comment]
Fixed.

**Comment by Wob223** [comment]
Thank you!
