### ISSUE TITLE
Falling issue

### ISSUE THREAD

**Issue by Fanits** [gamefreedomgit/Maelstrom#3325]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
reciveing fall damage when its not supposed to happen
**How to reproduce:**
When falling, before i hit the ground if i shift to flyform (on druid) and then take it out, then ill take all the damage as if i never use flyform

**How it should work:**
should not do any damage the way im doing it

**Database links:**

https://user-images.githubusercontent.com/132496902/236019765-c49bbd0e-ff00-4300-a465-6be8b4b39cee.mp4

**Comment by UltraNix** [comment]
Fixed.
