### ISSUE TITLE
Pyromaniac Talent - Fire Mage - Expires too soon

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3326]
https://youtu.be/5QHMTOrMvN0

**Description:** the pyromaniac buff from the fire mage talent expires too soon in some cases (flamestrike tested) or immediately in others (tested living bomb)

**How to reproduce:** Apply a Fire Damaging over Time Spell to 3 Targets or more

**How it should work:** Pyromaniac Talent is supposed to give a 5/10 % haste buff if 3 targets are taking fire damage over time from dots, for as long as 3 targets are taking fire damage.

**Database links:**  https://cata-twinhead.twinstar.cz/?spell=34295

**Comment by triceratopsrider** [comment]
Did you test in in ogrimmar dummies? Cause this issue seem to be the case with dummies, which has unique combat fading and targeting. When dealing with real enemy - it seem to work fine.

**Comment by staR1336** [comment]
> Did you test in in ogrimmar dummies? Cause this issue seem to be the case with dummies, which has unique combat fading and targeting. When dealing with real enemy - it seem to work fine.

Is that so? Damn, I shall try to test in real environment then
Thanks!!

**Comment by staR1336** [comment]
Confirmed, its just the dummies. closing
