### ISSUE TITLE
"Your pet doesn't like that food".

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#3327]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have a lvl85 cat from winterspring as a hunter pet, and although it supposedly only eats meat or fish, it refuses to eat either type, no matter what I offer it. The idea of a vegan cat is cute I guess, but can we not. Honestly, I would like to be able to feed my pet.

**How to reproduce:**
Idk, tame a winterspring cat and try to feed it?

**How it should work:**
It should eat the damn food instead of being a vegan little bastard.

**Database links:**
https://www.wowhead.com/classic/npc=7434/frostsaber-pride-watcher
https://cata-twinhead.twinstar.cz/?item=58263
https://cata-twinhead.twinstar.cz/?item=58262
https://cata-twinhead.twinstar.cz/?item=62778

https://vimeo.com/823485964/8c03a2cc3c

**Comment by Sketish** [comment]
![image](https://user-images.githubusercontent.com/122209088/236412262-ae5f5b4a-27b8-42aa-b2ae-4d71e61b3b2c.png)
confirmed, cat doesnt want to eat meat

**Comment by Zeehra** [comment]
Also seeing other players complain about the same issue, but with other pets; one dude had a wolf that wouldn't eat meat either.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Zeehra** [comment]
Is still not fixed.

**Comment by UltraNix** [comment]
@Zeehra What items? Make a new report with the new ones. Every single item must be revisited individually.

**Comment by Zeehra** [comment]
Oh shit. Well so far it seems a bit random, some pets will eat and some won't. I'll try out some different stuff and get back to you with a list.
