### ISSUE TITLE
Nefarion phase 2 adds are sometimes unable to be attacked / interupted

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3328]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometiems on Nefarion the phase 2 adds are targetable, but abilities don't work. The error message displayed on-screen is "Target not in line of sight".

**How to reproduce:**
*sometimes* during phase 2, target the adds and attempt to use any ability on the adds

**How it should work:**
Abilities should work on the adds

**Database links:**
[Screenshot](https://cdn.discordapp.com/attachments/1103400868109365329/1103401421770067968/image.png)

**Comment by UltraNix** [comment]
Fixed.
