### ISSUE TITLE
Feral druids are unable to interupt Nefarion phase 2 adds

### ISSUE THREAD

**Issue by Readie** [gamefreedomgit/Maelstrom#3329]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During phase 2, feral druids can't use Skull Bash to interupt the adds. The error message displayed is "No path available"

**How to reproduce:**
Be a feral druid during Nefarion phase 2.

**How it should work:**
Skull bash should not error.

**Database links:**
[Screenshot](https://cdn.discordapp.com/attachments/629797416148664320/1103412242675925012/image.png)

**Comment by UltraNix** [comment]
Fixed.
