### ISSUE TITLE
MC on nef (prolly same on cho'gall)making healing and friendly auras not working on oposite faction members

### ISSUE THREAD

**Issue by amanita199** [gamefreedomgit/Maelstrom#3330]
**Description:** after getting dominion as horde, you cant heal ally players. our horde shaman also got MCed and after that alliance players wouldnt receive nature resist, making it a oneshot to those ally players. this might have to do with race swapped feature.
~

**How it should work:**: disable cross faction, give a free faction change if you cant fix this for so long, tired of having to do bosses on normal mode because of server issues.

**Comment by Sketish** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3343
