### ISSUE TITLE
Death Knight [Improved Death strike talent heal BUG]

### ISSUE THREAD

**Issue by Wrathfuljimbo** [gamefreedomgit/Maelstrom#3331]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Death knight: Death strike minimum healing doesn't get affected by the talent  "Improved death strike"

**How to reproduce:**
Use death strike

**How it should work:**
It should increase the healing of the minimum heal component.

**Database links:** 
https://cata-twinhead.twinstar.cz/?spell=81138

**Comment by Wrathfuljimbo** [comment]
Thank you sarR1336 for the great video.
If I may add, it should increase the "Healing for 20% of the damage taken in the last 5 second" part as well, also this should be updated in the tooltip as following for level 3 "Improved death strike" talent: 
Unleash a powerful strike that heals you for 29% of the damage you have sustained during the preceding 5 sec (minimum of at least 10% (10.15 but it is rounded text) of your maximum health), while also dealing 330% weapon damage plus X to an enemy if the attack is successful.

**Comment by pro100klass** [comment]
bug report is wrong, you can close the topic

**Comment by Wrathfuljimbo** [comment]
> bug report is wrong, you can close the topic

Could you elaborate? I mained blood DK on Retail from Cata minute 1 till mid of shadowlands when I stopped playing retail, I am quite sure I remember the mechanics of the class :)

**Comment by Endofree1247** [comment]
i may confirm talent works wrong

**Comment by pro100klass** [comment]
> я могу подтвердить, что талант работает неправильно

.............................

**Comment by UltraNix** [comment]
Fixed.
