### ISSUE TITLE
item bug

### ISSUE THREAD

**Issue by nnkoment** [gamefreedomgit/Maelstrom#3333]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i bought the shoulders then istead of wearing them with the right mouse button i trasported them and they disappeared both in the bag and it is not in the equip also but the points have been deducted , the gms were super efficient in returning them to me but the same thing happened to a friend of mine in transporting them they are buggy check us out

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
No futher info - closing.
