### ISSUE TITLE
[Quest] (Durotar) Never Trust a Big Barb and a Smile

### ISSUE THREAD

**Issue by Tiebob99** [gamefreedomgit/Maelstrom#3336]
**Description:**
During the quest "Never Trust a Big Barb and a Smile", the Clattering Scorpids do not cast envenom like they should. A message pops up on screen, stating "Clattering Scorpid is casting Envenom! Place your totem down now!" However, clicking on the scorpid reveals it does not cast the spell and I get no Sample of Scorpid Venom when placing the totem.

**How to reproduce:**
Accept the quest and aggro a Clattering Scorpid. The scorpion will not cast envenom when the yellow text prompt shows up.

**How it should work:**
When the yellow text prompt "Clattering Scorpid is casting Envenom! Place your totem down now!" the scorpid should start casting envenom. Using the Poison Extraction Totem provided by the quest should divert the spell to the totem and give you a Sample of Scorpid Venom

**Database links:**
Quest - https://cata-twinhead.twinstar.cz/?quest=25165

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/fe891375-11bd-4d96-b0e2-98ac5835f027)

I see cast , it gives credit, i see the prompt.

Cannot reproduce
