### ISSUE TITLE
Death Knight[Glyph of rune tap BUG]

### ISSUE THREAD

**Issue by Wrathfuljimbo** [gamefreedomgit/Maelstrom#3337]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The glyph: Glyph of Rune Tap doesn't heal the death knight for the component: [Your Rune Tap also heals your party for 5% of their maximum health]

**How to reproduce:**
Use rune tap.

**How it should work:**
It should heal the DK for the additional 5% heal, it states it heals "the party" not your "party members" , it should also heal the DK for this amount even if he is solo.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=43825

**Comment by UltraNix** [comment]
Fixed.

**Comment by EdyGlockenspiel** [comment]
Actually it *was* working as intended. There is a comment on wowhead saying it *shouldn't* double dip. https://www.wowhead.com/item=43825/charred-glyph#comments "No, it doesn't double dip." This comment is a reply to a comment asking the question.
