### ISSUE TITLE
festering strike

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#3340]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.wowhead.com/ru/spell=85948/%D1%83%D0%B4%D0%B0%D1%80-%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F  should always extend disease duration by 6 seconds

**How to reproduce:**
https://youtu.be/y0tfUCk7FbI?t=108 dk uses https://cata.wowroad.info/?spell=77575 after uses https://www.wowhead.com/ru/spell=43265/%D1%81%D0%BC%D0%B5%D1%80%D1%82%D1%8C-%D0%B8-%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5 and two festering strike and gets a dot duration of 45 seconds. 
on this server you will never make 45 seconds after two uses festering strike

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Maximium duration on debuffs should be 46 secs
https://youtu.be/7MpQQsJ7EL4?t=40

**Comment by UltraNix** [comment]
Fixed.
