### ISSUE TITLE
Zul'Gurub

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3341]
1.Cauldrons shouln't be useable before killing Venomancers/Gurubashi Cauldron-Mixer
![image](https://user-images.githubusercontent.com/122209088/236310491-58ddaa4d-ad2e-4901-8dab-5ea564ebeb3e.png)
![image](https://user-images.githubusercontent.com/122209088/236310500-a100cdc7-cf69-4755-be92-beaf9aebab2f.png)
![image](https://user-images.githubusercontent.com/122209088/236310515-0afca436-cdb3-4f31-a64c-ad00ddd2704f.png)
![image](https://user-images.githubusercontent.com/122209088/236310554-c69b3578-4ba7-48ef-b920-f248447b714b.png)

2.Ticki Lord Mu'lo and Tiki Lord Zim'wae are not spawning ( only can see them with gm on)
![image](https://user-images.githubusercontent.com/122209088/236310765-db2156b5-239f-4ed5-b709-26cdf86457e2.png)
![image](https://user-images.githubusercontent.com/122209088/236310813-527c850e-5cce-46dc-b1bf-913707c1f62f.png)

3.Venomguard Destroyers are not linked
![image](https://user-images.githubusercontent.com/122209088/236310913-77795100-bbf1-43b8-a378-1103f3db165b.png)

4.High Priest Venoxis
Poison clouds are ticking twice 
![image](https://user-images.githubusercontent.com/122209088/236311064-d5c583b1-d7b2-4b4f-83a3-08e302ffdbac.png)
Boss should reset afte being pulled outside of his room
![image](https://user-images.githubusercontent.com/122209088/236315640-378d3375-588a-4714-86e3-d73dac459ceb.png)

Venomous Effusion is not always dealing damage to player when being hit
![image](https://user-images.githubusercontent.com/122209088/236311198-3719aa88-dff5-415e-94c2-ba3d2689d44d.png)

5.https://www.wowhead.com/npc=52348/berserking-boulder-roller
Boulders are not always hitting player
![image](https://user-images.githubusercontent.com/122209088/236311626-a257f6a1-19b5-4bd8-90e4-6f04a80d3c29.png)

6.Bloodlord Mandokir
Chained spirits are not visible during encounter
![image](https://user-images.githubusercontent.com/122209088/236311778-a76038dd-52db-4603-8525-1bcf7706bd9c.png)

7.Ritual Tiki Mask model is wrong
![image](https://user-images.githubusercontent.com/122209088/236311872-67ebd94e-a80f-4c4a-bb9d-da2d328ed23e.png)

8.This pack should be linked and their cast should be synchronized
![image](https://user-images.githubusercontent.com/122209088/236311984-08ffcaa6-00c9-4225-b93a-717c05edfe97.png)

9.Fire is not hitting player when hugging wall 
![image](https://user-images.githubusercontent.com/122209088/236312067-3f359b12-800b-42a7-9f0f-cc4faf20012d.png)

10.Pet pathing inside Temple of Betheek is little messed, pets are running through textures

11.Most aoes are puilling boss from below
![image](https://user-images.githubusercontent.com/122209088/236312300-c81a556a-1e16-4458-b8ab-518908b43a1d.png)

12.Boss is not reseting after being pulled out of her room
![image](https://user-images.githubusercontent.com/122209088/236312386-3821b778-9a48-49e7-bfe5-8730c1ecf869.png)
She should reset at
![image](https://user-images.githubusercontent.com/122209088/236312418-bc17a5a0-ed72-46f2-8d07-ffee1c72cf7b.png)

13.High Priestess Kilnara is not casting Wail of Sorrow after reset
Vengeful Smash is not being casted by boss at all

14.Zanzil
Zanzil Fire is ticking twice
![image](https://user-images.githubusercontent.com/122209088/236312689-1976e282-07b3-4a56-b827-d16824415ea2.png)
Zanzil Zombie's and Zanzil Berserker are being spawned but are immune and not moving at all
![image](https://user-images.githubusercontent.com/122209088/236312889-4078713b-e26d-4782-ab9d-36cc870ed1af.png)
![image](https://user-images.githubusercontent.com/122209088/236312919-8f6a139c-c44d-4dd1-9c03-af38b679a229.png)

Zanzil Graveyard gas debuff is not removed after boss death, spell id  96434

15.After spellstealing buff from boss, character cannot proc this aura
![image](https://user-images.githubusercontent.com/122209088/236313171-b2be83d0-ba98-4994-a6fe-d4275c939da9.png)

16. After pushing Jin'Do to phase 2 phasing messed up group, we weren't able to see each other
![image](https://user-images.githubusercontent.com/122209088/236313313-df407b5e-4da7-40ab-9817-0e6c84ce303f.png)
17.Gurubashi Spirit is not removing Brittle Barrier from chains after hitting them with Body Slam
![image](https://user-images.githubusercontent.com/122209088/236313481-cfbd8850-652b-4c88-91e5-54843fb6f27b.png)

Those NPC's are missing loot table
Tor-Tun
Mortaxx

17.No quests are offered from npc's inside dungeon
http://cata-shoot.tauri.hu/?quest=29173
http://cata-shoot.tauri.hu/?quest=29172
http://cata-shoot.tauri.hu/?quest=29175
http://cata-shoot.tauri.hu/?quest=29241
http://cata-shoot.tauri.hu/?quest=29252
http://cata-shoot.tauri.hu/?quest=29242
18.Venomous Needlers should aggro on players who are running below them
**https://youtu.be/uNj_cowoH-g?t=36
19.Lots of trolls inside are missing humanoid + elite border
creature_template wrong for:
52441
52413
52418
52089
52414
52381
52311
52155
52402
52405
52422
52151
52323
52322
52438
52148
20.Cache of Madness

Wushoolay is not casting Forked Lighting
Also bosses are not reseting after leaving room
![image](https://user-images.githubusercontent.com/122209088/236319037-738ae875-1e46-4e72-abce-adeedf9ffaf6.png)
Gri'lek
Rupture line is hitting twice
![image](https://user-images.githubusercontent.com/122209088/236320148-82a1a287-c0e8-4954-87a5-2a934ed9600f.png)
Hazza'rah
![image](https://user-images.githubusercontent.com/122209088/236321021-d6197dea-b938-42cb-a5d3-18a242e629b7.png)
Nightmare Illusion are not moving towards players
Also they have 1+mln hp rn, they should have 3k hp
https://wowpedia.fandom.com/wiki/Hazza%27rah

**Comment by Sketish** [comment]
20.05.2023 update
1.Venomtip Needlers should aggro on players who are running below them
**https://youtu.be/uNj_cowoH-g?t=36
2.No dmg when hugging wall
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/91710b66-9e86-4574-b379-fd7b531b3ec9)
3.High Priestess Kilnara
Wave of agony frontal is not always matching boss direction.
4.Jin'do the Godbreaker
Hakkar's Chains are keep healing to full
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/b98cabc3-b947-4b01-b67a-92c221f92224)

**Comment by Sketish** [comment]
22.05.2023

1.High Priest Venoxis
Venomous Effusion is ticking 2 or 3 times in 1 sec from same pool

2.High Priestess Kilnara
She only casted once Wave of Agony

**Comment by whothatdog** [comment]
This NPC is immune to freeze (blue cauldron) he should not.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/3617134a-b9a5-4bce-90ad-f2b96a9ac343)

Dark Simulacrum should work on Zanzil's Fire
https://www.reddit.com/r/wow/comments/ietbh/three_dks_using_dark_simulacrum_on_zanzil_fire_at/?rdt=57924

Dark Simulacrum should work on Bloodletting from Mandokir
https://www.reddit.com/r/wow/comments/3jxlqp/death_knights_what_is_your_best_dark_simulacrum/

**Comment by UltraNix** [comment]
Fixed.

**Comment by whothatdog** [comment]
last ZG I done I joined after two bosses killed.
Although that, great work on fixing bugs, I wonder if you use AI/GPT to help you out coding ;-D

If I may.

That NPC seems a little-off, the damage is correct, but 'tick' too fast,
the NPC did 21k damage per second (DPS) ;-O
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/b94d393b-e989-4647-bd59-a0b0c8516394)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/eba90445-43c6-4730-bec6-553f39d97e07)

those packs are always aggro when you go up on stairs, no matter what
they shouldn't also, according to the video they should walk a bit to allow free pass.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/b1762bc0-1521-43d0-a09c-25f4de84f1e3)

Zanzil graveyard gas start to damage immediatelly, according to the video above
even when the whole ground go green animation people still have time to go green cauldron before it start damage them.

Animation is about 28:18 (?) and damage start 28:25 (?) ~ approx.
in Whitemane the damage just start immediatelly.

If I'll had the opportunity to do more ZG/ZA and I'll notice something I'll report.

again, good job!

**Comment by whothatdog** [comment]
@UltraNix the dungeon is still bugged. ---> I **recommend** to watch https://www.youtube.com/watch?v=73h45_wjP_Q
it's 4.2.0 Zul'Gurub.

NPCS(Trash mobs)

1. the NPC that protect the cauldron is giving toxic link to everyone
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/339efe77-9a1d-4234-b2de-ccb25395acdb)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/b10d30a2-c269-4bfb-b7b5-b7526d782ef5)

it tick for 7.5k~ approx, that damage is scale wrong, on videos it does like 3k, the damage is x2/2.5 higher
and should link only two players.

2. Pride of Bethekk
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/47bc223c-674f-444f-979c-08f06a609a68)
1 leap = 3 stacks.

Bethekk melee damage is way high.
23k melee, 47.8k critical?
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/5980be5f-924e-4927-8ae2-b99b3c63b5ce)

on this video => https://www.youtube.com/watch?v=LQ9AzD3olIY
If I look correctly (the font sucks) the Bethekk melee attacks melee attack for 7.2k~ approx

https://www.youtube.com/watch?v=U6xIs06CIo8
another video 7.2k~ approx

Bosses:

Priest Venoxis
1. Boss still jump to the edge/corner instead down the stairs of the platform he stands -> boss jump video 6:20
2. Bloodvenom are moving faster than what should be => video 6:10.

Mandokir.
1. his melee attacks are hitting tank for 100-150k even before reach Frenzy
tanks get one shotted, and ofc if people are not kiting and move to distance the die too.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/1fd749aa-fed1-4273-a106-6a02640959a4)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/4fd57499-b7dd-4194-885e-1094b7cee5ae)
tank get 111.3k hit
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/815521e0-1e30-4ca6-9b84-8381faa6fbd1)

watch the video at 13:21 when boss Frenzy, the damage is drastically lower.

another videos:
https://www.youtube.com/watch?v=ESH-YSeoekE
or here 
https://www.youtube.com/watch?v=pwy3j891eA4 the boss is hitting 17-20k melee.

Kilnara:
Boss abilities and damage seems very off to me.
Ravage 106k, 126k
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/fc0cd089-ec5c-4411-b371-3860b32be109)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/1464d2e7-24b4-4e40-82cc-df5d155613a6)

melee attack damage:
62k max, 162k critical
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/4f42ae22-5ace-4c7b-8051-c0c6732480cd)

compare it to videos~

**Comment by whothatdog** [comment]
Another bug:
Mandokir is using Decapitate against his current target (<= tank).
Mandokir should not use Decapitate on tank.

https://www.mmo-champion.com/threads/1293490-quot-Bloodlord-Mandokir-will-no-longer-use-Decapitate-against-his-current-target-quot

**Comment by UltraNix** [comment]
@whothatdog The best is approach is one bug - one report.
Zul'Gurub is already live on our server, so it's easier to fix bugs one by one.

**Comment by whothatdog** [comment]
> @whothatdog The best is approach is one bug - one report. Zul'Gurub is already live on our server, so it's easier to fix bugs one by one.

Hey UltraNix thanks for commenting.
You want me to open issue specificly for **each** boss?

like [Zul'Gurub] Kilnara
[Zul'Gurub] Mandokir
etc?

I prefered to report it that way in a list order
but it's up to your preference, just say.
