### ISSUE TITLE
[Deadmines] First Boss -  Glubtok Issues

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3342]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Glubtok periodically casts Fists of Flame https://cata-twinhead.twinstar.cz/?spell=87859 and  Fists of Frost https://cata-twinhead.twinstar.cz/?spell=87861 after Blinking at a party member AND resetting the aggro. Said buffs have a CHANCE of having an effect (knockback for flame, slow debuff for frost). currently it is 100% chance instead.

![image](https://user-images.githubusercontent.com/130247490/236326046-3ca5acec-e9dc-41d1-bbc7-4f2ffcd37370.png)

Upon reaching 50% health threshold, Glubtok  will blink to a fixed spot just in front of his arc. marked by a General Purpose Bunny JMF 
![image](https://user-images.githubusercontent.com/130247490/236326322-e9edf854-03ca-4ea0-bdbf-a148c6adfb18.png)

 the spot he currently teleports to is incorrect (too forward)  

![image](https://user-images.githubusercontent.com/130247490/236326501-2ed3f7d7-8d85-4691-baf6-a7f822575ad8.png)

Also, the party SHOULD NOT get frozen at all but be able to continue to DPS and / or reposition and stack for the incoming flame wall.

Flame wall - the flame wall is moving too fast. approximate guess is at least 15% too fast. 
It should also NOT have those gaps and be as wide as the whole room. 
The Flame wall also tends to bug out upon reaching a certain angle, (check video for proof) 
![image](https://user-images.githubusercontent.com/130247490/236329389-e64e76f6-ce6d-4bc4-bd6c-f8bad89f6993.png)

Fire Blossom & Frost Blossom - These adds are supposed to spawn scattered all around the room, currently they spawn in a secluded area near the middle of the room instead

Video Proof
https://www.youtube.com/watch?v=djFh3W7flM4

RETAIL REFERENCES
https://www.youtube.com/watch?v=gM7Nk7w-aC4
https://www.youtube.com/watch?v=vnc9mhr9ge4

**Comment by UltraNix** [comment]
Fixed.
