### ISSUE TITLE
Kor'geld not in game

### ISSUE THREAD

**Issue by Brutalikz** [gamefreedomgit/Maelstrom#3344]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Kor'geld is supposed to be inside the "Yelmak Alchemy and Potions shop. Tide was kind enough to spawn him for me but requested I make this report. This is my first report ever and I am unsure about the protocol and information you need. Please feel free to message me should you need more information.

Kind regards
Brutalikx

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#2746
