### ISSUE TITLE
Quest ( Twilight highlands ) Rune ruination

### ISSUE THREAD

**Issue by GM-Niamh** [gamefreedomgit/Maelstrom#3345]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rune ruination you need too destroy 4 runes inside the cave. At the end the NPC should spawn. He doesn't.

**How to reproduce:**
NPC should spawn.

**How it should work:**
https://www.youtube.com/watch?v=6YNS2CvxyZ8&ab_channel=GitGudGuides

**Database links:**
https://www.wowhead.com/quest=27744/rune-ruination

**Comment by PanJanuszek** [comment]
Fixed, PTR stage

**Comment by WhitemaneChronus** [comment]
NPC to turn in the quest is missing.
- English client / phase 1

**Comment by PanJanuszek** [comment]
Fixed, will be with next update
