### ISSUE TITLE
Seal of Righteousness & Justice damage

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Maelstrom#3347]
Seal of Righteousness tooltip says 347, does 358.
Seal of Justice says 158, does 960.
Seal of Truth says 1151 DoT, does 1151 DoT.

Seal of Righteousness swing damage is too weak.
Seal of Justice swing tooltip or damage is wrong.
Seal of Truth looks fine.

For SoR formula I used:
https://wotlk.evowow.com/?spell=21084
MWS*0,022*AP+0,044*SP

For SoJ and SoT formula I used:
https://www.mmo-champion.com/content/1670-Paladin-Cataclysm
SoJ:
MWS*0,005*AP+0,005*SP
SoT:
0,125*AP+0,125*AP

I have:
AP: 6967
SP: 2113
SoR should hit ~640. Hits half that: 358
SoJ should hit 118, and says it does that, but in fact hits 6x what is supposed to: 960.
SoT should hit 1135 DoT and does that.

**Comment by jlldarocha** [comment]
Coefficients according to EJ 4.3 thread on ret paladins:

**Seal of Righteousness**
Seal: Weaponspeed + 1.1% AP + 2.2% SP. Cannot crit.

**Seal of Truth**

Censure: (2.7% AP + 1.4% SP) per stack. At 5 stacks (13.5% AP + 7% SP).


[source](https://web.archive.org/web/20131110045846/http://forums.elitistjerks.com/index.php?/topic/109393-the-retribution-concordance-43-voice-of-the-dps/)

**Comment by Consealer** [comment]
Ok, so looks like in Cata SoR does half the damage on swing.

@jlldarocha
In SoT I ment entire Dot Damage after melee hit (5 ticks). What do you mean by "(2.7% AP + 1.4% SP) per stack"? Entire DoT damage or **per tick**? If entire then currently it hits 5x more. If per tick, then it does it now.
But more... If you ment "per tick" and SoR is ment to be better for multiple targets then it doesn't happen, because with 1 hit of SoT you place 1k dmg DoT while you deal only 350 with SoR.
It would happen if JoT DoT damage was reduced 5x. Then one hit of SoT would place a dot of 240 and SoR would hit for 350.

**Comment by jlldarocha** [comment]
Thats the tick damage, with 5 stacks.

On the same post i linked with the coefficients, the OP goes over single Vs Aoe damage, and says its only worth switching seals with more than 4 targets

**Comment by UltraNix** [comment]
Should be fixed.
