### ISSUE TITLE
Diminishing returns

### ISSUE THREAD

**Issue by Cekma737** [gamefreedomgit/Maelstrom#3349]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Diminishing returns are bad to say the least! For example Cyclone,Fear,Stuns,Polymorph reduce duration should be 50% on 2nd ,75% on 3rd and immune on 4th for next 15 sec this never happens! Category of Diminishing Returns should be checked too for example cant be a Sap for 8 sec then poly for 8 too polymorph duration should be reduced to 50% (4 sec) !

**How to reproduce:**

**How it should work:**
Should 1st CC(cyclone,fear,stun) be full 2nd reduced on 50% third reduced on 75% 4th Immune until 15 seconds have passed since the last one! Categories of Diminishing Returns should be fixed too cuz cant Polymorph and Sap be for same time (8sec) they are in same category

**Database links:**
https://www.wowhead.com/guide/diminishing-returns-in-pvp-6024

**Comment by UltraNix** [comment]
And that's how it works.
Sap and Polymorph are the same group.
https://wowpedia.fandom.com/wiki/Diminishing_returns?oldid=2883440
