### ISSUE TITLE
[Mage] Living Bomb wrongly procs impact

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3350]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** the Living Bomb CAST (and only the cast) https://cata-twinhead.twinstar.cz/?spell=44457  is proccing Impact (Talent https://cata-twinhead.twinstar.cz/?spell=12357 ) because the act of casting is being calculated as one of the damaging spells that have the chance to proc it
![image](https://user-images.githubusercontent.com/130247490/236550761-4cdf5e77-f54f-4a81-8475-86e22d879cd8.png)

**How to reproduce:** Cast Living Bomb Repeatedly

**How it should work:**
Living bomb Should only be able to have a chance of proccing Impact with the end of the effect, the explosion. 

Video Proof

https://youtu.be/dMcRuJ2dmTs

**Comment by triceratopsrider** [comment]
Its not proof. Proof its something that says from cataclysm retail, that impact shouldnt work that way. Bomb is a damaging spell, and it cast proc combust. Its a minor change, wont affect mages at all basically, but to "confirm" something you should have evidence of that.
