### ISSUE TITLE
Zul'Aman

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3351]
1.Those quests are not being offerec by NPC at start:
https://www.wowdb.com/quests/29217-the-captive-scouts
https://www.wowdb.com/quests/29186-the-hex-lords-fetish

2.There is some cursor issue when moving it to Witch Doctor
https://www.youtube.com/watch?v=9pMMT3YHp6w&ab_channel=Smite

3.Tectonic Plating is not procing from player auto attacks
![image](https://user-images.githubusercontent.com/122209088/236549998-d893a9f9-7c96-493b-8517-cd46327984bf.png)

4.Amani Eagles are not coming during gauntlet
![image](https://user-images.githubusercontent.com/122209088/236550326-c42dde48-7a89-4afc-bf52-87079892b9f3.png)
Retail video: https://youtu.be/B2sGDPIP0FA?t=130

5. You can open cages before killing bosses, there is no chest with loot, but shouldnt be able to do that before boss death
![image](https://user-images.githubusercontent.com/122209088/236550804-218404e1-fde6-472e-a8b1-7b60e3cf1d3f.png)

6.Nalorakk
Brutal Strike damage is reduce by armor when it shouldn't
![image](https://user-images.githubusercontent.com/122209088/236550932-c2d33ee6-3a77-4253-9d5f-ae9a022846af.png)
![image](https://user-images.githubusercontent.com/122209088/236550947-2e349b84-bc81-4ed3-bd10-fbed4e42fa8b.png)

7.Amani Flame Caster is buffing him with Blazing Haste while in cc.

8.Pack is not linked
![image](https://user-images.githubusercontent.com/122209088/236551152-4cf7d8d4-4b20-416f-9e6c-af9909b1b9d8.png)

9.Frontal is not matching visual
![image](https://user-images.githubusercontent.com/122209088/236551186-dc348e0f-dda9-44de-b58b-62adee8d7cb9.png)

10.Amani'shi Guardian are not using dispell
https://wowpedia.fandom.com/wiki/Amani%27shi_Guardian

11.Pet can move through door and pull Halaazi
![image](https://user-images.githubusercontent.com/122209088/236551532-df3cb036-72ef-4226-8fe1-c124b3aada2a.png)

12.Halaazi
Refreshing Water totem should have 100k
![image](https://user-images.githubusercontent.com/122209088/236551726-ad52bbf5-785b-461a-b6e4-3f7bea0eb30b.png)
![image](https://user-images.githubusercontent.com/122209088/236551752-0354edf9-7c40-4046-b753-e8853c7e9e1a.png)

13.Crocolisk are not linked with Beast Tamer
![image](https://user-images.githubusercontent.com/122209088/236551843-3baa089d-fd77-41b1-a8f7-149245eff39b.png)

14,Amani'shi Beast Tamer are not using Domesticate
https://wowpedia.fandom.com/wiki/Amani%27shi_Beast_Tamer

15.Amani'shi Berserker are not spawning before temple after killing animal bosses
![image](https://user-images.githubusercontent.com/122209088/236552330-03db5d45-23cb-4ea1-aa16-454e34866ac1.png)
Also they arent using any abilities.

16.Berserkers should be linked
![image](https://user-images.githubusercontent.com/122209088/236552470-ad5c1603-be6a-4d9e-acb6-2cd3717b3cc1.png)

17.Blood worms are not moving towards boss.
![image](https://user-images.githubusercontent.com/122209088/236552551-48b3e23d-c7dd-4062-9a20-a34b599a98bf.png)

18.Amani Snakes have 142mln hp instead of 23,247k hp
![image](https://user-images.githubusercontent.com/122209088/236553493-44f56ba7-d780-4675-ac79-91aa640f92ee.png)
https://cata-twinhead.twinstar.cz/?npc=24338

19.Event with Amani'shi Savage is not working at all
https://youtu.be/b3yeYGEgTgQ?t=1603

20.Amani'shi Savage are not linked to Daakara

21.Currupted Lighting Totems have 100+mln hp instead of 25k hp
![image](https://user-images.githubusercontent.com/122209088/236554551-d6481e6d-4820-485c-ab2c-5c4ebba27776.png)

22.https://www.wowhead.com/object=186634/gold-coins#comments are not having any gold when looting

**Comment by Sketish** [comment]
20.05.2023 update

1.Eagles during gauntlet are pulling are mobs when gong downstairs
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/7ba73b67-9756-4487-bc57-c5c1f85c18b7)
Also eagles should keep spawning till Amani'shi Tempest is alive

2.Amani'shi Flame caster
Is casting Conflagration during cc

3.Jugernnaut is not linked to whole pack
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d7bdc72f-05d5-48f5-bd8d-7a260d278ae7)
4.You can still pull Halazzi out of his room
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/6cd32aac-c875-4cd3-bbb8-4b9c6b28ebc2)
5.Refreshing Water totem should have 100k currently it has 10,2k
6.Boss stop aa when in dragonhawk form
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/95d0bab2-769d-4bfd-a22c-dbf296bc93b8)
7.after reseting last he becomes dummy
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/49a2145d-9271-46dc-90a7-ff4ec78e843c)
8.Akil'zon and Nalorakk should add 5 min to timer before execution, currentlly they are adding less

**Comment by Sketish** [comment]
22.05

1.Juggernaut is not linked
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/9fa15a1e-7557-4d7f-be93-10a4dac85f9a)

**Comment by whothatdog** [comment]
I also forgot to say I completed that run with 2 hunters, me (as dispeller) I don't think it possible to do this run without
trapping 1/2 NPC and dispelling.

Amanishi Frenzy before 25-35% hp.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/186f7c65-c863-4c36-9919-39fbeab43990)

pack on start damage (9-12k)
the bleed effect hit for 10k.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/87025f6d-4b92-4d70-bbc4-52f6d698801d)

Amani'shi Flame Caster using Configuration (disorienting ability) 2-3 times in like 10 sec.

**Comment by UltraNix** [comment]
`Another problem is with the bird 'Caster' they use their Blazing buff too early and they spam it every like 10-15 sec.`
Give me exact name/id of that mob.

**Comment by UltraNix** [comment]
Fixed.
