### ISSUE TITLE
Titanium Seal of Dalaran

### ISSUE THREAD

**Issue by SexyPancake** [gamefreedomgit/Maelstrom#3353]
Titanium Seal of Dalaran
https://wowpedia.fandom.com/wiki/Titanium_Seal_of_Dalaran

The item currently only does the animation of flipping a coin without the associated emote.

From wowpedia, it should do the follow : 

You only need to right-click on the coin to flip it. You can do so while moving, but you can only stand in place to catch it.

<Name> casually flips <his/her> Titanium Seal of Dalaran.
If caught it will result in either:

<Name> catches the coin heads up!
<Name> finds the coin face down for tails!

Here is also a screenshot of how emote should look like ingame ;
http://666kb.com/i/b2cctoiaccjv88pr7.png

**Comment by Wick3dmind** [comment]
yes it doesnt work atm here tried it

**Comment by Afgann** [comment]
fixed
