### ISSUE TITLE
[Deadmines] Vanessa VanCleef Encounter

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3354]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Nightmare Part** During the nightmare, you get to fight weakened down versions of the bosses already fought, with some twists

Glubtok is spawned at top for the mini dialogue with Vanessa, but when the encounter starts he should disappear and appear at the door, where the fight happens. players have to dodge fire to get to him. At the moment Glubtok spawns on top and makes his way down there, plus, the players are currently able to stun him to prevent him from moving. not intended

Helix fight is a little bugged. upong engaging, the room should be filled with spiders, and of various dimensions, even a gigantic one. At the moment , upon engaging, only a few spiders spawn after a few seconds, small ones, and only small ones keep spawning indefinitely, but never in a proper number. not much of a nightmare.

Foe Reaper 5000 - the "super mario" part where u dodge the rotating lightning spheres before reaching the boss, is bugged in the spheres themselves, as they have far more reach than normal, making the journey to the boss very tedious and quite deadly.

The Ripsnarl rescue - The players are supposed to rush in to save the members of the Harrington Family, who are being attacked by the worgens. Players are encouraged to be fast, and gain speed buff for every rescue. The players are also supposed to be able to heal said npcs to prevent their death.

At the moment, the npcs are perfectly safe cause they do not get attacked at all. they also don't respond or say anything to the players once the worgens get wiped out. but the progress counts.

Even the last npc, Calissa Harrington, who has a debuff, is not worried at all cause she is regening hp to 100% .
![image](https://user-images.githubusercontent.com/130247490/236575353-320ce068-d981-4818-aa69-61881475b3e9.png)

The enemy npc, James Harrington is CORRECTLY not attacking the players as he is there in the middle of trying to kill Calissa
this is intended. 

**Vanessa Part** Upon killing James Harrington, the players exit the nightmare and can engage Vanessa. This works correctly.

**EXTREMELY IMPORTANT** Should the players wipe, the whole nightmare event resets and the players have to do EVERYTHING again. this is not intended. the players that complete the nightmare event should NOT have to redo everything.

**ADDENDUM** Should the players Reset the encounter by walking off the ship bridge, or just resetting in general, Vanessa will go back to her original position in the chamber and NOT run into the players, resulting in free DPS for ranged players. eventually vanessa will go back being "active" after the bombs mechanic.

**Adds** Adds spawn near the chamber entrance and will stay there and act as normal mobs, meaning that if the players are far enough they will not get aggroed. this is not intended. the adds are spawned to assist Vanessa and should get aggro immediately.

**Bombs Part** Vanessa will use the detonate charges mechanic twice, one at 50% and one at 25% . Upon Seeing the announcement (which has a typo btw) 
![image](https://user-images.githubusercontent.com/130247490/236576976-2e3576bc-15e2-45b4-831b-ced6d0ac3634.png)
they have around 4-5 seconds to grab the ropes before the explosions happen. At the moment, the explosion happen too soon, giving players little time to relocate.

**UPON DETONATING** the charges, when players come back to the ship after swinging from the ropes, they find the bridge in flames with only the middle of the ship that isn't. This is currently not happening as the whole ship is not on fire after the charges detonate.

Video Reference https://www.youtube.com/watch?v=RAC5GmKa0jg
https://www.youtube.com/watch?v=tkNxQ176Bhs

**Comment by triceratopsrider** [comment]
Yeah, some abilities dont work, raid bosses dont work, but vanessa in deadmines is "critical". Lol,why do you even have rights

**Comment by staR1336** [comment]
> Yeah, some abilities dont work, raid bosses dont work, but vanessa in deadmines is "critical". Lol, why do you even have rights

Once again, who hurt you little boy?

I do what i must and got asked to.

**Comment by UltraNix** [comment]
Fixed.
