### ISSUE TITLE
[Item] The Flag of Ownership

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#3355]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Flag of Ownership has the following issue:

1. In current state, the flag can **_only_** be planted on an unreleased, targeted, enemy corpse. If the enemy player releases spirit the flag cannot be planted as you cannot target them. 

**How to reproduce:**
https://youtu.be/mh2bhMdNTCQ?t=40

There is also a similar report on Twinstar, here: https://cata-twinhead.twinstar.cz/?issue=10687

**How it should work:**

1. The player _**does not**_ need to be targeting the corpse in order to plant the flag. The flag should automatically plant, when activated, on the corpse nearest the player. 

2. The flag may be planted even after the enemy player has released their spirit.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=38578

**Comment by Afgann** [comment]
fixed
