### ISSUE TITLE
WE cant transmog  [Knight-Captain's Lamellar Breastplate] ITS BUGGED 

### ISSUE THREAD

**Issue by elunee12** [gamefreedomgit/Maelstrom#3356]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Noone can transmog  [Knight-Captain's Lamellar Breastplate] its bugged since the start i talk to gms noone could fix it
**How to reproduce:**

We should be able to transmog it 
**How it should work:**
Its bugged it should be able to transmog it

**Database links:**

**Comment by Sketish** [comment]
You have to buy replica from area 52 then you are able to transmog.
![image](https://user-images.githubusercontent.com/122209088/236612528-31dbd7bc-79f4-42f9-bc5b-b5525f2879ac.png)
![image](https://user-images.githubusercontent.com/122209088/236612546-b70faf3d-1a69-4894-ac34-321fca2e906d.png)

**Comment by elunee12** [comment]
Well its not fixed yet u still cant tmog it

**Comment by EdyGlockenspiel** [comment]
That is blizz-like. None of the lvl 60 rare/epic pvp items from vanilla are or have ever been mogable. The Replica versions bought from area 52 netherstorm, which require something like 1800 RBG rating *are*.

**Comment by UltraNix** [comment]
It's not a bug.
https://www.wowhead.com/item=23272/knight-captains-lamellar-breastplate#comments:id=1585503
