### ISSUE TITLE
Sweeping Strikes not working/duplicating damage on Council

### ISSUE THREAD

**Issue by nezterx** [gamefreedomgit/Maelstrom#3357]
https://www.twitch.tv/videos/1786008862

Sweeping Strikes does not deal damage as it's supposed to on Council.

If you look closely in the video posted above, you can clearly see that the damage from Sweeping does not occur.
First Sweeping Strikes fresh into P2 will also clearly show the inconsistency of Sweeping damage output.

It can all be verified with MSBT.

**How to reproduce:**
Pop Sweeping strikes in p1 and p2 with both bosses stacked.

**How it should work:**
<html>
<body>

Your melee attacks strike an additional nearby opponent. Lasts 10sec.
--

</body>
</html>

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=12328

**Comment by Sketish** [comment]
This video is from one month ago .Tested today and all sweeping strikes were hitting 2nd boss. 

https://www.youtube.com/watch?v=geN9ueoYBGM&ab_channel=Smite
https://www.youtube.com/watch?v=RY-nLZ2w_oY&ab_channel=Smite
