### ISSUE TITLE
[Achievement] Jugger Not

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#3358]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Meeting the achievement criteria does not grant the achievement. 

**How to reproduce:**
Win the Battle for Gilneas by 100 points or less. 

Proof: 

2000 to 1980 -- no achievement,

![](https://i.imgur.com/yB0JOgM.jpg)

**How it should work:**
Winning the Battle for Gilneas by 100 points or less should grant the achievement.  

**Database links:**
https://cata-twinhead.twinstar.cz/?achievement=5255

**Comment by UltraNix** [comment]
Fixed.
