### ISSUE TITLE
Mage Bug

### ISSUE THREAD

**Issue by zsolti15a** [gamefreedomgit/Maelstrom#3359]
A lvl 80 fire mage in Blackrock Cavern almost one hitted the first boss (Rom'Ogg).
He made it alone and the boss died under 2-3 sec. 

I asked it from another fire mage and he said you should use well the combustion. 
So there might be some bug with it. Please fix it, it makes dungeons unenjoyable.

**Comment by triceratopsrider** [comment]
You should at least show combat logs or screen from recount/scada/details with the skill that mage dealt damage with. Its impossible to find bug with your words
