### ISSUE TITLE
[Archaeology]Zul`Mashar Digsite bugged

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#3360]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Eastern Plaguelands digsite, Zul`Mashar Digsite is bugged! 
You should be able to do it without problem but if your unlucky  (like me) one of the artifact spots in the north east of this digsite is bugged and red thing from survey points outside of the digsite. 

**Database links:**
https://wowpedia.fandom.com/wiki/Zul%27Mashar

**Comment by UltraNix** [comment]
Fixed.
