### ISSUE TITLE
Wrong heirlooms stats

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Maelstrom#3361]
At lvl 14:
Polished Helm of Valor: 5 STR, 7 STM, 3 CR, 3 HR
Polished Legplates of Valor: 5 STR, 7 STM, 3 CR, 3 ER
Polished Breastplate of Valor:  5 STR, 5 STM, 5 CR
Polished Spaulders of Valor: 5 STR, 5 STM, 3 CR

Burshished Helm of Might: 5 STR, 7 STM, 3 PR, 3 ER
Burshished Legplates of Might: 5 STR, 7 STM, 3 CR, 3 ER
Burshished Breastplate of Might: 5 STR, 7 STM, 5 D
Burshished Spaulders of Might: 4 STR, 6 STM, 4 PR

Legplates give the same stats. Is that correct?
I think Legplates of Might should not give Crit but Parry, like Helm of Might does. Just like the Valor Legplates copy Valor Helm stats.

**Comment by Readie** [comment]
Burnished Legplates of Might stats should be parry / hit:

https://web.archive.org/web/20121202110135/http://www.wowhead.com/item=69888/burnished-legplates-of-might

**Comment by varjla** [comment]
Right now, both items are wrong Polished Breastplate of Valor (DPS), that has the same stats as Burshished Legplates of Might(TANK):
5 STR, 7 STM, 3 HR, 3 EX

**Comment by UltraNix** [comment]
#4164
