### ISSUE TITLE
Death's Advance

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#3362]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**After restoring the green rune Death's Advance should continue for another 3-4 seconds

**How to reproduce:**

ANY VIDEO FROM THE OFFICIAL SERVER
https://youtu.be/yiii5ultT_Q?t=23
https://youtu.be/0SXB4zPiOe8?t=26

**How it should work:**
fast fix 10/10

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
