### ISSUE TITLE
Mana regeneration (any class)

### ISSUE THREAD

**Issue by theHalta** [gamefreedomgit/Maelstrom#3363]
**Description:**
Mana regeneration on any class is not acting as expected, with the count regressing every few milliseconds.

**How to reproduce:**
Cast any spell and observe your mana go "backwards" every few milliseconds.
Example:
![regen](https://user-images.githubusercontent.com/16519808/236641274-1a8555bb-7ffe-4791-a7db-3d5a12fa7851.gif)

**How it should work:**
Mana regeneration should be continuous without regressing.

**Comment by UltraNix** [comment]
Fixed.
