### ISSUE TITLE
Huddle pet dk

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#3364]
123

**Comment by Sketish** [comment]
Please provide any source instead of saying how it was working on other private servers

**Comment by bonfax4** [comment]
@Sketish https://cata-twinhead.twinstar.cz/?spell=47484 i mean my understanding reading ng this is that huddle used under dark transformation loses the "channel effect" ( which means it should still be able to attack ) if that what he's trying to say, but i don't what even is being reported here.

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/1156068-Unholy-dk-pvp-guide-4-3-4?highlight=Huddle

 

> Your ghouls damage is very important, aswell as your gargoyle, to get the best profit from your ghoul i suggest you control it by yourself, to control the ghouls stuns, when your ghoul is transformed with dark transformation you can use huddle, because when transformed the ghouls huddle doesn't prevent him/(her?) from dealing damage! You can use a simple macro like /cast huddle .

**Comment by Sketish** [comment]
Thank you for providing sources

**Comment by UltraNix** [comment]
Without Dark Transformation:
![WoWScrnShot_051023_213702](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/e68e37ca-de27-43b2-93d7-b91e61165e43)
Pet is staying and channeling - cannot move and attack.

With Dark Transformation:
![WoWScrnShot_051023_213828](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d10b258f-2e3c-463b-bc17-d1398154ee85)
![WoWScrnShot_051023_214000](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/8df739d0-8af0-445e-9514-1578bb6c3cfe)
Pet is following and attacking under the Putrid Bulwark effect.
Nothing's bugged here,

**Comment by bonfax4** [comment]
it works for the otehr abilities for example. casting claw does sweeping claws, leap does Shambling rush, etc. 

https://www.wowhead.com/spell=63560/dark-transformation#comments

> Claw replacement - [spell=91778 domain=cata]
> Gnaw replacement - [spell=91797 domain=cata]
> Leap replacement - [spell=91802 domain=cata]
> Huddle replacement - [spell=91837 domain=cata]

**Comment by bonfax4** [comment]
https://youtu.be/N6y5BsfQQGE?t=491 Also the cds seem to be shared just in case you need to look over that as well. Look how he auto casts gnaw and transforms but gnaw is still on cd.

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
@UltraNix Still had monstruous blow and Gnaw on my pet bar after the fix. Can use both separately still. Removing the updated ghoul abilities from the bar fixed the issue and casting /huddle and /gnaw do the updated version by default. Prob need a way to reset every ghoul bar spell to their default or smthing. Could possibly be an issue with chars that had the bar like i linked before the fix.

**Comment by UltraNix** [comment]
Should be fixed within the next update.
