### ISSUE TITLE
Beastmaster Spec in Hunter, talent not working well

### ISSUE THREAD

**Issue by Kentaro14** [gamefreedomgit/Maelstrom#3366]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hunter Beast Spec Talent is not working well. Just in case you should look at beastmaster spec overall, because it is not doing as well as it should be in pve in any case, id appreciate that.

**How to reproduce:**
![image](https://user-images.githubusercontent.com/58055418/236648209-63225688-a185-4786-8d9f-49fcbb5f8420.png)
Use the talent but the pet is not getting the +10 focus from the talent.
![image](https://user-images.githubusercontent.com/58055418/236648225-fe1f9f79-a437-448e-8c6e-6829b7b7f85c.png)

**How it should work:**
The focus bar from the pet should be in 110 the same as the hunter has.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
