### ISSUE TITLE
Squirrel's do not spawn

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3368]
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?npc=1412)

**Description:**
I'm almost done with World Explorer and have been doing some achivements like "To All The Squirrels I've Loved Before".
I can find all critters but there's not a single squirrel anywhere.

**How to reproduce:**
Fly through Ashenvale for example and spam /target Squirrel

**How it should work:**
A Squirrel should be found somewhere :P

**Database links:**

**Comment by Wick3dmind** [comment]
You can find a squirell in Dalaran or Elwyn forrest

**Comment by DorizarN** [comment]
Was not lucky with Elwyn Forest, tried a few laps. Though there was 1 in the middle of Dalaran, thanks!
