### ISSUE TITLE
Zandalari Menace Quest Line <H> 

### ISSUE THREAD

**Issue by ysiu15** [gamefreedomgit/Maelstrom#3369]
1.Bwemba doesn't always follow the player (leaving from the Horde village, the NPC stopped).

2. Serpents and Poison - healing 1 mob counts as 3 (sometimes 1 for 1). It's easy to see which one gives more because it uses more lines of dialogue. As Horde, you can heal Alliance mobs (to be checked if it should be this way). 

3. Bwemba doesn't spawn even after relogging, you have to fly to another zone for him to spawn.

4. Spirits Are With Us - the mob runs in the bonfire instead of standing in place and talking . https://www.youtube.com/watch?v=mbjT_DFUWnk&ab_channel=GitGudGuides

5. The Hunter's Revenge - killing the mob did not trigger the NPC dialogue and did not complete the quest. At Bwemba, a yellow "complete quest" marker appears, but it cannot be completed - IT DOES NOT WORK. https://www.youtube.com/watch?v=TcfvYnYmruM&ab_channel=GitGudGuides

6.Follow That Cat - due to the broken previous quest, the NPC does not spawn and does not run away. The quest is not completed when approaching the NPC. https://www.youtube.com/watch?v=1yOfuTiykzY&ab_channel=GitGudGuides

7.Mauti - the quest does not add automatically, after killing the cat, the NPC that appears runs in place. https://www.youtube.com/watch?v=S0wWfvwqnSo&ab_channel=GitGudGuides

8.After completing Bury Me With Me Boots..., Some Good Will Come cannot be done. The NPC disappears.

9.Defend Grom'gol - there is no event with the appearing mob and Bloodlord Mandokir. When we fly to the village, the fight is already ongoing, a typical 3-minute AFK quest. https://www.youtube.com/watch?v=qU26yGNTQy4&ab_channel=GitGudGuides

10.Voodoo Zombies - after killing the zombie, it changes its model to Infernal. Those that don't count towards the quest (which should be ) don't change their model.

11.Bad Supplies - Zanzil stands and talks, but he should also move his arms.

Overall, Bwemba bugged only at the very beginning and then flew normally.

**Comment by ysiu15** [comment]
1. Bwemba doesn't always follow the player (leaving from the Horde village, the NPC stopped). Bwemba spawn after relog
2. Serpents and Poison -  You cannot heal NPCs (vendors) in the village - https://www.youtube.com/watch?v=z20ffgwn8mk&ab_channel=GitGudGuides
3. Follow That Cat - Grent Direhammer keeps running with us all the time, he should disappear
4. Panther Cub - The cat still has an infinite (can be repeated indefinitely) quest for a pet
5. Defend Grom'gol - When we fly to the village, the fight is already ongoing, a typical 3-minute AFK quest. https://www.youtube.com/watch?v=qU26yGNTQy4&ab_channel=GitGudGuides
6.To Hardwrench Hideaway - Bwemba gets lost during the gryphon flight, and after arriving at the village, he doesn't appear. Relogging is required
7.Voodoo Zombies- It's not a bug. NPCs often use the same dialogue path multiple times (there is variety, but occasionally there are 5 identical ones in a row)


The quest chain overall works fine, with no major bugs except for the occasional issue where Bwemba doesn't appear.

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3595
https://github.com/gamefreedomgit/Maelstrom/issues/3596
https://github.com/gamefreedomgit/Maelstrom/issues/3597
https://github.com/gamefreedomgit/Maelstrom/issues/3594
Bury Me With Me Boots...
