### ISSUE TITLE
Minor Inscription Research didn't grant skill up

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Maelstrom#3370]
Level 14. Inscription 75/150.
Performed Minor Inscription research (orange). Did not grant skill up.
Next day:
Inscription 82/150
Performed Minor Inscription research (orange). Did not grant skill up.

And it's not like it "failed". I learned new glyph and the materials were used.
At this level it should always grant skill up, up to 125:
https://web.archive.org/web/20121118005858mp_/http://www.wowhead.com/spell=61288

**Comment by UltraNix** [comment]
Fixed.
