### ISSUE TITLE
Lack experience in the Herbaslim/Mining profession.

### ISSUE THREAD

**Issue by ysiu15** [gamefreedomgit/Maelstrom#3371]
**Description:**

We don't receive experience points for gathering rocks and plants.

**How to reproduce:**
Gather rocks and plants, and observe the experience bar

**How it should work:**
We should receive experience points for each rock/plant we gather.

**Database links:**
https://www.youtube.com/watch?v=1C6Qwms2c_Y&ab_channel=TotalBiscuit
https://wowwiki-archive.fandom.com/wiki/Formulas:Gather_XP#Basic_Principles_Herbalism_and_Mining

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/236848396-179cdba1-1e68-495c-b02d-426ab5d3f559.png)
Everything works okay.

**Comment by ysiu15** [comment]
![WoWScrnShot_051423_202040](https://github.com/gamefreedomgit/Maelstrom/assets/11962388/2f8853b6-7a8d-471d-881c-b17cf98262f9)
Where EXP ?

**Comment by UltraNix** [comment]
@ysiu15 What's your skill in herbalism?

**Comment by ysiu15** [comment]
525 But beffore u say ,, So thats why u dnt get exp " look at this 12:30 - https://www.youtube.com/watch?v=LTiKwWxQ0iw&ab_channel=TarouWoWGuides   , Pyrite Ore - 525 Skill

**Comment by UltraNix** [comment]
Fixed.
