### ISSUE TITLE
Cooking Trainer doesn't train you :(

### ISSUE THREAD

**Issue by LynWanderer** [gamefreedomgit/Maelstrom#3372]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

"Cookie" McWeaksauce, Cooking Trainer and Supplies, doesn't teach you Cooking and doesn't sell supplies.

**How to reproduce:**

- Speak to "Cookie" McWeaksauce in Odeysus Landing - Azuremyst Isle
- None of the menus work.

**How it should work:**

"Cookie" is the Draenei starting area trainer for Cooking, and also sells some reagens.

**Database links:**

https://www.wowhead.com/npc=17246/cookie-mcweaksauce

**Comment by Afgann** [comment]
fixed
