### ISSUE TITLE
[Quest][Twilight Highlands][NPC] High Shaman MacKilligan not found

### ISSUE THREAD

**Issue by Exorcista** [gamefreedomgit/Maelstrom#3376]
**Description:** the npc: https://www.wowhead.com/npc=46885/high-shaman-mackilligan for the quest: https://www.wowhead.com/quest=28875/bring-down-the-high-shaman is nowhere to be found on the "map waypoint" or any of the camps

**How to reproduce:** go there and search for him

**How it should work:** He should be there or arround like in: https://www.youtube.com/watch?v=F0-UGFVnH6M

**Comment by Exorcista** [comment]
writing again to say he was inside the Dragonmaw clan kinda under the map but managed to pull him out, he was inmobile, prob some dude kited him there...

**Comment by Sketish** [comment]
Checked today, and mob is placed correctly
