### ISSUE TITLE
[Death Knight] Blood Tap additional rune BUG

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3377]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This report was already created, but closed for some reason. (Maybe author accidently did it). The spell author refers to should be blood tap.
https://github.com/gamefreedomgit/Maelstrom/issues/3332
If you have all of your runes on cd, Blood Tap activates 2 runes instead of one.
Works for unholy and blood. Frost already has 2 death runes instead of blood runes.

**How to reproduce:**
Use blood tap with all of the rune on cd.

**How it should work:**
It should only activate a blood rune and convert it into a death rune.

**Database links:**
https://www.wowhead.com/spell=221699/blood-tap

**Comment by UltraNix** [comment]
Cannot reproduce it. All runes on cd (even frost and unholy) and still only one blood rune is converted.

**Comment by UltraNix** [comment]
Fixed.
