### ISSUE TITLE
Mining node underground hyjal

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#3379]
**How to reproduce:**
![image](https://user-images.githubusercontent.com/36106057/236884148-d94d91f8-463f-4284-bd4d-a5647a74ac3d.png)
inside rock
![image](https://user-images.githubusercontent.com/36106057/236884283-36a0ad7f-41e2-4a64-8e3e-590ee42fe35e.png)
![image](https://user-images.githubusercontent.com/36106057/236885148-3723e30d-7d4f-4ac4-bf29-efe8405322ae.png)

**How it should work:**
this mining node should not be inside rock players have no access to it

**Comment by UltraNix** [comment]
Already fixed.
