### ISSUE TITLE
[Priest] Shadowy apparitions

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3380]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**Doing all these tests using shadow word pain and running around which should increase proc chance to 60% per tick.**

- Spell has an odd behavior that i can't replicate with 100% accuracy but sometimes you see the spawn as an elemental for like half a second with no actual apparition showing up and moving. Might have to do with pathing messing up somehow and they're underground possibly ??

- The apparition limit is 4 but i could never get more than 3 up at once in one target after 1 hour of testing and running which should be unlikely ( @12% chance to have 4 up and this involves me running away far enough and even refreshing pain and still running further enough to almost get a 8 ticks rolling before one apparition hits the target) but this could be attributed to bad rng. Only few times where i could get 4 up at once is when i begin combat after stopping and multidotting

- Apparition "counter" just doesn't seem to reset after the apparition hits the target. Test this starting combat with dummy and proccing a few apparitions, then multi dot and keep running. Rare that i could proc more than 2 even though i had SWP up on 6-7 targets, **which is **very very** unlikely**. Feels like there's some sort of hidden cooldown. This might be what's causing that weird elemental behaviour i mentioned earlier on the 1st point.

http://web.archive.org/web/20111126012418/http://www.wowhead.com:80/spell=78204#comments

Seeing here as somebody saying they have a 20sec uptime, I'm very inclined to believe some are spawning but are underground or bugged in some way, limiting the amount you can have up at a time if that's how they currently work.

**How to reproduce:**

Go to dummy area and test away. This should be easier for a dev to test with a lot of haste.

**How it should work:**

Should be able to see scenarios where 4 apparitions are up more often than currently. Possibly these bug could be even hindering single target dps when this bug occurs and prevents apparition procs. I can see this being an issue in pvp as well where you run more often

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=78202

**Comment by UltraNix** [comment]
Fixed.
