### ISSUE TITLE
Atramedes - Sonic Breath

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3381]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Does not deal damage, does not increase sound. Not working mechanic, was fine two weeks ago.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/spell=78100/sonic-breath?dd=6

**Comment by UltraNix** [comment]
Fixed.
