### ISSUE TITLE
Lost in the Darkness quest cannot be completed

### ISSUE THREAD

**Issue by desocx** [gamefreedomgit/Maelstrom#3383]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
One you free orc sea dogs from being trapped in the webs, they dont count towards your quest counter so the quest cannot be finished, the quest is needed to continue with the silverpine forest quests.

EDIT: actually it only counts 1 after every 3 or so

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=27093/lost-in-the-darkness

**Comment by PanJanuszek** [comment]
fixed 25.04.2024

40% chance to spawn orc
