### ISSUE TITLE
Huge Resto Druid Bug

### ISSUE THREAD

**Issue by Qabany** [gamefreedomgit/Maelstrom#3384]
A huge bug for Resto Druids is that the game doesn't show the CD on Nature's Swiftness spell..I thought I could fix that by using WeakAuras to show me when it's off CD but still didn't work cuz apparently the the whole game doesn't read it..there is literally NO way of finding out the remaining CD on the most important spell in the spec..please this is urgent and hopefully easy to fix 😭

**Comment by UltraNix** [comment]
@Qabany Please, more info. Show us some screenshots of that bug. What talents do you have?
![WoWScrnShot_050923_091336](https://user-images.githubusercontent.com/80540499/237021990-f6145a05-4b36-435a-921b-8132d8d25372.jpg)
![WoWScrnShot_050923_091339](https://user-images.githubusercontent.com/80540499/237021999-fd7d3f31-0b40-4e95-bbcb-2247eaac5e2a.jpg)

**Comment by bonfax4** [comment]
@UltraNix you have to equip the glyph too

**Comment by bonfax4** [comment]
Healing touch major glyph, my bad

**Comment by Qabany** [comment]
apologies for my late response..as a fellow played mentioned when we equip the major Glyph of Healing touch the CD no longer track at all..not only visually but the client itself wont track it evident by the lack of tracking when assigning a WeakAura to it..the WA shows that its always off CD when I just used it..
![ns](https://github.com/gamefreedomgit/Maelstrom/assets/132952255/dab28f7b-f755-4d20-91cb-8860baff07e1)

**Comment by UltraNix** [comment]
Fix is on the way.

**Comment by UltraNix** [comment]
Fixed.
