### ISSUE TITLE
Skullcrusher the Mountain Bug

### ISSUE THREAD

**Issue by Dushkanu** [gamefreedomgit/Maelstrom#3385]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Quest not changing parts

**How to reproduce:** just do the quest

**How it should work:** skullcrusher should be hostile

**Database links:**

**Comment by UltraNix** [comment]
#1960
