### ISSUE TITLE
Bug del ascensor en mechanar

### ISSUE THREAD

**Issue by DualityFM** [gamefreedomgit/Maelstrom#3386]
hoy estuve haciendo esta mazmorra MECHANAR pero al momento de ir al segundo nivel el ascensor desaparecía al acercarme, lo mismo pasa en modo heroico.

**Description:**
al momento de al primero boss y a los respectivos elites se desbloquea la entrada para el segundo nivel pero al momento de acercarme desaparece el ascensor

**How to reproduce:**
 https://www.youtube.com/watch?v=PSs3r7u8e9I     
así esta actualmente

**How it should work:**
https://www.youtube.com/watch?v=YVTiEpZ3uHU
aquí un video de referencia como debería funcionar ( a partir del minuto 1:40)

**Database links:**
https://www.youtube.com/watch?v=YVTiEpZ3uHU

**Comment by Sketish** [comment]
Please translate report to english

**Comment by Exorcista** [comment]
> Please translate report to english

today i was doing mechanar but upon reaching the elevator for the 2nd boss , the elevator vanishes when i reach it, it happens both on HC and Normal Mode

Description: elevator should work upon killing 1st boss and clicking the cache near the door to it

How to reproduce:
**heres how its working on this server**

https://www.youtube.com/watch?v=PSs3r7u8e9I


How it should work:

https://www.youtube.com/watch?v=YVTiEpZ3uHU (from minute 1:40)

**Comment by UltraNix** [comment]
#2052

**Comment by jlemieux** [comment]
@UltraNix any update on this one? i want to buy whitemane+ for transmog, but need to be able to get the gear first :D
