### ISSUE TITLE
Chimaeron (10N) Feud cast ending prematurely while Bile-O-Tron remains disabled

### ISSUE THREAD

**Issue by kekonomics** [gamefreedomgit/Maelstrom#3387]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Chimaeron (on 10 player normal difficulty) Feud channels ending prematurely (roughly 5-10 seconds in) while the Bile-O-Tron is disabled, which effectively breaks the fight and causes raid members to be one shot.

**How to reproduce:**
Fight Chimaeron until he begins casting Feud. Note that the Feud cast ends prematurely (~5-10 seconds in) while the Bile-O-Tron is still down.

**How it should work:**
The Feud cast should last the full 30 second duration, and the Bile-o-Tron should be back up at the same time that Feud ends.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=43296

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Chimaeron
```
Offline phase details
Every few massacres, the Bile-O-Tron gets knocked offline and Chimaeron stats casting "Feud". This is the timing of the events:

-4s: Massacre starts casting
0s: Bile-O-Tron offline, Chimaeron casting Feud
0.1s: Massacre damage becomes visible to players ("it hits")
15s: First AoE pulse
20s: 2nd AoE pulse
25s: Last AoE pulse
26s: Feud finishes with 4 seconds remaining on the cast. Massacre starts casting again
30.1s: Massacre damage becomes visible to players ("it hits")
34.8s: First melee hit on tank (assuming 20% swing speed slow applied on top of his base 4s swing timer)
```

**Comment by Sketish** [comment]
Kekonomics at what timer he stopped casting Feud? Currently he is stopping after 26 secs and he starts casting massacre

**Comment by UltraNix** [comment]
No further info - closing.
