### ISSUE TITLE
[Stonecore] High Priestess Azil

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3388]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) Devout Follower damage is very low. its around 300-400 damage, while on official server they deal 3k-4k to a leather wearer. They should also appear not right in the fightpit, but from all different directions.
2) Force Grip should be interruptable.

**How to reproduce:**

**How it should work:**
https://youtu.be/jG25xWy_s38?t=331

**Database links:**

https://www.wowhead.com/spell=79351/force-grip#comments
https://www.wowhead.com/npc=42428/devout-follower

**Comment by Afgann** [comment]
fixed
