### ISSUE TITLE
SpeedHack after BG

### ISSUE THREAD

**Issue by Torvahal** [gamefreedomgit/Maelstrom#3390]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description :** It is possible to speedhack after a bg, it can be "beneficial

**How to reproduce :** enter BG with his mount and finish or leave the BG when you remove the mount you run fast

**How it should work :** we shouldn't run fast

**Database links : //**

**Comment by UltraNix** [comment]
No further info - closing.
