### ISSUE TITLE
Bag of Fishing Treasures (BC) contains no gold

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3399]
**Description:**
Currently the Bag of Fishing Treasures (any version) gives NO gold when it should. After that it should also reward 2 extra items. The way this works is explained in a comment on wowhead that I have linked. 

"This bag was designed with 3 slots of rewards :

1. first slot will be always gold, normally about 6-7G

2. second slot will be fishing related,

3. thrid slot most of the time will be junks, or sometime will come with the 'surprises'"

**How to reproduce:**
Open either version of the BC Bag of Fishing Treasures

**How it should work:**
It should *always* contain about 7g and contain at least 2 different items as stated by the 2nd top comment on wowhead for the non pet version of the bag, though the pet version works the same way, with the addition of it dropping a pet as well.

**Database links:**
https://www.wowhead.com/wotlk/item=34863/bag-of-fishing-treasures
https://www.wowhead.com/wotlk/item=35348/bag-of-fishing-treasures

**Comment by Afgann** [comment]
fixed
