### ISSUE TITLE
[TotFW] Anshal

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3400]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Now sometimes summons only 3 Ravenous Creepers (10m heroic). 

**How to reproduce:**
Dont know, happened after 5 or 6 wipes on the boss, maybe it has something to do with evade mechanics, maybe some of them spawned under platform,

**How it should work:**

**Database links:**
https://www.wowhead.com/npc=120861/ravenous-creeper

**Comment by UltraNix** [comment]
Cannot reproduce this one.
