### ISSUE TITLE
[BWD] Magmaw 

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3402]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) Timers on the server are not matching official ones. https://youtu.be/HQQZITmXcR4?t=63
First Blazing Bone Construct should mark its location at 28 seconds after the pull, 4 seconds later Pillar of Flame should spawn.
At Whitemane they spawn simultaneously.
According to dbm, timer for Blazing Bone Construct is not strict but has a ~4 seconds wide range, while timer for pillar of flame should always be the same. Here they both had strict timers. 
2) Blazing bone construct meteor trail should not be strict. Right now its just one straight line, while on official server it should be something like this https://youtu.be/XfQWdc5cJew?t=67 Also i think flames are not "moving" like they should. On official server they are somewhat slow invisible mobs that chase players, while here flames kinda moving, but dont look like retail version.
**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=HQQZITmXcR4&t=89s

**Database links:**
https://www.wowhead.com/npc=41570/magmaw

**Comment by UltraNix** [comment]
Fixed.
