### ISSUE TITLE
Sinestra cooldown reset on wipe.

### ISSUE THREAD

**Issue by randomtester44** [gamefreedomgit/Maelstrom#3404]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you wipe on Sinestra your Cooldowns don't reset, same issue as it was on Nefarian last week.

**How to reproduce:**
Wipe on Sinestra, check if your cooldowns got reset.

**How it should work:**
Cooldowns should reset on wipe cause of QoL change that was implemented.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
