### ISSUE TITLE
Archaeology dig site Dun Garok has incorrect spawns

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3405]
**Description:**
Currently spawns from this site can appear *inside* the building, when they should only appear outside on the areas that can be gotten to on a ground mount. (not on top of the building or mountain. Additionally, I encountered a dig that would not spawn, moving a quarter of a yard one way would make my next spyglass flip 180 still tilling me I am near it. This one happened to be inside (or maybe on top or below exactly where I was, not sure. I was inside the main area of the building at the time.)

**How to reproduce:**
Preform Archy digs at the Dun Garok site until you get some that spawn inside the building.

**How it should work:**
All of the finds should be outside, generally on the grassy area or maybe near the mountain if it is climbable by ground.

**Comment by UltraNix** [comment]
Fixed.
