### ISSUE TITLE
Diminishing returns in PVP

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#3406]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Diminishing returns in PVP is currently set to permanently be 15 seconds right now before it resets.

**How to reproduce:**
Simply test diminishing returns with a tracker and see that its permanently 15 seconds right now before it resets.

**How it should work:**
on retail it was dynamic Drs which is between 15-20 secs (rng) but since thats not the case here it should be set to permanently be 18 seconds which is how every server has done it.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Diminishing_returns

Quote to look at - "It should be noted that the server does not reset diminishing returns after exactly 15 seconds. Instead, it checks every 5 seconds if there are any diminishing returns that should be reset because the last spell in their category was cast on the target more than 15 seconds ago. As a result, a particular diminishing return category may take anywhere between 15 and 20 seconds to reset. Most addons guess that a DR category has reset after 18 seconds by default."

**Comment by UltraNix** [comment]
Fixed.
