### ISSUE TITLE
Omnitron not resetting CDS after wipe

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3407]
[//]: # https://imgur.com/a/SCshw97

**Description:**
As shown in the clip above, Omnitron is not resetting CD's after each wipe or reset.

**How to reproduce:**
Use CDs and die to Omnitron boss

**How it should work:**
Like the other bosses, either running out if possible or dying should refresh all CDs

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
