### ISSUE TITLE
[Goblin starting area] Morale Boost

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#3409]
**How to reproduce:**
goblins are resetting for unknown reason players are unable to finish the quest
https://github.com/gamefreedomgit/Maelstrom/assets/36106057/fcd0ff25-abec-49aa-8f79-4a648b402a97

**How it should work:**
like the video below
https://www.youtube.com/watch?v=Xr-UjKq--dQ

**Comment by UltraNix** [comment]
Fixed.
