### ISSUE TITLE
SPELL_INTERRUPT not working for counterspell

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#3411]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The sub event SPELL_INTERRUPT from COMBAT_LOG_EVENT_UNFILTERED does not give the right information when interrupting spell with Counterspell. (Although sometimes it is working) (Out of all the interrupt our mage did on Cho, none resulted in a rightful event)

![WoWScrnShot_051023_014930](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/1e5ecac8-470f-4e98-b8d7-69835442b3ec)

On this screenshot you can see that supposedly Saphury interrupted Healing Touch from Ecodeluz. But the reality is that I (Magynomix GUID:0x000000000001A491) interrupted Healing Touch from Lyouv (GUID:0x0000000000004296). GUID does not match as well.

**How to reproduce:**
/etrace and interrupt something using counterspell

**How it should work:**
the event should have the right information in

**Database links:**

**Comment by pyrovetis** [comment]
a little visualization of what's working and what is not
![lol](https://i.imgur.com/YWPWfUQ.png)

**Comment by EmileQL2P** [comment]
Same on druid skull bash >.<

**Comment by UltraNix** [comment]
Fixed.
