### ISSUE TITLE
Tomb of the Watchers (archaeology digsite)

### ISSUE THREAD

**Issue by Ruthysarsch** [gamefreedomgit/Maelstrom#3412]
Tomb of the Watchers dig site is supposed to be giving dwarven relics when dug instead, it gives troll which is completely unrelated to that particular area according to the official wow wiki not to mention it really hurts dwarven excavations due to the already overwhelming amount of troll dig sites on that continent.

**How to reproduce:**
Digging in the designated area - here's an example: https://i.imgur.com/PKe1eOy.jpeg

**How it should work:**
It should give dwarven relics not troll

**Database links:**
https://wowpedia.fandom.com/wiki/Tomb_of_the_Watchers#:~:text=The%20Tomb%20of%20the%20Watchers,of%20Bloodwatcher%20Point%20sits%20nearby.

**Comment by UltraNix** [comment]
Fixed.
