### ISSUE TITLE
Flask Keep removing after death

### ISSUE THREAD

**Issue by elysian072** [gamefreedomgit/Maelstrom#3415]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Please Help me fix my flask kept removing when I die. It is not suppose to remove unless the time is over. I use two flask, the first one I assume it accidentally click and remove but the second one after I died it is also removed on my buffs.:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment]
What flask did you use?

**Comment by UltraNix** [comment]
No further info - closing.
