### ISSUE TITLE
Charmed Ancient Bone Bow not able to be transmogged 

### ISSUE THREAD

**Issue by maxyo45** [gamefreedomgit/Maelstrom#3416]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
No matter which bow I use to transmog the bone bow it says 'This items appearance cannot be used.'

**How to reproduce:**
Try to mog the bow, with any bow you can equip.

**How it should work:**
You should be able to transmog the heirloom with another bow model that you can equip.

**Database links:**

**Comment by UltraNix** [comment]
Tested with Charmed Ancient Bone Bow and Bow of the Greate Hunter - no problems.
