### ISSUE TITLE
Karazhan Chess Event

### ISSUE THREAD

**Issue by istvans94** [gamefreedomgit/Maelstrom#3419]
Chess Event is bugged, like on any other private server.
On every private server that i`ve played it was bugged so i do not ask for a Fix (even tho it would be nice) but please at least do what every other Private Server did, Spawned down the chest so we can obtain the items from that boss. As for ex hunters can obtain their tier 4 boots from there. and only from there.
Ive Talked to Hiki and this was his response. 
"in the bug report you can ask for the chest just to be "auto spawned" so that the event doesnt have to actually be fixed."

Thanks
Ironmark

**Comment by PanJanuszek** [comment]
should be fixed by Afgann
