### ISSUE TITLE
Bag of Shiny Things has no money in it. (like all the other fishing bags)

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3420]
**Description:**
Yes, I know 1 whole silver is penny pinching, but it's the principle of the mater. Currently the bag's loot table *seems* to be fine after doing it loads of times on 2 alts nearly every day, but right now it drops no money. Wowhead lists it's value at dropping an average of about 1 silver per bag in raw 'gold'

**How to reproduce:**
Open the Bag of Shiny Things

**How it should work:**
It should contain an average of 1 silver in 'raw gold' on top of the items it drops as well.

**Database links:**
https://www.wowhead.com/item=67414/bag-of-shiny-things

**Comment by Afgann** [comment]
fixed
