### ISSUE TITLE
Introductions are in Order - Worgen quest

### ISSUE THREAD

**Issue by Covikt** [gamefreedomgit/Maelstrom#3421]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Koroth the Hillbreaker is spawned too close to the banner that you are required to pick up for the quest Introductions Are in Order.

**How to reproduce:**
If you attempt to grab the banner, he is so close that he immediately autos and cancels your interact. He then proceeds to either one or two shot you with the gear provided up until that point.

**How it should work:**
He should be spawned further back to allow users a chance to grab the banner and run.

**Database links:**
https://www.wowhead.com/npc=36294/koroth-the-hillbreaker#screenshots
https://www.wowhead.com/quest=24472/introductions-are-in-order

**Comment by Covikt** [comment]
![WoWScrnShot_051123_171701](https://github.com/gamefreedomgit/Maelstrom/assets/132974615/9e22f839-b1df-4bd5-97b2-5955aeed1dbc)

**Comment by UltraNix** [comment]
Fixed.
