### ISSUE TITLE
Magmoth Fire Totem can attack and has thousands of health instead of a few hundred

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3422]
**Description:**
Totems shouldn't be able to attack and most of them shouldn't have the same HP or more than their owner

**How to reproduce:**
Go to Magmoth in Borean Tundra, above Fizzcrank Airstrip and get into agro range of a totem

**How it should work:**
The totem should only have a few hundred HP and have no melee attack, and should be unable to move.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=25444

**Comment by Afgann** [comment]
fixed
