### ISSUE TITLE
Hunter Intervene

### ISSUE THREAD

**Issue by Hailelune** [gamefreedomgit/Maelstrom#3423]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The next attack's absorb works, but it only absorbs 50 points of damage, but it should absorb damage equal to 50% of the pet's hp. tenacity talent

**How to reproduce:**

**How it should work:**
it should absorb damage equal to 50% of the pet's hp. tenacity talent

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=2594

**Comment by UltraNix** [comment]
#3118
