### ISSUE TITLE
Learning to Communicate unable to be picked up or it's follow ups

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3424]
**Description:**
This quest being locked behind the other faction's breadcrumb quest prevents several other quests as well as lots of Cenarion Expedition rep from being obtained, AND locks out a vendor from becoming available.

**How to reproduce:**
Go to the NPC and attempt to pick up his quest

**How it should work:**
The quest should not require the breadcrumb to pick up, and after accepting the quest, the NPC should cast his ability on the player which grants water breathing and I think swim speed as well.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11571 
https://cata-twinhead.twinstar.cz/?npc=25197#abilities

**Comment by PanJanuszek** [comment]
Actually quest chain is fixed. And yes, it required pre request quest per each faction [King Mrgl-Mrgl] 11702 & 11704
