### ISSUE TITLE
Mage Hunter Personal Effects can be empty

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3426]
**How to reproduce:**
Accept the quest Rifle the Bodies and loot the dead bodies in the area, then open the bag.

**How it should work:**
It should contain one of the grey items listed in the link below 100% of the time and it's quest item as well.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=35792
https://cata-twinhead.twinstar.cz/?quest=12000

**Comment by EdyGlockenspiel** [comment]
Additionally, it seems trying to loot the bodies of Dead Mage Hunter while stealthed will result in no bag and the body just despawning.

https://cata-twinhead.twinstar.cz/?npc=26477

**Comment by EdyGlockenspiel** [comment]
So I looted quite literally every single one of them and still did not get the quest item. Spamming my /tar macro and there are literally no more left and I am having to wait for respawns for something that should have a 100% drop.

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
