### ISSUE TITLE
Getting attacked by a dead mob the entire deadmines dungeon

### ISSUE THREAD

**Issue by bmeas** [gamefreedomgit/Maelstrom#3429]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/131665314/8db5c11f-5c63-4fca-961b-3e75969defa5)
Getting attacked by a dead mob the entire deadmines dungeon

**How to reproduce:**
Idk?

**How it should work:**
Shouldn't be attacking while dead?

**Database links:**
?????

**Comment by UltraNix** [comment]
Fixed.
