### ISSUE TITLE
Mind Vision doesn't cancel properly in dungeon

### ISSUE THREAD

**Issue by Resfa99** [gamefreedomgit/Maelstrom#3430]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to cancel mind vision 

**How to reproduce:**
Mind vision a player in dungeon ( idk if you can bug it outside of dungeons)

**How it should work:**
cancel upon moving

**Database links:**

**Comment by UltraNix** [comment]
@Resfa99 Just tested and everything worked okay. Can you give us more info about this one. What dungeon? WHat was the range between you and your teammate? Can you interrupt by simple /esc?

**Comment by UltraNix** [comment]
I thinks it's #2835
