### ISSUE TITLE
Randomly die in OG

### ISSUE THREAD

**Issue by zsolti15a** [gamefreedomgit/Maelstrom#3431]
Sometimes I die randomly in Valley of Strength between the auction house and the place where Hellscream is. It's mainly when I'm landing with Flying mount or jumping. Don't know the exact reason. There is no enemy around me. It's just on one point of Ogrimmar. I made a ticket of it for GMs and I've got the response I should create an issue ticket right here.  Attached the screenshot of it and made a screenshot about the place where I die sometimes randomly. It happened already several times. 

![1](https://github.com/gamefreedomgit/Maelstrom/assets/61913518/7588d3a2-138f-4144-9628-dce645d6fcc7)
![2](https://github.com/gamefreedomgit/Maelstrom/assets/61913518/ef2e42c5-dd50-4a14-aa3e-eb44b8a56d11)

**Comment by UltraNix** [comment]
Should be fixed.
