### ISSUE TITLE
Stratholme Gate Bug

### ISSUE THREAD

**Issue by DonKnutzen** [gamefreedomgit/Maelstrom#3432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Stratholme (sorry if misspelled) when you enter the main gate and go to the left there is a gate that closes and never opens again (so players are trapped forever).

**How to reproduce:**
Go into Stratholme from the main gate, go straight and take the first left. On the right is a Big Abonemation right at the gate wich i discribed. Once you enter between the gate doors, the doors shut and never open again.

**How it should work:**
Usally the gates shut and rats spawn inside the cage (3 or 4 waves). Here, the rats spawn in a really weirdly bugged way OUTSIDE both gates. We tried killing all the rats outside from inside the gate, but it still didnt open them. Normally after killing the waves of rats, the gates open again.

**Database links:**

**Comment by Afgann** [comment]
fixed
