### ISSUE TITLE
Unleash Elements not working as intended

### ISSUE THREAD

**Issue by Rayioku95** [gamefreedomgit/Maelstrom#3434]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?spell=73680

**Description:**
Shaman's unleash elements ability doesn't register the lava burst if casted while the lava burst is flying towards the target. This is forcing shamans to waste the global cd which leads to the dps drop. This also might be the case with frost mage and freeze interaction with other spells. For example if the frostbolt is flying towards the target and I use pet freeze, the frost bolt will not benefit from the  freeze crit effect.

**How to reproduce:**
Casting Lava burst first then instantly using unleash elements. Right now it doesn't consume the UE proc if used this way.

**How it should work:**
When lava burst is casted and flying towards the target, if we use UE , it should consume it because UE hits the target first.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=73680
Screenshots of the spell not working properly.
https://snipboard.io/KbZeq7.jpg
https://snipboard.io/TlQyA1.jpg

**Comment by Sketish** [comment]
Can you provide any retail source ?

**Comment by Rayioku95** [comment]
Not sure where I can find that tbh, but It was bugged on retail due to the latency. It was working well on Twinstar though. And as I've mentioned it's basically the same problem as frost mage's shatter. If I cast frostbolt and then petfreeze while the fb is flying it won't register the crit bonus.

**Comment by bonfax4** [comment]
Iirc the double dip trick did not work that way and its well known unleash in this manner is a dps loss anyway, the gcd is not worth it. You could use Unleash elements before a lavaburst + flameshock and that would make both abilities benefit from it as noted [here](https://www.tauri-veins.tk/elemental-shaman-wow-pve-dps-rotation-cooldowns-abilities) if you want a dps increase . Your frostbolt example here would be different and very wrong, i remember having to cast freeze before the frostbolt finishes casting not after it's already flying. The crit check happens on-cast,not on-hit.


 Interesting that lava burst > flameshock did not work according to wowwiki dated to cata

**Comment by bonfax4** [comment]
Just tested the double dip and it's currently bugged. Unleash elements into Lava burst + flame shock is not working properly and neither is Earthliving weapon unleash into  casted heal > riptide .

https://web.archive.org/web/20120616050306/http://elitistjerks.com/f79/t121202-resto_raiding_4_1_updating_4_3_a/

> Due to a bug the next direct heal is only buffed by 16/24% (without/with Elemental Weapons talent) instead of 20/30%. Usually the wasted global cooldown is not worth the trouble, but it has a niche while moving or when anticipating massive single target damage. If you have time to plan ahead you can Unleash, then cast a large heal like Greater Healing Wave or Chain Heal, and queue a Riptide before the heal finishes. Your Unleash will then benefit both the direct heal, the direct component of your Riptide and the HoT portion of your Riptide, making it a very strong combination (#30). Unleashing does not wok with Healing Rain.

**Comment by bonfax4** [comment]
Here proof people saying unleash that way you described doesn't work after some guy proposed that idea you're describing .

**Comment by Rayioku95** [comment]
Hmm that seems even worse, not being able to cast lavaburst and then instantly use UE to boost its damage makes it even worse of a spell.  I used to do that combo when I need to move so I precast lavaburst and then pop UE after the cast while moving. Oh well, at least the double dip thing would be nice to work. Do you know if it buffs the DoT or just the direct hit from flame shock?

**Comment by bonfax4** [comment]
You should still use ue while moving if you dont have that lightning bolt while moving glyph and yes unleash should affect full flame shock dmg ( initial + dot )

**Comment by Rayioku95** [comment]
Yeah I have it glyphed, so I guess I will only use UE for that double dip trick once it gets fixed. But thanks for the information I truly thought It should work like I said cause I had an Elemental shaman on Twinstar server and it was working like that, making the ele shaman even more fun to play :)

**Comment by Sketish** [comment]
Not a bug
