### ISSUE TITLE
Missing Quest: Hunt the Keeper -  The Hinterlands

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3437]
**Description:**
The quest "Hunt the Keeper" in The Hinterlands is missing.

**How to reproduce:**
Complete quest called "Summit of Fate", after this quest is completed you should be able to pick up "Hunt the Keeper".

**How it should work:**
Quest "Hunt the Keeper should be visible after completing quest "Summit of Fate"

**Database links:**
Missing quest: https://cata-twinhead.twinstar.cz/?quest=26526
Pre req quest: https://cata-twinhead.twinstar.cz/?quest=26517

![Hunt the Keeper](https://github.com/gamefreedomgit/Maelstrom/assets/69581489/ed9bd92f-c0df-4e14-8898-1d3ff7434777)
![Summit of Fate](https://github.com/gamefreedomgit/Maelstrom/assets/69581489/31871be9-0b14-4201-bb75-475ea56f9aff)

**Comment by Afgann** [comment]
fixed
