### ISSUE TITLE
coh+ grip

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#3438]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** under the coh you can't grip

**How to reproduce:**
https://forum.wowcircle.com/showthread.php?t=955064

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
What is coh?

**Comment by UltraNix** [comment]
The thing is that Death Grip is considered as magical spell
```
ID - 49576 Death Grip
=================================================
Description: Harness the unholy energy that surrounds and binds all matter, drawing the target toward the death knight and forcing the enemy to attack the death knight for $49560d.

Category = 0, SpellIconID = 2723, activeIconID = 0, SpellVisual = (10906,0)
Family SPELLFAMILY_DEATHKNIGHT (15), flag [0] 0x02000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
```
and thus is negated by CoS.

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/fc89aee4-16a4-4d06-afdf-734dc414bc9d)
source: https://www.wowhead.com/spell=31224/cloak-of-shadows#comments
Not a bug
