### ISSUE TITLE
Enhancement Shaman Feral Spirits Spirit Hunt is not correctly healing the wolves. 

### ISSUE THREAD

**Issue by Bruthay** [gamefreedomgit/Maelstrom#3441]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, making a repost from: https://github.com/gamefreedomgit/Maelstrom/issues/3217
Currently the Spirit hunt ability on the feral spirits are not healing the Feral Spirits themselves. 

**How to reproduce:**
Summon Wolves, have them take any amount of damage, have them attack a target to receive "spirit hunt" healing. They will not heal up.  

**How it should work:**
"Spirit hunt" is supposed to heal the Caster Shaman **AND** the 2 Feral spirits, currently it only heals the caster shaman but not the feral spirits. 

**Database links:**
https://youtu.be/IRYBZ9kV4Ko?t=271
( The clip above shows the Feral wolves healing off of spirit hunt, keep an eye on the feral spirit portrait. We know it's not from another source because the wolves are isolated and the shaman does not have healing stream totem down.)

**Comment by UltraNix** [comment]
Fixed.
