### ISSUE TITLE
Maloriak HC bugs

### ISSUE THREAD

**Issue by nezterx** [gamefreedomgit/Maelstrom#3442]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://clips.twitch.tv/HelplessBoxyLobsterLitFam-Xsbov8-rV6EXy29p 

Orb in P2 gets buffed by adds in P2, which it shouldn't.
 - Orb does around 160-200k damage, buffed by the adds, shows elsewhere in the vod. It should definitely NOT be buffed by the adds, just like how abberations should NOT buff the black sludges during the black phase (which is fixed now).
Orb triggering radius is way too large.

 https://clips.twitch.tv/AgreeableSpoopyGarlicOpieOP-1fzcNzKSnJQnK8WL
Boss gets buffed in the air, whilst transitioning into the green phase one shotting our main tank, hitting him for just over 230k in a single swing. The boss should not be buffed by the adds transitioning into the green phase like that.

**How to reproduce:**
Clip 1, run into orb with adds on your ass.
Clip 2 is hard to reproduce, first time seeing that happen on many pulls.

**How it should work:**
Decribed above.

**Database links:**

**Comment by Sketish** [comment]
Proof of 2nd issue
https://youtu.be/pSzGlqmg8QY?t=241

**Comment by UltraNix** [comment]
Fixed.
