### ISSUE TITLE
Nefarian stuck in air

### ISSUE THREAD

**Issue by nezterx** [gamefreedomgit/Maelstrom#3443]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Nefarian perma flying in P3.

https://www.twitch.tv/videos/1818136566?t=4h56m36s

**How to reproduce:**
Pull Nefarian and go to P3?

**How it should work:**
Nefarian should be grounded and not above ground, forcing melee dps to jump constantly to get in a single gcd every time they jump.

**Database links:**

**Comment by chengme123321** [comment]
The problem has not been fixed？

**Comment by UltraNix** [comment]
#3435
