### ISSUE TITLE
Provisioner Arok has no faction and thus no discount on items

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3447]
**Description:**
Because of this, his items are more expensive than they should be with a 20% discount for being max rep.

**How to reproduce:**
Mouse over the NPC

**How it should work:**
He should be of The Earthen Ring faction and give reputation discounts accordingly. 

**Database links:**
https://www.wowhead.com/npc=50324/provisioner-arok#comments

**Comment by Afgann** [comment]
fixed
