### ISSUE TITLE
Achievement (Not In My House) not working

### ISSUE THREAD

**Issue by Zephtrix** [gamefreedomgit/Maelstrom#3451]
I believe cross faction has this achievement bugged. Ive replicated on mutliple toons and neither horde or alliance side seems to work. This is a warsong gulch achievement for kill 2 flag carriers before they leave flag room.

**Comment by Zephtrix** [comment]
My rogue Trailertrash has put in tickets for this and Tide has seen them.

**Comment by UltraNix** [comment]
Fixed.
