### ISSUE TITLE
Basic Campfire does not give spirt buff

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3452]
**How to reproduce:**
Set down a Basic Campfire via the cooking profession and stand by it.

**How it should work:**
The Basic Campfire spawned by the spell Cooking Fire from the Cooking profession should buff all friendly NPCs and players around it with +4 spirit that last for 60sec and is refreshed continuously for the duration of the Basic Campfire as long as people stay within range of it.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=818

**Comment by UltraNix** [comment]
Fixed.
