### ISSUE TITLE
Dalaran rings and Stormwind/Orgrimmar Cloak of Coordination have an equip CD when they shouldn't

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3453]
**Description:**
Equitable items with a cast time do not have an equip CD, only items that have instant effect once used have a 30sec equip CD.

**How to reproduce:**
Equip any of the 16 port to Dalaran rings bought from the vendor. 

**How it should work:**
All 16 of the rings that port you to Dalaran should have no equip CD as is stated both on twinhead and wowhead.

**Database links:**
The ring, NPC it is sold from, and the spell
https://cata-twinhead.twinstar.cz/?item=51559
https://cata-twinhead.twinstar.cz/?npc=32172
https://cata-twinhead.twinstar.cz/?spell=54406
Cata Cloaks
https://cata-twinhead.twinstar.cz/?item=65274
https://cata-twinhead.twinstar.cz/?spell=89158#used-by-item
https://cata-twinhead.twinstar.cz/?item=65360
https://cata-twinhead.twinstar.cz/?spell=89157#used-by-item

**Comment by UltraNix** [comment]
Fixed.
