### ISSUE TITLE
Replica vendors are not talking in area 52

### ISSUE THREAD

**Issue by te3ms** [gamefreedomgit/Maelstrom#3454]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
cannot interact.

**How to reproduce:**

**How it should work:**
self explanatory

**Database links:**

**Comment by Alandiel** [comment]
You need to have old PvP rank or Rated BG titles in order to interact with them.
