### ISSUE TITLE
Leap of Faith(priest grip) bugged on Atramedes during combat

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3456]
[//]: # https://clipchamp.com/watch/R1Kv6DLjOKm
[//]: # cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?spell=73325](https://cata-twinhead.twinstar.cz/?spell=73325)

**Description:**
In the clip above, you can see I'm pressing Leap of faith, but the ability doesn't work during the encounter. And I was testing pre-pull and it seems to be working fine.

**How to reproduce:**
Pull Atramedes, wait for the air phase and have a raid member run away from the beam typically along the outskirts of the room. Then try and use Leap of Faith.

**How it should work:**
Leap of Faith should pull your friendly party member right in front of the priests position, in this case to buy more time before gonging and potentially saving them.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
