### ISSUE TITLE
Unholy Command

### ISSUE THREAD

**Issue by Bepemap-best** [gamefreedomgit/Maelstrom#3457]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # ([cata-twinhead.twinstar.cz](https://cata-twinhead.twinstar.cz/?issue=858))

**Description:**
1/2 50% refresh Death Grip after kill grants exp or honor, 2/2 100%

**How to reproduce:**
Not refresh 
**How it should work:**
Refresh after kill grants exp or honor

**Database links:**

https://cata-twinhead.twinstar.cz/?issue=858

**Comment by UltraNix** [comment]
Tested on mobs giving exp and on players - both cases work okay.
