### ISSUE TITLE
Secrets of the Talonpriests - Mob not spawning

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3460]
**Description:**
Quest is called "Secrets of the Talonpriests".
All mobs spawn but the one called "Talonpriest Skizzik".

**How to reproduce:**
Fly around all of Skettis with the macro /Target Talonpriest Skizzik

**How it should work:**
Should spawn in a house in Skettis.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=11005
Mob: https://cata-twinhead.twinstar.cz/?npc=23067#comments

**Comment by PanJanuszek** [comment]
Even noticed two of them. Removed duplicated spawn. Setting respawn to 30sec
