### ISSUE TITLE
Adversarial Blood - Quest TBC

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3461]
**Description:**
Not able to click the Skull Piles. Needed to click them to summon the bosses.

**How to reproduce:**
Gather 10x Time-Lost Scroll -> Go to Skettis -> Find a skull pile -> Try to click on it.

**How it should work:**
Should be able to click the skull pile.

**Database links:**
Time-Lost Scroll: https://cata-twinhead.twinstar.cz/?item=32620
Quest: https://cata-twinhead.twinstar.cz/?quest=11885

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
