### ISSUE TITLE
Death Pact eats your Ghoul instead of an Army of the Dead when given the option.

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3462]
**Description:**
Currently the Death Pact ability is eating the wrong pet when use, right now it just ate my Raise Dead Ghoul while I had every one of my Army of the Dead Ghouls up. This should not happen. The Raise Dead Ghoul for frost/blood should be the last thing it tries to eat.

**How to reproduce:**
Use Raise Dead, then Army of the Dead, then cast Death Pact.

**How it should work:**
It should eat your least duration remaining temp pet/guardian in order of Army of the Dead>Gargoyle(unholy)/Raise Dead Ghoul(blood/frost)>UH perma pet Ghoul.

**Database links:**
https://www.wowhead.com/spell=48743/death-pact#comments

**Comment by EdyGlockenspiel** [comment]
So it seems to be completely random, the next time I used army+ghoul it ate one of my army like it should. But both times I summoned my ghoul first, then army after. It should be in the specific order I mentioned above, not random.

**Comment by UltraNix** [comment]
Fixed.
