### ISSUE TITLE
[the top of the vortex, the top of the cyclon dungeon] 

### ISSUE THREAD

**Issue by Gameadictive** [gamefreedomgit/Maelstrom#3467]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When u try to use the winds, the slip streams to go next floor if u are in combat cause the lurking tempests u can´t.

**How to reproduce:**
Just going trough the dungeon til u must go trough winds

**How it should work:**
This bugged invisible and inmortals lurking tempest should be deleted from the dungeon. So not more in combat.

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
Fixed.
