### ISSUE TITLE
[Stonecore] Stonecore Flayer Flay Deals No Damage

### ISSUE THREAD

**Issue by pretty-blossom** [gamefreedomgit/Maelstrom#3468]
**Description:**
[Stonecore Flayer's](https://www.wowhead.com/npc=42808/stonecore-flayer#abilities;mode:normal) [Flay ability](https://www.wowhead.com/spell=79922/flay) deals no damage

**How it should work:**
Should deal frontal damage to anyone standing in front of the caster.

Proof: https://i.imgur.com/U9mgw20.jpg

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f70922e1-b6c3-4b26-973d-5011da8373df)
Works okay.
