### ISSUE TITLE
[Paladin][Holy] Lay on Hands CD resets visually

### ISSUE THREAD

**Issue by pretty-blossom** [gamefreedomgit/Maelstrom#3469]
**Description:**
Lay on Hands sometimes show that it is not on cooldown (visually), however, it is actually still on cooldown and you cannot use the spell.

**How to reproduce:**
From what I noticed it usually happens with dungeons.
- Use Lay on Hands inside a dungeon
- TP out
- TP back in and the ability's cooldown will reset visually

Proof:
- Used Lay on Hands before leaving the dungeon (you can see the 10min cd on the tooltip) - https://i.imgur.com/59FlssY.jpg
- TP'd back inside the dungeon and the cooldown was removed (still can't use the spell) - https://i.imgur.com/xzf8weU.jpg

**Comment by UltraNix** [comment]
@pretty-blossom Do you have Glyph of Lay on Hands?

**Comment by UltraNix** [comment]
Fixed.
