### ISSUE TITLE
[Lost City of Tol'vir] General Husam Detonate Traps No Damage

### ISSUE THREAD

**Issue by pretty-blossom** [gamefreedomgit/Maelstrom#3470]
**Description:**
[Mystic Trap](https://www.wowhead.com/spell=83171/mystic-trap?dd=6) deals no damage after it [detonates](https://www.wowhead.com/spell=91263/detonate-traps?dd=6).

Proof: https://i.imgur.com/06q0cno.jpg

**Comment by UltraNix** [comment]
Fixed.
