### ISSUE TITLE
[Throne of the Tides] Lady Naz'jar Boss Fight

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3472]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** First of all, as previously stated in #3234 , The mobs that spawn at 60% and 30% just spawn and immediately pick up aggro of the closest person -  they should appear and activate only after a couple of seconds , giving time for players to react.
Tanks will this way pull aggro and their teammates will have time to relocate or CC one or two adds.

Also, During the phase, the boss will be casting tornadoes at the players but at the moment the boss is not casting them towards the players, but in random fixed angles around the room.

The Geyser is currently oneshoting before even adding the fall damage part
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/b7a02630-a7b3-4c3d-936f-cca33e386931)

**How it should work:** Mobs shouldn't spawn in places and activate immediately, but rather "pop in" , and activate one-two seconds later as shown in video references

Tornadoes should be more responsive and targeting players. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/35c8d5e6-4873-4ba9-9503-c91ceac49bb5)

Geyser should not one shot, although it would probably result in almost death normally when adding the fall damage part. has to be dodged.
https://web.archive.org/web/20120502073452/http://www.wowhead.com/spell=75722
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a1a8454c-ba10-4ac3-9310-49eee9dd2270)

**Database links:** Video proof of current situation
 https://youtu.be/pMnCG4HL0hg

Retail References 

https://web.archive.org/web/20120418162514/https://www.wowhead.com/npc=40586/lady-nazjar#encounter
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e5a5608d-0371-4238-8e87-aa7b1c4d57ed)

https://www.youtube.com/watch?v=WhUyJPMGBIM https://www.youtube.com/watch?v=AMIV_4f4IpA

**Comment by UltraNix** [comment]
Fixed.
