### ISSUE TITLE
Elite relic is misssing on vendor

### ISSUE THREAD

**Issue by elunee12** [gamefreedomgit/Maelstrom#3474]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Elite relic is missing on vendor
**How to reproduce:**
add the relic

**How it should work:**

it should be availble on the elite vendor its not
**Database links:**

**Comment by UltraNix** [comment]
Fixed.
