### ISSUE TITLE
Reins of the grey riding camel

### ISSUE THREAD

**Issue by Shlime414** [gamefreedomgit/Maelstrom#3475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, i got recommended here from a GM since there was no way for him to check, but i made a ticket asking about the grey riding camel, and if you guys added it. I fly around all the time when im bored and all ive seen was one of the broken camel statues once when i first started. Ive also never seen anyone use it in game so just wanted to see if it was even added so i dont fly around there and instead head somewhere else.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/item=63046/reins-of-the-grey-riding-camel

**Comment by UltraNix** [comment]
Yes - it's in the game.
