### ISSUE TITLE
Mathias does not appear in the Twilight Highlands for the quest "Mathias' Command"

### ISSUE THREAD

**Issue by Nereuzz** [gamefreedomgit/Maelstrom#3476]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As title states - He is nowhere to be found in the Dragonmaw pass

**How to reproduce:**
Grab the quest and go to the Dragonmaw Pass in Twilight Highlands - Mathias is nowhere to be found

**How it should work:**
I guess he should stand on the hill besides the alliance banner

**Database links:**

**Comment by Sketish** [comment]
As notification mention when you enter TH, zone is not yet fully scriped

**Comment by Nereuzz** [comment]
Ahh, i see that now, completely my mistake, was just on a quest-rampage ;) Feel free to close the issue
