### ISSUE TITLE
Small comforts

### ISSUE THREAD

**Issue by Bepemap-best** [gamefreedomgit/Maelstrom#3477]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=27805/small-comforts)

**Description:**

<html>
<body>
<h1 class="heading-size-1" style="outline: none; max-height: 1e+06px; color: rgb(255, 255, 255); font-family: brother-1816, &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; margin: 0px 0px 10px; line-height: 1.1; font-size: 38px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Small Comforts<span class="fa fav-star fa-star-o" style="outline: none; max-height: 1e+06px; cursor: pointer; font-size: 30.4px; margin-left: 10px;"></span></h1><div id="video-pos-body" style="outline: none; max-height: 1e+06px; color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><span style="color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Find and return<span> </span></span><a href="https://www.wowhead.com/item=62545/mearas-dried-roses" style="outline: none; max-height: 1e+06px; color: rgb(255, 209, 0); cursor: pointer; text-decoration: none; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24);">Meara's Dried Roses</a><span style="color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">,<span> </span></span><a href="https://www.wowhead.com/item=62546/parlans-ivory-hammer" style="outline: none; max-height: 1e+06px; color: rgb(255, 209, 0); cursor: pointer; text-decoration: none; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24);">Parlan's Ivory Hammer</a><span style="color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">, and<span> </span></span><a href="https://www.wowhead.com/item=62543/aprikas-doll" style="outline: none; max-height: 1e+06px; color: rgb(255, 209, 0); cursor: pointer; text-decoration: none; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24);">Aprika's Doll</a><span style="color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">.</span>

  | Meara's Dried Roses
-- | --
Parlan's Ivory Hammer
Aprika's Doll

<div id="lksjdowlha" style="outline: none; max-height: 1e+06px; color: rgb(187, 187, 187); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 class="heading-size-3" style="outline: none; max-height: 1e+06px; color: rgb(255, 255, 255); font-family: brother-1816, &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; margin: 30px 0px 8px; line-height: 1.1; font-size: 21px;">Relevant Locations</h2><span style="outline: none; max-height: 1e+06px;">The entirety of this quest happens in<span> </span><b style="outline: none; max-height: 1e+06px; font-weight: 600; color: rgb(255, 255, 255);">Twilight Highlands</b>.</span></div>
</body>
</html>
**How to reproduce:**
cant use quest items

**How it should work:**

use quest items
**Database links:**

https://www.wowhead.com/item=62545/mearas-dried-roses
https://www.wowhead.com/item=62546/parlans-ivory-hammer
https://www.wowhead.com/item=62543/aprikas-doll

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
it didnt get removed from auto complete list so its still bugged

**Comment by PanJanuszek** [comment]
Fixed, PTR stage.
