### ISSUE TITLE
Cat pet Prowl Ability

### ISSUE THREAD

**Issue by radicdario** [gamefreedomgit/Maelstrom#3478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pet prowl ability in pet bar can (sometimes) say that it is on cooldown when it isn't

**How to reproduce:**
I played dungeons and use prowl to mask my pet to not pull mobs. After pet initiates combat it breaks prowl. After that when I want to click prowl in pet bar it says its on cooldown. IT DOES WORK when I right click the prowl ability to toggle it and the pet does go prowl.

**How it should work:**
When I am out of combat and click pet Prowl in pet action bar, pet should Prowl.

**Database links:**

**Comment by radicdario** [comment]
If any more info is required let me know.
Pet that I use is the blood elf zone Lynx cat outside of Silvermoon.

**Comment by initialactivity** [comment]
![WoWScrnShot_051723_120728](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/10aa78ae-5282-41e3-a263-bcd49e1ca08a)

**Comment by UltraNix** [comment]
Fixed.
