### ISSUE TITLE
Remove Corruption druid spell issue

### ISSUE THREAD

**Issue by Sokrates03** [gamefreedomgit/Maelstrom#3481]
https://www.youtube.com/watch?v=3WoNx3TA4-4 

Remove Corruption druid spell doesn't dispell curse effects from friendly target.

https://www.wowhead.com/spell=2782/remove-corruption

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/006043a7-418e-4fdc-b63a-80dcc896eb52)

**Comment by UltraNix** [comment]
@Sokrates03 You are using some macro for this spell?
