### ISSUE TITLE
Turn Evil doesn't fear Warlocks Metamorphosis form

### ISSUE THREAD

**Issue by cenkenator** [gamefreedomgit/Maelstrom#3484]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Turn evil should fear warlocks under metamorphosis. It doesnt

**How to reproduce:**

 It should fear them, cant cast on that target. Try fearing on a warlock in metamorphosis.

**How it should work:** It should fear the warlock when cast on him during metamorphosis

**Database links:**

**Comment by Pornoodemon** [comment]
This spell, along with Holy Wrath(the stun part of the spell, it'll still cause damage), as of 4.0.1 no longer work on Demonology warlocks in the Metamorposis state. Last edited by 670764 on 2010/11/19 (Patch 4.0.3)
https://www.wowhead.com/spell=10326/turn-evil#comments

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/20a62029-f0fd-4626-9a22-7fa471539073)
