### ISSUE TITLE
Anti Magic shell generates infinite runic power

### ISSUE THREAD

**Issue by cenkenator** [gamefreedomgit/Maelstrom#3485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Anti Magic shell generates infinite runic power, 

**How to reproduce:**

Damage a dk with magic damage while he is in AMS spending lichborne death coils on himself.

**How it should work:**

 it should generate apropriately 0-100 based on magic damage taken in the shield

**Database links:**

**Comment by Sketish** [comment]
https://youtu.be/-s9lh3DhEhg?t=217

As you can see there he generated more than 100 rp during ams

**Comment by EdyGlockenspiel** [comment]
I don't remember how it worked in cata, but I do know by the end of mop, as frost I would get more than my max RP from a single attack while raiding SoO. I remember my strat during Garrosh prog would be to dump all my RP when the star would come out, then pop AMS and get told I generated something like 160 RP which is far above my cap. The amount absorbed is based on your max HP when you cast the ability, but the amount of RP generated is based on damage taken. So TL;DR the more max HP the DK has when they use AMS the more it can absorb and the more RP it will generate from magic damage absorbed.

**Comment by SimonBpvp** [comment]
Reopen please there’s about 10 idiot dks without github accounts complaining that it’s not fixed
