### ISSUE TITLE
Scarlet Praetorian Dmg

### ISSUE THREAD

**Issue by Problematikas** [gamefreedomgit/Maelstrom#3486]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Eastern Plague lands there is mobs called Scarlet Praetorian , as I been questing I noticed that they do form 300-500 damage a hit (which is insane) I`m being their level only have 1.3k HP , which means I`ll die in 3 shots or if by accident I pull 2 of them , I get one shotted.

The other mobs by them as Scarlet Clerk is doing normal damage.

**How to reproduce:**

**How it should work:**
The damage should be way lower as it makes impossible to quest with classes that wears "Cloth" armour.   

**Database links:**
![WoWScrnShot_051723_043127](https://github.com/gamefreedomgit/Maelstrom/assets/133836868/204730fa-0b1d-4a86-bb13-8bd4758d24c4)

**Comment by Sketish** [comment]
Acorrding to wowhead comments, those mobs  dmg was very high.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/82ba2137-2e63-4ec0-ac13-c5e3b19fc37e)
