### ISSUE TITLE
Summoned pets and demons fall through the platform of Siamat Boss

### ISSUE THREAD

**Issue by radicdario** [gamefreedomgit/Maelstrom#3488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Summoned pets and demons fall through the platform of Siamat Boss in The Lost City of Tol'vir

**How to reproduce:**
Pick a hunter or warlock class and use the whirlwind that gets you up to the platform of the last boss (clearing previous bosses required)

**How it should work:**
Pets and demons should be able to run on top of the platform the same way as characters.

**Database links:**

![WoWScrnShot_051723_090715](https://github.com/gamefreedomgit/Maelstrom/assets/53829811/898c21a1-46ef-4cb4-9f90-20b91c1cb8b9)

**Comment by UltraNix** [comment]
#2551
