### ISSUE TITLE
Corborus boss Pet bug

### ISSUE THREAD

**Issue by initialactivity** [gamefreedomgit/Maelstrom#3489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Phase where Corborus Boss of Stonecore dungeon comes out of the ground, the pets are unable to attack him. Pets just sit and they **evade** damage.

**How to reproduce:**
As Hunter or Warlock Fight the boss with Pet being commanded to Assist You and Attack. Boss will go underground and pop out to damage people. After he does it a few times he comes out of the ground, and pets are unable to attack.

**How it should work:**
After the boss comes out of the ground the pet should leave my side and go attack the boss.

**Database links:**
![WoWScrnShot_051623_233203](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/6dd02c55-19d7-4057-a39a-b8a560828a8e)

**Comment by UltraNix** [comment]
Tested - works okay.
