### ISSUE TITLE
Valor points are all sorts of fucked up.

### ISSUE THREAD

**Issue by bmeas** [gamefreedomgit/Maelstrom#3490]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Raids are giving inconsistent amounts of valor points. They're all over the place.
(no chars have done any dungeons this reset or anything else to gain valor + chars have been logged out and in to ensure its not a visual bug)

Char 1: Completed BH10/BH25 =  175/1250 Valor
Char 2: Completed BH10/BH25/Tot4W10/Tot4W25 = 280/1250 Valor
Char 3: Completed BH25 = 70/1250 Valor
Char 4: Completed BH10 = 70/1250 Valor

Char 4 went into a BH25 and it's total went to 140/1250 (+70), completed the same raids as Char 1 and has 35 Valor less.

Char 1 then went into a Tot4W10.
After the first boss the chat window said +70 and the Valor points went to 210/1250 (an actual increase of 35)
After the second boss the chat window said +70 and the Valor points went to 210/1250

**How to reproduce:**
Go into raids.

**How it should work:**
From what I can see online it should be 75 per 10 man boss and 105 per 25 man boss (links below) although I'm not sure if this was changed at a later date, regardless of this the points given are inconsistent.

**Database links:**
https://www.wowhead.com/news/cataclysm-justice-valor-point-drop-quantities-170048
https://www.engadget.com/2010-10-06-cataclysm-justice-and-valor-point-drop-rates-revealed.html

**Comment by bmeas** [comment]
Also asked a friend for his Valor points:
Char 1: BH10/BH25 175/1250 Valor
Char 2: BH10/BH25 175/1250 Valor
Char 3: BH10/BH25 140/1250 Valor
Char 4: BH10/BH25/Tot4W10/Tot4W25 = 280/1250 Valor

**Comment by bmeas** [comment]
@UltraNix Was not capped on any char. Neither was my friend. We did nothing else to get Valor in any way on any chars this reset other than those listed.

**Comment by UltraNix** [comment]
We made some tests and everything was okay.
@bmeas Are you able to do another test?

**Comment by bmeas** [comment]
> We made some tests and everything was okay. @bmeas Are you able to do another test?

Chars are capped at this point, would need to wait for next reset and see how it is

**Comment by UltraNix** [comment]
Okay.

**Comment by UltraNix** [comment]
@bmeas

**Comment by UltraNix** [comment]
No further info - closing.
