### ISSUE TITLE
Teleport This! - Bugged Quest - Netherstorm

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3494]
**Description:**
Nothing happens when you try to destroy the teleporters

**How to reproduce:**
Take control of a Cyber-Rage Forgelord with the quest item Mental Interference Rod -> Use ability Detonate Teleporter at or nearby the Teleporter. Nothing happens

**How it should work:**
When following the steps above the teleporter should be destroyed.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=10857
Video: https://www.youtube.com/watch?v=41OxvcqdNQ0&ab_channel=WoWQuests

**Comment by KevlinTallfellow** [comment]
Western teleporter still bugged as of 12/06/2023

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/ae363696-26e1-4b37-b901-be5cea5e2f79)

works as expected 07.03.2024
