### ISSUE TITLE
On Nethery Wings - Bugged Quest - Netherstorm

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3495]
**Description:**
Can't complete the quest since boss starts to evade attacks and then regens.

**How to reproduce:**
Pick up the quest -> Talk to the Nether Drake that will fly you around the boss (Also tried with my own flying mount as well as tried to DPS the boss) -> When using the given item "Phase Disruptor" to DMG the boss (or trying to DPS without item) the boss evades and regen to full.

**How it should work:**
Boss should not start to evade.

**Database links:**
Quest: https://cata-twinhead.twinstar.cz/?quest=10438
Video: https://www.youtube.com/watch?v=N1_mLcUoUas&ab_channel=PhoenixGaming

**Comment by PanJanuszek** [comment]
Fixed after restart
