### ISSUE TITLE
Magmaw - Lava Spew

### ISSUE THREAD

**Issue by randomtester44** [gamefreedomgit/Maelstrom#3496]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Lava Spew should do 3 ticks of damage (1tick every 2 seconds for 6 seconds = 3ticks) 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/c8585ec2-70c3-4506-961d-81ce50daffe2)
Currently it's doing only 1 tick and ability is over. As you can see on image below, he casted ability 24 times, there are 10 people in raid and we had 239(240/resist or smth) ticks which is 1 tick per player on each cast. Should be around 720 hits on 24 casts.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/83c45c96-df81-429b-9786-ca6931a0e6a5)

**How to reproduce:** Pull Magmaw on HC and check if Lava Spew does three ticks.

**How it should work:** Lava Spew should do damage every 2 seconds for 6 seconds.

**Database links:**

**Comment by Polynomix** [comment]
I'd like to add that right now the boss cast his spells every 7s instead of 22s. That means that we get 3 tick in 22s (1 tick every 7s) instead of 3 tick in 6s but every 22s. I hope the fix wont be 3 tick in 6s every 7s.
