### ISSUE TITLE
Asghar's Totem - Bugged Quest - Shadowmoon Valley

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3497]
**Description:**
Can not pick up the quest Asghar's Totem after pre req is completed.

**How it should work:**
After completing Find the Deserter -> Parshah should give you Asghar's Totem

**How to reproduce:**
Complete: Find the Deserter and see that  Parshah does not give you Asghar's Totem

**Database links:**
Pre req: https://cata-twinhead.twinstar.cz/?quest=10759
Quest: https://cata-twinhead.twinstar.cz/?quest=10777

**Comment by PanJanuszek** [comment]
fixed 11.03.2024
