### ISSUE TITLE
Wrong NPC type: worg shown as humanoid

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#3498]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blackrock Battle Worg from Redridge Mountains are shown as humanoids. So hunters can't tame them.

**How to reproduce:**
Just come and see it)

**How it should work:**
Should a beast, as it said on wowhead

**Database links:**
https://www.wowhead.com/npc=43340/blackrock-battle-worg

**Comment by Afgann** [comment]
fixed
