### ISSUE TITLE
Spawn of Fankriss hunter pet

### ISSUE THREAD

**Issue by Zipper1996** [gamefreedomgit/Maelstrom#3499]
https://www.wowhead.com/npc=15630/spawn-of-fankriss

**Description:**
Spawn of Fankriss should be marked as beast and be tamable. It is a worm pet.
![WoWScrnShot_051823_045816](https://github.com/gamefreedomgit/Maelstrom/assets/133601328/d6c4cfad-86a3-4b6e-ae3c-61188612fa0c)

**Comment by Revly** [comment]
Be careful, this Beast has a "Rage" or "Frenzy" damage increased by a certain %, when it is going to be tamed it does not have this skill learned

It is best to leave it as is, or when you tame it, it will not have that ability once tamed.

**Comment by UltraNix** [comment]
Fixed.
