### ISSUE TITLE
Enraged Spirits of Fire and Earth - Bugged Quest - Shadowmoon Valley

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3500]
**Description:**
No quest given from the quest giver.

**How to reproduce:**
Complete: The Hand of Gul'dan

**How it should work:**
After completing The Hand of Gul'dan you should be able to pick up: Enraged Spirits of Fire and Earth

**Database links:**
Pre req: https://cata-twinhead.twinstar.cz/?quest=10680
Quest: https://cata-twinhead.twinstar.cz/?quest=10458

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
