### ISSUE TITLE
NO SPOWN ON LOCATION

### ISSUE THREAD

**Issue by sqx035** [gamefreedomgit/Maelstrom#3501]
/npcscan add 51000 Blackshell the Impenetrable
/npcscan add 50731 Needlefang
/npcscan add 50838 Tabbs
/npcscan add 51018 Zormus
/npcscan add 50726 Kalixx
/npcscan add 51007 Serkett
/npcscan add 51021 Vorticus
/npcscan add 50728 Deathstrike

![Badlands 5 1 Rares](https://github.com/gamefreedomgit/Maelstrom/assets/133935162/9543149a-2f85-453c-9a2b-69f65c148fd9)
![Badlands 5 1 Hunter Pets](https://github.com/gamefreedomgit/Maelstrom/assets/133935162/376fe783-39f3-467b-b316-ded467a2e189)

**Comment by Alandiel** [comment]
This rares have been added to game in Mists of Pandaria. Not a bug.
