### ISSUE TITLE
Blood Is Thicker fish unable to be caught if you are at 4/5 for the quest

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3504]
**Description:**
Right now if you attempt to catch the Bloodtooth Frenzy from Pool of Blood and have 4 already, you will catch literally nothing and the pool will despawn like as if you fished it out.

**How to reproduce:**
Have 4 Bloodtooth Frenzy in your bags and fish out of a Pool of Blood with the daily quest Blood Is Thicker

**How it should work:**
You should be able to catch more than the amount needed for the quest

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13833
https://cata-twinhead.twinstar.cz/?item=45905#fished-from-object
https://cata-twinhead.twinstar.cz/?object=194479

**Comment by Alandiel** [comment]
Works fine. I had 4 fish and then finished quest with 7.
