### ISSUE TITLE
Got ninjaed in a dungeon by a prot paladi

### ISSUE THREAD

**Issue by Ceskayo** [gamefreedomgit/Maelstrom#3506]
Hello just did a Halls of origination dungeon as a holy paladin and a holy  Omega Brestplate droped its obv for healer and paladin tank named paladean ninjaed it from me

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3671f856-5a62-416d-a6fa-edcee342113a)
https://forms.gle/SjRnaG6eaAosbgUj8
