### ISSUE TITLE
Kurinnaxx tamable as hunter pet.

### ISSUE THREAD

**Issue by Zipper1996** [gamefreedomgit/Maelstrom#3509]
https://www.wowhead.com/npc=15348/kurinnaxx

**Description:**
Kurinnaxx in Ruins of Ahn'Qiraj should be labeled as a beast and be tamable by hunters. It is a Silithid pet.

**How to reproduce:**

**How it should work:**
![WoWScrnShot_051923_035802](https://github.com/gamefreedomgit/Maelstrom/assets/133601328/3bb0a22e-828f-41f5-be14-eecfbdd9bacf)

**Database links:**

**Comment by Alandiel** [comment]
Option to tame Kurinaxx was added in Legion.
