### ISSUE TITLE
Round two : Jewelcrafting trinkets.

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#3510]
It's been over 2 months that my first github getting ignored so I'll do another.
Jewelcrafting quest item for trinkets is bugged, droprate is so low it takes hours to drop 1 ( it's 2% in any mob in cata but I killed over 10k mobs and I only got 3 so far ).
The strength one never ever dropped on any 81/84 and agility takes atleast 10 hours to drop.
Link : 
https://cata-twinhead.twinstar.cz/?item=65895
https://cata-twinhead.twinstar.cz/?item=52197

**Comment by hamzaeleuch97** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2653
It's from 25 march :)

**Comment by UltraNix** [comment]
Fixed.
