### ISSUE TITLE
Venomhide Ravasaur Mount Quest Bug

### ISSUE THREAD

**Issue by cannibal69** [gamefreedomgit/Maelstrom#3511]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**
![WoWScrnShot_051923_122318](https://github.com/gamefreedomgit/Maelstrom/assets/134057994/6e736cc3-f667-4e9b-a86c-610a29a769c6)

Quest can't be completed even if I gathered all the requied quest items.

**Comment by PanJanuszek** [comment]
Cannot reproduce

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/6676fcaa-2184-4ad8-9417-167eccf45499)
