### ISSUE TITLE
Ishaal's Almanac i kill Talonpriest Ishaal and no give me quest. 

### ISSUE THREAD

**Issue by sqx035** [gamefreedomgit/Maelstrom#3512]
![WoWScrnShot_051923_122920](https://github.com/gamefreedomgit/Maelstrom/assets/133935162/f79c654b-c192-4d52-a6b1-2d8fd47acd15)
![WoWScrnShot_051923_123111](https://github.com/gamefreedomgit/Maelstrom/assets/133935162/3960f8fc-a6b0-4380-b58f-a53a93cf294f)

**Comment by sqx035** [comment]
TY!!!!!!!!

**Comment by PanJanuszek** [comment]
fixed 09.03.2024
