### ISSUE TITLE
Mail icon bug

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3516]
**Description:**
The "new mail icon" appears on the interface, when you have no mail.

**How to reproduce:**
Reciving a mail, sometimes the icon gets bugged and dont dissapear, even if you do /reload or close and open the game.

**How it should work:**
The mail icon must dissapear when you have no more "new mails"

**Database links:**
-

**Photography:**
https://i.imgur.com/9FDgAAk.png

**Comment by UltraNix** [comment]
@varjla Have you sold/bought something on AH?

**Comment by varjla** [comment]
> @varjla Have you sold/bought something on AH?

Obviously is a yes, but I guess this happens even when I only send mails between my players, after I got all my mail readed or picked up. I will pay some tests on this issue.

**Comment by UltraNix** [comment]
No further info - closing.
