### ISSUE TITLE
Cat/bear druid broken HUD after some quest with "vehicles" in Desolace

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3521]
**Description:**
After doing the Desolace quest chain where you transform yourself in a Naga AND move to another zone, if you are druid and transform to cat, you get your hud totally broken, getting the "naga vehicle hud"  but the cat/bear skills. (see photo). In other transofrmations the hud doesn't appear. Seems an error with the cat/bear action bars. /reload command seems to solve the problem. so its a minor issue.

**How to reproduce:**
Do the questline marked down, then, transform into cat or bear being a druid.

**How it should work:**
The vehicle HUD musn't appear anymore.

**Database links:**
https://www.wowhead.com/quest=14260/going-deep
https://www.wowhead.com/quest=14264/wetter-than-wet
https://www.wowhead.com/quest=14268/deep-impact

https://www.wowhead.com/quest=14284/a-revenants-vengeance (last quest I did)

**Photography:**
https://imgur.com/5ijxEaY

**Comment by UltraNix** [comment]
Fixed.
