### ISSUE TITLE
Severe Magmaw Bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Magmaw randomly gets the buff "Molten tantrum" which increases his damage by 100%. This should only be on him when tank is not in melee range, instead he gets it from time to time even though tank is in melee range.

**How to reproduce:**
This might happen whenever he does one of his abilities that target someone outside melee range and insta gets a stack, not 100% sure.

**How it should work:**
Even if some raid member is targeted for an ability like meteor or whatever, if tank is in melee range he should never get Molten Tantrum. This is because the ability says it should be cast when the boss can't melee a target, it should never try to melee ability targets.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
