### ISSUE TITLE
Warrior Mortal Strike overscaled damage or incorrect formula

### ISSUE THREAD

**Issue by Artemhx** [gamefreedomgit/Maelstrom#3525]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
### **[Mortal strike](https://cata-twinhead.twinstar.cz/?spell=12294) does more damage than it should based on the formula** 
**I've tested with this gear, talents and only one glyph([Glyph of Mortal Strike](https://cata-twinhead.twinstar.cz/?item=43421)):** 

![1](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/8f06c458-a8a0-4236-8b41-9178d7911aa8)
![2](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/515bd6ae-e5b9-4b50-be3e-230d612c9385)

**Against Mage with no talents, 0 resilence and 0 armor:**

![3](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/c3ab5df4-81ca-49a1-a880-218e0edf1bbc)

**How to reproduce:**

**I used that formula:**

> normalized_damage = base_weapon_damage + (X * Attack Power / 14) * 1.12(Two-Handed Weapon Specialization)
> where X is:
> 
> 1.7 for daggers
> 2.4 for other one-handed weapons
> 3.3 for two-handed weapons
> 2.8 for ranged weapons

**Current Attack Power: 7385**
**Weapon: [Worn Greatsword](https://wowpedia.fandom.com/wiki/Worn_Greatsword)**
![4](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/9151ce25-f462-4168-9f16-a524a646429e)

**So**
**min weapon damage = 2 +(3.3 * 7385 / 14) * 1.12 = 1951**
**max weapon damage = 4 +(3.3 * 7385 / 14) * 1.12 = 1953**

**Whitemane Mortal Strike formula(188% weapon damage + 1026)**
![5](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/8633d4ba-59aa-4a2f-abb6-fcbb35c722c0)
**So** 
**min 188% weapon damage + 1026 =1951 * 1.88 + 1026 =4695** 
**max 188% weapon damage + 1026 =1953 * 1.88 + 1026 =4698** 

**+ 5% battle stance**
**So**
**min damage= 4695 * 1.05 = 4929**
**max damage= 4698 * 1.05 = 4933**
**But actually, mortal strike does more damage:**
![6](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/32c60b5c-7249-4271-b00e-9d64bde44f19)

[Video link](https://youtu.be/M_eokDkMFYw)

**Also, i tested the same way with zero gear warrior and start weapon and the formula works correctly, but when i equip some gear(or use some buffs) and increase my attack power - mortal strike does more damage than it should based on the formula**

**Zero gear warriror with start weapon test -->**

**Current Attack Power: 631**
**Weapon: [Worn Greatsword](https://wowpedia.fandom.com/wiki/Worn_Greatsword)**
![4](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/9151ce25-f462-4168-9f16-a524a646429e)
**min weapon damage = 2 +(3.3 * 631 / 14) * 1.12 = 168**
**max weapon damage = 4 +(3.3 * 631 / 14) * 1.12 = 170**

**Mortal Strike formula(188% weapon damage + 1026)**

**So** 
**min 188% weapon damage + 1026 =168 * 1.88 + 1026 =1342**
**max 188% weapon damage + 1026 =170 * 1.88 + 1026 =1346**

**+ 5% battle stance**
**So**
**min damage= 1342 * 1.05 = 1410**
**max damage= 1346 * 1.05 = 1414**

**Works Correct -->**
![6](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/06275c17-8e31-4936-aaec-3b8bf8fa0fb9)

[Video link](https://youtu.be/iCAOwupahpc)

**How it should work:**
**Looks like the problem is: The more Attack Power increased - the more damage is inflated, than should be based on the formula. Idk maybe i'm wrong.**
**I've tested mortal strike with this formula on two other cata servers and there is always correct number, doesn't matter what gear is equipped or attack power value**

**Most likely the same problem on Whitemane with Overpower and other warrior's abilities, so i hope Whitemane QA team will check and test this out =)**

**Database links:**
https://wowpedia.fandom.com/wiki/Normalization

**Comment by BalanCV** [comment]
Wrecking crew gives you enrage 10% physical on mortal maybe that's it.
Lambs to the slaughter does similar but I see you didn't talent it.

**Comment by Artemhx** [comment]
Wrecking crew works only if mortal strike crits, and i didn’t crit any

**Comment by UltraNix** [comment]
@Artemhx Please, poke me on Discord.
