### ISSUE TITLE
Mutilate does not generate combo points on killing blow

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#3527]
**Description:**
There are a handful of rogue abilities that require combo points, which can be used even if the enemy with them is dead. Currently if your target dies, from an ability that *generates* combo points, the combo points will *not* be added even though the damage from the ability went off. Lets say for example I use Mutilate, which kills my target. I now can't use slice and dice or recuperate because I have 0 active points when I should have 2 or 3 (depending on if I crit or not). I also can not move these 2 or 3 points to another, living target with Redirect like I should, either. This makes questing as a rogue *very* annoying and would also cause problems in both pvp and pve, as well.

**How to reproduce:**
Kill a target with a combo point generating ability while having less than 5 on said target.

**How it should work:**
Combo points should be generated on the target whether or not it dies from the ability that generates them to allow you to spend or move them.

**Database links:**
No, I was not able to find reference to this on the wowhead pages for either Combo Points or the rogue class as a whole, but I am positive this is how it worked, my knowledge of rogue pre mop is quite low however. If you have evedence/knowledge of this working as intended in *cata* I'd like to see it. But I *do* know in mop it 100% worked this way, which leads me to believe if would also be the same for cata. At worst I can get on Blizzard's wrath classic PTR (which is free to DL and use) to test there if needed.

**Comment by Sketish** [comment]
https://youtu.be/Wu1yRxBjCgY?t=148 player was able to use recuperate or snd after killing player. Confirmed

**Comment by EdyGlockenspiel** [comment]
This bug also does not allow for talents that refresh buffs/debuffs on combo point *spender* to refresh. For example Cut to the Chase talent which should set slice and dice to 5 combo point duration, I just used it, which killed my target and did not get my slice and dice refreshed because the ability killed my target.
https://cata-twinhead.twinstar.cz/?spell=51667

**Comment by UltraNix** [comment]
@EdyGlockenspiel Just tested with Cheap Shot and combo points are added to dead player.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2d27d277-837b-4858-a359-162f513f95dc)

**Comment by UltraNix** [comment]
Also tested that talent and it got refreshed on Eviscerate (which killed the player).

**Comment by EdyGlockenspiel** [comment]
Cheap shot does not kill the target.. are you trolling?

**Comment by EdyGlockenspiel** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/126888684/52eb2060-b28c-4942-8751-c771c4b47384)
Perhaps it's just assassin then.

**Comment by EdyGlockenspiel** [comment]
So I tested all of my damaging combo point generators and it seems *only* mutilate bugs out like this.

**Comment by EdyGlockenspiel** [comment]
I also was able to refresh slice and dice moving combo points from a target dummy to a rat and 1 shotting it, so maybe it is just Envenom that is bugged in that way. I can't hit a rat with Envenom because I need deadly poison to be on it first. So can't test. But I know it was happening every so often while questing.

**Comment by EdyGlockenspiel** [comment]
Just tested it on a lvl 80 elite in hyjal and it refreshed my slice and dice. So idk what was causing it to not do so before. But mutilate still does not generate combo points on a killing blow, that much is clear.

**Comment by UltraNix** [comment]
Fixed.
