### ISSUE TITLE
magmaw bug tantrum

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3528]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 he puts tantrum even if u are in melee range and tank it

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
the bug appeared after restart and after law spew fix

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3524 duplicate
