### ISSUE TITLE
Character: Nikaila  My character died in orgrimmar randomly and my camera is stuck under the map. HELP

### ISSUE THREAD

**Issue by Fluffalpaca** [gamefreedomgit/Maelstrom#3529]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Character walking in Org and just died randomly (Second time this has happened) and now my character is bugged and I cannot play her. The camera is stuck underground and I was able to move her around but now it says im falling. Can't die, cant hearth. I even went into a dungeon and same thing. Relogged/Reopened game. Nothing.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please open ticket ingame so GM's can help you with that issue
