### ISSUE TITLE
Magmaw - Magma spit missing

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3531]
Magma spit should every 15 seconds hit 3 targets on 10 man and 8 targets on 25 man. Currently it look's like its not casted on proper number of targets and boss is stoping using Magma Spit after first pinning of his head.

**How to reproduce:**
https://www.warcraftlogs.com/reports/YcdNr1MV4Wg7ZHC2#fight=29&view=events&type=damage-taken&ability=91927

**How it should work:**
Magma Spit should be casted for whole duration of the fight

**Database links:**
https://www.youtube.com/watch?v=f0fuZniNU5w&t=27s&ab_channel=AvailedGuides

**Comment by UltraNix** [comment]
Fixed.
