### ISSUE TITLE
[Warlock] Burning embers not transfering damage to bane of Havoc target.

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3532]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Damage from burning embers is not being transferred to the bane of havoc target. Should be a decent dmg increase on fights like Halfus and Magmaw ( dots should still do damage to the exposed head and the main body even after each of them is untergetteable, have not tested yet if this is currently the case on this server). 

**How to reproduce:**
Bane of havoc a second target.

**How it should work:**
Burning embers should be considered a spell casted by the warlock and should be transfered to the bane target.

https://wowpedia.fandom.com/wiki/Burning_Embers_(original)?direction=prev&oldid=2977138

> Damage caused by Burning Embers is considered to be caused by the warlock, even when procced from the [Imp's](https://wowpedia.fandom.com/wiki/Imp_(warlock_minion)) Spell fire firebolt [[Firebolt]](https://wowpedia.fandom.com/wiki/Firebolt). This means that the additional damage from Firebolt will:
> Generate aggro for the Warlock and not the Imp
> Proc Fel Synergy, effectively causing the Imp to heal itself
> Proc Spell shadow felarmour [[Fel Armor]](https://wowpedia.fandom.com/wiki/Fel_Armor), effectively causing the Imp to heal the warlock
> Tap mobs on behalf of the warlock, allowing the warlock to loot mobs killed solely by the Imp

Also went to twinstar and BE dmg is also being transfered, not the most reliable source i know.

https://web.archive.org/web/20120103221302/http://elitistjerks.com/f80/t111390-destruction_cataclysm_4_3_release/p9/

> A slightly wrinkle with this maths is that Burning Embers (the damage of which is transferred by Havoc) also deals a significant proportion of "your" damage (about 5% on the 359 4.1 Simcraft parse) but is largely the result of the Imp's Firebolts. So with the Imp contributing 25% of your damage, this means that the total damage you deal will be slightly lower than suggested, but a greater proportion of it will be on the Drake: 70% of your normal damage + 300% to Halfus instead of 68% to Drake + 320% to Halfus.

Guide above also shows BOH being recommended to use on main body before exposed head and before it goes up since dots should still do damage the boss regardless if they're targetable.

> Magmaw
> 
> Place BoH on the body of Magmaw right before he is chained down and his head is exposed, then place BoH on the head when he about to go back up.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=91986
https://cata-twinhead.twinstar.cz/?spell=85112
https://wowpedia.fandom.com/wiki/Burning_Embers_(original)?direction=prev&oldid=2977138

**Comment by bonfax4** [comment]
https://youtu.be/0Q7EDl69RQg?t=83 Closest i can find. Burning ember should be the lowest ticking dot on average unless corruption was not refreshed during high int proc and ticks faster aswell. Slowing down the video you can see a 1166 dot having it's damage transfered 1166x0.15 = 175 dmg at a pace faster than a corruption tick.

**Comment by UltraNix** [comment]
Fixed.
