### ISSUE TITLE
[Warrior] [PvP] Victory Rush procs from too many things

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3536]
**Description:**
Warrior's VR procs too easily.

**How to reproduce:**
Kill mage's water elemental and see that you get VR proc. Same thing happens to basically anything any player can summon except Mirror Image and Snake Trap. Iirc it works even with Bane of Doom imps, which is ridiculous.

**How it should work:**
That's the problematic part. Wowiki isn't very helpful about it as far as I can find. It should proc from SOME pets but not all and let alone not every guardian. Right now it procs from shaman's Feral Spirit wolves, priest's Shadowfiend, mage's Water Elemental and back on PTR (don't know if it's still a thing) even Gurthalak tentacle. 
Blizzard did awful job at distinguishing them because if mage's elemental procced it, then it'd be a clear distinction - pets do, guardians don't. But water elemental has his own ability bar, pet commands and yet isn't included. I think it'd be fine to just logically deduct that if even this doesn't proc it, then none guardian should but I'll try to find as much proof as I can. 

Little speculation: One of the videos I linked is Swifty's, who despite using Sweeping Strikes against unholy dk in his another guide, doesn't speak a word of VR. I'm focusing on that because DK dismissed/resummoned his ghoul every single time it was close to death so I can't find a concrete proof. But if we assume it doesn't proc it, then maybe it's because both ghoul and water ele are pets on cooldown, meaning only hunter's and warlock's should proc it.

Be that as it may, if water elemental certainly shouldn't, then Treants, Shadowfiend and Feral Spirit don't make any sense to proc it either.

**Retail proof:**
Hunter's pet proccing victory rush
https://youtu.be/RCw09vX1jZM?t=276
Water elemental not proccing victory rush
https://youtu.be/_jTeRZNE4nE?t=1272
Gurthalak tentacle not proccing victory rush
https://youtu.be/DkFDDrmqJUw?t=446
Treant not proccing Victory Rush (it's for a second out of screen but you can track warrior's buffs in slow motion, no VR appeared)
1 minute later same thing happened, you can see under druid's frame that at least one of treants died from bladestorm.
https://youtu.be/rEujIbgyRmg?t=178

**Comment by UltraNix** [comment]
Fixed.

**Comment by ussj10** [comment]
@UltraNix It still requires further fixing. Water Elemental continues to give warriors Victory Rush.

**Comment by UltraNix** [comment]
@ussj10 Okay.

**Comment by UltraNix** [comment]
Fixed.
