### ISSUE TITLE
ignite update time

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3542]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
after fix https://github.com/gamefreedomgit/Maelstrom/issues/3487
when ignite damage is not increased, ignite duration is not updated (or idk why)

**How to reproduce:**
use crit attack

**How it should work:**
Critical hit should always update time the ignite time

**Database links:**

**Comment by UltraNix** [comment]
No need to open a new ticket.
