### ISSUE TITLE
atonement bugged

### ISSUE THREAD

**Issue by ganandorf45** [gamefreedomgit/Maelstrom#3543]
the divine aegis of the disc priest procs even if the smite or the holy fire doesn't crit, there's a 100% chance to make it proc. another strange thing is that if i crit with my smite the atonement can result in a crit too so if i crit for 20k with a smite i can heal for 40k with the atonement, or if i don't crit with the smite there's the chance that the atonement will crit anyway.

**Comment by UltraNix** [comment]
Fixed.
