### ISSUE TITLE
Mongoose procs are bugged

### ISSUE THREAD

**Issue by Sneezlesnorf** [gamefreedomgit/Maelstrom#3544]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The proc on mongoose does no work correctly. I've field tested it in battlegrounds and I have recieved no procs, I also tested it on the training dummies although that didn't produce results either although I didn't expect it too. I believe the proc rate needs to increased or fixed it it works at all

**How to reproduce:**
Just attack anything with the enchant on

**How it should work:**
I believe the internal cooldown rate is 30 seconds on requiping and item, aside from that issue it should proc relatively often on mainhand attacks. And should have a similar proc rate to crusader. With prior field testing from other commenters on wowhead it claims that the weapon gets between 2.6-3.3 Procs per minute prior to instant attack strikes. And should be increased with them. 

**Database links:**
https://www.wowhead.com/item=22559/formula-enchant-weapon-mongoose#comments

**Comment by UltraNix** [comment]
Proc rate is okay - 1 PPM.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d923e036-9e21-41b8-9557-1079d57253b5)
