### ISSUE TITLE
Exiting dungeons with the Dungeon Searcher doesn't reapply flight form to druids

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3549]
**Description:**
When you use Dungeon Searcher to go to an instance, the "system" teleports you to the entrance of the location, saving where the player was initially. For druids this is a problem if they are in flight form, because when you exit the dungeon (leaving the group or using the eye option) you regain control of your character in mid-air, but without fligth form. If you have fast hands,, you can retransform in the middle of the air, but sometimes you get crushed into the soil like a warnerbros anvil :D

**How to reproduce:**
Leave a dungeon with the Searcher eye after you entered the dungeon while in flight form and midair.

**How it should work:**
The server must save the state of the player: if the character was mounted, you must reappear mounted, if you was transformed in bird, you appear as a bird...

**Database links:**
no links

**Comment by UltraNix** [comment]
Fixed.
