### ISSUE TITLE
There is a way to "break" the chat timestamps

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3550]
**Description:**
There is a way to "break" the chat timestamps. I don't know exactly which specific action break the timestamps. I am investigating this right now. The timestamp option in the interface menu shows "personalized" which isn't an option...
While the "personalized" option is active, the timestamps doesn't appear. I changed it to "15:27:32" and its working ok.

**How to reproduce:**
Dont know yet, I am testing right now. Maybe a problem with the global chat?
Disconnect the character:  doesn't triggers the bug.
Closing the game: 
Leaving global channel:
Changing class colors options:
Some addons?

**How it should work:**
The timestamp in the chat is an option that must be saved serverside, so I guess it could be a problem wiith any other action that block this.... More test must be done.  Maybe related with an strange bug that I found where I cannot rightclick on the chat...

**Database links:**
no links

**Photography:**
https://imgur.com/mfFyN7s (SORRY: I did the screenshot and the tooltip got in the middle... but if you zoom in you can read the "personalizado" option.

**Comment by UltraNix** [comment]
Chat timestamps has nothing to do with server.
