### ISSUE TITLE
BOE Items used for transmog should become Soulbound

### ISSUE THREAD

**Issue by initialactivity** [gamefreedomgit/Maelstrom#3551]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I transmog an item which is BOE, it should become Soulbound.

**How to reproduce:**
1 Buy BOE item which can be used for transmog. i.e. Heavy Copper Longsword.
2 Transmog your weapon into it. BOE does become soulbound.
3 Logout (!!) I logged in the next day to notice that the item is no longer soulbound but Bind on Equip.
4 Log back in to check

**How it should work:**
When I use BOE for transmog it should become soulbound.

**Database links:**

![WoWScrnShot_052123_202033](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/b3733093-94a9-4141-83e7-0a4f8cdf488c)
![WoWScrnShot_052123_202044](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/f1175438-d17e-4832-9b36-9b107918fdab)

**Comment by UltraNix** [comment]
Fixed.
