### ISSUE TITLE
Losing Flight and Dropping from Sky After Exiting a BG

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3553]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you enter a battleground while on your flying mount when you exit your flying no longer works and you  will drop from the sky. If you live you'll gain 310% movement speed while running on the ground even if you dismount. It is fixed once you remount, but you should lose flight and drop from the sky. 

**How to reproduce:**

**How it should work:**
Return to the position you were and remain flying 

**Database links:**

**Comment by UltraNix** [comment]
@ghost Can you tell what was the flying mount before the bg?
