### ISSUE TITLE
LVL 25  GUILD ACHEVEMENT BUG

### ISSUE THREAD

**Issue by rossariaa** [gamefreedomgit/Maelstrom#3555]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/75a7a2b8-c68a-424b-9aa7-287714af6227)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/b431dc1e-4235-42c9-9564-0f7e1ce5a714)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/bc53579c-74c7-483e-90a3-c7ecea1ba4bf)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/6ae2fd0f-1691-41b1-bad5-eeedf955beba)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/e81bd3af-5767-4645-85b1-b2c5dc02f188)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/c5a855a4-e7dc-4062-8864-1e5d01179ded)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134143002/6273d811-f2c9-4b07-91f1-07921f432b28)

**How to reproduce:**
WE reach lvl 25 guild and we didn t get our achievement so we can t get our exalted guild mount

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@rossariaa It it okay now?

**Comment by UltraNix** [comment]
No further info - closing.
