### ISSUE TITLE
The Race to Restock (drop percentage is too low)

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3557]
**Description:**
The drop percentage for [Amorous Mud Snapper](https://www.wowhead.com/item=69967/amorous-mud-snapper) and [Randy Smallfish](https://www.wowhead.com/item=69964/randy-smallfish) is too low. As commented in a post in wowhead:

"On average, it takes around 4-5 casts to complete this quest. Sometimes, it takes as few as 2, sometimes as many as 8. Easy quest."

Today I fished 116 times and its not completed yet!
EDIT1: I fished 138 times to finish the quest!

**How to reproduce:**
Simply try to catch those fishes, at any fishing skill level.

**How it should work:**
It must take around 4-5 casts to complete this quest.

**Database links:**
https://www.wowhead.com/quest=29348/the-race-to-restock
https://www.wowhead.com/item=69964/randy-smallfish
https://www.wowhead.com/item=69967/amorous-mud-snapper

**Photography:**
https://imgur.com/DdhoGtF
https://imgur.com/dRtP3gd

**Comment by UltraNix** [comment]
Fixed.
