### ISSUE TITLE
reputation bug maelstrom whitemane

### ISSUE THREAD

**Issue by sccsoul** [gamefreedomgit/Maelstrom#3558]
Reputation bug.

iam exalted to therazane, but it shows as hated.

can you pleace fix this bug for [me.

](https://imgur.com/r3iXQIf)

greetings Purpleheart

**Comment by sccsoul** [comment]
Its just that simple.


Thanks for the help much appreciated.

Op ma 22 mei 2023 18:19 schreef xmrshoot ***@***.***>:

**Comment by xmrshoot** [comment]
so its not a bug , u can close it @Sketish
