### ISSUE TITLE
Buying/selecting items in quantity is bugged

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3559]
**Description:**
When you buy (in any vendor, in any place, any item), or when  you select items from inventory, you can use SHIFT+click to specify a quantity to buy/select. Usually you can click on the text box and change the quantity writing any needed quantity. This is not happening.

**How to reproduce:**
Try o buy something form a vendor with SHIFT+click. You cannot click on the text box and write a number.

**How it should work:**
SHIFT+click on any item. Click on the text box. Write a number. The number changes.

**Database links:**
no database links

**Comment by Alandiel** [comment]
Works fine for me. You don't have to even click on text box to change quantity. Try disabling addons.

**Comment by EdyGlockenspiel** [comment]
When I tried to buy 20 of a food item at a vendor, it bought 20 *STACKS* of 5 instead of 20 of the item. This is also the case where if I want just one, it will buy 5 if it is default sold in 5s. This should not work this way.

**Comment by varjla** [comment]
No idea about how to replicate the bug. After disconnect the character, the bug dissapeared for good.
