### ISSUE TITLE
NPC "Minx"

### ISSUE THREAD

**Issue by bovanova1** [gamefreedomgit/Maelstrom#3562]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
NPC Minx gets killed easily. 

**How to reproduce:**
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/106834485/3b860b8f-a70e-4a07-9d5b-73c7344406aa)

**How it should work:**
Shes supposed to end the quest "[Minx'll Fix It](https://www.wowhead.com/quest=25649/minxll-fix-it)" but gets killed super easly

**Database links:**
https://www.wowhead.com/npc=40881

**Comment by UltraNix** [comment]
#2928
