### ISSUE TITLE
Guilds (Guild Panels) are broken right now.

### ISSUE THREAD

**Issue by randomtester44** [gamefreedomgit/Maelstrom#3564]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When you open guild panel, you can see massive gaps between members, and you can only see like ~10-20% of people that are actually in guild.
This started once guild member cap came in changelog. Guild has 989 members at the point of screenshots.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/a431cbf2-b443-4b2f-9106-960cdc09267a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/1f539d7a-215a-418e-881e-4e122b8216f2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/bb056a56-63ac-47c4-9ad3-013d031ee123)
Count in the right corner showing how many people are online is correct, but you can only see a few of those people in guild panel.
Checked with /who command. Some of those people on /who list can't even be found in guild panel.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133038299/301d15ae-6e5d-4529-887b-30631334d64e)
Same thing happens when you try **starting the game without any addons.**

**How to reproduce:** Check description, self explanatory.

**How it should work:** You should be able to see all people in your guild on guild panel. Both online and offline members.

**Database links:**

**Comment by itsemmastone** [comment]
https://github.com/gamefreedomgit/gamefreedom-cata/commit/22482318e5f201d3f4916a6a4852cd62ae158a5f

**Comment by randomtester44** [comment]
Still having the same issue. (just a feedback)
