### ISSUE TITLE
The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Norainex** [gamefreedomgit/Maelstrom#3565]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest is bugged cannot talk to the npc 

**How to reproduce:**
You need to talk to an npc and click a dialog option but nothing happens when you click it

**How it should work:**
Should ne able to talk to the npc so the exorcism can begin

**Database links:**
https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules#

**Comment by bogdanian** [comment]
Can confirm that upon talking to the NPC nothing happens

**Comment by JustSimplePerson** [comment]
Still the same issue. Any chances to fix it? It make quest achievement in Hellfire Peninsula impossible to obtain.

**Comment by PanJanuszek** [comment]
Fixes after restart
