### ISSUE TITLE
Shiny stones in Thunder Bluff detected with mining skill without the quest

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3570]
**Description:**
The item [Shiny Stones](https://www.wowhead.com/item=69983/shiny-stone) is detected by mining minimap skill even when the quest is not active.

**How to reproduce:**
Get mining skill, walk arround Thunder Bluff and look at the minimap.

**How it should work:**
The minin skill must detect them? I am not sure, but for sure it only must happen when you have the proper quest on the inventory: [Shiny Baubles](https://www.wowhead.com/quest=29354/shiny-baubles).

In other hand: the quest has not POI on the map when you have the 20 stones (it should have a golden interrogation mark @35.0, 55.0 in Mulgore.

**Database links:**
https://www.wowhead.com/item=69983/shiny-stone
https://www.wowhead.com/quest=29354/shiny-baubles

**Comment by UltraNix** [comment]
Fixed.
