### ISSUE TITLE
Mulgore mining spot under texture @59.9, 36.4

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3571]
**Description:**
Copper ore mining spot under texture @59.9, 36.4. It generates a very time consuming spot, because it appears outside (golden not-faded point) if you see it from outside (and you can see the sparks) but you can see the spot golden and not-faded from the INSIDE of the mine. Low miners will spend much time here, searching.

**How to reproduce:**
Go to the coords, near the entrance of a mine (must have flying skill or cross the mine).

**How it should work:**
The mining spot must be 5 yards upper to click it.

**Database links:**
no links

**Comment by Afgann** [comment]
fixed
