### ISSUE TITLE
Sometimes (rarely) mining spots "have nothing"

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3572]
**Description:**
Sometimes (this is the second time I get this) some mining spots are "empty", and the lootbox doesn't open (sometimes a chest or an enemy could be empty and "lootable", but in that case the loot modal box opens briefly). This is a very rare event. 

**How to reproduce:**
Mining a lot. When you are mining, you rightclick on the ore, the castbar appears, it finish the cast, but nothing happens, the loot modal box is not open. But you can reclick on the ore and you can "mine" it again, getting the items. No "failed attemp", there isn't another player getting it at the same time... itis rare. I will continue my mining test to send more proofs.

**How it should work:**
A mining spot never come empty. If empty, it must dissapear.

**Database links:**
No links

**Photography:**
Mulgore: @54.2, 16.2
https://imgur.com/a/cJR3yCN

**Comment by UltraNix** [comment]
@varjla Maybe you moved/rotate a little bit?

**Comment by UltraNix** [comment]
No further info - closing.
