### ISSUE TITLE
Durotar resource spots under texture @38.0, 26.4; @44.3, 24.4; @41.0, 25.7; @40.2, 26.3; @38.3, 32.3; @42.7, 14.3; and @28.7, 24.1

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3573]
**Description:**
x2 Double Copper ore mining spot under texture @38.0, 26.4 and @44.3, 24.4 on Durotar. It generates a very time consuming spots, because they appear near a lake, and the only way to "explore underwater" for low level players is to jump into water, discover the ores are not there and at last, swim all the way out of the "lake" hundreds of yards south of this point. Really annoying.

There is another bugged Copper ore spot @28.7, 24.1

Earth root herbalism point under textures:
@41.0, 25.7
@40.2, 26.3

Peace flower herbalism point under textures:
@38.3, 32.3

Silverleaf herbalism point under textures:
@42.7, 14.3

**How to reproduce:**
Go to the coords, near the submerged kodo Thunder Ridge and near the entrance of Orgrimar.

**How it should work:**
The resource spots must be ?? yards upper or lower to click it correctly (and maybe, not two, but that is at your wish).

**Database links:**
no links

**Comment by UltraNix** [comment]
Fixed.
