### ISSUE TITLE
PET BM BUG

### ISSUE THREAD

**Issue by Noak1234** [gamefreedomgit/Maelstrom#3575]
Description:
When using any buff from exotics pets for example "Roar of Sacrifice" the Pet  will stop attacking the target and becomes passive, It won't attack the target anymore until the pet is dismissed and summoned again, 

How to reproduce:
https://youtu.be/hWnLfanzlbA

**Comment by UltraNix** [comment]
@Noak1234 What is your macro to use Roar of Sacrifice?

**Comment by Noak1234** [comment]
> 

/cast [@Noak] Roar of Sacrifice

**Comment by UltraNix** [comment]
Tested and cannot reproduce it with Shale Spider.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f17363be-2d2b-4a23-8897-84ec694625bb)

**Comment by UltraNix** [comment]
The same with Arcturis.

**Comment by Noak1234** [comment]
> 

I log in and show you

**Comment by Noak1234** [comment]
> [UltraNix](/UltraNix)

Try hitting the character and then you roar, I think that if only the pet hits and the hunter doesn't, that bug won't happen

**Comment by UltraNix** [comment]
@Noak1234 Poke me on Discord.

**Comment by UltraNix** [comment]
Fixed.
