### ISSUE TITLE
New equipped bag is not usable until disconnection of the character

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3576]
**Description:**
When you equip a new bag (crafted or buyed) you cannot open it, the modal box is not open with the rest of the bags. It occurs in the bank and in the personal bag slots.

**How to reproduce:**
Get a new bag (crafted, buyed or robbed - use magnets as necesary to get one), equip it replacing a new bag or in an empty slot. Try to open it.

**How it should work:**
Equipped bags must work properly at the very moment you have the bag equipped.

**Database links:**
no links

Additional info: 

The [Mammoth Mining Bag](https://www.wowhead.com/wotlk/item=38347/mammoth-mining-bag) get the same bug, but it doesn't work even if you use the command /reload.

**Comment by UltraNix** [comment]
Tested - works okay.
