### ISSUE TITLE
Dungeon Finder bugged sometimes: used instances

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3578]
**Description:**
Sometimes (10% of the times) the Dungeon Finder joins 5 people to a empty dungeon (can have some optional bosses or NPCs alive) without the last boss. An "used" instance.

**How to reproduce:**
Randomly with the dungeon finder

**How it should work:**
When a dungeon last boss is killed, the dungeon internal ID must die with the last boss(marked as tainted or something similar).

**Database links:**
No database link

For history purposes I finded this bug in:
Wailing caverns
Scarlet monastery: cemetery
Throne of the Tides

**Comment by UltraNix** [comment]
#771
