### ISSUE TITLE
[Warlock] Imp and Succubus issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3580]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Imp:
- Imp should not be able to do melee autos. 
- Imp abilities Flee and Singe Magic not being prioritized over firebolt when used.
- Flee is not working at all, pet is not jumping to your location.
- If I cast Singe Magic without a valid dispel target, my imp stops castings firebolt and starts meleeing his target instead.

Succubus:

-Succubus should not be able to do melee autos. She currently does both her basic attack and melee autos, increasing her damage output by a lot if she's in melee range.

**How to reproduce:**

1. Disable firebolt and send pet to attack.
2. Try to use pet abilities while imp is casting firebolts.

**How it should work:**

- Imp and Succubus should not be able to melee
- Pet Special abilities should be prioritized over firebolt, canceling firebolt if used while imp is casting.
- Succubus should only use lash of pain as her auto attack.

https://www.mmo-champion.com/threads/843071-One-pet-to-rule-them-all?highlight=succubus+lash+of+pain
> As the Succubus and the Imp have no other attack than LoP and Firebolt, both glyphs effectively increase their dps by 25 and 20%. Glyph of Felguard increases its dps by 1%. Glyph of Felhunter actually increases nothing.

https://wowpedia.fandom.com/wiki/Imp_(warlock_minion)?oldid=2891565
> A common mistake some warlocks make is to tell their Imp to attack when Firebolt isn't set to [auto-cast](https://wowpedia.fandom.com/wiki/Auto-cast). Since Firebolt is the Imp's only attack form, this gives it nothing to do; right-click on the Firebolt button to fix it. An Imp will also not attack if it is out of mana; it will also refuse to attack [mobs](https://wowpedia.fandom.com/wiki/Mob) that are [immune](https://wowpedia.fandom.com/wiki/Immune) to [fire](https://wowpedia.fandom.com/wiki/Fire).

https://www.wowhead.com/spell=7814/lash-of-pain#comments
> 20 yard range in Cataclysm, as well as no cooldown. If you turn it off of auto-cast she won't do anything and just stand there (just like the Imp when you turn Firebolt off of auto-cast). So she no longer causes physical damage, and only causes shadow damage and lashes once every 2 seconds (Lash of Pain global cooldown).

https://youtu.be/vdnk24v7YJg?t=380
Watch succubus auto attacking in any of Cobrak ( Known retail pvp Warlock player ) cata duels/videos. It stands at range spamming lash of pains.

https://www.youtube.com/watch?v=5NM15jXO15M
Imp using abilities mid-cast.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=7814
https://cata-twinhead.twinstar.cz/?spell=3110
https://cata-twinhead.twinstar.cz/?spell=89808
https://cata-twinhead.twinstar.cz/?spell=93282
https://cata-twinhead.twinstar.cz/?spell=93282

**Comment by EdyGlockenspiel** [comment]
I am pretty sure the imp is the only pet without an auto attack. I am 97.6% sure the Succubus always could auto attack, even with Lash of Pain.

**Comment by bonfax4** [comment]
Watch any cata warlock pvp video and see if you come back to the same conclusion. Succubus lost her auto attack on cata

**Comment by EdyGlockenspiel** [comment]
My knowledge of most classes outside of DK for cata is very limited. I know in wrath she has it and I know in later versions she does, like WoD. If it's true she does not in *just* cata or even mop that would be a very weird change by blizzard.

**Comment by EdyGlockenspiel** [comment]
Just watched the video and now I understand, lash has literally no CD where as the version of LoP I am use to has a like 3sec CD or something, so she should auto attack in-between casts of the ability. Since she can use it every 1.5 sec (the base GCD) I can see why she would not auto attack, since back in the day a lot of attacks reset your swing timer, this included pet abilities. 

Also reading the description "Lash of Pain doesn't have a cooldown and now has a 20 yard range, The succubus' base attack now and she no longer causes physical damage, if you turn it off of auto-cast she will just stand there (Like the Imp without Firebolt)" so they legit did remove her auto attack completely in 4.0.. huh.

**Comment by bonfax4** [comment]
Seems mostly fine but i see that succubus still runs into melee range to lash of pain spam. She should only run up to her maximum lash of pain range (20y). Has its benefits in pvp as in avoiding rogue seduction kicks or the pet running in too deep.

**Comment by UltraNix** [comment]
Fixed.
