### ISSUE TITLE
[Druid] Feral Blood in the Water talent

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rip is not recalculating rip dmg on refresh. It maintains the same amount of damage.

**How to reproduce:**
Refresh rip using ferocious bite during trinket procs or Tiger's fury on a target below 25%.

**How it should work:**
Rip damage should be recalculated when refreshed via the talent.

https://www.mmo-champion.com/threads/874192-Blood-in-the-Water-Tiger-s-Fury-amp-Trinket-Proc-s?highlight=blood+in+the+water

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
@UltraNix Needs to be revisited. The refresh now is currenty taking into account ferocious bite combo points and it should not. a 1 point ferocious bite should still refresh back up to 5 combo rip if that was the original duration. Also noticed the refresh is always putting rip back to max 5 point duration even when the refreshed rip has lower cp's and does lower dmg.

**Comment by UltraNix** [comment]
@bonfax4 Please, poke me on Discord.

**Comment by UltraNix** [comment]
Fixed.
