### ISSUE TITLE
Desolace resource spots under texture @65.7, 49.4; @53.6, 32.1; @63.2, 41.8;

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3582]
**Description:**
Some spots on desolace are under textures, here is the list (will be updated soon)
Iron deposit + liferoot: @65.7, 49.4;
Golden deposit: @53.6, 32.1
Iron deposit x2: @63.2, 41.8;

**How to reproduce:**
Go to the coords, noone can loot them.

**How it should work:**
The resource spots must be ?? yards upper or lower to click it correctly (and maybe, not two, but that is at your wish).

**Database links:**
no links

**Comment by Afgann** [comment]
fixed
