### ISSUE TITLE
Cat/bear druid broken HUD after some quest with "vehicles" in Hyjal

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3586]
Same issue as https://github.com/gamefreedomgit/Maelstrom/issues/3521

**Description:**
After doing the Hyjal questchain where you start asking questions with a Yes/No interface. if you are druid and transform to cat, you get your hud totally broken, getting the "yes/no vehicle hud" but the cat/bear skills. In other transofrmations the hud doesn't appear. Seems an error with the cat/bear action bars. /reload command seems to solve the problem. so its a minor issue.

The same happens with [The Greater of Two Evils](https://www.wowhead.com/quest=25310/the-greater-of-two-evils)

**How to reproduce:**
Complete the quests [Mental Training: Speaking the Truth to Power](https://www.wowhead.com/quest=25299/mental-training-speaking-the-truth-to-power) or [The Greater of Two Evils](https://www.wowhead.com/quest=25310/the-greater-of-two-evils), then transform yourself in a cat/bear.

**How it should work:**
This kind of quest must give the HUD only during quest, not until reload :D

**Database links:**
https://www.wowhead.com/quest=25299/mental-training-speaking-the-truth-to-power
https://www.wowhead.com/quest=25310/the-greater-of-two-evils

**Comment by UltraNix** [comment]
Fixed.
