### ISSUE TITLE
Quest: "Last ditch effort"

### ISSUE THREAD

**Issue by bovanova1** [gamefreedomgit/Maelstrom#3587]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stonetalon Mountains

**How to reproduce:**
Accept quest

**How it should work:**
When you accept the quest the NPC "master thal'darah" is supposed to take you on a flight to the Thal'darah grove. While you fly to there you see a giant balloon with a bomb that destroys the mentioned grove... then you fly back 

**Database links:**
https://www.wowhead.com/quest=25891/last-ditch-effort
https://www.youtube.com/watch?v=NQwLKD7EBq0

**Comment by UltraNix** [comment]
#2918
