### ISSUE TITLE
80-84 pvp bracket secondary stats and heirlooms

### ISSUE THREAD

**Issue by scias300** [gamefreedomgit/Maelstrom#3588]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1. Secondary stats in this bracket seems to work quite strange that leads to lots of classes that benefit from mastery like mages deal enormous damage at lvl 80-81 compairing even to 84. I lvled couple to test it after getting 45k ice lance crit on my 84 dk by 81 mage on BG. Turned out the problem is secondary stats and not the mages but examples are still mages because you need some time to gear and I just want to show the problem, at least it seems to me like one.
I think the number will say more about it.
![WoWScrnShot_052423_125307](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/a089b2b8-7650-42eb-a8de-7cf673256680)
![WoWScrnShot_052423_130149](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/56a338f9-34aa-4f3c-9e53-fffb4feeb79d)
![WoWScrnShot_052423_130202](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/a9aef20e-cdc8-4f87-b220-4c9102081fad)
![WoWScrnShot_052423_130340](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/0c36d64b-00ef-4b99-a1b4-81747d055e83)

2. Heirloom weapons are bugged at 84 lvl and seem to keep lvling after 80 even if its not visible in item stats. You can see the damage increases when I switch from 333 ilvl weapon to heirloom weapon. It strongly affects classes that rely on weapon dmg and a little surprisinly for me also especially feral druids.
![WoWScrnShot_052423_133913](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/ffd2e911-cb48-44ef-9fea-1e3c2b7e68d8)
![WoWScrnShot_052423_133909](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/5cb5af11-b42b-4fb2-b66e-a95f2e3b694a)
![WoWScrnShot_052423_133916](https://github.com/gamefreedomgit/Maelstrom/assets/47593082/932ddf02-595c-47d2-afc5-dd72cea441ab)

**Comment by UltraNix** [comment]
Fixed.
