### ISSUE TITLE
SPELL_AURA_REMOVED for shield have false information

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#3589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When a shield is removed due to absorbed damage, the event SPELL_AURA_REMOVED is supposed to give the remaining amount of absorb on the shield when it fades which is 0. But right now it gives the amount of absorb before the damage occurs.

This was working fine on May 2 and started not working somewhere before May 8.

**How to reproduce:**
Just check any logs and look for a SPELL_AURA_REMOVED followed by an event where there is absorb (SPELL_DAMAGE,SWING_DAMAGE, SWING_MISSED,...)

**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3a09e4e0-ccbc-40d6-84b7-ef48d167eb5f)
We can see here that the bdk gains 27760 of blood shield absorb, and 0.2s after he gets hit bt a melee that deals 56253 damage (27760 absorbed + 28493 damage taken), but the event thats show the removal of the shield still says that there is 27760 of absorb on it when it fades.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
