### ISSUE TITLE
[Hunter] [Pet] [Scaling] [Pet damage] [Pet Armor] [Pet Damage reduction %]

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3592]
Hello, just  a first attempt to post a what I believe it is a bug with the hunter pet damage and pet damage scaling, the "so called" tests I did was on beast mastery hunter only and it follows:

Description:
Outside dungeon/raid I believe the white damage (base damage without equipped gear) and scale are not working as intended.

How to reproduce:
I will not go into further detail unless I am required to(it involves a different server) a dwarf hunter vs worgen hunter without any equipment.

How it should work:
I found 2 sites/forum post that mention the pet scaling for this example of ferocity family "Ferocity (damage) -- 50% of master's AP, 40% health, 50% armor" and the other one, a forum post that claims "Ferocity Pet Scaling * 42.5% of hunter attack power"
The testing involves exact talents in both cases, all clickable spells disabled (Rabid, Roar of Courage), dwarven and Worgen hunters who have slight difference in strength and agility, agility for the dwarf and strength for the Worgen.

Dwarven hunter (697 RAP) pet spirit beast: 519-760 white damage(351.9 dps) attack power 1228, Attack Speed 1.82
Worgen hunter (556 RAP) pet spirt beast: 365-434 white damage(220 dps) attack power 1134, Attack Speed 1.82
Above listed is the base stats I get on both characters pets
Dwarven hunter (5260 RAP with Aspect of the Hawk and improved 3/3 One with Nature talent (4563 from aspect alone)), the spirit gets 1939 RAP from the aspect alone(ignore the base rap from the hunter) or **42.494%** of the hunter RAP.

(Whitemane server / our server) 
Worgen hunter(5120 RAP with Aspect of the Hawk and improved 3/3 One with Nature talent (4564 from aspect alone)),  the spirit gets 1004 RAP from the aspect alone(ignore the base rap from the hunter) or **21.998%** of the hunter RAP.

Comparison with equipped items white damage status
Dwarven 14994 RAP, pet 7304 or 48.71% of the hunter power.
Worgen 16672 RAP, pet 4679 or 28.065% of the hunter power.
**Database links:**
[http://thehuntersrefuge.blogspot.com/2010/09/pet-scaling-in-cataclysm.html](url)
[https://forums.wow-petopia.com/viewtopic.php?t=4893](url)

**Comment by nkopala2011** [comment]
About that I want speak about how insane is the bug in low level. Lvl 20-24 characters with pets with 2.2k or 1.8k when blizzlike must be almost 700hp.

Compare the hp of this pet from Whitemine and this video from a retail official world of warcraft server.

![WoWScrnShot_052423_161931](https://github.com/gamefreedomgit/Maelstrom/assets/134552421/5d6a8918-a8f1-469b-956f-8e71e725ee3b)
![WoWScrnShot_052423_162012](https://github.com/gamefreedomgit/Maelstrom/assets/134552421/f1e019c2-cb43-4e93-bbbf-61db16ef1fe2)
![WoWScrnShot_052423_161849](https://github.com/gamefreedomgit/Maelstrom/assets/134552421/0d240cab-7e24-4b25-b2a7-2bdfa0e36cba)

Compare with this video of blizzlike official WoW server cataclysm 4.3.4: 
https://yewtu.be/watch?v=rOZ0JbU-HDg

**Comment by nkopala2011** [comment]
I want to say the pet of warlocks have the same but, but apparently is just for health I cant say if is just for health and not for damage, is needed revision. But clearly their health scaling is bug too.

**Comment by UltraNix** [comment]
The report is about pets < 85 lvl?

**Comment by nkopala2011** [comment]
> I want to say the pet of warlocks have the same but, but apparently is just for health I cant say if is just for health and not for damage, is needed revision. But clearly their health scaling is bug too.

is a general bug, affect every pet in the game included, warlock pet, and hunter pet scaling damage and healing. The issue is more easy to recognice in low level because the pets kill everyone without any sense, without defense.

**Comment by NinacS90** [comment]
The report is about 85 level pets Ultra

**Comment by NinacS90** [comment]
Image 1.1 shows an example of Maelstrom ranged attack power
![1 1](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/ba875207-7f60-49a3-99c5-2d35f08e1f0c)
Image 2.1 shows an example of well, a different hunter for comparison
 
Image 1.2 shows the pet gets only  21.996% of the hunter's rap
![1 2](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/65dfbb49-54e0-47da-b65b-7edf9e9a81e9)
Image 2.2 shows the pet gets 48.712% of the hunter's rap(Don't ask me where the other 400 ap went, is there diminishing returns for the pet?)
69.997%
Image 1.3 shows the hunter armor and armor scaling, however 1.4 will be posted below, that image shows the pet gets only around 50% of the armor, so tooltip error at the hunter, or incorrect armor scaling?
![1 3](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/fc6a585b-7eba-4564-9b93-8a63ca04b71f)
![1 4](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/0020c6e5-7126-40a4-b0eb-4d40457cd11f)

Image 2.3 is from the comparison hunter and you can see on the image that the pet has 1608 more base armor, not significant, but why not put it out there since we are here
Image 2.4 shows the pet screen from the comparison hunter
![2 3](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/5bc0971a-1344-415f-93db-1f86e0620e4e)
![2 4](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/2d638030-216c-4ad0-af86-a84ecec64b36)

Getting back to main course link I provided the huntersrefuge...... its stated that ferocity family of pets get 
> Ferocity (damage) -- 50% of master's AP, 40% health, 50% armor
Is it possible to check which formula applies for patch 4.3.4, I have tried searching the old patch notes but aside from spell changes I do not believe to have seen anything regarding the pet scaling, that being said if the armor scale is greater than 50% then Maelstrom pets lack at level 85 1608 base armor and whatever the % is from the hunter, since the tooltip like I mentioned above shows it at 10103 hunter to pet which is 69.999% but come to think of it, I can just log on and check tenacity pets stats.

**Comment by Pornoodemon** [comment]
Pets of death knights, they are also concerned

**Comment by NinacS90** [comment]
Found another video, https://www.youtube.com/watch?v=9znbWaJRB1Q 

I made a testing hunter on the ptr and gave myself exactly the same gear and what I couldn't get around with the commands or the vendor I tried to get as close as possible, with a difference of only 9 Rap, the damage output of the ptr pet is 1102 - 1171(1136 average) while the other testing hunter has 1927 - 2168(2047 average).

The video linked above shows the hunter has 356ilvl, with 15155 rap with no other buffs and currently on my hunter on the main server with nearly 20K rap I can barely do 50% of the damage at 12:58(starting dummy attack)

**Comment by NinacS90** [comment]
I found another video, unfortunately the uploader did not open the pet tab but the hunter rap can be clearly seen, also the mastery.
https://www.youtube.com/watch?v=euc4P0HS_TU
He has a segment/chapter where he demonstrates on a target dummy and in the beginning and at the macro part of the video he shows that he has the pet talent "Rabid" on manual cast which makes it a lot easier to spot the white damage.

He has roar of courage 100% uptime and while his 'burst' macro is offline I can see the following stats:
Rap: 16718
Mastery:10.79 or 17% damage increase

Comparing to my hunter
Rap: 19134 (only roar of courage 100% uptime)
Mastery:14.10 or 23% damage increase

Rap percentage difference is 13.478% and 2416 difference in ap
6% higher pet damage from mastery

And ingame test on a target dummy for the pass 8 minutes(almost) 366 hits with the following results:
Normal hits
 - Minimum = 1041
 - Critical = 1125
 - Average = 1090

**Comment by NinacS90** [comment]
Hello @UltraNix I hope you haven't given up hope on this issue and you will give it another look when time allows it, I made a character on an instant wotlk server  so I can make some comparison between the talent specs & expansions.
![wotlk comparison](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/bbcb5358-0c57-451f-b60d-9cf3ddb58d61)
Can you please check how much of the hunter rap the pet get on our server? I just did now and its 22% and its the same as wotlk.
"Pets receive attribute bonuses at 15% of their master's/mistress' stats:"
"1 ranged attack power gives the pet 0.22 AP and 0.1287 spell damage (0.338 AP and 0.18 spell damage with 2/2 Wild Hunt"
https://wowwiki-archive.fandom.com/wiki/Hunter_pet

Now while the MM hunter in wotlk has access to higher ap due to the aura, combat experience 2/2, BM hunter has additional modifiers from the talents, Unleashed Fury 15%, Kindred Spirits 20%, Wild Hunt 2/2(30% more ap) and extra pet talent point in Shark Attack which allows the pet to have nearly 88% more damage(not counting the aura from the mm hunter), on the image the damage output the aura is included.

What I am trying desperately to point out, in wotlk you had all these modifiers and you could buff the pet with kings, blessing of might, gift of the wild, battle shout, etc however, as Cataclysm hit, they made the game a lot more simpler, they removed most of the damage modifiers from the hunter talents(kept the pet ones) and disabled the ability to buff the pets, so instead they increased the % of stats they inherit from the hunter, going further back, I suggest we take a look at 
[http://thehuntersrefuge.blogspot.com/2010/09/pet-scaling-in-cataclysm.html](https://github.com/gamefreedomgit/Maelstrom/issues/url) I believe he made accurate predictions and please consider looking at the damage table and consider that he probably did not have max level or gear. but going again to compare a hunter from a different cata server from the image above and while my hunter isn't endgame geared, I have around 20k ap, and the damage is still not even close, with 12.37 mastery 1.4k damage from the pet.

20k ap vs 15k ap
11.98% mastery vs 12.37% mastery
Maelstrom hunter: 1444-1517 (with roar of courage on)
Comparison hunter:2042-2298 (without roar of courage)
https://www.youtube.com/watch?v=9znbWaJRB1Q its very loud, volume warning, at the rotation segment near the end, he starts with roar of courage and call of the wild which gets him to 18.xxx ap and before pet rabid takes off, he starts hitting with 2k on the target, also those targets, they have some base armor don't they? To throw off physical damage off so whatever damage reduction they have and first two hits yielded 4 hits yielded 2k hits and 4k crit, after that I ignore it due to rabid and trinket agility build up and he didn't use bestial wrath and the pet charge(bonus 25% attack on the next hit) missed

Thank you!

**Comment by UltraNix** [comment]
Fixed.
