### ISSUE TITLE
Serpents and Poison

### ISSUE THREAD

**Issue by acko2469** [gamefreedomgit/Maelstrom#3594]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest not working - "Serpents and Poison"

**How to reproduce:**
Killing the mobs and healing adventurers not working

**How it should work:**
When the mobs are killed and adventurers healed the quest should be completed

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29103

**Comment by MrTide** [comment]
dublicate

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/fd673b17-ab17-466b-ba49-fdbabe295ede)
Just tested - works okay.

**Comment by MrTide** [comment]
reopening the issue quest still has issues 
players are unable to see the npcs 
by the look of it they are in wrong phase 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/36106057/689f0b94-0ef8-4d1e-b1e3-d95b16d8942a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/36106057/689f0b94-0ef8-4d1e-b1e3-d95b16d8942a)

**Comment by PanJanuszek** [comment]
Fixed after update
