### ISSUE TITLE
Bad Supplies

### ISSUE THREAD

**Issue by acko2469** [gamefreedomgit/Maelstrom#3596]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest not working - "Bad Supplies"

**How to reproduce:**
When you click on Grain Sack the Zanzil appears he speaks and the quest is not completed

**How it should work:**
When you click on Grain Sack the Zanzil appears he speaks and the quest should be completed 

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29151

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b662e32a-3f0f-463a-a164-957b1070ec70)
Just tested - works okay.
