### ISSUE TITLE
Making Contact

### ISSUE THREAD

**Issue by acko2469** [gamefreedomgit/Maelstrom#3597]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest not working - "Making Contact" 

**How to reproduce:**
Cannot find the NPC to speak with in Booty Bay

**How it should work:**
There should be NPC to complete quest at Booty Bay

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29152

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/41474659-8fee-4aac-b32a-917e8eeac9d7)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a397fb6f-46f8-4359-adae-5c5bd67c48bf)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9815ab99-79fd-4c6d-bf21-98d62d583373)
Just tested - works okay.
