### ISSUE TITLE
[Quest][Horde] The Zandalari Menace quest chain (multiple issues)

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#3598]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1. Killing mobs and healing headhunters for the quest "Serpents and Poison" gives no credit towards quest completion.
2. The objective "Use the bonfire near Bambala" for the quest "Spirits Are With Us" does not complete after interacting with the bonfire and viewing the interaction with High Priest Venoxis.
3. The objective "Find Mauti's Lair" for the quest "Follow That Cat" does not complete upon reaching the destination.
4. The objective "Bwemba has inspected the Cat" for the quest "Mauti" does not give completion. Upon killing Mauti, there is no option when speaking to Bwemba's spirit to have her inspect the corpse. The small interaction with High Priestess Kilnara automatically plays.
5. For the quest "Bury Me With Me Boots...", after picking up the boots off the floor behind Grent you are no longer able to turn in the quest. The NPC remains with a white ? over their head. (Possible bad interaction with the quest "Some Good Will Come" which is immediately available upon reaching the lair.)
6. The objective "Arrived at Hardwrench Hideaway" does not complete after reaching the area of Hardwrench Hideaway.
7. Killing Hideaway Zombies and having Bwemba change them into Hardwrench Zombie Survivors does not give credit towards quest completion. The Survivors also have the models of Dwarves, which would be applicable to the Alliance version of the quest.
8. Inspecting the Sack of Spices in the house at Hardwrench Hideaway plays the interaction with Zanzil, but does not complete the objective "Supplies Searched" for the quest "Bad Supplies".
9. After arriving in Booty Bay for the quest "Making Contact", there are no NPCs in town whatsoever, not even Baron Revilgaz who is needed to complete the quest. This makes "Making Contact" and "Bwemba's Spirit" both impossible to complete and prevents the completion of the final two quests in the chain, "Booty Bay's Interests" and "A Shiny Reward".

**How to reproduce:**
1. Accept quest and kill a Jungle Serpent or heal a poisoned headhunter and receive zero credit.
2. Accept quest and use the bonfire near Bambala.
3. Accept quest and proceed to the lair. Upon arrival, no quest objective completion is given.
4. Accept quest and kill Mauti.
5. Accept quest from Grent. Collect his boots from the cave behind him and attempt to turn in the quest.
6. Accept quest and proceed to Hardwrench Hideaway.
7. Accept quest. Kill a Hideaway Zombie and watch it turn into a Hardwrench Zombie Survivor and run off.
8. Accept quest and interact with the Sack of Spices.
10. Accept quest and head to Booty Bay. After reaching the inn and proceeding to the top, no NPCs are present.

**How it should work:**
1. Accept quest and kill a Jungle Serpent or heal a poisoned headhunter and receive credit for each kill or heal.
2. Accept quest and use the bonfire near Bambala. An interaction with High Priest Venoxis should play and the objective should complete after.
3. Accept quest and proceed to the lair. Upon arrival, objective completion is given.
4. Accept quest and kill Mauti. Speak to Bwemba's spirit to have her inspect the corpse. Upon doing so, the interaction with Kilnara should occur and the objective should complete after.
5. Accept quest from Grent. Collect his boots from the cave behind him and turn in the quest.
6. Accept quest and proceed to Hardwrench Hideaway. The objective "Arrived at Hardwrench Hideaway" should complete upon reaching the area.
7. Accept quest. Damage a Hideaway Zombie to under 10% and Bwemba purifies the zombie, changing it into a Hardwrench Zombie Survivor and giving credit towards the objective "0/10 Hideaway Survivors Rescued".
8. Accept quest and interact with the Sack of Spices. A small interaction with Zanzil will play, and afterwards the objective "Supplies Searched" should complete.
9. Accept quest and head to Booty Bay. After reaching the inn and proceeding to the top, an interaction between Vol'jin, Bwemba, and Baron Revilgaz should occur, completing the objectives for both "Making Contact" and "Bwemba's Spirit". The quest "Booty Bay's Interests" should then become available from Baron Revilgaz.

**Database links:**
1. https://cata-twinhead.twinstar.cz/?quest=29221
    https://wowpedia.fandom.com/wiki/Serpents_and_Poison
2. https://cata-twinhead.twinstar.cz/?quest=29222
    https://wowpedia.fandom.com/wiki/Spirits_Are_With_Us
3. https://cata-twinhead.twinstar.cz/?quest=29228
    https://wowpedia.fandom.com/wiki/Follow_that_Cat
4. https://cata-twinhead.twinstar.cz/?quest=29230
    https://wowpedia.fandom.com/wiki/Mauti_(quest)
5. https://cata-twinhead.twinstar.cz/?quest=29232
    https://wowpedia.fandom.com/wiki/Bury_Me_With_Me_Boots..._(Horde)
6. https://cata-twinhead.twinstar.cz/?quest=29236
    https://wowpedia.fandom.com/wiki/To_Hardwrench_Hideaway
7. https://cata-twinhead.twinstar.cz/?quest=29237
    https://wowpedia.fandom.com/wiki/Voodoo_Zombies_(Horde)
8. https://cata-twinhead.twinstar.cz/?quest=29238
    https://wowpedia.fandom.com/wiki/Bad_Supplies_(Horde)
9. https://cata-twinhead.twinstar.cz/?quest=29250
    https://wowpedia.fandom.com/wiki/Making_Contact_(Stranglethorn,_Horde)

**Comment by itsemmastone** [comment]
All of these issues have been fixed. I kindly ask you to delete the cache folder while your game is not running and then try to do this quest chain again.

**Comment by emirie1** [comment]
Please reopen this report. I closed my client and deleted the Cache folder as instructed and attempted to do the objectives again and none of them work. Additionally, there are other open bug reports about some of these same issues that have been marked as "Priority: Critical".

https://github.com/gamefreedomgit/Maelstrom/issues/3594 - Serpents and Poison
https://github.com/gamefreedomgit/Maelstrom/issues/3595 - Spirits Are With Us
https://github.com/gamefreedomgit/Maelstrom/issues/3596 - Bad Supplies
https://github.com/gamefreedomgit/Maelstrom/issues/3597 - Making Contact

**Comment by MarioVrenzola** [comment]
I don't know how but i was able to find the NPC in the correct location to complete "Making Contact" and went on to complete "Booty Bay's Interests" but didn't get the last quest "A Shiny Reward" after delivering the quest item from the last ZG boss to the goblin in booty bay (tried delivering inside ZG but couldn't speak to the NPC so i went back to booty bay and completed it there)
