### ISSUE TITLE
Serpents and Poison

### ISSUE THREAD

**Issue by acko2469** [gamefreedomgit/Maelstrom#3599]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest not working - Serpents and Poison

**How to reproduce:**
When you kill mobs and heal adventurers the quest should be completed

**How it should work:**
Killing mobs and healing adventureres does not count and you cant finish quest

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29103

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3594 duplicate
