### ISSUE TITLE
Missing item from SW Innkeeper, perhaps also other major city innkeepers.

### ISSUE THREAD

**Issue by Kaspahh** [gamefreedomgit/Maelstrom#3600]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Level 80 water is missing from the stormwind innkeeper, but she does sell lvl 80 food. I checked https://cata-twinhead.twinstar.cz. It is called "Sparkling Oasis Water"

**How to reproduce:**
Click the vendor hehe

**How it should work:**
The item should be there

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=6740#sells:0-2+1

**Comment by Afgann** [comment]
fixed
