### ISSUE TITLE
combustion

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3602]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
combustion ignore abilities that reduce damage taken

**How to reproduce:**
Use any abilities that reduce dmg after combustion

**How it should work:**
abilities that reduce dmg should work on combustion

**Database links:**
https://wowpedia.fandom.com/wiki/Combustion

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/ddac46b8-94ac-4bf6-a70f-79becaef67ff)

**Comment by Sketish** [comment]
Please provide proof on server that damage reduction is not working for combustion

**Comment by mipanka** [comment]
added screenshot with combatlog

**Comment by bonfax4** [comment]
This is working as intended btw. Combustion should NOT double dip with dmg increase/decrease effects, was hotfixed at some point. Combustion spread via Impact should take into account modifiers tho ( prevent abuse of spreading combustion into mobs with dmg reduc ). [This means combustion can only double dip resilience if spread through impact](https://www.mmo-champion.com/threads/946636-Combustion-Hotfix-Bugged?highlight=combustion+hotfix).

https://www.engadget.com/2011-08-10-patch-4-2-0-hotfixes-for-aug-10-2011.html
> Combustion damage from Ignite is no longer penalized by Resilience more than once, nor can it gain double benefit from Flashburn (mastery).

https://cata-twinhead.twinstar.cz/?spell=11129#reported-fixes
https://cata-twinhead.twinstar.cz/?fixreport=show&id=6292
> Fixed double dipping from reductions, also again will not double dip from auras increasing damage

https://www.mmo-champion.com/threads/945624-Patch-4-2-Hotfixes-July-26
"Combustion should no longer ignore damage modifiers on a target. As an example, Smoldering Elemental packs in the Firelands should no longer take full damage from Impact’s spread of Combustion, despite these creatures having damage reduction modifiers."

**Comment by mipanka** [comment]
its for spread from impact. If main target have 10k combustion and mage spread combustion on off target (where off target have -50% reduce dmg taken) combustion will be 10k as on main target

**Comment by bonfax4** [comment]
Possible that you're right. Considering initial ignite had no reduction to begin with. I wonder if combustion checks for that somehow to know if it can be reduced by effects done after. I'll try to look for a video of this exact scenario.

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/978112-Alysrazor-Guide-on-350k-Ignite-Comb-by-Logoz/page2?highlight=Logoz 

Look at alysrasor log. Burnout is 50% increase dmg debuff on the boss that drops while combustion is on the target, but combustion dmg remains exactly the same. I don't see why reduction would function any different but its possible. 

> [21:47:28.543] Logoz Combustion Alysrazor *381068*
> [21:47:28.643] Logoz Ignite Alysrazor 209723
> [21:47:28.643] Logoz Combustion Alysrazor *381069*
> [21:47:28.854] Logoz Combustion Alysrazor *381069*
> [21:47:29.002] Alysrazor's Burnout fades from Alysrazor
> [21:47:29.002] Logoz Combustion Alysrazor *381069*
> [21:47:29.287] Logoz Combustion Alysrazor *381068*
> [21:47:29.287] Logoz Pyroblast Alysrazor *81013*
> [21:47:29.377] Logoz Combustion Alysrazor *381068*
>

**Comment by UltraNix** [comment]
Fixed.
