### ISSUE TITLE
Missing final quest "A Shiny Reward" of the 4.1 quests in stranglethorn

### ISSUE THREAD

**Issue by MarioVrenzola** [gamefreedomgit/Maelstrom#3603]
#Description#
After completing "Booty Bay's Interests" ( i didn't get the quest "A Shiny Reward"  from the same quest NPC

#How to reproduce#
Do quests up to it and the npc won't give you anymore quests

#How it should work#
The npc should give you the final quest of the quest chain

#Database links#
https://www.wowhead.com/quest=29251/booty-bays-interests (last quest i did)
https://www.wowhead.com/quest=29155/a-shiny-reward  (the quest that is missing)

**Comment by UltraNix** [comment]
Fixed.
