### ISSUE TITLE
Spirit's vengeance in Bloodlord Mandokir - Zul Gurub

### ISSUE THREAD

**Issue by Futsume** [gamefreedomgit/Maelstrom#3605]
In the second encounter of Zul Gurub. When the spirits ressurect a player, they give them a buff: "Spirit's Vengeance" this buff is dissapearing after few seconds (4-5 secs aprox) and dissapear when you die too. It should stay permanently (5 mins according to wowhead) and stay through dead. Being able to accumulate till 10 charges according to the ingame guide.

https://www.wowhead.com/spell=96493/spirits-vengeance

**Comment by UltraNix** [comment]
Fixed.
