### ISSUE TITLE
mob disappeared with loot

### ISSUE THREAD

**Issue by Aquariosz** [gamefreedomgit/Maelstrom#3606]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During BOT 10 man we are cleaning trash mob and somemob drop Chelley`s Staff of Dark Mending, i was sending to person and mob desappeared with loot 

**How to reproduce:**

**How it should work:**

**Database links:**
![WoWScrnShot_052423_225211](https://github.com/gamefreedomgit/Maelstrom/assets/134575224/46540994-8b64-4655-9af6-ed1e3fce9ea6)

**Comment by xmrshoot** [comment]
ye mobs before valiona despawn too fast after kill and we cant get loot

**Comment by xmrshoot** [comment]
#3777  fixed on this @Sketish u can close
