### ISSUE TITLE
Minister of Air (Vortex Pinnacle) and Amani'shi Axe Thrower (Zul'Aman) channeling spells

### ISSUE THREAD

**Issue by Mercusz** [gamefreedomgit/Maelstrom#3607]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Minister of Air's Lightning Lash is currently doing 5 times more hits than intended. It should be a single bolt like every .1s, instead of hitting all players.

The same effect, to a much worse degree due to it not being interruptable, is also happening is Zul'Aman with the Amani'shi Axe Throwers.

**How to reproduce:**

Just engage with mobs with a party of 2 or higher.

**How it should work:**

For Minister of Air: https://youtu.be/02L1UQzZjj4?t=1207 you can also see here https://youtu.be/02L1UQzZjj4?t=1296 slightly clearer.
Wowhead unfortunately don't have much info. But in addition, there's a knockback spell that isn't being cast called Call Lightning.

For Amani'shi Axe Thrower: https://youtu.be/o5B5BwzO4Wo?t=280 kinda hard to see but you can check on raid frames that there's no dropping on the party hp at once, implying that the axe isn't thrown on all party members like whats going on here.

**Database links:**
https://www.wowhead.com/npc=45930/minister-of-air#abilities;mode:normal
DB for Amani'shi is kinda bad, but: https://www.wowhead.com/npc=23542/amanishi-axe-thrower#comments

**Comment by Afgann** [comment]
fixed
