### ISSUE TITLE
Justice Trade Goods vendor

### ISSUE THREAD

**Issue by d-gaberov** [gamefreedomgit/Maelstrom#3609]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Horde -> Orgrimmar -> Justice Trade Goods you can exchange Justice Points for Honor Points.
Alliance -> Stormwind -> Justice Trade Goods you can exchange Honor Points for Justice Points
Its inverted and hinders alliance players to spend justice points for pvp gear.

**How to reproduce:**
Just check the vendors

**How it should work:**
THey should be the same

**Database links:**

**Comment by d-gaberov** [comment]
![Screenshot 2023-05-25 092854](https://github.com/gamefreedomgit/Maelstrom/assets/56873738/624d6f65-7c26-495f-a87d-29e1c5bd9d48)
![Screenshot 2023-05-25 092756](https://github.com/gamefreedomgit/Maelstrom/assets/56873738/629eb9f0-3864-4999-aee2-6bf507390d0c)

**Comment by d-gaberov** [comment]
So 2-3 days after u get 85, Justice Points for alliance is useless, u get to 4k and have nothing to do with them. Horde in the other hand can still make heroic dungeons and get pvp gear with them. How is this unbalancing thing low priority :D

**Comment by Afgann** [comment]
fixed
