### ISSUE TITLE
Redirect does not transfer combo points

### ISSUE THREAD

**Issue by Carapilsx** [gamefreedomgit/Maelstrom#3614]
**Description:**
Redirect does not transfer combo points.

**How to reproduce:**
Build combo points on Target 1 => Use Redirect on Target 2 

**How it should work:**
Like the tooltip says. It should transfer combo points. 

Video : https://clips.twitch.tv/CrypticTangibleBulgogiPupper-lzlrot6ZQTZQ1dXk

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=73981

**Comment by Sketish** [comment]
Are you using any specific macro ?

**Comment by Unnaturalftw** [comment]
Have the same issue it used to work before, but now it doesnt

**Comment by UltraNix** [comment]
Fixed.
