### ISSUE TITLE
Zul'Gurub crash

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3622]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, this is incredibly weird place I find myself in, I was browsing both discord and here on github to see if other people experience but, so far I didn't find anything, so Zul'Gurub, take a look at the marked area, I just hope I selected the right one!
![Inkedmap_zulgurub](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/cd6d9346-4897-4e1f-8fdf-9382188387c4)
Here so far I have experienced 16 crashes to desktop and from what I can tell, several times players of the groups I was part from experienced it also, below you should see 3 images of the errors I get
![Desktop Screenshot 2023 05 25 - 22 14 11 50](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/f5f31406-0268-4706-8c1d-e4b6a39787b2)
![Desktop Screenshot 2023 05 25 - 22 28 07 67](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/3a2b2ab9-dd2b-4e4e-892e-08b7a606df64)
![Desktop Screenshot 2023 05 24 - 23 14 57 11](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/826455cc-fd61-4d36-ab35-71bbd9914ff2)

Below you should be seeing the crash.dmp and crash.txt, you have to forgive me I haven't done this so, hope for the best and if you should require anything else from me, I will do my best to assist.
[2023-05-25 22
[2023-05-25 22.14.05 Crash.txt](https://github.com/gamefreedomgit/Maelstrom/files/11569253/2023-05-25.22.14.05.Crash.txt)
.14.05 Crash.zip](https://github.com/gamefreedomgit/Maelstrom/files/11569226/2023-05-25.22.14.05.Crash.zip)

**How to reproduce:**
I will leave these pages blank, Well you can group up with me and go on a journey there hehe.

**How it should work:**
**Database links:**

EDIT:

I forgot to mention, I moved the WTF and the CACHE files and disabled all addons on my solo attempt today

**Comment by Futsume** [comment]
post only to confirm i'm having this issue too. First dung attemp when it releases, Me and other 2 members of the party got the game crashed just at that point. And yesterday i got myslef crashed 2 times again at that same point.
