### ISSUE TITLE
Magmaw Shadow Breath

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3623]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Last phase when on heroic when nefarian casts shadowbreath it sometimes(usually at the start) targets pets. In-game tooltip says it should only be on players. It will splash on melees who are near the pets.

**How to reproduce:**
Get to last phase on HC.

**How it should work:**
Target only players.

**Database links:**

**Comment by Bugtrack123** [comment]
http://prntscr.com/rwSMOtTS7xy0

**Comment by Afgann** [comment]
fixed
