### ISSUE TITLE
[Hunter] [Beast Mastery] [Spirit Mend]

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3624]
https://github.com/gamefreedomgit/Maelstrom/issues/1565

**Description:**
Hello, while fixes for the spell were implemented earlier there are still several issues with it(In my opinion)
1. It doesn't benefit from the hunter rap
2. hot debuff doesn't scale properly with the hunter rap(I am making an assumption here due limited information)
3. ~~hot debuff doesn't crit when you dismiss the pet~~
4. hot debuff shows as a hostile spell/event in the combat log( just an observation, it has no negative effect)
**How to reproduce:**

**How it should work:**
1. It should scale with the hunter rap both the initial heal and the hot
2. (3) Uhm I might be overreaching  here but I was under the impression the heal should be able to critically heal and now I am not sure, I just hope by putting this here someone else can confirm/clarify it
The two formulas I found, one I am sure its from the next expansion MoP but if like above anyone can clarify if the formula below is the intended one

[pet base heal + ((Ranged attack power * 0.6) * 1)] plus an additional [0 + ((Ranged attack power * 0.6) * .66) * (5)] over 10 sec.

Please consider the BM talent Spirit Bond ID: 20895

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=90361
https://www.wowhead.com/spell=90361/spirit-mend

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/4149a260-476b-4ebd-b3da-8aa15e7e82ab)

**Comment by NinacS90** [comment]
> ![image](https://user-images.githubusercontent.com/122209088/241159069-4149a260-476b-4ebd-b3da-8aa15e7e82ab.png)

I read that, but it says its edited last time in patch 5.2.0 MoP, or he edited something else at a later date, further down below there is afellow that says the following:
![Spirit Mend Comment wowhead](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/1de7e827-2be1-4081-b86b-6aa338e566df)
So he confirms that the initial spell can crit, however he mentions his "5.9K" hunter was overall healed for 10K which was wotlk thing(gear etc) so, a prepatch before the official release of the Cataclysm?  Last edited 6.10.2010, or 10.6.2010 (what on earth are these date formats) and the official release was 7.12.2010

**Comment by UltraNix** [comment]
```Description: The Spirit Beast heals the current friendly target for ${$m1+(($RAP*0.35)*0.5)} plus an additional ${$m2+(($RAP*0.35)*0.335)} over $d.```
Initial heal takes 17.5% from RAP and hot takes 11,725%.

**Comment by NinacS90** [comment]
My apologies for the mistakes, it was not my intention. Thank you for the quick fix I am looking forward to the next server restart
