### ISSUE TITLE
dominion interface bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3626]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**  sometimes after dominion your action bar dont show

**How to reproduce:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/d1ade9dd-d4cd-43cb-b678-f894ed8a022b)

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
and sometimes dominion ends instantly without pressing 1 to end mind control and then interface dissapear

**Comment by UltraNix** [comment]
Fixed.
