### ISSUE TITLE
Enchanted items refund bug

### ISSUE THREAD

**Issue by initialactivity** [gamefreedomgit/Maelstrom#3627]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I should not be able to refund bought items if I enchanted or gemmed them

**How to reproduce:**
-Buy an item with honor or emblems
-Enchant or gem it
-Talk to a vendor and right click to sell
-Confirm dialogue

**How it should work:**
I should not be able to refund an item. If I can get gold for the item, I should get the gold.

**Database links:**
![WoWScrnShot_052623_214309](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/3b869bdf-f934-4ce1-8b40-5b32699c729e)
![WoWScrnShot_052623_214334](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/cb7a94f2-42b4-41f8-8ac2-7dffb7c63504)
![WoWScrnShot_052623_214350](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/a61d7d01-e367-4d7d-b59d-a4eef0777509)
![WoWScrnShot_052623_214357](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/65efa97e-35a5-4d64-880f-6ab0d902b7d8)

**Comment by initialactivity** [comment]
I was able to refund an item which I put belt buckle on too.

**Comment by UltraNix** [comment]
Fixed.
