### ISSUE TITLE
now nefarin goes undermap 

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3628]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**now its going under map instead of flying , fix didnt work

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/3d17fd77-c386-4f0a-9377-fc4c0bfb9838)

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
![WoWScrnShot_052623_233111](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/9d9edb99-4c4d-4eaa-ae6a-9f6b6b6d5930)
 AND happens on nm difficulty , on heroic was good , but u can test both difficulties

**Comment by Exorcista** [comment]
![WoWScrnShot_052223_144122](https://github.com/gamefreedomgit/Maelstrom/assets/6818405/0aace7c3-9d5a-4915-8dff-5716d6c1e399)

top lel, happened on 10man N yesterday

**Comment by UltraNix** [comment]
> ![WoWScrnShot_052223_144122](https://user-images.githubusercontent.com/6818405/241350469-0aace7c3-9d5a-4915-8dff-5716d6c1e399.jpg)
> 
> top lel, happened on 10man N yesterday

I see 22 of May in calendar, so before the fix...
