### ISSUE TITLE
Vampiric Embrace bug

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#3631]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The shadow priest vampiric embrace talent heals the priest for 6% of all single target damage done and other party members by 3%.
Currently the 3% of heal per party members does not work, it splits 3% of all single target damage done among the 4 other party members so everyone gets only 0.75% of ST damage done as heals.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3fe4935f-2ab4-4c90-b5dc-fd2f4e2ecf84)

On this screen the hunter's pet also gets heal (not sure if this is supposed to happen or not) so the 3% is divided by 5

**How to reproduce:**
Check healing done by VE after a boss or a dungeon

**How it should work:**
Party members should be heal for 3% of the priest ST damage and not be 3% divided among party members

**Database links:**
http://cata-shoot.tauri.hu/?spell=15286

**Comment by UltraNix** [comment]
Fixed.
