### ISSUE TITLE
Bugged quest - Valkyrion Must Burn - The Storm Peaks

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3632]
**Description:**
To complete Valkyrion Must Burn you must enter a Harpoon Gun and shoot dry stacks of hay.
There only spawns 1 and the respawn rate is way to long.

**How to reproduce:**
Pick up quest -> Enter the Harpoon Gun ->Shoot the haystacks.

**How it should work:**
Should spawn more.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12953

**Comment by PanJanuszek** [comment]
fixed 27.03.2024
