### ISSUE TITLE
Skull bash 2 forms (interrupts) Combat log

### ISSUE THREAD

**Issue by EmileQL2P** [gamefreedomgit/Maelstrom#3635]
https://cata-twinhead.twinstar.cz/?spell=80964

Description:
If u use skull bash whatever which form combat log didnt show it. It shows only 4 sec silence.
Beacuse of that addons didnt show interrtups from druid, peoples says let's kick this f***ng n**b from rhc/raid cuz the didnt know how to interrupts and u get kicked and got id for no reason >.<

How it should work:
Just interrupt should be visible in combat log with successful interrupt on target

Video below:
https://www.youtube.com/watch?v=_-D78W0qMLs

**Comment by UltraNix** [comment]
Fixed.

**Comment by EmileQL2P** [comment]
Still didnt work after restart

**Comment by EmileQL2P** [comment]
Still didnt work @UltraNix

**Comment by UltraNix** [comment]
Fixed.
