### ISSUE TITLE
Zul'Gurub Razzashi Adder loot table

### ISSUE THREAD

**Issue by Bugtrack123** [gamefreedomgit/Maelstrom#3636]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mob is not skinnable, so you cannot access its skinning loot table

**How to reproduce:**
Kill the mob, try to skin it

**How it should work:**
Mob should be skinnable
**Database links:**
https://www.wowhead.com/npc=52085/razzashi-adder#skinning;mode:heroic

**Comment by Afgann** [comment]
fixed
