### ISSUE TITLE
Dungeon finder issues

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#3637]
There's a ton of issues with the dungeon finder currently, listing just a couple most annoying ones:

1. If a party member logs off in a dungeon group the member count of which is 3 or less, he cannot be voted out of the party, therefore making it impossible for the remaining players to finish the dungeon.
2. Entering a dungeon in progress with a boss killed often saves you to the dungeon immediately, without offering the usual "X bosses have been killed, would you like to get saved" prompt. I've had parties abandon the dungeons right after and then either someone logs off making it impossible to re-queue again (see first issue), or the dungeon finder bugs out leading to the same result and leaving the player that just entered saved to the instance, unable to re-queue, all without ever participating in the dungeon in the first place. Also, as far as I remember, the prompt given to a player entering a dungeon in progress was intended just to help the player understand what they were getting themselves into, with them not actually getting saved until they participated in a boss kill. In addition, declining to join the instance currently also saves you to the instance.
3. After one or more players have left a dungeon in progress and the rest have re-queued, a group will form, but the players saved to the dungeon will get a prompt saying someone in the party did not accept the invite and be put out of the queue again, without ever receiving a prompt to accept the invite (which, for the people already in the dungeon group shouldn't be required in the first place).
4. After a party has gone through a number of members (that either left or wanted to be kicked because they perceived the harder dungeon not worth their time), the group will become unable to re-enter the queue, having replaced "too many" members. I assume this was a measure added to prevent people from abusing the dungeon finder, but realistically it's more detrimental to the group who decides to persevere, who are then prevented from finishing the dungeon.
5. After completing a heroic dungeon, it is possible to put the group back in dungeon finder queue, resulting in the formation of a new group to an empty instance.
6. A party disbanding while a player is dead leaves him unable to zone out to his original entry point after reentering the dungeon to retrieve his body.

**Comment by EmileQL2P** [comment]
+1

**Comment by NinacS90** [comment]
Also I'd like to add to the list that people especially in the new dungeons would tend to sabotage or grief the rest of the group by going afk near the portal and even when kicked they cannot be replaced because the new member will get a error message "Instance is full" (I believe?) prompting you to open a ticket and try to settle this the only other way that is available, since reason is off the table, I think its the same for people who "accidentally" have "disconnected"

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/771#issuecomment-1542242844

**Comment by UltraNix** [comment]
```
Got the same issue right now. The entire team got the message with no valid tp location and there was no green eye on the minimap to tp into the dungeon. Tried a relog, didn't help. How I got there:

lvl 84 character, did Throne of the Tides
our group decided to requeue after we completed it
the system picked ToT again
as soon as we clicked Enter Dungeon we got the "no valid tp location" message
we tried to tp out and in
the instance was empty (completed)
we kicked each others to prevent deserter
I requeued
I'm not 100% sure but the system probably picked ToT again and that's where it all went wrong.
```

**Comment by UltraNix** [comment]
@VirtualReign 
```
After a party has gone through a number of members (that either left or wanted to be kicked because they perceived the harder dungeon not worth their time), the group will become unable to re-enter the queue, having replaced "too many" members. I assume this was a measure added to prevent people from abusing the dungeon finder, but realistically it's more detrimental to the group who decides to persevere, who are then prevented from finishing the dungeon.
```
Please - be more precise. What do you mean? Whar error appears?
There is no such code that prevent from queuing after kicked/removed some number of members.

**Comment by UltraNix** [comment]
Fixed.
