### ISSUE TITLE
Bugged Quest - The Heart of the Storm - The Storm Peaks

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3639]
**Description:**
Not possible to complete "The Heart of the Storm". When trying to take the heart an NPC stops you but you get no credit.

**How to reproduce:**
Pick up quest The Heart of the Storm -> Try to take the heart

**How it should work:**
Should get credit for trying to get the heart.

**Database links:**
https://cata-twinhead.twinstar.cz/?object=192181

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
