### ISSUE TITLE
[Transportation][Intance] Deeprun Tram missing

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3642]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Deeprun Tram is not working, it's simply not moving/not there.

**How to reproduce:**
Enter the Deeprun Tram instance and wait forever for the Tram to arrive.

**How it should work:**
The Tram should be there.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Deeprun_Tram

**Comment by UltraNix** [comment]
Fixed.
