### ISSUE TITLE
[Druid][Trainer] Dareth Trainer menu not working

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3643]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Druid Trainer NPC Dareth in front of Ironforge is missing Trainer menu. Right now it doesn't have any gossip options at all.

**How to reproduce:**
Travel in front of Ironforge as a Druid and talk to Dareth.

**How it should work:**
Dareth should be teaching druid spells, dual spec and offer to reset talents.

**Database links:**
http://cata-shoot.tauri.hu/?npc=52335

**Comment by UltraNix** [comment]
Fixed.
