### ISSUE TITLE
[Druid] Tree of Life and lifebloom issue

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3645]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can't always replicate this behaviour but sometimes refreshing lifeblooms via empowered regrowth (instant regrowth) during Tree of Life fails to work. Issue might be related with this [fix](https://github.com/gamefreedomgit/Maelstrom/issues/3117).

**How to reproduce:**
Not sure but I notice it often during dungeon runs when I try to refresh lifeblooms via tree of life instant regrowths.

**How it should work:**
 Lifeblooms cast when Tree form is up should only fail to be refreshed via talent outside of tree form. Life blooms end up falling off messing up the whole tree of life playstyle of spamming blooms and using clearcast regrowths to refresh them.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
