### ISSUE TITLE
Devouring Plague ticks inflict 1 point on damage to target dummies

### ISSUE THREAD

**Issue by rsantomo** [gamefreedomgit/Maelstrom#3648]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Priests' Devouring Plague spell doesn't work as expected when cast on target dummies.
It's initial direct damage caused by the Improved Devouring Plate talent works as expected, but the DoT itself doesn't: it always inflicts 1 point of damage per tick. No matter player's stats.

**How to reproduce:**
1. Be a priest.
2. Go to a target dummy in Orgrimmar.
3. Cast Devouring Plague on it.
4. Check its periodic damage.

**How it should work:**
Devouring Plague periodic damage should work just like the other DoTs (e.g. Shadow Word: Pain, Vampiric Touch, etc.).

**Database links:**

<img width="1604" alt="Screenshot 2023-05-29 alle 02 21 22" src="https://github.com/gamefreedomgit/Maelstrom/assets/11272777/80ee9e60-24c2-4487-9343-65f6159f25bb">

**Comment by UltraNix** [comment]
Fixed.
