### ISSUE TITLE
combat bug after council in BOT

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** after council is dead we always have combat bug and we must alt f4 to regen mana before cho gall

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
and cant switch to hc/nm cuz combat , need alt f4 too

**Comment by UltraNix** [comment]
@xmrshoot Still happens?

**Comment by xmrshoot** [comment]
@UltraNix hmm no
