### ISSUE TITLE
Druid initial task cannot be completed

### ISSUE THREAD

**Issue by caesarlewis** [gamefreedomgit/Maelstrom#3652]
**Description:**
Practice Moon Fire is not complete .
Unable to complete tasks using lunar fire on training dummies

**How to reproduce:**
Use a Druid , Received the Moon Fire mission

**How it should work:**
Using lunar fire on training dummies should complete quest.

**Database links:**

![1](https://github.com/gamefreedomgit/Maelstrom/assets/29245125/fd642ec3-8798-4fed-9996-aeb30ab5adb8)

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/63216736-dfd7-48b8-aafe-9184adbfbde5)
There is no such quest. Try to remove and clear your cache folder and try again.

**Comment by caesarlewis** [comment]
Hi UltraNix,
Thank you.
This is a translation error on the client side.
Simplified Chinese version display error.

**Comment by caesarlewis** [comment]
Hi UltraNix,
Thank you.
This is a translation error on the client side.
Simplified Chinese version display error.

**Comment by caesarlewis** [comment]
Hi UltraNix,
Thank you.
This is a translation error on the client side.
Simplified Chinese version display error.
