### ISSUE TITLE
General bug of pet scaling damage and health.

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#3653]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This bug causes player pets below level 85, both hunters and warlocks, frost mages, etc. to have high health and increased damage that is out of the norm, destroying the experience of many players in the battlegrounds who usually enter to level up.

Making the experience of playing one of these classes extremely easy as I get to carry a pet that has the health of a player 10 or more levels higher.

**How to reproduce:**
This bug is general and can be reproduced either by creating a class with a pet or looking at the health and damage of any pet of a classed player who owns pets below level 85

1. 
![WoWScrnShot_052923_115857](https://github.com/gamefreedomgit/Maelstrom/assets/134957578/48eb5b06-e322-4103-8ba2-3c994085c00b)
2.
![WoWScrnShot_052623_144905](https://github.com/gamefreedomgit/Maelstrom/assets/134957578/04821d46-2bdc-4cc2-99fe-0a687d1acf11)
3.
![WoWScrnShot_052423_162012](https://github.com/gamefreedomgit/Maelstrom/assets/134957578/c84b5011-1631-4611-aa6e-7784a40bc436)
4.
![WoWScrnShot_052423_161931](https://github.com/gamefreedomgit/Maelstrom/assets/134957578/96cd3795-3751-4f22-959e-9153d2430ae9)

**How it should work:**
Its not easy to find information today of scaling of the pet in low levels in the net, but there are videos of World of Warcraft Cataclysm in the official server that show and prove how it should work.[ This one](https://www.youtube.com/watch?v=rOZ0JbU-HDg) is a clear example.  The [following video](https://www.youtube.com/watch?v=o0t7em_ELYU) shows a level 20 warrior sometimes fighting against pets on the battleground. In the [following video](https://www.youtube.com/embed/94zJNb0kNoM) you can see a level 20 hunter in battlefields, it is a good video to appreciate the damage your pet does.

**Database links:**
There doesn't seem to be any information about low-level pet scaling on the net anymore, but there are videos and tests that show that in Whitemine they are not working as they should.

**Comment by Sketish** [comment]
Connected with https://github.com/gamefreedomgit/Maelstrom/issues/3592

**Comment by nkostarter** [comment]
Is it possible to know if there is any news about it?

**Comment by UltraNix** [comment]
Fixed.
