### ISSUE TITLE
Archaeology digsites are not showing on map anymore

### ISSUE THREAD

**Issue by Sleepy8919** [gamefreedomgit/Maelstrom#3654]
**Description:**
I don't see digsites markers (shovel) on map anymore with Track Digsites option checked. Also tried to /reload UI and disable all addons.

**How to reproduce:**
# Login as Versus
# Toggle track digsites 
# Open map
# View dig sites markers

**How it should work:**
Dig sites markers should appear on map

![image](https://github.com/gamefreedomgit/Maelstrom/assets/134961391/5ee87757-0b57-4ee0-b750-62c1f867e118)

**Comment by UltraNix** [comment]
#3593
