### ISSUE TITLE
The equipment disappeared.

### ISSUE THREAD

**Issue by Zegoooo** [gamefreedomgit/Maelstrom#3656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After I came out from the battlefield, my equipment disappeared. My English is not good. I'm not sure if I can contact GM in this way.
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please use https://forms.gle/gHv7dApL1PSng6YG6
