### ISSUE TITLE
Amnennar the Coldbringer has no loot

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3657]
**Description:**
Amnennar the Coldbringer has no loot...

**How to reproduce:**
Doesn't happens always. This is the first time I see this happen.

**How it should work:**
A last boss of an instance never has only gold in his corpse.

**Database links:**
https://www.wowhead.com/classic/npc=7358/amnennar-the-coldbringer

**Photography:**
![WoWScrnShot_052923_223349](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/1ec31f85-dfa6-43f8-9cdf-159d04890e6e)
![WoWScrnShot_052923_223405](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/b1e8d4eb-a5b3-4f1b-873d-1ae2142dcb4d)
![WoWScrnShot_052923_223408](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/932cadff-2284-498d-a2c1-3b9e558c8b8e)

**Comment by Afgann** [comment]
fixed
