### ISSUE TITLE
Quest stops progressing

### ISSUE THREAD

**Issue by EskwyreX** [gamefreedomgit/Maelstrom#3658]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
THe quest Elemental Energy in Deepholm stops progressing.

**How to reproduce:**
Just attempting to do the quest

**How it should work:**
Killing elementals near the totem should give +1.

**Database links:**

**Comment by Sketish** [comment]
Please provide snap

**Comment by EskwyreX** [comment]
What do you mean by Snap? 

Also, I figured out what the actual problem was. Using my summoned demons caused it to be inconsistent with giving quest credit, but when I dismissed and killed the creatures without a demon, the quest progressed just fine.

**Comment by UltraNix** [comment]
If your pet does the kill without your help (any damage) you won't get credit/exp.
