### ISSUE TITLE
Restless Blades Combat Rogue Bug

### ISSUE THREAD

**Issue by BorisVolk** [gamefreedomgit/Maelstrom#3659]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Restless Blades Combat Rogue talent triggers even if eviscerate misses.

**How to reproduce:** Gain combo points + use evi + it misses = profit

**How it should work:** Gain combo + use evi + it misses = no profit

**Database links:**

**Comment by Sketish** [comment]
It should only reduce cd when finisher deals dmg

**Comment by UltraNix** [comment]
Fixed.
