### ISSUE TITLE
Container item bug -lootall

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3661]
**Description:**
When you open an item that is a box (for example: a [Big-mouth Clam](https://www.wowhead.com/classic/item=7973/big-mouth-clam)) but the chest has more than 1 item and you DON'T have FREE SPACE ON BAGS and you have an stackable item on your inventory that loots from the item-chest (like [Zesty Clam Meat](https://www.wowhead.com/classic/item=7974/zesty-clam-meat)), when you open the "chest" on your inventory, if the system loot 1 of the items automatically (the zesty clam meat), and even there is another item (any pearl, for example), the lootbox get closed, the pearl was not looted, the clam dissapear (or discounted from the stack) and you never get the item.

**How to reproduce:**
- fill your bags until no freespace
- get a item that is a chest, like a clam
- must have an stackable item, like clam meat
- open the item
- must loot more than 1 item, the second item looted must be or nonstackable or you mustn't have a copy
- close the lootbox (or use autoloot)

**How it should work:**
There is 2 ways to workarround this:
- Blizzlike: the chest item doesn't dissapear and if you open it again (even in an stack) you reopen the "non-empty" chest instead of "new roll for items" (to avoid an "infinite money bag" bug). If you logout, the "garbage collector system" loot the item for you, discount the item form the stack and send it to your bags (if enough space) and if not, send it to your email.
- Private server: use garbage collector system in any case "fullbags+closing lootbox item).

**Database links:**
https://www.wowhead.com/classic/item=7973/big-mouth-clam
https://www.wowhead.com/classic/item=7974/zesty-clam-meat

**Comment by UltraNix** [comment]
Fixed.
