### ISSUE TITLE
Untargetable mobs in Uldum

### ISSUE THREAD

**Issue by EskwyreX** [gamefreedomgit/Maelstrom#3662]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # https://www.wowhead.com/quest=27903/ignition
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Ignition, you have to activate a statue and kill it. In the area there are miniature untargetable, undamageable infernals that aggro onto you.

**How to reproduce:**
Do the quest

**How it should work:**
There shouldn't be any miniature infernals there.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/134971874/491eaf99-ec9e-40b7-b1db-4199a14822a6)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134971874/791a0a7c-3ddc-4153-9168-49a357fd1203)

**Comment by Afgann** [comment]
fixed
