### ISSUE TITLE
Pet falling through the floor

### ISSUE THREAD

**Issue by EskwyreX** [gamefreedomgit/Maelstrom#3667]
**Description:**
Pet falls through floor at Siamat in Lost City of Tol'Vir. Cuts Demonology dps by 66% on Siamat.

**How to reproduce:**
Summon a pet on Siamat's platform

**How it should work:**
Pet should not fall through the floor.

Clip of it happening.
https://streamable.com/vj5c18

**Database links:**

**Comment by UltraNix** [comment]
#2551
