### ISSUE TITLE
Deadmines

### ISSUE THREAD

**Issue by RaresHdr** [gamefreedomgit/Maelstrom#3668]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The hitboxes are larger than they should be ex: fire storm on the first boss, the electric storm at the last boss in first phase, plus the first boss spawn too many thrash.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please provide any proofs and database links since currently its invalid report

**Comment by UltraNix** [comment]
No further info - closing.
