### ISSUE TITLE
Once More Into The Fire

### ISSUE THREAD

**Issue by RaresHdr** [gamefreedomgit/Maelstrom#3669]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest in Twilight Highlands, the npc is just standing there

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2775 duplicate
