### ISSUE TITLE
[Quest] Horde Trauma (First Aid quest)

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3670]
**Description:**
The NPC [Doctor Gregory Victor](https://www.wowhead.com/npc=12920/doctor-gregory-victor) in Hammerfall in Arathi Highlands @68.5.37.8 is not clickable. 

**How to reproduce:**
Get the quest.

**How it should work:**
You usually can click on the npc to finish a quest...

**Database links:**
https://www.wowhead.com/quest=6623/horde-trauma

Additional info: Victor doesn't have NPC name or nameplate. The soldiers near him are loosing and recovering life at a REALLY FAST SPEED mabe you want to correct this to down a bit the overheading of those NPCs to the server side...

![WoWScrnShot_053123_012410](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/4530b280-4bee-4979-a2f1-67ae2ece18ad)

**Comment by UltraNix** [comment]
Fixed.
