### ISSUE TITLE
Summon Gargoyle position

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
talent death knight Summon Gargoyle. If do pet command "/petattack", gargoyle will be in up

**How to reproduce:**
need use talent Summon Gargoyle and use macro /petattack (Master of Ghouls should be active)
/cast Summon Gargoyle
/petattack

**How it should work:**
The gargoyle summon should be inactive for the first second, and when it descends, start attacking, just like it works if you do not use a macro

**Database links:**
https://wowpedia.fandom.com/wiki/Summon_Gargoyle
https://wowpedia.fandom.com/wiki/Master_of_Ghouls
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/45dd1a67-757a-4467-9974-c949420c171a) screen from game with bug

**Comment by UltraNix** [comment]
Fixed.
