### ISSUE TITLE
Donation Issues.

### ISSUE THREAD

**Issue by Vinlan123** [gamefreedomgit/Maelstrom#3672]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Donated using https://playerid.me twice and have not received Ember Coins.

**How to reproduce:**
![IMG_1601](https://github.com/gamefreedomgit/Maelstrom/assets/135076947/bf52fe80-a42f-4666-9c3f-4f141c7b2366)
![IMG_1602](https://github.com/gamefreedomgit/Maelstrom/assets/135076947/9b445fb1-d104-4fad-a8a1-bfd6391eeb15)

**How it should work:**
Should have received Ember Coins equivalent to amount donated. 

**Database links:**
https://playerid.me/dashboard

**Comment by Sketish** [comment]
Please DM this to  Gaga on discord
