### ISSUE TITLE
[Warlock] Pets issues.

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

- Warlock Pets are currently not scaling with owner's haste rating. My imp has the 1.75 cast time talented, Voidwalker has the default 2 sec attack speed, etc. Not to be confused with total haste %, pets should not scale with % modifiers buffs from the owner, unless you're a dk.

- Pet still showing dodges when I'm spell hit capped and attacking from behind. Tested this with a felhunter. (Unless there's some visual bug on dummies).

Proof: 

18.28% haste should either lower the cast time by 1.75/1.1828=**1.48** or 2.5/1.1820 - 0.75(talent) = **1.37**. Whichever is the right formula
![34d651cc5ce466f3964a08de9df7bb52](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/54c75c12-df09-468d-b61d-b26eae8fac20)

Dodges when spell hit capped.
![d2b4ecb0fa51091dd2ab704bcd945047](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/4b78cbbd-8812-4207-a8c5-3b53fabc49a0)

**How to reproduce:**
Summon imp and look at the cats time.

**How it should work:**

- Pets should scale dynamically with the owner's haste rating/crit/mastery( demonology ) 
- Spell hit cap should make your pet/guardians hit and expertise capped.

Taken from simcraft 4.3
![2df8f4f4e457789af29f810a67e43c71](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/b021b4e6-63e1-49ad-8728-8a73b2a56c76)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=30146
https://cata-twinhead.twinstar.cz/?spell=697
https://cata-twinhead.twinstar.cz/?spell=688
https://cata-twinhead.twinstar.cz/?spell=712

**Comment by bonfax4** [comment]
https://www.youtube.com/watch?v=J9ZCPu9uips See imp cast time during bloodlust (pets are affected by bloodlust too) and with the trinkett haste procs. It varies from 1.0/1.1/1.3 seconds.

**Comment by bonfax4** [comment]
It's always been the case since wotlk. Hit capped hunter will also make their pets be spell hit capped. Should scale proportionally and it doesn't round down like it used to. 8% hit on hunter means pets will have their 17% and 17% spell hit on caster means your pets are hit/expertise capped. Simc data shows this too

**Comment by bonfax4** [comment]
@UltraNix simcraft snippet
![0a559a0211838b57b3bb53138fcaffd4](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/f2c30bee-f577-442c-af11-19c6b8bff10c)

**Comment by bonfax4** [comment]
You're right for casters spell hit is 1:1 but expertise is proportional if simcraft is to be trusted ofc.

**Comment by bonfax4** [comment]
nvm

**Comment by BalanCV** [comment]
The problem right now with pets in general seems to be that they don't get expertise capped from owner hit rating. I'm seeing a lot of pet dodges in my weekly logs from hunters and locks.

**Comment by bonfax4** [comment]
#2614 Dk's too apparently

**Comment by bonfax4** [comment]
@UltraNix 
Doomguard and i guess guardians in general most likely should follow the same rule according to posts I'm seeing. Only scale from haste rating and not haste % mods. Tested and they currently get the haste bonus from dark intent on their snapshot.

https://www.mmo-champion.com/threads/1057628-Doomguard-Haste?highlight=doomguard+haste
> Actually he does scale with haste, just not %+ haste increases added to you. (He does get +% haste increases added directly to him, I.E swapping your DI to him or having a priest power infuse him). So if you have a trinket that gives haste rating, he'll scale with it, but bloodlust, PI (casted on you), etc won't.

> So it seems from my log that the doomguard not only scales with your haste rating only, but more like it snapshots your current haste % at the time of summoning for its doom bolt cast time.

**Comment by jlldarocha** [comment]
The full message on your 2nd quote is actually telling the opposite: doomguard does scale with % auras, as he was affected by nozdormu haste aura by inheriting the warlock haste % when he was summoned.

full quote:

> My doomguard did a total of 60 doom bolt casts on madness with only 140secs uptime. Nozdormu's buff was still up during both times when i summoned him.

> [http://www.worldoflogs.com/reports/9...=10927&e=11566](http://www.worldoflogs.com/reports/9wa7m9ik7k91dnrm/details/33/?s=10927&e=11566)

> If its true that doomguard only scales with your haste rating only, i would only have roughly 21% haste unbuffed. That would result in a 2.7s cast time or so for doom bolt.

> From my log though it seems that the average cast time of doom bolt was around 2.33s. Factoring in the doomguard's slow reaction time and cast delay, it'll probably be around slightly less than 2.3s per cast instead. That actually coincides with the amount of haste i have fully buffed and with nozdormu's buff, which is around 50% haste, which would bring doom bolt's cast time down to 2.25s.

> So it seems from my log that the doomguard not only scales with your haste rating only, but more like it snapshots your current haste % at the time of summoning for its doom bolt cast time.

> Would be nice to see more logs that support and confirm this claim though.



While on it, please also check mastery scaling for demonology on him, its doing nothing right now

**Comment by bonfax4** [comment]
50% haste qoule not reduce it by that amount if it snapshotted. Withou accounting for his haste it would put it on a 2 second xlcast

**Comment by jlldarocha** [comment]
Hes with 50% haste considering nozdormu buff, along with his gear and haste from % spell haste aura. And as he said, doomguard was slow on reacting and had a lil delay between casts, as if he was playing without spell queue.

**Comment by bonfax4** [comment]
Hmm I'm a look for a video. Its very possible pets and guardians actually get the buff themselves like sinestra.

**Comment by bonfax4** [comment]
https://www.youtube.com/watch?v=4wUy2jOtGGg 
There you go pets getting the buff directly from presences.

**Comment by Pornoodemon** [comment]
> Doomguard is still not affected by demonology mastery too.
> 
> he should scale with static mastery(gear) and dynamic mastery (if cast under a mastery proc or buff he should snapshot the mastery for entire duration)

Agree . This is exactly how it works. The doomguard and infernal should remember the stats at the time of the call and keep them for the entire duration of the guards

**Comment by bonfax4** [comment]
Another issue i'vecoem across: 

 Ebon Imp ( Bane of Doom summon) seems to be scaling with spell power. Removing my gear reduced the imp dmg to the 300's back from like 1.7k.  It should not scale with any of the owners stats. Going through videos in different patches you can see ebon imp does about the same range of dmg regardless of gear or spec ranging from 500-900 it seems, don't know the exact values. Tested fiery imp and its working fine.

**Comment by bonfax4** [comment]
@Ultranix one more thing to add, Imp currently has no gcd on firebolt and can go below 1.5 seconds casts with no pauses or delays. All pets/guardians should have a a 1.5 gcd. Maybe make it work similar to how gargoyles work currently where it wont go below 1.5 on the haste scaling.

**Comment by UltraNix** [comment]
@bonfax4 Please, make a new report with this as it's has nothing to do with scaling system.
