### ISSUE TITLE
Huargen dk unholy pet bug

### ISSUE THREAD

**Issue by Empanada7u7** [gamefreedomgit/Maelstrom#3674]
**Description:**
The undead summon of the dk huargen unholy doesn´t count as a pet like the ability says, it´s just a normal pet, lasts 60 seconds and the cooldown of the spell is 3 min.

**How to reproduce:**
Just be a huargen dk and choose unholy as your main.

**How it should work:**
The pet should stay with me forever, have abilities that i can control and the spell cooldown to summoning it should be 60 seconds.
![WoWScrnShot_053023_233541](https://github.com/gamefreedomgit/Maelstrom/assets/135090699/0bb9f50f-7c1b-4eae-b7d1-44a1be067739)
![WoWScrnShot_053023_233549](https://github.com/gamefreedomgit/Maelstrom/assets/135090699/4af223f2-fba0-4935-9bfd-3b1b8a684b85)
![WoWScrnShot_053023_233558](https://github.com/gamefreedomgit/Maelstrom/assets/135090699/2234d578-fb88-4cb7-aa27-927e9b55a654)

**Comment by Sketish** [comment]
Relog or respec should fix this issue
