### ISSUE TITLE
Rare moobs doenst spawn anymore

### ISSUE THREAD

**Issue by tenme12** [gamefreedomgit/Maelstrom#3675]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Rare moobs doenst spawn anymore
**How to reproduce:**
When i kill it for first time, i wait like 30 min and they dont appear again.

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Well rares have longer respawn in cataclysm, also speciify what exactly rare mobs were you looking for.

**Comment by Sketish** [comment]
Provide any proof it should habe 3 min respawn

**Comment by BalanCV** [comment]
Server had increased spawn rates when it freshly launched, now its normal how it should be.
