### ISSUE TITLE
[Hunter] Pet issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

- Hunter pets should not benefit from owner's haste auras. They already benefit from these auras themselves through buffs. Pet current attack speed is lowered from 2.00 to 1.67 with 10% aura, double dipping in an additive manner weirdly enough, usually these % calcs are multiplicative. 2/1.2 = 1.67 speed and from 2 to 1.25 (2/1.6) during bloodlust. 

- Bm hunter talent [Frenzy](https://cata-twinhead.twinstar.cz/?spell=19623) is proccing on auto-attacks, rather than pet basic attacks. Basic attack are spells like Bite, Claw, smack, etc. 
![843bfb6551df9edc856e507b782fe75d](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/3a352952-9253-4fa3-accc-d087de44ba81)

- [Kindred spirits ](https://cata-twinhead.twinstar.cz/?spell=56315)talent not increasing pet focus by 10.

**How to reproduce:**
Spec survival and look at pet speed.

**How it should work:**
Pet attack speed should be 2.00/1.1 = **1.82**. Or 2/1.1/1.3= **1.4** during lust+buff.

https://cata-twinhead.twinstar.cz/?issue=779 Sadly all the logs are inaccessible since WOL closed down.
![890ac1051d59a57cc5377feba17d301a](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/bb99bb4b-537d-4873-bd1c-4bfdebcb175a)

**Database links:**

**Comment by UltraNix** [comment]
```
Hunter pets should not benefit from owner's haste auras. They already benefit from these auras themselves through buffs
```
And what if hunter owns some haste aura and it's only applied hunter? Pet should get any of this?

**Comment by bonfax4** [comment]
> And what if hunter owns some haste aura and it's only applied on hunter? Pet should get any of this?

Nope. Only from stuff that increases haste rating like [trinkets](https://cata-twinhead.twinstar.cz/?item=69112).

**Comment by UltraNix** [comment]
Okay.

**Comment by bonfax4** [comment]
@Ultranix
Hunter according to EJ only scaled with buffs that we're not range haste only (which ment talents didnt transfer to pets, but that pretty much means pets were scaling only with 10% buff and 0 mentions of doubledips on hunter forums. If we follow this and the fact that pets did not scale with any haste buffs on the hunter from raid mechanics according to logs devs went thorugh on twinstar, it's pretty obvious that pets were scaling with direct haste % on them (Bloodlust/ 10% haste/ whatever mechanic hits pets). It would be easy to confuse the 2. 

Anotehr thing Pets also scale with other stats too but I didnt bother checking, like intellect for extra mana, stam,etc. Some pets don't scale with crit but have their own base crit chance, I was specific on the ones that cannot crit at all.

**Comment by UltraNix** [comment]
@bonfax4 Thanks for the info.

**Comment by bonfax4** [comment]
Before you close down this issue make sure this is fixed.  Bm pets ramping up frenzy quickly is really broken in low level pvp considering the dmg pets already do.

> Bm hunter talent [Frenzy](https://cata-twinhead.twinstar.cz/?spell=19623) is proccing on auto-attacks, rather than pet basic attacks. Basic attack are spells like Bite, Claw, smack, etc.

**Comment by bonfax4** [comment]
Or let me know if I should open another report

**Comment by Stega23** [comment]
> Orc racials working on guardians needs to be researched, doesnt feel right. Cant find reliable sources on it either.

It did work, ive found proof year or two ago resarching it, but it has since been deleted...
Can be tested on retail tho, nothing has changed except the fact that its now 1% on retail compared to 5% on cata

**Comment by UltraNix** [comment]
Fixed.
