### ISSUE TITLE
[NPC] Bannok Grimaxe

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3677]
**Description:**
The NPC has no loot, instead, he drops a green item as another Silver Dragon Rare NPC. In other hand, he doesn't casted his skills. Maybe those are corrected, and only use them while surrounded by enemies. Or maybe I killed too fast?

**How to reproduce:**
Engage him. kill and loot him to check.

**How it should work:**
The NPC has a loot table and must use it, including a Blacksmith pattern.

**Database links:**
https://www.wowhead.com/npc=9596/bannok-grimaxe

Old post where the skills were reported first time: https://github.com/SallyWhitemane/Maelstrom/issues/574

**Comment by Afgann** [comment]
fixed
