### ISSUE TITLE
Hand of Sacrifice is multiplying Burden of the Crowns damage

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Maelstrom#3680]
**Description:**
Having hand of sac on ap erson who has Burden of the crown instantly kills them and the paladin when they use an ability

**How to reproduce:**
Put Hand of Sacrifice onto a person with Burden of the Crown in BWD Eight dwarfs and have the person with burden use an ability

**How it should work:**
It shouldnt multiply how many it does, only reduce its damage via sac transfer

![image](https://github.com/gamefreedomgit/Maelstrom/assets/93952514/16a826f8-5a5b-4976-9dd1-f345501a1b68)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=80718

**Comment by UltraNix** [comment]
Fixed.
