### ISSUE TITLE
[Item] Twilight Snare

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3681]
**Description:**
Twilight Snare dropped by Twilight Dragonstalker for the quest To Catch a Dragon doesn't drop if any on the party has the item yet.

**How to reproduce:**
Two players, one loot the twilight snare, then the other try to kill the npcs with this first player with the snare in his bags. Npcs never drop the snare again while the first player have the snare yet.

**How it should work:**
the snare must drop for all the players, even if one of the players in the party has the snare yet.

**Database links:**
https://www.wowhead.com/item=60383/twilight-snare
https://www.wowhead.com/quest=26768/to-catch-a-dragon
https://www.wowhead.com/npc=43992/twilight-dragonstalker

**Comment by Sketish** [comment]
Fixed
