### ISSUE TITLE
Honor Among Thieves [Talent] overwrites Combo Points to your current target

### ISSUE THREAD

**Issue by Carapilsx** [gamefreedomgit/Maelstrom#3683]
**Description:**
The talent Honor Among Thieves overwrites Combo points on your **current** target (even when you have built combo points on another target). 
Every time you switch targets (only by targeting them) you'll lose your combo points on your previous target if you get a combo point proc.
**How to reproduce:**
Build Combo Points on Dummy 1 => Target Dummy 2 => Wait for a Honor Among Thieves combo point proc

**How it should work:**
The combo points received from the talent "Honor Among Thieves" should not overwrite your combo points on your previous target. It should give you combo points on the target you already have combo points on.

Video: https://www.twitch.tv/videos/1834722469

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51699

**Comment by Afgann** [comment]
fixed
