### ISSUE TITLE
[Guild Perk] Have Group, Will Travel

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3685]
**Description:**
The guild perk for mass travel: Have Group, Will Travel (in spanish Viaje en grupo) is not working at all.

**How to reproduce:**
Join a party with someother, cast the spell, noone gets summoned.

**How it should work:**
The spell must summon all the people in a raid/party to the caster position.

**Database links:**

https://wowwiki-archive.fandom.com/wiki/Have_Group,_Will_Travel
https://cata.cavernoftime.com/spell=83967

I cannot find the link of the perk in wowhead, seems dissapeared from the DB. From Wowhead:
Spell #83967 doesn't exist. May it is not in the game.

**Comment by DorizarN** [comment]
Works fine for me.

**Comment by UltraNix** [comment]
Also tested - works okay.
