### ISSUE TITLE
Retribution Paladin Overheal

### ISSUE THREAD

**Issue by lethalninja** [gamefreedomgit/Maelstrom#3686]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Yesterday when I was doing arenas with my mate, we were versus Retribution paladin and Arms warrior. So the arena started and we killed the Warrior, and we took the paladin to around 8-10k health points, and with only 1 Cast of Word of Glory he went to full hp and he killed us both. 
As far as I know they can't use Lay on Hands in arenas, so there isn't any chance that he healed himself with some other spell.

**How to reproduce:**
I think that the spell -> Word of Glory needs to be Nerfed, because I don't know how much Blizzard was thinking when they were making this spell and all the numeric values of it and stuff, but It is NOT balanced to be playing Retribution paladin and to be able to heal in Arenas more than Holy paladin.

**How it should work:**
It should Heal him with some decent amount, but not from 0 to 100 because this is literally Non-sense for a DPS class.

**Database links:**

**Comment by Sketish** [comment]
Please provide any proofs from retail video

**Comment by Pornoodemon** [comment]
> **Description:** Yesterday when I was doing arenas with my mate, we were versus Retribution paladin and Arms warrior. So the arena started and we killed the Warrior, and we took the paladin to around 8-10k health points, and with only 1 Cast of Word of Glory he went to full hp and he killed us both. As far as I know they can't use Lay on Hands in arenas, so there isn't any chance that he healed himself with some other spell.
> 
> **How to reproduce:** I think that the spell -> Word of Glory needs to be Nerfed, because I don't know how much Blizzard was thinking when they were making this spell and all the numeric values of it and stuff, but It is NOT balanced to be playing Retribution paladin and to be able to heal in Arenas more than Holy paladin.
> 
> **How it should work:** It should Heal him with some decent amount, but not from 0 to 100 because this is literally Non-sense for a DPS class.
> 
> **Database links:**

I went to the arena with a paladin and it happened that he restored my full hp about 5 times during a battle. I agree that there is clearly some sort of overkill with a heal, but since I’m not strong in the class, it’s not possible to say for sure why this is happening Can . heal crits were 80-110k hp

**Comment by Renehadox** [comment]
WoG should crit heal over 100k in Cata season on a partner with buffs and shit.
WoG isn't bugged, looks pretty much normal to me.
Maybe he had, x2 trinket procs, Sacred Shield, Wings and he was low hp.

**Comment by Pornoodemon** [comment]
> WoG should crit heal over 100k in Cata season on a partner with buffs and shit. WoG isn't bugged, looks pretty much normal to me. Maybe he had, x2 trinket procs, Sacred Shield, Wings and he was low hp.

And in season 11, how much will they healing 150-200k?

**Comment by Pornoodemon** [comment]
Need to create a paladin on a test server and check the formulas

**Comment by UltraNix** [comment]
@lethalninja Combat logs would be the best.

**Comment by UltraNix** [comment]
No further info - closing.
