### ISSUE TITLE
[Quest] Joys of Omosh

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3687]
**Description:**
The quest doesn't exist. Orokk doesnt give it to you, so you failt to get the BlackSmithing pattern: https://www.wowhead.com/classic/item=7982/plans-barbaric-iron-gloves

EDIT1: After a GM gave me the quest ingame manually, when I finished the quest, I noted the last conversation of the NPC don't show the item https://www.wowhead.com/classic/item=7982/plans-barbaric-iron-gloves as a reward, but it gives it to ou after you click the button.

**How to reproduce:**
Nothing to do, the NPC doesn't give you the quest.

**How it should work:**
The npc must give you the quest. NPC must show you the item on the last conversation as the reward, not only text.

**Database links:**
https://www.wowhead.com/quest=2755/joys-of-omosh
https://www.wowhead.com/classic/item=7982/plans-barbaric-iron-gloves

Maybe linked with https://github.com/gamefreedomgit/Maelstrom/issues/3583

**Comment by PanJanuszek** [comment]
Ok, few things
a) Blacksmithing required
b) 140 skill required
c) This is 4 quest chain, starting on quest id 2751

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/e7f13b3b-286d-436d-b202-2eda30e60529)

Closing, not a issue
