### ISSUE TITLE
[Dungeon] Heroic Deadmines - Helix Gearbreaker

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#3688]
The Helix Gearbreaker encounter seems to have multiple issues, some of which are already outlined in #3245.

To add to that, mines often tend to spawn underground, seem to explode multiple times.

The encounter often also resets when Helix himself is on low health. Players are stuck in combat after that although the boss doesn't attack again, unable to resurrect fellow players or eat/drink.
If players then exit the dungeon, the encounter does not reset, rendering the group unable to resume/return to the dungeon.

**Comment by UltraNix** [comment]
Don't duplicate reports - just add your comment there.
