### ISSUE TITLE
Blood dk

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3689]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello. I don’t know much about the DK class. But dk in the specialization of blood has some kind of unreal heal and damage. No matter how much damage inflicted on him, 1-2 hits are enough to restore all hp. And about dropping the mole in general. 1-2 HIT. Despite the fact that I play as a caster and try not to let him near me. 
Any melee class cannot win Blood dk by default.
I play a warlock 3.4 res.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/89894d04-ac48-4a25-bb2d-64aa4d990f88)

 The video shows how the dk kills with two hits. Despite the fact that this is the "MEDIUM" damage that they cause
In my opinion, this is the most unbalanced specialization. I have played on various cataclysm projects before, but I see such bdk for the first time.

**How to reproduce:**

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7f2b2485-bba9-4de8-9fc1-a7f8512efd77

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Proofs, not speculations/wonders.
What exactly does not work? "that class has too much damage" says nothing to devs.

**Comment by Pornoodemon** [comment]
> Доказательства, а не предположения/чудеса. Что именно не работает? «у этого класса слишком много урона» ничего не говорит разработчикам.

I've only seen this with some Bdk players who give a one-shot and know some loopholes. But I can’t figure out how to repeat this, and I thought maybe one of the players could tell me what’s wrong. I think the topic can be closed
