### ISSUE TITLE
Unreachable Archeology node in Un'Goro Lakkari Tar Pits

### ISSUE THREAD

**Issue by MorbidMike** [gamefreedomgit/Maelstrom#3690]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a bugged Archeology node in the Lakkari Tar Pits (Fossil area). That node is unreachable (either very high in the air or underground).
Trying to reach it yields a lot of "red" lights in a circular pattern around that node's position (somewhere around 49.6;31.3). Experience with Archeology taught me that the light (green/yellow/red) measures 3 dimensional distances; not just north-south and east-west but also high-low. Since the area that node is in is completely flat, I suspect that the node is somehow up in the tree or below ground. See attached images.

**How to reproduce:**
I guess you could reproduce it by doing a lot of Archeology in the Lakkari Tar Pits until the bugged node pops up.

**How it should work:**
The "red" light should become yellow/green as you zone in on the node. That does not happen, so the node must be far away from the player vertically.

**Database links:**
![Screenshot from 2023-06-01 19-45-41](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/5c5619bb-152d-4e52-b6a0-30fad752c3f0)
![Screenshot from 2023-06-01 19-46-02](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/4ba75909-1b50-42be-b2ac-116530ec2337)
![Screenshot from 2023-06-01 19-46-18](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/88ed2c53-b26f-431c-aba4-9082e246af11)
![Screenshot from 2023-06-01 19-46-35](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/6a70c5ba-c075-4bf4-a5dc-923649f679a9)
![Screenshot from 2023-06-01 19-46-50](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/360c5d6c-5e95-41e7-936a-436d3201a21a)
![Screenshot from 2023-06-01 19-47-21](https://github.com/gamefreedomgit/Maelstrom/assets/2880791/5124310d-449a-48a1-af38-5a58f2e9658f)

**Comment by UltraNix** [comment]
Fixed.
