### ISSUE TITLE
 [Baradin Grunt's Talisman]

### ISSUE THREAD

**Issue by jpaardekooper** [gamefreedomgit/Maelstrom#3692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)

[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This trinket took some time to farm and not able to use it correctly is just a waste of time

**How to reproduce:**
use the trinket and u see the mobs hitting for 300

**How it should work:**
Lasts for 30 secs
Hits for 3k-4,7k
Crits for 2x dmg so (6-9k)
Strike ability is cast 3 times if in combat for the whole duration and does slightly more dmg than white hits

**Database links:**
https://www.wowhead.com/item=65176/baradin-grunts-talisman#comments

**Comment by Afgann** [comment]
fixed
