### ISSUE TITLE
[Dungeon] Zul'Gurub - High Priest Venoxis

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#3695]
The Venomous Effusion maze spawned in the Venoxis encounter seems have a bit too large of an area of effect. In some places you can't really walk between "walls" without taking damage, which makes running away from the Bloodvenom beams difficult.

In addition, I believe on retail it was possible to jump over the walls (which [this WoWWiki archive](https://wowwiki-archive.fandom.com/wiki/High_Priest_Venoxis) seems to agree with), currently jumping over those walls causes damage.

The maximum number of beams during the Bloodvenom ability should be 3 (it's even stated in the dungeon journal), currently the ability targets every player.

Edit:
Similar to the issue with Bloodvenom, there also seems to be an issue with the mob next to the cauldron in front of the Venoxis enclosure (Venomancer T'Kulu). It spawns venom links on all players in the vicinity at the same time, which shouldn't be the case. The link should only link 2 players at a time. The distance people need to travel to break the chains also seems to be farther than was the case on retail, although that may be the result of the ability just targeting too many players and requiring all to be a distance apart from other players before it breaks.

**Comment by Afgann** [comment]
fixed
