### ISSUE TITLE
King of the Foulweald & Defend the Tree! Quests Progression Bug

### ISSUE THREAD

**Issue by zachacuna198** [gamefreedomgit/Maelstrom#3696]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest 'Defend the Tree!', assimilating with the Shadumbra results in a permanent 0/100 Energy bar that does not regenerate. Restarting does not resolve the issue, nor does dismounting and remounting at the quest-giver. Both quests were done on a Worgen Hunter with a Bear pet.

During the quest 'King of the Foulweald', placing the banner upon the totem mound in Greenpaw Village does not result in the spawn of Enraged furbolgs nor the main boss, Chief Murgut. Repeated placings of the banner and restarting of the client does not resolve the issue.

**How to reproduce:**
'Defend the Tree!' bug:
Scale the tower and speak to Halannia, who will combine/mount the player to the spirit of Shadumbra. In doing so, the Shadumbra's energy bar will be shown as 0/100 and will not regain energy through any means.

'King of the Foulweald' bug:
Make your way to Greenpaw Village (near the intersection of the two nearby roads) and place the banner given by Karang Amakkar upon the totem mound. 

**How it should work:**
'Defend the Tree!' will not spawn the Shadumbra spirit with any energy with which to use skills to kill the Horde outside the building. Attempting to fight the Horde results in a dismount and no quest progression. 

'King of the Foulweald' will not spawn any enemies, neither the Enraged Furbolgs nor the boss, Chief Murgut. Progression not possible.

**Database links:**
https://www.wowhead.com/quest=13935/defend-the-tree
https://www.wowhead.com/classic/quest=6621/king-of-the-foulweald

**Comment by thedave88** [comment]
![WoWScrnShot_112723_233759](https://github.com/gamefreedomgit/Maelstrom/assets/152223565/4daadd88-df11-44f4-8b8b-684bcc053199)

**Comment by PanJanuszek** [comment]
fixed 15.01.2024
