### ISSUE TITLE
[AH] Glyphs ignore "Usable items" filter

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3698]
**Description:**
When you search for a glyph in the auction house, you may use the option filter "usable items only". But the option doesn't filter known yet glyphs.

**How to reproduce:**
Go to AH, select option "glyphs", then, select the option "Usable items" on top AH screen. Known-yet glyphs are still there,

**How it should work:**
It must filter the known-yet glyphs.

**Database links:**
no links

![image](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/4dfa259b-ac06-4f2d-9dbb-4c2a9570a277)

**Comment by UltraNix** [comment]
Fixed.
