### ISSUE TITLE
[LFG] Dungeon Searcher got bugged at level 59

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3699]
**Description:**
The dungeon searcher got bugged at lvl 59. Right now in the dropbox tells "Burning Crusade random dungeon" (that's ok), but when I click on "Search Group", it tells "You do not meet the requirements to enter the chosen dungeon." Maybe related to an error on all the Burning Crusade normal dungeons showing as "You cannot join to this dungeon." "You have an id for this dungeon". Cannot be solved with /reload. Cannot be solved disconnectiong the character.

**How to reproduce:**
Reach lvl 59 and try to join random dungeon.

**How it should work:**
You always can join to the Random LFG

**Database links:**
no links

![image](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/c617fe6b-4297-457e-9435-a6d615874565)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/92bdaa92-d0c9-4274-9a21-2b15aac2834a)

**Comment by Sketish** [comment]
Since people are skipping  60-80 content queue for those dungeons were disabled

**Comment by varjla** [comment]
> Since people are skipping 60-80 content queue for those dungeons were disabled

Ok, but why I cannot continue joining to the 55-60 dungeons with the Random Dungeon Finder? that forces players to do some quests or BGs. Ok, let the TBC and LK content stay disabled. But disable the change at level 58-59 on the RDF and let people continue with Classic dungeons.

**Comment by Sketish** [comment]
Its more about client side than bug. On level 58 you have classic rdf, on 59 it becomes tbc rdf due to 2 tbc dungeons being available.
