### ISSUE TITLE
Doomguard isnt affected by demonology mastery

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#3701]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Summon doomguard isnt gaining bonus damage with demonology mastery. He does the same damage per cast as he does on affliction and destruction, and lowering or raising your mastery value does nothing for it.

**26% mastery damage:**
![commastery](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/b778c08b-8d00-463e-a72f-671499a6c7bc)

**18% mastery damage (Base mastery)**
![semmastery](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/10064b05-8636-485d-a6d0-a4475717ca19)

**How to reproduce:**

Summon doomguards as demo, affli and destru.  Then summon doomguards as demo, with different levels of mastery without changing the other attributes.

**How it should work:**
Doomguard should gain the same damage bonus as all pets and guardians with demonology mastery, with a difference: he snapshots the mastery value at the summon cast.

**Comment by UltraNix** [comment]
Fixed.
