### ISSUE TITLE
All demo warlock guardian pets scaling issue mastery/haste

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3702]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently all demo warlock  guardian pets are not benefiting from mastery on autoattacks ( WHITE attacks) even though they should as stated by mastery tooltip. Some guardian pets are not benefiting by haste on autoattack or spell even though they should as established by precedent fix gamefreedomgit/Maelstrom#3673  (their auto is 2.0 speed regardless of owner haste)

More detailed:
Ebon Imp (guardian pet summoned by bane of doom)
Autoattacks not benefiting from either mastery nor haste. (no other special ability here)

Infernal
Autoattacks not benefiting from either mastery nor haste. 
Immolation ticks not benefiting from either mastery nor haste.

Will not address doomguard as someone else opened post for that specifically.

**How to reproduce:**
Use mastery/haste test rings on test server and track pets on test server

**How it should work:**

**Database links:**

**Comment by Gnom56** [comment]
Just checked pet tooltips, Destro:
![obraz](https://github.com/gamefreedomgit/Maelstrom/assets/128646169/d1d93f9c-66b4-4a18-921b-93125840c7fe)
Demo: 
![obraz](https://github.com/gamefreedomgit/Maelstrom/assets/128646169/9c4d176a-e2d0-44e4-a72c-9278ea2f76be)

**Comment by BalanCV** [comment]
Perhaps i should have clarified, was talking about Demonology Mastery. Will edit title

**Comment by Sketish** [comment]
Connected with https://github.com/gamefreedomgit/Maelstrom/issues/3701

**Comment by bonfax4** [comment]
Nah i looked around in videos before and ebon imp is roughly doing the same range of dmg between specs. Feel free to do research tho.

**Comment by BalanCV** [comment]
https://wowpedia.fandom.com/wiki/Bane_of_Doom
"[Patch 4.1.0](https://wowpedia.fandom.com/wiki/Patch_4.1.0) (2011-04-26): Imps summoned by Bane of Doom now benefit from the warlock's stats."
Since their damage is so low anyways around 30% from mastery is hard to notice anyway, I'm just arguing for it in order to progress on making pets and guardians streamlined on this server.
There might be a good chance you are right, but not scaling with mastery makes the least sense out of all and keep in mind blizzard was not bug free either :)

**Comment by bonfax4** [comment]
Dude check videos instead. Simc shows exactly what the videos show on terms of dmg. I checked 4.3 retail videos when i was researching exactly this issue. Would be very noticeable with DS gear

**Comment by BalanCV** [comment]
I am checking the direct code of simcraft and there are multiple lines of // comments indicating that they are not sure on certain matters either. (For example "//Please check if orc racial actually benefits, has been unknown and taken for granted")
According to your list e-imp should not scale with int/sp either but there are some wowhead comments showcasing different damage at different sp levels.
Regardless, this is turning into an infinite argument so I'll make this the last comment on the subject and let the devs decide the end result.

**Comment by UltraNix** [comment]
Fixed.
