### ISSUE TITLE
[Hunter] [Pet] [Growl] [Pet Spell]

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3704]
**Description:**
https://github.com/gamefreedomgit/Maelstrom/issues/3197
I'd like to reopen the issue, while the author flagged the spell as broken/bugged he didn't provide enough information in time the thread was open.
The pet taunt Growl ID:"2649" like previously stated is not working properly, the threat generated is on the extreme side, low where a single auto shot can produce more aggro & reach the pull aggro
**How to reproduce:**
Any generic hunter pet with growl cast or auto cast on an hostile npc.

**How it should work:**
I won't even pretend I fully understand after years of playing the game how threat works and after trying to find out how it should properly work in this case I learnt that the threat system was changed for cataclysm.
Before I go further I like to point out that while the spell is bugged, the pet scaling @85 level is still not resolved at the time of writing so bear in mind  when conducting your own tests.

The pet spell Growl:"2649"  has a base threat of 1.4k(I believe? Its only 1.4k on the server) and should generate further threat with  **pet attack power**

![growl](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/eb8e5346-c4fb-4b88-a4d5-769ee6ae66b3)

Pardon the poorly cropped image but I did not want to post dozens of images,

left side of the image  equipped gear, aspect on, pet ap 7304, single attack and growl = generated threat of 44.6k
right side of the image unequipped gear, aspect on, pet ap 3167(I noticed I did not include it, please take my word for it, hunter rap 5260.)single attack and growl = generated threat of 20.2k
44600 - 1591 / 7304 = 5.888
500% increase of 7304 = 43824 
Edit: Dammit I do not know how to strikethrough text, tons of edits over this.
**Database links:**

https://cata-twinhead.twinstar.cz/?spell=2649

**Comment by UltraNix** [comment]
I don;t see any source claiming the threat done by Growl should be modified by AP. It has a moderated 1373,90 threat amount on 85 lvl. There are more info about it: https://web.archive.org/web/20141006062018/http://us.battle.net/wow/en/forum/topic/9972467373
Also, what is the math? What is that 500%?

**Comment by NinacS90** [comment]
Hello, sorry I was unable to respond until now, I know that you understand how difficult is to dig up information and few videos I have seen are so blurry but the time where they were uploaded they were considered high quality, yes that ancient.
"Growl (pet) | +1234 base (rank 9) to pet, scales with pet attack power and level
 attack power and level"
taken from,
https://wowwiki-archive.fandom.com/wiki/Threat

Now this is outdated information due how threat works in Cataclysm. In Cataclysm they I guess streamlined threat generation so now its damage done to threat generation to be 1:1, further threat reduction being provided by temporally buffs or spells, Rogues Vanish, Hunters Feign death, Priests Fade, Paladins Hand of Salvation to name a few but I am rambling anyway moving on.
 (I can't speak for further expansions since I have never played them. Now, the threat in cataclysm is 300% until 4.2 (500% since 4.2) increased for tanks,(for pets this doesn't mean the white attack, basic attack, special attacks) dammit as I am typing I am trying to open the link to another window so I can paste it here only to be redirected to the World of Warcraft site.)

Edit: found a different source 
https://www.engadget.com/2011-08-16-patch-4-2-hotfixes-for-august-11.html
"Threat generation for all tanks has been increased to 500%, up from 300%. This applies to warriors in Defensive Stance, death knights in Blood Presence, druids in Bear Form, and paladins with Righteous Fury."

Now to reiterate while we are at 4.1 patch but talents, spells,, crafted items are for 4.3.4(or better to say a later patch,some items have been disabled) and the threat generation is true, I have tested it on a paladin with RF on, the single spell hit did 5071 holy damage and the threat generated was at 31.6xx.

I apologize for my lackluster of a post but it was done in a hurry and when I post I always hope that others more knowledgeable will quickly pile on to save the day but in my next life I will pay more attention in school when it comes to math, I am just stuck using formulas and online calculators.

So an example of how it should work

pet melee attack : 200
pet basic attack : 300
hunter's kill command : 1000
hunter's auto attack : 1200
hunter's arcane shot : 1200

This will generate 1500 threat for the pet and 2400 threat for the hunter which result in a overaggro however,
if growl was casted and for this example lets say the pet has 250 ap, then growl should generate (500%) 1500 threat.

I am basing this on a character that is on a same patch but on a different server, I hope you understand my reluctance to post further, however I agree if it is working properly here then it might be working better than intended on the other side, but still that being said if there is a issue with my explanation of if you feel there is a problem with the language I can hop on discord or ingame and well, try to find a hunter with more knowledge.

Final thoughts, I can't remember exactly where I read it but "Growl is your way to maintain aggro on multiple mobs in Cataclysm" (often creature target swap) or maybe I am remembering wrong, well ingame example on my hunter with several elite mobs I have to constantly keep Misdirection on, and the heal alone which is 0.5 threat of the amount healed is often more than enough to keep a high threat and even overaggro

**Comment by UltraNix** [comment]
It might be outdated as it shows wotlk data.

**Comment by NinacS90** [comment]
Yes I mentioned it but there is data about Cataclysm as well, the quote I posted is from 16/08/2011 hotfix patch "Threat generation for all tanks has been increased to 500%, up from 300%. This applies to warriors in Defensive Stance, death knights in Blood Presence, druids in Bear Form, and paladins with Righteous Fury." Unless you are referring to something else?

**Comment by NinacS90** [comment]
I will just post another comment instead of an edit, 

As I read through those comments there are a lot of claims that growl is not working properly, its on auto cast and its not casting, with md on and people having issues with threat
Is it possible at that date there was a glitch with the hunter pets but then again, those guys are like me, prone to misunderstandings

**Comment by UltraNix** [comment]
@NinacS90 Hmm, you are right here - something is off here.
On wotlk you had 1234 base + 5400 at 80 lvl. On cata we have only 1373,90 a big difference. Something we misses here.
