### ISSUE TITLE
[Warlock] Imp gcd

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3705]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Imp firebolt ~~not triggering gcd~~ gcd scaling with haste ? Allowing them to spam sub 1.5 second casts.

during high haste proc 
![947eb149906f46b8b769a8c580736f2a](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0a947d74-7ecc-4dcc-aed8-2d3301eb6021)

**How to reproduce:**
Stack haste

Use this macro

/cast Firebolt
/script local _,gcd=GetSpellCooldown("Firebolt"); print("Current global cooldown is "..gcd.." seconds.")

**How it should work:**
Imps spells should trigger a 1,5 sec gcd unscalable.

**Database links:**

**Comment by Sketish** [comment]
Please provide any source

**Comment by bonfax4** [comment]
> Please provide any source

Minimum gcd 1.5 on sim (Pet/Guardians gcds never scale with haste generally. You can go through any pet or guardian on sim and check,  why unholy gargoyle has an haste "cap" if you check guides )
![c048187ebf3fef82022bd46ad8888300](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/6a2057ca-755c-4ef0-9c74-196ac54def6c)

Person here detailing this exact issue that transcribed logs (luckily) during sinestra high haste buff on pet. Retail log in the bottom with 1.5+ (cast + travel time ) with 100% haste buff.

> Twin:
> [19:51:03.583] Chorin Firebolt Sinestra 5372 (O: 0)
> [19:51:04.376] Chorin Firebolt Sinestra 5375 (O: 0)
> [19:51:04.830] Chorin Firebolt Sinestra 5365 (O: 0)
> [19:51:05.297] Chorin Firebolt Sinestra *11044* (O: 0)
> [19:51:05.779] Chorin Firebolt Sinestra 5372 (O: 0)
> [19:51:06.240] Chorin Firebolt Sinestra 5368 (O: 0)
> [19:51:07.006] Chorin Firebolt Sinestra *11030* (O: 0)
> [19:51:07.471] Chorin Firebolt Sinestra *11057* (O: 0)
> [19:51:08.260] Chorin Firebolt Sinestra 5372 (O: 0)
> [19:51:08.741] Chorin Firebolt Sinestra 5368 (O: 0)
> 
> Offi: http://www.worldoflogs.com/reports/b0y6nm2z2dbpchms/sum/damageDone/?s=11515&e=11827
> 
> [23:50:45.302] Jakrot Firebolt Sinestra 7006
> [23:50:47.002] Jakrot Firebolt Sinestra 7009
> [23:50:48.501] Jakrot Firebolt Sinestra *13983*
> [23:50:50.138] Jakrot Firebolt Sinestra 7014
> [23:50:51.698] Jakrot Firebolt Sinestra 7009
> [23:50:53.311] Jakrot Firebolt Sinestra *13980*
> [23:50:54.901] Jakrot Firebolt Sinestra 6701
> [23:50:56.496] Jakrot Firebolt Sinestra 6438

**Comment by UltraNix** [comment]
Fixed.
