### ISSUE TITLE
[Druid] Treants/Force of nature

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3706]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Treants have a base atackspeed of 2 seconds.
![8cc06affaddd21e109cf1285198aff56](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/a43bf1ce-9f9b-48ef-9e42-56b205ddbf4d)

**How to reproduce:**
Summon treants and run the macro below to show pet window.

/run if not oldHasPetUI then oldHasPetUI = HasPetUI; HasPetUI = function() return true, false; end end PetTab_Update() ToggleCharacter("PetPaperDollFrame")

**How it should work:**

Treants should have a base atack speed of 1.65.

![475516a91324ce9b211930a96b1a2f4c](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0b1f2b9c-4a62-4d71-b3b6-2d4a4fb36c8c)
s.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
