### ISSUE TITLE
Quest Missing

### ISSUE THREAD

**Issue by lethalninja** [gamefreedomgit/Maelstrom#3707]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I abandoned my Twilight Highlands quest, and now I can't take it from the NPC in Azshara. The quest is the last before I must get the zeppelin to Twilight Highlands, don't remember the name

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by MrTide** [comment]
resolved ingame closing it
