### ISSUE TITLE
DoT Clipping

### ISSUE THREAD

**Issue by Evtanaziq** [gamefreedomgit/Maelstrom#3708]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** DoT Clipping is not working for some DoT Effects since last night

**How to reproduce:** Cast Mind Flay and then a second one before the first expires and it will lose the last tick of the first Mind Flay

**How it should work:** If my mind flay channel time is 2.5 sec and if I cast a second Mind Flay while the first one has 0.5 s to finish channeling, the second Mind Flay should Last 3.0sec because the last tick of the first Mind Flay gets added into the new cast. And this is exactly how it actually worked until like 40 hours ago.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by Evtanaziq** [comment]
Thank you!
