### ISSUE TITLE
KotEB quest:	 I Have an Idea, But First...

### ISSUE THREAD

**Issue by Trevor1189** [gamefreedomgit/Maelstrom#3709]
**Description:**
The Icecrown quest "it's All Fun and Games", once completed and delivered to the NPC "Baron Silver" (coords: 44, 25), does not unlock the following quest "I Have an Idea, But First..." as it should.

**Extra:**
Baron Silver is pivotal "Knight of the Ebon Blade" Questgiver since his quests are part of chains which unlock the "shadow vault knight of the ebon blade" dailies.

**Database links:**
https://wowpedia.fandom.com/wiki/Baron_Sliver
https://wowpedia.fandom.com/wiki/It%27s_All_Fun_and_Games
https://wowpedia.fandom.com/wiki/I_Have_an_Idea,_But_First...

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
