### ISSUE TITLE
Malygos second/third phase

### ISSUE THREAD

**Issue by Shakrei** [gamefreedomgit/Maelstrom#3713]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On 2nd phase the discs are flat on the ground which is a bit problematic if you're a melee - you can't fly up to the mobs. On third phase drakes have 0 energy and gain no energy.
Energy should be regenerated at 10/sec.

![malygos](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/bfaa2391-d211-4298-8caf-4b4a669b6059)

**Comment by PanJanuszek** [comment]
fixed 20.05.2024
