### ISSUE TITLE
Warlock  "Talent Soul Siphon "

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3718]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Talent Soul Siphon ( Branch Affliction) not working.
- Increases the amount drained by your Drain Life and Drain Soul spells by an additional 6% for each of your Affliction effects on the target, up to a maximum of 18% additional effect. | Increases the amount drained by your Drain Life and Drain Soul spells by an additional 6% for each of your Affliction effects on the target, up to a maximum of 18% additional effect. |  
https://cata-twinhead.twinstar.cz/?spell=17805
Screenshot of heal without Affliction effects - 3082 hp
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/184f44d0-a79d-4b43-b49e-3e91b227743e)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/62784da1-a45e-4aba-ab52-25ab94f500c5)
With 3 Affliction effects  effects - - 3082 hp.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/66171020-1e7a-4ce1-8b85-26a659bfe388)

**How to reproduce:**

**How it should work:**

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=17805

**Comment by Pornoodemon** [comment]
I want to note that Affliction effects count any debuff from the Affliction category, for example, fear and Curse of the Elements, and not just effects of periodic damage

**Comment by Sketish** [comment]
Please provide any retail proof it should increase both dmg and healing and not just dmg

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/71d8eca2-89ca-459e-9a28-4101a5dd8790)
 According to elitisjerks it should only increase dmg

**Comment by Pornoodemon** [comment]
> ![image](https://user-images.githubusercontent.com/122209088/243394378-71d8eca2-89ca-459e-9a28-4101a5dd8790.png) According to elitisjerks it should only increase dmg

This is a error. This talent, roughly speaking, was created for this.

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/841723-Soul-Siphon?highlight=Soul+siphon 

Nope this is fine. Only the dmg portion was affected
