### ISSUE TITLE
Warlock "Talent Demonic Pact"

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3719]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?spell=47236
Warlock "Talent Demonic Pact" Partially not working.
Does not passively increase spell power by 2%.
before and after using the talent, spell power remains at around 6295

Before
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/0598ccd1-ef10-4dbc-9916-8b0c02cfc4c2)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/e5373a56-b434-4c34-82fb-98bc748d5738)
After
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/3c01bb89-d087-4d78-9042-68793a77ca62)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/1c7a7c42-caf4-442e-b631-42bd413339e4)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by BalanCV** [comment]
You need to have your demon summoned first (lol) and then check if you get 10% instead of 12%

**Comment by Pornoodemon** [comment]
> You need to have your demon summoned first (lol) and then check if you get 10% instead of 12% Edit: but yes tried it out just now with demon out and it gives 10% instead of 12%

2% should work passively regardless of the active buff from the pet. Yes, and I checked it does not work.

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c1ef9ed4-6d53-4051-9b96-8648fdf237a2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/f8e2c297-e510-40d8-aa08-550b762565ae)
exactly 10%

**Comment by jlldarocha** [comment]
its 2% spell DAMAGE, not spell power

**Comment by Pornoodemon** [comment]
The Russian translation just says "Increases spell power by 2%", but in fact, if you take damage from the spells themselves, then these 2% work. So we can close the topic.
![куексвмсм](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/2ef9ec09-5af1-4d87-a300-4c0aefb331c8)

**Comment by UltraNix** [comment]
That 2% bonus is not visible in UI. Works okay.
