### ISSUE TITLE
Warlock " Spell Dark Intent"

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3720]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?spell=80398#issues
Spell Dark Intent partially does not work, namely the second part of the talent(When you or the linked target gains a critical periodic damage or healing effect, the other gains increased periodic damage and healing lasting for 7sec. You gain 3%, while the target gains 3%. Stacks up to 3 times. )

Visually, the buff appears but does not affect either the heal or the periodic damage.
In the screenshots buff on 3 stacks

![qweqwew](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/af336ca2-6059-4cd4-9099-b66a4dcac656)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Drain's Life healing snould not be affected by this talent.

**Comment by Pornoodemon** [comment]
> Drain's Life healing snould not be affected by this talent.

This is strange because according to the description, it should enhance the effects of periodic damage and "healing"

**Comment by UltraNix** [comment]
Healing part of Drain Life is not a periodic.

**Comment by UltraNix** [comment]
Fixed.
