### ISSUE TITLE
Warlock "Talent Doom and Gloom"

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3721]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?spell=18829
Warlock Talent "Doom and Gloom" not working.
 "Bane of Doom"Damage before and after using the two  talent points
 Same with Bane of Agony
![qweqwew](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/a03a44dd-037c-4c13-9176-38c8c2ecb9b8)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
It's increasing criting chance so screenshots are not proving anything

**Comment by Pornoodemon** [comment]
> It's increasing criting chance so screenshots are not proving anything

Yes you are right . Apparently I read something wrong because of a mistake in translation from English. I think the topic can be closed
