### ISSUE TITLE
[Game Objects] [Heavy Junkbox] ID:"16885" Missing Loot Table

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3723]
**Description:**
Boxes are empty

**How to reproduce:**
Heavy junkboxes are pickpocketed from mobs 50-60 levels, you need to have a rogue open or a blacksmith to use skeleton key
 
**How it should work:**
It should have a loot table of 60+ items, nothing of significance however according to wowhead comments, it has a ridiculously small chance to drop the item linked below,
https://www.wowhead.com/item=1728
Also, you should be able to lockpick the box, loot any valuables and as long as you leave something in it, it should remain in your inventory and still be elidable  for a repeatable quest for the Ravenholdt faction linked below

https://cata-twinhead.twinstar.cz/?quest=8249

**Database links:**
https://cata-twinhead.twinstar.cz/?item=16885
https://www.wowhead.com/wotlk/item=16885/heavy-junkbox

**Comment by Afgann** [comment]
fixed
