### ISSUE TITLE
Battlemaster Trinkets are stackable

### ISSUE THREAD

**Issue by Vnrs0** [gamefreedomgit/Maelstrom#3724]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134795729/bd5ca722-3bf2-427b-aeec-0709b8d42ffa)

**Description:** Battlemaster trinkets are stackable but probably shouldnt be

**How to reproduce:**
equip 2 trinkets with on use HP increase, use them both. (pref. in a macro: /use 13 /use 14)

**How it should work:**
only 1 BM trinket should be active at a time, with the other one going on a 30-second cooldown or something like that

**Database links:**
too lazy to find

**Comment by UltraNix** [comment]
Fixed.
