### ISSUE TITLE
RDF HC - declining cooldown grants deserter.

### ISSUE THREAD

**Issue by CreepyJoker** [gamefreedomgit/Maelstrom#3725]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The RDF deserter debuff is applied if you get into a group that has for example 1/4 bosses down and you decline getting a cooldown for it in order to continue the dungeon.

**How to reproduce:**
Join a RDF that's in progress and has any bosses defeated, then decline the pop-up that grants you CD on that dungeon, then leave the party.

**How it should work:**
If you decline the CD, you should not be granted the Deserter debuff.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
