### ISSUE TITLE
Quest "natural remedies" (tbc) does not work correctly

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3726]
**Description:**
Quest does not work correctly as it is supposed to.
No cast bar, no animations on crystal, no NPC that pops up with monologue, shardlings that pop up seperately, severely delayed goliathon spawn

**How to reproduce:**
Use the item on the earth ring and it will not behave properly.

**How it should work:**
https://www.youtube.com/watch?v=LCQhiZ_8lfI

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=10351

**Comment by PanJanuszek** [comment]
fixed after server update
