### ISSUE TITLE
Archaeology Digsite: Oneiros Digsite

### ISSUE THREAD

**Issue by Apache77** [gamefreedomgit/Maelstrom#3727]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Archaeology Digsite: Oneiros Digsite bugged. 
Objects spawn high up in the air.
Pointing telescope randomly changes direction out of nowhere.
Telescope points outside the bounds of the digsite.

**How to reproduce:**
Try to perform archaeology there.

**How it should work:**
Self explanatory.

**Database links:**
https://wowpedia.fandom.com/wiki/Oneiros

![WoWScrnShot_060223_011742](https://github.com/gamefreedomgit/Maelstrom/assets/76235260/56d5c012-60da-4051-8cdf-69113597d7c8)
![WoWScrnShot_060223_011754](https://github.com/gamefreedomgit/Maelstrom/assets/76235260/df089144-0473-44d6-bb2c-a42056cbb674)

**Comment by UltraNix** [comment]
#3851
