### ISSUE TITLE
Minor bug with portal from Twilight Highlands to Orgrimmar

### ISSUE THREAD

**Issue by initialactivity** [gamefreedomgit/Maelstrom#3728]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I return to Orgrimmar from Twilight Highlands my character is half way through the terrain stone. My character can move by jumping, so I would say a small bug.

**How to reproduce:**
As Horde take portal from Twilight highlands to Orgrimmar.

**How it should work:**
My char should not fall through the ground.

**Database links:**

![WoWScrnShot_060323_235256](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/87ad8c7b-f407-4228-bcf5-37ea5c4d7e2f)
After I pass through the portal:
![WoWScrnShot_060323_235246](https://github.com/gamefreedomgit/Maelstrom/assets/133864463/e71f10f7-4f14-4756-9670-dcd2a069a098)

**Comment by Sketish** [comment]
Fixed
