### ISSUE TITLE
Quest Arelion's mistress not completable due to stage bug

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3729]
**Description:**
In TBC quest "Arelion's Mistress" you are supposed to by cenarion spirits, which allows you to talk to Viera Sunwhisper which will prompt her to follow you so you can use the scroll on her. You cannot talk to her as the quest interface is just missing/she doesn't have the quest data.

**How to reproduce:**
Attempt to talk to Viera sunwhisper with cenarion spirits in your inventory.

**How it should work:**
https://www.youtube.com/watch?v=J9vZhTPCY2g
As you can see she has a quest marker, and talking to her makes her follow you.

**Database links:**
https://www.wowhead.com/quest=9472/arelions-mistress

**Comment by UltraNix** [comment]
#3128
