### ISSUE TITLE
[Raid] BWD - Nefarian's End - Onyxia's Corpse Remains

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#3732]
**Description:**
As a precursor, I'm surprised this hasn't been reported by other players who have cleared Nefarian. From what I've seen from previous private servers and from retail footage in the relevant links down below, Onyxia's corpse is supposed to disappear once she's been killed and the lava has dissipated from the second phase.

A significant quality-of-life fix for raiders that are especially clearing Nefarian on Heroic because it makes visibility for the final phase of the encounter easier because we'd be able to see the spawning points of the Dominion portals.

**How to reproduce:**
Kill Onyxia during P1 of the encounter, kill the adds on the pillar in P2 and see that Onyxia's corpse remains there for the remainder of the fight.

**How it should work:**
After Onyxia's been killed and submerged into lava, her corpse should no longer remain.

**Relevant links:**
https://www.youtube.com/watch?v=l8TilRDcR6s&ab_channel=AnataHolyLegend
https://www.youtube.com/watch?v=3MQyH78aqT4&ab_channel=paragonWOW

**Comment by Afgann** [comment]
fixed
