### ISSUE TITLE
Small size of tamed rare pets

### ISSUE THREAD

**Issue by Blackbones29** [gamefreedomgit/Maelstrom#3733]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When taming some rare hunter pets, like for instance King Crush and IceHorn, they become way smaller than they should. Comparatively, they are quite smaller than a regular Blasted Lands crab, for instance.

**How to reproduce:**

**How it should work:**
They should be bigger after tamed, probably around double the size they area now.

**Database links:**

![King Crush tamed](https://github.com/gamefreedomgit/Maelstrom/assets/135518832/98cb1941-301a-4d86-9253-4fc7a827a43f)
![Icehorn tamed](https://github.com/gamefreedomgit/Maelstrom/assets/135518832/a91394a9-1368-4fbd-9a4f-73a16e0e1cdf)
![Normal crab tamed](https://github.com/gamefreedomgit/Maelstrom/assets/135518832/861d417f-10e3-4fae-b273-2ed082171343)

**Comment by Blackbones29** [comment]
Found a pic from Wowhead of a tamed King Crush near a tauren, for comparison.

![King Crush pic from WowHead](https://github.com/gamefreedomgit/Maelstrom/assets/135518832/e05e6974-f559-4237-8fae-17b5c605d1c1)

**Comment by UltraNix** [comment]
Fixed.
