### ISSUE TITLE
Warlock Spell "Summon Doomguard"

### ISSUE THREAD

**Issue by Warlorc** [gamefreedomgit/Maelstrom#3735]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Doomguard is getting haste bonus from the Player and Bloodlust/Timewarp, also can be affected by Bloodlust/Timewarp in addition.

**How to reproduce:**
Stack haste, get Bloodlust/Timewarp, cast Doomguard, get another Bloodlust/Timewarp for the Doomguard itself, see it do way too many casts.

**How it should work:**
Doomguard/Infernal depends on your Crit, Mastery and Spellpower at the moment of summoning, their changes have no influence on the already summoned creature.

**Database links:**
https://www.tauri-veins.tk/affliction-warlock-wow-pve-dps-rotation-cooldowns-abilities Section 6.2
On a Bh fight of 1min39s:
![image (2)](https://github.com/gamefreedomgit/Maelstrom/assets/135524585/df25c3a8-d899-486d-89a7-13dac45c2b22)

**Comment by jlldarocha** [comment]
He should benefit from haste rating from the master, but its probably double dipping on BL. 

Tauri-veins isnt a very reliable source, and the whole haste interaction was discussed on report #3673

**Comment by Warlorc** [comment]
Nope, he shouldnt benefit from haste, just spellpower at the time of popping
also he should not get Bloodlust/timewarp since it isnt a pet but a guardian.
Only buff he can get is the red buff at sinestra.
I choose tauri veins only cause it has it written there quickly, had some old changelog site that i cant find anymore since i was curious on other servers too.

**Comment by bonfax4** [comment]
Should scale with haste rating, not haste %. Guardians shouldn't not get bloodlust on themselves nor snapshot it from the owner, only pets.

**Comment by bonfax4** [comment]
If proof needed. Logs shown there too.
https://web.archive.org/web/20140716032500/http://forums.elitistjerks.com/topic/117067-warlock-mechanics-in-cataclysm/page-8  

> Doomguard now benefits from haste value, but still doesnt benefit from haste multipliers. Except DI if you cast it onto him after he has been spawned. Base cast time of 3.0 seconds on Doombolt. Doesn't benefit from Lust before/after casting doomguard

**Comment by Warlorc** [comment]
Thanks a lot, couldnt find that site after some research, might have been tripping with the haste since i never saw a change on his spellcast besides when it got the red buff on sinestra.

**Comment by UltraNix** [comment]
Fixed.
