### ISSUE TITLE
World Wide Winner Achievement doesn't work (bugged)!

### ISSUE THREAD

**Issue by VincentADK** [gamefreedomgit/Maelstrom#3737]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Screenshots: https://imgur.com/a/PTfVmzU

I make this report for **Legend**MrEvilhouse**Veev**#7968 from discord!

**Description:**
The World Wide Winner Achievement isn't working.
It doesn't register any of the different Arena locations wins, it just stays grey.

**How to reproduce:**
Try winning an arena match in all different locations and see if it will register as completed in the Achievements tab!
(Bear in mind there are only 4 arenas active atm. so normal players can't complete the whole thing without help)

**How it should work:**
When you win an arena match in any of these locations you should get a completion mark (turns green) in your Achievements tab.
And when you got all 5 it should complete the World Wide Winner Achievement!

**Database links:**
https://cata-twinhead.twinstar.cz/?achievement=699

**Comment by UltraNix** [comment]
Fixed.
