### ISSUE TITLE
Duel zone for Horde and Alliance

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3738]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello. Am I the only one who thinks that the server not enough a common duel zone for the horde and alliance?
You can even arrange a competition for voting on the choice of location and so on.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Please, make that proposition on our Discord channels.
Bugtracker is for bugs.
