### ISSUE TITLE
Satyr horns get deleted when killing multiple mobs

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3739]
**Description:**
In the quest Satyr horns in Ashenvale you need to acquire Satyr horns. If you kill multiple mobs at once and try to loot all the horns, the moment you try to loot one of the bodies and pick up one of the horns, it deletes the rest.

**How to reproduce:**
Kill multiple mobs which drop satyr horns, try to loot the bodies together, it will delete the other horns (and the rest of the items) if you click one of the horns.

**How it should work:**
You should be able to pick up each one.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=6441

**Comment by UltraNix** [comment]
Fixed.
