### ISSUE TITLE
Heirlooms do extremely high damage on feral druids

### ISSUE THREAD

**Issue by fapines** [gamefreedomgit/Maelstrom#3741]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you equip an heirloom weapon in human form then shapeshift to any other form as a feral druid, you deal more damage than max level items would like malevolence.

**How to reproduce:**
Equip staff of jordan for example in human form then go cat form and compare the damage with other lvl 85 weapons

**How it should work:**
should not be dealing as much damage

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
