### ISSUE TITLE
RDF says invalid teleporting location

### ISSUE THREAD

**Issue by fapines** [gamefreedomgit/Maelstrom#3742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sometimes when you recreate RDF group when some 1 gets kicked/leaves you cant tp back in.

**How to reproduce:**
join rdf, kill at least one boss, vote kick some one, teleport out while waiting for some 1 to join , when the queue pops up accept while jumping around so you are mid air and wont get teleported in, now you can never teleport in and if you try so it tells you "invalid teleporting location"

**How it should work:**
you should be able to teleport in even if you couldn't tp the first time.

**Database links:**

**Comment by UltraNix** [comment]
#3637
