### ISSUE TITLE
Pets pathfinding big issues

### ISSUE THREAD

**Issue by Pisell1** [gamefreedomgit/Maelstrom#3749]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Pets on certain areas on certain encounters are practically inutilizable due to weird pathfinding, here's some examples:

On Tol'vir last boss, pet is falling underground, not being able to walk on the boss arena.

On Nefarian, when you go down pet is not following you down, and if you are a warlock and you resummon it, 90% of the time it's bugging and not working, it also has some problems jumping on the pillars in P2. When Nefarian flies up in P2, pet finally follows him entering the arena, trying to go hit him. So if you are lucky, you don't have pet for all P1, and probably not even for pillars adds, and can use it only on last phase.

On Chimaeron, pets sometimes are flying up towards the ceiling of the boss arena, making them useless. 

There are probably some other issues i'm not listing, as the problem seems to be the general pathfinding.

This bug is critical, because on certain bosses certain specs are unplayable. Even if you play affliction, pet are a huge portion of your DPS.

**How to reproduce:** Play a warlock or a hunter and suffer it for yourself.

**How it should work:**

**Database links:**

**Comment by Polynomix** [comment]
Fire Elem is afk the whole fight on Al'aki

**Comment by Feathalise** [comment]
Bump, game breaking bug to not be able to use a pet as hunter BM

**Comment by UltraNix** [comment]
All should be resolved.
