### ISSUE TITLE
[Core] Druids doesn't lose the form when instantly mounted

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3750]
**Description:**
When a transformed druid (in bear, cat, travel or flight form - I didn't tested on swim form) started any event that must change him/her to "human" form (no-stance), it never happens, showing hilarious things like a bear tank on a camel in Halls of Origination or flight-formed over the raptor in the quest [Breaking the Line](https://www.wowhead.com/quest=25035/breaking-the-line) in Echo Islands.

**How to reproduce:**
Start any event in catform that mount you up without casting.

**How it should work:**
Ay mount event should clear any druid form you have. (maybe it has any exception, like the [Boulder Platform](https://www.wowhead.com/npc=45191/boulder-platform) in the quest [The Resstless Brood](https://www.wowhead.com/quest=28391/the-restless-brood), that is bugged too: you cannot mount up those in any form that is not "human form", so they are bugged reversely)

**Database links:**
https://www.wowhead.com/quest=25035/breaking-the-line
https://www.wowhead.com/quest=28391/the-restless-brood

**Photos:**

![WoWScrnShot_060523_110832](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/173e47c1-d761-4339-8f55-8613b2e9c865)

**Comment by UltraNix** [comment]
Fixed.

**Comment by Alandiel** [comment]
It's not a bug. https://www.wowhead.com/achievement=5294/straw-that-broke-the-camels-back#screenshots look at screenshots from retail wow.

**Comment by UltraNix** [comment]
Arghhhh....

**Comment by UltraNix** [comment]
Argh...

**Comment by Alandiel** [comment]
Also druid tank gets shifted out from Bear form when tanking Magmaw during Mangle.

**Comment by varjla** [comment]
Yep, and I found that Bear tanks get shifted out in throne of the tides vortex from first boss.... sorry.

**Comment by UltraNix** [comment]
Fixed.
