### ISSUE TITLE
[Achievement/item] Here, Kitty Kitty... cannot be obtainable

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3751]
**Description:**
When you get a [Temple Rat](https://www.wowhead.com/item=69724/temple-rat) to do this achievement in Zul'Gurub, when you use the rat on the cats, they do nothing, they don't eat it.

**How to reproduce:**
Get a [Temple Rat](https://www.wowhead.com/item=69724/temple-rat), use it near [Pride of Bethekk](https://www.wowhead.com/npc=52345/pride-of-bethekk). One of those must eat the rat. Doing that the combat must start automatically, but the cats never eat the rat. Maybe I need to use the rat over a cat in combat. I will test.

**How it should work:**
Any [Pride of Bethekk](https://www.wowhead.com/npc=52345/pride-of-bethekk) must eat any [Temple Rat](https://www.wowhead.com/item=69724/temple-rat), being in combat or not.

**Database links:**
https://www.wowhead.com/achievement=5765/here-kitty-kitty
https://www.wowhead.com/npc=52059/high-priestess-kilnara
https://www.wowhead.com/item=69724/temple-rat
https://www.wowhead.com/npc=52345/pride-of-bethekk

**Photo:**

![WoWScrnShot_060423_184307](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/f5974f5f-db1d-46f1-85aa-ae20027ba38e)

**Comment by UltraNix** [comment]
Just pull the cats and boss - achievement works okay.
