### ISSUE TITLE
[Core] Elevator falling damage

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3752]
**Description:**
I am getting (a bit randomly) damage when I jump over the Jellyfish elevator on the Throne of Tides. I guess the problem is harder with catform, you can tresspass the jellyfish platform and fall through, but I not tested that fully.

**How to reproduce:**
Jump over the jellyfish elevator on Throne of Tides dungeon.

**How it should work:**
You never got fall damage when jumping on a plain platform...

**Database links:**
no link

**Photo:**
![WoWScrnShot_060423_170828](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/30d2ae79-ad87-4a20-91e8-fe07fb7d6cd1)

Is not only druid: its maybe an spot in the middle of the elevator.
![WoWScrnShot_060723_013735](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/520cc0a3-f731-4a28-8d13-cab7db9ee89d)

![WoWScrnShot_060723_021859](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/acb8e780-0495-4693-a42b-a149656acce9)

**Comment by UltraNix** [comment]
Just tested and works okay.
