### ISSUE TITLE
Glubtok <The Foreman> heroic second stage

### ISSUE THREAD

**Issue by Bepemap-best** [gamefreedomgit/Maelstrom#3754]
**Description:**
Glubtok on second stage spawn blossoms around himself, that is wrong and blocked melee dps for damage him.

**How to reproduce:**
Stage Two: Arcane Power!
At 50% health, Glubtok blinks to the center of the room and stay in place. Glubtok then begins to cast Fire Blossom and Frost Blossom spells randomly around in melee zone.

**How it should work:**
Stage Two: Arcane Power!
At 50% health, Glubtok blinks to the center of the room and levitates in place. Glubtok then begins to cast Fire Blossom and Frost Blossom spells randomly throughout the room.

**Database links:**
https://youtu.be/IiVk02Ae2CA
https://youtu.be/Q9jKEicSZ2Q
https://www.wowhead.com/npc=47162/glubtok

**Comment by UltraNix** [comment]
#3354

**Comment by UltraNix** [comment]
#3342
