### ISSUE TITLE
Eng slow fall

### ISSUE THREAD

**Issue by fapines** [gamefreedomgit/Maelstrom#3756]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Using engineering cloak enchant (slow fall) exactly when u hit the ground makes you infinitely slow fall.

**How to reproduce:**
use cloak exactly when you hit the ground (i know its not a top priority but still) and you will have invisible slow fall buff for ever.

**How it should work:**
it should disappear immediately

**Database links:**

**Comment by Afgann** [comment]
fixed
