### ISSUE TITLE
Can't stun someone in flying mount

### ISSUE THREAD

**Issue by Torvahal** [gamefreedomgit/Maelstrom#3758]
**Description:**
Can't stun someone in flying mount, people come to kill players and fly, we can't do anything to control it

**How to reproduce:**
use a flying mount, fly and wait for a stun player (Hammer of Justice) for example

**Link video: **  https://cdn.discordapp.com/attachments/1096795657387376871/1115474778606800987/2023-06-06_01-26-43.mp4

**Comment by UltraNix** [comment]
Players on flying mounts on air are immuned to all CC effects. Not a bug.

**Comment by Torvahal** [comment]
We can CC a guy who has been stealing this for a long time, it was like that on retail

**Comment by UltraNix** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2999
https://www.wowhead.com/forums/topic/druid-flightform-stun-immuned-172455
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/43726683?page=1
https://gaming.stackexchange.com/questions/73623/how-can-i-force-an-enemy-to-dismount
