### ISSUE TITLE
Vengeance Passive Protection Warrior

### ISSUE THREAD

**Issue by johhny455** [gamefreedomgit/Maelstrom#3759]
https://cata-twinhead.twinstar.cz/?spell=93099

**Description:** Whenever you take dmg It should increase your attack power.

**How to reproduce:**
No matter how much damage you receive as protection warrior the passive never activates 

**How it should work:**Whenever you take dmg It should increase your attack power.

**Comment by Pornoodemon** [comment]
This should not work in pvp. Only in pve

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/3af54ccf-6226-4a97-8aef-defc504dd66e)

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/82253d78-7617-4e1d-9887-b6519a8c3532)
Tested and works okay.
