### ISSUE TITLE
[Raid][Throne of the Four Winds] Alakir 25 Man - Loot

### ISSUE THREAD

**Issue by Warlorc** [gamefreedomgit/Maelstrom#3760]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you kill Alakir on 25 man hc difficulty, the 3 Essences that should drop are as a stack of 3 on the Boss instead of 3 separate Items. You need to assign the 3 Essences to 1 Person, which will only the able to trade the "original" Item, so only 1 of the 3 Items.

**How to reproduce:**
Kill Alakir on 25man hc difficulty, open the Shard and see the 3 Items as a Stack.

**How it should work:**
The Shard should have 3 separate Items, which can be assigned individually to the people rolling on them.

**Database links:**
https://ibb.co/0jFG5WG - the Essences how they are on Whitemane right now.
https://cata-twinhead.twinstar.cz/?boss-kill=1514268

**Comment by UltraNix** [comment]
Fixed.
