### ISSUE TITLE
Balance Druid - Raid Eclipse bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3762]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When dynamically swapping difficulty nm/hc inside raids and a balance druid is in one of the eclipses, the buff will disappear but the druid will be stuck at 100% progress .

**How to reproduce:**
swap difficulty in raids while in solar eclipse

**How it should work:**
Druid should either keep the buff or reset him to default 0 state

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
