### ISSUE TITLE
Zul'Aman Jan'alai

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3765]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Radius on his Flame breath ability is larger than the animation. Makes it a little weird for melee at times if tanks are slow to move

**How to reproduce:**

**How it should work:**
https://youtu.be/-BjycB-e6yU?t=868
Enhancement shaman almost hugging the flame with no dmg taken on retail.

**Database links:**

**Comment by Warlorc** [comment]
It's not only on Jan'alai but basically every ability in dungeons or raids have a higher radius then they should have. Dark Sludge on malo, v&t circles, magmaw fire, just to name some for raids. I think its a core issue since it's happening to every spell.

**Comment by UltraNix** [comment]
Fixed.
