### ISSUE TITLE
Scholomance dungeon boss bug

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3766]
**Description:**
 In the dungeon "Scholomance", the bosses  "Vectus" and "Marduk Blackpool" (combo boss) is bugged. In many runs, they will never even trigger or be attackable, even by AOE. 

**How to reproduce:**
Run scholomance and try to attack vectus or marduk

**How it should work:**
You should be able to fight them.

**Database links:**
https://cata-twinhead.twinstar.cz/?zone=2057
https://cata-twinhead.twinstar.cz/?npc=10432
https://cata-twinhead.twinstar.cz/?npc=10433

**Comment by PanJanuszek** [comment]
To start event you have to take Dawn Gambit from Light Chapel, Eastern Plaguelands. Once you do this. Put it in the middle of the room, observe student transformation, after 15sec boss will join the fight.

fixed 10.05.2024
