### ISSUE TITLE
[PvP] [Warlock] Succubus activates a hidden autocast

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3767]
**Description:**
After using your Seduction spell once, your succubus pet will continuously cast it, making it basically useless due to wasting DR and clearing dots from your target. This seems to have been a thing from launch.

**How to reproduce:**
Cast Seuction on your target, attack to break it, pet will cast seduction again and again for no reason.

**How it should work:**
Pet shouldn't use abilities on it's own, obviously.

**Comment by Sketish** [comment]
Please record video when succubus is spaming seduction on one target when autocast is turned off

**Comment by ussj10** [comment]
New info: the reason for bug occurring is funky spell queuing. If you click the spell couple times, even if the seduction will last 8 seconds on your target, after that the pet will still try to cast it for all the clicks we initially did.

**Comment by UltraNix** [comment]
@ussj10 Can you give us a video from this bug?

**Comment by ussj10** [comment]
I couldn't replicate it at first because I kept succubus on focus. Why it affected it? I don't know. Only happened when using a macro, which I show in the video, though it doesn't make sense to me why it would prevent that.

Anyway, here I show it's "autocast" with usage of both macro and clicking it on pet bar.

https://www.youtube.com/watch?v=WfxzfS9PQm8

**Comment by UltraNix** [comment]
Fixed.
