### ISSUE TITLE
[core commands] ".xp set" command output is bugged

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3768]
**Description:**
The command .xp set gives some strange outputs.

.xp set (any number not in (0,1,2) -> XP Rate change to 3! (when the actual xp rate is 4.35x)
.xp reset -> The same message
.xp display -> shows the correct ammount of ratio

Maybe the .xp command without parameters must not show set and reset for normal players? No because you hinder the possibilities of twinks and "I want full blizzlike exp" people.

**How to reproduce:**
Use the command .xp reset or .xp set 5

**How it should work:**
Maybe that message must be corrected to the real number and maybe the .xp command help must be filtered by permissions?

**Database links:**
no links

![WoWScrnShot_060723_025827](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/ae69417e-bcbc-4e51-9e82-5065bdbea7a9)

**Comment by UltraNix** [comment]
Nothing bugged. Command .xp set/reset modifies only base xp rate.
Max xp rate set by command is 3.
