### ISSUE TITLE
[Skill]  Barkskin can't be casted in some stuns

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3769]
**Description:**
As description says, barkskin can be casted ANYTIME, ANYWHERE, in any CONDITION you have, except death or mindcontroled, obviously. (and even Mindcontroled, the controler can use it). But seems that some NPCs in Blackrock Caverns can stun you enough to stop you casting this skill. The two of those both can do the stun:
- [Twilight Torturer](https://www.wowhead.com/npc=39978/twilight-torturer)
- [Twilight Sadist](https://www.wowhead.com/npc=39980/twilight-sadist)

I just tested it: the skill causing stuns is [Inflict Pain](https://www.wowhead.com/spell=75590/inflict-pain). Really this skill must stun?
And I tested the [Twilight Torturers](https://www.wowhead.com/npc=39978/twilight-torturer) are not applying the skill (Shackles)[https://www.wowhead.com/spell=76484/shackles]... Anyone replaced some skill here, and mix a very common channeled skill (Inflict pain) with a uncommmon stun skill (Shackles)...

Additionally, the Torturers are using [Wild Thrash](https://www.wowhead.com/spell=256882/wild-thrash#see-also-other)(one of those) at least in normal mode,, and I cannot find if hey must do it in the databases. And that doesn't appear in the combat log (see photo). Even the icon of the skill doesnt matches...

**How to reproduce:**
Create a +80 druid, start battle with the sspecific NPC and wait until stunned. After that, try to use barkskin.

**How it should work:**
Barkskin must be used ALWAYS (with some obvious exceptions)

**Database links:**
https://www.wowhead.com/spell=22812/barkskin
https://www.wowhead.com/npc=39978/twilight-torturer
https://www.wowhead.com/npc=39980/twilight-sadist

https://www.wowhead.com/spell=75590/inflict-pain
https://www.wowhead.com/spell=76484/shackles

https://www.wowhead.com/spell=256882/wild-thrash#see-also-other
![WoWScrnShot_060723_124817](https://github.com/gamefreedomgit/Maelstrom/assets/6797090/ce4ca172-cb1d-4c82-a1fc-8cd5edfd058c)

**Comment by Afgann** [comment]
fixed
