### ISSUE TITLE
Using Embersilk Net, Makes Drain Life Spell, "Not Ready Yet" Until Net Cooldown Is Done.

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#3770]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I Throw Embersilk Net, I Can't Drain Life.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Provide more details, screenshots. Currently this report is invalid

**Comment by Hermeleen** [comment]
dude i am telling you, and one lock confirmed it , DRAIN LIFE AND EMBERSILK NET SHARE CD

**Comment by Hermeleen** [comment]
https://www.youtube.com/watch?v=oeImRSZO32A

**Comment by Hermeleen** [comment]
> Provide more details, screenshots. Currently this report is invalid

ask and ye shall recieve. theres your link with vid

**Comment by UltraNix** [comment]
Fixed.

**Comment by Revly** [comment]
The same thing happens with Mage Fireball
