### ISSUE TITLE
Cho'Gall - Bastion of Twilight

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3772]
Description:
Currently Corrupted Adherents corpses are despawnign during fight. Due to that only 2 corpses can be up at same time making fight a lot easier.

**How to reproduce:**
Pull Cho'Gall and kill 3 Corrupting Adherent adds

**How it should work:**
Corpses should be on the ground for whole duration of p1, when boss is pushed to 25% all corpses should despawn

**Database links:**
https://youtu.be/4a-14HHdoQI?t=288

**Comment by UltraNix** [comment]
Fixed.
