### ISSUE TITLE
[Raid] BoT - Cho'Gall's Darkened Creation Nameplates

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#3773]
**Description:**
The nameplates of Cho'Gall's Darkened Creation do not appear during the fight.

**How to reproduce:**
Enter the final phase of the fight with Cho'Gall and observe that the Darkened Creation's nameplates do not appear.
![darkened creations](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/6212b2a5-ad18-4b68-8da9-f429b3c2d174)

As of now, although they appear with red emboldened text, they are not appearing. Perhaps this is because they may be viewed as friendly in the nameplates and as such do not appear unless you "Show All Nameplates".

**How it should work:**
The nameplates should be visible when "Show Enemy Nameplates Only".

**Comment by UltraNix** [comment]
#3257

**Comment by Waroxx-QA** [comment]
#3889

**Comment by UltraNix** [comment]
Fixed.
