### ISSUE TITLE
[Dominion] UI bug during Nefarian HC 10/25 HC

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3774]
[//]: # https://imgur.com/a/UmsxfqM
[//]: # 
[//]: # https://www.wowdb.com/spells/79318-dominion

**Description:**
During the Nefarian encounter on HC mode, Nefarian will cast dominion on random players swapping your action bars with 2 new abilities. Pressing 1 will cancel Dominion and 2 stacks your buff. In the picture above you can see my action bars disappeared after transitioning into Dominion and accidentally pressing 1 too quickly, resulting me to revert back from dominion without my action bars.

**How to reproduce:**
Become mind controlled by Nefarian on HC and spam 1 or your set keybind on the first slot in your main action bar. 

**How it should work:**
Mistakenly pressing 1 rapidly as I did should cancel dominion and return my full UI intact.

**Database links:**

**Comment by UltraNix** [comment]
@Battlecryz Happened only once?

**Comment by Battlecryz** [comment]
@UltraNix No. It's still happening and I don't use any action bar addons except for Moveanything to hide the default gryphons. I have to look out for conversion on DBM and stop my rotation to make sure it doesn't happen, but sometimes it still gets me off guard.

**Comment by UltraNix** [comment]
Fixed.
