### ISSUE TITLE
Shared mounts bug. Achievements for mounts bug

### ISSUE THREAD

**Issue by dredanwow** [gamefreedomgit/Maelstrom#3775]
Achievement that counts how many mounts in total i got is bugged. On my Death Knight for example it shows i have 66 mounts and on my Druid 61. I understand that on Death Knight i have 2 mounts more because of class mounts, and that they are not shared. but one some characters gap is even bigger, on certain characters that achievement shows i have below 50 mounts. Clearly it doesn't count how many mounts across all characters i've got.
Next, on my Death Knight i bought Wooly Mamoth in Dalaran which is awarded with achievement on purchase. I've got achievement but only on the character where mount is bought, and that is my Death Knight, on other characters it says that i "already know" mount and i can not obtain achievement for that mount. 
All in all, Achievements that are granted on certain mounts are not shared well, and achievement that counts total mounts is not counting it well...

**Comment by UltraNix** [comment]
Already fixed.
