### ISSUE TITLE
The blood dk problem

### ISSUE THREAD

**Issue by Xevallus** [gamefreedomgit/Maelstrom#3778]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Xevallus** [comment]
The blood death knight bone shield effect stacks infinitely making them immortal in pvp (mostly the 80-84 bracket but sometimes 85 one too)

**Comment by Pornoodemon** [comment]
> The blood death knight bone shield effect stacks infinitely making them immortal in pvp (mostly the 80-84 bracket but sometimes 85 one too)

Am I not the only one who noticed that something was wrong with the BDK. But I still can't figure out what exactly is wrong. Can you describe in more detail what exactly is summed up and how to repeat it

**Comment by Xevallus** [comment]
I dont know if its where when you are hit it stacks or you hit them and it starts stacking however it will do this thing where after the effect if finished it starts again the next second with it doing 10% more damage reduced from it everytime and this goes on infinitely with no cap so if you tried you could have a shield thats above player health

**Comment by Pornoodemon** [comment]
Do you mean the blood shield or the bone shield?

**Comment by Xevallus** [comment]
Ok so apperantly its from death strike and it has an effect where it absorbs melee damage and it keeps inf stacking to where they remain unkillable in the 84 bracket

**Comment by UltraNix** [comment]
Blood Shield caps at DK's max health.
I see no bug here - the ability properly takes 50% of your Death Strike healing (+ mastery points). It's easy to stack to the cap (if spamming only this spell).
