### ISSUE TITLE
Graduation speech in Hyjal missing button

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3779]
**Description:**
The Quest in hyjal graduation speech is missing a speech option most of the time, making it just a spam-and-hope-for-10-minutes thing.
Sometimes relogging or spamming the desk makes it appear.

**How to reproduce:**
attempt to hold the speech

**How it should work:**
There should be 3 buttons. Not 2. https://www.youtube.com/watch?v=RSvFLcZLYIE

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=25315

**Comment by PanJanuszek** [comment]
Cannot reproduce. Checked it 20x by clicking gameobject. Always with 3 button + exit
