### ISSUE TITLE
Cooking Daily Quest

### ISSUE THREAD

**Issue by Allie2c** [gamefreedomgit/Maelstrom#3781]
**Description:**
Seems to be not spawning any Confectioner's Sugar in any of the General Stores or Inn's in Stormwind

**How to reproduce:**
Just pick up the quest and go to a General Store of Stormwind or an Inn

**How it should work:**
Able to purchase limited amount of Confectioner's Sugar from General Store vendor and be able to loot them from ground in the General Store or Inn

**Database links:**
https://www.wowhead.com/quest=26192/orphans-like-cookies-too

**Comment by Afgann** [comment]
fixed
