### ISSUE TITLE
Balance Druid 4-set eclipse bug

### ISSUE THREAD

**Issue by cataboomie** [gamefreedomgit/Maelstrom#3783]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
**Here is the evidence link:**
https://youtu.be/2c7s7Q7NasM

**Description:**
Sometimes after reaching Eclipse (Solar) "Moonfire" doesn't turn into "Sunfire". Also not getting mana regeneration.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
