### ISSUE TITLE
Completion of the quest bug "Broken Boar Figurine"

### ISSUE THREAD

**Issue by Xorny** [gamefreedomgit/Maelstrom#3785]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Completion of the quest bug

**How to reproduce:**
 It is not possible to complete the quest "Broken Boar Figurine" for Jewelers. The "Continue" button, after collecting the ingredients is pressed without any effect

**How it should work:** The task should be completed, I suppose

**Database links:**

![111](https://github.com/gamefreedomgit/Maelstrom/assets/136030776/1f87f0e3-cbeb-4913-ab29-857676529b7f)

**Comment by MorbidMike** [comment]
Do you have all the materials in your bag? If some of them are in your bank you will still be able to click the "Continue" button but will be unable to complete (as you describe).

**Comment by Xorny** [comment]
Thanks for the tip), but I made this ticket because having all the ingredients in the bag and clicking the "Continue" button, nothing happens

**Comment by UltraNix** [comment]
Fixed.
