### ISSUE TITLE
Razorgore the Untamed Fight Bugs

### ISSUE THREAD

**Issue by Imgrot** [gamefreedomgit/Maelstrom#3787]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1.- missing voice lines per egg shatered
2.- the boss's speed is nearly 60% slower than it should
3.- the ads cast an aoe heal affect the player and player pet(s) as well, and a single cast heals the player for nearly 50% of their hp
4.- the demon portals act like regular enemies
5.- the ads heal the boss more than they should after all the eggs are destroyed
6.- the debuff "Mind Exhaustion" you should get after using the orb once (where you can't use it again for a certain time) is missing and you can spam the orb

(This is what i noticed with my knowledge from previous servers, there could be more)

**How to reproduce:**

Basically, go into the fight and realize that. It should be doable solo as a hunter on other servers with the script well done, but this makes it impossible to kill here.

**How it should work:**

1.- There should be a voiceline from the boss everytime he destroys an Egg.
2.- The boss's speed should be nearly 60% higher.
3.- The ads should heal only the boss and between themselves.
4.- The Demon Portals should behave like a portal and not attack like an enemy entity, just spawn an enemy and stay in place.
5.- The ad's healing should not heal the boss and the whole pack back to full hp in a single cast every second.
6.- When you use the Orb of Domination you should get a 90 second Debuff that makes you unable to use the Orb again until it fades.

**Database links:**

https://www.wowhead.com/classic/spell=23958/mind-exhaustion

**Comment by Afgann** [comment]
fixed
