### ISSUE TITLE
Flag carrier visibility after picking up flag

### ISSUE THREAD

**Issue by knoxx06** [gamefreedomgit/Maelstrom#3788]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Enemy flag carriers in BGs such as WSG should not be immediately visible on the map.

**How to reproduce:**

Join a BG and see the enemy on the map as soon as they pick it up.

**How it should work:**

All I can find is the 2.4.0 patch notes when it was added, which says they should not appear on the map till 45 seconds after the initial pick up. Also found this video https://www.youtube.com/watch?v=0b-O94tNpwU , in the first couple minutes they lose the flag and he checks the map after ~30 seconds and the carrier is still not on the map. That's how it should work and how I've seen it work on other private servers.

**Database links:**

https://wowwiki-archive.fandom.com/wiki/Patch_2.4.0

**Comment by UltraNix** [comment]
Fixed.
