### ISSUE TITLE
Hunter pets are broken and its frustrating

### ISSUE THREAD

**Issue by cenkenator** [gamefreedomgit/Maelstrom#3792]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**   Hunter pets keep you in combat for 30 seconds if you have a dot on them, as long as the dot lasts you will remain in combat. Also their chasing range is way overextended, a hunter pet should not chase you from Horde graveyard to the tree stump that is closest to the alliance tunnel. Also keeps you in combat just while targeting you without attacking first. I ress so many times in bg and cant mount 30 sec because of combat from hunters pet having my frost fever.

**How to reproduce:**  Get a hunter and dot his pet. Or run from it in a bg to see how far it chaces.

**How it should work:** Less range... No combat for 30 seconds..

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
