### ISSUE TITLE
"The Warchief will be pleased" spawning in floor and NPCs in floor

### ISSUE THREAD

**Issue by Dispentry** [gamefreedomgit/Maelstrom#3794]
**Description:**
In the quest "The Warchief will be pleased" for the twilight highlands questline, going through the portal spawns you partially in the floor. All the NPC's are partially inside the floor too. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134758706/6103eedb-1b5d-4e30-9ed9-e8e89ee1e8b2)
I jumped here to get out.
**How to reproduce:**
Go through the portal in "The Warchief will be pleased"
**How it should work:**
You should spawn ontop of the circle, and so should the NPC's.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26798

**Comment by Sketish** [comment]
Fixed
