### ISSUE TITLE
Roots dmg threshold

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#3795]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Roots dmg threshold right now is 20%

**How to reproduce:**
Root a person and dmg them seeing how much damage they can take before the root breaks

**How it should work:**
all root effects should have a 10% dmg threshold max.

**Database links:**

**Comment by mipanka** [comment]
I will also add that the absorbed damage should also be taken into account.

**Comment by Sketish** [comment]
Please provide any source

**Comment by mipanka** [comment]
https://wowpedia.fandom.com/wiki/Frost_Nova
https://wowpedia.fandom.com/wiki/Entangling_Roots

**Comment by Sketish** [comment]
Ok aborbed dmg should count towards threshold. still need source it should be 10%

**Comment by Kenniflopper** [comment]
I tried finding it but i can't, but any player knows its 10%, same goes for hex aswell.

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3714
After that discussion the range was changed to 20%.

**Comment by Kenniflopper** [comment]
Okay, so i checked multiple other servers, it seems like everything that has a threshold is set to 10% so i guess reverting the other fix back is the real fix and i was completely wrong. @UltraNix

**Comment by mipanka** [comment]
https://youtu.be/rPXue4sObxg?t=251 here sham take ~10-15k dmg (its ~10% at max hp) and nova will break. I will find more video, but need time =)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3797#issuecomment-1592555083

**Comment by UltraNix** [comment]
Fixed.
