### ISSUE TITLE
[Mage] Living bomb and prock talents impact

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3796]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://github.com/gamefreedomgit/Maelstrom/issues/3350 bug return

screen where I did use living bomb and get prock impact
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/5e7dcbb5-532d-479c-92e9-c82547ef1dcd)

**Comment by Kenniflopper** [comment]
yeah it can happen on just applying living bomb which is bug

**Comment by UltraNix** [comment]
Fixed.
