### ISSUE TITLE
Fear dmg threshold

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3797]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
fear ability and similar have threshold 20% on max hp

**How to reproduce:**
take fear and dmg after

**How it should work:**
fear and similar ability should have ~10% on max hp target, this applies to all similar mechanics **and the absorbed damage must also be taken into account**

I cant find now 100% proof, but some comment "Now fear break's on 8000-8400 dmg or near it.
Test it some times with direct dmg and dots. Bane of agony with 760 dmg tick break fear on 11 tick. Fel flame with average dmg 2100 break fear on 4 use." from wowhead patch 4.0.3. (players have ~100k hp)

**Database links:**
https://wowpedia.fandom.com/wiki/Fear
https://wowpedia.fandom.com/wiki/Howl_of_Terror
https://wowpedia.fandom.com/wiki/Psychic_Scream

**Comment by Pornoodemon** [comment]
Where exactly is 10%?

**Comment by Pornoodemon** [comment]
At 10%, it instantly disappears, sometimes one tick of dot. Now when it was fixed to 20%, although it looks normal. Fear withstands 2-3 cast

**Comment by mipanka** [comment]
has been corrected without proof, comment, this is not what you need, but still, я работаю над этим

**Comment by mipanka** [comment]
has been corrected without proof, comment, this is not what you need, but still, I'm working on it

**Comment by Pornoodemon** [comment]
> исправлено без пруфов, комментарий, это не то, что нужно, но все же, я работаю над этим



> исправлено без доказательств, комментарий, это не то, что вам нужно, но все же, я работаю над этим

The comments talk about a damage threshold from one hit of 10% of hp at which fear can disappear, and not a maximum damage threshold of 10%.
This is why damage over time effects deal more damage in total before the fear wears off.

**Comment by Pornoodemon** [comment]
In the last patch, 40% of hp is generally indicated, and after this patch there were no changes to 5.0.4.
Read other comments from the links you provided.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/e9e92d9f-cb31-494a-8d4a-fd2f70809412)

**Comment by mipanka** [comment]
https://youtu.be/_UIiaVIwl1M?t=247  here the druid received fear and dots, after the fear was broken, after receiving 5-10% damage, judging by the video

**Comment by Pornoodemon** [comment]
visually, judging by the video, 10% seems to be true, fear breaks down after the final crits at the threshold of about 10% I think this video can be considered proof.

**Comment by Pornoodemon** [comment]
And in general, about the video proofs. There is a video where a warlock demonologist on the official server, playing on bg  performs crits on players  the hand of guldan and doombolt 100k +damage  . But this video no reason to increase damage, because there is specific data on damage with formulas, and there is no fear in terms of work, so  need to look at fear objectively  и при 15% and the wolves are full and the sheep are whole by the fact that if you put 10% again, then it will again break with 1 touch and again someone will raise this topic.
https://www.youtube.com/watch?v=J5fBl6il13o&t=422s
https://github.com/gamefreedomgit/Maelstrom/assets/133828891/aec79da5-9aff-408b-838b-7170d2e5a780

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/5f686e92-f6ce-4ed1-9542-03b6c773d989

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/8b0e66ae-aa41-4d0a-b078-afc9c658eac5

**Comment by Pornoodemon** [comment]
For example, this source states 20% of max HP and offers a link to Wowpedia where it was stated in patches. But since many years have passed, this infa has already been removed from there
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/cdd0e48f-2794-4d6d-a5ab-faf2cb927fc4)

Here is the translation of this article.

So the history of the HP threshold in Fir:
1: Initially, the fear had a threshold of 40% of the maximum hp, while even approximate caps were made for each class, let's say such a proof - http://www.mmo-champion.com/threads/...story-of -Fear: ,
2: Later, the close ones, realizing that 40% is unrealistically cool, add this thing
From direct damage, the chance of this crap proc is much higher, and as experience from pillboxes shows, it worked very very rarely.

3: At the beginning of the cataclysm, the threshold is reduced to 20% - http://www.arenajunkies.com/topic/176571-fear-and-cata/ , later it  to have been reduced to 10, in pandaria

**Comment by Pornoodemon** [comment]
And in general, in such articles it is said that the work of fear on emulators will never be the same as in the official game, since the internal mechanics of the fira is unknown to anyone. This is where a compromise needs to be found.

**Comment by Pornoodemon** [comment]
Summing up, I can say the following.
Whether there is 10% or 20%, we will never know for sure.
If we take 15%, then we don’t get any imbalance in terms of nerf or up, but this will most likely fix the strange breakdown of fear. Since now at 20% this problem is not observed

**Comment by mipanka** [comment]
I don’t understand at all why it was necessary to change so many important mechanics, even without a video. I don’t see the point in following different, largely different texts, not even from Wowhead. When there are a lot of videos from the times of the cataclysm, where you can understand 99.99% how the abilities worked. It shouldn't be "let's do it like this, or like that", but should be in line with the official cataclysm, as much as possible. Therefore, in my bug reports, I always try to find proof. I hope the developer will return the way it was, and these fixes "according to the words, only make it worse".


P.S. new video https://youtu.be/7ibtrZdtJB8?t=1081 shaman taken fear and when taken minor damage, the fear was broken.

**Comment by Pornoodemon** [comment]
> Я вообще не понимаю, зачем нужно было менять столько важных механик, даже без видео. Не вижу смысла следить за разными, во многом разными текстами, даже не с Wowhead. Когда много видео времен катаклизма, где можно на 99,99% понять, как работали способности. Это не должно быть «давайте сделаем это так или так», но должно быть в соответствии с официальным катаклизмом, насколько это возможно. Поэтому в своих отчетах об ошибках я всегда стараюсь найти доказательства. Надеюсь разработчик вернет как было, а эти исправления "по словам только хуже делают".
> 
> PS новое видео https://youtu.be/7ibtrZdtJB8?t=1081 шаман брал страх и при получении незначительного урона страх разбивался.

On our server, in a battle against a shaman, the fear will not last even a second, since he can get out of it 2-3 times in a row. In the same way with other classes in the video, you don’t know how and how they can dispel, trinket or another

**Comment by mipanka** [comment]
> > I don’t understand at all why it was necessary to change so many important mechanics, even without a video. I don’t see the point in following different, largely different texts, not even from Wowhead. When there are a lot of videos from the times of the cataclysm, where you can understand 99.99% how the abilities worked. It shouldn't be "let's do it like this, or like that", but should be in line with the official cataclysm, as much as possible. Therefore, in my bug reports, I always try to find proof. I hope the developer will return the way it was, and these fixes "according to the words, only make it worse".
> 
> On our server, in a battle against a shaman, the fear will not last even a second, since he can get out of it 2-3 times in a row. In the same way with other classes in the video, you don’t know how and how they can dispel, trinket or another Well, why parse some text, especially if there is a reason on wowpedia With the same success, let's do a Doombolt like in the video Is it informative to increase his damage without text? Let's not argue further. Let the developer do it at his own discretion
> 
>  bandicam.2023-06-11.00-48-44-544.mp4

You can make bug reports if there are any other bugs. But do not clog my report, off topic.

**Comment by UltraNix** [comment]
Changed after https://github.com/gamefreedomgit/Maelstrom/issues/3714

**Comment by mipanka** [comment]
So You will cancel the last changes or how to understand? I gave a lot of video evidence where the fear break, after receiving minor damage, which clearly does not correspond to 20% of the target's maximum health. In fact, the latest changes were made without any evidence at all, except for some changes, but Blizzard does not put all the changes into patch notes, for that matter.

**Comment by Pornoodemon** [comment]
> So You will cancel the last changes or how to understand? I gave a lot of video evidence where the fear break, after receiving minor damage, which clearly does not correspond to 20% of the target's maximum health. In fact, the latest changes were made without any evidence at all, except for some changes, but Blizzard does not put all the changes into patch notes, for that matter.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/27c3fb79-3058-4c0d-8bdb-e3f096130773)

Unfortunately the suggested links have been removed from mmo-champion
But the one who wrote this clearly referred to the proofs.
Here is the translation of this article.

So the history of the HP threshold in Fear:
1: Initially, the fear had a threshold of 40% of the maximum hp, while even approximate caps were made for each class, let's say such a proof - https://www.mmo-champion.com/threads/711283-The-History-of-Fear,
2: Later, the close ones, realizing that 40% is unrealistically cool, add this thing
From direct damage, the chance of this crap proc is much higher, and as experience from pillboxes shows, it worked very very rarely.

3: At the beginning of the cataclysm, the threshold is reduced to 20% - http://www.arenajunkies.com/topic/176571-fear-and-cata/ , later it to have been reduced to 10, in pandaria

**Comment by Pornoodemon** [comment]
Fear Roots at 20% and Hex  are fine working now . I don't see the point in breaking them down and redoing them.

**Comment by Pornoodemon** [comment]
I learned something from a foreign developer about fear.
According to him, the mechanics are roughly as follows:
  Fear has a threshold of 20%. The first 10% do not break from damage. After exceeding 10%, there is a chance of breakage from any damage, even 1 unit.
Chance to break from Dot 5%
Chance to break from direct spells 13%.
After exceeding the threshold of 20% fear breaks in any case.

**Comment by mipanka** [comment]
> I learned something from a foreign developer about fear. According to him, the mechanics are roughly as follows: Fear has a threshold of 20%. max hp. The first 10% do not break from damage. After exceeding 10%, there is a chance of breakage from any damage, even 1 unit. Chance to break from Dot 5% Chance to break from direct spells 13%. After exceeding the threshold of 20% max hp fear breaks in any case. There are no proofs, but in my opinion this is the secret mechanic of fear because fear always breaks randomly but not immediately

pls some proof, not words

**Comment by mipanka** [comment]
https://youtu.be/rPXue4sObxg?t=200 rogue take ~10k dmg only dots and fear was break

**Comment by Pornoodemon** [comment]
> Изменено после #3714

I learned something from a foreign developer about fear.
According to him, the mechanics are roughly as follows:
Fear has a threshold of 20%. max hp. The first 10% do not break from damage. After exceeding 10%, there is a chance of breakage from any damage, even 1 unit.
Chance to break from Dot 5%
Chance to break from direct spells 13%.
After exceeding the threshold of 20% max hp fear breaks in any case.
There are no proofs, but in my opinion this is the secret mechanic of fear because fear always breaks randomly but not immediately

**Comment by Pornoodemon** [comment]
> https://youtu.be/rPXue4sObxg?t=200 разбойников получают ~10к урона только дотс и страх сломается

You drown nonsense. In the battle of opponents, rsham, who can dispel fear at any second, you do not consider the possible damage from partners in his team, as well as the simple ability to dispel it on your own from any class. And many other factors.
These videos don't say anything.

**Comment by mipanka** [comment]
> > https://youtu.be/rPXue4sObxg?t=200 разбойников получают ~10к урона только дотс и страх сломается
> 
> You drown nonsense. In the battle of opponents, rsham, who can dispel fear at any second, you do not consider the possible damage from partners in his team, as well as the simple ability to dispel it on your own from any class. And many other factors. These videos don't say anything. In addition, fear breaks down at different values and its mechanics cannot be understood by referring to some video.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/c2cd6bed-0c04-4084-9e48-aeab65f2e0fa)
1 - its impact (stun) sham cant help rogue
2 - its fear

**Comment by mipanka** [comment]
> Firstly, the stun from the mage lasted a fraction of a second, and secondly and he could even dispel it himself or take damage from partners, I already told you fear breaks down at different values and its mechanics cannot be understood by referring to some video. This is the same as determining the damage thresholds from the video. I already gave you an example.
> 
>  bandicam.2023-06-11.00-48-44-544.mp4 
> You just want to nerf roots ,fear ,hex without trying to understand how it works.

during the stun, the rogue lost fear, please look at the arguments, so far there has been nothing good from you, except for words. 
**And pls if you don't have any proof, please don't go offtopic here.**

**Comment by Pornoodemon** [comment]
At the moment when the  fear disappears, rogue is not even visible on the screen 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/ee90b2ed-a840-45c6-8964-6c698ccf9771)
I'm tired of arguing with you.

**Comment by UltraNix** [comment]
Okay, guys. After reading many articles, watching many videos and getting info from other players, this is how's gonna be work:
10% of max health is the minimum damage threshold, 20% of max health is the maximum damage threshold (both might be increased by some glyphs, e.g. Glyph of Frost nova)
Till this 10%, aura cannot be break by damage.
After 10%, aura can be break by any damage (5% on DoT, 13% on direct damage).
After 20%, aura is going to be break regardless of damage.

**Comment by Pornoodemon** [comment]
> Okay, guys. After reading many articles, watching many videos and getting info from other players, this is how's gonna be work: 10% of max health is the minimum damage threshold, 20% of max health is the maximum damage threshold (both might be increased by some glyphs, e.g. Glyph of Frost nova) Till this 10%, aura cannot be break by damage. After 10%, aura can be break by any damage (5% on DoT, 13% on direct damage). After 20%, aura is going to be break regardless of damage.

This will be the best solution for this issue. Thank you.

**Comment by UltraNix** [comment]
Fixed.
