### ISSUE TITLE
[Warrior] Retaliation and Recklessness

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3798]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Retaliation and Recklessness can be uses can be used at the same time

**How to reproduce:**
use ability

**How it should work:**
Retaliation and Recklessness should have a cooldown if using one of them

video where warrior used recklessness and retaliation cd https://youtu.be/snS5lZmjq1k?t=117

**Database links:**
https://wowpedia.fandom.com/wiki/Retaliation_(Classic)
https://wowpedia.fandom.com/wiki/Recklessness

**Comment by UltraNix** [comment]
Fixed.
