### ISSUE TITLE
4.1.0 content Bwemba's Spirit

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#3799]
**How to reproduce:**
Part of zandalari quest line which players having issues both player and npc are in phase 4 but players are unable to see them most of the time for unknown reason

**How it should work:**
players should be able to see them
https://www.youtube.com/watch?v=R3I2RELORWY

**Database links:**
https://wowpedia.fandom.com/wiki/Bwemba%27s_Spirit

**Comment by Sketish** [comment]
Fixed
