### ISSUE TITLE
looting random bug

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#3800]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
while killing random mobs and even in dungeons sometimes happens , after you loot the corpse , it remains lootable but nothing inside , which makes a problem when it's a beast/animal , it cannot be skinned as the corpse is bugged

**How to reproduce:**
it happens completely random , simply just keep killing mobs and you'll encounter it

**How it should work:**
once a corpse is looted , then it should be empty "no loot"

**Database links:**

**Comment by bludmoon** [comment]
quest item spawned eather yours or someone in party seen more as a skinner

**Comment by UltraNix** [comment]
#3070
