### ISSUE TITLE
Duskwing, Oh How I Hate Thee... Quest bugged

### ISSUE THREAD

**Issue by Fentanyl1337** [gamefreedomgit/Maelstrom#3802]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Quest "Duskwing, Oh How I Hate Thee..." in the "Eastern Plaguelands" is bugged.

**How to reproduce:**
Use the "Corpseburner's Flare" in the correct spot to summon Duskwing, but after he spawns in he keeps reseting and following you, so you are unable to kill him and you are stuck in combat.

**How it should work:**
Use the "Corpseburner's Flare" in the correct spot to summon Duskwing, kill him, Loot the Quest Item and return the Quest.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27523 --- Quest
https://cata-twinhead.twinstar.cz/?npc=11897 --- Mob

**Comment by UltraNix** [comment]
#2245
