### ISSUE TITLE
[Rogue] Sinister Strike procs Revealing Strike

### ISSUE THREAD

**Issue by ssyn02** [gamefreedomgit/Maelstrom#3804]
**Description:** Sinister Strike procs Revealing Strike

**How to reproduce:** apply Revealing Strike, and at any time during its lasting effect, use Sinister Strike

**How it should work:** only finishers should proc Revealing Strike

**Database links:** [Sinister Strike](https://cata-twinhead.twinstar.cz/?spell=1752) [Revealing Strike](https://cata-twinhead.twinstar.cz/?spell=84617)

**Comment by UltraNix** [comment]
Fixed.
