### ISSUE TITLE
[PvE] [Raid] Chogall's Conversion not responding to fear effects or Tremor Totem

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3805]
**Description:**
1. Chogall's Conversion spell should be interruptible with every CC in the game but for some reason Fears are an exception.
2. Tremor Totem doesn't remove conversion cast and isn't usable while shaman is mind controlled.

**How to reproduce:**
1. Try fearing mind controlled played during Chogall fight.
2. Try using Tremor Totem while you or anyone else is mind controlled.

**How it should work:**
1. Absolutely no reason why one specific type of CC should be an exception. Priest, Warlock and Warrior should be able to fear mind controlled teammates to get them out. This exception is so random that I don't feel like it needs any proof but I stumbled upon a priest Chogall guide that confirms it.
2. Tremor Totem's description claims it to be usable while under Charm effects and remove Charm effects of all teammates within 30 yards. No luck in finding shaman guides but again, just like in Fear's case, it seems like an extremely out of pocket exclusion. The ability is said to specifically counter this type of CC, so I don't see any logic behind the mechanic as it is right now.

https://www.engadget.com/2011-04-04-spiritual-guidance-priest-healing-strategies-for-chogall-in-th.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKhulzWi9NotuwKBHMgMhYPwuWvyAljlqSMZohF8ldPTRkIDUNn96ZOlYMy-9ceLLGVk24LsayYtyWvCpocpi1uO7EudC0Zr8GIIGNXxyKmfFKxxGFpsFroKWBj_zOa_d54ftr1yEc7QkacvBXz3bo_US6Z-X1JJX6hzsqF_akK5

**Comment by Waroxx-QA** [comment]
Fears should work, tremor totem shouldn't.
Up !

**Comment by Warlorc** [comment]
why shouldnt tremor totem work?

**Comment by bonfax4** [comment]
Some mond controls are not considered charms for some reason. https://wowpedia.fandom.com/wiki/Amani%27shi_Beast_Tamer Beast tamers in ZA can't be tremored. Possible Cho'gall's behaves the same way.

**Comment by BalanCV** [comment]
Disorient effects, such as hunter's scatter shot, also do not work.

**Comment by Waroxx-QA** [comment]
All Interrupts, CC, Fears and Disorient should free MCd players on Conversion.
And conversion isn't a Charm effect so tremor totem doesn't work on it.
