### ISSUE TITLE
arcanotron no shield

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3809]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**  Arcanotron has no shield activating under 50 energy and make boss easier

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#3647
