### ISSUE TITLE
Rigid Cogwheel

### ISSUE THREAD

**Issue by Firbael** [gamefreedomgit/Maelstrom#3810]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:*Rigid Cogwheel takes bag from Toolbelt*

**How to reproduce:*Equip Elementium toolbox to bag slots Fill with stuff, Buy cogwheel without another Elementium toolbox in Inventory*

**How it should work:*"No item in inventory"*

**Database links:*https://www.wowhead.com/item=59493/rigid-cogwheel*

**Comment by UltraNix** [comment]
Fixed.
