### ISSUE TITLE
[Core][Dungeon Finder] Replacement not being teleported to Leader 

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3811]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you join a dungeon through the Dungeon Finder and you end up joining a party as a replacement (not a newly formed party) you are teleported to the dungeon entrance, as you would if you would join a newly formed party.

**How to reproduce:**
Use the Dungeon Finder and get assigned to a party as replacement (a player left/was kicked before you).

**How it should work:**
As a replacement you should always get teleported to the party leader's current location. This was introduced with the Patch 3.3 rework and first introduction of the Dungeon Finder.

**Database links:**
https://wowpedia.fandom.com/wiki/Dungeon_Finder#Looking_for_more

**Comment by UltraNix** [comment]
Fixed.
