### ISSUE TITLE
Magmaw melees tanks during mangle

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3812]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Our tanks have reported getting melee hits while grabbed inside Magmaw during mangle. He shouldn't do anything except that ability during that time.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you provide any combat log ?

**Comment by UltraNix** [comment]
No further info - closing.
