### ISSUE TITLE
Warrior executioner talent bug

### ISSUE THREAD

**Issue by meatpounder** [gamefreedomgit/Maelstrom#3814]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Then Execute hits target sometimes it does not proc or refresh Executioner ( rank 2 ) stacks for some reasons.

**How to reproduce:**
Hit any mob or training dummy with execute for a few minutes to see it 

**How it should work:**
Executioner | Rank 2 : Your Execute hits have a 100% chance to improve your melee attack speed by 5% for 9sec.
--

</body>
</html>

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=20503

**Comment by UltraNix** [comment]
@meatpounder Just tested and cannot reproduce it. Are you able to record a video with this bug?

**Comment by UltraNix** [comment]
No further info - closing.
