### ISSUE TITLE
Hunter pets disappearing

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#3815]
It would seem every time I log on my hunter lately, another one of his pets goes missing.

At one time, 2 of them were gone.

I hadn't managed to figure out the cause but something strange is definitely going on there.

**Comment by Sketish** [comment]
Can you specify what pets are missing ?

**Comment by bonfax4** [comment]
I remember seeing this happen in wotlk privates a lot where the stable spot looks empty but if you move pets around they reappear, was just a visual issue. Sounds exactly like what you're describing.

**Comment by UltraNix** [comment]
@VirtualReign Poke me on Discord.

**Comment by UltraNix** [comment]
@VirtualReign Please - retest if swapping pets is still bugged.

**Comment by VirtualReign** [comment]
Seems the problem persists. When I log on one or 2 of the pets (either equipped or stabled) are missing. They do reappear by swapping pet positions at the stables, but it doesn't seem like a purely visual bug though, since when only one pet is missing in the equipped slot space, swapping one pet into the empty slow won't produce a result (the pet will simply be moved to the empty slot and a new empty slow will be made in it's original position), but then swapping another pet into the newly made empty slot will bring back the missing pet.

**Comment by UltraNix** [comment]
@VirtualReign Poke me on Discord.

**Comment by UltraNix** [comment]
Already resolved.
