### ISSUE TITLE
Adversarial Blood quest

### ISSUE THREAD

**Issue by Zipper1996** [gamefreedomgit/Maelstrom#3816]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/quest=11885/adversarial-blood#comments
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest not working.
![WoWScrnShot_061323_034000](https://github.com/gamefreedomgit/Maelstrom/assets/133601328/bac9f7d8-d053-492c-8554-08ff9db98500)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
