### ISSUE TITLE
[ITEM,QUEST] Flawed Power Stone must not exist

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3817]
**Description:**
The item and quest [Flawed Power Stone]](https://www.wowhead.com/tbc/quest=926/flawed-power-stone) must dissapear. It is part of the quest [The Demon Seed](https://www.wowhead.com/quest=924/the-demon-seed), which has dissapeared correctly. It still can be picked on the location of the NPC: [Ak'Zeloth](https://www.wowhead.com/npc=3521/akzeloth). And I dont know if all the chain from Margoz must exist in this version. Maybe yes, as part of the network of quests that redirects the player from Durotar to the Northern Barrens...

**How to reproduce:**
Simply go to [Ak'Zeloth](https://www.wowhead.com/npc=3521/akzeloth) location and look at the stones near him in the table/basket he has at his left.

**How it should work:**
I guess those quests has been deleted (better double check it before do nothing) so they must dissapear.

**Database links:**
https://www.wowhead.com/tbc/quest=926/flawed-power-stone
https://www.wowhead.com/quest=924/the-demon-seed
https://www.wowhead.com/npc=3521/akzeloth

There is a very interesting comment in wowhead that relates the full chain of quests here:
By [Vashra](https://www.wowhead.com/tbc/user=Vashra) (3,763 – 3·39) [on 2008/03/07](https://www.wowhead.com/tbc/quest=926/flawed-power-stone#comments:id=249161) (Patch 2.3.3)

**Comment by Afgann** [comment]
fixed
