### ISSUE TITLE
Shaman Far sight bugg

### ISSUE THREAD

**Issue by MerajMahmoudifar** [gamefreedomgit/Maelstrom#3818]
https://github.com/gamefreedomgit/Maelstrom/assets/136472046/6d701a05-015b-49af-aab7-723d166cb7bf

The problem is sometimes I cannot choose farsight location and it automatically selects beneath my foot.
The next problem is in Ghostlands when I farsighted once i got to a channeling an I could attack others no more. I just could cast spells
With regards.

**Comment by UltraNix** [comment]
Cannot reproduce it.
@MerajMahmoudifar still happens?

**Comment by UltraNix** [comment]
No further info - closing.
