### ISSUE TITLE
war rage issue

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3819]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** i think war arms dont get enough rage from damage received , can u check?

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
