### ISSUE TITLE
Power Infusion/Unholy Frenzy stacking with bloodlust

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3822]
Description:
Currently both Power Infusion and Unholy Frnezy are stacking with bloodlust on players.

**How to reproduce:**
Have a mage and discipline priest in your group. If priest use PI on you and mage use time warp you will get haste from both spells

**How it should work:**
If player has bloodlust effect + power infusion, he should get haste only from bloodlust and power infusion should only provide 20% mana cost reduction.Same for unholy frenzy shouldnt stack with bloodlust

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/4bb40fda-0df5-4ecf-8108-b93927a99dfd)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/51f5af69-9d9a-42b6-b31f-04a7cbe9a517)
https://www.tauri-veins.tk/unholy-death-knight-wow-pve-dps-rotation-cooldowns-abilities
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/31625ff6-55c1-4fea-ae0d-405ad35e13f7)
https://www.wowhead.com/spell=10060/power-infusion#comments

**Comment by UltraNix** [comment]
www.mmo-champion.com/threads/955829-Preventing-Power-Infusion

**Comment by UltraNix** [comment]
Fixed.
