### ISSUE TITLE
Dragonwrath Tarecgosa Questline

### ISSUE THREAD

**Issue by staR1336** [gamefreedomgit/Maelstrom#3827]
WIP - 
Having the achievements for cleared BWD, BOT and TOTFW should enable character to accept quest from coridormi / ziradormi A legendary Engagement - does not work - tested horde side on priest that did not kill a molten lord.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a1f13efb-efb8-47af-9003-6dc68a6394d9)
![Wow-64_YBFtTjgGBT](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/ebb2bf8d-4e51-4052-811a-b82b2afafb08)
![Wow-64_VvTpin722P](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/9b65a6e6-a296-4dd1-acc7-edc44e8d13b1)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/20515370-4c03-4b80-8206-cc061236875c)

**ALLIANCE**

Triggering "your time has come" by slaying Molten Lord in the Firelands 
Quest does not appear in quest log as it should + it does not tell you anything about going to meet Coridormi (https://www.wowhead.com/npc=52408/coridormi)  in SW .
![Wow-64_wouf4RnpeV](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a8257146-a254-4bd0-a105-b03029ebf2b9)
![Wow-64_0VQdoCa8o2](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5fb60972-d585-4846-a16a-67ae0021bc0d)
![Wow-64_dSwRja3xbW](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/cdd0c912-65a9-4397-8c94-39aeb1303d51)
how it should look - 
![chrome_SWMii5WYqp](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a2b40c54-3697-437a-8500-7f1cb950c762)
![chrome_g12zZakmwf](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/3bf844c9-a710-4314-b80f-d9f3b3a1d743)

Coridormi is not spawned at all - had to complete Your Time has Come - 29453 - manually
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/01cc9834-9d1a-47aa-a4dd-6cde3ea28484)
![chrome_1nGHwq3IFc](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/3edf9506-451f-4c55-9e3d-b83225c80929)
![chrome_hbsBtEwKms](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/17b22212-b5ec-40a2-bf52-691979b604de)

A Legendary Engagement - 29132 - consequently needed to be added manually

**HORDE** 
Horde side acts basically the same, with the unique difference that Ziradormi is present in the world.
IDS for horde side quests
Your Time has Come - HORDE - 29452
A legendary engagement - horde - 29129
![Wow-64_Hv3XbXc8Dw](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/d10ea3aa-3f0a-4001-8721-a5158e0ddbb1)
![Wow-64_499GcOcTDM](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/d30a5d25-bd01-4fa6-ad6f-80f662941417)
![Wow-64_ziRYcSQoTV](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5c5d9463-f5c7-4209-8e9b-8e18f4813cfd)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/98e4b640-80f7-44ad-9e48-66e2b56c7da2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5f5b618c-67c9-4409-b28c-7a31f5e68e0c)

A Wrinkle in Time 29134 works correctly ; cinematic and dialogue proc correctly - but upon completition, there is a phasing issue, with two dragons and two of ourselves
![Wow-64_NYumyFWvOk](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e7d1f332-2d49-4f9d-9d40-5d9e44228ada)

![chrome_ynne4zcvbJ](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/455c4b95-0562-4f77-9842-f72d06c25dca)

All-Seeing Eye 29135 is picked up afterwards, asking to collect 25 Eternal Ember and 3 Sands of Time (sold by Yasmin, https://www.wowhead.com/npc=49406/yasmin,  who is currently in a sitting position. should be standing i guess. Cost of each sand is 3000g. correct. ) 
![Wow-64_Q2BNRwSNcp](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/3a9dda68-53a3-421f-8897-b2112ed44c9a)

 Eternal Ember is collected by killing bosses in Firelands. this is the first grindy part. NM Drop 0-1 each , HC is dropping 0-1-2-3. it's not a guaranteed drop as of now. grindy indeed. *NEED TO CONFIRM HOW MANY SHOULD DROP AND IF AT LEAST 1 IS GUARANTEED*
![Wow-64_5ZU3CH2atF](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/8633e6ef-1a87-42d2-944d-9203b3a0a031)
![Wow-64_H6NOj8AZX7](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/3fe42f85-3fb2-4eae-ba37-683954f6abff)

![Wow-64_inVqwS5RIq](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/71b2a215-c2ac-4cea-8e87-e9b01f51a044)

The Timeless Eye gets crafted correctly and is correctly looted upon required for the following quest - On a Wing and a Prayer 29193 
![Wow-64_SGtzPDZAGF](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/41d61862-65aa-4a22-b43c-5f83ac839b06)
![Wow-64_XTFDo0Qmtq](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/4aab8db2-ab0f-4171-aab1-1a68d8213564)
![Wow-64_Ob6RFrOXEb](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/abb961a5-f720-4606-9eeb-c7b1efffc808)

Upon making our way in Coldarra, Northrend, A cutscene correctly plays, however there is no dialogue. Quest can be completed and following one can be picked up.
https://youtu.be/saSoiWv5uCs
Through a Glass, Darkly - 29194 - Correctly puts in a phased special version of the The Nexus dungeon.
 **note** none (or very few) of these quests are actually tracked correctly, there are no markers on map and such.
![Wow-64_gHu6jQj4JA](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/f330440c-649b-47b5-9621-b38e530b4501)

** The Nexus event **
Tarecgosa is correctly found inside the nexus.
Correctly starts the event as you speak to her.
Correctly casts invisibility upon spotting the sentry guard. 
Correctly engages the guard afterwards, speaks about the security being much stronger[...] , moves on to the "flame smoke walls" (which do not do damage currently but they should) 
** note ** she reset her position to the original after engaging in a fight in this area. will walk down again.
Correctly casts freeze on us upon spotting Nexus Wardens, dialogue ensues, correctly unfreezes and we move on.
Fight with ice sentry bugged out on me, he couldn't be hit, had to manually kill it.
Correctly Walks to the Librarium, switches back to Dragon form, battle with an ice sentry follows up.  note the frozen Imprisoned Wraiths, upon freeing themselves when walked next to, aggro, but do not attack.
Correctly Moves forward, onto an ice wall before the rift - correctly begins to channel spell "Shatter Door" , an event in which we have to defend her while she opens the way - Mob "Ceredos" correctly Spawns and fights us. 

The Rift - Tarecgosa and Thyrinar begin their fight in the middle , while we travel around trying to cross to the other side on moving platforms.
We keep switching platforms to proceed forward by killing the enemy Twilight Riftweavers, until we land on the platform close to the other side, and Thyrinar correctly breaks from his fight with Tarecgosa, to come disrupt our efforts - correctly casts "Searing Breath" that correctly destroys our platform, before temporarely disappearing ; we are prompted to jump onto another platform and then continue onto another bigger moving platform with a last Twilight Riftweaver, and upon jumping on its platform we finally land. 
At this point, Tarecgosa should move closer to us, freezing and killing any enemy minion on our path, and should be waiting us to get onto the ramp to the elevated platform. Once we get closer and get to the platform, she follows us there, landing, and the boss fight with Thyrinar occurs. 
**this currently does not happen. she bugs out in the sky and does not land. The original Tarec is in the middle of the rift flying bugged, the event can be triggered by standing in the circle which is a little uneven with the ground, spawning several other tarecgosas but they all bug in the air next to the platform. **
On my First attempt, i could not even trigger this cause i must have not walked on that uneven platform. upon restarting the scripted encounter, i managed to spawn a second Tarecgosa which eventually bugged in the air next to the platform anyway and i eventually understood that platform was the trigger. none of them landed though. 

Video
https://youtu.be/6VLEGgEXwZM
https://youtu.be/Ic-9JXn87Lk

References
https://www.youtube.com/watch?v=GpmPazMWltc
https://www.youtube.com/watch?v=YcQ3PoiwNeE
https://www.youtube.com/watch?v=VCM8SKOWaq8

**Comment by staR1336** [comment]
16-06-23 update

**HORDE**

Now correctly displays the prompt to accept and opens quest log
![Wow-64_t14MK8b0iM](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/67c3f8d0-5ad1-4779-9667-089d5849ce17)
![Wow-64_28FsrjCOnX](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/af396695-96de-4d3d-919b-3193480c94b0)
![Wow-64_U8T7YYu2y1](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/021f977d-aa97-44fa-a2d8-374d197acc84)

![Wow-64_G1Xf6pp9Pn](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/87ec1de8-1e85-477e-b4a4-40d32e765a6a)
![Wow-64_txvvl3pgnd](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/7ac6fe13-0336-47b2-b39b-c28620b697ab)
At the moment,  "A Legendary Engagement" 29129 , cannot be completed. nothing happens when you click on complete while talkign to the dragon.

Upon relogging, the quest is simply Failed. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/8c95c7d1-a57c-4461-a1b6-d4e0048d3ef6)

cannot progress at this moment




**ALLIANCE**

Similarly to Horde, the prompts are now fixed & Coridormi is spawned

![Wow-64_424l6a8pSz](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/59db9402-429c-4aff-a300-87bfdc89b67b)
![Wow-64_r4Jqe5t1N1](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/51af93f5-0a33-4493-9555-b61d460bb699)
![Wow-64_WcANmvFE7e](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a97adef5-b359-48d1-b1b9-9eb8e7f4b707)

Difference to Anachronos is, you can actually complete "A Legendary Engagement" , 29132 , And continue onto accepting "A Wrinkle in Time" 
![Wow-64_9rzQoGODxu](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/b30fae85-f5c0-4497-a260-9d32ad8e1338)

![Wow-64_jtDHIKlgJ6](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/a9ee735a-b575-4334-8453-a7460c01725b)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5cef7a27-cf52-4f4d-b284-0cbf0ab78db4)

Fixed the double dragon / player phasing issue. 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/7e9fe071-7672-47ae-a69d-66ac0e3d7f0a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e5889050-bdc8-4295-acc6-8bc7d5af31f6)

Fixed Quest Log / Map Tracking Objective

![Wow-64_fP9IQShlzg](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/eeeccf05-5806-46da-827f-27b07743dc22)

Fixed Written Dialogue Cutscene AND Audio Dialogue
![Wow-64_VdG5rAsQUP](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/ac88d62f-1213-4591-86c0-d7ed9c26ffd3)
![Wow-64_ScgIhzwUzA](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e5c297d0-cf8b-4374-8534-954a7b9426ab)

**BREAKING**

In the Nexus Scenario, Tarecgosa correctly starts, and casts party invisibility correctly, and consequently breaks it when we figth the first Icebound Sentinel. however, as we go down in the first hallway downwards, at the first "combat" , Tarecgosa gets stuck and does not resume whatever she is doing.

CANNOT PROGRESS AS OF THIS MOMENT. 
However i collected more info.

*note* the cloudy flame smoke does still no dmg
![Wow-64_UTpm5Xasu6](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e662c5a1-32fc-4e11-9432-9a42c3bfacd1)
Take 1 - Normally doing the event, getting bugged at first combat
https://youtu.be/v4Cj20zcm3k


Take 2 - i .die the add in the hallway in case that's the one bugging her - Still happens in the next combat. funnily enough, the dialogue continues as if we were doing the freezing event correctly.

https://youtu.be/gAFkiTXSyek

Take 3 - I kill every add that bugged Tarecgosa so far with gm commands. The Quest goes on and i actually manage to do the part where i was stuck at before. 


https://youtu.be/xWNBsRgwn9E


*notes*
1 -  The Icebound Sentinel after the second Sentry dialogue is still bugged: he is supposed to stop the fight shortly after engaging, going up the ramp and into the Librarium, luring Tarecgosa in a trap where she gets stunned, and another Icebound Sentinel - Also the ice wall that you can see on my video as we go up the ramp, with the bugged sentinel, should not happen

reference https://www.youtube.com/watch?v=GpmPazMWltc @ 4:53

This is the reason why he becomes untargetable in my test, he tried to go upstairs, but instead of dropping the aggro, he just kept attacking me. I could not attack him as it was invalid target and i had to kill with gm command.

2 - The Imprisoned Wraiths still only activate if u go really close to them, instead of activating as you/tarecgosa approach them. they also still do not attack, just follow.

3 - At the Librarium, There's only one Icebound Sentinel on my video because of note 1, the Sentinel doesn't go up

AFTER LIBRARIUM 

Tarecgosa correctly goes to shatter the wall and we have to fight the Dog "Ceredos" . In my Test run he kind of bugged until i moved around enough for him to move and becomes unstuck/visible, and be able to be fought. 

Ice wall is correctly removed at end of Tarecgosa's cast.

THE RIFT

The rift already worked well, and it continues to do so. you can correctly jump on platforms, big or small, use the mini bubble shield, and Enemy Dragon Correctly reacts to you almost completing the rift crossing, and attacks your platform. you are still correctly prompted to jump onto another or yours will get destroyed, and u will fall and die. 
Upon completing the last platform and landing, Tarecgosa does not spawn yet to continue, but at this pointi know i have to walk to that circle to do it and she come up, Freezes everyone correctly, kills everyone, and reacts to me nearing the little ramp and the boss fight ensues with Thyrinar.
 **NOTE** at some point we are prompted to spellsteal his healing, but he did not have such healing spell on himself.
 he did however correctly cast his other spells like blast and the tracking flame.

reference https://www.youtube.com/watch?v=YcQ3PoiwNeE @ 2:00 , also 3:10 more clear

The Shield on himself  , https://cata-twinhead.twinstar.cz/?spell=99392 , needs to be dispelled asap cause of its obvious healing power. Upon Removal, we get a shield bubble around us instead, as seen in the video.

Tarecgosa also buffs us with the Essence of the Blue dragonflight.


Cutscene Ensues , Arygos is in the middle of the platform, bugged inside it. Deathwing also disappears at some point then reappears. cutscene voice dialogues are there. no Bubble Chat windows.

**Comment by staR1336** [comment]
After last update it is possible to complete the scenario and proceed further into the Firelands part

FIRELANDS PART - 

Delegation - https://cata-twinhead.twinstar.cz/?quest=29234

Players need to obtain certain items at very particular times during encounters with Firelands Bosses

All this actually works as intended - although pretty hideous to do - Players are indeed are to collect the needed items, and the criterias to convert the items into their charged state all work in all the different bosses. i collected videos of all this but since it works, i didnt upload. can if needed.

Next, Players are able to open the portal at the path of corruption - the circle of thorns. 

![Wow-64_OsZL9NZH0B](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/e274518b-f70e-4752-a42c-fc582eb9f6a3)

PLAYERS SHOULD NOTE THAT THE PROGRESS OF "OPENING THE PORTAL" WITHIN THE FIRELANDS IS SAVED  THEREFORE IT IS OKAY TO RESET OR CHANGE MODE WITHOUT BEING AFRAID OF FARMING NEW CRYSTALS AGAIN.

Inside, A few npcs are missing and/or not behaving properly , and the item in the middle isnt responding and has aura missing (and the event aswell)

How it should look like 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5081853d-302d-4ccf-b367-d42b8c0b19ef)
How it looks right now 

![Wow-64_HrRF4lb7No](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/ccdfc4c0-42a2-4874-96d8-59e8e15c9011)

After clearing the adds, the player should be able to interact with the item in the middle to claim the branch, which triggers an event where a corrupted tree protector spawns, we subdue him , and obtain the branch of nordrassil afterwards. this does not currently happen.

how it should work 

https://youtu.be/_eFHxb1Ez8w?t=695

how it looks right now 

![Wow-64_dgjgoyGBi0](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/12fd1288-a6a1-4737-88fb-adc63ffd65a0)


PLAYERS SHOULD NOTE THAT THE PROGRESS OF "OPENING THE PORTAL" WITHIN THE FIRELANDS IS SAVED  THEREFORE IT IS OKAY TO RESET OR CHANGE MODE WITHOUT BEING AFRAID OF FARMING NEW CRYSTALS AGAIN.

**Comment by staR1336** [comment]
Updated 

Scenario is fixed perfectly, just one minor thing: There are more than 4 NPCs around the branch, about 7, as im counting the lines in the video reference. rest works perfectly.

Moving on , 

COMPLETING DELEGATION

Kalecgos is met at borean tundra, and he crafts the branch of nordrassil - we currently have a slight error in the animations, the staff and the eye (the red fire ball) are getting fused into the staff fine, but currently the animation doesn't stop at the right time for the staff to appear and instead lasts quite a bit - after i wait it out, i notice that there is a slight phasing issue because you actually can't see the staff with the ? quest mark to complete unless u walk closer. You can complete the quest perfectly fine, this is minor.

reference https://youtu.be/FRWPcaUXJhk?t=15

![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5e9018ff-b6f9-4b75-892c-9723b5725d9b)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/5d19af63-4b98-4266-9e19-f24cd6be8558)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/0a70134c-2629-432b-be15-0b7b7380b785)


The following quest , Emergency Extraction, is currently bugged - The cinematic does not occur correctly, we do not fly with kalecgos, and we are stuck unable to move bugged, while we assist to the scene. Furthermore, when we regain control for the next part of the quest, Tarecgosa's body is not there.

reference https://youtu.be/FRWPcaUXJhk?t=78

how it is currently https://youtu.be/M6g3pSfOcjo

**Comment by staR1336** [comment]
Quest - EMERGENCY EXTRACTION - https://cata-twinhead.twinstar.cz/?quest=29240

Cinematic is still broken , minor changes happened but it made it worse - there is an added phasing issue when enemy npcs surround kalecgos and you don't see anything anymore; irrelevant, should all work within cinematic

reference https://youtu.be/FRWPcaUXJhk?t=78

how it is as of previous report https://youtu.be/M6g3pSfOcjo

Quest - Time Grows Short - https://cata-twinhead.twinstar.cz/?quest=29270 - discussed above, works fine

Quest - Alignement - https://cata-twinhead.twinstar.cz/?quest=29285 - 

Works almost flawlessly, everything is fine, minus a detail: we do not hear Tarecgosa's voice saying "i am with you, always" upon completition of the quest - I mention this for an immersive touch, as we do hear "i am with you" the first time we fuse with her, In the quest following Emergency Extraction, "At One" - 29269 (reference https://youtu.be/FRWPcaUXJhk?t=191 )

reference https://youtu.be/gbeeepKPhKY?t=387

Quest - Heart of Flame - https://cata-twinhead.twinstar.cz/?quest=29307

The last grind part - Players are require to absorbe Firelands Bosses essences in the object of "Smouldering Essences" , Using the On-Use Ability from the Runestaff of Nordrassil ( https://cata-twinhead.twinstar.cz/?item=71085 ) on defeated Bosses Corpses. 

Amount of Smouldering Essences absorbed varies between 9-11 on blizzlike, double on Whitemane on purpose. 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/582c6e57-2881-42c2-8316-6005404004fa)

The [Heart of Flame] (https://www.wowhead.com/item=69848/heart-of-flame) will ONLY drop if you have 250/250 Smouldering Essences.

**CRITICAL** Heart of Flame object to be looted did NOT appear at all for me - i will rerun a second test on another char, requires further inspection.


Everything afterwards seem to work fine, besides that At the moment,  Upon completition of Chain and end of RP, the City (Stormwind/Orgrimmar) Does not have the Tarec Event on where the whole city is visited by the blue dragons and a huge Tarecgosa Figure is big on the city background 


![Wow-64_iAfzcX9cko](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/021675bb-5a8a-4e65-b0a6-d4c3efcc029f)

**Comment by staR1336** [comment]
July 28th

Cutscene is Emergency Extraction is still broken, more precisely, the first one where we are flying in with kalecgos. On top of that, there is now currently a phasing bug where we will not see absolutely anything unless we move (player is sent around whole of northrend i think) 

![ezgif-3-6daae4944f](https://github.com/gamefreedomgit/Maelstrom/assets/130247490/13cb4c8c-3a21-48e1-ae2c-647903b61376)

https://youtu.be/x35ngc3sGSE

How it should be: 

https://youtu.be/FRWPcaUXJhk?t=78

**Comment by Sketish** [comment]
Moved from discord:

Timestamps here reference these two videos compared to Whitemane
Video #1: https://www.youtube.com/watch?v=3Aukn6WwP5k
Video #2: https://www.youtube.com/watch?v=JMY_Az7nz10

In general Tarecgosa doesn't not help nearly as much as the one in the video and only healed me once in the entire run. Prepare to tank/kite everything yourself.

#1) Video #1 1:52: Meeting Tarecgosa 
Bug: When you zone in sometimes Tarecgosa isn't there or shows up as "Unknown"
Fix: Relog

#2 Video #1 2:20: Tarecgosa invises you 
Bug: The invis doesn't always work
Fix: Kite and kill the 1.2 million hp mob, this progresses the script

#3 Video #1 7:08: Gauntlet after "We cannot afford this delay"!
Bug: If you take it slowly and kill things one pack at a time like guy did in this video, the event sometimes does not advance and you have to reset the dungeon
Fix: Run after Tarecgosa and aggro everything. So you have a dog pack, the zero hp wraiths and two elites to kite/kill

#4: Video #1 12:07: Break the barrier
Bug: Ceredos's Spellflame ability has no cast time and insta-kills you as soon as he walks into melee range. If you release the script gets stuck and you have to reset the dungeon
Fix: Take the death, do not release until Tarecgosa finishes channeling Shatter Barrier (60 sec?). After she is done channeling, you can release and run back (relog if you are stuck at gy) and progress the quest

#5: Video #1 13:38: Riding the Discs part 1
Bug/Feature?: I did not find any way to dodge the dragon's Shadow Nova ability. I think you are supposed to be able to click the little orbs from your platform while fighting the Riftweavers but you are currently not able to (the cogwheels are grey, they are clearly yellow in the video)
Fix: Well I could heal myself, but probably pretty rough for classes that can not.

#6 Video #2: 2:35 Riding the Discs part 2:
Bug: Tarecgosa body slamming the big drake just doesn't happen
Fix: only RP is lost

#7: Riding the Discs in general
Bug: If you wipe at all on the discs or the final boss, the dragons reset but the discs do not, 
Fix: Soft reset the dungeon. Start over 

#8: Video #2: 4:49 Final fight
Bugs: The breath/beam generally felt a lot more unforgiving than the one in the video. The guy ran through it several times and was fine, it one shot me the first time I got there (and then ofc I had to soft reset because of #7)

Fix: Don't suck - not sure though how a mage/warlock would deal with the amount of damage I was taking.

**Comment by VirtualReign** [comment]
I'd like to add, Ceredos's Spellflame does not only instantly kill in melee range, it seems to have at least twice the range intended. You can check the intended range, 3.3s cast time and the animation that is currently missing here:

[darklink428 - Through a Glass, Darkly - Part 1 (timestamp 13:17)](https://youtu.be/0qudG2YzqIk?t=797)

**Comment by UltraNix** [comment]
Fixed.
