### ISSUE TITLE
Solo Queue Timer Bug

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3828]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When you Que for solo que and you cancel the que or you got a game after that when you reque the timer is where it was left of, for example 5 mins and 30 seconds, it should be like that. cause if you are above 5 minutes the class stacking is enabled.

Please fix this.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
