### ISSUE TITLE
Dangerously Delicious - Dalaran Fishing Daily not working

### ISSUE THREAD

**Issue by Vnrs0** [gamefreedomgit/Maelstrom#3830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/quest=13834/dangerously-delicious#comments
[//]: # (cata-twinhead.twinstar.cz) https://imgur.com/a/2XNXXY7

**Description:** Quest: Dangerously Delicious is bugged - player unable to fish the required fishes 

**How to reproduce:**
take the dailie from the Dalaran Fishing lady, fly to Wintergrasp, try to fish them up and... nothing. No quest fish poppin up.

**How it should work:**
Regardless of the fishing skill it should allow you to fish the required fishes in a 2:1 ratio of normal items to quest fish (aka every 2nd try, circa)

**Database links:**

**Comment by NinacS90** [comment]
I have completed this quest several times, never had issue with it, maybe the questing fish has lower than intended drop rates but that might just be me being petty over poor rng, last time I got it was 2 days ago, it was completed within 2 minutes.

**Comment by Vnrs0** [comment]
I have fished over 40 fishes without getting a single quest fish. It's not bad rng, its not working.

**Comment by hamzaeleuch97** [comment]
You have to drop the quest and take it again.

**Comment by emirie1** [comment]
I've not had any issues with any of the Dalaran fishing dailies. At one point I thought that The Ghostfish was bugged for the same reason after fishing for like 10-15 minutes with no luck, but after skipping it for a few weeks and deciding to give it another try I was able to get the ghostfish in less than 5 minutes. To me it just sounds like bad luck.

**Comment by UltraNix** [comment]
Proc chance is 50%.
Remember to be out of group/raid.
