### ISSUE TITLE
[Quest] Just a fancy cockroach makes you in combat bug.

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3831]
**Description:**
If you kill any [Amethyst Scarab](https://www.wowhead.com/npc=46129/amethyst-scarabs-slain) you stay in combat bug.

**How to reproduce:**
Kill the npc.

**How it should work:**
They must leave the combat state after dead.

**Database links:**
https://www.wowhead.com/quest=27627/just-a-fancy-cockroach

**Comment by PanJanuszek** [comment]
After restart
