### ISSUE TITLE
[Spell] Druids cannot click on Refreshment tables from mages in any form (excepy nostance)

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3832]
**Description:**
Druids cannot click on Refreshment tables. they got an error message: "you are transformed"

**How to reproduce:**
Click on a refreshment table from mage.

**How it should work:**
Druids can click on refreshment tables transformed in bear, cat or any other form and get the food.

**Database links:**
https://www.wowhead.com/spell=43987/conjure-refreshment-table

**Comment by UltraNix** [comment]
These spells have special attribute from Blizzard (`SPELL_ATTR0_NOT_SHAPESHIFT`) that prevent from using tables while in form. Do you have any proofs it should not be like that?

**Comment by varjla** [comment]
As I told you in any other post, I am so sorry, but I come from an special server that has as very strong developpement team. Maybe they moved a lot of "annoying" things and I am "used to" that kiind of "commodities". Thanks for confirming this is blizzlike.
