### ISSUE TITLE
Jewelcrafting trinkets

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#3833]
Our lovely devs in Whitemane already fixed demon panther / king of boars droprate and they are obtainable but the other 3 became the rare one and we're back to a 3 day farm no drop.
https://cata-twinhead.twinstar.cz/?item=65897
https://cata-twinhead.twinstar.cz/?item=65894
https://cata-twinhead.twinstar.cz/?item=65896
These are the last 3 with a bugged / super low droprate, thank you.

**Comment by hamzaeleuch97** [comment]
@UltraNix Hey sir, it's been a month since I posted. The dev team fixed only 2/5 and forgot the rest so could you please finish fixing the other 3 by just increasing the droprate similar to https://www.wowhead.com/item=65895/figurine-king-of-boars ?
Thank you.

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
@UltraNix  This should only drop for people with the jewelcrafting skill. I'm getting a million of these just questing about.

**Comment by UltraNix** [comment]
Fixed.
