### ISSUE TITLE
sinestra Wrack bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3834]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** as you can see in the imge Wrack shouldnt jump on tanks , but it does

**How to reproduce:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/62810ee3-dbb2-4ee3-bb22-06f86f7d3937)

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
If there are no other people without wrack debuff it can jump on tanks

**Comment by xmrshoot** [comment]
i know but @UltraNix  can check first

**Comment by bonfax4** [comment]
> If there are no other people without wrack debuff it can jump on tanks

https://youtu.be/s-U4McocxwU not a single wrack jumped to a tank on last phase. Check @ 5 min mark. Warrior and DK tank never got a wrack after everyone had it and they kept dispelling. It just caused the last person to be dispelled to lose wrack. Video was filmed right before 4.2 according to the description so the "avoid tank" fix was in place.

**Comment by xmrshoot** [comment]
ye so its bugged here
