### ISSUE TITLE
Incorrect fix: Unholy Frenzy should stack with Bloodlust

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3835]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
gamefreedomgit/Maelstrom#3822 
While it is true that PI doesn't stack with bloodlust ever since its introduction in wrath, the situation with Unholy frenzy is different because it is still considered an enrage effect. (This has only been removed in MoP and is unknown to me whether they removed BL stacking at that time as well)
That being said, Unholy Frenzy did and should stack with bloodlust.

**How to reproduce:**

**How it should work:**
I will quote some of the links below of retail wow players during cata time:

"Unholy Frenzy will stack with other haste effects (Icy Talons, Windfury Totem, etc). Basically a slightly lesser Bloodlust/Heroism for whoever (plus it stacks with that)."

"Now to answer your questions about unholy frenzy, the following has been taken from elitist jerks:

Unholy Frenzy

A 20% melee/range haste buff with a 30 second duration and a 3 minute cooldown is rather impressive - in fact, it would be an 18% or so dps boost for us during its course. Quite good. Unfortunately, the buff is classified as an enrage, and because of that fact it's an even greater damage gain for Fury Warriors, whose mastery amplifies the effect of enrages. They would get at least 25% more out of the buff than we would. When using it on others, try to time it with Heroism or various self-buffs they have such as Death Wish."

The latter post especially infers the benefit of timing UF+Garg during BL/Hero, which everyone recommends either way, and would be illogical if they didn't stack.

**Database links:**
https://www.mmo-champion.com/threads/740429-Unholy-Frenzy
https://www.mmo-champion.com/threads/1136988-Unholy-Frenzy-on-Pet
https://wowpedia.fandom.com/wiki/Unholy_Frenzy

**Comment by UltraNix** [comment]
There is a mistake in commit message. Unholy Frenzy will stack with Bloodlust/Hero. PI won't.
