### ISSUE TITLE
mission from brann bug in chamber of origins (penetrate their defenses, and, HIT THE BEAST)

### ISSUE THREAD

**Issue by ESTELARD** [gamefreedomgit/Maelstrom#3838]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
mission from brann bug in chamber of origins (penetrate their defenses, and, HIT THE BEAST) 
when you kill the bosses you can neither complete nor deliver the missions, I am twink 84 and I always need help from a GM, to complete them, please help

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#2617
