### ISSUE TITLE
mana regen in combat is the same as not in combat 

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#3839]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Being in combat does not seem to reduce mana regen as it should do. the regen is the same in combat and not in combat

**How to reproduce:**
Take off all your items that can proc spirit or intel, spam a high mana cost spell to get to 0 mana, and watch the time it takes to get back to 40k mana. Note that down and do it again but in combat this time. It will be the same amount of time.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/9f800645-581b-48a7-9302-e887961df52f)

Here we can see that i have 3170 "mana regen" not in combat, and 2170 "combat regen". Those values are for every 5 seconds. So it should take me 92seconds to get to 40k mana in combat, but it takes me 63seconds to do so which is the time that takes to get to 40k mana while not in combat. I tested this on training dummy, in duel and on an ogre in hyjal, its the same everywhere. I did not try this in dungeon or raid or bg or arena.

**How it should work:**
When you are in combat, it should be the "combat regen" value that is used to regen mana

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
