### ISSUE TITLE
[Warlock] Imp and Succubus attack range

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3840]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Imp and succubus are are walking into melee range while performing their basic attacks. Only happens on imp if your haste makes imp exceed the 1.5sec gcd cap.

**How to reproduce:**
Equip haste to reduce imp firebolt below 1.5sec gcd and watch it slowly walk into melee between casts.
Summon succubus and watch succubus walk into melee range.

**How it should work:**
It should not walk into melee range.

https://youtu.be/J9ZCPu9uips?t=532 Imp with lust with a 1sec firebolt cast time not walking into boss melee range. Even throughout the fight you can see his imp barely moved with 1.3 sec cast times.
https://youtu.be/vdnk24v7YJg?t=260 Succubus moving and max range spamming her basic attack.

**Database links:**

**Comment by bonfax4** [comment]
@UltraNix  Succubus is doing this weird thing where she tries to run to the back of whoever you target like a normal pet when you send her in outside of her attack range. She should just find the closest position to start atacking.

**Comment by UltraNix** [comment]
Fixed.
