### ISSUE TITLE
[TBC] [Open World] Ethereum Prisons 

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3841]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ethereum Prisons are energy spheres around the [Ethereum Staging Grounds](https://wowwiki-archive.fandom.com/wiki/Ethereum_Staging_Grounds). These spheres require an [[Ethereum Prison Key]](https://wowwiki-archive.fandom.com/wiki/Ethereum_Prison_Key) which can be obtained as random drop.

**How to reproduce:**
The prison work, either spawns a hostile or a friendly npc

**How it should work:**
The part with the friendly npc is bugged as far as I can tell, I tried it several times, you should have a % chance to get either a friendly or a hostile, as to the friendly mob it should be one of the following factions and should reward you reputation:

[Cenarion Expedition] ([Rescued Cenarion Expedition Druid] - 500 rep)
[Consortium](Rescued Consortium Dealer - 500 rep)
[Keepers of Time] (Rescued Keepers of Time Custodian - 500 rep)
[Lower City] (Rescued Lower City Brute - 500 rep)
[Sporeggar] (Rescued Sporeggar Scout - 450 rep)
[Sha'tar] (Rescued Sha'tar Vindicator - 500 rep)

**Database links:**

https://wowwiki-archive.fandom.com/wiki/Ethereum_Prison
https://www.wowhead.com/tbc/item=29460/ethereum-prison-key#guides

**Comment by PanJanuszek** [comment]
fixed 08.03.2024
