### ISSUE TITLE
[Quest] Two tents quest bugged as hell if a flight-formed druid takes the quest

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3842]
**Description:**
When you get the quest Two tents, the player must be teleported to the caravan, and mounted on it. Then a cinematic starts with a conversation. The conversation is missing as reported in https://github.com/gamefreedomgit/Maelstrom/issues/2095. The problem is that if you are a druid with flight form, you get a mini cinematic, but never starts the run of the caravan. If you click on the caravan, you enter in the caravan, but nothing happens, forcing you to close the game, because you cannot dismount.

**How to reproduce:**
Be a druid on flight form. take the quest.

**How it should work:**
I explained it yet. You never must be blocked like that.

**Database links:**
https://www.wowhead.com/quest=28274/two-tents

**Comment by PanJanuszek** [comment]
After restart
