### ISSUE TITLE
[TBC] Quest Id: 11085 "Escape from Skettis"

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While the quest works there is a small issue with the npc, it has unusual spawns and pathing, instead of spawning in cages on top of the trees he spawns across the zone Skettis 
and walks back to the starting event point
![WoWScrnShot_061623_204003](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/5c1fff12-409d-46ab-af95-0ab3ad6a58d1)
This was from two days ago

**How to reproduce:**
Simply find the npc and pick up the quest

**How it should work:**
The npc is part of a daily quest for Sha'tari Skyguard faction, he spawns in a cage in several locations once picked up we begin escorting him to safely the tree where he is spawned at, following the bridge and then we get down to the ground where the quest is then marked as finished.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 11.03.2024
