### ISSUE TITLE
[Hunter][Pet Spell][Beast Mastery] Exotic Ability Burrow Attack ID:"93433"

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3844]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Burrow attack does only 300-460 damage per tick, it doesn't scale with the hunter

**How to reproduce:**
Get a hunter with BM spec and get a worm as a pet

**How it should work:**
Unfortunately I only found the following website: https://rapidfirewow.wordpress.com/page/24/ for the damage formula, but I do not know if its the right one, I think it should have similar damage (maybe?)with Froststorm Breath (id:"92380)

The pet burrows itself unground and channels the spell Burrow Attack, while channeling it cannot move or cast other pet spells, casting kill command will interrupt the channeling.
I don't if other spells modify the damage but the testing I did on a hunter on another server was the following
15k rap
mastery 12
3030-3200 per tick(crits for 4500+/-)
pet ap 7300
 ![WoWScrnShot_061623_214321](https://github.com/gamefreedomgit/Maelstrom/assets/110466305/0d2fef2c-9a39-4b8f-abed-98e511ecd212)
**Database links:**
https://cata-twinhead.twinstar.cz/?spell=93433
https://www.wowhead.com/spell=93433/burrow-attack

**Comment by bonfax4** [comment]
You can aee the formula on wowhead [changelog](https://www.wowhead.com/spell=93433/burrow-attack#changelog) @ 4.3

**Comment by NinacS90** [comment]
In years of playing and using wowhead I don't think I have ever noticed it, hahah! I can't thank you enough!
