### ISSUE TITLE
plagued rat and spider boss in stratholme bugged

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#3846]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
between market row and kings square- there is a series of 2 gates that you walk through and its a trap which normally spawns rats inside and you have to kill them in order for the gates to open... fun little mechanic except its bugged and they spawn outside the gates and if the entire party is inside you cannot continue. if youre solo you are just stuck forever unless you can somehow ranged kill them with spells.   this happens every time not just a fluke 

the spider boss nerub 'enkan that summons little scarab pets also has a high chance to summon like 20 at once which will instantly wipe the group... super annoying lol 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
