### ISSUE TITLE
[Priest] [talent] Blessed Resilience

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3847]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the priest receives a bonus from the talent when receiving any damage

**How to reproduce:**
take any damage

**How it should work:**
talent should work as described "Whenever you are victim of an attack equal to damage greater than 10% of your total health or critically hit by any non-periodic attack"

**Database links:**
https://wowpedia.fandom.com/wiki/Blessed_Resilience

**Comment by UltraNix** [comment]
Fixed.
