### ISSUE TITLE
[Rogue] Blade Flurry targetting

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3848]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blade flurry currently targets a random target within the rogue's reach.

**How to reproduce:**
Test it on 3 dummies close to each other and position closer to one, blade flurry will randomly pick a target within range.

**How it should work:**
You should be able to somewhat control where your blade flurry will land since it should always hit the closest enemy within range to the rogue in cata. 

https://www.mmo-champion.com/threads/903179-Blade-Fury?

> Previously, blade flurry would hit a random enemy inside the range. Now it targets the closest enemy, even if you have another 4 possible targets in range.
> 
> Im 98.7% sure about this.

> Exactly This. Only one target and you can control which one it's hitting by moving your character to be closest to the mob you want to hit.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=13877

**Comment by bonfax4** [comment]
Sweeping strikes most likely behaves the same way

**Comment by bonfax4** [comment]
@UltraNix Any update on this ? This would most likely also  fix those issues where bladeflurry. Still annoying when you cant controll your cleave on certain hc fights like magmaw,halfus or cho even.

**Comment by Afgann** [comment]
fixed
