### ISSUE TITLE
[Druid] Force of Nature

### ISSUE THREAD

**Issue by cataboomie** [gamefreedomgit/Maelstrom#3849]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://youtu.be/qDIyZybrCRY

**Description:**
Treants don't attack the target. They gonna follow it but won't attack. They will attack when I start attack the target.
**How to reproduce:**

**How it should work:**
Treants should start attack when I send them to attack. They should not wait for me to attack first.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
