### ISSUE TITLE
[QA Run] Firelands - 10 NM

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#3850]
**TRASH MOBS**
------------------------------------------------------------------------------
Almost everything works fine, except **Cinderweb Drone** on Beth'tilac way, they do 1.2k-1.4k hits only, should be x10 times more
Trash before Baleroc room **Flamewalker Animator** are not empowering **Unstable Magma** when they get pulled so he remains invulnerable, no way to kill it and keeps you in combat.
**Lava Wielder** ( Trash before Ragnaros ) mechanics not working
**Molten Erupter** ( Trash beforegnaros ) mechanics not working
**Molten Erupter** ( Trash before Ragnaros ) doing only 1.1-1.4k melee hits. should be x10 times more.

------------------------------------------------------------------------------
**Shannox**
------------------------------------------------------------------------------
Looks like it's working perfectly, requires proper testing.

------------------------------------------------------------------------------
**Beth'tilac**
------------------------------------------------------------------------------
**Cinderweb Spiners** are not hittable/tauntable, it says "Invalid Target", so no way to kill them and no way to go to the top. tried to kill them with .damage, they spawn the **Filament** and you can go up with it normally but the animation is slow.
**Cinderweb Spiderlings** are dumb, not moving at all if there is no Cinderweb Drone, then they all start following the new drone when it spawns.
**Bethilac** works perfetly on the top, timers and damage are fine.
**Phase Two** works perfectly.

------------------------------------------------------------------------------
**Lord Rhyolith**
------------------------------------------------------------------------------
Not moving at all. unable to kill him.
I cheated and i got it pushed to phase two, it's working perfectly.

------------------------------------------------------------------------------
**Alysrazor**
------------------------------------------------------------------------------
**Feathers** can't be picked, so unable to get speed / fly buff.
**Blazing Talon Initiate** are not spawning and keep being bugged on bird form.
**Voracious Hatchling** are not moving, so unable to eat Lava Worms.
**Alysrazor** timers and path looks great, Blasing Power and Incendiary Clouds are working perfectly, Alysra's Razor buff doesn't come on the 25th stack of Blasing Power, but it comes on the next ring after you get the 25th stack.

------------------------------------------------------------------------------
**Baleroc**
------------------------------------------------------------------------------
Shards are not spawning at all ( or they are spawning so far undermap )
Not taking damage from Wave of Torment so idk.
Unable to test without Shards.

------------------------------------------------------------------------------
**Majordomo**
------------------------------------------------------------------------------
**Cat form**  Energy works perfectly, **Leaping Flames** happens, add spawns, but the boss gets undermap sometimes after Leaping.
Unable to go further / test other forms without a proper group

------------------------------------------------------------------------------
**Ragnaros**
------------------------------------------------------------------------------
Timers are fine
**Hand of Ragnaros**'s bump is too short
All adds are going undermap / so they are not killable.
**Phase 3** Meteors are not spawning ( Due to solo testing? )

**Comment by Sketish** [comment]
HP values update

Ragnaros 10 hc
Son of Flame - should be 287,5k hp
npc id = 53801
Lava Scion -  should be 3,335 mln hp
npc id = 53817

Ragnaros 25 hc
Son of Flame - should be 1,2 mln hp
npc id = 53802
Lava Scion - should be 8,6 mln hp
npc id = 53818

**Comment by Waroxx-QA** [comment]
**UPDATE**
TRASH MOBS
----------------------------
Trash before Baleroc room **Flamewalker Animator** 1 of the four adds ( left pack ) didn't die when **Unstable Magma** exploded, second pack ( the right one ) didn't empower **Unstable Magma** so he didn't explode.

ALYSRAZOR
---------------------
Tornades are cancer, unable to dodge them even with 2 feathers speed buff. [This is how it should be](https://www.dailymotion.com/video/xknohr)

RAGNAROS
------------------------
Meteor doesn't spawn.

**Comment by Waroxx-QA** [comment]
![WoWScrnShot_062523_112118](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/a291a6cc-8aa8-44be-ad80-79ec4b8cbfd9)

**Comment by UltraNix** [comment]
```
`The 40y range with Subjugator is for Unstable Magma only, as soon as the Subjugator dies and Unstable Magma explodes, all Flamewaker Animators around him should die, and each animator alive should give him 25 energy, actually Unstable Magma's energy isn't working at all and it's stuck at 100. if you kill Animators one by one before killing Subjugator ( subjugator casts burning motivation that removes shield from Flamewaker Animator so players can dps it ) if you kill Subjugator when there is only one Animator left, the animator dies when he explode and Unstable Magma starts at 25 energy and gains energy by time. if you kill it when there is 4 animators, the four animator dies when he explode and he starts at max energy, doing his maximum damage.
```
When you enter combat, all 4 Flamewaker Animators cast Animate Magma on Unstable Magma. Every 5 sec, Unstable Magma gains stack of Superheated aura. Killing Flamewaker Animators should give no extra buff value/energy.
https://www.youtube.com/watch?v=QjUOdzdfgUY

**Comment by Waroxx-QA** [comment]
First, left pack of Flamewaker Animators are not casting Animate Magma on Unstable Magma.
![WoWScrnShot_063023_024538](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/e60eb287-9323-43a2-b6f5-5002631088e6)
Unstable Magma not killing all flamewaker animators when he explodes
![WoWScrnShot_063023_024555](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/f9229f4f-da9b-4a88-bb57-48bf30bc4dcd)

`When you enter combat, all 4 Flamewaker Animators cast Animate Magma on Unstable Magma. Every 5 sec, Unstable Magma gains stack of Superheated aura. Killing Flamewaker Animators should give no extra buff value/energy.`

Burning Motivation from Flamewaker Subjugator is targeting the closest Animator, even if he already broke his Shield, it should target the 4 Animators one by one even if he's not moving
Burning motivation tooltip says ` Increases casting speed and removes any additional defenses on target.` so Superheated stacks faster by time.

**Comment by Sketish** [comment]
https://youtu.be/gV1Wj__aGJI?t=10 Alysrazor trash before boss

**Comment by Sketish** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3970
