### ISSUE TITLE
Bug with archeology, impossible to get fragments, stucked.

### ISSUE THREAD

**Issue by avengerxxl** [gamefreedomgit/Maelstrom#3851]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a place from archeology that it's impossible to get the fragments, the indicator is pointing under this tree that its impossible to get it under. The coordinates is shown in map picture that i shared under here:
![bugarcheology2](https://github.com/gamefreedomgit/Maelstrom/assets/118686196/e8aa63bf-16cc-4d7d-8688-62825b1dcb25)
![bugarcheology1](https://github.com/gamefreedomgit/Maelstrom/assets/118686196/c6346304-ada2-41f6-94da-33295f309ad7)
![bugarcheology3](https://github.com/gamefreedomgit/Maelstrom/assets/118686196/1fc852ed-616a-4e36-bb43-92e6a91bfd8c)
![bugarcheology4](https://github.com/gamefreedomgit/Maelstrom/assets/118686196/bed69566-eb8f-40e5-8f33-b51a20636e02)

**Comment by UltraNix** [comment]
Fixed.
