### ISSUE TITLE
Quest - Guardian of the Monument - Blade's Edge Mountains

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#3853]
**Description:**
Apexis Guardian's Head does not drop after killing Apexis Guardian. Tried twice. 100% droprate acording to Twinhead.

**How to reproduce:**
Gather 35 Apexis Shards -> Give shards to the Apexis Monument -> Click colours in order -> Giant spawns -> Kill the giant and head does not drop.

**How it should work:**
Quest item should drop.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=11059

**Comment by NinacS90** [comment]
I just summoned the guardian and the head dropped, I used the spawn point at 34/51, if the other spawns are bugged while they fix try using that one

**Comment by PanJanuszek** [comment]
drop chance was 79% - > changing to 100%
