### ISSUE TITLE
[NPC] Dark Ranger Velonara missing for horder players

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3854]
**Description:**
All the quests for the NPC are bugged because Dark Ranger Velonara is not in any of the 4 instances of Scarlet Monastery in the horder version of the dungeons.

**How to reproduce:**
Go to Scarlet Monastery.

**How it should work:**
The NPC must be there. Possibly deleted in https://github.com/gamefreedomgit/Maelstrom/issues/2272
Affected quests:
"All of these quests are similar, [Into the Scarlet Monastery](https://www.wowhead.com/quest=26986) from Arathi highlands, [Moving Things Along](https://www.wowhead.com/quest=26988) from Hinterlands, and [The Right Way](https://www.wowhead.com/quest=26987) from Hinterlands, and turned in to npc [Dark Ranger Velonara](https://www.wowhead.com/npc=44660) inside one of the four wings of scarlet monastery."

**Database links:**
https://www.wowhead.com/npc=44637/dark-ranger-velonara
https://www.wowhead.com/quest=26986
https://www.wowhead.com/quest=26988
https://www.wowhead.com/quest=26987
https://www.wowhead.com/npc=44660

**Comment by PanJanuszek** [comment]
As of 05.03.2024 she is there:

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/a5335074-4383-4b79-b667-16df25002785)
