### ISSUE TITLE
[warlock] soul swap

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3859]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ability can be used twice

**How to reproduce:**
I will describe it step by step to make it clearer. You also need to have a glyph of soul swap.
- use any dots on the target
- use soul swap on target
- now use on a new target where you want to move
- now press the ability without changing the target
- the moment it hits the target, the ability will re-trigger
- after which it can be used a third time

**How it should work:**
the ability must copy once from the target

**Database links:**
https://wowpedia.fandom.com/wiki/Soul_Swap
https://wowpedia.fandom.com/wiki/Glyph_of_Soul_Swap

**Comment by UltraNix** [comment]
`now press the ability without changing the target`
But Soul Swap requires different target - how to do it?
