### ISSUE TITLE
[Rogue] Combat rogue issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3860]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I've been noticing how combat rogues underperform by a lot compared to another project so i went digging for what could be wrong.

Few issues I gathered currently : 

- Killing spree is disabling auto attacks ( Huge nerf in damage since auto attacks during killing spree should be buffed by 20% or 30% if glyphed )

- Killing spree off hand hit never procced combat potency in all the testing i did, All off hand attacks should have a chance to proc this talent. Main gauche during KS is properly proccing it. Tested with shiv ( off hand weapon attack ) spam too and no procs as well. I know in [wotlk](https://www.engadget.com/2009-06-23-patch-3-2-ptr-data-file-class-changes.html) they made combat potency proc on all off hand attacks later on wotlk after an initial nerf not to because of combat shiv builds ( they just ended up nerfing shiv ) and I'm assuming this carried over to cata. 

- [Killing spree on Magmaw ](https://www.mmo-champion.com/threads/882872-Magmaw-and-KS?highlight=killing+spree+magmaw) should put you in front of the spike if casted on non-exposed head and not kill you or throw you in the lava. Killing spree positioning needs to be checked for ragnaros as well because I'm sure it will do interesting things. From what[ i've read](https://www.mmo-champion.com/threads/1006306-Killing-spree-on-Rag?highlight=killing+spree+al%27akir) killing spree on Rag p1-3 should put you in 1 of 4 positions depending on where you're located if no adds are around. Right, left and 2 frontal positions. Never off platform or inside lava.

- Bandit's guile is working fine but has a visual issue that can be annoying if you have an addon that tracks it. Striking a 2nd target after starting a cycle (Sinister strike or revealing strike ) does not remove the buff from you, it instead just resets the guile buff timer but it is properly removing the damage increase. Ex: I'm at yellow guile on target 1, sinister strike target 2 , Yellow guile resets timer with no damage increase but restarting the cycle still. Casting 3 more strikes overwrites and puts me at green guile again.

- #3848  Blade flurry targetting

**How to reproduce:**

**How it should work:**

- Auto attacks should still go through
- Combat potency should still proc during Killing Spree
- BG buff should also be removed when a fresh cycle is starting.

Proof:

Auto attacks going through during killing spree
https://youtu.be/bvqrEgx5f4I?t=509

You see how it used to be recommended to use Fan of Knives during KS if you capped energy and to always use it at 0 energy. This was hotfixed later on and fan of knives is no longer useable during killing spree. Point being capping energy was common during killing spree and right now it is hard to cap. 
http://web.archive.org/web/20120207223821/http://elitistjerks.com/f78/t111329-combat_guide_cata_12_01_2011_a/
https://www.mmo-champion.com/threads/653933-The-change-to-Combat-Potency?highlight=shiv+combat+potency
https://www.mmo-champion.com/threads/655439-Combat-Potency-Change?highlight=Combat+potency+melee+attacks?
>"All offhand attacks" means, that it now includes Shiv and Killing Spree's offhand attacks.

https://cata-twinhead.twinstar.cz/?issue=6849
Twinstar discussion about potency+killingspree

Killing spree ragnaros left side location
https://www.youtube.com/watch?v=aQLtM_6DaBA&t=47s

Killing spree magmaw non exposed head
https://youtu.be/bRwAjmivm8Q?t=20

Moment he switches from head to add and casts a sinister strike bandit's guile gets removed (new cycle)
https://youtu.be/ddhQFf33l9o?t=246

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=51690
https://cata-twinhead.twinstar.cz/?spell=84654

**Comment by bonfax4** [comment]
Using /startattack macro on killing spree macro fixes the auto attack issue btw.

**Comment by bonfax4** [comment]
You're right my bad. Tested it again now and see 4'ish with a 1.4 sec dagger and SND. Could have sworn when I tested earlier i couldn't see more than 2.

**Comment by UltraNix** [comment]
And you are testing only on one target? No other procs/abilities?

**Comment by bonfax4** [comment]
one target dummy yup. I'm aware autos dont travel when it jumps around and it only autos main target. Seen it in retail videos. Either wayyou can tell  just by looking at auto atacks before and into killing spree i that some sort of reset is happening.

**Comment by bonfax4** [comment]
I dunno, can't replicate it with 100% accuracy lol. Sometimes the autos go through fine, sometimes they don't. Could just be a target dummy issue.

**Comment by UltraNix** [comment]
Fixed.
