### ISSUE TITLE
fishing pools

### ISSUE THREAD

**Issue by bludmoon** [gamefreedomgit/Maelstrom#3861]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
fishing pool not fishable water too shallow 

**How to reproduce:**

uldum is 1 spot  on lake vir'naal ,outside ramkahen,
**How it should work:**
easy fix spawn pool flag  location always fishable 

**Database links:**

**Comment by Sketish** [comment]
Please provide screenshor or coordinations

**Comment by Afgann** [comment]
fixed
