### ISSUE TITLE
Archeology Digsite Bug

### ISSUE THREAD

**Issue by Glitchyeeq** [gamefreedomgit/Maelstrom#3864]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/137152225/f47fc628-f771-4547-9442-24d458f3e56c)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/137152225/0c347a86-24a3-422a-aaa1-556c49346ed8)
Dragonblight 26,50 and Zul'Drak  73,58.
On both these sites, surveying just makes me go around in circles with no possibility of finding fragments. 
Due to this reason I am also unable to get new dig sites and am stuck with these until I finish clearing these sites.

**Comment by UltraNix** [comment]
Just remember that in Azjol Nerub area you have different floor levels.

**Comment by UltraNix** [comment]
Fixed.
