### ISSUE TITLE
Fortunate misunderstandings quest bugged 12570

### ISSUE THREAD

**Issue by Kroetenmann** [gamefreedomgit/Maelstrom#3867]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fortunate misunderstandings quest bugged

I know this is low priority but its part of the green proto drake questchain so some ppl will ask for it.

**How to reproduce:**
the quest wont be marked as complete after the escort of the npc if you are not in proximity it seems,
after abandoning, waiting for npc respawn and retaking it I was able to finish.

**How it should work:**
you finish the quest once the escort npc despawns

**Database links:**
https://www.wowhead.com/quest=12570/fortunate-misunderstandings

**Comment by Kroetenmann** [comment]
The Npc name is Injured Rainspeaker Oracle

**Comment by PanJanuszek** [comment]
fixed 27.03.2024
