### ISSUE TITLE
Fortunate Misunderstandings quest bugged 12576

### ISSUE THREAD

**Issue by Kroetenmann** [gamefreedomgit/Maelstrom#3868]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fortunate Misunderstandings quest bugged

the frenzyheart npcs are not hostile / attackable.
probably has something to do with being friendly with the frenzyheart at the start of the chain,
I cannot uncheck and check at war again at that point, since i am hatred already

**How to reproduce:**

**How it should work:**
being able to attack the Npcs

**Database links:**
https://www.wowhead.com/quest=12576/forced-hand

**Comment by Sketish** [comment]
Please change name of the quest in the title for correct one
