### ISSUE TITLE
Magma totem not revealing hunter camouflage

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3869]
https://cata-twinhead.twinstar.cz/?spell=8187)
 https://imgur.com/a/uzoWWWY

**Description:**
In the recording above, I tested magma totem against all stealth classes. It revealed them out of stealth correctly except for hunters with camouflage. I couldn't find any evidence from retail proving it should work like this, but it doesn't makes sense that it wouldn't reveal them.

**How to reproduce:**
Place a Magma totem next to a Camouflaged hunter. 

**How it should work:**
Magma Totem with 5 health at the feet of the caster for 60 sec that causes 815 Fire damage to creatures within 8 yards every 2 seconds. 

**Database links:**

**Comment by Sketish** [comment]
Please try to provide any source from retail videos

**Comment by Hermeleen** [comment]
idk really if it should reveal him, i think of camo as smoke bomb, if you outside of it, there is a line of sight effect.

**Comment by Battlecryz** [comment]
@Hermeleen, To the player it is kind of like that, but to the Magma Totem, it's different. Something like a Searing Totem requires a target to shoot fireballs, but Magma Totem is basically an AoE on the ground, if you step near it, it'll damage you no matter what.

**Comment by Hermeleen** [comment]
@Battlecryz  yes aoe. But have a rogue smoke-bomb himself and restealth, and you put magma outside of smokebomb. If it gets him out, then it should also get out camo, if not, then there's no issue with hunters.

**Comment by bonfax4** [comment]
Aoe's casted outside of smokebomb still work iirc, you dont need to be inside. Dont see why magma totem would be any different. 

Any aoe should break it according to this [comment](https://web.archive.org/web/20121028120324mp_/http://www.wowhead.com/spell=51753#comments).

> Everything you would ever want to know about this ability:
> 
> -Works on you & your pet.
> -Can't be used while in combat, but feigning to drop combat & then casting camo immediately works.
> -While standing still, you are stealthed, meaning no one outside your party can see you until they're very close.
> -While moving you are, well, camouflaged. People can see you but can't attack you with anything except melee attacks.
> -~~Stealthers can't use any of their stealth-only abilities on you; they have to pop out of stealth to attack you.~~
> -Any damage taken by you, including AOE abilities like Flamestrike, Frost Nova, etc, breaks your camouflage.
> -Your pet taking damage, but not you, does NOT break your camouflage.
> -Camo is broken when arena games start; you have to use camo AFTER the gates open.
> -Laying traps, swapping aspects, using mend pet, reviving your pet, using pet abilities (not attacks), & eating food do NOT break camo.
> -Using any attack, dismissing pets & calling new pets DOES break camo.
> -Sending your pet to attack breaks camo immediately, even before your pet engages.
> 
> Basically, this is an upgraded version of stealth with a 1-minute cooldown. In PvE, you can use it to get into position before the fight and start DPS as soon as the tank pulls. In PvP, you can use it to start off any fight any way you want. Because rogues & ferals can't use any openers on you, you no longer need to camp flare @ the start of an arena match; you can use the flare offensively to try and knock them out while you waltz over to the other team's healer, unable to be attacked until you open.
> 
> I think this is a really underrated ability. While it's not something you can use all the time, and it definitely doesn't make hunters a stealth class, you can still use it to get a unique advantage over other players. Plus it means you don't have to go night elf to be invisible, which is sweet, because night elves suck.
> 
> Edit:
> 
> AND OF COURSE, THE ANSWER TO THE QUESTION EVERYONE WAS WONDERING:
> 
> Casting Aimed Shot doesn't break camo.
> 
> Yeah, that means you can get off an aimed, use rapid fire, and start charging up your next one, all from stealth.
> 
> Edit2: As of 4.1, stealthers can use their openers on you while camo'd. I'm disappointed with the change. That was one of the things that made Camo unique.]

Bit pointless tho because if the hunter is close enough for you to magma, mellee'ing would be quicker to pop him out reallistically. Unless the hunter is blind and walks into one lol.

**Comment by Hermeleen** [comment]
i would really like to see code for that.

**Comment by bonfax4** [comment]
Hmm see what happens also with priest mindsear and/or warlock hellfire. They're all non ground periodic effects (dots). Might be ignoring them all.

**Comment by bonfax4** [comment]
K here's proof that "aoe" totems have an issue vs camouflage, not just magma. This includes Earthbind totem.

Retail video earthbind totemseems to hit the hunter before he leaves camou.
https://youtu.be/wTgwuSeS_Qc?t=445 Slow the video down a bit, shaman pops earthbind right as the duel starts and it hits hunter through camouflage. Currently on the server neither magma or earthbind totem hit the hunter in camou.

**Comment by bonfax4** [comment]
https://youtu.be/ysnVwIwKPB8?t=120 Earthbind totem outside smoke bomb roots rogue inside smokebomb ( obscured like camouflage ).

**Comment by UltraNix** [comment]
Fixed.
