### ISSUE TITLE
Warlock pets are bugged

### ISSUE THREAD

**Issue by parcoy** [gamefreedomgit/Maelstrom#3873]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock's pets are bug, the action bar with all its abilities and controls doesnt show, you cant control your pet. 

**How to reproduce:**

**How it should work:**
as soon as you summon one demon a secondary actionbar must appear so you can control it's actions and spells. 

**Database links:**

**Comment by Pornoodemon** [comment]
This is how it happens up to level 10. And then you learn demon control.
