### ISSUE TITLE
Unable to Skull Bash (Cat form and Bear Form) on phase 2 adds on Nefarian

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Maelstrom#3876]
**Description:**
During phase 2 of nefarian in BWD, you can not skull bash the adds to kick the nova

**How to reproduce:**
Play Feral on Nefarian and try to skull bash the adds

**How it should work:**
They should be kickable and skull bash should go off

**Comment by Stega23** [comment]
Theres a temporary fix for that, you can go on "Top right platform"(looking from the place where you start the fight), you can make it work there

**Comment by UltraNix** [comment]
@Dova14 @Stega23 What error is shown in that case?

**Comment by Dova14** [comment]
I haven't been in BWD since i made the bug report (since fully saved) but my experience outside of what hes talking about it is that:

You Cant skull bash at all, the leap effect doesnt work nor does the interrupt.  But you can Feral Leap them ignoring minimum range.  So you still have to be within the max range but you can sit as close as you want to the adds and you can still leap them.  It might be whats causing feral leap to work that is causing Skull Bash to not work

**Comment by UltraNix** [comment]
Fixed.
