### ISSUE TITLE
Shadow cloack doesnt give you magic inmune

### ISSUE THREAD

**Issue by Misxfits** [gamefreedomgit/Maelstrom#3877]
Shadow cloack dont work like the description: 
"Provides a moment of magic immunity, instantly removing all harmful spell effects. The cloak lingers, causing you to resist harmful spells for 5 sec."

- Dispell all magic debuffs at use: Yes
- Make to you inmune to dots and magic: No

![WoWScrnShot_061823_142804](https://github.com/gamefreedomgit/Maelstrom/assets/132839352/d8cbfa67-c534-45f6-8a67-d2c6a181098f)

**Comment by Carapilsx** [comment]
This is blizzlike. Please you've already reported this once. 

After you used cloacked you can still get pala seal DoT, same for Dk Dot's and serpent sting from hunters.

Close this

**Comment by mipanka** [comment]
There is no error here, Cloak of Shadows does not provide full protection, cloak of shadows reduces chance to hit - 
Apply Aura: Mod Attacker Spell Hit Chance - % (126),
in the first second only immunity works.
