### ISSUE TITLE
Terborus, rare mob in Deepholm

### ISSUE THREAD

**Issue by Shrutasena** [gamefreedomgit/Maelstrom#3880]
Rare mob [Terborus](https://www.wowhead.com/npc=50060/terborus) in Deepholm spawn under texture

**How to reproduce:**
1) go to Deepholm, to [Terborus](https://www.wowhead.com/npc=50060/terborus) (see spawn point)
2)/tar Terborus
3) Mark him
![WoWScrnShot_062223_212509](https://github.com/gamefreedomgit/Maelstrom/assets/137438732/9a9aadc7-7246-4bf1-a896-40d64c3b73d0)

**How it should work:**
he spawns above the surface

**Comment by UltraNix** [comment]
Should be okay now.
