### ISSUE TITLE
Combat issues at the training dummies 

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3881]
![WoWScrnShot_021424_130732](https://github.com/gamefreedomgit/Maelstrom/assets/133050300/523f2d55-33fb-45a8-ab07-d92f2de814e8)

**Description:**
Testing out differences in itemization/trinket is very tedious to do so at the training dummies since for some reason it's keeps breaking combat for ranged DPS only. In the image you will notice how a short session at the dummies is broken into various 2 or 3 second fragments and makes the dummies pretty useless for ranged. 

**How to reproduce:**
Use any potion while in combat at the training dummies and you will notice that they become available again.

**How it should work:**
You should remain in combat while attacking the training dummies.

**Database links:**

**Comment by Battlecryz** [comment]
@UltraNix @Sketish Can you bump this up in priority? With the fresh server rolling out soon, you'll be getting an influx of players coming in testing out classes/gear for Cataclysm Classic.

**Comment by UltraNix** [comment]
@Battlecryz Can you record that bug, so we can see your rotation?

**Comment by Battlecryz** [comment]
> @Battlecryz Can you record that bug, so we can see your rotation? DoTs do not refresh combat on dummies.

https://www.youtube.com/watch?v=RYAGlGcIadg

Yeah, it seems to happen while I'm channeling Mind Flay as a filler

**Comment by UltraNix** [comment]
Okay - will be fixed for Mind Flay.
