### ISSUE TITLE
Dispersion doesn't reduce damage

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#3882]
![WoWScrnShot_062323_102517](https://github.com/gamefreedomgit/Maelstrom/assets/51279816/671c7075-646c-41fc-9c5b-52743040f9ad)
![WoWScrnShot_062323_102247](https://github.com/gamefreedomgit/Maelstrom/assets/51279816/e0a12d57-5d27-46bf-8bff-68dfa2f44442)
No discription needed, it doesn't reduce direct damage  only dots and it happened more than 10 times in 3 bgs.

**Comment by hamzaeleuch97** [comment]
Also I'd like to add that with this bug priest is just impossible to play.

**Comment by Sketish** [comment]
Well please provide screenshots of player hitting you with same ability before and after using dispersion

**Comment by hamzaeleuch97** [comment]
So you're telling me he hit me for 150k before dispersion ? No comment.

**Comment by Sketish** [comment]
I cant see any 150k hit

**Comment by hamzaeleuch97** [comment]
@Sketish Because it's not reducing any damage and 15k is just his normal damage.

**Comment by Waroxx-QA** [comment]
Just tested it, it's working normally, i think you got that 17k when Dispersion faded
Not a bug.
