### ISSUE TITLE
Hunter pet bug in Lost City of Tol'Vir dungeon

### ISSUE THREAD

**Issue by BroWzeff** [gamefreedomgit/Maelstrom#3884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When u fight Siamat in the Lost City of Tol'Vir dungeon as a hunter, ur pet disappears when u get on top of the building.

**How to reproduce:**
Use the "tornado" (or whatever it is that gets u on top of the building in order to fight the boss and the pet bugs out. I tried to dismiss and call a new one and it stays next to me but if i command it to attack it bugs again.

**How it should work:**
Pet should stay with u.

**Database links:**
-

**Comment by Amirhellscream** [comment]
I had this bug today i report it perhaps fix it soon

**Comment by UltraNix** [comment]
#2551
