### ISSUE TITLE
Bug with quest in Howling Fjord "Warning: Some Assembly Required"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3885]
**Description:**
Hi there is a bug in quest in howling fjord called "Warning: Some Assembly Required" where you go as abomination and need to explode vrykuls but you don't get credit for exploding them.

**How to reproduce:**
Just do Quest

**How it should work:**
 You should get credit for mobs when abomination explodes 

**Database links:**

**Comment by Aurorre** [comment]
5 months later busy here for lore master, This quest is still not working with giving the credit. ( 3 November 2023 )

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
