### ISSUE TITLE
bugged queue  RDF

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#3886]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
okey , so it happens randomly but sometimes i'm in queue for dungeons and it shows up "i'm playing not afk" for half a second then kicks me out  , i've attached a picture , if you'd look at the chat , it's a proof i was not afk , doing my quests just like any other time , and this happened , and it's not the first time , it happened so many times , i got tired of it , i had to make a post about it here .
it's like it shows up at the last second , as if it's display bugged or something.

**How to reproduce:**
it happens randomly , it'll only happen when queueing for dungeons

**How it should work:**
this shouldn't happen .

**Database links:**
https://imgur.com/51AetGa

**Comment by UltraNix** [comment]
Fixed.
