### ISSUE TITLE
Hunter pet disappeared and is no longer summonable

### ISSUE THREAD

**Issue by zalere** [gamefreedomgit/Maelstrom#3887]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pet is no longer available or summonable after doing quest "The Greater of Two Evils" https://www.wowhead.com/quest=25310/the-greater-of-two-evils attempted revival but pet is completely gone from "Call Pet" options and re-log hasn't worked

**How to reproduce:**
Not 100%, I had pet out during the quest and while ascended and killing the pit lord. Once I removed the ascended buff pet was gone and not revivable as it was still alive

**How it should work:**
Pet should not be permanently removed during a quest

**Database links:**

**Comment by UltraNix** [comment]
@zalere @Hellsz As I cant reproduce it, a video would be helpful.

**Comment by UltraNix** [comment]
No further info - closing.
