### ISSUE TITLE
Bugged Quest in Grizzly Hills "The Horse Hollerer"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3888]
**Description:**
Quest in Grizzly Hills called "The Horse Hollerer" where you supossed to throw bombs at horses is bugged where you don't get credit for Throwing bombs at horses (you are just throwing bombs at them and nothing happens)

**How to reproduce:**

**How it should work:**
Horses should run away after getting hit by bombs

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
