### ISSUE TITLE
absorbed damage and break cc

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3890]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
absorbed damage does not count towards destruction threshold, for fear, frost nova and similar effects

**How to reproduce:**
get CC with shield and take dmg

**How it should work:**

absorbed damage should be calculated for the knockdown threshold

**Database links:**

![WoWScrnShot_062423_214526](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/f8a32f3a-39fa-4342-b3df-40f38664ed83)

**Comment by Sketish** [comment]
Please provide any proofs

**Comment by mipanka** [comment]
on screen pala got 33355 dmg and nova doesnt broken

**Comment by mipanka** [comment]
https://wowpedia.fandom.com/wiki/Patch_4.3.0
"Spells which have an effect broken by taking damage past a threshold (Spell nature stranglevines [[Entangling Roots]](https://wowpedia.fandom.com/wiki/Entangling_Roots), Spell shadow possession [[Fear]](https://wowpedia.fandom.com/wiki/Fear), Spell frost frostnova [[Frost Nova]](https://wowpedia.fandom.com/wiki/Frost_Nova), etc.) now count damage that was prevented by damage absorbs or other damage reducing effects."

**Comment by Renehadox** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3083

Isnt this fixed already?
Or only for Sacred Shield talent??

**Comment by UltraNix** [comment]
@Renehadox It was fix for some auras only (including Sacred Shield)
This one will include all breakable CC auras.

**Comment by Renehadox** [comment]
> @Renehadox It was fix for some auras only (including Sacred Shield) This one will include all breakable CC auras.

Alright, perfect!

I cant wait for this fix tbh...

**Comment by UltraNix** [comment]
Fixed.
