### ISSUE TITLE
[paladin][druid][talent] Aura Mastery and Cyclone

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3891]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if you use the cyclone and master aura in the right order, you can get the eternal aura mastery effect

**How to reproduce:**
describe point by point
- turn on the aura
- use paladin aura mastery
- use druid cyclone
- an important condition for the aura mastery effect to end before the cyclone ends

**How it should work:**
there should be no permanent master aura effect

**Database links:**
https://wowpedia.fandom.com/wiki/Aura_Mastery
https://wowpedia.fandom.com/wiki/Cyclone

https://wowpedia.fandom.com/wiki/Concentration_Aura
https://wowpedia.fandom.com/wiki/Crusader_Aura
https://wowpedia.fandom.com/wiki/Devotion_Aura
https://wowpedia.fandom.com/wiki/Retribution_Aura

**Comment by UltraNix** [comment]
@mipanka Cannot reproduce the way you described.
While being cycloned, Aura Mastery effect (aura) disappears and after the cycloned is over, the aura (retri aura in my case) is back and nothing more.

**Comment by mipanka** [comment]
have You tried with other auras? Bcs I try only [Concentration_Aura, [Devotion_Aura](https://wowpedia.fandom.com/wiki/Devotion_Aura)](https://wowpedia.fandom.com/wiki/Concentration_Aura) https://wowpedia.fandom.com/wiki/Devotion_Aura and https://wowpedia.fandom.com/wiki/Resistance_Aura

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/0431a341-6c55-4fbc-905a-b3b800d56564)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/858c75d3-0b19-48a9-b11b-50cdd2aadd2a)

**Comment by UltraNix** [comment]
??
With Aura Mastery you have 122 and without 244?

**Comment by mipanka** [comment]
aura without "aura mastery" gives 122, during aura mastery gives 244 (+100%)

**Comment by mipanka** [comment]
I hope u undestend about Im talking

**Comment by UltraNix** [comment]
Yes, but it's just a visual (aura tooltip). I will fix it.

**Comment by mipanka** [comment]
in pvp hpal use https://wowpedia.fandom.com/wiki/Concentration_Aura after cyclone hpal have immune for kick/silence, mb better test on this

**Comment by UltraNix** [comment]
Okay.

**Comment by UltraNix** [comment]
Fixed.

**Comment by VincentADK** [comment]
@UltraNix sorry for the ping. 
It seems like this bug resurfaced again, it seems to happen within cc. If you were to aura mastery before getting cced
and ur aura mastery ends within that same cc, there seems to be a chance it stays on the whole game.

Here is another example from Playson: "lets say you are a holy paladin and you play with a shadow priest vs a druid feral lets say and hpala ..... if you have concentration aura active as a hpala and you use aura mastery and the enemy druid is cloning you while aura mastery is active ...after the aura mastery it can bug out and then you are permanent imune to silences / intrerupts until you relog"

I am not sure if this helps but here is a screenshot from our discord: https://imgur.com/a/1YZR5aF

This topic was brought up in our discord again, can you maybe have another look please? :D

**Comment by UltraNix** [comment]
@VincentADK New report please.

**Comment by Afgann** [comment]
fixed
