### ISSUE TITLE
"Anything We Can Get" and "Death Worthy of a Dragonmaw" are broken

### ISSUE THREAD

**Issue by Dellus112** [gamefreedomgit/Maelstrom#3895]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quests "Anything We Can Get" and "Death Worthy of a Dragonmaw" are broken. You cannot loot Dragonmaw Weapon and killing Dragonmaw Straggler does not count for quest.

**How to reproduce:**
Try to loot Dragonmaw Weapon Rack and try killing (Injured) Dragonmaw Straggler with these two quests active.

**How it should work:**
You should be able to loot Dragonmaw Weapon from Dragonmaw Weapon Rack and (Injured) Dragonmaw Straggler for the first quest, and for the secound one, killing (Injured) Dragonmaw Straggler should count for quest.

**Database links:**
https://www.wowhead.com/quest=27814/anything-we-can-get
https://www.wowhead.com/quest=27813/death-worthy-of-a-dragonmaw
https://www.wowhead.com/item=62511/dragonmaw-weapon
https://www.wowhead.com/object=206672/dragonmaw-weapon-rack
https://www.wowhead.com/npc=46851/dragonmaw-straggler
https://www.wowhead.com/npc=47465/injured-dragonmaw-straggler

**Comment by PanJanuszek** [comment]
Works correctly on 05.08.2023
