### ISSUE TITLE
[Death Knight] Blood Tap refreshes the currently recharging blood rune, rather than the currently depleted blood rune

### ISSUE THREAD

**Issue by jlemieux** [gamefreedomgit/Maelstrom#3896]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
DK runes have 3 states: full, recharging, depleted. Blood Tap should activate the currently depleted blood/death rune, rather than the currently recharging blood/death rune.
Related issue: #3466 

**How to reproduce:**
Use both of your blood runes or death runes, so that they are in a state of [recharging, depleted] or [depleted, recharging]. Use Blood Tap; it will activate the recharging one rather than depleted one.

**How it should work:**
It should prioritize the depleted rune instead.
See here for example from retail Cata: https://youtu.be/fRtlzjq0WwA?t=96
At 1:37 he uses blood tap while his death runes are in [depleted, recharging] state. and it activates the fully depleted rune
![image](https://github.com/gamefreedomgit/Maelstrom/assets/10594375/3c6f7570-6f4d-4414-b5e6-dce1f3bdd438)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/10594375/7c3fba37-d8be-4d5e-a9ac-6054a70d80fb)

**Database links:**
https://www.wowhead.com/spell=221699/blood-tap

**Comment by UltraNix** [comment]
Fixed.
