### ISSUE TITLE
Riding Turtle mount not shared across all the characters

### ISSUE THREAD

**Issue by Shakrei** [gamefreedomgit/Maelstrom#3897]
The tooltip in the shop states that the mount is shared across all the characters.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/b4b6f7a3-7972-47e2-ba70-16c171881cdd)
My gnome, Shakrei, has it
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/61c42db4-a6a2-493d-baa3-556670b08933)
but none of my alts do.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/6f903cb4-df0d-4304-8727-2020c25fe0e3)

**Comment by UltraNix** [comment]
Fixed.
