### ISSUE TITLE
aura work and dead players

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3898]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
auras continue to work after the death of the character

**How to reproduce:**
use aura and die

**How it should work:**
auras should stop working after character death

**Database links:**
...

**Comment by mipanka** [comment]
why? 
![WoWScrnShot_062623_012645](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/7762754f-27e2-477f-a3d3-8b1e55463d9a)

**Comment by UltraNix** [comment]
Fixed.
