### ISSUE TITLE
Dungeon Finder Re-Queue after Dungeon Completion

### ISSUE THREAD

**Issue by Akayso** [gamefreedomgit/Maelstrom#3899]
**Description:**
Searches for new members for the current dungeon after you finish the dungeon. After it found a new member, you can only port back to the finished dungeon. It does not re-queue current members for another one

**How to reproduce:**
Finish a dungeon, then re-queue for new dungeon with current partymembers

**How it should work:**
Get ported to the NEW dungeon after completing the current dungeon

**Database links:**
-

**Comment by UltraNix** [comment]
Fixed.
