### ISSUE TITLE
Stealth vs root effects

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3900]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stealth is currently not broken if root effects are applied. Ex: Earth's Grasp, Frost nova ( if dmg is absorbed by shields ), etc

**How to reproduce:**

**How it should work:**

Stealth should be broken by root effects

Proof:  

https://www.mmo-champion.com/threads/921275-shamman-totems-and-stealth
> if your ele and speced into earth's grasp or w/e that talent is called the root will pull rogues outta stealth

https://cata-twinhead.twinstar.cz/?issue=3997 **Translated**

> The whole stealth ejection system works poorly. I will write down all possible situations and how it should turn out.
> 
> Direct spelly: - frostbolt, chaos bolt, frost shock, but also meele hit ...
> Any direct spells are meant to throw the roguna out of stealth even if it has absorb
> 
> on it Flat spells: - holy nova, arcane explosion ...
> These area spells are meant to throw the roguna out of stealth even if it has absorbing
> 
> Surface spells (aoe target) on it: - Blizzard, Rain of fire ...
> These area spells are supposed to throw roguna out of stealth even if it has absorbent
> 
> Surface spells (aoe on the ground): consentration, DnD, flamestrike (the aoe that lies on the ground AFTER docastení)
> They do not throw roguna out of stealth if it
> 
> has absorb Dot effects: rend, corruption, deadly poison ...
> Ticky do not throw out the roguna from the stealth if it has absorbent on it - their application however yes
> 
> Root effects: frost nova, roots from a talented EB totem ...
> They are supposed to expose the roguna even if it has an absorber on it.
> 
> I will add that rogunu are to throw dot effects and flat spells on the ground in case the tick (damage) penetrates the absorber.

**Database links:**

**Comment by bonfax4** [comment]
https://youtu.be/gSuc4Jclooc?t=280 Frost nova getting shielded mage out of invis.

All the other mechanics need to be tested as well. Specially the aoe vs shielded stealthed player mechanics.

**Comment by bonfax4** [comment]
https://youtu.be/jk2ae8EYhGA?t=256 Shit quality but you can see Earth's Grasp  getting feral dudu out of stealth in the corner

**Comment by UltraNix** [comment]
Fixed.
