### ISSUE TITLE
Northrend dragonblight quest "Report to Lord Afaratrasz"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3901]
**Description:**
"Report to Lord Afaratrasz" after finishing prequest there is no dialogue for getting this one

**How to reproduce:**

**How it should work:*
after finishing q [Informing the Queen] you should get this one to pick up

**Database links:**
https://www.wowhead.com/wotlk/quest=12435/report-to-lord-devrestrasz

**Comment by PanJanuszek** [comment]
no repro 21.03.2024
