### ISSUE TITLE
Northrend Dragonblight quest "fall from grace"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3902]
**Description:**
This quest shouldn't be in the game (removed at start of cata)

**How to reproduce:**

**How it should work:**
there should be another q, not this one (The Truth Will Out) that one

**Database links:**

**Comment by PanJanuszek** [comment]
Not agree

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/2396b665-0b51-4a18-b9f2-3fab11121813)

The Truth Will Out - is next quest in chain

Closing
