### ISSUE TITLE
Northrend grizzly hills q "Raining Down Destruction"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3903]
**Description:** after finishing q "An Expedient ally" (horde only) couldn't get this one from NPC, tho finishing alliance counterpart "Find kurun" 
i got another one normally

**How to reproduce:**

**How it should work:**
should normally give another q called "Raining down destruction" after finishing horde one

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/6b37ae8a-59e5-46eb-8ca1-ff3cd7cdfd55)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/124f6160-2d94-4301-b9b7-8f05c95dba22)

 works as should 21.03.2024

If you finish Find kurun --> An Expedient ally will be not available. Vice - versa. Both of them lead to Raining Down Destruction
