### ISSUE TITLE
Wotlk Borean tundra q "Monitoring the rift:Sundered chasm"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3905]
**Description:**
You should go underwater and at very bottom use q item but q item doesn't work (allways tell you that you are not in the right zone)

**How to reproduce:**

**How it should work:**
you should be albe to use q item once you are at the bottom (where the rift is)

**Database links:**

https://www.wowhead.com/wotlk/quest=11582/monitoring-the-rift-sundered-chasm

**Comment by PanJanuszek** [comment]
Works as intended

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/3c9b3a42-f175-47e1-894c-dd7a517e9ac9)
