### ISSUE TITLE
wotlk Dragonblight q "Mystery of the Infinite,Redux"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3906]
**Description**
you should place hourglass on the ground and then fight off mobs till you are finished but mobs don't show up and once you hanlde first part "Mystery of the Infinite" it shows you can handle back in it 2nd way but it's like wisual bug (you can select the reward but can't turn it in second time, it should't show up)

**How to reproduce:**

**How it should work:**
place hourglass of infinity on the ground and mobs should show up, then def it untill last wave and done

**Database links:**
https://www.wowhead.com/wotlk/quest=13343/mystery-of-the-infinite-redux

**Comment by PanJanuszek** [comment]
fixed 19.03.2024
