### ISSUE TITLE
wotlk grizzly hills q "Filling the Cages"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3907]
**Description:**
You should be able to get this q after you finish "Good Troll Hunting" but next q don't show up

**How to reproduce:**

**How it should work:**
you should be able to get it after pre q 

**Database links:**

https://www.wowhead.com/wotlk/quest=11984/filling-the-cages

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/dbbb0eeb-fe0f-4886-ac2b-9b154683280e)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/82d7cd95-1125-4d30-9cfd-9d4b37f06991)

works as should 21.03.2024

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/e76fcbea-c93b-43b4-9de1-541018577faa)
