### ISSUE TITLE
wotlk Dragonblight q "The Forsaken Blight and You:How not to Die"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3908]
**Description:**
you should be able to get it after you finish preq "To Venospite" in Howling foyrd but it doesn't show up 

**How to reproduce:**

**How it should work:**
you should be able to get it after you turn in pre q

**Database links:**
https://www.wowhead.com/wotlk/quest=12188/the-forsaken-blight-and-you-how-not-to-die

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
