### ISSUE TITLE
Wotlk  Dragonblight q "A Tauren Among Taunka"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3909]
**Description:**
You should be able to get it after pre q "Across Transborea" from Borean Tundra but it doesn't show up to pick after turning in pre q

**How to reproduce:**

**How it should work:**
You should be able to get it after turning in pre q

**Database links:**
https://www.wowhead.com/wotlk/quest=11977/a-tauren-among-taunka

**Comment by PanJanuszek** [comment]
no repro 21.03.2024
