### ISSUE TITLE
Wotlk Boren tundra quest "Monitoring the rift:Winterfin cavern" bugged

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3910]
**Description:**
can't use quest item when you soposed to be use it it still messages (Requires Westrift seismic anomaly) 

**How to reproduce:**

**How it should work:**
you should be able to use it near entrance to the cavern 

**Database links:**
https://www.wowhead.com/wotlk/quest=12728/monitoring-the-rift-winterfin-cavern

**Comment by PanJanuszek** [comment]
should be fixed as on 18.03.2024
