### ISSUE TITLE
Midsummer Event - [NPC Missing from Badlands] [Horde]

### ISSUE THREAD

**Issue by Pointbp** [gamefreedomgit/Maelstrom#3914]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The NPC which you turn in the quest "Honor the Flame" for progression towards the achievement "Flame Keeper of Eastern Kingdoms" for Horde is missing in Badlands. GM Tide had a check around with me, ressurrected all NPC in the area, and i tried things such as reload and relog, without any solution. 

**How to reproduce:**
Fly to Badlands, outside Dreadmaul Hold. You can find the Horde NPC missing from under the midsummer tent. 

**How it should work:**
NPC should be alive and give you the quest "Honor the Flame", which you are able to turn in instantly for progression towards achievement

**Database links:**
https://www.wowhead.com/quest=28930/honor-the-flame
![WoWScrnShot_062723_150905](https://github.com/gamefreedomgit/Maelstrom/assets/137901851/a89d5621-5a7d-4f36-afe4-bf54be9f8084)
![WoWScrnShot_062723_150908](https://github.com/gamefreedomgit/Maelstrom/assets/137901851/312289f6-f7f6-4784-bfeb-d0617dafd4d3)
![WoWScrnShot_062723_151516](https://github.com/gamefreedomgit/Maelstrom/assets/137901851/4557858e-cd4e-480f-80ca-8b34396c8f05)

**Comment by UltraNix** [comment]
Fixed.
