### ISSUE TITLE
Wotlk Zul'drak quests "Pa'troll"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3916]
**Description:**
here you need to go to difirent places and do tasks for 4 of them but you don't have any quest from them that account (exept one of them but those are diffirent q not related to main quest) and after you finish those one you suposed to get, Name of them are "Cocooned!" "Something for the Pain" "Creature Comforts" and "Lab work". Dailys are not showing either before and after finishing all tasks and pa'troll. Name of Daily quests "Troll Patrol:Something for the pain(daily version) "Troll Patrol:Can you dig it?" "Troll Patrol:Hight Standarts" Troll Patrol:Done to Death" "Troll Patrol:Throwing Down" "Troll Patrol:Intestinal Fortidute" "Troll Patrol:Creature Comforts (Daily one)" "Troll Patrol:Couldn't Care Less" "Troll Patrol:Whatdya Want, a Medal?" 

**How to reproduce:**

**How it should work:**
it should be avilable regardless of starting main q 

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 26.03.2024
