### ISSUE TITLE
Wotlk Zuld'drak quest "It Rolls Downhill" and "Zero Tolerance"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3917]
**Description:**
You should get it after turning in quest "Infiltrating Voltarus" and getting next in line "So far So Bad" but there is no dialogue from NPC Overlord Drakuru, Quest is not working as intended. Submited Blight geist is not collecing any crystals when abliti is used. About next quest (next in line after 'It Rolls Downhill" same as before NPC have no dialogue for you with that one)

**How to reproduce:**

**How it should work:**
you should use q item on blight geist and then use pet ability to collect Crystalized Blight (FOR "It Rolls Downhill)

**Database links:**
https://www.wowhead.com/wotlk/quest=12673/it-rolls-downhill

**Comment by PanJanuszek** [comment]
should be fixed as on 18.03.2024
