### ISSUE TITLE
The Culling of Stratholme

### ISSUE THREAD

**Issue by Nightwiings** [gamefreedomgit/Maelstrom#3918]
**Description:**
Cant do the Box quest (Dispelling Illusions), i know that cuz a GM help me to pass the box quest, but and after that, i can clean and kill the first boss, but next boss when arthas walk inside the house, he bug and dissapear. 

**How to reproduce:**

**How it should work:**
Try do the dungeon and see by ur self this bug that i speak

**Database links:**
https://www.wowhead.com/quest=13149/dispelling-illusions

**Comment by Afgann** [comment]
fixed
