### ISSUE TITLE
Wotlk Zul'drak quest "Fuel for the Fire"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3919]
**Description:**
Next one from q-chain from "Voltarus" Overlord Drauku doesn't have dialogue after you get next q for zone "Sabotage" 

**How to reproduce:**

**How it should work:**
you should have q [Fuel for the Fire] avilable after you take quest "Sabotage"

**Database links:**
https://www.wowhead.com/wotlk/quest=12690/fuel-for-the-fire

**Comment by PanJanuszek** [comment]
fixed 09.02.2024
