### ISSUE TITLE
Wotlk Storm Peaks Hodir dailys

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#3920]
**Description:**
Quests "Thrusting Hodir's Spear" and "Feeding Arngrim" are not working at all. you should be able to throw spear at drake and them custom event starts wheere you will be fighting at the top of drake to kill it, on second one mobs should be replaced for another ones (Romaing Jormungar for Disembodied Jormungar) and at 15% they would be eaten by Arngrim 

**How to reproduce:**

**How it should work:**
Spear should be working and drake event should start as soon as drake comes close to you from pulling, on second one mobs should be changed after throwing at them q item and executed by NPC at 15%

**Database links:**
https://www.wowhead.com/wotlk/quest=13046/feeding-arngrim
https://www.wowhead.com/wotlk/quest=13003/how-to-slay-your-dragon

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
