### ISSUE TITLE
Cata: Preparation not resetting Sprint CD

### ISSUE THREAD

**Issue by Antiiblood** [gamefreedomgit/Maelstrom#3921]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Preparation not resetting Sprint CD

**How to reproduce:**
Use the skill see sprint not resetting

**How it should work:**
Reset sprint CD on use

**Database links:**
Tooltip:
When activated, this ability immediately finishes the cooldown on your Evasion, Sprint, Vanish, and Shadowstep abilities.

**Comment by Antiiblood** [comment]
Any update on the bug?

**Comment by Afgann** [comment]
fixed
