### ISSUE TITLE
Archeology in Burning Steppes bugged

### ISSUE THREAD

**Issue by wylgner12** [gamefreedomgit/Maelstrom#3923]
Description: Digsite in ruins of thaurissan bugged, sending me of bounce 

![WoWScrnShot_062823_103928](https://github.com/gamefreedomgit/Maelstrom/assets/138022911/88be2e25-e6a3-422d-98a3-54c5c7ef9924)

![WoWScrnShot_062823_103941](https://github.com/gamefreedomgit/Maelstrom/assets/138022911/1098dc74-118c-4937-8e4c-e55a0ddfed8a)
![WoWScrnShot_062823_104001](https://github.com/gamefreedomgit/Maelstrom/assets/138022911/e9bc2228-cfc3-4e49-92a5-63d365540c7e)

**Comment by UltraNix** [comment]
Fixed.
