### ISSUE TITLE
Oath-Chained Infernal Immolation buff spellsteal.

### ISSUE THREAD

**Issue by Apache77** [gamefreedomgit/Maelstrom#3924]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Oath-Chained Infernal ID 41253 - has an immolation buff ID 12743 applied on them which is spellstealable. Buff has a long duration and stacks with each other.
![WoWScrnShot_062823_224033](https://github.com/gamefreedomgit/Maelstrom/assets/76235260/97c99759-3a48-4fe6-ab53-3682bd3678f0)

**How to reproduce:**
Be a mage, spellsteal buff from Oath-Chained Infernals ID 41253

**How it should work:**
Buffs shouldn't stack and should replace each other.

**Database links:**
https://www.wowhead.com/npc=41253
https://www.wowhead.com/spell=12743

**Comment by UltraNix** [comment]
Fixed.
