### ISSUE TITLE
[Cataclysm] Tol'vir HC via RHC listed as 0/4 bosses cleared

### ISSUE THREAD

**Issue by Exorcista** [gamefreedomgit/Maelstrom#3925]
**Description:** Upon entering the HC diff via RDF tool, you get a version of the dungeon without any mob or boss on it, and even gms cant spawn last boss making it a waste of time

**How to reproduce:** really dont know, just queue via RDF tool

**How it should work:** get the full dungeon

**Comment by Waroxx-QA** [comment]
Did that happen after re-queuing with the same party ?

**Comment by Waroxx-QA** [comment]
#3899

**Comment by Exorcista** [comment]
> I think it happened because players you joined just finished the dungeon then re-queued without leaving / making a new party. #3899

really have no clue, but Crywolf has attended me 2 times over this bug happening and even he, cant even make last boss spawn

**Comment by Exorcista** [comment]
![WoWScrnShot_063023_004146](https://github.com/gamefreedomgit/Maelstrom/assets/6818405/283b27bf-4648-4a60-8bd7-734f0f50faac)

Stonecore HC rn

**Comment by UltraNix** [comment]
@Exorcista Need more info what happened before the last one (the one from the pic)? Have you been on Stonecore HC that day before? If yes - have you joined that heroic being progress or from the very beggining? 
And about the one from pic - you queued up as a party or solo? I see there intial mobs and the NPC that triggers the event before the 1.st boss.

**Comment by Exorcista** [comment]
> @Exorcista Need more info what happened before the last one (the one from the pic)? Have you been on Stonecore HC that day before? If yes - have you joined that heroic being progress or from the very beggining? And about the one from pic - you queued up as a party or solo? I see there intial mobs and the NPC that triggers the event before the 1.st boss.

sorry for late response

both times i queued as solo, last pic no i didn't do that one that day, this is listed as fixed on discord tho haha

**Comment by UltraNix** [comment]
Fixed.
