### ISSUE TITLE
Doomguard haste scaling (Again)

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#3926]
**Description:**
**After the last change made to doomguards, they arent benefitting properly from haste rating on gear.** 

**Going from 0 to 2094 haste rating isnt giving him any extra doombolt casts.**

Naked test with 0 rating:

![0haste](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/ddb79c93-a8af-40f7-bc38-ebcfdd3ee818)

Test with 2094 haste rating

![2094 21 casts](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/99de5c1b-f574-4972-b23b-63cb3d5c94c0)

**How to reproduce:**

Cast doomguard with 0 haste, and then with 2k haste and watch him do the same amount of casts per summon.

**How it should work:**
Doomguard should inherit the owner's haste rating at the moment of the summon, and snapshot it for the entire duration, making him cast more doombolts per summon the higher your haste rating is. 

With 2094 haste rating, he should cast:
 24 ~ 25 casts for demonology - 65 seconds duration/ 2.57s cast time =25.21 
 16 ~ 17 casts for affliction and destruction - 45 seconds duration/ 2.57 cast time =17.45

EJ Warlock mechanics discussion, post #146 talking about this:
https://web.archive.org/web/20140716032500/http://forums.elitistjerks.com/topic/117067-warlock-mechanics-in-cataclysm/page-8

**Comment by UltraNix** [comment]
Fixed.
