### ISSUE TITLE
Hunter: snake trap cast without learning it

### ISSUE THREAD

**Issue by Honzurka** [gamefreedomgit/Maelstrom#3927]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Hunter between levels 48-65 can use trap launcher + snake trap without learning the snake trap ability (requires level 66)

**How to reproduce:**
- snake trap cast must be done using macro:
/cast Trap Launcher
/cast Snake Trap

**How it should work:**
It shouldn't be possible to cast snake trap at those levels

**Comment by UltraNix** [comment]
Fixed.
