### ISSUE TITLE
[Hunter] [Pet] [Pet ability] [Beast Mastery] Spirit Walk Id:"90328" Prowl Id:"24450"

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#3930]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As I finished the thread it came to me to check if the regular ferocity cats spell prowl works better since for some reason I just realized that they are different spells, and both have the same issue

There is a small, yet very irritating, well 2 bugs with this spell.
1. If you manually cast it, you can't force the pet to leave stealth aside of sending it to attack hostile target.
2. If you manually cast stealth, the spell doesn't go on a cooldown after exiting and after ending/leaving combat you can't recast the ability because you get the following error message "Ability is not ready yet".
The 2nd issue can only be resolved by turning on auto cast for the spell (and remember read 1 can't get out of stealth), entering arena or relogging.
**How to reproduce:**
  - Tame any spirit beast or any other cat pet and manually cast prowl or spirit walk.
  - Try to leave stealth without entering combat(canceling the stealth by pressing the spell).
  - After entering/leaving combat, attempt to manually cast stealth again

**How it should work:**
First cast it puts the pet into stealth, second click should remove the spell aura and after leaving a spell cooldown should trigger

**Database links:**
https://www.wowhead.com/spell=90328/spirit-walk
https://www.wowhead.com/spell=24450/prowl

**Comment by UltraNix** [comment]
Fixed.
