### ISSUE TITLE
Al'akir P3 Pets Non-responsive

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3931]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently in Al'akir's last phase pets are not doing anything, just chilling beside owner.
https://imgur.com/a/ui5OL7m
High chance this is related to the fix that went through when pets had infinite leashes and people were sending them everywhere in bgs. Most likely since al'akir is so far away it triggers the range check that was implemented and makes them stay.

**How to reproduce:**

**How it should work:**
Pets should be able to attack boss regardless of owner distance (in this particular fight at least)
https://www.youtube.com/watch?v=6z3BEguaFIg&ab_channel=Manaflask
You can check from 5:20 onwards and see this guy's pet attacking on his scrolling combat text.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
