### ISSUE TITLE
The Lurker Below in Serpentshrine Cavern is already spawned and unable to be fished up.

### ISSUE THREAD

**Issue by buffmelee** [gamefreedomgit/Maelstrom#3933]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Lurker Below boss in Serpentshrine Cavern is required for the "The Lurker Above" achievement, which is also required for the "Accomplished Angler" meta achievement. This requires the player to actually fish the boss up (like in original TBC) however the boss is already spawned in when the area renders.

**How to reproduce:**
Enter the instance and walk within render distance of the boss.

**How it should work:**
The boss should be untargetable in a dormant state beneath the water. The player should be required to have a successful fishing attempt in the boss's pool area.

**Database links:**
https://www.wowhead.com/achievement=144/the-lurker-above#
https://www.wowhead.com/npc=21217/the-lurker-below#

**Comment by Exorcista** [comment]
you also are perma stuck in combat, and even after exiting the raid, he remains as "active encounter" and you cannot enter even redoing group doesn't fix this

**Comment by PanJanuszek** [comment]
lurker static spawn has been removed, fishing the Lurker works as of 20.05.2024
