### ISSUE TITLE
Midsummer Consumables

### ISSUE THREAD

**Issue by Hepticlol** [gamefreedomgit/Maelstrom#3936]
The stat food from the midsummer event currently gives 1 food per 5 blossom - It feels really painful and grindy to buy
You are supposed to get 5 food per 5 blossom

![image](https://github.com/gamefreedomgit/Maelstrom/assets/115653997/9be2d001-c4d3-49cf-9e9c-d1072cd7f072)

**Comment by bonfax4** [comment]
You should get i to the habit of linking proof, granted this barely needs research tk figure out it's wrong but still. Here's a cata wowhead link showing stack of 5's

**Comment by Hepticlol** [comment]
> You should get i to the habit of linking proof, granted this barely needs research tk figure out it's wrong but still. Here's a cata wowhead [link showing stack of 5's](https://web.archive.org/web/20120624070338/https://www.wowhead.com/npc=26124/midsummer-merchant)

I mean yea, that about says it by the fact that you found it quickly regardless of proof. I think anyone that has ever bought midsummer consumables on retail or pretty much any other private server knows its 5:5 for the food, atleast I have never seen a 1:5 ratio on any other server.
I didnt really think adding "proof" to this matter was necessary considering its widely known by most.
I would rather put in the effort of adding proof over bigger matters like something gamebreaking. All I wanted was not to suffer getting 5 times more blossoms than what I know would have been necassary to get.

**Comment by UltraNix** [comment]
Fixed.
