### ISSUE TITLE
[Warrior] [PvE] Minimal range for charge on Chogall's elementals is too big

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3937]
**Description:**
Warriors have to go away at around 25 yards range, if not more, in order to be able to charge fire and shadow elementals on Chogall HC. At the same time, their hitbox seems normal. Couple months ago it worked correctly

**How to reproduce:**
Try to charge elementals on Chogall and see how long range is required.

**How it should work:**
https://youtu.be/86vD9d96nac?t=113
At 1:57 the warrior doesn't use charge but you can see it on his bar (placed between Heroic Throw and Rend) is usable at way closer range than is allowed on the server.

**Comment by Afgann** [comment]
fixed
