### ISSUE TITLE
[PvE] Conclave of Winds HC state is and has been awful

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#3938]
**Description:**
Conclave ever since release exists in some unintentional mythic mode. It's easily in top5 hardest on t11 here, while normally it's more of a level of high tier group made fully of random pugs that aren't suitable even for Magmaw HC. I'll list the problems from most to least relevant.
1. The Wind Blast range is abysmally busted, to the point of it being closer to omnidirectional than actually frontal. 
My priest being pushed back standing roughly in 100 degrees angle to Rohash's hand:
https://imgur.com/hHlPW1d
Here (2 sec after being pushed) the angle is more like 130 degrees. From a CONE shaped attack.
https://imgur.com/O1CXTen
This mechanic is especially a joke when tornados make it impossible to keep your character at boss' butt or when they cloud so much that you can't see where he's directed.
To intercept an intuitive suggestion - no, this is not a visual bug of his animation. I've had cases of both me and one of dps being at 2 opposite sides of the boss and still getting pushed back by Wind Blast.
2. Another wrong thing with Wind Blast is it's cooldown. On this server it aligns with Storm Shield every time, making healing and dpsing during it a lot harder. On this retail video you can see it's casted together only on the first time for both at 0:52 (and Blast is still casted 2-3 seconds after applying the Shield), later we see Blast at 2:35, Shield at 3:15, Blast at 3:48, Blast at 5:05, Shield at 5:34, Blast at 6:19, Blast at 7:34, Shield at 7:58. Generally the cooldown here seems too long but it boosts the boss instead of weakening him.
3. Combat ress is often unusable here when the player died from a pushback ability - Tornado or Wind Blast. It usually moves player's corpse on the beginning platform but cb ress isn't usable neither here nor in the spot he died in. Note that you don't actually have to drop out of the platform in order for this to happen, so it's not like it wouldn't be here anyway. You can die from first tick of Wind Blast and still be unressable.
4. Nezir's Ice Patch is overly accurate. Take a look at it's placing at 1:52, 2:28, 4:28, 4:52, 6:43, 7:13 and 8:33. The pattern I see is that only the Patches casted right after Sleet Storm are placed with it's center on a player. Most of them aren't spawned on players at all. What it's supposed to do is pick a player but have a decent delay of actually placing the Patch on the location it picked. That way a moving target is barely possible for Nezir to catch in that aoe.
https://www.youtube.com/watch?v=uwfPydoT0tM

**How to reproduce:**
1. Try standing on Rohash's side (especially right) during Wind Blast.
2. None, compare timers from server and retail.
3. Die from a pushback effect on Rohash's platform, have another player try to ress you.
4. Get hit by Ice Patch on Nezir while running, compare with retail.

**How it should work:**
Already explained, would be unnecessarily messy to divide it into 2 sections.

**Comment by UltraNix** [comment]
@ussj10 
`
Combat ress is often unusable here when the player died from a pushback ability - Tornado or Wind Blast. It usually moves player's corpse on the beginning platform but cb ress isn't usable neither here nor in the spot he died in. Note that you don't actually have to drop out of the platform in order for this to happen, so it's not like it wouldn't be here anyway. You can die from first tick of Wind Blast and still be unressable.
`
You mean .e.g Soulstone? 
I just tested that - after I died (kicked by tornado), I've been teleported to the entrance platform and then I was able to click and ress myself.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/6f26fd39-c99e-4af1-bfa1-ce701b8c1cc3)

**Comment by UltraNix** [comment]
@ussj10 
`
Combat ress is often unusable here when the player died from a pushback ability - Tornado or Wind Blast. It usually moves player's corpse on the beginning platform but cb ress isn't usable neither here nor in the spot he died in. Note that you don't actually have to drop out of the platform in order for this to happen, so it's not like it wouldn't be here anyway. You can die from first tick of Wind Blast and still be unressable.
`
You mean e.g. Soulstone?
I just tested that - after I died from knockback (Wind Blast), just got teleported to the entrance platform and was able to click and ress myself.
![WoWScrnShot_070623_161927](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f14da5ae-8993-4c22-9bb4-1c181bee4643)

**Comment by ussj10** [comment]
@UltraNix I don't think so. Not sure if precasted SS worked for me or not. I mean primarily inability to cast SS or Rebirth on that corpse.

**Comment by UltraNix** [comment]
@ussj10 Something's changed with that combat ress thing recently? I mean - it works okay now?

**Comment by ussj10** [comment]
@UltraNix Yes, Rebirth was successfully casted on me after I died from pushback effect. I still haven't had the chance to test Patch delay and Blast range myself but I heard it's good now, same as Blast cooldown.

**Comment by UltraNix** [comment]
Then it's fixed.
