### ISSUE TITLE
ring of frost dmg threshold (DoT)

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3939]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
dmg threshold from dots are not count in the calculation

**How to reproduce:**
use ring of frost and get effect freeze with dots

**How it should work:**
dot should count for threshold dmg

**Database links:**
https://wowpedia.fandom.com/wiki/Ring_of_Frost

screen 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/8b3ff711-8a1f-47c8-a0cf-17c698b0e9fa)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/0a163973-c32e-41eb-a185-0243a855b7aa)

**Comment by Sketish** [comment]
Well provide any source that is confirming that

**Comment by mipanka** [comment]
123, pls fix it

**Comment by mipanka** [comment]
@Sketish

**Comment by Sketish** [comment]
Still waiting for any retail video or source

**Comment by mipanka** [comment]
bug after fix https://github.com/gamefreedomgit/Maelstrom/issues/3793
"It's gonna be 20% of base health - it's minimum dmg threshold.
40% of base health - it's maximum dmg threshold.
Once you brake 20%, then you have 13% (for DOTs it's 5%) chance to break right there and until you hit 40%.
Once you hit 40% - then aura is removed immediately."
UltraNix words

**Comment by UltraNix** [comment]
![asda](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ba256325-3f06-4c66-8e61-eefc12206167)
As you can see, 2 ticks of Living Bomb and Frost Nova is removed.

**Comment by UltraNix** [comment]
![asda](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9516ba2e-2c8f-4a1c-9da3-8d0b6a62d9e9)
As you can see - 2 ticks of LB and Frost Nova is removed.
Damage threshold works for DOTs.

**Comment by mipanka** [comment]
bug only with ring of frost

**Comment by mipanka** [comment]
btw pls fix it too https://github.com/gamefreedomgit/Maelstrom/issues/3980

**Comment by UltraNix** [comment]
Fixed.
