### ISSUE TITLE
ambassador flamelash is often dropping 0 items

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#3940]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ambassador flamelash in BRD is often times dropping 0 loot whatsoever. 

**How to reproduce:**
just kill it a bunch

**How it should work:**
should drop at minimum of 1 blue item, and hopefully the epic :D 

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=9156

**Comment by Afgann** [comment]
fixed
