### ISSUE TITLE
trouble with Binds to Blizzard account weapon

### ISSUE THREAD

**Issue by badtrip811** [gamefreedomgit/Maelstrom#3941]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sorry, google translator
my character (Nioba) has two Binds to Blizzard daggers: Sharpened Scarlet Kris, Balanced Heartseeker with expensive 15 agility upgrades. The character is level 81+ and I can't equip these daggers as they are listed as level 1-80. The daggers also have rogue poisons on them, making them non-mailable, and I can't equip them to cancel the poisons. I tried to replace them with sharpening, but the effect is the same. Please help me cancel the effect of poisons so that in the future I can send these weapons to my twinks. Thank you

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by badtrip811** [comment]
https://www.wowhead.com/item=122350/balanced-heartseeker
https://www.wowhead.com/item=122364/sharpened-scarlet-kris

**Comment by badtrip811** [comment]
How it should work:

As I recall, on Blizzard servers, Binds to Blizzard items can be worn at any level. The fact that 1-80 lvl is indicated on the daggers means that the increase in characteristics is 1-80 lvl, that is, I should be able to put on daggers at lvl 81, but they will be, as it were, at lvl 80

**Comment by bonfax4** [comment]
There was an issue iirc where heirloom weapons kept scaling over 80, so I'm assuming they were disabled intentionally. There was also a bug that allowed heirlooms with poison to be mailed to low levels too but i guess you knew that already too lol

**Comment by badtrip811** [comment]
> Была проблема iirc, из-за которой наследуемое оружие продолжало масштабироваться более 80, поэтому я предполагаю, что оно было отключено намеренно. Была также ошибка, которая позволяла отправлять реликвии с ядом по почте и на низкие уровни, но я думаю, вы уже знали об этом, лол.


so I want to remove the poison so that I can send my things to the twink, and since there is poison on the weapon, I can’t. I can't put on my things and take off the poison myself. Can you help?

**Comment by badtrip811** [comment]
так я и хочу снять яд, чтобы я смог отправить мои вещи твинку, а так как на оружии яд, у меня не получается. Одеть вещи и сам снять яд я тоже не могу Вы сможете помочь?

**Comment by bonfax4** [comment]
Try the support channel on discord honestly, or in-game ticket. Gm's respond quick these days.
