### ISSUE TITLE
Retaliation-Recklessness Shield Wall Bug

### ISSUE THREAD

**Issue by Evil203** [gamefreedomgit/Maelstrom#3942]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description:
Retaliation-Recklessness you can use it with wall but somehow it's not working now I have this problem for the last 5 days
warrior unplayable now with this situation.even if u cancel it you have to wait for 10 sec.
How to reproduce:
try use recklessness or retaliation with shield wall 

How it should work:
Shield Wall should work with retaliation or recklessness there is some evidence from another server

Database links:
https://imgur.com/a/Z1CzqAJ

**Comment by mipanka** [comment]
fix after https://github.com/gamefreedomgit/Maelstrom/issues/3798

**Comment by Sketish** [comment]
Not a bug
