### ISSUE TITLE
mobs in hellfire ramparts do not drop green loot

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#3943]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

the mobs just dont drop greens. i wanted to farm a thrown weapon that only drops from trash there but there is no trash loot. 
**How to reproduce:**
kill all the trash in hellfire ramparts (same for other low level dungeons too) 

**How it should work:**
should drop greens. 

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=17259#drop:50-13+1

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
