### ISSUE TITLE
Incorrect experience output

### ISSUE THREAD

**Issue by Frosen69** [gamefreedomgit/Maelstrom#3944]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

 for killing this NPC, a lot of experience is given.

**How to reproduce:**
need to kill

**How it should work:**
should give experience evenly to the level

**Database links:**
https://www.wowhead.com/ru/npc=142688/%D0%B4%D0%B0%D1%80%D0%B1%D0%B5%D0%BB%D0%BB%D0%B0-%D0%BC%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D1%83%D0%B7
![WoWScrnShot_070323_153353](https://github.com/gamefreedomgit/Maelstrom/assets/138493714/f8978d6e-572d-4ae8-be5b-cab6f6bc4db9)

**Comment by BalanCV** [comment]
That npc is a rare, as such it gives more exp on kill. This is blizzlike.
