### ISSUE TITLE
Vortex pinnacle no deserter debuff 

### ISSUE THREAD

**Issue by Veldanava97** [gamefreedomgit/Maelstrom#3945]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** i was running normal vortex pinnacle as a discipline priest i deserted after two wipes and did not get deserter i was the first one to leave also i was under the effects of the mass resurrection debuff im not sure if that had anything to do with it

**How to reproduce:** play vortex pinnacle NM as a disc priest die atleast 1 before the scond pull after the second boss and you must have the mass resurrection debuff. desert after your second death on the second pull after second boss

**How it should work:** i should get deserter for this 

**Database links:**

**Comment by UltraNix** [comment]
Should be fixed.
