### ISSUE TITLE
Social, Chat, Arena Solo Bugs!!!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3946]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
~Whenever someone from your friends list changes zones, teleports, enters arena it says on your chat that he has come online, thats the first bug.~ Fixed

Second bug, when you join arena or a bg as a group it shows this " party 1 is not in your party "

~Third bug i encountered is when you que for solo que and you teleport with hearstone it shows this.~ Fixed

**How to reproduce:**

**How it should work:**

**Database links:**
![WoWScrnShot_070423_015733](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7ee58d74-a8d2-48cb-be57-fad8755bef14)

![WoWScrnShot_070423_020932](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/b764f6bc-409f-43d2-9673-358f2790e785)

**Comment by Renehadox** [comment]
Is this fixed?

**Comment by Renehadox** [comment]
Is this fixed?

**Comment by UltraNix** [comment]
@Renehadox 
`Second bug, when you join arena or a bg as a group it shows this " party 1 is not in your party "`
Are you using some macros with "@party" prefix maybe or smth?

**Comment by Renehadox** [comment]
Yes but not with player names ,just party 1 2 3 ...

**Comment by UltraNix** [comment]
<img src="https://media1.giphy.com/media/JRUeMkrHnlIf2oE3Hs/giphy.gif"/>

**Comment by Renehadox** [comment]
> ![](https://camo.githubusercontent.com/67cef66784203d4911aa8b6f33569381c39a2981630fe83ff88289d9fd7ba882/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a5255654d6b72486e6c4966326f453348732f67697068792e676966) [ ![68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a5255654d6b72486e6c4966326f453348732f67697068792e676966](https://camo.githubusercontent.com/67cef66784203d4911aa8b6f33569381c39a2981630fe83ff88289d9fd7ba882/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a5255654d6b72486e6c4966326f453348732f67697068792e676966) ](https://camo.githubusercontent.com/67cef66784203d4911aa8b6f33569381c39a2981630fe83ff88289d9fd7ba882/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a5255654d6b72486e6c4966326f453348732f67697068792e676966) [ ](https://camo.githubusercontent.com/67cef66784203d4911aa8b6f33569381c39a2981630fe83ff88289d9fd7ba882/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a5255654d6b72486e6c4966326f453348732f67697068792e676966)

Show you what?

I am using party =party1 and =party2 macros thats all

**Comment by UltraNix** [comment]
Show me these macros - that's all I'm asking.

**Comment by Renehadox** [comment]
![macro](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/d8fb0e07-94ce-46d2-bebc-47fd0aca7114)

here you go.

**Comment by UltraNix** [comment]
Looks like it's some of your addon that makes that spam - nothing serverside.
Can you send to me all of your addons?

**Comment by Renehadox** [comment]
Gladius, Lose Control, Xperl ( some are disabled ), Power Auras, i cant name them all really.

**Comment by UltraNix** [comment]
#1 i #2 fixed.
