### ISSUE TITLE
Dungeon Catch-Up Transportation Bugged in SFK/Grim Batol

### ISSUE THREAD

**Issue by NickGrayInternational** [gamefreedomgit/Maelstrom#3947]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The dungeon catch-up transportation mechanics (teleporter NPC by the stairs in SFK and drakes in Grim Batol) do not function as intended as explained below. 

**How to reproduce:**
Attempt to use either the Grim Batol or the SFK teleporter/catch-up transportation options. 

**How it should work:**
SFK Intended Behavior: I click the text labeled "Take me to the laboratory" when talking to the teleporter NPC by the entrance stairs and it takes me to the laboratory.
SFK: Actual behavior: I click the text labeled "Take me to the laboratory" when talking to the teleporter NPC by the entrance stairs and it takes me to the dining hall. 

Grim Batol Intended Behavior: I click on the drakes to mount them so they will drop me off further in the dungeon.
Grim Batol Actual behavior: I click on the drakes to mount them, but cannot mount them for transportation. 

**Database links:**
none

**Comment by UltraNix** [comment]
Fixed.
