### ISSUE TITLE
High Priest Venoxis - ground pool hitbox

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3948]
Description:**
Currently players are not able to move on red lines w/o getting any dmg
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/caafc74c-9858-4a32-9c69-2fb83b464976)

**How to reproduce:**
Pull Higj Priest Venoxis and try to run between green lines
**How it should work:**
Players should be able to walk there without getting any dmg from green lines

**Comment by Afgann** [comment]
fixed
