### ISSUE TITLE
Item durability shouldn't be lost upon dying from an enemy players

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3949]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I have noticed this bug that is happening here from the release of this server.

Players shouldn't lose item durability upon dying from an enemy player.

**How it should work:**

**Database links:**

![WoWScrnShot_070423_184757](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/17b314b4-9217-4bb7-aaeb-8a73c67fb516)

**Comment by Renehadox** [comment]
Is this fixed?

**Comment by Renehadox** [comment]
Is this fixed?

**Comment by UltraNix** [comment]
@Renehadox Can you give more details? I tried on world pvp, duel and battlegrounds with no result - seemed to be okay.

**Comment by Renehadox** [comment]
I am losing items durability when i die from pvp players, 

Hence why i reported it.

**Comment by Renehadox** [comment]
When do you guys plan to fix this?
