### ISSUE TITLE
[Quest][Item] Unable to use Swords Deck

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#3950]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unable to use Swords Deck, says "You don't meet the requirements for that quest"

**How to reproduce:**
Use Swords Deck to get the error message.

**How it should work:**
Use Swords Deck to get the quest and turn it in.

**Database links:**
https://www.wowhead.com/item=37164/swords-deck

**Comment by Afgann** [comment]
fixed
