### ISSUE TITLE
Pet  [Leap] Death knight

### ISSUE THREAD

**Issue by Killmequick1** [gamefreedomgit/Maelstrom#3951]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My pet, when using the "Jump" ability, remains in place, regardless of the state of the rack

**How to reproduce:**
Doesnt work, pet just stay

**How it should work:**
Pet charge to target

**Database links:**

**Comment by Sketish** [comment]
Please provide more details
