### ISSUE TITLE
C'thun HP is 100 times what it says.

### ISSUE THREAD

**Issue by Abstractyyy** [gamefreedomgit/Maelstrom#3952]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
C'thun HP in phase 2 is not what nameplate says. Nameplate says 999k but from calculation it's closer to 100M. Damage output shows normal damage from us the players during the fight and in Recount Addon, but 1K on c'thun nameplate was 100K damage done to him. One boss kill took about an hour. Attatched photo shows our damage to c'thun in Recount Addon.

**How to reproduce:**
Try to kill c'thun. Nothing special was done to achieve this. We just entered, killed first phase, and then we got this bug.

**How it should work:**
Damage output should match how much HP c'thun loses.

**Database links:**

![WoWScrnShot_070523_020843](https://github.com/gamefreedomgit/Maelstrom/assets/17291272/65373787-62d0-40a5-9471-98a85966d8c0)

**Comment by Afgann** [comment]
fixed
