### ISSUE TITLE
bugged quest line midway through in twilight highlands

### ISSUE THREAD

**Issue by Syxxqt** [gamefreedomgit/Maelstrom#3953]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I was questing in twilight highlands to get bis  caster pants and mid way through my quest line it just stopped all together made me repeat a quest until i reached out to gms to help me even with the help i cannont collect nor complete the quests to get them now im stuck 10 quests away from getting the pants but yet No cigar
**How to reproduce:**

**How it should work:**

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/138647609/59f7f158-f08b-490a-8e43-4f57fc7124e7)

**Comment by Syxxqt** [comment]
At this point the Gm had to help me accept quests and try to complete but with no avail..... Kinda sucks to be stuck behind somthing like this..

**Comment by Sketish** [comment]
Fixed
