### ISSUE TITLE
Runn Tum Tuber should be in dire maul. 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#3954]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Runn Tum Tuber should be lootable from little pods in dire maul. 

**How to reproduce:**
go through dire maul

**How it should work:**
there should be objects called warpwood pods all around the place  (https://cata-twinhead.twinstar.cz/?object=179528)

**Database links:**
https://cata-twinhead.twinstar.cz/?item=18255

**Comment by PanJanuszek** [comment]
fixed 10.05.2024
