### ISSUE TITLE
Honor Among Thieves

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#3956]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
this talent is giving combo points to a new target even when you already have combo points on an existing target.

**How to reproduce:**
Generate combo points on one target, swap targets and then let it proc. It will delete your old combo points and add one point to your new target.

**How it should work:**
Add combo points on top of existing ones regardless of your current target. If 5 points are on a target then add no points to any target. If 0 points are on any targets then _and only then_ add one point to the current target.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51701

video of how it works on whitemane: https://www.youtube.com/watch?v=vNoIkaudfSw
video of how it worked on retail (long video full of examples cause I couldnt find any target dummy footage from retail): https://www.youtube.com/watch?v=Zj3wStRBZZs

**Comment by Afgann** [comment]
fixed
