### ISSUE TITLE
Can't use Banner on Gorax's corpse in quest The Foot of the Citadel

### ISSUE THREAD

**Issue by Dartictheunic** [gamefreedomgit/Maelstrom#3957]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When doing the quest "The Foot of the Citadel", you can't use the "Challenge from the Horde" item on the corpse of Force Commander Gorax, thus making the quest unfinishable. You get a message stating "Requires Force commander Gorax's corpse", whether you target the corpse or stand next to it.

**How to reproduce:**
Start the quest, kill Gorax and use the item.

**How it should work:**
The item should be placed and the next wave of mobs should appear.

**Database links:**
https://www.wowhead.com/tbc/quest=10876/the-foot-of-the-citadel

**Comment by oldspices** [comment]
yep, had to have gm complete it for me.

**Comment by Afgann** [comment]
fixed
