### ISSUE TITLE
Small Comforts missing doll

### ISSUE THREAD

**Issue by Hubavelka** [gamefreedomgit/Maelstrom#3958]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Aprika Doll is uninteractable in the place it should be like roses and hammer

**How to reproduce:**
It should be interactable but its not 
![first](https://github.com/gamefreedomgit/Maelstrom/assets/67584204/c42da101-505f-4068-8257-36a5bf677fab)
![second](https://github.com/gamefreedomgit/Maelstrom/assets/67584204/e200f44d-437f-49fb-b68a-20b78d056d4a)

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=27805/small-comforts

**Comment by Afgann** [comment]
fixed
