### ISSUE TITLE
Feralas bugged archaeology area

### ISSUE THREAD

**Issue by bogdanian** [gamefreedomgit/Maelstrom#3960]
**Description:**
Bugged archaeology area in Feralas

There is a bugged zone digging area in Feralas. The coordinates for the middle point are 52, 15. 
Clues in this area lead to unobtainable artifacts, as they are probably under the ground.

This makes it so that I am unable to finish the whole dig zone, which limits archaeology areas in the whole Kalimdor from 4 to 3. 

![WoWScrnShot_070623_142957](https://github.com/gamefreedomgit/Maelstrom/assets/16436911/aaa34903-204a-4fb7-88eb-a5c9328738e4)
![WoWScrnShot_070623_143012](https://github.com/gamefreedomgit/Maelstrom/assets/16436911/995c78d3-da5b-4aca-a78c-f4e4b67a9a41)
![WoWScrnShot_070623_143401](https://github.com/gamefreedomgit/Maelstrom/assets/16436911/c1e1cf15-48fd-447a-81ad-152ebf920748)

**Comment by bogdanian** [comment]
update: those artifacts got reset, and i was able to complete the zone today.

**Comment by UltraNix** [comment]
Fixed.
