### ISSUE TITLE
Area 52 vendors Bugged

### ISSUE THREAD

**Issue by CarlosB9920** [gamefreedomgit/Maelstrom#3961]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Hi, I want to buy some transmogs for my Warr in the Area 52 located in Abisal Storm but i see that i can only buy the Horde version. All the Aliance vendor are bugged, I clicked on them and just do nothing.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Cannot reproduce
