### ISSUE TITLE
rocket boots xtreme light is putting blink on CD for 3+ mins 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#3962]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?item=35581  sometimes rocket boots is putting blink on CD for 3 whole mins and i cannot blink until those rocket boots are off CD. its happend twice now in the last 24 hours and idk if its because im blinking while rocket booting or what but it shouldnt work like that

**How to reproduce:**
not 100% sure. could have to do with canceling ice block / blinking / rocket booting. 

**How it should work:**
blink should never be on cd longer than its own CD. 

**Database links:**
https://cata-twinhead.twinstar.cz/?item=35581

**Comment by UltraNix** [comment]
Should be fixed.
