### ISSUE TITLE
Bug on the rogue's technique "Preparation"

### ISSUE THREAD

**Issue by Kroutenberg** [gamefreedomgit/Maelstrom#3964]
Hi !

I would like to report a bug with the rogue's "preparation" technique. 
Indeed, the reinitialization of the Cds indicated is only effective approximately one time out of two.
It should work every time. This bug is very annoying, especially in PvP.

Thanks for your help.

https://www.wowhead.com/wotlk/fr/spell=14185/pr%C3%A9paration

**Comment by Kroutenberg** [comment]
In fact, Ifeel like it's the reinitalization of "Sprint" Cd wich is the main problem.  Often, the cd of tecnique "vanish" is reset, but not the "sprint" one. Thank you

**Comment by oldspices** [comment]
i noticed this as well. is a issue

**Comment by Sketish** [comment]
It will be fixed with next update

Author: afgann
Message: Core/Spell: Fix Preparation not resetting Sprint cooldown.

**Comment by Kroutenberg** [comment]
Ok, thank you for your reply ! How often are there usually updates, to get an idea?

**Comment by Sketish** [comment]
Usually every wednesday, unless some critical fixes then its updated asap

**Comment by Kroutenberg** [comment]
Thank you for your reply and for your work ! good bye
