### ISSUE TITLE
Broken quest - Tokens of the Descendants

### ISSUE THREAD

**Issue by markmakrai** [gamefreedomgit/Maelstrom#3966]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The descendants held prisoner by the Skettis talonpriests are listed in this book. Gezzarak the Huntress, Garokk the Crystal Giant, the heretic known as Darkscreecher Akkarai and Vekkaz the Windrager. They will all need to be slain before Terokk returns to this world.

You will need the scrolls carried by the time-lost arakkoa and burn them at the summoning circles all over Skettis. Bring me a token from each one. These are powerful beings you will be facing; you would do well to bring friends.

**How to reproduce:**

**How it should work:**
After using ''Elixir of Shadows'', you should be able to receive the following loot form mobs - Time-Lost Scroll. Using 10 of the scrolls, you can summon each slain mentioned in the description however, you cannot click on the pile of skulls in the purple circles to 
summon the mobs which drop the items to complete the quest. 

It is a daily quest and part of a reputation to a flying mount so it would be much appreciated if it could be fixed. 

**Database links:**

**Comment by imbanoobqt** [comment]
I can confirm that pile of skulls are still bugged/unclickable and it is therefor impossible to complete the quest 
Also the quest is the only way to summon boss Terokk which can drop an unique appearance change item <Time-Lost Figurine> : [Transforms caster to have the appearance of a Skettis arakko]

**Comment by PanJanuszek** [comment]
works - 08.03.2024
