### ISSUE TITLE
Deadmines lumbering oaf boss bug

### ISSUE THREAD

**Issue by Abstractyyy** [gamefreedomgit/Maelstrom#3967]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you accidently time his death (Lumbering oaf / Helix gearbreaker boss, Deadmines HC) right when he picks someone up to slam them in to the wall. That person will be stuck hovering his dead body, in the animation you do when he's holding you to slam you in to the wall, until you die. You still take damage from his slam at around the time when it should have happned. You also can get bombs stuck to your chest and take damage from bombs on the ground that land in range of you.

**How to reproduce:**
Time his pickup and slam ability with his death. Don't know if it's only in the HC version but that's where it happned to me.

**How it should work:**
Not sure but feels like he should let go of you if he dies when holding someone.

**Database links:**

**Comment by Afgann** [comment]
fixed
