### ISSUE TITLE
owl's pet 

### ISSUE THREAD

**Issue by msfarasat** [gamefreedomgit/Maelstrom#3969]
Spell Name: Snatch 
Spell Information: The Bird Of Prey Grabs the enemy's Weapon With its talons, Disarming them For 10 Sec.
srry dear i cant give u Wowhead Because its Filter in my countery T_T
this spell did'nt Worked on 85 heros and don't Disarm Enemys.

**Comment by Sketish** [comment]
Use twinstar databse to provide what is spell name
https://cata-twinhead.twinstar.cz/
