### ISSUE TITLE
Mage [talent] Flame Orb and Dragon's Breath

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3971]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the target affected by disorientation from the dragon's breath ability stops receiving damage from the flame orb

**How to reproduce:**
use flame orb and dragon breath

**How it should work:**
Flame Orb should continue to deal damage (this damage is not considered direct)
 

**Database links:**
https://wowpedia.fandom.com/wiki/Flame_Orb
https://wowpedia.fandom.com/wiki/Dragon%27s_Breath

proof:
https://youtu.be/p667ZATEkPY?t=99
mage use dragons breath and orb, where we can see orb attack pet with disorientation
https://youtu.be/p667ZATEkPY?t=231 
https://youtu.be/p667ZATEkPY?t=641

**Comment by UltraNix** [comment]
Fixed.
