### ISSUE TITLE
Pet [minion] warlock, mage (dk)

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
summoning a new minion, should reset the cooldown on his abilities

**How to reproduce:**
use cd ur minion, after abandon him and summon new

**How it should work:**
resummon should reset cds.

As for the mage with water elemental, I'll look for a video, but this was described in Xandin's guide, I'll look in general. I don't know about death knight with raise dead idk how should be.

**Database links:**
https://wowpedia.fandom.com/wiki/Felhunter
https://wowpedia.fandom.com/wiki/Summon_Water_Elemental
https://wowpedia.fandom.com/wiki/Raise_Dead_(death_knight_ability)

proof for warlock:
https://youtu.be/7ibtrZdtJB8?t=470

about dk https://youtu.be/yiii5ultT_Q?t=112 resummon should not reset cds (if it official server in video)

**Comment by Pornoodemon** [comment]
I also wanted to draw attention to this but could not find proofs. Thanks to the author.
The warlock should re-summon a new pet every time without cd since it's a new demon with a new name and so on.

**Comment by Pornoodemon** [comment]
After fix
Core/Pets: Warlock pets should not save cooldowns to DB.
the problem was partially solved.
If you let go and then call the pet again, then its cd is reset.
But if you resummon the pet through the "Soulburn" spell as shown in the video cd remains, this is a very important point

**Comment by Pornoodemon** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/133828891/62b7909f-3ce5-4a49-a83b-983382e9859b

**Comment by UltraNix** [comment]
Fixed.
