### ISSUE TITLE
Mage ward does not proc Incanter's Absorption

### ISSUE THREAD

**Issue by Mercusz** [gamefreedomgit/Maelstrom#3975]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mage ward (ID543) does not proc Incanter's Absorption (ID44935), therefore not granting spell power per absorbed spell damage.

**How to reproduce:**
Use mage ward and get damaged by either arcane, frost or fire spells

**How it should work:**
Incarter's absorption should proc and give the mage Incanter's Absorption

**Database links:**

**Comment by Afgann** [comment]
fixed
