### ISSUE TITLE
Moonwell chalice effect drops when you deal damage or cast a spell (PTR)

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#3976]
**Description:**
Moonwell Chalice isnt working properly, everytime you either deal damage or cast a spell, you lose the mastery buff.

**How to reproduce:**
Equip and use the trinket, attack dummies.

**How it should work:**
It should work as every other trinket, you use it, and then the buff stays for its full duration

Moonwell chalice ID: 70142

**Comment by bonfax4** [comment]
Does not work like other trinkets as you say. If you move too far away from it you should lose the buff and you can't get it back by moving back in. Wowhead comment says the range is @30y.

**Comment by jlldarocha** [comment]
I forgot about the range being a thing for it, but i wasnt moving at all, The report is about the effect being lost after every action/damage instance. 

**dot ticks, pet attacks and spell casts are dropping the buff**.

**Comment by Afgann** [comment]
fixed
