### ISSUE TITLE
Impossible to cast the same spell several times in row with held Alt/Shift/Ctrl+ another key

### ISSUE THREAD

**Issue by webabey** [gamefreedomgit/Maelstrom#3977]
Hi guys. Let's imagine I have several binds with 1 repeated key: S, Alt-S, Shift-S. 
Spell on S works fine but when I cast other spells bind on Alt-S/Shift-S/Ctrl-S for ex, the spell on S is casting instead of a spell on Alt-S/Shift-S/Ctrl-S.
Perhaps if S is being hit several times whilst Alt is pressed and held, it can't be recognized like a new spell casting.

**How to reproduce:**
Set bind on F and Alt/Shift/Ctrl-F. Press and hold Alt/Shift/Ctrl at the same time clicking F with it reproducing casting the same skill several times. 

**How it should work:**
Based on other servers mechanics, the key with Alt/Shift/Ctrl + key on F/G/S for ex. should work even when the former is pressed and held. I don't think that every player press Alt/Shift/Ctrl+key and release it immediately to press again Alt/Shift/Ctrl, it's inconvenient.

Please look into this.

**Comment by webabey** [comment]
BTW, found the same thing but when I use bing Alt-S, somehow the key C is pushing instead.

**Comment by Sketish** [comment]
Well it look's like keyboard issue rather than in game bug

**Comment by webabey** [comment]
I've been playing on another server a month ago, there wasn't any issues the same kind tho
