### ISSUE TITLE
Glitchy Raid frames

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#3979]
https://www.youtube.com/watch?v=P3E-x2TU7KA

**Description:**
In the clip above, notice how when selecting friendly players, it selects different players you're not trying to select which occurs as players leave/enter BG's.  /Reload doesn't fix this issue, only relogging fixes this, but who's going to relog in the middle of a BG? This is also an issue in PvE environments sometimes, but not as frustrating as in BG's as a **healer.** 

**How to reproduce:**
Queue a random battleground, allow the BG to progress as players enter/leave you'll notice your unit frames become glitchy.

**How it should work:**
You should be able to select your intended friendly target through your unit frames.

**Database links:**

**Comment by webabey** [comment]
Oh yeah, this seems to be a global issue for other servers as well.
Want to add that if you type **/reload**, then the statistics button for BG on the map disappears. 
@Sketish could you please also consider this?

**Comment by Battlecryz** [comment]
@webabey Yes it is a global issue I should have stated that better.

**Comment by UltraNix** [comment]
@Battlecryz Name of addon?

**Comment by UltraNix** [comment]
I downloaded that addon and got no problems. Targeting via addons works okay for me.

**Comment by UltraNix** [comment]
@webabey Please, send to your Elvui version (if it's the addon showed on your video)
