### ISSUE TITLE
[QUEST] The Battle for Gilneas City - NPC teleports you to the end.

### ISSUE THREAD

**Issue by Ahumaya** [gamefreedomgit/Maelstrom#398]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The actual battle during The Battle for Gilneas City is completely skipped when talking to Krennan Aranas. He simply teleports you to the end and gives you quest credit.

https://user-images.githubusercontent.com/82483575/115634639-a2e86000-a2cf-11eb-9f19-755497dab19a.mp4

**How to reproduce:**
Attempt to complete The Battle for Gilneas City.

**How it should work:**
You should be able to participate in the actual Battle for Gilneas City.

**Wowhead links:**
https://www.wowhead.com/quest=24904/the-battle-for-gilneas-city

**Comment by Ahumaya** [comment]
Also, the area buff from this quest persists through the rest of the zone.

**Comment by Loken-coolguy** [comment]
Scripted event missing

**Comment by itsemmastone** [comment]
This issue has been resolved through commits that were related to rewriting the entire Gilneas zone, addressing all its issues and quests in the process.
