### ISSUE TITLE
threshold and mana burn [fear,ring of frost, hex]

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#3980]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
this ability:
Ring_of_Frost
Psychic_Scream
Hex
should break after first use Mana_Burn
**How to reproduce:**
use Mana_Burn in Ring_of_Frost Psychic_Scream Hex
**How it should work:**
Ring_of_Frost Psychic_Scream Hex should break after first hit Mana_Burn in 

**Database links:**
https://wowpedia.fandom.com/wiki/Ring_of_Frost
https://wowpedia.fandom.com/wiki/Psychic_Scream
https://wowpedia.fandom.com/wiki/Hex
https://wowpedia.fandom.com/wiki/Mana_Burn

Wrath of the Lich King [Hotfix](http://blue.mmo-champion.com/23/16474158165-recent-ingame-fixes--41609.html) (2009-04-30): Mana Burn now causes Spell shadow possession [[Fear]](https://wowpedia.fandom.com/wiki/Fear), Spell shaman hex [[Hex]](https://wowpedia.fandom.com/wiki/Hex) and Spell shadow psychicscream [[Psychic Scream]](https://wowpedia.fandom.com/wiki/Psychic_Scream) to break early when used.

bug after last fix dmg threshold

**Comment by UltraNix** [comment]
Mana Burn vs Psychic Scream:
![1](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d3383ffd-f24e-4077-b251-607e1cfe3598)

Mana Burn vs Hex:
![2](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ebd5b00d-9fd1-4e21-8a77-94dffe8ff3e9)

**Comment by UltraNix** [comment]
I see no info about Mana Burn breaking Ring of Frost.

**Comment by mipanka** [comment]
I test only ring of frost, hex and fear written for completeness so as not to miss anything.

**Comment by UltraNix** [comment]
As I stated above - both works okay.
And for Ring of Frost - provide confirmation.

**Comment by UltraNix** [comment]
No further info - closing.

**Comment by UltraNix** [comment]
No further info - closing.
