### ISSUE TITLE
Twilight Highlands quest [Twilight Skies] (H)

### ISSUE THREAD

**Issue by CrusaderArelius** [gamefreedomgit/Maelstrom#3981]
[//]: # (REMEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Jumping on the Zeppelin during [Twilight Skies] after the Zeppelin passes the zone border between Wetlands and the Twilight Highlands seems to flag your character as "falling", and deals damage accordingly. It seems to briefly turn it on right around the time you pass the border, and then starts dealing damage again right before the dragon spawns and grabs onto the Zeppelin.

Additionally, dying and being revived seems to de-spawn the Zeppelin and locks you out from completing the quest until you go back and re-do the flight.

**How to reproduce:** Just existing on the Zeppelin and jumping on the Zeppelin periodically does falling damage.

**How it should work:** Same as above.

**Database links:**
Idk if this is what this is asking for, but this is the quest in question. https://www.wowhead.com/quest=28849/twilight-skies

**Comment by Sketish** [comment]
Fixed

**Comment by Sketish** [comment]
Need to find a way to reproduce, I'm trying on ptr and no issues

**Comment by Palaz1** [comment]
> Need to find a way to reproduce, I'm trying on ptr and no issues

I have a pretty long clip from the Maelstrom server. The most I could come up with is when you're in Wetlands, and there is ground (not water) beneath you, you take damage like you jumped from the Zeppelin.

I wasn't able to reproduce this time of taking 2 jumps of 22k+ damage and dying. (maybe position in the zep may affect this?)

But I definitely had multiple spots where I took like ~6k fall damage while over the shallow part of the drowned reef (~20seconds)

https://www.youtube.com/watch?v=ZlNd0sbz7bc
