### ISSUE TITLE
You Are Rakh'likh Demon Quest

### ISSUE THREAD

**Issue by ajienjamil** [gamefreedomgit/Maelstrom#3983]
[//]: # (https://wowpedia.fandom.com/wiki/You_Are_Rakh%27likh,_Demon_(Classic)

**Description:**

You Are Rakh'likh Demon

**How to reproduce:**

**How it should work:**

after teleport in the top of mountain in The Rise Of Defiler at Badland, there must stone or item when we klik, razelikh appear and we must kill it 
**Database links:**

**Comment by MrTide** [comment]
can confirm, it used to work seems like npcs completely deleted
i would assume by developers and forgot to readd later to fix it

**Comment by PanJanuszek** [comment]
if you talk with ghost nearby the mountain he will teleport and npc's will appear
