### ISSUE TITLE
"the Camel-Hoarder" Title/Mount Bug

### ISSUE THREAD

**Issue by TheAndreski** [gamefreedomgit/Maelstrom#3985]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Heyo, I found the Grey Riding Camel mount on my main Blunts on Whitemane.. I then logged to my alts and realized the mount is account wide but the title isn't sadly.. I opened a ticket in game and was told to make a report here because I wouldn't be able to learn the mount on my alts if I did find the camel figurine again..

**How to reproduce:**
If you are able to grant my alts the title/achievement I'd really appreciate it <3

**How it should work:**
Thank you for your time

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
