### ISSUE TITLE
[PTR] Firelands bugged NPC

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#3987]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently in PTR there's an Egg Pile NPC that is under the map continuously spawning mobs. It is the one on the left side as you enter Alysrazor zone.
https://cata-twinhead.twinstar.cz/?npc=53795
https://cata-twinhead.twinstar.cz/?npc=54059

Only tested on 10NM, but assume its same in every other difficulty, can't test.

IMPORTANT NOTE! This also makes it impossible to pull Alysrazor if u wipe on her once since I assume she goes out of her LOS pit if u kill all NPCs. THE LOS zone also makes the infinite spawning mobs go EVADE inside the alys pit and I assume if u stack enough of them u can also crash the server (will add pic3 soon for example)

Note2: I think there might also be a 2nd fire phoenix under the map or just plain missing causing the following fire aoe.
**How to reproduce:**
https://youtu.be/yYfQ2hlCL3I
(example for note scenario)

**How it should work:**

**Database links:**
https://imgur.com/a/OXosdvg
https://imgur.com/a/IEND1d1

**Comment by Sketish** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3970
