### ISSUE TITLE
Guardian Spirit

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#3988]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Calls upon a guardian spirit to watch over the friendly target. The spirit increases the healing received by the target by 60%, and also prevents the target from dying by sacrificing itself.  This sacrifice terminates the effect but heals the target of 50% of their maximum health. Lasts 10 sec.

**How to reproduce:**
cast a spell on yourself

**How it should work:**
Should restore exactly 50% HP, but restores 120k+

**Database links:**
maybe some modifiers affect it, but this should not be

**Comment by UltraNix** [comment]
Fixed.
