### ISSUE TITLE
Blood dk - dancing rune weapon + heart strike

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3992]
Description:
Heart strike is supposed to hit up to 3 targets. Currently if you used Dancing Rune Weapon and use Heart Strike it will hit more targets than it should.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/1f90b05b-211a-4f10-b297-e1ac6fcdeafc)

**How to reproduce:**
Created a blood dk, pull 5 mobs and use dancing rune weapon and start spamming heart strike.

**How it should work:**
Copied Heart Strike from DRW should also hit up to 3 targets

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55050

**Comment by UltraNix** [comment]
Fixed.
