### ISSUE TITLE
 Warlock Pets HP

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3993]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock pets have too much HP and mana.
For example. Ölen Demonology Warlock  (Official server)
https://www.youtube.com/watch?v=rivxK2hLHZY
![HP_pet](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/1123af21-f84b-4e0e-9405-2b93cd1fa853)

For comparison

![HP_PET2](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/1fa987b0-eee9-487d-af1f-96aef4ec2fdf)

By normal math, a rough example of xn scaling can be calculated.

IMP 70% of max hp,

Felguard 75% of max hp,

Fel Hunter 72% of max hp,

The succubus did not get into the frame, but from my memory she had a little more HP than the imp 
most likely something around 71% of max hp.
The Voidwalker is unlikely to be found on any video. this pet is useless in pvp and is used very rarely in pve as a tank and it has the most HP. Most likely around 80% of max hp

As for mana, the average scaling is about 60% of the warlock's mana.
For warlock pets, mana is a practically inexhaustible resource; I don’t think it makes sense to consider the little + - 5% related to mana.

Other warlock pet stats work fine (Sp, Mastery(Demonology) Armor,Res,  and so on.

And also after the last changes, the Black Imp has only 2800 hp. This is a error.
![HP3](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/82d5ca32-1979-4e5c-99bc-012f597b4bf6)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#2947
