### ISSUE TITLE
Orders From Lady Vashj - quest item missing.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#3996]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After becoming friendly with Cenarion Expedition, trash mobs in Steam Vaults are supposed to drop Orders From Lady Vashj, the quest item that enables you to hand in Coilfang Armaments for reputation. However, it doesn't seem to drop at all. I've run through the dungeon numerous times on different characters, on both normal and heroic, but it just doesn't drop.

**How to reproduce:**
Idk, kill a lot of shit and loot a lot of shit until you realise it's never gonna drop?

**How it should work:**
It should drop with a fairly high rate after becoming friendly with CenEx.

**Database links:**
http://cata.cavernoftime.com/item=24367
https://cata.cavernoftime.com/npc=17721

**Comment by BalanCV** [comment]
Yep I tried doing this a long time ago as well until I realized the item drop and quest was removed in cataclysm.
https://cata-twinhead.twinstar.cz/?quest=9764

**Comment by Zeehra** [comment]
> Yep I tried doing this a long time ago as well until I realized the item drop and quest was removed in cataclysm. https://cata-twinhead.twinstar.cz/?quest=9764

Yet all other databases say the item still drops. And if the quest was removed, why would Coilfang Armaments still be dropping?

**Comment by BalanCV** [comment]
https://www.wowhead.com/quest=9764/orders-from-lady-vashj
Read the comments, it was removed entirely in 4.3
Armaments still dropping is just blizz not caring to remove em.
Caverns of time db is pretty bad in general and accurate in some specific cases compared to others.
Sadly ur only choice for rep is to repeatedly farm the dungeons.

**Comment by oldspices** [comment]
yeah the comments on those pages told me that it was removed and maybe a foresight by blizzard, that is why i suggested they add tokens for TBC rep like they did for WOTLK reps. would be nice.

**Comment by PanJanuszek** [comment]
quest removed
