### ISSUE TITLE
fix double items loot in some raids especially bh

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3997]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

all ppl do bh 18 and if 2 same items drop its a waste of loot
**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/9c9635bf-e10c-4ae3-846a-52831362c709)

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/eb454e8e-b149-4512-a789-b4d510e3282c)

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
and on bot 25 /bwd 25 sometime happens cho gall or nef to drop same 3 tokens like 3 pala/lock/priest and 0 war/sham/hunt or udud/dk/mage

**Comment by Sketish** [comment]
Duplicates can drop on 25, not a bug
