### ISSUE TITLE
Enchant Weapon - Hurricane

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#3998]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Minor bug but hurricane should stack with itself on 3 different sources.  Currently the spell source  (spell damage or healing with an ICD) and the off-hand proc share their buffs so it just gets refreshed. I can currently get 2 stacks only max as a rogue but 3 up at a time should be possible. 

**How to reproduce:**
Equipped only an off hand **with no poisons** and waited for the proc, stopped auto atacking and then used recuperate to proc the spell based buff and the buff gets refreshed rather than stacking.

**How it should work:**
You should be able to get one enchant per weapon if dual wielding and an extra from spells (heals or damage, wowhead reports recuperate from rogues proccing this ).

Spell source should have an ICD (50 sec according to wowhead), while the melee versions works with ppm as it does currently.

Source: 

https://www.wowhead.com/item=52760/enchant-weapon-hurricane#comments
https://cata-twinhead.twinstar.cz/?issue=10499

**Database links:**

**Comment by bonfax4** [comment]
Off hand proc chance seems very low too even while spamming shiv ( off hand attack ) with a slow weapon equipped. Could just be an rng thing

**Comment by bonfax4** [comment]
Also not 100% sure if heals and spell dmg share the same cd considering there's a warrior saying he managed to get 4 buffs at once on wowhead comments.

**Comment by Pornoodemon** [comment]
> Also not 100% sure if heals and spell dmg share the same cd considering there's a warrior saying he managed to get 4 buffs at once on wowhead comments. Early cata tho.

The fact of the matter is that these are comments of kata 4.0.3-4.0.6.
By the release of patch 4.3.4, everything turned upside down there.

**Comment by bonfax4** [comment]
@Sketish  Simcraft showing hurricane is also coded to have 3 different sources to proc
![77adc91fee76033f7504821bd35666ef](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/f355f22b-c5d4-441f-88bf-7fac8f93592e)

**Comment by UltraNix** [comment]
Fixed.
