### ISSUE TITLE
Shard of Woe - mana reduction for holy and nature school spells

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#3999]
**Description:**
4.3 nerf to trinket Shard of Woe was for all schools except holy and nature. It should reduce mana cost by 405 instead of 205.

**How to reproduce:**
Equip trinket shard of woe on any healer and check mana cost reduction

**How it should work:**
https://www.wowhead.com/news/latest-cataclysm-hotfixes-feb-15-182855#news-post-182855

**Comment by clam119** [comment]
I was wondering if the priority of this could be shifted to a higher priority. There are a significant number of Restoration Druids, Holy Paladins, and Holy Priests that have access to Shard of Woe, and the numbers are pretty significant to the mana throughput of the item. 🤔

**Comment by Polynomix** [comment]
"https://www.wowhead.com/news/latest-cataclysm-hotfixes-feb-15-182855#news-post-182855" this was a hotfix during t11, it got nerfed after in 4.3. Just look at how simulationcraft handle it. https://www.mmo-champion.com/threads/991915-Shard-of-Woe-PTR-Nerf
