### ISSUE TITLE
[Rogue] Bandit's Guile + Redirect issue

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4002]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bandit's Guile  is not properly transfering the cycle after the mob dies. Very annoying in dungeons, it starts a new cycle instead.

**How to reproduce:**

**How it should work:**
You should be able to transfer you're insight buff without a reset even if your previous target is dead.
Source: 

https://youtu.be/Lvn00CqI6x8?t=313
Scion dies with Green insight buff > Redirected 4 remaining combo points into Rag > Buff does no fall off and the cycle resumes

https://cata-twinhead.twinstar.cz/?issue=272

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=84654
https://cata-twinhead.twinstar.cz/?spell=73981

**Comment by UltraNix** [comment]
Fixed.
