### ISSUE TITLE
Summoned pets/Guardians do not inherit player's haste values

### ISSUE THREAD

**Issue by Memphis3220** [gamefreedomgit/Maelstrom#4004]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
*Cata* Summoned pets/Guardians (Summon Gargoyle, Summon Doomguard, Fire Elemental Totem) currently do not benefit from the player's haste values so they always do the baseline ammount of strikes as if the player has 0 haste (17 for Gargoyle, 20 for Doomguard)

**How to reproduce:**
As a DK or Warlock you can just summon your guardian without any haste procs or heroism, count the strikes and then use heroism and summon them again, they do the same ammount of hits.

**How it should work:**
On every other cataclysm server where i have played(other than Atlantiss i think) Circle,Apollo,Wowmortal,Athenas,ProjectNelth,Moonshard,Nemesis,Monster-wow,Molten-wow(Warmane) These pets have inherited the player's haste in order to fit extra casts in the duaration that they are active.
I have done extencive testing and on the Warlock's Doomguard scaling on other servers and in all of them for each 386 haste(3% haste) the Doomguard manages to fit a single extra cast in its duration, so instead of the 20 default casts with 3% total haste it does 21 casts. It is easily testable on other servers and im willing to provide extra proof if needed.

**Database links:**

**Comment by Sketish** [comment]
Please provide any retail videos or databse links

**Comment by Memphis3220** [comment]
I couldnt find any database references about the scaling of the Guardian pets, but ive found a retail guide from 12 years ago where they talk about the doomguard scaling: [https://www.mmo-champion.com/threads/1018028-Destruction-4-3-PTR-PvE-Guide](url) (You should NEVER use a Doomguard or Infernal without almost full buffs, they scaled tremendously with spell power and intellect. (Note, neither scale with %damage or %haste or %critical strike chance increases, thought they do scale from %spell power/%intellect or buffs that grant rating instead of a percent. (So they won't gain damage with bloodlust but a **proc from a haste trinket that grants 2000 haste raiting, they will**) Thus, the best time to use either creature is to summon him at the beginning of each fight, usually with a Volcanic Potion effect.)

**Comment by Memphis3220** [comment]
Another Retail guide, where they mention to use Doomguard when a haste trinket procs from the guild Insomnia(so they know what they were talking about): [https://www.mmo-champion.com/threads/1120365-Warlock-Tips-and-Tricks-and-Specific-Encounter-Guides-4-3](url) (4.2 [Insignia of the Corrupted Mind](http://www.wowhead.com/item=77991)

This trinket procs a huge amount of haste. The most important thing to do when using this trinket is to make sure you save your Doomguard until it procs, and then use it.)

**Comment by Memphis3220** [comment]
There is also this video from retail [https://www.youtube.com/watch?v=CDNBG4xKWKc&t=101s](url) where the doomguard is clearly visible, i have counted 36 casts which can be seen, maybe one or two ive missed, but that is far from the 20 casts of the baseline with 0 haste

**Comment by Pornoodemon** [comment]
As far as I understand, buffs that give speed in% do not work on them before summon. For example from bloodlust.
But if this effect is applied to him after the summon of the guard, then he should work.

**Comment by Memphis3220** [comment]
Nope its exactly the opposite, they should scale from the haste increase on the character before they are summoned, but the actual heroism buff should not be applied to the pet itself.

**Comment by Pornoodemon** [comment]
> Нет, это как раз наоборот, они должны масштабироваться от увеличения скорости персонажа до того, как они будут призваны, но фактический бафф героизма не должен применяться к самому питомцу.

Why then is it stated that - (So they won't gain damage with bloodlust but a proc from a haste trinket that grants 2000 haste raiting, they will)

**Comment by Memphis3220** [comment]
thats in the case of bloodlust being cast after the summon which would just immune on the Doomguard

**Comment by Pornoodemon** [comment]
> это в случае, если жажда крови разыгрывается после вызова, который просто невосприимчив к Стражу ужаса.

It's clear. I just read and write through a translator, so I can't understand well.

**Comment by bonfax4** [comment]
This has been discussed before. Only dk pets and guardians scale with haste % modifiers, dk ghoul even double dip these effects if both owner and pet get them and this was researched on apollo. Other guardians only snapshot haste rating but it's currently bugged as reported [here](https://github.com/gamefreedomgit/Maelstrom/issues/3926) for doomguard.

**Comment by Memphis3220** [comment]
Summon gargoyle should also snapshot haste upon being summoned, not just the Doomguard, i am not saying anything about the dk ghoul i didnt check if theres issues there.

**Comment by Memphis3220** [comment]
There is a video of Preach talking about how the gargoyle should snapshot aswell: [https://www.youtube.com/watch?v=Tf1LiwVwfTE](url) **14:30**

**Comment by bonfax4** [comment]
Reread what I typed. You're fighting ghosts right now. Gargoyle and army snapshots full haste % wich includes hero. Other class guardians only haste from haste rating. You're only correct about gargoyle on your initial post.

**Comment by BalanCV** [comment]
The way inheritance works on this server is mostly blizzlike because of older bugposts that were resolved.
Generally the only haste% buff Doomguard should ever inherit or apply on itself is Sinestra buff.
Also while inheritance is working properly, the scaling might be a bit off giving the illusion stuff isn't working. (according to post #3926  )

**Comment by UltraNix** [comment]
Garoyle:
0% haste:
![WoWScrnShot_072023_185624](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f846c627-c731-4101-934d-96db97150e62)

72% haste:
![WoWScrnShot_072023_185734](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b5d58bac-09a1-4cd7-bc0e-5ca57360cf3e)

Other pets/guardians already explained.
