### ISSUE TITLE
Fall damage is not mitigated after successfull charge.

### ISSUE THREAD

**Issue by Alpelle91** [gamefreedomgit/Maelstrom#4006]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warrior ability Charge does not prevent damage upon falling down from a hill and charging a target before landing. Even if the charge is successfull fall damage is taken in full. 

**How to reproduce:**
Drop from a high hill and charge a mob or a player down below before landing.

**How it should work:**
If the charge is successfull the fall damage should be mitigated.

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/139290313/2d65efd3-4e63-48a8-bde0-3d5896a4684b)

**Comment by UltraNix** [comment]
Fixed.
