### ISSUE TITLE
Icecrown Wotlk quests "Matchmaker" and "Generosity Abounds"

### ISSUE THREAD

**Issue by Frostycd** [gamefreedomgit/Maelstrom#4009]
**Description:**
in both quests you are controlling undead and have some tasks to do (but you don't get credit for it or it isn't working). In first one you are suposed to throw a rock at brutes near skeletons to start a fight but nothing happens, and in second one you don't get a credit for blowing up abominations.

**How to reproduce:**
Do quests

**How it should work:**
in first one after you throw a rock there should be a little fight betwen both mobs and you should get a credit for every fight started, and in second one you should get credit after taking bomb to abominations

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
