### ISSUE TITLE
[Rogue] Killing spree

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4010]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Often times when the the person you're targeting while performing killing spree dies, killing spree fails to perform attacks on other targets, but you still jump around. See it occasionally in dungeons. Might be related to player dropping auto attack when main target dies.

**How to reproduce:**

**How it should work:**

Going through wowhead and mmo champ forums i can't find a single rogue complaining about this being an issue at any point. I wil attempt to look for video proof but this issue is so specific that its gonna be hard to find.

**Database links:**

**Comment by bonfax4** [comment]
Can also kinda replicate this issue by targetting myself while killing spree is up. I perform less than 5 assaults

**Comment by bonfax4** [comment]
Here proof : 
https://youtu.be/8LeG4NIVBtI?t=77
He starts killing spree when his target has 5% health. Slow video down and look at his floating combat text and killing spree still performed 5 assaults (auto attacks stopped as expected but all killing spree hits went through)

**Comment by nwiest** [comment]
just found out maelstorm has a page here, glad to see someone already reported this. Surprisingly it has only happened to me 2 or 3 times. I have had this occur when the target that I teleport to dies before the attack lands. I was not targeting the mob I just referred to.

**Comment by Afgann** [comment]
fixed
