### ISSUE TITLE
[Shaman] Interaction between Lava Burst and Flame Shock

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#4012]
The check whether Flame Shock is on the target (for the purposes of making Lava Burst a critical hit) should occur when the spell lands, not when the cast is finished (you should be able to reapply Flame Shock during Lava Burst's travel time).

**Comment by bonfax4** [comment]
No. This was only possible in bfa. Up till then flame cast needed to be up on cast finish not hit.

[Cata](https://wowpedia.fandom.com/wiki/Lava_Burst?oldid=2984217)

> If Flame Shock is applied for the first time while Lava burst is traveling to the enemy (in other words, after Lava Burst has been cast), the 100% critical strike chance will not apply.
> The Flame Shock DoT only has to be active upon completion of casting Lava Burst. If the DoT wears off while the Lava Burst projectile is traveling, it will still crit.

[Patch 8.1 BFA](https://www.icy-veins.com/forums/topic/39730-patch-81-elemental-shaman-changes/)

> In-flight [Lava Burst](http://www.wowdb.com/spells/51505)Lava Burst will now benefit from [Flame Shock](http://www.wowdb.com/spells/188389)Flame Shock cast after it.

**Comment by Sketish** [comment]
Not a issue

**Comment by VirtualReign** [comment]
Huh. I'd never played past WoD at all yet I was sure that's how the interaction was in retail.

But fair enough, thanks for digging that up!
