### ISSUE TITLE
Bugged Quest 

### ISSUE THREAD

**Issue by TheZized** [gamefreedomgit/Maelstrom#4013]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
a quest that's supposed to be returned to a goblin npc but the npc is nowhere to e found the quest name is (Patchwork Command)
i think i need this quest to unlock a new state of twilight highlands like mount hyjal so i hope it gets fixed fast sorry i couldn't give a screen shot with the bug complain but the screenshot wasn't supported 
**How to reproduce:**

**How it should work:**
idk i was doing the whole area quest for rep and to unlock recipes 

**Database links:**

**Comment by Sketish** [comment]
Fixed with new TH release
