### ISSUE TITLE
Rare Spawn In Uldum is hyper-spawning WAY to fast

### ISSUE THREAD

**Issue by SeraphTV** [gamefreedomgit/Maelstrom#4014]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As I was farming Volatile Air, I found Armagedillo, the rare spawn in Uldum tonight, killed it and skinned it but after my first initial rounds of farming, I noticed it was spawned again. Killed it again, skinned it and waited, it spawned again. After doing this 5 times I recorded to see how long it took to respawn. Exactly 2 minutes from the time the skinning finished to the time it spawned again. Link to YT video will be provided.

I believe this is due to me skinning it causing it to despawn after and triggering a bug with the spawns? Something like that.

**How to reproduce:**
Kill the mob, Skin it, wait 2 minutes. 
Video Proof(Might still be processing): https://www.youtube.com/watch?v=KvHozcpWYNI

**How it should work:**
Kill the mob, Skin it, Wait 3-5 hours.

**Database links:**
https://www.wowhead.com/npc=50065/armagedillo#comments

**Comment by SeraphTV** [comment]
Here are Time stamps for despawn and respawn so you don't have to watch the entire video.
Despawn: 0:19
Respawn: 2:15

**Comment by Afgann** [comment]
fixed
