### ISSUE TITLE
Felwood - Purity From Corruption

### ISSUE THREAD

**Issue by StafordDev** [gamefreedomgit/Maelstrom#4016]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Felwood quest 'Purity From Corruption' is not available even if you complete both pre-requisites: 'Crying Violet' and 'Forces of Jaedenar'.

**How to reproduce:**
Complete both quests above and talk to Andalar Shadevale - he will not offer you 'Purity From Corruption'.

**How it should work:**
You should be able to accept 'Purity From Corruption' quest after you complete both 'Crying Violet' and 'Forces of Jaedenar'.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=28119
https://cata-twinhead.twinstar.cz/?quest=28116
https://cata-twinhead.twinstar.cz/?quest=28121
https://cata-twinhead.twinstar.cz/?npc=51664

**Comment by PanJanuszek** [comment]
fixed 10.01.2024
