### ISSUE TITLE
[Lost City of Tol'vir] Issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4017]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

General Hussam issues :

- [Traps](https://cata-twinhead.twinstar.cz/?spell=91259) seem to detonate instantly when spawned beneath a player's feet. Trap spawns should be random  and there should be some delay ( Seems to be about 2 seconds ) before they're triggerable. You can see the delay until they start glowing [here](https://youtu.be/8sV1kxJSLUQ?t=36). You can see a melee near the boss walk over a bomb that just spawned [here](https://youtu.be/mLSGmd-Rq64?t=71). Trigger range seems to be a little higher than it should too.

- Shockwave goes off before the ability finishes the cast and it shouldn't stay on it's full path ticking for it's full duration. It should work as a ground projectile going though the 4 paths. https://youtu.be/4x3gTyxJmUc?t=22

Lockmaw issues  :

- [Paralytic Blow Dart](https://cata-twinhead.twinstar.cz/?spell=89989) should only target 1 player at a time in both phases of the boss. Targets all 5 members currently.
- [Frenzied crocolisks](https://cata-twinhead.twinstar.cz/?npc=49311) spawn too often. This only seemed to occur after a wipe. According to this [video](https://www.youtube.com/watch?v=jQQX5PNxFXk) they seem to spawn in bursts of 28-30 seconds. (@0:33, @1:01, @1:32)
- Augh should not engage instantly after Lockmaw's death if you're far away enough. https://youtu.be/jQQX5PNxFXk?t=205

Siamat:

- [Lightning charge](https://cata-twinhead.twinstar.cz/?spell=91872) does not always go through when the servant dies. Could be a similar issue to [this](https://github.com/gamefreedomgit/Maelstrom/issues/3647) where interrupts on thunder crash are somehow school locking the npc and preventing the cast.

**Database links:**

**Comment by bonfax4** [comment]
@Afgann Shockwave still a bit wonky. It still does the tick on the ground thing when it shouldn't.

**Comment by whothatdog** [comment]
can I use this issue @UltraNix 

boss Siamat:
missing 'Tempest Storm' when minion die (green texture cloudy on ground)

when Siamat using Wailing Winds it knock you off platform.
it shouldn't in this phase should be 'invisible walls' prevent from falling.

**Comment by bonfax4** [comment]
https://youtu.be/9YDYzDZlXCs?t=93 See a person getting knocked off here. But to be fair i went through like 12 vids and only found a person falling outside 1 time. Here at least 1 person gets thrown out 90% of the time lol

**Comment by whothatdog** [comment]
> https://youtu.be/9YDYzDZlXCs?t=93 See a person getting knocked off here. But to be fair i went through like 12 vids and only found a person falling outside 1 time. Here at least 1 person gets thrown out 90% of the time lol

lol nice video.
I found myself few times on Whitemane standing on middle of platform before casting the ability and getting knocked off
and one time pulled NPCs cause of it.

the Dungeon Journal say "knock **around** the platform" I haven't played Blizzard I experienced pservers using invisible walls prevent falling off..

**Comment by UltraNix** [comment]
`when Siamat using 'Wailing Winds' it knock people off platform - it shouldn't.
this phase should be 'invisible walls' prevent from falling.`
This is not a bug - you can fall from platform durin this spell.

**Comment by UltraNix** [comment]
Fixed.
