### ISSUE TITLE
The following item is being sold at the wrong price

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#4018]
The Warsong Battle Tabard is selling for less than it should, as shown in the attached image.

![Captura de pantalla -2023-07-19 20-20-10](https://github.com/gamefreedomgit/Maelstrom/assets/139988125/0e0e6ecb-0560-4263-95e4-51f2fb848a5d)

In the [following link ](https://cata-twinhead.twinstar.cz/?item=19505)you can see a database that corroborates the price at which said object should be.

The [following link](https://wowpedia.fandom.com/wiki/Warsong_Battle_Tabard?oldid=2684915) shows that in the 2011 World of Warcraft Cataclysm date the price is the same as what is shown on https://cata-twinhead.twinstar.cz/?item=19505

Item in both horde and alliance should be set to 2,059 honor points

**Comment by Afgann** [comment]
fixed
