### ISSUE TITLE
Quest "Enraged Spirits of Fire and Water" (quest ID 10458) is unobtainable

### ISSUE THREAD

**Issue by Ssauronn** [gamefreedomgit/Maelstrom#4019]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest, "Enraged Spirits of Fire and Water", in Shadowmoon Valley cannot be obtained from the quest giver, Earthmender Torlok. The quest does not appear at all after completing the prerequisite quest, "The Hand of Gul'Dan", and instead after completing the prerequisite, Earthmender Torlok just repeats the same dialogue box.

**How to reproduce:**
Complete the very first quest in the quest chain, "The Hand of Gul'Dan", given by Earthmender Sophurus in Shadowmoon Valley. The quest ends at Earthmender Torlok. From that point on, the next quest, "Enraged Spirits of Fire and Water" is bugged out and cannot be obtained from Earthmender Torlok.

**How it should work:**
After turning in "The Hand of Gul'Dan" to Earthmender Torlok, the next quest, "The Hand of Gul'Dan", should immediately be available from the same NPC.

**Database links:**
https://www.wowhead.com/quest=10680/the-hand-of-guldan
https://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
