### ISSUE TITLE
[Paladin] Light of Dawn 

### ISSUE THREAD

**Issue by Tigroska** [gamefreedomgit/Maelstrom#4021]
**Description:**
Light of Dawn ability heals 7 targets instead of 6.
![sss2](https://github.com/gamefreedomgit/Maelstrom/assets/125566782/aba06050-a824-4547-86f2-1af6f7d74764)

**How it should work:**
https://cata-twinhead.twinstar.cz/?spell=85222

**Comment by Tigroska** [comment]
![test3](https://github.com/gamefreedomgit/Maelstrom/assets/125566782/c8a2af27-690b-473b-b43c-3a65c1ac9034)

**Comment by BalanCV** [comment]
I don't think this is a bug because the 7th heal target its the caster itself and it doesn't get counted by the spell limit.
As u can see from the DB link the spell is composite of 2 effects of Heal. The first heal is 4-6 targets limited and the 2nd heal effect is self cast and part of the spell.

**Comment by UltraNix** [comment]
6 targets from AoE effect and you = 7 targets (including caster).
No bug.

**Comment by Tigroska** [comment]
> I don't think this is a bug because the 7th heal target its the caster itself and it doesn't get counted by the spell limit. As u can see from the DB link the spell is composite of 2 effects of Heal. The first heal is 4-6 targets limited and the 2nd heal effect is self cast and part of the spell.
> 
> Effect #1 | (10) HealValue: 1 Radius: 30 yards (10) HealValue: 1
> 
> Effect #2 | (10) HealValue: 1

Yes, thats what I thought at first too but then i found this comment on wowhead 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/125566782/13b6c0ea-78f4-48cb-9a22-55f8cefee8f6)
LoD can and will heal yourself unless other people need it more. - So if you are full hp and others 6+ dont it will heal 7 targets or 6?

**Comment by Tigroska** [comment]
> 6 targets from AoE effect and you = 7 targets (including caster). No bug.

This one is from Retail Cata
https://youtu.be/cH0aY4QxHYU
during the entire video you will not find any 7 heals from LoD , check th red line Screenshot from 0:40
![image](https://github.com/gamefreedomgit/Maelstrom/assets/125566782/2bd56647-bbe9-446e-964c-f95539c18281)

**Comment by Warlorc** [comment]
> > 6 targets from AoE effect and you = 7 targets (including caster). No bug.
> 
> This one is from Retail Cata https://youtu.be/cH0aY4QxHYU during the entire video you will not find any 7 heals from LoD , check th red line Screenshot from 0:40 ![image](https://user-images.githubusercontent.com/125566782/254946671-2bd56647-bbe9-446e-964c-f95539c18281.png)

Are you sure he uses the glyph? Might try with and without, maybe just the glyph isnt working proberly

**Comment by UltraNix** [comment]
Fixed.
