### ISSUE TITLE
Fire and Earth elementals vs large bosses

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4022]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

On Sinestra, fire and earth elemental run a marathon to go behind the boss to start attacking which takes like 30s off of uptime
On Al'akir, if summoned during P1, Fire elemental and earth elemental sometimes just don't do anything. I don't know if its because of the boss hitbox or the static shock but what i know is that they're supposed to do damage.

**How to reproduce:**

Sinestra -> pop elementals and watch them run all the way to the egg then to behind the boss
Al'akir -> pop elementals and watch them chill besides you doing nothing. (Sometimes they do attack, just pull again)

**How it should work:**

I don't really care about those bosses anymore because FL is soon, but i care what might happened on large bosses in FL (mainly Ragna)

**Database links:**

**Comment by Afgann** [comment]
fixed
