### ISSUE TITLE
Test Firelands 07/20/2023

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#4023]
Firelands

We tested fireland this 07/20/2023 at 6:00 p.m.

- NM:

Bethilac :

Only a display bug in phase 2, the boss remains suspended in the air, but attackable.

Shannox :

Crystal trap : triggers only once in three and therefore can be easily dodged. (Only triggers rarely.)
At times, if a player jumps, the trap that spawns on the player stays in the air and is therefore not active.

Baleroc :

No problems to report in the limits of the tests.

Alysrazor :

The two large firebirds in the middle before aggro Alysrazor remain displayed throughout the fight and block visibility (You have to change difficulty to make them disappear.).
Tornado phase is not correct, hitbox is ridiculously small and damage almost zero.
 Those who are in the air and have the fly buff take falling damage when the tornado phase begins.

Ryolith :

The boss has to go into the lava instead of near it to 'drink' (which is a strat fail, so slightly less punitive for mistakes.).
Display of lava flows, normally, this displays a pillar of fire which indicates that a flow is about to start.
Screen : https://media.discordapp.net/attachments/1112784503677665361/1131726625243934770/image.png

Majordomo :

_Only the feline phase was seen because we were too few for the scorpion phase_
Nothing to report.

Ragnaros :

The hammer that hits the ground is not correctly displayed, it can theoretically hit on the right side but finally the damage is on the left side (Sulfuras Strike)
(to be checked but the lava wave from the sulfuras strike only hits the player once even when taken full force : the player should "surf" with it (being hit multiple times in a row if still in wave). (Normally this should be untenable unless a player, for example a mage, uses transfer.))

Seeds of fire do or do no damage even close. Logically, we must move away to lower the damage but there even close, it is tenable. (/!\ to be checked)

-----

HM:

Bethilac :

[Cinderweb Worker] can spawns anywhere when it should always spawn in the same location (to the left of the room when entrance is behind you). (Problem encountered: The worker spawns at the same time as and on top of the small spiders => instant 10 stacks = instant wipe and players can’t do anything about it)

[Young Cinderweb Spider], must jump on a player if they are within 5m of them. There what happens is that it auto-attacks the player.

(to be checked) [Congested Spawn] if killed should spawn a pool of poison, which is not the case.

Baleroc :

Nothing to report

Alysrazor :

Same as in NM on problems.
During phase 1 (air), boss should not fly at low altitude, cleave and drop 10 feathers in a line (that’s for normal mode only). 
On heroic, boss should stay high in the air during all air phase and drop 10 feathers at a point below it after each storm.

Meteorites when they are not killed and they explode into small meteorites against the wall, they can continue even past the mountains (Normally they roll on the other side of the explosion, to the middle of the arena).

Ryolith :

Same as in NM 

Majordom :

The feline only jumps on the tank which make the encounter not winnable, it should targets casters and heals prio.

Ragnaros :

Same as in NM for displays bugs
+ : [Interval: inhabitants of the flames!], in HM the sons of flame have to spawn kinda randomly (you can see it on every HM ragna video on yt), not like in NM where there is a predefined pattern. 
Here HM sons of flame spawn like in normal mode.
P4: [Dreadflame] too little flame on the ground, may be a multiplication issue (to be more precise : dreadflames is a punitive mechanic because they spread exponentially : if 1 dreadflame is left unextinguish it become 2 then 4 then 8... here the boss will spawn dreadflames 2 by 2 (which is okay) but then those dreadflames will spread linearly and not exponentially : 1 then 2 then 3...) 
This mechanic alone is a major issue because it makes phase 4 way easier than it should be. 
Also, boss should spawn his dreadflames 2 by 2 in random locations in the entire area, with often 2 spawns a bit far from each other, sometime a bit close but never adjacent, here it happens twice in a single try that 2 dread spawns adjacent to each other, resulting in 2 non-threatening spawns.

Trash : No loot just gold coins, no items.

Cordialy,
Vaell, GM of Whitemane.

**Comment by Sketish** [comment]
Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3970
