### ISSUE TITLE
7/20 - Twilight Highlands Quest "Far from the Nest"

### ISSUE THREAD

**Issue by Lollrus** [gamefreedomgit/Maelstrom#4024]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest "Far from the Nest" requires looting 6 Vermilion eggs that are on the ground. The eggs are not lootable.

**How to reproduce:**
Attempted abandoning and re-accepting quest, reloaded game, no change.

**How it should work:**
Eggs should be lootable.

**Database links:**

**Comment by itsemmastone** [comment]
Verified on the PTR realm; it's working perfectly after the recent fix. I am closing it now.
