### ISSUE TITLE
Deep Freeze & Fingers of Frost

### ISSUE THREAD

**Issue by Xianji** [gamefreedomgit/Maelstrom#4025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Deep Freeze will when used on bosses consume two Fingers of Frost instead of one. 
_NOTE: this does not apply to stunable targets, then it will only consume one as normal_

**How to reproduce:**
Get two Fingers of Frost(i.e. pet's Freeze), then use Deep Freeze on a stun-immune target(such as any dungeon boss)

**How it should work:**
It should consume only one charge, allowing for the Frost Mage PvE opener to be Freeze > Deep Freeze > Cold Snap > Deep Freeze

**Database links:**
Only source I can find that confirms this is this guide from 2010:
https://www.mmo-champion.com/threads/813785-Kuni-s-Frost-Mage-PVE-Guide-(Cataclysm)

**This is quoted from the link above:**
"The opening sequence of a frost mage involves the use of cold snap. This spell resets all cooldowns that you use to DPS, providing absurd front loaded burst.
Frostfire orb > freeze > deep freeze > icy veins > cold snap > deep freeze"

**Comment by UltraNix** [comment]
#5531
