### ISSUE TITLE
Auto TurnIn Quests - Deathwing's Fall + Silvermarsh Rendezvouz

### ISSUE THREAD

**Issue by svenbledt** [gamefreedomgit/Maelstrom#4026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Quests mentioned in the Title should auto Turnin on completion.
That doesnt work as intended. i had to fly back to the core of deepholm.

**How to reproduce:**
Do the quests.

**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/8340034/f7560c0f-d0f9-499c-9cab-69d8894fa172)

**Database links:**
https://www.wowhead.com/quest=27007/silvermarsh-rendezvous
https://www.wowhead.com/quest=26258/deathwings-fall

**Comment by svenbledt** [comment]
Maybe this helps.

`UPDATE 'mop_world'.'quest_template' SET 'Method' = 2, 'Level' = 82, 'MinLevel' = 81, 'MaxLevel' = 0, 'ZoneOrSort' = 5042, 'Type' = 0, 'SuggestedPlayers' = 0, 'LimitTime' = 0, 'RequiredClasses' = 0, 'RequiredRaces' = 0, 'RequiredSkillId' = 0, 'RequiredSkillPoints' = 0, 'RequiredMinRepFaction' = 0, 'RequiredMaxRepFaction' = 0, 'RequiredMinRepValue' = 0, 'RequiredMaxRepValue' = 0, 'PrevQuestId' = 26245, 'NextQuestId' = 26256, 'ExclusiveGroup' = 0, 'NextQuestIdChain' = 26256, 'RewardXPId' = 4, 'RewardOrRequiredMoney' = 62000, 'RewardMoneyMaxLevel' = 157200, 'RewardSpell' = 0, 'RewardSpellCast' = 0, 'RewardHonor' = 0, 'RewardHonorMultiplier' = 0, 'RewardMailTemplateId' = 0, 'RewardMailDelay' = 0, 'SourceItemId' = 0, 'SourceSpellId' = 0, 'Flags' = 327820, 'Flags2' = 0, 'SpecialFlags' = 0, 'MinimapTargetMark' = 0, 'RewardTitleId' = 0, 'RewardTalents' = 0, 'RewardArenaPoints' = 0, 'RewardSkillId' = 0, 'RewardSkillPoints' = 0, 'RewardReputationMask' = 0, 'QuestGiverPortrait' = 33189, 'QuestTurnInPortrait' = 33189, 'RewardPackageItemId' = 0, 'RewardItemId1' = 0, 'RewardItemId2' = 0, 'RewardItemId3' = 0, 'RewardItemId4' = 0, 'RewardItemCount1' = 0, 'RewardItemCount2' = 0, 'RewardItemCount3' = 0, 'RewardItemCount4' = 0, 'RewardChoiceItemId1' = 0, 'RewardChoiceItemId2' = 0, 'RewardChoiceItemId3' = 0, 'RewardChoiceItemId4' = 0, 'RewardChoiceItemId5' = 0, 'RewardChoiceItemId6' = 0, 'RewardChoiceItemCount1' = 0, 'RewardChoiceItemCount2' = 0, 'RewardChoiceItemCount3' = 0, 'RewardChoiceItemCount4' = 0, 'RewardChoiceItemCount5' = 0, 'RewardChoiceItemCount6' = 0, 'RewardFactionId1' = 1135, 'RewardFactionId2' = 0, 'RewardFactionId3' = 0, 'RewardFactionId4' = 0, 'RewardFactionId5' = 0, 'RewardFactionValueId1' = 4, 'RewardFactionValueId2' = 0, 'RewardFactionValueId3' = 0, 'RewardFactionValueId4' = 0, 'RewardFactionValueId5' = 0, 'RewardFactionValueIdOverride1' = 0, 'RewardFactionValueIdOverride2' = 0, 'RewardFactionValueIdOverride3' = 0, 'RewardFactionValueIdOverride4' = 0, 'RewardFactionValueIdOverride5' = 0, 'PointMapId' = 0, 'PointX' = 0, 'PointY' = 0, 'PointOption' = 0, 'Title' = 'Deathwing\'s Fall', 'Objectives' = 'Go to Deathwing\'s Fall in Deepholm.', 'Details' = 'The Twilight\'s Hammer involvement in the disappearance of the World Pillar fragment makes complete sense.  Let us hope that we can act swiftly enough to recover it.$B$B<Maruut places his hand on your shoulder.>$B$BI\'ve established a spiritual bond with you.  We should be able to communicate while you remain in Deepholm.$B$BGo to Deathwing\'s Fall to the southeast and investigate the Twilight\'s Hammer operation there.', 'EndText' = 'Deathwing\'s Fall reached', 'OfferRewardText' = 'This must be where the world pillar fragment was brought.  Let\'s have a closer look. ', 'RequestItemsText' = '', 'CompletedText' = '', 'RequiredSourceItemId1' = 0, 'RequiredSourceItemId2' = 0, 'RequiredSourceItemId3' = 0, 'RequiredSourceItemId4' = 0, 'RequiredSourceItemCount1' = 0, 'RequiredSourceItemCount2' = 0, 'RequiredSourceItemCount3' = 0, 'RequiredSourceItemCount4' = 0, 'RewardCurrencyId1' = 0, 'RewardCurrencyId2' = 0, 'RewardCurrencyId3' = 0, 'RewardCurrencyId4' = 0, 'RewardCurrencyCount1' = 0, 'RewardCurrencyCount2' = 0, 'RewardCurrencyCount3' = 0, 'RewardCurrencyCount4' = 0, 'QuestGiverTextWindow' = 'Our spirits are now linked so that we may communicate while you\'re away.', 'QuestGiverTargetName' = 'Maruut Stonebinder', 'QuestTurnTextWindow' = 'They must\'ve brought the fragment here!', 'QuestTurnTargetName' = 'Maruut Stonebinder', 'SoundAccept' = 890, 'SoundTurnIn' = 878, 'DetailsEmote1' = 0, 'DetailsEmote2' = 0, 'DetailsEmote3' = 0, 'DetailsEmote4' = 0, 'DetailsEmoteDelay1' = 0, 'DetailsEmoteDelay2' = 0, 'DetailsEmoteDelay3' = 0, 'DetailsEmoteDelay4' = 0, 'EmoteOnIncomplete' = 0, 'EmoteOnComplete' = 0, 'OfferRewardEmote1' = 0, 'OfferRewardEmote2' = 0, 'OfferRewardEmote3' = 0, 'OfferRewardEmote4' = 0, 'OfferRewardEmoteDelay1' = 0, 'OfferRewardEmoteDelay2' = 0, 'OfferRewardEmoteDelay3' = 0, 'OfferRewardEmoteDelay4' = 0, 'WDBVerified' = 15595 WHERE 'Id' = 26258;
`

`UPDATE 'mop_world'.'quest_template' SET 'Method' = 2, 'Level' = 82, 'MinLevel' = 81, 'MaxLevel' = 0, 'ZoneOrSort' = 5042, 'Type' = 0, 'SuggestedPlayers' = 0, 'LimitTime' = 0, 'RequiredClasses' = 0, 'RequiredRaces' = 0, 'RequiredSkillId' = 0, 'RequiredSkillPoints' = 0, 'RequiredMinRepFaction' = 0, 'RequiredMaxRepFaction' = 0, 'RequiredMinRepValue' = 0, 'RequiredMaxRepValue' = 0, 'PrevQuestId' = 26260, 'NextQuestId' = 27010, 'ExclusiveGroup' = 0, 'NextQuestIdChain' = 27010, 'RewardXPId' = 3, 'RewardOrRequiredMoney' = 41000, 'RewardMoneyMaxLevel' = 104700, 'RewardSpell' = 0, 'RewardSpellCast' = 0, 'RewardHonor' = 0, 'RewardHonorMultiplier' = 0, 'RewardMailTemplateId' = 0, 'RewardMailDelay' = 0, 'SourceItemId' = 0, 'SourceSpellId' = 0, 'Flags' = 134807684, 'Flags2' = 0, 'SpecialFlags' = 0, 'MinimapTargetMark' = 0, 'RewardTitleId' = 0, 'RewardTalents' = 0, 'RewardArenaPoints' = 0, 'RewardSkillId' = 0, 'RewardSkillPoints' = 0, 'RewardReputationMask' = 0, 'QuestGiverPortrait' = 33189, 'QuestTurnInPortrait' = 33189, 'RewardPackageItemId' = 0, 'RewardItemId1' = 0, 'RewardItemId2' = 0, 'RewardItemId3' = 0, 'RewardItemId4' = 0, 'RewardItemCount1' = 0, 'RewardItemCount2' = 0, 'RewardItemCount3' = 0, 'RewardItemCount4' = 0, 'RewardChoiceItemId1' = 0, 'RewardChoiceItemId2' = 0, 'RewardChoiceItemId3' = 0, 'RewardChoiceItemId4' = 0, 'RewardChoiceItemId5' = 0, 'RewardChoiceItemId6' = 0, 'RewardChoiceItemCount1' = 0, 'RewardChoiceItemCount2' = 0, 'RewardChoiceItemCount3' = 0, 'RewardChoiceItemCount4' = 0, 'RewardChoiceItemCount5' = 0, 'RewardChoiceItemCount6' = 0, 'RewardFactionId1' = 1135, 'RewardFactionId2' = 0, 'RewardFactionId3' = 0, 'RewardFactionId4' = 0, 'RewardFactionId5' = 0, 'RewardFactionValueId1' = 3, 'RewardFactionValueId2' = 0, 'RewardFactionValueId3' = 0, 'RewardFactionValueId4' = 0, 'RewardFactionValueId5' = 0, 'RewardFactionValueIdOverride1' = 0, 'RewardFactionValueIdOverride2' = 0, 'RewardFactionValueIdOverride3' = 0, 'RewardFactionValueIdOverride4' = 0, 'RewardFactionValueIdOverride5' = 0, 'PointMapId' = 0, 'PointX' = 0, 'PointY' = 0, 'PointOption' = 0, 'Title' = 'Silvermarsh Rendezvous', 'Objectives' = 'Go to the Upper Silvermarsh in Deepholm.', 'Details' = 'Excellent work, $n.  We know exactly where the meeting location is.$B$BThe Upper Silvermarsh is a mercury swamp to the east of here.  It\'s normally only inhabited by elementals and occasional stone troggs, but our scouts have seen some Twilight activity in the region.$B$BMake your way there and let\'s find a way to eavesdrop on the Forgemaster\'s meeting.', 'EndText' = 'Upper Silvermarsh reached', 'OfferRewardText' = 'This is the place.  Our scouts confirmed the presence of high-ranking Twilight officers nearby as well as potential trogg hunting parties. Be on the lookout, $n. ', 'RequestItemsText' = '', 'CompletedText' = '', 'RequiredSourceItemId1' = 0, 'RequiredSourceItemId2' = 0, 'RequiredSourceItemId3' = 0, 'RequiredSourceItemId4' = 0, 'RequiredSourceItemCount1' = 0, 'RequiredSourceItemCount2' = 0, 'RequiredSourceItemCount3' = 0, 'RequiredSourceItemCount4' = 0, 'RewardCurrencyId1' = 0, 'RewardCurrencyId2' = 0, 'RewardCurrencyId3' = 0, 'RewardCurrencyId4' = 0, 'RewardCurrencyCount1' = 0, 'RewardCurrencyCount2' = 0, 'RewardCurrencyCount3' = 0, 'RewardCurrencyCount4' = 0, 'QuestGiverTextWindow' = 'We\'re familiar with the meeting location.', 'QuestGiverTargetName' = 'Maruut Stonebinder', 'QuestTurnTextWindow' = 'We\'ve arrived.', 'QuestTurnTargetName' = 'Maruut Stonebinder', 'SoundAccept' = 890, 'SoundTurnIn' = 878, 'DetailsEmote1' = 0, 'DetailsEmote2' = 0, 'DetailsEmote3' = 0, 'DetailsEmote4' = 0, 'DetailsEmoteDelay1' = 0, 'DetailsEmoteDelay2' = 0, 'DetailsEmoteDelay3' = 0, 'DetailsEmoteDelay4' = 0, 'EmoteOnIncomplete' = 0, 'EmoteOnComplete' = 0, 'OfferRewardEmote1' = 0, 'OfferRewardEmote2' = 0, 'OfferRewardEmote3' = 0, 'OfferRewardEmote4' = 0, 'OfferRewardEmoteDelay1' = 0, 'OfferRewardEmoteDelay2' = 0, 'OfferRewardEmoteDelay3' = 0, 'OfferRewardEmoteDelay4' = 0, 'WDBVerified' = 15595 WHERE 'Id' = 27007;`

**Comment by Afgann** [comment]
fixed
