### ISSUE TITLE
Bestial Wrath

### ISSUE THREAD

**Issue by powercrystal** [gamefreedomgit/Maelstrom#4027]
**Description:**
if you try to use Bestial Wrath to break from paladin's repentance it says you can't use that while stunned,didn't try it with cyclone yet.
Edit : doesn't work with Gouge too
**How to reproduce:**
cast repentance on BM hunter and use bestial wrath (The Beast Within sub-talent is needed to break the CC's)

**How it should work:**
Since Wotlk expansion patch changes : Bestial Wrath and Ability hunter beastwithin [[The Beast Within]](https://wowpedia.fandom.com/wiki/The_Beast_Within) changed to function like PvP Trinkets, removing any movement impairing effects and giving immunity to these effects for 10 seconds. The tooltip doesn't say this, but it also now breaks all forms of CC that a PvP trinket would break (including Cyclone, Sap, etc.).

**Database links:**
https://wowpedia.fandom.com/wiki/Bestial_Wrath
Edit: found these videos so far https://www.youtube.com/watch?app=desktop&v=XmsUQZWqSQs&ab_channel=JohnDaniel
time 0:22 slow from dk
time 2:28 rogue cheap shot
time 3:10 dk slow+warrior stun
time 5:37 druid cyclone
time 8:35 mage deep freeze
https://www.youtube.com/watch?app=desktop&v=5qx2a0_xmFg&ab_channel=JohnDaniel
time 7:47 feral slow (deep wounds)
https://www.youtube.com/watch?app=desktop&v=X9jqRLTgcLU&ab_channel=RandomPeopleISH
Kazzak PvP server---time 4:32 where he speaks about using Bestial Wrath as a trinket=breaks any stun/slow/snares etc
also gathered the informations from one "blizzlike" server where they fixed Bestial Wrath according to these videos and few more comments.

**Comment by Sketish** [comment]
Please find any retail video as proof

**Comment by djesic** [comment]
Everything but Cyclone should be able to be removed.

**Comment by djesic** [comment]
Experienced a bug where I could not use it during shadow priests Psychic Horror

**Comment by djesic** [comment]
Also with Ring of Frost

**Comment by Afgann** [comment]
fixed
