### ISSUE TITLE
[QuestID 27836] Stopping the Spread quest object not interactable

### ISSUE THREAD

**Issue by Demynnfire** [gamefreedomgit/Maelstrom#4028]
# Stopping the Spread quest can't be completed

### Description:

Slitherer Eggs are not able to be destroyed. 
Interacting with the eggs gives the error message "You can't open that".

### How to reproduce:

Just do the quest

### How it should work:

Slitherer Eggs should be able to be destroyed by interacting with them

### Database links:
https://www.wowhead.com/quest=27836/stopping-the-spread
https://www.wowhead.com/object=206390/slitherer-egg

**Comment by UltraNix** [comment]
@Demynnfire Tested today and it works for me. Still bugged for you?

**Comment by UltraNix** [comment]
No further info - closing.
