### ISSUE TITLE
Deterrence vs improved counterspell

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4029]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hunter spell Deterrence doesnt deflect Mage improved counterspell (talent)

**How to reproduce:**
Hunter cast deterrence, and a mage with arcane talent improved counterspell use it on hunter while deterrence is up.

**How it should work:**
Deterrence should deflect all spells and casts of that sort, improved counterspell should not go through deterrence. 

**Database links:**

**Comment by Kenniflopper** [comment]
Also you can get Felhunter spell lock, and warrior gag order silence through deterrence, so its not just counterspell.

**Comment by Kenniflopper** [comment]
All these 3 needs to be fixed ^^

**Comment by Kenniflopper** [comment]
@UltraNix any news on this?

**Comment by Kenniflopper** [comment]
@UltraNix ??

**Comment by bigticketx** [comment]
Bump,
This is actually gamechanging bug
Since is everyone is abusing it

As person above said,detterence should deflect everything

**Comment by Mongo69** [comment]
Yep,please fix this

**Comment by WhitemaneSylah** [comment]
@Sketish  request upgrade priority from medium to high due to length issue is outstanding

**Comment by Afgann** [comment]
fixed
