### ISSUE TITLE
Rare elite trash respawns every 1 minute after the server has passed 24 hours of uptime

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#4033]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rare elite trash respawns every 1 minute after the server has passed 24 hours of uptime

**How to reproduce:**
Wait 24 hours without crashing and farm rare elites every 1 minutes

**How it should work:**
He should have more respawn time

**Database links:**
https://www.wowhead.com/fr/npc=50086/tarvus-le-vil > 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/140123486/3452e6e4-32ec-4ed6-a90f-aa8050faf6be)

**Comment by itsemmastone** [comment]
Fixed in revision: https://github.com/gamefreedomgit/gamefreedom-cata/commit/c76c9627e7110e4f32fa021046c835f4ae323229
