### ISSUE TITLE
glyphe de prompte guérison

### ISSUE THREAD

**Issue by Lichdow** [gamefreedomgit/Maelstrom#4037]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** la glyphe de prompte guérison du druide restauration ne marche pas

**How to reproduce:** utiliser la glyphe dans le système de glyphe et essayer d'utiliser le sort

**How it should work:** le sort prompte guérison ne devrait pas avoir besoin de consommer un effet du sort Récupération ou Rétablissement 

**Database links:** 
![Capture d'écran 2023-07-23 093332](https://github.com/gamefreedomgit/Maelstrom/assets/140306467/07ed89e2-7d12-47a1-ac14-6160cfcafe1d)

**Comment by Sketish** [comment]
Translate to english pls

**Comment by Lichdow** [comment]
**Description:** Restoration Druid's glyph of swift healing does not work

**How to reproduce:** use the glyph in the glyph system and try to use the spell

**How it should work:** the swift heal spell should not need to consume an effect of the Recover or Restore spell

**Comment by Sketish** [comment]
Checked on live server, swiftmend is not consuming rejuvenation or regrowth hot from target
