### ISSUE TITLE
(Global) Pets

### ISSUE THREAD

**Issue by powercrystal** [gamefreedomgit/Maelstrom#4039]
**Description:**
If the player is mounted, his pets are aggroying aggresive npcs.

**How to reproduce:**
Tried it with npcs in Tol Barad but can be done with any other aggresive npc.

**How it should work:**
Pets shouldn't aggro aggresive npcs if the player is mounted,they should be considered "inactive" since you can't control them(give them commands) until you dismount.

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=10907
first sentence of the global mechanics (i didn't search for any videos yet as of it is obviously known mechanics)

**Comment by UltraNix** [comment]
Fixed.
