### ISSUE TITLE
The Innkeeper's Daughter not being the same as Hearthstone for Whitemane+

### ISSUE THREAD

**Issue by Akayso** [gamefreedomgit/Maelstrom#4041]
**Description:**
The Hearthstone gathered from Archaelogy (The Innkeeper's Daughter) does not pop up the menu for teleportation options if you have Whitemane+

**How to reproduce:**
By clicking The Innkeeper's Daughter ^^

**How it should work:**
Same as regular Hearthstone Whitemane+ option

**Comment by Afgann** [comment]
fixed
