### ISSUE TITLE
Warlock - Conflagrate No Targets?

### ISSUE THREAD

**Issue by InstantZzz** [gamefreedomgit/Maelstrom#4043]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, I am InstantZ and I have recently joined the Maelstrom. I currently playing as a Warlock (Level 16) with the Destruction Spec whose signature ability is the Conflagrate spell. The spell was automatically added to my bar but was greyed out. I had assumed that I manage to drag a spell that I had not learned yet onto my bar. I have come to the realization that the spell is simply not functioning for me.

Attached below are 3 images; showing my level 16 and level 10 character with the chat log and my selected class specialization. 

**How to reproduce:**
Create a Warlock and level it up to level 10 and then select the Destruction Spec. Gain the Conflagrate spell and have it greyed out, unable to cast.

**How it should work:**
After reaching level 10 and then selecting the Destruction Spec, you should be able to cast the Conflagrate spell.

**Database links:**

![No Conflagrate 2](https://github.com/gamefreedomgit/Maelstrom/assets/103078788/96c523f3-fa9b-4e80-888d-c71533b2ebd5)
![No Conflagrate 3](https://github.com/gamefreedomgit/Maelstrom/assets/103078788/f74a76c3-1645-4803-9d1c-8ab193b972eb)
![No Conflagrate](https://github.com/gamefreedomgit/Maelstrom/assets/103078788/f4d819ef-98f3-4f8d-abdd-c978ba3b9034)

**Comment by Pornoodemon** [comment]
immolatemust be applied to the target in order to be able to use it.

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/08f7f848-0c7f-402d-81f5-e48b9629f42d)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7406b127-ad16-47cd-b57f-1732ee1263f3)

**Comment by InstantZzz** [comment]
Yeah, I have come the realization that I thought that I could read when I really could not.
