### ISSUE TITLE
Feign Death

### ISSUE THREAD

**Issue by powercrystal** [gamefreedomgit/Maelstrom#4044]
**Description:**
If you aggro one npc from the group, use feign death and there are another npcs nearby they will aggro on you even though you are still feigning death.

**How to reproduce:**
https://www.youtube.com/watch?v=R-SfEzi4f54

**How it should work:**
All the npcs that are nearby should automatically reset if you have active Feign Death.
Feign Death is a level 32 hunter ability. It causes the hunter to fall to the ground and pretend to be dead for up to 6 minutes. This clears the hunter's threat, leading mobs to either attack the next-highest target on their threat list or, if no other target is available, drop combat altogether. It also prevents nearby mobs from noticing the hunter as long as it remains active.

**Database links:**
https://wowpedia.fandom.com/wiki/Feign_Death

**Comment by UltraNix** [comment]
Fixed.
