### ISSUE TITLE
iron hall (magmus boss) in BRD is bugged doing perma combat because the flames dont turn off

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4045]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
iron hall (magmus boss) in BRD is bugged doing perma combat because the flames dont turn off causing a HUGE pain in the ass because people often die to it then have to run allllll the way back, its a huge moral killer because youre so close to the end often groups fall apart here unless they are used to the bug which makes it more annoying for new players because yea... 

**How to reproduce:**
just go through the hall

**How it should work:**
flames should turn off after boss dies also no combat bug shoud happen but i think the flames cause it anyways

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 10.05.2024
