### ISSUE TITLE
mount hyjall music in feralas

### ISSUE THREAD

**Issue by sarunas863** [gamefreedomgit/Maelstrom#4048]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
mount hyjall music from cataclysm starting zone is playing in feralas jungle while im leveling at level 39-40.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
really?  wtf and why u open thread for this?

**Comment by sarunas863** [comment]
wow so developers are toxic as the players too i see. i found this bug
and asked in general chat in your discord they redirected me to this to put
the bug up so i did , and you just write me WTF ? your server is full of
bugs , unfinished zones ,quests and players that are really toxic writing
********** with !!!!! left and right. i liked the server at first but now i
see for what it really is bye.

2023-08-05, št, 02:12 xmrshoot ***@***.***> rašė:
