### ISSUE TITLE
Dark simulacrum holy shock interaction

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#4049]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Using holy shock while under dark simulacrum should remove the buff and award to spell to dk, here it doesnt. 
Why is this important?
Because you wanna give a "bad spell" to DK instead of a "good one", so it impact pvp a lot

**How to reproduce:**
Use holy shock while under effect of dark sim.

**How it should work:**
Holy shock among other spells should be copyable, as far as im aware most of mana costing spells should be copyable

**Database links:**
Source from 2011
https://www.dual-boxing.com/threads/37454-Dark-Simulacrum

**Comment by Afgann** [comment]
fixed
