### ISSUE TITLE
Core bugg, cast bars

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#4050]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Casting a spell and swapping target mid cast, removes the cast bar.

**How to reproduce:**
Example: Cast cobra shot on a dummy, change target asap, notice the cast bar dissapearing.

**How it should work:**
Cast bar should stay regardless of target selection.

**Database links:**
Check any wow exapnsion.

**Comment by UltraNix** [comment]
Tested - everything seems to be okay.
