### ISSUE TITLE
Core bugg, Spell max range leeway

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#4051]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Starting a spell cast at a max range of spell and its target moving an extra yard results in spell being canceled.

**How to reproduce:**
Example:
Casting Divine light at 40yards and target moving to 41 yard makes spell unable to complete, saying out of range.

**How it should work:**
Casted and channeled spells should get minor range increase after starting the cast/channel. According to formulas about 10% increase for casted spells and 20% for channeled spells

**Database links:**
https://www.reddit.com/r/classicwow/comments/chf071/extended_spell_range_when_someone_goes_a_little/
(Can find plenty more by a simple google search, but theres a nice answer here)

**Comment by Sketish** [comment]
Please provide any proof from cataclysm retail videos

**Comment by Stega23** [comment]
This exists in every iteration of wow from release, it would be easier if some of you has acess to classic or retail to test it yourself, resarching such a specific thing on video might be really annoying.

**Comment by Stega23** [comment]
https://youtu.be/eJKjm0iBDbM?t=699 Cast goes trough even tho target is out of range
https://github.com/TrinityCore/TrinityCore/issues/15375
This existed/exists in every wow expansion.

**Comment by Afgann** [comment]
fixed
