### ISSUE TITLE
 Army of the Dead, Death Knight

### ISSUE THREAD

**Issue by Trandyill** [gamefreedomgit/Maelstrom#4053]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The army of the dead does not take over, or incorrectly takes over the characteristics of the death knight. The army must adopt strength, speed and accuracy, but even at 8% from the owner, the army still misses. The blows themselves were 250-300, which was weak even for a lich king. Please check what you have with this.

**How to reproduce:**
To call an army without procs and with procs, there is almost no difference, although it should fill the numbers much higher, especially with a set of speed caps

**How it should work:**
ghouls should correctly adopt the characteristics of the owner
https://www.wowhead.com/ru/spell=42650/%D0%B2%D0%BE%D0%B9%D1%81%D0%BA%D0%BE-%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D1%8B%D1%85#english-comments

**Database links:**
https://www.noob-club.ru/index.php?topic=7774.0
![WoWScrnShot_072623_131031](https://github.com/gamefreedomgit/Maelstrom/assets/109137114/48b7474a-4924-4f78-8377-04c3d08bc530)
The first screenshot is calling an army with only a bugle, no procs.
![WoWScrnShot_072623_134500](https://github.com/gamefreedomgit/Maelstrom/assets/109137114/6b0a248c-bd37-4f1b-8c1a-06a3ab4bca9c)
Second screenshot during action: 15% strength from weapon enchantment + two trinkets for honor (912 strength and 1520 strength)

**Comment by Sketish** [comment]
Provide any retail logs from cataclysm that will confirm that dmg of army is too low
because
https://youtu.be/Y0NDk-QAg4o?t=13
8 ghouls did 2809-3361 dmg so its 350-420 per swing in dragon soul gear

**Comment by bonfax4** [comment]
Yh dmg seems fine. Hit to expertise thing is a bug to every pet class still I believe.

**Comment by UltraNix** [comment]
Hit to expertise also looks okay.
My hit:
![WoWScrnShot_082523_183529](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d073ce4a-39b5-427b-9094-bef8c5bbe80b)

And AoD auras:
![WoWScrnShot_082523_183542](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9d487ab8-402b-4c82-9c27-edeb64c86d29)

In red circle you can see that pet has aura with 28 expertise. It means that pets reduced enemy's dodge chance by 7%

About the AoD hit:
![WoWScrnShot_082523_185950](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ff2d5266-c05d-4ed1-a459-9895960622aa)
Takes 8% from my DK.
