### ISSUE TITLE
TBC mining nodes respawn time seems way too high, maybe same for herbs. 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4054]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

not only are they not seemingly all spawning but the ones that do it seems like its over 4 hours and should be 1 hour? IDK but all i know is that everyone i ever have talked to who mines outlands complains about it so its not a matter of bots taking the ore because also there is never more than scraps on the auction house. 
**Description:**
i think i have seen this posted before maybe it was just in discord  so im posting here just incase.

**How to reproduce:**

**How it should work:**
should be alot more in general . 

**Database links:**

**Comment by Sketish** [comment]
Please provide specific name what nods are spawning too long

**Comment by oldspices** [comment]
adamantite , fel iron , khorium , Eternium

heres a list from the top down a little ways https://www.wowhead.com/tbc/items/trade-goods/metal-and-stone/group-by:level
 also if you can check the times on tbc herbs heres a list i found https://www.wowhead.com/tbc/items/trade-goods/herbs/group-by:level

**Comment by oldspices** [comment]
but i think its not JUST times, its amount of spawns that are up at one time.... idk if one has to do with the other but yea

**Comment by Afgann** [comment]
fixed
