### ISSUE TITLE
Blind immune to stuns

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4055]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently you are immune to stuns for a short amount of time after blinking.

**How to reproduce:**
https://streamable.com/hjh11c

**How it should work:**
Blinking should not make you immune to stuns.

**Database links:**

**Comment by Kenniflopper** [comment]
Blink* i mistyped. :)

**Comment by oldspices** [comment]
its this way on wotlk classic idk

**Comment by bonfax4** [comment]
@Sketish mipanka is correct. You're immune to stuns as long as the buff is up which should be less than a second according to [this](https://wowpedia.fandom.com/wiki/Blink?oldid=2914868)

**Comment by Sketish** [comment]
Please provide any proof from retail

**Comment by ussj10** [comment]
https://youtu.be/V3rUa4QUCDw?t=368
At 6:11 Swifty charges immediately after mage blinks his throwdown, there is no immune.
