### ISSUE TITLE
Contrición

### ISSUE THREAD

**Issue by Zaraelh** [gamefreedomgit/Maelstrom#4057]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://cata-shoot.tauri.hu/?spell=81749
**Description:  este talento Contrición del sacerdote disciplina lo que hace es sanar a los aliados el 100% del daño infligido con tu punición y fuego sagrado en un radio de 15m del objetivo enemigo, el bug es que no esta contando el radio de los 15m y no esta llegando las curaciones a todos los demás aliados, esto sucede porque no se esta tomando en cuenta que debería ser el alcance de combate del enemigo seleccionado y se tendrá problemas por ejemplo como jefes de Ragnaros, Ultraxión, Lord Piroclasto entre muchos, esto se implemento en el servidor original en el parche 4.3 (dejaré el link), lo que implemento blizzar fue, Contrición tomará en cuenta el alcance de combate del enemigo seleccionado al calcular el rango, lo que permitirá su utilización contra criaturas grandes como Ragnaros y Ala'kir **
**Database links:**
https://wow.fandom.com/es/wiki/Parche_4.3.0

**Comment by Sketish** [comment]
Please translate to english

**Comment by Zaraelh** [comment]
https://cata-shoot.tauri.hu/?spell=81749
What this Discipline Priest's Atonement talent does is heal allies for 100% of the damage inflicted with your smite and holy fire within a 15m radius of the enemy target, the bug is that it is not counting the 15m radius and is not The healings reach all the other allies, this happens because it is not taking into account what the combat range of the selected enemy should be and there will be problems, for example, such as bosses of Ragnaros, Ultraxion, Lord Pyroclast among many, this was implemented in the original server in patch 4.3 (I'll leave the link), what blizzar implemented was, Atonement will take into account the combat range of the selected enemy when calculating the range, allowing it to be used against large creatures like Ragnaros and Ala'kir
https://wow.fandom.com/es/wiki/Parche_4.3.0

**Comment by Sketish** [comment]
So what's the bug? Atonement is working on Alakir right now

**Comment by Zaraelh** [comment]
You are not understanding me, Mr. GM, the problem is not whether you are working well in alkiar, the problem is that the range of the contrition talent that you have from the enemy target to the allies is not being counted correctly.
I will try to explain it better, the bug is that when calculating the scope of the contrition it is only doing it with the range that the priest has, but it should not be like that, the scope of the contrition must be calculated with the range that the priest has. enemy, not with the range that the priest has.
That's why I put this link (https://wow.fandom.com/es/wiki/Parche_4.3.0), because the blizzards put in the patch notes that the range of contrition would be calculated like this, giving an example that this would allow the discipline priest to heal more easily on bosses like Ragnaros and Ala'kir.
I don't know if now I managed to understand the bug that I want to report.

**Comment by jlldarocha** [comment]
Iirc this change was made so the range calculation begins on the outside of their hit box, rather than the center of the unit. its a big difference against huge bosses like the one he mentioned.

**Comment by Zaraelh** [comment]
Thank you very much Mr. Gm, the difference is really noticeable not only in big bosses, but also in dungeons.

**Comment by Zaraelh** [comment]
A question, Mr. Gm, when calculating the range, did you do it with the selection diameter or with the radius? because it should be with the selection diameter, because when you select the target you select the whole target not just a part.

**Comment by UltraNix** [comment]
On big bosses, the radius is calculated from the center of it: 100yards + its combat reach + 15yards.
On other bosses, it's just 15 yards.

**Comment by Zaraelh** [comment]
It seems to me that it should be 100 yards + the combat that the enemy reaches + 15 yards, because there are problems with other small bosses and this change should be in general, both in adds and in large and small bosses, because the difference is felt and I think there will be very poor performance when Alma de Dragón comes out. In this video we can see how the contrition reaches everyone because its reach is greater than what is fixed now.
https://www.youtube.com/watch?v=9qhd3CFo_Bk&t=234s
because this change should also be in small and large adds, because if you notice in the video in bosses like blackhorn the atonement reaches everyone when you hit the adds, you can also see this in the last boss in Deathwing when the tentacles arrive The atonement to everyone will also be noticed in heroic and normal Zon'ozz.
I want to emphasize that it is 100 yards + THE COMBAT RANGE OF THE ENEMY + 15 yards
This is what it says in the patch notes is the range that the enemy has.
https://wowpedia.fandom.com/wiki/Patch_4.3.0

**Comment by Zaraelh** [comment]
> On big bosses, the radius is calculated from the center of it: 100yards + its combat reach + 15yards. On other bosses, it's just 15 yards.

**Comment by UltraNix** [comment]
Fixed.
