### ISSUE TITLE
RDF satchel of helpful goods item pool looks bugged

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4058]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when completing RDF and getting satchel, the possible items that spawn is looking bugged. I Have noticed this at every level and have thoroughly tested it at the 46-55 range  on two characters.

on my 49 druid i am trying to get of stamina item but only get bandit / etc ( see photo) 
on my 49 pala i only get of stamina(for boots) and other physical stats but no items including intellect. 

looks like maybe this issue only applies to boots?

**How to reproduce:**
test RDF satchel on different classes 

**How it should work:**
it should be having decent chance to drop all the different types of loot.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=52002#reward-of
![image](https://github.com/gamefreedomgit/Maelstrom/assets/26885524/1fa67a31-4991-48ce-be2a-b0999431e015)

**Comment by UltraNix** [comment]
Properties/suffixes are random.
