### ISSUE TITLE
More Random Dungeon Finder issues

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#4059]
1. After entering a random heroic dungeon (Blackrock Caverns) via the dungeon finder I'd gotten a prompt informing me that it was a dungeon in progress, and that "0/5 bosses were defeated".

Eventually we found out none of the bosses were available at all. The event for the last boss looked like it wasn't triggered (there were some Warden mobs standing there, but no Ascendant Lord Obsidius and the 3 adds that usually accompany him).

Regardless of the particular dungeon-specific bugs, players should not get saved to a dungeon unless they actually defeated a boss, regardless of it being in progress or not, especially since bugs like these are still plentiful.

Edit:
I just entered another heroic dungeon (Shadowfang Keep) with this same issue (0/5 bosses defeated), declined participation and still got saved to the dungeon too.

2. After people leaving / being voted out of the party it's possible for the dungeon finder to "stall", where the button to confirm re-queueing gets greyed out and the party is stuck unable to find a replacement (and it's not even rare, happened a couple of times now the past 2 days, most recently after one person quit, the replacement quit, and one got voted out for going offline - of the 3 remaining none of us were able to queue us up again).

3.  Often when a player leaves/is removed from a dungeon, the game isn't letting the replacement into the dungeon saying the dungeon is full.

4. Sometimes a random heroic dungeon won't award Valor Points. Just happened to me upon completion of ZG.

Edit: Had it happen again in a Blackrock Caverns run. Neither Justice nor Valor Points were awarded after completing the dungeon.

**Comment by UltraNix** [comment]
@VirtualReign Poke me on Discord.

**Comment by UltraNix** [comment]
No further info - closing.
