### ISSUE TITLE
Freezing Trap & Scatter Shot

### ISSUE THREAD

**Issue by powercrystal** [gamefreedomgit/Maelstrom#4062]
**Description:**
After using Freezing Trap/Scatter Shot hunter doesn't stop auto attacking the target so it breaks right after you apply the control if you keep the npc/player in the target

**How to reproduce:**
https://www.youtube.com/watch?v=KBBm9IHb_sI

**How it should work:**
hunter should stop auto attacking the target after applying freezing trap/scatter shot
hunter's pet stops attacking the target after using these spells so this part works as intended

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=18871

**Comment by Sketish** [comment]
Please provide any retail video it should work like this

**Comment by Sketish** [comment]
No respond
