### ISSUE TITLE
Cho'gall: Conversion not interrupted by sleep and disorient effects

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4063]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Like the title says these 2 effects do not interrupt worshipping. As such Hunter has no interrupts he can use on this fight since scatter shot is disorient and wyvern sting is sleep. (trap works but you'd rather keep the cd for more important things during the fight)

**How to reproduce:**
Scatter or wyvern conversion targets and it won't break the effect. rogue blind probably doesn't work either if its the same class spell as disorient.

**How it should work:**
https://www.wowhead.com/npc=43324/chogall#comments:id=1440822
You can see this comment listing scatter shot as working interrupt as proof

**Database links:**

**Comment by Afgann** [comment]
fixed
