### ISSUE TITLE
taunt and pet

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4064]
1.taunt does not work on pets
2.Must work
3.https://prestige-gaming.ru/_holy_paladin_by_raits_4_3-t25704.html  man's guide from the official server, find the line where he talks about taunt

Многие считают, что нельзя найти применение таунту в PvP, но они ошибаются. Паладин может очень успешно и продуктивно использовать эту способность разными способами которые я опишу ниже. Прежде чем это сделать, перечислю 2 таунта которые есть у паладина. Это [[Праведная защита]](http://ru.wowhead.com/spell=31789) и [[Длань возмездия]](http://ru.wowhead.com/spell=62124). Теперь обо всем по порядку.

[[Праведная защита]](http://ru.wowhead.com/spell=31789) - снимает с дружественной цели мобов, касательно арены, снимает естественно только пэтов и прислужников. Лично я предпочитаю использовать ее стандартно, в макросе на Шок, который представлен выше в гайде. Способность не стоит маны, не имеет ГКД, использование ее через макрос полностью себя оправдывает, иногда рандомно снимает контроль, стаунчивает гаргулью и т.д.
[[Длань возмездия]](http://ru.wowhead.com/spell=62124) - таунт воздействующий непосредственно на враждебную цель. Конкретно у этой способсности действительно достаточное количество способов применения чтобы описать их.
На данный момент, большинство варлоков держат свою собаку на том таргете, в который играют. Это осложняет отфир пэта. Дело в том, что у способности [[Изгнание зла]](http://ru.wowhead.com/spell=10326) радиус действия всего 20 ярдов, тогда как у Длани возмезния 30, а Праведной защиты вообще 40. С помощью таунта, можно снимать с вашего тиммейта собаку и затем сфиривать ее не меняя при этом позиции / не подставляясь под контроль.

Таунт также можно использовать, чтобы снимать с себя разнообразный контроль. Для примера, приведу возможность снятия с себя хантовского скаттера ([Дезориентирующего выстрела](http://ru.wowhead.com/spell=19503/scatter-shot)). Непосредственно перед получением скаттера, вы можете стаунтить хантовского пэта, тогда, при получении дизориента пэт собьет с вас контроль. Тоже самое можно сказать и о таунте маговских имаджей ([Зеркальных изображений](http://ru.wowhead.com/spell=55342)) во время шипа. Другое дело, что подобные “триксы” работают далеко не всегда, сильно зависят от пинга и удачи, но использовать их все равно необходимо. У меня возникали моменты, когда я выходил из блаинда, таунтом варлоковской собаки играя против RLS, нет ничего невозможного.

Еще один вариант использования Длани возмездия, это введение в комбат противников. Имея достаточно большой рейдж в 30 ярдов, способность становиться идеальным вариантом чтобы самому входить в комбат, играя в билде без дополнительного увеличения дальности джаджа. Через длань, можно также вводить в комбат рогу / ферала в попытке рестелса, если джадж на кулдауне.

**Comment by UltraNix** [comment]
Fixed.
