### ISSUE TITLE
Catseye Elixir Bug

### ISSUE THREAD

**Issue by VincentADK** [gamefreedomgit/Maelstrom#4065]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Screenshot: https://imgur.com/a/avvBXIg
I am reporting this for illnasty from discord.

**Description:**
Catseye Elixir is a gGuardian Elixir that increases stealth detection, and it's improperly stacking on top of flasks (which state in their descriptions that they are both a Battle and Guardian Elixir)!

**How to reproduce:**
Get an Elixir (that is a Battle and Guardian Elixir) and then try using the Catseye Elixir on top of it. 
It shouldn't stack in that case.

**How it should work:**
It shouldn't stack with other flasks that are both Battle and Guardian Elixirs

**Database links:**
https://cata-twinhead.twinstar.cz/?item=10592

**Comment by Afgann** [comment]
fixed
