### ISSUE TITLE
[QuestID 29237][Horde] Voodoo Zombies (Zandalari Menace quest chain)

### ISSUE THREAD

**Issue by Demynnfire** [gamefreedomgit/Maelstrom#4066]
# Voodoo Zombies

**Description:**
Killing Hideaway Zombies does not give credit to quest

**How to reproduce:**
Kill any Hideaway Zombie while on the quest

**How it should work:**
Killing the zombies should make Bwemba "purify" them and give credit for saving them

**Database links:**
https://www.wowhead.com/quest=29237/voodoo-zombies

**Video proof**
https://streamable.com/fg192m

**Comment by zhorabzhora** [comment]
got the same issue

**Comment by oqoobo** [comment]
Got the Same issue - Killing Zombies summons survivors as per Quest description, but no credit.

**Comment by UltraNix** [comment]
#4562
