### ISSUE TITLE
Lunar Shower not working

### ISSUE THREAD

**Issue by Tdotsavage** [gamefreedomgit/Maelstrom#4073]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Lunar Shower not working as intended for balance druid. The talent specifically states that while under the effect of Lunar shower, moonfire generates solar energy, however in game it is currently generating lunar energy. 

**How to reproduce:**
press moonfire with lunar shower talent

**How it should work:**
moonfire should generate solar energy, not lunar energy

**Database links:**

**Comment by Mercixx** [comment]
Noticed this issue too. [Lunar Shower] do not working as intended

**Comment by Kenniflopper** [comment]
when is this getting fixed @Afgann ?

**Comment by bonfax4** [comment]
@Afgann  Guys some guy linked here video proof that this is in fact intended and correct and that it should go towards lunar. https://cata-twinhead.twinstar.cz/?issue=21210

**Comment by UltraNix** [comment]
Already fixed.
