### ISSUE TITLE
black magic doesnt proc at all 

### ISSUE THREAD

**Issue by tmo123456** [gamefreedomgit/Maelstrom#4074]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
black magic just doesn't proc at all 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
