### ISSUE TITLE
Critical Core: % damage stacks multiplicative instead of additive

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4077]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As title says, works fine on the first % modify effect, but as soon as you start stacking multiple % damage INCREASE OR DECREASE the calculations are wrong.
This affects most classes for the worse since 20% dampen can even become 25% dampen. 

Tested through the dampen effect in heroic raids -20%:
Example 1 Survival Hunter: No % dmg increase by default so 100% before entering heroic raid, 80% after dampen as intended because only 1 % modifier is applied

Example 2 Assasination Rogue: +20% damage from talents so 120% before entering hc raid, 96% after dampen because of effect 1 (+20%) and effect 2 (-20%) are calculated incorrectly.
Note: Obviously this becomes even more jumbled up as you add multiple class talents and raid buffs such as 3% ret/mage/hunt

**How to reproduce:**
Rogue scenario:
https://imgur.com/a/jRGXfVl
https://imgur.com/a/UMVaPTz

Hunter scenario:
https://imgur.com/a/KQbffiX
https://imgur.com/a/e9ruBXc

**How it should work:**
100% + 20% - 20% = 100% (not 96% lol)
^this is one example, the more modifiers you add to the base the more unpredictable the result is.

**Database links:**

**Comment by jlldarocha** [comment]
Its also working like this during metamorphosis. With my current gear it goes from 175% to 140%.

Inside raid: 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/2d54c9f5-1845-4345-95aa-af6e3df939e8)

Outside:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/24c84905-e29f-4a66-b20d-d5b9d84e905d)

**Comment by VirtualReign** [comment]
Your math is wrong, the calculations seem fine.

How do you calculate 80% of 120%?
120% * 0.8 = 96%

How do you calculate 80% of 175%?
175% * 0.8 = 140%

**Comment by Sketish** [comment]
Not a bug
