### ISSUE TITLE
Darkmoon Faire Sayge buff incorrectly giving strength buff,

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4079]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you gain Strength buff from Sayge, you gain lower amount than you should.

It says increases strength by 10%,

**How to reproduce:**

**How it should work:**

**Database links:**
![WoWScrnShot_073123_224620](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/9d799c80-137d-4220-9b53-f2e3d539822c)
4426 str no buff
![WoWScrnShot_073123_230022](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/e9070b99-8d00-4fdc-b7ad-88bea1671784)
5356 strength with buff flask and dudu buff.

lets do the math.

4426 + 300 = 4726, 

15% of 4726 is 708.9

in total i should have 5435 str and i have 5356, 79 str lower than it should be.

**Comment by UltraNix** [comment]
That buff increase your base str (from items, etc.) and not applying to other str buffs (e.g. Mark of the Wild increases your total str).
