### ISSUE TITLE
[QUEST] Don't Forget About Us

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Maelstrom#4080]
**Current behaviour**:
You are able to auto-complete the quest after you pick it up.

**Expected behaviour**: 
Should not be able to auto-complete it until you talk to Tharek in Kharanos
https://www.wowhead.com/quest=24493/dont-forget-about-us

**Comment by PanJanuszek** [comment]
https://youtu.be/n1-MZqw6fqw?feature=shared&t=194

It works the same as on video.
