### ISSUE TITLE
Darkmoon Faire Sayge buff incorrectly giving stamina ( buff )

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4082]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sayge buff for stamina is not giving 10% increased stamina.

**How to reproduce:**

**How it should work:**

**Database links:**

![WoWScrnShot_080123_141226](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/ca5095c1-96b1-472e-9e4b-bee5ec3c490d)
no buff 119759
![WoWScrnShot_080123_141831](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/b75aa3fb-220d-4937-8aed-6573fade5a67)
with buff 127263

10% of 119759 is 11975,9 

so 119759 + 11976 = 131735

**Comment by UltraNix** [comment]
Same as #4489 4079
