### ISSUE TITLE
When you report a player in a bg for spamming you get disconnect

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4083]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi,
When you report a player in a bg for spamming you get disconnect from the server.

**How to reproduce:**

**How it should work:**

**Database links:**
Please fix this bug...

**Comment by UltraNix** [comment]
#3130
