### ISSUE TITLE
Warlock's felhunter incorrectly breaks CC effects upon taking damage.

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4084]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I just finished an Arathi Basin, i did 1 stack of censure dot on a fel hunter and i turn evil it, the fear effect broke on the second dot from the censure which is a bug, it should be 30% of the total damage taken or total hp whatever the formula was...

I did a 1 stack of censure dot on a felguard pet and i turn evil it, the fear effect stayed till the end.

Can you please fix this bug asap??

Its critical vs warlocks in duels, bgs, and most importantly arenas.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
But it isn't supposed to work like that, in Wotlk in that work like this...

**Comment by Pornoodemon** [comment]
> Но это не должно так работать, в Wotlk в этой работе вот так...

Baby wake up it's a cataclysm)

**Comment by Sketish** [comment]
Not a bug

**Comment by Renehadox** [comment]
Its cataclysm?
No shit?
I doubt blizzard changed anything about it in cata.
In wotlk there is also a talent or spell that 15% of direct dmg done to the warlock transfers to its pet.
But CC is not broken...

**Comment by Pornoodemon** [comment]
> Its cataclysm? No shit? I doubt blizzard changed anything about it in cata. In wotlk there is also a talent or spell that 15% of direct dmg done to the warlock transfers to its pet. But CC is not broken...

I played a warlock on WOTLK and I remember that it broke randomly when taking threshold damage. In the same way, it works on a cataclysm. In addition, in Cata the warlock itself can dispel cc it at any time, which is not clear here.
