### ISSUE TITLE
bug quest in rise of the brotherhood

### ISSUE THREAD

**Issue by yukikalel** [gamefreedomgit/Maelstrom#4087]
there is no words in the quest. just a clear page and you cannot complete the quest. please fix

![Untitled](https://github.com/gamefreedomgit/Maelstrom/assets/12093420/98350de1-637d-4b24-940d-6fa31b2cf084)

**Comment by PanJanuszek** [comment]
Not all quests contain, RequestItemsText, this is one of them. And if you see such screen it definetely says in 100% that you didn't complete quest. You have left event too soon or didnt participate. As a proof this is text when quest is completed.

![image](https://github.com/user-attachments/assets/30256c13-9aec-4d37-8f33-6cc4cf47022d)
