### ISSUE TITLE
Hunter Pets ARENT SUPPOST TO STACK THE SAME CC with dismissal. And are behaving as stun instead of daze ( exept for talents chosen )

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#4088]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: **
What's happening in both duels and Arenas (especially 2s)  is really mediocre hunters are doing well by using 5 Monkey pets. I'm not entirely sure about the abandoning pet bug working, haven't bothered with it because I assume that part is working right, but first of all I notice the damage removing ISNT working correctly either. its behaving like a stun instead of a daze and hunters ARE NOT supposed to be able to use 5 bad manners by dismissing 4 monkey pets. this only worked during 4.0.6. for about 2 months after the monkey was added to the game. the only way a hunter can use multiple Pet CC right after the other after dismissal is by actually using 5 DIFFERENT families of pets (for example a monkey with 
 bad manners (daze), a spider with web (root), and 3 others all different. after 4.0.6(a) they fixed families for pets which meant the SAME abilities that aren't based on chosen talents would share a cooldown even while in stable. the only abilities that would reset after you dismiss ur pet are TALENT chosen abilities, such as roar of sacrifice. not abilities native to each animal regardless of which talents choose. 

**How to reproduce: **
cast bad manners with monkey pet, then dismissing pet then casting it with another monkey, up to 5 times. and its behaving like a stun instead of a blind (daze )

**How it should work: **
Any abilities by the same by name even if it's a different pet is considered shared cooldown. for example, you can summon a monkey, use bad manners, dismiss him then summon a spider and root him. as in u can use 5 different pet abilities by dismissing them each, not summoning the exact same pet. that's how its suppose to work. and its a blind as in the moment the target is hit the ability is removed.

**Database links: **
Explanation by [hirumaredx](https://www.youtube.com/@hirumaredx)

https://www.youtube.com/watch?v=5Es7wWtZIb8     

https://wowpedia.fandom.com/wiki/Patch_4.0.6

(Pet families added) is the line of text referring to what's explained in video, that pet CDs of same family (thus same spell) share a cool down.

**Comment by Sketish** [comment]
It was already dicsussed https://github.com/gamefreedomgit/Maelstrom/issues/3019#issuecomment-1508528439
