### ISSUE TITLE
On foot Speed (mount speed) bug

### ISSUE THREAD

**Issue by dethshot101** [gamefreedomgit/Maelstrom#4089]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I found a bug where when on foot, you have the speed of being mounted but are able to attack and do actions without losing that speed.

**How to reproduce:**
I entered a dungeon via Dungeon Finder, finished the dungeon and when I exited, I entered the Auction house which forced a dismount, but when I exited the AH, I got the speed of my mount without actually mounting. I was able to attack a target dummy without losing that speed, craft an item via engineering, and entered a building without losing it either. 

**How it should work:**
When dismounted, I should have lost that speed and not regained when exiting the building. 

**Database links:**

**Comment by UltraNix** [comment]
Should be fixed.
