### ISSUE TITLE
Synapse Springs and trinkets 

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4090]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Synapse Springs and trinkets can be on in sametime, with macro:
/cast Vicious Gladiator's Kodohide Gloves (with Synapse Springs)
/cast Vicious Gladiator's Badge of Dominance

**How to reproduce:**
use macro, I think its work with all trinkets in game  

**How it should work:**
They should be have cd, as without macro

**Database links:**
https://wowpedia.fandom.com/wiki/Synapse_Springs_(Mark_I)
https://wowpedia.fandom.com/wiki/Vicious_Gladiator%27s_Badge_of_Dominance

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/cf97dd35-023a-4d00-b92b-634ec517ff4e)

**Comment by UltraNix** [comment]
Fixed.
