### ISSUE TITLE
[rogue][mage] sap and speal steal

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4091]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
speal steal break sap from target

**How to reproduce:**
use speal steal on target under sap effect (mb should be some buff for steal)

**How it should work:**
speal steal never should break sap and similar effect

**Database links:**
https://wowpedia.fandom.com/wiki/Sap
https://wowpedia.fandom.com/wiki/Spellsteal

**Comment by keroblus** [comment]
that happen to me , it made me to lose over 10 arenas vs feral disc

**Comment by Afgann** [comment]
fixed

**Comment by mipanka** [comment]
tested yesterday bug still
