### ISSUE TITLE
[dk][pet] Leap

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4092]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Leap can be used in root (with Dark Transformation: Charge an enemy, interrupting spellcasting and immobilizing them for 2 sec.)

**How to reproduce:**
use Leap when pet in root, and pet will break cast

**How it should work:**
pet in root should not use Leap

**Database links:**
https://wowpedia.fandom.com/wiki/Leap

**Comment by Afgann** [comment]
fixed
