### ISSUE TITLE
aura mastery 

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4094]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://github.com/gamefreedomgit/Maelstrom/issues/3891

**How to reproduce:**
https://github.com/gamefreedomgit/Maelstrom/issues/3891

**How it should work:**
https://github.com/gamefreedomgit/Maelstrom/issues/3891

**Database links:**
https://github.com/gamefreedomgit/Maelstrom/issues/3891

bug is back

**Comment by Sketish** [comment]
Duplicate
