### ISSUE TITLE
[Ashenvale] Raynewood Retreat questgiver missing

### ISSUE THREAD

**Issue by kauchaus69** [gamefreedomgit/Maelstrom#4095]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Avrus Illwhisper is a Satyr questgiver that is missing from Raynewood Retreat, which renders a questline undoable.

**How to reproduce:** He is non-existent.

**How it should work:** Avrus Illwhisper should be stood right next to the moonwell in Raynewood Retreat, yet he is missing despite being marked as there on the map when turning in a quest.

**Database links:** https://www.wowhead.com/npc=34335/avrus-illwhisper

**Comment by PanJanuszek** [comment]
If you follow quest chain then you will see him.

![image](https://github.com/user-attachments/assets/53da573c-7bbc-4a9d-a2e6-c4df4ea755f5)
