### ISSUE TITLE
PTR DTR Completely BROKEN

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4097]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The fix to make DTR procs instant is working properly BUT now it procs on every single thing 100%
Please just revert it back it was as perfect as it can be even with copied spell travel time.

**How to reproduce:**
https://youtu.be/Frvf_s5VZtg

**How it should work:**

**Database links:**

**Comment by BalanCV** [comment]
You seem to have fixed the 100% proc on PTR.
Went back for a test today here is some info:
Ran 1k and 5k dot tick tests some before and after the fix.

-Non pet classes have the same ~8% proc chance as before the fix.
-Warlock pet class before the fix had 12% (ran multiple 1k tests all slightly above 12%, sadly didn't think to do 5k before), after the fix its 11% (multiple 1k and one 5k test)
I checked simcraft source code and they estimate pet class proc chance for 4.3(after nerf) to be (0.17 * 0.67=11.4%)
Now, I don't know what you might do with this info as no one can accurately say what is the real exact proc chance, but I hope its good knowledge to have.

Test before:
https://imgur.com/a/XbFzDCP

Test after:
https://imgur.com/a/ucnKb4e

**Comment by Warlorc** [comment]
![Screenshot_20230807_114327](https://github.com/gamefreedomgit/Maelstrom/assets/135524585/386e2c01-e46a-41ba-885e-63094eb98a73)

The procc rates should be like this for 4.2, since dtr only got nerfed on 4.3 patch

**Comment by BalanCV** [comment]
Yep that looks about right according to my test. The mage one at least always ended up around 8.3% in my tests.
Since the client is 4.3 the values will be post nerf. This has been their policy so far as I've seen.
We're not really getting 4.2 patch, just 4.2 content.

**Comment by Warlorc** [comment]
Yeah but the nerf of dtr was made because of the dragon soul raid, dtr in its original state is perfectly made for fl content and patch.

**Comment by Sketish** [comment]
We wont be reverting proc chance

**Comment by UltraNix** [comment]
Already fixed.
