### ISSUE TITLE
[Stonetalon] "Burn, Baby, Burn!" bugged

### ISSUE THREAD

**Issue by kauchaus69** [gamefreedomgit/Maelstrom#4099]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The quest is not doable because the flamethrowers you loot from the nearby Krom'gar incinerators don't give credit for killing the Warsong Stockpiles, of which you need to "kill" 8.

**How it should work:** When using the looted flamethrowers on the Warsong Stockpiles, you're supposed to gain credit for the kill.

**Database links:** https://www.wowhead.com/quest=25622/burn-baby-burn
https://youtu.be/yQdls8nSM-0

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/c5a216f4-fcee-41d4-a8d6-ab5a1faf3260)

Cannot reproduce
