### ISSUE TITLE
Wrong hp amount in a query for npc with id=46645

### ISSUE THREAD

**Issue by arkadygalperin29** [gamefreedomgit/Maelstrom#4102]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
A mistake with this npc HP modifier, probably it has extra 000 or something in query responsive for HP

**How to reproduce:**
--- just check the hp

**How it should work:**
-- shouldn't be 30 mln hp here

**Database links:**
https://www.wowhead.com/npc=46645/cursed-stallion

**Comment by Afgann** [comment]
fixed
