### ISSUE TITLE
Summon Infernal

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4103]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Summon Infernal
https://cata.wowroad.info/?spell=1122

The infernal's passive ability Immolation does not scale with warlock stats(Sp, Demonology Mastery).
Although it should scale. Most likely it should be 10% of spell power.
I'm not 100% sure about the spell formula itself, but I couldn't find anything else.
https://www.wowhead.com/spell=19483

![WoWScrnShot_080423_170923](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/844c12a4-9b3a-4ced-8cbb-d2e66885ae85)
464 damage to dummy

Playing on the official server
https://youtu.be/r8x0kjm4iwU?t=144 
1.5-2k damage in pvp 
![`13221321](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/67afb5aa-e83d-4f24-8485-a577902e1409)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
With 10k Spell Power:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f814b7e5-6dc8-4c7f-9208-5ca1deffb687)
With 3,5k Spell Power:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b2fae484-1629-4007-a8c2-4a72ae92931a)

Infernal takes 50% of warlock SP.
Immolation coeff is 40%.

**Comment by Pornoodemon** [comment]
> С силой заклинаний 10k: С силой заклинаний 3,5k:

Went to the test server. You forgot about mastery in demonology, it should affect him (Now does not affect) and he should also attack the one on whom the Bane of Doom hangs.
This is an analogue of "Doomguard" Only for AOE damage.

Screenshots of damage in different talent branches (Demo and affli). 1632
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/867cdae5-a653-4846-ae78-350b7e1f56ed)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7df4545a-d862-47de-bbf1-095e96e9df9a)

**Comment by Pornoodemon** [comment]
I also wanted to ask if this passive ability affects the guards. "Demonic Knowledge"
https://cata.wowroad.info/?spell=84740
I have information about what should influence, if it does not affect now, I will try to find a proof if I can.

**Comment by UltraNix** [comment]
Fixed.
