### ISSUE TITLE
Holy Word: Sanctuary and Healing Rain

### ISSUE THREAD

**Issue by Zaraelh** [gamefreedomgit/Maelstrom#4104]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: The problem is that it is miscounting the healing reduction and is removing 6p of healing for each pj that is within the healing area of ​​each spell, that is to say, it starts to deduct 6p from your healing if there are only 1 pj in the spell and 60p if there are 10 pj and 150p if there are 25 pj and it reduces the healing again if there are more than 6 pj within the spells, this should not be the case, according to blizzard in 4.0.3 changes were made where they said Rain of healing, Holy Radiance, Holy Word: Sanctuary have a minor effect when healing more than 6 players at once. This is only working on the holy paladin with his holy radiance. In the description of the spell it tells us that Heal effectiveness decreases for each player beyond 6 within the area. Not that the healing effectiveness is reduced by 6p for each player within the spell zone. **

**How it should work: should work like the holy radiance spell in that its heals are reduced after 6 characters healed.**

**Database links:  https://wow.fandom.com/es/wiki/Parche_4.0.3a (
See it in Classes: General, 3rd point)
https://cata.cavernoftime.com/spell=73920 
https://cata.cavernoftime.com/spell=88685 **

**Comment by Zaraelh** [comment]
One question, could this be solved?

**Comment by UltraNix** [comment]
Fixed.
