### ISSUE TITLE
Guild challenge dont work (dungeon)

### ISSUE THREAD

**Issue by Donkforfun** [gamefreedomgit/Maelstrom#4105]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
We went 3 man "guild dungeon challenge" tanktastic, Varlaria and Chuckmagi.
We went Blackrock Caverns
Went we killed last boss, and dungeon was over, we didnt get the usual Guild dungeon challenge complete.
We are a mix ally / horde guild, is that the issue ?
It say dungeon 80-85 and we were 3 lvl 85, is that the issue?
It also looked like Chuckmagi dcéd at the same time, we killed the boss (cant see if just before or just after)
Is that the issue, "he aint online when boss died?"

**How to reproduce:**

**How it should work:**
Well it should work like normal.
We kill last boss and get the Guild dungeon challenge done :D

**Database links:**

**Comment by Sketish** [comment]
Dc may caused that issue.

**Comment by UltraNix** [comment]
Yes - if someone is offline, the challenge is not completed. You need at least 3 online players from the same guild to complete the challenge.
