### ISSUE TITLE
Fire elem damage since pet changes

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The melee part of the damage is the one that is the further from what it should be. First of all, melee crit damage bonus for fire elem should be 166% not 100%. (100% for spells).  Non crit melees are also dealing less damage than what they should do. Spells damage where doing more damage before the patch, now the damage looks good except that the crit damage bonus is not 100% but something like 50% right now

**How to reproduce:**

Get full T11 and then use volcanic pot + proc torrent +  proc lightweave + volcanic destruction then pop fire elem and let him hit the dummy for his entire duration. Look at damage after.

This is from the PTR
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/54c83a5e-2aef-41e7-b51a-c6452577969e)
This is from simc 4.3
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/137651b3-52c5-4076-a1ee-3de93dbc3777)
I made sure to check only the buffs that i provide as ele in simc config

**How it should work:**

When summoned, the Fire Elem INT is same as the shaman INT when casted and the Fire Elem SP is the SP from the shaman minus the part coming from INT( so weapon, procs, ...)
Then Fire Elem Melee scales like this : 96,47% from Elem INT and 64,57% from the Elem SP (and 166% crit damage bonus)
Fire Elem Spells scale like this : 85% from Elem INT and 53,42% from the Elem SP (and 100% crit damage bonus). Spell damage looks good right now (but don't have right crit damage bonus) on the PTR, its just the melee damage that's very low

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
