### ISSUE TITLE
[Quest][NPC][Gilneas] Patriarch's Blessing

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#4108]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After finishing the objective for the quest "Patriarch's Blessing", the world area phases after you are given back control of your character. You are then instructed to "Return to Krennan Aranas at Aderic's Repose in Gilneas." However, Krennan Aranas is in a different phase and new worgen characters are unable to proceed further in their starting zone. They are stuck there unless they have someone summon them out to a different location.

**How to reproduce:**
Create a new worgen character and proceed through the starting zone until you reach Aderic's Repose. Complete the objective for "Patriarch's Blessing" by placing the offering at the tomb and watching the small scene. After regaining control of your character, run over to the quest turn in location and the NPC will not be there.

**How it should work:**
Complete the objective for "Patriarch's Blessing" by placing the offering at the tomb and watching the small scene. After regaining control of your character, run over to the quest turn in location and the NPC will be there.

**Database links:**
https://www.wowhead.com/quest=24679/patriarchs-blessing

**Comment by UltraNix** [comment]
Fixed.
