### ISSUE TITLE
Alliance Tol Barad Quartermaster Brazie

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#4109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It has a 2h respawn instead of 5min like the Horde one.

**How to reproduce:**
Kill the NPC and wait 2 hours or use the command .npc info

**How it should work:**
It should respawn in way less time than 2 hours

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=47328

**Comment by Afgann** [comment]
fixed
