### ISSUE TITLE
The talent in the build of the POWER OF EARTH enha does not work. does not remove shackles

### ISSUE THREAD

**Issue by feelyawhiteboy** [gamefreedomgit/Maelstrom#4111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.c

**Description:**

**How to reproduce:**

**How it should work:**

The talent in the build of the POWER OF EARTH enha does not work. does not remove shackles
**Database links:**

**Comment by Sketish** [comment]
Invalid report
