### ISSUE TITLE
Felhunter's Shadow bite base damage (Tested after the last round of pet fixes)

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#4112]
**Description:**
Shadow bite base damage is lower than it should. Right now its doing ~24% less than what simcraft shows with the same gear and self buffs.

**Base damage**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/b8b66edf-d05b-486d-9dd3-e517b4154b85)

**Simcraft damage with character export and Removing dots from APL to check base **damage**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/a8de8c23-8d07-429a-820e-16b85bd3c653)
-

**Simcraft archive using the same parameters and gear**

[shadowbite.zip](https://github.com/gamefreedomgit/Maelstrom/files/12268729/shadowbite.zip)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@jlldarocha Because formula for Shadow Bite in simulation is not 100% correct.
What is your Spell Power during the test? Was it a constant value?
Formula for Shadow Bite:
```
Description: Bite the enemy, causing ${$M1+(1.228*($SP*0.5))} Shadow damage plus an additional $s3% damage for each of your damage over time effects on the target.
```

**Comment by jlldarocha** [comment]
the spell power was constant because i wasnt using anything with a proc, neither cooldowns. The formula on sims MIGHT not be 100% correct, but the ~25% difference is a huge indication theres something wrong going on. 
Its the highest damaging spell of demonology toolkit, so its under the spotlight to be as close to the numbers that happened in game.

**Comment by UltraNix** [comment]
My test with constant 10331 SP:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/54dab1fb-b13a-4a9c-9d7c-693de3590c59)
10331 * 0.5 * 1.228 = 6343
6343 * 1.18 (Mastery) = 7484
7484 + (104-142 - base dmg of shadow bite) = 7588 - 7628

**Comment by UltraNix** [comment]
My test with constant 10331 SP:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/54dab1fb-b13a-4a9c-9d7c-693de3590c59)
10331 * 0.5 * 1.228 = 6343
6343 * 1.18 (Mastery) = 7484
7484 + (104-142 - base dmg of shadow bite) = 7588 - 7628
(7588 - 7628) * 1.15 (Dark Arts) = 8726 - 8772

**Comment by jlldarocha** [comment]
Theres something missing on the calculation, i just tested apollo numbers and they are averaging within 15 damage of simcraft results.

Without worldoflogs to research its difficult to check exact numbers, but apollo was done when it was still available.

**Apollo export simc numbers**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/da698805-f855-4362-8a3b-f87b7e2244b2)


**Apollo actual damage**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/042dd5d1-64da-4199-b79a-29c2ad61cc31)

**Comment by UltraNix** [comment]
@jlldarocha Poke me on Discord.

**Comment by UltraNix** [comment]
Fixed.
