### ISSUE TITLE
URGENT I AM STUCK IN SHAPESHIFT FORM! Please help me 

### ISSUE THREAD

**Issue by Deeebud** [gamefreedomgit/Maelstrom#4113]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am stuck in shapeshift form as a pile of bones. 

**How to reproduce:**
I was inside doing the scholomance when mid way through i turned into a pile of bones and was not able to remove it. 

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Contact Gm's ingame so they can help with that issue
