### ISSUE TITLE
Typhoon inconsistencies 

### ISSUE THREAD

**Issue by Tdotsavage** [gamefreedomgit/Maelstrom#4114]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Typhoon on this server is very inconsistent, when I typhoon a target in pvp with no DR its as if the server does not register that it hits the target and the target does not get knocked back, this can happen facing someone with no DR and no defensives being used. 

**How to reproduce:**
use typhoon enough times on targets standing still or moving and you will see (not including Diminishing return)

**How it should work:**
Typhoon should knock the target back if you are facing the target as long as they are not rooted or stunned in the middle of being knocked. 

**Database links:**

**Comment by Sketish** [comment]
Please provide video of that issue

**Comment by ussj10** [comment]
How can a pushback be DRed? It's not like getting pushed back second time in a row makes you fly half the usual distance.

**Comment by Hermeleen** [comment]
can't it be resist or spell miss?

**Comment by UltraNix** [comment]
Fixed.
