### ISSUE TITLE
[Enhancement Shaman] Primal Wisdom doesn't regenerate enough mana

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#4117]
**Description:**
Primal Wisdom is supposed to have 40% of a chance to regenerate 5% of your mana from every **melee attack**.  However right now it counts only autoattacks, ignoring Stromstrike, Lava Lash and Windfury (contrary to it's name, the dmg is still physical). Mana lows get quite problematic after spending it in arena for repeated heal hardcast.

**How to reproduce:**
Try few times to dps a target dummy, for 1 minute let's say (should be enough to make around 100 melee hits). Check in combat log how much mana Primal Wisdom gives you (X). Then check how many autoattacks did hit your dummy (Y). 
Since it's 40%, calculate Y * 0,4 * X. The result will be almost exactly the amount of mana you gained every time, meaning all melee attacks that aren't autoattack got ignored by Primal Wisdom.

**How it should work:**
As the tooltip suggests - Primal Wisdom should apply to all melee attacks, not just autoattack.

**Database links:**
https://wowpedia.fandom.com/wiki/Primal_Wisdom

**Comment by Afgann** [comment]
fixed
