### ISSUE TITLE
Infinite Blood Frenzy debuff

### ISSUE THREAD

**Issue by LadyFireflower** [gamefreedomgit/Maelstrom#4118]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The title speaks for itself.
After a battleground i've experienced, that arms warrior's Blood Frenzy ability stays untill death (Which of i have a screenshots, one, where i have it, and one where someone else have it.). Relog dosen't help, before anyone asks.

**How to reproduce:**
I do not know for sure, but here's a theory.
Take the debuff from any arms warrior, whom have this trait, before the battleground is almost done.
Since debuffs stays after the battleground, it may become separate from the bleed effect. This debuff dosen't have any duration, since it's tied to the bleed effect.
(Did a few battleground, but the issue didn't occured to verify)

**How it should work:**
When the bleed is over, the effect vanish along with it

**Database links:**

**Comment by Sketish** [comment]
Please provide any source after what time debuff should go off

**Comment by bonfax4** [comment]
Should last as long as a bleed debuff is up. Similar to Rogue savage combat talent and poison. [Mercader video here ](https://youtu.be/WLGMp0KMfSo)( known retail rogue player ) where savage combat drops instantly when poison debuff wears off at 0:30 seconds. Should also test if savage combat is displaying the same issue.

**Comment by bonfax4** [comment]
@Sketish  [Video here](https://youtu.be/jyjzHdD9ozY) blood frenzy dropping as soon as rend debuff wears off @ 3:40

**Comment by VincentADK** [comment]
LadyFireflower wanted me to provide these screenshots here:
https://imgur.com/a/r1LjYgH

**Comment by Afgann** [comment]
fixed
