### ISSUE TITLE
Reset Warlock Pet CD

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are two problems with resetting the warlock's pet cd.
First problem- if you re-summon the current pet (Any of the list)(For example, you have summoned a Fel Guard and you re-summon it with the help of casting the summon - reset its cd does not work
Second problem - If you summon the pet again through Soulburn, resetting the cd reset works everyone except felhunter (reset only visually, but but his spell ( Spell Lock) can't be used) .

 If you let go and then re-summon the pet any way, the cd reset works for all pets

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c5f9efd2-8db5-42dc-b2e1-bbcfb89f8dd4

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by Hermeleen** [comment]
So when demo lock uses felstorm, resummons felguard, it is correct to have the felstorm cd reset?

**Comment by Pornoodemon** [comment]
> So when demo lock uses felstorm, resummons felguard, it is correct to have the felstorm cd reset?

Yes . This should reset the cooldown on all pet abilities.
