### ISSUE TITLE
Shaman Riptide seemes to be bugged! (Ancestral healing)

### ISSUE THREAD

**Issue by VincentADK** [gamefreedomgit/Maelstrom#4120]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

I am writing this for Alp from our discord server!

Evidence: https://imgur.com/a/IUn9SYX
https://youtu.be/4qsERLrW3_o?t=493  
(just for reference, if you look, you can see that the warrior gets the buff while the shaman does nothing. 
Earthliving might be bugged too, not 100% sure about this tho)

**Description:**
Riptide periodic crits only proc Ancestreal Healing buff on the shaman and not on other players. 
(The 10% physical damage reduction buff)

**How to reproduce:**
Try to see if riptide is doing a periodical critical strike and if so that your target receives the buff!
Try using it on yourself and on another player please!

**How it should work:**
Riptides periodic effect should also proc Ancestral Healings effect on other players (targets)!

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=68120
https://cata-twinhead.twinstar.cz/?spell=16235#see-also-ability

**Comment by UltraNix** [comment]
Fixed.
