### ISSUE TITLE
ToT4W Guardian pets

### ISSUE THREAD

**Issue by Shakrei** [gamefreedomgit/Maelstrom#4121]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I'm not too sure whether it's just the dk's ghoul or all the guardians, but my pet did not attack any of the bosses there on several attempts/lockouts. He hit Anshal once and then just stood there, wouldn't even touch Alakir. As it is a guardian I have no way of controlling it or ordering it to attack
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/7e142877-5899-46d1-ad4d-a46428195077)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/826c45e1-02c0-42b7-a74a-f632a1da6a15)

![WoWScrnShot_080723_205927](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/cada1166-d985-4bc7-b9b3-17299dbc03a9)

**Comment by Afgann** [comment]
fixed
