### ISSUE TITLE
Horde Scarlet Monastery, bugged Dark Ranger Velonara

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4122]
**Description:**
Scarlet Monstary appears to be bugged, especially for Horde.
Quest give Dark Ranger Velonara is not spawning in any of the dungeons, we get Joseph instead.
https://i.imgur.com/nqcruDh.jpeg

Scarlet Armory also appears bugged, as Scarlet Soldiers are frendly.
https://i.imgur.com/kx4lEHh.png

When Velonara has been spawned in by a GM, I was still unable to turn in the quest "Moving Things Alon"
https://i.imgur.com/68FwFMG.jpeg

**How to reproduce:**
Create Horder character
Enter Scarlet monastery Alone or with Party
Observe that you cannot find Dark Ranger Velonara, even if the question mark (?) appears on minimap.

**How it should work:**
Velonara should be present at the entrance in any of the Scarlet Monastery Dungones.

**Comment by UltraNix** [comment]
Fixed.
