### ISSUE TITLE
 Into The Wild Green Yonder

### ISSUE THREAD

**Issue by Moszugun** [gamefreedomgit/Maelstrom#4123]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I cannot pick up crusaders 

**How to reproduce:**

**How it should work:**
I can pick them up 

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13045

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
