### ISSUE TITLE
Battle for Gilneas

### ISSUE THREAD

**Issue by Matjanusz** [gamefreedomgit/Maelstrom#4124]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest Battle for Gilneas doesn't work. After taking quest character instatly moving to another location and can complete quest. There is no plot in this quest

**How to reproduce:**

**How it should work:**

There should be a few scenes and battles but instead there is nothing.

**Database links:**

https://www.wowhead.com/quest=24904/the-battle-for-gilneas-city

**Comment by UltraNix** [comment]
#398
