### ISSUE TITLE
Plate items under level 50

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4126]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Plate is learned at level 50, yet there are Plate items with ilevel 45 (for example) that can be obtained bellow 50, without a level lock.
These items have no value as anything level 50 will be better.
I am not sure if this shoul've been mail or not.

I believe I obtained it from the RDF reward, but its unusable, as its either the wrong type (should be mail) or the wrong reward.

![5Z](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/c9e2a809-7b49-443b-8dec-37394055067a)

These are from random drops. Plate should be level 50+
These items drop in 30-35 areas, 50 because they are Plate, the level lock is useless.
![5a](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/26ed11b7-bde0-43eb-ac3d-bd471733ca6c)

![5b](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/fd6ebc4f-8870-4c37-89e4-8fbf970af0e3)

I am a level 35 Paladin.

**Comment by BalanCV** [comment]
You learn plate at level 40.
https://wowpedia.fandom.com/wiki/Plate_armor

**Comment by Sketish** [comment]
Not a bug
