### ISSUE TITLE
Shaman spirit wolfs bugging

### ISSUE THREAD

**Issue by tankjr-wowo** [gamefreedomgit/Maelstrom#4131]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi, after some checks on the shaman upgrade, the glyph of feral spirit is buggy and increases wolf damage and healing way too much, which is not sustainable, please fix this as soon as possible, it breaks pvp a bit , especially in the arena

**How to reproduce:**
With enhancement shaman spec, and with glyph of feral spirit

**Screenshots for the bugs **
without the glyph :
https://cdn.discordapp.com/attachments/693264305851859004/1138858795137765426/WoWScrnShot_080923_173751.jpg

with the glyph : 
https://cdn.discordapp.com/attachments/693264305851859004/1138858583409299526/WoWScrnShot_080923_173517.jpg

**Comment by UltraNix** [comment]
Fixed.
