### ISSUE TITLE
Combat Training - Quest - Out of Phase NPCs

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4133]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Quest Combat Training, where you use a Val'Kyr to gather forsaken troops, the Val'Kir dies as its being attacked by Alliance Laborers from other Phases (I believe)
In this video you will see that its taking damage and dying without atacking or being attacked (visibly)
https://imgur.com/a/OBgN6UW

**How to reproduce:**
Compelte the Felstone Field quests until you get the Combat Training

**How it should work:**
The correct NPCs should be in Phase and the other Phase should be isolated

**Comment by UltraNix** [comment]
Fixed.
