### ISSUE TITLE
Kill command is not doing dmg on my lvl

### ISSUE THREAD

**Issue by twiinker** [gamefreedomgit/Maelstrom#4135]
Description: Iam lvl 84 Twink hunter and iam doing 2,4K dmg with kill commands 
![kill command](https://github.com/gamefreedomgit/Maelstrom/assets/141876189/3a5792e1-ba16-405c-81df-87939aba4734)
![lvl 84](https://github.com/gamefreedomgit/Maelstrom/assets/141876189/df98218b-f268-43c0-8343-fa7164d9621f)
after new patch it bugged

How it should work: I should do more dmg at lvl 84

**Comment by UltraNix** [comment]
Fixed.
