### ISSUE TITLE
treasure finding potion and archaeology

### ISSUE THREAD

**Issue by greeny5** [gamefreedomgit/Maelstrom#4136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** potion of treasure finding not working. no chests dropping and a digsite in kalimdor is bugged. cant get the artefact so cant progress. the digsite is at the top of feralas. when you try to search for the artefact the telescope keeps changing position on the spot but never reveals the artefact. the treasure finding potions can be consumed but their effect doesnt work. i have tested this in firelands upon release. the archaeology one is a big issue for me because its 1 less digsite i can make into an uldum digsite and it limits my options to only 3 digsites in kalimdor
https://www.wowhead.com/item=58488/potion-of-treasure-finding#comments

**How to reproduce:** see pictures and links
NEW ISSUE. in the same spot the bug has changed for archaeology.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/141881759/a8bb1244-977f-4e2a-bf0d-e8b4f0e89496)
the telescope now tries to send you outside of the place you can dig. see the diggable area on the map
![image](https://github.com/gamefreedomgit/Maelstrom/assets/141881759/857feb72-61db-4d2a-95be-e39b54a0514d)

**How it should work:** treasure chests should drop on mob kills when potion of treasure finding is active. the artefact should appear and be collectable when in the correct place but this isnt happening.

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/141881759/b5867353-3b1a-4fcf-b84d-85cdf9aa5fc4)
the red circle on the map on the image is the bugged site on archaeology. 

not sure what more information i can give

**Comment by UltraNix** [comment]
About archeaology: #4067
About potion:
![Uploading WoWScrnShot_092923_135053.jpg…]()
