### ISSUE TITLE
Arena frames

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4138]
1. When you enter arena and someone has a pet out it messes up the arena frames

2. When you enter sometimes your party1 and party2 are flipped (only when you use raid party frames)

**Comment by MistrMattt** [comment]
Can confirm bug regarding enemy arena frames. Its not just visual bug but actually makes your enemies from "arena1, arena2,arena3" to "arena2, arena3, arena4" 

Evidence: https://imgur.com/a/wWUvR9w

**Comment by UltraNix** [comment]
@SimonBpvp @MistrMattt What addons do you use?

**Comment by SimonBpvp** [comment]
> @SimonBpvp @MistrMattt What addons do you use?

I use sArena but it’s surely not an addon related bug, it happens with gladius and without addons too I’m sure. It’s the team mate’s pet going into the first arena frame slot that messes up the arena frames. And if you have 2 teammates both with pets out then those pets will occupy both arena frames 1 and 2 which messes it up even more!
