### ISSUE TITLE
[Quest] Elemental Bonds: Doubt

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#4139]
**Description:**
These elementals should give you 5 energy from smaller elementals and 15 from the big elite, furthermore you should be able to tag these regardless of being in a party or not and gain credit.

**How to reproduce:**
Kill a few elementals while its crowded.

**How it should work:**
You should be able to tag these mobs without a group.

**Database links:**
https://gyazo.com/360673efa6fcde02361c0295104b6790
https://www.wowhead.com/quest=29327/elemental-bonds-doubt#comments
https://www.youtube.com/watch?v=lfqaGwlo0dw

**Comment by Battlecryz** [comment]
Just did this one and works fine now. But i'm running into the same issue with the 3rd part of the chain in Molten front
 [Elemental Bonds: Fury].

**Comment by UltraNix** [comment]
Already fixed.
Fixed for Elemental Bonds: Fury on the way.
