### ISSUE TITLE
Twilight Highlands Quest: Off The Wall

### ISSUE THREAD

**Issue by cryziz23** [gamefreedomgit/Maelstrom#4140]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am currently doing quests in Twilight Highlands, and I saw the text about it being under heavy construction. I'm doing the "Off The Wall" quest, getting into the Skyshredder Turret and shooting the Highbank mobs below. The turret seems a little lacking, just takes a few extra hits to kill so it could be intended, but once I got out of the turret the NPC (Patch?) is nowhere to be found to turn in the quest. I logged in and out, didn't seem to fix anything.  I've got the quest completed and in my log on my mage named Topbraz.

**Comment by Sketish** [comment]
Please follow template when reporting, currently it's invalid report
