### ISSUE TITLE
Dk Unholy Gargoyle Life Bug

### ISSUE THREAD

**Issue by Nskaneki** [gamefreedomgit/Maelstrom#4143]
greetings to all whitemane development team! i will try to be brief (my english is so bad because i´m spanish)
I am a multiclass player focused on pvp. Today that the season transition and the 4.2 patch implementations were made, I realized that the unholy dk's gargoyle has very low health, basically it can be killed with 2 hits. Specifically, it has 39,000 life, I report this so that it can be solved since as a profane dk, the gargoyle is part of the character's burst and thus it is impossible to play arenas competitively.
![Sin título](https://github.com/gamefreedomgit/Maelstrom/assets/141893601/172a952c-72a0-4f7a-b8d6-9b719dc60162)

It should be noted that I have all the strongest pvp armor 
![Sin título](https://github.com/gamefreedomgit/Maelstrom/assets/141893601/62aa417c-3056-4922-8823-9ab061251a5e)
so far vicious s10 and 1 relentless part.

Thank you in advance for your attention and for giving us this good server.
Greetings from Colombia.

**Comment by UltraNix** [comment]
Fixed.
