### ISSUE TITLE
ID PROBLEM

### ISSUE THREAD

**Issue by YOSHUA2023D** [gamefreedomgit/Maelstrom#4145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My friend - killed Pyro with us - then afk when we killed Bethlilac, we reinvited him for Shannox - now he can't join us.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
