### ISSUE TITLE
Firelands- issues

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4147]
Trash Mobs

1.Fire Hawk trash event is not working. after killing 2 small spinders before hawk finish cast, mob should give players buff
https://user-images.githubusercontent.com/122209088/250639509-5e74f13d-2ffb-4fb5-b9e9-cd66bc87c24c.png
https://www.wowhead.com/npc=53648/inferno-hawk#comments

2.Blazing Monstrosity are ccable and are stopping doing anything after getting any cc. Also players should be able to jump on them to direct the barrage on eggs

Shannox
1.Boss is casting Arcing Slash during Spear Throw, making cleave in random direction. He shouldnt cast those 2 abilities at same time

Majordomo
2.During cat form, boss is always leaping on tank, looks like boss is not swapping target during leap cast and is always jumping on highest threat target.

**Comment by Sketish** [comment]
Shannox
1.Boss was rooted in place and had aggro on tank who could run away from him.

Baleroc
1.If person dies during crystal and is combat ressed the crystal is ignoring that playr not allowing him to soak. The next crystal is working correctly.

Ragnaros
1.On first tranistion we had hammer on left side, on second one visual was showing that hammer will be placed on right side but all adds started moving to place  where hammer was on previous transition(left side).

**Comment by Sketish** [comment]
Trash
1.Blazing Monstrosity is not always visible when entering area
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/7e664eec-dc28-47d3-a08a-b807b52ba6eb)
2.1.Fire Hawk trash event should kill drone which is on top of hawk after successfull rescue

**Comment by Sketish** [comment]
Bosses

Beth'tilac
-Ember Flare should tick every 6 seconds instead of 12
- melee dmg on 10 man looks too low

Baleroc
-melee dmg way too low

Ragnaros
-melee dmg too low

**Comment by clam119** [comment]
> Bosses
> 
> Beth'tilac -Ember Flare should tick every 6 seconds instead of 12
> 
> * melee dmg on 10 man looks too low
> 
> Baleroc -melee dmg way too low
> 
> Ragnaros -melee dmg too low
> 
> Lord Rhyolith -should be easier to turn from max left to max right and vice versa.

Just to add on Beth'tilac's Ember Flare. On P1 specifically, it's 12 seconds, and P2's Ember Flare is every 5 seconds instead of 6.

**Comment by Sketish** [comment]
> > Bosses
> > Beth'tilac -Ember Flare should tick every 6 seconds instead of 12
> > 
> > * melee dmg on 10 man looks too low
> > 
> > Baleroc -melee dmg way too low
> > Ragnaros -melee dmg too low
> > Lord Rhyolith -should be easier to turn from max left to max right and vice versa.
> 
> Just to add on Beth'tilac's Ember Flare. On P1 specifically, it's 12 seconds, and P2's Ember Flare is every 5 seconds instead of 6.

https://youtu.be/mqUFFhvk0KU?t=81 1st flare
https://youtu.be/mqUFFhvk0KU?t=87 next flare  so it's 6 seconds

**Comment by clam119** [comment]
> > > Bosses
> > > Beth'tilac -Ember Flare should tick every 6 seconds instead of 12
> > > 
> > > * melee dmg on 10 man looks too low
> > > 
> > > Baleroc -melee dmg way too low
> > > Ragnaros -melee dmg too low
> > > Lord Rhyolith -should be easier to turn from max left to max right and vice versa.
> > 
> > 
> > Just to add on Beth'tilac's Ember Flare. On P1 specifically, it's 12 seconds, and P2's Ember Flare is every 5 seconds instead of 6.
> 
> https://youtu.be/mqUFFhvk0KU?t=81 1st flare https://youtu.be/mqUFFhvk0KU?t=87 next flare so it's 6 seconds

Wasn't disagreeing, I was just adding on that the P2 Ember Flares that are supposed to be cast every 6 seconds is being casted every 5 seconds instead of 6 seconds throughout the entire encounter.

**Comment by Sketish** [comment]
Ragnaros should enrage after 15 mins instead of 18.

2011-07-12 Ragnaros now enrages after 18 minutes in all raid difficulties and sizes, up from 15 minutes.

**Comment by Sketish** [comment]
Sons of flame are sometimes spawning under textures on 25m
https://www.youtube.com/watch?v=wHhKVofbjFo&ab_channel=Smite
