### ISSUE TITLE
Western plague lands. quest doesn't work

### ISSUE THREAD

**Issue by Skatiniaka** [gamefreedomgit/Maelstrom#4148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

when-death-yet-not-end
**Description:**

Kill Alliance Workers and Convert
**How to reproduce:**

workers are in invisibility and cannot be selected. quest doesn't work
**How it should work:**

https://www.youtube.com/watch?v=OSpV2W_xMe4
**Database links:**
https://www.wowhead.com/ru/quest=26937/когда-смерть-еще-не-конец

**Comment by PanJanuszek** [comment]
Fixed 29.12.2023
