### ISSUE TITLE
Deeper into Darkness Quest bug

### ISSUE THREAD

**Issue by Charleahurley** [gamefreedomgit/Maelstrom#4149]
**Description:**
Skitterweb Matriarch will not come down/stuck in ceiling. Cannot be aggroed with ranged attacks.

**How to reproduce:**
Certain target stuck in ceiling, cannot be targeted therefore cannot progress through questline

**How it should work:**
https://www.youtube.com/watch?v=neOikNxWwk8

**Database links:**
https://www.wowhead.com/quest=27094/deeper-into-darkness

**Comment by Sketish** [comment]
Duplicate https://github.com/gamefreedomgit/Maelstrom/issues/4365
