### ISSUE TITLE
Sholazar Basin - The Mist Isn't Listening Bugged

### ISSUE THREAD

**Issue by Guillitine** [gamefreedomgit/Maelstrom#4154]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest tells  you to go kill some NPCs, sadly the NPCs display "Invalid target" the moment you want to attack them.

**How to reproduce:**
No clue

**How it should work:**
Should be able to kill off the mobs, reputation even says "at war" and the mobs are marked red

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
