### ISSUE TITLE
Inquisition never gives " Divine Purpose " talent

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4157]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Paladin ability Inquisition never procs " Divine Purpose " talent.

I am playing here for months and i can confirm that this is a critical bug.

Yep, just did a 2 minute test 0 procs from inquisition...

Please fix asap this critical bug, thank you.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
uthor: Ultranix
Message: Core/Spells: Divine Purpose vs Inquisition.

gamefreedomgit/Maelstrom#4157 

Just did a 3 minute test, it says its fixed but it doesn't proc. :D

**Comment by UltraNix** [comment]
![WoWScrnShot_081523_101827](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/be2073f2-2f98-4490-b909-edd0d99e61dc)
It does work.
