### ISSUE TITLE
Gargoyle Damage

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4158]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Gargoyle damage is about twice as high as it should be.
On the video Dk 371 item level. 13800 attack power and 8.8 mastery
I have 3334 resilience, gargoyle hits 11k at 3334 resilience
Gargoyle just  solo kills
![WoWScrnShot_081123_030355](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/ba3b183f-f37b-48a5-81af-38842d37d86a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c209cdf7-e7dc-471d-933c-1c059d21a388)

Attached video
https://www.youtube.com/watch?v=3UBnBMuZsQY

Proof 1 
https://youtu.be/vOe6nrjXe2Y?t=17
Dk 13882 attack power and 12.27 mastery
7.5k damage ( Dummy  0 resilience)!!!
Proof 2
https://youtu.be/bQKxSBrudCA?t=561
Dk  in full 11 season  item
7.5k damage ( Dummy  0 resilience)!!!

The same DK with use PVP trinket  proc for attack power,+ other procs + buff druid and Flask on 300  power
 https://youtu.be/bQKxSBrudCA?t=934
11.2k damage ( Dummy  0 resilience)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
Proof 3
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/5c7cc325-4e96-4566-ba8a-d861f4ed82f5)
18 k attack power and 9.5 mastery
7-8 k damage ( Dummy 0 resilience)

https://youtu.be/5N7wTKndbmA?t=124

**Comment by Pornoodemon** [comment]
I think that Unholy DK will hate me for this but someone had to dot the and.
I think that proofs are enough not to return to this topic

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/34f5d7b8-2f1d-4aca-82b6-6d2d58982157)
![WoWScrnShot_081323_201121](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7c3fa4d4-3960-46af-8b06-5d5fd1c5ef93)

After the last fix .Damage remained inflated by about 15-20%

**Comment by Pornoodemon** [comment]
![21231112321](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/b327efff-6bcb-44c8-a585-4608246bb4ce)

1 Video 17682 AP =   7500 damage gargoyle strike

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/78a48bd3-061f-49a4-91c4-efb04db01f8d)
3 video - 18293 AP  (before summon gargoyle) -  7800 damage

**Comment by Pornoodemon** [comment]
18300 AP (before summon gargoyle) -9100 damage gargoyle strike

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/34f5d7b8-2f1d-4aca-82b6-6d2d58982157)
![WoWScrnShot_081323_201121](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7c3fa4d4-3960-46af-8b06-5d5fd1c5ef93)

**Comment by Pornoodemon** [comment]
According to Wowhead comments
Gargoyle Strike Damage Formula
  - base damage per strike is 120
  - attack power coefficient is 0.4
  - 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/9d4652f6-8cc3-4ed4-94fd-e290759130a0)

From (Patch 3.1.3) to (4.3.4) there was no change in damage.
120+17682 × 0.4 =7192
  + 8%  "Ebon Plaguebringer" 7192 ×1.08 =7768 damage
1 video 7522 damage
Damage is relatively the same (Deviation of 100-200 units)
2 video 
120 + 18390 × 0.4=7476 
![13213144334214](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/335dfd96-6730-4657-be12-541e95a5c9b5)
There is a spread of up to 300 damage (back and forth)
I think this is due to the fact that I can not take into account all the little things.

**Comment by UltraNix** [comment]
We take 0.453 from DK AP.

**Comment by Pornoodemon** [comment]
> We take 0.453 from DK AP.

Do you mean that 0.453 AP is the formula that is currently in use?

**Comment by UltraNix** [comment]
Yes. It's from DBC (aka Blizzard) files.

**Comment by Pornoodemon** [comment]
> Yes. It's from DBC (aka Blizzard) files.

Is there a 1.5 second cast speed limit?
On tests it looks like 1 sec GCD, but as far as I know it should be 1.5 sesec. I can try find proof of thisc.

**Comment by UltraNix** [comment]
You mean haste cap? Yes - there is a cap.
Min gcd is 1625ms, max gcd - casting time.

**Comment by Pornoodemon** [comment]
> Ты имеешь в виду шапку спешки? Да - шапка есть. Min gcd — 1625 мс, max gcd — время каста.
Thanks for your work. I think the topic can be closed .The udk can be left alone for now
