### ISSUE TITLE
magma rupture damage 

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4159]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**magma rupture on shannox in second phase(under 30%) is doing dmg before the cast and even if you are between flames still get hit , can u take a look , please? shannox is broken af 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Tested on ptr it's working correctly, if you stay between lines you are never getting hit unless you move towards spirals

**Comment by xmrshoot** [comment]
@Sketish  its not , Molten Eruption - this spell has 2 effects, first aoe on cast is working but 2nd part when boss is leaving spiral pattern on ground which is exploding. If player don't move at all he is 1shotted even when outside of visual. If player move during this spell then its working correctly. its like u said here , but u edited , the dmg is broken  in hase 2

**Comment by Sketish** [comment]
Checked on PTR and it;s workign correctly.
Did all scenarios:
Didnt moved at all on cast - no dmg
Stood between lines - no dmg
stood to close to spiral - took dmg

**Comment by xmrshoot** [comment]
ok so we need to not be closer to spirala, anyway everybody will do it on hc next week and in hc he dont have this mechanic
