### ISSUE TITLE
shannox item bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4160]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**shannox item boe instead of soulbond

**How to reproduce:** 
![Uploading image.png…]()

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
