### ISSUE TITLE
shannox item bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4162]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** boe instead of soulbond

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/a1de7535-6be2-43e5-bdea-60514ea352ed)

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
From normal it's boe on heroic its bop
