### ISSUE TITLE
Pets fall through the floor at Siamat in Lost City of the Tol'Vir

### ISSUE THREAD

**Issue by BrotherWolf7** [gamefreedomgit/Maelstrom#4163]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

At the Siamat fight in Lost City, hunter pets will fall through the floor, making them unusable for the entire fight. I have tried summoning each of my pets and the same thing occurs with each type. Unsure if this happens with death knight pets or warlock demons.

**How to reproduce:**

Summon a hunter pet on the roof at Siamat in Lost City of the Tol'Vir.

**How it should work:**

Pets should not drop through the floor.

**Database links:**

**Comment by UltraNix** [comment]
#2551
