### ISSUE TITLE
Hierloom from Guild Vendor, Need Stat corrections.

### ISSUE THREAD

**Issue by BeserkPsycho** [gamefreedomgit/Maelstrom#4164]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The heirloom Plate items in cataclysm have 2 versions of pve heirlooms. One for Dps and one for Tank, the DPS set is "Of valor" and comes with crit/expertise/hit/haste as secondary stats. The Tank set "Of Might" comes with Dodge/Parry/expertise/hit as secondary stats. The guild vendor sells heirloom Back, Head, and Legs. However, for some reason on your server, the Legs are off, the Tanking "of might" heirloom plate legs, has the same exact appearance, and stats as its dps "of valor" counterpart. No Dodge/Parry secondary stats to be found

**How to reproduce:**
N/A

**How it should work:**
The Tanking "of Might" legs have their secondary stats corrected to match the stat type of its Helm/Shoulders/Chest/Back counterpart. Give it the Parry / Hit secondary stats it's supposed to have.

**Database links:**
Below is a link showing what the full set of TANK plate heirlooms are, all in one picture, including what the correct stats for the plate tanking legs are. Below that is a side-by-side comparison of the plate heirlooms, Head-4-head, Chest-4-Chest etc. and you'll see that on your server the legs are wrong and are EXACTLY the same, instead of the legs having "Parry Hit" they have the same stats as the DPS ones.

https://media.mmo-champion.com/images/news/2011/march/heirloomtanking.jpg

![Shoulders](https://github.com/gamefreedomgit/Maelstrom/assets/142067675/b19be2fb-13f0-4e55-804c-897a06bed3c9)
![Chest](https://github.com/gamefreedomgit/Maelstrom/assets/142067675/4bb5b6bd-1963-430f-ac03-89674f9e8b55)
![Helm](https://github.com/gamefreedomgit/Maelstrom/assets/142067675/35c1ed58-177e-4a50-bb4a-4bf9775d5369)
![Legs](https://github.com/gamefreedomgit/Maelstrom/assets/142067675/04f7c1f7-1b35-4ce1-823e-d24963720e8c)

**Comment by BeserkPsycho** [comment]
This issue was made aware over a month ago. It is realistically a change that could be fixed during someones Lunch time. The ONLY thing that needs to happen, is the secondary stats of the Plate heirloom legs "of might" being swapped from the "dps secondary stats" back to "Parry / Hit" like its SUPPOSED to have. Maybe 5-10minutes at best, 30 at worst... Over a month. As well this has been "escalated by supervisors" and "assigned to 2 devs" supposedly, but still not fixed or addressed yet.

**Comment by UltraNix** [comment]
Fixed.

**Comment by BeserkPsycho** [comment]
Finally!

How long did the code fixing corrections take?
