### ISSUE TITLE
False World Chat cannot be deleted - Correct WorldChat does not work (bug)

### ISSUE THREAD

**Issue by firestormfreakz** [gamefreedomgit/Maelstrom#4165]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
False chats name "world" and "World_Chat" are created in my custom chat list and cannot be deleted, and the correct WorldChat does not work.

**How to reproduce:**
-

**How it should work:**
False chats must be able to be deleted and WorldChat must appear only and work.

**Database links:**

![Screenshot 2023-08-12 054911](https://github.com/gamefreedomgit/Maelstrom/assets/142069563/21f04a20-80fe-4e62-8f79-a83368788895)

**Comment by BalanCV** [comment]
Think you might need to delete cache, maybe even WTF folder (just save ur addon settings if u do)

**Comment by UltraNix** [comment]
@firestormfreakz Still happens? Tried the above solution?
