### ISSUE TITLE
hola tengo 2 personajes bugiados 

### ISSUE THREAD

**Issue by Adonis021291** [gamefreedomgit/Maelstrom#4166]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Adonis021291** [comment]
tengo un hunter y un dk bugiados uno esta muerto y eltro se quedo flotando en el aire al salir de una masmorra  los nombre de los pj es zeltrax, dk y riota, hunter

**Comment by Sketish** [comment]
Translate this to english pls
