### ISSUE TITLE
Mobs not appearing in Felstone Field 

### ISSUE THREAD

**Issue by tommyboogers** [gamefreedomgit/Maelstrom#4167]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Alliance Labourers mobs needed to be killed for the quests [Foes Before Hoes] and [When Death Is Not Enough] at Felstone Field in the Western Plaguelands are invisible and untargetable.

You can still kill them with AOE but this won't count for the 2nd quest as the corpses won't show up

**How to reproduce:**
Go to felstone Field

**How it should work:**
There should be targetable mobs for Horde

**Database links:**
https://www.wowhead.com/quest=26999/a-new-era-for-the-plaguelands
https://www.wowhead.com/quest=26937/when-death-is-not-enough

**Comment by PanJanuszek** [comment]
Fixed 29.12.2023
