### ISSUE TITLE
alysra trash birds

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** if you die to fire  birds keep spitting fire on you even if u are dead

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/6e2d62a2-e428-48e1-ac6f-7e0350e4560a)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
