### ISSUE TITLE
 [Supplies for the Other Side]

### ISSUE THREAD

**Issue by Lukabxjx** [gamefreedomgit/Maelstrom#4169]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cant loot Blueroot Vine
![image](https://github.com/gamefreedomgit/Maelstrom/assets/41426173/e09a536b-a708-436b-8242-5d4e93365b66)

**How to reproduce:**
Go to it and try to loot.

**How it should work:**
You should be able to harvest Blueroot Vine.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29166

**Comment by UltraNix** [comment]
Fixed.

**Comment by jlldarocha** [comment]
Isnt working again.

**Comment by Lukabxjx** [comment]
Re-open this. Its still bugged.
