### ISSUE TITLE
Blade Flurry not transfering damage correctly

### ISSUE THREAD

**Issue by Kobiano** [gamefreedomgit/Maelstrom#4170]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blade Flurry does not transfer 100% of damage when Sinister Strike, Revealing Strike and Eviscerate crit. It only transfers half of
the damage, as if the ability did not make a critical.
On auto attacks everything works fine, as it should, though.

**How to reproduce:**

**How it should work:**
Blade Flurry should transfer the full amount of damage that Sinister Strike, Revealing Strike and Eviscerate do when they make a 
critical hit. 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
