### ISSUE TITLE
Can't comple the quest The bears up there

### ISSUE THREAD

**Issue by Painttroll** [gamefreedomgit/Maelstrom#4175]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can't do the quest, i already abandon and retake the quest but nothing happens

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Quest is completeable
