### ISSUE TITLE
Ghoul life goes down mysteriously

### ISSUE THREAD

**Issue by Nskaneki** [gamefreedomgit/Maelstrom#4176]
Greetings again, I'm Nskaneki the dk who had previously reported the gargoyle bug, which was fixed successfully and quickly. This time I come to report a pet bug again, but it has to do with the ghoul..
I don't know how to explain it, but the ghoul's life is reduced considerably, normally my pet has 89991 health, but the health is reduced to 30-40k and I don't know why, this happens every time the pet is summoned and started a confrontation, so it is something recurring.
I will report this on github for further review, as many players abuse this bug to win soloqueue arenas. Thanks a lot.

I explain how this happens:
Upon entering an arena, I summon my ghoul, and he appears with full health as we can see here... 
![Spawned](https://github.com/gamefreedomgit/Maelstrom/assets/141893601/546ea18f-b77d-4f16-866c-d9bf6421d46d)

but just a few seconds later his life is reduced.

![Life Down](https://github.com/gamefreedomgit/Maelstrom/assets/141893601/0fd5c6d0-aa45-423c-8005-9245d40a3c21)

this occurs several times during the course of the confrontations. Thanks a lot for Dev and Staff Team. <3 

EDIT: 

https://github.com/gamefreedomgit/Maelstrom/assets/141893601/21b5cd98-b0b0-454e-b678-64191e543f7c

It seems that it is when a buff is applied to the player..

**Comment by Pornoodemon** [comment]
The maximum health reserve does not change. It's as if you took off and then put on all the items again.
Perhaps you are changing sets of equipment?

**Comment by Nskaneki** [comment]
> The maximum health reserve does not change. It's as if you took off and then put on all the items again. Perhaps you are changing sets of equipment?

nop, i add a video who can explain better the problem.

**Comment by Pornoodemon** [comment]
Try again with this buff. If this is a pattern, then the problem is in the buff.

**Comment by Nskaneki** [comment]
> Try again with this buff. If this is a pattern, then the problem is in the buff. in the video, as if at the moment the buff is applied, stamina is recalculated and this resets your pet's HP to base HP

Yes, the bug is in the HP buffs i try with Druid buff and problem is the same.. in WarLocks occurs same problem?

**Comment by Pornoodemon** [comment]
I’ll check later, but most likely it’s only for DK. I didn’t notice this with warlocks

**Comment by UltraNix** [comment]
Fixed.
