### ISSUE TITLE
Ebon Imp 

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4177]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 Ebon Imp summoned by Bane of Doom - Has 2.5k HP
I have 120k hp he should have around 40-60k (I don't know the exact number)

![WoWScrnShot_081223_213400](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/6e6bf3ac-f600-4c8a-bd46-adce1a69c5d6)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Need any source of what hp should be

**Comment by Pornoodemon** [comment]
All I could find
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/465b5f74-d731-4056-a968-f7f43f54f4a2)

**Comment by Pornoodemon** [comment]
![WoWScrnShot_081323_154528](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/351ec40f-b5de-4497-a246-c11cd6ba3f80)
HP on Twinstar Appolo 25 k

**Comment by UltraNix** [comment]
Fixed.
