### ISSUE TITLE
Dimensional Ripper - Area 52 not working properly

### ISSUE THREAD

**Issue by Erregwyn** [gamefreedomgit/Maelstrom#4181]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Engineering trinket Dimensional Ripper - Area 52's debuff is removed upon shapeshifting into druid forms.

**How to reproduce:**
Shapeshift into any form with debuff up

**How it should work:**
Debuff should persist, even through death and shapeshifting

This item, like all transporters, has multiple types of results when used.
Works as expected
Boring....
Soul Sprit: Evil!
Only the dark half of your soul made it though the transport.
1 Hour uncleanable debuff
Makes you look all dark red and transparent.

**Database links:**
https://www.wowhead.com/tbc/item=30542/dimensional-ripper-area-52

**Comment by UltraNix** [comment]
Debuffs: "Soul Split: Evil!" and "Soul Split: Good" should be removed upon shapeshifting (blizzlike).
Other debuffs work okay.
