### ISSUE TITLE
Pillar of Frost Glyph not working correctly.

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#4182]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pillar of frost as the desciption states says it makes u immune to all loss of controll  cahracter effects when u have the Glyph

**How to reproduce:**
just stun or CC someone who should be immune but isnt

**How it should work:**

it should do what the glyph says it does
**Database links:**

https://cata-twinhead.twinstar.cz/?item=43553

**Comment by UltraNix** [comment]
Fixed.
