### ISSUE TITLE
Upon entering arena or battleground, buffs like "Brittle bones" or "Blood frenzy" stays on player or player pet.

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#4183]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon entering arena or battleground, buffs like "Brittle bones" or "Blood frenzy" stays on player or player pet.

Evidence: 1.Brittle bones: https://imgur.com/a/oy8rRH2
2. Blood frenzy(on player pet, but seen it on players too): https://imgur.com/a/K6VBHBx
**How to reproduce:**
Get debuff Brittle bones or Blood frenzy and enter battleground or arena.

**How it should work:**
Upon entering arena or battleground, every debuff should be removed.

**Database links:**

**Comment by UltraNix** [comment]
@MistrMattt Can you provide some evidence from retail?

**Comment by MistrMattt** [comment]
bruh, really? how am i supposed to do that? its since TBC arenas everytime u enter arena or BG every single debuff should be removed

**Comment by UltraNix** [comment]
Brittle Bones is weird, because I just tested and got removed every time I enter bg.

**Comment by UltraNix** [comment]
Fixed.
