### ISSUE TITLE
Player pets are not being healed to full during arena/battleground staging phase(before gates open).

### ISSUE THREAD

**Issue by ghost** [gamefreedomgit/Maelstrom#4184]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Player pets are not being healed to full during arena/battleground staging phase(before gates open).

Evidence from BG(Hunter pet) : https://www.youtube.com/watch?v=ocl3hUxXbJ0
**How to reproduce:**
Enter arena/battleground with low HP of pet.

**How it should work:**
Pets should heal to full during arena/battleground staging phase(before gates open).

**Database links:**

**Comment by MistrMattt** [comment]
I think that only happens to hunter pets? DKs summons to full hp. Will provide more evidence if i have some

**Comment by MistrMattt** [comment]
edited and added evidence from BG

**Comment by Renehadox** [comment]
Do you have some evidence from retail ?

**Comment by UltraNix** [comment]
Fixed.
