### ISSUE TITLE
[DRUID][GLYP] Glyph of Rejuvenation ( Not giving 10% instead 8.03% )

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4185]
# (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?spell=54754

Description:

Glyph of Rejuvenation

Currently only Increases the Healing Done by 8.03% instead of 10%.
Picture; https://imgur.com/a/369yV4E
Before Glyph 1658, After Glyph 1791
How to reproduce:

Use / Dont use Glyph and watch Difference in healing
How it should work:

Increases the healing done by your Rejuvenation by 10%.

**Comment by bonfax4** [comment]
You gotta keep in mind that talents and glyphs that increase % on specific spells most of the time work additively, not multiplicatively on these calculations. Not sure if that's the case for resto druid but that's the usual trend.

**Comment by UltraNix** [comment]
@bonfax4 is right. Already explained in two topics what this is about: #4190 and #4189
