### ISSUE TITLE
[DRUID][RESTORATION TALENTS] Improved Rejuvenation ( Not giving 15% instead 12% )

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4189]
# (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?spell=17113

Description:

Improwed Rejuvenation

Currently only increases the Healing Done by 12% instead of 15%
Picture: https://imgur.com/a/lmNX2YI
Before talent 1660, After Talent 1859
How to reproduce:

Use / Dont use talent Improwed Rejuvenation and watch Difference inhealing
How it should work:

Increase the healing done by your Rejuvenation by 15%

**Comment by UltraNix** [comment]
No talent tree:
![WoWScrnShot_081523_120226](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b69e0411-80d5-4d1c-8704-bea75124f8f6)

Resto tree without talent:
![WoWScrnShot_081523_120320](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/21c7a158-babe-4128-8964-e9ff7c1097e9)
healing multiplier = 25 (Gift of Nature) + 4 (Blessing of the Grove) = 29 / 100 = 0,29
1865 * 1,29 = 2405

Resto tree with talent:
![WoWScrnShot_081523_120534](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/e2e7388a-06ab-48a9-bf63-bdfa4f054105)
healing multiplier = 25 (Gift of Nature) + 4 (Blessing of the Grove) + 15 (Improve Rejuvenation) = 44 / 100 = 0,44
1865 * 1,44 = 2685.

As explained #4190 - % spellmods are additive.
