### ISSUE TITLE
Bug on the technique of hunter ferocity type pets: "heart of the phoenix"

### ISSUE THREAD

**Issue by Kroutenberg** [gamefreedomgit/Maelstrom#4191]
I would like to report a bug on the technique of hunter ferocity type pets: "heart of the phoenix".
Indeed, this technique almost never works, and above all it is impossible to use it in combat, which is very handicapping for a BM hunter in particular.
This ability should be able to be used instantly as soon as the pet is dead.

Thank you in advance for your help

Spell : https://www.wowhead.com/wotlk/spell=55709/heart-of-the-phoenix

**Comment by Kroutenberg** [comment]
Up please the spell is still bug its very annoying !! in fact it dont work when the pet is dead.. in fight or not. but I can use it when the pet is alive ! It's mad !
Please when can you fix this ?
Thanks

**Comment by UltraNix** [comment]
Remember that you can use it once per 8 minutes.

**Comment by Kroutenberg** [comment]
Of course ! But even when I use it for the first time (the CD is available), this dont work... It worked maybe twice over several months of play !!!

**Comment by UltraNix** [comment]
Fixed.

**Comment by Kroutenberg** [comment]
Thanks ! Good continuation
