### ISSUE TITLE
Anti-Magic Shell(Magic Suppression) 

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4192]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://wowpedia.fandom.com/wiki/Magic_Suppression

https://cata-twinhead.twinstar.cz/?spell=49611
Anti-Magic Shell  + Magic Suppression  Creates crazy rune regeneration
1 tick dot(1k damage) returns half the power of the runes

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/af2497f9-2668-472f-8411-344f5669d780

Proof 
https://youtu.be/zNQiw69IveY?t=31 
The video shows UDK and 3 Dot + it is attacked by frost dk
The video shows how the dk regenerates an average of 3-10 rune power from a dot tick(1-4 k damage) and up to 20 rune power from a frost dk hit.

There is a similar bug report on Twinstar, which describes the same problem when 3 ticks of the pillbox replenished 100 rune power, this was a bug and they fixed it.
The report itself is in Czech
https://cata-twinhead.twinstar.cz/?issue=7131#comments:id=105801

Proof in their report
https://youtu.be/eSBc7vDHA7M?t=391

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
This is medium priority?

But it gives a lot of rune regen?

**Comment by UltraNix** [comment]
Fixed.
