### ISSUE TITLE
Flare LoS

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4193]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
flare will not work if you throw it and then move out of LoS

**How to reproduce:**

https://clips.twitch.tv/QuaintSpoopyAlmondNotLikeThis-8LLVhAW58jMJ58gi

**How it should work:**
it should be possible to launch it and then move out of LoS

**Database links:**

**Comment by Sketish** [comment]
Provide any source

**Comment by bigticketx** [comment]
Yeah can confirm,this bug is so annoying

**Comment by Mongo69** [comment]
+1

**Comment by SimonBpvp** [comment]
> Provide any source

No source but every ground ability should work whether u go out of LoS or not. Think of smoke bomb, rof, d&d, trap launcher. U know?

**Comment by Afgann** [comment]
fixed
