### ISSUE TITLE
skull bash in root (not priority bug)

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4194]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://www.youtube.com/watch?v=StNCDCgPVu4

**Description:**
when u try to skull bash in root it does a phantom cast in the combat log or something, my addon (Juked) picked it up.
Visual/audio/combat log bug only but annoying

**How to reproduce:**
try to skull bash in a root, it might only work in melee range

**How it should work:**
just cast when youre not rooted

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
