### ISSUE TITLE
Hunter per Intervene fix

### ISSUE THREAD

**Issue by Gratwerwolf** [gamefreedomgit/Maelstrom#4196]
This Pet Talent is not working as it should. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/142199390/e0c633e2-c7af-4f8c-b134-1d75f784b63b)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/142199390/7c917e4d-094d-4e77-8190-83ee408a6ad8)

**Description:**
This skill should be broken only on direct damage
But All DoT Damage should be absorbed by it

**How to reproduce:**
1) Get a scorpion / crab ect 
2) Learn this skill in tallent tree 
3) Apply the shied on yourself or ally 
4) Apply any DoT damage and the shield will be removed from a single DoT tic as it was direct damage. 

**How it should work:**
All DoT Damage should be absorbed
Proof: 
https://www.youtube.com/watch?t=117&v=SMSj3jzoBRE&feature=youtu.be

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=53476

**Comment by Gratwerwolf** [comment]
Sorry forgot to mention
Skill descirption in the video 1:30-1:45
How it works during the game 1:49-1:59 

Please note that hunters are hard countered by DoT damage, hence this is very much usefull

**Comment by UltraNix** [comment]
Fixed.
