### ISSUE TITLE
1000 Needles - Quest - Missing boats

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4198]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the quest "Circle the Wagons... er, Boats" you need to sink some boats.
There are no boats, just floating dwarfs...

![5p](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/b6144915-d81c-4fa6-8b47-6ccf9bcf3cd5)

![5q](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/ebb2435d-c5b9-44f3-a6a5-50adf6224e06)

This is how it should be like

[Youtube Video](https://www.google.com/search?q=Circle+the+Wagons...+er%2C+Boats&oq=Circle+the+Wagons...+er%2C+Boats&aqs=chrome..69i57j33i160l2.407j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:f3fb8cf5,vid:UGUicNlq3BU)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/706c3990-44ee-4821-9d77-481c92f85ae1)

cannot reproduce
