### ISSUE TITLE
hp gorgule 10/10

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4199]
Whitemaine https://ibb.co/4J4JsB4 Dk hp 143k gorgule 68k
Official https://youtu.be/Tf1LiwVwfTE?t=939 dk hp 142k GORGULE 95k
Fast fix pls

**Comment by Renehadox** [comment]
Did you notice that he is in 4.3.4 Dragon Soul gear ? :D
Here we just started Firelands, there is a difference....

**Comment by UltraNix** [comment]
Fixed.
