### ISSUE TITLE
a small bug in Lost city of Tol'Vir

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#4201]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
okey at the last boss Siamat , on my hunter when i summon my pet after taking the wind funnel up to the boss's platform , my pet goes underground and just never comes out and it cannot attack either , friend of mine plays warlock and told me that his Imp works since it's range , it doesn't move .

**How to reproduce:**
just go to the last boss as hunter and summon pet and move .

**How it should work:**
pet suppose to stay on platform and attack with you instead of disappearing in the ground

**Database links:**

**Comment by UltraNix** [comment]
#2551
