### ISSUE TITLE
1000 Needles - Quest - The Mag Magus

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4202]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing "The Mad Magus" Quest, Two-Tusk should be resurected, but he is still a spirit.

![5r](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/1adec258-fadf-476d-8610-ab2c70f5134d)

This is how it should be:

Youtube [Video](https://www.youtube.com/watch?v=1lt2o2L2C14&t=116s)

**Comment by PanJanuszek** [comment]
fixed 09.05.2024
