### ISSUE TITLE
DRs in pvp

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4203]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
DRs (diminshing returns) are starting when the CC begins. This is why people are complaining about DRs not lining up with their addons and feeling wierdly short.

**How to reproduce:**
CC someone and wait 14 sec then u can cc them full again

**How it should work:**
DR timer should start when the CC ends, not begins, and last 18sec 

**Database links:**
https://gyazo.com/eb6e9d51448dc95d570d80ac399cf762
https://wowpedia.fandom.com/wiki/Diminishing_returns

edit: links

**Comment by UltraNix** [comment]
It's not static 18 sec, but dynamic 15-20 sec.

**Comment by bonfax4** [comment]
This doesn't sound right for pvp. Can't  you perma sap somebody if it works the way you describe it ?

**Comment by SimonBpvp** [comment]
I might have got the bug description wrong. DRs do not misbehave every time, they just bug SOMETIMES and u can cc again crazy soon. I saw it in soloq many times

Maybe I close the issue and look for some clips to make a new report
