### ISSUE TITLE
Always miss on druids

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4205]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is something wrong with druids on this server.

Whenever I hit balance, feral or a resto druid sometimes i miss him even tho i am above the hit rating capped.

Also i am expertise capped as well.

How can i miss a resto druid in tree form? Oo

Things need to be recheked...

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
You mean NE druids? If so, have you considered that Night Elves have passive Quickness, that reduces chance to be hit by 2%?

**Comment by Renehadox** [comment]
> You mean NE druids? If so, have you considered that Night Elves have passive Quickness, that reduces chance to be hit by 2%?

Yes but that happens very often my friend, its 2% and not 20%. :/

**Comment by UltraNix** [comment]
You have bad luck :P
2% per attack.

**Comment by UltraNix** [comment]
Yes- it is a 2%.
```
ID - 20582 Quickness (Racial Passive)
=================================================
Description: Reduces the chance that melee and ranged attackers will hit you by $s1%.

Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -2
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 184 (SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE), value = -2, misc = 0 (0), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -2
Targets (0, 0) (NO_TARGET, NO_TARGET)
Aura Id 185 (SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE), value = -2, misc = 0 (0), miscB = 0, periodic = 0
```

To make a more detailed report - just ask some night elf to be your training dummy and you can then test hit by yourself.

**Comment by UltraNix** [comment]
No further info - closing.
