### ISSUE TITLE
1000 Needles - Horde - Grimtotem questchain

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4206]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the Grimtotem chain, you will encounter ally forces that fight against the grimtottem.
These NPCs cannot be attacked by single target attacks, but do take damage from AOE, then they attack you.

They should either be "frenemyes", Orange but not hostile
Or they should be completly hostile, Red.

[Video](https://imgur.com/a/DpCK6v7)
*Note that I have a macro that auto targets and starts attack on the nearest enemy each time I cast a spell.

![5s](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/1a57fe4a-aea9-4566-ac0f-7514cbacf466)

**Comment by PanJanuszek** [comment]
fixed 09.05.2024
