### ISSUE TITLE
DK quest : how to win friends and influence enemies 

### ISSUE THREAD

**Issue by GM-Niamh** [gamefreedomgit/Maelstrom#4209]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
how to win friends and influence enemies quest is bugged for DK. You get a box but the box is empty

**How to reproduce:**
https://www.wowhead.com/wotlk/quest=12720/how-to-win-friends-and-influence-enemies

https://www.wowhead.com/wotlk/item=39418/ornately-jeweled-box

https://www.wowhead.com/wotlk/item=39371/keleseths-persuader

DKs need this item for the quest 

**How it should work:**
When the DK opens the box there should be an item in it thats needed for the quest.

**Database links:**
https://www.youtube.com/watch?v=1ITKiybuXNc&ab_channel=Rodwenn

Greetings,

GM-Niamh

**Comment by Afgann** [comment]
fixed
