### ISSUE TITLE
petfollow and gorgule

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4210]
https://github.com/gamefreedomgit/Maelstrom/issues/3836 why is this thread being ignored? 
[UltraNix](https://github.com/UltraNix): But gargoyle is not a pet - how it should follow the order?
ok, then repeat the moment on the video https://youtu.be/bQKxSBrudCA?list=PL0A530B197FF152BF&t=745  the gargoyle gives one hit to the dummy and stops and follows the death knight. do it exactly as in the video and you will understand that you can stop the gargoyle with the petfollow command

**Comment by pro100klass** [comment]
https://ibb.co/2WYWBX0  [UltraNix](https://github.com/UltraNix) what kind of macro is so interesting on a gargoyle???? tell me please

**Comment by Sketish** [comment]
Stop duplicating issues, and move this report to previous one
