### ISSUE TITLE
Fury Warrior-> Battle Trance + Bloodsurge bug

### ISSUE THREAD

**Issue by Kelt123** [gamefreedomgit/Maelstrom#4212]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fury Warrior issue > Bloodsurge occasionally consumes Battle Trance proc.

**How to reproduce:**
Spam Bloodthirst until you have both Bloodsurge and Battle Trance buff. Then use Slam ability and it usually will consume both (Bloodsurge and Battle Trance).

**How it should work:**
Battle Trance consumes abilities that cost more than 5 rage. Bloodsurge makes Slam rage free to use (therefore it is less than 5 rage). When you use Slam while having Battle Trance proc it shouldn't consume it.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=85742
https://cata-twinhead.twinstar.cz/?spell=46915

**Comment by UltraNix** [comment]
Just tested that for a couple min - everytime only Bloodsurge is consumed.

**Comment by UltraNix** [comment]
More further info - closing.
