### ISSUE TITLE
The Protectors of Hyjal npcs

### ISSUE THREAD

**Issue by Shakrei** [gamefreedomgit/Maelstrom#4213]
Due to some cross-faction shenanigans, the summoned npcs have a tendency to turn hostile and/or fight with other NPCs. They also seem overly aggressive and will lunge at any mob in sight rather than assisting the player with the mob currently tagged.
![WoWScrnShot_081523_195838](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/c357c90e-e179-467c-8ba9-31d7a0e2635b)
Resetting them (by flying out and into the zone) does not change their allegiance.
![WoWScrnShot_081523_195858](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/f9cedc0c-9759-46cd-9a28-33b81aa6c0d1)

**Comment by UltraNix** [comment]
Fixed.
