### ISSUE TITLE
Something is bugged with feral druids survivability 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
So I just was 1v1 vs a feral druid in WSG, he had 85k hp, which means that he just hit 85 level and he is in green gear.

It took me around 2-3 minutes to beat him 1v1 and im BiS geared.

When ferals go in bear form they just dont die, imagine what would have happened if i faced a feral with same gear like mine and same skills?

The damage reduction scaling or formulas needs to be rechecked.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Stop making such nonseless reports that tells nothing. If you have something to report, than fill the template and give us more details.

**Comment by Renehadox** [comment]
Are you joking or are you serious?
Nonseless reports?
I barely killed a starter geared feral druid man.
And i am BiS geared, how is it possible for a ret to barely kill a green feral ? lol
I don't know the spells name but something is definitely bugged there.
