### ISSUE TITLE
Shannox cleave

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4215]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Shannox turns around towards intended target whenever he casts spear, rupture, and even traps. When he turns toward his point he can also cleave, possibly one shotting melee hiding behind him on nm, and definitely one shotting melees on heroic.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=mA6Yu0xW5ZY&ab_channel=FatbossTV

He should delay his cleave until after he finished targeting something other than tank for his 3 spells.
You can see in this video he never cleaves when turned around, sometimes he does it right after he faces tank again.
**Database links:**

**Comment by UltraNix** [comment]
Fixed.
