### ISSUE TITLE
Bone Shield

### ISSUE THREAD

**Issue by ErikcBrou** [gamefreedomgit/Maelstrom#4216]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?spell=49222

Bone Shield -disappears only after 16 attacks!!!!!

should disappear after 6 attacks.
The description says that "each" damaging attack  removes 1 charge
There is also a discussion on how it should work with dot 
https://cata-twinhead.twinstar.cz/?issue=19099#comments:id=131896

https://github.com/gamefreedomgit/Maelstrom/assets/142408640/19ac1dc0-315d-4902-936b-020d2c0bc803

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
As I can see, right now we have 3 sec cooldown on proc that. Is that valid?

**Comment by ErikcBrou** [comment]
> 

https://youtu.be/6K31OGXJLCc?t=94


> Из вашей ссылки:
> 
> ```
> At a minimum, Bone Shield can drop a stack every 2000ms.
> ```

This is a discussion on the topic dot.
Ns how can I say that the bone shield resets the charge in less than 2 seconds (from 4 charges to 3) for 1 second

**Comment by ErikcBrou** [comment]
As far as I understand, 2000ms. this is for dot damage .

**Comment by UltraNix** [comment]
```
the bone shield resets the charge in less than 2 seconds (from 4 charges to 3)1 second
https://youtu.be/6K31OGXJLCc?t=94
```
For me it's definetely not 1 sec :)

**Comment by UltraNix** [comment]
https://web.archive.org/web/20120823072140/https://www.wowhead.com/spell=49222#comments:id=433229:reply=225106
Another comment saying it's not only dots.

**Comment by ErikcBrou** [comment]
> ```
> the bone shield resets the charge in less than 2 seconds (from 4 charges to 3)1 second
> https://youtu.be/6K31OGXJLCc?t=94
> ```
> 
> Для меня это определенно не 1 секунда :)
> 
> https://www.wowhead.com/wotlk/spell=49222/bone-shield#comments Я вижу, они добавили эту информацию во всплывающую подсказку.



> https://web.archive.org/web/20120823072140/https://www.wowhead.com/spell=49222#comments:id=433229:reply=225106 Еще один комментарий, в котором говорится, что это не только точки.

You are right, but the charges should also be removeod for dot (Perhaps this is onli in cata)

**Comment by ErikcBrou** [comment]
on Cataclysm Increased the number of charges . And the video shows how the charge disappears from the dot
https://youtu.be/Jlff5p1OBhM?t=462

**Comment by UltraNix** [comment]
About DOTs, I see on wowpedia:
https://wowpedia.fandom.com/wiki/Bone_Shield?oldid=3045871
`
[AoE](https://wowpedia.fandom.com/wiki/AoE)'s, [DoT](https://wowpedia.fandom.com/wiki/DoT) ticks, auras and [bleeds](https://wowpedia.fandom.com/wiki/Bleed) do not consume bones.
`

**Comment by UltraNix** [comment]
Okay - that proof is enough for me.

**Comment by ErikcBrou** [comment]
> Okay - that proof is enough for me.

I don't know for sure. Maybe it's just for the cataclysm.
It's just that the video shows how it is removed from dot
https://youtu.be/Jlff5p1OBhM?t=391

**Comment by UltraNix** [comment]
Fixed.
