### ISSUE TITLE
Glyph of Anti-Magic Shell

### ISSUE THREAD

**Issue by ErikcBrou** [gamefreedomgit/Maelstrom#4217]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?item=43533#created-by

Glyph of Anti-Magic Shell

After using this glyph, Anti-Magic Shell absorbs 100% damage in any talent tree
It should only extend the duration by 2 seconds and nothing more

https://github.com/gamefreedomgit/Maelstrom/assets/142408640/4e967956-d7a6-45df-9f9c-16c6ba21cc4b

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
Thats why DK's are so OP here and they take 0 damage under anti magic shell... now i get it... Thanks for the report, lol.

**Comment by UltraNix** [comment]
101015
