### ISSUE TITLE
Chakra: Santuary

### ISSUE THREAD

**Issue by Zaraelh** [gamefreedomgit/Maelstrom#4218]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: Chakra: Sanctuary is no longer increasing 15% to Renew Spells and AoE Spells like Divine Anthem, Prayer of Healing, Circle of Healing, Holy Nova. For example, with the help of the Dr Damage addon, I can see that my anthem's critical average without chakra is 70334. If we do the calculation, it would be 70334*0.15 + 70334. I would have to get the Chakra increase: Sanctuary 15%, a total of 80884 healing , but this is not happening, it gives me a 75242 healing.**
**Database links: https://imgur.com/YqxchDT (Chakra: sanctuary not activated) 
https://imgur.com/FExCcNQ (Chakra: Sanctuary Activated) 
https://cata.cavernoftime.com/spell=14751**

**Comment by djesic** [comment]
+1 for this
Renew doesn't heal 15% more

**Comment by UltraNix** [comment]
All spellmods are additive, not multiplicative. It's not simple +15%.

On your screen, I see Divine Hymn giving 15080 healing and with Chakra - 16133. Even DrDamage addon is updating these values okay.

Tested in naked char, with no spellmos and auras.
Without Chakra:
Renew:
![WoWScrnShot_090723_193943](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/5df5eb62-e026-48d3-af5d-571c23e3c8df)
Divine Hymn:
![WoWScrnShot_090723_194009](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/c196099a-3972-465c-9ee8-63aedad4ef47)

With Chakra:
Renew and Divine Hymn:
![WoWScrnShot_090723_194056](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9a3fa455-023c-4489-b7e4-f8d64b0a1e9e)

No bug here.

**Comment by djesic** [comment]
Something must have gotten fixed, because just entering chakra didn't increase the healing of renew when I made the +1 post
