### ISSUE TITLE
Moonwell and Mooncloth (Tailor Priest Level 36) how and where to craft?

### ISSUE THREAD

**Issue by Udnossidos** [gamefreedomgit/Maelstrom#4220]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi, i try to craft mooncloth, but there isn't a moonwell in SW anymore and the one in the temple in darnassus doesn't recognize me standing in it.
I even rode to the moonwell west of Darnassus, And there it finally worked.
Where do I craft my mooncloth then as a Level 36 Human Priest without so much effort?

**How to reproduce:**

**How it should work:**
Any Moonwell should do the job

**Database links:**

**Comment by Udnossidos** [comment]
I don't understand.
You mean, that the one in Darnassus (there are even two moonwells!) isn't supposed to work?
Or you want a screenshot proving, it isn't working?
Anyways... here are 3 screenshots. 2 of darnassian moonwells, 1 of the moonwell in oracle glade (near Darnassus) where it works. Note the castbar under the character bar.
![___moonwell-temple-darnassus](https://github.com/gamefreedomgit/Maelstrom/assets/42095747/946c2d8a-b120-46fd-8b0a-674f2bb493e6)
![___moonwell-darnassus](https://github.com/gamefreedomgit/Maelstrom/assets/42095747/7b82a1c5-0f9e-4471-8f12-b6620d794ef7)
![___moonwell-oracle-glade](https://github.com/gamefreedomgit/Maelstrom/assets/42095747/7587debf-d7e7-45e6-b1ab-e405edfa31cd)

**Comment by UltraNix** [comment]
There is one Moonwell in Darnassus - at the Howling Oak.
