### ISSUE TITLE
[QA] Firelands 10 - HC

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#4221]
**Shannox**
--------------------------------------
Either Rageface or Riplimb can be slowed with stuff such as Shadowflame slow. Either way, it didn't look natural on Rejects kill.

--------------------------
**Ragnaros**
------------------------
~Charging Ragnaros as warrior/feral, brings you way into the lava. It should put you on the edge of the ledge of the lava.
~Sometimes lava is not dealing any dmg to players [VIDEO](https://www.twitch.tv/videos/1900366775?t=05h55m50s)
~Intermission phases: Sometimes Sons of Flame spawn too close to the hammer and due to Whitemane's unusual large hitboxes, the Sons instantly explode on some variation of spawns where Son of Flame spawns too close to the hammer.
~ Molten Elementals ( Seeds ) in P2: They don't get the damage amplification stacks when close to eachother. They basically hit as hard as normal mode Seeds when grouped up.
~Molten Elementals ( Seeds ) are able to be knocked back, which is not blizz-like on heroic difficulty.
~Molten Elementals randomly fixate on different players, Instead of each seed being designated to each player, sometimes there would be 2-3 seeds attacking the same person. Fixing the damage the deal when they're stacked, then it would be crucial to fix that aswell.
~P3/P4 meteors: They have the tendency to go underneath the floor when knocked either out of the p1-3 platform, or onto p4 platform, temporarily going under the platform and resurfacing later and wiping the group. 
~Knocking meteor in P4: (Not confirmed, suspect tho), Something knocking a meteor towards the raid, and not away. [VIDEO](https://clips.twitch.tv/BenevolentHealthyStarlingDendiFace-tDzqHEStAwURJq9M)
~Burning Wound debuff that Ragnaros applies to the main tank deals way too much damage. A bdk is doing 25-30k dps which is mostly from burning wound.

Credits : Nezter.
**Please put any bug you notice on this report.**

**Comment by Polynomix** [comment]
On alysrazor, the thing that makes us mount the big fire hawk trash mob before the boss were still there. So we kept clicking on it by accident during alys fight

https://clips.twitch.tv/HardTrappedCheeseHassaanChop-aqM-ggLYO9lPW-2Z

**Comment by UltraNix** [comment]
@Polynomix Please - make a new repoer about this as I'm closing this one.
