### ISSUE TITLE
QUEST BUG: Dragon, Unchained

### ISSUE THREAD

**Issue by Deukless** [gamefreedomgit/Maelstrom#4222]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Quest ID: 27701
https://www.wowhead.com/quest=27701/dragon-unchained

**Description:**
Free Lirastrasza

**How to reproduce:**
Lirastrasza is missing, she was supposed to be chained between 3 pillars on Twilight Cidatel, near Loch Verall

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
This part of TH is not scripted yet, please read information when entering zone
