### ISSUE TITLE
346 JUSTICE POINT ITEM LEVEL ITEMS NOT IN THE GAME

### ISSUE THREAD

**Issue by Nikaidoz** [gamefreedomgit/Maelstrom#4223]
**Description:**
Toren Landow used to sell 346 Item level items before 4.2 came out. They could be bought with Justice points. With the release of the Firelands patch, this vendor doesn't sell the items anymore. Those items were always in the game even during patch 4.3.

**How to reproduce:**

Every time you talk to the vendor, the items don't show up. 

**How it should work:**
The Vendor should always sell the 346 item level items that can be bought with JP (Justice points)

**Database links:**
[//]: # https://www.wowhead.com/npc=58154/toren-landow
[//]: # https://wowpedia.fandom.com/wiki/Toren_Landow

**Comment by kekonomics** [comment]
#4375 
^ This is the same issue, except it refers to the equivalent vendor in Orgrimmar.

**Comment by UltraNix** [comment]
Part of the 4.3 content - the current vendors are designed for the 4.2 version.
