### ISSUE TITLE
Issue with Alysrazor boss "Initiate"

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#4225]
There is a problem with [Alysrazor](https://www.wowhead.com/npc=52530/alysrazor/her%C3%B3ico-10-gu%C3%ADa-de-mazmorras) initiates, the problem is in the "[Brushfire](https://www.wowhead.com/spell=98868/brushfire)" ability, summoned by [Blazing Talon Initiate](https://www.wowhead.com/npc=53611/blazing-talon-initiate), it turns out that this spell moves very fast, when it shouldn't.

It should behave as seen in the following video:
https://youtu.be/mFX27gHv7SM?t=45
minute 0:45 "[Brushfire](https://www.wowhead.com/spell=98868/brushfire)" it moves slowly throughout the raid and doesn't shoot out like a missile.

En Whitemane sale disparado como un misil.

**Comment by UltraNix** [comment]
Fixed.
