### ISSUE TITLE
Firelands - Alysrazor Melee Hitbox P4

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4226]
**Description:**
Currently, the melee hitbox for Alysrazor in P4 when he reignites is significantly smaller than it should be. 

**How to reproduce:**
Get to Phase 4 of the Alysrazor encounter and try to melee Alysrazor - you will find that you have to be standing inside his model to attack.

**How it should work:**
You should be able to hit the boss safely from a further range as seen in this video from retail at the 6:15 mark
https://www.youtube.com/watch?v=pq9SsY-bqrI&ab_channel=EmilTh%C3%B8gersen

**Comment by UltraNix** [comment]
Fixed.
