### ISSUE TITLE
Nexus legendary quest

### ISSUE THREAD

**Issue by Elemele9** [gamefreedomgit/Maelstrom#4229]
https://www.wowhead.com/quest=29194/through-a-glass-darkly

**Description:**
The last part of the solo scenario where you have to jump on platforms is bugged if you die. Penultimate platform doesnt spawn two smaller platform with small adds. Because of that you get stuck on the platform and nither you can go on the bridge or next platform.

**How it should work:**

There should be two more adds and after you kill them you should be able to jump on last platform or directly to the bridge (it works like that with first attempt- its only bugged if you die on the last boss)

Moreover if you fall down from the platform you have parachute and bc of that you cant die- you just stuck somewhere on the bottom- there is no possibilty to get out from there. I think person should die if someone falls- would be easier just to release and go into instance again

**Comment by VirtualReign** [comment]
I'd like to add, Ceredos's Spellflame does not only instantly kill in melee range, it seems to have at least twice the range intended. You can check the intended range, 3.3s cast time and the animation that is currently missing here:

[darklink428 - Through a Glass, Darkly - Part 1 (timestamp 13:17)](https://youtu.be/0qudG2YzqIk?t=797)

Also the portals allowing players to move to the last progressed part were missing most of the time (I'd only seen them once and once I died they disappeared again).
