### ISSUE TITLE
Ragnaros Heroic - dreadflame

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4230]
**Description:**
When players goes through dreadflames it should leave a dot on them which will kill them over time. Also dreadflame does 0 damage
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/54d6f83c-7f7d-4145-9384-d4bbde5eaf0b)

**How to reproduce:**
Pull Ragnaros heroic and walk into dreadflames on last phase.
**Database links:**
https://wowpedia.fandom.com/wiki/Ragnaros_(Firelands_tactics)

**Comment by UltraNix** [comment]
Fixed.
