### ISSUE TITLE
blazing monstruosity vehicle not despawning

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4231]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

On alysrazor, the thing that makes us mount the big fire hawk trash mob before the boss were still there. So we kept clicking on it by accident during alys fight

https://clips.twitch.tv/HardTrappedCheeseHassaanChop-aqM-ggLYO9lPW-2Z

**How to reproduce:**
I don't know we had the left one and not the right one

**How it should work:**

Thing should despawn

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
