### ISSUE TITLE
Quest bug "Supplies for the Other Side"

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#4234]
Quest: [Supplies for the Other Side](https://www.wowhead.com/quest=29166/supplies-for-the-other-side#comments) 

["Blueroot Vine"](https://www.wowhead.com/quest=29166/supplies-for-the-other-side) item cannot be looted.

Apparently only those with the Herbalism profession can loot it.

**Comment by UltraNix** [comment]
Clearing cache should help.
