### ISSUE TITLE
petfollow and gorgule #4210

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4235]
https://github.com/gamefreedomgit/Maelstrom/issues/4210 why are you closing threads?

**Comment by Sketish** [comment]
Beacuse you keep duplicating reports about same issue :)

**Comment by pro100klass** [comment]
> Потому что вы продолжаете дублировать отчеты об одной и той же проблеме :)


I don't have an open topic for this bug
