### ISSUE TITLE
Firelands - Bridge to Majordomo is not loading correctly

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4237]
**Description:**
If person is not near baleroc room when room is being activated then you cant's see bridge and you fall under textures.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/26085606-4765-4ef9-bf2a-8c04739a9dd4)

**How it should work:**
You should be able to to launch bridhe and everyone inside should be able to see it

**Comment by UltraNix** [comment]
Fixed.
