### ISSUE TITLE
(Combat bug) Cast spells refreshing Out of Combat time ?

### ISSUE THREAD

**Issue by Muslym** [gamefreedomgit/Maelstrom#4239]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When you cast a Non-combat spell like polymorph, blind, repentance etc... it shouldnt refresh TTLC(time to leave combat) duration, because the spell doesnt put you in combat. It makes a lot of things unplayable because of this bug in pvp.

**How to reproduce:** Cast a spell who put you in combat, wait almost 4 seconds (out combat duration is 6sec) then it will refresh the TTLC (time to leave combat)

**How it should work:** 

https://github.com/gamefreedomgit/Maelstrom/assets/142475034/1e9319c2-9fae-432e-ab4c-f7e7fb28e548

https://github.com/gamefreedomgit/Maelstrom/assets/142475034/dae11caf-d388-4523-8b12-ae67eda3709f

**Database links:**

**Comment by Muslym** [comment]
https://streamable.com/c3vy02 (blind doesnt combat) 
https://streamable.com/ik1ssy (why im still in combat ???)

**Comment by Sketish** [comment]
Please provide any source to proof that

**Comment by Pornoodemon** [comment]
> Please provide any source to proof that

https://github.com/gamefreedomgit/Maelstrom/issues/4238
On this topic, it is also desirable to provide some kind of evidence. I have not heard anything like this in any video or guide on robbers on cata, but the fact that a robber can take damage under a shield and not go out of invisibility

**Comment by Kenniflopper** [comment]
Confirmed, combat behaves very weird, u can stay afk for 20 seconds sometimes in arenas and never leave combat even though ur not healing or damaging or buffing.

**Comment by UltraNix** [comment]
#3375
