### ISSUE TITLE
Shannox dog - Face rage spell

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4241]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During face rage all attacks against rageface should be crits. Currently both on nm and hc you sometimes don't crit.

**How to reproduce:**
Carefully check your attacks towards the dog while he channels spells and you'll see some non crits. We had a shaman with stacked earth shock for example, sometimes didn't crit, others reported non crits as well.

**How it should work:**
All attacks done to dog while face rage is cast should be crits.

**Database links:**
Some details from Ultranix in the mega thread:
Cataclysm [Hotfix](2011-07-14):
Successful attacks on Rageface will now always be critical strikes while he is channeling Face Rage.

**Comment by Sketish** [comment]
Pre nerf its increasing by 50% so not a bug

**Comment by BalanCV** [comment]
@UltraNix you asked me to open post for this now this guy closes
