### ISSUE TITLE
Hunt pet's spell "Heart of the Phoenix" bug !

### ISSUE THREAD

**Issue by Kroutenberg** [gamefreedomgit/Maelstrom#4243]
Hi ! I want to report a very annoying bug on the spell of ferocity hunter's pet : ["Heart of the Phoenix"](https://cata-twinhead.twinstar.cz/?spell=55709)

Indeed, it's impossible to use this spell when our pet is dead, in fight or not, while it is precisely supposed to resuscitate it.
But we can use the spell when the pet is alive (it's useless of course) !

We should be able to use this spell right after the pet dies, in fight or not, to instantly resuscitate it.

Its very annoying especially for BM hunters in PvP.

Thanks for your help !

**Comment by UltraNix** [comment]
#4191
