### ISSUE TITLE
Shannox - Attacking rageface during Face rage isnt a guaranteed critical strike

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#4244]
During his Face rage, all damage on him should be a critical strike

"Cataclysm Hotfix (2011-07-14):
Successful attacks on Rageface will now always be critical strikes while he is channeling Face Rage."

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/220c7bab-c643-4a03-8790-63046b79fdd5)

https://worldofwarcraft.blizzard.com/en-us/news/3019413/patch-42-hotfixes

**Comment by Sketish** [comment]
We have pre nerf version when its increasing crit chance by 50%, after nerf it was 100% . Not a bug

**Comment by jlldarocha** [comment]
this was hotfixed 1 week into the patch, during the first heroic week, its hard reaching to consider as a "nerf".
