### ISSUE TITLE
Shannox - Separation anxiety triggers on dead dog

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4245]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you kill rageface and pull both riplimb and boss away from his corpse, rageface's corpse still counts for distance enrage for the boss even if he's dead.
Not entirely sure this is a bug but it definitely feels non-intended. I'll leave this here and let the people knowledgeable on this decide.

**How to reproduce:**

**How it should work:**
Dead dog not counting for distance enrage from corpse to boss?

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
