### ISSUE TITLE
error en el poder del dk simulacion oscura 

### ISSUE THREAD

**Issue by alarakitoh94tlv** [gamefreedomgit/Maelstrom#4246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
no se ve correctamente que hechizo se robo y es un retrazo a la hora de hacer cc o daño

**How to reproduce:**

se supone que deberia de poder verse el hechizo robado
**How it should work:**
deberia verse el hechizo robado

**Database links:**
https://www.youtube.com/watch?v=GJpblsC53fs

**Comment by UltraNix** [comment]
@alarakitoh94tlv Poke me on Discord.

**Comment by UltraNix** [comment]
No further info - closing.
