### ISSUE TITLE
The Wardens are Watching

### ISSUE THREAD

**Issue by Lukabxjx** [gamefreedomgit/Maelstrom#4248]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest doesnt work. Druid of the Flame doesnt wanna go in to the trap(its afk).

**How to reproduce:**
Go to one of the Druids, lower it down, wait for the trap, nothing.

**How it should work:**
Druid of the Flame should go in to the trap and get captured.

**Database links:**
https://www.wowhead.com/quest=29192/the-wardens-are-watching
https://www.youtube.com/watch?v=PJjyjtY8bJU&ab_channel=TheKODO-GamingandRandomTutorials

**Comment by PureCnupTuk** [comment]
thats how it works(not) or server atm 
https://www.youtube.com/watch?v=qBnE854MwUQ&ab_channel=%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2

**Comment by UltraNix** [comment]
Fixed.
