### ISSUE TITLE
Shrine of Aviana and Druid of the Talons

### ISSUE THREAD

**Issue by Tempatchi** [gamefreedomgit/Maelstrom#4250]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Skylord Omnuron wont spawn, and the quest A Bird in Hand, is uncompleteable.

**How to reproduce:**
Hard to guess. During my initial levelling in Mount Hyjal the quest "A Bird in Hand" bugged out. Whenever i completed the quest objective i didnt get credit for completing the quest. After several tries I abandoned the quest, and moved on. 

The quest is still uncompleteable for me, whenever i go near any of the braziers used to summon the named NPC, they despawn before i can reach them - looks alot like a phasing issue. 

On another note, that MIGHT be related: I can't see Skylord Omnuron, for the Druids of the Talon dayli quests. I've gathered 150 Mark of the World Tree, but he just wont spawn. 

**How it should work:**
Quest should be completeable and Skylord Omnuron should be visible. 

**Database links:**
https://www.wowhead.com/npc=40997/skylord-omnuron
https://www.wowhead.com/quest=25731/a-bird-in-hand

**Comment by UltraNix** [comment]
@Tempatchi Have you completed https://www.wowhead.com/quest=25372/aessinas-miracle ?

**Comment by UltraNix** [comment]
Fixed.
