### ISSUE TITLE
Missing Molten Front NPC - Commander Jarod Shadowsong

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#4252]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon completion of various Mount Hyjal quests, the NPC Commander Jarod Shadowsong should appear inside the Molten Front in the first daily quest hub area. He is required in order to complete the Molten Front achievement "Fireside Chat". However, the NPC is nowhere to be found.

**How to reproduce:**

**How it should work:**
The NPC should be standing near the small cave entrance inside the Molten Front

**Database links:**
https://www.wowhead.com/npc=52134/commander-jarod-shadowsong#comments

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d027b141-0457-4f85-9ca7-31867cb3ff50)
Can you confirmed you completed those quests ?

**Comment by emirie1** [comment]
Screenshots from the addon Quest Completist showing completed quests.
![WoWScrnShot_082023_121800](https://github.com/gamefreedomgit/Maelstrom/assets/130517865/9fbfe73a-cbc5-4604-9aba-5d94242b7d44)
![WoWScrnShot_082023_121817](https://github.com/gamefreedomgit/Maelstrom/assets/130517865/1161340d-2ed2-4bf3-a73e-7c43f56a3ff1)

Screenshot showing my achievement for completing 115 quests in Hyjal being achieved on 4/14/23
![WoWScrnShot_082023_121912](https://github.com/gamefreedomgit/Maelstrom/assets/130517865/73123ff1-fb79-4e4a-aa2d-3f425d4ac120)

Screenshot showing the Gates of Sothann area in Hyjal where the quest "Slash and Burn" starts (with low level quests tracking turned on).
![WoWScrnShot_082023_122259](https://github.com/gamefreedomgit/Maelstrom/assets/130517865/7be04619-4473-4f45-8950-4ac99bb2c1a4)

**Comment by UltraNix** [comment]
Fixed.
