### ISSUE TITLE
Molten Front: mobs from another phase/layer are attacking warlock pets

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#4254]
I started questing in Molten Front on my warlock yesterday and was wondering why I'd been taking so much more damage than on my other characters.

Turns out I'd had mobs from another phase or layer (or maybe even underground) somehow aggro my pets and then proceed to attack me as well. Just today I'd noticed Ancient Charhounds attack my pets while questing there (the pet was getting knocked around and kept losing health which prompted me to have a look at the combat log).

The mob wasn't visible nor were they the objective of any quests today. When the pet died, the mob proceeded to attack me.

![MF-Phasing](https://github.com/gamefreedomgit/Maelstrom/assets/52958317/864a855c-07f7-4750-8716-4bcfa29dab52)

**Comment by UltraNix** [comment]
@VirtualReign Need more info. Where that happened (exactly on map)? What quests were you doing?

**Comment by VirtualReign** [comment]
I was killing the lone Molten Giant in the corner to the left of the border between the area just outside the sanctuary/base and the area with the lava pools behind it when suddenly the pet started being knocked back and taking damage. There's actually no other mobs in that particular area but a neutral scorpion so it was really obvious something was amiss.

**Comment by UltraNix** [comment]
@VirtualReign Remeber what quests you had in questlog (I need that info to determine your phase)?

**Comment by VirtualReign** [comment]
@UltraNix It was quests from the first set after you gain entry into the Molten Front. It was like second or the third day doing the dailies so I hadn't yet completed either of the two 150 mark quests that open up the zone further.

**Comment by VirtualReign** [comment]
I'd encountered the bug again, this time on a character a bit more progressed (I'd completed one of the 150 marks quests).

You can see I'm fighting a Lava Burster here that has no visible body, its nameplate also kept popping in and out of phase. Moments before it engaged me I also saw an Ancient Charhound spawn briefly and disappear right after, then it attacked my Lasher guardian pet provided for one of the quests and started knocking it around.

![MF-Phasing-2](https://github.com/gamefreedomgit/Maelstrom/assets/52958317/a0c7c013-6d7a-44ae-9591-6fdbe99f8c72)

**Comment by UltraNix** [comment]
@VirtualReign Poke me on Discord.

**Comment by UltraNix** [comment]
Fixed.
