### ISSUE TITLE
Disable Class stacking in solo que, it ruins the game play...

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Class stacking in solo que is not blizzlike and it is ruining the fun and gameplay of everyone especially on a high mmr level.

Double paladin, double priest or double shaman is not a good option vs a lot of combos.

I lost over 200 rating by playing Ret Paladin, Disc Priest, Shadow priest, thats not even a combo.

We will wait 10-15 minutes if we have to for a game but please disable class stacking for the sake of everybody.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Not a bug
