### ISSUE TITLE
Entering battlegrounds while in combat aka to escape world pvp or any other means of abusing world pvp.

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#4258]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
Screenshot of the article specified regarding entering battleground while in combat : https://prnt.sc/D23s20m8sYvL
Entire article regarding battlegrounds : https://wowpedia.fandom.com/wiki/Battleground

**Description:**
Lately alot of people do world pvp and when they are about to die they just escape to battleground to avoid death.
As it is written on site above entering battleground while in combat shouldnt be possible.
Hopefully it will be fixxed so people dont abuse something that shouldnt be possible.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
