### ISSUE TITLE
[Molten Front Questline] The Shadow Wardens and Druids of the Talon turn-in NPCs are not phased.

### ISSUE THREAD

**Issue by kekonomics** [gamefreedomgit/Maelstrom#4259]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Self-explanatory, NPCs for [The Shadow Wardens] and [Druids of the Talon] are not phased or are otherwise missing even though quest criteria (150 marks) shows as complete.

**How to reproduce:**
Go to turn-in locations for both of the above quests after acquiring 150 marks. "?" shows on the minimap, but there is no NPC in world to turn the quest in.

Edit: GM instructed me to delete cache folder and restart client. Problem persisted.

**How it should work:**
NPCs should be visible.

**Database links:**
Shadow Wardens: https://www.wowhead.com/quest=29214/the-shadow-wardens#
Druids: https://www.wowhead.com/quest=29181/druids-of-the-talon#comments

![Talon turnin](https://github.com/gamefreedomgit/Maelstrom/assets/132790862/f37ca213-754f-4dea-bd55-c63a1cd2dddf)
![Warden turnin](https://github.com/gamefreedomgit/Maelstrom/assets/132790862/27787cc8-c235-4bc7-ad28-5598822b0b66)

**Comment by Shakrei** [comment]
Wardens - Saynna is standing a bit closer to the fountain bit, the question mark doesn't match. She's beside the Leatherworking supplier.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130383518/fd1a75ba-2a0c-476f-9aa2-be846d212b5b)
I had the same issue on PTR with talons, strangely enough taking a flight path to Shrine of Aviana seemed to fix it for me - specifically a flight path, not just going there by myself.

**Comment by DartImpact** [comment]
which route?
Tried them all and it didn't work for: Skylord Omnuron <Druid of the Talon>

**Comment by DartImpact** [comment]
> Wardens - Saynna is standing a bit closer to the fountain bit, the question mark doesn't match. She's beside the Leatherworking supplier. ![image](https://user-images.githubusercontent.com/130383518/262158576-fd1a75ba-2a0c-476f-9aa2-be846d212b5b.png) I had the same issue on PTR with talons, strangely enough taking a flight path to Shrine of Aviana seemed to fix it for me - specifically a flight path, not just going there by myself.

which route?
Tried them all and it didn't work for: Skylord Omnuron Druid of the Talon

**Comment by Shakrei** [comment]
> > Wardens - Saynna is standing a bit closer to the fountain bit, the question mark doesn't match. She's beside the Leatherworking supplier. ![image](https://user-images.githubusercontent.com/130383518/262158576-fd1a75ba-2a0c-476f-9aa2-be846d212b5b.png) I had the same issue on PTR with talons, strangely enough taking a flight path to Shrine of Aviana seemed to fix it for me - specifically a flight path, not just going there by myself.
> 
> which route? Tried them all and it didn't work for: Skylord Omnuron Druid of the Talon

Just did the usual hyjal>shrine of aviana and by some miracle it phased me. Might just have been a fluke though. Did you find the other one then?

**Comment by UltraNix** [comment]
#4242
