### ISSUE TITLE
Baleroc - holy paladin beacon healing

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4262]
**Description:**
Currently if paladin have Vital Spark buffs and puts beacon on other player than tank, beaconed target also get increased healing
 which is not blizzlike.
**How to reproduce:**
Need 3 characters
1: tank with Blaze of Glory stacks
2nd Paladin with Vital Spark stacks( 100)
3rd any char which has beacon

Have hpala cast direct heal on tank to force buff to swap
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d7e43ce1-0ba7-4fab-abb5-9c653c05e5da)
Notice if paladin will keep healing tank the target with beacon also get increased healing which shouldnt happen

**How it should work:**
Beacon should copy basic healing value of spell instead of modified one.

**Comment by UltraNix** [comment]
Fixed.

**Comment by amanita199** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129459223/f8856626-13ec-43eb-89fd-0b7c4fca9a20)

was looking for info about the holy palas that solo healed bale hc back in retail, found this. didnt try it yet but hope this is working

https://www.mmo-champion.com/threads/1023359-Baleroc-10-hc-solo-heal

**Comment by Sketish** [comment]
Yes, if you use beacon on tank then he has multipied healing from vital sparks

**Comment by rkkkid** [comment]
now beacon copies 0 healing value instead of the basic numbers when beaconed players have Torment debuff. Is that normal?

**Comment by Sketish** [comment]
Provide any screenshot please

**Comment by rkkkid** [comment]
![6063231d9a6276743e13a24d87accb5](https://github.com/gamefreedomgit/Maelstrom/assets/143116320/d45eb819-2451-4d58-a404-ee9b7c70446f)

its a non-English client screenshot but see the spell icon as a proof
