### ISSUE TITLE
Baleroc - Shaman's Elementals Soaking Shard of Torment

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4266]
**Description:**
For some reason, a Shaman's Elementals can occasionally soak the Shard of Torment

**How to reproduce:**
Have a Shaman pop their Elementals on any of the Shard of Torments and see if they soak Shard of Torment from an existing player that is currently soaking the shard.

**How it should work:**
The elementals shouldn't be able to soak any of the Shard of Torments in the encounter.

**Relevant links:**
https://clips.twitch.tv/CrazySmoggyDiamondPogChamp-BmUvUVj8gKCiRWWN

**Comment by Igria123456** [comment]
Fire elemental can also hit and kill the first shard before it fixates to Baleroc (can post proof when i get to PC)

**Comment by UltraNix** [comment]
Fixed.
