### ISSUE TITLE
[Warlock] Pet issues

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4267]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

- Succubus lash of pain has a wrong crit multiplier. 
- Torment doing less dmg than expected.
- Voidwalker torment ability should be able to crit.
- Felguard felstorm dmg is off.

**How to reproduce:**

**How it should work:**

- Lash of pain crit multiplier should be 199.5% like every other pet/class spell.
- Voidwalker torment ability either has the wrong formula or multischool abilities are not being properly handled. Torment is a [shadowstrike ](https://wowpedia.fandom.com/wiki/Shadowstrike_(spell_school)) and as such should pick the lowest of either armor or shadow resistance, depending on which is lowest. Tested on a 85 dummy which i'd assume has shadow resis as the lowest stat but my torment dmg was lower than expected.
- Torment should be able to crit.
- Felstorm dmg is off by a huge margin, think it's double dipping mastery and possibly orc racial. Formula might be using weapon dmg ( already affected by mastery and racials ) instead of pet dmg before modifiers. My napkin math actually tells me its possibly triple dipping mastery.

Torment [dmg formula](https://www.wowhead.com/spell=3716/consuming-shadows#changelog) is (729 + (0,512 * (SP * 0,5))) 

Lash of pain crit multiplier on simc and dr damage
![a87d21ac8a8d23b5cdb49a58a1c7b0ac](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/e33f319c-d3f6-4af6-a0ad-f350d845da50)
![9154ec8c668d87442080b2fc13cc7d94](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/5e159cb2-c26c-4279-bacf-888cd9ca1f9d)

Torment on simc critting
![33e17ba1c9e6cac98b071e828c2d7917](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/cfa01b74-96ea-4827-b645-37c210966cd3)

This is from a warlock with 0 gear, 176sp, 18% mastery, 164 added dmg from formula (before mastery and armor mitigation ). Not a proper test but the dmg discrepancy is so big you can tell that something is wrong.

Melee dmg
![7470ccb8d700730c0d6e48adc7fc1132](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/d3505d61-9d58-4620-af09-d5e2c0c61893)

Felstorm dmg
![d8da2ac382f9a10703823582fd7c79f3](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/258736ee-f213-4d41-80f9-e652934b3fd6)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=3716
https://cata-twinhead.twinstar.cz/?spell=7814
https://cata-twinhead.twinstar.cz/?spell=89751

**Comment by Pornoodemon** [comment]
Not quite clear about the felguard

**Comment by bonfax4** [comment]
I'll test with mastery gear when I get time but for sure smthing is wrong. Felstorm uses pet dmg in it's formula + 164 with my gear and you can see a 53'ish% dmg increase when I only have 18% from mastery

**Comment by bonfax4** [comment]
> Not quite clear about the felguard The base damage has a scatter. At such low values 176 sp . It's not to test.



> Not quite clear about the felguard The base damage has a scatter. At such low values 176 sp . It's not to test.

My point the scatter is small with low gear and the discrepancy is big asf lol

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c40a1c88-118a-4282-b468-96db5b5f5715)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/5a6bf0cb-a178-4255-9b8f-b147b87fdc9b)
(((4462*0,5)*2)*0.33+111)=1583.46  + 3151(Weapon damage) = 4734.46
Result !!= 4734  -  4718  - 4776!! 
Matches to the smallest detail! and even if the spread would be within +- 300 damage, this is not a reason to break this pet Don't suffer nonsense
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/6d66d099-1ce4-4d36-b855-c6afef9b6fc0)

**Comment by bonfax4** [comment]
You are not accounting for the armor on the training dummy.

**Comment by bonfax4** [comment]
Maybe the issue is the dmg is ignoring armor I guess. It's physical dmg

**Comment by Pornoodemon** [comment]
> Возможно, проблема в том, что урон игнорирует броню. это физический урон

Armor in a regular dummy? LOL
I think it's time for one of us to go to bed

**Comment by bonfax4** [comment]
They do have armor tho. You just made me get out of bed to actually hit the dummy lol. Link me your felguard regular hit then pls

**Comment by Pornoodemon** [comment]
> У них есть доспехи, хотя. Ты только что заставил меня встать с кровати, чтобы ударить манекена, лол. Скиньте мне свой обычный хит стража Скверны, тогда, пожалуйста
Although the formula is correct, it seems to me that there is another problem here and not the one about which you made a report.
Mastery currently only increases weapon damage, but it should not increase weapon damage, it should increase the final value in the formula.

**Comment by bonfax4** [comment]
> Although the formula is correct, it seems to me that there is another problem here and not the one about which you made a report. Mastery currently only increases weapon damage, but it should not increase weapon damage, it should increase the final value in the formula.

Mastery directly affects pet dmg on the panel. You only didn't add mastery to the extra dmg

**Comment by bonfax4** [comment]
Can't find the actual value of armor. Gonna need a gm to help out

**Comment by Pornoodemon** [comment]
When I checked the death-strike BDK which deals physical damage it also matched the formula for damage not reduced by dummy armor. Maybe his armor only works for auto-attacks. I don't know

**Comment by bonfax4** [comment]
Also I'm fairly certain formula uses warlock spell power and not pet spell dmg btw.

**Comment by Pornoodemon** [comment]
> Также я совершенно уверен, что формула использует силу заклинаний чернокнижника, а не урон от заклинаний питомца, кстати. Идеально сочетается с всплывающей подсказкой таким образом.
That's just the point, I'm sure of it too But as far as I understand, pets here are arranged somehow in their own way.

**Comment by Pornoodemon** [comment]
Look at the calculation by the formula I took the spell power of a pet 4462

**Comment by bonfax4** [comment]
The current formula is using this and math kinda matches [melee * mastery * racial + (felstorm formula)]* mastery. Somewhat double dipping and the numbers kinda match.

**Comment by bonfax4** [comment]
Yup tested on lvl 3 dummies and I do much more dmg, so armor is actually working there.

**Comment by Pornoodemon** [comment]
> Да, проверено на манекенах 3 уровня, и я наношу гораздо больше урона, так что броня там действительно работает.
There is armor. But if checks it on the abilities of classes that deal physical damage with abilities and not with auto attacks, then this armor does not work

**Comment by bonfax4** [comment]
Well armor is working tho so that doesn't explain much. Let's just wait for a dev to reveal the formula and the armor value instead.

**Comment by jlldarocha** [comment]
Im not sure how much the dummies armor should reduce the physical damage, but the damage seems fine/correct.

On boss dummies My felstorm is doing 6182 maximum damage, with 5085 pet spellpower.

Using the felstorm coefficient with my stats: 

(3745+(((5085*0.5)*2)*0.33+111)) *1.4 (mastery) * 1.05 (orc racial) = 8,135.0535

 ~25% damage reduction from armour on dummies.

**Pet stats and damage**
![WoWScrnShot_082223_023754](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/e8eecdcd-6c56-41b8-ad59-fd7c859e0d2e)

**My stats to show %mastery**
![WoWScrnShot_082223_024606](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/2c067d8d-345a-4ffd-98e1-77b4509afb8f)

**Comment by jlldarocha** [comment]
Naked test on felstorm:

(1443+(((150*0.5)*2)*0.33+111)) *1.18 (mastery) * 1.05 (orc racial) = 1986 expected maximum damage

**1538 actual maximum damage** ~23% reduction from armor
![WoWScrnShot_082223_030309](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/dac92bd7-d991-451a-b24f-8394a6d3a15b)

(lack of) gear showcase
![WoWScrnShot_082223_030315](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/3236123f-8522-43ae-baf7-efb081477f6d)

**Comment by bonfax4** [comment]
Test it on the lvl 3 dummies on the starting areas and you'll have more accurate numbers. They barely have armor, so the auto attack dmg matches properly with the pet window.

**Comment by bonfax4** [comment]
lvl 3 dummy, 8 mastery (18.4% increase) , 176 sp

(($SP * .50) * 2) * 0.33 + 111) = 169.08 (176 sp)
![9b6a7c1b99a1222a2567145e49dfab3d](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/f9052128-2f63-4873-925b-92a74a8cfee8)

added dmg after mastery / racial = 169.08x1.184x1.05 = 210.2

melee range 1232 - 1423 (already affected by mastery / racial )

expected felstorm dmg with no double dips = 1442 - 1633

actual dmg = 1838 - 2053
![ded193dfc85d330d88704257327ea974](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/9911bad0-cf13-43f0-8be8-9b2afa997783)

Still not sure which modifiers on pets are multiplicative or additive but simc shows orc racial being additive with glyphs for pet spells. Possible mastery is additive with racial.

**Comment by bonfax4** [comment]
Actual formula for Felstorm / Legion strike should be smthing like this : if we follow simc additive/multiplicative rules : 

- Felstorm : [melee + (($SP * .50) * 2) * 0.33 + 111)] * mastery * racial
- Legion strike :  [melee + (($SP * .50) * 2) * 0.264 + 111)] * mastery * (glyph + racial) * dark arts talent 

Melee in both these scenarios is pet dmg before modifiers, no double dips.

**Comment by jlldarocha** [comment]
According to the comments on felguard issue log from apollo, both legion strike and felstorm DO double dip from mastery and racial, multiplying both on the weapon damage and on the end.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/5b177e36-fe86-46e4-ad1a-4f644b6fcc64)

Language is kinda harsh because its google translate from czech

**Comment by bonfax4** [comment]
i've seen that but he corrected himself later on if you follow the thread. the lkatest formula he arrived at is close to mine

**Comment by jlldarocha** [comment]
thats because theres a post from a dev talking about the possible solutions, before this you linked: they had to choose between double dip mastery or doubling the base weapon damage of the felguard (they went with that option)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/7df40704-00b6-4bc1-8e3f-c1cc217fee39)

**Comment by Pornoodemon** [comment]
To be honest, the wowhead formula itself looks very strange.
I think that the multipliers in the formula are referring to something and not multiplying spell power by itself twice, otherwise why would it even need so much math.
 (($SP * .50) * 2) * 0,33 + 111)]
This is not logical even from the point of view of code optimization
It would be much easier to just take sp * 0.3+ weapon damage or something like that.

**Comment by bonfax4** [comment]
That is not a dev... all devs are color coded there....

**Comment by bonfax4** [comment]
> To be honest, the wowhead formula itself looks very strange. I think that the multipliers in the formula are referring to something and not multiplying spell power by itself twice, otherwise why would it even need so much math. (($SP * .50) * 2) * 0,33 + 111)] This is not logical even from the point of view of code optimization It would be much easier to just take sp * 0.3+ weapon damage or something like that.

matches the tooltip exactly tho

**Comment by Pornoodemon** [comment]
At 10 k sp, the difference in increase will be in the range of 600-1200 damage. If it should work like this at all. In general, I would not touch this pet at all. works relatively well.

**Comment by bonfax4** [comment]
> At 10 k sp, the difference in increase will be in the range of 600-1200 damage. If it should work like this at all. In general, I would not touch this pet at all. works relatively well. In pvp when you have armor and resilience this will add 300-600 damage at bes Given the fact that this is physical damage, then everyone who feels the difference in the correction is wild boars in a durotar. Is it worth it to do it

Mastery would be the prob not sp. SP portion of this wouldnt change at all actually since it would not double dip

**Comment by Pornoodemon** [comment]
I just really don't understand if it makes sense to turn the world upside down to find out if your pet in full season 11 will have an extra 500-700 physical damage.
This is still leveled out due to resilience and armor up to 200 - 500 extra damage at the most

**Comment by Pornoodemon** [comment]
For example, I have 100% proof that Gargoyle damage is now increased by about 25-30%.
But I do not want to open this topic again and argue with the developer. She is now working + - normally and to hell with her.

**Comment by bonfax4** [comment]
Well it's posted and it's not blizzlike. If they decide not to touch it it's up to them. You should report the gargoyle as well dk's are broken as is.

**Comment by bonfax4** [comment]
After further testing this I realized simcraft is actually using a different mod for spellpower scaling on the ability (0.231). To match close to simc using the same profile stats values, it has to double dip somewhere but I can't figure out exactly how it's being calculated. 

Now the actual formula the server seems to be using for felstorm  is ( melee <- pet panel value with mast/racial + ( xtra dmg formula * mastery * racial )) * mastery *racial ) and the values seem to kinda match with what I'm seeing.

**Comment by Pornoodemon** [comment]
Twinstar can just as be wrong. It's not blizz.
Perhaps it works correctly for us and worse for Twinstar, or vice versa.
I wouldn't bother as the deviation is not significant.

**Comment by bonfax4** [comment]
I just need to know the exact  % reduction on boss level units and the actual player sp to pet AP formula and I can compare to that retail video and see if it's close or not. But I tried having similar levels of sp to the retail video on twinstar and the dmg is off by a good difference (600+ more and it will only get worse ofc when you factor mastery and sp procs ) so you know their formula is also wrong somewhere anyway.

**Comment by UltraNix** [comment]
Spell Power < 500 are to small to test (pets get 50% of it).

Torment formula:
` ${$M1+(0.512*($SP*0.5))} Shadowstrike damage.` `M1` is 729,45 at 85 lvl.
So we have `729,45+(0.512*($SP*0.5))`

![WoWScrnShot_083023_160458](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ce7a4775-1ef5-49b3-b1a7-47b7e4cda64d)

Tested in dumy with 41 armor and 0 shadow resi.
Pet have already 2690 SP from me (already double dip by Demonic Pact).
So we have now:
0,512 * 2690 = ~1377
1377 + ~730 (base value of Torment) = 2107
2100 * 1,27 (My mastery) = 2667 * 1,27 (it's shadow + physical, so it takes 2x mastery) = 3387

On boss dummy:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/876455c6-dec8-47b5-9bc0-2ac28e86c8b5)
The thing is that simcraft defines Torment as shadow, not shadowstrike. It should take both schools when calculates dmg.

**Comment by bonfax4** [comment]
Hmm ok then iss frostfire bolt / starsurge getting 200% mod if you get any buff to all damage then ?

**Comment by UltraNix** [comment]
These spells take two "spell/magic" resistances. Amor is a little bit tricky.

**Comment by bonfax4** [comment]
Yh I knew that part but buffs to all dmg double dip seems weird.. Found a random discussion saying it it's additive when it's increased to single schools and no double dip on all dmg  but looking around still. Wowwiki doesn't explain that part. Either way torment is not critting.

Anyway can you also tell me what's the warlock  SP to pet AP conversion formula ? It's def not 0.57% like the game suggests, it's closer to 100%.

**Comment by UltraNix** [comment]
It's something around 106% at 85 lvl.

**Comment by UltraNix** [comment]
@bonfax4 Poke me on Discord.

**Comment by UltraNix** [comment]
About double dipping on Felstorm:
Yes - Felguard takes extra bonus from Demonic Pact and an extra modifier at 85 lvl, according to simcraft.
```
virtual double composite_attack_power() const
  {
    double ap = pet_t::composite_attack_power();
    ap += owner -> composite_spell_power( SCHOOL_MAX ) * ( level / 80.0 ) * owner -> composite_spell_power_multiplier();
    return ap;
  }
  ```
Also, it's not normalized weapon damage, thus all modifiers are already calculated (included mastery).

**Comment by UltraNix** [comment]
Fixed.
