### ISSUE TITLE
Ragnaros - Elementals Targetting Magma Traps

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4269]
**Description:**
On Ragnaros regardless of the difficulty, the elementals have a significantly high chance to target any Magma Traps that are currently active within its vicinity. At times this causes them to trigger the Magma Trap without damaging the raid.

**How to reproduce:**
When a Magma Trap is active, have a Shaman place their elemental totems down and see their path towards the Magma Trap. 

**How it should work:**
The elementals should not be able to target the Magma Trap and detonate the Magma Traps.

**Comment by UltraNix** [comment]
Fixed.
