### ISSUE TITLE
[Random-Battlegrounds] - Balancer ( 5 healers, 1 tank, 4dps on one team 10v10 )

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4270]
I dont know if the is any balancer but would be nice to have one ...

I did Warrsong Gulch 10v10 while having 5 Healers, 1 Tank, 4 DPS on one team. The other team had only 1 healer. 
Balance could balance the healers.

Heres imgur pictures

https://imgur.com/a/oPf4j6w

**Comment by Sketish** [comment]
It's not a bug
