### ISSUE TITLE
DRs in pvp

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4271]
https://www.youtube.com/watch?v=UE9IXBpfAXY&feature=youtu.be
https://gyazo.com/a40ac36d81a2cc7a3597dabbe98a3c75
https://gyazo.com/cb78808ea3d14bc8ce6c0c755b4a3757
https://gyazo.com/03c0536365205d9e888730039dd211a2
(I get full cloned 14.68 seconds after the last one)

https://www.youtube.com/watch?v=MYkbnXItfX0
https://gyazo.com/02e6599d8d6d00cefd869989e823bb49
https://gyazo.com/ac88b1677affd39732b318b7e53312ef
https://gyazo.com/daa1ba7be6c8ffb056e0ac0d73bf6df6
(I full garrote the druid 13.73 seconds after the last one)

**Description:**
Diminishing Returns(DRs) are bugged, you can sometimes full CC someone 13-14 seconds after they were last CCed. I know you are using dynamic 15-20 sec drs here but really it's not 15sec it is a bit lower. Why? I'm not sure, maybe you are using a ticker that only checks DRs every 2 seconds to save memory or something? Maybe the DR timer is starting too early in the CC? There could also be a bit of server lag combined with these issues, in any case maybe change the dynamic to 17-20sec to compensate because you should never be able to CC someone full every 13 seconds, that's rediculous.
Or who knows maybe there is a hidden DR reset trigger somewhere in the core?

**How to reproduce:**
Don't know sorry because of course the timer is dynamic and that throws in an element of randomness I couldn't really test what the cause is, all I could do is to show that there is a bug.

**How it should work:**
You definitely shouldn't be getting full CCed any sooner than 15.000 seconds after the last one ends

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
