### ISSUE TITLE
quel dalar restored quest

### ISSUE THREAD

**Issue by tete122** [gamefreedomgit/Maelstrom#4273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
once i drop the sword to the sunwell nothing happend and i cant continue.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
