### ISSUE TITLE
Ignite

### ISSUE THREAD

**Issue by voidwho** [gamefreedomgit/Maelstrom#4274]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ignite rollling is sort off incorrect.
Scenario:

1. **1st scorch hits**
8/22 11:39:31.279  SPELL_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,2948,"Scorch",0x4,20467,20466,4,0,0,0,1,nil,nil
2. **ignite applied**
8/22 11:39:31.289  SPELL_AURA_APPLIED,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,DEBUFF
3. **ignite tick - ignite is sub 2 sec now**
8/22 11:39:33.259  SPELL_PERIODIC_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,5333,5332,4,0,0,0,nil,nil,nil
4. **2nd scorch**
8/22 11:39:33.350  SPELL_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,2948,"Scorch",0x4,20523,20522,4,0,0,0,1,nil,nil
5. **trigger refresh, now ignite splits on 3 parts**
8/22 11:39:33.350  SPELL_AURA_REFRESH,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,DEBUFF
6. **3rd scorch - ignite above 4 seconds, so no refresh event**
8/22 11:39:34.363  SPELL_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,2948,"Scorch",0x4,20449,20448,4,0,0,0,1,nil,nil
7. **tick - now ignite is sub 4 sec**
8/22 11:39:35.277  SPELL_PERIODIC_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,8895,8894,4,0,0,0,nil,nil,nil
8. ** 4th scorch - ignite sub 4, so we refresh **
8/22 11:39:35.371  SPELL_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,2948,"Scorch",0x4,20644,20643,4,0,0,0,1,nil,nil
9. **refresh ignite, now its above 4 again**
8/22 11:39:35.371  SPELL_AURA_REFRESH,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,DEBUFF
10. **ignite is above 4, so this one shouldnt refresh duration, only add to value**
8/22 11:39:37.174  SPELL_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,92315,"Pyroblast!",0x4,60490,60489,4,0,0,0,1,nil,nil
11. **tick happens after pyros added value**
8/22 11:39:37.292  SPELL_PERIODIC_DAMAGE,0x0000000000003285,"xyz",0x511,0x0,0xF130B6370000807C,"Training Dummy",0x10a28,0x0,12654,"Ignite",0x4,20026,20025,4,0,0,0,nil,nil,nil

Math is correct but there is "missing" feature. 

If Ignite ticks AFTER the crit and BEFORE the application of an Ignite refresh, you get a "rolled" Ignite. This is because the new Ignite pool damage is calculated before it is drained by the next tick.

There is SUPPOSED to be delay on **SPELL_AURA_REFRESH event check for ignite**(roughly 0.5 seconds). 
So when pyro lands, we should calculate ignite, delay the check for spell aura refresh - do the tick, refresh ignite. 

Which means - this tick that happened at 11. shouldnt do 20k, it should do previous value of ignite. But our next ignite should be stronger, and ignite should refresh.

At the moment - there is no ignite rolling mechanic ingame, which is why alys for example is unplayable(you cant roll it).

In theory - that 1 tick that happens in this scenario, even tho it did happen, it doesnt eat out value of next ignite.
For example - current ignite 40k.(split on 3, 13.3k)
We crit 10k(+4k for ignite) at ~4.01 seconds(roughyl juts about the ignite is about to tick)
In current scenario what happens: 
 - +4k gets added to ignite, total ignite is 44k, ignite duration doesnt get updated(since we are above 4 seconds), tick is 15k~

What should happen:
 - Next ignite gets calculated, 44k
 - Ignite ticks current value - aprox 13.3k
 - Ignite gets refreshed to 6~ seconds - with new calculated value 44k
**How to reproduce:**
Use log up to reproduce.

**How it should work:**
Explained above.
Basicly - there should be delay on ignite refresh event check after spell crit, and the calculation of NEXT ignite should take place at the time of crit.

**Database links:**

**Comment by voidwho** [comment]
http://web.archive.org/web/20120404210003/http://elitistjerks.com/f75/t129638-4_3_3_fire_mage_compendium/#Crit:_Ignite_Munching_and_Ignite_Stacking 
Refer to EJ guide regarding ignite rolling.

**Comment by bonfax4** [comment]
Think this was discussed already, they won't add that mechanic. It's useful for sub rogues and feral druids with t12 2pc. T12 was  actually bis in DS  for rogues because of it but won't be here,

**Comment by voidwho** [comment]
Ignite rolling is core part of gameplay - not implementing it doesn't make sense. 
Any reason why they wont add the mechanic?

**Comment by bonfax4** [comment]
Can't quite remember but it may be tough to implement. Either way I actually requested to make ignite not munch at all if we're gonna have a weird half version of it. They should just make ignite not munch at all like they did in classic already.

**Comment by mageceo** [comment]
If this issue is not addressed, it could result in high roll pulls not functioning properly. Is there any chance you could consider increasing the travel speed of Pyroblast slightly faster than Fireball? Doing so would help mitigate the issues with spell overlapping and could compensate for the potential DPS loss if the above fix is not feasible.

**Comment by Warlorc** [comment]
gg whitemane  perfect fix for fire mage  the best extation  for fire  mage  become trash here  no one  he can stack ignite again  wth crit damage  i play fire mage from 2008 ad i start play  cata from 2014 fire mage was opp now fire mage will bad spec ever in thi server and war  arm  wth 17% crit  stat one of his spell  do 48% overall damage  and whne fire mage wth 30% crit  and be wth 36% crit  raid buff fireball doing 28% crit damage overall and pyro wth tier2 bonus 5%  crit  32% overall damage rely ggg

**Comment by UltraNix** [comment]
Already discussed in that topic: #3487
We have no plans (right now) to implement that 500ms delay window.
