### ISSUE TITLE
game crash when u kill Argaloth

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4276]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the whole raids game crashed when we killed Argaloth

**How to reproduce:**
![gamecrash](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/a2566624-ea7a-45aa-a7dc-8a5f61329353)

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Look's like addon/pc issue , boss is not crashing client on live or ptr servers
