### ISSUE TITLE
dots breaking stealth with shield

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4281]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://www.youtube.com/watch?v=z5xO65P1EP0&feature=youtu.be

**Description:**
It seems like dots break stealth with a shield, tested with Serpent Sting, Power Word: Shield and a rogue

**How to reproduce:**
eat a dot then get a shield and try to stealth

**How it should work:**
The shield should hold the stealth from breaking to dots untill the shield breaks, then the dots can break the stealth when there is no shield.

**Database links:**

**Comment by Pornoodemon** [comment]
Any damage, including absorbed and any control and AoE control that does no damage at all, as well as almost all actions except movement and something else there.
should bring the rogue out of mere invisibility.

**Comment by bonfax4** [comment]
hmm dots should not break but almost everything else should. Aoe spells  ( direct and channeled ) / direct hits (spell cast or mellee ) / application of dots / roots like frost nova , earth's grasp,etc.  Grounded aoe's (consecration , death and decay , flamestrike, etc) that are already laying there should also not bring the rogue out unless they are hit directly on cast by them.

If you need proof that dots do not break here's [a video ](https://youtu.be/21PSu05RxG4?t=120). After vanish fades he stays in stealth with like 3 dots on him. 

https://github.com/gamefreedomgit/Maelstrom/issues/3900

**Comment by SimonBpvp** [comment]
> Any damage, including absorbed and any control and AoE control that does no damage at all, as well as almost all actions except movement and something else there.
> should bring the rogue out of mere invisibility.
> The only exception is Vanish, which grants the rogue 3 seconds of enhanced invisibility.

Wrong wrong wrong

**Comment by UltraNix** [comment]
#4238
