### ISSUE TITLE
Baleroc - shards spawning

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4282]
**Description:**
During Baleroc enounter shards are supposed to spawn randomly on any range or melee except tank. Currently its'a always spawning on melee players

**How to reproduce:**
Pull Baleroc and see it's always spawning on melee

**Comment by Polynomix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/72f6af3b-09c1-496a-b41b-823b3b9beb77)

spawning in range

**Comment by UltraNix** [comment]
Fixed.

**Comment by Sketish** [comment]
After watching retail vidoes @amanita199  is right,
on 10 man its always spawning on melee near boss
on 25man it's always 1 random melee and 1 random range

**Comment by UltraNix** [comment]
Fixed.
