### ISSUE TITLE
vanish vs spells

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4284]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz) 
https://www.youtube.com/watch?v=MP1Wxj9jT1k&feature=youtu.be

**Description:**

if you vanish at the right time you can immune spells. Here I immune aimed+chimera shot. This was wrathlike but not catalike. 
I think only shadowmeld could immune stuff like that

**How to reproduce:**
just time it right 

**How it should work:**
the only stuff you can immune with vanish is slows and roots

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=1856

**Comment by Pornoodemon** [comment]
This is a bug and they get immunity not only to spells, to any  control effect, and even to physical stuns.
And the main problem is that if he catches any control effect, then after 3 seconds it does not bring him out of stealth

**Comment by Pornoodemon** [comment]
https://cata-twinhead.twinstar.cz/?fixreport=show&id=9958

**Comment by Pornoodemon** [comment]
After 3 seconds of disappearance, if the rogue has some kind of control effect, this should take him out of stealth

**Comment by SimonBpvp** [comment]
> 

Well you’re hijacking this report slightly there. It was about immuning spells like you see in the clip, maybe make a bug report specifically about the cc part if u dont mind.

**Comment by SimonBpvp** [comment]
> 

Cool nice one, I’m going to say the cc part is a slightly different issue and needs its own report. This is specifically about immuning the spells not CCs not breaking stealth. Thanks

**Comment by Sketish** [comment]
Provide any retail sources instead of Apollo ones please

**Comment by SimonBpvp** [comment]
> Provide any retail sources instead of Apollo ones please

But yes I will have a look for a retail source on YouTube

**Comment by SimonBpvp** [comment]
> After 3 seconds of disappearance, if the rogue has some kind of control effect, this should take him out of stealth

nope apparently not true check this out from retail.

https://youtu.be/YrAjowatJS8?t=651

**Comment by bonfax4** [comment]
Doesn't require a lot to find sources. A lot of rogues crying about the vanish change and not being able to dodge in flight or being immnune to cc / damage from cata onwards.

https://www.bluetracker.gg/wow/topic/us-en/26859118887-vanish-immuning-is-no-more-intended/

https://www.mmo-champion.com/threads/939075-Vanish?
https://www.mmo-champion.com/threads/776196-New-vanish?
https://www.mmo-champion.com/threads/786813-Want-to-quot-dodge-quot-spells-with-vanish-

**Comment by UltraNix** [comment]
Fixed.
