### ISSUE TITLE
Paladin JP Vendor Leggings are only 1650 JP instead of 2200

### ISSUE THREAD

**Issue by Dominnuss** [gamefreedomgit/Maelstrom#4286]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Paladin 359 ilvl legs cost only 1650 Justice Points. Every other class/spec has legs that cost 2200 Justice Points.

**How to reproduce:**
-

**How it should work:**
Prices should be equal across classes/specs

**Database links:**
![2](https://github.com/gamefreedomgit/Maelstrom/assets/142952450/3fdf918b-57e8-44d5-b6a5-f25c1afad6b4)
![1](https://github.com/gamefreedomgit/Maelstrom/assets/142952450/16cc3c5d-f71c-49de-9c73-b67b9613ca21)

**Comment by UltraNix** [comment]
Fixed.
