### ISSUE TITLE
lock pets HP

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
whitemane: https://gyazo.com/d1c7dead1e3f30d537fbda918c5146c8
retail: https://gyazo.com/452ea9273484bb0764fbd1e1e9ae922a
**Description:**
lock pets have too low HP it should be like 75% of your max hp as you can see in the retail screenshot and right now its about 60% as you can see in the whitemane screenshot

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Pets take hp from owner's stamina, not max health.

**Comment by Pornoodemon** [comment]
> Pets take hp from owner's stamina, not max health.

Each pet should have a different value from 70 to 75% of the warlock's HP.
But now their HP is really low.
Somewhere I created a topic with formulas for hp pets. But it seems to have been deleted because I can't find it.

**Comment by SimonBpvp** [comment]
> Pets take hp from owner's stamina, not max health.

Cool, I don't think that affect my bug report tho, look here I have same max HP as snutz
https://gyazo.com/43608771e0cbee2361f2acbac6410b46

**Comment by SimonBpvp** [comment]
bump, pls fix, lock is semi-unplayable right now cause everyone tunnels your pet. It was fine 3 weeks ago and then someone unfixed it!

**Comment by Afgann** [comment]
fixed
