### ISSUE TITLE
Death from Above - Molten Front achievement

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4289]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The elites that should give credit for the achievement are not on their spot, except Blazefury.

**How to reproduce:**

Do the related daily quest in Molten Front.

**How it should work:**

By using the second spell on the Elementals you have on your extra action bar.
(3 of them each day)

**Database links:**
https://www.wowhead.com/achievement=5874/death-from-above
https://cata-twinhead.twinstar.cz/?achievement=5874

**Comment by UltraNix** [comment]
Fixed.
