### ISSUE TITLE
Arms Warrior - Opportunity Strike miss ‘small icd’ window

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4290]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Opportunity Strike. (Arms: Strikes of Opportunity, SoO)

**How to reproduce:**
Bladestorm on alot monsters at once and view with addon.

**How it should work:**
Opportunity Strike have ‘small icd’ like 0.1-0.2 sec
Bladestorm → 7 Swings → Maximum Opportunity Strikes = 7 (1 per swing)

**Database links:**
Strikes of Opportunity has been revealed by a blue post to have a 0.1s cooldown, to prevent a chainreaction of endless procs like you described. What you’d get would be a proc after each white and yellow attack. ([source](https://web.archive.org/web/20121218220712/https://www.wowhead.com/spell=76838#comments:id=1333051:reply=559258))

**Comment by UltraNix** [comment]
Fixed.
