### ISSUE TITLE
Mirror images from t12 2 piece mage set are missing spells even with the mage hit capped

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#4293]
**Description:**
Mirror images from the tier set arent inheriting the spell hit from mage, and are missing ~17% of their casts
![261877449-fa9bfccd-5c3a-49a9-a100-fd3ab2fe1d43](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/87848f63-16e0-4ca6-8dd2-373cfb2bdf3d)

**How to reproduce:**
Equip 2 piece and go damage a boss dummy to proc the mirror image, after a while look at his hit/miss ratio

**How it should work:**
They should have the same spell hit as the mage.

**Comment by xmrshoot** [comment]
same problem with normal mirror image spell

**Comment by UltraNix** [comment]
@xmrshoot Please - open a new report about it. This one is about t12 and is going to be closed.

**Comment by UltraNix** [comment]
Fixed.
