### ISSUE TITLE
Killing streak issue and kill command issue in magma front

### ISSUE THREAD

**Issue by Ivet2023** [gamefreedomgit/Maelstrom#4294]
https://cata-twinhead.twinstar.cz/?spell=82748

The hunter beast talent killing streak isnt working 
Description : 
When you score two Kill Command critical hits in a row, your third will deal 20% more damage and have its cost reduced by 10 Focus.but when you score two kill command critical nothing happend. 

Another bug is kill command dont do damage in some npc in magma front 
![Uploading 26f3819c-67db-445b-a7ee-6420315bc531.jpg…]()

**Database links:**https://cata-twinhead.twinstar.cz/?spell=94006

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/4309
