### ISSUE TITLE
Tanaria - QUest - Just trying to kill some bugs

### ISSUE THREAD

**Issue by Shaiogded** [gamefreedomgit/Maelstrom#4295]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After finishing the quest, and detonating the mind controlled bug, you do not get teleported back to the camp, you turn into the player and remain in the hive.

After the bug is detonated, your should be returned back to the camp, to the Bootlegger Outpost

![BE](https://github.com/gamefreedomgit/Maelstrom/assets/141687981/86207ef1-31d0-4236-80b7-bcee04c65db0)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 23.04.2024
