### ISSUE TITLE
Restoration Shaman - Healing Stream

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4296]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://ibb.co/XstJ21j
I was in dungeon doing heroic.
I checked the restoration shaman who been healing our group.
-the data is taken with Recount and Skada.
-the data is for **entire** run till we finished.
I don't have Shaman myself to re-check if there a bug.

I think you have a problem with Healing Stream for some reason(s) it was 1st healing source
and according to my knowledge the healing stream cannot be possible to be the 1st healing total.

**How to reproduce:**
No idea.
If I correct: Healing totem should heal once per 1.5 sec,
so check if healing totem is healing once per 1.5 seconds...
I don't have Shaman myself to re-check if there a bug

**How it should work:**
Healing Totem should heal one per 1.5 seconds.

**Database links:**

**Comment by Sketish** [comment]
So what is the bug ?

**Comment by whothatdog** [comment]
> So what is the bug ?

I wrote it and provided a screenshot link showing that - Healing Stream Totem is doing 1.25m healing and it position at 1st as healing source (total healing) which is impossible.
- the Healing totem stream should tick once per 1.5 seconds.
- it seems to tick faster or for some reason(s) to heal way too much than the totem should provide.\
it even beat Riptide.
- as I mentioned, I do not have Restoration Shaman to check it further.

**Comment by Sketish** [comment]
Currently totem is ticking every 1,5sec so I dont see issue there. Healing distribution depends from gear,dungeons or party comp. From ss I can see he was passively healing with totem+riptide  so group dmg was pretty low.

**Comment by whothatdog** [comment]
> Currently totem is ticking every 1,5sec so I dont see issue there. Healing distribution depends from gear,dungeons or party comp. From ss I can see he was passively healing with totem+riptide so group dmg was pretty low.

It was heroic dungeon 5 person run Tol'vir.
the Healing totem was first heal source every boss...
at end of the run it still was the first heal source with 1.25m heal done.

If the totem is tick every 1.5 sec it's good, I can't tell what the causing this issue.
although I believe, we both can agree that Healing totem cannot be the 1st heal source ;-)
