### ISSUE TITLE
KARAZHAN - Nightbane can't be summoned

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4297]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After completing the questline, clicking on the urn, nothing happens.

**How to reproduce:**

Do the related questline, press the urn on the Master's Terrace.

**How it should work:**

Simply go to Karazhan, to the Master's Terrace and on the Southern side you will find the urn located along the parapet. Click the Urn to summon Nightbane. After completing the quest you will be able to summon Nightbane by clicking the urn.

**Database links:**

**Comment by PanJanuszek** [comment]
should be fixed by Afgann
