### ISSUE TITLE
Scale of life doesnt work on bdk's death strike

### ISSUE THREAD

**Issue by Kismet-Fate** [gamefreedomgit/Maelstrom#4298]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Scale of life doesn't work with the healing from blood death knight's death strikes, it doesn't store the healing. 

**How to reproduce:**
Equip the trinket, use death strike

**How it should work:**
Scale of life should store the healing from death strike 

**Database links:**
https://www.wowhead.com/item=68915/scales-of-life#comments

**Comment by Afgann** [comment]
fixed
