### ISSUE TITLE
Alysrazor - missing blazing claw on p4

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4299]
**Description:**
After hitbox update to Alysrazor she stopped casting Blazing Claw on her current target during p4
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/07797aff-5279-4cd7-ab7c-42e4ae65cb1c)

**How to reproduce:**
Pull Alysrazor to p4 and see her doing just aoe

**Comment by UltraNix** [comment]
Fixed.
