### ISSUE TITLE
rogue t12 2pc

### ISSUE THREAD

**Issue by amanita199** [gamefreedomgit/Maelstrom#4301]
**Description:**
Rogue 2pc t12 is doing too little dmg

**How to reproduce:**
go to a dummy or boss, got this from a boss 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129459223/586a6ce5-a374-4f8e-bea9-3c8b9b5f1421)

**How it should work:**
Found some posts about it
https://www.mmo-champion.com/threads/961013-Rogue-tier-12-set-bonus-1?highlight=rogue+tier+12

https://www.wowhead.com/spell=99173/burning-wounds#comments

https://www.wowhead.com/spell=99174/item-rogue-t12-2p-bonus#comments

**Comment by UltraNix** [comment]
Fixed.
