### ISSUE TITLE
Queue arenas in the middle of world pvp

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#4302]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
People in the middle of pvp can just queue arenas and escape world pvp infinite amount of times

**How to reproduce:**
Queue for arena while you are pvping in open world

**How it should work:**
You should technically not be able to teleport because you are in combat, at least it works like that with RDF

**Database links:**
https://imgur.com/oG0zYiN

**Comment by Carapilsx** [comment]
You are wrong.

RDF may be scripted differently but you should be able to join arenas while you are **in combat** and also while you are **dead**. It was the case in classic tbc and classic wrath. 

It can be "sad" for wpvp, but at the end of the day, you want to get inside the arena. If you don't, you lose a game and the other team will wait for nothing. 

Close this

**Comment by Afgann** [comment]
fixed
