### ISSUE TITLE
[Priest]Dispel Magic doesn't activate combat

### ISSUE THREAD

**Issue by Artemhx** [gamefreedomgit/Maelstrom#4305]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Priest Dispel Magic doesn't activate combat

**How to reproduce:**
Use dispel magic on enemy beeing uncombat

**How it should work:**
It should activate combat

**Database links:**
https://www.youtube.com/watch?v=Wikh8Dr-XZc&ab_channel=%D0%A1%D0%BB%D0%B0%D0%B2%D0%B0%D0%97%D0%B0%D1%85%D0%B0%D1%80%D0%BE%D0%B2

**Comment by Renehadox** [comment]
You got retail proof of this?

The video you recorded its from this server

**Comment by Artemhx** [comment]
> You got retail proof of this?
> 
> The video you recorded its from this server

Its obviously when you dispel/purge enemy target there should be activate combat automatically

https://youtu.be/H8ZIH_-CBfU?si=zfqRNfCBidltF9Ss&t=1836
3:37 - priest used dispel magic on shaman and immediately entered combat

**Comment by Qidpuncher-outland** [comment]
> You got retail proof of this?
> 
> The video you recorded its from this server

You need a proof that dispelling should keep someone in fight ? ^^

**Comment by UltraNix** [comment]
Fixed.
