### ISSUE TITLE
Limitless Transmogrification NPC

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4308]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Once I am deleting a saved set at the limitless transmogrification npc there will be blank spots.
(I am sorry but it bothers me, since I am working on something everytime)
**How to reproduce:**

Save a set at the "Manage sets" tab.

**How it should work:**

I guess it should disappear.

**Database links:**

![LIMITLESS TRANSMOG NPC](https://github.com/gamefreedomgit/Maelstrom/assets/133872309/be72eed8-96ce-4e19-828a-faa5e354c3d2)

**Comment by XYNKA** [comment]
Author: afgann
Message: Core/Custom: Fix saved sets appearing as blank spots after they are removed in Limitless Transmogification. https://github.com/gamefreedomgit/Maelstrom/issues/4308 

The issue is still on.

**Comment by Afgann** [comment]
@XYNKA fixes are applied usually on wednesday.
