### ISSUE TITLE
Lord Rhyolith - Magma Flow Volcano Size

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4310]
**Description:**
Upon rewatching encounters of Lord Rhyolith on retail, it has come to my attention that the Magma Flow Volcanoes on Whitemane do not fully erect out of the ground before they start to spawn lava.

Currently, the Magma Flow Volcanoes are only half-erect from the ground and are smaller in both the size and height of the player.

In this first screenshot from retail: 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/db0e27c3-3cf3-4165-aa35-74240c2ec6b0)
You can see that the Magma Flow Volcano when fully erected from the ground, completely towers over the player.

In comparison to the second screenshot from Whitemane: 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/e1aa5ec8-6644-4b46-b3a8-392cf8ba0e53)
You can see that the Magma Flow Volcano isn't fully erected from the ground and proceeds to spill lava.

**How to reproduce:**
Start the encounter, wait for a Magma Flow Volcano to spawn and compare the size of the volcano to the player.

**How it should work:**
The Magma Flow Volcanoes should be fully erected from the ground before spilling lava and should be larger in size and height.

**Comment by UltraNix** [comment]
Fixed.
