### ISSUE TITLE
Item durability shouldn't be lost upon dying from an enemy players

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4311]
Description:

I have noticed this bug that is happening here from the release of this server.

Players shouldn't lose item durability upon dying from an enemy player.

Its also written in game in the loading screen.

How it should work:

Database links:

[WoWScrnShot_070423_184757
](https://user-images.githubusercontent.com/67479994/250962278-17b314b4-9217-4bb7-aaeb-8a73c67fb516.jpg)

**Comment by Renehadox** [comment]
![WoWScrnShot_070423_184757](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/1bdd5599-06c3-485a-b5f5-5f16e148ef79)

**Comment by UltraNix** [comment]
#3949
