### ISSUE TITLE
Sweeping strikes

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4313]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sweeping strikes is currently critting on the offtargets which should never happen since the crit from main target to off already happend, it also isnt double dipping into resil / armor from maintarget to offtargets (when it hits offtarget it should dip into resil + armor once again)

**How to reproduce:**
Have a warrior pop sweeping strikes recklessness and then bladestorm ontop of 2 or idealy 3 enemy players.

**How it should work:**
Sweeping strikes should not be able to crit on the offtargets since if it crits from main target the damage amplifier is already calculated and dealt to the offtarget,  and it should double dip into resil + armor from main target and offtargets,

**Database links:**

**Comment by Qidpuncher-outland** [comment]
Out of curiousity, is there a link that shows it should double dip ?
The crit part seems weird aswell given it just replicates the crits instead of critting itself.

**Comment by bonfax4** [comment]
Armor double dip can't be true because you see 100% dmg transfer on boss fights in retail. If that was true sweeping would be doing on average @ 70% less dmg. Resilience not sure.

**Comment by bonfax4** [comment]
@Afgann Yh Sweeping strikes is now double dipping armor which is wrong, as evidenced above it should not be affected by armor. You really should force ppl to provide proof before making these huge claims. Blade flurry/Sweeping should double dip on Aura dmg increase or decreases (physical or all damage). As in atacking a drake into halfus should provide the cleaved dmg the halfus dmg increase buff or [atacking ryolith legs should decrease your damage done again on the cleaved hit.](https://youtu.be/G16GzsEvY_M?t=37) (also [here](https://www.mmo-champion.com/threads/934222-Combat-vs-Rhyolith/page2?highlight=blade+flurry+ryolith) ppl mentioning double dipping on blade flurry on the dmg decrease aura on ryo) 

https://cata-twinhead.twinstar.cz/?fixreport=show&id=9930

**Comment by Juiceyyhi** [comment]
https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

I timestamped the Sweeping Strikes, apparently it does crit so this wasn't bugged at all.

**Comment by bonfax4** [comment]
> https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115
> 
> I timestamped the Sweeping Strikes, apparently it does crit so this wasn't bugged at all.

 No ? He is s right on that part, it just copies your crit, it can't crit by itself. There was never a cleaved crit on that video.

**Comment by Juiceyyhi** [comment]
The sweeping strike effect should copy the main targets damage to the offtarget, even if it's critting. 
Please check the timestamp. 

https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

Right now on Whitemane the damage value is not calculated correctly to the offtarget. 
I think they broke Sweeping Strikes now.

**Comment by Qidpuncher-outland** [comment]
Also @Afgann would it be possible to revert the spell as a whole to how it was before please ? The proof should be provided by the person creating the report not the other way around.

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/fc7c1cb3-3637-4255-992d-53a5d198871b)

Please revert, my sweeping is not copying critical strikes to the offtarget, and it's doing 300 damage sometimes?? That's completely bugged damage.

**Comment by Juiceyyhi** [comment]
https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

On this video, it clearly shows that critical strikes should be copied to offtarget, please watch the video and revert this change.
