### ISSUE TITLE
Pet resilience

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4314]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pets take absurd amount of damage right now, i believe the issue is resilience is not working on pets or aoe damage reduction.

**How to reproduce:**
Test damage on a pet where the owner has 0 resilience, and test it where the owner has resilience.

**How it should work:**
Pets should inherit owners resilience, and take reduced aoe damage aswell.

**Database links:**

**Comment by Kenniflopper** [comment]
https://cdn.discordapp.com/attachments/1071417987673882766/1142826354438582393/image.png just as an example, you can see how a bladestorm killed almost 4 pets in its duration. 1 of hunter pet, 1 of dk pet, gargoyle, and almost the dks second pet. also how we almost died aswell (i reported sweeping strikes in a different issue)

**Comment by bonfax4** [comment]
Tested and sweeping strikes + bladestorm interaction is not working 100%, it should only give you one sweeping per spin (every second) and i sometimes get more. This was hotfixed in wotlk. Also https://github.com/gamefreedomgit/Maelstrom/issues/4290 thats was fixed recently might have been part of the issue too. Avoidance I'm not 100% sure if it should work in cata pvp, it didn't in wotlk. 

![e45677b5ab993f7da49c8e66af61be8d](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/62b23435-4a98-435c-900b-cc6636accc40)
2 sweeping in the same second. You can prob pull off more depending on targets, I rly only tested on 3.

**Comment by SimonBpvp** [comment]
Yeah avoidance is pve only if thats what you meant, Kenni. I made this report #4287 which I thought was the problem. Cause I'm sure pets had blizzlike HP from start of the server but then they unfixed it.

**Comment by Afgann** [comment]
fixed
