### ISSUE TITLE
Hunter pet Ability: Intervene gamebreaking bug

### ISSUE THREAD

**Issue by Qidpuncher-outland** [gamefreedomgit/Maelstrom#4316]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The petspell "Intervene" from hunter currently absorbs the damage entirely sort of like a shield instead of absorbing just the next attack (physical i assume)

**Proof**

It's written in the tooltip itself "Your pet runs at high speed towards a group member, absorbing damage done against them for the **next attack** equal to 50% of your pet's total health

**How it should work:**

Should just absorb the next attack instead of acting like a shield
important note: it should not be removed by dots/bleeds as seen in this video: https://www.youtube.com/watch?v=SMSj3jzoBRE&ab_channel=Keeper01

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=53476

**Comment by aymenqtx** [comment]
Hello @Sketish. This should be considerer as "Critical" rather than High, because some people are currently abusing this intervene bug in arena (2s/SoloQ). Can we get a fix soon? @UltraNix

**Comment by Qidpuncher-outland** [comment]
This is quite  gamebreaking btw, would be amazing to see some love. I for my part wont que until this is fixed because some classes cant do anything about it

**Comment by SimonBpvp** [comment]
https://www.youtube.com/watch?v=n3Axlkm2_IA&feature=youtu.be
Yo, these are 3 where the bug was happening
