### ISSUE TITLE
shannox didnt dropped item

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4317]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**shannox didnt dropped crystalized firestone 

**How to reproduce:**

**How it should work:**
![WoWScrnShot_082523_174659](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/fdda76b2-e17b-422d-9366-e56ca82e40eb)

**Database links:**

**Comment by Sketish** [comment]
It doesnt have 100% drop chance
