### ISSUE TITLE
mirror image miss

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4318]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**im full hit capped as seen in photo and mirror image is missing hits

**How to reproduce:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/6764f957-9a09-4d42-973a-e473ea90c980)

**How it should work:**

**Database links:**

**Comment by Qidpuncher-outland** [comment]
They also break cc when they shouldnt

**Comment by suybird** [comment]
there should be a perm 1% chance to always miss spells

**Comment by jlldarocha** [comment]
> there should be a perm 1% chance to miss spells

??

**Comment by xmrshoot** [comment]
@suybird 1@ chance , they casted 4 fireball and 1 in 4 is miss

**Comment by bonfax4** [comment]
> there should be a perm 1% chance to miss spells

No. That was only in vanilla/tbc. Removed in wotlk
