### ISSUE TITLE
Blink on blades edge bug

### ISSUE THREAD

**Issue by Qidpuncher-outland** [gamefreedomgit/Maelstrom#4322]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you blink as a mage on blades edge arena, ontop of the bridge, angling your camera towards the ledges on the side you blink down instead of to the ledges

**How to reproduce:**

do what was exlained above

**How it should work:**

You should blink towards the ledge where the terrain basically ends even if its just a 0,5 meter blink. It kinda acts like a "wall" if u want so.  Its usually always like that with any kind of ledge and high differences

In addition to it, you also blink through the tomb on lordearon instead of just ontop of it.

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=1953

**Comment by whothatdog** [comment]
It happens in Battlegrounds too.
the blink should stop at different heights / different "Z"
if there is "hill" that people can't run on the blink should not work aswell...

some through obstacles that the Blink should not pass by them but the obscale should just stop them and prevent the blink on its fully distance.

**Comment by Afgann** [comment]
fixed
