### ISSUE TITLE
Warlock Soul Leech not working properly

### ISSUE THREAD

**Issue by OverlordDeveloper** [gamefreedomgit/Maelstrom#4325]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Soul Leech(Spellid:30295) talent from warlock destruction talent tree does not grant Replenishment after casting Soul Fire, Chaos Bolt or Shadowburn.

**How to reproduce:**
  
**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please provide any screenshot/video ro combat log

**Comment by OverlordDeveloper** [comment]
I made a mistake with this report, the talent is working as intended.
