### ISSUE TITLE
Quest BUG: Ready the Ground Troops

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#4329]
Quest "[Ready the Ground Troops](https://www.wowhead.com/quest=26374/ready-the-ground-troops)" does not work correctly.

The npc "[AWOL Grunt Disciplined](https://www.wowhead.com/npc=42893/awol-grunt-disciplined)" does not appear anywhere on the map.

It has to work as follows:
https://youtu.be/2wfmYWRz2EU

**Comment by PanJanuszek** [comment]
Can't agree with you 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/250069ba-c43c-4821-863f-07eaebc5e7ea)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/6d1b7d3f-5596-4c30-8bb0-3cc4dc870438)
