### ISSUE TITLE
Wings animation of warlocks vengeful gladiator helmets wont appear.

### ISSUE THREAD

**Issue by mistrmatt22** [gamefreedomgit/Maelstrom#4330]
**Description:**
After transmoging "Vengeful Gladiator's Dreadweave Hood" or "Vengeful Gladiator's Felweave Cowl", the animation of wings wont appear if player jumps or types /roar.

**How to reproduce:**
Transmog "Vengeful Gladiator's Dreadweave Hood" or "Vengeful Gladiator's Felweave Cowl" into head slot and jump or type /roar.

**How it should work:**
If you have transmoged "Vengeful Gladiator's Dreadweave Hood" or "Vengeful Gladiator's Felweave Cowl" into head slot item and you jump or type /roar animation of wings should appear.

***Proof from retail:**
Not really proof but you can see discussion in wowhead where people talk about it and explains it(at patch 4.3.4) :
https://imgur.com/a/gQxUiJ5 (its from https://www.wowhead.com/item=33683/vengeful-gladiators-felweave-cowl)

**Database links:**
wowhead: 
1 Fel-  https://www.wowhead.com/item=33683/vengeful-gladiators-felweave-cowl
2 Dread - https://www.wowhead.com/item=33677/vengeful-gladiators-dreadweave-hood

Cata twinhead:
1 Fel - https://cata-twinhead.twinstar.cz/?item=33683
2 Dread - https://cata-twinhead.twinstar.cz/?item=33677

**Comment by UltraNix** [comment]
No further info - closing.
