### ISSUE TITLE
Glutton for Fiery/Shadowy Punishment - Achievements in Azshara

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4331]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Neither of the achievements mentioned above are working.
The counter works, but it gives no credit once you are done without taking any damage.

(The Glutton for Icy Punishment is working)

**How to reproduce:**

Go to Arcane Pinnacle in Azshara, do the fire or shadow trial.

**How it should work:**

Once you are done without taking any damage, the achievement pops.

**Database links:**
https://www.wowhead.com/achievement=5448/glutton-for-fiery-punishment
https://www.wowhead.com/achievement=5547/glutton-for-shadowy-punishment

**Comment by UltraNix** [comment]
#2942
