### ISSUE TITLE
druids of the talon

### ISSUE THREAD

**Issue by uborg1** [gamefreedomgit/Maelstrom#4335]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/quest=29181/druids-of-the-talon)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the quest can not be completen as the npc [Skylord Omnuron](https://www.wowhead.com/npc=50082/skylord-omnuron) is not there

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#4326
