### ISSUE TITLE
工会通告成就不显示职业颜色

### ISSUE THREAD

**Issue by zbn72088** [gamefreedomgit/Maelstrom#4338]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**
![FHPIS~PN}@B5)LTJHSCN(S6](https://github.com/gamefreedomgit/Maelstrom/assets/143382496/fcabd256-c972-41c9-97cb-82a82b4cb154)

**Database links:**
![6 F`MCIN H2 $@JK9U%PBU6](https://github.com/gamefreedomgit/Maelstrom/assets/143382496/f99d8a95-1518-4070-87e4-8b862dbf1cbc)

**Comment by Sketish** [comment]
Invalid report + use english
