### ISSUE TITLE
Bug at last boss - ''Through a Glass, Darkly'' quest

### ISSUE THREAD

**Issue by mizbangz** [gamefreedomgit/Maelstrom#4339]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

I'm currently doing this quest "Through a Glass, Darkly", which is part of the legendary weapon storyline in Firelands. I got to the final boss fight but unfortunately died on my first attempt. When I reentered the dungeon, I noticed a portal at the entrance that quickly took me to the last boss's room. However, after I died again, the portal was no longer there for instant teleportation. I also tried to manually run to the boss room, but I couldn't proceed because I needed to use an elevator. Unfortunately, there was no clickable option to board the elevator and reach the boss room.

**Solution:**
There should be a portal for instant teleport to last boss room once I enter the dungeon.

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143391603/5c25617c-d8eb-46e3-b820-21da7ed06b91)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143391603/28d5d749-e582-4722-9444-62ea78398eea)

**Comment by UltraNix** [comment]
Fixed.
