### ISSUE TITLE
Lord rhyolith(Steering mechanic)

### ISSUE THREAD

**Issue by voidwho** [gamefreedomgit/Maelstrom#4340]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Steering was an issue for a while. This is just a thread to discuss potential issues that may or may not be.
My thought at the moment(from raiding in past few ids) is following:
 - Lord rhyo hp ticks every second(or half a second, im not sure) - He adjusts HP of both leggs.
 - This damage affects the steering?(it shouldnt?)
 
Random rhought:
So if everyone hits RIGHT leg, tick happens, leg HP gets adjusted, LEFT leg "takes" fake dmg, scale tips to left?

Does this adjustment affect steering(at current implementation)? From what I cna see it does.

Inertia is a mechanic of Rhyo(IE - his tendency to go straight if nothing happens). Eventualy - if damage is not present, or if damage is equal, he should balance himself and start walking forward, but if u actively hit ONLY 1 leg, he should never readjust until you change your target. 
2 possible issues(im not sure which one is true)
1. HP adjustment ticks of BOTH LEGS affect steering(they shouldnt)
2. "Inertia" mechanic kicks in when it shouldn't.
**How to reproduce:**
Go in FL and hit only 1 leg.

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Duplicate.
