### ISSUE TITLE
Eagle Eye not updating player locations

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4342]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Hunter spell Eagle Eye is not updating the movement of player characters, only pets and NPCs

**How to reproduce:**
Use Eagle Eye on an area with friendly or hostile players. Easier to spot if players are moving, but they are all standing or running in place like they lagged out

**How it should work:**
Player movement should be updated.
This is a bug with high impact in rated battlegrounds.
Additionally, could also be affecting the Shaman spell Far Sight, but I don't have a shaman handy to test

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=6197

**Comment by djesic** [comment]
@UltraNix I think it might also be affecting priest's Mind Vision on far away targets. New ticket or is this ok?

**Comment by UltraNix** [comment]
@djesic Should handle that one as well.

**Comment by UltraNix** [comment]
Fixed.

**Comment by djesic** [comment]
I've made a macro:
`/cast !Eagle Eye`

It allows to cast Eagle Eye while channeling, this was possible on retail Cataclysm as well, but after leaving the initial cast area, no new NPCs spawn in the world.

**Comment by djesic** [comment]
@UltraNix 
Using that macro, I experienced the same initial issue in PvP, was scouting and recasting and players stopped moving

**Comment by djesic** [comment]
I tried Eagle Eyeing from Hyjal over to Orgrimmar with this and I didn't see anyone.
Also, the spell animation stayed even when I casted another Eagle Eye.
I had party members in the world there and I could not see them
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/794f976a-aed4-48ac-8b3c-e5b6592674f6)

**Comment by UltraNix** [comment]
Fixed.
