### ISSUE TITLE
Rogue Poison on Thrown proccs also when u use envenom 

### ISSUE THREAD

**Issue by FB190709** [gamefreedomgit/Maelstrom#4345]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Invalid report.
