### ISSUE TITLE
Fear pathfinding is bugged asf here

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4347]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hi, whenever I get feared in a BG or arena and im on the edge of something i always fell down, its just ridiculous...

and when you get feared i notice that character flees around for a large portion of the space...

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#4283
