### ISSUE TITLE
Rhyolith Targetability of the Head/Body

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Maelstrom#4349]
**Description:**
Every Video on youtube, guide etc says that rhyolith's body/head should be targetable and damagable before last phase but currently only the legs are targetable and damgable.
should be considered critical since this is a pretty important part of the boss

**How to reproduce:**
engage boss, not a single kill i have done on normal since first week on 4 characters had the head targetable.

**How it should work:**
Head should be targetable and damagable.

https://www.youtube.com/watch?v=ejAKEb_NSRQ one of the many youtube vods where the head is targetable (retailvod)
https://www.youtube.com/watch?v=mzSvmlvcS7w another one from retail
https://www.youtube.com/watch?v=N0RTqce9_4o and this one is from twinstar/apollo
as you can see the % hp on lord rhyolith boss bar (right side under minimap) goes down from 100% 
https://www.icy-veins.com/wow/lord-rhyolith-strategy-guide-normal-heroic
to cite icy veins : During Phase One, Rhyolith's left and right foot have their own unit frames and can be attacked. Rhyolith himself is, of course, also attackable. The protection provided by his armor also applies to his feet.
Please scroll down to "3. Damaging Rhyolith" section to understand more of how that part works.

**Database links:**

**Comment by Sketish** [comment]
On your sources no1 of them was targeting head, just only frame occurs so players can see that

**Comment by Manpower99** [comment]
Ill make a seperate report for that, as for the first part yes it is a bug and this is the same one  that occurred of Apollo1 aswell and got fixed before Apollo2, guides online including icy veins specify it which i have linked. in every single video theres a boss health frame of the head... 
and heres another video
https://www.youtube.com/watch?v=cAuCDdBUEZ8 you can see when boss is casting the stomp through the boss frames here which currently is a functionality that doesnt exist in whitemane maelstrom. you can see in multiple apollo videos searing totems and chain lightning hitting the head also.
to cite more of icy veins : Unfortunately, ranged DPS will be busy with adds for a large part of the phase while melee DPS will sometimes need to move away from the boss to help with the Fragments or to avoid Summon Fragments of Rhyolith or Spark Therefore, every DPS needs to help out with attacking the feet, whenever they can. Eventually, players will find the right balance between attacking the feet and doing their other tasks. They can also attack Rhyolith's chest if they simply want to damage the boss without interfering with his current direction.
so yes, you should be able to attack his head/body/chest whatever you want to call it, since they all share Obsidian armor and Hp its irrelevant the only difference is that attacking the legs is what causes the movement/steering of the boss.

**Comment by Sketish** [comment]
Stop using Icy Veins as a source or Apollo videos . Provide any retail video when people are targeting head and can damage that.

**Comment by Manpower99** [comment]
Considering that tauri veins website is basically a copy paste of 4.3 icy veins and it also has the same word for word, but sure i wont use apollo or icy veins.
the only change ( based on retail changelogs that happened in WoD is the visual look of magma flow )

so heres a retail vod https://www.youtube.com/watch?v=aRKayYLQ8Lw
you can check target of target frames of this guys PoV when he targets the mage he is hitting the body under the name of "Lord Rhyolith" which you can also see the debuffs placed on the target aswell which will include corruption and dk diseases
go to timestamp 1:13 and 1:47

**Comment by Sketish** [comment]
On that videos it looks like some aoe spells may hit the head, 
https://youtu.be/JKDkSu7Iy7U?t=30 , 0 debuffs on boss just on legs

**Comment by Manpower99** [comment]
did you actually check the timestamps or not because you can clearly see corruption and frost fever

**Comment by Sketish** [comment]
May that was a bug, on 25m heroic video I linked there are 0 debuffs on boss frame

**Comment by SexyPancake** [comment]
Actual Icy-veins guide that was available during 4.3 patch where it's specified that Rhyolith is meant to be damageable during P1.

https://web.archive.org/web/20120626135128/http://www.icy-veins.com/lord-rhyolith-detailed-strategy

**Comment by Sketish** [comment]
I'm closing this issue, we won't be changing anything regarding targeting body since people werent doing that on retail
