### ISSUE TITLE
Transmogrification bug.

### ISSUE THREAD

**Issue by biljak323** [gamefreedomgit/Maelstrom#4351]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Problem with transmog, cannot transmog Vicious Gladiator's Decapitator into Hellslayer Battle Axe, both weapons are axes and game says "This item's appearance cannot be used."

**How to reproduce:**

**How it should work:**

It should change appearance, Vicious Gladiator's Decapitator should look like Hellslayer Battle Axe

**Database links:**

https://www.wowhead.com/item=61326/vicious-gladiators-decapitator
https://www.wowhead.com/item=13017/hellslayer-battle-axe

**Comment by UltraNix** [comment]
https://www.wowhead.com/item=13017/hellslayer-battle-axe#comments:id=1562352:reply=619823
