### ISSUE TITLE
Booty Bay NPCS

### ISSUE THREAD

**Issue by suybird** [gamefreedomgit/Maelstrom#4352]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are no NPCs at Booty Bay

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
