### ISSUE TITLE
Balance Druid T12 2p - Burning Treant Fireseed Missing Despite Being Hit Capped.

### ISSUE THREAD

**Issue by JimboLimbo175** [gamefreedomgit/Maelstrom#4353]
**Description:**
The [Burning Treants](https://www.wowhead.com/spell=99035/burning-treant) summoned by the [Balance Druid Tier 12 2p](https://www.wowhead.com/spell=99019/item-druid-t12-balance-2p-bonus) bonus can miss their [Fireseed](https://www.wowhead.com/spell=99026/fireseed) cast despite the player being hit capped.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/fd62a1bf-f370-4456-a2fd-7a1e10d7775f)

Seems to be a very similar issue to https://github.com/gamefreedomgit/Maelstrom/issues/4293

**How to reproduce:**
1. Equip a Balance Druid with the Tier 12 2piece bonus.
2. Ensure the Druid is spell hit capped.
3. Cast Wrath/Starfire on boss level enemy until the 2p is procced and a burning treant is summoned.
4. Wait for the treant to cast and observe that it might miss.

**How it should work:**
The Burning Treants' cast should not miss.

**Database links:**
https://www.wowhead.com/spell=99035/burning-treant
https://www.wowhead.com/spell=99019/item-druid-t12-balance-2p-bonus
https://www.wowhead.com/spell=99026/fireseed

**Comment by UltraNix** [comment]
Fixed.
