### ISSUE TITLE
add bug in the achivement king of the spider hill

### ISSUE THREAD

**Issue by lebombas** [gamefreedomgit/Maelstrom#4354]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in the achievement king of the spider hill the penultimate add to climb this bug and falls below

**How to reproduce:**
when the add appears it drops

**How it should work:**
The add should stay on the platform in order to scale.

**Database links:**
https://www.youtube.com/watch?v=B_JdJeMUo2s&ab_channel=CollinHarris

**Comment by UltraNix** [comment]
#3891 4277
