### ISSUE TITLE
Npcs not present in quest No Escape

### ISSUE THREAD

**Issue by tommyboogers** [gamefreedomgit/Maelstrom#4359]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There are supposed to be a few npcs in the top floor of Fenris keep for the quest No Escape, in Silverpine Forest, but these npcs aren't there and the cinematic to complete the quest won't play

**How to reproduce:**
Go to teh top floor of Fenris Keep in Silverpine Forest

**How it should work:**
Theres hould be NPCs in the room, upon entering, a cinematic will play

**Database links:**
https://www.wowhead.com/quest=27099/no-escape

**Comment by GM-Nightmaree** [comment]
quest is working fine
![image](https://github.com/gamefreedomgit/Maelstrom/assets/157993777/d614f407-f235-4517-9170-4b7e67396fb1)
