### ISSUE TITLE
Shaman Fire elemental 

### ISSUE THREAD

**Issue by Igria123456** [gamefreedomgit/Maelstrom#4360]
Description:
Lately Fire elemental has been attacking anything and everything from your raid to bale crystals to hand of ragnaros and to top it all off killing magma traps on the Ragnaros encounter. Therefore losing precious uptime of a big CD on Bosses.

CLIP1: Fire elemental attacking baleroc shard (losing 25seconds of uptime on boss). I know shard was made immune but it should be made untargatable by all sources
https://clips.twitch.tv/MildSuspiciousPigeonKappaRoss-84qGv89BahWVKBYt
Warcraft Log pic:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/137830486/7d7d4645-dd78-4639-99a7-2242b8f32afc)

CLIP2: Fire ele targeting everything possible on rag encounter when he goes down during intermission.
https://clips.twitch.tv/BenevolentPlumpPheasantTheTarFu-VEacL4q7DK0MQcHC
Warcraft Log pic:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/137830486/ebf8fe45-77dc-4cb0-a53b-5189c8ff7496)
Details pic from other pulls:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/137830486/be208848-42a4-4d6b-b090-a123b3a16c3c)

CLIP3; Fire elemental not fixating on closest target (check how i waited for the dog to go away)
https://www.twitch.tv/videos/1911670461

EXTRA; Fire elemental was also targeting people getting MCed even after they were kicked on Cho Gal (never happened for 5months of whole t11 patch) sadly i don't have a clip.

How to reproduce:
Simply just spawn your fire elemental and pull boss.

How it should work:
IMO you should make Fire elemental target the mob which currently has active Flame shock OR make all of these mechanics completely untargetable by all sources. Alternative fix could also be making fire ele fixate on closest target that is spawned to.

Database links:
https://classic.warcraftlogs.com/reports/tXfvTc6a2Kx8JYrZ

**Comment by amanita199** [comment]
also if you get MCed on chogall it will attack the raid members from oposite faction till summon other totem

**Comment by Stega23** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94021456/e0c93184-c583-45ab-aa99-30abc0baf643)
Fire ele can indeed target all the invisible trigger stuff(invisible for player), possibly breaking game mechanics if it kills that stuff

**Comment by BalanCV** [comment]
https://www.engadget.com/2011-07-23-totem-talk-fixing-the-fire-elemental-problem.html

To quote:
"In theory, your Fire Elemental prioritizes targets with a [Flame Shock](http://www.wowhead.com/spell=8050) on them. In reality, though, he's got the attention span of an undergraduate in a statistics class and spends half the fight DPSing the wrong target."

This confirms two things 1. Fire ele was just as retarded in blizzard cata 2. Just like searing totem its supposed to (or intended to) prio the freshest application of flame shock as a target.

**Comment by Igria123456** [comment]
![WoWScrnShot_090123_183948](https://github.com/gamefreedomgit/Maelstrom/assets/137830486/7cd67430-f30e-4876-a695-bcf6bdbb5658)

**Comment by Stega23** [comment]
> Fixed.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/94021456/b8f19719-deb8-4711-96d0-e1cc191593c1)
Can you reopen?

**Comment by UltraNix** [comment]
Should be fixed.
