### ISSUE TITLE
Deeper into Darkness Quest

### ISSUE THREAD

**Issue by yaraisop2** [gamefreedomgit/Maelstrom#4361]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
you can't kill the big spider

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=neOikNxWwk8

**Database links:**

**Comment by Sketish** [comment]
Invalid report
