### ISSUE TITLE
Pets run speed.

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4362]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Some pets are running faster than travel form druid.
like Felguard, Wolf etc.
It's hard to 'kite' them if they none-stop attacking and run faster than they should.

**How to reproduce:**
Try use rogue sprint or feral with travel form and send pets to attack it
see if it matching feral's travel form speed and 'catch' the druid while running away from the pets...

**How it should work:**
Not sure, but Hunters' pet require to pick **talents** to speed increase otherwise the speed should be normal(?)
Warlock pets are running faster than **druid** with travel form 140% speed // 170% speed.

Happened in low BGs 10-60+ but possible at max level BGs 85 too.

**Database links:**

**Comment by Pornoodemon** [comment]
By default, the warlock's pet speed is 100% of the warlock's speed.
And the Felguard runs faster because of their abilities.
The Felguard catches up to you with a charge and after that it gains 30% speed for a duration, and 15 sec cooldown this spell 
He also has immunity to all types of control for 15 seconds,  you not will be able to run away from the Felguardian of filth in most cases.

**Comment by whothatdog** [comment]
> By default, the warlock's pet speed is 100% of the warlock's speed. And the Felguard runs faster because of their abilities. The Felguard instant catches up to you with a charge and after that it gains 30% speed for a duration, and 15 sec cooldown this spell He also has immunity to all types of control for 15 seconds, you not will be able to run away from the Felguardian in most cases.

Yeah I know how Felguard works :-)
I mention it's not only Felguard but more pets.

About Felguard specificily: 130% vs 140% is still -10% slower.

Unable to 'turn' the pet off me 80% bg-map with travel form...

**Comment by Pornoodemon** [comment]
If the warlock is on a mount, the pet's speed will also be increased.
I just checked the pets, they run at normal speed.
I do not understand under what conditions he can catch up with you

**Comment by whothatdog** [comment]
> If the warlock is on a mount, the pet's speed will also be increased. I just checked the pets, they run at normal speed. I do not understand under what conditions he can catch up with you

the condition was in bg, travel form vs pet sent to attack.
the warlock/hunter were not mounted up.

Wolf, Felguard, Voidwalker and other pets sometimes are run at speed higher than the normal
without pets' talents, I guess it's some bug they're 'forced' to attack the player they sent to attack
so their speed somehow increasing to "match" the players' speed.


When pet owner is mounted up it should run **to return** to the player lol...

**Comment by Pornoodemon** [comment]
Perhaps something similar is present. But it most likely works sometimes and you need to understand under what conditions.
I tried to repeat by attacking a fleeing player and I couldn’t specifically increase the speed of the pet.

**Comment by UltraNix** [comment]
Player pets always want to have the same speed as their master.

**Comment by whothatdog** [comment]
> Player pets always want to have the same speed as their master.

It's an kinda old report, tbh I haven't noticed that behavior again when pet is running faster than my travel speed without Dash etc.
peace ~

**Comment by UltraNix** [comment]
So can be closed?
