### ISSUE TITLE
rogue 4pc t12

### ISSUE THREAD

**Issue by amanita199** [gamefreedomgit/Maelstrom#4366]
**Description:**
tried to use tricks a few times and the bonus i got is:
haste
haste
crit
haste
crit
haste
crit
crit
haste

had 0 procs mastery procs

**How it should work:**
quoted from wowhead comments
"Did a bit of testing.

haste
mastery
crit
mastery
haste
crit
mastery
haste
crit
mastery
crit
mastery

as you can see, it will not do 2 in a row, but neither does it do all 3 evenly. Whatever buff you just got, it randomly picks out of the 2 possible other buffs, as I got crit/mastery/crit/mastery chain."

**Database links:**

https://www.wowhead.com/spell=99175/item-rogue-t12-4p-bonus#comments

**Comment by amanita199** [comment]
after a few more attempts i did get the mastery proc, please check the proc rates and make them not being able to get the same in a row

**Comment by UltraNix** [comment]
Fixed.
