### ISSUE TITLE
Priest's Leap of Faith bug with scatter shot 

### ISSUE THREAD

**Issue by Setikx** [gamefreedomgit/Maelstrom#4368]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Priest spell "Leap of Faith" dont grip scatter-shotted (by hunter) targets. They are not rooted, they are disoriented, so they should be gripped. In 2012 year on official game it was working properly like i have described. This bug do the great PVP disballance against hunter teams on arenas and BG's.

**How to reproduce:**
While being priest u  have to use Leap of Faith on your mate while enemy hunter used on him Scatter shot. 

**How it should work:**
Scattered target should be gripped. 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=73325
https://cata-twinhead.twinstar.cz/?spell=46681

**Comment by Qidpuncher-outland** [comment]
Feels like the same for DB etc, it just doesnt really seem to work on ccd targets for some reason

**Comment by Setikx** [comment]
Yea, at all with CCed targets

**Comment by Afgann** [comment]
fixed
