### ISSUE TITLE
Lord Rhyolith - volcano

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4369]
**Description:**
Currently when Lord is channeling ignite Volcano and he steps on that volcano armor stacks are removed but if he walk through volcano after ignite animation and before volcano start exploding then stacks arent removed from boss.

**How it should work:**
After casting ignite volcano he should be always counted as active

**Database links:**
https://youtu.be/pzb2sQHa0tg?t=35

**Comment by UltraNix** [comment]
Fixed.
