### ISSUE TITLE
Lord Rhyolith pets avoidance

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4370]
**Description:**
Currently pets on Lord Rhyolith are dying to stomps or magma flow. They should have 90% reduced dmg from stomp and they shouldnt be able to get hit by magma glow

**How to reproduce:**
Pull Lords as unholy dk or hunter and see that pet is getting full dmg on each stomp or magma flow

**Comment by UltraNix** [comment]
#4260
