### ISSUE TITLE
Alysrazor - Alysra's Razor buff

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4371]
**Description:**
Alysra's Razor buff should be apllied to player after getting 24 stacks of Blazing Power

**How to reproduce:**
Pull alysrazor and start flying through circles and watch when player is getting  Alysra's Razor buff 

**Database links:**
https://youtu.be/1tX64eLakrs?t=184
https://youtu.be/i9p97AkGb74?t=450

**Comment by UltraNix** [comment]
Fixed.
