### ISSUE TITLE
Previous tier's Justice Point gear missing from vendor, Gunra

### ISSUE THREAD

**Issue by kekonomics** [gamefreedomgit/Maelstrom#4375]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As of the Firelands patch, Gunra <Justice Quartermaster> in Org (the Justice Point vendor) no longer sells the ilvl 346 blue gear after the 359 epic gear was moved to her inventory.

**How to reproduce:**
- Talk to Gunra in Org
- Note that the previous ilvl 346 JP gear is not available

**How it should work:**
Previous ilvl 346 JP gear should be available.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=46555

**Comment by kekonomics** [comment]
![2023-08-31 19_12_24-Greenshot](https://github.com/gamefreedomgit/Maelstrom/assets/132790862/eff965a1-f626-4c21-8958-9484a49f718a)

**Comment by itsemmastone** [comment]
Part of the 4.3 content - the current vendors are designed for the 4.2 version.
