### ISSUE TITLE
Two of the Twilight Highlands Dragon Quests Bugged

### ISSUE THREAD

**Issue by Udnossidos** [gamefreedomgit/Maelstrom#4376]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Two of the Dragon Quest ("Draconic Mending" and "Life from Death") in Twilight Highlands are bugged.

"Draconic Mending":
There are no healers anywhere to protect.

"Life from Death":
You can't plant ruby seeds on the corpses. It always tells you "Wrong Target"
**How to reproduce:**

**How it should work:**
Seeds should be possible to plant on the corpses and healers should be standing in the area to protect.

**Database links:**

**Comment by Sketish** [comment]
It's already fixed on PTR, not on live server yet

**Comment by PanJanuszek** [comment]
Yes, PTR so far
