### ISSUE TITLE
Death in orgrimmar, 3rd person view after

### ISSUE THREAD

**Issue by Kupsztall** [gamefreedomgit/Maelstrom#4377]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sudden death while just standing idle in orgrimmar, after using reincarnation im moving in 3rd person view
(im shaman with black transmog that's moving around)

**How to reproduce:**
dunno, just stay idle in orgrimmar

**How it should work:**
well, i shouldn't die from nothing, then i shouldn't see my character from 3rd person view

**Database links:**

can't contain a video here since its too big, link to yt
https://youtu.be/IrdH72EbQ14

in addition this is the view that i welcome when i logout and login
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143804732/66d01f60-04c6-4ffa-bb82-a490df06fb0a)

**Comment by Pornoodemon** [comment]
There was a similar problem. I walked out of the auction house and it's unclear why I died and encountered this. After next die and  the resurrection, the problem disappeared.

**Comment by BalanCV** [comment]
Bug existed since the start of the server. The deaths in ogri seem too random to figure out why, only info I got is that combat log says "Dies from fall damage" even though you are just moving around or even flying on mount.
Never encountered the camera displacement though, prolly because of reincarnation.

**Comment by MadeinNoxus** [comment]
I mean grant inmunity to fall damage in Orgrimmar/Stormwind, probably would do it and if you can make a command for disable/enable it would be a great idea and probably somehow help with the issue until the issue is foung.

**Comment by UltraNix** [comment]
Fixed.
