### ISSUE TITLE
Earth Shield does not work on pets

### ISSUE THREAD

**Issue by AlpReal** [gamefreedomgit/Maelstrom#4378]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Earth Shield does not get consumed on pets. I noticed, that at least shadow priests and warriors do not trigger Earth Shield on warlock pets.

**How to reproduce:**
Put Earth Shield on a warlock pet and make it take damage from another player. 

**How it should work:**
When the pet has Earth Shield, attacks on it should consume one charge every few seconds.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=974

**Comment by Afgann** [comment]
fixed
