### ISSUE TITLE
Sweeping strikes Double Dip

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently sweeping strikes is bugged, it doesnt transfer over crits to secondary target, and it currently double dips into both armor and resil.

**How to reproduce:**
Pop sweepings strikes, and hit a target with another enemy nearby.

**How it should work:**
Sweeping strikes should double dip into resil only and NOT ARMOR and crits should be transferred over to secondary target.

**Database links:**
https://cdn.discordapp.com/attachments/1049306466949017690/1147143897051566161/Screenshot_2023-09-01_142000.png - Shows that they removed the double dip into resil in mop which indicates it was a thing during cata.

Screenshots of a bajheera video showing the damage difference.

https://cdn.discordapp.com/attachments/1049306466949017690/1147152872618860644/Screenshot_2023-09-01_145535.png
https://cdn.discordapp.com/attachments/1049306466949017690/1147154057576861736/Screenshot_2023_0901_182926.png

**Comment by Juiceyyhi** [comment]
https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

Timestamped from retail.

If you crit on ur MAIN TARGET with Sweeping Strikes, your offtarget will also get critted. 
Your offtarget will not get affected by armor, the armor will only be calculated from MAIN TARGET > transfer damage to offtarget.

The issue on Whitemane:
I crit on maintarget, but it will not transfer to offtarget.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/34742335-745c-4fde-8955-431af41ad927)

**Comment by Juiceyyhi** [comment]
If you look on the timestamped video, he crits on maintarget > gets transferred over to offtarget.

https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/a3353a8c-ef56-4f1c-a58a-6683475652e4)

**Comment by Qidpuncher-outland** [comment]
Crits are still not transfered, SS missing a huge part of their damage due to that

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/4d81d11c-1c9a-4673-be1c-9f45218259c9)

Crits are still not being transferred!

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/af537d04-39c8-4514-8b6a-1aa654dd3896)

Both targets should receive the same amount of damage!

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/73aa2e39-15cf-4e1d-aefa-87b399128891)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/889cc102-be47-47ae-8b9b-ef8b1bf5b0c1)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/9227cd0e-9e17-4309-94ac-a4ae48587db5)


Offtarget is still receiving less damage when a critical strike occurs.

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/2442aaa6-75d9-4ea1-8825-f49f5a29e51c)
This image is from retail, with csmash up. The damage is properly being transferred over to the offtarget.

SOURCE: https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/090ae7d3-22a1-452a-b6ba-343039a55888)

This picture is from a combat log on Whitemane.
This shows that the maintarget is getting collosus smashed, but the offtarget dummy receives less damage than the main target.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/326ee65a-706c-4b0f-8bb4-fdee591db4bb)

Following up this.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/d4919711-94a8-4667-84d3-13b86e4fbc5c)
Maintarget has collosus smash, 100% armor pen debuff.
Offtarget doesn't receive identical damage. 


![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/10706bf3-ef96-4a8a-8de6-63d7b762d70e)

Both of the target dummys are the same identical level.

**Comment by Juiceyyhi** [comment]
According to this video, both targets should receive IDENTICAL damage values.
But on Whitemane it's not.

https://youtu.be/WMB4y4vVrto?si=blXOisDcUa4aOI2-&t=1115

**Comment by Juiceyyhi** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/88956d92-c78b-4652-a026-89db9268d176)
23% crit damage is not being applied to offtarget.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/7b75bb0e-102e-47b5-8e84-1a9ecbd17cff)

Warrior best talent point, is not being applied to offtarget damage values. 

The remaning 3% crit dmg modifier that is not being calculated to offtarget is.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/37423971/afdb3d39-69bd-43b0-a33d-9c5115a7f0f2)

**Comment by Afgann** [comment]
fixed
