### ISSUE TITLE
 [Los celadores vigilan]

### ISSUE THREAD

**Issue by jhr84** [gamefreedomgit/Maelstrom#4381]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
La mision no puede ser compeltada a pesar que se siguen lo pasos con los objetivos adecuados, el NPC (Celadora) lo atrapa, pero no lo lleva, no completa la mision.

**How to reproduce:**
Deberia llevarse al que esta atrapado.

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=29192/the-wardens-are-watching

**Comment by Sketish** [comment]
Translate to english please
