### ISSUE TITLE
Herbs spawn bug

### ISSUE THREAD

**Issue by Couragemeow** [gamefreedomgit/Maelstrom#4382]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
A bug with the location of herb spawns.

**How to reproduce:**
just fly up and see

**How it should work:**
it should just slide freely

**Database links:**
https://www.youtube.com/watch?v=7UML6GN_uSM

**Comment by UltraNix** [comment]
Fixed.
