### ISSUE TITLE
Lord Rhyolith - not reducing stacks on stomp/add spawn

### ISSUE THREAD

**Issue by IAmMijae** [gamefreedomgit/Maelstrom#4383]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Lord Rhyolith - According to your changelogs, should now reduce his molten armor every stomp / add spawn - https://imgur.com/a/32Hu4Ra

**How to reproduce:** - This wasnt occuring when we killed the boss tonight

**How it should work:** - As your changelogs suggest

**Database links:**

**Comment by Sketish** [comment]
Please provide any logs/video or ss,
