### ISSUE TITLE
"And the Meek Shall Inherit Kalimdor" achievement not working

### ISSUE THREAD

**Issue by MarioVrenzola** [gamefreedomgit/Maelstrom#4384]
**Description:** The quest where you have to throw the bear cubs from the trees doesn't gives you the check mark for this achievement (a friend said it worked for him randomly the 5th time he did the daily)

![frfegthuief](https://github.com/gamefreedomgit/Maelstrom/assets/133254960/8d0df903-7cc5-482f-ab8b-58fef925d83f)

**How to reproduce:** do quest

**How it should work:** it should count once done

**Database links:** https://www.wowhead.com/achievement=5868/and-the-meek-shall-inherit-kalimdor

**Comment by Revly** [comment]
Work
Check use a bear aim at a cannon and throw the bear at it and it should count, if not it works just with another one closer

**Comment by MarioVrenzola** [comment]
> Work Check use a bear aim at a cannon and throw the bear at it and it should count, if not it works just with another one closer

tried it on an alt and it worked straight away, yeah you have to try with different bears because not all counts
