### ISSUE TITLE
"Ready for Raiding II" Achievement not working

### ISSUE THREAD

**Issue by MarioVrenzola** [gamefreedomgit/Maelstrom#4385]
**Description:** been trying for the last 3 days getting credit on every boss by dodging everything (Even abandoned quest to retry multiple times) but still didn't get credited for not even 1

![dwddw](https://github.com/gamefreedomgit/Maelstrom/assets/133254960/58706906-11c6-42ef-af15-502cc38d9c10)

**How to reproduce:** Dodge special attacks and kill boss and it won't credit

**How it should work:** it should give credit for achievement

**Database links:** https://www.wowhead.com/achievement=5873/ready-for-raiding-ii

**Comment by Revly** [comment]
Totally True

**Comment by emirie1** [comment]
I have attempted this for the last 4 days and have not gotten credit for any of the 4 bosses that I've defeated. I've done the Ancient Firelord, the Cinderweb Queen, the Ancient Smouldering Behemoth, and the Ancient Charscale all without being hit by any special attacks. I have not gotten credit for any of these.

**Comment by XYNKA** [comment]
@emirie1 same here!

**Comment by UltraNix** [comment]
@MarioVrenzola @Revly @emirie1 @XYNKA Please - test it again.

**Comment by Revly** [comment]
With Elite Charscale no work Archiev
![IMG_20230911_122424](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/8b67dd51-2eec-4f2a-9614-43e341d30de8)

**Comment by UltraNix** [comment]
What about others?

**Comment by Revly** [comment]
Ancient Smoldering Behemoth, also

**Comment by UltraNix** [comment]
Fixed.
