### ISSUE TITLE
Retribution T12 2p Debuff refresh bad calculations

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4386]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Intro for explanation: set bonus inflicts a debuff on every crusader strike. The debuff deals 15% crusader damage in total. The debuff lasts 4 seconds and ticks only twice every 2seconds, as such one tick will deal 7.5% of that crusader's damage.
The premise of this report is that you should never lose any of the damage done by previous crusaders by refreshing the debuff with a new crusader.

The bug works differently depending on when you refresh the debuff with a new crusader so I will explain them as bug1 and bug2:

**Bug 1 ( might happen during bloodlust+procs and will 100% on alysra flight)**
This happens if you refresh the debuff before any ticks have gone through meaning you need to cast crusader at maximum of 2sec after the first. At certain high haste levels this is possible.

By doing 2 crusader strikes the calculations for individual ticks should stack as follows:
(CrusaderStrike1(1078) * 0.075 ) + (CrusaderStrike2(1078) * 0.075 ) = 81+ 81 = 162 per tick (continue formula for n crusader strikes)
Currently on the server the damage done is way less: 107 per tick 
https://imgur.com/a/UU0Nqqs

**Bug 2 ( MAJOR BUG as this will happen to any normally geared ret even without haste buffs)**
This happens when you refresh the debuff after 1 tick has gone through meaning you need to cast crusader strike between 2 and 4 seconds which is 100% of the time.

Currently on the server if you refresh after 1 tick, the refreshed debuff will IGNORE the previous tick entirely and will only do the damage of the newest crusader strike debuff. (not terminology expert but I believe this is called munching)
Since we are not supposed to lose damage the calculation for this situation should be as follows:
(PreviousLeftoverTick(80) + (CrusaderStrike2(1080)*0.15) ) / 2 = 240 / 2 = 120 dmg per tick
Instead on the server 3 ticks 80 dmg each: https://imgur.com/a/iKzUbly

Other than that if you let the debuff drop (which shouldn't happen on target active uptime) it behaves normally. 
(+-1 dmg because of weird client floating point approximation if you are wondering why 7.5% of 1078 is 81 and 7.5% of 1080 is 80 in my showcase above lol)

**How to reproduce:**
Bug 1: Use crusader strike again before 2sec have passed (so no ticks have gone through yet)
Bug 2: Use crusader strike again after 2sec but before 4sec (so 1 tick from previous debuff went through) - usual scenario

**How it should work:**
https://www.wowhead.com/spell=99093/item-paladin-t12-retribution-2p-bonus#comments
"It's been confirmed that the DoT works logically: it rolls like Ignite. We won't lose damage by using Crusader Strike before the DoT is finished ticking."

**Database links:**

**Comment by bonfax4** [comment]
This is not what you would call munching, "dot rolling"  is just non-existant if it works the way you describe. They should check this behaviour with all similar t12 procs because this is a reoccurring issue. They fixed this for rogue t12 recently

**Comment by BalanCV** [comment]
I actually checked the tier sets with dots when I noticed this bug and I think rogue one is the only other one. Will go and test that out as well when I have some time.

**Comment by Afgann** [comment]
fixed
