### ISSUE TITLE
Hunter - pet talent wild hunt (cunning pet + ferocity)

### ISSUE THREAD

**Issue by Lycadd** [gamefreedomgit/Maelstrom#4387]
**Description:**
Cunning pet talent "Wild Hunt" is nerfing pet's basic attacks AND melee hits. Ferocity pets with the same talent are not affected by this bug.
On this screenshot, pet basic attack Bite with Wild hunt 2/2 and <50 focus 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134816583/fa926c40-aee0-4608-bd44-1bde1298a3da)

On this one, pet basic attack Bite without Wild hunt (focus doesnt matter)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134816583/84fa1794-5045-43ea-ae77-c33cf375a831)

Furthermore, wild hunt bonus damage with >50 focus increases pet basic attack by 100% instead of 120%. Ferocity pets have the same issue as well.
Screenshot with wild hunt 2/2 and focus >50
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134816583/c9b9ae80-14c4-4792-a407-d7bf1f7659ee)

**How to reproduce:**
Tame 2 cunning pets, spec only one with wild hunt and compare bite damage with <50 focus and melee hits

**How it should work:**
Pets basic attacks and melee base damage should be the same regardless of wild hunt and when a basic attack is used with pet focus >50 it sould do 120% more damage.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=62762

**Comment by Afgann** [comment]
fixed
