### ISSUE TITLE
A more powerful spell is already active!

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4389]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I found that in Whitemane the "A more powerful spell is already active!" is not available.
for example using Recuperate with 5 combo points,
then using Recuperate with 1 combo point. it overwritting the 'stronger' Recuperate.

There a **list** of abilties that has that mechanic preventing overwritting stronger spells.
I can't name them.

**How to reproduce:**
Recuperate 5 points => Recuperate 1 points.

**How it should work:**
~

**Database links:**
I don't have links, I just logged to Twinstar and tried it with Recuperate.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/ed5c4acc-c781-4ca7-a8c5-4ec2a8c62afd)

**Comment by Sketish** [comment]
Recuperate is healing 2% each tick so there is no stronger,weaker version of that spell

**Comment by whothatdog** [comment]
> Recuperate is healing 2% each tick so there is no stronger,weaker version of that spell

It's about the duration.

3 points is 18 seconds, while I have on my buff list 24 seconds recuperate.
it won't let me use recuperate [in this case 3 points] if the duration is not less than 18 seconds.

I think this logic apply to other abilities as Rip, Rupture and other HoTs. (not sure about HoTs)

I am not sure about the List. It's from Twinstar, I assume its Catataclysm Blizzard mechanics.

**Comment by Sketish** [comment]
Then provide any retail source then we can change that

**Comment by whothatdog** [comment]
> Then provide any retail source then we can change that

comment by Denariant, implemented on Twinstar.
https://cata-twinhead.twinstar.cz/?issue=11180#comments

he link this -> http://eu.battle.net/wow/en/forum/topic/2499170459
but I cannot open it.

I won't look for Cata movies in youtube and look in 10-20 min videos for the 'right frame' when it show in the warnings.
perhaps @Kenniflopper can help or someone else...

**Comment by Sketish** [comment]
If it only was working for one spell then it doesnt make sense. Looks like just apollo thing

**Comment by whothatdog** [comment]
> If it only was working for one spell then it doesnt make sense. Looks like just apollo thing

Possible, but hard to believe they'll do such a thing.
I would like you to keep it open and maybe someone else with better knowledge will answer that.

**Comment by xmrshoot** [comment]
#3180

**Comment by UltraNix** [comment]
Fixed.
