### ISSUE TITLE
Absorbs / shields in dampening

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4390]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently absorbs /shields arent affected by dampening. which they should.

**How to reproduce:**
go into arena and try shield urself with power word shield during dampening and see its the same

**How it should work:**
Absorbs / shields should be affected by dampening

**Database links:**
https://ibb.co/TBVDFBx

**Comment by Artemhx** [comment]
Power word shield doesn't absorb after dampening starts
It says 23k, but you getting damage through absorb, and you getting damage with reduction. For example if there -40% dampening you will getting damage with 40% reduction while absorb is active

For example on this screenshot priest getting damage through absorb but while absorb is active on him he is getting 40% less damage
![image](https://github.com/gamefreedomgit/Maelstrom/assets/65182190/d61661fc-a833-44cc-96ec-b93b1341d3e2)
That how it works on whitemane on dampening with any absorb
