### ISSUE TITLE
Problem with quest-item 475 for Jewelcrafting

### ISSUE THREAD

**Issue by Draky123456789** [gamefreedomgit/Maelstrom#4392]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bug : We can drop some items for Jewelcrafting in dungeon (level Jewel 475)
Start a quest with them
Bug we CAN'T finish the quest when we have items on us :/ The quest button "you can finish, click here" appear, but nothing happen when we click on "continue" on the quest page

**How to reproduce:**
take an item 475 jewelcrafting in dungeon, take somes minerals you can found on the list from the quest, and try to finish the quest when the pop-up "(?) finish the quest" appear on your screen

**How it should work:**
Its should finish the quest if we have all items and give some rewards

**Database links:**
https://www.wowhead.com/quest=28775/broken-serpent-figurine for exemple (there is other items like this one)

**Comment by Erainor** [comment]
Same bug to report on Jewelcrafting.  All quests unfinishable.

**Comment by UltraNix** [comment]
Fixed.
