### ISSUE TITLE
Mission Twilight HighLands id28591

### ISSUE THREAD

**Issue by Tiohany** [gamefreedomgit/Maelstrom#4394]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mission "OFF THE WALL"
**How to reproduce:**

WOWhead ( (C_QuestLog.IsQuest28591))
**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
