### ISSUE TITLE
Lord Rhyolith - P2 Transition Debuff Removal

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4398]
**Description:**
On the transition from P1 to P2 at 25% health, any remaining Eruption debuff from the volcanoes in P1 should be removed from the remaining raid members.

**How to reproduce:**
Transition into P2 with Eruption debuffs still active on raid members.

**How it should work:**
Upon Lord Rhyolith reaching 25% health and transitioning into P2, the Eruption debuffs should be removed.

**Database links:**
https://www.youtube.com/watch?v=ByqaiEBnIws&t=10s&ab_channel=Mechatorium - 4:48 - Retail video of the Eruption debuffs being removed upon transition.

<img width="1433" alt="eruption debuff remaining on transition image" src="https://github.com/gamefreedomgit/Maelstrom/assets/42842394/081fa336-2ea3-4703-afae-852f738a33d7">

**Comment by Sketish** [comment]
On pre nerf version debuff stays after transitioning boss to p2. Not a bug
