### ISSUE TITLE
aiming high quest 

### ISSUE THREAD

**Issue by dagryne** [gamefreedomgit/Maelstrom#4400]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the aiming high quest that launches you into a cannon on to a zeplin doesnt work. it launches too early so you miss the zeplin entirely

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Did you test it on PTR?? If yes wait for PTR restart. Applied possible fix. Come back here with feedback later ;)
