### ISSUE TITLE
Warlock pet(Fel hunter) spell lock bug

### ISSUE THREAD

**Issue by Artemhx** [gamefreedomgit/Maelstrom#4401]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock pet(Fel hunter) can spell lock beeing in fear

**How to reproduce:**
https://www.youtube.com/watch?v=H7-UN7zJPjg&ab_channel=%D0%A1%D0%BB%D0%B0%D0%B2%D0%B0%D0%97%D0%B0%D1%85%D0%B0%D1%80%D0%BE%D0%B2

**How it should work:**
Fel hunter should not be able spell lock in fear

**Database links:**

**Comment by whothatdog** [comment]
funny bug, it reminds me the report I made about pets (hunter/warlock)
https://github.com/gamefreedomgit/Maelstrom/issues/4362

somehow 'forced' to run at my speed of 140% while pet should run at normal speed
I couldn't kite the pet and get it off me like 3/4 of the bg map completly ignoring any game 'behaviors' ;-)

**Comment by UltraNix** [comment]
@Artemhx Are you able to reproduce it once again?

**Comment by Artemhx** [comment]
> @Artemhx Are you able to reproduce it once again?

Im able, but not now
Not at home actually
Will be home at evening
