### ISSUE TITLE
Cheat death

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4404]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ignite ignores its damage reduction mechanic completely (as u can see in videos that it ticks 6.3k or more through cheat death)

**How to reproduce:**
Ignite completely ignoring the cheat death damage reduction -> https://streamable.com/pyy9ev
again  you can see ignite ignores cheat death dmg reduction -> https://streamable.com/5zkxvu

**How it should work:**
whenever it procs  it should reduce all incoming damage by 80% during the duration, also dots that was appplied before cheat death procced should be reduced by 80% when the buff is up.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=31230

**Comment by Kenniflopper** [comment]
Could be more than just ignite ignoring this mechanic completely, didnt do further testing regarding that.

**Comment by UltraNix** [comment]
Show us proof from retail. Ignite has special attribute that ignores all modifiers.

**Comment by UltraNix** [comment]
Fixed.
