### ISSUE TITLE
Flame-Scarred Junkbox from NPC + Pickpocket put you in combat

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4406]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pickpocketing few NPCs according to Twinstar database
that suppost to drop 'Flame-Scarred Junkbox' the NPCs just does not have anything pickpocket from them
just copper and silver coins.

**How to reproduce:**
pickpocket NPCs - Cata zone maps, Dungeons etc.

**How it should work:**
When pickpocket NPCs according to the list, rogue should able to loot 'Flame-Scarred Junkbox'
According to Twinstar the Junkbox contain 15 items with different % rate drop.
**2 daggers and thrown item level 359.** which I don't know what the rate is 0.5% or 1% or higher.
Many rogues farm those boxes to get 359 daggers.

https://cata-twinhead.twinstar.cz/?item=68161
https://cata-twinhead.twinstar.cz/?item=68162
https://cata-twinhead.twinstar.cz/?item=68163

**Database links:**
https://cata-twinhead.twinstar.cz/?item=63349#pick-pocketed-from
https://www.wowhead.com/item=63349/flame-scarred-junkbox

**Comment by UltraNix** [comment]
Pickpocket - fixed.
Flame-Scarred Junkbox - #2372

**Comment by whothatdog** [comment]
@UltraNix not working, 
it keeps put you in combat when it should not, the behavior is very different from Twin**
I also use Glyph of Pick Pocket that increase 5 yard PP.

NPC(s) are still miss loot table from PP, the Box should have 22-23% drop according to Twin**
I tested few of them in Deepholm. 

btw, on Dragon Soul -> Rogues will have to Pick Pocket Hagara (Legendary Quest)
If PP put them on Combat it might be problematic.

**Comment by UltraNix** [comment]
@whothatdog Record a video about pickpocket.

**Comment by whothatdog** [comment]
> @whothatdog Record a video about pickpocket.
Sorry, I can't record a video ;-)

Here from Twin** PTR
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/13150f7f-42cf-46f2-ae08-f4a906eb3f38)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/8967d706-e6be-494b-83d1-1ab5bc066364)

most of the loot is crap:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/7ea13319-b508-4adb-b449-d89acc07e19d)


the drop rate is very low for the epic 359 items, imo since you increased the 359 epic items chance
make it approx drop from 500-600 boxes (0.2%~?) would be nice.

retail video:
https://www.youtube.com/watch?v=Grl54I0b1E4

**Comment by UltraNix** [comment]
No - I need a video from out server. 
It's been fixed and tested by me - worked okay.
I don't want anything from Twinstar.

**Comment by whothatdog** [comment]
> No - I need a video from out server. It's been fixed and tested by me - worked okay. I don't want anything from Twinstar.

the yt video is from retail 12 years ago.
