### ISSUE TITLE
2 insignia of victory trinket

### ISSUE THREAD

**Issue by sauterux** [gamefreedomgit/Maelstrom#4407]
Hello.
I see many streams af locks play 2 insignia of victory trinket, and the 2 trinkets instantly re proc in every 20 sec. 

First, those trinkets have 15 % proc chance, same effect never can proc together, and they have  45s internal CD which begins after the proc effect wears off. So thats why in whitemane afflocks like perma bursting. There is a chance to this issue will fixed? 

https://www.wowhead.com/item=73491/cataclysmic-gladiators-insignia-of-victory#comments

**Comment by Warlorc** [comment]
Internal CDs start when the buff proccs

**Comment by SimonBpvp** [comment]
Wait wait wait where does it say the ICD should start when the proc offect wears off??? You might be correct, I’ve just never heard of  that in my life. 

Also the 15% proc chance sounds too low. I’m sure it should be higher but I will look for proof

**Comment by Stega23** [comment]
I dont see a reason why two effects wouldnt stack, it isnt unique equipped.
For example, i know you can have 2 landslide proc at same time and have them both up (thats normal).

@SimonBpvp 
ICD should not start when proc wears off, ICD starts as soon as you get the buff, so if you get proc, soonest you can get it again is 55 after that( or 35 sec after it wears off)

**Comment by Warlorc** [comment]
> 

It isnt unique-equip on whitemane but blizzlike it is

**Comment by Stega23** [comment]
> > 
> 
> It isnt unique-equip on whitemane but blizzlike it is

It isnt supposed to be tho, that was probably changed later and not in cata

**Comment by Stega23** [comment]
> https://web.archive.org/web/20120121023157/https://www.wowhead.com/item=73491 Not unique-equipped. 15% chance. 45 icd - starts when buff applies.
> 
> ICD is not shared between trinkets - need some proof/confirmation if it is okay.

According to ExtraCd addon files, which was updated and had good data till 4.3, 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/94021456/d41da1f2-98ee-49b4-81b6-22fd3c8cacd2)

Icd should be 50

**Comment by UltraNix** [comment]
We'll stay with 45 icd (checked in some different databases).
