### ISSUE TITLE
Firelands

### ISSUE THREAD

**Issue by Warlorc** [gamefreedomgit/Maelstrom#4408]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sum up of bugs encountered in Firelands.

Beth:

- Broodlings shouldnt be able to get rooted.
- The meteor holes persist too long on top.
- Spinners dont fall instantly and keeping aggro on people who go on top.

Shannox:

- Rageface keeps casting rage on people randomly instead on only the guy who breaks his face rage. should swap targets constantly.
- Dogs also dont like to take traps, especially Rageface.

Baleroc:

- Shard sometimes goes above 25 stacks. 
- Shard people seem to get lower healing then when not soaking (not 100% sure).

Alysrazor:

- Rings should give a debuff and not a buff.
- When you land with Wings, you are unable to fly again even when the buff is still running.
- Worms seem to spin a little bit too quick.

Rhyolith:

- Direct hits and bigger hits should count more towards steering then small hits and aoe spells.

Majordomo:

- 2 or 3 Seeds are exploding at the same, should be only 1 after each other with a 5s difference.
- Orbs debuff should stack and not have 2 separate debuffs.
- Hunters cant attack boss when stacked.

Ragnaros:

- Wrath should only be cast on range when atleast 3 are out.
- Lava is too big, if you pop meta or anything that increases your size you get lava dmg on the platform.
- Molten elementals arent stunnable or kickable after being solo again.
- Traps somehow either pop isntantly or after 5s, i assume something with the range where the trap gets exploded is off.
- Smash sometimes appears underneath the map and cant be seen properly.
- Superheated on the deluge person still ticks as immune, should be not affected by it at all.
- Instant dmg of spells like shadow word pain, corruption, etc. should be able to knock meteor, but it isnt (havent watched apparations close enough if they also dont work)
- Blink, killing spree and any "teleporting" spells make you fall underneath map.

General:

- Range on every spell is way too big, especially world of flames or any sort of fire on the ground. Mentioning only Ragnaros but its on every other boss/raid/open world.

**How to reproduce:**

Pull boss, replicate the situation, see yourself.

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Please - one bug, one report.

**Comment by Sketish** [comment]
I moved most of the issues to seperate reports.

I need more details about:
Alysrazor:
When you land with Wings, you are unable to fly again even when the buff is still running.

Ragnaros
Lava is too big, if you pop meta or anything that increases your size you get lava dmg on the platform.
Smash sometimes appears underneath the map and cant be seen properly.

And provide any source for that
Wrath should only be cast on range when atleast 3 are out.

**Comment by Warlorc** [comment]
- On alys when i was rogue and was helping the lower geared tank after reaching 25 stacks on his add, i landed to attack the hatchling. While still having 10s left on the wings of flame buff i was only able to jump on the ground instead of flying back up to refresh stacks/wings buff. Maybe someone streamed and i can check the vid later.
- the lava issue i encountered when someone played demo on rag and after poping his meta he took damage even when far away from the lava, but that probably is due to every ground effect appears to be bigger and increasing your size makes your hitbox to appear also bigger
- for wrath i couldnt find a written proof, just remembering that melees on 25 man always stacked up while ranges where standing outside, so there must have been some sort of requirement that it never hitted melees. 
- will try to find a vod for smash too

**Comment by Warlorc** [comment]
https://clips.twitch.tv/ExuberantLachrymoseBatteryAMPEnergyCherry-FzIlh2EmYozD3Hy6

For the meta

**Comment by Warlorc** [comment]
![Screenshot_20230904_104652_tv twitch android app](https://github.com/gamefreedomgit/Maelstrom/assets/135524585/0da3af8e-c9e5-4c12-a6e9-bc197d635409)
Doesnt let me clip it rn but here you can see half smash not shown, sometimes its less or more, think some specific spots on the platform are creating this issue

**Comment by Sketish** [comment]
So moved most of the reports to seperate ones. Will close this topic for now. Thanks for quick reply
