### ISSUE TITLE
Drain Life bug.

### ISSUE THREAD

**Issue by Lightward005** [gamefreedomgit/Maelstrom#4409]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Drain Life doesn't benefit from life drain bonuses from Soul Siphon talent, it only increases its damage.

**How to reproduce:**
Don't have video proof but just cast Drain life on Dummy without any debuff on the target versus debuffs and the difference is just damage increase in Drain Life but no Healing output increase.

**How it should work:**
Drain Life should get the benefit of healing as well as damage from Soul Siphon talent.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=64159
https://cata-twinhead.twinstar.cz/?spell=17804

**Comment by Sketish** [comment]
It was reported already, on retail it was only increasing dmg done. Not a bug
