### ISSUE TITLE
faerie fire breaks sap

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4411]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
human form faerie fire is breaking sap at the moment

**How to reproduce:**
sap a target then have your friend faerie fire it

**How it should work:**
it shouldnt break sap cause it does 0 dmg?

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=770

**Comment by UltraNix** [comment]
@SimonBpvp I can't reproduce it. Can you record it?

**Comment by UltraNix** [comment]
No further info - closing.
