### ISSUE TITLE
Return to graveyard button

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4412]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
it lets you swap graveyards

**How to reproduce:**

if you click this button
https://gyazo.com/a14bc54f920345560a1e81eb0697c5a9
in rated bg gilneas or twin peaks (maybe others too) it will let you move to a different graveyard if you click it really fast. Like if you double click it you can change graveyard

**How it should work:**
you have to stay at the graveyard the game gives you, you can't select a different one with the return to gy button, it should only put you back to the same gy you started at

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
