### ISSUE TITLE
Beth'tilac - Cinderweb Spinner and Drone

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4415]
**Description:**
There is sometimes delay when you taunt Spinner and him moving down.He should fall instantly after recieving taunt.
Cinderweb Spinners and Drones also sometimes have aggro on player on upper layer which makes drones go evade

**How it should work:**
All adds shouldn't be able to get aggro on player on top of web

**Comment by UltraNix** [comment]
Fixed.
