### ISSUE TITLE
Baleroc - shard stacks

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4418]
**Description:**
On 10m, each shard summoned by Baleroc should give 24-25 stacks, currently sometimes this number go higher

**How to reproduce:**
Pull Baleroc and check Torment stack

**Database links:**
https://wowpedia.fandom.com/wiki/Baleroc

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3dc0b767-12b4-4968-be13-a698cf8a853c)
Also it's dealing double dmg at 1 cast (2,3 and 2,4)

**Comment by UltraNix** [comment]
Fixed.
