### ISSUE TITLE
Alysrazor - Blazing Power should be a debuff on player

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4419]
**Description:**
During ALysrazor encounter, Blazing Power and Alysra's Razor should be displayed as debuffs
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/c0e31695-9fa3-488d-a6f5-7fbc5824c90c)

**Database links:**
https://www.youtube.com/watch?v=1tX64eLakrs&t=184s&ab_channel=ZumzarWoW

**Comment by UltraNix** [comment]
Fixed.
