### ISSUE TITLE
Lord Rhyolith- Burning Feet

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4421]
**Description:**
When boss is moving straight he should aplly buff Burning Feet to himself which should increase movement speed by 50% before nerf and 100% post nerf

**How it should work:**
Buff should be on boss when he is between 20 and 30 on bar

**Database links:**
https://www.wowhead.com/spell=98837/burning-feet#changelog

**Comment by UltraNix** [comment]
Fixed.
