### ISSUE TITLE
Ragnaros HC - Molten Elementals

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4424]
**Description:**
Molten Elemental adds should be only immune to cc when are stacked with each other withing 6y. Currently they are always immune no matter of the range.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/030d88cd-bd01-4b99-a734-1b47085a9342)

**Comment by UltraNix** [comment]
Fixed.
