### ISSUE TITLE
Ragnaros -  Delay between triggering Magma Trap

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4425]
**Description:**
When player walks into Magma Trap sometimes its not reacting at all unless you reach very middle of animation and wait few seconds before it triggers

**How it should work:**
You should pop trap instantly when reaching middle

**Database links:**
https://youtu.be/oN5URn760Ag?t=131

**Comment by UltraNix** [comment]
Fixed.
