### ISSUE TITLE
Ragnaros HC- blinking after boss reach p4

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4427]
**Description:**
Blink, killing spree and any "teleporting" spells make you fall underneath map after boss reach p4

blink start point (scorched earth) - blink destination (scorched earth) = under texture
blink start point (scorched earth) - blink destination (solid ground) = under texture
blink start point (solid ground) - blink destination (scorched earth) = under texture
blink start point (solid ground) - blink destination (solid ground) = safe

**Comment by Waroxx-QA** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/120338315/fb1bff5d-435a-47a2-be68-6751b4ed4a0e

**Comment by Waroxx-QA** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/120338315/411515c2-9193-4e46-8053-369f651d2fb8

**Comment by itsemmastone** [comment]
Fixed.
