### ISSUE TITLE
Ragnaros - lava hitbox

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4429]
**Description:**
the lava issue i encountered when someone played demo on rag and after poping his meta he took damage even when far away from the lava, but that probably is due to every ground effect appears to be bigger and increasing your size makes your hitbox to appear also bigger

**Database links:**
https://clips.twitch.tv/ExuberantLachrymoseBatteryAMPEnergyCherry-FzIlh2EmYozD3Hy6

**Comment by UltraNix** [comment]
Fixed.
