### ISSUE TITLE
Alysrazor - Wing of Flame

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4431]
**Description:**
On alys when i was rogue and was helping the lower geared tank after reaching 25 stacks on his add, i landed to attack the hatchling. While still having 10s left on the wings of flame buff i was only able to jump on the ground instead of flying back up to refresh stacks/wings buff. 

**How it should work:**
Player should be able to fly during Wings of Flame buff

**Comment by UltraNix** [comment]
Fixed.
