### ISSUE TITLE
Alysrazor - Firestorm vs CoS

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You take damage from the firestorm with CoS up

**How to reproduce:**
CoS and don't hide behind the meteor

**How it should work:**
CoS should make you immune to Firestorm damage (feint should also work, but i didn't test it)

**Database links:**

**Comment by Warlorc** [comment]
You get a 1s immunity to firestorm with CoS right now

**Comment by Sketish** [comment]
@Polynomix  if you can find any retail video that it should work that way ( I watched about 15 + rogue pov and noone ever used it for firestorm) then we will change that

**Comment by Polynomix** [comment]
http://web.archive.org/web/20120606020823/http://elitistjerks.com/f78/t123899-cataclysm_4_2_x_raid_mechanics/

"Feint and Cloak of Shadows both work against Firestorm"

Also they usually precise when a spell can only be cloak immuned during the 1st second which is not the case for this.

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/0a64cf6e-1d5f-4951-b82b-b9b2558f7e89)
http://web.archive.org/web/20120808075718/http://elitistjerks.com/f78/t123899-cataclysm_4_2_x_raid_mechanics/p5/

**Comment by Sketish** [comment]
Not a bug
