### ISSUE TITLE
Shaman Chain Lightning (and elesham mastery chain lightning cloned spell) LoS Problem

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4434]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you cast chain lightning on your initial target that is not obstructed by LoS, but next to your initial target there are possible jump targets obstructed by LoS, the chain lightning will not jump to those extra targets it could jump to because they are LoSing the player.

Important note: this bug is present in the mastery of elemental shaman as well. the spell cloned by mastery also behaves this way and will need to be fixed in addition to normal chain lightning.

**How to reproduce:**
First image you can see how chain lightning could jump to 2 more chickens but it doesnt since my character has a panel in between them causing LoS
https://imgur.com/a/hduO9j8

Second image chain lightning hits both chickens because I moved outside LoS
https://imgur.com/a/kYsxh0t

Also easier to see in the target dummy zone as there are multiple dummies and LoS objects around.

**How it should work:**
Chain lightning should only care about LoS on your initial target you click on. The actual jumps of the chain lightning should not care about your character position in relation to enemies it jumps on.

**Database links:**

**Comment by BalanCV** [comment]
Since common sense isn't enough, here's a retail video that you made me waste 1 hour of my life trying to find since I'm clearly part of the whitemane staff instead of you.
https://youtu.be/J8xRBHnOq4o?si=IkkzHp6x1XCBwAVj&t=310
At around 5:14 he casts chain lightning on initial target(not in LoS) and it extends to target2 (standing behind base wall in clear LoS of the caster). 
This is because CL is a smart cast, every other connexion in the chain is handled by the server and has no relation to the caster. Instead LoS should be calculated between enemy targets on every chain. (ex in the video: if there was a wall between enemy1 and enemy 2, even if caster had sight of enemy 2 the chain wouldn't jump and that would be correct.)

To simplify, first chain lightning target should use caster-target LoS, every chain jump should use previous target - next target LoS.

@Sketish please remove need info and put proper tags.

**Comment by UltraNix** [comment]
Fixed.
