### ISSUE TITLE
Charge (Warrior/Feral)

### ISSUE THREAD

**Issue by VirtualReign** [gamefreedomgit/Maelstrom#4438]
Currently charging a stationary enemy lands the warrior/feral so far inside the enemy's hitbox that their abilities are not immediately usable, they should probably land a bit earlier to facilitate them being able to use their melee attacks immediately.

**Comment by Qidpuncher-outland** [comment]
+++ you land behind the target with warrior charge aswell, its really awkward

**Comment by UltraNix** [comment]
@VirtualReign @Qidpuncher-outland Mobs or players? Can you give us some screenshots of this?

**Comment by Qidpuncher-outland** [comment]
> @VirtualReign @Qidpuncher-outland Mobs or players? Can you give us some screenshots of this?

I have no idea about PvE but playing arenas this seems to happen at least half the times that after your charge u end up behind the target. I can try and record some tonight

**Comment by UltraNix** [comment]
Yep - please record it.

**Comment by VirtualReign** [comment]
@UltraNix

It tends to happen pretty often, though it's not like I can give a definitive list.

I remember the Initiate adds on Alysrazor as offenders since I did that recently. Cat form charge lands you right in their hitbox and skills are unusable / auto-tattacking is prevented until you move a step back.

On a side note, you can also check feral skill Maim on those mobs, it seems to have a shorter range than the rest of the melee skills. You can be stationary and build your combo points on the mobs fine, but you will be out of range of Maim somehow.

**Comment by UltraNix** [comment]
@Qidpuncher-outland Still waiting for that warrior charge video - as for me it looks pretty okay against pvp targets.
Druid feral charge will be fixed.

**Comment by UltraNix** [comment]
Fixed.
