### ISSUE TITLE
Quest: Aiming High (alliance)

### ISSUE THREAD

**Issue by mrmoopie** [gamefreedomgit/Maelstrom#4439]
The quest is needed to continue questing in twilight highlands, you get send by a cannon towards a skyship yet you arrive to early and when you're using the explosive it keeps saying requires skyshredder belly, this quest is mandatory to continue, please fix this.

**Comment by Sketish** [comment]
You must be at specific spot to plant bomb

**Comment by Waroxx-QA** [comment]
Duplicate #4400
