### ISSUE TITLE
Shaman Chain heal jump affected by LoS

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4441]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Same issue as [Maelstrom#4434](https://github.com/gamefreedomgit/Maelstrom/issues/4434) but on chain heal instead of chain lightning.
If targets next to ur heal target are in LoS the heal won't jump on them.

Seems like every mechanic like this is bugged in this way, but currently can't think of other similar spells.

**How to reproduce:**
Have 1 guy being healed not in LoS and 1 guy next to the first guy, but in LoS.

**How it should work:**
LoS should work like: initial healed target - caster, previous healed jump - next healed jump LoS

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
