### ISSUE TITLE
[Hunter] Camouflage + petattack

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4442]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You can currently sit in stealth while pet is atacking. 

**How to reproduce:**

**How it should work:**
Camouflage should break when pet attack command is issued or if the pet engages in general.

I alrdy linked proof here : https://github.com/gamefreedomgit/Maelstrom/issues/4315#issuecomment-1696958334

**Database links:**

**Comment by Afgann** [comment]
fixed
