### ISSUE TITLE
[Paladin][Spell] Inquisition - Seal of Justice damage is not increased

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4443]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The auto attack seal damage that is Holy damage is not being increased by 30% by activating Inquisition.

**How to reproduce:**
Activate Seal of Justice and hit dummy with auto attack
Gain holy power to activate Inquisition
Seal of Justice Holy damage stays the same

**How it should work:**
Holy damage of Seal of Justice should be increased by 30% during Inquisition

The same scenario works for Seal of Truth, just as a reference.

**Database links:**
[Seal of Justice](https://cata-twinhead.twinstar.cz/?spell=20164)
[Inquisition](https://cata-twinhead.twinstar.cz/?spell=84963)

**Comment by Sketish** [comment]
Can you provide any combat log or video ?

**Comment by djesic** [comment]
Normal auto attacks
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/3c17b0e0-5771-46cb-bb20-f822fe929870)

With Inquisition
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/cfd64000-f6a3-4459-b927-bacb9a86ad4d)

729 constantly

**Comment by Afgann** [comment]
fixed
