### ISSUE TITLE
[Paladin][Spell] Avenging Wrath - Seal of Justice damage not increasing

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4444]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Avenging wrath is not increasing the seal damage done by Seal of Justice by 20% while it is active

**How to reproduce:**
Activate Seal of Justice and start attacking dummy
Activate Avenging Wrath

Note that white damage goes up by 20%, seal damage does not.

**How it should work:**
Seal of Justice damage should go up by 20% while Avenging Wrath is up
Tooltip states "all damage"

**Database links:**
[Avenging Wrath](https://cata-twinhead.twinstar.cz/?spell=31884)
[Seal of Justice](https://cata-twinhead.twinstar.cz/?spell=20164)

**Comment by Sketish** [comment]
Can you provide any combat log or video ?

**Comment by djesic** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/0a3682c0-2535-4b9b-8bee-9266b4e14277)
