### ISSUE TITLE
[Paladin][Talent] Guarded by the Light (2/2) - Shield does not take into account critical hits of Word of Glory

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4445]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Protection paladin talent (2/2) Guarded by the Light shield does not work on critical hits of Word of Glory

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/8421bd32-f82b-448a-b020-2bf8c427d5ad)

**How it should work:**
Should create an absorb equal to the overhealing

**Database links:**
[Guarded by the Light](https://cata-twinhead.twinstar.cz/?spell=85646)

**Comment by Afgann** [comment]
fixed
