### ISSUE TITLE
[Battlegrounds] Pet damage is not attributed to owner in the scoreboard

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4446]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Only player damage is in the scoreboard

I noticed after I left the BG, but I took a screenshot of REFlex 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/dd8e6292-4ce8-4766-885a-392c6d327f7a)

And here is my recount for that BG
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/ce0329f6-5a1d-4e9f-8ab7-56a2914c79db)

**Comment by Waroxx-QA** [comment]
If you select the option in Recount to show pets, it shows pets separately from you, but their contribution to your overall dps is still included in your dps value.

**Comment by djesic** [comment]
Ah, I deselected the "Merge owners with pets" in Recount and yeah, false alarm!
