### ISSUE TITLE
Bug at Quest: Decontamination

### ISSUE THREAD

**Issue by Majestik77z** [gamefreedomgit/Maelstrom#4447]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I was getting the quest "Decontamination" and when i was going to the NPC called Tehnician Braggle is just showing " continue " and i couldn't succeed the quest. I can't go forward playing without this quest i guess.

**How to reproduce:**
I tried to abandon the quest, retake it and it's the same problem. I even tried to login again on the game and it's still the same issue here. I don't know how to reproduce to others but at me it's definetly a bug. 

**How it should work:**
It should finish the quest after i'm going to that NPC Tehnician Braggle.

**Database links:**
https://imgur.com/a/CS0Ad6a

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/d24cb60b-fdfb-4edd-860d-81eba626acd9)

You didnt take that little copter to finish quest.

Works as should
