### ISSUE TITLE
Ready for Raiding II - Molten Front Achievement - Ancient Smoldering Behemoth

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4448]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

[Ancient Smoldering Behemoth](https://www.wowhead.com/npc=53771/ancient-smoldering-behemoth)：
[ Groundfire](https://www.wowhead.com/spell=99998/groundfire) - Run away from the boss. - I tried to leap away as a warrior, since the vortexes doesn't work, but it gave me no credit. (Tried many times)

**How to reproduce:**
Get the  Strike at the Heart daily quest.
Kill the elite without getting hit by its special attacks.

**How it should work:**

Once you killed it without getting hit by its special attacks, It should be seen on the achievement tab.
**Database links:**

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3684#issuecomment-1665903736
