### ISSUE TITLE
Fear pathing

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4449]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fear pathing is kinda weird right now, it can fear you over ledges and u will fall down once the fear effect is over.

**How to reproduce:**
https://clips.twitch.tv/VenomousDeterminedNuggetsDerp-dCMJVOPQIeu0i_ac

**How it should work:**
Fear effects should never make you run to a ledge and make you stay in the air and eventually making you fall down once the effect wears off.

**Database links:**

**Comment by Renehadox** [comment]
This happened in AB shitload of times to me, not gonna lie...

**Comment by Renehadox** [comment]
Wasn't this fixed before?

Author: afgann
Message: Core/Movement: Fix fear movement sometimes causing players to fall through floor. 

Just checked Discord.

**Comment by Afgann** [comment]
fixed
