### ISSUE TITLE
[PvP] Bestial Wrath vs Repentance

### ISSUE THREAD

**Issue by ussj10** [gamefreedomgit/Maelstrom#4450]
**Description:**
Bestial Wrath ability in BM tree normally removes all CC except for cyclone or disarm. This includes all stuns, fears, freezes, hexes and disorients such as sap, blind, scatter shot etc. However today a strange outlier appeared - ret's Repentance. 

**How to reproduce:**
Get Repentance'd by a paladin as a BM hunter. You will be unable to use Bestial Wrath at all.

**How it should work:**
Bestial Wrath is supposed to remove any type of CC from the owner that it can remove from their pet and be usable under those effects.

**Comment by Afgann** [comment]
fixed
