### ISSUE TITLE
quest prepping the soil

### ISSUE THREAD

**Issue by ginlok1** [gamefreedomgit/Maelstrom#4451]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the flamewards arnt spawning

**How to reproduce:**
look around were the quest takes place

**How it should work:**
there should be several flamewards around the area

**Database links:**
https://www.wowhead.com/quest=25502/prepping-the-soil

**Comment by UltraNix** [comment]
Fixed.
