### ISSUE TITLE
GUILD "Hands Of Fire" list of members buge

### ISSUE THREAD

**Issue by JozabadV** [gamefreedomgit/Maelstrom#4452]
Our guild 'Hands of Fire' is experiencing issues with the members list section, we cannot see any members on the list, and it appears that the roles are also broken."

![image](https://github.com/gamefreedomgit/Maelstrom/assets/55096903/9f55f586-91f9-4d9f-b82f-67f47123697d)

**Comment by UltraNix** [comment]
Fixed.
