### ISSUE TITLE
Quest: The Bear's Blessing

### ISSUE THREAD

**Issue by pinovo** [gamefreedomgit/Maelstrom#4454]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Bear's Blessing quest is not doable. There's need of tailfeather from Fleetfoot but he's friendly and can't attack him.

**How to reproduce:**
No reproducing...just a quest with wrong creep settings.

**How it should work:**
Creep should be killable.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=13544

**Comment by pinovo** [comment]
Now it's OK. But when I reported that, he was green to me, not yello, I was not able to attack him...

**Comment by pinovo** [comment]
I know, i was just pointing out that there's something wrong globaly. I can live with that. :) Thanks for your time.

**Comment by thedave88** [comment]
![WoWScrnShot_112723_221234](https://github.com/gamefreedomgit/Maelstrom/assets/152223565/ef0a2b6b-44b5-4568-9927-866c1bbd9379)

**Comment by thedave88** [comment]
![WoWScrnShot_112723_223908](https://github.com/gamefreedomgit/Maelstrom/assets/152223565/e0045c2a-c968-4ee8-a058-616a3d2aa9a1)
bugged for me as well on 27th of november 2023 at 22:40

**Comment by Inviktus611** [comment]
![WoWScrnShot_040724_234924](https://github.com/gamefreedomgit/Maelstrom/assets/166356544/2f652f6b-8b8d-4ee9-b0fc-1af1aed34578)

I've found this bug to still be present as of today.  Not sure if anyone figured out a work-around for this or if something we're doing is causing the mob to become friendly.

**Comment by PanJanuszek** [comment]
fixed 23.04.2024, server restart required
