### ISSUE TITLE
Trap launcher is buggy since last update

### ISSUE THREAD

**Issue by Mongo69** [gamefreedomgit/Maelstrom#4455]
**Description:**
When you use trap launcher your traps are no longer highlighted,so unless you check your buffs you dont know if your trap launcher buff is active,hella annoying

**How to reproduce:**
Use trap launcher,your freezing trap/frost trap should be highlighted for example

**How it should work:**
As you can see on on the video(01:23 or 03:30)your traps should be highlighted
https://youtu.be/b1jk5nxa2nU?si=i52OXXhi7XqZgN76&t=210

**Database links:**
https://wowpedia.fandom.com/wiki/Trap_Launcher

**Comment by UltraNix** [comment]
Fixed.
