### ISSUE TITLE
Baleroc 10hc spawns shards on tank after update

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4456]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As title says, I don't think its supposed to spawn on tank, we got it every pull. From retail vids I see it only spawning on 180 degree cone behind the boss in melee range.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=yrQNN_WZe2c&ab_channel=FatbossTV

**Database links:**

**Comment by itsemmastone** [comment]
Fixed.
