### ISSUE TITLE
Earth Shield doesn't work properly

### ISSUE THREAD

**Issue by avenue1234** [gamefreedomgit/Maelstrom#4458]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
earth shield is healing on every hit instead of every few seconds.

**How to reproduce:**

**How it should work:**
https://youtu.be/mg8DMsCdjYE?si=8NqC7vFEXAmA1NsW&t=755

Should just proc every few seconds from different attacks.
**Database links:**
https://cata-twinhead.twinstar.cz/?spell=974

**Comment by UltraNix** [comment]
Fixed.
