### ISSUE TITLE
Kill Command Bug

### ISSUE THREAD

**Issue by Rawrmand** [gamefreedomgit/Maelstrom#4459]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Killing Quest objective via Kill Command doesn't count
**How to reproduce:**
Use Kill Command take the last hit

**How it should work:**

Should've count when killed by Kill Command
**Database links:**
![Whitemane Bug](https://github.com/gamefreedomgit/Maelstrom/assets/144205252/2a5c05d4-3d05-46bc-b690-acbb5f32f486)

**Comment by UltraNix** [comment]
@Rawrmand Have you hit your victim? If only pet is doing damage, then you are not gonna receive the kill credit.

**Comment by Rawrmand** [comment]
> @Rawrmand Have you hit your victim? If only pet is doing damage, then you are not gonna receive the kill credit.

yes was hitting

**Comment by Rawrmand** [comment]
update prolly only working at gilneas area

**Comment by UltraNix** [comment]
Just tested and had no problems with getting kill credit using only Kill Command (of course, with at least on 1hit from my side)

**Comment by UltraNix** [comment]
No further info - closing.
