### ISSUE TITLE
Rogue legendary questline

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4460]
1.All quests objects are not visible on map
2..To catch a Thief - after you fail npc is reseting player twice( may occur lags crashes with more players)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3f04419e-7f62-45de-93d1-40ae842fbe75)
Mostarsz should send player insctruction through whispers
https://www.youtube.com/watch?v=TZOoEQ63Nv8&ab_channel=Kullax
Convenient rope should be glowing as clicklable object + cinematic when character is getting on top of roof is looking weird due to camera and character movement
https://youtu.be/TZOoEQ63Nv8?t=80
Fahrand is friendly to player
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/03588880-95cf-4ae2-a2df-940c6686334f)

3.Infernal model on Wrathion
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/46f85b9a-14c1-4fda-aa26-c8bc09caefad)

4.Our man in Gilneas - some phasing issue on retail video there are no mobs near gate
https://youtu.be/rc9Wkj6eMZU?t=2
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/0476f1dd-b957-4d5f-bc5f-22089147505c)

5.Assasinate Creed
Yellow mobs shouldnt be on that quest(85431 and 85483 ID's)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/4e89e77d-3755-4e69-b2a2-0bb0fa3a0e2f)
After failing and being dected combat is not dropped correctly
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3408bc81-c8bf-41f1-b1ba-15bff1260001)

Wasnt able to pass those guards, was always detected
https://youtu.be/tajyNHW04Q0?t=69

When player get to Lord Hiram Creed he is teleported to entrace- wrong reset there
https://www.youtube.com/watch?v=kwS3MHe5ogc&ab_channel=Smite 
Cant progress further

**Comment by Sketish** [comment]
28.09.2023

1.Lord Hilam Creed is melee swinging for 17-34 on retail he was hitting for about 8,5-9k(considering rogues have around 40% dmg reduction from armor basic hit should be for around 14-15k)
https://youtu.be/tajyNHW04Q0?t=255
2.I'm not able to complete q CLuster Clutch at Wrathion
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/798eed23-6c0f-4877-992c-821d84f70f7c)

Cant continue further questchain

**Comment by Sketish** [comment]
26.10.2023
1.Blood of the Betrayer
Blackwyrm mages are not despawning after being teleported to start ( failing sneaking)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e85b5318-7bbb-4770-b7af-4d38c33703ed)
Also mobs become bugged in Combat, cannot sap them anymore
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e40373ef-048e-4950-a74e-15038a0994bf)
Missing few patroling mobs theere
https://youtu.be/cnTkvgmSRTY?t=74
Player is not able to sabotage them ,making them explode aoe and kill mobs
https://www.wowhead.com/npc=58150/arcane-storage-unit#comments
Was always detected during this part
https://youtu.be/cnTkvgmSRTY?t=68
Again target is in combat
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/938ac94a-ada0-48d7-b590-a92cba385fe9)

Nalice

Arcane infused weapons is not working always, after reseting her it was working correctly
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/5b7057ca-b9d6-4766-8691-167c0c0eeadc)

Blazing shadow was only casted once and did 0 dmg to player + infernals  are visible + was no fire at the ground
https://youtu.be/XCznpE6Puhk?t=404

Final cinematic
Character is missing daggers equipped when killing dragon
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d57a3c39-8ccb-4b7d-8c7a-77a57e46793b)


Changes required
https://www.wowhead.com/item=74749/charging-decoder-ring reduce then time to 1h

[Elementium Gem Cluster] drop rates

 10m - 2 clusters 100%
 25m - 3-4 clusters
 Shadowy gem 5-10 roll from each cluster

**Comment by Sketish** [comment]
9.11.2023

1.NPC is missing quest mark above head
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/9331bfc8-d92a-4a88-af69-4811f7bbb0ab)

2.Changes required
https://www.wowhead.com/item=74749/charging-decoder-ring reduced time to 1h is not apllied
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d3db8de2-5043-4866-97ee-8e7595bd0817)

[Elementium Gem Cluster] drop rates

10m - 2 clusters 100%
25m - 3-4 clusters
Shadowy gem 5-10 roll from each cluster

3, To catch a thief
Mostrasz should sent tips to player how to procced with sneaking
https://youtu.be/TZOoEQ63Nv8?t=44

4.Wrathion is invisible during RP 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/79ac66e0-1628-4195-a630-d363a1751787)

5.Blood of the betrayer
Summoned constructs are not patrolling correctly
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/41f3de35-ab06-483e-91a7-61f9c37355cf)
https://youtu.be/cnTkvgmSRTY?t=180
Fires dont respawn after wipe
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/79d41d24-d91d-4078-803d-1989dea4cda9)
Blazing Shadows hit through Cloak of Shadow

6.FInale cinematic is not displayed correctly
Player is turned away from  Fahrad
Player is hitting air instead of dragon
https://youtu.be/2JnfUmUE00k?t=159

**Comment by Revly** [comment]
> Nalice
> 
> Arcane infused weapons is not working always, after reseting her it was working correctly ![image](https://private-user-images.githubusercontent.com/122209088/278311191-5b7057ca-b9d6-4766-8691-167c0c0eeadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTM4MTEsIm5iZiI6MTcwNTIxMzUxMSwicGF0aCI6Ii8xMjIyMDkwODgvMjc4MzExMTkxLTViNzA1N2NhLWI5ZDYtNDc2Ni04NjkxLTE2N2MwYzBlZWFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNjI1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTUwOWU1MmQ4YmMxMTYzNWUxZDg2MmIwZGIzNzRjZDFlMzA4NzE2YTE5MWNjMTllNjU2YjhkZjIwZDZiZTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bnHrz2UvWn60bxqMFMjcsXwy9QJ7LFs0L85P-Li0Ug)
> 
> Blazing shadow was only casted once and did 0 dmg to player + infernals are visible + was no fire at the ground

https://youtu.be/XCznpE6Puhk?t=404

"[Blazing shadow ](https://www.wowhead.com/spell=109988/blazing-shadows#comments) was only casted once and did 0 dmg to player + infernals are visible + was no fire at the ground "  This is Continuous bug, he doesn't even use it

In coments = **<a href="https://www.wowhead.com/es/quest=30109/la-sangre-de-la-traidora#english-comments " rel="nofollow"> Comemnts</a>**

"Click activated pillars. Avoid shizzles on the ground, plix." In a **<a href="https://youtu.be/SDZdwR8QGoU?t=203 " rel="nofollow"> Video</a>**  When you activate the pillars it gives you a buff that accumulates up to 2 times 2 pillars of course, this gives you damage, currently it is not giving damage. 

I couldn't find the buff but the clue I have is "Arcane Pillar" "object interactive think
They are minimal details but I think they do matter, to add difficulty
