### ISSUE TITLE
Freezing Trap DR Resets

### ISSUE THREAD

**Issue by lishpeth** [gamefreedomgit/Maelstrom#4461]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 

I watched a stream that belongs to a game played on Whitemane/ Maelstorm server last night and discovered that the freezing trap's dr got reset for some reason. You can see that Hunter (the streamer) uses his freezing trap at 27:15 in this video https://www.twitch.tv/kenniflopper/video/1917757403 and a couple of seconds later, he resets his cooldowns and retraps the same player. But the player is trapped for the entire duration instead of %50 reduced duration. The streamer himself discovered it so as well the watchers commented about it. The Cyclone might be the problem but it is not sure yet. 

**How to reproduce:
Cyclone or any other spells should not reset another spell's diminishing return time on a player. 

**How it should work:**

Player A is a Hunter and Player B is a Priest. Player A casts Freezing Trap on Player B. The duration of this first Freezing trap effect is 8 seconds. Immediately after this first freezing trap ends on Player B, the Hunter resets his cooldowns and recasts Freezing Trap. The duration of this second Freezing Trap effect is 4 seconds. Therefore, The Hunter will have to wait at least 15 seconds for the Freezing Trap ability to have its full 8-second duration on the Priest.

**Database links:**
https://www.wowhead.com/guide/diminishing-returns-in-pvp-6024

**Comment by Sketish** [comment]
There was a fix yesterdya apllied ot this, is this still hapenning ?

**Comment by UltraNix** [comment]
Should be okay now.
