### ISSUE TITLE
Felhunter shadowbite damage is ~18% lower than expected.

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#4462]
After upgrading several pieces of gear, i noticed my shadowbite damage is lower than it was some weeks ago. Based on the numbers discussed on the #4112 report, numbers are around 18% lower than expected. this turns into a ~4,5% lower damage for demonology. 

Here's all the relevant information from the testing:

**Talents, Gear, Buffs and pet stats**

I tested without external auras, consumables or debuffs on the target, only fel armor, and demonic pact when i was demonology.

This is my current gear and talents:

Affliction
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/f15bed47-51a5-4581-993f-a2a8d861891c)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/a06b1db2-ce74-4d22-a881-7e55db8ce375)

Demonology
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/59515a29-c2c2-4890-8756-5737dd452f4a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/b01f8e12-a28b-4e48-87cb-6ecdefabbdb3)

Damage test:

Affliction:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/49a5e19b-1b5e-45b8-b998-c0a452e49c5a)

Demonology:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/d5d39a1e-1f22-4da8-b6a1-c97e56b37698)

Expected damage:
Using the numbers found during the testing for #4112, this is what the damage formula looks like, using my current character stats:

**Affliction:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/5fbc5031-95f7-4c3f-8c61-cfafeece8bfa)

**Demonology**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/eb1a3e8c-f9d7-4ea5-88ac-c17998ac61a8)

Im not sure exactly what went wrong, but my pet is hitting for less than last month, 15 Item levels higher than i was at that time.

**Comment by jlldarocha** [comment]
More information on the base damage:
Using this retail video that showed the character stats - https://youtu.be/4TN_zE_T3tc - its possible to check the damage range of  shadow bite.

Spell power - 11317
Mastery - 16%, aka 36.8% felhunter damage

shadow bite damage instances without other procs:

**27212
54346**    Critical strike
**27325
27241
45847** Critical strike with only 2 dots active
**54397**   critical strike
**27254**

Damage formula:
(Felhunter SP *  1.228 + 308 ~ 344) * 1.15 (dark arts) * (1 + 0.3 for each dot on target) * 1.368 (mastery) * 1.08 (curse of elements)

**Minimum damage**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/28ca258e-9d33-43b0-b2a3-ee399744a639)

**Maximum damage**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/5b16391d-5d1d-4f20-a787-c930a0c2c97c)

**Comment by jlldarocha** [comment]
any news on this? not sure what needs confirmation, its a pretty clear comparison with the retail video i linked and the damage formulas used for the last time it was broken.

**Comment by Pornoodemon** [comment]
Perhaps this was fixed in the test but they forgot to fix it in the other realm

**Comment by UltraNix** [comment]
Here's my math (very similar to #4112)
Mastery: 16.37 (+37%)
Felhunter SP: 6701

![WoWScrnShot_091623_142759](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/086a4c1e-4bef-489f-b0f4-4393d24ba45b)
6701 * 1.228 (coeff) = 8228 + 120 (avg basic damage of shadow bite) ~8350
8350 * 1,37 (mastery) = 11439
11439 * 1,15 (dark arts) = 13154

With Curse of Elements:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/fd190bb2-2100-4537-8fcf-1b48e90648d5)
13154 * 1,08 = 14206

With Curse of Elements and dots (3 applications):
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9d2a0c05-e7b2-42e9-885c-c9ee29654ee8)

13154 * 1,08 * 1,9 ~27k
Nearly the same as [here](https://github.com/gamefreedomgit/Maelstrom/issues/4462#issuecomment-1710225800)

**Comment by Pornoodemon** [comment]
> Вот мои расчёты (очень похожи на #4112 ) Мастерство: 16,37 (+37%) SP Охотника Скверны: 6701
> 
> ![WoWScrnShot_091623_142759](https://user-images.githubusercontent.com/80540499/268447770-086a4c1e-4bef-489f-b0f4-4393d24ba45b.jpg) 6701 * 1,228 (коэфф) = 8228 + 120 (средний базовый урон от укуса тени) ~8350 8350 * 1,37 (мастерство) = 11439 11439 * 1,15 (темные искусства) = 13154
> 
> С Проклятием стихий: 13154 * 1,08 = 14206 ![изображение](https://user-images.githubusercontent.com/80540499/268447984-fd190bb2-2100-4537-8fcf-1b48e90648d5.png)
> 
> С Проклятием стихий и точек (3 применения): ![изображение](https://user-images.githubusercontent.com/80540499/268450403-9d2a0c05-e7b2-42e9-885c-c9ee29654ee8.png)
> 
> 13154 * 1,08 * 1,9 ~27к Примерно так же, как [здесь](https://github.com/gamefreedomgit/Maelstrom/issues/4462#issuecomment-1710225800)

Perhaps this was fixed on the test realm but not applied to the game realm?

**Comment by UltraNix** [comment]
The PTR core is the same as live at that matter.

**Comment by Pornoodemon** [comment]
> Ядро PTR в этом отношении такое же, как и вживую.

There is one moment when the SP for a warlock pet is not recalculated correctly. When you need to remove and reuse the Fel Armor so that the pet begins to take Sp. Perhaps because of this, the author made an error in the calculations.

**Comment by Pornoodemon** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/133828891/3a078520-0327-459b-8792-a963f9d431f1

**Comment by Pornoodemon** [comment]
SP recalculation is bugged after dismounting from a mount and perhaps in some other way. You need to remove and reapply the armor.
This is just to say that perhaps because of this the test was not done correctly.

**Comment by jlldarocha** [comment]
no, pet damage was actually lower few days ago,it seems the last restart that happened yesterday "fixed"it. 
The pet spellpower bug was also reported by me, theyre not related, i was watching the pets spellpower while testing for this. 

I will keep this open for a few more days, and wait for another restart to see if it will break again.

**Comment by jlldarocha** [comment]
After the weekly restart, his damage is lower again.

Expected damage: ~13860
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/59105d1d-9bb3-432d-b711-bb6ab611668b)
 

Actual damage: ~11670
![WoWScrnShot_092123_014947](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/71e6df56-9a58-4cd3-9f39-564cda092010)
![WoWScrnShot_092123_014951](https://github.com/gamefreedomgit/Maelstrom/assets/127895081/20372936-897c-4e72-8d6e-f1804cfad636)

https://www.youtube.com/watch?v=10HM-FgN76Y

**Comment by UltraNix** [comment]
Havse you just swapped pet or maybe summoned a new one (dismissing the previous one before)?

**Comment by Pornoodemon** [comment]
I haven't observed this before but it's really strange.
Have you noticed any patterns? Is there any connection with changing the set of items?
Or perhaps, when entering the game, the summoned pet does not accept some characteristics or buffs (try changing the set of items, releasing and resummoning the pet. I think that the algorithm for this breakdown is not in the damage formula itself, but in some recalculation of characteristics and buffs after log in and exit the game, possibly after some actions (based on the same principle as the bug with fel armor)

**Comment by jlldarocha** [comment]
> Havse you just swapped pet or maybe summoned a new one (dismissing the previous one before)?

No, i tried resummoning and relogging. It is happening after i do hcs on raid tho, might be saving the dampening debuff on the pet

**Comment by UltraNix** [comment]
But you did a test on dummy in Orgrimmar? So it's not a dampening.

**Comment by UltraNix** [comment]
Yep - it's dampening being saved to db.

**Comment by UltraNix** [comment]
Fixed.
