### ISSUE TITLE
Well of Eternity

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4466]
1.All demons should be immune to CC as example enslave demon is breaking script

Perth'tharn
1.Illidan is keeps apllying Shadowcloak to playes which is constanstly reseting boss

Azshara
1.After inerrupting once Total Obedience boss is not trying to cast this ability again

Mannoroth and Varo'then
1.Bosses should be immune to all forms of cc

**Comment by Sketish** [comment]
25.09.2023

1.Shado walk buff is not swapign to shadow ambusher during boss fight after eyes phase
https://www.wowhead.com/spell=103020/shadow-walk#see-also-other
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/f7f4bf3b-b225-4dd3-abe1-181df286a9c0)

**Comment by Sketish** [comment]
After forcing server restart during illidan stealth:
-there is no illidan after server restart
-players have pernament Shadowcloak buff and all mobs are evading
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/223732a0-6402-4304-b09f-9b3d4dd1af3a)
-need to add savepoints to prevent this interaction

**Comment by Sketish** [comment]
9.11.2023

Blessing of Elune is not adding dmg to players
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/509f540f-913b-4977-84e4-9e5a12a5422a)

**Comment by WhitemaneSylah** [comment]
@UltraNix  Reopen these,  dungeons are not functioning at all

**Comment by WhitemaneSylah** [comment]
Druid shape shift breaks the invisbility from Illidan,  Bears, Cats, Moonkins are affected and will not receive the stealth buff.

Peroth'arn - works fine

Queen Azshara - Servant of the queen works as intended,  Total Obedience if allowed to cast, players walk to Queen Azshara as intended - however - if all players reach Queen Azshara they should kneel then be instantly killed, this does not happen.  It soft locks the whole instance. GM intervention required.   Adds on fight work fine

Mannoroth & Varo'then - all fine no work needed
