### ISSUE TITLE
Hour of Twilight

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4467]
1.Thrall script is stuck at beginning, cant progress further on dungeon

Will update further after script update

**Comment by Sketish** [comment]
25.09.2023

1.Thrall is weirdly phased out and players arent able to continue dungeon.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/a31352b1-9eb0-4a5c-acac-6ed184d52638)
https://cdn.discordapp.com/attachments/368446147066462219/1155927844472492052/image.png


2.Boss is rooted in place during whole fight
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/68e890ea-86d5-4b0e-9c40-987e51e162c1)

3.Script is stucked there and players arent able to continue
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/093ef0bc-ca3e-46ea-a923-22f191093651)

**Comment by Sketish** [comment]
26.10.2023

1.Arcurion
Thrall is casting bloodlust on boss

2.Thrall is wrongly phased
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e351b692-cb9a-4e11-bb1b-4fc15c1c2cc8)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/df0ca266-f7e3-48a3-9e20-576585d0494a)
3.Asira Downslayer
Boss is still not moving and dont even attack player,looked liek she is stuck in some animation
4.Drake didnt despawn, player is stuck in the air
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/ad6e8117-a5d2-4457-ae34-7d1aff1477ea)
5.Cant go forward, NPC are doing nothing
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/c07ab111-1e58-46fb-9ebe-c38639935ffd)

**Comment by Sketish** [comment]
28.10

1.Minor - both thrall's are visible
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/6a265190-011b-4e90-8cf4-b182fb311231)
2.After server crash, the path is blocked.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/a03d6378-3303-43f6-aff6-ec2c48f1f53a)
3.Asira Downslayer
Boss is attackable during RP,
Thrall is not using any abilities, lava burst,rising fire totem
Blade barrier should last longer and lessser blade barrier is not apllied to boss at all
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/9ffea9ce-d986-4d19-a68d-2cbfdc69113b)
4.Mobs are not agrroing on thrall
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/738d82de-e300-43b6-8dfc-b4d360ed75d9)
5.Archbishop benedictus

1. If players dies to Wave of Virtune,Wave of Twilight boss is reseting
2.Corruptign twlight orbs are not spawning at all
3.Wave of twilight  always spawn in same position and players can run through this w/o taking dmg
4.Thrall  isnt using Cleanse Spirit ability
5.Achievement is counting wrongly number of Sparks
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/207f577d-040a-49e4-b504-9e9d8aaa65fc)
6.Due to crossfactions both portals should spawn after killing last boss

**Comment by Sketish** [comment]
6.11.2023

Arcurion
1.Thrall is casting lava burst on elementals bu its not killing them

2.Sometimes players are stuck in the air
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/6850de27-4529-4c80-9b28-42834fdf7786)

3.Faceless Brute
https://www.wowhead.com/spell=102861/squeeze-lifeless#used-by-npc
This cast should be intrerrupted after dealing dmg to add

4.Archbishop benedictus
Corrupting Twilight orbs are spawned but are not flying towards player location to leave zone under players
Portals aftger killing boss are not clickable

**Comment by Sketish** [comment]
9.11.2023
Archbishop benedictus
1. Only first wave of Corrupting Twilight spawned/hit players also then should only focus players - currently they are being casted on thrall

**Comment by WhitemaneSylah** [comment]
@UltraNix Reopen these.  Dungeons are unworkable/unplayable.

**Comment by WhitemaneSylah** [comment]
Thrall will be stuck in a loop from start of run,  First boss will not become attackable unless a GM .die's and .respawns boss

Asira Dawnslayer - No work needed, working

Pre-event for Archbishop Benedictus - Thrall stays at the top of the walkway and will not proceed without GM intervention. 

Archbishop Benedictus - Boss fight itself is fine

After Archbishop Benedictus - Thrall will be under the floor and cannot be talked to.  Gms need to pull him up to the correct XYZ.  Players CANNOT hand in the quests to thrall as this version of thrall has no handins.
