### ISSUE TITLE
ES is bugged?

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4469]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sorry for low quality report but ES is bugged according to my shaman friend, he said it can lose stacks too quickly and does no healing
he also says dots can proc it.

**How to reproduce:**
dont know 

**How it should work:**
it should proc not too often and heal for a decent amount?

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=974

**Comment by UltraNix** [comment]
Fixed.
