### ISSUE TITLE
Doors in nagrand arena

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4471]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://gyazo.com/713238a23507f1bbeb34bf5d1b7daf4b
these doors are visible the whole game

**How to reproduce:**
it happens every arena match i believe

**How it should work:**
they should despawn/become invisible pretty soon after they open

**Database links:**

**Comment by Sketish** [comment]
Please provide any source

**Comment by SimonBpvp** [comment]
> Please provide any source

https://www.youtube.com/watch?v=ppoR0FQLKd8
here the doors open and then disappear like 3 seconds later

**Comment by UltraNix** [comment]
Fixed.
