### ISSUE TITLE
spellsteal vs lifebloom

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4472]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if you spellsteal a lifebloom you purge all the stacks

**How to reproduce:**
duel a druid, get him to stack 3 lifeblooms, you spellsteal one and u get 1 stack and he loses all 3 (the other 2 just disappeared)

**How it should work:**
it should steal one stack at a time and heal the druid (or whoever the lifebloom is on) for some hp.

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=33763

**Comment by UltraNix** [comment]
Fixed.
