### ISSUE TITLE
water elemental AI

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4473]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the AI is wierd

**How to reproduce:**
https://gyazo.com/b60cc09222ad1cd2403d7e399ee81c52
https://gyazo.com/6eb50429f1c334dd4e59f6da4c439bd5
https://gyazo.com/d80af2782527bbd86b3ea97dc6aaf8c6

just playing a normal blade's edge arena and my water ele goes way down the ramp. On my life I swear I do not move him down there with pet move to. All i use is /petattack. He does this when his target moves out of LoS im 99% sure.

he does it on dalaran arena too.  On nagrand arena he runs really far too but always to try to get in LoS. But I don't want him to run so far. I think because his waterbolt is 45 yard range he decides he can run really far away to get in line of sight to cast it.

**How it should work:**
https://youtu.be/rtHkvwwHBZA?feature=shared&t=377
water ele should chase just like a normal melee pet if he is attacking

**Database links:**

**Comment by Pornoodemon** [comment]
There is the same problem with warlock pets.

**Comment by bonfax4** [comment]
Think pets try to run to backside as if they were normal melee pets, but they do it at max range instead. Issue relates to pets that do not melee at all like succubus and imp. I noticed this with succ few days back but it only happened if I sent her to attack while out of attack range.

**Comment by UltraNix** [comment]
Fixed.
