### ISSUE TITLE
[mage][druid] Spellsteal and lifebloom

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4474]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
after using spellsteal, the mage's lifebloom buff disappears if the druid uses lifebloom. "Lifebloom can only be cast on one target at a time" because of this, but this should not count when the effect was a spellsteal mage.

**How to reproduce:**
use speallsteal on on target with lifebloom and after it use lifebloom.

**How it should work:**
buff lifebloom should not be disappears from mage, if druid will use lifebloom again

**Database links:**
https://wowpedia.fandom.com/wiki/Spellsteal
https://wowpedia.fandom.com/wiki/Lifebloom

**Comment by Afgann** [comment]
fixed
