### ISSUE TITLE
Mage [talent] Frostfire Orb and Dragon's Breath

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the target affected by disorientation from the dragon's breath ability stops receiving damage from the frostfire orb

**How to reproduce:**
use frostfire orb and dragon breath

**How it should work:**
frostfire Orb should continue to deal damage (this damage is not considered direct)

**Database links:**
https://wowpedia.fandom.com/wiki/Frostfire_Orb
https://wowpedia.fandom.com/wiki/Dragon%27s_Breath

this bug similar as https://github.com/gamefreedomgit/Maelstrom/issues/3971

**Comment by whothatdog** [comment]
I spoke with Shadowlolz (Twinstar main dev) few years ago about that bug, when you use Flame orb or Frostfire orb and Dragon Breath player.

He told me the version they had in their cata server is inaccurate and Flame orb should break Dragon's breath.
Yes I am aware to Hansol video ;-)

**Comment by Sketish** [comment]
@mipanka  provide any video from retail which confirms that interaction

**Comment by whothatdog** [comment]
> @mipanka provide any video from retail which confirms that interaction

he will provide **Hansol** video like he provided for Flame Orb on 3971 issue.
according to what I understood from Shadowlolz the Orb consider direct-hit in Cata, re-designed in MoP (also changed the animation)

The Flame/Frostfire Orb in Cata are not detecting stealth players (get them out of it)
and also from what I undestand break Dragon's Breath or stop attack target under that effect.

About Hansol video,
except that video which probably was just a bug period time it recorded
I don't think it will exist, I did not found.

Shadowlolz:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/b3c86bb9-b101-48fb-847f-4f25ff881c3e)

**Comment by mipanka** [comment]
> 

I did give proof here https://github.com/gamefreedomgit/Maelstrom/issues/3971

**Comment by UltraNix** [comment]
@mipanka Just tested and works okay to me - Frostfire Orb targets victims with Dragon's Breath.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/66e155c8-c6a2-4a43-bc5b-18ababfac12e)
Rogalec already being hit by Frostfire Orb --> Dragon's Breath --> DR removed by Frostfire Orb

**Comment by whothatdog** [comment]
> ![image](https://user-images.githubusercontent.com/80540499/271583816-66e155c8-c6a2-4a43-bc5b-18ababfac12e.png) Rogalec already being hit by Frostfire Orb --> Dragon's Breath --> DR removed by Frostfire Orb

I am sorry to say, but there no single video except Hansol's one that Flame/Frostfire orbs work that way.

There are few videos of Frost+Fire comp 2v2 and I watched them to see if the fire mage use dragon's breath
like 'yolo' when Orbs are there, I couldn't see it.

read my comments here~

**Comment by UltraNix** [comment]
No further info - closing.
Stealth detection already fixed.
