### ISSUE TITLE
[rogue][mage] sap and spellsteal

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4476]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description:
spellsteal break sap from target

How to reproduce:
use spellsteal on target under sap effect (mb should be some buff for steal)

How it should work:
spellsteal never should break sap and similar effect

Database links:
https://wowpedia.fandom.com/wiki/Sap
https://wowpedia.fandom.com/wiki/Spellsteal

https://github.com/gamefreedomgit/Maelstrom/issues/4091 I did make a report before its copy. Bug is not fixen.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/52995331-f59b-4a26-93a9-0cf12d6b1281)
Works okay.
