### ISSUE TITLE
Holy Priest - Serendipity.

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When Holy Priest is using Binding Heal it should give x1 stack of Serendipity.
I noticed it does give instantly x2 stacks - it should not.

**How to reproduce:**
~

**How it should work:**
I noticed it does give instantly x2 stacks - it should not.

**Database links:**
0:58, Priest casting Binding Heal → x1 Serenpidity.
https://www.youtube.com/watch?v=OCjBs5IRcvU

0:58, Priest casting Binding Heal → x1 Serenpidity.
https://www.youtube.com/watch?v=opaEMctJeII

**Comment by Afgann** [comment]
fixed
