### ISSUE TITLE
¿Mission bug?

### ISSUE THREAD

**Issue by Criistis** [gamefreedomgit/Maelstrom#4479]
https://www.wowhead.com/quest=29193/on-a-wing-and-a-prayer

**Description:**
After delivering the 25 embers and 3 sands of time from the previous quest to ''on a wing and a prayer'' the ''anachronistic'' npc should have given me an item called ''timeless eye'' which is essential for Continue with the legendary weapon. This npc did not give me said article and now I am stuck in this mission ''on a wing and a prayer''

**Database links:**
https://www.wowhead.com/item=69238/timeless-eye

**Comment by Sketish** [comment]
Abandon and retake quest. May you were in raid group and that's what may caused this issue

**Comment by Criistis** [comment]
I was not in a raid group, I was doing the mission after having finished my raid with the brotherhood

**Comment by Waroxx-QA** [comment]
Maybe your inventory was full.
Did you try abandonning/retaking the quest and it doesn't work ?

**Comment by UltraNix** [comment]
@Criistis Still happens?

**Comment by UltraNix** [comment]
No further info - closing.
