### ISSUE TITLE
Problem with quest Obtain the Banner of Koroth in Koroth's Lair.

### ISSUE THREAD

**Issue by ChaosRing2830** [gamefreedomgit/Maelstrom#4480]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The banner they tell you to take is impossible to take since the Koroth monster has moved from place to place. He should be a little further away to give the player time to run away from him since it is impossible to kill him at level 15

**Comment by UltraNix** [comment]
Fixed.
