### ISSUE TITLE
Deepholm quest bug 

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Maelstrom#4481]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the quest name "the world pillar fragment" , when Abyssion lands and gets trapped , as a hunter , i couldn't attack no matter how far i get , it's always saying "target too close" , my pet was attacking even from being next to me far away . i was only able to kill it with normal attacks with my melee weapon, pet attacks and traps . 
i've attached 2 screenshots from the place and how it looked while i was doing the quest

**How to reproduce:**
just accept the quest , go lay the quest item there and wait until the dragon arrives .

**How it should work:**
it shouldn't say target is too close , it's considering the target hitbox massive , hitbox should be as the target's size is 

**Database links:**
https://i.imgur.com/YwFL1pS.jpg

https://i.imgur.com/XaNlYKE.jpg

**Comment by UltraNix** [comment]
Fixed.
