### ISSUE TITLE
Perma disconnect in raid groups until kicked

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4483]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon relogging inside a raid, when you try to log back in you instantly disconnect after loading screen until you are kicked from the raid group.

This bug only seems to happen to some people. For example, Until recently I never experienced this bug even though I've heard of it from a few of my group mates suffering from it. Now it happens to me 80% of times I relog in a raid instance and I can't get rid of it.

Hard to tell what this bug is but its not likely a client side one since I have played both without addons and with a fresh client install in a different directory and this still happens.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@BalanCV Specific raid? Maybe your raid started combat with something or they've changed difficulty without you?

**Comment by UltraNix** [comment]
No further info - closing.
