### ISSUE TITLE
Hand of Freedom during Cyclone

### ISSUE THREAD

**Issue by EDP445SupporterAlsoTrump2024** [gamefreedomgit/Maelstrom#4487]
**Description:**
Paladin can use ability "Hand of Freedom" during cyclone. Cyclone immunes every effect in the game and should not be possible

**How to reproduce:**
Paladin gets cycloned and he uses hand of freedom on his ally or party group member

**How it should work:**
He should not be able to use hand of freedom

**Comment by mipanka** [comment]
on retail hpal had the opportunity use hand of freedom on in cyclone

**Comment by Sketish** [comment]
Please provide any source

**Comment by mipanka** [comment]
https://youtu.be/gEsD2_0SR3M?t=91
