### ISSUE TITLE
Players lose Darkmoon buffs upon entering Molten Core

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You shouldn't lose the buff upon entering MC...

![WoWScrnShot_090923_231803](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/3be697b0-1c63-4260-936e-a9853e29d24e)
![WoWScrnShot_090923_232335](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/91b78911-56aa-4552-bab5-b45f268a34f2)

Upon entering Molten Core buff is lost.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
It's is good, It has always been so.
Unless they make it custom?

**Comment by Renehadox** [comment]
> It's is good, It has always been so. Unless they make it custom?

Buffs should be lost upon entering any raid or molten core only?
