### ISSUE TITLE
Molten Core Bosses DO NOT DROP GOLD AT ALL ( just wasting time )

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4490]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I just did a molten core run and none of the bosses drop gold.

SS:

![WoWScrnShot_090923_232335](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/48f1b86c-bc5b-4e88-90d7-e9089e2956e0)

I wasted my time as i need some gold but bosses don't drop!
Fix pls

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after restart
