### ISSUE TITLE
Which GY to spawn at in gilneas

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4493]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the chosen GY location when you die is wrong I think cause you can spawn at the same GY you died at

**How to reproduce:**
Dying in battle of gilneas bg

**How it should work:**
https://youtu.be/CIIkgd7juWo?feature=shared&t=740
you should spawn at a different node from the one you die at. It was made like this to make it easier to attack waterworks basically.
in this video Geru dies at WW and respawns at mines

**Database links:**

**Comment by Hermeleen** [comment]
From what i've seen, you can press "return to graveyard" button and it will cycle all possible graveyards. Same was on apollo.

**Comment by SimonBpvp** [comment]
> From what i've seen, you can press "return to graveyard" button and it will cycle all possible graveyards. Same was on apollo.

they fixed that already here

**Comment by UltraNix** [comment]
Fixed.
