### ISSUE TITLE
DK death grip

### ISSUE THREAD

**Issue by BlacksheepXG** [gamefreedomgit/Maelstrom#4494]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
death grips effecting on mobs 100% moving only 2-3 yards,but normal in PVP

**How to reproduce:**

**How it should work:**
griping to my face lol

**Database links:**

**Comment by Sketish** [comment]
Invalid report
