### ISSUE TITLE
Left Molten Spewer position bug 25man

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4496]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Left molten spewer worm before ragnaros is bugged on 25man. Melees can't attack it, only ranged. Its real position is probably shifter a bit back.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
Fixed.
