### ISSUE TITLE
 [Ready for Raiding II]

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#4497]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) 
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?achievement=5873

**Description:**
Ancient charscale doesnt get count for achievment even without being hit by any of the special attacks.

**How to reproduce:**

**How it should work:**

https://www.youtube.com/watch?v=vmYGOjaoibg
**Database links:**

**Comment by Ruthysarsch** [comment]
It isn't only the Charscale, Ancient Smoldering Behemoth as well.

**Comment by UltraNix** [comment]
Fixed.
