### ISSUE TITLE
[Molten Front][Quest] A Bitter Pill

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Maelstrom#4500]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The bubbles that are used to spawn the Subterranean Magma Worm for the daily quest "A Bitter Pill" in the Molten Front are unable to be interacted with. There is no gear/hand icon when hovering over either of the two sparkling sets of bubbles.
![WoWScrnShot_091023_211210](https://github.com/gamefreedomgit/Maelstrom/assets/130517865/4426e0ee-7cce-4c9f-ba9a-b90f3498e459)

**How to reproduce:**

**How it should work:**
There should be a spot in the sparkling bubbles that allows you to interact with them and summon the mob for the daily.

**Database links:**
https://www.wowhead.com/quest=29263/a-bitter-pill#comments

**Comment by MrTide** [comment]
can confirm
basically object and the npc are different phase than players so they are unable to do the event
other than that event related to quest works fine

**Comment by 123daveee** [comment]
veo que tienes el baton de la cadena de misiones de Tierras de Fuego , tengo problema con la mision delegacion que no me salen los fragmentos que hay que cargarlos de Bthi -Alyz -Lord-Shanoxx , fue en un Raid de 25 ,tal ves es la modalidad o es que lo tengo bugg ? o en todas las modalidades es igual ????por favor ayduame
