### ISSUE TITLE
[Moved from Discord] Mage Blink 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#4501]
Forxet — Today at 5:10 AM
Hello,

I hope this message finds you well. I'm reaching out with a sincere request and would greatly appreciate it if you could take a moment to address the issue I'm currently facing. It pertains to a problem I'm encountering with the Blink ability, as demonstrated in the following video accessible through this link:  ( https://streamable.com/kz2nls )  ( https://streamable.com/tup3nh ) 

I wouldn't be seeking assistance if this issue were affecting me while playing other classes. Unfortunately, I can only play as a Fire Mage, a class I've been dedicated to for quite some time. The reason I'm bringing this to your attention is that this problem has significant repercussions for me as a Fire Mage player. Blink is a cornerstone of my abilities, and it's not functioning as it should.

This malfunction has led to a decrease in my arena rating and multiple deaths in world PvP situations, primarily because Blink doesn't transport me as expected and leaves me stranded in the same spot. I'd like to clarify that I'm not suggesting a nerf to Blink; rather, I believe there might have been unintended changes to its behavior in recent updates. For instance, I've encountered situations where Hunters set traps in my path, and I'm unable to Blink over them. This is just one example.

I don't want to delve into the broader issue of how Hunters are behaving, but I hope you can appreciate the difficulties I'm facing as a Fire Mage player due to this Blink problem.

Thank you for your time and consideration. Your assistance in resolving this matter would be greatly appreciated.

**Comment by MrTide** [comment]
Update from him:
Description:

Blink Ability Concerns:

There are several issues with the Blink ability that need addressing:

Charge Interruption: When warriors perform a charge, it applies a 0.5-second ministun effect. Ideally, I should be able to use Blink to escape this effect. However, currently, I am unable to do so. This gives warriors a significant advantage over mage players, as they can swiftly follow up with additional spells to disrupt my abilities.

Inconsistent Blink Range: The Blink ability's range appears to be inconsistent. It frequently teleports me only 1 meter, accounting for roughly 65% of my gameplay time, which is not consistent with its intended functionality.

Ineffectiveness Over Hunter Traps: Blink does not work effectively over hunter traps. There is a 0.5-second delay before the trap activates, theoretically allowing me to Blink away from the trap's location. Unfortunately, regardless of whether I attempt to jump while using Blink or not, I remain in the same spot. This situation significantly favors hunters, as I am unable to escape the trap's effects. Currently, my only option is to circumvent the trap by walking around it before being able to Blink forward. This lack of escape options makes it challenging for me, as a fire mage, to engage hunters effectively, ultimately resulting in rapid defeat due to the absence of defensive capabilities.

Water Ineffectiveness: Blink also fails to function properly in water. Regardless of whether I attempt to jump and Blink or stay in the water and Blink, I find myself inexplicably reappearing in the same spot. This issue further limits my mobility options and hinders my ability to navigate and engage effectively in aquatic environments.

Obstacle Challenges: Blink ability doesn't work over fences, stairs, or other areas where natural walking is not possible but jumping is required. Consequently, I cannot jump over these obstacles and then Blink to a new location. This limitation becomes problematic in fast-paced arena scenarios where time is limited, often leading to situations where I become stuck in place and are at a significant disadvantage, frequently resulting in my defeat.


How to reproduce:

To replicate this issue:

Simply follow the instructions outlined in the description above and test it out in-game. Please note that you may need to play the game for an extended period to observe these problems. It's important to mention that these issues may not be readily noticeable to regular players, so testing in this manner may not yield significant results.


How it should work:

The Blink ability should function as follows:

The Blink ability should not be influenced by player movement.
It should reliably teleport the caster 20 yards forward, unless obstructed by solid objects such as walls, mountains, doors, and unjumpable fences.
Additionally, using Blink should grant the caster immunity from stuns and bonds.
After using Blink, the caster's movement speed should be boosted by 60% for a duration of 2 seconds.



Links to the video 


Link 1 https://streamable.com/tup3nh 

Link 2 https://streamable.com/8imcrx

Link 3 https://streamable.com/ajoo5v 

Link 4 https://streamable.com/qf1kuq

Keep in mind that these links expire in two days. But I have evidence saved on my machine and I will try to record more. Thank

**Comment by Afgann** [comment]
fixed
