### ISSUE TITLE
The Mechanar elevator bug

### ISSUE THREAD

**Issue by yrblanco2019** [gamefreedomgit/Maelstrom#4503]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Elevator that leads to the second floor inside The Mechanar dungeon vanish from sight when a player approach to take it.

**How to reproduce:**
Wait from outside the elevator entrance, until it comes down, then approach to take it and once you get close it fades from sight, like entering on a different phase or something, preventing anyone to get to the second floor of the dungeon.

**How it should work:**
Elevator should function normally, comes up and down at regular intervals with 2-3 secs intervals.

**Database links:**

**Comment by UltraNix** [comment]
#2612
