### ISSUE TITLE
Ragnaros - Engulfing Flames

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4504]
**Description:**
On heroic Ragnaros is casting Word in Flames which is engulfing 1/3 of platform every 3 sec for 9 seconds totally. The closest one to boss has bigger hitbox than is visual and sometimes does twice dmg to player
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e31b4cd1-d25c-4d5c-bb22-0f222f6f0d69)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/b047afcc-dc1d-43e6-b163-c551bd74a5d6)
https://www.youtube.com/watch?v=XKKDkRtXNvE&ab_channel=Smite

**Comment by UltraNix** [comment]
Fixed.
