### ISSUE TITLE
Lock curses vs sap

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4507]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
lock curses break the sap when they don't do damage

**How to reproduce:**
put elements or weakness on a target that is sapped, it breaks the sap even though these things do no damage

**How it should work:**
nothing should break the sap unless it does damage

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
