### ISSUE TITLE
Can't use Tremor Totem when Seduced by a lock pet.

### ISSUE THREAD

**Issue by AJansson93** [gamefreedomgit/Maelstrom#4508]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As a shaman, you can't press tremor totem while seduced by a warlocks succubus. Says "Can't do that while stunned".

https://gyazo.com/6a10267504d9da37ddf236e39ee34e1e

**How to reproduce:**
Get seduced by a lock as a shaman. Try pressing Tremor totem.

**How it should work:**
Should be dispelled.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=8143

**Comment by UltraNix** [comment]
Fixed.
