### ISSUE TITLE
Rogue opening from stealth causing mobs to evade in deepholm

### ISSUE THREAD

**Issue by Priestelar** [gamefreedomgit/Maelstrom#4509]
**Description:**
So ive been questing through deepholm and i'm not really sure what it is that causes it, but i would usually open with garrote from stealth on my assassination rogue and then i continue to use my abilities but its asif the mobs will not participate in combat and constantly resets its hp. This has only been happening in deepholm and im not sure what it is that causes it, but its been occurring on several mobs on multiple occassions, I will continue to post screenshots as it occurs. I am also stuck in combat with them even if i use vanish.

**Comment by Priestelar** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/16594771/a1741a37-14b4-4f2a-8d1b-ba6547e0d866)

**Comment by Priestelar** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/16594771/a56b9df1-16eb-48ca-be01-a0066f991d0b)
I pickpocketed the mob and then used garrote to open and the same occurred

**Comment by Priestelar** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/16594771/708b354a-94c3-48e8-a314-65a8bef4c9d5)
Reproduced again by pickpocketing before using garrote

**Comment by Inox03** [comment]
Not just for Deepholme but Rogues opening from stealth in general. I'm level 57 and had this happen to mobs in the open world that are not in combat about 75% of the time. makes it more annoying to quest for sure

**Comment by UltraNix** [comment]
Fixed.
