### ISSUE TITLE
Ankh in rateds

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4510]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ankh in rated bg bugs your char

**How to reproduce:**
If you die as a shaman in a rated then it lets you click "Reincarnation" but if you click it then you can't respawn and you have to alt f4.

**How it should work:**
Don't know exactly. But however it should work you shouldnt have to alt f4 to be able to respawn

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=21169

**Comment by UltraNix** [comment]
Fixed.
