### ISSUE TITLE
[Achievement - Hyjal ] Bounce

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4511]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://www.wowhead.com/achievement=5483/bounce
**Description:**

Achievement in Hyjal - Bounce

**How to reproduce:**

Jump on trampoline - you never get 20 jumps u always get thrown off / Jump too far away and end up on the edge so you can never do 20x jumps

**How it should work:**

Jump on trampoline 

See pictures. This is not "Skill Issue". Just did it on Retail.

**Database links:**
![BounceRetail](https://github.com/gamefreedomgit/Maelstrom/assets/128425789/901e96e3-b62d-4555-8071-b08d4e7eb6ee)

![WoWScrnShot_091323_072829](https://github.com/gamefreedomgit/Maelstrom/assets/128425789/765f55f6-7944-4a9d-86f8-f1dc97c78357)

**Comment by Revly** [comment]
This work, try Jump with Mount Flying u can control where fall

**Comment by UltraNix** [comment]
Wowhead comments confirm above statement - you can try with different mechanic.
EDIT: Just tested and it's doable even without click to move/mounts etc.
