### ISSUE TITLE
After completing the Flame Heart task within the team, the NPC is unable to provide me with the last step of the task, the Orange Staff

### ISSUE THREAD

**Issue by oranggeeeee** [gamefreedomgit/Maelstrom#4513]
After completing the Flame Heart task, the Horegosa NPC did not give me the last step of the task, making it impossible for me to obtain my Orange Staff
https://cata-twinhead.twinstar.cz/?quest=29309

**Comment by MrTide** [comment]
I am assuming he abandoned it and could not take it anymore
https://cata-twinhead.twinstar.cz/?quest=29309
![image](https://github.com/gamefreedomgit/Maelstrom/assets/36106057/e3576009-c846-4fb3-9a0e-1f58063da088)

**Comment by oranggeeeee** [comment]
I only remember that after completing the Flame Heart mission at that time, there were blue dragons outside of Orgrimmar, but I did not receive the final task. Now I have a conversation with the Horegosa NPC, and she said that every blue dragon will remember my heroic deeds, giving me the feeling that it has been completed? But there is no orange staff on the body, currently only equipped with 391 magic staff

**Comment by UltraNix** [comment]
@oranggeeeee Tried abandoning quest and take it again?

**Comment by oranggeeeee** [comment]
@UltraNix  
![4c9a7376849cf681951bd790f44c5df](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/8ffb7aca-97f3-4fa8-bcc1-6bba36ad5260)
![2e20c296ed2ee0ef6202f9f8c6e4210](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/49677367-7ce9-4761-9672-29373d1b745d)

This is the pickup record and equipment map of my mission items. The mission items have already been picked up, and the Flame Heart mission has been handed over, but there is no last step of the Orange Staff mission

**Comment by UltraNix** [comment]
Horde?

**Comment by oranggeeeee** [comment]
> 部落?

yes

**Comment by oranggeeeee** [comment]
> 部落?
@UltraNix   ![33666-c3673e26e202818cf7396e125d772822](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/e193e94a-ceda-4bed-ada5-265f446f0a9f)
https://cata-twinhead.twinstar.cz/?quest=29309
 tide should have found in the in-game data that my last task was not completed

**Comment by oranggeeeee** [comment]
@UltraNix  So the problem now is that I handed in the Heart of Flame mission and couldn't receive the final 'The Stuff of Legends' mission

**Comment by BalanCV** [comment]
Had the same issue, next final quest also doesn't complete after the roleplay. You get stuck at 0/1 Witness Event on 'The stuff of Legends'

**Comment by UltraNix** [comment]
@BalanCV Horde or Alliance?

**Comment by oranggeeeee** [comment]
> 有同样的问题,下一次的最后任务也没有完成后的角色扮演。你在"传奇之物"的目击证人活动中陷入困境

Yes, I can't receive the task, and the NPC doesn't have any storyline dialogue

**Comment by BalanCV** [comment]
Horde

**Comment by UltraNix** [comment]
@oranggeeeee @BalanCV Your races and classes?

**Comment by BalanCV** [comment]
Orc Warlock

**Comment by oranggeeeee** [comment]
Blood Elf Shadow Priest

**Comment by oranggeeeee** [comment]
> Fixed. You may need to clear your cache while your game is not running in order to refresh it.

New issues arise
![863473-d53228e39700e1fad9714c4269c34b12](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/3fca55a5-eae9-44a1-99eb-2e0211a75ccc)
I have received the task, but in the end, I was unable to complete the ceremony of Dragon Soul, so I cannot complete the task

**Comment by oranggeeeee** [comment]
@itsemmastone @UltraNix   I tried many times but couldn't complete it

**Comment by oranggeeeee** [comment]
> Fixed. You may need to clear your cache while your game is not running in order to refresh it.

I attended the Orange Stick ceremony, but it showed that it was not completed

**Comment by BalanCV** [comment]
Yes this is the next bug I mentioned above. Event doesn't complete the quest.

**Comment by oranggeeeee** [comment]
> Fixed. You may need to clear your cache while your game is not running in order to refresh it.

A new problem has arisen The final task still cannot be completed
