### ISSUE TITLE
[Shaman] Spirit link totem vs cyclone

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4514]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Was [hotfixed](https://github.com/gamefreedomgit/Maelstrom/issues/1168) to not work during cyclone.

**How to reproduce:**

**How it should work:**
Cycloned target should count for health redistribution. It bypasses immunes in general (cho'gall transform , etc).

Proof : 
https://youtu.be/cAQLuo08mlM?t=168 Warlock Cycloned with full health and link still counted

https://www.mmo-champion.com/threads/894897-Totem-Spirit-Link-healing-reduction
"It ignores things like Cyclone... so I seriously doubt a little reduction would stand it its way =P"

https://cata-twinhead.twinstar.cz/?fixreport=show&id=10983
Spirit Link Totem will correctly redistribute health of players affected by Druid's Cyclone

**Database links:**

**Comment by Qidpuncher-outland** [comment]
yeah link should definitely work on cloned targets

**Comment by UltraNix** [comment]
Fixed.
