### ISSUE TITLE
The Stuff of Legends Unable to complete the ritual plot, resulting in the inability to complete the final task

### ISSUE THREAD

**Issue by oranggeeeee** [gamefreedomgit/Maelstrom#4515]
The current situation is that after watching the plot, the task cannot be completed
https://cata-twinhead.twinstar.cz/?quest=29309
![374322-79dc52d9c519b86af2e3e6f89c5b53dd](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/5f4bdbb7-0a9b-4a87-8a2e-5bcdf93929e4)

![500038-ee592e495cdb750b0750721021b03bac](https://github.com/gamefreedomgit/Maelstrom/assets/144905513/1bdefbb2-c95d-4d40-a095-fa6f286afd16)

**Comment by oranggeeeee** [comment]
After waking up, I came up and made a new one, inexplicably able to complete it again. I have already picked up the orange staff. Thank you

![Uploading IMG_20230914_092404.jpg…]()

**Comment by oranggeeeee** [comment]
After waking up, I came up and made a new one, inexplicably able to complete it again. I have already picked up the orange staff. Thank you
![Uploading IMG_20230914_092404.jpg…]()

**Comment by UltraNix** [comment]
Fixed.
