### ISSUE TITLE
[HUNTER] [GLYPH] minor glyph of lesser proportion (id 43350)

### ISSUE THREAD

**Issue by Hellsz** [gamefreedomgit/Maelstrom#4517]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: hunter minor glyph of lesser proportion (id 43350)

**How to reproduce:
pet size without glyph
![image](https://github.com/gamefreedomgit/Maelstrom/assets/55023320/3afd7e4c-a3fc-4b08-b474-1585f67a41ac)

pet size with glyph
![image](https://github.com/gamefreedomgit/Maelstrom/assets/55023320/4dab4d48-6e6c-47dd-bc6f-c23c944121c0)

**

**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/55023320/b8c7f138-8874-4f3f-8088-927d637f7c3f)

**Database links:**
https://www.wowhead.com/item=43350/glyph-of-lesser-proportion

**Comment by Afgann** [comment]
fixed
