### ISSUE TITLE
rageface issue

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** sometimes even if u do 30k+ hit on rageface he is still castinf face rage, i did 42k with aimed shot and he stil casting

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Polynomix** [comment]
was that in 25man ?

**Comment by Meyzie** [comment]
in 25man 45k are required.

**Comment by xmrshoot** [comment]
ye i know , even in 25 a mage did 52k and rageface still casting face rage , check pls

**Comment by Meyzie** [comment]
> ye i know , even in 25 a mage did 52k and rageface still casting face rage , check pls

If you don't provide proper details like filling out the form you get when opening a bug report you make it incredibly hard for devs to reproduce and confirm the bug...

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/86131330-4633-4fb7-b42a-76af4d7be247)

Dasd is afflicted by Face Rage, Magikus hits Rageface with 45k crit (10 man) and Face Rage is canceled. No bug here.

**Comment by xmrshoot** [comment]
ye but not always work, sometimes work , sometimes dont work , try several times please

**Comment by UltraNix** [comment]
I tried several times already. Give us more details or record the video.
