### ISSUE TITLE
Death Grip not working as it should.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4519]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I Death Grip mobs, they don't get yanked straight to me as they should, but are instead taunted and start moving towards me.
Seems to be working on players, but should also work on NPCs and mobs.

**How to reproduce:**
Try to Death Grip mobs that are far away, but within the Death Grip range of 30 yards.

**How it should work:**
Mobs should be instantly pulled to the death knight, instead of just running over as when taunted.

**Database links:**
https://cata.cavernoftime.com/spell=49560

Video showing it not working properly on mobs:
https://vimeo.com/864426298/cacb02ae7f

Video showing how it works on other players:
https://vimeo.com/864431856/3ae6ef02d7

**Comment by Afgann** [comment]
fixed
