### ISSUE TITLE
[Quest] Delegation "Dragonwrath questline"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#4520]
tormented protector keep casting Blazing Stomp without Smouldering Roots in firelands after wipes
so players are unable to do it they keep getting thrown off the platform
i have encountered a group today that had this issue they couldnt even get close to him.
he is even casting it when you are not engaged in combat and just ran back after a wipe.
he also goes over the terrain and makes it impossible to pull him back after wipe and keep casting Blazing Stomp (i am guessing reason for this is that he is trying to follow the players that ported back)
this is how it should work https://www.youtube.com/watch?v=7-9qLGr5nJo

**Comment by 123daveee** [comment]
a mi me paso  en la mision (Delegacion) no me salen los fragmentos en el suelo de Bethi-Alyz-Shanoxx y Lord, si pudieran ayudarme por favor , o algun mj para hablar con el , mi PJ es Pytch Brujo 85

**Comment by MrTide** [comment]
recent updates:
This happens after wipe looks like ppl start running away and npcs start following them through the train and such or it gets stuck on train and they summon another one
https://github.com/gamefreedomgit/Maelstrom/assets/36106057/437588a6-4cc8-4a78-bb8e-a89ab5b264ca
https://github.com/gamefreedomgit/Maelstrom/assets/36106057/3c1f1dcd-fb19-40eb-bd95-37392f97a922
https://github.com/gamefreedomgit/Maelstrom/assets/36106057/055df040-e131-455d-8db4-ee58fa557589

**Comment by Afgann** [comment]
fixed
