### ISSUE TITLE
250 essences and Rag HC (Rage of Ragnaros

### ISSUE THREAD

**Issue by Igria123456** [gamefreedomgit/Maelstrom#4521]
At the moment if a guy has completed his essencess and hast to loot Heart of Flame his Staff weapon is doing weird RP while in combat with Rag (see link below) the RP is doing a hellfire around you which knocks your group members away from you making Rag HC impossible. Some players said that shouldn't be the case.

Clip of the ''Hellfire'' knocking 3 people away including tank into lava:
https://clips.twitch.tv/MotionlessSplendidFennelGingerPower-pvN882cgbyyqUzOe

How to reproduce:
Pull Ragnaros on any difficulty when done collecting Essencess and needing only heart of flame.

How it should work:
The staff shouldn't be knocking players away (on heroic difficulty only).

Database links:
https://www.wowhead.com/spell=101108/rage-of-ragnaros#comments
Check comments for the hotfix.

**Comment by UltraNix** [comment]
Fixed.
