### ISSUE TITLE
Whitemane+ Weapon Enchants

### ISSUE THREAD

**Issue by Meyzie** [gamefreedomgit/Maelstrom#4522]
**Description:**
Some of the Whitemane+ Weapon enchants are obnoxiously blinding on some weapons/with certain enchants.

**How to reproduce:**
Use the Whitemane+ enchant "Dancing Rune Weapon" on literally any polearm. 

**How it should work:**
Not distract people ingame, especially in PVP and blind them with a simple enchant.

**Database links:**
https://i.gyazo.com/400df3c12f5f56b4a6ec1810907f62fa.mp4
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/136866541/279846d6-e8cc-423a-bbe1-ed2da3911acf)
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/136866541/c49e3ef2-3678-4b46-b6d0-29509b7e8bd2)
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/136866541/51fec80a-3b26-4337-b675-24867445dd25)

Another player:
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/136866541/0cea2350-d248-4850-a16a-d744f6ad0cbc)

**Comment by Afgann** [comment]
fixed
