### ISSUE TITLE
crystalizzed firestone should have 100% drop chance on 25 hc

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4523]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
