### ISSUE TITLE
Mision Delegacion De Tierras De Fuego

### ISSUE THREAD

**Issue by 123daveee** [gamefreedomgit/Maelstrom#4524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**En la mision me deberia dejar recojer 4 fragmentos para cargarlos en cada 1 de los boss Bethi -Shanoxx-Alyz-Lord Piroclasto , ninguno de los fragmentos  me salen en el suelo por favor ayuda , La mision es (Delagacion)

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
post in english omg

**Comment by UltraNix** [comment]
Tested ingame - seems to work okay.
