### ISSUE TITLE
Warlock pets spellpower weird interaction with fel armor.

### ISSUE THREAD

**Issue by jlldarocha** [gamefreedomgit/Maelstrom#4525]
Demonology Pets spellpower is sometimes calculated wrong after you summon them, With fel armor reducing their spellpower until you remove the buff and cast it again. 

This is something thats happening frequently during fights when you are pet twisting.

**Video example**
https://www.youtube.com/watch?v=4g3DrXAROwI

**How to reproduce:**
Spec demonology, use fel armor, summon pets and check their spellpower and damage.

**How it should work:**
Pet spellpower should scale with fel armor, as it does scale most of the time, and when it bugs it you cancel the aura and use it again.

**Comment by jlldarocha** [comment]
I was testing again, and it also happens without fel armor on the equation. 
Seems related to demonic pact, because its exactly 10% spellpower.

https://www.youtube.com/watch?v=7EJngnb66Vc

**Comment by UltraNix** [comment]
Fixed.
