### ISSUE TITLE
[rogue] Desecration and Cloak of Shadows

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4527]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
slow from talent death knight Desecration work on rogue with cloak of shadows

**How to reproduce:**
to use cloak of shadows in aoe slow talent

**How it should work:**
cloak of shadows should give immun for Desecration

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55667
https://wowpedia.fandom.com/wiki/Cloak_of_Shadows

**Comment by Sketish** [comment]
There is not such talent as defile

**Comment by bonfax4** [comment]
@Sketish He means [Desecration](https://cata-twinhead.twinstar.cz/?spell=55667) for sure if he mentions aoe slow. Lost in translation i guess.

**Comment by Afgann** [comment]
fixed
