### ISSUE TITLE
life grip(leap of faith)

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4528]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
it doesnt work reliably

**How to reproduce:**
try and grip someone who is running around or jumping, the spell works like 50% of the time it seems like

**How it should work:**
it should work beautifully every time like in Reckful 3
https://www.youtube.com/watch?v=0nBG50lDU70

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=73325

**Comment by Sketish** [comment]
Provide any recording when its not working on our server so we can check

**Comment by UltraNix** [comment]
Yep. As I can't reproduce it, we need a video of this bug.

**Comment by UltraNix** [comment]
No further info - closing.
