### ISSUE TITLE
[QUEST] -  Strike at the Heart

### ISSUE THREAD

**Issue by Nerrielpriest** [gamefreedomgit/Maelstrom#4530]
Strike at the Heart
https://www.wowhead.com/quest=29243/strike-at-the-heart#comments

**Description:**
Missing ancient starting fight. it is on the mountain inside the texture =) 

**How it should work:**
Should stand ancient  (Witherbranch <Ancient of War>)  starting fight

**Database links:**
Witherbranch <Ancient of War> 
https://www.wowhead.com/npc=53074/witherbranch

**Comment by Nerrielpriest** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/128686023/bda27e1c-795b-483e-8dc6-89fb8c5401f5)

**Comment by MrTide** [comment]
Npc devout harbringer that you are supposed to fight disappears in terrains so treant just moves up there since there is nothing to fight
