### ISSUE TITLE
GUARDIAN SPIRIT - '50% HP+ UPON REACHING DEATH 'PROC NOT WORKING

### ISSUE THREAD

**Issue by Cursedaway** [gamefreedomgit/Maelstrom#4531]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My issue started today. When I use Guardian Spirit the heal increase part (60% + to the target) works, but the 'when you die HP resets to 50%' doesn't.
So everytime I use when I'm about to die, my holy priest immediately goes into the Spirit of Redemption.
Also talked with another holy priest, experiencing the same issue.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I don't get it. Where does it say that should reset priest health to 50%?

**Comment by UltraNix** [comment]
Fixed.
