### ISSUE TITLE
Two Barber Shop Chairs inside each other

### ISSUE THREAD

**Issue by Meyzie** [gamefreedomgit/Maelstrom#4532]
**Description:**
In the Stormwind Barber shop, at the middle chair, there is two chairs inside each other, one being lower, one being more up.

**How to reproduce:**
Go to SW; Check out the barber shop, look at the middle chair.

**How it should work:**
There should only be one.

**Database links:**
![grafik](https://github.com/gamefreedomgit/Maelstrom/assets/136866541/f21724d0-7c7d-4fd2-a13d-d141597dfcc7)

**Comment by Meyzie** [comment]
> really? stop posting those very low priority bugs

Priority is irrelevant? Devs prioritise, regardless of how many reports there are. 

You go learn to fill out bug reports properly, then we can talk. I'm not saying the bugs I report are "URGENT HIGH PRIO" or anything. But they are bugs. So they are reported.

**Comment by Afgann** [comment]
fixed
