### ISSUE TITLE
Personaje Con error al entrar al mundo.

### ISSUE THREAD

**Issue by Mordelonmelo** [gamefreedomgit/Maelstrom#4534]
Buenas tardes, mi problema ocurrio ayer cuando intentaba sacar puntos de justicia con la mision diaria que esta en Dalaran.
Sin saber que la estancia estaba dañada me entre y de ahi me voto del servidor y por mas que intento entrar al mundo solo me sale error cuando presiono "entrar al mundo".
Porfavor liberen a mi PJ que es Paladin nivel 85 humano con el nombre de Megete.
Esta en mi ultima esperanza ya que tambien envie tickets de otras cuentas.

**Comment by Mordelonmelo** [comment]
Estare esperando respuesta gracias.

**Comment by Sketish** [comment]
Translate to english.
