### ISSUE TITLE
 [Fel Intelligence] warlock pet spell 

### ISSUE THREAD

**Issue by lisol23** [gamefreedomgit/Maelstrom#4536]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the warlock pet Felhunter is bugged casting  [Fel Intelligence] while not mounted over and over and over non stop 

**How to reproduce:**
make a warlock summon a fel hunter pet and turn on  [Fel Intelligence] and stand next to him he will cast it non stop

**How it should work:**
cast one time

**Database links:**

**Comment by UltraNix** [comment]
@lisol23 Can't reproduce it. Could you record video of this?

**Comment by UltraNix** [comment]
Fixed.
