### ISSUE TITLE
Warlock - Succubus pet

### ISSUE THREAD

**Issue by miki95** [gamefreedomgit/Maelstrom#4537]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # https://www.wowhead.com/spell=712/summon-succubus
[//]: # cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?spell=712

**Description:**

Succubus pet is bugged, she is perma casting Lesser Invisibility like she is in some kind of loop, and her attack range shouldn't be that long. Each time you summon her she has different name, that is also wrong, seduction get to 30 seconds when casted on death knight with anti-magic shell, and she stays that way, can't cancel it.

**How to reproduce:**

https://gemoo.com/tools/upload-video/share/561656665755758592?codeId=M03ooj5Kx0bzR&card=561656662014439424

https://gemoo.com/tools/upload-video/share/561656975530262528?codeId=vJ9pppJX6xVOj&card=561656971759583232

**How it should work:**

https://www.youtube.com/watch?v=CPrv7wG0jSQ&t=346s

https://www.youtube.com/watch?v=oLesqeRWcnY&t=84s

**Database links:**

**Comment by bonfax4** [comment]
https://www.wowhead.com/spell=7814/lash-of-pain#comments
> Even though it's a 20 yard range, the succubus prefers to get closer to the opponent and fight from a 15 yard range.

Attack range seems to be more of an AI issue, prob to give pet some leeway on moving targets. I've seen situations with pet "move to" command where she attacks from a further distance on [cobrak videos](https://youtu.be/vdnk24v7YJg?t=1m34s).

**Comment by UltraNix** [comment]
Fixed.
