### ISSUE TITLE
Character With error when entering the world.

### ISSUE THREAD

**Issue by Mordelonmelo** [gamefreedomgit/Maelstrom#4538]
Good afternoon, my problem occurred yesterday when I was trying to get justice points with the daily mission that is in Dalaran. Without knowing that the room was damaged, I entered and from there I voted off the server and no matter how much I try to enter the world, I only get an error when I press "enter the world." Please free my PC who is a level 85 human Paladin by the name of Megete. This is my last hope since I also sent tickets from other accounts.

**Comment by Waroxx-QA** [comment]
It's a hardware issue, first thing to check is wow folder, your game folder can be corrupted, try installing a new wow client on another folder ( don't delete the old one just in case ) if it still happens, then your pc ( graphic card or system files ) has a problem and it's time to update it.
