### ISSUE TITLE
lock pet spamming

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4539]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
lock pets are spamming their buffs every 0.1 sec which is really noisey and annoying

**How to reproduce:**
summon a pet like felhunter or imp and enable auto buff like fel intelligence or blood pact

**How it should work:**
only cast the buff when its not up

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
