### ISSUE TITLE
Beacon of Light vs Baleroc Vital Spark (old fix created a new bug)

### ISSUE THREAD

**Issue by Baledilan** [gamefreedomgit/Maelstrom#4541]
Description:
After the Fix of this bug https://github.com/gamefreedomgit/Maelstrom/issues/4262
The Beacon of Light now does 0 Healing if the beacon is put on someone other than the tank (for example soaker of shard of Torment) and then healing the tank would result in 0 heals copied towards the beacon of light

How to reproduce:
1: tank with Blaze of Glory stacks
2nd Paladin with Vital Spark stacks
3rd any char which has beacon (Soaker of Shard of Torment)

Have hpala cast direct heal on tank to force buff 

Result : no heals are copied towards the Beacon of Light when healing any other target than the beacon of light itself
![263200515-d45eb819-2451-4d58-a404-ee9b7c70446f](https://github.com/gamefreedomgit/Maelstrom/assets/145230804/a0c855ec-0f23-43b3-b7ae-bb26be8b3cfb)

**Comment by Sketish** [comment]
Tested this on PTR, used beacon on soaking person and it was getting heals so need more details
