### ISSUE TITLE
Schematic: Rocket Boots Xtreme Lite not dropping

### ISSUE THREAD

**Issue by Romkak** [gamefreedomgit/Maelstrom#4543]
[//]: # [(cata-twinhead.twinstar.cz)](https://cata-twinhead.twinstar.cz/?item=35582)

Hello,

Today i tried to farm the Schematic: Rocket Boots Xtreme Lite fomr Mchano-Lord Capacitus in The Mechanar.

https://cata-twinhead.twinstar.cz/?item=35582

According to the twinstar website the schematic should have 30% dropchance on Heroic difficulty and 20% in normal.
After my daily HC try and 25+ normal tries i still haven't seen the schematic.
I opened a ticket to adress this.
One of your GMs answered rappidly stating that he had tried to get it to drop with no luck. He himself stated that it seemed to not be dropping at all and that i should report this as a gamebug. 

So here i am making this post.

**Comment by Afgann** [comment]
fixed
