### ISSUE TITLE
Mind-Numbing Poison bug in arena

### ISSUE THREAD

**Issue by Ramattraa** [gamefreedomgit/Maelstrom#4544]
http://cata.cavernoftime.com/spell=5760
https://cata-twinhead.twinstar.cz/?spell=5760
https://www.wowhead.com/spell=41190/mind-numbing-poison

This bug makes it so that a player who is a druid can apply this poison when attacking in arenas.

Enter arenas with the same set and transmog of the druid named Alright and attack another player.

Under no circumstances should the druid apply Mind-numbing Poison when attacking in arenas.

http://cata.cavernoftime.com/spell=5760
proof: https://media.discordapp.net/attachments/486636852049215509/1152801087787630623/image.png?width=993&height=559

**Comment by UltraNix** [comment]
Fixed.
