### ISSUE TITLE
Priest spell.   The spell (Guardian Spirit) does not restore health after death, but you die immediately.

### ISSUE THREAD

**Issue by druma123** [gamefreedomgit/Maelstrom#4548]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by druma123** [comment]
The spell (Guardian Spirit) does not restore health after death, but you die immediately.

**Comment by Sketish** [comment]
Duplicate https://github.com/gamefreedomgit/Maelstrom/issues/4531
