### ISSUE TITLE
Recover the Cargo! quest broken

### ISSUE THREAD

**Issue by renegadeofunk** [gamefreedomgit/Maelstrom#4549]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Renn's Supplies pack he gives you when you accept the quest is empty. It's supposed to contain tools that you need to complete the quest.

**How to reproduce:**
Accept the quest and try to open the Renn's Supplies pack

**How it should work:**
Renn's Supplies should not be empty

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27237

**Comment by mserkanoz** [comment]
I can confirm it. The pack is empty.

**Comment by Afgann** [comment]
fixed

**Comment by KevlinTallfellow** [comment]
As of Jan 1 2024 the supply pack is still empty.
