### ISSUE TITLE
[Quest] The Wardens Are Watching

### ISSUE THREAD

**Issue by TheGrapefood** [gamefreedomgit/Maelstrom#4550]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The quest is bugged. Whenever a Druid of the Flame is brought to low health, the Warden drops a trap. Upon luring the Druid of the Flame into the trap, it steps in the trap, and after some time, the trap disappears and the Warden bugs, and will no longer participate in combat.

**How to reproduce:** Do the quest as instructed.

**How it should work:** After the Druid of the Flame is lured into the trap, the quest should complete.

**Database links:** https://www.wowhead.com/quest=29192/the-wardens-are-watching#comments

**Comment by UltraNix** [comment]
Fixed.
