### ISSUE TITLE
 Veteran of the Molten Front  title issue-player not receiving it after completing.

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#4553]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?achievement=5879

**Description:** After completing this achievment i havent received title " The Flamebreaker " 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please provide some screenshots of achievements you have so we can check which one are not counting. Title should be added always after getting achiv.
