### ISSUE TITLE
Item " High Warlord's Tome of Destruction " Transmog issue.

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#4554]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/classic/item=23468/high-warlords-tome-of-destruction
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Item cannot be transmoged it says this item cannot be transmogriphied, this item is from Legacy Quartermaster in orgrimmar, item is supposed to be transmogriphable.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
This one require High Warlord pvp tilee to be used as xmog, not a bug

**Comment by Wick3dmind** [comment]
Or whitemane + ? so then why are the other items possible and not this tome ?
