### ISSUE TITLE
[DRUID] Spell - Typhoon

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4556]
https://www.wowhead.com/spell=132469/typhoon

**Description:**

"Knocks the target back and dazing them for 6 seconds"

- the knock back effect takes TOOO long to take effect. Should be almost INSTANT when i press Typhon. Not 2+ seconds after the animation is gone already.

Also it fails a LOT. 50/50 Doesn't do anything doesn't even trigger the Animation or Slow effect just goes on Cooldown.

**Comment by Alleyn321** [comment]
Update - Im in Dungeon leveling Dungeon called Maraudon and Typhoon works as it should. Its instant.

Why is it working in this dungeon but outside delayed 2 sec?

**Comment by Sketish** [comment]
You can miss spells at low lvl so it may be causing that

**Comment by Alleyn321** [comment]
Could be ...


But the Delayed 2 seconds effect is still happening

**Comment by Sketish** [comment]
https://youtu.be/P1Zmc9JQF8w?t=117 on retail there was also delay
