### ISSUE TITLE
[Guild][Perks] Bountiful Bags

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4558]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bountiful Bags is not working?
I disenchant about 20 epic items to maelstrom  [Maelstrom Crystal] x1 never more than one.

**How to reproduce:**
DE epic items with bountiful bags guild perk.

**How it should work:**
https://cata-twinhead.twinstar.cz/?item=52722#disenchanting:100-13+1
https://wowwiki-archive.fandom.com/wiki/Disenchanting_tables
https://wowpedia.fandom.com/wiki/Disenchanting_tables

according to Twinstar and the wowwiki-archive link when DE epic item player should grant 1-2 Maelstrom
I **assume** that **before** Bountiful Bags, with Bountiful Bags I **assume** player able to grant 1-3 or 1-4.

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=9731
https://cata-twinhead.twinstar.cz/?issue=19520

https://www.engadget.com/2012-01-20-how-to-make-146g-maelstrom-crystals-in-5-minutes.html

according to this link: "gives you a 20% yield boost when disenchanting epics".
although I have no clue myself what is the chance of the perk I can understand it is 20%?

Note: I am limited with DE items duo to gold, I am aware that DE 20 items might be low number, statistically.
as I said **ALL** the 20 items I DE'd grant me x1 Maelstrom.

I just report if everything is fine with the guild perk, ignore and close it ;-)

**Comment by BalanCV** [comment]
You were just unlucky I guess. Or maybe only your character is bugged under unknown conditions. For me it works fine.
https://imgur.com/a/TjEYxAA

**Comment by Afgann** [comment]
fixed
