### ISSUE TITLE
Quest Voodoo Zombies

### ISSUE THREAD

**Issue by biljak323** [gamefreedomgit/Maelstrom#4562]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Killing Digsite Zombie spawns Digsite Survivor but the quest dose not count +1 to objective it stays 0/10

**How to reproduce:**

**How it should work:**

Objective should be upadted to 1/10, 2/10...

**Database links:**

https://www.wowhead.com/quest=29150/voodoo-zombies

**Comment by biljak323** [comment]
No, I wasn't in group.

**Comment by UltraNix** [comment]
Fixed.
