### ISSUE TITLE
Glorious Conquest Quartermaster.

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Maelstrom#4563]
**Description:**
Glorious Conquest Quartermaster
name : Doris Chiltonius
 Warrior items requires Shaman items to be upgraded.

**How to reproduce:**
Warrior items cant be bought because of requiring shaman items

**How it should work:**
Warrior items should be upgraded by warrior items not shaman.

**Database links:**

https://cata-twinhead.twinstar.cz/?item=70258
https://cata-twinhead.twinstar.cz/?item=70257
https://cata-twinhead.twinstar.cz/?item=70256
https://cata-twinhead.twinstar.cz/?item=70255
https://cata-twinhead.twinstar.cz/?item=70254
    **SHOULD BE THESE**
Instead it requires these 
https://cata-twinhead.twinstar.cz/?item=70274
https://cata-twinhead.twinstar.cz/?item=70275
https://cata-twinhead.twinstar.cz/?item=70276
https://cata-twinhead.twinstar.cz/?item=70277
https://cata-twinhead.twinstar.cz/?item=70278
Screenshots : 
![1](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/1ac61c23-35b2-4391-b79a-fb93d021c7c7)
![2](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/772006eb-3d57-4ac8-bf50-29ebebbc086d)
![3](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/a596ac0f-bf0c-4651-9aa5-7d921f584257)
![4](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/169136c4-03cd-4add-bd85-914efcecf0d7)
![5](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/74717eef-04d9-4940-98cb-b93a37df6446)
![6](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/3561f11a-9867-45d6-9894-f3c22e5d7e65)
![8](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/0d43613c-2ac6-4c42-a46b-dee96debf257)
![7](https://github.com/gamefreedomgit/Maelstrom/assets/144904865/22f5541c-3929-47de-8a87-3a0642222783))

**Comment by Afgann** [comment]
fixed
