### ISSUE TITLE
The Lost City of Tolvir - Final Boss DC

### ISSUE THREAD

**Issue by ahearneo** [gamefreedomgit/Maelstrom#4564]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On the final boss of Lost city, just as the boss is transitioning into Phase 2 if an add is alive and we are all knocked into the air it seems to trigger a dc,, i had this happed 2 days in a row now and when logging back in it is not only me who disconnects it was the rest of my group as well

**How to reproduce:**
it seems to only happen was transitoning into p2, both times this has happened i was in a group with pets - it always happens when im in the air from the explosion

**How it should work:**
shouldnt disconnect

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/145494225/5de7d878-7d3d-4a96-adca-6b95350ae209)
![Screenshot 2023-09-19 193250](https://github.com/gamefreedomgit/Maelstrom/assets/145494225/7431cc01-ec93-41f0-9f0a-bbb14d2b0426)

**Comment by UltraNix** [comment]
@ahearneo 
`it always happens when im in the air from the explosion`
What explosion do you mean? Storm Cloud?

**Comment by UltraNix** [comment]
No further info - closing.
