### ISSUE TITLE
Fell through earth

### ISSUE THREAD

**Issue by slothic** [gamefreedomgit/Maelstrom#4565]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon exiting gnomeregan I got placed underground and fell through the earth.

**How to reproduce:**
Enter gnomeregan and exit gnomeregan.

**How it should work:**
Not falling through earth.

**Database links:**

**Comment by Waroxx-QA** [comment]
can't reproduce.

**Comment by Waroxx-QA** [comment]
I couldn't reproduce it. send video proof or explain how to reproduce it exactly.
