### ISSUE TITLE
Concentration Aura, Aura Mastery

### ISSUE THREAD

**Issue by AlpReal** [gamefreedomgit/Maelstrom#4566]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Concentration Aura, with Aura Mastery active, doesn't make party members interrupt and silence immune, only the paladin.

**How to reproduce:**
Interrupt a party member of the paladin while Aura Mastery with Concentration Aura is up.

**How it should work:**
The party members should get immune to interrupt and silences as well.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=31821

**Comment by SimonBpvp** [comment]
did u find this in BGs where there are multiple palas cause I noticed this bug there specifically.

**Comment by AlpReal** [comment]
also in arenas with only a single paly being in the group.
