### ISSUE TITLE
coren direbrew deserter

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4567]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** fix damn coren direbrew, i get 3 deserters in a row , ask GM crywolf he helped me with deserter debuff

**How to reproduce:**

**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/7340584a-0072-43dc-8d68-6f640dd4ef3c)

**Database links:**

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/7208259e-224d-4ef9-acd5-1dd021e0eba3)

look the time , in first photo was 09:07 in my country , second photo 09:10 and got deserter again , and happend when i exit dungeon and leave the party

**Comment by Sketish** [comment]
Invalid report, follow template next time :)
