### ISSUE TITLE
[Coren direbrew] deserter

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4568]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** i get deserter from nothing after i kill coren direbrew and leave party

**How to reproduce:** kill coren direbrew , then exit dungeon from  dungeon finder button and leave party

**How it should work:** dont get deserter

**Database link : 

As you can see in first photo time is 09:07i got deserter , after this gm removed then i did another coren and get deserter again at 09:10

**Comment by xmrshoot** [comment]
![269178032-7340584a-0072-43dc-8d68-6f640dd4ef3c](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/93366070-0e2e-422d-adb2-d84a542a6418)
![269178616-7208259e-224d-4ef9-acd5-1dd021e0eba3](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/19240139-d489-4f4a-a327-5b2d45b6c19b)
![269178616-7208259e-224d-4ef9-acd5-1dd021e0eba3](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/090335c9-3568-415c-ad28-269e8f52d49a)

**Comment by Whatisthisclass** [comment]
Still happened as of today (after update)

![unnamed](https://github.com/gamefreedomgit/Maelstrom/assets/112827896/51598571-8c13-47b2-8859-e155f0df3780)

**Comment by UltraNix** [comment]
Fixed.
