### ISSUE TITLE
DK Death Grip not working as intended

### ISSUE THREAD

**Issue by rosessix** [gamefreedomgit/Maelstrom#4569]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The DK's Death Grip, does not actually grip the enemy. It does the particle animation, but thats about it: https://streamable.com/31xzre (video expires in 2 days from now).

**How to reproduce:**
Be a DK and grip a Npc (have not tried on players)

**How it should work:**
When the DK Grips a person, it should move the selected player towards the DK.

**Comment by Afgann** [comment]
fixed
