### ISSUE TITLE
Mastercraft Kalu'ak Fishing Pole

### ISSUE THREAD

**Issue by Roskenc** [gamefreedomgit/Maelstrom#4570]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The item "Mastercraft Kalu'ak Fishing Pole" doesn't show up in the weapon's section for transmogging even though it said it got added to the collection upon buying it.

**How to reproduce:**
Farm the Fishing pole and try to use the Limitless Transmogrification 

**How it should work:**
Should just show up in the Weapon's section for transmogging

**Database links:**

**Comment by Afgann** [comment]
fixed
