### ISSUE TITLE
[Core] Summoning a Player multiple times or waiting too long to accept

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#4571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Summoning a Player multiple times (overlapping a currently ongoing summon that went through) will often (not always) lead to the summon being bugged, so that accepting the summon does absolutely nothing. 
This also sometimes happens if the summon (doesn't matter if it was only one or multiple ones going through) is almost running out, approximately >45-60sec left to accept.

This bug affects summons from summoning stones/ritual of summoning (warlock summoning stone)/have a group will travel (guild perk).

**How to reproduce:**
1st scenario: Summon someone multiple times in a row, while a summon is already active on that player, before accepting the summon.

2nd scenario: Wait about 60-75sec before accepting a summon.

**How it should work:**
Multiple summons shouldn't bug out the summoning effect. The same goes for waiting for a bit before you accept a summon.

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
