### ISSUE TITLE
arena frames bug

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4572]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
your frames bug and you get arena 1/2/3 on positions 2/3/4 which ruins your targetting

**How to reproduce:**
When your team mate enters arena and then summons a pet, and then you enter after that pet was summoned then the pet will appear on first arena frame.

**How it should work:**
always show 1 2 3 on 1 2 3 positions, pets are the problem

**Database links:**

**Comment by SimonBpvp** [comment]
> Hey can I ask you something since you are pr0 warlock ;-)? Bane of Doom should be dispellable? because if I remember well on Twinstar you could not dispel it and here you can. what your opinion?

yah bane of doom is a curse so it's decursable by shamans, druids and mages

**Comment by UltraNix** [comment]
#4138
