### ISSUE TITLE
event items

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4573]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
event items can be disenchant

**How to reproduce:**
use disenchant in item

**How it should work:**
event items should not be can disenchanted

**Database links:**
https://www.wowhead.com/event=372/brewfest and all trinkets from boss
https://www.wowhead.com/item=71337/mithril-stopwatch and etc.

**Comment by Waroxx-QA** [comment]
<html>
<body>
<div class="comment-header" style="outline: none; max-height: 1e+06px; color: rgb(187, 187, 187); font-size: 13px; margin: 0px; padding: 0px 0px 0px 10px; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

By Siigari (2,385 – 15·27) on 2011/10/09 (Patch 4.2.2) |   |  
-- | -- | --


</div><div class="text comment-body" lang="en" style="outline: none; max-height: 1e+06px; overflow: auto; padding: 10px 0px; color: rgb(187, 187, 187); line-height: 1.4; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">You cannot disenchant this.</div>
</body>
</html>By [Siigari](https://www.wowhead.com/user=Siigari) (2,385 – 15·27) [on 2011/10/09](https://www.wowhead.com/item=71337/mithril-stopwatch#comments:id=1538881) (Patch 4.2.2)		
You cannot disenchant this.

**Comment by Afgann** [comment]
fixed
