### ISSUE TITLE
Hyper-Vision Goggles

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4574]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
these goggles are usable in rated bgs to see stealth classes

**How to reproduce:**
equip them in rated bg 

**How it should work:**
You can't use engi items in rated bgs or arenas but you can use them in normal BGs along with everything else

**Database links:**
https://www.wowhead.com/tbc/item=23763/hyper-vision-goggles#created-by-spell

**Comment by Waroxx-QA** [comment]
Not a bug till you give a proof.
