### ISSUE TITLE
[Quest] Heart of flame

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Maelstrom#4576]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Players not able to pick up heart of flame after collecting 250 essence

**How to reproduce:**
After killing the boss Ragnarous , the heart of flame is visible but not able to pick it up for some reason 

**How it should work:**
players should be able to pick it up after collecting 250 essence , they're unable to do that after collecting the essences for some reason Note : **IT WORKS FOR SOME PLAYERS AND SOME PLAYERS IT DOESNT WORK**

**Database links:**
https://cata-twinhead.twinstar.cz/?item=69848
QUEST ID:
Alliance : https://cata-twinhead.twinstar.cz/?quest=29307
Horde : https://cata-twinhead.twinstar.cz/?quest=29308

**Comment by Sketish** [comment]
Hearth shouldnt be lootable if players dies during encounter.

**Comment by UltraNix** [comment]
@GM-Nightmare Still happens?

**Comment by Meyzie** [comment]
Still happens, but its like Sketish said, if the player dies, he looses the buff. If he looses the buff, he is not supposed to be able to loot it. This is correct and intended.

**Comment by UltraNix** [comment]
Then it seems not a bug.
