### ISSUE TITLE
Character Bug

### ISSUE THREAD

**Issue by Roli9503** [gamefreedomgit/Maelstrom#4577]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My character buged under OG, i cant move or use HS

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by GM-Nightmare** [comment]
Make a ticket ingame and will be happy to help you =)
