### ISSUE TITLE
[Core][PvE][Crowd Control] CC pulling aggro

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#4578]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Casting CC on npcs (for example Polymorph) pulls aggro from the mob and the npcs around them.

**How to reproduce:**
Go into a dungeon and polymorph a npc inside a trash group.

**How it should work:**
Polymorph and other similar CC effects shouldn't pull aggro.

**Database links:**

**Comment by Whatisthisclass** [comment]
This was added to the changelog, but after today's update this bug is still present. Polymorph is pulling aggro of trash groups and nearby npcs aswell as the target itself.

**Comment by UltraNix** [comment]
Fixed.
