### ISSUE TITLE
[Dungeon][Halls of Origination][Heroic] Rahj

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4579]
Well, It's just general issue report about the dungeon on heroic mode.
I might use it again in the future even after it'll go 'closed'.

the boss Rahj on Whitemane is melee players(tank mostly because keeping the aggro) while using ability "Blessing of the Sun".
so tank is getting extra damage melee + ability.

boss should stop melee while using the ability:

https://www.youtube.com/watch?v=UkfKvBpas1k => 1:05
https://www.youtube.com/watch?v=C6CqMqlm-ow => 1:13

**Comment by Afgann** [comment]
fixed
