### ISSUE TITLE
[Brewfest] Orc commoners missing in Orgrimmar

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4580]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The questgivers "Orc Commoner", that are supposed to start the Brewfest quest chain, are no where to be found. 

**How to reproduce:**
Search through Orgrimmar.

**How it should work:**
They are supposed to be spread all over Orgrimmar, giving the quest.

**Database links:**
https://www.wowhead.com/tbc/npc=19175/orc-commoner#starts

**Comment by UltraNix** [comment]
Fixed.
