### ISSUE TITLE
[Dungeon][Blackrock Caverns][Heroic] Rom'ogg Bonecrusher

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4581]
**Rom'ogg Bonecrusher:**

Quake ability:
https://github.com/gamefreedomgit/Maelstrom/issues/1971#issuecomment-1431483666
On that comment you stated the timer for Quake is setted to 17 sec or around that.

Quake timer should be 24-25 sec (24.99)
DXE:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/5fcfc5c7-3aeb-4697-88cc-ecf91b1cac72)

VIDEO:
1st time: 0:30~
2nd time: 0:54~
https://www.youtube.com/watch?v=Ual9phdWSHU

**Comment by Afgann** [comment]
fixed
