### ISSUE TITLE
[Dungeon][Blackrock Caverns][Heroic] Ascendant Lord Obsidius

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4582]
**Ascendant Lord Obsidius:**

The boss is fine except his **Shadow of Obsidius**.
1. The melee damage of the NPC is wrong.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/c8bc5192-4a03-4d6b-96bf-2edb242cd1f6)

VIDEO:
https://www.youtube.com/watch?v=lxIx_fu_bQ0 => 0:10-0:20
https://www.youtube.com/watch?v=_sArB-YXz4M => 1:43-1:50

2. the NPC can be dodge, resist, miss, parry, deflect etc etc.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/78c841a7-3ef2-4481-8a7f-d261bb5b9bfd)

which cause them to not apply Crepuscular Veil.

3. There should be only 1 Crepuscular Veil debuff, not 3.
in Whitemane each Shadow of Obsidius has own debuff and it's overlapping each debuff has it's own timer
4 seconds * 3 that 12 seconds total debuff, kinda wrong.

**Trash NPC**:

**Conflagration**
on some videos Group able to pull the NPC upstairs, near the bridge so Quicksilver won't be activated / deactivate
https://www.youtube.com/watch?v=VQ-QGTOkruM => 8:05
https://www.youtube.com/watch?v=8eYTNIx37dA => 6:16

Although according to this video
https://www.youtube.com/watch?v=-dqtb__obpE => 16:25 they do follow even if you go upstairs.

**Others:**

You can use the teleport to Karsh platform before killing him
 I assume it happen on Whitemane after killing Corla which causes 'skip' some Trash NPC
we able to go last boss but Raz wasn't activate, so we had to do all back.
But, according to what I know you cannot use the teleprot before **Karsh** boss is killed not Corla.

**Comment by Afgann** [comment]
fixed
