### ISSUE TITLE
[Dungeon][Vortex pinnacle][Heroic] NPC timer

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4583]
the NPC timer is missing, the NPC spamming ability.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/35ad7026-6886-4957-b9ef-620692af258a)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/423d8ec1-0f0c-43a2-aa48-5eb98f82f448)

**Comment by Afgann** [comment]
fixed
