### ISSUE TITLE
[Dungeon][Zul'Gurub] Zanzil

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Zanzil
1. Gas phase is immediately damage group even without animation

2. If Gas phase start when boss is almost die it still damage group the fight is not 'end'.
The boss used Gas phase about 1% HP, we killed the boss, we still took damage from Gas even after boss died.

**How it should work:**
1. https://www.youtube.com/watch?v=73h45_wjP_Q => Gas animation is about 28:18 (?) and damage start 28:25 (?) ~ approx.
that's about 8 seconds~ to group to reach and click the green cauldron.
In whitemane as I wrote, when he announce Gas phase the damage start instantly.

2. those screenshots for (2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/9f5a1f89-52c9-4255-8fa6-a8ef10b6d5bd)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/250e4094-f55a-4411-b7b4-930e3a83bb27)

**Database links:**

https://www.youtube.com/watch?v=73h45_wjP_Q 4.2 => Zul'Gurub (probably the most update/accurate video of this dungeon)

**Comment by Afgann** [comment]
fixed
