### ISSUE TITLE
[Dungeon][Zul'Gurub] Kilnara

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4585]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Kilnara: 
damage melee & abilties probably not scaling properly.

screenshots:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/cab6ecdb-ab4e-45c6-85a0-3159007d2638)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/6a87093f-0eea-455c-aed0-ebc82efc2800)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/9ce11b04-f3fd-4192-a544-50da6be926e7)

Bethekk:
 melee damage probably not scaling properly.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/d0701ec3-55f7-4473-9ff8-66cb815e0a79)

**How it should work:**

Kilnara:
There alot of videos of Kilnara even killed solo (Cataclysm - probably DS gear)
https://www.youtube.com/results?search_query=kilnara+solo

You can watch the damage and compare it to screenshots above. (100k/160k hits)

Bethekk:
https://www.youtube.com/watch?v=LQ9AzD3olIY => if I see correctly (the font sucks) the Bethekk melee attacks melee attack for 7.2k~ approx
https://www.youtube.com/watch?v=U6xIs06CIo8 => another video 7.2k~ approx

compare to the screenshot above. (23k / 57k hits)

More something about Bethekk
It seems sometimes when the NPC leap it just refresh the Gaping Wounds without giving it extra stack(s).
**but** sometimes it give you more stack(s) for no reason, people were are not stacking / 5-6 radius.

Example:
screenshot 1 leap = x3 stacks.
(I am sorry for cutting the screenshot like this, it was the pack near the stairs before the boss. [only 1 Bethekk]
You can see Lesser priest there.)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/07c085b2-4352-4268-b3c2-a88544cd5673)

Source link I recommend:
https://www.youtube.com/watch?v=73h45_wjP_Q = Zul'Gurub 4.2 video (probably the most accurate / updated version of ZG)

**Comment by Afgann** [comment]
fixed
