### ISSUE TITLE
[Dungeon][Zul'Gurub] Mandokir

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4586]
**Description:**
1. his melee attacks are hitting tank for 100-160k even before reach Frenzy -> tanks are getting one shot.
on Whitemane tanks can die even while boss just has x2-x3 "Level Up" buff.

BDK 361~ ilvl gear get 140k hit.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/946d40b2-c0dd-46f3-aba8-7ead112b99cd)
Feral 361~ ilvl gear get 113k hit
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/3a9982b5-8896-4a5f-a67c-378c7de9eecb)

Mandokir melee damage
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/dfa8b2bb-5a9b-426f-af6f-58d08c56bf7f)

2. Mandokir is using Decapitate against his current target => The **tank**.
Mandokir should not use Decapitate on **tank**. 
(I'll have to watch more videos to see if It's correct report, since I see links say tank is also get Decapitate)

**How it should work:**

1. videos for (1)

https://www.youtube.com/watch?v=pwy3j891eA4 => the boss is hitting 17-20k melee.
at 1:53 boss using **Frenzy,** the Blood DK did not used Icebound nor Death Strike (Blood shield)
Mandokir melee hit for 21.8k damage.
You can see in the video the tank is stand while the boss Frenzy and not getting one-shotted.

https://www.youtube.com/watch?v=ESH-YSeoekE or here.

2. sources for (2)

source1: https://www.mmo-champion.com/threads/1293490-quot-Bloodlord-Mandokir-will-no-longer-use-Decapitate-against-his-current-target-quot

source2: https://www.wowhead.com/spell=96684/decapitate#comments
"Tank never gets jumped so this is especially easy if 3 guys have died to decapitate, if the 4th person hasn't died yet then it seems to be 100% chance that he's the next target."

Note:
https://www.youtube.com/watch?v=73h45_wjP_Q => 11:06 Mandokir fight.
- Look at HP bar of Tank.
- Ability timers on top-right near mini-map.
- No Decapitate on tank detected
- at 13:22 the boss Frenzy.

**Comment by Afgann** [comment]
fixed
