### ISSUE TITLE
Hyper-Vision goggles with proof

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4587]
**Description:**
these goggles are usable in rated bgs to see stealth classes
https://user-images.githubusercontent.com/110876820/183555177-80fc0631-0c8b-4988-9ac0-9ec71b05c155.png
the screenshot is from a hotfix in wrath
(my last post was closed for lack of proof but you could have just asked first!)

**How to reproduce:**
equip them in rated bg

**How it should work:**
You can't use engi items in rated bgs or arenas but you can use them in normal BGs along with everything else

Database links:
https://www.wowhead.com/tbc/item=23763/hyper-vision-goggles#created-by-spell

**Comment by Afgann** [comment]
fixed
