### ISSUE TITLE
Shaman - Elemental Mastery bug

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you cast elemental mastery (EM), your next Lightning Bolt(LB), Chain Lightning(CL) or Lava Burst(LvB) will be instant. Currently sometimes this does not happened and the 30s buff just expires after 30s. Also the EM does not go on cooldown until those 30s are passed (this is not a bug, but it makes it so we loose 30s of CD from EM)

I never encountered that bug until i got DTR, and now its like 1 time per fight on average. Not saying its DTR fault, but its the only thing that i changed just before i started encountering this bug

In this clip you can see that i cast EM, and spam LB and the 30s EM buff that supposed to make it instant (id 16166) last for the entire 30s. The EM CD starts when the buff expires. Do not look at the WA in the middle, its scuffed because of me reseting CDs for testing. 
[clip](https://clips.twitch.tv/IgnorantAbstruseAnteaterStoneLightning-rK_FXo7iwRIbh6n_)

I'm aware of the EM cooldown cd display bug, this is completely something else.

Also weird thing in the logs : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/ae8d6be8-e1c8-4eba-ba7c-682351f1d5a1)

On live right now, every spell you cast that is not instant will show as the 2 last LB on that screen, but when i get the bug, they do show as cast and not just "begin cast" (with no cast successful event). You can see that for 30s after casting EM (which is the buff duration), all non instant spell are not "begin cast" only. The first lightning bolt that says 18,15s cast is because the last LB i casted was a "begin cast" LB 18s earlier.

**How to reproduce:**

Equip DTR?
Use EM and try casting LB.
If its instant, reset CDs and try again

**How it should work:**

As buff says and as it works without DTR

**Database links:**
https://wowpedia.fandom.com/wiki/Elemental_Mastery?oldid=2703317

**Comment by whothatdog** [comment]
I just want to know what is that combatlog screenshot you posted, what is it an addon? name it ;-)

**Comment by Polynomix** [comment]
/combatlog in game, then upload to warcraft log

**Comment by whothatdog** [comment]
oh, I used WoL when had different UI.
beautiful ;-)

**Comment by Polynomix** [comment]
@Sketish What info do you need ?

**Comment by UltraNix** [comment]
@Polynomix Poke me on Discord.

**Comment by UltraNix** [comment]
Fixed.
