### ISSUE TITLE
replenishment enduring winter

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
replenishment doesn't spread to your team mates.
https://gyazo.com/c4935066486920c4780bb7ba9c8bed7f
here i casted a frostbolt, I got the replenishment buff but my team mate didn't.

Doesn't work for rdruid talent either

**How to reproduce:**
Form a party and do something that gives replenishment. I did frostbolt with 3/3 enduring winter _**MAYBE ITS BUGGED WITH OTHER SPELLS WHICH GIVE REPLENISHMENT TOO_**

**How it should work:**
![e24230ededdea7aefc36ec40ca7c24d5](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/276e5556-7cca-4b17-b23d-0c3bb904a602)

![e1eb21e775c48c580117e67058b5bdd6](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/3a86bb10-cc28-4260-93e1-60a7b6f439ae)

Replenishment like it says on tooltip gives the buff to all party members 

**Database links:**
https://cata-twinhead.twinstar.cz/?search=replenishment#spells
https://cata-twinhead.twinstar.cz/?spell=86508
https://cata-twinhead.twinstar.cz/?spell=48544

**Comment by Afgann** [comment]
https://www.bluetracker.gg/wow/topic/eu-en/8864809328-replenishment-change-for-arenas/

**Comment by SimonBpvp** [comment]
https://www.youtube.com/watch?v=ppoR0FQLKd8 

youre right i see it here. Didn't know that
