### ISSUE TITLE
[Brewfest][Currency] Ram Master Ray daily repeatable not giving reward.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4591]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing "There and back again", rewarding 10 brewfest tokens, Ram Master Ray should once a day offer you a ram bridle, letting you deliver as many kegs as you can in the given amount of time (4 minutes + a bit more with each keg delivered) - each producing 2 additional brewfest tokens. While the bridle can be picked up and the kegs can be caught AND delivered, they do not award 2 tokens per keg, as they should.

**How to reproduce:**
Complete https://www.wowhead.com/quest=11409/now-this-is-ram-racing-almost and https://www.wowhead.com/quest=11412/there-and-back-again, then acquire a set of ram racing reins and ride to and fro https://www.wowhead.com/npc=24527/bok-dropcertain, accepting the portable brewfest keg, rude back to Ram Master Ray, where the keg dissappears and should instead give you 2 tokens, but doesn't.

**How it should work:**
...It should give you 2 tokens per keg delivered.

**Database links:**
https://www.wowhead.com/npc=24497/ram-master-ray
https://www.wowhead.com/quest=11412/there-and-back-again
https://www.wowhead.com/item=33306/ram-racing-reins
https://www.wowhead.com/npc=24527/bok-dropcertain
https://www.wowhead.com/item=33797/portable-brewfest-keg
https://www.wowhead.com/item=37829/brewfest-prize-token

https://vimeo.com/867149411/c3b4ddf5ac

**Comment by UltraNix** [comment]
Fixed.
