### ISSUE TITLE
[Hunter][Survival][Talent] Lock and Load

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4592]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When Hunter use ice trap and NPC activating the trap - LnL will proc.
If you run the NPC out of the ice trap and make him run on it again, it re-proc the LnL
when it should not proc it.

**How to reproduce:**
ice trap some NPC, LnL will proc.
move the NPC out of the trap by kiting it.
wait 13-14 sec (talent timer).
move the NPC back again to the trap.

**How it should work:**
as far I **know**: LnL should proc **only once** when NPC activating the trap.
making NPC walk on it back and forth should not re-proc LnL.
to proc LnL from trap, hunter will need new ice trap.

Note: tested on Twinstar PTR realm
LnL is not re-procced.

I haven't recorded it with timestamp.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/a6095769-522c-4f55-b2d4-f478a5539b65)

ice trap used (line 1)
LnL proc (line 2)
faded (line 3)
after 13-14 I re-gained it (line 5) <= ~ => should not get LnL from the same existed trap again.
faded (line 6)
repeat.

from trap it should proc only once, when NPC/Player step on the trap.

**Comment by Sketish** [comment]
Provide any sources that are proving this

**Comment by whothatdog** [comment]
> Provide any sources that are proving this

It would be hard or near impossible for me to find a video or proof 
that if you take NPC/Player out of trap and somehow (like by disengage over it) and force him or that to run or step over the trap again it will proc LnL.

on Twinstar 1 trap = 1 LnL proc.
move in the trap, move out the trap, move in the trap won't trigger LnL again. (by the same trap)
if Survival hunter want new LnL proc he will need to throw new trap.

otherwise the only way to proc LnL is via Black Arrow or Explosive trap.


Twinstar bug report about LnL:
https://cata-twinhead.twinstar.cz/?issue=3809

the closest thing I found is also posted within the report in Twinstar is

https://www.youtube.com/watch?v=EMEiwJrpCbU - I recommend to watch from 6:00
but specially at 6:20 when warrior and dk are stepping inside the trap (that exist) and it does not triggering LnL.

to trigger/proc LnL it require the hunter **new trap**, black arrow or explosive trap.

I also recommend to translate some of the comments in the bug report it might help.

**Comment by whothatdog** [comment]
Hi @UltraNix, @Sketish 
I notice a new bug probably related to this issue.

if you use Ice Trap and Explosive Trap on the same Ice Trap.
the Explosive Trap is not proc LnL.

Like this:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/2f83bf82-24e2-469b-b77d-d633c6fbde9d)

Ice Trap is work great, if you moving NPC out of the effect and move it in again
it does not proc LnL, only if you use new Ice Trap.

**Comment by UltraNix** [comment]
Remember there is a icd on this.

**Comment by whothatdog** [comment]
> Remember there is a icd on this.

ofc, I checked after the icd and I repeat the process more than one time.
here is a clip:

https://streamable.com/gcvcsi

**Comment by UltraNix** [comment]
@whothatdog The bug with Immolation Trap (periodic) not proccing LnL - the fix is on the way.

**Comment by UltraNix** [comment]
Fixed.
