### ISSUE TITLE
Quest: Beer Basted Boar Ribs

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4595]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Ragnar Thunderbrew does not offer the Beer Basted Boar Ribs quest.

https://www.youtube.com/watch?v=1qEVWLrXI1E&ab_channel=gamehelpers%21

**Comment by PanJanuszek** [comment]
fixed 23.04.2024, restart needed
