### ISSUE TITLE
Quests Teldrassil

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4597]
The NPCs do not offer the next quests:

Ferocitas the Dream Eater
Teldrassil: The Burden of the Kaldorei (so the whole quest chain can not be completed).

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/40561716-b655-4a73-ae10-a48d0ff0362a)

AFTER The Emerald Dreamcatcher -> GOT Ferocitas the Dream Eater -> There are no more quests from this NPC

Quest that you are mentioning is in chain ( WORGEN + NIGHT ELF ) only:

1.[Teldrassil: Crown of Azeroth]
2.[Teldrassil: Passing Awareness]
3.[Teldrassil: The Refusal of the Aspects]
4.[Teldrassil: The Burden of the Kaldorei]
5.[Teldrassil: The Coming Dawn]

If you follow the all chain correctly, you will get your "The Burden of the Kaldorei

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/7d267b19-d503-430e-930a-9db89532590b)

Closing as not issue
