### ISSUE TITLE
Gnome starting area double character as pet ?

### ISSUE THREAD

**Issue by im0xdev** [gamefreedomgit/Maelstrom#4598]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Have double character window seems like a pet frame for myself 

screenshot:
https://img001.prntscr.com/file/img001/Dyse9Xn8SQOQPayB6mkVAA.png

**How to reproduce:**
just create new character , with fresh client, without addons and play gnome starting area 

**How it should work:**
dont show pet window after last quest with the teleporter

**Database links:**

**Comment by Zeehra** [comment]
Not restricted to gnome starter area, happens a lot if you've been mounted in a quest vehicle or something like that.

**Comment by UltraNix** [comment]
Fixed.
