### ISSUE TITLE
bug in title "the flamebreaker"

### ISSUE THREAD

**Issue by lebombas** [gamefreedomgit/Maelstrom#4600]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143462139/4c75601a-7ea3-4d14-814d-ca4878def74d)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143462139/d9b5b0cc-04a2-443c-b942-685fbfaa68a9)
I won the achievement "Veteran of the Molten Front", and it didn't give me the respective title on two characters

**How to reproduce:**
do all the achiv, and don't work

**How it should work:**
should give the title "the flamebreaker"

**Database links:**
https://www.wowhead.com/achievement=5879/veteran-of-the-molten-front

**Comment by Sonni69** [comment]
i got same issue

**Comment by UltraNix** [comment]
Fixed.
