### ISSUE TITLE
[Quest][Brewfest] Bark for the Barleybrews can not be completed.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4602]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Accepted https://www.wowhead.com/quest=11293/bark-for-the-barleybrews and rode through all 4 quarters of Ironforge, making sure each area got ticked off as completed. But when I returned to Becan Barleybrew, I could not complete the quest - nothing happened when I pressed "Continue" in the quest text window. I have tried this on two different alliance characters now, both the exact same issue. Am not in a raid group, as a GM suggested, and honestly don't know what else could be the issue.

**How to reproduce:**
Try to complete the quest.

**How it should work:**
After riding through all 4 quarters and "barking" in front of each banner, I should be able to ride back to Becan on my ram and hand in the quest as I get near him, ultimately rewarding me 15 Brewfest Prize Tokens.

**Database links:**
https://www.wowhead.com/quest=11293/bark-for-the-barleybrews
https://imgur.com/a/K7XOWYE

**Comment by svcchostt** [comment]
It works, but you need to return with mounted horse, try to keep the speed to catch up questgiver. But should work with fly mount after all is ticked as done.

**Comment by Zeehra** [comment]
On horde, I could hand in after flying back - on alliance it never completes. Hence the numerous screenshots showing me, on the mount, exactly on the quest giver, within the time limit.

Literally everything I just explained. This is not a matter of me doing it wrong, it is a matter of the alliance version being bugged, which is why I made the bug report, instead of asking for help.

**Comment by UltraNix** [comment]
Fixed.
