### ISSUE TITLE
Raid converting / party bug

### ISSUE THREAD

**Issue by Akayso** [gamefreedomgit/Maelstrom#4605]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

There's a bug regarding raid parties converting back to party. I converted my raid back to a party while having people in Group 2 of the raid. I think this caused our characters to completely bug out as 3 of our characters (we were holding a LAN party at this time) were unable to get invited by eachother. And if one of our invites would go thru, we would see THE OTHER  player in the "party" - NOT the person that invited me.

I'm assuming we're in some kind of limbo.

**How to reproduce:**
Create a party, convert to raid. Place players into Group 2 (in our case). Convert back to party. Leave the party.

**How it should work:**
Self explanatory.

**Database links:**

**Comment by Afgann** [comment]
fixed
