### ISSUE TITLE
Brewfest Event bugged.

### ISSUE THREAD

**Issue by svcchostt** [gamefreedomgit/Maelstrom#4608]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
NPC dungeon boss Coren Direbrew and whole Event is missing after last server restart.
**Description:**  EDIT 2
*All about the event is missing. All npcs in Durotar and Dun Morogh is missing.

**How it should work:**
Should be spawned when enter via event dungeon finder.

**Database links:**
https://www.wowhead.com/npc=23872/coren-direbrew

**Comment by sillsi** [comment]
The event is not running currently at Dun morogh at all. There are no npcs, objects and quests spawned.

**Comment by UltraNix** [comment]
Just tested - seems to be okay.

**Comment by UltraNix** [comment]
Fixed.
