### ISSUE TITLE
Enduring The Heat Daily Molten Front

### ISSUE THREAD

**Issue by idhida** [gamefreedomgit/Maelstrom#4609]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/quest=29210/enduring-the-heat)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i'm working on daily "enduring the heat" but when i enter the igneous depthts it not check, and there are no flame runes to destroy

**How to reproduce:**

**How it should work:**
when i meet the npc Thresa Barkskin, it shoud count i enter the igneous depth, but it doesn't, 
and in the igneous depth there are 8 runes to destroy, but i get nothing to do with it. please help
**Database links:**

**Comment by UltraNix** [comment]
@idhida Still happens?

**Comment by UltraNix** [comment]
No further info - closing.
