### ISSUE TITLE
Dots keeping you in combat? 

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4610]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you respawn in a BG you are instantly in combat, no other players anywhere near you. I think your own dots are keeping you in combat or something

**How to reproduce:**
Dot an enemy player and wait

**How it should work:**
Your dots should never keep combat in PvP. Only direct actions done by you or against you can start combat (exception:  living bomb explosion which counts as direct dmg at the end of a dot) 

**Database links:**

**Comment by UltraNix** [comment]
#3375
