### ISSUE TITLE
Ragnaros heroic meteor and breadth interaction

### ISSUE THREAD

**Issue by Stega23** [gamefreedomgit/Maelstrom#4611]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Going to be two different buggs, sort of conected in this post:
1. Getting meteor into Breadth of Frost at phase 4 of HC Ragnaros instantly despawns Breadth, while it should despawn only after meteor frozen debuff expires, players should be able to stay in breadth and not take fire damage while killing the frozen meteor.
2. Meteor after getting killed doesnt despawn here, or despawns after long time, making dreadflames sometimes "hide" in it, it should despawn in 1-2 seconds.

**How to reproduce:**
Get in 4th phase, try to freeze 2 meteors on same patch, or try to see does breadth work while meteor is frozen in it

**How it should work:**
You can freeze indefinite amount of meteors on a patch, and their corpse should despawn in 1-2 sec.
https://youtu.be/hKL-TwZb9IM?t=1865

&  comment below the video
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94021456/adb2fb79-ef72-46dd-af8e-16f3dc17077c)

**Database links:**

**Comment by Sketish** [comment]
https://youtu.be/O-DIQF2Jj3Y?t=617 as breath source

**Comment by UltraNix** [comment]
Fixed.
