### ISSUE TITLE
Thunderstorm/ CCed targets

### ISSUE THREAD

**Issue by AlpReal** [gamefreedomgit/Maelstrom#4614]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Targets who are affected by CCs can not be knocked away with thunderstorm

https://youtu.be/TUA3JuRhNcA?si=WWpybDyCUggX4YHH&t=744
As you can see, the shaman gets knocked away while being affected by Hex.

**How to reproduce:**
Thunderstorm a target that is affected by Polymorph as an example

**How it should work:**

Polymorph should break, and the target should get knocked away
**Database links:**

**Comment by Afgann** [comment]
fixed

**Comment by oldspices** [comment]
hex allows you to take damage tho without breaking hex, so you should be knocked away...
