### ISSUE TITLE
Hunter Talent Master Marksman doesn´t work properly

### ISSUE THREAD

**Issue by Haramburgers** [gamefreedomgit/Maelstrom#4615]
**Description:**
Hunter Talent Master Marksman doesn´t work properly. If you cast Steady Shot 5 times and always get the talent stack you should get a instant free cast of Aimed Shot but if you cast Aimed Shot before the Steady Shot that should provide the 5th stack hits the target, you have the cast time of Aimed Shot + focus costs but the talent proc fades after the Aimed Shot hits the target. 

**How to reproduce:**
Get 4 stacks of the talent Master Marksman, cast Steady Shot and directly after cast Aimed Shot, if you get the 5th stack the talent proc fades away. If you still have 4 stacks, cast Steady Shot again and then directly after Aimed Shot.

**How it should work:**
If you cast Aimed Shot directly after the Steady Shot that provides the 5th stack of the talent, you should still have an instant free cast of Aimed Shot after the 1st Aimed Shot hits the target.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=34487

**Comment by SexyPancake** [comment]
Had this fixed during PTR before server launch if the issue wasn't resolved I have all the documentation with Mullich.

**Comment by Afgann** [comment]
fixed
