### ISSUE TITLE
[Dungeon][Zul'Gurub] Mandokir

### ISSUE THREAD

**Issue by naturesucks** [gamefreedomgit/Maelstrom#4616]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Phased from party in Zul'Gurub.

**How to reproduce:**
Die to his Decapitate. Release spirit instead of Revive from Chained Spirit. You are now phased from the rest of your party and cannot continue the dungeon.

**How it should work:**
Should not be able to release spirit.

**Database links:**

**Comment by UltraNix** [comment]
Player not able to release spirit before Chained Spirit revives him. After that, he can decline it and release spirit anyway.
I jus tested and see no bug here - no phasing out.
@naturesucks Need more info about this bug. Have you resurrected by entering instance in ghost or maybe revibed by someone?

**Comment by naturesucks** [comment]
Resurrected by entering dungeon.

**Comment by UltraNix** [comment]
I entered dungeon after declining resurrection by Chained Spirit - no problem with phased-out party members.

**Comment by UltraNix** [comment]
No further info - closing.
