### ISSUE TITLE
Bug buying leveling legs on guild

### ISSUE THREAD

**Issue by pitillox** [gamefreedomgit/Maelstrom#4617]
Hey, i got a bug buying leveling legs on my guild, it says we must have a achievement called ''Trabajar en equipo'' , when i enter on the achievement it marks that we dont have a leatherworker with 525 but when i search on the guild who is leatherworker i see that we have atleast 4 persons with 525 i dont know why the achievement is marked as not completed and why i cant buy the legs. Here i attach the screenshots to verify it. Thank you.

![WoWScrnShot_092423_214151](https://github.com/gamefreedomgit/Maelstrom/assets/145934035/bace4b7d-546b-4a8c-8c92-aebf4e0096e6)
![WoWScrnShot_092423_214219](https://github.com/gamefreedomgit/Maelstrom/assets/145934035/417717f5-cf76-4476-ade2-e2e7861154c0)
![WoWScrnShot_092423_214139](https://github.com/gamefreedomgit/Maelstrom/assets/145934035/b341bfda-4871-4cf3-8578-39752af8aaca)

**Comment by UltraNix** [comment]
#4075
