### ISSUE TITLE
Improved Steady Shot (ISS) doesn't work half the time, in particular during high amounts of Haste.

### ISSUE THREAD

**Issue by TheHate123** [gamefreedomgit/Maelstrom#4618]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Abbreviations:
ISS - Improved Steady Shot
SS - Steady Shot
AI - Aimed Shot

ISS is supposed to proc as soon as you cast 2 SS in a row.

**How to reproduce:**
Cast SS twice without casting anything else in between them.

**How it should work:**
You should gain the ISS buff the moment the second SS cast finishes. Yet half the time during Bloodlust, I am very clearly casting two of them and it feels like the game just forgets to count something, I can't really find logic as to why this is happening. I also don't think it has ever happened outside of very high haste amounts, it exclusively happens during stuff like Bloodlust and when flying on Alysrazor.

https://www.youtube.com/watch?v=KTYEvdBGit4

As you can see in the video, at 0:03 I cast 2 SS back to back and I get no ISS proc. 
Even weirder, at 0:12 I cast 2 SS, I don't get ISS, I cast an AI, after which I cast another SS, and then I somehow got ISS. That was a sequence of SS-SS-AI-SS and I somehow got ISS on AI-SS as my last 2 spells.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=53224

**Comment by bonfax4** [comment]
I think the 2nd hit that procs the buff is proccing on cast but it checks for a previous "hit" on steady ? So with enough travel time on huge bosses this can easily mess things up. I assume both checks should be on-cast.

If you notice on your 2nd example aimed shot travels quicker than the 2nd steady so your 3rd steady cast procs the buff because a steady hit was established before the cast ends.

**Comment by bonfax4** [comment]
https://youtu.be/Tc7L9In9gbM?si=Evg0r0lwFxRH_W6f Every 2 steadys he got a proc 100% of the time so clearly a bug. It should check for abilities "casted" in a row and not "hits". Server only seems to check for casts on SS but hits on other abils.

**Comment by Afgann** [comment]
fixed
