### ISSUE TITLE
Moonfire quest bug

### ISSUE THREAD

**Issue by SolidFEAR** [gamefreedomgit/Maelstrom#4620]
Aldrassil, Mardant Strongoak (druid teacher) quest giver. Moonfire quest is not works. Char need to cast a Moonfire spell on the dummy, but this task not works

**Comment by MadeinNoxus** [comment]
I believe it is a bug caused by auto learning all spells, but in reality the quest is heal wounded guard or whatever is the NPC.

**Comment by UltraNix** [comment]
There is no such quest. Clear your cache and try again by healing wounded sentinels.
https://cata-twinhead.twinstar.cz/?quest=26948
