### ISSUE TITLE
Wintersgrasp quartermaster

### ISSUE THREAD

**Issue by Beeeefsquatch** [gamefreedomgit/Maelstrom#4622]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello can the quartermaster in wintersgrasp please be fixed. He is simply not there

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
fixed with POW
