### ISSUE TITLE
dark-simulacrum

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4627]
https://www.wowhead.com/spell=77606/dark-simulacrum
  Skills stolen using the dark simulacrum must be used instantly
https://www.twitch.tv/videos/1934115345 
2:10 dk casting Chaos Bolt...

**Comment by UltraNix** [comment]
Fixed.

**Comment by Sketish** [comment]
people are saying its not working

**Comment by UltraNix** [comment]
More info and details then please.

**Comment by Sketish** [comment]
@pro100klass  Please provide details

**Comment by UltraNix** [comment]
Fixed.
