### ISSUE TITLE
[Core][Instance] Releasing Spirit/Disconnecting mid fight

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#4628]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dying and releasing spirit or disconnecting inside an instanced map while being infight (Dungeon or Raid Boss) bugs out your character, so that when you get combat resurrected, you won't be able to accept it. The error that you can't enter an Instance when an encounter is going on will be shown.
Also if you disconnect while being dead infight, it will automatically release your spirit.

This locks you out of a Boss Kill and Loot if you suffered from accidentally releasing spirit or disconnecting (this will automatically kill your character) mid fight.

**How to reproduce:**
Enter a Party/Raid, fight a Dungeon or Raid Boss and either disconnect and log back in or die and release Spirit. Now receive a combat ress from one of your party/raid members and try to accept it.

**How it should work:**
Releasing spirit infight should still make you eligible to accept a combat ress, as long as the limit hasn't been reached (and you were part of the fight until you died).

Disconnecting infight shouldn't automatically kill you and disconnecting while being dead during an encounter shouldn't automatically release your spirit.

Also disconnecting in general should leave your character online for a short period of time. I don't know the exact number because I couldn't find an exact number on the Wiki or in Patch notes, but according to a bit of research it ranges around 1-2 minutes.

Although there is an exception.
I remember your character staying online as long as it's infight (e.g. until a raid/dungeon boss dies or your character dies) when you disconnect mid fight. I have no other proof for that other than my own memory from retail and forum posts of people saying they were still eligible for loot after disconnecting.

**Database links:**
https://wowpedia.fandom.com/wiki/Disconnect (proof for grace period after disconnecting)

**Comment by UltraNix** [comment]
Fixed.
