### ISSUE TITLE
Hunter snakes targeting system is messed up

### ISSUE THREAD

**Issue by Mongo69** [gamefreedomgit/Maelstrom#4630]
**Description:**
At the moment Hunter snakes prioritize targeting person under the CC effects such as scatter shot,monkey stun or rog's blind
They wont attack that person immediately and break those CC effects but they'll wait next to that person and do absolutely nothing instead of attacking others
And the moment CC'd person escapes the CC either by using pvp trinket or simple break with damage,snakes will attack it and give it dots which for hunter players makes it impossible to continue CC chain for the next 20sec
It seems like CC effects trigger aggro towards snakes which shouldnt be the case

Examples of bug:

(Snakes should attack hunter or his pet,instead of waiting next to priest and do nothing)
https://streamable.com/1iiqo3
https://streamable.com/7rborf

Made a test with pets as well,This part works correct,snakes started attacking hunter instead of waiting for cc on pet to end
It should be same with players around you
https://streamable.com/6hvi0n

**How to reproduce:**
You'll need to have 2 ppl to reproduce this bug 
Use scatter shot/monkey stun first on your focus followed up immediately  by snake trap on either 1
You'll notice as soon as when scatter shot ends,snakes will start attacking that person immediately  

**How it should work:**
Snakes should start immediately attacking someone that's not under CC effects such as scatter,blind,monkey stun etc
Instead of just waiting on top of that person waiting for it to escape the such effects

Following videos are from retail catacylsm late season 11

https://youtu.be/louF9nqpLg0?si=DbJI0Nn3odqrU2k6&t=19
(Shaman is under scatter shot for 2more seconds so snakes start attacking lock,shaman left the cc for 1sec meanwhile snakes are still chasing the lock)

https://youtu.be/ew7etvPDYc8?si=f_AaAEDk3-iea171&t=250
(Snakes start attacking both hunter and dk because paladin was under scatter shot)

https://youtu.be/-BaeSfJEs0E?si=Yhsux5KEYSrudZ2Q&t=28
(Snakes rather start attacking mage thats super far away instead of waiting next to the shaman)

https://youtu.be/QyBPS_0Qq7Q?si=PCOiPDHQF-rj_2Qa&t=172
(Snakes immediately attack rog instead of shaman who was under scatter shot)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=34600
https://cata-twinhead.twinstar.cz/?spell=19503

**Comment by Kenniflopper** [comment]
Confirmed, this is a huge issue

**Comment by UltraNix** [comment]
Fixed.

**Comment by Kenniflopper** [comment]
can confirm this is bugged again now

**Comment by UltraNix** [comment]
Tested and looks okay.

**Comment by UltraNix** [comment]
No further info - closing.
