### ISSUE TITLE
Fire Mages

### ISSUE THREAD

**Issue by dilpertti** [gamefreedomgit/Maelstrom#4631]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Glyph of Fireball and Critical Mass talent are not working properly

**How to reproduce:**

**How it should work:**
Both should give +5% critical chance against target. After some research it shows neither is giving me that +5% critical chance with Pyroblast, hard to create Hot Streaks

**Database links:**

**Comment by SexyPancake** [comment]
Good luck providing the proper sample size to access that the %crit is not working properly (regardless of the issue being true or false). Firemage is the most RNG spec in cataclysm and you would need proper samples to test this.

**Comment by Sketish** [comment]
"After some research" so provide more details because currently you are assuming w/o any data provided

**Comment by bonfax4** [comment]
> Good luck providing the proper sample size to access that the %crit is not working properly (regardless of the issue being true or false). Firemage is the most RNG spec in cataclysm and you would need proper samples to test this.

I mean a dev could easily just equip like 90% crit ( or around 90% depending on crit suppression, not sure how it works in cata ) and see if fireball ever missed a crit. It wouldn't be as hard as you make it sound but i guess a regular player could not pull this off.

**Comment by BalanCV** [comment]
Alright, so I went on PTR with 90% crit and fireballed for like 10 minutes with glyph and scorch up. Result was 100% crit on firebolt so working as intended. I also scorched with 95% and that resulted in a few non crits. Most likely no bug here.
