### ISSUE TITLE
[Paladin][Retribution][Talent] Divine Storm & Divine Purpose

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4632]
**Description:**
When you Divine Storm multiple targets/NPC it seems the Divine Purpose proc higher than 15%.
The talent clearly say 15% for any ability on the list include -Divine Storm- while it doesn't matter how many targets being hit by the ability  => 1, 20 or 100 it should not be more than 15% chance.

* -- Note:
**Probably** there also a bug with Seal of Righteousness.
because when I am hitting Verdict with SoR I am also getting [seems like] increased proc chance to Divine Purpose.

**How to reproduce:**
Divine Storm with any seal on like 16+ targets, see how many procs of Divine Purpose you get.

**How it should work:**
15% chance for 1 target or more.

**Database links:**
The only way I can 'proof' it with this video:
12:37 + 12:45 + 12:49
Ret paladin using 3 times Divine Storm on 10-20 Targets
He do not get Divine Purpose at all.
https://www.youtube.com/watch?v=17R-CifROpE

VS

I am hitting 8 targets, and I am getting x3 Divine Purpose.
of course I can't use all the x3 but only 1.
but It makes Ret Paladins able to use Divine Storm -> Verdict back to back.
my **assumption** on Whitemane right now - the proc chance is like 15% * numoftargets => it's inaccurate.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/37fe99df-821f-444c-aaf4-3eaaba4d925a)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/11136d33-94eb-4bae-9298-2c127b6df1c4)

* -- Note: I am basing this report on retail videos.
and my pserver experience (twinstar), I haven't done research on other sources, forums, databases etc.

**Comment by Renehadox** [comment]
Is this a joke or what?

Why are you trying to nerf Ret paladins so much?

" When you Divine Storm multiple targets/NPC it seems the Divine Purpose proc higher than 15%.
The talent clearly say 15% for any ability on the list include -Divine Storm- while it doesn't matter how many targets being hit by the ability => 1, 20 or 100 it should not be more than 15% chance. "

Its 15% chance per HIT, not per cast, you misunderstand things, if you do not know the game mechanics then do not bother to post here wasting everyones time.

**Comment by whothatdog** [comment]
> Is this a joke or what?
> 
> Why are you trying to nerf Ret paladins so much?

I am no trying to "nerf" anything. but if something is not working right, it deserves a bug report.
I wrote that I am basing this report on videos and another pserver.

I logged that pserver-ptr and did the same.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/77c066e5-d048-4089-8674-66a44c96dffb)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/fdded3dc-56e8-4a6a-9139-4eec2ada879f)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/4d2dc320-fa37-47d3-a638-b7bc26e0350b)

I Divine Storm 3-4 times and haven't got Divine Purpose at all.

another video:
2:04-2:10 
https://www.youtube.com/watch?v=NWlu2Sby1ws

**Comment by Pornoodemon** [comment]
> > Это шутка или что? 
> > Почему вы так сильно пытаетесь ослабить рет-паладинов?
> 
> Я не пытаюсь ничего «нерфить». но если что-то работает не так, это заслуживает отчета об ошибке. На отчете я написал "Примечание", что этот отчет основан на видео и другом псервере. Я буду более чем «счастлив» ошибиться в своих отчетах, чем быть правым, если честно.
> 
> Сравнение: вошёл в этот Twin**-ptr и сделал то же самое: ![изображение](https://user-images.githubusercontent.com/143028214/271390166-77c066e5-d048-4089-8674-66a44c96dffb.png) ![изображение](https://user-images.githubusercontent.com/143028214/271391729-fdded3dc-56e8-4a6a-9139-4eec2ada879f.png) ![изображение](https://user-images.githubusercontent.com/143028214/271391588-4d2dc320-fa37-47d3-a638-b7bc26e0350b.png)
> 
> Я несколько раз проходил «Божественную бурю», но у меня вообще не было «Божественной цели», несколько раз я получал прок. (<= нормально). Что еще более **заметно** , нет ли в плавающем боевом тексте эффекта божественной цели x3 (это то, что я пытаюсь показать на этих скриншотах)
> 
> еще одно видео: 2:04-2:10 10:29-10:37 13:39, 13:43 https://www.youtube.com/watch?v=NWlu2Sby1ws

It’s good that you wrote about this, otherwise the paladins play and are silent.

**Comment by Sketish** [comment]
Also spells should have proc chance roll on pressing skill that checking on each hit.

**Comment by whothatdog** [comment]
I see there is only 1 proc atm of Divine Purpose when you Divine Storm no matter what.
Yet the proc chance seems very odd and not 15%.

Here a test I done for 40 times Divine Storm on Whitemane.

6-7 targets:
https://pastebin.com/WgYnMydv - the proc chance is 82.5%~

1 target:
[x](https://pastebin.com/fRUPAVup) - the proc chance is 17.5%~ 
(It's low number of tries [big number theory it probably will go 15%])

P.S
I might edit this message and will add clips later on.

**Comment by whothatdog** [comment]
The same problem occur with Holy Wrath, but because it's high cd (15 secs)
I am too lazy to test it for long 40-50 time and check the proc chance.

10 times Holy Wrath it procced 7 times on 6-7 targets. - 70% chance.

**Comment by Renehadox** [comment]
It has 15% chance per hit not per cast, so if there are like 10 targets it has 15% chance on each hit of them, stop trying to nerf ret paladins and boost mages ferals and hunters, thank you.

**Comment by VincentADK** [comment]
Phyre posted a video on our discord, please have a look. I hope this helps: https://discord.com/channels/1040715551531618365/1040715552227872809/1168604587092103239

**Comment by Renehadox** [comment]
@UltraNix 
@Afgann 
This was fixed before am  i right?

I am doing rdfs lately and divine storm now only procs 1 time it doesn't matter if it hits 10 or 15 targets it procs only 1 time.
So this bug report should be dismissed.

**Comment by Sketish** [comment]
Stop tagging all devs. Its proccing per cast not per hit

**Comment by UltraNix** [comment]
Fixed.
It supposes to proc per cast, not per hit.
In addition to that, you need to hit something.
