### ISSUE TITLE
2 set bonus resilence stack

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4633]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
2 set pvp bonus+400 resilence for heal stack with other same bonus set for dps +400 resilence

**How to reproduce:**
equip dps and heal pvp set 2/4

**How it should work:**
bonus set for dps and same for heal (2 bonus ) should not stack with same with other set. 

**Database links:**
https://wowpedia.fandom.com/wiki/Ruthless_Gladiator%27s_Mail_Leggings
"(2) Set: Increases Intellect by 70.
(2) Set: +400 Resilience Rating."
with same for heal and etc for other classes who have different sets for heal and dps.

**Comment by Sketish** [comment]
Provide any source that they shouldnt stack

**Comment by mipanka** [comment]
4.2.0 patch notes. I later will give link

**Comment by whothatdog** [comment]
https://cata-twinhead.twinstar.cz/?issue=2861
http://us.battle.net/wow/en/blog/2993743#items 4.2

**Comment by UltraNix** [comment]
Tested with shaman enh + ele sets. Resi bonus does not stack right now.

**Comment by mipanka** [comment]
> Tested with shaman enh + ele sets. Resi bonus does not stack right now.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/614c517c-8834-4fcd-a3c5-8598e3c0e877)
with 2 sets
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/d684bdc4-407f-41af-852f-76f99ccfbf80)
1 set
We tested with ele+heal sets

**Comment by UltraNix** [comment]
1 piece:
![WoWScrnShot_092923_120735](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/77cc2dd8-07bc-4759-90e1-c56af4421114)

2 piecies:
![WoWScrnShot_092923_120741](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9896ae0d-bcca-4173-8b7b-924dd2485b73)

3 piecies:
![WoWScrnShot_092923_120754](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/8ca3627e-6d37-46be-9f87-31ec15f05d4f)

4 pieces:
![WoWScrnShot_092923_120805](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f9a3c786-c00e-4296-adf5-cd513a5e7fb7)

179 + 173 + 400 (bonus) + 304 + 287 = 1383

**Comment by mipanka** [comment]
If all fine, why dmg was reduction. We tested two times and all time same result.
