### ISSUE TITLE
Retribution Paladin Divine Purpose Proc off Divine Storm and Holy Wrath

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4636]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Divine Purpose can proc from Divine Storm or Holy Wrath even when not in combat, or without any targets being hit. Based on the tooltip, this should be accurate.

**How to reproduce:**
I just did a test, casted 6 holy wraths and 24 divine storms, i got 0 divine purpose procs.

it should be upon spell cast not spell hit.

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#https://github.com/gamefreedomgit/Maelstrom/issues/3088 ?

**Comment by bonfax4** [comment]
![3361e12d142085687b7139d30adf9841](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0303e7d5-40ed-454a-827c-5f018312ea45)

**Comment by UltraNix** [comment]
Thx @bonfax4
