### ISSUE TITLE
Borean Tundra bugged quest

### ISSUE THREAD

**Issue by y3vnai** [gamefreedomgit/Maelstrom#4638]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** the quest "Monitoring the Rift Cleftcliff Anomaly" in Borean Tundra doesn't work even when using the quest item in the correct location 

**How to reproduce:** standing in the exact locations  (34,42) and using the "Arcanometer" item produces "Requires Clefcliff Anomaly" message.

**How it should work:** using the item while standing on the purple zone should give the correct reading and finish the quest.

**Database 

> links:** https://www.wowhead.com/wotlk/quest=11576/monitoring-the-rift-cleftcliff-anomaly#comments

**Comment by Waroxx-QA** [comment]
Duplicate - #3071
