### ISSUE TITLE
Hand of Gul'dan Quest does not work

### ISSUE THREAD

**Issue by Bunz123** [gamefreedomgit/Maelstrom#4639]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
Hi I am trying to do the Hand of Gul'dan quest line in Shadowmoon valley and it is not working. As soon as you turn in the quest there are no more quests to be had. The next quest in the chain should be Enraged Spirits of Fire and Earth. The NPC does not offer any quests past The Hand of Gul'dan.

**How to reproduce:**
---

**How it should work:**
The next quest in the chain should be Enraged Spirits of Fire and Earth. The NPC does not offer any quests past The Hand of Gul'dan.

**Database links:**

https://www.wowhead.com/tbc/quest=10680/the-hand-of-guldan

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
