### ISSUE TITLE
[Warlock][Item] Petrified Pickled Egg

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4640]
**Description:**
The trinket should not proc for Warlock via Fel Synergy, Syphon Life, Haunt, Harvest etc. 
Maybe it should work with Health funnel (pet) but I am doubt about it.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/121ae4ea-0066-413c-b561-3467e68d6a5d)

**How to reproduce:**
Use some warlock abiltiies on Dummy / NPC etc.

**How it should work:**
Should not proc for Warlock.

**Database links:**
1. https://www.wowhead.com/item=71336/petrified-pickled-egg#comments
"No passive Warlock heals seem to proc this trinket. It does not proc from Siphon Life, Drain Life or 2pc T5. Fel Synergy was untested but that seems very unlikely to work if 2pc T5 does not. Probably not very good for a warlock since it seems the proc will never be up."
"haunt doesn't even come up as a self heal in recount and stuff its the target healing you :-/ "

2. https://www.mmo-champion.com/threads/982342-petrified-pickled-egg-for-locks

on both links they mention it proc for warlock on 'last year' => old cataclysm patch (the item added on 4.2.0)
Whitemane are using 4.3.4 patch game, the trinket should not work for Warlock in 4.3.4 ;-)

* -- Note:
I can't test it on Twin** ptr they don't have that item on vendors.
Fixing it is really up to you, I can't provide more sources.

**Comment by Pornoodemon** [comment]
https://cata-twinhead.twinstar.cz/?spell=28176
But what about the effect of direct healing from Fel armor?

**Comment by Pornoodemon** [comment]
0 | By mooshimanx (7,239 – 2·12·43) on 2011/09/23 (Patch 4.2.2)I don't know if there's a bug or something, but I have this trinket on my Holy Paladin and it does not proc at all, no matter what I do. I've cast hundreds of spells and never seen it proc even once. | By mooshimanx (7,239 – 2·12·43) on 2011/09/23 (Patch 4.2.2) |   |  
-- | -- | -- | -- | --

**Comment by UltraNix** [comment]
`The last year's version was able to proc from [(Spell #55503)](https://www.wowhead.com/spell=55503) as well as from warlock self-heals, but as you don't cast these heals as often as a healer heals, I wouldn't rely on it to proc ;) This year's trinket and its spell look identical, just with better stats.`
From the same link from wowhead.

**Comment by Pornoodemon** [comment]
spamro on 2011/09/21 (Patch 4.2.2)
Can't get proc with Drain Life while 100% health.

Judging by the comments, this trinket worked and did not work for the same classes at the same time. Perhaps just because the test was carried out with 100% health.
I think the point of this comment is that if a warlock has less than 100% health, then the trinket should work, perhaps similarly for other classes.

This would explain this comment, why it does not work for the paladin.

**Comment by whothatdog** [comment]
> `The last year's version was able to proc from [(Spell #55503)](https://www.wowhead.com/spell=55503) as well as from warlock self-heals, but as you don't cast these heals as often as a healer heals, I wouldn't rely on it to proc ;) This year's trinket and its spell look identical, just with better stats.` From the same link from wowhead.

that spellid is Lifeblood (haste boosting) probably what they meant to say it stack with it, not proc by it.
Lifeblood is not any kind of 'heal' spell anyway.

> spamro on 2011/09/21 (Patch 4.2.2) Can't get proc with Drain Life while 100% health.
> 
> Judging by the comments, this trinket worked and did not work for the same classes at the same time. Perhaps just because the test was carried out with 100% health. I think the point of this comment is that if a has less than 100% health, then the trinket should work,
> 
> This would explain this comment, why it does not work for the paladin. This even makes sense so as not to waste the proc before the boss fight as a result of applying healing buffs and so on.

from what I know:
**healing** proccable trinkets unlike clickable trinkets can proc when healer is doing overhealing (=100% hp)
We see it everytime people stand in like Stormwind or Orgrimmar and heal and their trinkets proc.

tbh I am not so much into wowhead comments but If it did not proc with 100% health on drain life, it perhaps should not proc from it at all.
I just remember (I played long time ago, I hope my memory is not betraying me) on Twin** warlocks are not used this trinket it not worked for them.

**Comment by SimonBpvp** [comment]
> > `The last year's version was able to proc from [(Spell #55503)](https://www.wowhead.com/spell=55503) as well as from warlock self-heals, but as you don't cast these heals as often as a healer heals, I wouldn't rely on it to proc ;) This year's trinket and its spell look identical, just with better stats.` From the same link from wowhead.
> 
> that spellid is Lifeblood (haste increase) probably what they meant to say it stack with the trinket which also grant haste - not proc by it. Lifeblood is not any kind of 'heal' spell anyway. Also, be aware of 'last's year version' it's probably old version of egg and **not** the 4.3.4 one.
> 
> > spamro on 2011/09/21 (Patch 4.2.2) Can't get proc with Drain Life while 100% health.
> > Judging by the comments, this trinket worked and did not work for the same classes at the same time. Perhaps just because the test was carried out with 100% health. I think the point of this comment is that if a has less than 100% health, then the trinket should work,
> > This would explain this comment, why it does not work for the paladin. This even makes sense so as not to waste the proc before the boss fight as a result of applying healing buffs and so on.
> 
> from what I know: proccable **healing** trinkets unlike clickable trinkets (which ofc work by click ;-)) can proc when healer is doing overhealing (=100% hp) We see it everytime people stand in like Stormwind or Orgrimmar and heal and their trinkets proc.
> 
> tbh I am not so much into wowhead comments but If it did not proc with 100% health on drain life, it perhaps should not proc from it at all. I just remember (I played long time ago, I hope my memory is not betraying me in this case) on Twin** warlocks are not used this trinket it not worked for them.
> 
> I made some search on google to verify it and posted it in the links at #1 opener message.

Lifeblood does heal you a little bit actually

**Comment by whothatdog** [comment]
I done some tests on Twin**, If you want to take what they implements on server it's up to you.
or take the links I brought on first message.

on Twin** the Egg proc **only** from **Drain Life**.
in my opinion that's incorrect.

the egg probably proc only from heals you can cast/apply on someone else.
like drain life, harvest are self-healing and you can't use them to heal others.

Drain Life:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/3c3a1236-1d8b-479c-bcc1-8202d5d50f2f)

Harvest:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/75454c9e-fe91-4c68-bff4-300999ebcb84)

Damaging (Fel Synergy, Siphon Life, Haunt):
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/a88dd0d5-57b3-4c8c-912c-8dd557fc3804)

Note:
I damaged dummies to 3 million
all tests done with waiting of like 1 minute between to make sure trinket is ready.

Again, it is up to you but the trinket is according to what I know and found on searching is not proccable for Warlock.

on Whitemane it also proc from Recuperate(Rogue) but it's seems unlikely that Rogue will use it because it provide Intellect bonus.
And probably for any class even for Death Knight using Death Coil.
