### ISSUE TITLE
Black Diamond and Pristine Black Diamond do not drop at all

### ISSUE THREAD

**Issue by speelloare** [gamefreedomgit/Maelstrom#4641]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
The drop chance of 2 items is bugged or non-existent as they do not drop at all after hundreds and hundreds of mobs in BRD. Im talking about the Black Diamond item which has about 4-5% drop in BRD from all mobs. I must have killed like a thousand by now and nothing. There is also nothing on the AH. Same thing I believe is happening with the 2nd item - Pristine Black Diamond. Can you please check this and confirm? Thank you!

**How to reproduce:** 

**How it should work:**

**Database links:**

**Comment by SexyPancake** [comment]
As I was trying to tell you yesterday, those items are extremely rare to drop in cataclysm. Not sure which tables you are using to check that information as the highest drop rate from regular mob is 3% for Black Diamond and almost null for the pristine version.

https://cata-twinhead.twinstar.cz/?item=11754
https://cata-twinhead.twinstar.cz/?item=18335

You can also see many comments about how terrible the droprate was in cataclysm on wowhead : 
https://www.wowhead.com/item=11754/black-diamond#comments
https://www.wowhead.com/item=18335/pristine-black-diamond#comments

**It's quite possible that the Black Diamond is scuffed but I wouldn't say the Pristine version is right or wrong**

**Comment by speelloare** [comment]
Thank you for looking into it even though after a lot more research i've discovered that the content these gems were used for is obsolete in cata now which is a shame as I wanted those arcanum enchants for the head and pants heirlooms :D
