### ISSUE TITLE
Loot not added to inventory on pickup

### ISSUE THREAD

**Issue by Sylian1337** [gamefreedomgit/Maelstrom#4642]
**Description:**
I noticed that when fishing for Volatile Fire & Volatile Water, when I get the loot from fishing, it doesn't always give me the loot even when it tells me in chat that I got the items, but they aren't added to my bag/stack.

**How to reproduce:**
Simply fish in Mount Hyjal, pool of fire for drops of Volatile Fire.

**How it should work:**
I should get the items I loot.

**Database links:**
https://www.wowhead.com/item=52326/volatile-water
https://www.wowhead.com/item=52325/volatile-fire

**Comment by Sketish** [comment]
It's added to your inventory when its looted so please record this issue

**Comment by UltraNix** [comment]
@Sylian1337 Still happens?

**Comment by UltraNix** [comment]
No further info - closing.
