### ISSUE TITLE
[Achievment] Ready for Raiding II - Devout Harbinger no kill credit

### ISSUE THREAD

**Issue by jionyh** [gamefreedomgit/Maelstrom#4643]
**Description:**
I've been trying to complete this achievement for devout Harbinger for two days, but I think it's bugged. I've tried it in groups and solo and even without taking damage not get kill credit.

**How to reproduce:**
Just accept the quest and take damage from the creeping inferno.

Screenshot proof
https://imgur.com/a/6UA5zbl

**Database links:**
https://www.wowhead.com/achievement=5873/ready-for-raiding-ii#comments

**Comment by UltraNix** [comment]
Fixed.
