### ISSUE TITLE
[Ragnaros][Heroic] Spreading of Dreadflames

### ISSUE THREAD

**Issue by xHAGENx** [gamefreedomgit/Maelstrom#4645]
**Description:**
On last phase of ragnaros heroic dreadflames can spread on bridge or beyond the platfrom.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/90351303/a58f7d53-20ec-4f7f-838a-581f29b9b3c2)

**How to reproduce:**
Just start p4 of rag hc and dont wipe before flames spread.

**How it should work:**
Dreadflames should sprad only on platform where we fight with rag. It shouldn't spread on bridge or beyond the platform.

**Database links:**

https://www.wowhead.com/spell=100675/dreadflame

**Comment by UltraNix** [comment]
Fixed.
