### ISSUE TITLE
Molten Front, warlock pets do not attack players

### ISSUE THREAD

**Issue by Shrutasena** [gamefreedomgit/Maelstrom#4646]
**Description:**
Molten Front 1st phase, warlock demonology.
In Molten Front, my pet cannot attack or use abilities against other players. 
Even when they attack me. 
Everything is fine against mobs. I have not been to the sanctuary area.
Maybe it's just me who has the problem, my nickname Linden.

**How to reproduce:**
Try pressing an attack or ability with the mouse or keyboard

**How it should work:**
The warlock's pets must attack

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=688
https://cata-twinhead.twinstar.cz/?spell=697
https://cata-twinhead.twinstar.cz/?spell=30146
https://cata-twinhead.twinstar.cz/?spell=712
https://cata-twinhead.twinstar.cz/?spell=691

**Comment by Pornoodemon** [comment]
Your pet may be in Do Not Act mode

**Comment by Shrutasena** [comment]
Of course, this didn't help.

**Comment by UltraNix** [comment]
@Shrutasena Do you have any screenshots?
The starting area in Molten Front is a sanctuary.

**Comment by UltraNix** [comment]
Fixed.
