### ISSUE TITLE
Arcane Blast is snapshotting it's mana cost at the start of the cast instead of when the cast is completed.

### ISSUE THREAD

**Issue by TheHate123** [gamefreedomgit/Maelstrom#4648]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Arcane Blast is snapshotting the mana cost that it had when you started casting the ability and not when you finished the actual cast.

**How to reproduce:**
Press Arcane Blast with multiple charges of Arcane Blast (debuff) and see how it eats more mana than it should.

https://www.youtube.com/watch?v=evxkWbI0z8M

**How it should work:**
Like any other ability in the game, it should check for mana cost once the cast finishes and not when you start casting it.

https://youtu.be/VWf_fYfXTwE?si=xfz3N-5GFJBgkCeZ&t=229 -> After his Evocation, he will start casting an Arcane Blast with 4 stacks up, they drop mid-cast and his Arcane Blast eats only 0.7% of his mana, which is a 0 stack Arcane Blast's cost.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=30451

**Comment by UltraNix** [comment]
Fixed.
