### ISSUE TITLE
Double summon bug 

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4649]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you double summon a guy with summoning stone (warlock) then it won’t work

**How to reproduce:**
Get 3 guys in party. Warlock make a stone, 2 of you both cast summon on the same 3rd guy. 3rd guy try to click it. It fails. 

**How it should work:**
Allow him to accept the summon anyway. 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
