### ISSUE TITLE
Alchemy doesn't give you +80

### ISSUE THREAD

**Issue by twiftxd** [gamefreedomgit/Maelstrom#4650]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
flask of enhancement doesn't add on-to any other main-stat flask, like it's supposed to

**How to reproduce:**
have alchemy, click flask, only 300 intellect given pikachu face

**How it should work:**
alchemy is supposed to give a flask of enhancemnet, which it does, that gives you +80 intellect, usable in pvp. this does not stack with say, flask of draconic mind. due to the nature of it not stacking, and not adding +80(380) intellect when all the boxes are checked, it's a literal waste of a profession slot.

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/dde8a254-9ea9-4d1b-8d74-02dd9ffa89ae)

**Comment by SimonBpvp** [comment]
+1 it is a waste of a proff slot if you pve

**Comment by Revly** [comment]
Traslate Google: 
It should be possible to have +80 and +300

But never
2 enhancement flaks, for example
Jar of 40 and Jar of 80 together,
You can only flaks this way
40+300
80+300
And for the inscription scrolls it would be the same.

**Comment by whothatdog** [comment]
On Twin** you cannot use +300 stat flask and +80 stat flask (Flask of Enhancement)
Alchemy users have to cancel their FoE to use +300 stat flask.

the message from 4.0.3 is irrelevant, the message from 4.3.4 is more relevant and updated. (and accurate)

Alchemy users lose +80 stat bonus, they get +300 like everyone else.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/83f44490-c643-4a48-9217-111381fcb1ce)

**Comment by whothatdog** [comment]
On Twin** you cannot use +300 stat flask and +80 stat flask (Flask of Enhancement)
Alchemy users have to cancel their FoE to use +300 stat flask.

the message from 4.0.3 is irrelevant, the message from 4.3.4 is more relevant and updated. (and accurate)

Alchemy users lose +80 stat bonus, they get +300 like everyone else. 

twin** test
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/228c3103-698f-4c2c-83dd-f0cf5ca6c7d2)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/f4d35a7f-d28b-4c38-98e0-9fdb7093c165)

https://www.mmo-champion.com/threads/1148768-Alchemy-bonus

**Comment by xHAGENx** [comment]
Alchemy is one of the best profesion coz is giving you +80 stat and make ur flask longer and its not useless like other profesions coz u can craft some pots or flasks
![image](https://github.com/gamefreedomgit/Maelstrom/assets/90351303/f4958954-0cca-4378-943e-e0bb390937cc)

**Comment by xHAGENx** [comment]
Topic to close, everything working ok.
