### ISSUE TITLE
Cant reforge gear

### ISSUE THREAD

**Issue by Pashie32** [gamefreedomgit/Maelstrom#4651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cant reforge any gear, tried relogging, restarting game, restarting PC and deleting cache
Talked to GM nightmare
**How to reproduce:**
No clue

**How it should work:**
Remove some points from stats on gear, and make another state apper

**Database links:**

![reforge](https://github.com/gamefreedomgit/Maelstrom/assets/146573361/21f4805a-b6d8-495b-aefd-e5f65f909740)

**Comment by Revly** [comment]
If use /reload 
Can fix u problem before of reforge

**Comment by xHAGENx** [comment]
Problem was always on every server where I played /reload should help
Or just use addon reforge lite, even if u have that bug. That addon is changing reforges without any problems

**Comment by Pashie32** [comment]
well /reload, relogg, restart game, restart computer didnt work.. disabled all addons didnt work. changed char *repeat*

**Comment by xHAGENx** [comment]
Maybe try delete cache addon

**Comment by xHAGENx** [comment]
[ReforgeLite-v1.10.zip](https://github.com/gamefreedomgit/Maelstrom/files/12775677/ReforgeLite-v1.10.zip)
If that wont work I dont have idea what more u can do.
I send you reforge lite its great addon.
U set here for every stat prio + u can add caps and new value of stat if u raeach that cap
for example you wanna hit cap so u put most value on hit, set cap on 961 (8%), prio after reaching cap = 0
U have some ready profiles with values for classes but they are not the best

**Comment by Sketish** [comment]
It look's like addon/ui issue try reforging with all addons disabled,

**Comment by Waroxx-QA** [comment]
It's a client issue, Reload / relogging can fix it, if it doesn't, try to disable all your addons.
If the problem persists you'll have to install a new client.
