### ISSUE TITLE
Lance Rack Argent Turnament not giving a lance

### ISSUE THREAD

**Issue by CumanPV** [gamefreedomgit/Maelstrom#4654]
**Description:**
The user cannot equip a lance from the Lance Rack at the Argent Turnament, thus cannot continue 3 quests to gain reputation.

**How to reproduce:**
Go to the Argent Turnament Grounds, Icecrown, find a Lance Rack located near the stables or inside the faction tent and click on it.

**How it should work:**
When clicking the Lance Rack, a lance should appear in your inventory.

**Database links:**
https://www.wowhead.com/wotlk/item=46106/argent-lance
https://www.wowhead.com/wotlk/item=46069/alliance-lance
https://www.wowhead.com/wotlk/item=46070/horde-lance
https://www.wowhead.com/wotlk/quest=13828/mastery-of-melee (one of the quests)

**Comment by frostwave942** [comment]
The Tournament itself doesn't work correctly, at least for me i'm stuck in: <a href="https://cata-twinhead.twinstar.cz/?quest=13678">Up to the Challenge</a>, after taking that quest i can't take the dailies to farm aspirant seals to continue.

**Comment by PanJanuszek** [comment]
fixed 21.03.2024
