### ISSUE TITLE
Digsitte error

### ISSUE THREAD

**Issue by Pashie32** [gamefreedomgit/Maelstrom#4655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Digsite artifact is under the ground
Eastern plaugelands cords: 11,22
**How to reproduce:**
Go to the zone and survey

**How it should work:**
not be under the ground 

**Database links:**
![bild_2023-10-01_071132081](https://github.com/gamefreedomgit/Maelstrom/assets/146573361/349f818d-669d-492c-aa1f-6eaa8c0e650b)

**Comment by frostwave942** [comment]
i found some digsites in the air just like this

![Digsite-Error2](https://github.com/gamefreedomgit/Maelstrom/assets/146029129/3c9a3596-8ea6-44d7-acb5-889ec78571fa)
(found in Nazj'Vel, Darkshore, Kalimdor)

**Comment by UltraNix** [comment]
@Pashie32 That screenshot is too little :) Give us a bigger one and a map.

**Comment by UltraNix** [comment]
No further info - closing.
