### ISSUE TITLE
Ragnaros meteor combustion

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#4656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The combustion debuff that stacks on the player who knocks the meteor does not stacks damage taken

**How to reproduce:**

keep knocking the meteor and stacks the debuff as much as you can, you'll take only 2k per tick.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/2def646d-8915-43e0-b587-8ae3719b5fd0)

**How it should work:**

Damage taken from combustion should be increased for each stack of the debuff the players has

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/d341ce00-1659-4956-aaa3-416373824c66)

**Comment by UltraNix** [comment]
Fixed.
