### ISSUE TITLE
Eye of Eternity (10m) Bugged

### ISSUE THREAD

**Issue by lishpeth** [gamefreedomgit/Maelstrom#4657]
**Description:**
Eye of Eternity (10m) boss Malygos is unkillable. The fight's third phase is not scripted and bugs out. The boss flies high when he has less than %50 hp and becomes untargetable after the second phase. 

**How to reproduce:**
Attack Malygos till his hp drops below %50.

**How it should work:**
Phase 1 and phase 2 are working well, even though the disks are bugged, you can kill the Npcs flying around by bringing a caster DPS player with you. But even after killing all the NPCs, phase 3 doesn't start and the boss becomes unreachable and untargetable.

**Database links:**   https://www.warcrafttavern.com/wotlk/guides/eye-of-eternity-10/

**Comment by PanJanuszek** [comment]
fixed 20.05.2024
