### ISSUE TITLE
[Core][Summon] Have Group, Will Travel in Baradin Hold

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#4659]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Have Group, Will Travel (Guild Perk Summon) doesn't work inside the Baradin Hold Raid instance.

**How to reproduce:**
Enter Baradin Hold on 10 or 25man and try to use Have Group, Will Travel.

**How it should work:**
It should be usable (inside the raid) if you use it nearby the entrance.

**Database links:**

**Comment by Sketish** [comment]
Pleasr provide any source it should work inside tol barad.

**Comment by Whatisthisclass** [comment]
As you can see from the title and description, I am talking about Baradin Hold which is a Raid instance, not Tol Barad.

**Comment by Sketish** [comment]
That's what I meant  Baradin Hold Raid instance. Not sure if mass summon was working on retail inside pvp zone but UltraNix fixed that issue

**Comment by UltraNix** [comment]
Fixed.
