### ISSUE TITLE
[Achievement] To All the Squirrels who Cared for Me - Missing Critter

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4661]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

There are no <a href="https://www.wowhead.com/npc=48706/highlands-turkey">Highlands Turkey</a> or other critter in Vermillion Redoubt, Twilight Highlands needed for this achievement.

**How to reproduce:**

justo go to vermillion redoubt in twilight highlands.

**How it should work:**

Highlands Turkey and other critters should be there.

**Database links:**

https://www.wowhead.com/achievement=5548/to-all-the-squirrels-who-cared-for-me#comments

**Comment by PanJanuszek** [comment]
fix after reset
