### ISSUE TITLE
Orgrimmar wood signals in the middle of the way

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#4662]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is 2 signs in the middle of way and i believe they are part of the old Orgrimmar.

**How to reproduce:**
Walk from the valley of Wisdom to the valley of strenght, or viceversa does not matter from which side you come from.

**How it should work:**
There should be no signals in the middle of the way in Orgrimmar

**Database links:**
Trying to find the signal id, but it could not.
https://i.gyazo.com/dc53e5222b3038bbdf2a0dcbc3d9ab8f.jpg
https://i.gyazo.com/4f3836a539ff7a250583cd8e5f674739.jpg

**Comment by Afgann** [comment]
fixed
