### ISSUE TITLE
Dragon's Wrath, Tarecgosa's Last Rest - Balance Druid

### ISSUE THREAD

**Issue by Iflux313** [gamefreedomgit/Maelstrom#4663]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The legendary staff (Dragon's Wrath, Tarecgosa's Last Rest) doesn't seem to trigger a proc at 100 casts (Starfire/Wrath/Starry Suck). That should be 10 spells each with a proc chance of ~10%. DoTs work without any problems. Please check the damage spells on the Balance Druid (Starfire, Wrath, Starsog, Star Rain, Typhoon and Wild Mushroom:Detonate) that they can also correctly trigger the proc (Wrath of Tarecgosa).

**How to reproduce:**
Cast each Spell at least 100 times and Check if it procs.

**How it should work:**
According to a Retail Post(see link), all damage spells should be duplicated. With a proc chance of about 10%, but the proc is not triggered correctly by all spells.

**Database links:**
https://www.wowhead.com/guide/raiding/guide-to-dragonwrath-tarecgosas-rest#heartofflame-step-1-smouldering-essences

**Comment by Sketish** [comment]
Druid has 8% chance to proc and its for all spells.
