### ISSUE TITLE
be unable to sell one's goods to an auctioneer.

### ISSUE THREAD

**Issue by shinminhojjang** [gamefreedomgit/Maelstrom#4664]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
be unable to sell one's goods to an auctioneer
If you sell more than 21 at a time, you can't sell things

you've reached daily auction limit. 

**How to reproduce:**

**How it should work:**

**Database links:**

![대격변 error](https://github.com/gamefreedomgit/Maelstrom/assets/146730057/653e4d3b-792a-4213-94dd-2b1cc4c99d19)

**Comment by Sketish** [comment]
There is limit to auctions players can post
