### ISSUE TITLE
Lillehoff (Sons of Hodir Quartermaster) NPC missing (Quest chain needed to be done for the NPC to be visible, delete this)

### ISSUE THREAD

**Issue by CumanPV** [gamefreedomgit/Maelstrom#4665]
https://www.wowhead.com/wotlk/npc=32540/lillehoff

**Description:**
The NPC Lillehoff is missing in Dun Niffelem, The Storm Peaks thus making it impossible to buy reputation goods.

**How to reproduce:**
Go to Dun Niffelem in The Storm Peaks, Lillehoff should be located on the 3rd step but he is not.

**How it should work:**
Lillehoff should be present on the 3rd step in Dun Niffelem, The Storm Peaks

**Database links:**
https://www.wowhead.com/wotlk/npc=32540/lillehoff

![Screenshot_294](https://github.com/gamefreedomgit/Maelstrom/assets/146593442/75883cc2-33c1-4847-866b-e20bdd8d0866)
![Screenshot_295](https://github.com/gamefreedomgit/Maelstrom/assets/146593442/66b58df3-484a-45e9-98ad-b1ddacc3c4d9)

**Comment by Mona-Chi** [comment]
Are you sure you finished the quest line to unlock the npc?
For me the npc is right there and working.

![sonofhodirnpc](https://github.com/gamefreedomgit/Maelstrom/assets/147038298/47eed0aa-952d-46aa-b936-a558ea9001c5)

**Comment by CumanPV** [comment]
All good! :D

**Comment by PanJanuszek** [comment]
not an issue
