### ISSUE TITLE
Hunter bugged pets

### ISSUE THREAD

**Issue by Zipper1996** [gamefreedomgit/Maelstrom#4666]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/npc=11727/hivezora-wasp
https://www.wowhead.com/tbc/npc=23353/braxxus
[//]: # (cata-twinhead.twinstar.cz)

**Description:** If these 2 beasts linked above are tamed by a hunter, they will keep their abilities even as a hunter pet and they should not.
The wasp shouldn't have the Poison ability.
The core hound shouldn't have Panic, Double Breath and Mangle abilities.

**How to reproduce:**
![WoWScrnShot_100223_211919](https://github.com/gamefreedomgit/Maelstrom/assets/133601328/f2b4446f-c763-4537-8215-484ab5523f82)
![WoWScrnShot_100223_211927](https://github.com/gamefreedomgit/Maelstrom/assets/133601328/5abe6182-74f1-4546-9d79-5c1ae2d79d01)

**How it should work:**

**Database links:**

**Comment by frostwave942** [comment]
another bug that happens to any class with a pet is that if the pet gets the last hit (without owner intervention), the owner won't receive loot, reputation, credit for quests, achievements, etc. also if the owner mounts and dismounts a flying mount repeateadly, the pet's action bar will be disabled and it will be unable to attack.

**Comment by UltraNix** [comment]
@frostwave942 New report please.

**Comment by UltraNix** [comment]
Fixed.
