### ISSUE TITLE
[Raid][Firelands] Alysrazor reset takes too long

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#4668]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Wiping on Alysrazor won't instantly reset the encounter, it keeps going on for about 1-2minutes before it resets.

**How to reproduce:**
Wipe on alysrazor, and don't release spirit, watch the encounter going on.

**How it should work:**
Instantly reset the encounter.

**Database links:**

**Comment by Revly** [comment]
Bethilac same

**Comment by UltraNix** [comment]
Fixed.
