### ISSUE TITLE
Deepholm npcs not interactible to turn in quests

### ISSUE THREAD

**Issue by CarlHelberg** [gamefreedomgit/Maelstrom#4669]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing quests Intervention , Making Things Crystal Clear and Putting the Pieces Together, the quest giver can not be interacted with. They are yellow name plate NPCs and can be attacked, in Druid flight form the message appears "cannot attack while pacified".
The quest givers are Berracite and Kor the Immovable

**How to reproduce:**
Alliance lvl 84 Druid. Complete quests.

**How it should work:**
Quest giver should not be attackable, but you should be able to speak to them to turn in quests.

**Database links:**

**Comment by CarlHelberg** [comment]
Logging out and in does not help.
Exiting the game completely and re entering does not help.
Killing the NPCs and waiting for a respawn does not help.

**Comment by Sketish** [comment]
Make sure you not have at war with theraze faction

**Comment by CarlHelberg** [comment]
Thanks, that was the issue! I noticed there were 2 other people, 1 horde and 1 alliance that also attacked the npcs. 
Not sure if this was a server side bug or if we all did the same quest that triggered the at war status.
thanks again :)
