### ISSUE TITLE
"Surrender, or Else!" Goblin Starting Zone quest is bugged

### ISSUE THREAD

**Issue by Kythra6** [gamefreedomgit/Maelstrom#4670]
The "Faceless of the deep" mob at the end of the quest regenerates to full health instantly after taking any damage and then disappears after a while without giving quest credit, thus making it incompletable and entirely blocking me from completing the goblin intro.

**Comment by fishpoppin** [comment]
make sure you are following the NPC to the boss, otherwise quest can bug, just abandon and pick back up, then follow ACE to the boss

**Comment by Kythra6** [comment]
Following the NPC results in the same bug occurring, the quest is bugged regardless of how you try to do it

**Comment by UltraNix** [comment]
Fixed.

**Comment by thone32** [comment]
I am also having this bug happen to me
