### ISSUE TITLE
NETHERWEAVE BAGS ARE NOT WORKING

### ISSUE THREAD

**Issue by fishpoppin** [gamefreedomgit/Maelstrom#4671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

16slot netherweave bags are not working on my character. i can equip them but they do not open, even when manually clicking the bag to try and open the bag, it does not open,

https://www.wowhead.com/item=21841/netherweave-bag

**Comment by Revly** [comment]
If  /relog should work

**Comment by fishpoppin** [comment]
> If /relog should work

this actually worked, cant believe i didnt try that yet, i tried /reload but that didnt work, tysm!
