### ISSUE TITLE
Warlock pet control panel

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4672]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Something strange has been happening to the pet's panel for the last two days.
After resummon the pet, the follow mode disappears every once in a while.

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/61ac3c1a-aed2-489d-9d89-5d7c8e46440b

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/440077ab-d3f6-428d-b643-6ca2739e4839

Although the pet continues to follow, in battle it can stop in place and stand,

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
