### ISSUE TITLE
Another Bugs in Pets 

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

another bug that happens to any class with a pet is that if the pet gets the last hit (without owner intervention), the owner won't receive loot, reputation, credit for quests, achievements, etc. also if the owner mounts and dismounts a flying mount repeateadly, the pet's action bar will be disabled and the pet will be unable to attack.

**How to reproduce:**

for eg a hunter kill some mob only with his pet, this mob won't grant loot, repu, etc. (any class with a pet can check this) and the other issue just mount and dismount a flying mount repeatedly.

**How it should work:**

i hope if the pet kills any mob the owner can loot them, get the repu, etc. and after dismount from a flyng mount the pet's action bar should always be active.

**Database links:**

well <a href="https://www.youtube.com/watch?v=eFC02zPD-hI">this</a> happens if u kill any mob ony with ur pet,
if ure trying to farm repu in <a href="https://www.youtube.com/watch?v=vcjkldX2ZaM">dungeons</a> or if ure trying to complete some <a href="https://www.youtube.com/watch?v=2u1yIVhFLss">achievement</a>.

and this the <a href="https://www.youtube.com/watch?v=nu8BhqrWwYg">bug</a> with flying mount

these bugs apply to all classes with pet.

**Comment by Sketish** [comment]
Provide any proof for that

**Comment by whothatdog** [comment]
that incorrect.
I just tested it with a Hunter.
it only occur if the pet kill NPC without single hit from the Player itself.

I tested it few times
hitting NPC to like 40% -> stop attack -> let pet finish the NPC lone = loot appear.
let pet hit NPC to like 40% -> stop pet attack -> I finished NPC lone = loot appear.

the only bug I noticed right now is if you're mounted, enter to combat, dismount
the pet bar is inactive.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/ad328f91-ec72-4b78-b0ef-8deadd166d82)

**Comment by UltraNix** [comment]
`the only bug I noticed right now is if you're mounted, enter to combat, dismount
the pet bar is inactive.`
Can you record it as I can't reproduce it the way you described it?

**Comment by UltraNix** [comment]
@frostwave942 
`and after dismount from a flyng mount the pet's action bar should always be active.`
As I know, flying mounts should despawn your pet.

**Comment by UltraNix** [comment]
So there is one question - once you used flying mount, the pet was out? And its pet bar was okay? And then pet despawned and when you dismount, pet bar was already bugged out? You can reproduce it without getting combat?

**Comment by whothatdog** [comment]
I killed a npc (pet was out helping killing a npc, bar was okay.)
then I used flying mount and moved to next mob and dismounted the pet bar is inactive as you can see.
I think it happen only if you fly mount + enter combat then dismount.

**Comment by whothatdog** [comment]
> So there is one question - once you used flying mount, the pet was out? And its pet bar was okay? And then pet despawned and when you dismount, pet bar was already bugged out? You can reproduce it without getting combat?

I killed a npc (pet was out helping killing a npc, bar was okay.)
then I used flying mount and moved to next mob and dismounted the pet bar is inactive as you can see.
I think it happen only if you fly mount + enter combat then dismount.

**Comment by UltraNix** [comment]
https://streamable.com/h7rhdq
What am I doing wrong?

**Comment by frostwave942** [comment]
> https://streamable.com/h7rhdq What am I doing wrong?

if u hit the mob (with basic or ranged attack) and then ur pet finish it off u get the loot anyway, but if only ur pet kills the mob u dont get any loot

**Comment by UltraNix** [comment]
`if u hit the mob (with basic or ranged attack) and then ur pet finish it off u get the loot anyway, but if only ur pet kills the mob u dont get any loot, repu, credit for quest, achiv, etc.`
It's not a bug. You must hit the mob.
It was question to @whothatdog

**Comment by frostwave942** [comment]
> `if u hit the mob (with basic or ranged attack) and then ur pet finish it off u get the loot anyway, but if only ur pet kills the mob u dont get any loot, repu, credit for quest, achiv, etc.` It's not a bug. You must hit the mob. It was question to @whothatdog

if it's not a bug that means the pet is like a negative thing instead of being useful to you. it's like another player steals the kill and it looks kinda weird u know.

**Comment by UltraNix** [comment]
Yes- it's not a bug.

**Comment by whothatdog** [comment]
> https://streamable.com/h7rhdq What am I doing wrong?

That you need to try it few times and it might happen. 
It not occur everytime you dismount, but there a small chance that it will happen. 
don't do something special just dismount near NPC before / after entering a combat.
the bar is going inactive you can't command the pet to attack.

tbh, it's small issue, probably won't occur in raids or dungeons anyway.
low priority in my opinion.

but just for you, more 2 clips:
https://streamable.com/rc9wjp
https://streamable.com/tb7vol

**Comment by UltraNix** [comment]
Should be okay now.
