### ISSUE TITLE
quest in deephole

### ISSUE THREAD

**Issue by ziomarlbo** [gamefreedomgit/Maelstrom#4674]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**DescriCan't complete the quest "The middle fragment" in Deepholme

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
