### ISSUE TITLE
Fear / duration issue

### ISSUE THREAD

**Issue by Krache** [gamefreedomgit/Maelstrom#4675]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fear bugged. Receiving damage does not cancel the fear 

Control spells duration length 

**How to reproduce:**
Arena battleground: during fear receiving damage did not cancel the fear

Fear time application: Duration is not decreased after fear/transformation/silence (if not, and added up: players can't play for 28 sec) 

**How it should work:**

Fear / transformation should be cancelled

Spells should be classified as "control type" with decrease time of duration on single target  

**Database links:**

**Comment by Pornoodemon** [comment]
Currently, the warlock's fear effect has a damage threshold of 40% of the base stock.
After the threshold of fear withstands 20% of the base health, then fear has a chance to break when dealing any damage.
After recasting the fear spell, Diminishing Returns appears and the damage threshold is updated.
This topic has been raised a hundred times already, along with a ton of information on this spell, and now fear works almost perfectly and it doesn't need any corrections.

**Comment by Pornoodemon** [comment]
"Fear time application: Duration is not decreased after fear/transformation/silence (if not, and added up: players can't play for 28 sec)"

These are different types of control and "Diminishing returns" are also different.

**Comment by Krache** [comment]
Thank you for your reponse

Best
