### ISSUE TITLE
Bug with quest in Terokkar Forest

### ISSUE THREAD

**Issue by Toske2302** [gamefreedomgit/Maelstrom#4676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, i have problem with quest ''The Soul of Reth'hedron'' in Terokkar Forest.
I cant take item ''Flawless Arcane Essence'' from Sar'this.

**Comment by PanJanuszek** [comment]
Fixed after update
