### ISSUE TITLE
[Firelands] Bethilac 25HC Loot

### ISSUE THREAD

**Issue by xHAGENx** [gamefreedomgit/Maelstrom#4678]
**Description:**
On whitemane quantiny of loot from heroic bosses is increased:
from 2 to 3 on 10 hc
and from 5 to 8 on 25hc
but Bethilac 25HC is still droping only 5 items.
**How to reproduce:**
Kill bethilac 25hc and check loot.

**How it should work:**
Bethilac 25hc should drop 8 items like other bosses.

**Database links:**
https://www.twitch.tv/videos/1920375381 - 0:59:00

**Comment by UltraNix** [comment]
Fixed.
