### ISSUE TITLE
[Fading Into Twilight] - achievement bug (Twilight Highlands)

### ISSUE THREAD

**Issue by reila0405** [gamefreedomgit/Maelstrom#4680]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Achievement [Fading Into Twilight] - Complete 95 quests in Twilight Highlands doesn't work and resets quest count. I had 84/95 quests today morning. I completed [Bring Down the High Shaman] quest and the count in the achievement reseted back to 80/95. It happened over and over again in the last few days.

**How to reproduce:**

**How it should work:**
It should count completed quests.
**Database links:**

**Comment by UltraNix** [comment]
@reila0405 No DCs/restart/crashes?

**Comment by UltraNix** [comment]
No further info - closing.
