### ISSUE TITLE
Arena Frames Bug

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4681]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/c4c50b9a-d503-44cb-98bd-4ac9ba8139e5)
There is a teammate on the enemy frames. This messes up the targets and focus for most arena players at the moment.

**How to reproduce:**
Join arena AFTER your teammate has summoned his pet. The pet will make him appear as an enemy on your frames. 

**How it should work:**
Only show enemy’s in arena frames

(Closed previous issue cause it was stuck on status need info)

**Comment by UltraNix** [comment]
@SimonBpvp Cannot reproduce that way you described.
First warlock entered arena, summoned his pet and then warrior entered arena - no bug with frames. The same with opponent.

**Comment by UltraNix** [comment]
@SimonBpvp After recent fixes, still happens?
