### ISSUE TITLE
Jewelcrafting Daily Bug - A Present for Lila

### ISSUE THREAD

**Issue by Akayso** [gamefreedomgit/Maelstrom#4682]
Hello, 

the Jewelcrafting daily quest "A Present for Lila" - cut Nightstones into Timeless Nightstones Cut is not working all of the sudden. I have crafted the 3 Nightstones into the Timeless Nightstone cuts but the game did not count it. I crafted 3 again and the same happened. After that I abandoned the quest and did it once more without success.

Now I have a half finished quest and 9 cuts in my inventory but can't turn in the quest. Is there an easy & quick fix for this so I can redo the quest again or could I get the quest reward " 1x Illustrious Jewelcrafter Token"?

Edit: Reloading / Relogging does not fix the issue

![JC_quest_bug](https://github.com/gamefreedomgit/Maelstrom/assets/20610520/0805dbd8-f1ef-4fb6-8f9e-786e912d3c4f)

**Comment by BalanCV** [comment]
I see from the photo that you are in a group. If that is a raid group it might explain it. Most quest conditions don't complete in raid groups.

**Comment by Mona-Chi** [comment]
Thanks, that was actually the issue. I tried everything besides leaving the party which was a Raid group xD.
