### ISSUE TITLE
Battleground kick

### ISSUE THREAD

**Issue by ald333** [gamefreedomgit/Maelstrom#4683]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
For some reason, the game kicks me and my teammates when we defend a base in a BG even when we are not AFK.

**How to reproduce:**
Just stand in a BG and defend a base.

**How it should work:**
"Vote to kick" should be the only thing that kicks a player from a BG or typing "/afk"

**Database links:**

**Comment by ald333** [comment]
Idk why you need to be in combat to stay in the BG. While there's people who go AFK or do nothing and don't get kicked. If you defend a base you will be out of combat, that's normal. Fix this.

**Comment by Afgann** [comment]
fixed
