### ISSUE TITLE
Mushroom Menagerie

### ISSUE THREAD

**Issue by Cqueen26** [gamefreedomgit/Maelstrom#4685]
Long while ago, I worked on maatparm mushroom menagerie in bloodmyst. I thought I completed the quest and thought two quest items were left due to a bug. so i destroyed them. but when I went back to check on the npc because I forgot to pick up another quest from him, it was like I never picked up the quest. this time around he only asked me for two musthrooms. but he definetly asked for more than 2. I decided to recollect the two he was asking for and was able to complete the quest. Just wondering if any bugs could pop up or generally mess something else up. Please respond if you can

**Comment by Sketish** [comment]
So whats the issue you are reporting now ?

**Comment by Cqueen26** [comment]
Hello just saw this. I guess there is no issue anymore. I think I was just worrying too much, thinking other quests and stuff would be bugged because of this. No action is needed. I do apologize
