### ISSUE TITLE
Vortex Pinacle -  [Vengeance for Orsis]

### ISSUE THREAD

**Issue by ahearneo** [gamefreedomgit/Maelstrom#4686]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Vortex Pinacle -  [Vengeance for Orsis] - This quest when you kill the boss will only drop 1 quest item regardless if 5 people have it, its happened 3 times now, is this a bugg or intentional? 

I have done a bit of googling and I havent seen anything on the old wow wikis to say this is how it worked.

**How to reproduce:**
go dung with 2 people with quest, kill boss

**How it should work:**
everyone gets quest reward for boss kill

**Database links:**

**Comment by UltraNix** [comment]
Everything work okay here with the quest.
