### ISSUE TITLE
[Event][Item]No Brew of the Month

### ISSUE THREAD

**Issue by rhez** [gamefreedomgit/Maelstrom#4687]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
No brew mailed, only a letter.
https://imgur.com/QZZIaZe

**How to reproduce:**
Purchase Brew of the Month Club Membership Form from vendor

**How it should work:**
A monthly brew should be mailed along with the letter.

**Database links:**
https://www.wowhead.com/item=37571/brew-of-the-month-club-membership-form

**Comment by Zeehra** [comment]
Can confirm. And also, getting a massive amount of mail from the Brewfest fella, the first day I got 10-12 mails and been getting one each day since. Should only be one per month.
https://imgur.com/a/0ACphLE

**Comment by UltraNix** [comment]
![WoWScrnShot_101223_200229](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/1973700c-2bed-4c2a-824b-c74d04ff3c4b)
Cannot reproduce it.
@rhez @Zeehra happens on every char that have Brew of the Month Club Membership?

**Comment by rhez** [comment]
Unfortunately I only had the one char with enough funds to buy the membership form. Will need more verification.

**Comment by Zeehra** [comment]
> ![WoWScrnShot_101223_200229](https://user-images.githubusercontent.com/80540499/274690436-1973700c-2bed-4c2a-824b-c74d04ff3c4b.jpg) Cannot reproduce it. @rhez @Zeehra happens on every char that have Brew of the Month Club Membership?

Yep, every single char that completed the quest is now getting spammed like this.

**Comment by UltraNix** [comment]
The spam is made by DCs. I mean the bug with no brews in the mail.

**Comment by Zeehra** [comment]
Server DCs? Because I'll log off one day with an empty mailbox and log in the next with 12-14 new Brewfest mails. I.e., I haven't had any DCs in that period.

**Comment by UltraNix** [comment]
Server crash/restart.

**Comment by Zeehra** [comment]
But no matter what, I shouldn't be getting spammed EVERY SINGLE DAY for all eternity on all my characters? Seriously, it's insane how much I'm getting? I got less mail spam from gold sellers when the server started lol

**Comment by UltraNix** [comment]
Okay. I did not say it's not a bug. I asked an explanation about something else...

**Comment by UltraNix** [comment]
Fixed.
