### ISSUE TITLE
Brew of the Month vendor in Orgrimmar doesn't work.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4688]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The female goblin "Brew Vendor" in Orgrimmar is supposed to sell up to 24 of the current month's brew if you have completed the brew of the month club questline, yet the vendor can not be interacted with.

**How to reproduce:**
Attempt to interact with said vendor.

**How it should work:**
The vendor should sell a limited amount of brew of the month, just like the vendor in Ironforge does.

**Database links:**

https://imgur.com/a/q3QHh16
https://www.wowhead.com/npc=27819/brew-vendor

**Comment by UltraNix** [comment]
Fixed.
