### ISSUE TITLE
Issue in WOW European server maelstrom

### ISSUE THREAD

**Issue by wildhunterJ** [gamefreedomgit/Maelstrom#4690]
Hi All 

October 5th at 4:25pm, I killed Oinax in Deep Rock Island. It was supposed to be given to the phosphorite dragon cub, but after killing it, the body disappeared without giving me the mount.u can check in the database.I believe that fair administrators will provide fairness to players from every country.this is a screenshot of what I killed at the time,ill wait for ur reply thank you!10月5日下午4点25分（游戏时间），我在深岩之洲杀死了奥伊纳克斯，但是杀死后尸体直接消失，没有给我坐骑，您可以在数据库里查验，我相信公正的管理者会给与每一个国家的玩家公平，下面这个是我当时击杀的截图，期待您的答复，谢谢！

I sent email of above content to the support email GM provide but turned out this email doesn't exist. support@whitemane.org

Anyone can help on this issue?

Thanks

**Comment by wildhunterJ** [comment]
![mmexport1696519398218](https://github.com/gamefreedomgit/Maelstrom/assets/147081220/d4d0abc1-2da5-4dc4-a7fd-a33a0a19777c)

**Comment by Waroxx-QA** [comment]
It cannot disappear, falling in the same place to the ground, i did it several times it never happened.
Make an ingame Ticket, maybe GMs can you help you.
