### ISSUE TITLE
Linking from Dungeon Journal 

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4691]
**Description:**
Linking from Dungeon Journal in any chat is not working.
I checked like 4 times if my chat is interactive or noninteractive, I also asked few people about if they can link.
seems not working.

In my opinion it's very useful & helpful to link things in chat
pug runs, extra explanation, discussions, asking or answering to questions related to abilities or bosses.
able to linking is very important.

**How to reproduce:**
open the Dungeon Journal and link in say, party, raid, whisper etc chat to someone else.

**How it should work:**
Should able to link it in chats, people should able to click it and view the what been linked.

**example:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/63b3a38a-20cb-4b0a-bf74-a5df92375ce6)

**Comment by UltraNix** [comment]
Fixed.
