### ISSUE TITLE
Recuperate not affected by Dampening

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, recup isnt affected by dampening

**How to reproduce:**
Check recuperate healing in non dampening vs in dampening, it isnt affected

**How it should work:**
Recuperate should be affected by dampening :)

**Database links:**

**Comment by mipanka** [comment]
Btw need to test other healing ability (warrior, dk, hunter, warlock)

**Comment by Afgann** [comment]
fixed
