### ISSUE TITLE
alysra trash bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4693]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sometimes we cant see half of the trash and ppl cant attack, u can see the birds came out cuz ppl arent able to attack the second pair of eggs

**How to reproduce:** idk

**How it should work:**
always we should see it

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/e42652f9-123a-4a87-895f-395f93908b62)

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/3dd635c7-f5a1-4766-b75d-96968d06d441)
 it get fixed only by relog not reload and after trash it is killed should dissapera cuz we cant see the feathers cuz the big birds

**Comment by Sketish** [comment]
Also eggs are not linked to druid casters.
