### ISSUE TITLE
Roasted Beef not counting as meat for hunter's feed pet

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4694]
The level 80 food that drops from most cataclysm NPCs called Roasted Beef can not be fed to hunter pets that have a diet of meat. 

'Your pet doesn't like this food' shows up

**Comment by Zeehra** [comment]
Same as #3327. Was closed as "fixed" but wasn't actually fixed bc I never got around to making a complete list of exactly which pets don't like exactly which foods. However, the issue still persists.
