### ISSUE TITLE
Electrostatic Condenser

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4695]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![ab926266b4b69ac25185e7625ef69fe2](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/3dcf443e-ebaa-42ce-8c6c-3cc082ee14db)

this item doesnt work cause i farmed all these herbs and not 1 volatile air QQ

**How to reproduce:**
farm a bunch of herbs with the item
![2815f9eabdbf1294bb9f3af46a78a107](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/2ad9a379-e239-4175-b60a-990e68e73669)

**How it should work:**
provide volatile air

**Database links:**

https://cata-twinhead.twinstar.cz/?item=67494

**Comment by UltraNix** [comment]
![WoWScrnShot_101323_200816](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d6a64242-034d-4a77-8d67-25d22c675bc9)
You are sure you have the item with you in bags?
The drop chance is not very high (about 6%).

**Comment by UltraNix** [comment]
![WoWScrnShot_101323_200816](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2b91bcd6-09d3-4ccf-bcba-c567039b4406)
@SimonBpvp You are sure you have the item with you in bags?
The drop chance is not very high (about 6%).

**Comment by SimonBpvp** [comment]
Yeah but maybe I was unlucky
