### ISSUE TITLE
Forsaken NPC Darnell follows you forever

### ISSUE THREAD

**Issue by PedroEnrico555** [gamefreedomgit/Maelstrom#4698]
**Description:** On the early Forsaken quests, an NPC called Darnell spawns to help you collect some Scarlet Crusader corpses that are scattered across Deathknell. After completing the quest, the NPC disappears (as it should) and immediately respawns, following you for the entire game. I am not joking, you can only lose him in certain doorways, but anyway, he does not dissappear: neither logging out or restarting the game or even traveling by boat/zeppelin.

**How to reproduce:** Start as a Forsaken and complete the "Recruitment" quest.

**How it should work:** He should disappear after completing the quest "Recruitment".

**Comment by PedroEnrico555** [comment]
This has been happening since I started my first character on the server, about 3 months ago

**Comment by Waroxx-QA** [comment]
"On the other hand if one doesn't complete the quest Darnell; the NPC tasked with accompanying and assisting you, will not disappear, leaving you with a rather large zombie vanity pet that no one else can see. How long Darnell keeps will keep the player company I cannot yet say, though he has joined me as far as Brill."
Maybe you didn't complete the quest ?

**Comment by PedroEnrico555** [comment]
No, I'm pretty sure I completed the quest. This simply always happens.

**Comment by UltraNix** [comment]
Fixed.
