### ISSUE TITLE
[Mage] Flame/Frostfire Orb stealth detection

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4699]
**Description:**
as I wrote here https://github.com/gamefreedomgit/Maelstrom/issues/4475#issuecomment-1712460939
The Orbs are detecting players on stealth and get them out, they should not.

**How to reproduce:**
1 Mage, 1 Stealth character like Druid
cast Orb toward the stealthed character.

**How it should work:**
Should not detect stealth and get them out of stealth.

**Database links:**
~~~

**Comment by UltraNix** [comment]
@whothatdog Please, provide retail source.

**Comment by UltraNix** [comment]
@whothatdog Please, provide retail source. AoE spells in general reveal stealthed targets.

**Comment by whothatdog** [comment]
Orb is not considering as AoE.
it's using AoE to search for enemy targets on it's radius or something like that
to hit the targets on it's range but not should not 'discover' people under Stealth.

Only on MoP Blizzard re-designed Orb to be AoE.
Read my message here: https://github.com/gamefreedomgit/Maelstrom/issues/4475#issuecomment-1712460939

Perhaps I'll tag some PVP players:
@simonb
@kenniflopper

**Comment by SimonBpvp** [comment]
> Perhaps I'll tag some PVP players: @SimonBpvp @Kenniflopper
> 
> Hey, can you confirm or denounce it this issue?

No idea sorry, my instincts say it shouldnt pop stealth out but like it is doing but that's nothing more than a blind guess on my part. I will ask around.

**Comment by Crusaderz** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/4746
