### ISSUE TITLE
Transmog not applying on weapon

### ISSUE THREAD

**Issue by Xayris** [gamefreedomgit/Maelstrom#4700]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Transmog doesn't apply on weapon. Nothing happens when pressing the "Apply" button. 
I'm trying to transmogrify a polearm into: https://www.wowhead.com/wotlk/it/item=43600/brunnhildar-harpoon

**How to reproduce:**
Try to transmogrify a weapon into https://www.wowhead.com/wotlk/it/item=43600/brunnhildar-harpoon

**How it should work:**
Transmog should be applied but nothing happens when pressing apply

**Comment by Waroxx-QA** [comment]
Make an ingame ticket, a GM will help you.

**Comment by Xayris** [comment]
> You cannot transmogrify with "common" items ( white or grey items )

Yes, you can. It was added later. The game doesn't block me from selecting the white item. It's just the "Apply" button that doesn't do anything. No errors. Nothing happens.
![Screenshot 2023-10-07 125254](https://github.com/gamefreedomgit/Maelstrom/assets/45147607/60089a1a-5a02-4bcf-8bd3-02eeb9cf3806)
