### ISSUE TITLE
Drop rate for an important Engineering recipe is 66 times lower than it should be.

### ISSUE THREAD

**Issue by tehfran** [gamefreedomgit/Maelstrom#4703]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
An important quest item called SCRAP-E Access Card drops from Library Guardian mobs at very low rates (I didn't manage to drop it at all). It gives a quest that rewards a recipe necessary to make Jeeves.

**How to reproduce:**
Just kill mobs and watch them not drop the thing.

**How it should work:**
The drop rate is supposed to be 100% for engineers (I think specifically for engineers with 400 engineering) and 0% for anyone else. Wowhead's tracker obviously doesn't take into account what professions you have when you kill the mobs so it says 1.5%. You can check the comments on wowhead to verify this fact.

**Database links:**
https://www.wowhead.com/item=41267/scrap-e-access-card

**Comment by Zeehra** [comment]
Drop rate is low because item doesn't exist. Quest is removed. Just enter the cave, interact wih the console and complete.
https://vimeo.com/872177781/6bef0f0625?share=copy

**Comment by VirtualReign** [comment]
> Drop rate is low because item doesn't exist. Quest is removed. Just enter the cave, interact wih the console and complete. https://vimeo.com/872177781/6bef0f0625?share=copy

This is the recipe for the Scrapbot Kit, not Jeeves.

**Comment by Zeehra** [comment]
> > Drop rate is low because item doesn't exist. Quest is removed. Just enter the cave, interact wih the console and complete. https://vimeo.com/872177781/6bef0f0625?share=copy
> 
> This is the recipe for the Scrapbot Kit, not Jeeves.

Uhm yes. And the user specified, both here and on discord, that he wants the scrap-e card, not the jeeves recipe. Jeeves recipe exists, low drop, annoying etc, but scrap bot item was removed. Idk how else to make it obvious, I mean, the video shows it.

**Comment by SexyPancake** [comment]
Both jeeves recipe and scrap-e exist in the current game. End of story.

**Comment by UltraNix** [comment]
It's 1% as wowhead says.
