### ISSUE TITLE
Mostly Harmless

### ISSUE THREAD

**Issue by Cqueen26** [gamefreedomgit/Maelstrom#4704]
An in game GM helped me with the Mostly Harmless quest in Swamp of Sorrows where you had to disarm them. But the game processed it as complete right before I ported somewhere else and went to a loading screen. Will that cause bugs? I was able to turn in the quest just fine and the gear increased my armor the right amount. I didn't pay attention to any stats. But having the quest completed (the yelllow colored words on the screen) and then immediately go to a loading screen, will that cause bugs? I didn't even see the quest tracker symbol on my screen shift from exclamation mark to question mark. I just need this answered if anyone has time.

**Comment by UltraNix** [comment]
No problems should be appear with this.
