### ISSUE TITLE
[Hunter][Survival][Talent] Serpent Spread

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4708]
**Description:**

I use 1/2 talent, so the duration is 6 sec Serpent Sting
1.  a problem with when Hunter use twice Multi Shot -> Multi Shot
hunter is lose a tick of Serpent Sting.
the 6 sec should extend to 7-8 sec to allow the previous one to tick.

2. when you Multi Shot it apply 6 sec Serpent Sting. If Hunter using Cobra Shot the maximum it extends is - 12 sec. (6+6)
that incorrect it.
as long Hunter is not using Multi Shot and use single-target rotation (Cobra Shot) the Serpent Sting should go the maximum seconds like you apply it from the ability itself and not from the Multi Shot. (6+6...n up to 21 [15+6))

4. the damage of the Serpent Sting is low. Not sure it's even use correct multipliers / crit multipliers / formula corrections.

5. **Improved Serpent Sting** that instant damage 30% of the SS periodic damage is incorrect damage is low for some reasons.

Whitemane ilvl 362~
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/6600ec3d-45dd-4d6b-bbdd-acf205be51f6)

Whitemane empty gear only Light Crossbow:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/e15c5654-45b9-4e47-a37c-786bbcd324d9)

Twin** empty gear only Light Crossbow:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/a76b52b4-4578-4fd4-b9b7-8e022c418fb7)

max crit: Whitemane  711 VS  2829 Twin**
max normal: Whitemane  237 VS  944 Twin**

**How to reproduce:**
No clue.

**Database links:**
(1) - 4:25
https://www.youtube.com/watch?v=H0zLfEopSLs

**Comment by Waroxx-QA** [comment]
Providing evidence from other projects makes your report invalid.
Only RETAIL proofs are taken into consideration, so please make a new report using data from RETAIL only.

**Comment by whothatdog** [comment]
@Waroxx-QA Hi Waroxx, same here it took me alot of effort to report and make it very comrephensive.
Also, I provided link from **RETAIL** and specific time to watch (4:25)

This hunter casted Multi Shot x2 raw
the Serpent Sting extends to 8 sec as I wrote on (1)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/f9bbff04-7ad6-4001-8836-c66bd679edf1)

**Comment by bonfax4** [comment]
@whothatdog I can't check rn but if you have simcraft, open the hunter.cpp file and look for the serpent sting formula + modifiers. Or run a sim with the same gear, disable all temporary buffs in the rotation ( pots, call of the wild, orc racial, food , flask), disable all class buffs in the options, pick a lvl 85 ( default is boss I believe ) target if that's what you're testing against and compare numbers.

**Comment by bonfax4** [comment]
https://web.archive.org/web/20120723144959/https://www.wowhead.com/spell=1978

Causes (RAP * 0.4 + (460 * 15 sec / 3)) Nature damage over 15 sec.

**Comment by bonfax4** [comment]
@Waroxx-QA Also [here](https://youtu.be/1I_udByG8Y4?t=1m) you can see a refreshed multi shot serpent sting + cobra shot + cobra shot going from 6-7 into 12 into a 16-17 secs to help prove point nr 1 and 2 that it should add up to the max duration. 

Just reopen and let him update the main post instead.

**Comment by bonfax4** [comment]
Also another thing, the max duration serpent sting can go is 15 + time till last tick even with cobra shot increases, not 15 +6 ( 21 ). Used to be 21 when you check 4.0 videos but every 4.3 video shows refreshes being max 18 seconds.

**Comment by whothatdog** [comment]
@bonfax4 THANK you for commenting here.

-> Yeah the SS imporved from Multi Shot is probably 30% of the 6 seconds I did not wanted to write it
because I wasn't sure I read the description if 'total periodic' mean 15 or 6.
on Twin's it's of the 15 sec even from Multi Shot.

-> about 15+6 - you're right I tested it also on Twin's max is 18. (17+ previous tick?)

they dont want to take screenshots of damage comparsion or anything from that project
although some fixes there are possible to be correct, so why not?
Like really the same sources we provide here, other people provided for the developers there
it's just copy-pasting.

Anyway, much thanks for strengthening this report and confirm it. 
**please** look about the Pet damage I also tagged you.

@Waroxx-QA, @UltraNix please open it.

**Comment by bonfax4** [comment]
Twin bugtracker is a better reference imo, there's usually worldoflogs references or links with proof in there. There's no guarantee they are completely bug free tho, still see open issues in there.

>-> about 15+6 - you're right I tested it also on Twin's max is 18. (17+ previous tick?)

Ticks every 3 seconds, so  it will land somewhere between 15-18 on refresh.

**Comment by whothatdog** [comment]
Yeah I saw the two issues with worldoflogs links inside.
I could not take any information useful* from there and the worldoflogs but it did not opened even with web-archive so I gave up on it.
(*maybe except the formula the same you provided here, which I wasn't sure about)

Look at pet damage issue.
https://github.com/gamefreedomgit/Maelstrom/issues/4707

**Comment by whothatdog** [comment]
I wonder about this issue status can someone say? @Sketish

**Comment by bonfax4** [comment]
Eh you prob better off making another issue and linking it to this one as reference as proof.

**Comment by Sketish** [comment]
Personally I suggest making 2 seperate reports

First about sting duration when using multi shot

Second about :
the damage of the Serpent Sting is low. Not sure it's even use correct multipliers / crit multipliers / formula corrections.
Improved Serpent Sting that instant damage 30% of the SS periodic damage is incorrect damage is low for some reasons.

Then we can start working on it
