### ISSUE TITLE
Missing NPC - Ogri'la - Kronk

### ISSUE THREAD

**Issue by DorizarN** [gamefreedomgit/Maelstrom#4709]
**Description:**
The NPC called Kronk is missing in Ogri'la.
If you run out of the zone -> go back, then you can see Kronk floating briefly before the NPC falls through the ground.

**How to reproduce:**
Go to Ogri'la 

**How it should work:**
Should be in Ogri'la.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=23253

**Comment by frostwave942** [comment]
true, in approach that npc kronk falls through the map and after completing <a href="https://www.wowhead.com/quest=11010/bombing-run">bombing run</a>, the daily <a href="https://www.wowhead.com/quest=11023/bomb-them-again">bomb them again</a> is not unlocked. this rep will be necessary for winter veil event.

**Comment by Afgann** [comment]
fixed
