### ISSUE TITLE
Refund to Vendor "visual" bug

### ISSUE THREAD

**Issue by Flamelush** [gamefreedomgit/Maelstrom#4710]
[//]: #https://www.wowhead.com/npc=58154/toren-landow
[//]: # https://www.wowhead.com/item=58129/seafoam-mantle
[//]: 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/147324291/0b4bdf58-ec40-46b0-a9b9-14471c0b7264)

Refund Item to Vendor for JP visual bug.

Buy item, gem/enchant said item. Return to vendor to refund. window pops up, press yes. nothing happens, no errors message produced by server or system to say that its not eligble for a refund. 

Option to refund item should be completely disabled when returning to vendor for refund, and not halt halfway through process without any error messages telling players(s) that the item isnt eligble. (it depends on your server, some servers allow refunds despite item being worn/enchanted/gemmed.)

https://www.wowhead.com/npc=58154/toren-landow
[//]: # https://www.wowhead.com/item=58129/seafoam-mantle

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/9cc5966d-e3d0-4b65-8a25-c0860a58439a)
This is the error.
