### ISSUE TITLE
My Dungeon Finder Defaults to something that doesnt exist yet [Random Hour of Twilight Heroic]

### ISSUE THREAD

**Issue by Flamelush** [gamefreedomgit/Maelstrom#4711]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

My Dungeon Finder Defaults to something that doesnt exist yet [Random Hour of Twilight Heroic]

On relog, on reload, zone change, or completion of dungeon and zoning out,  it seems to default to this screen whenever i go back into Dungeon finder. 

Shouldnt really give you the default inferface of something that doesnt exist yet.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/147324291/5a3cde53-30b3-4618-a9ea-f5b7fc5b52c8)

**Comment by xmrshoot** [comment]
its patch 4.3.4 , its not a bug

**Comment by frostwave942** [comment]
y we're in patch 4.2 atm

**Comment by xmrshoot** [comment]
client is patfch 4.3.4
