### ISSUE TITLE
Gebler shouldn't be waiting for players next to Lilian's cage

### ISSUE THREAD

**Issue by wds40** [gamefreedomgit/Maelstrom#4716]
When players first arrive at the top of the Crusader's Outpost in Tirisfal Glades, only two NPCs should be up there: Lillian Voss and a random Scarlet Crusade trash mob. Scarlet Lieutenant Gebler should not appear until the player has found the scroll, read it, accepted the quest, and spoken to Voss.

Today, when I did this quest, Gebler was already next to Lilian's cage, just standing around with his thumb up his butt. When I spoke to Lilian, a SECOND Gebler came walking up the stairs and did the dialog with her.

**Comment by PanJanuszek** [comment]
Cannot reproduce, no gebler here:

![Uploading image.png…]()
