### ISSUE TITLE
Darnell respawns and follows me around Deathknell every time I return there

### ISSUE THREAD

**Issue by wds40** [gamefreedomgit/Maelstrom#4722]
After a player has finished all quests in Deathknell, they should never see Darnell again, unless he's following some other player who hasn't yet finished all of the quests there.

Instead, when I return to Deathknell, he respawns and follows me around.

EDIT: he follows me around **_outside_** Deathknell, too https://imgur.com/NX7GZvN

**Comment by UltraNix** [comment]
#4698
