### ISSUE TITLE
[Hunter] [Pet] [Talent] Heart of the Phoenix - unreliable behavior

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4728]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
"When used, your pet will miraculously return to life with full health."
This spell fails in PvP sometimes

**How to reproduce:**
My gut feeling is that the spell fails either when the pet dies during a CC.
Another case might be if it dies outside of 40y or LoS from hunter.
Clicking the Heart of the Phoenix spell does nothing - no message shows up, doesn't go on cooldown

**How it should work:**
Should always be able to ressurect pet with this talent, no matter the circumstances of the pet's death.
Assuming no ress debuff applied by the spell, but that's not the case in this issue.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55709

**Comment by djesic** [comment]
It is a pet ability, range is not relevant

**Comment by djesic** [comment]
Also, database link states range 0y, it's a pet self cast

**Comment by djesic** [comment]
But I really think the range is not the cause of the spell failing sometimes.
It's being CC'd during death most likely

**Comment by Afgann** [comment]
fixed

**Comment by djesic** [comment]
@Afgann please share some fix details, I'm really curious about what was wrong.

**Comment by djesic** [comment]
@Afgann not fixed - just failed in AB
