### ISSUE TITLE
[Hunter] [Pet] Can't dismiss pet during most scenarios.

### ISSUE THREAD

**Issue by ShadowForever1** [gamefreedomgit/Maelstrom#4730]
When trying to dismiss pet, the cast will complete but pet will still be there. Usually when the pet is in a odd place it doesn't seem to work or during combat when the pet is just standing next to you.
Pet should be able to be dismissed when ever or what ever position it's in.

**Comment by SimonBpvp** [comment]
Pet has to be in your line of sight to get dismissed no?

**Comment by ShadowForever1** [comment]
That's true, but even when in line of sight. It doesn't seem to work.

**Comment by Sketish** [comment]
Please provide any video of that issue
