### ISSUE TITLE
Un'goro repeatable quests bugged

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4731]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The whole questline in Un'goro is working surprisingly well. However, once you finish the questline with the quest https://www.wowhead.com/quest=24695/ever-watching-from-above
you are supposed to gain access to repeatable quest to gain junk consumable items in exchange for crystals from the 3 pylons in Un'goro (north, east, west). Useless on high level, in my case would be quite huge consumables for twinks.

This is not working on the server, instead, the pylons have a blue question mark over them but only have some dialogue when clicked.
I will link the unobtainable quests below:
https://cata-twinhead.twinstar.cz/?quest=24726
https://cata-twinhead.twinstar.cz/?quest=24725
https://cata-twinhead.twinstar.cz/?quest=24724
https://cata-twinhead.twinstar.cz/?quest=24729
https://cata-twinhead.twinstar.cz/?quest=24728

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
since shattering 4.0.3 these quests shouldnt be available
