### ISSUE TITLE
soulburn spell lock

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4732]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
resummoning a lock pet with soul burn resets the cd on pet abilities
(they nerfed this in 4.2 or something)

**How to reproduce:**
spell lock, soul burn and spell lock again with felhunter

**How it should work:**
not reset CDs when summoning a pet

**Database links:**

**Comment by Pornoodemon** [comment]
Patch 4.3.4
https://youtu.be/7ibtrZdtJB8?t=470
The video clearly shows the CD reset as well as (enemy shaman healer in the 11th season of gear)

**Comment by SimonBpvp** [comment]
https://web.archive.org/web/20120222132728/http://www.arenajunkies.com/topic/219709-soul-burn-spell-lock-hotfix/
https://web.archive.org/web/20120221010117/http://www.arenajunkies.com/topic/219700-fel-dom-cs/

There some players are saying it was hotfixed, date: Posted 09 February 2012 (that's in early 4.3)

**Comment by Pornoodemon** [comment]
Firstly, this is a discussion on a secondary forum
  and we are talking about a fix on some third-party resource and no information about the patch
Secondly, I provided video 4.3.4 (of the official server) which clearly shows how it works. I don’t understand what can be discussed here.

**Comment by SimonBpvp** [comment]
that footage in snutz 5 may have been captured before February 2012 though

**Comment by SimonBpvp** [comment]
4.3 / season 11 lasted from nov 2011 to august 2012 (longest season ever I think) so the February hotfix was 3 months into the season, plenty of time for Snutz to get footage of soulburn CS working pre hotfix. But in 4.3.4 you could not do it.

**Comment by Pornoodemon** [comment]
> 4.3 / 11-й сезон длился с ноября 2011 года по август 2012 года (я думаю, это самый длинный сезон за всю историю), поэтому февральское исправление было выпущено через 3 месяца после начала сезона, и у Снутца было достаточно времени, чтобы получить кадры работы Soulburn CS до исправления. А вот в 4.3.4 этого сделать не удалось.

Well, then let's make a fix based on your hypothesis.

**Comment by Pornoodemon** [comment]
In 2012, Snutz returned to BlizzCon again, playing alongside Venruki and Kollectiv for the independent team Bring It. The team won the Arena World Championship playing Mage, Warlock and Shaman, taking out the European team Yaspresents
2012 This is 4.3.4

**Comment by Sketish** [comment]
@SimonBpvp  Please provide any proof for 4.3.4

4.3 / season 11 lasted from nov 2011 to august 2012 (longest season ever I think) so the February hotfix was 3 months into the season, plenty of time for Snutz to get footage of soulburn CS working pre hotfix. But in 4.3.4 you could not do it.

**Comment by Pornoodemon** [comment]
This tournament took place in 2012. VIDEO 4.3.4 PATCH. Why should he provide evidence if I provided other evidence?

**Comment by SimonBpvp** [comment]
> VIDEO 4.3.4 PATCH. https://youtu.be/7ibtrZdtJB8?t=470 https://youtu.be/7ibtrZdtJB8?si=T-IHAwKst28tfVg6&t=995 Why should he provide evidence if I provided Evidence to the contrary? I went through all the official resources and nowhere is there any mention of fixes or hotfixes. To reset CD. 

First of all I already explained why this footage was not captured in patch 4.3.4, it was captured in 4.3.0.  Secondly there is no official documentation of the hotfix, because it's a hotfix. That's why I linked the archived AJ posts and not an official blizzard post, becuase there was no official blizzard post. That's why you are confused. Because it was hotfixed after snutz recorded snutz 5 and was never documented. In 4.3.4 you couldn't soulburn spell lock



> @SimonBpvp Please provide any proof for 4.3.4
> 
> 4.3 / season 11 lasted from nov 2011 to august 2012 (longest season ever I think) so the February hotfix was 3 months into the season, plenty of time for Snutz to get footage of soulburn CS working pre hotfix. But in 4.3.4 you could not do it.

my evidence (the archived AJ posts) is from patch 4.3.2. I have nothing from 4.3.4 because there is nothing from then. But they never reverted the hotfix so it stands untill 4.3.4

**Comment by SimonBpvp** [comment]
![892c13bb9affdbb9d675462448741573](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/4f9e565b-172c-47b5-a559-4e5dc5f1999f)
![390d15167a9027bc3229aa8e907b5d45](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/74ccf9ad-b38a-40d0-ad07-1f7e08b7fd4a)

![1aaca8dfc838ce60c59e7be6727d2e44](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/0a1b7ab1-c804-467d-b7dc-29cfa6223a4a)

![ba441f25d604b1d8e4d56751b499063e](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/22fc55fa-8ad6-459c-ae36-5d27a7e9b05b)

**Comment by Pornoodemon** [comment]
This forum is a garbage dump where half the discussion concerns pirate servers.
Where did this screenshot even come from?
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/648eb10e-b3a2-4b04-9cd0-55807fdbb756)
What Warcraft add-on are we talking about in this thread?
Why is there no links or screenshots of this office from official resources in this topic?

**Comment by SimonBpvp** [comment]
that screenshot when compared with AJ post dates(feb2012) confirms that the hotfix was from early patch 4.3.2(january2012).

I'm sorry I can't provide you with an official post or a dev tweet for the hotfix, Blizzard just didnt post about every single hotfix in history. They just didn't. I provided posts of players from AJ (who are all gladiator+ btw) cause that's all there is and that's all I have.

**Comment by Pornoodemon** [comment]
![WoWScrnShot_032923_170120](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/f0dccc37-d8f7-42cd-99f6-ca1e5670cfa5)

February 2012 This is patch 4.3.4.
The video shows in black on white how it works.
https://youtu.be/7ibtrZdtJB8?t=470
https://youtu.be/7ibtrZdtJB8?si=T-IHAwKst28tfVg6&t=995

**Comment by Pornoodemon** [comment]
And here, too, there is nothing about this.
https://wowpedia.fandom.com/wiki/Patch_4.2.2
https://wowpedia.fandom.com/wiki/Patch_4.3.0
https://wowpedia.fandom.com/wiki/Patch_4.3.0a
https://wowpedia.fandom.com/wiki/Patch_4.3.2
https://wowpedia.fandom.com/wiki/Patch_4.3.3
https://wowpedia.fandom.com/wiki/Patch_4.3.4

**Comment by SimonBpvp** [comment]
> And here, too, there is nothing about this. https://wowpedia.fandom.com/wiki/Patch_4.2.2 https://wowpedia.fandom.com/wiki/Patch_4.3.0 https://wowpedia.fandom.com/wiki/Patch_4.3.0a https://wowpedia.fandom.com/wiki/Patch_4.3.2 https://wowpedia.fandom.com/wiki/Patch_4.3.3 https://wowpedia.fandom.com/wiki/Patch_4.3.4

I know mate, I know there's nothing in there cause I looked myself. That's why I had to go looking in old forums for info.

**Comment by Sketish** [comment]
Evidence was only provided that cd should reset on soulbourn pet resummon. Not a bug

**Comment by SimonBpvp** [comment]
![timelineS11](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/f903fee5-0dfc-40c3-abf1-01f6ef7de791)

**Comment by SimonBpvp** [comment]
![timelineS11](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/6ab32940-8ff6-4081-8598-03e32f520f96)

**Comment by SimonBpvp** [comment]
No I know it's not proof of anything, it's an MS paint that took me 5 mins. It was just to illustrate that Snutz 5 doesn't falsify the hotfix's existence, it just shows a time before the hotfix like a lot of warlock videos also show, such as Dakkroth's videos.  I'm not claiming that you couldn't soulburn spell lock in season 11 cause you could. I'm claiming that you couldn't soulburn spell lock in 4.3.4 cause you couldn't.

**Comment by Sketish** [comment]
> > Evidence was only provided that cd should reset on soulbourn pet resummon. Not a bug
> 
> But it’s not blizzlike. Blizzlike would be you can’t reset cd with resummon. As I showed they changed it in 4.3.2. 4.3.4 comes 1 month after that. I need to draw a timeline to illustrate this I think.

Still no evidence provided from you, just some text from unofficial forums,. Unless some1 provide video from 4.3.4 when its wo rking differently we wont be changing that

**Comment by SimonBpvp** [comment]
If you’re looking for a video of a lock using fel dom pet summon and not getting a cd reset, then that’s going to be a bit difficult to provide but I can try. 
Anyway at least change to status need info or something cause this is definitely not a closed case.

**Comment by Pornoodemon** [comment]
> 
Out of curiosity, I looked for it myself. I watched more than a hundred videos and found nothing.

**Comment by SimonBpvp** [comment]
that Dakkroth vid is from 4.2 season 10. Look I will explain in a simple way. Imagine a sequence of events....
1. Cata is released and soul burn is a new spell which can be used to resummon a pet and reset spell lock.
2. Many people make different pvp warlock videos over 2 and a bit seasons of the game where they use this pet resummon mechanic.
3. During the 3rd and final season of cata blizzard decides to hotfix the pet resummon in between patch 4.3.2 and 4.3.4. They don't document this hotfix.
4. Players post on Arena Junkies about the change.
5. Snutz and other locks continue to make warlock clips, but now there is no soul burn felhunter used. (because it was nerfed)

[https://youtu.be/sQT0mI4e4e4?feature=shared](url)
https://www.youtube.com/watch?v=eAkJLZ8Mqag
https://www.youtube.com/watch?v=SKQcpTnE9mk

these are examples of lock gameplay after the hotfix. Spell lock is not used to resummon a pet by any warlock in these games. I believe that this is because of the nerf but I can't PROVE this, its just a clue.

**Comment by Pornoodemon** [comment]
Don't get me wrong.
I understand that in theory this is possible. But there is no proof.
I searched all over the Internet for RU/ENG

**Comment by SimonBpvp** [comment]
> Don't get me wrong.
> I understand that in theory this is possible. But there is no proof,and the initial idea for this correction originates from only one comment
> I searched all over the Internet for RU/ENG
> I think that there is no longer any point for the two of us to write something in this topic. You just need to leave this question until a better time. Perhaps someone will solve this issue someday.
> For now, we have the fact with proofs that it works for us as it does on 4.3

Well thank you for helping with the search cause I definitely don’t read Russian good! 

In terms of waiting for a better time I don’t think that’s wise because the sooner the better for fixes, the old blizzard proofs don’t last forever. 

Regarding those retail clips you linked I’m sorry but that’s fake proof cause it’s from the wrong patch both snutz and dakkroth. Fake proof is worse than no proof at all cause it’s misleading!

Anyway now I’m hoping that someone else can weigh in.

**Comment by Pornoodemon** [comment]
Those videos are not false information. They show how the spell worked in the  patch 4.3 +
Therefore, it is better than the absence of any information.

**Comment by SimonBpvp** [comment]
Anyone can test this on beta? Else have to wait prepatch on 30th to test it myself
