### ISSUE TITLE
NPCs do not appear in hyjal nor in archerus bastion

### ISSUE THREAD

**Issue by SebastianMoncada** [gamefreedomgit/Maelstrom#4733]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I am in Mount Hyjal, the NPCs do not appear to deliver the missions, just as in the archerus bastion, the NPC does not appear to reset the talents. I am DK.

**How to reproduce:**
Occurs when I approach NPCs

**How it should work:**
NPCs should appear

**Database links:**
https://drive.google.com/file/d/18iih5LNhyj4K9yZ5a4NTrkGJMnAEkODJ/view?usp=sharing

**Comment by UltraNix** [comment]
@SebastianMoncada Poke me on Discord.
