### ISSUE TITLE
[Deatch knight] pet and death pact

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4734]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
you cannot use death pact when the pet is in control

**How to reproduce:**
use control on the pet and try to use death pact

**How it should work:**
death pact should can be used if the pet in control

**Database links:**
https://wowpedia.fandom.com/wiki/Raise_Dead_(death_knight_ability) 
https://wowpedia.fandom.com/wiki/Death_Pact

I cant provide any video as proof, but nowhere is it mentioned that pet control should block this ability

**Comment by mipanka** [comment]
https://wowpedia.fandom.com/wiki/Death_Pact
[Patch 3.3.3](https://wowpedia.fandom.com/wiki/Patch_3.3.3) (2010-03-23): Fixed a bug where Death Pact would not kill the ghoul while under the effects of Spell nature earthbind [[Cyclone]](https://wowpedia.fandom.com/wiki/Cyclone).
as I understand it, this is confirmation, there were no changes, not even mentioned anywhere

**Comment by Hermeleen** [comment]
> https://wowpedia.fandom.com/wiki/Death_Pact [Patch 3.3.3](https://wowpedia.fandom.com/wiki/Patch_3.3.3) (2010-03-23): Fixed a bug where Death Pact would not kill the ghoul while under the effects of Spell nature earthbind [[Cyclone]](https://wowpedia.fandom.com/wiki/Cyclone). as I understand it, this is confirmation, there were no changes, not even mentioned anywhere
hmm, actually weird, i would agree that you should be able to sac stunned pet, shackled+ turn evil, or gouged, but i would think by the "immune" nature of cyclone, that during cyclone it shouldn't work. I would actually expect warning saying something like "Target Is Banished" or "Can't do that yet"

**Comment by Hermeleen** [comment]
> https://wowpedia.fandom.com/wiki/Death_Pact [Patch 3.3.3](https://wowpedia.fandom.com/wiki/Patch_3.3.3) (2010-03-23): Fixed a bug where Death Pact would not kill the ghoul while under the effects of Spell nature earthbind [[Cyclone]](https://wowpedia.fandom.com/wiki/Cyclone). as I understand it, this is confirmation, there were no changes, not even mentioned anywhere

hmm, actually weird, i would agree that you should be able to sac stunned pet, shackled+ turn evil, or gouged, but i would think by the "immune" nature of cyclone, that during cyclone it shouldn't work. I would actually expect warning saying something like "Target Is Banished" or "Can't do that yet"

**Comment by UltraNix** [comment]
Fixed.
