### ISSUE TITLE
'CC protection' missing

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4738]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This thing I'm calling 'CC protection' is non existant on Whitemane. 'CC protection' is mechanic that gives a short window like 250ms? (I dont know how long) where damage is ignored by breakable CC. It applies to DBs, blinds, gouges, scatters, polymorph, anything that can break on first damage and I'm told is even is supposed to apply to fears, novas, hexes which break on accumulated damage. It's on all classic servers and retail servers (and apollo) and I think it goes back a long time since before cataclysm. Most pvpers will know what I'm talking about here (when you deathed poly too early and the poly didn't break from your death).

**How to reproduce:**
use a breakable cc and hit it with dmg instantly
https://www.youtube.com/watch?v=u9gbhuKDZ4c
https://www.youtube.com/watch?v=DohNVZcwcwU

**How it should work:**
https://www.youtube.com/watch?v=u7W75EXoev4&t=691s

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=20024
same exact issue over on twin* before they fixed it back in 2019

**Comment by Afgann** [comment]
fixed
