### ISSUE TITLE
Holy priest bug

### ISSUE THREAD

**Issue by Noraregts** [gamefreedomgit/Maelstrom#4745]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** In BWD Chimaeron Massacre  ability kill Holy priest with spirit of redemption talent, cus the game detects that I'm dead at 1% healt. That's why I had to change talents...also in Zul'Gurub, at Bloodlord Mandokir the spirits won't ress me, because of Spirit of Redemption talent. I'm in that form for 15 sec after death. if expiries, the spirit won't ress me. 

**How to reproduce:**

**How it should work:** 

**Database links:**

**Comment by Afgann** [comment]
fixed
