### ISSUE TITLE
[Mage][PVP] Flame orb should not attack targets in stealth

### ISSUE THREAD

**Issue by Crusaderz** [gamefreedomgit/Maelstrom#4746]
But it does, and it breaks stealth
Also, the Impact proc talent knocks targets out of stealth if they are within 12 yards of the target the mage hit with Fire Blast, this shouldn't happen either.

I don't know if orb/impact breaks invisibility, but if it does, it shouldn't too.

An old clip showing a flame orb flying past a rogue in stealth at full speed:
https://youtu.be/krEAIHkWqYM?t=93

**Comment by Crusaderz** [comment]
Turns out the flame orb part is already reported: https://github.com/gamefreedomgit/Maelstrom/issues/4699

**Comment by Crusaderz** [comment]
Rogue POV: https://youtu.be/ZdVOXnSD83g?t=45

**Comment by Waroxx-QA** [comment]
Duplicate - #4699

**Comment by SimonBpvp** [comment]
in both those clips the rogue was in vanish not stealth

**Comment by Crusaderz** [comment]
In the second clip, he was briefly in stealth, but the orb didn't attack him until he opened
