### ISSUE TITLE
[Hunter] [Pet] [Talent] Intervene - not working versus DoT effects

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4747]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1st tick gets absorbed, buff fades

**How to reproduce:**
Cast Intervene on self while receiving damage from DoTs

**How it should work:**
All DoT instances should be absorbed, until receiving a direct attack
Proof: Retail Cataclysm video https://youtu.be/SMSj3jzoBRE?si=KTAxtM0R5UIylGZl&t=94

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=53476

**Comment by Hermeleen** [comment]
yes, phew. I thought on apollo it was actually wrong. This is very underrated talent. I am not sure but i think also non-bm pets can do that. I remember getting the disarm crab at westfall shores for mm. :D

**Comment by djesic** [comment]
Non-BM can get it, yes.
Crabs have pin (channeled root) in Cataclysm, disarm is now on birds of pray

**Comment by Hermeleen** [comment]
Oh yes, the crabs really have pin, but they do have intervene. So Its either roar of sacrifice or intervene for non-bm i guess.

**Comment by djesic** [comment]
You can still get both of those as non-BM with 17 talents. They are both T5 talents

**Comment by Hermeleen** [comment]
Oh yea, i was a bit unsure, i am not playing anything exotic for years. if mm, then monkey, if bm then shale spider. while shale spider is by far best pet i would say, the only problem is it's stun is magical unlike monkey stun, so it can be dispelled.

**Comment by Afgann** [comment]
fixed
