### ISSUE TITLE
Darnell Uncontrolled Spinning

### ISSUE THREAD

**Issue by Drakcain** [gamefreedomgit/Maelstrom#4749]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Darnell, the warrior at Undead starting zone, keeps spinning his upper body.

**How to reproduce:**
Just take the first quest that gives you "Darnell".

**How it should work:**
Not spin around and walk normal.

**Database links:**
https://wowpedia.fandom.com/wiki/Darnell

**Comment by PanJanuszek** [comment]
Cannot reproduce anymore, he follows his path, says two texts and wait for player action.
