### ISSUE TITLE
Alchemy Flask/Elixir Duration Bonus

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4752]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
When you have alchemy on 1 point, freshly learned, every flask or elixir will have doubled duration. Even if you don't know the recipe.

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
Te refieres a este hechizó?
https://www.wowhead.com/wotlk/es/spell=53042/la-ciencia-de-la-mezcla

**Comment by Hermeleen** [comment]
yep - https://cata-twinhead.twinstar.cz/?spell=53042

**Comment by SexyPancake** [comment]
Mixology only applies to elixirs or flasks that you can make yourself, whats the issue? Is the buff at (1) alchemy being applied to unlearned ones?

**Comment by Hermeleen** [comment]
Yes

**Comment by xmrshoot** [comment]
its fixed , u can close it

**Comment by Afgann** [comment]
fixed
