### ISSUE TITLE
Q: Graverobbers in Garren's Haunt

### ISSUE THREAD

**Issue by Drakcain** [gamefreedomgit/Maelstrom#4754]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
For the Q: Graverobbers: The mobs "Rot Hide Graverobber" not being counted for the Quest. I can kill the Mongrel for that part however.

**How to reproduce:**
Accept the quest and go try it
**How it should work:**
The Graverobbers should count for their 8 required and The Mongrel should count for their 5 required.

**Database links:**
https://www.wowhead.com/classic/quest=358/graverobbers

**Comment by PedroEnrico555** [comment]
I have that too. It always goes like:

0/0 Rot Hide Graverobber
8/5 Rot Hide Mongrel
5/5 Rot Hide Gnoll
