### ISSUE TITLE
When entering Tol Barad battle, mount moves at run speed

### ISSUE THREAD

**Issue by renegadeofunk** [gamefreedomgit/Maelstrom#4755]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When entering the Tol Barad battle via queue your mount will only move at run speed until you dismount and re-mount.

**How to reproduce:**
Enter a Tol Barad battle (teleported by queue) while already mounted and move

**How it should work:**
Mount should have it's normal movement speed

**Comment by frostwave942** [comment]
this also happens in tbc areas where u cannot fly, like silvermoon, eversong forest or azure/blood myst isles when u use mounts <a href="https://cata-twinhead.twinstar.cz/?item=69213#.">like this</a> for eg ur run speed is quite slow.

**Comment by UltraNix** [comment]
Fixed.
