### ISSUE TITLE
Ready for raiding II achievement - devout harbinger 

### ISSUE THREAD

**Issue by alilector** [gamefreedomgit/Maelstrom#4757]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
creature's(devout harbinger) special ability hits so fast and it cannot be dodged. also the companions thisalee crow and treant die so fast.
it is impossible to get "ready for raiding II" achievement.

**How to reproduce:**
harbinger deal less damage that a paladin with 382 gear can survive at first. then speciall ability tiks be slower that people can dodge it

**How it should work:**
achievement should be fixed to get

**Database links:**
https://www.youtube.com/watch?v=vFNGBw_E0L0

**Comment by Revly** [comment]
Need use vortex for Jump sprint etc need more ability Ez evade special ability

**Comment by frostwave942** [comment]
if ure a melee class it'll be kinda difficult to avoid the fire but if ure ranged class things are easier, look harbinger cast that fire every 25 sec knowing this u just attack her always at max range and when she's about to finish her cast make sure ure too far away from her.

**Comment by UltraNix** [comment]
Fixed.
