### ISSUE TITLE
PTR Vashjir chainquest Alliance

### ISSUE THREAD

**Issue by Firbael** [gamefreedomgit/Maelstrom#4758]
**Quest bugs- Better late than dead - Mount speed unchanged when using the ability** 
**Q:Case of crabs (25388) not collectable from crate till relog (Phase issue)** 
**Q:Decisions, Decisions (25743) - The porciline prophet is currently not destroyable and the NPC despawns before the hammer lands**
**Q:Decompression(25888) - After using Breathstone on "imprisioned Soldiers" Tracker not counting up**
**Q: Backed into a corner(25164):- Infinate respawns- Fathom-Lord Zin'jatar not spawning after 50 kills of Naga.** - fixed with HORDE
**Q: Undersea Inflation (25218)- Air ballon not filling on "valid" air source (crash using Quest item)**
**Q: Nespirah (25980) - NPC not spawning when going up the spiral 'Earthmender Duarn'**
**Q: Ancient Elven Etching - Not available for race??? --> yes this drop is very low, and has chance to drop for horde or alliance**
**Fathom-stalker azjentus does not give the quest 'Reoccupation'(25619) while on the quest Visions of the past: the invasion of vashir**
**NPC Fathom-stalker is un interactable within Visions of the past until hand in of a kill quest just after.**
**Q: By her ladys word (25858) After talking to NPC the credit is not awarded**
**Q: honor and a privilage(25898) Swimming to the top not credited**
**Q: Devout assembly (25896)- Fathomcaller Azrajar credit not awarded**
**Q: Full circle(26219) - Ship despawns once arrived then phase lock**
**### _Q: A lure(26017) - Nibblers non interactable_ - works as exptected, you ll get credit when nearby nibblers**
**The Brothers digsong 2 : eel-egg-trick boogaloo(26021)- Devious great-eel state not changing - Unkillable regen-**
Q: defending the rift (26193)- Boat bugs out and does not take you to quest location. (manual run over)

qw
Area Bugs - **Q:Gimme Shelter (repeatable-NPC spawn):** Underwater Running animation within smugglers cave, Forced Dismount after Addarah is signalled when re entering cave
Vehicles not despawning

**Phase Bugs- Phase issue within the deepmist Grotto cave before "Debriefing"(25824) (Dun-dun-Dun-dun-Dun-dun)
Q:Rundown:- not phasing into Rundown after accepting the quest**

**Mob bugs:- Brinescale Serpent "evade" bug
Warden Azjakir Double spawn for quest 'The Wardens Time'**
Fathom-Lord Zin'Jatar Infinite regen bug
**### _Quest 'Overseer Idra'kess' Regen bug and aggro borked_ - two nagas have to be killed before shield drops. Works as expected**

**Comment by rhez** [comment]
Q: Call of duty - did not teleport to Vash'jir

**Comment by rhez** [comment]
Q: Traveling on Our Stomachs (25546) - Crabs leave combat and quickly regain HP if not killed quickly enough.

**Comment by PanJanuszek** [comment]
Find me on discord -->Ragnus

**Comment by rhez** [comment]
Q: Once More, With Eeling (27729) should be auto-accepted once you kill one of these mobs:
- Slitherfin Eel
- Slickskin Eel

**Comment by numbuh132** [comment]
Q: Nespirah (25980) - NPC not spawning when going up the spiral 'Earthmender Duarn'

Is not fixed. Having this issue right now. Tried abandoning and picking up multiple times. Tried reloading/relogging/restarting. Tried running around entire area. NPCs won't spawn to progress quest. I am an 83 Human Rogue,
