### ISSUE TITLE
Glyph of Swiftmend

### ISSUE THREAD

**Issue by Kaihua77** [gamefreedomgit/Maelstrom#4759]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Glyph of Swiftmend not working the way it's supposed to work; can't use it without the need of rejuvenation or regrowth.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/3608e520-33bc-435f-bd86-9abafadd74f7)
 its working

**Comment by xmrshoot** [comment]
its working on live too , the glyph dont allow you to sue without reju or regrowth , the glyph dont consume them , read descirpiton again , its not bug
