### ISSUE TITLE
[Quest] Sludge Investigation - Northern Barrens #3059

### ISSUE THREAD

**Issue by Baleinebleu** [gamefreedomgit/Maelstrom#4760]
Description:
The "Muddy Marks" that needs to be interact for this quest are missing.

Database links:
[wowhead](https://www.wowhead.com/quest=29087/sludge-investigation)

On my screen :
![On my screen](https://github.com/gamefreedomgit/Maelstrom/assets/147919517/bca7feba-281c-42ab-bd4d-d3c23da4192d)

What it should be :
![What it should be](https://github.com/gamefreedomgit/Maelstrom/assets/147919517/a9f0854b-a541-4391-a212-7eee76f8eab3)

Thank you in advance

**Comment by Afgann** [comment]
fixed
