### ISSUE TITLE
[Hunter] [Beast Mastery] [Talent]  - 'Improved Mend Pet' doesn't work.

### ISSUE THREAD

**Issue by TemPod73** [gamefreedomgit/Maelstrom#4762]
**Description:**
Talent 'Improved Mend Pet' doesn't work. 

**_Correction - it works only on cast (not ticks)._**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/147922080/c2ac86b2-bda9-4711-8b87-5be5346f15fd)

**How to reproduce:**
Cast Hunter's spell 'Mend Pet' while pet has Poison, Desease, Curse or Magic debuff.

**How it should work:**
Rank 1 - 25% to clean one poison **and** desease **and** curse **and** magic debuff each tick.
Rank 2 - the same but it gives you 50% chance each tick.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=19573 [spell]
I didnt find good retail video-proof. This is only what i've got:
At https://youtu.be/7-Qsa34CYd4?t=12 player showing his talent 'Improved Mend Pet' = Rank1.
At https://youtu.be/7-Qsa34CYd4?t=286 player casting 'Mend Pet' and you can see how he's pet has decurse effect.

**Comment by TemPod73** [comment]
https://youtu.be/PCsdVIW4ZLo?t=76 Hunter's mark was dispelled.
https://youtu.be/PCsdVIW4ZLo?t=514 pet were cursed by warlock and than 08:36 talent 'improved mend pet' dispelled it.
https://youtu.be/PCsdVIW4ZLo?t=571 warlock's fear was dispelled.

**Comment by djesic** [comment]
@Afgann not fixed correctly - not working on spell ticks. Partially fixed because now it works on cast

**Comment by djesic** [comment]
@Afgann any follow up on this?

**Comment by djesic** [comment]
@UltraNix I know it's not assigned to you, but you are my go to dev. Can you please look at last few comments and fix this?

**Comment by UltraNix** [comment]
Fixed.
