### ISSUE TITLE
QUEST BUGGED "Devoured"

### ISSUE THREAD

**Issue by NecroEM** [gamefreedomgit/Maelstrom#4763]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
We're supposed to let ourselves die. Except Thrall comes to save us, but that's not what happens. 

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=NeySF8trsII

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/147931928/cb33fed2-deef-47d6-aa6c-4d5909934298)

**Comment by NecroEM** [comment]
I managed to validate the "devoured" quest but it didn't teleport me to thrall's side.
So I'm stuck and can't complete the quest.
because I have to go to the maelstorm to join him.
screenshot : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/147931928/92c83758-06df-4e47-9153-3514acd719ca)

**Comment by PanJanuszek** [comment]
Can you make a ticket if you have still issues after abandon/retake quest?
