### ISSUE TITLE
alysra birds corpses

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4764]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** pls make alysrazor trash birds corpses disspaera after death like u did with onyxia body on bwd , becaseu we cant see the druids in the fight when they appear becasue of the bodies and its makes the fight harder

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
Only that happens in raid 25

**Comment by xmrshoot** [comment]
ye, only on 25
