### ISSUE TITLE
Archeology leveling not working.

### ISSUE THREAD

**Issue by brka4** [gamefreedomgit/Maelstrom#4766]
**Description:** I am stuck at 56 skill at archeology and can't level it further. After contacting the GM-s about this, they said that I should make my post here and seek your help.

**How to reproduce:** I don't know. I was leveling archeology, leveled the skill in ogrimmar to 125 and after that I stopped gaining skill levels. I made about 5-6 artifacts and dug a lot of sites, but I still can't recieve skill points to level it further. I tried going to the Eastern Kingdoms continent, thinking it will fix the bug, but it did not. I don't know what i'm supposed to do now.

**How it should work:** I should be able to gain skill points and level my archeology like everyone else.

**Database links:** I have no links, but I am Invisibilis on maelstrom on whitemane server.

**Comment by frostwave942** [comment]
after 50 i think, the only way to lvl arch is completing artifacts, not just clicking the shovel at some digsite.

**Comment by brka4** [comment]
I can't level archeology even with that. I completed about 5-6 artifacts and I'm not getting any.

**Comment by Sketish** [comment]
Please provide any video when you are completing artefact and no skill up is provided

**Comment by brka4** [comment]
I tried making artifacts today, and it seems like it started working as intended. I will keep you updated if I encounter another problem again. I'm currently at 66 skill.

**Comment by brka4** [comment]
This dig site in Dreamer's Rest in Kalimdor is bugged. The night elf urn is probably inside the terrain. Please help.

![Screenshot_7](https://github.com/gamefreedomgit/Maelstrom/assets/147941121/7a070c6f-a640-4d67-88f2-a8ddd8e09bef)
