### ISSUE TITLE
No radar for school of fish / No shcool of fish in Tol Barad Peninsula.

### ISSUE THREAD

**Issue by JulienRoux17** [gamefreedomgit/Maelstrom#4768]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.wowhead.com/item=53070/fathom-eel / https://www.wowhead.com/item=53072/deepsea-sagefish
Player can fish but cant see schools, so cant effectivly fish.
No school of fish in Tol Barad Peninsula including fathom eel, deepsea sagefish and others.
No radar available of fish from Cooking talent on the minimap filters list.

**How to reproduce:**
Druid balance 85, 525 fisherman / 525 cooking tried to fish in TBP.

**How it should work:**
Players should seek from the minimap radar shcools of fish as they can do for ores and plants.

**Database links:**
??

**Comment by Sketish** [comment]
there are schools
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/2ee05fd7-f155-46e1-9656-d701530fe1c2)
