### ISSUE TITLE
Skitterflame dies after a successful channeling of Tame Beast

### ISSUE THREAD

**Issue by AnsBal** [gamefreedomgit/Maelstrom#4770]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After successfully finishing the channeling of Tame Beast on the rare beast [Skitterflame](https://www.wowhead.com/npc=54324/skitterflame) the beast die.

**How to reproduce:**
Trap him 3 times with Freezing Trap until his rage is bellow 20 then cast Tame Best on him.

**How it should work:**
Skitterflame should be tamed instead of dead after successfully finishing the channeling of Tame Beast

**Comment by Sketish** [comment]
Please provide any video beacuse mob should die when reach 0 energy,

**Comment by AnsBal** [comment]
I didn't know it die when it reaches 0 energy. Closing.
