### ISSUE TITLE
jewelry mission

### ISSUE THREAD

**Issue by meshiach83** [gamefreedomgit/Maelstrom#4773]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you go to complete the jewelry missions it doesn't work, it doesn't allow you to continue
![Screenshot 2023-10-15 155648](https://github.com/gamefreedomgit/Maelstrom/assets/55325307/d76a9284-662a-43e0-ba14-94ed8c784a18)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Does relog fixed this ?

**Comment by meshiach83** [comment]
> ¿Relog solucionó esto?

It doesn't work, I've already relogged 3 times and nothing still doesn't work

**Comment by meshiach83** [comment]
I abandoned the mission, picked it up again and that's how it worked
