### ISSUE TITLE
Guild Achievement Bug

### ISSUE THREAD

**Issue by akaskales** [gamefreedomgit/Maelstrom#4774]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
We have several players with 525 skinning and honorable brotherhood+ reputations, such as Tonykiing, who is revered and still doesn't recognize his skinning for the achievement. We Need Help

**How to reproduce:**

is pasive bug

**How it should work:**

It should skip the guild achievement but it doesn't

**Database links:**
https://www.wowhead.com/es/achievement=4860/trabajar-en-equipo

https://cdn.discordapp.com/attachments/1056887467745222728/1163202568902680617/WoWScrnShot_101523_214959.jpg?ex=653eb7cf&is=652c42cf&hm=b03410d5ffdc9277f21cf102685a81c56351582854a00689f321da84246f7878&

https://cdn.discordapp.com/attachments/1056887467745222727/1163202596614455436/WoWScrnShot_101523_215021.jpg?ex=653eb7d6&is=652c42d6&hm=a2f71208b428910e854994333d89133da18b9d815e75e9e755f66563ca780b25&

**Comment by UltraNix** [comment]
#4075
