### ISSUE TITLE
RAG HC P4 Meteor not taking damage when frozen

### ISSUE THREAD

**Issue by Igria123456** [gamefreedomgit/Maelstrom#4775]
In one of our raids Meteor wasnt killable after being frozen even after refreezing twice. Could have something to do with the recent changes since meteors were taking full damage even after being unfreezed.

Clip link:
https://clips.twitch.tv/BlueSparklingClipzRaccAttack-kI-f62PqTYOzjFx8

**Comment by UltraNix** [comment]
Fixed.
