### ISSUE TITLE
[Hunter] [Pet] - Devilsaur can not be dismissed during EOTS prep

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4776]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
DIsmiss Pet fails on Devilsaur pets in EOTS bubble before game starts.
I think that the "base model" of these pets is larger and that's why it fails

**Comment by SimonBpvp** [comment]
you: I'll dismiss my pet.
Devilsaur: No.

**Comment by UltraNix** [comment]
Fixed.

**Comment by djesic** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/04ac940b-7d80-4b05-aa42-38ceeecb10fe)
@UltraNix 
Dismiss pet failed

**Comment by djesic** [comment]
Would taming a new devilsaur fix this perhaps?

**Comment by UltraNix** [comment]
@djesic What devilsaur is this?

**Comment by UltraNix** [comment]
@djesic No. Needs a fix in core.

**Comment by UltraNix** [comment]
Fixed.
