### ISSUE TITLE
HC Ragnaros P4 Meteors Delayed Death

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4778]
**Description:**
For some reason, there is around a 2-3 second delay between deaths on HC Ragnaros' P4 Meteors upon impact.

**How to reproduce:**
Go into P4 & get hit by a meteor, and wait 2-3 seconds before it kills you.

**How it should work:**
It should kill you immediately upon impact.

https://www.twitch.tv/videos/1951749059

Timestamp: 
02:18:00  
02:18:15

**Comment by Sketish** [comment]
I dont see any delay

**Comment by UltraNix** [comment]
Fixed.
