### ISSUE TITLE
Vainilla Tabard championing isnt working

### ISSUE THREAD

**Issue by caalanuaa** [gamefreedomgit/Maelstrom#4781]
**Description:**
When doing low lvl dungeons, at max lvl, rep from tabard is not being gained

**How to reproduce:**
Equip a classic Tabard, enter a dungeon and kill bosses

**How it should work:**
When you kill a boss, you should gain some reputation according to the tabard you have equipped

**Database links:**

https://cata-twinhead.twinstar.cz/?item=45583

**Comment by UltraNix** [comment]
Championing does not work in low lvl dungeons (as there is no rep on these dungeons for killing mobs/etc).
https://wowpedia.fandom.com/wiki/Championing
