### ISSUE TITLE
Fear Pathfinding is still bugged... 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4783]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warrior feared me in a battleground, Eye of the storm in this case and i fell down the map, didn't you guys posted this a while ago that it is fixed in 2 different reports about the fear bug?

Nothing is fixed, i also fell down in AB today from priest fear...

**How to reproduce:**
![WoWScrnShot_100123_154549](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/cb48e3cf-6005-4660-8263-89838f7783b5)
![WoWScrnShot_100123_154542](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/4f98f664-593d-4ef0-8b69-5b03856b4bf0)

See for yourself...
**How it should work:**

**Database links:**

**Comment by djesic** [comment]
I got ran off a base in EOTS yesterday as well. It was on BET - was at the top of the ramp, got feared next to house, right to the cliff where when the fear ended, I fell down the side

**Comment by oldspices** [comment]
i got feared down and off from LM today ha

**Comment by Afgann** [comment]
fixed
