### ISSUE TITLE
Can not Interact with Kor the Immovable

### ISSUE THREAD

**Issue by dheoab** [gamefreedomgit/Maelstrom#4787]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can not taking quest from Kor the Immovable at Deepholm to take the quest

**How to reproduce:**

**How it should work:**
It should be simply right clicking and take the quest

**Database links:**
![WoWScrnShot_101723_113618](https://github.com/gamefreedomgit/Maelstrom/assets/124854474/d78a7766-37fd-4666-a62b-6b7ee7771802)

**Comment by Sketish** [comment]
Please remove at war in reputation tab. It will solve the issue
