### ISSUE TITLE
-20% permanent penalty to spirit and weapon buff is 10 days

### ISSUE THREAD

**Issue by dorkfish2** [gamefreedomgit/Maelstrom#4788]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My resto sham has a -25% penalty to spirit, also the weapon buffs (flametongue) is lasting 10 days
I had a ticket with crywolf, and have deleted cache as well as done a full fresh install of the client
The error has persisted through full spec changes as well as 
![wow30](https://github.com/gamefreedomgit/Maelstrom/assets/44677481/c8cf1ce1-751a-4bd3-8cfc-cecb54b911c7)
reset
I receive this error when I log in:
Date: 2023-10-16 22:36:57
ID: 1
Error occured in: Global
Count: 1
Message: [string "code"] line 1:
   unexpected symbol near '='
Debug:
   [C]: ?
AddOns:
  Swatter, v3.3.0 (<%codename%>)
  Auctionator, v3.0.0
  Babylonian, v5.1.DEV.312(/embedded)
  BagBrother, v
  Bagnon, v4.3.25
  Configator, v5.1.DEV.323(/embedded)
  Gatherer, v3.3.0
  HealBot, v4.3.4.1
  Recount, v
  SlideBar, v3.3.0 (<%codename%>)
![wow30](https://github.com/gamefreedomgit/Maelstrom/assets/44677481/989da93e-461f-46a5-95b3-cc408d106663)

**How to reproduce:**
No clue, i think it has some thing to do with the Bloodlord Mandokir fight in Zul'Grub

**How it should work:**
I shouldn't have a penalty and the buff should be 30min

**Database links:**

**Comment by Hermeleen** [comment]
Rogues poisons are for 20 days, used to be hour. So i would assume there is flat multiplier that now gets also applied to sham weapon enchants. /clap from me, definitely nice change. But i have 0 idea about the spirit thing.

**Comment by dorkfish2** [comment]
I don't know if it helps but the spirit penalty scales with spirit on gear but not on procs

**Comment by UltraNix** [comment]
Extended Shaman temp enchants is a feature, not a bug.
[Author: itsemmastone
Message: Extend the duration of Shaman weapon enchantments to 10 days ](https://discord.com/channels/1040715551531618365/1045188444617461870/1163260985574969384)

**Comment by UltraNix** [comment]
About spirit - poke me on Discord @dorkfish2

**Comment by BalanCV** [comment]
The "spirit pentaly" and red stats come from reforging most of the time. Might not be a bug check that first.

**Comment by dorkfish2** [comment]
> The "spirit pentaly" and red stats come from reforging most of the time. Might not be a bug check that first.

This was the "problem" lol, here I was wondering if I could heal heroics like this and turns out I did it to myself XD

**Comment by Hermeleen** [comment]
> > The "spirit pentaly" and red stats come from reforging most of the time. Might not be a bug check that first.
> 
> This was the "problem" lol, here I was wondering if I could heal heroics like this and turns out I did it to myself XD

I literally thought, Nah i won't type that, that can't be it. :D well, at least you got it sorted out...
