### ISSUE TITLE
[Mage][Mirror Image] Clones are in passive mode when spawning

### ISSUE THREAD

**Issue by Crusaderz** [gamefreedomgit/Maelstrom#4790]
There was an incorrect [report ](https://github.com/gamefreedomgit/Maelstrom/issues/1143) that they should only attack when the player is attacking someone, however after watching a dozen Cataclysm videos it is unequivocal that when they appear they should instantly attack a target that is in combat with the player

mirror image are used when the enemy is behind a pillar, they spawn and immediately run behind the pillar to attack the target
https://youtu.be/Rys18Ay8PAQ?t=255

mirror image used after scorch, they instantly attack when they spawned
https://youtu.be/rfsQOCSsX1k?t=394 

Hansol's mirror image instantly attacks a water elemental when used (patch 4.3.3 btw).
https://youtu.be/u7W75EXoev4?t=480

In the same video ([exact moment](https://youtu.be/u7W75EXoev4?t=497))  you can see that the clones change the target if the current target is under CC effect. Hansol used Dragon's Breath on an opponent and his clones stopped attacking his opponent and switched to the opponent's clones, this is to the point that @UltraNix asked for proof in this [report](https://github.com/gamefreedomgit/Maelstrom/issues/2490) that clones should not attack opponents who are being CC.

The player used mirror image, time wrap, fire blast sequentially, the clones is attacking already at the moment of using time wrap
https://youtu.be/qGl-bIqAGcY?t=185

I think that's enough.

**Comment by firedragoon10** [comment]
btw  you dont see another  bug on mirror image wth fire spec wth glyph  the hit low damage than  without  glyph  and this one need tofix it

**Comment by UltraNix** [comment]
Fixed.
