### ISSUE TITLE
Bug npc - Therazane 

### ISSUE THREAD

**Issue by Ulfrasark** [gamefreedomgit/Maelstrom#4791]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Therazane bugged, location Deepholm, throne of Therazane , quest https://www.wowhead.com/quest=29337/into-constant-earth 

**How to reproduce:**

**How it should work:**
Therazane is not click-able as npc

**Database links:**
![изображение](https://github.com/gamefreedomgit/Maelstrom/assets/143724159/82ec600a-8326-48bc-a81a-1a3da7e06d4e)

**Comment by PanJanuszek** [comment]
Fixed after update
