### ISSUE TITLE
alchemy bonuses for flasks / all mixology stopped working yesterday

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4793]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
alchemy bonus for flask supreme power and distilled wisdom stopped working yesterday for some reason. i was getting the bonus of 2 hour duration and increased effect. and then it turned into 1 hour and no effect. i still have alchemy and i do have the pattern for the flask too. 

**How to reproduce:**

pop flask
**How it should work:**
It should put flask duration to 2 hours when you pop one. as well as a 40% bonus to the effect or whatever the % is (i think its 30% ish ) 

2 hour + bonus
**Database links:**
https://cata-twinhead.twinstar.cz/?item=13511

**Comment by imbanoobqt** [comment]
Mixology is not working. There is no duration increase nor effect increase. Flask of the Winds last only 1h and give 300 agility.  Because of Mixology it should last 2h and give 380 agility

**Comment by IvanCarMad** [comment]
Same here

**Comment by bekamika1** [comment]
I can confirm that Mixology is no longer working
