### ISSUE TITLE
Gylph of Totemic Recall 

### ISSUE THREAD

**Issue by AlpReal** [gamefreedomgit/Maelstrom#4794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Gylph of Totemic Recall does not seem to work at all. I get the same mana back with and without the glyph.

**How to reproduce:**
Get the glyph, recall your totems and compare it to the mana you get back without the glyph.

**How it should work:**
You get more mana back when the glyph is being equipped.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55552

**Comment by Afgann** [comment]
fixed
