### ISSUE TITLE
Stoneclaw Totem

### ISSUE THREAD

**Issue by AlpReal** [gamefreedomgit/Maelstrom#4795]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stoneclaw Totem does not give all totems a shield when you summon it via Call of the Ancestors.  

**How to reproduce:**
Put Stoneclaw Totem, Flametongue Totem, Healing Stream Totem and Wrath of Air in your Call of the Ancestors Totem Bar, summon the totems via Call of the Ancestors, only Flametongue Totem and Stoneclaw Totem will receive the absorb effect. Healing Steam Totem and Wrath of Air Totem miss the absorb effect.

**How it should work:**
All Totems should receive the absorb effect.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=5730

**Comment by Afgann** [comment]
fixed
