### ISSUE TITLE
Frenzyheart repu - Quest (The Mist isn't Listening)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4796]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after taking this <a href="https://www.wowhead.com/quest=12538/the-mist-isnt-listening">quest<a/> i can't attack those mistwhisper gorlocs so i can't complete the quest and i can't continue with the quest line.

**How to reproduce:**

as long as u gain repu with frenzyheart u'll be hated by the oracles, so take the quest and try to attack them at least for me it didn't work cos they're <a href="https://imgur.com/a/pusJB0x">not flagged "at war"</a> like any <a href="https://imgur.com/a/0v8emr3">enemy faction<a/>.

**How it should work:**

like any enemy faction in war i should be able to attack them.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
