### ISSUE TITLE
Moonwell chalice tether bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4797]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The way i see it this trinket works by dropping a chalice gameobject on use, then the gameobject targets the player with a tether and provides the buff.

Currently the tether activates instantly every time on FIRST USE ONLY.
If you use it multiple times during a fight the tether is either not connecting at all giving 0 buff, connecting after many seconds, or connecting and disconnecting randomly. This makes it a shit intellect stick for warlocks who want to snapshot their meta.

Could be a terrain issue as this happens constantly in the ragnaros pit, but I'm pretty sure I've had this happen on baleroc and ryolith as well. Don't have time to test it properly everywhere.

Proper fix would be to force tether action on gameobject spawn.
Improper fix, but personally recommended, would be to simply give players the buff on trinket use and disregard the shit gimmick item mechanic. Its a trash design for an item and any delay on the tether makes macroing it with metamorphosis useless since getting the buff miliseconds after ur meta invalidates the snapshot ending up crippled.

**How to reproduce:**

**How it should work:**

**Database links:**
https://cata-twinhead.twinstar.cz/?item=70142

**Comment by Sketish** [comment]
So only bug is that sometimes gameobject fall through textures and then trinket is not working

**Comment by BalanCV** [comment]
The chalice gameobject itself doesn't actually fall through the texture as I can see it lying there uselessly all the time, but it might be some minor height difference or terrain jankyness affecting it for sure.

**Comment by Afgann** [comment]
fixed
