### ISSUE TITLE
The great arena chest dont drop trinkets on 100% drop rate

### ISSUE THREAD

**Issue by jonslowjon** [gamefreedomgit/Maelstrom#4798]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the great arena chest dont drop trinkets on the right droprate, in cata its 100% normally gms spawn a new chest or send trinket to your mail when the trinket dont drop. But tide dont wont to do that anymore so im here.

I looted the 11 Pm chest today and the trinket didnt drop and prove in the chat - https://ibb.co/f4zymg8

**How to reproduce:**

**How it should work:**
100% droprate

**Database links:**
https://cata-twinhead.twinstar.cz/?object=179697

**Comment by oldspices** [comment]
this has been posted here many times just fyi

**Comment by Sketish** [comment]
So why duplicate reports ?
