### ISSUE TITLE
A TIME TO BUILD UP - EVENT QUEST (Criteria for Rotten Hallow Achievement)

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#4800]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

![ATTBU1](https://github.com/gamefreedomgit/Maelstrom/assets/133872309/2d8addff-406f-4aee-9f62-84e81afcdd62)

**Description:**
Darkcaller Yanka doesn't give me the quest mentioned above, we figured out with Tide that there is a prequest from Horde Commoners, but I can't interact with them, they don't give me the preq named "A Season for Celebration"

**How to reproduce:**

**How it should work:**

Get the preq from any horde commoner, then talk to Darkcaller Yanka to get the "A Time to Build Up" quest.

**Database links:**

https://www.wowhead.com/quest=29376/a-time-to-build-up

**Comment by UltraNix** [comment]
Fixed.
