### ISSUE TITLE
guardian elixir is overwriting battle elixir 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4801]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When i pop guardian it over writes battle, and vice versa 
**How to reproduce:**
i used the 2 listed in links below - but maybe it works for all? 

**How it should work:**
should have both up at once, as it used to do. 

**Database links:**
(https://cata-twinhead.twinstar.cz/?item=9179)
https://cata-twinhead.twinstar.cz/?item=3825

**Comment by UltraNix** [comment]
Fixed.
