### ISSUE TITLE
Up, Up & Away!

### ISSUE THREAD

**Issue by W0lkeris** [gamefreedomgit/Maelstrom#4802]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

rocket goes very slow
**How to reproduce:**
fix it

**How it should work:**
Rocket needs to go fast

**Database links:**

Up, Up & Away!

**Comment by Sketish** [comment]
Invalid report
