### ISSUE TITLE
egg pile alysrazor

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4806]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 1 of 2 is unattackable after update

**How to reproduce:**

**How it should work:**

**Database links:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/4e59b2b1-4e39-4f67-b78a-e5633110bfbb)

**Comment by UltraNix** [comment]
After a few seconds should be attackable.

**Comment by xmrshoot** [comment]
@UltraNix  we killed first pile and the second was unattackable
