### ISSUE TITLE
Hallow's End Event Quest

### ISSUE THREAD

**Issue by Cacao98** [gamefreedomgit/Maelstrom#4807]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Celestine of the Harvest should give the daily quest "A Time to Gain" Required for the achievement "Rotten Hallow" but she is not giving it. I have done all the other ones and previous requirements in order to unlock it.

**How to reproduce:**

**How it should work:**
She should give this daily each day but it is not happening.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29075

**Comment by UltraNix** [comment]
@Cacao98 Poke/DM me on Discord.

**Comment by PanJanuszek** [comment]
Fix after restart
