### ISSUE TITLE
baron ashbury calamity no cast

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4808]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** he is not casting calamity under 25% hp

**How to reproduce:** dps the boss to 25%

**How it should work:** he should cast it

**Database links:** https://www.wowhead.com/spell=93812/calamity?dd=6

**Comment by xmrshoot** [comment]
@UltraNix any fixes?

**Comment by UltraNix** [comment]
@xmrshoot Cannot reproduce it. The Archaengel Form was casted? Can you record it?

**Comment by xmrshoot** [comment]
never mind , its working well, i will close it
