### ISSUE TITLE
Quest: Incoming Gumdrop

### ISSUE THREAD

**Issue by Aurorre** [gamefreedomgit/Maelstrom#4809]
https://www.wowhead.com/quest=8358/incoming-gumdrop

**Description:**
I'm busy with the meta-quest https://www.wowhead.com/quest=8312/hallows-end-treats-for-spoops for the Halloween event.

Here you get a quest that you have to pass certain Innkeepers (1 of each faction) Then you do an emote and get some candy.
I did this quest (https://www.wowhead.com/quest=8358/incoming-gumdrop) once before the event was up (the quest showed up) without realizing I needed it for the Halloween meta quest.
Now Kali Remik (who is  in Oggrimar and not in Sen'jin village as the quest suggest) doesn't give the quest anymore since I already "completed" it

**How it should work:**
The quest should be available when the event is up.

If you need More information let me know (Aurorre-Maelstrom)

I tried later on to invite someone who hasn't done the quest to try and share. That is not allowed (grey un-clickable).

**Comment by UltraNix** [comment]
@Aurorre Poke/DM me on Discord.

**Comment by Aurorre** [comment]
Sent an invite on discord
