### ISSUE TITLE
Sinister Squashling bug for alts achiev after used

### ISSUE THREAD

**Issue by mego94** [gamefreedomgit/Maelstrom#4812]
The achiev 'Sinister Calling', needs to get the 'Sinister Squashling' and the 'Hallowed helm', i got the pet and used with an alt so the pet shows as Already known on the other toons, so those toons cant get the achiev's pet needs checked bcs that toon cant learn the pet.
If 1 toon gets the pet then it should be checked for each toon achiev, or it should be checked when the pet is in that toon's bag

**Comment by frostwave942** [comment]
achivs or progress with them are not linked to the acc atm. so if u want the achiv with ur main just mail the pet with ur alts and get the helm from killing headless horseman. i wish one day achivs would be linked to the acc btw.

**Comment by UltraNix** [comment]
Fixed.
