### ISSUE TITLE
sinister call bug

### ISSUE THREAD

**Issue by Juan023111** [gamefreedomgit/Maelstrom#4813]
Hello, I have a problem with the achievement Sinister Call to complete the Hallowed Be Your Name achievement the Halloween event asks me to get the Sinister Zucchini but I have already learned it but when I get another one the achievement does not jump to me, my character's name is Glio troll hunter, If you can help me, thank you very much.

**Comment by Sketish** [comment]
Please follow template and redo report so we can fix it
