### ISSUE TITLE
Flask and Elixir duration bug in Alchemist

### ISSUE THREAD

**Issue by escapeshot** [gamefreedomgit/Maelstrom#4814]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have 525 in Alchemy, my Flask and Elixir Duration become 1hour after offline for a month

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Same as  https://github.com/gamefreedomgit/Maelstrom/issues/4815

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/3bf8cb4b-d5f7-4374-b32b-bbcc7a87a4c1)
 its fixed , u can close it @Sketish
