### ISSUE TITLE
alchemy still bugged

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4815]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** it has 1 hour duration instead of 2 and 300 intel instead of 380

**How to reproduce:** just use flask with alchemy

**How it should work:** it should have 2 hours and 4 hours if used with cauldron and 380 intel

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/d71111ba-faf3-4ec3-a0e3-aaee5c0536a3)

**Comment by oldspices** [comment]
idk if the fix to this is making  mixology to not work, as well as battle elixirs overwriting guardian elixirs

**Comment by oldspices** [comment]
wtb mixology fix xd

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/99d97cd6-f6bc-4c66-8221-232d30a36390)
 its fixed
