### ISSUE TITLE
picture missing - Licence to Slay - ItemID 58180

### ISSUE THREAD

**Issue by Flamelush** [gamefreedomgit/Maelstrom#4820]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/147324291/df5111e3-1d0a-4a46-8798-06707a0de7b9)

Picture is now missing on the item. Can buy it okay, but it currently doesn't have an icon.

**Comment by xmrshoot** [comment]
u tried delete cache?

**Comment by UltraNix** [comment]
Yep - clear your cache folder.
