### ISSUE TITLE
hot streak Tier 4 fire mage spec dont work 

### ISSUE THREAD

**Issue by firedragoon10** [gamefreedomgit/Maelstrom#4821]
Tier 3 hotstreak gives you a small proc chance after getting 1 crit to give you hotstreak
tier 4 hotstreak is the 100% chance after getting 2 crits in a row
![bug fire mage](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/728e31a5-ecfb-4a05-af73-1d573ddd4656)

so  when i get 2 crit its not work and i dont get hot streak  f

**Comment by firedragoon10** [comment]
![fire bug 2](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/b36045f0-ed89-4c2e-a6e3-2c5a0be7e1d0)
one  more secreen  ... mean fire mage  get hot streak  only wth tier3 and  tier 4 spec  2crit 100%  hot streak   bug  and need to fix it

**Comment by Burstloolz** [comment]
https://cdn.discordapp.com/attachments/542395914862592011/1165294383864754317/amumu.jpg?ex=654653f7&is=6533def7&hm=c23f45a67bd4e2109681000015f037a69621070b24b7dddac10271ea6120c5f9&
is 
is true  is bug  bro

**Comment by firedragoon10** [comment]
Hot Streak - Rank 1/1 - Your spells no longer trigger Arcane Missiles. Instead, your critical strikes with Fireball, Frostfire Bolt, Scorch, Pyroblast, or Fire Blast have a chance to cause your next Pyroblast spell cast within 15 sec to be instant cast and cost no mana........  so only  this is work  tier 3 fire spec 
 tier 4 fire mage spec  : Improved Hot Streak - Rank 2/2 - Any time you score 2 non-periodic critical strikes in a row with your Fireball, Frostfire Bolt, Scorch, Pyroblast, or Fire Blast spells, you have a 100% chance to trigger your Hot Streak effect.

**Comment by firedragoon10** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/1da49c47-0d74-4303-9ee4-c839e72139d7)
tier 3 spec fire mage  Hot Streak

**Comment by firedragoon10** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/338935fd-9822-4e72-8cf0-3e6c86448198)
tier 4 spec fire mage :  Improved Hot Streak need to fix it

**Comment by firedragoon10** [comment]
![firebug 200](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/de571d0f-ac2a-402a-90f9-3b3ef4785e7c)
This picture makes it clearer that what I am saying is correct : tier 4 hotstreak is the 100% chance after getting 2 crits in a row is bug

**Comment by firedragoon10** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/130104876/0210ba80-9609-4ba8-9a68-e83d04c75807)

**Comment by firedragoon10** [comment]
and how you can test it  : just spam fireball  on dommy  till when you get  2 fireball hit crit  or one crit  fireball  and one crit  pyro coem from  hostreak   coming  from  (Tier 3 hotstreak gives you a small proc chance after getting 1 crit to give you hotstreak ) and when both of them hit crit  you will see no hostreak proc  after 2 crit

**Comment by HappyHurricane90** [comment]
It has been 3 weeks since this was posted, when can we expect an update?

**Comment by UltraNix** [comment]
@firedragoon10 Just tested and everything works okay to me. Two crits in a row (fireball + pyroblast).
![obraz_2023-12-11_174252406](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/8994da40-2a7d-4b89-a966-65e71b78a635)

I need more info on this. Maybe you can record a video with combat log (with timestamps)?

**Comment by UltraNix** [comment]
No further info - closing.
