### ISSUE TITLE
Buged lava pool at Molten Front

### ISSUE THREAD

**Issue by Noisefr3ak** [gamefreedomgit/Maelstrom#4822]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a lava pool that everytime you enter you leave combat

**How to reproduce:**
Just enter the pook and out of combat

**How it should work:**
Enter the pool dont leave combat :D

**Database links:**
![εικόνα_2023-10-20_223234536](https://github.com/gamefreedomgit/Maelstrom/assets/108414976/27e85097-a129-4589-8de5-e1e9279a7b36)

**Comment by UltraNix** [comment]
Fixed.
