### ISSUE TITLE
Necrotic Strike casting speed slow (30%) and Mind Numbing Poison casting speed slow from snake trap (Also 30%) stacking

### ISSUE THREAD

**Issue by Will058** [gamefreedomgit/Maelstrom#4823]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Necrotic Strike casting speed slow (30%) and Mind Numbing Poison casting speed slow from snake trap (Also 30%) are stacking, resulting in super high cast reduction in pvp. 

**How to reproduce:**

Use necrotic and snake trap on a target, wait till snakes apply mind numbing, then make said target cast a spell. 

**How it should work:**

These should never stack, similarly to curse of tongues/mind numbing from rogues never stacking with necrotic. I don't know if necrotic or the snake trap mind numbing is the issue, it could be that either of these are currently stacking with other casting speed reduction effects that they shouldnt.

**Database links:**

**Comment by Revly** [comment]
What is your backup source, to say: These should never stack?

**Comment by UltraNix** [comment]
Fixed.
