### ISSUE TITLE
[Rogue][PVP] Multi-shot and Impact breaks stealth

### ISSUE THREAD

**Issue by Crusaderz** [gamefreedomgit/Maelstrom#4827]
Probably also "chain lightning".

multi-shot and chain lightning do not break stealth since vanilla. "Impact" boosted fire blast also shouldn't be a spell that knocks everyone out of stealth for 12 yards around the target, this radius is 50% larger than blizzard, freeze, ring of frost by the way.

**Comment by oldspices** [comment]
i seem to recall this .  is warlock pet cleave a cleave or aoe ? that gets me out of stealth but idk

**Comment by UltraNix** [comment]
@Crusaderz Please - provide some sources from retail.
In general, any damage taken should remove stealth.

**Comment by Crusaderz** [comment]
@UltraNix 

I'm afraid it's impossible to provide a source for something that never happened.

I've been playing since 2006 and I remember that only in early versions of WoW multi-shot & chain lightning dealt damage to invisible targets, but that was fixed by rule - damage only deals to visible targets as these spells require a target. Yes, multi-shot has changed since then and no longer does damage to three targets, but the point remains the same, it requires a target to use, just like fire blast (Impact).

I was knocked out of stealth at almost maximum distance at a 90 degree angle from the hunter. 

Blizzard has never specifically given players the ability to randomly knock enemies out of invisibility at a huge range, any more than Blizzard, Flare, Rain of Fire, Death & Decay which have an 8 yard radius and can be used against invisible targets. Impact is 12 yards, and multi-shot is 40 yards frontal (up to 90 degrees, as it turns out).

There were instances where some AOE spells worked this way, but Blizzard fixed it.

Example №1.

In WOTLK, the Starfall spell was knocking out stealthers. There were many threads on this topic on the forums (with tons of pages) they can still be found on mmo-champion.
Blizzard has fixed it.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/525025b4-b353-4ca0-824e-01b1dd437955)

Example №2.

In 2015, the Barrage (rapidly fires a spray of shots for 3 sec, dealing physical damage to all nearby enemies in front of you) 
spell knocked out stealth. There is a 9 page thread on mmo-champion where they discuss how unfair this is and that it should be fixed, citing the case of Starfall in WOTLK as an example (note nothing about Impact or Multi-Shot). Blizzard responded to this in the following way:

![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/452164ab-0dc5-4813-93b8-578ca10b093e)

I'd like to point out to you that Multi-Shot is very similar to Barrage, same distance and radius.

Based on these examples, I think you can understand Blizzard's approach to invisible targets and AOE spells beyond the standard 8 yards. I also can't find any mention of "impact stealth" and "multi-shot stealth" on google while "starfall stealth", "barrage stealth" will show a bunch of results with player complaints. That's a indirect indication as well. So hopefully, based on what has been written above, the necessary corrections will be made to these spells.

**Comment by UltraNix** [comment]
The difference between Multi-Shot and Chain Lightning is that MS is no longer chain spell - it's now an AOE spell in terms of blizzard definition of it. On wotlk, Multi-Shot was as Chain Lightning. So yeah - they were changes made to Multi-Shot since Wotlk.
Starfall and Barrage are both AOE spells, not chained.
All I need now is a proof that Multi-Shot should not break stealthed targets on cata.

**Comment by Crusaderz** [comment]
@UltraNix 

>All I need now is a proof that Multi-Shot should not break stealthed targets on cata.

it is not possible, rare cases of using multishot in PVP is perhaps only to interrupt the capture of the flag. Cataclysm era video with a rogue's POV where it happens just can't be found.

All we have is common sense and an understanding of how Blizzard treats such AOEs pre-Cataclysm and post-Cataclysm when it comes to randomly knocking stealth classes out of stealth. Example above.

Earlier you said:
>In general, any damage taken should remove stealth.

It's true, it's just that these spells (impact, multi-shot) shouldn't hit invisible targets.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/760f7ed7-6725-41a0-b310-8a987e21110a)

I think if there was a MoP expansion on the server and this spell was knocking out invisible targets, you'd argue that it should work that way since it's a frontal AoE. If we didn't have patch notes saying it no longer does damage on invisible targets, we'd be left with this bug forever, logically correct, but not a blizzlike.

**Comment by UltraNix** [comment]
I can't do anything with this without proof - it's too big change. As I said earlier, Multi-Shot was changed and is no longer chained spells (as Chain Lightning) - thus right now it does reveal steathled targets.

**Comment by Crusaderz** [comment]
I guess we'll have to wait for the retail cataclysm and then we'll see how it should work.

**Comment by UltraNix** [comment]
I'll close this one due to lack of evidences.
Report it again once we have more info about this
