### ISSUE TITLE
[Hallow's End] Hallowed Wand - Bat

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#4828]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Experienced an issue with [Hallowed Wand - Bat](https://cata-twinhead.twinstar.cz/?item=20410) where once cast onto a party member, the player was unable to right-click and remove the buff. Relog and /cancelaura did not resolve. Because [Hallowed Wand - Bat](https://cata-twinhead.twinstar.cz/?item=20410) prevents the player from mounting, this could be prone for abuse. Casting a different wand onto the player to overwrite the previous transformation, in this case [Hallowed Wand - Pirate](https://cata-twinhead.twinstar.cz/?item=20397), then allowed the player to mount. 

**How to reproduce:**
Cast [Hallowed Wand - Bat](https://cata-twinhead.twinstar.cz/?item=20410) onto a party member and attempt to right-click to remove the buff.

**How it should work:**
Player should have the ability to right-click and remove the [Hallowed Wand - Bat](https://cata-twinhead.twinstar.cz/?item=20410) transformation. 

**Database links:**
https://cata-twinhead.twinstar.cz/?item=20410

**Comment by Aurorre** [comment]
Quick fix that I used was to use the in-game unstuck function. You die and get placed at a nearby spirit healer and can walk back to your corpse.

**Comment by UltraNix** [comment]
Fixed.
