### ISSUE TITLE
[Hallow's End] Hallow's End Pumpkin Treat

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#4829]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Hallow's End Pumpkin Treat](https://cata-twinhead.twinstar.cz/?item=20557) is a common quest reward during the Hallow's End event. Currently, the treats provide no character transformation effect when consumed. 

**How to reproduce:**
Consume [Hallow's End Pumpkin Treat](https://cata-twinhead.twinstar.cz/?item=20557).

**How it should work:**
There should be a pool of possible forms, some with their own accompanying effects, that may be applied to the character once consumed. For example, Ghost form which includes levitate, Pirate form which includes a swim speed bonus. There are also effects that increase character size and turn the player orange.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=20557
https://web.archive.org/web/20120415064630/http://www.wowhead.com/item=20557

**Comment by UltraNix** [comment]
Fixed.
