### ISSUE TITLE
[Hallow's End] Candy Bucket

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#4830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This is a minor finding related to every [Candy Bucket](https://cata-twinhead.twinstar.cz/?object=190039). Each Candy Bucket gossip menu presents the character with two quest turns instead of one. The player may only accept and complete one quest, but on initial interaction with the bucket, two quests are presented. 

**How to reproduce:**
Visit any Candy Bucket from any world location. 

**How it should work:**
Only one quest turn in should be present.

![](https://i.imgur.com/QNuphrO.png)

**Database links:**
https://cata-twinhead.twinstar.cz/?object=190039

**Comment by UltraNix** [comment]
Fixed.
