### ISSUE TITLE
[Hallow's End] Fencing the Goods

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#4832]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This is a visual issue during the [Fencing the Goods](https://cata-twinhead.twinstar.cz/?quest=29398) quest. The quest description states: Follow the spiders to their destination and question the man you find there. The spiders are not present.

**How to reproduce:**
Accept [Fencing the Goods](https://cata-twinhead.twinstar.cz/?quest=29398). Observe.

**How it should work:**
As the player accepts the quest, a trail of spiders should guide the player to the quest objective, as shown below. 

![](https://wow.zamimg.com/uploads/screenshots/normal/800901-fencing-the-goods.jpg)

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29398
https://cata-twinhead.twinstar.cz/?spell=100618

**Comment by UltraNix** [comment]
Fixed.
