### ISSUE TITLE
Hallow's end candy

### ISSUE THREAD

**Issue by Flamelush** [gamefreedomgit/Maelstrom#4833]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Is making some characters too big to get through doors by hovering too far off the ground.  Have only tried it with a Draenei.
picture below

![image](https://github.com/gamefreedomgit/Maelstrom/assets/147324291/f74ebe8a-a739-4e89-b39a-c2de6b4a3648)

**Comment by Waroxx-QA** [comment]
It happens with size buffs in general 
It was happening in retail so idk
I'll keep it open.

**Comment by UltraNix** [comment]
Not a serverside bug.
