### ISSUE TITLE
Jewelcrafting Figurine Quest Can not be completed

### ISSUE THREAD

**Issue by dheoab** [gamefreedomgit/Maelstrom#4836]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I already have all the reagents for some broken JC figurine quest  but the quest can not be completed

**How to reproduce:**

**How it should work:**
Should be completed once i have all the reagents

**Database links:**
![WoWScrnShot_102123_214149](https://github.com/gamefreedomgit/Maelstrom/assets/124854474/b44f5525-f9c9-459a-9eea-1cc9a86f6525)

**Comment by PanJanuszek** [comment]
This is common client issue, where if you abandon and re-take quest it will work.
