### ISSUE TITLE
Quests in western plauges not working 

### ISSUE THREAD

**Issue by Beaniecow** [gamefreedomgit/Maelstrom#4839]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quests supporting the troops and ashes to ashes aren't working 

**How to reproduce:**

**How it should work:**
Killing andorhal defenders should count out of 15. So one kill should make it 1/15 but it stays at 0

**Database links:**

**Comment by Sketish** [comment]
Invalid report, follow template
