### ISSUE TITLE
Hunter's flare bugs

### ISSUE THREAD

**Issue by AnsBal** [gamefreedomgit/Maelstrom#4840]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I found two bugs related to hunter's flare. I'm not sure if I should create two issues. Ill open one for now.

- Flare's debuff is not dispellable. For instance, abilities like the rogue's cloak of shadows shouldn't remove it.
- When under flare, a rogue casting stealth will go invisible when he walk out of flare radius even in combat.

**How to reproduce:**
First bug: Use flare then have a rogue cast cloak of shadows to remove the debuff
Second Bug: 1) Use flare then have a rogue cast stealth. 2) Make the hunter auto attack him. 3) Make the rogue walk out of flare's radius and watch him go invisible.

**How it should work:**
First bug: Flare's debuff is not dispellable. For instance, abilities like the rogue's cloak of shadows shouldn't remove it.
Second Bug: The rogue that cast stealth shouldn't go invisible after he walks out of flare. Instead, stealth should immediately be on cooldown after being casted.

**Comment by Sketish** [comment]
Please provide any retail videom from cataclysm for confirmation of 2nd issue

**Comment by AnsBal** [comment]
I found classic wow video that show that interaction between stealth and flare but no video of cataclysm.

**Comment by AnsBal** [comment]
Can the first issue be fixed since it's confirmed. I will create a separate issue for other bug.

**Comment by UltraNix** [comment]
Fixed.
