### ISSUE TITLE
post bug

### ISSUE THREAD

**Issue by VarianXia** [gamefreedomgit/Maelstrom#4841]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[//]: # (http://whitemane.org/)
i send myself a post for 10000G,  and i received that post, but dont have any golds,just have a post name 10000,where  is my golds?
**How to reproduce:**
addresser name: Damsgaard
received name: Bachh

**How it should work:**
those golds should got to my bag,but not

**Database links:**

**Comment by Rezalution75** [comment]
WSG - Supreme Defender achi - not registering kills against flag runners started the BG with 57 killed 5 flag runners and only gone upto 58

**Comment by Sketish** [comment]
@VarianXia  contact Gaga on discord
