### ISSUE TITLE
Gilneas Drood Starting Quest : "MoonFire"

### ISSUE THREAD

**Issue by Melaycast** [gamefreedomgit/Maelstrom#4842]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hi, As a new Worgen Drood, i had encounter a strange quest that is impossible to validate 

This one called "Moonfire" in military sector of Gilneas, given by Celestine of the Harvest (The drood trainer).
Only available for drood, tell you to cast a moonfire spell on nearby hostile worgen but i can't validate it, even after log out or giving up it and relaunch afterward.

Character : Graylupus

**How to reproduce:**

Just start "Moonfire" quest and try to cast it on worgen nearby, it won't validate it

**How it should work:**

It should validate it after you cast one Moonfire on any mob nearby 

**Database links:**

https://www.wowhead.com/quest=14283/moonfire#comments
Quest No 14283 (Retail database)

Thanks !

**Comment by Melaycast** [comment]
In addition, This quest is required to continue your adventure, otherwise you can't go forward cause there is no other quests you can do 

Thanks a lot

**Comment by GM-Nightmare** [comment]
Quest is working fine , just translation error , Use rejuvenation on a wounded guard and it will complete the quest
