### ISSUE TITLE
fl bug when switch difficulty

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when we want to swap fron nm to hc it says loot remaining on boss , but no loot , as you can see warrior was raid leader, he cant swap cuz says loot remaining , he gave me lead and i cound change without showing me error with loot on boss , becasue was no loot , only bugged

**How to reproduce:**try to swap to nm to hc
![WoWScrnShot_102223_152601](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/0b2ce2ca-605f-4257-bb3c-e964736c7fbc)

**How it should work:** no error loot remaining

**Database links:**
![WoWScrnShot_102223_152617](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/2edd0f20-8e99-4eaf-8687-810d9f5c66ee)

**Comment by xmrshoot** [comment]
and its not first time happening , it happens all time and sometimes we must exit rai all and change the difficulty outside

**Comment by GM-Nightmare** [comment]
as a temporary fix , go outside the instance (get out of firelands) and you can switch it outside =)

**Comment by xmrshoot** [comment]
i know , i said that , but its a bug

**Comment by UltraNix** [comment]
@xmrshoot It was Master Loot?

**Comment by xmrshoot** [comment]
@UltraNix it was ml yes , no items left , everybody took cinders and embers and all stuff
