### ISSUE TITLE
WSG - Supreme Defender 

### ISSUE THREAD

**Issue by Rezalution75** [gamefreedomgit/Maelstrom#4844]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Not registering kills to flagrunners started game on 57 killed 5 flagrunner and returned flag only moved to 58

**How to reproduce:**

**How it should work:**
123456789

**Database links:**

**Comment by Sketish** [comment]
Invalid report
