### ISSUE TITLE
Moonfire Sunfire

### ISSUE THREAD

**Issue by GuidoSettecerze** [gamefreedomgit/Maelstrom#4845]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I aplly a Moonfire DoT, and then I apply a Sunfire DoT, the target should have both DoTs, but one overlap the other...

**How to reproduce:**
ussing Moonfire then Sunfire on Eclipse Solar

**How it should work:**
Stay both Dots.

**Database links:**
https://www.wowhead.com/spell=8921/moonfire
https://www.wowhead.com/spell=93402/sunfire

**Comment by xmrshoot** [comment]
it was bugged , not it works fine , what u say here is the bug that was fixed

**Comment by GuidoSettecerze** [comment]
Yes was working well, but I test it today and the bug is again !

**Comment by Sketish** [comment]
https://youtu.be/3C9Z5qLYABA?t=22  invalid report, it should replace each other
