### ISSUE TITLE
Blackrock Spire Shadow Hunter Vosh'gajin Broken Mechanic

### ISSUE THREAD

**Issue by irondan401** [gamefreedomgit/Maelstrom#4846]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Shadow Hunter Vosh'gajin's hex mechanic allows the boss to continue attacking and damaging hexed players while they are hexed. The mechanic is inoperable and uninterruptable. Needs to be fixed.

**How to reproduce:**
Engage Shadow Hunter Vosh'gajin

**How it should work:**
https://www.youtube.com/watch?v=c6j4-Gs8wQs

**Database links:**
https://www.wowhead.com/classic/npc=9236/shadow-hunter-voshgajin

**Comment by PanJanuszek** [comment]
fixed 10.05.2024
