### ISSUE TITLE
Moonwell chalice still not fixed

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Maelstrom#4847]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Message: DB/Scripts: Fix Moonwell Chalice channeling effect sometimes not applied on spawn. https://github.com/gamefreedomgit/Maelstrom/issues/4797 

Height difference  and minor terrain differences like rocks or platforms still mess it up as you can see in the photo.
Just make it ignore LoS already.

**How to reproduce:**
https://imgur.com/a/Tm3oxiE

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
