### ISSUE TITLE
Hunter Pet BG !

### ISSUE THREAD

**Issue by CDreger** [gamefreedomgit/Maelstrom#4848]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have problems with my pets when joining and playing bg !
1. When joining BG Pet ist often passive or after getting back to life on Graveyard !
2. When pet dies , i have to reanimate him 2 time, After first time he returns dead! After secound time he come back to life!
3. Some time in the BG i dont know  where the pet is or what he is doing. Does not comeback when i call him back !

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@CDreger More details required:
1. Before enter BG, your pet was on assist mode?
2. You are trying revive your pet when its out or maybe despawned?
3. Need some screenshoot or videos about this.

**Comment by UltraNix** [comment]
No further info - closing.
