### ISSUE TITLE
Disc priest penance does not stack grace if target is los

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4849]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Disc priest penance does not stack grace if target is los
**How to reproduce:**

start penance on someone then have them go out of los
**How it should work:**
it should give grace stacks for each heal 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
