### ISSUE TITLE
Dragonmaw Clan reputation

### ISSUE THREAD

**Issue by Ulof2** [gamefreedomgit/Maelstrom#4850]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Just finished Dragonmaw Clan reputation, got exalted, but I didn't get the achievement for it.

**How to reproduce:**

**How it should work:**
I should get the achievement when I get exalted with Dragonmaw Clan

**Database links:**
https://www.wowhead.com/achievement=4886/dragonmaw-clan

![WoWScrnShot_102323_190838](https://github.com/gamefreedomgit/Maelstrom/assets/148795072/3ce35faf-43c1-4a2b-aad0-a71dd0508655)

**Comment by UltraNix** [comment]
@Ulof2 Do you remember how and when did you get the exalted?

**Comment by Ulof2** [comment]
I farmed reputation in heroic dungeons using a tabard. Though I don't remember when exactly it was. Probably 1 or 2 days before I took this screenshot.

**Comment by Ulof2** [comment]
Am I ever going to get my achievement?

**Comment by UltraNix** [comment]
@Ulof2 Poke me on Discord.
