### ISSUE TITLE
[Balance Druid] Eclipse Power Being Generated on Cast Instead of on Hit

### ISSUE THREAD

**Issue by JimboLimbo175** [gamefreedomgit/Maelstrom#4851]
**Description:**
In Cataclysm, Solar and Lunar energy granted by spells should be generated when the spells hit the target, with the recent changes it is being incorrectly generated on spell cast. 
Note that the Lunar energy granted by the Balance T12 4p set bonus is still being generated on hit instead.

**How to reproduce:**
Cast Wrath or Starsurge from range, observe Eclipse power being generated on cast instead of on hit.

**How it should work:**
Eclipse power should be generated on spell hit.
Proof: check around 2:25 of this video https://www.youtube.com/watch?v=_GX4p1pwzOo, observe how the Eclipse bar doesn't move towards Lunar until Wrath hits the dummy.

**Comment by UltraNix** [comment]
Fixed.
