### ISSUE TITLE
[Balance Druid] Eclipse not Being Reached Despite Reaching 100 Lunar/Solar Energy

### ISSUE THREAD

**Issue by JimboLimbo175** [gamefreedomgit/Maelstrom#4852]
**Description:**
It often occurs that the Eclipse state is not reached even after reaching 100 Lunar/Solar energy. An additonal cast of Wrath/Starfire/Starsurge is then required to reach the eclipse state. This happens reliably when 100 energy is reached because of the Balance T12 4p set bonus (i.e. being at 75-79 Solar energy and casting Starfire without Euphoria or DTR proccs), but this is not necessarily the only scenario in which it happens. Possibly related to https://github.com/gamefreedomgit/Maelstrom/issues/4851 due to the order of events/eclipse state checks.

**How to reproduce:**
Reliable way, not necessarily only way: 

1. Equip a Balance druid with Balance T12 4p set bonus.
2. Starting from neutral, cast 3 Starfires in a row (ensure no Euphoria or DTR proccs).
3. You should now be at 75 Solar Energy.
4. Cast Starfire (ensure no Euphoria or DTR proccs)
5. You will now be at 100 Solar Energy but Eclipse state will not have been reached.

This can similarly happen towards Solar Eclipse by casting Wrath at 84-86 Lunar Energy.

**How it should work:**
Eclipse State should be granted always upon reaching 100 or more Solar/Lunar Energy.

**Screenshots:**
I use the BalancePowerTracker Addon to keep track of Solar/Lunar Energy. The addon is showing correct energy in the following screenshots.
100 Solar Energy and no Solar Eclipse:
![100 Solar No Eclipse](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/6f0a5a44-67ae-4170-b466-dd3768412b92)
100 Lunar Energy and no Lunar Eclipse:
![100 Lunar No Eclipse](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/a3e6254f-8d73-4fd6-b068-0a6a1e40e778)

**Comment by UltraNix** [comment]
Fixed.
