### ISSUE TITLE
raid leader assist

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4853]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when you pass raid leader it doesnt keep you as assist

**How to reproduce:**
give someone raid leader

**How it should work:**
it should let you still be assist when you pass raid leader to someone

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
