### ISSUE TITLE
[Balance Druid] Shooting Stars not Working if it Is Gained During Starsurge Cast

### ISSUE THREAD

**Issue by JimboLimbo175** [gamefreedomgit/Maelstrom#4854]
**Description:**
Getting a Shooting Stars proc while casting Starsurge will cause the Shooting Stars buff to remain on the player but Starsurge will remain on cooldown, preventing Starsurge from being cast.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/5058aeff-ba3f-483b-a076-0ac44100dec5)

**How to reproduce:**
1. Apply Insect Swarm and Moonfire/Sunfire to the target. Refresh them if they fall.
2. Start casting Starsurge, but cancel the cast before it ends to prevent it going on cooldown (for the purposes of testing).
3. Repeat step 2 until you get a Shooting Stars proc while mid Starsurge Cast. In this case let the cast finish.
4. Observe Starsurge remaining on cooldown despite having the Shooting Stars buff.

**How it should work:**
When gaining the Shooting Stars buff while casting Starsurge, Starsurge should remain off cooldown until the Shooting Stars buff is consumed with an instant Starsurge. (Or Starsurge is cast normally after the Shooting Stars buff runs out without being consumed.)

**Comment by Sketish** [comment]
Provide retail video of this issue

**Comment by hamyhamz** [comment]
It is really hard to find the video for this, so let me know if the following is not clear enough for you to decide. 

https://youtu.be/ghlHHZeYR94?t=1058 in this video it is really close to call it, but if you compare it to the regular procs then it's clearly this case. He got the proc right at the end of the cast time (you can slow it down to see it better). The spell went on CD briefly and reseted its cooldown.

**Comment by bonfax4** [comment]
@Sketish 

Well if this helps, this used to be an issue early on in cata until it was hotfixed. Only caveat is there was some sort of delay that prevented you to cast starsurge into starsurge instantly and I'm not sure if that was intentional or a latency issue, but some ppl complained about it in forums.

https://www.mmo-champion.com/threads/817156-Boomkin-Starsurge-and-Shooting-Stars-effect-delay

https://www.mmo-champion.com/threads/921529-Lava-Surge-vs-Shooting-Stars

2012 - Even at the end of cata there's mentions of a "delay". 

https://www.mmo-champion.com/threads/1217873-Starsurge-and-ShootingStars

> If you get a proc during starsurge you should channel wrath or starfire since you won't be able to use the proc until the first one actually lands.

https://web.archive.org/web/20120915035015/wowhead.com/spell=93399

> By guatafu (14,276 – 3·7·131) on 2012/03/04 (Patch 4.3.3) | Report |  
> 
> Due to client delay and personal lag, you will not be able to cast back-to-back starsurge if this procs while you're casting one already, it takes about 1-2 secs for the client to confirm that it its valid to cast the spell. This is an issue with several abilities from other classes as well, like Kill Shot from Hunters or Hammer of Wrath from Paladins, it will probably never be fixed.<br><br>With this in mind it is better to queue another spell right after you finish casting your starsurge and use the shooting stars proc afterwards.</div>

**Comment by Sketish** [comment]
So cooldown should reset if player has shooting star buff and previous cast hit the target.

**Comment by bonfax4** [comment]
https://youtu.be/nKxHAdQsz4o?t=572 You can see it here it goes on cd but resets after few seconds when ti procced mid surge cast. Not a huge travel time so can't say if it was before/after it landed.

**Comment by UltraNix** [comment]
Fixed.

**Comment by cataboomie** [comment]
> Fixed.

Not fixed.
**https://youtu.be/_3gmagZKgOQ**

**Comment by bonfax4** [comment]
> > Fixed.
> 
> Not fixed. **https://youtu.be/_3gmagZKgOQ**

Yes it is. You fired 2  Starsurges back to back almost because you were close enough. What is wrong in that video ?

**Comment by cataboomie** [comment]
> > > Fixed.
> > 
> > 
> > Not fixed. **https://youtu.be/_3gmagZKgOQ**
> 
> Yes it is. You fired 2 Starsurges back to back almost because you were close enough. What is wrong in that video ?

There is like 1 sec delay between first and second Starsurge. Both should go in the same time.

**Comment by bonfax4** [comment]
> > > > Fixed.
> > > 
> > > 
> > > Not fixed. **https://youtu.be/_3gmagZKgOQ**
> > 
> > 
> > Yes it is. You fired 2 Starsurges back to back almost because you were close enough. What is wrong in that video ?
> 
> There is like 1 sec delay between first and second Starsurge. Both should go in the same time.

Nah see the videos I linked above. Casted starsurge needs to land for the reset to occur.
