### ISSUE TITLE
Fire mage  Impact 

### ISSUE THREAD

**Issue by UlicaTV** [gamefreedomgit/Maelstrom#4855]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Impact](http://cata-shoot.tauri.hu/?spell=12355) Icon Impact is up. DoTs are spread with their current remaining time. Spreading Living Bomb causes Living Bomb to affect two nearby enemies (in addition to the current target).

**How to reproduce:**
Hello, I have tested and there are about 3 variants where it does not work
1- [Lord Rhyolith] when they appear - [Fragment of Rhyolith]
2- [Ragnaros] when they appear - [Son of Flame] I think he tells them or more precisely in the 2nd phase when he explodes [Lava Bolt]
3- [Occu'thar] when [Eyes of Occu'thar] appear

**How it should work:**

in all 3 situations, as far as I know, he had to anoint the spread
**Database links:**

I still don't have it, I'm going to investigate and I'm waiting for the rest of the characters (mage) to give their opinion

**Comment by SexyPancake** [comment]
What's the issue?

**Comment by UlicaTV** [comment]
> What's the issue?

the problem is that normally it has to work and throw the endowments on other targets as well

**Comment by UlicaTV** [comment]
> What's the issue?

Impact is up. DoTs are spread with their current remaining time. Spreading Living Bomb causes Living Bomb to affect two nearby enemies (in addition to the current target).

**Comment by SexyPancake** [comment]
Living Bomb has a 3 target limitation, what's the issue.....

**Comment by UlicaTV** [comment]
ignite has no limit and pyro dot + combination ...

**Comment by UltraNix** [comment]
@UlicaTV Still don't know what is the issue, what does not work on our server and how it should work.
