### ISSUE TITLE
Monitoring the Rift: Cleftcliff Anomaly Quest cannot be completed

### ISSUE THREAD

**Issue by ichuhan** [gamefreedomgit/Maelstrom#4856]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I went to the right place to finish the quest several times, it keeps saying that Anomaly required.
![WoWScrnShot_102423_111619](https://github.com/gamefreedomgit/Maelstrom/assets/148836574/09f7a65c-844d-4107-b618-0630f065b289)

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/quest=11576/monitoring-the-rift-cleftcliff-anomaly
https://www.youtube.com/watch?v=yyPcwLNOK0A&ab_channel=TomSanGames

**Comment by PanJanuszek** [comment]
Fix soon

**Comment by ichuhan** [comment]
Quest completed. Thank you!

PanJanuszek ***@***.***> 于2023年10月25日周三 23:21写道：
