### ISSUE TITLE
Quest "Cruel Intentions" is not available

### ISSUE THREAD

**Issue by S1rL00t4l0t** [gamefreedomgit/Maelstrom#4857]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest Cruel Intentions is not offered by Nazgrel in Hellfire Peninsula after finishing every other quest of that quest chain

**How to reproduce:**
Do the quest chain

**How it should work:**
After finishing Doorway to the Abyss Nazgrel should offer the quest

**Database links:**
https://www.wowhead.com/tbc/quest=10136/cruels-intentions#comments

**Comment by PanJanuszek** [comment]
Fix soon
