### ISSUE TITLE
raid markers bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4858]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** i cant clear them to put news one

**How to reproduce:**

**How it should work:**

**Database links:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/2b9d56d6-d22a-4596-8c87-fa88cb31502a)

**Comment by UltraNix** [comment]
@xmrshoot Please, take a shot on this.

**Comment by xmrshoot** [comment]
its ok now , thx @UltraNix
