### ISSUE TITLE
Last Word Paladin Talent possible bug ?

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4859]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The talent gives 60% increased critical strike chance to heal from word of glory on targets at 35% hp or below 35% low hp.

I have the best gear possible in PvP for my paladin plus elite weapons but the talent rarely crits at 35% hp or below 35% hp, especially on my arena partners.

Can you check the database for the percentage bonus? 

Maybe it is bugged?

**How to reproduce:**

**How it should work:**

It should crit 90% of the times considering the talent bonus plus character spell critical hit chance and other factors in mind.

**Database links:**

https://wowpedia.fandom.com/wiki/Last_Word_(paladin_talent)

**Comment by Renehadox** [comment]
EDIT:

Note that I am a ret paladin, not holy or protection.

Regards.

**Comment by Renehadox** [comment]
Confirmed, this is bugged.

Explaination:

Last Word 60% crit

Rule of Law ( Ret Talent ) that is plus 15% increased crit chance.

My character Spell Crit chance: 

![spellcrit](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7026f2f6-5c59-476e-ab54-38a6108d2bed)

60 + 15 + 13.36 = 88,36% increased critical effect chance.

Mark it is a critical as it is gamebreaking in PvP and in arenas, especially in high mmr arenas.

Regards.

**Comment by Renehadox** [comment]
Bumping this...

**Comment by Renehadox** [comment]
Hello???

Can you please fix this ??

Rets are unviable in PvP thanks to this...

**Comment by Renehadox** [comment]
@Sketish Can you mark this as critical since it is not checked up?
@Afgann

**Comment by Sketish** [comment]
> Hello???
> 
> Can you please fix this ??
> 
> Rets are unviable in PvP thanks to this...

Stop spamming pointless,
Also your confirmation proofed nothing, you just did some math w/o any clips or combat logs

**Comment by Renehadox** [comment]
> > Hello???
> > Can you please fix this ??
> > Rets are unviable in PvP thanks to this...
> 
> Stop spamming pointless, Also your confirmation proofed nothing, you just did some math w/o any clips or combat logs

Nobody is spamming pointless, im losing arena rating my dear friend cause of that bug.

I cannot test this on a dummy as i have to be dueling someone and to test at least 10 wogs when i am at 35% hp or below 35% hp.

If you want we can organize an in-game test so you can see, it rarely procs... you can test it by yourself.

Good luck.

**Comment by Sketish** [comment]
Just did some testing with 20% unbuffed crit and had crits quite often, and it's still crit chance so sometimes you may not have luck :)

**Comment by Renehadox** [comment]
> Just did some testing with 20% unbuffed crit and had crits quite often, and it's still crit chance so sometimes you may not have luck :)

Nobody said it doesn't crit.

When the healed target is at 35% hp or below 35% hp it should crit like 99,9% most of the times because of the talent, in my case i rarely crit myself when im low hp or my partners...
Hence why i made the report.

**Comment by Sketish** [comment]
How can you have 99% crit chance ?
It's increasing chance by 60% so show me your character with 35%+ crit

**Comment by Renehadox** [comment]
> How can you have 99% crit chance ? It's increasing chance by 60% so show me your character with 35%+ crit

Dude, are you joking or are you serious right now ?

I didn't mean literally 99,9% crit chance.

" It's increasing chance by 60% so show me your character with 35%+ crit "

Only that talent with 60% crit chance, plus Rule of Law talent which you obviously didn't read that is +15% crit chance.

Character spell crit chance 13,36 % that is 88,36 in total.

Oh and lets not forget the meta gem +3% increased critical effect. that is 91,36% total crit chance.

Which means it should rarelyyyy rarelyyyy not crit heal.

Thanks.

**Comment by Sketish** [comment]
Just tested with 40% crit chance and it always critted on target under 35%, closing

**Comment by Renehadox** [comment]
> Just tested with 40% crit chance and it always critted on target under 35%, closing

What?

40% crit chance of your character?

Excluding the talent right?

I get crits but rarely idk what are you on about..

**Comment by Sketish** [comment]
on ptr i can set my crit to 40% and with 2/2 in last word it always critted so no issue with that talent

**Comment by Renehadox** [comment]
Is this fixed?

**Comment by Sketish** [comment]
> on ptr i can set my crit to 40% and with 2/2 in last word it always critted so no issue with that talent

what to fix ??????????
