### ISSUE TITLE
Buggy Fear

### ISSUE THREAD

**Issue by Zeterak** [gamefreedomgit/Maelstrom#4860]
**Description:**
Fear in pvp is extremely buggy. Especially Priest fear.

1) you can't hit target from behind when it's feared
2)damage often does't break fear. Feels like you can hit feared target in full burst like for 5 seconds sometimes.
3)Feared characters often tend to go beyond texture's edge. 

**How to reproduce:**
For example in blades edge arena use fear on enemy on the bridge. Feared char often fall down.
Try fear in arena's those bugs happen literally almost every fear

**How it should work:**
Feared characters shouldn't fall off edges, fear should break under significant damage, feared characters should be vulnerable to damage from behind.

**Database links:**
I don't know what to write here.

**Comment by Renehadox** [comment]
Didn't they fix fear 3 times previously ??

Lol

**Comment by Zeterak** [comment]
idk I've been arround for month or so.

**Comment by Pornoodemon** [comment]
There is no information about the operation of the internal mechanics of these spells.
The “Fear”  currently worked great for warlocks. 
The warlock's fear effect has a damage threshold of 40% of the base hp.
After the threshold of fear withstands 20% of the base health, then fear has a chance to break when dealing any damage.
I think it works the same way for priests
The only problem is with falling.
And this happens mainly when trying to move while the effect "fear" while on the edge

**Comment by Pornoodemon** [comment]
> **How it should work:** Feared characters shouldn't fall off edges, fear should break under significant damage, feared characters should be vulnerable to damage from behind.
> 
Without any concrete evidence, the phrase “should” means nothing to developers.

**Comment by UltraNix** [comment]
@Zeterak @Pornoodemon Anything from here still valid?
About 2. - already being discussed in some many topics and this is not gonna change.

**Comment by Pornoodemon** [comment]
> @Zeterak @Pornoodemon Anything from here still valid? About 2. - already being discussed in some many topics and this is not gonna change.

"Fear" works perfectly.
In addition, for several months there has not been a single new topic related to fear.
