### ISSUE TITLE
 Texture's 

### ISSUE THREAD

**Issue by Zeterak** [gamefreedomgit/Maelstrom#4861]
**Description:**
Texture's in pvp doesn't work very well. Sometimes you can feral charge / charge /  AoE Fear through textures. It happened to me few times i feral charged character which was literally behind texture for example at lordaeron arena. Same happend to me when warrior charged me. My healer team mate got feared behind pillar many times. Feels obviously broken.

**How to reproduce:**
Try Charging and fearing near textures in arena's

**How it should work:**
Once character is out of los it shouldn't get feared or charged

**Database links:**
IDK

**Comment by Sketish** [comment]
We need clips or videos where it is happening

**Comment by Zeterak** [comment]
kk i'll try to shoot something in my arena sessions

**Comment by UltraNix** [comment]
No further info - closing.
