### ISSUE TITLE
Variable Pulse Lightning Capacitor

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4863]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sometimes stack was disappeared

**How to reproduce:**
attacking target/targets

**How it should work:**
stack should not disappeare

**Database links:**
https://cata-twinhead.twinstar.cz/?item=69110

https://github.com/gamefreedomgit/Maelstrom/assets/127995853/cb016a9f-9258-487a-8864-cd96f051fb2e
there was 2 stack, then it became 1

**Comment by mipanka** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/127995853/95d81419-1cab-472f-8eda-45e18f75faa1

+1 video, where 3 stack > 1 and 0 proc

**Comment by Kenniflopper** [comment]
can confirm this is bugged

**Comment by mipanka** [comment]
After the fix, the effects no longer disappear if you have target, but all lightning hit in target. But must hit the target from which it triggered trinket

**Comment by UltraNix** [comment]
Should be already fixed.
