### ISSUE TITLE
Eclipse with T12 is bugged

### ISSUE THREAD

**Issue by starfallminiedziala** [gamefreedomgit/Maelstrom#4867]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Hello!
T12 work that after i cast and hit my spell Wrath or Starfire i get some points to lunar/solar eclipse and after that hit set bonus give me additional points for T12. For starfire i get extra 5 points from wrath i get 3 points. So if i get 97 to Lunar eclips T12 bonus give me 3 points and i reach 100 points and still dont get Lunar Eclipse buff and i have to cast additional wrath or additional starsurge.

**Description:**
i cant into english

**How to reproduce:**

**How it should work:**
97+3=100 so i should enter lunar eclipse and
95+5=100 so i should enter solar eclipse

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
