### ISSUE TITLE
Magic Broom no fly zones

### ISSUE THREAD

**Issue by Aurorre** [gamefreedomgit/Maelstrom#4868]
Nothing big Just an FYI, 

When I jump on the event broom ([magic broom] (https://www.wowhead.com/item=37011/magic-broom)) in Silvermoon speed stays at 100% 
also happens in Eversong Woods and Ghostland.

Probably because it is a no fly zone.

Priority low

**Comment by Haramburgers** [comment]
Where‘s the problem?

**Comment by SexyPancake** [comment]
There is no flying possible in those zones, it's a waste of a github report.

**Comment by Aurorre** [comment]
It was that speed stayed at 100 and not the normal ground speed of 220
