### ISSUE TITLE
You Can't use Magic Broom in arena BUG, since today!

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4869]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Today when i played 2v2 it said that I can't use magic broom in arena, where it is usable, pls fix, ty.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
> Author: itsemmastone
> Message: The Magic Broom shouldn't be usable in Arena or Rated Battleground maps. 

Why did you guys disable this?

Where is the proof of this?

https://www.wowhead.com/item=37011/magic-broom#comments

> 
Can be used in BGs and arenas and anywhere where u can use ground mount.

Is this a joke or what is happening?

Someone cried to Gaga that he lost arena match vs guy who uses magic broom so he disabled it ?

**Comment by oldspices** [comment]
imagine crying about not being able to use broom in arena...
