### ISSUE TITLE
Bring back dancing rune weapon enchant (limitless tmog)

### ISSUE THREAD

**Issue by Anton251** [gamefreedomgit/Maelstrom#4870]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dancing rune weapon limitless transmog enchant was removed after the post:
https://github.com/gamefreedomgit/Maelstrom/issues/4522
I don't see why one persons complaint removed the enchant completely, we pay Whitemane+ to have access to those things
**How to reproduce:**
Enchant not existing anymore under limitless transmog

**How it should work:**
Please bring back the option to select dancing rune weapon enchant. If some players don't like it then they can just lower particle
density settings to view it less, or they can have a button to disable limitless tmog enchants of other players. Not fair to delete the enchant just because one player complained about it..

**Database links:**

**Comment by Sketish** [comment]
Its sugestion NOT A BUG REPORT
