### ISSUE TITLE
Undercity Blasted Lands Portal

### ISSUE THREAD

**Issue by Jingliu90** [gamefreedomgit/Maelstrom#4871]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**I wanted to use the Undercity Blasted lands Portal, but even after multiple clicks it didn't work

moving away from it and trying to click gives the too far away error. so should in theory work, but didn't

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Did you had 58+ lvl when clicked on portal ?

**Comment by UltraNix** [comment]
No further info - closing.
