### ISSUE TITLE
Brew of the Month Club - Spam messages

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4872]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after the <a href="https://github.com/gamefreedomgit/Maelstrom/issues/4621#issuecomment-1758992580">fix</a> i can buy the beers in orgrimmar (at least for me) but i'm still receiving <a href="https://imgur.com/a/kYJsMTM">mails without beer</a> every server crash, 

**How to reproduce:**

idk after buying the membership i started receiving this spam everyday.

**How it should work:**

in addition to buying the beers, i should only receive one mail per month with the beer attached, not this daily spam. idk if this happens to someone else.

**Database links:**

https://cata-twinhead.twinstar.cz/?achievement=1183

**Comment by Aurorre** [comment]
![WoWScrnShot_102623_102401](https://github.com/gamefreedomgit/Maelstrom/assets/146432018/3832230e-714e-46cd-8ceb-fb7cb7f6f8b5)
![WoWScrnShot_102623_102404](https://github.com/gamefreedomgit/Maelstrom/assets/146432018/12b2e742-b25c-4dbe-9a0f-77ffe68952ee)

Just wanted to make a post about it as well haha
