### ISSUE TITLE
Delegation items not completing as they should

### ISSUE THREAD

**Issue by Paschnfuzz** [gamefreedomgit/Maelstrom#4874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Delegation quest, not completing as it should for Ryo and Beth, so far.

**How to reproduce:** Engage ryolith as usual, collect the 3 fragments, create the item, drop under boss right before stomp and the item is not clickable.

Engage Beth'tilac.  Gather 3 items after drone dies, create item, take web upstairs and drop created item before smoldering devastation is about to go off.  Again, item not clickable.

**How it should work:**  Both quest items should be lootable when quest is done properly for each corresponding boss.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
