### ISSUE TITLE
[Death knight]Festering Strike and death rune

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4875]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when using already transformed runes (death runes), the ability https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948 they should remain after being re-transformed by death runes

**How to reproduce:**
use https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948

**How it should work:**
when re-transforming, the runes must be death runes

**Database links:**
https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948
https://wowwiki-archive.fandom.com/wiki/Reaping

**Comment by Sketish** [comment]
Used one festerInG strike and after recharging got two death runes so dont see any bgu there
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/5bbd4962-9f9a-4171-a37d-9d013968162e)

**Comment by mipanka** [comment]
To use more than one attack and will see, every strike should give death rune, every
