### ISSUE TITLE
The sanctuary must not fall

### ISSUE THREAD

**Issue by Nosferius** [gamefreedomgit/Maelstrom#4876]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest "The sanctuary must not fall" is not completing.

**How to reproduce:**
Work your way up to the quest "The sanctuary must not fall" and take it. Not only is the quest super duper slow with its dialogue it never completes the actual ritual to complete the quest

**How it should work:**
https://www.youtube.com/watch?v=nunfVvmdHEY

**Database links:**
https://www.wowhead.com/quest=29198/the-sanctuary-must-not-fall

**Comment by Sketish** [comment]
Need more details what is not working

**Comment by UltraNix** [comment]
Already fixed.
