### ISSUE TITLE
Droprate of Mote of Water Skettis

### ISSUE THREAD

**Issue by S1rL00t4l0t** [gamefreedomgit/Maelstrom#4877]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Droprate of Mote of Water in Skettis is too low in compare normal Server

**How to reproduce:**
Compare Droprates 

**How it should work:**

**Database links:**
https://www.wowhead.com/tbc/de/npc=21728/aufwiegler-von-skettis 35%

**Comment by PanJanuszek** [comment]
fixed 07.03.2024
