### ISSUE TITLE
[Druid] Aquatic Form + Sea Legs not applying properly

### ISSUE THREAD

**Issue by ChippyAndrah** [gamefreedomgit/Maelstrom#4879]
Sea Legs Swim speed makes my druid swim a 148% Swim Speed regardless of form (Gylph of Aquatic Form causes no difference to this speed either)

Edit: Aquatic form moves at 135% instead of 148% like other forms, making it slower in Vash'jr

Sea Legs and Aquatic Form are supposed to stack, but weirdly so, its been a 'bug' that's remained in the live versions of the game according to some forum posts, videos and my own experience the druid aquatic form in Vash'jr swims at roughly the same speed as the seahorse during Cataclysm

Video of a Druid in Cata swimming in Aquatic Form while in Vash'jr
https://www.youtube.com/watch?v=WndP6_ezv7o&t=52s&ab_channel=JohnMarshall

Comment on Wowhead
https://www.wowhead.com/quest=25929/sea-legs#comments:id=1213550

More claims of it being about the same speed as seahorse
https://dreamsofisorath.wordpress.com/2010/12/09/aquatic-form-and-vashjir/

Most Extensive Forum Thread I could find (However there's a lot of information being thrown around and its simply to show something is up with Aquatic Form)
https://www.mmo-champion.com/threads/808106-Aquatic-form-in-Vashj-ir

**Comment by UltraNix** [comment]
Fixed.
