### ISSUE TITLE
Retribution paladin Templar's verdict

### ISSUE THREAD

**Issue by twiftxd** [gamefreedomgit/Maelstrom#4881]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Retribution paladin Templar's verdict glyph not working, aswell as not scaling with strenght/attack power

**How to reproduce:**
press templar's verdict
https://youtu.be/UQZNgmp31qg (unlisted video from whitemane, without any gear and buffs/consumables for accurate comparision)
**How it should work:**
it should scale with both strenght, attack power aswell as the glyph, it doesn't scale properly with anything mentioned. 
I'm happy to announce that at least the "crusade" talent works as it should
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/cb77756e-e729-4b89-b158-3b2d96523da9)

**Database links:**
https://www.wowhead.com/spell=85256/templars-verdict
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/79428ad7-3824-4d04-869d-80a4d18a732f)

**Comment by Sketish** [comment]
Glyph is increasing dmg by 15 % so you must test with low lvl weapon so you can compare

**Comment by twiftxd** [comment]
> Glyph is increasing dmg by 15 % so you must test with low lvl weapon so you can compare

you are a real human I think

**Comment by Renehadox** [comment]
> Glyph is increasing dmg by 15 % so you must test with low lvl weapon so you can compare

Negative.

Not working.

Glyph doesn't work and Templar's verdict damage here is absurd low, its 351% weapon damage after all....

**Comment by oldspices** [comment]
random thought but i find this interesting because at low levels in pvp templars is one shotting ppl when it crits lol.

**Comment by bonfax4** [comment]
What is wrong about it ? Tested with both glyph and crusade talent and both increase the damage properly ?

Verdict does is 2.35x weapon dmg ([235%](https://wowpedia.fandom.com/wiki/Templar%27s_Verdict?oldid=2970147)) before glyph/talents.
![766ea0d4ca3759204dec8e7b039af945](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/17eb96f2-e05b-4d83-8d60-f4ecd194b571)

Glyph + Crusade talent are additive so multiplier becomes 2.35 X (1 + (0.15 + 0.30) =  3.4
![75fa0cbee615afa458edcb03831bbb1a](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/eac2709b-b463-4292-aff5-ec55b98470f0)

My current weapon swing is 4306 with 0 variance with https://cata-twinhead.twinstar.cz/?item=57692 so it's easy for testing against lvl 3 dummy which has very low armor.
![6af1fcc6b4dea420d826776e0cc05de4](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/7686d7e4-a059-4a0b-b3d6-a9e9a0fea236)


Hit with no talent/glyph = 10096.   Expected 4306 X 2.35 = 10119.1.
![c3e3b92433980cb18c089df807d9da05](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/ca9ffb7a-dc79-490f-b73c-f5ecd66c0fec)

Hit with glyph = 11605.   Expected 4306 X 2.35 X 1.15 = 11636
![4f3121e7c56c7d19d92f1a3e09e0ae35](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/4a17e789-62a2-4f84-802d-3469e0ff9f10)

Hit with glyph and 3/3 Crusade = 14640.  Expected 4306 X 2.35 X 1.45=  14672.
![1a132af21b6dd859a6a74865bdda0f77](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/27e20617-085a-4054-a7bd-8ce82e6204cd)

Small difference is due to the minimal amount of armor they have but the numbers check out ?

**Comment by twiftxd** [comment]
> What is wrong about it ? Tested with both glyph and crusade talent and both increase the damage properly ?
> 
> Verdict does 2.35x weapon dmg ([235%](https://wowpedia.fandom.com/wiki/Templar%27s_Verdict?oldid=2970147)) before glyph/talents with 3 holy power. ![766ea0d4ca3759204dec8e7b039af945](https://user-images.githubusercontent.com/16911730/278874649-17eb96f2-e05b-4d83-8d60-f4ecd194b571.png)
> 
> Glyph + Crusade talent are additive so multiplier becomes 2.35 X (1 + (0.15 + 0.30) = 3.4 ![75fa0cbee615afa458edcb03831bbb1a](https://user-images.githubusercontent.com/16911730/278874879-eac2709b-b463-4292-aff5-ec55b98470f0.png)
> 
> My current weapon swing is 4306 with 0 variance with https://cata-twinhead.twinstar.cz/?item=57692 so it's easy for testing against lvl 3 dummy which has very low armor. ![6af1fcc6b4dea420d826776e0cc05de4](https://user-images.githubusercontent.com/16911730/278875546-7686d7e4-a059-4a0b-b3d6-a9e9a0fea236.png)
> 
> Hit with no talent/glyph = 10096. Expected 4306 X 2.35 = 10119.1. ![c3e3b92433980cb18c089df807d9da05](https://user-images.githubusercontent.com/16911730/278875388-ca9ffb7a-dc79-490f-b73c-f5ecd66c0fec.png)
> 
> Hit with glyph = 11605. Expected 4306 X 2.35 X 1.15 = 11636 ![4f3121e7c56c7d19d92f1a3e09e0ae35](https://user-images.githubusercontent.com/16911730/278875491-4a17e789-62a2-4f84-802d-3469e0ff9f10.png)
> 
> Hit with glyph and 3/3 Crusade = 14640. Expected 4306 X 2.35 X 1.45= 14672. ![1a132af21b6dd859a6a74865bdda0f77](https://user-images.githubusercontent.com/16911730/278875709-27e20617-085a-4054-a7bd-8ce82e6204cd.png)
> 
> Small difference is due to the minimal amount of armor they have but the numbers check out ?

I have noticed that it works now and then, but as shown in the clip- it's not nearly close to all the time. on top of that, there's absolutely 0 str/ap scaling with it, which is a big part of the problem

**Comment by bonfax4** [comment]
Your clip os not conclusive enough because your weapon has a range of dmg. It will be 2.35 x weapon dmg and if you you rng a low hit what you showed can still happen. Why I did the test with a normalized one.

**Comment by bonfax4** [comment]
Formula you linked is not the cata formula, prob why you're misunderstanding this.

**Comment by twiftxd** [comment]
> Your clip is not conclusive enough because your weapon has a range of dmg. It will be 2.35 x weapon dmg and if you you rng a low hit what you showed can still happen. Why I did the test with a normalized one.
> 
> Your templar will always do in-between 2.35 x minWDmg - 2.35 x maxWDmg.
> 
> Your minimum with glyph can still be around your max without glyph

I fully accept this probability, however
without the glyph 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/4387c730-828c-49bb-907c-d966f7e92de5)
and here's with the glyph
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/f223d5f5-10f5-4451-b66f-c3a957a3462e)

is this a better sample size for you?

**Comment by bonfax4** [comment]
You'd need more hits than this still for any conclusive data... A video pref too because i cant replicate that at all with the weapon i'm testing. Cant tell if you're proccing stuff or not.

you can clearly see your minimum increased by some %.

**Comment by twiftxd** [comment]
> Formula you linked is not the cata formula, prob why you're misunderstanding this.
> 
> ![fecb47d0580e7ddda030c0208edfe7c9](https://user-images.githubusercontent.com/16911730/278879889-4511b9ef-1930-48dd-8697-e442ba3273dc.png)

both yes and no. this is the retardationized version of the explanation. it does scale with weapon damage, but it's supposed to take AP/strenght into account aswell, as it's increasing your base damage. that ius the core issue.

**Comment by bonfax4** [comment]
All the math i did was with char panel weapon range with takes into account atack power.... your images still show 15% increase in average, assuming you mislabeled and top is glyphed.

**Comment by twiftxd** [comment]
> You'd need more hits than this still for any conclusive data... A video pref too because i cant replicate that at all with the weapon i'm testing. Cant tell if you're proccing stuff or not.

this is done by the 2nd guy in the video, where he did a more extensive amount of testing, no procs available on any piece of gear/weapon.

**Comment by twiftxd** [comment]
> All the math i did was with char panel weapon range with takes into account atack power.... your images still show 15% increase in average, assuming you mislabeled and top is glyphed.

it is not labeled, and even IF IT WAS
are you saying 47176 x 1.15 is 49102? when in reality, it would be over 54k?

**Comment by bonfax4** [comment]
Just do a proper one with 100 hits at least, and clearly your friend did a 1 Holy power hit because 2k hit is only possible with 1 holy power...

**Comment by twiftxd** [comment]
> All the math i did was with char panel weapon range with takes into account atack power...

if this was the case, how come the 1k AP from landslide not only didn't make the weapon swing higher, but the templar's verdict did 500 less than the "clean" one?

**Comment by bonfax4** [comment]
! 1k / 14 x weapon speed  ) which i assume 3.6 ? It's only a 257 weapon dmg increase,

**Comment by bonfax4** [comment]
What is your weapon range ? screenshot your damage range, i'll do the math for you...

**Comment by twiftxd** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/de111bb3-fd4c-475e-83f0-b6b50ed4129a)
here is the 100% unbuffed, no procs, flask, aura, and here's the latest breakdown for rag

**Comment by Renehadox** [comment]
Who and why on whitemane is trying to nerf ret paladins so much?

For what reason?

I have played on 10 diff cata servers in my life ( private servers excluding retail cata ) Whitemane is the only server where rets are doing joke damage, tbh.

**Comment by bonfax4** [comment]
raid log doesn't help. I want the same conditions you had on the tests you did.

**Comment by twiftxd** [comment]
> Who and why on whitemane is trying to nerf ret paladins so much?
> 
> For what reason?
> 
> I have played on 10 diff cata servers in my life ( private servers excluding retail cata ) Whitemane is the only server where rets are doing joke damage, tbh.

literally no clue. someone who hasn't played ret on this server I'd assume, considering how dogshit they are compared to every other class, or any other server

**Comment by bonfax4** [comment]
So both of you guys are telling me the simcraft formula is also wrong ? I'm simply following the math and the numbers match....

**Comment by twiftxd** [comment]
> raid log doesn't help. I want the same conditions you had on the tests you did.

okay. I'd argue that the end boss on the patch is the ONLY place where it matters?

but go ahead, here's your exact same setting
![image](https://github.com/gamefreedomgit/Maelstrom/assets/146572823/664e3b49-1a85-4c43-a6e2-8ff93721c9e3)

**Comment by twiftxd** [comment]
> So both of you guys are telling me the simcraft formula is also wrong ? I'm simply following the math and the numbers match....

what you're not accounting for is that ret was extremely good in pvp in season 9, as they were on retail aswell- but they "balanced them", and it's now affecting pve and skewering the scaling/numbers as it is. and they need to look into it

I'm not saying your math is wrong, nor that simcraft is, I'm saying that ret is dogshit on whitemane, cause they have severely fucked up some things, and people who doesn't know better has no clue and thinks "rets are fine"

**Comment by bonfax4** [comment]
0.714 is the average reduction from the lvl 85 dummy. 

Unglyphed with talent : 3682 * 2.35 * 1.30 x 0.714 /   5270 * 2.35 * 1.30 x 0.714. **Range :  8031 - 11495**

Glyphed : 3682 * 2.35 * 1.45 x 0.714 /   5270 * 2.35 * 1.45 x 0.714. **Range : 8958 - 12822**

 landslide adds about  257 * 2.35 * 1.45 * 1.25 x 0.714 = **782 dmg to templars verdict** ?

Checking all these numbers you still think its not possible for all the scenarios you showed ? The gaps are like 3-4k and landslide only adds about 800 dmg.

No clue if ret is bugged but the bug is not with templar's verdict that's for sure,

**Comment by Renehadox** [comment]
> 0.714 is the average reduction from the lvl 85 dummy.
> 
> Unglyphed with talent : 3682 * 2.35 * 1.30 x 0.714 / 5270 * 2.35 * 1.30 x 0.714. **Range : 8031 - 11495**
> 
> Glyphed : 3682 * 2.35 * 1.45 x 0.714 / 5270 * 2.35 * 1.45 x 0.714. **Range : 8958 - 12822**
> 
> landslide adds about 257 * 2.35 * 1.45 * 1.25 x 0.714 = **782 dmg to templars verdict** ?
> 
> Checking all these numbers you still think its not possible for all the scenarios you showed ? The gaps are like 3-4k and landslide only adds about 800 dmg.
> 
> No clue if ret is bugged but the bug is not with templar's verdict that's for sure,

Who the F are you?

You are not a developer and you don't have to add salt to every soup around here.

Developers marked it is a bug i did test Templar with the glyph and without the damage is same...

**Comment by bonfax4** [comment]
You clearly didn't lmao.

**Comment by Renehadox** [comment]
> You clearly didn't lmao. And its not the 1st time you make false claims about stuff to get "fixed".

What false claims?

What are you talking about?

Check again who opened the bug report.

**Comment by bonfax4** [comment]
"Developers marked it is a bug i did test Templar with the glyph and without the damage is same..."

**Comment by Sketish** [comment]
Tested on dumym rn and dmg is increased by 15% when glyphed

**Comment by Renehadox** [comment]
@Sketish 

I just did a long ass BG, check this out:

![templars](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/9b727ae8-1b3e-4ba1-a70a-b1e11d9e2aef)

The glyph is maybe working or maybe not.

But... 60 templar hits, out of which 50 were normal hits 12833 average hit? 

For a BiS Ret Paladin PvP with Elite weapons ?

Is this a joke? :D

Note that this was done in a BG, where i also benefit from other player buffs, its not arena match, its a BG, templar's damage needs a boost here thats a fact.

**Comment by bonfax4** [comment]
Looking at average in bgs is meaningless, you're fighting different ppl with random amounts of armor, resilience, defensive cds, shields.... You literally have a 0 dmg templar as minimum which means it was prob fully absorbed. 

I see nothing wrong...  Simply looking at your weapon dmg your theoretical maximum crit outside of temporary buffs if the target had no defensives, 0 resil and 0 armor ( impossible ) is 9306 * 2.35 * 1.45 = 30600, that's 36.7k with wings. You're max crit was a 39K on that pic which prob came from procs. 

You can easily do proper testing in ptr with the weapon I linked above and the formulas, heck, you can even get somebody to equip resilience to fully test every possible scenario and then come back with your findings here.

**Comment by Sketish** [comment]
https://youtu.be/WnHQJELcNtI?t=74
15k normal hit
https://youtu.be/WnHQJELcNtI?t=107
34k crit
https://youtu.be/OKkVQqxQhPU?t=200
32k crit

so looks like normal dmg

**Comment by Renehadox** [comment]
So is this fixed or not ?
