### ISSUE TITLE
[Death knight]Festering Strike and death rune

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description:
when using already transformed runes (death runes), the ability https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948 they should remain after being re-transformed by death runes

How to reproduce:
use https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948

How it should work:
when re-transforming, the runes must be death runes

Database links:
https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948
https://wowwiki-archive.fandom.com/wiki/Reaping

p.s. I don’t get paid for creating reports, so I won’t create them a third time, let the bug remain if you close it

**Comment by mipanka** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/127995853/d65c9360-1596-4dc9-a17e-1640132e1f0b

**Comment by Sketish** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/bfefd1c6-1917-4535-ba7f-611f4eed2a6b)

Even on your video, its working correctly. So either you are not sure how it should work or not sure what are you reporting.
After using FS both runes recharged as death runes, you spent those on another one FS and they become original runes

**Comment by mipanka** [comment]
When I use death rune for festering strike, they should be death rune, now frost/blood

**Comment by UltraNix** [comment]
Fixed.
