### ISSUE TITLE
Temple Guardian Anhuur casting Burning Light while in Shield of Light

### ISSUE THREAD

**Issue by eulogy1337** [gamefreedomgit/Maelstrom#4885]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Temple Guardian Anhuur in the Halls of Origination (Heroic, haven't tested normal) is casting Burning Light while he is in his Shield of Light.

This makes it extremely difficult to complete the encounter, as the fire is likely to be placed while you are pushing the lever. It also seems to be casted more frequently than outside the Shield of Light phase.

**How to reproduce:**
Seems to happen every time in the phase where he is in his Shield of Light.

**How it should work:**
He should not be casting Burning Light in the Shield of Light phase.

**Database links:**
https://www.wowhead.com/npc=39425/temple-guardian-anhuur
https://www.wowhead.com/spell=75117/burning-light?dd=2
https://www.wowhead.com/spell=80747/shield-of-light

**Comment by UltraNix** [comment]
Already fixed.

**Comment by UltraNix** [comment]
Just tested on heroic - no Burning Light during Shield of Light.
