### ISSUE TITLE
[Battleground] Twin Peaks Player Positioning

### ISSUE THREAD

**Issue by MaelstromAbbey** [gamefreedomgit/Maelstrom#4886]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Players are loaded into the map with incorrect initial orientation. Currently, players are positioned facing 180 degrees opposite to the intended direction.

**How to reproduce:**
Join the Twin Peaks battleground from Alliance (untested on Horde). Initial orientation has the player facing the wall.

**How it should work:**
Players should be loaded into the map facing the appropriate direction, providing a correct initial orientation.

**Comment by UltraNix** [comment]
Fixed.
