### ISSUE TITLE
[Vashj'ir] A Breath of Fresh Air (Horde)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4887]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after taking this <a href="https://www.wowhead.com/quest=26006/a-breath-of-fresh-air">quest</a>, <a href="https://www.wowhead.com/npc=42410/legionnaire-nazgrim">legionnaire nazgrim</a> is not on the ship also the <a href="https://www.wowhead.com/item=57412/boom-boots">item provided</a> doesn't work. so i can't continue the storyline.

**How to reproduce:**

take the quest and try to complete it.

**How it should work:**

https://www.youtube.com/watch?v=RhzOMn7HsXw

**Database links:**

**Comment by PanJanuszek** [comment]
Fix after restart
