### ISSUE TITLE
[Quest] Retaking Windrunner Spire   Unavailable

### ISSUE THREAD

**Issue by AngryJeus** [gamefreedomgit/Maelstrom#4888]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest [Retaking Windrunner Spire](https://www.wowhead.com/tbc/quest=9173/retaking-windrunner-spire)

Unavailable 
After finishing and getting rewards from these quests
[Troll Juju](https://www.wowhead.com/tbc/quest=9199/troll-juju)
[Investigate Amani Catacombs](https://www.wowhead.com/tbc/quest=9193/investigate-the-amani-catacombs)

The quest was available, I saw exclamation mark above NPC 
[High Executor Mavren](https://www.wowhead.com/tbc/npc=16252/high-executor-mavren)

I turned those two, the exclamation mark disappeared 

**How to reproduce:**
Grab
[Troll Juju](https://www.wowhead.com/tbc/quest=9199/troll-juju)
[Investigate Amani Catacombs](https://www.wowhead.com/tbc/quest=9193/investigate-the-amani-catacombs)

Turn in reward

**How it should work:**
There's no reason why it should become unavailable, because those two quests are not in chain
I guess pick it up before turning them in for now?

**Comment by PanJanuszek** [comment]
fixed 17.04.2024, after server restart
