### ISSUE TITLE
Leaving rated bg 

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4890]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When u leave rated bg you get no loss on your record. So you can evade an L by leaving early. Maybe you don’t lose rating either?

**How to reproduce:**
Enter a rated bg and then leave it

**How it should work:**
Give you a loss on your record and lose rating 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
