### ISSUE TITLE
[Critical] Demon "Braxxus" is tameable, yet classified as a demon 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#4891]
(https://www.wowhead.com/npc=23353/braxxus#comments)

Demon Braxxus is tameable by beast mastery hunters - This NPC is tagged as a demon and should not be tameable (not a beast, cannot be classified as exotic)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/121137397/2600bece-4ca2-42fb-aeb5-cd53b33636b3)

**Comment by UltraNix** [comment]
Fixed.
