### ISSUE TITLE
problem at "Easy Money" quest (for Uldum)

### ISSUE THREAD

**Issue by smhunter2** [gamefreedomgit/Maelstrom#4893]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Hi, I'm smhunter who one of fan of whitemane(Mealstorm) server.

I wish to do the Uldum quest and I complete the quest "Warchief's Command: Uldum!" but I can not get the next quest "Easy Money".

Can you solve the problem? I need Uldum reputation.

please care the problem

thanks for your help

best regards

smhunter

https://www.wowhead.com/quest=27003/easy-money

![image](https://github.com/gamefreedomgit/Maelstrom/assets/149213356/945143ea-8f0c-45fe-81d1-dd62efd7a76d)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report, you didnt provided any detials

**Comment by smhunter2** [comment]
> Invalid report, you didnt provided any detials

Simply, I got the quest "Warchief's Command: Uldum!" at the board in Orgrimmar and complete the quest at Tanaris.
But, The NPC does not give the next quest "Easy Money" so all of Uldum quests are prevented.
