### ISSUE TITLE
when you mind control someone they keep getting meleed

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4895]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when you mind control someone they keep getting meleed

**How to reproduce:**
mc someone in arena who was getting attacked

**How it should work:**
they should become friendly and unattackable. 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
