### ISSUE TITLE
An Old, Crazed Friend

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4897]
After accepting the quest and entering Scarlet Monastery, you should be able to talk to Joseph the Crazed, but you can´t, therefore you can´t finish this quest and the rest of the quests in the instance.

https://cata-twinhead.twinstar.cz/?quest=26984

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/eaac165b-65e3-48c4-b8e9-9ee21a7089b1)
Closing as not a defect

**Comment by ootxc** [comment]
![2024-04-27](https://github.com/gamefreedomgit/Maelstrom/assets/145803287/7185a1b9-68ff-4ba6-981e-03025eb2b0dd)

Still not able to finish the quest.
