### ISSUE TITLE
Quest "Bad supplies" cannot be completed

### ISSUE THREAD

**Issue by Pipousek** [gamefreedomgit/Maelstrom#4898]
**Description:**
Quest "Bad Supplies" located in Hardwrench Hideaway from quest line from Bwemba cannot be finished. The ghost Zanzil disapears before he finished his speach and quest didn't mark as finished.
Even relog didn't help.

**How to reproduce:**
Start Bwemba quest line.
Try to finish Bad Supplies

**How it should work:**
Quest should be done after 3 monologue sentences from Zanzil and should be able to complete quest at ghost Bwemba.
How the quest should be done by video on [Youtube](https://www.youtube.com/watch?v=TR7eiS9m4R8&ab_channel=GitGudGuides)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/4f31098d-d123-429b-9ce9-e3f968f4117c)

That's not possible from code site. Killcredit is 1.5s before despawn. I have tried it a couple of times. Works as should
