### ISSUE TITLE
Marley's Final Flight

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4899]
After finishing Marley's Final Flight the keep should light on fire, which should open new quests. After finishing the quest the phase didn´t change though, which means the rest of the questchain is unavailable.

https://cata-twinhead.twinstar.cz/?quest=25120
https://www.youtube.com/watch?v=CbhkgRq1x2E&ab_channel=GameGuidesChannel

**Comment by PanJanuszek** [comment]
fixed 07.05.2024, restart required
