### ISSUE TITLE
Karazhan entrance grates

### ISSUE THREAD

**Issue by Ihazcookie** [gamefreedomgit/Maelstrom#4901]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The grates just outside both entrances to Karazhan return the error message "Invalid target" when interracted with.

**How to reproduce:**
Left/Right click the Karazhan Gatehouse Portcullis at the main entrance, or the Karazhan Side Entrance for the secondary entrance.

**How it should work:**
Both grates should just open.

**Database links:**

**Comment by UltraNix** [comment]
Should be fixed.
