### ISSUE TITLE
Trigger NPCS visibility @ The Stonecore

### ISSUE THREAD

**Issue by Yann-Brenno** [gamefreedomgit/Maelstrom#4903]
https://www.wowhead.com/zone=5088/the-stonecore

Theres 2 NPCS in The Stoncecore that should be invisible to players but they arent.

Going to this place:

[MAP](https://i.imgur.com/qIX4Iof.png)
[NPCS](https://i.imgur.com/qTf73Uv.jpeg)

to see em just nee to go to marked position on first image
they shouldn't be visible to players.

**Comment by Afgann** [comment]
fixed
