### ISSUE TITLE
No Cinder drop on 3 bosses Shannox and Major Domo Heroic and Ragnaros Normal

### ISSUE THREAD

**Issue by kickmeonfire** [gamefreedomgit/Maelstrom#4904]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**its my first time not getting quest item from the boss

**How to reproduce:**from 4 bosses like lord rhyolith/Alyzrazor/Baleroc and Beth i got them from cinders but this 3bosses
like Shannox and Majordomo Heroic and Ragnaros Normal its not giving me cinders I dont know why 

**How it should work:**

**Database links:** https://imgur.com/a/6Yv4d1I https://imgur.com/a/lojVXeX

**Comment by UltraNix** [comment]
@kickmeonfire Happened only once? Maybe someone already looted?
