### ISSUE TITLE
Anchorite Traska Quest bug

### ISSUE THREAD

**Issue by Ouresin** [gamefreedomgit/Maelstrom#4905]
- "In Defense of Quel'Danil" quest.
When you meet Traska and receive a quest, she goes into hiding, but does not cancel hiding even if you meet the quest conditions. Because of this, she cannot proceed any further.

 - "The Highvale Documents" quest also has no items in its designated location.

**Comment by PanJanuszek** [comment]
changed only respawn timer for object from 5min -> 5sec.
cannot reproduce rest
