### ISSUE TITLE
Quest - Fallen But Not Forgotten in Vashj'ir - Shimmering Expanse bug

### ISSUE THREAD

**Issue by Karayable** [gamefreedomgit/Maelstrom#4906]
**Description: Quest "Fallen But Not Forgotten" in Vashj'ir - Shimmering expanse is bugged. The quest objective is to "save" 6 Injured Assault Volenteer. The problem is that the NPCs don't reset after someone talks to them and they become unavailable to talk to.

**How to reproduce:**
Only tested the alliance side of the quest, reproduce the bug by doing the quest normally.

**How it should work:**
The NPC should run away and despawn after someone talks to them (video below) and after "x" ammount of time it should respawn.

**Database links:**
https://www.wowhead.com/quest=25753/fallen-but-not-forgotten
https://www.wowhead.com/npc=41281/injured-assault-volunteer
https://www.youtube.com/watch?v=NdfSVz9NayM

**Comment by PanJanuszek** [comment]
Fixed after restart
