### ISSUE TITLE
Taerar's Fall

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4908]
After finishing Ysondre's Call quest, Ysondre should offer Taerar's Fall quest, which didn´t happen.

https://www.wowhead.com/quest=25379/taerars-fall
https://cata-twinhead.twinstar.cz/?quest=25379

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/61c761c2-97c4-4136-b1a8-08f83b533ebc)
no reproduction as of 17.04.2024
