### ISSUE TITLE
Pitting madness against madness

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#4912]
To finish this quest, you are supposed to talk to Joseph the Insane in Scarlet monastery. The NPC is non-responsive, you can´t finish the quest.

(https://www.wowhead.com/quest=26985/pitting-madness-against-madness)

**Comment by PanJanuszek** [comment]
Works as expected

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/bca66204-824a-4399-a965-245283fd79c0)

**Comment by ootxc** [comment]
![2024-04-27 (1)](https://github.com/gamefreedomgit/Maelstrom/assets/145803287/e380f3c9-4618-4f7a-9be2-f08ab0608362)

Still not able to finish the quest.
