### ISSUE TITLE
Gurubashi arena stopped spawning chest

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4913]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
stv gurubashi arena stopped spawning chest its not at 2 nor 3 

**How to reproduce:**
go to stv gurubashi arena at the time its supposed to spawn

**How it should work:**
should spawn a chest

**Database links:**
https://cata-twinhead.twinstar.cz/?item=18706
this should be 100% drop rate btw it wasn't in the past

**Comment by UltraNix** [comment]
#3786
