### ISSUE TITLE
Quartermaster Winter's Grasp missing

### ISSUE THREAD

**Issue by S1rL00t4l0t** [gamefreedomgit/Maelstrom#4915]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quartermaster of Winter's Grasp is missing.
I made sure my faction was owing it when I was looking for him.
I need the shoulder enchants for my 80 PvP twink and maybe buying the mammoth mount.

**How to reproduce:**
Go to Winter's Grasp while your faction is ruling it and look at where the quartermaster is supposed to be.

**How it should work:**
The quartermaster should be there.

**Database links:**
https://www.wowhead.com/wotlk/de/npc=32296/steingardist-mutaha

**Comment by PanJanuszek** [comment]
fixed with POW
