### ISSUE TITLE
Hunter Pet Size Bug

### ISSUE THREAD

**Issue by KanseiDrift** [gamefreedomgit/Maelstrom#4916]
**Description:**
The Size of Hunter Pets is incredibly small. Mechanically this effects nothing, Hunter pets on a mechanical level work as they should.
But cosmetically their size makes them about the height of a player's ankles.
I believe this bug happens because when the pet is shrunk, it is applying the maximum shrink size that it might apply to a mob like a Devilsaur, but it is instead applied to pets universally instead of each pet having their own appropriate scale.

**How to reproduce:**
As far as I've seen, this bug is a constant for hunter pets.

**How it should work:**
Pets should reasonably scale instead of being shrunken down to the size of a mouse.

**Comment by UltraNix** [comment]
@KanseiDrift Do you have some screenshots of this?
My devilsaur looks like that:
![obraz_2023-10-31_220802002](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/c14da566-7c04-433e-882a-44bab45ab5ff)

**Comment by UltraNix** [comment]
No further info - closing.
