### ISSUE TITLE
The quest "That's the end of that Raptor" is bugged and it cannot be completed.

### ISSUE THREAD

**Issue by Aargonn** [gamefreedomgit/Maelstrom#4918]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
Screamslash, for the quest "That's the end of that Raptor" dosen't respawn where the quest helper shows. Please fix the quest.

**How to reproduce:**

**How it should work:**
The mob should be there where the quest helper indicate
![Bex](https://github.com/gamefreedomgit/Maelstrom/assets/149429895/b3cffa51-c1c7-4f7c-9935-0444f98eaea7)

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 17.04.2024, after server restart
