### ISSUE TITLE
Quest Vash'jir - Shimmering expanse - Alliance - The Culmination of Our Efforts

### ISSUE THREAD

**Issue by Karayable** [gamefreedomgit/Maelstrom#4921]
**Description: After Completing the quest "Chosen Burden" the quest chain doesn't continue. (Thus making the Vash'jir questchain achivement currently unattainable)
The quest giver "Lady Naz'jar doesn't offer the next quest in the chain, which would be "The Culmination of Our Efforts".

**How to reproduce: Only tested on alliance side, relog didn't solve the problem. Reproduce the bug by doing the quest chain.

**How it should work: Lady Naz'jar should offer the continuation of the quest chain.
***Sidenote, minor issue: The area should be under siege, but no battle is going on between the naga and the kvaldir, they are just chillin' (video below).

**Database links:
https://www.wowhead.com/quest=26191/the-culmination-of-our-efforts
https://www.wowhead.com/quest=25863/chosen-burden
https://www.wowhead.com/npc=42076/lady-nazjar
https://www.youtube.com/watch?v=zP87VylsZwo

**Comment by PanJanuszek** [comment]
I agree with battle event, will take a look on it
