### ISSUE TITLE
[MAGE][GLYPH] Molten Armor not giving you crit spell chance

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#4922]

**Comment by xmrshoot** [comment]
@Sketish  its not bug , molten armor gives only 3% and with gkyph(+2%) = total of 5%
![WoWScrnShot_103123_170735](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/6ac556b9-b417-40cc-9ea6-c8fb2edb5d0a)

![WoWScrnShot_103123_170732](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/7465017e-927b-4ae6-9663-c96493db10f4)
![WoWScrnShot_103123_170754](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/1b3bcbd4-99ef-4e15-8734-c566318b1b90)
https://cata-twinhead.twinstar.cz/?spell=30482

**Comment by Nenze** [comment]
can be closed

**Comment by xmrshoot** [comment]
close by yourself , u have button on bottom of page, near comment
