### ISSUE TITLE
Quest "Aiming High" - Alliance - Bugged and cannot be done (either step). Stopping all quest progress in Twilight Highlands.

### ISSUE THREAD

**Issue by Lolzor1234** [gamefreedomgit/Maelstrom#4923]
**Description:**
The "Aiming High" quest is supposed to shoot you out of the cannon next to Fargo Flintlocke once the zeppelin you're going to blow up is in position. So you may have to wait a bit for it to get there. However, Fargo Flintlocke and "Doc" Schweitzer next to him do not engage any of the quest dialogue. I also attempted to manually fly to the zeppelin and plant the explosives that way. This also does not work, but I cannot tell if it is because you aren't fired from the cannon first or if the location for where you plant the bomb is bugged as well.

This is a critical bug as it blocks all of Twilight Highlands as a questing zone and is right near the start.

**How to reproduce:**
Take the quest and the NPC "Fargo Flintlocke" will not engage any of his dialogue even after waiting for 15 minutes and taking the quest several times (waiting 10-15 minutes each time).

**How it should work:**
https://www.youtube.com/watch?v=VX9UvWM51UE

**Comment by Lolzor1234** [comment]
To note, there was another player on the same quest (some level 85 rogue) that ran into the same problem with the quest and gave up/left. So it's not just me.

**Comment by PanJanuszek** [comment]
It should be ok since yesterday restart. Open if not
