### ISSUE TITLE
Death and decay not giving combat

### ISSUE THREAD

**Issue by SatsumaDK** [gamefreedomgit/Maelstrom#4924]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
initial tick of death and decay is not giving combat and is detrimental to arena for dks

**How to reproduce:**
place death and decay on enemy, not get combat, get vanish full sapped, gg

**How it should work:**
u should get combat

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
