### ISSUE TITLE
[quest]The Fire Lord （Mount Hyjal）not started

### ISSUE THREAD

**Issue by wangcongdj1987** [gamefreedomgit/Maelstrom#4925]
quest link （wowhead）
https://www.wowhead.com/quest=25551/the-firelord

**Description:**
human lv83 deathknight.
combat with ragnaros is not going to start after
enter the portal.3 npcs remain standing there
and nothing interactive.

**Comment by UltraNix** [comment]
Just tested on live - everything works okay.
If there are 3 npcs near the portal - then you need just talk to Malfurion and start the event.
Or if the event is in progress - just wait a little bit.
