### ISSUE TITLE
Respawn Rate and Creature Placement

### ISSUE THREAD

**Issue by sirpaulins** [gamefreedomgit/Maelstrom#4927]
I've done a quick leveling throughout Eastern Kingdoms with a Horde character and noticed the respawn rate is very fast. If you're leveling alone it will most likely be a problematic experience. Also, I've seen several spots where creatures were misplaced - some were even spawning inside towns - and in a much larger number than expected.

I think these need some revising in order to provide a better blizzlike experience. Also, I would understand if this isn't top priority, as every zone would need to be revisited and thoroughly checked, but please consider doing it at some point, because it does hinder the gaming experience for some people.

**Comment by Sketish** [comment]
So what exactly are you reporting ? You didnt mention anything specific
