### ISSUE TITLE
disparution du balais magique

### ISSUE THREAD

**Issue by trydarion** [gamefreedomgit/Maelstrom#4928]
bonjour 
sur mon personage  lounya sur le serveur maelstrom, mon balai magique a disparut apres la fin de l'évenement , rapellant qu'il est acheter avec des bonbon farceurs .
merci

**Comment by Sketish** [comment]
Translate to english

**Comment by Aurorre** [comment]
C'est normal après la fin de l'événement, cela est également indiqué uniquement pendant l'événement sacré. A moins que tu n'aies eu le balai de 14 jours

Peux-tu fermer le sujet ?
