### ISSUE TITLE
Engineering item Electrostatic Condenser low proc rate

### ISSUE THREAD

**Issue by Strahx** [gamefreedomgit/Maelstrom#4929]
[Electrostatic Condenser](https://www.wowhead.com/item=67494/electrostatic-condenser)
https://cata-twinhead.twinstar.cz/?item=67494
https://www.wowhead.com/item=52328/volatile-air
https://www.wowhead.com/item=53038/obsidium-ore
https://www.wowhead.com/object=202736/obsidium-deposit

**Description:**
The proc rate for this item is way too low, back in the day it was 1-2%, but then they buffed it to be like 30%, so every few ores it would proc and youd get [Volatile Air] from it. For example i went around MH 2 times, got over 30 stacks of  [Obsidium Ore], and the item procced 5 times, giving me a total of 15 Volatile Air total. I mined around 120 nodes to get that much  [Obsidium Ore], so by standard math, the proc rate (for me atleast) is about 0.24%.

**How to reproduce:**
Make the item and start mining in any of Cata zones, the numbers should show themselves.

**How it should work:**
As stated above, the item should proc more often, i am not sure if 30% is accurate, but thats my estimate from way back when it was current, even without the item, the ore deposits should have like 2% change to give Volatile Air alongside the Ore even without the Electrostatic Condenser, so with the item, the % for V.Air showing with the ore should only be higher.

**Comment by UltraNix** [comment]
It's 6% chance for veins (with 10% chance exception for rich deposits) and herbs.
it's 10% chance for skinning.
