### ISSUE TITLE
entangling roots is not putting myself or them into combat (arena) 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4930]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i got instant proc and used it to root someone, neither of us got put into combat. 

Same thing happened when i blinded someone on my rogue alt too. 

**How to reproduce:**

**How it should work:**
should make combat. 

**Database links:**

**Comment by UltraNix** [comment]
Yep - roots should not put in combat (that's what I see in blizzard files). You can post some proofs from retail.

**Comment by UltraNix** [comment]
No further info - closing.
