### ISSUE TITLE
pet abilities are not going off onto people in iceblock/bubble

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4931]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
pets are not using abilities' if the person is in iceblock etc but they all go off the nanosecond its over- they should not be this automated. 

**How to reproduce:**

**How it should work:**
i think it should go off , and be "immune" or it should not be "smart" to go off the exact moment the block ends. 

**Database links:**

**Comment by Hermeleen** [comment]
I think it is maybe done like this, to prevent breaking cc. Just a guess..

**Comment by Sketish** [comment]
Provide any proof for proper reaction of pets

**Comment by bonfax4** [comment]
https://youtu.be/rTIRN-uygQY?t=71 Look at pet claw ability when paladin used bubble. It only resumed casting it after shield ended.

**Comment by Sketish** [comment]
So doesnt like like bug, pet was just autoattackig and use claw instantly after bubble went off

**Comment by bonfax4** [comment]
> So doesnt like like bug, pet was just autoattackig and use claw instantly after bubble went off

Kinda. This video makes it look even weirder. Looks like pet will bite the a nearby eligible target instead (mage elemental) whiel still auto atacking the iceblock, but when the mage is iceblocking without the pet nearby the bite doesnt go off. https://www.youtube.com/watch?v=LBTHVZP3CJA
