### ISSUE TITLE
Can no longer log into a character after starting the quest to travel to Mount Hyjal 

### ISSUE THREAD

**Issue by TomoRanger** [gamefreedomgit/Maelstrom#4932]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** I started the quest to go to Mount Hyjal and upon mounting the dragon in Moonglade to get to Hyjal, I got disconnected. Now when I try to log into this toon, I just get automatically disconnected every time. I can log into other toons with no issue.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Contact with any GM ingame - they will help you.
