### ISSUE TITLE
[Quest] An old Friend - Zul'Gurub

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4933]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after completing the <a href="https://www.wowhead.com/item=69251/lashtail-hatchling#comments">quest line</a> (horde) to obtain the lashtail hatchling, i can see it inside zg <a href="https://imgur.com/a/Gk2nO8K">after killing</a> bloodlord mandokir (2nd boss) but the <a href="https://www.wowhead.com/quest=29208/an-old-friend">quest</a> to obtain the pet is not given.

**How to reproduce:**

complete the quest line in the same order (quests are given in disarray but works), then go zg and kill bloodlord mandokir (2nd boss)

**How it should work:**

after killing bloodlord mandokir, the lashtail hatchling should give the quest <a href="https://www.wowhead.com/quest=29208/an-old-friend">An old Friend</a> to obtain the pet.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
