### ISSUE TITLE
[Mage] Water elemental freeze + invisibility issue

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#4934]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pet freeze is not removing its invisibility. Mages can freely fish for stealthed players without giving away their positions.

**How to reproduce:**
Cast invis > cast pet freeze > notice pet is still invisible

**How it should work:**
Pet Freeze should remove it's invisibilty.

Proof : 
https://youtu.be/rZwVAAqacwI?t=9
https://youtu.be/YyZkuZL_BDM?t=31

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=33395
https://cata-twinhead.twinstar.cz/?spell=66
https://cata-twinhead.twinstar.cz/?spell=96243 pet invis buff

**Comment by Afgann** [comment]
fixed
