### ISSUE TITLE
Well Read Achievement Horde

### ISSUE THREAD

**Issue by Aurorre** [gamefreedomgit/Maelstrom#4935]
For the Well Read Achievement [https://www.wowhead.com/achievement=1244/well-read](https://www.wowhead.com/achievement=1244/well-read) I found the following missing Horde Side

The Betrayer Ascendant [https://www.wowhead.com/object=175759/the-betrayer-ascendant](https://www.wowhead.com/object=175759/the-betrayer-ascendant) :  Doesn't show up at the horde location in Silvermoon ( cord 68;64) at the crate in Velaani's Arcane goods store. (Can be found in Darnassus)

The Alliance of Lordaeron [https://www.wowhead.com/object=175746/the-alliance-of-lordaeron](https://www.wowhead.com/object=175746/the-alliance-of-lordaeron) : Doesn't show up at Horde location in Silvermoon (cord 66;73) on the floor above the inn (can be found in Tarrenmill).

Scarlet Monestary (library part)
The World Tree and the Emerald Dream (Library at Athenaeum)  [https://www.wowhead.com/object=175730/the-world-tree-and-the-emerald-dream](https://www.wowhead.com/object=175730/the-world-tree-and-the-emerald-dream) (can be found in Stormwind with an occasional sudden death)
Aftermath of the Second War (Library east of Gallery of Treasures) [https://www.wowhead.com/object=21581/aftermath-of-the-second-war](https://www.wowhead.com/object=21581/aftermath-of-the-second-war)  (can be found in Nethergarde Keep but lots of lvl 65 guards)
Aegwynn and the Dragon Hunt (Library at Gallery of Treasures)  [https://www.wowhead.com/object=175738/aegwynn-and-the-dragon-hunt](https://www.wowhead.com/object=175738/aegwynn-and-the-dragon-hunt)  (Can be found in Brill)
The War of the Ancients (Library at Athenaeum)  [https://www.wowhead.com/object=175727/the-war-of-the-ancients](https://www.wowhead.com/object=175727/the-war-of-the-ancients) (can be found in Darnassus)

Greetings Aurore

Priority low because you can get it as horde.

**Comment by UltraNix** [comment]
Fixed.
