### ISSUE TITLE
Warrior

### ISSUE THREAD

**Issue by Qjubjo** [gamefreedomgit/Maelstrom#4936]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometimes, not always, mortal strike does not refresh slaughter buff EVEN THO the mortal strike DID hit, happened to me and my friend as well many times,
Also recklessness does not add 50%crit to your meele stat during its duration, and I ve noticed that it probably doesnt even work sometimes, today I didnt crit for 10 spells in row, which should be impossbile with 65%ˇcrit or? 

**How to reproduce:**

**How it should work:**
Mortal strike should always reset slaughter if it deals dmg to the target, 
Recklessness is supposed to add 50% crit to your meele stat during duration of recklessness
**Database links:**

**Comment by Sketish** [comment]
Provide any details when mortal is not reseting slaughter.

**Comment by UltraNix** [comment]
`Also recklessness does not add 50%crit to your meele stat during its duration, and I ve noticed that it probably doesnt even work sometimes, today I didnt crit for 10 spells in row, which should be impossbile with 65%ˇcrit or?`
Nope - it's not shown in your chat stats.
