### ISSUE TITLE
Inquisition again not procing free ret abilities

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4937]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It was fixed once in #4157 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Renehadox** [comment]
Confirmed.

**Comment by Renehadox** [comment]
I am still trying to figure it out who and why is trying to fck up ret paladins on this server that much...

**Comment by Sketish** [comment]
There were no changes to this ability, so can more people confirm ?

**Comment by Renehadox** [comment]
I just said confirmed 7 hours ago?

Did a test now, 30 inquisitions used, 0 Divine Purpose procs.

So someone is obviously fking Rets here, from what i see..

**Comment by UltraNix** [comment]
Fixed.
