### ISSUE TITLE
Glyph of Freezing Trap not working

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#4938]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When your Freezing Trap breaks, the victim's movement speed is reduced by 70% for 4 seconds.

**How to reproduce:**
Trap someone and either break it or let it run out, no debuff is applied.

**How it should work:**
it should slow the target when the freezing trap ends

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
