### ISSUE TITLE
Combustion 

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#4941]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Combustion does not calculate damage from DOT correctly.
For example, I placed a “living bomb” on the target, After a while I had one last tick left  which should cause conditionally 2.5k damage.
At the moment of use, “combustion” should add this tick into 1 new effect that will create an additional 2.5damage within “conditional 12 seconds”
Instead, combustion always sums the maximum number of ticks .
  always results in maximum possible damage.
The video shows the use of "Combustion" and the last tick of a living bomb which should deal approximately 2.6k damage.

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/b04a8340-8ce7-46af-b053-98a16c8a26a4

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
I’m not entirely sure if this is correct, but level 81-83 twinks kill level 85 players with 130k HP + in 1  use Combustion

**Comment by mipanka** [comment]
Pls find and to read formula combustion

**Comment by Pornoodemon** [comment]
> Пожалуйста, найдите и прочтите формулу горения.



> Pls find and to read formula combustion

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/71cc2066-60a3-41c5-beb7-f3ae88869d74)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/3fa30756-5079-4d92-8a68-2457e7e3f61a)
There is conflicting information about this on mmo-champion
This is probably not a bug.

**Comment by mipanka** [comment]
I know

**Comment by Pornoodemon** [comment]
> Пожалуйста, найдите и прочтите формулу горения.

> Я знаю

Я закрыл тему но  с камбустом явно что-то не то .  Каакие-то невероятные ваншоты по 300 к дамага за камбуст

**Comment by Pornoodemon** [comment]
> I know
https://forum.wowcircle.com/showthread.php?t=630759
Это же твой пост?

**Comment by mipanka** [comment]
Все верно, в расчет комбуста идет базовое кол-во тиков дот(пиры, игнайта, лб). Поэтому как ты заметил выше комбуст с последнего тика, равен комбусту с первого.
В той теме на вовсеркл, баг был в том что комбуст брал общий урон от дот(с учетом хасты в данный момент), а не базовую формулу.
Проверить легко, кидаешь лб+комбуст мгновенно (заметь мгновенный урон комбуста т не должен критануть). После повторяешь это с большим количеством хасты, если есть разница = есть баг.
