### ISSUE TITLE
Quest "Warning:Some Assemby Required" does not work

### ISSUE THREAD

**Issue by S1rL00t4l0t** [gamefreedomgit/Maelstrom#4943]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Kill of Vrykul with the Abomination do not count towards the quest goal of killing 20

**How to reproduce:**
Start and do the quest 

**How it should work:**
The kills ffrom the abomination should count towards the killss needed for the quest

**Database links:**
https://www.wowhead.com/wotlk/quest=11310/warning-some-assembly-required

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
