### ISSUE TITLE
Hex doesn't break when under Sacred Shield

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4944]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When a Ret paladin is under sacred shield and he is hexed by a Shaman and he takes damage, hex doesn't break, it stays in full duration.

It broke after sacred shield went down, happened to me in a BG.

Pls fix this high critical bug.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by mipanka** [comment]
mb it work on all dmg absorb?

**Comment by Renehadox** [comment]
> mb it work on all dmg absorb?

idk that

**Comment by deeyouwhy16** [comment]
Hex isn't suppose to break on direct damage

**Comment by UltraNix** [comment]
Fixed.
