### ISSUE TITLE
[Hunter] Camouflage doesn't reduce the detection range of enemy creatures.

### ISSUE THREAD

**Issue by Georgiimo** [gamefreedomgit/Maelstrom#4946]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Camouflage doesn't reduce the detection range of enemy creatures even though it should.

**How to reproduce:**

Slowly walk up to mobs with, and without camouflage and notice that there is no difference in detection range.

**How it should work:**

Camouflage should reduce the detection range of enemies.

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=51755

**Comment by Georgiimo** [comment]
I did some more testing and it seems like camouflage actually INCREASES the range at which mobs detect you. Whenever you lose the stealth buff from camouflage you seem to have a larger detection radious than when you are just standing still without camouflage.

Here is a video showing some testing: https://streamable.com/dbyby3

**Comment by UltraNix** [comment]
Fixed.
