### ISSUE TITLE
Priest's Psychic scream doesn't break on damage.

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4950]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Today in a BG a priest feared me and a warrior attacked me after, the fear didn't break at all from his damage and he had around 125k hp, the fear stayed full duration aka 8 seconds.

WTB Fix.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report, 0 details
