### ISSUE TITLE
[Guild Achievement] United Nations

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4951]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

i think only reputation counts per player, not per guild member as it should be, u know. that'd explain <a href="https://imgur.com/a/Np8J0YD">this</a>.

**How to reproduce:**

just look in ur guild achiv tab if u get credit when any other guild member gets some exalted reputation

**How it should work:**

if any guild member gets exalted with any reputation required for this achiv, all guild members should receive credit for it.

**Database links:**

https://cata-twinhead.twinstar.cz/?achievement=5892

**Comment by UltraNix** [comment]
Fixed.
