### ISSUE TITLE
Dropping the Hammer Bug

### ISSUE THREAD

**Issue by Schmoopietty** [gamefreedomgit/Maelstrom#4952]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Servias Windterror is immune when riding any gryphon

**How to reproduce:**
Ride a Gryphon and do damage to the mob

**How it should work:**
Mob should take damage

**Database links:**

**Comment by Sketish** [comment]
Invalid report, follow template
