### ISSUE TITLE
"Blown Away" Orgrimmar quest bugged

### ISSUE THREAD

**Issue by Sylkan101** [gamefreedomgit/Maelstrom#4956]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
The quest is missing objects to loot such as the balloons in Orgrimmar

**How to reproduce:** 
Begin the quest

**How it should work:** 
We should find balloons around Orgrimmar and loot them

**Database links:**
https://www.wowhead.com/quest=29412/blown-away

**Comment by Hermeleen** [comment]
I thought the same on Alliance quest, but when you see people running around with balloons, it makes you wonder. I figured, there are balloons, but very few. On alliance i found most of them in mage quarter. And on horde, as i just now tried, found most of them in valley of spirits. Also, if i am not totally wrong, they respawn, so you can technically get 5 from 1 spot.

**Comment by PanJanuszek** [comment]
fixed 05.03.2024
