### ISSUE TITLE
my gold is gone

### ISSUE THREAD

**Issue by stander91** [gamefreedomgit/Maelstrom#4961]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
hi, i login to the game today (around 2pm) and i found out my gold was gone! it supposed i have around 7k gold but when i realized i was left 148g only. i don't know what happened. i really hope you can help me..

**How to reproduce:**
i wish i could get back my lost gold

**How it should work:**

**Database links:**
maelstrom
character name : Majisk
character level : 85

**Comment by Aurorre** [comment]
If you make an ingame ticket maybe a GM can look into the history sometimes.

**Comment by Sketish** [comment]
Report this via discord, its nto bug report
