### ISSUE TITLE
Deepholm, story quest line stuck at Gunship Down quest pickup

### ISSUE THREAD

**Issue by jjYBdx4IL** [gamefreedomgit/Maelstrom#4962]
Maruut at the central quest hub in Deepholm does not offer Gunship Down quest. Maelstrom server, character: Gruust.

It is supposed to be step 33 in the quest line https://www.wowhead.com/storyline/deepholm-war-gunships-543

Used QuestCompletionist addon to check all locations in Deepholm for quests able to pick up, but none of the unfinished ones are available.

**Comment by SexyPancake** [comment]
This is the actual storyline during Cataclysm patch :

**Comment by jjYBdx4IL** [comment]
According to that page, the next quest should be "The Very Earth Beneath Our Feet" which . I have completed "The Middle Fragment". Interestingly, QuestCompletionist addon doesn't prefix that quest with either a question mark or done/green hook symbol.

**Comment by jjYBdx4IL** [comment]
"Deepholm: Realm of Earth" isn't completed. I remember there was an issue.

**Comment by jjYBdx4IL** [comment]
Icecrown quest "Preparations for War" doesn't work either. When I speak to that guy as requested, nothing happens.

**Comment by jjYBdx4IL** [comment]
Just tried it from Vashir via "The War Has Many Fronts". Handed in the quest at shrine in SW, then nothing. Probably because I already was at the Maelstrom.

**Comment by jjYBdx4IL** [comment]
Okay, I think I solved it now with an in-game ticket. GM sent me to Maelstrom to finish that particular quest. Now Maruut sends me out on the missing stuff. The real bug is that you can abandon "Deepholm: Realm of Earth" after leaving Maelstrom and not be able to pick it up again AND Maruut apparently depending on it being completed. Maybe just remove that dependency?
