### ISSUE TITLE
Demons Deck quest

### ISSUE THREAD

**Issue by Samo26** [gamefreedomgit/Maelstrom#4964]
I cant pick up quest from quest item "Demon's Deck". It says "You don't meet requirements for that quest" but it is Darkmoon Faire right now and I don't have to skill up inscription to do that quest.

**Comment by frostwave942** [comment]
i have the same issue, after creating the deck (demons/rogues) with my inscriber i can use it and get the quest but if i try to trade or mail to other char i got that error msg. i think i'll hav to wait for 27/12 when darkmoon island is open to raise this repu cuz almost all daily quest are bugged (except arch).

**Comment by UltraNix** [comment]
Inscription is needed to start this quest.
