### ISSUE TITLE
mage pets below lvl 85 have had their HP nerfed and they wont respawn at GY

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4967]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
so about 2 months ago this was never an issue, but somewhere along the line the HP massively changed to be low-  now any class damage ability will 1 shot the pet. 1 frost bolt 1 backstab etc etc etc- 

at level 80 it is less than half the hp of caster- it never used to be this way and if this was changed due to arena or something at least make the pets spawn at GY? 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Provide any details and proof of retail what hp was around 80-84

**Comment by oldspices** [comment]
> Provide any details and proof of retail what hp was around 80-84

hmmm idk where to find that but shouldnt the pet respawn at gy? would be a good fix imo

**Comment by bonfax4** [comment]
@Sketish 

https://youtu.be/g6Nf7Qh_X4k?t=6m47s 
Frost ele respawning at gy after death

**Comment by UltraNix** [comment]
Just tested with Frost Mage - pet is respawned on graveyard revival.

**Comment by oldspices** [comment]
> Just tested with Frost Mage - pet is respawned on graveyard revival.

they respawn if they never died , if they died then they do not respawn. 

if hunter pets die they respawn.
either make hunters have to resummon pets after rezzing or make mages not have to.

**Comment by UltraNix** [comment]
@oldspices If the elemental is killed before you, it just despawn - you have no longer pet beside you.
On video you see that player is dead with pet next to him - in that case everything works okay.
In case of pet died before player - need more proofs from retail.

**Comment by UltraNix** [comment]
Fixed.
