### ISSUE TITLE
weapon oils tooltip says 1 hour duration but only last 30 min

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4968]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
tooltip says 1 hour but only last 30 min for multiple types of weapon oils

**How to reproduce:**
apply oil to weapons' 

**How it should work:**
should last 1 hour 

**Database links:**
https://cata-twinhead.twinstar.cz/?item=20750

https://cata-twinhead.twinstar.cz/?item=22522

**Comment by Afgann** [comment]
fixed
