### ISSUE TITLE
Combat timer to reset/enemy pathing when flying

### ISSUE THREAD

**Issue by deeyouwhy16** [gamefreedomgit/Maelstrom#4970]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Combat timer seems to be bugged, takes far too long to reset combat and pathing of enemies should still hold aggro when flying as far as they do

**How to reproduce:**
for the combat distance on non enemy players, simply add a virtual anchor to cause them to retreat after certain distance is gained.

**How it should work:**
Combat timer should be reset in 6 seconds, in arena it takes seemingly way to long to reset

Enemies path/aggro while flying should almost instantly drop when flying up. They do not, they stay on your target for a far greater distance than they should which is 

**Database links:**

**Comment by Sketish** [comment]
Any proof for that ?

**Comment by Hermeleen** [comment]
I remember that, i wanted to write report for it too back then, then i somehow forgot.. But now testing it, it seems like it's ok. I can't remember where, but i remember that "somewhere" i had to go to extreme elevations to drop aggro. Might have been certain mob type, wrong pathing at that spot, or perhaps server communication issues. But it happened more than once. If you can tell, where does it happen, that would help.

**Comment by deeyouwhy16** [comment]
> Any proof for that ?

What do you mean proof? Just go to literally any mob that pulls aggro on a flying mount and compare to any other server and compare the aggro range.

There was an issue with this over a decade ago on other servers as well, to implement a quick fix, they added anchor points to the aggro range


Same thing for the out of combat timer, just que a quick 2v2 match run away from the action, and watch how long it takes for combat to drop(and yes I'm aware of any HoTs, DoT,s or pets involved may affect this timer)

**Comment by Sketish** [comment]
Compare to any other server - invalid

**Comment by deeyouwhy16** [comment]
> Compare to any other server - invalid

They worth comparing when they are all sharing the same pull distance and anchor points.

Also the fact that this was a notable issue back in 2011-2012 and required fixing. Therefore depending on how copy pasted the server is, could be that we may be experiencing the same issue here.

but to say comparing to any other server is invalid is just willfully ignorant.
