### ISSUE TITLE
Dtr on fulmination´s shaman issue

### ISSUE THREAD

**Issue by Firebenderz** [gamefreedomgit/Maelstrom#4972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Dtr is not working on dmg of fulmination, hes doing a very little dmg when he hits twice, One hit are taking the charges of lightning shield and the other fulmination are taking 0 charges.  https://imgur.com/a/KKdjjYQ

**How to reproduce:** Spaming lightning bolt until gets 9 charges of lightning shield so use earth shock to proc fulmination, when dtr procs he will do 2hits but hes dont doing dmg or very low

**How it should work:** When fulmination is proc with dtr, should be same dmg when is normal or crit hit a fulmination consumes lightning orb charges but dmg might be equal to the first fulmination : based on http://web.archive.org/web/20120208100749/http://elitistjerks.com/f79/t110309-elemental_cataclysm_discussion_patch_4_3_a/p11/
 [16:39:04.265] Entropei Fulmination Training Dummy 1 (O: 24774)
[16:39:04.265] Entropei Earth Shock Training Dummy 1 (O: 5937)
[16:39:05.046] Entropei Fulmination Training Dummy 1 (O: 24774)

[16:43:51.562] Entropei Fulmination Training Dummy 1 (O: 22522)
[16:43:51.562] Entropei Earth Shock Training Dummy 1 (O: 5404)
[16:43:51.656] Entropei Earth Shock Training Dummy 1 (O: 5385)

**Database links:** http://cata-shoot.tauri.hu/?spell=88766 
https://www.tauri-veins.com/elemental-shaman-wow-pve-dps-rotation-cooldowns-abilities

**Comment by Afgann** [comment]
fixed
