### ISSUE TITLE
Marca Dañaluz no se activan sus tics

### ISSUE THREAD

**Issue by luxurywood** [gamefreedomgit/Maelstrom#4973]
https://www.wowhead.com/es/item=63839/marca-da%C3%B1aluz

**Description:** No se activa como deberia funcionar normalmente, deberian corroborar si su probabilidad para que salte el debuf sea la correcta

saludos cordiales

**Comment by Sketish** [comment]
Translate to english

**Comment by UltraNix** [comment]
Fixed.
