### ISSUE TITLE
Counterspell and Windshear Goes Through DK Anti Magic Shell

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4974]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
I was casting hungering cold as frost dk, and mage counterspelled me. I got kicked on frost, but the "improved counterspell", silence, was immuned. So i tried shaman windshear, pressed antimagic shell and started casting hungering cold, and he as well, kicked me through.
I say "possible" because maybe, those abilities are considered physical? Obviously i could get kicked by feral,rogue,warrior through shell, but not for example shadowpriest silence, because it doesn't have kick mechanics.
**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Magic intterupt as silence from priest wont work during ams, same for mage improved- you are kicked by silence is no apllies due to ams

**Comment by Hermeleen** [comment]
> Magic intterupt as silence from priest wont work during ams, same for mage improved- you are kicked by silence is no apllies due to ams

i am sorry if i dont understand you correctly, so, if i cast as frost dk and have ams, and mage will cast counterspell and it kicks me, that is working as intended? same as shaman windshear during ams? the kick is working as it should?

**Comment by deeyouwhy16** [comment]
> > Magic intterupt as silence from priest wont work during ams, same for mage improved- you are kicked by silence is no apllies due to ams
> 
> i am sorry if i dont understand you correctly, so, if i cast as frost dk and have ams, and mage will cast counterspell and it kicks me, that is working as intended? same as shaman windshear during ams? the kick is working as it should? What i mean is, that would imply that mage kick and shaman windshear is "physical" but if it would be physical, you would not be able kick palading hand of protection (bop), but you can with counterspell and windshear. From my point of view, kick should either kick through bop, and get stopped by ams, Or, be "immune" on kick into bop, but then go through ams.

CS, Windshear, Warlock pet kick, Spriest Silence, druid aoe silence are all considered magical interrupts and SHOULD not be able to interrupt a cast through AMS. However a physical interrupt such as , warrior, rogue, and feral can interrupt through AMS.

If magic interrupts are going through AMS then it is bugged.

**Comment by Hermeleen** [comment]
yes but as i said priest silence doesn't have "kick" to it, its just silence. that is obvious that it will not go through ams. But counterspell is only kick, unless you put talent points so that it has also silence effect. 99% it is bug.

**Comment by Hermeleen** [comment]
So i was quickly back on my dk on apollo, and it seems like the sham can windshear through anti magic shell there as well, but i think, it's just a bug there too.

**Comment by UltraNix** [comment]
No - it's not a bug.
AMS description says: `[...]and preventing application of harmful magical effects[..]`
The word `Application` is the key. Kick effects often are not auras - they are just spell effects thus can go through by AMS. AMS protect from applying negative/harmfull auras.
