### ISSUE TITLE
Mission of enchanting in the Darkmoon Faire "Putting Trash to Good Use“ doesn't work

### ISSUE THREAD

**Issue by chenran1219** [gamefreedomgit/Maelstrom#4975]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mission of enchanting in the Darkmoon Faire does work.

**How to reproduce:**
Get the mission "Putting Trash to Good Use“ and then can't find the stuff Discarded Weapons on the ground.

**How it should work:**
Get the mission "Putting Trash to Good Use“ and find the quest stuff Discarded Weapons around the darkmoon faire area. use Disenchant skill .At the end, get the target stuff for the mission。

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=29510

**Comment by Revly** [comment]
This quest of Professions Darkmoon Faire quest only works on 4.3.4 on Darkmoon Faire Island.
As we are currently on 4.2 it does not work because Darkmoon Faire is the LK version

Check

**Comment by chenran1219** [comment]
thx. got it!
