### ISSUE TITLE
2FA codes doesnt work in game(can't login into game), but it works well on website.

### ISSUE THREAD

**Issue by Rakragul** [gamefreedomgit/Maelstrom#4976]
**Description:**
As in tittle, my 2FA codes dont work in game. But there is no problem on website.
Every time my IP changes(basically once very 24h) i need to deactivate 2FA because no matter how many times i try "in game", codes don't work.

**How to reproduce:**
I guess you need to try to login into my account and use codes from my google authenticator

**How it should work:**
After entering code it just should accept it.

**Database links:**
N/A

**Comment by frostwave942** [comment]
i think 2fa should be done via email, i think it's less problematic and more ppl might decide to use it.

**Comment by Sketish** [comment]
Please contact gaga directly via discord
