### ISSUE TITLE
heirlooms to char in same acc -  error -  "internal mail database error"

### ISSUE THREAD

**Issue by bonusaa** [gamefreedomgit/Maelstrom#4977]
when i try to send the heirlooms to my alt char in the same acc  ,, items dont send just go back to my bag with error "internal mail database error"
 
 is there any fix or something ? also i tried to send a normal uncommon boe and it sent it so problem must be in heirlooms

**Comment by Aurorre** [comment]
If there is an enchant on it you need to use void-storage

**Comment by bonusaa** [comment]
> If there is an enchant on it you need to use void-storage

there is not

**Comment by Sketish** [comment]
Please provide screenshot of item that you are trying to send

**Comment by GM-Nightmare** [comment]
Adding your character to friend list should fix the problem

**Comment by UltraNix** [comment]
No further info - closing.
