### ISSUE TITLE
Spammable Howling Blast

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4978]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
When paladin presses bubble, and you howling blast him, it doesnt cost runes. the problem is, that it is aoe, so you can spam it on the paladin and aoe everyone down without any rune cost. Maybe same for mage ice block, will test.

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment]
@Sketish 

Immunes should not refund runes it seems according to these retail videos below.

https://youtu.be/lRuS3g3leYo?t=3m4s
Slow down to 0.25. Howling blast ( Death rune ) into divine shield > full rune CD.

https://youtu.be/lRuS3g3leYo?t=4m10s
Slow down to 0.25 . 
Necrotic strike ( Unholy rune ) right as the mage used Ice Block into immune and full unholy rune CD.

https://youtu.be/Y4M7rX-EE8k?t=1m2s 
Obliterate? orr whatever he did into  that block and full frost/unh cd.



https://youtu.be/XHv4Mwg0qmo?t=1m6s Unrelated but howling blast Into deter @ 1:10 did refund a death rune. I'm assuming miss/dodge/parry/deflects should refund. Immunes should not.

**Comment by Sketish** [comment]
Thank you @bonfax4 !

**Comment by Renehadox** [comment]
> @Sketish
> 
> Immunes should not refund runes of any ability, not just HB it seems according to these retail videos below.
> 
> https://youtu.be/lRuS3g3leYo?t=3m4s Slow down to 0.25. Howling blast ( Death rune ) into divine shield > full rune CD.
> 
> https://youtu.be/lRuS3g3leYo?t=4m10s Slow down to 0.25 . Necrotic strike ( Unholy rune ) right as the mage used Ice Block into immune and full unholy rune CD.
> 
> https://youtu.be/Y4M7rX-EE8k?t=1m2s Obliterate? orr whatever he did into that block and full frost/unh cd.
> 
> https://youtu.be/XHv4Mwg0qmo?t=1m6s Unrelated but howling blast Into deter @ 1:10 did refund a death rune. I'm assuming miss/dodge/parry/deflects should refund. Immunes should not.

DKS are getting nerf finally, its the reason their damage is absurd on this server.

**Comment by UltraNix** [comment]
Fixed.
