### ISSUE TITLE
Can't complete quest "Stopping the Spread" in Uldum

### ISSUE THREAD

**Issue by austinbrowne** [gamefreedomgit/Maelstrom#4980]
**Description:**
The quest cannot be completed as the eggs give an error saying that you can't open them when you attempt to destroy them.

**How to reproduce:**
Start the quest and interact with any egg

**How it should work:**
Eggs should be destroyed when interacting with them

https://www.wowhead.com/quest=27836/stopping-the-spread

**Comment by Sketish** [comment]
what is happening when you mouse over them ?

**Comment by austinbrowne** [comment]
I do see the standard sort of cog wheel turn gold and it appears I should be able to interact.

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/804a54e0-5454-4b8f-a014-2e836f643feb)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/720d909d-1f19-428d-963a-11f561a8edfd)

cannot reproduce
