### ISSUE TITLE
Weird chat limit bug.

### ISSUE THREAD

**Issue by yoitspug** [gamefreedomgit/Maelstrom#4982]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cannot type more than a couple lines of text. Not saying anything harmful, not mentioning other servers, not reaching the in-game chat limit.

**How to reproduce:**
Log onto a player account, try to type out a long message. When you press enter it will act like it is sending the message but it will simply disappear and will not show. Continue removing letters from the message until it eventually sends what you're trying to type.

**How it should work:**
There is a built in character limit for how long of a message you can send in a chat message at a time. When you reach that limit whatever you will typing will simply stop being entered into the chat box and you can send your uncompleted message like normal. What is instead happening, is the message is not reaching this built in limit, and is instead just simply not posting your completed message until it is lower than this new, imaginary character limit.

**Database links:**
Theres no database links for this but I have a screenshot showing how much I can type at one time in a message and it is no where near the real character limit for the chat box in game. 

https://gyazo.com/fe90f215cd44bd781950035151ad2147

**Comment by oldspices** [comment]
ive been noticing this too, super annoying

**Comment by PanJanuszek** [comment]
Retail servers also have limit for chat box, not an issue

![image](https://github.com/user-attachments/assets/41b12076-b50a-4d1a-9f75-77b79c5333f2)
![image](https://github.com/user-attachments/assets/c5f85342-7434-40f2-b088-8bb30452dfb8)
