### ISSUE TITLE
14 slot bag is not available at most vendors it should be at 

### ISSUE THREAD

**Issue by oldspices** [gamefreedomgit/Maelstrom#4983]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
this bag is not at all the vendors in all the cities i checked. 

i did find it in some twiilight highlands vendor once.

**How to reproduce:**

**How it should work:**
it should be available, it would help out new players and old. 

**Database links:**
https://cata-twinhead.twinstar.cz/?item=60335#sold-by:0+3+1

**Comment by UltraNix** [comment]
Fixed.
