### ISSUE TITLE
Heroic leap

### ISSUE THREAD

**Issue by pashobg** [gamefreedomgit/Maelstrom#4985]
Hi guys, please, make heroic leap able to jump on a higher surfaces i know that at the start of the expansion, has been like that, but later on they change it, it was never changed in any private server, please make it work, it's a huge game changer for warriors, it makes our gameplay way smoother and cooler, come on guys, since i came back yesterday i see u are passionate about the realm and pvp, u can make it work, please, make my best ever class better, thanks in advance!!

**Comment by Sketish** [comment]
So what bug are you exactly reporting ? I dont see any details of locations
