### ISSUE TITLE
[DK Minor Bug] Picking up BG buffs ( Leaf, Berserk, Speed ) Turns Off Path Of Frost 

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4987]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Imagine you start Arathi Basin and want to go straight Blacksmith over water, you press path of frost and on the way pick up the buff in stables building. It turns off Path of frost.  I wouldn't maybe even mention it, but it is still 1 rune, which is 8 seconds without technically two runes because you have to reapply.

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
