### ISSUE TITLE
Quest Bug Duskwing, Oh how I hate thee

### ISSUE THREAD

**Issue by Feliphito** [gamefreedomgit/Maelstrom#4988]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
bug quest duskwing, oh how I hate thee:  can't kill him, followed around, 

**How to reproduce:**
go to the spot use the flare to call him, leave the flare before he lands then use the flare again then run, now you cant kill him, and follow you around the map 

**How it should work:**
use the flare he lands press your abilities then kill him

**Database links:**

**Comment by UltraNix** [comment]
#2245
