### ISSUE TITLE
Dungeon Queue bug

### ISSUE THREAD

**Issue by etan264** [gamefreedomgit/Maelstrom#4989]
**Description:** When you are in queue and it pops, and someone doesn't click accept (let's use a dps as an example) it should return you to the top of the queue. In game if a dps afks the queue and I as a dps accepted, instead of returning me to the top of the queue with the tank and healer, I always lose one. So I'm in a 3 dps/1 healer queue instead of a 1 tank/1 heal/2 dps queue.

**How to reproduce:**Go queue, and when people inevitably afk through the queue pop, watch the tank that rdf found disappear even though they clicked accept.

**How it should work:** If a tank a healer and 2 dps accept a queue, and 1 dps afks it should basically instantly pop afterwards with another dps. Because the same 4 people should be at the top of the queue.

**Database links:**Go play retail or any other server with an rdf.

**Comment by UltraNix** [comment]
It does work the way you described. All players that did accept the queue, but the proposal failed - all of them are pushed to the front of the queue and then calculates the best compatibles again - it does not guarantee that you will be put in the same group/proposal as previously.
