### ISSUE TITLE
/target totems

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4990]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Apparently you can target totems with /target spellcast macro. 

**How to reproduce:**
duel a shaman and use /cast [target=Healing Stream Totem] Ice Lance

**How it should work:**
It shouldn’t be allowed for those macros to work

**Database links:**

**Comment by Sketish** [comment]
Any proof that macro shouldn't work ?

**Comment by SimonBpvp** [comment]
Only what I could find on Google search
![79FCAC61-19B5-46F6-A5EA-66EBE1E7D023](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/d3bd3df0-602b-4aa2-b24a-86007e0ca57c)

**Comment by Sketish** [comment]
5 years  ago wasnt cata on retail, it's from legion/bfa I guess

**Comment by bonfax4** [comment]
@Sketish 

It was def in wotlk when they broke it. Ppl abused those macros in tbc with their pets. 

https://wowpedia.fandom.com/wiki/Patch_3.2.0

> Macros and scripts will no longer be able to target totems by name.

**Comment by Sketish** [comment]
Thanks for helping with finding confirmation

**Comment by UltraNix** [comment]
This macro does not work for me in duel.

**Comment by UltraNix** [comment]
@bonfax4 Still valid?
