### ISSUE TITLE
[Guild Achievement] United Nations - Reward

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#4992]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after getting this <a href="https://imgur.com/a/78VHs08">achiv</a>, i can't buy the <a href="https://www.wowhead.com/item=63138/dark-phoenix-hatchling">pet</a> i think only the alliance got credit for that (this guild is originally alliance). so the achiv i can see in my tab is the <a href="https://cata-twinhead.twinstar.cz/?achievement=5812">alliance version,</a> that's why i can't buy the pet being horde, cross-faction things after all.

**How to reproduce:**

use any horde char, then join some alliance guild, get the achiv and try to buy the pet.

**How it should work:**

regardless of faction both should be able to buy the pet or any other guild reward.

**Database links:**

**Comment by frostwave942** [comment]
![WoWScrnShot_112123_144855](https://github.com/gamefreedomgit/Maelstrom/assets/146029129/08e99eca-2df6-4571-b106-f8d68b0f1910)

ye, but i cant buy the pet yet

**Comment by frostwave942** [comment]
![WoWScrnShot_112123_144855](https://github.com/gamefreedomgit/Maelstrom/assets/146029129/efd90940-e339-42da-8b17-2fa9abf50d20)

ye, but i cant buy the pet yet.

**Comment by UltraNix** [comment]
Fixed.
