### ISSUE TITLE
Missing Judgment and Hammer of Wrath On Ret ( Hit Capped )

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4993]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Well first i noticed when i pressed hammer of justice on rogue and then casted hammer of wrath and it missed him. Then i noticed missing a judgement on feral. Both of them had one thing in common, they were both night elves, so i wonder, the night elf passive for missing an attack is suppose to be only ranged and melee no?
Because there is discrepancy, as we discussed, censure being applied through cloak of shadows via judgment, because it is considered "physical" attack, i could understand that it can miss on night elf as considered "attack", but hammer of wrath is spell, because it is "immune" on cloak. So hammer shouldn't miss at all, assuming hit cap...? ( 5.01% )
If someone can confirm? I will close if i am off here.
**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
DR stuns ???

**Comment by Hermeleen** [comment]
*hammer of wrath, that's the Ret execute.

**Comment by Sketish** [comment]
Night elves racial is affecting both melee and range attacks. cloak is providing immunity for 1 sec and later it reduce chance to be hit by spells so it is working against hammer of wrath
