### ISSUE TITLE
Area 52 PvP Vendor bug

### ISSUE THREAD

**Issue by Radii24** [gamefreedomgit/Maelstrom#4998]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Vendor in Area 52 in Outland named Grex Brainboiler couldn't be opened. I'm personally Alliance and the Vendor is for Alliance only, I can open the Horde one tho

**How to reproduce:**

**How it should work:** Should be able to click and see what Vendor is selling

**Database links:**

**Comment by UltraNix** [comment]
#4998

**Comment by PanJanuszek** [comment]
Cannot reproduced. All vendors are only for those who have Feats of Strength classic  achievements.

The only exception is TBC vendor.
