### ISSUE TITLE
Frenzied Regeneration unable to crit

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#4999]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Frenzied Regeneration ticks can't crit.

**How to reproduce:**
-

**How it should work:**
Frenzied Regeneration ticks should be able to crit, and from my understanding scales off of spell crit.

**Database links:**
https://github.com/TrinityCore/TrinityCore/issues/24602
https://www.wowhead.com/spell=22842/frenzied-regeneration#comments ctrl-f crit
https://sunniersartofwar.com/blog/2011/07/11/frenzied-regeneration-glyph-analysis/

**Comment by Afgann** [comment]
fixed
