### ISSUE TITLE
Fire Elemental Totem not benefiting from Totemic Wrath

### ISSUE THREAD

**Issue by Hepticlol** [gamefreedomgit/Maelstrom#5000]
**Description:**

Regarding "Greater Fire Elemental" for Elemental Shamans specifically

The fire ele itself is not benefiting off of Fire Totems Totemic Wrath, the 10% Spellpower buff.
If I am the only one providing 10% SP buff, my totem is providing it, the swap to fire ele "flickers" the buff for one frame causing it to NOT benefit from the 10% spellpower buff
The "flicker" I mentioned happens between swapping totems. Example is having Flametongue/Searing totem out, then using Fire Ele, you lose the buff before Fire Ele totem becomes active.
Since fire ele snapshots its rough to lose out on that 10% bonus if you are the only one providing the bonus.

I tested the damage with multiple instances:
_**No** totem beforehand:_ Ele hitting for 12,7k
_**MY** Flametongue beforehand:_ Ele hitting for 12,7k
_Another shaman in the group providing 10% **WHILE** I have totem out beforehand:_ Ele hitting for 13,3k

How it should work:

I do not know how it is "supposed" to work, which is why I make this issue. It would make sense that totem benefits off itself but that implies the caster gets the 10% SP bonus before Fire Ele becomes active. So it seems to be a certain order of where/when things happen.

It would also be nice to get some data on how Fire Ele snapshots, like how much it scales off getting 1int/1sp, does it snapshot crit, etc.

Hope this all makes sense.

**Comment by Afgann** [comment]
fixed
