### ISSUE TITLE
Potential issue with a vendor in Area 52

### ISSUE THREAD

**Issue by yoitspug** [gamefreedomgit/Maelstrom#5001]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As an alliance rogue, level 84, I cannot access the "Classic Cloth & Leather" armor vendor in Area 52. I can access the Horde one just fine but not the Alliance one. On my Paladin I can access the Mail & Plate vendor just fine.

**How to reproduce:**
Go to Area 52 on an alliance rogue or feral druid, try to gain access to the Cloth & Leather vendor, it will simply do nothing. No chat box, no pop up, just does nothing when clicked on.

**How it should work:**
The vendor box should open up and you should be able to purchase replica leather and cloth gear used for transmog.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
