### ISSUE TITLE
MOON GUARD ACHIEVEMENT - END TIME

### ISSUE THREAD

**Issue by XYNKA** [gamefreedomgit/Maelstrom#5002]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I have tried to solo the achievement as Protection Warrior, after surviving her Shadow Gauntlet phase and pulled the boss, the achievement didn't pop up.

**How to reproduce:**

Engage the Echo of Tyrande in End Time on Heroic Difficulty after surviving her Shadow Gauntlet without allowing the party's healer to take any damage.

**How it should work:**

Engage the Echo of Tyrande in End Time on Heroic Difficulty after surviving her Shadow Gauntlet without allowing the party's healer to take any damage.

**Database links:**

https://www.wowhead.com/achievement=5995/moon-guard

**Comment by UltraNix** [comment]
Fixed.
