### ISSUE TITLE
The purification of Quel'Delar 

### ISSUE THREAD

**Issue by Drezzdd** [gamefreedomgit/Maelstrom#5004]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest The purification of Quel'Delar in the quest line from Battered hilt item is unable to be completed. After using quest item to purify in sunwell, nothing happens and the cutscene is not started.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=FILdWp5AaaQ&ab_channel=PathaleonEU

**Database links:**
https://wowpedia.fandom.com/wiki/The_Purification_of_Quel%27Delar_(Horde)

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
