### ISSUE TITLE
Bad buff script at trash from EMERALD DRAGONSHRINE

### ISSUE THREAD

**Issue by johnatgh** [gamefreedomgit/Maelstrom#5005]
**Description:**
The trash npcs before emerald boss have a 90% damage reduction buff that gets removed when they step into the light and after the light fades (**too fast** compared to a video from retail) that damage reduction buff is re-applied and this way the stack of these trash npcs gets too big that tank and heal can no longer handle and dps can't kill them fast enough because of the damage reduction.
Sure, for the high geared pigs, err I mean players, it's easier to clear those before the light fades.
P.S.: The moonlance spell from echo of tyrande = lmao xD

**How to reproduce:**
Play the game.

**How it should work:**
The buff shouldn't be re-applied after it gets removed.

**Database links:**
https://www.youtube.com/watch?v=NUCPjpvGCI4
Check @ 15:30

**Comment by Sketish** [comment]
Light dahes when you are killing mobs around it.We will increase mob count

What about Moonlance ?

**Comment by johnatgh** [comment]
Sometimes moonlance takes a turn when it's splitting in 3 and faces probably the random player which was the destination at the time of cast instead of going straight after the split.

**Comment by Sketish** [comment]
Ok thanks, we will fix that

**Comment by UltraNix** [comment]
Fixed.
