### ISSUE TITLE
Goldshire Flightmaster is on the Smithy roof

### ISSUE THREAD

**Issue by Winningone** [gamefreedomgit/Maelstrom#5007]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On Maelstrom server Bartlett the Brave is currently on the Smithy roof in Goldshire and can't be accessed for quest turn ins or flight.

**Comment by UltraNix** [comment]
Contact with any GM - they will help with that.
