### ISSUE TITLE
Quest - Well of Eternity - Documenting the Timeways

### ISSUE THREAD

**Issue by Karayable** [gamefreedomgit/Maelstrom#5009]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: The quest in title has three steps to complete, but it won't add credit to the second goal which is "Royal Handmaiden archived"

**How to reproduce: Just do the quest normally and it should reproduce

**How it should work: Since I did not find anything written fact online about the quest I am just guessing, that before the second boss there are two handmaidens and it should give credit to the quest step after you kill them. (this guess is based on the picture found on wowhead links screenshot section - link below)

**Database links: 
https://www.wowhead.com/quest=30104/documenting-the-timeways

**Comment by Revly** [comment]
Something similar has happened to me with the Alters and I think what happens is that you have to kill the Handmaidens very close for them to give you credit for it, they could increase the credit rank, and then you shouldn't have problems

**Comment by Karayable** [comment]
I tried it first with a tank character as well so i was pretty close 😄 didn't get credit with three characters so its pretty consistent

**Comment by UltraNix** [comment]
Fixed.
