### ISSUE TITLE
trading with i85 char

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5012]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
you can't trade a healthstone or food to a insta 85 char. this makes it quite hard to play 2s with them as a lock or mage
solution: maybe put food table or soulwell into the arena match to cover this?

**Comment by oldspices** [comment]
imo make it so soul well / table only requires 1 clicker . would be a nice QOL change since ppl are never clicking when they should anyways

**Comment by Afgann** [comment]
fixed
