### ISSUE TITLE
Pets "auto casting" spells 

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5013]
Pets "auto casting" spells  is only working in Combat.

it should always work in and out of combat.. it's when you right click on a spell for example [Dash] 

![dash](https://github.com/gamefreedomgit/Maelstrom/assets/129106504/cf7369bd-04ce-4e2a-a649-6da752bbcf0f)

**Comment by Sketish** [comment]
Autocasting wont work outside combat because that how pet AI is working, you can bind Dash or press it with button then pet will use dash outside of combat
