### ISSUE TITLE
Dragonwrath Tarecogsa's Rest Proc/Uptime on Elemental Shaman

### ISSUE THREAD

**Issue by Klosterbro** [gamefreedomgit/Maelstrom#5015]
Please Read All of This.
[//]: # (https://www.engadget.com/2011-12-10-mastery-vs-haste-for-elemental-shaman.html?_fsig=N6VOb_LawzmA6bgNm3X5Vg--%7EA) "The last part of mastery's return to glory is that more and more players are gaining access to Dragonwrath, Tarecgosa's Rest. Dragonwrath's (http://www.wowhead.com/item=71086/dragonwrath-tarecgosas-rest) proc works much like elemental's mastery to begin with, with the benefit of proccing off both an Elemental Overload and the spell that procced it. This means that every mastery proc you have when you're using the legendary gives you another chance to activate the legendary's own potent proc. Haste, on the other hand, just allows you to squeeze in more full-strength spells per minute, but the rate of proccing Dragonwrath drops down a small amount."

[//]: # https://www.mmo-champion.com/threads/929168-Dragonwrath-Wrath-of-Tarecgosa-Legendary-Staff-Which-class-is-it-best-for-and-why

[//]: # https://cata-twinhead.twinstar.cz/?spell=101056

**Description:**
For some reason DTR on Elemental Shaman only duplicate out of DoT from Flame Shock, there is not a single duplicated spell such as Lava Burst, Lightning Bolt, Chain Lightning. I'm pretty sure it should be able to duplicate non-DoT spell such as that also should be able to duplicate from talent called Overload. Cause i've seen some mages can proc from spell such as arcane blast and missiles. 

Below currently on baleroc DTR Uptime on Ele Shaman is only 0.5% and it only proc out of Flame Shock tick.

![DTR PROC ON ELE BAD](https://github.com/gamefreedomgit/Maelstrom/assets/127820418/f6e358b1-9254-49a1-b1b2-a669be126c20)

**How to reproduce:**
It should be able to duplicate Lava Burst, Lightning Bolt, Chain Lightning (all harmful spell).

**How it should work:**
It should be able to duplicate Lava Burst, Lightning Bolt, Chain Lightning (single target spell).

**Database links:**
https://wowpedia.fandom.com/wiki/Dragonwrath,_Tarecgosa%27s_Rest
https://cata-twinhead.twinstar.cz/?spell=101056

**Comment by bonfax4** [comment]
Not how it works. Wrath of tarecgosa proc is only for duplicated dot ticks. Normal spells just get duplicated as if they are normal spells.

**Comment by Sketish** [comment]
But do you know details are adding tarecgosa procs into spell dmg ? So all extra dmg done by lighting bolt is added to that spell in details

**Comment by Klosterbro** [comment]
hmm, all right it just for me i feel like it doesnt make sense for the proc to adding extra damage to the spell and counted as that said spell instead of counted as Wrath of Tarecgosa tho.
