### ISSUE TITLE
Typo in NPC Jorgensen Idle chat

### ISSUE THREAD

**Issue by Winningone** [gamefreedomgit/Maelstrom#5016]
**Description:**
During the quest "Return of Bravo Company" the player is escorted by four NPC's they have rescued. The one named Jorgensen has a typo in one of his idle statements:

"Can't believe we're putting the old team back together. All thanks to you, $n."

Instead of the player character name being used at the end of the sentence it is left as "$n".

**Database links:**
Quest: https://www.wowhead.com/quest=26563/return-of-the-bravo-company
NPC: https://www.wowhead.com/npc=43272/jorgensen

**Comment by PanJanuszek** [comment]
fixed 17.04.2024, after server restart
