### ISSUE TITLE
[Guild Perk] Bountiful Bags (disenchant items)

### ISSUE THREAD

**Issue by Nightwiings** [gamefreedomgit/Maelstrom#5019]
(https://wow.gamepedia.com/Bountiful_Bags)
(https://wowwiki.fandom.com/wiki/Bountiful_Bags)
(https://web.archive.org/web/20120703083947/http://www.wowhead.com/spell=83966)
Old wowhead archive since this perk was removed by Blizzard a few years back.
Comments take a while to load but they're there.

**What is happening:**

This perk doesn't seem to do anything for me or other guild members in disenchant items. I could be mistaken about this.

**What should happen:**
From the wowhead archive, not sure if the info is correct but it looks ok to me:

    -This affects all levels of mining, skinning, herbalism, and enchanting.
    -The 'proc' essentially functions as hitting a node/disenchanting an item a second time.
    -Does NOT proc from the group disenchant option. If you want a chance at the proc, greed the item and disenchant it yourself.
    -While it will count you as 'hitting' a node twice, it will not give you extra items like volatiles or gems.
    -The extra 'proc' will not give extra experience if you are below 85.

    Proc Chances
    1 loot: 85.0000%
    2 loots: 12.7500%**
    3 loots: 1.9125%
    4 loots: ~0.2869%
    5 loots: ~0.0430%
    6 loots: ~0.0065%
    7 loots: ~0.0010%
    8 loots: ~0.0001%
    9 loots: ~0.0000%

    This continues following the infinite series S(n) = 0.850.15^n(n+1). As n approaches infinity, S(n) approaches ~1.17647. For spreadsheets and formulas using Bountiful Bags, it is more appropriate to use the approximation 1.17647 instead of 1.15.
    **When I say "1 loot" or "2 loots" I mean the number of nodes it rolls for you - for example getting 3 loots for a pyrite node would be like getting three nodes worth of pyrite ore.

**Comment by Sketish** [comment]
Perk in increasing number of herbs/ores you gathered or disenchant items you get. What exactly are you reporting ?

**Comment by Nightwiings** [comment]
@Sketish disenchant, never get the extra mats for the guild bonus.

**Comment by oldspices** [comment]
they recently nerfed this it seems. i used to get lots of procs from disenchanting stuff. now never.

**Comment by Nightwiings** [comment]
@oldspices no they just do this :

Author: Ultranix
Message: DB/Loot: Epic weapons and armor pieces above 300 ilvl should give 2 Maelstrom Crystals at max while disenchanting.

gamefreedomgit/Maelstrom#4914

But the extra mats for the guild skill (Bountiful Bags) show a message like this:
U get maelstrom crystal x 1-2
U create maelstrom crystal x 1-2 ---- This part is the bonus for the guild, and I only saw it once a long time ago.

**Comment by UltraNix** [comment]
Fixed.
