### ISSUE TITLE
Quest priest lvl 3

### ISSUE THREAD

**Issue by Pocholuk** [gamefreedomgit/Maelstrom#5020]
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

The quest for learn and practice the spell " pain ", the shadow dot for priest, doesn't work. I can't use it on the mannequin as required. So i can't lvl up. 
Human faction.

**How to reproduce:**

The spell should work 5 times on the mannequin.

**Database links:**

**Comment by UltraNix** [comment]
There is no such quest. Remove your cache folder and try again.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2cbbcafb-197e-483d-afe7-ba4bbc3e9376)
https://wowpedia.fandom.com/wiki/Healing_the_Wounded
