### ISSUE TITLE
Echo of Tyrande Spell Moonbolt

### ISSUE THREAD

**Issue by loboxter** [gamefreedomgit/Maelstrom#5021]
**Description:** Tyrande's Echo boss is casting an ability incorrectly, as it should cast it to its current target and not randomly

**How to reproduce:** The boss ignores the tank and begins casting Lunar Bolt at targets other than his current target

**How it should work:** What should happen is that the boss should cast his Lunar Bolt spell to the tank or dps with more agro at the time, however he casts it randomly causing incredibly high damage to the group and therefore making it very difficult to kill him

**Database links:** boss :  https://www.wowhead.com/es/npc=54544/eco-de-tyrande
spell : https://www.wowhead.com/es/spell=102193/descarga-lunar

Thanks all.

**Comment by UltraNix** [comment]
Fixed.
