### ISSUE TITLE
Missing item in pvp vendor [BUG]

### ISSUE THREAD

**Issue by Krysztal** [gamefreedomgit/Maelstrom#5023]
**Description:**
Item [Ruthless Gladiator's Pummeler] 391 itemlvl is missing in npc Lieutenant Tristia (Stomwind and Azshara, maybe also Orgimmar)

**How to reproduce:**
Check in npc

**How it should work:**
Item has to be present

**Database links:**
https://cata-twinhead.twinstar.cz/?item=70202

**Comment by UltraNix** [comment]
Fixed.
