### ISSUE TITLE
Achievement 4872

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#5025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello there, so I did all quests in Uldum and I have 89/105 complete. So I went to do 2 daily quests. 
https://www.wowhead.com/quest=28736/fire-from-the-sky this one doesnt work. Did report.
https://www.wowhead.com/quest=28250/thieving-little-pluckers does work but it does not add you a point to quests in Uldum complete. 

can you please take a loot at it, thank you

https://www.wowhead.com/achievement=4872/unearthing-uldum

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
You missed  some quests, should be more than 115 in Uldum. Also dailies are noti supposed to count to achievement

**Comment by Asirie1** [comment]
While I was doing the chain quest from the start til the end I took up every single quest I saw at every outpost. I just flew around whole Uldum and didnt notice any quests. Also I'm doing dailies in Twilight Highlands and it does count. Can you please look at it, thank you.
