### ISSUE TITLE
Echo of Tyrande's  Tears of Elune

### ISSUE THREAD

**Issue by Georgiimo** [gamefreedomgit/Maelstrom#5026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Her tears are not falling in the way that they should. I have been getting completely hammered by these without seeing them.

**How to reproduce:**
Take her to 30% and observe.

**How it should work:**
They should be visible while falling and fall quite slow.

Like this: https://youtu.be/OhDisHjtfpY?si=IN5nszIwJRR2CCid&t=88

**Database links:**
https://www.wowhead.com/spell=102241/tears-of-elune

**Comment by UltraNix** [comment]
Fixed.
