### ISSUE TITLE
Pvp replicas

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5028]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
PvP replicas are fully working in pve, they aren't disabled. You can use them in firelands/molten front. This is a bug right?

**Comment by UltraNix** [comment]
@SimonBpvp Some specific items?

**Comment by SimonBpvp** [comment]
I’ll have another check but all of the items were working in pve when I made the report 6 weeks ago, I think I had equipped hc vplc and domo belt but you since added durability to the replica trinkets so maybe u fixed it at that time

**Comment by UltraNix** [comment]
Okay - closing this one.
