### ISSUE TITLE
[Warrior] [Glyph] - Intimidating Shout

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5030]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It is causing my pet to run away and not tremble with the glyph
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/6ce983cb-1c3a-4f72-baae-62de8f8fde5c)
My pet ran away while the Warrior had the glyph active

**How to reproduce:**
Cast Intimidating shout on hunter + pet - with and without the glyph

**How it should work:**
Other units should be feared but tremble in place when you have the glyph

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=5246
https://cata-twinhead.twinstar.cz/?item=45794

**Comment by UltraNix** [comment]
Fixed.
