### ISSUE TITLE
Wraith Scythe weapon heal is bugged

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5031]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Currently it heals only for 1 HP

**How to reproduce:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/5316d679-cf6a-4fff-8540-93fec10997c3)

**How it should work:**

It should also scale 100% with dmg/heal.

**Database links:**

https://www.wowhead.com/item=11920/wraith-scythe

**Comment by Waroxx-QA** [comment]
it happens on that dummy because it has 1 hp.
