### ISSUE TITLE
[Hunter] [Talent] Bestial Wrath not usable under warrior's Intimidating Shout main target

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5032]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When a warrior casts Intimidating Shout on the hunter (main target, not AoE fear) they are trembling in fear and unable to use Bestial Wrath to break it.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/8f11defb-e3c9-408a-8f56-0dfcefc9e099)

**How to reproduce:**
Cast Intimidating Shout on BM hunter
Try to use Bestial Wrath, while also having the Beast Within talent
"Can't do that while stunned"
(Works for HoJ, kidney, Intimidation, deep freeze.. all stuns I can think of)

Try casting Intimidating Shout on BM pet
Hunter gets AoE feared, pet is 'stunned' -> Bestial Wrath Usable

**How it should work:**
Should be able to break main target Intimidating Shout with Bestial Wrath
The same spell can be removed by the pet, so it should be able to be removed by the hunter with The Beast Within

https://www.mmo-champion.com/threads/899890-Does-Bestial-Wrath-realy-act-as-a-second-trinket
```
BW only gives your pet CC immunity. It breaks you out of CCs/slows, but doesn't grant you immunity. I liked being CC immune nuking people :<. Was quite OP in a way though. I can see why it's changed now.
Last edited by Bassch; 2011-05-07 at 10:21 AM.
```
https://web.archive.org/web/20120705170135/http://www.wowhead.com/spell=19574#comments
```
As of 4.0 I've found that Bestial Wrath no longer makes you immune to fear or any other CC while in effect, it just breaks out of them... maybe it's a glitch
    - It was in the patch notes, they got rid of the permanent immunity.
```

**Database links:**
Main target Intimidating Shout spell
https://cata-twinhead.twinstar.cz/?spell=20511

**Comment by Renehadox** [comment]
Didn't bestial wrath worked only for stuns ?

**Comment by Afgann** [comment]
fixed
