### ISSUE TITLE
King Crawler in Ferals dont give Deepsea Scale from Skinning

### ISSUE THREAD

**Issue by blayzer33** [gamefreedomgit/Maelstrom#5033]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)

[https://www.wowhead.com/item=52982/deepsea-scale#skinned-from](url)

**Description:**
King Crawler Level 83-85 usually give DeepSea Scale blizzlike

**How to reproduce:**
While Skinning King Crawler found in lower right swampy zone in feralas, they never give Deepsea Scale. Usually they should, as found on wowhead and other websites refering to good farming locations indicating that this is a very common farming spot.

**How it should work:**
Usually there should be a ca. 30% chance of skinning deepsea scales from said crabs, as for now it sadly doesnt work.

**Database links:**
[https://www.wowhead.com/item=52982/deepsea-scale#skinned-from](url)
[https://www.wowhead.com/npc=51714/king-crawler](url)
[https://www.thebuddyforum.com/threads/skinning-n-deepsea-scales-savage-leather-82-the-steam-pools-feralas.46693/](url)

**Comment by UltraNix** [comment]
Fixed.
