### ISSUE TITLE
Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by shefzp** [gamefreedomgit/Maelstrom#5034]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Ancient Shadowmoon Spirit](https://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit) is missing

**How to reproduce:**

**How it should work:**
must stand still and pass the quest

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 08.03.2024
