### ISSUE TITLE
[Firelands] Ragnaros Heroic 10man - Transition Phase Hammer+Adds spawn bugged

### ISSUE THREAD

**Issue by skyy0** [gamefreedomgit/Maelstrom#5035]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ragnaros Heroic p1->p2 and p2->p3 transition - 

Hammer is visually(and physically) in the centre, but the addspawn is as if the hammer was on the side
For example: 2 on the far left side, 6 on the right side(2-3 of them very close to the hammer)

I will add screenshots / VoDs when we are there again this id.

**How it should work:**
If the hammer is centred, there should be 4 adds per side, not 2 on one side and 6 on the other, 2 of which are completely close to the centre hammer

**Comment by Sketish** [comment]
On heroic adds patterns are randomly not 6/2 4/4 2/6 . Not a bug
