### ISSUE TITLE
Moonskin balancing may be off the charts.

### ISSUE THREAD

**Issue by blayzer33** [gamefreedomgit/Maelstrom#5036]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Moonkins seem nerfed way to hard on the server

**How to reproduce:**
Compairing other classes with same equip, rotation knowledge and progression with each other, the dps of moonkins is too low. While grouping its similar to Tanks and sometimes even below that. 

**How it should work:**
Ok I know its a hard task to try and rebalance the game, however I think in my personal oppinion its best to keep it as close to blizz as possible with doing only whats necessery. It seems a bit off that the Moonkin Druid can only perform 10-12k at 354 iLvL while Hunters are perfroming arround 20k with that iLvL. 

I am not sure about this tho, maybe you want to recheck on this issue. Its just a feeling i get when comparing classes. maybe a good dev wants to recheck this issue :) 

**Database links:**
its hard finding solid data on this but I have found a dps average list of 2012
[https://web.archive.org/web/20120120191450/http://stateofdps.com/](url)

**Comment by Sketish** [comment]
Will be fixed on Friday with all updates to 4.3 dungeons

**Comment by Sketish** [comment]
If player is doing 10-12k with 354ilvl it's player issue. Invalid report
