### ISSUE TITLE
[Dungeon][End Time] Echo of Baine dying mid air makes it impossible to loot the boss

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#5037]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If Echo of Baine dies mid air (doing the cast to break the platforms) he will lay mid air dead, making it impossible to loot him.

**How to reproduce:**
Kill Echo of Baine while he is jumping mid air.

**How it should work:**
If the boss dies mid air he should fall down afterwards.

**Database links:**

**Comment by Sketish** [comment]
Will be fixed on Friday with all 4.3 fixes
