### ISSUE TITLE
Shannox traps dont drop a shard for delegation if a dog steps in the trap

### ISSUE THREAD

**Issue by BroWzeff** [gamefreedomgit/Maelstrom#5038]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Crystal Prison traps from Shannox wont drop shards for delegation quest when a dog gets in the trap. The trap just dissapears and nothing happens.

**How to reproduce:**
Put a dog in the trap and when the trap duration ends it wont drop a shard. When a player gets in the trap and u kill the trap it drops a shard.

**How it should work:**
When a dog gets in the trap the trap's health should decay and when it dies from the decay the trap should drop a shard.

**Database links:**
https://www.youtube.com/watch?v=3Dm61O_w1ug&t=108s (you can skip to 0:55)I am watching this youtube video back from cata and u can see that when the dog gets trapped the trap health decays and then a shard is dropped on the ground. It happens twice

**Comment by UltraNix** [comment]
Fixed.
