### ISSUE TITLE
Can't revive in PVP zone.

### ISSUE THREAD

**Issue by millehouse** [gamefreedomgit/Maelstrom#5039]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you die in the PVP zone, if you release spirit you can't press accept when on top of your corpse, you can see the button but it does not work. This means you're forced to use spirit healer and wait 10 minutes.

**How to reproduce:**
Die in PVP zone and try to revive,  has happened to me on multiple characters, all of them are PoW.

**How it should work:**
You can revive.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
