### ISSUE TITLE
spectator buff visual bug

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5040]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/95730c26-f010-4634-9849-15012b895026)
visual bug: spectator shows a buff so if a lot of people spectate your game it stacks buffs on someone
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/cb5ee0e1-41f2-43a8-b1c5-01ee7e03329e)

**Comment by UltraNix** [comment]
Fixed.
