### ISSUE TITLE
Murozond´s Mechanic Fail

### ISSUE THREAD

**Issue by Juan-9904** [gamefreedomgit/Maelstrom#5042]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description: Character Doesn't move after resurrect

How to reproduce: After using the clock in the battle against Murozond in end of time, when the character revives this one doesn´t move from their respaw position if he was dead, he stuck as if he was falling and you cannot move

How it should work: After using the clock, all characters in the dungeon return to their "Freeze time" Body and they can continue the battle with all their cds restored and if a character was dead it will be resurrected and the battle continues.

https://www.youtube.com/watch?v=Xe3mO-SIH4Q Min 21:10

Database links: https://www.wowhead.com/npc=54432/murozond
https://www.wowhead.com/spell=101591/rewind-time

**Comment by Sketish** [comment]
On ptr was able to move after being ressed by hourglass. What class was tank ?

**Comment by UltraNix** [comment]
Also tested and worked okay.

**Comment by UltraNix** [comment]
No further info - closing.
