### ISSUE TITLE
Volcanoe Card

### ISSUE THREAD

**Issue by ProvokeBC** [gamefreedomgit/Maelstrom#5046]
Volcanic Destruction buff from darkmoon card volcanoe no longer has an internal cooldown.

Equip and watch the proc spam itself on dots and spellcasts. Permanent 1600 intellect.

Should have an internal cooldown.

https://cata-twinhead.twinstar.cz/?spell=89091

Courtesy - Keye

**Comment by Sketish** [comment]
Fix is rdy, just waiting for server restart
