### ISSUE TITLE
[Mage][Glyph of Mirror Image] Clones are dealing low damage and staying in a single spot.

### ISSUE THREAD

**Issue by QQruZZnick** [gamefreedomgit/Maelstrom#5047]
**Description:**
The Glyph of Mirror Image in Fire and Arcane specializations is not functioning correctly. There are two issues with the illusions:

- After summoning, they stack in one spot instead of spreading out to the left, right, and behind the character.
- The damage dealt by illusions is low, approximately 300 for Fireball in the Fire spec and around 250 for Arcane Blast in the Arcane spec, compared to 1500 for Frost.
If this glyph is used for Frost spec, there is no such effect, and the same applies to other specs without this glyph.

**How to reproduce:**
- Apply the Glyph of Mirror Image.
- Cast Mirror Image.
- Start a battle with a random target.

**How it should work:**
- The damage done by illusions with this glyph should be no less than the damage without the glyph (I have no proof about the numbers, but I suppose it should be at least the same).
- Illusions should not stack in one spot after appearing.

**Screenshots:**
![Mirror_images_bug_1](https://github.com/gamefreedomgit/Maelstrom/assets/13526434/6f0c3ce1-dd01-4b73-9b3a-00dca6952f0e)
![Mirror_images_bug_2](https://github.com/gamefreedomgit/Maelstrom/assets/13526434/f79cf424-49aa-4f6f-9c1c-aef305143713)
![Mirror_images_bug_3](https://github.com/gamefreedomgit/Maelstrom/assets/13526434/d3b8e270-72d7-4d68-ae6b-3ccfb415e4a0)
![Mirror_images_bug_4](https://github.com/gamefreedomgit/Maelstrom/assets/13526434/df553804-05db-4bd3-b72b-46a612e1a8ac)
![Mirror_images_bug_5](https://github.com/gamefreedomgit/Maelstrom/assets/13526434/ef02c6f5-25d4-42f3-bc70-ec8bedaa6936)

**Comment by Sketish** [comment]
We need any resource to compare dmg to retail cata numbers

From what I found, during 25hc they were hiting for 2,3k so they should hit at least for same amount as mirriors w/o glyph,.

**Comment by bonfax4** [comment]
Arcane mirror glyph was only a better option than no glyph in retail if the interaction with arcane blast stacks is working properly. Their damage should scale with the mage arcane blast stacks. No idea if this currently working but I doubt it.

https://www.mmo-champion.com/threads/991622-Glyph-of-mirror-image-as-arcane-DPS-Gain/page3

**Comment by QQruZZnick** [comment]
> We need any resource to compare dmg to retail cata numbers
> 
> From what I found, during 25hc they were hiting for 2,3k so they should hit at least for same amount as mirriors w/o glyph,.

I dont think that any video will help you with this issue because:
- Almost all videos that i have seen is a PVP or PVE events which contains large amount of numbers and it is hard to findout which nimber relates to an illusion damage
- As far as I know illusion damage are based on spell-damage, so to be able to precisely calculate all the numbers you will also need a knowledge about character's gear.

What I assume:
On our server we already heave correctly-working illusions. They deal correct non-fixed damage based on character's spell-damage. You can check it by removing gear (in my case they deal ~250 dmg with completely naked character).
I guess the main issue is that after applying this glyph illusion damage formula stops calculating spell-damage.
Besides that what also should be kept in mind - illusion behavior. I did not make full comparison of behavior as it takes alot of time. After spawn they stack in one spot, which is not a correct behavior, and I think potentially their behavior can be different form frost-spec illusions.
Also what I found out - that after some time frost illusions starts to cast fire blast, but I did not observed this behavior for arcane or fire illusions.

I found this comment on wowhead, despite it relates to patch 3.0.3, I dont think that mechanics was changed (https://www.wowhead.com/wotlk/spell=55342/mirror-image#comments:id=508570).


> Arcane mirror glyph was only a better option than no glyph in retail if the interaction with arcane blast stacks is working properly. Their damage should scale with the mage arcane blast stacks. No idea if this currently working but I doubt it.
> 
> https://www.mmo-champion.com/threads/991622-Glyph-of-mirror-image-as-arcane-DPS-Gain/page3

Very interesting topic. Here are some considerations:
**Illusions Damage Calculation**
- Should illusions' damage be based on spell power at the moment they appear or on the character's current spell power?
**Fireblast Casting by Illusions (Glyph of Mirror Image)**
- Should illusions cast Fireblast when the Glyph of Mirror Image is active?
**Arcane Blast (AB) Stacking**
- Should Arcane Blast (AB) stack on the illusions' current AB stack or on the player's current AB stack?

**Comment by bonfax4** [comment]
Player's stacks. They had their own visual blast stacks that didn't work and they scaled with the player's instead. 

Fireblast is only used by the no-glyph/frostbolt version iirc. Fire version only spams fireballs.

**Comment by bonfax4** [comment]
According to sim they take 75% of your spell power. 
![791840d2fe8916ee6c521b1287728cf4](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/df39a2f8-7abd-4aef-b1a1-481b1a9ce556)

and then AB from mirror images takes [ base dmg + 27.5% of mirror image spelldmg <- (owner arcane spell power * 0.75 ) ) ]
![a4b2bda6f8d34abc6c96ca9bbed01146](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/20ced5f4-21ac-4aa7-a879-b8c4cc8d22d2)

With these values you can check if the dmg is correct

**Comment by bonfax4** [comment]
@Sketish I did not test this at at all, not sure if it's currently bugged, Wait for the OP feedback

**Comment by bonfax4** [comment]
Mirror image fireball scaling since it's also broken.

![0a1e4b066b8c78ab730f6012be39b374](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0efa791f-dd8b-4783-ba5e-e622cedc5d70)

**Comment by UltraNix** [comment]
Fixed.
