### ISSUE TITLE
Variable Pulse Lightning Capacitor Damage bug

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#5049]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently lightning capacitor does too much damage, compared to back on retail

**How to reproduce:**
Test on target dummy, make sure it fires on 1 stack so its easier to see how much damage difference there is.
On this server the 1 stack damage does 6285 damage.
https://streamable.com/3byjad

**How it should work:**
https://www.youtube.com/watch?v=BmqY8Cb7RKQ
You can see the big difference from this video alone.
First proc is 1 stack, it does 3.9k damage on the target dummy

Can also check all other stack damage difference, just thought it would be easier to see with just the 1 stack alone :)

**Database links:**

**Comment by mipanka** [comment]
on video normal or hc version? and in ur test normal or hc version? They have different dmg

**Comment by bonfax4** [comment]
Can't even get it to proc like the video honestly, from 0 charges displayed directly into a proc. If you look closely he procced with no charges displayed. But it seems fine when it procs 1+. Proc seems to be charges displayed + 1 but i can never get teh proc at 0 charges.

**Comment by Kenniflopper** [comment]
no charges displayed = 1 stack sent off

**Comment by bonfax4** [comment]
Yeah but in your video you had 1 charge

**Comment by Kenniflopper** [comment]
as u can tell obv

**Comment by Kenniflopper** [comment]
It does not work like that, on cata retail if you procced with 0 charges its 1 stack, it cant fire off without stacks. The trinket cant procc on 0 stacks my guy. it just behaved differently

**Comment by bonfax4** [comment]
Dude compare both videos you linked... a proc from 0 would be 1 charge obv. The video you linked from whitemane you procced it on 1 charge displayed so 2 charge dmg which would be @ 6k

**Comment by Kenniflopper** [comment]
> Dude compare both videos you linked... a proc from 0 would be 1 charge obv. The video you linked from whitemane you procced it on 1 charge displayed so 2 charge dmg which would be @ 6k

It does not work like that on here, you CANT proc on "0" stacks here, so it works differently from retail. Here it actually procs on the actual number it shows.

**Comment by Kenniflopper** [comment]
So if it shows 1 stack here, and it procs, it sends off a 1 stack. 
Retail cata if it procced on "0" it would proc as if it was 1 stack etc.

**Comment by Kenniflopper** [comment]
> on video normal or hc version? and in ur test normal or hc version? They have different dmg

Its obviously heroic, cause if it was normal version it would be really bugged here, it makes most sense he has the heroic version, and that was what i tested with aswell

**Comment by bonfax4** [comment]
If you can't proc it on 0 wouldn't this be a nerf anyway ( in comparison to the way it should work )? Currently its kinda like retail but without proc at 0

**Comment by Kenniflopper** [comment]
Either its damage thats bugged or its the actual proc showing different from retail, but you cant proc on "0" stacks here as shown in the video above. so thats why i believe its the damage. The test team can see for themselves though, i MIGHT be wrong!

**Comment by mipanka** [comment]
> > on video normal or hc version? and in ur test normal or hc version? They have different dmg
> 
> Its obviously heroic, cause if it was normal version it would be really bugged here, it makes most sense he has the heroic version, and that was what i tested with aswell

need to know for sure.

**Comment by mipanka** [comment]
As for the damage, as I said in the discord, it is not constant and it varies (with 1 stack)
I find info about it here https://www.wowhead.com/item=68925/variable-pulse-lightning-capacitor#comments
"Testing today on my demo lock, idly wandering through low level heroics like Sethekk Halls. Saw some numbers that seemed unusually high so I did went to the SW training dummies and experimented a little longer, while watching the combat log. Here are a few numbers I noted. No temporary buffs, no procs (which I assume don't affect it anyway, I'm just saying for thoroughness), no Curse of Elements, just the numbers. Because everyone likes seeing numbers.

4-stack crit: ~33k
2 stack crit: 16.3k
2 stack hit: 9k, 8.7k, 8.2k
1 stack crit: ~13.5k, 10.7k
1 stack hit: ~6.5k, 6.4k, 6k, 5.6k, 3.1k, 3k

If the damage stacks additively, the 4-stack seems like it should have hit harder, and even the 1-stack hits range remarkably widely in their damage.

Trinket says 1034-1333 per stack... but it appears to hit for between 2 and 4 times that amount, a fairly wide range of fluctuation. Or there's just something odd about 1-stack mechanics."

**Comment by Kenniflopper** [comment]
There is many issues with it, i also noticed a wide range of damage, it fluctuates alot aswell.

**Comment by mipanka** [comment]
> There is many issues with it, i also noticed a wide range of damage, it fluctuates alot aswell.

in comment above its not a bug, dmg can be different

**Comment by bonfax4** [comment]
> Trinket says 1034-1333 per stack... but it appears to hit for between 2 and 4 times that amount, a fairly wide range of fluctuation. Or there's just something odd about 1-stack mechanics."

No. The trinket eventually got a buff that did not reflect in tooltip dmg.  https://www.mmo-champion.com/threads/971361-Stealth-Buff-Variable-Pulse-Lightning-Capacitor?highlight=Variable+Pulse+Lightning+Capacitor

**Comment by mipanka** [comment]
> > Trinket says 1034-1333 per stack... but it appears to hit for between 2 and 4 times that amount, a fairly wide range of fluctuation. Or there's just something odd about 1-stack mechanics."
> 
> No. The trinket eventually got a buff that did not reflect in tooltip dmg. https://www.mmo-champion.com/threads/971361-Stealth-Buff-Variable-Pulse-Lightning-Capacitor?highlight=Variable+Pulse+Lightning+Capacitor

all true, in comment ppl wrote it too

**Comment by bonfax4** [comment]
Eh think messing with this further will be a  a bigger nerf than the very minimal nerf it already is for not proccing at 0 honestly. Do you have a log ? Is it outperforming predicted amount of dmg ?

**Comment by mipanka** [comment]
> about proc woth 0 stack, this happens when trinket is triggered, also triggerd proc lightning

"about proc woth 0 stack, this happens when trinket is triggered, also triggerd proc lightning"

**Comment by bonfax4** [comment]
I'm aware but proc at 0 does not happen on whitemane. Only 1+

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/7d4b084f-d8c6-43ca-913f-c3884f4177ba)
normal version, I see now dmg less than in comment wowhead

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/2012cb69-ee6a-49c5-915b-b50d0fae8f40)
 next test same 2 stack and dmg more

**Comment by mipanka** [comment]
> I'm aware but proc at 0 does not happen on whitemane. Only 1+

dont care, u get ur stack and he will proc late

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/e9bd5810-e3ff-4443-8393-b7fbebf95cd5)
2 stack
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/b315d2aa-0227-4e53-b23e-e13641578b6b)
2 stack
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/c8af418a-5109-4052-815e-e36566a5bfb4)
2 stack

**Comment by SimonBpvp** [comment]
> There is many issues with it, i also noticed a wide range of damage, it fluctuates alot aswell.

The damage is indeed quite Variable I would say

**Comment by Kenniflopper** [comment]
The trinkets should hit a fixed damage as per tooltip since nothing else will be taken into account, except increased nature damage stuff. so realistically hc should hit 3301 per stack.

**Comment by Kenniflopper** [comment]
Normal version hits 6k on dummies aswell, and on tooltip it should do 3x less damage. 
So both versions are broken right now, since the damage doesnt scale with int, sp, or anything else but + nature damage stuff.

**Comment by mipanka** [comment]
tooltip is the last place to look

**Comment by Kenniflopper** [comment]
No its not, unless you have real patch notes / dev blog about the trinket. :)

**Comment by mipanka** [comment]
> No its not, unless you have real patch notes / dev blog about the trinket. :)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/a7965518-b9a3-471d-9d69-b5b37c436299)

**Comment by Kenniflopper** [comment]
> > No its not, unless you have real patch notes / dev blog about the trinket. :)
> 
> ![image](https://user-images.githubusercontent.com/127995853/283649035-a7965518-b9a3-471d-9d69-b5b37c436299.png)

This is random wowhead comments, the video i linked was taken from a retail video.

**Comment by mipanka** [comment]
yes, but better than nothing

**Comment by mipanka** [comment]
> > > No its not, unless you have real patch notes / dev blog about the trinket. :)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/127995853/283649035-a7965518-b9a3-471d-9d69-b5b37c436299.png)
> 
> This is random wowhead comments, the video i linked was taken from a retail video.

we didnt see hc or normal capa, and only 1 hit, its so low

**Comment by mipanka** [comment]
I think now there is not enough evidence to say anything

**Comment by Kenniflopper** [comment]
> I think now there is not enough evidence to say anything

I linked a retail video of how much it should do on a dummy, you can look at tooltip and take that as reference.

**Comment by mipanka** [comment]
> > I think now there is not enough evidence to say anything
> 
> I linked a retail video of how much it should do on a dummy, you can look at tooltip and take that as reference.

In tooltip 1035 dmg, in video 3900. Tooltip or video false in ur logic

**Comment by Kenniflopper** [comment]
so if you take into account the "hidden buff" it does the 800 more dmg than it should on heroic version tooltip. thats still not near as close as the damage it does on maelstrom server right now. So even with the hidden buff its still almsot double as broken as it should be.

**Comment by bonfax4** [comment]
They do not do a  static amount of dmg btw. If you go to wowpedia you can see the updated tooltip for the dmg variation after the hotfix. No idea on what it should scale with but it used to scale with arcane mastery or anything that specifically increased spell dmg done before the hotfix, so if nothing was changed that can easily justify the higher dmg you see on the retail video. 

Tooltip for the hc version is correct in terms of average dmg but it also does a [range of dmg.](https://cata-twinhead.twinstar.cz/?item=69110) ( 2888 - 3713 ) 

https://wowpedia.fandom.com/wiki/Variable_Pulse_Lightning_Capacitor?oldid=2784662
![0e80712d6046ebf11c726d8a29caa3e5](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0d7904a7-9323-4769-8def-dab722e265af) 

Simc shows the average as 2926 on normal version which is pretty accurate . 5853/2 = 2926.5. 
![a93abb592b21cc842e9c5d097c1b20d0](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/da469921-3fb5-4c3c-b8d0-4b64463c0d9c)

All the dmg I'm seeing is within range. It seems to scale with arcane mastery too since im hitting for more than the range sometimes  arcane spec but never more than max-min * mastery.

**Comment by Pornoodemon** [comment]
This damage is influenced by all passive and active effects that increase damage. Therefore, Damage will vary for different classes and specializations.

**Comment by Pornoodemon** [comment]
If this is an owl druid or a warlock in demonology, then the damage can be increased by 50-70 - sometimes even by 100%.
For example, in metamorphosis my damage is increased by 65%, so the lightning damage output will also be increased.
The rest varies by talents, passives, etc. Therefore, I think there are no errors in the operation of this trinket

**Comment by mipanka** [comment]
btw from https://wowpedia.fandom.com/wiki/Variable_Pulse_Lightning_Capacitor?oldid=2784662
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/75e19388-bdd9-4c99-ab06-8e37b7723457)

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/1df06b17-dce8-4f03-89b7-e8f93034e285)
As I understood from comment, bdru can increased dmg (which everyone knew)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/5883c472-914e-4ef0-959a-e1eef4799771)

**Comment by mipanka** [comment]
https://youtu.be/BmqY8Cb7RKQ?t=66 (with time)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/023d15c6-6678-4549-931a-c6cf74e3b9d2)
6.4k dmg 1 stack capacitor in buff

**Comment by Kenniflopper** [comment]
> https://youtu.be/BmqY8Cb7RKQ?t=66 (with time) ![image](https://user-images.githubusercontent.com/127995853/283796244-023d15c6-6678-4549-931a-c6cf74e3b9d2.png) 6.5k dmg 1 stack capacitor in buff

Pls stop saying random stuff. As i said above. 
Capacitor on retail worked that it could proc on (0) which mean 1 stack.
On your timestamp it say 1 and then he crit and it proc which means it proc on 2 stack.

**Comment by Kenniflopper** [comment]
> They do not do a static amount of dmg btw. If you go to wowpedia you can see the updated tooltip for the dmg variation after the hotfix. No idea on what it should scale with but it used to scale with arcane mastery or anything that specifically increased ~spell dmg~ % dmg done ( checked [majordomo video](https://www.youtube.com/watch?v=ZNo6UZcUV7I) and dmg was increased by the buff ), so if nothing was changed, that can easily justify the higher dmg you see on the retail video.
> 
> Tooltip for the hc version is correct in terms of average dmg but it also does a [range of dmg.](https://cata-twinhead.twinstar.cz/?item=69110) ( 2888 - 3713 )
> 
> https://wowpedia.fandom.com/wiki/Variable_Pulse_Lightning_Capacitor?oldid=2784662 ![0e80712d6046ebf11c726d8a29caa3e5](https://user-images.githubusercontent.com/16911730/283705616-0d7904a7-9323-4769-8def-dab722e265af.png)
> 
> Simc shows the average as 2926 on normal version which is pretty accurate . 5853/2 = 2926.5. ![a93abb592b21cc842e9c5d097c1b20d0](https://user-images.githubusercontent.com/16911730/283706009-da469921-3fb5-4c3c-b8d0-4b64463c0d9c.png)
> 
> All the dmg I'm seeing is within range. It seems to scale with arcane mastery too since im hitting for more than the range sometimes in arcane spec but never more than max-min * stacks * mastery.

i know they dont do a static amount, that cant make it fluctuate so much it does basicly twice or triple the amount of damage on this server compared to retail. 

As the videos above says, i test on a heroic capacitor it says 3101 on tooltip which is after the 2.6x damage buff. cause that buff is already on the core cus we play on 4.3.4.

And 1 stack on here does 6289 damage. IF i rememebr correctly, lightning capacitor does not scale with anything, meta form, etc. only stuff that increases nature damage / magic damage taken for example curse of elements.

**Comment by bonfax4** [comment]
Bro I linked you a retail video that shows a 3 stack almost hitting for 30k non crit with max concentration on majo. It clearly scales with % auras. 1 stack is 6K since it's a 2 stack dmg worth when procced. Even the retail video shows a 3.9k hit which  shouldn't even be possible since the max dmg on hc trink is 3.7 before auras

**Comment by mipanka** [comment]
> > https://youtu.be/BmqY8Cb7RKQ?t=66 (with time) ![image](https://user-images.githubusercontent.com/127995853/283796244-023d15c6-6678-4549-931a-c6cf74e3b9d2.png) 6.5k dmg 1 stack capacitor in buff
> 
> Pls stop saying random stuff. As i said above. Capacitor on retail worked that it could proc on (0) which mean 1 stack. On your timestamp it say 1 and then he crit and it proc which means it proc on 2 stack.

Proof? As Im see hit trigger stack and this hit trigger proc

**Comment by Kenniflopper** [comment]
> > > https://youtu.be/BmqY8Cb7RKQ?t=66 (with time) ![image](https://user-images.githubusercontent.com/127995853/283796244-023d15c6-6678-4549-931a-c6cf74e3b9d2.png) 6.5k dmg 1 stack capacitor in buff
> > 
> > 
> > Pls stop saying random stuff. As i said above. Capacitor on retail worked that it could proc on (0) which mean 1 stack. On your timestamp it say 1 and then he crit and it proc which means it proc on 2 stack.
> 
> Proof? As Im see hit trigger stack and this hit trigger proc

Can you explain why in the video he procs on 0stacks? Because He crits and that crit sends away a 1 stack bolt.

**Comment by Kenniflopper** [comment]
> Bro I linked you a retail video that shows a 3 stack dmg worth almost hitting for 30k non crit with max concentration on majo. It clearly scales with % auras. 1 stack is 6K since it's a 2 stack dmg worth when procced. Even the retail video you linked shows a 3.9k hit which shouldn't even be possible since the max dmg on hc trink is 3.7 before auras

The 800 dmg difference is the hidden buff as mipana had shown and as explained above. So tooltip says 3301, i have no damage modifier, anything. And both capacitor trinkets hits way harder Than they should, even if you say that damage modifiers should Increase the damage that was not the test that was done. :)

**Comment by bonfax4** [comment]
I literally tested both trinkets, so you're just lying now. Check the range of dmg again and redo all your calcs. I never did more than the min-max  X stacks dmg I linked above. Your whole calculation is just wrong because you're assuming the proc at 1 should be 1. 1 stack visual should and does between 5122 - 6584 before modifiers. I never did more than that on my tests

**Comment by bonfax4** [comment]
Mipanka linked normal version at 2 stacks and his logs show dmg within the expected range...  2561 *3 to 3292 * 3 which is between 7683 and 9876. What exactly is wrong ?

**Comment by SimonBpvp** [comment]
I think you guys are looking at 2 different bugs at the same time. 
Need to make report 1. Stacks firing at wrong time. 2. Damage of lightning bolt wrong

**Comment by mipanka** [comment]
not proof, I just went to Apollo, 1 stack does exactly the same amount of damage as here. But it can work from 0 stacks to 3k+

**Comment by SimonBpvp** [comment]
so on retail it could fire on 0 stacks, on whitemane it cannot fire on 0 stacks. Thats the difference right?

**Comment by SimonBpvp** [comment]
so on retail the trinket had the option to fire on 0 stacks without adding one stack buff. But on whitemane it can never fire on 0, it will always add 1 stack if 0 stacks are present. That's the difference right?

**Comment by mipanka** [comment]
> so on retail the trinket had the option to fire on 0 stacks without adding one stack buff. But on whitemane it can never fire on 0, it will always add 1 stack if 0 stacks are present. That's the difference right?

mb, dmg with 1 stack same where we not tested and calculete

**Comment by Waroxx-QA** [comment]
So it's supposed to proc even at 0 stacks.

**Comment by UltraNix** [comment]
Fixed.
