### ISSUE TITLE
Rich Thorium Vein bad skill requirements

### ISSUE THREAD

**Issue by Sungis18** [gamefreedomgit/Maelstrom#5051]
**Description:**
Hi, I've encountered an issue where minning rich thorium veins is available earlier than 275 as mentionned in the Wotlk wowhead here:
https://www.wowhead.com/wotlk/object=175404/rich-thorium-vein

As a result, the rich thorium vein get become green too early making it hard to get to 300 with minning.

**How to reproduce:**
Level minning from ~275 to 300 regularly, the only way is to mine thorium/rich thorium veins.

**How it should work:**
The rich thorium vein should be minnable at 275 making it yellow between 275-300.

**Database links:**
https://www.wowhead.com/wotlk/object=175404/rich-thorium-vein

**Comment:**

The Twinstar link shows 255 required level for minning rich thorium vein but I think this isn't accurate as it cause this issue.

**Comment by Waroxx-QA** [comment]
<html>
<body>
<div class="comment-header" style="outline: none; max-height: 1e+06px; color: rgb(187, 187, 187); font-size: 13px; margin: 0px; padding: 0px 0px 0px 10px; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
By Sithari (434 – 5·4) on 2010/05/11 (Patch 3.3.3) |   |  
-- | -- | --


</div><div class="text comment-body" lang="en" style="outline: none; max-height: 1e+06px; overflow: auto; padding: 10px 0px; color: rgb(187, 187, 187); line-height: 1.4; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 24, 24); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Latest changes to mine go as follows:<br style="outline: none; max-height: 1e+06px;"><br style="outline: none; max-height: 1e+06px;">Rich Thorium Vein requires 255 mining (old one: 275)<br style="outline: none; max-height: 1e+06px;">Truesilver Deposit requires 205 mining (old one: 235)</div>
</body>
</html>By [Sithari](https://www.wowhead.com/user=Sithari) (434 – 5·4) [on 2010/05/11](https://www.wowhead.com/object=175404/rich-thorium-vein#comments:id=1036748) (Patch 3.3.3)		
Latest changes to mine go as follows:

Rich Thorium Vein requires 255 mining (old one: 275)
Truesilver Deposit requires 205 mining (old one: 235)
