### ISSUE TITLE
[Core][Death Knight] Death Grip on casting NPCs

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#5056]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometimes (really not always, but often enough) when you death grip a NPC that's casting or channeling something, the actual gripping of the target won't happen, although the taunt does.

**How to reproduce:**
Death Grip a casting/channeling NPC.

**How it should work:**
Should still grip the target.

**Database links:**

**Comment by UltraNix** [comment]
@Whatisthisclass Could you give us exact example of such NPC?

**Comment by Sungis18** [comment]
So here's en example of the problem when it occurs:
https://github.com/gamefreedomgit/Maelstrom/assets/4041328/8af21e6f-a3f0-4207-8080-93b0cb0ac431

It seems that the creature is cancelled (because of the grip, which is normal) but attempt to cast again in mid air which makes it cancel the grip.

**Comment by Whatisthisclass** [comment]
Sorry for the late reply.

@Sungis18 thank you for the example. This is exactly one of the situations that I meant. Sometimes the NPC won't even be gripped by a bit, it will just stand there doing nothing and then continue it's normal behaviour after a few seconds.
But to summarize it, the clip shows exactly what I meant.

**Comment by UltraNix** [comment]
@Whatisthisclass Could you re-test it?

**Comment by Afgann** [comment]
fixed
