### ISSUE TITLE
QUEST "Were-surrounded" bugged and no further quest active

### ISSUE THREAD

**Issue by OsPav** [gamefreedomgit/Maelstrom#5057]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Username - Druugi 
Quest in Deepholm see link below is bugged, after killing all 12 mobs as returning quest to [Earthbreaker Dolomite](https://www.wowhead.com/npc=43160/earthbreaker-dolomite)
there is no further quest appear. 

Beacause of that whole quest line for opening fraction reputation of Therazane is interrupted and no reputation / enchant / items gain possible.

**How to reproduce:**

**How it should work:**
Please activate or reset whole a quest line for User: Druugi begining with [Earthbreaker Dolomite](https://www.wowhead.com/npc=43160/earthbreaker-dolomite)

After Returning https://www.wowhead.com/quest=26500/were-surrounded 
to [Earthbreaker Dolomite](https://www.wowhead.com/npc=43160/earthbreaker-dolomite)
Quest https://www.wowhead.com/quest=26502/thunder-stones
should appear

**Database links:**
https://www.wowhead.com/quest=26500/were-surrounded

**Comment by Waroxx-QA** [comment]
You should've missed [Sealing the Way](https://www.wowhead.com/quest=26501/sealing-the-way)
All the quests are there.

**Comment by OsPav** [comment]
@Waroxx-QA 

i^ve done [Sealing the Way](https://www.wowhead.com/quest=26501/sealing-the-way)
and returned it, also i^m missing the 
[Rockslide Reagents](https://www.wowhead.com/item=58885/rockslide-reagent)
beacuse of the done quest.

there ist no previous or further quests active in the area (checked 1 min ago) also talked to all NPCs for possible dialogs. nothing.
still can not go on in the quest line
