### ISSUE TITLE
Balance druid pvp 4 set not working

### ISSUE THREAD

**Issue by PrinceArtyx** [gamefreedomgit/Maelstrom#5058]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Basically balance druid pvp 4 set not working at all. It should give you solar or lunar energy when you recieve crit attacks, but it's not giving you anything. It was working before but not anymore for some reason

**How to reproduce:**
Get bommy 4 set, and recieve crit attacks.

**How it should work:**
Every 6 sec you recieve a crit attack, you should get 20 solar or 13 lunar energy whichever is more beneficial to you

**Database links:**
https://streamable.com/vqxlxc

**Comment by Waroxx-QA** [comment]
Duplicate - #5052
