### ISSUE TITLE
Draconic mending quest 

### ISSUE THREAD

**Issue by Dufelow** [gamefreedomgit/Maelstrom#5060]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi,

Draconic mending quest :
I keep killing the baddies but the quest do not progress.
Is it me or a bug ?

Thanks :)

**How to reproduce:**

**How it should work:**
Quest should advance

**Database links:**

**Comment by PanJanuszek** [comment]
To progress you have to keep all 5 mending healing, otherwise you will have to do it twice or more.
