### ISSUE TITLE
Glyph of Lifebloom

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#5062]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have reason to believe glyph of lifebloom isn't affecting the crit chance of the final bloom.

**How to reproduce:**
https://i.imgur.com/xKUhm9M.png - 29.6% crit chance on my normal bloom ticks
https://i.imgur.com/nj1iEsH.png - 17.1% crit chance on my actual bloom

**How it should work:**
The glyph states it increases the crit chance of your lifebloom by 10%, which should include the bloom at the end.

**Database links:**

**Comment by bonfax4** [comment]
https://www.wowhead.com/item=40915/charred-glyph#comments

> The spell effect is the same as the [T11 2 pieces set bonus ](https://www.wowhead.com/spell=90157)[code]Apply Aura: Add Modifier - Flat (7) Value: 5[/code]only 10% instead of 5%, so I believe it applies only to the periodic portion.

> It would appear to increase the crit chance of tick. With a run thru a heroic VP (1954 ticks) I had a base crit chance of 14.55%. Recount shows 25.9% (507) crit.


![01224beee9028937736d52696efdbd08](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/c4df6094-c40a-46bf-accb-3d3517963518) ![191ff22eb1ed28df45c9368670cdbb9f](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/9e942e35-eeeb-4254-b37c-c63a1fb4e142)


This is very early cata comments tho, so you need to find actual proof at least that it should affect bloom

**Comment by Waroxx-QA** [comment]
Not a bug till you get a proof that it affects Bloom.

**Comment by bonfax4** [comment]
Also, bloom effect is using the target crit chance and not your own. Which makes this even less likely
