### ISSUE TITLE
HoT, Archibishop Benedictus

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#5063]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
idk how, but we skipped dark phase on archibishop benedictus

**How to reproduce:**
idk

**How it should work:**
dark phase should start on 60% of boss hp

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/63796901/a8f86242-a903-486c-ae79-e08b237ce137)
as u can see on screen shot, boss is almost dead but its still holy phase

**Comment by UltraNix** [comment]
Fixed.

**Comment by ETatskyi** [comment]
> Fixed.

looks like its now "overfixed"
made another ticket
https://github.com/gamefreedomgit/Maelstrom/issues/5136
