### ISSUE TITLE
Battle of life and death quest!

### ISSUE THREAD

**Issue by Fegyoxx** [gamefreedomgit/Maelstrom#5065]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The npc who should give this quest is not there!
https://wowpedia.fandom.com/wiki/Battle_of_Life_and_Death

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
It requires pre-quest:
https://www.wowhead.com/cata/quest=28712/enter-the-dragon-queen

I have tried it, took 28712 and I see NPC normally:
![image](https://github.com/user-attachments/assets/73c780c4-1f8a-4308-8948-416cbdbf77fa)
