### ISSUE TITLE
Battle for Gilneas

### ISSUE THREAD

**Issue by Lite3333** [gamefreedomgit/Maelstrom#5066]
When initiating the battle for Gilneas by speaking with Krennan Aranas and clicking the start chat bubble, my character is dropped thru the world and killed.  I tried this 4 times and the final time when it killed me I clicked "release to graveyard" instead of putting me in the Gilneas graveyard it placed me in the Westfall graveyard.  So at lest it freed me from purgatory.

**Comment by Lite3333** [comment]
I am not permitted to pvp due to the "Battle of Gilneas" quest not being complete, which is the last quest in my racial introduction quest line.

**Comment by PanJanuszek** [comment]
Fixed after server restart

**Comment by Lite3333** [comment]
All is good. thank you.
