### ISSUE TITLE
QUEST "Were-surrounded" bugged REissued

### ISSUE THREAD

**Issue by OsPav** [gamefreedomgit/Maelstrom#5067]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://github.com/gamefreedomgit/Maelstrom/issues/5057#issue-2000102595

issue is not fixed.
No quest active. All previous quests done and no quest items left.
**How to reproduce:**

**How it should work:**
Reset quest line 

**Database links:**
see description

**Comment by PanJanuszek** [comment]
I have got Thunderstones as should.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/1341fe96-14e1-4bb7-a159-2f468d97e135)

no repro on 16.04.2024
