### ISSUE TITLE
Hour of Twilight - Add Faceless Brute

### ISSUE THREAD

**Issue by loboxter** [gamefreedomgit/Maelstrom#5069]
**Description:** : This Add casts an ability incorrectly as when using its "Squeeze Life" spell it should drop the target when it receives an amount of 29508p according to wowhead.com

**How to reproduce:** You just have to wait for him to use his spell

**How it should work:** It should release the target when taking a certain amount of damage

**Database links:** https://www.wowhead.com/es/spell=102861/exprimir-vida

TY All.

**Comment by Sketish** [comment]
It's releasing target after you deal enough dmg to him
