### ISSUE TITLE
Portals in the end of Hour of Twiligh 

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#5070]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
looks like active portal is depend of faction of leader (if he is from horde active is to Orgrimar etc.)

**How to reproduce:**
just go into dungeon with different leaders from different factions

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
Something similar happens with the traveling tundra mammoth mount:
example:

If the leader is an alliance and your mount is a horde, the npcs are useless.

If the leader is a horde and the mount is an alliance, the NPC's are useless.

If the leader is an alliance and the mount is an alliance, it works for the NPC's.

If the leader is horde and the mount is horde, if the npc's work

Could there be a way to make the mammoth npc's work for both?

**Comment by UltraNix** [comment]
@Revly Not related to this one, Please, make a new report about it.

**Comment by UltraNix** [comment]
Fixed.
