### ISSUE TITLE
Quest npc missing 26171

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#5071]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.wowhead.com/quest=26171/you-are-rakhlikh-demon

missing npc at top of the mountain

https://www.youtube.com/watch?v=KWuPXBuoVc0 here is how it should work

cannot complete loremaster therefore

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/4bb52a6a-14ed-40d2-8245-2459d7a33644)
 quest works in 100% you have to talk with that ghost to teleport at the top of the mountain... closing

**Comment by MrTide** [comment]
reopening the report this event has been inactive and not working for long while i would assume developers disabled it due a crash

**Comment by PanJanuszek** [comment]
I tested it locally yesterday. Can you confirm it on main?
