### ISSUE TITLE
Well of Eternity- Queen Azshara- Arcane Mage-Arcane Bomb

### ISSUE THREAD

**Issue by loboxter** [gamefreedomgit/Maelstrom#5073]
**Description:** : Queen Azshara's Arcane Mage NPC is casting a spell incorrectly, this would be the arcane bomb as it is casting it instantly and generating a huge amount of unblockable damage when it shouldn't be. 

**How to reproduce:** : Wait for Queen Azshara's npc arcane mage to come out and you'll see how you can't even see where the impact of the arcane bomb is going to land, it just gives you huge damage with no time to react

**How it should work:**:  The arcane mage must summon an arcane bomb in a place above a random player that after 6-8 seconds will create an impact that generates a lot of damage and also reduces the movement speed by 50%, however you can see in the video how you don't even see the arcane bomb, but directly take the damage,   making it impossible to react :   https://www.youtube.com/watch?v=Lcc0qfUoLoE&ab_channel=SebasLobo

**Database links:** : You can see in the link: https://www.wowhead.com/es/npc=54853/reina-azshara/heroico-gu%C3%ADa-de-mazmorras : that the last ability of the arcane mage is called "Arcane Bomb" https://www.wowhead.com/es/spell=102455/bomba-arcana?dd=2 and that it must generate an impact after 6-8 seconds from the beginning of its fall, as an example I will put a link to a video on youtube you can place it at minute 22:13 to be able to observe the arcane bomb how it descends and the damage is not instantaneous

https://www.youtube.com/watch?v=k1qe98LdKpo&ab_channel=AltehuzGamer277AdrianMac%C3%ADas

Ty all.

**Comment by UltraNix** [comment]
Fixed.
