### ISSUE TITLE
Auction house searches not working for certain items.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#5074]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When searching for specific types of crafted jewlery, i.e. Hessonite Band or Nightstone Choker, nothing shows up in the auction house search, when typing in the specific item enchant, for instance "of the Soldier" or the like.

**How to reproduce:**
Search the auction house for a stats combination, like "Windstorm" or "Bouldercrag", and see how it does not give any results at all, even though said items are actually on the AH.

**How it should work:**
All items with the searched word should appear in the search results.

**Database links:**
https://cata.cavernoftime.com/item=52316
https://cata.cavernoftime.com/item=52314
https://imgur.com/a/K8tA5Fx

**Comment by UltraNix** [comment]
Fixed.
