### ISSUE TITLE
The Exorcism of Colonel Jules 10935

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#5076]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules
When you click the npc to begin with exorcism, nothing happens

https://www.bing.com/videos/riverview/relatedvideo?q=the%20exorcism%20of%20colonel%20jules%20wow&mid=0443D8B23009BAD5E31C0443D8B23009BAD5E31C&ajaxhist=0

here is how it should work
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after restart
