### ISSUE TITLE
Vashj'ir questline bugged

### ISSUE THREAD

**Issue by EchoRigger** [gamefreedomgit/Maelstrom#5078]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Once the very first quests have been completed, you recieve the quests "Buy us some time" and "Traveling on our stomachs". These quests can't be completed. When attacking either the crabs or the nagas, they never truly enter combat. They take damage from your initial attack, but then immediately regenerate the damage taken, so they can't be killed. I've had this happen on two different chars now, but on my first character, I didn't encounter problems with the quests.

**How to reproduce:**
Hit level 80 with an alliance character (so far it's happened to me with a mage and a lock). Do the Vashj'ir questline and watch it fail.

**How it should work:**
The nagas and crabs should enter combat properly and be killable.

**Database links:**
Buy us some time quest:
https://www.wowhead.com/quest=25357/buy-us-some-time

Traveling on our stomachs quest:
https://www.wowhead.com/quest=25546/traveling-on-our-stomachs

**Comment by frostwave942** [comment]
in twilight shore (north from dragonmaw port) something similar happens, when u hit nagas with ur pet and then hit them with ur skills, the nagas regenerates their health making them difficult or impossible to kill.

**Comment by Afgann** [comment]
fixed
