### ISSUE TITLE
Vial of the Sands (Sandstone Drake) not work properly as ground mounts 

### ISSUE THREAD

**Issue by iqraaswad** [gamefreedomgit/Maelstrom#5080]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
today, i bought Vial of the Sands item. when i trying to use it at firelands or Hot... i can't click it... 

**How to reproduce:**
Go to dungeons or Firelands. then try to use that mount. We can use other flying mount. but not sandstone Drake

**How it should work:**
In cata, flying mounts should work as standard ground mounts in no fly zones.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/93418373/ab1d8faa-a8b4-4e46-b7eb-46aeee92cbfa)

**Comment by UltraNix** [comment]
It's clientside - nothing we can do about it.
