### ISSUE TITLE
Missing Quest - Additional Materials (TBC, Terokkar Forest, Alliance)

### ISSUE THREAD

**Issue by Vic-Dim** [gamefreedomgit/Maelstrom#5081]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://www.wowhead.com/quest=10664/additional-materials
https://tbc-twinhead.twinstar.cz/?quest=10664

**Description:**
There's a medium-length questline (which rewards amazingly cool looking daggers in the end) that starts by obtaining an [item drop](https://www.wowhead.com/tbc/item=30756/illidari-bane-shard)  by killing [Overseer Ripsaw](https://www.wowhead.com/tbc/npc=21499/overseer-ripsaw) in Shadowmoon Valley and leads to going around several dungeons and collecting resources for the quests that open next. However, once you turn in the quest "[The Hermit Smith (Alliance)](https://www.wowhead.com/quest=10662/the-hermit-smith)", the next one from the chain doesn't appear. 

**How to reproduce:**
Go to Legion Hold in Shadowmoon Valley and kill the forementioned NPC to obtain the forementioned shard. Turn in the quest to [Ordinn Thunderfist](https://www.wowhead.com/npc=19370/ordinn-thunderfist) in Wildhammer Stronghold and accept the [next quest](https://www.wowhead.com/quest=10626/capture-the-weapons). Obtain the required items, turn in to Ordinn again and accept The Hermit Smith. Fly to Terokkar Forest to turn in the quest.

**How it should work:**
The Hermit Smith:
https://www.youtube.com/watch?v=14fw9685l-Q
https://www.youtube.com/watch?v=Jlw2bnr13tE

Additional Materials:
https://www.youtube.com/watch?v=v2bo15xQegw
https://www.youtube.com/watch?v=xxx2gEwfbqQ

**Database links:**

**Comment by PanJanuszek** [comment]
fixed after restart
