### ISSUE TITLE
What Book? I Don't See Any Book 10231

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#5083]
https://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book

the npc "Dirty" Larry is at the wrong position and also is an enemy (for me as ali, idk about horde).
![WoWScrnShot_112123_230222](https://github.com/gamefreedomgit/Maelstrom/assets/146331666/736f2b2a-4292-4dec-aee3-094e1729357c)

here is how it should work

https://www.youtube.com/watch?v=Kb-SuL9S_h4

**Comment by PanJanuszek** [comment]
Fixed after restart
