### ISSUE TITLE
Thorns of the Dying Day should drop 

### ISSUE THREAD

**Issue by chenran1219** [gamefreedomgit/Maelstrom#5084]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After so many days of farm trashs in HoT WoE and End Time, i have never see Thorns of the Dying Day in AH or any loot from my dungeon. 

**How to reproduce:**
Farm the trash of three new dungeons.

**How it should work:**
Thorns of the Dying Day should be in the drop list of the trash in the three new dungeon.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=76155

**Comment by UltraNix** [comment]
Fixed.
