### ISSUE TITLE
Lightwell Not targetable / Killable

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#5087]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently you cant even left click (target) lightwell at all, it should spawn with 89k hp and be targetable and killable.

**How to reproduce:**
Summon a Lightwell and try and click / attack it. You will see you can't do either.

**How it should work:**
https://www.youtube.com/watch?v=CsCdPuS6cK8&t=226s
Lightwell Should spawn with a set hp amount and should be able to be killed.

**Database links:**

**Comment by djesic** [comment]
983 HP

**Comment by Afgann** [comment]
fixed
