### ISSUE TITLE
Teron Gorefiend, I am 10645

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#5088]
https://www.wowhead.com/tbc/quest=10645/teron-gorefiend-i-am

Accepting the quest turns you into demon but you cant attack the quest target, cant cast spells because it says you are silenced/pacified

https://www.youtube.com/watch?v=Czm_ucQdB9A

how it should work

thank you

**Comment by PanJanuszek** [comment]
fixed 08.03.2024
