### ISSUE TITLE
All or Nothing Quest

### ISSUE THREAD

**Issue by Xaime1983** [gamefreedomgit/Maelstrom#5089]
I can't complete the "All or Nothing" quest in Vashj'ir - Kelp'thar Forest. I've tried killing naga's, doing nothing for like 5-10 mins, and retaking the quest. Naga's should take me somewhere but nothing happens...

I've logged out and back again, I've disabled all my addons, and tried again nothing happened, I can take the quest, and start the fight and it would take forever.

**Comment by Revly** [comment]
x2

**Comment by PanJanuszek** [comment]
Fixed after restart
