### ISSUE TITLE
[Achievement]  Pilgrim's Peril  -  Undercity not working

### ISSUE THREAD

**Issue by MijatRanok** [gamefreedomgit/Maelstrom#5090]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
By sitting in Undercity (at around 61.98, 66.62) achievement is not completed. 

**How to reproduce:**
Wear either a Pilgrim's Dress, Robe or Attire and take a seat at Undercity's Bountiful Table. 

**How it should work:**
Undercity should be checked (as completed) under achievement Pilgrim's Peril.

**Database links:**
https://cata-twinhead.twinstar.cz/?achievement=3580

**Screenshot:**
https://imgur.com/a/FoQhrAK

**Comment by UltraNix** [comment]
Fixed.
