### ISSUE TITLE
Hunter pets still broken

### ISSUE THREAD

**Issue by ryznnxxxx** [gamefreedomgit/Maelstrom#5091]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Heart of the Pheonix talent doesnt work 9/10 times and the 1 time it will work you need to be standing ON TOP of your pet. Hunter pets will stop attack mid PvP and just stand there you cannot dismiss them they wont move and then about 2 minutes later they just vanish, Cant dismiss a dead pet, It will randomly tell you pet is not in line of sight for masters call or mend pet when its literally right infront or beside you, It will randomly run off it bg or get stuck under the map or on some object. The pathing needs to be worked on badly and some of the pet skills, Ive been trying to report this for months now. -Thanks xP

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by oldspices** [comment]
i have issue where my mage pet is grayed out as if im mounted- but im not and its not in a cc it just wont do shit but run around aimlessly :D

**Comment by ryznnxxxx** [comment]
> i have issue where my mage pet is grayed out as if im mounted- but im not and its not in a cc it just wont do shit but run around aimlessly :D

- Yeah I've had that problem on my mage as well
-

**Comment by UltraNix** [comment]
@ryznnxxxx 
`Heart of the Pheonix talent doesnt work 9/10 times and the 1 time it will work you need to be standing ON TOP of your pet.`
`Hunter pets will stop attack mid PvP and just stand there you cannot dismiss them they wont move and then about 2 minutes later they just vanish`
`Cant dismiss a dead pet, It will randomly tell you pet is not in line of sight for masters call or mend pet when its literally right infront or beside you`
`It will randomly run off it bg or get stuck under the map or on some object`
Please - provide some evidences/screenshots of all these situations.

**Comment by UltraNix** [comment]
@djesic When it fails, see any spell error?

**Comment by djesic** [comment]
Nothing whatsoever. Zero red text

**Comment by UltraNix** [comment]
Need some video about it :)

**Comment by djesic** [comment]
> Need some video about it :)

For now at least, unable to get a recording of it not being unusable.
However - I was able to use it 3 times in a row on different pets. This is a bug.
This https://cata-twinhead.twinstar.cz/?spell=55711 should be applied on the Hunter when it is used
This debuff duration should be affected by https://cata-twinhead.twinstar.cz/?spell=53264

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/72b60af8-0f56-4b4a-a2b9-4ed289d5fa79)
This debuff is applied on pet as the pet is the caster.

**Comment by djesic** [comment]
@UltraNix Failed in BG yesterday, but was not recording

**Comment by UltraNix** [comment]
Pitty.

**Comment by PanJanuszek** [comment]
No info provided to finish debug
