### ISSUE TITLE
[World Event] Pilgrim's Bounty - Achievement (Pilgrim's Paunch)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5092]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after gaining the spirit of sharing at some undercity table this gives no credit

**How to reproduce:**

go undercity, sit on any table and eat five times each food to gain the spirit of sharing buff and check the achiv

**How it should work:**

when u gain the spirit of sharing u should gain credit for completing this achiv too

**Database links:**

https://cata-twinhead.twinstar.cz/?achievement=3557

**Comment by Sylwania** [comment]
It works there https://prnt.sc/BaZ00In_pc3l

**Comment by frostwave942** [comment]
yes the only table that works i realized 2 days ago, thanks anyway.
