### ISSUE TITLE
[Quest] Hero's Call: Mount Hyjal (Alliance)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5093]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

this quest is not given by the board (stormwind city) so i cant start the stoty line in mount hyjal, the only quest i could do was "guardians of hyjal: call of the ancients" and i was also able to do the quests to help aviana. but i cant take more quests so im stuck there.

**How to reproduce:**

idk if its a "general bug" or it only happens to my hunter, the fact is that quest doesnt appear on the board.

**How it should work:**

i should be able to see that quest on the board to start the story line there, i need to unlock the molten front to pahse the zone and see the rares to tame and all.

**Database links:**

https://cata-twinhead.twinstar.cz/?quest=27726

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/c5694c40-609a-4f94-8885-a160ab021595)

It is something on your side only i think.

There is no pre-req sites. Only level 80 is required
