### ISSUE TITLE
BM talents 3dmg% increase doesn't Show up in raids after wipe!!

### ISSUE THREAD

**Issue by Orbitell** [gamefreedomgit/Maelstrom#5096]
BM talents 3dmg% increase doesn't Show up in raids after wipe!!

Most of the times after a Wipe(mostly wipes), mount or dismount, or pet and dismiss pet it bugs and the bonus dmg increase stops showing off and doesn't work. Tried multiple times, and different methods, with mounting and dismissing only solution is to re-enter the raid, and that's a problem and very time consuming if you get ress at the boss or you forgot to check for the buff if its there.

**Comment by Waroxx-QA** [comment]
That's normal, it doesn't stack with [Communion](http://cata-shoot.tauri.hu/?spell=31876) from Retribution Paladins and [Arcane Tactics](http://cata-shoot.tauri.hu/?spell=82930) from Arcane Mages. it counts one of them, depends on who get ressed first/last.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/4231cb83-304e-4051-8e3e-feb97ee11406)
