### ISSUE TITLE
Majordomo bar is full yet the DPS is the same as 0 stacks on concentration 

### ISSUE THREAD

**Issue by devvotion** [gamefreedomgit/Maelstrom#5097]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**
2 fights on majo and my rogue Imnotshort that does 40+k with the buff did only 24, same with everyone else in the raid. No one actually got the buff of damage and healing

**How it should work:**
we should get the buff

**Database links:**
IDK about database links, I can add a screenshot 
![WoWScrnShot_112523_181113](https://github.com/gamefreedomgit/Maelstrom/assets/143356148/fa807995-e19b-4953-a68f-b9245b2b09fc)

**Comment by devvotion** [comment]
![WoWScrnShot_112523_182034](https://github.com/gamefreedomgit/Maelstrom/assets/143356148/5ed64683-91f0-49a9-8abe-55373146c99f)
![WoWScrnShot_112523_182058](https://github.com/gamefreedomgit/Maelstrom/assets/143356148/4b8cbd43-85c7-4663-bda1-334ceaa25550)
![WoWScrnShot_112523_182512](https://github.com/gamefreedomgit/Maelstrom/assets/143356148/210c6151-aed2-48f0-ace7-c1b8ee711b9f)

**Comment by UltraNix** [comment]
Already fixed.
