### ISSUE TITLE
Ignore message is still not shown after you whisper someone who ignores you.

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5098]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When a player puts you in ignore it should be written in red letters " Renethadox is ignoring you " 

Currently it doesn't show anything and someone stated that it was fixed in the changelog a couple of days ago but its not.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Okay.
Druidd ignores Magik.
Druidd try to whisper Magik - it shows error "Magik is ignoring" and no message delivered to Magik.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/b67a2d54-a11f-4759-a38b-a35c597a3455)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f737696e-22bd-456a-bdf8-274f50ceabe1)


Now:
Magik try to whisper Druidd - still error shows: "Druidd is ignoring you" and no message delivered to Druidd.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/037788fd-7891-4ec0-9fd8-c4c4e9c6de37)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/475df470-bda5-484d-b970-9f65372149a1)

**Comment by Renehadox** [comment]
Developer, you misunderstood the bug.

You applied even a wrong fix " Fixed one error displayed when inviting players in instances/arenas.
Players cannot whisper to ignored players.
gamefreedomgit/Maelstrom#5075  "

Currently on whitemane if someone ignores you and you whisper him he will not get the message.

But the red message which you posted on your screenshots is not showing which may lead sometimes to confusion as you think he is afk or he is not reading your message while he is actually ignoring you.

**Comment by UltraNix** [comment]
@Renehadox What is wrong with you? I posted 4 screenshots and all with the error.

**Comment by UltraNix** [comment]
Post your screenshots from game it's not fixed yet.

**Comment by UltraNix** [comment]
You said that bug is still not fixed, even though I sent you screenshots from server that this is already fixed.
If not, then test it in game and post proof it's still not fixed.

**Comment by Renehadox** [comment]
![WoWScrnShot_112823_193259](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/9e59f797-27b8-4955-8190-625f28d8c8e2)

he ignores me but red message still not shown

**Comment by UltraNix** [comment]
According to database, Xasisis does not ignore you.

**Comment by Renehadox** [comment]
It was a temporary ignore.

**Comment by UltraNix** [comment]
@Renehadox Poke me on Discord.
