### ISSUE TITLE
Flags in BGs are not shown on map after they are taken, world war 1 bug

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5099]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

This bug here is since world war 1, enemy takes flag and its not shown on map.

Check it out:

![flagbug](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/8b366cea-5d92-409e-9c8c-39ed3423dcd8)

As you can see Alliance flag is taken and its not shown on the map we dont know where the enemy flag carrier moves.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Hermeleen** [comment]
#3788

**Comment by Hermeleen** [comment]
Why is this tagged as semi-confirmed? I mentioned the fix you did. If you "fix" this, you will bug it.

**Comment by bonfax4** [comment]
There should be a timer for twin peaks as well.
Retail video where the flag is picked around 2:30, priest opens map at 2:55 and no flag displayed on the map.
https://youtu.be/sIGIAp8PO4U?t=2m55s

**Comment by bonfax4** [comment]
https://youtu.be/Pp9kuPBgk-A?t=56s
This one is much better since he has the minimized map. Flagged picked @ 0:56 and displayed on the map around 1:43'ish.

**Comment by UltraNix** [comment]
Not a bug - flags are not visible immediately.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/828c8260-ebb3-480c-a8e9-0f78a46e71e7)
