### ISSUE TITLE
Strange Whitemane crazy bugs...

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5100]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

What happened was that yesterday i was doing End Time and we were at final boss but before we fight final boss our tank left and we requed again to find a tank, que popped and it put me in a new EoT with a new group but i had a 60 seconds timer that im gonna be ported out of dungeon as if i left the group by right clicking leave party on my character head.

![WoWScrnShot_112523_030144](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/910beafc-aeea-467a-bdd5-b867c2182d84)
![WoWScrnShot_112523_030155](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/fa11d47e-99f0-42e0-b88c-6163f458ca05)

As you can see on my dps meter that was my first group and then it put me with a new group, idk what happened but its a bug so it must be reported.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Renehadox Happened more than once?

**Comment by Renehadox** [comment]
> @Renehadox Happened more than once?

nope that was the first time only

**Comment by UltraNix** [comment]
Okay. If it happens again, let me know.
