### ISSUE TITLE
Mobs are in Tol Barad during fight which they shouldn't

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5101]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Currently when a Tol Barad fight is going on the mobs who are for the quests are currently in the battle which they shouldn't.

It wasn't like this before.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by frostwave942** [comment]
in addition, when tol barad battle ends and horde wins for eg, alliance npcs (quest givers and guards) are still in the center.

**Comment by UltraNix** [comment]
@frostwave942 
`in addition, when tol barad battle ends and horde wins for eg, alliance npcs (quest givers and guards) are still in the center.`
It's because of crossfaction.

**Comment by UltraNix** [comment]
No further info - closing.
