### ISSUE TITLE
multiple paladins in group

### ISSUE THREAD

**Issue by imblish** [gamefreedomgit/Maelstrom#5102]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when there are multiple paladins on group / hc 
seal of truth seems bugged it just doesnt register on boss
we get no mana from buff or dot

**How to reproduce:**
go on hc boss with 2 ret and 1 prot with seals
and see no procs on gesture or judgement of the bold procs
i was oom on 1 minute on single boss fight
and my dps was way lower than should be

**How it should work:**
each pala should have his own dot on boss and 
we should get the proc from judgement of the bold

**Database links:**

**Comment by Renehadox** [comment]
Thats the reason i oom in 20 seconds a ret in DS dungeons.

I can confirm this.

**Comment by imblish** [comment]
well the problem is that i cant see my debuff on the target when there multiple paladins on group
and recount / dps meter doesnt register any damage as dot from me
i ll provide a screen next time i go in-game and have this happen
i can surely say that i didnt get a proc from mana judgement when other paladins are present
anyway i ll provide image when it happens
