### ISSUE TITLE
Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by Solker455** [gamefreedomgit/Maelstrom#5105]
**Does not appear https://www.wowhead.com/npc=15077/riggle-bassbait during the event https://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza therefore, it is impossible to get an achievement https://www.wowhead.com/wotlk/achievement=306/master-angler-of-azeroth**

**Come to the Pirate Bay during the event and make sure that there is no https://www.wowhead.com/npc=15077/riggle-bassbait during the event https://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza**

**During the event https://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza must appear https://www.wowhead.com/npc=15077/riggle-bassbait and accept https://www.wowhead.com/item=19807/speckled-tastyfish in the amount of 40 pieces, if you bring it first, you get an achievement https://www.wowhead.com/wotlk/achievement=306/master-angler-of-azeroth**

**[Database links:](https://www.wowhead.com/npc=15077/riggle-bassbait)**

**Comment by Solker455** [comment]
It's been 2 months, and it hasn't been fixed...

**Comment by PanJanuszek** [comment]
fixed  after update
