### ISSUE TITLE
warlock talent [Jinx]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5106]
sometimes when i face lock i get "jinx" debuff even after arena ends and it's giving a wrong debuff "+10% increase focus on all abilities" i'm a hunter.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/129106504/b5312f0a-ee90-407a-8f22-a7b781dc540d)

**Comment by mipanka** [comment]
u have curse, after debuff will end, this debuff end too

**Comment by mipanka** [comment]
if someone know, this debuff should stack or no.
curse +8% dmg and curse -10% dmg+ability rune/enerfy/focus cost

**Comment by Pornoodemon** [comment]
> если кто-то знает, этот дебафф должен стакаться или нет. проклятие +8% урона и проклятие -10% урона+стоимость руны способностей/энергии/фокусировки

на сколько мне известно то он не стакаеться только с проклятием стихий.

**Comment by Sketish** [comment]
Not a bug
