### ISSUE TITLE
waist 378

### ISSUE THREAD

**Issue by lYlahdi** [gamefreedomgit/Maelstrom#5107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
How to change waist 378 to 391
It is not available in the shop

![Screenshot (8)](https://github.com/gamefreedomgit/Maelstrom/assets/112273567/3980d6d6-500f-46a7-a1a4-159b1cdd0928)

![Screenshot (9)](https://github.com/gamefreedomgit/Maelstrom/assets/112273567/8f9947c6-990e-4fe2-9fbb-c05cd4df68e1)

Whitemane Server

**Comment by Revly** [comment]
exist in Database but

https://www.wowhead.com/es/item=71396 (Heroic) no avalible

**Comment by Sketish** [comment]
there is no hc version available, not a bug
