### ISSUE TITLE
 [Concussive Shot]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5108]
[Concussive Shot] slow is bugged, it always reduce enemy's movement speed to 50%.

how it should work: it should reduce the enemy's movement speed by 50%

example: if feral is running  at 150% speed, concusive shot should get him to 75% speed. Atm it's 50% speed.
even if feral uses [Dash] at 195% he's still slowed at 50% speed instead of 97% speed.

https://prnt.sc/mwmVzfJnseZJ

https://prnt.sc/yALcIbSRTOVt

**Comment by UltraNix** [comment]
Fixed.
