### ISSUE TITLE
Monkey pet [Bad manner] with [Bullheaded]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5110]
when i use  [Bullheaded] which is the  pet trinket, i can still cast [bad manner] mid GCD. 

https://github.com/gamefreedomgit/Maelstrom/assets/129106504/9d3e9371-b3eb-492b-905f-47a8849a2db3

**Comment by UltraNix** [comment]
@jimmyiwnl Too big change to be made without proofs.
Bad Manner trigger no gcd, while Bullheaded does it - but without any category (kinda weird). We need some video from retail to see if it's blizzlike.

**Comment by bonfax4** [comment]
Hmm bullheaded is shown to trigger no gcd on old cata wowhead but it does trigger a CD on pet special abils ( didn't trigger for basic attacks ) on videos. Thing is this could also be a visual bug on retail so I can't tell 100%. 



https://web.archive.org/web/20120703075318/http://www.wowhead.com/spell%3D53490

https://web.archive.org/web/20120626050230/wowhead.com/spell=90337

This is a stretch but the best I can find but he did try to cast the pet special ability  ( interrupt ) here when he triggered bullheaded gcd and it didn't go through until the gcd was over on 2nd press ( or he queued it  ? No idea if pet abils even queue ) slow down the video to 0.25 https://youtu.be/LBTHVZP3CJA?t=1m12s.

**Comment by UltraNix** [comment]
Fixed.
