### ISSUE TITLE
Gurthalak  voice of the deeps

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5111]
**Description:**
Tentacles that are summoned from procv should hit 100% hit chance, currently they are missing sometimes
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/8a0295c8-c501-4623-a50b-c0f3d06e4af1)

**Database links:**
https://www.wowhead.com/item=77191/gurthalak-voice-of-the-deeps

**Comment by bonfax4** [comment]
@UltraNix actually no. It scaled with spell hit and there are reports of warrior missing on bosses while hit capped. 

https://www.mmo-champion.com/threads/1040084-Gurthalak-questions?p=14582206&&viewfull=1#post14582206

**Comment by bonfax4** [comment]
Might as well check everything while looking into this.

-  150% crit bonus that scales with meta gem to 154. 5. Does not scale with owner crit bonus

- Scales with spell crit chance

 -  Increased by dmg modifier auras.

> Also weapon-based attacks not considered to come from Gurthalak will -not- proc it. This is from a sample size of 633 slams from the main hand and the only source of rage was battle shout and berserker rage, absolutely no autoattacks at all. I had gurthalak in my offhand and a garbage green in the mainhand. There were -zero- procs. HOWEVER, if you are attacking with a non-weapon-based melee attack, such as Bloodthirst, then it -CAN- proc, regardless of what hand the weapon is in as long as it is equipped.

**Comment by Sketish** [comment]
https://www.youtube.com/watch?v=XyMv-DSqnbc&ab_channel=Nahoris

Still minor issues with tentacles stoping casts, dmg % modifiers are working

**Comment by UltraNix** [comment]
Fixed.
