### ISSUE TITLE
Quest "Stranglethorn Fever" does not work

### ISSUE THREAD

**Issue by TheCeaptain** [gamefreedomgit/Maelstrom#5113]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You need to give the NPC "Witch Doctor Unbagwa" a "Gorilla Fang" to continue the quest but after giving him the item the quest does not proceed.

**How to reproduce:**
just have the quest "Stranglethorn Fever" running, go the the Witch doctor NPC with the gorilla fang in inventory and click continue.

**How it should work:**
After clicking continue the quest should continue with you fighting 3 enemies with the final one dropping the item the one you need for the quest

**Database links:**
https://www.wowhead.com/quest=26597/stranglethorn-fever

**Comment by UltraNix** [comment]
#2722
