### ISSUE TITLE
hunter spell [Feign Death]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5114]
looks like [Feign death] Also removing combat for enemy when i'm using it, that's so broken, it should only remove combat for myself.
rogue and ferals  abusing it the most by having free restealths

Uploading Desktop 2023.11.27 - 13.53.44.25.mp4…

https://github.com/gamefreedomgit/Maelstrom/assets/129106504/ba58305a-6e5c-44f1-ac94-f7f25429275c

**Comment by jimmyiwnl** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/129106504/b71007f1-7821-4b62-b9d9-2473164be0d9

**Comment by jimmyiwnl** [comment]
Vanish already remove combat only for rogue 🤡

**Comment by Renehadox** [comment]
proofs from retail?

**Comment by UltraNix** [comment]
Fixed.
