### ISSUE TITLE
[Bad manner] vs rogue's [smoke bomb]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5118]
Whenever i use [Bad manner],  if rogue smoke bomb while pet is running towards him. the monkey will run inside the smoke bomb and still bad manner the rogue. which is working perfectly as shown in the video Below

https://github.com/gamefreedomgit/Maelstrom/assets/129106504/1cd836cc-b6e5-4c76-bba5-930b41ca16f8

The issue is when  the rogue Smoke bomb first and then i use [Bad manner] my pet will sit afk and not run inside smoke bomb to bad manner the rogue. it should still work cz Smoke bomb act as a pillar it puts the rogue out of Line of Sight of the hunter, so pet should chase him inside of it just like it's chase him around a pillar. which is not the case as shown in this video.

https://github.com/gamefreedomgit/Maelstrom/assets/129106504/0d38436a-d8c6-4cdc-856d-ffc2845b1f62

**Comment by UltraNix** [comment]
@jimmyiwnl So pet should ignore Bad Smoke?

**Comment by jimmyiwnl** [comment]
i never said it should ignore smoke bomb, i said the pet should run inside the smoke bomb and still cast bad manner, cz smoke bomb act as a pillar.
should pet ignore the pillar ? ofc not but it should still chase the eneny arround it. so in the smoke bomb case it should run inside of it and still cast bad manner.
if pet is already in smoke bomb then it should simply cast bad manner which is working atm. but when it's out of smoke bomb pet should move inside of it and cast bad manner not stand afk

**Comment by Renehadox** [comment]
Why whenever a hunter bug is reported its always marked as high? Oo

**Comment by UltraNix** [comment]
Should be already fixed.
