### ISSUE TITLE
Stratholme Dungeon doesn't work

### ISSUE THREAD

**Issue by Gremadx** [gamefreedomgit/Maelstrom#5119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
To get the achievement "Glory to the Hero", you need to get two achievements from Stratholme, namely "Time is running out" and "Zombie Day". The key point is that there is no way to proceed with their implementation due to the lack of efficiency of the quest "Dispelled illusions", it simply does not count the boxes we need. It turns out that the dungeon is not operational at its very first stages.

**How to reproduce:**

**How it should work:**
When Chromie gives us a task to dispel illusions, we are given a special device, it removes these very charms, thereby counting the box we need, the same 1 out of 5

**Database links:**
https://www.wowhead.com/quest=13149/dispelling-illusions

**Comment by Gremadx** [comment]
> **Description:** To get the achievement "Glory to the Hero", you need to get two achievements from Stratholme, namely "Time is running out" and "Zombie Day". The key point is that there is no way to proceed with their implementation due to the lack of efficiency of the quest "Dispelled illusions", it simply does not count the boxes we need. It turns out that the dungeon is not operational at its very first stages. This is specifically for version 4.3.4 WOW cataclysm from Whitemane
> 
> **How to reproduce:**
> 
> **How it should work:** When Chromie gives us a task to dispel illusions, we are given a special device, it removes these very charms, thereby counting the box we need, the same 1 out of 5
> 
> **Database links:** https://www.wowhead.com/quest=13149/dispelling-illusions

**Comment by Afgann** [comment]
fixed
