### ISSUE TITLE
The food from the pilgrim event is not granting regeneration.

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5122]
Description:

As the title says, the food is not granting mana and health regeneration, during the event, it only grants the benefit when 10 seconds pass after having eaten.

And the feast doesn't work for eating either.

![WoWScrnShot_112723_200146](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/9203774f-bbf3-4bd8-844f-9dc69d0551f3)
![WoWScrnShot_112723_200134](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/84a4617e-9d6d-45a7-a92e-c2a9df6482b7)
![WoWScrnShot_112723_195540](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/60bcdc67-2e75-4f77-a6d1-cac129a023fc)
![WoWScrnShot_112723_195538](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/a1967f44-b437-46d4-a13a-b773b5409424)
![WoWScrnShot_112723_195522](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/350639ba-1a78-415f-8f92-a369dd866230)
![WoWScrnShot_112723_195508](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/21f35f2e-ae5f-408c-a7f9-ecf9719ab480)
![WoWScrnShot_112723_195446](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/bea7ea81-bb78-48e8-b226-8683913d6191)
![WoWScrnShot_112723_195411](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/450f67ec-f6bc-443c-a1a6-777199851eb3)

**How to reproduce:**
During the event, if you eat one of these meals, you currently do not regenerate 4% mana and health

**How it should work:**
During the event, if you eat one of these foods it says it grants 4% mana and health **regeneration**

And to reaffirm the regeneration of mana and life I give an example

![WoWScrnShot_112723_202012](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/ec5e4876-a660-443c-a83e-cdd2edf49f05)
![imagen_2023-11-27_203025867](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/2fdf1511-c8ba-4e17-b53f-64fa7805204d)

**Database links:**
https://www.wowhead.com/item=46887/bountiful-feast

https://www.wowhead.com/item=44836/pumpkin-pie
https://www.wowhead.com/item=44837/spice-bread-stuffing
https://www.wowhead.com/item=44838/slow-roasted-turkey
https://www.wowhead.com/item=44839/candied-sweet-potato
https://www.wowhead.com/item=44840/cranberry-chutney

**Comment by UltraNix** [comment]
Fixed.
