### ISSUE TITLE
The quests I've had troubles with

### ISSUE THREAD

**Issue by Avraolf** [gamefreedomgit/Maelstrom#5123]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
[//]: # (**Description:**)
[//]: # (**How to reproduce:**)
[//]: # (**How it should work:**)
[//]: # (**Database links:**)

[In Defense of Krom'gar Fortress](https://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress)
**Description**
The quest seems impossible to complete as the [Gnomish Bombers](https://www.wowhead.com/npc=42015/gnomish-bomber) spawn to high above the character. The cannon cannot reach them and shoot them. [Gnomish Flying Machine](https://www.wowhead.com/npc=42016/gnomish-flying-machine) don't spawn at all.

**How to reproduce**
* complete [Spare Parts Up In Here!](https://www.wowhead.com/quest=26048/spare-parts-up-in-here) from [Sergeant Dorntag](https://cata-twinhead.twinstar.cz/?npc=41991);
* Take the quest form [Chief Blastgineer Bombgutz](https://www.wowhead.com/npc=40902/chief-blastgineer-bombgutz);

**How it should work**
Shown it [this](https://www.youtube.com/watch?v=JE8xTVZa90Y) video
**Database links added above**

[Proof of lies](https://www.wowhead.com/quest=26097/proof-of-lies)
**Description**
It seems that after completion of this quest [General Grebo](https://www.wowhead.com/npc=42050/general-grebo#ends) duplicates.

**How to reproduce**
* Complete [To Battlescar!](https://www.wowhead.com/quest=26082/to-battlescar) quest from [General Grebo](https://www.wowhead.com/npc=42050/general-grebo#ends);
* Take [Proof of Lies](https://www.wowhead.com/quest=26097/proof-of-lies) from [High Chieftain Cliffwalker](https://www.wowhead.com/npc=42039/high-chieftain-cliffwalker);

**How it should work**
[General Grebo](https://www.wowhead.com/npc=42050/general-grebo#ends) should not duplicate.
**Database links added above**

[Is This Justice?](https://www.wowhead.com/quest=26099/is-this-justice)
**Description**
[General Grebo](https://www.wowhead.com/npc=42050/general-grebo#ends) duplicates at some point before this quest and don't become hostile during quest. After killing his bodyguards [High Chieftain Cliffwalker](https://www.wowhead.com/npc=42039/high-chieftain-cliffwalker) and [Masha Cliffwalker](https://www.wowhead.com/npc=42047/masha-cliffwalker) starts to infinetly loose health, die, respawn and die again. The quest is impossible to complete and be hand it to Masha.

**How to reproduce**
* Complete [To Battlescar!](https://www.wowhead.com/quest=26082/to-battlescar) from [General Grebo](https://www.wowhead.com/npc=42050/general-grebo#ends);
* Complete [Proof of lies](https://www.wowhead.com/quest=26097/proof-of-lies) from [High Chieftain Cliffwalker](https://www.wowhead.com/npc=42039/high-chieftain-cliffwalker);
* Take [Is This Justice?](https://www.wowhead.com/quest=26099/is-this-justice) from [High Chieftain Cliffwalker](https://www.wowhead.com/npc=42039/high-chieftain-cliffwalker);

**How it should work**
Shown in [this](https://www.youtube.com/watch?v=MxL6n-v8eiY) video
**Database links added above**

[Early adoption](https://www.wowhead.com/quest=14246/early-adoption)
**Description**
There are no nests in which I should put the eggs/

**How to reproduce**
* Take the quest from Cenarion [Embassador Thunk](https://www.wowhead.com/npc=35661/cenarion-embassador-thunk)

**How it should work**
Shown in [this](https://www.youtube.com/watch?v=YXCtEdUOEv0) video
**Database links added above**

**Comment by PanJanuszek** [comment]
Stonetalon Mountains fixes have these included
