### ISSUE TITLE
Priest dispell against against fear (and probably other magic CC debufs)

### ISSUE THREAD

**Issue by Sallyasylum** [gamefreedomgit/Maelstrom#5124]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dispell magic (at least for shadow) doesnt work on priest AOE fear when used to dispell friendly target altho its magic debuff
Was in the BG(so raid party) and receiver was natural ally (not faction balance thing) he got feared few times, everytime i couldnt dispell it ( and not that it dispelled smth else its just didint cast it without error thingy notification) it could be also related to dispell magic glyph (restores 3 percent max hp if succesfully dispelled smth) havent tried it without it
**How to reproduce:**
Raid group
glyph dispell magic
use dispell on teamate affected by phy scream

**How it should work:**
it should dispell it if i recall correctly(could be mixing up expansions) but as an official note there there no changes from wotlk to cata in thius particular case :)

**Database links:**
https://www.mmo-champion.com/threads/706936-Cataclysm-Dispel-Mechanics

**Comment by UltraNix** [comment]
Just tested and cannot reproduce it with psychic scream and glyphed Dispel Magic (and with Absolution talent).
@Sallyasylum Any screenshots with combat log on it or video about it? Happened only once (this one bg)?

**Comment by Hermeleen** [comment]
Don't forget that shadow priest can't dispel magic on friendly targets, only with mass dispel he can.

**Comment by djesic** [comment]
In Cataclysm, only healing specs have access to dispelling magic from friendly targets.
The one notable exception to this is Mass Dispel, which will remove magic debuff from friendlies even as a shadow priest

Check the Absolution passive in spec summary for discipline and holy.
So all priest specs have access to Dispel Magic that will purge hostile targets, but only healing priests can remove magic from friends.

**Comment by UltraNix** [comment]
So there is no bug here?

**Comment by djesic** [comment]
I think it might be an invalid report, @Sallyasylum please follow up if this report was for shadow priest casting dispel magic on friendly and not dispelling magic

**Comment by SimonBpvp** [comment]
No bug here, SP can’t cast dispel magic on friends in cata.
