### ISSUE TITLE
Whitemane crazy bugs 2

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5125]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I qued for RDF hc and in the meantime i invited a player in a group.

After that, que popped i accepted it and i left party it marked me as i didn't accept the que and  i got removed.

The fack ?

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
If you join group during queue it should break queue for dungs

**Comment by djesic** [comment]
> > If you join group during queue it should break queue for dungs
> 
> You are not reading what i type.
> 
> I qued then i invited a player, que popped after 2 minutes i clicked accept and when i left party with the guy i was in it kicked me out, how is that possible where i got que first and i did click accept? :D

You are not reading what he wrote either.
The issue is that you should have been removed from the dungeon queue when another player joined your party.

**Comment by Renehadox** [comment]
I don't know, how is it supposed to work properly then?

**Comment by UltraNix** [comment]
Fixed.
