### ISSUE TITLE
Silencing Shot

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#5127]
silence must be applied when the projectile reaches the target https://www.wowhead.com/wotlk/spell=34490/silencing-shot
https://youtu.be/6U4zveFkK7A?t=529

**Comment by djesic** [comment]
Nice report!
I want to mention that there is the same issue currently affecting protection paladin's Avenger's Shield.
In case the same fix can easily be applied there as well

**Comment by Afgann** [comment]
fixed
