### ISSUE TITLE
Whitemane+ transmog bug

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5129]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I transmog a mace into a sword after 3 seconds oriiginal look to the weapon is shown.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
so what is a bug ?

**Comment by Renehadox** [comment]
> so what is a bug ?

the transmog weapon original look is going back after 3-4 seconds.

**Comment by UltraNix** [comment]
@Renehadox What weapons are we talking about here? Can you show us some screenshots?
