### ISSUE TITLE
problem with archeology.

### ISSUE THREAD

**Issue by PawiiH** [gamefreedomgit/Maelstrom#5130]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i have an issue with archeology.

i have 27/32 needed troll fragments, and i have two troll tablets i should be able to use to finish the troll artifact.

but the problem is, when i go under the troll artifacts interface, the "icon" where i drag the tablet to is just gone, it's not there.

it is however there on the other artifacts interface, so i have no way to use my troll tablets.

**How to reproduce:**
im not sure why or even how it happened in the first place.

**How it should work:**
i should have an icon where i can drag the tablet into, under the troll artifacts interface.

**Database links:**
![archeology](https://github.com/gamefreedomgit/Maelstrom/assets/152497901/d73c9a8b-fb3c-4520-bb60-b6d4d68947e0)

**Comment by frostwave942** [comment]
some artifacts hav keystone sockets and others dont, thats how the prof works. for eg that <a href="https://www.wowhead.com/item=63118/lizard-foot-charm">artifact</a> doesnt hav keystone sockets.

**Comment by PawiiH** [comment]
i am so sorry for having made this an issue, i tried to finish the artifact.
and it did change so i could again.
i blame my own stupidty haha :)

sorry!
