### ISSUE TITLE
Bloodsail's End unable to progress due to non working part

### ISSUE THREAD

**Issue by TheCeaptain** [gamefreedomgit/Maelstrom#5135]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After accepting the quest you then need to go to Kebok who is right next to Horde FM, when you interact with Kebok and option appears that says "Yes - I need another wind rider", when you click it, it does the animation for mounting the wind rider but nothing else happens, there is no wind rider and you cant progress the quest.

**How to reproduce:**
accept the quest "Bloodsail's End" and go to Kebok, interact with him and click the action/prompt

**How it should work:**
After clicking on the action/prompt you should get onto a wind rider and fly over to "Fleet Master Firallon"s ship

**Database links:**
wowhead: https://www.wowhead.com/quest=26703/bloodsails-end#screenshots

**Comment by frostwave942** [comment]
u can use ur own flying mount to reach the ship and kill their leader.

**Comment by TheCeaptain** [comment]
> u can use ur own flying mount to reach the ship and kill their leader.

yes but i did this quest with my lvl 35 char.

**Comment by Afgann** [comment]
fixed
