### ISSUE TITLE
Hour of Twilight. Archibishop fight

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#5136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
during th fight, while boss casts holy wave, thrall casts water shield. if boss reaches 60% of hp twilight phase starts and shield disapear, causing holy wave killing characters.

**How to reproduce:**

**How it should work:**
im not sure, but i guess either shield shouldn't disappear or holy wave should be stopped

**Database links:**

**Comment by frostwave942** [comment]
i think that's how the fight should work: https://www.youtube.com/watch?v=szPnpSS5VRc
and i think everyone has noticed that the light/dark orbs areas are kinda big and hard to avoid.

**Comment by ETatskyi** [comment]
> i think that's how the fight should work: https://www.youtube.com/watch?v=szPnpSS5VRc and i think everyone has noticed that the light/dark orbs areas are kinda big and hard to avoid.

This video prouve nothing. Bulb disappear on 61% of HP when wave is gone
On WM we have situation when wave just started, boss became to 60%, bulb disappear and wave smash everyone.

**Comment by JK2M** [comment]
https://www.youtube.com/watch?v=LaVB2YxEXY0
Atleast on PTR Retail hes right, Bubble should not disappear

**Comment by UltraNix** [comment]
Fixed.
