### ISSUE TITLE
Random Hour of Twilight

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#5137]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Random Hour of Twilight is unable to que. After clicking button it perform the message "u dont meet requirements". Its broken both on PTR and live. Que to specific dungeons works fine.

**How to reproduce:**
Just try to que to Random Hour of Twilight. 

**How it should work:**
Should be able to que as like to Random Heroic with same rewards.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/63796901/04b1f1c5-01f1-4fa2-ba4f-0ccb10c27732)

**Comment by UltraNix** [comment]
Fixed.
