### ISSUE TITLE
Worgen Two Forms Racial Ability

### ISSUE THREAD

**Issue by Taroongaming** [gamefreedomgit/Maelstrom#5138]
**Description:**
Started on a worgen and got through the quest until I turn into worgen but I do not have the racial ability Two Forms so now I am stuck as a worgen and can't go back to human form.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/152660045/292ef385-da6b-459f-9d30-552786744a68)

**How to reproduce:**

I had the racial ability Darkflight at level 1 and used it which turned me into a worgen before I was meant to and I believe that is what caused the bug. To reproduce it, I suppose, use the Darkflight ability at level one and see if Two Forms becomes available later.

**How it should work:**
I should have the ability in my spellbook and turn back into human when using it.

**Database links:**

**Comment by KevlinTallfellow** [comment]
I'm not sure if, on Whitemane's server, you're supposed to automatically have the Two Forms ability, but I can confirm that if you use the racial speed boost you can transform into a worgen before the story is ready for you to be a worgen, and so you can't change back until you complete all of the quests in the Gilneas line up to the point where you're captured and given a cure.  At this point, you will receive the Two Forms ability as a quest reward, allowing you to change back and forth.

**Comment by UltraNix** [comment]
Fixed.
