### ISSUE TITLE
To Legion Hold

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5140]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The first time I used the box, it turned me into an imp, not a crate.  Subsequent uses of the box turned me into a box, but I could move when I should not have been able to.  Logging out and back in, the first use of the box again turned me into an imp.  Sometimes it will turn you into an imp instead of a box without logging out.  Usually, using the disguise item near the communication device will not spawn the NPC and start the event conversation without moving closer to the communication device while disguised.  After hearing the entire conversation between the NPC and the communication device, the NPC walks away and will despawn if not attacked, but the objective "Discover Legion's Plans" does not complete.

**How to reproduce:**
Obtain quest at Wildhammer Stronghold from Wing Commander Nuainn.  Go to quest location.  Use disguise item near the communication device.

**How it should work:**
https://www.wowhead.com/wotlk/quest=10563/to-legion-hold

**Database links:**
https://www.wowhead.com/wotlk/quest=10563/to-legion-hold

**Comment by KevlinTallfellow** [comment]
Strangely enough, even though the quest journal never showed the objective complete, and the quest tracker never showed the objective complete, and there was never a pop-up message showing the objective complete, I was able to continue the quest when I got back to the stronghold and spoke to the NPC.

**Comment by KevlinTallfellow** [comment]
Just had a similar issue with a subsequent quest, "Blast the Infernals!" https://www.wowhead.com/wotlk/quest=10564/blast-the-infernals

I went to the quest location, used the quest item, and it appeared to work as all of the infernals died, but the quest tracker, quest journal, and pop-up messages never showed the objective as complete.  Also, like before, the quest NPC at the quest hub showed on the mini-map with a "?" indicating completion, but did not show on the zone map indicating completion, and when speaking to him, the quest option had a grey "?" indication the quest objectives were not complete, but I was able to click the "COMPLETE" button anyway to proceed with the quest.

**Comment by PanJanuszek** [comment]
After restart
