### ISSUE TITLE
It's about Protection Warrior Block Rate Breaking Bad

### ISSUE THREAD

**Issue by spiritualmotor** [gamefreedomgit/Maelstrom#5141]
Warrior critical block rate
First thing first i play warrior as a tank because interested on high block value and high hp playstyle also unlimited taunt as tank or offtank
here is problem screenshoot
![WoWScrnShot_120223_133049](https://github.com/gamefreedomgit/Maelstrom/assets/152680458/25075f07-9dc2-4e14-aabe-015b81e69bfa)
Warrior have 31% block rate chance and 31 % critical block(100% damage block on cata, idk) it written wrong on character stat window, and it looks like did not function well. 
![WoWScrnShot_120223_133241](https://github.com/gamefreedomgit/Maelstrom/assets/152680458/2d924967-e777-4519-a537-cf0b942a971f)
![WoWScrnShot_120223_133248](https://github.com/gamefreedomgit/Maelstrom/assets/152680458/c775a712-46f4-4516-a3c5-a6bea51e3282)
rate so tiny on 22 mastery, i know it divided by critical block, but i confuse. 31% block, 31% critical block, where is my 20%?
and the reduction was, weird. i tank Murozond(i didn't have screenshot) on 37k armor and 70% shield block rate( on stats and shield spell) he one shot me lol, it was normal 100k damage !!! not temporal blast damage !!
and it's rare to block, even on smaller monster.
Hopefully i can still play warrior, maybe screaming with slowing shout https://cata-twinhead.twinstar.cz/?spell=58372 and kite all entire mobs on dungeon, but on boss monster, i feel like a blue gear paladin.
and on paladin i find it pretty over power, and blood dk too. they have healing traits, huge armor was like 40k, and also overheal that makes dk and ppala having bubbles beyond stupid 200k.
i hope protection warrior can be fixed. i cannot play it like dark soul with meme on beyond reason difficulty.with all that superior sting feed on world chat everyday by high kings.
if this not broken, maybe i'm the one who should realize i was nothing just a small dust in air that exhale by someone bonsai, thanks
p.s i never cheat

**Comment by UltraNix** [comment]
There is nothing missing here. You already see your total block rate: 51.57. That means you have 51,57% chance to block damage.
That 31% you see tells about how much of damage is blocked.
Mastery increases your block chance, not block damage reduction.
