### ISSUE TITLE
Kalu'ak daily quests: Howling Fjord broken

### ISSUE THREAD

**Issue by massimo1980** [gamefreedomgit/Maelstrom#5145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://www.wowhead.com/wotlk/item=40946/anuniaqs-net
https://www.wowhead.com/npc=23804/orfus-of-kamagua

**Description:**
Kalu'ak reputation: Once finished the "internal" quests you have to do the "daily quests" to complete the reputation.
The daily quests are divided by 3 zones: Borean Tundra, Dragonblight and Howling Fjord.
The quests in Howling Fjord are not assignable. You can talk with the NPCs but can't take any quests.
Actually i've found this issue on 2 NPCs: Anuniaq ( that should give a daily called "The way to his heart" ) and Lunk-tusk ( that should gives you the "internal" quests, starting with one called "Orfus of Kamarga" )

**How to reproduce:**
Just talk with the NPCs :)

**How it should work:**
The NPC should gives you a quest

**Database links:**
https://www.wowhead.com/quest=11472/the-way-to-his-heart
https://www.wowhead.com/quest=11573/orfus-of-kamagua

**Comment by PanJanuszek** [comment]
Works as intended. You have to to pre-requestsite quests (https://www.wowhead.com/?quest=11509  and  https://www.wowhead.com/?quest=11469)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/66ddec89-59f7-470c-94a2-30cc303ece6e)

**Comment by MrTide** [comment]
@PanJanuszek i think the problem is https://cata-twinhead.twinstar.cz/?quest=11504 because its not available for them

**Comment by massimo1980** [comment]
As @MrTide said: after complete The Dead Rise, Street "Cred"and Swabbin' Soap now i'm able to take the daily quest:

![image](https://github.com/gamefreedomgit/Maelstrom/assets/4678483/f4397324-962c-423e-a9a8-77c462abe378)

Thank a lot Tide!!
