### ISSUE TITLE
Kaluak Fishing Tournamet doesnt work

### ISSUE THREAD

**Issue by drax1233** [gamefreedomgit/Maelstrom#5146]
After i send a ticket to a GM , i have been told to write the issue here.
Can you please try fix this tournament in Dalaran?

How it should work:
The Kalu'ak Fishing Derby is similar to the Stranglethorn Fishing Extravaganza, running on Saturdays at 2:00 PM to 3:00 PM server time in Northrend. There is no level requirement, but you must be able to visit Daralan, since this is where you have to turn in the goal fish.
Thank you !

**Comment by Sketish** [comment]
Provide more details how event should work

**Comment by mrsanten** [comment]
Similar to #5104 and we will follow all Kaluak related issues there.
