### ISSUE TITLE
Aquamarine Pendant of the Warrior "use" buff doesn't persist across Druid form change

### ISSUE THREAD

**Issue by Packets-n-Python** [gamefreedomgit/Maelstrom#5148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The stamina "use" buff of Aquamarine Pendant of the Warrior is deactivated when switching forms as a Druid

**How to reproduce:**
Use Aquamarine Pendant of the Warrior, buff appears in list, then buff disappears when going from normal form to bear/cat/aqua/travel forms

**How it should work:**
Aquamarine Pendant "use" buff should remain active across form changes.

**Database links:**

**Comment by Afgann** [comment]
fixed
