### ISSUE TITLE
Creatures: class warrior, rage power displayed

### ISSUE THREAD

**Issue by Sungis18** [gamefreedomgit/Maelstrom#5149]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
All class warrior creatures have rage displayed.

**How to reproduce:**
See all class warrior creatures ingame.

**How it should work:**
The rage should not be displayed (unless wanted).

**Database links:**

**Screenshot:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/05e22d58-f921-4486-93c7-eed059c6fda9)

**Comment by Sungis18** [comment]
So here's a video where you can see there's no rage displayed on these creatures :
https://youtu.be/NOB7i37no8U

Here's what we can see in Whitemane, on Captain Peake:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/a1d00e8c-1dac-4ecb-a485-2efa0a3f43e6)

And the warden right next to him:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/ce938593-5d31-46c0-a540-cf5aa5fb9f42)

I'm a software developper who've worked on MaNGOS & TrinityCore frameworks since 2010. This rage bug was introduced with the rework of the power system introduced in Cataclysm.

Rage is only displayed when intended, by default, it is not.

You can see more proofs comparing any class warrior creature in Whitemane with any class warrior creature in +12-13 years cataclysm videos.

**Comment by Sungis18** [comment]
Hi, fyi, it seems that the attempting fix didn't do the job:

There're some creature with 0/1000 (rage I guess?):
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/c7d175d9-851f-4522-97d2-fcdb7d1e71ba)

And some other with 0/100 just as in the beginning:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/daa4ba44-526f-48d9-95e8-45decc05b2c2)

**Comment by UltraNix** [comment]
Fixed.

**Comment by Sungis18** [comment]
Hello, it seems that there's still some creatures with rage displayed :

![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/54c1125d-dc82-4b4d-9827-95490307b024)

**Comment by UltraNix** [comment]
Yes it is.

**Comment by Sungis18** [comment]
Alright, here is a list of vehicle powers mapped with they "real" power :
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/986c129bc0d7db60f56e094d1eef55970c1e92d8/src/server/game/Entities/Vehicle/Vehicle.cpp#L77

According to this list, I think there's no CLASS_WARRIOR vehicle displaying rage power. Checking Vehicle.dbc can also help to find it out.
