### ISSUE TITLE
Orgrimmar: grunt OOC enraged

### ISSUE THREAD

**Issue by Sungis18** [gamefreedomgit/Maelstrom#5153]
**Description:**
It seems that Orgrimmar grunts are enraged for no appearant reason out of combat.

**How to reproduce:**
Go to Orgrimmar, watch grunts.

**How it should work:**
When OOC the grunts should not be enraged.

**Screenshot:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/4041328/c60a122c-bb3c-4359-9178-e6bc4c2a6c69)

**Comment by KevlinTallfellow** [comment]
I've noticed this a lot too.  It's kind of silly.

On the other hand, they're orc grunts.  They live for battle.  Maybe all the strolling around *not* fighting is what's making them pissed all the time?

**Comment by PanJanuszek** [comment]
Only on server start
