### ISSUE TITLE
Guardian of Ancient Kings doing ridiculously low amount of damage

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5159]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Guardian of Ancient Kings is bugged, i noticed yesterday that i am hitting for 1800 on a dummy while this guy doing 5k guardian hits on a dummy with lower gear.
**How to reproduce:**
![WoWScrnShot_120523_023025](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/1bb96009-eec8-4616-8adc-916fd7b69ff5)
![WoWScrnShot_120523_022409](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7425372e-221b-4f8b-bb8e-cfb06989ca68)

1937 with full pve gear, with heroic weapon and fully buffed plus scroll of strength ?

**How it should work:**

https://www.youtube.com/watch?v=6cu2zWwM17o&t=552s&ab_channel=LoppyMaus - 10:52 guardian starts attacking dummy.

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=86698

**Comment by Renehadox** [comment]
Edit:

The guy in the video is pvp geared i am full pve 0 resil still doing 3x lower his damage with Guardian.

**Comment by SimonBpvp** [comment]
> Edit:
> 
> The guy in the video is pvp geared i am full pve 0 resil still doing 3x lower his damage with Guardian.

It’s 2x lower not 3x. But aside from that the report looks good enough to me.
