### ISSUE TITLE
Justice trade vendor bug in Stormwind City

### ISSUE THREAD

**Issue by anilceyhanyeni** [gamefreedomgit/Maelstrom#5160]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Justice trade vendor returning 250 Honor for 375 Honor instead of justice points

**How to reproduce:**
Interact with Talric Forthright <Justice Trade Goods> in Stormwind City Command Center and try to buy 250 Justice Points for 375 Honor points that you have

**How it should work:**
NPC should be returning 250 Justice Points for 375 Honor Points 

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/47708346/150f1874-07f2-4124-9163-2a5c740f538c)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/47708346/72148cfb-a5c0-4a30-857d-34cc8882fdc9)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/47708346/e16859b3-542d-42f8-83f7-b40bde9136c9)

like this NPC but in reverse

**Comment by Shadowdkj** [comment]
I lost 875 Honor, by trading 5 times. Nick Elthyr

**Comment by Shadowdkj** [comment]
yoo, it's reversed now. We still can't buy Justice Points for Honor Points
