### ISSUE TITLE
Electro-shock goodness!

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5164]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

You use the quest item to give your character a buff, that gives a chance for your attacks to proc on the slimes to make them split into much smaller slimes called globules, which you then kill off for quest credit.  The problem is, these globules that spawn have like 9300 health, far more than all of the other mobs in the area which have around 6700, when they're supposed to only have around 600 health.  They seem to be spawning as regular mobs, with regular health, that do regular damage, and having 6 of those things suddenly appear on a level 70 character is incredibly deadly.

**How to reproduce:**

Use quest item.  Attack slime.  When buff procs, slime will split into globules.

**How it should work:**
The globules that spawn should only have around 600 health.  They are intended to be easily killed.

**Database links:**

https://www.wowhead.com/wotlk/quest=10411/electro-shock-goodness

**Comment by PanJanuszek** [comment]
fixed 07.03.2024
