### ISSUE TITLE
Whitemane WoW/ Maelstorm server

### ISSUE THREAD

**Issue by Loktarogar0** [gamefreedomgit/Maelstrom#5165]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Hello everyone, I'm playing WoW on Whitemane. I've been hunting for Aeonax for a long time now and I finally found it. I'm a hunter and I have a problem when I mount him and I need to kill him, I can't do it because I'm a hunter ranged dps and somehow I accidentally ground him and killed him. Is this a bug or is there a way for ranged dps to kill it like me, but if someone knows how to explain. Thanks & Regards

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
No - it's not a bug.
