### ISSUE TITLE
Stranglethorn Fever

### ISSUE THREAD

**Issue by wnt23** [gamefreedomgit/Maelstrom#5166]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stranglethorn Fever quest is bugged. When I turn in the gorilla fang to witch doctor unbagwa the waves of gorillas that are supposed to come never show up making it impossible to get Heart of Mokk to complete the quest

**Database links:**
https://www.youtube.com/watch?v=yrCOCHVNUH0

**Comment by UltraNix** [comment]
#2722
