### ISSUE TITLE
Parshah in shadowmoon valley, whitemane server

### ISSUE THREAD

**Issue by Volannar** [gamefreedomgit/Maelstrom#5167]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
hello, I just returned the quest "find the deserter" to Parshah, and normally he should give me the follow-up which is: "asghar's totem".
Can you help me ?
Thanks in advance.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after restart
