### ISSUE TITLE
Torlok in shadowmourn valley

### ISSUE THREAD

**Issue by Volannar** [gamefreedomgit/Maelstrom#5168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
hello, I just returned the quest "the hand of Gul'dan" to Torlok, and normally he should give me the follow-up which is: "Enraged spirits of fire and earth".
Can you help me ?
Thanks in advance.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after restart
