### ISSUE TITLE
Characters do not get drunk from alcoholic beverages

### ISSUE THREAD

**Issue by Hellsz** [gamefreedomgit/Maelstrom#5172]
**Description:**
alcohol effect does not work

**How to reproduce:**
drink something from the list below
| Skin of Dwarven Stout
| Southshore Stout
| Steamwheedle Fizzy Spirits
| Wizbang's Special Brew
| Jug of Bourbon
--
**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/55023320/9168b12e-cddc-4463-a6c3-181c68c00f98)

**Database links:**
(https://cata-twinhead.twinstar.cz/?spell=11008)
[Flask of Port](https://vanilla-twinhead.twinstar.cz/?item=2593)
[Skin of Dwarven Stout](https://vanilla-twinhead.twinstar.cz/?item=2596)
[Southshore Stout](https://vanilla-twinhead.twinstar.cz/?item=3703)
[Steamwheedle Fizzy Spirits](https://vanilla-twinhead.twinstar.cz/?item=17403)
[Wizbang's Special Brew](https://vanilla-twinhead.twinstar.cz/?item=11846)

**Comment by Afgann** [comment]
fixed
