### ISSUE TITLE
Bug in Firelands

### ISSUE THREAD

**Issue by Chrisdev00** [gamefreedomgit/Maelstrom#5174]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Shannox bug in Firelands:**

**How to reproduce:**
If you move one of the adds away from the boss, in this case to the Dismemberer at the top quite far away, you get to bug the dog, leaving it still and out of combat. This helps you a lot because in a HC encounter you get rid of a dog, and you would be looking out only for another,.

The correct way should be as in the video, if you move one of the dogs away, it should gain the enrage debuff, increase the damage and kill the tank, attached video from the official website.

**How it should work:**
![Captura de pantalla 2023-12-09 224445](https://github.com/gamefreedomgit/Maelstrom/assets/134344269/800324bb-d4bc-4d6b-87c6-8b294e199614)
![Captura de pantalla 2023-12-09 224459](https://github.com/gamefreedomgit/Maelstrom/assets/134344269/8b6d1ba5-8bbb-4c03-9b15-92776f3bfb07)

**Database links:**

https://www.youtube.com/watch?v=Bp4rs44HcCg

**Comment by Sketish** [comment]
Boss have enrage if dogs are in x yard away from him

**Comment by UltraNix** [comment]
Fixed.
