### ISSUE TITLE
[Quest - TBC] The Fel and the Furious

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5175]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

i can control the fel reaver, but i dont get credit for killing the infernals.

storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=1195">74/90</a>

**How to reproduce:**

take the quest, click on the console to control one of those fel reavers and try to destroy the infernals.

**How it should work:**

https://www.youtube.com/watch?v=2hPF8a4sK-o

**Database links:**

**Comment by PanJanuszek** [comment]
works as expected 07.03.2024
