### ISSUE TITLE
[Quest] Loremaster - Kalimdor & Eastern Kingdoms (Horde)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5176]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

well, these are all the bugs i found when i tried to get loremaster of kalimdor and eastern kingdoms.

======== Kalimdor  =========

=== Stonetalon Mountains ===

name = <a href="https://cata-twinhead.twinstar.cz/?quest=26058">In Defense of Krom'gar Fortress</a>

bug    = it's too difficult to destroy those flying machines, despite this it is possible to complete this quest but it takes too long 
              i think the mechanics for aiming those flying machines could work better.

how it should work = https://www.youtube.com/watch?v=Pyu0qrC2-Oo

(it is possible to get the <a href="https://cata-twinhead.twinstar.cz/?achievement=4980">achiv</a>)

------

=== Tanaris ===

name = <a href="https://cata-twinhead.twinstar.cz/?quest=26896">The Thunderdrome</a>

bug    = cannot be completed, after clicking on dr. dealwell nothing happens.

how it should work = https://www.youtube.com/watch?v=OA2oyvJ9RhQ

(storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=4935">38/40</a>)

------

=== Thousand Needles ===

name = <a href="https://www.wowhead.com/npc=45278/freewind-brave#ends">Freewind Brave</a>

bug    = after completing the quest <a href="https://www.wowhead.com/quest=27328/grimtotem-chiefs-the-chief-of-chiefs">Grimtotem Chiefs: the Chief of Chiefs</a>, next quest: <a href="https://www.wowhead.com/quest=27358/the-captive-bride">The Captive Bride</a> is not given.

(storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=4938">48/60</a>)

------

=== Felwood ===

bug = after completing the quest <a href="https://cata-twinhead.twinstar.cz/?quest=28121">Forces of Jaedenar</a>, there are no more quests in the entire area.

(storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=4931">17/55</a>)

------

======== Eastern Kingdoms =========

=== Western Plaguelands ===

name = <a href="https://www.wowhead.com/quest=27086/ashes-to-ashes">Ashes to Ashes</a>

bug    = there are no commanders to kill.

how it should work  = https://www.youtube.com/watch?v=ez-VZ3sqG8s

------

name = <a href="https://www.wowhead.com/quest=27085/supporting-the-troops">Supporting the Troops</a>

bug    = killing andorhal defenders gives no credit to complete this quest.

how it should work = https://www.youtube.com/watch?v=9BjCWMsQcZQ

------

name = <a href="https://www.wowhead.com/quest=26933/foes-before-hoes">Foes before Hoes</a>

bug    = there are no laborers to kill.

how it should work = https://www.youtube.com/watch?v=QWTcAfA5rnI

------

name = <a href="https://www.wowhead.com/quest=26979/strange-new-faces">Strange new Faces</a>

bug    =  after completing this quest, when u enter in felstone fields a val'kyr will always spawn to follow you forever (unless you relogin) even if you take the <a href="https://www.wowhead.com/quest=26937/when-death-is-not-enough">next quest</a> or not.

------

name = <a href="https://www.wowhead.com/quest=26937/when-death-is-not-enough">When Death is not Enough</a>

bug    = there are no laborers to kill and convert.

how it should work = https://www.youtube.com/watch?v=1D18juqs-RQ

(storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=4893">36/45</a>)

------

=== Burning Steppes ===

bug = after completing <a href="https://www.wowhead.com/quest=28431/a-perfect-costume">A Perfect Costume</a>, next quest: <a href="https://www.wowhead.com/quest=28432/into-the-black-tooth-hovel">Into the Black Tooth Hovel</a> is not given.

(storyline stuck in <a href="https://cata-twinhead.twinstar.cz/?achievement=4901">17/40</a>)

------

=== Silverpine Forest ===

name = <a href="">On her Majesty's Secret Service</a>

bug    = when u get to where Lorna Crowley is, nothing happens.

how it should work = https://www.youtube.com/watch?v=qgrnfwa24rY

(it is possible to get the <a href="https://cata-twinhead.twinstar.cz/?achievement=4894">achiv</a>.)

------

=== Swamp of Sorrows ===

name = <a href="https://www.wowhead.com/quest=27773/step-three-prophet">Step Three: The Prophet</a>

bug    = after defeating prophet jammal'an u don't get credit and if u abandon this quest lord itharius won't give it u again.

how it should work = https://www.youtube.com/watch?v=WQ0p94o0isE

(it is possible to get the <a href="https://cata-twinhead.twinstar.cz/?achievement=4904">achiv</a>.)

------

**Comment by PanJanuszek** [comment]
For Thousand Needles quest block:
You have to do these 3:

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/c500ae5d-f37d-4b53-886a-4746f395b48f)

In order to unlock

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/e691d715-5b67-43b4-92e9-3d066db8ee13)

**Comment by PanJanuszek** [comment]
For Felwood you have to do Forces of Jaedenear + Crying Violet to move further. Crying Violet is available after complete 28102.

**Comment by frostwave942** [comment]
> For Thousand Needles quest block: You have to do these 3:
> 
> ![image](https://private-user-images.githubusercontent.com/398043/291864757-c500ae5d-f37d-4b53-886a-4746f395b48f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTg4MzMsIm5iZiI6MTcwMzY5ODUzMywicGF0aCI6Ii8zOTgwNDMvMjkxODY0NzU3LWM1MDBhZTVkLWYzN2QtNGI1My04ODZhLTQ3NDZmMzk1YjQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNzM1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmIwYzY5N2NhMjcxM2ViMjBhZmM5MjUwMzRmYzQ5MjE5NTRkNjkyOWFhODZiNTMzZTY1YTVjYTNhNzRkYTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zvhggvuGnwwaplJDW-_1eF4jdVs1VS-2iFUF9kPnpXE)
> 
> In order to unlock
> 
> ![image](https://private-user-images.githubusercontent.com/398043/291864668-e691d715-5b67-43b4-92e9-3d066db8ee13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTg4MzMsIm5iZiI6MTcwMzY5ODUzMywicGF0aCI6Ii8zOTgwNDMvMjkxODY0NjY4LWU2OTFkNzE1LTViNjctNDNiNC05MmU5LTNkMDY2ZGI4ZWUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNzM1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTg5ZTlhMzQ3MmZjNzRlZTMwYzg0ODk5M2Y0OWE4ZTkwMTI2OWUzMWZkNTI1OTVjYjJlNWZkNzNmMmNmOTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nRe45f2RNYwNw_scFROHF48zNzNqrH-NCqljdiPvV7s)

i completed those quests i think, the fact is that the Freewind Brave doesn't give me <a href="https://imgur.com/a/ESyP256">more quests</a>

**Comment by PanJanuszek** [comment]
fixed for 16.04.2024
