### ISSUE TITLE
Asghar's Totem

### ISSUE THREAD

**Issue by CataclysmEnjoyer** [gamefreedomgit/Maelstrom#5178]
**Description:**
Npc named Parshah in Shadowmoon Valley doesn't give the quest in the title, i did the prequest and nothing.

**How it should work:**
He should be giving the named quest.

**Database links:**
https://wowpedia.fandom.com/wiki/Asghar%27s_Totem

https://imgur.com/mKnuILO

**Comment by PanJanuszek** [comment]
You have to wait for restart
