### ISSUE TITLE
Model Error after Pet Taming Rex Ashil

### ISSUE THREAD

**Issue by JK2M** [gamefreedomgit/Maelstrom#5179]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: Taming Rex Ashil, a Wasp ends up getting a different Model and interacting, mutate to a Ground Model while it should be a Flying Wasp. 
And here from Whitemane PTR my own Vid how it changed to the False Model
https://www.youtube.com/watch?v=PoJQs81sLeQ

**How to reproduce: go to Silithus and Tame it, dismiss it, resummon and it will be a Crawler one but with Wasp Abilities, Sting Smack and even Talents are for Wasps.

**How it should work: It should be not change the Model completly to a different Pet Class

**Database links:**
https://www.wowhead.com/npc=14475/rex-ashil

**Comment by UltraNix** [comment]
Fixed.
