### ISSUE TITLE
Shield wall bug in Warrior

### ISSUE THREAD

**Issue by freakyfrizes** [gamefreedomgit/Maelstrom#5180]
Shield wall isn't working proparly and stays unavailable even after using /cancelaura Recklessness and cancelaura /Retaliation which should make it instantly available to use. Instead we have to wait 12 seconds even if the spells were canceled to be able to use our shield wall,this is causing alot of problems in arenas especially for not being able to cast out diffensives in time.

**Comment by Sketish** [comment]
It was reported already. on retail there was cooldown even when you cancelled aura.

**Comment by bonfax4** [comment]
Nvm found video where it was still greyed out after shield wall buff was removed early. It should remain greyed out for the duration it seems. Disregard this.

https://youtu.be/QnDvt7txWgU?t=2m8s
