### ISSUE TITLE
BUG Glyph of Bane of Agony

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#5183]
Glyph of Bane of Agony, not working correctly, this glyph should add 2 "S+" marks and it doesn't.
Currently what the glyph does is add 1 tick "M" and 1 tick "S"

Without glyph of BoA: 
W W W W / M M M M / S S S S
 
With glyph: 
W W W W / M M M M M / S S S S S
 
Meaning it adds an extra M and S to the spell.

**How it should work:**

When using the glyph, two extra strong ticks must be added to the end:
W W W W / M M M M / S S S S / S+ S+

**Combat log:**
A Muñeco de entrenamiento de banda le afecta Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **168** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **168** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **168** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **168** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **336** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **336** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **336** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **336** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **336** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **504** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **504** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **504** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **504** Sombras daño de Terror de agonía de Limitt. 
Muñeco de entrenamiento de banda sufre **504** Sombras daño de Terror de agonía de Limitt. 

**Let me clarify that the 2 "S+" ticks are 33% stronger than the "S" ticks**

You can read this report on twinstar to fix it properly.
https://cata-twinhead.twinstar.cz/?issue=21018

You can also see how it works on wowhead.
https://www.wowhead.com/item=42456/charred-glyph#comments:id=374992:reply=359517

**Comment by UltraNix** [comment]
Fixed.
