### ISSUE TITLE
Pvp server down?

### ISSUE THREAD

**Issue by eyehack84** [gamefreedomgit/Maelstrom#5184]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**    Is the server down.

**How to reproduce:** Was only able to get into PTR

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
If server crashed please check discord for updates
