### ISSUE TITLE
Rogue legendary daggers - Fury of The Destroyer buff - Not functioning

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#5185]
Rogue legendary daggers are proccing the buff correctly but the buff itself does not function
https://www.wowhead.com/spell=109949/fury-of-the-destroyer

https://youtu.be/cePM0k9gSow?si=jbi9gOBulxuZMZf4&t=45 - from PTR showing it does not work

https://youtu.be/HxTdIxs_xGI?si=_Y3KQk2wnSVmKHn6&t=107 - very laggy video from retail showing how the proc works

TLDR:  but should Immediately grants 5 combo points (works) and causes your finishing moves to grant 5 combo points (does not work).  Lasts 6 sec.

**Comment by youz584** [comment]
i have tried it many times too , never generated 5 combo points  after a finishing move 
**Video in whitemane PTR** : https://www.veed.io/view/068504c6-91a9-4dff-9336-69a6c4352008?sharingWidget=true&panel=share

**Comment by UltraNix** [comment]
Fixed.
