### ISSUE TITLE
Recipe: Elixir of Ogre's Strength - bugged drop 

### ISSUE THREAD

**Issue by Kushinagodx** [gamefreedomgit/Maelstrom#5186]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:) 
[//]: # (http://wowhead.com/) https://www.wowhead.com/wotlk/item=6211/recipe-elixir-of-ogres-strength
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?item=6211

**Description:**
 I farm Recipe: Elixir of Ogre's Strength about 2h. Let me explain, drop is 3% and I didnt got it. Drop of melon juice is 2% and I got 20 if it if we will count same drop like 2% for both its chance 1:1048576 it means 9.53e-7% its almost like chance to win lotery and eurojacpot. Stop my sufering of this proven bug by numbers.

**How to reproduce:**
Give me this item to mailbox

**How it should work:**

so logically, the chance should be approximately the same with the mentioned melon juice. Currently it is more than 1:1000000

**Database links:**
Character is Itachigodx - I am sending a screen where you can see 21 melon juices and 0 recipes 
![Uploading Bez názvu.png…]()

**Comment by UltraNix** [comment]
Drop chance 3% is only on two mobs - besides is very low.
