### ISSUE TITLE
The Moonglow Vest Quest are Bugged? (1582)

### ISSUE THREAD

**Issue by derekcc2** [gamefreedomgit/Maelstrom#5187]
Hi, i'm new on server and do low level quests
I don't know if the bug is just with me or a geral bug, and normaly i dont speak about, but i see the message of server that if find any bug is to report, then i decide report
The Quest: Moonglow Vest on Darnasus are Bugged to me, i have all necessary itens made by myslef, but the npc dont give me the Monglow Vest Pattern, in the true, i cannot complete the quest

The Quest
https://www.wowhead.com/classic/quest=1582/moonglow-vest

Necessary itens to complete the Quest
https://www.wowhead.com/classic/item=4239/embossed-leather-gloves (x1)
https://www.wowhead.com/classic/item=2309/embossed-leather-boots (x5)
https://www.wowhead.com/classic/item=2310/embossed-leather-cloak (x5)

The Reward
https://www.wowhead.com/classic/item=6710/pattern-moonglow-vest

the npc stucks on window before the Quest reward window

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/757c9252-f054-4dc5-8d10-fe0daf48e90b)
cannot reproduce, made myself all items
