### ISSUE TITLE
[Talent][Paladin] Eternal Glory consumes the clearcasting effect from Divine Purpose

### ISSUE THREAD

**Issue by Crusaderz** [gamefreedomgit/Maelstrom#5188]
And instead gives 3 holy powers.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/f74c2282-b556-4530-9bae-0da45c3e880f)

How to test: Have less than 3 HP (0-2), use WoG during Divine Purpose buff, when ET proc you will instantly gain 3 HP.

How it should work:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/af982332-09ce-4cdb-b865-c28f88d364e9)

**Comment by Pornoodemon** [comment]
Finally at least someone wrote about it x)

**Comment by UltraNix** [comment]
Fixed.
