### ISSUE TITLE
Lockboxes with little drop and little content

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5189]
**Description:**

Maybe no one reported it because at the time it affected no one's own economy, but we have to let them know.

At the beginning of the Server I gathered many Boxes and opened them, to get a chance to get some prize for my hard work and I didn't get anything...

These Chests currently do not contain what they should, according to wowhead in the comments I have read it says that they contain "X amount of items and X amount of Gold"

The Drop is too low or the Fix is not correct

**How to reproduce:**
[https://www.wowhead.com/item=68729/elementium-lockbox](url)  The Drop is too low or the Fix is not correct, Unrealistic
[https://www.wowhead.com/item=63349/flame-scarred-junkbox](url)  In the Epic items there was much less luck

**How it should work:**

It should have a Drop as they say in the comments

https://www.wowhead.com/item=68729/elementium-lockbox#english-comments
https://www.wowhead.com/item=63349/flame-scarred-junkbox#comments

**Database links:**

https://www.wowhead.com/item=63349/flame-scarred-junkbox
https://www.wowhead.com/item=68729/elementium-lockbox

**Comment by UltraNix** [comment]
Fixed.
