### ISSUE TITLE
Damage reduction Bug

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#5191]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, when you use or is a affected by a dmg reduction ability, it will also decrease ur actual damage aswell.

**How to reproduce:**
https://streamable.com/x6afqu Raptor strike 20% Dmg reduction difference with and without (Tested with Chimera shot)
https://streamable.com/p79jqw Barkskin 20% dmg reduction difference with and without (Tested with Mangle)
https://streamable.com/0nlig5 Survival instincts 50% Dmg Reduction Difference with and without (Tested with Mangle)
https://streamable.com/tyfwza Combat Readiness 50% Dmg reduction difference with and without Tested with (Hemo And ambush somehow eviscerate is not affected by this bug)

**How it should work:**
When affected by a damage reduction ability it should not decrease ur damage aswell, it should ONLY decrease damage taken from enemys.

**Database links:**

**Comment by Kenniflopper** [comment]
I tested this with pain suppression and Power word: Barrier and only Power word: Barrier reduces every allied person inside of it by 25%

**Comment by Kenniflopper** [comment]
Paladin spell called Divine protection which reduces damage taken by 20% also reduces the players damage done by 20%

**Comment by Kenniflopper** [comment]
I just tested Resoration shaman talent Ancestral healing which also reduces damage reduction by 10% but ALSO the damage on the target that is affected by it.

So i think all talents that does does any form of damage reduction effect also reduces damage done.

**Comment by Gunda456** [comment]
recklessness is giving 20% bonus damage ........

**Comment by Kenniflopper** [comment]
And now damage reductions doesnt even work, just tested this with Combat readiness and pain supression

**Comment by WhitemaneSylah** [comment]
Dispersion damage reduction no longer functioning, Adding this as a player refuses to do so.
