### ISSUE TITLE
Pet stance with [Bad manner]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5192]
when the enemy is already under a CC effect for example Scatter shot, i can't overlap [Bad manner] on it While pet is in assisst stance, it only works when pet is in passive stance ,it should work regardless of pet stance. 

You can clearly see in the video, hunter scatter shotted rogue and bad manner over it while pet was in Assist stance.

proof: https://youtu.be/Gdg3N2dmxkk?si=33KwFJUOwepKd6WI&t=193

**Comment by UltraNix** [comment]
Fixed.
