### ISSUE TITLE
mage's orb vs smoke bomb

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5193]
Smoke bomb  effect should complete negate mage's orb which is not the case here.
https://github.com/gamefreedomgit/Maelstrom/assets/129106504/40c996cc-930a-4d2c-9e5c-ee141f40c91d

proof:  https://www.youtube.com/watch?v=owOnI1N-B3k&t=143s

**Comment by UltraNix** [comment]
Fixed.
