### ISSUE TITLE
[Death and Decay] Combat bug

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5194]
Death and decay should only put me in combat if dk lands it on me.
but if he doesn't land it on me and i step on it, it shouldn't put me in combat. 
https://github.com/gamefreedomgit/Maelstrom/assets/129106504/d4a075ea-b2fd-4973-8f9b-9f029ebabe0e

proof: https://youtu.be/tUWXzMmFUls?si=caKL1grsq_U7lmMQ&t=261
You can see Tosan mount top right corner not greyed out when he step into the DnD

**Comment by Revly** [comment]
#4924 #1208 
You have to keep in mind 3 similar reports

**Comment by UltraNix** [comment]
Fixed.
