### ISSUE TITLE
DK  Frost rune bug

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5196]
Frost runes dont work, when using Festering Strike 2 times they should turn into death runes.

https://www.youtube.com/watch?v=VIruSGoNA4g

**Comment by OmbreeTheAmazing** [comment]
having the same issue with unholy dk, tried changing spec, dying, relogging still the same issue

**Comment by UltraNix** [comment]
Better report #5198
