### ISSUE TITLE
Quest: Mostly Harmless (horde)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5197]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mostly Harmless is a quest given by Trade Baron Silversnap in Bogpaddle.  You must go out into the swamp and collect disarmed mines that lay around on the ground in the area.  You must complete this quest to continue the quest series for Swamp of Sorrows.  The main problem is that the mines in the area are very few and far between.  I'm not sure if they have a spawning issue, a phasing issue, or they just have a respawn timer that is way too long to support any number of questing players in the area.  I've been able to collect at least 5 mines since I arrived here, but the quest requires the player to collect 8 mines, and if you do so improperly the mines explode and you cannot collect the quest item you need, so really there should be far more mines than are necessary to complete the quest in order to account for errors.  I suppose it is theoretically possible to complete this quest, but I have not seen any mines in the past 30 minutes or so of riding around the area, including outside of the marked quest area on the map where I have found a few mines to interact with.

The storyline for Swamp of Sorrows contains 36 quests.  "Mostly Harmless" is the 3rd quest in the series, and being unable to complete it prevents the player from doing quests 4, 5, 6, and 7.  I was able to go on to Stonard to pick up quests 8 and 9.

**How to reproduce:**

Using a level 50-52 character, use the quest board in a city to get the quest to go to Swamp of Sorrows.  Talk to Trade Baron Silversnap in Bogpaddle, and do all quests available in the town up to "Mostly Harmless".  Go out into the swamp and look for mines in the area marked on the map, but also look a bit outside of that marked area as mines seem to spawn outside the area as well.
**How it should work:**
The player should be able to go out into the swamp, find the mines spread around the area, and disarm at least 8 of them to take back to Silversnap, accounting for some failures to disarm and triggering some of the mines in the process.

**Database links:**

https://www.wowhead.com/quest=27536/mostly-harmless

**Comment by KevlinTallfellow** [comment]
Logged in many hours later, and rode around the quest area.  Did not see a single land mine spawn.  Still unsure if spawn issue or phasing issue.

**Comment by KevlinTallfellow** [comment]
A day or so later, after I had finished questing in Blasted Lands, I went back to Bogpaddle to check around for mines.  I found enough mines to get the 4 remaining quest items I needed.  I was eventually able to complete this quest and move on to the following quests for the goblins, but it was not in any kind of reasonable time frame for a simple gather quest.

**Comment by UltraNix** [comment]
#2351
