### ISSUE TITLE
Festering strike/Reaping major death rune bug on all unholy dks

### ISSUE THREAD

**Issue by OmbreeTheAmazing** [gamefreedomgit/Maelstrom#5198]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I use festering strike, it should turn my blood rune into a death rune and my frost rune into death rune.  Right now, it ONLY turns my spent blood rune into a death rune.  (Not the frost).    I tested it on 2 death knights, tried killing myself and tried changing to blood then back to unholy.  My brother made a fresh dk on his account and the same issue happened too. 

**How to reproduce:**
On an unholy DK,  cast festering strike. 

**How it should work:**
When you cast festering strike, it should turn your spent blood rune and spent frost rune into death runes.   The unholy passive Reaping is what makes it work.  

**Database links:**
https://cata-twinhead.twinstar.cz/xlomwttpe.html?spell=85948
https://cata-twinhead.twinstar.cz/?spell=56835

**Comment by OmbreeTheAmazing** [comment]
I also asked random dks to try and they have the same issue

**Comment by JK2M** [comment]
GJ was wondering why my rotation is so fked up

**Comment by OmbreeTheAmazing** [comment]
Looks good now thanks UltraNix
