### ISSUE TITLE
Dark Simulacrum and Hand of Sacrifice conflict/bug

### ISSUE THREAD

**Issue by OmbreeTheAmazing** [gamefreedomgit/Maelstrom#5201]
**Description:**
After casting Dark Simulacrum on a target affected by Hand of Sacrifice, when the target casts a spell it will copy Hand of Sacrifice instead of the casted spell.  

**How to reproduce:**
Have a paladin cast Hand of Sacrifice on a mage.  Have the Death Knight cast Dark Simulacrum on the mage.  The mage affected by Hand of Sacrifice then casts a spell like Polymorph.  The Death Knight will now have Hand of Sacrifice copied.

**How it should work:**
Normally, it should copy the Polymorph (or whatever spell the person casted) instead of Hand of Sacrifice. 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=6940
https://cata-twinhead.twinstar.cz/?spell=77606

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/0f568562-a9cf-4271-96a8-17c59ecf59a9)
It works okay for me. You can see Poly icon on my bar while mag still have Hand of Sacrifice.

**Comment by OmbreeTheAmazing** [comment]
Hmm I must be missing something then, it still happens to me from time to time.  I noticed it happened when I was in 3v3 yesterday, maybe it's when a mage steals it from a paladin.

**Comment by UltraNix** [comment]
@OmbreeTheAmazing But mage steals what? Hand of Sacrifice? Then it must be from enemy paladin.

**Comment by UltraNix** [comment]
No further info - closing.
