### ISSUE TITLE
Quest:  Step Three: Prophet (horde)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5202]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Lord Itharius asks the player to go into the temple and defeat Jammal'an the Prophet.  However, when the player defeats Jammal'an, he says his dialogue and simply despawns instead of doing his actual escape script, so the event doesn't trigger the remote completion of the quest to continue the series.
**How to reproduce:**
Speak to Itharius outside of the temple to go through the quests.  Once you get down into the temple, the quests begin to complete remotely, where you eventually obtain the quest to defeat Jammal'an.  Go to bottom of temple and fight Jammal'an.

**How it should work:**

Once the player "defeats" Jammal'an, Jammal'an should say his line and use an ability to teleport away, causing Itharius to autocomplete the quest remotely and offer the next quest.
**Database links:**

https://www.wowhead.com/quest=27773/step-three-prophet#videos:id=84020

**Comment by KevlinTallfellow** [comment]
Addendum:

As of Dec 29 2023 this quest is also still bugged for alliance characters, though I don't think that matters since it's a neutral quest.

**Comment by UltraNix** [comment]
#5176
