### ISSUE TITLE
Arena mmr bug 

### ISSUE THREAD

**Issue by Milagring** [gamefreedomgit/Maelstrom#5203]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
i am wondering in arena rating with my 2's i got 1800+ nearly 1900 rating and played with ret when i log out and came back things change my mmr go back to 1600 and my standing is 0-3

**How it should work:**
Please fix this bug arena mmr 

my proofs 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/153963205/0b23522c-f9b5-4813-86db-64581163002c)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/153963205/e56d0ecd-5828-401c-b2b2-0a5ef58836c4)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/153963205/da0cc7da-d338-4502-a93a-a6b633a352e7)

**Comment by UltraNix** [comment]
There was a rollback then.
