### ISSUE TITLE
Insta 85 Chars Cannot See Bases On Maps

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#5204]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Only Happens To My Insta 85 Chars, but on gilneas and eye of the storm, when you press M, you cannot see base icons.
**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Most likely client issue. Try clear your cache folder.

**Comment by Hermeleen** [comment]
Didn't help by the way. I am pretty sure every insta 85 char has this issue.
