### ISSUE TITLE
Herbs/Briarthorn with gear loot icon instead of Herbing

### ISSUE THREAD

**Issue by talltxtech** [gamefreedomgit/Maelstrom#5205]
m[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When Herbing in Northern barrens there are some herb such as Briar thorn that have the gear Icon instead of the normal herbs one and it makes it so it can't be harvested.  I will supply the location

**How to reproduce:**

**How it should work:**
![briar2](https://github.com/gamefreedomgit/Maelstrom/assets/154006903/2de4a7a7-fd3d-4549-be70-a164e37ade7c)
![briar](https://github.com/gamefreedomgit/Maelstrom/assets/154006903/26d9b3a3-44d7-42df-afb6-52a3282c7c9f)

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/01a2dd62-aeb6-4619-b353-17e57e59f685)
Looks okay.
