### ISSUE TITLE
Lightwell Targetting

### ISSUE THREAD

**Issue by itslethis** [gamefreedomgit/Maelstrom#5207]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
To use Lightwell you need to click on it. When clicking it you are targetting it. IT's really annoying.

**How to reproduce:**
Make it so when I click Lightwell I get the healing buff but I don't make me target Lightwell so I need to change target again and again.

**How it should work:**
When click on Lightwell I get the buff but it doesn't make me target Lightwell when i click it.

**Database links:**

**Comment by Hermeleen** [comment]
#5087 . Could be make so that right click gets you buff, and left click targets it.

**Comment by itslethis** [comment]
> #5087 . Could be make so that right click gets you buff, and left click targets it.

No matter if i right or left click it. It gonna target Lightwell anyway.

**Comment by Hermeleen** [comment]
> > #5087 . Could be make so that right click gets you buff, and left click targets it.
> 
> No matter if i right or left click it. It gonna target Lightwell anyway.

What i mean is that that could be the possible solution, target on left click, and get only buff on right click.

**Comment by itslethis** [comment]
> > > #5087 . Could be make so that right click gets you buff, and left click targets it.
> > 
> > 
> > No matter if i right or left click it. It gonna target Lightwell anyway.
> 
> What i mean is that that could be the possible solution, target on left click, and get only buff on right click.

Ah ye, that would be good solution, I hope they can do something with that because Lightwell is really but spell but it's annoying to keep switching targets every few seconds

**Comment by Sketish** [comment]
Suggestion, not a bug report. Cosing
