### ISSUE TITLE
Frost-fire orb doesn't crit

### ISSUE THREAD

**Issue by dickonhard** [gamefreedomgit/Maelstrom#5213]
**### Description:**
**Frost-fire orb** spell (https://cata-twinhead.twinstar.cz/?spell=84726) doesn't have crit chance, tested on dummies AND players. It never crits.

**How to reproduce:**
https://youtu.be/jBcEb28bLoc

**How it should work:**
It should crit. Proof from old real cata: https://www.youtube.com/watch?v=AneH1dAtbto (1:59)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=84726

**Comment by Afgann** [comment]
fixed
