### ISSUE TITLE
Gurthalak doing 9 tics instead of 8

### ISSUE THREAD

**Issue by Padreftis** [gamefreedomgit/Maelstrom#5214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154061449/4c712c76-21c8-435e-8b66-74df75e042bd)
8 tics on apollo

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154061449/d8ea9bd0-2ec7-455a-b908-c1e1a75a14e4)
9 tics on test server 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Hermeleen** [comment]
maybe haste difference?

**Comment by Sketish** [comment]
Provide retail proof of ticks, AND NEVER compare to apollo

**Comment by bonfax4** [comment]
Somebody archived all the mentions of gurth proc here https://github.com/simulationcraft/simc/issues/984 and it should do a mixture of 8-9 ticks reallistically. Tentacles should not scale with haste.

**Comment by bonfax4** [comment]
If its consistently doing 9 maybe some rng factor should be added to proc to properly emulate retail ?

**Comment by Sketish** [comment]
I mean if dmg from single proc is not bigger than on retail then the dmg is just divided by 9 ticks which doesnt matter much

**Comment by UltraNix** [comment]
Fixed.
