### ISSUE TITLE
[QA] [Dragon Soul Heroic] Unholy DK Issues

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#5215]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
1) Ultraxion can't be hit by Death and Decay, even if you place it as far as possible on the Edge. (Possibly same issues with other ground targeted AOEs)

2) Pet sometimes gets stuck and evades Shadow Infusion Stacks on Madness of Deathwing after switching Platforms. (Possibly similar issues with hunter and warlock pets)

3) Pet takes way too much dmg and gets killed by Corrupted Parasites' Unstable Corruption. Should be reduced by Pet aoe passive.

**How to reproduce:**
1) Fight Ultraxion and try to place Death and Decay as close as possible under him.

2) Fight Madness of Deathwing and switch platforms with your Pet summoned.

3) Fight Madness of Deathwing and place Pet next to Corrupted Parasite before it explodes.

**How it should work:**
1) Ultraxion should get hit by ground targeted AOEs.

2) Pet should follow/jump with you and not get stuck.

3) Pet should takes reduced damage from Unstable Corruption due to Pet passive.

**Database links:**
https://www.cavernoftime.com/spell=43265 - Death and Decay
https://www.cavernoftime.com/spell=49572 - Shadow Infusion
https://www.cavernoftime.com/spell=108813 - Unstable Corruption
https://www.cavernoftime.com/spell=62137 - Avoidance (Pet Passive)

**Comment by UltraNix** [comment]
Fixed.
