### ISSUE TITLE
Frost bolt critical hit chance into frozen target is calculated WRONG

### ISSUE THREAD

**Issue by dickonhard** [gamefreedomgit/Maelstrom#5217]
**Description:**
The frost bolt (https://cata-twinhead.twinstar.cz/?spell=116 ) crit chance into FROZEN target is calculated wrong.
Glyph of frost bolt(https://cata-twinhead.twinstar.cz/?item=42742 )
Shatter talent multiplies the crit chance of spells being hit on frozen targets by 3(https://cata-twinhead.twinstar.cz/?spell=12982 )
So basically how its crit chance should be calculated is this: basic crit chance(24.27% of mine. https://imgur.com/a/PKKk6bq ) adds up to 5% crit chance from Glyph of frost bolt, and then the sum must be multiplied by 3 (shatter talent) which equal 87.81% 
(24.27+5)x3=87.81% and this must be estimated crit chance of frost bolt.
What we have instead: Basic crit chance(24.27%) is multiplied by 3 (equals 72.81%) and THEN added up the 5% crit chance from glyph of frost bolt and equals 77.81%
(24.27x3)+5=77.81%
This all i figured out after testing the ability ON PLAYERS, not dummies.

**How to reproduce:**
This all i figured out after testing the ability ON PLAYERS, not dummies.
My stats and recount (https://imgur.com/a/PKKk6bq )
So after testing 204 Frostbolt on player, each of spell was casted only when player was frozen(37 min video of testing, can check: https://www.youtube.com/watch?v=OZC0q4kszqg ) and the result of test were: 77.9% of critical hits of frostbolt when estimated chance was 87.81%. And 77.9% would be estimated probability only if the calculations were done wrong way as i mentioned before(when 5% crit chance from glyph is added AFTER the multiplication of basic crit by 3)
For example, ice lance showed result of 72.9% of critical hits overall after 133 attempts, which equals to its estimated chance of 72.81%

**How it should work:**
As i said, formula FIRSTLY must add the 5% crit chance from frostbolt glyph to basic crit chance of player, and then multiply it by 3 from shatter talent

**Database links:**

**Comment by dickonhard** [comment]
What info needed?

**Comment by dickonhard** [comment]
@Sketish should I provide some sort of info or what?

**Comment by bonfax4** [comment]
This is one of those things that would be hard to prove but this early cata guide does mention it. 

https://www.mmo-champion.com/threads/820907-Mage-The-Ultimate-Guide-to-Frost

> Keep in mind that Shatter takes each spell's individual crit chance into account – if you have glyph of frost bolt, for example, that's actually +15% crit after Shatter.


Also going over frost [elitistjerks frost post](https://web.archive.org/web/20120807223537/http://elitistjerks.com/f75/t110339-frost_mage_discussion_cataclysm/p5/), critical mass or similar crit debuffs should also account for shatter ( according to early tests, unless smthing changed later on ).

@dickonhard Test 5% critical debuff and see if it triples

**Comment by bonfax4** [comment]
@Sketish also [this](https://www.mmo-champion.com/threads/923185-Frost-mage-Questions?highlight=Glyph+of+frostbolt+shatter)

**Comment by Sketish** [comment]
Ah my comment wasnt send for some reason, I wanted proff that multiplied crit chance should be always all crit from stats+glyph+talents  summed before. Blizzard used to not count something. But @bonfax4  helped with info

**Comment by dickonhard** [comment]
@Sketish they counted all outgoing critical chance before multiplying. They might have not counted for example the +5% crit chance debut on target (from scorch for example) to be multiplied. This might have actually been added after multiplication. Just like other buffs or rebuffs on target like barkskin for example, which should reduce crit chance taken by 25% but after all of the multiplications. So I’m assuming there must be such logic: the final spells crit chance is calculated by 1)  outgoing crit chance from subject who launch the spell 2) +- buffs or debuffs incoming crit chance of subject 2 who gets casted on.  So multiplication must be the last phase of calculating the OUTGOING crit chance, and afterwards, you just plus minus from debuffs. This is my semantic assumptions, but I don’t see other versions making more sense

**Comment by dickonhard** [comment]
@bonfax4 thank you for participating <3

**Comment by bonfax4** [comment]
Critical debuff did count for shatter crit calc as well.

**Comment by bonfax4** [comment]
You are prob right. All the conversations I'm seeing that argue if boss crit suppression ( 2% ) is in effect that crit cap would raise to @34%  (34*3 = 102 ) and not @35.3% like you'd expect.

**Comment by dickonhard** [comment]
@bonfax4 i haven’t tested fire tbf, I suppose 5% from scorch is counted in shatter, otherwise there would have been so many complaints. Another question wether it should or should not be actually multiplied im still wondering

**Comment by dickonhard** [comment]
On the other hand it fits my logic that it shouldn’t. On the other hand I dunno if devs would ever nerf fire like that, if it gets multiplied rn

**Comment by bonfax4** [comment]
It is

**Comment by dickonhard** [comment]
I’m not gonna debate on that one, cuz I haven’t researched that one. Was just expressing my thoughts

**Comment by dickonhard** [comment]
@bonfax4 by the way, there’s sort of contradiction, since the test showed that 5% is multiplied by shatter, but some gm confirmed it didnt(in this case =shouldn’t)
![IMG_2317](https://github.com/gamefreedomgit/Maelstrom/assets/144682267/16657a97-72e7-4efc-9961-99ae1fb0f557)

**Comment by dickonhard** [comment]
Yes I saw it worked, I mean what if it shouldn’t, just was a bug

**Comment by dickonhard** [comment]
It’s a philosophical question tho, since I’m down for blizzlike with their errors and bugs actually

**Comment by bonfax4** [comment]
That won't matter, the fix based on how it worked and not how it should work. The reason they custom implemented "ignite munching" mechanic.

**Comment by mipanka** [comment]
I now tested pyroblast crit, glyph https://wowpedia.fandom.com/wiki/Glyph_of_Pyroblast. My crit chance 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/0872b5a1-865d-4340-9d45-9b4838b36379)
and 5% https://wowpedia.fandom.com/wiki/Critical_Mass = 33.43%*3 = 100.29%

**Comment by dickonhard** [comment]
@mipanka and fireball?

**Comment by bonfax4** [comment]
What are you testing against btw ? 85 dummy ?

**Comment by dickonhard** [comment]
Yea by the way test it on people, gms won’t take into consideration dummy tests

**Comment by bonfax4** [comment]
Not that it's needed at this point but Cartoonz mentioning pyro glyph gets the 3x boost from shatter https://youtu.be/hVIaYJoT_5U?t=7m27s

**Comment by dickonhard** [comment]
It must get yeah, as well as fireball glyph

**Comment by bonfax4** [comment]
Oof looking at some mop data crit suppression affected crit before shatter calculations so now I'm again not sure again if spells like barkskin crit reduction happens before or after ? Any definite proof on that ?

**Comment by dickonhard** [comment]
@bonfax4 its completely a different game and story, I remember and nobody will argue that it didn’t affect crit too much on ferals with skin, if it was calculated before then chance of crit would have been around 0%. besides right now it’s in ferals interest to prove it wrong.

**Comment by dickonhard** [comment]
@Sketish do I have to make separate reports for pyroblast glyph, fireball glyph, and critical mass? Because even from these topics it’s obvious that all of them were multiplied by shatter talent

**Comment by bonfax4** [comment]
@dickonhard https://youtu.be/UnGImLYzujY?t=1m19s Very small sample pool but he says barkskin made druid uncrittable when he tried to burst.

**Comment by dickonhard** [comment]
Well it seems like it’s broken too then

**Comment by dickonhard** [comment]
@Sketish any thoughts man?

**Comment by bonfax4** [comment]
Critical mass and barkskin seem to be fine so far from what i tested as in calc being done pre-shatter. Only problem is crit glyphs

**Comment by dickonhard** [comment]
@bonfax4 i will test it again this week, but yeah glyphs 100% don’t work, question is only critical mass

**Comment by dickonhard** [comment]
@Sketish yo man I know you’re busy with more important DS stuff, but if you would find some time for this would appreciate it bro

**Comment by Sketish** [comment]
Make other report for fireball/pyro and critical mass. Currently this one has medium prio. Prolly will be looked after DS hc release

**Comment by dickonhard** [comment]
@Sketish alright, thanks!

**Comment by dickonhard** [comment]
@Sketish how’s it going?

**Comment by UltraNix** [comment]
Fixed.
