### ISSUE TITLE
[QA] [Dragon Soul Heroic] Morchok Crystal Beam Visual

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#5220]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Crystal Beam Visual sometimes disappears randomly. (see video)

**How to reproduce:**
Fight Morchok and wait for Crystal to spawn and link to you.

**How it should work:**
Shouldn't disappear.

**Video links:**
https://streamable.com/ikjboe

**Comment by UltraNix** [comment]
Fixed.
