### ISSUE TITLE
Discipline priest bugged

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#5221]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The penance spell is bugged, should send three charges and every other time it only does two instead of three.

**How to reproduce:**
Cast penance

**How it should work:**
Should send three charges of heal

**Database links:**
https://www.wowhead.com/fr/spell=241466/p%C3%A9nitence

**Comment by xmrshoot** [comment]
its not bugged
![Uploading image.png…]()

**Comment by xmrshoot** [comment]
![WoWScrnShot_121723_230202](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/058ffb9f-8296-4d8b-bc99-760c0b204586)

not bugged

**Comment by VaellWhitemane** [comment]
Bro read what I write

**Comment by xmrshoot** [comment]
and look the screen shot , it heals 3 times , its not bugged

**Comment by VaellWhitemane** [comment]
Ok ok  i Will make video for u

**Comment by xmrshoot** [comment]
u are right , sorry , i did it 10 times and like 3 out of 10 sent only 2 heals not 3

**Comment by VaellWhitemane** [comment]
:)

**Comment by xmrshoot** [comment]
ye , its bugged 
![WoWScrnShot_121723_231904](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/25c60662-4a84-46e5-9823-23204464e75f)

**Comment by Afgann** [comment]
fixed

**Comment by GreyLorethal** [comment]
Excuse me, but looks like this bug has returned.
