### ISSUE TITLE
Replenishment buff doesn't work in arena

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5224]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When you use judgement on an enemy my arena partner is not receiving replenishment buff

**How to reproduce:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/e05c0660-be8a-4af0-bddb-3eb20882db8c)
 he dont have the buff

**How it should work:**

**Database links:**

**Comment by SimonBpvp** [comment]
#4590 
I reported this one too but it’s working as intended
