### ISSUE TITLE
Its Over Nine Thousand!

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#5226]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, I passed 9k achivement points (currently 9010)on Whitemane Maelstrom and didnt get the "Its Over Nine Thousand!" Feats of Strenght achivement.
My in game character name on Maelstrom realm is: Hacker 

**How to reproduce:**

**How it should work:**
I should have it once I pass the 9000 achivementpoint score. 

**Database links:**
https://www.wowhead.com/achievement=4496/its-over-nine-thousand

**Comment by UltraNix** [comment]
@TheRealHackerMan Write a ticket ingame.
