### ISSUE TITLE
Reset instances

### ISSUE THREAD

**Issue by Dinbandit** [gamefreedomgit/Maelstrom#5227]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I cant reset instances

**How to reproduce:**
Right click character and select reset all instances

**How it should work:**
It should reset all instances, but it doesnt

**Database links:**

**Comment by VaellWhitemane** [comment]
Yes its bugged

**Comment by UltraNix** [comment]
Just tested and works okay.
Only normal instances can be reset,

**Comment by Revly** [comment]
gamefreedomgit/Maelstrom/issues/5227

supposedly work
