### ISSUE TITLE
Rogue Legendary daggers | Fury of the Destroyer  BUFF | BUG

### ISSUE THREAD

**Issue by youz584** [gamefreedomgit/Maelstrom#5229]
the " Fury of the Destroyer" buff , caused by  the daggers it's does not  generate  5 combo points when i doing a finishing move, 
i tested it many times , never worked as expected 
**Fury of the Destroyer Buff** : https://www.wowhead.com/spell=109949/fury-of-the-destroyer

![image](https://github.com/gamefreedomgit/Maelstrom/assets/154277142/42d0f0ef-d1df-4085-bb93-db12aeff4c56)

**Video in whitemane PTR** : https://www.veed.io/view/068504c6-91a9-4dff-9336-69a6c4352008?sharingWidget=true&panel=share

**Comment by UltraNix** [comment]
#5185
