### ISSUE TITLE
Quest: A Spirit Guide (horde)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5231]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The player is supposed to go to the corpse of the assassin, and use the spirit guide item to spawn a ghost wolf.  Then the ghost wolf leads the player up into the Mag'har encampment, where the player is able to complete the quest and get enough reputation to change Mag'har from unfriendly to neutral, allowing the player to do quests for them to further increase reputation.  However, when the spirit wolf finally reaches the captain, instead of staying there a moment to allow the player to turn the quest in, the spirit wolf immediately disappears, preventing the player from completing the quest.
**How to reproduce:**

Accept quest.  Go to assassin's corpse and use the ancestral spirit wolf totem.  Follow spirit wolf up into Mag'har encampment, to where the escort ends at Gorkan Bloodfist and Earthcaller Ryga.
**How it should work:**

The spirit wolf should guide the player up into the Mag'har encampment, back into the area where the captain and the earthcaller are, and then walk up to the earthcaller, who converses with the spirit wolf.  The spirit wolf is supposed to stay there for a moment, so that while it is nearby the player is able to turn the quest in to Gorkan Bloodfist.
**Database links:**

https://www.wowhead.com/quest=9410/a-spirit-guide#comments

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/a8c74579-c8d4-4fb6-bf07-223e90b1e9fa)
I didn't meet any problems
