### ISSUE TITLE
master of the molten flow

### ISSUE THREAD

**Issue by Digna007** [gamefreedomgit/Maelstrom#5233]
https://www.wowhead.com/achievement=5871/master-of-the-molten-flow

**Description:**
shaman dies by the flameweave, but it doesn't register for the achievement "master of the molten flow"

**How to reproduce:**
try to kill the shaman, with the flamewave and to register in the achievement, "master of the molten flow"

**How it should work:**
it should be registered in the achievement
it should register
**Database links:**

**Comment by MaestosoToad** [comment]
I can confirm and reproduce this behavior

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/04e2a343-8899-48da-8681-b4115e3b8641)
Nothing wrong here - just make sure it dies from Flameweave, not from your attacks. Also, the shaman must be hit by the flames casted by lava randomly.
