### ISSUE TITLE
DS: Globs hit like a truck and they are all come in when they in combat

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5236]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Already reported and fixed.
