### ISSUE TITLE
Zon'ozz disrupting shadows

### ISSUE THREAD

**Issue by RamiroBaraza** [gamefreedomgit/Maelstrom#5237]
Tested in Mimiron playgrounds, Zon'ozz 10 NM

Description: When you dispell a player, everyone in 10m radius get the knockback and damage

How to reproduce: Dispell someone with Disrupting Shadows in 10 NM with some other player nearby

How it should work: Should only knockback and damage the dispelled player, in NM mode

**Comment by UltraNix** [comment]
Tested and works okay - only dispeled players gets knockback and damage.
