### ISSUE TITLE
[MPG] Can't rupture ice tomb on hagara.

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5239]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I was unable to use rupture on the ice tomb on hagara as sin rogue

**How to reproduce:**
Try to use rupture on ice tomb on hagara as sin rogue

https://clips.twitch.tv/HardMoldyCasetteEagleEye-RXDhp41Ny0rAcEse

**How it should work:**
Should be able to rupture on ice tomb on hagara as sin rogue

**Database links:**

https://www.wowhead.com/spell=70157/ice-tomb
https://www.wowhead.com/spell=1943/rupture

**Comment by Waroxx-QA** [comment]
Already reported and fixed. should be up by the next update
