### ISSUE TITLE
portal should close on summit tower when we activate the ultraxion encounter but the portal to down floor is still available

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5240]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report. read announcement + follow template

**Comment by UltraNix** [comment]
Fixed.
