### ISSUE TITLE
u should see twilight assaulter's casting channel and to interrupt they are bugged after typhoon and they will afk till die

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5242]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report. read announcement + follow template

**Comment by UltraNix** [comment]
Casting channel is not visible, because it's an infinity cast.

**Comment by UltraNix** [comment]
Fixed.
