### ISSUE TITLE
[MPG] Still only 1 fading light between each hour of twilight

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5245]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The boss casts only 1 serie of fading light debuff

**How to reproduce:**

pull the boss and wait
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/0264fa4d-21d2-41c5-ba85-f275070dd832)

**How it should work:**

Should be 2 serie of fading light in normal between each hour of twilight

**Database links:**

**Comment by Sketish** [comment]
Already reported in https://github.com/gamefreedomgit/Maelstrom/issues/4629
