### ISSUE TITLE
warmaster blackhorn: dxe bugged out

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report, read announcement + follow template
