### ISSUE TITLE
[MPG] Twilight barrage aoe is too big

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5249]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Maybe the visual of the swirling thing on the ground is permissive, but look at his clip, it seems way too big.

https://clips.twitch.tv/GleamingInquisitiveKimchiChefFrank-WlgoNQ8lZ_L9dXoF

**How to reproduce:**

try to take barrages at different distance from the aoe

**How it should work:**

smaller aoe ? (it says 5 yard in the codex) i really dont know if its supposed to be this big or not

**Database links:**

http://cata-shoot.tauri.hu/?spell=109203

**Comment by Polynomix** [comment]
To show i did die from the two barrage and not from something else : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/6b245999-dad0-4fcf-b86f-e5efff621e55)

**Comment by UltraNix** [comment]
Fixed.
