### ISSUE TITLE
[MPG] YOR sahj slime trash moving around the room 

### ISSUE THREAD

**Issue by Maestra7Aisset** [gamefreedomgit/Maelstrom#5250]
**Description:**
trash slimes moving all around the room super fast around the entire arena

**How to reproduce:**

**How it should work:**
https://youtu.be/lJLAt9_cwiE

**Database links:**

**Comment by Maestra7Aisset** [comment]
![WoWScrnShot_122023_123413](https://github.com/gamefreedomgit/Maelstrom/assets/143819276/b8854f17-8fe3-4f61-967f-daadd6a79d51)
![WoWScrnShot_122023_123402](https://github.com/gamefreedomgit/Maelstrom/assets/143819276/153ff05d-2eee-4034-b086-5a6a1f0eee27)

**Comment by Waroxx-QA** [comment]
Already fixed, it will be up by the next update.
