### ISSUE TITLE
[MPG] Weird Blade rush visual from the Twilight Elite

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5251]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Sometimes the blade rush visual does not represent at all the charge that the Twilight Elite is going to do

Example in this clip at 15s : https://clips.twitch.tv/GleamingInquisitiveKimchiChefFrank-WlgoNQ8lZ_L9dXoF

There was also times whre it was 90 degree from what the Charge actually did

**How to reproduce:**

Pull the boss and look

**How it should work:**
visual should match the animation of the charge

**Database links:**

**Comment by Potatwowo** [comment]
Description:
Charge texture is not in alignment with the charge path.
https://www.youtube.com/watch?v=1BvotoTgvWg

How to reproduce:
Engage Warmaster, wait for adds to charge.

How it should work:
Charge texture should align with the charge path.
https://youtu.be/Sgt7Wp2kSLk?t=77

Moved it here as I didn't see its already posted.

**Comment by UltraNix** [comment]
Fixed.
