### ISSUE TITLE
[MPG] DS: Hagara crystals issue

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5252]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Ingame name: Mishka

**Description:**
Hagara the Stormbinder: when the ice phase begins and you need to kill all the crystals, the phase ends prematurely. Even when one or two crystals remain, the phase ends

**How it should work:**
You need to kill all the crystals to end the ice phase

**Database links:**

**Comment by UltraNix** [comment]
@vanarenan More info on it. Do you have any screenshots?
Phase is ended if all 4 ice crystals are killed or the cast is ended.

**Comment by vanarenan** [comment]
> @vanarenan More info on it. Do you have any screenshots? Frozen Phase happened after the Lightning one? Phase is ended if all 4 ice crystals are killed or the cast is ended.

Sorry, no screenshots available. Yes, Frozen Phase happened after the Lightning one.
So the main issue is that Frozen Phase may end before cast ended even if not all 4 ice crystals are killed. In my case it ended when we killed 3-rd one and one more left.

**Comment by UltraNix** [comment]
Hmm - maybe it was enrage?

**Comment by vanarenan** [comment]
Not an issue anymore, seems working normaly now

**Comment by UltraNix** [comment]
Okay - I will close it. As soon as it happens again, please open a new report with details.
