### ISSUE TITLE
DS: Warmaster Blackhorn

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5254]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**Description:**
Goriona doesn't fly away when she is below 70% HP

**How it should work:**
Goriona should fly away when she is below 70% HP

**Comment by UltraNix** [comment]
Already reported in #4629
