### ISSUE TITLE
DS : Combat Bug

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#5255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On spine we wipe and now, when the first guy enter in raid, we have "impossible to change zone during an encounter" cuz we get mode combat when we enter

**How to reproduce:**
Idk, wipe and go out 

**How it should work:**
Dont Get Combat bug

**Database links:**

**Comment by UltraNix** [comment]
The thing is: talking to NPC on the boat starts Spine encounter/combat. If the 1st guy did it and the rest of the raid was out of instance (e.g. in ghost forms) then it's not a bug. It's -50 dkp for that guy :P

**Comment by Waroxx-QA** [comment]
@UltraNix issue confirmed, there's a combat bug, only 1 player can go inside and gets in combat, the 9 other players can't go in, the only way to fix it is that the player that could go inside starts the encounter again, die and realease.

**Comment by UltraNix** [comment]
Fixed.

**Comment by VaellWhitemane** [comment]
name of character : Ozo
