### ISSUE TITLE
DS: Warmaster Blackhorn

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#5256]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The shockwave should break everyone's cast, but it doesn't

**How to reproduce:**
Cast while the boss does shockwave

**How it should work:**
Should interact the people who continue to cast, and silence them

**Database links:**

**Comment by Waroxx-QA** [comment]
it's not shockwave but **Disrupting Roar**
![Screenshot_2023-12-20-21-05-58-28_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/1bc85a10-1733-417d-9a2a-3478c946cbaf)
it has a 10 yards range, so unless you don't get silence standing less than 10y from the boss, it's not a bug.
i'll test it later and confirm.
Please edit your report by replacing Shockwave with **Disrupting Roar**.

**Comment by UltraNix** [comment]
Shockwave stuns player in a 80y cone - it works okay.
About Disrupting Roar - always works okay. Take into consideration it has 10y radius.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/831881af-b728-4162-a0fb-eb421f03975b)
