### ISSUE TITLE
Goriona Fly Away problem

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5258]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
During Warmaster Blackhorn, Goriona does not fly away when it reaches 20% HP

**How to reproduce:** 
Goriona should fly away on 20% HP on Normal difficulty and 15% HP on Heroic difficulty.
**How it should work:**
Fight Goriona during the boss fight, at 20% it should fly away but it doesn't.
**Database links:**

https://youtube.com/clip/UgkxoeLhZyORrTV17Lc7PB08NQA9fuWe3fjp?si=1X7p5ppf-pFaoVMe

**Comment by Waroxx-QA** [comment]
Wrong, Goriona flies at 25% on normal and 20% in heroic
Already reported and fixed, should be up after next update
