### ISSUE TITLE
[MPG] madness spellwave dmg too high

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5259]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** spellwave damage from kalecgos is too high or procs are too many

**How to reproduce:** just do dmg

**How it should work:** dmg should be w way more low

**Database links:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/cfee1f25-b014-4448-a3f2-432558350d6f)

**Comment by Waroxx-QA** [comment]
Already reported.

**Comment by UltraNix** [comment]
v
