### ISSUE TITLE
[MPG] SPINE

### ISSUE THREAD

**Issue by Maestra7Aisset** [gamefreedomgit/Maelstrom#5262]
**Description:**
spine plate killed but hitbox stil there blocking the path 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Maestra7Aisset** [comment]
![WoWScrnShot_122023_164928](https://github.com/gamefreedomgit/Maelstrom/assets/143819276/bcd3fb0a-d922-40ef-a267-df8a2b7bc6cb)
![WoWScrnShot_122023_164936](https://github.com/gamefreedomgit/Maelstrom/assets/143819276/11f5e836-b602-4101-82ab-c3b08360d688)
![WoWScrnShot_122023_114236](https://github.com/gamefreedomgit/Maelstrom/assets/143819276/1141abb7-5da7-4ec2-9a08-f98d0ebdf3d7)

**Comment by Potatwowo** [comment]
It worked fine first 2 pulls, but after that it stopped working. It is like there is an invisible plate there.

**Comment by vanarenan** [comment]
Samw issue for everyone else now

**Comment by UltraNix** [comment]
Fixed.
