### ISSUE TITLE
[MPG]Invisible wall bugged inside dragon soul

### ISSUE THREAD

**Issue by Misclick2** [gamefreedomgit/Maelstrom#5263]
Character name : Rott

**Description:**
Heroic Leap out of bounds at entrance in Dragon Soul (did not test with other movement abilities eg. disengage, leap of faith, blink... probably works with them also)
You can pretty much go anywhere you want that is behind the bounds.

**How to reproduce:**
Go into dragon soul, go next to the entrance portal, walk until you hit the invisible wall heroic leap to go beyond the wall (screenshots provided of exact spot),

**How it should work:**
Invisible walls should block all passage through them not allowing things like heroic leap to go through.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=6544
![Screenshot_1](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/b72b360a-07f3-44c5-8eef-98c2aabd5159)

![Screenshot_2](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/1dd0c54b-0858-48d6-a2e0-44657a2313eb)
![Screenshot_3](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/50edace2-0707-4c7a-aa95-fefb5bd614ed)
![Screenshot_4](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/a86a15b6-f861-465d-8971-ce168afe3c48)
![Screenshot_5](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/ce05b615-3b5c-40f0-8399-fdb3aeecb77c)
![Screenshot_6](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/00aea573-eca9-47b9-be53-eb09f7661eaa)
![Screenshot_7](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/551f64fc-4289-48ec-bc0a-52d0fd40e668)
![Screenshot_8](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/3723007b-5e78-4b2f-a15a-f114bb1889b9)
![Screenshot_9](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/f09bdad8-cebd-4fb1-92b8-c3a855ad91fa)
![Screenshot_10](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/40311e1a-5fae-4f9c-8c1d-d0b73df0718a)
![Screenshot_11](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/ebecbb40-9808-40ef-9aa4-7187f95785d4)
![Screenshot_12](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/82afa9ff-1c90-41f9-84db-4c7a9a3199c7)
![Screenshot_13](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/36cac5c4-b9ca-4377-8bc6-72d7e8d71f12)

**Comment by Misclick2** [comment]
edit : You can pretty much go over any invisible wall around ds. 
![Screenshot_18](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/03c737ed-6d5e-4d7b-b40a-744ad53ae4e2)
![Screenshot_19](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/91fc7fac-13ea-4da8-a552-7a367ac3c0f0)
![Screenshot_20](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/07dbaefb-162c-4080-ab29-9dfca900648d)
![Screenshot_22](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/f1350637-262f-427a-96a2-c3fcf4576831)

**Comment by UltraNix** [comment]
Won't fix - blizzard did not finished textures for the rest of the raid.
Heroic Leap (and similar spells) do not check non-wmo files to check LoS.
