### ISSUE TITLE
[MPG] Dead npc's but interactable? 

### ISSUE THREAD

**Issue by Misclick2** [gamefreedomgit/Maelstrom#5264]
Character name - Rott

https://www.wowhead.com/npc=27943/dalormi ( dalormi used as npc for the example )
**Description:**
As the title says, the npc's are dead in the wyrmrest temple but still interactable (screenshots provided)
IMO minor bug 

**How to reproduce:**
Walk in wyrmrest temple in dragon soul ( no bosses killed )
![Screenshot_16](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/d629116c-3191-4e01-bd7e-ae50b5f08375)

**How it should work:**
They should be alive or dead and non - interactable

**Database links:**
![Screenshot_17](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/ab58419d-447b-4bd0-be07-043b32257584)

**Comment by Potatwowo** [comment]
You need to wait for the npcs from the entrance in DS to arrive to the temple, they will res them

**Comment by Misclick2** [comment]
> You need to wait for the npcs from the entrance in DS to arrive to the temple, they will res them

I'm aware of that but you shouldn't be able to interact with them while they are dead, its a very minor thing but I guess a bug is a bug

**Comment by UltraNix** [comment]
Fixed.
