### ISSUE TITLE
warmaster DXE BUGGING

### ISSUE THREAD

**Issue by blackmazes** [gamefreedomgit/Maelstrom#5267]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
![image_2023-12-21_004655664](https://github.com/gamefreedomgit/Maelstrom/assets/154478268/86a3e979-db72-40fd-aba8-b626dcbeac3f)

[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**
when warmaster spawn DXE KEEEPS SPAMING its shouldnt be like that

**How it should work:**
when warmaster spawn DXE KEEEPS SPAMING its shouldnt be like that

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by Revly** [comment]
Phase 2 still Spam in Dxe 🥹
