### ISSUE TITLE
[MPG] Spellwave doing dmg to main target (madness of deathwing)

### ISSUE THREAD

**Issue by Firebenderz** [gamefreedomgit/Maelstrom#5271]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:) 
[//]: # (http://wowhead.com/) https://www.wowhead.com/spell=106039/spellweaver
[//]: # (cata-twinhead.twinstar.cz) https://cata-shoot.tauri.hu/?spell=106039

**Description:** Spellweaver doing dmg unitarget when should do aoe dmg without main target 
Guide Description : https://imgur.com/a/sBm4TUr

Probs: https://imgur.com/a/VypAkrA (first target: main wing without bloods near, Second wing without bloods near, Mutated Corrupcion dies before bloods so he should no take dmg)

**How to reproduce:** Just hitting with habilities to see spellweaver doing dmg

**How it should work:** When u hit with spells u have a % to proc a aoe dmg but the main target dont take dmg, so spellweaver doing 40-50% on all classes on deathwing making a easy fight

**Database links:** https://www.wowhead.com/npc=56173/deathwing#comments 
https://www.wowhead.com/spell=106040/spellweaving#comments

**Comment by UltraNix** [comment]
Fixed.
