### ISSUE TITLE
DS-Spine of Deathwing-Invisible wall

### ISSUE THREAD

**Issue by flyingevelyn** [gamefreedomgit/Maelstrom#5273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the 10-raid, we meet invisible wall after killing the first Burning Tendons. We can not move further.

**How to reproduce:**

Only found in the 10 normal run.
**How it should work:**
After killing the first burning tendons, the armor plate shall be removed and the players can move forward to kill the next one.

**Database links:**

https://www.wowhead.com/npc=53879/deathwing

**Comment by Waroxx-QA** [comment]
Duplicate #5262
