### ISSUE TITLE
Assasinate Creed not working properlly

### ISSUE THREAD

**Issue by Skurten** [gamefreedomgit/Maelstrom#5274]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/quest=30093/assassinate-creed
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?quest=30093

**Description:**
Not getting teleported out while flying over. and other times adds wont teleport me out.

**How to reproduce:**
No cue

**How it should work:**
Adds should teleport you out some of them dont
And i do not think its intended that you could just fly in there and kill Lord hiram creed

**Database links:**
![bugreport](https://github.com/gamefreedomgit/Maelstrom/assets/146117505/d578adc2-bb08-4a6b-823f-b0065efc35b3)

https://www.wowhead.com/quest=30093/assassinate-creed

**Comment by Skurten** [comment]
sketish i just wanted to send a Screenshot so i saw it ^^

**Comment by UltraNix** [comment]
Fixed.
