### ISSUE TITLE
DS incomplete mob respawn

### ISSUE THREAD

**Issue by Firokash** [gamefreedomgit/Maelstrom#5277]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154538052/9511e97b-088f-46a2-a27b-5d58c3cbea50)

**Description:**
mobs don't fully respawn

**How to reproduce:**
down some bosses, leave, come back later, less mobs

**How it should work:**
down some bosses, leave, come back later, more mobs

**Database links:**

**Comment by Waroxx-QA** [comment]
No, adds should disappear after killing Morchok.

**Comment by UltraNix** [comment]
Fixed.
