### ISSUE TITLE
[MPG] DS: Spine Amalgamation issue

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5278]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**Description:**
If Amalgamation explodes  even in the center of platform it triggers plate

**How it should work:**
 It should trigger plate only if Amalgamation explodes near by plate

**Comment by UltraNix** [comment]
Fixed.
