### ISSUE TITLE
[MPG] DS: Spine teleportation issue

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5280]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**Description:**

When spine is dead it doesn't teleport all members of group on madness platform ( Some may be stuck on spine )

**How it should work:**

All members of raid party should be teleported into madness platform when spine is dead

**Comment by UltraNix** [comment]
@vanarenan Cannot reproduce it. Were these players (that are not got teleported) were inside instance? Were dead or alive? They got the cinematic?

**Comment by vanarenan** [comment]
So we all were alive and on spine when we killed 3-rd plate, but for 2 of us was no cinematic and no teleportation, even after reloging we(2/10 players) ramained on spine with no combat. We had to die manually and use portal by ourselfes instead

**Comment by UltraNix** [comment]
Fixed.
