### ISSUE TITLE
DS Yor'sahj Trash mobs broken

### ISSUE THREAD

**Issue by Kireq** [gamefreedomgit/Maelstrom#5281]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After we died on trash blobs before Yor - blobs that killed us - changed the route. Now they don't run in a circle around, but turn to the place where the group died/pulled. (in our case it happened under the blue portal). Also now their camp was bigger than should be (after wipe they have to reset and run in grps of 3)

**How to reproduce:**
Try do aggro 3 packs of blobs and die near blue portal

**How it should work:**

Blobs should always have same route and be in same size packs.
**Database links:**
no database for trash mobs.

Reported by: Snusei (guild: New Day)

**Comment by Kireq** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/86050732/36f628fe-2742-4383-9a81-0f71ff6fd837)

**Comment by Misclick2** [comment]
Reported this already also u used my screenshot lol

**Comment by Kireq** [comment]
yep np i deleted/ just want them to notice error  21.12.2023, 21:30, "Misclick2" ***@***.***>: Reported this already also u used my screenshot lol—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Kireq** [comment]
we make a bigger report. Not only about camp
