### ISSUE TITLE
[MPG] Adds before Hagara

### ISSUE THREAD

**Issue by Misclick2** [gamefreedomgit/Maelstrom#5282]
In game name : Rott

**Description:**
Adds provided in screenshot should all be pulled on start of combat not only one pack of 3

**How to reproduce:**
Pull one pack off adds only

**How it should work:**
They all should be pulled at start of combat no matter what pack is pulled

**Database links:**
![Screenshot_3](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/6a98d1ec-2c42-490f-b199-9da2b499d4a8)

**Comment by UltraNix** [comment]
Fixed.
