### ISSUE TITLE
[MPG]  Ultraxion has no BACK!

### ISSUE THREAD

**Issue by Kireq** [gamefreedomgit/Maelstrom#5283]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Ultraxion boss:

Unable to use Garrote and Backstub for a rogue 

**How to reproduce:**
Try to use these spells

**How it should work:**

the boss face here should count as the boss's back
**Database links:**
![NO BACK](https://github.com/gamefreedomgit/Maelstrom/assets/86050732/ca9a755f-e1d9-4536-b262-9340d207d06b)

**Comment by Waroxx-QA** [comment]
This was possible on PTR, but never on live ( retail )
that's why rogues were playing combat.
