### ISSUE TITLE
[MPG] Hagara the Stormbinder ice/frost phase 

### ISSUE THREAD

**Issue by Misclick2** [gamefreedomgit/Maelstrom#5284]
In game name : Rott

**Description:**
The ice walls circled in red move way to fast , and going in the purple circled zone to avoid them you take way too much dmg 

**How to reproduce:**
Do the fight and you will notice the above mentioned

**How it should work:**
Walls should move slower and going in purple marked zone on screenshot shouldn't make your character take that much damage (dmg shown in second screenshot)
![Screenshot_5](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/1ac106cc-d323-4d3f-8705-c332d77f0cca)
![Screenshot_6](https://github.com/gamefreedomgit/Maelstrom/assets/154470865/e765ce64-d778-48ff-94b6-ce03a2044ba8)

**Database links:**

**Comment by Waroxx-QA** [comment]
Already reported and fixed. it will be working properly after the next update
