### ISSUE TITLE
[MPG] Hunter's range Ultraxion

### ISSUE THREAD

**Issue by Kireq** [gamefreedomgit/Maelstrom#5285]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Hunter can't stand with everyone in the same group on Ultraxion, because he can't shoot closer, and at that distance the hits couldn't get him. He had to stand in the spot on the screenshot.  He couldn't shoot any closer.
**How to reproduce:**

**How it should work:**
Should still be possible to attack much closer to boss

**Database links:**

![изображение_2023-12-21_222944468](https://github.com/gamefreedomgit/Maelstrom/assets/86050732/ef79d7ec-b49e-40b3-bc58-e45548fc2ff5)

Reported by: Snusei (New Day guild)

**Comment by UltraNix** [comment]
Fixed.
