### ISSUE TITLE
[MPG] Zon'ozz going evade mode 

### ISSUE THREAD

**Issue by Pearstache** [gamefreedomgit/Maelstrom#5288]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Once void orb is out of the area Zon'ozz used [Black Blood Eruption](http://cata-shoot.tauri.hu/?spell=108799) then left us on evade mode till death

**How to reproduce:** Just let the orb going to walls

**How it should work:** No evade mode after Black Blood Eruption spell should still be killable (or dont let the orb going out)

**Database links:**

**Comment by UltraNix** [comment]
@Pearstache I can't reproduce it, so need more info on it. It was your 1. void? How many stacks applied?

**Comment by Pearstache** [comment]
It was the second orb, no stack, hitting the wall straight

**Comment by UltraNix** [comment]
Still cannot repro. It happened only once? It is something you can easily replicate?

**Comment by UltraNix** [comment]
@Pearstache @vanarenan Somebody is able to record that bug?

**Comment by Pearstache** [comment]
Hi ! we didn't get to fight Zon again but i will if the bug happens again

**Comment by UltraNix** [comment]
@Pearstache I believe it can be closed?

**Comment by vanarenan** [comment]
Never happened again neither in normal or heroic modes, so we fine now, ty
