### ISSUE TITLE
DS: Lord Devrstrasz

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5289]
Ingame name: Xonacylver

Description:

This NPC should only have this dialogue, when the DS in the future adds ease with the debuff in the Raid to the "Presence of Aspects" enemies

![repordampoening](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/d323c80a-b649-49b8-9ce4-e6ef70423549)

This NPC should not have this Dialogue, since it lends itself to misunderstandings or other things.

You can get all the information in the Comments in English

How to reproduce:

Currently the dialogue appears on the NPC, but during the Raid the debuff is not there (possibly they should also fix this), they can add the dialogue and the debuff in the Future

How it should work:

While you are doing Progressively, you shouldn't have that Dialogue

Database links:

https://www.wowhead.com/es/search?q=poder%20de%20los%20aspectos
https://www.wowhead.com/es/spell=109251/poder-de-los-aspectos#english-comments
https://cata-twinhead.twinstar.cz/?search=Aspects#spells
https://cata-twinhead.twinstar.cz/?spell=109251

**Comment by Sketish** [comment]
Yes there is still this option when you talk to npc but this buff is disabled and wont be live.

**Comment by UltraNix** [comment]
Fixed.
