### ISSUE TITLE
Warmarster ADDS

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5290]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**warmaster ADDS

**How to reproduce:** charges are really bugged , they'r doing "zigzag".

**How it should work:** should to the charge in a straight line.

**Database links:**

**Comment by Sketish** [comment]
Already fixed - check Changelog
