### ISSUE TITLE
Madness head

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5291]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Madness head

**How to reproduce:** The madness head take all the plateform (wrong position).

**How it should work:** madness  phase 2 the head didn't touch the platforme (fixing postion of the head on the platform)

**Database links:**

**Comment by Sketish** [comment]
already fixed, just need update on main realm
