### ISSUE TITLE
Ultraxion debuffs and damage (heroic mode ptr).

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5293]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Ultraxion damage during the debuffs.

**How to reproduce:** ultraxion don't do damage when  he put buffs on players (heroic mode).

**How it should work:** ultraxion need to do damage (aoe dmg) when he put the debuffs on players.

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/dbbfbfbe-6c34-4f66-b24c-02a62e08ebd9)
Works okay everything here as long as the player is inside Twilight Realm.
