### ISSUE TITLE
Yorshaj trash adds.

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5294]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Yorshaj trash adds.

**How to reproduce:** Yorshaj trash adds stay together and run together so u can not pull pack by pack. 

**How it should work:** the packs need to be separated

**Database links:**

**Comment by Sketish** [comment]
Fixed already, waiting for update on main realm
