### ISSUE TITLE
Morchok heroic PTR

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5295]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Morchok heroic PTR

**How to reproduce:** you can cast things behind the pilars

**How it should work:** you can't cast spells (wallcast) behind the pilars.

**Database links:**

**Comment by Sketish** [comment]
https://www.youtube.com/watch?v=esfyEktOn9w&ab_channel=Luk%C3%A1%C5%A1S%C3%BDkora
You can cast if you stay between 2 pillars

**Comment by Strato12345** [comment]
i'm not talking CAST between 2 pillars, i said behind the pillar.

**Comment by UltraNix** [comment]
@Strato12345 Shou us some screenshots from your positioning on the encounter.

**Comment by Strato12345** [comment]
i didn't take a picture cause it was on PTR test  (for the 350 ember coins) with neon on group and waroxx and on vocal warox said (yes i know that bug).
so i reported here after one week ,  u are free to check it by yourself :) i'm not going to PTR anymores.

**Comment by UltraNix** [comment]
I can't reproduce it - that's why I'm asking for more details.

**Comment by UltraNix** [comment]
@Strato12345 I believe it can be closed?

**Comment by Strato12345** [comment]
yes you can ^^
