### ISSUE TITLE
Hagara wall forst phase

### ISSUE THREAD

**Issue by Strato12345** [gamefreedomgit/Maelstrom#5296]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Hagara wall forst phase

**How to reproduce:** we can not dodge the wall in the frost phase and he have a big hitbox.

**How it should work:** you can dodge it when you enter on the bubule without getting damage by the wall inside.

**Database links:**

**Comment by Sketish** [comment]
Fixed already, waiting for update on main
