### ISSUE TITLE
Madness warrior bug

### ISSUE THREAD

**Issue by freakyfrizes** [gamefreedomgit/Maelstrom#5298]
Charging on the impaler is charging me to the other plateform without even being on the edge
Character name : Zalame

**Comment by UltraNix** [comment]
@freakyfrizes What do you mean by "impaler"?

**Comment by freakyfrizes** [comment]
@UltraNix the Tentacle that spawns in every platform that at the back called "mutated corruption"  which players have to switch to and kill . Using charge on it sometimes is sending me to oblivion into another platform

**Comment by Waroxx-QA** [comment]
impaler is the corruption

**Comment by freakyfrizes** [comment]
@Waroxx-QA it happend to me at the last platform right side

**Comment by UltraNix** [comment]
Fixed.
