### ISSUE TITLE
[MPG] DS: Hagara tombs

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5299]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**How to reproduce:**
If there are any players inside ice tombs right before boss is dead they are not disappearing after killing boss.

**How it should work:**
They should disappear right after boss death (at least it is how I remember it was in previous servers I played before).

**Comment by Waroxx-QA** [comment]
Not a bug unless you get proof from retail.

**Comment by UltraNix** [comment]
Waiting for update.

**Comment by UltraNix** [comment]
Fixed.
