### ISSUE TITLE
[MPG] DS: Yor'sahj the Unsleeping

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5301]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Exhunter

**Description:**
Issue with trash before boss

**How to reproduce:**
If you pull all trash ( or few packs ) and all member dies then this trash will go around all together 
(screenshot: https://ibb.co/3FP5cbz)

**How it should work:**
Trash should move around separate (in packs of 3), not all together

**Comment by Sketish** [comment]
Already fixed, waiting for update
