### ISSUE TITLE
[MPG] Hour of Twilight resist

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5302]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

You can resist the HoT from Ultraxion

**How to reproduce:**

Take damage form the HoT and see that you resisted some
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/a6989e08-06b4-4e18-b4f2-103459bc02cb)

**How it should work:**

Should not be resistable

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/1da17a37-58b1-42f9-aa32-c1ef459fe935)

https://www.wowhead.com/spell=106371/hour-of-twilight#changelog

**Comment by UltraNix** [comment]
Fixed.
