### ISSUE TITLE
[MPG] Hunter deterrence vs Hour of Twilight (Ultraxion)

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5303]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

 Hunter deterrence is not working against HoT

**How to reproduce:**

Take HoT with deterrence up

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3a9d569d-c071-4da6-816f-7c937b364470)

**How it should work:**

Hunter should not take any damage from HoT with Deterrence up

https://youtu.be/5urPbK9hNlw?t=170

**Database links:**

https://www.wowhead.com/spell=106371/hour-of-twilight#changelog
http://cata-shoot.tauri.hu/?spell=19263

**Comment by Sketish** [comment]
It should only work if hunter has talent Mirrored Blades. Did you have it ?

**Comment by Polynomix** [comment]
No but doesn't matter, in the video the hunter is MM, so he doesn't have this talent either.

**Comment by Polynomix** [comment]
@Sketish I'm curious on what you were basing your affirmation that it needed this talent to work ? Can you link me where you saw that ?

**Comment by Sketish** [comment]
I just missread talent, I thought it allows to deflect spells

**Comment by UltraNix** [comment]
Fixed.
