### ISSUE TITLE
DS : Ultraxion

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#5304]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Normally, there are two phases of debuff called "Falling Light" before the time of twilight

**How to reproduce:**
Pull boss

**How it should work:**
2 phase unbuff before time of twilight

**Database links:**

**Comment by Sketish** [comment]
Already fixed, waitign for update on main
