### ISSUE TITLE
[MPG] CoS vs Void orb on Zon'ozz

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5305]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Took damage from void orb while under CoS in nm.

**How to reproduce:**

Hit the ball with CoS up in normal mode
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/182c622f-35f9-41d6-b6c1-8dd5acada6bd)

**How it should work:**

In nm CoS should negate damage of the void diffusion.
In hc Cos should negate damage of the void diffusion for the first second of the CoS
Zon'ozz section : http://web.archive.org/web/20120525042200/http://elitistjerks.com/f78/t126818-cataclysm_4_3_x_raid_mechanics

**Database links:**

**Comment by Sketish** [comment]
CoS, provide immune for 1 sec, from your screenshot it took longer than 1 sec. Not a bug

**Comment by Polynomix** [comment]
@Sketish  Can you read what i wrote and the source also ? Its different in normal and heroic

**Comment by Sketish** [comment]
I think we wont be changing that, it will be same for norm and hc.
