### ISSUE TITLE
[MPG] DS: Morchok

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5306]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**How to reproduce:**
Very big stomp radius

**How it should work:**
Normally radius of stomp is smaller so all member of raid party should be closer to boss in order to split damage

**Comment by Sketish** [comment]
It's 25 yards so need screenshot of whole raid position

**Comment by vanarenan** [comment]
WIll try to make some

**Comment by vanarenan** [comment]
Indeed, 25 yards.
Can be closed.
