### ISSUE TITLE
Hunters min range

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5307]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Basically it is more an offer for a feature then issue.
I offer to remove hunters min range at least for such bosses as Ultra/Yor'sahj. 
Had such feature on previous server and it was lovely.
But I guess it is not exactly changing hunters mechanic but bosses hitbox.

**Comment by Sketish** [comment]
Its suggestion, not a bug
