### ISSUE TITLE
[MPG] Trash before Hagara

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5312]
Trash before Hagara should cast their spells more often

Twilight Frost evoker is a Mage, shouldn't melee / move to her target unless you interupt her ( she stops casting for few seconds so she does melee damage for 2-3s then cast again following her rotation, players interrupt so she moves to her target ) Her rotation should be like this : Frostbolt x2 > Shackles Of Ice > Frostbolt x2 > Blizzard...

Stormbinder Adept should cast Tornado earlier.

Stormborn Myrmidon should cast Chain Lightning and Spark more often. ( between X melee damage, couldn't find any numbers )

**Comment by UltraNix** [comment]
Fixed.
