### ISSUE TITLE
[MPG] Hagara - Frost Phase : Ice Wave

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5313]
Frost Phase - Ice Wave should be faster, based on retail videos 9s for a 90° ( from a crystal to another one )

**Comment by UltraNix** [comment]
https://youtu.be/RxChXHBVbwU?t=177
https://youtu.be/RxChXHBVbwU?t=216

https://youtu.be/pikRzhR8Ibo?t=95
https://youtu.be/pikRzhR8Ibo?t=134

~40 sec for full run - just like on our server.

**Comment by Waroxx-QA** [comment]
Based your video it's 36-37s for a full run, check it again 😅
