### ISSUE TITLE
[MPG] Hagara weapon enchants

### ISSUE THREAD

**Issue by Potatwowo** [gamefreedomgit/Maelstrom#5314]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hagara is having diffrerent enchants on her weapons as shown in the video. 
https://youtu.be/FoaA-hFHODk

This way it is not able to indicate which phase will be first.

**How to reproduce:**
Observe Hagara after clearing the trash.

**How it should work:**
Hagara weapons should have same weapon enchants on both weapons and the enchants are corresponding to the phase that will follow after. For example as seen in the video https://youtu.be/jABnOkUfVMY?t=20 the lightning enchant is there on both weapons and the first phase is lightning phase.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/8541d3fc-5e19-4e1a-97d4-248e158e751d)

**Database links:**
https://www.icy-veins.com/wow/hagara-the-stormbinder-strategy-guide-normal-heroic

**Comment by Waroxx-QA** [comment]
Already fixed, it will be up by the next update.
