### ISSUE TITLE
[MPG] DS: Madness charge

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5316]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Ingame name: Mishka

**How to reproduce:**
When you try to cahrge as cat (at least as cat, I believe as warrior as well) into Arm Tentacle it drops you under textures

**How it should work:**
Well it shouldn't do that, even considering you charge behind back it is a bug

**Database links:**

**Comment by Waroxx-QA** [comment]
Warrior charge is fine.

**Comment by vanarenan** [comment]
> Warrior charge is fine.

Yep, my bad, warriors are not charging behind targets back. But there is still an issue with cat's one.

**Comment by UltraNix** [comment]
Fixed.
