### ISSUE TITLE
Health stone crit

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5318]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After the fix, nothing changed. Does not work .

Author: afgann
Message: Core/Spell: Healthstone will be able to crit.
https://github.com/gamefreedomgit/Maelstrom/issues/5003

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
tested with 130% crit chance on ptr, confirmed

**Comment by UltraNix** [comment]
Fixed.
