### ISSUE TITLE
[MPG] killing spree / Shadowstep Arm of madness of deathwing

### ISSUE THREAD

**Issue by Firbael** [gamefreedomgit/Maelstrom#5319]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When killing spree'ing the elementium bolt ocne in range Killing spree can sometimes latch onto the arm and then drop you off the side. Same when shadowstepping the arm

**How to reproduce:**Cast Killing spree once the the elementum bolt is in range and targetable- As it moves away its a 50/50 chance it will stay on the arm and then drop you from the side. (conformed on the Nozdormu platform for sure Not tested on other platforms yet but does work normally on Ysera and Alex platforms SO far)

**How it should work:** Killing spree should keep target when cast Without Blade flurry + Should keep you on the edge and not drop you from the platform. 

**Database links:** Stabit

**Comment by bonfax4** [comment]
Killing spree +  bladeflurry interaction you're thinking about is a mop mechanic. They simply just added spots where killing spree will send you in most encounters to avoid those issues.

Is Killing spree against spine tendon working properly btw ?

**Comment by Firbael** [comment]
Not something I tried to do unfortunatly

**Comment by UltraNix** [comment]
Fixed.
