### ISSUE TITLE
[MPG] Pressing Dream on ultraxion before pulled

### ISSUE THREAD

**Issue by Firbael** [gamefreedomgit/Maelstrom#5320]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Pressing Dream before the boss is pulled can phase you from the party before combat is started and does not put you back into the "normal" realm

**How to reproduce:**Press the button before combat starts

**How it should work:**Pressing the button even out of combat should still drop you back into the normal realm

**Database links:**Stabit

**Comment by Warlorc** [comment]
You should not have a button at all, heroic will is granted when entering the shadow realm which happens after the event.

**Comment by UltraNix** [comment]
Fixed.
