### ISSUE TITLE
[MPG] Cloak of shadows VS Hour of twilight

### ISSUE THREAD

**Issue by Firbael** [gamefreedomgit/Maelstrom#5321]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Hour of twilight should still be negated by cloak of shadows as this was how the retail version should be done.
As well as not killing you it should still count as a player "hit" by hour of twilight and not cause Twilight eruption

**How to reproduce:**Having Cloak of shadows up just before HoT.

**How it should work:**[](https://www.youtube.com/watch?v=Zb1_0OLXBPc) First HoT CoS is used- Negated and counted as a person "hit" by HoT

**Database links:**Stabit

**Comment by Waroxx-QA** [comment]
With CoS Hour of twilight shouldn't kill you but it counts as a hit, you don't get the HoT debuff, and it removes it if you already have it, right ?

**Comment by Firbael** [comment]
i cant say ive even seen the debuff once on Normal mode, i can faint every HoT, but yes it shouldnt kill me AND count as a player "hit" by HoT

**Comment by bonfax4** [comment]
> With CoS Hour of twilight shouldn't kill you but it counts as a hit, you don't get the HoT debuff, and it removes it if you already have it, right ?

No. Cloak just nullifies dmg. You can't remove the HC debuff with it or stop it from being applied and if you try to cloak soak with the debuff, it should still insta kill you.

**Comment by Firbael** [comment]
so yes the debuff for HC should kill you regardless of cloak, but you should be able to tank one HoT with cloak on normal or hc with clock (yes hc you will get the debuff regardless, but the current issue is that you just die on normal when tanking HoT with cloak https://www.youtube.com/watch?v=Zb1_0OLXBPc < how cloak should work

**Comment by Polynomix** [comment]
You can cloak the hour of Twilight in normal right now

**Comment by Revly** [comment]
CoS yes remove debuff HoC

**Comment by UltraNix** [comment]
Fixed.
