### ISSUE TITLE
[MPG] DS: Killing-spree in Ultraxion

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5322]
Ingame name: Xonacylver

**Description:**

Currently it does not allow use, in ultraxion

**How to reproduce:**

is out of reach Ultraxion

![imagen_2023-12-23_225742879](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/1ab10c02-6f03-49fe-8acd-3efbb7302c8e)

https://github.com/gamefreedomgit/Maelstrom/assets/12503112/e1c5f437-5c63-40b2-80cd-063e1e35d12b

**How it should work:**

It should be allowed to be used and kept in the same position.

**Database links:**

https://www.wowhead.com/spell=51690/killing-spree
https://cata-twinhead.twinstar.cz/?spell=51690#reported-fixes

**Comment by UltraNix** [comment]
Fixed.
