### ISSUE TITLE
DS: Morchock  Cloak of shadows Vs Black blood of the earth

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5324]
Ingame name: Xonacylver
**Description:**

Maybe I'm wrong or not but
Morchok's Black Blood pierces the Cloak of Shadows' immunity.

1. The shadow cloak removed my charges of black blood, correct. ☑
2. The first tick after fading charges, he became immune to blood damage, ☑
3. And after that immune tick, he's giving me charges (✘)  and dealing damage again (✘) "while under the effect of Cloak of Shadows."

It should not be like that.

**How to reproduce:**

https://youtu.be/eC3AjSjcWbA

**How it should work:**

You should not get charges of the black blood of the earth (School Damage (Nature)) as long as the cape effect remains.

**Database links:**

https://www.wowhead.com/spell=31224/cloak-of-shadows
https://cata-twinhead.twinstar.cz/?spell=31224#issues
https://www.wowhead.com/spell=103785/black-blood-of-the-earth
https://cata-twinhead.twinstar.cz/?spell=103785

**Comment by Sketish** [comment]
https://youtu.be/OV68Ke4-QI0?t=91 invalid report
