### ISSUE TITLE
[MPG] DS: Trash Ancient Water Lord & Pure Water

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5325]
Ingame name: Xonacylver

**Description:**

During the DS Trash cleanup.
When you killed the Npc **<a href="https://www.wowhead.com/npc=57160/ancient-water-lord" rel="nofollow">Ancient Water Lord</a>**, it grants a Buff to the raid at the place where the NPC died and lasts 2 minutes **<a href="https://cata-twinhead.twinstar.cz/?spell=107780" rel="nofollow">Pure Water</a>**

This serves to make cleaning faster, and also not have a debuff from **<a href="https://www.wowhead.com/spell=107677/dust-storm" rel="nofollow">Dust Storm</a>** from **<a href="https://www.wowhead.com/npc=57158" rel="nofollow">Earthen Destroyer</a>**

**How to reproduce:**

![WoWScrnShot_122323_201017](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/b7b88a8c-e579-4f88-8867-10f85f97c11c)
![WoWScrnShot_122323_201012](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/cdcf11ea-933f-428e-b39d-8b135a02b05b)

Currently this is not happening

**How it should work:**

Npc <a href="https://www.wowhead.com/npc=57160/ancient-water-lord" rel="nofollow">Ancient Water Lord</a> it should grant a Buff to the raid at the location where the NPC died and lasts 2 minutes.

**Database links:**

https://cata-twinhead.twinstar.cz/?npc=57160#abilities
https://cata-twinhead.twinstar.cz/?spell=107780
https://www.wowhead.com/npc=57160/ancient-water-lord
https://www.wowhead.com/spell=107770/pure-water

**Comment by UltraNix** [comment]
Fixed.
