### ISSUE TITLE
[MPG] DS: Hagara no cast Shattered-ice

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5326]
Ingame name: Xonacylver

**Description:**

I have realized that he is doing this using this skill very little.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/1fc7cbff-c8bf-4552-8afb-a07033036c4d)

**How to reproduce:**

During the encounter with Hagara, he uses very little **<a href="https://www.wowhead.com/spell=105289/shattered-ice" rel="nofollow">Shattered Ice</a>**
**<a href="https://youtu.be/PdjAgD2lPlU " rel="nofollow">ATM</a>**

**How it should work:**

Hagara should use **<a href="https://www.wowhead.com/spell=105289/shattered-ice" rel="nofollow">Shattered Ice</a>**, after using **<a href="https://www.wowhead.com/spell=206891/focused-assault?dd=1" rel="nofollow">Focused Assault</a>**
**<a href="https://youtu.be/v4gz0lBgRiE?t=55" rel="nofollow">This is Hagara H</a>** But the pattern of Shattering Ice is almost the same.

**Database links:**
https://www.wowhead.com/npc=55689/hagara-the-stormbinder

https://www.wowhead.com/spell=105289/shattered-ice
https://cata-twinhead.twinstar.cz/?spell=105289

**Comment by Waroxx-QA** [comment]
Without retail proof we won't take it into consideration 😅

**Comment by Revly** [comment]
> Without retail proof we won't take it into consideration 😅

In my opinion it would be very easy, if "Hagara" doesn't use it more often

**Comment by Revly** [comment]
I have seen other Hagara Normal Videos (non-retail)
But I do see that he uses Shattered Ice more than once.

**<a href="https://youtu.be/qRl4jj8XuyE?t=8" rel="nofollow"> Example 1 (10 man)</a>** 
**<a href="https://youtu.be/jABnOkUfVMY?t=17" rel="nofollow"> Example 2 (25 man)</a>** 
**<a href="https://youtu.be/y-v0Xn6A73w?t=15" rel="nofollow"> Example 3 (10 man)</a>**

**Comment by UltraNix** [comment]
Fixed.
