### ISSUE TITLE
[MPG] Shadowflame vs Ultraxion/Madness

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#5328]
Ultraxion cannot be affected by Shadowflame.
The same thing happens with some limbs and the head of "Madness".

**How to reproduce:**
Go to a Warlock and use Shadowflame on Ultraxion, also use it on "Madness's" limbs and head.

**How it should work:**
Shadowflame has a 180 degree angle and a range of 100 yards, so it should affect everything within 100 yards of it.

**Database links:**
https://cata-twinhead.twinstar.cz/?issue=9779
https://www.wowhead.com/npc=56173/deathwing/normal-10-encounter-journal
https://www.wowhead.com/npc=55294/ultraxion

Character name: Tactikal

**Comment by UltraNix** [comment]
Just tested on Ultraxion - works okay.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/fd387271-1402-42fa-9789-84b3dc45942e)
Need more info on it or I will close it.

**Comment by DartImpact** [comment]
I imagine it was fixed because of this:
Author: Ultranix
Message: Scripts/DragonSoul: Fixed engaging Ultraxion from ranged spells. 

Have you tried it on Deathwing's head and limbs? I remember it didn't work on his head and some limbs.

**Comment by UltraNix** [comment]
I will test it.

**Comment by UltraNix** [comment]
Tested on Madness - all tentacles and head. Works okay - just staying on Nozd bubble. Remember it's only 10y.
