### ISSUE TITLE
[MPG] Madness 

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5333]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
In game name: Exhunter

**Description:**
If Mutated Corruption has no target or was retaunted right before Impale, then it start casting it on current Aspect. Seems about right, but Impale does not deal any damage to the Aspect. 
Screenshots below:
(https://ibb.co/2hJbPCX, 
https://ibb.co/DKYSCNL)

**How it should work:**
If Mutated Corruption's Impale directed on Aspect then it should damage it

**Comment by UltraNix** [comment]
Fixed.
