### ISSUE TITLE
Quest bug: [The Mist Isn't Listening]

### ISSUE THREAD

**Issue by Haltus-Kain** [gamefreedomgit/Maelstrom#5334]
**Description:**
WotLK | Scholozar Basin | Quest | [The Mist Isn't Listening]
Cannot attack quest kill objectives (Mistwhisper Warrior, Mistwisper Oracle). They appear red, but do not engage in combat. Cannot toggle the "At war" box in the rep panel.

This quest is a necessary chain for several achievements and a mount.

**How to reproduce:**
Start quest

**How it should work:**
The Oracles should be at war and attackable at this stage.

**Database links:**
https://warcraft.wiki.gg/wiki/The_Mist_Isn%27t_Listening

![image](https://github.com/gamefreedomgit/Maelstrom/assets/87287845/82da63b1-d438-41e6-bc7d-5c426ca43513)
Attempted normal attacks, AoE, and sending pet to attack - none worked.

**Comment by PanJanuszek** [comment]
fixed 18.03.2024
