### ISSUE TITLE
[MPG] DS: Spine HC/spawn amalgamation 

### ISSUE THREAD

**Issue by raxidozec** [gamefreedomgit/Maelstrom#5335]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Instantly spawn Amalgamation(https://www.wowhead.com/npc=53890/hideous-amalgamation) after kill Corruption(https://www.wowhead.com/npc=56162/corruption#abilities;mode:h10)

**How to reproduce:**
Just need to kill Corruption(https://www.wowhead.com/npc=56162/corruption#abilities;mode:h10)

**How it should work:**

https://youtu.be/CpBYiJzt2AI?t=53
So u can see after kill Corruption(https://www.wowhead.com/npc=56162/corruption#abilities;mode:h10) 
1) 3s after kill Corruption, animation Corruption finished
2) then Amalgamation(https://www.wowhead.com/npc=53890/hideous-amalgamation) spawned 
3) 5s after kill Corruption, Amalgamation(https://www.wowhead.com/npc=53890/hideous-amalgamation) activated

**Database links:**

**Comment by UltraNix** [comment]
#4629
