### ISSUE TITLE
quest npc

### ISSUE THREAD

**Issue by Just-Fir4s** [gamefreedomgit/Maelstrom#5336]
**Description:**
i cant complete the quest "Sins of the sea witch" i cant find the npc that i should find

**How to reproduce:**

**How it should work:**

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/69849816/856234a1-8a25-4a69-a50e-a56b0142cd13)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/45d6db56-df37-4f40-b8b2-8282778c31cd)
cannot reproduce
