### ISSUE TITLE
Blackhorn Shockwave visual missing SOMETIMES

### ISSUE THREAD

**Issue by Yuwusei** [gamefreedomgit/Maelstrom#5340]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # [(http://wowhead.com/)](https://www.wowhead.com/npc=56427/warmaster-blackhorn)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Blackhorns Shockwave did not have a visual when hitting me. This doesnt occur all the time. Just this one instance where it happend.
https://medal.tv/games/world-of-warcraft/clips/1L9QLzv2u-aOqF/d13379PFrDBq?invite=cr-MSxtcHgsMjU4OTU3NTMs

**How to reproduce:**
Not sure really since it doesnt always happen. Maybe it has something to do with the bossplacement and where it stood?

**How it should work:**
Should have a visual

**Database links:**

**Comment by UltraNix** [comment]
I'm afraid there's nothing I can do with that animation as it's completely clientside stuff.
