### ISSUE TITLE
[MPG][Warmaster Blackhorn] Skyfire Harpoon does not reload

### ISSUE THREAD

**Issue by Puttblug** [gamefreedomgit/Maelstrom#5341]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Warmaster Blackhorn]
The last Drake in Phase 1 was too far away. Harpoon Gun was not active nor was it possible to activate it somehow. We waited multiple sappers but we did not manage to kill the drake (due to range).

**How to reproduce:**
If you are too slow (you are not killing them fast enough) on Twilightdrakes the harpoon will pull the previous drake instead of the new one. So you can never reach that drake.

**How it should work:**
Harpoons should be infinite or at least recast it soon after. Right now you are limited to 3 harpoons on each side.

**Database links:**
https://www.wowhead.com/npc=56681/skyfire-harpoon-gun#abilities;mode:n10
https://www.wowhead.com/spell=108039/reloading (this one is not working!)

**Comment by Waroxx-QA** [comment]
![WoWScrnShot_122523_165116](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/0e714c2b-fba2-4b1c-8e1c-0874f4aefb3a)

**Comment by UltraNix** [comment]
Fixed.
