### ISSUE TITLE
[MPG] Madness - Elementium Bolt

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5344]
Elementium Bolt landing too close to the point where it's supposed to explode, giving just a short time for players to kill it, almost impossible for average / below average groups to do this.
[This is how it should work](https://youtu.be/xeAx7Y3itrU?si=YEKFS98zzxs_B8pp&t=62)

**Comment by UltraNix** [comment]
Fixed.
