### ISSUE TITLE
Warlock pets will not put owner into combat when attacking another player in PvP combat

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#5348]
https://youtu.be/A31by-UDoOE

How it is working right now - Pet will put the player into combat if attacking an NPC but not when the pet is sent to attack another player

How it should work - Pet combat should put the player in combat regardless of if the target is an NPC or not

**Comment by bonfax4** [comment]
@Waroxx-QA  Pvp behaviour is correct and was addressed already with proof in another issue https://github.com/gamefreedomgit/Maelstrom/issues/5086

**Comment by WhitemaneSylah** [comment]
@UltraNix Reopen the case, warlock pets and hunter pets do not function the same.  See below video from retail
https://www.youtube.com/watch?v=U255BI7HVKA

**Comment by SimonBpvp** [comment]
Can I add that also there is a bug where if someone casts a spell on your pet, you get combat

**Comment by UltraNix** [comment]
Fixed.
