### ISSUE TITLE
[MPG] Warmaster Blackhorn - Twilight Assault Drake

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#5350]
["Twilight Assault Drake"](https://www.wowhead.com/npc=56855/twilight-assault-drake) incorrectly deposits ["Twilight Elite Slayer"](https://www.wowhead.com/npc=56848/twilight-elite-slayer) on the ship.

**How to reproduce:**
In the encounter you can see how 2 dragons instantly place ["Twilight Elite Dreadblade"](https://www.wowhead.com/npc=56854/twilight-elite-dreadblade) and ["Twilight Elite Slayer"](https://www.wowhead.com/npc=56848/twilight-elite-slayer) on the ship, this should not work this way.
![Captura de pantalla 2023-12-25 181950](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/e89fc19d-63d3-4415-b151-831cdf162c85)

**How it should work:**
In this [video](https://youtu.be/zD_JtfP_tNA?si=hjCGKkDxUdbz8nhA) you can see how the dragon on the right of the ship takes a while to arrive and place "Twilight Elite Slayer", about 5-6 seconds later than the first dragon.

Apparently the error is in the dragon on the right, it has to take a little longer to appear and not cross paths with the first dragon.

Character name: Tactikal

**Comment by Waroxx-QA** [comment]
That's wrong, according to your video drakes are getting gripped at the same time, the last one flies out ( didn't get killed on the first harpoon ) so he was gripped again.

**Comment by UltraNix** [comment]
Fixed.
