### ISSUE TITLE
Quest Bug: [Surrender or Else!]

### ISSUE THREAD

**Issue by barukmcbaruk** [gamefreedomgit/Maelstrom#5352]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cataclysm | Lost Isles | Quest
The [Faceless of the Deep](https://www.wowhead.com/npc=38448/faceless-of-the-deep) in [Surrender or Else!](https://www.wowhead.com/quest=24868/surrender-or-else) is unattackable and despawns shortly after giving his speech, making the quest uncompletable and the Goblin start unfinishable

**How to reproduce:**
Launch [Surrender or Else!](https://www.wowhead.com/quest=24868/surrender-or-else) and go to the spawn point of the [Faceless of the Deep](https://www.wowhead.com/npc=38448/faceless-of-the-deep)

**How it should work:**
The Faceless of the Deep shouldn't despawn and should get in combat with the player instead

**Database links:**
[Surrender or Else!](https://www.wowhead.com/quest=24868/surrender-or-else)
[Faceless of the Deep](https://www.wowhead.com/npc=38448/faceless-of-the-deep)

**Comment by PanJanuszek** [comment]
Fixed
