### ISSUE TITLE
Quest Into the Fire ID 29206

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5354]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Аfter taking the яуест there is nothing i can do.
Abandoning the quest gives me other quest to finish but not this.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=29206/into-the-fire

**Comment by frostwave942** [comment]
probably someone else took the quest first and triggered the event
so if u want to complete it just pass through the fire even if u die and kill the firelord
or wait until those npcs kill him to reset the event.

**Comment by UltraNix** [comment]
As above.
