### ISSUE TITLE
Smoke Bomb vs Pet ai

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#5355]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently pets bug out when they try to use spells on targets thats inside / outside of the smoke bomb.
They just stand still and refuse to do anything.
Spell affected that i tested is Bad manner and Roar of sacrifice.

**How to reproduce:**
https://streamable.com/qzcndc
https://streamable.com/09vujt

**How it should work:**
Pets should automatically move in or outside of bomb when your pet use a spell.

**Database links:**

**Comment by Sketish** [comment]
Please provide retail video from cataclysm that will proof that they should move out automatically

**Comment by Kenniflopper** [comment]
I can try,, but this was not a thing 1 month ago, something you did broke this mechanic.

**Comment by Kenniflopper** [comment]
https://www.youtube.com/watch?v=J9kNEWD6egg 

9:09 his pet starts to move towards his priest thats in bomb and he gets roar of sacrifice.

This is the best i can find, i tried searching for better clips but i cant find it since cata has almost no clips on youtube

**Comment by Sketish** [comment]
That's good thanks for help!

**Comment by UltraNix** [comment]
Should be already fixed.
