### ISSUE TITLE
[Quest] The Twilight Flight

### ISSUE THREAD

**Issue by rfraess** [gamefreedomgit/Maelstrom#5356]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Zoltrik Drakebane is not despawning after unsuccessful attempts at the quest.

**How to reproduce:**
Start the quest "The Twilight Flight". Do not kill him while you are both flying on the drake. When you land on the floating rock at 50,38 you will get obliterated by a bunch of Zoltrik Darkbanes, making the quest impossible to complete without high damage. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/99368708/04bfa6b3-d63a-46ab-b820-204ed99d7ff2)

**How it should work:**
No other Zoltrik Darkbanes should exist on the floating rock so that you can finish fighting him to complete the quest.

**Database links:**
https://www.wowhead.com/npc=44135/zoltrik-drakebane
https://www.wowhead.com/quest=26831/the-twilight-flight

**Comment by UltraNix** [comment]
Fixed.
