### ISSUE TITLE
Ultraxion Fading Light Cast twice in the same target

### ISSUE THREAD

**Issue by Juan-9904** [gamefreedomgit/Maelstrom#5357]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description: When ultraxion Cast Fading Light in the main target sometimes it cast twice 

How to reproduce: Fading Light cast in the same target twice which make impossible for the player to survive

How it should work: It should be cast in two different targets so they can survive using heroic will

Database links: https://www.wowhead.com/spell=109075/fading-light

![imagen_2023-12-26_165150797](https://github.com/gamefreedomgit/Maelstrom/assets/64923048/e947612b-ad98-468f-bb40-041a1efa0dc0)

this is the dbm telling us that the chaman receive twice the fading light

**Comment by Sketish** [comment]
Did you had a full 10 man group ?

**Comment by Juan-9904** [comment]
Yes , we were in a 10 man group. It happens several trys it doesn't matter if all of us were alive or if one or two in our party were dead

**Comment by UltraNix** [comment]
@Juan-9904 Was the shaman the closest target during the cast?

**Comment by Juan-9904** [comment]
It happens in some trys and was always cast in the boss main focus, in this case the chaman was his focus. 
The ability should be cast in the main focus of the boss and in a random player. But sometimes the main focus receive the two faiding light

**Comment by UltraNix** [comment]
@Juan-9904 Should be okay after restart.

**Comment by UltraNix** [comment]
Fixed.
