### ISSUE TITLE
spellstealing hots

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5358]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when u spellsteal a hot from rdruid it doesn't give u the hot it only purges it from the target

**How to reproduce:**
get a rdruid to use wild growth/rejuv and try to spell steal it (mage)

**How it should work:**
remove the buff from target and put it on the player

Char Name: Brutestrengt

**Comment by UltraNix** [comment]
Fixed.
