### ISSUE TITLE
vanish 

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5359]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
#4284 
same issue from before, vanish immuning dmg spells

**How to reproduce:**
vanish while someone has a spell in the air

**How it should work:**
it should only immune roots and slows

Char Name:
Brutestrengt

**Comment by UltraNix** [comment]
@SimonBpvp Tested against warlock Shadow Bolt. Applied Vanish right before SB hit me - not immunity at all.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a6e8a237-4e19-402a-a711-e885d0240029)

**Comment by UltraNix** [comment]
No further info - closing.
