### ISSUE TITLE
[DS] Madness - Missing Shrapnel Debuff on Players/Raid UI

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5361]
Shrapnel from Elementium Fragment isn't showing debuff on targeted players, the debuff should appear on players and also in the raid UI. [Proof](https://youtu.be/6nDmhMtZLwk?si=jC-l_DhKAs2UUnIW) 0:15

**Comment by UltraNix** [comment]
Fixed.
