### ISSUE TITLE
quest A Hidden Message

### ISSUE THREAD

**Issue by acde00** [gamefreedomgit/Maelstrom#5362]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have a problem, my quest where I need to charge a ring, get a note and decrypt that very note got a bug. I got the ring, paid 10k gold and flew for the note, after getting the note and waiting for time, I decrypted the note and my ring disappeared. After completing the quest, I found that I failed the first item of the quest. now I can't do anything about it

**How to reproduce:**
dont know

**How it should work:**
as described above, I don't understand why it got the bug

**Database links:**
https://www.wowhead.com/quest=29802/a-hidden-message

**Comment by acde00** [comment]
Nickname Skoe

**Comment by Firbael** [comment]
Same issue, Stabit 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/136281996/ec839944-defe-4f3d-b97e-4479ac19cd6f)

**Comment by Waroxx-QA** [comment]
The ring has only 1H cooldown, should be 12h.
![Screenshot_2023-12-28-00-27-51-44_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/894a78bd-bf1b-40eb-ad1e-168daf479c18)

**Comment by Remainqxz** [comment]
This same quest doesn't work for me either.
Nickname Whocanstopme

**Comment by acde00** [comment]
Also you cant use re-forging because you havent completed the quest.

**Comment by UltraNix** [comment]
Fixed.
