### ISSUE TITLE
[DS] Madness - Impale Cooldown timer wrong

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5363]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Right now it has a 30s cooldown instead of 35s

**How to reproduce:**
 See how often the mutated corruption does impale

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/a36f6a0f-0322-43af-bcb9-e4d8b98a7cd0)

**How it should work:**
CD should be 35s

 https://www.youtube.com/watch?v=wMD1R2ODoOY
At 2m35 he gets first impale, at 3m10 he gets second

**Database links:** 

http://cata-shoot.tauri.hu/?spell=106400

**Comment by UltraNix** [comment]
Fixed.
