### ISSUE TITLE
[DS] Spine - Double absorb debuff (Searing Plasma)

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5364]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 We got 2 absorb debuff on the same player

**How to reproduce:**

Get lucky/unlucky i guess
 https://clips.twitch.tv/AbnegateDirtyAppleDxCat-lypyO_9zENLfGDtD

**How it should work:**

Should not target twice the same person

**Database links:**
http://cata-shoot.tauri.hu/?spell=109362

**Comment by UltraNix** [comment]
Fixed.
