### ISSUE TITLE
step stun

### ISSUE THREAD

**Issue by acde00** [gamefreedomgit/Maelstrom#5366]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
immunity stun effect for 2-3s

**How to reproduce:**
when you give a chipshot to a mage, the mage will blink if you quickly step and give him a kidneyshot. mage get immunity and dont get stun effect

**How it should work:**
has to get a stun effect

**Database links:**
-

**Comment by Sketish** [comment]
If I recall correctly it was discussed before and blink is applying aura which makes player immune to stun for 0,5-1sec after usuing blink
