### ISSUE TITLE
Quest bug: [A Unified Front]

### ISSUE THREAD

**Issue by Haltus-Kain** [gamefreedomgit/Maelstrom#5367]
**Description:**
WotLK | Dragonblight | Quest | [[A Unified Front]](https://www.wowhead.com/quest=13126/a-unified-front)
Cannot turn in quest once objectives are completed becuase [Image of Belgaristrasz](https://www.wowhead.com/npc=28012/image-of-belgaristrasz) doesn't spawn once [Varos Cloudstrider](https://www.wowhead.com/npc=27447/varos-cloudstrider) is killed.

**How to reproduce:**
Accept quest and complete objectives.

**How it should work:**
[Image of Belgaristrasz](https://www.wowhead.com/npc=28012/image-of-belgaristrasz) is supposed to spawn at [Varos Cloudstrider's](https://www.wowhead.com/npc=27447/varos-cloudstrider) corpse once defeated.

**Comment by PanJanuszek** [comment]
fixed 20.03.2024
