### ISSUE TITLE
Ultraxion - Hour of Twilight

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5369]
**Description:**
Currently there is chance that ultraxion aoe Unstable Monstriosity will tick right after Hour of Twilight

**How it should work:**

Acorrding to retail video there was 4 seconds delay for first tick of aoe after hour of twilight cast

**Database links:**
https://youtu.be/c1ddWXTG-eQ?si=lAIgwUyFgKbMCAU0&t=165

**Comment by UltraNix** [comment]
Fixed.
