### ISSUE TITLE
Battlegrounds: Mount bug/abuse!

### ISSUE THREAD

**Issue by Sylwania** [gamefreedomgit/Maelstrom#5370]
Battleground mount bug abuse!
**Description:**
Players coming with mounts in flagroom from ramp, and through tunnel in Warsong Guclh!
**How to reproduce:**
Instant fix. This abuse ruin the fun about bgs...
**How it should work:**
Players should be dismounted when they enter in tunnels or rooms ( Check room dismount )
Video: https://drive.google.com/file/d/1FICA-TXTcwJP6g_L6RfLJtV5vydZkTVb/view?usp=sharing
Screenshot: https://prnt.sc/FI6hT0ZCJUQo
Players are: Capdiff and Playgrndpre coming few times with mounts.

**Comment by Crusaderz** [comment]
Not just mounts. I saw a druid in travel form running through a horde tunnel.

**Comment by Hermeleen** [comment]
i already reported #5216

**Comment by UltraNix** [comment]
#5216

**Comment by Hermeleen** [comment]
Unfortunately, just saw again, mounted player in warsong gulch flag room.

**Comment by UltraNix** [comment]
Ups - closed too soon.

**Comment by UltraNix** [comment]
Fixed.
