### ISSUE TITLE
[DS] Ultraxion - Essence crystals timer wrong

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5371]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 Red crystal from Alexstrasza spawn after the second hour of twilight at 1m38 instead of before at 1m20

Green crystal spawn 5s earlier and blue crystal 5s earlier also

**How to reproduce:**

pull the boss and watch when the red crystal spawn

**How it should work:**

red crystal spawn 1m20 into the fight
green 2m35 into the fight
blue 3m35 into the fight

https://www.youtube.com/watch?v=8OiJNtoNpsM

**Database links:**

**Comment by UltraNix** [comment]
https://www.youtube.com/watch?v=c_AIB2RmzrA&t=49s
Timestamps on chat:
23:27:51 - starts encounter
23:29:11 - summons red crystal (1min 20 sec after engaging)
23:30:30 - summons green crystal (2min 30 after engaging)
23:31:25 - summons blue crystal (3min 34 sec after engaging)
23:32:45 - summons yellow crystal (4 min 54sec after engaging)

**Comment by UltraNix** [comment]
Fixed.
