### ISSUE TITLE
Priest - Prayer of Mending bounce range is more than 20 yards

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#5378]
https://streamable.com/b6m22z

Currently PoMs bounce range is 40 yards,  this should be 20 as per tool tip

https://gyazo.com/61d2541e6572fb58124e09e1d9fda7f5

Casting range is correct (40 yards), however PoM buff bounce range should be 20

**Comment by UltraNix** [comment]
Fixed.
