### ISSUE TITLE
Mage ( Mirror image break every cc) pvp/arena

### ISSUE THREAD

**Issue by keroblus** [gamefreedomgit/Maelstrom#5379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
mirror image should attack your target not closest enemy 

**How to reproduce:**

**How it should work:**
for example while mirrors image are casting and  in same time you or your party member cc target of mirror image, mirrors image will break it .every cc should  have 0.05 sec immune at start to dont get break (same as retail or warname or arena-tournament private servers)

**Database links:**
https://www.mmo-champion.com/threads/613742-Mirror-Image-Theories-and-Discussion
5) - What else?
Answer:
- They also only target and fight what the mage is fighting. If the mage switches targets, they switch targets.

**Comment by mipanka** [comment]
Any proof?

**Comment by keroblus** [comment]
there are alot of video from retail in youtube witch shows you mirror only attack your target and even if you poly target and in same time they cast into your poly it get immune

**Comment by Sketish** [comment]
then provide link to those videos

**Comment by keroblus** [comment]
https://youtu.be/xYM-Emts8SI
3:31
you can see here rogue blind war and orb hit into blind but it anit break blind and war trinket after that

**Comment by Sketish** [comment]
So for orb, and what about mirrors since its topic of this bug report ?

**Comment by keroblus** [comment]
https://youtu.be/JuvMG4qSSs4 
0:38 poly and mirror hit in same time

**Comment by keroblus** [comment]
i think whitemane  have to get some pvp pro player gm its not my job to find proff to fix bugs

**Comment by UltraNix** [comment]
Already fixed.
