### ISSUE TITLE
[Will of Unbinding] Bug

### ISSUE THREAD

**Issue by iamwindruner** [gamefreedomgit/Maelstrom#5380]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Will of Unbinding] is not working with any peridic damage

**How to reproduce:**
Hi
im a priest shadow
and i had [Will of Unbinding] from spine
it will not proc with any predic damage
not vampiric ... not mind fly .... not any predic damage
just with mind blast mind spike and shadow apprentice
its bug ... can you pls tell admin about it ? and fix this thing
its realy anoying
i had a boss fight in madness and i lost my intellect stack every time

i also got a video with bandicam ... doing multi DOT on dummys ... its not getting stack at ALL!!

**How it should work:**
well ... it sais harmfull spells ... so it should be working with any peridic damage ... not just casting spells

**Database links:**

**Comment by UltraNix** [comment]
#1072
