### ISSUE TITLE
[Hunter][Ability][BM] Exclusive Beast Mastery pet Chimaera is not giving Frenzy Effect stacks

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#5381]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Exclusive BM pet Chimaera is not giving Frenzy Effect stacks which means u can`t use Focus Fire ur main dps increase ability 

**How to reproduce:**
Find and tame Chimaera and go BM spec 

**How it should work:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/3b4b3093-f3fa-43a8-9654-a5e701280dfc)
https://cata-twinhead.twinstar.cz/?spell=82692

And here jpg with diffrent pet Devilsaur working as it should 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/27d238ad-0d8c-4c77-976e-26cfa644bc9e)

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/37107b95-3211-4fdd-9d82-d6deb6679fc6)
You are attacking with Basic Ability?

**Comment by JK2M** [comment]
Ability Bite is building Stacks w/o any Problems 
Auto Attack doesnt build Stacks
just tried it right now, if you need i can make a Vid

**Comment by Nenze** [comment]
It seems I had disabled Basic ability on my chimaera and did not test it enough before posting here tho thanks to JK2M issue is pointed on.
Thats why i did not get the stacks and i got them on Devilsaur cuz hes basic ability was on. 
Not sure now if its a bug tbh as the ability is called Basic attack 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/96f3cf3d-24ad-4fd0-a641-73ede26f9fc4)

> ![image](https://private-user-images.githubusercontent.com/80540499/293422239-37107b95-3211-4fdd-9d82-d6deb6679fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4ODg5ODcsIm5iZiI6MTcwMzg4ODY4NywicGF0aCI6Ii84MDU0MDQ5OS8yOTM0MjIyMzktMzcxMDdiOTUtMzIxMS00ZmRkLTlkODItZDZkZWI2Njc5ZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIyMjQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzhjMzg1MjUyMjI0YTRmZWM4YzJjZGI3OWVkZmYzZTllMGYzNzE2NmQxYjg1NmMxNjEzOGE2MTcxMDRhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLHtKXG5JGUrU0X_-49_AfDCZb8pmTj8jttNi2Fd2Sk) You are attacking with Basic Ability?
