### ISSUE TITLE
VPLC

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5382]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when it sends lightning bolt it goes on current target, not the guy who it procced on

**How to reproduce:**
put dots on one dummy and then target a different dummy

**How it should work:**
send the proc on the target that triggered it

char: Brutestrengt

**Comment by Sketish** [comment]
Provide any proof that it shouldn't hit target of a player

**Comment by BalanCV** [comment]
Maelstrom#4696 is proof. If what he's saying is accurate looks like the bug came back after it was fixed a while ago.

**Comment by UltraNix** [comment]
Fixed.
