### ISSUE TITLE
Quest NPC John J. Keeshan (after Done Nothing Wrong) (alliance)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5383]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

After you do the quest for Mouton Flamestar to free the whelplings, John J. Keeshan has a brief interaction with Mouton, after which he should offer the next quest in the zone plot, but he has no quests available, even after /reload and logging out and back in.
**How to reproduce:**

Complete "Done Nothing Wrong" with an alliance character (who has not done the Redridge questlines).
**How it should work:**

After completing "Done Nothing Wrong" and bringing the whelps back to Mouton Flamestar, John J. Keeshan should have a brief interaction with Mouton, and then offer the player the next quests in the zone plotline.
**Database links:**
https://www.wowhead.com/quest=28172/done-nothing-wrong
https://www.wowhead.com/quest=28174/burning-vengeance#comments

**Comment by PanJanuszek** [comment]
fixed 15.04.2024 after server restart
