### ISSUE TITLE
permafrost talent

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5384]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
permafrost doesnt give 10% extra slow to cone of cold, it only gives it to frostbolt
(OR MAYBE ITS JUST THE TOOLTIP I HAVENT TESTED IT)

**How to reproduce:**
![WoWScrnShot_122923_215335](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/b31ba9fa-4263-4fb2-a9b6-7cd22ba7c198)
(ignore the unlearened talent points, I had the talent learned as you can see the learn button is greyed out)

**How it should work:**
it should add 10% to the slow strength, making it 70% not 60% 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=12571

**Comment by Sketish** [comment]
Are you sure its not only tooltip issue ? Since blizzard was lazy with making those update correctly.

**Comment by SimonBpvp** [comment]
> Are you sure its not only tooltip issue ? Since blizzard was lazy with making those update correctly.

It might be a tooltip issue, I haven’t tested it. I‘m too lazy to test it.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/693f6e65-315d-4c50-9909-86e1623d3d29)
Tooltip problem.
