### ISSUE TITLE
chaos orb is soulbound

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5385]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** beggining with patch 4.3.4 chaos orb are no more soulbond

**How to reproduce:**

**How it should work:**

**Database links:** http://coldsgoldfactory.blogspot.com/2011/10/wow-patch-43-brings-tradeable-chaos.html
https://www.wowhead.com/blue-tracker/topic/chaos-orbs-in-patch-4-3-3280532927

**Comment by UltraNix** [comment]
Fixed.
