### ISSUE TITLE
frostweave bags not usable 

### ISSUE THREAD

**Issue by lasslouss** [gamefreedomgit/Maelstrom#5386]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
frostweave bags not usable 

**How to reproduce:**
frostweave bag just can't be used when equipped won't even open

**How it should work:**
should be usable like any other bag

**Database links:**

**Comment by Sketish** [comment]
Provide any clip or screenshot.

**Comment by lasslouss** [comment]
i logged today and it seems to be fixed , thank you for your reactivity
