### ISSUE TITLE
Cant ress when we wipe

### ISSUE THREAD

**Issue by VaellWhitemane** [gamefreedomgit/Maelstrom#5387]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cant ress when we wipe, we need disconnect and relog when we wipe

**How to reproduce:**
wipe

**How it should work:**
enter and ress in raid

**Database links:**

**Comment by frostwave942** [comment]
i have the same problem when <a href="https://imgur.com/a/fxMzp8y">i die in dungeons</a> i cant enter unless someone inside res me otherwise im forced to revive with sickness for 10m. at first i thought it only happened in that dungeon but no, it can happen in any dungeon even in raids.

**Comment by UltraNix** [comment]
Will be okay with the next update.

**Comment by UltraNix** [comment]
Fixed.
