### ISSUE TITLE
Swamp of Sorrows plotline (alliance)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5389]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Trade Baron Silversnap is supposed to offer quests to the player, to start the plotline in Swamp of Sorrows.  After speaking to him to turn in the Hero's Call introduction quest, he offers no other quests, even though my character is level 52 and has friendly reputation with his faction.

I was also unable to acquire "The Bogpaddle Bullet" from Burning Steppes, as I was not able to do any of the plotline in Burning Steppes after "Done No Wrong", which I described in this report:  https://github.com/gamefreedomgit/Maelstrom/issues/5383

Using /reload did not fix the issue, as well as logging the character out and back in.
**How to reproduce:**

Alliance character (level 52 gnome warlock), friendly reputation with Booty Bay faction, no other introduction (or other) quests leading to Silversnap, use board in town (Stormwind) to get the Hero's Call introduction quest for Swamp of Sorrows, travel to Bogpaddle to speak to Silversnap and complete the Hero's Call quest.
**How it should work:**
Regardless of which introduction quest takes you to Bogpaddle, or if you just go out to Bogpaddle on your own, you should be able to speak to Trade Baron Silversnap (negative reputation withstanding) to obtain the first quest in the Swamp of Sorrows plotline, "Maliciously Delicious".

**Database links:**

https://www.wowhead.com/quest=28675/heros-call-swamp-of-sorrows
https://www.wowhead.com/quest=27587/maliciously-delicious
https://www.wowhead.com/npc=45786/trade-baron-silversnap#ends
https://www.wowhead.com/quest=28569/the-bogpaddle-bullet

**Comment by KevlinTallfellow** [comment]
Addendum:  Failure to do the quests for Silversnap also prevents the player from obtaining any of the quests from Joanna Blueheart involving the horde vs alliance battle quests in the zone.

https://www.wowhead.com/npc=46676/joanna-blueheart#starts

**Comment by KevlinTallfellow** [comment]
Addendum:

There are phasing issues with the following quests:

Cutting Supply  https://www.wowhead.com/quest=27851/cutting-supply

Firstly, if you take the "Assault on Stonard" quest from Joanna first, she will phase out and you will not be able to get the "Cutting Supply" quest from her.  The "Stonard Supplies" that you have to loot for the quest come from containers that are NOT in the quest phase for "Assault on Stonard", they are in the normal Stonard phase, where the town is full of level 60 PVP guards, as well as possible PVP flagged players.  I discovered this because...

Assault on Stonard https://www.wowhead.com/quest=27849/assault-on-stonard

...after killing the 6 "Stonard Defender" in the quest phase, rendering the quest objective "complete" and without being able to locate any of the "Stonard Supplies", I was immediately dropped OUT of the quest phase and INTO normal Stonard, right in the center of the town, surrounded by all of the level 60 town guards and vendors and quest NPCs, and even a horde player who happened to be there at the time.  I did not survive, and it was because of my soulstone that I was able to revive inside the town in a place where I could freely loot 3 of the Stonard supply crates behind one of the large buildings where the town NPCs couldn't see me.  The fourth crate was near the back gate, where I got agro from the guards there whom my voidwalker happily pulled agro on, and the final crate was actually inside one of the large buildings in the town, which I was only able to loot because of the damage absorption shield from my voidwalker keeping me alive long enough to run in and grab it.  I did not survive my attempt to exit the town.  I would imagine that many classes who do not have these kinds of tricks would essentially have to "corpse flop" through the town, running in as close as they could to a crate and dying, only to come back as a ghost and try to respawn and grab the crate before dying again.

While these issues may not be a problem for a high level character doing these quests, they are a pretty big problem for at-level characters doing these quests at level 52.

**Comment by KevlinTallfellow** [comment]
Addendum:

You need to do the quests for Crazy Larry to get the quest that sends you over to Baba Bogbrew, and *she* is the one who will eventually direct you to go speak to Lord Itharius, who then sends you on to Marshtide Watch.

https://www.wowhead.com/quest=27740/baba-bogbrew
https://www.wowhead.com/quest=27869/the-dragon-and-the-temple

So, without being able to do the quests for Trade Baron Silversnap, alliance characters never get sent to Crazy Larry, who never sends them to Baba Bogbrew, who sends them to Lord Itharius, who sends them to Joanna Blueheart.  You would have to know ahead of time about Baba Bogbrew and/or Lord Itharius to get the quest sending the alliance character to Marshtide Watch.

**Comment by PanJanuszek** [comment]
fixed 08.05.2024, server restart required
