### ISSUE TITLE
Hearhblossom 

### ISSUE THREAD

**Issue by Cekma737** [gamefreedomgit/Maelstrom#5391]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Spawn points of this herb are rly poor there! Me as a herbalist in everyone cata server till now do 2 full rotations of map and find some like this 2x stack of herbs in a other case find more Cinderbloom than Heartblossom this is not normal cuz Heartblossom are farmed only in deepholm and drop rate is too low comapre other herbs for example Whiptail drop for 1 to 20 in one herb Heartblossom drop from 1 to max 5 in one herb!!!
**How to reproduce:**

**How it should work:**
U should make alot more spawn point of this herb in every one point of map ill attach image from wowhead

**Database links:**

![heartblossom deephom](https://github.com/gamefreedomgit/Maelstrom/assets/132700566/25bdba86-e33b-46d4-ba35-f40f27709024)
   there is a link too
 https://www.wowhead.com/zone=5042/deepholm#show:herb:heartblossom
https://cata-twinhead.twinstar.cz/?object=202750

**Comment by UltraNix** [comment]
Fixed.
