### ISSUE TITLE
[Quest] Western Plaguelands (After fix)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5392]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

after the fix i found another bugs and phase issues in this zone

<a href="https://www.wowhead.com/quest=26933/foes-before-hoes">Foes before hoes</a> there are alliance laborers in the area, yes. but <a href="https://imgur.com/a/jIulBMJ">i don't get credit</a> after killing them.

<a href="https://www.wowhead.com/quest=26937/when-death-is-not-enough">When death is not enough</a> after taking this quest and enter in felstone fields the <a href="https://imgur.com/a/nz0bgmh">val'kyr doesn't spawn</a> so i can't complete it.

i could complete <a href="https://imgur.com/a/WQr0yOA">these quests</a> but in Andorhal, koltira or other quest giver are <a href="https://imgur.com/a/cAdST6L">not there</a>.

storyline stuck <a href="https://imgur.com/a/oiDAsCX">42/45</a>

**Comment by PanJanuszek** [comment]
after restart
