### ISSUE TITLE
 A major bug in the legendary dagger mission line 

### ISSUE THREAD

**Issue by iceringzx** [gamefreedomgit/Maelstrom#5394]
I am a Chinese player ID: milaazul. In this week's Dragon Soul raid, my team completed the process of [collecting gems clusters (legend)] for me. Before allocating items, the item allocator automatically assigned 7 source gems clusters to another player who held the [ Prove your value ] task. After multiple attempts to contact the GM, the issue was not resolved. I hope to return the 7 source gems clusters that were mistakenly assigned to me. 
![Uploading 微信图片_20231231031928.png…]()

**Comment by iceringzx** [comment]
<img width="611" alt="_20231231031928" src="https://github.com/gamefreedomgit/Maelstrom/assets/155260355/88a6029a-21cc-4df5-a1b0-ff7ea4c79736">

**Comment by Sketish** [comment]
How is that a major bug ?
How was it automatically assigned ?
Items are not added to player bag by system so what addons are you using ?
Also if that was guild run how could you take someone else clusters ?
So it doesnt looke like bug but players error

**Comment by iceringzx** [comment]
I did not use any item allocation plugins, and during the entire raid process, only two bosses automatically dropped their items into the player's backpack without any tasks before allocation.

**Comment by iceringzx** [comment]
> I did not use any item allocation plugins, and during the entire raid process, only two bosses automatically dropped their items into the player's backpack without any tasks before allocation.


I did not use any item allocation plugins, and during the entire raid process, only two bosses automatically dropped their items into the player's backpack without any tasks before allocation.

**Comment by iceringzx** [comment]
@Sketish

**Comment by iceringzx** [comment]
@Sketish Players who do not have a task receive task items, which is impossible for any plugin to achieve

**Comment by iceringzx** [comment]
@Sketish  It's like two men together can never give birth to a child

**Comment by iceringzx** [comment]
@Sketish In this week's Dragon Soul raid, the team chose me, and only I had the task of collecting gem clusters in the legendary dagger series. I proceeded normally until the distribution of items for the fifth and sixth bosses. The task item, source crystal gem cluster, was automatically distributed to a rogue without manual distribution, who did not have the task of collecting gem clusters.I am a Chinese player, and the screenshot of evidence I provided was taken using a Chinese client.I also uploaded the screenshot to the forumhttps://github.com/gamefreedomgit/Maelstrom/issues/5394.Because this issue was not caused by ninjia, the server is a normal GM and cannot help me return the gem clusters that were distributed by the system error. Please do not question me, as players without related tasks cannot obtain this gem cluster, so this is not a man-made issue.Please help me return the lost seven source crystal gem clusters to me.

**Comment by UltraNix** [comment]
There is no bug here.
