### ISSUE TITLE
Survival hunter crit chance bug

### ISSUE THREAD

**Issue by AnsBal** [gamefreedomgit/Maelstrom#5395]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I hit a dummy as a survival hunter with 35.04% crit chance and here is the results:

| Spell  | Hit count | Crit count | Crit chance|
| ------------- | ------------- | ------------- |------------- |
| Explosive shot | 915  | 522  | 36% |
| Cobra shot  | 429  | 192  | 30%  |
| Auto shot  | 690 | 318 | 31%  |
| Black arrow | 654 | 284 | 30%  |
| Serpent sting | 385 | 349|  47%  |

I have a low sample for the following spells and they all had a crit chance close to 30%: Arcane shot, Flaming arrow(PvE gear bonus) and Lightning strike (Vial of Shadows)

Note that I have  [Glyph of Explosive Shot] that increases Explosive Shot's crit chance by 6%.  [Glyph of Serpent Sting] and  [Improved Serpent Sting (talent)] that increase Serpent Sting's crit by 16% in total.

I should have 35% crit chance but the data shows that I have a 30% crit chance.

**How to reproduce:**
Hit a dummy as survival hunter.

**How it should work:**
If I have 35% crit chance I should be criting 35% of the time.

Is crit chance reduced by 5% against the Raider's Training dummy?

**Comment by bonfax4** [comment]
Yh there should be a 4.8% crit suppression on boss targets, you should retest on a lvl 85 one

**Comment by JK2M** [comment]
And a big But, 35% Crit chance doesnt mean you Crit in 1000 shots 350 times, no it means in 1000 shots you have a chance of 35% to crit
It is always only a Chance on the Single Shot not on "XYZ" Number

**Comment by AnsBal** [comment]
I tested on lvl 85 dummy and concluded that there is no problem. Closing this issue.
