### ISSUE TITLE
Darkmoon Faire deathmatch.Darkmoon treasure chest do not spawn

### ISSUE THREAD

**Issue by Hunafanai** [gamefreedomgit/Maelstrom#5397]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**it should spawn every 3 hrs from midnight

**How to reproduce:**https://wowwiki-archive.fandom.com/wiki/Darkmoon_Treasure_Chest

**How it should work:**

**Database links:**https://wowwiki-archive.fandom.com/wiki/Darkmoon_Treasure_Chest

**Comment by Afgann** [comment]
fixed

**Comment by Accidentlol** [comment]
> fixed

Its not fixed, reopen this.
