### ISSUE TITLE
[DS] Spine - Missing yell on pull

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5399]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 Not a big deal, but this yell is missing on pull right now, this is what's triggering DBM for this fight so DBM is not showing anything.
 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/6043334f-f7e0-424b-9036-ba08ff9a72e2)

**How to reproduce:**

 Pull

**How it should work:**

Should yell "The plates! He's coming apart! Tear up the plates and we've got a shot at bringing him down!" on pull

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
