### ISSUE TITLE
Taste The Rainbow! and Chromatic Champion bug

### ISSUE THREAD

**Issue by Firokash** [gamefreedomgit/Maelstrom#5402]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154538052/b5fcdc9e-9002-48fd-9093-0e2c9972af57)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/154538052/5a30eb8a-e2f9-413c-86e8-da73bdb1dbe0)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/154538052/4239545e-4533-4716-8236-6c7ee4b2e272)

Progress is not being tracked for the Dragon Soul Achievments

**Comment by UltraNix** [comment]
Fixed.
