### ISSUE TITLE
Elemental Bonds: Doube + Shadowfiend

### ISSUE THREAD

**Issue by Firokash** [gamefreedomgit/Maelstrom#5403]
If I kill an Essence of Doubt while shadowfiend is active, the game hard crashes
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154538052/3670301e-f78a-4ec1-8422-b67afdd4964b)

**Comment by PanJanuszek** [comment]
No info provided

**Comment by WhitemaneChronus** [comment]
Tested today with a player on spanish client.
When they use shadowfiend, as soon as its target dies they crash.
