### ISSUE TITLE
Spine of Deathwing

### ISSUE THREAD

**Issue by acde00** [gamefreedomgit/Maelstrom#5404]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the tendon must have a back or be a back

**How to reproduce:**
on outlaws, you must hit with back blows and ambushes. 

**How it should work:**

**Database links:**
https://www.youtube.com/watch?v=LyqlNfrxKkU&list=PL0E864DDE878F26A8&index=3

**Comment by UltraNix** [comment]
Fixed.
