### ISSUE TITLE
Dragon Soul - Hagara Bugs

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5406]
- I got 0 Shattered Ice casts.
- Hagara isn't casting / chanelling water bubble during the Frost Phase, and the dome isn't appearing.
![WoWScrnShot_010124_010707](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/fd5d5ba8-bd98-4c3d-93ce-7c7b7c58554d)

(Tested in 25 HC but it should be checked on all difficulties.)

**Comment by UltraNix** [comment]
Fixed.
