### ISSUE TITLE
Dragon Soul - Ultraxion Melee Range

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5407]
Ultraxion Melee range ( also twilight burst range ) should be at the last line close to the base of the stairs, this affects charges.
![WoWScrnShot_010124_013457](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/a5dcbedd-6a4c-4f1e-b2a7-c95b2e16b8f1)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/6cfe61db-d3ae-4d55-b08e-83eae6bf7eb6)
Source : [https://www.icy-veins.com/wow/ultraxion-strategy-guide-normal-heroic](https://www.icy-veins.com/wow/ultraxion-strategy-guide-normal-heroic)

**Comment by UltraNix** [comment]
Fixed.
