### ISSUE TITLE
[Darkmoon Faire] Daily Quests (Cooking & Engineering)

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5409]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Name = <a href="https://cata-twinhead.twinstar.cz/?quest=29509">Putting the Crunch in the Frog</a>

Bug    = after clicking the frogs near the stam's pot, nothing happens.

How it should work = https://www.youtube.com/watch?v=vL9fuTSJX60

---------

Name = <a href="https://cata-twinhead.twinstar.cz/?quest=29511">Talkin' Tonks</a>

Bug    = after using the "Battered Wrench" near of those damaged tonks, nothing happens.

How it should work = https://www.youtube.com/watch?v=YqRH7KV2c7U

---------

**Comment by Revly** [comment]
+
Also 

Jewelry no work
Enchant no work

**Comment by halendia** [comment]
Can confirm the [Putting the Crunch in the Frog] does not work.
Enchanting quest works 2/1-24 @ 16:00 ST.

**Comment by UltraNix** [comment]
Fixed.
