### ISSUE TITLE
Rogue - shadowy gem drop rate

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5410]
**Description:**
Shadowy Gem are currently dropping with higher rate than intented,

**How to reproduce:**
Kill any DS boss during q https://www.wowhead.com/quest=30107/cluster-clutch

**How it should work:**
After adjusting each cluster should drop 5-10, currently people are reporting getting over 10 from single cluster

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
