### ISSUE TITLE
Quest NPC Balos Jacken

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5412]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The player is supposed to do enough damage to Balos Jacken to make him stop fighting and turn friendly, so the player can have a conversation with him.  He does not do that.  I've wanded him down a couple of times now, and he never stops fighting and turns friendly.  My priest even stabbed him down with a dagger, and he still fought to the death.  This prevents the player from having the necessary conversation to complete "The Deserters", and continuing the alliance plotline in Dustwallow Marsh.  He's not supposed to be killable, as far as I can tell; he should never go below 1 health.

**How to reproduce:**

With "The Deserters" active, try to fight Balos Jacken until he stops attacking you.
**How it should work:**

The player should fight with Balos Jacken until he gets down to 1 health, and then he should no longer take damage, and become friendly, so the player can converse with him.
**Database links:**
https://www.wowhead.com/quest=27287/the-deserters#comments
https://www.wowhead.com/npc=5089/balos-jacken#comments

**Comment by PanJanuszek** [comment]
fixed 16.04.2024, server restart required
