### ISSUE TITLE
Quest:  Two-Tusk Takedown (alliance)

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5415]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The player is tasked to go into a cave to defeat the admiral and obtain a key.  The caves have many hostile ogres on patrol, which are elite and very high health, because they are not intended to be fought, they are intended to be interacted with in a way that makes them non-hostile.  However, the quest item that the player is supposed to use on the ogres to make them non-hostile fails to work, so the ogres continue to be hostile and attack, which is deadly for at-level players trying to do the quest.
**How to reproduce:**

Get the quest from Wizzle Brassbolts.  Try to use the "Fake Treasure" quest item (from the quest tracker button) on an ogre. 
**How it should work:**

Using the "Fake Treasure" item on the ogres should distract them and make them non-hostile long enough for the player to bypass them and get into the cave to reach the quest objective inside.
**Database links:**

https://www.wowhead.com/quest=25627/two-tusk-takedown#comments

**Comment by PanJanuszek** [comment]
fixed after restart
