### ISSUE TITLE
Missions without level requirement

### ISSUE THREAD

**Issue by Andors3** [gamefreedomgit/Maelstrom#5417]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/classic/es/item=11476/pelambre-de-ucha)
[//]: # (https://cata-twinhead.twinstar.cz/?item=11476)

**Description:**
https://www.wowhead.com/classic/es/npc=9622/ucha
The npc U'cha drops his fur, any player can loot it and trade it at a lower level, thus allowing the mission to be completed.

**How to reproduce:**
By killing and collecting the hair

**How it should work:**
You shouldn't let go of your hair unless you have the mission.

**Comment by UltraNix** [comment]
Already fixed.
