### ISSUE TITLE
Darkmoon Despoiler

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#5418]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello, achivement Darkmoon Despoiler not working correctly. These quest items comes from pvp -removing insignia of corpses- I have played 20+ battlegrounds and removed ~80-100 insignia got zero quest items.

**How to reproduce:** Add these items in the game:
https://www.wowhead.com/item=71953/fallen-adventurers-journal
https://www.wowhead.com/item=71951/banner-of-the-fallen#comments
https://www.wowhead.com/item=71952/captured-insignia#comments
**How it should work:**
They should be looted in battlegrounds- removing insignia of fallen enemy.

**Database links:**

**Comment by frostwave942** [comment]
i wondered the same, i played too many bgs lots of hks and all but none dropped those quest item after looting their insignias.

**Comment by UltraNix** [comment]
Fixed.
