### ISSUE TITLE
Quest Harpy Raiders (Horde) Requires level 12 - Level 15

### ISSUE THREAD

**Issue by NicolasEyh** [gamefreedomgit/Maelstrom#5419]
**Description:**
This mission is given to you by Darsok Swiftdagger and you have to collect 8 Witchwing talons. 

**How to reproduce:**
Directly the NPC does not give you the mission, when originally it has an important mission follow-up.  

**How it should work:**
Once accepted you will be able to continue doing the missions without any problem. 

**Database links:**
https://cata-twinhead.twinstar.cz/giojwqcmho.html?quest=867

**Comment by PanJanuszek** [comment]
fixed 15.04.2024, required server restart
