### ISSUE TITLE
Report to Thork (Horde) Requires level 5 - Level 5 

### ISSUE THREAD

**Issue by NicolasEyh** [gamefreedomgit/Maelstrom#5420]
**Description:**
When you start the mission, you have to talk to Thork, in question is all that makes the mission.  

**How to reproduce:**
The problem is that when the mission does not appear, you can not continue and you can not continue with other missions, even if the GM gives it to you, you can not complete it. 

**How it should work:**
Once you are given the mission you have to talk to Thork, once you talk to him, he has to give you another mission to follow. 

**Database links:**
https://cata-twinhead.twinstar.cz/startattack?quest=29095

**Comment by PanJanuszek** [comment]
fixed with update 04.03.2024
