### ISSUE TITLE
Mor'shan Caravan Delivery (Horde) Requires level: 14 - Level 16

### ISSUE THREAD

**Issue by NicolasEyh** [gamefreedomgit/Maelstrom#5421]
**Description:**
It is a follow-up of caravan missions, you have to protect the caravan and deliver it safely. 

**How to reproduce:**

The problem is that the third time you are supposed to protect it, it does not let you continue, the mission in question does not appear even though the mission item is still in your inventory and the mod to mount it does not appear either.   

**How it should work:**

You will have to protect the caraba one last time and complete the mission, remove the item that generates this mission and you will be able to continue with another mission that does not appear unless you complete this one already mentioned. 

**Database links:**
https://cata-twinhead.twinstar.cz/giojwqcmho.html?quest=29111

**Comment by PanJanuszek** [comment]
Fixed with barrens refactor 04.03.2024
