### ISSUE TITLE
Items: Chaos Orb

### ISSUE THREAD

**Issue by raxidozec** [gamefreedomgit/Maelstrom#5423]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Now we in 4.3.4 patch and Chaos orb still personal

**How it should work:**
On retail timeline it should be like this:

4.0.3a 23.11.2010 chaos orb was added(like personal when u get in ur bag)
4.3.0 29.11.2011 chaos orb remake and from now possible to trade on Auction House.

**Comment by VaellWhitemane** [comment]
go BoE pls

**Comment by UltraNix** [comment]
#5385
