### ISSUE TITLE
Dragon Soul - Morchok HC bugs.

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5425]
1- Crystals from a group hitting players from the other group even if they are not linked to it, if 3 players are linked to their crystal and the crystal from the other group explodes it hits them. so the cristal is hitting all players who got the crystal debuff instead of hitting only those who are linked to it. [Clip for this bug](https://clips.twitch.tv/CrispyFrozenCarabeefPeanutButterJellyTime-FCMi2Ftr2330YHAR)

2- Also the two bosses takes a long time to split, Kohcrom alone sometimes. [Clip for this bug](https://clips.twitch.tv/MagnificentFlaccidGarageResidentSleeper-ZYcdD925WQEEgywU)

**Comment by UltraNix** [comment]
Fixed.
