### ISSUE TITLE
Ultraxion Bug

### ISSUE THREAD

**Issue by iamwindruner** [gamefreedomgit/Maelstrom#5426]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ultraxion Bug

**How to reproduce:**
Fix this looming darkness

**How it should work:**
when the hour of twilight coming up ... 2 people must stay and should get hit by the hour of twilight ... when we have 2 player staying on the twilight realm and they will get the looming darkness ... wich so far its fine .... but for the next hour of twilight ... the people who had looming darkness will die anyway ... even in the safe realm

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
