### ISSUE TITLE
Colossal Guardians

### ISSUE THREAD

**Issue by LShotorov** [gamefreedomgit/Maelstrom#5428]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Collosal Guardian that has the Stone of the Sun is NOT spawning

**How to reproduce:**
I got the "Colossal Guardians" quest and killed the one that has the moon stone. The one that has the Sun Stone doesn't exist..

**How it should work:**
There should be one more colossal guardian that has the Sun stone.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/123563786/f2d6d9ce-4a2a-4cd9-92a4-c0dcccb1c493)
**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/137a2c69-2000-481b-8b96-a26786267316)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/8e84a45b-a0d6-4355-9b02-f7ef13e90743)

both exist, maybe someone killed it before you
