### ISSUE TITLE
Shaman T13 2p Resto bonus not working

### ISSUE THREAD

**Issue by VenkIvanov** [gamefreedomgit/Maelstrom#5429]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[/https://www.wowhead.com/spell=105764/item-shaman-t13-restoration-2p-bonus-mana-tide/]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Shaman T13 p2 Resto set bonus is not working. Mana reduction is not applied. Noting triggers after Mana Tide expires.

**How to reproduce:**

Get shaman with 2p T13 Resto, spend some mana, pull MT totem. Wait for MT totem to go off.

**How it should work:**

It should reduce the mana required by spells.

**Database links:**

https://www.wowhead.com/spell=105764/item-shaman-t13-restoration-2p-bonus-mana-tide

**Comment by UltraNix** [comment]
Fixed.
