### ISSUE TITLE
Dragon Soul - Madness HC bugs

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5430]
**1-** Time zone isn't slowing Corrupting Parasite's cast. should slow it by 50% if it's dropped on the Time Zone
![TZ](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/d3654cc5-c723-4d59-97c0-9dfc386592fe)

**2-** Alexstrasza's Cauterise ability isn't dealing damage to the parasite. it should do.
![Alextraza](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/457bffef-5dc7-4e8d-8c7e-e003b70571de)

**3-** Corrupting Parasite's cast could be interrupted, it shouldn't be possible.

**4-** Congealing Bloods should be [slowable](https://youtu.be/k1A9bU0rGvw?si=tc3tb9OKmcQtzDy0&t=737
). Slow effects shouldn't stack when multiple slows are there, it counts the highest % slow.
Known AoE Slowing effects that should work on them :
Crippling Poison 70% / Shadowflame(with glyph) 70% / Frost Trap 50% / Earthbind Totem 50%
Single target slows should work also, but as i mentionned before it shouldn't stack, the highest % slow is counted.

**Comment by UltraNix** [comment]
Fixed.
