### ISSUE TITLE
Muddy Crawfish aren't removed if mounted

### ISSUE THREAD

**Issue by Solonarv** [gamefreedomgit/Maelstrom#5431]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** During daily quest [Crawfish Creole](https://cata-twinhead.twinstar.cz/?quest=26226), if you pick up a crawfish while mounted, the crawfish does not despawn.

**How to reproduce:**

1. Take [Crawfish Creole](https://cata-twinhead.twinstar.cz/?quest=26226) daily.
2. Find a [Muddy Crawfish](https://cata-twinhead.twinstar.cz/?npc=42548)
3. Mount up (either flying or ground mount)
4. Right-click the muddy crawfish to collect it
5. Receive error message "you are mounted", and [Muddy Crawfish](https://cata-twinhead.twinstar.cz/?item=57765) item in inventory.
6. Observe the crawfish still scuttling around.
7. Repeat steps 4-6.

**How it should work:** In step 5, either you should not get the muddy crawfish item, or the muddy crawfish NPC should despawn.

**Database links:**

- [Crawfish Creole](https://cata-twinhead.twinstar.cz/?quest=26226) daily quest
- [Muddy Crawfish](https://cata-twinhead.twinstar.cz/?npc=42548) NPC for the quest
- [Muddy Crawfish](https://cata-twinhead.twinstar.cz/?item=57765) item required for the quest

**Comment by PanJanuszek** [comment]
fixed 15.04.2024 server restart required
