### ISSUE TITLE
Keeping the Faire Sparkling dont reset

### ISSUE THREAD

**Issue by cristianandreiu** [gamefreedomgit/Maelstrom#5432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Daily inside the Darkmoon fair given bij Chronos does not reset.

**How to reproduce:**
https://www.youtube.com/watch?v=LI10w2igC0Y

**How it should work:**
it should reset

**Database links:**
https://www.wowhead.com/quest=29516/keeping-the-faire-sparkling

**Comment by UltraNix** [comment]
It's a weekly quest and does reset.
