### ISSUE TITLE
DS tundra mammoth bug

### ISSUE THREAD

**Issue by freakyfrizes** [gamefreedomgit/Maelstrom#5434]
NPCs on the TRAVELER'S TUNDRA MAMOTH are always going hostile when i mount up inside the raid , we always have to go outside to repair our gear .

**Comment by Revly** [comment]
A mention my example:

> Something similar happens with the traveling tundra mammoth mount: example:
> 
> If the leader is an alliance and your mount is a horde, the npcs are useless.
> 
> If the leader is a horde and the mount is an alliance, the NPC's are useless.
> 
> If the leader is an alliance and the mount is an alliance, it works for the NPC's.
> 
> If the leader is horde and the mount is horde, if the npc's work
> 
> Could there be a way to make the mammoth npc's work for both?


This is how it is currently working

**Comment by UltraNix** [comment]
Fixed.
