### ISSUE TITLE
bugged achie and adds do to much damage

### ISSUE THREAD

**Issue by cristianandreiu** [gamefreedomgit/Maelstrom#5435]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the achievement : Extra Credit Bonus Stage. where you collect 5 orbs in side the dungeon is bugged, the orbs are spawned way to far away to grab them.
Also Adds deal more damage then boss? 
**How to reproduce:**
move it closer 
**How it should work:**

they should be closer normally they are able to be grabbed by a jump 
**Database links:**
https://www.wowhead.com/achievement=5289/extra-credit-bonus-stage

**Comment by UltraNix** [comment]
Spawn positions are correct.
