### ISSUE TITLE
Karoma Missing wolf special.

### ISSUE THREAD

**Issue by Gelura24** [gamefreedomgit/Maelstrom#5437]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After taming Karoma i noticed he does not have the wolf special ability. 

**How to reproduce:**

**How it should work:**
he should have the wolf special ability

**Database links:**
https://www.wowhead.com/npc=50138/karoma

**Comment by djesic** [comment]
Karoma comes with Spirit Beast spells - Roar of Courage, Spirit Mend and Spirit Walk.
It does not come with wolf Furious Howl (5% crit)

https://web.archive.org/web/20110521160300/http://wow-petopia.com/look/wolf_ghost.html

**Comment by UltraNix** [comment]
https://www.wowhead.com/npc=50138/karoma#controlled-abilities
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/52b4938f-26d3-40b5-993c-2ca99c247f1c)

Looks okay to me.
