### ISSUE TITLE
Quest: "Entrenched" at deepholm, Shuddering Spires

### ISSUE THREAD

**Issue by BreadCrumbless** [gamefreedomgit/Maelstrom#5438]
I cannot speak with the NPC "Kor the Immovable" as I am only given the option to kill him

How it should work: To be able to speak with the NPC "Kor the Immovable" in Shuddering Spires to be able to proceed with the quests

Database links:

https://www.youtube.com/watch?v=hIy6a4_lXww&ab_channel=WorldOfWarcraftGuidesAndGameplay
https://www.wowhead.com/quest=26436/entrenched

**Comment by MrTide** [comment]
Hello
apparently you're At War with that faction. If you're At War, even a friendly faction can be attacked by you and you will no longer be able to interact with them. To fix this issue, please head to Character Info > Reputation and choose the faction you are interested in. On the right side you will see faction overview and the check boxes. Untick `At War` and you will be friendly again

**Comment by BreadCrumbless** [comment]
Thanks!!
