### ISSUE TITLE
Ultraxion Encounter engagement 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#5439]
**How to reproduce:**
after changing the difficulty from heroic to normal players couldnt talk to kalecgos to start the event anymore

**How it should work:**
changing the difficulty should not have any effect on this

**Comment by UltraNix** [comment]
@MrTide More info please. It was right after defeating Hagara? Or maybe during the drakes event?

**Comment by flyingevelyn** [comment]
If changing the difficulty just after picking up the loots from Hagara, we will meet this problem. If we change the difficulty after the drakes event, there will be no problem, as mentioned by my friend.

**Comment by flyingevelyn** [comment]
@UltraNix

**Comment by UltraNix** [comment]
Fixed.
