### ISSUE TITLE
[mage] impact and dtr

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5441]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
talent impact doesnt work (stun) if dtr copyed fireblast

**How to reproduce:**
use fireblast with proc talent impact (buff)

**How it should work:**
target should be stunned 

**Database links:**
https://wowpedia.fandom.com/wiki/Impact_(mage_talent)#:~:text=Impact%20is%20a%20mage%20talent,enemy%20targets%20within%2012%20yards.
https://www.wowhead.com/item=71086/dragonwrath-tarecgosas-rest

If I find something new, I’ll add it

**Comment by Sketish** [comment]
I need any proof that it should stun target

**Comment by mipanka** [comment]
I'll try make a video, cuz my combat log dont help with it

**Comment by SimonBpvp** [comment]
> I need any proof that it should stun target

He means it won’t stun at all. He didn’t mean that the copy doesn’t stun. 

I’ve noticed it a few times impact not stunning with DTR

**Comment by SimonBpvp** [comment]
![WoWScrnShot_030524_200145](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/914a4cf2-0fd4-4dd7-9ee1-3fd6070d9647)
there u can see what I mean: my fireblast copies and does not stun

**Comment by SimonBpvp** [comment]
![WoWScrnShot_030624_123511](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/96ca4593-324e-49d5-9702-6492c0decd83)

here you can see that impact doesn't affect the target dummy when the fire blast gets copied by DTR

**Comment by SimonBpvp** [comment]
<img width="679" alt="Screenshot 2024-03-12 at 17 26 56" src="https://github.com/gamefreedomgit/Maelstrom/assets/94299191/bbc331aa-a54f-437a-b22e-8683720a7654">

>should not trigger impact

it didn't and shouldn't but that's not the issue here. The issue is like this:
on retail your fire blast with impact and dtr proc made 2 fire blasts and 1 stun
on whitemane it makes 2 fire blasts and 0 stuns

**Comment by UltraNix** [comment]
Fixed.
