### ISSUE TITLE
[Rogue] Legendary Daggers 45% damage increase effect not applied to Sinister Strike and Revealing Strike

### ISSUE THREAD

**Issue by JimboLimbo175** [gamefreedomgit/Maelstrom#5443]
**Description:**
The main hand legendary daggers have an effect stating: Increases the damage dealth by Sinister Strike and Revealing Strike by 45%. 
However, this effect is not currently applied.
Sinister strike damage with the 406 legendary main hand dagger (902-1677 Base Dmg): 
![SS 406 Lego](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/69e04139-8fc2-43f5-a502-5837329c1273)
Sinister strike damage with a 391 1.80 dagger (784-1459 Base Dmg):
![SS No Lego](https://github.com/gamefreedomgit/Maelstrom/assets/143458967/6b251d3b-10d2-4534-82a3-e959418e9521)
Shallow/Moderate/Deep Insight is consistent across tests.
There is a slight increase with the 406 daggers, but this is because of the increase in base damage between the daggers and does not represent the 45% increase in damage we should be seeing.
Revealing Strike also lacks the increased damage.
All the testing for this was done with the Tier 2 legendary daggers, but it is likely the issue applies for all 3 Tiers.

**Database links:**
https://www.wowhead.com/item=77945/fear
https://www.wowhead.com/item=77947/the-sleeper

**Comment by UltraNix** [comment]
Fixed.
