### ISSUE TITLE
Shadow Priest T13 p4  is not working

### ISSUE THREAD

**Issue by szx686** [gamefreedomgit/Maelstrom#5444]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Shadow Priest T13 p4  is not working。Shadow Spectre does not trigger 3 stacks of Shadow Orbs when attacking.

**How to reproduce:**
Shadow Spectre correctly triggers 3 stacks of Shadow Orbs when attacking.

**How it should work:**
Shadow Spectre correctly triggers 3 stacks of Shadow Orbs when attacking.

**Database links:**
wowhead.com can't be accessed normally in my country. Item ID: 76357-76361

**Comment by UltraNix** [comment]
Fixed.

**Comment by szx686** [comment]
I see that discord says it has been fixed, but after the server restarted yesterday, it still doesn't work.

**Comment by UltraNix** [comment]
Fixed.
