### ISSUE TITLE
[Morchok]   [Stomp] TIMER

### ISSUE THREAD

**Issue by UlicaTV** [gamefreedomgit/Maelstrom#5445]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I had a problem at 10H at [Morchok] from what I saw it gave [Stomp] before splitting

**How to reproduce:**
I think that if you damage it too much and it reaches a certain percentage, then this happens...

**How it should work:**
You have to Stomp the clone or the boss after it splits
I will attach a video

**Database links:**

https://youtu.be/ZK-h1dU6FFc

**Comment by UltraNix** [comment]
Also seems not to be a bug - that's how the timers look like there (even according to your DBM addon they are correct).
