### ISSUE TITLE
 [The Earth Consumes You!]   [Morchok] 10H

### ISSUE THREAD

**Issue by UlicaTV** [gamefreedomgit/Maelstrom#5446]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
From what I noticed, it happens strictly at [Morchok], this problem, casts [Stomp] and almost instantly also [The Earth Consumes You!]
**How to reproduce:**
From what I noticed, it happens strictly at [Morchok], this problem, casts [Stomp] and almost instantly also [The Earth Consumes You!]
Heroic happens only on Morchok
​

**How it should work:**
there must be a timler between [Stomp] and [The Earth Consumes You!], but he casts them at the second
I will attach the video

**Database links:**
https://youtu.be/EVFLlS7RvYk

**Comment by Sketish** [comment]
Yes, sometimes those overlap can happen

**Comment by UltraNix** [comment]
Seems not to be a bug.
