### ISSUE TITLE
Parry rating overstrong in PVP

### ISSUE THREAD

**Issue by Setikx** [gamefreedomgit/Maelstrom#5450]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In PVP as feral druid trying to put Rake or Rip on War Ret or DK it can be parried sometimes 5 times in a row with their 5% parry. U lost 4.5-7.5 sec on GCD's for nothing.  It shouldn't be like this. And this problem is too old - from the very beginning of the server. 

**How to reproduce:**
Statistically try to use Rake on UDK (for example) so sometimes it will be 3-5 times in a row. U and DK have to be in PVP gear.

**How it should work:**
Not so ofter with 5% chance to parry. 

**Database links:**
https://cata.cavernoftime.com/spell=3127

**Comment by UltraNix** [comment]
Lack of luck? :)

**Comment by UltraNix** [comment]
1. test
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d4e16c40-8229-4166-b7be-922a0cd14306)
20 parries / 500 casts ~5,7%

2. test
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a292bef4-709b-41d3-9181-875cb0da0e4b)
27 parries / 500 casts ~ 5,4%

3. test
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/314ab55a-17af-4421-9bd1-ad03ed544bf7)
25 parries / 500 casts ~ 5%

I see nothing wrong here. 
Random is random. If you are out of luck, you may have 3-5 parries in a row and then within 100 next attacks on that target no single parry at all.

**Comment by SimonBpvp** [comment]
Uhdk does get naturally high parry chance from strength (it might be like 20%?).

**Comment by UltraNix** [comment]
No further info - closing.
