### ISSUE TITLE
Quest bug(s): [Up To The Challenge] & corresponding daily quests

### ISSUE THREAD

**Issue by Haltus-Kain** [gamefreedomgit/Maelstrom#5451]
**Description:**
WotLK | Icecrown | Quest | [[Up To The Challenge]](https://warcraft.wiki.gg/wiki/Up_To_The_Challenge_(Alliance))
Starting [[Up To The Challenge]](https://warcraft.wiki.gg/wiki/Up_To_The_Challenge_(Alliance)) (Alliance version) requires 15 [[Aspirant's Seal]](https://warcraft.wiki.gg/wiki/Aspirant%27s_Seal) for completion, which are awarded by the daily quests listed below - these quests do not become available upon starting [[Up To The Challenge]](https://warcraft.wiki.gg/wiki/Up_To_The_Challenge_(Alliance)).

Bugged daily quests:
[[A Blade Fit For A Champion]](https://warcraft.wiki.gg/wiki/A_Blade_Fit_For_A_Champion_(Alliance_Aspirant))
[[A Worthy Weapon]](https://warcraft.wiki.gg/wiki/A_Worthy_Weapon_(Alliance_Aspirant))
[[The Edge of Winter]](https://warcraft.wiki.gg/wiki/The_Edge_Of_Winter_(Alliance_Aspirant))
[[Training In The Field]](https://warcraft.wiki.gg/wiki/Training_In_The_Field_(Alliance))
[[Learning The Reins]](https://warcraft.wiki.gg/wiki/Learning_The_Reins_(Alliance))
*there are Horde version of all of these as well - unsure if those are working or not.

**How to reproduce:**
Start [[Up To The Challenge]](https://warcraft.wiki.gg/wiki/Up_To_The_Challenge_(Alliance)). Playing on a Human Death Knight named "Haltus".

**How it should work:**
Daily quests mentioned above should activate, allowing accrual of [[Aspirant's Seal]](https://warcraft.wiki.gg/wiki/Aspirant%27s_Seal).

Progression through the Argent Tournament is dependent on this chain, including access to the quartermaster.

/salute

![image](https://github.com/gamefreedomgit/Maelstrom/assets/87287845/2ea3b547-86dd-4162-a3c9-45dbc13d5f4f)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/d36f9319-1057-49f8-bfd1-e8169716ef9e)

actually they should be available with Up To The Challenge :)

fixed 26.03.2024
