### ISSUE TITLE
Quest bug: [Among the Champions]

### ISSUE THREAD

**Issue by Haltus-Kain** [gamefreedomgit/Maelstrom#5452]
**Description:**
WotLK | Icecrown | Quest | [[Among the Champions]](https://warcraft.wiki.gg/wiki/Among_the_Champions)
Objective is to collect 4 [[Mark of the Champion]](https://warcraft.wiki.gg/wiki/Mark_of_the_Champion_(Argent_Tournament)) by defeating faction Champion such as [Stormwind Champion](https://warcraft.wiki.gg/wiki/Stormwind_Champion).

The champions can be fought, but the combat is buggy, with their healthpools randomly resetting or combat just randomly ending. They can be defeated, buggy combat permitting, both via normal combat and by mounted jousting combat; but when they're killed they don't award a [[Mark of the Champion]](https://warcraft.wiki.gg/wiki/Mark_of_the_Champion_(Argent_Tournament)).

**How to reproduce:**
Challenge a Faction Champion to combat. Playing on a Human Death Knight named "Haltus".

**How it should work:**
Jousting combat to get their health to 0 - they're not supposed to actually die, but admit defeat, end combat, and award a [[Mark of the Champion]](https://warcraft.wiki.gg/wiki/Mark_of_the_Champion_(Argent_Tournament)).

[[Among the Champions]](https://warcraft.wiki.gg/wiki/Among_the_Champions) is one of only a few sources of [[Champion's Seal]](https://warcraft.wiki.gg/wiki/Champion%27s_Seal), a currency used to purchase many desirable items such as mounts, pets, a tabbard with a teleport, and a vendor summon.

**Comment by PanJanuszek** [comment]
fixed 25.03.2024
