### ISSUE TITLE
Omnotron Defense System

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5454]
1. There should be 1 order of bosses activation per id,as example:
Electron>Magmatron>Toxitron>Arcanatron and it should be every pull. Currently players can change that with reseting the boss

2.On heroic difficulty Nefarian should emport next ability that is used by constructs every 35 seconds. Currently this is not time based and there are cycles when empowered abilities are not occuring.

3.Grip of Death is casted on guardians, should be only casted on player

4.There is issue with chemical bomb and dbm calling this out. Nearly always wrong person is sending information that its casted on him

**Comment by UltraNix** [comment]
Fixed.
