### ISSUE TITLE
Chimaeron

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5455]
Currently when boss casts Mortality which reduce healing done by 99%, other auras are overwritting this
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/649d9501-fb30-408c-b560-125d7d9b621d)
As example
- blood dk can still stakc absorb via mastery even when it should be reduced by 99%
- using vampiric blood overwrites te 99% reduction
-Guardian spirit healing modifier shouldnt work on that spell. Only if targets die it should set his hp to 40$
-only power word shield absorb shouldnt be affected by this since its absorb and not heal

**Comment by UltraNix** [comment]
Fixed.
