### ISSUE TITLE
Bastion of Twilight

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#5458]
1.Trash at entrace is not fully scripted. Those 4 golden orbs inside each pack should channel dmg on nearby players. Only killing whole pack of Twilight Phase-Twister should desotry orb
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/57e52541-ef97-4feb-b0af-40678bdda5ff)

2.Halfus Wyrmbreaker
After player release dragon, he should cast his spell to weakness Halfus and then Halfus should enslave them
https://youtu.be/gRnAfntR0BY?t=22

3.Theralion should be targetable 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/8c5b767d-7e36-40de-a782-b7d0f0bb14f0)

4.Ascendant Council
Lighting Rod shouldnt be casted on tanks

5.Cho gall
1.Fester Blood should have unlimited range, if raid fails to kill everyone should gain corruption stacks
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/205fd3eb-a00f-4b19-ab98-a411c343db53)
2.Mages can reset corruption with Invisibility
3.When player reach 100 corruption he shouldnt be healable
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/c9141f3b-f858-4f54-893b-de60b41a9727)
Currently beacon from holy paladin and attonement bypass this and allow player to be healed,

6.Sinestra
1.Twilight Drake is getting aggro on his way to land on platform. he shouldnt aggro on any player till he lands
2.Drake also has ability to drink pools from whelps. currently this is workign with drake corpse. Should only work when drake is alive
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d4021e71-5f4c-4376-8ad1-72403adc2a3e)
There is issue with phase 2. Currently you have to push both eggs during single "push phase - when sinestra lost her mana" if you fail Calen will be oneshotted by boss and raid will wipe. On retail after each push phase Sinestra regained her mana and after she reach 0 mana again same push phase should happen.

**Comment by UltraNix** [comment]
Fixed.
