### ISSUE TITLE
[mage] mirror image and db

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5460]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
copies from mirror image should break db

**How to reproduce:**
use mirror image and later db

**How it should work:**
copies frim mirror image should break db

**Database links:**
https://wowpedia.fandom.com/wiki/Dragon%27s_Breath
https://wowpedia.fandom.com/wiki/Mirror_Image

https://youtu.be/u7W75EXoev4?t=585 in next 10-15 sec we can to understand how work mirror image and db

**Comment by mipanka** [comment]
But it only for db, copies still should stop attack if target in polymorph, blind and etc.

**Comment by UltraNix** [comment]
Fixed.
