### ISSUE TITLE
hunter's Camouflage 

### ISSUE THREAD

**Issue by Eskelgun** [gamefreedomgit/Maelstrom#5461]
**Description:** **How to reproduce:**
Camouflage in hunter is very bad, activate Berserking (Troll Racial)
should'nt take off the Camouflage or order pet to attack either.

**How it should work:**
Camouflage says that when you or your pet receive/do damage it will take
off.

**Database links:**

**Comment by Sketish** [comment]
Waiting for database links

**Comment by UltraNix** [comment]
No further info - closing.
