### ISSUE TITLE
Talkin' Tonks quest

### ISSUE THREAD

**Issue by Chrisdev00** [gamefreedomgit/Maelstrom#5462]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The Talkin' Tonks quest doesnt work, it cannot be completed because every time you repair a Tonk that you find at the darkmoon fair it doesnt count as repaired.

**How to reproduce:**

**How it should work:**
This quest requires no additional items, simply target a [Damaged Tonk] and use the [ Battered Wrench] provided.

**Database links:**
https://www.wowhead.com/es/quest=29511/hablando-de-tonques

**Comment by UltraNix** [comment]
#5409
