### ISSUE TITLE
Shaman - Earthliving

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5463]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I remember a discussion here about earthliving during t12 where people were debating proc rate of it and that it was lowered. During a raid, our rsham healed Ultraxion and got no proc at all during the whole fight. 1389 tick of healing rain and not a single earthliving proc. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/38afbe71-0368-45ec-9b61-f23dfc9789b0)

Same  happened on wm, spine and madness

wm:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/1d77be8c-3ccd-4fe2-88ca-4f98747aefc0)

spine:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/b7409ba7-e7e1-4b7c-954d-90567233f34b)

madness:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/105b875a-61f3-4b18-bc02-c4fbe831e0ea)

2842 healing rain tick on madness and we did drop below 35% hp

On other bosses he did have some earthliving proc, i'm gonna show screenshot for comparaison sake

morchock: 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/16ac2a59-4c00-4824-a668-f891be91f737)

zon:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/cf8f52bc-3933-4ddb-a4d4-daa0092acdd2)

yor:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/e9c3e673-1c54-4347-89fd-3a68225cfff7)

Hagara:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/97857207-cf21-46bf-bc27-73af478a914a)

After posting those ss, i realize that its when we switched from hc to nm after pulling ultraxion once that it started not proccing. We had to all leave the instance to switch.

**How to reproduce:**

i don't know. maybe its just a log issue and it did proc. maybe there is an issue with it proccing from healing rain since he mainly uses healing rain.

**How it should work:**

Earthliving should proc at least sometimes.

**Database links:**

http://cata-shoot.tauri.hu/?spell=51945

**Comment by Polynomix** [comment]
I just remember that the shaman's game crashed during ultraxion hc (earthliving was working) and then we switched to nm and never saw an earthliving proc from there

**Comment by UltraNix** [comment]
You are sure that Eartliving Weapon was applied on his weapon after the game crash?

**Comment by Polynomix** [comment]
he cant unleash without it

**Comment by UltraNix** [comment]
I tried different things: disconnects, crashes, etc - no result. Earthliving still works okay.

**Comment by Polynomix** [comment]
yes, also we didn't realize until the end of the raid, so maybe just a relog or a refresh of the buff would have fixed it

**Comment by UltraNix** [comment]
I will wait like 1-2 more IDs and then close it if no new info there.

**Comment by UltraNix** [comment]
As stated above - closing.
