### ISSUE TITLE
[Hunter]---"Bad manner" and "Roar of Sacrifice"

### ISSUE THREAD

**Issue by Setikx** [gamefreedomgit/Maelstrom#5464]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hunter's dismissing and resummon another monkey-pet shouldn't refresh CD of monkeystun "Bad manner" and "Roar of Sacrifice". Technikally hunter have 4 monkeys and all of them dont share the cooldown of those spells.  

**How to reproduce:**
Tame 4 monkeys in Stranglethorn vale with those abilities. Use both of them, than instantly dismiss current monkey #1 and summon monkey #2 - those spells wont have CD.  Same for monkeys #3 and #4. 

**How it should work:**
All monkeys have to share CD of "Bad manner" and "Roar of Sacrifice" spells.
Hunters on retail in 2012 year were using Monkey, crab, spider, tiger in their arsenal with different spells but not 4 monkeys and 1 tiger. 

**Database links:**
https://www.wowhead.com/wotlk/spell=53480/roar-of-sacrifice
https://cata-twinhead.twinstar.cz/?spell=90337#comments
PS: Twinstar hunts have the same bug. 

Video of PVP: Hunter Gladiator from official Blizzard servers (no resummonning 4 monkeys):
https://www.youtube.com/watch?v=uxYgZMaR9zU

**Comment by mipanka** [comment]
Not a bug

**Comment by Sketish** [comment]
Was diccussed already 1350385963509386093 times, pet didnt share cd on retail cata. Not a bug

**Comment by Setikx** [comment]
> Was diccussed already 1350385963509386093 times, pet didnt share cd on retail cata. Not a bug

Any video evidence 12-14 years old?

**Comment by Sketish** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3019#issuecomment-1674364013
