### ISSUE TITLE
Battle at Valhalas: Fallen Heroes (Icecrown)

### ISSUE THREAD

**Issue by Anderzrez** [gamefreedomgit/Maelstrom#5466]
[[//]: # (http://wowhead.com/)](https://www.wowhead.com/wotlk/quest=13214/battle-at-valhalas-fallen-heroes)

**Description:**
The event starts when you accept the quest and the mobs spawn but once they are killed they give no credit. Abandoning the quest to retake it also doesnt work and the NPC stays up in the air flying with no quest to retake.

**How to reproduce:**
I was given the quest for a second time and i tried to do it by killing them without my pet. Still no luck.

**How it should work:**
You have to kill all of the Fallen Heroes to complete the quest.

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/93f6b564-5282-4a24-a65d-17398359243d)

can't reproduce

**Comment by PanJanuszek** [comment]
fixed after restart
