### ISSUE TITLE
Ferocitas the Dream Eater (Quest)

### ISSUE THREAD

**Issue by voit47** [gamefreedomgit/Maelstrom#5467]
![WoWScrnShot_010924_152840](https://github.com/gamefreedomgit/Maelstrom/assets/156099976/6ea53301-99f5-43b5-bdaf-e276391336d6)

**Description:**
I can't take quest (https://www.wowhead.com/quest=2459/ferocitas-the-dream-eater) after completed required (The Emerald Dreamcatcher)

**How it should work:**
That quest should be available after completion of first part of quest chain (The Emerald Dreamcatcher)

**Database links:**
https://www.wowhead.com/quest=2459/ferocitas-the-dream-eater

**Comment by UltraNix** [comment]
Fixed.
