### ISSUE TITLE
t13 set bonus on sp do not work

### ISSUE THREAD

**Issue by Ddemoncore** [gamefreedomgit/Maelstrom#5468]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
t13 set bonus do not work properly
https://youtu.be/D8K2ihNuxDc

**How to reproduce:**
Dark Spirits should give the priest 3 stacks of orbs

**How it should work:** 
Your Shadowfiend and Shadowy Apparitions have a 100% chance to grant you 4 Shadow Orbs each time they deal damage.

**Database links:**
https://cata-shoot.tauri.hu/?spell=105844

**Comment by UltraNix** [comment]
#5444
