### ISSUE TITLE
Dragon Soul 10man Hagara lightning issue

### ISSUE THREAD

**Issue by Battledamn** [gamefreedomgit/Maelstrom#5469]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During lightning phase of Hagara in 10 man Norm and HC when charging the pillars the lightning seems to bug out if you use any kind of magic immunity while connecting. The visual effect gets stuck on you, which later on prevents you from getting the effect again and actually connecting.

**How to reproduce:**
When the lightning phase starts and the add dies start moving the lightning to a pillar, but use any magic immunity (like AMS or Cloak) in the meanitme. The effect will get stuck on you, and you will not be able to contribute to pillars even after the immunity ends.

**How it should work:**
The pillar connection should reset after the immunity ends, letting you contribute to pillars, if the chain is unbroken.

**Database links:**

**Comment by Waroxx-QA** [comment]
Already reported but i'll keep it 
@UltraNix

**Comment by Battledamn** [comment]
was unable to find report, sorry about the duplication

**Comment by Waroxx-QA** [comment]
> was unable to find report, sorry about the duplication

it wasn't reported on github dw

**Comment by UltraNix** [comment]
Fixed.
