### ISSUE TITLE
Dragon Soul - Ice Lance debuff - Hagara NM

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5470]
Ice Lance debuff ( -25% attack speed ) shouldn't stack, getting hit again only refresh the timer instead of giving another stack.

While Heroic mode debuff of Ice Lance should stack ( +25% frost damage per stack ) [THIS ONE IS WORKING]

I couldn't find the ID of the debuffs so please when you fix the normal one make sure that the heroic one isn't touched.

**Comment by UltraNix** [comment]
https://youtu.be/lx_O-QD3NeU?t=37
You can see clearly more than 1 stack of Ice Lance.

https://youtu.be/rFXfw-iluXI?t=555
Same here.

https://youtu.be/jABnOkUfVMY?t=115
And again.

Not a bug.
