### ISSUE TITLE
Dragon Soul - Ultraxion HC - Fading light debuff on Both tanks

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#5472]
Seems like feral off tank is still having an issue with the debuff, as you can see on [this video](https://www.twitch.tv/videos/2025730631?t=01h31m51s) both tanks Bdk + Feral got the debuff, even if the Feral had Last Defender of Azeroth debuff.
He was in cat form but since he got last defender he shouldn't get the debuff no matter which form he's using, feral should just be in bear form when Thrall casts the buff on tanks in the beginning to be counted as a tank.

**Comment by Polynomix** [comment]
https://www.twitch.tv/videos/2025730631?t=2h37m53s
also sometimes it's not the tank with current aggro who gets the debuff

**Comment by UltraNix** [comment]
@Polynomix But your offtank got it.

**Comment by UltraNix** [comment]
@Waroxx-QA So let's assume - main tank already have the Fading Light, the offtank is in feral form -what should happen? If feral is not counted as a tank, who gets the tank debuff?

**Comment by Polynomix** [comment]
not according to waroxx

**Comment by Waroxx-QA** [comment]
> @Polynomix But your offtank got it. It's either main or off tank to get it.

there is no tank debuff, it's target debuff.

Fading light = Target + Two random players

Target part has no exceptions. if you are tank / heal / dps and you are targetd by the boss when he casts fading light you get the target debuff.

Two Random players part has two exceptions, Having Last defender debuff ( if you have it and you are not targeted ), or if you are a healer, the rest can get the debuff.

**Comment by UltraNix** [comment]
Fixed.
