### ISSUE TITLE
Hunter Quest! Bug

### ISSUE THREAD

**Issue by Ateenaa-Tik** [gamefreedomgit/Maelstrom#5473]
https://imgur.com/a/PAC13mw

Quest: https://www.wowhead.com/quest=8658/strikers-leggings

Raid: https://www.wowhead.com/zone=3428/temple-of-ahnqiraj

**Description:**

The mission is Bug, it does not allow the mission to be delivered when I give it continue to deliver it, it does not continue, please fix it! 

Also in that same raid on the Twin Emperors boss, they do not give loot. I have killed him several times and he has never given me loot.

https://www.wowhead.com/npc=15276/emperor-veklor

**Comment by PanJanuszek** [comment]
Cannot reproduced, I set raid group, have completed quest. I was able to finish? Can you try to do it on enGB / enUS client version?

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/5286794e-eb72-4996-9ccf-fb73bf974c3c)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/655eb614-4b7e-4198-bdf8-875418352856)
