### ISSUE TITLE
Quest ID 29305 Strike at the Heart

### ISSUE THREAD

**Issue by hh2h** [gamefreedomgit/Maelstrom#5474]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At the End of my Veteran of the Molten front achievement I struggle with finishing that quest, because every time doing quest I see 2 spammed Lieutenants and one of every time is Devout Harbinger.  

What is it at the moment:
https://youtu.be/BpfRmNVhC5M

**How to reproduce:**
Eliminate one of 2 Lieutenant and rotate them.

**How it should work:**
According me during that quest it must be spammed only 1 Lieutenant.

**Database links:**
https://www.wowhead.com/quest=29305/strike-at-the-heart

**Comment by Sketish** [comment]
So there is no rotation each day ?

**Comment by hh2h** [comment]
Every day there are two lieutenants. One changes and the other is Devout Harbinger.

**Comment by hh2h** [comment]
I haven't seen Ancient Smoldering Behemoth and Ancient Charscale appear yet. I don't know if this has any bearing on my report. I'm worried that only 3 out of 5 lieutenants are only staked.

**Comment by hh2h** [comment]
Another thing for today. If i take quest from the first time today after I compleate chain, I see 1 lieutenant, but if i die or abandone the quest they spam 2 lieutenants.

**Comment by UltraNix** [comment]
Fixed.
