### ISSUE TITLE
character entrance bug

### ISSUE THREAD

**Issue by sassdae** [gamefreedomgit/Maelstrom#5475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**when i ennter to one of my characters it logs me out of the server

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Contact to our GMs on Discord channel.
