### ISSUE TITLE
Incorrect operation of the T13 set of the priest of darkness.

### ISSUE THREAD

**Issue by Grentanks1** [gamefreedomgit/Maelstrom#5476]
Hello. The Priest of Darkness' kit 4 T13 does not work correctly. When damage is caused by twilight ghosts, the set does not trigger, and accordingly the priest does not receive 3 spheres of darkness.

I refer to the description of the T13 set "When your Shadowfiend or Twilight Wraith deals damage, the Priest instantly receives 3 orbs of darkness.

**Comment by UltraNix** [comment]
#5444
