### ISSUE TITLE
Naxxramas Patchwork Hateful strike

### ISSUE THREAD

**Issue by Skyfangneko** [gamefreedomgit/Maelstrom#5477]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:me and my guild are doing Naxxramas and while were doing the undead wing the hateful strike is hitting the primary target.**

**How to reproduce: with a 10 man group the boss is hitting the main tank. **

**How it should work: it should be hitting the person with the 2nd most amount of threat.**

**Database links:
![image_2024-01-10_171303413](https://github.com/gamefreedomgit/Maelstrom/assets/149633465/d0f18c05-495e-4743-8a48-5da2d3d2a102)
**

**Comment by PanJanuszek** [comment]
fixed 04.04.2024
