### ISSUE TITLE
Naxxramas Thaddous teleporter didnt spawn after boss kill

### ISSUE THREAD

**Issue by Skyfangneko** [gamefreedomgit/Maelstrom#5478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:*
![image_2024-01-10_182740051](https://github.com/gamefreedomgit/Maelstrom/assets/149633465/2e1c5370-b92d-467d-b46e-985fe0ef0676)
*

**How to reproduce: we killed thaddous and his teleporter did not spawn**

**How it should work: when you kill thaddous he spawns a teleporter to get back to the beginning of the raid**

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
