### ISSUE TITLE
Naxxramas Heigan the Unclean is not targetable.

### ISSUE THREAD

**Issue by Skyfangneko** [gamefreedomgit/Maelstrom#5479]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: me and my guild wiped after the 2nd  phase of Heigan the Unclean and when we came back he became untargetable**

**How to reproduce:**

**How it should work:**

**Database links:
![image_2024-01-10_191158901](https://github.com/gamefreedomgit/Maelstrom/assets/149633465/37041919-a333-4e78-97cd-8777b90f3188)

**

**Comment by UltraNix** [comment]
Fixed.
