### ISSUE TITLE
Naxxramas Instructor Razuvious

### ISSUE THREAD

**Issue by Skyfangneko** [gamefreedomgit/Maelstrom#5480]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:while fighting and killing Instructor Razuvious his Death Knight Understudies stayed alive under our control**

**How to reproduce:**

**How it should work: the Death Knight Understudies shouldve despawned when the boss has been killed**

**Database links:**
![image_2024-01-10_193052905](https://github.com/gamefreedomgit/Maelstrom/assets/149633465/24574a2c-1d65-46af-a381-aacb52b0eab5)

**Comment by UltraNix** [comment]
Fixed.
