### ISSUE TITLE
Naxxramas 4 horsemen ones dead

### ISSUE THREAD

**Issue by Skyfangneko** [gamefreedomgit/Maelstrom#5481]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: me and my guild are doing the 4 horsemen fight and korthazz is dead even after wiping
![image_2024-01-10_200112194](https://github.com/gamefreedomgit/Maelstrom/assets/149633465/b719e402-268c-4f88-a321-88be339b0dbc)
**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
