### ISSUE TITLE
Dragon Soul - Cannot talk with Kalecgos to start the battle with Ultraxion

### ISSUE THREAD

**Issue by flyingevelyn** [gamefreedomgit/Maelstrom#5483]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
We met bugs again after Hagara the Stormbinder. Our RL just changed the difficulty inside. Again we can not talk with Kalecgos to start the battle with Ultraxion. 

**How to reproduce:**
We killed the Hagara in the Heroic difficulty. Then the RL changed the difficulty to normal inside for the rest bosses. When we walked out and found we can not talk with Kalecgos to start Ultraxion.

**How it should work:**

We talk with Kalecgos to start the battle with Ultraxion
**Database links:**

https://www.wowhead.com/npc=55689/hagara-the-stormbinder

**Comment by UltraNix** [comment]
#5439
