### ISSUE TITLE
Daily Reward of Conquest Points for a BG win !

### ISSUE THREAD

**Issue by devialey** [gamefreedomgit/Maelstrom#5484]
**Description:**  The Daily reward of Conquest Points towards the players that queue Random Battlegrounds is totally nonexistant with the introduction of Season 11 in the Maelstrom realm, Players right now are only getting Honor through BGs..

**How it should work:** In Season 11 players should be able to get rewarded with a 100 Conquest Points for a daily win with a BG, then get rewarded 50 Conquest Points for each win!

- Here's a website that provides the evidence of how it should be working : https://www.engadget.com/2011-11-17-patch-4-3-ptr-valor-and-conquest-point-changes.html

**Comment by Renehadox** [comment]
Confirmed.

**Comment by UltraNix** [comment]
Fixed.
