### ISSUE TITLE
Gurthalak procs 3-4 tentacles at once bug

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I dueled a ret paladin in duel zone and Gurthalak spawned 4 tentacles in a time span of 3 seconds.

Thats blizzlike or a server bug?

I decided to post it here.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Any melee hit/ability has a 2% chance to spawn tentacle. Just rng
