### ISSUE TITLE
Ignition Uldum Quest Bug

### ISSUE THREAD

**Issue by Joaokfa** [gamefreedomgit/Maelstrom#5486]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The ignition quest in Uldum is kind of broken first the orbs that the players should use to guardian fall through the ground only after 5th or 6th i got one to hit the guardian, and then the quest item doesnt drop.

**How to reproduce:**

**How it should work:**
One orb that we could use to hit the guardian and the item to drop after guardian dead.

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after update
