### ISSUE TITLE
Shadow Priest Shadowy Apparition damage bug or proc is high?

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5487]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I did arena match vs shadow priest and shadowy apparition according to details addon was second most damage done spell of the shadow preist, during retail cata shadowy apparition didn't do much damage.

There is definitely something wrong with the talent or the priest is just abusing something we dont know.

Its only a 12% chance to proc.

**How to reproduce:**
![WoWScrnShot_010324_231427](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/dff03c90-be46-4819-9f67-9f57ac8befc3)

**How it should work:**

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=78204 - the talent from shadow priest tree

https://cata-twinhead.twinstar.cz/?spell=589 - Shadow word pain

**Comment by Sketish** [comment]
If you are moving it has higher chance to proc. So we need more details

**Comment by Renehadox** [comment]
Still doing second most damage from that battle is absurd, talent needs a recheck.

**Comment by Hermeleen** [comment]
Shadow apparition is indeed a bit op on this server, back on apollo you could target it and kill it, here you can't. Don't know what is retail mechanics tho.

**Comment by Pornoodemon** [comment]
Maybe this talent should have an ICD? The thing is that shadowy apparition seems to
  works non-stop and there are too many of them

**Comment by bonfax4** [comment]
Hmm there shouldn't be a CD between procs. Seen videos where they proc quickly on succession like [this](https://youtu.be/k62F95s1_5w?t=27s). But there's a possibility that each of the 4 summon have their own icd but dunno. 

Also apparitions that lose their target ( via death, vanish, feign ) should go back to the priest and stand there for their full 19-20 sec duration  and I dunno if that happens currently on live, but should reduce procs vs certain classes.

**Comment by Renehadox** [comment]
> Hmm there shouldn't be a CD between procs. Seen videos where they proc quickly on succession like [this](https://youtu.be/k62F95s1_5w?t=27s). But there's a possibility that each of the 4 summon have their own icd but dunno.
> 
> Also apparitions that lose their target ( via death, vanish, feign, etc ) should go back to the priest and stand there for their full duration (18-20 sec duration ) and I dunno if that happens currently on live, but should reduce procs vs certain classes.
> 
> https://youtu.be/zkqe-RPGvwM?t=3m50s. 5 procs in a 12-14 sec timespan so if there's an icd per "apparition slot" it can't be more than that.

the SA walk on your video and here on whitemane they run and doing second most damage out of all the spells is kinda ridiculous.

@Sketish

**Comment by bonfax4** [comment]
They are targetable btw, but I still haven't seen anyone killing them. Not affected by aoe either. They have 5 HP.

https://youtu.be/8NHpB43oCr8?t=5m9s

**Comment by Renehadox** [comment]
> Shadow apparition is indeed a bit op on this server, back on apollo you could target it and kill it, here you can't. Don't know what is retail mechanics tho. Also i don't think it is damage problem, i think it's the fact that every apparition hits, because you cannot avoid it. Unless kiting it of course, which could make you leave pillar so it's lesser of two evils so to speak.

https://www.youtube.com/watch?v=8NHpB43oCr8&t=309s&ab_channel=Sacredheals

@Sketish @bonfax4 what about shadowy apparition base damage and its coefficients ?

I think its doing higher than it should be.

**Comment by UltraNix** [comment]
Fixed.
