### ISSUE TITLE
"Crimson shale spider" PET BUGGED

### ISSUE THREAD

**Issue by ArchiveGodx** [gamefreedomgit/Maelstrom#5488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
This pet been buggy for over a month or more, when its inside small houses or in warsong gulch tunnel i cant use its abilities and i cant dismiss it either, i cant dismiss and the pet wont be able to attack until its outside these areas,i also cant dismiss the pet in eye of the storm purple bubble,i

**How to reproduce:**
the pet is called "Crimson shale spider" you can tame it from deepholm,its been bugged like that for a long time,ive tried to tame a new one, or kill the one i have then revive or reset talents clearing cache it didnt help, ive tried other pets they all work fine only this one doesnt.

**How it should work:**
it should be able to use its abilities in those small areas(houses,tunnels etc) and i should be able to dismiss the pet anywhere as long as its next to me.

**Database links:**
https://www.wowhead.com/npc=44425/crimson-shale-spider#drops

**Comment by Hermeleen** [comment]
The tunnel in gulch is indeed buggy sometimes, for example i saw dk summon a gargoyle, and it spawned in the floor above (just below roof and ground floor.), and the garg had to pathfind over into the tunnel taking 15 seconds ish, which is basically wasted cd. Tho i am not sure how often it happens, as in, if it happens at every spot in the tunnel, or at certain place only. I wanted to report it, but i didn't have it recorded and haven't seen any other dk summon garg there.

**Comment by djesic** [comment]
I reported devilsaur can't be dismissed in EOTS bubble #4776 
It seems like the pet collision size is massive and that messes up pathfinding for using abilities. (charge, web wrap)
Might be affecting more types of summons? (gargoyle)

**Comment by UltraNix** [comment]
Fixed.

**Comment by ArchiveGodx** [comment]
thanks alot.
