### ISSUE TITLE
[rogue] gouge and vial of shadows

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
dmg proc from trinket vial of shadows break effect gouge incapacitating 

**How to reproduce:**
use gouge 

**How it should work:**
proc vial shouldn break effect gouge incapacitating 

**Database links:**
https://wowpedia.fandom.com/wiki/Gouge
https://wowpedia.fandom.com/wiki/Vial_of_Shadows  fix need for all version normal/hc/lfr
original videos
https://www.warcraftmovies.com/movieview.php?id=220655
https://www.warcraftmovies.com

https://github.com/gamefreedomgit/Maelstrom/assets/127995853/5567aea0-a9c8-433a-9189-854cf685cf74

/movieview.php?id=220655&stream=69

**Comment by bonfax4** [comment]
Yeah the server does not have the cc break immunity iirc, haven't played the n a while so I dunno if that changed. Should be @ 0.5 sec window or w/e, dunno the actual value. I've seen weird scenarios where frost nova breaks instantly too ( immunity should also apply to cc with dmg thresholds )

**Comment by Hermeleen** [comment]
> Yeah the server does not have the cc break immunity iirc, haven't played the n a while so I dunno if that changed. Should be @ 0.5 sec window or w/e, dunno the actual value. I've seen weird scenarios where frost nova breaks instantly too ( immunity should also apply to cc with dmg thresholds )

I think it does, you can sheep/cone or sheep/nova. Also mages immune cc for a tiny bit of time after blinking.

**Comment by bonfax4** [comment]
Well, did they only apply it to mage cc and not every cc in the game ?

**Comment by UltraNix** [comment]
Fixed.
