### ISSUE TITLE
[Item] [Cunning of the Cruel] proc is bugged 

### ISSUE THREAD

**Issue by Dimzy2** [gamefreedomgit/Maelstrom#5490]
[//]: # (https://cata-twinhead.twinstar.cz/?item=78000)

**Description:**
[Cunning of the Cruel] proc in the game hit one enemy only even when they are in 10 yd space , it hit properly when the player in a crowd controlled like cyclone

**How to reproduce:**

Just fixed it like you see in the video link 

**How it should work:**
https://youtu.be/HRxzq-AR2-4?si=iPmzmbHHhUkZOUa4

**Database links:**

**Comment by UltraNix** [comment]
@Dimzy2 Just tested in the same dummy as on the videos and see no difference with our server - works the same way.

**Comment by UltraNix** [comment]
Fixed.
