### ISSUE TITLE
[DS] Spine - Blood Corruption : Death explode prematurely

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5491]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

We had one Blood Corruption : Death explode prematurely on spine it was not even past half the duration and it exploded.

In the clips below if you watch carefuly, the mage got another debuff right before we dispelled the drood and it went on the mage also.

**How to reproduce:**

https://clips.twitch.tv/DreamyMiniatureSowTooSpicy-6Tj7OpWd5t6TmjMy

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/2e9e76b3-9eb7-455b-9656-2eac199999d0)

**How it should work:**

should explode when duration expires only or should not go to someone who already has one when dispelled.

**Database links:**

http://cata-shoot.tauri.hu/?spell=106199

**Comment by UltraNix** [comment]
Fixed.
