### ISSUE TITLE
[item] [Electrostatic Condenser}

### ISSUE THREAD

**Issue by Lightmace** [gamefreedomgit/Maelstrom#5492]
Description:

It allows you a chance to get Volatile Air when you are mining, shinning, or collecting herbs but I have gathered over 1500 herbs and have not got a single Volatile Air from it

How to reproduce:

craft item and go pick flowers

How it should work:

should be getting some Volatile Air

**Comment by Sketish** [comment]
It has super low chance, you can check previous reports about it

**Comment by Lightmace** [comment]
> It has super low chance, you can check previous reports about it

Yes I know its a low chance its like 6% I believe but now that my count is up to 2300 herbs gathered and have not got a single one meaning that something isnt working correctly. I should have gotten a few by now

**Comment by UltraNix** [comment]
Remember that it drops only from Cata herbs/mines.
Also - chance is calculated per herb/mine opened, not per herbs/ores count.

Made a test (with small modification - one herb gives exactly one item and Condesator gives exactly one air).
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/5df0f11c-a794-4184-978b-221b07bd688c)
200 herbs and 12 Volatile Air - 6% chance.
