### ISSUE TITLE
Bug Rshamy T 13 DONT WORK Two tokens 

### ISSUE THREAD

**Issue by Manjaroid** [gamefreedomgit/Maelstrom#5493]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hello . i looked bug for rsham do not work T 13 totem mana tide, dont give for you 30 % reduce  mana for skill

**How to reproduce:**

**How it should work:**

Should give for you 30% reduce for mana cost skills
**Database links:**

**Comment by Sketish** [comment]
Duplicate
