### ISSUE TITLE
Lightning Conductors on Hagara Heroic working inconsistantly

### ISSUE THREAD

**Issue by TEIWASTAKEN** [gamefreedomgit/Maelstrom#5495]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My guild was doing hagara heroic last night on 10 man and the lightning condusctors on cardinal directions didn't take the ligntning in to them. Also the initial condusctor had an unlimited range on it's lightning that it kept constantly on the main target doesn't matter how far they were from it

**How to reproduce:**
Do hagaras ligthning phase and try to chain the lightning from the initial condusctor to the ones furthetst away (N,E,S,W)

**How it should work:**
They should instantly get tethered to the ligthning conductors

**Database links:**

**Comment by Waroxx-QA** [comment]
Fixed, it's caused by immunities. ( like Pala bubble or HoP / Rogue Cloak )
Will be pushed on the next restart.
