### ISSUE TITLE
[warlock] dark intent

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5496]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if mage spell steal https://wowwiki-archive.fandom.com/wiki/Dark_Intent warlock still will get dmg buff

**How to reproduce:**
use https://wowwiki-archive.fandom.com/wiki/Dark_Intent and spell steal this buff

**How it should work:**
warlock should not gain a buff if enemy mage stealing dark intent

**Database links:**
https://wowpedia.fandom.com/wiki/Dark_Intent
https://wowpedia.fandom.com/wiki/Spellsteal#:~:text=Spellsteal%20is%20a%20mage%20class,from%20which%20it%20was%20stolen.

**mb report false, in my test now all fine**

**Comment by mipanka** [comment]
in new test:

https://github.com/gamefreedomgit/Maelstrom/assets/127995853/f4d9942b-035a-4e4b-b632-b4cebf1cc9b6

as we can see, I used spell steal on dark intent and warlock still getting buff from dark intent

**Comment by Waroxx-QA** [comment]
proof ?

**Comment by Pornoodemon** [comment]
Here we must add that the magician should not be able to steal the same dark intent buff from two or more targets
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/a1156dca-5cd3-4a29-93f3-d1780018b0bd)

**Comment by mipanka** [comment]
> proof ?

hope u will find, idk where take, proc buff from enemies do nothing work in game as example

**Comment by mipanka** [comment]
idk 100%, mb even not a bug

**Comment by bonfax4** [comment]
Also weird that you get to stack 2 dark intents, since they shouldn't stack at all. Also spellsteal on dark intent should break the warlock dark intent on the pet according to https://youtu.be/JMIhonqdQSw?t=2m54s. Pet lost dark intent when stolen
