### ISSUE TITLE
Random HC/HoT vs Lockout

### ISSUE THREAD

**Issue by pretty-blossom** [gamefreedomgit/Maelstrom#5497]
**Description:**
Queueing RHC or RHoT dungeons via the Dungeon Finder should not lock players.

**Proof:**
https://wowpedia.fandom.com/wiki/Patch_4.3.0#Dungeons_&_Raids

![image](https://github.com/gamefreedomgit/Maelstrom/assets/39058978/f389da5c-ec4d-4f9c-8f92-03c8cfd88d74)

This change allows players to repeatedly queue, or in other words, farm, these dungeons nonstop.

Players are currently, still getting locked out of said instances when queueing Random - making the overall farming of Hour of Twilight dungeons slow and timegated every 24 hours.

**Comment by UltraNix** [comment]
Fixed.
