### ISSUE TITLE
RHC Incorrect Valor Amount

### ISSUE THREAD

**Issue by pretty-blossom** [gamefreedomgit/Maelstrom#5498]
**Description:**
Random Heroic Dungeons should reward 150 Valor Points, not 70.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/39058978/339bbdc5-9acd-429f-a670-44e2167b2ebd)
(105 due to weekend bonus)

**Proof:**
https://wowpedia.fandom.com/wiki/Dungeon_Finder#Patch_changes

![image](https://github.com/gamefreedomgit/Maelstrom/assets/39058978/f8218c76-e5ae-48f8-8d51-2f37a8c849a2)

**Comment by UltraNix** [comment]
Fixed.
