### ISSUE TITLE
bug in quest at stonetalon mountain kalimdor

### ISSUE THREAD

**Issue by igor0546506003** [gamefreedomgit/Maelstrom#5499]
aliance continent:Kalimdor Zone:Stonetalon mountains
discribsion: bug in a quest called:Don't look them in the eyes
even after i cencel the quest the item i got from it dont disapear. and i cant cencel it afect on me.
it called Gnomecorder.
i dont get Azure iron ore from the orces i kill in the cave near by or out side of the cave as it should work.
i cant continu the quest line without finishing thise quest and i am stuck. please help.
![WhatsApp Image 2024-01-12 at 23 17 08 (2)](https://github.com/gamefreedomgit/Maelstrom/assets/53992141/177e99e7-2311-4432-93a0-ea038a25a147)
![WhatsApp Image 2024-01-12 at 23 17 08 (1)](https://github.com/gamefreedomgit/Maelstrom/assets/53992141/be4bd5a8-e7e3-455b-96f4-3070ceca208b)
![WhatsApp Image 2024-01-12 at 23 17 08](https://github.com/gamefreedomgit/Maelstrom/assets/53992141/4decc675-20a2-4023-b25c-8e011b1a8359)

**Comment by PanJanuszek** [comment]
fixed after restart. you have to be in combat with him to drop iron

**Comment by PanJanuszek** [comment]
There was no update yet
