### ISSUE TITLE
[talent] fire mage talent cauterize and proc vial (mb other proc dmg too)

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5500]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
proc items ignored cauterize

**How to reproduce:**
on low hp will try to attack 

**How it should work:**
talent should work on proc dmg from items

**Database links:**
https://wowpedia.fandom.com/wiki/Vial_of_Shadows
https://wowpedia.fandom.com/wiki/Cauterize
on my screen combat log, where I had talent cauterize, but he didnt work, but but cd appeared
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/d049677f-b704-4a1c-9672-7cb7c2b98a36)
on screen: 
-proc vial
-auto attack
-no cauterize

p.s. sometime dtr too killing me without cauterize, but I dont have combat log for show, thats why I dont added in report, I think all proc dmg can kill through cauterize or other similar talent/skill

**Comment by Revly** [comment]
I want to add (this problem has already been seen in other private Svr)

In summary.
Most PVE item attack procs with extra attacks do not trigger Cauterize.

example:
proc cruel cunning
prox not kaled
proc vishanka
proc road shadows
proc DTR
bone fetish proc

among others.

**Comment by mipanka** [comment]
there are other similar abilities, for example cheat death

**Comment by Revly** [comment]
> there are other similar abilities, for example cheat death

This yes but, is another report

**Comment by mipanka** [comment]
sometime vs retry pala didnt proc too, when from one hit few different dmg

**Comment by UltraNix** [comment]
Fixed.

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/114eaeb2-ce27-4ecd-a914-559cf945cb5e)
enemy mage died without cauterize, last hit proc vial in combat log
