### ISSUE TITLE
[Mage] Fireblast and Deep Freeze share dr /pvp

### ISSUE THREAD

**Issue by keroblus** [gamefreedomgit/Maelstrom#5501]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
its just a mini stun it shouldnt share dr with deep freeze

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by mipanka** [comment]
I tested now, all work fine
