### ISSUE TITLE
[warlock] soul link and cunning of cruel/other trinkets/chant

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5502]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
dmg from soul link triggered proc cunning of cruel

**How to reproduce:**
attack warlock with cunning of cruel and h should have pet with soul link

**How it should work:**
soul link shouldn triggerd cunning of cruel or other trinkets

**Database links:**
https://wowpedia.fandom.com/wiki/Soul_Link

https://github.com/gamefreedomgit/Maelstrom/assets/127995853/be9c15bc-ca71-49ec-b892-9f1f15f502cf

https://wowpedia.fandom.com/wiki/Cunning_of_the_Cruel

**Comment by UltraNix** [comment]
Fixed.
