### ISSUE TITLE
Warthorn Creche of the Final Dragon doesn't proc from spells

### ISSUE THREAD

**Issue by OverlordDeveloper** [gamefreedomgit/Maelstrom#5503]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The trinket ItemID: 177205 only procs from melee attacks, does not proc from spells or ranged attacks.

**How to reproduce:**
Equip the trinket and cast spells on a dummy target, it will not proc at all.

**How it should work:**
The trinket says "When you deal damage you have a chance ... " which means there is no restriction on the damage type / school, it should proc when you do damage.

**Database links:**

**Comment by Waroxx-QA** [comment]
Not a bug, that's how it works ;)

**Comment by OverlordDeveloper** [comment]
But Soulshifter Vortex has the exact same description and it does proc, in fact mages play it on this server.

What is the proof that this particular trinket should not proc, while having the same exact text as others that proc ?
