### ISSUE TITLE
Creche of the Final Dragon part 2 

### ISSUE THREAD

**Issue by OverlordDeveloper** [gamefreedomgit/Maelstrom#5505]
Not a bug, that's how it works ;)

_Originally posted by @Waroxx-QA in https://github.com/gamefreedomgit/Maelstrom/issues/5503#issuecomment-1890790320_
            
But Soulshifter Vortex has the exact same description and it does proc, in fact mages play it on this server.

Why this particular trinket should not proc, while having the same exact text as others that proc ?
And if this is how it should be, how do you know? Or is it that Soulshifter Vortex is bugged and should not proc ?

**Comment by UltraNix** [comment]
Fixed.
