### ISSUE TITLE
The quests "Wrath of the Mushroom Mancer" and "Fighting Corruption" are not completed

### ISSUE THREAD

**Issue by Accrime** [gamefreedomgit/Maelstrom#5508]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: Account: Accrime, PC: Godfrey. I can't complete quests Quest ID 26585, Quest ID 26583. When interacting with an NPC, my character attacks him. Gorsik the Tumultuous NPC ID 42472, Ruberick NPC ID 43442**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Accrime** [comment]
![1](https://github.com/gamefreedomgit/Maelstrom/assets/156562532/50cd31ed-12e4-4503-b004-75ea1570a241)
![2](https://github.com/gamefreedomgit/Maelstrom/assets/156562532/90805bf0-ebb1-4a71-9048-bfef03852610)

**Comment by Accrime** [comment]
same situation with all both factions

**Comment by Accrime** [comment]
I can only attack them

**Comment by PanJanuszek** [comment]
Cannot reproduce:

![Uploading image.png…]()
