### ISSUE TITLE
Gurthalak  bugged in PVP

### ISSUE THREAD

**Issue by freakyfrizes** [gamefreedomgit/Maelstrom#5509]
When gurthalak's tentacle spawns it doesn't instantly start attacking your target and it stands there untill you do damage, and sometimes if you dont stay constantly damaging your target it will just stand there and chill without hitting,thats happening when the tentacle has to resset it's channeled attack which it does every like 2 secs,if im not attacking the target it will somtimes just stand there afk ,basically making it useless whenever im stunned/cced or getting kitted.

**Comment by Waroxx-QA** [comment]
This is how gurthalak should work:

Attacks the target of the player even if he's not hitting his target.
if you stop targeting, it doesn't stop hitting during the cast, it stops right after the end of the cast.
if you swap target, it doesn't swap target instantly, it finishes casting on the previous target, then it swaps to the new target (on the next cast.)

**Comment by UltraNix** [comment]
Fixed.
