### ISSUE TITLE
Bugged quest in ashenvale

### ISSUE THREAD

**Issue by Daniel123000** [gamefreedomgit/Maelstrom#5510]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hi. I have a problem with a quest, in ashenvale, the quest is 'Defend the tree!' and the problem is when i transform into the ghost cat to kill the invaders, the cat doesnt have energy regen, its stand at 0 and i cant kill the orcs outside

**How to reproduce:**
do the quest 'Defend the tree"

**How it should work:**
I think the cat should have energy regen

**Database links:**
https://www.wowhead.com/quest=13935/defend-the-tree

![WoWScrnShot_011424_174236](https://github.com/gamefreedomgit/Maelstrom/assets/131005721/9aa9d28a-867b-4c0e-9ef7-24754ba04bd3)

**Comment by PanJanuszek** [comment]
fixed after restart

**Comment by Daniel123000** [comment]
thank you very much :)
