### ISSUE TITLE
recover level object

### ISSUE THREAD

**Issue by laorce** [gamefreedomgit/Maelstrom#5511]
**Description
Hice un war humano de nombre "heterosex" desde level 1, con puntos de honor de mi otro personaje compré las hombreras de leveo, luego en la zona de leveo acepte las opciones de un npc que me envió al instant 85 pvp, y se elimino mi item, intente eliminar el personaje pero no me deja.

**Comment by laorce** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/156603455/c3ef4e49-e989-4a7c-b487-4e7c4b6041cc)

**Comment by Sketish** [comment]
Translate to english

**Comment by laorce** [comment]
I made a human war called "heterosex" from level 1, with honor points from my other character I bought the leveling shoulder pads, then in the leveling area I accepted the options of an npc who instantly sent me 85 pvp, and it was eliminated my item, I tried to delete the character but it won't let me.

**Comment by laorce** [comment]
I tried to eliminate the character, but it won't let me because it says it has a relic, I proceeded to eliminate said relic which is for leveling, but it still won't continue, in conclusion I want to eliminate the "heterosex" character and recover my leveling backs that I bought with my other character and honor points "broussard"

**Comment by laorce** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/156603455/b7d8e1c7-76f9-4f63-9af6-1ba3573280c2)

**Comment by laorce** [comment]
A game master gave me an answer but I didn't understand the whole thing.

**Comment by laorce** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/156603455/09cff568-85d0-44e6-8e24-2ea29bb66380)

**Comment by laorce** [comment]
I want to have the object on my "broussard" character because previously it would be returned to the same "heterosex" character and I couldn't send it by mail to the other characters.

**Comment by xmrshoot** [comment]
Its not a Bug , @Sketish
