### ISSUE TITLE
Vazruden Reinforced Fel Iron Chest missing from Hellfire ramparts BC

### ISSUE THREAD

**Issue by Bunz123** [gamefreedomgit/Maelstrom#5513]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After you kill Vazruden and his drake a chest is supposed to appear that has a loot table for the bosses loot. As of now the boss drops nothing from his loot table and the chest does not appear.

**How to reproduce:**
n/a

**How it should work:**
This lootable chest spawns upon defeat of [Nazan](https://www.wowhead.com/?npc=17536) and [Vazruden](https://www.wowhead.com/?npc=17537) in [Hellfire Ramparts](https://www.wowhead.com/?zone=3562).

**Database links:**
https://www.wowhead.com/object=185168/reinforced-fel-iron-chest

**Comment by PanJanuszek** [comment]
tested with gm and myself, cant reproduce
