### ISSUE TITLE
Nalice. Blood of the Betrayer 

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5514]
#4460 

Could you review these final details please?

> > Nalice
> > Arcane infused weapons is not working always, after reseting her it was working correctly ![image](https://private-user-images.githubusercontent.com/122209088/278311191-5b7057ca-b9d6-4766-8691-167c0c0eeadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTM4MTEsIm5iZiI6MTcwNTIxMzUxMSwicGF0aCI6Ii8xMjIyMDkwODgvMjc4MzExMTkxLTViNzA1N2NhLWI5ZDYtNDc2Ni04NjkxLTE2N2MwYzBlZWFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNjI1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTUwOWU1MmQ4YmMxMTYzNWUxZDg2MmIwZGIzNzRjZDFlMzA4NzE2YTE5MWNjMTllNjU2YjhkZjIwZDZiZTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bnHrz2UvWn60bxqMFMjcsXwy9QJ7LFs0L85P-Li0Ug)
> > Blazing shadow was only casted once and did 0 dmg to player + infernals are visible + was no fire at the ground
> 
> https://youtu.be/XCznpE6Puhk?t=404
> 
> Nalice has some problems, currently it is very easy and it should not be
> 
> 1- In my 2 battles that I have had with her, she does not use "[Blazing shadow ](https://www.wowhead.com/spell=109988/blazing-shadows#comments) was only casted once and did 0 dmg to player + infernals are visible + was no fire at the ground " This is Continuous bug, he doesn't even use it
> 
> 2- Sometimes she interrupts herself while she is casting.
> 
> In coments = **[ Comemnts](https://www.wowhead.com/es/quest=30109/la-sangre-de-la-traidora#english-comments )**
> 
> "Click activated pillars. Avoid shizzles on the ground, plix." In a **[ Video](https://youtu.be/SDZdwR8QGoU?t=203 )** When you activate the pillars it gives you a buff that accumulates up to 2 times 2 pillars of course, this gives you damage, currently it is not giving damage.
> 
> 3- I couldn't find the buff but the clue I have is "Arcane Pillar" "object interactive think They are minimal details but I think they do matter, to add difficulty

**Comment by UltraNix** [comment]
Fixed.
