### ISSUE TITLE
Twilights Highlands Cant kill Snake Mobs

### ISSUE THREAD

**Issue by CDreger** [gamefreedomgit/Maelstrom#5515]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In Twilight Highlands you cant kill some of the SnakeMobs for the Quest on the beach.
Also you stay in combat or they follow you even into the Castle !

**How to reproduce:**
Try to kill them.
Hit one and try to escape.

**How it should work:**
Like every other Mobs that you can kill in the game.

**Database links:**

**Comment by PanJanuszek** [comment]
Cannot reproduce
