### ISSUE TITLE
Of Keys And Cages (Quest)(Howling Fjord)

### ISSUE THREAD

**Issue by Anderzrez** [gamefreedomgit/Maelstrom#5516]
https://www.wowhead.com/wotlk/quest=11231/of-keys-and-cages

All of the cages in the area are open already and cannot be used.

How it should work:

Killing the mobs in the area to get keys which can then be used to open the numerous cages in the area.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed, decreased time to wait between 30s - 60s. After server update you can check

**Comment by Whirlwind89** [comment]
As of now this quest is bugged again, cages are not opened but they are not clickable at all, so we can not free those prisoners, and we can not complete the quest now, because of that... Please fix it again..
