### ISSUE TITLE
[DS] Ultraxion - Damage reduction effect not working on Twilight Instability

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5517]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My understanding of the current state of the [Twilight instability](http://cata-shoot.tauri.hu/?spell=109176) is that it deals 500k resistable damage split evenly among everyone within 30yards of the target. So 50k resistable damage per player.

Currently every damage reduction effect used in my raid could not reduce this number.

**How to reproduce:**

[Barskin](http://cata-shoot.tauri.hu/?spell=22812) 20%, [Survival Instinct](http://cata-shoot.tauri.hu/?spell=61336) 50% : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/b4e49aaa-2928-439f-8114-a9c1f60bf60d)

[Icebound Fortitude](http://cata-shoot.tauri.hu/?spell=48792) (bdk) 50% , [Bone Shield](http://cata-shoot.tauri.hu/?spell=49222) 20% : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/f22c175e-e1cb-4ba4-8963-239f850a4a33)

[Icebound Fortitude](http://cata-shoot.tauri.hu/?spell=48792) (udk) 20% : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3c79aa37-2f0d-44b3-8b93-54e7e42e5fa6)
(the line where there is only A:30000 is because when no real damage are done and everything is absorbed, the resist part doesn't show)

[Divine protection](http://cata-shoot.tauri.hu/?spell=498) (with glyph) 40% : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/49e99c5f-704e-4b6d-845e-086c53c4c931)
(the 4th damage line we were only 8 getting hit and 5th damage line we were 9)

[Power word: Barrier](http://cata-shoot.tauri.hu/?spell=62618) 25% : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/b14af895-6df8-4f35-83d7-6ef64eb780f6)

[Natural reaction](http://cata-shoot.tauri.hu/?spell=57880)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/ddea94e0-b1c6-4bae-95ca-8d7bc11dfe65)

Use one of those spells and watch the damage before and after.

**How it should work:**

Damage reduction should work. Also seeing how it is always 50k, i'm pretty sure that damage reduction from talent like drood's [natural reaction](http://cata-shoot.tauri.hu/?spell=57880), shaman's [elemental warding](http://cata-shoot.tauri.hu/?spell=28998) and more also do not work.

**Database links:**

edit: removed hand of sacrifice as it is counted as absorb

**Comment by UltraNix** [comment]
All of these effects are not resistance effects.
Show us proofs from retail they should work.

**Comment by Polynomix** [comment]
this is not you ?
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/62625794-d1b6-49e7-9a31-28ffe40456bd)

**Comment by Polynomix** [comment]
i wont search for video proof, close this if you dont think damage reduction effect should work

**Comment by doctopo** [comment]
https://www.youtube.com/watch?v=9xpwdCaL0WU
He use divine protection at 3:37 ,around that ,so check damage he take before using it and after ,you can see with divine prot its around 18K ,without its 30K or 34K depends ,means that reduction cd should work on ultraxion aoe damage(twilight instability)

**Comment by doctopo** [comment]
Also to note ,that damage should not be resisted ,but it's doing 100K more than on retail so that arounds it to the same amount

**Comment by UltraNix** [comment]
Fixed.
