### ISSUE TITLE
Transmog

### ISSUE THREAD

**Issue by Cqueen26** [gamefreedomgit/Maelstrom#5519]
Say I have a one hand weapon. If I transmog it to look like a two handed weapon (or vice versa) does my damage, damage per second, and any stat buffs like +2 spirit, remain the same for whatever I have currently equipped? It won’t mess up or effect what I currently have equipped? Have any transmog bugs ever been reported in this context?

**Comment by UltraNix** [comment]
It's not a bug report.
Transmog does not change any stats - it's only visual.
