### ISSUE TITLE
 [MPG] DS 10nm - Warlord of Zon' Ozz: Disrupting Shadows (Bug)

### ISSUE THREAD

**Issue by TriGhost** [gamefreedomgit/Maelstrom#5520]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On 10man normal difficulty Zon' Ozz should apply his Disrupting Shadows debuff on 2 players, while
on 10man heroic difficulty the number of players with debuff should increase to 3.
Currently it applies debuff to 3 players on both normal and heroic difficulty.

**How to reproduce:**

**How it should work:**
How it should work: 
explained in the video linked below - which was recorded at retail 12 years ago 
Disrupting Shadows part from 1:18 to 1:45

**Database links:**
https://youtu.be/BHarmo4mf4k?si=OWbc6HLTKbx068lV&t=78

**Comment by UltraNix** [comment]
Fixed.
