### ISSUE TITLE
[DS][Hunter] Distracting Shot does not stop the Ultraxion trash dragons from breathing fire.

### ISSUE THREAD

**Issue by Georgiimo** [gamefreedomgit/Maelstrom#5521]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Using Distracting Shot on the dragons does not make them come to you like they should.

**How to reproduce:**

Use Distracting Shot on the dragons.

**How it should work:**

They should stop breathing fire and start chasing you.
https://www.youtube.com/watch?v=sGcB3pnYprw&t=22s

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=20736

**Comment by UltraNix** [comment]
Fixed.
