### ISSUE TITLE
Cunning of the Cruel

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5522]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://www.wowhead.com/item=78000/cunning-of-the-cruel
Does not work on a player with pets. “Perhaps with guards” or any secondary targets within a radius of 10 meters .I haven’t checked all the variations.
The arrow of darkness must hit the current target as well as all targets within a radius of 10 meters from current target
In the battle logs, damage was also inflicted only on the pet.

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/efbedd6e-f74c-46f8-bed7-c59443b60f69

If the player does not have a pet then this works fine

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/92681668-4153-40de-9a2f-7eecedb86923

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
Similar topic
https://github.com/gamefreedomgit/Maelstrom/issues/5490

**Comment by UltraNix** [comment]
Fixed.
