### ISSUE TITLE
Huargen mission

### ISSUE THREAD

**Issue by ThiagoMel** [gamefreedomgit/Maelstrom#5523]
The mission moonfire of the worgen race has bugs, it asks you to go up to level 3 and you already reach that mission with level 5. It asks you to use moonfire against Bloodfang Worgen, but when you use it it does not take it as finished.

How to play:
Due to the amount of experience one gains, you arrive at that quest at level 5 and not level 3 as requested. Please fix that bug
![270130153-cf0cbd85-7098-44ed-a78a-90dd048ac752](https://github.com/gamefreedomgit/Maelstrom/assets/156846921/2dde1931-d67a-4f58-b7d9-2e0b677df5e2)

**Comment by carrizoaagustin** [comment]
I have the same bug, I hope they can fix it soon

**Comment by PanJanuszek** [comment]
Fixed after update
