### ISSUE TITLE
Dancing rune weapons

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The problem is that dancing rune weapons simply copy 50% of the damage, ignoring armor if it is a player.
Rune weapons should work similarly to Pets and Guardians where a single copy attack should deal 50% damage but the damage from that  attack should in turn take into account resistance and armor and damage reduction modifiers. .

Proofs +-. But this should work like this by default for pets and guardians.
And runic weapons are this pet.
Today I encountered a situation when a dk summon and applied to me runic weapon and at that time he himself began to attack the dummy and as a result the runic weapon, copying the damage, killed me solo in a few hits, ignoring my 4k res, 65 to armor in metamorphosis as well as soul link (-25%) damage.At the same time, the death knight didn’t even try to attack me

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/b88cc9e2-cb94-40a4-aa34-b634f719ec67)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/1b0d741f-3ff1-4cde-954a-678317784771)

https://wowwiki-archive.fandom.com/wiki/Dancing_Rune_Weapon
https://www.wowhead.com/wotlk/spell=49028/dancing-rune-weapon
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
https://youtu.be/tkcbFNZxamo?si=fzqD1PBWXginY-EW&t=84
In general, judging by the video, runic weapons are an analogue of a “guard” who lives a separate life. At the same time, it is displayed in the addon as a separate target, but I don’t know if it is possible to kill it or apply CC to it like for a bloody worm. So in the video you can see that it has a gcd between copying abilities and the ability to attack only in melee. But it is worth noting that it copies not only damage-dealing abilities, but also creates double debuffs of various magical abilities. The total damage is far from 50% damage for pvp .On average, it deals from 10% to 30% damage in pvp. Which confirms that it doesn't just duplicate 50% of the damage
![13443121421](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/ab57401c-8a34-4934-8075-14227dc01bf2)
![134343434](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/5ce74c99-5326-4d76-84e9-a6b3ae12cfd4)

**Comment by UltraNix** [comment]
The thing is that DRW copies damage equal to 50% of damage already done by DK. It means that that damage was already reduced by armor/etc once DK hit you.
E.g. DK does 10k damage to you and DRW copies 5k. That 5k is already reduced by armor and other reductions - we cannot reduce it once again.

**Comment by Pornoodemon** [comment]
> The thing is that DRW copies damage equal to 50% of damage already done by DK. It means that that damage was already reduced by armor/etc once DK hit you. E.g. DK does 10k damage to you and DRW copies 5k. That 5k is already reduced by armor and other reductions - we cannot reduce it once again.

The fact of the matter is that he should copy not the damage, but the ability used, multiplying the damage from auto attacks and abilities by 0.5

**Comment by UltraNix** [comment]
In that case, DRW will always do less than 50% of DK damage - just simply because DRW does not have such auras that increase dmg, does not have spellmods, etc. If it's okay, then I can change it.

**Comment by UltraNix** [comment]
Fixed.
