### ISSUE TITLE
Boss Bugged Temple Anh Quiraj

### ISSUE THREAD

**Issue by Ateenaa-Tik** [gamefreedomgit/Maelstrom#5526]
https://www.wowhead.com/classic/es/npc=15276/emperador-veklor

https://www.wowhead.com/es/zone=3428/ahnqiraj

**Description:**

Hello, apparently this boss is buggy, I have killed him 6 times and he has never given me loot, please fix it, since it drops a nice item to transmog! thank you!

**Database links:**

https://imgur.com/a/rhwFjk8

**Comment by UltraNix** [comment]
Fixed.
