### ISSUE TITLE
Hellfire Ramparts - Quest items do not drop

### ISSUE THREAD

**Issue by MitchellOpitz** [gamefreedomgit/Maelstrom#5527]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quests within Hellfire Ramparts do drop quest items.  I've run mutliple days and both Omor's Hoof and Gargolmar's Hand do not drop.  Nazan's Head DOES successfully drop.

**How to reproduce:**
Accept quests Demons in the Citadel and War on the Ramparts.  Defeat Gargolmar and Omor.

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=29528/war-on-the-ramparts
https://www.wowhead.com/quest=29529/demons-in-the-citadel

**Comment by PanJanuszek** [comment]
fixed on 05.03.2024
