### ISSUE TITLE
Warlock pet resummon

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5530]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After fix "Core/Pets: Summoned pets (warlock pets,water elemental, etc.) should not immedialtely despawn on its death."

After a pet dies, ressumon the current pet leaves it dead
If possible, this needs to be corrected as quickly as possible, as this is critical in pvp

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/b21b5304-a7ca-47a2-8f57-37d5c786bfa5

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Snipin** [comment]
The bug is also happening for DK, essentially the pet is unable to be resummoned, since the dead pet is taking up the slot

[https://streamable.com/hztywm](url)

**Comment by Hermeleen** [comment]
ah yes, just wanted to report. Warlock talent "Demonic Rebirth" doesn't work. Basically when your pet dies and you use insta-pet-resummon, the pet stays dead and you don't get new one.

**Comment by SimonBpvp** [comment]
workaround: if you dismiss your pet you can resummon it. but if you just leave it dead and try to resummon it will stay dead

**Comment by Pornoodemon** [comment]
Same problem with dk pets

**Comment by UltraNix** [comment]
Alreayd fixed.
DK pets handled by another report.
