### ISSUE TITLE
Deep Freeze consuming 2x FoF

### ISSUE THREAD

**Issue by Xianji** [gamefreedomgit/Maelstrom#5531]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Deep freeze is currently dealing damage twice and consuming all Fingers of Frost stacks(1 or 2 depending on how many you currently have up). 

**How to reproduce:**
Use Deep Freeze on a non-stunnable target(any dungeon/raid boss) with 2 Fingers of Frost procs active(i.e. after a pet freeze).

**How it should work:**
It should only deal damage once and consume one Fingers of Frost proc(out of the two that you can have as a maximum)

**Database links:**
https://youtu.be/dRgZhRtG8es?si=_Givxr9TCLgzBXHL&t=520
Preach video from original Cata release, look closely at the Fingers of Frost buff at 8:40 after he deep freezes, it only does damage once and consumes only one Fingers of Frost.

**Comment by UltraNix** [comment]
Fixed.
