### ISSUE TITLE
Raiding training dummy being stunnable

### ISSUE THREAD

**Issue by Xianji** [gamefreedomgit/Maelstrom#5532]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Raiding training dummy is stunnable, making abilities such as Deep Freeze stun them instead of dealing damage to them.

**How to reproduce:**
Use Deep Freeze on a raiding training dummy.

**How it should work:**
It shouldn't be stunnable, you should deal the damage portion of Deep Freeze instead of stunning them.

**Database links:**
https://youtu.be/YxSov01Hk2c?t=252

**Comment by bonfax4** [comment]
Here you go https://youtu.be/YxSov01Hk2c?t=252

@Sketish

**Comment by UltraNix** [comment]
Fixed.

**Comment by Nenze** [comment]
worst fix ever
RIP playable competitive pve frost 
[*] 9th August 2023 - 18th January 2024 [*]
