### ISSUE TITLE
Ulduar Raid

### ISSUE THREAD

**Issue by Mrkgud** [gamefreedomgit/Maelstrom#5533]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bosses works but Loot Chests are not appearing after killing Bosses
Thorim picture below for example.
**How to reproduce:**

**How it should work:**
it should spawn after boss dies 

**Database links:**
![UlduarCapture](https://github.com/gamefreedomgit/Maelstrom/assets/156952807/cefbe938-3344-4eac-99ff-d0079cb61fdf)

**Comment by Mrkgud** [comment]
seems like only thorim doesnt drop it... the needed one.

**Comment by UltraNix** [comment]
Fixed.
