### ISSUE TITLE
Warlord Zon'ozz's black phase damage goes trough palading immunity bubble

### ISSUE THREAD

**Issue by TEIWASTAKEN** [gamefreedomgit/Maelstrom#5534]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
Warlord Zon'ozz's black phase damage goes trough palading immunity bubble

**How to reproduce:** 
Go to Black Phase on Warlord Zon'ozz and use the bubble that should make you immune to all damage

**How it should work:**
Bubble should give immunity to the damage.

**Database links:**

**Comment by Revly** [comment]
I don't think so... it says very well here [Black-blood-of-gorath](https://www.wowhead.com/spell=104377/black-blood-of-gorath)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/eb0099d6-0b79-4e89-b34f-ad471b102e1b)

[Unaffected by invulnerability]

Also if they apply this.

> Bubble should give immunity to the damage.


Then Rogue's Shadow Cloak would have to do the same


Database links:
https://www.wowhead.com/spell=104377/black-blood-of-gorath
https://cata-twinhead.twinstar.cz/?spell=104377

**Comment by Lycadd** [comment]
https://youtu.be/COz36KzaK8Y?si=r4Vo1amtD2CsWGvi&t=147 2mn27
https://youtu.be/fdRH9w7SwGk?si=6SFTIs1gKxwcZ93W&t=112 1mn52

Divine shield should work on Zon ozz black phase

**Comment by Revly** [comment]
Apparently, as long as the effect persists you should be immune to damage taken, just like the rogue's shadow cloak.

**Comment by UltraNix** [comment]
Fixed.
