### ISSUE TITLE
Cluster Clutch Rogue quest

### ISSUE THREAD

**Issue by Sasinuka** [gamefreedomgit/Maelstrom#5535]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**Hello, So I made a ticket couple of days ago asking if its the same ammount of Cluster that drops on normal and Heroic mode, i've been told that it should be x2 the normal mode ammount which had appeared that it is not, I don't really know if this is how it should work I made a ticket in game they told me report here, here I am!

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
There is no difference in 10n and 10hc. Only between 10m and 25m raids
