### ISSUE TITLE
Fury of the Destroyer With Recuperate and other details

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5537]
**Description:**

[Fury of the Destroyer](https://www.wowhead.com/es/spell=109949/) o  is supposed to "Immediately grants 5 combo points and causes your finishers to grant 5 combo points. Lasts 6 sec" Works with all finishing moves.

Slice and Dice
Expose armor
Rupture
Eviscerate
Kidney blow
Poison
Death Throw

But for some strange reason, [Recuperate](https://cata-twinhead.twinstar.cz/?spell=73651) doesn't take it as a CP finish.

**How to reproduce:**

Evidence:

[Fury of Distroyer + Recuperate + Shadow of Destroyers
](https://youtu.be/B6u036tk2-c)

https://github.com/gamefreedomgit/Maelstrom/assets/12503112/1ad102fb-d510-48d3-a77a-115af60d1de7

Therefore, this should not be so.
Practically it is not counting it as a CP finish.

**How it should work:**

The 5 CP Orotgar Destroyer's Fury sequence should not be interrupted by using Recuperate, it should work like all other finishers

**Database links:**

https://www.wowhead.com/es/spell=109949/furia-del-destructor
https://cata-twinhead.twinstar.cz/?spell=109949
https://www.wowhead.com/es/spell=109950/furia-del-destructor
https://cata-twinhead.twinstar.cz/?spell=109950

https://cata-twinhead.twinstar.cz/?spell=73651

**Comment by Revly** [comment]
I want to add something else that I have found is useful information. in the comments [here](https://www.wowhead.com/spell=109939/item-dragon-soul-legendary-daggers#comments)

I guessed it when I was practicing.

**How to reproduce:**

I lost the stacks of [Shadow of the Destroyer](https://www.wowhead.com/spell=109941/shadows-of-the-destroyer) when the [Fury](https://www.wowhead.com/es/spell=109949/furia-del-destructor) was activated 

**How it should work:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/64bffa6b-9b1d-4803-a6c4-daa8e3a4fba6)

**Database links:**

https://www.wowhead.com/spell=109941/shadows-of-the-destroyer
https://www.wowhead.com/spell=109939/item-dragon-soul-legendary-daggers#comments

**Comment by UltraNix** [comment]
Fixed.
