### ISSUE TITLE
"Higher Learning" achievement 

### ISSUE THREAD

**Issue by Dellus112** [gamefreedomgit/Maelstrom#5538]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I can`t do the achievement "Higher Learning" in Dalaran by reading the 8 books, because they are never spawned. I looked in the whole Dalaran at different hours and days, but without success. The only book I could find was "The Schools of Arcane Magic - Introduction" at "The Violet Gate (teleportation room)".

**How to reproduce:**
There are many tutorials on the internet where you should find the books and there are about 8 spots. Check these 8 spots and you`ll find nothing.

**How it should work:**
In these 8 spots, different books should be spawned, not necessarily the achievement books, and after you read them, they should de-spawn and after a while, another book should appear in that place. After reading all the books that start with "The Schools of Arcane Magic - ..." you should get the achievement "Higher Learning"

**Database links:**
https://www.wowhead.com/achievement=1956/higher-learning
https://www.wowhead.com/object=192708/the-schools-of-arcane-magic-introduction
https://www.wowhead.com/object=192710/the-schools-of-arcane-magic-conjuration
https://www.wowhead.com/object=192713/the-schools-of-arcane-magic-enchantment
https://www.wowhead.com/object=192866/the-schools-of-arcane-magic-necromancy
https://www.wowhead.com/object=192709/the-schools-of-arcane-magic-abjuration
https://www.wowhead.com/object=192711/the-schools-of-arcane-magic-divination
https://www.wowhead.com/object=192865/the-schools-of-arcane-magic-illusion
https://www.wowhead.com/object=192867/the-schools-of-arcane-magic-transmutation

**Comment by UltraNix** [comment]
Fixed.
