### ISSUE TITLE
Sanctuary: paladin talent resets

### ISSUE THREAD

**Issue by agynesse** [gamefreedomgit/Maelstrom#5539]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon selecting the Sanctuary talent and clicking the "Learn" button, the said talent get backs to its initial version (e.g., I have 1/3 point distributed. When I click it to add another point, the point resets back to 1/3).

**How to reproduce:**
I've tried adding more points to this talents over a course of 3-4 levels but I'm unable to add more. Whenever I do so, the talent points restore to its initial count.

**How it should work:**
I should be able to add another point to the Sanctuary talent and see 2/3 and then 3/3 respectively when I confirm it with "Learn."

**Database links:**

**Comment by Sketish** [comment]
Please try to reset your talents

**Comment by UltraNix** [comment]
No further info - closing.
