### ISSUE TITLE
Well of Eternity RHOT HC didn't give me valor points upon finishing it

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5540]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I did RHOT HC and it was woe and i didn't get any valor points after killing mannoroth.

**How to reproduce:**

**How it should work:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/4ea1870f-546f-44bc-8ff1-4e291bf00a63)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7bf19854-9bcd-465d-8705-778e10f64972)

**Database links:**

**Comment by Renehadox** [comment]
@Sketish When am i going to get my valor points from this rdf?

**Comment by UltraNix** [comment]
@Renehadox Happened only once?

**Comment by UltraNix** [comment]
No further info - closing.
