### ISSUE TITLE
Well of Eternity Queen bugged loot

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5541]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Queen Azshara loot is bugged, last 10 WoE i did only the ring drops, every single time, literally...

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/bc8449c7-3bfa-4954-87aa-7c084bc888e9)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
well its called rng , not a bug
