### ISSUE TITLE
gurthalak bugged in pvp

### ISSUE THREAD

**Issue by freakyfrizes** [gamefreedomgit/Maelstrom#5543]
Once gurthalak procs the tentacle is picking random targets isntead of hitting the target i am targeting/hitting,in addition it sometimes rarely procs without even hitting anyone and just casually stands there.i procced 3 tentacles while hitting a warlock and all 2 of them targeted his pet for the entire duration without even retargeting to warlock after the duration was over(i was targetting and hitting the warlock the entire arena didnt target his pet once),and that happend to me in a bunch of arenas , where the tentacle would just target the other player instead of the one i am hitting. its fucked up hard right now.

**Comment by Sketish** [comment]
Tentacle is attacking player on which it procced. Tentacles are not supposed to swap targets unless their previous target dies

**Comment by freakyfrizes** [comment]
> Tentacle is attacking player on which it procced. Tentacles are not supposed to swap targets unless their previous target dies

not true the tentacle should retarget to my current target after it finishes it's cast

**Comment by freakyfrizes** [comment]
This is how gurthalak should work:

Attacks the target of the player even if he's not hitting his target.
if you stop targeting, it doesn't stop hitting during the cast, it stops right after the end of the cast.
if you swap target, it doesn't swap target instantly, it finishes casting on the previous target, then it swaps to the new target (on the next cast.)

worrax described it perfectly in my last post about gultharak and they said it was FIXED but sadly it isnt working this way at all.

**Comment by Sketish** [comment]
> This is how gurthalak should work:
> 
> Attacks the target of the player even if he's not hitting his target. if you stop targeting, it doesn't stop hitting during the cast, it stops right after the end of the cast. if you swap target, it doesn't swap target instantly, it finishes casting on the previous target, then it swaps to the new target (on the next cast.)
> 
> worrax described it perfectly in my last post about gultharak and they said it was FIXED but sadly it isnt working this way at all.

Send proofs

**Comment by bonfax4** [comment]
You can go through this [video](https://youtu.be/xIiCGvbVqWA?si=fQMoCc_E-25ngmxj) and see it does not work how you described. I never do see it standing there doing nothing in videos, it seems to always look for eligible targets

But good luck finding out how the retarded AI blizz had works lol, but it does seem to target whoever it procs on initially.

**Comment by bonfax4** [comment]
https://youtu.be/72JgcRdzUhc?t=1m4s
Just to show that the tentacle just starts attacking a random dk still mounted ( not in combat ) when there's no target nearby.

**Comment by bonfax4** [comment]
@Sketish @UltraNix 

After going through a few videos this is how I believe it works :

- Target the nearest player or pet ( usually ends up being your target if there's no kiting involved but in retail there was a delay from the proc moment until the tentacle spawned, so often in pvp this isn't the case) , this happens on a per cast basis. It will look for another target once the cast is finished, it doesn't lock to a target. 
- Los'ing will also trigger the above behaviour as well, but the tentacle will finish it's current flay through los then look for a new closest available target again.
- Immunities such as ice block,Divine Shield invalidates you as a target even when you're the closest.
- Ignores cc with dmg cap spells like hex. Didn't get the chance to see others, but logically don't see why it wouldn't be the same for any breakable cc in the game.
- Not being engaged in combat with the wearer does not stop you from being an eligible target in pvp combat at least (ok only seen Bgs, didn't see any world pvp vid )

https://youtu.be/xIiCGvbVqWA?t=2m31s 
Paladin procs tentacle on Bajheera, shaman moves closer to the tentacle and target changes.

https://youtu.be/xIiCGvbVqWA?t=8m11s 
Tentacle targets the rogue when a hexed priest is the closest.
https://youtu.be/xIiCGvbVqWA?t=10m50s
Ignores hexed pala and targets 2nd closest which is the druid.

Just trying to see now if they ignore guardians like mirror images/gargoyles etc

**Comment by bonfax4** [comment]
@Ultranix proof [here](https://youtu.be/2G9NFBvZuCE?t=4m31s) It can cast more than 3. Felhunter until it died > Player until it died > priest in the ring of frost > 4th one was resisted by the pet but you can see in the combat log. Locking it to 3 casts would create situations where it stands doing nothing when they are forced to target switch

**Comment by freakyfrizes** [comment]
today i was playing a soloq arena , im hitting the unholy dk against me and the enemy Holy paladin is standing like 10 feet away, i go there fear the paladin (he had no bubble or trinket ) full 8 second fear,i switch back and charge the Unholy dk and hit him , my tentacle spawns and it starts channeling on the feared holy paladin which is standing like 20 feet away at this point breaking the fear.This is a real issue and the fact that the paladin has no bleeds,standing very far away and straight up im not near him to hit him or anything and it just procs and starts attacking him a mile away is proof that the tentacles arent working properly. @UltraNix . If you can watch done arenas please tell me and i could tell you which game exactly this happend so you can have cunning proof.

**Comment by pro100klass** [comment]
upp gurthalack usseles

**Comment by UltraNix** [comment]
Fixed.
To all wondering about targeting mechanic: https://github.com/gamefreedomgit/Maelstrom/issues/5543#issuecomment-1904105583
