### ISSUE TITLE
Hunter's [Camouflage]

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#5544]
There are 2 Game breaking bugs with camouflage.

1. if 2 hunters are in camouflage they shouldn't be able to shoot each others. only melee / AoE can take hunter out of camouflage as mentioned in tooltip.
![camo tooltips](https://github.com/gamefreedomgit/Maelstrom/assets/129106504/9ee47161-60fe-427c-b12d-a2cf66e06628)

2. when hunter summon a pet while in camouflage, camouflage should get removed ( which is not the case here)

![camouflage bug](https://github.com/gamefreedomgit/Maelstrom/assets/129106504/e8a120b8-039f-4958-b325-a95016a0ae42)

**Comment by WhitemaneSylah** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/121137397/fad603a1-5c3b-4e1a-a43d-cb58a7cab1e8

**Comment by WhitemaneSylah** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/121137397/1cc52b4d-efdf-409c-a5bd-f937095c2f53

**Comment by jimmyiwnl** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/129106504/afccb38f-81d1-442d-8c8e-049990bf7527

new bug, i shouldn't lose my camouflage buff if i try to shoot an enemy hunter that is also in camouflage

**Comment by Renehadox** [comment]
> Desktop.2024.01.30.-.15.14.40.02.mp4 
> new bug, i shouldn't lose my camouflage buff if i try to shoot an enemy hunter that is also in camouflage

retail proof of this ?
you just posted wowhead comment

**Comment by UltraNix** [comment]
Fixed.
