### ISSUE TITLE
Some Toys do not have Version Female

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5545]
**Description:**`
I was looking at some items, in the Maelstrom Realm and in the PTR

the ones I have found at the moment

1- Maelstrom  [Leyara's Locket](https://www.wowhead.com/item=71259/leyaras-locket)
2- PTR [Dire-brew](https://www.wowhead.com/item=38320/dire-brew)  when using the item It has neither male nor female form.

**How to reproduce:**

[Leyara's Locket](https://www.wowhead.com/item=71259/leyaras-locket) It does not have a female version currently With Char Female

**Female Char  OK**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/68491a03-1923-4c4b-9cff-46dd51fb468f)

**Using Toy**... _why Version Male Whit char Female?_
![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/f244f304-9c77-4243-a314-e698cfc40fc8)

**How it should work:**

**Female Version with Char Female**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/70aca232-cd0b-44ad-9ac1-1114c6ca4df9)

**As extra information.**

Since you implemented that all CDs restart when we kill boses, enter bg, arena, among other things.
I have never seen this item restart the CD [Leyara's Locket](https://www.wowhead.com/item=71259/leyaras-locket)  and maybe other items in the future that will be implemented if you wish.

**Database links:**

https://www.wowhead.com/item=71259/leyaras-locket
https://cata-twinhead.twinstar.cz/?item=71259
https://www.wowhead.com/item=38320/dire-brew
https://cata-twinhead.twinstar.cz/?item=38320

**Comment by UltraNix** [comment]
Fixed.
