### ISSUE TITLE
Rune of Cinderglacier

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#5546]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Whole weapon enchant seems buggy. Doesn't get consumed by Scourge Strikes shadow damage portion, [Unholy Blight](https://i.imgur.com/kTZzMS5.png) seems to also be consuming stacks on every single tick, which means the Cinderglacier proc pretty much instantly disappears as you get it.

**How to reproduce:**

**How it should work:**
Should be consumed by scourge strikes, unholy blight shouldn't consume it.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=53386

**Comment by UltraNix** [comment]
Unholy Blight is shadow damage.

**Comment by bonfax4** [comment]
@Ultranix yh but it's consuming the buff on a per tick basis. Can't find proof it shouldn't work that way tho but seems unlikely.

**Comment by UltraNix** [comment]
Rune of Cinderglacier can proc off from DoTs.

**Comment by bonfax4** [comment]
Wowhead comment seems to indicate otherwise... Says plague strike does not even consume the buff but the disease is still increased by the dmg.. implication here that only direct dmg should proc it.

**Comment by bonfax4** [comment]
@UltraNix 

> (a) [ Death and Decay](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=43265) (DnD) does not consume CG charges but benefits from CG.
> 
> (b) CG increases the damage of both [ Frost Fever](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=59921) (FF) and [ Blood Plague](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=59879) (BP) if it is active while they are applied. CG stacks are only consumed if the triggering spell itself benefits from CG. That means:
> [ Icy Touch](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=45477) consumes 1 stack of CG, although both Icy Touch and the triggered FF benefit from CG.
> [ Plague Strike](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=45462) does not consume any stack of CG, but the triggered BP benefits from it.
> [ Pestilence](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=50842) does not consume any stack of CG, but all diseases created by it benefit from it (the original diseases remain unaffected, however).
> [ Chains of Ice](https://web.archive.org/web/20120702150742mp_/http://www.wowhead.com/spell=45524) does not consume any stack of CG, but the triggered FF benefits from it.
> (c) CG's bonus is updated on-the-fly for DnD, but not for diseases. That means if you get a Cinderglacier proc after you've cast DnD and applied diseases, your DnD's damage will increase, but your diseases's damage will not. (The same is true for the case that CG fades: DnD's damage decreases, FF/BP's damage remains unaffected.)

**Comment by bonfax4** [comment]
Even in the case of unholy blight updating dynamically with % increases, if we follow how everything else behaved there, it wouldn't even consume it since it's also a dot.

**Comment by UltraNix** [comment]
Fixed.
