### ISSUE TITLE
Honoring the Dead quest bug

### ISSUE THREAD

**Issue by xrtf1** [gamefreedomgit/Maelstrom#5547]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest cannot be returned.

**How to reproduce:**
Do the quest

**How it should work:**
Quest is returned and gives rewards

**Database links:**
https://www.wowhead.com/quest=24573/honoring-the-dead

P.S, i relogged several times, no change. (If you think that i dont have the required quest item, i checked, i do)

https://github.com/gamefreedomgit/Maelstrom/assets/136637141/d9f2e428-8c7b-4155-853d-ed6a0f573ceb

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2a1f47bb-349a-4cb4-8639-91bdfbd0ea1c)
Works okay to me.

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/7ae3582d-0c20-4ca2-b45b-8d7fe9b7d5c1)

cannot reproduce
