### ISSUE TITLE
trinkets from DS

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5549]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
vial and fetish sometime can can double/triple proc in a row

**How to reproduce:**
100% idk. mb only low chance

**How it should work:**
trinket should not x2, x3 in a row, after proc should be cd (9 for vial, 24 for fetish)

**Database links:**
https://wowpedia.fandom.com/wiki/Vial_of_Shadows
https://wowpedia.fandom.com/wiki/Bone-Link_Fetish

https://gyazo.com/0adc40ac8fd8b88514ed0375ae803640
x3 proc in a row, 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/d269f9cb-222d-45a9-9565-3a1b7dcaa1c4)
x2 proc in a row

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/34491427-f727-45d7-be92-69b458517df1)
I tested it, need only attack for reproduce bug, low chance for double, triple proc

**Comment by UltraNix** [comment]
Fixed.
