### ISSUE TITLE
RItual Materials (Quest (Darkshore))

### ISSUE THREAD

**Issue by voit47** [gamefreedomgit/Maelstrom#5552]
https://www.wowhead.com/quest=13566/ritual-materials)

**Description:**
Can't pick quest item 'Tuft of Mottled Doe Hair' from 'Critter'

[
![WoWScrnShot_012124_155121](https://github.com/gamefreedomgit/Maelstrom/assets/156099976/c5981fdd-7d8a-4cb6-8fb6-8ad1ff70a990)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/d1b16100-f1f6-47f2-8298-39c4ee148112)

Cant'reproduce i was able to gather 7x in 5s.
