### ISSUE TITLE
Ashenvale / King of the Foulweald quest bug

### ISSUE THREAD

**Issue by Daniel123000** [gamefreedomgit/Maelstrom#5553]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When i do the quest, if i put down the flag, nothing happens.

**How to reproduce:**
Do the quest and put down the flag.

**How it should work:**
When i do the quest, if i put down the flag, the furbolgs need to attack me and the the "boss"

**Database links:**
https://www.wowhead.com/quest=6621/king-of-the-foulweald

![WoWScrnShot_012124_181658](https://github.com/gamefreedomgit/Maelstrom/assets/131005721/7308a322-c2a0-453c-984c-61b81ce6edc3)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/a9e62090-4e4a-4051-a884-e27979fabf20)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/56e7bc9b-70e1-411d-bf8f-4f7ee08295fa)

cannot reproduce, ursa start to attack me after 5sec
