### ISSUE TITLE
Morchok: Black Blood of the Earth

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#5554]
**Description:**
In the ["Black Blood of the Earth"](https://www.wowhead.com/spell=103785/black-blood-of-the-earth?dd=6) phase, the black blood should not do any damage if you are behind a spike, which makes it possible for you to cast spells without taking any damage.

**How to reproduce:**
Go to morchok and try to cast any spell behind the spike and you will see how you receive damage from the black blood.

**How it should work:**
You should be able to cast spells when behind a spike without taking any damage.

You can check out these videos from 12 years ago:
https://youtu.be/5ElswYPDTaA?t=86
https://youtu.be/5ElswYPDTaA?t=291
https://youtu.be/ulmuXvee4Eo?t=75
https://youtu.be/ulmuXvee4Eo?t=179
https://youtu.be/OMwPr_PbXb8?t=97

Another thing, watching the videos I also realized that the spikes appear in pairs and it is possible to cast spells in the middle of these 2 spikes without receiving any damage.

**Comment by Sketish** [comment]
You must stay between 2 pillars to be able to cast any spell and yes then you take no damage

**Comment by Sketish** [comment]
Need clips from our server

**Comment by DartImpact** [comment]
You don't necessarily have to be between 2 pillars, you can watch the first retail video I posted.
![Captura de pantalla 2024-01-22 122003](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/704fa547-ba21-4974-9e48-1a13fd9bcc2d)

I found this clip: https://clips.twitch.tv/StylishGoodLyrebirdBlargNaut-yaWMPufB-HjTakjX
I'll try to record a video myself if it's still necessary.

**Comment by DartImpact** [comment]
@UltraNix 
**Retail:** 
**Video 1:** (2:52) https://youtu.be/JSOvKmUrTzM?t=171
![sangre negra retail](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/e0b99d33-be67-4b8e-a4aa-3ab9a64c7b26)

**Video 2:** (4:30) https://youtu.be/H8JStl_lyKE?t=270
![sangre negra retail2](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/df412edc-3308-4fdf-ba47-29af25e9155a)


**Whitemane:**
**Video 1:** https://youtu.be/mWea2ksTJsw?si=zBgK2H6dpwBmTYUN
![BlackBloodWhite](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/eb807098-e94c-40f4-9702-8f707d246f4f)

**Video 2:** https://youtu.be/dPV8QlT4qPg?si=SRqipdYp3haffKcL
![BlackBloodWhite2](https://github.com/gamefreedomgit/Maelstrom/assets/141894993/0a728f93-df46-4581-9c39-25d4d93d993d)

**Comment by Georgiimo** [comment]
I can confirm that you take damage even when you are behind two pillars.

https://streamable.com/zzngym

**Comment by DartImpact** [comment]
@UltraNix 
https://youtu.be/CMUlD1o4Xjw?si=o1zOIKQPTcg74DSt
https://youtu.be/pBNH3-SCZHU?si=yUqtMAPA0C97hWUL
I think the evidence is enough, there is clearly an error with the black blood.
it's not blizzlike.

**Comment by UltraNix** [comment]
Fixed.
