### ISSUE TITLE
Solo queue MMR banding limit (PvP council)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#5555]
Solo queue coupling players should only group players that have a difference of +300/300 in MMR.

Regardless of how long the queue takes this barrier should be maintained to ensure fairness to players on the lower end and higher end 

Example : Player with 2200 rating can join queues with players who are 1900 at its lowest end, or 2500 at its highest end

**Comment by SimonBpvp** [comment]
That will suck if you’re 2900 and nobody queues above 2600, then you can’t play soloq 🙃

**Comment by UltraNix** [comment]
Already implemented.

**Comment by SimonBpvp** [comment]
> That will suck if you’re 2900 and nobody queues above 2600, then you can’t play soloq 🙃

likewise it will suck if you're really noob and somehow get your MMR below 1200 or something. Then you will never be able to play soloq again on that char haha. (although some people might say that's a good thing) 

So in conclusion it punishes people for being too good or too bad. Which is the exact opposite of what you intended to do:

> to ensure fairness to players on the lower end and higher end

**Comment by SimonBpvp** [comment]
![WoWScrnShot_012524_231601](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/d2a92ccc-c9e4-4a26-aace-d5e3af90d4a5)

im not even rank1 or something, im like rank 16
