### ISSUE TITLE
Altered Beings missing mobs and Northern Barrens Hero's Call Bugged.

### ISSUE THREAD

**Issue by getastore** [gamefreedomgit/Maelstrom#5557]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest Altered Beings, the mobs needed for the quest simply aren't present in the Forgotten Pools where they should be

And also the Hero's Call for Northern Barrens is bugged not giving follow up quests where it should give, the quests just end after the first one and the NPCS simply doesn't hand out any more quests.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/classic/quest=880/altered-beings

**Comment by PanJanuszek** [comment]
Fixed with barrens refactor 04.03.2024
