### ISSUE TITLE
Dual wielding (NM) No'Kaled's gives off similar proc amount as if wielding only 1

### ISSUE THREAD

**Issue by megalocuts** [gamefreedomgit/Maelstrom#5558]
**Description:**
Dual wielding No'Kaled's (main hand and off hand) cancels each other's proc chance somehow.
I've tested it in a 3 minute window with full rotation and auto attacks only, both wielding just one and dual wielding. The chances were around the same as if using only 1.

**How to reproduce:**
Equip 2 No'Kaled and hit any dummy/player with and/or without special abilities within a limited time (check procs on Recount).
Then equip just 1 No'Kaled and repeat.

**How it should work:**
Each No'Kaled axe should have its own proc window without interrupting the other's. Doubling up the proc chance.

**Database links:**
https://www.wowhead.com/item=77188/nokaled-the-elements-of-death

**Comment by megalocuts** [comment]
Have to clarify I used 1 normal and 1 wartorn version for this test.
If it's a bug then check [Souldrinker](https://www.wowhead.com/item=77193/souldrinker) while you're at it.

**Comment by mipanka** [comment]
Every no kaled, should proc from hand where equip, so u never get x2 chance proc as u want

**Comment by bonfax4** [comment]
Well it wouldn't be a straight up 2x increase but having 2 should increase the number of procs if the weapon was working properly. Problem is no kaled is currently bugged and having 1 equipped makes it proc from all attacks already. Stormstrike ( attacks with both weapons separately per use ) should give you 2 ( 3 realistically, debuff had a chance to trigger ) chances to proc if dual wielding in a normal scenario or 1 single wielding. Lava lash and unleash wind should give you 1 or 0 depending on where the weapon is equipped.

Either way, procs should work independently of each other so this could be a bug but you should wait till the fix #5550 1st.

**Comment by megalocuts** [comment]
Yeah the chances being "doubled" is worded wrong but you get the idea. Realistically I should have more procs from autoattacks only, for instance I had roughly 8-10 procs in 2 minutes whereas it should be something around 15.

**Comment by bonfax4** [comment]
Actually, this might actually be accurate behaviour now that I look how gurthalak works for fury warrior. It's recommended for them to use different versions on dual wield because they share the proc on non weapon dmg based attacks. Shaman attacks are all weapon based so this would never be an issue for them in normal circumstances.

**Comment by megalocuts** [comment]
I've played on two different Cata servers before and this was never an issue, while the Gurthalak thing persisted through. I'm not 100% sure if it's a bug but please take in consideration they're totally different procs, one summons a "pet" (that might not be replaceable), the other does extra damage even with auto attacks. I play a frost DK, No'Kaled is a desired weapon on that spec and for PVP, same goes for [Souldrinker](https://www.wowhead.com/item=77193/souldrinker) which I'm also concerned about. As for testing I don't have any other version of it.

**Comment by megalocuts** [comment]
Once I got the second one and equipped it I didn't feel any upgrade, and was disappointed at the unusual behavior. But if you say it's broken it's ok for me. Problem is this might lead to more misunderstanding as people spend (and waste) conquest or win a roll in DS when it's not any more beneficial.

**Comment by Sketish** [comment]
I need help with research if this should work like as on fury warrior:
If you have 2x gurthalak from same version then offhand weapon will never proc tentacle.
That's why best warriors used hc in mh and normal one in offhand

Trying to get info about nokaled's

**Comment by bonfax4** [comment]
>If you have 2x gurthalak from same version then offhand weapon will never proc tentacle.

Not accurate. Off hand gir can still proc from auto, rageblow offhand, whirlwind off hand in that scenario. It's mostly referring to non-weaponbased mellee attacks like bloodthirst. These single entry attacks would share their proc if they had the same ilvl.

I tried to look for I fo on the others but no luck. This wouldn't affect neither dk's or shamans anyway since they don't have such attacks. Would only concern SMF warriors tbh.

**Comment by mipanka** [comment]
Off hand weapon can proc from auto attack or attack from left hand. As example if in right hand weapon without proc (t1 pvp) and in off hand no kaled/gurth, player shouldn to get proc from right (main) attack

**Comment by UltraNix** [comment]
Fixed.
