### ISSUE TITLE
[quest] Hacking the Construct

### ISSUE THREAD

**Issue by KevlinTallfellow** [gamefreedomgit/Maelstrom#5561]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

The player is supposed to interact with an arcane construct in the night elven camp, however, the construct simply dies every time it respawns, preventing the player interaction to continue the quest.
**How to reproduce:**

Obtain quest, go to spawn location, wait for respawn and observe.
**How it should work:**
The player is supposed to interact with the arcane construct, and after some dialogue, the construct goes forward into the night elven camp and attacks the NPCs there, completing the quest objective.

**Database links:**
https://www.wowhead.com/quest=14430/hacking-the-construct
https://www.wowhead.com/npc=36599/arcane-construct#abilities

**Comment by PanJanuszek** [comment]
fixed after restart
