### ISSUE TITLE
[Priest][Spell] Dispel Magic and multiple Living Bomb

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5563]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dispel Magic for healer priest removes two harmful magic effects.
This is not true when you have Living Bomb from two (or more) different mages

**How to reproduce:**
Get Living Bomb cast on you from multiple mages
(Don't use Scorch to apply Critical Mass, skews results)
Self cast Dispel Magic
Only a single Living Bomb debuff is removed

**How it should work:**
Two Living Bombs should be removed

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=527

**Comment by UltraNix** [comment]
Fixed.
