### ISSUE TITLE
[Paladin] Seal of Truth

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5564]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Seal of truth currently onyl starts doing dmg at 5 stacks

**How to reproduce:**

**How it should work:**
Should start doing dmg as early as 1 stack for 1/5 of it's total damage until it reaches 5 and does full dmg.

sim proof : 
![9475a888a24f8892f39369ef637c6089](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/19811590-d729-4189-8550-30a75f79e125)

![2eebed0e08f041b5ed2100af7ea73de6](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/662a5d03-e9af-4ed7-8b1f-09b1e54f9702)

Log linked From ******** : 

[20:39:14.909] Ultraxion afflicted by Censure (3) from Dns
[20:39:14.909] Dns Seal of Truth Ultraxion 852
[20:39:15.745] Ultraxion afflicted by Censure (4) from Dns
[20:39:15.745] Dns Seal of Truth Ultraxion 1434

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=31801
https://cata-twinhead.twinstar.cz/?spell=31803

**Comment by bonfax4** [comment]
Just to clarify that SoT dmg is not tied to Censure nor SoC. Seal of truth only starts doing dmg from 1 stack upwards. Abilities only apply censure and SoC before that. 

Ex: 

0-1 Seal proccing abilities only proc Censure + Seal of Command
1-2  SoT * 0.2 + censure + SoC
2-3 sot * 0.4 + w/e
3-4 sot * 0.6 + w/e
4-5 sot * 0.8 + w/e
5-5 refresh Sot full dmg.

**Comment by Renehadox** [comment]
so rets are doing less damage by this bug ?

**Comment by bonfax4** [comment]
while building up censure maybe but i need to do more research because some abilities trigger seal sometimes and others don't and simc isnt very clear about it.

**Comment by bonfax4** [comment]
https://www.youtube.com/watch?v=0xd9wAETcq8
Seems to me like SoT dmg pre-5 stacks only goes through if you're in melee range to me with all sealing proccing abilities (censure application up to 5). 
But if you had 5 stacks, the censure refreshes always triggered SoT full dmg.

**Comment by bonfax4** [comment]
@Ultranix Oh and Seal of Command dmg is not tied to SoT dmg. That's clearly what was causing the double SoC proc at 5 stacks.

**Comment by Renehadox** [comment]
> @UltraNix Oh and Seal of Command dmg is not tied to SoT dmg. That's clearly what was causing the double SoC proc bug at 5 stacks or SoT is acting like a melee atack that in turn triggers soc lol.

you cant comment stuff like that, when you dont know what blizzard did back then in 2010-2011.

**Comment by Renehadox** [comment]
> Idc how the code works. All I know is it should not double proc command, which it currently does lol

Seal of truth atm is double proccing seals of command talent?

Wait, what?

**Comment by UltraNix** [comment]
Fixed.
