### ISSUE TITLE
[General] Munching mechanic issue with aoe

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5566]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently if you try to aoe with a class that suffers from this mechanic, only 1 target gets a debuff.
**How to reproduce:**
Try to aoe with firemage or with a warr and do multiple crits simultaneously on different targets. There's prob other effects that suffer from this that escape me right now. Some t12 set bonuses also had munching mechanics.

**How it should work:**
Munching was a delay with calculations with multiple crits on the same target. It never affected multiple targets. 

**Database links:**

**Comment by Sketish** [comment]
Can you provide any example so we can test on PTR ?

**Comment by bonfax4** [comment]
@Sketish 

https://github.com/gamefreedomgit/Maelstrom/assets/16911730/918521ab-3cd0-4a9b-8461-21ef9c489fa4
Its like the talent has an icd of 0.5 sec, so it only triggers once.

**Comment by bonfax4** [comment]
Might be wrong about this, after watching this video https://www.youtube.com/watch?v=NCz2JzSamk0 and https://www.youtube.com/watch?v=eKWxpy3QjCQ
