### ISSUE TITLE
FoF ice lance dtr

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5567]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ice lance consumes 2 stacks of fingers of frost when it gets copied by DTR. 

**How to reproduce:**
get 2 stacks of FoF and send one ice lance. If DTR copies the ice lance it will consume both stacks

**How it should work:**
only consume 1 stack 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=83074
https://cata-twinhead.twinstar.cz/?item=71086
https://cata-twinhead.twinstar.cz/?item=42745

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/77b3c0c7-3894-40ca-991d-3e5412256628)
https://wowpedia.fandom.com/wiki/Dragonwrath,_Tarecgosa%27s_Rest
