### ISSUE TITLE
Rathrak, the Poisonous Mind

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5568]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Doesn't work with DoT
https://www.wowhead.com/item=77195
The proc should be caused by any damaging spells. (As written in the tooltip)
Dot effects should cause proc
![34513](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/181888bd-0f37-46ad-a145-c79c8689f4e5)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/4bb831ad-b666-412c-bd3d-0a1f5163c4e3)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I don;t think it's valid. Mind Sear is not DoT.
In the same link:
`As it says, it only procs on casts, dot ticks don't seem to trigger`
`Passive DoT's such as Pyroblast and Ignite do not proc this weapon`
`Living bomb DoT does not appear to proc it either`

**Comment by UltraNix** [comment]
More info: https://www.mmo-champion.com/threads/1035701-Rathrak-the-Poisonous-Mind
`-Doesn't proc off dot ticks`

**Comment by Pornoodemon** [comment]
> More info: https://www.mmo-champion.com/threads/1035701-Rathrak-the-Poisonous-Mind `-Doesn't proc off dot ticks`

https://youtu.be/DXDIYOnubS4?si=tv1yEVo6fzbg2z-3&t=171

**Comment by Pornoodemon** [comment]
> More info: https://www.mmo-champion.com/threads/1035701-Rathrak-the-Poisonous-Mind `-Doesn't proc off dot ticks`

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/ced81e31-dfcb-44a5-b323-1fd0be8f88ac)
This is not his personal experience of using it. Moreover, the early LFR version worked differently..

In my opinion, this commentary with a personal test of use on later versions of the kata will be more informative.
![34513](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/181888bd-0f37-46ad-a145-c79c8689f4e5)

**Comment by Pornoodemon** [comment]
> I don;t think it's valid. Mind Sear is not DoT. In the same link: `As it says, it only procs on casts, dot ticks don't seem to trigger` `Passive DoT's such as Pyroblast and Ignite do not proc this weapon` `Living bomb DoT does not appear to proc it either`
> 
> Alsom tooltip says about "harmful spellcasts", not "any damaging spells"

Proc from AOE and Dot

https://youtu.be/DXDIYOnubS4?si=tv1yEVo6fzbg2z-3&t=171

**Comment by Pornoodemon** [comment]
HMM. Interesting situation. On twin, this does not work from Dot ticks, but it works from the very use of any “harmful spellcasts”, that is, it does not work, for example, from corruption ticks, but it works from the use of the corruption spell .
Apparently this should work the same way as on twin

For us this only works from direct castes.
100 uses of damage and not a single proc.

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/894dde4c-e7e9-4804-892e-049400fcdb28

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/09979f67-f2c4-496d-82b2-afe13e969f3b)

**Comment by Pornoodemon** [comment]
After the fix, there was still a problem with the proc chance  and possibly with icd.
The proc triggers once in 2-3 duels, talents that have a 4%proc  chance, for example, “Glyph of Corruption,” trigger more often than a snowcat.
The proc  chance  should be 15%
Icd 17 sec.

**Comment by UltraNix** [comment]
There is a 15% chance and 15 icd. That mean once it procced, you have 17 sec cooldown. If you are very, very lucky, it procs 3 times in 1 minute.
```
Proc flag 0x00010000, chance = 15, charges - 0
=================================================
  16 Successful damage from harmful magic spell cast
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 42 (SPELL_AURA_PROC_TRIGGER_SPELL), value = 0, misc = 0 (0), miscB = 0, periodic = 0
   Trigger spell (107831) Blast of Corruption. Chance = 15
   Description: Description: Deals $o1 nature damage to enemies in the affected area over $d.

   ToolTip: $s1 damage every $t1 $lsecond:seconds;.

=================================================
Items using this spell:
   77195: Rathrak, the Poisonous Mind 
```
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d4b9d510-9a0a-45d7-b045-b1a7f6a3a1ae)

**Comment by Pornoodemon** [comment]
> Шанс 15% и 15 icd. Это означает, что после срабатывания у вас будет время восстановления 15 секунд. Если вам очень-очень повезет, оно сработает 3 раза за 1 минуту.

Is this proc chance the same for pvp and pve?

**Comment by UltraNix** [comment]
The are 3 version of this spell - normal, heroic and LFR (with different IDs, but same proc chance, masks, flags, cooldowns, etc).
The spells works the same regardless of enemy type (pvp or pve)

**Comment by Pornoodemon** [comment]
OK . Then I think the topic can be closed

**Comment by Dimonz10** [comment]
Please watch this https://youtu.be/DXDIYOnubS4?si=mEnwbAmRjazQR51M&t=135 with x 0.25 speed and if u watched it correctly you will see that inside the GCD it procs its means it procs from a dot ticks please watch it and rewatch it.

conclusion "it does proc from dot tics"

![rathraaak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/c2ceac89-6b1e-4bd8-b825-cac2594ea0d0)

in the same GCD
![rathraaaak11](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/247d3237-4290-4167-93f7-a0afe12efa30)
