### ISSUE TITLE
bug pet del caballero de la muerte profano 

### ISSUE THREAD

**Issue by Xcanserbera** [gamefreedomgit/Maelstrom#5570]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
https://www.youtube.com/watch?v=K4OhUmw5zYE
[//]: # (http://wowhead.com/)
https://www.youtube.com/watch?v=K4OhUmw5zYE
[//]: # (cata-twinhead.twinstar.cz)
https://www.youtube.com/watch?v=K4OhUmw5zYE

**Description:**
la pet del caballero de la muerte se muere cuando no debe morirse, la pet del brujo, cazador no se muere porq la del dk profano si, no deberia morirse

**How to reproduce:**
https://www.youtube.com/watch?v=K4OhUmw5zYE

**How it should work:**

solo no debe morir la pet del caballero de la muerte

**Database links:**
hay dejo un video de como debe de funcionar la pet
https://www.youtube.com/watch?v=K4OhUmw5zYE

**Comment by Sketish** [comment]
Translate to english please
