### ISSUE TITLE
SPINE HC BUG - I CAN KNOCKBACK ALL

### ISSUE THREAD

**Issue by jeanpyere** [gamefreedomgit/Maelstrom#5571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
arcane spec [Mana Shield] id: 1463, PUSHING BLOODS AND TENDON ON SPINE HC FIGHT
i need use it for my  [Incanter's Absorption] ID:44395

**How to reproduce:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/7775198/5898bed0-060a-4d93-bef0-dd9288b829ea)

**How it should work:**

It wasn't supposed to be possible to push anything in this fight

**Database links:**

check in, and look about reset all cd's

**Comment by Revly** [comment]
TENDON can´t should affect by knockback 10j & 25j "This is Critical"

**Comment by jeanpyere** [comment]
and bloods?

**Comment by Revly** [comment]
> and bloods? I don't remember if it can interfere, disrupt the raid too much

The amalgam and blood should not be affected by knockback's as well.

**Comment by jeanpyere** [comment]
> > and bloods? I don't remember if it can interfere, disrupt the raid too much
> 
> The amalgam and blood should not be affected by knockback's as well.

TY

**Comment by UltraNix** [comment]
Fixed.
