### ISSUE TITLE
Wrath of Unchaining and hunter's shots

### ISSUE THREAD

**Issue by AnsBal** [gamefreedomgit/Maelstrom#5573]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
All shots increase the stacks of [Wrath of Unchaining] except serpent sting, black arrow, and explosive shot. Aren't they considered "attacks"?

**How it should work:**
all attacks should increase [Wrath of Unchaining] stacks.

**Comment by Sketish** [comment]
Follow template and provide proofs.

**Comment by AnsBal** [comment]
Sure, In this [video ](https://www.youtube.com/watch?v=JSN5kJH5LIo)at min 4:15 the boss fight start and the hunter start auto-atks and applies serpent sting and immediately got 2 stacks of Wrath of Unchaining. At min 4:18 he already applied black arrow and explosive shot and now he has 5 stacks of Wrath of Unchaining. In 3 seconds he got 2 stacks from auto shots and 3 stacks from serpent string, explosive shot, and black arrow.

**Comment by UltraNix** [comment]
Fixed.
