### ISSUE TITLE
Rogue problem spell Blade Flurry

### ISSUE THREAD

**Issue by Mortalle** [gamefreedomgit/Maelstrom#5574]
https://www.youtube.com/watch?v=C5Dd4GHS1as

**Description:**ITs mayble split 20% dmg with blade flurry (thats too loow) please fix that problem,thats huge problem!

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Polynomix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/4a590183-09e8-465d-9e47-7d42ffe5348e)
not proccing on every attack. was working before thurday patch

**Comment by UltraNix** [comment]
Fixed.
