### ISSUE TITLE
[hunter] Serpent sting clipping

### ISSUE THREAD

**Issue by Lycadd** [gamefreedomgit/Maelstrom#5575]
**Description:**
Serpent sting dot clipping mechanic is not working whether it is refreshed by the spell itself or by multi-shot through the survival talent Serpent Spread

`Between patches 4.0.1 and 6.0.1, this functionality only allowed DoTs to be "clipped" by a single tick before duration was wasted, requiring DoTs to be refreshed between the second-to-last and the last tick to maintain uninterrupted DoT ticks while optimizing duration gain.` 
(https://wowpedia.fandom.com/wiki/Damage_over_Time)

Proof that serpent sting is subject to dot clipping:
https://youtu.be/tPRdIpNy3lI?si=5UVipKi61-OFLfMq&t=50
0:50 : you can see the serpent sting applied through multi shot and serpent spread with 6 seconds duration. It is later extended to a maximum of 9s (6seconds base duration + 1tick duration -> 3s)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=35511 Serpent Sting
https://cata-twinhead.twinstar.cz/?spell=87934 Serpent Spread

**Comment by bonfax4** [comment]
#4708  There's another issue with it that was mentioned here but the OP never ended up reopening. Serpent spread should not do reduced Improved SS damage.

**Comment by UltraNix** [comment]
Fixed.
