### ISSUE TITLE
UNHOLY PET BUGUED ON ULTRA FIGHT

### ISSUE THREAD

**Issue by jeanpyere** [gamefreedomgit/Maelstrom#5576]
**Description:**

**the pet is falling or dying, I don't know exactly, but it's bugged, there's no way to play unholy there without the pet**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/7775198/33d8a002-f844-4772-a34e-761b648aef9f)
i summon him 3x (dead)

**How to reproduce:**

This video shows how it should be

https://www.youtube.com/watch?v=K4OhUmw5zYE

**How it should work:**

fix the unholy pet on the ultraxion

**Database links:**

https://www.youtube.com/watch?v=K4OhUmw5zYE

https://cata-twinhead.twinstar.cz/?spell=46584

**Comment by doctopo** [comment]
It's beceause he is charging ,all you need to do is remove pet charge and you can play with your pet ,you can see on the video he doesn't pet charge

**Comment by UltraNix** [comment]
As above - turn off Leap.
