### ISSUE TITLE
Fel Armor only heals through Corruption

### ISSUE THREAD

**Issue by ald333** [gamefreedomgit/Maelstrom#5577]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Fel Armor isn't healing at all.  https://imgur.com/cTkiKSk

**How to reproduce:**
Use Fel Armor while dotting a dummy. You will notice that only Corruption ticks heal (from siphon life).

**How it should work:**
Increasing spell power by 639 and ***causes you to be healed for 6% of any single-target spell damage you deal.***
This implies that any single-target damage dealt should heal the caster 

**Database links:**

**Comment by ald333** [comment]
https://youtu.be/D9RqE8mabNU?t=385  Here's a link to how it should work. It's 3% here but 6 in our current patch.

**Comment by Sketish** [comment]
Please provide combat logs

**Comment by ald333** [comment]
> Please provide combat logs

https://imgur.com/WGm8Bn5  I couldn't send you a video, the file was too large. After seeing the combat log, it seems that fel armor isn't even healing, that was syphon life healing through corruption. I don't know how no one noticed this before.

**Comment by ald333** [comment]
[image: WoWScrnShot_012624_092349.jpg]

**Comment by bonfax4** [comment]
Did you try to lifetap before you dmg ? Reading that it won't proc at full health. https://www.mmo-champion.com/threads/1002023-Fel-armor-healing

**Comment by ald333** [comment]
Yeah just tried it. It works but the heals are garbage..

**Comment by bonfax4** [comment]
garbage as in incorrect ? Link logs at least

**Comment by Pornoodemon** [comment]
Everything is working correctly, you can close the topic.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/003b6096-7321-48ac-9e06-7d197c3f8ccb)

**Comment by Pornoodemon** [comment]
> Yeah just tried it. It works but the heals are garbage..

6% of damage dealt.

**Comment by SimonBpvp** [comment]
Pretty sure target dummies have like 1 health. 6% of 1 isn’t very much lol. Try it in a duel and it should be fine
