### ISSUE TITLE
Warlock pet action bar

### ISSUE THREAD

**Issue by ald333** [gamefreedomgit/Maelstrom#5578]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Any time I enter or exit a battleground or instance, the pet bar disappears. I have to either /reload or re-summon my pet when entering a BG even though I had a pet summoned. The pet is still there but the bar is gone.

**How to reproduce:**
Summon any pet and enter a battleground.

**How it should work:**
The pet bar shouldn't disappear when you leave or enter a different instance.

**Database links:**

**Comment by UltraNix** [comment]
But when you teleport from one map to other map, the pet is despawned. So how you get the pet at the start of battleground?

**Comment by UltraNix** [comment]
Fixed.
