### ISSUE TITLE
[Paladin] Judgement 

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5579]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Judgement unleash damage is not being affected by the [Two-Hand spec](https://cata-twinhead.twinstar.cz/?spell=20113) 25% dmg.

**How to reproduce:**

**How it should work:**
According to both ret paladin 4.3 spreadsheets, it should. 

Spreadsheet 1:
![03d559c264a8f97aa838ee25694c76b3](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/3448dab8-9908-440a-9f6a-c6236d40bb83)

Spreadsheet 2 :
![49bf84a19e2cf662ffb6b36d4b4dd143](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/a69ded34-658b-480e-8805-f792801917f3)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=20113
https://cata-twinhead.twinstar.cz/?spell=20271

**Comment by bonfax4** [comment]
Unsure if this applies to all seals, but according to those it applies to SoT and SoR at least

**Comment by UltraNix** [comment]
As I can see, Two Hand Spec increases physical damage.
Judgements are holy spells - thus not affected by it.

**Comment by bonfax4** [comment]
I'm aware buts it's odd 2 different sources telling the same thing. And isn't judge considered a mellee ability that does magic dmg ?

**Comment by bonfax4** [comment]
25% dmg difference would be noticed by theorycrafters

**Comment by Renehadox** [comment]
So this is the reason Rets on Whitemane are doing 2k Judgements, WOTLK damage right there, ngl.

**Comment by UltraNix** [comment]
Fixed.
