### ISSUE TITLE
[Paladin] Censure dmg

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5580]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Censure damage is off.

**How to reproduce:**

**How it should work:**
Censure formula according to EJ, spreadsheet and original tooltip :

Censure: (2.7% AP + 1.4% SP) per stack. At 5 stacks (13.5% AP + 7% SP). 

My current testing stats are  3991 AP and 1271 SP.

Modifiers active : 

- Additive: 1.42 ([SotP](https://cata-twinhead.twinstar.cz/?spell=20225) + [IoF](https://cata-twinhead.twinstar.cz/?spell=53382) )
- Multiplicative : 1.02 ([communion](https://cata-twinhead.twinstar.cz/?spell=31876)). Don't have an aura up so I'm not accounting for the extra *1.03

Expected dmg at 5 stacks : 909
Actual dmg at 5 stacks : 880

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=31803
https://cata-twinhead.twinstar.cz/?spell=31801

**Comment by bonfax4** [comment]
Difference becomes smaller with more, ap so not sure what's causing it.

**Comment by bonfax4** [comment]
Another minor bug about it:

Censure tickrate should change dynamically with haste. It's currently snapshotting on application.
http://web.archive.org/web/20130208003303/http://elitistjerks.com/f76/t110342-retribution_concordance_4_3_voice_dps/#Single_Target 
> 4.0.1 also didn't apply haste to Censure on-the-fly (only on application), which 4.0.3 corrected. We definitely should re-test to be sure. The fact that the glyph ticks have the auto-crit on Demon/Undead is an interesting fact, one I'll also have to add to the OP.

**Comment by Renehadox** [comment]
So this is a damage buff to Rets?

**Comment by UltraNix** [comment]
Fixed.
