### ISSUE TITLE
[Paladin] Avenger's Shield not bouncing to pets

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Completely ignoring pets as targets for bounce at the moment

**How to reproduce:**
Cast Avenger's Shield on any class with pet next to them, will not bounce.

**How it should work:**
https://youtu.be/KdjK4fuD0ow?si=IOROspWCyNcik95m&t=529

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=31935

**Comment by djesic** [comment]
also not to mirror images

**Comment by djesic** [comment]
nor shaman wolves, I sure would love to apply Seal of Justice + daze from glyph on them

**Comment by UltraNix** [comment]
Fixed.
