### ISSUE TITLE
The forging is broken

### ISSUE THREAD

**Issue by Russianvodka123** [gamefreedomgit/Maelstrom#5583]
I have 26% of the crit, and a rating of 1300. When I raise the percentage of criticism, the rating does not grow. Other hunters have 33% of the crit and they have a 2000+ rating of it

Character name Russianvodka

![2024-01-26_23-53-01](https://github.com/gamefreedomgit/Maelstrom/assets/157846892/d132ff6a-0d49-4712-a5f2-50e76d4b9ef7)

**Comment by Russianvodka123** [comment]
![2024-01-26_23-53-01](https://github.com/gamefreedomgit/Maelstrom/assets/157846892/63361239-1561-411a-939b-f10af420610c)


Вот я сменил специализацию, процент увеличен а рейтинг нет

**Comment by Russianvodka123** [comment]
![2024-01-26_23-56-42](https://github.com/gamefreedomgit/Maelstrom/assets/157846892/e0b2ab0f-d91b-4a29-b448-47746cecfbd3)



Вот я сменил ветку талантов, процент вырос а рейтинг нет

**Comment by Pornoodemon** [comment]
Создай тикет на английском иначе  кина не будет . Через переводчик переведи

**Comment by Russianvodka123** [comment]
> Создай тикет на английском иначе кина не будет . Через переводчик переведи

я смотрю ты тут часты персонаж)

**Comment by Pornoodemon** [comment]
> > Создай тикет на английском иначе кина не будет . Через переводчик переведи
> 
> я смотрю ты тут часты персонаж)

типа того)

**Comment by djesic** [comment]
Agility (Lukavost?) gives critical strike rating. Is that the same on both screenshots?

**Comment by Russianvodka123** [comment]
> Ловкость (Лукавость?) дает рейтинг критического удара. Это одно и то же на обоих скриншотах?

there are different percentages on different screens, but the rating is the same

**Comment by Pornoodemon** [comment]
> > Ловкость (Лукавость?) дает рейтинг критического удара. Это одно и то же на нижних скриншотах?
> 
> на разных экранах разные проценты, но рейтинг один и тот же

Бафы проверял? Может доп проценты дает баф или  вкачаный талант

**Comment by djesic** [comment]
The attack power is also way different.
My assumption: Roar of Courage cat buff? 
1307 rating on both and give the same percentage. Has to be different agility

**Comment by UltraNix** [comment]
Critical rating and crit chance are different stats.
If you have some auras that increases your critical chance, your crit rating might be the still the same.
Agility increases your critical chance, not rating.
