### ISSUE TITLE
Heroic Warmaster Blackhorn - Fire Extinguishing NPCs Registering Markers As Fire

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5584]
**Description:**
Currently, the NPCs that are extinguishing fires on Heroic Warmaster Blackhorn are incorrectly registering markers as fire and then extinguishing them as evidenced in the timestamp below.

https://www.twitch.tv/videos/2044386495 - 05:51:28

**How to reproduce:**
Place markers and let the HP of the Skyfire Ship drop to spread fire on the ship and watch the NPCs extinguish the markers.

**How it should work:**
The markers should not be registered as fire and thus should not be extinguished.

**Comment by UltraNix** [comment]
Fixed.
