### ISSUE TITLE
Transmogrification

### ISSUE THREAD

**Issue by Cqueen26** [gamefreedomgit/Maelstrom#5585]
Just needed to know. Say I have a one hand weapon. If I transmog it to look like a two handed weapon (or vice versa) does my damage, damage per second, and any stat buffs like +2 spirit, remain the same for whatever I have currently equipped? It won't mess up or effect what I currently have equipped?

**Comment by Pornoodemon** [comment]
Transmogrification only affects visual appearance

**Comment by Sketish** [comment]
Not a bug
