### ISSUE TITLE
[Druid] Balance Druid PVP 4-Set Bug

### ISSUE THREAD

**Issue by itslethis** [gamefreedomgit/Maelstrom#5589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Video link where I show and explain what is the problem: https://www.youtube.com/watch?v=e_dg-o2rum8

**Description:**
Reaching 100 Solar/Lunar energy from getting hit by enemy do not gets me into Solar/Lunar eclipse. When this situation happens to get into Solar/Lunar eclipse I need to use Starsurge/Wrath/Starfire on enemy target or use 2x Moonfire (Lunar Shower talent).

**How to reproduce:**

**How it should work:**
Reaching 100 Solar/Lunar energy from getting hit by enemy should get me into Solar/Lunar eclipse and I should receive increased damage buff.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
