### ISSUE TITLE
Cooldowns do not reset after bosses in Hour of Twilight dungeon

### ISSUE THREAD

**Issue by WorrunTV** [gamefreedomgit/Maelstrom#5590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As title suggests, when you kill any of 2 (not sure about 3rd) Arcurion or Asira Dawnslayer, personal cooldowns as well as Sated debuff from Heroism/TW do not reset.

**How to reproduce:**
Pop CDs, kill any of first two bosses in HoT and see the result.

**How it should work:**
Should reset cds after boss kill like every other dungeon/raid.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
