### ISSUE TITLE
Paladin Auras

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5592]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Auras from other Paladins make own auras uncastable, because when player is under effects of them, UI treats them as if they are active.

Other Paladin's auras should not make own auras appear as active in aura (stance) bar.

Retail:
https://youtu.be/YCXVL-IEasU?t=18
https://youtu.be/LVcWZ5hfhis?t=297
https://youtu.be/75GUQE-ozo0?t=114

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Provide any cata proof, not wotlk one

**Comment by Renehadox** [comment]
> Provide any cata proof, not wotlk one

Sketish why Whenever I post a bug you are asking for a retail proof ?

Blizzard didn't change literally a single thing regarding auras from wotlk to cataclysm man.

Here is your retail proof:

https://www.youtube.com/watch?v=IufyT4br41I&t=77s&ab_channel=PlaiOfficial 0-12 there are 2 paladins and only his resistance aura is shown.

https://www.youtube.com/watch?v=0xd9wAETcq8&ab_channel=Swifferr - only his armor aura is shown and other paladin concentration aura is not.

**Comment by Sketish** [comment]
> > Provide any cata proof, not wotlk one
> 
> Sketish why Whenever I post a bug you are asking for a retail proof ?
> 
> Blizzard didn't change literally a single thing regarding auras from wotlk to cataclysm man.
> 
> Here is your retail proof:
> 
> https://www.youtube.com/watch?v=IufyT4br41I&t=77s&ab_channel=PlaiOfficial 0-12 there are 2 paladins and only his resistance aura is shown.
> 
> https://www.youtube.com/watch?v=0xd9wAETcq8&ab_channel=Swifferr - only his armor aura is shown and other paladin concentration aura is not.

Because most of your reports were invalid. That's a solid reason

**Comment by Renehadox** [comment]
> > > Provide any cata proof, not wotlk one
> > 
> > 
> > Sketish why Whenever I post a bug you are asking for a retail proof ?
> > Blizzard didn't change literally a single thing regarding auras from wotlk to cataclysm man.
> > Here is your retail proof:
> > https://www.youtube.com/watch?v=IufyT4br41I&t=77s&ab_channel=PlaiOfficial 0-12 there are 2 paladins and only his resistance aura is shown.
> > https://www.youtube.com/watch?v=0xd9wAETcq8&ab_channel=Swifferr - only his armor aura is shown and other paladin concentration aura is not.
> 
> Because most of your reports were invalid. That's a solid reason

Most of them were not invalid but okay...

**Comment by UltraNix** [comment]
Fixed.
