### ISSUE TITLE
Lunar Festival - Elders not spawning

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5593]
**Description:**
At least one Elder NPC is not spawned inside a dungeon during Lunar Festival event.  Elder Igasho should appear next to Omorok in the Nexus, but is completely absent.

**Comment by frostwave942** [comment]
![WoWScrnShot_012824_154642](https://github.com/gamefreedomgit/Maelstrom/assets/146029129/2582ba7c-94ab-48af-b5cb-610a26ea9d3f)

i think some spawns on heroic may not work, so try to change difficulty to normal.

**Comment by UltraNix** [comment]
Fixed.
