### ISSUE TITLE
shattrath city daily cooking quests barrels missing 2 recipes 

### ISSUE THREAD

**Issue by Catalin542** [gamefreedomgit/Maelstrom#5594]
In shattrath city there are 2 kind of rewards the player can pick after finishing the quest.One of them being  https://www.wowhead.com/tbc/item=33844/barrel-of-fish .

Inside this barrel there are many recipes, yet 2 of them never drop:
https://www.wowhead.com/tbc/item=33869/recipe-broiled-bloodfin
https://www.wowhead.com/tbc/item=33870/recipe-skullfish-soup

The drop % might be close to an absolute 0 or it's non existent. Either way after 3-4 months of doing dailys this 2 never dropped.

This is required for https://www.wowhead.com/achievement=1800/the-outland-gourmet  achievement in order to get the Chef title.

**Comment by frostwave942** [comment]
those recipes just have low drop rate, at least for me it took me more than a month to get them.

**Comment by Revly** [comment]
> The drop % might be close to an absolute 0 or it's non existent. Either way after 3-4 months of doing dailys this 2 never dropped.

I doubt it, I was also getting the recipes and it lasted 4 months, I paused and came back when I remembered and in one case he did give me the recipe.
summary: the probability is low and good luck
