### ISSUE TITLE
[Paladin] Glyph of exorcism clip

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5596]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Glyph of Exorcism dot tickrate is being reseted on refreshes.

**How to reproduce:**
Spam exorcism with the glyph on

**How it should work:**
Should have the cata dot clip mechanics like any other dot. duration + time until next tick from the previous dot.

Proof : https://youtu.be/rTXSYbaqYWo Dot when refreshed goes above the 6 sec duration, up to a max of 8 sec. 

**Database links:**
https://cata-twinhead.twinstar.cz/?item=41103
https://cata-twinhead.twinstar.cz/?spell=879

**Comment by UltraNix** [comment]
Fixed.
