### ISSUE TITLE
Huargen Druida Cadena de misiones BUG

### ISSUE THREAD

**Issue by Drrez23** [gamefreedomgit/Maelstrom#5599]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Al llegar a la mision "Fuego Lunar" donde tienes que practicar el poder Fuego Lunar aunque lo lances varias veces a diferentes objetivos no no toma como realizado

**How to reproduce:**
Solamente tienen que seguir la cadena de misiones como Huargen Druida, veran que en la mision no pueden avanzar

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Translate to english
