### ISSUE TITLE
[pvp] Mortal Strike effects

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5601]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In cata they changed mortal strike effects from 50% to 10% in the start and then buffed them from 10% to 25%,.

However, forgot / missed to buff one of those abilities, ie. demonology warlock's felguard's "Legion Strike". 
It still applies 10% MS effect instead of 25% which is inconsistent with all the other effects.

I ask for this change as it will help a very weak spec that is borderline not playable and not meta at all in arenas (due to spam dispels and no dispel protection). While still not effecting or buffing affliction which is the main warlock spec and already S tier / A+ tier , as Felguard is a demonology only pet other warlock specs cannot use it.

Here is the official blue post on the matter:

"Mortal Strike (and similar debuffs)
We dropped the healing debuff from 50% to 10% some time ago, but were convinced at 10% that it was hard to appreciate the effect at all. We want to try Mortal Strike et al. at 25% to see if it feels useful but not mandatory. If 25% is too much and 10% is too little, then it may mean the entire mechanic may not have much of a future. We decided to only change the debuff for the warrior, rogue, and hunter, restoring the original relationship between “strong” and “weak” MS that we had in Lich King."

https://www.wowhead.com/blue-tracker/topic/explanation-of-4-3-balance-changes-part-two-3932489

**How to reproduce:**
Summon your Felguard as Demonology warlock and use Legion Strike, it applies 10% healing reduction, instead of 25%, like all other sources ingame.

**How it should work:**
Legion Strike should apply 25% healing reduction just like all other 'mortal strike' effects ingame.

**Database links:**
https://www.wowhead.com/blue-tracker/topic/explanation-of-4-3-balance-changes-part-two-3932489

**Comment by Waroxx-QA** [comment]
Not a bug but a suggestion, github is for bugs, suggestions are posted on discord 😅
