### ISSUE TITLE
Eye for an Eye paladin talent does not reflect damage to Ultraxion

### ISSUE THREAD

**Issue by slchristensen** [gamefreedomgit/Maelstrom#5602]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Eye for an Eye paladin talent does not do damage to Ultraxion, or is not tracked in damage meters

**How to reproduce:**
Ret pally with 'eye for an eye' specced, get hit by Ultraxion's Twilight Instability (shadow magic damage aoe), 0 damage shown for 5+ attempts of logs

**How it should work:**
40% of the time the boss should take 30% damage. Over the course of a 10M Heroic attempt, 4M damage taken * 0.4 * 0.3 should be 480k damage returned to the boss. Roughly a 1.3k dps increase.

This works on Rag's aoe fire damage, so it should be the same.

**Database links:**

**Comment by Waroxx-QA** [comment]
"It seems only to trigger from direct spell hits."
[SOURCE](https://www.wowhead.com/spell=25988/eye-for-an-eye#comments:id=1296198)
