### ISSUE TITLE
King Crawler Mob (doesnt exist)

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5603]
Hello all.
There are some mobs calles KING CRAWLER in Feralas
But they are doesnt exist (may be 1-2 instead many).
It will be helpful if they will be much on their places.
Thanks a lot.

https://cata-twinhead.twinstar.cz/?npc=51714      MOB

![WoWScrnShot_013124_002321](https://github.com/gamefreedomgit/Maelstrom/assets/154531435/6ddf004c-dd0c-48d8-8ecc-da107d42e6e1)
![WoWScrnShot_013124_002327](https://github.com/gamefreedomgit/Maelstrom/assets/154531435/a934fabc-11fa-4ce2-9923-303d6fd5531d)

Empty lake

**Comment by UltraNix** [comment]
They are around the big lake, not in it.
