### ISSUE TITLE
[warlock] [talent] "Emberstorm"  and "Decimation"

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5604]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock talent, "Emberstorm" (second row in the destruction tree) is not working correctly when picked with the talent "Decimation" (5th row in the demo tree), it is not reducing the casting time of soul fire by the correct amount. 

**How to reproduce:**
1. pick the talent "decimation" in the demo tree 2/2.
2. pick the talent "emberstorm in the destro tree 2/2.
3. cast soulfire with emberstorm active and decimation not active (ie on a target above 25% hp) and note the cast time of soulfire.
4. cast soulfire with emberstorm active and decimation active (ie on a target below 25% hp) and note the cast time of soulfire.

**How it should work:**
The talent emberstorm should reduce the casting time of soulfire by 0.5sec per talent point. ie 1/2 should reduce by 0.5sec and 2/2 should reduce by 1sec. As it says in the talent itself. 
Likewise the talent decimation should reduce the casting time of soulfire by 20%/40% per talent point, such that if you have 2/2 in "decimation" it will reduce the cast time of soulfire by 40% - when used on target at or below 25% hp.
**Database links:**
Decimation rank 1 (1/2):  https://cata-twinhead.twinstar.cz/?spell=63156
Decimation rank 2 (2/2):  https://cata-twinhead.twinstar.cz/?spell=63158
Emberstorm rank 1 (1/2):  https://cata-twinhead.twinstar.cz/?spell=17954
Emberstorm rank 2 (2/2):  https://cata-twinhead.twinstar.cz/?spell=17955

**Comment by bonfax4** [comment]
Tested and see nothing wrong ? Decimation multiplies your ability cast time by 0.6% and the numbers match up for me. 1 sec reduction comes before you apply other reductions like haste and talents.  ( 4 sec - Emberstorm ) / (1+haste % /100) * 0.60 <- Decimation. Simcraft code follows this too.

**Comment by UltraNix** [comment]
Also tested and see no bug here. 
Flat modifiers (like Emberstorm) are always calculated before pct modifiers (like Decimation).
