### ISSUE TITLE
Combat Rogue Blade flurry

### ISSUE THREAD

**Issue by EvilTwilight0901** [gamefreedomgit/Maelstrom#5606]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It seems like Blade Flurry's damage is bugged, please find attached screenshot. Blade Flurry should be the top on the damage meter, it procs lower than expected, the damage is also lower than expected. It works well before last reset.

**How to reproduce:**
Please do check with the procs and the procs damage, it should be 100% of the core damage spells and auto attacks.

**How it should work:**
Blade Flurry should replicating the core damage spells (Sinister Strike, Revealing Stike, Eviscerate) and auto attacks.

**Database links:**
![WoWScrnShot_013124_070139](https://github.com/gamefreedomgit/Maelstrom/assets/154529350/98777ea7-273f-4ca3-8c58-47d5378ec3d1)

**Comment by Sketish** [comment]
So what exactly is hitting for too low ? And from what site you get information it should be top dmg ?

**Comment by EvilTwilight0901** [comment]
> So what exactly is hitting for too low ? And from what site you get information it should be top dmg ?

Hello Sketish, i believe Blade Flurry should be replicating/copying 100% Combat Rogue's Core abilities and Auto Attacks. If you take a look on my screenshot, there were 246 auto attacks proc during the fight, but Blade flurry only procs 54. And this doesnt include the Revealing Strike, Sinister Strike, and Eviscerate. 
![WoWScrnShot_013124_072856](https://github.com/gamefreedomgit/Maelstrom/assets/154529350/53668b3b-2dc9-471a-a5cf-a5d0893a4b0a)
![WoWScrnShot_013124_073055](https://github.com/gamefreedomgit/Maelstrom/assets/154529350/b659b68e-a852-4f70-9e03-822de2eea579)

**Comment by EvilTwilight0901** [comment]
I just had another 1m fight on the dummys, only auto attacks and Blade flurry was on. Please check the screenshots
![WoWScrnShot_013124_073732](https://github.com/gamefreedomgit/Maelstrom/assets/154529350/17c98bad-1cd4-4ce6-b831-95a7a0ec633b)
![WoWScrnShot_013124_073736](https://github.com/gamefreedomgit/Maelstrom/assets/154529350/b499cd8c-7ac4-4374-9b69-10c8e335f817)

301 auto attacks in total, but Blade Flurry only procs 83 times.

**Comment by EvilTwilight0901** [comment]
There is another report 5574 that incdicates the same problem, please help.

**Comment by Polynomix** [comment]
looks like it has a 1s icd on the proc after last week changes #5574

**Comment by EvilTwilight0901** [comment]
Please let me know if you need more information on this, i could ask my guidies to send more dmg screenshots.

Many thanks.

**Comment by UltraNix** [comment]
#5574
