### ISSUE TITLE
Setting XP Rate

### ISSUE THREAD

**Issue by Cqueen26** [gamefreedomgit/Maelstrom#5607]
Hey when I was trying to change  my xp rate, I accidentally typed in “.xp reset 1”. I did this twice and I hope it didn’t mess anything up and setting xp rates is still working correctly. Yellow text did pop up and I think it said xp set to 1 but I’m not entirely sure. I don’t remember if it said set to 1 or did a full reset. And I honestly don’t want to repeat it in case something was messed up but logging out,exiting, relaunching the game, and logging back in, fixed anything. Just wondering if anyone has ever reported a similar problem or if I  should be looking out for problems.

**Comment by Waroxx-QA** [comment]
What's the issue ? =3

**Comment by Cqueen26** [comment]
I'm worried that I might have messed up setting xp.

**Comment by xmrshoot** [comment]
Dude just ușe .XP reset
