### ISSUE TITLE
2set DPS deathknight tier 13 gear

### ISSUE THREAD

**Issue by alilector** [gamefreedomgit/Maelstrom#5608]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
rime has 60% chance to grant 2 charge and sudden doom has 30% chance to grant 2 charge but when rime triggered most of the time like 9 out of 10 it only grants 1 charge 
**How to reproduce:**
increase the chance of rime triggering 2 charge 

**How it should work:**
it should trigger 2 charges more as i play frost dk in blizard apollo and some other private servers

**Database links:**

**Comment by Sketish** [comment]
Invalid report, 0 sources, no combat logs

**Comment by alilector** [comment]
It's not something that could be shown in combat logs. I could dm you in
discord when im online to show you in game that "Rime" procs only on charge
most of the time.
