### ISSUE TITLE
Sacred radiance, healing rain

### ISSUE THREAD

**Issue by Zaraelh** [gamefreedomgit/Maelstrom#5611]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: In patch 4.0.3a there was a change where it says that Healing Rain, Bloom, Holy Radiance, Holy Word: Sanctuary have a minor effect when healing more than 6 players at a time, this is not happening with rain spells of healing and radiance.
The problem is that the radiance and healing rain is not decreasing when the effectiveness of his healing when he heals in raids of 25, causing problems that a player with an item level of 359 heals more than one who is more armed, causing the spamming of only that spell in its gameplay and not allowing the other healers to heal with dots such as druid and the sacred priest.**

**How to reproduce: This only occurs in raids of 25 and 10, where a radiance is cast and in the recount I already raised more than 35k healing. This can be seen in the attached images, where it is seen that it does not have a minimum value.**

**How it should work: Decreasing the paladin's healing, does not allow the other healers**

**Database links:https://wow.fandom.com/es/wiki/Parche_4.0.3a (see in the Classes part: General) 
https://i.imgur.com/upL9L14.jpeg (As you can see, the raid does not have much damage received and the paladin alone with radiance already raised 17k healing)
https://i.imgur.com/zmRPYHc.jpeg (Here we can see that it does not have a minimum of healing, that is, most of the time it counted all the radiance and the raid was not always together.)
https://i.imgur.com/hUynQv8.jpeg (With healing rain it is the same, it does not have a minimum amount of healing for the allies, that is, all the healing goes into the allies with 4 healers healing at the same time.)**

**Comment by Sketish** [comment]
It has dimishing powert after healing more people past 6. So if radiance is casted on 10 players, 6 of them will get normal healing and 4 will get dimished healing

**Comment by bonfax4** [comment]
Looking at the few logs available on web.archive, holy radiance is doing an average of @70% of total healing on ultraxion, which kinda checks out with your log tbh. 

Check the top 3 logs on Ultraxion [here](https://web.archive.org/web/20120513084048/http://worldoflogs.com/rankings/players/Dragon_Soul/Ultraxion/25N/hps/#) they are accessible.

**Comment by Zaraelh** [comment]
If it is like the records but it is not counting that in the records to be able to do that amount of healing the characters were equipped with the maximum number of objects and with the total benefit of the four parts of tiers 13, but shamans and paladins who do not have complete the benefit they are healing others.

**Comment by bonfax4** [comment]
But the holy paladin you linked is [decently geared](https://db.whitemane.org/armory/maelstrom/Holypain). If it was as broken as you say, we would see higher numbers than those 70%. Unless those numbers were done without the buff.

This shouldn't be hard to test anyway. Go to a nearby AH and cast healing rain. Then test healing rain on yourself or up to 6 ppl.

**Comment by bonfax4** [comment]
@UltraNix @Sketish

Yh smthing is off with it. It heals 6 ppl always for the full amount it seems, regardless of the number of targets. The reduction is only being applied to the extra targets, which is def wrong. This ends up healing 40% more than it should if healing rain hits 10 targets ( assuming that only the extra 4 people are getting the heal *6/10, if that's how it's currently working).  

https://youtu.be/GT52PQ_uKp8 you can see ppl being healed roughly for the same amount in the prepull healing rain. If it worked like it currently does, you'd see few ppl getting healed for 3k+.

**Comment by bonfax4** [comment]
Yh that will be impossible... But  if we follow their intention, it was made so the heal would remain somewhat consistent against 6 or more targets. Should be the same for holy radiance. Other thing that would be good to know is if pets/guardians count towards the heal reduction calculation, or if it's player targets only. I do know they can get healed by it.

**Comment by Sketish** [comment]
Pets are also counting towards that

**Comment by bonfax4** [comment]
Yh I don't think they should tho. I can only find mid mop discussions about it tho because the spell got changed and ppl were debating if was a nerf or buff there.


https://www.mmo-champion.com/threads/1327825-So-what-is-the-deal-with-Healing-Rain-now/page4

**Comment by Polynomix** [comment]
https://discord.com/channels/1040715551531618365/1045188444617461870/1205623655418302465

not sure what Efflorescence has to do with that since its always healing only 3 people per tick even when the whole raid is stacked

**Comment by bonfax4** [comment]
@UltraNix 

Yeah, hopefully that wasn't a nerf. The abilities that suffer from this have the diminishing mentioned in the tooltip.

**Comment by UltraNix** [comment]
No - no changes to Efflorescence. Just took misleading description from wowpedia into comiit message.

**Comment by UltraNix** [comment]
Fixed.
