### ISSUE TITLE
No loot from Attumen the Huntsman 3 CDs

### ISSUE THREAD

**Issue by vrbtski** [gamefreedomgit/Maelstrom#5612]
**Description:**
After killing Attumen the Huntsman twice with no loot, I opened a ticket, GM said to kill boss slowly to fix no loot problem. I did on 3rd ID, did not help. Opened a ticket while in instance, GM came in, respawned the boss, killed it - no loot. Tried on different character, no such problem.
I am not going for mount, only cloth gloves 15% drop chance. 
Boss is still available in raid info.

**How to reproduce:**
Please fix my char: Antagonist.

**Comment by Revly** [comment]
Lately when you kill that Boss with Pets or guardians or active totem it is not giving loot, I don't know why this is, it has happened to me too.

PS: I haven't seen those cloth gloves fall either the times I've gone to kill him...

**Comment by vrbtski** [comment]
> Lately when you kill that Boss with Pets or guardians or active totem it is not giving loot, I don't know why this is, it has happened to me too.
> 
> PS: I haven't seen those cloth gloves fall either the times I've gone to kill him...

Gloves dropped for me on other character. You maybe right, I use mirror images while killing. 
Thanks

**Comment by UltraNix** [comment]
If pets did more than 50% dmg - no loot.

**Comment by Revly** [comment]
> If pets did more than 50% dmg - no loot.

I don't think it's that, because I've done this several times and sometimes without a pet and it's still the same.
