### ISSUE TITLE
Raid Info doesn't show 10/25 man description

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5613]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/5c7e6956-e249-4c1c-917b-9817c52d3ea3)

On raid info below, left of normal it should be written if it is 10 man or 25 man, most of the times it causes confusions to players and they join raids which they are saved before.

It works great for casual wow gamers.

This bug is since release of the server btw.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
In the Calendar y only show id 10 & 25 but can't see The bosse's downs.
And if you are right, the Raid info should show which is 10 and which is 25.

**Comment by Renehadox** [comment]
> In the Calendar y only show id 10 & 25 but can't see The bosse's downs. And if you are right, the Raid info should show which is 10 and which is 25.

its funny that so much pve players are playing here, hardcore ones and nobody ever reported this bug before.

**Comment by Renehadox** [comment]
> In the Calendar y only show id 10 & 25 but can't see The bosse's downs. And if you are right, the Raid info should show which is 10 and which is 25.

I also personally forget sometimes which DS or BH i joined 10 or 25, it just very very confusing not to show raid difficulty.
If it was 10 normal 10 hc 25 nm or 25 hc

**Comment by Revly** [comment]
> > In the Calendar y only show id 10 & 25 but can't see The bosse's downs. And if you are right, the Raid info should show which is 10 and which is 25.
> 
> I also personally forget sometimes which DS or BH i joined 10 or 25, it just very very confusing not to show raid difficulty. If it was 10 normal 10 hc 25 nm or 25 hc

Maybe it is because some of us are aware that bosses we have killed

**Comment by SexyPancake** [comment]
It's not a bug it's an UI limitation due to having split raids.

Wasn't the case before ID split was added in T11.

**Comment by Waroxx-QA** [comment]
IDs are not supposed to be split on Cataclysm, there are two variables on it, Normal and Heroic. I'm not sure if that can be modified.

**Comment by doctopo** [comment]
> > In the Calendar y only show id 10 & 25 but can't see The bosse's downs. And if you are right, the Raid info should show which is 10 and which is 25.
> 
> I also personally forget sometimes which DS or BH i joined 10 or 25, it just very very confusing not to show raid difficulty. If it was 10 normal 10 hc 25 nm or 25 hc

just open calendar

**Comment by Sketish** [comment]
> IDs for 10m & 25m are not supposed to be split on Cataclysm, there are two variables on cataclysm raids on the Raid Info, Normal and Heroic. I'm not sure if that can be modified.

We cant change that due to client limitation, would require custom client to be able to seperate 10/25
