### ISSUE TITLE
Healing Rain and Holy Radiance Evade WARMASTER/MADNESS

### ISSUE THREAD

**Issue by Roywz** [gamefreedomgit/Maelstrom#5614]
Healing Rain Shaman EVADE
Holy Radiance Paladin EVADE

**Description:**
Healing Rain at Shaman and Holy Radiance at Paladin doing evade at Warmaster and Madness.
Also how you will see in the screenshots, it's doing so much evade.
I think the problem of evade is from textures.

**How to reproduce:**
I think u need to work at the textures or see what happens.

**How it should work:**
Stop doing Evade.
![WoWScrnShot_020124_002932](https://github.com/gamefreedomgit/Maelstrom/assets/157684666/cabcbda0-e593-4a0e-8ce3-1624e21796cf)
![WoWScrnShot_020124_002934](https://github.com/gamefreedomgit/Maelstrom/assets/157684666/d3bc49c5-6e05-4343-a8a9-c3d1e190ffcb)
![WoWScrnShot_020124_005112](https://github.com/gamefreedomgit/Maelstrom/assets/157684666/4c127793-da62-4b7d-957a-1e50bf4b6697)

**Database links:**
https://cata-twinhead.twinstar.cz/28121?spell=73920
https://cata-twinhead.twinstar.cz/?spell=82327

**Comment by Revly** [comment]
Absolutely true
Since they applied some changes 2-3 weeks ago these things are happening 🤔

**Comment by Roywz** [comment]
at spine too. 
![WoWScrnShot_020224_011731](https://github.com/gamefreedomgit/Maelstrom/assets/157684666/f2e62ac3-5ad7-4ef0-aa4c-e0bbde9a8c4c)

**Comment by xmrshoot** [comment]
@UltraNix  And hunter/lock/dk pets evade too when they did dmg and they dont follow their master and must be resummoned on each platform

**Comment by UltraNix** [comment]
@Roywz @Revly @xmrshoot Do we have any clips with this from our server? I'm not sure if these evades come from pets or something else.

**Comment by UltraNix** [comment]
@xmrshoot When you jump between platforms?

**Comment by Revly** [comment]
> @Roywz @Revly @xmrshoot Do we have any clips with this from our server? I'm not sure if these evades come from pets or something else.

it could be something more, but I do not know

**Comment by xmrshoot** [comment]
@UltraNix Yes , whe u jump between them

**Comment by xmrshoot** [comment]
![WoWScrnShot_020724_215003](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/eddbab3b-b9e6-4ec6-8be9-2a456d5e51db)
Evade on healing rain

**Comment by UltraNix** [comment]
Anything showing targets of these heals would be very helfpul (combat log, addon, etc)

**Comment by Polynomix** [comment]
from madness : ![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/799aaf05-e8ba-4893-82ec-93da5aa00533)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/8a3bac61-7607-4e44-90e1-5958b309cf02)

from spine : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/40b92a13-e249-4c26-92dd-931a40f1a9d0)

i dont see evade on player though

**Comment by xmrshoot** [comment]
i think evade is on pets , cuz pets are bugged
https://github.com/gamefreedomgit/Maelstrom/issues/5642

**Comment by UltraNix** [comment]
Fixed.
