### ISSUE TITLE
Rathrak, the Poisonous Mind

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5615]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rathrak, the Poisonous Mind is bugged. proc is not working correctly. (procs way less than it should, especially in Arena)

**How to reproduce:**
equip dagger test proc.

**How it should work:**
- 17sec cd, 15% proc chance.
- should proc 3 times a minute.
- should also proc off dots not just direct damage. every "harmful spell" has a chance to proc it.
- the proc should apply a dot to your target and all enemies within 10 yards of the target. (aoe)
- the DoT should NOT scale from characters stats ie spellpower, haste, crit. but the DoT itself CAN crit (around 15% crit chance)
- the DoT should benefit from +dmg modifiers such as: Tricks of the Trade / demonology Metamorphosis / curse of elements / ebon plaguebringer / earth and moon, etc.

**Database links:**
https://www.wowhead.com/item=78475/rathrak-the-poisonous-mind
see link above, and check comment section as well.

"On a single target 85 heroic dummy, after 10 million damage, the DoT from this dagger provided around 6% of my overall damage."
As seen above, on single target it should be around 6-7% total dmg depending on class buffs/debuffs, atm its around 1-2%

**Comment by Pornoodemon** [comment]
The problem is precisely that at the moment it only works from direct spells.
In 4 battles in the arena, I see 1proc that unreal.
In the same way, you need to check the operation of the icd, since there is a feeling that sometimes the icd is using without a debuff
https://github.com/gamefreedomgit/Maelstrom/issues/5568

**Comment by pizza-with-pineapple** [comment]
It should proc off direct damage spells, DoTs, and even spells that do Zero dmg. 
It literally says on the item ALL harmful spells can proc it, ie purges/dispels as well.

furthermore it should have a 17sec cd and 15% proc chance as mentioned in my original post, should proc 3 times a minute.
(and it should act as another DoT for warlock's felhunter's "shadow bite".

**Comment by Pornoodemon** [comment]
Regarding Dot ticks, I can’t find a reliable proof. But regarding any other spells, it really works from casting polymorph, fear, etc. on anything, and it’s logical to assume that it should also work from Dot ticks.

**Comment by pizza-with-pineapple** [comment]
no it should not work on DoT ticks. but DoT Casts. (most dots dont do damage straight away) but applying the DoT should proc it. for example applying Corruption should proc it even if it takes ~3sec for first corruption tick to occur.
another example, Bane of Doom takes 15sec for first damage tick, but applying Bane of doom is a harmful spell should proc it.
Plus harmful spells such as purge or offensive dispels should also proc it even though they do zero damage.

**Comment by Pornoodemon** [comment]
> нет, это не должно работать на тиках DoT. но DoT Casts. (большинство точек не наносят урон сразу), но применение DoT должно сработать. например, применение «Повреждения» должно сработать, даже если для появления первого тика повреждения требуется ~3 секунды. Другой пример: Bane of Doom занимает 15 секунд для первого тика урона, но применение Bane of Doom — вредного заклинания должно сработать. Кроме того, вредные заклинания, такие как чистка или атакующее развеивание, также должны срабатывать, даже если они наносят нулевой урон.

I agree with you Exactly the same way it works on twin . We are waiting for a response from the developer.

**Comment by pizza-with-pineapple** [comment]
fyi all of this is regarding the Wartorn versions of the dagger. (normal and heroic Wartorn versions)

(i dont know about the pve raid versions. did not test them.)

**Comment by Pornoodemon** [comment]
> К вашему сведению, все это касается версий кинжала Wartorn. (обычная и героическая версии Wartorn)
> 
> (я не знаю о версиях для пве-рейдов. Не проверял их.)

I think the final version 4.3+ of this dagger worked the same for both pvp and pve

**Comment by pizza-with-pineapple** [comment]
yes this is all for patch 4.3 and above ofc.

**Comment by Dimonz10** [comment]
Please watch this https://youtu.be/DXDIYOnubS4?si=mEnwbAmRjazQR51M&t=135 with x 0.25 speed and if u watched it correctly you will see that inside the GCD it procs its means it procs from a dot ticks please watch it and rewatch it.

conclusion "it does proc from dot tics"

![rathraaak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/b2ec29b6-aa0c-4ce0-b0ac-87a14b4dfb26)
in the same GCD
![rathraaaak11](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/6b039624-b93b-4d00-a930-59fe89c0411e)
