### ISSUE TITLE
Healthstones

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5616]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You cannot use Healthstones while being in a Paladin's Hand of Protection (HOP)
https://cata-twinhead.twinstar.cz/?spell=1022

**How to reproduce:**
get a paladin to HOP you, then try to use Healthstone.

**How it should work:**
Healthstones should be usable while inside HOP, as HOP prevents the use of physical abilities not spells.
and Healthstone is in the spell-category, to be specific it is in the shadow school.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=1022
https://cata-twinhead.twinstar.cz/?spell=34130

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/df9c4b1f-ed09-45cf-81da-2395ddbad472)

**Comment by pizza-with-pineapple** [comment]
oh wow, did not pay attention, does that mean conjured food from a mage is also physical?

**Comment by Pornoodemon** [comment]
> oh wow, did not pay attention, does that mean conjured food from a mage is also physical?

Don't know)

**Comment by pizza-with-pineapple** [comment]
you are correct. bug report is wrong. and can be closed.

**Comment by SimonBpvp** [comment]
I think can close your own report if you want
