### ISSUE TITLE
madness Shrapnel

### ISSUE THREAD

**Issue by Gunda456** [gamefreedomgit/Maelstrom#5617]
[//]: # ([cata-twinhead.twinstar.cz](https://cata-twinhead.twinstar.cz/?spell=106791)

**Description:**
Shrapnel cast from the fragments  doesn't align with the debuff;  whenever you get hit from it  still have  1 second left for the debuff 

**How it should work:**
by the time cast is over you shouldnt have the debuff

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=106791

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/38547744-09de-4a23-9f52-25aa9d8ebc77)
Shrapnel cast lasts 6 sec.

![Uploading image.png…]()
Shrapnel debuff lasts 7 sec.

Not a bug.
