### ISSUE TITLE
(spine)    Residue abnormal speed

### ISSUE THREAD

**Issue by Gunda456** [gamefreedomgit/Maelstrom#5618]
**Description:**
Residue is reaching the nearest  hole so fast if you compare it to this pov
https://www.youtube.com/watch?v=_PYhiz6GL8M&t=80s

**How it should work:**
their movement speed should be greatly reduced

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=105223

**Comment by UltraNix** [comment]
Fixed.
