### ISSUE TITLE
ultrax fading lights target selection

### ISSUE THREAD

**Issue by Gunda456** [gamefreedomgit/Maelstrom#5619]
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ultrax fading light not always picking the target thats  tanking it

**How it should work:**
it should always pick whoever is tanking it and under no circumstances it should pick 2 tanks at once

https://www.youtube.com/watch?v=9ealr_ggLDs

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=110079

**Comment by Waroxx-QA** [comment]
We need a video proof of this when it happens.

it was already reported and fixed, this can happen if your Feral off tank starts the boss as a cat and doesn't get the last defender (tank debuff).
