### ISSUE TITLE
(ultrax HC) Faded Into Twilight working same as normal

### ISSUE THREAD

**Issue by Gunda456** [gamefreedomgit/Maelstrom#5620]
**Description:**
as the title says its working same as normal causing no threat generation for the whole duration

**How it should work:**
it should cause 100% Physical damage taken  for the whole duration 

**Database links:**
(HC) https://cata-twinhead.twinstar.cz/?spell=109462
(NM)https://cata-twinhead.twinstar.cz/?spell=105927

**Comment by Waroxx-QA** [comment]
It's working properly, mind that it's still resetting the threat on the tank, you can use the addon "Omen Threat Meter" to check it.
