### ISSUE TITLE
A bug has occurred in a mission in Deep Rock State

### ISSUE THREAD

**Issue by h7901657** [gamefreedomgit/Maelstrom#5622]
I am a Chinese player and my description may not be accurate

The mission of Deep Rock State is to subdue the enemy Monolok (mission name: Catch a prisoner). The mission monsters are flying around,

It's the mission of the Alliance airship in the sky

If you see it, you can also contact me in the game. My game ID is Qiguigui

**Comment by Waroxx-QA** [comment]
Please add wowhead/twinhead links
