### ISSUE TITLE
madness Corrupting Parasite

### ISSUE THREAD

**Issue by Gunda456** [gamefreedomgit/Maelstrom#5623]
**Description:**
Corrupting Parasite is  inflicting 0 shadow damage  to the host

**How it should work:**

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=108649

**Comment by Sketish** [comment]
You mean the dot dmg before add spawn ?

**Comment by Gunda456** [comment]
i mean that

**Comment by Waroxx-QA** [comment]
Wowhead link :[https://www.wowhead.com/spell=108649/corrupting-parasite](https://www.wowhead.com/spell=108649/corrupting-parasite)

Some logs that confirm your report : [https://www.warcraftlogs.com/reports/jTrCYmyGxRc78thD#fight=24&type=damage-taken&by=ability](https://www.warcraftlogs.com/reports/jTrCYmyGxRc78thD#fight=24&type=damage-taken&by=ability)

**Comment by UltraNix** [comment]
Fixed.
