### ISSUE TITLE
Hymn Of Hope (Priest)

### ISSUE THREAD

**Issue by Anderzrez** [gamefreedomgit/Maelstrom#5624]
https://cata-twinhead.twinstar.cz/?spell=64901

**Description:**
It should restore mana per tick over a channeled time. It only seems to grant the mana on the first tick of channeling and then nothing. The tick it does grant is big.

**How to reproduce:**
I have cast the spell many times and changed talents.

**How it should work:**
It should restore 2% mana to 3 nearby low mana friendly party or raid targets every 2 sec for 8sec, and increases their total maximum mana by 15% for 8sec. Maximum of 12 mana restores. The Priest must channel to maintain the spell.

**Database links:**

**Comment by Lycadd** [comment]
rather than doing nothing, the ticks are sometimes stolen by random summons 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/134816583/88695f8d-0233-4c04-8524-39992729fed5)

**Comment by UltraNix** [comment]
Fixed.
