### ISSUE TITLE
[Warlock Talent] Demonic Circle: Teleport

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5625]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock's teleport "demonic circle: teleport" does not work at times. It does not teleport you to the set-location where you place your portal. Instead the ability is put on CD and nothing happens, you stay on the same spot. (animation does occur but you do not get teleported and the ability goes on full cd)

note; this bug only happens sometimes but when it does happen its 100% loss (in arena) as teleport is suppose to be your escape and you rely on this to get to safety and when that doesnt work, you are dead almost certainly.

**How to reproduce:**
not sure what is triggering this bug but as mentioned above it mostly happens in arena/bgs. 
the animation does happen but it doesnt teleport your character.  and the ability goes on full cd.

**How it should work:**
it should teleport you to the location where you casted "demonic circle: summon".

**Database links:**

**Comment by Pornoodemon** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/4172
