### ISSUE TITLE
Either vial of shadow should not proc Bone-Link or the Dark Phenix 2 set bonus should work with Vial and Bone-Link Crits

### ISSUE THREAD

**Issue by wickedlike** [gamefreedomgit/Maelstrom#5627]
**Description:**
Bone-link procs off Vial because it counts vial of shadows as " your melee strike " 
Dark Phenix (2) set makes is so " my melee critical strike hits deal 6% additional damage over 4 sec "  

**How to reproduce:**
You can reprocude Vial of shadows procing Bone-Link fetish by having Vial and Bone-Link equiped and spamming trown at a target dummy. You get a vial proc of a ranged attack(trown), and that proc counds as me melee-ing and it will proc Bone-Link
And you can reprocude Dark Phenix not setting the target on fire by having it equped while attacking the dummy until you only get a Vial or Bone-Link proc to crit (reseting if you get auto crits setting the target on fire)

**How it should work:**
Either Bone-Link and Vial should not proc off eachother or Dark Phenix should work with them.

SS of Trown into vial proc into bone-link proc (and nokaled procs)
![image kek](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/59d51605-2cb1-4db4-bde3-f78a3de5799f)

SS of Dark Phenix not setting the target on fire with Vial crits
![WoWScrnShot_020324_205245](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/cfe2f97f-807c-4396-9ea1-44a4e0bb9f14)

Dark Phenix discruption 
![WoWScrnShot_020324_205828](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/2371b9d1-5670-4fdf-ac1f-72ab311a7e5c)
Bone-Link discription 
![WoWScrnShot_020324_210449](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/aec402cd-57d7-42f7-8c03-521bd74e6575)
Vial discription 
![WoWScrnShot_020324_213345](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/455f9aca-3c52-4a5e-a959-6b63dced624e)

**Comment by UltraNix** [comment]
Fixed.
