### ISSUE TITLE
[mage] [talent] shatter and glyph of pyroblast

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5628]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
mage glyph doesnt work on shatter talent

**How to reproduce:**
attack frozen target

**How it should work:**
talent shatter should affect on glyph of pyroblast +5% crit chance

**Database links:**
https://wowpedia.fandom.com/wiki/Glyph_of_Pyroblast
https://wowpedia.fandom.com/wiki/Shatter (on cata this talent give x3 chacne crit in frozen target

video on server now https://www.youtube.com/watch?v=TkA1ud7aWxA&ab_channel=%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9

p.s. I have 24.92% crit chance+5% critical mass+ **5% glyph** should = 100% chance crit for pyroblast

**Comment by UltraNix** [comment]
Fixed.
