### ISSUE TITLE
Sins of the sea witch

### ISSUE THREAD

**Issue by brooksjoe074d** [gamefreedomgit/Maelstrom#5629]
https://www.wowhead.com/quest=28843/sins-of-the-sea-witch This quest is only offered to alliance players when you zone into throne of the tides. it's marked but both horde and alliance on wowhead. 

make a horde toon, zone in no quest. 
make an alliance toon, zone into throne of the tides and the quest giver gives the quest.

Show be able to accept quest on either horde or alliance. faction should not matter.

**Comment by UltraNix** [comment]
Fixed.
