### ISSUE TITLE
Daughter's Embrace

### ISSUE THREAD

**Issue by UnclePedo** [gamefreedomgit/Maelstrom#5630]
Can't complete the mission because I can't trigger the scene of Voss speaking with his father.
What should I do?

![WoWScrnShot_020424_154443](https://github.com/gamefreedomgit/Maelstrom/assets/158838395/2dea7d62-30bc-49d9-9e0d-7aae6d341e4a)

Can't interact or attack any of those charecters

**Comment by UnclePedo** [comment]
Just notice Lillian is always casting Stealth repeatedly

**Comment by UnclePedo** [comment]
She's always with the stealth
![WoWScrnShot_020424_162229](https://github.com/gamefreedomgit/Maelstrom/assets/158838395/74aa7900-3327-4e4d-9f2e-9d700150d876)

**Comment by PanJanuszek** [comment]
should be fixed after restart
