### ISSUE TITLE
[Mage][Talent] 'Arcane Potency' talent not working

### ISSUE THREAD

**Issue by xakepka** [gamefreedomgit/Maelstrom#5632]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Talent "Arcane Potency" doesn't work as it should. What the talent should be doing: Increases the critical strike chance of your next damaging spell by 15% after gaining Clearcasting or Presence of Mind.

**How to reproduce:**
Nothing happens, it's like I haven't activated the talent even though it is.

**How it should work:**
Talent should up my crit chance by 15%, but this doesn't show up in any of my stats. My base critical chance is 14.56% and upon activating talent this should increase to close to 29.56%. However my crit stays the same (14.56%). This is definitely a bug because I only have this issue on Cataclysm(4.3.4), on WOTLK (3.3.5) the talent works as it should and the stats are shown. I've provided pictures of both WOTLK and Cataclysm (4.3.4).

![WoWScrnShot_082723_103459](https://github.com/gamefreedomgit/Maelstrom/assets/141313960/4a3f2975-dc20-4ff7-8aee-3663b557b307)

![WoWScrnShot_082723_103441](https://github.com/gamefreedomgit/Maelstrom/assets/141313960/1a07dda9-64d6-4432-9113-da2d7825ec92)

![WoWScrnShot_082823_155106](https://github.com/gamefreedomgit/Maelstrom/assets/141313960/a1d1a395-bee0-454e-a4a8-1ebda1030d0b)
![WoWScrnShot_082823_155056](https://github.com/gamefreedomgit/Maelstrom/assets/141313960/02341e5a-31d0-48f4-808c-66f8d3d64a2c)

**Comment by UltraNix** [comment]
Talent works okay.
It is not shown in your char stats UI sheet.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/416511bf-2a7c-43e4-9c67-5f9af0fc3d03)

Aura 57531 gives extra 15 crit chance to your spells, not to all your critical crit chance.
