### ISSUE TITLE
[Warlock Talent] Demonic Pact

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5635]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Warlock talent Demonic pact is not working properly. It is only granting 1 half of the talent and not the other.
It is not granting the 2% spell damage increase to yourself.
It is only granting 10% spell damage to all party and raid members.

"Increases your spell damage by 2%, and your summoned demon grants the Demonic Pact effect to all nearby friendly party and raid members. The Demonic Pact effect increases spell power by 10%."

https://cata-twinhead.twinstar.cz/?spell=47236

**How to reproduce:**
- note spell damage prior to selecting the talent and note spell damage after selecting the talent.
- note spell damage prior to summoning a pet and note spell damage after summoning a pet.

**How it should work:**
it should grant 2% increase to your spell damage. and grant 10% increase to spell damage for all party/raid members. 
so  in other words, 12% for yourself and 10% for party/raid.
ATM its only granting 10% and ignoring the 2% self buff.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=47236

**Comment by Pornoodemon** [comment]
Hellfire has no base damage spread
1769 before and 1804 after. There's no mistake here
![WoWScrnShot_020524_191138](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/11b8e0a4-9493-494f-af5d-fa692ca89db8)
![WoWScrnShot_020524_191604](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/b673d9ad-f99b-4607-92b2-a09474db337a)
