### ISSUE TITLE
Complaint about other players obtaining equipment that does not belong to them

### ISSUE THREAD

**Issue by h7901657** [gamefreedomgit/Maelstrom#5637]
I am a Chinese player. If there are any unclear expressions, please forgive me
I am Qigui

During the strategy of the Eternal Well dungeon, someone maliciously requested to take away my equipment

Three of them engaged in malicious equipment demand operations through team building behavior

![123123123](https://github.com/gamefreedomgit/Maelstrom/assets/158608565/a40ef5ca-718c-445a-951a-1e80c77830cc)

Mmyhp is a shaman player who requested to take my own power accessory and traded it to Buxifengren (warrior)

Including Yangss (Warlock Player) below

They three players perform dungeon operations and repeatedly help each other in maliciously requesting equipment that should not belong to them

I think as a very fun server, I am just playing different factions of each profession, but this is not a reason for him to help his friends demand equipment that does not belong to him

I was unable to find any other channels for complaints because I had previously reported bugs in the game here. I hope the game administrator can help me transfer them to the contact person responsible for handling the corresponding incident. Thank you

The screenshot of the game is in Chinese because I am a Chinese player.

The content is: 4 players have requested the power jewelry dropped by the final boss.

**Comment by Waroxx-QA** [comment]
To report ninja, go to whitemane discord and type and send !ninja on any text channel, and follow the steps.
