### ISSUE TITLE
Can't Talk to Therazane 

### ISSUE THREAD

**Issue by Wiggiiles** [gamefreedomgit/Maelstrom#5638]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Can't complete the quest "At the Stone Mother's Call" since Therazane is unclickable 

https://www.wowhead.com/quest=26750/at-the-stonemothers-call

**Comment by GM-Nightmaree** [comment]
Make a ticket when this happens and we will assist you  =)
