### ISSUE TITLE
Rogue Shadowstep on Madness

### ISSUE THREAD

**Issue by Battledamn** [gamefreedomgit/Maelstrom#5639]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Using Shadowstep on deathwing's head makes you fall. Simple as that. Same with Killing Spree.

**Comment by frostwave942** [comment]
in ultraxion same thing happens to feral druids after using feral charge.

**Comment by UltraNix** [comment]
Fixed.
