### ISSUE TITLE
Player pets sometimes see you in Vanish

### ISSUE THREAD

**Issue by wickedlike** [gamefreedomgit/Maelstrom#5640]
**Description:**
Pets sometimes see rogues in vanish, in the case of mirror images they will just follow you, in other cases they attack, Sometimes they even remove the vanish buff instantly. 

The pets will only follow you while you have vanish, the moment vanish ends and you enter normal stealth they will drop aggro.

**How to reproduce:**
I dont know exactly how to reproduce it, it just happens on occasion with different results, sometimes one pet will only follow, other times all of them. I just have someone fight with me as they would normally and it will happen.

**How it should work:**
Pets should not see you in vanish as its an improved version of the base stealth. If they drop agro on base stealth, they should drop aggro on vanish as well. 

Mirror images following you in vanish

https://github.com/gamefreedomgit/Maelstrom/assets/156576564/b0cbaa0c-e22b-4b37-82cd-c9fb44e970e0

In the example of the mirror images, if i didnt have a dot that would desteath me, they would stop following me the moment vanish ends and i enter normal steath.

Eventually ill look for more clips when I find the time. Hopefully get a clip of it removing vanish and not letting me cheap or garrot.

**Comment by UltraNix** [comment]
@wickedlike Can you record such video about other pets, e.g. hunter or warlock?

**Comment by wickedlike** [comment]
When i said "in other cases" i was refuring to pets from other classes, this isnt a mage only thing :)
Dk's are by far the worst offenders of this bug with their 2 pets + army of the dead.

**Comment by UltraNix** [comment]
Fixed.
