### ISSUE TITLE
all pets bugged at madness

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5642]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** dk pet andhunter pet bugged here, they dont attack the claw/wing (u need to move the pet behind wing/claw to attack , they evade  when they attack and they dont follow you , u have to resummon/ recall them on every platf , warlock pet too

**How to reproduce:**just attack and move from a platf to another

**How it should work:** to work properly
![WoWScrnShot_020724_000429](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/e35bb8a4-6fe4-4049-9bb8-74afc5f24ab7)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
