### ISSUE TITLE
Mirror Images continuously attacking CC'd targets

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#5644]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is an issue with the mage Mirror Images where they won't stop casting on polymorphed / CC'd targets.

Currently if your mirrors are attacking a target, they will NOT stop casting their abilities if you sheep or blind that target. They will keep attacking that target until they are dead or vanish from your sight. 

Mirrors also don't seem to really have any logic as to who they attack sometimes. I unfortunately didn't record this game, but I had a 2v2 game on Blade's Edge where I was downstairs versus a Death Knight and a Paladin. In this game I deep froze the Paladin and sheeped him (he was still in combat from the deep), and then while in LoS and in combat with the Death Knight I cast mirror images, and the mirrors just immediately fire blasted the Paladin and broke the sheep, rather than attacking (as per the articles I linked below) "the creature that most hates the Mage", which in this scenario, would be the Death Knight who was not CC'd and actively in combat with me, rather than the Paladin next to me who was inside a sheep.

**How to reproduce:**

**How it should work:**
As per this article: https://wowpedia.fandom.com/wiki/Patch_3.1.2#Mages
And this article: https://wowpedia.fandom.com/wiki/Patch_3.2.0#Mages

Mirror Images: The images summoned by this spell will now target the creature that most hates the Mage, and should no longer cast Spell fire fireball [Fire Blast] or Spell frost frostbolt02 [Frostbolt] on targets that are affected by crowd control debuffs that break immediately on damage unless they are already casting these spells when crowd control is applied.

[Mirror Image]: The mirror images will no longer complete casts of Spell frost frostbolt02 [Frostbolt] on targets which are Polymorphed at the time their Frostbolt channel finishes.

So per those patch notes, mirror images should stop attacking, and even cancel their frostbolt casts if the target gets put inside a Crowd Control that breaks on damage (blind, sap, polymorph, gouge, scatter shot etc).

Mirrors also according to this should prioritise attacking targets that "most hate the Mage", which means they should swap off of targets that are not engaging with you and attack either your target or someone closeby that is attacking the mage, rather than wandering off and chasing CC'd healers who haven't touched the mage.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55342

**Comment by mipanka** [comment]
Mirror image can break dragon breath

**Comment by UltraNix** [comment]
Fixed.
