### ISSUE TITLE
Heroic Madness of Deathwing - Corrupting Parasite DOT Ticks Too High - Incorrectly Scaled

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5645]
**Description:**
The scaling damage of the Corrupting Parasite DOT Ticks is currently incorrectly tuned and totals an estimated 644,700 damage.

**How to reproduce:**
Start the Madness of Deathwing encounter in Heroic difficulty.

**How it should work:**
The damage of the Corrupting Parasite DOT is currently too excessive and should not be exceeding  644,700 damage. It should be dealing increasing **shadow damage** which scales with its duration, whereas currently, I don't believe that the damage is Shadow Damage as it is currently not being reduced by Shadow Resistance. 

The damage of the Corrupting Parasite DOT is currently too excessive and should not be exceeding  644,700 damage. A screenshot of the image below shows the DOT damage of the Corrupting Parasite scaling excessively past the point of reasonable values in a 10-man roster at least.

If we take the difference between the 2nd DOT tick and 3rd DOT tick (47400 - 31600), this comes to 15800 and so we can assume that the first tick of the DOT would be 15800, and add the total 10 ticks this comes to approximately 644,700 damage, with the final tick of the DOT doing a total of 157,900.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/cb0d3ad1-21fa-4cd5-a38d-beeb5645a92d)

Please find below a link to the Corrupting Parasite DOT damage as reference for tuning. Perhaps the values of 17549 - 18450 shadow damage are considered low, but re-visit the damage scaling so that it's reasonably scaled.

**Database links:**
https://cata.cavernoftime.com/spell=108601

**Comment by Polynomix** [comment]
https://youtu.be/PpkgAs9YFFg?t=34

**Comment by UltraNix** [comment]
Fixed.
