### ISSUE TITLE
Wartorn (Heroic Gurthalak) Not workin/proccing properly on ret

### ISSUE THREAD

**Issue by KordyH** [gamefreedomgit/Maelstrom#5646]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** 
Doesn't work properly on ret pal procc rarely and hit random target not even main target.

**How to reproduce:**
repair the procc rate on ret

**How it should work:**
work on every melee class .

**Database links:**

**Comment by Heroclassx** [comment]
not only that but it also targets totems and just does 0 dmg to them, it should follow your target similar how gargoyle from dk works with his pet, its the same mechanic

**Comment by bonfax4** [comment]
> not only that but it also targets totems and just does 0 dmg to them, it should follow your target similar how gargoyle from dk works with his pet, its the same mechanic

Not true. Closest target per cast ( it casts on average 3 times if interrupts it). It should not target totems tho so you should open a report.

**Comment by KordyH** [comment]
Give me back my conquest and delete this shit unscripted weapon

**Comment by Pornoodemon** [comment]
> or pay me and i go script properly if u guys can't

The point is that what’s right is not the way you want it to work.

**Comment by UltraNix** [comment]
It has 2% chance on proc.
Only melee attacks:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a1cc3f48-14d3-4c91-9963-11460915b925)
1000 melee hits and 19 summons = 1,9%

Melee attacks with Crusader Strike and Divine Storm:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/2dfe7f9c-8a9b-4c1a-afff-349fc3bbd343)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/7b23e6a7-01bc-4b61-b23f-c423f845b565)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/dd5136df-0b32-4e84-bf38-d0f871d51cae)
In total: 1168 hits and 27 summons = 2,3%

No bug with proc chance.

Targeting totems - that will be fixed.

**Comment by UltraNix** [comment]
Fixed.
