### ISSUE TITLE
Yor sahj adds

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5647]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # ( http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** yor sahj adds are fixating on more than 1 player , as u see in screenshot i had 2 on me and other players who get aggro had 3 at a certain time

**How to reproduce:** hard aoe heal or dmg on adds at yor black phase

**How it should work:** they should fixate on only 1 player and not get aggro from heal or dmg

**Database links:**
![WoWScrnShot_020724_202852](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/24eff41b-4283-48a6-b0d4-9899b5b8e155)

**Comment by UltraNix** [comment]
Fixed.
