### ISSUE TITLE
yor sahj green phase

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5648]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** sometimes players get hit by 2 or 3 digestive acid in a row and other players get hit 0 times and if its combined with purple we cant heal cuz we get stacks , or we get oneshooted like me , u can see in ss , and i wasnt stacked with everyone , i was  5 yards   distance

**How to reproduce:** go green phase and see the dmg

**How it should work:** it should hit equally , not a player 3 times and other 0 

**Database links:** SEE RECOUNT
![WoWScrnShot_020724_203855](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/2fb97433-cc38-4812-9523-47b8c40fdb37)

**Comment by Waroxx-QA** [comment]
True, it hits more than one player at a time, and it's hitting the same players.
This is how it should work
![Screenshot_2024-02-08-00-54-14-25_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/aad1e61a-c8a4-485a-9de1-38a96ee71822)

**Comment by UltraNix** [comment]
You have like 15-17 ranged and it takes 14 targets on 25 man version - yeah, it's most likely it'll take one target more than once.

**Comment by UltraNix** [comment]
If near the boss - no. You can see that on many videos.
The only problem might be the range

**Comment by xmrshoot** [comment]
but the scripts dont say acidhit range players , it says hit random players

**Comment by UltraNix** [comment]
What scripts?

**Comment by UltraNix** [comment]
That's what will be fixed.

**Comment by UltraNix** [comment]
Fixed.
