### ISSUE TITLE
Love is in the Air -bugs

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#5649]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During world event 'Love is in the Air' the quest Crushing the Crown not working. Also the item that generates Lovely Charms not working. This leads to nobody can turn 10 of them into Lovely Bracelets. Also My Love is like a Red, Red Rose achivement not working Wowhead says 100% drop chance on Stonecore HC but didnt drop, either in Blackrock Carverns HC... 

**How to reproduce:**
Fix the quest: Crushing the Crown , fix the item Lovely Charm Collector Kit, and drop chance of Bouqet of Roses. (Red or Ebon roses)

**How it should work:**
Bomb sould work on Chemical Co. Wagon,  kit should collect charms, Bouqet of Roses should drop 100% of certain bosses! 

**Database links:**
https://m.youtube.com/watch?v=BL9b2dutqVE
https://www.wowhead.com/wotlk/item=49661/lovely-charm-collectors-kit#comments
https://www.wowhead.com/item=22206/bouquet-of-red-roses

**Comment by Sylwania** [comment]
For solo players Roses drop from Prince Keleseth in Utgarde Keep in normal dungeon.

**Comment by frostwave942** [comment]
the ach <a href="https://cata-twinhead.twinstar.cz/?achievement=1704">i pitied the fool</a> seems not working too, at least for me a i didn't get credit after placed the fool on wintergrasp.

**Comment by UltraNix** [comment]
@frostwave942 New report please.

**Comment by Sylwania** [comment]
> the ach [i pitied the fool](https://cata-twinhead.twinstar.cz/?achievement=1704) seems not working too, at least for me i didn't get credit after placed the fool on wintergrasp.

You need to target it and write /pity (works on all places)

**Comment by UltraNix** [comment]
Fixed.
