### ISSUE TITLE
Combat Readiness

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#5650]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Combat Readiness stacks up too quickly here, you get 5 stacks pretty much instantly because it has no ICD.

**How to reproduce:**

**How it should work:**
Combat Readiness should have an ICD of around 1 second, as seen here: https://youtu.be/Koi1hhMSX-k?si=kBxOJYJrBy8Ba-nH&t=154

https://www.wowhead.com/spell=74001/combat-readiness#comments

Wowhead also seems to have it listed with a 1 second ICD and some people in the comment section confirming it has a small ICD.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=74001

**Comment by Renehadox** [comment]
If this is not fixed yet, jimusa, on wowhead it says 1-2 sec ICD not 1 sec id, which means it can be from 1 to 2 seconds..

-Works on physical damage only.

This procs from paladins judgement, exorcism and hammer of wrath, why ?

Ultranix, take this into consideration: " Max duration is 30 seconds. There is a small 1-2 second internal cooldown for building stacks. That means you need to pop this before the damage starts coming; it's going to take a few seconds to stack the buff up to 5, and you could be dead by the time that happens."

**Comment by UltraNix** [comment]
It's set to static 1 sec.
