### ISSUE TITLE
[Priest] Echo of light mastery clip

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ability only ticking 6 times.

**How to reproduce:**
spam ability

**How it should work:**
Not getting the extra tick on refresh. (heal bank / 7 ticks , since the hot rolls). 

Proof: 
https://www.youtube.com/watch?v=vdZ-JAH0hEE
Look at his target debuffs and you'll see it occasionally goes up to 7 seconds.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=77489
https://cata-twinhead.twinstar.cz/?spell=77485

**Comment by bonfax4** [comment]
@Ultranix 

Actually, after researching more the heal had weird behavior but it always calculated based on 6 ticks for the most part, but spread through 7 ticks on refresh. Sometimes it bugged out and the bank would account for  -1 tick, as in [heal tick  * (remaining ticks - 1 ) + new heal * mastery] / **6**. So the 7th tick would always be extra healing, if it was never refreshed ofc.

Explained here : https://www.mmo-champion.com/threads/862352-Echo-of-Light-how-does-it-work?highlight=echo+of+light. Simcraft tries to emulate the -1 tick thing too in their code.

**Comment by UltraNix** [comment]
Fixed.
