### ISSUE TITLE
Sandstone Earthen (Level 49) in Tanaris/Uldum - XP difference

### ISSUE THREAD

**Issue by Tanatsuko** [gamefreedomgit/Maelstrom#5653]
Sandstone Earthen (Level 49) can be found in the south of Tanaris in a narrow zone that leads into Uldum. Once you are in Uldum, the same mobs give about 10x more XP. I noticed 1387 XP vs. 11030 XP for the same mob, same level. Most likely a bug.

**Comment by UltraNix** [comment]
Fixed.
