### ISSUE TITLE
Pet Frame Bug - Death Knight

### ISSUE THREAD

**Issue by Tenzoftw** [gamefreedomgit/Maelstrom#5655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When dk pet dies, his frame stay activated with 0 hp and we cant re-summong a new one until we do the maccro : /script PetAbandon();

**How to reproduce:**
Use death pact to sacrifice pet.

**How it should work:**
Pet frame would disapear when pet dies, so we can summon another one without need abandonpet.

**Database links:**

**Comment by UltraNix** [comment]
You don't need a macro - just summon a new pet.

**Comment by Tenzoftw** [comment]
Description:
When dk pet dies, his frame stay activated with 0 hp and we cant re-summon a new one with the usual maccro that should work : 
/use [nopet] Raise Dead; !Dark Transformation
Its a special macro when no pet exist, its summon new one, and when pet exist, its only use dark transformation in same bind. 

So with the frame bug now we need to abandon pet to remove the pet frame : /script PetAbandon(); 

How to reproduce:
Use death pact to sacrifice pet and see the frame of the pet that doesnt disapear. 

How it should work:
Pet frame should disapear when pet dies.

Video in the link below to show the problem : 
https://we.tl/t-p6AW0kmYqB
