### ISSUE TITLE
[rogue] vanish

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
vanish dont work as should "For the first 3sec after vanishing, damage and harmful effects received will not break stealth." this

**How to reproduce:**
use vanish and any dmg aoe spell

**How it should work:**
as in tooltip 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=1856

**Comment by Hermeleen** [comment]
Just to chime in, remember that if you vanish, and i for example press dragon breath it will still hit you. Same with frost nova and cone of cold and such. I don't play rogue that much, almost never, but when on mage and rogue vanishes, and i cone of cold into the position i would assume he is, he gets hit and rooted and if he has no dots, he would still stay in stealth after that. If i dragon breath into vanish, it still hits and disorients but will not put him out of stealth. Pardon me, if i talk about something else.

**Comment by UltraNix** [comment]
Just tested with Flamestrike - does not break stealth from Vanish.
@mipanka Please - record that bug.

**Comment by mipanka** [comment]
Try with direct dmg or I'll record video

**Comment by UltraNix** [comment]
Direct AOE dmg - like what?

**Comment by mipanka** [comment]
flame strike had direct dmg after use, and dot dmg aoe on earth. I mean as example frost nova

**Comment by Hermeleen** [comment]
Guys,... 
https://www.bluetracker.gg/wow/topic/us-en/26859118887-vanish-immuning-is-no-more-intended/

quoting:
....
"We grew tired, as did many players, of "Vanish never works LOL" so we looped back to the original intent of Vanish being about stealth. That is why the tooltip specifically says that harmful effects won't break Vanish, but does *not* say that the harmful effects won't land. We understand some rogues liked using Vanish to "dodge spells" but the ability was never designed to work that way and never was going to work that way very well. The more we tried to let it be a damage negater, the harder time we had letting it guarantee stealth."
...

**Comment by mipanka** [comment]
I now tested with dragon breath, was bug

**Comment by Pornoodemon** [comment]
Similar problem with "Vanish" and "Demon Leap"
Vanish ignores stunl and damage from AOE damage "Demon Leap"
Can this be fixed in one report or do I need to create a new report?
https://cata-twinhead.twinstar.cz/?spell=54785

Perhaps a similar problem will also  with Heroic Leap (Have not tested)

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/613b27d5-b5dc-415c-87bc-3efbebb50102

**Comment by mipanka** [comment]
> Similar problem with "Vanish" and "Demon Leap" Vanish ignores stunl and damage from AOE damage "Demon Leap" https://cata-twinhead.twinstar.cz/?spell=54785 Perhaps a similar problem will also with Heroic Leap (not tested)
> 
>  bandicam.2024-02-13.17-42-58-337.mp4

my report is for different reason, create second one
