### ISSUE TITLE
[rogue] stealth and impact

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5657]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
aoe spred effect from impact (fire mage talent) break stealth

**How to reproduce:**
use impact on random target when rogue near

**How it should work:**
aoe effect shouldn break stealth

**Database links:**
https://wowpedia.fandom.com/wiki/Impact_(mage_talent)
https://wowpedia.fandom.com/wiki/Stealth

https://www.youtube.com/watch?v=mfPrbW4bscU&ab_channel=%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9

**Comment by Sketish** [comment]
any retail proof is thouldn't break ?

**Comment by Pornoodemon** [comment]
https://cata-twinhead.twinstar.cz/?spell=54785
"Demon Leap
Leap through the air 0 yards in front of you, slamming down on all enemies within 5 yards of the target area, causing 1 Shadow damage and stunning them for 2sec.
"
In the same way, it must break stealth. Instead, the rogue  remains stealth

**Comment by UltraNix** [comment]
Fixed.
