### ISSUE TITLE
[item] Stay of Execution (bug?)

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5658]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
player can cancel buff on absorb dmg and start taking dmg

**How to reproduce:**
use trinket and cancel buff

**How it should work:**
idk, bug its or no, mb some users help me

**Database links:**
https://wowpedia.fandom.com/wiki/Stay_of_Execution_(item)

**Comment by UltraNix** [comment]
Not a bug. You can wear off item-casted buffs.
