### ISSUE TITLE
Legacy PVP vendors bugged. 

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#5659]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I noticed other people actually complained about this already. the Legacy vendors for PVP items for transmog don't work. there either not here even though database says they should be, the vendor dosnt do anything when you click him even though it shows the bag symbol, or they bring up a chat box even though it shows the vendor symbol. I know some of them require rating of between 1800-2000 depending on item. I have beyond the required rating and it still doesn't work. if anyone could try to fix this please. 

**How to reproduce:**
N/A

**How it should work:**

self explanatory 

**Database links:**

https://cata-twinhead.twinstar.cz/?item=40824

https://cata-twinhead.twinstar.cz/?item=42319

**Comment by UltraNix** [comment]
#4998
