### ISSUE TITLE
Quest Imperial Qiraji Armaments

### ISSUE THREAD

**Issue by Mynameistakenalready** [gamefreedomgit/Maelstrom#5661]
**Description:**
Quest:
https://cata-twinhead.twinstar.cz/?quest=8789
Have the items, can't turn in

**How to reproduce:**
Take quest, have items:
https://cata-twinhead.twinstar.cz/?item=21232
https://cata-twinhead.twinstar.cz/?item=18562
Try to talk to npc. Question mark above npc is grey. In dialog pop-up 1st option question mark is yellow, next step show required quest items, continue button is red (available to move to next step), yet clicking button doesn't do anything

**How it should work:**
Get quest-> having/getting items-> turn-in. Should move through every option foward.

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=8789
https://cata-twinhead.twinstar.cz/?item=21232
https://cata-twinhead.twinstar.cz/?item=18562

**Comment by UltraNix** [comment]
Fixed.
