### ISSUE TITLE
Morchok bugged when he separated and the clone stopped dealing damage

### ISSUE THREAD

**Issue by Zero0610** [gamefreedomgit/Maelstrom#5662]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When the boss separates on the second face and moves away, Morchok and Kohcrom separate a long distance, Korchom stops dealing damage and stands still and the only boss that deals damage is Morchock, The boss's loot was not recognized.
My character in the game who discovered the bug, the name is Nasgari and my discord is zero0225.

**How to reproduce:**
The clone was separated from the main boss

**How it should work:**
Even if the boss is separated, both should still do damage and their mechanics as normal.
**Database links:**

**Comment by UltraNix** [comment]
Fixed.
