### ISSUE TITLE
Rathrak, the Poisonous Mind Proc still Bugged 

### ISSUE THREAD

**Issue by Dimonz10** [gamefreedomgit/Maelstrom#5665]
[//]: # (http://cata.cavernoftime.com/item=77195)

**Description:**
The Rathrak Proc Still Bugged and not fixed yet @itsemmastone  promote it as fixed but sadly its not 
sometime it doesn't proc even once in a 3min+ arena how can we say it fixed !!!!!!!!!!!!!!!!!!!!
i tested it on single and multiple target i notice that it procs only from direct spells it should proc from DOT ticks as well 
in arena somehow the proc % doesn't work at all i mean if its a 17 icd with 15% proc and multiple target in arena are dotted it should  proc constantly .... here is the tests
My testing in Dummy Single target 10M dmg: 
![rathraksingletar](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/eea43872-6b8e-4b06-89b4-fb56d3d02f04)

https://ibb.co/smsCzNh
Multiple target for 10M dmg:
![rathrakmultipletar](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/ca149454-10d7-471e-9b87-8ecbcc30a96e)

https://ibb.co/myRLN8R
Arena tests :
![rathrak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/0eb0ca94-ef29-4628-8376-8a54a112d605)

https://ibb.co/0ZL7S0y
![rathrak2](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/337be559-0a36-4bb2-be08-e62a686dca30)

https://ibb.co/hy8N2h7

**How to reproduce:**

it has an ICD of 17 Sec and 15% chance ( as an Affliction warlock it should proc constantly cuz of the multi dots)
in Single Target Dummy it should do 5.5%-6.5% Total Damage 
in a Multiple Target it should do 7.5%-8.5%

**How it should work:**

"This weapon's damage does NOT scale with anything other than spell damage and nature spell damage modifiers.
Even the tooltip on weapon changes, the tooltip on buff ([ Blast of Corruption](https://www.wowhead.com/spell=107831/blast-of-corruption)) always stays as "1742 damage...", BUT the real damage it does is what weapon tooltip says plus any spell damage modifier applied on mob (e.g: [(Spell #48506)](https://www.wowhead.com/spell=48506)).
Since [(Spell #77492)](https://www.wowhead.com/spell=77492) increases damage of your nature spells within[ Eclipse (Solar)](https://www.wowhead.com/spell=48517/eclipse-solar), it also increases this weapon's damage and this is shown in weapon's tooltip.
It DOES proc from DOT ticks.
It DOES proc from[ Soothe](https://www.wowhead.com/spell=2908/soothe) and [(Spell #770)](https://www.wowhead.com/spell=770).
It does NOT proc from any physical damage.
edit:
currently I am testing this weapon on bgs with 1492 mastery rating (+32% bonus dmg) and it seems it does 3572 (5519 crit) dmg per tick."

**Database links:**
https://www.wowhead.com/item=77195/rathrak-the-poisonous-mind#comments

**Comment by UltraNix** [comment]
No - it should not proc from DoT ticks (only from DoT applications).
#5568

**Comment by Dimonz10** [comment]
Please watch this https://youtu.be/DXDIYOnubS4?si=mEnwbAmRjazQR51M&t=134 with x 0.25 speed and if u watched it correctly you will see that inside the GCD it procs its means it procs from a dot tic please watch it and rewatch it 
conclusion "it does proc from dot tics"

![rathraaak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/c2677829-9b83-427f-9107-be7b60638ee2)
in the same GCD
![rathraaaak11](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/6cc518c4-26d8-417d-b3cf-f4bca750da3f)
