### ISSUE TITLE
Twilight Barrage on Heroic Warmaster can critical hit

### ISSUE THREAD

**Issue by slchristensen** [gamefreedomgit/Maelstrom#5666]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Twilight Barrage on Heroic Warmaster can critical hit - does 2x the damage it should. It hit our dk for 380k through resist, with no debuff stack on him. Happens very rarely, <5%?

**How to reproduce:**
I've only seen it on 2 of maybe 20+ attempts, And one person was in the circle by themself.

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please provide combat log

**Comment by ginlok1** [comment]
![badgame](https://github.com/gamefreedomgit/Maelstrom/assets/144193924/e8e0926d-8edf-4d77-a06e-3e7f96e1841d)

**Comment by UltraNix** [comment]
@ginlok1 How many stacks of debuff were present? How many players afftected by this damage??

**Comment by ginlok1** [comment]
@UltraNix  just the one person

**Comment by UltraNix** [comment]
Damage from Twilight Barrage is shared among all players.
So if only 1 player is afflicted, then only that player takes all damage - 280k on heroic.

**Comment by UltraNix** [comment]
No further info - closing.
