### ISSUE TITLE
Dragon Soul 10 Normal Starting Warmaster NPC

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5667]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Yesterday, while we were riding someonе started the boss from the NPC Skye Captain Swayse and then one more time where everything started to go x2, including floor bombs, mobs and drakes.

**How to reproduce:**

**How it should work:**
The whole battle only needs to start once.

**Database links:**
https://imgur.com/a/kJEYhjW

**Comment by UltraNix** [comment]
@MirNelthDB So 2 players were able to start the encounter?

**Comment by UltraNix** [comment]
@xmrshoot It happens after wipe?

**Comment by xmrshoot** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/2257c931-ad3d-4789-9381-f83e856aef05)
 ye only after wipe , in this photo is before wipe so only `1 npc

**Comment by UltraNix** [comment]
Okay.

**Comment by xmrshoot** [comment]
so its bugged after wipe , more npc spawn after wipe

**Comment by UltraNix** [comment]
Will be fixed.

**Comment by UltraNix** [comment]
Fixed.
