### ISSUE TITLE
[Priest] [Spell] - Mind Vision bugged (not updated player location)

### ISSUE THREAD

**Issue by Hellsz** [gamefreedomgit/Maelstrom#5668]
**Description:**
The Priest spell Mind Vision does not update the movements of player characters, only pets and NPCs.

**How to reproduce:**
Use Mind Vision on friendly or hostile players. Easier to spot if players are moving but they are all standing or running in place as if they were left behind - Battle of Tol Barad (if used from the center to the Ironclad, Slagworks etc.) - easy to see spells going wrong.

**How it should work:**
Player movement should be updated.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=2096

**Comment by UltraNix** [comment]
@Hellsz I can't reproduce it. Could you record it?

**Comment by Hellsz** [comment]
> @Hellsz I can't reproduce it. Could you record it?

https://i.imgur.com/GQ6MPHS.mp4
hope you can see the moment of the bug, the characters suddenly freeze, but some still move and do not lag

**Comment by UltraNix** [comment]
As I can see you casted another Mind Vision directly on new target - that might be the reason.

**Comment by Hellsz** [comment]
> As I can see you casted another Mind Vision directly on new target - that might be the reason.

I saw that this was fixed in the patch notes and decided to check it out.
1. I tried it again in a Tol Barad and if I don’t change the target, it seems to work as it should do
2. after changing the target, everyone around freezes,  ~~but if you land on the same target that was the first, everyone again seems to come out of the bug (no, everyone still gets the bug and freezes in place)~~
3. This means that when changing targets and at a fairly large distance - more than 100+ yards - the processing of the movement of player characters and NPCs freezes

**Comment by UltraNix** [comment]
Fixed.

**Comment by Hellsz** [comment]
Almost works as it should
Now, if you change the target in the same way and if the second and subsequent targets are further than the character’s visible area, then vision does not work and returns to the player (priest)
doesn't talk about resistance, it just doesn't work
but now all the players’ movements are visible and the players seem to have stopped glitching ++
