### ISSUE TITLE
Anti magic zone dont work at all

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5669]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** AMZ dont work at all, it shuld reduce spell damage by 75% and should it dissapear after absorb an amount of dmg , but the zone is not absorbing at all and not reducing spell dmg at all , its useless

**How to reproduce:** go inside it and take damage to see

**How it should work:** it should reduce spell damage by 75% and absorb the damage in the same time .After the zone absorbs that amount in description (mine is 430160) it should dissapear

**Database links:** 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/1be4f9e1-7411-4cb0-b0e6-f2bbcc9a172a)

**Comment by Revly** [comment]
> (mine is 430160) it should dissapear

"43016" 🤔

**Comment by Pornoodemon** [comment]
> > (у меня 430160) должно оно исчезнуть
> 
> "43016" 🤔

He clearly didn't test something correctly, I just checked and the damage is reduced by 75%. But the visual bug absolutely needs to be fixed. This interferes with all participants in the battle, including the  DK

**Comment by pro100klass** [comment]
> Не знаю как вы это проверяли, но урон уменьшен на 75%.. А вот АМЗ не исчезает после получения порогового урона - это визуальный баг, который довольно сильно мешает в PvP, из-за того, что зона не исчезает , невозможно понять закончился ли эффект и это нужно исправлять.

А ты точно наносишь нужное количество урона что бы купол пропал?

**Comment by Pornoodemon** [comment]
> А ты точно наносишь необходимое количество урона, чтобы купол пропал?

больше 100к

**Comment by xmrshoot** [comment]
speak english omg

**Comment by pro100klass** [comment]
> > А ты точно наносишь необходимое количество урона, чтобы купол пропал?
> 
> больше 100к

100к поглощенного урона? не может быть

**Comment by pro100klass** [comment]
и да, если бы купол не стоял нужно нанести более 170к урона что бы его уничтожить. мне кажется сейчас так же и работает и репорт можно закрывать

**Comment by xmrshoot** [comment]
@sketish pls mute those russians here if they cant english

**Comment by Pornoodemon** [comment]
> @Sketish pls mute those russians here if they cant english

I described the essence of the problem in English. In russian I answered the question that was asked to me in russian.

**Comment by pro100klass** [comment]
> > и да, если бы купол не выстоял, нужно было бы получить более 170к урона, что бы его уничтожить. мне кажется сейчас так же и работает и отчет можно закрыть
> 
> Каких 170 к урона? Есть пороговый урон в 30-40к в зависимости от АП . После получения этого урона зона пропадает. С его статами этот щит должен поглотить 43 к и пропасть

43к поглощенного урона(который уменьшается на 75%)

**Comment by Pornoodemon** [comment]
> 43к поглощенного урона(который уменьшается на 75%)
Ну типа того но в другой последовательности ) ,весь входящий маг урон уменьшаеться на 75% ,когда отметка поглощенного урона  перевалит за 43 к щит пропадёт

**Comment by UltraNix** [comment]
Just tested and AMZ works okay itself - it absorbs up to 75% of damage.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/cff41f07-55d5-44c6-ac64-aeb446324e34)

Only bug here is what @Pornoodemon described - that'll be fixed.

**Comment by UltraNix** [comment]
About @Pornoodemon bug -  I don't thinks it's a bug.
AMZ is a AoE buff. Let's say that 2 people have it. 1 of these players have already absorbed his max amount ((2 * AP) + 10000) and thus is removed fomr him. But the 2nd should still have it as he haven't absorbed enough damage.
Also, anybody can enter that zone anytime and still have the buff.

**Comment by xmrshoot** [comment]
@UltraNix ye but the visual effect dont dissapear after effect is done

**Comment by UltraNix** [comment]
It will be fixed.
