### ISSUE TITLE
[rogue] [warrior] mb other classes too, Throw

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ability Throw can be used 2-3 times if spam ability as on video

**How to reproduce:**
spam as on video this ability

**How it should work:**
this ability have ~2sec cast 

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Throw
link on rogue ability, warrior have same, I dont test with bow and gun, mb too
https://www.youtube.com/watch?v=fUqGbypj2jk&ab_channel=%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9

**Comment by UltraNix** [comment]
Fixed.
