### ISSUE TITLE
[paladin][item] repetance and bonelink/spell

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5672]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
proc item bonelink fetish dont break repetance

**How to reproduce:**
attack target as on video

**How it should work:**
aoe dmg from item should break repetance, I dont tested with other similar ability, mb too

**Database links:**
https://www.youtube.com/watch?v=Pwqd8r289dQ&ab_channel=%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9
https://wowpedia.fandom.com/wiki/Bone-Link_Fetish

**Comment by UltraNix** [comment]
Fixed.
