### ISSUE TITLE
"Vanish" and "Demon Leap"

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Problem with "Vanish" and "Demon Leap"
Vanish ignores stun and damage from  "Demon Leap"
https://cata-twinhead.twinstar.cz/?spell=54785
Perhaps a similar problem will also  with " Shadowfury " and with  Warrior "Heroic Leap" (not tested)

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/613b27d5-b5dc-415c-87bc-3efbebb50102

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
