### ISSUE TITLE
Violet Citadel unatainable for Horde

### ISSUE THREAD

**Issue by Bakalogatos** [gamefreedomgit/Maelstrom#5675]
**Description:**
The violet citadel should be accessible by both factions but it seems its under the alliance trespassing in Dalaran.

**How to reproduce:**
Just go into Violet Citadel in dalaran as horde

**How it should work:**
Both factions should have access

**Database links:**
https://i.imgur.com/29sQno6.png

**Comment by PanJanuszek** [comment]
cannot reproduce

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/170f7d0a-74d9-4010-8e39-c71fe7c0cee8)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/52f80188-46b6-4015-a126-b2a217725cf5)
