### ISSUE TITLE
HPal - Holy Radiance

### ISSUE THREAD

**Issue by LooBSterStylE** [gamefreedomgit/Maelstrom#5679]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/spell=173379/holy-radiance

**Description:**The spell should change the amount of healing depending on the number of people it affects

**How to reproduce:**
Treat at 5ppl + Treat at 25ppl

**How it should work:**
The spell works similarly to Mind Sear (priest)/Thunder clap (war).

**Database links:**

**Comment by Sketish** [comment]
It has diminishing past 6 targets
