### ISSUE TITLE
Quest Stranglehorn Fever bugged

### ISSUE THREAD

**Issue by chuckda099** [gamefreedomgit/Maelstrom#5680]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest mob for "Stranglehorn" Fever (named Monk) resets before you can fight it for the quest item.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=26597/stranglethorn-fever

**Comment by PanJanuszek** [comment]
cant reproduce
