### ISSUE TITLE
Shadow Orb sp 

### ISSUE THREAD

**Issue by Yarikels666** [gamefreedomgit/Maelstrom#5681]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
increases dot damage by 23% instead of 24% as written in the skill

**How to reproduce:**

**How it should work:**
24%

**Database links:**

**Comment by Sketish** [comment]
Invalid report,.
