### ISSUE TITLE
Priest Class   : Prayer of Mending , Shadowy Apparition , ShadowFiend Pet  Bug

### ISSUE THREAD

**Issue by iamwindruner** [gamefreedomgit/Maelstrom#5682]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Some bug that i found in Priest
Prayer of Mending problem
Shadowy Apparition
And ShadowFiend Pet

So here it is ... As Healer Priest ( Holy or Discipline ) the prayer of mending spell does not work in boss fight like Ultraxion and Madness ... When we are getting Aoe damage it should work and spread among players in raid ... but it does not ... it only works on the tanks  just so cuz of getting Auto attack by the boss while actually it should work on getting any kind damage ( spells and physical attacks )

it also happens when we are on madness of deathwing
when the boss fight starts the whole raid is getting a Massive Aoe damage for wich prayer of mending is one of the best spells that could help the priest to cover the raid ... but it only works when the blistering tentacles come up ... as soon as the blisterings are dead .... prayer of mending does not work anymore

( Also im pretty sure while we were in T11 ... on the magmaw boss fight this happened too )

While you are in madness boss fight whether you are on Shadow Talent or not .... The ShadowFiend pet will bug on 2 sites of boss fight ... when you are on Alexstrasza site ; if you summon your ShadowFiend pet on Mutated Corruption to attack  ...  it  falls down ( or it may go up wich i dont know exaclty where :D )  but it does not attack and gets bugged ....  Also the same issue happens on the Kalegos side ... Wich means you will lose Shadow Orbs and Mana

and last but not least : the Shadowy Apparition talent

while im on the Madness of Deathwing boss fight .... My Shadowy Apparition gets bugged so many times 
it is like when the Shadow Apparition should hit the target and do damage .... Sometimes they just stay and do nothing until they disappear ... or sometimes they just walk to some weird direction and fall off the platform for no good reason

**How it should work:**

Well ... i explained everything

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=41635

https://cata-twinhead.twinstar.cz/?spell=78204

https://cata-twinhead.twinstar.cz/?spell=34433

**Comment by Sketish** [comment]
Next time, 1 bug 1 report - easier to do fixes

**Comment by UltraNix** [comment]
> **Description:**
> 
> Some bug that i found in Priest Prayer of Mending problem Shadowy Apparition And ShadowFiend Pet
> 
> So here it is ... As Healer Priest ( Holy or Discipline ) the prayer of mending spell does not work in boss fight like Ultraxion and Madness ... When we are getting Aoe damage it should work and spread among players in raid ... but it does not ... it only works on the tanks just so cuz of getting Auto attack by the boss while actually it should work on getting any kind damage ( spells and physical attacks )
> 
> it also happens when we are on madness of deathwing when the boss fight starts the whole raid is getting a Massive Aoe damage for wich prayer of mending is one of the best spells that could help the priest to cover the raid ... but it only works when the blistering tentacles come up ... as soon as the blisterings are dead .... prayer of mending does not work anymore

@iamwindruner Need more info on it - what AoE damage on these bosses?
E.g. Ultraxion's AoE (Twilight Instability) as I can see should not trigger procs e.g. from PoM. Can you find retail sources?

**Comment by UltraNix** [comment]
Fixed.
