### ISSUE TITLE
[Priest] Shadowy apparition reviisited

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5687]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Shadowy apparitions are currently targeteable by cc like traps / frost nova / RoF. Abilities like Mage orb / shaman searing are targetting them. You are also currently able to fear them and if they reach their target while feared they don't do any dmg (shouldn't be able to aoe fear them in the first place )
 

**How to reproduce:**

**How it should work:**

Feels like however the shaman totems ( passive ones ) are coded to work is how apparitions should work, only killeable/targeteable by direct dmg spells. No aoe/ground cc/dmg should work on them, unsure about targeted.

Orb close enough to dmg the apparition and no hit.
https://youtu.be/ZinmVuw9EIU?t=317

Apparition walking over ring of frost
https://youtu.be/kF7gxTq_bHU?t=230

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
@UltraNix still eating hunter traps. Also it's weird seeing the immune text on them when cc is attempted, multiple immunes on ring of frost. Actually. Should just "ignore" these effects just as totems do.

**Comment by SimonBpvp** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/d3f115c8-d212-4171-9415-2d7ba981303f)

I think they are supposed to despawn when they die also

**Comment by UltraNix** [comment]
Fixed.
