### ISSUE TITLE
DTR BOOMKIN

### ISSUE THREAD

**Issue by Kult321** [gamefreedomgit/Maelstrom#5688]
Description:
DTR does not work when there is a duplicate spell does not give eclipse power.

How it should work:
I found a video that should work like this, it can be seen at 49 seconds and at 1:50. It's better to watch the video at 0.25
Dragon Soul - Heroic Morchok Heroic 10 man - Boomkin
https://www.youtube.com/watch?v=333Wzpd5ZDA

**Comment by Kult321** [comment]
Description:
DTR does not work when there is a duplicate spell does not give eclipse power.

How it should work:
I found a video that should work like this, it can be seen at 49 seconds and at 1:50. It's better to watch the video at 0.25
Dragon Soul - Heroic Morchok Heroic 10 man - Boomkin
https://www.youtube.com/watch?v=333Wzpd5ZDA

**Comment by shatterqq** [comment]
yea duplicate spells doesnt give eclipse power, but it should

**Comment by Endofree1247** [comment]
Can confirm DTR on booking isn’t working well

**Comment by pizza-with-pineapple** [comment]
Using this logic, should it also duplicate "shadow embrace" https://cata-twinhead.twinstar.cz/?spell=32392
ie when DTR procs on haunt/shadowbolt you gain 2 stacks of shadow embracer instead of 1.
right now it grants 1 stack only even if DTR procs.

**Comment by shatterqq** [comment]
> Using this logic, should it also duplicate "shadow embrace" https://cata-twinhead.twinstar.cz/?spell=32392 ie when DTR procs on haunt/shadowbolt you gain 2 stacks of shadow embracer instead of 1. right now it grants 1 stack only even if DTR procs.

so you can go and report it for wlocks aswell

**Comment by UltraNix** [comment]
@pizza-with-pineapple New report please with details/proofs.

**Comment by Kult321** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/160233807/5df76a30-b88f-46c0-9382-4fdcf4b17ea3)

**Comment by UltraNix** [comment]
Fixed.
