### ISSUE TITLE
yor sahj mana void

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5689]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** void is going too far away , he is away from water

**How to reproduce:** do yor sahj

**How it should work:** should stay closer to the boss and raid

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/b585e9e2-e052-44b3-bbd5-7693e7831649)

**Comment by Revly** [comment]
#5572 Similar

**Comment by xmrshoot** [comment]
![WoWScrnShot_021624_211153](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/32bcfef4-b762-438b-bdbd-840cb898502f)
![WoWScrnShot_021724_144148](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/1e878ae3-85ba-4d00-bd10-5727a5b8732d)
![WoWScrnShot_021724_144259](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/41084f77-5f0b-490b-8a0a-b4d9140d62b7)
 on another raid, look how far its going
