### ISSUE TITLE
Mount achievement count.

### ISSUE THREAD

**Issue by dredanwow** [gamefreedomgit/Maelstrom#5690]
For example, i recieve mount on my alt character, learn it (since i can not trade it to my main), that character recieves mount and mount is shared across all characters, but the TOTAL COUNT of MOUNTS (achievement) on my main just doesn't count that mount, even though i have it in my spellbook. So basically if i learn mount on my alt character, it won't be counted on my main character's mounts achievement. Simply i am unable to progress my mounts count achievement (which gives certain rewards for 50-100-250 mounts etc.)  on my main character if i learn mounts on my alt characters.

**Comment by frostwave942** [comment]
the game can't determine which char is ur main, but those achievements have a kind of internal counter so if uve learned a mount/pet with one char, the list/counter will update when u learn a new mount/pet with other char (ur main).

**Comment by UltraNix** [comment]
Fixed.
