### ISSUE TITLE
Quest bug to summon Nightbane

### ISSUE THREAD

**Issue by rodineee** [gamefreedomgit/Maelstrom#5691]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/tbc/quest=9644/nightbane)
[//]: # (cata-twinhead.twinstar.cz/?quest=9644)

**Description:**
Quest: Nightbane

**How to reproduce:**
Npc quest

**How it should work:**
Npc should give you a Quest Item called "Blackened Urn" to summon Nightbane and finish the quest

**Database links:**

**Comment by Sketish** [comment]
You dont need that past wotlk

**Comment by rodineee** [comment]
what do you mean sir by that? how can I summon him then?

**Comment by rodineee** [comment]
oh I see, i thought i need quest item. thanks a lot
