### ISSUE TITLE
Sorting items in bags causes disconnect

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#5692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Macro or addons(like [Sushisort](https://www.curseforge.com/wow/addons/sushi-sort)) that provide sorting bags causes disconnect. Looks like this actions are recognized as bot or smth

**How to reproduce:**
try to use macro or addon (https://www.curseforge.com/wow/addons/sushi-sort)

**How it should work:**
Disconnect from server should not appear

**Database links:**
https://www.curseforge.com/wow/addons/sushi-sort - one of addons, that dont work on server

**Comment by UltraNix** [comment]
It's an anti-flood protection. Try to sort bag by bag.

**Comment by ETatskyi** [comment]
And what about sorting guldbanks?
Please, share an addon or macro that can do it and doesnt cause disconects. Any retail-tested ways i found doesnt work on server

**Comment by ETatskyi** [comment]
> It's an anti-flood protection. Try to sort bag by bag.

And what about sorting guldbanks?
Please, share an addon or macro that can do it and doesnt cause disconects. Any retail-tested ways i found doesnt work on server
