### ISSUE TITLE
Gurthalak still bugged

### ISSUE THREAD

**Issue by jimusah** [gamefreedomgit/Maelstrom#5693]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Gurthalak tentacle targeting is still bricked.

It almost always prioritises attacking hunter pets, shadowfiends, snakes from snake trap, and even just attacking healers for no reason when you havent even looked at them.

**How to reproduce:**

**How it should work:**
Pls make it attack players instead of pets, and preferably attack your target when it spawns right on top of the guy you are hitting.

**Database links:**

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/5543#issuecomment-1904105583

**Comment by bonfax4** [comment]
@UltraNix  Quick revisit, targets in general are only eligible targets if they're in combat with you as in they're attacking you or you attacked them or theyre healing somebody you attacked, etc. They need to be in "combat"  with you.  Usually for pets this mean it will prob ignore them unless they're attacking you directly or you attacked/cleaved them. I was looking at this again recently and this seems to be the case.

So you shouldn't be seeing gurth randomly attacking snakes or stuff like mirror images/gargoyle if they're not directly on you in most cases. 
Or if it procs and you're somehow out of combat, the 1st person it will lock on is the person you get i n combat with regardless of range until other ppl get in combat with you and become eligible targets. ( the attack nearest mechanic begins with players in combat with you ) .
