### ISSUE TITLE
Heart of Unliving Bugs on Holy Paladins

### ISSUE THREAD

**Issue by iamwindruner** [gamefreedomgit/Maelstrom#5694]
**Description:**
Heart of Unliving Bugs on Holy Paladins

Hello ... I played holy paladin today and i understood the Heart of Unliving does not getting any stack with the Light of Dawn

its a healing spell ... Even the most strong one ... so it should work

**How it should work:**
every healing spell will proc the Heart of Unliving ... Exept the Light of dawn ... You should fix this ... Thanks

**Database links:**

**Comment by Revly** [comment]
I have noticed that many healers' HOT healings are not doing Proc, from Hearexample: the shaman's tides and his HOT does not do Proc, but Healing Rain does. "inexplicable" 🤔

**Comment by UltraNix** [comment]
@Revly Because it should not proc from HoTs, but from applications.

**Comment by Revly** [comment]
> @Revly Because it should not proc from HoT ticks, but from applications.

I found comments and if I was wrong [Heart of Unliving](https://www.wowhead.com/item=77996/heart-of-unliving#comments)
no work Hots

**Comment by UltraNix** [comment]
Fixed.
