### ISSUE TITLE
Gurthalak isnt attacking your main target in arena

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5695]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/0cb48f22-2c6d-41c2-83db-308abfe22424)
![WoWScrnShot_021924_223958](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/741be1f4-121c-4521-a95b-deb8060676ea)

In arena against disc priest and frost mage, it attacked frost mage water elemental instead of the frost mage.

Please fix this annoying dumb bug.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/5543#issuecomment-1904105583
