### ISSUE TITLE
Guardian Of Ancient Kings ( Ret ) VS Shadowfiend ( Shadow Priest ) damage 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5696]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7bedfac7-182f-4a96-9ffb-19f977077be9)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/bdfc4dda-5bcc-443e-8dc9-5335556679c6)

How is Shadowfiend dealing more damage than Guardian btw?

Shadowfiend max damage 10k hits, Guardian 2k max hit?

**How to reproduce:**

**How it should work:**

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=86698

https://cata-twinhead.twinstar.cz/?spell=34433

**Comment by Sketish** [comment]
Invalid report.

**Comment by Renehadox** [comment]
> Invalid report.

How is this invalid report?
Shadowfiend is doing 10k hits
Guardian doing 2k ???
