### ISSUE TITLE
[Paladin] Turn evil Versus Gargoyle 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#5700]
**Description:**
Casting Turn evil directly on Deathknight gargoyle

**How to reproduce:**
1. Cast Turn evil on deathknight gargoyle
2. deathknight gargoyle keeps casting it has no effect on it
https://cdn.discordapp.com/attachments/1154185525935226940/1209679745176969216/image.png?ex=65e7cd0e&is=65d5580e&hm=d9106ec1e6ab28a5fe7aa9085de70b0d0d4387876423b5f5f5fb0f434f5b1f9d&

**How it should work:**
It should be under effect of fear

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=10326

**Comment by UltraNix** [comment]
Fixed.
