### ISSUE TITLE
Party Frames are not showing when you are in a party bug

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5701]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When I invite someone in a party i dont see their heads aka the party frames.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/d8e7a461-985d-475a-b70e-80a359506349)

I dont want raid style frames when im in party because lose control addon will not work.

Also i disabled all of my addons and tried it again but it doesnt work so its a server side issue.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
Similar #4995

**Comment by Renehadox** [comment]
> Similar #4995

This is a server side bug or a client side bug ?

**Comment by Sketish** [comment]
Looks like a client bug

**Comment by Revly** [comment]
> Looks like a client bug

If mi client this in Spanish have bug?
Maybe I tried with client English

**Comment by Renehadox** [comment]
> Looks like a client bug

And what is the fix for this ?

**Comment by Renehadox** [comment]
> Looks like a client bug

Its a server bug caused by some addon, i jsut downloaed a new client and party frames worked, i then copy paste my interface folder from main wow game to new client and they are missing.

**Comment by Renehadox** [comment]
Hello bumping this?

**Comment by UltraNix** [comment]
`Its a server bug caused by some addon, i jsut downloaed a new client and party frames worked, i then copy paste my interface folder from main wow game to new client and they are missing.`
You have your answer - it's one of your addon.
