### ISSUE TITLE
Hour of Twilight - Faceless Shadow Weaver

### ISSUE THREAD

**Issue by Bakalogatos** [gamefreedomgit/Maelstrom#5702]
**Description:**
You have made this particular mob extremely difficult for no reason. For god knows why, this mob uses its skill every 5 seconds, making it almost impossible to clear with a grp of 353 ilvl which is what is supposed to happen. If you look at the youtube video (Could not find a written cooldown) you will clearly see that the seeking shadows spell, happens every 30-40 seconds approximately. Please fix this mistake so that people can happily complete this dungeon.

    Seeking Shadows-Fires a missile towards a random target. When this missile lands, it deals 48750 to 51250 Shadow damage to all enemies within 8 yards of that location.
    Shadow Volley-Inflicts 14625 to 15375 Shadow damage.

**How to reproduce:**
Just play Hour of Twilight

**How it should work:**
Much Much longer cooldown on the mobs spell.

**Database links:**
https://wowpedia.fandom.com/wiki/Faceless_Shadow_Weaver
https://youtu.be/sRtv8P6yUj4?t=826

**Comment by UltraNix** [comment]
Fixed.
