### ISSUE TITLE
DTR BOOMKIN

### ISSUE THREAD

**Issue by Kult321** [gamefreedomgit/Maelstrom#5703]
Description:
DTR does not work when there is a duplicate spell does not give eclipse power.

How it should work:
I found a video that should work like this, it can be seen at 49 seconds and at 1:50. It's better to watch the video at 0.25
Dragon Soul - Heroic Morchok Heroic 10 man - Boomkin
https://www.youtube.com/watch?v=333Wzpd5ZDA 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/160233807/1c126ff5-d9ea-4850-af7f-87bf477cfd5c)
The problem is that there was a message in the discord about solving the DTR BOOMY problem but it still doesn't work
![image](https://github.com/gamefreedomgit/Maelstrom/assets/160233807/ec7c1f42-f8b4-44d8-a6e7-f41425614a67)

**Comment by xmrshoot** [comment]
dude they didnt restart the sever , so the fixees are not live, stop crying and wait for restart

**Comment by UltraNix** [comment]
Not live yet.
