### ISSUE TITLE
anti-magic zone

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#5706]
wtf? Why does the anti-magic zone disappear?https://www.youtube.com/watch?v=hwGCxIK8dOY

**Comment by xmrshoot** [comment]
cuz its fixed now and after its absorb dmg it should dissapear, its not bug

**Comment by pro100klass** [comment]
> потому что сейчас это исправлено, и после поглощения урона оно должно исчезнуть, это не ошибка

there was no damage

**Comment by UltraNix** [comment]
Fixed.
