### ISSUE TITLE
[item] cunning of the cruel

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5708]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
trinket should proc if target not in LoS and out of range

**How to reproduce:**
dot target and move out from los

**How it should work:**
item should proc (shadow bolt) in target even if target not in LoS

**Database links:**
https://wowpedia.fandom.com/wiki/Cunning_of_the_Cruel

Just got the heroic version of this a couple days ago and did some testing with this trinket.
**Shadwbolt Volley is not effected by Line of Sight, and it can proc on an enemy outside the standard 40 yard range.**
It can proc off ticks, giving procs slightly more often to DoT classes.
The proc isn't actually "current target." It actually uses the target of the tick of a spell that procced the trinket, so a shadow priest multi-DoTing will see the proc be based around different targets quite often.
Shadowbolt Volley is shadow damage and is effected by modifiers, giving affliction warlocks and shadow priests much more powerful procs.

On large scale battlegrounds (i.e. 40 Players) this is the most fun item I've ever had. It does not do that much damage, but it proccs fairly often, and it seems to have no range limit, which is just fun to look at. Imagine a shadowbolt volley just disappearing **in some random direction to hit some poor target that's not even in sight or way out of range.**

from wowheal comment, later will find video(if exists), now doesnt have time

**Comment by SimonBpvp** [comment]
I know retails videos exist of cunning sending 100+ yard shadow bolts, it was pretty disgusting on blizzlike tbh.

**Comment by bonfax4** [comment]
https://youtu.be/HRxzq-AR2-4?t=1m9s
