### ISSUE TITLE
priest bufff dont work on raid

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5709]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
if u use stamina and shadow resist u have to buff the player one by one if the priest is different faction

**How to reproduce:** go to an alliance priest in a raid full of horde and use buffs

**How it should work:** you should buff entire raid with one cast of buffs , not one by one , we are not in WOTLK

**Database links:**

**Comment by UltraNix** [comment]
Just tested with Power Word: Fortitude and with alliance priest/horde rogue. Targeting priest, targeting rogue or targeting none - buff is always put on both chars.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/257aa99b-ac7c-4f4a-b5f9-5312ce61d6a0)

**Comment by xmrshoot** [comment]
idk on my raid didnt worked , the priest had to do it manually on all players one by one

**Comment by xmrshoot** [comment]
@UltraNix try with shadow buff too , shadow resistance
