### ISSUE TITLE
[DTR][Frost Mage] Legendary staff on Frost mage does not work as intended?

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#5715]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Legendary staff on Frost mage does not work as intended
It should copy abilites but does not.
Works good on Fire mage.
Does not work at all with Frost Mage making frost shit especially since you guys fixed Deep Freeze
( https://github.com/gamefreedomgit/Maelstrom/issues/5531 ) 

(not related to bug but imma rant cuz this guy who made issue above destroyed frost on this server xd)

I did not know it was a bug and ive been playing frost since firelands but fixing Deep Freeze was mistake cuz now Frost is unplayable PvE wise and does little damage compared to other mages making me not enjoy game anymore  : v . 
Before fix you could compete against Fire mages or other dpses (not the best ones) on some bosses especially if u had gear making frost not super good and not super bad option like it is now to play with it was good/okay.
But now its total meh in pve xd Pleasseeeee bring back old Frost 0.0 let me enjoy the game lol 
Bug literally made frost playable

**How to reproduce:**
Fight Target dummy or any boss as any DTR spec then try Frost mage

**How it should work:**
DTR Should copy Frost mage abilites and it does not

**Database links:**
10min fight with Frost and 11 min fight with Fire on Madness. 
Testing with friends about an hour ago
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/4af0e917-7538-4888-b44f-3d3041dc2ce0)

**Comment by Nenze** [comment]
Math Casts of "Wrath of Tarecgosa"
Fire Mage 105 casts
vs
Frost Mage 12 Casts 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/39f8110a-dafd-43e6-b321-fa6643501ab8)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/7e7e4e9a-36f1-4d0a-b9a2-434b92ec9e60)

and here
Aliz 3min 30 sec as Frost 2 casts of wrath 
vs 2min 30sec as Fire with 10 casts of wrath
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/8cabdd5e-0b01-4b65-b97a-12bcbc6f1a5e)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/9524783f-dd3b-4f8a-b1d3-a7a7ea1047e7)

**Comment by Nenze** [comment]
Someone said in whitemane dc that wrath of tarecgosa in dmg meter is for DoTs only and to see real dmg you should look at the casts vs hits thingy tho it looks wacky here anyway so i might be wrong with it (or maybe its details being bad?)
If there is someone with more knowledge who can check it that would be cool
Ill try to post with diffrent dmg meter addons later
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/267638b1-cabd-4ac7-9588-630a95644e6c)

**Comment by Sketish** [comment]
If DTR proc from casting spell like frostbolt or icelance it's damage is added to same spell in recount/details.
If you want to check procs rate then use any combat scrolling text it will display dmg done by copied spells.
DTR proc is set for class not spec so doubt is not working for some spells.

"Before fix you could compete against Fire mages or other dpses (not the best ones) on some bosses especially if u had gear making frost not super good and not super bad option like it is now to play with it was good/okay."

Frost wasnt a pve spec in cata. So if other specs scale better you will fall off as frost

**Comment by pizza-with-pineapple** [comment]
as mentioned above,
Wrath of Tarecgosa is only for the DoTs copied.
The direct damage spells copied are shown as the name of the spell itself.
So if the staff copies frostbolt, it will show its damage on dmg-meters under the name of the spell "frostbolt"
