### ISSUE TITLE
Glyph of arcane power is not working

### ISSUE THREAD

**Issue by vamasa123** [gamefreedomgit/Maelstrom#5717]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
glyph of arcane power is not working

**How to reproduce:**

**How it should work:**
 you use mana shield,blink or mirror image then you use arcane power .It is supposed to reset them but it is not working nothing happens

**Database links:**

**Comment by UltraNix** [comment]
`Description: While Arcane Power is active the global cooldown of your Blink, Mana Shield, and Mirror Image is reduced to zero.`
First use Arcane Power, then use Blink, Mana Shield or Mirror Image.
Glyph do not reset gcd on these.
