### ISSUE TITLE
Error en las misiones 

### ISSUE THREAD

**Issue by kamyterry** [gamefreedomgit/Maelstrom#5718]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Hola, Kor el Inamovible de (Infralar) no me deja tomar sus misiones, me sale el icono de mision pero tambien me sale la opcion de ataque y por lo tanto no puedo tomar la mision, Grax.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
english omg
