### ISSUE TITLE
Boomie: Eclipse does not reset CD on Nature's Grace if proc'd with DTR

### ISSUE THREAD

**Issue by shadowpope** [gamefreedomgit/Maelstrom#5719]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Eclipse does not refresh Nature's Grace cooldown when gaining Eclipse, if eclipse was gained from a DTR proc.

I have uploaded a screenshot of my combat log with this happening.
I go into Solar Eclipse with Starfire from DTR (2 in a row my own + DTR) - I then apply Insect Swarm but I don't get Nature's Grace buff.

Also - this is a fairly recent issue, I didn't experience this last week.

**How to reproduce:**

Get into eclipse with DTR. Use either insect swarm or moonfire to proc Nature's grace.

**How it should work:**

Nature's grace cooldown should be reset.

**Database links:**
![WoWScrnShot_022724_164915](https://github.com/gamefreedomgit/Maelstrom/assets/148686039/e72ec915-5532-407b-9ca3-346c95a65d58)

https://cata-twinhead.twinstar.cz/?spell=61346

**Comment by UltraNix** [comment]
Fixed.
