### ISSUE TITLE
Holy Shock healing while 2 are in duel

### ISSUE THREAD

**Issue by Citizn1991** [gamefreedomgit/Maelstrom#5720]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Holy shock spell can heal others while they duel

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
