### ISSUE TITLE
bone link fetish trinket

### ISSUE THREAD

**Issue by alilector** [gamefreedomgit/Maelstrom#5721]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
bone link fetish do less damage than it said in its description

**How to reproduce:**

**How it should work:**
doing damage equal to its description
![bone](https://github.com/gamefreedomgit/Maelstrom/assets/142694416/5df1bdeb-8bec-4525-9cb1-5add7a5e53e6)

**Database links:**

**Comment by Sketish** [comment]
Its physical so its reduced by bosses armor
