### ISSUE TITLE
Yor sahj purple and tranquility

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#5722]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** using tranq in purple phase dint add stacks of Deep corruption

**How to reproduce:**
Use tranq during purple

**How it should work:**
IT s should add stacks of debuff

**Database links:**

**Comment by bonfax4** [comment]
Here's a compiled list on how spells should behave : 
[Source](https://www.mmo-champion.com/threads/1037455-Yor-sahj-and-purple/page2)

Druid
Effloresence - NO STACKS
Lifebloom - 1 stack per cast.
Rejuvenation - 1 stack on initial application
Swiftment - 1 stack on the person swiftmended.
Tranquility - 1 stack per tick (i.e. a raid killer)
Wild Growth - 1 stack for each person hit by Wild Growth

Shaman
Chain Heal - 1 stack on initial hit only (although I'd like a bit more testing!)
Healing Rain - 1 stack upon entering. If you leave and re-enter, you gain another stack.
Healing Stream Totem - NO STACKS
Riptide - 1 stack on initial application
Spirit Link - NO STACKS

Paladin
Beacon of Light - NO STACKS
Holy Radiance - 1 stack for initial application (i.e. if it hits 4 people, 4 people get 1 stack).
Word of Glory - NO STACKS

Priest
Atonement - 1 stack
Divine Hymn - 1 stack per tick (i.e. will wipe your raid)
Echo of Light (Holy Mastery) - NO STACKS
Holy Word: Sanctuary - 1 stack upon entering. If you leave and re-enter, you gain another stack.
Holy Word: Serenity - 1 stack
Lightwell - 1 stack per buff gain (i.e. when the person clicks)
Penance - 1 stack for the whole channeled cast (i.e. not 1 per tick)
Power Word: Shield - 1 stack (even when glyphed)
Prayer of Healing - 1 stack
Prayer of Mending - NO STACKS
Renew - 1 stack on initial application

Other Abilities
Deathknight Deathstrike - ??
Druid Leader of the Pack - no stacks
Hunter Chimera Shot - no stacks
Priest Vampiric Embrace - no stacks
Rogue Recuperate - no stacks
Warlock Healthstones - no stacks

**Comment by xmrshoot** [comment]
ye , also if u site with atonement =0 stacks , its should add 1 stack per cast of smite
