### ISSUE TITLE
Killing Lieutenants of Flame does not count towards [Ready for Raiding II] achievement. 

### ISSUE THREAD

**Issue by Daddyvictum** [gamefreedomgit/Maelstrom#5723]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
So far, it counted only Cinderweb Queen, but it did not count the other three. 
At first, I thought it's related to me not attacking he mob first (instead allowing the ancient do it),but today I ensured I did it first today, and it still didn't count. 

**How to reproduce:**
No particular steps. Pick up the quest from Choluna, go there, kill it and it doesn't give credit. 

**How it should work:**
Give credit per kill. 

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/a43b578c-22ea-407a-9693-344f122e23b8)

can't reproduce. you can't be hit remember by any spell of them
