### ISSUE TITLE
DTR proc does not give Impending Doom effect

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5726]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
similar to the boomkin fix that was done recently.
DTR proc does not give Impending Doom effect when it procs.

https://cata-twinhead.twinstar.cz/?spell=85108

**How to reproduce:**

**How it should work:**
DTR procs should be able to give impending doom effect.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=85108

**Comment by UltraNix** [comment]
Fixed.
