### ISSUE TITLE
DTR proc does not apply Burning Embers effect.

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5727]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Similar to the boomkin fix that was done recently.
DTR proc does not apply "burning embers" 

https://cata-twinhead.twinstar.cz/?spell=85112

**How to reproduce:**

**How it should work:**
DTR proc should apply burning embers.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=85112

**Comment by UltraNix** [comment]
Fixed.
