### ISSUE TITLE
DTR proc does not apply Soul Leech effect

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5728]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
similar to the boomkin fix that was done recently.
DTR proc does not apply Soul Leech effect.

https://cata-twinhead.twinstar.cz/?spell=30295

**How to reproduce:**

**How it should work:**
DTR proc should apply Soul Leech.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=30295

**Comment by UltraNix** [comment]
Fixed.
