### ISSUE TITLE
Quest : cold hearted

### ISSUE THREAD

**Issue by filiopirgaki** [gamefreedomgit/Maelstrom#5729]
https://www.wowhead.com/wotlk/quest=12856/cold-hearted

**Description:**   the bug is that there is none Brunnhildar  prisoner to resque and this is a chain quest to complete so i can be friendly with them SON OF THE HODIR to buy things from their quartermaster 

**How to reproduce:**

**How it should work:**
be there brunnhildar prisoners on ice to resque by taking them with the proto-drake

**Database links:**

**Comment by MirNelthDB** [comment]
I also can confirm that this quest is bug.

At the start of the quest, it is possible to remove "Lok' lira's Bargain" and appear at the entrance of "Dum Niffelen". The chains of the proto-dakes are not visible. After restarting the server and taking the quest, "Brunnhildar prisoners" are visible, sometimes missing the ice blocks around them. Even if I take three prisoners and on the way back to "Brunnhildar village" I don't get an inscription that the archdeacon is free. When I returned to the village, the prisoners did not fall from the archetype, and accordingly, he did not report anything to me. If I abandon the quest and try to repeat it, the prisoners are missing.

How should work:
https://www.youtube.com/watch?v=ahxXhW5YDgI

Sourse:
https://www.wowhead.com/quest=12856/cold-hearted

**Comment by PanJanuszek** [comment]
fixed 05.03.2024

**Comment by Furiianda** [comment]
This is still bugged, after a player turns in the quest all the mobs remain alive at the drop-off point and need to be manually killed by a GM to respawn back in their ice cubes at the pickup location in Dun Niffelem.
