### ISSUE TITLE
Argent Tournament Bugged Quest " A valiant of Stormwind " you cannot progress further

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5731]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I finished the quest which required 15 aspirant seals and i choose " A valiant of Stormwind " quest i accepted the quest and finished it but it doesn't give me any further quests with the stormwind faction.

**How to reproduce:**

**How it should work:**

**Database links:**

https://wowpedia.fandom.com/wiki/A_Valiant_Of_Stormwind

https://wowpedia.fandom.com/wiki/The_Valiant%27s_Charge_(Alliance)

**Comment by Renehadox** [comment]
@Waroxx-QA can you put this medium because i am farming some PvE content, achievements and stuff, Thank you.

**Comment by PanJanuszek** [comment]
fixed 26.03.2024
