### ISSUE TITLE
Quest bug 

### ISSUE THREAD

**Issue by leeroyJenkings** [gamefreedomgit/Maelstrom#5735]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Ques from darme Evniki Kapsalis not work

**How to reproduce:** she can't do complete the quest

**How it should work:** let complete the quest and show the bag to buy items 

**Database links:** https://www.wowhead.com/wotlk/es/npc=34885/dama-evniki-kapsalis

**Comment by PanJanuszek** [comment]
more data required

**Comment by PanJanuszek** [comment]
After 7 days without info, i will close ticket
