### ISSUE TITLE
Adds in Heroic Warmaster 

### ISSUE THREAD

**Issue by NonSun0755** [gamefreedomgit/Maelstrom#5736]
**Description:**
When shaman or druid balance push the melee adds outside the ship, these can´t return and these stay there doing nothing.
we can kill these adds without taking damage from above the ship.

**Comment by bonfax4** [comment]
Don't think any add besides the sapper should be able to be pushed at all to begin with.

**Comment by bonfax4** [comment]
Can confirm here :
- https://youtu.be/f7zKAO2nEH4?t=1m29s sapper pushed back 
- https://youtu.be/f7zKAO2nEH4?t=2m13s typhoon hits a stunned sapper and both melee adds and no pushbacks

**Comment by UltraNix** [comment]
Fixed.
