### ISSUE TITLE
Faerie Fire (Feral) (Cat) not providing Clear casting buff 

### ISSUE THREAD

**Issue by justabugreport** [gamefreedomgit/Maelstrom#5737]
**Description:**
Druid's spell
Faerie Fire (Feral) (Cat)
It should have a chance to proc Clear Casting and it used to do so.
First time I noticed it doesn't do it anymore is around 10 days ago.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=16857

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/20efb874-b2b3-498e-9b53-66f2fc332620)
Works okay.

**Comment by justabugreport** [comment]
Did u implement it? Did you test without hitting a dummy I just did like 60-70 times ff and got 0 procs.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by justabugreport** [comment]
You tested on cataclysm realm right?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UltraNix** [comment]
Of course I did test it on cata realm.

**Comment by justabugreport** [comment]
I don't know I did test it yesterday night again with over 100 faerie fires in cat form and it never proced. Also had my friend feral try and test too he also wasn't able to get any proc as well.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by justabugreport** [comment]
Now it works well after the server restart.
Thanks,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
