### ISSUE TITLE
Bashi'ir Landing stasis chambers don't respawn

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5738]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The stasis chambers at Bash'ir Landing don't respawn after being opened.  So far it's been twenty-four hours.

**How to reproduce:**
Open a chamber, wait.

**How it should work:**
Chambers should respawn within a reasonable time frame, no more than ten minutes.

**Database links:**
https://www.wowhead.com/spell=35725/opening-ethereum-stasis-chamber#used-by-item
https://warcraft.wiki.gg/wiki/Ethereum_Stasis_Chamber
https://www.wowhead.com/quest=10974/stasis-chambers-of-bashir

**Comment by PanJanuszek** [comment]
More data required, quest? gameobject name? item id?

**Comment by PanJanuszek** [comment]
fixed 07.03.2024
