### ISSUE TITLE
Reply-Code Alpha can't be used to start quest

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5739]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I looted Reply-Code Alpha from Algalon and couldn't start the quest due to error message that I didn't meet requirements.  I was told that this was because I looted a copy keyed for the opposite faction.

**How to reproduce:**

**How it should work:**
Should be able to use to start quest https://www.wowhead.com/quest=13631/all-is-well-that-ends-well

**Database links:**
https://www.wowhead.com/item=46052/reply-code-alpha

**Comment by PanJanuszek** [comment]
Fixed after update
