### ISSUE TITLE
Warlock soul link damaging the warlock

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5741]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Sometimes the soul link damage to the warlock pet also damage the warlock

**How to reproduce:**

idk, take damage

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/14b330da-875f-43b0-897a-ba7ef3bc973a)

maybe because of dtr

**How it should work:**

soul link should not damage the warlock

**Database links:**

[Soul Link](http://cata-shoot.tauri.hu/?spell=19028)

**Comment by UltraNix** [comment]
@Polynomix Do you know the source of damage that triggered these Soul Links?

**Comment by UltraNix** [comment]
Fixed.
