### ISSUE TITLE
Manaforge Ultris Etherium Prison chambers don't respawn

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Etherium prison chambers aren't respawning after being accessed.  So far they have been down for almost 36 hours.

**How to reproduce:**

**How it should work:**
Chambers should be respawning in a reasonable time frame, no more than ten minutes.

**Database links:**
https://www.wowhead.com/item=29460/ethereum-prison-key
https://www.wowhead.com/quest=10973/a-thousand-worlds
https://wowpedia.fandom.com/wiki/Ethereum_Prison
https://www.wowhead.com/npc=20520/ethereum-prisoner

**Comment by PanJanuszek** [comment]
More data required, quest? gameobject name? item id?

**Comment by PanJanuszek** [comment]
fixed 07.03.2024

**Comment by Daethalion** [comment]
Issue is still ongoing.
