### ISSUE TITLE
Assault on Bash'ir Landing world event is broken

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5745]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The periodic world event Assault on Bash'ir Landing doesn't play, even though the trigger condition is being reported by an NPC at Vortex Summit.  See https://imgur.com/a/D7rjDBL for details.

**How to reproduce:**
Observe.

**How it should work:**
Every 2-3 hours a raid event is supposed to take place which, if completed successfully, will spawn a temporary merchant who offers rare items.

**Database links:**
https://www.wowhead.com/quest=11119/assault-on-bashir-landing
https://www.wowhead.com/npc=23245/aether-tech-master

**Comment by PanJanuszek** [comment]
We do not have data to fix it.
