### ISSUE TITLE
Rogues Deck Qutest item dosnt work or something

### ISSUE THREAD

**Issue by wickedlike** [gamefreedomgit/Maelstrom#5746]
**Description:**
Rogues deck should give me a repeatable quest thats used to farm darkmoon faire rep

**How to reproduce:**
Get Rogues deck, try using it to get the quest.

**How it should work:**
Should give you a complated quest thats grands rep

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=12517#wh-comments

Would be nice if this gets fixed before the darkmoon ends.

**Comment by PanJanuszek** [comment]
What's the problem??

Got deck, right clicked, got quest, summoned gnome, handled, got rep + item

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/98702d8f-7445-4a65-bf71-754b24fb6be6)

**Comment by PanJanuszek** [comment]
Added 10x items got 10x quests...

**Comment by wickedlike** [comment]
It appears that I can only start the quest on my warrior who has inscription as a prof, but i dont actually play on him, while all my alts that i use seem to not meet the requarment. After checking up with GM's they confirmed that i should not need that prof for me to start the quest. So i dont know what im missing, 

![WoWScrnShot_030524_140318](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/a934f384-c69d-4b06-9e8f-674c479a25ea)
![WoWScrnShot_030524_140528](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/049ae173-54a0-424c-a927-ed721d7bcd03)

**Comment by wickedlike** [comment]
Only when i get inscription (1/75) can i start the quest.

**Comment by PanJanuszek** [comment]
yes, quest requires inscription.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/30409482-da7a-4f13-a263-64487ec97ba0)

**Comment by PanJanuszek** [comment]
so for me... not an issue until you prove that having inscription it doesnt work
