### ISSUE TITLE
Disconnected when the vehicle UI appears doing the quest "Tailgunner!" in Uldum

### ISSUE THREAD

**Issue by Bhahlou** [gamefreedomgit/Maelstrom#5747]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Systematically disconnected during the quest "Tailgunner!" In Uldum. As soon as the vehicule UI appears, game crashes.

**How to reproduce:**
Start the quest, and wait :D

**How it should work:**
Should not crash I guess 

**Database links:**
Quest 27905

**Comment by PanJanuszek** [comment]
What is your wow client language?
Can you remove cache from client and try again?

**Comment by PanJanuszek** [comment]
@SallyWhitemane Client related issue only spanish&russian clients has it. Maybe mini version???
