### ISSUE TITLE
 [Enrage] Furry warrior talent

### ISSUE THREAD

**Issue by Kabashpowa** [gamefreedomgit/Maelstrom#5748]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Enrage talent in furry warrior tree should increase the dmg of the warrior for fix amount + %oh the mastery. For example with 13.43 Mastery it should be 17%. At the moment it increases the dmg always 10%fix. Even though the talent says 17% in the talent tree.

**How to reproduce:**
Make furry spec and and mele hit the traget. there is 9% change to proc Enrage.

**How it should work:**
 [Mastery] Unshackled Fury increases the benefit of Enrage. 

**Database links:**

**Comment by bonfax4** [comment]
From what I'm reading om Simcraft, it doesn't work the way you're describing. 

Enrage gets affected by mastery in a multiplicative way, as in enrage % amount * (1 + mastery %/100 ). with 17% mastery fully talented you'd have 10% *1.17 which is a about 11.7% dmg increase really. 

It could still be bugged but the numbers wouldn't be as big as you think they are.

**Comment by UltraNix** [comment]
Let's take e.g. Death Wish.
Normally, it give you +20% damage increase.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a27096aa-2656-465e-b39d-aa7fee3f4ad6)
With 1000 mastery, I get extra +42% to Death Wish effect.
1,42 * 0,2 = 0,284 ~ 28% damage increase from Death Wish.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/08b336e1-8f83-45f2-bd27-2af78a119816)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/7bcec846-ce54-4189-9233-c838508fd75e)
With 2000 mastery, I get extra +73% to Death Wish effect.
1,73 * 0,2 = 0,346 ~34% damage increase from Death Wish.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/e28a1a24-5c3d-471e-9efb-b372b783736c)

I see nothing bugged here.

**Comment by Kabashpowa** [comment]
Death Wish works fine, but the ''enrage'' talent in fury spec increases the dmg by 10% fix, it should be 10% + the % of the whole mastery.

**Comment by bonfax4** [comment]
There"s a cata wowhead now, should be hard to link stuff now. 

https://www.wowhead.com/cata/spell=13046/enrage
