### ISSUE TITLE
PRIEST SHADOWFIEND BUG

### ISSUE THREAD

**Issue by dexxus0408** [gamefreedomgit/Maelstrom#5749]
**Description:**
I'm playing with a priest and when use the spell shadowfiend, the game crash

**How to reproduce:**
occurs when using the shadowfiend in fights

**How it should work:**
Not giving crash error

**Database links:**
https://www.wowhead.com/spell=34433/shadowfiend
![error](https://github.com/gamefreedomgit/Maelstrom/assets/162356703/c0bdda97-1c45-45e4-aa7e-c943db536ac5)

**Comment by Sketish** [comment]
Must be some addon issue not in game stuff
