### ISSUE TITLE
Krolmir, Hammer of Storms ID: 13010

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5750]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When I am raiding Krolomir and moving with him on the spot, nothing happened. 
0/1 Krolomir's Fate Discovered not count. 

In addition i cant jump from Krolomir and have to logout to run normal. Cinematic missing, conversation with Thorim missing too. I cant normaly end this quest in the Thunderfall.

**How it should work:**
https://www.youtube.com/watch?v=7aTSFJ5xspA

https://wow.zamimg.com/uploads/screenshots/normal/169818-krolmir-hammer-of-storms.jpg

**Comment by PanJanuszek** [comment]
fixed 19.03.2024

**Comment by WhitemaneChronus** [comment]
NPC disappears right after player transforms into a giant (talking to thorim)
quest is completed but player cannot turn it in.
