### ISSUE TITLE
DTR delay

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5752]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

its not really a bug just pointing out that there was a half second delay from DTR on retail, video:

https://youtu.be/mv-zwPPPijE?feature=shared&t=54

I don't know if you want to add that or just leave it how it is with no delay

**Comment by Sketish** [comment]
It's set to 250 ms on our server, wont be changed

**Comment by Polynomix** [comment]
more like 25ms

**Comment by SimonBpvp** [comment]
> the only delay i'm observing on this server is the travel time (~25-50ms)
yeah there feels like 0 delay, maybe they accidentally set it to 25ms instead of 250ms
