### ISSUE TITLE
Proc Trinket Snapshotting

### ISSUE THREAD

**Issue by wickedlike** [gamefreedomgit/Maelstrom#5754]
**Description:**
I somehow managed to snapshot  [Wartorn Cunning of the Cruel] and i get the showdow bolt proc without having it on.

**How to reproduce:**
I dont know how to reproduce, i just logged my mage and swapped from pvp set to pve, started attacking dummies and noticed it. Qued for a RHOT and even after death it still procs shadow bolts. 

**How it should work:**
I should not have a chance for a shadowbolt proc without the trinket on. Its as if the game thinks im with it on and even with Wartorn it still procs in pve.

![WoWScrnShot_030724_132335](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/6236b262-3646-4361-8abf-444d79697a0c)
![WoWScrnShot_030724_132350](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/5213325e-6e3a-47b8-9494-5baddbbc6567)
![WoWScrnShot_030724_132400](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/c3a39d09-81e2-4661-a7a4-4c63c1825f8b)
then i qued rhot
![WoWScrnShot_030724_134613](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/bea28c17-912a-46ea-b531-d948f3cd189d)
![WoWScrnShot_030724_134642](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/2a0b72ff-6b76-4986-91cc-eca9d8555d69)
![WoWScrnShot_030724_134643](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/b8877598-a45e-40df-84a2-5884d64b9ce1)
![WoWScrnShot_030724_134644](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/b4b5ab4d-c79e-41f1-b942-1b6cd4d51748)
![WoWScrnShot_030724_134709](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/96b617e8-190a-4558-a5f5-950aeb29613d)
![WoWScrnShot_030724_132856](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/5e37ed47-5741-4b57-b448-a7ca92d9c5ed)

**Comment by wickedlike** [comment]
tried to replicate it today and it worked again, just swapped from pve to pvp and back to pve and started attacking the dummies
![WoWScrnShot_030824_204821](https://github.com/gamefreedomgit/Maelstrom/assets/156576564/a8b99e64-8740-447a-82e3-5e9fe91c614e)

**Comment by UltraNix** [comment]
Fixed.
