### ISSUE TITLE
 Healing Rain

### ISSUE THREAD

**Issue by Scroll2024** [gamefreedomgit/Maelstrom#5756]
Healing rain | Deep damage
[Healing Downpour](https://www.wowhead.com/spell=73920 ) + [Deep Damage](https://www.wowhead.com/spell=105171 )
When using [Healing Shower] (https://www.wowhead.com/spell=73920 ) with active debuff
[Deep damage] https://www.wowhead.com/spell=105171 ) continues to give a stack for each tick. Shouldn't keep giving a stack.
[Healing Downpour] (https://www.wowhead.com/spell=73920 ) - 1 stack when a player enters a puddle. If you get out of the puddle and go in again - 1 more stack. ONE stack should be given to each player who is within the radius of the puddle.

https://www.wowhead.com/spell=105171
According to the comment on this spell, it follows that it does not work correctly.

**Comment by Sketish** [comment]
Need video from retail to confrm  that, watched currently about 10 video and rshamans never used rain during purple debuff

**Comment by Polynomix** [comment]
currently on the server, it does give only 1 stack as long as you do not reenter

**Comment by Sketish** [comment]
Not a bug
