### ISSUE TITLE
Reins of the Grand Black War Mammoth

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5757]
**Description:**

Maybe it is not important but it can be useful in the future.
I found a "Retail" Video where this [Mount](https://www.wowhead.com/wotlk/item=43959/reins-of-the-grand-black-war-mammoth) is exclusive that can carry companions and is Exempt to combat, with other mounts, you can't but with this one you can.

**How to reproduce:**
![mamut](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/c17b3394-b0c3-46c2-8288-ff8d96e4580e)

In the SS the Mouse cannot be shown when the Mount Button is shown
Currently, you cannot take companions who are in Combat

**How it should work:**

I should be able to carry companions who are in Combat as shown in the [Video](https://www.youtube.com/watch?v=WpxgVTHgSsQ)

**Database links:**

https://www.youtube.com/watch?v=WpxgVTHgSsQ
https://www.wowhead.com/wotlk/item=43959/reins-of-the-grand-black-war-mammoth
https://cata-twinhead.twinstar.cz/?item=43959

**Comment by Waroxx-QA** [comment]
Only Cataclysm videos from 12 years ago approximately, can be taken as proof
