### ISSUE TITLE
Bug talent Molten Core

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#5758]
https://cata-twinhead.twinstar.cz/?spell=47247

**Description:**
Molten Core is being consumed when activated during the cast of Incinerate unmodified, when it should not be consumed.

**How to reproduce:**
Cast Incinerate while you have Immolate active on your target and wait for Molten Core to proc while casting Incinerate and you will be able to see a charge of Molten Core consumed during the casting of Incinerate

**How it should work:**
Molten Core won't be consumed if it procs during unmodified Incinerate cast.

retail minute 2:49
https://youtu.be/f__LGzHItyU?list=PLD47BDAA8A49C5F1E&t=166

**Comment by UltraNix** [comment]
Fixed.
