### ISSUE TITLE
[Mage] [Talent] Arcane Potency

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5759]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Increases spell critical chance by 15%

**How to reproduce:**
Observe spell critical chance before buff
Proc buff
Still the same %

**How it should work:**
Should increase by 7/15% depending on 1/2 talent

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=57531

**Comment by UltraNix** [comment]
@djesic You mean critical chance showed in character sheet UI?

**Comment by UltraNix** [comment]
That talent does not modify your critical strike in general, but applies only to some spells (in that case to your damaging spellks). Not a bug. Talent works okay.
