### ISSUE TITLE
DC every report in chat

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#5761]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
So some players are just being a spam, troll, or very rude with languages needed to be censored. When I report a player for being those above mentioned, I get DC.

**How to reproduce:**
1. Right click player name on chat window.
2. Select `Report Player For`.
3. Select any report for option.
4. Accept/Proceed
5. Gets DC

**How it should work:**

**Database links:**

**Comment by Hermeleen** [comment]
Yes it is annyoing. I would like to report names. Because consider me retro, but i dont think name like "swallowmycum" should be allowed.

**Comment by UltraNix** [comment]
#3130
