### ISSUE TITLE
Mob/Boss Unkillable Hyper Regen.

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#5763]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I am a rogue, sometimes when I approach a mob while being on stealth the mob notices me. If the mob notices me and yet it did not attack/aggro, therefor not breaking my stealth, it still makes me in combat state.  When this happens, the mob becomes unkillable, it regens so fast. It's like a mob that just got "aggro-reset" upon, hyper regen and always avoid, but in this case just the hyper regen.

**How to reproduce:**

1. Play as rogue.
2. Stealth.
3. Get near mob.
- if it notices you but did not attack, that is when the hyper regen kicks-in.
4. Attack mob (cannot kill mob since hyper regen)

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@chrisdomaub-dev Can you give us examples of such mobs? Or maybe even record it?

**Comment by SimonBpvp** [comment]
was this in twilight highlands by any chance?

**Comment by SimonBpvp** [comment]
#2364 
this was the same issue i was having then

**Comment by UltraNix** [comment]
Fixed.
