### ISSUE TITLE
Quest disconnect

### ISSUE THREAD

**Issue by B-Jimmy-B** [gamefreedomgit/Maelstrom#5768]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After taking the Quest "Tailgunner!" in Uldum.
Just before the plane takes off I get disconnected

**How to reproduce:**
Start the quest anew and same result.

**How it should work:**
I should fly and do the quest in air

**Database links:**

**Comment by Waroxx-QA** [comment]
#5747
