### ISSUE TITLE
Birds of a Feather

### ISSUE THREAD

**Issue by Maciairek** [gamefreedomgit/Maelstrom#5769]
**Description:**
During the quest "Birds of a Feather" player cannot use "Empty Birdcage" to catch Female Kaliri Hatchling which is blocking the quest.

**How to reproduce:**
1. Travel to the Hellfire Peninsula.
2. Navigate to Falcon Watch.
3. Accept above-mentioned quest from Falconer Drenna Riverwind.
4. Navigate to location shown on map ("Den of Haal'esh").
5. Find "Female Kaliri Hatchling".
6. Use quest item "Empty Birdcage" on above-mentioned npc.
7. Observe Female Kaliri Hatchling not catching and player not obtaining "Caged Female Kaliri Hatchling" required for quest to be finished.

**How it should work:**
As shown in linked video:
Player should find Kaliri Nest and interact it.
Player should obtain "Caged Female Kaliri Hatchling" quest item after using "Empty Birdcage" when "Female Kaliri Hatchling" is targeted.

**Database links:**
https://www.wowhead.com/quest=9397/birds-of-a-feather
https://cata-twinhead.twinstar.cz/?quest=9397
https://www.youtube.com/watch?v=qilrLprvwCs

**Comment by PanJanuszek** [comment]
fixed 11.03.2024
