### ISSUE TITLE
Silvermoon Blacksmith Trainer

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#5773]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The blacksmith trainer in Silvermoon City is bugged. I cannot learn/train the profession there.

**How to reproduce:**
1. Interact with blacksmith trainer

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Provide any in game screenshots

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/db57c372-3a67-454b-a27d-34bdccbc1ec9)
Do you have already blacksmithing skill?

**Comment by chrisdomaub-dev** [comment]
yes just like that screenshot above.
No I am trying to learn the blacksmithing profession but cannot.

**Comment by UltraNix** [comment]
Fixed.
