### ISSUE TITLE
Echo of Light (Zero)

### ISSUE THREAD

**Issue by Anderzrez** [gamefreedomgit/Maelstrom#5774]
https://wowpedia.fandom.com/wiki/Mastery:_Echo_of_Light

Echo of Light on my holy priest shows that the amount Echo of Light is healing is zero.

Cast any heals and it reproduces the same issue, always staying at zero.

Echo of Light is based off of your mastery and should do an extra "X" amount of healing based on your mastery amount.

**Database links:**

**Comment by Sketish** [comment]
Provide combat logs

**Comment by UltraNix** [comment]
Fixed.
