### ISSUE TITLE
Indoor mount Bug

### ISSUE THREAD

**Issue by Sylwania** [gamefreedomgit/Maelstrom#5775]
**Description:**
Indroor check dismount not working well, after battleground finish, while you are mounted and teleported back.
Its kinda abuse and hiding vendors with large mounts.
https://prnt.sc/b2SGJnxVnE0K - Screenshot

**How it should work:**
Should dismount player when battleground ends or leave by himself or kicked out.
Should check indoor and dismount automatically.

**Comment by UltraNix** [comment]
Fixed.
