### ISSUE TITLE
Shaman ghost wolf form speed doesnt work properly.

### ISSUE THREAD

**Issue by Destromulti** [gamefreedomgit/Maelstrom#5777]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

http://cata-shoot.tauri.hu/?spell=16287
**Description:**
shaman ghost wolf speed doesnt increase when using talented ghost wolf

**How to reproduce:**

**How it should work:**
its using speed 30% when it should be 45%

**Database links:**

**Comment by Sketish** [comment]
Provide any proofs its not working

**Comment by Destromulti** [comment]
![WoWScrnShot_031224_095325](https://github.com/gamefreedomgit/Maelstrom/assets/163101599/4b495000-e45f-416f-8236-af6515a0139b)
![Uploading WoWScrnShot_031224_095331.jpg…]()

**Comment by Destromulti** [comment]
![WoWScrnShot_031224_095331](https://github.com/gamefreedomgit/Maelstrom/assets/163101599/617b7eb6-242d-4463-8675-838fedb1fdf7)

**Comment by Polynomix** [comment]
it increases your movement speed when not in wolf, wolf speed is still 30%
