### ISSUE TITLE
You still can't buy DTR while having 2300 rating in 2v2

### ISSUE THREAD

**Issue by aymenqtx** [gamefreedomgit/Maelstrom#5778]
**Description:**
Title

**How to reproduce:**
Title

**How it should work:**
So basically since the 02/22/2024, you can buy all heroic (wartorn/replica) items with 2300 rating in 2v2, which wasn't the case before (only restricted to 3s and soloq). Proof: 
![proof](https://github.com/gamefreedomgit/Maelstrom/assets/91341316/ea31b503-0a2c-4ab2-b811-a20b6decdfb4)

Basically if I go to the vendor right now while having 2.4 cr in 2s, i still can't buy it:
![PROOF1](https://github.com/gamefreedomgit/Maelstrom/assets/91341316/f635143f-cc6f-4543-b1a3-161bd3964885)
![proof3](https://github.com/gamefreedomgit/Maelstrom/assets/91341316/9257faf9-27dd-4074-ab0e-0db0051b61c3)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
