### ISSUE TITLE
 Cunning of the Cruel - Accessory

### ISSUE THREAD

**Issue by StropM16** [gamefreedomgit/Maelstrom#5779]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The crit multiplier for Priests in the Darkness branch does not work correctly when the “Cunning of the Cruel” item is triggered. When choosing the branch - Darkness, the Priest is given the passive ability "Energy of Darkness" - Increases critical damage from dark magic spells by 100%, which is the benefit of the Accessory "Cunning of the Cruel".
![image](https://github.com/gamefreedomgit/Maelstrom/assets/163300396/2022a3bc-9243-4eb0-8bb9-3a081fba826c)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/163300396/113626b6-a0c6-466d-a901-00f7e3ef0955)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/163300396/c4ef8579-f368-4bae-8920-d384d9d04fd8)

**How to reproduce:**
Should increase critical damage with Dark magic from the proc of the item “Cunning of the Cruel” for Priests in the Darkness branch, due to the passive ability “Energy of Darkness” by +100%. I also checked on the Mage the critical proc of the item “Cunning of the Cruel” deals the correct damage +100% damage when the Accessory is critically triggered, in contrast to the ShP, which deals the base +50% when the item is critically triggered.

**How it should work:**
Should increase critical damage with Dark magic from the proc of the item “Cunning of the Cruel” for Priests in the Darkness branch, due to the passive ability “Energy of Darkness” by +100%. I also checked on the Mage the critical proc of the item “Cunning of the Cruel” deals the correct damage +100% damage when the Accessory is critically triggered, in contrast to the ShP, which deals the base +50% when the item is critically triggered.

**Database links:**

**Comment by StropM16** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/163300396/316238dc-5b77-4e63-bd28-aae12d335366)

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c4dd260c-b6f9-4b12-8e83-aa7e6b685614)

More evidence is needed here since this passive ability most likely only applies to the priest's darkness spells

**Comment by bonfax4** [comment]
Looking at simc code, this is accurate behaviour. Proc items scale with crit dmg increase effects but not with **bonus** crit dmg  increases. Thjs means Warlocks and Mages get the 199.5%  ( mages an warlocks have an innate 33% crit dmg increase by default, 150%*1.33)  on magical effects from items, and hybrids do not. 

This also explains why these items scaled with meta gem crit dmg increase, not sure if they do here tho.

**Comment by UltraNix** [comment]
Shadow Power talent increase damage/critical damage of your spells (priest) only.
