### ISSUE TITLE
Npc doesn't offer a quest

### ISSUE THREAD

**Issue by CataclysmEnjoyer** [gamefreedomgit/Maelstrom#5781]
**Description:**
Npc named Teemo in Azshara doesn't offer a starting quest of a quest chain.

**How it should work:**
She should offer a starting quest.

**Database links:**
https://wowpedia.fandom.com/wiki/Azshara_Blues
https://wowpedia.fandom.com/wiki/Teemo

**Comment by PanJanuszek** [comment]
You didn't follow previous chain:
https://wowpedia.fandom.com/wiki/Azshara_storyline

Azsharite Experiment Number Two -> A Hello to Arms -> Azshara Blues
