### ISSUE TITLE
Jormungar color change

### ISSUE THREAD

**Issue by PootisBird17** [gamefreedomgit/Maelstrom#5787]
All the tameable Jormungars have the same default purple-ish color, even those who were supposed to have a color change since 4.0 patch.
Here are some examples of supposedly-color-swapped Jormungars who kept the default skin, the place where to find them and the color they're supposed to be :

Rattlebore, Dragonblight, black [https://www.wowhead.com/npc=26360/rattlebore](url)
Ice Heart Jormungar Feeder, Dragonblight, green [https://www.wowhead.com/npc=26358/ice-heart-jormungar-feeder](url) (even if he's purple on the picture)
Ice Heart Jormungar Spawn, Dragonblight, white [https://www.wowhead.com/npc=26359/ice-heart-jormungar-spawn](url)
Ravenous Jormungar, Storm Peaks, blue [https://www.wowhead.com/npc=29605/ravenous-jormungar](url)

[https://www.wow-petopia.com/guides/transformed.html](url)

**Comment by Sketish** [comment]
So what is a bug ?

**Comment by PootisBird17** [comment]
It's more of something you forgot to add, but it's still a game issue.

**Comment by UltraNix** [comment]
Fixed.
