### ISSUE TITLE
Warlock Pets using abilities while they are feared

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5788]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Didnt you guys said this was fixed before?

I got pet stun while the pet was feared.

Its critical bug especially in arena.

![warlockbug](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/7696e4f8-2f0e-4939-a32f-b21f01b2122e)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
Oh my god.....You banished a pet after throwing an ax.The ax flies to the target for some time after use.

**Comment by Pornoodemon** [comment]
Ability cannot be used while a fear

https://github.com/gamefreedomgit/Maelstrom/assets/133828891/6ffe216b-9347-48ed-b995-4618c0cf386f

**Comment by Pornoodemon** [comment]
> Its critical bug especially in arena.

This is another critical mistake in your head.

**Comment by pizza-with-pineapple** [comment]
the pet stun, axe toss, has a travel time so even though per is feared the stun will occur a few moments later.
besides, warlock have a ability to cleanse all CC effects from their pet.

this is not a bug.

**Comment by Renehadox** [comment]
> > Its critical bug especially in arena.
> 
> This is another critical mistake in your head.

Says the guy who made 3 replies with 5-6 edit to his posts each ? :D

What is the travel time of the axe? 5 seconds? as you can see fear is 1,3 seconds left out of 8 seconds and i had 1 second left of the stun.

**Comment by Pornoodemon** [comment]
.

Just try to check the nonsense that you write. And then delete this topic.

**Comment by Renehadox** [comment]
> the pet stun, axe toss, has a travel time so even though pet is feared the stun will occur a few moments later. besides, warlock have a ability to cleanse all CC effects from their pet.
> 
> this is not a bug.

what is the travel time of the axe toss?
