### ISSUE TITLE
[shaman] hex

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5790]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
player under effect hex can use some abilities 

**How to reproduce:**
use hex on player and try use some abilities example rogue vanish/shaman link

**How it should work:**
under effect hex player should not could use any abilities (only trinket/human race)

**Database links:**
https://wowpedia.fandom.com/wiki/Hex

https://www.twitch.tv/videos/2090819536 01:11:13 time

**Comment by Sketish** [comment]
What skill did he used? cant see on twitch

**Comment by mipanka** [comment]
https://wowpedia.fandom.com/wiki/Spirit_Link_Totem

**Comment by mipanka** [comment]
looked bad 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/030c2c53-eb5f-4e27-8155-fe1cb4a181b9)
 after link

**Comment by mipanka** [comment]
> looked bad ![image](https://private-user-images.githubusercontent.com/127995853/313853737-030c2c53-eb5f-4e27-8155-fe1cb4a181b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDEyMjksIm5iZiI6MTcxMDgwMDkyOSwicGF0aCI6Ii8xMjc5OTU4NTMvMzEzODUzNzM3LTAzMGMyYzUzLWViNWYtNGUyNy04MTU1LWZlMWNiNGExODFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQyMjI4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGIyMDM3MTNmNmNlMjg0NmRjOTU5NjJiMWNmMWUyODZhZDliODY2ZTM2MmZiYzg0MWIzMDg2ZDlkOTJmNmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NIVPNo_RsI5n33FBW89A-n5vkIuYjMug785kKzJymTw) before link

**Comment by mipanka** [comment]
Dont need, I tested vanish and can use under hex as stealth too on my rogue

**Comment by UltraNix** [comment]
As I can see, Vanish has special attribute that ignores caster auras, such as Hex.

**Comment by UltraNix** [comment]
Fixed.
