### ISSUE TITLE
Kor el Inamovible 

### ISSUE THREAD

**Issue by ironmaidem** [gamefreedomgit/Maelstrom#5791]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the mission of Kor the Immovable this bug won't let me do it, it's even disappeared from my list of missions, please help I already donated 30 euros and I plan to continue donating but I need help with this issue, thanks in advance

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Invalid report
