### ISSUE TITLE
Paralysis

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5792]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/ff441642-2049-4ab1-bc86-33a2e04b51be)

when i crit mind blast on a death knight that has death's advance it doesnt quite work 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/118687e6-ca94-48f8-8fcc-bfa055d76f6f)

**How to reproduce:**
https://clips.twitch.tv/StrangeSincerePancakeHeyGirl-Btn1_fqpj8hUgrCc

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@SimonBpvp And what is the bug here?

**Comment by SimonBpvp** [comment]
> @SimonBpvp And what is the bug here? Paralysis reduces movement by 100% and Death's Advance negates such effects.

it works as a root any other time so I would think it's supposed to root. Death's Advance doesn't prevent frost nova or entangling roots for example. Unless Paralysis is maybe coded different from all other roots

**Comment by bonfax4** [comment]
They are coded different despite being a root mechanic. It says it applies an aura that decreases speed by 100 for paralysis. Could be blizzlike but not sure.

https://web.archive.org/web/20120902053933/http://www.wowhead.com/spell=87194

https://www.wowhead.com/cata/spell=87194/paralysis

**Comment by bonfax4** [comment]
Maybe done this way to share Dr with roots ( controlled roots ? ), similar to how bad manner is a disorient with stun mechanic ?

https://www.wowhead.com/cata/spell=90337/bad-manner

**Comment by bonfax4** [comment]
https://web.archive.org/web/20120127095103/https://www.wowhead.com/spell=87195/paralysis#comments 

Comments here seem to confirm it's a 100% slow

**Comment by SimonBpvp** [comment]
ok good find
