### ISSUE TITLE
[mage] [talent] cauterize

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5793]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
sometime doesnt proc

**How to reproduce:**
idk 100% but have log from arena where talent doesnt proc

**How it should work:**
as in tooltip 

**Database links:**
https://wowpedia.fandom.com/wiki/Cauterize

screen:
![WoWScrnShot_031724_233351](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/113f8189-0baa-42be-949f-1efa732ec00d)
![WoWScrnShot_031724_233354](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/d80f0626-2577-433d-a996-7db90ab043dc)
if need translate I can help

**Comment by UltraNix** [comment]
@mipanka Yes, please - translate.

**Comment by PanJanuszek** [comment]
No feedback, no info, next time please translate
