### ISSUE TITLE
Kor el inamovible

### ISSUE THREAD

**Issue by ironmaidem** [gamefreedomgit/Maelstrom#5794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
la mision de infralar KOr el inamovible no me funciona no me deja hacerla ni completarla ni nada 
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Please make a new report in English.
