### ISSUE TITLE
fear ward

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5795]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when I fear this shaman he has fear ward on but it doesn't immune the fear

**How to reproduce:**
https://clips.twitch.tv/BitterAggressiveLampDoritosChip-J5oa2yKyUi9ATYU0

**How it should work:**
fear ward should immune the fear

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=6346

**Comment by Pornoodemon** [comment]
No. It should dispel  fear when the totem pulsates and not give immunity to fear

**Comment by Pornoodemon** [comment]
This is not the effect of fear, but the effect of horror.

**Comment by UltraNix** [comment]
Cannot reproduce it.
@SimonBpvp Happened only once?

**Comment by SimonBpvp** [comment]
> This is not the effect of fear, but the effect of horrify .Or did I understand something wrong from the video?

psychic scream, priest aoe fear 
https://cata-twinhead.twinstar.cz/?spell=8122

**Comment by Pornoodemon** [comment]
Yes you are right .
You should also check diminishing returns with fear effects. This may also not work correctly

**Comment by SimonBpvp** [comment]
> Cannot reproduce it. @SimonBpvp Happened only once?

it happened twice in that one game

**Comment by UltraNix** [comment]
@SimonBpvp Can you test it on duel?

**Comment by SimonBpvp** [comment]
I probably can't

**Comment by UltraNix** [comment]
Hmm, Fear Ward has not been consumed by Psychic Scream?

**Comment by UltraNix** [comment]
Fixed.
