### ISSUE TITLE
dampening

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5798]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
question: is dampening working the way it's supposed to with shields?

https://www.twitch.tv/videos/2095686997?t=1h26m17s

in this clip at 50% damp the shaman dies with stoneclaw buff up (how can u die with a shield ?)

**Comment by mipanka** [comment]
When dampening 50%, shields working only on 50% dmg, when 90% on 10%

**Comment by mipanka** [comment]
My opinion is that this is unfair for classes with shields, since the overall amount of damage is not reduced; it would be more correct if the volume of the shields was reduced from dampening.

**Comment by mipanka** [comment]
Disc on 50%+ dampening > all other heals

**Comment by SimonBpvp** [comment]
> My opinion is that this is unfair for classes with shields, since the overall amount of damage is not reduced; it would be more correct if the volume of the shields was reduced from dampening.

Yes I don’t know if it’s fair or unfair but I agree it’s more correct to have the volume of the shield reduced instead of how it is now. Cause a shield is supposed to be an absorb, not a x% dmg reduce.

**Comment by UltraNix** [comment]
It affects only healing done. Shields are not affected by Dampening right now.

**Comment by pizza-with-pineapple** [comment]
> Disc on 50%+ dampening > all other heals

it shouldnt be like that though,. dampening should effect heals+absorbs.

**Comment by UltraNix** [comment]
Fixed.
