### ISSUE TITLE
Bugged achievement: The Incredible Hulk

### ISSUE THREAD

**Issue by beldy69** [gamefreedomgit/Maelstrom#5800]
GM said that the problem might be that Valkyrie is not spreading Volatile Infection. So the Valkyrie cant kill Scourge Hulk....
Dungeon: Utgarde Pinnacle
Boss: Svala Sorrowgrave (Valkyrie)
Please fix it asap :))) ty

 HIGH PRIORITY PLEASE NEED MY MOUNT :)))
Beldy

**Comment by WhitemaneIsa** [comment]
Hey, until this is fixed please open a ticket containing "Isa told me to send this ticket, "The Incredible Hulk" Achievement doesn't work, I need it added" and I will add it to you ingame.

**Comment by beldy69** [comment]
Hey, i opened a ticket. Waiting for a response. ^^

**Comment by PanJanuszek** [comment]
fixed 08.04.2024, server has to restart
