### ISSUE TITLE
[Quest] [WOTLK] Reclusive Runemaster

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Maelstrom#5801]
**Description:**
The quest cannot be completed because the Quest Mob Dregmar Runebrand cannot be killed as it isn't attackable.

**How to reproduce:**
Questmob is not attackable.

**How it should work:**
Quest mob should be killable.

**Database links:**
https://www.wowhead.com/wotlk/quest=12150/reclusive-runemaster

**Comment by PanJanuszek** [comment]
fixed 25.03.2024
