### ISSUE TITLE
Banish and Demonic Empowerment

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5804]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?spell=710
https://cata-twinhead.twinstar.cz/?spell=47193
When a fel hunter is Banished, using Demonic Empowerment does not dispel Banish.
Banish is a magical effect that must be dispelled by  Demonic Empowerment 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/c966d323-f902-4ed4-b1f7-63b3cdbfed51)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/51d62898-85f8-4ddb-9b51-487824a26396)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment]
Banish does give you every school immunity while it's up and empowerment is physical. Same way you can't dispel a banish with class dispells besides mass dispel which bypasses immunities.

**Comment by bonfax4** [comment]
Actually, looking at wowhead  felhunyer empowerment bypasses immunities as well.

https://www.wowhead.com/cata/spell=54509/demonic-empowerment

**Comment by Pornoodemon** [comment]
> Actually, looking at wowhead felhunter empowerment bypasses immunities as well.
> 
> https://www.wowhead.com/cata/spell=54509/demonic-empowerment
> 
> Edit: needs to be tested for sure. Noticed now mass dispel has a bypass invulnerability flag, and banish makes you invulnerable. I'll test on classic wotlk soon and post back.

I'm not sure that it worked for the lich king as well as for the cataclysm

**Comment by bonfax4** [comment]
If the flags are correct on the cata/wotlk classic wowhead they should work the same. Im about to test on classic

**Comment by bonfax4** [comment]
Nope, it doesn't remove banish

**Comment by Pornoodemon** [comment]
Before the cataclysm, Banish himself worked differently. They could drive out a druid in the form of a tree and a warlock in metamorphosis. Which, combined with fear, gave endless cc. This changed during the cataclysm. And the demonic enhancement was created to remove various control effects and other things from the pet. In general, my opinion is that this should remove the banish. Just for fun, you can go check how it works on twin.

**Comment by bonfax4** [comment]
yeah but you're also assuming the change was done to banish and not the forms themselves. From what I'm reading, after 4.0.1 neither run evil or holy wrath also worked on metamorphosis. Sounds more like they changed those temporary forms to not change your "creature type". Not to say I'm correct, but everything else points out to you being wrong. You might need a retail video for this.

![056b887752edb85d60df39a1f17f17b7](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/0364c342-5c99-45fe-8b29-e794c2ed27a5)

![76266e27c12960da5d877d9ef4024265](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/8419b63d-52f3-4b66-ad68-980cf5dcde71)

**Comment by Pornoodemon** [comment]
Yes, I myself understand that this will reach a dead end, so it’s probably better to leave it as it is

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/16911730/b8dd318e-d141-4669-af59-0d58566ccf31

doesn't work in cata classic either btw.
