### ISSUE TITLE
portal to xylems tower doesnt appear in azshara

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Maelstrom#5805]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
there is no portal to get back to xylems tower after you talk to azuregos

![image](https://github.com/gamefreedomgit/Maelstrom/assets/159703358/7f1f91fc-1811-4ceb-875d-9a3cf9ddd81e)

**How it should work:**

there should be a portal to "Xylem's retreat" 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/159703358/59722966-ac16-4c55-96c3-d2465739118f)

**Comment by qqdbpp** [comment]
the missing portal is the one at 27.11, 40.87 next to sanath lim-yo ID 50299 and it should teleport you to the portal at 22.44, 43.57 next to nyrill 36374

**Comment by PanJanuszek** [comment]
fixed 08.04.2024, server restart required
