### ISSUE TITLE
Higher Learning - Missing books - achiev

### ISSUE THREAD

**Issue by Wick3dmind** [gamefreedomgit/Maelstrom#5808]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?achievement=1956

**Description:**
I have been chasing books for Higher learning for about a month or so with at least 3 daily checkups for spawn, however only these spawn : https://prnt.sc/Vy7Gnugkjz1H   and other random books.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#5538
