### ISSUE TITLE
Blood DKs/ death strike in all 3 specs got stealth nerfed????

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#5809]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Okay so im at an absolute loss here. heres the thing, i know blood dks are frownded upon in pvp. i get it. there useless in 3v3 and are banned in solo q for GOOD REASON that i toally agree with. If i do arena solo q i use unholy anyways which is best. thats all fine. how ever there a tank and they have there place in BGs like wsg and alterac valley, and even defending bases. and i get people are annoyed when they run into them but Op classes are like racial slurs, either all of them are okay or none of them are. im am 10000% percent certain you guys have done something to make blood dks weaker. I would duel people with my alt DK in vicious gear as a joke, cuz i know its OP and im literally taking more damage now in my FULL geared best in slot pvp gear all tier 2 over 5k resil blood dk, then i was with my vicious gear dk vs the same people who have the same gear. not to mention im getting my death strike, and i notice this happening with frost AND unholy aswell, parried and dodge countless times where as every other attack hits nearly every time when ur hit rating and exp are capped. this makes no sence at all. not only that dancing rune weapon isnt working right either. its suppost to attack for 50% of your strikes. and instead its only doing 20% which is completely wrong. the 20% is the parry chance increase you get, not the damage it deals. resillience seems to be making me take more damage somehow when its over 5k. please fix what ever this is. as i said its all ok or none of it is. if your gonna nerf something becuase people complain then you got a long list of things to fix with rogues, hunters, mages, ect. ect. this dosnt make any sence at all. 

**How to reproduce:**
idk, get a GM or a player to attack me. im taking more damage on my max gear dk then i uste to on my vicous one vs people who are less geared. if they nerfed the class then cleary i would get hit even harder on my alt. 

**How it should work:**
Idk, but i do know i shouldnt be getting hit this hard. let alone getting every death strike parried or dodged reguarldess of what spec i am. 

**Database links:**
seriously.....no way to measure something like this. if its a stealth nerf of some kind. idk.

**Comment by frostwave942** [comment]
seems like more to be a complaint about how the class works in this patch than a bug report.

**Comment by UltraNix** [comment]
Invalid report. Follow the template.

**Comment by Hoofjob-Instinctz** [comment]
alright. ill show some evidence, itll be hard but ill think of something

**Comment by Hoofjob-Instinctz** [comment]
> seems like more to be a complaint about how the class works in this patch than a bug report.

naw dude, i was using my vicious dk vs people with cataclysmic gear and before what ever updates, i was taking less damage on him then on my main dk who has full cata. im elite rank which ig et with uhnoly and ive got tier 2 weapon, and im 5,4k resil. it makes 0 sence
