### ISSUE TITLE
Engineering  Enchant  glove 

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5810]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Over the past few days, a bug has appeared that was previously fixed.
These glove upgrades do not begin their cooldown after leaving combat. CD is reset only after relog.
What makes it problematic to use for example on BG
https://cata-twinhead.twinstar.cz/?spell=82180
https://cata-twinhead.twinstar.cz/?spell=82201
https://cata-twinhead.twinstar.cz/?spell=82200

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
