### ISSUE TITLE
drain soul doesnt snap shot

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5814]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
warlock spell drain soul

**How to reproduce:**
cast it then have target heal up and compare dmg

**How it should work:**
it should snapshot

**Database links:**
[1120](https://cata-twinhead.twinstar.cz/?spell=1120)

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/1c0ef117-90f9-40e0-a7e9-4895fe4c8bfb)
I see no differences.

**Comment by dididadadududada** [comment]
sorry i'll be more clear. drain soul does double damage when the target is at or below 25% health. if the target drops to or below 25% health and you cast drain soul you should see the double damage regardless if the target heals up over 25% health or not. i hope it makes sense and thank you for getting back

**Comment by UltraNix** [comment]
Fixed.
