### ISSUE TITLE
[arena] eye on arena / crystalls

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5818]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Eyes on arena should be as debuff

**How to reproduce:**
Take eye

**How it should work:**
Should as debuff, and cannot be canceled

**Database links:**
Idk how link, its eye for track stealth or invisible players

**Comment by Accidentlol** [comment]
Retail proof of this?

**Comment by UltraNix** [comment]
Fixed.
