### ISSUE TITLE
sello del campeon

### ISSUE THREAD

**Issue by muerto12** [gamefreedomgit/Maelstrom#5819]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
  There is a bug in the champion H test dungeons by not giving the champion's seal on each boss

**How to reproduce:**
does not give the Champion's Seal

**How it should work:**
should give each boss in heroic mode the "champion's seal 

**Database links:**
https://www.wowhead.com/es/currency=241/sello-de-campe%C3%B3n#contained-in-object
![Captura de pantalla 2024-03-28 075503](https://github.com/gamefreedomgit/Maelstrom/assets/165277671/1be4fa65-2e66-4145-a5a2-67326748638b)
![Captura de pantalla 2024-03-28 075535](https://github.com/gamefreedomgit/Maelstrom/assets/165277671/d5c1933e-e586-43dd-a0f2-193a9c7f87c3)

**Comment by muerto12** [comment]
> **Description:** hay un bug en las mazmorra prueba del campeón H al no dar sello del campeón en cada jefe
> 
> **How to reproduce:** no da el Sello del campeón
> 
> **How it should work:** debería dar en cada jefe en modo heroico el "sello del campeón "
> 
> **Database links:** https://www.wowhead.com/es/currency=241/sello-de-campe%C3%B3n#contained-in-object
> 
> ![WoWScrnShot_032824_073029](https://private-user-images.githubusercontent.com/165277671/317714227-8f31d345-4bac-4ce9-9e6e-9fe0753f829a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjcwMjIsIm5iZiI6MTcxMTYyNjcyMiwicGF0aCI6Ii8xNjUyNzc2NzEvMzE3NzE0MjI3LThmMzFkMzQ1LTRiYWMtNGNlOS05ZTZlLTlmZTA3NTNmODI5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMTUyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzAxZGEwZDE4MGVjY2M2YmRlOWI4MzRhODM1ZmRmMWViNjdkZWFhOGQ1NTc0YjgzZDJlYWY0Mzk0NjJjYzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOwP8nHvtyIoMb4V6lehpVrs5qpcaILI8_OGhJvvBfM) ![WoWScrnShot_032824_073034](https://private-user-images.githubusercontent.com/165277671/317714330-06d526a4-d8d5-40e4-b59a-d61c1dfc6616.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjcwMjMsIm5iZiI6MTcxMTYyNjcyMywicGF0aCI6Ii8xNjUyNzc2NzEvMzE3NzE0MzMwLTA2ZDUyNmE0LWQ4ZDUtNDBlNC1iNTlhLWQ2MWMxZGZjNjYxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMTUyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmM0MmQ3Mzg3YWNhZDI5M2Y3MzFlMDNkNjZhMmFmODQzNjczNjQ0YTM5OTE1ODY2ODA5NzQ0OTg0YTc4ZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.98nZB4s_9H4cAR_TM2HxWY3f4cA5XMwzkqNu1i7tgnA)

**Comment by PanJanuszek** [comment]
Please write ticket in English

**Comment by muerto12** [comment]
> Por favor escribe el billete en inglés.

I already modified it

**Comment by muerto12** [comment]
> Por favor escribe el billete en inglés.

I already modified it

**Comment by UltraNix** [comment]
Fixed.
