### ISSUE TITLE
Bug achivement point for glory of the hero in Server Maelstrom

### ISSUE THREAD

**Issue by zaldrayn** [gamefreedomgit/Maelstrom#5822]
[//]: # (https://www.wowhead.com/achievement=1871/experienced-drake-rider:)
[//]: # (https://ibb.co/rZJcsbq
https://ibb.co/F5MWXWP
https://ibb.co/t8dXmtx)
[//]: # (https://cata-twinhead.twinstar.cz/?achievement=2136)

**Achievement Bug:**

**We are 3 people on emerald drake doesnt count:**

**Kill last boss from occulus whole party using same drake for make achivement  Experienced drake raider:**

**Database links:**
https://youtu.be/GlByM6DWY2U?si=eqcNC6hYu2AnBlna

**Comment by Waroxx-QA** [comment]
![Screenshot_2024-04-01-02-57-00-73_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/268fd4b1-c4d1-419d-9ec1-63bc4e260ea6)
