### ISSUE TITLE
Hadronox Denied and The Incredible Hulk achievement bug

### ISSUE THREAD

**Issue by PootisBird17** [gamefreedomgit/Maelstrom#5824]
The achievements "Hadronox Denied" and "The Incredible Hulk" are currently uncompletable. For Hadronox, we cannot damage him while he's climbing up the tunnel, because he evades all the time. And the Ritual of Swords of Svala Sorrowgrave doesn't deal any damage at the end.

Links : [https://www.wowhead.com/achievement=1297/hadronox-denied](url)
           [https://www.wowhead.com/achievement=2043/the-incredible-hulk](url)

**Comment by PanJanuszek** [comment]
part with [The Incredible Hulk] is done

**Comment by PanJanuszek** [comment]
cannot reproduce part with Hadronox
