### ISSUE TITLE
Cannot accept quest nor complete quest in deepholm.

### ISSUE THREAD

**Issue by Lunitics** [gamefreedomgit/Maelstrom#5829]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Stuck on quest Entrenched in deepholm does not let me complete quest at Kor the Immovable. Also cannot accept quest from Therazane The stone mother.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=26436/entrenched
https://www.wowhead.com/faction=1171/therazane

**Comment by Waroxx-QA** [comment]
Impossible, you should've missed something

**Comment by GM-Nightmaree** [comment]
Pressing C > reputations > therezane > untick at war
 should fix the problem for you

**Comment by Lunitics** [comment]
Ty it worked 🙂


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
