### ISSUE TITLE
holy priest can use some spells without the required talent

### ISSUE THREAD

**Issue by DowoDowoDowo** [gamefreedomgit/Maelstrom#5830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

if you spec into chakra but not into revelations you can still use holy word serenity or holy word sanctify provided you have a macro for them

![Sin títulod](https://github.com/gamefreedomgit/Maelstrom/assets/165705629/55ffbca4-f623-4684-a537-a6c6492d0a15)

![Sin título](https://github.com/gamefreedomgit/Maelstrom/assets/165705629/cf50b2d9-c9ea-445e-83d9-f47413720911)

**Comment by UltraNix** [comment]
Fixed.
