### ISSUE TITLE
[Hunter][Survival][Talent] Improved Serpent Sting

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#5831]
**Description:**

Improved Serpent Sting (2/2) does 30% of 6 sec duration if used Multi Shot with Serpent Spread talent (1/2)
(I assume with 2/2 it does 30% of 9 sec duration - haven't tested.)

**How to reproduce:**
Use Multi Shot on a single target or multi-targets and see the Instant Serpent Sting damage.

Using Serpent Sting (SpellID 1978) on Dummy - Improved Serpent Sting does 3,396 for me.
Using Multi Shot on Dummy - Improved Serpent does 1,234 for me.

**Both** Improved Serpent Sting damage should be the same if used with Multi Shot or not.

**How it should work:**
According to what I know it should do 30% of the full duration 15 seconds.

More explaination:

On this video at 4:16, 4:26 - Hunter is using Multi Shot and the Improved Serpent Sting hits **MORE** than the Multi Shot Itself.
https://www.youtube.com/watch?v=H0zLfEopSLs

On other hand, Whitemane - https://ibb.co/WW2s5Pc 
Multi : ISS
43493:6809 - Mine.
43924:58494 - Video.

Another video at 4:05 and 4:08.
https://www.youtube.com/watch?v=UtKhYbx1jrc

Multi Shot : ISS
a. 71850 : 86150
b/ 99337 : 93071

Conclusion:
Improved Serpent Sting by Multi Shot should do instant 30% damage of the full duration (15 seconds).
and not of the 6 seconds or 9 seconds as work in Whitemane.

@bonfax4 you have discord, I want to speak with you about something.

**Comment by UltraNix** [comment]
Fixed.
