### ISSUE TITLE
Mini Tyreal summoned halfway into ground

### ISSUE THREAD

**Issue by TheAndreski** [gamefreedomgit/Maelstrom#5832]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I bought the Mini Tyreal pet from the Whitemane Store and everytime and everywhere I summon him he is always halfway sticking out of the ground.

**How to reproduce:**
Get the pet and summon it and you will see that he sticks halfway out of the ground no matter where you summon him.

**How it should work:**
Mini Tyreal should be flying a few feet in the air at all times. This make me hesitant to buy more flying pets from the Whitemane Store, if this can't be fixed then how should I go about getting a refund on Whitemane Store?

**Database links:**
https://www.wowhead.com/npc=29089/mini-tyrael#screenshots:id=536313

![WoWScrnShot_040124_144548](https://github.com/gamefreedomgit/Maelstrom/assets/139296998/71899c10-b673-4e37-a8be-d873df405cee)

**Comment by PanJanuszek** [comment]
fix soon

**Comment by PanJanuszek** [comment]
fixed 08.04.2024
