### ISSUE TITLE
Dampening is not reducing the effectiveness of absorbs/shields.

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5834]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Dampening in arena is not reducing the effect of absorbs/shields.
It is only reducing the effect of Heals.

This bug makes disc priests extremely overpowered in arena (especially in 2v2). As all other healers get reduced healing from dampening while priests absorbs are not effected at all.
2v2 teams such as Disc+Feral or Disc+Rogue, know this bug and intentionally pillar-hug for 20mins and refuse to play the game until late dampening starts. 
So other non-priest healers effectiveness is reduced by major percent while they still have full absorbs/shields active and then they leave pillar and go for kill.
The absorbs/shields are strengthened even more with Pain Suppression, while other healers (paladin/shaman/druid) lose effectiveness on their Heals. 
Leaving only 2 viable options for 2v2, either play with disc priest (feral+disc or rogue+disc) or play double DPS.

**How to reproduce:**

**How it should work:**
Dampening should effect Heals and Absorbs/shields.

**Database links:**

**Comment by Revly** [comment]
#5798

**Comment by UltraNix** [comment]
Already fixed.
