### ISSUE TITLE
(Quest) Corrupted Blackwood permanent agro AND "FRIENDLY" after finishing Cleans The Afflicted quest

### ISSUE THREAD

**Issue by mafiaknight** [gamefreedomgit/Maelstrom#5835]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Corrupted Blackwood Furbolg permanently agroed after turning green/friendly as part of a quest. Other Furbolg agroed at the time also broke the code that confines them to their area.
the Furbolg in question followed me out of the zone to Blackfathom Camp, and then all the way back up to Lor'danel, and then out to sea.
I eventually killed the red/hostile Furbolg, but the green/hostile one was "friendly" and immortal...
It chased me for half an hour

**How to reproduce:**
The second quest in the chain to "cure" corruption from the Blackwood Furbolg in Twilight Vale (Darkshore/Kalimdor).
(https://www.wowhead.com/quest=13545/cleansing-the-afflicted)
I used a lvl30 darkelf druid (boomkin spec) and ran the quest chain while leveling herbalism.
I was fighting multiple Furbolg to do the quest quickly. when the last one turned friendly/green at the completion of the quest it continued attacking me, along with the other Furbolg I was fighting at the time. two more immediately agroed when it turned green even though non of us were moving.
I MAY have attempted to use the quest item to bring out the corruption blob on my second enemy AS the last required Blackwood turned green.

**How it should work:**
Green/friendly NPCs should NEVER be hostile. mobs should not leave their area. when the quest completed, the Corrupted Blackwood should have turned green/friendly, stopped attacking me, and then disappeared like the other 6 did.
(https://www.youtube.com/watch?v=tLIHdixSvdE) //(not my video. just an example of the quest working correctly)

**Database links:**

![WoWScrnShot_040224_040852](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/4f68e746-ed91-4327-ba67-b5f44517c0d3)
![WoWScrnShot_040224_041223](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/197d79f5-cf64-4d06-a895-538176e1b52e)
![WoWScrnShot_040224_041326](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/7f805140-a541-4c73-8e0c-585884ddeabb)
![WoWScrnShot_040224_042741](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/ff115cae-6722-42ec-9380-0193ac82eca0)

**Comment by mafiaknight** [comment]
I think I found the same NPC still glitched out, but just chilling now...

![WoWScrnShot_040424_233445](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/06797d9d-dc52-42af-a8c2-cc3418853e56)

I guess this is where he ended up when I logged off? or is there _supposed_ to be one here?

**Comment by PanJanuszek** [comment]
fixed 08.04.2024, server restart required
