### ISSUE TITLE
Moonstalker Matriarch spawned with 24 runts

### ISSUE THREAD

**Issue by mafiaknight** [gamefreedomgit/Maelstrom#5836]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Moonstalker Matriarch spawned with 24 runts

**How to reproduce:**
not sure. I stumbled upon them. admittedly a low priority imo. could be unexpectedly lethal for someone though...

**How it should work:**
I usually see them with 1-3 runts

**Database links:**

![WoWScrnShot_040224_034751](https://github.com/gamefreedomgit/Maelstrom/assets/89418074/81ceb604-c0ca-4a8a-916a-11710809a10b)

**Comment by UltraNix** [comment]
Fixed.
