### ISSUE TITLE
swd DB

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
shadow word death doesn't break Dragons Breath

**How to reproduce:**
use swd right before a mage db you

**How it should work:**
it should break no?

**Database links:**

**Comment by pizza-with-pineapple** [comment]
yes shadow word death should break dragons breath as its direct damage.
https://cata-twinhead.twinstar.cz/?spell=31661

**Comment by UltraNix** [comment]
@SimonBpvp You mean self-damage part of the spell?

**Comment by SimonBpvp** [comment]
> @SimonBpvp You mean self-damage part of the spell? If yes, then it's not a direct damage, but a DoT with 1 sec duration.
> 
> ```
> ID - 32409 Shadow Word: Death
> 
> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 0
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> Aura Id 3 (SPELL_AURA_PERIODIC_DAMAGE), value = 0, misc = 0 (0), miscB = 0, periodic = 1000
> ```

interesting, is it supposed to be a dot?

**Comment by SimonBpvp** [comment]
ok thank you
