### ISSUE TITLE
Heroic Leap (Warrior)

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#5840]
https://www.youtube.com/watch?v=cXRtLJ5bqNQ

**Description:**
In the clip above I compare the functionality of Heroic leap on Whitemane vs Cataclysm Classic beta to show how it should work.

**How to reproduce:**
Attempt to Heroic leap at the minimum distance visually allowed

**How it should work:**
Heroic Leap should work at the nearest distance and it should also correct the positioning to the allocated minimum  around the character if too close.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=6544

**Comment by UltraNix** [comment]
Fixed.
