### ISSUE TITLE
[Shadow Priest] Extreme Lag Spike, Input Lag, Buggy Spell-queuing 

### ISSUE THREAD

**Issue by cubelogs** [gamefreedomgit/Maelstrom#5841]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While facing the 25H encounter of [Valiona](https://wowpedia.fandom.com/wiki/Valiona) and [Theralion](https://wowpedia.fandom.com/wiki/Theralion), my character began to fail to cast regularly due to extreme input lag and spell-queuing issues. My character would attempt to cast Vampiric Touch as it's about to fall off, but instead it recasts mindflay several times and the lag goes out of control. The rest of my raid team had no issues like this, only me. 

**How to reproduce:**
I don't know how to reproduce this issue. I need to report the issue so I don't get gkicked for dropping raid without attempting to resolve the issue.

**How it should work:**
I should be able to hit my abilities slightly before the end of a cast and have those abilities cast after the current spell has completed casting. I should not lag so much I see the heroism animation 15 seconds after it has been sent. 

**Database links:**

**Comment by UltraNix** [comment]
So if it's only on your side, it's something with your client or addons.
