### ISSUE TITLE
Variable Pulse Lightning Capacitor is bugged. ( stays active after you unequip it )

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#5843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
the Variable Pulse Lightning Capacitor is this trinket that when you attack players with it sometimes procs and gives you charges which start to damage players based on how many you have up to 5 which can really melt peoples health in combination with other items. I had been dueling this Warlock for a while and noticed how his dmaage was randomly way higher then it should be, but just noticed he was switching trinkets right before the duel to a PVP burst one, while also using the cunning of cruel, removing the Variable Pulse Lightning Capacitor and yet the 5 charges were staying active. and i could see in combat record, but i made the mistake of assuming it was the cunning of cruel proccing to much. 

**How to reproduce:**
simply equip the Variable Pulse Lightning Capacitor, attack a player, get 5 stacks, remove it and boom, u get to have the effects of 3 different dps burst trinkets all at once. 

**How it should work:**
should be ovious but like, when you remove it, the charges go away. you lose the effect. 

**Database links:**

https://cata-twinhead.twinstar.cz/?item=69110

**Comment by Pornoodemon** [comment]
Bro, I use different trinkets for duels with different classes. And I can't understand what your theory is. .
If before the duel I changed the trinket to the one that suits me better, is this really a bug?

**Comment by UltraNix** [comment]
As @Pornoodemon said - VPL stacks do not work without trinket (they cannot proc damage).

**Comment by UltraNix** [comment]
As @Pornoodemon said - VPL stacks do not work without trinket (they cannot proc damage).

**Comment by Hoofjob-Instinctz** [comment]
it literally shows 5 charges while its not equiped. should i make a clip?

**Comment by UltraNix** [comment]
It shows 5 stacks but does nothing. You need equip again to make them proc and do the damage.

**Comment by Hoofjob-Instinctz** [comment]
well even so, sitll worth fixing cuz thats still a buff to stop a rebuff spell. and i still see locks and mages do more damage when those procs are active without it equipped. its doing something. was it like this on retail?

**Comment by Pornoodemon** [comment]
> well even so, sitll worth fixing cuz thats still a buff to stop a rebuff spell. and i still see locks and mages do more damage when those procs are active without it equipped. its doing something. was it like this on retail?

If the trinket is not equipped, it does absolutely nothing and has no effect on damage or anything else.
