### ISSUE TITLE
Firelands hunter's pet Claw & Kill Command

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#5845]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The following npcs in the Molten Front can't be hit by hunter's Kill Command and the pet's basic attack Charred Vanquis(52503), Druid of the Flame(54343)

**How to reproduce:**

-
**How it should work:**

-
**Database links:**

**Comment by UltraNix** [comment]
Fixed.
