### ISSUE TITLE
Holy Priest - Chakra: Sanctuary (AOE) Incorrect Ingame Modifiers

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5846]
**Description:**
I was curious about the current modifiers for Holy Priests especially with the upcoming release of Deathwing and wanted to take a look at the current ingame modifiers for Holy Priest's Chakra: Sanctuary (AOE Stance) that increases AOE heals (Circle of Healing, Divine Hymn, Prayer of Healing) and Renew by 15%, and found that perhaps the current modifiers are incorrect as they feel underwhelming to play.

**How to reproduce:**
As of this report, I was using the following talent tree: https://talents.ice-wow.eu/eng/?PR#003.18-2331220212012211032113.20-!-1,-1,-1,-1,-1,-1,-1,-1,-1 which does not take any points into the Twin Disciplines talent in the Discipline tree that would otherwise increase healing by 6%.

To reproduce the numbers, please cast Renew/Prayer of Healing/Circle of Healing/Divine Hymn in Chakra: Serenity (Single Target stance) and Chakra: Sanctuary, and compare the percentage increase between the two values.

**How it should work:**
I will provide a breakdown below of the current values for Renew, Prayer of Healing and Divine Hymn both with and without Chakra: Sanctuary active, as well as a respective screenshot and adequate explanation for each spell.

**Renew**
1. [Without Sanctuary](https://ibb.co/WkHkhbb) - Renew currently will heal 2732
2. [With Sanctuary](https://ibb.co/g34CFxx) - Renew currently will heal 3060
3. Therefore the percentage increase between these two values is **12.01%** and **NOT** 15%

**Prayer of Healing**
1. [Without Sanctuary](https://ibb.co/h95RXfG) - Prayer of Healing will heal 6543 in accordance with its tooltip
2. [With Sanctuary](https://ibb.co/VpBgnX7) - Prayer of Healing will heal 7397 in accordance with its tooltip
3. Therefore the percentage increase between these two values is **13.04%** and **NOT** 15%

**Circle of Healing**
1. [Without Sanctuary](https://ibb.co/1ZS1XSm) - Circle of Healing will heal 5006 in accordance with its tooltip
2. [With Sanctuary](https://ibb.co/K7DyCqy) - Circle of Healing will heal 5659 in accordance with its tooltip
3. Therefore the percentage increase between these two values is **12.65%** and **NOT** 15%

**Divine Hymn**
1. [Without Sanctuary](https://ibb.co/qRynWgD) - Divine Hymn currently will heal 15442
2. [With Sanctuary](https://ibb.co/VYpssdP) - Divine Hymn currently will heal 16519
3. Therefore the percentage increase between these two values is **6.5%** and **NOT** 15%

I'm not the most knowledgeable when it comes to modifiers, however, I would like to highlight these potential issues as they do play a significant part in a Holy Priest's identity.

**Comment by Polynomix** [comment]
Renew : glyph of renew, spiritual healing, improved renew and chakra sanctuary are all additives with each other right now. (2732/1.25)*1.4 = 3060 (1.25 from improved renew/spiritual healing, 1.40 from improved renew/spiritual healing/sanctuary)

PoH : spiritual healing  and chakra sanctuary are additives with each other right now. (6543/1.15)*1.3 = 7397 (1.15 from spiritual healing, 1.30 from spiritual healing/sanctuary)

CoH : spiritual healing  and chakra sanctuary are additives with each other right now. (5006/1.15)*1.3 = 5659 (1.15 from spiritual healing, 1.30 from spiritual healing/sanctuary)

DH : spiritual healing, heavenly voice  and chakra sanctuary are additives with each other right now. (15442/2.15)*2.3 = 16519 (2.15 from spiritual healing/heavenly voice, 2.30 from spiritual healing/sanctuary/heavenly voice)

Now, i don't know for sure which modifiers are supposed to be additive or multiplicative but simc shows that spiritual healin, sanctuary, glyph of renew, improved renew, heavenly voice, holy archangel and twin disciplines are all multiplicatives

**Comment by clam119** [comment]
> Renew : glyph of renew, spiritual healing, improved renew and chakra sanctuary are all additives with each other right now. (2732/1.25)*1.4 = 3060 (1.25 from improved renew/spiritual healing, 1.40 from improved renew/spiritual healing/sanctuary)
> 
> PoH : spiritual healing and chakra sanctuary are additives with each other right now. (6543/1.15)*1.3 = 7397 (1.15 from spiritual healing, 1.30 from spiritual healing/sanctuary)
> 
> CoH : spiritual healing and chakra sanctuary are additives with each other right now. (5006/1.15)*1.3 = 5659 (1.15 from spiritual healing, 1.30 from spiritual healing/sanctuary)
> 
> DH : spiritual healing, heavenly voice and chakra sanctuary are additives with each other right now. (15442/2.15)*2.3 = 16519 (2.15 from spiritual healing/heavenly voice, 2.30 from spiritual healing/sanctuary/heavenly voice)
> 
> Now, i don't know for sure which modifiers are supposed to be additive or multiplicative but simc shows that spiritual healin, sanctuary, glyph of renew, improved renew, heavenly voice, holy archangel and twin disciplines are all multiplicatives
> 
> I'll try to test this on the cata beta when i have time

I'd avoid using the Cataclysm Beta as reference for now since everything especially class-related issues are a mess. However, I did browse through a few articles on mmo-champion, e.g. https://www.mmo-champion.com/threads/693203-Additive-or-multiplicative that has mentioned that Holy Priest's talents are multiplicative instead of additive, which is in-line with what you've mentioned about the talents in the Holy tree as multiplicative.
