### ISSUE TITLE
ring of frost and cyclone interaction

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5848]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
this is one of the things that doesn't explain it in the tooltip of either cyclone or ring of frost. it's like with spirit link totem not working in smoke bomb. but when a mage casts ring of frost and you cyclone that mage the ring shouldn't freeze new targets for the duration of the cyclone.

**How to reproduce:**
have a mage cast ring of frost, cast cyclone on that mage, walk into the ring of frost

**How it should work:**
ring of frost shouldn't freeze anything when the mage sits in a cyclone, it makes it pause, but it doesn't affect targets already frozen. so it should only freeze targets when the mage isn't cycloned

**Database links:**
https://www.wowhead.com/cata/spell=82676/ring-of-frost
https://www.wowhead.com/cata/spell=33786/cyclone

**Comment by Revly** [comment]
Totally False u need Proof 🚩

**Comment by dididadadududada** [comment]
not false dont need proof unless anybody important is asking for it.

**Comment by Revly** [comment]
interesting

**Comment by mipanka** [comment]
https://www.warcraftmovies.com/movieview.php?id=210911&__cf_chl_jschl_tk__=e1415a26475a8ce61d4f8f440e79577ff81a68ef-1589171314-0-AeNSnfAdZa0EBYMAJgnYWo-QGe97DuEkX-2Qv79G7g0JmJG8eR88CRI8eqPVdwR2O0RdFCh0Dz8_YH6X0nnjv0owdgTY-4popgD3MNbrkAN_jx1oGOocULZ3uofFA_40jEn57iMD8V9c1AxGoqv2pJ4mLU3jfD6b1CX86ceoMjieFE2SrMRDWpyYCsYPBu9PF9cYkxmjHVQanNCflETn08T_9SQzo3e5g01xGTeiyfy8j0pqsLX0r-gVM1wVvTWMkFji2zZm0CSMwfd70S6emqhJr2hYL2dk2z_d1fFiKoSFlsePEcF2lQWGc4nIheWXHA
but Im not sure, cuz I saw video where mage under CC and RoF worked

**Comment by mipanka** [comment]
and here 4.3 patch https://youtu.be/p667ZATEkPY?t=365 RoF worked when mage in CC. I think early patch RoF didnt worked when mage under CC, but later its be fixed or idk

**Comment by Revly** [comment]
> and here 4.3 patch https://youtu.be/p667ZATEkPY?t=365 RoF worked when mage in CC. I think early patch RoF didnt worked when mage under CC, but later its was fixed or idk

is more credible

**Comment by Hermeleen** [comment]
> and here 4.3 patch https://youtu.be/p667ZATEkPY?t=365 RoF worked when mage in CC. I think early patch RoF didnt worked when mage under CC, but later its was fixed or idk

Yes but, it's not just any cc, it has to be clone, which i think and don't quote me 100% is a "banish" effect, as ret you can't bubble it or such. Negating ring with ring was a known thing to me.

**Comment by mipanka** [comment]
RoF its channel spell

**Comment by mipanka** [comment]
> > and here 4.3 patch https://youtu.be/p667ZATEkPY?t=365 RoF worked when mage in CC. I think early patch RoF didnt worked when mage under CC, but later its was fixed or idk
> 
> Yes but, it's not just any cc, it has to be clone, which i think and don't quote me 100% is a "banish" effect, as ret you can't bubble it or such. Negating ring with clone was a known thing to me. Clone is very special case of cc.
If we talk about cyclone, above video where any cc to break work Ro. And if in second video RoF working when mage under cc, why should'n with cyclone? Need proof with 4.3 patch or waiting retail cata for be sure.

**Comment by dididadadududada** [comment]
Quit trying to gaslight developers. You're insulting their intelligence. Read the title we're talking about cyclone, you can't just link a video of any CC and call it credible. Get out of here.

**Comment by Revly** [comment]
> If we talk about cyclone, above video where any cc to break working RoF. And if in second video RoF working when mage under cc, why should'n with cyclone? Need proof with 4.3 patch or waiting retail cata for be sure.
> P. S. I know about this mechanic, but cant say how should work 100%, some other project fixed and after some time back to how was before.

I also think the same, I'm sure it's something they fixed later, ((but I'm not against it either)(it's a good way to control the magician and his RoF)
At least more tests if it was fixed later or something like that... (some hotfix is most likely)

**Comment by UltraNix** [comment]
Fixed.

**Comment by mipanka** [comment]
> Fixed.

I show video where any cc break RoF working, and video where cc (stun) dont break RoF working. Mb need 4.3 patch proof, or I can provide when cata retail will be, but no early
