### ISSUE TITLE
Bugged quest in Vashj'ir

### ISSUE THREAD

**Issue by Yoridzen** [gamefreedomgit/Maelstrom#5849]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest girding our loins was bugged, orgrimmar axes and Gilblin Plunderers doesn't spawning

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/quest=25944/girding-our-loins https://www.wowhead.com/item=56243/orgrimmar-axe https://www.wowhead.com/npc=41746/gilblin-plunderer

**Comment by PanJanuszek** [comment]
Spawn time changed to 15sec, Gilblin Plunders + axes
