### ISSUE TITLE
charging through ring of frost

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5852]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
ring of frost shouldn't freeze people when you skull bash through it

**How to reproduce:**
have a mage cast ring of frost. be a druid and target the mage or any other target and skull bash through the ring.

**How it should work:**
it shouldn't freeze u when you skull bash through it. nothing should happen

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=80964
https://www.wowhead.com/cata/spell=82676/ring-of-frost

**Comment by UltraNix** [comment]
@dididadadududada I need retail proofs for this one.

**Comment by SimonBpvp** [comment]
legit?

**Comment by UltraNix** [comment]
https://www.mmo-champion.com/threads/961207-mag-stands-in-ring-of-frost-im-feral?p=12810233&viewfull=1#post12810233

**Comment by SimonBpvp** [comment]
thats feral charge, OP is talking about skull bash. 2 different spells. 

https://cata-twinhead.twinstar.cz/?spell=80964
https://cata-twinhead.twinstar.cz/?spell=49376

**Comment by UltraNix** [comment]
Both are charges.

**Comment by SimonBpvp** [comment]
No I would say cat form feral charge is closer to a shadowstep than a charge. Skull bash is a charge. As I understand it: you would never see cat form feral charge saying "no path available" because it doesn't path. Skull bash does path like warrior charge. That's the difference or am I wrong?

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
@UltraNix 
https://youtu.be/tlv2AZjxhI0?t=127 doubtful. Did look like the freeze came before he reached the mage, but the mage was standing at the corner so can't be 100% sure. I do have cata beta acess i'll try it over there.

**Comment by bonfax4** [comment]
Yup should revert this. Much clearer here https://youtu.be/_J8GUUaRXDE?t=58

**Comment by SimonBpvp** [comment]
Nice! My question now is is there any spell for a feral or warrior which should go through ring of frost? 
skull bash: no
feral charge bear / cat: no / no
warrior charge: no?
heroic leap: ?

**Comment by bonfax4** [comment]
Feral charge does work. Leap not sure but can research

**Comment by SimonBpvp** [comment]
sorry in this clip you linked i see the Catform feral charge triggering rof, is that wrong and it was actually the skull bash?
https://youtu.be/ZewwtSRkd98?t=24

**Comment by bonfax4** [comment]
Yeah skull bash, look at mage's debuff.

**Comment by bonfax4** [comment]
https://youtu.be/6gGcR6JvaPw?t=137 Leap working followed by a warrior charge that procced it. So leap seems to work ?

**Comment by SimonBpvp** [comment]
> Yeah skull bash, look at mage's debuff.

the skull bash comes after the catform feral charge

**Comment by bonfax4** [comment]
> > Yeah skull bash, look at mage's debuff.
> 
> the skull bash comes after the catform feral charge

Hmm you could be right. I'll try to look for other leap videos

**Comment by SimonBpvp** [comment]
> https://youtu.be/6gGcR6JvaPw?t=137 Leap working followed by a warrior charge that procced it. So leap seems to work ?

looks good as long as there isnt something wierd with Presence of Mind, RoF in mists xpac. like a delay

**Comment by bonfax4** [comment]
Very odd sometimes but yh RoF does have a delay until it can proc after cast, and an icd of 3 secs i believe after dispelled/removed.

https://youtu.be/mqvYtC4ynaw?t=71 Leaped over here
https://www.youtube.com/watch?v=K1QZTghE6wE Warrior charged here and didint proc but might have been inbetween the arming time
