### ISSUE TITLE
gladiator's medallion of tenacity not working with multiple cc

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5853]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
gladiator's medallion of tenacity (the trinket that clears loss of control from your character) can't be used when affected by priest psychic scream, mage dragon's breath and hunters freezing trap all at the same time

**How to reproduce:**
get dragons breathed, fear and trap on you at the same time then try to trinket

**How it should work:**
trinket should clear all those effects

**Database links:**
https://www.wowhead.com/cata/spell=13704/psychic-scream
https://www.wowhead.com/cata/spell=27753/freezing-trap
https://www.wowhead.com/cata/spell=86691/dragons-breath
https://www.wowhead.com/cata/item=72412/ruthless-gladiators-medallion-of-tenacity

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/ccedb5b6-3ce2-4a31-970f-bd7ec1bd52d4)
Tested and removed all these effects.
@dididadadududada Do you have any screenshots of this bug? I cannot reproduce it.

**Comment by Waroxx-QA** [comment]
I think he got cc right after using the trinket

**Comment by UltraNix** [comment]
Then it's not a bug.
