### ISSUE TITLE
warlock minions have too little health

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5854]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
warlock minions should have more health.
warlock in the video has 136k hp unbuffed and the pet has 103k hp unbuffed
https://youtu.be/7ibtrZdtJB8?t=48

my warlock on whitemane has 148k hp and felhunter has 99700 hp

**How to reproduce:**
summon felhunter and look at its hp

**How it should work:**
it should scale with master's maximum health, so when the warlock gains more max health by any means the pet hp should also increase

**Database links:**

**Comment by Pornoodemon** [comment]
> **Описание:** у миньонов-чернокнижников должно быть больше здоровья. у чернокнижника в видео 136к хп без баффов, а у питомца 103к хп без баффов https://youtu.be/7ibtrZdtJB8?t=48


Yes, but keep in mind that this should scale like Snapshot HP when summon.

**Comment by Hermeleen** [comment]
daamn, it was weird, pet dying solely from soul link too often

**Comment by UltraNix** [comment]
Fixed.
