### ISSUE TITLE
Assa rogue

### ISSUE THREAD

**Issue by Navixe** [gamefreedomgit/Maelstrom#5855]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Assa rogue mastery not work correct

**How to reproduce:**
Mastery dont work correctly with poisons and bleeds dont do a real damage dont matter how mastery u have simply dont work 

**How it should work:**
That should be more damage..damage actually is too low full refogered mastery enchnats gems full mastery cap and poison-bleeds not work correctly... 

**Database links:**

**Comment by Revly** [comment]
#5733 similar?

**Comment by Navixe** [comment]
Yes both cases mastery don´t work correctly!

**Comment by UltraNix** [comment]
Duplicate.
