### ISSUE TITLE
 bug quest Harrison Jones, "Tailgunner!" server disconnect me  mid air

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5856]
I'm doing the mission "Tailgunner!" from Harrison Jones in uldum, every time the plane starts to rise, after hearing the npc's phrase, the **server disconnect  me,** it has already happened to me 7 times. a GM tried to help me by completing my mission, but give me the wrong one, same name, same npc, but from the beta

Tailgunner!" = https://www.wowhead.com/quest=27905/tailgunner# 

Tailgunner! beta = https://www.wowhead.com/quest=28743/tailgunner

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/e5ad6d38-42e0-43de-a946-bf21fa8c999d)

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/2f95a59e-4102-48cf-9d3d-32fb90d8a75f)

**Comment by PanJanuszek** [comment]
Can you contact me on discord? --> Ragnus
