### ISSUE TITLE
Darkmoon-faire The fishing trainer was Bug

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5858]
**Description:**

This NPC does not give access to purchase fishing levels as long as you have a reputation above Neutral.

**How to reproduce:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/5367d3d8-d9df-4944-a3f4-8fd6bbceab79)

_No Work_
**How it should work:**
It should be accessible to buy Fishing level

**Database links:**
https://www.wowhead.com/cata/es/npc=56068/steven-stagnaro
https://cata-twinhead.twinstar.cz/?npc=56068
https://www.wowhead.com/es/npc=56068/steven-estancacua

**Comment by UltraNix** [comment]
Fixed.
