### ISSUE TITLE
Wotlk Npc Nargle & Tabard's

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5860]
**Description:**

Supposedly this npc sells it, but i don't see thah he sells, it why is it? I also have an index of 2200

Maybe it's because it's old content?

**How to reproduce:**

He no sell Tabard's

**How it should work:**

I should sell Old Content Tabard I think

**Database links:**

https://www.wowhead.com/wotlk/es/npc=31863/nargle-trallacable#english-comments
https://www.wowhead.com/wotlk/es/item=51534/tabardo-de-gladiador-colérico

**Comment by PanJanuszek** [comment]
Tabard has been removed in patch 4.1 due to blizzard make it unique for WOTLK seasons only.
You can read all comments here:
https://cata-twinhead.twinstar.cz/?issue=13443
