### ISSUE TITLE
HotFix Potion of Illution

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5861]
**Description:**

#979
after a few months of opening DS, Lately they have blocked the Potion with any character saying: "The spell is not available to you"

**How to reproduce:**
No Work Say messaje red: The spell is not available to you

**How it should work:**

https://www.wowhead.com/item=58489/potion-of-illusion
https://cata-twinhead.twinstar.cz/?item=58489

Extra: Maybe they make it only available for players to copy, if they copy other things it produces a "Wow Error" I think...
Extra 2: When the shaman uses wolf form and they use the potion, something strange also happens, can you check?

**Database links:**

https://cata-twinhead.twinstar.cz/?item=58489
https://www.wowhead.com/item=58489/potion-of-illusion

**Comment by UltraNix** [comment]
Fixed.
