### ISSUE TITLE
Necrotic strike debuff doesn't wear off showing "negating 0 healing left".

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#5865]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

A lot of the times lately Necrotic Strike debuff from enemy doesn't wear off showing "negating 0 healing left". I noticed firstly , when enemies were healing "through" necro. But it is just visual bug
**How to reproduce:**

**How it should work:**

**Database links:**
![WoWScrnShot_041024_150601](https://github.com/gamefreedomgit/Maelstrom/assets/48323513/e51e165a-334b-4a96-a410-e1cb19e50f74)

**Comment by SimonBpvp** [comment]
if the casting speed slow stays on after you outheal the necro then that's not just a visual bug that's a big bug.

**Comment by UltraNix** [comment]
`if the casting speed slow stays on after you outheal the necro then that's not just a visual bug that's a big bug.`
Source?

**Comment by UltraNix** [comment]
Fixed.
