### ISSUE TITLE
[Profession] [Skinning] [Mob] [Reputation] [Firelands] [Spell bug]

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#5869]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Skinning of the following mobs in Firelands is not possible:
Fire Scorpion: 53127
Giant Fire Scorpion: 53128
Fire Turtle Hatchling: 53096
Matriarch Fire Turtle: 53095
Patriarch Fire Turtle: 53094

Reputation gain on kill of the following mobs in Firelands is not correct or not giving at all:
Giant Fire Scorpion: 53128
Matriarch Fire Turtle: 53095

~~The following spell is not working as intended/at all
Patriarch Fire Turtle: 53094
Spell ID:100842~~

**How it should work:**
1.Giant Fire Scorpion: 53128
 Gives 7 reputation with bonuses included however on wowhead its stated that they give 15 without any bonuses (assuming its possible to get bonus out of items/ racials or events).

~~2.Patriarch Fire Turtle: 53094
Spell ID:100842
"Reflects 50% of incoming spells back at the  caster"~~

3.Matriarch Fire Turtle: 53095
 Should get 15 base reputation

**Comment by UltraNix** [comment]
Ad3. Turtle usues it at 1-55% every 18 sec.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/c9b88196-9055-48f9-8be9-6e0ebe0cc70e)

**Comment by NinacS90** [comment]
Aw I made a huge mistake, my apologies, I misunderstood the spell; "Shell Shield | 4.2.0 (Tue Aug 16 2011) Build 14107 - Shell Shield - 1.5 seconds cast - reflects 50% of damage taken" - I thought its all damage reflected.

**Comment by UltraNix** [comment]
Fixed.
