### ISSUE TITLE
Crawfish Creole 

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#5870]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The Crawfish are not getting picked up.

**How to reproduce:**
Try to complete the quest.

**How it should work:**
https://www.youtube.com/watch?v=R4OWLbktSfk&ab_channel=ultrastream

**Database links:**
https://www.wowhead.com/quest=26226/crawfish-creole

**Comment by PanJanuszek** [comment]
fixed 15.04.2024 after server restart
