### ISSUE TITLE
Quest isn't completable

### ISSUE THREAD

**Issue by CMG-Scarecrow** [gamefreedomgit/Maelstrom#5872]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The Quest "You are Rakh'likh, Demon" a quest in the Blasted Land isn't completable because the necessary mobs won't spawn, as a result of that, i can't complete the following quests which means i can't complete the Blasted Land quest achievement.

**How to reproduce:**
I don't know what to write here, sorry :)

**How it should work:**
A little roleplay between two mobs should start, after you get teleported on top of the mountain, after that little roleplay you need to defeat the demon and trap him with a quest item, so he won't return.

**Database links:**
I don't have Database links :(

**Comment by MadeinNoxus** [comment]
https://www.wowhead.com/cata/quest=3628/you-are-rakhlikh-demon There is your data base

**Comment by PanJanuszek** [comment]
Did you start event  by talking with ghost down the hill?

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/7dc5d825-44a4-42ff-8752-38ac8b0781a2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/8d21deb6-395f-414c-a8f5-98c95cf0287d)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/aa493d87-7e6c-4510-9239-10abd4ce8a4f)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/0fd2635f-0fe8-49e0-b37f-54cf38b389d0)

**Comment by PanJanuszek** [comment]
> https://www.wowhead.com/cata/quest=3628/you-are-rakhlikh-demon There is your data base

This is wrong pre-cata
