### ISSUE TITLE
Trap macro bug

### ISSUE THREAD

**Issue by Kadalol** [gamefreedomgit/Maelstrom#5874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Since yesterday, I can no longer use my traps macro on the instant realm (but it work on your PTR)
#showtooltip
/use Launch-trap
/use Frost trap(Frost - Launch-trap)

**How to reproduce:**
copy this macro and try it on your PTR and on your instant realm.

**How it should work:**
I should be able to use this macro, the parenthesis means that the launch trap must be active to be able to use the trap

**Database links:**
https://www.wowhead.com/cata/fr/spell=77769/lance-pi%C3%A8ge
https://www.wowhead.com/cata/fr/spell=1499/pi%C3%A8ge-givrant

**Comment by UltraNix** [comment]
Fixed.
