### ISSUE TITLE
Archaeology digsite Nazj'vel(Darkshore) spawns fragment in middle air, imposible to reach

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5875]
As title says, It happens to me two times with same digsite and same fragment in same coords.
Both times the bug occured with the  last fragment

![WoWScrnShot_041424_032047](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/a342ecf2-7132-4716-89c8-6f450650d827)
![WoWScrnShot_041424_032054](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/9bc14053-e87e-4bb6-9c85-ea56f007423f)
![WoWScrnShot_041424_032126](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/7fbf702c-cadf-4ee9-befa-f83575b85596)

**Comment by MadeinNoxus** [comment]
https://www.wowhead.com/cata/quest=3628/you-are-rakhlikh-demon There is your data base

**Comment by Pepelomb** [comment]
@UltraNix any news? :)

**Comment by UltraNix** [comment]
Fixed.
