### ISSUE TITLE
Death Knight Trainers not available if questline is skipped

### ISSUE THREAD

**Issue by Mythhy** [gamefreedomgit/Maelstrom#5876]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
When creating a Death Knight and using the NPC to skip the questline, the starting zone is stuck in a phase were the trainers are not there but Morgaine cannot reset talents as such making it impossible for death knights that skipped the questline to reset their talents.

**How to reproduce:**
Create a death knight, skip questline via npc, teleport to capital city, teleport back and look for the trainers.

**How it should work:**
Obviously this is a whitemane specific feature as such no blizzard equivalent but it is quiet resonable to expect it to work in a way where talent resets are possible.

**Database links:**
No blizzard equivalent to the feature.

**Comment by UltraNix** [comment]
Just use your Death Gate instead - your old starting location is now replaced (and phased-out) by the new one.

**Comment by UltraNix** [comment]
Fixed.
