### ISSUE TITLE
Misleading text description [Vial of Shadows]

### ISSUE THREAD

**Issue by NinacS90** [gamefreedomgit/Maelstrom#5877]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I thought I was on to something with the damage but it turns out the text on the item was wrong and misleading.
Vial of Shadows has 4 versions on the server( raid finder or arsenal, wartorn through pvp vendor and pve normal and heroic)
The descriptions on various sites or comments you can find are the following:
"Equip: Your melee and ranged attacks have a chance to trigger an additional attack for (3568 + 0.266 * AP)."
"Equip: Your melee and ranged attacks have a chance to trigger an additional attack for (4028 + 0.3 * AP)."
"Equip: Your melee and ranged attacks have a chance to trigger an additional attack for (4546 + 0.339 * AP)."
Whitemane depending on the version:
"Equip: Your melee and ranged attacks have a chance to trigger an additional attack for %. physical damage."

**How to reproduce:**
.

**How it should work:**
Raid Finder or Arsenal
"Equip: [Your melee and ranged attacks have a chance to trigger an additional attack for 3568 to 5353 physical damage." 
(Proc chance: 45%, 9s cooldown)
Wartorn or normal pve
"Equip: [Your melee and ranged attacks have a chance to trigger an additional attack for 4028 to 6042 physical damage."
(Proc chance: 45%, 9s cooldown)
Wartorn or heroic pve
"Equip: [Your melee and ranged attacks have a chance to trigger an additional attack for 4546 to 6819 physical damage."
(Proc chance: 45%, 9s cooldown)

**Database links:**
https://www.wowhead.com/cata/item=77979/vial-of-shadows
https://www.wowhead.com/cata/item=77207/vial-of-shadows
https://www.wowhead.com/cata/item=77999/vial-of-shadows

**Comment by ManneN1** [comment]
@NinacS90 where did you find the scaling formula? E.g., 3568 + 0.266 * AP?

**Comment by NinacS90** [comment]
Hey, here I forgot to add it 
https://wowpedia.fandom.com/wiki/Vial_of_Shadows, check raid finder, normal and heroic versions
