### ISSUE TITLE
Goldshire Spring Rabbit

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#5879]
**Description:**
The Spring Rabbit critter in Goldshire is permanently in love with some other rabbit and cannot be "loved" for the [Spring Fling] achievement.

**How to reproduce:**
Spring Rabbit in Goldshire

**How it should work:**
Walk up to the Spring Rabbit with your Spring Rabbit companion and the two will fall in love and give you the progress for the achievement.

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=32791
https://www.wowhead.com/wotlk/npc=32791/spring-rabbit
https://www.wowhead.com/wotlk/achievement=2419/spring-fling

**Comment by PanJanuszek** [comment]
fixed 15.04.2024 after server restart
