### ISSUE TITLE
Sinestra - Dispelled Wrack Gives 4 Stacks Instead Of Two

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5883]
**Description:**
Reporting in the stead of Tmugsy on Discord. Currently there seems to be a bug where dispelling wrack on 25m (and possibly 10m) that gives you four debuffs instead of two on the initial dispell of the first application of Wrack. 

As this was on Maelstrom, I would assume that this could carry on over to Deathwing and so would perhaps be a good thought to see if this occurs on both realms & in 10 and 25 man raid sizes.

**How to reproduce:**
Get a group of at least 5+ people, have the first initial application of Wrack dispelled and see if it applies four separate Wrack debuffs or two.

**How it should work:**
Dispelling any single individual Wrack debuff should only split it into two and not four.

Logs Link:
https://www.warcraftlogs.com/reports/RfhnxPD4T7wB2MKH#fight=1&type=auras&view=events&spells=debuffs&ability=89421

**Comment by UltraNix** [comment]
Fixed.
