### ISSUE TITLE
Fish school not gives x5 loot

### ISSUE THREAD

**Issue by AlucardHellsingChapel** [gamefreedomgit/Maelstrom#5884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Fishing schools do not give loot x5 they still give x1

**How to reproduce:**
Fish at any fish school

**How it should work:**
Should give the x5 loot but gives x1

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/68818693/2f5c779e-e7d2-4807-a382-f261a4f21fb2)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Deathwing/issues/16
