### ISSUE TITLE
Fire Elemental not switching targets with Flame shock (Shaman)

### ISSUE THREAD

**Issue by Battlecryz** [gamefreedomgit/Maelstrom#5885]
**Description:**
The fire elemental totem is not switching targets when applying flame shock when switching targets.

**How to reproduce:**
On a target dummy, use Fire Elemental totem and cast flame shock on a target, then use flame shock on a secondary target.

**How it should work:**
The Fire elemental is suppose to function with flame shock to switch targets just like a searing totem, however currently it'll stay on first target you attack.

**Database links:**
https://cata-shoot.tauri.hu/?spell=2894

**Comment by Sketish** [comment]
This change was done in MoP not in cata

**Comment by UltraNix** [comment]
Also - https://www.mmo-champion.com/threads/851031-Elemental-FAQ-(updated-for-4-3)?p=10435271&viewfull=1#post10435271
Only Srearing Totem follow Flame Shocked targets.
