### ISSUE TITLE
Charging through ring of frost 

### ISSUE THREAD

**Issue by bonfax4** [gamefreedomgit/Maelstrom#5889]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Revert #5852 
![eb6ad5b0ee15845198fa7e2ff2a436bd](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/fdf76f9a-d7db-436c-b399-e0fe3f27f428)

**How to reproduce:**

**How it should work:**

> @UltraNix https://youtu.be/tlv2AZjxhI0?t=127 doubtful. Did look like the freeze came before he reached the mage, but the mage was standing at the edge on the other side so can't be 100% sure. I do have cata beta acess i'll try it over there.
> 
> Leap should work, confirmed already but still nice to see video proof. https://youtu.be/Kt7IpfBABQE?t=110

> Yup should revert this. Much clearer here https://youtu.be/_J8GUUaRXDE?t=58 / https://youtu.be/ZewwtSRkd98?t=24

**Database links:**

**Comment by mipanka** [comment]
@UltraNix  pls try test RoF and Cyclone on ptr

**Comment by dididadadududada** [comment]
#5852 was for skull bash only, i don't know why people were talking about other abilities.
https://www.youtube.com/watch?t=58&v=_J8GUUaRXDE&feature=youtu.be is feral charge - cat which doesn't matter for this case
https://www.youtube.com/watch?t=24&v=ZewwtSRkd98&feature=youtu.be druid is standing in ring of frost after the skull bash, which is freezing him. mage is standing close to the ring, so when druid uses skull bash the druid is still touching the ring, causes druid to get frozen after he lands skull bash. u can play it frame by frame to see it easier

**Comment by bonfax4** [comment]
Such a reach. Mage is nowhere near that ring on that video.. Find a video confirming it then. I went through multiple, if it was a thing I'd find it more often for sure

**Comment by UltraNix** [comment]
After looking all these videos - I will revert it.

**Comment by UltraNix** [comment]
Fixed.
