### ISSUE TITLE
Dk Quest: Massacre At Lights Hope

### ISSUE THREAD

**Issue by cloud1121** [gamefreedomgit/Maelstrom#589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When Using the Gryphon from cannon to go back, flying mount gets stuck in path. 

**How to reproduce:**
Do quest, use cannon skill 5 to fly back

**How it should work:**
Should continue the path all the way back

**Database links:**
![Massacre Bug](https://user-images.githubusercontent.com/77916637/120377532-18cde700-c2d2-11eb-9a60-c5585e31edfc.PNG)

**Comment by WhitemaneSylah** [comment]
New issues found with this 

![image](https://user-images.githubusercontent.com/121137397/221206353-da6539bd-59ad-4514-90b8-d0a56faa581d.png)

Clicking on the cart will spawn you where the cart should be but outside it, the object then reverts to being clickable.

![image](https://user-images.githubusercontent.com/121137397/221211429-565e4054-1291-4d9c-999a-76f462382fd7.png)

**Comment by WhitemaneSylah** [comment]
Closed as per discussion with Ultranix
