### ISSUE TITLE
Bug with archeology

### ISSUE THREAD

**Issue by LadyBorshi** [gamefreedomgit/Maelstrom#5891]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** Hi, Deathwing, character Trish. After yesterday's server restart, archeology is buggy, I don't see any excavation sites, etc. It is impossible to abolish a profession and retrain it.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Waroxx-QA** [comment]
Make a ticket in-game.
