### ISSUE TITLE
Potion of Treasure Finding does not work in Tol Borad

### ISSUE THREAD

**Issue by slchristensen** [gamefreedomgit/Maelstrom#5892]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
This potion, despite it's tooltip, should work in Tol Borad if it matches retail behavior

**How to reproduce:**
Killed a few hundred mobs with the potion buff, no treasure chests dropped.

**How it should work:**
5% of kills should drop a treasure chest. Per testing in the comments of the link.

**Database links:**
https://www.wowhead.com/item=58488/potion-of-treasure-finding#comments

**Comment by UltraNix** [comment]
Fixed.
