### ISSUE TITLE
Bugged NPC - Roxi Ramrocket

### ISSUE THREAD

**Issue by Chuzz13** [gamefreedomgit/Maelstrom#5893]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
This NPC is supposed to sell items as well as be a trainer. Only it seems some accounts do not get the choice and the training menu appears. Where as other accounts can buy her items required to make the Mechno-Hog

**How to reproduce:**
Right-click and the flight trainer menu appears. My friend clicks and he gets a choice of training or browse goods.

**How it should work:**
Should right click and get a choice of training or browse goods.

**Database links:**
https://www.wowhead.com/wotlk/npc=31247/roxi-ramrocket#sells

**Comment by Waroxx-QA** [comment]
I think it's caused by racial shifting
to be tested.

**Comment by Chuzz13** [comment]
> I think it's caused by racial shifting to be tested.

No racial shift on my account. Gnome and Undead on two different accounts unable to purchase from Roxi

**Comment by Waroxx-QA** [comment]
![Screenshot_2024-04-20-12-38-53-70_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/b46bf172-f09e-43ad-84cd-55af59732b9a)

@Chuzz13

**Comment by PanJanuszek** [comment]
as described above, some conditions have to be met
