### ISSUE TITLE
Died

### ISSUE THREAD

**Issue by Mico690** [gamefreedomgit/Maelstrom#5894]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
was in the Maraudon Doungen, and we died. but no one can find the instance. we spend 30min. then log out, when we was going at 2 meters from spiret. then it say you need to go into the instance, but we could't find it.

**How to reproduce:**
ressucte, and mabay make a help guidelines for that instance.

**How it should work:**

**Database links:**
Calina-Deathwing

**Comment by Waroxx-QA** [comment]
Do your own research on youtube. there's a lot of clips posted by players showing instances entrance.
