### ISSUE TITLE
 [Una lección aprendida]

### ISSUE THREAD

**Issue by Blady29** [gamefreedomgit/Maelstrom#5895]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

Misión de Terrallende - Valle SombraLuna 
NPC Onorok Corazon Roto

**How to reproduce:**

al dar clic en los huevos se muestra mensaje "no se puede abrir"
**How it should work:**

Debería destruirse el huevo al dar clic

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/95987529/0de68d61-107d-4a89-8fd8-23e7f4543184)

https://www.wowhead.com/tbc/es/quest=10515/una-lecci%C3%B3n-aprendida

**Comment by Waroxx-QA** [comment]
Make a new report in English please.
