### ISSUE TITLE
Toys with little or no dropability

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5896]
**Description:**

During Maelstrom during the beginning of patch 4.1 I was able to verify that these Items despite their low Drop I was never able to obtain one, then I gave up continuing.

 **### _(I did what I could maybe I should try dropability?)_**

so I went to test the PTR

![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/49a8af91-3ede-4aab-8f03-06b36cd9626a)

Never Drop Dice when you steal from NPC's.

Despite being a Low Drop Chance I will never drop those items "Toys"

[worn-trol-dice](https://www.wowhead.com/es/item=36862/) LK
[loaded-gnomic-dice](https://www.wowhead.com/es/item=63269/loaded-gnomic-dice) CATA
[decahedral-dwarven-dice](https://www.wowhead.com/es/item=36863/) LK

All comments about items in Wow Head

**How to reproduce:**

[loaded-gnomic-dice](https://www.wowhead.com/es/item=63269/loaded-gnomic-dice) It does not make any gesture and should make a gesture or emotion & no Drop
[worn-trol-dice](https://www.wowhead.com/es/item=36862/) Work but no Drop
[decahedral-dwarven-dice](https://www.wowhead.com/es/item=36863/) Work but no Drop

**How it should work:**

[loaded-gnomic-dice](https://www.wowhead.com/es/item=63269/loaded-gnomic-dice) I should make a gesture like they do with dice
[worn-trol-dice](https://www.wowhead.com/es/item=36862/)  should have more dropability
[decahedral-dwarven-dice](https://www.wowhead.com/es/item=36863/) hould have more dropability

**Database links:**

https://www.wowhead.com/es/item=63269/loaded-gnomic-dice // https://cata-twinhead.twinstar.cz/?item=63269

https://www.wowhead.com/es/item=36862/worn-trol-dice  //  https://cata-twinhead.twinstar.cz/?item=36862

https://www.wowhead.com/es/item=36863/decahedral-dwarven-dice //  https://cata-twinhead.twinstar.cz/?item=36863

**Comment by UltraNix** [comment]
https://www.wowhead.com/cata/item=36862/worn-troll-dice#pick-pocketed-from - it's a pickpocket loot. The biggest chance is from https://www.wowhead.com/npc=29874/drakkari-inciter - 16%
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a7f71560-8b49-4191-8ded-01d990c9b016)

**Comment by Revly** [comment]
> https://www.wowhead.com/cata/item=36862/worn-troll-dice#pick-pocketed-from - it's a pickpocket loot. The biggest chance is from https://www.wowhead.com/npc=29874/drakkari-inciter - 16% ![image](https://private-user-images.githubusercontent.com/80540499/326052081-a7f71560-8b49-4191-8ded-01d990c9b016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDU0MjEsIm5iZiI6MTcxNDMwNTEyMSwicGF0aCI6Ii84MDU0MDQ5OS8zMjYwNTIwODEtYTdmNzE1NjAtOGI0OS00MTkxLThkZWQtMDFkOTkwYzliMDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDExNTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWVlZmM2NGEzYWM3ZjAwYTRhNmYwNTIwZjZiMDU0MDI5NDlkNGY0ZTdlYjdjZTEzMDI5ZDZmMjIyOWVlODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QogScxaGdqa4sZP7fzBc6WFqgJbRIWNHmigvOAXRwI)

OK

But another's Low Dropability
[loaded-gnomic-dice](https://www.wowhead.com/es/item=63269/loaded-gnomic-dice) CATA
[decahedral-dwarven-dice](https://www.wowhead.com/es/item=36863/) LK

With their respective npcs that should be pickpocket loot most only give gold

**Comment by UltraNix** [comment]
Fixed.
