### ISSUE TITLE
Bastion of Twilight - Valiona & Theralion Engulfing Magic Melee

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5901]
**Description:**
Currently there exists a bug that was prominent in the early stages of Maelstrom but has resurfaced in Deathwing, and that is the Engulfing Magic debuff appearing in melee. 

**How to reproduce:**
Start the encounter with a few melee stacked up as Engulfing Magic is cast and notice it appearing on melee.

**How it should work:**
Engulfing Magic should not be applied on melee.

**Database links:**

**Comment by UltraNix** [comment]
Hmm - it works like that:
First, it picks up targets in 15-250y from the boss.
If the list is empty, then is takes random players from any range.

So if you are a rogue 16y away from the boss - you may get the buff.
If you are a mage 10y away from the boss - you may not get the buff.

**Comment by UltraNix** [comment]
Fixed.
