### ISSUE TITLE
Blackwing Descent - Toxitron: Soaked in Poison Dispel 

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5902]
**Description:**
This has been a known bug since Maelstrom but it applies to both Maelstrom and Deathwing, and it is that the Soaked in Poison debuffs that stack should be completely removed upon a single dispel.

**How to reproduce:**
Start the encounter and have Toxitron's shield active, get stacks of Soaked in Poison and use Cleanse to dispel the poison and observe as it only removes a single stack a time.

**How it should work:**
As per the ingame journal and WoWHead, you should be able to dispel all stacks with a single dispel.

**Database links:**
https://www.wowhead.com/npc=42180/toxitron

**Comment by UltraNix** [comment]
Fixed.
