### ISSUE TITLE
Some Npc's in Vash ir dont should Friendly

### ISSUE THREAD

**Issue by Revly** [gamefreedomgit/Maelstrom#5903]
**Description:**

Vash ir is a dangerous place so it would not be bad to place it, if it were not Friendly
This NPC is the equivalent of the Fel Reaver from Hellfire Peninsula, but in the Cata version, he patrols a certain place and if you cross him on the way he will hurt you.

according to the comments

**How to reproduce:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/6c27ec31-ad3d-4278-9e17-c1a53421e997)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/4008fc78-b28a-49b5-ac2b-d1e341d1b067)

**How it should work:**

dont should Friendly

**Database links:**

https://www.wowhead.com/cata/es/npc=42181/velskar
https://www.wowhead.com/cata/npc=42215/kolorath

**Comment by PanJanuszek** [comment]
fixed 22.04.2024, server restart required

**Comment by Revly** [comment]
> fixed 22.04.2024, server restart required

Need abilities
https://cata-twinhead.twinstar.cz/?npc=42181#abilities

[Kolorath](https://www.wowhead.com/npc=42215/kolorath#comments) Need Damage

it's totally easy
