### ISSUE TITLE
Bastion of Twilight - Cho'gall Rooted In Place

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5906]
**Description:**
Currently, there's a bug on Cho'gall where players are randomly getting stuck in place although the cause is unknown. Perhaps it is something to do with being in the middle of the room whilst under Conversion but not certain as to what is causing this.

**How to reproduce:**
Start the encounter and position yourself in the centre of the room and see if Conversion is the cause of this issue.

**How it should work:**
Shouldn't be rooted in position.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
