### ISSUE TITLE
Mage tier gloves cost shoulder token

### ISSUE THREAD

**Issue by Kendanter88** [gamefreedomgit/Maelstrom#5908]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The valorous quartermaster is selling the mage tier gloves for the cost of a shoulder token and shoulder piece

**How to reproduce:**
visit valorous quartermaster as a mage

**How it should work:**
the mage tier gloves should cost a glove token and glove

**Database links:**
![tier bug 2](https://github.com/gamefreedomgit/Maelstrom/assets/32742809/856d13c8-1c2c-491c-a606-3b305a8002d8)
![tier bug](https://github.com/gamefreedomgit/Maelstrom/assets/32742809/57c34305-1680-4426-8517-9f4007a87d43)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Deathwing/issues/27 as it's Deathwing.
