### ISSUE TITLE
Bug quest "They Grow Up So Fast"  [quest=13906] 

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5909]
**Description:**
the npc show white question mark. I already tried restart game. I'm using english exe

**How to reproduce:**
Just got all the ingredients but npc show question mark in white

**How it should work:**
the npc, should allow to complete, and give  _"Whistle of the Venomhide Ravasaur" item id: 46102_

**Database links:**
[quest=13906] 

![WoWScrnShot_042224_011555](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/73a607c6-318b-4470-a5c7-8574a64572ec)

![WoWScrnShot_042224_011518](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/6aa1d314-08bc-439a-ab1c-8dd52cb4c392)

**Comment by UltraNix** [comment]
@Pepelomb Try abandon quest and re-take it.

**Comment by Pepelomb** [comment]
> @Pepelomb Try abandon quest and re-take it.

I will try now, I hope it wont delete the teeth

**Comment by Pepelomb** [comment]
It worked!!. Thanks =D.  Now issue can be mark as close/solved
