### ISSUE TITLE
Caravan Questline in EPL.(The Trek Continues)

### ISSUE THREAD

**Issue by Phoob2** [gamefreedomgit/Maelstrom#5910]
Going through the caravan questline im stuck after doing crown guard tower's quests im unable to proceed going in the caravan to the next tower. It only gives the option to get one of three buffs.

Complete 2 quests in crown guard tower in the chain

Should be able to click the caravan and click go to next destination.

https://www.wowhead.com/cata/quest=27448/the-trek-continues) is the quest it should offer

![WoWScrnShot_042224_043853](https://github.com/gamefreedomgit/Maelstrom/assets/167758169/16faafca-6338-4c60-940e-fea30584275a)

**Comment by PanJanuszek** [comment]
Basing on GM theory. You have skipped one quest. Me and two other people were able to continue this chain

**Comment by Phoob2** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/167758169/a9506741-e340-4767-bd7f-29fc8c000df5)

I followed this questline and did all the quests , maybe they left something out or i triggered something to bug it im not sure, maybe the database is wrong and it requires over lvl 39
