### ISSUE TITLE
Blazing speed not intended behaviour (Fire Mage PVP)

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#5912]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Mages can get Blazing speed procs without any cooldown.

**How to reproduce:**
Hit a fire mage, and wait for him to proc the Blazing speed (mage talent). It has no 25 second cooldown.

**How it should work:**
"Blazing Speed was a mage talent. Blazing Speed provided a very short boost of movement speed. It had a 25-second cooldown and was not affected by the global cooldown." this is the description during the original Cataclysm. 

This part was added during later stages of original Cataclysm. 
- [Patch 4.0.3a] Blazing speed no longer dispels movement slowing effects (it still dispels effects that totally stop movement). This was put into action during cataclysm. 

At no point in Cataclysm original did mages have endless amount of blazing speed procs. 

**Database links:**
https://wowpedia.fandom.com/wiki/Blazing_Speed
https://cata-twinhead.twinstar.cz/?spell=49264

**Comment by SimonBpvp** [comment]
it's another fire talent that makes it dispel slows![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/aa86c61a-842d-479b-b48c-dd4d7a831896)

**Comment by mipanka** [comment]
mb u will show any proof? :)

**Comment by bonfax4** [comment]
Not true. Check mage buffs through the video https://youtu.be/iIBbXlI_tfs?t=4m59s . He's getting it refreshed before it even runs out
