### ISSUE TITLE
ice barrier and mana shield needs to dissipate upon arena start

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5913]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
ice barrier and mana shield needs to dissipate upon arena start

**How to reproduce:**
go to arena, cast ice barrier and mana shield before gates opens, then wait for gates to open and see the shields are still up.

**How it should work:**
ice barrier and mana shield needs to dissipate upon arena start just like any other short term buff does

**Database links:**
https://classicdb.ch/?spell=13031)
(https://www.wowhead.com/classic/spell=1463/mana-shield)

**Comment by SimonBpvp** [comment]
if the buff is over 30 seconds it doesn't get removed, under 30sec gets removed.
