### ISSUE TITLE
VORTEX PINNACLE COMBAT BUG

### ISSUE THREAD

**Issue by oxy1111** [gamefreedomgit/Maelstrom#5914]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
There's a bug that somehow prevents you from exiting combat so you can't drink, eat or taking the vortex to the next stage.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by oxy1111** [comment]
d

**Comment by Revly** [comment]
[Lurking tempest](https://www.wowhead.com/es/npc=45704)

Leaves combat bug sometimes

**Comment by frostwave942** [comment]
the solution for now is tp out and in after killing first boss.

**Comment by Revly** [comment]
> the solution for now is tp out and in after killing first boss.

It's like the last solution, but the best solution is that at such a distance it should stop combat, but it bugs because it keeps casting a lightning charge to the target

**Comment by UltraNix** [comment]
Just kill the mob :)

**Comment by Revly** [comment]
[Lurking tempest](https://www.wowhead.com/es/npc=45704) Supposedly he is using [Lurk](https://www.wowhead.com/es/spell=85467/esconderse) 
Does this count as a Feign Death or am I wrong?

I find In commentary say he Use [Feing Death](https://www.wowhead.com/es/spell=85267/fingir-muerte)

**Comment by UltraNix** [comment]
Fixed.
