### ISSUE TITLE
Quest: Human Infestation ID: 28138

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5915]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest cannot be completed because there are missing elements from it. There are maybe two or three webbed miners in the entire area, there should be more. There are many miners in the zone, but they are static. When I taunt them and want to use Titanium Shackles nothing counts.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=2c8fGnE0CEQ

**Database links:**
https://www.wowhead.com/quest=28138/human-infestation

**Comment by PanJanuszek** [comment]
First:

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/12b1119c-5c63-429d-ab53-8a12e6f99ec6)


1. Hillsbrad Sentry will attack you after taunt 
2. You have to deal damage up to 35% of his HP (difficult on high level)
3. Then you can use quest item. Added text that informs player about it.
