### ISSUE TITLE
Dropped Alchemy, re-learned it Bugged.

### ISSUE THREAD

**Issue by Tableskiing** [gamefreedomgit/Maelstrom#5916]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I wanted to re-learn a new specialization for alchemy, so i dropped it, re-trained it and never gave me the quest at the end. It didn't me drop the specialization after re-learning it. Now i have no specialization nor can get the quest. 
![Bug 1](https://github.com/gamefreedomgit/Maelstrom/assets/167943844/4fc77295-275c-41f1-8e14-e671f2fe432f)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment]
You mean you lvled alchemy from 1-525 again to change spec ? You should only need to do a quest to switch irrc.
