### ISSUE TITLE
[Death Knight][Tier sets] DPS Tier DK 4set does not work on Blood DK

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Maelstrom#5919]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

You can use diffrent sets and tier bonus of those should work anyway.
Like in t12 Firelands some BDKs use 2set DPS 2set Tank for bonuses etc, yet T11 dps 4set bonus is bugged and does not trigger on Blood DK, screenshot below.

How it should work?
According to a tooltip info of DK 4set  "Each time you gain Death Rune or trigger killing machine..." anyway you get 1% attack power stacking 3 times. Which works as Unholy.

But if you are in Blood DK talents it does not work which is a bug.

JPG as Unholy
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/3f2141cf-b9d2-47f4-a81b-5febe38d4e80)
and here as Blood you can clearly see ive got Death Runes yet no buff
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/24c97f26-e0d5-434c-9228-89c1451bf36d)

**Comment by Nenze** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/4bd471dc-1ebe-415d-b271-dd3f0a767779)
its this icon for context

**Comment by Nenze** [comment]
Update
Changelog said its fixed its still not
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122581454/8c1c38ab-c905-4f58-aaa8-0cb28d8f0b3b)

**Comment by UltraNix** [comment]
Fixed.
