### ISSUE TITLE
[Warlock] Felguard's Felstorm continues when disarmed

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#5920]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Similar to arms warrior's bladestorm, felguard's felstorm is subject to disarm (requires weapon)
Felguard can't cast felstorm while it is disarmed, which is working correctly
But, getting disarmed during felstorm does not stop it.

**How to reproduce:**
Cast felstorm
Disarm felguard
Spell continues, damage continues

**How it should work:**
Spell should end on disarm
[EDIT] Or maybe spell should update damage calculation if disarmed
**Database links:**
https://cata-twinhead.twinstar.cz/?spell=89751
https://www.wowhead.com/cata/spell=89751/felstorm (Requires main hand weapon)

**Comment by Pornoodemon** [comment]
Since it's a pet, it's unclear how disarming should work on pets. More evidence is needed. Maybe it shouldn't work on pets at all.

**Comment by djesic** [comment]
Legion Strike (the other felguard ability) requires a weapon, and is subject to disarm also, and it doesn't cast it when disarmed.
And both spell's tooltip mention the felguard's axe.
Therefor it is a melee weapon.

Also, the animation is there - you see the axe go away when it is disarmed.

I don't think there are other instances of pet's wielding weapons, certainly not on other classes.
Maybe succubus's whip? But I don't think it's relevant here

**Comment by djesic** [comment]
Here are the tooltips
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/2a62f1df-55b6-4177-8683-9919df3f8d2e)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/1754350a-8444-4c49-836a-37b64ae736d2)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/1ba8dba5-4569-47f0-a1df-70234ac70696)

All of them specify "Requires Two-Handed Axes" and in the tooltip for Felstorm there is this line:
```
within 8 yards for its *weapon damage* plus
```

**Comment by djesic** [comment]
And here is a combat log from a duel, just for good measure
```
Thooroon casts Felstorm. 
Thooroon's Felstorm hits Circlejerkin for 4821 Physical. 
Thooroon gains Thooroon's Felstorm. 
Thooroon's Felstorm was parried by Circlejerkin. 
Circlejerkin casts Dismantle at Thooroon. 
Thooroon is afflicted by Circlejerkin's Dismantle. 
Thooroon's Felstorm hits Circlejerkin for 9586 Physical.(Critical) 
Thooroon's Felstorm hits Circlejerkin for 9446 Physical.(Critical) 
Thooroon's Felstorm hits Circlejerkin for 9593 Physical.(Critical) 
Thooroon's Felstorm hits Circlejerkin for 4842 Physical. 
Thooroon's Felstorm hits Circlejerkin for 4757 Physical. 
Thooroon's Felstorm fades from Thooroon. 
Circlejerkin's Dismantle dissipates from Thooroon. 
```

**Comment by UltraNix** [comment]
Need some proofs from retail it should stop casting it.

**Comment by Revly** [comment]
Two-handed Axe is Weapon, Yes should dismantle, cancel Fel Storm, and disable Throw axe, no have proof but I have experience.
I find Proof's after

**Comment by UltraNix** [comment]
Logic is not a strong suit of Blizzard ;)

**Comment by Pornoodemon** [comment]
It's not even a matter of having a weapon, but whether it should work on the pet.
Here  need a video proof  to understand how it works.

**Comment by Revly** [comment]
> It's not even a matter of having a weapon, but whether it should work on the pet. Here need a video proof to understand how it works.


Yes work on the pet because is Demon and he use weapon,  
On several servers where I have gone it has always worked

**Comment by Pornoodemon** [comment]
Convincing proofs)

**Comment by Pornoodemon** [comment]
Haha. Found a more interesting thing.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/f642e467-4efc-439d-a129-75e1b3bcc0c9)

**Comment by Revly** [comment]
> Haha. Found a more interesting thing. During felstorm the felguard should be able to use other abilities сontrary to the spell's description ![image](https://private-user-images.githubusercontent.com/133828891/326134682-f642e467-4efc-439d-a129-75e1b3bcc0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzU2ODIsIm5iZiI6MTcxNDE3NTM4MiwicGF0aCI6Ii8xMzM4Mjg4OTEvMzI2MTM0NjgyLWY2NDJlNDY3LTRlZmMtNDM5ZC1hMTI5LTc1ZTFiM2JjYzBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQyMzQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGVjMWU5NzczMDE1OWRkMTFlYjQxOTk3YjJhZGFhYjJkMWM2MjgwZDM1ZWM2NWVjZGE4MWIxMjFhMDRhODk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOxRo1UOGIm-ymDW7G74qqaoRajGRmKIXwixMqB9SmQ)

Excelent
But steel need MainHand Weapon so Logic ???
![Screenshot_2024-04-26-18-49-16-200_com opera gx](https://github.com/gamefreedomgit/Maelstrom/assets/12503112/267ae01d-fa9f-4cd0-9533-faade6b8309e)

**Comment by Pornoodemon** [comment]
are most of the flags from Pandaria and later patches where the felguard could actually change weapons in the right hand. By the same logic, Legion Strike should have the same flag, but it doesn’t.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/cd28f28d-abe5-4f45-9ddc-4b909d97f4e8)

**Comment by Pornoodemon** [comment]
> are most of the flags from Pandaria and later patches where the felguard could actually change weapons in the right hand. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/2a40cf8d-2949-4786-a4df-3740290b0ad2)

By the same logic, Legion Strike should have the same flag, but it doesn’t. ![image](https://private-user-images.githubusercontent.com/133828891/326136557-cd28f28d-abe5-4f45-9ddc-4b909d97f4e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzY1NDIsIm5iZiI6MTcxNDE3NjI0MiwicGF0aCI6Ii8xMzM4Mjg4OTEvMzI2MTM2NTU3LWNkMjhmMjhkLWFiZTUtNGY0NS05ZGRjLTRiOTA5ZDk3ZjRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMDA0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjZlNWE3N2IzMDc2MjBjMTlhZWQwODNiN2Q3ZDcwYWUxMTNiZmI5YzJhMmNiNzQ1ODI4NDM5NWRmZWUwNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NEcWlw7DPm54odLhD56Q-L96Qa5Q6UwhyAwQsavEy8Q)

**Comment by Revly** [comment]
> are most of the flags from Pandaria and later patches where the felguard could actually change weapons in the main hand. ![image](https://private-user-images.githubusercontent.com/133828891/326136931-2a40cf8d-2949-4786-a4df-3740290b0ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzcyMzMsIm5iZiI6MTcxNDE3NjkzMywicGF0aCI6Ii8xMzM4Mjg4OTEvMzI2MTM2OTMxLTJhNDBjZjhkLTI5NDktNDc4Ni1hNGRmLTM3NDAyOTBiMGFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMDE1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjBiOTBkNDllMGNlYmNkMWE0ZmJmYzEzNjg2YzJlNmNkMWJkNzRjNzEzNWRhMjlkMDM3M2JlMGQyYjRlYTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yBx7CKyVTf1FXWbPCrhGyZFf-gQsaGCvnauf7nZfhE8)
> 
> By the same logic, Legion Strike should have the same flag, but it doesn’t. ![image](https://private-user-images.githubusercontent.com/133828891/326136557-cd28f28d-abe5-4f45-9ddc-4b909d97f4e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzY1NDIsIm5iZiI6MTcxNDE3NjI0MiwicGF0aCI6Ii8xMzM4Mjg4OTEvMzI2MTM2NTU3LWNkMjhmMjhkLWFiZTUtNGY0NS05ZGRjLTRiOTA5ZDk3ZjRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMDA0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjZlNWE3N2IzMDc2MjBjMTlhZWQwODNiN2Q3ZDcwYWUxMTNiZmI5YzJhMmNiNzQ1ODI4NDM5NWRmZWUwNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NEcWlw7DPm54odLhD56Q-L96Qa5Q6UwhyAwQsavEy8Q)

Only "Cata" no panda, no legion
https://www.wowhead.com/cata/spell=89751/felstorm

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/e173485a-7d4b-45fe-aa62-5d25110e314d)

**Comment by djesic** [comment]
I've only found this from last year https://www.reddit.com/r/worldofpvp/comments/1049i3j/you_can_disarm_felguard/ so far

**Comment by Pornoodemon** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/ee51336c-952b-4403-a650-e09e068bad1a)

**Comment by djesic** [comment]
Yeah, does not cover this case, but at least there is some confirmation that they are subject to disarm :)

**Comment by bonfax4** [comment]
Date of this comment would put it around cata prepatch or beta possibly but :

"Disarming it WORKS! I dueled a skilled Rogue who always disarmed my pet. It makes it so you can't use Axe Throw (the stun). The demon still Felstorms but it hits for like 300s, making it shit."

Not very clear but seems to imply interrupting mid cast does not cancel but instead lowers the dmg.

**Comment by Revly** [comment]
> Date of this [comment](https://www.mmo-champion.com/threads/791855-Has-anyone-recently-dueled-as-a-warrior-a-demonology-warlock/page3?highlight=Felstorm+disarm) would put it around cata prepatch or beta possibly but :
> 
> "Disarming it WORKS! I dueled a skilled Rogue who always disarmed my pet. It makes it so you can't use Axe Throw (the stun). The demon still Felstorms but it hits for like 300s, making it shit."

Excellent, there is the evidence
@UltraNix

**Comment by Pornoodemon** [comment]
Yes, but that doesn't stop the felstorm.
Most likely it just subtracts weapon damage

**Comment by djesic** [comment]
Cool, then maybe that is the actual bug?
All in all, I made the report because it just seemed so odd that nothing happens when you disarm it.

**Comment by Pornoodemon** [comment]
A significant part of the damage from Fel storm depends on the SP and mastery of the warlock and not on the damage of the weapon. Therefore, having SP 10k / subtracting the damage from the weapon of the Fel Guard itself, at best, will reduce its damage by 1-2 to and if you disarm the warlock, taking away from him approximately 3 to SP will reduce the damage from Fel strom much more.
But if you are interested in doing nonsense disarming Felguard, then this is rather your stupidity).
disarming does not dispel fel storm

**Comment by Pornoodemon** [comment]
@UltraNix  What is the base weapon damage of the Felguard?

**Comment by Revly** [comment]
1- Currently disarming Fel Storm is not reducing the damage of your Fel Storm.
2- If you disarm him before he uses ax throw, it is not disabling the throw either, (it should be disabled until the effect wears off).
3- You currently cannot use other abilities when using Fel Storm, (but they should be able to be used).

**Comment by djesic** [comment]
> A significant part of the damage from Fel storm depends on the SP and mastery of the warlock and not on the damage of the weapon Felguard. Therefore, having warlock SP 10k / subtracting the damage from the weapon of the Fel Guard itself, at best, will reduce its damage by 1-2 to and if you disarm the warlock, taking away from him approximately 3 to SP will reduce the damage from Fel strom much more. But if you are interested in doing nonsense disarming Felguard, then this is rather your stupidity). disarming does not dispel fel storm

@Pornoodemon Awesome, thanks for insulting me! I'm sure you're a wonderful person to interact with and collaborate. Thank you for choosing to take this bug report personally

**Comment by Pornoodemon** [comment]
> > Значительная часть урона от Бури Скверны зависит от SP и мастерства чернокнижника, а не от урона оружия Страж Скверны. Поэтому наличие у чернокнижника СП 10к/вычитание урона от оружия самого Стража Скверны в лучшем случае снизит его урон на 1-2 к, а если обезоружить чернокнижника, отняв у него примерно 3 к СП, урон уменьшится. от Фел Строма гораздо больше. Но если вы заинтересованы в том, чтобы заняться ерундой по обезоруживанию Стражей Скверны, то это скорее ваша глупость). обезвреживание не рассеивает бурю Скверны
> 
> @PornoodemonКруто, спасибо, что оскорбили меня! Я уверен, что вы замечательный человек, с которым приятно общаться и сотрудничать. Благодарим вас за то, что решили принять этот отчет об ошибке лично.

This is most likely a Google translator error.

**Comment by bonfax4** [comment]
> 4- You currently cannot use other abilities when using Fel Storm, (but they should be able to be used).

From videos I see the felguard can use axe toss during felstorm, but he won't resume auto-casting legion-strike until the spin is over. Unsure if forcing it to cast works.

**Comment by Pornoodemon** [comment]
By the way, in the video you can see that the ax toss and the demon leap  are different DR
https://youtu.be/fHeKCbgsMZ4?si=hM5bpsaey04JMOmq&t=426

**Comment by UltraNix** [comment]
Okay - it looks like the only effect of disarming this pet is lowered damage.

**Comment by bonfax4** [comment]
@Ultranix  Tested on cata beta and disarm stops you from using Legion strike/ Axe Toss as well. Felstorm is missing there so can't test xD. My guess is only felstorm had that weird behavior if you disarmed mid cast to keep spinning.

**Comment by UltraNix** [comment]
Fixed.
