### ISSUE TITLE
Quests with included Enthralled Val'kyr, Western Plaguelands zone

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5921]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest chane with included Enthralled Val'kyr are broken. Doing Western Plaguelands quests and I am stuck on 40/45 of that zone.
Accprding my addon information I have 12 avalible quests, but flying around I dont see new one to take or to abandone and retake.

I come to the conclusion that the chain is broken between Combat Training ID 26938 and The Battle Resumes! ID 27083.

**How to reproduce:**

**How it should work:**

**Database links:**
my view of addon https://imgur.com/a/TPDTUKv

https://www.wowhead.com/quest=26938/combat-training#
https://www.wowhead.com/quest=27083/the-battle-resumes
https://www.wowhead.com/npc=45080/enthralled-valkyr#comments

**Comment by PanJanuszek** [comment]
I am leaving you map with potential places with quests.
Zone was refactored and checked twice for both factions. You probably miss something.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/daab4d00-be3d-4d3f-ae72-f41a0fc899c7)

**Comment by MirNelthDB** [comment]
GM added me the battle resumes
And it strikes me that in this area the mouse does not point them to me so that I can interact with them. but i still open the windows of the given nps.

Even that i finished already my achievement and continue to doing quest just to view how things going on and i am on 
https://www.wowhead.com/quest=27089/ace-in-the-hole
Which in my side i got two Enthralled Val'kyr

**Comment by PanJanuszek** [comment]
find me on discord: Raknar

**Comment by MirNelthDB** [comment]
I think I messed up the order of the quests. And if there is someone who is unlocked and needs to be passed later, it becomes a mess. The only addon I use is loremaster which tells me where there is a mark/point.
