### ISSUE TITLE
Quest "Put it on" in Abyssal Depths doesn't work

### ISSUE THREAD

**Issue by Lukbexer** [gamefreedomgit/Maelstrom#5922]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest "Put it on" in Abyssal Depths. When you accept the quest, cutscene starts playing and when it ends the quest objective doesn't count itself.

**How to reproduce:**
Cutscene starts playing, it ends and your quest is done.

**How it should work:**
Cutscene starts playing, it ends and your quest is done.

**Database links:**

https://www.wowhead.com/quest=25987/put-it-on#videos

**Comment by PanJanuszek** [comment]
fixed 26.04.2024, after restart
