### ISSUE TITLE
bug quest "A Spirit Guide" - Mag'har quest line -  Hellfire pensinula - ID 9410

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5923]
**_Sounds confusing, ask clarification if needed_**

I'm using english client

**How to reproduce:**
I go to corpse start quest and follow the spirit wolf to the place where I need to complete the quest, gorkan doesn't show a question mark, if I log out and then log in near gorkan then he shows again the "?" but cant talk because he's _unfriendly_.
If I get far from gorkan as soon as he disappears from minimap the "?" disappears until I log off and log in again.

the  spirit wolf never applies the aura buff only shows for itself

**How it should work:**
The wolf should apply a buff to me, so I can speak gorkan( yellow "?" must appear) and then complete the quest

https://www.youtube.com/watch?v=ovCoEXxznPc&t=369s

**Database links:**

![image](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/e2aeff14-3567-443a-b05b-ed3f7decc899)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/39874760-730a-499b-9b28-793cd3467269)

**Comment by PanJanuszek** [comment]
fixed 26.04.2024, server restart required
