### ISSUE TITLE
Bug quest "Don't Kill the Fat One" - Terokkar forest - id 9889

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5927]
**Description:**
when unkor has low health he just becomes friendly and sits but have no dialog nor "?" so quest cant be complete 

**How to reproduce:**
Just attack Unkor, when reaches low health will become friendly and you should talk to him, but no option to talk appears.
after the failed attempt I tried to attack him again, but this time he just dies, not friendly phase and must abandon quest 

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/ac07017e-cfe8-4734-949c-f38303401270)

**How it should work:**
when he has low health becomes friendly and you cant talk to him to complete quest

https://www.youtube.com/watch?v=vakPNFiMRUQ&t

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/dc7fc9a3-a3b8-415b-ae20-4851ce7e1cd0)

fixed 29.04.2024, restart required
