### ISSUE TITLE
Bastion of Twilight - Heroic Council Bugs: Frozen Orb & P2 Transition

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#5928]
**Description:**
A prevalent bug that has been existent since Maelstrom on HC Ascendant Council are that the Frozen Orbs fixate on a single target (excluding the MT of course), and continues to chase the same player, and on the transition from P1 to P2, if you did not cleanse the Static/Gravity Core debuffs then they remain as a permanent aura on the original player(s) affected by them,

**How to reproduce:**
Transition from P1 to P2 with player(s) affected by Gravity Core and Static Overload and monitor how the buffs permanently remain on the affected targets, and watch as the same player besides the MT gets fixated by all of the Frozen Orbs.

**How it should work:**
Upon transitioning from P1 to P2, the debuffs from P1 should be removed and the Frozen Orb should not only be fixating on a single player. A **key point** with this report is to make sure that the target of the Frozen Orb cannot be the MT as this would not be a correct interaction.

**Comment by Sketish** [comment]
Upon transitioning from P1 to P2, the debuffs from P1 should be removed any proof for that ?

**Comment by UltraNix** [comment]
@clam119 We need a proof from retail it should be cleansed.

**Comment by UltraNix** [comment]
https://youtu.be/-2CO3nEULJc?t=133
Seems to be valid.

**Comment by dccdcd** [comment]
> @clam119 We need a proof from retail it should be cleansed.

The debuff cleansing part isn't true, but frozen orbs shouldn't chase the same player all throughout P2 - you can watch any video of the fight on youtube to see every new orb should pick a different target (not including the tanks).

https://www.youtube.com/watch?v=jLZJRHClFvU

https://www.youtube.com/watch?v=W_DIbqU5WVE

**Comment by UltraNix** [comment]
Fixed.
