### ISSUE TITLE
Demo Warlock / Felguard 

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#5929]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
https://www.wowhead.com/spell=89751/felstorm#comments
Contrary to the spell's description  The Felguard must be able to use other abilities while using the Fel strom ability.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/378c52ab-e5d7-46bc-9b97-25f18864ee11)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/7ab9f82e-32b0-4bfe-a8cb-bf63bd74e95b)

https://www.wowhead.com/spell=89766/axe-toss
https://www.wowhead.com/cata/spell=54785/demon-leap

Axe Toss and Demonic Leap should have different DR

https://youtu.be/fHeKCbgsMZ4?si=Q1Nk3SMkfu9Gqg51&t=431

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment]
What is demon leap ? You mean [pursuit](https://www.wowhead.com/cata/spell=30151/pursuit) ?

You can check wowhead cata for gcd category btw. If it shows has n/a it means they don't share gcd with anything but the spell itself. Pet Spells that share gcd have the same "normal" gcd category.

**Comment by Pornoodemon** [comment]
@bonfax4 
https://www.wowhead.com/cata/spell=54785/demon-leap

**Comment by bonfax4** [comment]
Ah you mean DR, my bad.

**Comment by UltraNix** [comment]
Fixed.
