### ISSUE TITLE
A bug with the Quest "A Haunting in Hillsbrad" - Maelstrom

### ISSUE THREAD

**Issue by maxstain** [gamefreedomgit/Maelstrom#5930]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest "A Haunting in Hillsbrad" is bugged and does not want to complete (Issue with NPC).

**How it should work:**
The NPC should have his quest flag activates hen you reach him, also the NPC should be walking around.

**Database links:**
video: https://www.wowhead.com/quest=28635/a-haunting-in-hillsbrad

**Comment by PanJanuszek** [comment]
fixed 29.04.2024, server restart required
