### ISSUE TITLE
Bug quest in Deepholm

### ISSUE THREAD

**Issue by Myrtara1205** [gamefreedomgit/Maelstrom#5931]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

Hello.
Want to report a bugged quest in Deepholm (On second thought, take one prisoner), Mor'norokk the Hateful is not spawning, we were at the ship waiting for at least 30min.
https://www.wowhead.com/cata/quest=26250/on-second-thought-take-one-prisoner

**Comment by PanJanuszek** [comment]
Cannot reproduce:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/28ff0785-ee77-4d00-a7e8-226266518c74)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/97539c90-ddb8-4647-abec-f9b8841fbd8d)

Checked with timer 16:59 - kill (picture 1) 
Respawn 17:01 (picture 2)
