### ISSUE TITLE
Alterac Valley School of Hard Knocks

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#5934]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The Children Week achivement School of Hard Knocks impossible to do due to issues around the Alterac Valley battleground. If you cant play it, there shouldnt be an achivement that requires playing it... 

**How to reproduce:**
Either lower the minimum player requirements for queue or just grant the achievement for those who has 3/4 and missing only AV one. Or dedicate one day to Alterac Valley and allow only this BG for a day. 

**How it should work:**
AV should be playable or there shouldnt be achivement that requires to play it... Its just unfair that this is impossible on Maelstrom server. 

**Database links:**
https://www.wowhead.com/achievement=1786/school-of-hard-knocks

**Comment by frostwave942** [comment]
as i know alterac valley only pops on weekends, also strand of the ancients seems like it doesnt work too so we cant complete <a href="https://cata-twinhead.twinstar.cz/?achievement=1785">Dinner Impossible"</a> to get the <a href="https://cata-twinhead.twinstar.cz/?achievement=1563">Chef title</a>.

**Comment by Revly** [comment]
#3278 
#3284 
Similar
 But Deathwing & Maelstrom
