### ISSUE TITLE
[World Event] Children's Week -Pet Reward Missing

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5936]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

after completing <a href="https://cata-twinhead.twinstar.cz/?quest=5502">A Warden of the Horde</a> / <a href="https://cata-twinhead.twinstar.cz/?quest=171">A Warden of the Alliance</a> this <a href="https://cata-twinhead.twinstar.cz/?item=66073">pet</a> doesn't appear among the rewards to choose. proof = <a href="https://imgur.com/a/Pu4h0IX">img</a> (tested in both sides).

also this <a href="https://cata-twinhead.twinstar.cz/?item=69648#reward-of">pet</a> from shattrath is missing the same way.

pets from shattrath aren't acc-wide neither give credit for <a href="">Veteran Nanny</a>(if u learn them with alters). i know this ach can be completed normally in 3 years, but with all this acc-wide stuff i thought we could complete it this year.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
soon

**Comment by PanJanuszek** [comment]
fixed 04.05.2024, server restart required
