### ISSUE TITLE
Quest: The Soul Cannon of Reth'hedron (Shadowmoon Valley, Terokkar Forest; TBC)

### ISSUE THREAD

**Issue by KazidosWoW** [gamefreedomgit/Maelstrom#5938]
**Description:**
You need to get the next things to complete the quest (https://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron):

2 [Felsteel Bar](https://www.wowhead.com/item=23448/felsteel-bar)
1 [Adamantite Frame](https://www.wowhead.com/item=23784/adamantite-frame)
1 [Khorium Power Core](https://www.wowhead.com/item=23786/khorium-power-core)
1 [Flawless Arcane Essence](https://www.wowhead.com/item=32822/flawless-arcane-essence)

The problem is when you talk with Sar'this (to get the Flawless Arcane Essence), he don´t summon the elementals and you can´t get the item. (https://www.wowhead.com/npc=23093/sarthis)

![Captura de pantalla 2024-05-05 125831](https://github.com/gamefreedomgit/Maelstrom/assets/166726682/7250bf6c-47d0-40bb-8489-b336bdde13e9)
![Captura de pantalla 2024-05-05 125844](https://github.com/gamefreedomgit/Maelstrom/assets/166726682/bd7b2f4b-6b3f-4286-9cd3-73697a9bebff)
![Captura de pantalla 2024-05-05 125912](https://github.com/gamefreedomgit/Maelstrom/assets/166726682/6a99246e-f86f-4bf9-92e7-058bb9f5212e)

**How it should work:**

To get the Flawless Arcane Essence, you have to to speak to Sar'this at Terokkar Forest : (44.7,42.2)
Sar'this will walk around in the camp, summoning a few elementals (air, water, earth, fire). Then his "servants" get together and summon the arcane elemental. (https://www.wowhead.com/npc=23100/flawless-arcane-elemental)

**Comment by WhitemaneChronus** [comment]
Sar'this has the option to talk to, but nothing happens as described

**Comment by PanJanuszek** [comment]
Fixed after update
