### ISSUE TITLE
[NPC] Innkeeper from Argent Tournament doesn't work

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5940]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

at least in horde tent, when u click on that <a href="https://cata-twinhead.twinstar.cz/?npc=33971">npc</a> to set ur hs there, nothing happens.

**How to reproduce:**

go to Argent Tournament ->horde tent and click on innkeeper.

**How it should work:**

we should be able to set our hs there.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 05.05.2024, server restart required
