### ISSUE TITLE
Quest ID 11677 Stop The Plague

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5941]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
In the cave "Plague Cauldron" missing and I cant use my Highmesa's Cleansing Seeds
https://imgur.com/a/mikFFXM

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=11677/stop-the-plague
https://www.youtube.com/watch?v=CDipEHxAdZI
**Database links:**

**Comment by PanJanuszek** [comment]
cannot reproduce
