### ISSUE TITLE
Bug quest "Losing ground" -  Vashj'ir - id: 25967

### ISSUE THREAD

**Issue by Pepelomb** [gamefreedomgit/Maelstrom#5942]
**Description:**
**Update: Quest can be completed but its really tricky, took me about 2 hs of trying, so this is a guide for anyone that has this problem.**

1) took quest from Wavespeaker  in cave, then go to (29,78) and took seahorse from quest, npc trigger dialog but wont complete quest, dismount in forward post, go inside building. 
2)  go again to (29,78) take again seahorse from quest, and this time seahorse get inside cave and got complete status

+Quest giver [Wavespeaker Tulra (npc=40919) : Quest can be taken in (29,78) and (51,62) . if you ride the seahorse  quest giver offers, the orc npc(forward post) will trigger dialog. but still wont complete quest. 

+seahorse will travel from quest giver to forward post, and then to cave, when it is near the entrance seahorse  bug and stuck in a weird cycle like shaking, must dismount.

+ if you use your personal seahorse, wont trigger dialog with orc npc

First time I took the quest, forward post wasn't even in correct phase(site was empty and no corpses) then I relog and got right phase but cant complete

**How to reproduce:**
Take the quest from Wavespeaker Tulra, then take the seahorse or use own seahorse

**How it should work:**
Go to forward post, some npc starts to talk, and complete the quest, next must go to Nazgrim( He is in the cave he was before the attack)

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/f9304bcc-9ebd-405a-a23f-14b7fcdf4aff)

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/0cc45542-9a45-46c6-920f-1dd580a033a0)

![imagen](https://github.com/gamefreedomgit/Maelstrom/assets/166284649/8426a9a7-0d2d-460f-9c90-cb1b6d560ec3)

**Comment by PanJanuszek** [comment]
fixed 07.05.2024, after restart
