### ISSUE TITLE
Locks Felguard (demonolog)

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5945]
I saw bug that some players use on bg:
Warlocks use Re-summon this pet to reset all Cds all the time on bg
So 30 sec cd Stun and 45 sec cd whirl (dont remember name of ability like aarms warrior weapon whirl)
Resets! U can make 2 atacks in 1 battle without exiting from combat mode just use abilities first time andd then instant re-summ felguard one more.
Also u just cast summon right after battle to reset all cds for next near clash.
Think its too OP Please fix it. Demons must have shared cds on their types.

**Comment by Pornoodemon** [comment]
It’s not a bug. pet re-summon   resets all the pet’s CD. At least before patch 4.3 it worked like that.

**Comment by frostwave942** [comment]
sadly for u it's not a bug, it's a blizz mechanic.
