### ISSUE TITLE
arcanist adyria (scryers rep)

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5947]
This NPC doesnt give repeatable task for basilisk eyes after 1. So reputation stoped....

**Comment by PanJanuszek** [comment]
This can be done only to Neutral reputation. Is that what you plan to do it? Otherwise works as intended

**Comment by PanJanuszek** [comment]
As you can see, I have modified my reputation to unfriendly, then quest appeared

**Comment by PanJanuszek** [comment]
When I hit neutral, quest dissappears
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/e1b2ea63-1f7b-460d-bf4e-e3c22e04d03f)


No issue then
