### ISSUE TITLE
Loch Modan timer quests not working properly + questionable HP of 1 mob

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Maelstrom#5948]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)
Pics for number 1 issue:
https://prnt.sc/8AoeHnia7jex
https://prnt.sc/jda_1RTeLrP8

Pics for number 2 issue:
https://prnt.sc/1BOQBKRhUO5R

**Description:**
1.Quest called "A Hunter's Boast" has timer until completion/delivery. Once timer passes quest can still be delivered.
Same goes for next quest you take after completing the one above "A Hunter's Challenge" .

2. Mob called "O'l Sooty" has 484hp and is not Elite. By the looks of WoW Head it should be elite with around 1.4k hp.
**How to reproduce:**
Reproducing issue 1: Do the quest and don't deliver it in required time. Try to complete it after.

**How it should work:**
Quest should fail after timer runs out.

**Database links:**

https://www.wowhead.com/wotlk/quest=271/vyrins-revenge  - Quest for O'l Sooty and her stats.

**Comment by PanJanuszek** [comment]
1. These quests should be removed in Cataclysm
2. He shouldn't be elite in Cataclysm
