### ISSUE TITLE
Fell to death walking out of Orgrimmar auction house

### ISSUE THREAD

**Issue by DrLooneyy** [gamefreedomgit/Maelstrom#5951]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
My character Bersorc walked out of the auction house in Orgrimmar and died randomly. According to the combat log he fell to his death.

**How to reproduce:**
Unknown, haven't tested it nor was expecting it

**How it should work:**
Should just walk fine
![Uploading Wow Bug.PNG…]()

**Database links:**

**Comment by PanJanuszek** [comment]
If you catch it once again, please re-open it. We will check mmaps.
