### ISSUE TITLE
quests in western plague lands are bugged and don't work

### ISSUE THREAD

**Issue by timedude187** [gamefreedomgit/Maelstrom#5952]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
all the quests for the argent crusade/dawn in the western plague lands are bugged. nothing I do whether its kill mobs or collect items is counting towards the quest objective. I have tried abandoning the quest and redoing it, relogging, exiting the game then coming back, and nothing i do seems to work.

**How to reproduce:**
accept one of the quests and try it out

**How it should work:**
everything being done should count towards the quest objective.

**Database links:**

**Comment by timedude187** [comment]
I figured out that when you are in a raid group, your quest objectives don't count. I think that's the issue

**Comment by PanJanuszek** [comment]
Yes, doing quests while in raid is impossible. I was, it will be on retail always :)

Not a defect, closing
