### ISSUE TITLE
Quest ID 12324 Smoke'Em Out

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5955]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Using "Smoke Bomb" in the spots not counting my 0/20 Venture Company Stragglers smoked out
I tried in/out of three spots and nothing counts.

This quest is a part of "Grizzled Veteran"

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=12324/smoke-em-out#
https://www.youtube.com/watch?v=_rmRuivU8Og

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 16.05.2024
