### ISSUE TITLE
bug in the quest moonfire huargen

### ISSUE THREAD

**Issue by lozzarpa123** [gamefreedomgit/Maelstrom#5956]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I can't complete the moonfire mission with a wargen

**How to reproduce:**
does not complete the mission when the objective is met

**How it should work:**

you practice the moonfire skill
**Database links:**

**Comment by PanJanuszek** [comment]
fixed after update
