### ISSUE TITLE
northern stranglethorn quests missing

### ISSUE THREAD

**Issue by Schinkepizza** [gamefreedomgit/Maelstrom#5959]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** the northern stranglethorn is missing quests on alliance site from rebel camp, i wanted to do the 50 quests achievement qurrently iam stuck at 38/50

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Can you share any details, what quests are missing ?

**Comment by AlxVlc** [comment]
I have 42 and I cannot see more t do the achievement

**Comment by Sketish** [comment]
As alliance or horde ? Need more details when any questchain broke.

**Comment by AlxVlc** [comment]
Alliance. I have only a quest to do with Revilgazz (the goblin captain on booty bay)in stranglethorn but is south, I don't know if is part of a chain and ends on south. The other is obsolete by blizz. It says to speak with a guy on Scarlet monastery, Joseph the crazed.Sorry about muy english, and thanks for all.-------- Mensaje original --------De: Sketish ***@***.***>Fecha: lun, 16 sept 2024, 8:24Para: gamefreedomgit/Maelstrom ***@***.***>Cc: AlxVlc ***@***.***>, Comment ***@***.***>Asunto: Re: [gamefreedomgit/Maelstrom] northern stranglethorn quests missing (Issue #5959)
As alliance or horde ? Need more details when any questchain broke.
