### ISSUE TITLE
[World Event] Argent Tournament - Bugs

### ISSUE THREAD

**Issue by frostwave942** [gamefreedomgit/Maelstrom#5961]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

after completing <a href="https://cata-twinhead.twinstar.cz/?quest=13678">Up to the Challenge</a> u can still see their <a href="https://imgur.com/a/uR10lmF">daily quests</a>, same thing happens with factions daily quests. 
i completed the dailies of Silvermoon, then i chose Undercity to continue with the tournament but their daily quests weren't unlocked but i can still see <a href="https://imgur.com/a/Jte1yqf">silvermoon dailies</a> instead. so i can't continue with the tournament.

also mounted duels sometimes not work so well and some riders of Darnassus, Stormwind, Undercity and Orgrimmar doesn't work. this could make it harder to complete <a href="https://cata-twinhead.twinstar.cz/?quest=13787">The Grand Melee</a> and <a href="https://cata-twinhead.twinstar.cz/?quest=13811">Among the Champions</a>.

<a href="https://www.youtube.com/watch?v=mYXvdt38cHU">video 1</a>
<a href="https://www.youtube.com/watch?v=nTPLkPsrlbs">video 2</a>

and the <a href="https://www.wowhead.com/wotlk/quest=13641/the-seers-crystal#comments:id=679685">quest line</a> of the black knight doesnt work, after completing <a href="https://www.wowhead.com/wotlk/quest=13634/the-black-knight-of-silverpine">The Black Knight of Silverpine?</a>, next quest <a href="https://www.wowhead.com/wotlk/quest=13641/the-seers-crystal">The Seer's Crystal</a> is not given.

**How to reproduce:**

pick a bloodelf char -> get exalted with silvermoon -> complete their daily quests at the tournament -> and choose Undercity 

**How it should work:**

at least in this case after getting exalted with some faction and earned the right to represet them in the tournament we should be able to continue with other factions dailies like Undercity for eg.

Among the Champions (WotLK Classic) -> https://www.youtube.com/watch?v=pSUCx4LPgRg
The Grand Melee (WotLK Classic) -> https://www.youtube.com/watch?v=T5l8ZlbZkNM 

(the problem aren't these quests, the problem is how the mounted duels work)

**Database links:**

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
