### ISSUE TITLE
Timothy Jones <Jewelcrafting Trainer> doesnt scaled

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5962]
Timothy Jones 
https://www.wowhead.com/cata/npc=28701/timothy-jones
still give 1 Dalaran Jewelcrafter's Token
https://www.wowhead.com/cata/currency=61/dalaran-jewelcrafters-token
for daily.
Issue was formed early but still doesnt fixed.
Thanks.

**Comment by Sketish** [comment]
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/5949
