### ISSUE TITLE
Hunter pet kills do not give credit to me

### ISSUE THREAD

**Issue by Slimshady0551** [gamefreedomgit/Maelstrom#5966]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)
Hello, as the title sais, pet kills does not count for the player

**Description:**
when hunter pet kills a mob, it does't give xp/credit to the player

**How to reproduce:**
let pet attack a monster without you engaging or hitting it
also when on defensive or assist stance and the player gets hit by a mob and the pet engages automaticly, the player doesn't get xp nor credit

**How it should work:**
the kills and/or xp should be credited to both the player and the pet ? 
idk i've seen mixed responses in the internet

**Database links:**

**Comment by PanJanuszek** [comment]
That's normal, on retail it is the same. If hunter, DK(with ghoul) wont engage you won't get credit/xp.

It's not an issue.
