### ISSUE TITLE
Clefthoof Meat (doesnt scaled 1x still)

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5967]
Hello
TBC expansion
Clefthoof Meat   https://www.wowhead.com/cata/item=27678/clefthoof-meat
from
Clefthoof Bull  https://www.wowhead.com/cata/npc=17132/clefthoof-bull
still 1x. (need x5 +)
Pls can u scale TBC good?

**Comment by Sketish** [comment]
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/5997
