### ISSUE TITLE
Valor Point Issue

### ISSUE THREAD

**Issue by hzeidan84** [gamefreedomgit/Maelstrom#5968]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** Recently i am not getting any valor points whenever i finish any heroic, only justice point, Character name is Maiia, horde dranian 

**How to reproduce:** i honestly dont know

**How it should work:**i honestly dont know

**Database links:**i honestly dont know

**Comment by Sketish** [comment]
Make a ticket ingame, GM will assist you.
