### ISSUE TITLE
Quest ID 12175 Gray Worg Hides

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5970]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
It doesn't show up for pickup and completion.
I can collect Gray Worg Hide (3) but when i go to npc Hidetrader Jun'ik, nothing happens.

**How to reproduce:**

**How it should work:**

https://www.wowhead.com/quest=12175/gray-worg-hides
**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/b69f6c26-2d0d-4ed4-8856-2572ab1220a8)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/8baaa4e1-d159-40af-80c9-4b1637bc0323)

cannot reproduce
