### ISSUE TITLE
Quest ID 12259 The Thane of Voldrune

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest is compleatable, but need to rewrite.
Right now i just go and slain the Thane Torvald Eriksson

Interaction with drake missing. I cant fly of drake and kill Thane over drake.

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/quest=12259/the-thane-of-voldrune

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after restart
