### ISSUE TITLE
Quest ID 12661 Infiltrating Voltarus

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5973]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
1. Using Stefan's Horn in area the summoned NPC droped under the map.
2. I am with Scourge Disguise and I can talking with Gorebag without limits. 
If I talk with Gorebag before taking quest ID 12664 Dark Horizon from Overlord Drakuru I am stuck in the air before fly path end of flying fiend. Same problem is if I take quest Dark Horizon first and then talk with Gorebag. Still stucking in the air, but quest 12664 Dark Horizon is compleated now. Here is where I am stuck in the air https://imgur.com/a/CN3w1m3 . When i Logout of my account and login latter i am on the ground and can talk with Overlord Drakuru and compleate Dark horizon.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
fixed after update
