### ISSUE TITLE
Quest ID 12676 Sabotage

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5975]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Тo complete this quest you must pass and Quest ID12690 Fuel for the fire.
1. Drakkari Skullcrushers Slain (60) must count when i am at Scourge Disguise and control Bloated Abomination using him as minion.
Currently now i can slain drakkari skullcrushers without Scourge Disguise and without controlling minion just in normal.
Have to rewrite.

2. Quest ID 12710 Disclosure need a bit cosmetics and visuals like chains of orange trolls :) and path of skeleton till the middle of the map.

3. Because of that all of this quests are part of Guru of Drakuru Achievement and every main quest have to be finished with Stefan Vadu. As i mention before Stefan's Horn drops under the map - Reliquary of Pain. So every main quest have to be finished with Stefan Vadu in Ebon Watch.
**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=12676/sabotage
https://www.wowhead.com/quest=12690/fuel-for-the-fire
https://www.wowhead.com/quest=12710/disclosure
https://www.youtube.com/watch?v=ndCNE4bNAZI
**Database links:**

**Comment by PanJanuszek** [comment]
fixed after update, i have left condition so that player can kill manually these trolls. I have heard so many complains about time spent upon this quest
