### ISSUE TITLE
[Deathwing] Warlock PVE 2 set bonus is not working in Arena (soloq) for path of war characters.

### ISSUE THREAD

**Issue by pizza-with-pineapple** [gamefreedomgit/Maelstrom#5977]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Wartorn Balespider's 2 set bonus is not working in arena for path of war characters.
The 2 set reads:
(2) Set: Your periodic damage has a chance to summon a Fiery Imp to assist you in battle for 15 sec.

It works fine outside of arena on training dummies, but inside arena it does not proc even once no matter how long the game goes or how many DoTs you put up.

**How to reproduce:**
equip 2 set, join soloq and DoT targets, it does not proc even once.

**How it should work:**
2 set should work in arena just like it does outside arena.

**Database links:**
https://wowpedia.fandom.com/wiki/Balespider%27s_Burning_Vestments

**Comment by pizza-with-pineapple** [comment]
edit: 
forgot to mention, it should have a 45sec ICD so it should proc atleast once per minute.
atm it does not proc at all in arena. even in 4-5min+ games

https://www.wowhead.com/spell=99220/item-warlock-t12-2p-bonus#comments

**Comment by Afgann** [comment]
fixed
