### ISSUE TITLE
DK quest controlling eye not working properly again

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Maelstrom#5979]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

[Death Comes From On High]
**Description:**
Eye moves way too slow. 

**How to reproduce:**
Do the quest [Death Comes From On High] and see how slowly eye moves. It takes it more than 2 minutes to arrive where you can control it.

**How it should work:**
It should be faster by 1 minute.
https://www.youtube.com/watch?v=2P6Kdwy3He0&ab_channel=WoWQuests

**Database links:**
https://www.wowhead.com/wotlk/quest=12641/death-comes-from-on-high

**Comment by PanJanuszek** [comment]
fixed after update
