### ISSUE TITLE
A Dream of a Better Tomorrow Quest Item Bug

### ISSUE THREAD

**Issue by kedjek** [gamefreedomgit/Maelstrom#5981]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest Dream of a Better Tomorrow quest does not allow players to pick up Mechanized Air quest item in the hut.

**How to reproduce:**
Accept quest

**How it should work:**
Should allow players to pick up quest item in hut

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/c7125fee-93c1-4240-9e7a-1651cb0b0ac9)

cannot reproduce,
