### ISSUE TITLE
Quest ID 12072 Blightbeasts be damned

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5982]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I am using Valnok's Flare Gun, Kor'kron war rider summoning, but I cant mount him and use to compleate quest.
Currently quest can be finished without this mount just target Anub'ar Blightbeast and kill alone.

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=12072/blightbeasts-be-damned
https://www.youtube.com/watch?v=OR-_l7K5TYI

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 21.05.2024, after restart
