### ISSUE TITLE
The Stones of Vekh'Nir quest not able to be completed. Deathwing server

### ISSUE THREAD

**Issue by mckamyv** [gamefreedomgit/Maelstrom#5983]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Can not turn in The Stones of Vekh'Nir quest (Burning Crusade quest). Turn-in NPC question mark remains gray and quest turn in window does not do anything if you press the 'Continue' button.

**How to reproduce:**
Obtain the quest item 'charge' it then attempt to turn it in to Dertrok

**How it should work:**
Like any quest should allow turn in upon completion of requirements.

**Database links:**
Quest ID: 10565
https://www.wowhead.com/cata/quest=10565/the-stones-of-vekhnir

**Comment by PanJanuszek** [comment]
fixed 23.05.2024, after restart
