### ISSUE TITLE
Ethereum Prisons (doesnt respawn)

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5985]
![WoWScrnShot_052324_020729](https://github.com/gamefreedomgit/Maelstrom/assets/154531435/8ec322c2-c4b1-40eb-a9f7-3f4e374c310c)
Ethereum prisons doesnt respawn.

It still empty.
But need to be like this sphere 
https://www.wowhead.com/cata/spell=35349/opening-ethereum-prison#used-by-item

**Comment by PanJanuszek** [comment]
fixed 23.05.2024, after restart
