### ISSUE TITLE
Ornak Fleet Boat Bug

### ISSUE THREAD

**Issue by djembesolobird** [gamefreedomgit/Maelstrom#5987]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The boats pathing is messed up; the boat rides fine at first but then spazzes out mid way.

**How to reproduce:**
Just speak to Ornak & get a ride.

**How it should work:**
Sails to the fleet smoothly.

**Database links:**

https://streamable.com/o4l1l0

**Comment by PanJanuszek** [comment]
fixed after update
