### ISSUE TITLE
My pj 

### ISSUE THREAD

**Issue by Eduardo021205** [gamefreedomgit/Maelstrom#5988]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Hello, I need you to revive my character or send him to the cemetery because I died and when I freed myself I appeared floating in the air and it won't let me teleport to the nearest cemetery, please help me, the name is Fetuchini, thank you

**How to reproduce:**

![imagen_2024-05-25_121808078](https://github.com/gamefreedomgit/Maelstrom/assets/170819408/2cb7762d-c606-42f7-b4e7-5af80095cbbb)

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
In game issue
