### ISSUE TITLE
Teldrassil Wellspring Hovel

### ISSUE THREAD

**Issue by UnknownUnitW10** [gamefreedomgit/Maelstrom#5989]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
When first arriving to this area a ! Marker appears on the mini-map with no quest giver npc present.  

**How to reproduce:**
Nothing required default bug.  Just arrive to the area.

**How it should work:**
Solution: The ! Marker is actually attached to the npc Denalan.  Starting the quest "The Shimmering Frond" & traveling to the Lake Al' Ameth will switch the ! Marker about halfway to the area & completing the quest lines should remove the ! Marker located in Wellspring Hovel.
![Screenshot_2024-05-26-14-43-25-979](https://github.com/gamefreedomgit/Maelstrom/assets/148837280/7e5998d1-8e36-49f9-a337-14597aaee891)
![Screenshot_2024-05-26-15-20-23-420](https://github.com/gamefreedomgit/Maelstrom/assets/148837280/15312a49-e3dc-45ab-ac71-9e6b3b06ff27)
![Screenshot_2024-05-26-15-22-01-314](https://github.com/gamefreedomgit/Maelstrom/assets/148837280/ca6cb5f0-cc2f-44e5-821f-9820477f873e)
![Screenshot_2024-05-26-15-22-05-180](https://github.com/gamefreedomgit/Maelstrom/assets/148837280/a9534bfe-b3d2-4af8-a038-8cafcdaf383d)
![Screenshot_2024-05-26-15-25-20-318](https://github.com/gamefreedomgit/Maelstrom/assets/148837280/f2dcf1c7-987b-46bb-9242-2648115bbe98)

**Database links:**

**Comment by PanJanuszek** [comment]
fixed after update
