### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by azkavan** [gamefreedomgit/Maelstrom#5992]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

deathwing  sever / character name : alphabeta
**Description:**do not quest  /  quest name ' all-out attack '  /  The health of quest mobs does not decrease.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Please create ticket once again. It's not clear what's the problem here.
