### ISSUE TITLE
Quest ID12274 A Fall From Grace

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5995]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Missing interaction text button with Abbot. 
https://imgur.com/a/QZive36

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=12274/a-fall-from-grace
https://www.youtube.com/watch?v=iCAnVB33RqU

**Database links:**

**Comment by MirNelthDB** [comment]
https://imgur.com/a/ts88jG1 right now is like that.

**Comment by PanJanuszek** [comment]
fixed after update
