### ISSUE TITLE
Clefthoof Calf doesnt exist?

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#5996]
Hello
I was searching for this mob 
Clefthoof Calf
https://www.wowhead.com/cata/npc=19183/clefthoof-calf
see pls his population on map in wowhead
in real i found only 1! (Mark!) mob on all area it must be.
Pls populate him.

**Comment by PanJanuszek** [comment]
Tested on retail, there are 5.
In our database there are also 5.
