### ISSUE TITLE
[Mage][PVP] Living bomb explosion activates combat mode

### ISSUE THREAD

**Issue by Crusaderz** [gamefreedomgit/Maelstrom#5998]
1. Play BG
2. Mean fire mage casts a living bomb at you
3. You get scared and run away
4. No pvp action so the combat mode ends
5. Living bomb explodes
6. In combat mode again
7. Can't mount or stealth for next 6 seconds

Mage should also not enter combat mode after the explosion

Retail video:  https://youtu.be/wyK9AXb_cog?t=420
Rogue enter stealth as soon as living bomb explodes. You can actually see stealth buff on his unit frame for a split second.

**Comment by mipanka** [comment]
blizz maked explode as DoT, new cata classic full bugs. need wait for fix it. Original cata have combat from explode

**Comment by mipanka** [comment]
https://github.com/JamminL/cata-classic-bugs/issues/471 blizz reports

**Comment by Crusaderz** [comment]
The video evidence is relevant to WOTLK. It probably worked the same way in Cataclysm, but we need to find that out for sure

**Comment by mipanka** [comment]
Old cata LB will input u in combat. Now on cata classic no, cuz bug, I provide proof from blizzard git

**Comment by Sketish** [comment]
Not a bug, we are comparing to original cata
