### ISSUE TITLE
Hot and Cold quest bug

### ISSUE THREAD

**Issue by tdaigo99** [gamefreedomgit/Maelstrom#6008]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:) https://wowpedia.fandom.com/wiki/Hot_and_Cold
[//]: # (https://www.wowhead.com/cata)

**Description:** You recieve a pickaxe where you can mine the giants, that pickaxe makes u kill a few adds and pick up essence of ice from them, it gives you max 6 and then takes the pickaxe away, once u go to Frozen iron scrap there is a chance that it can use 2 essence of ice instead of 1, and since you no longer have the pickaxe there is no way to get that 1 lost essence of ice.

**How to reproduce:** get 6 essence of ice in the quest, click one of em twice really fast if your mouse double clicks by accident or registers 2 essence's of ice. pickaxe is not in your inventory to get that 1 lost essence of ice

**How it should work:** use 1 essence of ice instead of 2

**Database links:**

**Comment by PanJanuszek** [comment]
Cannot reproduce. There is 10 sec cooldown on it.
![image](https://github.com/user-attachments/assets/124190c9-5370-41b9-980c-0c5496aa5080)
