### ISSUE TITLE
Missing NPC ID 32630 Vyragosa

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6010]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I've been flying around looking for this npc for a few months now to no avail. I haven't even seen his dead body. I'm coming to the conclusion that there is a problem with his respawn time or something in his behavior. 
Not finding the Vyragosa makes it impossible to get the Frostbite achievement.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/npc=32630/vyragosa

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/3a6434b7-8a1c-4566-897f-4e4973a147d1)

She is all the time on server, but probable someone killed it before you.

**Comment by MirNelthDB** [comment]
https://imgur.com/a/shpZXiW 
Worked 27.08.2024

**Comment by Nidhogg89** [comment]
> https://imgur.com/a/shpZXiW Worked 27.08.2024

worked what? I know where exactly that place is where you killed it, its way further from its original route where Vyra should be flying, that one is at Temple of Life which is ridiculous...

https://imgur.com/a/FEMWa6V                               .......
