### ISSUE TITLE
Argent tournament bug

### ISSUE THREAD

**Issue by Nightwiings** [gamefreedomgit/Maelstrom#6013]
[](https://www.wowhead.com/quest=13672/up-to-the-challenge)
[](https://www.wowhead.com/quest=13679/the-aspirants-challenge)

**What is happening:**
Some months back, when argent tournament have more bugs, i do those quest "up to the challenge" and "the aspirants challenge", now i show the daily quests of the silver covenant but cant choose a quest of my race " a valiant of darnassus"

**How it should work:**
i dont know if need talk with a game master in game for activate that quest for me, because i see other reports of other players can do the quest of him race but can get quest of other races.

![1234](https://github.com/gamefreedomgit/Maelstrom/assets/131043094/d5f04b7a-0733-4449-b54a-5a7fe28cced5)

**Comment by ZayHolt** [comment]
I'm having the exact same problem. I hope they fix it soon.

**Comment by PanJanuszek** [comment]
To get A Valiant of Darnassus quest:

Here is the road:

Up To The Challenge(15 Seals) -> The Aspirant's Challenge ->A Valiant of Darnassus

![image](https://github.com/user-attachments/assets/4be6a616-aaa6-44fe-97c7-5e2cc13043e6)
![image](https://github.com/user-attachments/assets/e8461139-668c-4bd4-9f66-e85f3d4ecaa3)

**Comment by ZayHolt** [comment]
> To get A Valiant of Darnassus quest:
> 
> Here is the road:
> 
> Up To The Challenge(15 Seals) -> The Aspirant's Challenge ->A Valiant of Darnassus
> 
> ![image](https://private-user-images.githubusercontent.com/398043/355371074-4be6a616-aaa6-44fe-97c7-5e2cc13043e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkwODEsIm5iZiI6MTcyMjk0ODc4MSwicGF0aCI6Ii8zOTgwNDMvMzU1MzcxMDc0LTRiZTZhNjE2LWFhYTYtNDRmZS05N2M3LTVlMmNjMTMwNDNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTFmYjJiOTVlMWE3N2M3MjBkY2ZiZGYxNTA2NjRhYjA2YzhlODA1YjJhNGU4NTIzN2EwMWE2ZjA2MGM0NDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hFZHHEcSmT0osoDYbN4YvZRcEWAnHpU5Q6uSn3AZqes) ![image](https://private-user-images.githubusercontent.com/398043/355371142-e8461139-668c-4bd4-9f66-e85f3d4ecaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkwODEsIm5iZiI6MTcyMjk0ODc4MSwicGF0aCI6Ii8zOTgwNDMvMzU1MzcxMTQyLWU4NDYxMTM5LTY2OGMtNGJkNC05ZjY2LWU4NWYzZDRlY2FhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjZmMDRjMGE4ZjI4YzVhOGI2OTRjZTQ2MDk2NWM0MTNiODc2OWY3OWU5NjJjMjNlMWUyOTc5MWJlNzY1NDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GvGmGXBKoqVSf_caDdSNuuTEP1gyZa1GaJE3RYEBeqc)

Hi, please check this problem on my issue ticket. I have explained it with all details. It is really a problem, not what you think.

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
