### ISSUE TITLE
Achivement

### ISSUE THREAD

**Issue by MissCllick** [gamefreedomgit/Maelstrom#6016]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Idk that only I have that issue.... but  achivement  A Simple Re-Quest dont work for me... it counts only one daily  and stop counting even if i do a massive amount of the same daily quests.... for example cooking - Stealing from our own , molten front - The protectors of Hyjal..... this is strange af... cuz on my alt shamm i do this achivement doing dailies from JwC  those are not reaptable day by day 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Author: afgann
Message: Core/Player: Fix 'A Simple Re-Quest' achievement criteria not counting properly. https://github.com/gamefreedomgit/Maelstrom/issues/5393 

Please recheck after server update

**Comment by PanJanuszek** [comment]
Fixed
