### ISSUE TITLE
Quest ID 10853 Spirit Calling

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6018]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The Lesser Nether Drakes seem to be my friends right now, instead of being ready to kill them.
How is now: https://imgur.com/a/gEhVc2P

**How to reproduce:**

**How it should work:**
As I understand it, after taking the quest I need to kill them to use the totem and account for their spirit.

**Database links:**
https://www.wowhead.com/quest=10853/spirit-calling

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/d719bf73-96ad-40d5-8453-25809b698c5b)

If you are friendly+ rep, you have to set at war flag
