### ISSUE TITLE
Jilanne missing NPC

### ISSUE THREAD

**Issue by Kornflex97** [gamefreedomgit/Maelstrom#6019]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** NPC Missing

**How to reproduce:** Put the Missing NPC where it should be

**How it should work:** A Npc called Jilanne in eversong voods - Fairbreeze is missing. she used to sell Pet's.

**Database links:** https://www.wowhead.com/cata/npc=16860/jilanne

**Comment by PanJanuszek** [comment]
She is there, all the time
![image](https://github.com/user-attachments/assets/1844c555-9ada-48ac-bbbd-2ea78967c7ea)
