### ISSUE TITLE
 The Day that Deathwing Came: What Really Happened

### ISSUE THREAD

**Issue by anbarreras** [gamefreedomgit/Maelstrom#6022]
](https://www.youtube.com/watch?v=Ps1plvEYpcU)
**Description:**
Problem in the quest [The Day that Deathwing Came: What Really Happened], in Badlands.

**How to reproduce:**
After you accept the quest, you cannot to anything.

**How it should work:**
You should be able to control the orc,

**Database links:**

**Comment by PanJanuszek** [comment]
Can you record a clip? What client do you use?

**Comment by jorgichu2** [comment]
Hello, there is a bug again, once what the mission asks for is done, the orc that you have to complete does not complete it, the question remains gray. 
![WoWScrnShot_091324_164159](https://github.com/user-attachments/assets/b6d265bd-784e-490b-8eff-7294eb6ef09c)
![WoWScrnShot_091324_164219](https://github.com/user-attachments/assets/c12b0781-fe59-48e4-bd9c-d531927cc4bc)
![WoWScrnShot_091324_164935](https://github.com/user-attachments/assets/190cd87f-146f-4bcf-8349-bb41da464b07)
