### ISSUE TITLE
Quest ID 10607 Whispers of the Raven God

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6024]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have the Soul Attraction buff and yet every single prophecy doesn't count as fulfilled.
How is now: https://youtu.be/NzIcaj6ukKc

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=D0tFkJAeEL0

**Database links:**
https://www.wowhead.com/quest=10607/whispers-of-the-raven-god

**Comment by PanJanuszek** [comment]
You didn't read quest description carefully. **You have to kill two Grishna arrakoa to get buff.** With buff you can loot items.

![image](https://github.com/user-attachments/assets/781d6800-72f2-4596-9a8f-a458a49ecdf6)
