### ISSUE TITLE
stuck in strange geoplane

### ISSUE THREAD

**Issue by JiangYi86** [gamefreedomgit/Maelstrom#6025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
after finish question investigate the cow at top north of stormwind. the npc andrun Wrynn dont give next mission maybe called like “they keep away from us”.and then my role stuck in a strange geoplane  cannot see my partymate  at the harbor and cannot see any npc in the harbor

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Still valid?
