### ISSUE TITLE
unjustified penalty

### ISSUE THREAD

**Issue by kunashgykun** [gamefreedomgit/Maelstrom#6026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** I received an unjustified penalty for an unfriendly player, I need a solution as soon as possible please and that there be a sanction for those types of people who make the game tedious and unpleasant, I leave attached a sample of the type of person that discriminator is

**How to reproduce:**
![Captura de pantalla 2024-07-05 174854](https://github.com/gamefreedomgit/Maelstrom/assets/174837578/96097473-89ef-4a2b-b122-f62d08b818f9)

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
This tracker is not for personal issues
