### ISSUE TITLE
Helm of the Brown Lands bug item

### ISSUE THREAD

**Issue by damienchoyhoong** [gamefreedomgit/Maelstrom#6028]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/92500062/7aad58d0-7644-4093-9bfe-ce68cff4f1ea)

**How to reproduce:**
Place cursor on this item and it will show you the wrong stats difference in the tooltip

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Clear cache and disable addons, check again. I couldn't reproduce
![image](https://github.com/user-attachments/assets/738fab1e-17a2-4c36-87c1-634ddf5c48a5)

**Comment by PanJanuszek** [comment]
Clear cache and disable addons. Couldn't reproduce
![image](https://github.com/user-attachments/assets/f4819919-ee41-486c-a974-b33aa8494122)
