### ISSUE TITLE
Change into the human form(Not a bug excatly)

### ISSUE THREAD

**Issue by owlbefineOwO** [gamefreedomgit/Maelstrom#6029]
Hello!
I'm playing as a Worgen Druid/Path of War, and I haven't finished the quest line where I learn the shape-shifting ability. I chose the racial shift of a Night Elf because, because I didn't want my character be in a Worgen form, but I accidentally pressed [Running Wild] and turned into Worgen form, and now I can't change it back. Could you please turn my character back into a human form, but without making my character learn the [Two Forms] cast?   
My ING name is Lovelybuster, i can explain more clearly if needed!

**Comment by Sketish** [comment]
Please make a ticket ingame
