### ISSUE TITLE
Quest ID 11065 Wrangle Some Aether Rays!

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6030]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Using Wrangling Rope of Aether Rays, nothing happen. I got message "Invalid target". 
How is now: https://youtu.be/DJYFgffzrHc

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=oxYIeu19M6I

**Database links:**
https://www.wowhead.com/quest=11065/wrangle-some-aether-rays

**Comment by PanJanuszek** [comment]
Works as should. You have to beat NPC below 40% to be able to use item.

**Restrictions have been removes in patch 6.0.1**
