### ISSUE TITLE
[QUEST] Argent Tournament's chain quest doesn't works prorpely

### ISSUE THREAD

**Issue by ZayHolt** [gamefreedomgit/Maelstrom#6031]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

Firstly, we have the beginning of the chain quest:
[The Argent Tournament](https://www.wowhead.com/cata/quest=13667)
When you turn in this quest, you get this [achievement](https://www.wowhead.com/cata/achievement=2756/argent-aspiration)

And then continues:

[Mastery Of Melee](https://www.wowhead.com/cata/quest=13828)
[Mastery Of The Charge](https://www.wowhead.com/cata/quest=13837)
[Mastery Of The Shield-Breaker](https://www.wowhead.com/cata/quest=13835)

And then:
[Up To The Challenge](https://www.wowhead.com/cata/quest=13672), complete the following daily quests to earn enough [Aspirant's Seals](https://www.wowhead.com/cata/item=45192) to continue. (15 seals at 5 per day)

[A Blade Fit For A Champion](https://www.wowhead.com/cata/quest=13666) or [A Worthy Weapon](https://www.wowhead.com/cata/quest=13669) or [The Edge of Winter](https://www.wowhead.com/cata/quest=13670)
[Learning The Reins](https://www.wowhead.com/cata/quest=13625)
[Training in the field](https://www.wowhead.com/cata/quest=13671)

And finally:

[The Aspirant's Challenge](https://www.wowhead.com/cata/quest=13679)
You will be offered one of these quests based on your race:
[A Valiant Of The Exodar](https://www.wowhead.com/cata/quest=13690)
[A Valiant Of Ironforge](https://www.wowhead.com/cata/quest=13685)
[A Valiant Of Stormwind](https://www.wowhead.com/cata/quest=13684)
[A Valiant Of Darnassus](https://www.wowhead.com/cata/quest=13689)
[A Valiant Of Gnomeregan](https://www.wowhead.com/cata/quest=13688)

When you turn in one of the quests above, you will get [another achievement](https://www.wowhead.com/cata/achievement=2758)

And now comes the bug:
Me, as a night elf mage, turned in [A Valiant Of Darnassus](https://www.wowhead.com/cata/quest=13689) and the rest of the chain quest simply didn't appear. It just goes back to the point where I have to get the [Aspirant's Seals](https://www.wowhead.com/cata/item=45192). And gets stuck in these three quests to catch the seals.
And the quests that should appear don't appear:
![WoWScrnShot_070624_234026](https://github.com/gamefreedomgit/Maelstrom/assets/111104406/d7137aa2-7aec-4f4d-84e4-f6b3f2430109)

And if by any chance this is useful, here are my reputations:
![WoWScrnShot_070624_234426](https://github.com/gamefreedomgit/Maelstrom/assets/111104406/e9354ce8-fedd-4a70-b1a7-d9fdced7f45c)
![WoWScrnShot_070624_234555](https://github.com/gamefreedomgit/Maelstrom/assets/111104406/233c7984-c538-4e17-934f-21fea31e812d)
![WoWScrnShot_070624_234711](https://github.com/gamefreedomgit/Maelstrom/assets/111104406/7c45be3e-e000-418f-bd29-f52bc35dea04)

And that achievement:
![WoWScrnShot_070724_000250](https://github.com/gamefreedomgit/Maelstrom/assets/111104406/bffd0dba-6371-48c3-bed4-0c926086ae7c)

**How to reproduce:**

Just do the chain quest described above.

**How it should work:**

When you get to the part about choosing a faction:
[A Valiant Of The Exodar](https://www.wowhead.com/cata/quest=13690)
[A Valiant Of Ironforge](https://www.wowhead.com/cata/quest=13685)
[A Valiant Of Stormwind](https://www.wowhead.com/cata/quest=13684)
[A Valiant Of Darnassus](https://www.wowhead.com/cata/quest=13689)
[A Valiant Of Gnomeregan](https://www.wowhead.com/cata/quest=13688)

and when you get this [achievement](https://www.wowhead.com/cata/achievement=2758), the following quests should appear:

[The Valiant's Charge](https://www.wowhead.com/cata/quest=13718), complete the following daily quests to earn enough [Valiant's Seals](https://www.wowhead.com/cata/item=44987) to continue. (25 seals at 5 per day)
[A Blade Fit For A Champion](https://www.wowhead.com/cata/quest=13746) or [The Edge Of Winter](https://www.wowhead.com/cata/quest=13616) or [A Worthy Weapon](https://www.wowhead.com/cata/quest=13742)
[A Valiant's Field Training](https://www.wowhead.com/cata/quest=13592)
[The Grand Melee](https://www.wowhead.com/cata/quest=13665)
[At The Enemy's Gates](https://www.wowhead.com/cata/quest=13847)

**Additional notes:**
Sorry for my bad English, I wrote using Google Translate, and I hope you guys fix this soon, because this chain quest is very good, and I consider it to be the best in the game, not to mention the prizes it gives. Anyway, I leave you a big hug for the best private server of Cataclysm in the world.

**Database links:**

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
