### ISSUE TITLE
Quest ID 10329 Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6032]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
On the first try, I was able to press the control console, but nothing happened. There is no text button inside. On the second try, I don't even have an iteration for the push. Subtitles missing, npcs who attack me missing.

*** I pay attention that the quests are passed as it is written in the top center of the screen, but on the right in the objects it says that it is not passed.
https://imgur.com/a/GhR3H25
Same is with Manaforge Ara, Manaforge Duro, Manaforge Cooru and Manaforge B'naar.
To avoid confusion, go back to the npc that gave you the quest and complete it.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=LkcvDAt1lU0

**Database links:**
https://www.wowhead.com/quest=10329/shutting-down-manaforge-bnaar

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/55dedf66-7d74-49d5-842b-a7668df7f1c5)
 1. Quest takes two minutes.
 2. Without quest item from Overseer Theredis it won't work

Rest is fixed
