### ISSUE TITLE
Agatha (valkyr in Silverpine Forest quests) not functioning correctly

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Maelstrom#6034]
**Description:**
There are two quests in Silverpine Forest which you do with the assistance of the valkyr Agatha - Rise, Forsaken and No Escape. Agatha is meant to be elite and is also meant to follow you, not run off attacking mobs on her own. The issue is that she is not an elite on Maelstrom server; she has the same HP as the player, which makes her quite squishy. She died once on me while I was completing Rise, Forsaken - which should be an easy quest - because mob hyperspawns mean she can't stop and heal. This also makes it impossible to complete No Escape, as you have to fight your way through elite mobs in Fenris Keep. Again, Agatha keeps dying. The only way for her to respawn is to abandon the quests and start over. Without Agatha, the leaders on top floor of the keep don't spawn and you can't complete the quest.

She also runs off attacking mobs on her own instead of following the player which, again, makes her more likely to die.

(Not as crucial but her pathing is a bit crazy and she tends to sink into the floor instead of flying. It's all just really buggy in general)

**How to reproduce:**
Just play through these quests and see for yourselves.

**How it should work:**
Agatha should be (a) elite and therefore difficult to kill, enabling you to move through the elite mobs in Fenris Keep with ease - not dying every five minutes and (b) not run off attacking every mob she sees.

**Database links:**
N/A

**Comment by Seren79** [comment]
As an update, if Agatha dies when you are doing No Escape, there is no way to get her to respawn, even if you abandon the quest and re-take it. This means you are unable to complete the quest and therefore unable to continue the Silverpine Forest questline (thanks to Blizz changing the way we quest to 'questing on rails' from Cata onwards).

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
