### ISSUE TITLE
Quest ID 10204 Bloodgem Crystals

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6041]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I use a Bloodgem Shard on the appropriate spot and I'm instantly interrupted. I have no way to cast a shard.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=Ns0efjMi-7M

**Database links:**
https://www.wowhead.com/quest=10204/bloodgem-crystals

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
