### ISSUE TITLE
The Purification of Quel'Delar CATA 

### ISSUE THREAD

**Issue by tallsian** [gamefreedomgit/Maelstrom#6042]
[80] [The Purification of Quel'Delar](Part 1)
(https://www.wowhead.com/cata/quest=24598/the-purification-of-queldelar)

**After entering the raid and using the sword to purify it, the cinematic does not appear and the sword cannot be recovered.
It cannot be completed by not picking up the sword.:**

https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by PanJanuszek** [comment]
Cannot reproduce
![image](https://github.com/user-attachments/assets/035fd8f0-e2f2-4865-99d5-31525997a835)

You didnt go to the circle

**Comment by WhitemaneChronus** [comment]
The only issue with this quest atm is asking you to be in a raid group while it shouldnt. 
Once you speak to the guard at the entrance, it should teleport you inside.

The rest of quest works fine as you showed.
![Screenshot 2024-08-08 103130](https://github.com/user-attachments/assets/1f7dc5b3-9d85-45a0-83c6-80bd238b43fa)
