### ISSUE TITLE
Quest Deep Impact

### ISSUE THREAD

**Issue by Munibandis** [gamefreedomgit/Maelstrom#6043]
(https://www.wowhead.com/cata)](https://www.wowhead.com/quest=14268/deep-impact#videos:id=69353)

**Description:**
cant see the tablets so u can't complete the Q

![image](https://github.com/user-attachments/assets/d1d652fb-7501-4b05-84fe-9d44591e113f)

**Comment by PanJanuszek** [comment]
Added 30 objects to game
