### ISSUE TITLE
Resistance is Futile/A Man Named Godfrey - problem with companions

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Maelstrom#6044]
**Description:**
The quests 'Resistance is Futile' and 'A Man Named Godfrey' in Silverpine Forest require you to complete them with both Commander Belmont and the valkyr Arthuras, partly because you need to fight your way through a bunch of elite mobs. As with the other valkyr quests in Silverpine Forest (Rise, Forsaken and No Escape), the companions are not as strong as they're meant to be. Despite being "elite", both Belmont and Arthuras only have 386 HP, less than my level 17 warlock. There are also far more elite mobs on the route than in the Blizz version of this quest, making it unnecessarily difficult. All of this means both Arthuras and Belmont die before you can reach Godfrey's body so you can't complete the quests which, again, means you can't continue on with the Silverpine Forest quest lines.

Arthuras usually dies first as she takes aggro, even when I'm using my voidwalker which has nearly 3x her HP. 

Both companions also run off to attack any nearby mobs instead of following the player's lead i.e. they are in aggressive instead of defensive mode. This should not happen.

**How to reproduce:**
Simply try doing the quests yourself.  

**How it should work:**
Both Arthuras and Belmont should be elite in more than name only. This means more HP than the player (scaling with the player's level) and they should not be dying so easily. I completed this quest on Blizz Cata Classic last week and it was a total faceroll (helped by so few elite mobs spawning in the area). Belmont and Arthuras didn't even come close to dying.

**Comment by PanJanuszek** [comment]
Scaling HP was not implemented in Cata. ~Started from MoP.
