### ISSUE TITLE
Quest bugged: On Her Majesty's Secret Service

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Maelstrom#6046]
**Description:**
Lorna Crowley does not aggro and you can't attack her. Companions do not auto-attack her either. She does not respond to anything, she just stands there doing nothing despite being flagged an an 'enemy'. Unable to complete quest as is. Tried relogging but it made no difference.

(As an aside, the three companions - Godfrey, Ashbury and that other one - are relatively squishy, despite Godfrey supposedly being a ?? boss. All three die way more easily than you'd expect them to and Godfrey does not hold aggro, as he's apparently supposed to.) 

**How to reproduce:**
Try the quest yourselves.

**How it should work:**
Lorna Crowley should be attackable, enabling the player to weaken and then capture her. 
Edit: I just completed this on Blizzard's version of Cata Classic and a short dialogue is supposed to start when you approach Lorna with the three amigos. Once this ends, she is then attackable. However, on Maelstrom this dialogue does not trigger. 

(My experience over on the official server also confirms that Godfrey, Walden and Ashbury are way too squishy here - they didn't die once fighting elite mobs whereas on Maelstrom, all three died multiple times).

**Database links:**
https://www.wowhead.com/quest=27594/on-her-majestys-secret-service
https://www.youtube.com/watch?v=qgrnfwa24rY

**Comment by PanJanuszek** [comment]
Lorna is not unattackable, because short event didn't take place. I have added condition to start event if you have all 3 guys with you.

Like this:
![image](https://github.com/user-attachments/assets/f0064da6-a916-4fae-8be0-feb5a35c9158)

Fix will be applied with next update
