### ISSUE TITLE
Menas de Eternio Burning

### ISSUE THREAD

**Issue by eltiritas** [gamefreedomgit/Maelstrom#6049]
https://www.wowhead.com/cata/es/item=23427/mena-de-eternio#mined-from-object

Las menas de eternio que deberian salir en cualquier en todo tipo de menas de Burning Crusade tienen menos probabilidad de salir que el korio y no debería ser así . Deberian subirle el porcentaje de looteo  llevo farmeando todo tipo de menas mas de 3 horas y tengo 10 barras , en el hierro vil inexistente , en la adamantita rica sale un poco y en el korio igual 

Disculpen las molestias y gracias de antemano

**Comment by PanJanuszek** [comment]
Please create ticket in English
