### ISSUE TITLE
Portal to hyjal bug

### ISSUE THREAD

**Issue by DanielGglz1518** [gamefreedomgit/Maelstrom#6050]
Hello. I can't see the portal to Hyjal and I already completed the quest chain. It's the only portal I can't see

only in mi rogue on the alliance

Rogue name: Silimex lv 85

![Portal bug](https://github.com/user-attachments/assets/7c98f633-17f0-4d55-a047-d9f4700818ba)

**Comment by WhitemaneChronus** [comment]
Open an in game ticket about this, usually the very first quest in Hyjal is missing
@DanielGglz1518
