### ISSUE TITLE
[Achievement] My Very Own Broodmother 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Maelstrom#6052]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Achievement does not complete upon completing the task.
Player must complete the Restless Brood daily quest in Deepholm within 90 seconds of striking the Resonating Crystal.

Completing the quest took 36 seconds to complete but the achievement doesnt apply.

**Database links:**
https://www.wowhead.com/cata/quest=28391/the-restless-brood
https://www.wowhead.com/cata/achievement=5447/my-very-own-broodmother

**Comment by PanJanuszek** [comment]
Fix will be applied with next update
