### ISSUE TITLE
BUG INFRALAR QUESTS 

### ISSUE THREAD

**Issue by Thundersong123** [gamefreedomgit/Maelstrom#6056]
Hello, I have a problem with the Infralarr missions, it does not let me continue the mission chain, I am trying to farm reputation in Terazane but it does not allow me to take missions, I think it is a bug, the last mission I did was: The central fragment After that they stopped giving me missions I even did the Questflag for Captain's Log mission.
My Name in Game Malestrom is Thundersong

**Comment by GM-Nightmare** [comment]
Make a ticket when this happens please and we will assist you.
