### ISSUE TITLE
Glory of the Hero

### ISSUE THREAD

**Issue by meremarlo09** [gamefreedomgit/Maelstrom#6057]
Just tried to do an achievement run with friend to try to get the Red Proto drake but we are stuck on 2 achievements which is Brann Spankin' New and The Incredible Hulk.  We killed the Scourge hulk as the achievement says but we didn't get credited and on Brann Spankin' New achievement we defended Brann without taking any damage but we didn't get credited too. Lastly we can't see Brann on the last door of Halls of Stone so we can't kill the last boss. I hope this will get fix. 

how it should work?
Defend Brann without him  taking any damage after the gauntlet players will get credited for the achievement.
After Svala Sorrowgrave kill the Scourge Hulk with her ability players will get credited for the achievement. 

https://www.wowhead.com/wotlk/achievement=2154/brann-spankin-new
https://www.wowhead.com/wotlk/achievement=2043/the-incredible-hulk

**Comment by frostwave942** [comment]
this server seems kinda abandoned the two devs (i think) are working on lich king realms so i dont think they have the time to fix something here, if u take a look at the bug tracker there are 3 and a half pages of unsolved bugs.

**Comment by PanJanuszek** [comment]
Abomination max health should be 9200, otherwise you won't get achievement

![image](https://github.com/user-attachments/assets/8950a678-331c-449d-89cc-9e5edde814aa)
![image](https://github.com/user-attachments/assets/08fd948d-fdc3-4651-b32f-504bf2d3a687)

**Comment by PanJanuszek** [comment]
Brann achievement:
- fix will be applied with next update

**Comment by meremarlo09** [comment]
Yeah my bad on Incredible Hulk it works just forgot to edit this ticket and thanks for fixing the brann achievement

**Comment by meremarlo09** [comment]
When is the next update though?

**Comment by meremarlo09** [comment]
Also I'd like to add Abuse the Ooze is bug also when we do it the ooze when they merge slimes don't transform into Iron Sludges.
