### ISSUE TITLE
The Sons of Hodir quest chain is bugged

### ISSUE THREAD

**Issue by lucascampolimm** [gamefreedomgit/Maelstrom#6058]
Description:
The Sons of Hodir quest chain is bugged.

How to reproduce:
The 'Cold Hearted' quest from the Sons of Hodir quest chain is not working. The frozen prisoners are not appearing in Dun Niffelem, only the blue dragons are present.

How it should work:
The frozen prisoners should appear.

Database links:
https://www.wowhead.com/cata/quest=12856/cold-hearted
https://imgur.com/a/FyJezJO

**Comment by PanJanuszek** [comment]
It would be nice, if GM would tell you in which phase you actually are :)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/3dca582b-be45-4538-a6c9-01e48da59dab)

I see them normally in phase 2 as I am, during quest. Maybe other people did the quest? Respawn is 2min.

![image](https://github.com/user-attachments/assets/f67d9bcb-41f7-4795-bef0-51a30f7b4652)

Can handle normally

**Comment by lucascampolimm** [comment]
They started appearing to me again. 😀
