### ISSUE TITLE
NINJA LOOT

### ISSUE THREAD

**Issue by dkarnita** [gamefreedomgit/Maelstrom#6059]
Buenos dias quiero report a un ninja este sujeto se llama ETERNALWARR esta persona ya habia loteado el item pero como no estuvo conforme con sus dados espero hasta el final y lo volvio a lotear aca tengo la captura de los dados 
![WoWScrnShot_073124_071453](https://github.com/user-attachments/assets/c7902b78-7f41-4aec-9280-336b3f592126)
espero la respuesta y gracias

**Comment by MadeinNoxus** [comment]
Github is not the ninja form or the correct place for report ninja. https://whitemane.org/ninja
