### ISSUE TITLE
Quest Gasping For breath

### ISSUE THREAD

**Issue by TomasZacharyas** [gamefreedomgit/Maelstrom#6060]
Drowning watchman cannot be saved, cant interact with them and are floating in the air out of the water. Quest cant be completed.

https://www.wowhead.com/quest=14395/gasping-for-breath

![obrázek_2024-08-03_231315890](https://github.com/user-attachments/assets/c0740ed5-557c-4d3e-a067-ae5ffb68b097)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/803cf319-f74c-4785-8939-6cd39e9fd081)
![image](https://github.com/user-attachments/assets/ef9bbbad-ff03-43fc-b021-3a388942f445)

Cannot reproduce
