### ISSUE TITLE
[Quest] The Hunter's Revenge (A 29115/ H 29227)

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Maelstrom#6062]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

Quest doesn't complete upon killing NPC [Mauti?](https://www.wowhead.com/cata/npc=52349/mauti)

**How to reproduce:**

Accept the quest go to Mauti? location and kill it. 

**How it should work:**

Quest should mark as complete after you take [Grent Direhammer](https://www.wowhead.com/cata/npc=52346/grent-direhammer) to Mauti? and kill it.

**Database links:**
Horde: https://www.wowhead.com/cata/quest=29227/the-hunters-revenge
Alliance: https://www.wowhead.com/cata/quest=29115/the-hunters-revenge

**Comment by PanJanuszek** [comment]
You have to take Grent Direhammer to Mauti corpse:
![image](https://github.com/user-attachments/assets/150fbd6c-e36d-424b-88da-dd279f62e6c5)
