### ISSUE TITLE
RE: Lost In The Deeps Quest - Pebble Wont Follow  #6048

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6065]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
This bug was marked closed but it was not yet resolved bug tracker #6048. @PanJanuszek.

Pebble still wont follow the player towards outside the cave. It wont complete the quest.

**How to reproduce:**
Get the quest:  "Lost in the Deeps"

**How it should work:**
Pebble should be following the player towards outside of the Crumbling Depths which marks the quest complete.

**Database links:**

![Screenshot_8](https://github.com/user-attachments/assets/fe53fe66-ec33-4385-ba17-94b54eba49bc)

**Comment by PanJanuszek** [comment]
Update is not on server yet.
