### ISSUE TITLE
Those Bears Up There - Daily Quest Bug

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6066]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The throw trajectory cannot be aim properly. It doesn't move vertically, it only moves horizontally.

**How to reproduce:**
Get the daily quest "Those Bears Up There"

**How it should work:**
Aiming should be controlled vertically and horizontally.

**Database links:**

![image](https://github.com/user-attachments/assets/0a803453-69df-48ef-9333-926ac88af9ea)

**Comment by PanJanuszek** [comment]
You have to press and keep Right Button on your mouse.

**Comment by chrisdomaub-dev** [comment]
@PanJanuszek  yes, I am using the "hold right click" to navigate the aim. As I have already done this DQ many times without a problem for the past months I've been playing.

Maybe its a UI bug? I will update here if it comes back again in tomorrow's DQ.
