### ISSUE TITLE
Quest "Flight of the Witergarde Defender"

### ISSUE THREAD

**Issue by 20adam24** [gamefreedomgit/Maelstrom#6067]
Hello.

This is my first bug report, so I apologize if I do something wrong.
I have a problem with the quest as in the title, the characters I have to save disappear after I approach them, and as a result the quest cannot be completed.

Regards
20adam24

**Comment by WhitemaneChronus** [comment]
Seems to be working 
![image](https://github.com/user-attachments/assets/80a230a2-e279-45b6-b65d-ee25bab8fa2c)

make sure to relog and clear your cache files.

**Comment by 20adam24** [comment]
Hi.

The cache files were deleted, the game was restarted, after saving 7 mobs the problem returned and this time deleting the files did not help. Could this be some conflict with addons?

Regards
20adam24

**Comment by WhitemaneChronus** [comment]
Well you can disable all your addons and try again. 
If you are still struggling to finish it, open a ticket in game (there's a customer support option with a "?" icon) so me or one of the GMs can look into it there.

![image](https://github.com/user-attachments/assets/b88b50ce-4344-40be-a735-5e431f47b887)

**Comment by 20adam24** [comment]
Yes i do that, still i can't finish that quest.

**Comment by 20adam24** [comment]
I try tomorrow, but i t's something wrong.

**Comment by 20adam24** [comment]
Thank you Chronos for help.

**Comment by WhitemaneChronus** [comment]
Continuing the test on live server, npcs seem to vanish, i cannot find the reason
english client / phase 1

You can see in one picture NPCs are alive but as I get close to them, they will disappear (shows dead)
![Screenshot 2024-08-10 114013](https://github.com/user-attachments/assets/c0888cf0-389b-4cca-8ae7-97d61a9842b4)
![Screenshot 2024-08-10 114248](https://github.com/user-attachments/assets/3f468654-d945-475e-ab63-6c0fc508bb8b)
