### ISSUE TITLE
Told Barad, Baradin Hold - Daily Quest Givers Stacked Position Bug

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6068]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

The daily quest giver npcs are stacked together, making it very hard and annoying to click the right npc to get a quest or complete a quest.

**How to reproduce:**
Go to Tol Barad > center of Baradin Hold. try to get some quest.

**How it should work:**
they're supposed to be beside each other not stacked together.

**Database links:**
![image](https://github.com/user-attachments/assets/2a8dc2ad-f6f9-4acb-b7b6-8d3ebd2844d1)

**Comment by PanJanuszek** [comment]
According to retail info there is one main quest giver plus 1 of 3 possible random choose for defender team.

Actually it looks like stucked because all are available from start, which is an issue. Pushing fix.

**Comment by MirNelthDB** [comment]
When i did this quests before a months ago it was the same for me too. And in that time Tide spread them :)

**Comment by PanJanuszek** [comment]
fixed after update
