### ISSUE TITLE
Prince Anduin keeps following me without any quest's involved with him

### ISSUE THREAD

**Issue by StannIv** [gamefreedomgit/Maelstrom#6069]
I need help, prince Anduin Wrynn keeps following  me  and  its been like  this for several days. I don't have  any quests involved with him and  I completed everything  he had to offer  as quests, yet still he's always with me. I would  love to be removed from me as  this just  gets more annoying  then it was.

**Comment by PanJanuszek** [comment]
Do you have quest My Son, the Prince in your quest log?

**Comment by PanJanuszek** [comment]
I have checked twice. Without these quest Anduin will not show up. So you have to complete them.
