### ISSUE TITLE
Game tracks low lvl quest all the time

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6070]
**Description:**
The game tracks and shows quest that is defined as "low lvl quest" even if you don´t have tracking option for low lvl quests activated.
The low lvl quests are displayd on the minimap and abow the quest givers head, they look just like a quest that is within your lvl region.

**How to reproduce:**
Lvlel up a bit and travel to a starting zone and see if quest appear on minimap.

**How it should work:**
You should not need to see all low lvl quest if you don´t activly want to track them.

**Comment by PanJanuszek** [comment]
Can you send your pics? I can't reproduce.
![image](https://github.com/user-attachments/assets/6e888787-bb30-4c6c-8ee7-aafc5777cebb)
![image](https://github.com/user-attachments/assets/3d51811b-1f4f-4d4e-978e-3f6d62f42466)

**Comment by Hellbringar** [comment]
Hello again! 

Thanks for your fast response! 

Here are some pictures that show that the low level quest is still being shown above the head of the NPC even if your not tracking them but the problem with low level quest show up the minimap without tracking on have been fixed it seems! :)

![WoWScrnShot_081824_211301](https://github.com/user-attachments/assets/e7aa8dd2-4450-4f42-a980-c9a8fa5c73ba)
![WoWScrnShot_081824_211309](https://github.com/user-attachments/assets/107f3017-267c-436b-ab2e-303dbae9e2bd)
![WoWScrnShot_081824_211315](https://github.com/user-attachments/assets/39cdca9e-6537-4304-8481-0f9e1bc2fca7)
![WoWScrnShot_081824_213455](https://github.com/user-attachments/assets/9a5a1209-2984-4a88-8ab8-f8ef7f42f2c3)
![WoWScrnShot_081824_213500](https://github.com/user-attachments/assets/7d8fbb22-6985-4017-a627-e9f60128071f)

**Comment by PanJanuszek** [comment]
Ok, we have to separate two things here. On cata you didn't have 'Trivial quest' switch. This is what you are looking for. Up to WOD 'low-level' quest switch only affected Minimap(radar) and didn't update actual point of view on your client side. So we are not able to hide them actually.
