### ISSUE TITLE
You Are Rakh'likh, Demon - Missing Rakh'likh - Blasted Lands

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6073]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
- Rakh'likh is nowhere to be found, I talked to Deathly Usher and was teleported to the top of Rise of the Defiler location, but rakhlikh is nowhere to be found.

**How to reproduce:**
get the quest "You Are Rakh'likh, Demon, speak with Deathly Usher, get to the top of Rise Of The Defiler.

**How it should work:**
After speaking with deathly user, you are teleported to the top, Rakhlikh is supposed to be there.

**Database links:**

![image](https://github.com/user-attachments/assets/c9390fa3-fb41-4c79-ba55-2ac6cdfcf826)

**Comment by PanJanuszek** [comment]
Ok here is the tip how it works:

1. Player click on gossip to start
2. If there is no other player - you summon both of NPC's to event
3. If there is any player, then you are getting teleported there
4. You can't start event if second is played.
5. If Loramus Thalipedes dies, then you can start new event.

**Comment by WhitemaneChronus** [comment]
Adding it here for the record, following these steps works fine on PTR but on live server the issue persists.

![Screenshot 2024-08-14 112936](https://github.com/user-attachments/assets/08891afd-c0e4-43b0-ad8b-3ca7bbc6fb68)

**Comment by PanJanuszek** [comment]
Added some debug conditions for live server, please check after update

**Comment by WhitemaneChronus** [comment]
![image](https://github.com/user-attachments/assets/8d0bdb2a-b775-4c9b-b9bc-7d460e4e1463)
Working fine now, Thank you.
