### ISSUE TITLE
Fuselight Ho! Quest is bugged.

### ISSUE THREAD

**Issue by Clovkworknait** [gamefreedomgit/Maelstrom#6076]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** I just went to go talk to Eddie to report in for the fuselight ho! Quest and after selecting "Fuselight Ho! A blank quest page shows up. Pressing continue does nothing. I tried reloging  and it's still broken. 

**How to reproduce:** Try to talk to Eddie maybe? 

**How it should work:** I think he supposed to give you new quests for that region. 

**Database links:**

**Comment by PanJanuszek** [comment]
I dont see any problem here.

![image](https://github.com/user-attachments/assets/f4719564-99f0-4a5f-a217-aaa7ef118979)
![image](https://github.com/user-attachments/assets/a8bdb073-f409-4530-bedd-91c315e78af8)
![image](https://github.com/user-attachments/assets/8e3296d0-1fc3-45ba-9d5f-733bf375d8a7)

**Comment by PanJanuszek** [comment]
Cannot reproduce your behavior. Try to clear cache and try again

![image](https://github.com/user-attachments/assets/bbb3670f-78c8-4cbf-8764-7a1cd24838ea)
![image](https://github.com/user-attachments/assets/ec6e57fa-9349-4cf5-b44e-5e267c9fd2b0)
