### ISSUE TITLE
Archaeology rewards more experience than it should

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Maelstrom#6078]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

It appears that finding fragments or crafting artifacts is giving too much experience considered the rate on Maelstrom. 
Here's an image after setting the experience rate to 0.5
![image](https://github.com/user-attachments/assets/dc3a4af0-9597-433c-aded-e037641d5d45)

and the default rate:
![image](https://github.com/user-attachments/assets/7e40b38c-355e-4164-ac19-a998b2973d34)

**How to reproduce:**

Take Archaeology as a profession and find fragments in dig sites.

**How it should work:**

Experience rewards must be adjusted with server rates.

**Comment by Hellbringar** [comment]
Is there any progress being made on this?
I´m still waiting and the joy the game brings is reduced since i can´t experiance the archaeology part of the game!

**Comment by Hellbringar** [comment]
Still missing out alot of gameplay since this bugg is not fixed! Please prioritize this issue!

**Comment by Hellbringar** [comment]
@WhitemaneChronus I can now confirm that this issue have been resolved after I created a second report that contained your report's information!

Thanks for creating the report in the first place!

**Comment by Afgann** [comment]
fixed
