### ISSUE TITLE
Skullcrusher the Mountain

### ISSUE THREAD

**Issue by laggerdude** [gamefreedomgit/Maelstrom#6079]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have comleted all quest requirments but cant end it by speaking with Kurdan Wildhammer.

**How to reproduce:**
Just do what needs to be done and npc wont speak with you.

**How it should work:**
The big red button "continue" in npc menu should open dialogue with npc and he will show you rewards. 

**Database links:**

**Comment by laggerdude** [comment]
![Uploading WoWScrnShot_081424_193841.jpg…]()

**Comment by laggerdude** [comment]
![Uploading WoWScrnShot_081424_193841.jpg…]()

**Comment by PanJanuszek** [comment]
Tested on both sides, along with GM on PTR realm. Both of us succeded.

![image](https://github.com/user-attachments/assets/44839b7d-ad84-4cff-b8ff-7956cc231dcd)

It seems that you have tried to complete it second time somehow, faction change? asking GM to add quest once again?
