### ISSUE TITLE
Flight of the Wintergarde Defender (12237)

### ISSUE THREAD

**Issue by Aline19fr** [gamefreedomgit/Maelstrom#6080]
Hi, 

I can not do the quest "Le vol du défenseur de Garde-Hiver": the PNJs vanish before I can reach theam.

Thank you for the help!

**Comment by PanJanuszek** [comment]
I wonder if you can record clip, there is no invis, phase there. I would like to see it

**Comment by PanJanuszek** [comment]
fixed with next update
