### ISSUE TITLE
[Quest] Steel Thunder - Sea Dog Crate - The crates does not add up in the bag or to the quest tracker

### ISSUE THREAD

**Issue by ryzealex1** [gamefreedomgit/Maelstrom#6081]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

Location: Silverpine forest

**Description:**
When the crate is clicked, The item does not go to the bag, due to that the quest progress is not tracked 

**How to reproduce:**
1. Take the quest
2. Reach the location.
3. Click on crates
Notice that the crates does not go to the players inventory.

**How it should work:**
1. Take the quest
2. Reach the location.
3. Click on crates
Notice that the crates does go to the players inventory.

**Database links:**

**Comment by PanJanuszek** [comment]
One quest accept, you get follower:

![image](https://github.com/user-attachments/assets/82cee98e-7cff-4272-928a-23fa6ab32db6)

If he is nearby and you click the box:

![image](https://github.com/user-attachments/assets/a7736260-32c4-4ad2-a1e1-31002742acd4)

Closing as not an issue

**Comment by ryzealex1** [comment]
Please note that this issue still persists if the quest is taken while mounted the minion that carries the cargo does not spawn
