### ISSUE TITLE
[Quest[ Saving Yenniku - North Stranglethorn Vale - Using the Soul gem Yenniku does not complete the quest

### ISSUE THREAD

**Issue by ryzealex1** [gamefreedomgit/Maelstrom#6082]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

Video: https://www.youtube.com/watch?v=EsR1WTibgIc

**Description:**
Using the Soul gem Yenniku does not complete the quest

**How to reproduce:**
1. Navigate to N-STV
2. Take the Saving Yenniku quest.
3. Navigate to the quest marker.
4. Use the soul gem on Yenniku
Notice that the quest does not complete when the gem is used.

**How it should work:**

Use the soul gem on Yenniku
Notice that the quest does complete when the gem is used.

**Database links:**

**Comment by GM-Nightmare** [comment]
![image](https://github.com/user-attachments/assets/3b5fcee0-8f38-46dc-96c9-8f52bc4db6b5)
it's working fine and as intended.

**Comment by ryzealex1** [comment]
Now works as intended, thanks for the fast response.
