### ISSUE TITLE
Impossible to complete the quest "Ascending the Vale"

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6085]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest called "Ascending the Vale"is a quest that gets auto-completed when you arrive at a certain location on the map, but that doesn't happen. (I know i´m at the right place since i have dubblechecked on WoWhead where the quest is supposed to get completed)

**How to reproduce:**
Travel to the questmarker on the map and see that the quest dosen´t get completed.

**How it should work:**
You travel to the location and the quest get´s auto-completed in you questlog

**Comment by PanJanuszek** [comment]
fixed with next update

**Comment by Hellbringar** [comment]
When is the next update?
How often do you update?

**Comment by PanJanuszek** [comment]
maybe today or tomorrow, gaga knows
