### ISSUE TITLE
no me sale el portal a monte hyjal

### ISSUE THREAD

**Issue by enmanuel20202** [gamefreedomgit/Maelstrom#6086]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
no me sale el portal a monte hyjal

**How to reproduce:**
no me sale el portal a monte hyjal

**How it should work:**
no me sale el portal a monte hyjal

**Database links:**
no me sale el portal a monte hyjal
![Uploading kdtukdtyuktuykldt7kdty7ldtul57ld57l5t76l57io5t67ui67582347isryjxcfghjkdsrtytksr5d7ks4567ikow4s6ir56ujdryjdryj546ier56jk456k.png…]()

**Comment by PanJanuszek** [comment]
To unlock Mount Hyjal portal you have to finish first quests, depending on your faction:

![image](https://github.com/user-attachments/assets/2e279832-812d-4a87-8601-8726499ee600)


After "As Hyjal Burns" you will see portal in capital city
