### ISSUE TITLE
I can't get out of Ahn'Quiraj

### ISSUE THREAD

**Issue by Sitoo84** [gamefreedomgit/Maelstrom#6087]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I was flying over Ahn'Quiraj and i died on the sea so now i can't come back to life because the angel is not where it is supposed to be.

**How to reproduce:**
If you cpuld make me back to life or put the angel in his place, please.

**How it should work:**
There should be an angel where i appear.

**Database links:**

**Comment by PanJanuszek** [comment]
fixed with next update
