### ISSUE TITLE
Misión "La Prueba de las Sombras" no se puede hacer

### ISSUE THREAD

**Issue by Cocolinodeep** [gamefreedomgit/Maelstrom#6088]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
No cuenta las sombras a la hora de meterlas en las marcas moradas, razon por la cual no puedo hacer la misisón.

**How to reproduce:**
Dejo un ejemplo de como se deberia ejecutar la misión https://www.youtube.com/watch?app=desktop&v=PpRKwEGVuZ0

**How it should work:**
Deberia contar las sombras y acumularse al pasar por encimas de los circulos hasta completar las 20 acumulaciones de sombras
![Velhka](https://github.com/user-attachments/assets/4587cb0a-c21d-4305-a40d-e9a59320cd67)

**Database links:**
https://www.wowhead.com/es/quest=24479/la-prueba-de-las-sombras

**Comment by PanJanuszek** [comment]
Unfortunately, if I see correct, you didn't even take quest. You don't have it on your quest list on the right.

Second thing, I have taken Spanish client and tested myself.

![image](https://github.com/user-attachments/assets/c7b78967-30af-457a-9a39-b3ab2885acad)

My conclusion is that you don't have our client. If you provide me a clip with prove that you are using our client + you will do this quest from scratch, then please re-open this ticket.
