### ISSUE TITLE
[QUEST] Resupplying the Excavation - Loch Modan

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6090]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
resupplying the excavation doesn't mark completed when you find the dwarves,
when you reach the dwarves, its supposed to mark complete.

**How to reproduce:**
get the quest "Resupplying the Excavation"

**How it should work:**
When you find the dwarves, they are engaged in a battle and when you go near the dwarves the quest should mark complete.

**Database links:**

![image](https://github.com/user-attachments/assets/2236a63a-98a8-4f2a-8190-538203369a28)

**Comment by PanJanuszek** [comment]
fixed after update
