### ISSUE TITLE
NPC - Sassy Hardwrench

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Maelstrom#6092]
Copy pasted from ticket:

Triple or more stacked npcs with the same name in:
Warchief's Lookout, npc: Sassy Hardwrench
https://imgur.com/a/wUF07N1

**Comment by Sketish** [comment]
Can't replicate on main or ptr, also imgur is not working

**Comment by WhitemaneIsa** [comment]
Tbh the screenshot just showed the 3 NPCs stacked, https://www.wowhead.com/en/npc=38387

Considering this NPC has a lot quests and relates to phasing etc. that's probably what's causing it. But for now I'd say this is low prio anyway as it doesn't hinder the quest progression, it's just an ugly phasing bug.

**Comment by PanJanuszek** [comment]
Ehmm... gm off??
