### ISSUE TITLE
Addon "Gatherer" sets wrong deposits for minerals

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6093]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have noticed that my addon "Gathered" marks some mining deposits wrongly, silver veins get´s the name and icon of the tin vein on the map and the gold ore get´s the iron deposits.

I saw that you recently fixed a similar problem withe dark iron so I hope i can get help with this as well

**How to reproduce:**
Mine some gold or silver ore and see what the games says it has marked on your map

**How it should work:**
Solver veins gets silver marks & gold ores gets gold ore marks

![WoWScrnShot_082124_211121](https://github.com/user-attachments/assets/a5a9fccf-99da-4f63-ab32-f6b2824601aa)
![WoWScrnShot_082124_211135](https://github.com/user-attachments/assets/0dcea79a-cc23-4114-9ed3-ab1216b4e84e)

**Comment by Sketish** [comment]
From what site you downloaded addon. I need to check this

**Comment by Hellbringar** [comment]
Hello!

Thanks for such a quick response!

It´s originally downloaded from curseforge - https://www.curseforge.com/wow

**Comment by Sketish** [comment]
It's mainly because silver vein is rare spawn of tin vein and same is for gold vein which is rare spawn of iron vein. That's why its not  a server bug just addon thing
