### ISSUE TITLE
[QUEST ITEM] - Renn's Supplies - Recover The Cargo Quest

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6094]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The item Renn's Supplies are provided for the quest "Recover the Cargo". It should contain a Salvage Kit and a Repaired Diving Gear.
I tried opening Renn's Supplies many times by retaking the quest, but all of them was empty.

I cannot complete the quest since the items from the supply are needed.

**How to reproduce:**
1. Get the quest Recover The Cargo.
2. Open the provided package "Renn's Supplies"

**How it should work:**
Renn's Supplies should contain:
1x Salvage Kit
1x Repaired Diving Gear

These items are needed to complete the quest "Recover The Cargo"

**Database links:**
![image](https://github.com/user-attachments/assets/c99c2816-d15c-4e04-a747-5765f3ef20ec)

**Comment by Sketish** [comment]
https://www.wowhead.com/quest=27237/recover-the-cargo link to quest

**Comment by Sketish** [comment]
![image](https://github.com/user-attachments/assets/5ef1ec61-16c9-49c8-935e-f627d6e2e476)

I'm also able to loot items from box.

**Comment by PanJanuszek** [comment]
Fixed after update
