### ISSUE TITLE
Northern Barrens - Leveling Quest Chain - Helga Bloodeye

### ISSUE THREAD

**Issue by jbakes97** [gamefreedomgit/Maelstrom#6100]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Northern Barrens - Leveling Quest Chain - Helga Bloodeye
After completing the quest to kill the Greater Plainstrider to collect beaks "Plainstrider Menance", the quest chain does not generate the next quests. You should start the one to go kill the wolves, ride the kodo etc. Started quest from the Warchief's board. 
https://www.wowhead.com/cata/npc=34258/halga-bloodeye
**How to reproduce:**
Made Tauren, took the quest from the board, verified we had low level quest tracking on. Quest chain stopped after the beak quest.

**How it should work:**
You should start the one to go kill the wolves, ride the kodo etc.

**Database links:**

**Comment by PanJanuszek** [comment]
H [5-30] [Plainstrider Menace](https://wowpedia.fandom.com/wiki/Plainstrider_Menace) (Side quest, not necessarily part of the chain)

Is side-quest, not main quest.

![image](https://github.com/user-attachments/assets/ba7414cc-f9d2-4955-a436-2b5eadd3a31d)

**Comment by PanJanuszek** [comment]
Another thing, this guy in OG starts also chain.

![image](https://github.com/user-attachments/assets/db4989af-7751-410a-ade4-e03f23a66b00)

**Comment by PanJanuszek** [comment]
So it seems that these 2 quests should direct you to the same conclusion.

**Comment by PanJanuszek** [comment]
Fixed after restart
