### ISSUE TITLE
Questgiver for daily cooking quests in Stormwind City have teleported up to a nearby roof

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6101]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Questgiver for daily cooking quests in Stormwind City have teleported up to a nearby roof

**How to reproduce:**
Go to the questgiver for daily cooking quests in Stormwind City

**How it should work:**
Questgiver should be standing on the ground near a cart

**Database links:**
![WoWScrnShot_082524_012338](https://github.com/user-attachments/assets/9da251a5-c412-43e7-b0f8-d1bab6db8667)

**Comment by GM-Nightmare** [comment]
Fixed it , make a ticket if it happens again please!

**Comment by Sketish** [comment]
Not a bug, just one player is trolling npc's
