### ISSUE TITLE
Throne of the Tides - QA run

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6107]
1.Naz'jar Spiritmender - healing wave should heal for 50% as in prenerf dungeon.
NPC is also missing hex spell
https://www.wowhead.com/cata/npc=41096/nazjar-spiritmender#abilities;mode:heroic

2.Ozumat tentacles shouldnt go through wall and should be marked as enemy npc
https://youtu.be/WhUyJPMGBIM?t=165

3.Naz'jar Invader are missing Bubble Shield spell
https://www.wowhead.com/cata/npc=39616/nazjar-invader#abilities;mode:heroic

4.Cinematic when clicking console is missing a lot compared to retail
https://youtu.be/WhUyJPMGBIM?t=867

5.Faceless Watcher should be immune to cc

6.Mindbender Ghur'sha
Absorb Magic - it should absorb all magic dmg taken and heal for triple amount of absorb. Currently you can break this absorb

7.Ozumat encounter
3 Vicious Mindlasher should spawn during phase 1. Currently only one spawn.

8.Lady Naz'jar
Watersprot tornado shuld spin player to the wall, currently its  releasing player after 1 second

9.Commander Uthulok should destory Corals(gameobject)
![image](https://github.com/user-attachments/assets/45217dce-4c0f-49fb-8741-0fe7a4ac7cc9)

10.Ozumat is not kidnapping Neptulon after completing encounter

**Comment by PanJanuszek** [comment]
Fixed after update
