### ISSUE TITLE
Heroes of the horde quest bug

### ISSUE THREAD

**Issue by kuervo1** [gamefreedomgit/Maelstrom#6109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I was doing the "Heroes of the horde!" quest and when Orkus is supossed to call Kasha to get me a ride to Tarren Mill to finish the quest, it just never happened. I've tried everything to get it to work but Kasha never shows up :(

**How to reproduce:**

**How it should work:**
Kingslayer Orkus says: Tell me when you are ready and we will go!

You then will have to talk to Orkus and tell him you are ready to go. He will promptly jump at the Stormpike Battle Master and kill him in one shot, and then immediately engage the trio at the tower..

Kingslayer Orkus yells: GET THE PLANS AND GO!
Kingslayer Orkus yells: CAN YOU SMELL WHAT THE LOK'TAR IS COOKIN'?

After you loot the corpse and get the Alliance Battle Plans...

Kingslayer Orkus yells: KASHA, GET <NAME> OUT OF HERE!
Kingslayer Orkus yells: FORGET ABOUT ME, KASHA! GO!

**Database links:**
https://www.wowhead.com/cata/quest=28400/heroes-of-the-horde

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/b3423fb6-aa6c-4837-bc2d-28a500e18270)
![image](https://github.com/user-attachments/assets/68c3af44-b517-4476-8103-be4f3c7b8cc1)

**Comment by PanJanuszek** [comment]
Any chance that you were on mount?

**Comment by WhitemaneChronus** [comment]
The state of this quest is confirmed to have issues on live server.
Player has done the quest chain properly and does have the item, alliance battle plans. however kasha never appears and they are unable to complete the quest.
