### ISSUE TITLE
The Stonecore

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6112]
1.Stonecore Warbringer - cleave dmg hits for 3k looks a bit undertuned

2.Stonecore Berserker - Spinning Slash each hit should apply dot. It look's like dopt have cap of stacks or player is not getting each time
 he got hit. I wasn't able to past 4 stacks when on retail getting 8 stacks was normal for melees.

3.Corborus - melee dmg is way too low, he hits leather player for 17-18k when on vidoes he hit plate tank for about 25-28k
Animation during Borrow is messed up, boss model shouldnt appear above ground.
https://youtu.be/K6FIFSYALPU?t=48

4.Crystalspawn Giant- melee dmg is also undertuned.On video he hits for about 15-18k plate tank. Currently its 3k into leather class

5.Stonecone Flayer- should be stunable + their melee dmg also too low.Should do twice amount as now.
https://youtu.be/K6FIFSYALPU?t=155

6.Geting hit by stalactite during gauntlet event deals 0 dmg to player. Should hit for around 100k

7.Slabhide - he should melee tank for around 17-20k

8.Stonecore Brusier - melee dmg is too low

**Comment by PanJanuszek** [comment]
I dont see your point about Corborus animation, i have seen for jumps with earth effect on ground. Nothing special beside it.

**Comment by Sketish** [comment]
> I dont see your point about Corborus animation, i have seen for jumps with earth effect on ground. Nothing special beside it.

Trying to replicate on PTR, Before there were 2 models 1 above ground and 1 burrowed jumping. Currently there is only one displayed so look's like it's fixed.

**Comment by PanJanuszek** [comment]
Fixed after update
