### ISSUE TITLE
The Lost City of Tol'Vir

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6113]
1.Oathsworm Pathfinder hits for 8 damage - should be scaled up

2.Oathsworn Axemaster - missing Skull Crush spell
https://www.wowhead.com/cata/npc=44922/oathsworn-axemaster#abilities;mode:heroic

3.General Husam - Bad Intentions was never casted

4.Missing Augh fight there
![image](https://github.com/user-attachments/assets/0003f6b9-09ba-4c29-a8ce-49a0bc3e1ab8)
https://youtu.be/2V7HYEsaCyc?t=517

5.Lockaw
Frenzied Crocolisk are hitting cloth user for 2k. Currently its hitting for 600-700
Boss is never casting Viscious Poison

6.Augh is missing roleplay after killing Lockmaw
https://youtu.be/0GtZWTFbW1o?t=348

7.Augh is not casting whirlwind during encounter.

8.Siamat- Wailing Winds shouldn't push down players from platform.

**Comment by PanJanuszek** [comment]
Fixed after update
