### ISSUE TITLE
Quest: The Crucible of Carnage: The Bloodeye Bruiser!

### ISSUE THREAD

**Issue by ootxc** [gamefreedomgit/Maelstrom#6114]
Gurgthock in the Twilight Highlands is supposed to offer quest The Crucible of Carnage: The Bloodeye Bruiser! starting the arena quest chain. Although, Gurgrthock is not offering any quests.

https://www.wowhead.com/quest=27863/the-crucible-of-carnage-the-bloodeye-bruiser

**Comment by PanJanuszek** [comment]
Fresh horde player:
![image](https://github.com/user-attachments/assets/9c1284f6-9026-4351-9e52-396fcc056786)

Fresh ally player:
![image](https://github.com/user-attachments/assets/1f28986a-b84f-470f-bafe-194fe50e9988)

**Comment by PanJanuszek** [comment]
Cannot reproduce

**Comment by PanJanuszek** [comment]
If any other player did fail or abandon quest, you have to wait for NPC despawn, before starting new event. Cooldown 60s.
