### ISSUE TITLE
BUG ICC 4TO BOSS (NO DEJA ACTIVAR Y EL BOSS NO APARECE)

### ISSUE THREAD

**Issue by Rexzio** [gamefreedomgit/Maelstrom#6117]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

Mi nombre en el juego  es Riplek,server Maelstrom
**Description:**La banda de ICC de 10 normal,en el cuarto jefe no deja activar siendo lider,ni pasando el liderazgo a otro de la faccion contraria,y sencillamente no deja continuar,incluso al activar el jefe no aparece. Por favor podrian ayudarnos

**How to reproduce:**La banda de ICC de 10 normal,en el cuarto jefe no deja activar siendo lider,ni pasando el liderazgo a otro de la faccion contraria,y sencillamente no deja continuar. Por favor podrian ayudarnos

**How it should work:**La banda de ICC de 10 normal,en el cuarto jefe no deja activar siendo lider,ni pasando el liderazgo a otro de la faccion contraria,y sencillamente no deja continuar. Por favor podrian ayudarnos

**Database links:**La banda de ICC de 10 normal,en el cuarto jefe no deja activar siendo lider,ni pasando el liderazgo a otro de la faccion contraria,y sencillamente no deja continuar. Por favor podrian ayudarnos

**Comment by Sketish** [comment]
Please translate to english
