### ISSUE TITLE
 [Faerie Fire] my feral casting and chage form to worgen/human

### ISSUE THREAD

**Issue by CAPLEITE** [gamefreedomgit/Maelstrom#6120]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Hello
I have a bug in my feral druid, dual talents.
primary talents= ok
secundary talents =bug when i cast Faerie fire

**How to reproduce:**
 My feral, i  made it with the same talents(primary and secudary), the same glyphs, but when I use [Faerie Fire] with primary talents I don't lose the feral form, but when I use [Faerie Fire] with secondary talents (with cat or bear form) I immediately stop being feral and enter human/worgen form.

**How it should work:**
primary talents = secudary talents

**Database links:**
wow cataclysm/ aliance/ druid therena

**Comment by Sketish** [comment]
Could you pleas share screenshot of your talents and glyphs ?

**Comment by CAPLEITE** [comment]
I apologize for the inconvenience, I've been playing WoW for years (+15 years) and I never realized that in Druid there are 2 [Faerie Fire (Feral)] and [Faerie Fire], in Feral you have to use the feral one.

Problem solved, Thanks.
