### ISSUE TITLE
Of Keys And Cages (Quest)(Howling Fjord)

### ISSUE THREAD

**Issue by Whirlwind89** [gamefreedomgit/Maelstrom#6121]
https://cata-twinhead.twinstar.cz/?quest=11231

All of the cages in the area are not clickable at all.

How it should work: 

Keys are obtainable from the mobs in the are but cages themselves are not clickable at all, so quest can not be completed...

https://cata-twinhead.twinstar.cz/?quest=11231

Please fix it... Thank you..

**Comment by PanJanuszek** [comment]
Fixed after update
