### ISSUE TITLE
Grim Batol

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6122]
1.General Umbriss- he should melee tank for around 20-25k per swing, currently it's hitting leather user for 18k
2.Valiona is flying inside textures instead of standing on the ground which breaks Devouring Flames visual+hitbox
![image](https://github.com/user-attachments/assets/03fa306b-88d6-4ce3-a7e3-949c74802b11)
3.Valiona should leave combat when she reach 20% and fly away
https://youtu.be/xiP1v7ug1EE?t=543
4.Faceless Corruptor(trash before last) is not casting any of abilities : Umbral Mending,Twilight Corruption on eggs,Siphon Essence on players

**Comment by PanJanuszek** [comment]
4.Twilight Corruption on eggs
This is cosmetic spell used during his patrolling path

**Comment by PanJanuszek** [comment]
Fixed after update
