### ISSUE TITLE
Prot warrior useless tank on raids

### ISSUE THREAD

**Issue by Armodeus95** [gamefreedomgit/Maelstrom#6123]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[[//]: # (https://www.wowhead.com/cata)](https://www.wowhead.com/spell=76857/mastery-critical-block)

**Description:**
The critical block not work on the prot warrior.

**How to reproduce:**
My prot warr use shield block add 30% block chance. If 100+% block chance not stop the incoming melee attacks. Now the prot warr a useless tank on raids.

**How it should work:**
Raise your shield, blocking all melee attacks against you for 6 sec.
Shield Block rating - Block rating is no longer a stat in the game. Instead, a Protection[ Warrior](https://www.wowhead.com/cata/class=1/warrior) Warrior will use the new stat Mastery to increase its chances to block an attack.

**Database links:**
https://www.wowhead.com/cata/guide/classes/warrior/protection/tank-overview-pve

**Comment by Sketish** [comment]
Need more details, mastery is not working at all or just in specific scenario ?

**Comment by Armodeus95** [comment]
> Need more details, mastery is not working at all or just in specific scenario ?
> 
> Currently testing on ptr and its working

It doesn't work, I played the prot war with the content, it wasn't useless like here.

**Comment by Sketish** [comment]
So show me what is not working, on ptr you have block and critical blocks working.

**Comment by PanJanuszek** [comment]
Waiting for info next 7 days, otherwise closing
