### ISSUE TITLE
Shadowfang Keep Heroic

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6124]
1.Ghostly Cook are very rarely using Tenderize ability
https://www.wowhead.com/cata/npc=47232/ghostly-cook#abilities;mode:heroic
2.Baron SIlverlaine:
Razorclaw the Butcher - Butcher Drain drain effect is not working
Spectral Rush was never casted by Razorclaw
Rethilgore spawned twice on single cast
![image](https://github.com/user-attachments/assets/7695c38c-5652-4867-a71f-50d5cb660196)
3.Commander Springvale pull range is a little bit too high, players should be able to enter his room without pulling boss

**Comment by PanJanuszek** [comment]
Fixed after update
