### ISSUE TITLE
Halls of Origination

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6126]
1.Temple Guardian Anhuur
Player are able to interact with Beacon of Light before encounter start so it break script

2.Earthrager Ptah
Raging Smash is not hitting other players than main tank.
Boss should submerge at 50% transition, currently his model stays atop
https://youtu.be/A9Cj37lpyY4?t=33

3.Gauntlet even to Anraphet
Cd's are resseted every miniboss kill, Should only reset after killing boss.
All Wardens should be immune to cc.
Stone Trogg Pillager should respawn every 25-30seconds

4.Anraphet
Crumbling Ruin is not applied to all players after each cast of Alpha Beams or Omega Stance

5.Setesh
Boss is not using Reign of Chaos ability at all.
Chaos Blast is casted only once per fight.
Seed of Chaos are not spawning on the ground.
https://www.wowhead.com/npc=39732/setesh
6.Ammunae
Noxious Spores should damage Bloodpetal Blossom for 15% of their hp per tick.

7.Isiset
Veil of sky is not reflecting magic dmg.

8.Sun-Touched Servant- adds should split into 2 smaller elementals upon death Sun-Touched Sprite and then split into Sun-Touched Spriteling.Each split should do aoe dmg around
https://youtu.be/8w7382enTfM?t=1693

8.Rajh
Sun orb is always casted on tank instead of random player

**Comment by PanJanuszek** [comment]
@Sketish please remember one fact. If you are testing it as solo, most of the spells are not activated because they are not designed for tanks. Keep that in mind

**Comment by PanJanuszek** [comment]
3.
Stone Trogg Pillager -> correction every 1min -> 1min15sec

**Comment by PanJanuszek** [comment]
Fixed after update
