### ISSUE TITLE
Anatoly will talk - quest WOTLK

### ISSUE THREAD

**Issue by Vraeor** [gamefreedomgit/Maelstrom#6127]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest doesn t work:  https://www.wowhead.com/wotlk/quest=12330/anatoly-will-talk

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/quest=12330/anatoly-will-talk#videos:id=938

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after update
