### ISSUE TITLE
Bastion of Twilight

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6129]
1.Halfus Wyrmbreaker
Proto-Behemoth Scorching Breath should do 12k fire dmg per tick, currently it;s 4,5k + animation of breath is missing
![image](https://github.com/user-attachments/assets/1ff8d261-459d-42cb-b714-19598db319bb)
2.Valiona and Theralion
When player is under aura 92890 and is getting hit by Dazzling Destruction or Deep Breath it should kill player. Currently it's not working
![image](https://github.com/user-attachments/assets/13adcafb-d60d-4bfc-906d-e753e7d0a55a)
![image](https://github.com/user-attachments/assets/66256a29-dfce-4cce-b76d-6ba02156b930)
3.Facelesss Guardians ID 45676 should have desyned  Pooled blood casts.
4.Sinestra
Calen is not regenerating mana when he is consuming his health
https://www.wowhead.com/cata/spell=87323/pyrrhic-focus
When warrior is charging right egg sometimes he fell under textures.

**Comment by PanJanuszek** [comment]
1. 12k is for 25normal and both HC. Did you test it on 10N?

**Comment by Sketish** [comment]
It was tested on 10 heroic

**Comment by PanJanuszek** [comment]
Well I am testing it on 10HC:

![image](https://github.com/user-attachments/assets/0bc4e17f-7f02-46b4-a49e-45ebfe013e16)

And looks ok. Please check again.

10 & 25 Normal - 8100
10  & 25 HC - 12000

**Comment by PanJanuszek** [comment]
2. As you can see in Twilight Shift I've been hit for 500k during Twilight Shift. Without debuff (2nd screen)
![image](https://github.com/user-attachments/assets/316de446-e432-4510-ac15-be37691d74a3)

![image](https://github.com/user-attachments/assets/1233bfca-b22e-47cc-8342-19dd846e8853)

**Comment by Sketish** [comment]
> 2. As you can see in Twilight Shift I've been hit for 500k during Twilight Shift. Without debuff (2nd screen)
>    ![image](https://private-user-images.githubusercontent.com/398043/365434455-316de446-e432-4510-ac15-be37691d74a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY1NDYsIm5iZiI6MTcyNTc5NjI0NiwicGF0aCI6Ii8zOTgwNDMvMzY1NDM0NDU1LTMxNmRlNDQ2LWU0MzItNDUxMC1hYzE1LWJlMzc2OTFkNzRhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMTUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2JlMTIzNmE0NGM2Y2FhNzczYmQzNWFhMWQ4NzZkODRmMjQ2YjZiNzM0ODY1ZTc4ZjcwNjlkZWNjYmM3MTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JLaZjoyI8L0DdaAuIsG5Urp6gno-cAa4TmpYPUYRBYs)
> 
> ![image](https://private-user-images.githubusercontent.com/398043/365434926-a2e6434b-7bf9-41f5-a65f-1bdb6cb9d510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY1NDYsIm5iZiI6MTcyNTc5NjI0NiwicGF0aCI6Ii8zOTgwNDMvMzY1NDM0OTI2LWEyZTY0MzRiLTdiZjktNDFmNS1hNjVmLTFiZGI2Y2I5ZDUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMTUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjc0N2Y2NjYzMDFmMzIyODM5ZmVkZTNkYTc1YTUyYjcxOTUwODY4OGQwZWE2MjAwMzk0MzQwNDhmMzM3ZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HX8YTfzFmjfchWLyg6TUJuvka-FPsEpfigHxGApFqDE)

Then it will most likely kill player, only depends if cheat death,cauterize can save player from that

**Comment by Sketish** [comment]
> Well I am testing it on 10HC:
> 
> ![image](https://private-user-images.githubusercontent.com/398043/365433864-0bc4e17f-7f02-46b4-a49e-45ebfe013e16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY3ODMsIm5iZiI6MTcyNTc5NjQ4MywicGF0aCI6Ii8zOTgwNDMvMzY1NDMzODY0LTBiYzRlMTdmLTdmMDItNDZiNC1hNDllLTQ1ZWJmZTAxM2UxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMTU0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWM4MjFhNjA3MDhiYmVkY2FlM2Q1MWU5ZmMwZjRiODkyYzE3MzRmNjIzNTZiOWE1NDRkMTc3MmM5ZWNjZDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BFLfW_RrSdNHRbYDdXG8pmm_q3JSmpHGG0W6SdT0a0U)
> 
> And looks ok. Please check again.
> 
> 10 & 25 Normal - 8100 10 & 25 HC - 12000

Found the Issue:
Basic spell is doing 12k dmg but when players release Orphaned Emerald Whelps, they should reduce dmg of that spell by 750 per whelp, there should be 8 whelps so its 6k dmg reduction. Scorching Breath is ticking for 4,5k instead of 6k(12k basic -6k from whelps).There should be 8 whelps but there are only 6 in cages
![image](https://github.com/user-attachments/assets/c64c6bbe-76df-4d3b-8ba7-f528c58d9839)

https://www.wowhead.com/cata/guide/raids/the-bastion-of-twilight/halfus-wyrmbreaker-strategy
https://youtu.be/GrM5G-Yfi18?t=13

**Comment by PanJanuszek** [comment]
Yes it's ticking 4.5k on normal 10&25 -> 8100 - (6*600) = 4500. Yes, number of whelps are wrong but calculations are ok with reducing damage. Whelps are the issue here :)

**Comment by Sketish** [comment]
It was ticki

> Yes it's ticking 4.5k on normal 10&25 -> 8100 - (6*600) = 4500. Yes, number of whelps are wrong but calculations are ok with reducing damage. Whelps are the issue here :)

![image](https://github.com/user-attachments/assets/136ff9c4-0316-4a35-85a4-567eaf690072)
on 10 heroic its ticking for 4,5k post whelps

**Comment by PanJanuszek** [comment]
Fixed after update
