### ISSUE TITLE
[QUEST] - Ignition

### ISSUE THREAD

**Issue by nusvo** [gamefreedomgit/Maelstrom#6130]
**Description:**
The quest Ignition in Uldum is bugged, the orbs that the Guardian spawns fall through the floor and once you kill it, it doesn't drop the Lens of the Sun, which is required to finish the quest.

**How to reproduce:**
Just do the quest

**How it should work:**
The orbs should spawn and be clickable to kill the Guardian quickly and he should drop the Lens of the Sun once killed.

**Database links:**

**Comment by PanJanuszek** [comment]
Fixed after update
