### ISSUE TITLE
Misión "La Prueba de las Sombras" no se puede hacer

### ISSUE THREAD

**Issue by Cocolinodeep** [gamefreedomgit/Maelstrom#6132]
[//]: # https://www.youtube.com/watch?v=rVwiUi4To40
[//]: # https://www.wowhead.com/es/quest=24479/la-prueba-de-las-sombras

**Hola de nuevo, intento realizar la misión **prueba de las sombras** en el reino **Maelstrom** pero no genera las acumulaciones al pasar las sombras por las regiones resaltadas. en esta ocasion puse la quest para que se visualizara  en el apartado de seguimiento de objetivos**

**Debo pasar las dombras atra vez de las regiones sein que me toquen y de esta manera acumular **
 cargas

**Debo pasar las dombras atra vez de las regiones sein que me toquen y de esta manera acumular **
 cargas**

**Adjunto video en el cual se puede ver que la mision no se ejecuta**

https://github.com/user-attachments/assets/4bd2ed74-974b-49f2-9a93-b6a22534074e

https://github.com/user-attachments/assets/aee75837-6e00-44ba-b6bd-0a9bca447b33

**Comment by Sketish** [comment]
Could you please translate this to english?

**Comment by Cocolinodeep** [comment]
Hello again, I'm trying to do the shadow quest test mission in the Maelstrom realm but it doesn't generate the stacks when passing the shadows through the highlighted regions. This time I set the mission to display in the target tracking section, as seen in the image.

**I must pass the shadows through the regions without them touching me and in this way accumulate 20 charges

I must pass the shadows through the regions without them touching me and in this way accumulate 20 charges

I attach a video in which you can see that the mission is not executed. I ask for your help please.
