### ISSUE TITLE
Transmog not available for Blood Elf Warlock level 31

### ISSUE THREAD

**Issue by windyweather** [gamefreedomgit/Maelstrom#6136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Trying to use Transmog station in orgrimmar as Blood Elf Warlock level 31. All items are grayed out and no wardrobe of choices appears. Some items equipped are green and blue. 

**How to reproduce:**
IDK - but a low level character that has seen some blue and green items should be able to use Transmog, RIght?

**How it should work:**
Transmog should work for level 31 character that has seen some blue and green gear items over the course of their existence.

**Database links:**
https://wowpedia.fandom.com/wiki/Transmogrification

I did about an hour's work searching for a rule that would prevent me from using transmog based on my current character and could not find any reason that transmog should not work. Limited choices of course, but it should work.

Here's a video showing my experience:
https://youtu.be/t4JOms0cxOE

**Comment by SexyPancake** [comment]
Working as intended, you already got answered by the lead GM and many users. Cataclysm transmog system was the first iteration and you are linking the current system.
