### ISSUE TITLE
BUG ON FIGHT BOSS WARMASTER - ALERT PRIORITY

### ISSUE THREAD

**Issue by jeanpyere** [gamefreedomgit/Maelstrom#6138]
LOOK image, we can stun sapper 

![image](https://github.com/user-attachments/assets/eb8ce47f-5ed5-4252-b351-9e247bc80c4f)

**Comment by jeanpyere** [comment]
bugueed in normal  e  heroic mode

**Comment by Sketish** [comment]
Yes, Sapper is ccable, stuns,slows,disorient works on him

**Comment by PanJanuszek** [comment]
stun and slow is allowed, other should be immune

**Comment by jeanpyere** [comment]
new bugued, after first wipe, sapper not doing damage on boat, 100% ignored!
