### ISSUE TITLE
Deepholm

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6142]
1.Aggra speech is not displayed when flying.
https://youtu.be/iLTaYTlCDNU?t=22
2.Blizzard did change that its group credit so people can't grief each other
https://www.wowhead.com/quest=26250/on-second-thought-take-one-prisoner
3.This quest The Forgemaster's Log is not popping out after completing https://wowpedia.fandom.com/wiki/Question_the_Slaves
https://www.wowhead.com/quest=26260/the-forgemasters-log
4.Quest Maziel's Ascendancy is not popping out automatically after completing Maziel's Revelation
https://www.wowhead.com/quest=27102/maziels-ascendancy
5.Currently quest https://wowpedia.fandom.com/wiki/The_Twilight_Overlook is on autocomplete, players should be force to fly to NPC so questchain dont break.
6.Stormcaller Mylra is missing question mark on completing quest Big Game,Big Bait
![image](https://github.com/user-attachments/assets/e3dd780b-adb3-4e81-a209-0731e34589af)
7.the world pillar fragment wow quest - Abyssion abilities are not beign casted or deal 0 dmg
Shado nova has 40y range and it's not hitting when staing near drake
Rift Barrage or Twilight Breath is never casted
https://wowpedia.fandom.com/wiki/Abyssion
8.There are multiple Aggra;s wondering around
![image](https://github.com/user-attachments/assets/84751125-c7e3-495a-955e-8330aacfece3)
![image](https://github.com/user-attachments/assets/d9e994f9-defd-430e-a4ac-2e9b2dae2feb)
9.Take him to the Earthcaller - there is missing rp when Flint is approaching Earthcaller Yevaa
https://youtu.be/kmfbqxP9Mv8?t=29
10.There is duplicate of quests if 1 is obtained from event( quest appear on right side on screen to pick up) and 2nd one from real npc that should offer quest.
![image](https://github.com/user-attachments/assets/caa86f1e-eb09-4b0b-807b-c29253154679)
11.Sealing the Way - building already look sealed before using quest item
![image](https://github.com/user-attachments/assets/a9df6de0-3080-44f0-8218-00660a6e52e6)
https://youtu.be/ZxhBOhQtWvQ?t=51
Stone Trogg Digger should be aggresive towards player and stoneharth Defenders and Earthen Geomancers
12.Keeping the off the Front
Friendly npc's should be able to kill waves that are close to catapults.
Fungal Terror hp looks too big, on video 1 shot of catapult is enough to kill them
https://youtu.be/YKOnodHl8xs?t=24
13.Reactivate the Constructs - after clicking on Conctruct it should aggro on enarby trogg and attack him
https://youtu.be/YhNIzxXpKFw?t=43
14.Rescue the Stonefather... and Flint - missing RP during fight
https://youtu.be/Zznc0jlaKmE?t=30
15.On even Ground - Servant of Therazne should die when is knocked down
https://www.youtube.com/watch?v=Kem1l4XQ9ug&ab_channel=Bue
16.Imposing Confrotation - there is no rp when using quest item
https://www.youtube.com/watch?v=hnucUqXK3eI&ab_channel=Bue
17.Crumbling depths location - missing Collosal Gyreworm npc
https://youtu.be/mDTUsSRbXIE?t=44
18.Kor the Immovable should be stucked in ground
https://youtu.be/U2OeJ9C0L50?t=51
19.Putting the Pieces Together
When player is clicking on Dormant Stonebound Elemental it should reform into living elemental
https://youtu.be/b9ZG8kUdc84?t=65
20.Don't stop moving - there are no Stone Drakes around quest zone
https://youtu.be/1511J6y2SWA?t=37
21.Hard Falls- when drake is hitting ground he should have around 30% of max hp. Currently they have full hp
https://youtu.be/bjOFItgyppE?t=26
22. Terath should throw player on Boulder Platform during quest https://wowpedia.fandom.com/wiki/Resonating_Blow
23.After completing A Head full of Wind - wind devil is still following player
24. Those NPC https://www.wowhead.com/npc=43368/verlok-shroomtender are not dropping  Berlok Miracle-Grow for ques thttps://wowpedia.fandom.com/wiki/Corruption_Destruction
25.Therazane faction is not fighting vs Troggs
https://youtu.be/2U4B9qlPc6k?t=48
26.Audience with the Stonemother
Therazane says: And what then? Will you leave Deepholm to its denizens?
Earthcaller Torunscar says: We'll leave. We've no desire to be stayin' where we're not welcome.
Therazane says: I'm glad you're at least that perceptive.
Therazane says: I propose this: We will march on the Twilight cult and extinguish any utterings of Deathwing's name from this realm. Your Earthen Ring will march with us.
Therazane says: You do this, and I will send Gorsik to the temple with our piece of the World Pillar.
Therazane says: Seal the rift and leave this place.
Earthcaller Torunscar says: We'll be doin' exactly that then. Ya have our tanks, Stonemother.
Therazane says: Save your thanks. We march upon the Twilight Precipice as soon as our forces are gathered. I expect to see you on the battlefield.

There is some issue with Therazane quotes. She is asking twice "And what then? Will you leave Deepholm to its denizens?"

27.Therazane faction is not fighting with twilight one
![image](https://github.com/user-attachments/assets/3a34bb9f-4f39-41fb-a909-ea1ebfcfdcdf)

28. During quest Twilight Flight - Zoltrik should have 75% when he is on drake, currently he is at 100%.Also drake dissmount player when combat end instead of taking him on top of temple
https://youtu.be/tFkvI_X9OQY?t=100
29.Undying Twilight - there are no friendly npc to help
https://youtu.be/ob0Lwv2rH2Q?t=34
30.This quest should be offered automatically after completing Undying Twilight
https://wowpedia.fandom.com/wiki/The_Binding
31.The Binding - High priestess Lorthuna should be on the ground not on the broken pillar.There are no enemy Twilight NPC;s near center.
32.High Priestess Lorthuan shouldnt change model into elemental
![image](https://github.com/user-attachments/assets/2429f65f-3649-4f2b-b09c-092d9f6576ea)
https://youtu.be/q1TzlXIgJEk?t=27
![image](https://github.com/user-attachments/assets/03cf1980-4d21-4f88-99c6-f0b03e238e29)
33.This "cinematic" doesnt occur in game at all + missing ending RP between Shaman and Therazane
https://youtu.be/q1TzlXIgJEk?t=120

**Comment by PanJanuszek** [comment]
Fixed after update
