### ISSUE TITLE
Quest 27857 - We're Under Attack! is not working

### ISSUE THREAD

**Issue by Humanbasher** [gamefreedomgit/Maelstrom#6143]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Phase don't change after acceptin the quest

**How to reproduce:**
Accept the quest.

**How it should work:**
Phase change after accepting quest, enemy "Marshtide Invaders" npc=46869 should appear

**Database links:**
https://www.wowhead.com/cata/quest=27857/were-under-attack

**Comment by PanJanuszek** [comment]
Fixed after update
