### ISSUE TITLE
Quest in Crucible of Carnage

### ISSUE THREAD

**Issue by Gnollmann** [gamefreedomgit/Maelstrom#6145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Hello!
There is an information that some players (including me) face the next situation: after cancellation of the first quest in quest chain of Crucible of Carnage (that in Twilight Highlands) an NPC (a goblin Gurgthock) who gives this quest does not give it anymore. It seems bugged - that is why I write this text.

**How to reproduce:**
To take a quest and delete it after "dismissing in competition" (for example, running from battlefield).

**How it should work:**
After deletion this quest should be available to get from NPC again.

**Database links:**
https://www.wowhead.com/quest=27863/the-crucible-of-carnage-the-bloodeye-bruiser

**Comment by PanJanuszek** [comment]
NPC has 60s cooldown after fail == when NPC summoned will despawn. Then he can give you back quest.

**Comment by Gnollmann** [comment]
> NPC has 60s cooldown after fail == when NPC summoned will despawn. Then he can give you back quest.

Sorry, I haven`t written that after "dismissing" I returned to NPC a lot later than after 60 seconds. I`ve checked him a couple of minutes ago and still can not take this quest.
