### ISSUE TITLE
A Fall From Grace: Quest bugged

### ISSUE THREAD

**Issue by EvanBlaze** [gamefreedomgit/Maelstrom#6147]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest cannot be turned after completion.

**How it should work:**
Every part of the quest goes well except for the end, after the abbot suicides, you should go back to Agent Skully and complete the quest, but the button to complete does not actually complete it and cannot be finished. 

**Data,Links**
![WoWScrnShot_091124_232210](https://github.com/user-attachments/assets/dc8b315c-8cae-451f-ae64-7b930c0c423e)
![WoWScrnShot_091124_232226](https://github.com/user-attachments/assets/0738d7c3-a019-44f1-a303-2b8372244cf5)

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by EvanBlaze** [comment]
Amazing Thanks!!
