### ISSUE TITLE
Achievement: Master of the Molten Flow -- Flamewaker Shaman part

### ISSUE THREAD

**Issue by Nidhogg89** [gamefreedomgit/Maelstrom#6149]
Hi, I've been trying to finish this achievement for a while, it simply doesn't give me credit for the Flamewaker Shaman part to complete achievement.
I've tried all different strategies that came up to my mind, I didnt damaged him at all, I've let him die from the Flamewave several times, then I tried to lower his hp so that he can die from Flamewave's hit. But nothing worked, I've seen that this particular achievement had issues in the past, so please take a look at it and fix it. I cant get Veteran of the Molten Front achievement and a title without this one, its frustrating for an achi hunter, believe me it really is...

https://cata-twinhead.twinstar.cz/?achievement=5871
https://cata-twinhead.twinstar.cz/?npc=53093
https://cata-twinhead.twinstar.cz/?spell=98210

Best regards by Xodus

**Comment by Whirlwind89** [comment]
I totally agree with this issues, please fix it.

**Comment by PanJanuszek** [comment]
Fixed after update
