### ISSUE TITLE
Mision bug ID: 10588

### ISSUE THREAD

**Issue by Baltramar** [gamefreedomgit/Maelstrom#6151]
I was completing the Oronok Heartglen quest chain in Shadowmoon Valley. I finished the entire quest chain, but Oronok didn't give me the last quest in the chain. Quest ID 10588

![WoWScrnShot_091324_171345](https://github.com/user-attachments/assets/acba41a4-5af4-49f6-bda8-b942a1529f36)
![1](https://github.com/user-attachments/assets/29f5482e-4f6e-4b91-99a8-c851cdb0e7cc)

**Comment by PanJanuszek** [comment]
Well, that's the fact when you base on addons :)

To get the quest that you are looking for, you have to finish these:

![image](https://github.com/user-attachments/assets/ab410599-e528-4534-af65-13ed9b1cf162)

**Comment by PanJanuszek** [comment]
Cannot reproduce
