### ISSUE TITLE
Trouble with "The Worldbreaker" Quest

### ISSUE THREAD

**Issue by punk48** [gamefreedomgit/Maelstrom#6155]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I died on the quest "Devoured" in Iso'rath (Twilight Highlands), but still completed the quest right when I died. 
I then had to auto-complete the quest and auto-accept the "The Worldbreaker" quest. 
But since I had to leave the area for respawning, Deathwing or Thrall never spawned and I couldn't complete the quest. 
I abandoned the quest in hope to be able to reaccept it, but I couldn't. 

Only afterwards I read on wowpedia, that you're not supposed to leave the area or abandon the quest. 
But I couldn't do anything else anyways... 

The questgiver is supposed to be Thrall and he should be in the Maelstrom, but if you've already been to Deepholm, you can't get back to the Maelstrom.

**How to reproduce:**
Do the same...

**How it should work:**
Well, Deathwing should spawn and you should kill him. But you shouldn't die before that I guess.

**Database links:**
https://www.wowhead.com/quest=27378/the-worldbreaker
https://wowpedia.fandom.com/wiki/The_Worldbreaker_(quest)

**Comment by PanJanuszek** [comment]
Fixed after update
