### ISSUE TITLE
Needjalooters

### ISSUE THREAD

**Issue by kapsouli** [gamefreedomgit/Maelstrom#6157]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**So many ppl need on items that are not for their spec is it fair ? hordes and alliance ate in the same dungon some times ppl dont heal some other times ppl need cause they dont want the enemy function to take the loot no balance

can u solve this ?
![WoWScrnShot_091724_184548](https://github.com/user-attachments/assets/f35a7fa0-8cc4-4840-bccb-b8fc037f572d)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Currently its not changeable, it was solved during mists of pandaria
