### ISSUE TITLE
Issue with Bwemba's Spirit Questline

### ISSUE THREAD

**Issue by punk48** [gamefreedomgit/Maelstrom#6158]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I'm trying to do the quests in Stranglethorn, where you have to talk to Bwemba a couple of times to complete several quests for the Bwemba's Spirit Questchain.
But Bwemba is not there. She only spawns when I just enter Stranglethorn via the airship from Orgrimmar, but as soon as I leave Grom Gol, she stops following and disappears. 

**How it should work:**
As far as I understood the comments on wowhead, she should follow you all the time in Stranglethorn.

**Database links:**
https://www.wowhead.com/quest=29219/bwembas-spirit

**Comment by punk48** [comment]
Just found out that if you relog into the game, it seems to work how it should...

**Comment by PanJanuszek** [comment]
Fixed after update
