### ISSUE TITLE
GENERAL TOPIC FOR MELEE DAMAGE PROBLEM - DUNGEONS PLEASE REPORT ALL HERE

### ISSUE THREAD

**Issue by Bloodar** [gamefreedomgit/Maelstrom#6159]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)
![OPMeleeDmg](https://github.com/user-attachments/assets/89ace331-22c7-4e51-9475-2752d433e3b7)

**Description:**
This happened after today's server restart, the boss is hitting 100k on tanks, I'm a plate user and it hits me for 150k+ per swing, hope someone look into it and adjust the numbers.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Odyseos** [comment]
![WoWScrnShot_091924_022622](https://github.com/user-attachments/assets/32d3378b-2372-448b-ac7c-eae101ff090b)
![WoWScrnShot_091924_022625](https://github.com/user-attachments/assets/16d2257c-1237-439d-be60-b19776093e14)
![WoWScrnShot_091924_022629](https://github.com/user-attachments/assets/14e75ce9-30e3-46ea-8469-0b1d2d28e695)

The combat log shows between 44k to 50k, and I'm palatank.

**Comment by PanJanuszek** [comment]
OK, few things.

1. To clear all damage issues, please re-title this issue for more general.
2. The reason why some mobs hits so much is fact that in past we oscillate on damage from different sources.
3. To make it right, put in comment DUNGEON -> NPC -> COMMENT (hits too much / hits too low)

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Bloodar** [comment]
Thank you.
