### ISSUE TITLE
BOSS WARMASTER - TWILIGHT SAPPER

### ISSUE THREAD

**Issue by DartImpact** [gamefreedomgit/Maelstrom#6161]
https://github.com/gamefreedomgit/Maelstrom/issues/6138#issuecomment-2361241094
![Desktop Screenshot 2024 09 20 - 21 37 39 92](https://github.com/user-attachments/assets/78ec2917-fa75-4a6b-bdc4-ba4eeed49ed8)

Twilight Sapper can also be affected by "Death Grip"
min 1:57
https://youtu.be/fQ5gEoDr7JM?t=117

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by jeanpyere** [comment]
still not working, i tested yest and today

**Comment by jeanpyere** [comment]
i see sometimes, sapper dont doing damage on boat, is critical bug

**Comment by PanJanuszek** [comment]
Ticket was for deathgrip, update was today
