### ISSUE TITLE
Dragon Soul Madness hc

### ISSUE THREAD

**Issue by Yarikels666** [gamefreedomgit/Maelstrom#6168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
You can avoide parasite with such spells like AMS or Ice Block, or CoS, Divine Shield, Deterrence, etc immune if you use them before parasite should appear

**How to reproduce:**
Idk how it must works. 

**How it should work:**
Сan you make it so that it cant be skipped? It loses all the interest of fight with madness

**Database links:**
https://www.wowhead.com/npc=56173/deathwing
https://www.wowhead.com/spell=108649/corrupting-parasite
https://www.wowhead.com/spell=7121/anti-magic-shield
https://www.wowhead.com/spell=45438/ice-block
https://www.wowhead.com/spell=642/divine-shield
https://www.wowhead.com/spell=31224/cloak-of-shadows
https://www.wowhead.com/spell=19263/deterrence

**Comment by Sketish** [comment]
[Corrupting Parasite](https://www.wowhead.com/spell=108649) Icon Corrupting Parasite is a rather complex mechanic that will occur twice on every platform during Phase One, once at around the same time that the [Mutated Corruption](https://www.wowhead.com/npc=56471) spawns and once again 60 seconds later. It begins with [Corrupting Parasite](https://www.wowhead.com/spell=108649) Icon Corrupting Parasite, a 10-second debuff cast by Deathwing on a random raid member. This debuff deals increasing Shadow damage, for a total of roughly 300,000 over the course of its duration. When the debuff wears off, an NPC with the same name will spawn at the location of the afflicted raid member.

So using immunity should force add to spawn under player position

**Comment by Yarikels666** [comment]
Yes, i think must work like this, but I want to clarify, I’m talking about the fact that if a person presses immune before the parasite appears, and madness throws a parasite at him, the debuff simply will not appear, in this way by pressing immune you can not hit the parasite at all, i think must work something like Madness use parasite on immune target -> boom parasite exploded insta

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Yarikels666** [comment]
thanks

**Comment by Yarikels666** [comment]
You can still avoide debuff parasite with AMS https://www.wowhead.com/spell=7121/anti-magic-shield
Nothing fixed, i try to make video for you later

**Comment by Sketish** [comment]
Fix is not yet on live server

**Comment by Yarikels666** [comment]
oh sry, mb
