### ISSUE TITLE
unable to progress with handing in quest due to phase problem

### ISSUE THREAD

**Issue by DcPersona** [gamefreedomgit/Maelstrom#6170]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
unable to hand in a completed quest due to npc not being visible.
character name:Huzaar

i have the quest item in my bags, i am at the location to hand in, i can see the yellow question mark on the mini map, but npc is missing. i am stuck in a phase which has made npcs at certain locations dissapear, one of those locations being "Shrine of Aviana"
![missingnpc_questhandin](https://github.com/user-attachments/assets/82fba48d-8564-4beb-8851-bc9e37ea4eb2)

npcs in other areas missing, which makes it hard to sell,repair etc whilst working in the area.
![missingnpc](https://github.com/user-attachments/assets/f3af60ce-f31b-439a-aa0d-e891881d8a52)

**How to reproduce:**

**How it should work:**
i go to the npc, & hand it in.

**Database links:**
[Brood of Evil](https://www.wowhead.com/cata/quest=25552/brood-of-evil#comments)

**Comment by Sketish** [comment]
Please contant GM in Game, they will be able to help you

**Comment by PanJanuszek** [comment]
I think that's the issue with phase after quest Slash and Burn? You have seen group of NPC's there but now it's empty?

**Comment by DcPersona** [comment]
@Sketish i firstly contacted a GM in game, (Toxicmist) and he suggested i make this bug post. So i made this post, and the suggestion is to contact GM in game again? seems a little cyclic. @PanJanuszek yes, there were a bunch of npcs there, and then they all dissapeared.

**Comment by GMNeon** [comment]
When you are online could you contact a gm so we can look to see what the underlying issue is and get it resolved as fast as possible while also providing Details to the devs to stop this from occurring again?

**Comment by PanJanuszek** [comment]
> So i made this post, and the suggestion is to contact GM in game again? seems a little cyclic.

Yes, because  GM is the only person in game who can provide such information like phase of your character

**Comment by DcPersona** [comment]
hi again, thanks for the response.  GMOkamiden responded, i explained situation, and it wasnt long before they rectified the problem and i managed to hand in the quest.  all seems well on the western front.  as per GMNeon' request for details, youll have to speak with the GM.  thank you for your time and effort.
