### ISSUE TITLE
Mission heart healed bugg

### ISSUE THREAD

**Issue by wolform2000** [gamefreedomgit/Maelstrom#6171]
**Description:**

My character Esquirla has been trying to complete the frozen heart mission for a day and I can't.

For a day now I have been trying to do the frozen heart mission, which should be able to take a proto-drake, upload the prisoners and deliver them, but when the prisoners are uploaded, it cannot be delivered and is not completed.

I have tried to leave the mission and take it again, I have also tried to take all the prisoners or take another proto-drake and it never lets me know how I freed them.

**How to reproduce:**
I should take the mission because from what I understand it doesn't just happen to me.

**How it should work:**
They should be able to hand themselves over to the prisoners and hand over the protodrakes to complete it.
![Captura1](https://github.com/user-attachments/assets/7294467f-7538-4bdd-b006-fe3746213c9d)
![2](https://github.com/user-attachments/assets/66dc1202-90f5-4d7c-8ae8-e7726d6d24e5)

**Database links:**

https://www.youtube.com/watch?v=GnPMsgbUlY8

**Comment by PanJanuszek** [comment]
This is the place where you handle prisoners and drakes

![image](https://github.com/user-attachments/assets/9cc335e8-389e-427f-b00b-3db59aad1dec)

![image](https://github.com/user-attachments/assets/8f18fb89-9d7a-4f00-9735-c0eb8007e632)

Not an issue
