### ISSUE TITLE
Quest "Hellscreams Legacy"

### ISSUE THREAD

**Issue by rock-b-asd** [gamefreedomgit/Maelstrom#6173]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I tried to do the quest, but the fuel containers do not spawn.

**How to reproduce:**
Start quest

**How it should work:**
Fuel containers spawn close to the orks.

**Database links:**

**Comment by GMNeon** [comment]
![image](https://github.com/user-attachments/assets/02f13580-7de3-4660-8993-ba8e916567cc)

**Comment by rock-b-asd** [comment]
Thanks for the screenshot.
