### ISSUE TITLE
RECIPE DROP FROM QUEST IN STRATHOLME DOSEN´T WORK

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6179]
[**Description:**
The boss "Risen Hammersmith" in Stratholme only spawned once and never dropped the 100% drop items "Plan: Enchanted thorium leggings" & "Bottom half of advanced armorsmitthing 2"

I have been in contact with two different GMs and they  have told me different things about this issue.
The first GM told me that he should spawn every single time you play the dungeon (But he dosen´t) and that you don´t need the quest to face him. 

The next GM told me that he should drop everything the first time I face him, but all he did was drop one item that everyone could roll at so then it´s impossible to get the item if you don´t win the roll since he doesn´t spawn without the quest? Seems weird!

**How to reproduce:**
Defeat the boss "Risen Hammersmith" in Stratholme

**How it should work:**
Should drop items "Plan: Enchanted thorium leggings" & "Bottom half of advanced armorsmitthing 2"

**Database links:**

**Comment by PanJanuszek** [comment]
(Patch 2.4.0) | By 78626 (7,505 – 5·14·49) on 2008/03/30 (Patch 2.4.0)
he's not guaranteed to drop the bottom half page, just killed himand he drop some green mail bracers :(


And yes he is still triggered NPC:

1) The Crimson Hammersmith is a triggered spawn, so you can't just wander around and expect to find it.
2) Clicking on the parchment labeled "Blacksmithing Plans" will trigger the Crimson Hammersmith, who will try and kill you.
3) The parchment labeled "Blacksmithing Plans" seems to have a few locations where it can spawn. The ones I know or have read about are listed here:

A) In the Hoard area, before Canoneer Willy on the floor (this is where I found it).
B) Before the main boss of the Live Side, in two small alcoves, also occupied by Archivist Galiford. It will be sitting on a bench.

![image](https://github.com/user-attachments/assets/72f8edc0-d4fd-4cd1-9919-f748b49100c9)
![image](https://github.com/user-attachments/assets/d83497b5-55d4-470f-a8f7-1227713fdfa0)

Fixed drop chance to proper value (61%)
![image](https://github.com/user-attachments/assets/62938897-887e-41c8-bd7b-b1a714424187)

Plan: Enchanted thorium legging, this is 1% drop chance, dunno who told you that it's 100%...
As it is old content recipe I will increase chance to 10%.

![image](https://github.com/user-attachments/assets/d3895c57-5f43-4418-83db-cbe0499cecd0)

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Hellbringar** [comment]
> Fixed after update

Hello!
Thanks for quick reply!

I used AtlasLoot the check the drop rates, please see a picture which states that Enchanted thorium leggingins should be a quest reward.

![WoWScrnShot_092724_214407](https://github.com/user-attachments/assets/ad3668a2-6197-4869-8c2e-2b21d5627df2)

**Comment by PanJanuszek** [comment]
If quest will not award this, please create ticket for that quest
