### ISSUE TITLE
Quest: An Old, Crazed Friend -- (Scarlet Monastery - Armory)

### ISSUE THREAD

**Issue by Nidhogg89** [gamefreedomgit/Maelstrom#6181]
There should be a dialogue window to be able to talk to Joseph the Crazed but all it says is Greetings. So quest is not completable.
Please, fix it.

https://cata-twinhead.twinstar.cz/?quest=26984

https://cata-twinhead.twinstar.cz/?npc=44741

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Rampageris** [comment]
i can't finish don't work
