### ISSUE TITLE
Scale Belly rare in Crystalvein Cavern in The Northern Stranglethorn

### ISSUE THREAD

**Issue by Nidhogg89** [gamefreedomgit/Maelstrom#6183]
I've killed him six times lately and he dropped same item six times in a row now. (Iridescent Scale Leggings (Mail) ), his loot table gotta be broken for sure. There's alot of other items that he can drop.

https://classicdb.ch/?npc=1552#drop:250-16+1

**Comment by PanJanuszek** [comment]
This NPC has only 2 drops in Cata expansion: legs and sword
