### ISSUE TITLE
[BUGGED QUEST] "The Purification of Quel'Delar"

### ISSUE THREAD

**Issue by megalocuts** [gamefreedomgit/Maelstrom#6188]
The [quest](https://www.wowhead.com/quest=24553/the-purification-of-queldelar) consist of using an item within a private instance of Sunwell Plateau, the item is called [Tainted Quel'Delar](https://www.wowhead.com/item=49879/tainted-queldelar) and in exchange the player obtains [Restored Quel'Delar](https://www.wowhead.com/item=49871/restored-queldelar) to complete it. But instead of receiving the latter nothing happens after using the first item.

**How to reproduce:**
You use the Tainted Quel'Delar item in front of the lightwell.

**How it should work:**
You use the Tainted Quel'Delar item in front of the lightwell and after following NPC's scripts you are able to pick up the Restored Quel'Delar item.

**Comment by Nidhogg89** [comment]
Would like this one fixed as well 🙃

**Comment by PanJanuszek** [comment]
Cannot reproduce, gained this quest and uses quest item.
Event works. Please attach clip next time. 

![image](https://github.com/user-attachments/assets/2b36af66-d447-4605-81c6-14e52116492a)
![image](https://github.com/user-attachments/assets/5bd7a4ba-38b9-4813-ac6d-0fc2fab56f93)
