### ISSUE TITLE
"Abuse the Ooze" (Glory of the Hero) Achievement BUG LAST BOSS

### ISSUE THREAD

**Issue by Rexzio** [gamefreedomgit/Maelstrom#6189]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

THE “Abuse the Ooze” ACHIEVEMENT CANNOT BE COMPLETED, IT HAS ERRORS, WHEN THE JOINTS DO NOT JOIN AS THEY SHOULD AND YOU SIMPLY CAN'T COMPLETE THE ACHIEVEMENT.

**How to reproduce:**
In the last boss of the dungeon, when I want to collect the sludges, or more specifically the snot

**How it should work:**
By mixing 2 of them, they join together and become a larger one, you have to collect 5 of those large ones to complete the achievement.

**

**Database links:**
https://www.wowhead.com/wotlk/achievement=2155/abuse-the-ooze 
https://www.wowhead.com/wotlk/achievement=2136/glory-of-the-hero
Defeat Sjonnir the Ironshaper in the Halls of Stone on Heroic Difficulty and kill 5 Iron Sludges during the encounter.

**Comment by PanJanuszek** [comment]
Not an issue.

![image](https://github.com/user-attachments/assets/3e631813-d056-431d-858a-32ec8b123c08)

Achievement works, I have gathered 7x in 2min. However, boss applies aura which damage allies and enemies, making it a little harder, sometimes it kills ooze's before you connect them. I assume you were doing it solo. It will be hard. Pick someone to party
