### ISSUE TITLE
Archaeology Digsite Eastern Plaguelands

### ISSUE THREAD

**Issue by Shaky1324** [gamefreedomgit/Maelstrom#6190]
![WoWScrnShot_093024_141454](https://github.com/user-attachments/assets/d8bc4324-9e57-47ba-98e1-4ca8a6d9058d)
![WoWScrnShot_093024_141504](https://github.com/user-attachments/assets/9c7c2c8b-67b2-45f7-9407-99fdc253ac27)
![WoWScrnShot_093024_141513](https://github.com/user-attachments/assets/6cf7be37-5c8b-4c76-9f40-1b8cc4a09a34)

Found a bug whilst trying to complete this digsite in Eastern Plaguelands. Took screenshots to hopefully provide a clearer picture of the issue.

Got a green light whilst surveying but it's sending me in circles and there's no artefact showing up. Co-ords aprroximately are 11.70 | 20.50

**Comment by frostwave942** [comment]
there is a cave below, the digsite is there.
