### ISSUE TITLE
4.1 Questline - alliance

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#6191]
1. To Fort Livingston - missing quest text

2.Serpent and Poisons - Bwemba is missing healing animation + sometimes player can get multiple credit from one npc
https://youtu.be/HAO0hQLwxWA?t=639

Jungler Serpent ID:52224 their melee dmg looks low

3.Nesingnwary will know - same as #1
![image](https://github.com/user-attachments/assets/1e505318-3b1a-41ba-8605-b55aa1462c74)

4.Hunter's Revenge - missing quest location on map
![image](https://github.com/user-attachments/assets/4ac6bea4-0930-4344-bf45-6c654290ac05)

5.Flares are visible before fight with Mauti and event with stealing dwarf grent direhammer
![image](https://github.com/user-attachments/assets/4556ded3-4166-4427-971e-096277d09c88)

Also during event cat is jumping to opposite directions than flares.
https://youtu.be/wjnejbw4Mik?t=100

6.Some good will come - missing quest text
![image](https://github.com/user-attachments/assets/69fad15e-1658-4752-8b18-25623d26e4e6)
https://youtu.be/wjnejbw4Mik?t=344

Also this quest should appear after turning Bury me with me boots

7.Bwemba dissapear during flying to Booty Bay and there is a huge phasing issue, most npc are missing, only Voljin is there

**Comment by PanJanuszek** [comment]
Fixed after update
