### ISSUE TITLE
Invisible Aeonaxx Spawn

### ISSUE THREAD

**Issue by NirajBajracharya** [gamefreedomgit/Maelstrom#6194]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** Aeonaxx spawned around 53,66 in Deepholm I could target it but it was invisible. I killed it, but no corpse and no loot.

**How to reproduce:** Unsure

**How it should work:** Should be rideable, killable and drop mount.

**Database links:**  https://www.wowhead.com/cata/npc=50062/aeonaxx

I did not think to take a screenshot while fighting Aeonaxx. But Skada still recorded the fight. ScreenShots below
https://imgur.com/Y8nyzrB
https://imgur.com/ZsMQ1x8
https://imgur.com/H3nA3t1

edit: it happened again. This time I took a screenshot
https://imgur.com/r6xftd2

**Comment by PanJanuszek** [comment]
Fixed after update
