### ISSUE TITLE
Kings of the Spider-hill achievement

### ISSUE THREAD

**Issue by Lightret** [gamefreedomgit/Maelstrom#6195]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Can not reach the last platform. Before the last platform, one spider missing.  

**How to reproduce:**

**How it should work:**
There should be a spider there. 
![WoWScrnShot_100324_223823](https://github.com/user-attachments/assets/1558bd1c-0abc-4052-b6df-d0cd973c03c7)

**Database links:**

**Comment by PanJanuszek** [comment]
well that spider is actually on your level, by unknown reason if you kill it and try again it will work
