### ISSUE TITLE
TBC raid SSC/TK drops are missing

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#6197]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have been clearing Serpentshrine Caverns and Tempest Keep lately (kill every boss /npc available) in the hopes of recieving a specific profession pattern. According to WowHead every pattern has a 1-2% chance to drop, and yet I got ONLY belt patterns and ZERO boot pattern of any kind. My first idea was that I'm just unlucky, so I repeated 5x on my DK, and 5x on my druid as a full trash clear of each SSC + TK but still NO boot pattern of any kind dropped.  Please not that there are 2 plate 2 mail 2 leather 2 cloth that should drop. Kept getting 3-4 of same belt patterns...

**How to reproduce:**
Please look into the drop rates and make every patterns listed drop on the intended rate/ make them available to drop at all.

**How it should work:**
Not only belt patterns should drop but boot patterns also. (The basic epic drops for Serpentshrine Cavern and Tempest Keep were alright,  only the boot profession pattern are not there for some reason.)

**Database:**
https://www.wowhead.com/tbc/item=30283/pattern-boots-of-the-long-road
https://www.wowhead.com/item=30307/pattern-boots-of-the-crimson-hawk
https://www.wowhead.com/item=30324/plans-red-havoc-boots
https://www.wowhead.com/item=30306/pattern-boots-of-utter-darkness

**Comment by Afgann** [comment]
fixed
