### ISSUE TITLE
Problem with pets that have a string + he tuskar dragon doesn't do the effect

### ISSUE THREAD

**Issue by Grimmllin** [gamefreedomgit/Maelstrom#6198]
have a nice good day =) I just bought the Tuskar dragon for my lvl 19 in the shop. I noticed that firstly you can't see the purr that goes from the hand of the char to the dragon ( this error is also with the balln pets like from the dark moon faire ), and secondly the tuska dragon doesn't have the effect with the lightning and the sound.

Actually, you should see the purr that goes from the hand of the char to the dragon and the dragon should actually have an effect every 10-30 seconds that makes the dragon flash as well as the char + sound. 

It would be really great if you can fix the problem

**Comment by Grimmllin** [comment]
sry my translator mistranslated a word I didn't mean purr xD But the string that goes from the hand to the kite

**Comment by Sketish** [comment]
can you please give wowhead link to pet , since translation is not matching any pet name in game

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Grimmllin** [comment]
It's this pet =)
https://www.wowhead.com/wotlk/de/item=49287/tuskarrdrachen
Unfortunately, the dragon is not doing anything at the moment. And the cord (line) is unfortunately not visible either. The line problem is also with all other pets that have a cord (leash).
It should be so that the string goes from the hand to the dragon and it should have an effect that triggers a lightning that goes from the dragon to the char with a thunderstorm sound.

**Comment by PanJanuszek** [comment]
Dragon is fixed and waiting for update.

Tuskar is missing only kite rope?

**Comment by Grimmllin** [comment]
Yes, the rope is missing. also with the other pets that should actually have one. such as the Darkmoon Balloon or Alliance Balloon. 
Otherwise, everything is great and the customer service is very fast and friendly =)

**Comment by Grimmllin** [comment]
Good evening =) short feedback on the tuskarr dragon. The effect works now and you can see the rope too. Thank you very much, great service and wonderful server =)
