### ISSUE TITLE
Quest: 29201 - [Through the Gates of Hell] 

### ISSUE THREAD

**Issue by GMNeon** [gamefreedomgit/Maelstrom#6201]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Should trigger phase change inside molten front where malfurion is fighting the elemental, Quest complete not triggers and the malfurion is not attacking.

**How to reproduce:**
accept quest, go in and the slaglord is there but pretagged. Malfuron is just chiling not engaging the slaglord.

**How it should work:**
malfurion should be attacking and the mob should not be tagged. After quest complete player should be phased.

**Database links:**
https://www.wowhead.com/quest=29201/through-the-gates-of-hell#comments

**Comment by PanJanuszek** [comment]
Fixed after update
