### ISSUE TITLE
No flight master at Shalewind Canyon

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6204]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
There is no flightmaster at Shalewind canyon base. You can fly there, but if you land there you will not be able to fly anywhere else.

**How to reproduce:**
Travel to Shalewind canyon and try and fly from there anywhere else (You can´t since there is no flight master there)

**How it should work:**
Should be a flightmaster there offering you a flight to another flight post

**Database links:**
![WoWScrnShot_100724_020251](https://github.com/user-attachments/assets/940c5f54-be96-403c-bc57-3a5fc6d0c582)
![WoWScrnShot_100724_020258](https://github.com/user-attachments/assets/a16d4c1b-bffc-4017-ba29-549801bd002f)

**Comment by PanJanuszek** [comment]
This particular area depends from your progress in Redridge Mountains, if you didn't complete history here, you will not see NPC's there.
