### ISSUE TITLE
Rattlegore won´t drop the item "Top Half of Advanced Armorsmithing: Volume II"

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6209]
**Description:**
Not sure that drop in Scholomance is working correctly, have been going at it for some time now and have gotten every other drop at least 4 times but no "Top Half of Advanced Armorsmithing: Volume II"!

Please make sure that the drop is working as it should.

**How to reproduce:**
Kill Rattlegore in Scholomance intill you get the drop - "Top Half of Advanced Armorsmithing: Volume II"

**How it should work:**
 Rattlegore should have close 8% drop rate for the item -  "Top Half of Advanced Armorsmithing: Volume II"

**Database links:**
![Print of Rattlegores drops](https://github.com/user-attachments/assets/d79ea86b-7b80-468f-b3dc-325a5a2ac472)

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Hellbringar** [comment]
> Fixed after update

Can you also check if the drop "Bottom Half of Advanced Armorsmithing Volume III" from the Black Guard Swordsmith in Stratholme works as it should? Been trying for some time there as well without success.

![Stratholme - Black Guard Swordsmith - Bottom Half of Advanced Armorsmithing Volume III](https://github.com/user-attachments/assets/91e8c0b0-bff1-4acb-a23c-ae07c970d8d2)

**Comment by Hellbringar** [comment]
> Fixed after update

Hello again!
An update on the original bug report!

Got the item the first try after you updated the server! Great work, thanks man! :D
![WoWScrnShot_101624_231121](https://github.com/user-attachments/assets/95e0cf4e-2120-42cf-800c-bb26e0cc4d7c)
