### ISSUE TITLE
Wild Wild Wildhammer Wedding

### ISSUE THREAD

**Issue by Blindriver38** [gamefreedomgit/Maelstrom#6213]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Doing the Quest Wild, Wild, Wildhammer Wedding, and I am at the part where your supposed to protect the wedding. Except after teh ceremony, its supposed to be a battlefield with the tentacle things. Your supposed to fight a boss and save the day. Except here I am teleported to the new instance, no enemies, but im being healed constantly, beak is flying around, but no enemies or anything else

**How to reproduce:**
Take the quest, do the ceremony, and bam, no new instance, no boss to fight. Here is the Wowhead page of the quest. 
**How it should work:**
After you  listen to the ceremony, you should be teleported to an instance where the wedding is under attack and you fight all these tentacles and a boss,

**Database links:**

https://www.wowhead.com/quest=28655/wild-wild-wildhammer-wedding

**Comment by PanJanuszek** [comment]
Feedback from players, it was caused by addons.
