### ISSUE TITLE
NPC ID 3028 Kah Mistrunner

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Тhis NPC won't give me the daily quests. They are needed for Fish or Cut Bait: Thunder Bluff ID 5849 and Gone Fishin' ID 5849

**How to reproduce:**

**How it should work:**

**Database links:**
https://wowpedia.fandom.com/wiki/Fish_or_Cut_Bait:_Thunder_Bluff
https://wowpedia.fandom.com/wiki/Gone_Fishin%27
https://www.wowhead.com/npc=3028/kah-mistrunner

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/f3f11493-7e3f-446e-ab3c-151c8688a342)

required Fishing 75 at least

**Comment by MirNelthDB** [comment]
I do not dispute this, but I pay attention that if I do a daily quest in an undercity or in an orgrimmar, and only after that I come to this NPC, it does not give me a quest. I shouldn't have to come here first to do this quest, but they should work every day, one in each major city no matter if I passed the others.
