### ISSUE TITLE
Can´t start quest from "Enchanted thorium platemail volume 2"

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6217]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I have been gathering the pieces that are required for the "Enchanted thorium set" and have now combined top and bottom halfs of version 2 (That creates "Enchanted thorium platemail volume 2" - https://www.wowhead.com/cata/item=18770/enchanted-thorium-platemail ) but the newly created item isn´t starting the quest like it´s supposed to do.

Nothing happens when I press the item to start the quest as with any other quest-starting item.

**How to reproduce:**
Get "Enchanted thorium platemail volume 2" and try to start it´s quest.

**How it should work:**
"Enchanted thorium platemail volume 2 "should start a quest for the player.

**Database links:**

![WoWScrnShot_101724_010555](https://github.com/user-attachments/assets/440dd1ab-bc99-4502-b180-99ea88b5cad8)

https://www.wowhead.com/cata/item=18770/enchanted-thorium-platemail

**Comment by PanJanuszek** [comment]
I like our story, with fixing this whole chain ;)

**Comment by PanJanuszek** [comment]
Create all tickets for them

**Comment by Hellbringar** [comment]
> Create all tickets for them

Hello again!
Volume 1 I have managed to collect now and it seems to be working! BUT before we can control volume 3 the issues mentioned in the following bug report need to be fixed! - "Bugg prevents summoning of a boss in Lower Blackrock Spire - Oruk Doomhowl! #6215"
