### ISSUE TITLE
Seasonal quest "Missing Heirlooms" bugged!

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6221]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest "Missing Heirlooms" is bugged.
Nothing happens when you speak with the NPC in the cabin of the ship.

**How to reproduce:**
Take the quest "Missing Heirlooms" from Stormwind inn in the trade district and try to complete by traveling to stationary alliance ship  in Stormwind harbor and enter ships cabin.

**How it should work:**
Should be able to complete by talking to NPCs body in the ship's cabin.

**Database links:**
![WoWScrnShot_101824_143327](https://github.com/user-attachments/assets/f34ffd94-024f-45b1-a8c3-62ad77d32b8c)
![WoWScrnShot_101824_143331](https://github.com/user-attachments/assets/c5699d91-3d86-45d2-8f26-ac38fd55a3fe)

**Comment by Nidhogg89** [comment]
Raknar please fix this one before event ends. Thank you..

**Comment by PanJanuszek** [comment]
Fixed after update
