### ISSUE TITLE
 Event quest : Missing Hierlooms

### ISSUE THREAD

**Issue by MissCllick** [gamefreedomgit/Maelstrom#6222]
Quest is not working : u can interact with dead npc.... but after that nothing happends.... quest isnt completed.... question mark is grey

**Comment by Sketish** [comment]
Please follow template and provide details what quest and send ss how its looks ingame

**Comment by Sketish** [comment]
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6221
