### ISSUE TITLE
 [Rotten Hallow]

### ISSUE THREAD

**Issue by patr1cxk** [gamefreedomgit/Maelstrom#6227]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**   [Rotten Hallow] under this achievement. an alliance A Time to Gain No where to find

**How to reproduce:**  It suppose to show in entrance SW.

**How it should work:** 

**Database links:**

**Comment by Sketish** [comment]
https://www.wowhead.com/quest=29075/a-time-to-gain missing quest
