### ISSUE TITLE
Shilah Slabchisel's quest chain issue

### ISSUE THREAD

**Issue by Jazzz999** [gamefreedomgit/Maelstrom#6228]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Shilah Slabchisel's quest chain issue

**How it should work:**
miss a quest in quest chain 
"The Mosshide Job" quest id 25865

**Database links:**
https://www.wowhead.com/npc=41415/shilah-slabchisel

**Comment by PanJanuszek** [comment]
You missed something.

Chain:
Assault on Menethil Keep -> Swiftgear Station -> Dinosaur Crisis -> The Mosshide Job
