### ISSUE TITLE
Event quest "Crashing the Wickerman Festival" is bugged!

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6229]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
You are supposed to scout the Wickerman Festival just west of Undercity but ther isnothing there. (See pictures)

**How to reproduce:**
Take that quest outside of Stormwind and travel to Undercity, there is nothing there.

**How it should work:**
Run up to wickerman festival and then run away.

**Database links:**
![WoWScrnShot_101924_194351](https://github.com/user-attachments/assets/c5d59f8a-6e32-4e71-9ff6-03f2cb4314b4)
![WoWScrnShot_101924_194358](https://github.com/user-attachments/assets/d1463347-43a4-4731-b8e8-aafc5257fbba)

https://www.wowhead.com/cata/quest=1658/crashing-the-wickerman-festival (Some infor here regarding quest starting place might not be true)

**Comment by Hellbringar** [comment]
> **Description:** You are supposed to scout the Wickerman Festival just west of Undercity but ther isnothing there. (See pictures)
> 
> **How to reproduce:** Take that quest outside of Stormwind and travel to Undercity, there is nothing there.
> 
> **How it should work:** Run up to wickerman festival and then run away.
> 
> **Database links:** ![WoWScrnShot_101924_194351](https://private-user-images.githubusercontent.com/177574891/378111084-c5d59f8a-6e32-4e71-9ff6-03f2cb4314b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NTUzNjYsIm5iZiI6MTcyOTQ1NTA2NiwicGF0aCI6Ii8xNzc1NzQ4OTEvMzc4MTExMDg0LWM1ZDU5ZjhhLTZlMzItNGU3MS05ZmY2LTAzZjJjYjQzMTRiNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQyMDExMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDExNDliOTgzOGExZDdmMmE1Y2UwMThjYmU0NDg4ODE4ZDQ3YjBlYmIzNjIyMDdlMWNjMDc1N2NiNjFhNDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0n2DNxB8fZ9SA6zBesZM_66xfxzqIgdZ8S-WZPoJqyM) ![WoWScrnShot_101924_194358](https://private-user-images.githubusercontent.com/177574891/378111086-d1463347-43a4-4731-b8e8-aafc5257fbba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NTUzNjYsIm5iZiI6MTcyOTQ1NTA2NiwicGF0aCI6Ii8xNzc1NzQ4OTEvMzc4MTExMDg2LWQxNDYzMzQ3LTQzYTQtNDczMS1iOGU4LWFhZmM1MjU3ZmJiYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQyMDExMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWVjYTVmOTRiNjM4N2QwOTkwYTRjYmE1YjMyYzRiMTMzNGNhNTdhZjc2YmUzN2E1NTNkN2VjNDQ1N2QzZmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iF0ZQ_PWdmlmRv583agibh-66WLDf8e8aYPanFMwtuU)
> 
> https://www.wowhead.com/cata/quest=1658/crashing-the-wickerman-festival (Some infor here regarding quest starting place might not be true)

(Edit: 2024-10-20)
The quest works but questmarker on the map is in the wrong place! (You finish the quest inside the square of lorderons ruins)

**Comment by PanJanuszek** [comment]
You came here from Frostmourne?? On Maelstorm there is no option to take it

**Comment by Hellbringar** [comment]
> You came here from Frostmourne?? On Maelstorm there is no option to take it

Hello mate!

No i have only/are only playing on Maelstorm.

In saying that the quest is not available for players to accept you are actually wrong. I did it and a lot of other players have been asking about it in the WorldChatt, so it is very much acceptable. (even if it maybe is not meant to be)
