### ISSUE TITLE
Arelion's Secret Quest Outlands

### ISSUE THREAD

**Issue by Norzektt** [gamefreedomgit/Maelstrom#6235]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
https://www.wowhead.com/cata/quest=10286/arelions-secret

`Description `
Arelion's journal does not deal with any sort of scholarly studies. It details his escapades with a young female blood elf! How could I've been such a fool?

Unfortunately, the floozy's identity is not revealed in this journal. Aledis, a colleague of Arelion's, was his best friend and confidant. Go question him and find out who he was having this affair with.

I saw Aledis leave Falcon Watch for Zangarmarsh. Follow the road headed north from town; it'll eventually lead west, toward Zangarmarsh.

How to reproduce:  
Magister Aledis needs to be spawn 

How it should work:
Magister Aledis is an Blood Elf NPC that is found on his mount walking the road between Flacon Watch to Zangarmarsh
https://www.youtube.com/watch?v=jArM_Cc9mvU

This video shows he is now where to be found
https://youtu.be/Mb1SCbd2bjM

Database links:
https://www.wowhead.com/cata/npc=20159/magister-aledis

**Comment by Norzektt** [comment]
I found the NPC he was walking but sometimes underground... and sometimes he isnt responsive to the click

**Comment by GMNeon** [comment]
Can confirm this is just a pathing issue. while in the air or underground threat is wobbly but this quest is still completable.

**Comment by Afgann** [comment]
fixed
