### ISSUE TITLE
The World Pillar Fragment quest in Deepholm

### ISSUE THREAD

**Issue by tartarugee** [gamefreedomgit/Maelstrom#6249]
[//]: # (https://www.wowhead.com/cata)

**Description:**

You kill the Dragon, then you can't loot it

**How it should work:**

There's something like a stone in the air, what you should loot but can't loot it. 

**Database links:** 

For an example it should work like it 

https://www.youtube.com/watch?v=a-IRYrawDAk

**Comment by Sketish** [comment]
Fix is waiting for being apllied to main realm. Wait for server restart
