### ISSUE TITLE
Omnitron defense system not working on 10h 25n or 25h. 

### ISSUE THREAD

**Issue by Hoofjob-Instinctz** [gamefreedomgit/Maelstrom#6250]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

this is new. the statues are frozen, and when i try to start teh fight by swapping the diffuclty they just stop moving. very odd. GM please fix xD

**Comment by PanJanuszek** [comment]
leave and enter instance

**Comment by Hoofjob-Instinctz** [comment]
Tried everything already plenty of times.

**Comment by Hoofjob-Instinctz** [comment]
There just flat out frozen, it dosnt work

**Comment by Sketish** [comment]
Confirmed on ptr. Also inactive robots shouldn;t be targetable.
![image](https://github.com/user-attachments/assets/5f392beb-2a21-48dd-bfb0-16d425641c77)

**Comment by Hoofjob-Instinctz** [comment]
i was gonna post a full clip if GMs didnt confirm it lol.

**Comment by Afgann** [comment]
fixed
