### ISSUE TITLE
Quest bugged - Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by Beeeefsquatch** [gamefreedomgit/Maelstrom#6262]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
This quest is bugged. The giant picks you up in his hand to investigate the last place the hammer was seen but then instantly drops you. The quest says completed but when you return to Thorim, you cannot compete the quest.

**How to reproduce:**
I did all the quests in the series leading up to it. The giant picks me up to take me somewhere then instantly drops me and says I completed the quest. I go to turn in the quest to Thorim and I can’t 

**How it should work:**
The quest should be able to be turned in
**Database links:**
I don’t know how but I can show you the quest bugging

**Comment by GMNeon** [comment]
Please add the rest of the information. including the link to the quest and what you did vs what should happen.

**Comment by GMNeon** [comment]
https://www.wowhead.com/cata/quest=13010/krolmir-hammer-of-storms
