### ISSUE TITLE
MISION BUG "UNA LIMPIEZA VISCOSA" "KROLMIR, EL MARTILLO DE TORMENTAS" EN CUMBRES TORMENTOSAS , RASGANORTE

### ISSUE THREAD

**Issue by jarecito66621** [gamefreedomgit/Maelstrom#6263]
LA MISION TE LA DA EL "YELMO DE ODIN" EN CUMBRES TORMENTOSAS EN DUN NIFFELEM
TE ENVIA A RECOGER 5 UNIDADES DE ACEITE VISCOSO PERO LOS NPC QUE DAN LOS ACEITES NO APARECEN EN LA CAVERNA IVERNAL, Y OTRO BUG ES LA MISION QUE TE DA THORIM EN CUMBRES TORMENTOSAS EN TEMPLO DE LAS TORMENTAS.
TE ENVIA A HABLAR CON EL REY JOKKUM EN DUN NIFFELEM PARA SABER SOBRE EL MARTILLO DE KROLMIR PERO ALA HORA DE HABLAR CON EL NPC TE COJE TE ALZA Y TE SUELTA ALA VES Y AY ES DONDE SE BUGEA LA MISION , PORFAVOR LE PIDO QUE ARREGLEN ESOS BUGS , YA QUE SOY APASIONADO DEL PVE Y ME DESMOTIVA A SEGUIR EN EL SERVER CON TANTOS BUGS,, ESTARE REPORTANDO MAS BUGS..MUCHAS GRACIAS MJ..

**Comment by jarecito66621** [comment]
https://www.wowhead.com/cata/quest=13010/krolmir-hammer-of-storms ENLACE DE LA QUEST

**Comment by Sketish** [comment]
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6216
