### ISSUE TITLE
Bugged dungeon quests! Hellfire Citadel - Hellfire Ramparts

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6264]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quests "Demons in the citadel" & "War on the ramparts" inside the dungeon Hellfire Ramparts is bugged.
Both of these quests are quests where you collect loot from the bosses inside the dungeon but nothing dropped for me upon defeating the bosses (See pictures)

**How to reproduce:**
Enter the dungeon "Hellfire Ramparts" and talk with the NPC close to entrance and accept quests.
Defeat the bosses inside that are mentioned in the quests. 

**How it should work:**
Both of these quests are quests where you collect loot from the bosses inside the dungeon but nothing dropped for me upon defeating the bosses (See pictures)

**Database links:**
![WoWScrnShot_102824_225210](https://github.com/user-attachments/assets/91d4c99a-416c-4ef6-aa2d-a74389ee5206)
![WoWScrnShot_102824_234216](https://github.com/user-attachments/assets/e6545a68-4806-4baf-9eeb-53df80dc884d)
![WoWScrnShot_102824_234218](https://github.com/user-attachments/assets/81dd373e-97ac-4b41-a449-63dea1a031db)

**Comment by Sketish** [comment]
Were you in raid group ? If yes then dungeons quest wont workj ?

**Comment by Hellbringar** [comment]
> Were you in raid group ? If yes then dungeons quest wont workj ?

Hmm i might have been!
But that don't explain why I didn't get the correct drops for quests from bosses or progress for killing the mobs right?

**Comment by Sketish** [comment]
In raid group you arent getting credit for most quests. so its not a bug. Try in party instead of raid
