### ISSUE TITLE
Bugged dungeon quests! Hellfire Citadel - The shattered halls

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6265]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quests "O`mrogg`s warcloth", "One last favor" & "Turning the tides" inside the dungeon "The shattered halls" is bugged.

"O`mrogg`s warcloth" & "Turning the tides" are both quests where you collect loot from the bosses inside the dungeon but nothing dropped for me upon defeating the bosses.

The quest "One last favor" is a quest where you are requested to kill specific mobs inside the dungeon but my kills did not count towards the quest goal when I defeated the required mobs.

**How to reproduce:**
Enter the dungeon "The shattered halls" and talk with the NPC close to entrance and accept quests.
Defeat the bosses and mobs inside that are mentioned in the quests.

**How it should work:**
"O`mrogg`s warcloth" & "Turning the tides" are both quests where you collect loot from the bosses efter killing them.

The quest "One last favor" is a quest where you are requested to kill specific mobs inside the dungeon.

**Database links:**
![WoWScrnShot_102824_233334](https://github.com/user-attachments/assets/f168d4b1-c097-46fe-8367-895411bd6c2b)
![WoWScrnShot_102824_234228](https://github.com/user-attachments/assets/eba4713b-16f1-4244-be67-75717980c831)
![WoWScrnShot_102824_234230](https://github.com/user-attachments/assets/b2fe2d6f-484e-4bbb-a417-09bb6d7c0499)
![WoWScrnShot_102824_234232](https://github.com/user-attachments/assets/5d29b268-4a77-4bb9-885f-a1168108d98b)

**Comment by Sketish** [comment]
In raid group you arent getting credit for most quests. so its not a bug. Try in party instead of raid
