### ISSUE TITLE
The Amphitheater of Anguish

### ISSUE THREAD

**Issue by Elfy279** [gamefreedomgit/Maelstrom#6271]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Amphitheatre of Anguish seems to be bugged. Gurgthok does not offer any quests, and both he and Wodin just have 'Greetings *player*' for chat dialogue. Even when given the first quest by gm, the encounter did not trigger

**How to reproduce:**

**How it should work:**

**Database links:**
wowhead.com/cata/quest=12932/the-amphitheater-of-anguish-yggdras#comments

**Comment by Sketish** [comment]
Did you took  prequest from dalaran ?

**Comment by Elfy279** [comment]
No, I had no idea there was one. When I was looking it up there was no mention of a prequest. I will try to find it in dalaran and let you know

**Comment by Elfy279** [comment]
Wow, yeah that worked. I swear that quest must have been optional before though, because I've never done it, and I played retail in wotlk. anyways, Resolved
