### ISSUE TITLE
The Lost Pilot quest in loch modan not appearing

### ISSUE THREAD

**Issue by Drakegamer456879** [gamefreedomgit/Maelstrom#6272]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
So ive just done all the quests in Dun Morogh that lead up to this quest, yet its doesnt appear after i completed Reinforecement for Loch Modan, by which i cant continue questing in Loch Modan as a Night Elf.

**How to reproduce:**
Complete Reinforecement for Loch Modan and u wont get a follow up quest

**How it should work:**
After completing Reinforecement for Loch Modan the follow up quest The Lost Pilot should be the next quest the npc shows to start the next quest chain

**Database links:**
https://www.wowhead.com/quest=26131/reinforcements-for-loch-modan
https://www.wowhead.com/classic/quest=419/the-lost-pilot

**Comment by Afgann** [comment]
This quest requires 'Hero's Call: Loch Modan!' to be done before. The series is shown here: https://www.wowhead.com/cata/quest=26854/the-lost-pilot. You can use cataclysm wowhead version instead of classic to get proper info.
