### ISSUE TITLE
Stonecore HC

### ISSUE THREAD

**Issue by maru0188** [gamefreedomgit/Maelstrom#6273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The spikes from Slabhide just spawn on people and they instantly die.

**How to reproduce:**

**How it should work:**

A shadow should be visable in order to dodge the pilllars, which will fall from the sky.
**Database links:**

**Comment by Sketish** [comment]
can you provide any video ?

**Comment by maru0188** [comment]
A GM can just watch a live group doing that boss.

I will not go back there to record until a fix has been implemented.

Sidenote: Queue to the stonecore can be up to 1 hour long as a dps which is terrible.

**Comment by Afgann** [comment]
fixed
