### ISSUE TITLE
Ascending the Vale not taking progress

### ISSUE THREAD

**Issue by Drakegamer456879** [gamefreedomgit/Maelstrom#6279]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
So im in Stonetalon on the quest ascending the vale and however i try to jump from stone to stone it doesnt take progression, i checked on youtube how to complete it and tried it the exact way yet it didnt progress.

**How to reproduce:**
On the quest Ascending the Vale jump from non of the higher standing rocks to on top of one the get the quest progression

**How it should work:**
Normally when u jump on top of one of the higher rocks the quest should auto complete

**Database links:**
https://www.youtube.com/watch?v=valWJRY0VwA

**Comment by Afgann** [comment]
fixed
