### ISSUE TITLE
Dustwallow Marsh - Main Questline Locked Behind Call to Arms! Quest [Alliance]

### ISSUE THREAD

**Issue by CaelumH420** [gamefreedomgit/Maelstrom#6280]
Description:
Dustwallow Marsh - Main Questline Locked Behind Call to Arms! Quest

How to reproduce:
Go to Theramore without having the Call to Arms! quest. Calia Hastings does not have any quests available.

How it should work:
Should not need a breadcrumb quest to do the main questline for the zone.  Should be like that for every zone.

Database links:
https://www.wowhead.com/cata/quest=27210/traitors-among-us

**Comment by Afgann** [comment]
fixed
