### ISSUE TITLE
Achievement "Prince of the Tides" bug

### ISSUE THREAD

**Issue by Hygin1** [gamefreedomgit/Maelstrom#6283]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
We can't complete the "[Prince of the Tides](https://www.wowhead.com/achievement=5286/prince-of-tides)" achievement : we keep the unyielding behemoth alive, kill everything else, but the 2nd phase isn't starting. We tried several times, with different groups, differents strats, nothing works.

We did a video : [https://www.youtube.com/watch?v=64S4SFojBJw](https://www.youtube.com/watch?v=64S4SFojBJw)

**How to reproduce:**
For the achievement, keep the Unyielding Behemoth alive until we grow up with the Tidal Surge fighting Ozumat then we can kill him. But the Tidal Surge only pops when we are in the 2nd phase... So impossible ! 

Maybe in the meantime give the achievement ? Or help us getting to the 2nd phase ?

Thank you :)

**Comment by Afgann** [comment]
fixed
