### ISSUE TITLE
Achievement King of the Spider-Hill

### ISSUE THREAD

**Issue by Rery795** [gamefreedomgit/Maelstrom#6287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**The secound to last spider is not in possition. When i kill him he spawns on upper platform but instantly falls to lower.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment]
Please provide screenshot or video

**Comment by Rery795** [comment]
![Uploading Snimka zaslona 2024-11-10 183553.png…]()

**Comment by Rery795** [comment]
![Snimka zaslona 2024-11-10 183553](https://github.com/user-attachments/assets/cae785a9-5b44-4655-8629-b54a74a592e2)

**Comment by Afgann** [comment]
fixed
