### ISSUE TITLE
Combat bug on dummy in Azshara

### ISSUE THREAD

**Issue by albernthegreat** [gamefreedomgit/Maelstrom#6291]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I'm in queue for Arena and I attacked the dummy at Azshara using the Gnaw pet skill first and tried to do some damage when the Arena popped up I moved away in the dummy and put my pet on passive but after so long the combat never gets rid. below is the link to the video as proof of the bug.

https://www.youtube.com/watch?v=Egf8UujmARs

**How to reproduce:**

**How it should work:**
It should remove the combat status after 10 seconds or so of not doing damage in the dummy.

**Database links:**

**Comment by Afgann** [comment]
fixed
