### ISSUE TITLE
Deepholm - Quest Hard Falls

### ISSUE THREAD

**Issue by Fried1** [gamefreedomgit/Maelstrom#6292]
**Description:**
Doing the Quest Hard Falls in Deepholm. I have to kill stone dragons. But every time I attack one, it gets elevated up in the air and I cant reach it.

The drake regenerates while flying and keeps the player in fight for a long time.
![grafik](https://github.com/user-attachments/assets/5f6435e5-45af-4b26-9447-a322e4841674)

Probably introduced by fixing number 21 of #6142 

**How to reproduce:**
Deepholm, The Pale Roost.

Stunned Stone Drakes on the ground rise up as soon as they are attacked. Only way to complete the quest as melee is to stun the drakes long enough or kill the one dragon that is on the ground, unstunned, with full hp.
![grafik](https://github.com/user-attachments/assets/1712e11f-99f1-4563-b9fe-d3944f8c1fd7)

**How it should work:**
Stunned dragons can be attacked on the ground
See https://www.youtube.com/watch?v=bjOFItgyppE&t=26s

**Database links:**

**Comment by Afgann** [comment]
fixed
