### ISSUE TITLE
Potion Master and Potion of illusion

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#6296]
Hello guys

https://www.wowhead.com/cata/item=58489/potion-of-illusion
this pot doesnt proc of Potion Master of alchemy
It already have 1-2 proc by its default - may be this dont allow it to proc From mastery.
I spend 300 to make. there is no other proc (3, 4, 5) instead 1-2 as it on default.

13.11.2024 Cataclysm nick Runesmith

**Comment by Sketish** [comment]
![image](https://github.com/user-attachments/assets/d09bc2e4-4005-4172-8311-209982e855a3)
 confirmed

**Comment by Afgann** [comment]
fixed
