### ISSUE TITLE
Chest from fishing doesn´t contain anything (First reported 2024-08-23 #6098)

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6297]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Chests you get when fishing is bugged and don´t contain any items. Instead the chest says "That slot is empty" when you open them. (You get nothing from them either!)
Here are some examples of chests that I know is bugged; "Battered Chest", "message in a bottle", "Waterlogged crate" and annotherone that is called "putlocker" or "footlocker"... something like that!

**How to reproduce:**
Get the fishing profession and start fishing for chests.

**How it should work:**
Chests you get from fishing should contain items.

**Database links:**

![WoWScrnShot_082324_225505](https://github.com/user-attachments/assets/45cdf55b-a9d2-454b-9d7e-6f8005e75a0d)
![WoWScrnShot_082324_225528](https://github.com/user-attachments/assets/3dbb2d9f-44f5-4a79-840f-161426e4d103)

![WoWScrnShot_082424_010159](https://github.com/user-attachments/assets/738f0cb0-7d1a-443e-9be3-1b0fee920ea3)
![WoWScrnShot_082424_010202](https://github.com/user-attachments/assets/f6ce52dd-941e-437a-8022-ef6d0c0942cd)

![WoWScrnShot_082424_010649](https://github.com/user-attachments/assets/b2b13c9c-41dc-4140-a122-3c24b46857a7)
![WoWScrnShot_082424_010652](https://github.com/user-attachments/assets/a924fdb5-156a-433c-8ef1-b38c3da96183)

![WoWScrnShot_091524_013251](https://github.com/user-attachments/assets/788f7ad2-c806-4af5-8f8e-ea68526a1aa8)

**Comment by Afgann** [comment]
fixed

**Comment by Hellbringar** [comment]
> fixed

Thanks!
What was wrong? (Why did this happen?)

**Comment by Afgann** [comment]
> > fixed
> 
> Thanks! What was wrong? (Why did this happen?)

There was no loot in the database, probably no one noticed that before or didn't report.
