### ISSUE TITLE
Fished up a reinforced create but it never got to my bag (First reported 2024-08-27 #6108)

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6298]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I was fishing in Darkmoon fair and looted a reinforced create, but it never got to my bag 
I don´t know if it matters but i do have the "auto loot" funktion on.

(at the time I did have space in the bag as you see in the picture)

**How to reproduce:**
Get the fishing profession and fish up a reinforced create with the auto loot funktion on.

**How it should work:**
The loot should get placed in your bag right away.

**Database links:**
![WoWScrnShot_082724_223535](https://github.com/user-attachments/assets/35f357d2-14e8-4990-b58c-421eada58d52)

**Comment by Afgann** [comment]
fixed
