### ISSUE TITLE
[Reputation] [The Aldor] [ More Venom Sacs]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Maelstrom#6299]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
[ More Venom Sacs] quest is not repeatable and not offered at the npc for BLOOD ELF

**How to reproduce:**
Take the quest and do it once , its not repeatable anymore

**How it should work:**
Should be repeatable quest.

**Database links:**
https://www.wowhead.com/tbc/quest=10019/more-venom-sacs
https://www.wowhead.com/tbc/guide/farming-fel-armanents-aldor-reputation-items-burning-crusade-classic

**Comment by Afgann** [comment]
fixed
