### ISSUE TITLE
BUG ON RAID DRAGON SOUL

### ISSUE THREAD

**Issue by jeanpyere** [gamefreedomgit/Maelstrom#6306]
Theys cant interrupted now, I believe the right thing to do would be to just stop them. interrupt (shadow gaze spell)
And if possible check if we can stun it still pls
I don't know if they should show the casting bar, when they contract, crouching down, it means they are casting the skill, I believe that being able to interrupt this is the right thing to do, I don't know if stuns like the druid and pally should work.
I know that stunning with the hunter trap and ignoring them the whole fight, as they were doing, is wrong.

![image](https://github.com/user-attachments/assets/f7f311be-7950-41ce-bea2-040f0c7ac8fd)

**Comment by Afgann** [comment]
Cast bar should be invisible from what i've found here: https://www.icy-veins.com/wow/warlord-zon-ozz-strategy-guide-normal-heroic

"Keep in mind that the Eyes of Go'rath can be interrupted when they are casting Shadow Gaze, thus reducing the raid damage. There is no cast bar for this spell, however, and you will have to interrupt blindly."

Interrupt issue is fixed and will be applied with next update.
