### ISSUE TITLE
breadth of frost - ragnaros heroic fight - firelands

### ISSUE THREAD

**Issue by jeanpyere** [gamefreedomgit/Maelstrom#6308]
on last phase (4) on [Breadth of Frost] ragnaros heroic fight, no need make triangule on classic

![image](https://github.com/user-attachments/assets/35ad2638-e42c-40eb-9885-f46498952c6d)

put in 9:40
https://youtu.be/KaT0J7ksZSY?si=I-mL9PK-8k4Zgmgz&t=580

**Comment by Sketish** [comment]
Because on classic it's post nerf version.
