### ISSUE TITLE
Achievement [Abuse the Ooze] in the Hall of stones dungeon

### ISSUE THREAD

**Issue by ornencha** [gamefreedomgit/Maelstrom#6310]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)
https://www.wowhead.com/cata/achievement=2155/abuse-the-ooze#

**Description:**
During the last boss encounter you have to let Malformed Oozes merge into Iron Sludges and kill 5 of theses Iron Sludges.

**How to reproduce:**
After the boss hitting 40% life or less Malformed Oozes starts spawning, and SHOULD merge when crossing path but nothing happens.

**How it should work:**
After the boss hitting 40% life or less Malformed Oozes starts spawning, and merge when crossing path.

some video on how it should works : https://www.youtube.com/watch?v=xMI3HyvH6SM
**Database links:**

**Comment by Afgann** [comment]
fixed
