### ISSUE TITLE
Glory of the Hero - ABUSE THE OOZE achievement BUG

### ISSUE THREAD

**Issue by TheRealHackerMan** [gamefreedomgit/Maelstrom#6313]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The Glory of the Hero achievement: Abuse the Ooze not working corrcetly. In Halls of Stone final boss fight, when Sjonnir the Ironshaper reaches 50% of health, he begins to spawn Oozes. The Oozes merge togather into 'Iron Ooze' after a few seconds. Well this part did not happen, even after. The Oozes just stand in middle of the area (not merging, as intended) and they disappear eventually after a while.

**How to reproduce:**
Fix the Oozes to merge properly into the desired 'Iron Ooze' which we need to kill to complete the achivement.

**How it should work:**
When Sjonnir the Ironshaper reaches 50% health, he should start spawning Oozes, the Oozes should MERGE into 'Iron Oozes', after killing 5 Iron Oozes during the bossfight, the achivement should be granted.

PM: The other achivement DEHYDRATION + ABUSE THE OOZE are the ONLY 2 that not working in Glory of the Hero! :)

**Database links:**
https://www.wowhead.com/achievement=2136/glory-of-the-hero
https://www.youtube.com/watch?v=x20nAu--cxI

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/6310
