### ISSUE TITLE
Quest "Counterattack!" Bugged

### ISSUE THREAD

**Issue by Emarcee-Q-Em** [gamefreedomgit/Maelstrom#6314]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**The quest https://www.wowhead.com/classic/quest=4021/counterattack is bugged, as none of the enemies are spawning.**

**Nothing happens once the quest is accepted.**

**As far as I understand, an event should occur wherein Kolkar centaurs spawn and begin to attack the Horde guards that are patroling near the bunker. After killing enough of them, a named centaur called Krom'zar should spawn, who then drops the banner item on the ground needed to complete the quest. It is possible that talking to the quest giver NPC should be the trigger for the quest.**

**https://www.wowhead.com/cata/quest=4021/counterattack**
**https://www.wowhead.com/cata/npc=9456/warlord-kromzar**

**Comment by Afgann** [comment]
fixed
