### ISSUE TITLE
Item ID 43639 Arthas' Gold Coin

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6315]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
This coin is impossible to catch. Either its catch chance is extremely low or it is missing from the loot table.

I've tried catching coins in three places, but this one is impossible at the moment. Please, if anyone has managed to catch it, at least share feedback.

**How is now:**
https://imgur.com/a/MkJjEhM

**How it should work:**
It should fished from fountain in Dalaran.

**Database links:**
https://www.wowhead.com/item=43639/arthas-gold-coin

**Comment by Afgann** [comment]
fixed
