### ISSUE TITLE
Vashj'ir - Shimmering expanse // *This item starts a quest* not working // Quest: Piece of the Past

### ISSUE THREAD

**Issue by BobSasZele** [gamefreedomgit/Maelstrom#6319]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
[Ancient Elven Etching](https://www.wowhead.com/cata/item=62281/ancient-elven-etching) drop from [Azsh'ir Patroller](https://www.wowhead.com/cata/npc=39638/azshir-patroller) and [Azsh'ir Infantry](https://www.wowhead.com/cata/npc=41227/azshir-infantry) doesn't start [Piece of the Past](https://www.wowhead.com/cata/quest=27716/piece-of-the-past). Instead I get the message "The quest is not available for your race.". The quest and item are Alliance version, no idea if it works for Horde [Ancient Elven Etching](https://www.wowhead.com/cata/item=62282/ancient-elven-etching) since they're different items.

This matches the report from an older thread [PTR Vashjir chainquest Alliance](https://github.com/gamefreedomgit/Maelstrom/issues/4758).
Interestingly there is a similarly named quest [Pieces of the past](https://www.wowhead.com/cata/quest=24495/pieces-of-the-past) for Worgen only. This is potentially relevant as I reproduce the bug with a Worgen character and don't know if there is a mismatch in the code due to the name similarity.

**How to reproduce:**
Force a drop from the aforementioned mobs with an Alliance character (Worgen in my case) and attempt to right-click activate the item to receive the quest and get the message instead.

**How it should work:**
It should start [Piece of the Past](https://www.wowhead.com/cata/quest=27716/piece-of-the-past).

**Database links:**
[Ancient Elven Etching](https://www.wowhead.com/cata/item=62281/ancient-elven-etching)
[Piece of the Past](https://www.wowhead.com/cata/quest=27716/piece-of-the-past)

Thanks in advance!

**Comment by AngryEndUser** [comment]
I also had this issue. After farming for approx. 2 hours, the item relevant to my faction dropped.

**Comment by BobSasZele** [comment]
> I also had this issue. After farming for approx. 2 hours, the item relevant to my faction dropped. Before that, the item of the opposite faction (which I cannot use) dropped ~5 times.

So it's likely the drop I've been getting is for Horde, hence the "wrong race" message.
Will try several more times, just in case.
Thanks for the info!

**Comment by BobSasZele** [comment]
So after a little farming the Alliance version of the quest item dropped and is working as intended.
My only recommendation at this point is to somehow filter the Alliance and Horde versions of the quest item into loot list only available for the respective faction. At the moment both versions can drop for the same character and the ratio for mine was 4 Horde ones before the correct Alliance one finally dropped.

**Comment by AngryEndUser** [comment]
> So after a little farming the Alliance version of the quest item dropped
Glad to hear it! At the time I didn't even know if the correct faction item would drop, so I was mindlessly farming for what felt like an eternity.

But yeah, the loot table for these mobs definitely needs a rework, it takes an insane amount of time to get the item.

**Comment by Afgann** [comment]
fixed
