### ISSUE TITLE
Quest "Counterattack!" Still Bugged

### ISSUE THREAD

**Issue by Emarcee-Q-Em** [gamefreedomgit/Maelstrom#6321]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**The quest https://www.wowhead.com/classic/quest=4021/counterattack was reported as fixed, but is still bugged, as none of the enemies are spawning.**

**Nothing happens once the quest is accepted. Interacting with the quest giver also does not spawn any enemies.**

**As far as I understand, an event should occur wherein Kolkar centaurs spawn and begin to attack the Horde guards that are patroling near the bunker. After killing enough of them, a named centaur called Krom'zar should spawn, who then drops the banner item on the ground needed to complete the quest. It is possible that talking to the quest giver NPC should be the trigger for the quest.**

![image](https://github.com/user-attachments/assets/74cf881a-51aa-4b2f-bca7-de00bda689a3)

**https://www.wowhead.com/cata/quest=4021/counterattack**
**https://www.wowhead.com/cata/npc=9456/warlord-kromzar**

**Comment by Afgann** [comment]
fixed
