### ISSUE TITLE
[Balance Druid] Typhoon's Effect Delay

### ISSUE THREAD

**Issue by lethiz** [gamefreedomgit/Maelstrom#6323]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
When I cast Typhoon on an enemy player, the knock and a dazing effect will happen after like a one second. It feels like a little delay. On Cata Classic Typhoon's effect happens like half a second sooner so it is easier to interrupt casting enemies and it feels more useful in big team fights. Because of that little delay on Maelstrom, sometimes I feel like it is not even worth to use Typhoon. 

**How to reproduce:**
Reduce the waiting time of Typhoon's effect by a half of the time or even make it instant (like it was on one of the previous servers where I played where when I used Typhoon, the effect was instant - enemy getting dazed and knocked back). 

**How it should work:**
Typhoon's effect should happen sooner. In the video from the link below, on the left side it is shown how Typhoon works on Maelstrom and on the right side it is shown how it works on Cata Classic. I should have change the speed of the video so it would be more clear to see the difference but YouTube offers an option to change the speed of the video. At 0.5 speed the difference is shown more clearly.

**Database links:**
https://www.youtube.com/watch?v=-bH1TdCuDOA

**Comment by Afgann** [comment]
fixed
