### ISSUE TITLE
[Balance Druid] 'Shooting Stars' Talent Bug

### ISSUE THREAD

**Issue by lethiz** [gamefreedomgit/Maelstrom#6324]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The problem with 'Shooting Starts' talent is that when I'm already casting one Starsurge and while casting I receive the proc, the first Starsurge that I'm casting will be sent but to send the second Starsurge from the proc (non-cast) I will have to wait 1 second. On all other Cataclysm server where I have played and currently on Cata Classic it works properly so when I'm casting Starsurge and I receive the proc  while casting, both the first casting Starsurge and the second non-cast Starsurge from the proc will be sent at the same time if I keep pressing Starsurge bind. Problem appears also when I receive Starsurge proc one after another so for example, when I have tons of dots on enemy targets and I receive a lot of Starsurge procs, let's say I receive one - I send the Starsurge and at the same time I receive another Starsurge proc. I won't be able to send one after another instantly but I will have to wait 1 second (sometimes it bugs worse and I have to wait even longer like 4-5 seconds).

**How to reproduce:**
Remove the cooldown on Starsurge if I have the proc and and I'm casting and sending first Starsurge so I can send the second at the same time, not having to wait 1 second or more.

**How it should work:**
It is shown how it should work on the video from the link below. On the left side it is shown how it works on Maelstrom and on the right side it is shown how it works on Cata Classic. It should work like on Cata Classic - when I'm casting a Starsurge and I receive the non-cast proc while casting I should be able to send both first casting Starsurge and the second non-cast Starsurge at the same time. (I recommend to change the speed of the video to 0.5 or even 0.25 so it is shown clearly what is the problem)

**Database links:**
https://www.youtube.com/watch?v=8JuUYly5q30

**Comment by Afgann** [comment]
fixed

**Comment by lethiz** [comment]
> fixed

Not exactly fixed. I just tested it and still - second Starsurge from the non cast proc can be sent 1 second after first Starsurge is sent. Both of them can't be sent simultaneously as they should be.

**Comment by Afgann** [comment]
fixed
