### ISSUE TITLE
[Spell] Worgen's 'Running Wild' Bug

### ISSUE THREAD

**Issue by lethiz** [gamefreedomgit/Maelstrom#6325]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
'Running Wild' spell that is Worgen's racial and works as a mount for this race does not look to work properly. It looks 'buggy' as you can see on the video from the link below. 0:00-0:21 shows how it looks like on Maelstrom and 0:22-0:46 shows how it should and how it works on Cata Classic. 

**How to reproduce:**
Fix 'Running Wild' animation to make it look "normal", just like on Cata Classic.

**How it should work:**
It should work like it works on Cata Classic.

**Database links:**
https://www.youtube.com/watch?v=cS984_EZJeQ

**Comment by lethiz** [comment]
Can we have it fixed? Please :)

**Comment by Afgann** [comment]
It looked like this on cataclysm, you can see it here: https://www.youtube.com/watch?v=MGCI5EpGgww.
Can't really do much, classic has new client and they added new animations there.
