### ISSUE TITLE
Quest: There's Something About The Squire

### ISSUE THREAD

**Issue by Uros2332** [gamefreedomgit/Maelstrom#6327]
**Description:**
When you use an item that should knock him it says "This spell is unavailable to you"

**How it should work:**
So you need to kill a hostile mob"Skeletal Woodcutter" right next to him and loot an useable item called "Large Femur" go behind a neutral NPC called "Maloric" and use it on him that will knock/dizzy him and you search and loot for "Murderer's toolkit". -Quest completed-  
https://www.youtube.com/watch?v=swqESasuGoU

**Note:** This is a mandatory quest for Argent Tournament questline into unlocking more quests this bug is preventing all of that. 
I tryed all angles into completing quest because I thought that was the problem but no its something else. 

**Screenshots:** https://prnt.sc/D-UCrWWkq5Kr ,

**My Solution:** If it requires a lot of work a simple solution for now that would allow people to advance into this huge content would simply be just killing him and looting it from him. 

**Database links:** https://www.wowhead.com/cata/quest=13654/theres-something-about-the-squire

**Comment by Afgann** [comment]
fixed
