### ISSUE TITLE
(Quest) To Battlescar! Bugged

### ISSUE THREAD

**Issue by Emarcee-Q-Em** [gamefreedomgit/Maelstrom#6329]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**The quest "To Battlescar!" is bugged. The Darnassian Glaive Throwers regenerate health rapidly as if permanently out of combat.**

**When a Darnassian Glaive Thrower is attacked, it will regenerate rapidly as if permanently out of combat. It does not matter if you are in the Krom'gar Demolisher or not.**

**The Darnassian Glaive Throwers should be killable, but effectively cannot be due to their out-of-combat regen being active.**

https://www.wowhead.com/cata/quest=26082/to-battlescar
https://www.wowhead.com/cata/npc=35150/darnassian-glaive-thrower

**Comment by Afgann** [comment]
fixed
