### ISSUE TITLE
Completed the dungeon "The Nexus" in HC-mode but didn´t get any achievement (First reported 2024-11-01 #6274)

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6341]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I completed the dungeon "The Nexus" in HC-mode with some guild members but didn´t get any achievement.
All the other players in the dungeon did get the achievment but not me.
The achievement i missed out on was "The Nexus", "Heroic The Nexus" & "Intense cold"
I was level 67 at the time.

**How to reproduce:**
Completed the dungeon "The Nexus" in HC-mode and see what happens when you complete it I guess.
Hard to tell you how to reproduce since it worked for everyone but me.

**How it should work:**
Efter you kill all bosses you get the achievements (Both for normal and HC-mode)

**Database links:**
(Look at the log in the pictures of what my teammates were rewarded)
![image](https://github.com/user-attachments/assets/3c3e88f9-4e6f-474d-962d-5ba7ed27162d)

![image](https://github.com/user-attachments/assets/971474f4-b44d-4aac-9a5b-65cbedd0682b)

![image](https://github.com/user-attachments/assets/cf866b20-db04-4068-baa1-ea8064701bb1)

**Comment by Sketish** [comment]
Please dont duplicate reports, vanilla-wotlk changes have low prio.
