### ISSUE TITLE
The XP gained from quests doesn´t match what you're supposed to receive (First reported 2024-08-05 #6063)

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6344]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Yesterday I talked with one of your GMs who asked me to compare xp from quests with what WoWhead tells us you're supposed to receive from that quest. I have now done some research and found out that in my case the questlog say that you will receive one set amount of xp, the NPC that you hand the quest in to say a different amount and then when I actually complete and hand in the quest i get i diffrent amount all togheter!

Example;
Quest - Totem of Tikti
Revarded xp for completion - 90xp (according to WoWhead)

My quest log said the reward was 94xp
NPC for completing a quest said the reward was 85xp
I received 93xp

(This is all done with the command. xp set 1, since I want to play as blizzlike as possible)

**How to reproduce:**
Complete some quest and compare what the quest log say the xp reward is to what quest completing NPC say and what xp you actually recive.

**How it should work:**
The .xp set X command should adjust the xp gaind accoring to the amount you tell it.

**Database links:**
![355230469-9bb9c450-c9a0-4d67-b847-5d24cbeb3588](https://github.com/user-attachments/assets/91d0213a-9a39-43ce-aa11-8f503bc14d7b)

![355230477-b02695ef-1603-4d3b-9bcb-b03cf817cc3c](https://github.com/user-attachments/assets/577e9058-00a2-4a70-8baa-6f7bdd54eea7)

![355230480-3d2a1bc5-68b8-4976-8475-a6e7e592402b](https://github.com/user-attachments/assets/8c93e6c6-d132-40e4-9c1f-c9b5cc548714)

![355230482-e4fa8271-b14b-4b8a-8384-086e4cb03cd3](https://github.com/user-attachments/assets/ca7df7e3-d085-45b9-bcd9-508dcf530585)

**Comment by Sketish** [comment]
Dont duplicate reports
