### ISSUE TITLE
Drix Blackwrench (Horde tundra mamoth The Fixer) Crystal Vial

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#6346]
Hello

This guys https://www.wowhead.com/cata/npc=32641/drix-blackwrench from horde travellers mamoth
doesnt selling https://www.wowhead.com/cata/item=3371/crystal-vial as it must to be.
Many many months cause nobody dont care DDD
this different between Horde and Ally
![WoWScrnShot_121224_201126](https://github.com/user-attachments/assets/01583031-8752-4e76-b4de-0c4b1672055f)
![WoWScrnShot_121224_201318](https://github.com/user-attachments/assets/05be2e5e-e330-4896-a82c-aea905dd925f)

**Comment by Afgann** [comment]
fixed
