### ISSUE TITLE
{QUEST} Emergency Protocol: Section 8.2, Paragraph D

### ISSUE THREAD

**Issue by BjarneBjarne** [gamefreedomgit/Maelstrom#6347]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
MINOR ISSUE as quest is completable:
Unable to scuttle any of the two northwestern wrecks as the quest requires you to do.
However, the southeasternmost wreck counts as a northwestern wreck for quest completion.

**How to reproduce:**
Play quest.

**How it should work:**
Should be able to scuttle either of the two northwestern wrecks, and the southeastern wreck should not count for the northwestern.

**Database links:**

**Comment by Afgann** [comment]
fixed
