### ISSUE TITLE
Alliance player can fly to Horde flight post

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6353]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I used a flight master and ended up at a Horde outpost and instantly got killed by their flight master and guards.
I flew from Shattarat City to Sanctum of the Stars

**How to reproduce: **
As an Alliance player, see if you can fly from a neutral or alliance flight post to a horde flight post (Sanctum of the Stars if you want to be specific)

**How it should work:**
Players should only be able to fly to their own factions flight posts to avoid this.

**Database links:**
![WoWScrnShot_121024_012303](https://github.com/user-attachments/assets/0383d45d-35f9-403a-9bbf-29f0b42ac119)

**Comment by Sketish** [comment]
That depends what faction you pick up during Shattrah quest City of Light. You either join aldor or scryers so it's not a bug

**Comment by Hellbringar** [comment]
> That depends what faction you pick up during Shattrah quest City of Light. You either join aldor or scryers so it's not a bug

I had joined up with the Aldor and could still fly there and as a result got killed. That is not how it's supposed to be?

**Comment by Sketish** [comment]
Well you can fly there because you have all fly paths unlocked.

**Comment by Hellbringar** [comment]
> Well you can fly there because you have all fly paths unlocked.

Okay, so no bug then?

**Comment by Sketish** [comment]
I wouldn't classify this as bug/
