### ISSUE TITLE
Fishing is bugged in Northrend - Borean Tundra

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6354]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
If you kill certain animals in Borean Tundra you get the "covered in blood" debuff, then you go to the coast and jump into the water to create a "pool of blood" this pool of blood is now a specific fishing spot for specific fish.

The problem is that you catch nothing, everything works just fine except that there is no fish on the hook even after you get the bite-animation and sound from the "indicator" 

**How to reproduce:**
Get the "covered in blood" debuff, then go to the coast and jump into the water to create a "pool of blood". Start fishing and see if you catch any fish.

**How it should work:**
If you kill certain animals in Borean Tundra you get the "covered in blood" debuff, then you go to the coast and jump into the water to create a "pool of blood" this pool of blood is now a specific fishing spot for specific fish.

**Database links:**
![WoWScrnShot_121424_023118](https://github.com/user-attachments/assets/c37fb519-7e83-4a8c-b518-57bbd6dad395)

**Comment by Afgann** [comment]
fixed
