### ISSUE TITLE
Highland Worg doesnt drop any greens

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#6359]
Hello

Highland Worg https://www.wowhead.com/cata/npc=46153/highland-worg
never drops greens( or any items). seems his drop broken.

![WoWScrnShot_121524_165910](https://github.com/user-attachments/assets/efd3bcd8-ff22-4663-841d-cc59a66dba36)
I noticed it many months ago.
https://www.wowhead.com/cata/item=67495/strange-bloated-stomach also doesnt drop from it.

**Comment by Ieluy** [comment]
Something wrong with loot . Need check it.

**Comment by Afgann** [comment]
fixed
