### ISSUE TITLE
[CATA] [Quest] Ignition

### ISSUE THREAD

**Issue by LopezJuanIgnacio** [gamefreedomgit/Maelstrom#6360]
**Description:**
When you go down the obelisk of sun, for the quest ignition, you'll be asked to use an item given by the quest in front a statue so it comes to life as an enemy so you can kill it, take an item and then finish the quest. The problem is that said npc is clipped into a pillar

**How to reproduce:**
Simply take the quest and go into the obelisk and you'll see how the statue is clipped

**How it should work:**
 You are supposed to use the item exactly at its feet so it activates into being a killable enemy, but since its clipped into a pillar higher than floor level you can't do it

**Database links:**
https://www.wowhead.com/cata/quest=27903/ignition

**Comment by Afgann** [comment]
fixed
