### ISSUE TITLE
[CATA] [Quest] To Fort Livingston/Bwemba's spirit

### ISSUE THREAD

**Issue by LopezJuanIgnacio** [gamefreedomgit/Maelstrom#6362]
**Description:**
Bwemba doesn't appear and the fort livingston is not phased correctly

**How to reproduce:**
Take both quests and head to Northern Stranglethorn

**How it should work:**
When entering Northern Stranglethorn Northern Stranglethorn should start folowing you and when you enter fort livingston you should be able to talk to Bwemba and the mariscal so you can finish both quests

**Database links:**
https://www.wowhead.com/cata/quest=29102/to-fort-livingston
https://www.wowhead.com/cata/quest=29100/bwembas-spirit

**Comment by Afgann** [comment]
From what i've read here: https://www.wowhead.com/cata/quest=29100/bwembas-spirit#comments:id=1400284.
Bwemba's spirit shouldn't be completeable in Fort Livingston.

Phasing is broken and will be fixed.

**Comment by Afgann** [comment]
fixed
