### ISSUE TITLE
Froststeel lockboxes contain nothing!

### ISSUE THREAD

**Issue by Hellbringar** [gamefreedomgit/Maelstrom#6364]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
When you unlock and open up a froststeal lockbox there is noting inside (Nothing gets looted or registered)

**How to reproduce:**
Unlock and open a froststeal lockbox

**How it should work:**
Froststeal lockboxes should contain loot

**Database links:**
https://www.wowhead.com/cata/item=43622/froststeel-lockbox#contains

**Comment by Afgann** [comment]
fixed
