### ISSUE TITLE
Xariona's Spectral Claws

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Maelstrom#6380]
Hello
this item https://www.wowhead.com/cata/item=67239/xarionas-spectral-claws#dropped-by
never drops from https://www.wowhead.com/cata/npc=50061/xariona
never see this item in game but this https://www.wowhead.com/cata/item=69876/xarionas-spectral-gauntlets
with lower chances -   much.

check drop and loot please

**Comment by Sketish** [comment]
Because rare  item is not longer obtainable, blizzard buffed 346 blues into epics to make wold bosses wortth killing
