### ISSUE TITLE
Undercity Patrols

### ISSUE THREAD

**Issue by WarlordXecc** [gamefreedomgit/Maelstrom#891]
Basically all NPCs that should patrol in Undercity are not. 
Below I've provided Screenshots of all the IDs and Spawn IDs through .npc info command.

![WoWScrnShot_092522_202914](https://user-images.githubusercontent.com/66841484/192160715-ba7f4cdd-3c61-42c4-9930-d0e1c1618faf.jpg)
![WoWScrnShot_092522_202917](https://user-images.githubusercontent.com/66841484/192160717-8ce974f3-d1a6-4203-a555-eb20df4742d5.jpg)
![WoWScrnShot_092522_203136](https://user-images.githubusercontent.com/66841484/192160719-2fa8421e-b6b6-4f62-8390-91e5dcc33225.jpg)
![WoWScrnShot_092522_203138](https://user-images.githubusercontent.com/66841484/192160720-9b328b42-4292-44b8-a55a-6120233ea597.jpg)
![WoWScrnShot_092522_203141](https://user-images.githubusercontent.com/66841484/192160722-6d171ff4-c50e-4a48-9993-b72db3642a0c.jpg)
![WoWScrnShot_092522_203155](https://user-images.githubusercontent.com/66841484/192160724-7dbd4246-77f0-4776-8a3b-aaf55fc76bbc.jpg)
![WoWScrnShot_092522_203204](https://user-images.githubusercontent.com/66841484/192160725-5c58f750-fd27-41a5-ba1c-bb040f0088c4.jpg)
![WoWScrnShot_092522_203211](https://user-images.githubusercontent.com/66841484/192160726-cdad1637-9011-41aa-823c-929ea7b13062.jpg)
![WoWScrnShot_092522_203214](https://user-images.githubusercontent.com/66841484/192160727-bcd751fb-19ae-46f2-891c-af6f5ca8275a.jpg)
![WoWScrnShot_092522_203216](https://user-images.githubusercontent.com/66841484/192160728-c6d4de45-d8b0-4d73-8a57-ec19478d911a.jpg)
![WoWScrnShot_092522_203218](https://user-images.githubusercontent.com/66841484/192160729-40dcf278-677a-4c12-a468-a0d2c241224e.jpg)
![WoWScrnShot_092522_203232](https://user-images.githubusercontent.com/66841484/192160730-6ea735c8-a3d4-4a6b-bc99-30ac5f1dc44e.jpg)
![WoWScrnShot_092522_203253](https://user-images.githubusercontent.com/66841484/192160731-3f1c3603-fc9e-40af-a09f-d4b1ad05b828.jpg)
![WoWScrnShot_092522_203301](https://user-images.githubusercontent.com/66841484/192160732-6e713a71-3569-460c-be0e-c90fb8da0736.jpg)
![WoWScrnShot_092522_203339](https://user-images.githubusercontent.com/66841484/192160733-cce94548-4ad1-4795-ac6c-242c5627e00d.jpg)
![WoWScrnShot_092522_203453](https://user-images.githubusercontent.com/66841484/192160734-e74c563b-8ab9-4151-bab5-600ece33d083.jpg)
![WoWScrnShot_092522_203459](https://user-images.githubusercontent.com/66841484/192160735-f9ca7292-6249-4017-b5e4-3a1c0298500f.jpg)
![WoWScrnShot_092522_203504](https://user-images.githubusercontent.com/66841484/192160736-32980d2a-d1e5-48ac-91a7-269d1fff990f.jpg)

**Comment by UltraNix** [comment]
Guards, bats and Kor'kron Overseers not fixed - lack of data.

**Comment by gaga-whitemane** [comment]
I will handle these.
