### ISSUE TITLE
Ironforge Patrols

### ISSUE THREAD

**Issue by WarlordXecc** [gamefreedomgit/Maelstrom#892]
Basically all NPCs that should patrol in Ironforge are not.
Below I've provided Screenshots of all the IDs and Spawn IDs through .npc info command.

![WoWScrnShot_092522_203546](https://user-images.githubusercontent.com/66841484/192160773-38f8fcd8-fbf4-4bb4-81a4-108c712d3e54.jpg)
![WoWScrnShot_092522_203550](https://user-images.githubusercontent.com/66841484/192160776-69297e17-9105-4b59-a2cd-6f43dbd07213.jpg)
![WoWScrnShot_092522_203600](https://user-images.githubusercontent.com/66841484/192160779-eec3ccd1-6332-430a-a658-a8ba0e59ff50.jpg)
![WoWScrnShot_092522_203603](https://user-images.githubusercontent.com/66841484/192160781-70c6ad66-efc5-4d0c-a524-2e6a5ec56cb0.jpg)
![WoWScrnShot_092522_203607](https://user-images.githubusercontent.com/66841484/192160782-0e8ed1ea-6fff-4847-86ed-8d92d52de5ec.jpg)
![WoWScrnShot_092522_203610](https://user-images.githubusercontent.com/66841484/192160783-d60fdd5f-1683-4b4b-9d90-d3e831a9e52b.jpg)
![WoWScrnShot_092522_203625](https://user-images.githubusercontent.com/66841484/192160784-8dffdccc-52ed-4132-aa1a-ebd34e8e632a.jpg)
![WoWScrnShot_092522_203630](https://user-images.githubusercontent.com/66841484/192160786-9ac570b8-2e43-420d-8e18-91af50a8d041.jpg)
![WoWScrnShot_092522_203632](https://user-images.githubusercontent.com/66841484/192160787-9286bf7f-cf0b-45b9-80fe-06bb81399961.jpg)
![WoWScrnShot_092522_203733](https://user-images.githubusercontent.com/66841484/192160788-90fcb4d2-3680-4e87-9dc3-a0814c3e63d1.jpg)
![WoWScrnShot_092522_203745](https://user-images.githubusercontent.com/66841484/192160790-fc5e2942-ce9e-4c01-9493-f92d2c72e2b1.jpg)
![WoWScrnShot_092522_203759](https://user-images.githubusercontent.com/66841484/192160791-1804b331-489c-4d2a-a5bb-0ba4967a2800.jpg)
![WoWScrnShot_092522_203816](https://user-images.githubusercontent.com/66841484/192160793-9433bb4f-2745-4f7e-b631-634bc83fb318.jpg)
![WoWScrnShot_092522_203821](https://user-images.githubusercontent.com/66841484/192160794-0a66ac4b-a621-4d77-ad10-5197f7029a57.jpg)
![WoWScrnShot_092522_203823](https://user-images.githubusercontent.com/66841484/192160795-9f80fb71-77a8-46ad-9a66-394202827b49.jpg)
![WoWScrnShot_092522_203826](https://user-images.githubusercontent.com/66841484/192160796-55568755-6481-4315-bf5d-dc44e496615b.jpg)
![WoWScrnShot_092522_203830](https://user-images.githubusercontent.com/66841484/192160797-e7cd6c4a-0b53-4bbc-bbe3-0f0c43e482a5.jpg)
![WoWScrnShot_092522_203837](https://user-images.githubusercontent.com/66841484/192160798-b2c2b837-30ad-4674-8438-d276e9e57c91.jpg)
![WoWScrnShot_092522_203840](https://user-images.githubusercontent.com/66841484/192160800-3a786f9a-cb66-4a2f-b6d0-5b25700d2126.jpg)
![WoWScrnShot_092522_203844](https://user-images.githubusercontent.com/66841484/192160802-31b97204-5958-40d2-a259-5f87259c7e00.jpg)
![WoWScrnShot_092522_203846](https://user-images.githubusercontent.com/66841484/192160804-75e636f2-2809-4485-8ebe-cd6dd31b49af.jpg)
![WoWScrnShot_092522_203848](https://user-images.githubusercontent.com/66841484/192160805-a5ea2e96-280c-4b24-8154-efe17569155d.jpg)
![WoWScrnShot_092522_203856](https://user-images.githubusercontent.com/66841484/192160807-ac3c99f3-c6ac-4957-99af-4b49ccee1725.jpg)
![WoWScrnShot_092522_203904](https://user-images.githubusercontent.com/66841484/192160808-be98ff75-4fff-4107-a447-cc469b4e0110.jpg)
![WoWScrnShot_092522_203929](https://user-images.githubusercontent.com/66841484/192160809-fd358888-321b-4447-8036-d4c3985180dc.jpg)
![WoWScrnShot_092522_203941](https://user-images.githubusercontent.com/66841484/192160810-ecd82b9f-453c-45eb-b08c-c4c38aa00333.jpg)
![WoWScrnShot_092522_204005](https://user-images.githubusercontent.com/66841484/192160811-84eb160d-ef81-4a1c-89ed-dba45861dbaa.jpg)
![WoWScrnShot_092522_204012](https://user-images.githubusercontent.com/66841484/192160812-57a01bc5-78af-4769-b810-e6a841724774.jpg)
![WoWScrnShot_092522_204017](https://user-images.githubusercontent.com/66841484/192160814-fe1a7ef9-650c-43af-a292-7c81ff43b021.jpg)
![WoWScrnShot_092522_204024](https://user-images.githubusercontent.com/66841484/192160816-ef663137-ef58-4329-b9b2-290e674b3737.jpg)
![WoWScrnShot_092522_204029](https://user-images.githubusercontent.com/66841484/192160817-58c7f3f9-fe32-4783-81e7-6bf67a502b92.jpg)
![WoWScrnShot_092522_204037](https://user-images.githubusercontent.com/66841484/192160818-7608220a-52c2-48ab-a529-44f8712a8972.jpg)

**Comment by UltraNix** [comment]
Ironforge guards not fixed - lack of data.

**Comment by gaga-whitemane** [comment]
I will handle these.
